dev: hoist generated code out of sandbox into workspace
cockroachdb/cockroach pull request #68663
Opened 2021-08-10 18:38 UTC by rickystewart

(Only the most recent commit applies for this review.)

One might be expected that this command be implemented as
`dev generate protobuf` or `dev generate execgen` or similar, but that's
not really practical for a couple reasons:

1. Building all the protobuf in-tree isn't really possible on its own:
   see #58018 (comment).
2. For non-proto generated code, one can imagine that we do a bunch of
   `bazel query`s to list all the generated files in tree and to find
   which files are generated. Given that there are hundreds of generated
   files in tree, and a single `bazel query` can take ~1s, this is not
   tractable.

The implementation here is ad-hoc and a bit hacky. Basically we search
`bazel-bin` for files ending in `.go` and apply some heuristics to
figure out whether they should be copied and where those files should
go.

This is gated behind a feature flag for now because actually copying
these files into the workspace right now dirties a ton of files. (The
diffs are benign -- mostly comments.) We can flip this option to be on
by default when it's safe (probably after the `Makefile` is deleted).

Closes #68565.

Release note: None

2021-08-10 18:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68663)
<!-- Reviewable:end -->

2021-08-11 22:10 UTC, rail requested changes
> Reviewed 15 of 15 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68663)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[pkg/cmd/dev/io/os/os.go, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68663#-MgrEvSsEuaocpTdvkPf:-MgrEvSt2KLC8RwkjAFG:b-9nlt6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bb44b82928b8002257cc285255703c5994f3a68/pkg/cmd/dev/io/os/os.go#L192)):*
> ```Go
> 	if o.Recording == nil {
> 		// Do the real thing.
> 		contents, err := ioutil.ReadFile(src)
> ```

Maybe use `io.Copy()` so you don't waste memory by reading the whole thing?


<!-- Sent from Reviewable.io -->

2021-08-11 22:59 UTC, rickystewart commented
> > Reviewed 15 of 15 files at r1, 6 of 6 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68663)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)
> 
> _[pkg/cmd/dev/io/os/os.go, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68663#-MgrEvSsEuaocpTdvkPf:-MgrEvSt2KLC8RwkjAFG:b-9nlt6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bb44b82928b8002257cc285255703c5994f3a68/pkg/cmd/dev/io/os/os.go#L192)):_
> 
> > ```go
> > 	if o.Recording == nil {
> > 		// Do the real thing.
> > 		contents, err := ioutil.ReadFile(src)
> > ```
> 
> Maybe use `io.Copy()` so you don't waste memory by reading the whole thing?

You're looking at the wrong PR, this is from the earlier one :) But yeah, fixed in both PR's now.

2021-08-12 01:40 UTC, rail approved these changes
> Reviewed 6 of 6 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68663)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2021-08-12 20:03 UTC, rickystewart commented
bors r=rail

2021-08-12 21:40 UTC, merged