colexec: interrupt parallel unordered sync local inputs when draining
cockroachdb/cockroach pull request #68677
Opened 2021-08-10 23:27 UTC by yuzefovich

This commit updates the parallel unordered synchronizer to interrupt
each local input when the synchronizer transitions into the draining
state. This is implemented by deriving a separate child context for each
local input with the corresponding context cancellation function.

Previously, whenever the synchronizer started draining, it would have
to wait for each input goroutine to finish the current `Next` call
before actually draining the metadata; now we won't have to wait for
local inputs anymore.

We cannot perform the context cancellation for the remote inputs (i.e.
those with `colrpc.Inbox` as a leaf) because the context cancellation
would break the gRPC stream making it impossible to fetch the remote
metadata. We thought that using the DrainSignal message sent by the
inbox to the outbox would solve the problem, but the difficulty is that
the main goroutine of the inbox is blocked on `stream.Recv` which
doesn't take a separate context object. Therefore, the only two ways to
unblock the main inbox goroutine are to cancel the stream context (thus
breaking the gRPC stream and making it unusable) or to wait for the
outbox to actually send something on the stream (like a non-zero length
batch or metadata, or actually close the stream for good). In any case,
it doesn't seem possible at the moment.

However, the existing change seems beneficial as is (we might reduce the
amount of work the local node will perform) and is sufficient for the
use case of parallel scans with the locality optimized search.

Release note: None

2021-08-10 23:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68677)
<!-- Reviewable:end -->

2021-08-11 19:53 UTC, yuzefovich commented
Alright, I think I fleshed out all the edge cases, RFAL.

2021-08-11 20:37 UTC, michae2 requested changes
It does seem a little weird to call `DrainMeta` and `Close` after the context has been cancelled, and this comment above `colexecop.Operator` does not inspire confidence:

```
	// Canceling the provided context results in forceful termination of
	// execution. The operators are expected to hold onto the provided context
	// (and derive a new one if needed) that is then used for Next(),
	// DrainMeta(), and Close() calls (when applicable).
```

I would feel better about this if context was only passed to `Next` instead of `Init`. Are there any operators that actually check context during `DrainMeta` and `Close`?

Maybe the context passed to `Init` is too broad for this usage? Maybe we need a "small" context that only applies to an individual call of `Next`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-:-MgqtlCA9yvvdAc2UTmz:b-y4979u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/parallel_unordered_synchronizer.go, line 283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-MgqsZ3VEubvNmMxTqjM:-MgqsZ3VEubvNmMxTqjN:bq6gkhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c3593ccfbd9552cdb660bb4ca0a0de836d11fea/pkg/sql/colexec/parallel_unordered_synchronizer.go#L283)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 							// TODO(yuzefovich): can we do better than the
> 							// string comparison?
> 							if strings.Contains(err.Error(), context.Canceled.Error()) ||
> 								strings.Contains(err.Error(), cancelchecker.QueryCanceledError.Error()) {
> ```
</details>


Could we use `errors.Is` for this check?

I wish the `context.WithCancel` func took an error as an argument. I wonder if we have something like that internally.


<!-- Sent from Reviewable.io -->

2021-08-12 02:19 UTC, yuzefovich reviewed
I think this is the first case where having separate contexts for `Next` and `DrainMeta/Close` seems useful. Originally, all of these methods were taking a context argument, but in #61223 and #61323 we changed the contract to always use the one coming from `Init`. Generally speaking I still think that it was the right decision because it cleaned up a lot of confusion in the general case.

> Are there any operators that actually check context during `DrainMeta` and `Close`?

Yeah, there are a handful of them. The context usage in `Close` doesn't seem worrisome to me because it is used primarily for logging purposes, and the fact that the context is canceled doesn't change anything for that. The more concerning part is `DrainMeta`, in particular in how it affects the tracing, stats collection, and LeafTxnFinalState (e.g. `ColBatchScan.DrainMeta`).

I have just audited this code, and I believe that everything should just work since the context is either used for logging or for propagating `context.Value`s, and both should work as if the context wasn't canceled. From my reading of the code, the context cancellation does several things: closes `Done` channel and sets the error, detaches the context from its parent, and cancels all of the children. Importantly, no `context.Value`s are changed. I feel a bit better now about this approach.

> Maybe the context passed to `Init` is too broad for this usage? Maybe we need a "small" context that only applies to an individual call of `Next`?

Yeah, I think in this particular scenario that could work well, possibly we could extend `Init` signature to take in two contexts - one for the whole lifetime of the `Operator` and one for long-running, possibly blocking operations (i.e. for `Next` implementations), then we'd have an option to cancel the latter context while we'd always use the former in `DrainMeta/Close`. However, that would be a pretty large mechanical change, and it would also introduce some confusion that we removed a few months ago. I would like to see several other example scenarios where this would be useful before going down that road.

If we don't feel comfortable merging this, I'd rather abandon this PR. Additionally, this PR would essentially be beneficial only if we start planning multiple table readers within the same flow (which I'm prototyping in #68679). If that PR doesn't get merged, there might not be enough justification to merge the current PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-:-Mgs1VX2C2M8XvK-uIc3:b-us0dg5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[pkg/sql/colexec/parallel_unordered_synchronizer.go, line 283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-MgqsZ3VEubvNmMxTqjM:-Mgs-5_70k5UZY8l0Ht-:b-t0q39a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c3593ccfbd9552cdb660bb4ca0a0de836d11fea/pkg/sql/colexec/parallel_unordered_synchronizer.go#L283)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 							// TODO(yuzefovich): can we do better than the
> 							// string comparison?
> 							if strings.Contains(err.Error(), context.Canceled.Error()) ||
> 								strings.Contains(err.Error(), cancelchecker.QueryCanceledError.Error()) {
> ```

Could we use `errors.Is` for this check?

I wish the `context.WithCancel` func took an error as an argument. I wonder if we have something like that internally.
</blockquote></details>

Hm, I was thinking about it too but was afraid to try it.

(I think `errors.Is` might not work correctly across the node boundaries (because the gRPC somehow modifies the error) unless you make sure that the errors implement some additional decoding methods, and previously - if I'm not mistaken - we had to fallback to the string comparison in some cases. Also, it doesn't work when the error is returned from lib/pq.)

However, here we need to check this for local only operator trees, and I think `errors.Is` should work. I've stressed a couple of tests, and this seems to work. Done.


<!-- Sent from Reviewable.io -->

2021-08-12 03:38 UTC, yuzefovich commented
I added a unit test for the eager cancellation as well as a tiny another commit.

2021-08-12 12:17 UTC, knz reviewed
I'm not sure I see the value of the 2nd commit (if anything, it'll make it hard for someone to add some additional logging later),
but that commit <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  nonetheless on behalf o the KV team.

I did not look at the 1st commit

> Reviewed 2 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-:-MguHrWVCfPj1n7E697r:b-s8l1b3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)



<!-- Sent from Reviewable.io -->

2021-08-12 15:05 UTC, yuzefovich commented
The unused context argument was something I noticed while auditing how contexts are being used when the flow is being drained, and I thought I could clean it up all the way for `execinfra.MisplannedRanges` but couldn't, so I don't see much value in the second commit either. Removed.

2021-08-12 19:27 UTC, michae2 approved these changes
Thanks for the context, it helps. (Pun not intended.) I'm comfortable merging this.

An alternative idea I had was: change all `DrainableOperator`s to make `DrainMeta` callable concurrently with `Next`, so that `DrainMeta` itself could be used for this type of "small" cancellation. But the more I thought about that idea, the worse it seemed. Lots of complexity for a small gain.

Maybe a simpler alternative idea would be to add a `CancelNext()` method to `Operator` (callable concurrently with `Next`). For most operators this method would be a no-op, but blocking operators would have to use a channel internally, very similar to but distinct from `ctx.Done()`.

But I think this is splitting hairs with your current approach, which is fundamentally very similar and is less work. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 10 files at r1, 1 of 3 files at r2, 1 of 1 files at r5, 1 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-:-MgvOvj96IJ1kvgU2SQX:b7fl7a)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/parallel_unordered_synchronizer.go, line 135 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-Mgv_Mt517YoyqpwRmaE:-Mgv_Mt517YoyqpwRmaF:b-kvef9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a05ea2a86023b36f15d0c1ed933ddf7e586ebd/pkg/sql/colexec/parallel_unordered_synchronizer.go#L135)):*
> ```Go
> // zero-length batch received from Next.
> func NewParallelUnorderedSynchronizer(
> 	inputs []colexecargs.OpWithMetaInfo, wg *sync.WaitGroup, usesFakeSpanResolver bool,
> ```

nit: Instead of passing this to the constructor, could we make it an exported field so that tests can set it without having to teach the rest of the system about it?
___
*[pkg/sql/colexec/parallel_unordered_synchronizer_test.go, line 175 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-Mgvoxd07CBgoCFF_w_q:-Mgvoxd07CBgoCFF_w_r:bakqpj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a05ea2a86023b36f15d0c1ed933ddf7e586ebd/pkg/sql/colexec/parallel_unordered_synchronizer_test.go#L175)):*
> ```Go
> 				meta := s.DrainMeta()
> 				actualDuration := timeutil.Since(start)
> 				require.True(t, actualDuration < blockDuration/2)
> ```

nit: Do we need this check? Won't raising the "unexpectedly slept for a second" error in the callback operator accomplish the same thing?


<!-- Sent from Reviewable.io -->

2021-08-12 21:02 UTC, yuzefovich reviewed
Previously, we actually allowed the concurrent calls to `Next` and `DrainMeta`, but it turned out to be error-prone, so overtime we refactored to prohibit the concurrency between those, and I think it's simpler this way.

`CancelNext` idea sounds interesting but also seems like a pretty large undertaking.

Happy you're on board as is :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-:-Mgw99YDAZUP1GTCXgp2:b-ude1fu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz and @michae2)

___
*[pkg/sql/colexec/parallel_unordered_synchronizer.go, line 135 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-Mgv_Mt517YoyqpwRmaE:-Mgw82NKAsALYNyZG_EH:bjjviap) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a05ea2a86023b36f15d0c1ed933ddf7e586ebd/pkg/sql/colexec/parallel_unordered_synchronizer.go#L135)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Instead of passing this to the constructor, could we make it an exported field so that tests can set it without having to teach the rest of the system about it?
</blockquote></details>

Hm, good question. If I understand your idea correctly, we would have an exported global variable (e.g. `execinfra.UsesFakeSpanResolver`) which we would update in `DistSQLPlanner.SetSpanResolver` accordingly; then, when creating the parallel unordered sync we would just take a look at that variable.

I don't think this will work because we're running the logic tests concurrently (meaning both "fake" and "non-fake" configs simultaneously), so IIUC there will be a race between setting a fake span resolver and unsetting it. Did you have something like this in mind?
___
*[pkg/sql/colexec/parallel_unordered_synchronizer_test.go, line 175 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-Mgvoxd07CBgoCFF_w_q:-Mgw5-sR2Q-ouDAvrGfW:b-3630se) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a05ea2a86023b36f15d0c1ed933ddf7e586ebd/pkg/sql/colexec/parallel_unordered_synchronizer_test.go#L175)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Do we need this check? Won't raising the "unexpectedly slept for a second" error in the callback operator accomplish the same thing?
</blockquote></details>

Yep, good point, removed.


<!-- Sent from Reviewable.io -->

2021-08-12 21:18 UTC, michae2 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68677)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz, @michae2, and @yuzefovich)

___
*[pkg/sql/colexec/parallel_unordered_synchronizer.go, line 135 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-Mgv_Mt517YoyqpwRmaE:-MgwBulr1_xXVkcpm5ji:b-mcprt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a05ea2a86023b36f15d0c1ed933ddf7e586ebd/pkg/sql/colexec/parallel_unordered_synchronizer.go#L135)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, good question. If I understand your idea correctly, we would have an exported global variable (e.g. `execinfra.UsesFakeSpanResolver`) which we would update in `DistSQLPlanner.SetSpanResolver` accordingly; then, when creating the parallel unordered sync we would just take a look at that variable.

I don't think this will work because we're running the logic tests concurrently (meaning both "fake" and "non-fake" configs simultaneously), so IIUC there will be a race between setting a fake span resolver and unsetting it. Did you have something like this in mind?
</blockquote></details>

Oh, I meant change `ParallelUnorderedSynchronizer.usesFakeSpanResolver` to `ParallelUnorderedSynchronizer.UsesFakeSpanResolver` and then set it in `vectorized_flow.go` after calling `NewParallelUnorderedSynchronizer` instead of calling `NewParallelUnorderedSynchronizer` with `false /* usesFakeSpanResolver */` everywhere except one spot. But it's just a nit, doesn't really matter.


<!-- Sent from Reviewable.io -->

2021-08-12 21:35 UTC, yuzefovich reviewed
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-:-MgwHSAJ3pwTeX1a79Zi:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz and @michae2)

___
*[pkg/sql/colexec/parallel_unordered_synchronizer.go, line 135 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68677#-Mgv_Mt517YoyqpwRmaE:-MgwHF3o6p2QjvPhqBlu:b9lzju5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a05ea2a86023b36f15d0c1ed933ddf7e586ebd/pkg/sql/colexec/parallel_unordered_synchronizer.go#L135)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Oh, I meant change `ParallelUnorderedSynchronizer.usesFakeSpanResolver` to `ParallelUnorderedSynchronizer.UsesFakeSpanResolver` and then set it in `vectorized_flow.go` after calling `NewParallelUnorderedSynchronizer` instead of calling `NewParallelUnorderedSynchronizer` with `false /* usesFakeSpanResolver */` everywhere except one spot. But it's just a nit, doesn't really matter.
</blockquote></details>

Oh, I see, good point, done.


<!-- Sent from Reviewable.io -->

2021-08-13 01:19 UTC, merged