[WIP] sql: add descriptions of jobs that are created during DROP CASCADE
cockroachdb/cockroach pull request #68717
Opened 2021-08-11 18:01 UTC by sajjadrizvi

Previously, job descriptions were empty for the jobs that were
created during DROP CASCADE. This commit adds job descriptions.

Release note: None

Fixes: #59221

2021-08-24 12:57 UTC, ajwerner reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68717)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sajjadrizvi)

___
*[pkg/sql/drop_table.go, line 578 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-MhsDvvgE6AfcMYS_LYN:-MhsDvvgE6AfcMYS_LYO:b-rpw02e) ([raw file](https://github.com/cockroachdb/cockroach/blob/674df4c595237fcd3e6294f7fe2441d4d13c3d17/pkg/sql/drop_table.go#L578)):*
> ```Go
> 		return err
> 	}
> 	jobDesc := fmt.Sprintf("removing FK %s for back-reference in cascade", ref.Name)
> ```

Can you add information about the tables involved? Also, I don't think this `for back-reference` language is very clear. Does it have clear meaning to you?


<!-- Sent from Reviewable.io -->

2021-08-24 16:19 UTC, sajjadrizvi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68717)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/drop_table.go, line 578 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-MhsDvvgE6AfcMYS_LYN:-MhsmcG34s54bQncTWsY:bn5rg2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/674df4c595237fcd3e6294f7fe2441d4d13c3d17/pkg/sql/drop_table.go#L578)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you add information about the tables involved? Also, I don't think this `for back-reference` language is very clear. Does it have clear meaning to you?
</blockquote></details>

No, I thought it's clear to other and it's only me who gets confused with `back-reference` term. 


<!-- Sent from Reviewable.io -->

2021-08-27 20:16 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68717)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @sajjadrizvi)

___
*[pkg/sql/drop_table.go, line 578 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-MhsDvvgE6AfcMYS_LYN:-Mi8FRu10wzO203j81Z1:b-88vqzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/674df4c595237fcd3e6294f7fe2441d4d13c3d17/pkg/sql/drop_table.go#L578)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

No, I thought it's clear to other and it's only me who gets confused with `back-reference` term. 
</blockquote></details>

let's look up fully qualified names here. 

nit: use the word `referenced by` 
___
*[pkg/sql/drop_table.go, line 637 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-Mi8FILf5_GwoWTqkCyT:-Mi8FILf5_GwoWTqkCyU:b-o1c9tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/988fa5905f37fd3edf04339cfa332347df244547/pkg/sql/drop_table.go#L637)):*
> ```Go
> 		return err
> 	}
> 	jobDesc := fmt.Sprintf("removing outbound FK %s from table %s(%d), referring to table %s(%d)",
> ```

let's look up fully qualified names here. 

nit: use the word `referencing` 


<!-- Sent from Reviewable.io -->

2021-09-02 20:47 UTC, sajjadrizvi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68717)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/drop_table.go, line 578 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-MhsDvvgE6AfcMYS_LYN:-MicFPik4BMDaZaM25aG:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/674df4c595237fcd3e6294f7fe2441d4d13c3d17/pkg/sql/drop_table.go#L578)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

let's look up fully qualified names here. 

nit: use the word `referenced by` 
</blockquote></details>

OK
___
*[pkg/sql/drop_table.go, line 637 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-Mi8FILf5_GwoWTqkCyT:-MicFlsqB21_p_Ny5EIq:b2nhktp) ([raw file](https://github.com/cockroachdb/cockroach/blob/988fa5905f37fd3edf04339cfa332347df244547/pkg/sql/drop_table.go#L637)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

let's look up fully qualified names here. 

nit: use the word `referencing` 
</blockquote></details>

OK.


<!-- Sent from Reviewable.io -->

2021-09-08 18:53 UTC, ajwerner reviewed
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68717)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @sajjadrizvi)

___
*[pkg/sql/drop_table.go, line 637 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-Mi8FILf5_GwoWTqkCyT:-Mj5jvpo2zLP5K3Adt-g:bdj0c4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/988fa5905f37fd3edf04339cfa332347df244547/pkg/sql/drop_table.go#L637)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

nit: lose the `to` between `referencing` and `table`. Also, I don't think we want these ID numbers in these messages. If an engineer wants the IDs they can decode them from the descriptor or namespace table. Also, remove the `,` so: `removing outbound FK %s from table %s referencing table %s`
___
*[pkg/sql/drop_table.go, line 586 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-Mj5jr419qjKqQd27nH6:-Mj5jr419qjKqQd27nH7:b-ovwfah) ([raw file](https://github.com/cockroachdb/cockroach/blob/c621ead9cf9f6290ae3bb695fdb17f505da1ef29/pkg/sql/drop_table.go#L586)):*
> ```Go
> 		return err
> 	}
> 	jobDesc := fmt.Sprintf("removing inbound FK %s from table %s(%d), referenced by table %s(%d)",
> ```

nit: `removing inboud FK %s from table %s referenced by table %s`


<!-- Sent from Reviewable.io -->

2021-09-13 14:17 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-:-MjUWHe4EXRatTXJ19YA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sajjadrizvi)



<!-- Sent from Reviewable.io -->

2021-09-13 16:26 UTC, postamar requested changes
As it is the GC job descriptions can get a bit hard to read as the job descriptions which comprise it get concatenated simply with `;` instead of `; `, plus the descriptions are a bit verbose. Here's what I get for `DROP DATABASE movr CASCADE` in `cockroach demo`: 

```
demo@127.0.0.1:26257/defaultdb> SELECT description FROM [SHOW JOBS] WHERE job_type = 'SCHEMA CHANGE GC';
                                                                                                                description
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  GC for removing outbound FK fk_vehicle_city_ref_vehicles from table movr.public.rides referencing table movr.public.vehicles;removing inbound FK fk_city_ref_users from table movr.public.users referenced by table movr.public.vehicles
  GC for removing outbound FK fk_city_ref_users from table movr.public.rides referencing table movr.public.users;removing outbound FK fk_city_ref_users from table movr.public.user_promo_codes referencing table movr.public.users
  GC for removing inbound FK fk_city_ref_rides from table movr.public.rides referenced by table movr.public.vehicle_location_histories
  GC for DROP DATABASE movr CASCADE
(4 rows)
```

Obviously this is an improvement over what there was previously (i.e. nothing) but it's a bit verbose. It's also burying the lede: the jobs in this example pertain, respectively, to tables `vehicles`, `users` and `vehicle_location_histories` but that's not immediately obvious.

More worryingly, the job description string can potentially become quite long and I'm concerned that it's essentially unbounded in length. I understand that these job descriptions just get stuff appended to them (interspersed with `;`) but it seems like it'd be worth adding some code in the `AppendDescription` of `Record` that keeps the job description length under a certain upper bound. After a few hundred characters it's probably fine to end the description with `[...]` or whatever to indicate it's been truncated. More sophisticated things are possible of course, I don't think it's worth investing too much time in making something fancy as long as it conveys useful information without growing too large.

2021-09-13 17:44 UTC, sajjadrizvi reviewed
It is indeed verbose, but it also adds clarity when tables can have same names in different databases and schemas. May be we can add some decorations and remove the `table` word. For example, 

```
  GC for removing outbound FK 'fk_vehicle_city_ref_vehicles' from 'movr.public.rides' referencing 'movr.public.vehicles';removing inbound FK 'fk_city_ref_users' from 'movr.public.users' referenced by 'movr.public.vehicles'
  GC for removing outbound FK 'fk_city_ref_users' from 'movr.public.rides' referencing 'movr.public.users';removing outbound FK fk_city_ref_users from 'movr.public.user_promo_codes' referencing 'movr.public.users'
  GC for removing inbound FK 'fk_city_ref_rides' from 'movr.public.rides' referenced by 'movr.public.vehicle_location_histories'
```

It helps a little! What do you think?

I was also concerned about the length of descriptions when we added `JobRecords`. How many descriptions we potentially append? I guess we don't go too deep. Nevertheless, we should limit their length, and may be prepend them instead of append so that most relevant description appears first (assuming that recent descriptions are more relevant). I guess we should address this h in another PR.

Good point about `;` vs `; `.  Should I add the space in this PR?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-:-MjVA6TXE_hJ7hZTp6cn:b3bpl4i)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)

___
*[pkg/sql/drop_table.go, line 588 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-MgqN4pVmScvk5uO8S5c-r6-588:-MjVA5RC4bLLoH7DmNHb:b9cedjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/393e3d1fbb3960fe48f706dcb600cc60d7e635eb/pkg/sql/drop_table.go#L588)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Don't forget to remove this.
</blockquote></details>

Done. Thanks for catching it.
___
*[pkg/sql/drop_table.go, line 656 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-MgqN4pVmScvk5uO8S5c-r6-656:-MjVA5GYDU4aepeTV5fJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/393e3d1fbb3960fe48f706dcb600cc60d7e635eb/pkg/sql/drop_table.go#L656)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-13 18:08 UTC, postamar commented
I'm OK with doing a follow-up PR as long as you bound the job description length somehow in this PR.

2021-09-13 20:40 UTC, sajjadrizvi reviewed
OK. I will add a limit to description length in this PR. It should be in `AppendDescription`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-:-MjVrHcJ93kbISXyrQXK:b-tqebwn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)



<!-- Sent from Reviewable.io -->

2021-09-13 21:31 UTC, ajwerner commented
None of the removing ... should say `GC`, right? `GC` is about waiting for a TTL, these are about running the schema changer. Where did the `GC` come from?

2021-09-13 21:31 UTC, ajwerner commented
Oh, I see, that's horrible, after we drop the database, we then go and take the verbatim description and plop it into the GC job. I think we're doing something very wrong here.

2021-09-13 21:32 UTC, ajwerner commented
I feel like at it's core, we have to ask, why are there 4 GC jobs in the motivating issue?

2021-09-13 21:33 UTC, ajwerner commented
I feel like this is going to reveal something deeper where we're creating jobs we should not be.

2021-09-14 01:26 UTC, postamar reviewed
The way I understand it, we create these schema change jobs as part of the DROP ... CASCADE to remove FK references (among others perhaps). I'll admit I've never questioned myself whether these were necessary, or even legit. 

After looking into it a bit more it seems that this is an artifact of the schema change state machine: removing FK references triggers a `SCHEMA CHANGE` job which walks through the state machine which at some point notices that the table in question is being dropped and so, hey, this table therefore also requires a GC job, so it triggers a `SCHEMA CHANGE GC` job here: https://github.com/cockroachdb/cockroach/blob/0c50eeeee2aa861d58db06978c73b4c9579d0ac1/pkg/sql/schema_changer.go#L657

I may be wrong (it's late) but I agree with @ajwerner that something deeper's not right here. @sajjadrizvi as far as this PR is concerned I'd say it's fine to merge it as-is, except for the fact that your `TestDescriptionInDropCascade` test is asserting on a job description string which we now realize is not correct. I'd be fine with removing that test altogether, or instead of having a `description LIKE` clause on something which we now know is incorrect, perhaps instead assert on the results of `SELECT count(DISTINCT description) FROM [SHOW JOBS] WHERE job_type = 'SCHEMA CHANGE GC'`

2021-09-14 01:26 UTC, postamar commented on pkg/sql/drop_test.go
> +		sqlRun.QueryRow(t, `SELECT count(*) FROM [SHOW JOBS] WHERE description LIKE 'removing outbound FK %' AND status = 'succeeded'`).Scan(&count)
I didn't notice this the first time around but I think you need to add a `job_type = 'SCHEMA CHANGE GC'` to your `WHERE` clause, and update the comment three lines above which is now out of date.

2021-09-14 14:26 UTC, sajjadrizvi reviewed
OK, I can assert using the query that you have shared. To understand correctly, why the assertion on the current description is incorrect for only this test? The test is about verifying that the descriptions that we have added surface in the table as desired. Would counting distinct descriptions sufficient or relevant for this test?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-:-MjZcnKI3WN9Vp2WKuH3:b89veg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)

___
*[pkg/sql/drop_test.go, line 1383 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-MgqN4pVmScvk5uO8S5d-r7-1383:-MjZcXX75onDkBOTUyOH:b-6y9rcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e46e363ec2837ec3f823676e2825a9d3f1ea29/pkg/sql/drop_test.go#L1383)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I didn't notice this the first time around but I think you need to add a `job_type = 'SCHEMA CHANGE GC'` to your `WHERE` clause, and update the comment three lines above which is now out of date.
</blockquote></details>

OK, I am updating.


<!-- Sent from Reviewable.io -->

2021-09-14 18:57 UTC, postamar commented
It's only incorrect in that as of yesterday we realized that it doesn't make sense for a garbage-collection job, which removes actual records from storage, to mention foreign keys at all. The description string is therefore a bit nonsensical. I feel that adding a test that checks that the description string talks about foreign keys sends a confusing message because it implicitly signals that this is something we want, when we strongly suspect that it's not.

It's not a huge deal either way, I just think it's good practice to be kind to our future selves: we _plan_ to do follow-up work on this and investigate something that's very suspicious like @ajwerner noticed but we don't know when we're going to do it and we shouldn't assume it's going to be soon or even done by one of us three.

2021-09-14 20:14 UTC, sajjadrizvi reviewed
>  it doesn't make sense for a garbage-collection job, which removes actual records from storage, to mention foreign keys at all

I didn't get this point before. Now I understand. Thanks for the clarification.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68717#-:-Mj_vw6GBOi-w3UZVrXy:b-ty402l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)



<!-- Sent from Reviewable.io -->

2021-09-24 14:43 UTC, closed without merging