ui: Add date range selector in statements page
cockroachdb/cockroach pull request #68831
Opened 2021-08-12 21:35 UTC by xinhaoz

Related to #68089

Release note (ui change): This commit adds date range state
properties and a date range selector component to the DB
console's statements page. This change is necessary to
support surfacing persisted statistics in the DB console.

2021-08-12 21:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68831)
<!-- Reviewable:end -->

2021-08-24 22:33 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 232 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MhuHgjACjDAnB8gj75I:-MhuHgjACjDAnB8gj75J:b-24rm30) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5fcdde2ce12727595e00def1a9ee90b838d8c26/pkg/ui/src/views/statements/statementsPage.tsx#L232)):*
> ```XML
>       // We currently don't have the support for determining the bounds
>       // of persisted statement data, aside from issuing a get all.
>       validStatementsDateRange: [
> ```

I don't we should limit one year or trying to find the oldest data. The picker itself can go back as far as possible and the user selects what makes more sense.  Is common to have a selector going back more than you have data for, we simply show what we have
(make that change on the other statementsPage too, so have older data range)


<!-- Sent from Reviewable.io -->

2021-08-25 14:17 UTC, matthewtodd reviewed
A tour de force, nice work!

I am wondering whether we want to expose this "combined" concept up through the API, or whether we see it more as an implementation detail of The Future way to view statements, in which case maybe we take over the existing `/_status/statements` endpoint, making the "combined" behavior opt-in with a query parameter for now, but eventually making "combined" the default?

What do you all think?

> Reviewed 1 of 19 files at r3, 11 of 34 files at r5, 35 of 35 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-:-Mhxd_Xj3BnrDKrgXB26:b-kheaqx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)



<!-- Sent from Reviewable.io -->

2021-08-26 00:02 UTC, maryliag reviewed
> Reviewed 1 of 35 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd and @xinhaoz)

___
*[pkg/ui/cluster-ui/src/statementsPage/statementsPage.selectors.ts, line 49 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MhzjoEj4S0op1vSxZq7:-MhzjoEj4S0op1vSxZq8:b7mvgov) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f4c336e2b8fc2ba657442ad52766f8dd323c1d/pkg/ui/cluster-ui/src/statementsPage/statementsPage.selectors.ts#L49)):*
> ```XML
> export const statementsSelector = createSelector(
>   adminUISelector,
>   adminUiState => adminUiState.combinedStatements,
> ```

you may need to change back to .statements, otherwise it may not work as expected on the cases you're calling the statements api
___
*[pkg/ui/cluster-ui/src/statementsPage/statementsPageConnected.tsx, line 59 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mhzk3Fb2yUucHQASRff:-Mhzk3Fb2yUucHQASRfg:b37emox) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f4c336e2b8fc2ba657442ad52766f8dd323c1d/pkg/ui/cluster-ui/src/statementsPage/statementsPageConnected.tsx#L59)):*
> ```XML
>     }),
>     (dispatch: Dispatch) => ({
>       refreshStatements: () => dispatch(combinedStatementActions.refresh()),
> ```

similar to previous comments, we won't be refreshing combined on all cases, so might need to handle here too
___
*[pkg/ui/src/redux/statements/statementsSelectors.ts, line 18 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MhzkcYD3p1K9OWMRJB6:-MhzkcYD3p1K9OWMRJB7:b-hks1z6) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f4c336e2b8fc2ba657442ad52766f8dd323c1d/pkg/ui/src/redux/statements/statementsSelectors.ts#L18)):*
> ```XML
> 
> export const selectStatementByFingerprint = createSelector(
>   (state: AdminUIState) => state.cachedData.combinedStatements.data?.statements,
> ```

similar to the other comments
___
*[pkg/ui/src/views/statements/statementDetails.tsx, line 153 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mhzkm8q3MMEaP3V1Zp5:-Mhzkm8q3MMEaP3V1Zp6:b-uzgc1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f4c336e2b8fc2ba657442ad52766f8dd323c1d/pkg/ui/src/views/statements/statementDetails.tsx#L153)):*
> ```XML
> 
> export const selectStatement = createSelector(
>   (state: AdminUIState) => state.cachedData.combinedStatements,
> ```

same comment as other cases
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 67 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MhzkpsR-C-eiP9w1lr8:-MhzkpsR-C-eiP9w1lr9:bq4psf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f4c336e2b8fc2ba657442ad52766f8dd323c1d/pkg/ui/src/views/statements/statementsPage.tsx#L67)):*
> ```XML
> // StatementsPage, based on if the appAttr route parameter is set.
> export const selectStatements = createSelector(
>   (state: AdminUIState) => state.cachedData.combinedStatements,
> ```

same as others


<!-- Sent from Reviewable.io -->

2021-08-26 05:34 UTC, Azhng reviewed
Nice. Great work on this. Just some quick drive-by comments. 

Also, do you mind put some screenshots into the PR description ?

> Reviewed 1 of 19 files at r3, 11 of 34 files at r5, 4 of 35 files at r6, 3 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-:-Mhviz_P7gWFGNp-BmfU:b-s5bm2f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd and @xinhaoz)

___
*[-- commits, line 42 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MhvBY8q9tWnGzruuWKg):*
release justification? 
___
*[pkg/ui/cluster-ui/src/api/fetchData.ts, line 38 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MhvCQeY013tU2bzY1fs:-MhvCQeY013tU2bzY1ft:b-hkqbrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5fcdde2ce12727595e00def1a9ee90b838d8c26/pkg/ui/cluster-ui/src/api/fetchData.ts#L38)):*
> ```XML
> // - non-string values will be toString'd
> export function propsToQueryString(props: { [k: string]: any }) {
>   return _.compact(
> ```

in other pages we are trying to move from using `lodash` to using vanilla js array functions (#68820). Do we really need lodash here? 
___
*[pkg/ui/cluster-ui/src/store/localStorage/localStorage.reducer.ts, line 42 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi-vaDu4rtGFnHPRmhj:-Mi-vaDu4rtGFnHPRmhk:bgwxvt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f4c336e2b8fc2ba657442ad52766f8dd323c1d/pkg/ui/cluster-ui/src/store/localStorage/localStorage.reducer.ts#L42)):*
> ```XML
> const initialState: LocalStorageState = {
>   "adminUi/showDiagnosticsModal":
>     Boolean(JSON.parse(localStorage.getItem("adminUi/showDiagnosticsModal"))) ||
> ```

This is interesting. Why do we need to `JSON.parse` it ? 


<!-- Sent from Reviewable.io -->

2021-08-26 18:47 UTC, Azhng reviewed
Also let's update the PR description to be the same as the commit message :) 

> Reviewed 8 of 67 files at r8, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-:-Mi2mIjP-k6RQYe1ELHG:b-hw721q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 171 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2jgar19zP7p5AxMsk:-Mi2jgas2fFhYlfFpSgJ:bb9kcn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L171)):*
> ```XML
>     combined: true,
>     start: Long.fromNumber(props.dateRange[0].unix()),
>     end: Long.fromNumber(props.dateRange[0].unix()),
> ```

should this be `props.dateRange[1].unix()`  ?
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 124 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2jnrZE1WWg0EVICnE:-Mi2jnrZE1WWg0EVICnF:btlvcmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L124)):*
> ```XML
>   (statementsState, combinedStatementsState, props) => {
>     // TODO (xinhaoz) We need both in-memory and peristed data right now since
>     // statement details could refer to statemetns from the transactions page or
> ```

nit: `s/statemtns/statements/`
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts, line 47 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2k9B176Qwirg-lVAy:-Mi2k9B176Qwirg-lVAz:bs4m9k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts#L47)):*
> ```XML
>     statement,
>     statementsError: state.adminUI.combinedStatements.lastError,
>     dateRange: state.adminUI.uiConfig.isTenant ? null : selectDateRange(state),
> ```

so is it correct that we are disabling this on CC Console ?
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 127 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2kL-89QZ8eiobDMv5:-Mi2kL-89QZ8eiobDMv6:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L127)):*
> ```XML
>     combined: true,
>     start: Long.fromNumber(props.dateRange[0].unix()),
>     end: Long.fromNumber(props.dateRange[0].unix()),
> ```

ditto
___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 356 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2l1dF3dvvw8KQnZBO:-Mi2l1dF3dvvw8KQnZBP:b-5fa267) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L356)):*
> For now in-memory statements are needed for the transaction page

I don't quite follow here, why does transactions page need to in-memory stats? Are you referring to the Transaction Overview Page or Transaction Detail Page? 
___
*[pkg/ui/workspaces/db-console/src/util/api.ts, line 689 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2lWdN-8gruI7ZgBMX:-Mi2lWdN-8gruI7ZgBMY:b-qx5h3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/util/api.ts#L689)):*
> ```XML
>   timeout?: moment.Duration,
> ): Promise<StatementsResponseMessage> {
>   // (TODO) xinhaoz We can merge the getStatements and getCombinedStatements APIs on the frontend
> ```

Do we have an issue for this? I think it might be a good idea to track this work.
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 159 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2lmuBB2tGwuW9zSVN:-Mi2lmuBB2tGwuW9zSVO:bwo8l6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L159)):*
> ```XML
>   (_state: AdminUIState, props: RouteComponentProps) => props,
>   (statementsState, combinedStatementsState, props) => {
>     // TODO (xinhaoz) We need both in-memory and peristed data right now since
> ```

I think we should definitely cleanup our terminology here. `crdb_internal.{statement, transaction}_statsitics` returns both in-memory and persisted data. So using the terms like "in-memory and persisted data" makes it quite confusing what exactly this sentence is referring to. 
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 160 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2ljEh254uJFsCsdMY:-Mi2ljEi-mfyKsi4lOBY:b-inizb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L160)):*
> ```XML
>   (statementsState, combinedStatementsState, props) => {
>     // TODO (xinhaoz) We need both in-memory and peristed data right now since
>     // statement details could refer to statemetns from the transactions page or
> ```

`s/statemetns/statements/g


<!-- Sent from Reviewable.io -->

2021-08-26 19:10 UTC, maryliag reviewed
> Reviewed 1 of 19 files at r3, 5 of 34 files at r5, 8 of 67 files at r8, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts, line 36 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2qS-UEZvjAiiL41oA:-Mi2qS-UEZvjAiiL41oB:b-ftizal) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts#L36)):*
> ```XML
>     .subtract(1, "hours")
>     .unix(),
>   end: moment.utc().unix() + 60, // Add 1 minute to accout for potential lag.
> ```

nit: account
___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 353 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2qhI14bpQsFbl_HOm:-Mi2qhI14bpQsFbl_HOn:b-sav39x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L353)):*
> ```XML
>   settings: CachedDataReducerState<api.SettingsResponseMessage>;
>   stores: KeyedCachedDataReducerState<api.StoresResponseMessage>;
>   // TODO (xinhaoz) We can consolidate statemetns and combindStatements when both the
> ```

nit: statements combinedStatements
___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 356 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2l1dF3dvvw8KQnZBO:-Mi2qn78Bdml2Q32yOc5:bjydqd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L356)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

> For now in-memory statements are needed for the transaction page

I don't quite follow here, why does transactions page need to in-memory stats? Are you referring to the Transaction Overview Page or Transaction Detail Page? 
</blockquote></details>

the transactions and statements page currently use the same cache/reducer, so when one of the pages make a call, the other also get updates. This PR is changing the statements page to call the combined api, but until we add the data picker (which will be coming on a following PR), we can't use the same cache for both pages.
For this PR we don't touch txn page and keep using the in-memory data only, and use combined on stmts page. The next task is to use combined on txn and then we can use just one cache/reducer for everything
___
*[pkg/ui/workspaces/cluster-ui/src/store/combinedStatements/combinedStatements.reducer.ts, line 51 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2qAOM6l64r1Xp-AI9:-Mi2qAOM6l64r1Xp-AIA:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/store/combinedStatements/combinedStatements.reducer.ts#L51)):*
> ```XML
>       state.valid = false;
>     },
>     // Define actions that don't change state
> ```

nit: period
___
*[pkg/ui/workspaces/db-console/src/redux/statementsDateRange.ts, line 1 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2nnt-E7Y_QI2MpLkY:-Mi2nnt-E7Y_QI2MpLkZ:b-jc2ha3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/redux/statementsDateRange.ts#L1)):*
> ```XML
> import moment from "moment";
> ```

you need to add a license header here


<!-- Sent from Reviewable.io -->

2021-08-26 21:38 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/util/api.ts, line 689 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2lWdN-8gruI7ZgBMX:-Mi3OFxz06pd98_NAzQN:bqn6ns0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/util/api.ts#L689)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Not yet. I talked offline with Marylia a little about this issue, but essentially if we want the selected date range to differ between transactions and statements pages, then we probably do need to separate the state between the two pages like we are doing right now. If we're using the same date range between them though, then we can go back to using the same state/actions to refresh data between pages.

Personally I feel like it makes sense to use the same date range throughout the two pages especially because transactions can take you to the statements details page for a statement in the transaction, and we currently select the data for the statement from the store. If the date ranges are separate, we need to request both transactions + statements data for statementdetails page (unless we change how we load that data) since we don't know if the statement is referring to one in the transactions page or statements page. 

I can file an issue and update these comments if we know which route we're taking.
</blockquote></details>

We will be following the route of keeping the same data on both pages


<!-- Sent from Reviewable.io -->

2021-08-26 21:46 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 171 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2jgar19zP7p5AxMsk:-Mi3I2il1PSZ9b11Ly_j:bqtxcp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L171)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

should this be `props.dateRange[1].unix()`  ?
</blockquote></details>

Yes, nice catch! Fixed.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 124 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2jnrZE1WWg0EVICnE:-Mi3ILIW10dx4pIxVhH7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L124)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `s/statemtns/statements/`
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts, line 47 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2k9B176Qwirg-lVAy:-Mi3IMQa4WR9WG3ubUPB:b-ggef2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts#L47)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

so is it correct that we are disabling this on CC Console ?
</blockquote></details>

Yep that's correct, we're disabling only for serverless.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 127 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2kL-89QZ8eiobDMv5:-Mi3Ik3m4szQy0MubtUu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L127)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts, line 36 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2qS-UEZvjAiiL41oA:-Mi3Ixhl8breHpeWIRXH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts#L36)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: account
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 353 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2qhI14bpQsFbl_HOm:-Mi3Iz5QAIZY7AAreG4O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L353)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: statements combinedStatements
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 159 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2lmuBB2tGwuW9zSVN:-Mi3MjCM7Bc1Zijjpr0e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L159)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I think we should definitely cleanup our terminology here. `crdb_internal.{statement, transaction}_statsitics` returns both in-memory and persisted data. So using the terms like "in-memory and persisted data" makes it quite confusing what exactly this sentence is referring to. 
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 160 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2ljEh254uJFsCsdMY:-Mi3NG7w42TTVfjksL4d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L160)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

`s/statemetns/statements/g
</blockquote></details>

Done.
___
*[pkg/ui/cluster-ui/src/api/fetchData.ts, line 38 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MhvCQeY013tU2bzY1fs:-Mi3NHxa9xtneZGcYbTx:b-rh1z88) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5fcdde2ce12727595e00def1a9ee90b838d8c26/pkg/ui/cluster-ui/src/api/fetchData.ts#L38)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

in other pages we are trying to move from using `lodash` to using vanilla js array functions (#68820). Do we really need lodash here? 
</blockquote></details>

Ah true, copied this from pkg/ui. Gave the function a makeover to remove lodash.
___
*[pkg/ui/cluster-ui/src/store/localStorage/localStorage.reducer.ts, line 42 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi-vaDu4rtGFnHPRmhj:-Mi3PpIi35YO-xDgHnss:ba1zehy) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f4c336e2b8fc2ba657442ad52766f8dd323c1d/pkg/ui/cluster-ui/src/store/localStorage/localStorage.reducer.ts#L42)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

This is interesting. Why do we need to `JSON.parse` it ? 
</blockquote></details>

AFAIK everything in local storage is saved as key/val pairs where val is a string. I'm storing the date range object as a stringified json obj.
___
*[pkg/ui/workspaces/cluster-ui/src/store/combinedStatements/combinedStatements.reducer.ts, line 51 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2qAOM6l64r1Xp-AI9:-Mi3Irea1coJJ-0vfUef:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/store/combinedStatements/combinedStatements.reducer.ts#L51)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: period
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/redux/statementsDateRange.ts, line 1 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2nnt-E7Y_QI2MpLkY:-Mi3J7PpEC5G82V9UsJP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/redux/statementsDateRange.ts#L1)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you need to add a license header here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-26 22:22 UTC, maryliag requested changes
> Reviewed 1 of 35 files at r6, 24 of 67 files at r8, 1 of 2 files at r9, 10 of 10 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts, line 47 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2k9B176Qwirg-lVAy:-Mi3WKfe3YoTxJs58vLN:bs45liq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts#L47)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Yep that's correct, we're disabling only for serverless.
</blockquote></details>

Just to use the correct names here: CC Console and Serverless are not the same thing, we're disabling this on Serverless, not on CC Console, that's why the check is for isTenant
___
*[pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts, line 18 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi3XoCw1txtEHWPyNsi:-Mi3XoCw1txtEHWPyNsj:b-rrr63n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fa0a897be1d6f496bfb110b3aaddf743b89b0da/pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts#L18)):*
> ```XML
> 
> export const selectStatementByFingerprint = createSelector(
>   (state: AdminUIState) => state.cachedData.combinedStatements.data?.statements,
> ```

are you saving the not combined data on the combined data cache?
if they're on different parameters you should have a check, if is tenant use cachedData.statements, otherwise the combined
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx, line 69 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi3YPKkAVV5pVYVbVxc:-Mi3YPKkAVV5pVYVbVxd:b-kh1l1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fa0a897be1d6f496bfb110b3aaddf743b89b0da/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L69)):*
> ```XML
> // StatementsPage, based on if the appAttr route parameter is set.
> export const selectStatements = createSelector(
>   (state: AdminUIState) => state.cachedData.combinedStatements,
> ```

similar to the other comment. Is this working for tenant cases?


<!-- Sent from Reviewable.io -->

2021-08-26 22:58 UTC, Azhng reviewed
> Reviewed 19 of 67 files at r8, 1 of 2 files at r9, 5 of 10 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts, line 47 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2k9B176Qwirg-lVAy:-Mi3RiFk2wK0Ydl5Nk9z:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts#L47)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Yep that's correct, we're disabling only for serverless.
</blockquote></details>

:+1:
___
*[pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts, line 48 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi3eDC4ExIK2hMGnAme:-Mi3eDC4ExIK2hMGnAmf:b-gn9p9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fa0a897be1d6f496bfb110b3aaddf743b89b0da/pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts#L48)):*
> ```XML
>   "dateRange/StatementsPage":
>     JSON.parse(localStorage.getItem("dateRange/StatementsPage")) ||
>     defaultDateRange,
> ```

just noticed that `localStorage.saga.ts` doesn't have a corresponding `*.spec.ts`. Did we not have test for the localStorage reducers ?
___
*[pkg/ui/workspaces/cluster-ui/src/store/statements/statements.sagas.ts, line 30 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi3f5eR9dwRKWRrv9av:-Mi3f5eSEe4YmGkMtRom:b-wi066f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fa0a897be1d6f496bfb110b3aaddf743b89b0da/pkg/ui/workspaces/cluster-ui/src/store/statements/statements.sagas.ts#L30)):*
> ```XML
> ): any {
>   if (action?.payload.combined) {
>     yield put(combinedStatementsActions.refresh(action.payload));
> ```

IIUC, this should result in different set of actions be issued in the redux. Let's also update the `statements.sagas.spec.ts` to reflect this? 
___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 356 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2l1dF3dvvw8KQnZBO:-Mi3XLVZCp6BxBNYA1np:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L356)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the transactions and statements page currently use the same cache/reducer, so when one of the pages make a call, the other also get updates. This PR is changing the statements page to call the combined api, but until we add the data picker (which will be coming on a following PR), we can't use the same cache for both pages.
For this PR we don't touch txn page and keep using the in-memory data only, and use combined on stmts page. The next task is to use combined on txn and then we can use just one cache/reducer for everything
</blockquote></details>

:+1:
___
*[pkg/ui/workspaces/db-console/src/util/api.ts, line 689 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi2lWdN-8gruI7ZgBMX:-Mi3WOSB2rZQiA_v4KW5:bj8bvos) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3720ae9e2a743f8786e151f585aade92edc09b6/pkg/ui/workspaces/db-console/src/util/api.ts#L689)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

We will be following the route of keeping the same data on both pages
</blockquote></details>

:+1: We can continue the discussion on the issue. 


<!-- Sent from Reviewable.io -->

2021-08-27 14:34 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts, line 48 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi3eDC4ExIK2hMGnAme:-Mi70uqz2s2dch3EaD8M:b-fejbvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fa0a897be1d6f496bfb110b3aaddf743b89b0da/pkg/ui/workspaces/cluster-ui/src/store/localStorage/localStorage.reducer.ts#L48)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

just noticed that `localStorage.saga.ts` doesn't have a corresponding `*.spec.ts`. Did we not have test for the localStorage reducers ?
</blockquote></details>

Seems like we don't currently have them, I can add some for the saga.
___
*[pkg/ui/workspaces/cluster-ui/src/store/statements/statements.sagas.ts, line 30 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi3f5eR9dwRKWRrv9av:-Mi70arA-APhFyOmfOjc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fa0a897be1d6f496bfb110b3aaddf743b89b0da/pkg/ui/workspaces/cluster-ui/src/store/statements/statements.sagas.ts#L30)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

IIUC, this should result in different set of actions be issued in the redux. Let's also update the `statements.sagas.spec.ts` to reflect this? 
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts, line 18 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi3XoCw1txtEHWPyNsi:-Mi3uB2O8D7ZYWlluMe9:bn53dm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fa0a897be1d6f496bfb110b3aaddf743b89b0da/pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts#L18)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

are you saving the not combined data on the combined data cache?
if they're on different parameters you should have a check, if is tenant use cachedData.statements, otherwise the combined
</blockquote></details>

Updated to include statements from transactions page. (Clarified offline this was actually for txns, not tenant).
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx, line 69 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi3YPKkAVV5pVYVbVxc:-Mi3u3hN6_l-oTur83lM:bvjdbjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fa0a897be1d6f496bfb110b3aaddf743b89b0da/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L69)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

similar to the other comment. Is this working for tenant cases?
</blockquote></details>

This is only used on the statementsPage in db console so it shuold be fine to select combinedStatements directly.
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 232 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MhuHgjACjDAnB8gj75I:-Mi70o5u9g4PRnIgUaCX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5fcdde2ce12727595e00def1a9ee90b838d8c26/pkg/ui/src/views/statements/statementsPage.tsx#L232)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I don't we should limit one year or trying to find the oldest data. The picker itself can go back as far as possible and the user selects what makes more sense.  Is common to have a selector going back more than you have data for, we simply show what we have
(make that change on the other statementsPage too, so have older data range)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-27 14:43 UTC, maryliag reviewed
> Reviewed 11 of 13 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/dateRange/dateRange.stories.tsx, line 13 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi73EI-5o7Lg-avakHW:-Mi73EI-5o7Lg-avakHX:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/349e35ea8210bde6362fcf82770ef793297be10f/pkg/ui/workspaces/cluster-ui/src/dateRange/dateRange.stories.tsx#L13)):*
> ```XML
> import React from "react";
> import { storiesOf } from "@storybook/react";
> ```

nit: remove blank line
___
*[pkg/ui/workspaces/cluster-ui/src/dateRange/dateRange.stories.tsx, line 15 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-Mi73FjnAhyot_pcTmAG:-Mi73FjnAhyot_pcTmAH:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/349e35ea8210bde6362fcf82770ef793297be10f/pkg/ui/workspaces/cluster-ui/src/dateRange/dateRange.stories.tsx#L15)):*
> ```XML
> 
> import { start, end, allowedInterval } from "./dateRange.fixtures";
> ```

nit: remove blank line


<!-- Sent from Reviewable.io -->

2021-08-27 19:48 UTC, maryliag requested changes
A few issues: 
- I was able to select an end date before the start data. The selection should be validated
- When I clean one of the values, it's not updating the selection on the main picker
- Because the value of the main picker in not being updated, if you click apply with one of the values empty, and then open again, the value gets populated with the value from the main picker

> Reviewed 1 of 67 files at r8, 2 of 39 files at r13, 37 of 37 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-:-Mi87bd91p2bEbJ33wqg:b-g0s3hw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2021-08-27 21:23 UTC, maryliag reviewed
the phrasing sounds a little weird, can you change to “Date interval not valid” if the before happens after the end, and “Select a start and end date” when one of them is not selected

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-:-Mi8UTjZCZq1xNrM6DLH:bbnu95r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2021-08-27 22:03 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 67 files at r8, 4 of 5 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-:-Mi8ckQ17WtP8M_h3Hne:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2021-08-28 16:03 UTC, maryliag requested changes
> Reviewed 41 of 47 files at r17.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[-- commits, line 28 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCPpQ99O1snvYjENuZ):*
nit: and transaction page
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 168 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCQDM_EugIVZtlqSgQ:-MiCQDM_EugIVZtlqSgR:b-n6djko) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0602c5db93a2833c0394ea3339e25e6bf6f9257/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L168)):*
> ```XML
>   if (props.dateRange == null) return null;
>   return new cockroach.server.serverpb.StatementsRequest({
>     combined: true,
> ```

you need to use this value from the props too, since it will be false for tenants
I added the props value on a PR currently being merged, you can rebase yours with that one and use the value from there
https://github.com/cockroachdb/cockroach/pull/69444
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageConnected.tsx, line 50 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCRjXs3ufp5odBSsex:-MiCRjXs3ufp5odBSsey:b-wzjw3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0602c5db93a2833c0394ea3339e25e6bf6f9257/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageConnected.tsx#L50)):*
> ```XML
>     (state: AppState, props: StatementsPageProps) => ({
>       statements: selectStatements(state, props),
>       dateRange: state.adminUI.uiConfig.isTenant
> ```

once you merge with the PR I mention, change this to
`dateRange: selectIsTenant(state) ? null : selectDateRange(state)` 
just to be on the safe side, so we have one single place of source for that value 
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx, line 90 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCSaHH38KIo_SLKkVw:-MiCSaHH38KIo_SLKkVx:b-wz8nvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0602c5db93a2833c0394ea3339e25e6bf6f9257/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L90)):*
> ```XML
>   if (props.dateRange == null) return null;
>   return new protos.cockroach.server.serverpb.StatementsRequest({
>     combined: true,
> ```

similar to the other case, the combined value must check the isTenant value
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageConnected.tsx, line 43 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCSnGwDsw_tNAp4VJV:-MiCSnGwDsw_tNAp4VJW:b-v0yr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0602c5db93a2833c0394ea3339e25e6bf6f9257/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageConnected.tsx#L43)):*
> ```XML
>       nodeRegions: nodeRegionsByIDSelector(state),
>       error: selectTransactionsLastError(state),
>       dateRange: state.adminUI.uiConfig.isTenant
> ```

similar to the other message, use the selector from the other PR
___
*[pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts, line 22 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCTJ8X9fAY3vGMaVG1:-MiCTJ8X9fAY3vGMaVG2:b7hxwiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0602c5db93a2833c0394ea3339e25e6bf6f9257/pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts#L22)):*
> ```XML
>   (statements, statementFingerprint) => {
>     if (statements == null) {
>       return null;
> ```

why you want to return null here? using an empty array is safer. If you're using this value to decide on using statements vs combined statements, you should be using the value of isTenant
___
*[pkg/ui/workspaces/db-console/src/util/api.ts, line 679 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCTnvZ9VDrrO6L986t:-MiCTnvZ9VDrrO6L986u:b-aq9ea2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0602c5db93a2833c0394ea3339e25e6bf6f9257/pkg/ui/workspaces/db-console/src/util/api.ts#L679)):*
> ```XML
> ): Promise<StatementsResponseMessage> {
>   const queryStr = propsToQueryString({
>     combined: true,
> ```

this value should be based on value of isTenant


<!-- Sent from Reviewable.io -->

2021-08-28 17:14 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx, line 90 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCSaHH38KIo_SLKkVw:-MiCjlEz29dxv0ZGZZSL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0602c5db93a2833c0394ea3339e25e6bf6f9257/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L90)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

similar to the other case, the combined value must check the isTenant value
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageConnected.tsx, line 43 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCSnGwDsw_tNAp4VJV:-MiCjn7R4GdPFw8mMDRA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0602c5db93a2833c0394ea3339e25e6bf6f9257/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageConnected.tsx#L43)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

similar to the other message, use the selector from the other PR
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts, line 22 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCTJ8X9fAY3vGMaVG1:-MiCjq6I19F4mW89cZz-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0602c5db93a2833c0394ea3339e25e6bf6f9257/pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts#L22)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why you want to return null here? using an empty array is safer. If you're using this value to decide on using statements vs combined statements, you should be using the value of isTenant
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/util/api.ts, line 679 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCTnvZ9VDrrO6L986t:-MiCjtX6-zrreJGSuSX5:bldq45g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0602c5db93a2833c0394ea3339e25e6bf6f9257/pkg/ui/workspaces/db-console/src/util/api.ts#L679)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this value should be based on value of isTenant
</blockquote></details>

This is only used for db console, so we'll always be using combined api.


<!-- Sent from Reviewable.io -->

2021-08-28 17:33 UTC, maryliag requested changes
> Reviewed 4 of 11 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx, line 90 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCmptUEiP3d6Xb0c0D:-MiCmRbZBM9Krs32vVQz:b-mbg9uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e14aa0572734ee82b58590d5c6c086b5011113/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L90)):*
> ```XML
>   props: TransactionsPageProps,
> ): protos.cockroach.server.serverpb.StatementsRequest | null {
>   if (props.isTenant || props.dateRange == null) return null;
> ```

on the previous refresh the in-memory was being updated, now your new refresh call this function and this only updates the combined data, so when it's a tenant or the user didn't make any date selection is not doing any refreshes. We still want tenant values to be refreshed, so you still return a request when is tenant or there is not data range, the difference is that you will make the call without passing any of those values. 


<!-- Sent from Reviewable.io -->

2021-08-28 17:58 UTC, maryliag approved these changes
Thank you for adding changes to transaction too. I had just 3 small nits and then
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-:-MiCu8bMB2p2uHs_U3oA:b33zr80)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 123 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCu2iQ51QXQucuwYe7:-MiCu2iQ51QXQucuwYe8:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e14aa0572734ee82b58590d5c6c086b5011113/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L123)):*
> ```XML
>   (statementsState, props) => {
>     const statements = statementsState.data?.statements;
> ```

nit: remove blank line
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts, line 46 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCstsl-_i6SJrd_04x:-MiCstsl-_i6SJrd_04y:bnmx55b) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e14aa0572734ee82b58590d5c6c086b5011113/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts#L46)):*
> ```XML
>     statement,
>     statementsError: state.adminUI.statements.lastError,
>     dateRange: state.adminUI.uiConfig.isTenant ? null : selectDateRange(state),
> ```

nit: can you change this one too to use the selector instead of the parameter directly?
___
*[pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts, line 25 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCtduB8K9Ti0Y0npNY:-MiCtduC8imbjPgUZnPt:bi8qz9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e14aa0572734ee82b58590d5c6c086b5011113/pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts#L25)):*
> ```XML
>     );
>   },
> );
> ```

you can remove the `return` now, since you retracted the other changes you made here


<!-- Sent from Reviewable.io -->

2021-08-28 18:08 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68831)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 123 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCu2iQ51QXQucuwYe7:-MiCwNKeBm02aT6c9H3C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e14aa0572734ee82b58590d5c6c086b5011113/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L123)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: remove blank line
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts, line 46 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCstsl-_i6SJrd_04x:-MiCwGHI3e2uxD4XwOUI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e14aa0572734ee82b58590d5c6c086b5011113/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts#L46)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: can you change this one too to use the selector instead of the parameter directly?
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts, line 25 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68831#-MiCtduB8K9Ti0Y0npNY:-MiCwVtF0QGyFfplXtZU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e14aa0572734ee82b58590d5c6c086b5011113/pkg/ui/workspaces/db-console/src/redux/statements/statementsSelectors.ts#L25)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you can remove the `return` now, since you retracted the other changes you made here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-28 19:41 UTC, xinhaoz commented
bors r+

2021-08-28 20:48 UTC, merged