sql: implement ON UPDATE expressions
cockroachdb/cockroach pull request #69091
Opened 2021-08-18 14:44 UTC by pawalt

This PR implements ON UPDATE expressions.

Resolves #69057

Release note (sql change): This PR adds ON UPDATE expression to allow users to
evaluate expressions when a row is updated.

2021-08-18 14:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/69091)
<!-- Reviewable:end -->

2021-08-18 19:30 UTC, mgartner reviewed
Very cool!

We probably want to add support for `ON UPDATE` to the optimizer's test catalog. This will allow you to add tests for your changes in `optbuilder` to `pkg/sql/opt/optbuilder/testdata`. Here's an example commit for adding support for a new column type to the test catalog: https://github.com/cockroachdb/cockroach/commit/2045ba2e86c53818b1c6cd32584583c737a93e55

> Reviewed 3 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-:-MhPiyCNCfc7iTY_-MUg:b-kf7as1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPY_I4EIzRhtYXUG8Q:-MhPY_I5-DfB4kS22NdH:bdmgcxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/-- commits#L9)):*
nit: A release note should read as if it's included in the release notes for a DB version. So mentioning "PR" may not be the correct perspective. Here's a suggestion you can play with: "An ON UPDATE expression can now be added to a column. Whenever a row is modified, a column's `ON UPDATE` expression is re-evaluated and the column is updated to the result."
___
*[pkg/sql/alter_table.go, line 364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPZlEz6rUwxjYdixoI:-MhPZlEz6rUwxjYdixoJ:b-poygjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/alter_table.go#L364)):*
> ```Go
> 			case *tree.ForeignKeyConstraintTableDef:
> 				// We want to reject uses of ON UPDATE actions where there is already an
> 				// ON UPDATE expression for the column.
> ```

nit: make it clear the first `ON UPDATE` you mention is FK related.
___
*[pkg/sql/alter_table.go, line 1199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPekVK54ODCkkA5nUV:-MhPekVK54ODCkkA5nUW:b-9esoqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/alter_table.go#L1199)):*
> ```Go
> 
> 		if col.NumUsesSequences() > 0 {
> 			if err := params.p.removeSequenceDependencies(params.ctx, tableDesc, col); err != nil {
> ```

I don't understand the need for this block. Can you add a comment explaining what it does?
___
*[pkg/sql/alter_table.go, line 1204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPgcp80z6R9xeRhe-k:-MhPgcp80z6R9xeRhe-l:b-lyzk5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/alter_table.go#L1204)):*
> ```Go
> 		}
> 		if t.Expr == nil {
> 			col.ColumnDesc().OnUpdateExpr = nil
> ```

When would `t.Expr` be `nil`? Do you have a logictest for this case?
___
*[pkg/sql/catalog/descpb/structured.proto, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPgKLQ-t2ALRY6dvB_:-MhPgKLQ-t2ALRY6dvBa:bxvrazl) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/catalog/descpb/structured.proto#L145)):*
> ```protobuf
>   // have been serialized in a internal format. Instead, use one of the
>   // schemaexpr.FormatExpr* functions.
>   optional string on_update_expr = 18;
> ```

Consider adding some validation for this field [here](https://github.com/cockroachdb/cockroach/blob/e2cd3ae015c1f86d188ace3650db2ea622ec58b4/pkg/sql/catalog/tabledesc/validate.go#L645) and testing that validation [here](https://github.com/cockroachdb/cockroach/blob/6e3438f6055730d80cb430283a3e85f7503c9e18/pkg/sql/catalog/tabledesc/validate_test.go#L312).
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPf6ueDaf0S1Q5yUpp:-MhPf6ueDaf0S1Q5yUpq:bgg5dvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/logictest/testdata/logic_test/on_update#L110)):*
> ```
> 
> statement error pq: cannot specify a foreign key update action and an ON UPDATE expression on the same column
> ALTER TABLE alter_update ADD CONSTRAINT fk FOREIGN KEY (j) REFERENCES test_fk_base (j) ON UPDATE SET DEFAULT
> ```

Can you add some tests with `SHOW CREATE TABLE ...`?
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPhID59xd4njb-g2GU:-MhPhID59xd4njb-g2GV:bqd18mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/opt/optbuilder/mutation_builder.go#L1205)):*
> ```Go
> // computed value expression for the given table column, and caches it for
> // reuse.
> func (mb *mutationBuilder) parseOnUpdateOrComputedExpr(colID opt.ColumnID) tree.Expr {
> ```

Is there a need to parse a computed expression here? A column is not allowed to be both computed and have an `ON UPDATE`, correct? 

It'd also be confusing to now have both `parseDefaultOrComputedExpr` and `parseOnUpdate`. Maybe this should be refactored to `parseDefaultExpr`, `parseOnUpdateExpr`, and `parseComputedExpr` which all call a function that does most of the work like `parseColumnExpr(colID opt.ColumnID, exprStr string) tree.Expr) { ... }`. The caching might be a slight hurdle... `parseColumnExpr` could also take a map to use for caching.


<!-- Sent from Reviewable.io -->

2021-08-18 20:08 UTC, RaduBerinde reviewed
Absolutely, we need optbuilder testcases.

We should also have a TODO somewhere to avoid updating the column unnecessarily (e.g. if the expression is immutable and the input columns don't change).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-:-MhPriqjDARghRwVHipZ:b-jtrw3o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)



<!-- Sent from Reviewable.io -->

2021-08-18 20:26 UTC, postamar requested changes
Reviewing on behalf of @cockroachdb/sql-schema I just have a few small requests but nothing major.

2021-08-18 20:26 UTC, postamar commented on pkg/sql/catalog/tabledesc/validate.go
> +						col.GetID(),
This error also doesn't need to be an assertion failure, you can return a `pgerror.New(pgcode.InvalidTableDefinition, ...`
The validation framework will wrap these into assertion failures when required (at descriptor read and write time).

Also, ideally we try to capture as many validation failures as possible, not just the first encountered. I understand you want to use this in `create_table.go` as well. Perhaps there's a way. If you look at other validation code you'll notice that we're not particularly disciplined in doing this but better late than never.

2021-08-18 20:26 UTC, postamar commented on pkg/sql/catalog/tabledesc/column.go
> +}
This `OnUpdateExpr` field should be visited by `ForEachExprStringInTableDesc` in `tabledesc`.

Please add tests to cover a missing cross-reference in `validate.go` in the `tabledesc` package. By that I mean, a test case in which the `ON UPDATE` expression refers to a descriptor which doesn't exist, like an user-defined enum type value for example.

2021-08-18 20:26 UTC, postamar commented on pkg/sql/opt_catalog.go
> +			d.ColumnDesc().OnUpdateExpr,
I'm aware this is continuing an existing pattern but we _really_ should avoid looking stuff up in `ColumnDesc()` or `IndexDesc()` when possible and instead delegate to the `catalog.Column` interface. 

Perhaps this is out of scope for this change. Also I'm aware that the opt-catalog predates the schema-catalog but at some point we'll have to do this change so might as well start now and make it happen gradually?

2021-08-18 21:34 UTC, rytaft reviewed
> Reviewed 6 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/sql/opt/cat/column.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhQ8mVcEiHDHoDttG0H:-MhQ8mVeEiYqalCL_q9l:bapvg5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/opt/cat/column.go#L108)):*
> ```Go
> 
> // HasOnUpdate returns true if the column has an on update expression.
> // OnUpdateStr will be set to the SQL expression string in that case.
> ```

nit: on update expression -> ON UPDATE expression
nit: OnUpdateStr -> OnUpdateExprStr?
___
*[pkg/sql/opt/cat/column.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhQ96OTBw5NGA-zfPYy:-MhQ96OTBw5NGA-zfPYz:b-nujlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/opt/cat/column.go#L114)):*
> ```Go
> 
> // OnUpdateExprStr is set to the SQL expression string that describes the column's
> // on update expression. It is used when the user does not provide a value for
> ```

nit: ON UPDATE
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 600 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhQ9iEd2G4mN0IxIbNV:-MhQ9iEd2G4mN0IxIbNW:bgtkhuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/opt/optbuilder/mutation_builder.go#L600)):*
> ```Go
> 			// Always include WriteOnly columns.
> 		} else if tabCol.HasOnUpdate() && applyOnUpdate {
> 			// Use ON UPDATE columns if specified
> ```

nit: end comment with a period.


<!-- Sent from Reviewable.io -->

2021-08-19 18:27 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @mgartner, @postamar, and @rytaft)

___
*[pkg/sql/alter_table.go, line 1199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPekVK54ODCkkA5nUV:-MhUVkYh59UN8uytWgZG:ba6vsqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/alter_table.go#L1199)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't understand the need for this block. Can you add a comment explaining what it does?
</blockquote></details>

Done.

I realized I needed to take into account both DEFAULT and ON UPDATE expressions when recalculating sequence dependencies, so I've factored that logic out into an `updateSequenceDependencies` function. I think I'm doing the updating properly, but if someone could sanity-check it, that'd be great.

I added tests for this case at the bottom of my `on_update` logic test.
___
*[pkg/sql/alter_table.go, line 1204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPgcp80z6R9xeRhe-k:-MhTrFOrCexuQP1L8Efa:bgk0bzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/alter_table.go#L1204)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

When would `t.Expr` be `nil`? Do you have a logictest for this case?
</blockquote></details>

`t.Expr` is nil in the case where we drop an ON UPDATE expression. 
___
*[pkg/sql/opt_catalog.go, line 1827 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhOiF4MquS28IjySS02-r1-1827:-MhUF9lE5vaLyLdJRV6p:b-h7fgl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/opt_catalog.go#L1827)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm aware this is continuing an existing pattern but we _really_ should avoid looking stuff up in `ColumnDesc()` or `IndexDesc()` when possible and instead delegate to the `catalog.Column` interface. 

Perhaps this is out of scope for this change. Also I'm aware that the opt-catalog predates the schema-catalog but at some point we'll have to do this change so might as well start now and make it happen gradually? 
</blockquote></details>

I think this will have to be a one-shot migration. The `Init` function takes in a string pointer and knows that the expression is empty if the pointer is nil. The catalog behavior, however, is to output an empty string if there is no expression. We'll have to change `Init` to match this behavior. This shouldn't be too hard of a change to make, but I think it's better for a later PR.
___
*[pkg/sql/catalog/descpb/structured.proto, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPgKLQ-t2ALRY6dvB_:-MhUCxJK9jM_q9nwqUYy:bdbhbsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/catalog/descpb/structured.proto#L145)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Consider adding some validation for this field [here](https://github.com/cockroachdb/cockroach/blob/e2cd3ae015c1f86d188ace3650db2ea622ec58b4/pkg/sql/catalog/tabledesc/validate.go#L645) and testing that validation [here](https://github.com/cockroachdb/cockroach/blob/6e3438f6055730d80cb430283a3e85f7503c9e18/pkg/sql/catalog/tabledesc/validate_test.go#L312).
</blockquote></details>

I added validation by updating `ForEachExprStringInTableDesc` and adding a test. Is there other validation I should be doing? The test I added covers referencing nonexistent descriptors.
___
*[pkg/sql/catalog/tabledesc/column.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhOiF4LVKnXkWPd4hPw-r1-123:-MhUCG9FE4MLkGjRijBR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/catalog/tabledesc/column.go#L123)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This `OnUpdateExpr` field should be visited by `ForEachExprStringInTableDesc` in `tabledesc`.

Please add tests to cover a missing cross-reference in `validate.go` in the `tabledesc` package. By that I mean, a test case in which the `ON UPDATE` expression refers to a descriptor which doesn't exist, like an user-defined enum type value for example.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 670 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhOiF4LVKnXkWPd4hPy-r1-670:-MhTvrZU3lTKfr-IxWgv:b-cq3sjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/catalog/tabledesc/validate.go#L670)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This error also doesn't need to be an assertion failure, you can return a `pgerror.New(pgcode.InvalidTableDefinition, ...`
The validation framework will wrap these into assertion failures when required (at descriptor read and write time).

Also, ideally we try to capture as many validation failures as possible, not just the first encountered. I understand you want to use this in `create_table.go` as well. Perhaps there's a way. If you look at other validation code you'll notice that we're not particularly disciplined in doing this but better late than never.
</blockquote></details>

Ah didn't know that. Changed.

I could build up a single error string with all the ON UPDATE validation errors in it, but I'm not sure how idiomatic that is. Does that sound reasonable? It's the only way I can think of to reuse this code off the top of my head.
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPf6ueDaf0S1Q5yUpp:-MhU04tB8pbLVj0SKAP-:bxgyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/logictest/testdata/logic_test/on_update#L110)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add some tests with `SHOW CREATE TABLE ...`?
</blockquote></details>

Added. Any specific other cases I should be looking out for?
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPhID59xd4njb-g2GU:-MhUM3cA9x8naOODziTi:b-7f7zm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/opt/optbuilder/mutation_builder.go#L1205)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is there a need to parse a computed expression here? A column is not allowed to be both computed and have an `ON UPDATE`, correct? 

It'd also be confusing to now have both `parseDefaultOrComputedExpr` and `parseOnUpdate`. Maybe this should be refactored to `parseDefaultExpr`, `parseOnUpdateExpr`, and `parseComputedExpr` which all call a function that does most of the work like `parseColumnExpr(colID opt.ColumnID, exprStr string) tree.Expr) { ... }`. The caching might be a slight hurdle... `parseColumnExpr` could also take a map to use for caching.
</blockquote></details>

Gave this a shot; Let me know how it looks


<!-- Sent from Reviewable.io -->

2021-08-19 23:50 UTC, rytaft approved these changes
Opt stuff <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> nice work! (just some nits below)

> Reviewed 8 of 17 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-:-MhVn9GeBE7rYYMnE6X2:b-780479)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @mgartner, @pawalt, and @postamar)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 148 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhVjXxq3m_S2R-hLFIq:-MhVjXxq3m_S2R-hLFIr:b-1zqmqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/opt/optbuilder/mutation_builder.go#L148)):*
> ```Go
> 	subqueries []*scope
> 
> 	// parsedColComputedExprs is a cached set of parsed default expressions
> ```

nit: default expressions -> computed expressions
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 152 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhVjdec3l1R8i_6m3lv:-MhVjdec3l1R8i_6m3lw:b-9f0a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/opt/optbuilder/mutation_builder.go#L152)):*
> ```Go
> 	parsedColComputedExprs []tree.Expr
> 
> 	// parsedColComputedExprs is a cached set of parsed computed expressions
> ```

nit: parsedColComputedExprs -> parsedColDefaultExprs
nit: computed expressions -> default expressions
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhVjxyVBe4N7o846ejz:-MhVjoM70eV_XuUyXpqZ:bpy8xmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/opt/optbuilder/mutation_builder.go#L156)):*
> ```Go
> 	parsedColDefaultExprs []tree.Expr
> 
> 	// parsedColUpdateExprs is a cached set of parsed on update expressions from
> ```

nit: on update -> ON UPDATE
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 158 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhVk04sDKuvxJxmFX5_:-MhVk04sDKuvxJxmFX5a:b-lrl55f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/opt/optbuilder/mutation_builder.go#L158)):*
> ```Go
> 	// parsedColUpdateExprs is a cached set of parsed on update expressions from
> 	// the table schema. These are parsed once and cached for reuse.
> 	parsedColUpdateExprs []tree.Expr
> ```

nit: I'd call this `parsedColOnUpdateExprs`
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhVktDC24Zor8MdN8oZ:-MhVktDDEXeIKLvtQEYU:b59zqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/opt/optbuilder/mutation_builder.go#L1237)):*
> ```Go
> 			}
> 			return datum
> 		} else {
> ```

nit: don't need else here (you'll probably get a lint error for this)
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1326 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhVl_2JB21inp_TVZMt:-MhVl_2JB21inp_TVZMu:b-8dkepv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/opt/optbuilder/testdata/insert#L1326)):*
> ```
> 
> build
> INSERT INTO on_update_with_default VALUES (1)
> ```

nit: add a similar test for `on_update_bare` and check that NULL is inserted
___
*[pkg/sql/opt/optbuilder/testdata/update, line 1713 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhVlq8w6s9aQBTuSAxS:-MhVlq8w6s9aQBTuSAxT:bp9750i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/opt/optbuilder/testdata/update#L1713)):*
> ```
>       │         └── 1 [as=a_new:11]
>       └── projections
>            └── 10 [as=v_default:12]
> ```

nit: also add a couple tests where you explicitly update v


<!-- Sent from Reviewable.io -->

2021-08-20 01:54 UTC, arulajmani reviewed
Exciting stuff! 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-:-MhWFy1c1Xz9ONB2ZZDJ:bn8g1jz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @pawalt, and @postamar)

___
*[pkg/sql/alter_table.go, line 1186 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhWF3dECNU9Eg3FqYsn:-MhWF3dECNU9Eg3FqYso:bw8w9dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/alter_table.go#L1186)):*
> ```Go
> 		}
> 
> 	case *tree.AlterTableSetOnUpdate:
> ```

We should gate this (and the CREATE codepath) behind a cluster version. Checkout `pkg/clusterversion/cockroach_versions.go`, you probably want to add something in there. 
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 109 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhWFVyf8bceZ94J9c8D:-MhWFVyf8bceZ94J9c8E:bhz7t9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/logictest/testdata/logic_test/on_update#L109)):*
> ```
> pk4  should_not_change
> 
> # ON UPDATE usage with foreign key cascading
> ```

nit: Can we spell out this test case in a bit more detail?
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 138 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhWFgrt5VOrR8QTTIob:-MhWFgru-kxofgGGsNee:bbfhety) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/logictest/testdata/logic_test/on_update#L138)):*
> ```
> pk2  val2       def
> 
> # ON UPDATE error cases - conflict with a FK ON UPDATE
> ```

Same as above. 
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 204 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhWCx6w0LiRi9cbe-PP:-MhWCx6w0LiRi9cbe-PQ:blaacnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/logictest/testdata/logic_test/on_update#L204)):*
> ```
> )
> 
> # Sequence tests
> ```

Let's add something similar for enums as well? Separately, would this work with dropping enum values? Say an enum value is used in an ON UPDATE expression. Do we track/validate it correctly when trying to drop it? 


<!-- Sent from Reviewable.io -->

2021-08-20 18:43 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @mgartner, @postamar, and @rytaft)

___
*[pkg/sql/alter_table.go, line 1186 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhWF3dECNU9Eg3FqYsn:-MhZlhIzEfM319ouzV-w:bsqutq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/alter_table.go#L1186)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We should gate this (and the CREATE codepath) behind a cluster version. Checkout `pkg/clusterversion/cockroach_versions.go`, you probably want to add something in there. 
</blockquote></details>

This PR is getting a little big, so I'll add this check in after this lands. Issue here:
https://github.com/cockroachdb/cockroach/issues/69196
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 138 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhWFgrt5VOrR8QTTIob:-MhZmcm-16t3x_M9Uj8X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/logictest/testdata/logic_test/on_update#L138)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same as above. 
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 204 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhWCx6w0LiRi9cbe-PP:-MhZp1nv97kBtDk6ZXE-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb91fe5b086d425aaf7aea55c8079a98cab1d26/pkg/sql/logictest/testdata/logic_test/on_update#L204)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's add something similar for enums as well? Separately, would this work with dropping enum values? Say an enum value is used in an ON UPDATE expression. Do we track/validate it correctly when trying to drop it? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-20 20:18 UTC, rytaft approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @mgartner, and @postamar)



<!-- Sent from Reviewable.io -->

2021-08-20 20:39 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @mgartner, @pawalt, and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 297 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-Mh_GBcG3mAZ6hYFVo-p:-Mh_GBcG3mAZ6hYFVo-q:b-it18ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b08dce3b1acc101a540cb444f60e7e117a05291/pkg/sql/logictest/testdata/logic_test/on_update#L297)):*
> ```
> pk2  x
> 
> # Make sure that our ON UPDATE has a dependency on test_seq
> ```

You mean test_enum?
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-Mh_GIUM50Vz5w_UXps-:-Mh_GIUM50Vz5w_UXps0:b-fmr0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b08dce3b1acc101a540cb444f60e7e117a05291/pkg/sql/logictest/testdata/logic_test/on_update#L299)):*
> ```
> # Make sure that our ON UPDATE has a dependency on test_seq
> statement error pq: cannot drop type "test_enum" because other objects \(\[test.public.test_table_enum\]\) still depend on it
> DROP TYPE test_enum
> ```

Can we test dropping enum values using `ALTER TYPE test_enum ... DROP TYPE` as well? I was hoping for a test like: 

```
CREATE TYPE abc AS ENUM ('a', 'b', 'c'); 
CREATE TABLE t(k INT PRIMARY KEY, v abc ON UPDATE 'a'); 
ALTER TYPE abc DROP VALUE 'b' <-- should work because the enum isn't being used in a row/an expression.
ALTER TYPE abc DROP VALUE 'a' <--- should not work because 'a' is being used in the `ON UPDATE` expression of t.
```


<!-- Sent from Reviewable.io -->

2021-08-23 13:50 UTC, ajwerner reviewed
It's close. Let's clean up the `ALTER TABLE` logic a bit more. The code in the two cases smells. 

> Reviewed 3 of 16 files at r1, 6 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-:-MhnGTyP8dSMaEcAYVUo:b-x1z5v6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @mgartner, @pawalt, and @postamar)

___
*[pkg/sql/alter_table.go, line 1199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPekVK54ODCkkA5nUV:-MhnDJT-8OQRphJ_2MDm:bvt8y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/alter_table.go#L1199)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Done.

I realized I needed to take into account both DEFAULT and ON UPDATE expressions when recalculating sequence dependencies, so I've factored that logic out into an `updateSequenceDependencies` function. I think I'm doing the updating properly, but if someone could sanity-check it, that'd be great.

I added tests for this case at the bottom of my `on_update` logic test.
</blockquote></details>

The code in these two cases remains heavily duplicated. Can we deduplicate them further? 
___
*[pkg/sql/create_table.go, line 2198 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhnC8iSBIvYmsne4vU-:-MhnC8iSBIvYmsne4vU0:bk63wlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b08dce3b1acc101a540cb444f60e7e117a05291/pkg/sql/create_table.go#L2198)):*
> ```
> 	if err := tabledesc.ValidateOnUpdate(desc.AllColumns(), desc.GetOutboundFKs()); err != nil {
> 		return nil, err
> 	}
> ```
why was this call added here?
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 1 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhnFxln9tMspilhMs2l:-MhnFxln9tMspilhMs2m:b-iojpue) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b08dce3b1acc101a540cb444f60e7e117a05291/pkg/sql/logictest/testdata/logic_test/on_update#L1)):*
> ```
> statement ok
> ```

nit: use `subtest` in this file for the various feature subtests like sequences, enums, show etc. 


<!-- Sent from Reviewable.io -->

2021-08-23 15:35 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @mgartner, and @postamar)

___
*[pkg/sql/alter_table.go, line 1199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPekVK54ODCkkA5nUV:-MhndOHwCQ3_zhM5HHB8:b2xk2az) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/alter_table.go#L1199)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The code in these two cases remains heavily duplicated. Can we deduplicate them further? 
</blockquote></details>

I deduped parsing, but I'm not sure how far I can go from here. Let me know if there's anywhere else I should factor out. 
___
*[pkg/sql/create_table.go, line 2198 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhnC8iSBIvYmsne4vU-:-MhnM9WiC_IP2paVjKFv:bdj856d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b08dce3b1acc101a540cb444f60e7e117a05291/pkg/sql/create_table.go#L2198)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	if err := tabledesc.ValidateOnUpdate(desc.AllColumns(), desc.GetOutboundFKs()); err != nil {
> 		return nil, err
> 	}
> ```
why was this call added here?
</blockquote></details>

Before returning the table descriptor, we need to ensure that ON UPDATE expressions don't conflict with ON UPDATE FK actions. We need to return an error instead of failing with a `vea.Report` because we want this error reported to the user.

I put the validation here instead of at a higher level because if you just inspect the create statement, you have to handle both inline FKs and explicit FKs. If I wait until the descriptor is created, I can just iterate over all FKs.
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 297 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-Mh_GBcG3mAZ6hYFVo-p:-MhnMs8-54uVRpy6YYWw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b08dce3b1acc101a540cb444f60e7e117a05291/pkg/sql/logictest/testdata/logic_test/on_update#L297)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

You mean test_enum?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-Mh_GIUM50Vz5w_UXps-:-MhnPjOa5fd3vI7bHsj2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b08dce3b1acc101a540cb444f60e7e117a05291/pkg/sql/logictest/testdata/logic_test/on_update#L299)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we test dropping enum values using `ALTER TYPE test_enum ... DROP TYPE` as well? I was hoping for a test like: 

```
CREATE TYPE abc AS ENUM ('a', 'b', 'c'); 
CREATE TABLE t(k INT PRIMARY KEY, v abc ON UPDATE 'a'); 
ALTER TYPE abc DROP VALUE 'b' <-- should work because the enum isn't being used in a row/an expression.
ALTER TYPE abc DROP VALUE 'a' <--- should not work because 'a' is being used in the `ON UPDATE` expression of t.
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-23 16:48 UTC, ajwerner reviewed
> Reviewed 1 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @mgartner, @postamar, and @rytaft)

___
*[pkg/sql/alter_table.go, line 1199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPekVK54ODCkkA5nUV:-MhnfNGBDHrMqHGm4ShB:bnf12ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/alter_table.go#L1199)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I deduped parsing, but I'm not sure how far I can go from here. Let me know if there's anywhere else I should factor out. 
</blockquote></details>

I've been mulling this a bit and I think the ugliness comes from trying to avoid parsing and type-checking the expression again inside of `updateSequenceDependencies`. I don't think you need to worry about that. This logic where we remove them all first is a bit sad but it was pre-existing so whatever. That can get pushed down into your helper too. So, given that, imagine:


```go
func updateNonComputedColumnExpr(
    params runParams, tab *tabledesc.Mutable, col catalog.Column,  op string, newExpr tree.Expr, exprToUpdate **string,
) error {
    	// If a DEFAULT or ON UPDATE expression starts using a sequence and is then
	// modified to not use that sequence, we need to drop the dependency from
	// the sequence to the column. The way this is done is by wiping all
	// sequence dependencies on the column and then recalculating the
	// dependencies after the new expression has been parsed.
	if col.NumUsesSequences() > 0 {
		if err := params.p.removeSequenceDependencies(params.ctx, tableDesc, col); err != nil {
			return err
		}
	}
        if expr == nil {
		*exprToUpdate = nil
	} else {
 		_, s, err = sanitizeColumnExpression(params, t.Expr, col, op)
		if err != nil {
			return err
		}
		*exprToUpdate = &s
 	}
        if err := updateSequenceDependencies(params, tab, col); err != nil {
 	 	return err
 	}
}

func updateSequenceDependencies(
	params runParams,
	tableDesc *tabledesc.Mutable,
	colDesc catalog.Column,
) error {
    var changedSeqDescs []*tabledesc.Mutable
    mergeIntoChanged := func(toAdd []*tabledesc.Mutable) {
        changedSeqDescs = append(changedSeqDescs, toAdd...)
        sort.Slice(
            changedSeqDescs,
            func(i, j int)  bool { return changedSeqDescs[i].GetID() < changedSeqDescs[j].GetID() },
        )
        truncated := changedSeqDescs[:0]
        for i, d := range changedSeqDescs {
            if i == 0 || changedSeqDescs[i-1].GetID() != d.GetID() {
                truncated = append(truncated, d)
            }
        }
        changedSeqDescs = truncated
    }
    for _, colExpr := range []struct {
        name string
        exists func(catalog.Column) bool
        get func(catalog.Column) string
    } {
        {"ON UPDATE", (catalog.Column).HasOnUpdate, (catalog.Column).GetOnUpdate},
        {"DEFAULT", (catalog.Column).HasDefault, (catalog.Column).GetDefault},
    } {
                if !colExpr.exists(col) {
                    continue
                }
		expr, _, err := sanitizeColumnExpression(params, colExpr.get(col), col, colExpr.name)
		if err != nil {
			return err
		}
        	// Get sequence references from DEFAULT expression.
		changedSeqDescsFromExpr, err := maybeAddSequenceDependencies(
			params.ctx,
			params.p.ExecCfg().Settings,
			params.p,
			tableDesc,
			colDesc.ColumnDesc(),
			expr,
			nil, /* backrefs */
		)
		if err != nil {
			return err
		}
                mergeIntoChanged(changedSeqDescsFromExpr)
    }
	for _, changedSeqDesc := range changedSeqDescs {
		if err := params.p.writeSchemaChange(
			params.ctx, changedSeqDesc, descpb.InvalidMutationID,
			fmt.Sprintf("updating dependent sequence %s(%d) for table %s(%d)",
				changedSeqDesc.Name, changedSeqDesc.ID, tableDesc.Name, tableDesc.ID,
			)); err != nil {
			return err
     }

}
```


<!-- Sent from Reviewable.io -->

2021-08-23 17:15 UTC, arulajmani approved these changes
The interactions with `ALTER TYPE ... DROP VALUE` <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> . Looks like this is quite close! 

> Reviewed 2 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-:-Mho-Qs37ZQDlIbrkG6J:b-7md863)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @mgartner, @pawalt, @postamar, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 336 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhnzJob8X3c1KFKtW_2:-MhnzJob8X3c1KFKtW_3:bjtb5r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bff19a2992e8009b5037413d63046d5d4987a39/pkg/sql/logictest/testdata/logic_test/on_update#L336)):*
> ```
> statement ok
> ALTER TABLE test_table_enum ALTER COLUMN k DROP ON UPDATE
> ```

nit: Let's remove the `pk2` row (so that 'x' is unused) and do an `ALTER TYPE test_enum DROP VALUE 'x'` and make sure that succeeds. 
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 337 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhnydcH4bAhQwBOnxTH:-MhnydcH4bAhQwBOnxTI:b83bq9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bff19a2992e8009b5037413d63046d5d4987a39/pkg/sql/logictest/testdata/logic_test/on_update#L337)):*
> ```
> ALTER TABLE test_table_enum ALTER COLUMN k DROP ON UPDATE
> 
> # Make sure that our DEFAULT has a dependency on test_seq
> ```

nit: test_enum


<!-- Sent from Reviewable.io -->

2021-08-23 17:55 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @mgartner, @postamar, and @rytaft)

___
*[pkg/sql/alter_table.go, line 1199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPekVK54ODCkkA5nUV:-Mho7k2g0YkCsuOXlK5-:bfvxmx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/alter_table.go#L1199)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I've been mulling this a bit and I think the ugliness comes from trying to avoid parsing and type-checking the expression again inside of `updateSequenceDependencies`. I don't think you need to worry about that. This logic where we remove them all first is a bit sad but it was pre-existing so whatever. That can get pushed down into your helper too. So, given that, imagine:


```go
func updateNonComputedColumnExpr(
    params runParams, tab *tabledesc.Mutable, col catalog.Column,  op string, newExpr tree.Expr, exprToUpdate **string,
) error {
    	// If a DEFAULT or ON UPDATE expression starts using a sequence and is then
	// modified to not use that sequence, we need to drop the dependency from
	// the sequence to the column. The way this is done is by wiping all
	// sequence dependencies on the column and then recalculating the
	// dependencies after the new expression has been parsed.
	if col.NumUsesSequences() > 0 {
		if err := params.p.removeSequenceDependencies(params.ctx, tableDesc, col); err != nil {
			return err
		}
	}
        if expr == nil {
		*exprToUpdate = nil
	} else {
 		_, s, err = sanitizeColumnExpression(params, t.Expr, col, op)
		if err != nil {
			return err
		}
		*exprToUpdate = &s
 	}
        if err := updateSequenceDependencies(params, tab, col); err != nil {
 	 	return err
 	}
}

func updateSequenceDependencies(
	params runParams,
	tableDesc *tabledesc.Mutable,
	colDesc catalog.Column,
) error {
    var changedSeqDescs []*tabledesc.Mutable
    mergeIntoChanged := func(toAdd []*tabledesc.Mutable) {
        changedSeqDescs = append(changedSeqDescs, toAdd...)
        sort.Slice(
            changedSeqDescs,
            func(i, j int)  bool { return changedSeqDescs[i].GetID() < changedSeqDescs[j].GetID() },
        )
        truncated := changedSeqDescs[:0]
        for i, d := range changedSeqDescs {
            if i == 0 || changedSeqDescs[i-1].GetID() != d.GetID() {
                truncated = append(truncated, d)
            }
        }
        changedSeqDescs = truncated
    }
    for _, colExpr := range []struct {
        name string
        exists func(catalog.Column) bool
        get func(catalog.Column) string
    } {
        {"ON UPDATE", (catalog.Column).HasOnUpdate, (catalog.Column).GetOnUpdate},
        {"DEFAULT", (catalog.Column).HasDefault, (catalog.Column).GetDefault},
    } {
                if !colExpr.exists(col) {
                    continue
                }
		expr, _, err := sanitizeColumnExpression(params, colExpr.get(col), col, colExpr.name)
		if err != nil {
			return err
		}
        	// Get sequence references from DEFAULT expression.
		changedSeqDescsFromExpr, err := maybeAddSequenceDependencies(
			params.ctx,
			params.p.ExecCfg().Settings,
			params.p,
			tableDesc,
			colDesc.ColumnDesc(),
			expr,
			nil, /* backrefs */
		)
		if err != nil {
			return err
		}
                mergeIntoChanged(changedSeqDescsFromExpr)
    }
	for _, changedSeqDesc := range changedSeqDescs {
		if err := params.p.writeSchemaChange(
			params.ctx, changedSeqDesc, descpb.InvalidMutationID,
			fmt.Sprintf("updating dependent sequence %s(%d) for table %s(%d)",
				changedSeqDesc.Name, changedSeqDesc.ID, tableDesc.Name, tableDesc.ID,
			)); err != nil {
			return err
     }

}
```

</blockquote></details>

Ah thanks for the help; that makes sense. Implemented.


<!-- Sent from Reviewable.io -->

2021-08-23 18:25 UTC, ajwerner reviewed
This is getting very close. Just tiny things from me left. 

> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-:-MhoF_3494k_PAXMbMpz:b-5eqswr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @mgartner, @pawalt, @postamar, and @rytaft)

___
*[pkg/sql/alter_table.go, line 1144 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoD0uTC7UjmhpUe5_H:-MhoD0uTC7UjmhpUe5_I:b-7msoa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/alter_table.go#L1144)):*
> ```Go
> 
> 	case *tree.AlterTableSetDefault:
> 		err := updateNonComputedColExpr(
> ```

nit: scope `err` to the conditional here and at the other invocation site. 
```
if err := updateNonComputedColExpr(
    /* ... */,
); err != nil {
   return err
}
```
___
*[pkg/sql/alter_table.go, line 1291 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoDHscDl6m_ALUYq8H:-MhoDHscDl6m_ALUYq8I:b-kgopgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/alter_table.go#L1291)):*
> ```Go
> 
> // updateNonComputedColExpr updates an ON UPDATE or DEFAULT column expression
> // and recalculates sequence dependencies for the column.
> ```

nit: say more here about what is `exprField`
___
*[pkg/sql/alter_table.go, line 1341 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoDOKM8mFKInScKUYC:-MhoDOKM8mFKInScKUYD:bf84ci3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/alter_table.go#L1341)):*
> ```Go
> 
> 	s := tree.Serialize(typedExpr)
> ```

nit: remove this stray line
___
*[pkg/sql/create_table.go, line 2198 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhnC8iSBIvYmsne4vU-:-MhoFSwz9zYm8IrmF4vH:bj6yjo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b08dce3b1acc101a540cb444f60e7e117a05291/pkg/sql/create_table.go#L2198)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Before returning the table descriptor, we need to ensure that ON UPDATE expressions don't conflict with ON UPDATE FK actions. We need to return an error instead of failing with a `vea.Report` because we want this error reported to the user.

I put the validation here instead of at a higher level because if you just inspect the create statement, you have to handle both inline FKs and explicit FKs. If I wait until the descriptor is created, I can just iterate over all FKs.
</blockquote></details>

Ack, give this a bit of commentary.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 670 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhOiF4LVKnXkWPd4hPy-r1-670:-MhoE7Ff7ZaTUJqIdG7h:bdyhu18) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/catalog/tabledesc/validate.go#L670)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Ah didn't know that. Changed.

I could build up a single error string with all the ON UPDATE validation errors in it, but I'm not sure how idiomatic that is. Does that sound reasonable? It's the only way I can think of to reuse this code off the top of my head.
</blockquote></details>

Use `errors.CombineErrors` to combine them all. 
___
*[pkg/sql/catalog/tabledesc/validate.go, line 654 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoEuBODr_sFMobzv5a:-MhoEuBPD1yc6jJ-_ahw:b1ljqgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/catalog/tabledesc/validate.go#L654)):*
> ```Go
> // ValidateOnUpdate returns an error if there is a column with both a foreign
> // key constraint and an ON UPDATE expression, nil otherwise.
> func ValidateOnUpdate(cols []catalog.Column, outboundFks []descpb.ForeignKeyConstraint) error {
> ```

how would you feel about using `catalog.TableColSet` to construct the set of columns which have an `OnUpdate` clause so we only iterate each fk one time? 


<!-- Sent from Reviewable.io -->

2021-08-23 18:52 UTC, mgartner reviewed
> Reviewed 3 of 16 files at r1, 14 of 17 files at r2, 1 of 5 files at r3, 3 of 4 files at r5, 3 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @mgartner, @pawalt, @postamar, and @ZhouXing19)

___
*[pkg/sql/catalog/descpb/structured.proto, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPgKLQ-t2ALRY6dvB_:-MhoDK5G1t7mdu-q8VZt:b-zd1oog) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/catalog/descpb/structured.proto#L145)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I added validation by updating `ForEachExprStringInTableDesc` and adding a test. Is there other validation I should be doing? The test I added covers referencing nonexistent descriptors.
</blockquote></details>

We should add validation for invalid `ON UPDATE` column descriptors in `validateColumns`. For example, we should validate that a column is not both computed and has an `ON UPDATE` expression.  We probably want to disallow `GENERATED [ALWAYS | BY DEFAULT] AS IDENTITY` (currently being worked on by @zhouxing19, so this can be added by one of you once both syntaxes land in master) and `ON UPDATE`. Are there other cases where an `ON UPDATE` column descriptor would be invalid?
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPf6ueDaf0S1Q5yUpp:-MhoEVGn9dgMOmMSJPS_:b-q9apu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/logictest/testdata/logic_test/on_update#L110)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Added. Any specific other cases I should be looking out for?
</blockquote></details>

A common one that is missed is `CREATE TABLE cpy (LIKE t INCLUDING ...)`. For example, see the `CREATE TABLE ... LIKE` expression index tests: https://github.com/cockroachdb/cockroach/blob/1ba6a4b68181cbfa881e818ba619e98db2426a38/pkg/sql/logictest/testdata/logic_test/expression_index#L325-L448

I'm not sure which `INCLUDING` options should copy the `ON UPDATE` to the new table. `DEFAULT` expressions are only copied if `INCLUDING DEFAULTS` or `INCLUDING ALL` is provided. I'd suggest creating an issue for this and addressing it in a follow-up PR to avoid bloating this one and because there's some questions here with unclear answers.
___
*[pkg/sql/opt/optbuilder/insert.go, line 386 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoH_Rp0dzLJjQDCKkG:-MhoH_Rq6sZ4dmd_TIFG:bueya57) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/opt/optbuilder/insert.go#L386)):*
> ```Go
> 		}
> 		if mb.tab.Column(i).HasOnUpdate() {
> 			return true
> ```

I'm struggling to understand why an `ON UPDATE` columns requires existing columns to be fetched in all cases. 
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPhID59xd4njb-g2GU:-MhoJVi3Bw3vq_EYZ-VV:b8eau4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/opt/optbuilder/mutation_builder.go#L1205)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Gave this a shot; Let me know how it looks
</blockquote></details>

I like it!
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1220 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoJ_YSAcIs8gaSlWu-:-MhoJ_YSAcIs8gaSlWu0:b-gucvpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/opt/optbuilder/mutation_builder.go#L1220)):*
> ```Go
> 		exprStr = tabCol.DefaultExprStr()
> 	case columnParseTypeOnUpdate:
> 		exprStr = tabCol.OnUpdateExprStr()
> ```

nit: you could add exprStr as an argument to `parseColExpr` and remove `columnParseType` entirely. Then `parseColExpr` is truly general and I think the code would be cleaned up a bit too.
___
*[pkg/sql/opt/optbuilder/testdata/upsert, line 61 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoKhiL2a_E1AKUXiwx:-MhoKhiL2a_E1AKUXiwy:byw48xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/opt/optbuilder/testdata/upsert#L61)):*
> ```
> exec-ddl
> CREATE TABLE on_update_bare (
>     a INT NOT NULL UNIQUE,
> ```

`UPSERT` with a `rowid` PK is making the tests confusing, and maybe not testing what you want. Is there a reason you omitted an explicit PK here?


<!-- Sent from Reviewable.io -->

2021-08-23 22:56 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @arulajmani, @mgartner, @postamar, and @ZhouXing19)

___
*[pkg/sql/catalog/descpb/structured.proto, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPgKLQ-t2ALRY6dvB_:-MhpCDr48w8k54GopFRN:b-afqs1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/catalog/descpb/structured.proto#L145)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We should add validation for invalid `ON UPDATE` column descriptors in `validateColumns`. For example, we should validate that a column is not both computed and has an `ON UPDATE` expression.  We probably want to disallow `GENERATED [ALWAYS | BY DEFAULT] AS IDENTITY` (currently being worked on by @zhouxing19, so this can be added by one of you once both syntaxes land in master) and `ON UPDATE`. Are there other cases where an `ON UPDATE` column descriptor would be invalid?
</blockquote></details>

The only column-local validation that is needed are the computed column check and the GENERATED check. We need to do the foreign key check too, but that requires a tabledesc.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 670 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhOiF4LVKnXkWPd4hPy-r1-670:-Mhp7ZTZ1qMyBUh8IFtK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/catalog/tabledesc/validate.go#L670)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Use `errors.CombineErrors` to combine them all. 
</blockquote></details>

Done.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 654 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoEuBODr_sFMobzv5a:-Mhp8TZz9hos1V0ZSaXa:bctpdcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/catalog/tabledesc/validate.go#L654)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

how would you feel about using `catalog.TableColSet` to construct the set of columns which have an `OnUpdate` clause so we only iterate each fk one time? 
</blockquote></details>

Makes sense. Done.
___
*[pkg/sql/logictest/testdata/logic_test/on_update, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhPf6ueDaf0S1Q5yUpp:-MhpBQyP89Ve3BQFXGcC:bbp45v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb65355f13e4433f28efeb14d07d916675b7184a/pkg/sql/logictest/testdata/logic_test/on_update#L110)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

A common one that is missed is `CREATE TABLE cpy (LIKE t INCLUDING ...)`. For example, see the `CREATE TABLE ... LIKE` expression index tests: https://github.com/cockroachdb/cockroach/blob/1ba6a4b68181cbfa881e818ba619e98db2426a38/pkg/sql/logictest/testdata/logic_test/expression_index#L325-L448

I'm not sure which `INCLUDING` options should copy the `ON UPDATE` to the new table. `DEFAULT` expressions are only copied if `INCLUDING DEFAULTS` or `INCLUDING ALL` is provided. I'd suggest creating an issue for this and addressing it in a follow-up PR to avoid bloating this one and because there's some questions here with unclear answers.

</blockquote></details>

#69258
___
*[pkg/sql/opt/optbuilder/insert.go, line 386 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoH_Rp0dzLJjQDCKkG:-Mhp8_pN41rk1Qi3Vybk:b-j4mz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/opt/optbuilder/insert.go#L386)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm struggling to understand why an `ON UPDATE` columns requires existing columns to be fetched in all cases. 
</blockquote></details>

They don't; this was leftover from some testing. Thanks for the catch.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1220 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoJ_YSAcIs8gaSlWu-:-Mhp9pZVDNZN-7SrhSuB:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/opt/optbuilder/mutation_builder.go#L1220)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you could add exprStr as an argument to `parseColExpr` and remove `columnParseType` entirely. Then `parseColExpr` is truly general and I think the code would be cleaned up a bit too.
</blockquote></details>

Good point. Done.
___
*[pkg/sql/opt/optbuilder/testdata/upsert, line 61 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhoKhiL2a_E1AKUXiwx:-MhpA2Rf3aJnbARHGUY2:b-sl35py) ([raw file](https://github.com/cockroachdb/cockroach/blob/c09ec39568174fa66dbdb7277197040a8e9064db/pkg/sql/opt/optbuilder/testdata/upsert#L61)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`UPSERT` with a `rowid` PK is making the tests confusing, and maybe not testing what you want. Is there a reason you omitted an explicit PK here?
</blockquote></details>

Nope no reason. Fixed.


<!-- Sent from Reviewable.io -->

2021-08-23 23:38 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-:-MhpNMP69pss-aHjz8Zw:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @arulajmani, @mgartner, @pawalt, @postamar, and @ZhouXing19)

___
*[pkg/sql/catalog/tabledesc/validate.go, line 747 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhpN0c78LFFIfpKHwEb:-MhpN0c78LFFIfpKHwEc:b-8soj1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/734929014f3b37445a17d8eb09725ed8bb7e4ee7/pkg/sql/catalog/tabledesc/validate.go#L747)):*
> ```Go
> 			return errors.Newf(
> 				"computed column %q cannot also have an ON UPDATE expression",
> 				column.GetName(),
> ```

nit: you can add a unit test for this here: https://github.com/cockroachdb/cockroach/blob/6e3438f6055730d80cb430283a3e85f7503c9e18/pkg/sql/catalog/tabledesc/validate_test.go#L312
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1222 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhpLnYn6xeMem5-n-3E:-MhpLnYn6xeMem5-n-3F:b-vh2swz) ([raw file](https://github.com/cockroachdb/cockroach/blob/734929014f3b37445a17d8eb09725ed8bb7e4ee7/pkg/sql/opt/optbuilder/mutation_builder.go#L1222)):*
> ```Go
> 	// If we were not able to find the expression type we were looking for, return
> 	// NULL or a default value.
> 	if exprStr == "" {
> ```

I'm thinking this block may be better suited within `parseDefaultExpr`, since I believe it only applies in that case. It'll also be safer to not assume some default values for empty computed columns and `ON UPDATE` columns. Sorry for not catching this earlier.
___
*[pkg/sql/opt/optbuilder/testdata/upsert, line 1966 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhpMZCg9Y8i2gTRcH8n:-MhpMZCg9Y8i2gTRcH8o:bs859mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/734929014f3b37445a17d8eb09725ed8bb7e4ee7/pkg/sql/opt/optbuilder/testdata/upsert#L1966)):*
> ```
> 
> build
> UPSERT INTO on_update_bare VALUES (1, 2)
> ```

Does it make sense to add a test like `UPSERT INTO on_update_bare VALUES (1)`?


<!-- Sent from Reviewable.io -->

2021-08-24 05:11 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-:-MhqZH5A0pG3XnB9CKxK:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @arulajmani, @mgartner, @pawalt, @postamar, and @ZhouXing19)



<!-- Sent from Reviewable.io -->

2021-08-24 14:16 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @arulajmani, @mgartner, @postamar, and @ZhouXing19)

___
*[pkg/sql/opt/optbuilder/testdata/upsert, line 1966 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhpMZCg9Y8i2gTRcH8n:-MhsW5Hg3eqN-LJlrZ-d:b2nhswv) ([raw file](https://github.com/cockroachdb/cockroach/blob/734929014f3b37445a17d8eb09725ed8bb7e4ee7/pkg/sql/opt/optbuilder/testdata/upsert#L1966)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does it make sense to add a test like `UPSERT INTO on_update_bare VALUES (1)`?
</blockquote></details>

Yep


<!-- Sent from Reviewable.io -->

2021-08-24 15:55 UTC, mgartner approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69091)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 4 stale) (waiting on @ajwerner, @arulajmani, @mgartner, @pawalt, @postamar, and @ZhouXing19)

___
*[pkg/sql/catalog/tabledesc/validate_test.go, line 1129 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhsrCn8BqTOCod89CYI:-MhsrCn8BqTOCod89CYJ:byc2k6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bb644cb7b0fbc15b7737aeda8fdaa4f964eb722/pkg/sql/catalog/tabledesc/validate_test.go#L1129)):*
> ```Go
> 					{ID: 0, Name: "primary", ColumnIDs: []descpb.ColumnID{1}, ColumnNames: []string{"bar"}},
> 				},
> 				PrimaryIndex: descpb.IndexDescriptor{ID: 1, Name: "bar", KeyColumnIDs: []descpb.ColumnID{1},
> ```

nit: I think you can omit `PrimaryIndex` and `NextIndexID` for brevity.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1192 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69091#-MhsrQ3h39nr43Bj6EaH:-MhsrQ3h39nr43Bj6EaI:b-sowbl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bb644cb7b0fbc15b7737aeda8fdaa4f964eb722/pkg/sql/opt/optbuilder/mutation_builder.go#L1192)):*
> ```Go
> 
> 	// If we were not able to find the expression type we were looking for, return
> 	// NULL or a default value.
> ```

nit: update the comment to match the logic: "If there is no DEFAULT expression return NULL or a default value."


<!-- Sent from Reviewable.io -->

2021-08-24 19:06 UTC, pawalt commented
Failing test is a flake (didn't appear in previous runs, and I haven't changed anything). Going to bors this in.

bors r=arulajmani,mgartner,ajwerner,rytaft

2021-08-24 19:34 UTC, pawalt commented
bors r=arulajmani,mgartner,ajwerner,rytaft

2021-08-24 22:38 UTC, merged