server: create api to query persisted stats by date range
cockroachdb/cockroach pull request #69238
Opened 2021-08-23 14:59 UTC by xinhaoz

Release note (api change):

Create _status/persistedstms endpoint to retrieve persisted
statements from crdb_internal.statement_statistics by
aggregated_ts range. The request expects query string
parameters start and end, which are the date range
in unix time.

The response returned is currently the response expected
by the get all statements api for frontend compatibility.

2021-08-23 14:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/69238)
<!-- Reviewable:end -->

2021-08-23 21:40 UTC, maryliag requested changes
> Reviewed 1 of 5 files at r1, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @xinhaoz)

___
*[-- commits, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhouiv48KCtkrSPuesW:-Mhouiv528oW-DHhb2pj:b-ou6g8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/-- commits#L15)):*
Release justification: Category 2 low-risk updates to new functionality
___
*[pkg/server/persisted_statement_stats.go, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhovVVi1aidFy7LcznE:-MhovVVi1aidFy7LcznF:b-33uc53) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L1)):*
> ```Go
> // Copyright 2021 The Cockroach Authors.
> ```

nit: update the file name to be combined_statements_stats
___
*[pkg/server/persisted_statement_stats.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhovOFr7tenhBrCFDml:-MhovOFr7tenhBrCFDmm:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L41)):*
> ```Go
> 	startTime := timeutil.Unix(req.Start, 0)
> 	endTime := timeutil.Unix(req.End, 0)
> ```

nit: remove blank line
___
*[pkg/server/persisted_statement_stats.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhovQTG2jGLnB4UxIoC:-MhovQTG2jGLnB4UxIoD:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L43)):*
> ```Go
> 
> 	statements, err := collectCombinedStatements(ctx, s.internalExecutor, startTime, endTime)
> ```

nit: remove blank line
___
*[pkg/server/persisted_statement_stats.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhowBHQ8JvczRx9BUmb:-MhowBHQ8JvczRx9BUmc:b-pnpkxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L61)):*
> ```Go
> 
> func collectCombinedStatements(
> 	ctx context.Context, ie *sql.InternalExecutor, start time.Time, end time.Time,
> ```

we should treat start and end as optional and only add to the query if we have a value for it. This way is more generic and we can use in different cases (e.g. everything before a date, everything after a date, data between two dates and data with no restriction)
___
*[pkg/server/persisted_statement_stats.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhovvkK1WIhtmJpZJCt:-MhovvkK1WIhtmJpZJCu:b9u4y6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L111)):*
> ```Go
> 			Key: serverpb.StatementsResponse_ExtendedStatementStatisticsKey{
> 				KeyData: metadata.Key,
> 				NodeID:  roachpb.NodeID(0),
> ```

what is this 0 for?
___
*[pkg/server/persisted_statement_stats.go, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhow3b7EPDophPOmlH6:-Mhow3b7EPDophPOmlH7:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L118)):*
> ```Go
> 
> 		statements = append(statements, stmt)
> ```

nit: remove blank line
___
*[pkg/server/persisted_statement_stats.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhowrT43so46aXn-o0D:-MhowrT43so46aXn-o0E:bbdwd0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L129)):*
> ```Go
> 
> func collectCombinedTransactions(
> 	ctx context.Context, ie *sql.InternalExecutor, start time.Time, end time.Time,
> ```

similar to statements, start and end should be optional and properly handled 
___
*[pkg/server/persisted_statement_stats.go, line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhox0cE4LSIziARWEKf:-Mhox0cE4LSIziARWEKg:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L163)):*
> ```Go
> 
> 		app := string(tree.MustBeDString(row[0]))
> ```

nit: remove blank line
___
*[pkg/server/persisted_statement_stats.go, line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhox2enCRWrAiBgUDIr:-Mhox2enCRWrAiBgUDIs:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L193)):*
> ```Go
> 
> 		transactions = append(transactions, stmt)
> ```

nit: remove blank line


<!-- Sent from Reviewable.io -->

2021-08-23 22:31 UTC, Azhng requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[pkg/server/persisted_statement_stats.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhowrT43so46aXn-o0D:-Mhp5ROCEy50qe8fU88-:b-j1c7j1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L129)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

similar to statements, start and end should be optional and properly handled 
</blockquote></details>

:+1:

also nit: you can do 

``` golang
func collectedCombinedTransactions(
  ctx context.Context, ie sqlutil.InternalExecutor, start, end time.Time,
) ...
```
___
*[pkg/server/persisted_statement_stats.go, line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp4CH64bpI-Dyo6xXi:-Mhp4CH64bpI-Dyo6xXj:bp4elqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L61)):*
> ```Go
> 
> func collectCombinedStatements(
> 	ctx context.Context, ie *sql.InternalExecutor, start time.Time, end time.Time,
> ```

nit: use `sqlutils.InternalExecutor` interface
___
*[pkg/server/persisted_statement_stats.go, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6uRBBLpYqDP8zweK:-Mhp6uRBBLpYqDP8zweL:bwv4xer) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L95)):*
> ```Go
> 
> 		var stats roachpb.StatementStatistics
> 		statsJson := tree.MustBeDJSON(row[1]).JSON
> ```

nit: personally i think we should use `JSON` since it's an acronym 
___
*[pkg/server/persisted_statement_stats.go, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6k2G5SEGSImeQiZO:-Mhp6k2G5SEGSImeQiZP:bqfrm0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L134)):*
> ```Go
> 	query :=
> 		`SELECT
> 				app_name,
> ```

nit: master now has `fingerprint_id` field added to the protobuf message, let's also select that column as well.
___
*[pkg/server/persisted_statement_stats.go, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6RxvEsG5y8Ne60Qj:-Mhp6RxvEsG5y8Ne60Qk:b-q543h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L156)):*
> ```Go
> 	var ok bool
> 	for ok, err = it.Next(ctx); ok; ok, err = it.Next(ctx) {
> 		row := it.Cur()
> ```

check if `row` is nil. It can happen for some reason :shrug: 
___
*[pkg/server/persisted_statement_stats.go, line 162 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6X3X9hvfEjbvMa9I:-Mhp6X3X9hvfEjbvMa9J:b-idhsxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L162)):*
> ```Go
> 		}
> 
> 		app := string(tree.MustBeDString(row[0]))
> ```

also check if you have expected number of columns in your `tree.Datums`
___
*[pkg/server/persisted_statement_stats.go, line 168 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp5vy20CxavbKpzRCl:-Mhp5vy20CxavbKpzRCm:b-9q0eav) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L168)):*
> ```Go
> 		var stats roachpb.TransactionStatistics
> 		statsJson := tree.MustBeDJSON(row[2]).JSON
> 		err = sqlstatsutil.DecodeTxnStatsStatisticsJSON(statsJson, &stats)
> ```

nit: compact this line and the following lines as:

```golang
if err = sqlstatsutil.DecodeTxnStatsStatisticsJSON(statsJSON, &stats); err != nil {
  return nil, err
}
```
___
*[pkg/server/persisted_statement_stats.go, line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp732LClElGtiYr9Dd:-Mhp732LClElGtiYr9De:b-mzq9vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L174)):*
> ```Go
> 		}
> 
> 		var metadata roachpb.CollectedTransactionStatistics
> ```

`roachpb.CollectedTransactionStatistics` contains both metadata and statistics, you only need to create one object and pass it as a pointer to the decoder. See [example](https://github.com/cockroachdb/cockroach/blob/9ba9958b8988e284d8e2e9161b445add38f5bfb3/pkg/sql/sqlstats/persistedsqlstats/txn_reader.go#L135).

Also same goes for the handling for `roachpb.CollectedStatementStatistics`
___
*[pkg/server/persisted_statement_stats.go, line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp67WG7s5ycDYUCAW1:-Mhp67WG7s5ycDYUCAW2:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L176)):*
> ```Go
> 		var metadata roachpb.CollectedTransactionStatistics
> 		metadataJson := tree.MustBeDJSON(row[3]).JSON
> 		err = sqlstatsutil.DecodeTxnStatsMetadataJSON(metadataJson, &metadata)
> ```

ditto
___
*[pkg/server/persisted_statement_stats.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6CmJ9nxKtDsJkSCZ:-Mhp6CmJ9nxKtDsJkSC_:bfgo85h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L182)):*
> ```Go
> 		}
> 
> 		stmt := serverpb.StatementsResponse_ExtendedCollectedTransactionStatistics{
> ```

`s/stmt/txnStats` 
___
*[pkg/server/persisted_statement_stats.go, line 196 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6K0F70DUcHEvSFyR:-Mhp6K0F70DUcHEvSFyS:b-1cpex3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L196)):*
> ```Go
> 	}
> 
> 	if err != nil {
> ```

seems like a redundant error check? Unless I missed something? 
___
*[pkg/server/persisted_statement_stats.go, line 203 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp54jgAJyprVxW7wQY:-Mhp54jgAJyprVxW7wQZ:bo2cw6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L203)):*
> ```Go
> }
> 
> func datumToStmtFingerprintId(datum tree.Datum) (roachpb.StmtFingerprintID, error) {
> ```

this method already exists in `pkg/sql/sqlstats/persistedsqlstats/stmt_reader.go` as a helper function. How about let's refactor this into the `pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil` package?


<!-- Sent from Reviewable.io -->

2021-08-24 13:37 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[pkg/server/persisted_statement_stats.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhowBHQ8JvczRx9BUmb:-MhsGavqDUizD8YZohy0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L61)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

we should treat start and end as optional and only add to the query if we have a value for it. This way is more generic and we can use in different cases (e.g. everything before a date, everything after a date, data between two dates and data with no restriction)
</blockquote></details>

Done.
___
*[pkg/server/persisted_statement_stats.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhovvkK1WIhtmJpZJCt:-MhsHDuO3fstR5UW13aX:b-ypxqez) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L111)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

what is this 0 for?
</blockquote></details>

I thought it might be necessary on the frontend, but I checked and it doesn't seem to be so removed it.
___
*[pkg/server/persisted_statement_stats.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhowrT43so46aXn-o0D:-MhsHM5T1aYF8oVapzd4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7fe6df24ccfd348fcd610b39c6fe4fe1913b6c7/pkg/server/persisted_statement_stats.go#L129)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

:+1:

also nit: you can do 

``` golang
func collectedCombinedTransactions(
  ctx context.Context, ie sqlutil.InternalExecutor, start, end time.Time,
) ...
```
</blockquote></details>

Done.
___
*[pkg/server/persisted_statement_stats.go, line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp4CH64bpI-Dyo6xXi:-MhsGc6G2YRLCNT2UaBd:bvde2e1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L61)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: use `sqlutils.InternalExecutor` interface
</blockquote></details>

The internal executor on statusServer uses sql.InternalExecutor so keeping this as is
___
*[pkg/server/persisted_statement_stats.go, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6k2G5SEGSImeQiZO:-MhsHNAN8Nrb3nw_w39Q:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L134)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: master now has `fingerprint_id` field added to the protobuf message, let's also select that column as well.
</blockquote></details>

Done
___
*[pkg/server/persisted_statement_stats.go, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6RxvEsG5y8Ne60Qj:-MhsHPvAAw3fZJcPug1i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L156)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

check if `row` is nil. It can happen for some reason :shrug: 
</blockquote></details>

Done.
___
*[pkg/server/persisted_statement_stats.go, line 162 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6X3X9hvfEjbvMa9I:-MhsHR-m2JV-2pk9ltbC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L162)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

also check if you have expected number of columns in your `tree.Datums`
</blockquote></details>

Done.
___
*[pkg/server/persisted_statement_stats.go, line 168 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp5vy20CxavbKpzRCl:-MhsHTf_0cePn6Yy_YdA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L168)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: compact this line and the following lines as:

```golang
if err = sqlstatsutil.DecodeTxnStatsStatisticsJSON(statsJSON, &stats); err != nil {
  return nil, err
}
```
</blockquote></details>

Done.
___
*[pkg/server/persisted_statement_stats.go, line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp732LClElGtiYr9Dd:-MhsHVaU0rS1LMwLouc_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L174)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

`roachpb.CollectedTransactionStatistics` contains both metadata and statistics, you only need to create one object and pass it as a pointer to the decoder. See [example](https://github.com/cockroachdb/cockroach/blob/9ba9958b8988e284d8e2e9161b445add38f5bfb3/pkg/sql/sqlstats/persistedsqlstats/txn_reader.go#L135).

Also same goes for the handling for `roachpb.CollectedStatementStatistics`
</blockquote></details>

Done.
___
*[pkg/server/persisted_statement_stats.go, line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp67WG7s5ycDYUCAW1:-MhsHVxfEzSKtiozY77K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L176)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/server/persisted_statement_stats.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6CmJ9nxKtDsJkSCZ:-MhsHXCyA-X9yBxL2GkB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L182)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

`s/stmt/txnStats` 
</blockquote></details>

Done.
___
*[pkg/server/persisted_statement_stats.go, line 196 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6K0F70DUcHEvSFyR:-MhsABbC6AYSadTIbFja:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L196)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

seems like a redundant error check? Unless I missed something? 
</blockquote></details>

Done.
___
*[pkg/server/persisted_statement_stats.go, line 203 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp54jgAJyprVxW7wQY:-MhsDYEK0x1u3evjPm-i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L203)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

this method already exists in `pkg/sql/sqlstats/persistedsqlstats/stmt_reader.go` as a helper function. How about let's refactor this into the `pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil` package?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-24 13:40 UTC, ajwerner reviewed
drive-by review, didn't look at much

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-:-MhsO2jO7dSj0pjWkfiP:b-3nmvg0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[pkg/server/persisted_statement_stats.go, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhsNqQVBNtE_81oZ4wx:-MhsNqQVBNtE_81oZ4wy:b-ko79s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L142)):*
> ```Go
> 				aggregated_ts >= $1 AND aggregated_ts <= $2`
> 
> 	it, err := ie.QueryIteratorEx(ctx, "combined-txns-by-interval", nil,
> ```

You need to make sure you close this iterator. On some of your early return error paths it won't be closed. 
___
*[pkg/server/persisted_statement_stats.go, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhp6RxvEsG5y8Ne60Qj:-MhsNVa4CXQC-LPCtvBi:b-kho2rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5850f444476dd3358097d9c5b9183a33496028/pkg/server/persisted_statement_stats.go#L156)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It really should not happen if `ok` is true. 


<!-- Sent from Reviewable.io -->

2021-08-24 14:07 UTC, maryliag reviewed
> Reviewed 5 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @xinhaoz)

___
*[pkg/server/combined_statement_stats.go, line 74 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhsS74T4L5K1Fi6rUdR:-MhsS74T4L5K1Fi6rUdS:b-ypbrq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f050d531e8c322d5b986eb2d56fa508f80e50d42/pkg/server/combined_statement_stats.go#L74)):*
> ```Go
> 	if start != nil || end != nil {
> 		buffer.WriteString("WHERE ")
> 	}
> ```

nit: since the default case is not having a start and end, you can add a else and return here (so it won't need to do those extra checks)


<!-- Sent from Reviewable.io -->

2021-08-24 14:58 UTC, Azhng reviewed
> Reviewed 2 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[pkg/server/combined_statement_stats.go, line 61 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhsaU9yCmmvQz6P7Ubc:-MhsaU9yCmmvQz6P7Ubd:b407hgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f050d531e8c322d5b986eb2d56fa508f80e50d42/pkg/server/combined_statement_stats.go#L61)):*
> ```Go
> 		Statements:            statements,
> 		Transactions:          transactions,
> 		LastReset:             timeutil.Now(),
> ```

This should use the actual reset time: `s.sqlServer.pgServer.SQLServer.GetSQLStatsProvider().GetLastReset()`
___
*[pkg/server/combined_statement_stats.go, line 74 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhsS74T4L5K1Fi6rUdR:-MhsbVup1A7Z5Ouku7jd:b-q23lom) ([raw file](https://github.com/cockroachdb/cockroach/blob/f050d531e8c322d5b986eb2d56fa508f80e50d42/pkg/server/combined_statement_stats.go#L74)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: since the default case is not having a start and end, you can add a else and return here (so it won't need to do those extra checks)
</blockquote></details>

usually we do explicit checks on the early return paths. E.g.

``` golang
if start == nil && end == nil {
  return "", args
}
```
___
*[pkg/server/combined_statement_stats.go, line 87 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhsdWgBBaO5DaBPHwht:-MhsdWgC9iJioYpY6qsp:bq0j3m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f050d531e8c322d5b986eb2d56fa508f80e50d42/pkg/server/combined_statement_stats.go#L87)):*
> ```Go
> 	if end != nil {
> 		argNum := len(args) + 1
> 		buffer.WriteString(fmt.Sprintf("aggregated_ts <= $%d", argNum))
> ```

minor nit: perhaps just use `len(args) + 1` here to simplify things a tiny bit 
___
*[pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/utils.go, line 18 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhsa1wx6YJC3Pnf-xpa:-Mhsa1wx6YJC3Pnf-xpb:b2h1dmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f050d531e8c322d5b986eb2d56fa508f80e50d42/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/utils.go#L18)):*
> ```Go
> )
> 
> func DatumToUint64(d tree.Datum) (uint64, error) {
> ```

nit: comments on exported function or linter will complain 


<!-- Sent from Reviewable.io -->

2021-08-24 15:46 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[pkg/server/combined_statement_stats.go, line 74 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhsS74T4L5K1Fi6rUdR:-Mhsphoe3wk3dd32BNPD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f050d531e8c322d5b986eb2d56fa508f80e50d42/pkg/server/combined_statement_stats.go#L74)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

usually we do explicit checks on the early return paths. E.g.

``` golang
if start == nil && end == nil {
  return "", args
}
```
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/utils.go, line 18 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhsa1wx6YJC3Pnf-xpa:-MhspGBf2SSCw1vYPkBQ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f050d531e8c322d5b986eb2d56fa508f80e50d42/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/utils.go#L18)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: comments on exported function or linter will complain 
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-08-24 16:45 UTC, Azhng reviewed
Let's write some tests for the new endpoint. Existing test example: `TestStatusAPITransactions`, `TestStatusAPIStatements`. Also you want to implement the same thing in the `tenantStatusServer` in `pkg/server/tenant_status.go` to support serverless. This is a bit annoying but eventually we will replaced the current `statusServer` with the new `tenantStatusServer`. 

> Reviewed 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-:-Mht1m5k7Vml54XLpbXF:bb99736)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[-- commits, line 4 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht-mB0BGFgK1tWwDmk):*
Incomplete release note, also this should be in the last thing in the commit message.
___
*[-- commits, line 6 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht1c6x8ALvYMC71cUN):*
nit: `/_status/persistedstmts`
___
*[-- commits, line 7 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht1hyy7-uzksU0V8qu):*
nit: also `crdb_internal.transaction_statistics` 
___
*[pkg/server/combined_statement_stats.go, line 61 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhsaU9yCmmvQz6P7Ubc:-Mht09bh6OfmBr9KztMR:b-i4fhp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f050d531e8c322d5b986eb2d56fa508f80e50d42/pkg/server/combined_statement_stats.go#L61)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

This should use the actual reset time: `s.sqlServer.pgServer.SQLServer.GetSQLStatsProvider().GetLastReset()`
</blockquote></details>

What about the fix for `LastReset` field? 
___
*[pkg/server/combined_statement_stats.go, line 104 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht0U2fE4illrzHXgjn:-Mht0U2g-tc4CYSyfphy:b6r8ogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a80908371979a72582ffc9c179178458654b26/pkg/server/combined_statement_stats.go#L104)):*
> ```Go
> 				fingerprint_id,
> 				metadata,
> 				statistics
> ```

just realized that you also want to select the `plan` columns from the system table. See [example](https://github.com/cockroachdb/cockroach/blob/08a8eec4e0477e34b3e7cd4d019ff0d2ddd19e98/pkg/sql/sqlstats/persistedsqlstats/stmt_reader.go#L162)

Also we want to select the `aggregated_ts` column as well
___
*[pkg/server/combined_statement_stats.go, line 123 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht0sF84wFOtTdU5G3s:-Mht0sF84wFOtTdU5G3t:b-qj81u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a80908371979a72582ffc9c179178458654b26/pkg/server/combined_statement_stats.go#L123)):*
> ```Go
> 	var statements []serverpb.StatementsResponse_CollectedStatementStatistics
> 	var ok bool
> 	for ok, err = it.Next(ctx); ok; ok, err = it.Next(ctx) {
> ```

nit: this `err` is not checked 
___
*[pkg/server/combined_statement_stats.go, line 198 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht10ED06pntWoi7mb2:-Mht10ED06pntWoi7mb3:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a80908371979a72582ffc9c179178458654b26/pkg/server/combined_statement_stats.go#L198)):*
> ```Go
> 	var transactions []serverpb.StatementsResponse_ExtendedCollectedTransactionStatistics
> 	var ok bool
> 	for ok, err = it.Next(ctx); ok; ok, err = it.Next(ctx) {
> ```

ditto
___
*[pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/utils.go, line 18 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhsa1wx6YJC3Pnf-xpa:-Mht-Lt8E7InCWGHobNk:b-5gdx8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f050d531e8c322d5b986eb2d56fa508f80e50d42/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/utils.go#L18)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Done
</blockquote></details>

super nit: period in the end.


<!-- Sent from Reviewable.io -->

2021-08-24 18:42 UTC, maryliag reviewed
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @xinhaoz)

___
*[-- commits, line 6 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht1c6x8ALvYMC71cUN):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `/_status/persistedstmts`
</blockquote></details>

Archer, the correct api is indeed `/_status/combinedstmts`. Using persisted would imply it returns only persisted, which is not the case, this api is for the combined stmts from in memory and persisted
___
*[pkg/server/combined_statement_stats.go, line 79 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhtSJozC_AR2tH1qw5g:-MhtSJozC_AR2tH1qw5h:bvth4ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb6ebc220deae993598b4e87db767dbbb6e4f91/pkg/server/combined_statement_stats.go#L79)):*
> ```Go
> 
> func getFilterAndParams(start, end *time.Time) (string, []interface{}) {
> 	var buffer strings.Builder
> ```

nit: you can create this variable after your first if, this way it won't be created unnecessarily on default cases


<!-- Sent from Reviewable.io -->

2021-08-24 20:29 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @xinhaoz)

___
*[pkg/server/combined_statement_stats.go, line 61 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhsaU9yCmmvQz6P7Ubc:-Mht4Io64WfVUyzTbJKm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f050d531e8c322d5b986eb2d56fa508f80e50d42/pkg/server/combined_statement_stats.go#L61)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

What about the fix for `LastReset` field? 
</blockquote></details>

Done.
___
*[pkg/server/combined_statement_stats.go, line 104 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht0U2fE4illrzHXgjn:-Mhtpv4g5j830sLCjXtP:bu42225) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a80908371979a72582ffc9c179178458654b26/pkg/server/combined_statement_stats.go#L104)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

just realized that you also want to select the `plan` columns from the system table. See [example](https://github.com/cockroachdb/cockroach/blob/08a8eec4e0477e34b3e7cd4d019ff0d2ddd19e98/pkg/sql/sqlstats/persistedsqlstats/stmt_reader.go#L162)

Also we want to select the `aggregated_ts` column as well
</blockquote></details>

Added to query, and also added aggregated_ts to `ExtendedStatementStatisticsKey` as discussed offline.
Issue created to consolidate `CollectedStatementStatistics`
https://github.com/cockroachdb/cockroach/issues/69326
___
*[pkg/server/combined_statement_stats.go, line 123 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht0sF84wFOtTdU5G3s:-Mht5oWkAkSOI8oTLCzx:bes2kbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a80908371979a72582ffc9c179178458654b26/pkg/server/combined_statement_stats.go#L123)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: this `err` is not checked 
</blockquote></details>

I added the error check below, since ok should be false if there is an error (unless I misunderstood the comments).
 Is there a need to add it here as well as below the for?
___
*[pkg/server/combined_statement_stats.go, line 198 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht10ED06pntWoi7mb2:-Mht61oVDJIlsgKVllD1:bh24ur3) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a80908371979a72582ffc9c179178458654b26/pkg/server/combined_statement_stats.go#L198)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Same here for adding it after the loop.


<!-- Sent from Reviewable.io -->

2021-08-25 02:42 UTC, Azhng reviewed
Nice. Just some minor nits. Also just make sure update your commit message to put the release note in the bottom. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-:-MhvAuZZAThbAbdSDSsl:blkyyiq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[-- commits, line 6 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht1c6x8ALvYMC71cUN):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Archer, the correct api is indeed `/_status/combinedstmts`. Using persisted would imply it returns only persisted, which is not the case, this api is for the combined stmts from in memory and persisted
</blockquote></details>

Good call
___
*[pkg/server/combined_statement_stats.go, line 123 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mht0sF84wFOtTdU5G3s:-MhvAEkaDtyGYe2p-uoo:b-kwphrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/70a80908371979a72582ffc9c179178458654b26/pkg/server/combined_statement_stats.go#L123)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I added the error check below, since ok should be false if there is an error (unless I misunderstood the comments).
 Is there a need to add it here as well as below the for?
</blockquote></details>

fair enough :+1:
___
*[pkg/server/status_test.go, line 1887 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhv8gEzAfFRaC0ov4vk:-Mhv8gEzAfFRaC0ov4vl:b-yibv52) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f98a5958f52c199efe492d27e314ebd569a8f5/pkg/server/status_test.go#L1887)):*
> ```Go
> 
> 	testPath := func(path string, expectedStmts []string) {
> 		// Hit query endpoint.
> ```

nit: run them in subtests, e.g. 

```golang
t.Run(path, func(t *testing.T) {
  // ... 
})
```

Or alternatively you can specify the test name
___
*[pkg/server/status_test.go, line 1888 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhv92FOBQI-miqFnfXF:-Mhv92FOBQI-miqFnfXG:b-lu3ebi) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f98a5958f52c199efe492d27e314ebd569a8f5/pkg/server/status_test.go#L1888)):*
> ```Go
> 	testPath := func(path string, expectedStmts []string) {
> 		// Hit query endpoint.
> 		if err := getStatusJSONProtoWithAdminOption(firstServerProto, path, &resp, false); err != nil {
> ```

nit: `require.NoError(t, err)` can help to reduce the verbosity a bit
___
*[pkg/server/tenant_status.go, line 173 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhv86laBpHlk4ew8XM2:-Mhv86laBpHlk4ew8XM3:b-qd5wvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f98a5958f52c199efe492d27e314ebd569a8f5/pkg/server/tenant_status.go#L173)):*
> ```Go
> 	}
> 
> 	if t.sqlServer.SQLInstanceID() == 0 {
> ```

duplicated code


<!-- Sent from Reviewable.io -->

2021-08-25 13:49 UTC, maryliag reviewed
> Reviewed 6 of 7 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[-- commits, line 15 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhxYjxACYomVrglEvIB):*
nit: don't forget to update the PR description with your updates commit message


<!-- Sent from Reviewable.io -->

2021-08-25 17:34 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @xinhaoz)

___
*[pkg/server/tenant_status.go, line 173 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mhv86laBpHlk4ew8XM2:-MhyLb87BcgJf0XAsDBq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f98a5958f52c199efe492d27e314ebd569a8f5/pkg/server/tenant_status.go#L173)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

duplicated code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-25 18:08 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[pkg/server/serverpb/status.proto, line 1009 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhyUHbD57taSTXYzIli:-MhyUHbD57taSTXYzIlj:bhaficm) ([raw file](https://github.com/cockroachdb/cockroach/blob/825a47fa4a7305f1a83bf85f0a45695f37564e66/pkg/server/serverpb/status.proto#L1009)):*
> ```protobuf
>   string node_id = 1 [(gogoproto.customname) = "NodeID"];
>   // If this field is set we will use the combined statements API instead.
>   bool combined = 2;
> ```

Hmm this is new? :thinking: 

Why not just hit `/_status/combinedstmts` endpoint? Or it's something with the frontend codebase.


<!-- Sent from Reviewable.io -->

2021-08-25 18:26 UTC, Azhng approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-:-MhyZ4S17I39T1imQ8fE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[pkg/server/serverpb/status.proto, line 1009 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhyUHbD57taSTXYzIli:-MhyYwSR2YsijLjAS7t6:bsug21i) ([raw file](https://github.com/cockroachdb/cockroach/blob/825a47fa4a7305f1a83bf85f0a45695f37564e66/pkg/server/serverpb/status.proto#L1009)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm this is new? :thinking: 

Why not just hit `/_status/combinedstmts` endpoint? Or it's something with the frontend codebase.
</blockquote></details>

Discussed offline. This is due to the need for supporting for Serverless. 


<!-- Sent from Reviewable.io -->

2021-08-25 23:47 UTC, maryliag reviewed
> Reviewed 4 of 4 files at r10, 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[pkg/server/status_test.go, line 1948 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhzgSRx467sNyuXRct2:-MhzgSRx467sNyuXRct3:bz6gz8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/825a47fa4a7305f1a83bf85f0a45695f37564e66/pkg/server/status_test.go#L1948)):*
> ```Go
> 	// Test with start = now; should give no results.
> 	testPath(fmt.Sprintf("combinedstmts?start=%d", nowInSecs), nil)
> }
> ```

also add tests for calling statements api with the new options of combined


<!-- Sent from Reviewable.io -->

2021-08-26 13:38 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag and @xinhaoz)

___
*[pkg/server/status_test.go, line 1948 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-MhzgSRx467sNyuXRct2:-Mi1fYIp-hOOyrscpoGZ:b-wypcuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/825a47fa4a7305f1a83bf85f0a45695f37564e66/pkg/server/status_test.go#L1948)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

also add tests for calling statements api with the new options of combined
</blockquote></details>

I added one under the StatementsAPI test


<!-- Sent from Reviewable.io -->

2021-08-26 18:30 UTC, maryliag approved these changes
great! just a very small nits, otherwise <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-:-Mi2iEOf1WSvIIF2q2wW:b-aza8il)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @xinhaoz)

___
*[-- commits, line 11 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi2gIXl3EBxatDFxFdO):*
nit: typo bby/ by
___
*[pkg/server/status_test.go, line 1550 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi2h8MOAkK0Zhof0XlX:-Mi2h8MOAkK0Zhof0XlY:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbf2a5cc99bd82467718fed8bd0e4d6e9b7df90/pkg/server/status_test.go#L1550)):*
> ```Go
> 		}
> 
> 		// Sanity check numeric stat values
> ```

nit: period
___
*[pkg/server/status_test.go, line 1849 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi2hJv63rVOY6_P_1JW:-Mi2hJv63rVOY6_P_1JX:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbf2a5cc99bd82467718fed8bd0e4d6e9b7df90/pkg/server/status_test.go#L1849)):*
> ```Go
> 	}
> 
> 	// Test no params
> ```

nit: period
___
*[pkg/server/status_test.go, line 1851 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi2hLpV66o6sNfcJd2k:-Mi2hLpV66o6sNfcJd2l:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbf2a5cc99bd82467718fed8bd0e4d6e9b7df90/pkg/server/status_test.go#L1851)):*
> ```Go
> 	// Test no params
> 	testPath("statements", expectedStatements)
> 	// Test combined=true forwards to CombinedStatements
> ```

nit: period
___
*[pkg/server/status_test.go, line 1938 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi2hY1E6JjhcMIIya0R:-Mi2hY1E6JjhcMIIya0S:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbf2a5cc99bd82467718fed8bd0e4d6e9b7df90/pkg/server/status_test.go#L1938)):*
> ```Go
> 	}
> 
> 	// Test with no query params
> ```

nit: period


<!-- Sent from Reviewable.io -->

2021-08-26 18:38 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @xinhaoz)

___
*[pkg/server/combined_statement_stats.go, line 61 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi2jCLzEMBSeIyila0a:-Mi2jCLzEMBSeIyila0b:bj9gu5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbf2a5cc99bd82467718fed8bd0e4d6e9b7df90/pkg/server/combined_statement_stats.go#L61)):*
> ```Go
> 	startTime := getTimeFromSeconds(req.Start)
> 	endTime := getTimeFromSeconds(req.End)
> 	statements, err := collectCombinedStatements(ctx, ie, startTime, endTime)
> ```

you need to add a check for this err here, otherwise you might be hitting an error, but the value is replaces on the following line and that one might not have any errors
___
*[pkg/server/combined_statement_stats.go, line 131 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi2jsJL865GWuUux_Bd:-Mi2jsJL865GWuUux_Be:b-93z6d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbf2a5cc99bd82467718fed8bd0e4d6e9b7df90/pkg/server/combined_statement_stats.go#L131)):*
> ```Go
> 	}
> 
> 	defer it.Close()
> ```

you're getting a lint error here: 
defer it.Close() <- unchecked error
___
*[pkg/server/combined_statement_stats.go, line 212 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi2k0CF-Zg1YBZIUpQ7:-Mi2k0CF-Zg1YBZIUpQ8:b-93z6d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbf2a5cc99bd82467718fed8bd0e4d6e9b7df90/pkg/server/combined_statement_stats.go#L212)):*
> ```Go
> 	}
> 
> 	defer it.Close()
> ```

you're getting a lint error here: 
defer it.Close() <- unchecked error


<!-- Sent from Reviewable.io -->

2021-08-26 18:42 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @xinhaoz)

___
*[pkg/server/status_test.go, line 1467 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi2lGD65au1TUiuYZmf:-Mi2lGD65au1TUiuYZmg:byi2oke) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbf2a5cc99bd82467718fed8bd0e4d6e9b7df90/pkg/server/status_test.go#L1467)):*
> ```Go
> 		{
> 			query:         `INSERT INTO posts VALUES (1, 'foo')`,
> 			fingerprinted: `INSERT INTO posts VALUES (_, _)`,
> ```

`INSERT INTO posts VALUES (_, '_')`


<!-- Sent from Reviewable.io -->

2021-08-26 18:52 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @xinhaoz)

___
*[pkg/server/combined_statement_stats.go, line 228 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi2nUCN34PVEo-OkYwo:-Mi2nUCN34PVEo-OkYwp:b-u77z21) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbf2a5cc99bd82467718fed8bd0e4d6e9b7df90/pkg/server/combined_statement_stats.go#L228)):*
> ```Go
> 		app := string(tree.MustBeDString(row[0]))
> 		aggregatedTs := tree.MustBeDTimestampTZ(row[1]).Time
> 		fingerprintID, err := sqlstatsutil.DatumToUint64(row[2])
> ```

you're not checking for the error here


<!-- Sent from Reviewable.io -->

2021-08-27 03:35 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @Azhng, @maryliag, and @xinhaoz)

___
*[pkg/server/status_test.go, line 1444 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi4e_PH45cYOpNnKGuI:-Mi4e_PH45cYOpNnKGuJ:bwwislj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbbf2ea5cb70fa0f30279c64c8ef746de4d6e943/pkg/server/status_test.go#L1444)):*
> ```Go
> 	defer log.Scope(t).Close(t)
> 
> 	testCluster := serverutils.StartNewTestCluster(t, 3, base.TestClusterArgs{})
> ```

Spin up test cluster using:

```golang

params, _ := tests.CreateTestServerParams()

cluster := serverutils.StartNewTestCluster(t, 3 /* numNodes */, base.TestClusterArgs{
	ServerArgs: params,
})
```

This should fix the CI errors for "descriptor not found". 

Same goes for the tenant tests.

---

Explanation: the `tests.CreateTestServerParams()` overrides the `AS OF SYSTEM TIME` clause in the read statement for reading SQL stats from the system table. See: #69346.


<!-- Sent from Reviewable.io -->

2021-08-27 16:23 UTC, maryliag reviewed
> Reviewed 1 of 2 files at r14, 1 of 2 files at r15, 5 of 7 files at r16, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69238)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @xinhaoz)

___
*[pkg/server/status_test.go, line 1554 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi7PsvFC-1fEmYCVPgr:-Mi7PsvFC-1fEmYCVPgs:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/63eb73ab7a4190db34ce6576c8aa6f98fb177ee1/pkg/server/status_test.go#L1554)):*
> ```Go
> 		}
> 
> 		// Sanity check numeric stat values
> ```

nit: period
___
*[pkg/server/status_test.go, line 1859 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi7Pv4yDLoU0MkIz4ni:-Mi7Pv4yDLoU0MkIz4nj:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/63eb73ab7a4190db34ce6576c8aa6f98fb177ee1/pkg/server/status_test.go#L1859)):*
> ```Go
> 	}
> 
> 	// Test no params
> ```

nit: period
___
*[pkg/server/status_test.go, line 1861 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi7Pxcz2282n08EVJSj:-Mi7Pxcz2282n08EVJSk:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/63eb73ab7a4190db34ce6576c8aa6f98fb177ee1/pkg/server/status_test.go#L1861)):*
> ```Go
> 	// Test no params
> 	testPath("statements", expectedStatements)
> 	// Test combined=true forwards to CombinedStatements
> ```

nit: period
___
*[pkg/server/status_test.go, line 1951 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/69238#-Mi7Q04jA52kct3v3OPE:-Mi7Q04jA52kct3v3OPF:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/63eb73ab7a4190db34ce6576c8aa6f98fb177ee1/pkg/server/status_test.go#L1951)):*
> ```Go
> 	}
> 
> 	// Test with no query params
> ```

nit: period


<!-- Sent from Reviewable.io -->

2021-08-28 06:58 UTC, merged