release-21.1: ui: handle new parameters on versions before 21.1.7
cockroachdb/cockroach pull request #69305
Opened 2021-08-24 16:20 UTC by maryliag

Backport 1/1 commits from #69205.

/cc @cockroachdb/release

---

A few changes were backported to 21.1 that added new parameters
to protobuf (`last_exec_timestamp` and `nodes`). To be able to update cluster-ui version on
managed repo, this commit is introducing some checks on the ui,
so when cluster-ui is loaded on versions prior to 21.1.8 it will
not crash

Release justification: Category 2 Bug Fix

Release note (bug fix): Introduce checks on statements and transaction
pages so managed repo can update cluster-ui version.

2021-08-24 16:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/69305)
<!-- Reviewable:end -->

2021-08-25 18:23 UTC, nathanstilwell requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/cluster-ui/src/statementDetails/statementDetails.tsx, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69305#-MhyXEL04ok8Scyc44n3:-MhyXEL04ok8Scyc44n4:b-hpgmrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3619a589e7af13fa88b7f8696782d1c541eabfe/pkg/ui/cluster-ui/src/statementDetails/statementDetails.tsx#L474)):*
> ```XML
>     const duration = (v: number) => Duration(v * 1e9);
>     const hasDiagnosticReports = diagnosticsReports.length > 0;
>     const lastExec =
> ```

Are there any negative consequences of `lastExec` being `undefined`?
___
*[pkg/ui/cluster-ui/src/statementsTable/statementsTable.tsx, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69305#-MhyXih34jCION9uf_rV:-MhyXih34jCION9uf_rW:b-dm09m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3619a589e7af13fa88b7f8696782d1c541eabfe/pkg/ui/cluster-ui/src/statementsTable/statementsTable.tsx#L306)):*
> ```XML
>     if (stmt.stats.nodes) {
>       stmt.stats.nodes.forEach(node => {
>         if (Object.keys(regions).includes(nodeRegions[node.toString()])) {
> ```

If `regions` is defined 5 lines above this one, will this condition ever be true? Is there some other way that `regions` could be anything other than an empty object?


<!-- Sent from Reviewable.io -->

2021-08-25 18:27 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

___
*[pkg/ui/cluster-ui/src/statementDetails/statementDetails.tsx, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69305#-MhyXEL04ok8Scyc44n3:-MhyYdgh9L7aT4kwAExM:b-wqptwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3619a589e7af13fa88b7f8696782d1c541eabfe/pkg/ui/cluster-ui/src/statementDetails/statementDetails.tsx#L474)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

Are there any negative consequences of `lastExec` being `undefined`?
</blockquote></details>

no, is we have the case that is undefined it will just not show the value on the ui, nothing will break
___
*[pkg/ui/cluster-ui/src/statementsTable/statementsTable.tsx, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69305#-MhyXih34jCION9uf_rV:-MhyYwnxBajWNt5ii4d2:bumn1vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3619a589e7af13fa88b7f8696782d1c541eabfe/pkg/ui/cluster-ui/src/statementsTable/statementsTable.tsx#L306)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

If `regions` is defined 5 lines above this one, will this condition ever be true? Is there some other way that `regions` could be anything other than an empty object?
</blockquote></details>

we're doing a loop on all nodes were the statement was executed, so the first time it will never be true, but it can be true to any of the other loop iteration


<!-- Sent from Reviewable.io -->

2021-08-25 18:27 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

___
*[pkg/ui/cluster-ui/src/statementDetails/statementDetails.tsx, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69305#-MhyXEL04ok8Scyc44n3:-MhyZHdWAk8mIuUuhqbR:b-cdwqix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3619a589e7af13fa88b7f8696782d1c541eabfe/pkg/ui/cluster-ui/src/statementDetails/statementDetails.tsx#L474)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

no, is we have the case that is undefined it will just not show the value on the ui, nothing will break
</blockquote></details>

*no, if we


<!-- Sent from Reviewable.io -->

2021-08-25 19:35 UTC, nathanstilwell approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69305)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2021-08-25 23:44 UTC, merged