ui: hide node/regions info on tenants
cockroachdb/cockroach pull request #69444
Opened 2021-08-26 23:45 UTC by maryliag

On tenant clusters we don't want to show information
about nodes and regions.

This commit hides that information on:
- statements page (table, filter, column selector)
- statement details page (overview, exec stats)
- transactions page (table, filter)

Release justification: Category 4
Release note (ui change): Hide node and regions information
on the new tenant plan (serverless / free tier)

2021-08-27 14:04 UTC, matthewtodd requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69444)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @maryliag)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6tpwYA7W5syfc1rDO):*
nit: `s/cluster/clusters`
___
*[pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6u10d2RsAoGzBYdQ3:-Mi6u10d2RsAoGzBYdQ4:bzd6f0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/683176762a92ed3286345b67cef4f3288e42206d/pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx#L59)):*
> ```XML
>   // If true, the user can't overwrite the setting for this column. False if not defined.
>   alwaysShow?: boolean;
>   // If true, it will hide this column if it's tenant cluster. False is not defined.
> ```

nit: "If true, hide this column for tenant clusters. False if not defined."
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6uMBB7EbYepBbJcBS:-Mi6uMBB7EbYepBbJcBT:bfzkx43) ([raw file](https://github.com/cockroachdb/cockroach/blob/683176762a92ed3286345b67cef4f3288e42206d/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L351)):*
> ```XML
>         // list if the list is not empty.
>         // If the cluster is a tenant cluster we don't care
>         // about regions
> ```

nit: trailing period.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6uOyaAwfN8smOwEK5:-Mi6uOyaAwfN8smOwEK6:bfzkx43) ([raw file](https://github.com/cockroachdb/cockroach/blob/683176762a92ed3286345b67cef4f3288e42206d/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L368)):*
> ```XML
>         // list if the list is not empty.
>         // If the cluster is a tenant cluster we don't care
>         // about nodes
> ```

nit: trailing period.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6uRvkEc3Qq2HSk2FI:-Mi6uRvkEc3Qq2HSk2FJ:bfzkx43) ([raw file](https://github.com/cockroachdb/cockroach/blob/683176762a92ed3286345b67cef4f3288e42206d/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L404)):*
> ```XML
>     const isEmptySearchResults = statements?.length > 0 && search?.length > 0;
>     // If the cluster is a tenant cluster we don't show info
>     // about nodes/regions
> ```

nit: trailing period.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6u_rnC-rEknhsduFJ:-Mi6u_rnC-rEknhsduFK:b-wxk8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/683176762a92ed3286345b67cef4f3288e42206d/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L482)):*
> ```XML
>               showScan={true}
>               showRegions={regions.length > 1 && !isTenant}
>               showNodes={nodes.length > 1 && !isTenant}
> ```

Are these clauses redundant with setting `nodes` and `regions` to empty arrays above?
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6uuJA56Bxdhq90uII:-Mi6uuJA56Bxdhq90uIJ:bfzkx43) ([raw file](https://github.com/cockroachdb/cockroach/blob/683176762a92ed3286345b67cef4f3288e42206d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L237)):*
> ```XML
>             );
>             // If the cluster is a tenant cluster we don't show info
>             // about nodes/regions
> ```

nit: trailing period.
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6uy-N3Uqce_K94rKy:-Mi6uy-N3Uqce_K94rKz:b-wxk8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/683176762a92ed3286345b67cef4f3288e42206d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L295)):*
> ```XML
>                       filters={filters}
>                       showRegions={regions.length > 1 && !isTenant}
>                       showNodes={nodes.length > 1 && !isTenant}
> ```

Are these clauses redundant with setting `nodes` and `regions` to empty arrays above?
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6v7Mc2oK6jzuVypI9:-Mi6v7Md-2eH3oD3Z7Oq:bfzkx43) ([raw file](https://github.com/cockroachdb/cockroach/blob/683176762a92ed3286345b67cef4f3288e42206d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L144)):*
> ```XML
>       if (regions.length == 0 && nodes.length == 0) return true;
>       // If the cluster is a tenant cluster we don't care
>       // about node/regions
> ```

nit: trailing period.


<!-- Sent from Reviewable.io -->

2021-08-27 14:15 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69444)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6u_rnC-rEknhsduFJ:-Mi6xX2YCuGIm9U8HpW8:b-kkg7ea) ([raw file](https://github.com/cockroachdb/cockroach/blob/683176762a92ed3286345b67cef4f3288e42206d/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L482)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Are these clauses redundant with setting `nodes` and `regions` to empty arrays above?
</blockquote></details>

Good point, remove here and other cases.
Done
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-Mi6uy-N3Uqce_K94rKy:-Mi6xcZm0AVLRuQgGxYm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/683176762a92ed3286345b67cef4f3288e42206d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L295)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Are these clauses redundant with setting `nodes` and `regions` to empty arrays above?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-27 15:16 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69444#-:-Mi7Akck1TP0MScZlQw4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh)



<!-- Sent from Reviewable.io -->

2021-08-28 15:43 UTC, maryliag commented
bors r+

2021-08-28 17:06 UTC, merged