kvserver: Run one ScanInterleavedIntents per store concurrently
cockroachdb/cockroach pull request #69607
Opened 2021-08-30 20:15 UTC by itsbilal

Currently, lock table migration related requests (Barrier,
ScanInterleavedIntents, PushTxn, ResolveIntent), are only run
with a concurrency of 4 regardless of the size of the cluster.

This change increases that to 4 * numNodes, and adds a new
mechanism to limit the ScanInterleavedIntents on the receiver
side to 1 per store. This throttle is applied before latches
are grabbed. Only ScanInterleavedIntents needs to be
rate-limited as it's by far the heaviest component in
the separated intents migrations.

Release justification: Category 2, low-risk update to new functionality
Release note: None.

2021-08-30 20:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/69607)
<!-- Reviewable:end -->

2021-08-30 21:41 UTC, dt commented on pkg/kv/kvserver/batcheval/cmd_scan_interleaved_intents.go
> +	"github.com/marusama/semaphore"
I think we like this thing better (that sem isn't fair) https://github.com/cockroachdb/cockroach/blob/master/pkg/util/limit/limiter.go#L47

2021-08-30 21:49 UTC, dt commented on pkg/kv/kvserver/replica_send.go
> +		panic("no throttling cleanup for a non-ScanInterleavedIntents request")
2¢: I donno why I'm slightly uneasy about the panic, as well as the map lookup, plus being getOrCreate here (we would never want to create, then release). I might vote to have maybeThrottle just return a limiter.Reservation and if the caller gets a non-nil reservation, they have to defer releasing it.

2021-08-31 16:33 UTC, dt commented
I think we might actually want to make this setting-tunable. Like, these are _basically_ like ExportRequests, right? They both have to scan a large span and look for intents. You could potentially just copy/paste the ConcurrentExportRequests limiter, adding to the limiters field that is already an attribute of each store, to avoid needing to keep your own map, and so you'd also have a Settings.SV around to setup the on-change hook. I dunno.

2021-08-31 17:52 UTC, itsbilal commented
Thanks for the review! Yep, making it settings-tunable is probably a good idea. That way we can stuff the 4x node multiplier default into the cluster setting and have that drive that multiplier instead. I'll make that change shortly. Addressed the other points.

2021-08-31 19:17 UTC, itsbilal commented
Done. Slight update to last comment: I didn't put the 4x fan-out-time node multiplier factor in the setting, but rather the 1x store multiplier in it. That's less useful as there's no easy way to "slow it down" by reducing it any lower than 1 (0 would effectively stop rate limiting as the limiter will just return an error upon `Begin`); the operator could only speed it up from the default if they want to get the migration out of the way. Maybe that's fine, but something worth noting.

2021-08-31 19:30 UTC, dt approved these changes

2021-08-31 19:43 UTC, sumeerbhola requested changes
> Reviewed 6 of 8 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/kv/kvserver/replica_send.go, line 288 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69607#-MiSi4R852aicn-Ro2Yx:-MiSi4R852aicn-Ro2Yy:bkdd7ny) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d7ddf6c9dc9b0f016ea7caaed642a91cf8ddea/pkg/kv/kvserver/replica_send.go#L288)):*
> ```Go
> 		reservation, err := r.store.limiters.ConcurrentScanInterleavedIntents.Begin(ctx)
> 		if err != nil {
> 			return nil
> ```

why are we ignoring the error?
___
*[pkg/kv/kvserver/replica_send.go, line 355 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69607#-MiSidF53ZswX_d17ybo:-MiSidF53ZswX_d17ybp:b-cbj7xb) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d7ddf6c9dc9b0f016ea7caaed642a91cf8ddea/pkg/kv/kvserver/replica_send.go#L355)):*
> ```Go
> 
> 	// Handle any request-specific pre-latch throttles.
> 	if res := r.maybeThrottleRequestPreLatch(ctx, ba); res != nil {
> ```

Why do this here instead of earlier in `Store.Send` in `maybeThrottleBatch` -- it fits well with the other logic there?


<!-- Sent from Reviewable.io -->

2021-08-31 23:42 UTC, itsbilal reviewed
> Dismissed @sumeerbhola from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, and @sumeerbhola)

___
*[pkg/kv/kvserver/replica_send.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69607#-MiNgy8NntjJjskz7qDV-r1-292:-MiTYexu8bQe4U5FFzVt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a0035c41aaa705330505289ea047217361ee9c2/pkg/kv/kvserver/replica_send.go#L292)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

2¢: I donno why I'm slightly uneasy about the panic, as well as the map lookup, plus being getOrCreate here (we would never want to create, then release). I might vote to have maybeThrottle just return a limiter.Reservation and if the caller gets a non-nil reservation, they have to defer releasing it.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_send.go, line 288 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69607#-MiSi4R852aicn-Ro2Yx:-MiTYcub6z-I0eVUT5J3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d7ddf6c9dc9b0f016ea7caaed642a91cf8ddea/pkg/kv/kvserver/replica_send.go#L288)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why are we ignoring the error?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_send.go, line 355 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69607#-MiSidF53ZswX_d17ybo:-MiTYflhCHmaf-o0_6HM:b-fcwo9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d7ddf6c9dc9b0f016ea7caaed642a91cf8ddea/pkg/kv/kvserver/replica_send.go#L355)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Why do this here instead of earlier in `Store.Send` in `maybeThrottleBatch` -- it fits well with the other logic there?
</blockquote></details>

Done. I had missed that as I was looking at replica_send.go and not store_send.go. 
___
*[pkg/kv/kvserver/batcheval/cmd_scan_interleaved_intents.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69607#-MiNgy8MaiuaowTJAgCo-r1-25:-MiT_xDq16vxe0nFobsw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a0035c41aaa705330505289ea047217361ee9c2/pkg/kv/kvserver/batcheval/cmd_scan_interleaved_intents.go#L25)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think we like this thing better (that sem isn't fair) https://github.com/cockroachdb/cockroach/blob/master/pkg/util/limit/limiter.go#L47
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-01 17:14 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69607#-:-MiXLWha3LeQyytYats6:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)



<!-- Sent from Reviewable.io -->

2021-09-02 16:45 UTC, itsbilal commented
TFTRs!

bors r=dt

2021-09-02 19:05 UTC, merged