sql: restructure sqlstats public writer API
cockroachdb/cockroach pull request #69710
Opened 2021-09-01 21:16 UTC by Azhng

Previously, SQL Stats's public writer interface is very limited
in its functionality. This was intentional back in the time where
SQL Stat's writer is injected into stats collector and directly
writes statistics into the in-memory store. However, as we move
to support grouping of statement statistics within an explicit
transaction, this limited interface becomes a hurdle for stats
collector to implement that behavior.
This commit restructure the SQL Stats Writer API to introduce
the concept of sqlstats.ApplicationStats, which maps to
ssmemstorage.Container struct. Now, sqlstats.Storage interface
would return the new sqlstats.ApplicationStats intead of
sqlstats.Writer to the connExecutor, which can be injected into
the sqlstats.StatsCollector.

Release justification: Low risk, high benefit changes to existing
functionality
Release note: None

2021-09-01 21:16 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/69710)
<!-- Reviewable:end -->

2021-09-07 15:46 UTC, matthewtodd requested changes
I was a little confused by the commit comment. Reading through the diff, I noticed this change is mostly renaming `sqlstats.Writer` to `sqlstats.ApplicationStats`, then moving a couple of methods around. Would it make sense to separate those 2 steps? (The first one, the renaming, would be easy to describe and easy to review!)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-:-Mj-vJ21Dwfl_qgFxkD-:b-mz5w7b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-uZ_5Cjgfwl1Q-bpI):*
nit: s/is/was
___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-ucnw5gzMeu8JMH8w):*
nit: s/is/was
___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-ugov3DgFwzCXykiY):*
nit: injected into _the_ stats collector
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-um4ZCTM7facWL1kQ):*
nit: s/writes/wrote
___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-ur6S24rywpHOqJUF):*
nit: s/of//
___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-uxUy7EKMGDexYHmE):*
nit: Maybe rewrite this sentence to say what the hurdle is, or to give an example?
___
*[-- commits, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-v2ps4fpI5TlQgyif):*
nit: s/restructure/restructures
___
*[-- commits, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-v8Vt1I61Hqtufbb_):*
I'm not sure what you mean by "maps to" here, could you say more?
___
*[pkg/sql/sqlstats/ssprovider.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-s014EedT6Bz2fODq:-Mj-s014EedT6Bz2fODr:biaqc7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/100da9de8eaef8a4c041895086a7163c2c3f6e78/pkg/sql/sqlstats/ssprovider.go#L75)):*
> ```Go
> 	// IterateAggregatedTransactionStats iterates through all the collected app-level
> 	// transactions statistics. It behaves similarly to IterateStatementStats.
> 	IterateAggregatedTransactionStats(context.Context, *IteratorOptions, AggregatedTransactionVisitor) error
> ```

I can kind of imagine for `GetLastReset`, above, but I'm curious why this method moved; could you help me understand?

(Also, as a n00b it's unclear to me from the comments what the difference is between `IterateTransactionStats` and `IterateAggregatedTransactionStats`. I know it's off-topic for this PR, but perhaps it would be worth clarifying sometime?)
___
*[pkg/sql/sqlstats/ssprovider.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-t1Gh5JvChqkKorcc:-Mj-t1Gh5JvChqkKorcd:b-8gad8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34d31ef79bb1f3ebf327c7cf51f06b9f5a04bd5/pkg/sql/sqlstats/ssprovider.go#L140)):*
> ```Go
> 
> 	// GetLastReset returns the last time when the sqlstats is being reset.
> 	GetLastReset() time.Time
> ```

Actually, FWIW, it's a little confusing to me why this method lives here instead of on `StatsCollector`.


<!-- Sent from Reviewable.io -->

2021-09-15 21:33 UTC, Azhng reviewed
Hmm, I feel it might be slightly difficult to split the renaming. This is because `sqlstats.Writer` is not really going away and replaced by the `sqlstats.ApplicationStats`. `sqlstats.ApplicationStats` is a super set of the `sqlstats.Writer`. Trivially renaming `sqlstats.Writer` to `sqlstats.ApplicationStats` in the first commit will result in reintroduction of `sqlstats.Writer` in the second commit, which I feel can be a bit more confusing.

I drew the hierarchy diagram below hoping to makes it easy to understand what's my mental process for this:


```
# Existing Architecture

             Storage
            /      \
           /        +--<has many>
Reader (top level)   \
* IterateStmtStats  Writer (app level)
* IterateTxnStats     |
* GetLastReset        |
* IterateAggTxnStats  |
                    * RecordStmtStats
                    * RecordTxnStats
                    * RecordStmtExecStats


# New Architecture

             Storage--------------------+
            /      \                     \
           /        +--<has many>         \
Reader (top level)   \                     \
* IterateStmtStats    ApplicationStats     * GetLastReset
* IterateTxnStats     /              \
* IterateAggTxnStats /                \
                    /                  \
              Reader (app level)   Writer (app level)
            * IterateStmtStats     * RecordStmtStats
            * IterateTxnStats      * RecordTxnStats
            * ...                  * RecordStmtExecStats



```

> Actually, FWIW, it's a little confusing to me why this method lives here instead of on StatsCollector.

This method returns when was the last time the subsystem's statistics has been reset. `StatsCollector` is an ephemeral object that is created and deleted for each Session. Originally this was part of the `Reader` was because `Storage` embeds a `Reader` interface. However, in the new architecture, `Storage` and `ApplicationStats` both embeds `Reader` interface. `GetLastReset` is a method that exposes top level information on the subsystem, which doesn't make sense to be plumbed down to `ApplicationStats`. 

> I can kind of imagine for GetLastReset, above, but I'm curious why this method moved; could you help me understand? (Also, as a n00b it's unclear to me from the comments what the difference is between IterateTransactionStats and IterateAggregatedTransactionStats. I know it's off-topic for this PR, but perhaps it would be worth clarifying sometime?)


Our transaction stats are grouped 2 levels:
* level 1: app_name
* level 2 by transaction fingerprint ID, (

hence `ApplicationStats` embeds `Reader`. inside of SQLStats we also stores transaction statistics per `app_name` (not grouped by transaction fingerprint ID). This is what we refer to as `AggregatedTransactionStatistics` here.  We currently only have the in-memory storage for this and it's not flushed to disk. (I doubt if this is even accessible in DB Console).

But good point, This should go back into the `Reader`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-:-MjehvQN1cUNIz16McGS:b-o1bd5s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-uZ_5Cjgfwl1Q-bpI):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: s/is/was
</blockquote></details>

Done.
___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-ucnw5gzMeu8JMH8w):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: s/is/was
</blockquote></details>

Done.
___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-ugov3DgFwzCXykiY):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: injected into _the_ stats collector
</blockquote></details>

Done.
___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-um4ZCTM7facWL1kQ):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: s/writes/wrote
</blockquote></details>

Done.
___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-ur6S24rywpHOqJUF):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: s/of//
</blockquote></details>

Done.
___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-uxUy7EKMGDexYHmE):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Maybe rewrite this sentence to say what the hurdle is, or to give an example?
</blockquote></details>

Done.
___
*[-- commits, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-v2ps4fpI5TlQgyif):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: s/restructure/restructures
</blockquote></details>

Done.
___
*[-- commits, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-v8Vt1I61Hqtufbb_):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I'm not sure what you mean by "maps to" here, could you say more?
</blockquote></details>

`sqlstats.ApplicationStats` is an interface implemented by `ssmemstorage.Container` struct. I rephrase the sentence. 
___
*[pkg/sql/sqlstats/ssprovider.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-s014EedT6Bz2fODq:-MjfN7Ef1BnHzlbzJSYW:bfdw9r0) ([raw file](https://github.com/cockroachdb/cockroach/blob/100da9de8eaef8a4c041895086a7163c2c3f6e78/pkg/sql/sqlstats/ssprovider.go#L75)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I can kind of imagine for `GetLastReset`, above, but I'm curious why this method moved; could you help me understand?

(Also, as a n00b it's unclear to me from the comments what the difference is between `IterateTransactionStats` and `IterateAggregatedTransactionStats`. I know it's off-topic for this PR, but perhaps it would be worth clarifying sometime?)
</blockquote></details>

Responded in the top level comment above
___
*[pkg/sql/sqlstats/ssprovider.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mj-t1Gh5JvChqkKorcc:-MjfN1vg815f2VUsD4HP:bfdw9r0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34d31ef79bb1f3ebf327c7cf51f06b9f5a04bd5/pkg/sql/sqlstats/ssprovider.go#L140)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Actually, FWIW, it's a little confusing to me why this method lives here instead of on `StatsCollector`.
</blockquote></details>

Responded in the top level comment above


<!-- Sent from Reviewable.io -->

2021-09-15 21:37 UTC, Azhng reviewed
N.B: I made some edit to the ASCII diagrams in the Github side but it seems like it's not sync'd back to Reviewable.  The diagram in reviewable is not entirely accurate. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-:-MjfNv101YihDcaw8YxL:bqf0yo8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)



<!-- Sent from Reviewable.io -->

2021-09-16 14:35 UTC, matthewtodd reviewed
> Reviewed 3 of 12 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[pkg/sql/sqlstats/ssprovider.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mjj0dSt8S7XaPd_dEoD:-Mjj0dSu7cOoHSHe1qyL:bpayqz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5e64d67c080d17653c00d03baf1e7f406bb9bd9/pkg/sql/sqlstats/ssprovider.go#L83)):*
> ```Go
> 
> // ApplicationStats is an interface to read from or write to the statistics
> // belongs to an application.
> ```

nit: s/belongs/belonging


<!-- Sent from Reviewable.io -->

2021-09-16 14:36 UTC, matthewtodd reviewed
That ASCII art is :fire:. Thanks for explaining!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-:-Mjj1FlUBy3r4Irtk7kU:b2004uy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)



<!-- Sent from Reviewable.io -->

2021-09-16 14:37 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-:-Mjj1Oe39_3Wh0jn8dXw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)



<!-- Sent from Reviewable.io -->

2021-09-16 14:38 UTC, matthewtodd approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69710)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69710#-Mjj1ayi8ZxS3k3GbkY0):*
nit: interface ~is~ was very limited


<!-- Sent from Reviewable.io -->

2021-09-27 18:39 UTC, Azhng commented
bors r=matthewtodd

2021-09-27 20:00 UTC, merged