ui: add nodes and region information to databases pages
cockroachdb/cockroach pull request #69804
Opened 2021-09-02 23:52 UTC by xinhaoz

This commit adds node and region information
to the databases table, databases details table, and
table details page.

Release justification: low-risk, high benefit changes to
existing functionality

Release note (ui change): We are now able to show which
nodes and regions a database uses. In the databases page,
a new column has been added showing node/region information
for each database. On the database details page, a column is
added displayign node/region information for each table.
On the table page, we add a summary section of the nodes and
regions the table data is stored.

For each table, the column is only displayed if we have more
than one node.

---------------
Databases page:
![image](https://user-images.githubusercontent.com/20136951/131930108-d32abab8-6337-44ce-b272-08c700ea2210.png)
Db details page:
![image](https://user-images.githubusercontent.com/20136951/131930159-c02206bb-cc68-417f-8a0f-b9cebf3268e6.png)
table page:
![image](https://user-images.githubusercontent.com/20136951/131930014-3c16aa24-c29d-4f05-b529-bd7a48a939f5.png)

2021-09-02 23:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/69804)
<!-- Reviewable:end -->

2021-09-07 14:41 UTC, matthewtodd approved these changes
Looks great! Thanks for cleaning up that sprawling selector I wrote. :-)

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-:-Mj-h9hr3aC3wGGjrF9g:b-co0900)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-e0YA2oDG7PQ6CGFZ):*
nit: displaying
___
*[pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-eZEmEFoiPzX8tHWC:-Mj-eZEmEFoiPzX8tHWD:b-5xlmvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L26)):*
> ```XML
> } from "src/sortedtable";
> import * as format from "src/util/format";
> import { UIConfigState } from "../store/uiConfig";
> ```

nit: Is this import used anymore?


<!-- Sent from Reviewable.io -->

2021-09-07 14:54 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[-- commits, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-e0YA2oDG7PQ6CGFZ):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: displaying
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-eZEmEFoiPzX8tHWC:-Mj-iV8w7mOHsEHRny5n:b2hj3i1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L26)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Is this import used anymore?
</blockquote></details>

Nope - removed!


<!-- Sent from Reviewable.io -->

2021-09-07 15:02 UTC, matthewtodd approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)



<!-- Sent from Reviewable.io -->

2021-09-07 15:04 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-iohDET44swNO6_7O:-Mj-iohEAMe-yN6Zv7oI:b3hrtaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L80)):*
> ```XML
>   name: string;
>   tables: DatabaseDetailsPageDataTable[];
>   showNodeRegionsColumn?: boolean;
> ```

Since this is a boolean field, is there any reason this field is optional? Also since `nodesByRegionString` field below is already optional, do we need another boolean field here? 
___
*[pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.stories.tsx, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-jH_r-vETT4Lau_rT:-Mj-jH_r-vETT4Lau_rU:bx96l3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.stories.tsx#L54)):*
> ```XML
>     };
>   }),
> ```

nit: remove extra line
___
*[pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-kO0N4CSGqLhGsjRj:-Mj-kO0N4CSGqLhGsjRk:bwuv9up) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx#L221)):*
> ```XML
>         return this.paginatedData();
>       }
>       const sortColumn = columns.find(c => c.name === sortSetting.columnTitle);
> ```

Nice! 
___
*[pkg/ui/workspaces/db-console/src/views/databases/utils.ts, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-lKwh3H-NwnycX-Yu:-Mj-lKwh3H-NwnycX-Yv:by3dgx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/db-console/src/views/databases/utils.ts#L18)):*
> ```XML
>   nodeRegions: Record<string, string>,
> ): Record<string, number[]> {
>   const nodesByRegionMap: Record<string, number[]> = {};
> ```

nit: `s/const/let`? Since we are mutating this var later? 
___
*[pkg/ui/workspaces/db-console/src/views/databases/utils.ts, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-l_MZ6u7rrNjR_XXE:-Mj-l_MZ6u7rrNjR_XXF:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/db-console/src/views/databases/utils.ts#L38)):*
> ```XML
> ): string {
>   // Sort the nodes on each key.
>   const regions = Object.keys(nodesByRegion).sort();
> ```

ditto
___
*[pkg/ui/workspaces/db-console/src/views/databases/utils.ts, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-llp682Rpp2MTQzdr:-Mj-llp682Rpp2MTQzds:b-d4dx2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/db-console/src/views/databases/utils.ts#L43)):*
> ```XML
>   });
> 
>   const nodesByRegionString = regions
> ```

nit: directly return this line? 


<!-- Sent from Reviewable.io -->

2021-09-07 15:25 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-iohDET44swNO6_7O:-Mj-nQb75_3NwO7CSzxz:bjydl1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L80)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Since this is a boolean field, is there any reason this field is optional? Also since `nodesByRegionString` field below is already optional, do we need another boolean field here? 
</blockquote></details>

`nodesByRegionString` is per table. A table might not have any data => no nodes/regions. `showNodeRegionsColumn` is just set to true if we have more than one node.  I also decided to add it explicitly as a prop to simplify setting the 'showByDefault' value on the column itself.

Making it optional just for convenience sake so that not including the prop would be equiv to false.
___
*[pkg/ui/workspaces/db-console/src/views/databases/utils.ts, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-lKwh3H-NwnycX-Yu:-Mj-oTHC53WRiyWbo_bU:bv79ugc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/db-console/src/views/databases/utils.ts#L18)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `s/const/let`? Since we are mutating this var later? 
</blockquote></details>

In JS const just means we don't reassign the value rather than for describing immutability. In TS we can define immutable objects with ReadOnly iirc
___
*[pkg/ui/workspaces/db-console/src/views/databases/utils.ts, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-llp682Rpp2MTQzdr:-Mj-puYNDZySA47IPOU9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/db-console/src/views/databases/utils.ts#L43)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: directly return this line? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-07 16:12 UTC, maryliag requested changes
> Reviewed 7 of 12 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/views/databases/utils.ts, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj007Qm7UwLj_WGXxTR:-Mj007Qm7UwLj_WGXxTS:bg2oa3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/58a9b9cd4abf39d39eefe5937ca2c9acaa4f6e08/pkg/ui/workspaces/db-console/src/views/databases/utils.ts#L14)):*
> ```XML
> // based on the nodes list provided and nodeRegions, which is a full
> // list of node id to the region it resides.
> export function createNodesByRegionMap(
> ```

can you check how this is being done on statements/transactions page so all can use the same function? feel free to replace there with the functions you created
___
*[pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts, line 117 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj00o3BCmpZqx4oZ87w:-Mj00o3BCmpZqx4oZ87x:bi8r13z) ([raw file](https://github.com/cockroachdb/cockroach/blob/58a9b9cd4abf39d39eefe5937ca2c9acaa4f6e08/pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts#L117)):*
> ```XML
>   loaded: selectLoaded(state),
>   databases: selectDatabases(state),
>   showNodeRegionsColumn: selectIsMoreThanOneNode(state),
> ```

and is not tenant


<!-- Sent from Reviewable.io -->

2021-09-07 17:29 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/views/databases/utils.ts, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj007Qm7UwLj_WGXxTR:-Mj0IV-M1HD_A6i4zdjc:b-qa4alu) ([raw file](https://github.com/cockroachdb/cockroach/blob/58a9b9cd4abf39d39eefe5937ca2c9acaa4f6e08/pkg/ui/workspaces/db-console/src/views/databases/utils.ts#L14)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you check how this is being done on statements/transactions page so all can use the same function? feel free to replace there with the functions you created
</blockquote></details>

Resolved offline.
___
*[pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts, line 117 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj00o3BCmpZqx4oZ87w:-Mj0IYBM6BDk-5PM6HMN:bmtblm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/58a9b9cd4abf39d39eefe5937ca2c9acaa4f6e08/pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts#L117)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

and is not tenant
</blockquote></details>

tenant value isn't being passed in right now since db pages don't exist in cluster ui, but I added the value for the future.


<!-- Sent from Reviewable.io -->

2021-09-07 17:30 UTC, xinhaoz commented
___
*[pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts, line 117 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj00o3BCmpZqx4oZ87w:-Mj0Iib97J-9HlGaMZx4:bhuk6j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/58a9b9cd4abf39d39eefe5937ca2c9acaa4f6e08/pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts#L117)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

tenant value isn't being passed in right now since db pages don't exist in cluster ui, but I added the value for the future.
</blockquote></details>

That is, the value `hideIfTenant` in the columns


<!-- Sent from Reviewable.io -->

2021-09-07 17:30 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-:-Mj0IuCN7PI5C4HpPWcA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @xinhaoz)



<!-- Sent from Reviewable.io -->

2021-09-07 19:15 UTC, Azhng approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-:-Mj0fnzj8jxqfvo7VLmM:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-iohDET44swNO6_7O:-Mj0fUoL6BXMzqk8vrRP:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L80)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

`nodesByRegionString` is per table. A table might not have any data => no nodes/regions. `showNodeRegionsColumn` is just set to true if we have more than one node.  I also decided to add it explicitly as a prop to simplify setting the 'showByDefault' value on the column itself.

Making it optional just for convenience sake so that not including the prop would be equiv to false.
</blockquote></details>

:+1:
___
*[pkg/ui/workspaces/db-console/src/views/databases/utils.ts, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69804#-Mj-lKwh3H-NwnycX-Yu:-Mj0fdD77Ugukvba1gFp:bb741ss) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a566e7484eaadd6710f0fab8866449df581114f/pkg/ui/workspaces/db-console/src/views/databases/utils.ts#L18)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

In JS const just means we don't reassign the value rather than for describing immutability. In TS we can define immutable objects with ReadOnly iirc
</blockquote></details>

TIL.


<!-- Sent from Reviewable.io -->

2021-09-07 23:28 UTC, merged