sql: implement pg_my_temp_schema and pg_is_other_temp_schema
cockroachdb/cockroach pull request #69909
Opened 2021-09-08 02:30 UTC by nvanbenschoten

Needed for #69010.

This PR adds a real implementation for the `pg_my_temp_schema` builtin
function. `pg_my_temp_schema` returns the OID of session's temporary schema, or 0
if the session has not yet created a temporary schema.

The PR then implements the `pg_is_other_temp_schema` builtin function.
`pg_is_other_temp_schema` returns true if the given OID is the OID of another
session's temporary schema. This can be useful, for example, to exclude other
sessions' temporary tables from a catalog display.

Release note (sql change): The pg_my_temp_schema builtin function now properly
returns the OID of the active session's temporary schema, if one exists.

Release note (sql change): The pg_is_other_temp_schema builtin function is now
supported, which returns whether the given OID is the OID of another session's
temporary schema.

Release justification: None, waiting for v22.1.

2021-09-08 17:27 UTC, rafiss requested changes
thanks for implementing these!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69909#-:-Mj5RgXf-iOFB4ZPD1og:b-mj68ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 847 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69909#-Mj5Jkl3BkJ9B3B0BOqi:-Mj5Jkl3BkJ9B3B0BOqj:b-rzbkad) ([raw file](https://github.com/cockroachdb/cockroach/blob/aba40c70f4d6a28e192ef30627b59930557a913c/pkg/sql/sem/builtins/pg_builtins.go#L847)):*
> ```Go
> 					return tree.NewDOid(0), nil
> 				}
> 				oid, err := ctx.Planner.ResolveOIDFromString(
> ```

would be nice if we could use `planner.Descriptors().GetSchemaByName()` (and avoid going through the internal executor). but i believe it's not possible to add that to the EvalPlanner interface because of the dependencies it has.

how would you feel about adding a test that uses this builtin to `rttanalysis.BenchmarkORMQueries`? then if we resolve https://github.com/cockroachdb/cockroach/issues/69495 or improve this in some other way, we'd be able to measure it
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 875 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69909#-Mj5Ranc3LnJva7YtydC:-Mj5Ranc3LnJva7YtydD:bggkisi) ([raw file](https://github.com/cockroachdb/cockroach/blob/227ef71e11fc1a403fd68ca1e52534736bd31edf/pkg/sql/sem/builtins/pg_builtins.go#L875)):*
> ```Go
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				schemaArg := tree.UnwrapDatum(ctx, args[0])
> 				schema, err := getNameForArg(ctx, schemaArg, "pg_namespace", "nspname")
> ```

similarly, could you add a benchmark for this?


<!-- Sent from Reviewable.io -->

2021-09-09 17:45 UTC, nvanbenschoten reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69909#-:-MjAe_dECFrrv7PH10_g:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 847 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69909#-Mj5Jkl3BkJ9B3B0BOqi:-MjAeTWC7MNfANMIWIAv:b-czsg7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/aba40c70f4d6a28e192ef30627b59930557a913c/pkg/sql/sem/builtins/pg_builtins.go#L847)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would be nice if we could use `planner.Descriptors().GetSchemaByName()` (and avoid going through the internal executor). but i believe it's not possible to add that to the EvalPlanner interface because of the dependencies it has.

how would you feel about adding a test that uses this builtin to `rttanalysis.BenchmarkORMQueries`? then if we resolve https://github.com/cockroachdb/cockroach/issues/69495 or improve this in some other way, we'd be able to measure it
</blockquote></details>

Done.

```
BenchmarkORMQueries/pg_my_temp_schema-16         	     177	   6485745 ns/op	         2.000 roundtrips
```
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 875 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69909#-Mj5Ranc3LnJva7YtydC:-MjAeTtG8gtMVxZ5FWJ0:buw5aud) ([raw file](https://github.com/cockroachdb/cockroach/blob/227ef71e11fc1a403fd68ca1e52534736bd31edf/pkg/sql/sem/builtins/pg_builtins.go#L875)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similarly, could you add a benchmark for this?
</blockquote></details>

Done.

```
BenchmarkORMQueries/pg_is_other_temp_schema-16         	     100	  12407798 ns/op	         3.000 roundtrips
```


<!-- Sent from Reviewable.io -->

2021-09-10 15:42 UTC, rafiss approved these changes
lgtm! would be good to get a look from sql-schema, specifically for awareness about the `ResolveOIDFromString` and `getNameForArg` calls, just in case there's an immediately obvious improvement to be had.

2021-09-10 17:07 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69909)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[pkg/bench/rttanalysis/orm_queries_bench_test.go, line 187 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69909#-MjFfBGb35B4p8xLcJHu:-MjFfBGb35B4p8xLcJHv:by1a0qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e200a05f7094686957177d97bc02732cb190e9/pkg/bench/rttanalysis/orm_queries_bench_test.go#L187)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> 		{
> 			Name: "pg_my_temp_schema",
> 			Setup: `SET experimental_enable_temp_tables = true;
>               CREATE TEMP TABLE t(a int primary key, b int)`,
> 			Stmt: `SELECT pg_my_temp_schema()`,
> 		},
> 		{
> 			Name: "pg_is_other_temp_schema",
> 			Setup: `SET experimental_enable_temp_tables = true;
>               CREATE TEMP TABLE t(a int primary key, b int)`,
> 			Stmt: `SELECT pg_is_other_temp_schema('t'::regclass)`,
> 		},
> ```
</details>

thoughts on adding another one that does it twice in the same statement and shows that that is currently worse than doing it once? 


<!-- Sent from Reviewable.io -->

2021-09-13 23:13 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69909)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/bench/rttanalysis/orm_queries_bench_test.go, line 187 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69909#-MjFfBGb35B4p8xLcJHu:-MjWLUMO6VjZvbpO4dIn:buobarg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e200a05f7094686957177d97bc02732cb190e9/pkg/bench/rttanalysis/orm_queries_bench_test.go#L187)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		{
> 			Name: "pg_my_temp_schema",
> 			Setup: `SET experimental_enable_temp_tables = true;
>               CREATE TEMP TABLE t(a int primary key, b int)`,
> 			Stmt: `SELECT pg_my_temp_schema()`,
> 		},
> 		{
> 			Name: "pg_is_other_temp_schema",
> 			Setup: `SET experimental_enable_temp_tables = true;
>               CREATE TEMP TABLE t(a int primary key, b int)`,
> 			Stmt: `SELECT pg_is_other_temp_schema('t'::regclass)`,
> 		},
> ```
thoughts on adding another one that does it twice in the same statement and shows that that is currently worse than doing it once? 
</blockquote></details>

Done for both.

```
name                                                  time/op
ORMQueries/pg_my_temp_schema-16                       6.77ms ± 0%
ORMQueries/pg_my_temp_schema_multiple_times-16        6.54ms ± 0%
ORMQueries/pg_is_other_temp_schema-16                 7.41ms ± 0%
ORMQueries/pg_is_other_temp_schema_multiple_times-16  11.3ms ± 0%

name                                                  roundtrips
ORMQueries/pg_my_temp_schema-16                         2.00 ± 0%
ORMQueries/pg_my_temp_schema_multiple_times-16          2.00 ± 0%
ORMQueries/pg_is_other_temp_schema-16                   6.99 ± 0%
ORMQueries/pg_is_other_temp_schema_multiple_times-16    11.0 ± 0%
```


<!-- Sent from Reviewable.io -->

2021-09-14 01:15 UTC, nvanbenschoten commented
bors r+

2021-09-14 02:24 UTC, merged