sql: implement information_schema._pg_char_max_length
cockroachdb/cockroach pull request #69911
Opened 2021-09-08 03:41 UTC by nvanbenschoten

Needed for #69010.

This commit implements the `information_schema._pg_index_position` builtin
function. Given an index's OID and an underlying-table column number,
`information_schema._pg_index_position` return the column's position in the
index (or NULL if not there).

The function is implemented as a user-defined function in Postgres here:
https://github.com/postgres/postgres/blob/master/src/backend/catalog/information_schema.sql

Release note: None.

Release justification: None, waiting for v22.1.

2021-09-08 03:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/69911)
<!-- Reviewable:end -->

2021-09-08 05:36 UTC, ajwerner reviewed
We should really do https://github.com/cockroachdb/cockroach/issues/69495 in v22.1. Until then, these queries really hurt if this gets called more than once in a transaction because we'll pull all of `system.descriptor` every time this function is invoked. It's bad enough that we have to pull it once per transaction. 

One approach to make things not suck would be to allocate unique OIDs per index and index those somewhere. That's a bigger project. That feels like a pretty big thing. I'm decreasingly inclined to pursue that as the next step. It's too many migrations and is pretty painful to leverage.

Instead I often think about a protocol to lease all of the descriptors with a "one version invariant". By that I mean there'd be some sort of lease on some resource which means that no schema changes can happen while that lease is outstanding. We'd need some way to pre-empt that sort of lease so that sessions fall back to reading the table per transaction. This is a very similar thing to what we'd want for low-latency changefeeds.

Given that `pg_catalog` is database scoped, we could have a mechanism to lease all of the descriptors in a database and do that at the node level. That way we could still avoid any need to keep all descriptors for all databases in RAM at any point. 

All this being said, I don't think these are the sorts of visions we're going to realize this release due to being seriously short on resources. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-:-Mj2rLGW7n8bKt_Ha_AM:b-io4gka)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-09-08 14:08 UTC, nvanbenschoten commented
Could you remind me why we're discussing leasing, whether session-scoped or database-scoped, and not a more simple form of coordination-free caching? I'd imagine that if the concern is pulling all descriptors every time one of these builtins is invoked (per row in many cases), a session or even statement-scoped cache would provide a large win. You mention "It's bad enough that we have to pull it once per transaction.", which is fair, but also, maybe obscuring the lower hanging fruit. Am I thinking about this correctly? Do we have examples of where the descriptor lookups hurt the most?

2021-09-08 14:48 UTC, ajwerner commented
> Could you remind me why we're discussing leasing, whether session-scoped or database-scoped, and not a more simple form of coordination-free caching? 

We have a session-scoped cache, hence the first paragraph and  "It's bad enough that we have to pull it once per transaction." The problem is that it hangs off of the `extraTxnState` which is not shared by the internal executor, hence the reference to #69495.

2021-09-08 21:25 UTC, nvanbenschoten commented
> The problem is that it hangs off of the extraTxnState which is not shared by the internal executor, hence the reference to #69495.

Got it, that makes sense. Thanks.

2021-09-09 18:54 UTC, rafiss requested changes
just tiny nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-:-MjAu2C83N8-3SWD5wPR:b5kevu3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1921 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-MjAo64_6Lf6kKYFsCxS:-MjAo64_6Lf6kKYFsCxT:bte06om) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdaa65b4eb41902585ed69f7dc92a1e056c0e965/pkg/sql/sem/builtins/pg_builtins.go#L1921)):*
> ```Go
> 	// (or NULL if not there).
> 	//
> 	// NOTE: this could be defined as a user-defined function, like
> ```

glad you thought so too! i had commented the same w.r.t. other builtins on https://github.com/cockroachdb/cockroach/issues/58356#issuecomment-774347018
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-MjAtsq2ChOO5j3bMBRJ:-MjAtsq2ChOO5j3bMBRK:b7va0i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdaa65b4eb41902585ed69f7dc92a1e056c0e965/pkg/sql/sem/builtins/pg_builtins.go#L1942)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Int),
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				r, err := ctx.InternalExecutor.QueryRow(
> ```

similar to the pg_my_temp_schema PR - could you add a benchmark for this?
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1953 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-MjAsQU608i2QFqnM0mI:-MjAsQU608i2QFqnM0mJ:b9aubaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdaa65b4eb41902585ed69f7dc92a1e056c0e965/pkg/sql/sem/builtins/pg_builtins.go#L1953)):*
> ```Go
> 					return nil, err
> 				}
> 				if len(r) == 0 {
> ```

nit: would it be more clear if this check were `if r == nil` ? (asking since it may not be clear that tree.Datums is a slice of Datums.) up to you
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1956 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-MjAtY205LpK7rd5wFyy:-MjAtY205LpK7rd5wFyz:b-lsy0l1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdaa65b4eb41902585ed69f7dc92a1e056c0e965/pkg/sql/sem/builtins/pg_builtins.go#L1956)):*
> ```Go
> 					return tree.DNull, nil
> 				}
> 				return r[0], nil
> ```

nit: `return tree.MustBeDInt(r[0]), nil`
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1958 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-MjAnSKF5OnpBjWy3MB1:-MjAnSKGELZH7GVsq-6h:bu2ux9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdaa65b4eb41902585ed69f7dc92a1e056c0e965/pkg/sql/sem/builtins/pg_builtins.go#L1958)):*
> ```Go
> 				return r[0], nil
> 			},
> 			Info:       notUsableInfo,
> ```

nit: should the Info have a real description?


<!-- Sent from Reviewable.io -->

2021-09-09 18:56 UTC, rafiss reviewed
ah and one more nit: could you mention this new function in a release note?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-:-MjAuczH3PPZ9XYlDnF2:b14lbc1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2021-09-13 23:30 UTC, nvanbenschoten reviewed
> could you mention this new function in a release note?

Done.

TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-:-MjWRTrI8UdI3Q-LVewt:b34b1nx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-MjAtsq2ChOO5j3bMBRJ:-MjWSyfo4e6WycgcSXEb:bb44vh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdaa65b4eb41902585ed69f7dc92a1e056c0e965/pkg/sql/sem/builtins/pg_builtins.go#L1942)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similar to the pg_my_temp_schema PR - could you add a benchmark for this?
</blockquote></details>

Done.

```
BenchmarkORMQueries/information_schema._pg_index_position-16         	      13	 103740333 ns/op	        15.00 roundtrips
```
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1953 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-MjAsQU608i2QFqnM0mI:-MjWTOHlE-yieMautUNZ:b9eqg95) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdaa65b4eb41902585ed69f7dc92a1e056c0e965/pkg/sql/sem/builtins/pg_builtins.go#L1953)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: would it be more clear if this check were `if r == nil` ? (asking since it may not be clear that tree.Datums is a slice of Datums.) up to you
</blockquote></details>

We seem to use the `len(r) == 0` check everywhere else in this file, so I'll keep it here for consistency.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1956 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-MjAtY205LpK7rd5wFyy:-MjWU28N56RdTBUX9m9k:b-19xznn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdaa65b4eb41902585ed69f7dc92a1e056c0e965/pkg/sql/sem/builtins/pg_builtins.go#L1956)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: `return tree.MustBeDInt(r[0]), nil`
</blockquote></details>

`DInt` (the return type of `MustBeDInt`) doesn't implement `Datum`, `*DInt` does. We could eat an allocation here, but it doesn't seem worth it.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1958 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69911#-MjAnSKF5OnpBjWy3MB1:-MjWUJchB1WnXl3ttH38:b-624sin) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdaa65b4eb41902585ed69f7dc92a1e056c0e965/pkg/sql/sem/builtins/pg_builtins.go#L1958)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should the Info have a real description?
</blockquote></details>

I don't think so. These `information_schema._pg_xxx` functions are just about as internal as they get. They aren't even documented by Postgres. So I feel comfortable not documenting this.


<!-- Sent from Reviewable.io -->

2021-09-14 02:37 UTC, nvanbenschoten commented
bors r+

2021-09-14 03:25 UTC, merged