storage: narrow down use of SingleDel to avoid anomalies
cockroachdb/cockroach pull request #69923
Opened 2021-09-08 13:36 UTC by tbg

Fixes #69414.

Only use SingleDel if

- the meta tracking allows it (i.e. the sole previous condition), and
- epoch zero, and
- no ignored txn seqno ranges.

These three together imply that the engine history of the metadata key
is a single `Set`, so we can safely use `SingleDel`.

This is a below-Raft change, but no mixed-version problems are expected.
This is because using a Del vs using a SingleDel (if it does not cause
an anomaly) is not visible at the replica state level. In particular,
a deleted key looks the same to the consistency checker as a
single-deleted key.

Release justification: fix for a release blocker
Release note: None

2021-09-08 13:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/69923)
<!-- Reviewable:end -->

2021-09-08 17:40 UTC, sumeerbhola requested changes
Looks good!

nit: why is this "below-Raft" given this is being done by the leaseholder when evaluating the proposal?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-:-Mj5RQU29uQcMJs-SDqY:blzau2t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/mvcc.go, line 2957 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-Mj5SIhfB0HyLomky5wc:-Mj5SIhfB0HyLomky5wd:b-wuu52p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b12b444998bdd297f3e66ba45bf30cd5e37dcef/pkg/storage/mvcc.go#L2957)):*
> ```Go
> // to change with #69891):
> //
> // - Set (Set' Del) Set'' SingleDel
> ```

nit: are the parentheses supposed to represent what was in a single compaction?
If so, the example is not quite accurate. We won't compact (Set' Del) into nothing. The Del will live because there is an older Set.
A bad sequence (which happens even if the first Del is a SingleDel) is 
Set Set' (Del Set'') SingleDel
Set Set' (Set'' SingleDel)
Set Set' 
___
*[pkg/storage/mvcc.go, line 2971 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-Mj5Sz9p0BlOzlrG8eam:-Mj5Sz9p0BlOzlrG8ean:b-kn5uza) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b12b444998bdd297f3e66ba45bf30cd5e37dcef/pkg/storage/mvcc.go#L2971)):*
> ```Go
> // https://github.com/cockroachdb/cockroach/issues/69891
> type singleDelOptimizationHelper struct {
> 	_didNotUpdateMeta *bool
> ```

why underscore prefixes in the names?
___
*[pkg/storage/mvcc.go, line 2982 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-Mj5TEEQ7YuT5gI5sIhT:-Mj5TEEQ7YuT5gI5sIhU:b-oni78s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b12b444998bdd297f3e66ba45bf30cd5e37dcef/pkg/storage/mvcc.go#L2982)):*
> ```Go
> 	}
> 	// TODO(sumeerbhole): changing this to `return true` does not
> 	// yield any test failures. This seems problematic.
> ```

I didn't understand this comment. We currently don't populate this optional field unless it is true, but that is just an implementation detail.
___
*[pkg/storage/mvcc.go, line 2996 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-Mj5TZpU-Otar9rbnwVh:-Mj5TZpU-Otar9rbnwVi:bsa9u2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b12b444998bdd297f3e66ba45bf30cd5e37dcef/pkg/storage/mvcc.go#L2996)):*
> ```Go
> }
> 
> // onClearIntent returns true if the SingleDel optimization is available
> ```

nit: how about calling this`onAbortIntent` with a code comment saying that this should not be mistaken to mean txn abort, since it only applies to the intent? `onClearIntent` seems a bit confusing since we clear the intent even in the case of committing (`intentDemuxWriter.ClearIntent`)


<!-- Sent from Reviewable.io -->

2021-09-09 19:30 UTC, tbg reviewed
> nit: why is this "below-Raft" given this is being done by the leaseholder when evaluating the proposal?

:see_no_evil: it's not, fixed, thank you.

RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-:-MjAy9v33hSQfkz2EjnY:b1bwl8j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 2971 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-Mj5Sz9p0BlOzlrG8eam:-MjB-Ga74HBC0GCnFNhY:b-ti0f7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b12b444998bdd297f3e66ba45bf30cd5e37dcef/pkg/storage/mvcc.go#L2971)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why underscore prefixes in the names?
</blockquote></details>

It's my attempt to make it less likely that they will be accessed instead of the getters by accident.
___
*[pkg/storage/mvcc.go, line 2982 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-Mj5TEEQ7YuT5gI5sIhT:-MjB-c3jBq8yRDMFIJFG:b-w77kry) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b12b444998bdd297f3e66ba45bf30cd5e37dcef/pkg/storage/mvcc.go#L2982)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand this comment. We currently don't populate this optional field unless it is true, but that is just an implementation detail.
</blockquote></details>

Ah, that makes sense, thank you for clarifying.


<!-- Sent from Reviewable.io -->

2021-09-10 19:00 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-:-MjG3nwq0YXexHE_WdIK:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

___
*[-- commits, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-MjG2NnB0n7pRTTaguE1):*
btw, I'd feel better if we also fix the compatibility issue with 21.1 before beta https://github.com/cockroachdb/cockroach/issues/69891#issuecomment-916452800 (I realize we don't expect to upgrade from 21.1 to 21.2 beta for serverless, so it isn't strictly necessary, but remembering why partial fixes are ok make my head hurt).
___
*[pkg/storage/mvcc.go, line 2937 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69923#-MjG3R-d9ulsAWOAYwys:-MjG3R-d9ulsAWOAYwyt:b9hnopd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7971115b9c4e60f2704cef91b5ff8687e8c3ee2f/pkg/storage/mvcc.go#L2937)):*
> ```Go
> //   BEGIN;
> //     SAVEPOINT foo;
> //       INSERT INTO kv VALUES(1, 1);
> ```

nit: can you add back the UPDATE in the example that was there in your previous version. That is more consistent with the use of Del below.


<!-- Sent from Reviewable.io -->

2021-09-10 19:05 UTC, tbg commented
bors r=sumeerbhola
TFTR!
Going to leave the comments as is since I don't have time for another CI turnaround tonight. I expect there'll be another chance to touch these up with progress on https://github.com/cockroachdb/cockroach/issues/69891#issuecomment-916452800.

2021-09-10 20:17 UTC, merged

2021-09-13 15:11 UTC, tbg commented
blathers backport 21.2