roachtest: make --workload optional
cockroachdb/cockroach pull request #70059
Opened 2021-09-10 21:48 UTC by mgartner

This commit makes the `--workload` flag optional because some roachtests
do not require a workload binary.

Release note: None

2021-09-10 21:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70059)
<!-- Reviewable:end -->

2021-09-12 20:37 UTC, otan requested changes
i *think* some roachtests rely on not specifying a workload binary flag, in which case `findBinary` would look in the "default places" for the workload binary. in other words, this would break invocations such as ` bin/roachtest run tpcc/multiregion/survive=region/chaos=true` which relies on `findBinary` to find the "default". seems like a gotcha to me.

2021-09-13 07:04 UTC, tbg commented
+1, findBinary also provides the default value (for better or worse), what if you revert to the old code but you return a sentinel error instead of this one

https://github.com/cockroachdb/cockroach/blob/6b89733c29ecd0e9161a7b1d30adb8a897cd7a28/pkg/cmd/roachtest/cluster.go#L181

and then here

https://github.com/cockroachdb/cockroach/blob/6b89733c29ecd0e9161a7b1d30adb8a897cd7a28/pkg/cmd/roachtest/cluster.go#L207-L211

you detect that error and print something like "`workload` binary not provided, proceeding anyway" instead of exiting.

2021-09-13 15:16 UTC, mgartner commented
I see, thanks for the additional context. I've made the suggestions @tbg suggested.

2021-09-14 09:42 UTC, tbg approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70059)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @otan)



<!-- Sent from Reviewable.io -->

2021-09-14 12:50 UTC, mgartner commented
TFTR!

bors r+

2021-09-14 17:07 UTC, merged