roachprod: tag ssh keys in aws to map them to users and add creation …
cockroachdb/cockroach pull request #70201
Opened 2021-09-14 14:59 UTC by healthy-pod

…time

Previously, roachprod created ssh key pairs without any direct way
of mapping them to users, and without any way of knowing the
creation time.

This needed to change because we need to delete ssh key pairs of
previous users and we should have a way of finding those keys.

This patch ensures that any newly created ssh key pair will be
tagged with 'IAM-UserName' and 'CreatedAt' tags.

Release note: None

2021-09-14 14:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70201)
<!-- Reviewable:end -->

2021-09-14 20:52 UTC, jlinder reviewed
I've a couple suggestions, one here and one below.

For the title of the PR, it should not be broken between the title and the beginning of the body. Please either move 'time' to the title or shorten the title. The [Commit title](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#Commit-title) section of the [Git Commit Messages](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages) wiki page is relevant here too since the title was based on the commit's title (so it might be good to shorten the commit title too). A possible shorter title might be `roachprod: tag ssh keys in aws with IAMUserName and CreatedAt`.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70201#-:-Mja1rmq9xXXXpHr_50w:b-lu04eb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod)

___
*[pkg/cmd/roachprod/vm/aws/keys.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70201#-Mj_xTgk360REqppAFoi:-Mj_xTgk360REqppAFoj:bzhxjtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a8af6230d4bae8891c63e387a4f1a44a68c28b/pkg/cmd/roachprod/vm/aws/keys.go#L80)):*
> ```Go
> 		"--key-name", keyName,
> 		"--public-key-material", fmt.Sprintf("fileb://%s", sshPublicKeyFile),
> 		"--tag-specifications", fmt.Sprintf("ResourceType=key-pair,Tags=[{Key=IAM-UserName,Value=%s}, {Key=CreatedAt,Value=%s}]", user, timeString),
> ```

How about we use `IAMUserName` without the dash?


<!-- Sent from Reviewable.io -->

2021-09-14 22:54 UTC, healthy-pod commented
Added the recommended changes and used timeutil instead of time in my latest commit. Build failed due to linting issue, and logs show "Some automatically generated code is not up to date". Any thoughts on that? Is it maybe related to the fact that I made a commit then edited it? 

https://teamcity.cockroachdb.com/viewLog.html?buildId=3444156&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_CheckGeneratedCode

2021-09-15 14:29 UTC, jlinder requested changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod)

___
*[-- commits, line 15 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70201#-Mjdk4LO4w9TPN2rAQ4Z):*
`Release justification` should no longer be necessary. What happens if you rebase to the latest master?
___
*[pkg/cmd/roachprod/vm/aws/keys.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70201#-MjaFErfCo52B3GU615n:-MjaFErfCo52B3GU615o:b-ghhr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/887f1fd695791e870648170597b38ba13732bbef/pkg/cmd/roachprod/vm/aws/keys.go#L73)):*
> ```Go
> 
> 	timestamp := timeutil.Now().UTC()
> 	timeString := fmt.Sprintf("%d-%02d-%02dT%02d:%02d:%02dZ", timestamp.Year(), timestamp.Month(), timestamp.Day(), timestamp.Hour(), timestamp.Minute(), timestamp.Second())
> ```

I missed this in the first review. There is a standard way of formatting a `time.Time` instance using the [time.Time.Format()](https://pkg.go.dev/time#Time.Format) function. Please use this instead.
___
*[pkg/cmd/roachprod/vm/aws/keys.go, line 72 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70201#-MjdnfJa45WeGGaxdLDu:-MjdnfJa45WeGGaxdLDv:b-2didcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/df18cbffafc1aa3b2420816623997170642767d1/pkg/cmd/roachprod/vm/aws/keys.go#L72)):*
> ```Go
> 	}
> 
> 	timestamp := timeutil.Now().UTC()
> ```

If you look at what is returned from `timeutil.Now()` (for both [now_unix](https://github.com/cockroachdb/cockroach/blob/master/pkg/util/timeutil/now_unix.go) and [now_windows](https://github.com/cockroachdb/cockroach/blob/master/pkg/util/timeutil/now_windows.go)), they return the `UTC` time already. They also return an instance of [time.Time](https://pkg.go.dev/time)Z, which is important for some of the other comments I'm making.
___
*[pkg/cmd/roachprod/vm/aws/keys.go, line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70201#-MjdpNK98KNRXJP02bLZ:-MjdpNK98KNRXJP02bL_:btz9rf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/df18cbffafc1aa3b2420816623997170642767d1/pkg/cmd/roachprod/vm/aws/keys.go#L80)):*
> ```Go
> 		"--key-name", keyName,
> 		"--public-key-material", fmt.Sprintf("fileb://%s", sshPublicKeyFile),
> 		"--tag-specifications", fmt.Sprintf("ResourceType=key-pair,Tags=[{Key=IAMUserName,Value=%s}, {Key=CreatedAt,Value=%s}]", user, timeString),
> ```

(I also missed this in my first review.) This line is longer than our [guidelines](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Line-Length) recommend. They ask that lines be wrapped at 100 characters (80 chars for comments in normal situations). For this, I'd probably generate the `fmt.Sprintf` output before this line.


<!-- Sent from Reviewable.io -->

2021-09-15 17:42 UTC, jlinder approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70201#-:-MjeY6G1A-kN2Hb_JWsZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @healthy-pod)



<!-- Sent from Reviewable.io -->

2021-09-15 17:51 UTC, healthy-pod commented
bors r+

2021-09-15 19:07 UTC, merged

2021-09-15 19:16 UTC, jlinder commented
@healthy-pod The backport errors for 20.2.x and 21.1.x are probably related to the bazel file change. We hadn't started the bazel migration when those major release versions were started.