ui/cluster-ui: add 'Interval Start Time' column to stmts/txns tables
cockroachdb/cockroach pull request #70282
Opened 2021-09-15 21:14 UTC by xinhaoz

This commit adds the `Interval Start Time (UTC)` column to stmt and txn
tables. Statements and transactions are now both grouped by their `aggregated_ts`
field in addition to the stmt / fingerprint id.

To support viewing of statements grouped by aggregation interval start time,
a new query parameter has been added to statement details pages.
If `aggregated_ts` is set, it will display the statement details for statements
aggregated at that interval, using data from combined statements API response.
If unset, we will fetch and show statement data from in-memory stats.

Release note (ui change): A new column, 'Interval Start Time (UTC)', has
been added to both statement and transaction tables. The column represents
the start time in UTC of the stats aggregation interval for a statement.
By default, the aggregation interval is 1 hour.

A new query parameter has been added to statement details pages.
If the search param `aggregated_ts` is set, it will display the statement details
for statements aggregated at that interval. If unset, we will display the statement
details for the statement collected from the last hour.

2021-09-15 21:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70282)
<!-- Reviewable:end -->

2021-09-16 14:12 UTC, matthewtodd requested changes
I like it! Just a couple of questions.

> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-:-Mjiwu_i-vSIwDRCT2h_:b-j0hndm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjitBpj4yKmg3uWCOI4:-MjitBpj4yKmg3uWCOI5:b9fcbte) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L121)):*
> ```XML
> 
> // Mock value for aggregated timestamp: Sep 15 2021 01:00:00 GMT+0000
> const aggregatedTs = 1631667600;
> ```

nit: I don't know if this particular value is important, but you could do something like `Date.parse("Sep 15 2021 01:00:00 UTC") / 1000` to make the value self-describing.
___
*[pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjitv50BbgWJDV021AA:-Mjitv50BbgWJDV021AB:budw6dj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L95)):*
> ```XML
> // The function parameter is a StatisticType, which represents the type
> // of data the statistics are based on (e.g. statements, transactions, or transactionDetails). The
> // StatisticType is used to modify the content of the tooltip.
> ```

nit: Remove this StatisticType comment since the parameter's gone away?
___
*[pkg/ui/workspaces/cluster-ui/src/util/convert.ts, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjiv6QU9c-d_LaQkvdf:-Mjiv6QV5DBY2596tnwz:bdu7ang) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/util/convert.ts#L65)):*
> ```XML
>     return defaultIfNull;
>   }
>   return timestamp.seconds.toNumber() + NanoToMilli(timestamp.nanos);
> ```

Is this correct? It looks like we're adding (integer) seconds with (integer) milliseconds.
___
*[pkg/ui/workspaces/db-console/src/util/convert.ts, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjiwLA83OuHri0fXYUT:-MjiwLA83OuHri0fXYUU:b-816h6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/db-console/src/util/convert.ts#L76)):*
> ```XML
>     return defaultIfNull;
>   }
>   return timestamp.seconds.toNumber() + NanoToMilli(timestamp.nanos);
> ```

Same.
___
*[pkg/ui/workspaces/db-console/src/util/query.ts, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjiwRIpA_vtezzyKluP:-MjiwRIqDAPSZGjOHVQ3:brnr1bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/db-console/src/util/query.ts#L34)):*
> ```XML
>         : null,
>     ),
>   ).join("&");
> ```

nit: Just curious, in the other location you used `URLSearchParams`. Any reason for the difference? (And I'm also wondering if these are worth sharing, rather than defining twice...)


<!-- Sent from Reviewable.io -->

2021-09-16 14:35 UTC, maryliag requested changes
> Reviewed 24 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjitv50BbgWJDV021AA:-MjiyJvn6vHMiiu0YBtR:bsa7ufn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L95)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Remove this StatisticType comment since the parameter's gone away?
</blockquote></details>

we don't have the parameter for the new column, but it is still being used on other titles, so the comment still stands :) 
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjiyrxI5whvvZrQFUfa:-MjiyrxI5whvvZrQFUfb:bvslx6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L79)):*
> ```XML
>   filters?: Filters;
>   statementFingerprintIds: Long[] | null;
>   aggregatedTs: protos.google.protobuf.ITimestamp | null;
> ```

nit: add the type a little above like we do with the other types and then call here
```
type ITimestamp = protos.google.protobuf.ITimestamp
...
aggregatedTs: ITimestamp | null
```

___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjizKZS1pkFpljjIZa4:-MjizKZS1pkFpljjIZa5:bh2xf3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L60)):*
> ```XML
> export const getStatementsByFingerprintIdAndTime = (
>   statementFingerprintIds: Long[],
>   timestamp: protos.google.protobuf.ITimestamp | null,
> ```

nit: similar to me other comment
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsTable.tsx, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjizvdF0ikV04qdgS8K:-MjizvdF0ikV04qdgS8L:b-40gf8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsTable.tsx#L138)):*
> ```XML
>     },
>     {
>       name: "interval start time",
> ```

this value needs to be the same key you added to the stats util file, so `intervalStartTime`, otherwise it won't load on the column selector
___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjj-mH-DjP_pF-l3rdj:-Mjj-mH-DjP_pF-l3rdk:b-sxgutk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts#L244)):*
> ```XML
> export function statementKey(stmt: ExecutionStatistics): string {
>   return (
>     stmt.statement + stmt.implicit_txn + stmt.database + stmt.aggregated_ts
> ```

nit: update the comment with the new parameters being used
___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjj0WkX2PF7UIVQrdVv:-Mjj0WkY5zDZN1ZtNdlh:br1cgxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/db-console/src/util/appStats.ts#L228)):*
> ```XML
> export function statementKey(stmt: ExecutionStatistics): string {
>   return (
>     stmt.statement + stmt.implicit_txn + stmt.database + stmt.aggregated_ts
> ```

update the comment on the function
___
*[pkg/ui/workspaces/db-console/src/views/transactions/transactionsPage.tsx, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjj1-Jq-D2onHk98Ecu:-Mjj1-Jr1Kc_nd1BQt4M:b-kwcm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/db-console/src/views/transactions/transactionsPage.tsx#L35)):*
> ```XML
>   (state: AdminUIState) => state.cachedData.statements,
>   (state: CachedDataReducerState<StatementsResponseMessage>) => {
>     if (!state.data || !state.valid) return null;
> ```

nit: can you add some comment about what is a valid statement?


<!-- Sent from Reviewable.io -->

2021-09-16 16:35 UTC, Azhng reviewed
> Reviewed 11 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjR9AS-wsvwKIEZP-C):*
Previously, if the selected time range is more than 1 aggregation interval, we would have 1 entry for each distinct stmt/txn fingerprint, now it seems like if the selected time range is more than 1 aggregation interval, we would have multiple entry for each distinct stmt/txn fingerprint. I'm curious that, with this change, is it still possible for users to view statistics for stmts/txns aggregated across the entire selected time range? 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjNean-_qWZf1KdvkY:-MjjNean-_qWZf1KdvkZ:b-f2izsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L172)):*
> ```XML
>   // If there was no aggregated_ts requested in the search parameters, we show
>   // the latest statement from in-memory stats. This is mostly relevant for displaying
>   // statement details from active queries from the session details page.
> ```

I'm a bit confused by the second part of this comment. SQL Stats doesn't have any information on the "Active Queries", since the active queries are being tracked by a different system. So I'm a bit puzzled here on how is statement details related to active queries? 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjOJlP2VmJ-4Lkozgl:-MjjOJlP2VmJ-4Lkozgm:b-i86eo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L365)):*
> ```XML
> 
>   componentDidMount() {
>     const req = statementsRequestFromProps(this.props);
> ```

nit: perhaps refactor this into a helper func since both `componentDidMount` and `componentWillUnmount` reuse the same code.


<!-- Sent from Reviewable.io -->

2021-09-16 17:40 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjizKZS1pkFpljjIZa4:-MjjGn_28sRMCBdddXJs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L60)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: similar to me other comment
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsTable.tsx, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjizvdF0ikV04qdgS8K:-MjjG_3-4LkGkPq3ja2F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsTable.tsx#L138)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this value needs to be the same key you added to the stats util file, so `intervalStartTime`, otherwise it won't load on the column selector
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/util/convert.ts, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjiv6QU9c-d_LaQkvdf:-Mjj-seA8LpEUZABcQSC:b956mh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/util/convert.ts#L65)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Is this correct? It looks like we're adding (integer) seconds with (integer) milliseconds.
</blockquote></details>

Fixed! Nice catch.
___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjj-mH-DjP_pF-l3rdj:-Mjjg5Ok8cnACoiBi3vS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts#L244)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: update the comment with the new parameters being used
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjj0WkX2PF7UIVQrdVv:-MjjgHYrBPViWeyxjmXm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/db-console/src/util/appStats.ts#L228)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

update the comment on the function
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/util/convert.ts, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjiwLA83OuHri0fXYUT:-Mjj0-NxC-g-q4BO_XBQ:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/db-console/src/util/convert.ts#L76)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Fixed.
___
*[pkg/ui/workspaces/db-console/src/util/query.ts, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjiwRIpA_vtezzyKluP:-Mjj04DdEnd3bigxwVpL:b-sxabi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/db-console/src/util/query.ts#L34)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Just curious, in the other location you used `URLSearchParams`. Any reason for the difference? (And I'm also wondering if these are worth sharing, rather than defining twice...)
</blockquote></details>

Ah, I just moved this function over from where it was previously defined in `api.ts` since they seemed to be doing the same thing (but this function ignores nullish params). I've now matched it with the one from `cluster-ui`, as that one is more up to date.
I don't think cluster-ui currently packages its query utils, hence the duplication.
___
*[pkg/ui/workspaces/db-console/src/views/transactions/transactionsPage.tsx, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjj1-Jq-D2onHk98Ecu:-Mjj6JQp22S1BNAUcFsI:b-nzf2ss) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/db-console/src/views/transactions/transactionsPage.tsx#L35)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: can you add some comment about what is a valid statement?
</blockquote></details>

Done, and changed it to inFlight for db-console which I think makes more sense. My intention here was I wanted to show the loading screen while we are fetching new data, for when the user sets a new date range / resetting the date. The cluster-ui states don't have an inFilght state, but !state.isValid should accomplish the same loading behaviour.


<!-- Sent from Reviewable.io -->

2021-09-16 17:49 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, @maryliag, @matthewtodd, and @xinhaoz)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjR9AS-wsvwKIEZP-C):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Previously, if the selected time range is more than 1 aggregation interval, we would have 1 entry for each distinct stmt/txn fingerprint, now it seems like if the selected time range is more than 1 aggregation interval, we would have multiple entry for each distinct stmt/txn fingerprint. I'm curious that, with this change, is it still possible for users to view statistics for stmts/txns aggregated across the entire selected time range? 
</blockquote></details>

As of this change, it will not be possible to view the stmt/txn fingerprint aggregated over the user-specified time range, and there will be multiple entries for a stmt/txn fingerprint (with the specified agg interval start time). I am going off the figma, but @kevin-v-ngo can probably confirm the expected view/behaviour here.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjNean-_qWZf1KdvkY:-Mjji0qx5rbeFSIqajwv:b-76o71j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L172)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I'm a bit confused by the second part of this comment. SQL Stats doesn't have any information on the "Active Queries", since the active queries are being tracked by a different system. So I'm a bit puzzled here on how is statement details related to active queries? 
</blockquote></details>

Currently on session details, the active query links to the statement details page for the query based on the URL created from the active query info. Are you saying we will never have collected information for the active query? 


<!-- Sent from Reviewable.io -->

2021-09-16 17:58 UTC, maryliag reviewed
> Reviewed 3 of 37 files at r1, 13 of 14 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjj0WkX2PF7UIVQrdVv:-Mjjk5pe9HNM5WWE6hkA:b6ve9qx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/db-console/src/util/appStats.ts#L228)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You marked as done, but you forgot to address this :) 


<!-- Sent from Reviewable.io -->

2021-09-16 18:04 UTC, xinhaoz commented
___
*[pkg/ui/workspaces/db-console/src/util/appStats.ts, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-Mjj0WkX2PF7UIVQrdVv:-MjjljFe9HlkPti203gG:b3v313v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/db-console/src/util/appStats.ts#L228)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

You marked as done, but you forgot to address this :) 
</blockquote></details>

Whoops, didn't hit save on the file :facepalm:  Done!


<!-- Sent from Reviewable.io -->

2021-09-16 18:45 UTC, maryliag reviewed
can you add the issue number here and on the commit message? thanks

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-:-MjjvLNK1o9HsXtv_CcD:b-3ro1ud)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, @matthewtodd, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2021-09-16 19:23 UTC, xinhaoz commented
Done.





<!-- Sent from Reviewable.io -->

2021-09-17 02:58 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, @matthewtodd, and @xinhaoz)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjR9AS-wsvwKIEZP-C):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

As of this change, it will not be possible to view the stmt/txn fingerprint aggregated over the user-specified time range, and there will be multiple entries for a stmt/txn fingerprint (with the specified agg interval start time). I am going off the figma, but @kevin-v-ngo can probably confirm the expected view/behaviour here.
</blockquote></details>

Interesting. I suppose some customer feedback would be helpful here to see whether aggregated or non-aggregated behaviour is preferred, if there's any preference at all. 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjNean-_qWZf1KdvkY:-MjlfxFrBi8NfCxocDw1:b-gpzt3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L172)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Currently on session details, the active query links to the statement details page for the query based on the URL created from the active query info. Are you saying we will never have collected information for the active query? 
</blockquote></details>

Interesting, I didn't know you can redirect from Session Page to Statement Detail Page. Though I know for sure that until the query is done executing, we won't have stats available in the from the API. The result would be a blank page like follow.

![Screen Shot 2021-09-16 at 22.57.02.png](https://files.reviewableusercontent.io/images/reviewable/9267198/Lcb_orDGcfZmA868jFcVM0eP/Screen%20Shot%202021-09-16%20at%2022.57.02.png)


<!-- Sent from Reviewable.io -->

2021-09-17 18:08 UTC, xinhaoz commented
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjNean-_qWZf1KdvkY:-MjovvLs6tZQ1TJX_WTA:bg4u8s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L172)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Interesting, I didn't know you can redirect from Session Page to Statement Detail Page. Though I know for sure that until the query is done executing, we won't have stats available in the from the API. The result would be a blank page like follow.

![Screen Shot 2021-09-16 at 22.57.02.png](https://files.reviewableusercontent.io/images/reviewable/9267198/Lcb_orDGcfZmA868jFcVM0eP/Screen%20Shot%202021-09-16%20at%2022.57.02.png)

</blockquote></details>

I see, that makes sense... In that case, is redirecting from session details active query -> statement details useful? Seems like we would often get results like this. cc @kevin-v-ngo 


<!-- Sent from Reviewable.io -->

2021-09-21 02:03 UTC, kevin-v-ngo reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjR9AS-wsvwKIEZP-C):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Interesting. I suppose some customer feedback would be helpful here to see whether aggregated or non-aggregated behaviour is preferred, if there's any preference at all. 
</blockquote></details>

A good start is non-aggregated. It can help pinpoint outliers at the interval granularity. As we get feedback, it'd be interesting to see if/how we can correlate Start Time with areas such as our time-series metrics.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjNean-_qWZf1KdvkY:-Mk54jtUDupi2iUu2VnB:b297i64) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L172)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I see, that makes sense... In that case, is redirecting from session details active query -> statement details useful? Seems like we would often get results like this. cc @kevin-v-ngo 
</blockquote></details>

We'd only get results if the statement fingerprint has already executed in the most recent interval correct? So this message would only appear during the fingerprint’s first execution within the current aggregation interval coming from the sessions page. 

Can we update the text to clarify? "Statement statistics have not yet been collected within the current interval for this statement fingerprint."  


<!-- Sent from Reviewable.io -->

2021-09-21 18:10 UTC, xinhaoz commented
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-MjjNean-_qWZf1KdvkY:-Mk8YCZq44uxgsgMbA5H:b7w9q7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad7a4a026b2a24a96be45355730899a9fdd494d/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L172)):*
<details><summary><i>Previously, kevin-v-ngo wrote…</i></summary><blockquote>

We'd only get results if the statement fingerprint has already executed in the most recent interval correct? So this message would only appear during the fingerprint’s first execution within the current aggregation interval coming from the sessions page. 

Can we update the text to clarify? "Statement statistics have not yet been collected within the current interval for this statement fingerprint."  

</blockquote></details>

Spoke to Kevin offline about this and we will be removing the link to statement details from session details in a separate issue.


<!-- Sent from Reviewable.io -->

2021-09-22 00:00 UTC, kevin-v-ngo commented
@Annebirzin and I chatted today and noticed that we should include the Interval Start Time on the Statement details page. This would allow the user to understand which interval they came from and are viewing statistics for. I created a separate issue [here](https://github.com/cockroachdb/cockroach/issues/70545) but it would be great if we can have this for the V1 experience in 21.2.

2021-09-29 15:01 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 38 files at r7, 26 of 37 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70282#-:-Mkm3qng2057bhwUsC-U:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, @matthewtodd, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2021-09-29 19:59 UTC, xinhaoz commented
TFTR!
bors r=maryliag

2021-09-29 21:39 UTC, merged