Issue 32811: sql: SHOW GRANTS on empty db does not show grant on db until new table is created
cockroachdb/cockroach pull request #70316
Opened 2021-09-16 14:27 UTC by jackcwu

https://github.com/cockroachdb/cockroach/issues/32811#issuecomment-920366066

replaced two calls with writeNonDropDatabaseChange in grant_revoke.go and added tests

2021-09-17 18:17 UTC, rafiss commented
glad you identified this improvement!

one nit: the convention is to make the PR title have a title of `package: lower case description`. so in this case, you should remove "Issue 32811" from the PR title. Instead, in the PR _body_ you should add a line like `references #32811`, which will automatically link to the issue. (Usually, you don't need the Github issue link in the commit, just in the PR)

2021-09-22 19:26 UTC, RichardJCai approved these changes

2021-09-23 02:50 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jackcwu and @rafiss)

___
*[pkg/sql/grant_revoke.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70316#-MkFXyO_0eUx7ofHmHXh:-MkFXyO_0eUx7ofHmHXi:bk9ucsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7693659df1ee2c0546358a47f5c0831d69d3299/pkg/sql/grant_revoke.go#L213)):*
> ```Go
> 		switch d := descriptor.(type) {
> 		case *dbdesc.Mutable:
> 			p.writeNonDropDatabaseChange(ctx, d, fmt.Sprintf("updating privileges for database %d", d.ID))
> ```

check out the error from TeamCity -- it's saying that the error returned by this call needs to get handed:
```
lint_test.go:1577: pkg/sql/grant_revoke.go:213:32:  p.writeNonDropDatabaseChange(ctx, d, fmt.Sprintf("updating privileges for database %d", d.ID)) <- unchecked error
```


also, maybe question for @richardjcai, but is this change what we want? isn't it better if we actually put all the changes into the same batch (created on L158). that way all the changes can get in parallel when we get to the end of the `for` loop: https://github.com/cockroachdb/cockroach/blob/351d9895de50c875a97aa92414380fd387a8d71d/pkg/sql/grant_revoke.go#L292-L295

if so, then the fix would be to change the order of `createNonDropDatabaseChangeJob` and `writeDatabaseChangeToBatch` (so that `createNonDropDatabaseChangeJob` is called first)


<!-- Sent from Reviewable.io -->

2021-09-23 21:27 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/grant_revoke.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70316#-MkFXyO_0eUx7ofHmHXh:-MkJXxfF5dOWsUxzyflz:b-1x3gcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7693659df1ee2c0546358a47f5c0831d69d3299/pkg/sql/grant_revoke.go#L213)):*
> also, maybe question for @RichardJCai, but is this change what we want? isn't it better if we actually put all the changes into the same batch (created on L158). that way all the changes can get in parallel when we get to the end of the for loop: 

Oh shoot you're right, `writeNonDropDatabaseChange` runs the batch, we don't want that. 

I think we can just close this out, the order of `createNonDropDatabaseChangeJob` and `writeDatabaseChangeToBatch` doesn't matter.


<!-- Sent from Reviewable.io -->

2021-09-23 21:48 UTC, closed without merging

2021-09-23 21:48 UTC, jackcwu commented
nonissue