release-21.1: server: acceptance tests asserting backwards compatibility with recent patches
cockroachdb/cockroach pull request #70327
Opened 2021-09-16 18:36 UTC by HonoreDB

version-upgrade tests upgrading and downgrading across major/minor versions. This
pr adds a similar test upgrading and downgrading across patch versions, and therefore
allows upgrades to finalize before downgrading them.

It doesn't do any fixture management since the purpose isn't to test the whole upgrade
path, just recent-version interoperability, so we can start from a clean cluster.

Release note: None

2021-09-16 18:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70327)
<!-- Reviewable:end -->

2021-09-18 21:49 UTC, knz reviewed
LGTM but would also like another person from test eng to have a look.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-:-MjusZH0-eaOBJqy2k5O:bg4kswm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @HonoreDB, and @tbg)

___
*[pkg/cmd/roachtest/versionupgrade.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-MjusLDxAK_uoZ4TFth2:-MjusLDxAK_uoZ4TFth3:bcsupu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b4cef2877e7ac645b32379c05ead5e5a1d8738/pkg/cmd/roachtest/versionupgrade.go#L81)):*
> ```Go
> 
> // setupPersistentDB is a test step when running on a new cluster to
> // make it look like the fixtures
> ```

nit: period at end of sentence.
___
*[pkg/cmd/roachtest/versionupgrade.go, line 662 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-MjusSJrBsJvcBTr5RR8:-MjusSJrBsJvcBTr5RR9:b3r8bkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b4cef2877e7ac645b32379c05ead5e5a1d8738/pkg/cmd/roachtest/versionupgrade.go#L662)):*
> ```Go
> 		testFeaturesStep,
> 		// Since we've done nothing to stop it, the cluster version
> 		// should be updated if it's going to, but let's make sure
> ```

nit: here and below, make full sentences with a period at the end.


<!-- Sent from Reviewable.io -->

2021-09-27 08:28 UTC, tbg requested changes
How long do these tests run? The `acceptance/` family of roachtests is run on *every* CI and while it's important that we don't break patch compat again, it is also a very rare thing to happen. Can we move these to nightly-only? This means making them free-standing roachtests.

I'm also curious about the decision to run without fixtures. I see how the incident triggering this bug didn't need fixtures because it was a very obvious breakage. But in general, compat problems introduced in a patch release could be much more subtle, and if it wouldn't hurt to start from a fixture we should.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-:-MkaLLgW6RU8237Pq2B3:b-9y4b0k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @HonoreDB, and @knz)

___
*[pkg/cmd/roachtest/acceptance.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-MkaLxA-1LxpqctPu7w5:-MkaLxA-1LxpqctPu7w6:b-lxtxdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec4724ab5ffc53507437c153a3193a923e12c76/pkg/cmd/roachtest/acceptance.go#L60)):*
> ```Go
> 				name: "patch-upgrade",
> 				fn: func(ctx context.Context, t *test, c *cluster) {
> 					runPatchUpgrade(ctx, t, c, r.buildVersion, 0)
> ```

`0 /* offset */`
___
*[pkg/cmd/roachtest/acceptance.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-MkaLyNpE5Eh_LZ22HZk:-MkaLyNpE5Eh_LZ22HZl:b2zq51l) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec4724ab5ffc53507437c153a3193a923e12c76/pkg/cmd/roachtest/acceptance.go#L69)):*
> ```Go
> 				name: "double-patch-upgrade",
> 				fn: func(ctx context.Context, t *test, c *cluster) {
> 					runPatchUpgrade(ctx, t, c, r.buildVersion, 1)
> ```

`1 /* offset */`
___
*[pkg/cmd/roachtest/test_runner.go, line 1237 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-MkaM1gh4WwVbA8ks-1K:-MkaM1gh4WwVbA8ks-1L:b-u0exe6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec4724ab5ffc53507437c153a3193a923e12c76/pkg/cmd/roachtest/test_runner.go#L1237)):*
> ```Go
> }
> 
> // RecentPatchVersions returns up to n version strings from the same minor release as buildVersion
> ```

Punctuation, and also specify the format in which they are returned (we have `vX.Y.Z` and `X.Y.Z`, here it's the latter).

Also document where this starts and the ordering. If the version is `21.1.2-123`, then the returned versions are `21.1.2`, `21.1.1`, ..., for a length of `n`.


<!-- Sent from Reviewable.io -->

2021-09-27 20:34 UTC, HonoreDB reviewed
Thanks for the review! These are about 2 minutes each as local tests, but I agree there's no reason for them to be in the main CI. I've moved them outside `acceptance/`, hopefully correctly. Fixture management for the version-upgrade tests looks painful and manual, not a step I'd want to add to every release. This should still catch data incompatibility issues with recent patch versions, and version-upgrade catches incompatibility with older releases, so the gap is pretty narrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-:-MkcvWAa-3go0jSkDB6Y:bwu2nom)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @knz)

___
*[pkg/cmd/roachtest/test_runner.go, line 1237 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-MkaM1gh4WwVbA8ks-1K:-MkcvI1GBK5i9yAOVJlQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec4724ab5ffc53507437c153a3193a923e12c76/pkg/cmd/roachtest/test_runner.go#L1237)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Punctuation, and also specify the format in which they are returned (we have `vX.Y.Z` and `X.Y.Z`, here it's the latter).

Also document where this starts and the ordering. If the version is `21.1.2-123`, then the returned versions are `21.1.2`, `21.1.1`, ..., for a length of `n`.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/versionupgrade.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-MjusLDxAK_uoZ4TFth2:-MkcvKZQ-btHUeN0yTCu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b4cef2877e7ac645b32379c05ead5e5a1d8738/pkg/cmd/roachtest/versionupgrade.go#L81)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: period at end of sentence.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/acceptance.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-MkaLxA-1LxpqctPu7w5:-MkcvO__-TkceNnHJ2OK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec4724ab5ffc53507437c153a3193a923e12c76/pkg/cmd/roachtest/acceptance.go#L60)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

`0 /* offset */`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-05 23:32 UTC, knz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but please also get an approval from the test eng team.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-:-MlHnE2RAkVzarj_Qi-2:b-1qo6wv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2021-10-28 10:50 UTC, tbg reviewed
So sorry to let this sit, I think this must've fallen prey to me emptying out my inbox after I came back from PTO a while ago.
This looks good, once we use the fixtures in this test as well (or you explain why we shouldn't). The current rationale

>   It doesn't do any fixture management since the purpose isn't to test the whole upgrade
  path, just recent-version interoperability, so we can start from a clean cluster.

isn't convincing to me. An empty cluster is a lot more trivial than a cluster from the fixture (for that major version); the fixture still adds value. It makes sure that the data in the store evolved all the way from 1.0 (or whatever version I started them from). It shouldn't be difficult to use the fixture, let me know if you run into any problems.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-:-Mn5Vv882WzZ4BlvB_Br:ba0xaig)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @HonoreDB)

___
*[pkg/cmd/roachtest/versionupgrade.go, line 655 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70327#-Mn5VSoxAM9IeKyiRq6d:-Mn5VSoxAM9IeKyiRq6e:b-ba1q0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ce353146205ef56bab6d74b58b20b3e3ca0685/pkg/cmd/roachtest/versionupgrade.go#L655)):*
> ```Go
> 		// Start a cluster from a previous patch version.
> 		uploadAndStartEmptyCluster(c.All(), predecessorVersion),
> 		setupPersistentDB.step(c.All().randNode()),
> ```

This seems off, why aren't we starting the predecessor version from the fixture? The data in the fixtures is bound to evolve over time and so `setupPersistentDB` would have to evolve in lockstep; that seems wrong, and beside it's hard to guarantee that they manage to create the same state (in fact, they most certainly won't).


<!-- Sent from Reviewable.io -->

2025-07-09 07:05 UTC, closed without merging