69852/ccl/error message invalid timestamp/table
cockroachdb/cockroach pull request #70421
Opened 2021-09-20 14:59 UTC by wongio123

2021-09-21 16:16 UTC, HonoreDB requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shermanCRL and @wongio123)

___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk84c0n19-Eml_0Lf9X):*
Commit message has a stray copy of the release note template in it. Also, s/oututs/outputs
___
*[pkg/ccl/backupccl/backupresolver/targets.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk84s5V8zk8kNzvUwG_:-Mk84s5V8zk8kNzvUwGa:b-d95php) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d19cbd2b0fbe7f6d68c92378f9f9d525d03322a/pkg/ccl/backupccl/backupresolver/targets.go#L46)):*
> ```Go
> // MissingTableErr is a custom error type for Missing Table when resolver.ResolveExisting() is called in DescriptorsMatchingTargets
> type MissingTableErr struct {
> 	Inner     error
> ```

Please call this Wrapped to align with how the rest of the codebase does this (unless it turns out there's some magic behind that and it breaks everything)
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk86J927qmS6y4fpdqx:-Mk86J927qmS6y4fpdqy:b-tnj5wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d19cbd2b0fbe7f6d68c92378f9f9d525d03322a/pkg/ccl/changefeedccl/changefeed_test.go#L284)):*
> ```Go
> 	defer cleanup()
> 
> 	tenantArgs := base.TestTenantArgs{
> ```

Non-blocking: You can delete all of the tenant stuff here and make this test much simpler. The only setup you need is to not create any tables, so you could delete all references to tenantSQL except for the one creating the changefeed, which you'd change to kvSQL. Then just delete the CREATE TABLE statement.


<!-- Sent from Reviewable.io -->

2021-09-21 16:58 UTC, HonoreDB approved these changes
Nicely done!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-:-Mk8Hrun3UVe_eA_bKlC:b-ao1qb6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shermanCRL and @wongio123)



<!-- Sent from Reviewable.io -->

2021-09-21 18:57 UTC, miretskiy requested changes
This PR needs description.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-:-Mk8hcRZBTgc5CW1J9sY:b-ptu6zu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shermanCRL and @wongio123)

___
*[pkg/ccl/backupccl/backupresolver/targets.go, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk8hhbv9LV-lFcWR6db:-Mk8hhbv9LV-lFcWR6dc:bthxk3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/d81bc358528450cb92beeebce8532e94edc96f6c/pkg/ccl/backupccl/backupresolver/targets.go#L44)):*
> ```Go
> }
> 
> // MissingTableErr is a custom error type for Missing Table when resolver.ResolveExisting() is called in DescriptorsMatchingTargets
> ```

nit: wrap extra long comment.
___
*[pkg/ccl/backupccl/backupresolver/targets.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk8hys87ReQv9gnEKx-:-Mk8hys87ReQv9gnEKx0:bqwkxww) ([raw file](https://github.com/cockroachdb/cockroach/blob/d81bc358528450cb92beeebce8532e94edc96f6c/pkg/ccl/backupccl/backupresolver/targets.go#L46)):*
> ```Go
> // MissingTableErr is a custom error type for Missing Table when resolver.ResolveExisting() is called in DescriptorsMatchingTargets
> type MissingTableErr struct {
> 	Wrapped   error
> ```

does this field need to be exported?
___
*[pkg/ccl/backupccl/backupresolver/targets.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk8i0CW2-Niv6q4wD4L:-Mk8i0CW2-Niv6q4wD4M:b-3e2qph) ([raw file](https://github.com/cockroachdb/cockroach/blob/d81bc358528450cb92beeebce8532e94edc96f6c/pkg/ccl/backupccl/backupresolver/targets.go#L47)):*
> ```Go
> type MissingTableErr struct {
> 	Wrapped   error
> 	TableName string
> ```

I'd rather not export TableName, and instead provide an accessor function.


<!-- Sent from Reviewable.io -->

2021-09-22 16:32 UTC, wongio123 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @shermanCRL)

___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk84c0n19-Eml_0Lf9X):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Commit message has a stray copy of the release note template in it. Also, s/oututs/outputs
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backupresolver/targets.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk84s5V8zk8kNzvUwG_:-MkDLFep3kwkoPkMf_EK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d19cbd2b0fbe7f6d68c92378f9f9d525d03322a/pkg/ccl/backupccl/backupresolver/targets.go#L46)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Please call this Wrapped to align with how the rest of the codebase does this (unless it turns out there's some magic behind that and it breaks everything)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backupresolver/targets.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk8hys87ReQv9gnEKx-:-MkDLGq87Jb4rRS5qBr2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d81bc358528450cb92beeebce8532e94edc96f6c/pkg/ccl/backupccl/backupresolver/targets.go#L46)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

does this field need to be exported?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backupresolver/targets.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk8i0CW2-Niv6q4wD4L:-MkDLHSh7h4z203KC_-4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d81bc358528450cb92beeebce8532e94edc96f6c/pkg/ccl/backupccl/backupresolver/targets.go#L47)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'd rather not export TableName, and instead provide an accessor function.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk86J927qmS6y4fpdqx:-MkDLJl-2huYwtdMsrd9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d19cbd2b0fbe7f6d68c92378f9f9d525d03322a/pkg/ccl/changefeedccl/changefeed_test.go#L284)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Non-blocking: You can delete all of the tenant stuff here and make this test much simpler. The only setup you need is to not create any tables, so you could delete all references to tenantSQL except for the one creating the changefeed, which you'd change to kvSQL. Then just delete the CREATE TABLE statement.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-22 22:03 UTC, miretskiy approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @shermanCRL)

___
*[-- commits, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70421#-Mk84c0n19-Eml_0Lf9X):*
<details><summary><i>Previously, wongio123 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think we need release note; I think it could be `Release note: None`
I would perhaps rephrase the commit message a bit; perhaps just say that

```
Improve error message returned when checking for table existence.
Introduce an `MissingTableError` error which provides error context to the caller. 
````


<!-- Sent from Reviewable.io -->

2021-09-24 16:36 UTC, wongio123 commented
bors r+

2021-09-24 18:56 UTC, merged