xform: new transformation to convert multiple scalar min/max expressions into scalar subqueries
cockroachdb/cockroach pull request #70496
Opened 2021-09-21 14:59 UTC by msirek

Fixes https://github.com/cockroachdb/cockroach/issues/35038

Previously, only queries with one MIN or MAX expression could
utilize the ReplaceScalarMinMaxWithLimit rewrite rule and
do a limit scan using an index or primary key.

This was inadequate because the user shouldn't have to
rewrite their query manually to avoid a FULL SCAN.

To address this, a new transformation rule,
ReplaceScalarMinMaxWithScalarSubqueries is added to
separate each MIN or MAX expression into its own
scalar subquery, each of which could then trigger
the ReplaceScalarMinMaxWithLimit rule.

Release note (performance improvement): A SELECT query with both
MIN(LeadingIndexColumn) and MAX(LeadingIndexColumn) can now be
performed with two LIMITED SCANs instead of a single FULL SCAN.

2021-09-21 14:59 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=70496) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=70496) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=70496) it.</sub>

2021-09-21 14:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70496)
<!-- Reviewable:end -->

2021-09-21 19:50 UTC, jordanlewis commented
Hi @msirek, thanks for your contribution! We will take a look at this soon.

2021-09-22 13:49 UTC, rytaft reviewed
Really nice work, @msirek, and thanks for the contribution! A few comments, but mostly just nits below.

> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-:-MkCfwi4B3WV5nN2LG9E:b-u8xayp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCYlXHAX95A0fWOyW-):*
nit: typically we try to have the commit title fit on one line
___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCYrJK0L6irbvRZFxx):*
nit: limit -> limited
___
*[.gitignore, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCZ3OL-bK217FugPAb:-MkCZ3OM51PoUFHRygaG:b-2ehc3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/.gitignore#L20)):*
> ```ignore
> *.swp
> .idea
> node[0-9]*
> ```

I don't think you should commit this change
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 514 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCZg_L0yuvkYIJlkby:-MkCZg_M4cqVQBJDjjtu:b-6n0ct7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L514)):*
> ```
> 
> query T
> EXPLAIN (TYPES) SELECT min(a), max(a) FROM abc
> ```

nit: is there a reason we need this much verbosity? `TYPES` is the highest verbosity level
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkC_gnE5_FNXrvjnULI:-MkC_gnF0DsDs1tUEV9o:b-mjtvg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L31)):*
> ```Go
> 
> // MakeMinMaxScalarSubqueries transforms a list of MIN and MAX
> // aggregate expressions (aggs) from a ScanExpr (input) into a
> ```

nit: This is a bit confusing since the aggregate expressions wouldn't be on the scan -- they would be on a groupby, perhaps with the scan as the input to the groupby. Can you rephrase?
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkC_SQa1zCKTpCAcoC6:-MkC_SQa1zCKTpCAcoC7:b-a3nxze) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L32)):*
> ```Go
> // MakeMinMaxScalarSubqueries transforms a list of MIN and MAX
> // aggregate expressions (aggs) from a ScanExpr (input) into a
> // multiple scalar subqueries, with one MIN or MAX expression
> ```

nit: "a multiple scalar subqueries" -> "multiple scalar subqueries"
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCa9PO-l2xSF8ZNluM:-MkCa9PO-l2xSF8ZNluN:b-6tcvx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L37)):*
> ```Go
> 	grp memo.RelExpr, input memo.RelExpr, aggs memo.AggregationsExpr,
> ) {
> ```

nit: extra blank line
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCaKWa2-7bvPH-kwYE:-MkCaKWb5zRzjE6WK7iY:b4ngwex) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L40)):*
> ```Go
> 	// Pushing scalar MIN/MAX into joins is not currently done,
> 	// so only build this transformation for simple ScanExprs.
> 	newScanExpr, inputSuccessfullyCopied := c.TryConstructScan(input)
> ```

nit: I like the self-documenting nature of this variable `inputSuccessfullyCopied`, but it's more idiomatic and probably just as helpful in this case to call it `ok`

Also, it seems like overkill to create a separate function for `TryContructScan`, since you know this function will only be called with a `ScanExpr` (based on how you constructed the rule). I would just directly assert the type in this case.

As I mentioned in another couple of comments, though, you could just pass in the `scanPrivate` directly, and you'll also need to duplicate the private. So you could do this (assuming you passed in `scanPrivate *memo.ScanPrivate` as a function param):
```
newScanPrivate := c.DuplicateScanPrivate(scanPrivate)
newScanExpr := c.e.f.ConstructScan(newScanPrivate)
```
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCbXpFDAxl9cdCBjpt:-MkCbXpFDAxl9cdCBjpu:b-k70wfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L72)):*
> ```Go
> 	}
> 	tupleTyp := types.MakeTuple(dataTypes)
> 	tuples[0] = factory.ConstructTuple(valuesEntries, tupleTyp)
> ```

nit: I would just construct the single-item ScalarListExpr here instead of making the slice above and assigning this to element 0
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCcD-FEcQM-9yhcddQ:-MkCcD-FEcQM-9yhcddR:b3zm9zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L88)):*
> ```Go
> // otherwise returns nil, false.
> func (c *CustomFuncs) TryConstructScan(in memo.RelExpr) (_ memo.RelExpr, ok bool) {
> ```

nit: remove extra blank line
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCcYzx3pjWPltV3Y81:-MkCcYzy3GynesShQ1Jw:b-wilari) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L92)):*
> ```Go
> 	case *memo.ScanExpr:
> 		private := &t.ScanPrivate
> 		return c.e.f.ConstructScan(private), true
> ```

I don't think you can just reuse the `ScanPrivate` here, since you'll be reusing the column IDs. We have a function `DuplicateScanPrivate` you can use for this purpose.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCd14e6LJEj_ouecR4:-MkCd14e6LJEj_ouecR5:b-i5hx6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L109)):*
> ```Go
> 
> 		switch agg.Agg.Op() {
> 		case opt.MinOp:
> ```

nit: this works since you're returning true below, but this won't actually fall through to the MaxOp case. I would just put them on the same line, e.g. `case opt.MinOp, opt.MaxOp:`
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkChFFwEpATXjc4LWLn:-MkChFFx4yx2kZ4OOdLt:bhk1rdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/rules/groupby.opt#L13)):*
> ```
> [ReplaceScalarMinMaxWithScalarSubqueries, Explore]
> (ScalarGroupBy
>     $input:(Scan)
> ```

I think you want to check that this is a canonical scan. Maybe there are cases where we would want to allow a constrained scan here, but that will require a lot more testing and seems like it could be error-prone. I would suggest limiting this to a canonical scan for now, and if we find a use case later we can expand this to include constrained scans.

You can also grab the scanPrivate here so you don't need to get it inside `MakeMinMaxScalarSubqueries`. For example, you can change
```
$input:(Scan)
```
to
```
(Scan $scanPrivate:* & (IsCanonicalScan $scanPrivate))
```
and then pass `$scanPrivate` to `MakeMinMaxScalarSubqueries`
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCfF48ByOIiHF_8bmc:-MkCfF48ByOIiHF_8bmd:bt98riz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/testdata/r [...]

2021-09-22 13:54 UTC, mgartner requested changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[.gitignore, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCZ3OL-bK217FugPAb:-MkClq6t9uivR2fAJlr8:bg59mfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/.gitignore#L20)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think you should commit this change
</blockquote></details>

Rather than update the shared `.gitignore` file, you can add your own ignore rules to `.git/info/exclude`.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCl001E304W2yezlgT:-MkCl001E304W2yezlgU:b-nbwwyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L35)):*
> ```Go
> // per subquery.
> func (c *CustomFuncs) MakeMinMaxScalarSubqueries(
> 	grp memo.RelExpr, input memo.RelExpr, aggs memo.AggregationsExpr,
> ```

Your pattern ensures that `input` is a `ScanExpr` with `$input:(Scan)`. So, optgen will generate code that passes a variable typed as a `*ScanExpr` to this function. So you can change `input memo.RelExpr` to `input *memo.ScanExpr` and avoid any checks within this function to ensure that it is indeed a ScanExpr.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCj_OA5iVJyKDvWWba:-MkCj_OA5iVJyKDvWWbb:b-ge5aj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L40)):*
> ```Go
> 	// Pushing scalar MIN/MAX into joins is not currently done,
> 	// so only build this transformation for simple ScanExprs.
> 	newScanExpr, inputSuccessfullyCopied := c.TryConstructScan(input)
> ```

~I think we'll need a new table ID and column IDs for the duplicated scan. You should be able to use `CustomFuncs.DuplicateScanPrivate` to get a new ScanPrivate which you can pass to `c.e.f.ConstructScan`.~

Looks like @rytaft beat me to it :P


<!-- Sent from Reviewable.io -->

2021-09-23 06:03 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCYlXHAX95A0fWOyW-):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: typically we try to have the commit title fit on one line
</blockquote></details>

OK, changing it to:
    xform: convert 2+ scalar min/max expressions into subqueries
___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCYrJK0L6irbvRZFxx):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: limit -> limited
</blockquote></details>

done
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkC_gnE5_FNXrvjnULI:-MkDM9rl7Jq8_rZJc69a:b-ik0zbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L31)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: This is a bit confusing since the aggregate expressions wouldn't be on the scan -- they would be on a groupby, perhaps with the scan as the input to the groupby. Can you rephrase?
</blockquote></details>

Good point.  Changed it to:
# ReplaceScalarMinMaxWithScalarSubqueries replaces a scalar group by
# having a single ScanExpr and n > 1 MIN/MAX expressions with
# n scalar subqueries, so that each subquery may take advantage
# of the ReplaceScalarMinMaxWithLimit rule.
# NOTE: The input relation must be a simple scan as currently no
# other cases, such as joins, can take advantage of this rewrite.

I used the term "ScanExpr" for code-level clarity, but if this term is out of place here I can change it to "scan" or something else.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkC_SQa1zCKTpCAcoC6:-MkDOTPM2yHlz3Jw8393:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L32)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: "a multiple scalar subqueries" -> "multiple scalar subqueries"
</blockquote></details>

Fixed
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCl001E304W2yezlgT:-MkDXUAPDJlj5Iz8hZ67:bvhfw1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L35)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Your pattern ensures that `input` is a `ScanExpr` with `$input:(Scan)`. So, optgen will generate code that passes a variable typed as a `*ScanExpr` to this function. So you can change `input memo.RelExpr` to `input *memo.ScanExpr` and avoid any checks within this function to ensure that it is indeed a ScanExpr.
</blockquote></details>

Thanks.  I removed "input" entirely since refactoring from other comments adds new arg scanPrivate.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCa9PO-l2xSF8ZNluM:-MkDXQlp6VFR9e-rHPWs:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L37)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: extra blank line
</blockquote></details>

Removed
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCaKWa2-7bvPH-kwYE:-MkDX65KDe39RgxgMsHf:b-2vusjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L40)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: I like the self-documenting nature of this variable `inputSuccessfullyCopied`, but it's more idiomatic and probably just as helpful in this case to call it `ok`

Also, it seems like overkill to create a separate function for `TryContructScan`, since you know this function will only be called with a `ScanExpr` (based on how you constructed the rule). I would just directly assert the type in this case.

As I mentioned in another couple of comments, though, you could just pass in the `scanPrivate` directly, and you'll also need to duplicate the private. So you could do this (assuming you passed in `scanPrivate *memo.ScanPrivate` as a function param):
```
newScanPrivate := c.DuplicateScanPrivate(scanPrivate)
newScanExpr := c.e.f.ConstructScan(newScanPrivate)
```
</blockquote></details>

Thanks.  Removed TryContructScan, passed new arg scanPrivate, and added DuplicateScanPrivate.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCj_OA5iVJyKDvWWba:-MkDWwbyBxgfreYMDEfG:b-u6dbq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L40)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

~I think we'll need a new table ID and column IDs for the duplicated scan. You should be able to use `CustomFuncs.DuplicateScanPrivate` to get a new ScanPrivate which you can pass to `c.e.f.ConstructScan`.~

Looks like @rytaft beat me to it :P
</blockquote></details>

Thanks, made the change.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCbXpFDAxl9cdCBjpt:-MkDWn_VCXQx1GOT21nZ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L72)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: I would just construct the single-item ScalarListExpr here instead of making the slice above and assigning this to element 0
</blockquote></details>

Done
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCcD-FEcQM-9yhcddQ:-MkDVat26z_HTfp1i929:bzc7j5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L88)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: remove extra blank line
</blockquote></details>

The TryConstructScan function is removed after refactoring.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCcYzx3pjWPltV3Y81:-MkDU5jL8qPzUyIlFElX:b-p2rql5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L92)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think you can just reuse the `ScanPrivate` here, since you'll be reusing the column IDs. We have a function `DuplicateScanPrivate` you can use for this purpose.
</blockquote></details>

Fixed.  I had tried using DuplicateScanPrivate in an initial fix, but it was causing the rewrite to not occur.  Now I see it's because the column IDs referenced in the MIN and MAX expressions refer to the original scan.  I've added new logic to remap those IDs, which fixes the problem.  I'm creating a new ScanExpr/ScanPrivate pair for every new subquery.  It seems correct, but may generate many new column IDs for wide tables and many MIN and MAX expressions. 
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCd14e6LJEj_ouecR4:-MkDTyVb3K81cUjGAzmi:b-y3t2n7)  [...]

2021-09-23 13:20 UTC, rytaft reviewed
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[pkg/sql/opt/xform/groupby_funcs.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkC_gnE5_FNXrvjnULI:-MkHS3vi5rof8mhKLQFF:b-as80mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L31)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Good point.  Changed it to:
# ReplaceScalarMinMaxWithScalarSubqueries replaces a scalar group by
# having a single ScanExpr and n > 1 MIN/MAX expressions with
# n scalar subqueries, so that each subquery may take advantage
# of the ReplaceScalarMinMaxWithLimit rule.
# NOTE: The input relation must be a simple scan as currently no
# other cases, such as joins, can take advantage of this rewrite.

I used the term "ScanExpr" for code-level clarity, but if this term is out of place here I can change it to "scan" or something else.
</blockquote></details>

That change looks good (looks like you made the change in the opt file), but I was specifically referring to the comment here. I think a small change here would clarify things: "from a ScanExpr" -> "and a ScanExpr"
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHhX4WEQojJHP0lYuq:-MkHhX4WEQojJHP0lYur:b-jmcyib) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L61)):*
> ```Go
> ) {
> 	valuesEntries := make(memo.ScalarListExpr, len(aggs))
> 	numCols := len(aggs)
> ```

nit: you could move this up and pass `numCols` as the length of `valuesEntries`
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHhO4VBLSPkG658Hky:-MkHhO4VBLSPkG658Hkz:b47g451) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L62)):*
> ```Go
> 	valuesEntries := make(memo.ScalarListExpr, len(aggs))
> 	numCols := len(aggs)
> 	dataTypes := make([]*types.T, 0, numCols)
> ```

Why not just make these have length `numCols` too? 
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHZIyABC_aj3NXQJSw:-MkHZIyABC_aj3NXQJSx:b-hdf32j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L77)):*
> ```Go
> 		// Variable expressions must have their ColIDs remapped,
> 		// which requires building a new AggregationsItem.
> 		if variable, ok := aggs[i].Agg.Child(0).(*memo.VariableExpr); ok {
> ```

if you add a check that there are only variable inputs in `TwoOrMoreMinOrMax`, then you can just assert the type here, and panic with `errors.AssertionFailedf` if ok is false. For example:
```
variable, ok := aggs[i].Agg.Child(0).(*memo.VariableExpr)
if !ok {
  panic(errors.AssertionFailedf("expected a variable as input to the aggregate, but found %T", aggs[i].Agg.Child(0)))
}
```
That will also limit the amount of indentation needed below.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHfOIj7jbE1j2Psvfh:-MkHfOIj7jbE1j2Psvfi:b-hoaq8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L79)):*
> ```Go
> 		if variable, ok := aggs[i].Agg.Child(0).(*memo.VariableExpr); ok {
> 			if varColID, ok2 := c.RemapColID(scanPrivate, variable.Col, baseColID); ok2 {
> 				newVarExpr := factory.ConstructVariable(varColID)
> ```

Nice work figuring out how to remap the columns! We already have a way of doing this in other places in the code, though, so I'd rather you follow that example to keep the remapping code in one place (and remove your two new functions above).

I think what you can probably do here is:
```
newVarExpr := c.mapScalarExprCols(variable, scanPrivate.Cols, newScanPrivate.Cols)
```
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHYrDN2nIk-GwNxx3m:-MkHYrDN2nIk-GwNxx3n:b-3ahimm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L87)):*
> ```Go
> 					newAggrFunc = factory.ConstructMin(newVarExpr)
> 				default:
> 					return // Should never happen, but skip this rewrite if it does
> ```

We'd probably want this to panic with an `errors.AssertionFailedf` since it indicates a bug
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHg2GE29i78XaW7pIk:-MkHg2GE29i78XaW7pIl:bbktyhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L93)):*
> ```Go
> 					factory.ConstructAggregationsItem(
> 						newAggrFunc,
> 						c.e.mem.Metadata().AddColumn(columnMeta.Alias, columnMeta.Type),
> ```

Did you try using the original column here (`aggs[i].Col`) instead of adding a new one? I think that should be possible, and might even be necessary. Otherwise any parent operators trying to use the original column might not have the correct input. It would be good to add a test case for this too, where the scalar group by is part of a larger expression (e.g., the output columns are passed to a Projection expression such as `x + 1`)
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHXVGk6liYAfxfNkSv:-MkHXVGl469zupfESVx3:bcnvqnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L146)):*
> ```Go
> 		switch agg.Agg.Op() {
> 		case opt.MinOp, opt.MaxOp:
> 			// The matched case, do nothing
> ```

You should also check here that the input to the min/max is just a single variable, since otherwise the `ReplaceScalarMinMaxWithLimit` rule won't match (be sure to add a test case for this too). 
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkChFFwEpATXjc4LWLn:-MkHkHGP0qaZO9jNT03X:bpiiw37) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/rules/groupby.opt#L13)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Thanks, I've modified it as suggested.  I see function makeNewScan in general_funcs.go remaps columns in constraints.  Maybe it could be used in future work to relax the canonical scan limitation.
</blockquote></details>

Yea, that's a good idea. Since you identified a few cases where it would be beneficial to match on a constrained scan, feel free to make the change now if you'd like. You might still want to check that the scan is not already limited, though.

Otherwise we can always save it for a future PR.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 613 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHlLbVAseys8GeogQ9:-MkHlLbVAseys8GeogQA:b-dhn8pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/testdata/rules/groupby#L613)):*
> ```
> 
> # Verify the rule does not fire when FILTER is used.
> opt expect=ReplaceScalarMinMaxWithLimit
> ```

hmm now this comment seems wrong. I think what's probably happening is that the filter is getting pushed down before the rule fires. Maybe you could leave this test case (fixing the comment), but also add another one with a filter that cannot get pushed into the scan, such as `(WHERE b > 1)`.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, li [...]

2021-09-23 23:48 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 514 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkCZg_L0yuvkYIJlkby:-MkJmDUmEI1m4stakfuK:b-9fgz0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L514)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

That's very surprising that the optimization was not picked for any of these. That implies to me that there might be another bug, since this test case wouldn't constrain the scan otherwise. But you might also try reverting the change to use a canonical scan (see comment above) and see if that fixes it.
</blockquote></details>

I now think these broke when duplicating ScanPrivate was introduced and adding column remapping fixed them.  I've re-added the tests, though the ones with WHERE clauses won't fire the rule until support for constraints is added.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkC_gnE5_FNXrvjnULI:-MkIWKPN31nsxq5Sgt0a:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/groupby_funcs.go#L31)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

That change looks good (looks like you made the change in the opt file), but I was specifically referring to the comment here. I think a small change here would clarify things: "from a ScanExpr" -> "and a ScanExpr"
</blockquote></details>

done
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHhX4WEQojJHP0lYuq:-MkIW_DP6DWaIjHb_Y5f:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L61)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: you could move this up and pass `numCols` as the length of `valuesEntries`
</blockquote></details>

done
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHhO4VBLSPkG658Hky:-MkIXt632wFFUZDXeyAF:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L62)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why not just make these have length `numCols` too? 
</blockquote></details>

done
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHZIyABC_aj3NXQJSw:-MkIsKPgEVCgBO5SyDMw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L77)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

if you add a check that there are only variable inputs in `TwoOrMoreMinOrMax`, then you can just assert the type here, and panic with `errors.AssertionFailedf` if ok is false. For example:
```
variable, ok := aggs[i].Agg.Child(0).(*memo.VariableExpr)
if !ok {
  panic(errors.AssertionFailedf("expected a variable as input to the aggregate, but found %T", aggs[i].Agg.Child(0)))
}
```
That will also limit the amount of indentation needed below.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHfOIj7jbE1j2Psvfh:-MkIsBiB5MQiSS6II8y_:b-69yqv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L79)):*
> panic(errors.AssertionFailedf("expected a variable as input to the aggregate, but found %T", aggs[i].Agg.Child(0)))
Fixed
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHYrDN2nIk-GwNxx3m:-MkIsF893YM1i-cIiHop:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L87)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

We'd probably want this to panic with an `errors.AssertionFailedf` since it indicates a bug
</blockquote></details>

Done
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHg2GE29i78XaW7pIk:-MkJGP-g34kJALtNZX8U:ba5960z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L93)):*
> general_funcs
Yes, originally the code used aggs[i], but that uses a source expression with the wrong column IDs, and so the rewrite did not occur, so a new one with remapped columns is needed.  It sounds like your concern is that the column IDs of the new expression won't match those of the original.  My understanding is that the column IDs in the new scalar group by don't need to match the old scalar group by because we're not calling AddScalarGroupByToGroup.  AddValuesToGroup is called, so instead it is the ValuesExpr which is replacing the original ScalarGroupByExpr, and it is the columns in the ValuesExpr that must have the same column IDs as the original ScalarGroupByExpr.  Please correct me if this is wrong.  I tried some test cases with a projection like x+1, for example:
   select min(a)+1, max(a)+1 from t1;

... and results are correct.  I will add some test cases.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHXVGk6liYAfxfNkSv:-MkJbJM58G1r7HxH4whw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L146)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You should also check here that the input to the min/max is just a single variable, since otherwise the `ReplaceScalarMinMaxWithLimit` rule won't match (be sure to add a test case for this too). 
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkChFFwEpATXjc4LWLn:-MkJbNODCako1fv3YqQ-:b-295p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/rules/groupby.opt#L13)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea, that's a good idea. Since you identified a few cases where it would be beneficial to match on a constrained scan, feel free to make the change now if you'd like. You might still want to check that the scan is not already limited, though.

Otherwise we can always save it for a future PR.
</blockquote></details>

In looking at other examples in the code, splitScanIntoUnionScans for example, it looks like some work would need to be done to build the spans to use and do analysis on the indexes to use (if each MIN or MAX is on a different column).  Perhaps the complexity here warrants its own separate PR.  I haven't had much time today to look at this in depth.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 613 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHlLbVAseys8GeogQ9:-MkJiY1j8nm5aF7fC3wf:bpuzsou) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/testdata/rules/groupby#L613)):*
> ```
> SELECT max(a) FILTER (WHERE a > 'a') FROM abc
> ```
I've fixed the comment and added a WHERE b > 1 test, which also fires the rule.  I think maybe it is OK because this gets bui [...]

2021-09-24 19:22 UTC, msirek commented
To support this rewrite with Filters, it seems like the code should not only construct a new ScanExpr for each subquery, but a new SelectExpr with a copy of the Filter with column IDs remapped.
For this test case:
`select min(a), max(a) from mws.t1 where a < 6;`
The scalar group by expression has a SelectExpr as the first child when the ReplaceScalarMinMaxWithScalarSubqueries rule fires, so it seems like the rewrite should build something similar to preserve the FiltersExpr:

> result = {github.com/cockroachdb/cockroach/pkg/sql/opt.Expr | *github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ScalarGroupByExpr} 
>  Input = {github.com/cockroachdb/cockroach/pkg/sql/opt/memo.RelExpr | *github.com/cockroachdb/cockroach/pkg/sql/opt/memo.SelectExpr} 
>   Input = {github.com/cockroachdb/cockroach/pkg/sql/opt/memo.RelExpr | *github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ScanExpr} 
>   Filters = {github.com/cockroachdb/cockroach/pkg/sql/opt/memo.FiltersExpr} len:1, cap:1
>    0 = {github.com/cockroachdb/cockroach/pkg/sql/opt/memo.FiltersItem} 
>     Condition = {github.com/cockroachdb/cockroach/pkg/sql/opt.ScalarExpr | *github.com/cockroachdb/cockroach/pkg/sql/opt/memo.LtExpr} 
>      Left = {github.com/cockroachdb/cockroach/pkg/sql/opt.ScalarExpr | *github.com/cockroachdb/cockroach/pkg/sql/opt/memo.VariableExpr} 
>      Right = {github.com/cockroachdb/cockroach/pkg/sql/opt.ScalarExpr | *github.com/cockroachdb/cockroach/pkg/sql/opt/memo.ConstExpr}

2021-09-24 21:17 UTC, mgartner reviewed
> To support this rewrite with Filters, it seems like the code should not only construct a new ScanExpr for each subquery, but a new SelectExpr with a copy of the Filter with column IDs remapped.

That sounds right to me. Rather than trying to match non-canonical scans, we can add another rule to match canonical scans under Selects. Something like:

```
(ScalarGroupBy
    (Select
        (Scan $scanPrivate:* & (IsCanonicalScan $scanPrivate))
        $filters:*
    )
    ....
)
```

If you're up for it, you can add this in a follow-up PR and keep this PR succinct.

> Reviewed 2 of 7 files at r1, 5 of 5 files at r3, 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-:-MkOa8ts8SoNH2XHz4rc:bod79s9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[pkg/sql/opt/xform/groupby_funcs.go, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOcPlVCkMy4nasUXLn:-MkOcPlVCkMy4nasUXLo:b5y4khd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/groupby_funcs.go#L42)):*
> ```Go
> 	newCols := make(opt.ColList, numCols)
> 
> 	factory := c.e.f
> ```

nit: we typically just use `c.e.f` through these custom functions rather than assigning it to a variable. 
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOc-Ga-cikSyFElD1K:-MkOc-Ga-cikSyFElD1L:bxjf2lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/groupby_funcs.go#L45)):*
> ```Go
> 	for i := 0; i < numCols; i++ {
> 		// Pushing scalar MIN/MAX into joins is not currently done,
> 		// so only build this transformation for simple ScanExprs.
> ```

nit: I don't think this comment is necessary given the comments above the Rule in groupby.opt.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOeTjn2gYY647KGRiS:-MkOeTjo7Oij4_Ex9QSj:bfnpxxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/groupby_funcs.go#L86)):*
> ```Go
> 		// The VALUES clause inherits the target column ID
> 		// and datatype from the scalar group by, so the
> 		// outputs are identical.
> ```

nit: you can widen comments to 80 characters.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1133 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOe0CHDEq6o7kZEKkV:-MkOe0CHDEq6o7kZEKkW:b9n52cf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/testdata/rules/groupby#L1133)):*
> ```
>       │         ├── scan xyz@yy
>       │         │    ├── columns: y:9!null
>       │         │    ├── constraint: /9/8: (/NULL - ]
> ```

I don't understand why this scan has this constraint (which seems meaningless), and the other scan doesn't. @rytaft is this fine?
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1219 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOeOgyBNx_z-bqCQOr:-MkOeOgyBNx_z-bqCQOs:bgkude) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/testdata/rules/groupby#L1219)):*
> ```
> 
> # ReplaceScalarMinMaxWithScalarSubqueries can only
> # be applied to canonical scans.
> ```

nit: you can widen these comments to 80 characters.


<!-- Sent from Reviewable.io -->

2021-09-25 04:14 UTC, msirek reviewed
OK, sounds good.  I've opened this issue for it:  https://github.com/cockroachdb/cockroach/issues/70735
I haven't yet found a general-purpose expression tree copy function that does a deep copy of all the nodes (for copying the Filter).  Do you know of one?  Thanks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-:-MkPITMJ6wzIC3vHfIHV:bx4kz0x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/groupby_funcs.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHfOIj7jbE1j2Psvfh:-MkP9NbM15RusLElUmJU:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L79)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> panic(errors.AssertionFailedf("expected a variable as input to the aggregate, but found %T", aggs[i].Agg.Child(0)))
Fixed
</blockquote></details>

Fixed
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOcPlVCkMy4nasUXLn:-MkP6wbc0ACmazyYLAhQ:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/groupby_funcs.go#L42)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: we typically just use `c.e.f` through these custom functions rather than assigning it to a variable. 
</blockquote></details>

Fixed
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOc-Ga-cikSyFElD1K:-MkP6Rr782dML9dLwdyO:b11x3hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/groupby_funcs.go#L45)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I don't think this comment is necessary given the comments above the Rule in groupby.opt.
</blockquote></details>

Removed the comment.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOeTjn2gYY647KGRiS:-MkP99uhD0w0n24h6B5z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/groupby_funcs.go#L86)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you can widen comments to 80 characters.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1133 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOe0CHDEq6o7kZEKkV:-MkOsAJ_7makwhPwXtkT:b11bmte) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/testdata/rules/groupby#L1133)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't understand why this scan has this constraint (which seems meaningless), and the other scan doesn't. @rytaft is this fine?
</blockquote></details>

I think it's because there is an implicit NOT NULL constraint on the primary key columns.  The scan of nullable index column 'y' needs to skip over nulls, but the scan of non-null primary key column 'x' does not.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1219 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOeOgyBNx_z-bqCQOr:-MkP4hrkA2yXwptowRoD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/testdata/rules/groupby#L1219)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you can widen these comments to 80 characters.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-27 03:48 UTC, msirek commented
Prototyped filter support:  https://github.com/msirek/cockroach/pull/1/files

2021-09-27 15:56 UTC, rytaft reviewed
> I've opened this issue for it: #70735 

Thanks!

> I haven't yet found a general-purpose expression tree copy function that does a deep copy of all the nodes (for copying the Filter). Do you know of one? Thanks.

I think `CustomFuncs.MapFilterCols` does what you want.

> Prototyped filter support: https://github.com/msirek/cockroach/pull/1/files

Prototype looks like a good start! Typically we'd actually write a completely separate rule for the filter case, and just reuse the custom functions. For example, `GenerateLookupJoins` and `GenerateLookupJoinsWithFilter`:
https://github.com/cockroachdb/cockroach/blob/883e8eea7af8a826857c7f83742ffda470657538/pkg/sql/opt/xform/rules/join.opt#L137
and
https://github.com/cockroachdb/cockroach/blob/883e8eea7af8a826857c7f83742ffda470657538/pkg/sql/opt/xform/rules/join.opt#L192

Whenever you're ready, feel free to open that prototype as a new PR and I can add more comments there.

> Reviewed 2 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-:-MkbvdBC5Tp4Ew0P_QNR:bvqr7s7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 808 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkbgbV88_ZbS8qrZGdr:-MkbgbV9Cwdc8UbAZC7y:b-3y3nlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L808)):*
> ```
> 
> # A constrained scan should be preferred over separate subqueries.
> # Also, only canonical scans are supported.
> ```

nit: this comment would be a bit cryptic for someone not aware of what this is testing. I'd just say "we don't yet support the optimization to convert multiple aggregates to subqueries with limit 1 when there is a filter"
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHg2GE29i78XaW7pIk:-Mkbi84e-fd85j470STN:b-3zlco7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L93)):*
> originally the code used aggs[i], but that uses a source expression with the wrong column IDs, and so the rewrite did not occur, ...

Yes, you'd still need to construct a new aggregations item, I'm just suggesting that you could probably reuse the old Column ID for the new agg. e.g.:
```
			c.e.f.ConstructAggregationsItem(
				newAggrFunc,
				aggs[i].Col,
			)

```
What you're doing is also probably fine, I think it just creates new column IDs unnecessarily (I think you're right that it doesn't compromise correctness, it's just a tiny bit less efficient).
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 103 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-Mkbiz2276PjfmYIvu1y:-Mkbiz2276PjfmYIvu1z:b5tbalk) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/xform/groupby_funcs.go#L103)):*
> ```Go
> // or more MIN or MAX expressions on variable expressions with no other type of
> // aggregate function.
> //
> ```

nit: blank line not needed here
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkChFFwEpATXjc4LWLn:-Mkbj4MO-X_pniAYRXoF:b-mm7447) ([raw file](https://github.com/cockroachdb/cockroach/blob/4858c496aeb8b8dfd866d462dec508454e94a78b/pkg/sql/opt/xform/rules/groupby.opt#L13)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

In looking at other examples in the code, splitScanIntoUnionScans for example, it looks like some work would need to be done to build the spans to use and do analysis on the indexes to use (if each MIN or MAX is on a different column).  Perhaps the complexity here warrants its own separate PR.  I haven't had much time today to look at this in depth.
</blockquote></details>

Sounds good -- I would save it for a follow-on PR.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 613 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHlLbVAseys8GeogQ9:-MkbjHNi1tgEEi2UA7mq:bkdjqll) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/testdata/rules/groupby#L613)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> ```
> SELECT max(a) FILTER (WHERE a > 'a') FROM abc
> ```
I've fixed the comment and added a WHERE b > 1 test, which also fires the rule.  I think maybe it is OK because this gets built as a limit hint inside the scan, not a strict limit, and the limit is applied only after the filter is applied (I tried it with data and it produces correct results).  Or maybe there is something different about this test driver that is different from running normal SQL? 

SELECT max(a) FILTER (WHERE b > 3.1415926535) FROM abc
----
scalar-group-by
 ├── columns: max:8
 ├── cardinality: [1 - 1]
 ├── key: ()
 ├── fd: ()-->(8)
 ├── limit
 │    ├── columns: a:1!null b:2!null
 │    ├── internal-ordering: -1
 │    ├── cardinality: [0 - 1]
 │    ├── key: ()
 │    ├── fd: ()-->(1,2)
 │    ├── select
 │    │    ├── columns: a:1!null b:2!null
 │    │    ├── key: (1)
 │    │    ├── fd: (1)-->(2)
 │    │    ├── ordering: -1
 │    │    ├── limit hint: 1.00
 │    │    ├── scan abc,rev
 │    │    │    ├── columns: a:1!null b:2
 │    │    │    ├── key: (1)
 │    │    │    ├── fd: (1)-->(2)
 │    │    │    ├── ordering: -1
 │    │    │    └── limit hint: 3.00
 │    │    └── filters
 │    │         └── b:2 > 3.1415926535 [outer=(2), constraints=(/2: [/3.1415926535000005 - ]; tight)]
 │    └── 1
 └── aggregations
      └── const-agg [as=max:8, outer=(1)]
           └── a:1
</blockquote></details>

I see, we must have some rule that converts the `FILTER` into a select when possible (probably `PushAggFilterIntoScalarGroupBy`). That rule was added after this test case was added, which explains why the test case exists. That rule also fires regardless of whether an index is available, so it's not actually helpful to add a new test case for filtering on `b`. I think you could just modify the existing test case to disable that rule, using `opt expect-not=ReplaceScalarMinMaxWithLimit disable=PushAggFilterIntoScalarGroupBy`. Then you can remove the new test case and put back the original comment. 

Sorry for the back and forth, and thanks for helping improve our test cases!
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1133 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOe0CHDEq6o7kZEKkV:-Mkbltob-yeJKuIKHP14:b8pei5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/testdata/rules/groupby#L1133)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I think it's because there is an implicit NOT NULL constraint on the primary key columns.  The scan of nullable index column 'y' needs to skip over nulls, but the scan of non-null primary key column 'x' does not.
</blockquote></details>

Yes, that's right.


<!-- Sent from Reviewable.io -->

2021-09-27 16:06 UTC, mgartner reviewed
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1239 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkbyESpEtd2WzblDwXi:-MkbyESpEtd2WzblDwXj:b-4cval) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/xform/testdata/rules/groupby#L1239)):*
> ```
> 
> # ReplaceScalarMinMaxWithScalarSubqueries cannot be applied on MIN/MAX
> # expressions which are not a simple variable expression
> ```

nit: end comment with period.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1241 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkbxgbMDJWyEXBkWY2Z:-MkbxgbMDJWyEXBkWY2_:b6bm4wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/xform/testdata/rules/groupby#L1241)):*
> ```
> # expressions which are not a simple variable expression
> opt expect-not=ReplaceScalarMinMaxWithScalarSubqueries
> SELECT min(y+1), max(x+1) FROM xyz
> ```

This is not testing the check you added for `if _, ok := agg.Agg.Child(0).(*memo.VariableExpr); !ok {`. The rule doesn't fire in this case because the project between the scalar-group-by and scan makes the rule's pattern not match. In this case, the children of min and max are variables `column6` and `column8`.

I think this is a fine test to add, just wanted to point this out. I'm not aware of a way that we can test that new variable check. As far as I know, it is only possible for the child of a min/max aggregate to be a variable. 


<!-- Sent from Reviewable.io -->

2021-09-27 16:08 UTC, mgartner commented
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1133 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkOe0CHDEq6o7kZEKkV:-Mkc-qN86huCh37nmXMD:bfketrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab676853ebc48a05955978352e00aa7818943a6/pkg/sql/opt/xform/testdata/rules/groupby#L1133)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yes, that's right.
</blockquote></details>

Ahh makes sense!


<!-- Sent from Reviewable.io -->

2021-09-27 23:00 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 808 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkbgbV88_ZbS8qrZGdr:-Mkcpu5y44FIzqPXuSxO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L808)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: this comment would be a bit cryptic for someone not aware of what this is testing. I'd just say "we don't yet support the optimization to convert multiple aggregates to subqueries with limit 1 when there is a filter"
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHg2GE29i78XaW7pIk:-MkcqqhN5w4Y2cIbPGcz:bl0pnfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/groupby_funcs.go#L93)):*
> aggs[i].Col
OK, I misunderstood your original comment.  I've made the suggested modification.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 103 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-Mkbiz2276PjfmYIvu1y:-MkcrEVSBBoFBaa8Ic_i:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/xform/groupby_funcs.go#L103)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: blank line not needed here
</blockquote></details>

Removed.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 613 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkHlLbVAseys8GeogQ9:-MkdN6c44FtDD0qLe4gO:btp84n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f853a630d638646f098c951b42bd6dcda0992bf9/pkg/sql/opt/xform/testdata/rules/groupby#L613)):*
> PushAggFilterIntoScalarGroupBy
No worries, this is all very instructive.  Made the change.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1239 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkbyESpEtd2WzblDwXi:-MkdNYYF60oxkD_UEO9y:b94cvxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/xform/testdata/rules/groupby#L1239)):*
> ```
> ReplaceScalarMinMaxWithScalarSubqueries cannot be applied on MIN/MAX
> ```
Done.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1241 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkbxgbMDJWyEXBkWY2Z:-MkdSBeJ6-yRJhykw7d5:b7f9o78) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/xform/testdata/rules/groupby#L1241)):*
> if _, ok := agg.Agg.Child(0).(*memo.VariableExpr);
I see.  I wasn't sure if expressions are always assigned to variables in cockroachdb, that's why I added it.  I guess it's OK to leave in as a sanity check, even if it could never occur.


<!-- Sent from Reviewable.io -->

2021-09-28 13:36 UTC, mgartner commented
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1241 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkbxgbMDJWyEXBkWY2Z:-Mkgaj_6A95hKYrgE2f0:b-bogzfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/xform/testdata/rules/groupby#L1241)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> if _, ok := agg.Agg.Child(0).(*memo.VariableExpr);
I see.  I wasn't sure if expressions are always assigned to variables in cockroachdb, that's why I added it.  I guess it's OK to leave in as a sanity check, even if it could never occur.
</blockquote></details>

I agree. You could leave a note above it if you'd like, something like "The child of a min or max aggregation should always be a variable, but we add a sanity check here anyway".


<!-- Sent from Reviewable.io -->

2021-09-28 14:47 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Awesome work!

I'll wait in case you want to add the comment @mgartner suggested below, and then I'll merge this.

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-:-Mkgrlnm3pms0S1qCjQK:b-pua5sj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)



<!-- Sent from Reviewable.io -->

2021-09-28 15:01 UTC, msirek reviewed
Thanks.  If it's OK, I'd like to add that comment in the filter support branch so I won't have to rebase it again.  Sometimes the rebase gets confused and I have to redo the merges.  

> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-:-Mkgu2bj-LAnwkX6RMBo:b-k9nko2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1241 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkbxgbMDJWyEXBkWY2Z:-Mkgv-hS20fDtTHWRfXv:b-k1q72l) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/xform/testdata/rules/groupby#L1241)):*
> The child of a min or max aggregation should always be a variable, but we add a sanity check here anyway"
OK.  If possible, maybe I could add this comment in the filter support branch, which should be ready soon.


<!-- Sent from Reviewable.io -->

2021-09-28 15:08 UTC, msirek commented
> _[pkg/sql/opt/xform/testdata/rules/groupby, line 1241 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkbxgbMDJWyEXBkWY2Z:-Mkgaj_6A95hKYrgE2f0:b-bogzfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/xform/testdata/rules/groupby#L1241)):_
> 
> Previously, msirek (Mark Sirek) wrote…
> > > if _, ok := agg.Agg.Child(0).(*memo.VariableExpr);
> > > I see.  I wasn't sure if expressions are always assigned to variables in cockroachdb, that's why I added it.  I guess it's OK to leave in as a sanity check, even if it could never occur.
> 
> I agree. You could leave a note above it if you'd like, something like "The child of a min or max aggregation should always be a variable, but we add a sanity check here anyway".

@mgartner OK.  Is it OK to add this in the filter support branch, which should be ready soon?

2021-09-28 20:32 UTC, rytaft approved these changes
That sounds fine to me! Thanks again for your contribution :)

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-:-Mki5t-IBeOEh-XchC0w:bytp5e1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)



<!-- Sent from Reviewable.io -->

2021-09-28 20:34 UTC, rytaft commented
Hmm that's weird that I can't bors this. @mgartner we might need your approval too.

2021-09-28 21:52 UTC, RaduBerinde commented
bors r+

2021-09-28 22:24 UTC, msirek commented
> Hmm that's weird that I can't bors this. @mgartner we might need your approval too.

@rytaft Maybe this is related to github permissions issues I was having.  I received an e-mail from craig[bot] saying:
"🔒 Permission denied

Existing reviewers: [click here to make rytaft a reviewer](https://bors.crdb.io/repositories/56/add-reviewer/rytaft) "

I tried clicking on it, but I got a permission denied message.  Maybe someone who manages the repository needs to help.

2021-09-28 22:34 UTC, msirek commented
@rytaft I guess I'll wait until this is merged to open a pull request for the filter support branch:  msirek/minMaxOptWithFilter
Github seems confused when I try to open a pull request from it:

> "We couldn’t figure out how to compare these references, do they point to valid commits? "

2021-09-28 22:50 UTC, merged

2021-09-29 13:40 UTC, mgartner reviewed
Thanks again for the contribution!

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-:-MklmI9bDMWiO8mmRv8p:b-y6am5j)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1241 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70496#-MkbxgbMDJWyEXBkWY2Z:-Mklm3qv6V5OWWQ-hQm-:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/91e6dfbe45cfec488d3fb5a01bed7c073165c387/pkg/sql/opt/xform/testdata/rules/groupby#L1241)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

@mgartner OK.  Is it OK to add this in the filter support branch, which should be ready soon?
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->