Added nollen@cockroachlabs.com to the AUTHORS file.
cockroachdb/cockroach pull request #70521
Opened 2021-09-21 19:05 UTC by nollenr

Adding "nollen" to the AUTHORS file.

2021-09-21 19:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70521)
<!-- Reviewable:end -->

2021-09-21 19:47 UTC, rickystewart requested changes
Please update your commit message to match the template (You need a `Release note: None`). Also, it looks like your email address isn't set up on your GitHub account.

2021-09-21 22:13 UTC, rickystewart requested changes
You're trying to merge 3 commits, that's way too many for this :) I recommend doing `git rebase -i master` and `squash`ing the last two commits so there's only one. Make sure the new commit has the right commit message.

2021-09-22 14:36 UTC, nollenr commented
Starting over!

2021-09-22 14:36 UTC, closed without merging