roachprod: clean up roachprod ssh keys in aws
cockroachdb/cockroach pull request #70603
Opened 2021-09-22 22:25 UTC by healthy-pod

Many SSH keys created by roachprod are no longer used, and some were created by former employees.

This needed to change to change because it's a security issue that former employees may exploit.

This patch adds another step to roachprod-gc cronjob to tag any untagged keys created by roachprod in AWS and delete them if they are unused.

Release note: None

2021-09-22 22:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70603)
<!-- Reviewable:end -->

2021-09-24 15:39 UTC, rail requested changes
A few suggestions:

* Can you use `dryrun` so it's easier to test.
* Can you add logging, esp to the destructive operations.
* I wonder if we should pass around a client instance instead of creating it in each function. This way it'd be easier to unit test.
* Would be great to have some unit tests! :)
* Instead of returning errors, would be great to "wrap" them so it's easier to find the offender. You can use https://github.com/cockroachdb/errors/#Error-composition-summary - I believe we already use it in roachprod.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-:-MkK6mFe6Us1NiLDDt-q:b5fp6ie)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod and @jlinder)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkIyxZt1FKEx3NGU00B):*
to change to change -> to change ;)
___
*[pkg/cmd/roachprod/main.go, line 926 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkIzb5uBhKsOmUsi6_P:-MkIzb5uBhKsOmUsi6_Q:bsq519o) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/main.go#L926)):*
> ```Go
> var gcCmd = &cobra.Command{
> 	Use:   "gc",
> 	Short: "GC expired clusters\n",
> ```

Can you update `Short` and `Long` to reflect the changes.
___
*[pkg/cmd/roachprod/main.go, line 940 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkIzyR75x1iQZX1z37z:-MkIzyR75x1iQZX1z38-:b-1s8h4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/main.go#L940)):*
> ```Go
> 		err = cld.GCAWSKeyPairs()
> 		if err != nil {
> 			return err
> ```

Hmm. We probably shouldn't return here, because it'd stop the next step and prevent the cluster garbage collecting phase.
I wonder if we should combine `cld.GCAWSKeyPairs()` and `cld.GCClusters(cloud, dryrun)` errors after both are done. Maybe something like 

```go
err1 := cld.GCAWSKeyPairs()
err2 := cld.GCClusters(cloud, dryrun)
if err1 != nil || err 2 != nil {
  return combineErrorsSomehow(err1, err2) // maybe https://pkg.go.dev/github.com/cockroachdb/errors#CombineErrors?
}
```
___
*[pkg/cmd/roachprod/cloud/BUILD.bazel, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkJ0iwn6Nu2NG0psV2m:-MkJ0iwn6Nu2NG0psV2n:bunvb6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/BUILD.bazel#L8)):*
> ```Starlark
>         "cluster_cloud.go",
>         "gc.go",
>         "gcAWSKeypairs.go",
> ```

Can you rename the file and use lower case letters please. It's just safer to not mix cases.
___
*[pkg/cmd/roachprod/cloud/gcAWSKeypairs.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkJ1VDUCfPXgygFOnGL:-MkJ1VDUCfPXgygFOnGM:b-8t662x) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/gcAWSKeypairs.go#L15)):*
> ```Go
> import (
> 	"context"
> 	// "fmt"
> ```

My internal linter screams that we should remove the commented import. :)
___
*[pkg/cmd/roachprod/cloud/gcAWSKeypairs.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkJ22_w2k3DmqCcNF_r:-MkJ22_w2k3DmqCcNF_s:b-ifbd18) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/gcAWSKeypairs.go#L44)):*
> ```Go
> 
> func getIAMUsers() ([]iamtypes.User, error) {
> 	IAMClient, err := getIAMClient("")
> ```

Can you add comments why you pass an empty string instead of a region name here?
___
*[pkg/cmd/roachprod/cloud/gcAWSKeypairs.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkJ2Mfl0XkJd3VdXTtI:-MkJ2Mfl0XkJd3VdXTtJ:bsfs4ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/gcAWSKeypairs.go#L49)):*
> ```Go
> 	}
> 	// MaxItems (ie: max returned users) default value is less than the number of users we have.
> 	maxitems := int32(1000)
> ```

What happens when we hit the 1k limit? Maybe use pagination instead and retrieve the user list in batches? I'm not familiar with this API, but there must be something in the response that would tell you that there is something left to retrieve.
___
*[pkg/cmd/roachprod/cloud/gcAWSKeypairs.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkJ42PK7W-oNVC1fVsp:-MkJ42PK7W-oNVC1fVsq:b-x4ru2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/gcAWSKeypairs.go#L63)):*
> ```Go
> 		return nil, err
> 	}
> 	userHasAccessKey := make(map[string]bool)
> ```

The `userHasAccessKey` name is a bit confusing IMO. Maybe `usersWithActiveAccessKey`?
___
*[pkg/cmd/roachprod/cloud/gcAWSKeypairs.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkJ3G4T3MAOoYbJpVh6:-MkJ3G4T3MAOoYbJpVh7:b-hak9x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/gcAWSKeypairs.go#L66)):*
> ```Go
> 	for _, user := range users {
> 		input := iam.ListAccessKeysInput{UserName: user.UserName}
> 		resp, err := IAMClient.ListAccessKeys(context.TODO(), &input)
> ```

Can `IAMClient.ListAccessKeys()` limit the amount of keys it returns, so we may end up with not all keys? In other words, does it support pagination?
___
*[pkg/cmd/roachprod/cloud/gcAWSKeypairs.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkJ4oLCCMqnj0UDK7cf:-MkJ4oLCCMqnj0UDK7cg:bslrlte) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/gcAWSKeypairs.go#L86)):*
> ```Go
> 		return nil, err
> 	}
> 	userHasConsoleAccess := make(map[string]bool)
> ```

Something similar here. Maybe `usersWithConsoleAccess`?
___
*[pkg/cmd/roachprod/cloud/gcAWSKeypairs.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkK4EPjDvvtwZrvvh7C:-MkK4EPjDvvtwZrvvh7D:b-rz1thr) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/gcAWSKeypairs.go#L136)):*
> ```Go
> }
> 
> func getTagsValues(tags []ec2types.Tag) (string, string) {
> ```

This is a pure function, can you add tests for it please.
___
*[pkg/cmd/roachprod/cloud/gcAWSKeypairs.go, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkNNlUL-YRIVpfzuOag:-MkNNlUL-YRIVpfzuOah:b-rz1thr) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/gcAWSKeypairs.go#L152)):*
> ```Go
> // Expected keypair name format: ${IAMUserName}-${PublicKeyHash}
> // ${PublicKeyHash} will always be 28 characters (SHA1 hash encoded into base64).
> func getIAMUserNameFromKeyname(keyName string) string {
> ```

This is a pure function, can you add tests for it please.
___
*[pkg/cmd/roachprod/cloud/gcAWSKeypairs.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkN7eTu-1DG0BxKh9SJ:-MkN7eTu-1DG0BxKh9SK:b-837rzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/gcAWSKeypairs.go#L253)):*
> ```Go
> 				continue
> 			}
> 			CreatedAt, err := tagKeyPair(*region.RegionName, keyPair, IAMUserName, timestamp)
> ```

Any reason to have `CreatedAt` capitalized? I don't think you export it.
___
*[pkg/cmd/roachprod/cloud/gcAWSKeypairs.go, line 258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-MkK53VuEovjR_MLSNPV:-MkK53VuEovjR_MLSNPW:ba37bw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/14ee944f38e5697036d475480125501d92f2989e/pkg/cmd/roachprod/cloud/gcAWSKeypairs.go#L258)):*
> ```Go
> 			}
> 
> 			if IAMUserName == "teamcity-runner" {
> ```

Can you add comments, why we  [...]

2021-09-28 17:55 UTC, healthy-pod commented
@rail 
> I think we may have a (rare) race condition here. Let's say someone asks to replace their MFA. In order to do this we delete the existing one and ask the user to enable a new one. If this job runs during that window, we would delete the keys of that particular user.

It is possible to have multiple MFA devices at once, so we can enable the new device then disable the old device. I think I agree though about tagging keys with a "ToDelete" tag then deleting the key after some time. Should deleting the keys tagged with "ToDelete" be part of this run?

2021-09-28 18:33 UTC, rail commented
> @rail
> 
> > I think we may have a (rare) race condition here. Let's say someone asks to replace their MFA. In order to do this we delete the existing one and ask the user to enable a new one. If this job runs during that window, we would delete the keys of that particular user.
> 
> It is possible to have multiple MFA devices at once, so we can enable the new device then disable the old device. I think I agree though about tagging keys with a "ToDelete" tag then deleting the key after some time. Should deleting the keys tagged with "ToDelete" be part of this run?

I'd say, let's see how bad it complicates the code. Sometimes it's worth having clearer code with some caveats, than having something that makes everything complicated. :)

Do you think it would change the logic a lot?

2021-09-28 19:17 UTC, healthy-pod commented
> Do you think it would change the logic a lot?

I think it depends on the deletion logic. For example: if a key is tagged with "ToDelete":"date", should we just it delete x days after "date" and that's it? This however doesn't help for obvious reasons unless there is a condition to untag this keypair in the future after realizing it shouldn't be deleted or a plan to "manually" check keys staged for deletion which is not great? :)

2021-09-29 11:00 UTC, rail reviewed
Woot! This looks great! I have a couple of nits, but they don't change the logic.
Let's try to test this and if everything works as expected, we can merge it! \o/

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-:-MklCJDQ726j9vdEsBOq:b-hg1yf2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @jlinder, and @rail)

___
*[pkg/cmd/roachprod/cloud/cloud_test.go, line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-Mkl5s0F0tZbfqjwrcMn:-Mkl5s0F0tZbfqjwrcMo:biemapc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4e14f7b4bb49f3e744871146790085c9bfcb5ce/pkg/cmd/roachprod/cloud/cloud_test.go#L24)):*
> ```Go
> 	createdAtKey := "CreatedAt"
> 
> 	tcIAMUserNameValue := "user.name"
> ```

IIRC we don't allow dots in cluster names (because of DNS), see https://github.com/cockroachdb/cockroach/blob/ab0c462672cff1e6928aba2dfc3a5429466aea39/pkg/cmd/roachprod/main.go#L211. Probably not a big deal for tests, JFYI.
___
*[pkg/cmd/roachprod/cloud/gc_aws_keypairs.go, line 179 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-Mkl923j1OCLVxXBuioU:-Mkl923j1OCLVxXBuioV:b4gcknf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4e14f7b4bb49f3e744871146790085c9bfcb5ce/pkg/cmd/roachprod/cloud/gc_aws_keypairs.go#L179)):*
> ```Go
> 
> // Tag keypair with IAMUserName and CreatedAt if untagged and return createdAtValue.
> func tagKeyPair(
> ```

Maybe rename this function to `maybeTagKeyPair`? `tagKeyPair` tells me that you tag the key pair no matter what until I read the comments or the code. What do you think?


<!-- Sent from Reviewable.io -->

2021-09-29 14:52 UTC, healthy-pod commented
> tcIAMUserNameValue := "user.name"

> IIRC we don't allow dots in cluster names (because of DNS)

That's true, my IAM username is "ahmad.abedalqader" and I had to name my cluster "ahmadabedalqader-test" (i.e. without the dot). Keypair name doesn't depend on the cluster name though, it checks the caller identity which will be the exact IAM username then appends the public key hash to it.

https://github.com/cockroachdb/cockroach/blob/c1a9c8b8eb699a76319f56663bc4f4d1355bcffa/pkg/cmd/roachprod/vm/aws/keys.go#L82

2021-09-29 17:00 UTC, rail approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Let's test this together before you merge it!
:tada: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70603#-:-MkmUjGA8q-D29PvR5i3:bhtjlec)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rail)



<!-- Sent from Reviewable.io -->

2021-09-29 17:00 UTC, rail commented
Oh, one thing that we need to address is to resolve the vendor conflict. Should be relatively easy :)

2021-10-04 20:32 UTC, rail approved these changes
> Reviewed 6 of 6 files at r5, 6 of 6 files at r6, 1 of 1 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70603)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rail)



<!-- Sent from Reviewable.io -->

2021-10-04 20:43 UTC, healthy-pod commented
bors r=rail

2021-10-05 01:02 UTC, merged