generate-test-suites: don't clear `pkg/BUILD.bazel` on failure
cockroachdb/cockroach pull request #70703
Opened 2021-09-24 17:47 UTC by rickystewart

Avoid using the redirection (`>`) because if the command fails this
results in `pkg/BUILD.bazel` being empty or containing garbage.

Also teach `generate-test-suites` how to say what the error was instead
of just asking the user to repro.

Release note: None

2021-09-24 17:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70703)
<!-- Reviewable:end -->

2021-09-27 13:21 UTC, rail requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70703)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[pkg/cmd/generate-test-suites/main.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70703#-MkbPJXn30Q1hl8W83Jc:-MkbPJXo9lpInD1lzzQH:b-9bqzc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/85eb8dd662d373c4b31ef8e1bab90596c8ad5c89/pkg/cmd/generate-test-suites/main.go#L27)):*
> ```Go
> 	if err != nil {
> 		log.Printf("Could not query Bazel tests: got error %v", err)
> 		if cmderr, ok := err.(*exec.ExitError); ok {
> ```

The linter wants to use some alternatives:
```
=== RUN   TestLint/TestRoachVet
lint_test.go:109:
pkg/cmd/generate-test-suites/main.go:27:24: invalid direct cast on error object
Alternatives:
if _, ok := err.(*T); ok        ->   if errors.HasType(err, (*T)(nil))
if _, ok := err.(I); ok         ->   if errors.HasInterface(err, (*I)(nil))
if myErr, ok := err.(*T); ok    ->   if myErr := (*T)(nil); errors.As(err, &myErr)
if myErr, ok := err.(I); ok     ->   if myErr := (I)(nil); errors.As(err, &myErr)
switch err.(type) { case *T:... ->   switch { case errors.HasType(err, (*T)(nil)): ...
--- FAIL: TestLint/TestRoachVet (257.02s)
```


<!-- Sent from Reviewable.io -->

2021-09-27 15:19 UTC, rail approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70703#-:-MkbpnfkClc6dKthoMpR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2021-09-27 16:09 UTC, rickystewart commented
bors r=rail

2021-09-27 18:04 UTC, merged