server: expect duplicate session cookies on HTTP requests
cockroachdb/cockroach pull request #70792
Opened 2021-09-27 20:58 UTC by dhartunian

Previously, the golang HTTP library was used to retrieve a cookie with
the specific name we use to store our authentication token. This API
method retrieves the *first* matching cookie in the header and ignores
the rest. This can cause issues with requests that contain multiple
matching cookies with the same name (if other applications are
potentially running on the same domain).

This change adjusts the HTTP API we use to retrieve cookies (we now
prefer to call `req.Cookies()` and iterate through the entire list
ourselves, instead of relying on the API to give us the matching cookie
since it only supports returning a single result.

Resolves #70376.

Release note (security update): Authenticated HTTP requests to nodes can
now contain additional cookies with the same name as the one we use
("session"). Duplicates like this are permitted by the HTTP spec and our
code will now attempt to parse all cookies with a matching name before
giving up. This can resolve issues with customers who run other services
on the same domain as their CRDB nodes.

2021-09-27 20:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70792)
<!-- Reviewable:end -->

2021-09-27 21:02 UTC, knz approved these changes
cc @aaron-crl to get another pair of :eyes: from seceng

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-:-Mkd38HL0GDriJ_HA3xU:bl2w170)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[-- commits, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-Mkd3-ZwBQQiSz-mbkBy):*
nit: missing closing parenthesis


<!-- Sent from Reviewable.io -->

2021-09-28 12:28 UTC, aaron-crl commented
I'm going to suggest @catj-cockroach have a look at this one too. If not possible I'll try to circle back this week.

2021-10-01 18:54 UTC, catj-cockroach requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70792)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/server/authentication.go, line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-MkxAQ1D5XWOMOKFlzRn:-MkxAQ1D5XWOMOKFlzRo:bozrkvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2f0c4643ae4e165571708fe67e081f0a8ef971/pkg/server/authentication.go#L602)):*
> ```Go
> 	var err error
> 	for _, c := range cookies {
> 		if c.Name == SessionCookieName {
> ```

Small logic nitpick, rather than `c.Name == SessionCookieName`, could we do:

```golang
if c.Name != SessionCookieName {
    continue
}
```
___
*[pkg/server/authentication.go, line 617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-MkxBBH36SajszpyjW_Y:-MkxBBH36SajszpyjW_Z:b-ep1y3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2f0c4643ae4e165571708fe67e081f0a8ef971/pkg/server/authentication.go#L617)):*
> ```Go
> 		return "", nil, http.ErrNoCookie
> 	}
> 	if err != nil {
> ```

This if statement will only be true if we get an error on the last Session cookie we interact with, so I'd argue this is not really useful to us anymore. If we want to handle the error we should do so in the for-loop (and only break on unexpected weird errors).
___
*[pkg/server/authentication_test.go, line 703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-MkxCC-l2C4MAqcQHJX5:-MkxCC-l2C4MAqcQHJX6:bw43gvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2f0c4643ae4e165571708fe67e081f0a8ef971/pkg/server/authentication_test.go#L703)):*
> ```Go
> 		{"GET", adminPrefix + "users", nil, "session=badcookie"},
> 		{"GET", statusPrefix + "sessions", nil, ""},
> 		{"POST", ts.URLPrefix + "query", tsReqBuffer.Bytes(), ""},
> ```

Could we add a test where we have multiple session cookies for different domains?


<!-- Sent from Reviewable.io -->

2021-10-18 23:36 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70792)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach and @knz)

___
*[-- commits, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-Mkd3-ZwBQQiSz-mbkBy):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: missing closing parenthesis
</blockquote></details>

Done.
___
*[pkg/server/authentication.go, line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-MkxAQ1D5XWOMOKFlzRn:-MmKfk6kCVD6YaxzXFZp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2f0c4643ae4e165571708fe67e081f0a8ef971/pkg/server/authentication.go#L602)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Small logic nitpick, rather than `c.Name == SessionCookieName`, could we do:

```golang
if c.Name != SessionCookieName {
    continue
}
```
</blockquote></details>

Done.
___
*[pkg/server/authentication.go, line 617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-MkxBBH36SajszpyjW_Y:-MmKgK4r36C6SLOe1xvO:b-twbzjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2f0c4643ae4e165571708fe67e081f0a8ef971/pkg/server/authentication.go#L617)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

This if statement will only be true if we get an error on the last Session cookie we interact with, so I'd argue this is not really useful to us anymore. If we want to handle the error we should do so in the for-loop (and only break on unexpected weird errors).
</blockquote></details>

Gotcha. I logged errors and removed this block.
___
*[pkg/server/authentication_test.go, line 703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-MkxCC-l2C4MAqcQHJX5:-MmKihL6B_-NSBLznxN7:b-s8ht68) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2f0c4643ae4e165571708fe67e081f0a8ef971/pkg/server/authentication_test.go#L703)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Could we add a test where we have multiple session cookies for different domains?
</blockquote></details>

I'm not sure I follow here. My understanding is that the browser figures out what cookies to send but once we have them in the header we don't really know if they were for different domains/subdomains from the header alone.


<!-- Sent from Reviewable.io -->

2021-10-19 15:30 UTC, catj-cockroach approved these changes
Looks good to me! :shipit: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-:-MmOA2cf95kV6j7NIYNN:bebera5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/server/authentication_test.go, line 703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70792#-MkxCC-l2C4MAqcQHJX5:-MmO913kCxPtkfD0Uofu:b-3wylar) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2f0c4643ae4e165571708fe67e081f0a8ef971/pkg/server/authentication_test.go#L703)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I'm not sure I follow here. My understanding is that the browser figures out what cookies to send but once we have them in the header we don't really know if they were for different domains/subdomains from the header alone.
</blockquote></details>

Ah, it's been a bit since I read through the HTTP spec so I didn't realize that they wouldn't send the domain tag as well. Ignore me!


<!-- Sent from Reviewable.io -->

2021-10-19 16:43 UTC, merged