dev: implement `dev doctor`, remove `dev` config inference
cockroachdb/cockroach pull request #70802
Opened 2021-09-27 22:13 UTC by rickystewart

For a while `dev` has been automatically inserting
`--config=devdarwinx86_64` in `bazel` calls, but really this is the
sort of thing that makes the most sense for people to put into a
`bazelrc`. Instead of doing it the other way, implement a `dev doctor`
command that checks whether your machine is up-to-snuff, and perform
that check in `dev doctor`. Then the `--config=devdarwinx86_64` can be
removed from every `bazel` invocation.

For macOS we also check whether XCode is installed and provide clear
instructions on how to fix it.

Release note: None

2021-09-27 22:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70802)
<!-- Reviewable:end -->

2021-09-28 13:21 UTC, rail requested changes
Wooooo! So much cleaner and more explicit. Love it! Just a nit to address and make the linter happy :)

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70802#-:-MkgZ8pn9QqWd45BtnX9:bf1qasj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[pkg/cmd/dev/doctor.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70802#-MkgYEuTEDlF_SXQqnA5:-MkgYEuU4r31kNKPydm9:bd1mlci) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab5fa10c0391e65922b580d8cf5c05fa31dc1d45/pkg/cmd/dev/doctor.go#L73)):*
> ```Go
> 	if success {
> 		log.Println("You are ready to build :)")
> 		return nil
> ```

The linter says
```
pkg/cmd/dev/doctor.go:74:9: if block ends with a return statement, so drop this else and outdent its block
```


<!-- Sent from Reviewable.io -->

2021-09-28 15:26 UTC, rail approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70802#-:-Mkh-qjW5KIK70e0kpwR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2021-09-28 15:28 UTC, rickystewart commented
Made a quick change to remove the now relevant `--skip-dev-config` command-line flag. :) 

bors r=rail

2021-09-28 16:47 UTC, rickystewart commented
bors r-

2021-09-28 16:48 UTC, rickystewart commented
forgot to `dev generate bazel` lmao

bors r=rail

2021-09-28 22:50 UTC, merged