xform: multiple MIN/MAX subqueries rewrite, filter support
cockroachdb/cockroach pull request #70854
Opened 2021-09-29 01:56 UTC by msirek

Fixes https://github.com/cockroachdb/cockroach/issues/70735

Previously, we only rewrite single-table queries with scalar
min and max aggregate expressions into separate subqueries
if there is no WHERE clause, for example:
    select min(pk_col1), max(pk_col1) from t1;
becomes:
    select (select min(pk_col1) from t1),
           (select max(pk_col1) from t1);

... allowing each subquery to utilize a limited scan
    via the primary key.

This was inadequate because it is of limited value.
Many user queries use a WHERE clause, so WHERE clause
support is crucial to allow this optimization to be
applied in more cases.

To address this, this patch adds a new rewrite rule named
ReplaceFilteredScalarMinMaxWithSubqueries to detect a Select
as input to two or more scalar MIN or MAX expressions. If present,
a new Select is built for each MIN or MAX expression with the same
Filters (WHERE clause) as the original Select, but with mapped column
IDs in a copy of the tree. Each new Select is used as input
to a newly constructed subquery and combined via a values clause.
The values clause replaces the original ScalarGroupByExpr.

Release note (performance improvement): A SELECT query from
a single table with both MIN(LeadingIndexColumn) and
MAX(LeadingIndexColumn) and a WHERE clause can now be
performed with two LIMITED SCANs, instead of a single FULL SCAN,
for example:
    create table t1 (a int, b int, primary key(a));
    explain (opt) select min(a), max(a) from t1 where b < 6;
    ---------------------------------------------
      values
       └── tuple
            ├── subquery
            │    └── scalar-group-by
            │         ├── limit
            │         │    ├── select
            │         │    │    ├── scan t1
            │         │    │    └── filters
            │         │    │         └── b < 6
            │         │    └── 1
            │         └── aggregations
            │              └── const-agg
            │                   └── a
            └── subquery
                 └── scalar-group-by
                      ├── limit
                      │    ├── select
                      │    │    ├── scan t1,rev
                      │    │    └── filters
                      │    │         └── b < 6
                      │    └── 1
                      └── aggregations
                           └── const-agg
                                └── a

2021-09-29 01:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70854)
<!-- Reviewable:end -->

2021-09-29 21:51 UTC, rytaft reviewed
Looking good!

nit: in the PR message you can use backticks to format the code nicely (single backticks for inline code elements, or three backticks at the beginning and end for blocks of code). You can just update the PR message directly in GitHub.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-:-MknM-DV5sEw-F3Iw5iY:bluh43r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[pkg/sql/opt/xform/groupby_funcs.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknNTII-SNbsAc1y00f:-MknNTII-SNbsAc1y00g:b-hz515) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/groupby_funcs.go#L57)):*
> ```Go
> 		newScanExpr := c.e.f.ConstructScan(newScanPrivate)
> 
> 		var inputExpr memo.RelExpr
> ```

nit: you could define this earlier (maybe outside the for loop) and then directly assign the output of `ConstructScan` to it.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknNnfvE7QO3dHV0-wd:-MknNnfvE7QO3dHV0-we:b-nc05pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/groupby_funcs.go#L61)):*
> ```Go
> 		// If the input to the scalar group by is a Select with filters, remap the
> 		// column IDs in the filters and use that to build a new Select.
> 		if grp.Child(0).Op() == opt.SelectOp {
> ```

instead of checking that the group is a Select, I would just check that `len(filters) > 0`
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknOHUBAavXL5jhQN5w:-MknOHUBAavXL5jhQN5x:b-arqy3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/rules/groupby.opt#L21)):*
> ```
> 
> # ReplaceFilteredScalarMinMaxWithSubqueries replaces a scalar group by from a
> # SelectExpr having a Filter, a single ScanExpr and n > 1 MIN/MAX expressions
> ```

nit: all `SelectExprs` should have a filter -- I'd just say a "SelectExpr with a ScanExpr as input and...".
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknOzS43CPRp-OGpGJJ:-MknOzS43CPRp-OGpGJK:bjapuxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/testdata/rules/groupby#L1187)):*
> ```
>            └── z:3
> 
> # We expect ReplaceScalarMinMaxWithScalarSubqueries not to be preferred here.
> ```

This comment isn't quite right. `ReplaceScalarMinMaxWithScalarSubqueries` cannot be applied because there is a filter. `ReplaceFilteredScalarMinMaxWithSubqueries` is applied, but the resulting plan is not chosen because the ordering of the scan does not match the aggregation column.  (FYI, `expect-not` means the rule did not generate any new expressions in the memo. `expect` means the rule did generate a new expression in the memo, but it does not necessarily mean the new expression is chosen).

I would just leave the old comment as-is.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknSPnyCo5lQ5FbscKi:-MknSPnyCo5lQ5FbscKj:bfoh9d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/testdata/rules/groupby#L1333)):*
> ```
> 
> # ReplaceFilteredScalarMinMaxWithSubqueries can be applied due to min/max on
> # leading index column.
> ```

nit: the rule will be applied regardless -- the plan is actually chosen because the min/max is on the leading index column. I'd just remove this comment.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknTYD55r99aEEar4iH:-MknTYD55r99aEEar4iI:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/testdata/rules/groupby#L1402)):*
> ```
> 
> # ReplaceFilteredScalarMinMaxWithSubqueries can be applied due to min/max on
> # leading index column.
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-09-30 00:09 UTC, msirek reviewed
Thanks for reviewing!  Added the backticks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-:-MknjWi0DXcIyJ7O77q-:b-n69ryq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/xform/groupby_funcs.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknNTII-SNbsAc1y00f:-Mknk9-f3h63fjJpeVGW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/groupby_funcs.go#L57)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: you could define this earlier (maybe outside the for loop) and then directly assign the output of `ConstructScan` to it.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknNnfvE7QO3dHV0-wd:-MknnlgyAxR2hxgHMTUS:b9armnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/groupby_funcs.go#L61)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

instead of checking that the group is a Select, I would just check that `len(filters) > 0`
</blockquote></details>

Right, I guess this is after the rewrite phase, so the EliminateSelect rule probably wouldn't kick in.  Made the change.
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknOHUBAavXL5jhQN5w:-Mknoqcv6kFXcOLkFqVw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/rules/groupby.opt#L21)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: all `SelectExprs` should have a filter -- I'd just say a "SelectExpr with a ScanExpr as input and...".
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknOzS43CPRp-OGpGJJ:-Mknvwyb5FE9qdWEMzTZ:b-cs1lku) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/testdata/rules/groupby#L1187)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This comment isn't quite right. `ReplaceScalarMinMaxWithScalarSubqueries` cannot be applied because there is a filter. `ReplaceFilteredScalarMinMaxWithSubqueries` is applied, but the resulting plan is not chosen because the ordering of the scan does not match the aggregation column.  (FYI, `expect-not` means the rule did not generate any new expressions in the memo. `expect` means the rule did generate a new expression in the memo, but it does not necessarily mean the new expression is chosen).

I would just leave the old comment as-is.
</blockquote></details>

The old comment was: 'ReplaceScalarMinMaxWithScalarSubqueries can only be applied to canonical
scans', doesn't really describe this case any more.  I cleaned up the comment to describe what's actually going on and moved this test down into the the ReplaceFilteredScalarMinMaxWithSubqueries section.  The new comment is:

# We expect the ReplaceFilteredScalarMinMaxWithSubqueries and
# ReplaceScalarMinMaxWithLimit rules to fire, however, as we know nothing about
# the ordering of y on the index zyx after a scan on xyz with z > 0, a sort is
# required, making the new plan more expensive and therefore not selected.
opt expect=ReplaceFilteredScalarMinMaxWithSubqueries expect=ReplaceScalarMinMaxWithLimit
SELECT min(y), max(x) FROM xyz@zyx WHERE z > 0
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknSPnyCo5lQ5FbscKi:-MknxP442DqLlWS1xppl:b-r99g9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/testdata/rules/groupby#L1333)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: the rule will be applied regardless -- the plan is actually chosen because the min/max is on the leading index column. I'd just remove this comment.
</blockquote></details>

Right, confusing statement.  The leading index column just allows the sort requested in ReplaceScalarMinMaxWithLimit to be avoided. Removed these comments.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknTYD55r99aEEar4iH:-Mknxo4S4nF7hZaPs4Pr:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/testdata/rules/groupby#L1402)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2021-09-30 14:01 UTC, mgartner requested changes
Great work!

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-:-Mkr-d2LCf7q9qH6qsdR:b-9dwnzc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkquOH63rs2pUykv2Xm):*
nit: rewrite => rewrote
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkquSat8xrprzK7aHh3):*
nit: is => was
___
*[-- commits, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkqv7dE8f28G15yXxJv):*
nit: Adding empty lines around your examples here and below would make this easier to read.
___
*[-- commits, line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqucKS4X7_Wsgh2yaS):*
nit: Make this a full sentence like "The purpose of this transformation was to allow each subquery to ...". It's a bit confusing to read this sentence extension after the examples.
___
*[-- commits, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkqvaa0Cy3C7ZO_F1Zv):*
This rule applies in more cases than described here. It applies for two or more min or max aggregates. This release note implies that the rule only works for `min(a), max(b)`, but not `min(a), min(b)`, or `min(a), max(b), min(c)`. Maybe there's a way to make it more clear that these are optimized too?
___
*[-- commits, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqvSNN1jnhaUXiWrPs):*
nit: I'd move this example above the release note. I don't think an example in the release note is necessary.
___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 788 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqwRCr0rOJ6j4lQ9iA:-MkqwRCr0rOJ6j4lQ9iB:bfc2io5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/logictest/testdata/logic_test/aggregate#L788)):*
> ```
> 
> query FI
> SELECT max(z), min(x) FROM xyz having (max(z), min(x)) = (select max(z), min(x) from xyz)
> ```

nit: capitalize keywords `from`, `where`, `select`, `having` in these 3 tests. I think we have a linter that will enforce this, but I'm not sure.
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 909 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqwirC0zckUMjR58s2:-MkqwirC0zckUMjR58s3:b-604mws) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L909)):*
> ```
> # Filter on derived table is supported.
> query T
> EXPLAIN SELECT max(z), min(x) FROM (select x,y,z from xyz a) dt where dt.y > 0
> ```

nit: capitalize keywords
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 957 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqwfpOBTwBn6EyNY05:-MkqwfpOBTwBn6EyNY06:b-604mws) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L957)):*
> ```
> # Scalar subquery in filter is supported.
> query T
> EXPLAIN SELECT max(z), min(x) FROM xyz where (z,x) = (select max(z), min(x) from xyz)
> ```

nit: capitalize keywords
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknNnfvE7QO3dHV0-wd:-Mkqz3zNE7Ry7Nld6XMi:bcndup7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/groupby_funcs.go#L61)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Right, I guess this is after the rewrite phase, so the EliminateSelect rule probably wouldn't kick in.  Made the change.
</blockquote></details>

`EliminateSelect` should still kick in when you call `c.e.f.ConstructSelect`. If you look at the internals of that function you'll see the generated code for `EliminateSelect`. But you'll still want the `if len(filters) > 0 {` check because `MapFilterCols` will probably panic with `nil` filters. I think @rytaft's suggestion was for the sake of simplicity.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqzmJeEIXNCGrt4Fjy:-MkqzmJeEIXNCGrt4Fjz:b-l8hctr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/xform/groupby_funcs.go#L133)):*
> ```Go
> 		case opt.MinOp, opt.MaxOp:
> 			// The child of a min or max aggregation should always be a variable, but
> 			// we add a sanity check here anyway.
> ```

:+1: Thanks for adding this!
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1378 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkr-L61AekN4wWkU4u4:-Mkr-L61AekN4wWkU4u5:b-vve2as) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/xform/testdata/rules/groupby#L1378)):*
> ```
> 
> opt expect=ReplaceFilteredScalarMinMaxWithSubqueries
> SELECT max(z), min(x) FROM xyz WHERE y is not null
> ```

nit: capitalize `IS NOT NULL`
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkr-OMD5KAvZO0__xXw:-Mkr-OME-tQD7lvy6wct:b-vve2as) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/xform/testdata/rules/groupby#L1447)):*
> ```
> # expressions which are projections.
> opt expect-not=ReplaceFilteredScalarMinMaxWithSubqueries
> SELECT max(z+1), min(x) FROM xyz WHERE y is not null
> ```

nit: capitalize `IS NOT NULL`
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkr-PbB6g2AZZZ4kxrz:-Mkr-PbB6g2AZZZ4kxs-:bircau3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/xform/testdata/rules/groupby#L1480)):*
> ```
> # ORDER BY should not disable ReplaceFilteredScalarMinMaxWithSubqueries.
> opt expect=ReplaceFilteredScalarMinMaxWithSubqueries
> SELECT max(z), min(x) FROM xyz WHERE y is not null order by 1
> ```

nit: capitalize `IS NOT NULL ORDER BY`
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkr-Ud50dym-eJJpYcQ:-Mkr-Ud50dym-eJJpYcR:b-n43nud) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/xform/testdata/rules/groupby#L1550)):*
> ```
> # the ordering of y on the index zyx after a scan on xyz with z > 0, a sort is
> # required, making the new plan more expensive and therefore not selected.
> opt expect=ReplaceFilteredScalarMinMaxWithSubqueries expect=ReplaceScalarMinMaxWithLimit
> ```

To expect multipled rules, use `expect=(FirstRule,SecondRule)` rather than two `expect`s.


<!-- Sent from Reviewable.io -->

2021-09-30 16:55 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once you address comments from @mgartner. Nice work!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-:-MkrcI4HCiN_t0KvTEmJ:b3wosne)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)



<!-- Sent from Reviewable.io -->

2021-09-30 19:45 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70854)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkquOH63rs2pUykv2Xm):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: rewrite => rewrote
</blockquote></details>

Done.
___
*[-- commits, line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkquSat8xrprzK7aHh3):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: is => was
</blockquote></details>

Done.
___
*[-- commits, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkqv7dE8f28G15yXxJv):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Adding empty lines around your examples here and below would make this easier to read.
</blockquote></details>

Done.
___
*[-- commits, line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqucKS4X7_Wsgh2yaS):*
> The purpose of this transformation was to allow each subquery to
Done.
___
*[-- commits, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkqvaa0Cy3C7ZO_F1Zv):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This rule applies in more cases than described here. It applies for two or more min or max aggregates. This release note implies that the rule only works for `min(a), max(b)`, but not `min(a), min(b)`, or `min(a), max(b), min(c)`. Maybe there's a way to make it more clear that these are optimized too?
</blockquote></details>

OK, changed it to the following.  What do you think?

Release note (performance improvement): A SELECT query from
a single table with more than one MIN or MAX scalar aggregate
expression and a WHERE clause can now be performed with LIMITED SCANs,
one per aggregate expression, instead of a single FULL SCAN.

Note: No other aggregate function, such as SUM, may be present
      in the query block in order for it to be eligible for
      this transformation. This optimization should occur when
      each MIN or MAX expression involves a leading index column,
      so that a sort is not required for the limit operation, and
      the resulting query plan will appear cheapest to the optimizer.
___
*[-- commits, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqvSNN1jnhaUXiWrPs):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I'd move this example above the release note. I don't think an example in the release note is necessary.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 788 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqwRCr0rOJ6j4lQ9iA:-MksASAq7ydBQxnP8a2d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/logictest/testdata/logic_test/aggregate#L788)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: capitalize keywords `from`, `where`, `select`, `having` in these 3 tests. I think we have a linter that will enforce this, but I'm not sure.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 909 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqwirC0zckUMjR58s2:-MksA_H92c2dK0yCBsUa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L909)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: capitalize keywords
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 957 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqwfpOBTwBn6EyNY05:-MksAlws5vMKZKbpwq1z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L957)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: capitalize keywords
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MknNnfvE7QO3dHV0-wd:-Mks444sEbcw3ldRTZXA:brujztc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e23bdb3983f1bee80fc3e60d9959e979a00bba9/pkg/sql/opt/xform/groupby_funcs.go#L61)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`EliminateSelect` should still kick in when you call `c.e.f.ConstructSelect`. If you look at the internals of that function you'll see the generated code for `EliminateSelect`. But you'll still want the `if len(filters) > 0 {` check because `MapFilterCols` will probably panic with `nil` filters. I think @rytaft's suggestion was for the sake of simplicity.
</blockquote></details>

OK, thanks.
___
*[pkg/sql/opt/xform/groupby_funcs.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-MkqzmJeEIXNCGrt4Fjy:-MksB1Ax4l8iZIjf11IB:bb74ce2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/xform/groupby_funcs.go#L133)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

:+1: Thanks for adding this!
</blockquote></details>

Sure
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1378 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkr-L61AekN4wWkU4u4:-MksBAsB9FIOJ3zLYkdY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/xform/testdata/rules/groupby#L1378)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: capitalize `IS NOT NULL`
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkr-OMD5KAvZO0__xXw:-MksBeNJ2mGDPcWywfJw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/xform/testdata/rules/groupby#L1447)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: capitalize `IS NOT NULL`
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkr-PbB6g2AZZZ4kxrz:-MksBhuT8znj4K0Ukbda:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/xform/testdata/rules/groupby#L1480)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: capitalize `IS NOT NULL ORDER BY`
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 1550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkr-Ud50dym-eJJpYcQ:-Mks4Y2J6HcvzmWE_ApA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b64bfb8a0dfdbcbada95bd56cb91c4d4b17fc2/pkg/sql/opt/xform/testdata/rules/groupby#L1550)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

To expect multipled rules, use `expect=(FirstRule,SecondRule)` rather than two `expect`s.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-30 19:46 UTC, msirek reviewed
Thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-:-MksESGI-CZ5AVP0PLly:b-zcjvte)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)



<!-- Sent from Reviewable.io -->

2021-09-30 20:26 UTC, mgartner approved these changes
Great work! Thanks again.
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-:-MksNjbf4nDuSVXy1xEY:b-xwp2vt)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[-- commits, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70854#-Mkqvaa0Cy3C7ZO_F1Zv):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, changed it to the following.  What do you think?

Release note (performance improvement): A SELECT query from
a single table with more than one MIN or MAX scalar aggregate
expression and a WHERE clause can now be performed with LIMITED SCANs,
one per aggregate expression, instead of a single FULL SCAN.

Note: No other aggregate function, such as SUM, may be present
      in the query block in order for it to be eligible for
      this transformation. This optimization should occur when
      each MIN or MAX expression involves a leading index column,
      so that a sort is not required for the limit operation, and
      the resulting query plan will appear cheapest to the optimizer.

</blockquote></details>

Looks great!


<!-- Sent from Reviewable.io -->

2021-09-30 20:26 UTC, mgartner commented
bors r+

2021-09-30 21:28 UTC, merged