sql: implement information_schema.{_pg_numeric_precision,_pg_numeric_precision_radix,_pg_numeric_scale}
cockroachdb/cockroach pull request #70881
Opened 2021-09-29 20:39 UTC by e-mbrown

This commit adds implementation for the `information_schema._pg_numeric_precision`, `information_schema._pg_numeric_precision_radix` and `information_schema._pg_numeric_scale` builtin functions. 

These functions return the precision, and scale of an exact numeric type as well as the base the precision and scale are in.

Release note (sql change): The `information_schema._pg_numeric_precision`, `information_schema._pg_numeric_precision_radix` and `information_schema._pg_numeric_scale` builtin functions are nowsupported, which improves compatability with PostgreSQL.

2021-09-29 20:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70881)
<!-- Reviewable:end -->

2021-09-30 19:50 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MksEGdw4ndn_Czp36w1:-MksEGdxBcrGbj8S6LY3:b-4jnzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6447103b0b74bb1158cea60a0f8332459b8bf878/pkg/sql/sem/builtins/pg_builtins.go#L2280)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Int),
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				typid := oid.Oid(args[0].(*tree.DOid).DInt)
> ```

nit: change this to `oid.Oid(tree.MustBeDOid(args[0]).DInt)`
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MksEVbGAi6nO0ZYsyOU:-MksEVbGAi6nO0ZYsyOV:b-sf5urz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6447103b0b74bb1158cea60a0f8332459b8bf878/pkg/sql/sem/builtins/pg_builtins.go#L2281)):*
> ```Go
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				typid := oid.Oid(args[0].(*tree.DOid).DInt)
> 				typmod := *args[1].(*tree.DInt)
> ```

nit: change to `tree.MustBeDInt(args[1])
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MksEdNS1H2XxMiwCLmV:-MksEdNS1H2XxMiwCLmW:bcy5lld) ([raw file](https://github.com/cockroachdb/cockroach/blob/6447103b0b74bb1158cea60a0f8332459b8bf878/pkg/sql/sem/builtins/pg_builtins.go#L2293)):*
> ```Go
> 						return tree.DNull, nil
> 					} else {
> 						//ELSE (($2 - 4) >> 16) & 65535
> ```

nit: remove the commented code, and instead mention that this logic matches the postgres implementation of how to calculate the precision based on the typmod, and link to https://github.com/postgres/postgres/blob/d84ffffe582b8e036a14c6bc2378df29167f3a00/src/backend/catalog/information_schema.sql#L109
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MksF-EP5Cb5r9ouPGlZ:-MksF-EP5Cb5r9ouPGl_:b-quqfn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6447103b0b74bb1158cea60a0f8332459b8bf878/pkg/sql/sem/builtins/pg_builtins.go#L2317)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Int),
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				typid := oid.Oid(args[0].(*tree.DOid).DInt)
> ```

nit: use `tree.MustBeDOid`
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MksFI-SDTRweAeBnr-n:-MksFI-SDTRweAeBnr-o:bs15c35) ([raw file](https://github.com/cockroachdb/cockroach/blob/6447103b0b74bb1158cea60a0f8332459b8bf878/pkg/sql/sem/builtins/pg_builtins.go#L2340)):*
> ```Go
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				typid := oid.Oid(args[0].(*tree.DOid).DInt)
> 				typmod := *args[1].(*tree.DInt)
> ```

nit: use `MustBeDoid` and `MustBeDInt`
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MksFPFU3CKR5aoyGLpj:-MksFPFU3CKR5aoyGLpk:b-ag476e) ([raw file](https://github.com/cockroachdb/cockroach/blob/6447103b0b74bb1158cea60a0f8332459b8bf878/pkg/sql/sem/builtins/pg_builtins.go#L2347)):*
> ```Go
> 						return tree.DNull, nil
> 					} else {
> 						return tree.NewDInt((typmod - 4) & 65535), nil
> ```

nit: add a comment and a link to the postgres implementation


<!-- Sent from Reviewable.io -->

2021-10-01 15:49 UTC, rafiss requested changes

2021-10-01 15:49 UTC, rafiss commented on pkg/sql/logictest/testdata/logic_test/pg_builtins
> +WHERE a.attrelid = 'numeric'::regclass
nit: could you add `ORDER by a.attname` at the end, so that it has a guaranteed order?

2021-10-01 15:49 UTC, rafiss commented on pkg/sql/logictest/testdata/logic_test/pg_builtins
> +j      numeric  8   10  4
hm, when i try in postgres, i and j looks different for `_pg_numeric_precision`:

```
| i         | numeric   | 12                      | 10                            | 2                   |
| j         | numeric   | 4                       | 10                            | 4                   |
```

I think it comes down to the parentheses: `((typmod - 4>>16) & 65535)` versus `(((typmod - 4) >> 16) & 65535)`

note how postgres has those extra parens: https://github.com/postgres/postgres/blob/d84ffffe582b8e036a14c6bc2378df29167f3a00/src/backend/catalog/information_schema.sql#L122

2021-10-01 19:53 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2272 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxOyan-ACA4iXutHXj:-MkxOyaoE8l7asherfjj:bt97flx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2272)):*
> ```Go
> 	),
> 
> 	"information_schema._pg_numeric_precision": makeBuiltin(defProps(),
> ```

nit: instead of `defProps` use `tree.FunctionProperties{Category: categorySystemInfo},`
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxPWG36gibmWVgCxEz:-MkxPWG44mX2hbcn8dOr:be2mbfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2296)):*
> ```Go
> 						return tree.NewDInt(((typmod - 4) >> 16) & 65535), nil
> 					} else {
> 						return tree.DNull, nil
> ```

nit: remove the else. stylistically, if the `if` block returns, then there's no need for else. this shows up in the style linter too

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3527406?expandedTest=build%3A%28id%3A3527396%29%2Cid%3A4940
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxP_4aCI05H_Pk4P-J:-MkxP_4aCI05H_Pk4P-K:bjq28l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2305)):*
> ```Go
> 				return tree.DNull, nil
> 			},
> 			Info:       notUsableInfo,
> ```

instead of `notUsable` this can say "Returns the precision of the given type with type modifier."
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2310 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxP2un3O_IbUyiPfyo:-MkxP2un3O_IbUyiPfyp:bt97flx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2310)):*
> ```Go
> 	),
> 
> 	"information_schema._pg_numeric_precision_radix": makeBuiltin(defProps(),
> ```

nit: instead of `defProps` use `tree.FunctionProperties{Category: categorySystemInfo},`
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxPiUsANTmjunxN3Z2:-MkxPiUsANTmjunxN3Z3:b-cu0w22) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2327)):*
> ```Go
> 				}
> 			},
> 			Info:       notUsableInfo,
> ```

instead of `notUsable` this can say "Returns the radix of the given type with type modifier."
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2332 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxP3co0C43PRZnpSMQ:-MkxP3co0C43PRZnpSMR:bt97flx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2332)):*
> ```Go
> 	),
> 
> 	"information_schema._pg_numeric_scale": makeBuiltin(defProps(),
> ```

nit: instead of `defProps` use `tree.FunctionProperties{Category: categorySystemInfo},`
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxPES0A38Ddj_WGvgA:-MkxPES0A38Ddj_WGvgB:be2mbfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2347)):*
> ```Go
> 					if typmod == -1 {
> 						return tree.DNull, nil
> 					} else {
> ```

nit: remove the else. stylistically, if the `if` block returns, then there's no need for else. this shows up in the style linter too

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3527406?expandedTest=build%3A%28id%3A3527396%29%2Cid%3A4940
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxP7BO2B_acU6c5WOi:-MkxP7BO2B_acU6c5WOj:bzhfug0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2355)):*
> ```Go
> 				}
> 				return tree.DNull, nil
> 			},
> ```

It looks like this is missing `Info` and `Volatility` fields

the info can say "Returns the scale of the given type with type modifier."


<!-- Sent from Reviewable.io -->

2021-10-04 13:47 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/logictest/testdata/logic_test/pg_builtins, line 578 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkwT8NsdjhdV6Mc0YB_-r2-578:-MlAXUJvDsjBgGJk4mQe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40d868b6db1cce9f010a34c7af96c10df9694988/pkg/sql/logictest/testdata/logic_test/pg_builtins#L578)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, when i try in postgres, i and j looks different for `_pg_numeric_precision`:

```
| i         | numeric   | 12                      | 10                            | 2                   |
| j         | numeric   | 4                       | 10                            | 4                   |
```

I think it comes down to the parentheses: `((typmod - 4>>16) & 65535)` versus `(((typmod - 4) >> 16) & 65535)`

note how postgres has those extra parens: https://github.com/postgres/postgres/blob/d84ffffe582b8e036a14c6bc2378df29167f3a00/src/backend/catalog/information_schema.sql#L122
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxP_4aCI05H_Pk4P-J:-MlAXew224nKnZc7gkAA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2305)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of `notUsable` this can say "Returns the precision of the given type with type modifier."
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxPiUsANTmjunxN3Z2:-MlAY4qj-_mjXINWSTM_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2327)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of `notUsable` this can say "Returns the radix of the given type with type modifier."
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70881#-MkxP7BO2B_acU6c5WOi:-MlAYdx_CCs2O5rXtJqo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe8ca0649b8889fd12cf249b2a97885fcd71bb48/pkg/sql/sem/builtins/pg_builtins.go#L2355)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

It looks like this is missing `Info` and `Volatility` fields

the info can say "Returns the scale of the given type with type modifier."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-04 16:38 UTC, rafiss commented
you'll need to re-generate the automatically created docs too (see the error in CI)
```
  diff --git a/docs/generated/sql/functions.md b/docs/generated/sql/functions.md
  index bab2bccc58..a3f6dcd23f 100644
  --- a/docs/generated/sql/functions.md
  +++ b/docs/generated/sql/functions.md

....

  ====================================================
  Some automatically generated code is not up to date.
  Run `make generate` to automatically regenerate these.
  Process exited with code 1
```

you can also just do this with `make buildshort` and then resubmit

2021-10-05 02:34 UTC, rafiss approved these changes
lgtm! nice

2021-10-05 13:56 UTC, e-mbrown commented
bors r=rafiss

2021-10-05 15:51 UTC, merged