sql: make diff tool to fail when no diff and there is an expected diff
cockroachdb/cockroach pull request #70887
Opened 2021-09-29 21:28 UTC by mnovelodou

Previously, diff tool didn't fail when there was an expected diff but
the diff was fixed
This was inadequate because, we need to keep the expected diffs
up-to-date
To address this, this patch enforces to run with --rewrite-diffs to
update expected diffs JSON when needed

Release note: None

2021-09-29 21:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70887)
<!-- Reviewable:end -->

2021-09-30 16:17 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70887)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou and @rafiss)

___
*[pkg/sql/pg_metadata_diff.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70887#-MkrUFfjEk946urEN9EH:-MkrUFfkC8ydW93FF25f:b7da13q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8749ef66373b8581be8fca8c6c2cfa9315a6e87/pkg/sql/pg_metadata_diff.go#L137)):*
> ```Go
> )
> 
> // isDiffOid verifies if there is a datatype mismatch or if the diff is an expected diff
> ```

nit: the function name in the comment should be updated


<!-- Sent from Reviewable.io -->

2021-10-01 22:19 UTC, mnovelodou reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70887)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/pg_metadata_diff.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70887#-MkrUFfjEk946urEN9EH:-Mkxw7Lz9lwIPLt57a4G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8749ef66373b8581be8fca8c6c2cfa9315a6e87/pkg/sql/pg_metadata_diff.go#L137)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the function name in the comment should be updated
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-04 15:16 UTC, rafiss approved these changes
bors r+

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70887#-:-MlAs5pg5Iknjx8Bmxn7:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou)



<!-- Sent from Reviewable.io -->

2021-10-04 16:47 UTC, merged