cluster-ui: hide terminate session / query buttons
cockroachdb/cockroach pull request #70955
Opened 2021-09-30 21:06 UTC by matthewtodd

Temporarily mitigates #70832

Currently, these buttons do not work for tenant clusters, both because
of a redux oversight and because the we still need to build out the
endpoints they would hit in the tenant status server.

Until we can get to that work, let's just turn them off.

Release justification: Category 2: Bug fixes and low-risk updates to new
functionality.

Release note (ui): The terminate session and terminate query buttons
have been temporarily disabled in the cluster ui.

2021-09-30 21:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/70955)
<!-- Reviewable:end -->

2021-09-30 21:12 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70955)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70955#-MksYCnJ0OL_-bC16JDF:-MksYCnJ0OL_-bC16JDG:bgrte9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1091a75b2a4215f51018473e86537461cdc4475/pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx#L144)):*
> ```XML
>     } = this.props;
>     const session = this.props.session?.session;
>     const showActionButtons = !!session && !sessionError && !isTenant;
> ```

this deals with serverless, what about "regular" CC console?


<!-- Sent from Reviewable.io -->

2021-09-30 21:29 UTC, matthewtodd reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70955)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70955#-MksYCnJ0OL_-bC16JDF:-Mksaslh46zZ6kd99rYl:b8gj3mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1091a75b2a4215f51018473e86537461cdc4475/pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx#L144)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this deals with serverless, what about "regular" CC console?
</blockquote></details>

Good catch, fixed!


<!-- Sent from Reviewable.io -->

2021-09-30 21:37 UTC, maryliag requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70955)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70955#-MksYCnJ0OL_-bC16JDF:-MkschmMDfaXftrPQp1W:bxfusi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1091a75b2a4215f51018473e86537461cdc4475/pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx#L144)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Good catch, fixed!
</blockquote></details>

actually, is this part necessary? Since you're hiding the whole column anyway


<!-- Sent from Reviewable.io -->

2021-10-01 13:47 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70955)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70955#-Mkw5x0X9vbIlFXmHzNU:-Mkw5x0Y50xub4W23JHV:b-undoye) ([raw file](https://github.com/cockroachdb/cockroach/blob/5976b9d90262b5e0034e306c5c48dcf8db3ffaa8/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx#L97)):*
> ```XML
> };
> 
> export function makeSessionsColumns(
> ```

this file is hitting several lint errors, make sure to address them


<!-- Sent from Reviewable.io -->

2021-10-01 13:55 UTC, matthewtodd reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70955)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70955#-MksYCnJ0OL_-bC16JDF:-Mkw72AhBXwOSG1kIa0O:b-6scuw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1091a75b2a4215f51018473e86537461cdc4475/pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx#L144)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

actually, is this part necessary? Since you're hiding the whole column anyway
</blockquote></details>

It is necessary here. This is a different view without columns, see [line 167](https://github.com/cockroachdb/cockroach/blob/c7bfb49cb9d5453037fd4bcbea187de463398ba8/pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx#L167).
___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70955#-Mkw5x0X9vbIlFXmHzNU:-Mkw7Xpx8CVlns83-k1m:b7143iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5976b9d90262b5e0034e306c5c48dcf8db3ffaa8/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx#L97)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this file is hitting several lint errors, make sure to address them
</blockquote></details>

Gah, thanks. I had run `yarn lint:fix` earlier but neglected to after making further changes. Thanks for looking through the failures, you saved me some time!


<!-- Sent from Reviewable.io -->

2021-10-01 14:01 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70955#-:-Mkw96h44LKbV6PaivYO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)



<!-- Sent from Reviewable.io -->

2021-10-01 14:02 UTC, matthewtodd reviewed
Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70955#-:-Mkw9OhI4L1nZkp1_DT_:b-9755fn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)



<!-- Sent from Reviewable.io -->

2021-10-01 15:06 UTC, matthewtodd commented
bors r+

2021-10-01 18:46 UTC, matthewtodd commented
bors r+

2021-10-01 19:35 UTC, merged