importccl: allow changes to referencing set or privileges on UDT
cockroachdb/cockroach pull request #71016
Opened 2021-10-01 20:34 UTC by ajwerner

In #69674 we enabled importing of tables which used UDTs. We added the caveat
that these types must not change during the import. In #70987, @ajstorm
uncovered that adding new usages of the type cause an illegal change. This is
a particularly painful limitation as all regional by row tables will use the
enum type of the database. That makes the limitation of import much more
extreme than just precluding renames or modifications of enums or their
members.

To fix this limitation, we permit changes to the referencing set which
occur during the import. We also permit changes to privileges as they
won't impact the correctness of the import.

Relates to #69706
Fixes #70987

Release note (enterprise change): Fixed a limitation of IMPORT for tables
using user-defined types whereby any change to the set of tables or views
which reference the type or any changes to privileges on the type during
the IMPORT would lead to failure. Now new references to the type or GRANT
or REVOKE operations performed while the IMPORT is ongoing will not cause
failure.

2021-10-01 20:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/71016)
<!-- Reviewable:end -->

2021-10-01 20:52 UTC, ajstorm requested changes
This PR made my day :tada:.  Some comments below.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-:-MkxcFkQBmvQMUbbFRGG:b-2d0grd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @ajwerner)

___
*[pkg/ccl/importccl/import_stmt.go, line 2362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-MkxaCh-BF5O85Smods_:-MkxaCh-BF5O85Smodsa:b-mv0f56) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce97ef14c86594683f81738c7b0b5ea1bca16bf0/pkg/ccl/importccl/import_stmt.go#L2362)):*
> ```Go
> 			}
> 			equivalent, err := areEquivalentTypes(typeDesc.TypeDesc(), savedTypeDesc.Desc)
> 			if equivalent || err != nil {
> ```

Nit: Might just be me, but I find this reads better as:

```
if err != nil {
   return err
}
if equivalent {
   return nil
}
```
inferring that `err == nil` when `equivalent == true` takes a bit of reasoning which slows down the reading here.
___
*[pkg/ccl/importccl/import_stmt.go, line 2365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-MkxanCSAwl_2F9fYjm0:-MkxanCSAwl_2F9fYjm1:b-zdjghq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce97ef14c86594683f81738c7b0b5ea1bca16bf0/pkg/ccl/importccl/import_stmt.go#L2365)):*
> ```Go
> 				return err
> 			}
> 			return errors.Newf("type descriptor %d has a different modification time than what"+
> ```

I think this message needs updating to describe that the type has fundamentally changed.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 7295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-MkxbESG1nEYUAKTWytI:-MkxbESG1nEYUAKTWytJ:bxex5ag) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce97ef14c86594683f81738c7b0b5ea1bca16bf0/pkg/ccl/importccl/import_stmt_test.go#L7295)):*
> ```Go
> 			false,
> 		},
> 		{
> ```

Nit: Is it possible to modify `TestImportMultiRegion` to add some concurrency and validate that the scenario which originally flagged this issue is resolved (and stays resolved)?


<!-- Sent from Reviewable.io -->

2021-10-01 22:24 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71016)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @ajstorm)

___
*[pkg/ccl/importccl/import_stmt.go, line 2362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-MkxaCh-BF5O85Smods_:-Mkxnsax1GyxbllbAzaY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce97ef14c86594683f81738c7b0b5ea1bca16bf0/pkg/ccl/importccl/import_stmt.go#L2362)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Might just be me, but I find this reads better as:

```
if err != nil {
   return err
}
if equivalent {
   return nil
}
```
inferring that `err == nil` when `equivalent == true` takes a bit of reasoning which slows down the reading here.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/import_stmt.go, line 2365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-MkxanCSAwl_2F9fYjm0:-MkxnqhY5Pfdz8zaIOjR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce97ef14c86594683f81738c7b0b5ea1bca16bf0/pkg/ccl/importccl/import_stmt.go#L2365)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I think this message needs updating to describe that the type has fundamentally changed.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 7295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-MkxbESG1nEYUAKTWytI:-MkxxGXOAzawbYurmUWX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce97ef14c86594683f81738c7b0b5ea1bca16bf0/pkg/ccl/importccl/import_stmt_test.go#L7295)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Is it possible to modify `TestImportMultiRegion` to add some concurrency and validate that the scenario which originally flagged this issue is resolved (and stays resolved)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-04 13:11 UTC, ajstorm approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-:-MlAQbYK1TmxWYtsY0Xf:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/ccl/importccl/import_stmt.go, line 2365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-MkxanCSAwl_2F9fYjm0:-Ml7vx_zAQZ1EBHHoXS5:b-ex8kd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce97ef14c86594683f81738c7b0b5ea1bca16bf0/pkg/ccl/importccl/import_stmt.go#L2365)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good.  One more think you _might_ want to think of adding here is a hint.  Something like "Retrying the IMPORT operation may succeed if the operation concurrently modifying the descriptor does not reoccur during the retry attempt."

Super nitty comment: I think you might want to add commas before and after "potentially incompatibly".


<!-- Sent from Reviewable.io -->

2021-10-04 13:13 UTC, adityamaru approved these changes

2021-10-04 15:19 UTC, ajstorm commented
Added backport flag to 21.2.  IMO, this is a candidate for 21.2.1, but not a GA blocker.

2021-10-11 12:33 UTC, ajwerner reviewed
Reworked the control flow as an early return would have allowed changes to subsequent types to slip through due to a return rather than a continue. Fortunately the linter caught that. Added a test and changed things around to avoid any need for `continue`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-:-MljKllo1nNho-RdXB9E:b-9k8rsr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm)

___
*[pkg/ccl/importccl/import_stmt.go, line 2365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71016#-MkxanCSAwl_2F9fYjm0:-MljKjHv-UvPwlo76tcC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce97ef14c86594683f81738c7b0b5ea1bca16bf0/pkg/ccl/importccl/import_stmt.go#L2365)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Looks good.  One more think you _might_ want to think of adding here is a hint.  Something like "Retrying the IMPORT operation may succeed if the operation concurrently modifying the descriptor does not reoccur during the retry attempt."

Super nitty comment: I think you might want to add commas before and after "potentially incompatibly".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-12 23:23 UTC, merged