bazel,ui: compress assets generated by bazel build
cockroachdb/cockroach pull request #71111
Opened 2021-10-04 22:00 UTC by rickystewart

Up until now building `cockroach` has resulted in the following warning:

    WARNING: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ui/distccl/BUILD.bazel:4:8: output 'pkg/ui/distccl/assets' of //pkg/ui/distccl:genassets is a directory; dependency checking of directories is unsound

The [Bazel documentation](https://docs.bazel.build/versions/main/be/general.html#general-advice)
has this to say:

> Avoid creating symlinks and directories. Bazel doesn't copy over the
> directory/symlink structure created by genrules and its dependency
> checking of directories is unsound.

So we're getting this error because the
`pkg/ui/{distccl,distoss}:genassets` rules produced an output directory
rather than a discrete set of output files. Since the contents of the
`assets` directories have unpredictable names, we can't fix this by
naming the individual files. However, we can compress the `assets`
directory into a single file and use that instead.

Here we make a helper tool at `pkg/util/targz/gen` that basically just
compresses the `assets` directory into an `assets.tar.gz` (just as `tar`
would, but we don't assume that the user machine has `tar` installed).
We also add a helper library `pkg/util/targz` that exposes the `.tar.gz`
file as an `fs.FS`, which is enough for the downstream consumers of the
`assets`.

Closes #70348.

Release note: None

2021-10-04 22:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/71111)
<!-- Reviewable:end -->

2021-10-05 11:04 UTC, koorosh requested changes
@rickystewart , still have this warning when run `bazel build //pkg/cmd/cockroach` (without UI)
`_empty_assets` dir has nested directory so it might affects behavior.
```
Starting local Bazel server and connecting to it...
INFO: Analyzed target //pkg/cmd/cockroach:cockroach (1178 packages loaded, 27503 targets configured).
INFO: Found 1 target...
WARNING: /cockroach/pkg/ui/distccl/BUILD.bazel:3:8: input 'pkg/ui/distccl/_empty_assets' to //pkg/ui/distccl:genassets is a directory; dependency checking of directories is unsound
```

2021-10-05 17:41 UTC, rickystewart commented
Had to fix a `.gitignore` thing, should be done now.

2021-10-05 17:47 UTC, koorosh approved these changes
LGTM 👍🏽

2021-10-05 22:55 UTC, rickystewart commented
bors r=koorosh

2021-10-06 00:08 UTC, merged