sql: NFC-normalization on double-quoted identifiers
cockroachdb/cockroach pull request #71140
Opened 2021-10-05 15:37 UTC by e-mbrown

Resolves: #55396

There was a lack of NFC-normalization on double-quoted
identifiers. This allowed for ambiguous table/db/column names.
This change adds normalization and prevents this case.

Release note: None

2021-10-05 23:13 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/sql/normalization_test.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlHDDcJD5jzBHaj44fx:-MlHDDcJD5jzBHaj44fy:b-n791zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a3c59f272fd510e8457e97862196fd8090529a/pkg/sql/normalization_test.go#L39)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	defer db.Close()
> ```

nit: you can simplify the new test cluster and pgurl stuff with:
```
	s, db, _ := serverutils.StartServer(t, base.TestServerArgs{Insecure: true})
	defer s.Stopper().Stop(context.Background())
	defer db.Close()
```
___
*[pkg/sql/normalization_test.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlHEVXQEYpkIJ1zBSm7:-MlHEVXQEYpkIJ1zBSm8:b-7a5ncz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a3c59f272fd510e8457e97862196fd8090529a/pkg/sql/normalization_test.go#L41)):*
> ```Go
> 	defer db.Close()
> 
> 	_, err = db.Exec("CREATE TABLE \"" + string("caf\u00E9") + "\" (a INT)")
> ```

nit: use
```
"CREATE TABLE \"caf\u00E9\" (a INT)"
```
___
*[pkg/sql/normalization_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlHEXRfAXPh3u9RAapu:-MlHEXRfAXPh3u9RAapv:bvzx2eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a3c59f272fd510e8457e97862196fd8090529a/pkg/sql/normalization_test.go#L44)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	_, err = db.Exec("CREATE TABLE \"" + string("cafe\u0301") + "\" (a INT)")
> ```

nit: use
```
"CREATE TABLE \"cafe\u0301\" (a INT)"
```
___
*[pkg/sql/normalization_test.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlHgndYC0EQrA7Es0vU:-MlHgndYC0EQrA7Es0vV:brachi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a3c59f272fd510e8457e97862196fd8090529a/pkg/sql/normalization_test.go#L45)):*
> ```Go
> 
> 	_, err = db.Exec("CREATE TABLE \"" + string("cafe\u0301") + "\" (a INT)")
> 	require.Errorf(t, err, "The tables should be considered duplicates when normalized")
> ```

let's also add a check for the error message:
```
require.True(t, strings.Contains(err.Error(), "already exists")
```

actually in addition, let's make the test create in this order:
```
	_, err = db.Exec("CREATE TABLE café (a INT)")
	_, err = db.Exec("CREATE TABLE cafe\u0301 (a INT)")
	_, err = db.Exec("CREATE TABLE caf\u00E9 (a INT)")
	_, err = db.Exec("CREATE TABLE \"caf\u00E9\" (a INT)")
	_, err = db.Exec("CREATE TABLE \"cafe\u0301\" (a INT)")
```

the first one should work, and all the other ones should get the error.
___
*[pkg/sql/normalization_test.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlHgRxg1haIP9tI4sbJ:-MlHgRxh8TkaAFgADo_M:bk3ldbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a3c59f272fd510e8457e97862196fd8090529a/pkg/sql/normalization_test.go#L46)):*
> ```Go
> 	_, err = db.Exec("CREATE TABLE \"" + string("cafe\u0301") + "\" (a INT)")
> 	require.Errorf(t, err, "The tables should be considered duplicates when normalized")
> }
> ```

i think we should add another test here:
```
	var b bool
	err = db.QueryRow("SELECT 'caf\u00E9' = 'cafe\u0301'").Scan(&b)
	require.NoError(t, err)
	require.False(t, b)
```

this will make sure that normal strings are not normalized
___
*[pkg/sql/scanner/scan.go, line 920 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlHi4B8Cz4YDtvEg2A9:-MlHi4B91IuxD0_hNTeX:b-9gzo1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a3c59f272fd510e8457e97862196fd8090529a/pkg/sql/scanner/scan.go#L920)):*
> ```Go
> 	}
> 
> 	lval.SetStr(s.finishString(lexbase.NormalizeBytes(buf)))
> ```

i think this might be normalizing too many inputs -- it will apply to normal strings as well as identifiers. i think we need this kind of logic limited to only be in the identQuote case here https://github.com/cockroachdb/cockroach/blob/f14a123d3fc8aab5921d47dd56eee0f03c7a56a6/pkg/sql/scanner/scan.go#L153 

also i noticed one other existing bug which i think we'll need to fix for this to work. this line should say `if isLower && isASCII`: https://github.com/cockroachdb/cockroach/blob/f14a123d3fc8aab5921d47dd56eee0f03c7a56a6/pkg/sql/scanner/scan.go#L566


<!-- Sent from Reviewable.io -->

2021-10-06 16:56 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/normalization_test.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlHgndYC0EQrA7Es0vU:-MlLVt_p3yfMI6Tu3_dE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a3c59f272fd510e8457e97862196fd8090529a/pkg/sql/normalization_test.go#L45)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

let's also add a check for the error message:
```
require.True(t, strings.Contains(err.Error(), "already exists")
```

actually in addition, let's make the test create in this order:
```
	_, err = db.Exec("CREATE TABLE café (a INT)")
	_, err = db.Exec("CREATE TABLE cafe\u0301 (a INT)")
	_, err = db.Exec("CREATE TABLE caf\u00E9 (a INT)")
	_, err = db.Exec("CREATE TABLE \"caf\u00E9\" (a INT)")
	_, err = db.Exec("CREATE TABLE \"cafe\u0301\" (a INT)")
```

the first one should work, and all the other ones should get the error.
</blockquote></details>

Done.
___
*[pkg/sql/normalization_test.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlHgRxg1haIP9tI4sbJ:-MlLVqXf9l3WdwBIYQmC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a3c59f272fd510e8457e97862196fd8090529a/pkg/sql/normalization_test.go#L46)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we should add another test here:
```
	var b bool
	err = db.QueryRow("SELECT 'caf\u00E9' = 'cafe\u0301'").Scan(&b)
	require.NoError(t, err)
	require.False(t, b)
```

this will make sure that normal strings are not normalized
</blockquote></details>

Done.
___
*[pkg/sql/scanner/scan.go, line 920 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlHi4B8Cz4YDtvEg2A9:-MlLVwKZCO_RcwpomfHd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8a3c59f272fd510e8457e97862196fd8090529a/pkg/sql/scanner/scan.go#L920)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this might be normalizing too many inputs -- it will apply to normal strings as well as identifiers. i think we need this kind of logic limited to only be in the identQuote case here https://github.com/cockroachdb/cockroach/blob/f14a123d3fc8aab5921d47dd56eee0f03c7a56a6/pkg/sql/scanner/scan.go#L153 

also i noticed one other existing bug which i think we'll need to fix for this to work. this line should say `if isLower && isASCII`: https://github.com/cockroachdb/cockroach/blob/f14a123d3fc8aab5921d47dd56eee0f03c7a56a6/pkg/sql/scanner/scan.go#L566
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-06 17:23 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/sql/lexbase/normalize.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlLbpUwELu79Nf_qRoK:-MlLbpUwELu79Nf_qRoL:b2ef8go) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7493d36f99b99ea0c5e7af41a4414cc0f12ec7/pkg/sql/lexbase/normalize.go#L57)):*
> ```Go
> }
> 
> //NormalizeBytes normalizes to lowercase and Unicode Normalization
> ```

nit: this doesn't turn things into lower case. actually, maybe we should add a test for that too by adding to the test so it creates:
- table `"Café"` (with quotes) which should not fail
- table Café (without quotes) which should fail
___
*[pkg/sql/lexbase/normalize.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlLcJlnDJ2yMAP2ZIxt:-MlLcJlnDJ2yMAP2ZIxu:ba0fb0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7493d36f99b99ea0c5e7af41a4414cc0f12ec7/pkg/sql/lexbase/normalize.go#L61)):*
> ```Go
> //identifiers.
> func NormalizeBytes(n []byte) []byte {
> 	return norm.NFC.Bytes(n)
> ```

do you know why we need NFC.bytes here? why not NFC.String, like the function above?


<!-- Sent from Reviewable.io -->

2021-10-06 18:17 UTC, e-mbrown commented
___
*[pkg/sql/lexbase/normalize.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlLcJlnDJ2yMAP2ZIxt:-MlLmOcP7Q-T0LrY4tQt:bwxu61j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7493d36f99b99ea0c5e7af41a4414cc0f12ec7/pkg/sql/lexbase/normalize.go#L61)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do you know why we need NFC.bytes here? why not NFC.String, like the function above?
</blockquote></details>

We use NFC.bytes here because in scanString(scan.go line 829), buf isn't converted into a string until the end of the function using s.finishString.  A lot of the other functions use s.finishString so I thought targeting buf beforehand was a better option


<!-- Sent from Reviewable.io -->

2021-10-06 19:37 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/sql/normalization_test.go, line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlM-P-UBFSOlhkos3ZE:-MlM-P-V0WOEkaiFKHZE:b-r9tehf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99659d8351a6705f6ac2ebf9b5519045ee42758c/pkg/sql/normalization_test.go#L35)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	_, err = db.Exec(`CREATE TABLE "Café" (a INT)`)
> ```

super tiny nit: but could you move the `"Café"` test so it's the last one? that way we can be sure that the `Café` test is conflicting with the table we expect it to
___
*[pkg/sql/lexbase/normalize.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlLcJlnDJ2yMAP2ZIxt:-MlM42vvErExhuRmoDer:b-dsy0la) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7493d36f99b99ea0c5e7af41a4414cc0f12ec7/pkg/sql/lexbase/normalize.go#L61)):*
<details><summary><i>Previously, e-mbrown wrote…</i></summary><blockquote>

We use NFC.bytes here because in scanString(scan.go line 829), buf isn't converted into a string until the end of the function using s.finishString.  A lot of the other functions use s.finishString so I thought targeting buf beforehand was a better option
</blockquote></details>

ah it makes sense. i think we can make it use NFC.String though. that way we can add the optimization from the above function:
```
func NormalizeString(s string) string {
	if isASCII(s) {
		return s
	}
	return norm.NFC.String(s)
```
(we just don't want the convert to lower-case step)

then we change the call from scan.go so it's:
```
lval.SetStr(lexbase.NormalizeString(s.finishString(buf))
```


<!-- Sent from Reviewable.io -->

2021-10-06 20:39 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/normalization_test.go, line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlM-P-UBFSOlhkos3ZE:-MlMJYXE97DUYaOZ29UW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99659d8351a6705f6ac2ebf9b5519045ee42758c/pkg/sql/normalization_test.go#L35)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super tiny nit: but could you move the `"Café"` test so it's the last one? that way we can be sure that the `Café` test is conflicting with the table we expect it to
</blockquote></details>

Done.
___
*[pkg/sql/lexbase/normalize.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlLcJlnDJ2yMAP2ZIxt:-MlMJe6W70yz947LUauC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7493d36f99b99ea0c5e7af41a4414cc0f12ec7/pkg/sql/lexbase/normalize.go#L61)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah it makes sense. i think we can make it use NFC.String though. that way we can add the optimization from the above function:
```
func NormalizeString(s string) string {
	if isASCII(s) {
		return s
	}
	return norm.NFC.String(s)
```
(we just don't want the convert to lower-case step)

then we change the call from scan.go so it's:
```
lval.SetStr(lexbase.NormalizeString(s.finishString(buf))
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-08 21:53 UTC, rafiss commented
the failing test is
```
# Unicode sequences are preserved.

statement ok
CREATE TABLE Amelie("Amélie" INT, "Amélie" INT); INSERT INTO Amelie VALUES (1, 2)
```

The two column names in that test have different unicode representations. @knz it seems that you added the test long ago, but later on you filed https://github.com/cockroachdb/cockroach/issues/55396

Am I correct to conclude that you no longer want that `"Amélie"` test to exist in its current form?

2021-10-11 04:18 UTC, knz commented
> Am I correct to conclude that you no longer want that "Amélie" test to exist in its current form?

I'd say we need to change the text to expect a duplicate column definition (i.e. check that the normalization occurs)

2021-10-11 04:20 UTC, knz reviewed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/sql/lexbase/normalize.go, line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlhZpaG1Ke5L-_htGCT:-MlhZpaG1Ke5L-_htGCU:bbk8lpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c56cefaf2a4267df8095f79cfd962ebb528d820/pkg/sql/lexbase/normalize.go#L57)):*
> ```Go
> }
> 
> //NormalizeString normalizes to Unicode Normalization Form C (NFC).
> ```

nit: 1 space after `//`


<!-- Sent from Reviewable.io -->

2021-10-11 17:04 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @knz, and @rafiss)

___
*[pkg/ccl/logictestccl/testdata/logic_test/case_sensitive_names, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlkIDN2DoGhxilFNtnU:-MlkIDN33VuFmKXLBYnt:b-ld3n3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f50285b0569da41ca7361ac363a489144759ba7/pkg/ccl/logictestccl/testdata/logic_test/case_sensitive_names#L20)):*
> ```
>   PARTITION p1 VALUES IN ((1)),
>   PARTITION "P1" VALUES IN ((2)),
>   PARTITION "Amélie" VALUES IN ((3))
> ```

i don't think we want to change this

but in pkg/sql/logictest/testdata/logic_test/case_sensitive_names we need to change these tests.

```
statement ok
CREATE TABLE Amelie("Amélie" INT, "Amélie" INT); INSERT INTO Amelie VALUES (1, 2)

# Check that the column names were encoded properly
query I
SELECT ordinal_position FROM information_schema.columns WHERE table_name = 'amelie' AND column_name::BYTES = b'Ame\xcc\x81lie'
----
1

query I
SELECT ordinal_position FROM information_schema.columns WHERE table_name = 'amelie' AND column_name::BYTES = b'Am\xc3\xa9lie'
----
2

# Check that the non-normalized names propagate throughout until results.

query II colnames
SELECT "Amélie", "Amélie" FROM Amelie
----
Amélie Amélie
2      1
```

the first one should become:
```
statement error duplicate column name: "Amélie"
CREATE TABLE Amelie("Amélie" INT, "Amélie" INT); INSERT INTO Amelie VALUES (1, 2)
```

and we can remove the other tests.


<!-- Sent from Reviewable.io -->

2021-10-11 17:08 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @knz, and @rafiss)

___
*[pkg/ccl/logictestccl/testdata/logic_test/case_sensitive_names, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71140#-MlkIDN2DoGhxilFNtnU:-MlkJy0lEUQyqljb9qqB:bnb9wb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f50285b0569da41ca7361ac363a489144759ba7/pkg/ccl/logictestccl/testdata/logic_test/case_sensitive_names#L20)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think we want to change this

but in pkg/sql/logictest/testdata/logic_test/case_sensitive_names we need to change these tests.

```
statement ok
CREATE TABLE Amelie("Amélie" INT, "Amélie" INT); INSERT INTO Amelie VALUES (1, 2)

# Check that the column names were encoded properly
query I
SELECT ordinal_position FROM information_schema.columns WHERE table_name = 'amelie' AND column_name::BYTES = b'Ame\xcc\x81lie'
----
1

query I
SELECT ordinal_position FROM information_schema.columns WHERE table_name = 'amelie' AND column_name::BYTES = b'Am\xc3\xa9lie'
----
2

# Check that the non-normalized names propagate throughout until results.

query II colnames
SELECT "Amélie", "Amélie" FROM Amelie
----
Amélie Amélie
2      1
```

the first one should become:
```
statement error duplicate column name: "Amélie"
CREATE TABLE Amelie("Amélie" INT, "Amélie" INT); INSERT INTO Amelie VALUES (1, 2)
```

and we can remove the other tests.
</blockquote></details>

oh my bad, you can keep the change in this file too. didn't see that it was a change in the expected result


<!-- Sent from Reviewable.io -->

2021-10-11 18:33 UTC, rafiss approved these changes
lgtm! feel free to merge once CI passes

2021-10-12 01:35 UTC, merged