ui/cluster-ui: make app name a query search parameter in stmts page
cockroachdb/cockroach pull request #71175
Opened 2021-10-05 20:49 UTC by xinhaoz

Fixes: #70790

Previously, the selected app was derived from a route param on the
statements page. All other filters are derived from query search
parameters on the page. This commit makes the app name a query search
parameter, as is the case in the transactions page.

Release note (ui change): The selected app name on the statements page
is now a query search parameter instead of a route parameter.
E.g., instead of `/statements/movr`, use `/statements?app=movr`

2021-10-05 20:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/71175)
<!-- Reviewable:end -->

2021-10-05 21:14 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[-- commits, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71175#-MlHIIF43i-bZUWZAjbs):*
release notes are used for things the user will notice. Even though this changed ui code, it won't affect the user, so you can leave as release note: none


<!-- Sent from Reviewable.io -->

2021-10-06 14:35 UTC, matthewtodd requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71175)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/app.tsx, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71175#-MlL07by2lFq9TKy7Atc:-MlL07by2lFq9TKy7Atd:bbys47q) ([raw file](https://github.com/cockroachdb/cockroach/blob/739aec3f5df9d979efd16ed261cb90c953f2e338/pkg/ui/workspaces/db-console/src/app.tsx#L193)):*
> ```XML
>                       )}`}
>                     />
>                   )}
> ```

Did you look at collapsing this down? I think this will work, but maybe you ran into a complication I'm not aware of:

```
<Redirect
  exact
  from={`/statements/:${appAttr}`}
  to={`/statements?app=:${appAttr}`}
/>
```


<!-- Sent from Reviewable.io -->

2021-10-07 13:28 UTC, maryliag requested changes
Open Statement Page > Open filter > Select All and click apply (or any other and go back to all)
this will add `app=all` as a parameter, making no statement to show up since none have an app named `all`. This is also making the filter display 1 selection, even though it's the default value
![Screen Shot 2021-10-07 at 9.27.48 AM.png](https://files.reviewableusercontent.io/images/reviewable/1017486/ec1cYprUlBbjPSMFK539bu4m/Screen%20Shot%202021-10-07%20at%209.27.48%20AM.png)
 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71175#-:-MlPvgm-4DYLlbDHda7L:bavvr99)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd and @xinhaoz)



<!-- Sent from Reviewable.io -->

2021-10-07 15:35 UTC, xinhaoz reviewed
Addressed issue above!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71175#-:-MlQO9TGCT73XhNtTpZo:b5sv9y5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[-- commits, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71175#-MlHIIF43i-bZUWZAjbs):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

release notes are used for things the user will notice. Even though this changed ui code, it won't affect the user, so you can leave as release note: none
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-08 15:28 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 7 files at r1, 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71175#-:-MlVWLqk4qP2FDyP307S:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)



<!-- Sent from Reviewable.io -->

2021-10-11 17:18 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71175#-:-MlkMETJ8ms6hvNHe39r:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @xinhaoz)



<!-- Sent from Reviewable.io -->

2021-10-12 01:35 UTC, merged