sql: UserHasAdminRole should return true for the admin role itself
cockroachdb/cockroach pull request #71219
Opened 2021-10-06 16:15 UTC by tukeJonny

This PR makes `planner.UserHasAdminRole` returns true on the `admin` role for improving introspection.

This PR had checked by running `make testbaselogic` .

2021-10-06 16:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/71219)
<!-- Reviewable:end -->

2021-10-06 16:35 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=71219) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=71219) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=71219) it.</sub>

2021-10-06 18:52 UTC, rafiss requested changes
ah, i thought we already had tests in place for this, but we don;t

could you add `admin` to the test case here: https://github.com/cockroachdb/cockroach/blob/d36bb1a71ccb02297ee40de0e372c94329557d4f/pkg/sql/logictest/testdata/logic_test/pg_catalog#L5359

2021-10-07 15:18 UTC, rafiss approved these changes
i see, thanks for that investigation! in that case, this PR looks good! (there are other logictests that look up "admin" in other pg_catalog tables, and those already are correct)

bors r+

2021-10-07 15:45 UTC, tukeJonny commented
Thanks for the great opportunity!

This Issue was just right and a good opportunity to look around and learn more!

2021-10-07 17:00 UTC, merged