sql: remove InternalExecutor from EvalCtx
cockroachdb/cockroach pull request #71246
Opened 2021-10-06 21:04 UTC by RichardJCai

Minor refactor to remove duplicate InternalExecutor definition
on EvalCtx and in the tree package.

We already have 2 interface declarations for InternalExecutor
in sql and sqlutil, this refactor hopefully makes the dependencies
a little more clear.

Resolves https://github.com/cockroachdb/cockroach/issues/60507

2021-10-11 19:45 UTC, RichardJCai commented
Need to do a bit more cleanup but what are the thoughts on using the InternalExecutor on ExecCfg for builtins.

The downside is that we need to specify more overrides to use the InternalExecutor for builtins but I think this is somewhat more clear of an interface.

2021-10-14 17:07 UTC, rafiss requested changes
i like the direction of this. definitely feels like an improvement.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-:-Mlzl8TDAPhsYIjAi_fc:by8ylng)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RichardJCai)

___
*[pkg/sql/backfill.go, line 1882 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-Mlzinbx1mUjCOEzkr5I:-MlzinbyE1Yl_USVGRdQ:b-t33zji) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f0cc22d1b13a72797d5dea9603cfb90b5400a2/pkg/sql/backfill.go#L1882)):*
> ```Go
> 			return ie.WithSyntheticDescriptors([]catalog.Descriptor{desc}, func() error {
> 				cnt, err := ie.QueryRowEx(ctx, "VERIFY INDEX", txn,
> 					sessiondata.NodeUserSessionDataOverride, query)
> ```

do you know when we are supposed to use the node user versus the root user?
___
*[pkg/sql/exec_util.go, line 1176 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-Mlzj9ig4Ot8QzUXCSps:-Mlzj9ig4Ot8QzUXCSpt:b-53bvid) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f0cc22d1b13a72797d5dea9603cfb90b5400a2/pkg/sql/exec_util.go#L1176)):*
> ```Go
> 
> // InternalExecutorFactory is a function that produces a "session
> // bound" internal executor.
> ```

does session bound in this context mean that it should always inherit session variables from the parent session?

thinking of https://github.com/cockroachdb/cockroach/issues/70888

speaking of which, @cucaroach you'd probably want to be aware of this change (at the moment still in draft state)
___
*[pkg/sql/planner.go, line 828 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MlzkCAg2adRAFNgqtbP:-MlzkCAg2adRAFNgqtbQ:b-4w9ydu) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f0cc22d1b13a72797d5dea9603cfb90b5400a2/pkg/sql/planner.go#L828)):*
> ```Go
> 	opName string,
> 	txn *kv.Txn,
> 	session *sessiondata.SessionData,
> ```

nit: name it `sd` maybe?
___
*[pkg/sql/planner.go, line 840 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MlzkG2Z2HfP7Ndc8jaM:-MlzkG2Z2HfP7Ndc8jaN:br6qre1) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f0cc22d1b13a72797d5dea9603cfb90b5400a2/pkg/sql/planner.go#L840)):*
> ```Go
> 	opName string,
> 	txn *kv.Txn,
> 	session *sessiondata.SessionData,
> ```

nit: name it `sd`
___
*[pkg/sql/sem/tree/eval.go, line 3248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MlzkQBN84OFtDPbnyX7:-MlzkQBN84OFtDPbnyX8:b-snzs0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f0cc22d1b13a72797d5dea9603cfb90b5400a2/pkg/sql/sem/tree/eval.go#L3248)):*
> ```Go
> // InternalRows is an iterator interface that's exposed by the internal
> // executor. It provides access to the rows from a query.
> type InternalRows interface {
> ```

hm, is `tree` the right package for `InternalRows`? i wonder if it'd be better to have it in a new package. well then again it makes sense to be in the same package as EvalPlanner. i'm fine to leave it here if there's no better place

anyway, would be worth adding a `var _ InternalRows = rowsIterator{}` assertion somewhere


<!-- Sent from Reviewable.io -->

2021-10-21 20:31 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, and @rafiss)

___
*[pkg/sql/backfill.go, line 1882 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-Mlzinbx1mUjCOEzkr5I:-MmZWS2F-al50KVpVaBp:bgixbb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f0cc22d1b13a72797d5dea9603cfb90b5400a2/pkg/sql/backfill.go#L1882)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do you know when we are supposed to use the node user versus the root user?
</blockquote></details>

I think root should be sufficient but I thought this fit similarly to how the other `NodeUserSessionDataOverrides` were used which is for "system" ops. I think backfill falls under that.
___
*[pkg/sql/exec_util.go, line 1176 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-Mlzj9ig4Ot8QzUXCSps:-MmZLkaJ9ihpEYVOUlRc:b6kvxt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f0cc22d1b13a72797d5dea9603cfb90b5400a2/pkg/sql/exec_util.go#L1176)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does session bound in this context mean that it should always inherit session variables from the parent session?

thinking of https://github.com/cockroachdb/cockroach/issues/70888

speaking of which, @cucaroach you'd probably want to be aware of this change (at the moment still in draft state)
</blockquote></details>

Yeah session data and some txn state should be passed when creating it.
___
*[pkg/sql/sem/tree/eval.go, line 3248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MlzkQBN84OFtDPbnyX7:-MmZWcvI9DUr8tyPnhFW:b-iub2tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/26f0cc22d1b13a72797d5dea9603cfb90b5400a2/pkg/sql/sem/tree/eval.go#L3248)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, is `tree` the right package for `InternalRows`? i wonder if it'd be better to have it in a new package. well then again it makes sense to be in the same package as EvalPlanner. i'm fine to leave it here if there's no better place

anyway, would be worth adding a `var _ InternalRows = rowsIterator{}` assertion somewhere
</blockquote></details>

Added the `var _ InternalRows = rowsIterator{}` 

The deps are pretty messy here, I'd like to make InternalRows standalone but the original one has `colinfo.ResultColumns` which has a dependency on tree and I can't find a nice way to make it work.


<!-- Sent from Reviewable.io -->

2021-11-12 22:46 UTC, rafiss requested changes
just some relatively small comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-:-MoLJxUQ8_25LbrN3FaS:b9cx0jb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, @rafiss, and @RichardJCai)

___
*[pkg/sql/conn_executor.go, line 1500 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLHoiFDLFcN_yEBPJV:-MoLHoiG5JwWChBHtZPz:b-onfqp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/conn_executor.go#L1500)):*
> ```Go
> 	}
> 
> 	if !ex.extraTxnState.keepDescCollectionOnClose {
> ```

should this change be done as a separate PR?
___
*[pkg/sql/internal.go, line 131 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLJAjO-i4KDviJ1y3D:-MoLJAjO-i4KDviJ1y3E:bntziwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/internal.go#L131)):*
> ```Go
> 
> func (ie *InternalExecutor) SetExtraTxnState(extraTxnState ExtraTxnState) {
> 	ie.extraTxnState = extraTxnState
> ```

hm, i wonder if the extraTxnState stuff should be a different PR. I don't feel strongly, if it would be hard to separate into a different change I wouldn't worry much about it.
___
*[pkg/sql/planner.go, line 820 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLInbT1lS4Yv8R97aN:-MoLInbT1lS4Yv8R97aO:b-ffimgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/planner.go#L820)):*
> ```Go
> 
> // QueryRowEx is like QueryRow, but allows the caller to override some session data
> // fields (e.g. the user).
> ```

nit: the comment refers to QueryRow, but that isn't defined on this type
___
*[pkg/sql/resolve_oid.go, line 60 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLJ4L38-BYmhrUQdXy:-MoLJ4L38-BYmhrUQdXz:b-6omxii) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/resolve_oid.go#L60)):*
> ```Go
> 	toResolve tree.Datum,
> 	user security.SQLUsername,
> 	database string,
> ```

why did we need to add these two parameters?
___
*[pkg/sql/sem/tree/eval.go, line 3228 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLJW55Bjay7rKgXGOJ:-MoLJW55Bjay7rKgXGOK:bhc10oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/sem/tree/eval.go#L3228)):*
> ```Go
> 	ExternalWriteFile(ctx context.Context, uri string, content []byte) error
> 
> 	QueryRowEx(
> ```

nit: comment this function and the next
___
*[pkg/sql/sem/tree/eval.go, line 3232 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLJaOpCRnBiJdAFbGv:-MoLJaOpCRnBiJdAFbGw:bm4vox9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/sem/tree/eval.go#L3232)):*
> ```Go
> 		opName string,
> 		txn *kv.Txn,
> 		session *sessiondata.SessionData,
> ```

nit: `sessionData` or `sd` instead of `session`

but does this actually need to be a param? won't the `planner` always have one of these available on it already? so we can just get it from the receiver


<!-- Sent from Reviewable.io -->

2021-11-23 18:39 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, and @rafiss)

___
*[pkg/sql/conn_executor.go, line 1500 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLHoiFDLFcN_yEBPJV:-MpCeDq1-hSWoT4GnE3R:bl6xiqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/conn_executor.go#L1500)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this change be done as a separate PR?
</blockquote></details>

Sure that's reasonable to me, removed for now
___
*[pkg/sql/internal.go, line 131 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLJAjO-i4KDviJ1y3D:-MpCef5W4FdOcq7E4JYP:blqsdl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/internal.go#L131)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, i wonder if the extraTxnState stuff should be a different PR. I don't feel strongly, if it would be hard to separate into a different change I wouldn't worry much about it.
</blockquote></details>

Removing this for now as well for simplicity
___
*[pkg/sql/planner.go, line 820 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLInbT1lS4Yv8R97aN:-MpCfg6s3atYwjagOmfa:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/planner.go#L820)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the comment refers to QueryRow, but that isn't defined on this type
</blockquote></details>

Updated
___
*[pkg/sql/resolve_oid.go, line 60 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLJ4L38-BYmhrUQdXy:-MpCg68v-7IGVg3lOcJM:b-k37gh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/resolve_oid.go#L60)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why did we need to add these two parameters?
</blockquote></details>

Removed, this isn't needed
___
*[pkg/sql/sem/tree/eval.go, line 3232 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MoLJaOpCRnBiJdAFbGv:-MpD0hq86jCkUDu4fki7:bhy27mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a51ea402b2dc8aedfb5f30109fec5977bce24539/pkg/sql/sem/tree/eval.go#L3232)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: `sessionData` or `sd` instead of `session`

but does this actually need to be a param? won't the `planner` always have one of these available on it already? so we can just get it from the receiver
</blockquote></details>

This should actually be `sessiondata.InternalExecutorOverride` 


<!-- Sent from Reviewable.io -->

2021-11-23 23:37 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, @rafiss, and @RichardJCai)

___
*[pkg/sql/backfill.go, line 1566 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE96s13Z5u9xh64UO8:-MpE96s13Z5u9xh64UO9:b-u02v3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/backfill.go#L1566)):*
> ```Go
> 				}
> 				return ie.WithSyntheticDescriptors([]catalog.Descriptor{tableDesc}, func() error {
> 					row, err := ie.QueryRowEx(ctx, "verify-inverted-idx-count", txn, execOverride, stmt)
> ```

does it still need to be `NodeUserSessionDataOverride`?
___
*[pkg/sql/backfill.go, line 1688 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE99wIEz98ELZSr62b:-MpE99wIEz98ELZSr62c:b-u02v3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/backfill.go#L1688)):*
> ```Go
> 				}
> 				return ie.WithSyntheticDescriptors([]catalog.Descriptor{desc}, func() error {
> 					row, err := ie.QueryRowEx(ctx, "verify-idx-count", txn, execOverride, query)
> ```

does it still need to be `NodeUserSessionDataOverride`?
___
*[pkg/sql/backfill.go, line 1787 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE85NwDKY61k4242qV:-MpE85NwDKY61k4242qW:b739oms) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/backfill.go#L1787)):*
> ```
> execOverride
> ```
i thought the plan was to keep this using `NodeUserSessionDataOverride`
___
*[pkg/sql/planner.go, line 824 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE8dsjCvEHj9yGADSQ:-MpE8dsjCvEHj9yGADSR:b1btojf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/planner.go#L824)):*
> ```Go
> 	opName string,
> 	txn *kv.Txn,
> 	session sessiondata.InternalExecutorOverride,
> ```

nit: rename `session` to `override`
___
*[pkg/sql/planner.go, line 842 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE8b9_BQ1zO3Wd1XDY:-MpE8b9_BQ1zO3Wd1XDZ:b1btojf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/planner.go#L842)):*
> ```Go
> 	opName string,
> 	txn *kv.Txn,
> 	session sessiondata.InternalExecutorOverride,
> ```

nit: rename `session` to `override`
___
*[pkg/sql/unsplit.go, line 110 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE8jZd80idhHb-fUSE:-MpE8jZd80idhHb-fUSF:bdqwuhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/unsplit.go#L110)):*
> ```Go
> 	}
> 	it, err := params.p.ExtendedEvalContext().ExecCfg.InternalExecutor.QueryIteratorEx(
> 		params.ctx, "split points query", params.p.txn, sessiondata.NoSessionDataOverride,
> ```

this used to use `root`, but now doesn't have an override. does it still need to be `root` or `node`?
___
*[pkg/sql/faketreeeval/evalctx.go, line 342 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE8q1l1QWSMx_5ITdj:-MpE8q1l1QWSMx_5ITdk:b1btojf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/faketreeeval/evalctx.go#L342)):*
> ```Go
> 	opName string,
> 	txn *kv.Txn,
> 	session sessiondata.InternalExecutorOverride,
> ```

nit: rename `session` to `override`
___
*[pkg/sql/faketreeeval/evalctx.go, line 354 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE8q_9DYzNEOGh1myA:-MpE8q_9DYzNEOGh1myB:b1btojf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/faketreeeval/evalctx.go#L354)):*
> ```Go
> 	opName string,
> 	txn *kv.Txn,
> 	session sessiondata.InternalExecutorOverride,
> ```

nit: rename `session` to `override`
___
*[pkg/sql/sem/tree/eval.go, line 3241 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE9-_xEM5mhPsmNLiB:-MpE9-_xEM5mhPsmNLiC:b1btojf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/sem/tree/eval.go#L3241)):*
> ```Go
> 		opName string,
> 		txn *kv.Txn,
> 		session sessiondata.InternalExecutorOverride,
> ```

nit: rename `session` to `override`
___
*[pkg/sql/sem/tree/eval.go, line 3255 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE90OB0OJKxP642V65:-MpE90OB0OJKxP642V66:b1btojf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/sem/tree/eval.go#L3255)):*
> ```Go
> 		opName string,
> 		txn *kv.Txn,
> 		session sessiondata.InternalExecutorOverride,
> ```

nit: rename `session` to `override`


<!-- Sent from Reviewable.io -->

2021-11-23 23:39 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, @rafiss, and @RichardJCai)

___
*[pkg/sql/backfill.go, line 1566 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE96s13Z5u9xh64UO8:-MpE9gq-Cqhh8HP-WSqZ:b-vgo1ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/backfill.go#L1566)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does it still need to be `NodeUserSessionDataOverride`?
</blockquote></details>

nvm, changed in the rebase
___
*[pkg/sql/backfill.go, line 1688 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE99wIEz98ELZSr62b:-MpE9fCDDu3ZbUN4eHnT:b-vgo1ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/backfill.go#L1688)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does it still need to be `NodeUserSessionDataOverride`?
</blockquote></details>

nvm, changed in the rebase
___
*[pkg/sql/backfill.go, line 1787 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE85NwDKY61k4242qV:-MpE9bxv76C99s_1PI1m:b-bvak8) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/backfill.go#L1787)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> ```
> execOverride
> ```
i thought the plan was to keep this using `NodeUserSessionDataOverride`
</blockquote></details>

ah i see it happened in a rebase. this seems fine then


<!-- Sent from Reviewable.io -->

2021-11-24 15:55 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, @rafiss, and @RichardJCai)

___
*[pkg/sql/backfill.go, line 1566 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE96s13Z5u9xh64UO8:-MpHdk7v1AtC1XpWD2uq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/backfill.go#L1566)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nvm, changed in the rebase
</blockquote></details>

Done.
___
*[pkg/sql/backfill.go, line 1688 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE99wIEz98ELZSr62b:-MpHdkRV3PYBCIpFWJ6i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/backfill.go#L1688)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nvm, changed in the rebase
</blockquote></details>

Done.
___
*[pkg/sql/backfill.go, line 1787 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE85NwDKY61k4242qV:-MpHdl8J412Kx3xebwRO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/backfill.go#L1787)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah i see it happened in a rebase. this seems fine then
</blockquote></details>

Done.
___
*[pkg/sql/unsplit.go, line 110 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE8jZd80idhHb-fUSE:-MpHdzEfEcePHjeY2ZyZ:bea3kuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/unsplit.go#L110)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this used to use `root`, but now doesn't have an override. does it still need to be `root` or `node`?
</blockquote></details>

This actually used `NoSessionDataOverride` or rahter just an empty `sessiondata.InternalExecutorOverride{}` before - this should continue to be sufficient. (Look at first commit)


<!-- Sent from Reviewable.io -->

2021-11-24 19:27 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, @rafiss, and @RichardJCai)

___
*[pkg/sql/resolve_oid.go, line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpIPLG25y2MAAcaSGvJ:-MpIPLG25y2MAAcaSGvK:b-by7dlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61e3fc0b4500eda0028b054b3ea954333e246f2/pkg/sql/resolve_oid.go#L78)):*
> ```Go
> 	results, err := ie.QueryRowEx(ctx, "queryOid", txn,
> 		sessiondata.NoSessionDataOverride, q, toResolve)
> 	//results, err := ie.QueryRowEx(ctx, "queryOid", txn,
> ```

commented code (and just confirming that the user override is right?)
___
*[pkg/sql/unsplit.go, line 110 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE8jZd80idhHb-fUSE:-MpIPEQQ9qa20SBROeYP:bpw5upi) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/unsplit.go#L110)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

This actually used `NoSessionDataOverride` or rahter just an empty `sessiondata.InternalExecutorOverride{}` before - this should continue to be sufficient. (Look at first commit)
</blockquote></details>

ah OK then i guess i got mixed up -- but now it looks like `r7` is using NodeUser again?
___
*[pkg/bench/rttanalysis/testdata/benchmark_expectations, line 54 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpIPZzfBxHjOW6jzwkq:-MpIPZzfBxHjOW6jzwkr:bgu81vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61e3fc0b4500eda0028b054b3ea954333e246f2/pkg/bench/rttanalysis/testdata/benchmark_expectations#L54)):*
> ```
> 20,Grant/grant_all_on_3_tables
> 17,GrantRole/grant_1_role
> 20,GrantRole/grant_2_roles
> ```

looks like between `r6` and `r7` some of these disappeared again

```
10,InternalExecutor/has_schema_privilege_1_col
14,InternalExecutor/has_schema_privilege_2_col
18,InternalExecutor/has_schema_privilege_3_col
48,InternalExecutor/has_schema_privilege_3_schemas_3_col
72,InternalExecutor/has_schema_privilege_5_schemas_3_col

3,ORMQueries/information_schema._pg_index_position

4,ORMQueries/pg_is_other_temp_schema
4,ORMQueries/pg_is_other_temp_schema_multiple_times
2,ORMQueries/pg_my_temp_schema
2,ORMQueries/pg_my_temp_schema_multiple_times
```


<!-- Sent from Reviewable.io -->

2021-11-24 20:32 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, @rafiss, and @RichardJCai)

___
*[pkg/sql/resolve_oid.go, line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpIPLG25y2MAAcaSGvJ:-MpIcBU2Cl57zcgGHOIj:b1kcy6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61e3fc0b4500eda0028b054b3ea954333e246f2/pkg/sql/resolve_oid.go#L78)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

commented code (and just confirming that the user override is right?)
</blockquote></details>

Yeah before this used to just be `QueryRow` so I think `NoSessionDataOverride` should work here
___
*[pkg/sql/unsplit.go, line 110 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpE8jZd80idhHb-fUSE:-MpId-Ej5-_Jvvr4t7EH:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc81e441225eb2a8d10c54e9d7e7f0212732a4ea/pkg/sql/unsplit.go#L110)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah OK then i guess i got mixed up -- but now it looks like `r7` is using NodeUser again?
</blockquote></details>

Updated.
___
*[pkg/bench/rttanalysis/testdata/benchmark_expectations, line 54 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-MpIPZzfBxHjOW6jzwkq:-MpIQDhI7qibQkThXzv0:b-ioyq15) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61e3fc0b4500eda0028b054b3ea954333e246f2/pkg/bench/rttanalysis/testdata/benchmark_expectations#L54)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

looks like between `r6` and `r7` some of these disappeared again

```
10,InternalExecutor/has_schema_privilege_1_col
14,InternalExecutor/has_schema_privilege_2_col
18,InternalExecutor/has_schema_privilege_3_col
48,InternalExecutor/has_schema_privilege_3_schemas_3_col
72,InternalExecutor/has_schema_privilege_5_schemas_3_col

3,ORMQueries/information_schema._pg_index_position

4,ORMQueries/pg_is_other_temp_schema
4,ORMQueries/pg_is_other_temp_schema_multiple_times
2,ORMQueries/pg_my_temp_schema
2,ORMQueries/pg_my_temp_schema_multiple_times
```
</blockquote></details>

Yeah I reverted all my benchmark changes since this shouldn't actually change anything if I'm not passing desc cols. Will re-add in future desc colsPPR.


<!-- Sent from Reviewable.io -->

2021-11-24 21:58 UTC, rafiss approved these changes
lgtm! i still don't really get why those benchmark changes were missing, but seems fine to add them later

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-:-MpIxFcHA1_cVK5H9nJl:b-v2iwli)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, @rafiss, and @RichardJCai)



<!-- Sent from Reviewable.io -->

2021-11-24 21:59 UTC, rafiss reviewed
maybe a followup is to remove `ExecCfg.InternalExecutor` entirely?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71246#-:-MpIxNRf62BC-kcrDagC:b-6od7h1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, @rafiss, and @RichardJCai)



<!-- Sent from Reviewable.io -->

2021-11-24 22:16 UTC, RichardJCai commented
TFTR! 
bors r=rafiss

2021-11-24 23:38 UTC, merged

2021-11-25 20:57 UTC, adityamaru commented
@RichardJCai do you have a follow up to inject extra txn state into the IE sitting around, or should I write one up? I kinda need something similar for some IMPORT work I'm doing.

2021-11-25 21:04 UTC, RichardJCai commented
> @RichardJCai do you have a follow up to inject extra txn state into the IE sitting around, or should I write one up? I kinda need something similar for some IMPORT work I'm doing.

If you look at the reviewable on r5, I had something to inject extra txn state, however I'll probably not get to it until Tuesday, if you need it more urgently I'd recommend taking inspiration from r5 here and optionally pass in `ExtraTxnState` into `SessionBoundInternalExecutorFactory` it shouldn't be too much to add on I believe. I left it out of this PR to limit the scope of it. I'd recommend doing something like passing in optional functions into `InternalExecutorFactory` where the function calls takes an `InternalExecutor` and mutates it in some way (injecting state in this case)

2021-11-26 16:52 UTC, adityamaru commented
I took a stab at https://github.com/cockroachdb/cockroach/pull/73193. I'm conflicted whether we should pass in a closure and leave it up to the user of the internal executor to set the appropriate fields, or if we should require the user to inject the state by having types arguments to the factory?

2021-11-26 18:07 UTC, adityamaru commented
Regardless of what we decide above, I think the next step as pointed out by rafi is to remove the InternalExecutor from ExecCfg entirely and force everyone to initialize a new one when they need one. This way we move closer to our eventual goal of tightly binding statement execution with the external state. I'll try putting that out next before trying to inject ExtraTxnState.