rpc,security: use the tenant client cert for pod-pod communication
cockroachdb/cockroach pull request #71248
Opened 2021-10-06 22:32 UTC by knz

Fixes #71106
Alternative design to  #71190
Epic: SEC-665

As of this patch, we have the following file usage:

- KV nodes on host cluster:
  - ui.crt (optional):
    - used as server cert for HTTP
  - ui-ca.crt (optional):
    - used in unit tests to verify the server's identity for HTTP conns
  - node.crt:
    - used as client cert for node-to-node comms
    - used as server cert for node-to-node comms
    - used as server cert for SQL clients
    - used as server cert for incoming conns from SQL tenant servers
    - used as server cert for HTTP, if ui.crt doesn't exist
  - tenant-client-ca.crt (optional):
    - used to verify client certs for SQL tenant servers
  - client-ca.crt (optional);
    - used to verify client certs for SQL clients
    - used to verify client certs for SQL tenant servers, if tenant-client-ca.crt doesn't exist
  - ca.crt:
    - used to verify other node client certs for node-to-node comms
    - used in unit tests to verify the server's identity for SQL and RPC conns
    - used to verify client certs for SQL clients, if client-ca.crt doesn't exist
    - used to verify client certs for SQL tenant servers, if neither tenant-client.ca.crt nor client-ca.crt exist

- SQL servers:
  - ui.crt (optional):
    - used as server cert for HTTP
  - ui-ca.crt (optional):
    - used in unit tests to verify the server's identity for HTTP conns
  - client-tenant.NN.crt:
    - used as client cert for node-to-node comms (SQL server to SQL server)
    - used as server cert for node-to-node comms (SQL server to SQL server)
    - used as client cert for conns to KV nodes
    - used as server cert for SQL clients
    - used as server cert for HTTP, if ui.crt doesn't exist
  - tenant-client-ca.crt (optional):
    - used to verify client certs for SQL tenant servers
  - client-ca.crt (optional);
    - used to verify client certs for SQL clients
    - used to verify client certs for SQL tenant servers, if tenant-client-ca.crt doesn't exist
  - ca.crt:
    - used to verify other SQL server certs for node-to-node comms, if tenant-client-ca.crt doens't exist
    - used to verify client certs for SQL clients, if client-ca.crt doesn't exist
    - used to verify client certs for SQL tenant servers, if neither tenant-client.ca.crt nor client-ca.crt exist
    - used in unit tests to verify the server's identity for SQL and  RPC conns

Release note (security update): Multitenant SQL servers now reuse
the tenant client certificate (`client-tenant.NN.crt`) for SQL-to-SQL
communication. Existing deployments must regenerate the certificates
with dual purpose (client and server authentication).

2021-10-06 22:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/71248)
<!-- Reviewable:end -->

2021-10-06 23:21 UTC, catj-cockroach requested changes
First pass looks good to me!

I have a few suggestions:

* let's rename every instance of TenantClient to Tenant
* let's assume that the CA used for tenants is the same as the CA used for the SQL layer and remove support for the TenantCACertificate. I'd prefer we add it back if we need it rather than having a distinct CA for every potential layer of the infrastructure.

We then end up with:

* ca.crt - used for infrastructure
* client-ca.crt - used for SQL clients

> Reviewed 29 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-:-MlMtXV795v0iMOdH_JQ:b7e4zlt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach and @knz)

___
*[pkg/rpc/auth.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMjY8a8vgr9-00eaQ7:-MlMjY8a8vgr9-00eaQ8:bsixoa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/rpc/auth.go#L150)):*
> ```Go
> 		// Is this a connection from another SQL tenant server?
> 		subj := tlsInfo.State.PeerCertificates[0].Subject
> 		if !security.Contains(subj.OrganizationalUnit, security.TenantsOU) {
> ```

Could we throw this logic and the above logic into an exported function in the `security` package?

For example:

```golang
// IsTenantCertificate returns true if the passed certificate indicates an
// inbound Tenant connection.
func IsTenantCertificate(cert *x509.Certificate) bool {
		return Contains(cert.Subject.OrganizationalUnit, TenantsOU)
}
```
___
*[pkg/security/certificate_manager.go, line 778 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMsKns-1LPnlo2G3Fl:-MlMsKnt1T8oe1jIbxLz:bnzsvke) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L778)):*
> ```Go
> 
> 	var nodeCert *CertInfo
> 	if cm.tenantClientCert == nil {
> ```

Could I suggest that we do a search and replace for all instances of "tenantClient", replacing it with "tenant"?
___
*[pkg/security/certificate_manager.go, line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMnQq7ETXzDGvqLmXC:-MlMnQq7ETXzDGvqLmXD:blg2r33) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L873)):*
> ```Go
> 	if cm.clientCACert == nil {
> 		// No client CA: use general CA.
> 		if cm.tenantClientCert == nil {
> ```

I am not 100% certain what's going on here so I'll layout what my assumption is:

This function checks to see if the CA certificate exists in the CertificateManager. 
* If it does not, it checks to see if the Tenant Client Certificate exists.
* If the Tenant Certificate has not been loaded into the certificate manager (it points to nil), it returns the global CA certificate.
* If the Tenant Certificate has been loaded (is not nil), it returns the Tenant CA certificate.
* If the Client CA certificate _does_ exist, we verify that it is valid. If it is valid, we return it. If it is not valid we return an error.

Is this correct?
___
*[pkg/security/certificate_manager.go, line 963 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMr2MP936uts0y1u7E:-MlMr2MP936uts0y1u7F:bc5l39s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L963)):*
> ```Go
> // certificates. Use the tenant client CA if it exists, otherwise fall back to
> // client CA. cm.mu must be held.
> func (cm *CertificateManager) getTenantClientCACertLocked() (*CertInfo, error) {
> ```

Given that the Tenant Client Certificate is no longer just used as a client, I'd think it would make sense to rename this to `getTenantCACertLocked()`
___
*[pkg/security/certificate_manager.go, line 976 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMrNml7xxao7hW1Q_5:-MlMrNml7xxao7hW1Q_6:b-zg7o0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L976)):*
> ```Go
> // getTenantClientCertLocked returns the tenant node cert.
> // cm.mu must be held.
> func (cm *CertificateManager) getTenantClientCertLocked() (*CertInfo, error) {
> ```

Likewise with above, could we rename this to `getTenantCertLocked()`
___
*[pkg/security/certificate_manager.go, line 986 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMrYSX-Qq6DidZFRDx:-MlMrYSX-Qq6DidZFRDy:b-dcoee7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L986)):*
> ```Go
> // GetTenantClientTLSConfig returns the most up-to-date tenant client
> // tls.Config.
> func (cm *CertificateManager) GetTenantClientTLSConfig() (*tls.Config, error) {
> ```

Is this still intended for outbound connections as a client? 
___
*[pkg/security/certificate_manager.go, line 1018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMruY57YkUt_weBwk-:-MlMruY57YkUt_weBwk0:b-2yk3w7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L1018)):*
> ```Go
> 
> // GetClientTLSConfig returns the most up-to-date client tls.Config.
> // Returns the dual-purpose node certs if user == NodeUser and there is no
> ```

Should this say dual-purpose node certificates (or tenant certificates)?
___
*[pkg/security/certs.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMqFUM3gqTZmY9G_Sl:-MlMqFUM3gqTZmY9G_Sm:b6uvucb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certs.go#L488)):*
> ```Go
> 	}
> 
> 	// Load the tenant client CA cert info. Note that this falls back to the regular client CA which in turn falls
> ```

What do we intend on using as `ca.crt` in the SQL servers? Is it the tenant CA certificate?


<!-- Sent from Reviewable.io -->

2021-10-07 15:54 UTC, knz reviewed
> let's assume that the CA used for tenants is the same as the CA used for the SQL layer and remove support for the TenantCACertificate. 

I've tried that and there is _waay_ too much code changes needed. I think I want to de-risk this and avoid boiling the ocean so close to the release.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-:-MlQSdjM1jzBHaa76JOH:b3qvmpl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach)

___
*[pkg/rpc/auth.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMjY8a8vgr9-00eaQ7:-MlQRmL7-2rLlysS_j5G:btq3yri) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/rpc/auth.go#L150)):*
> Could we throw this logic and the above logic into an exported function in the security package?

Probably we can yes. Do you want me to do it too?
___
*[pkg/security/certificate_manager.go, line 778 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMsKns-1LPnlo2G3Fl:-MlQRtESCnAVIURBaP91:bchi5tx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L778)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Could I suggest that we do a search and replace for all instances of "tenantClient", replacing it with "tenant"?
</blockquote></details>

Yes you could suggest that. Is this also what you want to happen?
___
*[pkg/security/certificate_manager.go, line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMnQq7ETXzDGvqLmXC:-MlQSR2v8ixYgA_9E0_e:bth1bc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L873)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

I am not 100% certain what's going on here so I'll layout what my assumption is:

This function checks to see if the CA certificate exists in the CertificateManager. 
* If it does not, it checks to see if the Tenant Client Certificate exists.
* If the Tenant Certificate has not been loaded into the certificate manager (it points to nil), it returns the global CA certificate.
* If the Tenant Certificate has been loaded (is not nil), it returns the Tenant CA certificate.
* If the Client CA certificate _does_ exist, we verify that it is valid. If it is valid, we return it. If it is not valid we return an error.

Is this correct?
</blockquote></details>

that sounds about right with the current code. I'm not sure that the code we should have there though.
___
*[pkg/security/certificate_manager.go, line 963 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMr2MP936uts0y1u7E:-MlQSLLr-05zof3dB8EQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L963)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Given that the Tenant Client Certificate is no longer just used as a client, I'd think it would make sense to rename this to `getTenantCACertLocked()`
</blockquote></details>

Done.
___
*[pkg/security/certificate_manager.go, line 976 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMrNml7xxao7hW1Q_5:-MlQS0DR7ZjZEWSJjYbs:b-z52don) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L976)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Likewise with above, could we rename this to `getTenantCertLocked()`
</blockquote></details>

probably we could yes. if you want it to happen, please spell it out.
___
*[pkg/security/certificate_manager.go, line 986 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMrYSX-Qq6DidZFRDx:-MlQ9VZ641-pwBFuwh1u:bfpdr1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L986)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Is this still intended for outbound connections as a client? 
</blockquote></details>

it's used for outbound connections from tenant to KV node.
___
*[pkg/security/certificate_manager.go, line 1018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMruY57YkUt_weBwk-:-MlQRbmxEzs63ncnHsDK:bggkxm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L1018)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Should this say dual-purpose node certificates (or tenant certificates)?
</blockquote></details>

I don't know?
If you have a specific idea, please spell it out.
___
*[pkg/security/certs.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMqFUM3gqTZmY9G_Sl:-MlQRfQo7OOcwEkvL1Vw:bxfacj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certs.go#L488)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

What do we intend on using as `ca.crt` in the SQL servers? Is it the tenant CA certificate?
</blockquote></details>

I don't know - what do you think?
If you need this to change in any particular way, please spell it out.


<!-- Sent from Reviewable.io -->

2021-10-07 17:30 UTC, catj-cockroach requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71248)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[-- commits, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlQlo6Z1or7ek2ZhDzZ):*
Can we reword this to:

```
- used to verify certificates from SQL tenant servers connecting as clients
```
___
*[-- commits, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlQmBOtACetB-OP6q0-):*
Can we reword this to:

```
used to verify certs from other SQL tenant servers
```
___
*[pkg/rpc/auth.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMjY8a8vgr9-00eaQ7:-MlQTEWeARgCsuBTg5LG:bo6ompl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/rpc/auth.go#L150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> Could we throw this logic and the above logic into an exported function in the security package?

Probably we can yes. Do you want me to do it too?
</blockquote></details>

Yes please!
___
*[pkg/security/certificate_manager.go, line 778 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMsKns-1LPnlo2G3Fl:-MlQTOOGENdJyT6J5Ysc:bo6ompl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L778)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes you could suggest that. Is this also what you want to happen?
</blockquote></details>

Yes please!
___
*[pkg/security/certificate_manager.go, line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMnQq7ETXzDGvqLmXC:-MlQTPzd0KMvEhSAXL_x:bl59dxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L873)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

that sounds about right with the current code. I'm not sure that the code we should have there though.
</blockquote></details>

I'd argue for this specific function, let's return `client-ca.crt` or `ca.crt` if clientCACert doesn't exist. Let's treat Tenant Client CA as only used for tenant certificates.

What if we have CertificateManager have a `IsTenant` function? We could have it return true if we have a tenant certificate (and if we want to share the tenant ID with the certificate manager, we could also require that be set as well), and then use that to determine what certificate to return? (This is part of why I suggested we remove the TenantClientCACert).
___
*[pkg/security/certificate_manager.go, line 894 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlQUjEV8YW1Fw_qeWVb:-MlQUjEV8YW1Fw_qeWVc:b-79d4yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L894)):*
> ```Go
> 			return cm.getCACertLocked()
> 		}
> 		return cm.getTenantClientCACertLocked()
> ```

To simplify things, let's only use `ui-ca.crt`, `client-ca.crt`, or `ca.crt` for the UI everywhere.

Could you remove references to the Tenant CA from the UI related functions in this file?
___
*[pkg/security/certificate_manager.go, line 921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlQV1A4AVgkXe-Lyyo5:-MlQV1A4AVgkXe-Lyyo6:b-1kzc9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L921)):*
> ```Go
> 			return cm.getNodeCertLocked()
> 		}
> 		return cm.getTenantClientCertLocked()
> ```

And here!
___
*[pkg/security/certificate_manager.go, line 976 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMrNml7xxao7hW1Q_5:-MlQhfZsAzGO8tqUYMeJ:bxutqp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L976)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

probably we could yes. if you want it to happen, please spell it out.
</blockquote></details>

OK! Let's rename it to `getTenantCertLocked()` and add a function that calls it directly called `getTenantClientCertLocked`.
___
*[pkg/security/certificate_manager.go, line 986 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMrYSX-Qq6DidZFRDx:-MlQi1YQ2C4H6LKVAeKt:b-4zj1mi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L986)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

it's used for outbound connections from tenant to KV node.
</blockquote></details>

Are we also using it for Tenant-to-Tenant communication? If so, let's rename this to `GetTenantTLSConfig()`, if not, let's rename it to `GetTenantToKVTLSConfig()`
___
*[pkg/security/certificate_manager.go, line 1018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMruY57YkUt_weBwk-:-MlQiE1t6fEu6u2sw7Mn:b6mjw3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L1018)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't know?
If you have a specific idea, please spell it out.
</blockquote></details>

I was looking at this locally and I think we should split this function into two functions.

```golang
func (cm *CertificateManager) getUserTLSConfig(user SQLUsername) (*tls.Config, error) {
	cm.mu.Lock()
	defer cm.mu.Unlock()

	// We always need the CA cert.
	var ca *CertInfo
	var err error

	ca, err = cm.getCACertLocked()
	if err != nil {
		return nil, err
	}
	
	clientCert, err := cm.getClientCertLocked(user)
	if err != nil {
		return nil, err
	}

	cfg, err := newClientTLSConfig(
		cm.tlsSettings,
		clientCert.FileContents,
		clientCert.KeyFileContents,
		ca.FileContents)
	if err != nil {
		return nil, err
	}

	return cfg, nil
}

// exported so we can refactor code that always wants the NodeTLSConfig directly.
func (cm *CertificateManager) GetNodeTLSConfig() (*tls.Config, error) {
	cm.mu.Lock()
	defer cm.mu.Unlock()

	// We always need the CA cert.
	ca, err = cm.getCACertLocked()
	if err != nil {
		return nil, err
	}

	// We're the node user:
	// Return the cached config if we have one.
	if cm.clientConfig != nil {
		return cm.clientConfig, nil
	}

	clientCert, err := cm.getNodeClientCertLocked()
	if err != nil {
		return nil, err
	}

	cfg, err := newClientTLSConfig(
		cm.tlsSettings,
		clientCert.FileContents,
		clientCert.KeyFileContents,
		ca.FileContents)
	if err != nil {
		return nil, err
	}

	// Cache the config.
	cm.clientConfig = cfg
	return cfg, nil

}

// GetClientTLSConfig returns the most up-to-date client tls.Config.
// Returns the dual-purpose node certs if user == NodeUser and there is no
// separate client cert for 'node'.
func (cm *CertificateManager) GetClientTLSConfig(user SQLUsername) (*tls.Config, error) {
	if !user.IsNodeUser() {
		return cm.getUserTLSConfig(user)
	}

	return cm.GetNodeTLSConfig()
}
```
___
*[pkg/security/certificate_manager.go, line 954 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlQku3R6jXJKOsRNPtE:-MlQku3R6jXJKOsRNPtF:b-nq19ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/52d61aee4c27298375ccbf7f785f34de25bde990/pkg/security/certificate_manager.go#L954)):*
> ```Go
> 			return cm.getNodeCertLocked()
> 		}
> 		return cm.getTenantClientCertLocked()
> ```

We're only using Node to refer to KV layer/non-multi-tenant nodes, could we remove the SQL tenant logic from this function? Below I've a request to rename and alias the existing `getTenantClientCertLocked()`, and I'd prefer we explicitly use that function rather than having this function try to return the correct certificate.
___
*[pkg/security/certs.go, line 488 at r1](h [...]

2021-10-07 20:16 UTC, knz reviewed
I've processed your review comments, but still working to fix a few thigns. I'll give a signal when this is ready to review again.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-:-MlROb0c-nPJ_2etwC-6:brswvv7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach and @chrisseto)

___
*[-- commits, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlQlo6Z1or7ek2ZhDzZ):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Can we reword this to:

```
- used to verify certificates from SQL tenant servers connecting as clients
```
</blockquote></details>

Done.
___
*[-- commits, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlQmBOtACetB-OP6q0-):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Can we reword this to:

```
used to verify certs from other SQL tenant servers
```
</blockquote></details>

Done.
___
*[pkg/rpc/auth.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMjY8a8vgr9-00eaQ7:-MlQpyDO1UKFEKqfRaJF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/rpc/auth.go#L150)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Yes please!
</blockquote></details>

Done.
___
*[pkg/security/certificate_manager.go, line 778 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMsKns-1LPnlo2G3Fl:-MlQqM0u6afPwFf_ue9T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L778)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Yes please!
</blockquote></details>

Done.
___
*[pkg/security/certificate_manager.go, line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMnQq7ETXzDGvqLmXC:-MlRJmgQCKZLJaUDp-sd:b-qcu9rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L873)):*
> What if we have CertificateManager have a IsTenant function?

Done.
___
*[pkg/security/certificate_manager.go, line 894 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlQUjEV8YW1Fw_qeWVb:-MlRL2k_E0kqMjSamEEN:b-9l5lg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L894)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

To simplify things, let's only use `ui-ca.crt`, `client-ca.crt`, or `ca.crt` for the UI everywhere.

Could you remove references to the Tenant CA from the UI related functions in this file?
</blockquote></details>

@chrisseto suggests this wouldn't be smart, because our deployment code does not yet provision separate certs/CA for the HTTP service.
___
*[pkg/security/certificate_manager.go, line 921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlQV1A4AVgkXe-Lyyo5:-MlRL9Tk9zCHRBDW6MmO:b-z3p5ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L921)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

And here!
</blockquote></details>

ditto above
___
*[pkg/security/certificate_manager.go, line 976 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMrNml7xxao7hW1Q_5:-MlRMbov1WdV3XwvBB7_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L976)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

OK! Let's rename it to `getTenantCertLocked()` and add a function that calls it directly called `getTenantClientCertLocked`.
</blockquote></details>

Done.
___
*[pkg/security/certificate_manager.go, line 986 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMrYSX-Qq6DidZFRDx:-MlRMe_EDB7SGCf3lcEY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L986)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Are we also using it for Tenant-to-Tenant communication? If so, let's rename this to `GetTenantTLSConfig()`, if not, let's rename it to `GetTenantToKVTLSConfig()`
</blockquote></details>

Done.
___
*[pkg/security/certificate_manager.go, line 1018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMruY57YkUt_weBwk-:-MlRNdGiBP8UGu-SOWmR:b-e16dza) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certificate_manager.go#L1018)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

I was looking at this locally and I think we should split this function into two functions.

```golang
func (cm *CertificateManager) getUserTLSConfig(user SQLUsername) (*tls.Config, error) {
	cm.mu.Lock()
	defer cm.mu.Unlock()

	// We always need the CA cert.
	var ca *CertInfo
	var err error

	ca, err = cm.getCACertLocked()
	if err != nil {
		return nil, err
	}
	
	clientCert, err := cm.getClientCertLocked(user)
	if err != nil {
		return nil, err
	}

	cfg, err := newClientTLSConfig(
		cm.tlsSettings,
		clientCert.FileContents,
		clientCert.KeyFileContents,
		ca.FileContents)
	if err != nil {
		return nil, err
	}

	return cfg, nil
}

// exported so we can refactor code that always wants the NodeTLSConfig directly.
func (cm *CertificateManager) GetNodeTLSConfig() (*tls.Config, error) {
	cm.mu.Lock()
	defer cm.mu.Unlock()

	// We always need the CA cert.
	ca, err = cm.getCACertLocked()
	if err != nil {
		return nil, err
	}

	// We're the node user:
	// Return the cached config if we have one.
	if cm.clientConfig != nil {
		return cm.clientConfig, nil
	}

	clientCert, err := cm.getNodeClientCertLocked()
	if err != nil {
		return nil, err
	}

	cfg, err := newClientTLSConfig(
		cm.tlsSettings,
		clientCert.FileContents,
		clientCert.KeyFileContents,
		ca.FileContents)
	if err != nil {
		return nil, err
	}

	// Cache the config.
	cm.clientConfig = cfg
	return cfg, nil

}

// GetClientTLSConfig returns the most up-to-date client tls.Config.
// Returns the dual-purpose node certs if user == NodeUser and there is no
// separate client cert for 'node'.
func (cm *CertificateManager) GetClientTLSConfig(user SQLUsername) (*tls.Config, error) {
	if !user.IsNodeUser() {
		return cm.getUserTLSConfig(user)
	}

	return cm.GetNodeTLSConfig()
}
```
</blockquote></details>

That's a slightly too ambitious refactor for this time. I'll leave a TODO.
___
*[pkg/security/certificate_manager.go, line 954 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlQku3R6jXJKOsRNPtE:-MlRMVx16zE0ISJ6ojRu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/52d61aee4c27298375ccbf7f785f34de25bde990/pkg/security/certificate_manager.go#L954)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

We're only using Node to refer to KV layer/non-multi-tenant nodes, could we remove the SQL tenant logic from this function? Below I've a request to rename and alias the existing `getTenantClientCertLocked()`, and I'd prefer we explicitly use that function rather than having this function try to return the correct certificate.
</blockquote></details>

Done.
___
*[pkg/security/certs.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMqFUM3gqTZmY9G_Sl:-MlRO3U5-vIQQC6P2ZYm:b-fmjhc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certs.go#L488)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Oh, sorry I [...]

2021-10-07 21:44 UTC, catj-cockroach approved these changes
> Reviewed 15 of 17 files at r3, 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71248)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/security/certificate_manager.go, line 611 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlRd6Mx1pXl3q22uAMJ:-MlRd6Mx1pXl3q22uAMK:b-600flx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7422314cb6a895df23c13f9def02487d636d6793/pkg/security/certificate_manager.go#L611)):*
> ```Go
> 		case NodePem:
> 			// Don't even bother loading the node cert if we are not in the
> 			// host cluster.
> ```

Oooo good call!
___
*[pkg/security/certificate_manager.go, line 938 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlRf9i90VU0PEUBh0-a:-MlRf9i90VU0PEUBh0-b:b75099u) ([raw file](https://github.com/cockroachdb/cockroach/blob/406b3969019423a52a4ecf2f840f9589bf855008/pkg/security/certificate_manager.go#L938)):*
> ```Go
> // cm.mu must be held.
> //
> // TODO(catj): split the logic here into two functions.
> ```

Thank you! :)
___
*[pkg/security/certificate_manager.go, line 957 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlRfGTA8hiZYBtnmsSn:-MlRfGTA8hiZYBtnmsSo:b-c2cc3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/406b3969019423a52a4ecf2f840f9589bf855008/pkg/security/certificate_manager.go#L957)):*
> ```Go
> 		// but only if we are in the host cluster.
> 		if cm.IsForTenant() {
> 			return nil, errors.New("no node client cert for a SQL server")
> ```

Oh this is much clearer, thank you!
___
*[pkg/security/certificate_manager.go, line 1116 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlRgfBU8FoFtU8eOixF:-MlRgfBV68EnKet6v5J5:b73j6pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/406b3969019423a52a4ecf2f840f9589bf855008/pkg/security/certificate_manager.go#L1116)):*
> ```Go
> 	caBlob := uiCA.FileContents
> 
> 	// If it's available, we also include the tenant CA.
> ```

Out of curiosity, why do we include the tenant CA as well? Is it signing anything related to the UI?
___
*[pkg/security/certs.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlMqFUM3gqTZmY9G_Sl:-MlRgsaV0unyb51Kia1d:b2ni6cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d860f6c8c8a0b2462f5204d533f95bdf154eb98d/pkg/security/certs.go#L488)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think the commit message describes what the current behavior is. I don't know what a good endpoint should be, but then it's not exactly in-scope for this PR.
</blockquote></details>

kk!
___
*[pkg/security/tls.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlRh-hTBzG-sEZ6PsFD:-MlRh-hTBzG-sEZ6PsFE:b-1n02fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/406b3969019423a52a4ecf2f840f9589bf855008/pkg/security/tls.go#L44)):*
> ```Go
> // Embedded certificates specific to multi-tenancy testing.
> const (
> 	EmbeddedTenantCACert = "ca-client-tenant.crt" // CA for client connections
> ```

This doesn't need to happen now but we should rename this to `ca-tenant.crt` as well!


<!-- Sent from Reviewable.io -->

2021-10-07 21:45 UTC, catj-cockroach approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71248)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)



<!-- Sent from Reviewable.io -->

2021-10-07 21:52 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71248)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @catj-cockroach)

___
*[pkg/security/certificate_manager.go, line 1116 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlRgfBU8FoFtU8eOixF:-MlRjL5wCum_axm4UI-H:blxu2v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/406b3969019423a52a4ecf2f840f9589bf855008/pkg/security/certificate_manager.go#L1116)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Out of curiosity, why do we include the tenant CA as well? Is it signing anything related to the UI?
</blockquote></details>

In unit tests, we have the HTTP client validate the server's identity.
Since the server may be using the tenant cert, we need it to know about the tenant CA too.
___
*[pkg/security/tls.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71248#-MlRh-hTBzG-sEZ6PsFD:-MlRjWCkCPRbQPN6l0ux:b1vs09y) ([raw file](https://github.com/cockroachdb/cockroach/blob/406b3969019423a52a4ecf2f840f9589bf855008/pkg/security/tls.go#L44)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

This doesn't need to happen now but we should rename this to `ca-tenant.crt` as well!
</blockquote></details>

I fear there are hardcoded file paths in other places. Let's not boil the ocean.


<!-- Sent from Reviewable.io -->

2021-10-11 03:45 UTC, knz commented
@chrisseto can you provide repro steps?

I just tried myself with a directory that doesn't have node certs, and it appears that the SQL server starts fine.

2021-10-11 03:54 UTC, knz commented
@chrisseto I think it's vaguely possible you're trying to mix and match different crdb executable versions?

2021-10-11 04:45 UTC, knz commented
I'm going to go ahead and merge this, on account of Catherine's positive review and that CI is satisfied.

My purpose in merging this now is to give a chance to our roachtests to exercise the changes thoroughly in the nightly run.

We can adjust the logic further in followup PRs.

bors r=catj-cockroach

2021-10-11 06:22 UTC, merged