opt: binary span merging and constraint unioning for ORed conditions
cockroachdb/cockroach pull request #71247
Opened 2021-10-06 21:56 UTC by msirek

Fixes https://github.com/cockroachdb/cockroach/issues/60602

Previously, spans for a chain of ORed predicates were merged with the
entire list of previously-built spans, one-at-a-time, which takes hours
in some cases.  This patch changes it to a divide and conquer approach
and removes redundant processing of conditions.

The old method was inadequate because app-generated SQL may contain
thousands of ORed conditions, and building the spans for such SQL needs
needs to be handled in a reasonable amount of time (seconds, not hours).
The problem revolves around the use a single linear structure that needs
to be searched for the merge point of each new span.  An ORed boolean
SQL expression gets constructed into a left-deep tree of OrExpr's,
for example, given:
```
A OR B OR C OR D OR E
```
The expression tree for these conditions is built as:
```
                OrExpr
                 /    \
              OrExpr   E
               /    \
            OrExpr   D
             /    \
          OrExpr   C
           /    \
          A      B
```
Because of the shape of the expression tree and the recursive processing
of each condition, we only maintain a single list of spans associated
with the left side of this tree.
In the worst-case scenario, to merge a given span into m
previously-added spans, we need to search all m of them to find the
merge location.  For n items, the average span list size during
construction is n/2.  So, to merge all n items could take a worst-case
n*(n/2) operations, or O(n²).

Besides the above, there were redundant calls to makeSpansForExpr which
would cause ORed conditions to be processed more than once.  Given the
example above, we would end up processing conditions as follows:
```
1. A, B, C, D, E
2. B, C, D, E
3. C, D, E
4. D, E
5. E
```
For long chains of ORed conditions, this is quite expensive.  In fact,
this appears to be the main source of the performance issue.

To address the single span list issue, we collect all directly-connected
ORed conditions into a list, and use divide and conquer to recursively
process the left and right halves.  This causes merging to be done on
multiple conditions at a time, which is more efficient.  Merging is a
single-pass operation, so the more elements we can merge in one pass,
the better.  The runtime is similar to what it would have been had the
condition tree originated as a balanced binary tree instead of a
left-deep tree.

To address the redundant calls to makeSpansForExpr, we track whether
the current expression node is the child of an OrExpr in 
indexConstraintCtx.simplifyFilter, and if so, only call makeSpansForExpr
when the first (top-most) OrExpr in an OrExpr chain is encountered.
Fixing this part alone drops runtime of a test case with 6000 terms from
2 hours to 1 minute.  With divide and conquer added as well, the test
case takes 1 second.

Release note (performance improvement): Queries with many ORed WHERE
clause predicates previously took an excessive amount of time for the optimizer
to process, especially if the predicates involved index columns, and if
there were more than 1000 predicates (which could happen with
application-generated SQL). To fix this, we optimized the processing of SQL
with many ORed predicates to make sure a query plan can be generated in
seconds instead of minutes or hours.

2021-10-08 03:56 UTC, msirek commented
@rytaft Thanks.  I've added a microbenchmark.  I'm not sure exactly how to interpret the numbers, but here they are:
```
make bench PKG=./pkg/sql/opt/bench BENCHES=BenchmarkPhases/many-ored-preds
...
GOFLAGS= go test   -mod=vendor -gcflags "all=-N -l" -tags ' make x86_64_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=v21.2.0-alpha.00000000-4745-gc18188e8ee-dirty" -X "github.com/cockroachdb/cockroach/pkg/build.rev=c18188e8ee2e4ecdd0f731df7dc89c28bb1c8566" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-linux-gnu"  ' -run "-" -bench "BenchmarkPhases/many-ored-preds" -timeout 5m ./pkg/sql/opt/bench 
I211008 03:48:58.859742 1 (gostd) rand.go:104  [-] 1  random seed: 7753518535582582574
goos: linux
goarch: amd64
pkg: github.com/cockroachdb/cockroach/pkg/sql/opt/bench
cpu: Intel(R) Core(TM) i9-9960X CPU @ 3.10GHz
BenchmarkPhases/many-ored-preds/Simple/Parse-32         	       4	 308401248 ns/op
BenchmarkPhases/many-ored-preds/Simple/OptBuildNoNorm-32         	       2	 546900302 ns/op
BenchmarkPhases/many-ored-preds/Simple/OptBuildNorm-32           	       2	 571083422 ns/op
BenchmarkPhases/many-ored-preds/Simple/Explore-32                	       2	 744148165 ns/op
BenchmarkPhases/many-ored-preds/Simple/ExecBuild-32              	       2	 768180758 ns/op
BenchmarkPhases/many-ored-preds/Prepared/AssignPlaceholdersNoNorm-32         	       9	 118236239 ns/op
BenchmarkPhases/many-ored-preds/Prepared/AssignPlaceholdersNorm-32           	       9	 118435695 ns/op
BenchmarkPhases/many-ored-preds/Prepared/Explore-32                          	       4	 286782875 ns/op
BenchmarkPhases/many-ored-preds/Prepared/ExecBuild-32                        	       4	 304593762 ns/op
PASS
ok  	github.com/cockroachdb/cockroach/pkg/sql/opt/bench	22.109s
```

2021-10-08 14:14 UTC, cucaroach reviewed
Nice work, I'll defer stamp of approval to my colleagues with more familiarity with this code but this is awesome!   

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-:-MlVBK7F5BdwHzW2PKF9:bpx4r97)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @msirek)

___
*[pkg/sql/opt/bench/bench_test.go, line 305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlV83Ly3ca1WDXCuPmy:-MlV83Ly3ca1WDXCuPmz:b8dqbiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/bench/bench_test.go#L305)):*
> ```Go
> 		`,
> 		args: []interface{}{1, 2, 3, 4},
> 	},
> ```

It would be nice to programatically construct the query with a parameter and I would go with a smaller N, ie 1s vs 10s is just as good as 15s vs 300s.    I wonder where the bottleneck has moved to, making N a parameter will aid future efforts where we might need 10s or 100s of thousands of ORs to be snappy.
___
*[pkg/sql/opt/idxconstraint/testdata/many_preds, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVF88M-aUQw3UcULPq:-MlVF88M-aUQw3UcULPr:bv881ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/testdata/many_preds#L1)):*
> ```
> index-constraints vars=(id INT, book_id INT, book2_id INT, citation_id INT) index=(id)
> ```

many_preds seems excesssive for a correctness test we probably don't need that many preds.   If there's a reason to test the system like that I would re-cast the test as a hand written test instead of a data driven test.
___
*[pkg/sql/opt/memo/constraint_builder.go, line 554 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlV9nZzBIA7NYn2UjsS:-MlV9nZzBIA7NYn2UjsT:b-4fsyv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/memo/constraint_builder.go#L554)):*
> ```Go
> 		var collectDisjunctions func(e opt.ScalarExpr)
> 		collectDisjunctions = func(e opt.ScalarExpr) {
> 			if and, ok := e.(*OrExpr); ok {
> ```

'and' seems like a confusing choice for this variable name.


<!-- Sent from Reviewable.io -->

2021-10-08 17:05 UTC, mgartner requested changes
Nice find!!

FYI You can use benchstat ([example usage](https://blog.jiayu.co/2019/05/benchmarking-go-code/)) to compare benchmark results more easily. For example, running benchstat on your benchmark output above yields:

```
name                                                         old time/op  new time/op  delta
Phases/many-ored-preds/Simple/Parse-32                       54.4ms ± 0%  53.8ms ± 0%   ~     (p=1.000 n=1+1)
Phases/many-ored-preds/Simple/OptBuildNoNorm-32               535ms ± 0%    91ms ± 0%   ~     (p=1.000 n=1+1)
Phases/many-ored-preds/Simple/OptBuildNorm-32                 541ms ± 0%    91ms ± 0%   ~     (p=1.000 n=1+1)
Phases/many-ored-preds/Simple/Explore-32                      75.4s ± 0%    0.1s ± 0%   ~     (p=1.000 n=1+1)
Phases/many-ored-preds/Simple/ExecBuild-32                    76.1s ± 0%    0.1s ± 0%   ~     (p=1.000 n=1+1)
Phases/many-ored-preds/Prepared/AssignPlaceholdersNoNorm-32   451ms ± 0%    17ms ± 0%   ~     (p=1.000 n=1+1)
Phases/many-ored-preds/Prepared/AssignPlaceholdersNorm-32     469ms ± 0%    17ms ± 0%   ~     (p=1.000 n=1+1)
Phases/many-ored-preds/Prepared/Explore-32                    75.1s ± 0%    0.0s ± 0%   ~     (p=1.000 n=1+1)
Phases/many-ored-preds/Prepared/ExecBuild-32                  74.8s ± 0%    0.0s ± 0%   ~     (p=1.000 n=1+1)
```

If you run the benchmarks at least 5 times each (with `GOFLAGS='-count=5'`) then the `delta` column will be populated too.

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-:-MlVkeY94nqvjD21O_F1:b3dubov)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @msirek)

___
*[-- commits, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVjDM23q-iFLkZKw3q):*
nit: fix alignment
___
*[pkg/sql/opt/bench/bench_test.go, line 305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlV83Ly3ca1WDXCuPmy:-MlVlL_T5Q-yLGGfs7EA:b-ydgj11) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/bench/bench_test.go#L305)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

It would be nice to programatically construct the query with a parameter and I would go with a smaller N, ie 1s vs 10s is just as good as 15s vs 300s.    I wonder where the bottleneck has moved to, making N a parameter will aid future efforts where we might need 10s or 100s of thousands of ORs to be snappy.
</blockquote></details>

I agree. We should only need 10s of ORs to see a difference in the benchmarks. They can take a while to run as-is, so best to not make them unnecessarily slower.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 826 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVlsrk8MdicMmQIuwB:-MlVlsrl96F6VPmlygmd:b1o472y) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/index_constraints.go#L826)):*
> ```Go
> 	or := e.(*memo.OrExpr)
> 	var filters memo.FiltersExpr
> 	filters = make(memo.FiltersExpr, 0, 2)
> ```

`FiltersExpr` represents a list of conjunctions, so it's a bit confusing to store a set of disjunctions in it. Can you use a `[]opt.ScalarExpr` instead? This also avoids the need to wrap the expressions in `memo.FiltersItem`s.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 846 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVn6DpABybXUmYMwvr:-MlVn6DpABybXUmYMwvs:b3m7gp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/index_constraints.go#L846)):*
> ```Go
> ) (tight bool) {
> 	size := len(disjunctions)
> 	mid := size / 2
> ```

nit: you can move this below the `if size == 1 { }` block
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 958 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVpQhn13oxE2Wbk329:-MlVpQhn13oxE2Wbk32A:bg1841r) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/index_constraints.go#L958)):*
> ```Go
> //    by getMaxSimplifyPrefix). So `[/1/2 - /1/2]` is contained in the
> //    expression span and we can simplify `@2 = 2` to `true`.
> // orExprDepth tracks the depth of child OrExprs under a top-level OrExpr.
> ```

nit: add a blank line above this new one.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 960 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVo9sBDnnwFfxvdpgX:-MlVo9sBDnnwFfxvdpgY:b-w4u71x) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/index_constraints.go#L960)):*
> ```Go
> // orExprDepth tracks the depth of child OrExprs under a top-level OrExpr.
> func (c *indexConstraintCtx) simplifyFilter(
> 	scalar opt.ScalarExpr, final *constraint.Constraint, maxSimplifyPrefix int, orExprDepth int,
> ```

This is never decremented, only reset to `0` for some recursive calls, so I think this could be a bool instead, like `nestedUnderOrExpr bool`.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1016 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVp0YLEzUhmcNdQoj_:-MlVp0YLEzUhmcNdQoja:b-3equ4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/index_constraints.go#L1016)):*
> ```Go
> 
> 		left := c.simplifyFilter(t.Left, final, maxSimplifyPrefix, leftOrExprDepth)
> 		right := c.simplifyFilter(t.Right, final, maxSimplifyPrefix, rightOrExprDepth)
> ```

If you switch the argument to a bool like I suggest above, these recursive calls can be simplified to `c.SimplifyFilter(___, final, maxSimplifyPrefix, true /* nestedUnderOrExpr */)` I think.
___
*[pkg/sql/opt/memo/constraint_builder.go, line 452 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVqdvdAbEIByLFN3Qv:-MlVqdvdAbEIByLFN3Qw:b-1limxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/memo/constraint_builder.go#L452)):*
> ```Go
> ) (_ *constraint.Set, tight bool) {
> 	size := len(disjunctions)
> 	mid := size / 2
> ```

nit: `mid` can be declared below `if size == 1 { }`
___
*[pkg/sql/opt/memo/constraint_builder.go, line 551 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVprAyBKduu_l5so-9:-MlVprAyBKduu_l5so-A:b99brn) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/memo/constraint_builder.go#L551)):*
> ```Go
> 	case *OrExpr:
> 		var filters FiltersExpr
> 		filters = make(FiltersExpr, 0, 2)
> ```

nit: use `[]opt.ScalarExpr` here.
___
*[pkg/sql/opt/memo/constraint_builder.go, line 552 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVqBp09yuTJIIP0PKO:-MlVqBp09yuTJIIP0PKP:b-ka0ius) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/memo/constraint_builder.go#L552)):*
> ```Go
> 		var filters FiltersExpr
> 		filters = make(FiltersExpr, 0, 2)
> 		var collectDisjunctions func(e opt.ScalarExpr)
> ```

nit: since you're doing this in two places, considering making a helper function (probably in `pkg/sql/opt/memo/expr.go` like `CollectContiguousOrExprs`.


<!-- Sent from Reviewable.io -->

2021-10-10 22:54 UTC, msirek reviewed
Thanks, I've collected benchstat results with 5, 20, 100 and 400 ORed predicates.  It looks like the bug did not affect parameterized queries.
```
benchstat ored-preds-5.old ored-preds-5.new2
name                                          old time/op  new time/op  delta
Phases/ored-preds-5/Simple/Parse-32            275µs ± 2%   277µs ± 3%    ~     (p=0.690 n=5+5)
Phases/ored-preds-5/Simple/OptBuildNoNorm-32   499µs ± 4%   492µs ± 2%    ~     (p=0.310 n=5+5)
Phases/ored-preds-5/Simple/OptBuildNorm-32     502µs ± 2%   500µs ± 3%    ~     (p=0.690 n=5+5)
Phases/ored-preds-5/Simple/Explore-32          631µs ± 2%   610µs ± 2%  -3.37%  (p=0.008 n=5+5)
Phases/ored-preds-5/Simple/ExecBuild-32        676µs ± 2%   639µs ± 3%  -5.43%  (p=0.008 n=5+5)
Phases/ored-preds-5/Prepared/ExecBuild-32     21.8µs ± 3%  21.7µs ± 5%    ~     (p=0.841 n=5+5)

benchstat ored-preds-20.old ored-preds-20.new2
name                                           old time/op  new time/op  delta
Phases/ored-preds-20/Simple/Parse-32           1.06ms ± 3%  1.03ms ± 2%     ~     (p=0.056 n=5+5)
Phases/ored-preds-20/Simple/OptBuildNoNorm-32  1.92ms ± 3%  1.75ms ± 2%   -8.95%  (p=0.008 n=5+5)
Phases/ored-preds-20/Simple/OptBuildNorm-32    1.92ms ± 2%  1.75ms ± 3%   -8.50%  (p=0.008 n=5+5)
Phases/ored-preds-20/Simple/Explore-32         3.27ms ± 2%  2.13ms ± 4%  -34.86%  (p=0.008 n=5+5)
Phases/ored-preds-20/Simple/ExecBuild-32       3.28ms ± 2%  2.18ms ± 4%  -33.47%  (p=0.008 n=5+5)
Phases/ored-preds-20/Prepared/ExecBuild-32     55.2µs ± 3%  55.2µs ± 4%     ~     (p=1.000 n=5+5)

benchstat ored-preds-100.old ored-preds-100.new2
name                                            old time/op  new time/op  delta
Phases/ored-preds-100/Simple/Parse-32           5.14ms ± 2%  5.19ms ± 5%     ~     (p=0.548 n=5+5)
Phases/ored-preds-100/Simple/OptBuildNoNorm-32  12.7ms ± 4%   8.5ms ± 5%  -32.86%  (p=0.008 n=5+5)
Phases/ored-preds-100/Simple/OptBuildNorm-32    12.9ms ± 6%   8.6ms ± 3%  -33.54%  (p=0.008 n=5+5)
Phases/ored-preds-100/Simple/Explore-32          107ms ± 3%    11ms ± 4%  -89.99%  (p=0.008 n=5+5)
Phases/ored-preds-100/Simple/ExecBuild-32        105ms ± 4%    11ms ± 4%  -89.77%  (p=0.008 n=5+5)
Phases/ored-preds-100/Prepared/ExecBuild-32      226µs ± 4%   222µs ± 5%     ~     (p=0.548 n=5+5)

benchstat ored-preds-400.old ored-preds-400.new2
name                                            old time/op  new time/op  delta
Phases/ored-preds-400/Simple/Parse-32           21.8ms ± 3%  21.3ms ± 4%     ~     (p=0.421 n=5+5)
Phases/ored-preds-400/Simple/OptBuildNoNorm-32   108ms ± 1%    35ms ± 1%  -67.41%  (p=0.008 n=5+5)
Phases/ored-preds-400/Simple/OptBuildNorm-32     108ms ± 4%    36ms ± 3%  -66.98%  (p=0.008 n=5+5)
Phases/ored-preds-400/Simple/Explore-32          5.24s ± 1%   0.04s ± 2%  -99.15%  (p=0.008 n=5+5)
Phases/ored-preds-400/Simple/ExecBuild-32        5.24s ± 1%   0.05s ± 4%  -99.14%  (p=0.008 n=5+5)
Phases/ored-preds-400/Prepared/ExecBuild-32      901µs ± 3%   874µs ± 4%     ~     (p=0.095 n=5+5)

benchstat ored-preds-using-params-5.old2 ored-preds-using-params-5.new2
name                                                                   old time/op  new time/op  delta
Phases/ored-preds-using-params-5/Simple/Parse-32                        284µs ± 3%   270µs ± 2%  -5.26%  (p=0.008 n=5+5)
Phases/ored-preds-using-params-5/Simple/OptBuildNoNorm-32               446µs ± 4%   443µs ± 4%    ~     (p=1.000 n=5+5)
Phases/ored-preds-using-params-5/Simple/OptBuildNorm-32                 431µs ± 2%   427µs ± 1%    ~     (p=0.310 n=5+5)
Phases/ored-preds-using-params-5/Simple/Explore-32                      479µs ± 5%   468µs ± 3%    ~     (p=0.310 n=5+5)
Phases/ored-preds-using-params-5/Simple/ExecBuild-32                    499µs ± 2%   485µs ± 2%    ~     (p=0.095 n=5+5)
Phases/ored-preds-using-params-5/Prepared/AssignPlaceholdersNoNorm-32  59.5µs ± 5%  61.0µs ± 1%    ~     (p=0.151 n=5+5)
Phases/ored-preds-using-params-5/Prepared/AssignPlaceholdersNorm-32    41.9µs ± 2%  42.2µs ± 4%    ~     (p=0.690 n=5+5)
Phases/ored-preds-using-params-5/Prepared/Explore-32                   79.8µs ± 4%  78.9µs ± 4%    ~     (p=0.548 n=5+5)
Phases/ored-preds-using-params-5/Prepared/ExecBuild-32                 95.1µs ± 4%  94.4µs ± 3%    ~     (p=0.690 n=5+5)

benchstat ored-preds-using-params-20.old2 ored-preds-using-params-20.new2
name                                                                    old time/op  new time/op  delta
Phases/ored-preds-using-params-20/Simple/Parse-32                       1.05ms ± 4%  1.05ms ± 2%    ~     (p=1.000 n=5+5)
Phases/ored-preds-using-params-20/Simple/OptBuildNoNorm-32              1.48ms ± 2%  1.50ms ± 2%    ~     (p=0.222 n=5+5)
Phases/ored-preds-using-params-20/Simple/OptBuildNorm-32                1.43ms ± 2%  1.37ms ± 1%  -3.92%  (p=0.008 n=5+5)
Phases/ored-preds-using-params-20/Simple/Explore-32                     1.42ms ± 4%  1.42ms ± 3%    ~     (p=0.841 n=5+5)
Phases/ored-preds-using-params-20/Simple/ExecBuild-32                   1.46ms ± 3%  1.45ms ± 3%    ~     (p=0.690 n=5+5)
Phases/ored-preds-using-params-20/Prepared/AssignPlaceholdersNoNorm-32   174µs ± 4%   176µs ± 2%    ~     (p=0.841 n=5+5)
Phases/ored-preds-using-params-20/Prepared/AssignPlaceholdersNorm-32    81.0µs ± 2%  80.7µs ± 7%    ~     (p=0.421 n=5+5)
Phases/ored-preds-using-params-20/Prepared/Explore-32                    118µs ± 5%   118µs ± 6%    ~     (p=0.690 n=5+5)
Phases/ored-preds-using-params-20/Prepared/ExecBuild-32                  131µs ± 4%   135µs ± 3%    ~     (p=0.056 n=5+5)

benchstat ored-preds-using-params-100.old2 ored-preds-using-params-100.new2
name                                                                     old time/op  new time/op  delta
Phases/ored-preds-using-params-100/Simple/Parse-32                       5.09ms ± 2%  5.10ms ± 2%   ~     (p=0.690 n=5+5)
Phases/ored-preds-using-params-100/Simple/OptBuildNoNorm-32              6.95ms ± 2%  7.07ms ± 2%   ~     (p=0.151 n=5+5)
Phases/ored-preds-using-params-100/Simple/OptBuildNorm-32                6.37ms ± 2%  6.44ms ± 3%   ~     (p=0.421 n=5+5)
Phases/ored-preds-using-params-100/Simple/Explore-32                     6.50ms ± 3%  6.50ms ± 1%   ~     (p=1.000 n=5+5)
Phases/ored-preds-using-params-100/Simple/ExecBuild-32                   6.47ms ± 2%  6.59ms ± 2%   ~     (p=0.095 n=5+5)
Phases/ored-preds-using-params-100/Prepared/AssignPlaceholdersNoNorm-32   780µs ± 4%   804µs ± 2%   ~     (p=0.095 n=5+5)
Phases/ored-preds-using-params-100/Prepared/AssignPlaceholdersNorm-32     282µs ± 2%   288µs ± 4%   ~     (p=0.151 n=5+5)
Phases/ored-preds-using-params-100/Prepared/Explore-32                    327µs ± 3%   327µs ± 3%   ~     (p=1.000 n=5+5)
Phases/ored-preds-using-params-100/Prepared/ExecBuild-32                  343µs ± 3%   352µs ± 4%   ~     (p=0.151 n=5+5)

benchstat ored-preds-using-params-400.old2 ored-preds-using-params-400.new2
name                                                                     old time/op  new time/op  delta
Phases/ored-preds-using-params-400/Simple/Parse-32                       21.6ms ± 3%  20.9ms ± 3%   ~     (p=0.056 n=5+5)
Phases/ored-preds-using-params-400/Simple/OptBuildNoNorm-32              29.3ms ± 2%  28.8ms ± 4%   ~     (p=0.310 n=5+5)
Phases/ored-preds-using-params-400/Simple/OptBuildNorm-32                27.0ms ± 4%  26.4ms ± 3%   ~     (p=0.310 n=5+5)
Phases/ored-preds-using-params-400/Simple/Explore-32                     27.0ms ± 2%  26.9ms ± 2%   ~     (p=0.548 n=5+5)
Phases/ored-preds-using-params-400/Simple/ExecBuild-32                   26.8ms ± 2%  26.4ms ± 1%   ~     (p=0.095 n=5+5)
Phases/ored-preds-using-params-400/Prepared/AssignPlaceholdersNoNorm-32  3.17ms ± 1%  3.19ms ± 3%   ~     (p=0.222 n=5+5)
Phases/ored-preds-using-params-400/Prepared/AssignPlaceholdersNorm-32    1.10ms ± 4%  1.11ms ± 5%   ~     (p=0.690 n=5+5)
Phases/ored-preds-using-params-400/Prepared/Explore-32                   1.17ms ± 1%  1.13ms ± 3%   ~     (p=0.056 n=5+5)
Phases/ored [...]

2021-10-16 18:23 UTC, rytaft reviewed
Really nice work!! Sorry it took me so long to get to this. Just nits from me below.

> Reviewed 1 of 4 files at r1, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-:-Mm9KnB31M9-Cbq_RVqw:byrbyxo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @msirek)

___
*[-- commits, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9DByM2Jy2KTDkchO4):*
nit: keep track the -> keep track of the
___
*[-- commits, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9DKF42k4-2T7l9JVz):*
You should add a release note with tag `Release note (performance improvement): ...` explaining how this will improve performance for end users
___
*[pkg/sql/opt/bench/bench_test.go, line 578 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9E9Vl2Rggof9MOG-k:-Mm9E9Vl2Rggof9MOG-l:b-rx8vmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/bench/bench_test.go#L578)):*
> ```Go
> 	var buf bytes.Buffer
> 	buf.WriteString(`SELECT * FROM stock WHERE `)
> 	or := ""
> ```

nit: maybe call this "sep" instead of "or" -- I think it would be a bit more idiomatic
___
*[pkg/sql/opt/bench/bench_test.go, line 598 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9EU4k0QCwHmJNcwtx:-Mm9EU4k0QCwHmJNcwty:bhmbp7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/bench/bench_test.go#L598)):*
> ```Go
> 	var value int
> 	for i := 1; i <= numParams; i++ {
> 		parameterValues[i-1] = value
> ```

looks like `value` is always 0 -- is that what you intended?
___
*[pkg/sql/opt/bench/bench_test.go, line 612 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9Drr11ODkXHMAZmlN:-Mm9Drr11ODkXHMAZmlO:b-ob2hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/bench/bench_test.go#L612)):*
> ```Go
> // makeOredPredsTests constructs a set of non-parameterized queries and
> // parameterized queries with a certain number of ORed predicates as indicated
> // in the testSizes array and test name suffix.  The test names produced are:
> ```

nit: remove space after period
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1016 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVp0YLEzUhmcNdQoj_:-Mm9HN_zE8zZp-kzpFbr:bs56agd) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/index_constraints.go#L1016)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> (___, fina
nestedUnderOrExpr should only be true for an OrExpr that's the child of an OrExpr, so I believe we still need to check the Op kind to make sure makeSpansForExpr is called on non-OrExpr children.
</blockquote></details>

I think it would be clearer if you take @mgartner's suggestion, and if needed you could add a check that the current expr is an `OrExpr` when `nestedUnderOrExpr` is true.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 825 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9FDgG9JGHXVE2WWlW:-Mm9FDgG9JGHXVE2WWlX:b-mlhzas) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/idxconstraint/index_constraints.go#L825)):*
> ```Go
> ) (tight bool) {
> 	or := e.(*memo.OrExpr)
> 	var disjunctions = memo.CollectContiguousOrExprs(or)
> ```

nit: why not just do `disjunctions := memo.CollectContiguousOrExprs(or)`?
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 959 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9GUoUCAeYi_5c1hDr:-Mm9GUoUCAeYi_5c1hDs:b-mbtze7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/idxconstraint/index_constraints.go#L959)):*
> ```Go
> 	switch t := scalar.(type) {
> 	case *memo.AndExpr:
> 		left := c.simplifyFilter(t.Left, final, maxSimplifyPrefix, false)
> ```

nit: `, false /* nestedUnderOrExpr */)`
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9HjU5-d_4sKJ83d8L:-Mm9HjU5-d_4sKJ83d8M:b-mbtze7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/idxconstraint/index_constraints.go#L1135)):*
> ```Go
> 	for i := range ic.requiredFilters {
> 		prefix := ic.getMaxSimplifyPrefix(&ic.constraint)
> 		condition := ic.simplifyFilter(ic.requiredFilters[i].Condition, &ic.constraint, prefix, false)
> ```

nit: `, false /* nestedUnderOrExpr */)`
___
*[pkg/sql/opt/idxconstraint/testdata/many_preds, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVF88M-aUQw3UcULPq:-Mm9HqgnDX3ARHrVrgTZ:bwlemmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/testdata/many_preds#L1)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Good point.  The benchmark test can check whether a query with a large number of ORed predicates can run within a timeout, so this functional test doesn't need to be so large.  I've reduced the number of predicates.  This type of functionality test may even be covered by pre-existing tests.  If you think it's unnecessary I can remove the test entirely.
</blockquote></details>

This seems significantly smaller than your first iteration, so this is probably fine to leave as-is (assuming it runs quickly now).
___
*[pkg/sql/opt/memo/constraint_builder.go, line 550 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9JdSE6T9v-R0cgJoy:-Mm9JdSE6T9v-R0cgJoz:b1t03yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/memo/constraint_builder.go#L550)):*
> ```Go
> 
> 	case *OrExpr:
> 		var disjunctions = CollectContiguousOrExprs(e)
> ```

nit: why not use `disjunctions := `?


<!-- Sent from Reviewable.io -->

2021-10-18 06:22 UTC, msirek reviewed
No worries.  Thanks for reviewing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-:-MmGqPjN8gu8vLSMiUUL:b-vy38qs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rytaft)

___
*[-- commits, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9DByM2Jy2KTDkchO4):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: keep track the -> keep track of the
</blockquote></details>

Fixed.
___
*[-- commits, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9DKF42k4-2T7l9JVz):*
> Release note (performance improvement):
Added the following:
```
Release note (performance improvement): Queries with many ORed WHERE    
clause predicates may take an excessive amount of time for the optimizer
to process, especially if the predicates involve index columns, and if  
there are more than 1000 predicates (which may happen with
application-generated SQL). This fix optimizes the processing of SQL 
with many ORed predicates to make sure a query plan can be generated in
seconds instead of minutes or hours.
```
___
*[pkg/sql/opt/bench/bench_test.go, line 578 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9E9Vl2Rggof9MOG-k:-MmGvlK2BQ2nkUab6VTG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/bench/bench_test.go#L578)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: maybe call this "sep" instead of "or" -- I think it would be a bit more idiomatic
</blockquote></details>

Done.
___
*[pkg/sql/opt/bench/bench_test.go, line 598 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9EU4k0QCwHmJNcwtx:-MmGwSnaBBU9VHpIGEeU:b70pg4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/bench/bench_test.go#L598)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

looks like `value` is always 0 -- is that what you intended?
</blockquote></details>

Good catch.  I actually meant to use a different value for each parameter, so I'll just use 'i' here, though it might not matter which value is used.
___
*[pkg/sql/opt/bench/bench_test.go, line 612 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9Drr11ODkXHMAZmlN:-MmGxIB3EjoxNiGMBuU2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/bench/bench_test.go#L612)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: remove space after period
</blockquote></details>

Done.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1016 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVp0YLEzUhmcNdQoj_:-MmGzYPw71oz7vJxhcXG:b-bzb8ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/index_constraints.go#L1016)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think it would be clearer if you take @mgartner's suggestion, and if needed you could add a check that the current expr is an `OrExpr` when `nestedUnderOrExpr` is true.
</blockquote></details>

OK, I modified the description of nestedUnderOrOp from this:
`nestedUnderOrExpr indicates if we are processing an OrExpr which is the child of another OrExpr.`
to this:
`nestedUnderOrExpr indicates if we are processing a ScalarExpr which is the child of an OrExpr.`

Then pass nestedUnderOrExpr as always true on lines 1009 and 1010.  
The condition which determines if makeSpansForExpr is called is modified to:
`if scalar.Op() != opt.OrOp || !nestedUnderOrExpr {`
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 825 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9FDgG9JGHXVE2WWlW:-MmGxW1xAJUi0yDGxliQ:bdwf45d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/idxconstraint/index_constraints.go#L825)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: why not just do `disjunctions := memo.CollectContiguousOrExprs(or)`?
</blockquote></details>

Done.  I think it ended up this way from some refactoring.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 959 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9GUoUCAeYi_5c1hDr:-MmGy7TT5erhJbdv1eVn:b-59gqw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/idxconstraint/index_constraints.go#L959)):*
> /* nestedUnderOrExpr */
Added the parameter name comment.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9HjU5-d_4sKJ83d8L:-MmH-e9yA3gHWLQAPAZ4:b-qea85w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/idxconstraint/index_constraints.go#L1135)):*
> /* nestedUnderOrExpr */
Done.
___
*[pkg/sql/opt/idxconstraint/testdata/many_preds, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVF88M-aUQw3UcULPq:-MmH00Ly2smNgnuWS-TW:bkuma96) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/testdata/many_preds#L1)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This seems significantly smaller than your first iteration, so this is probably fine to leave as-is (assuming it runs quickly now).
</blockquote></details>

OK.  Yes, it does run quickly.  The previous test also ran quickly.  I guess the point was it was excessively long (too many lines), so maybe if we need to test that, use a different approach.
___
*[pkg/sql/opt/memo/constraint_builder.go, line 550 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9JdSE6T9v-R0cgJoy:-MmH1m1wAbxzPSbLSP6_:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3686ad7b1ef84a078396fbe387592a41be669eed/pkg/sql/opt/memo/constraint_builder.go#L550)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: why not use `disjunctions := `?
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-10-18 14:23 UTC, rytaft reviewed
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @msirek)

___
*[-- commits, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9DKF42k4-2T7l9JVz):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> Release note (performance improvement):
Added the following:
```
Release note (performance improvement): Queries with many ORed WHERE    
clause predicates may take an excessive amount of time for the optimizer
to process, especially if the predicates involve index columns, and if  
there are more than 1000 predicates (which may happen with
application-generated SQL). This fix optimizes the processing of SQL 
with many ORed predicates to make sure a query plan can be generated in
seconds instead of minutes or hours.
```
</blockquote></details>

This is good, but I'd tweak the language a bit so it sounds more like a release note, i.e. emphasizing what we fixed. For example:

```
  Release note (performance improvement): Queries with many ORed WHERE
  clause predicates previously took an excessive amount of time for the optimizer
  to process, especially if the predicates involved index columns, and if
  there were more than 1000 predicates (which could happen with
  application-generated SQL). To fix this, we optimized the processing of SQL
  with many ORed predicates to make sure a query plan can be generated in
  seconds instead of minutes or hours.

```
___
*[pkg/sql/opt/bench/bench_test.go, line 305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlV83Ly3ca1WDXCuPmy:-MmIk5OV7RBj_VlS0Jiw:bjmfb6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/bench/bench_test.go#L305)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Good idea.  I've changed the benchmarks to test different numbers of ORed terms, both parameterized and non-parameterized.  Currently it's testing 5, 20, 100 and 400 terms, but this can be changed if you think it's too many variations (would add too much time to the benchmarks).
</blockquote></details>

How much time does it add to the benchmarks? Benchmarks are not run as part of CI so it's not quite as critical that they run quickly, but we do want to avoid adding more time than necessary.
___
*[pkg/sql/opt/idxconstraint/testdata/many_preds, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVF88M-aUQw3UcULPq:-MmIkoZHEBusNAUUQta9:b-lbb8uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/testdata/many_preds#L1)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK.  Yes, it does run quickly.  The previous test also ran quickly.  I guess the point was it was excessively long (too many lines), so maybe if we need to test that, use a different approach.
</blockquote></details>

"Quickly" is all relative, of course. I think you mentioned that the test was taking 1 second before? That's obviously a huge improvement from what it would have taken without your change, but it does mean that every time we run these tests (which is every CI run) it will add 1 second to the testing time. Although 1 second doesn't seem like a big deal, it does add up over time, and as we add more and more tests it starts to hamper productivity if each one adds a second to the total runtime. 

Anyway, I'm guessing that this is much less than 1 second now, but if not, I think you can just remove this test (since it seems to be covered by the benchmarks and other functional tests).


<!-- Sent from Reviewable.io -->

2021-10-18 16:54 UTC, mgartner approved these changes
> Reviewed 1 of 4 files at r1, 2 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @msirek, and @rytaft)

___
*[-- commits, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVjDM23q-iFLkZKw3q):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: The alignment here still looks off to me.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1016 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVp0YLEzUhmcNdQoj_:-MmJIn793yipgBXGSl09:by3bluq) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/index_constraints.go#L1016)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, I modified the description of nestedUnderOrOp from this:
`nestedUnderOrExpr indicates if we are processing an OrExpr which is the child of another OrExpr.`
to this:
`nestedUnderOrExpr indicates if we are processing a ScalarExpr which is the child of an OrExpr.`

Then pass nestedUnderOrExpr as always true on lines 1009 and 1010.  
The condition which determines if makeSpansForExpr is called is modified to:
`if scalar.Op() != opt.OrOp || !nestedUnderOrExpr {`
</blockquote></details>

I like it! The name `nestedUnderOrExpr` is now more fitting.


<!-- Sent from Reviewable.io -->

2021-10-18 17:04 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rytaft)

___
*[-- commits, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9DKF42k4-2T7l9JVz):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is good, but I'd tweak the language a bit so it sounds more like a release note, i.e. emphasizing what we fixed. For example:

```
  Release note (performance improvement): Queries with many ORed WHERE
  clause predicates previously took an excessive amount of time for the optimizer
  to process, especially if the predicates involved index columns, and if
  there were more than 1000 predicates (which could happen with
  application-generated SQL). To fix this, we optimized the processing of SQL
  with many ORed predicates to make sure a query plan can be generated in
  seconds instead of minutes or hours.

```
</blockquote></details>

Done.
___
*[pkg/sql/opt/bench/bench_test.go, line 305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlV83Ly3ca1WDXCuPmy:-MmJHst2EqVNbZtawuwY:bltq024) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/bench/bench_test.go#L305)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

How much time does it add to the benchmarks? Benchmarks are not run as part of CI so it's not quite as critical that they run quickly, but we do want to avoid adding more time than necessary.
</blockquote></details>

On my machine it adds 96 seconds.  There are 8 variations of the test (4 parameterized, 4 non-parameterized), so if this is too much time we could reduce the number of variations.
___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1016 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVp0YLEzUhmcNdQoj_:-MmJKgyq06Gkb0L-gwrq:b-7tdf7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/index_constraints.go#L1016)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I like it! The name `nestedUnderOrExpr` is now more fitting.
</blockquote></details>

agree
___
*[pkg/sql/opt/idxconstraint/testdata/many_preds, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVF88M-aUQw3UcULPq:-MmJJKij2h_kiU6HHOAX:b-e59gcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/testdata/many_preds#L1)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

"Quickly" is all relative, of course. I think you mentioned that the test was taking 1 second before? That's obviously a huge improvement from what it would have taken without your change, but it does mean that every time we run these tests (which is every CI run) it will add 1 second to the testing time. Although 1 second doesn't seem like a big deal, it does add up over time, and as we add more and more tests it starts to hamper productivity if each one adds a second to the total runtime. 

Anyway, I'm guessing that this is much less than 1 second now, but if not, I think you can just remove this test (since it seems to be covered by the benchmarks and other functional tests).
</blockquote></details>

The timing I got is about .05 seconds.  But I don't know if this includes time to create the table or parse the test.  It does look like other tests such as idxconstraint/testdata/misc already test ORed terms, so it could be that this test adds no value.  Let me know if you think I should remove it.


<!-- Sent from Reviewable.io -->

2021-10-18 20:09 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @msirek)

___
*[-- commits, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9DKF42k4-2T7l9JVz):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look like you pushed your update.
___
*[pkg/sql/opt/bench/bench_test.go, line 305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlV83Ly3ca1WDXCuPmy:-MmJz30mDnXYfD_4Ucd8:bprpykr) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/bench/bench_test.go#L305)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

On my machine it adds 96 seconds.  There are 8 variations of the test (4 parameterized, 4 non-parameterized), so if this is too much time we could reduce the number of variations.
</blockquote></details>

Yea that feels a little bit excessive (and I'm not sure we gain a lot of additional useful info by having 8 configs). Maybe choose 1 or 2 configs to run with parameterized and non-parameterized, for a total of 2 or 4. If we can already see a significant improvement with a smaller number of OR clauses, then there shouldn't be a need to test a much larger number.
___
*[pkg/sql/opt/idxconstraint/testdata/many_preds, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVF88M-aUQw3UcULPq:-MmK-lfh0Go6yjuFw16S:be7mc0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/testdata/many_preds#L1)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

The timing I got is about .05 seconds.  But I don't know if this includes time to create the table or parse the test.  It does look like other tests such as idxconstraint/testdata/misc already test ORed terms, so it could be that this test adds no value.  Let me know if you think I should remove it.
</blockquote></details>

I think 0.05s is fine, I kind of like this test in its reduced form. Thanks for measuring!


<!-- Sent from Reviewable.io -->

2021-10-18 21:54 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rytaft)

___
*[-- commits, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVjDM23q-iFLkZKw3q):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: The alignment here still looks off to me.
</blockquote></details>

I had only fixed the text in Github because I thought that got propagated to git in the final merge.  It's corrected in the commit message now too.
___
*[-- commits, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9DKF42k4-2T7l9JVz):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Doesn't look like you pushed your update.
</blockquote></details>

Sorry, I was under the impression that the comments inside the pull request get picked up for the final commit, so didn't directly modify the commit message. I've updated the commit message now too.
___
*[pkg/sql/opt/bench/bench_test.go, line 305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlV83Ly3ca1WDXCuPmy:-MmKJ4gM5Yb9BJyM-Emt:b-ltgv7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/bench/bench_test.go#L305)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea that feels a little bit excessive (and I'm not sure we gain a lot of additional useful info by having 8 configs). Maybe choose 1 or 2 configs to run with parameterized and non-parameterized, for a total of 2 or 4. If we can already see a significant improvement with a smaller number of OR clauses, then there shouldn't be a need to test a much larger number.
</blockquote></details>

OK, I've kept only the variations which use 100 predicates because it is short-running, and also shows a large percentage improvement.  I added a comment on how to test more variations.
___
*[pkg/sql/opt/idxconstraint/testdata/many_preds, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlVF88M-aUQw3UcULPq:-MmKESRh90R4GiscNjsJ:bb74ce2) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/idxconstraint/testdata/many_preds#L1)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think 0.05s is fine, I kind of like this test in its reduced form. Thanks for measuring!
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2021-10-18 22:02 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Great work, and thanks again for the contribution!

I'll go ahead and merge this now.

bors r+

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-:-MmKQDj07cF7MMuQwLRO:b-t8ivwl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

___
*[-- commits, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-Mm9DKF42k4-2T7l9JVz):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Sorry, I was under the impression that the comments inside the pull request get picked up for the final commit, so didn't directly modify the commit message. I've updated the commit message now too.
</blockquote></details>

No worries!
___
*[pkg/sql/opt/bench/bench_test.go, line 305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71247#-MlV83Ly3ca1WDXCuPmy:-MmKQ1I51gRZFoJMWTS9:b-qn06j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/507eeb1c10311b103d2fa06788647ff8e9baa094/pkg/sql/opt/bench/bench_test.go#L305)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, I've kept only the variations which use 100 predicates because it is short-running, and also shows a large percentage improvement.  I added a comment on how to test more variations.
</blockquote></details>

Great - thanks!


<!-- Sent from Reviewable.io -->

2021-10-18 22:45 UTC, merged