backupccl: support preserving privilege grants for specific users
cockroachdb/cockroach pull request #71332
Opened 2021-10-08 18:05 UTC by gh-casper

Previously during restore, these grants are wiped and replaced with default privileges as if the restore had created new tables.

Now we add an option 'preserve_grants_for' to allow preserve grants for specific users if they exist in the backup.

Fixes:  cockroach#45359

Release note: None

2021-10-08 18:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/71332)
<!-- Reviewable:end -->

2021-10-14 21:38 UTC, RichardJCai requested changes
> Reviewed 7 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71332)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @gh-casper, and @shermanCRL)

___
*[pkg/ccl/backupccl/restore_job.go, line 1077 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71332#-Mm-gyufB3cqezMFQJq3:-Mm-gyugBYAS6lgQh22c:b4rjknu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d19610dae4ced671d1c98773907e7b0892ef4749/pkg/ccl/backupccl/restore_job.go#L1077)):*
> ```Go
> 	}
> 	for u := range users {
> 		return errors.Errorf("Failed to keep privilege grants for non-existent user %s in the restoring cluster", u.Normalized())
> ```

This will only return the error for the first user right?

Should we accumulate the users and return one error message outside the for loop?
___
*[pkg/ccl/backupccl/restore_job.go, line 1286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71332#-Mm-hYDU6jqKjY24iOW3:-Mm-hYDU6jqKjY24iOW4:bohzft3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d19610dae4ced671d1c98773907e7b0892ef4749/pkg/ccl/backupccl/restore_job.go#L1286)):*
> ```Go
> 			ctx context.Context, txn *kv.Txn, descsCol *descs.Collection,
> 		) error {
> 			err := checkUsersInRestoringCluster(ctx, txn, p, preserveGrantsForUsersMutable)
> ```

Do we really need this `preserveGrantsForUsersMutable` map? We can just check and users that match and add that to a list before using it to generate an error.
___
*[pkg/ccl/backupccl/restore_job.go, line 2559 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71332#-Mm-ii6u1Wle7cQHxSTT:-Mm-ii6u1Wle7cQHxSTU:b-sasvim) ([raw file](https://github.com/cockroachdb/cockroach/blob/d19610dae4ced671d1c98773907e7b0892ef4749/pkg/ccl/backupccl/restore_job.go#L2559)):*
> ```Go
> 			// Leave the privileges of the temp system tables as the default too.
> 			if descCoverage == tree.RequestedDescriptors || wrote.GetName() == restoreTempSystemDB {
> 				updatedPrivileges = &descpb.PrivilegeDescriptor{}
> ```

I'm a bit confused - why do we have to do this as opposed to using `wrote.GetPrivileges()`
___
*[pkg/ccl/backupccl/restore_job.go, line 2563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71332#-Mm-iaHo9DmylDiWTFnS:-Mm-iaHo9DmylDiWTFnT:b7feeat) ([raw file](https://github.com/cockroachdb/cockroach/blob/d19610dae4ced671d1c98773907e7b0892ef4749/pkg/ccl/backupccl/restore_job.go#L2563)):*
> ```Go
> 				preservePrivilegeGrantsForUsers(desc, updatedPrivileges, preserveGrantsForUsers)
> 			}
> 			// Restoring a table only.
> ```

I think this should either go to the right of the else if or inside the block.
___
*[pkg/ccl/backupccl/restore_job.go, line 2578 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71332#-Mm-ioXF-jp6O8HHGNnv:-Mm-ioXF-jp6O8HHGNnw:b-g76ljo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d19610dae4ced671d1c98773907e7b0892ef4749/pkg/ccl/backupccl/restore_job.go#L2578)):*
> ```Go
> 	case catalog.TypeDescriptor, catalog.DatabaseDescriptor:
> 		if descCoverage == tree.RequestedDescriptors {
> 			// Beside keeping the default privileges, we preserve grants for specified users as
> ```

nit: should be Besides keeping


<!-- Sent from Reviewable.io -->

2021-11-06 21:15 UTC, gh-casper reviewed
Sorry for the rebasing. Switch to full diff to avoid irrelevant changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71332#-:-Mnr5iIs21ICtjivR8h0:b-ulm07b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @RichardJCai, and @shermanCRL)

___
*[pkg/ccl/backupccl/restore_job.go, line 1077 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71332#-Mm-gyufB3cqezMFQJq3:-MnqywMr-dadDjRDWxxl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d19610dae4ced671d1c98773907e7b0892ef4749/pkg/ccl/backupccl/restore_job.go#L1077)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

This will only return the error for the first user right?

Should we accumulate the users and return one error message outside the for loop?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 1286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71332#-Mm-hYDU6jqKjY24iOW3:-Mnqz0HYDqc-GCILcs2_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d19610dae4ced671d1c98773907e7b0892ef4749/pkg/ccl/backupccl/restore_job.go#L1286)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Do we really need this `preserveGrantsForUsersMutable` map? We can just check and users that match and add that to a list before using it to generate an error.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 2559 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71332#-Mm-ii6u1Wle7cQHxSTT:-Mnr5gQ-CBpGq0xmHgOk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d19610dae4ced671d1c98773907e7b0892ef4749/pkg/ccl/backupccl/restore_job.go#L2559)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I'm a bit confused - why do we have to do this as opposed to using `wrote.GetPrivileges()`
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 2563 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71332#-Mm-iaHo9DmylDiWTFnS:-MnquIB2C7Y2Y-EkJNUV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d19610dae4ced671d1c98773907e7b0892ef4749/pkg/ccl/backupccl/restore_job.go#L2563)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think this should either go to the right of the else if or inside the block.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 14:51 UTC, shermanCRL commented
For my understanding: is it sufficient to match on SQL user name for this? If our assumption is that we are restoring into an existing cluster, from which the backup was made, can we guarantee that the SQL user of a given name is that same user that was backed up?

In other words, should we match on an ID instead? @dt

2022-03-25 23:08 UTC, closed without merging