sql: check DEFAULT clause for ALTER COLUMN...SET DATA TYPE
cockroachdb/cockroach pull request #71423
Opened 2021-10-11 21:04 UTC by e-mbrown

fixes https://github.com/cockroachdb/cockroach/issues/70605

Prior to this change it was possible to alter a columns type
in a way that was not compatible with the DEFAULT clause.

Release note (sql change): <what> <show> <why>

2021-10-11 21:04 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/71423)
<!-- Reviewable:end -->

2021-10-14 21:02 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/sql/alter_column_type.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mm-WVIv5c7r-Z6Vw-RF:-Mm-WVIv5c7r-Z6Vw-RG:b-v6iap2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8ed2c6f67abf29c01c3cbc1f6de7533bfb18ad/pkg/sql/alter_column_type.go#L133)):*
> ```Go
> 			"the requested type conversion (%s -> %s) requires an explicit USING expression",
> 			col.GetType().SQLString(), typ.SQLString())
> 	case schemachange.ColumnConversionTrivial:
> ```

i don't think we need to modify the "trivial" case -- we only get here if the old type and new type are identical.
___
*[pkg/sql/alter_column_type.go, line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mm-X8no3Wun9xVqIIeL:-Mm-X8no3Wun9xVqIIeM:bu3lqtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8ed2c6f67abf29c01c3cbc1f6de7533bfb18ad/pkg/sql/alter_column_type.go#L377)):*
> ```Go
> 			return errors.WithHintf(
> 				pgerror.New(pgcode.DatatypeMismatch, "cannot change column type with incompatible ON UPDATE expression"),
> 				`you may need to specify "USING %s::%s"`,
> ```

nit: we should remove the hint -- don't think it applies for this error

then the pgerror should be
```
pgerror.Newf(pgcode.DatatypeMismatch, "default for column %q cannot be cast automatically to type %s", colName, toType.SQLString())
```
___
*[pkg/sql/alter_column_type.go, line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mm-XEAf4t3yxpfRBqWs:-Mm-XEAf4t3yxpfRBqWt:b-h11p6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8ed2c6f67abf29c01c3cbc1f6de7533bfb18ad/pkg/sql/alter_column_type.go#L404)):*
> ```Go
> 		if !toType.Equivalent(typedExpr.ResolvedType()) {
> 			colName := col.ColName()
> 			return errors.WithHintf(
> ```

nit: remove the hint

and similar to above, can you make the pgerror include the column name and new type?

heads up, don't use colName.String() and use toType.SQLString()
___
*[pkg/sql/alter_column_type.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mm-Ys7V73RQluHHZE8G:-Mm-Ys7V73RQluHHZE8H:bq2kk0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8ed2c6f67abf29c01c3cbc1f6de7533bfb18ad/pkg/sql/alter_column_type.go#L425)):*
> ```Go
> 		Type:            toType,
> 		Nullable:        col.IsNullable(),
> 		DefaultExpr:     newColDefaultExpr,
> ```

there was a different bug we just noticed here -- can you make another PR to set OnUpdateExpr to fix https://github.com/cockroachdb/cockroach/issues/71571

as long as you are in this area :P 
___
*[pkg/sql/alter_column_type_test.go, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mm-ajslDEgWym_5BJfY:-Mm-ajslDEgWym_5BJfZ:b-lelwhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8ed2c6f67abf29c01c3cbc1f6de7533bfb18ad/pkg/sql/alter_column_type_test.go#L416)):*
> ```Go
> }
> 
> func TestSetDataTypeNotMatchingDefaultClause(t *testing.T) {
> ```

i think these tests would be a bit more readable as logic tests. can you add them to pkg/sql/logictest/testdata/logic_test/alter_column_type instead of here?


<!-- Sent from Reviewable.io -->

2021-10-21 17:04 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mm-WVIv5c7r-Z6Vw-RF:-MmYn68d3psG2uTFwm7i:b-ta8wwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8ed2c6f67abf29c01c3cbc1f6de7533bfb18ad/pkg/sql/alter_column_type.go#L133)):*
<details><summary><i>Previously, e-mbrown wrote…</i></summary><blockquote>

I was getting there with timestamp and timestamptz, in the issue that threw an error.
</blockquote></details>

hm yeah i see, it looks like it is an issue. for the same reason as https://github.com/cockroachdb/cockroach/issues/41775

@otan do you happen to know if the new assignment cast work is supposed to make DEFAULT clauses be able to handle this?

alternatively, maybe we should update the classifiers in https://github.com/cockroachdb/cockroach/blob/d556001291b4b64a37c2f83449cdaeedb54eb3dc/pkg/sql/schemachange/alter_column_type.go#L103-L109

so timestamp->timestamptz changes aren't "trivial"


<!-- Sent from Reviewable.io -->

2021-10-22 05:51 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @rafiss, and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mm-WVIv5c7r-Z6Vw-RF:-MmaXepk3KPlIpMT0BGP:b-f1g3r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8ed2c6f67abf29c01c3cbc1f6de7533bfb18ad/pkg/sql/alter_column_type.go#L133)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm yeah i see, it looks like it is an issue. for the same reason as https://github.com/cockroachdb/cockroach/issues/41775

@otan do you happen to know if the new assignment cast work is supposed to make DEFAULT clauses be able to handle this?

alternatively, maybe we should update the classifiers in https://github.com/cockroachdb/cockroach/blob/d556001291b4b64a37c2f83449cdaeedb54eb3dc/pkg/sql/schemachange/alter_column_type.go#L103-L109

so timestamp->timestamptz changes aren't "trivial"
</blockquote></details>

this should, in theory, work anyway because `current_timestamp` can return both a timestamp and timestamptz (https://github.com/cockroachdb/cockroach/blob/11f60dc551686e022e40d5789bca22d3b4db0afb/pkg/sql/sem/builtins/builtins.go#L6579-L6626), but yes it can get implicitly cast by postgres.


<!-- Sent from Reviewable.io -->

2021-10-26 19:53 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @rafiss, and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mmy95HFCQ5mAMIHcuVu:-Mmy95HFCQ5mAMIHcuVv:b-lrmgab) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f9f238cbf1bb46f9a3fdd08288ddcc15ecbaa94/pkg/sql/alter_column_type.go#L350)):*
> ```Go
> 		}
> 
> 		if !toType.Equivalent(typedExpr.ResolvedType()) {
> ```

actually, i think we can remove this Equivalent check.
___
*[pkg/sql/alter_column_type.go, line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mmy9DDI0kGwLz7v1kKW:-Mmy9DDJ63aF-De2NNRB:b67g8a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f9f238cbf1bb46f9a3fdd08288ddcc15ecbaa94/pkg/sql/alter_column_type.go#L363)):*
> ```Go
> 		newDefaultComputedExpr, err := castExpr.Eval(params.EvalContext())
> 		if err != nil {
> 			return err
> ```

here, we can return
```
pgerror.Wrapf(err, pgcode.DatatypeMismatch, "default for column %q cannot be cast automatically to type %s", colName, toType.SQLString())
```


<!-- Sent from Reviewable.io -->

2021-10-26 20:03 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mm-WVIv5c7r-Z6Vw-RF:-MmyBiS-677aLEJHa3ze:b-3ymhma) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8ed2c6f67abf29c01c3cbc1f6de7533bfb18ad/pkg/sql/alter_column_type.go#L133)):*
> current_timestamp can return both a timestamp and timestamptz

it can, but the problem in this issue is that the default clause is stored as `current_timestamp:::timestamptz` (with the type annotation)


<!-- Sent from Reviewable.io -->

2021-11-02 18:28 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnWr0ks-uQxlz8Mt_6D:-MnWr0ks-uQxlz8Mt_6E:b2cz6hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/61cca61cac459fb9dce615168f8a327f445edff8/pkg/sql/alter_column_type.go#L141)):*
> ```Go
> 			shadowColName := tabledesc.GenerateUniqueName(col.GetName(), nameExists)
> 			oldColComputeExpr := tree.CastExpr{
> 				Expr:       &tree.ColumnItem{ColumnName: tree.Name(col.GetName())},
> ```

this is just taking the column and casting it. did you mean to get the old DEFAULT expr and use that?

luckily, i think we can actually simplify this. as per marcus's comment in https://github.com/cockroachdb/cockroach/issues/70605#issuecomment-955084811 we shouldn't be rewriting the DEFAULT (or ON UPDATE) exprs anyway. so let's change this check so it just makes sure that the old type can be assignment casted to the new type.

so the trivial case will become something like:

```
if col.HasDefault() || col.HasOnUpdate() {
  if validCast := tree.ValidCast(col.GetType(), typ, tree.CastContextAssignment); !validCast {
    // return an error
  }
}
```

this means we no longer need the new `checkClause` and `columnSwap` functions
___
*[pkg/sql/alter_column_type.go, line 354 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnWsvAV-tAPATjKbL0C:-MnWsvAW2wBfT0LQu9NZ:b-yhntyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/61cca61cac459fb9dce615168f8a327f445edff8/pkg/sql/alter_column_type.go#L354)):*
> ```Go
> 		inverseExpr = tree.Serialize(&oldColComputeExpr)
> 	}
> 	print(newColComputeExpr)
> ```

nit: remove extra print
___
*[pkg/sql/alter_column_type.go, line 356 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnWt3S45jzDRy0u2V-k:-MnWt3S45jzDRy0u2V-l:b5vz0by) ([raw file](https://github.com/cockroachdb/cockroach/blob/61cca61cac459fb9dce615168f8a327f445edff8/pkg/sql/alter_column_type.go#L356)):*
> ```Go
> 	print(newColComputeExpr)
> 	// Create the default expression for the new column.
> 	newCol, err := checkClause(ctx, col, toType, shadowColName, params)
> ```

let's remove the new functions

then instead of rewriting the DefaultExpr, we add a check like the one i commented above

```
if col.HasDefault() || col.HasOnUpdate() {
  if validCast := tree.ValidCast(col.GetType(), typ, tree.CastContextAssignment); !validCast {
    return nil, pgerror.Wrapf(err, pgcode.DatatypeMismatch, "default for column %q cannot be cast automatically to type %s", colName, toType.SQLString())
  }
}
```
___
*[pkg/sql/alter_column_type.go, line 435 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnWtgd40AbWUGNFDYYC:-MnWtgd40AbWUGNFDYYD:bdkpc27) ([raw file](https://github.com/cockroachdb/cockroach/blob/61cca61cac459fb9dce615168f8a327f445edff8/pkg/sql/alter_column_type.go#L435)):*
> ```Go
> 		UsesSequenceIds: col.ColumnDesc().UsesSequenceIds,
> 		OwnsSequenceIds: col.ColumnDesc().OwnsSequenceIds,
> 		//ComputeExpr:     newColComputeExpr,
> ```

why was this commented?
___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 266 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnWu594BVCwkrZDaTci:-MnWu594BVCwkrZDaTcj:b7r62yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/61cca61cac459fb9dce615168f8a327f445edff8/pkg/sql/logictest/testdata/logic_test/alter_column_type#L266)):*
> ```
> )
> 
> # Ensure default expressions are casted correctly.
> ```

nit: update the comment


<!-- Sent from Reviewable.io -->

2021-11-02 18:31 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnWr0ks-uQxlz8Mt_6D:-MnWuz0ECVOOg4cXL-4O:bxglbsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/61cca61cac459fb9dce615168f8a327f445edff8/pkg/sql/alter_column_type.go#L141)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is just taking the column and casting it. did you mean to get the old DEFAULT expr and use that?

luckily, i think we can actually simplify this. as per marcus's comment in https://github.com/cockroachdb/cockroach/issues/70605#issuecomment-955084811 we shouldn't be rewriting the DEFAULT (or ON UPDATE) exprs anyway. so let's change this check so it just makes sure that the old type can be assignment casted to the new type.

so the trivial case will become something like:

```
if col.HasDefault() || col.HasOnUpdate() {
  if validCast := tree.ValidCast(col.GetType(), typ, tree.CastContextAssignment); !validCast {
    // return an error
  }
}
```

this means we no longer need the new `checkClause` and `columnSwap` functions
</blockquote></details>

actually, there should be separate cases for `HasDefault` and `HasOnUpdate`, so that the error message can be more helpful
___
*[pkg/sql/alter_column_type.go, line 356 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnWt3S45jzDRy0u2V-k:-MnWun3YCs9zoeT336IG:bxglbsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/61cca61cac459fb9dce615168f8a327f445edff8/pkg/sql/alter_column_type.go#L356)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

let's remove the new functions

then instead of rewriting the DefaultExpr, we add a check like the one i commented above

```
if col.HasDefault() || col.HasOnUpdate() {
  if validCast := tree.ValidCast(col.GetType(), typ, tree.CastContextAssignment); !validCast {
    return nil, pgerror.Wrapf(err, pgcode.DatatypeMismatch, "default for column %q cannot be cast automatically to type %s", colName, toType.SQLString())
  }
}
```
</blockquote></details>

actually, there should be separate cases for `HasDefault` and `HasOnUpdate`, so that the error message can be more helpful


<!-- Sent from Reviewable.io -->

2021-11-02 18:41 UTC, ajwerner commented
@postamar tagging you on this as you're playing in some of this area right now. Feel free to kick it back to me if you'd prefer.

2021-11-02 19:25 UTC, postamar commented
FYI this PR will probably have to be rebased on top of https://github.com/cockroachdb/cockroach/pull/72327

@ajwerner yes please, I'd like to kick it back to you.

2021-11-02 19:31 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mmy95HFCQ5mAMIHcuVu:-MnX7VAy1ZbE4g7Rnx5R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f9f238cbf1bb46f9a3fdd08288ddcc15ecbaa94/pkg/sql/alter_column_type.go#L350)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

actually, i think we can remove this Equivalent check.
</blockquote></details>

Done.
___
*[pkg/sql/alter_column_type.go, line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mmy9DDI0kGwLz7v1kKW:-MnX7VoW2Va2B3gsCTGf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f9f238cbf1bb46f9a3fdd08288ddcc15ecbaa94/pkg/sql/alter_column_type.go#L363)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

here, we can return
```
pgerror.Wrapf(err, pgcode.DatatypeMismatch, "default for column %q cannot be cast automatically to type %s", colName, toType.SQLString())
```

</blockquote></details>

Done.
___
*[pkg/sql/alter_column_type.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnWr0ks-uQxlz8Mt_6D:-MnX1u_O9GRrCzjpEUcH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61cca61cac459fb9dce615168f8a327f445edff8/pkg/sql/alter_column_type.go#L141)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

actually, there should be separate cases for `HasDefault` and `HasOnUpdate`, so that the error message can be more helpful
</blockquote></details>

Done.
___
*[pkg/sql/alter_column_type.go, line 356 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnWt3S45jzDRy0u2V-k:-MnX1hrDASRHkj34wXHI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61cca61cac459fb9dce615168f8a327f445edff8/pkg/sql/alter_column_type.go#L356)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

actually, there should be separate cases for `HasDefault` and `HasOnUpdate`, so that the error message can be more helpful
</blockquote></details>

Done.
___
*[pkg/sql/alter_column_type_test.go, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mm-ajslDEgWym_5BJfY:-MmPH3NCCmF-P7t7WIvK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8ed2c6f67abf29c01c3cbc1f6de7533bfb18ad/pkg/sql/alter_column_type_test.go#L416)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think these tests would be a bit more readable as logic tests. can you add them to pkg/sql/logictest/testdata/logic_test/alter_column_type instead of here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-02 23:33 UTC, rafiss reviewed
small nit, then looks good from my end

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-:-MnXzrdv8Pe8ge42Fwg7:b-aj6qli)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 266 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnXzbYFBazbDA_Q2r74:-MnXzbYFBazbDA_Q2r75:buqyy21) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c12c176f318d9740279cc1b7bf3465d74d2c50/pkg/sql/logictest/testdata/logic_test/alter_column_type#L266)):*
> ```
> )
> 
> # Ensure default expressions are casted correctly.
> ```

nit: the comment should now say "Ensure the type of the default column is checked"


<!-- Sent from Reviewable.io -->

2021-11-04 17:19 UTC, ajwerner reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, @postamar, @rafiss, and @RichardJCai)

___
*[-- commits, line 5 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-Mnfwdgh3DVNlp3AyOGx):*
nit: `typein`
___
*[pkg/sql/alter_column_type.go, line 132 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnfwvqKEmDcnhJGvbtB:-MnfwvqKEmDcnhJGvbtC:bjhm9zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c12c176f318d9740279cc1b7bf3465d74d2c50/pkg/sql/alter_column_type.go#L132)):*
> ```Go
> 			"the requested type conversion (%s -> %s) requires an explicit USING expression",
> 			col.GetType().SQLString(), typ.SQLString())
> 	case schemachange.ColumnConversionTrivial:
> ```

what about uses of the column in predicates for partial indexes? Also, is there a concern that the column type change might invalidate the index predicate? If you're changing a column that is in the index itself, I don't think we have a problem, but if the column is not in the index, then I don't think we'll re-backfill it. It seems like either we should disallow the change in that case or re-build partial indexes or indexes with computed expressions which reference it?

That brings me to another point, what sort of checking do we do on computed expressions or check constraints which reference this column? I think for check constraints it doesn't matter whether that changes because of the funky definition of check constraints, but it's a somewhat scary edge case for me. 


<!-- Sent from Reviewable.io -->

2021-11-04 19:45 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @otan, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 435 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnWtgd40AbWUGNFDYYC:-MngJyct-_beaHR7jTWL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61cca61cac459fb9dce615168f8a327f445edff8/pkg/sql/alter_column_type.go#L435)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why was this commented?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 20:09 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, @otan, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 132 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnfwvqKEmDcnhJGvbtB:-MngIg6nBfGEKXg_RVyf:bo14jlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c12c176f318d9740279cc1b7bf3465d74d2c50/pkg/sql/alter_column_type.go#L132)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what about uses of the column in predicates for partial indexes? Also, is there a concern that the column type change might invalidate the index predicate? If you're changing a column that is in the index itself, I don't think we have a problem, but if the column is not in the index, then I don't think we'll re-backfill it. It seems like either we should disallow the change in that case or re-build partial indexes or indexes with computed expressions which reference it?

That brings me to another point, what sort of checking do we do on computed expressions or check constraints which reference this column? I think for check constraints it doesn't matter whether that changes because of the funky definition of check constraints, but it's a somewhat scary edge case for me. 
</blockquote></details>

nice catch. yup that's broken:
```
root@:26257/defaultdb> create table a (a int primary key, b text, c text);
CREATE TABLE

root@:26257/defaultdb> create index idx on a(c) where b = 'cat';
CREATE INDEX

root@:26257/defaultdb> alter table a alter column b set data type timestamp;
ALTER TABLE

root@:26257/defaultdb> insert into a values (1,now(),'abc');
ERROR: unsupported comparison operator: <timestamp> = <string>
SQLSTATE: 22023
```

postgres does check when doing the alter though
```
-- partial index case
postgres=# alter table a alter column b set data type timestamp using to_timestamp(b, 'yyyy');
ERROR:  operator does not exist: timestamp without time zone = text
```

and postgres has this behavior for computed columns:
```
postgres=# create table a (a int primary key, b text, c int generated always as (length(b)) stored);
CREATE TABLE

postgres=# alter table a alter column b set data type int using b::integer;
ERROR:  cannot alter type of a column used by a generated column
```

I'd prefer to file these as a separate issues.


<!-- Sent from Reviewable.io -->

2021-11-04 20:53 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, @otan, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 132 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MnfwvqKEmDcnhJGvbtB:-MngiLt43cs6x1hx--_L:boveo7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0c12c176f318d9740279cc1b7bf3465d74d2c50/pkg/sql/alter_column_type.go#L132)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nice catch. yup that's broken:
```
root@:26257/defaultdb> create table a (a int primary key, b text, c text);
CREATE TABLE

root@:26257/defaultdb> create index idx on a(c) where b = 'cat';
CREATE INDEX

root@:26257/defaultdb> alter table a alter column b set data type timestamp;
ALTER TABLE

root@:26257/defaultdb> insert into a values (1,now(),'abc');
ERROR: unsupported comparison operator: <timestamp> = <string>
SQLSTATE: 22023
```

postgres does check when doing the alter though
```
-- partial index case
postgres=# alter table a alter column b set data type timestamp using to_timestamp(b, 'yyyy');
ERROR:  operator does not exist: timestamp without time zone = text
```

and postgres has this behavior for computed columns:
```
postgres=# create table a (a int primary key, b text, c int generated always as (length(b)) stored);
CREATE TABLE

postgres=# alter table a alter column b set data type int using b::integer;
ERROR:  cannot alter type of a column used by a generated column
```

I'd prefer to file these as a separate issues.
</blockquote></details>

filed https://github.com/cockroachdb/cockroach/issues/72456 and https://github.com/cockroachdb/cockroach/issues/72457

we are already good on CHECK constraints
```
root@:26257/defaultdb> create table a (a int primary key, b text, c text check (c = 'cat'));
CREATE TABLE


Time: 4ms total (execution 4ms / network 0ms)

root@:26257/defaultdb> alter table a alter column c set data type int using c::int;
ERROR: unimplemented: ALTER COLUMN TYPE for a column that has a constraint is currently not supported
SQLSTATE: 0A000
```


<!-- Sent from Reviewable.io -->

2021-11-04 22:16 UTC, rafiss approved these changes
lgtm!

i vote for not backporting this, since ALTER COLUMN TYPE is experimental anyway

2021-11-04 22:17 UTC, rafiss commented
looks like you need to run gofmt/crlfmt on this

2021-11-08 19:35 UTC, rafiss commented
the CI failure is from a timezone test that got fixed, so lgtm!

bors r+

2021-11-10 18:08 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, @otan, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 382 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MoA1DDo0nHSvOUJzBPQ:-MoA1DDo0nHSvOUJzBPR:bxhuheo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f26388fd5ac8e9ee83bbbf3d7330583aea4c02e/pkg/sql/logictest/testdata/logic_test/alter_column_type#L382)):*
> ```
>             CONSTRAINT t17_pkey PRIMARY KEY (rowid ASC),
>             FAMILY fam_0_y_rowid (y, rowid),
>             FAMILY fam_1_x (x)
> ```

this is actually puzzling -- i don't know why the FAMILY would change at all. i'll try this locally


<!-- Sent from Reviewable.io -->

2021-11-10 18:20 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, @otan, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 382 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MoA1DDo0nHSvOUJzBPQ:-MoA2fFu0DJlcHbCRKcJ:byo3o48) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f26388fd5ac8e9ee83bbbf3d7330583aea4c02e/pkg/sql/logictest/testdata/logic_test/alter_column_type#L382)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is actually puzzling -- i don't know why the FAMILY would change at all. i'll try this locally
</blockquote></details>

ah ok, there is some randomization logic for FAMILY: https://github.com/cockroachdb/cockroach/blob/a539b38b5a83be6d4a205d3053aca7ccb5f24717/pkg/sql/logictest/logic.go#L2579

to avoid this, modify the earlier line:
```
CREATE TABLE t17 (x STRING DEFAULT 'HELLO', y STRING ON UPDATE 'HELLO');
```

to be
```
CREATE TABLE t17 (x STRING DEFAULT 'HELLO', y STRING ON UPDATE 'HELLO', FAMILY f1 (x, y));
```

and then the expected output here should be updated accordingly


<!-- Sent from Reviewable.io -->

2021-11-10 18:48 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, @otan, @postamar, @rafiss, and @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 382 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/71423#-MoA1DDo0nHSvOUJzBPQ:-MoAAX-R63yNLwN49rmB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f26388fd5ac8e9ee83bbbf3d7330583aea4c02e/pkg/sql/logictest/testdata/logic_test/alter_column_type#L382)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah ok, there is some randomization logic for FAMILY: https://github.com/cockroachdb/cockroach/blob/a539b38b5a83be6d4a205d3053aca7ccb5f24717/pkg/sql/logictest/logic.go#L2579

to avoid this, modify the earlier line:
```
CREATE TABLE t17 (x STRING DEFAULT 'HELLO', y STRING ON UPDATE 'HELLO');
```

to be
```
CREATE TABLE t17 (x STRING DEFAULT 'HELLO', y STRING ON UPDATE 'HELLO', FAMILY f1 (x, y));
```

and then the expected output here should be updated accordingly
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 19:54 UTC, rafiss approved these changes
lgtm!

2021-11-12 19:55 UTC, e-mbrown commented
bors r+

2021-11-15 05:01 UTC, rafiss commented
bors r+

2021-11-15 05:46 UTC, merged