changefeedccl: introduce 'min_checkpoint_frequency' to adjust sink flush frequency
cockroachdb/cockroach pull request #71436
Opened 2021-10-12 00:32 UTC by gh-casper

Previously, for latency-sensitive sinks like cloud storage, users want to achieve better throughput by adjusting flush frequencies and use 'resolved=X' for this purpose. However, 'resolved' has a different meaning, controlling what time we should at least wait to emit a resolved timestamp event.

This patch disentangles 'resolved' option from this purpose.

Fixes: cockroachdb#69161

Release note (sql change): An option “min_checkpoint_frequency” has been added to CREATE CHANGEFEED statement. When this option is set, changefeed will wait for at least the specified duration before a flush to the external sink. If set empty, changefeed will flush as long as it has local frontier advancement. If not set, it will default to 30 seconds. This option helps high latency sinks to control flush frequency to achieve better throughput.

2021-10-12 00:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/71436)
<!-- Reviewable:end -->

2021-10-12 11:13 UTC, stevendanna requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71436)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloCCmD3MjJ3XYsVScr:-MloCCmD3MjJ3XYsVScs:bmzxuzc) (no related file):*
Glad to see this being looked at! Thanks for taking it on.

---
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-Mlo7I-I4-F61jAPFW0w:-Mlo7I-I4-F61jAPFW0x:b-kl30vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_processors.go#L166)):*
> ```Go
> 	}
> 
> 	// MinCheckpointFrequency controls how frequent the changeAggregator flushes the sink
> ```

s/frequent/frequently/

I'm also not sure on the name MinCheckpointFrequency. But, I haven't thought of a better name yet. 
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-Mlo7ajMAG1FnxOhK7Uz:-Mlo7ajMAG1FnxOhK7V-:b-dnurqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_processors.go#L168)):*
> ```Go
> 	// MinCheckpointFrequency controls how frequent the changeAggregator flushes the sink
> 	// and checkpoints the local frontier to changeFrontier. It is used as a rough
> 	// approximation of how latency-sensitive the changefeed user is. For a latency-sensitive
> ```

Here and in the commit message we call the cloudstorage sink "latency-sensitive."  Perhaps "high latency" might be a better term?  All the sinks are latency sensitive to one degree or another.
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 524 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-Mlo9zWH5TyGy23MgRQj:-Mlo9zWH5TyGy23MgRQk:bymar8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_stmt.go#L524)):*
> ```Go
> 			}
> 		}
> 	}
> ```

Would it be useful to error out if  the user has provided a `resolved` and `min_checkpoint_frequency` that are incompatible?


<!-- Sent from Reviewable.io -->

2021-10-12 11:51 UTC, miretskiy requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71436)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper, @miretskiy, and @stevendanna)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloKqgW98ZF7Gq79t-I):*
I think this PR definitely needs a release note -- we are changing how resolved option is handled and we're introducing a new option
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloKkDYCXcJxmr80OgA:-MloKkDYCXcJxmr80OgB:b-mhvzzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_processors.go#L186)):*
> ```Go
> 		}
> 	} else {
> 		ca.flushFrequency = changefeedbase.DefaultFlushFrequency
> ```

we're still keeping default at 5 seconds?


<!-- Sent from Reviewable.io -->

2021-10-12 17:49 UTC, gh-casper reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71436)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloCCmD3MjJ3XYsVScr:-Mlpbug60OuN8tNUdpuN:bouyv77) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Glad to see this being looked at! Thanks for taking it on.
</blockquote></details>

Glad I can help.

---
___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloKqgW98ZF7Gq79t-I):*
> itely needs a release note -- we are changing how resolved option is handled and we're introducing a new option
Done
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-Mlo7I-I4-F61jAPFW0w:-MlpX77wCQF93HD9qtQC:b-dj3akr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_processors.go#L166)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

s/frequent/frequently/

I'm also not sure on the name MinCheckpointFrequency. But, I haven't thought of a better name yet. 
</blockquote></details>

I think MinFlushFrequency can be an alternative but flush can be an overloaded term.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-Mlo7ajMAG1FnxOhK7Uz:-MlpVzrs-6FhkYHd--9w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_processors.go#L168)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Here and in the commit message we call the cloudstorage sink "latency-sensitive."  Perhaps "high latency" might be a better term?  All the sinks are latency sensitive to one degree or another.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloKkDYCXcJxmr80OgA:-MlpVqEw8v9_dA1szb3k:b3zge1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_processors.go#L186)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we're still keeping default at 5 seconds?
</blockquote></details>

Oops, forgot to change the DefaultFlushFrequency.
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 524 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-Mlo9zWH5TyGy23MgRQj:-MlpUDb63VOMF4v943gw:ba5i95h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_stmt.go#L524)):*
> min_checkpoint_frequency
They are quite independent and not incompatible. `resolved` controls how frequently we emit a resolved timestamp in the changedFrontier. We can have frequent flush frequency in changeAggregators but infrequent resolved timestamp emissions in changeFrontier.


<!-- Sent from Reviewable.io -->

2021-10-12 19:01 UTC, miretskiy approved these changes
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71436)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper, @miretskiy, and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloKkDYCXcJxmr80OgA:-Mlpr8iz68NYOm9wDnb_:bp5rsg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_processors.go#L186)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

Oops, forgot to change the DefaultFlushFrequency.
</blockquote></details>

Let's rename this constant while at it.


<!-- Sent from Reviewable.io -->

2021-10-12 19:02 UTC, miretskiy approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71436)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gh-casper, @miretskiy, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloCCmD3MjJ3XYsVScr:-MlpsU-e-2H6zxg0fd5-:b-d4y5kn) (no related file):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

Glad I can help.
</blockquote></details>

This looks reasonable to me; giving an <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> , but please let @stevendanna comment/approve as well.
Thanks.

---


<!-- Sent from Reviewable.io -->

2021-10-15 17:12 UTC, stevendanna approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71436)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @gh-casper and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloCCmD3MjJ3XYsVScr:-Mm3v5vL93RxGXd9t9KH:brhbz5m) (no related file):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This looks reasonable to me; giving an <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> , but please let @stevendanna comment/approve as well.
Thanks.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  I left some comments to confirm my own understanding and one non-blocking suggestion.  I defer to your judgement there.

---
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-Mlo7I-I4-F61jAPFW0w:-Mm3qXzM0OSGsM2wOXB_:bfzkigp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_processors.go#L166)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

I think MinFlushFrequency can be an alternative but flush can be an overloaded term.
</blockquote></details>

:D Unfortunately `Checkpoint` is also overloaded. For example, this is the interval at which we flush the sink and forward to the changeFrontier, but it isn't _quiet_ the same of how often we "checkpoint" our resolved timestamp in the frontier to the job record.  But, let's not get hung up here right now.  I think we'll converge on language as we iterate on the code over the next weeks and months. 
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 524 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-Mlo9zWH5TyGy23MgRQj:-Mm3qvE04_-4O3DqfrHh:b1kjsee) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_stmt.go#L524)):*
> We can have frequent flush frequency in changeAggregators but infrequent resolved timestamp emissions in changeFrontier.

Right, but you can't have the reverse because we can't emit resolved timestamps at a rate faster than the changeAggregator forwards them to the changeFrontier.  While I know that `resolved` is documented as the _minimum_ time between resolved timestamp emissions, I still worry that if the user requests `resolved=5s` and `min_checkpoint_frequency=10m` they likely are confused about what they want and it could be worth it to at least warn them.

That said, I'm happy to drop this.
___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-Mm3vZRe11DPGCZOZBcn:-Mm3vZRe11DPGCZOZBco:bfu4bt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeedbase/options.go#L156)):*
> ```Go
> 	OptTopicInValue:             sql.KVStringOptRequireNoValue,
> 	OptResolvedTimestamps:       sql.KVStringOptAny,
> 	OptMinCheckpointFrequency:   sql.KVStringOptAny,
> ```

I think we could make this `KVStringOptRequireValue` to ensure that the user has set a value.


<!-- Sent from Reviewable.io -->

2021-11-06 21:16 UTC, gh-casper reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71436)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @gh-casper, @miretskiy, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloCCmD3MjJ3XYsVScr:-MnqoI-F8RFp6GnlT2Mq:b-896fix) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  I left some comments to confirm my own understanding and one non-blocking suggestion.  I defer to your judgement there.
</blockquote></details>

Done.

---
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-MloKkDYCXcJxmr80OgA:-MnqoCML8nsHnIr255N9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeed_processors.go#L186)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Let's rename this constant while at it.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71436#-Mm3vZRe11DPGCZOZBcn:-MnqoFID4_GO-qLS2z_r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c75501ddf9e05d116ab1c31c63517ce7616d509/pkg/ccl/changefeedccl/changefeedbase/options.go#L156)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I think we could make this `KVStringOptRequireValue` to ensure that the user has set a value.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-15 15:31 UTC, gh-casper commented
bors r+

2021-11-15 16:57 UTC, merged