sql: remove diagnostics.sql_stat_reset.interval
cockroachdb/cockroach pull request #71597
Opened 2021-10-15 02:53 UTC by Azhng

Previously, SQL Stats resets its in-memory SQL Stats
periodically (determined by diagnostics.sql_stat_reset.interval
cluster setting). The periodic reset loop was introduced early
in 21.1 prior to persisted SQL Stats. In 21.2, we introduced
persisted SQL Stats and also runs perodic task that flushes
in-memory SQL Stats into system tables. This two async tasks'
coexistence introduced unwanted race conditions. If the SQL
Stats reset task resets the in-memory store before the
flusher can flush it to system table, then that particular stats
would be lost forever.
This commit change the .Start() method in PersistedSQLStats to
avoid this race condition. However, reported SQL Stats still
periodically resets its in-memory storage in case the telemetry
server goes offline.

Release note (sql change): diagnostics.sql_stats_reset.interval
is removed.

2021-10-15 02:54 UTC, Azhng commented
Follow up to #71596

2021-10-15 04:00 UTC, Azhng commented
Tagging @cockroachdb/sql-experience  for reviewing if I retired the cluster setting properly

2021-10-18 20:02 UTC, matthewtodd requested changes
Are there any tests that would be useful to add here? I'm imagining something that would show the interaction of the happy-path flush to system tables with the uh-oh path reset because it's been too long and we're running out of memory. WDYT?

> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-:-MmJykb0Bxp2uC7yRVDn:b-19zecx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[-- commits, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-MmJyYToA4I6LXEu1GsS):*
nit: some style / grammar adjustments, WDYT?

> Previously, the SQL Stats system reset its in-memory SQL Stats periodically,
determined by the `diagnostics.sql_stat_reset.interval` cluster setting. This
periodic reset loop was introduced early in 21.1 prior to persisted SQL Stats.
In 21.2, we introduced persisted SQL Stats and along with a perodic task to
flush in-memory SQL Stats into system tables. These two async tasks'
coexistence introduced unwanted race conditions. If the SQL Stats reset task
reset the in-memory store before the flusher could flush it to the system
table, those particular stats would be lost forever.
> 
> This commit changes the `.Start()` method in `PersistedSQLStats` to avoid this
race condition. However, reported SQL Stats still periodically resets its
in-memory storage in case the telemetry server goes offline.
___
*[pkg/sql/conn_executor.go, line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-MmJzEMt5IDfddH-NNnH:-MmJzEMt5IDfddH-NNnI:bi772as) ([raw file](https://github.com/cockroachdb/cockroach/blob/d337fdd2ee5073eeca5c9e611c81520fcd452191/pkg/sql/conn_executor.go#L447)):*
> ```Go
> 	s.sqlStats.Start(ctx, stopper)
> 
> 	// reportedStats is periodically cleared to prevent too much SQL Stats
> ```

nit: s/much/many/


<!-- Sent from Reviewable.io -->

2021-10-18 21:48 UTC, maryliag reviewed
We also need tests that are able to capture the initial issue that this PR is trying to fix otherwise it's just a guess that this change would indeed fix the issue.

> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-:-MmKLbmACi3JaIlYVwhQ:b-x7xr8e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)



<!-- Sent from Reviewable.io -->

2021-11-09 16:27 UTC, knz reviewed
Regarding testing, there are two separate stories:

- When I look at this PR without the context of the issue that motivates it, I still see a compelling reason to merge the PR: the periodic flush has become redundant with the new mechanism to persist stats, and it's good to remove redundant code (for hygiene). When removing an obsolete mechanism, we do not typicall introduce new tests that confirm that the mechanism has been removed. Instead, we remove the tests that had been added to support the original mechanism.

  (Btw, I am not recongizing this: where were the unit tests for `diagnostics.sql_stats_reset.interval` located? These should at least be altered, if not removed outright, by this PR)

- Generally, if there's a race condition somewhere, it is due to the interaction between two or more subsystems. **If we keep both subsystems** and then add some coordination mechanism (e.g. a mutex), then yes we do want to add a new test for that race condition, to assert that it does not occur and prevent regressions.
 
  However, in this case, **we are removing one of the participants in the race condition** such that only one subsystem remains. After this PR is merged, there is no conflict between two mechanisms any more - no environment where a race condition could even occur. In that case (all concurrent mechanisms, but one, have been removed) we also don't typically add new tests.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-:-Mo4Vj9Y2YbHkHT1kX_t:b-8wvcb6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-Mo4VUFLAZH2JR-ZDL88):*
More words here please.


<!-- Sent from Reviewable.io -->

2021-11-09 17:33 UTC, Azhng reviewed
I was having a difficult time trying to find where we originally tested the behaviour for `diagnostics.sql_stats_reset.interval` cluster setting, but I couldn't find any. Perhaps this was the reason why this issue was not caught early on. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-:-Mo4gHVb7UgVNfBra06r:b-e9k5t2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @maryliag, and @matthewtodd)

___
*[-- commits, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-MmJyYToA4I6LXEu1GsS):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: some style / grammar adjustments, WDYT?

> Previously, the SQL Stats system reset its in-memory SQL Stats periodically,
determined by the `diagnostics.sql_stat_reset.interval` cluster setting. This
periodic reset loop was introduced early in 21.1 prior to persisted SQL Stats.
In 21.2, we introduced persisted SQL Stats and along with a perodic task to
flush in-memory SQL Stats into system tables. These two async tasks'
coexistence introduced unwanted race conditions. If the SQL Stats reset task
reset the in-memory store before the flusher could flush it to the system
table, those particular stats would be lost forever.
> 
> This commit changes the `.Start()` method in `PersistedSQLStats` to avoid this
race condition. However, reported SQL Stats still periodically resets its
in-memory storage in case the telemetry server goes offline.

</blockquote></details>

Done.
___
*[-- commits, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-Mo4VUFLAZH2JR-ZDL88):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

More words here please.
</blockquote></details>

Added more description to the release note.
___
*[pkg/sql/conn_executor.go, line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-MmJzEMt5IDfddH-NNnH:-Mo4edpD5bT_FhhKIHEE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d337fdd2ee5073eeca5c9e611c81520fcd452191/pkg/sql/conn_executor.go#L447)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: s/much/many/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-09 17:53 UTC, knz approved these changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71597)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)



<!-- Sent from Reviewable.io -->

2021-11-09 19:52 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71597#-:-Mo5FS3pDEZFffbN3vGb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)



<!-- Sent from Reviewable.io -->

2021-11-09 19:53 UTC, Azhng commented
TFTR!

bors r=knz,maryliag

2021-11-10 00:53 UTC, merged

2021-11-10 09:54 UTC, knz commented
should this be blindly backported to 21.2? Was the code for stats persistence already in 21.2?

2021-11-19 21:15 UTC, Azhng commented
blathers backport 21.2