roachtest: add jasyncsql test suite
cockroachdb/cockroach pull request #71710
Opened 2021-10-19 14:38 UTC by e-mbrown

fixes #71158

Add a new roachtest, jasyncsql. Currently there is not config object
to alter the connection port in the original repo. The test points to
a forked repo, with altered config object, which runs the original
postgreSQL test suite.

Release note: None

2021-10-19 18:53 UTC, rafiss requested changes

2021-11-05 02:33 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhuUGy0EH1cCyHA4AD:-MnhuUGy0EH1cCyHA4AE:b-9sj3eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql.go#L43)):*
> ```Go
> 		t.Status("cloning jasync-sql and installing prerequisites")
> 
> 		//remove old
> ```

nit: fix comment
___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhuWAG3M7imNIDA448:-MnhuWAG3M7imNIDA449:bdrmvbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql.go#L61)):*
> ```Go
> 			"https://github.com/jasync-sql/jasync-sql.git",
> 			"/mnt/data1/jasyncsql",
> 			"master",
> ```

instead of relying on master, let's tie it to a specific commit.

basically, i mean add a step after this that does `git checkout cd93bded` (that's the commit where you added the env vars)

once there is an official release with your change, then we can point at that instead
___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhvJPDDuL-e51oBS-a:-MnhvJPG9Hgd-5Ivq1C1:b-nbths) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql.go#L137)):*
> ```Go
> 		}
> 
> 		//Not sure where I'd get a tag
> ```

for the tag you can use the commit i mentioned above
___
*[pkg/cmd/roachtest/tests/jasyncsql_blocklist.go, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-Mnhtksu4sW8aJ3p_-Yq:-Mnhtksu4sW8aJ3p_-Yr:b25s65r) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql_blocklist.go#L14)):*
> ```Go
> 
> var jasyncsqlBlocklists = blocklistsForVersion{
> 	{"v21.2", "jasyncsqlBlocklist21_2", jasyncBlocklist21_2, "jasyncsqlIgnoreList21_2", jasyncsqlIgnoreList21_2},
> ```

this should be for v22.1 -- v21.2 has already been released so if we merge this to master now, it will be for v22.1
___
*[pkg/cmd/roachtest/tests/jasyncsql_blocklist.go, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhuDzN0dE9bulSARN4:-MnhuDzN0dE9bulSARN5:bz2lddb) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql_blocklist.go#L19)):*
> ```Go
> var jasyncBlocklist21_2 = blocklist{}
> 
> var jasyncsqlIgnoreList21_2 = blocklist{
> ```

hm this list doesn't look right to me. i ran the jasync-sql test locally myself and got
```
163 tests completed, 87 failed, 5 skipped
```

if you run `roachtest run jasyncsql` you can look in your local `artifacts/` folder to find the roachtest logs. then look for a log line from https://github.com/cockroachdb/cockroach/blob/ed35bbe8f6e5947db6e3f2423d1aa9dde1d15804/pkg/cmd/roachtest/tests/java_helpers.go#L204

to see if its parsing all the XML files


<!-- Sent from Reviewable.io -->

2021-11-09 15:09 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MmNzOxoOCNfgnlV-osP-r1-77:-Mo-pFYF6z_w5ujrELfT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c13219d65495d358359e724c1f7265de5ee68e55/pkg/cmd/roachtest/tests/jasyncsql.go#L77)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nice work! the next thing that needs to be added here is making the tests actually use the blocklists. we have some helpers that already can do that. you can make it call the code similar to how this part of the pgjdbc test is

https://github.com/cockroachdb/cockroach/blob/c8c186f2d27f24c489aba5f6a38b57b48f628148/pkg/cmd/roachtest/tests/pgjdbc.go#L130-L189
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhuWAG3M7imNIDA448:-Mo-p8VS9DdmOrest8Ol:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql.go#L61)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of relying on master, let's tie it to a specific commit.

basically, i mean add a step after this that does `git checkout cd93bded` (that's the commit where you added the env vars)

once there is an official release with your change, then we can point at that instead
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhvJPDDuL-e51oBS-a:-Mo-pCvuBHB6pzDTel-S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql.go#L137)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

for the tag you can use the commit i mentioned above
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/jasyncsql_blocklist.go, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-Mnhtksu4sW8aJ3p_-Yq:-Mo--uAiDDW59yypPqT6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql_blocklist.go#L14)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this should be for v22.1 -- v21.2 has already been released so if we merge this to master now, it will be for v22.1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 16:25 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhuUGy0EH1cCyHA4AD:-MoJx8y0AzRREolJl8Pe:b-7z3zna) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql.go#L43)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: fix comment
</blockquote></details>

nit: there should be a space after `//` and `Remove` should be capitalized
___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhvJPDDuL-e51oBS-a:-MoJwWYD31abOLsIXR9m:b-pul9pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql.go#L137)):*
<details><summary><i>Previously, e-mbrown wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: remove this comment
___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MoJxqNJ8QqNJmpYi5Vb:-MoJxqNJ8QqNJmpYi5Vc:b19vl0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e02d090433b2cb42c7379df615efcd037255f93/pkg/cmd/roachtest/tests/jasyncsql.go#L65)):*
> ```Go
> 		}
> 
> 		if err := c.RunE(ctx, node, fmt.Sprintf("cd /mnt/data1/jasync-sql && git checkout %s",
> ```

nit: add a TODO comment saying that we should switch to an official release once it is available
___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 124 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MoJx53t5ZRSVQyXUlji:-MoJx53t5ZRSVQyXUljj:bbmwr2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e02d090433b2cb42c7379df615efcd037255f93/pkg/cmd/roachtest/tests/jasyncsql.go#L124)):*
> ```Go
> 		}
> 
> 		//Load all test results
> ```

nit: there should be a space after the `//`
___
*[pkg/cmd/roachtest/tests/jasyncsql_blocklist.go, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhuDzN0dE9bulSARN4:-MoJwaziEzTQrLD4zZP5:bvft88) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql_blocklist.go#L19)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm this list doesn't look right to me. i ran the jasync-sql test locally myself and got
```
163 tests completed, 87 failed, 5 skipped
```

if you run `roachtest run jasyncsql` you can look in your local `artifacts/` folder to find the roachtest logs. then look for a log line from https://github.com/cockroachdb/cockroach/blob/ed35bbe8f6e5947db6e3f2423d1aa9dde1d15804/pkg/cmd/roachtest/tests/java_helpers.go#L204

to see if its parsing all the XML files
</blockquote></details>

this list should be the blocklist, not the ignorelist. ignorelist is meant for flaky tests, while blocklist is for tests that are failing because of a difference between crdb and postgres


<!-- Sent from Reviewable.io -->

2021-11-12 19:52 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/cmd/roachtest/tests/jasyncsql.go, line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhvJPDDuL-e51oBS-a:-MoKgrSX8son5THYpDOd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql.go#L137)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: remove this comment
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/jasyncsql_blocklist.go, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71710#-MnhuDzN0dE9bulSARN4:-MoKhN1HD86mQ1MsHngG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd060f9b61ac17ffc2b5d29412e37728bb3edaf2/pkg/cmd/roachtest/tests/jasyncsql_blocklist.go#L19)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this list should be the blocklist, not the ignorelist. ignorelist is meant for flaky tests, while blocklist is for tests that are failing because of a difference between crdb and postgres
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-18 22:02 UTC, rafiss approved these changes
lgtm!

2021-11-23 18:59 UTC, rafiss commented
bors r+

2021-11-23 19:57 UTC, merged

2023-09-12 21:03 UTC, RaduBerinde commented on pkg/cmd/roachtest/tests/jasyncsql.go
> +		Tags:    []string{`default`, `orm`},
Does anyone know what the `orm` tag here is used for?