backupccl: add parquet format to export
cockroachdb/cockroach pull request #71868
Opened 2021-10-22 14:58 UTC by msbutler

Commit 1: Add Parquet SQL EXPORT parsing logic
Previously, the sql package only parsed the EXPORT command for CSV files. This commit adds some very basic logic to process EXPORT for parquet files. This commit doesn't add any user facing options for exporting parquet files, which likely needs more product discovery.

Commit 2: Add Parquet Processor
This commit adds a new processor for exporting a relation as a parquet file,
and adds a test for exporting a relation with bools, ints, floats, and strings.
This commit also updates the fraugster parquet-go vendor dependency.
Future work must ensure that all crdb data types, including arrays, can be
exported properly.

The fraugster/parquet-go vendor was specifically chosen because it allows us
to  define the parquet schema at runtime. Specifically, we can write rows
encoded as a dynamically created map[string]interface{}.

Release note (sql change): adds ability to EXPORT PARQUET for relations with
float, int, string column types.

Informs: #67710

Once this PR merges, I plan to work on the following:
- [x] Modify the export processor to add the input relation's column names
- [x] Investigate how Export Parquet should support nullable columns #72530
- [x] Support array types
- [x] Support all other types supported by crdb
- [ ] Investigate optimal default parquet file and chunk size
- [x] Consider refactoring the CSV Exporter and Parquet Exporter to remove duplicate code. Will at least modify all relevant ExportCSV tests to also run ExportParquet. 
- [x] EXPORT options validation for options that don't make sense with parquet (if any)
- [x] Randomized Testing
- [ ] Encoding benchmarks

2021-10-22 17:20 UTC, stevendanna requested changes
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @msbutler)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcxPb7EO_lJSBvwNDI:-MmcxPb7EO_lJSBvwNDJ:brio0rh) (no related file):*
I didn't make it through everything, but have left some initial comments.

Given that this is limited in scope at the moment (in terms of its coverage of the supported SQL types), I think it would be good to spell out what the next few steps are somewhere.

While I'm not sure you need to do it _now_, it might be nice to put thought into how we could reduce some of the duplication between the two exporters, especially if we ever end up with a 3rd export format.

---
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcoXAW0V3ZR7gL5x3m):*
nit: It's nice to wrap commit messages so they show up nicely in the terminal.
___
*[pkg/ccl/importccl/exportcsv_test.go, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mmcwno77gjDnxXzArqk:-Mmcwno77gjDnxXzArql:b-i9wtdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportcsv_test.go#L288)):*
> ```Go
> 		return err
> 	}
> 	fmt.Printf("Printing file %s\n", file)
> ```

Perhaps move the most useful of these print statements to t.Logf and remove the rest.
___
*[pkg/ccl/importccl/exportparquet.go, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mmcs13EEl0yBLBoo0cf:-Mmcs13F4OBkdMN7S5rW:b-2fc7p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L36)):*
> ```Go
> 
> // parquetExporter data structure to augment the compression
> // and csv writer, encapsulating the internals to make
> ```

s/csv/parquet/
___
*[pkg/ccl/importccl/exportparquet.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mmcsp8kBxkgFcgXH_7m:-Mmcsp8kBxkgFcgXH_7n:bkk0awh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L39)):*
> ```Go
> // exporting oblivious for the consumers.
> type parquetExporter struct {
> 	compressor     *gzip.Writer
> ```

I don't see compressor being used. It looks like the parquet library supports its own compression that we are using.  Perhaps we should mark this as TODO or remove it? I think there is perhaps some thinking here about what to do if the user explicitly specifies gzip compression or no compression.
___
*[pkg/ccl/importccl/exportparquet.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mmcs7og7Zno-8PLPbJu:-Mmcs7og7Zno-8PLPbJv:b-sfoyye) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L45)):*
> ```Go
> }
> 
> // Write append record to parquet file.
> ```

s/append/appends/
___
*[pkg/ccl/importccl/exportparquet.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcsRFtEPM5P034IFnL:-MmcsRFtEPM5P034IFnM:b-bnvchq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L50)):*
> ```Go
> }
> 
> // Flush append record to parquet file.
> ```

Let's fix up this comment. I'm surprised we don't need to do anything here.  Perhaps a comment saying why we don't (it looks like Close() does most of the work).
___
*[pkg/ccl/importccl/exportparquet.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmctRNC-I_tmWBpTNx_:-MmctRNC-I_tmWBpTNxa:b30zhmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L55)):*
> ```Go
> }
> 
> // Close closes the parquet writer
> ```

I think the linter is going to yell at you about a period at the end of the comment. Or at least, I remember it yelling at me once.
___
*[pkg/ccl/importccl/exportparquet.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmczjIQ4q7x5iEaDCC1:-MmczjIT0Vz4D276MHVP:b-hl5ngq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L57)):*
> ```Go
> // Close closes the parquet writer
> func (c *parquetExporter) Close() error {
> 	c.parquetWriter.Close()
> ```

Close returns an error, any reason not to return it below?
___
*[pkg/ccl/importccl/exportparquet.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmctJFt6TLYkjrPoPPt:-MmctJFt6TLYkjrPoPPu:b-1urjor) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L62)):*
> ```Go
> 
> // Bytes results in the slice of bytes with compressed content.
> func (c *parquetExporter) Bytes() []byte { // IDENTICAL TO CSV
> ```

[nit] I don't think we need these `IDENTICAL` comments.
___
*[pkg/ccl/importccl/exportparquet.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmctgiVEub4Bhyhep6l:-MmctgiVEub4Bhyhep6m:b-92kq90) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L76)):*
> ```Go
> 
> func (c *parquetExporter) FileName(spec execinfrapb.ParquetWriterSpec, part string) string {
> 	pattern := exportFilePatternDefault
> ```

I think this still points to the variable defined in the `csv` export.  I'm guessing we never see spec.NamePattern == "" but probably good to clean up anyway.
___
*[pkg/ccl/importccl/exportparquet.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcvR6N2r_M9ql7bbF7:-MmcvR6N2r_M9ql7bbF8:bcnh8lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L146)):*
> ```Go
> 	col.crbdType = typ
> 
> 	col.definition.SchemaElement.RepetitionType = parquet.FieldRepetitionTypePtr(parquet.FieldRepetitionType_REQUIRED)
> ```

Do we need to account for NULLABLE columns?  I see some commented code about nullable values down below.  Perhaps a TODO comment somewhere explaining what we need to do would be good. If we don't support them right now, we might also want to error if you try to export a table with a nullable column.
___
*[pkg/ccl/importccl/exportparquet.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcuhwABwVN9Yq5PnKH:-MmcuhwABwVN9Yq5PnKI:b-pvz5pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L198)):*
> ```Go
> 
> 	default:
> 		return col, errors.Errorf("parquet export does not support type yet")
> ```

Let's add the type to the error message here.
___
*[pkg/sql/distsql_physical_planner.go, line 3921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcopDrB_hfBsyBEQzg:-MmcopDrB_hfBsyBEQzh:b-9ydad8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a669e6812da765582ba5de576107dee0a7c5ce2/pkg/sql/distsql_physical_planner.go#L3921)):*
> ```Go
> 		}
> 	} else{
> 		return nil, errors.Errorf("PARQUET AND CSV OPTS BOTH EMPTY?!?")
> ```

We probably want to clean up this error message.  It seems like it would a programming error on our part if we get here, so perhaps an AssertionFailedf error would be appropriate. 
___
*[pkg/sql/export.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcqvWe583bgfh73DW6:-MmcqvWe583bgfh73DW7:b-rfd5li) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a669e6812da765582ba5de576107dee0a7c5ce2/pkg/sql/export.go#L16)):*
> ```Go
> 	"context"
> 	"fmt"
> 	"github.com/cockroachdb/cockroach/pkg/util"
> ```

[nit] We typically split the import list into two sections, one for stdlib packages and one f [...]

2021-10-22 21:11 UTC, msbutler reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcxPb7EO_lJSBvwNDI:-MmddAgn3q0avLB2USRU:b9j08x6) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I didn't make it through everything, but have left some initial comments.

Given that this is limited in scope at the moment (in terms of its coverage of the supported SQL types), I think it would be good to spell out what the next few steps are somewhere.

While I'm not sure you need to do it _now_, it might be nice to put thought into how we could reduce some of the duplication between the two exporters, especially if we ever end up with a 3rd export format.


</blockquote></details>

Just edited the top comment in the PR with Additional ToDOs!

---
___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcoXAW0V3ZR7gL5x3m):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

nit: It's nice to wrap commit messages so they show up nicely in the terminal.
</blockquote></details>

done
___
*[pkg/ccl/importccl/exportcsv_test.go, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mmcwno77gjDnxXzArqk:-MmdgrO17T5KyUcREtJ8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportcsv_test.go#L288)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Perhaps move the most useful of these print statements to t.Logf and remove the rest.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mmcs13EEl0yBLBoo0cf:-Mmdhs39AjieikM4ChKd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L36)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

s/csv/parquet/
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mmcsp8kBxkgFcgXH_7m:-Mmdhsje6K_e7DyzBmPn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L39)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I don't see compressor being used. It looks like the parquet library supports its own compression that we are using.  Perhaps we should mark this as TODO or remove it? I think there is perhaps some thinking here about what to do if the user explicitly specifies gzip compression or no compression.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mmcs7og7Zno-8PLPbJu:-MmdiDkg9dZkSs95emFW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L45)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

s/append/appends/
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcsRFtEPM5P034IFnL:-Mmdj8hl-kLd_Gr8C6Hx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L50)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Let's fix up this comment. I'm surprised we don't need to do anything here.  Perhaps a comment saying why we don't (it looks like Close() does most of the work).
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmctRNC-I_tmWBpTNx_:-Mmdj9rR9jBTHAsO3CLe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L55)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I think the linter is going to yell at you about a period at the end of the comment. Or at least, I remember it yelling at me once.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmczjIQ4q7x5iEaDCC1:-MmdjGsKCgciyHhJ4veE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L57)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Close returns an error, any reason not to return it below?
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmctJFt6TLYkjrPoPPt:-MmdjKmW1FJm4Fw0U3BS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L62)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] I don't think we need these `IDENTICAL` comments.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmctgiVEub4Bhyhep6l:-Mmdjtmd3eNm8SEqKsrj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L76)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I think this still points to the variable defined in the `csv` export.  I'm guessing we never see spec.NamePattern == "" but probably good to clean up anyway.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcvR6N2r_M9ql7bbF7:-MmdkYtp5tjLw7xS8LdE:bkgj84i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L146)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do we need to account for NULLABLE columns?  I see some commented code about nullable values down below.  Perhaps a TODO comment somewhere explaining what we need to do would be good. If we don't support them right now, we might also want to error if you try to export a table with a nullable column.
</blockquote></details>

The export processor will now error out if a null value is encountered. I need to do a bit more thinking on how to handle null values, which i think requires it's own pr. 
___
*[pkg/ccl/importccl/exportparquet.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcuhwABwVN9Yq5PnKH:-MmdlO-l8UTwrgFiLN3f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L198)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Let's add the type to the error message here.
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 3921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcopDrB_hfBsyBEQzg:-Mmdm4Tk5RGXMmydBiet:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a669e6812da765582ba5de576107dee0a7c5ce2/pkg/sql/distsql_physical_planner.go#L3921)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

We probably want to clean up t [...]

2021-10-28 10:26 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @msbutler, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5A9BtDzlkssgITRwE:-Mn5A9BtDzlkssgITRwF:b-ezif98) (no related file):*
Thanks for adding the TODO list. I've added some bullet points for testing as well.

I would replace `Fixes #67710` with `Informs #67710` for now since the type coverage is limited at the moment.  Once we've expanded the types a bit, we can mark it as fixed.

It looks like you've got some lint/formatting issues caught by CI.  The code base uses a custom code formatter: https://github.com/cockroachdb/crlfmt. I've found it saves a lot of back-and-forth with CI if you integrate running it into your editor or workflow.

I've left a few more comments.  I don't want to annoy you too much with multiple passes of review since I believe the goal here is to merge this step which gets parquet export working end-to-end and then iterate in smaller PRs.  This is a plan I like.

It _might_ be nice to put something small in the code that allows us to enable the feature during tests but would prevent it from being exposed to end-users until it is done.  Probably doesn't need to be as big as a cluster setting, even a package-level variable that we can flip to true in the tests might be enough.

---
___
*[pkg/ccl/importccl/exportcsv_test.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5AjRh2vAsbEYN69BC:-Mn5AjRh2vAsbEYN69BD:b-uwl5kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportcsv_test.go#L40)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/workload/workloadsql"
> 	goparquet "github.com/fraugster/parquet-go"
> 	//goparquet "github.com/fraugster/parquet-go"
> ```

[nit] looks like we can remove this
___
*[pkg/ccl/importccl/exportparquet.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mmcsp8kBxkgFcgXH_7m:-Mn5LbluDy9pE7-A69vs:bwklj2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L39)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like the linter is going to complain about the unused struct.  

It appears that the library does support other compressors: https://github.com/fraugster/parquet-go/blob/c28e3072a9721f25d59193b9d74c642d20800fe8/compress.go#L154

Although, the exact semantics may be a bit different still since I _think_ parquet compression is at a column level and not a whole-file level.
___
*[pkg/ccl/importccl/exportparquet.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcvR6N2r_M9ql7bbF7:-Mn5HfwB4xoANyoiRbSc:b-vs3igg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L146)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

The export processor will now error out if a null value is encountered. I need to do a bit more thinking on how to handle null values, which i think requires it's own pr. 
</blockquote></details>

When you get to this, it might be useful to pick Aaron Zinger's brain as he has done work on the avro encoder where there are similar issues.
___
*[pkg/ccl/importccl/exportparquet.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5HCLM-URDzUylMxfh:-Mn5HCLM-URDzUylMxfi:b-fj0a37) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L113)):*
> ```Go
> 		}
> 		parquetColumns[i] = parquetCol
> 	}
> ```

Since we know there is more to do here this may be premature, but I wonder if we can attempt this right away in newParquetWriterProcessor just so we get a more immediate error on any unsupported types.
___
*[pkg/ccl/importccl/exportparquet.go, line 297 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5Iulp6Xcy26D1f8X_:-Mn5Iulp6Xcy26D1f8Xa:bwffqe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L297)):*
> ```Go
> 			// MB: a big difference from csv: for parquet, it's easiest to create a
> 			// new ParquetExporter each time the processor creates a new parquet file,
> 			// as the ParquetExporter contains metadata specific to that file
> ```

Would it be sufficient to have a method that Reset()'s the data buffer and then reconstruct the parquetWriter?  If so, it might be nice to do that to save on re-allocating our buffer, re-creating the parquet schema, etc.
___
*[pkg/ccl/importccl/exportparquet.go, line 327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5KSUv5dzJBkKOZjTA:-Mn5KSUv5dzJBkKOZjTB:b-rayz03) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L327)):*
> ```Go
> 						return errors.New("NULL value encountered during EXPORT PARQUET, " +
> 							". Tables with NULL values not supported yet :(")
> 						/*if sp.spec.Options.NullEncoding != nil {
> ```

I would consider removing this commented code and the related TODOs just because I imagine that we'll be handling nulls differently than this CSV implementation since (I assume?) the parquet file format defines how a null value is represented for a given data type and thus I'm guess we don't need the NullEncoding option here.  Might even be best to remove it from the proto as well for now.
___
*[pkg/ccl/importccl/exportparquet.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5NqC40YKdJpV8YxIw:-Mn5NqC40YKdJpV8YxIx:btnpz0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L372)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 			// Close exporter to ensure buffer and any compression footer is flushed.
> 			err = exporter.Close()
> 			if err != nil {
> 				return errors.Wrapf(err, "failed to close exporting exporter")
> 			}
> ```
</details>


[nit] I know this is matching existing code, but I think it would be a little more clear for this to be right below the Flush() above unless there is a reason that it needs to be down here.
___
*[pkg/sql/export.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcqvWe583bgfh73DW6:-Mn5FpLlBaS_tu-Tl0_T:b-2s7xtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a669e6812da765582ba5de576107dee0a7c5ce2/pkg/sql/export.go#L16)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hrm, perhaps reviewable is confused but this still looks like an issue.


<!-- Sent from Reviewable.io -->

2021-10-28 21:27 UTC, msbutler reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5A9BtDzlkssgITRwE:-Mn7eBkRDhUtG368SQ-5:b-rdoppl) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Thanks for adding the TODO list. I've added some bullet points for testing as well.

I would replace `Fixes #67710` with `Informs #67710` for now since the type coverage is limited at the moment.  Once we've expanded the types a bit, we can mark it as fixed.

It looks like you've got some lint/formatting issues caught by CI.  The code base uses a custom code formatter: https://github.com/cockroachdb/crlfmt. I've found it saves a lot of back-and-forth with CI if you integrate running it into your editor or workflow.

I've left a few more comments.  I don't want to annoy you too much with multiple passes of review since I believe the goal here is to merge this step which gets parquet export working end-to-end and then iterate in smaller PRs.  This is a plan I like.

It _might_ be nice to put something small in the code that allows us to enable the feature during tests but would prevent it from being exposed to end-users until it is done.  Probably doesn't need to be as big as a cluster setting, even a package-level variable that we can flip to true in the tests might be enough.

</blockquote></details>

Just pushed some revisions to your previous set of very helpful comments. Could you point me to an example of a lightweight feature gate?

Note that my latest pr has a dirty vendor directory. Everytime i try to rebase to master, i get vendor conflicts... it's a total mess, so I'm going to open a separate branch and pr on cockroachdb/cockroach to publicize my vendor changes so the parquet vendor will always be at the head. 

---
___
*[pkg/ccl/importccl/exportcsv_test.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5AjRh2vAsbEYN69BC:-Mn6TDch5ynbuARI7ANJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportcsv_test.go#L40)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] looks like we can remove this
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mmcsp8kBxkgFcgXH_7m:-Mn6WH4Z9WQkdz1okrE2:b7kcrxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L39)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Looks like the linter is going to complain about the unused struct.  

It appears that the library does support other compressors: https://github.com/fraugster/parquet-go/blob/c28e3072a9721f25d59193b9d74c642d20800fe8/compress.go#L154

Although, the exact semantics may be a bit different still since I _think_ parquet compression is at a column level and not a whole-file level.
</blockquote></details>

I'm going to delete the `compressor` field for now, and will address compression in a later pr.
___
*[pkg/ccl/importccl/exportparquet.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcvR6N2r_M9ql7bbF7:-Mn7OZO-1D5aG7591YVQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a263c0ae406480b8367d00d7dbff166779af5a6f/pkg/ccl/importccl/exportparquet.go#L146)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

When you get to this, it might be useful to pick Aaron Zinger's brain as he has done work on the avro encoder where there are similar issues.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5HCLM-URDzUylMxfh:-Mn7OKTpA9sZlZKGsaQt:b-n0vpel) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L113)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Since we know there is more to do here this may be premature, but I wonder if we can attempt this right away in newParquetWriterProcessor just so we get a more immediate error on any unsupported types.
</blockquote></details>

I'm not sure what you're suggesting here. `newParquetColumn` will error out if the type passed in is not supported.
___
*[pkg/ccl/importccl/exportparquet.go, line 297 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5Iulp6Xcy26D1f8X_:-Mn7_2WlEhW0PYj-7MiA:b-rzbvu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L297)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Would it be sufficient to have a method that Reset()'s the data buffer and then reconstruct the parquetWriter?  If so, it might be nice to do that to save on re-allocating our buffer, re-creating the parquet schema, etc.
</blockquote></details>

Good idea. Required a bit of refactoring. Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5KSUv5dzJBkKOZjTA:-Mn7PpQq6e7oNWvnc75n:b-6wm067) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L327)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I would consider removing this commented code and the related TODOs just because I imagine that we'll be handling nulls differently than this CSV implementation since (I assume?) the parquet file format defines how a null value is represented for a given data type and thus I'm guess we don't need the NullEncoding option here.  Might even be best to remove it from the proto as well for now.
</blockquote></details>

I'm going to leave the NullEncoding in the ParquetOptions proto so the proto is not empty. But I've changed export.go, so that the user cannot populate ParquetOptions.NullEncoding -- it will always be null. I've done the same for ParquetWriterSpec.FileCompression.
___
*[pkg/ccl/importccl/exportparquet.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5NqC40YKdJpV8YxIw:-Mn7_oJQ2RdLZwXNbZFX:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L372)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

> ```
> 			// Close exporter to ensure buffer and any compression footer is flushed.
> 			err = exporter.Close()
> 			if err != nil {
> 				return errors.Wrapf(err, "failed to close exporting exporter")
> 			}
> ```

[nit] I know this is matching existing code, but I think it would be a little more clear for this to be right below the Flush() above unless there is a reason that it needs to be down here.
</blockquote></details>

done.
___
*[pkg/sql/export.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcqvWe583bgfh73DW6:-Mn7_y5X7R_Q3UGrzbQO:b3eyifo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a669e6812da765582ba5de576107dee0a7c5ce2/pkg/sql/export.go#L16)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Hrm, perhaps reviewable is confused but this still looks like an issue.
</blockquote></details>

yeah, i fixed this, according to the global diff on github. i think reviewable is confused because i accidentally fixed this on the second commit in this pr, instead of the first commit, where i initially made the change :smiley: 


<!-- Sent fro [...]

2021-10-29 00:32 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @msbutler, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5A9BtDzlkssgITRwE:-Mn8HIUJ9GReT6WylAUF:b-ol9xyr) (no related file):*
Okie dokie. I left a few comments, but I think since your plan is to do a series of follow up PRs to this, perhaps it is best to move towards merging this once you sort through the branch conflicts and such.

> Note that my latest pr has a dirty vendor directory. Everytime i try to rebase to master, i get vendor conflicts... it's a total mess,

You'll get one any time vendor has been updated since you last rebased. 

> Could you point me to an example of a lightweight feature gate?

I don't feel super strongly about the feature gate btw.  If you think it is a good idea, perhaps just using a cluster setting would be best just so we don't need to do anything fancy when we want to test with a real cluster.  You can see a few examples of a non-public cluster setting in pkg/ccl/backupccl/backup_processor.go  (`useTBI` for instance).  I posted a message is slack to see what others feel about using cluster settings for in-progress work like this.

---
___
*[pkg/ccl/importccl/exportcsv_test.go, line 317 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn8KuCa-lgLSufurB1i:-Mn8KuCa-lgLSufurB1j:b-udhec7) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8b41c60c535cc07dbc3874d0c38082613434a5/pkg/ccl/importccl/exportcsv_test.go#L317)):*
> ```Go
> 			} else {
> 				return fmt.Errorf("type not supported :(")
> 			}
> ```

Since we are saving decodedV back into a variable with type `interface{}`, is this type switch doing anything other than asserting that we got back one of the types we think we support?  That is, could we do (warning, code written in comment box):

```golang
			v := row[cols[i].SchemaElement.Name]
			switch vv := v.(type) {
			case []byte, string, int64, float64, bool:
			default:
				t.Fatalf("unexpected type: %T", vv)
			}
			require.Equal(t, truthRows[count][i], v)
```
___
*[pkg/ccl/importccl/exportcsv_test.go, line 357 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn8J2eTCMJ2TlsJyTY0:-Mn8J2eTCMJ2TlsJyTY1:bb15z9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8b41c60c535cc07dbc3874d0c38082613434a5/pkg/ccl/importccl/exportcsv_test.go#L357)):*
> ```Go
> 
> 	err = validateParquetFile(t, paths[0], truth)
> 	if err != nil {
> ```

No need for the err != nil here.  `require.NoError(t, err)` asserts err is not nil.
___
*[pkg/ccl/importccl/exportparquet.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5HCLM-URDzUylMxfh:-Mn8Nb3xAiLTsp-MQo2n:b-xh68bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L113)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

I'm not sure what you're suggesting here. `newParquetColumn` will error out if the type passed in is not supported.
</blockquote></details>

I think I was suggesting that we call `newParquetColumns` inside the `newParquetWriterProcessor` function so that we get any type errors earlier in the execution of the export statement.  That said, I'm sure the exact right place for it without digging into the code more.
___
*[pkg/ccl/importccl/exportparquet.go, line 297 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5Iulp6Xcy26D1f8X_:-Mn8Og-fCrDzK5sW07dZ:b1gv8bj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L297)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

Good idea. Required a bit of refactoring. Done.
</blockquote></details>

If you wanted to go further, I suppose you could have buf, schema, and parquetColumns as members of the exporter struct, then rather than constructing the new exporter have a method on exporter that was like:

```golang
func (c *parquetExporter) Reset() {
	c.buf.Reset()
	c.parquetFileWriter = buildFileWriter(c.buf, c.schema)
}
```

which would probably mean you could keep the construction of schema, parquetColumns, and buf inside the constructor for parquetExporter.  But, I leave that to your discretion.
___
*[pkg/ccl/importccl/exportparquet.go, line 327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5KSUv5dzJBkKOZjTA:-Mn8Dpmy-_6And-e64aA:b6pzzug) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L327)):*
> I'm going to leave the NullEncoding in the ParquetOptions proto so the proto is not empty. 

Protos can be empty without any issue. 


<!-- Sent from Reviewable.io -->

2021-11-01 10:01 UTC, adityamaru commented
Very nice, lays a good foundation for future work!

2021-11-01 10:01 UTC, adityamaru requested changes

2021-11-01 10:01 UTC, adityamaru commented on pkg/ccl/importccl/exportcsv_test.go
> +			if vv, ok := v.([]byte); ok {
nit: can we change to a switch statement, might be more readable.

switch t := v.(type) {
	case int64:
		// Use t to get deocdedV
	case string:
}

2021-11-01 10:01 UTC, adityamaru commented on pkg/ccl/importccl/exportcsv_test.go
> +func TestBasicParquetTypes(t *testing.T) {
Nice!

2021-11-01 19:14 UTC, msbutler reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5A9BtDzlkssgITRwE:-MnRjt-I3nuE5TaJ8GiN:b-qq0ltb) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Okie dokie. I left a few comments, but I think since your plan is to do a series of follow up PRs to this, perhaps it is best to move towards merging this once you sort through the branch conflicts and such.

> Note that my latest pr has a dirty vendor directory. Everytime i try to rebase to master, i get vendor conflicts... it's a total mess,

You'll get one any time vendor has been updated since you last rebased. 

> Could you point me to an example of a lightweight feature gate?

I don't feel super strongly about the feature gate btw.  If you think it is a good idea, perhaps just using a cluster setting would be best just so we don't need to do anything fancy when we want to test with a real cluster.  You can see a few examples of a non-public cluster setting in pkg/ccl/backupccl/backup_processor.go  (`useTBI` for instance).  I posted a message is slack to see what others feel about using cluster settings for in-progress work like this.
</blockquote></details>

I took a look at your slack thread, and it doesn't seem like there's an important reason to feature gate. So, i'm not going to add one.

---
___
*[pkg/ccl/importccl/exportcsv_test.go, line 287 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcVd-7UJIq9TO6pFJJ-r4-287:-MnRBMgb4bdbImuK3fiX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8b41c60c535cc07dbc3874d0c38082613434a5/pkg/ccl/importccl/exportcsv_test.go#L287)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

can we assert len(cols) == len(truthRows[0])?
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportcsv_test.go, line 298 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcVd-7UJIq9TO6pFJJ-r4-298:-MnRBaeXCcqgoXDRgq3K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8b41c60c535cc07dbc3874d0c38082613434a5/pkg/ccl/importccl/exportcsv_test.go#L298)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

instead of this can we assert that fr.NumRows() == len(truthRows)?
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportcsv_test.go, line 306 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcVd-7UJIq9TO6pFJJ-r4-306:-MnRAm9mAL8eX7ouFYx5:b4agxp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8b41c60c535cc07dbc3874d0c38082613434a5/pkg/ccl/importccl/exportcsv_test.go#L306)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: can we change to a switch statement, might be more readable.

switch t := v.(type) {
	case int64:
		// Use t to get deocdedV
	case string:
}
</blockquote></details>

Done, reposting inline comment:

// TODO (MB): as we add more type support, this
// test will be insufficient: many go native types are encoded as
// []byte, so in the future, each column will have to call it's own
// custom decoder ( this is how IMPORT Parquet will work)
___
*[pkg/ccl/importccl/exportcsv_test.go, line 317 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn8KuCa-lgLSufurB1i:-MnRAxoX0SYHS9kyM_2N:bl63psl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8b41c60c535cc07dbc3874d0c38082613434a5/pkg/ccl/importccl/exportcsv_test.go#L317)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Since we are saving decodedV back into a variable with type `interface{}`, is this type switch doing anything other than asserting that we got back one of the types we think we support?  That is, could we do (warning, code written in comment box):

```golang
			v := row[cols[i].SchemaElement.Name]
			switch vv := v.(type) {
			case []byte, string, int64, float64, bool:
			default:
				t.Fatalf("unexpected type: %T", vv)
			}
			require.Equal(t, truthRows[count][i], v)
```


</blockquote></details>

Done, note the inline comment I added. 
___
*[pkg/ccl/importccl/exportcsv_test.go, line 329 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcVd-7UJIq9TO6pFJJ-r4-329:-MnRC-Sw1dYU_xR9pDUx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8b41c60c535cc07dbc3874d0c38082613434a5/pkg/ccl/importccl/exportcsv_test.go#L329)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportcsv_test.go, line 357 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn8J2eTCMJ2TlsJyTY0:-MnRC8qm4Msyc2rjhtez:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8b41c60c535cc07dbc3874d0c38082613434a5/pkg/ccl/importccl/exportcsv_test.go#L357)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

No need for the err != nil here.  `require.NoError(t, err)` asserts err is not nil.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5HCLM-URDzUylMxfh:-MnRE2lU1l3Ss5OMxtRJ:b-rqhrya) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L113)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I think I was suggesting that we call `newParquetColumns` inside the `newParquetWriterProcessor` function so that we get any type errors earlier in the execution of the export statement.  That said, I'm sure the exact right place for it without digging into the code more.
</blockquote></details>

I see. I will keep as is for now, and will consider this change when I attempt to refactor the CSV Exporter and Parquet Exporter to delete new code. 
___
*[pkg/ccl/importccl/exportparquet.go, line 297 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5Iulp6Xcy26D1f8X_:-MnRbO7l6kLdA-P-jGl_:b986ou0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L297)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

If you wanted to go further, I suppose you could have buf, schema, and parquetColumns as members of the exporter struct, then rather than constructing the new exporter have a method on exporter that was like:

```golang
func (c *parquetExporter) Reset() {
	c.buf.Reset()
	c.parquetFileWriter = buildFileWriter(c.buf, c.schema)
}
```

which would probably mean you could keep the construction of schema, parquetColumns, and buf inside the constructor for parquetExporter.  But, I leave that to your discretion.
</blockquote></details>

ah, good idea. Makes it look more like csvExporter.
___
*[pkg/ccl/importccl/exportparquet.go, line 327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-Mn5KSUv5dzJBkKOZjTA:-MnRgj4l-fOGi5n_v3Cn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4781f7153d3e74464fc3e0b46ec4e3c78034c8/pkg/ccl/importccl/exportparquet.go#L327)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

> I'm going to leave the NullEncoding in the ParquetOptions proto so the proto is not empty. 

Protos can be empty without any issue. 
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/exportparquet.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71868#-MmcVd-7UJIq9TO6pFJN-r4-86:-MnRCyczAqH296VYvNyi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8b41c60c535cc07dbc3874d0c38082613434a5/pkg/ccl/im [...]

2021-11-01 23:32 UTC, stevendanna approved these changes
To pass CI, it looks like you'll need to run `make bazel-generate` and commit the results.

2021-11-01 23:32 UTC, stevendanna commented on pkg/ccl/importccl/exportparquet.go
> +// Copyright 2018 The Cockroach Authors.
2021

2021-11-02 12:42 UTC, msbutler commented on pkg/ccl/importccl/exportparquet.go
> +// Copyright 2018 The Cockroach Authors.
done

2021-11-02 12:43 UTC, msbutler commented
regenerated the bazel stuff, with `./dev generate bazel` which i believe is the new bazel generate command.

2021-11-02 12:50 UTC, adityamaru approved these changes
Nice work on this! I think there are things in the code that will get gradually cleaned up as we "productionize" this so lets get this merged 🥳

2021-11-02 14:12 UTC, msbutler commented
bors r+, r= adityamaru, stevendanna

2021-11-02 16:02 UTC, merged