cli: commands to perform unsafe recovery on quorum loss
cockroachdb/cockroach pull request #71996
Opened 2021-10-26 18:55 UTC by aliher1911

Previously, if range quorum was lost because too many replicas becoming
permanently unavailable, cockroach could either be recovered from
a backup, or debug-unsafe-remove-replicas command applied on each node
to recover to a potentially inconsistent state.
This command has some limitations on how it decides which replica is
the most up to date one and in not usually recommended.
This diff introduces the new process for the recovery. It doesn't
guarantee consistency after recovery, but it provides additional checks
and lays the foundation for further recovery work.

Release note: None

Addresses: #71863, #71862, #71861

2021-11-24 15:26 UTC, aliher1911 commented
I'm not keen on splitting this PR as if we cut it along the original lines in issues, each part would provide no meaningful functionality by itself. Currently it covers the workflow end-to-end and only provides functionality that we already have with respect to how the replica is picked. It also provides a data driven parser to make tests for newer use cases.
That said, I can try to cut it in smaller bits if needed before we are too deep into the review of actual code.

2021-11-25 16:00 UTC, tbg requested changes, later dismissed
Phew, that was a big one. Looks good so far! A few high-level comments:

- Not everything is implemented here. This is expected but as a reviewer I'm left wondering which of the follow-up work you're aware of. For a PR this big I'd expect a much more comprehensive commit message that references issues (which also helps reference this PR from them in turn) and points out what's in scope for this PR and what isn't. For example, I'm left wondering if the "check that recovered cluster doesn't have holes in keyspace" is tracked anywhere or if I need to point it out and check. The PR should let me know where we are leaving things. Since it doesn't, I was reviewing with uncertainty about what to point out and what to assume would be taken care of later.
- The comments in general could be more detailed. A fair amount of them that exist are sort of saying the obvious thing without explaining the greater scheme of things (the comments were telling me what the next line does, rather than telling me why). I realize that this PR is still somewhat in progress and I support getting review as early as possible, so this is just a reminder to keep comments and documentation in mind as the foundations settle and the PR gets closer to a merge, at which point I'll also try to give more suggestions - it's just really tiring at this size of PR
- A number of my comments suggest a stricter separation of `cli`-like functionality (interactivity, interacting with the flags, etc) and the meat. I do like the idea of pulling the business logic into `pkg/kv/kvserver/loqrecovery` so let's discuss (with the other reviewers) whether to do that. I'm strongly in favor but I've been overruled before :-), kooking for @erikgrinaker's opinion in particular.
- The datadriven stuff looks great, thanks for the effort that must have taken. I didn't review this in detail yet though, will wait for the other dust to settle.

> each part would provide no meaningful functionality by itself.

I agree that once you have a 2700+ LOC PR it's not worth splitting it up. But also it was painful to review this giant chunk, I've been at it for a few hours and I'm still not done. There is generally an inverse relationship between the size of a commit and the quality of the review (which again correlates with code quality, documentation, etc). Perhaps the issues weren't the right way to split up the work, that is well possible, but in my opinion there is always some way to make it easier for the reviewer to provide a high-quality review by carving out chunks and thus "checkpointing" not only the work but also the scope and context. Concretely, here the cli scaffolding could've been set up in a separate commit. `cli` stuff is very different from the actual recovery logic and it has its own idiosyncrasies and reviewer mindset that I don't need to have for the rest of the review. Doing it that way might've presented an earlier opportunity for a reviewer like myself to suggest the `kvrecovery` package and the separation of concerns, which now comes with extra work for you, and a extra review overhead as well. Doing this perfectly for one reviewer's taste is a a bit of an art and for two mostly impossible, but I think here it would've been a good idea for all but the most exotic reviewers.

> Reviewed 10 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MpMk84hDT9NpLRzEGjW:bu4jfja)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @erikgrinaker)

___
*[pkg/cli/debug.go, line 1520 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMPGT491PIFA8Sh9qQ:-MpMPGT491PIFA8Sh9qR:b-y0wlvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug.go#L1520)):*
> ```Go
> }
> 
> // debugSubCommandsForRocksDB lists debug subcommands that access rocksdb through the engine
> ```

`s/rocksdb/pebble/i` throughout.
___
*[pkg/cli/debug.go, line 1524 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMPYmeClvMc5Gi69Jd:-MpMPYmeClvMc5Gi69Je:bgu2h5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug.go#L1524)):*
> ```Go
> // This list is separate from debugCmdsForRocksDB as it is used to enable encryption options
> // but not when building top level debug command list.
> // Note: do NOT include commands that just call rocksdb code without setting up an engine.
> ```

After reading this comment, I still have no idea why there are two lists and when which one goes where. All of the commands in `debugCmdsForPebble` set up an engine, and yet they're all *not* in this list. Don't they also need encryption flags? See if you can clear this up.
___
*[pkg/cli/debug.go, line 1551 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMQ0wI88680-GZmlQ7:-MpMQ0wI88680-GZmlQ8:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug.go#L1551)):*
> ```Go
> // DebugCommandsRequiringEncryption lists debug (sub)commands that access rocksdb through the engine
> // and need encryption flags (injected by CCL code).
> // Note: do NOT include commands that just call rocksdb code without setting up an engine.
> ```

ditto
___
*[pkg/cli/debug.go, line 1554 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMQ2Gf23FA5WGiG5tp:-MpMQ2Gf23FA5WGiG5tq:b-forxc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug.go#L1554)):*
> ```Go
> var DebugCommandsRequiringEncryption = append(debugCmdsForPebble, debugSubCommandsForPebble...)
> 
> // debugInteractive contains commands that need a confirmation flag
> ```

.

`debugNeedsConfirmation` instead of `debugInteractive`?
___
*[pkg/cli/debug.go, line 1665 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMQG_i7ijRGdHTY79W:-MpMQG_i7ijRGdHTY79X:b-dsr40h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug.go#L1665)):*
> ```Go
> 
> 	f = recoverDeadReplicaPlanCmd.Flags()
> 	f.StringVarP(&debugDeadReplicaPlanOpts.outputFileName, "plan", "o", "replica-remove-plan.json",
> ```

"output-file" instead of "plan" to keep things consistent?
___
*[pkg/cli/debug.go, line 1712 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMQYFt4PFJkK4S2DUG:-MpMQYFt4PFJkK4S2DUH:byexvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug.go#L1712)):*
> ```Go
> 
> 	for _, cmd := range debugInteractive {
> 		AddPersistentPreRunE(cmd, validateConfirmationFlag)
> ```

Unless I'm missing some technicality that makes this a non-starter, the idiomatic way of doing this is to add a new type that implements `pflag.Value` (the `Set` method does the validation), and to use `f.Var` instead of `StringVar`.
___
*[pkg/cli/debug.go, line 1714 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMQXHw9zm6Wn11h6zF:-MpMQXHw9zm6Wn11h6zG:b1bolvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug.go#L1714)):*
> ```Go
> 		AddPersistentPreRunE(cmd, validateConfirmationFlag)
> 		f = cmd.Flags()
> 		f.StringVar(&interactivePromptOpts.action, "confirm", "p",
> ```

snazzy!
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMSaJK9yfZ2zfWIhEP:-MpMSaJK9yfZ2zfWIhEQ:b4ctx3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L104)):*
> ```Go
> 0. Stop the cluster
> 
> 1. Run cockroach debug recover collect-info on every node to collect
> ```

Could you make sure to point out that the commands need to be invoked per store, not once per node. (Or once per node, supplying all stores -th [...]

2021-11-25 20:37 UTC, erikgrinaker reviewed
Initial pass to reply to comments, will review tomorrow.

> I'd expect a much more comprehensive commit message

+1

>I do like the idea of pulling the business logic into `pkg/kv/kvserver/loqrecovery` so let's discuss (with the other reviewers) whether to do that.

I agree. Especially since we want to do some of this stuff online down the road, so the server process would presumably need to import this logic too. But also just because non-trivial logic should be separated out from the user interface anyway.

> Reviewed 2 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MpNbb3_4Tmo9wrUhHl8:byffkxo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @knz, and @tbg)

___
*[pkg/cli/debug.go, line 1665 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMQG_i7ijRGdHTY79W:-MpNidnUBsAp1ADEpyZ7:b26tku3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug.go#L1665)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

"output-file" instead of "plan" to keep things consistent?
</blockquote></details>

I'd prefer "plan" over "output-file" in general, since it's more specific.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMVyUOC4U6LJk9YKbK:-MpNjqYAAqLOICpyI0aZ:bhrq75i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L176)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Could it be confusing to switch between Stdout and Stderr for interactiveness? I think we should consider keeping it simple and say that unless you're fully onboard with `y` everywhere, you have to provide a file. Otherwise, you can use stdout and there won't be anything there except the file. Or we say the prompt is always on stderr, I assume that would also just work.
</blockquote></details>

Yeah, I'd keep it simple and just stick with stderr for the prompts.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 256 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMVPpV4WJ_mcLkduC3:-MpNkMm78YcWWEKHmMZA:bk4bco4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L256)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

We use `jsonpb` elsewhere, see for example [here](https://github.com/cockroachdb/cockroach/pull/72732/files#diff-dc8c107eaa827dd0e9446540cc65ee244f5c8111f27b720d62366ee3f8d6a517R87), we should probably use it here too.
</blockquote></details>

Yes, always use `jsonpb`. The Protobuf spec [mandates a canonical JSON encoding](https://developers.google.com/protocol-buffers/docs/proto3#json) for Protobuf messages, which is incompatible with the Go stdlib's JSON encoding convention. Not only does this break interoperability, but it can also cause data loss for certain datatypes and structures when passing a Protobuf through a stdlib Marshal/Unmarshal cycle.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMW_Iy70K-JQg-Fpw5:-MpNlhIF69tZ36UWLrOI:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L267)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Please refactor all of these methods such that they don't rely on the global state. That is, make a little trampoline where the actual command sets up the parameters and then invokes a method that has all of the business logic (passing all of the configuration directly to it). For inspiration, see https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug.go#L1077 which is the business logic. The command only has the setup and plumbing as well as the confirmation prompt, but nothing that you may want to unit test. I would like the datadriven tests to not touch any of the config state in `cli`, i.e. operate purely on the business logic. (Haven't gotten to that part of the review yet).
</blockquote></details>

+1
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMbH-22SuRVKWaKWfj:-MpNm6rk1Oubagn7Dg06:b4y0bzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L446)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It's almost not worth quibbling about this, but as I already brought up elsewhere I'm not sure if it's worth asking for prompts on commands that simply write the desired output file. I'd trust @knz's judgment call on that but I don't think this is what we consistently do elsewhere in the cli. I do think it makes sense to avoid overwriting files but at least the `ballast` command simply errors out:

```
tobias@td:~/go/src/github.com/cockroachdb/cockroach$ ./cockroach debug ballast -z 1MiB foo.asd
tobias@td:~/go/src/github.com/cockroachdb/cockroach$ ./cockroach debug ballast -z 1MiB foo.asd
ERROR: file already exists
Failed running "debug ballast"
```

I don't feel strongly about this here. Just curious what the "right" thing to do is. I do like to keep it simple, and there's enough code here around this handling to have a bug.
</blockquote></details>

I agree, error out and optionally provide a `-f,--force` flag to overwrite. If this isn't already the case, there should also be a way to opt out of interactive operation entirely (if nothing else, for testability).
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMdQh15QXZ4POS7RI-:-MpNfJBB16jFAXjGqooN:b-uo2cdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L545)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This looks like a TODO, make it a proper one. As is, this is potentially causing confusion about what the code is or is not doing.

Also, add a TODO (maybe replacing this one?) about writing to logs the fact that the recovery happened. We need to discuss what the right logs are. Ideally you want audit-type logging, but this is the `cli` so we don't have that luxury. We could stash a file in the store directory or write a store-local key that then translates, on node startup, into a proper log structured log entry (without removing the store key - can't hurt to remember that fact forever). I think that is the right way to do it. Definitely not for this PR, but make sure to file an issue. (cc @erikgrinaker)
</blockquote></details>

Yeah, we'll have to stash this somewhere in the store. I prefer a key over a file because it's more resistant to deliberate or accidental manipulation, but a store-local key isn't ideal because the info will be lost if the node is decommissioned or the store is removed. I think we'll have to buffer it as a store-local key temporarily, and then move it into the audit log and the replicated key-space once the node starts back up.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMfDNW9J68SLyCvmpv:-MpNniXcBynEHub2MLSj:befadm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L567)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I've been thinking that it might be the better approach to always expect a valid plan. If the plan is invalid and the oper [...]

2021-11-26 10:26 UTC, aliher1911 commented
Before we move to any further. I realized how ballooned this PR became with error handling that was added at later stages. I can split that into smaller pieces by collect-plan-apply boundary. At least into multiple commits if that makes any sense. I think some comment history might be lost, but I'll address all existing bits before doing split.
What do you think?
That would also separate datadriven tests into separate commit which was my concern initially as it makes commits non self sufficient.

2021-11-26 10:29 UTC, aliher1911 reviewed
> I do like the idea of pulling the business logic into pkg/kv/kvserver/loqrecovery so let's discuss (with the other reviewers) whether to do that.
I like this idea. I think current approach is almost there as there are functions that are called by cli and they do flags and whatever interactions we may have, and they further delegate 'compute' to functions that do processing. There's a small last minute leak of abstraction there, but I have idea how to fix that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MpQmG_DBPggqJoCbfo2:b-3gp04)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @knz, and @tbg)



<!-- Sent from Reviewable.io -->

2021-11-30 10:53 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMSaJK9yfZ2zfWIhEP:-MpfvUZa80uEiM3xkL1K:bgchnnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L104)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Could you make sure to point out that the commands need to be invoked per store, not once per node. (Or once per node, supplying all stores -that should both work).
</blockquote></details>

I'll put that in the collect-info description. I think that is more appropriate there.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMS3voCJD8HVSWBZYQ:-MpfboZO8T0F1KJcd5Fi:b-ap9mth) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L143)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Without args it goes to stdout? Or do you want `ExactArgs(1)`. Explain it in `Long` above if it is in fact optional (but probably not a good idea, since stdout receives other writes too due to prompt?)
</blockquote></details>

The idea behind optional output was to ssh command and capture output. All other logging goes to stderr if output is stdout. That would allow ssh to just return all the info without a need for scp-ing back temporary files.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMVyUOC4U6LJk9YKbK:-MpffDpy1Vu6U8vLsb3I:b-vtwps2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L176)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yeah, I'd keep it simple and just stick with stderr for the prompts.
</blockquote></details>

I think both things are reasonable. Only allow stdout with y/n and always use stderr for prompts regardless to reduce moving parts.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMT2-kAP7bOLpdaeC9:-MpfvsCb8wPPgWvpBKk7:b1vmm4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L178)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Does this command really need confirmation?
</blockquote></details>

It asks the confirmation to overwrite existing file. It is currently used to write all json marshallable output which is replica info as well as plan. I can drop it in favour of always overwriting the file.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMUGTeAUKvSaJDCOEA:-MpfwUcf4plYFOWnoojt:biolknu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L226)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Explain that this step also runs various sanity checks that try to prevent the operator from embarking on a futile recovery attempt.
</blockquote></details>

In its current form it describes what this PR does. e.g. the action is identical to current recovery. Subsequent PR will change our plan method and then this description would need to be changed.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 301 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMY9Oo5pUorjRMti4L:-MphgCpYB_cGAnX7sjfH:bcctqi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L301)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: `var quorum ReplicaUpdate` is every so slightly more idiomatic (imo) since the canonical zero-element slice is the nil value, not the empty slice.
</blockquote></details>

I made such a hack because marshalling nil to json produced nil string vs [], but that might be an artifact of json. I'll rather handle that in marshalling method.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMZ2eFBn8qV_XwEupk:-Mphgae3CIESx-onCOrN:b-k4xn98) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L376)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

If there is a survivor whose ReplicaID is `>= desc.NextReplicaID` we need to error out, do we do that now? In fact better than erroring out would be picking that other replica as a survivor, but let's make sure we catch & test this problem first and we can fix it later, it's unlikely to make much of a difference in practice.
</blockquote></details>

That't the next PR bit, this is just mimicking what we already have.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpM_uO3-Q4SQoPwNiZS:-MphoZTz0MrMOwQR7wUr:b-xwigxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L406)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

// The difference between all referenced StoreIDs (missingStoreIDs) and the present StoreIDs (presentStoreIDs) should exactly equal the user-provided list of dead stores (deadStores), and the former must be a superset of the latter (since each descriptor found on a store references that store). Verify all of these conditions and error out if one of them does not hold.

We need to have unit tests for all of these cases (haven't fully reviewed yet, maybe they're already there).
</blockquote></details>

We have unit tests for those case outside of datadriven ones. Making a datadriven seems an overkill here and to verbose.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMbH-22SuRVKWaKWfj:-MphhvD2BfFVLwhVvRZD:b-py3e04) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L446)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I agree, error out and optionally provide a `-f,--force` flag to overwrite. If this isn't already the case, there should also be a way to opt out of interactive operation entirely (if nothing else, for testability).
</blockquote></details>

Agreed, I'll just make it fail here if file is already present.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMdrpW1Jk1LmsLfZDz:-MpgKnGk6lMhanuz2zlH:bgyfwzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L528)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I am confused why the concept of a NodeID plays a role here. Everything operates on StoreIDs - the designated survivors plan is logically a map from RangeID to StoreID (`StoreID` is unique across cluster). Try to keep NodeID out of it and if we absolutely need it, make clear why. (It's fine to use it for validation, but it looks like we're using it for more than that).
</blockquote></details>

The only reason that NodeID is present here is to [...]

2021-11-30 14:55 UTC, erikgrinaker reviewed
I'm only half-way through an initial superficial review, but flushing the comments that I have. Will continue later.

> Before we move to any further. I realized how ballooned this PR became with error handling that was added at later stages. I can split that into smaller pieces by collect-plan-apply boundary. At least into multiple commits if that makes any sense. I think some comment history might be lost, but I'll address all existing bits before doing split.
> What do you think?

I'm not sure if the extra effort of splitting it up into multiple commits is going to be worth it after-the-fact. I'll let @tbg weigh in, but I'm fine with keeping this PR as is and getting it across the line instead.

I do agree that this should've been split up into multiple commits though -- if splitting by command didn't make sense, another option might have been along the functionality/UI/test-harness boundaries.

---

I tried using this on a cluster with a few borked ranges. Notes below:

- Running `cockroach debug recover collect-info` in a random directory just output `null` and exited, it needs a more informative error.

- `collect-info` should output a newline after the JSON string.

- I'm getting a couple of log messages that seem entirely unrelated to the command (we're not going to open 8192 files simultaneously here, right?):

    ```
    W211130 13:49:28.948232 1 server/config_unix.go:113  [-] 1  soft open file descriptor limit 8192 is under the recommended limit 15000; this may decrease performance
    W211130 13:49:28.948232 1 server/config_unix.go:113  [-] 1 +please see https://www.cockroachlabs.com/docs/v22.1/recommended-production-settings.html for more details
    ```

- `-p, --confirm` appears to default to `y` (at least that's what `--help` says), shouldn't it default to `p`?

- `make-plan` doesn't seem to work:

    ```
    $ cockroach debug recover make-plan --dead-store-ids 4,5 s1.json s2.json s3.json 
    ERROR: failed to unmarshal replica info from file s1.json: unexpected type *[]loqrecoverypb.LocalRangeInfo does not implement proto.Message
    Failed running "debug recover make-plan"
    ```

That's about as far as I got now. This really needs CLI tests as well, to make sure all of the plumbing works.

> Reviewed 1 of 13 files at r1, 2 of 16 files at r3, 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-Mpl1Pnf3PhKuDlYZ91D:bp06neh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug.go, line 1653 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MplGobA1i47KfG1STTT:-MplGobA1i47KfG1STTU:b-8xofk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug.go#L1653)):*
> ```Go
> 	f.StringVarP(&debugRecoverPlanOpts.outputFileName, "plan", "o", "replica-remove-plan.json",
> 		"filename to write plan to")
> 	f.IntSliceVar(&debugRecoverPlanOpts.deadStoreIDs, "dead-store-ids", nil,
> ```

I wonder if we really need this option. Since this command takes input from all existing stores across all existing nodes, we have the information we need to deduce the dead stores (i.e. stores that are not included in the given files). I believe the covering property allows us to detect ranges that are completely gone (i.e. that would have been contained entirely on the dead stores). What's the upside?
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpRWtda731agefR1PuE:-MpRWtda731agefR1PuF:b7l1hih) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L93)):*
> ```Go
> var debugRecoverCmd = &cobra.Command{
> 	Use:   "recover [command]",
> 	Short: "quorum recovery commands",
> ```

This needs to be more specific.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpRXI4m89mWA2yBfSbH:-MpRXI4m89mWA2yBfSbI:b9iony0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L94)):*
> ```Go
> 	Use:   "recover [command]",
> 	Short: "quorum recovery commands",
> 	Long: `Set of commands to collect process and apply quorum recovery.
> ```

This whole section touches on the main points, but it could be more explanatory and specific. What exactly does it do? What are the situations in which it is or isn't appropriate? What are the risks? When can it not be used? Can the cluster continue to be used afterwards? Etc. Might also be good to include concrete examples of commands.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpRZPJS6fYg1eJG9Dt5:-MpRZPJS6fYg1eJG9Dt6:bgumj49) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L135)):*
> ```Go
> var recoverDeadReplicaCollectCmd = &cobra.Command{
> 	Use:   "collect-info [destination-file]",
> 	Short: "collect replica information for range recovery in event of quorum loss",
> ```

The "for range recovery in event of quorum loss" is a bit redundant, since it's given by the main `recover` command. Instead, consider being more specific, e.g. "from the given stores".
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMS3voCJD8HVSWBZYQ:-Mpl2pw56xn_ncqtYKC_:b-ipr50b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L143)):*
>That would allow ssh to just return all the info without a need for scp-ing back temporary files.

This is a nice property. Do we really need to log anything apart from errors to stderr in this case?
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 301 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMY9Oo5pUorjRMti4L:-Mpl36lUEegBeJEGOAUc:b678sq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L301)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I made such a hack because marshalling nil to json produced nil string vs [], but that might be an artifact of json. I'll rather handle that in marshalling method.
</blockquote></details>

Might be preferable and easier to just use an empty slice.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl8RPz6qyCCLZFa5IS:-Mpl8RPz6qyCCLZFa5IT:b-yh35m2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L55)):*
> ```Go
> 		return "p"
> 	}
> 	return fmt.Sprintf("unknown confirm action flag value %d", *l)
> ```

This should panic, since getting the value into this state is a programming error.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 171 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl8jf7AUoka77nA7DB:-Mpl8jf7AUoka77nA7DC:bbpdz1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L171)):*
> ```Go
> 	Short: "collect replica information for range recovery in event of quorum loss",
> 	Long: `
> Collect replica information by reading descriptors from underlying stores.
> ```

Do we expect end-users to know what a descriptor is?
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 197 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl9yBHDqmDSFQgw3m6:-Mpl9yBI4QYHyxjRj3Ak:bia52qw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L197)):*
> ```Go
> 
> 	var  [...]

2021-11-30 15:15 UTC, aliher1911 reviewed
Looks like splitting logic out of cli borked something.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MplPS6s50gM9d4c5cYK:bpr1kve)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)



<!-- Sent from Reviewable.io -->

2021-11-30 21:10 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug.go, line 1653 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MplGobA1i47KfG1STTT:-MplXt-f62hPXbjLQtnL:bcm2qme) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug.go#L1653)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I wonder if we really need this option. Since this command takes input from all existing stores across all existing nodes, we have the information we need to deduce the dead stores (i.e. stores that are not included in the given files). I believe the covering property allows us to detect ranges that are completely gone (i.e. that would have been contained entirely on the dead stores). What's the upside?
</blockquote></details>

I think this is a reasonable sanity check for the case where you forgot to provide --store= for some stores or missed some nodes. We won't blindly drop data on those.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpRWtda731agefR1PuE:-MpmF9oB7W5-9-OJyfp_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L93)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This needs to be more specific.
</blockquote></details>

Done.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpRXI4m89mWA2yBfSbH:-MpmdMGp4nR7He5na21w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L94)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This whole section touches on the main points, but it could be more explanatory and specific. What exactly does it do? What are the situations in which it is or isn't appropriate? What are the risks? When can it not be used? Can the cluster continue to be used afterwards? Etc. Might also be good to include concrete examples of commands.
</blockquote></details>

Done.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpRZPJS6fYg1eJG9Dt5:-MpmCg-135E5JBXVh_uS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L135)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

The "for range recovery in event of quorum loss" is a bit redundant, since it's given by the main `recover` command. Instead, consider being more specific, e.g. "from the given stores".
</blockquote></details>

Done.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMS3voCJD8HVSWBZYQ:-MplYeoD6M5I3i-F5rtV:bctrpfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L143)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

>That would allow ssh to just return all the info without a need for scp-ing back temporary files.

This is a nice property. Do we really need to log anything apart from errors to stderr in this case?
</blockquote></details>

Not intentionally, no. Now everything is stderr driven.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 301 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMY9Oo5pUorjRMti4L:-MpmG1b-3CQojOKN-YED:b30463f) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L301)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Might be preferable and easier to just use an empty slice.
</blockquote></details>

Since the value is now returned from a function handling empty slice in a "typical" was seems reasonable.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl8RPz6qyCCLZFa5IS:-Mpm3_fy9cxNMNBfps2o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L55)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This should panic, since getting the value into this state is a programming error.
</blockquote></details>

Done.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 171 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl8jf7AUoka77nA7DB:-MpmCfiuARJe92mSK6YY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L171)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Do we expect end-users to know what a descriptor is?
</blockquote></details>

Done.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 197 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl9yBHDqmDSFQgw3m6:-Mpleikj0ypEb1AFjyGP:b-3333wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L197)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Do we really need to open all of the stores simultaneously? Seems like we could just iterate over the stores and collect info for each one separately. The same goes for the other commands.
</blockquote></details>

For collection it is doable, but would need some jumping through the hoops to run over memory stores that datadriven test uses.
For updates operation batches are prepared upfront with summary presented to the user to confirm before proceeding with destructive actions. If we open stores one by one, we'll have to confirm many times which would pull more logic into cli part which is not ideal.
So unless this is really a problem, I'd rather have methods in recovery operate on stores passed to them.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 222 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl9DGC-PoLWiwtztcy:-MpmEzssAOj9zcZCMrs9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L222)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

> ```
> 	Short: "Generate replica removal plan range recovery in event of quorum loss",
> 	Long: `
> Make plan aggregate info obtained from all nodes using debug recover collect-info
> command and devises a plan that would to recover from loss of quorum.
> ```

This should be rewritten for clarity.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MplC67t-L5g03yZD_1h:-MpmdSzk3OwJnZ6k4dLq:b7jr6rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/kv/kvserver/loqrecovery/recovery.go#L37)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

It seems unnecessary to introduce additional logging infrastructure specifically for this set of commands. I'd argue that we should either return structured results which the caller can decide how to present, and/or use the standard logging facilities for progress output along with a structured error for any failures such that  [...]

2021-12-01 13:24 UTC, erikgrinaker reviewed
Notes from another run:

- `collect-info` does not have a newline after the output:

    ```
    $ cockroach debug recover collect-info -s ~/local/3/data/ >s3.json
    W211201 11:09:30.781688 1 server/config_unix.go:113  [-] 1  soft open file descriptor limit 8192 is under the recommended limit 15000; this may decrease performance
    W211201 11:09:30.781688 1 server/config_unix.go:113  [-] 1 +please see https://www.cockroachlabs.com/docs/v22.1/recommended-production-settings.html for more details
    Collected info about 55 replicas.erik@gceworker-grinaker recover $
    ```

- `make-plan` is very verbose, and it's unclear to me as a user what do to with this information (it seems more like debugging output):

    ```
    $ cockroach debug recover make-plan --dead-store-ids 4,5 s1.json s2.json s3.json 
    Info:
      found available stores: s1, s2, s3
      not designated survivor, skipping: r1:/{Min-System/NodeLiveness} [(n1,s1):1, (n3,s3):2, (n5,s5):3, (n2,s2):4, (n4,s4):5, next=6, gen=8]
    [...]
      replica has not lost quorum, skipping: r4:/System{/tsd-tse} [(n2,s2):4, (n4,s4):2, (n1,s1):5, next=6, gen=12]
    [...]
      replica has lost quorum, recovering: r55:/Table/52/1/-92222461369478{85149-37122} [(n4,s4):5, (n5,s5):2, (n3,s3):3, next=6, gen=16, sticky=1638283477.384712889,0] -> node_id:3 store_id:3 range_id:55 start_key:"\274\211\200\200\004\000\000\000\000\273\243" new_replica:<node_id:3 store_id:3 replica_id:6 > next_replica_id:7
    [...]
    {"updates": ... }Plan created
    ```

    The "not designated survivor" message in particular is confusing. This range still has quorum, so why is it talking about designated survivors? Also, "replica has lost quorum, recovering" makes it sound like it actually went ahead and recovered the range -- make it clear that it's only marking/scheduling it for recovery. We also need a newline between the JSON output and "Plan created".

    Generally, we should either just not output anything that is not significant or relevant to the user, or at least make it very clear whether the information requires further action or investigation from the user or not. Considering that many clusters have as many as 100.000 ranges and half a million replicas, we may also just want to output a summary rather than a separate line for each replica. Remember, this is likely to be used in a stressful situation, and additional noise and uncertainty is not helpful.

    Also, once the plan is generated, it would be useful to know which stores need to have the plan applied. We have clusters with as many as 80 nodes and 640 stores, and we often won't have to apply the plan to all of them. Even in my test with 5 nodes, it turns out I only need to apply the plan on 2 out of the remaining 3 nodes.

- If I just run `apply-plan` in a random directory, it just says "No updated planned on this node". Apart from the typo, it should either require a `-s` parameter or check whether the current directory is a valid store directory (I suppose this applies with `collect-into` too).

- `apply-plan` could be more specific about what it's about to do:

    ```
    Info:
      updating replica for r77:/Table/52/1/-9222246136947254424
      updating replica for r78:/Table/52/1/-9222246136947206397
      updating replica for r114:/Table/52/1/-9222246136947128279
    ```

    It should say something like "making replica (n3,s3):3 for range r77:/Table/52/1/-9222246136947254424 the only replica, discarding (n2,s2):1, (n5,s5):2"

- After running `apply-plan` I was able to start the cluster back up and run a `SELECT COUNT(*)` across the table (yay!). However, some of the ranges still showed an outdated range descriptor, e.g.:

    ```
    /-9222246136947584832 | /-9222246136947506714 |       75 |     82.883198 |            3 | cloud=local,region=local,zone=local | {3,4,5}  | {"cloud=local,region=local,zone=local",,}

    ```

    Not sure what's going on here, since r75 should have been rewritten with 3 as its sole survivor, and all the nodes were cold-started. It did eventually resolve though, and all the ranges were properly upreplicated.

> Reviewed 2 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MppvCrwAf4gb3S_3cTF:bqa3fsq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug.go, line 1653 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MplGobA1i47KfG1STTT:-MppuOpyCR6Qip1iIqCL:bxpjrvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug.go#L1653)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I think this is a reasonable sanity check for the case where you forgot to provide --store= for some stores or missed some nodes. We won't blindly drop data on those.
</blockquote></details>

I suppose.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpRXI4m89mWA2yBfSbH:-Mpq5eVQ5_8atjnMOaKm:b-ocyz76) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L94)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. I think we should mention that we strongly recommend the data be migrated into a fresh cluster, since we may have violated internal invariants that can cause further damage or failures in the future. We don't have tooling to verify SQL or other system invariants, and I don't think it's feasible for users to vet this properly without intimate knowledge of CRDB internals.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl8RPz6qyCCLZFa5IS:-MppgsBWEUP8ppoYNcNq:b-1vgjhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L55)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I guess we should use `log.Fatalf` here. I see we're not consistent about this in the CLI code (there's lots of panics around too), but I think we generally prefer `log.Fatalf` over bare panics, at least in the main codebase.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 197 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl9yBHDqmDSFQgw3m6:-Mpq777767lfswTBX_Tv:b7vu5gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L197)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

For collection it is doable, but would need some jumping through the hoops to run over memory stores that datadriven test uses.
For updates operation batches are prepared upfront with summary presented to the user to confirm before proceeding with destructive actions. If we open stores one by one, we'll have to confirm many times which would pull more logic into cli part which is not ideal.
So unless this is really a problem, I'd rather have methods in recovery operate on stores passed to them.
</blockquote></details>

Sure, I guess that's fine. My concern here is exceeding open file limits, I don't know how many files these stores typically keep open. But I suppose it'll generally be run in the same environment as the main `cockroach` binary. We can consider revisiting this if it turns out to actually be a problem, since there's a pretty simple workaround anyway (bumping the limits).
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 185 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpq6Sxo0xmko-Y0n00Z:-Mpq6Sxo0xmko-Y0n00_:b73nr5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/ [...]

2021-12-01 14:14 UTC, aliher1911 commented
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MplC67t-L5g03yZD_1h:-MpqKVBE9Ed-nrPZaBYw:b-z0qr07) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/kv/kvserver/loqrecovery/recovery.go#L37)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I guess I just find this approach a bit odd. There should be a separation of concerns between the mechanism and the user interface, but this appears to conflate the two. It seems cleaner to me to return structured information, and leave the presentation and user interface to the CLI code. Except for actual debug logging, if we even need it, which I suppose should be done via the usual facilities.
</blockquote></details>

How about calling it an action list which we want user to acknowledge or see. So all the wantf's would be recordAction(...) while infofs would just go to normal logs under info. Then we'll have logs with whatever additional info available and then we'll just print out actionrecords before asking to proceed? I guess the questionable part would be if logs being printed to stderr by default or not and how they would mix with "normal" interaction.


<!-- Sent from Reviewable.io -->

2021-12-01 14:28 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MplC67t-L5g03yZD_1h:-MpqNPFpBVdJMuz8bIso:b9s46p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/kv/kvserver/loqrecovery/recovery.go#L37)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

How about calling it an action list which we want user to acknowledge or see. So all the wantf's would be recordAction(...) while infofs would just go to normal logs under info. Then we'll have logs with whatever additional info available and then we'll just print out actionrecords before asking to proceed? I guess the questionable part would be if logs being printed to stderr by default or not and how they would mix with "normal" interaction.
</blockquote></details>

Why not just return something like:

```
type PlanReplicasResult struct {
  Updates []ReplicaUpdate
  HealthyReplicas []ReplicaDescriptor
  DeadStores []StoreID
}
```

This has a bunch of benefits: all the presentation and UI code is moved into the CLI (it can choose to either emit them as individual lines, as a summary, as JSON, or whatever), it's much easier to test since we can assert on the structured result, and it takes much less memory since we're not duplicating all of these strings.


<!-- Sent from Reviewable.io -->

2021-12-01 15:55 UTC, erikgrinaker reviewed
Ok, I'm done with a superficial first pass and think we've gotten most of the bikeshedding out of the way. 😅 I'll go more in-depth on the core logic for each of the components later, and hopefully provide more substantial feedback.

> Reviewed 2 of 5 files at r2, 5 of 16 files at r3, 6 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-Mpqgo177Dq0LlS1gp9I:b-2h3acz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @tbg)

___
*[pkg/kv/kvserver/loqrecovery/recovery_test.go, line 86 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpqfx-y8ZMwt9haz40d:-Mpqfx-y8ZMwt9haz40e:b-nk4ff7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/kv/kvserver/loqrecovery/recovery_test.go#L86)):*
> ```Go
> 		err             bool
> 	}{
> 		{name: "no_dead_stores", replicas: cluster(node1, node2, node3), deadStores: nil, liveStores: storeSet(1, 2, 3), missingStoreIDs: storeSet()},
> ```

nit: t.Run() will automatically do underscoring and such of the test names, so we usually just write them out normally.
___
*[pkg/cli/testdata/quorum/learners_lose, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMjnK86AvIMW_kpI2g:-Mpq_eVBBjJjcgcV-lHs:b-704lq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/testdata/quorum/learners_lose#L42)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

This one is tricky as test driven specific structs that you need to write as inputs use strings and it allows parsing keys, while plans use real structs where keys are bytes and the only thing here is to at least make them print on a single line rather than byte per line. The only solution I found is to again mirror the struct in test, but that is becoming tedious and I don't think is worth the effort.
Unless you know some magic.
</blockquote></details>

There's a few different options here. The simplest would be to implement `MarshalYAML` and `UnmarshalYAML` for `roachpb.Key`, but it seems like the string formatting may be lossy, and I don't think it would be appropriate in all conceivable contexts. Another option is to add a new key type specifically for these plans that embeds `roachpb.Key`, and implement `MarshalYAML` and `UnmarshalYAML` for that -- we'd then use this type also for the test structs, to avoid doing the parsing everywhere. None of these options are ideal though, but I think it's useful to output keys in a format that's easily inspectable and consistent with the inputs.

https://pkg.go.dev/gopkg.in/yaml.v2#Marshaler
___
*[pkg/kv/kvserver/loqrecovery/recovery_env_test.go, line 98 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpqgEBQ43Hr7_oICh_4:-MpqgEBQ43Hr7_oICh_5:b-4f2978) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/kv/kvserver/loqrecovery/recovery_env_test.go#L98)):*
> ```Go
> }
> 
> type quorumRecoveryEnv struct {
> ```

This test harness is great, thanks for building it!
___
*[pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto, line 19 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpqWZXjBH78q1v_viqu:-MpqWZXjBH78q1v_viqv:b-3qkv97) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto#L19)):*
> ```protobuf
> import "gogoproto/gogo.proto";
> 
> // Info about range replica
> ```

Please expand this comment and others in this file.
___
*[pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto, line 20 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpqWl-nDzOLAVVb3If1:-MpqWl-nDzOLAVVb3If2:by6f9k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto#L20)):*
> ```protobuf
> 
> // Info about range replica
> message LocalRangeInfo {
> ```

Consider `LocalReplicaInfo` or something, since we call this `replicas` in the `Replicas` message below and throughout much of the code.
___
*[pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto, line 31 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpqc9aR3rCOu27W21ck:-Mpqc9aR3rCOu27W21cl:b-rlaeob) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto#L31)):*
> ```protobuf
> }
> 
> message Replicas {
> ```

This is essentially what `collect-info` returns. It would be nice if we could come up with a descriptive and consistent name for that, since we currently use pretty vague terms when describing it (i.e. this affects what `collect-info` outputs, what `make-plan` takes as input, what the different structs and variables are called, etc). I don't have any great ideas though, other than e.g. `ReplicaInfo` or `RecoveryInfo` or something like that -- maybe you have any better ideas?
___
*[pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto, line 54 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpqZ-679LnIea-A-1kL:-MpqZ-679LnIea-A-1kM:b-d2mueh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto#L54)):*
> ```protobuf
> }
> 
> message Updates {
> ```

Consider calling this `Plan`, since this is what `make-plan` outputs.


<!-- Sent from Reviewable.io -->

2021-12-02 15:10 UTC, aliher1911 reviewed
Changed what is printed on steps.
Collect info:
```
Collected info about 41 replicas.
```

Plan now:
```
Total replicas analyzed: 45
Healthy replicas found:  40
Discarded live replicas: 2

Recovering range r16:/Table/20 promoting replica r1 at store s1 to r4. Discarding replicas: (n4,s4):3,(n2,s2):2
Recovering range r7:/Table/11 promoting replica r2 at store s3 to r5. Discarding replicas: (n4,s4):4,(n2,s2):3
Recovering range r31:/Table/35 promoting replica r2 at store s3 to r5. Discarding replicas: (n2,s2):4,(n4,s4):3

Discovered dead stores from provided files: s2, s4

Proceed with plan creation [y/N] y

Plan created
Run update on node n1, store(s) s1
Run update on node n3, store(s) s3

```

Apply:
```
Replica 5 for range 7:/Table/11 will be promoted with peer replica(s) removed: (n4,s4):4,(n2,s2):3
Replica 5 for range 31:/Table/35 will be promoted with peer replica(s) removed: (n2,s2):4,(n4,s4):3

Proceed with above changes [y/N] y

Updated store(s): s3
```

Strangely I don't see your warnings about not enough file descriptors, but maybe that's because I bumped mine to infinity to make build work at some point in the past.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-Mpvee6H1RTmkcXzdPNs:b5ffftk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpRXI4m89mWA2yBfSbH:-MpqJiAu7jZIMyQYhcEc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L94)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Thanks. I think we should mention that we strongly recommend the data be migrated into a fresh cluster, since we may have violated internal invariants that can cause further damage or failures in the future. We don't have tooling to verify SQL or other system invariants, and I don't think it's feasible for users to vet this properly without intimate knowledge of CRDB internals.
</blockquote></details>

Done.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl8RPz6qyCCLZFa5IS:-MpqHb4A-VGIJ_vkhR0h:bgucf49) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L55)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I guess we should use `log.Fatalf` here. I see we're not consistent about this in the CLI code (there's lots of panics around too), but I think we generally prefer `log.Fatalf` over bare panics, at least in the main codebase.
</blockquote></details>

It makes sense to use log.Fatalf when running as a server, but I'm not sure what would happen with log when you run cli. You don't really want errors in the log in command line tools. Anyway it is all purely theoretical as I don't see this case happening in real system. I'll change to log, but it is ugly.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 185 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpq6Sxo0xmko-Y0n00Z:-MpqIQ4-AvbkaC89PKda:b-pb7ckl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/cli/debug_recover_loss_of_quorum.go#L185)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This should be info-node2 and 5.
</blockquote></details>

:scissors: too much copy&pasta! :scissors:
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MplC67t-L5g03yZD_1h:-MpvfqgM52Gv9hCKNdcC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/kv/kvserver/loqrecovery/recovery.go#L37)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Why not just return something like:

```
type PlanReplicasResult struct {
  Updates []ReplicaUpdate
  HealthyReplicas []ReplicaDescriptor
  DeadStores []StoreID
}
```

This has a bunch of benefits: all the presentation and UI code is moved into the CLI (it can choose to either emit them as individual lines, as a summary, as JSON, or whatever), it's much easier to test since we can assert on the structured result, and it takes much less memory since we're not duplicating all of these strings.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 273 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MplAhDE96swu_m9DHCB:-MpqKFn_1JAJQHSz667-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/kv/kvserver/loqrecovery/recovery.go#L273)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Comment needs updating.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto, line 19 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpqWZXjBH78q1v_viqu:-MpuRTv63rwIOdGLpE1c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto#L19)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Please expand this comment and others in this file.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto, line 20 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpqWl-nDzOLAVVb3If1:-MpuQqYs3pkJidicS4JB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto#L20)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Consider `LocalReplicaInfo` or something, since we call this `replicas` in the `Replicas` message below and throughout much of the code.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto, line 31 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpqc9aR3rCOu27W21ck:-MpuQpuwECjMuZnMU25z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto#L31)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This is essentially what `collect-info` returns. It would be nice if we could come up with a descriptive and consistent name for that, since we currently use pretty vague terms when describing it (i.e. this affects what `collect-info` outputs, what `make-plan` takes as input, what the different structs and variables are called, etc). I don't have any great ideas though, other than e.g. `ReplicaInfo` or `RecoveryInfo` or something like that -- maybe you have any better ideas?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto, line 54 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpqZ-679LnIea-A-1kL:-MpuRVYeAU380Jcs7dcL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b545e81e954dfe1158a57c8a05d6a60829291d4d/pkg/kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto#L54)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Consider calling this `Plan`, since this is what `make-plan` outputs.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-06 19:51 UTC, aliher1911 reviewed
FYI: This is the follow up on checking key coverage: https://github.com/aliher1911/cockroach/pull/1
I don't want to stack it just to highlight that existing replica choice is taken directly from existing command that we have and next PR comes closer to what we want to achieve with range_commit_index and completeness check.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MqGHpcq0K06Wuiz3Rx6:b-d5pk5h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)



<!-- Sent from Reviewable.io -->

2021-12-07 13:21 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMgNVy2y6yjuilhbJS:-MqK0xvR9CgTFK5J73G9:b-9crshh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L672)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Agree, that was clumsy attempt to add a check without fully thinking through.
</blockquote></details>

I contenplated CPut a bit, but if we want to make it work, we'll have to preserve full descriptor all the way to planner and back. While doable, it would be more trouble than just checking existing state by hand. Shouldn't checking Generation be enough in general if it is passed back with update? 
___
*[pkg/cli/testdata/quorum/learners_lose, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMjnK86AvIMW_kpI2g:-MqK0NVB4fyERpcPjpKC:b-ujd5hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/testdata/quorum/learners_lose#L42)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

There's a few different options here. The simplest would be to implement `MarshalYAML` and `UnmarshalYAML` for `roachpb.Key`, but it seems like the string formatting may be lossy, and I don't think it would be appropriate in all conceivable contexts. Another option is to add a new key type specifically for these plans that embeds `roachpb.Key`, and implement `MarshalYAML` and `UnmarshalYAML` for that -- we'd then use this type also for the test structs, to avoid doing the parsing everywhere. None of these options are ideal though, but I think it's useful to output keys in a format that's easily inspectable and consistent with the inputs.

https://pkg.go.dev/gopkg.in/yaml.v2#Marshaler
</blockquote></details>

I took the type "alias" with marshaller route. Definitely not a lazy man's approach as it required a new package so that it could be included into proto file without cyclic dependencies and few casts.


<!-- Sent from Reviewable.io -->

2021-12-08 14:35 UTC, erikgrinaker reviewed
Nice, this looks much better! Some more nits:

* Running `collect-info` on an active store returns "ERROR: resource temporarily unavailable". I suppose this comes from an `EAGAIN` at the syscall level due to a Pebble lock or something, but it might be nice with a more informative error message like "store is in use".

* Running `collect-info` without an output file has no newline between the JSON output and the status message: `"raft_committed_index":41}]}Collected info about 53 replicas`.

* `make-plan` gives me this output:

    ```
    Total replicas analyzed: 167
    Healthy replicas found:  75
    Discarded live replicas: 84
    ```

    What does "discarded live replicas" mean? The output below only shows 16 discarded replicas for 8 ranges that lost quorum, so why is it saying 84 replicas will be discarded?

    Maybe also list total number of ranges and number of ranges without quorum.

* Why do we change the replica ID of the survivor? Is this a vestige of the old command? I though we would just keep the existing replica?

* `make-plan` says "Run update on node n3, store(s) s3". Consider "Run apply-plan" instead, which is the actual command name.

* `apply plan` says "Replica 5 for range x will be promoted", when in fact it is replica 4 (replica 5 will be the replica ID after recovery). Should probably include both the old and new replica IDs here.

* If I run `apply plan` again after having already applied it, it correctly lists that the replicas have all been updated, but then asks me for confirmation.

> Strangely I don't see your warnings about not enough file descriptors, but maybe that's because I bumped mine to infinity to make build work at some point in the past.

That's probably the case, but you should be able to see it by running e.g. `ulimit -n 1024` first.

> Reviewed 7 of 11 files at r7, 7 of 8 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MqP6vgtAr8YiI5w_Nfn:b-a04z57)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mpl8RPz6qyCCLZFa5IS:-MqPNRsH5uP5ya16L333:b4fflxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/cli/debug_recover_loss_of_quorum.go#L55)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

It makes sense to use log.Fatalf when running as a server, but I'm not sure what would happen with log when you run cli. You don't really want errors in the log in command line tools. Anyway it is all purely theoretical as I don't see this case happening in real system. I'll change to log, but it is ugly.
</blockquote></details>

Yeah, I don't really have a strong opinion here -- just trying to follow the established convention, but there doesn't really seem to be one for the CLI, so either is probably fine. Maybe the CLI people will let us know when reviewing.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 340 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPKSNaD6nF3qvJV1PX:-MqPKSNaD6nF3qvJV1PY:b7y82x0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L340)):*
> ```Go
> 		}
> 
> 		if proceed, err := console.confirm("Proceed with plan creation"); !proceed || err != nil {
> ```

Consider asking for confirmation if there are any recoverable ranges, regardless of whether we autodetected dead stores or not.

Also, the logic here is wrong in the case where stores were not autodiscovered and there were no recoverable ranges -- it will create a noop plan instead of exiting with "no recoverable ranges".
___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 45 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPQ31PEdMtyX_2BRlU:-MqPQ31PEdMtyX_2BRlV:bhguwmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum_test.go#L45)):*
> ```Go
> 
> 	ctx := context.Background()
> 	dir, cleanupFn := testutils.TempDir(t)
> ```

nit: `testing.T` now supports this natively with `t.TempDir()`.
___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 119 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPQpO64Yvt1koegrsF:-MqPQpO64Yvt1koegrsG:buxfxca) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum_test.go#L119)):*
> ```Go
> 	out, err := c.RunWithCaptureArgs([]string{"debug", "recover", "make-plan", "--confirm=y", "--plan=" + planFile, replicaInfoFileName})
> 	require.NoError(t, err, "failed to run make-plan")
> 	require.FileExists(t, planFile, "generated plan file")
> ```

Maybe check that the file is non-empty and that it contains valid JSON too.
___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 128 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPRD7FDAhqfqS7dorq:-MqPRD7FDAhqfqS7dorr:b-vq7cji) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum_test.go#L128)):*
> ```Go
> // out of three and checking that application of command produces output
> // that is consistent with plan application execution.
> func TestApplyPlan(t *testing.T) {
> ```

I wonder if this test alone would be sufficient? Is there anything we're testing in the two other tests that wouldn't cause a failure in this test?
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MplC67t-L5g03yZD_1h:-MqPSxYV3Y9izWoCiGjT:bf3vg7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c7aeee4666564a7be3b9812af522137cb07283a/pkg/kv/kvserver/loqrecovery/recovery.go#L37)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice, thank you!
___
*[pkg/cli/testdata/quorum/learners_lose, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMjnK86AvIMW_kpI2g:-MqPPHZt9LXSPuOK--Ei:b-vgpp7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/testdata/quorum/learners_lose#L42)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I took the type "alias" with marshaller route. Definitely not a lazy man's approach as it required a new package so that it could be included into proto file without cyclic dependencies and few casts.
</blockquote></details>

Nice, that didn't end up being all that bad -- lesser of evils.


<!-- Sent from Reviewable.io -->

2021-12-09 13:11 UTC, erikgrinaker reviewed
Review pass over ´loqrecovery` package, will do another pass over the CLI.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MqUJUGq3pF8Ghh_2d_Y:b-ttj1fb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 351 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU-xWxBNlzHdTctBHn:-MqU-xWxBNlzHdTctBHo:b-fhzzeo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L351)):*
> ```Go
> 	if len(debugRecoverPlanOpts.outputFileName) > 0 {
> 		if _, err = os.Stat(debugRecoverPlanOpts.outputFileName); err == nil {
> 			return errors.Newf("file '%s' already exists", debugRecoverPlanOpts.outputFileName)
> ```

nit: `%q` will produce a quoted string.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 177 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU4SjXD6nyL4ZE4kQO:-MqU4SjXD6nyL4ZE4kQP:b-mlffum) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L177)):*
> ```Go
> 			//
> 			// https://github.com/cockroachdb/cockroach/issues/33007
> 			if rep.IsVoterNewConfig() && rep.StoreID > maxLiveVoter {
> ```

There will be a follow-up PR to use a better heuristic here, right? Is there an issue for that? Consider adding a TODO to, for clarification.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 190 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU4zwQ3PoOQO_e67xS:-MqU4zwQ3PoOQO_e67xT:b-k01dwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L190)):*
> ```Go
> 			continue
> 		}
> 		if rangeDesc.StoreID != maxLiveVoter {
> ```

Consider moving this conditional below the `CanMakeProgress` one. When I was looking at the info logs, it was very confusing to see "not designated survivor" for lots of ranges that hadn't lost quorum, so we should check that first. I think also produces incorrect stats, since it's counted as `LiveNonSurvivor` rather than `HealthReplicas`.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 206 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU5RzV6UlFf0iVj53m:-MqU5RzV6UlFf0iVj53n:bw0yt4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L206)):*
> ```Go
> 		}
> 
> 		// We're the designated survivor and the range does not to be recovered.
> ```

s/does not/needs/
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 229 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU62gZ4KQNn31-8Sj8:-MqU62gZ4KQNn31-8Sj9:b-jrd68b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L229)):*
> ```Go
> 				NodeID:    rangeDesc.NodeID,
> 				StoreID:   rangeDesc.StoreID,
> 				ReplicaID: desc.NextReplicaID,
> ```

There's a risk here that `NextReplicaID` is already in use by a different replica, since the designated survivor may currently be a lagging replica. I don't think that shouldn't be possible once we pick the store with the highest commit index, but maybe it's worth verifying that we pick a new replica ID that's higher than all known `NextReplicaID`? Or will that follow from the commit index? This is also important for picking the new `NextReplicaID`.

I see that this is covered by the `RaftLog` property in the RFC (i.e. we assume that all surviving replicas have applied all changes to the range descriptor). Will we be implementing any additional checks for this in the final logic? If so, it's worth describing that in an issue and/or adding a `TODO` spelling that out.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 233 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU9Tou7qTgm3W7GWx8:-MqU9Tou7qTgm3W7GWx9:bky4hob) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L233)):*
> ```Go
> 			NextReplicaID: desc.NextReplicaID + 1,
> 		}
> 		log.Infof(ctx, "Replica has lost quorum, recovering: %s -> %s", &desc, &update)
> ```

nit: don't think the`&` is needed here?
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 319 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUA_AxDgrUitc5kQcB:-MqUA_AxDgrUitc5kQcC:bku5grn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L319)):*
> ```Go
> 	// That would produce 'nil' as a result where we want to have '[]'.
> 	if results == nil {
> 		results = make([]interface{}, 0)
> ```

I don't think this logic is necessary, the input can be a `proto.Message` type.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 321 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUA19aESGiqF8W6hUS:-MqUA19aESGiqF8W6hUT:b-5yc945) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L321)):*
> ```Go
> 		results = make([]interface{}, 0)
> 	}
> 	if out, err = marshalFn(results); err != nil {
> ```

nit: why `marshalFn` instead of just calling `jsonpb.Marshal()` directly?
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 372 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUBYWLCR_YYQbq_eho:-MqUBYWLCR_YYQbq_ehp:behrlk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L372)):*
> ```Go
> 	nodeID roachpb.NodeID,
> 	stores map[roachpb.StoreID]storage.Engine,
> ) (map[roachpb.StoreID]storage.Batch, PrepareStoreReport, error) {
> ```

Nice that we're staging this as write batches.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 380 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUCTQEA9QFw69kaJ_k:-MqUCTQEA9QFw69kaJ_l:botpthj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L380)):*
> ```Go
> 	// configured in this command invocation.
> 	missing := make(map[roachpb.StoreID]struct{})
> 	for _, update := range plan.Updates {
> ```

I think this logic can be folded into the loop below? Otherwise we end up having to duplicate checks in both loops.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 389 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUGCO07M2frntfxzxY:-MqUGCO07M2frntfxzxZ:baz80jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L389)):*
> ```Go
> 			_, ok := batches[update.StoreID]
> 			if !ok {
> 				batches[update.StoreID] = store.NewBatch()
> ```

It's a bit iffy that we create the batch separately from where we close/commit it, since that prevents using e.g. `defer Close()` for error handling, and makes the responsibility unclear to the caller. Consider passing in the batches instead of the engines as `ReadWriter`, and doing all reads/writes on the batches, leaving the responsibility of managing the batch to the caller.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 419 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUDKp96kmsyEOEkZIY:-MqUDKpA6tcELSBIWpp6:bq59efi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L419)):*
> ```Go
> }
> 
> func prepareReplicaUpdate(
> ```

Consider calling this `applyReplicaUpdate` or something, and taking a `storage.ReadWriter` as input. In principle it shouldn't care about whether it applies the change to a batch or directly to the engine. You can then remove the `store` parameter too, and just read via th [...]

2021-12-09 16:31 UTC, erikgrinaker reviewed
Nothing major on the CLI bits, but let's do some final UX polish before we merge this. I can do another pass for that as well once everything else is sorted.

Would be good to get another review from @tbg on the recovery logic.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MqV0t5V8Q25jG_99eIN:b8oembe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 528 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMdrpW1Jk1LmsLfZDz:-MqV0GhY2JQ6lx_dUdKV:berjadt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L528)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

The only reason that NodeID is present here is to verify that you didn't forget to pass any store configs when invoking the command. Imagine you have 2 stores and you only passed one while plan contains fixes for the other store too. That sounds fishy unless you really want to fix only subset of ranges there. But to figure that out, we need to get nodeid of some local store and then verify that all range replicas belonging to all stores on that node are updated.
</blockquote></details>

May as well check this -- the node ID is useful in plans for inspection, if nothing else -- but I'd move the actual check into `PrepareUpdateReplicas`.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 78 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUu0_2DjUFnH-Xx_Ow:-MqUu0_33xRmkrO4zIOC:b-9gr2re) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L78)):*
> ```Go
> // dialog provides a crude facility for commands to interact with user or
> // to force certain outcome based on command line flag.
> type dialog interface {
> ```

I wonder whether we really need all of this infrastructure, or if we could do something much simpler. `confirm()` is called in two places, and seems like it could be replaced by a simple function like `func confirm(msg string, mode confirmActionFlag)` or something. `printf()` is really just a thin wrapper around an `io.Writer`, so we could do something like `console := os.Stderr; if silence { console = io.Discard }`.

If we do introduce infrastructure like this, we should make it general enough that it can be used throughout the CLI (unless we/Cobra already have facilities for this). I'd defer to the CLI team on that.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 380 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUzTF56jXvDNWZItMC:-MqUzTF6EFPTG-mzaIkW:boi135v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L380)):*
> ```Go
> 
> 		var nodeReplicas loqrecoverypb.NodeReplicaInfo
> 		jsonpb := protoutil.JSONPb{Indent: "  "}
> ```

nit: since we're only unmarshalling here we don't really need to set `Indent`.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 477 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqV-7KW1u4ck8xumhup:-MqV-7KW1u4ck8xumhuq:b-htl69k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L477)):*
> ```Go
> 	if proceed, err := console.confirm("\nProceed with above changes"); !proceed || err != nil {
> 		if !proceed {
> 			return errors.New("aborting at user request")
> ```

Isn't this going to always replace whatever error `confirm()` returned, because `proceed` will be `false` whenever `confirm` errors? Consider using a separate branch for the error condition.


<!-- Sent from Reviewable.io -->

2021-12-09 17:19 UTC, tbg commented
Will review tomorrow.

(sent from mobile, please excuse my brevity)

On Thu, Dec 9, 2021, 17:31 Erik Grinaker ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Nothing major on the CLI bits, but let's do some final UX polish before we
> merge this. I can do another pass for that as well once everything else is
> sorted.
>
> Would be good to get another review from @tbg <https://github.com/tbg> on
> the recovery logic.
>
> *Reviewable
> <https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MqV0t5V8Q25jG_99eIN:b8oembe>*
> status: [image: :shipit:] complete! 0 of 0 LGTMs obtained (waiting on
> @aliher1911 <https://github.com/aliher1911> and @tbg
> <https://github.com/tbg>)
>
> ------------------------------
>
> *pkg/cli/debug_recover_loss_of_quorum.go, line 528 at r2
> <https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMdrpW1Jk1LmsLfZDz:-MqV0GhY2JQ6lx_dUdKV:berjadt>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L528>):*
> *Previously, aliher1911 (Oleg) wrote…*
>
> The only reason that NodeID is present here is to verify that you didn't
> forget to pass any store configs when invoking the command. Imagine you
> have 2 stores and you only passed one while plan contains fixes for the
> other store too. That sounds fishy unless you really want to fix only
> subset of ranges there. But to figure that out, we need to get nodeid of
> some local store and then verify that all range replicas belonging to all
> stores on that node are updated.
>
> May as well check this -- the node ID is useful in plans for inspection,
> if nothing else -- but I'd move the actual check into
> PrepareUpdateReplicas.
> ------------------------------
>
> *pkg/cli/debug_recover_loss_of_quorum.go, line 78 at r9
> <https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUu0_2DjUFnH-Xx_Ow:-MqUu0_33xRmkrO4zIOC:b-9gr2re>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L78>):*
>
> // dialog provides a crude facility for commands to interact with user or
> // to force certain outcome based on command line flag.
> type dialog interface {
>
> I wonder whether we really need all of this infrastructure, or if we could
> do something much simpler. confirm() is called in two places, and seems
> like it could be replaced by a simple function like func confirm(msg
> string, mode confirmActionFlag) or something. printf() is really just a
> thin wrapper around an io.Writer, so we could do something like console
> := os.Stderr; if silence { console = io.Discard }.
>
> If we do introduce infrastructure like this, we should make it general
> enough that it can be used throughout the CLI (unless we/Cobra already have
> facilities for this). I'd defer to the CLI team on that.
> ------------------------------
>
> *pkg/cli/debug_recover_loss_of_quorum.go, line 380 at r9
> <https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUzTF56jXvDNWZItMC:-MqUzTF6EFPTG-mzaIkW:boi135v>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L380>):*
>
> 		var nodeReplicas loqrecoverypb.NodeReplicaInfo
>
> 		jsonpb := protoutil.JSONPb{Indent: "  "}
>
> nit: since we're only unmarshalling here we don't really need to set
> Indent.
> ------------------------------
>
> *pkg/cli/debug_recover_loss_of_quorum.go, line 477 at r9
> <https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqV-7KW1u4ck8xumhup:-MqV-7KW1u4ck8xumhuq:b-htl69k>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L477>):*
>
> 	if proceed, err := console.confirm("\nProceed with above changes"); !proceed || err != nil {
>
> 		if !proceed {
>
> 			return errors.New("aborting at user request")
>
> Isn't this going to always replace whatever error confirm() returned,
> because proceed will be false whenever confirm errors? Consider using a
> separate branch for the error condition.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/71996#pullrequestreview-827921816>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGXPZDZBNQ4HPMJNUNOS6TUQDKWTANCNFSM5GYQQWHQ>
> .
>

2021-12-10 00:27 UTC, aliher1911 reviewed
- `collect-info` new line is coming from the fact that messages go to stderr while output goes to stdout. It would make some sense if you run it locally, but over ssh it would be mess because they could even overlap even if I add a spare \n before report. I think it is enough separation tbh. In real situation you would either redirect stdout or just provide a filename to write it.
- discarded replicas is definitely a miscalculation. checking total range count is a bit hard, but I'll add this in updated algorithm that analyzes all found replicas of the range together. It makes calculations more consistent. I think for this diff having ranges with lost quorum should be enough without writing additional aggregations of replicas solely for the purpose of this stat.
- survivor replica id change came from original recovery code, I was under impression that we use that to discourage remaining replicas from doing anything funny.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MqUjavM-73J5TJ0qZba:bqqzzba)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 340 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPKSNaD6nF3qvJV1PX:-MqWibf49QuEKl5LlMnv:brepw24) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L340)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Consider asking for confirmation if there are any recoverable ranges, regardless of whether we autodetected dead stores or not.

Also, the logic here is wrong in the case where stores were not autodiscovered and there were no recoverable ranges -- it will create a noop plan instead of exiting with "no recoverable ranges".
</blockquote></details>

When would that be the case though, if we expect a replica on a store, store is available, but replica is missing? I think we can try that in follow up where we group replicas before making a decision.
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 477 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqV-7KW1u4ck8xumhup:-MqWUIz0Dbs4zghg7iob:bezyyx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L477)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Isn't this going to always replace whatever error `confirm()` returned, because `proceed` will be `false` whenever `confirm` errors? Consider using a separate branch for the error condition.
</blockquote></details>

I guess it is now irrelevant since logic is inlined.
___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 45 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPQ31PEdMtyX_2BRlU:-MqW30ViBpsvkochtDzT:bqppx8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum_test.go#L45)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: `testing.T` now supports this natively with `t.TempDir()`.
</blockquote></details>

As we now know, there's soma bazel hack in our
___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 128 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPRD7FDAhqfqS7dorq:-MqV1gEr3wb_pk0YAP3l:b-w0r9kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum_test.go#L128)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I wonder if this test alone would be sufficient? Is there anything we're testing in the two other tests that wouldn't cause a failure in this test?
</blockquote></details>

We only test that cli produced some sensible console output based on missing replicas, but we don't test actual changes. I think we shouldn't test correctness of application here as it is covered by our datadriven tests. I think we should only check that cli accepted file and did "something" which is covered separately.
Dependency on previous steps is not ideal. and would fail if collect or plan fails. Alternative would be to create plan by hand, but that's imho fragile. If we change anything upstream of apply, we'll break this test since the data is out of data, while using previous steps gives up up to date guarantees.
We can bake it all into a single test though. Then failure message would distinguish different failures.
I'm open to suggestions here.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 233 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU9Tou7qTgm3W7GWx8:-MqWC_OJ3oti9MmtvsLA:btaog5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L233)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: don't think the`&` is needed here?
</blockquote></details>

Looks like I need to suppress gogoproto stringer and add custom for it to work by value.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 319 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUA_AxDgrUitc5kQcB:-MqV3yJyDv22goukx6_I:bojznpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L319)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I don't think this logic is necessary, the input can be a `proto.Message` type.
</blockquote></details>

Oh true, this is a remainder of the code code where we just passed a slice of messages and it resulted in nil. Now with plan and node message it goes away.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 321 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUA19aESGiqF8W6hUS:-MqV8XBlEuopb0HgWwkU:b-7bldka) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L321)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: why `marshalFn` instead of just calling `jsonpb.Marshal()` directly?
</blockquote></details>

That was also remnant of marshalling slice.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 595 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUH99M2_uPOCRe5gc7:-MqVCd8D8qS5PvLob28r:b-keryrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L595)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I don't think we should attempt to apply the same batch multiple times and retry errors. IO errors are always fatal.
</blockquote></details>

Retry here means you can relaunch binary with apply plan. If you have 3 stores and store 2 failed because of something. You then retry it and first store is already processed so we will have no updates.


<!-- Sent from Reviewable.io -->

2021-12-10 14:01 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 340 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPKSNaD6nF3qvJV1PX:-MqZZ4aB3rKmFYbqwswz:b-bwawsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum.go#L340)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

When would that be the case though, if we expect a replica on a store, store is available, but replica is missing? I think we can try that in follow up where we group replicas before making a decision.
</blockquote></details>

I'm basically saying that I think we can drop the `len(deadStoreIDs)` check. The `len(plan.Updates) == 0` check is currently only run when`len(deadStoreIDs) == 0`, I think it should apply regardless (along with the confirmation).

This would happen when a user runs this and it turns out that no ranges have actually lost quorum.
___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 45 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPQ31PEdMtyX_2BRlU:-MqZ_JqY2Hx1IkUzvYaQ:b-hhctw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum_test.go#L45)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

As we now know, there's soma bazel hack in our
</blockquote></details>

Yeah, that seems unfortunate.
___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 128 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPRD7FDAhqfqS7dorq:-MqZ_VTdBb0zJrGvN_7q:b-lzvt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum_test.go#L128)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

We only test that cli produced some sensible console output based on missing replicas, but we don't test actual changes. I think we shouldn't test correctness of application here as it is covered by our datadriven tests. I think we should only check that cli accepted file and did "something" which is covered separately.
Dependency on previous steps is not ideal. and would fail if collect or plan fails. Alternative would be to create plan by hand, but that's imho fragile. If we change anything upstream of apply, we'll break this test since the data is out of data, while using previous steps gives up up to date guarantees.
We can bake it all into a single test though. Then failure message would distinguish different failures.
I'm open to suggestions here.
</blockquote></details>

Yes, I agree that we should test correctness in the datadriven tests, and that this should be a basic end-to-end test like it already is.

What I mean is that `TestCollectInfo` currently just checks that we fetched some JSON data from the stores, and `TestGeneratePlan` checks that a plan file was generated. It seems like if either of those things fail, then `TestApplyPlan` would also fail, so `TestApplyPlan` alone would get us basically the same test coverage as the other tests. We could therefore probably just remove the other tests.

Anyway, your call, just a thought.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 233 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU9Tou7qTgm3W7GWx8:-MqZb4lKEJYKpvkR9EHt:b-5etbzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L233)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Looks like I need to suppress gogoproto stringer and add custom for it to work by value.
</blockquote></details>

Ah, my bad -- I keep forgetting that value types can't implicitly cast to pointer receivers when they're unaddressable. We totally shouldn't do anything custom here.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 595 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUH99M2_uPOCRe5gc7:-MqZdLSz72T9LPe3FwdR:b-ciowo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L595)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Retry here means you can relaunch binary with apply plan. If you have 3 stores and store 2 failed because of something. You then retry it and first store is already processed so we will have no updates.
</blockquote></details>

Ah, got it -- makes sense.


<!-- Sent from Reviewable.io -->

2021-12-10 14:31 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 128 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPRD7FDAhqfqS7dorq:-MqZii6s8TM8m_ZErkvf:b-jhcfzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum_test.go#L128)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yes, I agree that we should test correctness in the datadriven tests, and that this should be a basic end-to-end test like it already is.

What I mean is that `TestCollectInfo` currently just checks that we fetched some JSON data from the stores, and `TestGeneratePlan` checks that a plan file was generated. It seems like if either of those things fail, then `TestApplyPlan` would also fail, so `TestApplyPlan` alone would get us basically the same test coverage as the other tests. We could therefore probably just remove the other tests.

Anyway, your call, just a thought.
</blockquote></details>

I'm now leaning towards making it a single test and then adding structuredevent logging to it in following diff. @tbg maybe you have some bright thoughts about the end to end workflow test for sequence of cli commands? Currently I see 2 options:
- test per operation, but verify the last one in chain. pros: test are per feature, cons: fails if earlier step fails (but we can make is succeed if prerequisite is not successful), runtime is long as we need 3 node disk based cluster with replication
- single test. pros: less duplication, runs faster, cons: long test with a bit of logic akin to roachtests.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 233 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU9Tou7qTgm3W7GWx8:-MqZi5OD0PbSlkqbkWid:b-5ubg5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L233)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Ah, my bad -- I keep forgetting that value types can't implicitly cast to pointer receivers when they're unaddressable. We totally shouldn't do anything custom here.
</blockquote></details>

We actually override it alot because of redactability/safety reasons so lots of those structs have Stringer defined on value rather than pointer. I already changed that. It makes it look more consistent with the rest of structs we have.


<!-- Sent from Reviewable.io -->

2021-12-10 22:12 UTC, tbg reviewed
Revisited all my waiting comments and did a pass through `recovery.go`. I would need to do another pass to really dig into the logic, I found that I was constantly semi-confused about what I was currently looking at, which I chalk up to Friday night brain but also naming and comments that I had trouble absorbing. I think the pragmatic approach is to revisit all of this in one of the follow-up PRs and to focus in this PR on the cli UX and on the test corpus. I haven't looked through the datadriven tests myself yet, but I saw a comment of Erik's where he suspected there were a number of scenarios we aren't covering yet. Adding those in (stopping short of those that require specialized states, like intents to abort or mismatching applied indexes etc, we can save those for the PRs that handle them) might be the last thing to do here before the merge, but it's probably even better to add these in in a follow-up PR. I'll defer to @erikgrinaker here.
Hope to try this out next week, pretty exciting!

> Reviewed 1 of 11 files at r7, 1 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MqaNJmBDApnv9-0fEEF:b1mzulm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMdQh15QXZ4POS7RI-:-MqaMOFH0hH6Jk-i43dH:bmjpxix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L545)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yeah, we'll have to stash this somewhere in the store. I prefer a key over a file because it's more resistant to deliberate or accidental manipulation, but a store-local key isn't ideal because the info will be lost if the node is decommissioned or the store is removed. I think we'll have to buffer it as a store-local key temporarily, and then move it into the audit log and the replicated key-space once the node starts back up.
</blockquote></details>

Lost track, was this done or filed?
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 640 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMg0xqBQOOXkdZq6gY:-MqaMUsn5ESCcMP0BWm9:bsilo66) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L640)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Wouldn't the replicaGC queue automatically remove them once it notices that the replicas are no longer part of the descriptor? However, we should make sure that happens asap, rather than waiting for however long it takes the queue to get around to it.
</blockquote></details>

The replicaGCQueue does not operate at the scale of user latencies. If a stuck replica is around after the recovery, it may stick around for days if we're really unlucky, and requests routed to it may time out. Also through the lens of stability it just seems better to minimize the possible interactions between the "old" and "new" replicas. And for a third point, we want the metrics to back to healthy the moment the recovery ends, and not "sometime in the future". We don't have to do it now, but is this tracked somewhere?
___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMgNVy2y6yjuilhbJS:-MqaN73v9_mEDOuJ5q-t:b-b2aexm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L672)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I contenplated CPut a bit, but if we want to make it work, we'll have to preserve full descriptor all the way to planner and back. While doable, it would be more trouble than just checking existing state by hand. Shouldn't checking Generation be enough in general if it is passed back with update? 
</blockquote></details>

Checking `Generation` should be enough in practice, I would be fine with that. Doesn't have to happen now but make a note of it please.
___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMhkVE448J4w1vEYkV:-MqaLsXx46600RkInHta:b-5lv73p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum_test.go#L50)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Moved all structs together with datadriven handlers into separate file. Does it matter that it is now a _test.go file but without actual tests?
</blockquote></details>

No, totally fine.
___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 128 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPRD7FDAhqfqS7dorq:-Mqa1sjJAyGwsP8pHRzv:b-yxfeh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum_test.go#L128)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I'm now leaning towards making it a single test and then adding structuredevent logging to it in following diff. @tbg maybe you have some bright thoughts about the end to end workflow test for sequence of cli commands? Currently I see 2 options:
- test per operation, but verify the last one in chain. pros: test are per feature, cons: fails if earlier step fails (but we can make is succeed if prerequisite is not successful), runtime is long as we need 3 node disk based cluster with replication
- single test. pros: less duplication, runs faster, cons: long test with a bit of logic akin to roachtests.
</blockquote></details>

I'm not sure I understand your last suggestion, Oleg. Erik seems to say "just remove TestGeneratePlan and TestCollectInfo". This seems to make sense to me, since `TestApplyPlan` covers their ground and then some (once you also incorporate the two or three `require.XYZs` from the ends of the two tests into `TestApplyPlan`).

If you are entertaining structured logging, I think the easiest way to do it might be to write a JSON stream to a (flag-specified and defaulting to /dev/null) file in `apply-plan`, but I'm not sure it's worth the effort at this point.

Rather, what's missing is that we actually get the cluster back. If our rewritten range descriptors trivially triggered a panic on node restart, would we catch this anywhere (haven't reviewed the entire diff, came straight to this comment)? We have `TestRemoveDeadReplicas` which end-to-end-tests `./cockroach debug remove-dead-replicas`, it seems like you could copy a lot of of the ideas there verbatim to make a more powerful end-to-end test. In fact, since your work is also replacing (in the long run) `remove-dead-replicas`, we would anticipate that source test to vanish someday.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 229 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU62gZ4KQNn31-8Sj8:-Mqa9s-B8NYnK-_Kb2bt:b-189i30) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L229)):*
> I don't think that shouldn't be possible once we pick the store with the highest commit index

It will still be possible then. We would need to pick the store with the highest AppliedIndex. And even then, we might find that the true descriptor is visible on meta2 and has a replica on a store that didn't know about this yet. This would be a learner, and I think we'd get away with it (the voter wouldn't have the learner in its config, so raft wouldn't immediately crash), but it's a mess.

The simple fix here would be to add 10.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 1 at r11](https://reviewable.io [...]

2021-12-13 17:08 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 128 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqPRD7FDAhqfqS7dorq:-Mqo_uciAOZCTPXjX4Qq:bq38al2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/cli/debug_recover_loss_of_quorum_test.go#L128)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'm not sure I understand your last suggestion, Oleg. Erik seems to say "just remove TestGeneratePlan and TestCollectInfo". This seems to make sense to me, since `TestApplyPlan` covers their ground and then some (once you also incorporate the two or three `require.XYZs` from the ends of the two tests into `TestApplyPlan`).

If you are entertaining structured logging, I think the easiest way to do it might be to write a JSON stream to a (flag-specified and defaulting to /dev/null) file in `apply-plan`, but I'm not sure it's worth the effort at this point.

Rather, what's missing is that we actually get the cluster back. If our rewritten range descriptors trivially triggered a panic on node restart, would we catch this anywhere (haven't reviewed the entire diff, came straight to this comment)? We have `TestRemoveDeadReplicas` which end-to-end-tests `./cockroach debug remove-dead-replicas`, it seems like you could copy a lot of of the ideas there verbatim to make a more powerful end-to-end test. In fact, since your work is also replacing (in the long run) `remove-dead-replicas`, we would anticipate that source test to vanish someday.
</blockquote></details>

Looking on `TestRemoveDeadReplicas` it seem to cover everything from command line down to various cases of "survivability" of data. In our case we have tests that check selection and update using generated data which is fast and easily extendable, but it doesn't assert if cluster can actually recover after restart.
What I found about existing test is that if recovery doesn't happen (e.g. we just lose quorum across the board) the test will just hang because liveness ranges are broken and cluster start never finishes. So we only test that some corner case where majority of ranges recover somehow and then we don't have upreplication for some particular range.
___
*[pkg/kv/kvserver/loqrecovery/recovery_test.go, line 23 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUIrMLApL7nOBKvTzz:-Mqnb5cuE9yxgSgD7KW8:b-1okijp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery_test.go#L23)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Will we be writing additional test cases for this? I haven't gone through the exercise of actually enumerating them, but there seems to be lots of other possible scenarios here, including futile ones where we want to make sure that we fail safely.
</blockquote></details>

With respect to this PR, it covers cases that are supported. Once we have range check and also committed index analyzed they need to be added as well. Currently we test what original recovery supported.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 49 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mqa4qtuBxQasV57zcZy:-MqnEHQj6dkHN31JcL7S:bp8nuxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e873800bfeb4b08af5b02610588a6220c4b3245f/pkg/kv/kvserver/loqrecovery/recovery.go#L49)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

mini nit: `FromDisk` -> `FromStorage`?
nit I feel a bit more strongly about: the canonical name for the `Reader` parameter is `reader` (or basically anything but `db`, which is usually the KV DB or the SQL DB).
</blockquote></details>

I don't want to rename kvserver functions as a part of this PR tbh. FromStorage is coming from our store in there.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 102 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mqa5ts53A_KciE8BT2i:-MqnL1eS1gaefu7CoeJ5:bvb7yeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e873800bfeb4b08af5b02610588a6220c4b3245f/pkg/kv/kvserver/loqrecovery/recovery.go#L102)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you add comments on these? Is TotalReplicas = HealthyReplicas plus any replicas that are members of ranges that have lost quorum? Or also LiveNonSurvivors? So if I have a single range, 5x replicated but three replicas are on dead nodes, but one of the nodes is actually live (surprise), do we get Total=3 Healthy = 0 LiveNonSurvivors=1?

Also, feels weird to use the word "Live" here, I would generally avoid this since "liveness" is a running-cluster concept and here we're only looking at disks. "Present" maybe?
</blockquote></details>

Rather Total=2 Healthy = 0 LiveNonSurvivors=1, but total and healthy would also include ranges that we don't touch because we don't need recovery.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 112 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mqa6uG84pK-2U3Kud-k:-MqnPJ3B9Utp46D4QQes:b-gqmw1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e873800bfeb4b08af5b02610588a6220c4b3245f/pkg/kv/kvserver/loqrecovery/recovery.go#L112)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Isn't this `RangePlan`? Looking at the struct (which could use field comments btw) it sounds like it's determining for the given Range which Replica to keep and which ones to discard. So it is a plan to recover this range, not a plan that only affects a single replica?
</blockquote></details>

This is only meant to be printed. It replaced previous []string type report that was collected during planning to present to user for confirmation. It is now capturing data in struct and let cli do the printing in whatever form deemed necessary.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 117 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mqa7miH8fLKWxv5Bdf6:-MqnQj9j6kPVM80YRgfH:ba96tv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e873800bfeb4b08af5b02610588a6220c4b3245f/pkg/kv/kvserver/loqrecovery/recovery.go#L117)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> ```
> PlannedReplicaReport contains detailed info about changes planned for particular replicas.
> ```

Sorry to nitpick on the comment, but when (aeons ago) I said

> A fair amount of them [the comments] that exist are sort of saying the obvious thing without explaining the greater scheme of things (the comments were telling me what the next line does, rather than telling me why).

and didn't have an example, this is one - I'm not really any wiser after reading this line and so we might as well remove it and replace it with something more concise such as (sorry, can't resist sneaking a type rename in there)

> RangeRecoveryPlan describes how quorum will be restored to a Range by naming the StoreID whose Replica will be reconfigured as the sole voter, as well as the other Replicas (which will be discarded to prevent undesired interactions).
</blockquote></details>

That't not really a plan, I'll try to expand comment to make it more clear.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 240 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqaAa-K4t470WnEGwyV:-MqnRfHo0S2bAzBk-QeY:b-1vyuvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e873800bfeb4b08af5b02610588a6220c4b3245f/pkg/kv/kvserver/loqrecovery/recovery.go#L240)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'm sure Erik and you have been over this, and I don't want to open the can of wor [...]

2021-12-16 14:03 UTC, erikgrinaker reviewed
Great, I think we're getting there.

In the `make-plan` report, consider adding a summary line for "Discarded dead replicas" too, for completeness. Also, should we consider including the dead replicas in the total replica count too, or add a separate line for "Total replicas known"? As a user, I might be confused that things don't add up -- here's an example, where I might wonder why 149+16 != 157:

```
Total replicas analyzed: 157
Healthy replicas found:  149
Ranges without quorum:   8
Discarded live replicas: 0

Recovering range r67:/Table/55/1/-9222246136947044152 promoting replica r4 at store s1 to r5. Discarding replicas: (n5,s5):3,(n2,s2):2
Recovering range r68:/Table/55/1/-9222246136946980632 promoting replica r1 at store s1 to r4. Discarding replicas: (n5,s5):3,(n2,s2):2
Recovering range r95:/Table/55/1/-9222246136947431320 promoting replica r1 at store s4 to r5. Discarding replicas: (n5,s5):4,(n2,s2):2
Recovering range r65:/Table/55/1/-9222246136947367800 promoting replica r1 at store s4 to r4. Discarding replicas: (n5,s5):3,(n2,s2):2
Recovering range r96:/Table/55/1/-9222246136947302264 promoting replica r1 at store s4 to r4. Discarding replicas: (n5,s5):3,(n2,s2):2
Recovering range r97:/Table/55/1/-9222246136947238744 promoting replica r1 at store s4 to r4. Discarding replicas: (n5,s5):3,(n2,s2):2
Recovering range r66:/Table/55/1/-9222246136947173208 promoting replica r1 at store s4 to r4. Discarding replicas: (n5,s5):3,(n2,s2):2
Recovering range r85:/Table/55/1/-9222246136947109688 promoting replica r1 at store s4 to r4. Discarding replicas: (n5,s5):3,(n2,s2):2
```

Maybe something like this might be better (same dataset):

```
Total replicas known: 267
Live replicas analyzed: 157
Discarding dead replicas: 110
Discarding live replicas: 0
Ranges without quorum: 8
```

Also, the `make-plan` output says "promoting replica r1 at store s1 to r4", but `apply-plan` calls this replica 14, not 4.

Finally, there are a fair bit of typos and grammar issues in the CLI help text and such. That isn't a big deal in internal comments and such, but I think we should avoid it in user-facing text. Do you mind doing a pass over this? I'd be happy to do a pass as well, if you'd like.

>I haven't looked through the datadriven tests myself yet, but I saw a comment of Erik's where he suspected there were a number of scenarios we aren't covering yet. Adding those in (stopping short of those that require specialized states, like intents to abort or mismatching applied indexes etc, we can save those for the PRs that handle them) might be the last thing to do here before the merge, but it's probably even better to add these in in a follow-up PR. I'll defer to @erikgrinaker here.

Yeah, let's write additional tests later. Makes sense to defer that until the recovery logic is finalized.

> Reviewed 3 of 13 files at r10, 11 of 13 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-Mr2EA7R-V75xxYD9Vcb:b-j3uokn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum_test.go, line 176 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mr2Mg-kEoifFus562io:-Mr2Mg-kEoifFus562ip:be8btrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f702c63bcdf197df5972c5374c7f0dadfa7c2091/pkg/cli/debug_recover_loss_of_quorum_test.go#L176)):*
> ```Go
> 	).Connect(ctx)
> 	if err != nil {
> 		t.Fatal(err)
> ```

nit: why not `require.NoError` throughout?
___
*[pkg/kv/kvserver/loqrecovery/recovery_test.go, line 23 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUIrMLApL7nOBKvTzz:-Mr2FZI2D-apvz18petA:ba18k5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery_test.go#L23)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

With respect to this PR, it covers cases that are supported. Once we have range check and also committed index analyzed they need to be added as well. Currently we test what original recovery supported.
</blockquote></details>

Yeah, that's fine, we can add cases later. There's still many cases we should test, even with this initial logic. As a couple of basic examples: what happens if there's only a learner replica left? What happens if one replica underwent a split but another didn't? There's lots of scenarios like these.
___
*[pkg/kv/kvserver/loqrecovery/utils.go, line 50 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-Mr2PIQhCkzC4TlCJ0-o:-Mr2PIQhCkzC4TlCJ0-p:bmbh9yy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f702c63bcdf197df5972c5374c7f0dadfa7c2091/pkg/kv/kvserver/loqrecovery/utils.go#L50)):*
> ```Go
> // to lazily create batches and perform lifecycle management of the store
> // and the batch.
> type UpdatableStore struct {
> ```

It's unclear to me why this exists. It's only instantiated and used once, for `PrepareUpdateReplicas` and `CommitReplicaChanges`, but those functions could just as well take `map[roachpb.StoreID]storage.ReadWriter` containing batches. What does this type add that we can't already do with existing types?
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 229 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU62gZ4KQNn31-8Sj8:-Mr2HwMoEPMIBj0QS74p:bv2s78w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L229)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> I don't think that shouldn't be possible once we pick the store with the highest commit index

It will still be possible then. We would need to pick the store with the highest AppliedIndex. And even then, we might find that the true descriptor is visible on meta2 and has a replica on a store that didn't know about this yet. This would be a learner, and I think we'd get away with it (the voter wouldn't have the learner in its config, so raft wouldn't immediately crash), but it's a mess.

The simple fix here would be to add 10.
</blockquote></details>

Right. How about collecting all of the canonical range descriptors from meta2, and if it has quorum, use those to pick the new replica IDs? Adding 10 seems like an ok fallback.


<!-- Sent from Reviewable.io -->

2021-12-16 23:28 UTC, aliher1911 reviewed
I'm not sure how to calculate total replicas known without collecting all the data about all replicas in temporary maps. I'll drop statistics altogether except for basic counter.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-Mr4Y4cjAcMxVdz_PZyK:bp1f7tq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/cli/debug_recover_loss_of_quorum.go, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MpMdQh15QXZ4POS7RI-:-Mr2uxTk6-xobEzF276z:b-qqmg1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3b4540d74fb9b23c9628205727fc2adccc6f04b/pkg/cli/debug_recover_loss_of_quorum.go#L545)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Lost track, was this done or filed?
</blockquote></details>

Added in #73785
___
*[pkg/kv/kvserver/loqrecovery/recovery_test.go, line 23 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUIrMLApL7nOBKvTzz:-Mr4LS0iCDvhLCUdGlu-:b-ttz8py) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery_test.go#L23)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yeah, that's fine, we can add cases later. There's still many cases we should test, even with this initial logic. As a couple of basic examples: what happens if there's only a learner replica left? What happens if one replica underwent a split but another didn't? There's lots of scenarios like these.
</blockquote></details>

We'll get various inconsistent states. Do we want to record that behaviour in tests as expectations? I can do that. Not sure what is the benefit if they have to be dropped subsequently as we'll get a better solution.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 229 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU62gZ4KQNn31-8Sj8:-Mr2uFVE8CD0Wi3Rjc29:bbn9xlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L229)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Right. How about collecting all of the canonical range descriptors from meta2, and if it has quorum, use those to pick the new replica IDs? Adding 10 seems like an ok fallback.
</blockquote></details>

In #73756 it takes highest nextReplicaID out of all surviving replicas as next ID. 


<!-- Sent from Reviewable.io -->

2021-12-20 14:56 UTC, tbg commented
Did a runthrough. Cool stuff!

In `make-plan`, when I was providing the dead stores via the flag, I still get the output

> Discovered dead stores from provided files: s5, s6

which is now slightly confusing since I also provided them. Perhaps this should say

> Discovered dead stores from provided files: s5, s6 (this matches --dead-store-ids)

When I provide an additional bogus store that is not in the system as dead:

> ./cockroach debug recover make-plan --dead-store-ids 5,6,123 *.info.json > foo.json

This isn't pointed out, should this cause an error? I suppose it shouldn't; there could be situations in which a store died but because of constraints or dumb luck it isn't actually a member anywhere in the surviving system. So maybe this is working as intended. When I provide a live store as dead, the tool correctly refuses to make a plan.

Another comment about

> Discovered dead stores from provided files: s5, s6

In the case in which this is auto-detected, it might make sense to augment the following prompt with a request to verify that these are indeed the stores that the user thinks are dead forever. As is, it says `Proceed with plan creation [y/N]` but it's not really clear if the user should do anything and will probably blindly hit `y`.

After confirming, this output

```
Plan created
Run apply-plan on node n1, store(s) s1
Run apply-plan on node n2, store(s) s2
Run apply-plan on node n3, store(s) s3
Run apply-plan on node n4, store(s) s4
```

Is perhaps slightly vague? These are the follow-up instructions, but I'm not 100% sure this is how readers will understand it. Perhaps this would be better:

```
Plan created
To complete recovery, distribute the plan to the below nodes and invoke `apply-plan`:
- node n1, store(s) s1
- ...
```

When I don't provide the `-s` flag to `apply-plan`, I get misleading output:

```
$ roachprod ssh tobias-tpcc:1-4 -- ./cockroach debug recover apply-plan plan.json
tobias-tpcc: ./cockroach debug recover a... 4/4
   1: No updates planned on this node.
   2: No updates planned on this node.
   3: No updates planned on this node.
   4: No updates planned on this node.
```

This should really tell me that I need to point it at the store.

```
roachprod ssh tobias-tpcc:1-4 -- ./cockroach debug recover apply-plan -p y -s /mnt/data1/cockroach plan.json
```

worked.

The messages could be a wee bit more helpful:

> Replica 3 for range 251:/Table/59/1/105/55550 will be promoted to 14 with peer replica(s) removed: (n5,s5):1,(n6,s6):2

It would be nice to know which store Replica 3 is on. Perhaps just being consistent with the formatting would help:

> Replica (n3,s3):3 for range 251:/Table/59/1/105/55550 will be promoted to 14 with peer replica(s) removed: (n5,s5):1,(n6,s6):2

I have no idea what "promoted to 14" means, so that should probably be fixed as well. Does this mean `(n3,s3):14`?

I'd encourage you to react to my feedback above in a separate PR (and I think Erik also has a pass incoming, feel free to wait for that).

Also, as a last point, when restarted the surviving nodes, n2 quickly crashed:

```
F211220 14:45:58.659335 1620 kv/kvserver/store_remove_replica.go:98 ⋮ [n2,replicaGC,s2,r396/14:‹/Table/59/1/{79/470…-81/3892}›] 167  replica descriptor's ID has changed (14 >= 5)
```

(from the replicaGCQueue). I think this might've been on me; I messed up the restarting and briefly started some of the "dead" stores again too. But we definitely want a roachtest like that, which should have an issue filed as well. Documenting my steps below, they should translate pretty straightforwardly into a roachtest.

```
roachprod create -n 6 tobias-tpcc
roachprod put ...
roachprod start tobias-tpcc
roachprod run tobias-tpcc:1 -- ./cockroach workload fixtures import tpcc --warehouses 300 --checks=false
roachprod run tobias-tpcc:6 ./cockroach workload run -- tpcc --warehouses=300 --duration 300s {pgurl:1-5}
roachprod stop tobias-tpcc:5,6
roachprod ssh tobias-tpcc:1-4 -- ./cockroach debug recover collect-info -s /mnt/data1/cockroach info.json
roachprod get tobias-tpcc:1-4 info.json
./cockroach debug recover make-plan --dead-store-ids 5,6 *.info.json > plan.json
roachprod put tobias-tpcc:1-4 -- plan.json
roachprod ssh tobias-tpcc:1-4 -- ./cockroach debug recover apply-plan -p y -s /mnt/data1/cockroach plan.json
roachprod start tobias-tpcc:1-4
```

2021-12-20 16:25 UTC, tbg commented
Also, it just occurred to me that the above would make for a great demo on the kv joint weekly. Would you be up for giving it early next year? If so consider penciling in.

2021-12-20 16:58 UTC, erikgrinaker approved these changes
> I'm not sure how to calculate total replicas known without collecting all the data about all replicas in temporary maps. I'll drop statistics altogether except for basic counter.

Ok, your call. I think this might be useful in reassuring operators that it's doing something expected, but I won't push for it.

> Reviewed 8 of 8 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MrNk6pS9JoBPOBsBMNF:b-z2zerb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/kv/kvserver/loqrecovery/recovery_test.go, line 23 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqUIrMLApL7nOBKvTzz:-MrNlRatCq0fr36R0BdA:b-r5j8zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery_test.go#L23)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

We'll get various inconsistent states. Do we want to record that behaviour in tests as expectations? I can do that. Not sure what is the benefit if they have to be dropped subsequently as we'll get a better solution.
</blockquote></details>

Let's do it in a later PR, once the recovery logic has been revised. But yeah, we should have tests for sad paths too -- I'd argue those are just as useful/important as the happy paths, if not more so.
___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 229 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU62gZ4KQNn31-8Sj8:-MrNktfD0RZ36Tk7BVm-:bnyaxst) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L229)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

In #73756 it takes highest nextReplicaID out of all surviving replicas as next ID. 
</blockquote></details>

Couldn't that still cause issues if the dead replicas have already applied changes to the canonical descriptor that the surviving replicas haven't learned about yet? But let's discuss over on #73756.


<!-- Sent from Reviewable.io -->

2021-12-21 12:51 UTC, aliher1911 reviewed
```
tobias-tpcc: ./cockroach debug recover a... 4/4
   1: No updates planned on this node.
```
This is interesting, I think you have a cockroach-data directory where you run the command, otherwise it would fail to open store and fail. I think message should include read store and node id(s). Would it be an issue in prod? I guess if client env is so messy to have random directories laying around that would confuse those commands.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MrRx4Fc-I7giwDg4dTe:bpd0drc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)

___
*[pkg/kv/kvserver/loqrecovery/recovery.go, line 229 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-MqU62gZ4KQNn31-8Sj8:-MrS0PeI8k-dR7iKNlgj:b-f0mbnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23187fe1556715967ee6b5c44fed82cc8e8a06e/pkg/kv/kvserver/loqrecovery/recovery.go#L229)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Couldn't that still cause issues if the dead replicas have already applied changes to the canonical descriptor that the surviving replicas haven't learned about yet? But let's discuss over on #73756.
</blockquote></details>

This is true! I think we might keep adding 10 even in that case. I'll update that PR.


<!-- Sent from Reviewable.io -->

2021-12-21 13:00 UTC, tbg reviewed
Oh, yeah, I likely did. Should we be comparing the cluster ID which is part of StoreID and thread it through the plans, etc? I don't think this is particularly urgent but it might be worth filing away as a follow-up issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71996#-:-MrS3kF-5MAOacU5gfoO:bhht0q1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @tbg)



<!-- Sent from Reviewable.io -->

2021-12-21 15:57 UTC, aliher1911 commented
bors r=erikgrinaker,tbg

2021-12-21 17:50 UTC, merged