Roachprod: Add custom label to roachprod
cockroachdb/cockroach pull request #72014
Opened 2021-10-27 03:35 UTC by xun-cockroachlabs

To add a new custom label use  `--label labelName=labelValue`.

Addresses: #71531  

Release note: None

2021-10-27 12:23 UTC, miretskiy requested changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @petermattis, and @xun-cockroachlabs)

___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0g4OB6iEA1AhXLKqK:-Mn0g4OB6iEA1AhXLKqL:brm7110) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L809)):*
> ```Go
> 			fmt.Sprintf("name=%s", name),
> 			"roachprod=true"},
> 			opts.LabelOpts...)
> ```

I'm not saying the change from Lifetime -> lifetime is unnecessary; but I'm not a fan of making
such changes combined with the other changes.  If you feel strongly that you need
to lower case these options, then I'd send out a separate PR.  To be honest, I'm not sure why we're doing this.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0gcS6D2UQ8vecPEND:-Mn0gcS72NGbstIsIKIo:b-3xo498) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/azure/azure.go#L126)):*
> ```Go
> 	clusterTags[tagLifetime] = to.StringPtr(opts.Lifetime.String())
> 	clusterTags[tagRoachprod] = to.StringPtr("true")
> 	for _, opt := range opts.LabelOpts {
> ```

Is it necessary to repeat the same code for each provider?
Why not turn opts.LabelOpts into a real map?  See for example the way `ebsVolumeList` is implemented in aws.go.
I think something similar, where you have `customLabelMap` could make parsing, validating and using label options much simpler.


<!-- Sent from Reviewable.io -->

2021-10-27 14:51 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, and @xun-cockroachlabs)

___
*[pkg/cmd/roachprod/main.go, line 1918 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1CegB5mlNTk0f5cvK:-Mn1CegB5mlNTk0f5cvL:bjrr44y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/main.go#L1918)):*
> ```Go
> 
> 	createCmd.Flags().StringSliceVarP(&createVMOpts.LabelOpts,
> 		"label", "s", []string{},
> ```

The short form flag names are useful for frequently used flags. The `--label` flag is not frequently used, so I'd recommend getting rid of the short flag (i.e. use `StringSliceVar`, not `StringSliceVarP`). You'll want to fix up the help text to not mention `-s`.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1D0t-Aoh-_bC3ly_9:-Mn1D0t-Aoh-_bC3ly_A:b8veka1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L714)):*
> ```Go
> 			for _, entry := range in.Tags {
> 				tagMap[entry.Key] = entry.Value
> 				sb.WriteString(fmt.Sprintf("{Key=%s,Value=%s},", entry.Key, entry.Value))
> ```

What is the format of the `Labels` field? As written, we'll send something like `[{Key=foo,Value=bar},]` which doesn't look like valid json. Does this need to be json.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0g4OB6iEA1AhXLKqK:-Mn1DUSv17Nve0iTriaj:bfs9f54) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L809)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm not saying the change from Lifetime -> lifetime is unnecessary; but I'm not a fan of making
such changes combined with the other changes.  If you feel strongly that you need
to lower case these options, then I'd send out a separate PR.  To be honest, I'm not sure why we're doing this.
</blockquote></details>

Ditto what @miretskiy said. I'll go further: I suspect you've introduced a bug. Existing clusters with the uppercase `lifetime` tag will no longer be recognized and would no longer be reclaimed by the periodic `roachprod gc` process which would be Bad. The testing around this functionality is not great (perhaps non-existent), so it pays to be overly paranoid and not changing anything that doesn't absolutely need to be changed.


<!-- Sent from Reviewable.io -->

2021-10-28 18:59 UTC, xun-cockroachlabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, and @petermattis)

___
*[pkg/cmd/roachprod/main.go, line 1918 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1CegB5mlNTk0f5cvK:-Mn7G9b_DoLZnnaJlild:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/main.go#L1918)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The short form flag names are useful for frequently used flags. The `--label` flag is not frequently used, so I'd recommend getting rid of the short flag (i.e. use `StringSliceVar`, not `StringSliceVarP`). You'll want to fix up the help text to not mention `-s`.
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1D0t-Aoh-_bC3ly_9:-Mn7GB163g76gl83sZ8a:bdlqpqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L714)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What is the format of the `Labels` field? As written, we'll send something like `[{Key=foo,Value=bar},]` which doesn't look like valid json. Does this need to be json.
</blockquote></details>

Replaced with map per comment from Yevgeniy.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0g4OB6iEA1AhXLKqK:-Mn2Hv04-sz4UHVJFC9e:b-xyhda8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L809)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ditto what @miretskiy said. I'll go further: I suspect you've introduced a bug. Existing clusters with the uppercase `lifetime` tag will no longer be recognized and would no longer be reclaimed by the periodic `roachprod gc` process which would be Bad. The testing around this functionality is not great (perhaps non-existent), so it pays to be overly paranoid and not changing anything that doesn't absolutely need to be changed.
</blockquote></details>

Before the change I experimented with both `--Lifetime==2h` and `--lifetime=2h` and both worked properly, so it looks cmd line option is case insensitive.
I agree with you this is risky change giving the current test coverage, so I will revert this.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0gcS6D2UQ8vecPEND:-Mn7GMJ2EzzbPERBkKST:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/azure/azure.go#L126)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Is it necessary to repeat the same code for each provider?
Why not turn opts.LabelOpts into a real map?  See for example the way `ebsVolumeList` is implemented in aws.go.
I think something similar, where you have `customLabelMap` could make parsing, validating and using label options much simpler.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-28 19:02 UTC, xun-cockroachlabs reviewed
Tested gcp and azure, have some aws auth issue(before it worked fine, see error below), will test aws once I resolve the issue.
```
Code="ExpiredAuthenticationToken" Message="The access token expiry UTC time '10/28/2021 6:10:15 PM' is earlier than current UTC time '10/28/2021 6:11:41 PM'."
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-:-Mn7GYid26wfIcxFyhlI:bxhk84x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, and @petermattis)



<!-- Sent from Reviewable.io -->

2021-10-28 20:01 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, @petermattis, and @xun-cockroachlabs)

___
*[pkg/cmd/roachprod/vm/vm.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7SNOo0uB3-MOgZIxr:-Mn7SNOp7F8q2ZrpiNns:b8rzvxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L32)):*
> ```Go
> const (
> 	TagCluster   = "cluster"
> 	// RFC3339-formatted timestamp.
> ```

not sure what this comment refers to.
___
*[pkg/cmd/roachprod/vm/vm.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7Tm0r85aEgp83d6U7:-Mn7Tm0r85aEgp83d6U8:b52l437) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L34)):*
> ```Go
> 	// RFC3339-formatted timestamp.
> 	TagCreated   = "created"
> 	TagLifetime  = "lifetime"
> ```

I thought we decided to stick with upper case.. Or are these different tags?
___
*[pkg/cmd/roachprod/vm/vm.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7Scjm4bpESd6W4OcY:-Mn7Scjm4bpESd6W4OcZ:b-vcbnyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L39)):*
> ```Go
> 
> type customLabelMap map[string]string
> var labelMapMutex = sync.RWMutex{}
> ```

I don't understand why we need mutex here.  Command line argument parsing is not multi threaded.
___
*[pkg/cmd/roachprod/vm/vm.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7TxOtE325fx68fnYD:-Mn7TxOtE325fx68fnYE:b-h2w31p) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L45)):*
> ```Go
> 	parts := strings.Split(s, "=")
> 	if len(parts) != 2 {
> 		return fmt.Errorf("wrong label defintion: %s, must be 'name=value' format, example: usage=cloud-report-2020", s)
> ```

should we allow empty label value?  Seems legit use case, though presumably you can do `name=''`..
Just not sure we need to error out here.
___
*[pkg/cmd/roachprod/vm/vm.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7UBQp1RLeeyWhyL7w:-Mn7UBQqCA8icK3QaH1q:b1mcki7) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L75)):*
> ```Go
> // TryAddDefaultTags checks if a common set of labels exist in m, add any that
> // doesn't exist.
> func (m *customLabelMap) TryAddDefaultTags(opts CreateOpts) {
> ```

probably doesn't need to be exported.
___
*[pkg/cmd/roachprod/vm/vm.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7UDgc27No-gi3Kgp-:-Mn7UDgc27No-gi3Kgp0:b6u18wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L89)):*
> ```Go
> // CheckAndAdd checks label name doesn't exists in m, then add it into m,
> // else returns error.
> func (m *customLabelMap) CheckAndAdd(name string, value string) error {
> ```

does this need to be exported?
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1D0t-Aoh-_bC3ly_9:-Mn7Takc6q0HWvQ22jhq:bt2wlxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L714)):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

Replaced with map per comment from Yevgeniy.
</blockquote></details>

I think @petermattis comment still stands: what's the format? This doesn't appear to be valid json.
(like strings are not quoted).


<!-- Sent from Reviewable.io -->

2021-10-28 21:30 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, and @xun-cockroachlabs)

___
*[pkg/cmd/roachprod/main.go, line 1918 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1CegB5mlNTk0f5cvK:-Mn7jdopDhiHi-Hvqw7H:b-n4qgo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/main.go#L1918)):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nit: `s/VarP/Var`, and then you don't have to pass `""` for the short-hand flag.
___
*[pkg/cmd/roachprod/vm/vm.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7n0Oo9K21-INM33eZ:-Mn7n0Oo9K21-INM33e_:b-bhskqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L38)):*
> ```Go
> )
> 
> type customLabelMap map[string]string
> ```

Rather than this new type, I think you can use the `pflag.FlagSet.StringToString` type. 
___
*[pkg/cmd/roachprod/vm/vm.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7Scjm4bpESd6W4OcY:-Mn7m_oK4HUf8dap1_xQ:b-yks69i) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L39)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't understand why we need mutex here.  Command line argument parsing is not multi threaded.
</blockquote></details>

Ditto about the lack of need for thread safety. And if you want thread safety you should put the mutex inside of the `customLabelMap` type instead of using a global.
___
*[pkg/cmd/roachprod/vm/vm.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7mSKr7Jjj0D7qmb4O:-Mn7mSKs49zYXVWIZCoM:b-sb0pg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L65)):*
> ```Go
> // Type implements flag Value interface.
> func (m *customLabelMap) Type() string {
> 	return "JSON"
> ```

This doesn't look like JSON to me. The syntax looks like `key=value`.
___
*[pkg/cmd/roachprod/vm/vm.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7mNbn7FYAGNhcprXO:-Mn7mNbn7FYAGNhcprXP:btiumh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L70)):*
> ```Go
> // String Implements flag Value interface.
> func (m *customLabelMap) String() string {
> 	return "CustomLabelMap"
> ```

Shouldn't this be formatting the contents of the map?
___
*[pkg/cmd/roachprod/vm/vm.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7nG_h-x787CtYSSUd:-Mn7nG_h-x787CtYSSUe:b46903a) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L79)):*
> ```Go
> 	time := timeutil.Now().Format(time.RFC3339)
> 	// Format according to gce label naming convention requirement.
> 	if len(opts.VMProviders) > 0 && opts.VMProviders[0] == "gce" {
> ```

Putting VM provider specifics in this generic code is an abstraction violation.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1D0t-Aoh-_bC3ly_9:-Mn7lK2O2ut9w34LA8jW:b216k0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L714)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think @petermattis comment still stands: what's the format? This doesn't appear to be valid json.
(like strings are not quoted).
</blockquote></details>

@xun-cockroachlabs I still don't know what the format this is adhering to. More importantly, `sb` is unused, so why are you populating it?
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0g4OB6iEA1AhXLKqK:-Mn7k3B50T_3F6-7Hm0W:b-6j7uel) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L809)):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

Before the change I experimented with both `--Lifetime==2h` and `--lifetime=2h` and both worked properly, so it looks cmd line option is case insensitive.
I agree with you this is risky change giving the current test coverage, so I will revert this.
</blockquote></details>

@xun-cockroachlabs I think you misunderstood my concern and @miretskiy's. The concern is not about the `--lifetime` vs `--Lifetime` flag. It is about the tags you're passing to AWS. Unless I'm completely misunderstanding this code, it is dealing with the AWS tags. As far as I can tell, those tags are case sensitive, so we absolutely do not want to change the case of tags that are in use for existing roachprod clusters. 
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 729 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7kfwO52wxPUKrO3v1:-Mn7kfwO52wxPUKrO3v2:b-kxsln1) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/aws/aws.go#L729)):*
> ```Go
> 
> 			var lifetime time.Duration
> 			if lifeText, ok := tagMap["lifetime"]; ok {
> ```

Please keep the capitalization of this tag as `Lifetime`.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 814 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7lgZxAt7P63KQyRrV:-Mn7lgZxAt7P63KQyRrW:byvknc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/aws/aws.go#L814)):*
> ```Go
> 		sb.WriteString(fmt.Sprintf("{Key=%s,Value=%s},", key, value))
> 	}
> 	tagSpecs := fmt.Sprintf("ResourceType=instance,Tags=[%s]", sb.String())
> ```

I would have written this as:

```
	var sb strings.Builder
	sb.WriteString("ResourceType=instance,Tags=[")
	for key, value := range opts.CustomLabelMap {
		fmt.Fprintf(&sb, "{Key=%s,Value=%s},", key, value)
	}
	sb.WriteString("]")
	tagSpecs := sb.String()
```

Note that the whole point of `strings.Builder` and `bytes.Buffer` are that they implement the `io.Writer` interface and can thus be formatted into use `fmt.Fprintf`. 


<!-- Sent from Reviewable.io -->

2021-10-29 00:18 UTC, xun-cockroachlabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, @petermattis, and @xun-cockroachlabs)

___
*[pkg/cmd/roachprod/vm/vm.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7SNOo0uB3-MOgZIxr:-Mn7Y-3-97cT5glSPeFR:b1sc071) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L32)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

not sure what this comment refers to.
</blockquote></details>

This is from the original comment from `azure.go`, I just moved it to this file. It refers to the time format used for this label field. It looks I need to move it back to `azure.go` per Peter's command `vm.go` shouldn't contain provider specific implementation.
___
*[pkg/cmd/roachprod/vm/vm.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7Tm0r85aEgp83d6U7:-Mn7aB-Y3gqtg0z5VnEa:b-f3kogf) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L34)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I thought we decided to stick with upper case.. Or are these different tags?
</blockquote></details>

I keep the same casing as the original change, for some reason different providers use different casing for these labels.
___
*[pkg/cmd/roachprod/vm/vm.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7n0Oo9K21-INM33eZ:-Mn8JZ6G2uMxjH6Fmxsy:brss75d) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L38)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Rather than this new type, I think you can use the `pflag.FlagSet.StringToString` type. 
</blockquote></details>

It seems to me we still need the new type definition, so we can override `Set(string), Type(), String()` method to implement our logic?
___
*[pkg/cmd/roachprod/vm/vm.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7Scjm4bpESd6W4OcY:-Mn8LDI9-KGsS-c-BMSc:b-5gr12o) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L39)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ditto about the lack of need for thread safety. And if you want thread safety you should put the mutex inside of the `customLabelMap` type instead of using a global.
</blockquote></details>

Mutex seems to be necessary, as earlier aws run hit concurrent map write issue, I could take @petermattis 's suggestion though.
```
roachprod create xun-cldrprt22-c5a-4xlarge-2149426116 -n 2 --lifetime 24h --clouds aws --aws-machine-type c5a.4xlarge --aws-ebs-volume-type=gp2 --aws-ebs-volume-size=2500 --aws-zones=us-east-1a --aws-image-ami=ami-036490d46656c4818 --local-ssd=false --aws-enable-multiple-stores
Creating cluster xun-cldrprt22-c5a-4xlarge-2149426116 with 2 nodes
fatal error: concurrent map writes
```
___
*[pkg/cmd/roachprod/vm/vm.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7TxOtE325fx68fnYD:-Mn8P64z0-twrApFwwYr:b-iefmh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L45)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should we allow empty label value?  Seems legit use case, though presumably you can do `name=''`..
Just not sure we need to error out here.
</blockquote></details>

Good point. I will experiment all providers to make sure empty label is allowed, change the implementation if so.
___
*[pkg/cmd/roachprod/vm/vm.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7mSKr7Jjj0D7qmb4O:-Mn8MMGC2g2VF9PKepZQ:bpq47ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L65)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This doesn't look like JSON to me. The syntax looks like `key=value`.
</blockquote></details>

By looking at `Value` interface of flag.go, there is no document on the method. From our repo there are different ways to implement the function, the majority is a string specify the type of the interface so I will change to follow this pattern.

https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachprod/vm/gce/gcloud.go#L224
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1D0t-Aoh-_bC3ly_9:-Mn8NwQDAy-nFkGWr_kL:b-lbw7hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L714)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@xun-cockroachlabs I still don't know what the format this is adhering to. More importantly, `sb` is unused, so why are you populating it?
</blockquote></details>

I should have removed the `sb` related code. `Labels` is a new field added by me to record Label information, in last change I already changed the definition to: `Labels   customLabelMap `json:"labels"`
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0g4OB6iEA1AhXLKqK:-Mn86UCj4Xu1EMwEcCjW:b-s40lsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L809)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@xun-cockroachlabs I think you misunderstood my concern and @miretskiy's. The concern is not about the `--lifetime` vs `--Lifetime` flag. It is about the tags you're passing to AWS. Unless I'm completely misunderstanding this code, it is dealing with the AWS tags. As far as I can tell, those tags are case sensitive, so we absolutely do not want to change the case of tags that are in use for existing roachprod clusters. 
</blockquote></details>

Thanks for the clarification.
It looks the current implementation has a mixed casing for different providers, for example Azure uses "lifetime" tag name:
https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachprod/vm/azure/azure.go#L498


<!-- Sent from Reviewable.io -->

2021-10-30 16:51 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, @petermattis, and @xun-cockroachlabs)

___
*[pkg/cmd/roachprod/vm/vm.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7n0Oo9K21-INM33eZ:-MnH56UK7tH5GxhcYzxp:bpfzdrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L38)):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

It seems to me we still need the new type definition, so we can override `Set(string), Type(), String()` method to implement our logic?
</blockquote></details>

Why would you need to override `Set(string)`, `Type()`, and `String()`? You're trying to read a set of key=value pairs as a flag value. I'm pretty sure `pflag.FlagSet.StringToString` does exactly that.
___
*[pkg/cmd/roachprod/vm/vm.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7Scjm4bpESd6W4OcY:-MnH5ISgBPI5kpQS4Bi6:b6bjh4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L39)):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

Mutex seems to be necessary, as earlier aws run hit concurrent map write issue, I could take @petermattis 's suggestion though.
```
roachprod create xun-cldrprt22-c5a-4xlarge-2149426116 -n 2 --lifetime 24h --clouds aws --aws-machine-type c5a.4xlarge --aws-ebs-volume-type=gp2 --aws-ebs-volume-size=2500 --aws-zones=us-east-1a --aws-image-ami=ami-036490d46656c4818 --local-ssd=false --aws-enable-multiple-stores
Creating cluster xun-cldrprt22-c5a-4xlarge-2149426116 with 2 nodes
fatal error: concurrent map writes
```
</blockquote></details>

Huh, that's curious. You should track down where the concurrent map access is coming from (there should be goroutine stack traces showing where it happened. As @miretskiy said, command line parsing is not multi-threaded. My suspicion is that you're using this `customLabelMap` class somewhere that is multi-threaded.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0g4OB6iEA1AhXLKqK:-MnH5im95hcxx8Pua_4_:b-iyvj7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L809)):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

Thanks for the clarification.
It looks the current implementation has a mixed casing for different providers, for example Azure uses "lifetime" tag name:
https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachprod/vm/azure/azure.go#L498
</blockquote></details>

Yes, the current implementation uses different casing in AWS vs what is used in Azure and GCE. I don't think you can reasonably fix that if the casing matters. But perhaps it doesn't matter. You could check what AWS does for tags that differ only in case. Assuming the casing does matter, I don't see an easy way to normalize the case in a single PR. What you'd have to do is to change this code to handle either case when reading. Let that get propagated out to every usage of `roachprod`, and then many months later, change the code to write in lower case. Perhaps there is an easier approach I'm not thinking of. What we definitely can't do is simply change the AWS tags to be lowercase. That will break the usage of those tags on existing roachprod clusters.


<!-- Sent from Reviewable.io -->

2021-11-01 19:35 UTC, xun-cockroachlabs reviewed
With this change, it introduced a strange issue (for both aws and azure, gcp is fine), that after the cluster gets successfully created by `if createErr := cld.CreateCluster(numNodes, createVMOpts); createErr != nil {` call in main.go, the cloud list would fail to list the just created cluster in this line: https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachprod/main.go#L458. 
I was struggling yesterday on this issue and still couldn't figure out why, other than breaking one map with lock into 2 map, my change should be equivalent as the previous changed version, and I don't see how this change could break cloud listing functionality.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-:-MnRy1rm-eHc12v392bc:b-1pwu1n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, and @petermattis)

___
*[pkg/cmd/roachprod/main.go, line 1918 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1CegB5mlNTk0f5cvK:-MnDB-KT-NqgjTd9hIxc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/main.go#L1918)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `s/VarP/Var`, and then you don't have to pass `""` for the short-hand flag.
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/vm.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7SNOo0uB3-MOgZIxr:-MnH-P300VQBX9DAPKNH:bowc917) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L32)):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

This is from the original comment from `azure.go`, I just moved it to this file. It refers to the time format used for this label field. It looks I need to move it back to `azure.go` per Peter's command `vm.go` shouldn't contain provider specific implementation.
</blockquote></details>

I will keep it in the current file as the other provider files also use it.
___
*[pkg/cmd/roachprod/vm/vm.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7n0Oo9K21-INM33eZ:-MnRwhiMB5hIJkWZfgQ6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L38)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Why would you need to override `Set(string)`, `Type()`, and `String()`? You're trying to read a set of key=value pairs as a flag value. I'm pretty sure `pflag.FlagSet.StringToString` does exactly that.
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/vm.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7Scjm4bpESd6W4OcY:-MnRwjZ30ABA71JBwMu8:bwcykih) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L39)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Huh, that's curious. You should track down where the concurrent map access is coming from (there should be goroutine stack traces showing where it happened. As @miretskiy said, command line parsing is not multi-threaded. My suspicion is that you're using this `customLabelMap` class somewhere that is multi-threaded.
</blockquote></details>

I debugged it, it's because `aws.go's runInstance` looks to be executed in parallel by multiple nodes, the debugging logging definitely shows the method gets run in parallel. So I modify the implementation to use a local map to record default labels that get generated inside the function. 
___
*[pkg/cmd/roachprod/vm/vm.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7mNbn7FYAGNhcprXO:-MnDB1Rf7NuWB-M_mQmh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L70)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Shouldn't this be formatting the contents of the map?
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/vm.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7UBQp1RLeeyWhyL7w:-MnDB3YKA41UTWkQljOI:b-s3lnvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L75)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

probably doesn't need to be exported.
</blockquote></details>

This needs to be exported as provider go files such as `aws.go` icalls it.
___
*[pkg/cmd/roachprod/vm/vm.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7nG_h-x787CtYSSUd:-MnDBHIbCnM-Eo5C5ib_:b-itu4st) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L79)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Putting VM provider specifics in this generic code is an abstraction violation.
</blockquote></details>

Moved to provider go files.
___
*[pkg/cmd/roachprod/vm/vm.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7UDgc27No-gi3Kgp-:-MnD4Vol8qYlkGygQ53W:bj0rrg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/vm.go#L89)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

does this need to be exported?
</blockquote></details>

This needs to be exported as `aws.go` calls it.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0g4OB6iEA1AhXLKqK:-MnMqEY52dAFsYOOXoEM:bz55i83) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L809)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, the current implementation uses different casing in AWS vs what is used in Azure and GCE. I don't think you can reasonably fix that if the casing matters. But perhaps it doesn't matter. You could check what AWS does for tags that differ only in case. Assuming the casing does matter, I don't see an easy way to normalize the case in a single PR. What you'd have to do is to change this code to handle either case when reading. Let that get propagated out to every usage of `roachprod`, and then many months later, change the code to write in lower case. Perhaps there is an easier approach I'm not thinking of. What we definitely can't do is simply change the AWS tags to be lowercase. That will break the usage of those tags on existing roachprod clusters.
</blockquote></details>

My approach is to follow your previous comment, not to change the existing labels' casing for any provider, as you can see in my latest change I reverted aws's casing change. This can safely guarantee that we don't bring any breaking changes. I agree in the long run if we can switch to all lower casing that's nice, for now I just want to make a safe code change that doesn't bring any breaking change. Let me know if this is the right approach.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 729 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn7kfwO52wxPUKrO3v1:-MnD4oTX405SlTeranS4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/794cbf4647142ec886b2f0f00e99695250aed03a/pkg/cmd/roachprod/vm/aws/aws.go#L729)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Please keep the capitalization of this tag as `Lifetime`.
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 814 at r2](https://reviewable.io/reviews/cockroachdb/cock [...]

2021-11-01 19:48 UTC, xun-cockroachlabs reviewed
I will remove the debugging in next change, when I figure out the root cause of this issue. Keep it if you could like to run the version to repro the issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-:-MnS1h2R6cQvK_yE_Ob2:bodq7q4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, @petermattis, and @ZhouXing19)



<!-- Sent from Reviewable.io -->

2021-11-02 14:06 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, @xun-cockroachlabs, and @ZhouXing19)

___
*[pkg/cmd/roachprod/cloud/cluster_cloud.go, line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MnVvi62A8Cia6AAGWLS:-MnVvi62A8Cia6AAGWLT:bckn27m) ([raw file](https://github.com/cockroachdb/cockroach/blob/497ff10789ae78ab361632579adae59280d79905/pkg/cmd/roachprod/cloud/cluster_cloud.go#L174)):*
> ```Go
> 			userName, clusterName, err := namesFromVM(v)
> 			if p.Name() == "azure" {
> 				fmt.Printf("username:%s, clustername:%s, error:%s\n", userName, clusterName, err)
> ```

Did you mean to leave this in?
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1D0t-Aoh-_bC3ly_9:-MnVw7PG4VeJ4sGMUjs-:bpx4zjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L714)):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

I should have removed the `sb` related code. `Labels` is a new field added by me to record Label information, in last change I already changed the definition to: `Labels   customLabelMap `json:"labels"`
</blockquote></details>

Are you going to remove this code? It doesn't look like it is doing anything.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0g4OB6iEA1AhXLKqK:-MnVwWbYDZcdQmYwmJsm:b-nk6j9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L809)):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

My approach is to follow your previous comment, not to change the existing labels' casing for any provider, as you can see in my latest change I reverted aws's casing change. This can safely guarantee that we don't bring any breaking changes. I agree in the long run if we can switch to all lower casing that's nice, for now I just want to make a safe code change that doesn't bring any breaking change. Let me know if this is the right approach.
</blockquote></details>

I think it is correct to not change the existing casing used by the cloud providers. Unfortunately, you now have duplicate labels in the AWS case. It looks to me like the AWS tags will contain both `Lifetime` and `lifetime`, and `Roachprod` and `roachprod`. That is going to be quite confusing and error prone for the future. 

I suggest you define a map from the keys used in `opts.CustomLabelMap` to the tags used by AWS. Something like:

```
var awsLabelMap = map[string]string {
  vm.TagCluster: "name",
  vm.TagCreated: "created",
  vm.TagLifetime: "lifetime",
  vm.TagRoachprod: "roachprod",
}
```

Then in the loop below where you're merging `opts.CustomLabelMap` into `m` you do:

```
m := make(map[string]string)
for key, value := range opts.CustomLabelMap {
  m[awsLabelToTag[key]] = value
}
```

I think this gets rid of the need to initialize `m` as you're currently doing, though I might be missing something. Be sure to scrutinize this.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MnVx-nbAZS4qjFrcq81:-MnVx-nbAZS4qjFrcq82:b-6l5gvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/497ff10789ae78ab361632579adae59280d79905/pkg/cmd/roachprod/vm/azure/azure.go#L117)):*
> ```Go
> 
> 	m := vm.GetDefaultLabelMap(opts)
> 	m[vm.TagCreated]= timeutil.Now().Format(time.RFC3339)
> ```

Nit: there is a missing space before the `=` suggesting that this code hasn't be run through `gofmt` or a similar tool (`crlfmt`).


<!-- Sent from Reviewable.io -->

2021-11-02 22:14 UTC, xun-cockroachlabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, @petermattis, and @ZhouXing19)

___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn1D0t-Aoh-_bC3ly_9:-MnWRQI_0HMwqBaXcsbH:b44pr89) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L714)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are you going to remove this code? It doesn't look like it is doing anything.
</blockquote></details>

I had already removed it, then need to debug the list cloud issue and revert to previous version multiple times, sorry forgot to remove this again with the last submission.
___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn0g4OB6iEA1AhXLKqK:-MnWQFiuDURsLYOvz9Vr:b-dbi3x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d4278cc2f06942b21ecd0f675f2bffcb3621aec/pkg/cmd/roachprod/vm/aws/aws.go#L809)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think it is correct to not change the existing casing used by the cloud providers. Unfortunately, you now have duplicate labels in the AWS case. It looks to me like the AWS tags will contain both `Lifetime` and `lifetime`, and `Roachprod` and `roachprod`. That is going to be quite confusing and error prone for the future. 

I suggest you define a map from the keys used in `opts.CustomLabelMap` to the tags used by AWS. Something like:

```
var awsLabelMap = map[string]string {
  vm.TagCluster: "name",
  vm.TagCreated: "created",
  vm.TagLifetime: "lifetime",
  vm.TagRoachprod: "roachprod",
}
```

Then in the loop below where you're merging `opts.CustomLabelMap` into `m` you do:

```
m := make(map[string]string)
for key, value := range opts.CustomLabelMap {
  m[awsLabelToTag[key]] = value
}
```

I think this gets rid of the need to initialize `m` as you're currently doing, though I might be missing something. Be sure to scrutinize this.
</blockquote></details>

I think the current implementation works, it will not populate two sets of labels such as `Lifetime` and `lifetime`, as I didn't call `vm.GetDefaultLabelMap(opts)` as other providers do, instead I generated `m` map with the correct upper casing names to populate the aws tags.

I will take your suggestion, though, to use the map from keys used by `opts.CustomLabelMap` to the aws tags. This will allow me to handle de-duping more correctly on sample input `--label lifetime=1h`: In the current version it will think it's a different label key and accept that. With the new change it will block that, as ideally we should not allow user to enter ambiguous key with only casing difference: I agree with you they will be confusing at the least. 
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MnVx-nbAZS4qjFrcq81:-MnWYQ8J8AMhe_0ZoMZv:b-hn10mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/497ff10789ae78ab361632579adae59280d79905/pkg/cmd/roachprod/vm/azure/azure.go#L117)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: there is a missing space before the `=` suggesting that this code hasn't be run through `gofmt` or a similar tool (`crlfmt`).
</blockquote></details>

I added the tools before for managed-service, didn't realize it's a per project setting. Just added .
___
*[pkg/cmd/roachprod/cloud/cluster_cloud.go, line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MnVvi62A8Cia6AAGWLS:-MnWQeBJEaOBXfzMdhmi:b-ihg0s7) ([raw file](https://github.com/cockroachdb/cockroach/blob/497ff10789ae78ab361632579adae59280d79905/pkg/cmd/roachprod/cloud/cluster_cloud.go#L174)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Did you mean to leave this in?
</blockquote></details>

I left a comment yesterday that I am going to remove added debugging in next change, I meant to keep them for convenience if you intend to repro the list cloud issue that I mentioned.


<!-- Sent from Reviewable.io -->

2021-11-03 05:07 UTC, xun-cockroachlabs reviewed
Finally figure out the root cause of the above issue and get it fixed.
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-:-MnZBH545yuGMWPRUgC6:b-4clw57)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, @petermattis, and @ZhouXing19)



<!-- Sent from Reviewable.io -->

2021-11-03 12:30 UTC, miretskiy approved these changes
I think this <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> to me (modulo few minor nits), but please wait for :thumbsup: from @petermattis as well.

> Reviewed 5 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-:-Mn_lkBED8pKV5RXJlNY:b-jx5kk0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @bobvawter, @miretskiy, @petermattis, @xun-cockroachlabs, and @ZhouXing19)

___
*[pkg/roachprod/vm/vm.go, line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn_kkb07_w4Lg1RQ4hp:-Mn_kkb07_w4Lg1RQ4hq:bj4n7gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e67d18cf07635dc523314496b981632f2cb0da/pkg/roachprod/vm/vm.go#L45)):*
> ```Go
> 	m[TagCluster] = opts.ClusterName
> 	m[TagLifetime] = opts.Lifetime.String()
> 	m[TagRoachprod] = "true"
> ```

nit: perhaps simply
```
return map[string]string {
  TagCluster: ...,
   TagLIfetime ....
 }
```
___
*[pkg/roachprod/vm/aws/aws.go, line 832 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-Mn_lMLp9Jz8428b7jxX:-Mn_lMLp9Jz8428b7jxY:brlqq47) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e67d18cf07635dc523314496b981632f2cb0da/pkg/roachprod/vm/aws/aws.go#L832)):*
> ```Go
> 	// all of our metadata into the tagSpec.
> 	m := vm.GetDefaultLabelMap(opts)
> 	var awsLabelMap = map[string]string{
> ```

nit: perhaps rename to `awsLabelsNameMap` to make it explicit that this map defines label names (and not actual labels)?


<!-- Sent from Reviewable.io -->

2021-11-03 12:48 UTC, petermattis commented
Minor comments remaining.

2021-11-03 12:56 UTC, petermattis commented on pkg/cmd/roachprod/main.go
> +	defaultMap := make(map[string]string)
I don't think this needs to be a separate variable. Simply pass in `make(map[string]string)` to the `StringToStringVar` invocation.

2021-11-03 12:56 UTC, petermattis commented on pkg/roachprod/vm/aws/aws.go
> +		fmt.Fprintf(&sb, "{Key=%s,Value=%s},", awsLabelMap[key], value)
If `key` is not present in `awsLabelMap`, then `awsLabelMap[key]` will return `""` which is probably not what you want. You need to do something like:

```
if n, ok := awsLabelMap[key]; ok {
    key = n
}
fmt.Fprintf(&sb, "{Key=%s,Value=%s},", key, value)
```

2021-11-03 12:56 UTC, petermattis commented on pkg/roachprod/vm/vm.go
> +	CustomLabelMap map[string]string
Nit: in the `VM` type the field is simply `Labels`. Here you're using a `Map` suffix which is inconsistent naming. I think this should be named `CustomLabels` for consistency.

2021-11-03 12:56 UTC, petermattis commented on pkg/roachprod/vm/azure/azure.go
> +	tagComment   = "comment"
The tags were sorted lexicographically before.

2021-11-03 12:56 UTC, petermattis commented on pkg/cmd/roachprod/main.go
> +			"Examples: usage=cloud-report-2021, namewithspaceinvalue='s o s'")
Will values with spaces actually work with the way these labels are getting passed to the cloud providers?

2021-11-12 03:10 UTC, xun-cockroachlabs reviewed
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-:-MoH6s8_9AgohNQgufF8:bb71pro)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @bobvawter, @miretskiy, @petermattis, and @ZhouXing19)

___
*[pkg/cmd/roachprod/main.go, line 1093 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MmzoIsMmweKZMsWIPgw-r4-1093:-MoFnpoA-0Sny7j9GzEF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e67d18cf07635dc523314496b981632f2cb0da/pkg/cmd/roachprod/main.go#L1093)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't think this needs to be a separate variable. Simply pass in `make(map[string]string)` to the `StringToStringVar` invocation.
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/main.go, line 1099 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MmzoIsMmweKZMsWIPgw-r4-1099:-MoFpouDBBdAhlFnYr_j:bawumvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e67d18cf07635dc523314496b981632f2cb0da/pkg/cmd/roachprod/main.go#L1099)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Will values with spaces actually work with the way these labels are getting passed to the cloud providers?
</blockquote></details>

It works for aws and azure, modified the usage message.
___
*[pkg/roachprod/vm/aws/aws.go, line 852 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MnYKUO7UfsEBzS-yvFc-r4-852:-MoFut1cBMWu3FvzTKCM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e67d18cf07635dc523314496b981632f2cb0da/pkg/roachprod/vm/aws/aws.go#L852)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If `key` is not present in `awsLabelMap`, then `awsLabelMap[key]` will return `""` which is probably not what you want. You need to do something like:

```
if n, ok := awsLabelMap[key]; ok {
    key = n
}
fmt.Fprintf(&sb, "{Key=%s,Value=%s},", key, value)
```
</blockquote></details>

Done.
___
*[pkg/roachprod/vm/azure/azure.go, line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MnYKUO7UfsEBzS-yvFd-r4-44:-MoFvrrb18EUQs-RTVVI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e67d18cf07635dc523314496b981632f2cb0da/pkg/roachprod/vm/azure/azure.go#L44)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The tags were sorted lexicographically before.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-15 14:33 UTC, petermattis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-:-MoZ06P03cpWkF2y8qyh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @bobvawter, @miretskiy, @xun-cockroachlabs, and @ZhouXing19)

___
*[pkg/cmd/roachprod/main.go, line 1099 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MmzoIsMmweKZMsWIPgw-r4-1099:-MoZ-rN_4J7Mse_0bZfY:b-6qlusb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e67d18cf07635dc523314496b981632f2cb0da/pkg/cmd/roachprod/main.go#L1099)):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

It works for aws and azure, modified the usage message.
</blockquote></details>

Thanks for checking. I'm super surprised that values containing whitespace work given how we're passing these labels on the command line. Is there actually a need for that functionality, or are you only noting it here for completeness?
___
*[pkg/roachprod/vm/aws/aws.go, line 839 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MoZ-iyl0-gP0XMhK6Hv:-MoZ-iyl0-gP0XMhK6Hw:b-mbbf8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/77b3c7c8b90bad55242ac931583f2e35a3feba22/pkg/roachprod/vm/aws/aws.go#L839)):*
> ```Go
> 		vm.TagLifetime:  "Lifetime",
> 		vm.TagRoachprod: "Roachprod",
> 		"Name":          "Name",
> ```

I think this line isn't necessary as you'll pass through keys as-is if they aren't present in `awsLabelsNameMap`.


<!-- Sent from Reviewable.io -->

2021-11-16 01:21 UTC, xun-cockroachlabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @bobvawter, @miretskiy, @petermattis, and @ZhouXing19)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MoaKDqj6pc06n3dNjl1:-MoaKDqj6pc06n3dNjl2:b-238g81) (no related file):*
Disabled flaky `TestChangefeedResolvedFrequency` test, PTAL.

---
___
*[pkg/cmd/roachprod/main.go, line 1099 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MmzoIsMmweKZMsWIPgw-r4-1099:-MoZOMYF4zRQYajHfmNk:b-s6hjuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3e67d18cf07635dc523314496b981632f2cb0da/pkg/cmd/roachprod/main.go#L1099)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Thanks for checking. I'm super surprised that values containing whitespace work given how we're passing these labels on the command line. Is there actually a need for that functionality, or are you only noting it here for completeness?
</blockquote></details>

Mostly for completeness, also there may be a future scenario we may want labels containing space for aws and azure.
___
*[pkg/roachprod/vm/aws/aws.go, line 839 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MoZ-iyl0-gP0XMhK6Hv:-MoZOp4d1piWtUvvPNof:b-s5juy) ([raw file](https://github.com/cockroachdb/cockroach/blob/77b3c7c8b90bad55242ac931583f2e35a3feba22/pkg/roachprod/vm/aws/aws.go#L839)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this line isn't necessary as you'll pass through keys as-is if they aren't present in `awsLabelsNameMap`.
</blockquote></details>

You are correct, thanks for pointing this out.


<!-- Sent from Reviewable.io -->

2021-11-16 17:01 UTC, xun-cockroachlabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @bobvawter, @miretskiy, @petermattis, and @ZhouXing19)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MoaKDqj6pc06n3dNjl1:-Modga681ax_Jxyyv5NM:b-ydi9ay) (no related file):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

Disabled flaky `TestChangefeedResolvedFrequency` test, PTAL.
</blockquote></details>

bors r+

---


<!-- Sent from Reviewable.io -->

2021-11-16 18:09 UTC, merged

2021-11-16 18:32 UTC, xun-cockroachlabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72014)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72014#-MoaKDqj6pc06n3dNjl1:-Moe0Avl2FqUZPZldV9-:b-m5ph5t) (no related file):*
<details><summary><i>Previously, xun-cockroachlabs wrote…</i></summary><blockquote>

bors r+
</blockquote></details>

It was auto merged.
TFTR!

---


<!-- Sent from Reviewable.io -->