cdc: add pubsub sink
cockroachdb/cockroach pull request #72056
Opened 2021-10-27 20:47 UTC by wongio123

changefeedccl: Pubsub Sink Integration
    
  Previously there was no changefeed sink for pubsub.
  This was inadequate because there are use cases for a pubsub sink when
  a Kafka sink is overkill and there are advantages with easier cloud
  compatibility. To address this I created a generic pubsub sink system
  that will allow for different pubsub sink integrations across different
  cloud providers to be easily implemented in the future. Currently GCP
  pubsub and in memory pubsub are implemented.
  
  Release note (enterprise change): Changefeeds now support gcp pubsub as a sink.

2021-10-27 21:38 UTC, miretskiy requested changes
Overall, I think it's a great start! Most of my comments are nits.  A slightly bigger ask is to implement
pubsub test feed -- just like we have testfeed implementations for all other sinks so that we can use "pubsub" testfeed implementations from changefeed_test.

I think this WIP PR can be converted to a real PR (perhaps merge/collapse some changes).  You definitely need to write real
descriptions, w/ `Release Notes`

Again, great job @wongio123 

> Reviewed 5 of 7 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-:-Mn2fghA35gcq0l3cegr:b3m8txy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @wongio123)

___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2_8sqDu2ihCgrJkCA:-Mn2_8sqDu2ihCgrJkCB:bfsnrgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L60)):*
> ```Go
> }
> 
> type GcpPubsubSink struct {
> ```

this probably doesn't need to be exported (since I think we construct Sink via getSink factory)
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 72 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2_DhGDR3cQbaMD30m:-Mn2_DhGDR3cQbaMD30n:bwtzh2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L72)):*
> ```Go
> }
> 
> type PubsubDesc interface {
> ```

nit:exported interfaces (and their methods need to be documented)
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 72 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2fKll-6voYmJeqtP-:-Mn2fKll-6voYmJeqtP0:b-yaxz4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L72)):*
> ```Go
> }
> 
> type PubsubDesc interface {
> ```

I'm also not sure what this interface supposed to accomplish.  Perhaps it needs a better name (and a comment.).
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 82 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2fPcX3Phf3fO1pdou:-Mn2fPcX3Phf3fO1pdov:b-rnsv7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L82)):*
> ```Go
> 	) error
> 	EmitResolvedTimestamp(ctx context.Context, encoder Encoder, resolved hlc.Timestamp) error
> 	Flush(ctx context.Context) error
> ```

FYI: If you're trying to say that "this interface also has methods from that interface", you can say that much more succinctly in go:
```
type PubsubDesc interface {
  Sink
  ...
}
```
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 106 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2_KSfBkBMwFMvQ8mk:-Mn2_KSfBkBMwFMvQ8ml:bc7m37g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L106)):*
> ```Go
> 	// errChan is written to indicate an error while sending message.
> 	errChan chan error
> ```

nit: extra \n
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 108 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2_Llv6exE0Xzkjhzg:-Mn2_Llv6exE0Xzkjhzh:bmil24q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L108)):*
> ```Go
> 
> }
> ```

I assume pubsubSink implements PubsubDesc?
If so, let's document this fact via

```
var _ PubsubDesc = (*pubsubSink)(nil)
```
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2aFxV1I7B8korOJOV:-Mn2aFxV1I7B8korOJOW:bq9rzf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L110)):*
> ```Go
> 
> //getGCPCredentials returns gcp credentials parsed out from url
> func getGCPCredentials(q *url.Values, ctx context.Context) (*google.Credentials, error){
> ```

if you use `sinkURL` as an argument to this method you get lots fo "goodies" s.a. base64 decoding support, etc.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2b-pR2iAtFeoQWG6O:-Mn2b-pR2iAtFeoQWG6P:bneghkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L146)):*
> ```Go
> //MakePubsubSink returns the corresponding pubsub sink based on the url given
> func MakePubsubSink(ctx context.Context, u *url.URL, opts map[string]string) (Sink, error) {
> ```

nit: extra \n?
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2dlEr0MU8EeHuoUxw:-Mn2dlEr0MU8EeHuoUxx:b-thp5ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L181)):*
> ```Go
> 		return g, nil
> 	case memScheme:
> 		m := &MemPubsubSink{pubsubDesc: p}
> ```

is MemPubsubSink only useful in tests? If so, perhaps this can be moved to test only code?
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 195 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2b4irCnRdgvugy130:-Mn2b4irCnRdgvugy131:b-9baqda) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L195)):*
> ```Go
> 
> //getUrl returns url
> func (p *pubsubSink)getUrl() *url.URL{
> ```

nit "\s" between receiver () and function name.  Same below.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 205 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2b9RG2eTohXnHi0Jl:-Mn2b9RG2eTohXnHi0Jm:b-nobtvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L205)):*
> ```Go
> 
> //EmitRow pushes a message to event channel where it is consumed by workers
> func (p *pubsubSink) 	EmitRow(
> ```

nit: extra \s between receiver and function name.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 294 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2cM9411F0fMGO7ASN:-Mn2cM957XEztewhDCVH:b-8jt096) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L294)):*
> ```Go
> 	})
> 	if err != nil {
> 		return errors.Wrapf(err, "sending message")
> ```

do we need to wrap here?
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 334 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2c_-tE_V4yXTRvTLw:-Mn2c_-tE_V4yXTRvTLx:b-seayk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L334)):*
> ```Go
> 			}
> 
> 			//inline func to trigger the defer alloc release when it loops
> ```

I don't think you need to worry about deferring release.
Just have straight code (json.marshal, sendMessage, etc).  Then just call msg.alloc.Release() at the end.
I understand that you worry "what happens if an error occurs and I don't release" -- the answer is, don't worry.
This memory still gets released, and if you get an error, you're shutting down/restarting changefeed anyway.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 420 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2buPh5OYVVNFhfi7v:-Mn2buPh5OYVVNFhfi7w:bnr5n3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L420)):*
> ```Go
> 	}
> 
> 	//TODO: implement options
> ```

can you be more specific? which options do you have in mind?
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 438 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2bmA3AXwxSJI3Hau6:-Mn2bmA3AX [...]

2021-11-01 14:23 UTC, wongio123 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @wongio123)

___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2_8sqDu2ihCgrJkCA:-MnOsOfmEcXEaOUZOiOx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L60)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

this probably doesn't need to be exported (since I think we construct Sink via getSink factory)
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 72 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2fKll-6voYmJeqtP-:-MnQr0435LgEi9aMH2P8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L72)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm also not sure what this interface supposed to accomplish.  Perhaps it needs a better name (and a comment.).
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 108 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2_Llv6exE0Xzkjhzg:-MnQrFwP06DLTIHE6b2i:b-vaas7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L108)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I assume pubsubSink implements PubsubDesc?
If so, let's document this fact via

```
var _ PubsubDesc = (*pubsubSink)(nil)
```
</blockquote></details>

I got rid of the pubsubDesc interface and instead included pubsubSink directly into the gcpPubsub and memPubsub structs. I realized there isn't really much of a point to have the inner pubsubSink implementation be an interface unless we needed it for testing or if we wanted to switch out the package we use. Since gcpPubsub and memPubsub act basically as wrappers calling the methods in pubsubSink it doesn't make too much sense for testing. I think the go cloud sdk is the only general use pubsub library available.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2aFxV1I7B8korOJOV:-MnQsCDR38iW9-LNVMnj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L110)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

if you use `sinkURL` as an argument to this method you get lots fo "goodies" s.a. base64 decoding support, etc.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 294 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2cM9411F0fMGO7ASN:-MnQs_Tv4SplytMqFTq5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L294)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we need to wrap here?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 334 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2c_-tE_V4yXTRvTLw:-MnQsaZkBSuLfZ1RoQhQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L334)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't think you need to worry about deferring release.
Just have straight code (json.marshal, sendMessage, etc).  Then just call msg.alloc.Release() at the end.
I understand that you worry "what happens if an error occurs and I don't release" -- the answer is, don't worry.
This memory still gets released, and if you get an error, you're shutting down/restarting changefeed anyway.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 420 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2buPh5OYVVNFhfi7v:-MnQsbjU56goFZvPHKt6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L420)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

can you be more specific? which options do you have in mind?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 438 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2bmA3AXwxSJI3Hau6:-MnQscfw-sS1ZUtw4FBz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L438)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

i would just return EmitRow w/out any wrapping.  The caller may decide to wrap the error if it wants to.
Ditto below.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-01 14:24 UTC, wongio123 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @wongio123)

___
*[pkg/ccl/changefeedccl/sink_pubsub_test.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2bRIM5WDvRfjtN5pF:-MnQshm84wl28Z_aXcXi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub_test.go#L213)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

extra test?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-02 20:15 UTC, HonoreDB reviewed
This is awesome @wongio123 , and thanks for jumping in with the detailed review @miretskiy!

> Reviewed 7 of 7 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-:-MnXHKMO6k4LaX2JEABz:b9y402o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @wongio123)

___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 142 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnXGJot0Puewpa1oXgi:-MnXGJou7Ds7E55gjy4A:b56umlu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6f18d12bd9708f7e7dfbe490d378866b4c181f1/pkg/ccl/changefeedccl/sink_pubsub.go#L142)):*
> ```Go
> 
> 	ctx, cancel := context.WithCancel(ctx)
> 	p := &pubsubSink{workerCtx: ctx, url: sinkURL{u, u.Query()}, numWorkers: 10, exitWorkers: cancel}
> ```

Comment explaining where 10 comes from? Or whether this will ultimately come from config or something dependent on the wrapping class or something.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnXH0l6Ce_hIA8DMoEY:-MnXH0l6Ce_hIA8DMoEZ:b-l3x6d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6f18d12bd9708f7e7dfbe490d378866b4c181f1/pkg/ccl/changefeedccl/sink_pubsub.go#L150)):*
> ```Go
> 		creds, err := getGCPCredentials(p.url, ctx)
> 		if err != nil {
> 			_ = p.close()
> ```

Just curious, what do these single-var assignments to `_` do?


<!-- Sent from Reviewable.io -->

2021-11-03 20:25 UTC, HonoreDB reviewed
> Reviewed 2 of 4 files at r5, 3 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @wongio123)

___
*[pkg/ccl/changefeedccl/testfeed_test.go, line 1522 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnbQhytBRrYCLf_RT7m:-MnbQhytBRrYCLf_RT7n:b-a1o4h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b8cf11b5c0cfe6bbbc02711e322f4a122b3acac/pkg/ccl/changefeedccl/testfeed_test.go#L1522)):*
> ```Go
> 		}
> 		msg := p.mockSink.Pop()
> 		if msg != "" {
> ```

You have this check again two lines down. Also it makes me nervous, do you know why sometimes there'd be blank messages?
___
*[pkg/ccl/changefeedccl/testfeed_test.go, line 1527 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnbR0yd0qxAnadLQig9:-MnbR0yd0qxAnadLQigA:b-a6vzaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b8cf11b5c0cfe6bbbc02711e322f4a122b3acac/pkg/ccl/changefeedccl/testfeed_test.go#L1527)):*
> ```Go
> 				var err error
> 				var resolved bool
> 				resolved, err = isResolvedTimestamp([]byte(msg))
> ```

Nit: Usual style here is to collapse these 3 lines into `resolved, err := isResolvedTimestamp([]byte(msg))`.
___
*[pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnbR_rSEC89V4i54UpG:-MnbR_rSEC89V4i54UpH:bq910nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b8cf11b5c0cfe6bbbc02711e322f4a122b3acac/pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go#L39)):*
> ```Go
> 
> func (p *MockPubsubSink) Dial() error{
> 	sub ,err := pubsub.OpenSubscription(p.ctx, p.url)
> ```

Nit: `p.sub, err := pubsub.OpenSubscription(p.ctx, p.url)`
___
*[pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go, line 48 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnbS8-90Y4b0riVdYWY:-MnbS8-90Y4b0riVdYWZ:b-hleg1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b8cf11b5c0cfe6bbbc02711e322f4a122b3acac/pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go#L48)):*
> ```Go
> }
> 
> func (p *MockPubsubSink) recieve() {
> ```

receive
___
*[pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go, line 59 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnbSYFfBNkcFnoA2Ptk:-MnbSYFfBNkcFnoA2Ptl:bk9qi1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b8cf11b5c0cfe6bbbc02711e322f4a122b3acac/pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go#L59)):*
> ```Go
> 			return
> 		default:
> 			if msgBody != "" {
> ```

Side-eying this check here too. As far as I know we shouldn't be sending any messages with empty bodies, so there should be at least one test that fails if we do. If this is an existing pattern for dealing with a poll loop with no messages, sorry.


<!-- Sent from Reviewable.io -->

2021-11-09 01:18 UTC, wongio123 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @stevendanna, and @wongio123)

___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnXH0l6Ce_hIA8DMoEY:-Mo1FGMF6TEEppW6zQu5:bjm87c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6f18d12bd9708f7e7dfbe490d378866b4c181f1/pkg/ccl/changefeedccl/sink_pubsub.go#L150)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Just curious, what do these single-var assignments to `_` do?
</blockquote></details>

the _ is there so I don't get an unhandled error warning. We don't really care about the error since we are closing. I can log it out instead.
___
*[pkg/ccl/changefeedccl/sink_pubsub_test.go, line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2bYTQ9KDwOEKOQ4kI:-Mo1F_NvDlc5mHMIAoH9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub_test.go#L2)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we probably should implement pubsub testfeed implementation so that we can hook up pubsub sink to the changefeed_test tests.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub_test.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2f4KR0R-r_8ILpkZC:-Mo1Fa2ZEJsRBUlyBjqG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub_test.go#L130)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

you should definitely look into testfeed implementations. 
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/testfeed_test.go, line 1522 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnbQhytBRrYCLf_RT7m:-Mo1Fjqa6kCZ162AMi-W:b-iifhob) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b8cf11b5c0cfe6bbbc02711e322f4a122b3acac/pkg/ccl/changefeedccl/testfeed_test.go#L1522)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

You have this check again two lines down. Also it makes me nervous, do you know why sometimes there'd be blank messages?
</blockquote></details>

got rid of the extra check and made it so that pop returns a pointer so we can check for nil instead of ""
___
*[pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnbR_rSEC89V4i54UpG:-Mo1G32-A7RDyHpBV3G8:bvksmuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b8cf11b5c0cfe6bbbc02711e322f4a122b3acac/pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go#L39)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Nit: `p.sub, err := pubsub.OpenSubscription(p.ctx, p.url)`
</blockquote></details>

I figured this would prevent p.sub from accidentally being assigned junk. But I guess it doesn't matter since we are returning an error anyway
___
*[pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go, line 48 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnbS8-90Y4b0riVdYWY:-Mo1GE6o3N3MAFelxS4x:b-jkuxn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b8cf11b5c0cfe6bbbc02711e322f4a122b3acac/pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go#L48)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

receive
</blockquote></details>

should have never turned off goland spell check
___
*[pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go, line 59 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnbSYFfBNkcFnoA2Ptk:-Mo1Gd25CWaPD5tzXup8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b8cf11b5c0cfe6bbbc02711e322f4a122b3acac/pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go#L59)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Side-eying this check here too. As far as I know we shouldn't be sending any messages with empty bodies, so there should be at least one test that fails if we do. If this is an existing pattern for dealing with a poll loop with no messages, sorry.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-09 01:22 UTC, wongio123 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @stevendanna)

___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2dlEr0MU8EeHuoUxw:-Mo1HSb9-dt5ubjg8FCP:b-84847m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L181)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

is MemPubsubSink only useful in tests? If so, perhaps this can be moved to test only code?
</blockquote></details>

Moved
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 142 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnXGJot0Puewpa1oXgi:-Mo1HM344yhNeBGboUA6:b-ehjpxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6f18d12bd9708f7e7dfbe490d378866b4c181f1/pkg/ccl/changefeedccl/sink_pubsub.go#L142)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Comment explaining where 10 comes from? Or whether this will ultimately come from config or something dependent on the wrapping class or something.
</blockquote></details>

Yup this will come from some sort of config. I will add a comment


<!-- Sent from Reviewable.io -->

2021-11-09 08:02 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @wongio123)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2hvx_9Fk6CDVaXfZQ:-Mo2hvx_9Fk6CDVaXfZR:b-10h442) (no related file):*
Nice to see this moving forward. I've given it one read through but haven't left many comments.  I'll try to read through it again this week and comment more extensively.

---
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 126 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2cCf10ZWbsbmw4MrP:-Mo2cCf10ZWbsbmw4MrQ:b-neead8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/changefeed_test.go#L126)):*
> ```Go
> 	//t.Run(`cloudstorage`, cloudStorageTest(testFn))
> 	//t.Run(`kafka`, kafkaTest(testFn))
> 	//t.Run(`webhook`, webhookTest(testFn))
> ```

reminder to uncomment these before merge.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1159 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2hFKB5H4jd8hrU2c4:-Mo2hCs-56fr18QN2fjI:bxhlxrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/changefeed_test.go#L1159)):*
> ```Go
> 	t.Run(`webhook`, webhookTest(testFn, feedTestNoTenants))
> 	//t.Run(`pubsub`, pubsubTest(testFn, feedTestNoTenants))
> 	//failing on payloads violate CDC per-key ordering guarantees for multiple altars
> ```

Do you have more details here? Do we think this is a consequence of the mem pub sub implementation not providing ordering or something on our side?
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 36 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2cfwLByFYRa_KSrJ1:-Mo2cfwLByFYRa_KSrJ2:b-3znnud) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/sink_pubsub.go#L36)):*
> ```Go
> )
> 
> //isPubsubSInk returns true if url contains scheme with valid pubsub sink
> ```

[nit] here and in other places, we typically put a space after `//`
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 310 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2ef2E2yZMTRLKN4A4:-Mo2ef2E2yZMTRLKN4A5:bimqz9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/sink_pubsub.go#L310)):*
> ```Go
> 			if msg.isFlush {
> 				// Signals a flush request, makes sure that the messages in eventsChans are finished sending
> 				continue
> ```

Do we need to do more here? I'm wondering if we need to call any methods on the underlying Topic to ensure that anything the library might be buffering is sent.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 377 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2f1AU8L3hU1mtwLOe:-Mo2f1AU8L3hU1mtwLOf:b-12l1t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/sink_pubsub.go#L377)):*
> ```Go
> 	conn, cleanup, err := gcppubsub.Dial(p.pubsubSink.getWorkerCtx(), p.creds.TokenSource)
> 	if err != nil {
> 		return errors.Wrapf(err, "establishing gcp connection")
> ```

[nit] We can use Wrap rather than Wrapf here and in a few other places where were we don't need format arguments


<!-- Sent from Reviewable.io -->

2021-11-12 06:49 UTC, wongio123 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @stevendanna, and @wongio123)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 126 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2cCf10ZWbsbmw4MrP:-MoHsn1J2CRbwitn81Ig:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/changefeed_test.go#L126)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

reminder to uncomment these before merge.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1159 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2hFKB5H4jd8hrU2c4:-MoHswrT1hNN3bjgpCzU:b-5blzgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/changefeed_test.go#L1159)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do you have more details here? Do we think this is a consequence of the mem pub sub implementation not providing ordering or something on our side?
</blockquote></details>

So the mempubsub im using for testing purposes which is an in memory pubsub doesn't not have any ordering guarantees. In the future I could possibly make a pr to the go cloud cdk to include that option or maybe just implement my own mock sink without using the mempubsub.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 36 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2cfwLByFYRa_KSrJ1:-MoHtuSF9ifR_Z5szJ9K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/sink_pubsub.go#L36)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] here and in other places, we typically put a space after `//`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 07:02 UTC, wongio123 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @stevendanna, and @wongio123)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2hvx_9Fk6CDVaXfZQ:-MoHwxBsELe4BMGUYbCU:bzh25e2) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Nice to see this moving forward. I've given it one read through but haven't left many comments.  I'll try to read through it again this week and comment more extensively.
</blockquote></details>

Thank you for reviewing!

---
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 310 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2ef2E2yZMTRLKN4A4:-MoHuKkD2aSNI0OpWZln:b-o8rc5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/sink_pubsub.go#L310)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do we need to do more here? I'm wondering if we need to call any methods on the underlying Topic to ensure that anything the library might be buffering is sent.
</blockquote></details>

I don't think so because the workers process messages one by one and flush will block until every worker is able to grab the flush message off of their respective channel and then signal the sink that flush is done. The flush message will not be read from the channel until the prior message is sent since workers handle the messages synchronously according to their respective workerIndex. The send function will only return once the message has been sent according to the docs. https://github.com/google/go-cloud/blob/v0.24.0/pubsub/pubsub.go#L233-L235

In the future when I implement batching I will need to account for that though.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 377 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2f1AU8L3hU1mtwLOe:-MoHwvrsDWXcYKACY6XH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/sink_pubsub.go#L377)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] We can use Wrap rather than Wrapf here and in a few other places where were we don't need format arguments
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 07:09 UTC, wongio123 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @stevendanna, and @wongio123)

___
*[pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnbR_rSEC89V4i54UpG:-MoHxf0p-m9Mc49uB-Fm:baaj8rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b8cf11b5c0cfe6bbbc02711e322f4a122b3acac/pkg/ccl/changefeedccl/cdctest/mock_pubsub_sink.go#L39)):*
<details><summary><i>Previously, wongio123 wrote…</i></summary><blockquote>

I figured this would prevent p.sub from accidentally being assigned junk. But I guess it doesn't matter since we are returning an error anyway
</blockquote></details>

I tried doing it with the := and it actually does not work. I think it has something to do with assigning to a member in the mockpubsubsink object.


<!-- Sent from Reviewable.io -->

2021-12-08 19:17 UTC, HonoreDB approved these changes
> Reviewed 7 of 19 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @stevendanna, and @wongio123)

___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 185 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqQQm0G8h8YNUfIynuC:-MqQQm0G8h8YNUfIynuD:bi6e2gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f9b9147b7d4c723ceb6198d763bd5eb88ff27c/pkg/ccl/changefeedccl/sink_pubsub.go#L185)):*
> ```Go
> 	}
> 	//creates a topic for each target
> 	for id, topic := range targets {
> ```

Variable name here should be target, not topic. Also, nonblocking but it could be more efficient here to only create one topic in the case where pubsubTopicName is set, rather than a bunch of duplicate topic objects, and then have a `topicForId(id)` method that uses the `withTopicName` flag.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 534 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqQQB3W30mXxY_KwNU9:-MqQQB3W30mXxY_KwNUA:bpvm6cm) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f9b9147b7d4c723ceb6198d763bd5eb88ff27c/pkg/ccl/changefeedccl/sink_pubsub.go#L534)):*
> ```Go
> // Dial opens topic using url
> func (p *memPubsubSink) Dial() error {
> 	//topic, err := pubsub.OpenTopic(p.pubsubSink.getWorkerCtx(), p.pubsubSink.url.String())
> ```

Remove commented code


<!-- Sent from Reviewable.io -->

2021-12-08 23:56 UTC, miretskiy commented
Can you update this pull requests descr?

2021-12-09 17:15 UTC, wongio123 reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-:-MqVAmUUCYPssrUR_Yxj:bb6un1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @stevendanna, and @wongio123)

___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 185 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqQQm0G8h8YNUfIynuC:-MqR1alD9XX4lvNRpTq6:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f9b9147b7d4c723ceb6198d763bd5eb88ff27c/pkg/ccl/changefeedccl/sink_pubsub.go#L185)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Variable name here should be target, not topic. Also, nonblocking but it could be more efficient here to only create one topic in the case where pubsubTopicName is set, rather than a bunch of duplicate topic objects, and then have a `topicForId(id)` method that uses the `withTopicName` flag.
</blockquote></details>

Done
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 534 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqQQB3W30mXxY_KwNU9:-MqVAicDEy5GWxPiKR58:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f9b9147b7d4c723ceb6198d763bd5eb88ff27c/pkg/ccl/changefeedccl/sink_pubsub.go#L534)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-13 14:26 UTC, miretskiy commented
@wongio123 Would it be possible to squash some of the commits in the stack?

2021-12-13 17:58 UTC, miretskiy requested changes
> Reviewed 3 of 19 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @stevendanna, and @wongio123)

___
*[pkg/ccl/changefeedccl/sink.go, line 115 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoRA547C2zusRb8x_2:-MqoRA547C2zusRb8x_3:b-8n8m18) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink.go#L115)):*
> ```Go
> 			return validateOptionsAndMakeSink(changefeedbase.PubsubValidOptions, func() (Sink, error) {
> 				return MakePubsubSink(ctx, u, feedCfg.Opts, feedCfg.Targets)
> 			})
> ```

add a TODO to add metrics to this sink.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 108 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2_Llv6exE0Xzkjhzg:-MnRCBfJAyOuJzgz6jeq:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L108)):*
<details><summary><i>Previously, wongio123 wrote…</i></summary><blockquote>

I got rid of the pubsubDesc interface and instead included pubsubSink directly into the gcpPubsub and memPubsub structs. I realized there isn't really much of a point to have the inner pubsubSink implementation be an interface unless we needed it for testing or if we wanted to switch out the package we use. Since gcpPubsub and memPubsub act basically as wrappers calling the methods in pubsubSink it doesn't make too much sense for testing. I think the go cloud sdk is the only general use pubsub library available.
</blockquote></details>

Nice.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2dlEr0MU8EeHuoUxw:-MqoUHHG4Jlp52g-jzVD:bvh83us) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L181)):*
<details><summary><i>Previously, wongio123 wrote…</i></summary><blockquote>

Moved
</blockquote></details>

I would love not to have any test related code inside production code.   Because you reference mempubsub, it does get compiled in...
It appears that mem sink is used only from unit tests.  Currently, it is not used in the cdc roachtest since you connect to the real
pubsub.  So, I think it's possible to restrict mem sink to be available in unit test only.

Add a factory for pubsub sink.

```
var makePubsubSink = func(p *pubsubSink) (Sink, error) {
		creds, err := getGCPCredentials(ctx, p.url)
		if err != nil {
			_ = p.close()
			return nil, err
		}
		return &gcpPubsubSink{creds: creds, pubsubSink: p}, nil
}
```
So, by default makePubsubSink just moves the code inside gcpScheme to a named function...
So, just invoke that function in the branch above.
The memScheme branch goes away, and so does the "mem" scheme.

memPubsubSink needs to be moved to `sink_pubsub_test.go` -- this will be compiled only when compiling the tests.
Inside that file, add:
```
func init() {
   makePubsubSink = func(p *pubsubSink) (Sink, error) {
      return &memPubsubsink...
   }
}
```
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 45 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoTDtM2EeBmbLiyvs2:-MqoTDtM2EeBmbLiyvs3:b2c4xhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L45)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> const credentialsParam = "CREDENTIALS"
> const authParam = "AUTH"
> const authSpecified = "specified"
> const authImplicit = "implicit"
> const authDefault = "default"
> ```
</details>


let's move these authentication related constants inside getCreds function.
We will probably have to remove those constants when we refactor the code anyway (see the comment on get credentials function)
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 46 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoQg8sBW9OFNkoifB5:-MqoQg8sBW9OFNkoifB6:b1vh18i) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L46)):*
> ```Go
> const authImplicit = "implicit"
> const authDefault = "default"
> const gcpScheme = "gcppubsub"
> ```

@amruss are we okay w/ this name? 
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 49 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoBOon4ggV_nOy6CpG:-MqoBOon4ggV_nOy6CpH:b-jryqqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L49)):*
> ```Go
> const memScheme = "mem"
> const gcpScope = "https://www.googleapis.com/auth/pubsub"
> const numOfWorkers = 128
> ```

This number seems to be  rather arbitrary (and maybe even too high)...
Perhaps this should be configurable? 
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 74 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoBbAd2FLakl56iYsU:-MqoBbAd2FLakl56iYsV:b9m3z3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L74)):*
> ```Go
> 	isFlush bool
> 	topicID descpb.ID
> 	logIt   func()
> ```

This looks to be debug logging left over.  Probably should be removed.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 80 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mqoj_0KENVJ10N6Q7ty:-Mqoj_0KENVJ10N6Q7tz:b-vb9hiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L80)):*
> ```Go
> 	client     *gcpClient.PublisherClient
> 	cleanup    func()
> 	pubsubSink *pubsubSink
> ```

The code structure seems a bit backward to me.  pubsubSink seems to be the "main" that emits messages downstream -- to gcp pubsub.
Yet, the code is structured  where gcpPubsubSink contains pubsubSink...
Perhaps i'm misunderstanding something.

If the problem was that you are trying to use mem vs real sink, then just introducing an interface that abstracts the operations you need
(e.g. Send, Close, etc) would accomplish this.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 123 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoSdo-D3ZIunmC2Kl2:-MqoSdo-D3ZIunmC2Kl3:bz4helo) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L123)):*
> ```Go
> 	authOption := u.consumeParam(authParam)
> 
> 	// implemented according to https://github.com/cockroachdb/cockroach/pull/64737
> ```

I think we need to refactor  some code so that we can use the shared gcs configuration/cred parsing logic.
In particular, I'm concerned about the fact that by copying this code we are not respecting `--external-io-implicit-credentials`
command line flag -- and we really should.

I'm okay w/ slapping a big TODO on this function, but that's just something that needs to be addressed before pubsub can be released.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 157 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoTilh-on2-0cXgNjP:-MqoTilh-on2-0cXgNjQ:bneghkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L157)):*
> ```Go
> 	ctx context.Context, u *url.URL, opts map[string]string, targets jobspb.ChangefeedTargets,
> ) (Sink, error) {
> ```

nit: extra \n?
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 158 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoTn4y38QWGgSo5-db:-MqoTn4z5oWmP3nsynFY:bqor4k8) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L158)):*
> ```Go
> ) (Sink, error) {
> 
> 	pubsubURL := sinkURL{u, u.Query( [...]

2021-12-15 14:21 UTC, miretskiy requested changes
> Reviewed 3 of 19 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @stevendanna, and @wongio123)



<!-- Sent from Reviewable.io -->

2021-12-21 20:26 UTC, wongio123 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @stevendanna, and @wongio123)

___
*[pkg/ccl/changefeedccl/sink.go, line 115 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoRA547C2zusRb8x_2:-MrTeeaaCPoA7H1AoT8a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink.go#L115)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

add a TODO to add metrics to this sink.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 108 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2_Llv6exE0Xzkjhzg:-MrTemEj8pLgXGS5iR9A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L108)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Nice.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2dlEr0MU8EeHuoUxw:-MrTdIoH4gW6e8Usp7Ns:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d99e26de618e4f02e47d0a99c67598276d996482/pkg/ccl/changefeedccl/sink_pubsub.go#L181)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would love not to have any test related code inside production code.   Because you reference mempubsub, it does get compiled in...
It appears that mem sink is used only from unit tests.  Currently, it is not used in the cdc roachtest since you connect to the real
pubsub.  So, I think it's possible to restrict mem sink to be available in unit test only.

Add a factory for pubsub sink.

```
var makePubsubSink = func(p *pubsubSink) (Sink, error) {
		creds, err := getGCPCredentials(ctx, p.url)
		if err != nil {
			_ = p.close()
			return nil, err
		}
		return &gcpPubsubSink{creds: creds, pubsubSink: p}, nil
}
```
So, by default makePubsubSink just moves the code inside gcpScheme to a named function...
So, just invoke that function in the branch above.
The memScheme branch goes away, and so does the "mem" scheme.

memPubsubSink needs to be moved to `sink_pubsub_test.go` -- this will be compiled only when compiling the tests.
Inside that file, add:
```
func init() {
   makePubsubSink = func(p *pubsubSink) (Sink, error) {
      return &memPubsubsink...
   }
}
```

</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 45 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoTDtM2EeBmbLiyvs2:-MrTegHKBHV0RJfzVWtr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L45)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> const credentialsParam = "CREDENTIALS"
> const authParam = "AUTH"
> const authSpecified = "specified"
> const authImplicit = "implicit"
> const authDefault = "default"
> ```

let's move these authentication related constants inside getCreds function.
We will probably have to remove those constants when we refactor the code anyway (see the comment on get credentials function)
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 49 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoBOon4ggV_nOy6CpG:-MrTejOV7Mk309E9oN8W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L49)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This number seems to be  rather arbitrary (and maybe even too high)...
Perhaps this should be configurable? 
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 74 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoBbAd2FLakl56iYsU:-MrTekkP-dyrVS5WgrtC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L74)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This looks to be debug logging left over.  Probably should be removed.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 80 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mqoj_0KENVJ10N6Q7ty:-MrTcatPAtzGLIEcOlLC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L80)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

The code structure seems a bit backward to me.  pubsubSink seems to be the "main" that emits messages downstream -- to gcp pubsub.
Yet, the code is structured  where gcpPubsubSink contains pubsubSink...
Perhaps i'm misunderstanding something.

If the problem was that you are trying to use mem vs real sink, then just introducing an interface that abstracts the operations you need
(e.g. Send, Close, etc) would accomplish this.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 123 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoSdo-D3ZIunmC2Kl2:-MrTcnmc9O8df3RicNDi:b-4fnix) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L123)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think we need to refactor  some code so that we can use the shared gcs configuration/cred parsing logic.
In particular, I'm concerned about the fact that by copying this code we are not respecting `--external-io-implicit-credentials`
command line flag -- and we really should.

I'm okay w/ slapping a big TODO on this function, but that's just something that needs to be addressed before pubsub can be released.
</blockquote></details>

what is --external-io-implicit-credentials?
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 158 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoTn4y38QWGgSo5-db:-MrTd54D1Nhn33ARw6-z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L158)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

let's use named parameters.  Pretty sure we have linters to complain about that.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 221 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoYFve8Aze2Wbwb8cM:-MrTdM1s4HiMalc7B_w_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L221)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why not just access workerCtx directly?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 224 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoXxcoDsEZSEqbg69o:-MrTdMyUD6k5dq3UduMY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L224)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

probably needs to be removed.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 297 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mqotsu2CJuK0USJPnca:-MrTdizS79JflqI-OXgu:b-397bgz) ([raw file](https://github.com/cockroachdb/cockr [...]

2021-12-21 21:04 UTC, HonoreDB requested changes
> Reviewed 2 of 19 files at r9, 19 of 23 files at r18, 7 of 7 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @stevendanna, and @wongio123)

___
*[node_modules/.yarn-integrity, line 2 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MrTjVA30nQB811dNAUo:-MrTjVA48h7WKl9uIxhD:btq3hmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/node_modules/.yarn-integrity#L2)):*
> ```
> {
>   "systemParams": "darwin-x64-102",
> ```

This file probably shouldn't be checked in.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 424 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MrTkk525ebQ4NmUQjZo:-MrTkk525ebQ4NmUQjZp:bazenxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L424)):*
> ```Go
> 		client, err = pubsub.NewClient(p.ctx, p.projectID, option.WithCredentials(creds), option.WithEndpoint(p.region))
> 	} else {
> 		client, err = pubsub.NewClient(p.ctx, p.projectID, option.WithCredentials(creds), option.WithEndpoint(p.region))
> ```

This else is identical to the if, should be changed or removed. Possibly we should fail for now if region is not provided since we can't guarantee ordering.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 455 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MrTlW0e2bTC09oEc3br:-MrTlW0e2bTC09oEc3bs:b-msjn46) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L455)):*
> ```Go
> func (p *gcpPubsubClient) openTopic(topicName string) (*pubsub.Topic, error) {
> 	t := p.client.Topic(topicName)
> 	topicExist, err := t.Exists(p.ctx)
> ```

Can this be made "optimistic"? Try to create the topic, and then if it already exists tolerate the error? As is this is potentially a race condition if the topic gets created (by another changefeed, say) in between Exists and CreateTopic.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 470 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MrTmHYT7FwvgLupkYrP:-MrTmHYT7FwvgLupkYrQ:bnyvtjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L470)):*
> ```Go
> 
> func (p *gcpPubsubClient) closeTopics(withTopicName string) {
> 	for _, topicStruct := range p.topics {
> ```

Nonblocking, but I'd still rather we had a `p.allTopics()` method (or even `p.forEachTopic( function (t topic))` if you want to get fancy) so that we wouldn't need to check `withTopicName` in so many places. 
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 176 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MrTn4zUBwHwyr84Jyg-:-MrTn4zUBwHwyr84Jyg0:b-gjktga) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/sqlproxyccl/proxy_handler.go#L176)):*
> ```Go
> 
> 	if handler.DirectoryAddr != "" {
> 		//lint:ignore SA1019 grpc.WithInsecure is deprecated
> ```

Do we have an issue for this?
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1159 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2hFKB5H4jd8hrU2c4:-MrTnUd3-wZEcMlrPt5I:b-89duv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/changefeed_test.go#L1159)):*
<details><summary><i>Previously, wongio123 wrote…</i></summary><blockquote>

So the mempubsub im using for testing purposes which is an in memory pubsub doesn't not have any ordering guarantees. In the future I could possibly make a pr to the go cloud cdk to include that option or maybe just implement my own mock sink without using the mempubsub.
</blockquote></details>

Comment can be removed now as you've done the thing.


<!-- Sent from Reviewable.io -->

2021-12-21 21:25 UTC, miretskiy requested changes

2021-12-21 21:59 UTC, miretskiy commented on pkg/ccl/changefeedccl/testfeed_test.go
> +	client := &fakePubsubClient{buffer: &mockPubsubMessageBuffer{rows: make([]mockPubsubMessage, 0)}}
nit: a bit more wrapping?

2021-12-21 21:59 UTC, miretskiy commented on pkg/ccl/changefeedccl/sink_pubsub.go
> +//  i dont really like having getTopicName in the interface but fullname test requires it
Let's drop this comment.

2021-12-21 21:59 UTC, miretskiy commented on pkg/ccl/changefeedccl/sink_pubsub.go
> +		return false
nit: perhaps just `return u.Scheme == gcpScheme`

2021-12-21 21:59 UTC, miretskiy commented on pkg/ccl/changefeedccl/sink_pubsub.go
> +//}
drop these comments?

2021-12-21 21:59 UTC, miretskiy commented on pkg/ccl/changefeedccl/sink_pubsub.go
> +// getGCPCredentials returns gcp credentials parsed out from url
nit: Let's add a TODO to unify this code with basically whatever cloudstorage is doing wrt to GCP credentials parsing.

2021-12-21 21:59 UTC, miretskiy commented on pkg/ccl/changefeedccl/sink_pubsub.go
> +		workerCtx: ctx, numWorkers: numOfWorkers,
let's keep each field on a separate line?

2021-12-21 21:59 UTC, miretskiy commented on pkg/ccl/changefeedccl/sink_pubsub.go
> +		g := &gcpPubsubClient{topics: p.getTopicsMap(targets, pubsubTopicName),
nit: let's wrap struct fields?

2021-12-21 21:59 UTC, miretskiy commented on pkg/ccl/changefeedccl/sink_pubsub.go
> +		_ = p.Close()
Why do we have to do it? Is it to avoid leaking cancel?  Perhaps we can do that in the Dial instead?

2021-12-21 21:59 UTC, miretskiy commented on pkg/ccl/changefeedccl/sink_pubsub.go
> +		client, err = pubsub.NewClient(p.ctx, p.projectID, option.WithCredentials(creds), option.WithEndpoint(p.region))
nit: formatting?

2021-12-21 21:59 UTC, miretskiy commented on pkg/ccl/changefeedccl/sink_pubsub.go
> +		client, err = pubsub.NewClient(p.ctx, p.projectID, option.WithCredentials(creds), option.WithEndpoint(p.region))
I don't see the difference with the above branch.  Seems like we still use WithEndpoint option even if region is empty?

2021-12-22 23:23 UTC, wongio123 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss, @HonoreDB, @miretskiy, and @stevendanna)

___
*[node_modules/.yarn-integrity, line 2 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MrTjVA30nQB811dNAUo:-MrYxryp9Yv5dhLwHftB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/node_modules/.yarn-integrity#L2)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

This file probably shouldn't be checked in.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 46 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MqoQg8sBW9OFNkoifB5:-MrYQ-do6adqi5uyrj9d:bz9w57u) ([raw file](https://github.com/cockroachdb/cockroach/blob/369af4abf0182b0364faf98378f79d412ee0e477/pkg/ccl/changefeedccl/sink_pubsub.go#L46)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

@amruss are we okay w/ this name? 
</blockquote></details>

Changed it to gcpubsub after talking w Abbey about it
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 42 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2VV9afdTCJiQ7HAT--r19-42:-MrYRy_03qqyaAhRS4UK:bbq4m5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L42)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: perhaps just `return u.Scheme == gcpScheme`
</blockquote></details>

Done i thought the switch version would be more expandable when adding more vendors
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 46 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2VV9afdTCJiQ7HAT--r19-46:-MrYS3xZ2_nnEQ7qDB_C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L46)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Let's drop this comment.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 108 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2VV9afdTCJiQ7HAT--r19-108:-MrYS9shEICOwaGn8fU3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L108)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

drop these comments?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 171 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2VV9afdTCJiQ7HAT--r19-171:-MrYSV335p7r5Cw9ND1x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L171)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

let's keep each field on a separate line?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 186 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2VV9afdTCJiQ7HAT--r19-186:-MrYTWG308yjibZunEt4:b-4a5wlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L186)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Why do we have to do it? Is it to avoid leaking cancel?  Perhaps we can do that in the Dial instead?
</blockquote></details>

no longer need it, I removed it. I previously had the workers setup in MakePubsubSink so i would have to clean up the workers if i exited. Now i moved the worker setup to Dial so its no longer necessary.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 424 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mn2VV9afdTCJiQ7HAT--r19-424:-MrYUVRsBDg2fjzwuKoy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L424)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't see the difference with the above branch.  Seems like we still use WithEndpoint option even if region is empty?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 424 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MrTkk525ebQ4NmUQjZo:-MrYUWXN6QVCVfD35DVW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L424)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

This else is identical to the if, should be changed or removed. Possibly we should fail for now if region is not provided since we can't guarantee ordering.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 455 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MrTlW0e2bTC09oEc3br:-MrYvys0CmwFyxKYQJJJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L455)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Can this be made "optimistic"? Try to create the topic, and then if it already exists tolerate the error? As is this is potentially a race condition if the topic gets created (by another changefeed, say) in between Exists and CreateTopic.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/sink_pubsub.go, line 470 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MrTmHYT7FwvgLupkYrP:-MrZS0pX6yY8fPJNHWpz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/sink_pubsub.go#L470)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Nonblocking, but I'd still rather we had a `p.allTopics()` method (or even `p.forEachTopic( function (t topic))` if you want to get fancy) so that we wouldn't need to check `withTopicName` in so many places. 
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/proxy_handler.go, line 176 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MrTn4zUBwHwyr84Jyg-:-MrZS4pD9IQxAmqKLiA-:b4sb0a1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/sqlproxyccl/proxy_handler.go#L176)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Do we have an issue for this?
</blockquote></details>

Ill make one once it gets merged
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1159 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-Mo2hFKB5H4jd8hrU2c4:-MrYwOdB6aL83OiOv4WU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6ffda58df6f3d06952c1ddeeb3360c2e5d5b2c0/pkg/ccl/changefeedccl/changefeed_test.go#L1159)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Comment can be removed now as you've done the thing.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1400 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/72056#-MnaCqOdgHM9lPEzLsvE-r19-1400:-MrYwPOl4FWClzeH4TQQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a44192902f3006012279dfc52a5ce431f5bfe74e/pkg/ccl/changefeedccl/changefeed_test.go#L1400)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

altars?
nit: space after //
</blockquote></details>

Done.
___
*[pkg/util/grpcutil/grpc_util_test.go, line 74 at r19](https://reviewab [...]

2021-12-23 15:32 UTC, HonoreDB approved these changes
> Reviewed 15 of 15 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss, @HonoreDB, @miretskiy, and @stevendanna)



<!-- Sent from Reviewable.io -->

2021-12-23 18:09 UTC, wongio123 commented
bors r+

2021-12-23 19:08 UTC, merged