sql: textual explain analyze now shows max mem/disk stats
cockroachdb/cockroach pull request #72113
Opened 2021-10-28 18:25 UTC by Azhng

Resolves #66109

Release note (sql change): explain analyze now shows maximum
allocated memory and maximum sql temp disk usage for a statement.

Example: 

```
EXPLAIN ANALYZE SELECT c.a FROM c INNER MERGE JOIN d ON c.a = d.b
----
planning time: 10µs
execution time: 100µs
distribution: <hidden>
vectorized: <hidden>
rows read from KV: 4 (32 B)
maximum memory usage: <hidden>
network usage: <hidden>
regions: <hidden>
·
• merge join
│ nodes: <hidden>
│ regions: <hidden>
│ actual row count: 2
│ estimated max memory allocated: 0 B
│ estimated max sql temp disk usage: 0 B
│ equality: (a) = (b)
│
├── • sort
│   │ nodes: <hidden>
│   │ regions: <hidden>
│   │ actual row count: 2
│   │ estimated max memory allocated: 0 B
│   │ estimated max sql temp disk usage: 0 B
│   │ estimated row count: 1
│   │ order: +a
│   │
│   └── • scan
│         nodes: <hidden>
│         regions: <hidden>
│         actual row count: 2
│         KV time: 0µs
│         KV contention time: 0µs
│         KV rows read: 2
│         KV bytes read: 16 B
│         estimated max memory allocated: 0 B
│         estimated row count: 1 (100% of the table; stats collected <hidden> ago)
│         table: c@sec
│         spans: FULL SCAN
│
└── • scan
      nodes: <hidden>
      regions: <hidden>
      actual row count: 2
      KV time: 0µs
      KV contention time: 0µs
      KV rows read: 2
      KV bytes read: 16 B
      estimated max memory allocated: 0 B
      missing stats
      table: d@d_pkey
      spans: FULL SCAN
```

2021-11-01 13:21 UTC, mgartner requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72113)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/opt/exec/explain/emit.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72113#-MnQdjujDlilr0FrCDAc:-MnQdjujDlilr0FrCDAd:bf75h8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab1c4bb9e0e588962824ec9039da380c31ba982/pkg/sql/opt/exec/explain/emit.go#L380)):*
> ```Go
> 		}
> 		if s.MaxAllocatedMem.HasValue() {
> 			e.ob.AddField("max memory allocated", humanize.IBytes(s.MaxAllocatedMem.Value()))
> ```

`MaxAllocatedMem` and `MaxAllocatedDisk`come from memory monitors, so they are an estimate of bytes usage. I think the output should make it clear that these are estimates.


<!-- Sent from Reviewable.io -->

2021-11-01 14:49 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72113)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/exec/explain/emit.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72113#-MnQdjujDlilr0FrCDAc:-MnQyHyI-IxCxMLxy3js:b-po4uj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab1c4bb9e0e588962824ec9039da380c31ba982/pkg/sql/opt/exec/explain/emit.go#L380)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`MaxAllocatedMem` and `MaxAllocatedDisk`come from memory monitors, so they are an estimate of bytes usage. I think the output should make it clear that these are estimates.
</blockquote></details>

Updated to `estimated {max memory, max sql temp disk} allocated` 


<!-- Sent from Reviewable.io -->

2021-11-02 14:02 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  (as long as tests are passing :smile:  ) 

> Reviewed 2 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72113#-:-MnVxC_UEgVkrI7mNuIh:b-iea2ig)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2021-11-02 14:30 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72113#-:-MnW2jH72NI71UGrY9a7:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2021-11-03 14:59 UTC, Azhng commented
@mgartner RFAL

2021-11-04 14:25 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72113#-:-MnfKrmpBe6oiUcVEZ99:bg7igkv)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @RaduBerinde)



<!-- Sent from Reviewable.io -->

2021-11-04 14:29 UTC, Azhng commented
TFTR!

bors r=mgartner,matthewtodd,maryliag

2021-11-04 15:24 UTC, Azhng commented
Retrying 

bors r=mgartner,matthewtodd,maryliag

2021-11-04 16:48 UTC, merged