jobs: add mechanism to communicate job completion in-memory locally
cockroachdb/cockroach pull request #72297
Opened 2021-11-01 17:52 UTC by ajwerner

The first commit just moves some code out into a new file to make the second
commit more obvious.

This change does two things. Firstly, when local transactions create jobs
which are pre-claimed by the current registry, there's no need for the
registry to go search to find these job IDs. Instead, it can just directly
attempt to resume them. This nicely avoids a bunch of contention. Then,
when we wait for the jobs to complete, we can avoid polling the status
of the jobs table in the common case and instead wait for an in-memory
notification. This is beneficial because it reduces contention on the
job record of the running job.
    
Release note (performance improvement): Improved job performance in the
face of concurrent schema changes by reducing contention.

2021-11-01 17:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72297)
<!-- Reviewable:end -->

2021-11-01 17:52 UTC, ajwerner commented
@miretskiy I think this is what you were looking for in #71909.

2021-11-01 17:53 UTC, ajwerner commented
Best reviewed commit-by-commit. More fallout from #71800.

2021-12-22 01:23 UTC, miretskiy reviewed
I still need to think this through a bit more; but just initial set of mostly nits.

2021-12-22 01:23 UTC, miretskiy commented on pkg/jobs/wait.go
> +       AND (status != $1 AND status != $2 AND status != $3 AND status != $4)`,
paused need to be considered too?

2021-12-22 01:23 UTC, miretskiy commented on pkg/jobs/wait.go
> +		j, err := r.LoadJob(ctx, id)
i wonder: at what point would just starting a rangefeed and filtering for things we care about be faster?
Certainly would bypass any locking issues, and presumably if the job set cardinality is sufficiently large, running the above count(*) query plus a load for each job might be pretty expensive.

2021-12-22 01:23 UTC, miretskiy commented on pkg/jobs/wait.go
> +	ctx context.Context, ex sqlutil.InternalExecutor, jobs []jobspb.JobID, done <-chan struct{},
nit: (maybe silly one) ... I always associate done with something that this func closes when it's done.  But it appears that in this case done is a signal to wait to stop waiting.  perhaps rename to abortWait or some such?

2021-12-22 01:23 UTC, miretskiy commented on pkg/jobs/registry.go
> +		waiting map[jobspb.JobID]map[*waitingSet]struct{}
nothing wrong w/ this..  but I wonder if we need this map of map of pointer complexity?
Wouldn't just a slice do? I understand we have to iterate or whatnot, but we're not expecting thousands of entries in there, do we?

2021-12-22 02:24 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @stevendanna)

___
*[pkg/jobs/registry.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MnRcKYxfnjnrSsJPfpG-r2-147:-MrUqu7G-wzEM-zMVdcs:b-yp2a34) ([raw file](https://github.com/cockroachdb/cockroach/blob/e715df7959bcd69baf845155102d2236bf4f087f/pkg/jobs/registry.go#L147)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nothing wrong w/ this..  but I wonder if we need this map of map of pointer complexity?
Wouldn't just a slice do? I understand we have to iterate or whatnot, but we're not expecting thousands of entries in there, do we?
</blockquote></details>

why do something worse when there's already something better? I'll make it a type. I disagree that it's that complicated.
___
*[pkg/jobs/wait.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MnRcKYxfnjnrSsJPfpH-r2-66:-MrUtQa-BWdmaylw41Sg:b-62sn8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e715df7959bcd69baf845155102d2236bf4f087f/pkg/jobs/wait.go#L66)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: (maybe silly one) ... I always associate done with something that this func closes when it's done.  But it appears that in this case done is a signal to wait to stop waiting.  perhaps rename to abortWait or some such?
</blockquote></details>

consider `ctx.Done()`... but okay
___
*[pkg/jobs/wait.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MnRcKYxfnjnrSsJPfpH-r2-84:-MrUq_3r-9imfWEQgq6O:b-tazdwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e715df7959bcd69baf845155102d2236bf4f087f/pkg/jobs/wait.go#L84)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

paused need to be considered too?
</blockquote></details>

nice, thanks, done
___
*[pkg/jobs/wait.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MnRcKYxfnjnrSsJPfpH-r2-128:-MrUqaZl5O_SRnnGnaa7:biry5m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e715df7959bcd69baf845155102d2236bf4f087f/pkg/jobs/wait.go#L128)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

i wonder: at what point would just starting a rangefeed and filtering for things we care about be faster?
Certainly would bypass any locking issues, and presumably if the job set cardinality is sufficiently large, running the above count(*) query plus a load for each job might be pretty expensive.
</blockquote></details>

I thought about it and I agree with you but it'd be a *lot* of complexity for this change. This code is just moved, it's not new. I don't worry about these locking issues on the point lookups really at all. Don't look at anything in this file as new code in the first commit. 


<!-- Sent from Reviewable.io -->

2021-12-22 13:59 UTC, miretskiy requested changes
> Reviewed 2 of 5 files at r1, 1 of 7 files at r3, 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @stevendanna)

___
*[pkg/jobs/registry.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MnRcKYxfnjnrSsJPfpG-r2-147:-MrXKIuy6zpkunUwjPtc:b-yfnn4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e715df7959bcd69baf845155102d2236bf4f087f/pkg/jobs/registry.go#L147)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why do something worse when there's already something better? I'll make it a type. I disagree that it's that complicated.
</blockquote></details>

I guess in the eye of a beholder.  A small map is less efficient than the small vector or slice.  At least that was true in c++; pretty sure it's true here as well.   I also find vectors easier to reason about than a map of int to map of pointer (containing channel and a map of int to struct) to struct.
___
*[pkg/jobs/registry.go, line 1168 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXIGpL0eeF0ffwq4s0:-MrXIGpL0eeF0ffwq4s1:b-e9z2fp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/registry.go#L1168)):*
> ```Go
> 	case StatusPaused:
> 		return errors.NewAssertionErrorWithWrappedErrf(jobErr,
> 			"job %d: unexpected status %s provided to state machine", job.ID(), status)
> ```

Does `StatusPaused` branch need `r.removeFromWaitingSet`?

In general, I'm worried about the brittleness of this solution.  Forgetting to remove from sets
is probably okay -- though I wonder if we'd be leaking resources and how much.

Do we need to remove when say `filterAlreadyRunningAndCancelFromPreviousSessions` runs?

Do you think it would make sense to take the existing adoptedJobs map, along w/ waiting set and make a small struct
with methods on it?  I can't think of a reason we wouldn't want to remove from waiting set when `delete(r.mu.adoptedJobs, id)`.  I would replace all uses of the delete with method calls.  And similarly put methods on management of waiting set...
___
*[pkg/jobs/wait.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXMFTHCjd5Z0BFRYt_:-MrXMFTI4E_GSKjpvRN0:b7qh6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L86)):*
> ```Go
> 	// populate the crdb_internal.jobs vtable.
> 	query := fmt.Sprintf(
> 		`SELECT count(*) FROM system.jobs WHERE id IN (%s)
> ```

probably could do w/ out fmt.Sprintf since you built buf anyway?
___
*[pkg/jobs/wait.go, line 226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXQVkR7FlL1DfLgwFk:-MrXQVkR7FlL1DfLgwFl:b-xgzwd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L226)):*
> ```Go
> 					r.ac.AnnotateCtx(context.Background()),
> 					"corruption detected in waiting set for id %d", id,
> 				)
> ```

log.Fatal makes me sad here.  I sort of understand it.. but also, this feels so harsh... And also removeFromWaitingSet below
doesn't do that when deleting from ws.set .
___
*[pkg/jobs/wait.go, line 244 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXPu42-kC8fj40h0gl:-MrXPu42-kC8fj40h0gm:b8no8la) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L244)):*
> ```Go
> 		delete(ws.set, id)
> 		if len(ws.set) == 0 {
> 			close(ws.jobDoneCh)
> ```

I have to say: processing this data structure is giving me hard time.  

The are multiple reasons for this: for one, it's a very complex data structure. 
So complex in fact that it probably needs its own tests imo.

Secondly, this data structure gets mutated all over the place, so it's hard to isolate cause/effect.

Seeing code like this (`close(ws.jobDoneCh)`) makes me worried.  
`removeFromWaitingSets` is called from many places.  Could remove
be called for the same id? Would we panic when we close done channel twice?
I can understand the argument that it doesn't happen *now*, but I hope you can see my concern about brittleness here.
Could an accidental call to removeFromWaitingSets be added where it shouldn't be added, causing a hard to trigger race
condition that our tests will almost certainly not pick up?


<!-- Sent from Reviewable.io -->

2021-12-22 14:07 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @stevendanna)

___
*[pkg/jobs/wait.go, line 244 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXPu42-kC8fj40h0gl:-MrXSjLID05D8CCRp2L1:b-y8xwk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L244)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I have to say: processing this data structure is giving me hard time.  

The are multiple reasons for this: for one, it's a very complex data structure. 
So complex in fact that it probably needs its own tests imo.

Secondly, this data structure gets mutated all over the place, so it's hard to isolate cause/effect.

Seeing code like this (`close(ws.jobDoneCh)`) makes me worried.  
`removeFromWaitingSets` is called from many places.  Could remove
be called for the same id? Would we panic when we close done channel twice?
I can understand the argument that it doesn't happen *now*, but I hope you can see my concern about brittleness here.
Could an accidental call to removeFromWaitingSets be added where it shouldn't be added, causing a hard to trigger race
condition that our tests will almost certainly not pick up?
</blockquote></details>

NM: re panicing; ws.set delete above ensures that doesn't happen... Still, literally every line of code requires thinking what's happening here.


<!-- Sent from Reviewable.io -->

2021-12-22 14:09 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @stevendanna)

___
*[pkg/jobs/wait.go, line 240 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXTOhZB0ZPsPRzWmRg:-MrXTOhZB0ZPsPRzWmRh:b-igoa78) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L240)):*
> ```Go
> 	r.mu.Lock()
> 	defer r.mu.Unlock()
> 	sets := r.mu.waiting[id]
> ```

can it be nil?  I guess that's fine -- range works okay; but is that a bug ?


<!-- Sent from Reviewable.io -->

2021-12-22 15:09 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, and @stevendanna)

___
*[pkg/jobs/registry.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MnRcKYxfnjnrSsJPfpG-r2-147:-MrXg8T76F0GHKhSg_Dt:b-asz0rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e715df7959bcd69baf845155102d2236bf4f087f/pkg/jobs/registry.go#L147)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I guess in the eye of a beholder.  A small map is less efficient than the small vector or slice.  At least that was true in c++; pretty sure it's true here as well.   I also find vectors easier to reason about than a map of int to map of pointer (containing channel and a map of int to struct) to struct.
</blockquote></details>

If we had the new `slices` package coming in go1.18, I might agree with you. Right now they're such a pain to deal with. 
___
*[pkg/jobs/registry.go, line 1168 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXIGpL0eeF0ffwq4s0:-MrXf2QjCj4EFp-IQwzU:by2q7ml) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/registry.go#L1168)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Does `StatusPaused` branch need `r.removeFromWaitingSet`?

In general, I'm worried about the brittleness of this solution.  Forgetting to remove from sets
is probably okay -- though I wonder if we'd be leaking resources and how much.

Do we need to remove when say `filterAlreadyRunningAndCancelFromPreviousSessions` runs?

Do you think it would make sense to take the existing adoptedJobs map, along w/ waiting set and make a small struct
with methods on it?  I can't think of a reason we wouldn't want to remove from waiting set when `delete(r.mu.adoptedJobs, id)`.  I would replace all uses of the delete with method calls.  And similarly put methods on management of waiting set...
</blockquote></details>

The thing I feel like you're missing here and below when you worry about leaks, is that we have the fallback loop and we remove the state when the client who is waiting goes away. If we never notified, the code would still be correct, and, in fact, not worse than what was there before this commit. Notifying is an optimization. 
___
*[pkg/jobs/wait.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXMFTHCjd5Z0BFRYt_:-MrXfVlG82gBO-L74_CB:b-xm854w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L86)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

probably could do w/ out fmt.Sprintf since you built buf anyway?
</blockquote></details>

:shrug: 
___
*[pkg/jobs/wait.go, line 226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXQVkR7FlL1DfLgwFk:-MrXfXMd46pHlwIYaPfk:b9j16gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L226)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

log.Fatal makes me sad here.  I sort of understand it.. but also, this feels so harsh... And also removeFromWaitingSet below
doesn't do that when deleting from ws.set .
</blockquote></details>

Sure, I'll make it less harsh. 
___
*[pkg/jobs/wait.go, line 244 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXPu42-kC8fj40h0gl:-MrXfd7yB5pX-U7UjJxB:bcf6qzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L244)):*
> Still, literally every line of code requires thinking what's happening here.

:thinking: Is it really that subtle? On some level, doesn't every line of code require thinking? Would more commentary put you at ease? There's one place where the channel is closed and before it's closed, it's removed from the data structure, all of that happens under a mutex. 


<!-- Sent from Reviewable.io -->

2021-12-22 15:16 UTC, miretskiy approved these changes
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, and @stevendanna)

___
*[pkg/jobs/registry.go, line 1168 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXIGpL0eeF0ffwq4s0:-MrXgxOg7HzIhKwC_lcI:bwjnbem) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/registry.go#L1168)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The thing I feel like you're missing here and below when you worry about leaks, is that we have the fallback loop and we remove the state when the client who is waiting goes away. If we never notified, the code would still be correct, and, in fact, not worse than what was there before this commit. Notifying is an optimization. 
</blockquote></details>

I see... Which loop also removes from this map as a cleanup?
___
*[pkg/jobs/wait.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXhEcp2LjNFa8YVRUH:-MrXhEcp2LjNFa8YVRUI:b1z98no) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L130)):*
> ```Go
> 	defer func() {
> 		log.Infof(ctx, "waited for %d %v queued jobs to complete %v",
> 			len(jobs), jobs, timeutil.Since(start))
> ```

presumably this doesn't run frequently?
___
*[pkg/jobs/wait.go, line 244 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXPu42-kC8fj40h0gl:-MrXhJZE2Be4xIPZy5bl:baixeqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L244)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> Still, literally every line of code requires thinking what's happening here.

:thinking: Is it really that subtle? On some level, doesn't every line of code require thinking? Would more commentary put you at ease? There's one place where the channel is closed and before it's closed, it's removed from the data structure, all of that happens under a mutex. 
</blockquote></details>

Very true -- code requires thinking.  But simpler code requires a lot less of that.  More commentary is "more better" :)
Perhaps not on deletes or whatnot; but on this function and the lifetime of the waiting sets as a whole.  That comment you left on top (re this being
an optimization is important one); who does the cleanup, when things get removed, etc.  This type of commentary would put me more at ease.


<!-- Sent from Reviewable.io -->

2021-12-22 15:33 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, and @stevendanna)

___
*[pkg/jobs/registry.go, line 1168 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXIGpL0eeF0ffwq4s0:-MrXlFpY83oXL8fkqaH5:biyrbr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/registry.go#L1168)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I see... Which loop also removes from this map as a cleanup?
</blockquote></details>

The `r.Run` method where we call `installWaitingSet` after that we defer the removal. Then, underneath that, we call `r.wait` which polls the status. If the goroutine watching either sees the status change or exits for whatever reason, the state will be cleaned up. 


<!-- Sent from Reviewable.io -->

2021-12-23 02:00 UTC, ajwerner reviewed
Okay, I added ample commentary, did a bit of cleanup, and removed the fatal. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-:-Mr_0BVC9AgND9VGfHm0:b-jkehc8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @stevendanna)

___
*[pkg/jobs/wait.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXMFTHCjd5Z0BFRYt_:-Mr_09GvEFXU6VgvJUkN:bmvsuci) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L86)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

:shrug: 
</blockquote></details>

Refactored this to be better. 
___
*[pkg/jobs/wait.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXhEcp2LjNFa8YVRUH:-Mr_04Kr3TRqq-QzOc7E:b-47bqn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L130)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

presumably this doesn't run frequently?
</blockquote></details>

It runs every time a job gets run, but we log so much for that that it didn't seem like a big deal. 
___
*[pkg/jobs/wait.go, line 226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXQVkR7FlL1DfLgwFk:-MrZzs1S0ZKl4kSgClmy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L226)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Sure, I'll make it less harsh. 
</blockquote></details>

Done.
___
*[pkg/jobs/wait.go, line 240 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXTOhZB0ZPsPRzWmRg:-MrZzssuBG5Ik1eB9Lv5:b-ftkomp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L240)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

can it be nil?  I guess that's fine -- range works okay; but is that a bug ?
</blockquote></details>

It's not at all a bug if it's nil. It'll commonly be nil. I am relying on nil semantics working here. I typed a comment but it seemed better to just check the bool and avoid ambiguity.  
___
*[pkg/jobs/wait.go, line 244 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-MrXPu42-kC8fj40h0gl:-Mr_-VcnE2UFSrtrHKVy:b-d0403s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f497a790e4409b6367767b80211ea4a27658081/pkg/jobs/wait.go#L244)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Very true -- code requires thinking.  But simpler code requires a lot less of that.  More commentary is "more better" :)
Perhaps not on deletes or whatnot; but on this function and the lifetime of the waiting sets as a whole.  That comment you left on top (re this being
an optimization is important one); who does the cleanup, when things get removed, etc.  This type of commentary would put me more at ease.
</blockquote></details>

More commentary here and elsewhere. 


<!-- Sent from Reviewable.io -->

2021-12-23 14:54 UTC, miretskiy approved these changes
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72297)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, and @stevendanna)

___
*[pkg/jobs/wait.go, line 195 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72297#-Mrbm0aj9JLBHdJC5nuO:-Mrbm0aj9JLBHdJC5nuP:bps7gal) ([raw file](https://github.com/cockroachdb/cockroach/blob/5301a3ee55ae678ccf230939e1c47fba7dc735b7/pkg/jobs/wait.go#L195)):*
> ```Go
> // set is an optimization, the caller still polls the job state to wait for it
> // to transition to a terminal status (or paused). This is unavoidable: the job
> // may end up running elsewhere.
> ```

Love it. Thanks for writing this up.


<!-- Sent from Reviewable.io -->

2022-01-03 08:17 UTC, ajwerner commented
bors r+

2022-01-03 10:04 UTC, merged