server: allow toleration of panics in HTTP handlers
cockroachdb/cockroach pull request #72395
Opened 2021-11-03 16:28 UTC by cameronnunez

Fixes #68638.

A panic in an HTTP request handler can cause a node to crash. Nodes should
be tolerant to such panics. This patch handles these panics by intercepting
these panics when they occur and logging them.

Release note (bug fix): servers no longer crash due to panics in HTTP handlers.

2021-11-03 16:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72395)
<!-- Reviewable:end -->

2021-11-25 14:18 UTC, erikgrinaker requested changes
> Reviewed 3 of 5 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72395)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @dhartunian)

___
*[pkg/server/api_v2.go, line 180 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMLqL8Agatm54HTzt7:-MpMLqL8Agatm54HTzt8:bfhtb23) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/api_v2.go#L180)):*
> ```Go
> 		handler = &callCountDecorator{
> 			counter: telemetry.GetCounter(fmt.Sprintf("api.v2.%s", route.url)),
> 			inner:   panicHandler(route.handler),
> ```

Looks like the idiomatic way to register middleware in Gorilla is via `Router.Use()`:

https://github.com/gorilla/mux#middleware

That seems cleaner and likely safer than explicitly wrapping the handlers.
___
*[pkg/server/server.go, line 1990 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMRWX26_EvGYlobyZJ:-MpMRWX26_EvGYlobyZK:b-z08z5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/server.go#L1990)):*
> ```Go
> 		opts ...grpc.CallOption,
> 	) error {
> 		defer log.ErrorOnPanic()
> ```

I'm not sure if it's really necessary to handle panics here. We're just passing the request on to gRPC, so if something did panic, it'd most likely be on the gRPC server side where the request is actually processed. That said, I suppose it doesn't hurt -- I wonder if grpc-gateway maybe already has any options or middleware to do this.
___
*[pkg/server/server.go, line 2726 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMPKPgEeKV5Fhqwfyc:-MpMPKPgEeKV5Fhqwfyd:b-1v3x2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/server.go#L2726)):*
> ```Go
> func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
> 	// This is our base handler, so catch all panics and make sure they stick.
> 	defer log.ErrorOnPanic()
> ```

This seems to be the base handler, as all of the other servers get registered under `s.mux`. If that's the case, we can probably just move all of the panic handling here, but I'll let the server team weigh in on this. 

Also, `ErrorOnPanic()` here seems to only log the message, rather than returning a `500` error response to the caller.
___
*[pkg/server/server_test.go, line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMMQk7-B-xwItzfahP:-MpMMPFb9_FsIwLsXaQW:b-e7wqmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/server_test.go#L90)):*
> ```Go
> 	s, err := serverutils.StartServerRaw(base.TestServerArgs{})
> 	if err != nil {
> 		t.Fatal(err)
> ```

May want to use `require.NoError()` for these.
___
*[pkg/server/server_test.go, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMMcHl7_ZsEHLxrIeb:-MpMMam_AvD2gWfQfLR7:b-436x4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/server_test.go#L101)):*
> ```Go
> 	require.NotPanics(t, func() {
> 		// Pass a nil ResponseWriter to induce panic to recover from.
> 		ts.ServeHTTP(nil /* w */, r)
> ```

This test is a bit loose. If `ts.ServeHTTP()` is later changed such that it no longer panics on `nil` ResponseWriters, then this test will pass even if the panic handling is broken. It'd be better to register a new route that explicitly panics in this test, or something like that.

The test should also assert that a 500 error response is returned to the caller.
___
*[pkg/util/log/log.go, line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMOqwv09mN1HALVVY5:-MpMOqwv09mN1HALVVY6:btrj2it) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/util/log/log.go#L30)):*
> ```
> // This is useful for preventing HTTP handlers from recovering
> // panics and ignoring them.
> ```

This comment doesn't seem accurate anymore.


<!-- Sent from Reviewable.io -->

2021-11-29 23:52 UTC, dhartunian reviewed
> A panic in an HTTP request handler can cause a node to crash. Nodes should
> be tolerant to such panics. This patch handles these panics by intercepting
> them when they occur and logging them.

Can you clarify exactly which servers are getting a panic handler? It seems there are 3 separate cases that are being handled here.

> Reviewed 1 of 5 files at r2, 1 of 3 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-:-Mpi4WjJ6MWu-y2c9WWQ:bm5rn7b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @rauchenstein)

___
*[pkg/server/server.go, line 2753 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-Mpi58Cd4hjxasSXfsml:-Mpi58Cd4hjxasSXfsmm:b1hqrdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1dfb1750e2f2adcd985c00243930a790d05e3c/pkg/server/server.go#L2753)):*
> ```Go
> 		w = gzw
> 	}
> 	s.mux.ServeHTTP(w, r)
> ```

If you export the `panicMiddleware` from a shared pkg you can use it here to just wrap the `ServeHTTP` call. Then it can handle the response writing consistently. Looks like it needs a pointer to `SV` so you can make a func that takes one as an argument and returns a middleware function for you. That can be reused in all 3 cases here.
___
*[pkg/server/debug/server.go, line 246 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-Mpi5TsZDD4gobsgWaMI:-Mpi5TsZDD4gobsgWaMJ:b-rl7dk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1dfb1750e2f2adcd985c00243930a790d05e3c/pkg/server/debug/server.go#L246)):*
> ```Go
> 			http.Error(w, errAPIInternalErrorString, http.StatusInternalServerError)
> 		}
> 	}()
> ```

same advice here as above, you can use the same panic middleware for everything.


<!-- Sent from Reviewable.io -->

2021-11-30 23:02 UTC, cameronnunez reviewed
Done. The panics are to be handled strictly at the base handler. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-:-Mpn3ZRe7seAXaDPOQK1:bofl0xv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @erikgrinaker, and @rauchenstein)

___
*[pkg/server/api_v2.go, line 180 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMLqL8Agatm54HTzt7:-Mpn3jnBAzR__cCfyC_R:b-8v6s81) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/api_v2.go#L180)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Looks like the idiomatic way to register middleware in Gorilla is via `Router.Use()`:

https://github.com/gorilla/mux#middleware

That seems cleaner and likely safer than explicitly wrapping the handlers.
</blockquote></details>

Noted. Panic handling moved to the base handler.
___
*[pkg/server/server.go, line 1990 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMRWX26_EvGYlobyZJ:-Mpn3pa_6Kvt-R0q97I3:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/server.go#L1990)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I'm not sure if it's really necessary to handle panics here. We're just passing the request on to gRPC, so if something did panic, it'd most likely be on the gRPC server side where the request is actually processed. That said, I suppose it doesn't hurt -- I wonder if grpc-gateway maybe already has any options or middleware to do this.
</blockquote></details>

Ditto.
___
*[pkg/server/server.go, line 2726 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMPKPgEeKV5Fhqwfyc:-Mpn3tff0NCTCpilP-sU:b-c66jzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/server.go#L2726)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This seems to be the base handler, as all of the other servers get registered under `s.mux`. If that's the case, we can probably just move all of the panic handling here, but I'll let the server team weigh in on this. 

Also, `ErrorOnPanic()` here seems to only log the message, rather than returning a `500` error response to the caller.
</blockquote></details>

Decided to move all the handling here, which was discussed earlier but hadn't been done so thanks for mentioning it.
___
*[pkg/server/server.go, line 2753 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-Mpi58Cd4hjxasSXfsml:-Mpn44Yg8Qhw1kbkqlYD:bncx3s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1dfb1750e2f2adcd985c00243930a790d05e3c/pkg/server/server.go#L2753)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

If you export the `panicMiddleware` from a shared pkg you can use it here to just wrap the `ServeHTTP` call. Then it can handle the response writing consistently. Looks like it needs a pointer to `SV` so you can make a func that takes one as an argument and returns a middleware function for you. That can be reused in all 3 cases here.
</blockquote></details>

:thumbsup: Moved all the panic interception to the base handler.
___
*[pkg/server/server_test.go, line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMMQk7-B-xwItzfahP:-Mpn4Ffc5TXPf-xfuCyS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/server_test.go#L90)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

May want to use `require.NoError()` for these.
</blockquote></details>

Done.
___
*[pkg/server/server_test.go, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMMcHl7_ZsEHLxrIeb:-Mpn4HVWD6hT2H2X-gpC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/server_test.go#L101)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This test is a bit loose. If `ts.ServeHTTP()` is later changed such that it no longer panics on `nil` ResponseWriters, then this test will pass even if the panic handling is broken. It'd be better to register a new route that explicitly panics in this test, or something like that.

The test should also assert that a 500 error response is returned to the caller.
</blockquote></details>

Done.
___
*[pkg/util/log/log.go, line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMOqwv09mN1HALVVY5:-Mpn4ISIAnrudXyN7dIC:bajgcas) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/util/log/log.go#L30)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

> ```
> // This is useful for preventing HTTP handlers from recovering
> // panics and ignoring them.
> ```

This comment doesn't seem accurate anymore.
</blockquote></details>

No longer necessary so removed.
___
*[pkg/server/debug/server.go, line 246 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-Mpi5TsZDD4gobsgWaMI:-Mpn4Nb-4dkDu-mTYBXB:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1dfb1750e2f2adcd985c00243930a790d05e3c/pkg/server/debug/server.go#L246)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

same advice here as above, you can use the same panic middleware for everything.
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2021-12-01 15:34 UTC, dhartunian reviewed
Nice to see the PR get smaller. No further comments from me, I'll leave the LGTM to your team.

> Reviewed 2 of 5 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-:-MpqcGgU-gRGtDoivn6T:b-c9jjx5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @dhartunian, and @erikgrinaker)

___
*[pkg/server/server.go, line 2753 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-Mpi58Cd4hjxasSXfsml:-Mpqb5kP1c9E8VbZkSHF:b-rgvmpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1dfb1750e2f2adcd985c00243930a790d05e3c/pkg/server/server.go#L2753)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

:thumbsup: Moved all the panic interception to the base handler.
</blockquote></details>

Ah nice!
___
*[pkg/server/server_test.go, line 101 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpqbziuDxe52ZxO8I7z:-MpqbziuDxe52ZxO8I8-:b-pr380q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9299ecf126c8bef3597801fff91a271811c64afe/pkg/server/server_test.go#L101)):*
> ```Go
> 
> 	// Create a request.
> 	req, err := http.NewRequest(http.MethodGet, "http://"+ts.HTTPAddr()+"/panic", nil /* body */)
> ```

nit: I think you can use `ts.AdminURL()` and just append `/panic` to simplify a bit.


<!-- Sent from Reviewable.io -->

2021-12-01 16:13 UTC, erikgrinaker reviewed
Awesome, this is much cleaner! ✨

We're confident that there aren't any HTTP servers tucked away somewhere that don't go via the base muxer?

> Reviewed 2 of 5 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-:-MpqipkP6yYrGnLefPWX:b3nn42a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @dhartunian, and @rauchenstein)

___
*[pkg/server/server.go, line 2756 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpqjRyX1mBW1QFE3Mbg:-MpqjRyX1mBW1QFE3Mbh:byx3o99) ([raw file](https://github.com/cockroachdb/cockroach/blob/9299ecf126c8bef3597801fff91a271811c64afe/pkg/server/server.go#L2756)):*
> ```Go
> 	defer func() {
> 		if p := recover(); p != nil {
> 			logcrash.ReportPanic(context.Background(), &s.st.SV, p, 1 /* depth */)
> ```

I'm a bit worried about the use of `context.Background()` here, since this calls out to e.g. Sentry over the network, so it can cause buildup of goroutines in case of a service outage. It looks like it uses its own timeout rather than relying on the context though:

https://github.com/cockroachdb/cockroach/blob/e002229b6fbedb088cea64b78e480ceba1fe0ab5/pkg/util/log/logcrash/crash_reporting.go#L325

I still think we should use a timeout here, something like 5-10 seconds, e.g. in case we're logging across the network or something. We can also consider inheriting the client request's context, via `http.Request.Context()`, but I think we probably want to report these regardless of whether the client goes away.
___
*[pkg/server/server_test.go, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpMMcHl7_ZsEHLxrIeb:-MpqkyNB4v5d2k4rUa9U:bpb45yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aab9517074c1114a522a72c85c9ca57b1410f62/pkg/server/server_test.go#L101)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, this is much better. 👍
___
*[pkg/server/server_test.go, line 121 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-Mpql3BO-dcI-h-_QGS4:-Mpql3BO-dcI-h-_QGS5:bnfbajd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9299ecf126c8bef3597801fff91a271811c64afe/pkg/server/server_test.go#L121)):*
> ```Go
> 		log.WithMarkedSensitiveData)
> 	require.NoError(t, err)
> 	if len(entries) == 0 {
> ```

nit: consider `require.NotEmpty(t, entries, "no log entries matching the regexp")`.


<!-- Sent from Reviewable.io -->

2021-12-01 16:24 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72395)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @dhartunian, and @rauchenstein)

___
*[pkg/server/server.go, line 2756 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpqjRyX1mBW1QFE3Mbg:-MpqncPB7HTP9YTnAt27:b-crrfj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9299ecf126c8bef3597801fff91a271811c64afe/pkg/server/server.go#L2756)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I'm a bit worried about the use of `context.Background()` here, since this calls out to e.g. Sentry over the network, so it can cause buildup of goroutines in case of a service outage. It looks like it uses its own timeout rather than relying on the context though:

https://github.com/cockroachdb/cockroach/blob/e002229b6fbedb088cea64b78e480ceba1fe0ab5/pkg/util/log/logcrash/crash_reporting.go#L325

I still think we should use a timeout here, something like 5-10 seconds, e.g. in case we're logging across the network or something. We can also consider inheriting the client request's context, via `http.Request.Context()`, but I think we probably want to report these regardless of whether the client goes away.
</blockquote></details>

Actually, nevermind. I think we have to be able to assume that the logging infrastructure will use appropriate timeouts, otherwise we'd have to litter timeouts throughout the entire codebase. But maybe add a comment saying why we use a background context here (i.e., because we want to log even if the client goes away, and we trust the logging infra to use timeouts).


<!-- Sent from Reviewable.io -->

2021-12-01 18:49 UTC, cameronnunez reviewed
Yes, I believe we are confident in that. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-:-MprDfNcCPfDODJq9RR_:b-a3qulh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @dhartunian, and @erikgrinaker)

___
*[pkg/server/server.go, line 2756 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-MpqjRyX1mBW1QFE3Mbg:-MprDwY-9wgIaQOTMdQF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9299ecf126c8bef3597801fff91a271811c64afe/pkg/server/server.go#L2756)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Actually, nevermind. I think we have to be able to assume that the logging infrastructure will use appropriate timeouts, otherwise we'd have to litter timeouts throughout the entire codebase. But maybe add a comment saying why we use a background context here (i.e., because we want to log even if the client goes away, and we trust the logging infra to use timeouts).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-01 19:14 UTC, erikgrinaker approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks!

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72395#-:-MprPflq1G2R_vQJYT8D:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cameronnunez, @dhartunian, and @rauchenstein)



<!-- Sent from Reviewable.io -->

2021-12-01 23:13 UTC, cameronnunez commented
thanks!

bors r=erikgrinaker,dhartunian

2021-12-02 01:10 UTC, merged

2022-01-06 10:31 UTC, erikgrinaker commented
Should we backport this? Just had another incident reported by a customer (on 21.1.10), see #74507.

2022-01-06 17:30 UTC, cameronnunez commented
yes and @knz approves of the idea

2022-01-06 17:30 UTC, cameronnunez commented
blathers backport 21.1

2022-01-06 18:50 UTC, cameronnunez commented
blathers backport 21.2