streamingccl: support protected timestamp in stream replication producer job
cockroachdb/cockroach pull request #72404
Opened 2021-11-03 19:14 UTC by gh-casper

Create protected timestamp to protect tenant spans  when a producer job is created.

Release note: none

2021-11-03 19:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72404)
<!-- Reviewable:end -->

2021-11-10 17:03 UTC, gh-casper reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72404)* status: :shipit: complete! 0 of 0 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72404#-Mo9n8ax9h0XETZVVldw:-Mo9n8ax9h0XETZVVldx:boig35t) (no related file):*
Can you just review the second commit? The first commit is the ongoing "create_replication_stream" change.

---


<!-- Sent from Reviewable.io -->

2021-11-10 18:29 UTC, miretskiy requested changes

2021-11-10 18:29 UTC, miretskiy commented on pkg/ccl/streamingccl/streamproducer/producer_job.go
> +	}
I'm pretty sure we want to create PTS record before we start the job.  E.g. see changefeed_stmt.
Basically, we don't ever want to run streaming w/out knowing we have protected data.

2021-11-10 18:29 UTC, miretskiy commented on pkg/ccl/streamingccl/streamproducer/producer_job.go
> +		Less(ts); shouldUpdatePTS {
Maybe this MinProtectedTS advance is .. a bit premature optimization.
Perhaps we can simply update pts record to ts provided ts > ptsRecord.Timestamp?
We can add min advance later.

2021-11-10 18:29 UTC, miretskiy commented on pkg/ccl/streamingccl/streamproducer/producer_job.go
> +		func(txn *kv.Txn, md jobs.JobMetadata, ju *jobs.JobUpdater) error {
I wonder if the entirety of the above code must happen here, inside UpdateJobWithTxn?

For one, if txn gets retried, you get up to date job record.  So, your checks whether you need to update will
be more accurate.  Secondly, registry takes care of making sure the job is running, so I think you'd be able to drop some of the checks you have above.  Finally, in the happy case, 1 less read against jobs table.

2021-11-10 18:29 UTC, miretskiy commented on pkg/ccl/streamingccl/streamproducer/producer_job_test.go
> +			sql.SucceedsSoonDuration = 3 * time.Second
I will keep asking the same question: why do we need to override this?

2021-11-10 18:30 UTC, miretskiy commented
Okay.

On Wed, Nov 10, 2021 at 12:04 PM gh-casper ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> *Reviewable <https://reviewable.io/reviews/cockroachdb/cockroach/72404>*
> status: [image: :shipit:] complete! 0 of 0 LGTMs obtained
>
> *a discussion
> <https://reviewable.io/reviews/cockroachdb/cockroach/72404#-Mo9n8ax9h0XETZVVldw:-Mo9n8ax9h0XETZVVldx:boig35t>
> (no related file):*
> Can you just review the second commit? The first commit is the ongoing
> "create_replication_stream" change.
> ------------------------------
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/72404#pullrequestreview-802886602>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANA4FVCDGDGNKJLUYVBBS63ULKQZ7ANCNFSM5HJW2VBQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-10 21:40 UTC, gh-casper reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72404)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72404#-Mo9n8ax9h0XETZVVldw:-MoAms_LES2C3CVBaYXK:bvfkwpx) (no related file):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

Can you just review the second commit? The first commit is the ongoing "create_replication_stream" change.
</blockquote></details>

I rebased it on the current master after that PR got merged.

---
___
*[pkg/ccl/streamingccl/streamproducer/producer_job.go, line 151 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72404#-MnbDHwW81CAj-gR-OJj-r5-151:-MoAPYJRC8dZS5xz9olX:b-k36k8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/788640dc08da5b4db318d3ece6c1d321c21ed8eb/pkg/ccl/streamingccl/streamproducer/producer_job.go#L151)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm pretty sure we want to create PTS record before we start the job.  E.g. see changefeed_stmt.
Basically, we don't ever want to run streaming w/out knowing we have protected data.

</blockquote></details>

They will be running in the same transaction (txn object passed in from doStartReplicationStream function). No?
___
*[pkg/ccl/streamingccl/streamproducer/producer_job.go, line 187 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72404#-MnbDHwW81CAj-gR-OJj-r5-187:-MoASWaIB3a_Y8UskQSd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/788640dc08da5b4db318d3ece6c1d321c21ed8eb/pkg/ccl/streamingccl/streamproducer/producer_job.go#L187)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Maybe this MinProtectedTS advance is .. a bit premature optimization.
Perhaps we can simply update pts record to ts provided ts > ptsRecord.Timestamp?
We can add min advance later.
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamproducer/producer_job.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72404#-MnbDHwW81CAj-gR-OJj-r5-194:-MoAS6cSBUgNn0oayH_F:bw8ciz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/788640dc08da5b4db318d3ece6c1d321c21ed8eb/pkg/ccl/streamingccl/streamproducer/producer_job.go#L194)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I wonder if the entirety of the above code must happen here, inside UpdateJobWithTxn?

For one, if txn gets retried, you get up to date job record.  So, your checks whether you need to update will
be more accurate.  Secondly, registry takes care of making sure the job is running, so I think you'd be able to drop some of the checks you have above.  Finally, in the happy case, 1 less read against jobs table.
</blockquote></details>

Same comment above. This `UpdateJobWithTxn` shares the same `txn` object with `provider.UpdateTimestamp()`. So they are running in the same txn?
___
*[pkg/ccl/streamingccl/streamproducer/producer_job_test.go, line 184 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72404#-MnbDHwXH6my1qpEjQSK-r5-184:-MoASUJrEEz9CYELA33C:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/788640dc08da5b4db318d3ece6c1d321c21ed8eb/pkg/ccl/streamingccl/streamproducer/producer_job_test.go#L184)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I will keep asking the same question: why do we need to override this?
</blockquote></details>

Removed.
___
*[pkg/ccl/streamingccl/streamproducer/producer_job_test.go, line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72404#-MnbDHwXH6my1qpEjQSK-r5-215:-MoAR5AL3Xibc7PBwr64:b-e7rdn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/788640dc08da5b4db318d3ece6c1d321c21ed8eb/pkg/ccl/streamingccl/streamproducer/producer_job_test.go#L215)):*
> waitUntilReverting
I should have renamed `waitUntilReverting` to be `waitJobFinishReverting` because the channel is actually signaled after `OnFailOrCancel` runs. In this case, we are sure that the job reaches "reverting" stage after `waitJobFinishReverting()`. 


<!-- Sent from Reviewable.io -->

2021-11-10 22:45 UTC, miretskiy approved these changes
> Reviewed 1 of 22 files at r1, 2 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72404)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @gh-casper, and @miretskiy)

___
*[pkg/ccl/streamingccl/streamproducer/producer_job.go, line 151 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72404#-MnbDHwW81CAj-gR-OJj-r5-151:-MoB-h7BCReIpDiIDwM-:b-xd3vm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/788640dc08da5b4db318d3ece6c1d321c21ed8eb/pkg/ccl/streamingccl/streamproducer/producer_job.go#L151)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

They will be running in the same transaction (txn object passed in from doStartReplicationStream function). No?
</blockquote></details>

You're right.
___
*[pkg/ccl/streamingccl/streamproducer/producer_job.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72404#-MnbDHwW81CAj-gR-OJj-r5-194:-MoB09Wv5aG4L1WwuJwS:brol7hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/788640dc08da5b4db318d3ece6c1d321c21ed8eb/pkg/ccl/streamingccl/streamproducer/producer_job.go#L194)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

Same comment above. This `UpdateJobWithTxn` shares the same `txn` object with `provider.UpdateTimestamp()`. So they are running in the same txn?
</blockquote></details>

Yes, you're correct that it's the same txn... But UpdateJob will execute select to load job record -- so, at the very least, let's not
do this twice?
___
*[pkg/ccl/streamingccl/streamproducer/producer_job_test.go, line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72404#-MnbDHwXH6my1qpEjQSK-r5-215:-MoB0Prh97UG3kSy0zh1:b-wh3mqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/788640dc08da5b4db318d3ece6c1d321c21ed8eb/pkg/ccl/streamingccl/streamproducer/producer_job_test.go#L215)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

> waitUntilReverting
I should have renamed `waitUntilReverting` to be `waitJobFinishReverting` because the channel is actually signaled after `OnFailOrCancel` runs. In this case, we are sure that the job reaches "reverting" stage after `waitJobFinishReverting()`. 
</blockquote></details>

I see.  Makes sense.  Still , double check ? will you?


<!-- Sent from Reviewable.io -->

2021-11-30 01:08 UTC, gh-casper commented
bors r+

2021-11-30 02:23 UTC, merged