backupccl: allow using LATEST shorthand in RESTORE and SHOW BACKUP
cockroachdb/cockroach pull request #72409
Opened 2021-11-03 20:40 UTC by dt

We allow the alias 'LATEST' when backing up into a collection, e.g. by running
BACKUP INTO LATEST IN x, which automatically replaces 'LATEST' with the path to
most recent backup added to the collection. However for RESTORE and SHOW BACKUP
using the same alias would previously return an error, saying that the literal
'latest' path did not contain a backup. This change fixes that, doing the same
automatic expansion of the alias during RESTORE and SHOW that is done by BACKUP.

Release note (bug fix): 'RESTORE ... FROM LATEST IN' now works to restore the latest backup from a collection without needing to first inspect the collection to supply its actual path.

2021-11-03 20:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72409)
<!-- Reviewable:end -->

2021-11-03 23:46 UTC, msbutler approved these changes
LGTM!

2021-11-04 01:17 UTC, msbutler requested changes
Actually, one thought: it might be worth adding a test that verifies that the `SHOW BACKUP LATEST IN location` syntax works

2021-11-09 13:47 UTC, adityamaru approved these changes
+1 if we can add a simple test for `SHOW BACKUP LATEST` that'd be great.

2021-11-09 16:34 UTC, dt commented
Added SHOW test

2021-11-09 19:00 UTC, msbutler approved these changes
LGTM!

2021-11-10 03:39 UTC, dt commented
TFTRs!

bors r+

2021-11-10 15:26 UTC, dt commented
rebased to get revert for that flake, let's try this again

bors r+

2021-11-10 16:17 UTC, merged

2021-12-03 21:45 UTC, dt commented
blathers backport 21.2