kvserver: improve an assertion about closed timestamps
cockroachdb/cockroach pull request #72441
Opened 2021-11-04 18:18 UTC by andreimatei

We have a sanity check on the proposer side asserting that a proposal's
write timestamp is not below the closedts that the propBuf has
previously communicated to followers. Unfortunately, this seems to have
failed in the wild for unknown reasons.

This patch adds lease information to the assertion, and also adds a
second assertion that tries to isolate the failure to properly track
in-flight evaluations. This new assertion checks that a request that's
exiting the evaluation tracker has a higher timestamp than the tracker's
lower bound. This way, if one of these assertions fires again, we'll
know whether the bug is a Tracker problem, or whether the bug is about
the propBuf's assignedClosedTimestamp maintenance.

Release note: None

Touches #72428

2021-11-04 18:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72441)
<!-- Reviewable:end -->

2021-11-04 19:08 UTC, ajwerner reviewed
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72441)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @erikgrinaker, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-MngLHP_2rq_ZjLk3IKz:-MngLHP_2rq_ZjLk3IL-:b-b5a2qs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4ebfe17cbe44c8739ce521e3b8fd0bab4f9a59d/pkg/kv/kvserver/replica_proposal_buf.go#L484)):*
> ```Go
> 			lb := b.evalTracker.LowerBound(ctx)
> 			if wts.Less(lb) && p.Request.IsIntentWrite() {
> 				log.Fatalf(ctx, "%v", errorutil.UnexpectedWithIssueErrorf(72428,
> ```

In what ways is it better or worse to fatal here as opposed to propagating the error up the stack?
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-MngFDWQ3dTcBfpxnSah:-MngFDWQ3dTcBfpxnSai:b-64ypt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4ebfe17cbe44c8739ce521e3b8fd0bab4f9a59d/pkg/kv/kvserver/replica_proposal_buf.go#L677)):*
> ```Go
> 		log.Fatalf(ctx, "%v", errorutil.UnexpectedWithIssueErrorf(72428,
> 			"attempting to propose command writing below closed timestamp. "+
> 				"wts: %s < assigned closed: %s. ba: %s. Lease: %s.",
> ```

uber-nit: lowercase `lease`?


<!-- Sent from Reviewable.io -->

2021-11-04 20:37 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72441)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @erikgrinaker, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-MngLHP_2rq_ZjLk3IKz:-Mngcexz3XIuqFpQ-uBT:bk8pf9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4ebfe17cbe44c8739ce521e3b8fd0bab4f9a59d/pkg/kv/kvserver/replica_proposal_buf.go#L484)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

In what ways is it better or worse to fatal here as opposed to propagating the error up the stack?
</blockquote></details>

Propagating the error up the stack is pretty pointless because we panic up the stack on these errors anyway.
I personally only have soft rules about this choice, and I'll take opinions. In general, if it's easy to return an assertion error instead of panicking (e.g. if the function in question was already returning errors), then I'll prefer to return an error; otherwise I'll panic. But there are factors that will change the calculus for me. For example, in this case, this function does return errors, but it has extra logic for that so that we go through the loop completely. I didn't want to think about the dangers of either a `continue` or an early return at this point.
Also, generally the textbook says to return errors and let the caller decide what to do with them, in order to make functions as pure as possible. But in this case, I'm getting extra-involved with this error by putting an issue number on it. So, this function has a pretty good idea about what it wants from this error - it wants it to be printed loudly, including the issue number. So we're not exactly willing to hand it to the caller and let the caller deal with it as it sees fit; by putting the issue number in it we're getting opinionated about this error.


<!-- Sent from Reviewable.io -->

2021-11-04 20:47 UTC, erikgrinaker approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-:-Mngh8vRBbmJcsUXuF2x:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-MnggLiA2m0Cq0sZe8oD:-MnggLiA2m0Cq0sZe8oE:b6h0cdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4ebfe17cbe44c8739ce521e3b8fd0bab4f9a59d/pkg/kv/kvserver/replica_proposal_buf.go#L143)):*
> ```Go
> 	enqueueUpdateCheck()
> 	closedTimestampTarget() hlc.Timestamp
> 	// leaseDebug returns a info on the current lease.
> ```

nit: stray 'a'.


<!-- Sent from Reviewable.io -->

2021-11-04 22:16 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72441)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @erikgrinaker, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-MnggLiA2m0Cq0sZe8oD:-Mnh0ezg6ELO20NbAcns:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4ebfe17cbe44c8739ce521e3b8fd0bab4f9a59d/pkg/kv/kvserver/replica_proposal_buf.go#L143)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: stray 'a'.
</blockquote></details>

done
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-MngFDWQ3dTcBfpxnSah:-Mnh0PA76MLPSOkAeox_:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4ebfe17cbe44c8739ce521e3b8fd0bab4f9a59d/pkg/kv/kvserver/replica_proposal_buf.go#L677)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

uber-nit: lowercase `lease`?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-11-10 15:20 UTC, nvanbenschoten requested changes
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72441)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, and @erikgrinaker)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-Mo9Q7-z6rFFwOFyZD09:-Mo9Q7-z6rFFwOFyZD0A:b-3cylrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdb3b667dc85cbd33b06c0121df10e58974a4d7/pkg/kv/kvserver/replica_proposal_buf.go#L143)):*
> ```Go
> 	enqueueUpdateCheck()
> 	closedTimestampTarget() hlc.Timestamp
> 	// leaseDebug returns info on the current lease.
> ```

This should be `leaseDebugLocked()`, right? Also, let's move this down to the bottom of these methods.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 483 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-Mo9QNW38xIx-2S__8RU:-Mo9QNW38xIx-2S__8RV:b-uy9vw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdb3b667dc85cbd33b06c0121df10e58974a4d7/pkg/kv/kvserver/replica_proposal_buf.go#L483)):*
> ```Go
> 			wts := p.Request.WriteTimestamp()
> 			lb := b.evalTracker.LowerBound(ctx)
> 			if wts.Less(lb) && p.Request.IsIntentWrite() {
> ```

Why check `p.Request.IsIntentWrite()` twice?
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-Mo9QW_m0faN3CuRROya:-Mo9QW_m0faN3CuRROyb:br75yqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdb3b667dc85cbd33b06c0121df10e58974a4d7/pkg/kv/kvserver/replica_proposal_buf.go#L486)):*
> ```Go
> 				log.Fatalf(ctx, "%v", errorutil.UnexpectedWithIssueErrorf(72428,
> 					"request writing below tracked lower bound: wts: %s < lb: %s; ba: %s; lease: %s.",
> 					wts, lb, p.Request, b.p.leaseDebug()))
> ```

Does the presence of this assertion introduce any new heap allocations on the hot path?


<!-- Sent from Reviewable.io -->

2021-11-10 22:11 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72441)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @erikgrinaker, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-Mo9Q7-z6rFFwOFyZD09:-MoAnVInEXFcLRrfHz2K:b-t0dh8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdb3b667dc85cbd33b06c0121df10e58974a4d7/pkg/kv/kvserver/replica_proposal_buf.go#L143)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This should be `leaseDebugLocked()`, right? Also, let's move this down to the bottom of these methods.
</blockquote></details>

RLocked.
Done.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 483 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-Mo9QNW38xIx-2S__8RU:-MoAnf33C6SoD5Osnk3P:b-lkjeqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdb3b667dc85cbd33b06c0121df10e58974a4d7/pkg/kv/kvserver/replica_proposal_buf.go#L483)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why check `p.Request.IsIntentWrite()` twice?
</blockquote></details>

no reason. done.
___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-Mo9QW_m0faN3CuRROya:-MoAtpinBrJlRTloXNBO:b40ikfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdb3b667dc85cbd33b06c0121df10e58974a4d7/pkg/kv/kvserver/replica_proposal_buf.go#L486)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does the presence of this assertion introduce any new heap allocations on the hot path?
</blockquote></details>

good call; I've now made copies of the variables inside the assertion block


<!-- Sent from Reviewable.io -->

2021-11-10 22:41 UTC, nvanbenschoten requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72441)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andreimatei)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-Mo9QW_m0faN3CuRROya:-MoB-_i30L714aW0u-3l:b-3evf47) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdb3b667dc85cbd33b06c0121df10e58974a4d7/pkg/kv/kvserver/replica_proposal_buf.go#L486)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

good call; I've now made copies of the variables inside the assertion block
</blockquote></details>

Don't you want real copies, not recomputed copies? That way you're actually printing what you used to compare.

```
wts, lb := wts, lb // copies escape to heap
```


<!-- Sent from Reviewable.io -->

2021-11-11 00:56 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72441)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-Mo9QW_m0faN3CuRROya:-MoBUhqACj1WOthoW21h:b-yxoa7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fdb3b667dc85cbd33b06c0121df10e58974a4d7/pkg/kv/kvserver/replica_proposal_buf.go#L486)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Don't you want real copies, not recomputed copies? That way you're actually printing what you used to compare.

```
wts, lb := wts, lb // copies escape to heap
```
</blockquote></details>

yes. I think I went back and forth and ended up in the middle. Done.


<!-- Sent from Reviewable.io -->

2021-11-11 18:57 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-:-MoFM8-EASMnf03kWfcX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andreimatei)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 485 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-MoFM4oS44EeI5ow6LbR:-MoFM4oS44EeI5ow6LbS:b-92fqil) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa18b6adf34d405f07134513e60cc49dfa48652b/pkg/kv/kvserver/replica_proposal_buf.go#L485)):*
> ```Go
> 			lb := b.evalTracker.LowerBound(ctx)
> 			if wts.Less(lb) {
> 				// Copies that escape to the heap.
> ```

This comment is now redundant.


<!-- Sent from Reviewable.io -->

2021-11-11 19:52 UTC, andreimatei reviewed
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-:-MoFYbV_4NGeGWXETP4f:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 485 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72441#-MoFM4oS44EeI5ow6LbR:-MoFYaPuCulkHL-lXh9V:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa18b6adf34d405f07134513e60cc49dfa48652b/pkg/kv/kvserver/replica_proposal_buf.go#L485)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment is now redundant.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-11-12 02:58 UTC, merged

2021-11-22 10:01 UTC, erikgrinaker commented
@andreimatei Should we backport this for 21.1 and 21.2?