Blocklist liquibase
cockroachdb/cockroach pull request #72554
Opened 2021-11-09 02:51 UTC by otan

2021-11-09 02:51 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72554)
<!-- Reviewable:end -->

2021-11-09 18:35 UTC, rafiss requested changes
they just had a new test harness tag https://github.com/liquibase/liquibase-test-harness/tags

maybe try with 1.0.4

i also asked in https://cockroachlabs.slack.com/archives/CUG42HAN9/p1636482649001700

2021-11-09 20:24 UTC, otan commented
makes it worse

```

Failed tests:   apply addCheckConstraint against cockroachdb 20.2(liquibase.harness.change.ChangeObjectTests): liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Validation Failed:(..)
  apply addDefaultValueSequenceNext against cockroachdb 20.2(liquibase.harness.change.ChangeObjectTests): Condition not satisfied:(..)
  apply alterSequence against cockroachdb 20.2(liquibase.harness.change.ChangeObjectTests): Condition not satisfied:(..)
  apply createSequence against cockroachdb 20.2(liquibase.harness.change.ChangeObjectTests): Condition not satisfied:(..)
  apply dropCheckConstraint against cockroachdb 20.2(liquibase.harness.change.ChangeObjectTests): liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Validation Failed:(..)
  apply dropSequence against cockroachdb 20.2(liquibase.harness.change.ChangeObjectTests): Condition not satisfied:(..)
  apply renameSequence against cockroachdb 20.2(liquibase.harness.change.ChangeObjectTests): Condition not satisfied:(..)
  Apply column against cockroachdb 20.2(liquibase.harness.snapshot.SnapshotObjectTests): Can't find resource file /liquibase/harness/snapshot/expectedSnapshot/column.json!. Expression: inputStream. Values: inputStream = null
  Apply table against cockroachdb 20.2(liquibase.harness.snapshot.SnapshotObjectTests): Can't find resource file /liquibase/harness/snapshot/expectedSnapshot/table.json!. Expression: inputStream. Values: inputStream = null
```

```

Apply table against cockroachdb 20.2(liquibase.harness.snapshot.SnapshotObjectTests)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Can't find resource file /liquibase/harness/snapshot/expectedSnapshot/table.json!. Expression: inputStream. Values: inputStream = null
	at liquibase.harness.util.FileUtils.getResourceContent(FileUtils.groovy:75)
	at liquibase.harness.snapshot.SnapshotObjectTests.Apply #testInput.snapshotObjectName against #testInput.database.name #testInput.database.version(SnapshotObjectTests.groovy:25)
	Suppressed: java.lang.AssertionError: Can't find resource file /liquibase/harness/snapshot/cleanupSql/table.sql!. Expression: inputStream. Values: inputStream = null
		at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:417)
		at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
		at liquibase.harness.util.FileUtils.getResourceContent(FileUtils.groovy:75)
		at liquibase.harness.util.FileUtils$getResourceContent$2.call(Unknown Source)
		at liquibase.harness.util.DatabaseConnectionUtil.executeQuery(DatabaseConnectionUtil.groovy:109)
		at liquibase.harness.util.DatabaseConnectionUtil$executeQuery$1.callStatic(Unknown Source)
		at liquibase.harness.snapshot.SnapshotObjectTests.$spock_feature_0_0(SnapshotObjectTests.groovy:39)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

```

apply dropCheckConstraint against cockroachdb 20.2(liquibase.harness.change.ChangeObjectTests)  Time elapsed: 0.701 sec  <<< FAILURE!
java.lang.AssertionError: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Validation Failed:
     2 changes have validation failures
          Change Set ID: 1 Change Set Author: as
Change Type 'pro:addCheckConstraint' is not allowed without a valid Liquibase Pro License.
To purchase or renew a Liquibase Pro license key, please contact sales@liquibase.com or
go to https://www.liquibase.org/download, liquibase/harness/change/changelogs/dropCheckConstraint.xml::1::as
          Change Set ID: 2 Change Set Author: as
Change Type 'pro:dropCheckConstraint' is not allowed without a valid Liquibase Pro License.
To purchase or renew a Liquibase Pro license key, please contact sales@liquibase.com or
go to https://www.liquibase.org/download, liquibase/harness/change/changelogs/dropCheckConstraint.xml::2::as

	at org.junit.Assert.fail(Assert.java:88)
	at liquibase.harness.util.TestUtils.executeCommandScope(TestUtils.groovy:53)
	at liquibase.harness.change.ChangeObjectTests.apply #testInput.changeObject against #testInput.databaseName #testInput.version(ChangeObjectTests.groovy:47)
	Suppressed: java.lang.AssertionError: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Validation Failed:
     2 changes have validation failures
          Change Set ID: 1 Change Set Author: as
Change Type 'pro:addCheckConstraint' is not allowed without a valid Liquibase Pro License.
To purchase or renew a Liquibase Pro license key, please contact sales@liquibase.com or
go to https://www.liquibase.org/download, liquibase/harness/change/changelogs/dropCheckConstraint.xml::1::as
          Change Set ID: 2 Change Set Author: as
Change Type 'pro:dropCheckConstraint' is not allowed without a valid Liquibase Pro License.
To purchase or renew a Liquibase Pro license key, please contact sales@liquibase.com or
go to https://www.liquibase.org/download, liquibase/harness/change/changelogs/dropCheckConstraint.xml::2::as
```

2021-11-10 16:59 UTC, rafiss commented
I asked for help in https://cockroachlabs.slack.com/archives/CUG42HAN9/p1636563545003300

2021-11-16 21:24 UTC, closed without merging