bazel: run docker image tests under Bazel
cockroachdb/cockroach pull request #72586
Opened 2021-11-09 20:42 UTC by ZhouXing19

2021-11-09 20:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72586)
<!-- Reviewable:end -->

2021-11-22 16:27 UTC, rail reviewed
I have a crazy idea :)
Can we run these tests as a part of the acceptance test? Acceptance has a lot of functions/utils which know how to deal with docker, so maybe we can reuse them? See https://github.com/cockroachdb/cockroach/tree/master/pkg/acceptance for the details.

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-:-Mp7SOil9tbCu85ZLHQk:byuh21r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder and @ZhouXing19)

___
*[pkg/docker/docker_test.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7PINS11h5iN6PHVmL:-Mp7PINS11h5iN6PHVmM:b-eh2tw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_test.go#L66)):*
> ```Go
> 		testcase := fmt.Sprintf("Running %s", tt.testName)
> 		t.Run(testcase, func(t *testing.T) {
> 			err := buildDockerContainer(tt.buildContainerArgs, tt.containerName)
> ```

From what it does, it sounds like `buildDockerContainer` should be renamed to `runDockerContainer` and `buildContainerArgs` to `runContainerArgs`. What do you think?
___
*[pkg/docker/docker_utils.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7LOmR1c9s74ivYc4a:-Mp7LOmR1c9s74ivYc4b:b8qc9og) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L32)):*
> ```Go
> 		"container",
> 		"rm",
> 		"-f",
> ```

I wonder if the docker version we use supports `docker container prune -f`. This way you don't need to pass the command through `sh`.
___
*[pkg/docker/docker_utils.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7MEaP5ALZOtofL3Lf:-Mp7MEaP5ALZOtofL3Lg:b8kehll) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L42)):*
> ```Go
> // listContainers print the list of all active containers.
> func listContainers() (string, error) {
> 	output, err := exec.Command("docker", "container", "ls").Output()
> ```

Maybe add `-q` to get rid of the titles and `--no-trunc` to get full IDs?
___
*[pkg/docker/docker_utils.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7MqCkEiPTJUOxanpY:-Mp7MqCkEiPTJUOxanpZ:bhuyile) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L58)):*
> ```Go
> 	}
> 
> 	fmt.Println(string(output))
> ```

Maybe instead of printing the logs here, we can return them back to the caller function and let it decide whether to print them?
___
*[pkg/docker/docker_utils.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7ODaTAGupCx9eFEWv:-Mp7ODaTAGupCx9eFEWw:b-3cjhu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L66)):*
> ```Go
> func buildDockerContainer(dockerRunArgs []string, containerName string) error {
> 	// Must make sure that the container name is consistent with the one
> 	// in dockerRunArgs.
> ```

Is this comment a TODO? I'm not sure what it means :)
___
*[pkg/docker/docker_utils.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7NPYB3XDUojqbYKkd:-Mp7NPYB3XDUojqbYKke:b31jc2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L69)):*
> ```Go
> 	dockerRunArgs = append(dockerRunArgs, fmt.Sprintf("--listening-url-file=%s", FifoFile))
> 
> 	if len(dockerRunArgs) == 0 {
> ```

Is this even possible for `dockerRunArgs` to be zero? Or did you want to check this before `append()`?
___
*[pkg/docker/docker_utils.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7Pjv2D_wMMPjkn4I1:-Mp7Pjv2D_wMMPjkn4I2:b-p9ek63) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L73)):*
> ```Go
> 	}
> 
> 	if dockerRunArgs[0] != "run" {
> ```

Maybe instead of checking for "run" you just don't pass it from the caller and let this function explicitly add it for `exec.Command("docker", "run", dockerRunArgs...)`? You may also want to control the `-d` flag - if someone forgets to specify it, you may end up in a situation when the command doesn't run in background, so you won't be able to control the timeout.
___
*[pkg/docker/docker_utils.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7R0_30Rb0eVkscI5d:-Mp7R0_30Rb0eVkscI5e:b4j3tfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L107)):*
> ```Go
> 	}
> 
> 	//time.Sleep(1 * time.Second)
> ```

Remove or uncomment :)


<!-- Sent from Reviewable.io -->

2021-11-29 18:45 UTC, ZhouXing19 commented
@rail thanks for the previous suggestions for using docker compose to run containers, and use `expect` files to run SQL queries. However, I decided to switch to docker's go SDK because the current docker image is built on `registry.access.redhat.com/ubi8/ubi-minimal`, which makes it quite complicated to install the `expect` tool. 
This commit only added tests for single-node server, I'll try to support a multi-node cluster test, maybe for a flex Friday project.

2021-11-29 19:03 UTC, rafiss requested changes
i didn't review the docker_utils file too closely, but i defer to Rail on that. looking nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-:-Mph3ybtCEyhqB-zFI2S:b-z656ji)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rail, and @ZhouXing19)

___
*[pkg/docker/single_node_docker_test.go, line 15 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph3U_lD_q4_ob5Ax6V:-Mph3U_lD_q4_ob5Ax6W:bmi5znr) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/single_node_docker_test.go#L15)):*
> ```Go
> )
> 
> type SqlQuery struct {
> ```

nit: does this need to be capitalized? either way, it could use a comment
___
*[pkg/docker/single_node_docker_test.go, line 22 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph3FXl5VaZngpxIXxn:-Mph3FXl5VaZngpxIXxo:b-2clyfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/single_node_docker_test.go#L22)):*
> ```Go
> // runContainerArgs are equivalent to arguments passed to a `docker run `
> // command.
> // envSetting is to set the environment variables. volSetting is to set
> ```

nit: the comments on what each variable is should go above that variable
___
*[pkg/docker/single_node_docker_test.go, line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph3LbW2TfcJwg2w8GU:-Mph3LbX3eSrV03a9S3-:bgyvqu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/single_node_docker_test.go#L40)):*
> ```Go
> 	containerName    string
> 	sqlOpts          []string
> 	sqlQueries       []SqlQuery
> ```

nit: add comments for sqlOpts and sqlQueries to say how they are used
___
*[pkg/docker/single_node_docker_test.go, line 160 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph3jqa1GXudoy7yGwP:-Mph3jqa1GXudoy7yGwQ:b-qotv5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/single_node_docker_test.go#L160)):*
> ```Go
> 			if err := contextutil.RunWithTimeout(
> 				ctx,
> 				"wait server to fully start up",
> ```

nit: "wait for server"
___
*[pkg/docker/docker-entrypoint-initdb.d/foo.txt, line 0 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph2vNO9oyYtG3LCgYz:-Mph2vNP75wy-fu2xUu5:b-ovij14) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker-entrypoint-initdb.d/foo.txt#L0)):*
is this empty file intentional?
___
*[pkg/docker/docker-entrypoint-initdb.d/hello.sql, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph2xOa58cT6vnuivLv:-Mph2xOa58cT6vnuivLw:b-ngwu42) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker-entrypoint-initdb.d/hello.sql#L1)):*
> ```TSQL
> USE mydb;
> ```

nit: all of the test files should be under `pkg/docker/testdata/docker-entrypoint-initdb.d/`


<!-- Sent from Reviewable.io -->

2021-11-29 19:08 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rail, and @ZhouXing19)

___
*[build/teamcity/cockroach/ci/tests/docker-image.sh, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph5DmlANGrsQJ4pmQR:-Mph5DmlANGrsQJ4pmQS:bndh4oy) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/build/teamcity/cockroach/ci/tests/docker-image.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

it looks like other files in this directory use underscored instead of dashes; so maybe rename to `docker_image.sh`. or `docker_image_test.sh`


<!-- Sent from Reviewable.io -->

2021-11-30 02:53 UTC, rail reviewed
This looks amazing! I have some questions and comments.

> Reviewed 6 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-:-Mpikaz96Jhjqifj0FdN:b-rqessg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail and @ZhouXing19)

___
*[pkg/docker/BUILD.bazel, line 4 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph60Dx0dXswWerEhWS:-Mph60Dy1YWbHyc6ohaQ:b-or1gip) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/BUILD.bazel#L4)):*
> ```Starlark
> 
> go_library(
>     name = "docker",
> ```

Hmm, "docker" sounds very generic. Not sure where to put it ATM, maybe somewhere under `pkg/testutil`?
___
*[pkg/docker/BUILD.bazel, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph7_c398AchHptUKp3:-Mph7_c398AchHptUKp4:b6v45c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/BUILD.bazel#L26)):*
> ```Starlark
>         "docker-entrypoint-initdb.d/**",
>     ]) + [
>         "//pkg/docker:docker-entrypoint-initdb.d",
> ```

This is interesting. What does it do? IIRC, you added this to fix the "file not found" issue when you mount a docker volume, but I'm not sure if I understand how this helps.
___
*[pkg/docker/docker_utils.go, line 31 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph82ADBAa9J9zgxZRF:-Mph82ADBAa9J9zgxZRG:b-we2zfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L31)):*
> ```Go
> 	HostPort            = "8080"
> 	CockroachPort       = "26275"
> 	HostIP              = "127.0.0.1"
> ```

I believe you don't need to export the variables above, better to keep them lower case.
___
*[pkg/docker/docker_utils.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph5MCC0EE4h_EshTGM:-Mph5MCC0EE4h_EshTGN:b-ph22rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L41)):*
> ```Go
> // removeLocalData removes existing database saved in cockroach-data.
> func removeLocalData() error {
> 	_, err := exec.Command("rm", "-rf", "./cockroach-data").Output()
> ```

Maybe use https://pkg.go.dev/os#RemoveAll instead? It's more portable and you can get better errors.
___
*[pkg/docker/docker_utils.go, line 48 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph915H5Hs17WXGGzLy:-Mph915H5Hs17WXGGzLz:befbqf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L48)):*
> ```Go
> }
> 
> // showContainerLog outputs the container's logs to the logFile and stdout.
> ```

`io.MultiWriter()` uses `os.Stderr`, probably you meant "and stderr".
___
*[pkg/docker/docker_utils.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphAPwC6fPOQTHTtXqX:-MphAPwDDryDbae_cNmp:buk9ma2) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L128)):*
> ```Go
> // removeAllContainers removes all running containers by force.
> func (dn *dockerNode) removeAllContainers(ctx context.Context) error {
> 	conts, err := dn.cli.ContainerList(ctx, types.ContainerListOptions{All: true})
> ```

I wonder if we should remove only "our containers" instead. Removing all containers would probably work in CI, but may be a bit dangerous if you run this locally. What do you think?
___
*[pkg/docker/docker_utils.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphAvWoB7BH1NZdRxx5:-MphAvWoB7BH1NZdRxx6:boeaosl) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L141)):*
> ```Go
> }
> 
> type ExecResult struct {
> ```

If you don't need to export this, please use lower case for the struct and the member names.
___
*[pkg/docker/docker_utils.go, line 154 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphBKOt0dq_ohpsNwfe:-MphBKOt0dq_ohpsNwff:b-gtb62j) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L154)):*
> ```Go
> 	resp, err := dn.cli.ContainerExecAttach(ctx, execId, types.ExecStartCheck{})
> 	if err != nil {
> 		return execResult, err
> ```

I nit, `return  ExecResult{}, err` would be a more explicit signal that this is an error condition. It confused me for a few seconds :)
___
*[pkg/docker/docker_utils.go, line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphCdFDC_VLGI7vvPga:-MphCdFDC_VLGI7vvPgb:b-f6iq73) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L210)):*
> ```Go
> 		return nil, fmt.Errorf(
> 			"cannot create command \"%s\":\n %v",
> 			strings.Join(cmd[:], " "),
> ```

A nit: do you have to use `cmd[:]` instead of `cmd`?
___
*[pkg/docker/docker_utils.go, line 236 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphCz00AwJsH_dtY61m:-MphCz00AwJsH_dtY61n:b-3vn9ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L236)):*
> ```Go
> 
> // waitServerStarts waits till the server truly starts or timeout, whichever
> // earlier. It keeps listening to the
> ```

The comment looks incomplete.
___
*[pkg/docker/docker_utils.go, line 248 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphDLfj4r6KcSWPzlCy:-MphDLfj4r6KcSWPzlCz:bfdivze) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L248)):*
> ```Go
> 		ctx,
> 		[]string{
> 			"inotifywait",
> ```

I wonder if we can use Go instead `inotifywait`, so we have less OS deps. Maybe https://github.com/fsnotify/fsnotify - it's already vendored?
___
*[pkg/docker/docker_utils.go, line 287 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MpiZkkM0vszx_XchxKc:-MpiZkkN3S3QXX--zDqB:b23q1w2) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L287)):*
> ```Go
> 	ctx context.Context, sqlQuery string, sqlQueryOpts []string,
> ) (*ExecResult, error) {
> 	query := append([]string{cockroachEntrypoint, "sql", "-e", fmt.Sprintf("%s", sqlQuery)},
> ```

I think `fmt.Sprintf()` is redundant here, just use `sqlQuery`.
___
*[pkg/docker/single_node_docker_test.go, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mpi_b95E2NE894GSuFA:-Mpi_b95E2NE894GSuFB:b-b56bj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/single_node_docker_test.go#L60)):*
> ```Go
> 					"COCKROACH_USER=myuser",
> 					"COCKROACH_PASSWORD=23333",
> 					"DOCKER_API_VERSION=1.39",
> ```

Can you add comments why we have to use this particular Docker API version. Would we need to update it, if we decide to upgrade the docker version we use on the agents?
___
*[pkg/docker/single_node_docker_test.go, line 113 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mpiadlg5zM_L9awGPOG:-Mpiadlg5zM_L9awGPOH:b-jai5nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/single_node_docker_test.go#L113)):*
> ```Go
> 	}
> 
> 	cli, err := client.NewClientWithOpts(client.FromEnv)
> ```

A nit. `cli` threw me off a bit, because it looks like CLI :) I wonder what name we can use without changing the imports.


<!-- Sent from Reviewable.io -->

2021-11-30 03:52 UTC, ZhouXing19 commented
___
*[pkg/docker/BUILD.bazel, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph7_c398AchHptUKp3:-MpixuZLCsGSWzD671sh:b-s0yqde) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/BUILD.bazel#L26)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

This is interesting. What does it do? IIRC, you added this to fix the "file not found" issue when you mount a docker volume, but I'm not sure if I understand how this helps.
</blockquote></details>

I have no idea lol, it just worked like magic


<!-- Sent from Reviewable.io -->

2021-11-30 16:23 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rail)

___
*[pkg/docker/docker_test.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7PINS11h5iN6PHVmL:-Mpiz0d219zwPBa8E2Vi:bpvmcbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_test.go#L66)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

From what it does, it sounds like `buildDockerContainer` should be renamed to `runDockerContainer` and `buildContainerArgs` to `runContainerArgs`. What do you think?
</blockquote></details>

Resolved since we're using docker's go sdk now.
___
*[pkg/docker/docker-entrypoint-initdb.d/foo.txt, line  at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph2vNO9oyYtG3LCgYz:-MpldnSPDuyCWrKqt9bZ:bxcue9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker-entrypoint-initdb.d/foo.txt#L)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is this empty file intentional?
</blockquote></details>

Yes this file should be ignored by the init process since we don't support a txt format. I just added some random lines to it. 
___
*[build/teamcity/cockroach/ci/tests/docker-image.sh, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph5DmlANGrsQJ4pmQR:-Mpld3L94yvMhsk1ctWX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/build/teamcity/cockroach/ci/tests/docker-image.sh#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it looks like other files in this directory use underscored instead of dashes; so maybe rename to `docker_image.sh`. or `docker_image_test.sh`
</blockquote></details>

Done.
___
*[pkg/docker/BUILD.bazel, line 4 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph60Dx0dXswWerEhWS:-Mpld5681hxvCDVabJF_:b-8u1khv) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/BUILD.bazel#L4)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Hmm, "docker" sounds very generic. Not sure where to put it ATM, maybe somewhere under `pkg/testutil`?
</blockquote></details>

Moved it to `pkg/testutils`, and renamed the go_library to `testutils_docker`.
___
*[pkg/docker/docker_utils.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7LOmR1c9s74ivYc4a:-MpizkJc3mD7a5F51NaO:bpvmcbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L32)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

I wonder if the docker version we use supports `docker container prune -f`. This way you don't need to pass the command through `sh`.
</blockquote></details>

Resolved since we're using docker's go sdk now.
___
*[pkg/docker/docker_utils.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7MEaP5ALZOtofL3Lf:-Mpj-Gj60-HvWKQZOcqC:bpvmcbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L42)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Maybe add `-q` to get rid of the titles and `--no-trunc` to get full IDs?
</blockquote></details>

Resolved since we're using docker's go sdk now.
___
*[pkg/docker/docker_utils.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7MqCkEiPTJUOxanpY:-Mpj-HmC8sieEyV1ZXF5:bpvmcbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L58)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Maybe instead of printing the logs here, we can return them back to the caller function and let it decide whether to print them?
</blockquote></details>

Resolved since we're using docker's go sdk now.
___
*[pkg/docker/docker_utils.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7ODaTAGupCx9eFEWv:-Mpj-IVe4fZ25GnALN7U:bpvmcbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L66)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Is this comment a TODO? I'm not sure what it means :)
</blockquote></details>

Resolved since we're using docker's go sdk now.
___
*[pkg/docker/docker_utils.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7NPYB3XDUojqbYKkd:-Mpj-JJp6OTwIyhX-cid:bpvmcbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L69)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Is this even possible for `dockerRunArgs` to be zero? Or did you want to check this before `append()`?
</blockquote></details>

Resolved since we're using docker's go sdk now.
___
*[pkg/docker/docker_utils.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7Pjv2D_wMMPjkn4I1:-Mpj-K3HA61E47HvSV_j:bpvmcbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L73)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Maybe instead of checking for "run" you just don't pass it from the caller and let this function explicitly add it for `exec.Command("docker", "run", dockerRunArgs...)`? You may also want to control the `-d` flag - if someone forgets to specify it, you may end up in a situation when the command doesn't run in background, so you won't be able to control the timeout.
</blockquote></details>

Resolved since we're using docker's go sdk now.
___
*[pkg/docker/docker_utils.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mp7R0_30Rb0eVkscI5d:-Mpj1M26BKs5En74xPYe:bpvmcbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff2adcde5953ead9c427af33aba40e7e99c0f05/pkg/docker/docker_utils.go#L107)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Remove or uncomment :)
</blockquote></details>

Resolved since we're using docker's go sdk now.
___
*[pkg/docker/docker_utils.go, line 31 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph82ADBAa9J9zgxZRF:-MpldFouCSn46w6shJRR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L31)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

I believe you don't need to export the variables above, better to keep them lower case.
</blockquote></details>

Done.
___
*[pkg/docker/docker_utils.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph5MCC0EE4h_EshTGM:-MpldHJZ-sUb07Ysf7Ee:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L41)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Maybe use https://pkg.go.dev/os#RemoveAll instead? It's more portable and you can get better errors.
</blockquote></details>

Done.
___
*[pkg/docker/docker_utils.go, line 48 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mph915H5Hs17WXGGzLy:-MpldI0D6Kw8oKb7VXP-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L48)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

`io.MultiWriter()` use [...]

2021-11-30 16:25 UTC, ZhouXing19 commented
___
*[pkg/docker/docker_utils.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphAPwC6fPOQTHTtXqX:-MpleFhD6svSUHIR_GVy:bxiuyfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L128)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Actually, this is just for a sanity check, to make sure no containers are running with the same port. But we probably can just remove it, since if there's a container on the same port, it will fail to start the new container with the error message `Bind for 127.0.0.1:26275 failed: port is already allocated`, and this hints the user to remove associated containers.
</blockquote></details>

Oh I think I understand what you meant my `our containers` now -- just remove all containers using this `cockroachdb/cockroach-demo:latest` image. Yes that makes much sense, let me try to implement it.


<!-- Sent from Reviewable.io -->

2021-11-30 17:20 UTC, ZhouXing19 commented
___
*[pkg/docker/docker_utils.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphAPwC6fPOQTHTtXqX:-MplrBRQ0YVvhZ_asFZI:bmfxgaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L128)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Oh I think I understand what you meant my `our containers` now -- just remove all containers using this `cockroachdb/cockroach-demo:latest` image. Yes that makes much sense, let me try to implement it.
</blockquote></details>

Done :)


<!-- Sent from Reviewable.io -->

2021-12-09 16:58 UTC, jlinder requested changes
This is looking great! I left some questions and comments.

> Reviewed 5 of 9 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-:-MqV72BY75pQKwqvu38X:bz9yese)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rail, and @ZhouXing19)

___
*[pkg/testutils/docker/testdata/single-node-test/docker-entrypoint-initdb.d/foo.txt, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MqV6gaG-l8GU1pcyiqB:-MqV6gaHEy7la17vqPZG:b-91s301) ([raw file](https://github.com/cockroachdb/cockroach/blob/863fc62c8f3ebf1f7023ecc3c44cd4c8993a59be/pkg/testutils/docker/testdata/single-node-test/docker-entrypoint-initdb.d/foo.txt#L1)):*
> ```help
> This file is intentionally left with some random strings since the docker init
> ```

Why is this file needed?
___
*[pkg/docker/docker_utils.go, line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphCdFDC_VLGI7vvPga:-MqMqOanBa9jfSSTzp3V:bqos2f5) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L210)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Note: It looks like you missed one `cmd`.
___
*[pkg/docker/docker_utils.go, line 248 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphDLfj4r6KcSWPzlCy:-MqUxCsx1kj0EmdTdHGD:bsef5yu) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L248)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

I think we may have to go with the os here, because when the server is fully started, it writes to the urlFile _inside_ the container, so we have to get _inside_ the container and listen to the file. I.e., we have to run a `docker exec` command to do that. 

Another way to use `fsnotify` is to mount a go file with it to the container, and but use `docker exec` to run that go file instead of inotifywait command. It may work, but then we need to install `fsnotify` inside that container. But it doesn't seem easier than what we have with `inotifywait` right now.

</blockquote></details>

I think mounting a go binary that uses `fsnotify` to the container is the better way to do this. The reasons:

- Adding a dependency for a new tool means it needs to be vendored into the repo (we vendor all dependencies).
- `inotify-tools` is a C program. We want to have as few C/C++ dependencies as possible (ideally 0).
- `fsnotify` is already vendored
-   The docker image being tested is the production / release image. That image should include only the things needed for running cockroach in production. Thus, testing / development tools like `inotify-tools` (and the suggested go program using `fsnotify`) should not be built into the image and all the supporting tools needed to build `inotify-tools` in the image should not be included in the image.
___
*[pkg/testutils/docker/docker_utils.go, line 244 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MqMrHaSA2KNwnWiZauJ:-MqMrHaT35IGpmdzYLO1:b-k2qq4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/863fc62c8f3ebf1f7023ecc3c44cd4c8993a59be/pkg/testutils/docker/docker_utils.go#L244)):*
> ```
> // server. Until the server is successfully restarted and hence write the url
> // to the listenUrlFile, we mark it as fully started.
> ```

This last sentence took me a couple times to understand. Maybe either add a comma before the 'and' or move "we mark it as fully started" to the beginning?
___
*[pkg/testutils/docker/docker_utils.go, line 277 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MqMsVa54kf543LJ3LP9:-MqMsVa54kf543LJ3LPA:b-w20xjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/863fc62c8f3ebf1f7023ecc3c44cd4c8993a59be/pkg/testutils/docker/docker_utils.go#L277)):*
> ```Go
> 			}
> 			return fmt.Errorf("%v\n"+
> 				"HINT: it could be because the init script is erronous, and made the \n "+
> ```

Is there an extra space after the `\n` or is it an intentional indent of the next line?
___
*[pkg/testutils/docker/single_node_docker_test.go, line 32 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MqPszFO7_4fmBayJKvR:-MqPszFO7_4fmBayJKvS:bc1s0z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/863fc62c8f3ebf1f7023ecc3c44cd4c8993a59be/pkg/testutils/docker/single_node_docker_test.go#L32)):*
> ```Go
> }
> 
> // singleNodeDockerTest is consist of two main parts: start the container with
> ```

suggestion: `is consist` => `consists`


<!-- Sent from Reviewable.io -->

2021-12-16 22:02 UTC, ZhouXing19 commented
___
*[pkg/docker/docker_utils.go, line 248 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphDLfj4r6KcSWPzlCy:-Mr4E0dLC8JY5EjHAhbR:bomldto) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L248)):*
Thanks for the suggestion! I'm a bit confused about 

> `fsnotify` is already vendored

Per `build/deploy/Dockerfile`, if we keep it unchanged, the docker image will only contain the cockroach binary, `cockroach.sh` and `libgeos.so`,`libgeos_c.so`. It doesn't even have go installed. So I think the vendored `fsnotify` cannot be used in our case.

Another way is to do , and run a go file that uses `fsnotify` to listen to the desired file. Specifically:
 1. `docker exec roach1 -- microdnf install go`
 2.  `docker exec roach1 -- git clone https://github.com/janeCockroachDB/docker-fsnotify`
 3.  `docker exec roach1 -- cd docker-fsnotify && ./mynofify.go /cockroach init_success` 
(`mynofify.go` is a file that listen to a folder (`/cockroach`) and return either once the desired file (`init_success`) is written, or timeout for 30 seconds) 


<!-- Sent from Reviewable.io -->

2021-12-20 19:52 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder, @rafiss, and @rail)

___
*[pkg/testutils/docker/testdata/single-node-test/docker-entrypoint-initdb.d/foo.txt, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MqV6gaG-l8GU1pcyiqB:-MrONrnsA88XhgERAvhC:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/863fc62c8f3ebf1f7023ecc3c44cd4c8993a59be/pkg/testutils/docker/testdata/single-node-test/docker-entrypoint-initdb.d/foo.txt#L1)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Why is this file needed?
</blockquote></details>

Removed.
___
*[pkg/docker/docker_utils.go, line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphCdFDC_VLGI7vvPga:-MrONuXa0okccrp4WN8x:b-yrw6vd) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L210)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Note: It looks like you missed one `cmd`.
</blockquote></details>

Hmm I'm not sure which `cmd` I'm missing?
___
*[pkg/docker/docker_utils.go, line 248 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphDLfj4r6KcSWPzlCy:-MrOO2YM1D27RfXfzWEP:b4hl7ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L248)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Thanks for the suggestion! I'm a bit confused about 

> `fsnotify` is already vendored

Per `build/deploy/Dockerfile`, if we keep it unchanged, the docker image will only contain the cockroach binary, `cockroach.sh` and `libgeos.so`,`libgeos_c.so`. It doesn't even have go installed. So I think the vendored `fsnotify` cannot be used in our case.

Another way is to do , and run a go file that uses `fsnotify` to listen to the desired file. Specifically:
 1. `docker exec roach1 -- microdnf install go`
 2.  `docker exec roach1 -- git clone https://github.com/janeCockroachDB/docker-fsnotify`
 3.  `docker exec roach1 -- cd docker-fsnotify && ./mynofify.go /cockroach init_success` 
(`mynofify.go` is a file that listen to a folder (`/cockroach`) and return either once the desired file (`init_success`) is written, or timeout for 30 seconds) 
</blockquote></details>

Changed it to 
1. Mount the `docker-fsnotify` go project to the docker container, which listens to the creation of a file 
     under a given path, or exits if timeout.
2. `microdnf install go` in that docker container
3. `go mod tidy` to install dependency of `docker-fsnotify`
4. `go run ./ListenFileCreation.go /cockroach $listenUrlFile` 
___
*[pkg/testutils/docker/docker_utils.go, line 244 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MqMrHaSA2KNwnWiZauJ:-MrONzA32qRWkRQ21hss:b-4m53oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/863fc62c8f3ebf1f7023ecc3c44cd4c8993a59be/pkg/testutils/docker/docker_utils.go#L244)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

> ```
> // server. Until the server is successfully restarted and hence write the url
> // to the listenUrlFile, we mark it as fully started.
> ```

This last sentence took me a couple times to understand. Maybe either add a comma before the 'and' or move "we mark it as fully started" to the beginning?
</blockquote></details>

Done rephrasing. Sorry for the confusion!
___
*[pkg/testutils/docker/docker_utils.go, line 277 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MqMsVa54kf543LJ3LP9:-MrOOgot3i3JCVmvvUMy:b6wsjzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/863fc62c8f3ebf1f7023ecc3c44cd4c8993a59be/pkg/testutils/docker/docker_utils.go#L277)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Is there an extra space after the `\n` or is it an intentional indent of the next line?
</blockquote></details>

Removed it since we're using fsnotify now.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 32 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MqPszFO7_4fmBayJKvR:-MrONpl6CG112nxvsMVr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/863fc62c8f3ebf1f7023ecc3c44cd4c8993a59be/pkg/testutils/docker/single_node_docker_test.go#L32)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

suggestion: `is consist` => `consists`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-20 19:55 UTC, ZhouXing19 commented
Note that I changed the sql query test content -- any tests concerning the "improved docker image that support env var and init scripts" are removed. It's because this PR should be merged before [the PR for improved docker image](https://github.com/cockroachdb/cockroach/pull/70238). Will re-add those removed tests in that PR after this one is merged.





<!-- Sent from Reviewable.io -->

2021-12-22 06:13 UTC, jlinder reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder, @rafiss, and @rail)

___
*[pkg/docker/docker_utils.go, line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphCdFDC_VLGI7vvPga:-MrVaMzjE_N94Qs61fRI:b98skdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L210)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Hmm I'm not sure which `cmd` I'm missing?
</blockquote></details>

I misread the initial comment.

There are two more instances of  `cmd[:]` in a `strings.Join()` below.
___
*[pkg/docker/docker_utils.go, line 248 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphDLfj4r6KcSWPzlCy:-MrVgGfo5wgtpMFdWXuN:by2gps7) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L248)):*
> Thanks for the suggestion! I'm a bit confused about
> >    fsnotify is already vendored

Ah! The key here is to build the `docker-fsnotify` binary before `//pkg/testutils/docker:docker_test` needs it. Then it can be placed in a mounted directory and just run in the container. There is also then no need to re-vendor `fsnotify` in `pkg/testutils/docker/docker-fsnotify`.

In the make world, `docker-fsnotify` would be built in `build/teamcity/cockroach/ci/tests/docker_image.sh` before running `//pkg/testutils/docker:docker_test`. I think in the bazel world, it's possible to make `//pkg/testutils/docker:docker_test` depend on `docker-fsnotify` which will make sure `docker-fsnotify` will be built first. 


<!-- Sent from Reviewable.io -->

2022-01-06 17:27 UTC, ZhouXing19 commented
___
*[pkg/docker/docker_utils.go, line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphCdFDC_VLGI7vvPga:-MskQUmV0TZXzJZSCPCM:b-g72kxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L210)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

I misread the initial comment.

There are two more instances of  `cmd[:]` in a `strings.Join()` below.
</blockquote></details>

Ah right, thank you! Done.


<!-- Sent from Reviewable.io -->

2022-01-06 17:27 UTC, ZhouXing19 commented
___
*[pkg/docker/docker_utils.go, line 248 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MphDLfj4r6KcSWPzlCy:-MskQYsO45KLpDhivpmx:b-1k00l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/db799448e3bf769ae776e09dcf058cb53aa82ad4/pkg/docker/docker_utils.go#L248)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

> Thanks for the suggestion! I'm a bit confused about
> >    fsnotify is already vendored

Ah! The key here is to build the `docker-fsnotify` binary before `//pkg/testutils/docker:docker_test` needs it. Then it can be placed in a mounted directory and just run in the container. There is also then no need to re-vendor `fsnotify` in `pkg/testutils/docker/docker-fsnotify`.

In the make world, 'docker-fsnotify` would be built in `build/teamcity/cockroach/ci/tests/docker_image.sh` before running `//pkg/testutils/docker:docker_test`. I think in the bazel world, it's possible to make `//pkg/testutils/docker:docker_test` depend on `docker-fsnotify` which will make sure `docker-fsnotify` will be built first. 


</blockquote></details>

Yep done adding the docker-fsnotify in #72394. Thank you!


<!-- Sent from Reviewable.io -->

2022-01-06 22:19 UTC, rafiss commented
Looks like there are linting failures to address:
```
        github.com/cockroachdb/cockroach/pkg/testutils/docker: golang.org/x/net/context <- please use "context" instead of "golang.org/x/net/context"

    lint_test.go:1662:
        pkg/testutils/docker/docker_utils.go:38:2: const listenUrlFile should be listenURLFile
    lint_test.go:1662:
        pkg/testutils/docker/docker_utils.go:47:2: struct field contId should be contID
    lint_test.go:1662:
        pkg/testutils/docker/docker_utils.go:173:60: method parameter execId should be execID
    lint_test.go:1662:
        pkg/testutils/docker/docker_utils.go:225:2: var execId should be execID
    lint_test.go:1662:
        pkg/testutils/docker/docker_utils.go:287:9: if block ends with a return statement, so drop this else and outdent its block
    lint_test.go:1662:
        pkg/testutils/docker/docker_utils.go:294:23: method execSqlQuery should be execSQLQuery
    lint_test.go:1662:
        pkg/testutils/docker/docker_utils.go:322:6: func cleanSqlOutput should be cleanSQLOutput
    lint_test.go:1662:
        pkg/testutils/docker/single_node_docker_test.go:176:26: error strings should not be capitalized or end with punctuation or a newline
```

and also the test is failing in Github CI
```
TestSingleNodeDocker/single-node-insecure-mode
    single_node_docker_test.go:137: cannot create container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

2022-01-07 02:26 UTC, ZhouXing19 commented
@rafiss thanks for pointing that out! Fixed for the lint errors except for this one:
```
github.com/cockroachdb/cockroach/pkg/testutils/docker: golang.org/x/net/context <- please use "context" instead of "golang.org/x/net/context"
```
Looks like it's for the `pkg/testutils/docker/BUILD.bazel`. Not sure how to change the line `"@org_golang_x_net//context",` though...
And yeah, I didn't notice the `cannot create container` error in GithubCI. The test did passed the dedicated TC Build Configuration [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_ScratchProjectPutTcExperimentsInHere_JaneDockerImageTest/4061199), but I don't know how to deal with the failed tests (`maybe_stressrace`, `maybe_stress`, `test`, `testrace`). They all failed because the docker deamon is not started. 

@jlinder any idea how to fix this? Thanks!

2022-01-22 02:22 UTC, jlinder requested changes
Thank you for moving `docker-fsnotify` back to `pkg/testutils/docker/docker-fsnotify/`. 

> @jlinder any idea how to fix this? 

Yes. The way to get the docker image tests to not run for `test`, `testrace`, etc. is to use the [go build constraint system](https://pkg.go.dev/go/build#hdr-Build_Constraints). Using the acceptance tests as an example, the things you need to do are:

1. Add these two lines after the copyright comment in `pkg/testutils/docker/single_node_docker_test.go` ([acceptance example](https://github.com/cockroachdb/cockroach/blob/8f253cf360b43a3d2fe6f2780b561e17dc5b1616/pkg/acceptance/test_acceptance.go#L11-L12)):
    ```
    //go:build docker
    // +build docker
    ```
2. Add a `gotags` line to the `docker_test` target in `pkg/testutils/docker/BUILD.bazel` ([acceptance example](https://github.com/cockroachdb/cockroach/blob/8f253cf360b43a3d2fe6f2780b561e17dc5b1616/pkg/acceptance/BUILD.bazel#L57)):
    ```
    gotags = ["docker"],
    ```

There are also some new linter errors:
```
    lint_test.go:1601: pkg/testutils/docker/docker-fsnotify/ListenFileCreation.go:60:21:	defer watcher.Close() <- unchecked error
    lint_test.go:1733: 
        pkg/testutils/docker/docker-fsnotify/ListenFileCreation.go:112:2: redundant return statement (S1023)
    lint_test.go:91: 
        pkg/testutils/docker/docker_utils.go:281:10: github.com/cockroachdb/errors.NewAssertionErrorWithWrappedErrf format %s has arg res of wrong type *github.com/cockroachdb/cockroach/pkg/testutils/docker.execResult
        pkg/testutils/docker/docker-fsnotify/ListenFileCreation.go:52:10: non-wrapped error is passed to fmt.Errorf; use pgerror.Wrap/errors.Wrap/errors.CombineErrors/errors.WithSecondaryError/errors.NewAssertionErrorWithWrappedErrf instead
    lint_test.go:1504: 
        github.com/cockroachdb/cockroach/pkg/testutils/docker/docker-fsnotify: errors <- please use "github.com/cockroachdb/errors" instead of "errors"
    lint_test.go:1504: 
        github.com/cockroachdb/cockroach/pkg/testutils/docker/docker-fsnotify: log <- please use "util/log" instead of "log"
    lint_test.go:1504: 
        github.com/cockroachdb/cockroach/pkg/testutils/docker: golang.org/x/net/context <- please use "context" instead of "golang.org/x/net/context"
```

> Reviewed 1 of 9 files at r7, 2 of 7 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 4 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-:-MtydSfo29ZOcc3Knne0:bovbkgu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder, @rafiss, @rail, and @ZhouXing19)

___
*[-- commits, line 7 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MtyHn9b--Xt4iPbErmJ):*
This can be updated now since #72394 is merged.
___
*[-- commits, line 14 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MtyohWI3WG_v2zQh0oz):*
Could you add a fully formed commit message for this commit? The [PR organization philosophy](https://wiki.crdb.io/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews#PR-organization-philosophy) section of [this wiki page](https://wiki.crdb.io/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews) describes why I'm asking for this.
___
*[pkg/testutils/docker/docker_utils.go, line 272 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MtyG1kO9Tai8ye-fzQZ:-MtyG1kP2Y8eP2Oid9L7:b-eog7z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d6ae2b394402edb8fb03bdf91d04e693ca48358/pkg/testutils/docker/docker_utils.go#L272)):*
> ```Go
> 	var err error
> 
> 	// Run the file which listen to the /cockroach folder until ei
> ```

This comment looks like it is unfinished.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 27 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MtyQ7WRAMykmaKi9yUB:-MtyQ7WRAMykmaKi9yUC:bmfxftn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6125b4b49cc03cdd7a7096108d393bc116d9d5fc/pkg/testutils/docker/single_node_docker_test.go#L27)):*
> ```Go
> )
> 
> const upstreamArtifactsPath = "/home/agent/work/.go/src/github.com/cockroachdb/cockroach/upstream_artifacts"
> ```

Since the docker tests now depend on `pkg/testutils/docker/docker-fsnotify`, the `docker-fsnotify` binary is available locally in the bazel output directories (it's built when the `bazel run //pkg/testutils/docker:docker_test` command is run). 

You can find the binary in the `pkg/testutils/docker/docker-fsnotify/docker-fsnotify_/` directory under the directory returned by the command `bazel info bazel-bin`. (Note: you'll likely need to include one or both of the flags `--config=crosslinux` or `--config=test` when calling `bazel info bazel-bin`.)

Because it's built locally, you'll also want to remove the code from [build/teamcity/cockroach/ci/builds/build_docker_image.sh](https://github.com/cockroachdb/cockroach/blob/8f253cf360b43a3d2fe6f2780b561e17dc5b1616/build/teamcity/cockroach/ci/builds/build_docker_image.sh#L45-L47) that previously built the binary.


<!-- Sent from Reviewable.io -->

2022-01-27 21:42 UTC, ZhouXing19 commented
@jlinder thanks for reviewing!

> The way to get the docker image tests to not run for test, testrace, etc. is to use the go build constraint system.

I've added the build constraint to `pkg/testutils/docker/single_node_docker_test.go` and the gotags to the docker_test target in `pkg/testutils/docker/BUILD.bazel`, but now it keeps failing the `check generated code` test in `Github CI`:
```
diff --git a/pkg/testutils/docker/BUILD.bazel b/pkg/testutils/docker/BUILD.bazel
index 2222ff8a86..7fcce7b48f 100644
--- a/pkg/testutils/docker/BUILD.bazel
+++ b/pkg/testutils/docker/BUILD.bazel
@@ -1,4 +1,4 @@
-load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
+load("@io_bazel_rules_go//go:def.bzl", "go_library")
 go_library(
     name = "testutils_docker",
@@ -13,25 +13,5 @@ go_library(
         "@com_github_docker_docker//client",
         "@com_github_docker_docker//pkg/stdcopy",
         "@com_github_docker_go_connections//nat",
-        "@org_golang_x_net//context",
-    ],
-)
-
-go_test(
-    name = "docker_test",
-    size = "enormous",
-    srcs = ["single_node_docker_test.go"],
-    gotags = ["docker"],
-    data = glob(["testdata/**"]) + [
-        "//pkg/testutils/docker:testdata",
-        "//pkg/testutils/docker/docker-fsnotify:docker-fsnotify",
-    ],
-    embed = [":testutils_docker"],
-    deps = [
-        "//pkg/util/contextutil",
-        "//pkg/util/log",
-        "@com_github_cockroachdb_errors//:errors",
-        "@com_github_docker_docker//client",
-        "@org_golang_x_net//context",
     ],
 )
```

But we do need the `go_test` part to run on bazel, right? Should we make `build/bazelutil/check.sh` ignore `pkg/testutils/docker/BUILD.bazel`?

2022-01-27 21:48 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder, @rafiss, and @rail)

___
*[-- commits, line 7 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MtyHn9b--Xt4iPbErmJ):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

This can be updated now since #72394 is merged.
</blockquote></details>

Done.
___
*[-- commits, line 14 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MtyohWI3WG_v2zQh0oz):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Could you add a fully formed commit message for this commit? The [PR organization philosophy](https://wiki.crdb.io/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews#PR-organization-philosophy) section of [this wiki page](https://wiki.crdb.io/wiki/spaces/CRDB/pages/1411744698/Decomposing+changes+and+updating+PRs+during+reviews) describes why I'm asking for this.
</blockquote></details>

Removed that draft commit.
___
*[pkg/testutils/docker/docker_utils.go, line 272 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MtyG1kO9Tai8ye-fzQZ:-MuSVKBK8svybIdWOoh3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d6ae2b394402edb8fb03bdf91d04e693ca48358/pkg/testutils/docker/docker_utils.go#L272)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

This comment looks like it is unfinished.
</blockquote></details>

Done.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 27 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MtyQ7WRAMykmaKi9yUB:-MuSVNTF6uMooO6PBl7g:b69eq6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6125b4b49cc03cdd7a7096108d393bc116d9d5fc/pkg/testutils/docker/single_node_docker_test.go#L27)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Since the docker tests now depend on `pkg/testutils/docker/docker-fsnotify`, the `docker-fsnotify` binary is available locally in the bazel output directories (it's built when the `bazel run //pkg/testutils/docker:docker_test` command is run). 

You can find the binary in the `pkg/testutils/docker/docker-fsnotify/docker-fsnotify_/` directory under the directory returned by the command `bazel info bazel-bin`. (Note: you'll likely need to include one or both of the flags `--config=crosslinux` or `--config=test` when calling `bazel info bazel-bin`.)

Because it's built locally, you'll also want to remove the code from [build/teamcity/cockroach/ci/builds/build_docker_image.sh](https://github.com/cockroachdb/cockroach/blob/8f253cf360b43a3d2fe6f2780b561e17dc5b1616/build/teamcity/cockroach/ci/builds/build_docker_image.sh#L45-L47) that previously built the binary.

</blockquote></details>

Removed from `build/teamcity/cockroach/ci/builds/build_docker_image.sh` the logic to build the`docker-fsnotify` binary.


<!-- Sent from Reviewable.io -->

2022-02-14 22:07 UTC, jlinder requested changes
I think there's one last change to make. Left a comment below for it.

> Reviewed 1 of 7 files at r9, 8 of 12 files at r15, 3 of 15 files at r16, 2 of 10 files at r19, 10 of 11 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-:-MvuGGgxAqptIRtzEzkB:b-iwm6z5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder, @rafiss, @rail, and @ZhouXing19)

___
*[build/teamcity/cockroach/ci/builds/build_docker_image.sh, line 36 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MumsNPU8rViIKdZnJxc:-MumsNPU8rViIKdZnJxd:bggne7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e492ecd1f8e574b5a3df923cb31edb1f3ee325e9/build/teamcity/cockroach/ci/builds/build_docker_image.sh#L36)):*
> ```Shell
> docker_tag="cockroachdb/cockroach-ci"
> 
> docker build --help
> ```

Looks like this is a stray debugging line.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 83 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MvtoTds7xvFjYMeFcz3:-MvtoTds7xvFjYMeFcz4:b-n8yvts) ([raw file](https://github.com/cockroachdb/cockroach/blob/68dd1e1d8d19591becfc889fb8e25252ce9ec10c/pkg/testutils/docker/single_node_docker_test.go#L83)):*
> ```Go
> 	// run 'bazel info bazel-bin --config=crosslinux' cli command to get the binary
> 
> 	fsnotifyPath := filepath.Join(filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(pwd)))))), "docker-fsnotify")
> ```

This path needs to be updated to use `bazel info bazel-bin --config=crosslinux --config=test` to get the directory under which bazel places the binaries it generates. The `docker-fsnotify` binary should be at  `$(bazel info bazel-bin --config=crosslinux --config=test)/pkg/testutils/docker/docker-fsnotify/docker-fsnotify_/docker-fsnotify`.

Note: the `--config=crosslinux` or `--config=test` options might not be needed on the `bazel info` command. 
___
*[pkg/testutils/docker/single_node_docker_test.go, line 85 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mvtlzs9AqYwzFbniotH:-Mvtlzs9AqYwzFbniotI:ba3bmrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/68dd1e1d8d19591becfc889fb8e25252ce9ec10c/pkg/testutils/docker/single_node_docker_test.go#L85)):*
> ```Go
> 	fsnotifyPath := filepath.Join(filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(pwd)))))), "docker-fsnotify")
> 
> 	if err := os.Chmod(filepath.Join(fsnotifyPath, fsnotifyBinName), 0777); err != nil {
> ```

Why set to `0777`? Is `0755` not enough?


<!-- Sent from Reviewable.io -->

2022-02-15 17:48 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder, @rafiss, and @rail)

___
*[build/teamcity/cockroach/ci/builds/build_docker_image.sh, line 36 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MumsNPU8rViIKdZnJxc:-MvyUXujAKWN9XeDmuxc:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e492ecd1f8e574b5a3df923cb31edb1f3ee325e9/build/teamcity/cockroach/ci/builds/build_docker_image.sh#L36)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Looks like this is a stray debugging line.
</blockquote></details>

Removed.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 83 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MvtoTds7xvFjYMeFcz3:-MvyU_GlAlc69SG9marD:bc28aco) ([raw file](https://github.com/cockroachdb/cockroach/blob/68dd1e1d8d19591becfc889fb8e25252ce9ec10c/pkg/testutils/docker/single_node_docker_test.go#L83)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

This path needs to be updated to use `bazel info bazel-bin --config=crosslinux --config=test` to get the directory under which bazel places the binaries it generates. The `docker-fsnotify` binary should be at  `$(bazel info bazel-bin --config=crosslinux --config=test)/pkg/testutils/docker/docker-fsnotify/docker-fsnotify_/docker-fsnotify`.

Note: the `--config=crosslinux` or `--config=test` options might not be needed on the `bazel info` command. 
</blockquote></details>

We decided to switch back to tracing the file system tree, because that path that`bazel info bazel-bin` gives doesn't contain `docker-fsnotify-bin`.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 85 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-Mvtlzs9AqYwzFbniotH:-MvyUq5VCIVJSIvVIOJ3:b-2fe0io) ([raw file](https://github.com/cockroachdb/cockroach/blob/68dd1e1d8d19591becfc889fb8e25252ce9ec10c/pkg/testutils/docker/single_node_docker_test.go#L85)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Why set to `0777`? Is `0755` not enough?
</blockquote></details>

Removed this `chmod` line.


<!-- Sent from Reviewable.io -->

2022-02-15 17:52 UTC, jlinder approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-:-MvyVT8j6kDvSsVRM7xt:bks4kj3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder, @rafiss, and @rail)

___
*[pkg/testutils/docker/single_node_docker_test.go, line 83 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MvtoTds7xvFjYMeFcz3:-MvyRwuR4N97HeQDMgmC:b-8dt1nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/68dd1e1d8d19591becfc889fb8e25252ce9ec10c/pkg/testutils/docker/single_node_docker_test.go#L83)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

This path needs to be updated to use `bazel info bazel-bin --config=crosslinux --config=test` to get the directory under which bazel places the binaries it generates. The `docker-fsnotify` binary should be at  `$(bazel info bazel-bin --config=crosslinux --config=test)/pkg/testutils/docker/docker-fsnotify/docker-fsnotify_/docker-fsnotify`.

Note: the `--config=crosslinux` or `--config=test` options might not be needed on the `bazel info` command. 
</blockquote></details>

Ah! It turns out the implementation you have is correct after all. I was thrown off by seeing the stray `run 'bazel info ...` comment.


<!-- Sent from Reviewable.io -->

2022-02-15 19:18 UTC, rafiss requested changes
i have a few minor nits. overall looks good!

2022-02-17 17:23 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder, @rafiss, and @rail)

___
*[pkg/testutils/docker/docker-fsnotify/ListenFileCreation.go, line 32 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MrON-bIZj4gj2npIBoP-r27-32:-Mw7gqHt3nLYDqrEizpm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a0a9e68d19c1852b4894e0a6f1e5b55a066ac77/pkg/testutils/docker/docker-fsnotify/ListenFileCreation.go#L32)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: you can make this `defaultTimeout = 30 * time.Second` so you don't have to do the multiplication everywhere else
</blockquote></details>

Done.
___
*[pkg/testutils/docker/docker-fsnotify/BUILD.bazel, line 5 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MtxY3yQPm8Ui1I60Vka-r27-5:-MvyscjY8rW387zQs3vV:b-udsup5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a0a9e68d19c1852b4894e0a6f1e5b55a066ac77/pkg/testutils/docker/docker-fsnotify/BUILD.bazel#L5)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is there any specific reason the file name has capitalization like this? most go files are lowercase and underscores.
</blockquote></details>

Done renaming it.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 83 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MvtoTds7xvFjYMeFcz3:-Mw7grClEmT_iutngAlb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68dd1e1d8d19591becfc889fb8e25252ce9ec10c/pkg/testutils/docker/single_node_docker_test.go#L83)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Ah! It turns out the implementation you have is correct after all. I was thrown off by seeing the stray `run 'bazel info ...` comment.
</blockquote></details>

Done.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 81 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MplZkdVXHvdFV9jJED7-r27-81:-MvypZRw7SSv1cCP3pQi:by8r6lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a0a9e68d19c1852b4894e0a6f1e5b55a066ac77/pkg/testutils/docker/single_node_docker_test.go#L81)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it looks like there are a lot of extra `filepath.Dir` calls by accident.
</blockquote></details>

These are intentional. The pwd is 
```
/home/agent/.cache/bazel/_bazel_agent/40f5e2a2e18a7cdb4cd075f919d8072b/execroot/cockroach/bazel-out/k8-fastbuild-ST-d1e13b6b4354/bin/pkg/testutils/docker/docker_test_/docker_test.runfiles/cockroach/pkg/testutils/docker
```
and the binary we want is saved at 
```
/home/agent/.cache/bazel/_bazel_agent/40f5e2a2e18a7cdb4cd075f919d8072b/execroot/cockroach/bazel-out/k8-fastbuild-ST-d1e13b6b4354/bin/pkg/testutils/docker/docker-fsnotify/docker-fsnotify-bin
```
So we have to go up lots of layers.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 94 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MplZkdVXHvdFV9jJED7-r27-94:-Mw7cs_L1K_Ufy7RI1vP:b7qzpxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a0a9e68d19c1852b4894e0a6f1e5b55a066ac77/pkg/testutils/docker/single_node_docker_test.go#L94)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

more of a dev-inf question: does this work for the bazel sandbox? i thought we'd need to use `testutils.TestDataPath()` similar to how we do for logic tests. cc @jlinder 
</blockquote></details>

It actually doesn't matter here because the mounted `/cockroach/cockroach-data` is eventually empty, so that it can trigger the initialization. 
___
*[pkg/testutils/docker/single_node_docker_test.go, line 253 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MplZkdVXHvdFV9jJED7-r27-253:-Mw7gsbV51sDDQbvXQLm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a0a9e68d19c1852b4894e0a6f1e5b55a066ac77/pkg/testutils/docker/single_node_docker_test.go#L253)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: you can make both of these be `10 * time.Second` and `80 * time.Second`
</blockquote></details>

Done.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 257 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MplZkdVXHvdFV9jJED7-r27-257:-MvyqBuk5guVJOePa6yN:bz6sl6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a0a9e68d19c1852b4894e0a6f1e5b55a066ac77/pkg/testutils/docker/single_node_docker_test.go#L257)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

was the port changed on purpose? normally it defaults to 26257
</blockquote></details>

Ah it's a typo, changed it back to 26257, thanks!
___
*[pkg/testutils/docker/single_node_docker_test.go, line 500 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MplZkdVXHvdFV9jJED7-r27-500:-Mw7gtbaC_znXyC9E5Nd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a0a9e68d19c1852b4894e0a6f1e5b55a066ac77/pkg/testutils/docker/single_node_docker_test.go#L500)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

if you change `serverStartTimeout` as per my earlier comment, then make sure this is converted back to the correct units using `string(serverStartTimeout.Seconds())`
</blockquote></details>

Done.
___
*[pkg/testutils/docker/single_node_docker_test.go, line 543 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-MplZkdVXHvdFV9jJED7-r27-543:-Mw7dl3s8DZMtu-G2WDw:bhzquic) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a0a9e68d19c1852b4894e0a6f1e5b55a066ac77/pkg/testutils/docker/single_node_docker_test.go#L543)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think you should be able to avoid this cleaning step by using `--format` when you query. for example, try these out:
```
./cockroach sql --insecure -e 'select 1,2,3' --format=csv

./cockroach sql --insecure -e 'select 1,2,3' --format=tsv

./cockroach sql --insecure -e 'select 1,2,3' --format=raw

./cockroach sql --insecure -e 'select 1,2,3' --format=records
```

and see which one you find easiest to parse
</blockquote></details>

Thanks! I now added `--format=csv`, but the output still contains extra lines such as `Time:xx ms`, so I kept the `cleanQueryResult` function, but with simpler logic.  



_Code quote:_
```Go
serverStartTimeout
```


<!-- Sent from Reviewable.io -->

2022-02-17 17:34 UTC, rafiss approved these changes
lgtm! nice work!

> Reviewed 1 of 11 files at r23, 9 of 9 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72586#-:-Mw7k1aHDNVAmHEwpAwB:brr1vet)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jlinder, @rafiss, and @rail)



<!-- Sent from Reviewable.io -->

2022-02-17 17:36 UTC, ZhouXing19 commented
Thanks! 
bors r+

2022-02-17 17:36 UTC, ZhouXing19 commented
bors r-

2022-02-17 18:54 UTC, ZhouXing19 commented
bors r+

2022-02-17 21:24 UTC, ZhouXing19 commented
bors r+

2022-02-18 01:28 UTC, merged