indexrec, optester: add index candidate set
cockroachdb/cockroach pull request #72696
Opened 2021-11-12 17:37 UTC by nehageorge

This PR adds logic for walking a normalized expression to find index candidates for recommendation.
See the function comment in `FindIndexCandidates` to learn more about how the potential indexes are determined.

2021-11-12 17:37 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72696)
<!-- Reviewable:end -->

2021-11-15 22:17 UTC, rytaft reviewed
Nice!

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-:-Mo_enyWDrHxireLMzRH:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)

___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_X5sr26lI5Av6-Rqe:-Mo_X5sr26lI5Av6-Rqf:byy1r67) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L21)):*
> ```Go
> 
> // FindIndexCandidateSet returns a map storing potential indexes for each table
> // referenced in a query.
> ```

nit: add another sentence here to introduce the bullet points that follow.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_XzaCBgyZ9M623sn0:-Mo_XzaCBgyZ9M623sn1:brt8dkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L69)):*
> ```Go
> // candidates in the JOIN, EQUAL, and RANGE categories. See rule 5 in
> // FindIndexCandidateSet.
> func (ics *indexCandidateSet) synthesizeIndexCandidates() {
> ```

nit: maybe call this "combineIndexCandidates"?
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo__IjH0oPt_Wz0lNhc:-Mo__IjH0oPt_Wz0lNhd:b-tiw49r) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L176)):*
> ```Go
> // index on all such columns.
> func (ics *indexCandidateSet) addJoinIndexes(expr memo.FiltersExpr) {
> 	for _, col := range expr.OuterCols().ToList() {
> ```

nit: I think you should call `expr.OuterCols().ToList()` once at the beginning of the function and store the result in a variable
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_aM9oECDwrKQQgW6h:-Mo_aM9oECDwrKQQgW6i:byffcrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L215)):*
> ```Go
> 	for t, leftIndexes := range leftIndexMap {
> 		if rightIndexes, found := rightIndexMap[t]; !found {
> 			continue
> ```

nit: instead of having continue here, you can just change the condition to `found`
___
*[pkg/sql/opt/indexrec/index_candidate_set_test.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_czfu0Xe1b4PHbYKM:-Mo_czfu0Xe1b4PHbYKN:b-85s2k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c25c3b38a8169cfb456ffecb2617df24878ac6/pkg/sql/opt/indexrec/index_candidate_set_test.go#L236)):*
> ```Go
> func candidatesAreEqual(leftCandidates, rightCandidates map[cat.Table][][]cat.IndexColumn) bool {
> 	return checkCandidateEquality(leftCandidates, rightCandidates) &&
> 		checkCandidateEquality(rightCandidates, leftCandidates)
> ```

any way to implement this without needing to call this function twice?
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 1987 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_dV7i0YBwgkbty3Fq:-Mo_dV7i0YBwgkbty3Fr:b-npmd3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c25c3b38a8169cfb456ffecb2617df24878ac6/pkg/sql/opt/testutils/opttester/opt_tester.go#L1987)):*
> ```Go
> 
> // IndexCandidates is used with the index-candidates option. It finds index
> // candidates for the SQL statement and formats them as sorted string.
> ```

nit: as sorted string -> as a sorted string ?
___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_eCgZ5_Fd1XCgmJKR:-Mo_eCgZ5_Fd1XCgmJKS:bylzkpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c25c3b38a8169cfb456ffecb2617df24878ac6/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L116)):*
> ```
> (s)
> t2:
> (s)
> ```

should `(i,s)` be here too?

This example also reminds me that `IS` should probably be treated the same way as equality when creating candidates


<!-- Sent from Reviewable.io -->

2021-11-15 22:45 UTC, nehageorge reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @rytaft)

___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_eCgZ5_Fd1XCgmJKR:-Mo_kFUmEr3U_Y0zCX95:bgem9ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c25c3b38a8169cfb456ffecb2617df24878ac6/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L116)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should `(i,s)` be here too?

This example also reminds me that `IS` should probably be treated the same way as equality when creating candidates
</blockquote></details>

Good point about `IS`. The reason `(i,s)` isn't there is because the `expr.On` for joins only seems to consider filters referencing multiple tables. I think this makes sense for our use case, as the reason that we would have an index candidate in the join category would be because it is "joining" tables. Otherwise, it can just be in the regular equality or range categories. In this case, I believe`(i)` should be in the equality category because of `IS`, and so `(s,i)` would be an index, by our rules listed in `FindIndexCandidates`. I will add the code changes for this, and perhaps make it more clear in a comment about the requirements for join candidacy. Let me know if you disagree with this. 


<!-- Sent from Reviewable.io -->

2021-11-16 15:17 UTC, rytaft commented
___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_eCgZ5_Fd1XCgmJKR:-ModIpno8jnePelHnw4e:b-e1933b) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c25c3b38a8169cfb456ffecb2617df24878ac6/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L116)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

Good point about `IS`. The reason `(i,s)` isn't there is because the `expr.On` for joins only seems to consider filters referencing multiple tables. I think this makes sense for our use case, as the reason that we would have an index candidate in the join category would be because it is "joining" tables. Otherwise, it can just be in the regular equality or range categories. In this case, I believe`(i)` should be in the equality category because of `IS`, and so `(s,i)` would be an index, by our rules listed in `FindIndexCandidates`. I will add the code changes for this, and perhaps make it more clear in a comment about the requirements for join candidacy. Let me know if you disagree with this. 
</blockquote></details>

sounds good -- `IS NULL` is technically a join predicate in this case (it's part of the `ON` condition), but I assume the filter was pushed down below the join as part of normalization, so I think it's fine to exclude it from the join predicates (since you're going to include it as an equality predicate anyway)


<!-- Sent from Reviewable.io -->

2021-11-16 15:23 UTC, nehageorge reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @rytaft)

___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_eCgZ5_Fd1XCgmJKR:-ModKi5J11uhiv5W_cw_:bvjjd96) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c25c3b38a8169cfb456ffecb2617df24878ac6/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L116)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

sounds good -- `IS NULL` is technically a join predicate in this case (it's part of the `ON` condition), but I assume the filter was pushed down below the join as part of normalization, so I think it's fine to exclude it from the join predicates (since you're going to include it as an equality predicate anyway)
</blockquote></details>

Oh that would make sense as to why single-table `ON` filters are not included -- they have been pushed down. 


<!-- Sent from Reviewable.io -->

2021-11-16 16:43 UTC, nehageorge reviewed
I added a TODO in `FindIndexCandidates` to consider columns that are used in the statement but do not fall in any other category (for example in `s LIKE "neha"`, s would be in this category). This is discussed in the RFC. The reason I am not handling it now is because I have seen different approaches in academia and don't want to do something arbitrary. Perhaps, in the future, different approaches can be tried on larger datasets, and the one with the largest overall cost benefit can be kept.

2021-11-16 16:50 UTC, nehageorge reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_X5sr26lI5Av6-Rqe:-ModdsYR3cV3JdG38pvL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L21)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: add another sentence here to introduce the bullet points that follow.
</blockquote></details>

Done.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_XzaCBgyZ9M623sn0:-ModduWl2Be-a18gi-Ap:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L69)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: maybe call this "combineIndexCandidates"?
</blockquote></details>

Done.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo__IjH0oPt_Wz0lNhc:-ModdvQt3DIiMrev3g1u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L176)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: I think you should call `expr.OuterCols().ToList()` once at the beginning of the function and store the result in a variable
</blockquote></details>

Done.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_aM9oECDwrKQQgW6h:-ModdwcR0UlVkHZIWLBa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L215)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: instead of having continue here, you can just change the condition to `found`
</blockquote></details>

Done.
___
*[pkg/sql/opt/indexrec/index_candidate_set_test.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_czfu0Xe1b4PHbYKM:-ModdzN-EK7zVoHqJCku:bmhzy0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c25c3b38a8169cfb456ffecb2617df24878ac6/pkg/sql/opt/indexrec/index_candidate_set_test.go#L236)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

any way to implement this without needing to call this function twice?
</blockquote></details>

Yes, good point. I fixed this.
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 1987 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mo_dV7i0YBwgkbty3Fq:-ModdxaG5Sxdgzl6IFiT:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c25c3b38a8169cfb456ffecb2617df24878ac6/pkg/sql/opt/testutils/opttester/opt_tester.go#L1987)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: as sorted string -> as a sorted string ?
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-11-16 18:31 UTC, rytaft commented
The TODO is fine, but in the future we should try to use the same logic we use with LIKE to constrain indexes (I wonder if there's an opportunity in the future to make use of the constraint library for this work...). Basically, if there are no wildcards, LIKE is similar to equality. If the wildcards appear anywhere after the first character, it can be treated as a range predicate (but a TODO is still fine for now).





<!-- Sent from Reviewable.io -->

2021-11-16 19:08 UTC, mgartner requested changes
Is there any harm in treating `LIKE` expression as both range and equality expressions? The optimizer will figure out if it any of the indexes are actually useful.

> Reviewed 4 of 4 files at r1, 5 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-:-Moe3ipEBalFvr6L-EGN:b-9clmut)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nehageorge and @rytaft)

___
*[-- commits, line 15 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe2BM1BwrJ_b6TlI1L):*
nit: typically tests are included in the same commit that adds new functionality, so you could squash these into a single commit.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Modax1F8mQDzj9p3WJE:-Modax1F8mQDzj9p3WJF:b59szbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L60)):*
> ```Go
> // init allocates memory for the maps in the set.
> func (ics *indexCandidateSet) init() {
> 	ics.equalCandidates = make(map[cat.Table][][]cat.IndexColumn)
> ```

nit: you can reduce allocations in some cases by passing the number of tables in the metadata, `numTables := len(ics.md.AllTables())`, to `make`. The map won't always include all tables in the metadata, but the map should never have more tables than in the metadata.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mode6Oj20t2B-cTdboT:-Mode6Oj20t2B-cTdboU:buthqws) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L97)):*
> ```Go
> 		ics.addOrderingIndex(expr.ProvidedPhysical().Ordering)
> 	case *memo.GroupByExpr:
> 		addMultiColumnIndex(expr.GroupingCols.ToList(), nil, ics.md, ics.overallCandidates)
> ```

nit: `nil /* desc */`
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Modf_p4AfvkCZZ8QhON:-Modf_p4AfvkCZZ8QhOO:bttzm67) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L99)):*
> ```Go
> 		addMultiColumnIndex(expr.GroupingCols.ToList(), nil, ics.md, ics.overallCandidates)
> 	case *memo.RangeExpr:
> 		addVariableExprIndexRecursive(expr, ics.md, ics.rangeCandidates)
> ```

A RangeExpr is a tree of AndExprs and comparisons that constrain a single column. I think the recursion into each child at the bottom of this function means that you don't need to specifically match a RangeExpr here, and you can remove `addVariableExprIndexRecursive`.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModgB0dDxr7QIFAfns9:-ModgB0dDxr7QIFAfnsA:bjgr8h5) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L129)):*
> ```Go
> 	}
> 	for i, n := 0, expr.ChildCount(); i < n; i++ {
> 		ics.categorizeIndexCandidates(expr.Child(i))
> ```

Do you need to recurse into children that you've already added indexes for above? For the comparisons, the only case where this might be necessary is complex comparison like `(a + b) > 0`, but that optimizing for that filter would require an expression index, which you'll not be recommending at this point. For the joins, I'm not sure if it is required to recurse into the `On` or not... Perhaps it is if the ON condition has a subquery?
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModjmgtBTKF06dhkNlU:-ModjmgtBTKF06dhkNlV:b-t61gss) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L138)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> // sort, in order of appearance. The first column of each table's index will be
> // ordered ascending. If that is the opposite of the column's ordering in the
> // sort, each subsequent column will also be ordered opposite to its ordering
> // (and vice versa).
> ```
</details>


I don't understand what the "vice versa" case means. Can you elaborate?
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModliZ88KBUEvbp9N_j:-ModliZ88KBUEvbp9N_k:brsb2ac) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L234)):*
> ```Go
> ) {
> 	var leftIndexColSet util.FastIntSet
> 	// Store left columns in map for fast access.
> ```

nit: "map" => "a set"
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Modp5GZ8xsHEoFP2CPl:-Modp5G_EOm1Ksil-buB:b-ovda9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L236)):*
> ```Go
> 	// Store left columns in map for fast access.
> 	for _, leftCol := range leftIndex {
> 		leftIndexColSet.Add(int(leftCol.ColID()))
> ```

nit: You should use the `opt.ColSet` type that wraps a `FastIntSet`.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe1sFb1Bl_SdRbHZGy:-Moe1sFb1Bl_SdRbHZGz:b-rqt6d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a7326fceafbdd803a2d430e4741a7ea8b0523a2/pkg/sql/opt/indexrec/index_candidate_set.go#L43)):*
> ```Go
> // TODO(nehageorge): Add a rule for columns that are referenced in the statement
> // but do not fall into one of these categories. This will be the final case,
> // *memo.VariableExpr. See the papers referenced in this RFC for inspiration:
> ```

I don't understand "This will be the final case, *memo.VariableExpr", can you elaborate?
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 2003 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe6oT179Yd3CXbNkUU:-Moe6oT179Yd3CXbNkUV:b-mcsbax) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/opt_tester.go#L2003)):*
> ```Go
> 		for i, index := range indexes {
> 			var indexSb strings.Builder
> 			indexSb.WriteString("(")
> ```

nit: indenting each index under its table's name might make the output easier to read.
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 2012 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe6Jbx2PHXzM9xKjfH:-Moe6Jbx2PHXzM9xKjfI:b-hwbxcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/opt_tester.go#L2012)):*
> ```Go
> 				if j < (len(index) - 1) {
> 					indexSb.WriteString(", ")
> 				}
> ```

super nit: I think it's cleaner to move this to the top of the loop and change to `if j > 0 { ... }` instead. Feel free to leave as-is if you don't agree.
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 2020 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe5xH_Eqzldwj1Ws9A:-Moe5xH_Eqzldwj1Ws9B:b8dd8dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/opt_tester.go#L2020)):*
> ```Go
> 		tableSb.WriteString(strings.Join(indexesOutput, ""))
> 		tablesOutput[count] = tableSb.String()
> 		count++
> ```

nit: `count` is unnecessary if you initialize `tablesOutput` with length 0 and capacity `len(indexCandidates)` and use `append()` to add strings to it.
___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe771bAHtX [...]

2021-11-16 19:25 UTC, rytaft commented
yea that's a good point... since we're just creating candidates, there's not much harm in creating too many to start





<!-- Sent from Reviewable.io -->

2021-11-16 19:34 UTC, rytaft reviewed
> Reviewed 5 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nehageorge)

___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-MoeDnp0AYihqVWZ66e0:-MoeDnp0AYihqVWZ66e1:b-as5p5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L119)):*
> ```
> (i)
> (s)
> (s, i)
> ```

I feel like the optimizer would be more likely to use `(i, s)` than `(s, i)`. Feels like you're probably going to want to include both as candidates.


<!-- Sent from Reviewable.io -->

2021-11-16 19:46 UTC, nehageorge reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)

___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModgB0dDxr7QIFAfns9:-MoeFTmHDjGftxD7tBAP:b-udsqy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L129)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do you need to recurse into children that you've already added indexes for above? For the comparisons, the only case where this might be necessary is complex comparison like `(a + b) > 0`, but that optimizing for that filter would require an expression index, which you'll not be recommending at this point. For the joins, I'm not sure if it is required to recurse into the `On` or not... Perhaps it is if the ON condition has a subquery?
</blockquote></details>

I believe I do need to recurse for the ON condition. As I was discussing with Becca, after normalization the ON may not contain all the filters, notably the ones that do not reference more than one table. Thus in order to get all the equality/range candidates for these filters, we need to recurse. For comparisons, I agree with you in that I don't think we need to recurse, although I don't see much of a change in performance. I'm open to modifying this to not recurse, however. For sort and group by (that you didn't mention), I believe we need to recurse as well. 
___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe771bAHtX8wpAbpvJ:-MoeD3uv2dGWHlTHc7RI:b-3nl7s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L46)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'd expect `(i, k)` and `(k, i)` to be here too.
</blockquote></details>

Based on the rules, the multi-column equality candidate only gets used when there are candidates in other categories (join, range) that it can be combined with. Although, I could change this so that the multi-column equality candidate gets included on its own no matter what, as I see how this would be beneficial. Is there a reason why you expect both `(i, k)` and `(k, i)`? Here it seems simple to construct all possible multi-column equality candidates because there are only two columns, but if this was more, the number of possible column permutations would increase quite fast. I'm still open to including all permutations, though, as in practice we shouldn't have too many columns, but wanted to note that this is something to be considered.
___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe7UJ_6Tloc2CmMBuI:-MoeEP5q-6kIA1O-HTAS:b-3mdly0) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L95)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't see what `tf.f::STRING NOT LIKE t2.i::STRING` is testing here - only an expression index could help satisfy this predicate.
</blockquote></details>

The reason I included this is because I wanted to show a case where there is an `expr.On` join filter that isn't any other type of filter (equality, range), and ensure that its candidates were still created. Although this would change if we include like in the equal/range candidates... I'd need another way to test this.


<!-- Sent from Reviewable.io -->

2021-11-16 19:52 UTC, nehageorge reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @rytaft)

___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-MoeDnp0AYihqVWZ66e0:-MoeI4WXE5ksl25d_E6r:b-jr8a33) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L119)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I feel like the optimizer would be more likely to use `(i, s)` than `(s, i)`. Feels like you're probably going to want to include both as candidates.
</blockquote></details>

Interesting. I was under the impression that since order doesn't matter for `GROUP BY`, any order would suffice. But I'm not too sure about how the optimizer handles this. Are you suggesting that, since order is not maintained in `memo.GroupByExpr`, I construct all possible column permutations?


<!-- Sent from Reviewable.io -->

2021-11-16 19:54 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nehageorge and @rytaft)

___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModgB0dDxr7QIFAfns9:-MoeHz1TBiCSgbvNrl41:b-kwud2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L129)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

I believe I do need to recurse for the ON condition. As I was discussing with Becca, after normalization the ON may not contain all the filters, notably the ones that do not reference more than one table. Thus in order to get all the equality/range candidates for these filters, we need to recurse. For comparisons, I agree with you in that I don't think we need to recurse, although I don't see much of a change in performance. I'm open to modifying this to not recurse, however. For sort and group by (that you didn't mention), I believe we need to recurse as well. 
</blockquote></details>

In the case you discussed with Becca, I believe the filters would be removed from the ON condition and pushed into the inputs of the joins, not necessarily pushed filter into the ON condition. I think that's only possible if the ON condition has a subquery, but I'm not sure.
___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe771bAHtX8wpAbpvJ:-MoeIEiP15QX3lBfukCk:b5gagbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L46)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

Based on the rules, the multi-column equality candidate only gets used when there are candidates in other categories (join, range) that it can be combined with. Although, I could change this so that the multi-column equality candidate gets included on its own no matter what, as I see how this would be beneficial. Is there a reason why you expect both `(i, k)` and `(k, i)`? Here it seems simple to construct all possible multi-column equality candidates because there are only two columns, but if this was more, the number of possible column permutations would increase quite fast. I'm still open to including all permutations, though, as in practice we shouldn't have too many columns, but wanted to note that this is something to be considered.
</blockquote></details>

Right, we'd only need one of those indexes, and the order wouldn't matter for equality.
___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe7UJ_6Tloc2CmMBuI:-MoeJ-GRDH73yu6UgXKd:bwzsmk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L95)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

The reason I included this is because I wanted to show a case where there is an `expr.On` join filter that isn't any other type of filter (equality, range), and ensure that its candidates were still created. Although this would change if we include like in the equal/range candidates... I'd need another way to test this.
</blockquote></details>

Oh I see. How is this working? I don't see where `t1.f` is added to the index candidate set.


<!-- Sent from Reviewable.io -->

2021-11-16 20:00 UTC, nehageorge reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @rytaft)

___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModgB0dDxr7QIFAfns9:-MoeJaOtETmlAXNQ2d4t:b-9tz3vz) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L129)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

In the case you discussed with Becca, I believe the filters would be removed from the ON condition and pushed into the inputs of the joins, not necessarily pushed filter into the ON condition. I think that's only possible if the ON condition has a subquery, but I'm not sure.
</blockquote></details>

```
"I believe the filters would be removed from the ON condition and pushed into the inputs of the joins, not necessarily pushed filter into the ON condition."
```
Yes, that is what I was referring to, sorry if I was unclear. This is why I believe you need to recurse on the children of the `expr`, although you may not need to recurse specifically on the `expr.On` (which I now realize is what you were probably referring to). Although I would think that since there is the potential complexity of a subquery, it is best to leave as is.
___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe771bAHtX8wpAbpvJ:-MoeJWFKDFsCQyTPTzQc:b-pbdqz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L46)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Right, we'd only need one of those indexes, and the order wouldn't matter for equality.
</blockquote></details>

Agreed.
___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe7UJ_6Tloc2CmMBuI:-MoeKREqCL4pV8HVD3Oh:biqyehe) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L95)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Oh I see. How is this working? I don't see where `t1.f` is added to the index candidate set.
</blockquote></details>

`ti.f` is a join candidate, since it is referenced in a multi-table join filter. 


<!-- Sent from Reviewable.io -->

2021-11-16 20:17 UTC, nehageorge reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @rytaft)

___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModgB0dDxr7QIFAfns9:-MoeO1iV39FnI3qf2LgH:bb0pavp) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L129)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

```
"I believe the filters would be removed from the ON condition and pushed into the inputs of the joins, not necessarily pushed filter into the ON condition."
```
Yes, that is what I was referring to, sorry if I was unclear. This is why I believe you need to recurse on the children of the `expr`, although you may not need to recurse specifically on the `expr.On` (which I now realize is what you were probably referring to). Although I would think that since there is the potential complexity of a subquery, it is best to leave as is.
</blockquote></details>

Here's an example of a case with a subquery: 
```
SELECT * FROM t1 JOIN t2 ON ((SELECT COUNT(*) FROM t1 JOIN t2 ON t1.k = t2.k WHERE t1.f > 3) = 1);
```
We'd want to recurse into `expr.On` to get t1.f as a range candidate.


<!-- Sent from Reviewable.io -->

2021-11-16 20:24 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @rytaft)

___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe7UJ_6Tloc2CmMBuI:-MoePwUBAyvQA_9KAvw6:b-pmx7bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L95)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

`ti.f` is a join candidate, since it is referenced in a multi-table join filter. 
</blockquote></details>

I see - join filters just consider outer columns. :+1: 


<!-- Sent from Reviewable.io -->

2021-11-16 20:34 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)

___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-MoeDnp0AYihqVWZ66e0:-MoeRpHK5k-7C6EwlWgK:bxbrmfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L119)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

Interesting. I was under the impression that since order doesn't matter for `GROUP BY`, any order would suffice. But I'm not too sure about how the optimizer handles this. Are you suggesting that, since order is not maintained in `memo.GroupByExpr`, I construct all possible column permutations?
</blockquote></details>

This isn't a GROUP BY -- this is the JOIN query with the IS NULL filter that gets pushed down below the join. I just think you might want to consider putting equality columns *before* join columns, since the optimizer may not be able to use the index without first constraining on the equality columns.


<!-- Sent from Reviewable.io -->

2021-11-16 20:42 UTC, nehageorge reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @rytaft)

___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-MoeDnp0AYihqVWZ66e0:-MoeT5AC5kBFfxzkYnNC:b-uarf5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L119)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This isn't a GROUP BY -- this is the JOIN query with the IS NULL filter that gets pushed down below the join. I just think you might want to consider putting equality columns *before* join columns, since the optimizer may not be able to use the index without first constraining on the equality columns.
</blockquote></details>

Oh sorry, my bad, I was thinking of the wrong test. I see your point. Do you think we should construct both `J + EQ` and `EQ + J`, or just the latter? This configuration was taken from past published work, so maybe it makes sense to do both, as you initially suggested. By extension, I think it also makes sense to consider `EQ + J + R` in addition to `J + EQ + R` (which is already done).


<!-- Sent from Reviewable.io -->

2021-11-16 21:37 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)

___
*[pkg/sql/opt/testutils/opttester/testdata/index-candidates, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-MoeDnp0AYihqVWZ66e0:-MoeecH68iFin3lXngO_:b-w4rgj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/testdata/index-candidates#L119)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

Oh sorry, my bad, I was thinking of the wrong test. I see your point. Do you think we should construct both `J + EQ` and `EQ + J`, or just the latter? This configuration was taken from past published work, so maybe it makes sense to do both, as you initially suggested. By extension, I think it also makes sense to consider `EQ + J + R` in addition to `J + EQ + R` (which is already done).
</blockquote></details>

I'm not sure if `J + EQ` will be useful, but to Marcus' point, we'll only recommend the indexes that are used by the optimizer anyway, so there's not a huge downside to including both in the candidate set. You could start by including both and then collect some stats to see if the `J + EQ` index is ever selected (and if not, remove it from the code). And you're right, we'll also want to consider `EQ + J + R` in addition to `J + EQ + R`.


<!-- Sent from Reviewable.io -->

2021-11-17 16:41 UTC, nehageorge reviewed
Good point. For this PR, I'm going to leave `LIKE` out. I think it's more focused on getting the foundational logic merged. In the future, the expressions we consider will likely be modified, and I will consider `LIKE` then. See the TODO for `FindIndexCandidates`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-:-Moik4044dlv0lno2dfD:b-bjm07q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @rytaft)

___
*[-- commits, line 15 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe2BM1BwrJ_b6TlI1L):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: typically tests are included in the same commit that adds new functionality, so you could squash these into a single commit.
</blockquote></details>

Good to know, fixed.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Modax1F8mQDzj9p3WJE:-Moii5hV7dqotxUYvNk2:bv0jxid) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L60)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you can reduce allocations in some cases by passing the number of tables in the metadata, `numTables := len(ics.md.AllTables())`, to `make`. The map won't always include all tables in the metadata, but the map should never have more tables than in the metadata.
</blockquote></details>

True, done.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Mode6Oj20t2B-cTdboT:-Moii7tJ0ENvzT9tTkjv:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L97)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `nil /* desc */`
</blockquote></details>

Fixed.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Modf_p4AfvkCZZ8QhON:-Moii92b6_Bp87-q4WUJ:b18glkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L99)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

A RangeExpr is a tree of AndExprs and comparisons that constrain a single column. I think the recursion into each child at the bottom of this function means that you don't need to specifically match a RangeExpr here, and you can remove `addVariableExprIndexRecursive`.
</blockquote></details>

Good point, I removed the function. Fixed.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModgB0dDxr7QIFAfns9:-MoiiNV1D9AHL7QSGMTX:bapnivq) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L129)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

Here's an example of a case with a subquery: 
```
SELECT * FROM t1 JOIN t2 ON ((SELECT COUNT(*) FROM t1 JOIN t2 ON t1.k = t2.k WHERE t1.f > 3) = 1);
```
We'd want to recurse into `expr.On` to get t1.f as a range candidate.
</blockquote></details>

I also thought of an obscure case where we'd want to recurse for comparison cases: `(a < b) = (b  < c)'. Without recursion, we would hit the equality condition, not match any columns, and return -- which would be incorrect. So I think it is best to leave the function recursion as is, with recursion on an expression's children in every case.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModjmgtBTKF06dhkNlU:-Moij5Rg9oU8jv-tY82S:b-1eh3wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L138)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> ```
> // sort, in order of appearance. The first column of each table's index will be
> // ordered ascending. If that is the opposite of the column's ordering in the
> // sort, each subsequent column will also be ordered opposite to its ordering
> // (and vice versa).
> ```

I don't understand what the "vice versa" case means. Can you elaborate?
</blockquote></details>

Sure, done.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModliZ88KBUEvbp9N_j:-Moij7ScAk8KMm0YUkdH:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L234)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "map" => "a set"
</blockquote></details>

Fixed.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Modp5GZ8xsHEoFP2CPl:-Moij99oBKBJwCZKEqNM:bkrfyym) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L236)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: You should use the `opt.ColSet` type that wraps a `FastIntSet`.
</blockquote></details>

This would work if we had the `opt.ColumnID` which comes from the metadata. At this point, we only have the `cat.StableID`, so I believe it makes sense to just use `FastIntSet`.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe1sFb1Bl_SdRbHZGy:-Moii18VADs3R05NdQZT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a7326fceafbdd803a2d430e4741a7ea8b0523a2/pkg/sql/opt/indexrec/index_candidate_set.go#L43)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't understand "This will be the final case, *memo.VariableExpr", can you elaborate?
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 2003 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe6oT179Yd3CXbNkUU:-Moijd3DBrRjWhcl5lvR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/opt_tester.go#L2003)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: indenting each index under its table's name might make the output easier to read.
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 2012 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe6Jbx2PHXzM9xKjfH:-Moijdwq5_bXTK6IT4CD:brkno94) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/opt_tester.go#L2012)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

super nit: I think it's cleaner to move this to the top of the loop and change to `if j > 0 { ... }` instead. Feel free to leave as-is if you don't agree.
</blockquote></details>

I agree, done.
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 2020 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Moe5xH_Eqzldwj1Ws9A:-MoijgPTAvVKdJx3FMHh:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/963a20e59407aaafbf45d35cc41a40384d977da1/pkg/sql/opt/testutils/opttester/opt_tester.go#L2020)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `count` is unnecessary if you initialize `tablesOutput` with length 0 and cap [...]

2021-11-17 18:54 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-:-MojErLK2QNr1Us90f8p:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)



<!-- Sent from Reviewable.io -->

2021-11-19 19:58 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :tada: 

> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-:-MotlnefCImS9fvQA7pj:by6fmpn)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @nehageorge)

___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-ModgB0dDxr7QIFAfns9:-MotjuNg33lzMzWv3Oxl:bhlduk) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L129)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

I also thought of an obscure case where we'd want to recurse for comparison cases: `(a < b) = (b  < c)'. Without recursion, we would hit the equality condition, not match any columns, and return -- which would be incorrect. So I think it is best to leave the function recursion as is, with recursion on an expression's children in every case.
</blockquote></details>

Sounds good to me. Note, though, that in the `(a < b) = (b < c)` case - only an expression index could be used to speed up this filter.
___
*[pkg/sql/opt/indexrec/index_candidate_set.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72696#-Modp5GZ8xsHEoFP2CPl:-Motkfcd74CRi1Nuhdz0:bzhw5hd) ([raw file](https://github.com/cockroachdb/cockroach/blob/882a151a2e38446bd6dcf3aa5da820a68a944102/pkg/sql/opt/indexrec/index_candidate_set.go#L236)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

This would work if we had the `opt.ColumnID` which comes from the metadata. At this point, we only have the `cat.StableID`, so I believe it makes sense to just use `FastIntSet`.
</blockquote></details>

Oh I see. I mistakenly thought that `leftCol.ColID()` returned an `opt.ColumnID`. 


<!-- Sent from Reviewable.io -->

2021-11-19 20:04 UTC, nehageorge commented
TFTRs!

bors r+

2021-11-19 21:24 UTC, merged