kvprober: add feature to bypass admission queue
cockroachdb/cockroach pull request #72748
Opened 2021-11-15 14:54 UTC by dasrirez

When users run workloads that overload the CPU, health check tools like
kvprober fail to have their requests processed in time, which results in
false alarms for cockroach cloud dedicated clusters. To overcome this
problem, kvprober should be able to bypass the admission queue so that
health checks can continue being processed even under high CPU stress.

This commit adds a new cluster setting for kvprober that determines if
the admission queue should be bypassed. It modifies the admission of kv
work so that work sourced from ROOT_KV is bypassed. It also adds new
functions to kv.DB and kv.Txn to support this intent.

Release note: None

2021-11-15 14:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72748)
<!-- Reviewable:end -->

2021-11-15 15:38 UTC, dasrirez commented
Oh I see. If that's the case then I believe this PR is always going to be bypassing admission queue. I'll have to change the implementation around for that. Will update once that is done, thanks.

2021-11-15 15:53 UTC, tbg commented
@joshimhoff isn't the contract for Serverless that an individual user should not be able to saturate a KV node? If that is happening, that node will be effectively unresponsive for all tenants. So why are we allowing kvprober to "not see" that?

What I was expecting is that when running a CC-**Dedicated** cluster, we would let kvprober bypass the queues. For serverless, it should go through admission control like any tenant would.

2021-11-15 16:29 UTC, joshimhoff commented
@tbg: I agree with everything you are saying, yes. I made an error when I wrote up https://github.com/cockroachdb/cockroach/pull/72748#issuecomment-969025976. I have fixed it now. Thanks!

2021-11-15 18:13 UTC, dasrirez commented
Before updating this PR I just wanted to double check my understanding here.

Right now, on master, this is how kv work is admitted (based on source):
```
OTHER -> bypass
ROOT_KV -> not handled
```
and in the future
```
OTHER -> bypass
ROOT_KV -> no bypass
```

- To bypass keep using `OTHER` as the source
- To not bypass, set `ROOT_KV` as the source in kvprober, change `AdmitKVWork` to not bypass this source (would there be any problems with this? `gc_queue` and `backup_processor` use this source).

2021-11-16 08:54 UTC, knz reviewed
Sorry before this review can go through in KV, we need to be clear on terminology: What does the term "root kv" even mean?

(I only know of one "root" - the SQL user called `root`. This is a KV-only change so I don't think we care about which SQL user is sending the command?)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-:-MobwzSH5ki3ciVIUi-g:bvmrjh9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-11-16 14:02 UTC, joshimhoff commented
@knz: We are talking about `roachpb.AdmissionHeader_ROOT_KV`. See here: https://github.com/cockroachdb/cockroach/issues/68732#issuecomment-923157212, where @sumeerbhola uses this language.

2021-11-18 14:35 UTC, sumeerbhola requested changes
> Reviewed 1 of 7 files at r1, 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dasrirez and @joshimhoff)

___
*[pkg/kv/db.go, line 826 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-MonQSlXAnDRHRZineN2:-MonQSlXAnDRHRZineN3:bd1zvic) ([raw file](https://github.com/cockroachdb/cockroach/blob/653f9a5303a371864c3c051a8af5577dbb483c79/pkg/kv/db.go#L826)):*
> ```Go
> }
> 
> // TxnRootKV is the same as Txn but for use by root kv sources.
> ```

"root kv" is not a well known term, and I defined it only for use in admission control, so this comment should be something like

// TxnRootKV is the same as Txn, but specifically represents a request originating within KV, and that is at the root of the tree of requests.
// Do not use this for executing work originating in SQL. This distinction only affects admission control. See AdmissionHeader_Source for more details. 
___
*[pkg/kv/txn.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-MonRZax53xdoVWmee9F:-MonRZax53xdoVWmee9G:b-q6ymzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/653f9a5303a371864c3c051a8af5577dbb483c79/pkg/kv/txn.go#L153)):*
> ```Go
> // NewTxnRootKV is like NewTxn but suitable for use by root kv systems. Note
> // that this initializes Txn.admissionHeader to specify that the source is
> // ROOT_KV.
> ```

Similarly needs a longer comment like `TxnRootKV`
___
*[pkg/kv/kvprober/settings.go, line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-MonS82h4P1qjrJfpxPL:-MonS82h4P1qjrJfpxPM:b-t2poy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/653f9a5303a371864c3c051a8af5577dbb483c79/pkg/kv/kvprober/settings.go#L22)):*
> ```Go
> // kv.prober.bypass_admission_control controls whether kvprober's requests
> // should bypass kv layer's admission control queues. This ensures that kvprober
> // can continue to perform checks even if the cluster's CPU is overloaded.
> ```

"This ensures ... can continue to perform checks even if the cluster's CPU is overloaded" is not clear to me.
What ensures?
A running kvprober is always performing checks.

Is this trying to say:
Setting this value to true ensures that kvprober will not be significantly affected if the cluster is overloaded.


<!-- Sent from Reviewable.io -->

2021-11-18 16:05 UTC, dasrirez reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff and @sumeerbhola)

___
*[pkg/kv/db.go, line 826 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-MonQSlXAnDRHRZineN2:-Monk-Af03A4zYzRTWBq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/653f9a5303a371864c3c051a8af5577dbb483c79/pkg/kv/db.go#L826)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

"root kv" is not a well known term, and I defined it only for use in admission control, so this comment should be something like

// TxnRootKV is the same as Txn, but specifically represents a request originating within KV, and that is at the root of the tree of requests.
// Do not use this for executing work originating in SQL. This distinction only affects admission control. See AdmissionHeader_Source for more details. 


</blockquote></details>

Done.
___
*[pkg/kv/txn.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-MonRZax53xdoVWmee9F:-Monk5N25qBWA5-FjVh-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/653f9a5303a371864c3c051a8af5577dbb483c79/pkg/kv/txn.go#L153)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Similarly needs a longer comment like `TxnRootKV`
</blockquote></details>

Done.
___
*[pkg/kv/kvprober/settings.go, line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-MonS82h4P1qjrJfpxPL:-MonkGQFAzD8KXrR4QbJ:b7lueck) ([raw file](https://github.com/cockroachdb/cockroach/blob/653f9a5303a371864c3c051a8af5577dbb483c79/pkg/kv/kvprober/settings.go#L22)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

"This ensures ... can continue to perform checks even if the cluster's CPU is overloaded" is not clear to me.
What ensures?
A running kvprober is always performing checks.

Is this trying to say:
Setting this value to true ensures that kvprober will not be significantly affected if the cluster is overloaded.
</blockquote></details>

Done. Thanks, this is much better worded. Originally the comment was written with the thought that kvprober's requests were being dropped and that the CPU was the sole resource factor for it, but that is not the case!


<!-- Sent from Reviewable.io -->

2021-11-18 17:45 UTC, sumeerbhola reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> , except for the `kvprober` changes, that I didn't look at

> Reviewed 1 of 6 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-:-Moo8ZmDEbxMySyeDL_6:b-ou7a9g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @joshimhoff and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-11-18 22:39 UTC, joshimhoff reviewed
Looks good. Mostly I have some Qs for Sumeer / KV.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-:-MopBHZy0lVjhcbYQhXD:b-uncdzh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dasrirez, @joshimhoff, and @sumeerbhola)

___
*[-- commits, line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop5BWs-do-4FdnB8Eh):*
nit: It's not really about CPU scaling specifically. Maybe change this up to say: "since the user owns capacity planning" & "When some hardware resource is overloaded in serverless clusters".
___
*[-- commits, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop0z94-4d8Zrwad_XZ):*
Darius: You say the following:

> To not bypass, set `ROOT_KV` as the source and have `AdmitKVWork` not bypass admission for it. Would there be any problems with this? `gc_queue` and `backup_processor` use `ROOT_KV` as their source. Should the change for `AdmitKVWork` be left for later?

I think admission control is already being applied to requests with `roachpb.AdmissionHeader_ROOT_KV`. This is what this comment from @tbg  suggests to me:

> Looks like we can "just" teach kvprober to populate the AdmissionHeader for the BatchRequests it sends (to ROOT_KV) https://github.com/cockroachdb/cockroach/blob/30ab2e1ea8a7c862270bcad56bddcda02bab95c9/pkg/roachpb/api.pb.go#L6786-L6815
and then cockroach/pkg/server/node.go should do the right thing (apply admission control).

(https://github.com/cockroachdb/cockroach/issues/68732#issuecomment-927928426)

OTOH, this comment from @sumeerbhola sort of suggests the opposite thing to me: 

> But I think it is worth adding a code comment in that code in node.go that I pointed to earlier that once we start using roachpb.AdmissionHeader_ROOT_KV and subjecting it to admission control it may cause kvprober to no longer bypass admission control.

> https://github.com/cockroachdb/cockroach/issues/68732#issuecomment-923157212

So I'm a little confused. Darius, are you confused? Or does this all make sense to you?

If admission control IS already being applied to requests with `roachpb.AdmissionHeader_ROOT_KV`, we need not make changes to `AdmitKVWork`, and we are also not changing the behavior of existing stuff like `gc_queue`.

I also can't find `AdmitKVWork` in the codebase. Can you provide a link, Darius?
___
*[pkg/kv/txn.go, line 103 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop-eehE3fWGnqbdHLq:-Mop-eehE3fWGnqbdHLr:b-e3e4oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/txn.go#L103)):*
> ```Go
> // NewTxn returns a new RootTxn.
> // Note: for SQL usage, prefer NewTxnWithSteppingEnabled() below.
> // Note: for KV usage, prefer NewTxnRootKV() below.
> ```

@sumeerbhola and/or KV folks: Is this generally good guidance? My understanding is that using `NewTxnRootKV` means using `roachpb.AdmissionHeader_ROOT_KV`  which means admission control being applied. But for some KV work such as node liveness heartbeats, we do NOT want to apply admission control. Right? Should this comment read something like this?

```
// Note: for KV usage on which admission control should be applied, prefer NewTxnRootKV() below.
```

Same comment re: the doc strings above `NewTxnRootKV` and `TxnRootKV`.

Actually same comment re: the names of those functions. Should they be clearer about the fact that admission control will be applied, or do users not need that detail? Maybe this is work for later.
___
*[pkg/kv/kvprober/kvprober.go, line 298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop8lbW3pvhG_c7YDWe:-Mop8lbW3pvhG_c7YDWf:b-15lehb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/kvprober.go#L298)):*
> ```Go
> 		// TODO(josh): Trace the probes.
> 		f := ops.Read(step.Key)
> 		if bypassAdmissionControl.Get(&p.settings.SV) {
> ```

Can you add a short comment about what these different functions lead to in terms of what admission control header is added / whether admission control is actually applied?
___
*[pkg/kv/kvprober/kvprober.go, line 353 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop9C8J6qNhdYE-WoFt:-Mop9C8J6qNhdYE-WoFu:b2gi5a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/kvprober.go#L353)):*
> ```Go
> 		// clean it up.
> 		f := ops.Write(step.Key)
> 		if bypassAdmissionControl.Get(&p.settings.SV) {
> ```

I'm wondering if there is a way to make this a little more readable while still allowing us to write the unit tests you have written. I don't have a suggestion yet, but I'm going to look at this with fresh eyes tomorrow morning!
___
*[pkg/kv/kvprober/kvprober_test.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop8g0jAv57t_YWGek5:-Mop8g0jAv57t_YWGek6:bloibqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/kvprober_test.go#L56)):*
> ```Go
> 	})
> 
> 	t.Run("happy path with bypass", func(t *testing.T) {
> ```

nit: "happy path with bypass cluster setting overriden".
___
*[pkg/kv/kvprober/kvprober_test.go, line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop6RKy2OOJ0Mn-6Jg9:-Mop6RKy2OOJ0Mn-6JgA:bdhcmmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/kvprober_test.go#L70)):*
Can you add a comment here noting that the `planner` always bypasses admission control intentionally?

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvprober/planner.go#L221

I think this is logical. Say something like this:

> Queries from the `planner` bypass admission control, regardless of what `kv.prober.bypass_admission_control.enabled` is set to. Operators would like to get paged due to probes failing in an overload situation, not the `planner` failing. The `planner` is an implementation detail of `kvprober`, and tho it being broken is not desired as (i) it hurts alerting coverage & (i) it prob does indicate an issue with the cluster, the signal of cluster health that is most useful to operators is failing probes, as this signal reflects the "size" of the outage, by taking measurements across the keyspace.
___
*[pkg/kv/kvprober/kvprober_test.go, line 279 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop8H0NAxxPC9mUAu9g:-Mop8H0NAxxPC9mUAu9h:bbyhqi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/kvprober_test.go#L279)):*
> ```Go
> ) error {
> 	if m.bypass {
> 		m.t.Error("root kv txn used but bypass is set")
> ```

No change requested: CRDB doesn't use gomock today IIUC. A good refactor for one of us to do sometime is replace these mocks with some gomock mocks!
___
*[pkg/kv/kvprober/settings.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop3bB1CNvwDch_9GiS:-Mop3bB1CNvwDch_9GiT:b-nhvfqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/settings.go#L23)):*
> ```Go
> // should bypass kv layer's admission control. Setting this value to true
> // ensures that kvprober will not be significantly affected if the cluster is
> // overloaded.
> ```

Can you add a little more about why one might set this to true vs. false? The bit you have in the commit description about serverless vs. dedicated and who owns scaling is want I want to be clear to our future selves about!
___
*[pkg/kv/kvprober/settings.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop3LNZ5T7F8tMQ6VUQ:-Mop3LNZ5T7F8tMQ6VUR:bqiq381) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/settings.go#L27)):*
> ```Go
> 	"kv.prober.bypass_admission_control.enabled",
> 	"set to bypass admission control queue for [...]

2021-11-22 15:51 UTC, dasrirez reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dasrirez, @joshimhoff, @sumeerbhola, and @tbg)

___
*[-- commits, line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop5BWs-do-4FdnB8Eh):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

nit: It's not really about CPU scaling specifically. Maybe change this up to say: "since the user owns capacity planning" & "When some hardware resource is overloaded in serverless clusters".
</blockquote></details>

Done.
___
*[-- commits, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop0z94-4d8Zrwad_XZ):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

Darius: You say the following:

> To not bypass, set `ROOT_KV` as the source and have `AdmitKVWork` not bypass admission for it. Would there be any problems with this? `gc_queue` and `backup_processor` use `ROOT_KV` as their source. Should the change for `AdmitKVWork` be left for later?

I think admission control is already being applied to requests with `roachpb.AdmissionHeader_ROOT_KV`. This is what this comment from @tbg  suggests to me:

> Looks like we can "just" teach kvprober to populate the AdmissionHeader for the BatchRequests it sends (to ROOT_KV) https://github.com/cockroachdb/cockroach/blob/30ab2e1ea8a7c862270bcad56bddcda02bab95c9/pkg/roachpb/api.pb.go#L6786-L6815
and then cockroach/pkg/server/node.go should do the right thing (apply admission control).

(https://github.com/cockroachdb/cockroach/issues/68732#issuecomment-927928426)

OTOH, this comment from @sumeerbhola sort of suggests the opposite thing to me: 

> But I think it is worth adding a code comment in that code in node.go that I pointed to earlier that once we start using roachpb.AdmissionHeader_ROOT_KV and subjecting it to admission control it may cause kvprober to no longer bypass admission control.

> https://github.com/cockroachdb/cockroach/issues/68732#issuecomment-923157212

So I'm a little confused. Darius, are you confused? Or does this all make sense to you?

If admission control IS already being applied to requests with `roachpb.AdmissionHeader_ROOT_KV`, we need not make changes to `AdmitKVWork`, and we are also not changing the behavior of existing stuff like `gc_queue`.

I also can't find `AdmitKVWork` in the codebase. Can you provide a link, Darius?
</blockquote></details>

Here is [`AdmitKVWork`](https://github.com/dasrirez/cockroach/blob/578ffd0c3646eb37e35a466f788305f142f2d2d2/pkg/kv/kvserver/store.go#L3159). Looking at how `bypassAdmission` gets set here, I'm assuming that `roachpb.AdmissionHeader_ROOT_KV` is not a factor. I wanted to change the behaviour of this function so that work from `ROOT_KV` ~does~ doesn't bypass admission control, but I noticed there are other systems that are currently using `ROOT_KV` as their source and they may not be ready for undergoing admission control.
___
*[pkg/kv/kvprober/kvprober.go, line 298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop8lbW3pvhG_c7YDWe:-Mp7JKgj8wDYP4sMIcF5:b-xqz1yf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/kvprober.go#L298)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

Can you add a short comment about what these different functions lead to in terms of what admission control header is added / whether admission control is actually applied?
</blockquote></details>

Done. Comments for `Txn` and `TxnRootKV` have been added to the interface.
___
*[pkg/kv/kvprober/kvprober_test.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop8g0jAv57t_YWGek5:-Mp7JfYXDq3VtcRSweCH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/kvprober_test.go#L56)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

nit: "happy path with bypass cluster setting overriden".
</blockquote></details>

Done.
___
*[pkg/kv/kvprober/kvprober_test.go, line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop6RKy2OOJ0Mn-6Jg9:-Mp7JgOk1lmEnUeYe-ia:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/kvprober_test.go#L70)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

Can you add a comment here noting that the `planner` always bypasses admission control intentionally?

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvprober/planner.go#L221

I think this is logical. Say something like this:

> Queries from the `planner` bypass admission control, regardless of what `kv.prober.bypass_admission_control.enabled` is set to. Operators would like to get paged due to probes failing in an overload situation, not the `planner` failing. The `planner` is an implementation detail of `kvprober`, and tho it being broken is not desired as (i) it hurts alerting coverage & (i) it prob does indicate an issue with the cluster, the signal of cluster health that is most useful to operators is failing probes, as this signal reflects the "size" of the outage, by taking measurements across the keyspace.
</blockquote></details>

Done.
___
*[pkg/kv/kvprober/kvprober_test.go, line 279 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop8H0NAxxPC9mUAu9g:-Mp7K8C81C1IhEtn4lNa:brxp9sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/kvprober_test.go#L279)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

No change requested: CRDB doesn't use gomock today IIUC. A good refactor for one of us to do sometime is replace these mocks with some gomock mocks!
</blockquote></details>

Sounds good!
___
*[pkg/kv/kvprober/settings.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop3bB1CNvwDch_9GiS:-Mp7KBq21-d8E3ud878G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/settings.go#L23)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

Can you add a little more about why one might set this to true vs. false? The bit you have in the commit description about serverless vs. dedicated and who owns scaling is want I want to be clear to our future selves about!
</blockquote></details>

Done.
___
*[pkg/kv/kvprober/settings.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop3LNZ5T7F8tMQ6VUQ:-Mp7KHZIEgvadgvlqOKz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/kvprober/settings.go#L27)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

I vote we make this default to `true`. I want to backport this PR into the 21.2 branch. To do that, prob better (or perhaps required) to not introduce an actual change. Also, I think it's easier on our ops load to set this to `false` on our ~10 host clusters than to set it to true on our many dedicated clusters.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-22 22:14 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dasrirez, @joshimhoff, @sumeerbhola, and @tbg)

___
*[-- commits, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop0z94-4d8Zrwad_XZ):*
<details><summary><i>Previously, dasrirez (Darius Asri Rezaei) wrote…</i></summary><blockquote>

Here is [`AdmitKVWork`](https://github.com/dasrirez/cockroach/blob/578ffd0c3646eb37e35a466f788305f142f2d2d2/pkg/kv/kvserver/store.go#L3159). Looking at how `bypassAdmission` gets set here, I'm assuming that `roachpb.AdmissionHeader_ROOT_KV` is not a factor. I wanted to change the behaviour of this function so that work from `ROOT_KV` does bypass admission control, but I noticed there are other systems that are currently using `ROOT_KV` as their source and they may not be ready for undergoing admission control.
</blockquote></details>

`ROOT_KV` should not bypass admission control. OTHER is for bypassing.
@joshimhoff my comment "...once we start using roachpb.AdmissionHeader_ROOT_KV ..." no longer applies, since it predates my change to start using `ROOT_KV` for certain internal KV requests (and predates the change to AdmitKVWork).
AdmitKVWork should not need to be changed.
___
*[pkg/kv/txn.go, line 103 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop-eehE3fWGnqbdHLq:-Mp8hPpQBQrBY_-MiJ9y:b-b5wn63) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/txn.go#L103)):*
> Should this comment read something like this?
> // Note: for KV usage on which admission control should be applied, prefer NewTxnRootKV() below.

Yes, this additional comment would be good to have.
I don't think the name of the function needs to change -- if folks are calling a function without reading the (short) function comment that is their fault.


<!-- Sent from Reviewable.io -->

2021-11-23 01:33 UTC, dasrirez reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dasrirez, @joshimhoff, @sumeerbhola, and @tbg)

___
*[-- commits, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop0z94-4d8Zrwad_XZ):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`ROOT_KV` should not bypass admission control. OTHER is for bypassing.
@joshimhoff my comment "...once we start using roachpb.AdmissionHeader_ROOT_KV ..." no longer applies, since it predates my change to start using `ROOT_KV` for certain internal KV requests (and predates the change to AdmitKVWork).
AdmitKVWork should not need to be changed.


</blockquote></details>

Er, sorry that was a typo in my last comment. The code is currently setting `ROOT_KV` with the intention of NOT bypassing admission.


<!-- Sent from Reviewable.io -->

2021-11-23 13:35 UTC, dasrirez reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dasrirez, @joshimhoff, @sumeerbhola, and @tbg)

___
*[pkg/kv/txn.go, line 103 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop-eehE3fWGnqbdHLq:-MpC-GH964erCptMwZf6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea12383ee1f41b031dc6eeab8c2cba5ac6d5972f/pkg/kv/txn.go#L103)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> Should this comment read something like this?
> // Note: for KV usage on which admission control should be applied, prefer NewTxnRootKV() below.

Yes, this additional comment would be good to have.
I don't think the name of the function needs to change -- if folks are calling a function without reading the (short) function comment that is their fault.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 14:34 UTC, sumeerbhola approved these changes
> Reviewed 1 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dasrirez, @joshimhoff, @sumeerbhola, and @tbg)

___
*[pkg/kv/txn.go, line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-MpCC_y08MfqUz7FGDgc:-MpCC_y08MfqUz7FGDgd:b-k8qu6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0df95be9613d6d306c97b3ac83579e570c25bb/pkg/kv/txn.go#L155)):*
> ```Go
> // originating within KV and that is at the root of the tree of requests.
> // Do not use this for executing transactions originating in SQL. This
> // distinction only affects admission control. See AdmissionHeader_Source for
> ```

should say that this makes these requests subject to admission control.
Also in the comment for `TxnRootKV`.


<!-- Sent from Reviewable.io -->

2021-11-23 14:54 UTC, dasrirez reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dasrirez, @joshimhoff, @sumeerbhola, and @tbg)

___
*[pkg/kv/txn.go, line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-MpCC_y08MfqUz7FGDgc:-MpCGBWg2zcnTRWoiYlp:b-tey8am) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0df95be9613d6d306c97b3ac83579e570c25bb/pkg/kv/txn.go#L155)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should say that this makes these requests subject to admission control.
Also in the comment for `TxnRootKV`.
</blockquote></details>

Done. Description is now more explicit about the resulting admission control effect.


<!-- Sent from Reviewable.io -->

2021-11-23 19:06 UTC, joshimhoff approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

Lovely! We're going to want to backport this into the 21.2 branch. We'll need to check in with KV about this. We may need to backport to two branches since the real goal is to get the fix onto serverless host clusters where it is needed. Serverless has its own 21.2 branch still IIUC. I don't know the name of that branch but we can ask #cc-serverless or something. I think Andy Kimball is the approver of all backports to that branch.

https://wiki.crdb.io/wiki/spaces/CRDB/pages/900005932/Backporting+a+change+to+a+release+branch

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-:-MpDAeYuD65v3I_BPtdk:b-v86w4q)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dasrirez, @joshimhoff, @sumeerbhola, and @tbg)

___
*[-- commits, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-Mop0z94-4d8Zrwad_XZ):*
<details><summary><i>Previously, dasrirez (Darius Asri Rezaei) wrote…</i></summary><blockquote>

Er, sorry that was a typo in my last comment. The code is currently setting `ROOT_KV` with the intention of NOT bypassing admission.
</blockquote></details>

Thanks, all! I got it now.
___
*[pkg/kv/kvprober/kvprober.go, line 352 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-MpD5XI0B8tJ93l8aBvF:-MpD5XI0B8tJ93l8aBvG:ba1c21g) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc1667c1729675a0a544ff74c67eef95e1136e88/pkg/kv/kvprober/kvprober.go#L352)):*
> ```Go
> 	timeout := writeTimeout.Get(&p.settings.SV)
> 	err = contextutil.RunWithTimeout(ctx, "write probe", timeout, func(ctx context.Context) error {
> 		// We attempt to commit a txn that puts some data at the key then
> ```

Can you move this comment up to the implementation of `Write` plz?


<!-- Sent from Reviewable.io -->

2021-11-23 20:21 UTC, dasrirez reviewed
Sounds good, thanks for the reviews everyone!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-:-MpDRxTHA6XbbWSBrDJB:b-yz7d0)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dasrirez, @joshimhoff, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvprober/kvprober.go, line 352 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72748#-MpD5XI0B8tJ93l8aBvF:-MpDS3MuEaz7l-MaYvmn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc1667c1729675a0a544ff74c67eef95e1136e88/pkg/kv/kvprober/kvprober.go#L352)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

Can you move this comment up to the implementation of `Write` plz?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-29 19:52 UTC, dasrirez commented
bors r+

2021-11-29 22:39 UTC, merged