sql: fix ALTER COLUMN TYPE erasing ON UPDATE clause
cockroachdb/cockroach pull request #72779
Opened 2021-11-15 19:47 UTC by e-mbrown

Resolves #71571

When changing the data type of a column the ON UPDATE
clause was erased. This change ensures that the ON UPDATE
clause remains when column types are changed.

Release note: None

2021-11-15 19:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72779)
<!-- Reviewable:end -->

2021-11-15 19:56 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72779)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @e-mbrown)

___
*[pkg/sql/alter_column_type.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72779#-Mo_9FTp9lYgcqPaGDvO:-Mo_9FTp9lYgcqPaGDvP:b-pb33ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/5187039e80af2eb9367992f84e37935d945c0f8f/pkg/sql/alter_column_type.go#L389)):*
> ```Go
> 			)
> 		}
> 		newCol = descpb.ColumnDescriptor{
> ```

This has a similar problem as before. If there's both an `ON UPDATE` expression and a `DefaultExpr`, we don't seem to copy over the `DefaultExpr`. 

I think the answer is to make sure we copy both expressions over if they exist after the checking. 
Consider writing a some logic tests that might currently fail and then trying out your solutions. 


<!-- Sent from Reviewable.io -->

2021-11-15 19:56 UTC, rafiss requested changes
could you add a logic test that would have previously failed but is now fixed?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72779#-:-Mo_9fYF8Ef0f156LEfK:b-rkcohk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, and @rafiss)

___
*[pkg/sql/alter_column_type.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72779#-Mo_9lFF7VRI7CC6oT1O:-Mo_9lFF7VRI7CC6oT1P:bc6xyqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5187039e80af2eb9367992f84e37935d945c0f8f/pkg/sql/alter_column_type.go#L389)):*
> ```Go
> 			)
> 		}
> 		newCol = descpb.ColumnDescriptor{
> ```

i don't think these should be in two separate branches of the code -- the way it is now means that the `DefaultExpr` will be removed if there is an `OnUpdateExpr` already

instead, you should just add one more line to the original `newCol` declaration
```
OnUpdateExpr:    col.ColumnDesc().OnUpdateExpr,
```


<!-- Sent from Reviewable.io -->

2022-11-15 16:07 UTC, e-mbrown commented
This problem requires more discussion, closing this PR.

2022-11-15 16:07 UTC, closed without merging