[WIP] importccl: support partial indexes in IMPORT INTO
cockroachdb/cockroach pull request #72846
Opened 2021-11-17 00:03 UTC by adityamaru

WIP

Release note: None

2021-11-17 00:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72846)
<!-- Reviewable:end -->

2021-11-17 00:04 UTC, adityamaru commented
@mgartner I want to add some more tests around the interaction between default/computed columns and partial indexes but thought it would be useful to get some eyes on the general approach.

2021-11-19 22:38 UTC, mgartner reviewed
General approach LGTM. Just left some nits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-:-MouLLBzAl6DErcGKGnf:b-7qxgoi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @stevendanna)

___
*[pkg/sql/row/row_converter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MoiVnhLBVgwl_A7j1eX:-MoiVnhLBVgwl_A7j1eY:b-xbfc2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/429130af0f077ac65d1492276126c63a07d85d85/pkg/sql/row/row_converter.go#L465)):*
> ```Go
> 		c.tableDesc.PublicColumns(), c.tableDesc, c.EvalCtx, &semaCtxCopy)
> 	if err != nil {
> 		return nil, errors.Wrapf(err, "error evaluating partial index expression for IMPORT INTO")
> ```

nit: partial index expressions are being type checked and built here, not "evaluated". The error above for computed column expressions is incorrect too 
___
*[pkg/sql/row/row_converter.go, line 523 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MoiUD6cCNpm_1ZfeJX5:-MoiUD6d3akxW3m2eNbT:boxyuur) ([raw file](https://github.com/cockroachdb/cockroach/blob/429130af0f077ac65d1492276126c63a07d85d85/pkg/sql/row/row_converter.go#L523)):*
> ```Go
> 		c.partialIndexIVarContainer.CurSourceRow = insertRow
> 		c.EvalCtx.PushIVarContainer(&c.partialIndexIVarContainer)
> 		partialIndexes := make(tree.Datums, len(c.tableDesc.PartialIndexes()))
> ```

nit: partialIndexes is a confusing name here. These are boolean datums that indicate whether or not a row should be added to each partial index. Maybe use the name used in PartialIndexUpdateHelper: `partialIndexPutVals`?
___
*[pkg/sql/row/row_converter.go, line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MoiTOuc75ug87wPJIVE:-MoiTOuc75ug87wPJIVF:bx3aj94) ([raw file](https://github.com/cockroachdb/cockroach/blob/429130af0f077ac65d1492276126c63a07d85d85/pkg/sql/row/row_converter.go#L534)):*
> ```Go
> 			}
> 		}
> 		err = pm.Init(partialIndexes, []tree.Datum{}, c.tableDesc)
> ```

nit: you should be able to pass `nil /* partialIndexDelVals */` as the second argument (I should have done that in other places that call `PartialIndexUpdateHelper.Init`).


<!-- Sent from Reviewable.io -->

2021-11-22 18:24 UTC, adityamaru reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72846)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/sql/row/row_converter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MoiVnhLBVgwl_A7j1eX:-Mp7t6qd3cucAJ9oVciy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/429130af0f077ac65d1492276126c63a07d85d85/pkg/sql/row/row_converter.go#L465)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: partial index expressions are being type checked and built here, not "evaluated". The error above for computed column expressions is incorrect too 
</blockquote></details>

Done.
___
*[pkg/sql/row/row_converter.go, line 523 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MoiUD6cCNpm_1ZfeJX5:-Mp7t7pqCuyR20PtMQWA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/429130af0f077ac65d1492276126c63a07d85d85/pkg/sql/row/row_converter.go#L523)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: partialIndexes is a confusing name here. These are boolean datums that indicate whether or not a row should be added to each partial index. Maybe use the name used in PartialIndexUpdateHelper: `partialIndexPutVals`?
</blockquote></details>

Done.
___
*[pkg/sql/row/row_converter.go, line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MoiTOuc75ug87wPJIVE:-Mp7t8W2E1R4GYIs2SNR:bgnfexb) ([raw file](https://github.com/cockroachdb/cockroach/blob/429130af0f077ac65d1492276126c63a07d85d85/pkg/sql/row/row_converter.go#L534)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you should be able to pass `nil /* partialIndexDelVals */` as the second argument (I should have done that in other places that call `PartialIndexUpdateHelper.Init`).
</blockquote></details>

Done, and changed elsewhere too!


<!-- Sent from Reviewable.io -->

2021-12-01 14:15 UTC, adityamaru commented
friendly ping @mgartner 🙂

2021-12-06 15:19 UTC, mgartner requested changes
Apologies for the delay.

> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-:-MqFJnOW6i7BiR2EWI-9:byib4zn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @stevendanna)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 7322 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MqFIaEvDyTVA2yGstHd:-MqFIaEvDyTVA2yGstHe:bg065x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5cb0f1ec11fc40daa46611fcc192410232f240e/pkg/ccl/importccl/import_stmt_test.go#L7322)):*
> ```Go
>     FAMILY (c)
> )`)
> 		data = "1,2,1"
> ```

It would be good to add a row where `b <= 1` to make sure it doesn't get written to the partial index.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 7327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MqFHrRs8EksLMS_ZJYT:-MqFHrRs8EksLMS_ZJYU:bwi1oha) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5cb0f1ec11fc40daa46611fcc192410232f240e/pkg/ccl/importccl/import_stmt_test.go#L7327)):*
> ```Go
> 			{"1", "2", "1"},
> 		})
> 		sqlDB.ExpectErr(t, "index \"idx_c_b_gt_1\" is a partial index that does not contain all the rows needed to execute this query",
> ```

nit: I don't think this check is necessary. This behavior relies on optimizer logic, not IMPORT logic, and it's already well-tested elsewhere.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 7340 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MqFIMYbErsldY7femUD:-MqFIMYbErsldY7femUE:b-zg3oil) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5cb0f1ec11fc40daa46611fcc192410232f240e/pkg/ccl/importccl/import_stmt_test.go#L7340)):*
> ```Go
> 		sqlDB.Exec(t, fmt.Sprintf(`IMPORT INTO c CSV DATA ('%s')`, srv.URL))
> 		// Run an update just to make sure it works as expected.
> 		sqlDB.Exec(t, `UPDATE c SET i = i + 1`)
> ```

nit: I don't think you need to test `UPDATE` either.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 7351 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MqFIUMT6PxwHZyLcraN:-MqFIUMT6PxwHZyLcraO:b-90w6qt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5cb0f1ec11fc40daa46611fcc192410232f240e/pkg/ccl/importccl/import_stmt_test.go#L7351)):*
> ```Go
>     a INT PRIMARY KEY,
>     b INT,
>     c INT AS (B + 10) VIRTUAL,
> ```

nit: `B` => `b`
___
*[pkg/ccl/importccl/import_stmt_test.go, line 7370 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MqFIrz0CIxHPG5TZew3:-MqFIrz0CIxHPG5TZew4:bi6hdiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5cb0f1ec11fc40daa46611fcc192410232f240e/pkg/ccl/importccl/import_stmt_test.go#L7370)):*
> ```Go
> `)
> 		data = "1,0\n1,2"
> 		sqlDB.ExpectErr(t, "duplicate key in primary index",
> ```

`1,0\n1,2` should not error because only one satisfies `b > 0`. I think you should test a successful import (the current `data` is fine), and also an unsuccessful import with something `data = "1,2\n1,0\n1,3"`.
___
*[pkg/sql/row/row_converter.go, line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72846#-MoiTOuc75ug87wPJIVE:-MqFJhwvDiC2LfzVQhpo:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/429130af0f077ac65d1492276126c63a07d85d85/pkg/sql/row/row_converter.go#L534)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Done, and changed elsewhere too!
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2022-07-28 20:21 UTC, ecwall commented
PR moved here https://github.com/cockroachdb/cockroach/pull/85244

2022-07-28 20:21 UTC, closed without merging