roachprod: remove ClusterImpl interface
cockroachdb/cockroach pull request #72887
Opened 2021-11-17 20:40 UTC by RaduBerinde

The ClusterImpl interface was useful when roachprod had some (very
limited) support for Cassandra, but that has been removed. We're left
with an unnecessary indirection that lacks documentation. The code
doesn't follow any layering, with `Cockroach` working directly with
`SyncedCluster` internals and plenty of cockroach-specific code in
`SyncedCluster`.

This commit removes this interface and improves the documentation of
the methods that are simplified.

Release note: None

2021-11-17 20:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72887)
<!-- Reviewable:end -->

2021-11-18 15:11 UTC, rail requested changes
Woo, this is so much cleaner and I bet easier for Goland to resolve definitions. LGTM, you just forgot to change `h` to `c` in one spot.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72887#-:-MonaBzP0iVc2rA36RaB:bu02kbu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @RaduBerinde, and @stevendanna)

___
*[pkg/roachprod/install/cockroach.go, line 715 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72887#-Mona3Jv3dWzXJ3qqz-x:-Mona3Jv3dWzXJ3qqz-y:bl2xcg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffb94ed7e3c766a8c1a1050fe8f89d35b3b2b64e/pkg/roachprod/install/cockroach.go#L715)):*
> ```Go
> }
> 
> func (h *SyncedCluster) getEnvVars() []string {
> ```

The linter says `s/h/c` ;)


<!-- Sent from Reviewable.io -->

2021-11-18 18:23 UTC, RaduBerinde reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72887#-:-MooHLKX5S21_IvS_C6C:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @rail, and @stevendanna)

___
*[pkg/roachprod/install/cockroach.go, line 715 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72887#-Mona3Jv3dWzXJ3qqz-x:-MooGxlvB7QH0Vwx0Nq4:b7eex9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffb94ed7e3c766a8c1a1050fe8f89d35b3b2b64e/pkg/roachprod/install/cockroach.go#L715)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

The linter says `s/h/c` ;)
</blockquote></details>

Removed the receiver altogether.


<!-- Sent from Reviewable.io -->

2021-11-18 18:26 UTC, rail approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :shipit: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72887#-:-MooI6Ho-mxa2iZZOYbd:byzm7aw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @healthy-pod and @stevendanna)



<!-- Sent from Reviewable.io -->

2021-11-18 18:45 UTC, RaduBerinde commented
bors r+

2021-11-18 22:08 UTC, merged