[DRAFT] server: implement connection_wait for graceful draining
cockroachdb/cockroach pull request #72991
Opened 2021-11-19 19:24 UTC by ZhouXing19

This is a draft commit (PR).

Currently, the draining process is consist of three consecutive periods:
- `drain_wait`: The `/health?ready=1` starts to show that the node is shutting
	down. New connections and new queries are allowed. Server do a hard wait
	till the timeout.
- `query_wait`: New connections are not allowed. Connections with no queries in
	flight will be closed by the server immediately. The rest of these
	connections will be terminated by the server as soon as their queries are
	finished. Early exit if all connections are closed.
- `lease_transfer_wait`: Wait to transfer range leases. Server do a hard wait
	till the timeout.

This commit reorganize the draining process by adding a connection_wait period,
and slightly modifying the existing ones:

- `drain_wait`: The `/health?ready=1` starts to show that the node is shutting
	down. New connections and new queries are allowed. Server do a hard wait
	till the timeout.
- `connection_wait`: Wait until all connections are closed or timeout.
	New connections are not allowed. Existing connections and new queries are
	allowed. We do an early exist if all connections are closed by the user.
	If `connection_wait` is set with a negative duration, the server wait infinitely
	long time until all connections are terminated by the user.
- `query_wait`: Connections with no queries in flight will be closed by the server
	immediately. The rest of these
	connections will be terminated by the server as soon as their queries are
	finished. Early exit if all connections are closed.
- `lease_transfer_wait`: Wait to transfer range leases. Server do a hard wait
	till the timeout.

The duration of `connection_wait` can be set similarly to the other 3 variables:
```
SET CLUSTER SETTING server.shutdown.connection_wait = '40s'
```

Release note: TBD

2021-11-19 19:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/72991)
<!-- Reviewable:end -->

2022-01-21 18:25 UTC, knz commented
@cameronnunez do you want to start reviewing this on behalf of the server team?

2022-01-25 21:41 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @ZhouXing19)

___
*[pkg/server/drain.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI8Z2c310CyYad8sXT:-MuI8Z2d9llN8C8rqUad:buul946) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L57)):*
> ```Go
> 			"before proceeding with the rest of the shutdown process. It must be set "+
> 			"with a non-negative value",
> 		0*time.Second,
> ```

after the default `0 second` val, you can pass in
```
settings.NonNegativeDurationWithMaximum(maxAllowedSetting),
```

This automatically enforces that the setting is `>=0`, and does not exceed whichever max you pick
___
*[pkg/server/drain.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI9f5G-Ji1RHwg6xup:-MuI9f5G-Ji1RHwg6xuq:bn0at1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L255)):*
> ```Go
> 	// /health?ready=1 will notice.
> 	s.grpc.setMode(modeDraining)
> 	s.sqlServer.acceptingClients.Set(false)
> ```

nit: `acceptingClients` is supposed to be renamed, right?
___
*[pkg/server/drain.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI8nO92AaQR5YSjHkf:-MuI8nO92AaQR5YSjHkg:b-thav78) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L261)):*
> ```Go
> 
> 	// Log the number of connections in cockroach.log every 3 seconds.
> 	go func() {
> ```

we need to be careful when spinning up goroutines -- doing it like this means the goroutine will last forever and the main server goroutine doesn't know about this goroutine

we should use something like `s.Stopper.RunAsyncTask` for this
___
*[pkg/server/drain.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI9MYk2ud66N7K0126:-MuI9MYk2ud66N7K0127:b-s80iqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L269)):*
> ```Go
> 
> 	if shouldDelayDraining {
> 		drainWaitLogMessage := fmt.Sprintf("drain wait starts, timeout after %s",
> ```

nit: "starting" instead of "starts" might be more clear
___
*[pkg/server/drain.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI9R3D-gLdsZObgOFa:-MuI9R3EENoBVD-kTLAN:bpk6mp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L280)):*
> ```Go
> 		connectionMaxWait := connectionWait.Get(&s.st.SV)
> 		if connectionMaxWait < 0 {
> 			return errors.Wrapf(fmt.Errorf("server.shutdown.connection_wait must be set with non-negative duration"), "%s")
> ```

don't need this if we enforce the setting when registering the cluster setting
___
*[pkg/server/drain.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI9VC_7pkewQrdmy5b:-MuI9VC_7pkewQrdmy5c:b3s4uy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L285)):*
> ```Go
> 		// "connection wait starts, no new SQL connections allowed, early exit to
> 		// lease transfer phase once all SQL connections are closed."
> 		connectionWaitLogMessage := fmt.Sprintf("connection wait starts, timeout after %s",
> ```

nit: "starting"
___
*[pkg/server/drain.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI9Ypn2KV9yD_cpP0s:-MuI9Ypn2KV9yD_cpP0t:bs1yehq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L294)):*
> ```Go
> 
> 	queryMaxWait := queryWait.Get(&s.st.SV)
> 	if queryMaxWait < 0 {
> ```

also can avoid this by adding validation in the cluster setting
___
*[pkg/sql/pgwire/server.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuIA3QS5PEOslJP2Mmb:-MuIA3QS5PEOslJP2Mmc:b-kp9er) ([raw file](https://github.com/cockroachdb/cockroach/blob/5359e546359dc95acb36b226ca95f83b7001c389/pkg/sql/pgwire/server.go#L451)):*
> ```Go
> 		s.mu.Lock()
> 		defer s.mu.Unlock()
> 		if !s.setDrainingLocked(true) {
> ```

why did this need to be removed?
___
*[pkg/sql/pgwire/server.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuIArCE11kfyrLEX1x_:-MuIArCE11kfyrLEX1xa:bkp3hbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/sql/pgwire/server.go#L460)):*
> ```Go
> // This is a helper function to the connectionWait process, which listen to the
> // status of all connections, and early exits if there remains no connections.
> func (s *Server) GetConnCancelMap() cancelChanMap {
> ```

nit: i think this can be changed so it just returns the size of the map. it seems less risky that way
___
*[pkg/sql/pgwire/server.go, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuIAWKb778ig8-5QS89:-MuIAWKb778ig8-5QS8A:bnwpitb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/sql/pgwire/server.go#L480)):*
> ```Go
> 			return
> 		default:
> 			if len(s.GetConnCancelMap()) == 0 {
> ```

i'm not entirely sure about this part -- it's calling GetConnCancelMap in a tight loop, and that accesses a mutex. i wonder if that could lead to lock contention. maybe a better approach is to check the connCancelMap periodically using a ticker. another set of eyes on this would help
___
*[pkg/sql/pgwire/server.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuIAPUV0a9S6AriVDYJ:-MuIAPUV0a9S6AriVDYK:b7br97p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/sql/pgwire/server.go#L481)):*
> ```Go
> 		default:
> 			if len(s.GetConnCancelMap()) == 0 {
> 				if !timer.Stop() {
> ```

nit: a comment saying why we have an extra wait here might help


<!-- Sent from Reviewable.io -->

2022-01-27 16:41 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @rafiss)

___
*[pkg/server/drain.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI8Z2c310CyYad8sXT:-MuRO5ZM8Y-wPqk7wAiR:bwqrv6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L57)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

after the default `0 second` val, you can pass in
```
settings.NonNegativeDurationWithMaximum(maxAllowedSetting),
```

This automatically enforces that the setting is `>=0`, and does not exceed whichever max you pick
</blockquote></details>

Done, set 10 hours as the maximum duration.
___
*[pkg/server/drain.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI9f5G-Ji1RHwg6xup:-MuROCkPDEy8lb7nYHm3:b-erukwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L255)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: `acceptingClients` is supposed to be renamed, right?
</blockquote></details>

Done renaming it to `isHealthcheckReady`.
___
*[pkg/server/drain.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI8nO92AaQR5YSjHkf:-MuRONVnAB6hEaTkHsSG:bg8iqm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L261)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we need to be careful when spinning up goroutines -- doing it like this means the goroutine will last forever and the main server goroutine doesn't know about this goroutine

we should use something like `s.Stopper.RunAsyncTask` for this
</blockquote></details>

Using `s.Stopper.RunAsyncTask` now.
___
*[pkg/server/drain.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI9R3D-gLdsZObgOFa:-MuROUOE4vds18dr5SsP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L280)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

don't need this if we enforce the setting when registering the cluster setting
</blockquote></details>

Done.
___
*[pkg/server/drain.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI9Ypn2KV9yD_cpP0s:-MuROWtSBck082RrByfc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L294)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

also can avoid this by adding validation in the cluster setting
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuIA3QS5PEOslJP2Mmb:-MuRKv1c8hAWSU66bb--:b-dm238i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5359e546359dc95acb36b226ca95f83b7001c389/pkg/sql/pgwire/server.go#L451)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why did this need to be removed?
</blockquote></details>

Because `s.setDrainingLocked(true)` is now used within `s.DisallowNewSQLConn()`, which has been called in `s.DrainConnections()`. I.e. now with `s.mu.draining == true`, it only means that "connection_wait" has started, not `query_wait` has started.
___
*[pkg/sql/pgwire/server.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuIArCE11kfyrLEX1x_:-MuRP9Lv8s9L7qOC-18W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/sql/pgwire/server.go#L460)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think this can be changed so it just returns the size of the map. it seems less risky that way
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuIAWKb778ig8-5QS89:-MuRPDC52IRo7GWkD6NK:b-we0ij5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/sql/pgwire/server.go#L480)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm not entirely sure about this part -- it's calling GetConnCancelMap in a tight loop, and that accesses a mutex. i wonder if that could lead to lock contention. maybe a better approach is to check the connCancelMap periodically using a ticker. another set of eyes on this would help
</blockquote></details>

Done using a ticker to check the active SQL connections every 2 seconds.
___
*[pkg/sql/pgwire/server.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuIAPUV0a9S6AriVDYJ:-MuRPNssE2w4uGvNOcJp:bldxvxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/sql/pgwire/server.go#L481)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: a comment saying why we have an extra wait here might help
</blockquote></details>

Added above.


<!-- Sent from Reviewable.io -->

2022-01-30 20:56 UTC, cameronnunez reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugf7Cs0raBaLceU8C7:-Mugf7Cs0raBaLceU8C8:b-x2zypd) (no related file):*
This would benefit from a test. 

When logging information, I still think it’s still worth disentangling the cluster setting names and the stage names. It may be convenient to reuse the naming but I think it can lead to confusion. The main reason this is the case is because we risk befuddling the users as to what a drain is actually doing. It should be made clear that the core components of the draining process are (1) draining SQL connections and (2) draining leases & leadership. This is clear from the fact that `isDraining()` only starts returning true once we reach the step of draining SQL connections. In contrast to the waiting stages, during which the server experiences normal operation, the two core stages have the server operating atypically (e.g. forcefully closing connections when their queries finish, transferring leases off the node, etc.)

---
___
*[pkg/server/drain.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI8nO92AaQR5YSjHkf:-Mugji23258AYcl0S4an:b-4h2840) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L261)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Using `s.Stopper.RunAsyncTask` now.
</blockquote></details>

Task name should be dash separated e.g. `s.stopper.RunAsyncTask(ctx, "log-active-conns", ....`
___
*[pkg/server/drain.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugi1FA7ESOO7n-_9QR:-Mugi1FA7ESOO7n-_9QS:bf8io2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/server/drain.go#L54)):*
> ```Go
> 		settings.TenantReadOnly,
> 		"server.shutdown.connection_wait",
> 		"the amount of time a server waits users to close all SQL connections "+
> ```

the maximum amount of time, because we could have an early exit, right? I think in general we should probably be more descriptive with the other cluster settings, specifying if a setting is a minimum duraiton or if it is a timeout.
___
*[pkg/server/drain.go, line 268 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MugfhXl31yDtWCkb-z3:-MugfhXl31yDtWCkb-z4:blsac6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/server/drain.go#L268)):*
For the infinite loop here, a select block is more appropriate. Something like this should do:
>```go 
> for period := 3 * time.Second; ; timer.Reset(period) {
>   select {
>   case <-timer.C:
>     timer.Read = true
>     s.sqlServer.pgServer.LogActiveConns(ctx)
>   case <-s.server.stopper.ShouldQuiesce():
>     return
>   case <-ctx.Done():
>     return 
>   }
> }
>```

To make all of this look more clean, you could write a function that returns this `s.stopper.RunAsyncTask`
___
*[pkg/server/drain.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugk4YvEOhkK55CDo3h:-Mugk4YvEOhkK55CDo3i:b3jk4oe) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/server/drain.go#L274)):*
> ```Go
> 
> 	if shouldDelayDraining {
> 		drainWaitLogMessage := fmt.Sprintf("drain wait starting, will timeout after %s",
> ```

`drain_wait` is a minimum duration, unlike `connection_wait` and `query_wait`, which are timeouts.
___
*[pkg/server/server_sql.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MugiFJF14RXdsn7yK5h:-MugiFJF14RXdsn7yK5i:b-7hvtvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/server/server_sql.go#L162)):*
> ```Go
> 	// set to true when the server has started accepting client conns.
> 	// Used by health checks.
> 	isHealthcheckReady syncutil.AtomicBool
> ```

agreed with renaming `acceptingClients`. can you update the comments corresponding to it too?  (nit) we can simplify `isHealthcheckReady` to `isReady`
___
*[pkg/sql/pgwire/server.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MughLX74h_72pn6QCOl:-MughLX74h_72pn6QCOm:bxladhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L376)):*
> ```Go
> }
> 
> func (s *Server) IsQueryDraining() bool {
> ```

Instead of `queryDraining` and `s.IsQueryDraining()`, you can use `s.isDraining()` which returns starts returning true after entering the draining phases. 
___
*[pkg/sql/pgwire/server.go, line 473 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MugiwWs77Q8UGyhDWj3:-MugiwWs77Q8UGyhDWj4:bkxsj8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L473)):*
> ```Go
> // During the connectionWait period, no new SQL connections are allowed, and as
> // soon as all existing SQL connections are closed, we do an early exit.
> func (s *Server) DrainConnections(ctx context.Context, connectionWait time.Duration) {
> ```

“waits for the users” Might be best to change the wording here as well, since all of the connections don’t need to be closed during connection wait. Something like: "... waits for SQL connections to close for the duration of connectionWait “
Also might be best to change the function name to make it clearer that this is a wait - that the server is not draining SQL connections here. `WaitForDrainConnections` perhaps
___
*[pkg/sql/pgwire/server.go, line 541 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MughqmG-fBBk4wzqmwz:-MughqmG-fBBk4wzqmx-:b-fk9o0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L541)):*
> ```Go
> 	}
> 
> 	queryWaitLogMessage := fmt.Sprintf("query wait starting, will timeout after %s",
> ```

We can be more descriptive here with something like: “draining remaining SQL connections, will timeout after %s”
___
*[pkg/sql/pgwire/server.go, line 571 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugh8Vg7J8JeI5znscT:-Mugh8Vg7J8JeI5znscU:b-ohf4qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L571)):*
> ```Go
> 	}()
> 
> 	// Wait for all connections to finish up to drainWait.
> ```

Noticed this pre-existing comment that incorrectly says drainWait instead of queryWait.
___
*[pkg/sql/pgwire/server.go, line 574 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugije18TmtjNIc5lG6:-Mugije18TmtjNIc5lG7:b-1vtv4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L574)):*
> ```Go
> 	select {
> 	case <-time.After(queryWait):
> 		fmt.Println("query wait ended at ", time.Now().Format(pgTimeFormat))
> ```

this should be after the select block right? because this stage can early exit.


<!-- Sent from Reviewable.io -->

2022-01-31 19:49 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @rafiss)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugf7Cs0raBaLceU8C7:-MuleGdV-7rQDQ1ebt6d:b-1svox7) (no related file):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

This would benefit from a test. 

When logging information, I still think it’s still worth disentangling the cluster setting names and the stage names. It may be convenient to reuse the naming but I think it can lead to confusion. The main reason this is the case is because we risk befuddling the users as to what a drain is actually doing. It should be made clear that the core components of the draining process are (1) draining SQL connections and (2) draining leases & leadership. This is clear from the fact that `isDraining()` only starts returning true once we reach the step of draining SQL connections. In contrast to the waiting stages, during which the server experiences normal operation, the two core stages have the server operating atypically (e.g. forcefully closing connections when their queries finish, transferring leases off the node, etc.)
</blockquote></details>

@cameronnunez Thanks for reviewing!
I'm preparing the tests as well. Will add them to this PR once ready.

For the log message, I added more info about the current draining stage, along with which cluster session variable to set its duration. 

---
___
*[pkg/server/drain.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MuI8nO92AaQR5YSjHkf:-MuldVrm2Pts14atn2fI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8204aff05410dff7b363aa97e449669f01d3e40/pkg/server/drain.go#L261)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Task name should be dash separated e.g. `s.stopper.RunAsyncTask(ctx, "log-active-conns", ....`
</blockquote></details>

Done.



_Code quote:_
```Go
connectionWait = settings.RegisterDurationSetting(
```
___
*[pkg/server/drain.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugi1FA7ESOO7n-_9QR:-MuldH8G0o2yKkyml5Ii:b-d3jmz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/server/drain.go#L54)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

the maximum amount of time, because we could have an early exit, right? I think in general we should probably be more descriptive with the other cluster settings, specifying if a setting is a minimum duraiton or if it is a timeout.
</blockquote></details>

Yes good point, done.
___
*[pkg/server/drain.go, line 268 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MugfhXl31yDtWCkb-z3:-Mul_tPr6ECpX2ljP731:bxuyc9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/server/drain.go#L268)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

For the infinite loop here, a select block is more appropriate. Something like this should do:
>```go 
> for period := 3 * time.Second; ; timer.Reset(period) {
>   select {
>   case <-timer.C:
>     timer.Read = true
>     s.sqlServer.pgServer.LogActiveConns(ctx)
>   case <-s.server.stopper.ShouldQuiesce():
>     return
>   case <-ctx.Done():
>     return 
>   }
> }
>```

To make all of this look more clean, you could write a function that returns this `s.stopper.RunAsyncTask`
</blockquote></details>

Thanks! Using a helper function `s.logActiveConns()`now.
___
*[pkg/server/drain.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugk4YvEOhkK55CDo3h:-MuldXV4-Ptb0YNOTP_N:brmcjib) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/server/drain.go#L274)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

`drain_wait` is a minimum duration, unlike `connection_wait` and `query_wait`, which are timeouts.
</blockquote></details>

Changed the log message.
___
*[pkg/server/server_sql.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MugiFJF14RXdsn7yK5h:-MulaJkn7xE8DsRAFTl5:b-dvx86u) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/server/server_sql.go#L162)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

agreed with renaming `acceptingClients`. can you update the comments corresponding to it too?  (nit) we can simplify `isHealthcheckReady` to `isReady`
</blockquote></details>

Updated the comments.
I'd prefer keeping it as `isHealthcheckReady`, because`isReady` can be ambiguous (e.g. can be wrongly interpreted as the server is (not) ready for _SQL queries_)
___
*[pkg/sql/pgwire/server.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MughLX74h_72pn6QCOl:-Muhp4xLEgFjDB9kVfTM:bcpmq4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L376)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Instead of `queryDraining` and `s.IsQueryDraining()`, you can use `s.isDraining()` which returns starts returning true after entering the draining phases. 
</blockquote></details>

The reason to introduce the `queryDraining` var is to decouple "disallow new connections" and "drain idel connections that are without queries in flight".  `s.IsDraining()` now only takes care of the former , and the latter is enabled when `s.IsQueryDraining()` returns true. 
But yes the naming is confusing. Maybe `s.IsDraining()` should be renamed as `s.IsDrainingConnections()` and `s.IsQueryDraining()` should be `s.IsDrainingQueries()`?



_Code quote:_
```Go
func (s *Server) IsQueryDraining() bool {
```
___
*[pkg/sql/pgwire/server.go, line 473 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MugiwWs77Q8UGyhDWj3:-Mul9vD9A_o2sFTUk1Zq:bq7g62r) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L473)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

“waits for the users” Might be best to change the wording here as well, since all of the connections don’t need to be closed during connection wait. Something like: "... waits for SQL connections to close for the duration of connectionWait “
Also might be best to change the function name to make it clearer that this is a wait - that the server is not draining SQL connections here. `WaitForDrainConnections` perhaps

</blockquote></details>

Yes makes sense, done.
___
*[pkg/sql/pgwire/server.go, line 541 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MughqmG-fBBk4wzqmwz:-MulcNf70TUQfgBscKQ6:bh2bzsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L541)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

We can be more descriptive here with something like: “draining remaining SQL connections, will timeout after %s”
</blockquote></details>

Added more lines to the log message. (In fact, I may have made it too verbose. You think?)
___
*[pkg/sql/pgwire/server.go, line 571 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugh8Vg7J8JeI5znscT:-MuldCB2A1r5DUxTIqQH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L571)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Noticed this pre-existing comment that incorrectly says drainWait instead o [...]

2022-02-01 01:26 UTC, cameronnunez requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugf7Cs0raBaLceU8C7:-Mumlz4Y0bdD9oqLIzAf:bhilao) (no related file):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

@cameronnunez Thanks for reviewing!
I'm preparing the tests as well. Will add them to this PR once ready.

For the log message, I added more info about the current draining stage, along with which cluster session variable to set its duration. 

</blockquote></details>

Regarding the draining bools, we need to do something different here.

Before the changes being made here, the rejection of new SQL connections would only happen during draining (i.e. after the waiting portion is done). Naturally, for this reason, `s.isDraining()` has been synonymous with the rejection of connections.

However, with your changes, this is no longer true - rejection will now start earlier in the process. 
Draining implies rejection, but rejection will no longer imply draining.

So what we need are two separate bools: 
`s.mu.draining` and `s.mu.rejectingConn` (new)

Changes needed for this:
* Updating the function `registerConn` by replacing `s.mu.draining` with `s.mu.rejectingConn`
* Creating a function `s.setRejectingConnLocked`
* Use`s.setRejectingConnLocked(true)` at the start of WaitForDrainConnections
* Put back `setDrainingLocked(true)` where it originally was since we now have a separate rejection bool
* The description for `IsDraining()` needs to be updated. (e.g. //IsDraining returns true if the server started draining client connections). 
* Updating the function `s.Undrain()` by using `s.setRejectionLocked(false)` in addition to `s.setDrainingLocked(false)`

---
___
*[pkg/server/server_sql.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MugiFJF14RXdsn7yK5h:-MumntaXCTQx2u7yPICY:bktl7sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/server/server_sql.go#L162)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Updated the comments.
I'd prefer keeping it as `isHealthcheckReady`, because`isReady` can be ambiguous (e.g. can be wrongly interpreted as the server is (not) ready for _SQL queries_)
</blockquote></details>

We don't think in terms of readiness in such situations. We think of a node as not ready only when the health check fails. Non-readiness happens in two conditions: (1) when user traffic should not be directed to the node or (2) the node is unable to communicate with most of the nodes in the cluster. 
___
*[pkg/sql/pgwire/server.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MughLX74h_72pn6QCOl:-MumstFADNb5Oohj1lEU:bj1z03r) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L376)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

The reason to introduce the `queryDraining` var is to decouple "disallow new connections" and "drain idel connections that are without queries in flight".  `s.IsDraining()` now only takes care of the former , and the latter is enabled when `s.IsQueryDraining()` returns true. 
But yes the naming is confusing. Maybe `s.IsDraining()` should be renamed as `s.IsDrainingConnections()` and `s.IsQueryDraining()` should be `s.IsDrainingQueries()`?
</blockquote></details>

See main comment above.


<!-- Sent from Reviewable.io -->

2022-02-01 17:43 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @rafiss)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugf7Cs0raBaLceU8C7:-MunPN8TCkjyM8pQS7QW:b-ipp0yd) (no related file):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Regarding the draining bools, we need to do something different here.

Before the changes being made here, the rejection of new SQL connections would only happen during draining (i.e. after the waiting portion is done). Naturally, for this reason, `s.isDraining()` has been synonymous with the rejection of connections.

However, with your changes, this is no longer true - rejection will now start earlier in the process. 
Draining implies rejection, but rejection will no longer imply draining.

So what we need are two separate bools: 
`s.mu.draining` and `s.mu.rejectingConn` (new)

Changes needed for this:
* Updating the function `registerConn` by replacing `s.mu.draining` with `s.mu.rejectingConn`
* Creating a function `s.setRejectingConnLocked`
* Use`s.setRejectingConnLocked(true)` at the start of WaitForDrainConnections
* Put back `setDrainingLocked(true)` where it originally was since we now have a separate rejection bool
* The description for `IsDraining()` needs to be updated. (e.g. //IsDraining returns true if the server started draining client connections). 
* Updating the function `s.Undrain()` by using `s.setRejectionLocked(false)` in addition to `s.setDrainingLocked(false)`

</blockquote></details>

Thanks for the detailed instruction! 
All suggested changes are valid except for "Put back setDrainingLocked(true) where it originally was since we now have a separate rejection bool". Originally, `setDrainingLocked(true)` is only called when the server starts draining SQL queries. I think now the true starting point of the "draining process" is when the server starts draining SQL connections. 

---
___
*[pkg/server/server_sql.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MugiFJF14RXdsn7yK5h:-Munfwu4A2uZpYa2FYq7:bogzeyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/server/server_sql.go#L162)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

We don't think in terms of readiness in such situations. We think of a node as not ready only when the health check fails. Non-readiness happens in two conditions: (1) when user traffic should not be directed to the node or (2) the node is unable to communicate with most of the nodes in the cluster. 
</blockquote></details>

Makes sense, done renaming it to `isReady`.
___
*[pkg/sql/pgwire/server.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MughLX74h_72pn6QCOl:-Mung4SH7DMF3JEyaPu4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc915d9d27da47b2b3f9693069b94b5cbb6c23f1/pkg/sql/pgwire/server.go#L376)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

See main comment above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-01 17:51 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @rafiss)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugf7Cs0raBaLceU8C7:-MuqN_6g6g5r7gpoM8k4:bhgmxau) (no related file):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Thanks for the detailed instruction! 
All suggested changes are valid except for "Put back setDrainingLocked(true) where it originally was since we now have a separate rejection bool". Originally, `setDrainingLocked(true)` is only called when the server starts draining SQL queries. I think now the true starting point of the "draining process" is when the server starts draining SQL connections. 
</blockquote></details>

Note that I added the following changes:
1. The `pgserver.mu.draining` is now set to `true` when the server starts draining SQL connections;
2. The `remaining` SQL queries are not recorded via the `reporter` callback in `pgServer.drainImpl()` now;
3. Originally, if there are "remaining" SQL queries and range leases after a draining iteration, the `pgServer.drainImpl()` will be called again, but actually this is a no-op. Now the draining of SQL connections and queries is only going to be triggered once. 

For 2 and 3, see more discussion [here](https://cockroachlabs.slack.com/archives/C01CDD4HRC5/p1643695002810989).

---


<!-- Sent from Reviewable.io -->

2022-02-01 18:53 UTC, cameronnunez reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, and @ZhouXing19)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugf7Cs0raBaLceU8C7:-MuqbUI86npUFqRkjhuy:b-rpdx34) (no related file):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Note that I added the following changes:
1. The `pgserver.mu.draining` is now set to `true` when the server starts draining SQL connections;
2. The `remaining` SQL queries are not recorded via the `reporter` callback in `pgServer.drainImpl()` now;
3. Originally, if there are "remaining" SQL queries and range leases after a draining iteration, the `pgServer.drainImpl()` will be called again, but actually this is a no-op. Now the draining of SQL connections and queries is only going to be triggered once. 

For 2 and 3, see more discussion [here](https://cockroachlabs.slack.com/archives/C01CDD4HRC5/p1643695002810989).

</blockquote></details>

The drain sequence should be understood as the following:
1. Initial wait (node becomes unready)
2. Wait for clients to close SQL connections (**rejecting connections begins**)
3. Drain SQL connections (**draining begins**)
4. Drain leases & leadership

There is no notion of draining queries; the server drains connections as their corresponding queries finish. `setDrainingLocked(true)` in its current location happens at the beginning of `drainImpl`, and so the beginning of draining.

---


<!-- Sent from Reviewable.io -->

2022-02-01 19:16 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @rafiss)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugf7Cs0raBaLceU8C7:-MuqheBn51L-Ppb5jRt8:b-6qkl27) (no related file):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

The drain sequence should be understood as the following:
1. Initial wait (node becomes unready)
2. Wait for clients to close SQL connections (**rejecting connections begins**)
3. Drain SQL connections (**draining begins**)
4. Drain leases & leadership

There is no notion of draining queries; the server drains connections as their corresponding queries finish. `setDrainingLocked(true)` in its current location happens at the beginning of `drainImpl`, and so the beginning of draining.
</blockquote></details>

Ah I see, thanks!
Have put `setDrainingLocked(true)` back to `drainImpl`, and updated the log messages as well.

---


<!-- Sent from Reviewable.io -->

2022-02-01 23:32 UTC, ZhouXing19 commented
The `reporter` callback is put back to `pgServer.drainImpl()`, since we need it for the API responses of `cockroach node drain`.

2022-02-15 22:07 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, and @ZhouXing19)

___
*[-- commits, line 61 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzNHkg6aYG_tW8Nj_w):*
refer to the categories here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#Categories

i think this should just be `Release note (ops change)`
___
*[pkg/cmd/roachtest/tests/draining.go, line 26 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzOB-xB6T6Hde-cROl:-MvzOB-xB6T6Hde-cROm:b39caix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/cmd/roachtest/tests/draining.go#L26)):*
> ```Go
> 
> 		r.Add(registry.TestSpec{
> 			Name:    fmt.Sprintf("sqlexp/draining-early-exit-conn-wait"),
> ```

nit: rename to `draining/early-exit-conn-wait`

(no need to put the team name in the test name)
___
*[pkg/cmd/roachtest/tests/draining.go, line 35 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzOIoY6ZSmUelNrZM8:-MvzOIoY6ZSmUelNrZM9:b-gn21el) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/cmd/roachtest/tests/draining.go#L35)):*
> ```Go
> 
> 		r.Add(registry.TestSpec{
> 			Name:    fmt.Sprintf("sqlexp/draining-early-exit-query-wait"),
> ```

nit: rename to `draining/early-exit-query-wait`
___
*[pkg/cmd/roachtest/tests/draining.go, line 58 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzOW5B4tcFNpLobAp1:-MvzOW5B4tcFNpLobAp2:bij5xix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/cmd/roachtest/tests/draining.go#L58)):*
> ```Go
> 	connectionWaitDurationSec := 200
> 	queryWaitDurationSec := 20
> 	totalWaitDurationSec := drainWaitDurationSec + connectionWaitDurationSec + queryWaitDurationSec
> ```

nit: all of these could be const too?
___
*[pkg/cmd/roachtest/tests/draining.go, line 144 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzPD0u0OJ9d5hpYzH8:-MvzPD0u0OJ9d5hpYzH9:bacfvt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/cmd/roachtest/tests/draining.go#L144)):*
> ```Go
> 
> 	result, err = c.RunWithDetailsSingleNode(ctx, t.L(), c.Node(nodeToDrain),
> 		"curl", fmt.Sprintf("http://%s/health\\?ready\\=1",
> ```

it would be useful to move the `curl` and reading the response into a separate function, since it's called multiple times
___
*[pkg/cmd/roachtest/tests/draining.go, line 201 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzPYhSEdfnbUxIetaK:-MvzPYhSEdfnbUxIetaL:bkmhj0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/cmd/roachtest/tests/draining.go#L201)):*
> ```Go
> 	row := randConn.QueryRowContext(ctx, "SELECT 1;")
> 	if row.Err() != nil {
> 		t.Fatal("cannot run query before the server draining SQL connections")
> ```

nit: `t.Fatal(errors.Wrap(...))`
___
*[pkg/cmd/roachtest/tests/draining.go, line 204 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzPb30458WbfQmSucy:-MvzPb30458WbfQmSucz:b32w1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/cmd/roachtest/tests/draining.go#L204)):*
> ```Go
> 	}
> 	if err := row.Scan(&queryRes); err != nil {
> 		t.Fatal("cannot scan the result from query")
> ```

nit: `t.Fatal(errors.Wrap(...))` 
___
*[pkg/cmd/roachtest/tests/draining.go, line 207 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzPi23B5dOUeEh3Rai:-MvzPi23B5dOUeEh3Raj:b-z2ytje) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/cmd/roachtest/tests/draining.go#L207)):*
> ```Go
> 	}
> 
> 	t.L().Printf("query succeed: %s", queryRes)
> ```

nit: "succeeded"
also, don't need queryRes here, since we don't actually care about it
___
*[pkg/cmd/roachtest/tests/draining.go, line 243 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzQ3bI9bTq-80eZAGh:-MvzQ3bI9bTq-80eZAGi:b-mtyz69) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/cmd/roachtest/tests/draining.go#L243)):*
> ```Go
> 	connectionWaitDurationSec := 10
> 	queryWaitDurationSec := 200
> 	totalWaitDurationSec := drainWaitDurationSec + connectionWaitDurationSec + queryWaitDurationSec
> ```

nit: could these  be const?
___
*[pkg/server/admin.go, line 1817 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzDEP-A2nh07N3Gwq5:-MvzDEP-A2nh07N3Gwq6:b7xt12u) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/server/admin.go#L1817)):*
> ```Go
> 		return status.Errorf(
> 			codes.Unavailable,
> 			"node is not ready for new SQL clients (healthcheck endpoint returns "+
> ```

i think we can remove the part of the message in parentheses
___
*[pkg/server/drain.go, line 327 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzGoU3-5PQmrHBFfcg:-MvzGoU3-5PQmrHBFfch:b-5nmi4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/server/drain.go#L327)):*
> ```Go
> 	// Log the number of connections periodically.
> 	if err := s.logActiveConns(ctx); err != nil {
> 		log.Ops.Info(ctx, fmt.Sprintf("error showing alive SQL connections: %v", err))
> ```

nit: perhaps it should be a `log.Ops.Warning` if it's not expected to have an error
___
*[pkg/server/drain.go, line 336 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzGSHs4sRHKJdrcZJK:-MvzGSHs4sRHKJdrcZJL:bcxyb48) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/server/drain.go#L336)):*
> ```Go
> 		drainWaitDuration := drainWait.Get(&s.sqlServer.execCfg.Settings.SV)
> 		drainWaitLogMessage := fmt.Sprintf(
> 			"node enters the unready status, health checkpoint starts to report "+
> ```

nit on phrasing. should it be something more like:

"node is entering the unready state, and the /healthz?ready=1 healthcheck endpoint will report the shutting-down status; proceeding to the next draining phase after %s (configured by 'server.shutdown.drain_wait')"
___
*[pkg/server/drain.go, line 349 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzHntUBcuj4jg69q93:-MvzHntUBcuj4jg69q94:b-4bygje) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/server/drain.go#L349)):*
> ```Go
> 	connectionMaxWait := connectionWait.Get(&s.sqlServer.execCfg.Settings.SV)
> 
> 	//if err := s.sqlServer.pgServer.Drain(ctx, queryMaxWait, reporter); err != nil {
> ```

remove commented code
___
*[pkg/server/server_sql.go, line 160 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzICh65lWO_Ywi5N_B:-MvzICh65lWO_Ywi5N_C:bgx60n) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/server/server_sql.go#L160)):*
> ```Go
> 	connManager netutil.Server
> 
> 	// TODO (janexing): Is the health checkpoint /health?ready=1 only used by
> ```

i think the TODO can be removed. (the answer is yes, `/health?ready=1` is only expected to be used by load balancers)
___
*[pkg/sql/pgwire/server.go, line 465 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzJ-qjEhnmdoDUiAqf:-MvzJ-qjEhnmdoDUiAqg:blsestw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/sql/pgwire/server.go#L465)):*
> ```Go
> // s.mu must be locked.
> func (s *Server) setRejectingSqlConnLocked(reject bool) bool {
> 	if s.mu.rejectingNewSqlConn == reject {
> ```

it seems like `setRejectingSqlConnLocked` is only used in one place. i think this code should be moved inside of `DisallowNewSQLConn`, and `setRejectingSqlConnLocked` should be removed

this helps preve [...]

2022-02-16 00:05 UTC, cameronnunez reviewed
Btw this PR will need conflict resolution with the new comments update.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-:-Mvzh9te9dkxKP04xuMJ:bt40bgk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, and @ZhouXing19)

___
*[pkg/server/admin.go, line 1817 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mvzf3Fz-vowjT-oYi5R:-Mvzf3Fz-vowjT-oYi5S:b-h8uscl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/admin.go#L1817)):*
> ```Go
> 		return status.Errorf(
> 			codes.Unavailable,
> 			"node is not ready for new SQL clients (healthcheck endpoint returns "+
> ```

Simplify to "node is not ready".
___
*[pkg/server/drain.go, line 49 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mvzizgj0-k_tnlF7F7R:-Mvzizgj0-k_tnlF7F7S:b-rhc2lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L49)):*
> ```Go
> 		"the amount of time a server waits in an unready state before proceeding with the rest "+
> 			"of the shutdown process "+
> 			"(note that the --drain-wait parameter for cockroach node drain may need adjustment "+
> ```

I should have highlighted that `drainWait` and `--drain-wait` are not the same in my comments update PR but overlooked it. Mind making this clear here?
___
*[pkg/server/drain.go, line 58 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzhjlWBp7_C1oCiHh7:-MvzhjlWBp7_C1oCiHh8:b28b4ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L58)):*
> ```Go
> 		settings.TenantReadOnly,
> 		"server.shutdown.connection_wait",
> 		"the maximum amount of time a server waits all SQL connections to be "+
> ```

Should mention that we skip the step for draining SQL connections if we early exit here. Also need to reduce the length of this description.
___
*[pkg/server/drain.go, line 59 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvziUnp58SCas-VEiQ1:-MvziUnp58SCas-VEiQ2:blccnrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L59)):*
> ```Go
> 		"server.shutdown.connection_wait",
> 		"the maximum amount of time a server waits all SQL connections to be "+
> 			"closed before proceeding with the rest of the shutdown process. "+
> ```

"before proceeding with a drain"
___
*[pkg/server/drain.go, line 335 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzOn-iDto35f56wleT:-MvzOn-iDto35f56wleU:b-qepcuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L335)):*
> ```Go
> 	if shouldDelayDraining {
> 		drainWaitDuration := drainWait.Get(&s.sqlServer.execCfg.Settings.SV)
> 		drainWaitLogMessage := fmt.Sprintf(
> ```

Log message is too verbose. Those who comb the logs often will be overburdened with repetitive info. Let's keep it short. Something like  "waiting for health probes to notice that the node is not ready..." Also, we can remove the log var, and instead inline the log messages and the use of the API i.e. `log.Ops.Info(ctx, "waiting for health probes to notice that the node is not ready...")`
___
*[pkg/server/drain.go, line 349 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzfkkX7oBPVA2-fbWn:-MvzfkkX7oBPVA2-fbWo:beqk9rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L349)):*
> ```Go
> 	connectionMaxWait := connectionWait.Get(&s.sqlServer.execCfg.Settings.SV)
> 
> 	//if err := s.sqlServer.pgServer.Drain(ctx, queryMaxWait, reporter); err != nil {
> ```

I think `pgServer.Drain` should be left as is. Instead of having `WaitSqlDraining` and `waitSqlQueryDraining`, let's stick with simply doing `WaitForClosedConns` (a renaming of `waitSqlConnDraining`) before`pgServer.Drain`.
___
*[pkg/sql/pgwire/server.go, line 437 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzmkdWD7_rmqpRFzeP:-MvzmkdWD7_rmqpRFzeQ:beb7rnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/sql/pgwire/server.go#L437)):*
> ```Go
> // been done by the time this call returns. See the explanation in
> // pkg/server/drain.go for details.
> func (s *Server) waitSqlQueryDraining(
> ```

I would leave this code as it was because this is the step when draining truly begins. And the draining state is set to true with the call to`drainImpl`. Also as mentioned before, queries do not "drain"; connections do. 
___
*[pkg/sql/pgwire/server.go, line 512 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzkaVN7Mj8lLrebRUE:-MvzkaVN7Mj8lLrebRUF:be2vnyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/sql/pgwire/server.go#L512)):*
> ```Go
> }
> 
> // waitSqlConnDraining waits for SQL connections to be closed for the
> ```

nit: "waits for clients to close SQL connections"
___
*[pkg/sql/pgwire/server.go, line 514 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzkODp507SrcRwJD2O:-MvzkODp507SrcRwJD2P:b-2l8ntm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/sql/pgwire/server.go#L514)):*
> ```Go
> // waitSqlConnDraining waits for SQL connections to be closed for the
> // duration of connectionWait.
> // During the connectionWait period, no new SQL connections are allowed, and as
> ```

replace with "With this phase, the node starts rejecting SQL connections" since the rejection is maintained beyond this phase.
___
*[pkg/sql/pgwire/server.go, line 525 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzkydS3JVDgpiTQMr3:-MvzkydS3JVDgpiTQMr4:bdihvce) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/sql/pgwire/server.go#L525)):*
> ```Go
> 
> 	connectionWaitLogMessage := fmt.Sprintf(
> 		"waiting for SQL connections to be closed, no new SQL connections "+
> ```

See my above comment on log verbosity. Let's stick to a one or two liner. 
___
*[pkg/sql/pgwire/server.go, line 610 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzLJzWD5TELqq3UrLW:-MvzLJzWD5TELqq3UrLX:b-ud9k9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/sql/pgwire/server.go#L610)):*
> ```Go
> 
> 	queryWaitLogMessage := fmt.Sprintf(
> 		"draining remaining SQL connections that are without queries in "+
> ```

See my above comment on log verbosity. I'd keep it short to something that succinctly does the job of highlighting the start of the phase. Something like: "starting drain. draining the SQL layer..."
___
*[pkg/sql/pgwire/server.go, line 1301 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzKrxC6P8dDJu5JP9S:-MvzKrxC6P8dDJu5JP9T:b2o3fe2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/sql/pgwire/server.go#L1301)):*
> ```Go
> func (s *Server) registerConn(
> 	ctx context.Context,
> ) (newCtx context.Context, rejectingNewSqlConn bool, onCloseFn func()) {
> ```

nit: IMHO we can simplify some of these var names and func names to remove terms like "new" and "SQL" since those are implied. here specifically, `rejectConn` looks cleaner alongside `registerConn` to me


<!-- Sent from Reviewable.io -->

2022-02-17 04:45 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, and @ZhouXing19)

___
*[-- commits, line 61 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzNHkg6aYG_tW8Nj_w):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

refer to the categories here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#Categories

i think this should just be `Release note (ops change)`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 144 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzPD0u0OJ9d5hpYzH8:-Mw4uDVm0BeOx2HiQRgR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/cmd/roachtest/tests/draining.go#L144)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it would be useful to move the `curl` and reading the response into a separate function, since it's called multiple times
</blockquote></details>

Done.
___
*[pkg/server/admin.go, line 1817 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzDEP-A2nh07N3Gwq5:-Mw4v0-Z2P4SbU7lV70w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/server/admin.go#L1817)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we can remove the part of the message in parentheses
</blockquote></details>

Done.
___
*[pkg/server/admin.go, line 1817 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mvzf3Fz-vowjT-oYi5R:-Mw4v5iDB0Q7aIjbg-g-:bjl5iv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/admin.go#L1817)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Simplify to "node is not ready".
</blockquote></details>

Changed it back to "node is not accepting SQL clients".
___
*[pkg/server/drain.go, line 336 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzGSHs4sRHKJdrcZJK:-Mw4uiepAseq_-P1Zrxt:boyexb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/server/drain.go#L336)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit on phrasing. should it be something more like:

"node is entering the unready state, and the /healthz?ready=1 healthcheck endpoint will report the shutting-down status; proceeding to the next draining phase after %s (configured by 'server.shutdown.drain_wait')"

</blockquote></details>

Done. Thanks!
___
*[pkg/server/drain.go, line 349 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzHntUBcuj4jg69q93:-Mw4vhdHBjSUa7784eoD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/server/drain.go#L349)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

remove commented code
</blockquote></details>

Done.
___
*[pkg/server/drain.go, line 49 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mvzizgj0-k_tnlF7F7R:-Mw4vALJ7TNTLKbssEdW:b25ngct) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L49)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

I should have highlighted that `drainWait` and `--drain-wait` are not the same in my comments update PR but overlooked it. Mind making this clear here?
</blockquote></details>

Added explanatory lines.
___
*[pkg/server/drain.go, line 58 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzhjlWBp7_C1oCiHh7:-Mw4vLG8AeN3fJPGjHRU:byhjfqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L58)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Should mention that we skip the step for draining SQL connections if we early exit here. Also need to reduce the length of this description.
</blockquote></details>

Rephrased it to "proceeds to draining range leases".
___
*[pkg/server/drain.go, line 59 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvziUnp58SCas-VEiQ1:-Mw4yy0N6zbfrIiHIp-X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L59)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

"before proceeding with a drain"
</blockquote></details>

Done.
___
*[pkg/server/drain.go, line 335 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzOn-iDto35f56wleT:-Mw4vzo13LJ9CAMTHiM5:bzcbxzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L335)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Log message is too verbose. Those who comb the logs often will be overburdened with repetitive info. Let's keep it short. Something like  "waiting for health probes to notice that the node is not ready..." Also, we can remove the log var, and instead inline the log messages and the use of the API i.e. `log.Ops.Info(ctx, "waiting for health probes to notice that the node is not ready...")`
</blockquote></details>

I think it would be helpful to provide more information in the log message, as it would make troubleshooting easier. The user or the operator would quickly know what the duration was set to and which cluster setting should be adjusted to change it. It is true that this will seem verbose, but since these log messages will only get printed once per draining, I don't think they will take up too much log space.
___
*[pkg/server/drain.go, line 349 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzfkkX7oBPVA2-fbWn:-Mw4ulH75zzM7xQj1-3O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L349)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

I think `pgServer.Drain` should be left as is. Instead of having `WaitSqlDraining` and `waitSqlQueryDraining`, let's stick with simply doing `WaitForClosedConns` (a renaming of `waitSqlConnDraining`) before`pgServer.Drain`.
</blockquote></details>

Done.
___
*[pkg/server/server_sql.go, line 160 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzICh65lWO_Ywi5N_B:-Mw4umD284C075U1SX-b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/server/server_sql.go#L160)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think the TODO can be removed. (the answer is yes, `/health?ready=1` is only expected to be used by load balancers)
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 465 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzJ-qjEhnmdoDUiAqf:-Mw4uqJO-9WtSg3P5WIJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/sql/pgwire/server.go#L465)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it seems like `setRejectingSqlConnLocked` is only used in one place. i think this code should be moved inside of `DisallowNewSQLConn`, and `setRejectingSqlConnLocked` should be removed

this helps prevent a mistake where somebody calls `setRejectingSqlConnLocked` without realizing they need to take the lock first

(also, it looks like the return value is not ever used, so we could simplify things by not returning it)
</blockquote></details>

Done [...]

2022-02-18 21:44 UTC, cameronnunez reviewed
I think a key aspect that needs to be tested here is whether a warning is logged if the client did not close all the connections i.e. if `connectionWait` expires, need to verify that a warning exists.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-:-MwDgEuz0WoJZutawt47:b-vhh2ln)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, and @ZhouXing19)

___
*[pkg/cmd/roachtest/tests/draining.go, line 20 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDOePV6EhaZCQIE2BM:-MwDOePV6EhaZCQIE2BN:bomdzkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L20)):*
> ```Go
> )
> 
> func registerDraining(r registry.Registry) {
> ```

simplify to `registerDrain` and `drain/conn-wait`
___
*[pkg/cmd/roachtest/tests/draining.go, line 48 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDQuR4CJYeJc75u_G-:-MwDQuR4CJYeJc75u_G0:b-9hhfqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L48)):*
> ```Go
> // draining phase if all connections are closed by user before the
> // duration set by `server.shutdown.connection_wait` times out.
> func testEarlyExitInConnectionWait(
> ```

the standard is the `run` prefix here. I recommend `func runDrainConnectionWait`
___
*[pkg/cmd/roachtest/tests/draining.go, line 77 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDP8ly5e2zkxswOfGG:-MwDP8ly5e2zkxswOfGH:b-7hmgrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L77)):*
> ```Go
> 	nodeToDrain := 1
> 	db := c.Conn(ctx, t.L(), nodeToDrain)
> 	defer func() {
> ```

nit: `defer db.Close()`
___
*[pkg/cmd/roachtest/tests/draining.go, line 89 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDRVq6EIrJnO-cqH9K:-MwDRVq6EIrJnO-cqH9L:blg3n21) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L89)):*
> ```Go
> 	for j := 0; j < 2; j++ {
> 		conn, err := db.Conn(ctx)
> 		if err != nil {
> ```

use `require.NoErrorf` throughout in instead of `t.Fatal`
___
*[pkg/cmd/roachtest/tests/draining.go, line 113 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDUz0T0zWCx6IFbx_g:-MwDUz0T0zWCx6IFbx_h:b3cvcxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L113)):*
> ```Go
> 	// Start draining the node.
> 	var m *errgroup.Group
> 	m, ctx = errgroup.WithContext(ctx)
> ```

Use `c.NewMonitor`.
___
*[pkg/cmd/roachtest/tests/draining.go, line 125 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDTh0U1Qsid8G5Vjkn:-MwDTh0U1Qsid8G5Vjko:b-qnppsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L125)):*
> ```Go
> 	drainStartTimestamp := time.Now()
> 
> 	// Make sure we're in the middle of the phase set by `server.shutdown.drain_wait`.
> ```

There hasn't been any changes to the nature of how the first wait works so I don't think the testing for that here is necessary. 
___
*[pkg/cmd/roachtest/tests/draining.go, line 159 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDWFEZ5wHxNxhsSKms:-MwDWFEZ5wHxNxhsSKmt:b-pg0tkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L159)):*
> ```Go
> 	conns = append(conns, newConn)
> 
> 	// Sleep till the server is in the status of waiting users to close SQL
> ```

nit: "waiting for users"
___
*[pkg/cmd/roachtest/tests/draining.go, line 161 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDVe-m-y1DTAWIYpxz:-MwDVe-m-y1DTAWIYpy-:bwcqij8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L161)):*
> ```Go
> 	// Sleep till the server is in the status of waiting users to close SQL
> 	// connections. No new SQL connections are allowed now.
> 	time.Sleep((pokeHealthAfterConnDrainTimestamp - pokeHealthBeforeConnDrainTimestamp) * time.Second)
> ```

I think this test should just proceed to this step, since the functionality of drain prior to this is unchanged. This will narrow the focus of the roachtest on `connectionWait` rather than draining in general for which testing already exists (for the code that is unchanged).

Also, comment here that we are verifying that new connections are rejected.
___
*[pkg/cmd/roachtest/tests/draining.go, line 168 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDWUTf6keQJCj0PlwQ:-MwDWUTf6keQJCj0PlwR:b-ya3rca) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L168)):*
> ```Go
> 	} else {
> 		t.Fatal(errors.New("new SQL connections should not be allowed when the server " +
> 			"starts waiting the user to close SQL connections."))
> ```

nit: "waiting for the user"
___
*[pkg/cmd/roachtest/tests/draining.go, line 171 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDWqzhCh-SljVBhLHJ:-MwDWqzhCh-SljVBhLHK:b-aqm4o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L171)):*
> ```Go
> 	}
> 
> 	if db.Stats().OpenConnections != 3 {
> ```

Use `require.Equalf(t, db.Stats().OpenConnections, 3, <error message>)`
___
*[pkg/cmd/roachtest/tests/draining.go, line 178 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDXDPD1P0pYI8CWdvo:-MwDXDPD1P0pYI8CWdvp:b-oh4pq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L178)):*
> ```Go
> 	randConn := conns[rand.Intn(len(conns))]
> 
> 	// Before the server starts draining SQL connections (enter the phase whose
> ```

Comment here that we are verifying that queries do not fail. nit: "(i.e. the phase whose)" 

error message: "expected query not to fail"
___
*[pkg/cmd/roachtest/tests/draining.go, line 188 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDfh083DHuLFN9OWrL:-MwDfh083DHuLFN9OWrM:bx2fg2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L188)):*
> ```Go
> 	for _, conn := range conns {
> 		if err := conn.Close(); err != nil {
> 			t.Fatal(errors.Wrap(err, "cannot close connection when the server "+
> ```

for the error message we want something like "expected connection to be able to be successfully closed client-side"
___
*[pkg/cmd/roachtest/tests/draining.go, line 213 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDSzbL09-4VISScNmg:-MwDSzbL09-4VISScNmh:bdulbzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L213)):*
> ```Go
> // draining phase if all SQL queries are finished before the
> // duration set by `server.shutdown.query_wait` times out.
> func testEarlyExitInQueryWait(
> ```

I don't think this test is needed. One roachtest specific to `connectionWait` should be sufficient since we're keeping `pgServer.Drain` and testing already exists for that.
___
*[pkg/server/drain.go, line 335 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzOn-iDto35f56wleT:-MwDA9cMEb8O6C1pEdkB:b-kwve84) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L335)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

I think it would be helpful to provide more information in the log message, as it would make troubl [...]

2022-02-22 01:53 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @rafiss)

___
*[pkg/cmd/roachtest/tests/draining.go, line 20 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDOePV6EhaZCQIE2BM:-MwS-w19CPfs2ED0A9bT:b-ymmysf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L20)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

simplify to `registerDrain` and `drain/conn-wait`
</blockquote></details>

I kept two tests: `drain/early-exit-conn-wait`, `drain/warn-conn-wait-timeout`. The first is to verify the server early exits when all conns are closed during conn_wait, and the second is to verify that the warning is logged if there're remaining connections when conn_wait times out.
___
*[pkg/cmd/roachtest/tests/draining.go, line 48 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDQuR4CJYeJc75u_G-:-MwS-xN17i7SiV6GsHoc:bwkp45v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L48)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

the standard is the `run` prefix here. I recommend `func runDrainConnectionWait`
</blockquote></details>

renamed it to `runEarlyExitInConnectionWait`. 
___
*[pkg/cmd/roachtest/tests/draining.go, line 77 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDP8ly5e2zkxswOfGG:-MwS13OhDu1trVSAsCK6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L77)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: `defer db.Close()`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 89 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDRVq6EIrJnO-cqH9K:-MwS19495njGolk0lISi:b-hf9vpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L89)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

use `require.NoErrorf` throughout in instead of `t.Fatal`
</blockquote></details>

Done. But just curious why we don't use `t.Fatal` or `t.Fatalf`, since they seem common in other roachtests. 
___
*[pkg/cmd/roachtest/tests/draining.go, line 113 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDUz0T0zWCx6IFbx_g:-MwS1d5O1_P_0hJQNRZ1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L113)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Use `c.NewMonitor`.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 125 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDTh0U1Qsid8G5Vjkn:-MwS29Kx9SzbSgqxU_Pb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L125)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

There hasn't been any changes to the nature of how the first wait works so I don't think the testing for that here is necessary. 
</blockquote></details>

Done.



_Code quote:_
```Go
Make sure we're in the middle of the phase set by `server.shutdown.drain_wait`
```
___
*[pkg/cmd/roachtest/tests/draining.go, line 159 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDWFEZ5wHxNxhsSKms:-MwS2CPM39FA1J_cesSd:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L159)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: "waiting for users"
</blockquote></details>

Done
___
*[pkg/cmd/roachtest/tests/draining.go, line 161 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDVe-m-y1DTAWIYpxz:-MwS3NRf2NHDe_QtGaut:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L161)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

I think this test should just proceed to this step, since the functionality of drain prior to this is unchanged. This will narrow the focus of the roachtest on `connectionWait` rather than draining in general for which testing already exists (for the code that is unchanged).

Also, comment here that we are verifying that new connections are rejected.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 168 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDWUTf6keQJCj0PlwQ:-MwS3Nqh82tHlKvVP27C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L168)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: "waiting for the user"
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 171 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDWqzhCh-SljVBhLHJ:-MwS3QMLEWu01Gqiq4tn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L171)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Use `require.Equalf(t, db.Stats().OpenConnections, 3, <error message>)`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 178 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDXDPD1P0pYI8CWdvo:-MwS5UWq5B3dvk6tBQRw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L178)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Comment here that we are verifying that queries do not fail. nit: "(i.e. the phase whose)" 

error message: "expected query not to fail"
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 188 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDfh083DHuLFN9OWrL:-MwS43UT-UGTJ_a9X2ee:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L188)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

for the error message we want something like "expected connection to be able to be successfully closed client-side"
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 213 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDSzbL09-4VISScNmg:-MwS44Yl-lEN-NqoX3k_:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L213)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

I don't think this test is needed. One roachtest specific to `connectionWait` should be sufficient since we're keeping `pgServer.Drain` and testing already exists for that.
</blockquote></details>

Removed.
___
*[pkg/server/drain.go, line 335 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzOn-iDto35f56wleT:-MwS466oAf4lqQ2sOxJV:bbucziz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/server/drain.go#L335)):*
<details><summary><i>Previously, c [...]

2022-02-23 18:04 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, and @ZhouXing19)

___
*[pkg/cmd/roachtest/tests/draining.go, line 75 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwbb7IG7CU4NA208aew:-Mwbb7IG7CU4NA208aex:b-dkzsjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/cmd/roachtest/tests/draining.go#L75)):*
> ```Go
> 		// drainWaitDurationSec, but smaller than (drainWaitDurationSec +
> 		// connectionWaitDurationSec).
> 		pokeDuringConnWaitTimestamp = 25
> ```

nit: make all of these Duration types, instead of ints. then you can also simplify the names
```
		drainWaitDuration      = 10 * time.Second
		connectionWaitDuration = 60 * time.Second
		queryWaitDuration      = 10 * time.Second
		pokeDuringConnWaitTimestamp = 25 * time.Second
```
___
*[pkg/cmd/roachtest/tests/draining.go, line 86 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbbRNk5TQgA6WBSxab:-MwbbRNk5TQgA6WBSxac:b-b2db8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/cmd/roachtest/tests/draining.go#L86)):*
> ```Go
> 	defer db.Close()
> 
> 	db.SetConnMaxLifetime(30 * time.Second)
> ```

nit: should there also be a const for `const connMaxLifetime = 30 * time.Second`, defined in the same place as the others?

this way it's easier to see why we've chosen all these times
___
*[pkg/cmd/roachtest/tests/draining.go, line 176 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbboCVB8EynaFzuJTQ:-MwbboCWBgrGyFZR2r4x:bw2jglz) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/cmd/roachtest/tests/draining.go#L176)):*
> ```Go
> 		drainWaitDurationSec      = 0
> 		connectionWaitDurationSec = 10
> 		queryWaitDurationSec      = 20
> ```

nit: again, use ` * time.Second` here, and remove `Sec` from the names
___
*[pkg/server/drain.go, line 353 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwbj65o4InreIzHAa3i:-Mwbj65o4InreIzHAa3j:ba4egfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/server/drain.go#L353)):*
> ```Go
> 	// Drain all SQL connections.
> 	// The queryWait duration is a timeout for waiting on clients
> 	// to self-disconnect. If the timeout is reached, any remaining connections
> ```

hm, this comment doesn't seem to be too different than the comment above "// Wait for users to close the existing SQL connections." 
___
*[pkg/server/drain.go, line 394 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbjWib80H5elJ0E3cK:-MwbjWib80H5elJ0E3cL:bkrabrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/server/drain.go#L394)):*
> ```Go
> 
> // logActiveConns logs the number of active SQL connections every 3 seconds.
> func (s *drainServer) logActiveConns(ctx context.Context) error {
> ```

nit: i think it should be `logOpenConns`

"active" usually means that the connection has a query actively running.
___
*[pkg/sql/pgwire/server.go, line 490 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbiFahDRyec7B-eW2G:-MwbiFahDRyec7B-eW2H:b-9cor7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L490)):*
> ```Go
> // LogActiveConns logs the number of active connections.
> func (s *Server) LogActiveConns(ctx context.Context) {
> 	log.Ops.Info(ctx, fmt.Sprintf("number of active connections: %d\n", s.GetConnCancelMapLen()))
> ```

nit: this doesn't seem that necessary as a separate function. it's only called in one place, and that place can just call `logs.Ops.Info` directly.
___
*[pkg/sql/pgwire/server.go, line 511 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbfBEt-G7yMgCFQfe5:-MwbfBEt-G7yMgCFQfe6:b25gjfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L511)):*
> ```Go
> 	defer timer.Stop()
> 
> 	quitWaitingForConns := make(chan struct{})
> ```

nit: should this channel have a size of 1?
___
*[pkg/sql/pgwire/server.go, line 514 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbjuB7A-aIvlO-8lGN:-MwbjuB7A-aIvlO-8lGO:b7xzdw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L514)):*
> ```Go
> 	defer close(quitWaitingForConns)
> 
> 	_, allConnDone := s.waitConnsDone(quitWaitingForConns)
> ```

i may not have a correct understanding, but does this really do what we want?

i thought it would just signal when the queries were done running (which is why we use it for the query_wait) stage. but what we need is a signal for when the client closes the connection entirely.
___
*[pkg/sql/pgwire/server.go, line 551 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbepMh6Fifus7dNpT4:-MwbepMj2uBKxRlDMYGa:b25gjfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L551)):*
> ```Go
> 	}()
> 
> 	allConnsDone := make(chan struct{})
> ```

nit: should this channel have a size of 1?
___
*[pkg/sql/pgwire/server.go, line 596 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbgmF674sPs5RTCRro:-MwbgmF674sPs5RTCRrp:b25gjfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L596)):*
> ```Go
> 	// goroutine to stop work through quitWaitingForConns.
> 
> 	quitWaitingForConns := make(chan struct{})
> ```

nit: should this channel have a size of 1?


<!-- Sent from Reviewable.io -->

2022-02-23 21:34 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @rafiss)

___
*[pkg/cmd/roachtest/tests/draining.go, line 75 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwbb7IG7CU4NA208aew:-MwcCTa580zTCIFdni57:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/cmd/roachtest/tests/draining.go#L75)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: make all of these Duration types, instead of ints. then you can also simplify the names
```
		drainWaitDuration      = 10 * time.Second
		connectionWaitDuration = 60 * time.Second
		queryWaitDuration      = 10 * time.Second
		pokeDuringConnWaitTimestamp = 25 * time.Second
```
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 86 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbbRNk5TQgA6WBSxab:-Mwc-HokCgSatwHNGBbc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/cmd/roachtest/tests/draining.go#L86)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should there also be a const for `const connMaxLifetime = 30 * time.Second`, defined in the same place as the others?

this way it's easier to see why we've chosen all these times
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 176 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbboCVB8EynaFzuJTQ:-Mwc-JP91MecjsJjAC-f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/cmd/roachtest/tests/draining.go#L176)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: again, use ` * time.Second` here, and remove `Sec` from the names
</blockquote></details>

Done.
___
*[pkg/server/drain.go, line 353 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwbj65o4InreIzHAa3i:-Mwc-aVi3OAMCck_KaT6:bzagrm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/server/drain.go#L353)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, this comment doesn't seem to be too different than the comment above "// Wait for users to close the existing SQL connections." 
</blockquote></details>

Changed it to `waiting for SQL queries to finish`.



_Code quote:_
```Go
Drain all SQL connections.
```
___
*[pkg/server/drain.go, line 394 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbjWib80H5elJ0E3cK:-Mwc-x836-uTWm7tc3Hz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/server/drain.go#L394)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think it should be `logOpenConns`

"active" usually means that the connection has a query actively running.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 490 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbiFahDRyec7B-eW2G:-Mwc0Iho-vgGtkNppvHU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L490)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this doesn't seem that necessary as a separate function. it's only called in one place, and that place can just call `logs.Ops.Info` directly.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 511 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbfBEt-G7yMgCFQfe5:-Mwc0chaB1pYIsccsN-C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L511)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should this channel have a size of 1?
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 514 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbjuB7A-aIvlO-8lGN:-MwcB1hz8yurlZ7_VEbr:bwhu42i) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L514)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i may not have a correct understanding, but does this really do what we want?

i thought it would just signal when the queries were done running (which is why we use it for the query_wait) stage. but what we need is a signal for when the client closes the connection entirely.

</blockquote></details>

The current implementation is doing what we want. It's when `s.mu.draining` is set true that the server will be signaled the query on a connection is done, see in `pkg/sql/pgwire/conn.go`, 

```
	if draining() {
		// TODO(andrei): I think sending this extra error to the client if we also
		// sent another error for the last query (like a context canceled) is a bad
		// idea; see #22630. I think we should find a way to return the
		// AdminShutdown error as the only result of the query.
		log.Ops.Info(ctx, "closing existing connection while server is draining")
		_ /* err */ = writeErr(ctx, &sqlServer.GetExecutorConfig().Settings.SV,
			newAdminShutdownErr(ErrDrainingExistingConn), &c.msgBuilder, &c.writerState.buf)
		_ /* n */, _ /* err */ = c.writerState.buf.WriteTo(c.conn)
	}
```
And we set `s.mu.draining = true` only after we enter the `query_wait` phase.

This has also been validated by the roachtest `drain/early-exit-conn-wait`, which shows that the server exit the conn_wait phase only after all connections are closed. 
___
*[pkg/sql/pgwire/server.go, line 551 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbepMh6Fifus7dNpT4:-MwcCRby7X8bYX8ZOg92:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L551)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should this channel have a size of 1?
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 596 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbgmF674sPs5RTCRro:-MwcCSPf4sQrvva4qBMw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L596)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should this channel have a size of 1?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-24 03:38 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, and @ZhouXing19)

___
*[pkg/cmd/roachtest/tests/draining.go, line 89 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDRVq6EIrJnO-cqH9K:-MwdbsoT5CpI9P05C-Ta:bm1bqot) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L89)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Done. But just curious why we don't use `t.Fatal` or `t.Fatalf`, since they seem common in other roachtests. 
</blockquote></details>

I think @cameronnunez meant instead of using `if err != nil ...` just use `require.NoError(t, err)..` 

Its a shorthand for the `if err != nil..` pattern in roachtests
___
*[pkg/cmd/roachtest/tests/draining.go, line 171 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDWqzhCh-SljVBhLHJ:-MwdcNUA-Zp1LtXrdwl-:b-m0naya) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L171)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Replace the if with require
___
*[pkg/cmd/roachtest/tests/draining.go, line 188 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDfh083DHuLFN9OWrL:-MwdcT7PCCENUyMAIE4K:b-xzs0qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L188)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

replace if with `Require.NoError`
___
*[pkg/cmd/roachtest/tests/draining.go, line 71 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwdblQl66V83Qhch8Fg:-MwdblQl66V83Qhch8Fh:b-i4acbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/cmd/roachtest/tests/draining.go#L71)):*
> ```Go
> 		queryWaitDuration      = 10 * time.Second
> 		// pokeDuringConnWaitTimestamp is the timestamp after the server
> 		// starts waiting SQL connections to close (with the start of the whole
> ```

nit: waiting for
___
*[pkg/cmd/roachtest/tests/draining.go, line 123 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwdcHI09ZfPvFhVQ6ak:-MwdcHI09ZfPvFhVQ6al:b-ttbfdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/cmd/roachtest/tests/draining.go#L123)):*
> ```Go
> 			"new SQL connections: %v", pokeDuringConnWaitTimestamp, err))
> 	} else {
> 		require.NoError(t, errors.New("new SQL connections should not be allowed when the server "+
> ```

We can just t.Fatal error
`require.NoError` is only used to replace the `if err != nil` pattern
___
*[pkg/cmd/roachtest/tests/draining.go, line 249 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwdceBv74aKdAUzfBmC:-MwdceBv74aKdAUzfBmD:b-wghs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/cmd/roachtest/tests/draining.go#L249)):*
> ```Go
> 	)
> 
> 	if _, err := db.ExecContext(ctx, waitPhasesSettingStmt); err != nil {
> ```

Replace if with `require.NoError`
___
*[pkg/sql/pgwire/server.go, line 223 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwdddB_-D2tYpJcETk4:-MwdddB_-D2tYpJcETk5:b1cu47v) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/sql/pgwire/server.go#L223)):*
> ```Go
> 		// SQL connections, e.g. when the draining process enters the phase whose
> 		// duration is specified by the server.shutdown.connection_wait.
> 		rejectingNewSqlConn bool
> ```

nit: I'd favour renamin this to `rejectNewConnections` for clarity
___
*[pkg/sql/pgwire/server.go, line 493 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwddIFK1gQGuPFCyibc:-MwddIFK1gQGuPFCyibd:b3oebcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/sql/pgwire/server.go#L493)):*
> ```Go
> // soon as all existing SQL connections are closed, the server early exits this
> // draining phase.
> func (s *Server) WaitSQLConnsToClose(ctx context.Context, connectionWait time.Duration) {
> ```

nit: rename to`WaitForSQLConnsToClose`
___
*[pkg/sql/pgwire/server.go, line 509 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwdiJlG0sr3MKGfoDEs:-MwdiJlG0sr3MKGfoDEt:b-denpni) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/sql/pgwire/server.go#L509)):*
> ```Go
> 	defer close(quitWaitingForConns)
> 
> 	_, allConnDone := s.waitConnsDone(quitWaitingForConns)
> ```

nit: allConnsDone
___
*[pkg/sql/pgwire/server.go, line 536 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwdmvsp8dWaQ2OQhBT8:-Mwdmvsp8dWaQ2OQhBT9:b-4tkn5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/sql/pgwire/server.go#L536)):*
> ```Go
> func (s *Server) waitConnsDone(quitWaitingForConns chan struct{}) (cancelChanMap, chan struct{}) {
> 
> 	connCancelMap := func() cancelChanMap {
> ```

I'm trying to understand this a little better 

`waitConnsDone` is called in two places
1. ` WaitSQLConnsToClose` after we're already rejecting connections, so in that case we don't actually have to make a copy of the map since we're guaranteed new connections will not be made 
2. `drainImpl` where new connections can still be made.

If I'm correct here, would it make sense to break this helper into two where one returns a copy of the map and the second takes a map and creates the wait channel.
___
*[pkg/sql/pgwire/server.go, line 1304 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwdil-EEva38kg1EL58:-Mwdil-EEva38kg1EL59:b1lnjrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/sql/pgwire/server.go#L1304)):*
> ```Go
> 	s.mu.Unlock()
> 
> 	// If the server is rejecting new SQL connection, we will use the connection
> ```

nit: rejecting new SQL connections


<!-- Sent from Reviewable.io -->

2022-02-24 16:26 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/draining.go, line 89 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDRVq6EIrJnO-cqH9K:-MwgPzr6-sd0m0kGpHXi:b-exqrqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L89)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think @cameronnunez meant instead of using `if err != nil ...` just use `require.NoError(t, err)..` 

Its a shorthand for the `if err != nil..` pattern in roachtests
</blockquote></details>

Ah thanks! Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 171 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDWqzhCh-SljVBhLHJ:-MwgQHAW-3x_UOg1mmiH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L171)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Replace the if with require
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 188 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDfh083DHuLFN9OWrL:-MwgQK8N-FzsJgQNMJeG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L188)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

replace if with `Require.NoError`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 71 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwdblQl66V83Qhch8Fg:-MwgPygK3au7e1Fq1-j-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/cmd/roachtest/tests/draining.go#L71)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: waiting for
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 123 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwdcHI09ZfPvFhVQ6ak:-MwgQ4HA6znWTdQ-2rsZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/cmd/roachtest/tests/draining.go#L123)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

We can just t.Fatal error
`require.NoError` is only used to replace the `if err != nil` pattern
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 249 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwdceBv74aKdAUzfBmC:-MwgQSyK0bOF_pG9eHvR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/cmd/roachtest/tests/draining.go#L249)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Replace if with `require.NoError`
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 223 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwdddB_-D2tYpJcETk4:-MwgUDvtBtMQmsc_DRDP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb39f91e96538115d1cb05aef475134d5a4da5dd/pkg/sql/pgwire/server.go#L223)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: I'd favour renamin this to `rejectNewConnections` for clarity
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 493 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwddIFK1gQGuPFCyibc:-MwgRELmB7dLjXMxdX8A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/sql/pgwire/server.go#L493)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: rename to`WaitForSQLConnsToClose`
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 509 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwdiJlG0sr3MKGfoDEs:-MwgRO7M1Wq-d-CLgQMC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/sql/pgwire/server.go#L509)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: allConnsDone
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 536 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwdmvsp8dWaQ2OQhBT8:-MwgRPRl2H_xmUpum6OL:bvidnww) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/sql/pgwire/server.go#L536)):*
> drainImpl where new connections can still be made.

No, `drainImpl` is always called after `WaitSQLConnsToClose` (i.e. `query_wait` is after `connection_wait`), and in `drainImpl` we don't allow new SQL connections as well.

We still want to keep a copy of the map following the original reason (but with `s.mu.rejectNewConnections = false` now):
> 	// 2) If new connections are added to the original map, it follows that they
	// were added when s.mu.draining = false, thus not requiring cancellation.
	// These connections are not our responsibility and will be handled when the
	// server starts draining again.
___
*[pkg/sql/pgwire/server.go, line 1304 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwdil-EEva38kg1EL58:-MwgUCe95F1Wfc3Yv93l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/sql/pgwire/server.go#L1304)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: rejecting new SQL connections
</blockquote></details>

Done.



_Code quote:_
```Go
rejecting new SQL connection
```


<!-- Sent from Reviewable.io -->

2022-02-24 20:13 UTC, RichardJCai requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, and @ZhouXing19)

___
*[pkg/sql/pgwire/server.go, line 536 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwdmvsp8dWaQ2OQhBT8:-MwhLmZs9V2PJW_EASb-:b-z2zk47) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/sql/pgwire/server.go#L536)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

> drainImpl where new connections can still be made.
No, `drainImpl` is always called after `WaitSQLConnsToClose` (i.e. `query_wait` is after `connection_wait`), and in `drainImpl` we don't allow new SQL connections as well.

We still want to keep a copy of the map following the original reason (but with `s.mu.rejectNewConnections = false` now):
> 	// 2) If new connections are added to the original map, it follows that they
	// were added when s.mu.draining = false, thus not requiring cancellation.
	// These connections are not our responsibility and will be handled when the
	// server starts draining again.
</blockquote></details>

I see

I'm slightly confused about one thing, how can new connections be added to the original map now?
Doesn't `s.mu.rejectNewConnections = true` have to be the case now if we're in the state?

And thus we won't be adding anything to the original map
```
	rejectNewConnections = s.mu.rejectNewConnections
	if !rejectNewConnections {
		var cancel context.CancelFunc
		newCtx, cancel = contextutil.WithCancel(ctx)
		done := make(chan struct{})
		s.mu.connCancelMap[done] = cancel
		onCloseFn = func() {
			cancel()
			close(done)
			s.mu.Lock()
			delete(s.mu.connCancelMap, done)
			s.mu.Unlock()
		}
	}
	s.mu.Unlock()
```


<!-- Sent from Reviewable.io -->

2022-02-24 21:03 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, and @RichardJCai)

___
*[pkg/sql/pgwire/server.go, line 536 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwdmvsp8dWaQ2OQhBT8:-MwhXFXQ8MLNg6728Mob:b367je9) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fdd168794b215be3b9928d6f254188b5edd96f/pkg/sql/pgwire/server.go#L536)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I see

I'm slightly confused about one thing, how can new connections be added to the original map now?
Doesn't `s.mu.rejectNewConnections = true` have to be the case now if we're in the state?

And thus we won't be adding anything to the original map
```
	rejectNewConnections = s.mu.rejectNewConnections
	if !rejectNewConnections {
		var cancel context.CancelFunc
		newCtx, cancel = contextutil.WithCancel(ctx)
		done := make(chan struct{})
		s.mu.connCancelMap[done] = cancel
		onCloseFn = func() {
			cancel()
			close(done)
			s.mu.Lock()
			delete(s.mu.connCancelMap, done)
			s.mu.Unlock()
		}
	}
	s.mu.Unlock()
```

</blockquote></details>

Just revised `s.Undrain()` so that the `s.mu.rejectNewConnections` can be set `false`. So if `Undrain()`is called, new SQL connections will be allowed to be added to the original map, but they should not be drained. 


<!-- Sent from Reviewable.io -->

2022-02-24 23:33 UTC, cameronnunez reviewed
> Reviewed 1 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/cmd/roachtest/tests/draining.go, line 48 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDQuR4CJYeJc75u_G-:-Mwi-G2F5P_1laFcwTt0:bczu3y8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L48)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

renamed it to `runEarlyExitInConnectionWait`. 
</blockquote></details>

Simplify the two roachtests into a single roachtest by putting the code of each in different scopes e.g.

```go
func runConnectionWait(...) {

    // Verify that draining proceeds immediately after connections are closed client-side.
    {
    .
    .
    .
    }

    // Verify a warning exists in the case that connectionWait expires.
    {
    .
    .
    .
    }
}

```
___
*[pkg/cmd/roachtest/tests/draining.go, line 113 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDUz0T0zWCx6IFbx_g:-MwhpqQMCexy-Tfz6KsT:b-mkpezi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L113)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: `c.NewMonitor(ctx, c.Node(nodeToDrain))`
___
*[pkg/cmd/roachtest/tests/draining.go, line 178 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDXDPD1P0pYI8CWdvo:-MwhwX3FDkOxM-7s-ApM:bwrh66s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L178)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Adjust the comment a bit since the server does not drain any connections in this test.
___
*[pkg/cmd/roachtest/tests/draining.go, line 41 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwhzuat81BzqK8dytqA:-Mwhzuat81BzqK8dytqB:boumcuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/cmd/roachtest/tests/draining.go#L41)):*
> ```Go
> 			Cluster: r.MakeClusterSpec(numNodes),
> 			Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
> 				runEarlyExitInConnectionWait(ctx, t, c, numNodes, duration)
> ```

remove `numNodes` as an argument for the run function since variability of the number of nodes does not affect the test



_Code quote:_
```Go
func runTestWarningForConnWait(
```
___
*[pkg/cmd/roachtest/tests/draining.go, line 84 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwhsvrp8UaQmfTJlp9C:-Mwhsvrp8UaQmfTJlp9D:b-iv6u5) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/cmd/roachtest/tests/draining.go#L84)):*
> ```Go
> 
> 	// We will drain the node 1.
> 	nodeToDrain := 1
> ```

nit: initialize this var with the other `const` vars
___
*[pkg/cmd/roachtest/tests/draining.go, line 224 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwhjcK80kcZ6As_Wl94:-MwhjcK80kcZ6As_Wl95:b3ws94p) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/cmd/roachtest/tests/draining.go#L224)):*
> ```Go
> ) {
> 
> 	c.Put(ctx, t.Cockroach(), "./cockroach", c.All())
> ```

nit: `Put` is deprecated; use `PutE` instead paired with `require.NoError`
___
*[pkg/cmd/roachtest/tests/draining.go, line 227 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwhkAvk3Lx39d6cloVW:-MwhkAvk3Lx39d6cloVX:b-licauo) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/cmd/roachtest/tests/draining.go#L227)):*
> ```Go
> 
> 	// Start the cockroach server.
> 	for i := 1; i <= nodes; i++ {
> ```

Instead of this loop, do `c.Start(ctx, t.L(), option.DefaultStartOpts(), install.MakeClusterSettings(), c.All())`
___
*[pkg/cmd/roachtest/tests/draining.go, line 236 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwhlydy3bir2joxAw94:-Mwhlydy3bir2joxAw95:bigfjed) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/cmd/roachtest/tests/draining.go#L236)):*
> ```Go
> 	defer db.Close()
> 
> 	waitPhasesSettingStmt := fmt.Sprintf(
> ```

nit: can use raw string literals here:
```go 
_, err := db.ExecContext(ctx, `
SET CLUSTER SETTING server.shutdown.drain_wait = $1;
SET CLUSTER SETTING server.shutdown.connection_wait = $2;
SET CLUSTER SETTING server.shutdown.query_wait = $3;`, 
    drainWait.Seconds(),
    connectionWait.Seconds(),
    queryWait.Seconds(),
)
require.NoError(t, err)
```
___
*[pkg/server/drain.go, line 353 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwbj65o4InreIzHAa3i:-MwhxAPQ453u47j7sTfH:bd7wqzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/server/drain.go#L353)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Changed it to `waiting for SQL queries to finish`.
</blockquote></details>

nit: maybe update the comment to say "Drain any remaining SQL connections" since ideally it is preferable that the client closes the connections and not the server.
___
*[pkg/server/drain.go, line 335 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwhx_s27cxD19V39xYx:-Mwhx_s27cxD19V39xYy:ba8c99) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/server/drain.go#L335)):*
> ```Go
> 	}
> 
> 	// Wait for drainUnreadyWait. This will fail load balancer checks and
> ```

The comment should remain as is; the var `drainUnreadyWait` does not exist.
___
*[pkg/sql/pgwire/server.go, line 614 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzMEB92jp1yhay29JP:-MwhyZ4R1n37EvaS653R:b-zdbx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/sql/pgwire/server.go#L614)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Shrinked the message per @cameronnunez 's suggestion.
</blockquote></details>

The log message should be specific to draining SQL connections since that's the goal of `drainImpl`. If we want to also signal the beginning of draining the SQL layer, that message needs to go somewhere where it is guaranteed to be run; here, the message won't be logged if there are no active connections on the server. 
___
*[pkg/sql/pgwire/server.go, line 514 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbjuB7A-aIvlO-8lGN:-MwhdY3E0StwROGNCubE:b-24b3kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L514)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

The current implementation is doing what we want. It's when `s.mu.draining` is set true that the server will be signaled the query on a connection is done, see in `pkg/sql/pgwire/conn.go`, 

```
	if draining() {
		// TODO(andrei): I think sending this extra error to the client if we also
		// sent another error for the last query (like a context canceled) is a bad
		// idea; see #22630. I think we should find a way to return the
		// AdminShutdown error as the only result of the query.
		log.Ops.Info(ctx, "closing existing connection while server is draining")
		_ /* err */ = writeErr(ctx, &sqlServer.GetExecutorConfig().Settings.SV,
			newAdminShutdownErr(ErrDrainingExistingConn), &c.msgBuilder, &c.writerState.buf)
		_ /* n */, _ /* err */ = c.writerState.buf.WriteTo(c.conn)
	}
```
And we set `s.mu.draining = true` only after we enter the `quer [...]

2022-02-25 19:14 UTC, rafiss approved these changes
lgtm from my end. i had a few small nits, and i'll let cameron have the final signoff

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-:-MwmIN0Y7eu7B9iI2EhE:byzmf6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/sql/pgwire/server.go, line 514 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwbjuB7A-aIvlO-8lGN:-MwmGF6N4kHDlZn8d8bj:b-9dkznx) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/sql/pgwire/server.go#L514)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

@rafiss I think it signals when the connection closes, not when the queries finish. You can check out the function`registerConn` in `pgwire/server.go` for a closer look. when a connection closes, the key corresponding to the connection is deleted from the map `connCancelMap`.

If draining SQL connections becomes necessary after waiting for client-side connection closure, there's a wait for queries to finish with `queryWait` (but no reception of any query signals) and subsequently there is server-side cancellation of the remaining connections.
</blockquote></details>

i see, thanks for explaining!
___
*[pkg/sql/pgwire/server.go, line 471 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwmHrZU25W0pEwrit5A:-MwmHrZVAV5YUufVHajp:bslpc71) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/sql/pgwire/server.go#L471)):*
> ```Go
> }
> 
> // setDraining sets the server's rejectNewConnections state.
> ```

nit: update the comment with the correct name
___
*[pkg/sql/pgwire/server.go, line 707 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwmFKHc5M_zlwfNTL0e:-MwmFKHd6Q9nr3Ysr9fr:bt05q0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/sql/pgwire/server.go#L707)):*
> ```Go
> // An error is returned if the initial handshake of the connection fails.
> func (s *Server) ServeConn(ctx context.Context, conn net.Conn, socketType SocketType) error {
> 	ctx, draining, onCloseFn := s.registerConn(ctx)
> ```

nit: maybe `draining` should be renamed to `rejectNewConnections` (since you changed the name of the return value in `registerConn`)


<!-- Sent from Reviewable.io -->

2022-02-27 23:27 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/cmd/roachtest/tests/draining.go, line 48 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDQuR4CJYeJc75u_G-:-Mwi7bbq4B_v6QIZnik5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L48)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Simplify the two roachtests into a single roachtest by putting the code of each in different scopes e.g.

```go
func runConnectionWait(...) {

    // Verify that draining proceeds immediately after connections are closed client-side.
    {
    .
    .
    .
    }

    // Verify a warning exists in the case that connectionWait expires.
    {
    .
    .
    .
    }
}

```
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 113 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDUz0T0zWCx6IFbx_g:-Mwi8HjyBke7AXkWRNXr:b3oh8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L113)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: `c.NewMonitor(ctx, c.Node(nodeToDrain))`
</blockquote></details>


Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 178 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwDXDPD1P0pYI8CWdvo:-Mwi8WJn4z4Qzv9FD-V-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4025ff41d66936fbe4bb09a3f034889bb5eca1ca/pkg/cmd/roachtest/tests/draining.go#L178)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Adjust the comment a bit since the server does not drain any connections in this test.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 41 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwhzuat81BzqK8dytqA:-MwxNtrH94_a5K3Hwa7H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/cmd/roachtest/tests/draining.go#L41)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

remove `numNodes` as an argument for the run function since variability of the number of nodes does not affect the test
</blockquote></details>

Done.



_Code quote:_
```Go
numNodes
```
___
*[pkg/cmd/roachtest/tests/draining.go, line 84 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwhsvrp8UaQmfTJlp9C:-Mwi7_AF3-fQzEBduDaS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/cmd/roachtest/tests/draining.go#L84)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: initialize this var with the other `const` vars
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 224 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwhjcK80kcZ6As_Wl94:-Mwi8ovn-S0nKoYh2bfH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/cmd/roachtest/tests/draining.go#L224)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: `Put` is deprecated; use `PutE` instead paired with `require.NoError`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 227 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwhkAvk3Lx39d6cloVW:-MwxNwon2k3p-LVxDdqw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/cmd/roachtest/tests/draining.go#L227)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Instead of this loop, do `c.Start(ctx, t.L(), option.DefaultStartOpts(), install.MakeClusterSettings(), c.All())`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/draining.go, line 236 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwhlydy3bir2joxAw94:-Mwi9JvV9c9m-9fA-gTR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/cmd/roachtest/tests/draining.go#L236)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: can use raw string literals here:
```go 
_, err := db.ExecContext(ctx, `
SET CLUSTER SETTING server.shutdown.drain_wait = $1;
SET CLUSTER SETTING server.shutdown.connection_wait = $2;
SET CLUSTER SETTING server.shutdown.query_wait = $3;`, 
    drainWait.Seconds(),
    connectionWait.Seconds(),
    queryWait.Seconds(),
)
require.NoError(t, err)
```

</blockquote></details>

Done.
___
*[pkg/server/drain.go, line 353 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwbj65o4InreIzHAa3i:-MwxNzA8DNxWMfJrsToM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/573c6dbb700f093f05f554dbd69c6214750ff299/pkg/server/drain.go#L353)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: maybe update the comment to say "Drain any remaining SQL connections" since ideally it is preferable that the client closes the connections and not the server.
</blockquote></details>

Done.
___
*[pkg/server/drain.go, line 335 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwhx_s27cxD19V39xYx:-Mwx67M2BARhjtWeuD05:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/server/drain.go#L335)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

The comment should remain as is; the var `drainUnreadyWait` does not exist.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 614 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MvzMEB92jp1yhay29JP:-MwxNORH6AbLUaHVQ7DK:bw6u9y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ec8b61d08801cd39f676e5a11396d97bde77ef8/pkg/sql/pgwire/server.go#L614)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

The log message should be specific to draining SQL connections since that's the goal of `drainImpl`. If we want to also signal the beginning of draining the SQL layer, that message needs to go somewhere where it is guaranteed to be run; here, the message won't be logged if there are no active connections on the server. 
</blockquote></details>

Moved the logging to the beginning of `drainImpl`.



_Code quote:_
```Go
starting draining the SQL layer
```
___
*[pkg/sql/pgwire/server.go, line 471 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MwmHrZU25W0pEwrit5A:-Mwx6ZHZ6LZ_txQkwWlV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/sql/pgwire/server.go#L471)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: update the comment with the correct name
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 475 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwhhp-JCHfXTIcUGVRR:-Mwx6a3TD8yBe_1afyaZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/sql/pgwire/server.go#L475)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

This should be `s.mu.rejectNewConnections`. Also, this function is identical to `DisallowNewSQLConn`, so one of them should be removed.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 519 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwh [...]

2022-02-28 17:08 UTC, cameronnunez reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugf7Cs0raBaLceU8C7:-Mx0DTumCAqTJfW4q46X:b-kl77s6) (no related file):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Ah I see, thanks!
Have put `setDrainingLocked(true)` back to `drainImpl`, and updated the log messages as well.
</blockquote></details>

Rename `draining.go` to simply `drain.go`. Also seems like CI linter is complaining.

---
___
*[pkg/cmd/roachtest/tests/draining.go, line 236 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0E7hQ2XVDhIw7CROG:-Mx0E7hQ2XVDhIw7CROH:b-ccy4r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6632ed7a8aec84a87eb38e5ebd71ca4a9e7738c9/pkg/cmd/roachtest/tests/draining.go#L236)):*
> ```Go
> 	defer db.Close()
> 
> 	waitPhasesSettingStmt := fmt.Sprintf(
> ```

nit: still unchanged it seems. I would update it to: 

```go 
_, err := db.ExecContext(ctx, `
SET CLUSTER SETTING server.shutdown.drain_wait = $1;
SET CLUSTER SETTING server.shutdown.connection_wait = $2;
SET CLUSTER SETTING server.shutdown.query_wait = $3;`, 
    drainWait.Seconds(),
    connectionWait.Seconds(),
    queryWait.Seconds(),
)
require.NoError(t, err)
```
___
*[pkg/server/drain.go, line 343 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0Gf3Y3FLsj26wvvde:-Mx0Gf3Y3FLsj26wvvdf:bmi5q3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/server/drain.go#L343)):*
> ```Go
> 		log.Ops.Info(ctx, "waiting for health probes to notice that the node "+
> 			"is not ready for new sql connections...")
> 		s.drainSleepFn(drainWaitDuration)
> ```

nit: can simplify to what was here previously: `s.drainSleepFn(drainWait.Get(&s.sqlServer.execCfg.Settings.SV))` since `drainWaitDuration` is only used one time
___
*[pkg/server/drain.go, line 351 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0HzefBOHyahvv3vBI:-Mx0HzefBOHyahvv3vBJ:bkx48id) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/server/drain.go#L351)):*
> ```Go
> 	// or it reaches the connectionMaxWait timeout, whichever earlier.
> 	connectionMaxWait := connectionWait.Get(&s.sqlServer.execCfg.Settings.SV)
> 	s.sqlServer.pgServer.WaitForSQLConnsToClose(ctx, connectionMaxWait)
> ```

nit: can simplify to `s.sqlServer.pgServer.WaitForSQLConnsToClose(ctx, connectionWait.Get(&s.sqlServer.execCfg.Settings.SV))`
___
*[pkg/sql/pgwire/server.go, line 555 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mwhh1VI1Fr7i0kmPnEv:-Mx0DN1N0DXV7mV9ofHR:bof3603) ([raw file](https://github.com/cockroachdb/cockroach/blob/167e8c703b19082137e5eef07ce286f2c99cca4f/pkg/sql/pgwire/server.go#L555)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

I'm confused about this -- I thought we wanted to have the closure of `quitWaitingForConns` outside of `waitConnsDone` because it's used to signal the goroutine to stop listening to the status of connections.
</blockquote></details>

Ah you're right about this, nevermind! 
___
*[pkg/sql/pgwire/server.go, line 223 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0FSZRBwjp_bNa8hDk:-Mx0FSZRBwjp_bNa8hDl:baqch5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L223)):*
> ```Go
> 		// that is closed when the connection is done.
> 		connCancelMap cancelChanMap
> 		// draining is set true when server starts draining any SQL connections that
> ```

Could generalize and say that "draining is set to true when the server starts draining the SQL layer", since there won't be any connections to drain if the client closed all the connections, which we expect to happen.
___
*[pkg/sql/pgwire/server.go, line 500 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0G-8S1fzp-P2pDK-2:-Mx0G-8S1fzp-P2pDK-3:b-psl9lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L500)):*
> ```Go
> 	}
> 
> 	log.Ops.Info(ctx, "waiting for clients to close existing SQL connections...")
> ```

Near the top of the function, check the value of `connectionWait`. If it is zero, we'll want to early exit this function entirely because we don't want any warnings logged in that case. 
___
*[pkg/sql/pgwire/server.go, line 507 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0HfGuEbbl9zTxanc1:-Mx0HfGuEbbl9zTxanc2:b-5jirgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L507)):*
> ```Go
> 	defer timer.Stop()
> 
> 	_, allConnsDone, quitWaitingForConns := s.waitConnsDone()
> ```

nit: do `defer close(quitWaitingForConns)` here
___
*[pkg/sql/pgwire/server.go, line 522 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0ER_IA6iJngWIC8Z_:-Mx0ER_J0n-8lkswHi_7:bc47684) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L522)):*
> ```Go
> 	close(quitWaitingForConns)
> 
> 	return
> ```

nit: do `return nil` instead of just `return` throughout this function
___
*[pkg/sql/pgwire/server.go, line 583 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0FD8q9s5RNcRpb7zC:-Mx0FD8q9s5RNcRpb7zD:bp48hnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L583)):*
> ```Go
> 	}
> 
> 	log.Ops.Info(ctx, "starting draining SQL connections...")
> ```

This needs to come after the check that `len(connCancelMap)` is non-zero.
___
*[pkg/sql/pgwire/server.go, line 599 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0HrPaCSa8BhxB9EGG:-Mx0HrPaCSa8BhxB9EGH:b-5jirgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L599)):*
> ```Go
> 	// These connections are not our responsibility and will be handled when the
> 	// server starts draining again.
> 	connCancelMap, allConnsDone, quitWaitingForConns := s.waitConnsDone()
> ```

nit: do `defer close(quitWaitingForConns)` here


<!-- Sent from Reviewable.io -->

2022-02-28 17:30 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/server/drain.go, line 343 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0Gf3Y3FLsj26wvvde:-Mx0KU5o8dnHUtpgf1gT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/server/drain.go#L343)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: can simplify to what was here previously: `s.drainSleepFn(drainWait.Get(&s.sqlServer.execCfg.Settings.SV))` since `drainWaitDuration` is only used one time
</blockquote></details>

Done.
___
*[pkg/server/drain.go, line 351 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0HzefBOHyahvv3vBI:-Mx0KZH8B5RPWe38Ae_c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/server/drain.go#L351)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: can simplify to `s.sqlServer.pgServer.WaitForSQLConnsToClose(ctx, connectionWait.Get(&s.sqlServer.execCfg.Settings.SV))`
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 223 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0FSZRBwjp_bNa8hDk:-Mx0KmOxDmwBgRMedHin:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L223)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Could generalize and say that "draining is set to true when the server starts draining the SQL layer", since there won't be any connections to drain if the client closed all the connections, which we expect to happen.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 500 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0G-8S1fzp-P2pDK-2:-Mx0L-XFENk5t-CXkKFb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L500)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Near the top of the function, check the value of `connectionWait`. If it is zero, we'll want to early exit this function entirely because we don't want any warnings logged in that case. 
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 507 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0HfGuEbbl9zTxanc1:-Mx0L8s2AUdbYgPmZqDX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L507)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: do `defer close(quitWaitingForConns)` here
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 522 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0ER_IA6iJngWIC8Z_:-Mx0Lxl8EtEV9MQaARmw:b-rk657m) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L522)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: do `return nil` instead of just `return` throughout this function
</blockquote></details>

Why? This function is not supposed to return anything (in fact the IDE complains about `return nil`). 
___
*[pkg/sql/pgwire/server.go, line 583 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0FD8q9s5RNcRpb7zC:-Mx0Mqpv6cBv7I-2a-J_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L583)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

This needs to come after the check that `len(connCancelMap)` is non-zero.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 599 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0HrPaCSa8BhxB9EGG:-Mx0LTVf274-jhCfUOiX:byw4xk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L599)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: do `defer close(quitWaitingForConns)` here
</blockquote></details>

I think we should explicitly close `quitWaitingForConns` right after waiting for `queryWait`, instead of deferring the closure to the end of this function, since there's also `cancelWait` after `queryWait` here.
___
*[pkg/cmd/roachtest/tests/draining.go, line 236 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0E7hQ2XVDhIw7CROG:-Mx0KKeq7CWYUizki0Od:b-6efrcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6632ed7a8aec84a87eb38e5ebd71ca4a9e7738c9/pkg/cmd/roachtest/tests/draining.go#L236)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: still unchanged it seems. I would update it to: 

```go 
_, err := db.ExecContext(ctx, `
SET CLUSTER SETTING server.shutdown.drain_wait = $1;
SET CLUSTER SETTING server.shutdown.connection_wait = $2;
SET CLUSTER SETTING server.shutdown.query_wait = $3;`, 
    drainWait.Seconds(),
    connectionWait.Seconds(),
    queryWait.Seconds(),
)
require.NoError(t, err)
```
</blockquote></details>

Ah yeah I missed that. Thanks!


<!-- Sent from Reviewable.io -->

2022-02-28 17:56 UTC, cameronnunez reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/sql/pgwire/server.go, line 522 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0ER_IA6iJngWIC8Z_:-Mx0SO_IA3RP6idzloL2:b-wi2y80) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L522)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Why? This function is not supposed to return anything (in fact the IDE complains about `return nil`). 
</blockquote></details>

You'll need to specify a return value of `error` in the function header. I think in general we try to avoid naked returns. 
___
*[pkg/sql/pgwire/server.go, line 599 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0HrPaCSa8BhxB9EGG:-Mx0TB348C1qCBgcq9m_:b-t8x6pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L599)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

I think we should explicitly close `quitWaitingForConns` right after waiting for `queryWait`, instead of deferring the closure to the end of this function, since there's also `cancelWait` after `queryWait` here.
</blockquote></details>

The pre-existing code deferred the closure and it did not and still does not interfere with `cancelWait`.
___
*[pkg/sql/pgwire/server.go, line 609 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0SeoX7UyW8hJ03_3G:-Mx0SeoX7UyW8hJ03_3H:boxvyjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a590623f94c3bd3b5abcdbb2028377d98becbd/pkg/sql/pgwire/server.go#L609)):*
> ```Go
> 	connCancelMap, allConnsDone, quitWaitingForConns := s.waitConnsDone()
> 
> 	if len(connCancelMap) == 0 {
> ```

This check has already been done so needs to be removed.


<!-- Sent from Reviewable.io -->

2022-02-28 18:02 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/sql/pgwire/server.go, line 522 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0ER_IA6iJngWIC8Z_:-Mx0UNMr7J_yLV-XOJtP:b-qyfetj) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L522)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

You'll need to specify a return value of `error` in the function header. I think in general we try to avoid naked returns. 
</blockquote></details>

I see, thanks! Done.
___
*[pkg/sql/pgwire/server.go, line 599 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0HrPaCSa8BhxB9EGG:-Mx0UiSICj4xXOHXLyBG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64511fbe1c2e6f3683f3f4f04075018e76f4794a/pkg/sql/pgwire/server.go#L599)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

The pre-existing code deferred the closure and it did not and still does not interfere with `cancelWait`.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 609 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx0SeoX7UyW8hJ03_3G:-Mx0Ui14AmvgEAU7Im1u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a590623f94c3bd3b5abcdbb2028377d98becbd/pkg/sql/pgwire/server.go#L609)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

This check has already been done so needs to be removed.
</blockquote></details>

Done.



_Code quote:_
```Go
if len(connCancelMap) == 0 {
```


<!-- Sent from Reviewable.io -->

2022-02-28 21:12 UTC, cameronnunez commented
Looks like an update need to be made to `TestPGWireDrainClient`

2022-03-01 03:02 UTC, ZhouXing19 reviewed
@cameronnunez It seems that `TestPGWireDrainClient` failed because `s.setRejectNewConnections(true)` was skipped when `connectionWait == 0`, which is wrong. Moved `s.setRejectNewConnections(true)` before checking if conn_wait is set 0, and now `TestPGWireDrainClient` passes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-:-Mx2PxWt6bl9JtbEbL2O:b-9muex7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)



<!-- Sent from Reviewable.io -->

2022-03-01 15:36 UTC, cameronnunez commented
Needs a `generate bazel` and the commit message needs a release justification.

2022-03-01 16:53 UTC, cameronnunez commented
Make sure the core information is in the release note, not the justification. You can keep the justification short. In terms of what a release justification looks like, [click here for the different categories](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/168656965/Guidelines+for+Release+Stability+Period ).

2022-03-01 16:54 UTC, cameronnunez commented
Also, combine the commits into a single commit.

2022-03-01 17:56 UTC, cameronnunez commented
Looks like the CI is complaining about lint errors, will be fixed by a run of `crlfmt` on the changed files. Keep an eye on the GH CI if it complains any further after you fix that.

2022-03-01 20:46 UTC, cameronnunez reviewed
Looking good! Just a few last things.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-:-Mx69NZKBWHqOXvdfCL2:b3ia63g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/server/drain.go, line 61 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx6AGC3-K-Zt0R5ft_q:-Mx6AGC3-K-Zt0R5ft_r:b8kacnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/server/drain.go#L61)):*
> ```Go
> 		"the maximum amount of time a server waits for all SQL connections to "+
> 			"be closed before proceeding with a drain. "+
> 			"When all SQL connections are closed before times out, the server early "+
> ```

Exactly what the server early exits might be ambiguous (e.g. early exiting the entire drain process?). Instead I think you can leave out the second sentence. "maximum" implies a timeout and that it will not always elapse
___
*[pkg/server/drain.go, line 346 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx69aZp2ZFoOqN6XXFp:-Mx69aZp2ZFoOqN6XXFq:b6m5b92) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/server/drain.go#L346)):*
> ```Go
> 	// Wait for users to close the existing SQL connections.
> 	// During this phase, the server is rejecting new SQL connections.
> 	// The server exit this phase either once all SQL connections are closed,
> ```

nit: "The server exits this phase" 
nit: "or the connectionMaxWait timeout elapses,"
___
*[pkg/sql/pgwire/server.go, line 224 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx6B45C-xkIXaFP-Pgg:-Mx6B45C-xkIXaFP-Pgh:b-j4v2kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/sql/pgwire/server.go#L224)):*
> ```Go
> 		connCancelMap cancelChanMap
> 		// draining is set to true when the server starts draining the SQL layer.
> 		// Remaining SQL connections will be closed as
> ```

nit: "When set to true, remaining SQL connections will be closed." for the second line in place of the rest of the comments. I actually don't see anything to indicate that connections are closed as soon as queries finish, but rather there's a wait of duration `query_wait` allowing queries to finish, after which all connections are closed. 



_Code quote:_
```Go
Remaining SQL connections will be closed
```
___
*[pkg/sql/pgwire/server.go, line 517 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx6COj_2P4U3NAlVGPS:-Mx6COj_2P4U3NAlVGPT:bcfouym) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/sql/pgwire/server.go#L517)):*
> ```Go
> 	// Connection wait times out.
> 	case <-time.After(connectionWait):
> 		log.Ops.Infof(ctx,
> ```

I'd suggest a warning log message here instead of an info message. it seems to fall under the umbrella of "possibly requiring more attention" than a typical informational message. 
___
*[pkg/sql/pgwire/server.go, line 545 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx6CwNB1mfeJVDvmcF7:-Mx6CwNB1mfeJVDvmcF8:b52jvfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/sql/pgwire/server.go#L545)):*
nit: I'd say you had the right thinking originally to have `quitWaitingForConns` outside of `waitConnsDone`. Having to call `defer close(quitWaitingForConns)` after each call of `waitConnsDone` is a bit messy. 

> I'm confused about this -- I thought we wanted to have the closure of quitWaitingForConns outside of waitConnsDone because it's used to signal the goroutine to stop listening to the status of connections.

> Ah you're right about this, nevermind!


<!-- Sent from Reviewable.io -->

2022-03-01 21:11 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @knz, @rafiss, @RichardJCai, and @ZhouXing19)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugf7Cs0raBaLceU8C7:-Mx2Q_TZ8ugZTfzexXnS:b-896fix) (no related file):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Rename `draining.go` to simply `drain.go`. Also seems like CI linter is complaining.
</blockquote></details>

Done.

---
___
*[pkg/server/drain.go, line 61 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx6AGC3-K-Zt0R5ft_q:-Mx6F-ij55uqEa6v0I-h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/server/drain.go#L61)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Exactly what the server early exits might be ambiguous (e.g. early exiting the entire drain process?). Instead I think you can leave out the second sentence. "maximum" implies a timeout and that it will not always elapse
</blockquote></details>

Done.



_Code quote:_
```Go
the maximum amount of time a server waits for all SQL connections
```
___
*[pkg/server/drain.go, line 346 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx69aZp2ZFoOqN6XXFp:-Mx6F8QR-MVKY1OZcurt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/server/drain.go#L346)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: "The server exits this phase" 
nit: "or the connectionMaxWait timeout elapses,"
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 224 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx6B45C-xkIXaFP-Pgg:-Mx6HEJd-fdM7c71Yw4H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/sql/pgwire/server.go#L224)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: "When set to true, remaining SQL connections will be closed." for the second line in place of the rest of the comments. I actually don't see anything to indicate that connections are closed as soon as queries finish, but rather there's a wait of duration `query_wait` allowing queries to finish, after which all connections are closed. 
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 517 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx6COj_2P4U3NAlVGPS:-Mx6HNxKC0GBwE-5XTx1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/sql/pgwire/server.go#L517)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

I'd suggest a warning log message here instead of an info message. it seems to fall under the umbrella of "possibly requiring more attention" than a typical informational message. 
</blockquote></details>

Done.



_Code quote:_
```Go
case <-time.After(connectionWait):
```
___
*[pkg/sql/pgwire/server.go, line 545 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx6CwNB1mfeJVDvmcF7:-Mx6Hacy32hz-j996p1n:b-bsdegm) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/sql/pgwire/server.go#L545)):*
> Having to call defer close(quitWaitingForConns) after each call of waitConnsDone
This is unavoidable I think. The change I made per your suggestion was to create `quitWaitingForConns` inside `waitConnsDone`, instead of creating it outside and passing it to `waitConnsDone` as an argument.


<!-- Sent from Reviewable.io -->

2022-03-01 21:14 UTC, ZhouXing19 commented
___
*[pkg/sql/pgwire/server.go, line 545 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx6CwNB1mfeJVDvmcF7:-Mx6KH5GEFj-FcCaTn7a:b24z3y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/sql/pgwire/server.go#L545)):*
> Having to call defer close(quitWaitingForConns) after each call of waitConnsDone

 This is unavoidable I think. The change I made per your suggestion was to create quitWaitingForConns inside waitConnsDone, instead of creating it outside and passing it to waitConnsDone as an argument.


<!-- Sent from Reviewable.io -->

2022-03-02 01:23 UTC, cameronnunez approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-:-Mx7DEd5B5EjeY-jzoUB:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cameronnunez, @knz, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/sql/pgwire/server.go, line 545 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mx6CwNB1mfeJVDvmcF7:-Mx7AYOH635j_9HXrndv:b-pivqoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/accad0a93a68d320d15e577354dc7ac4031d5622/pkg/sql/pgwire/server.go#L545)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

> Having to call defer close(quitWaitingForConns) after each call of waitConnsDone

 This is unavoidable I think. The change I made per your suggestion was to create quitWaitingForConns inside waitConnsDone, instead of creating it outside and passing it to waitConnsDone as an argument.

</blockquote></details>

Really what I was getting at was readability. Having `quitWaitingForConn` initialized outside of `waitConnsDone` might make the `defer close` more intuitive to a reader down the line and mitigates the possibility that the channel does not get closed when this code is touched in the future. But also passing a newly created channel as an argument is not pretty either, so perhaps it is best to leave it in this state.


<!-- Sent from Reviewable.io -->

2022-03-03 22:39 UTC, knz reviewed
Ok I like the gist of this change. 

> Reviewed 1 of 6 files at r4, 1 of 3 files at r5, 1 of 3 files at r7, 2 of 7 files at r10, 3 of 6 files at r11, 1 of 1 files at r21, 1 of 2 files at r23, 2 of 2 files at r24, 2 of 2 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-:-MxGu2DZAbap4uOesttg:bohd1ee)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/server/drain.go, line 35 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGuAdN9BYxMLFGMvr_:-MxGuAdO6N9ynf5FGPVn:bpkbc7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/server/drain.go#L35)):*
> ```Go
> var (
> 	queryWait = settings.RegisterDurationSetting(
> 		settings.TenantReadOnly,
> ```

why did you change this and the next one from writable to readonly? (also same question for the new setting below)
___
*[pkg/server/drain.go, line 338 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGuJ-01OgiCQIiP5VJ:-MxGuJ-01OgiCQIiP5VK:bk01hwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/server/drain.go#L338)):*
> ```Go
> 	if shouldDelayDraining {
> 		log.Ops.Info(ctx, "waiting for health probes to notice that the node "+
> 			"is not ready for new sql connections...")
> ```

no need for an ellipsis in he log message
___
*[pkg/server/drain.go, line 345 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGuRC81Zr4pMk0xYK1:-MxGuRC9D87QFRcFDSCW:bbg52qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/server/drain.go#L345)):*
> ```Go
> 	// During this phase, the server is rejecting new SQL connections.
> 	// The server exits this phase either once all SQL connections are closed,
> 	// or the connectionMaxWait timeout elapses, whichever earlier.
> ```

nit: whichever _happens_ earlier. 
___
*[pkg/sql/pgwire/server.go, line 454 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGt8vu2KmxSYgrSbG0:-MxGt8vu2KmxSYgrSbG1:bodnn24) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L454)):*
> ```Go
> // connections are accepted.
> func (s *Server) Undrain() {
> 	s.setRejectNewConnections(false)
> ```

Why did you choose to pull the locking into the individual operations?

What do you think should be the behavior if there is a call to Undrain issued concurrently with Drain?
___
*[pkg/sql/pgwire/server.go, line 505 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGtIil5BKks_b_ib-s:-MxGtIil5BKks_b_ib-t:bpo9s1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L505)):*
> ```Go
> 	}
> 
> 	log.Ops.Info(ctx, "waiting for clients to close existing SQL connections...")
> ```

no need for an ellipsis at the end of the log message
___
*[pkg/sql/pgwire/server.go, line 513 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGtSZ92yCMWcmqQctO:-MxGtSZ92yCMWcmqQctP:bcdq1pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L513)):*
> ```Go
> 	defer close(quitWaitingForConns)
> 
> 	select {
> ```

can you explain to me which logic ensures this select exits if the server is being shut down prematurely? (e.g. via stopper?)
___
*[pkg/sql/pgwire/server.go, line 531 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGto6n576lyU95eekZ:-MxGto6o8uAjuCxhcdw7:b-f66v20) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L531)):*
> ```Go
> // waiting for connections, whichever earlier.
> func (s *Server) waitConnsDone() (cancelChanMap, chan struct{}, chan struct{}) {
> ```

nit: no empty space at start of function
___
*[pkg/sql/pgwire/server.go, line 579 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGtqKwA7JA_HEr9JIz:-MxGtqKwA7JA_HEr9JJ-:beyw7y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L579)):*
> ```Go
> 	reporter func(int, redact.SafeString),
> ) error {
> ```

ditto empty space
___
*[pkg/sql/pgwire/server.go, line 590 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGts2--2k3FIPZ_AOV:-MxGts2--2k3FIPZ_AOW:bimq9m4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L590)):*
> ```Go
> 	}
> 
> 	log.Ops.Info(ctx, "starting draining SQL connections...")
> ```

ditto ellipsis
___
*[pkg/cmd/roachtest/tests/drain.go, line 63 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGutA267Pw2FCerX5D:-MxGutA267Pw2FCerX5E:bvcz8oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L63)):*
> ```Go
> 			// drainWaitDuration, but smaller than (drainWaitDuration +
> 			// connectionWaitDuration).
> 			pokeDuringConnWaitTimestamp = 45 * time.Second
> ```

IMHO the durations you've chosen here make this roachtest run for way too long. Given that there's just 1 node, there's no complexity needed for a drain so all the phases should be able to run within a few seconds. 

Is there a way to chose the durations so that the total  duration of each phase of the test is lower than, say, 10-20 seconds?
___
*[pkg/cmd/roachtest/tests/drain.go, line 105 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGvJWPAIvgkqYx4wKU:-MxGvJWQ6nN5bGq37zl6:b-2ufqx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L105)):*
> ```Go
> 		// connections. Verify that the server is rejecting new SQL connections now.
> 		time.Sleep(pokeDuringConnWaitTimestamp)
> 		_, err = db.Conn(ctx)
> ```

nit: `if _, err := ...; err != nil { .... } else { ... }`
___
*[pkg/cmd/roachtest/tests/drain.go, line 118 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGvTxU6nA0Ojt-gu4c:-MxGvTxU6nA0Ojt-gu4d:b-i86pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L118)):*
> ```Go
> 		t.Status("number of open connections: ", db.Stats().OpenConnections)
> 
> 		randConn := conns[rand.Intn(len(conns))]
> ```

please report in the test status messages which connection was used (in case we want to reproduce / analyze a failure)
___
*[pkg/cmd/roachtest/tests/drain.go, line 123 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGv_2g5jtn1KsByn71:-MxGv_2g5jtn1KsByn72:b670zux) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L123)):*
> ```Go
> 		// queries do not fail.
> 		_, err = randConn.ExecContext(ctx, "SELECT 1;")
> ```

nit: no empty space needed here
___
*[pkg/cmd/roachtest/tests/drain.go, line 152 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGvi1m2_ZJTBrSDu9-:-MxGvi1m2_ZJTBrSDu90:b2tnjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L152)):*
> ```Go
> 	}
> 
> 	// Verify a warning exists in the case that connectionWait expires.
> ```

Since this block is a test independent from the previous one, please split them into separate test functions (with separate entries in the test registry). This way if one fail we can investigate the failure without having to bother about the other part of the test.
___
*[pkg/cmd/roachtest/tests/drain.go, line 204 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGvrGK81vrByHy8DDn:-MxGvrGK81vrByHy8DDo:bz8ckfe) ([raw file](https://github.com/cockroachdb/cockroach/blob [...]

2022-03-07 18:12 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cameronnunez, @knz, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/server/drain.go, line 35 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGuAdN9BYxMLFGMvr_:-Mx_FwKv8QDwK-oeKuUH:beovdjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/server/drain.go#L35)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

why did you change this and the next one from writable to readonly? (also same question for the new setting below)
</blockquote></details>

Since the setting of draining may affect all users' experience on this node, according to the sementics of tenant read-only and writable [here](https://github.com/cockroachdb/cockroach/pull/73349/files#diff-dfa1f65b3c27c6bd6c462b0b899841fa71e71485717ea959b0ff51877ee3ffc0R68-R88), I don't think these settings are "per tenant and can be modified by the tenant".
___
*[pkg/server/drain.go, line 338 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGuJ-01OgiCQIiP5VJ:-Mx_H64D7SHnbbpvnOUZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/server/drain.go#L338)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

no need for an ellipsis in he log message
</blockquote></details>

Done.
___
*[pkg/server/drain.go, line 345 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGuRC81Zr4pMk0xYK1:-Mx_HAA79LG58veCQ2Lx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/server/drain.go#L345)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: whichever _happens_ earlier. 
</blockquote></details>

Done.



_Code quote:_
```Go
the connectionMaxWait timeout elapses, whichever earlier.
```
___
*[pkg/sql/pgwire/server.go, line 454 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGt8vu2KmxSYgrSbG0:-Mx_M3xo5rDS-BFTvNVY:b-k9g776) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L454)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why did you choose to pull the locking into the individual operations?

What do you think should be the behavior if there is a call to Undrain issued concurrently with Drain?
</blockquote></details>

Ah yes good point, Undrain and Drain are expected run in serial when called concurrently, while the operations in current `Undrain` is not entirely locked, which fails to ensure the serial execution. Made the changes.
___
*[pkg/sql/pgwire/server.go, line 505 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGtIil5BKks_b_ib-s:-Mx_NIlX7HaGTncbtRRs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L505)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

no need for an ellipsis at the end of the log message
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 513 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGtSZ92yCMWcmqQctO:-Mx_Vtz_06udvV2COPAv:b7r3h97) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L513)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

can you explain to me which logic ensures this select exits if the server is being shut down prematurely? (e.g. via stopper?)
</blockquote></details>

Added 
```
	case <-ctx.Done():
		return ctx.Err()
	case <-stopper.ShouldQuiesce():
		return context.Canceled
```
for both `conn_wait` and `query_wait`.
___
*[pkg/sql/pgwire/server.go, line 531 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGto6n576lyU95eekZ:-Mx_W7eXBPXejHCwgVpm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L531)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: no empty space at start of function
</blockquote></details>

Done.



_Code quote:_
```Go
func (s *Server) waitConnsDone() (cancelChanMap, chan struct{}, chan struct{}) {
```
___
*[pkg/sql/pgwire/server.go, line 579 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGtqKwA7JA_HEr9JIz:-Mx_WGUu-fEKbQPlaLs3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L579)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto empty space
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 590 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGts2--2k3FIPZ_AOV:-Mx_WFmd55LbJRdCWdu4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/sql/pgwire/server.go#L590)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto ellipsis
</blockquote></details>

Done.



_Code quote:_
```Go
starting draining SQL connections...
```
___
*[pkg/cmd/roachtest/tests/drain.go, line 63 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGutA267Pw2FCerX5D:-Mx_CYgQ5tlN88yJY86K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L63)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

IMHO the durations you've chosen here make this roachtest run for way too long. Given that there's just 1 node, there's no complexity needed for a drain so all the phases should be able to run within a few seconds. 

Is there a way to chose the durations so that the total  duration of each phase of the test is lower than, say, 10-20 seconds?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/drain.go, line 105 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGvJWPAIvgkqYx4wKU:-Mx_CioRBHUkTch4LlUy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L105)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: `if _, err := ...; err != nil { .... } else { ... }`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/drain.go, line 118 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGvTxU6nA0Ojt-gu4c:-Mx_D88T6-EE35Y9hQ3S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L118)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please report in the test status messages which connection was used (in case we want to reproduce / analyze a failure)
</blockquote></details>

Done.



_Code quote:_
```Go
randConn := conns[rand.Intn(len(conns))]
```
___
*[pkg/cmd/roachtest/tests/drain.go, line 123 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGv_2g5jtn1KsByn71:-Mx_DMYsBEO-pvluOPJq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L123)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: no empty space needed here
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/drain.go, line 152 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGvi1m2_ZJTBrSDu9-:-Mx_DOOG8l-5iKhFvryh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L152)):*
<details><summary><i>Previously, knz (k [...]

2022-03-07 18:13 UTC, ZhouXing19 commented
___
*[pkg/server/drain.go, line 35 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGuAdN9BYxMLFGMvr_:-Mx__JvgChoS8YFEYcsC:borf32v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/server/drain.go#L35)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Since the setting of draining may affect all users' experience on this node, according to the sementics of tenant read-only and writable [here](https://github.com/cockroachdb/cockroach/pull/73349/files#diff-dfa1f65b3c27c6bd6c462b0b899841fa71e71485717ea959b0ff51877ee3ffc0R68-R88), I don't think these settings are "per tenant and can be modified by the tenant".
</blockquote></details>

"all users' experience on this node" => "all tenants' experience on this node"


<!-- Sent from Reviewable.io -->

2022-03-09 11:35 UTC, knz approved these changes
> Reviewed 1 of 4 files at r26, 3 of 3 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-Mugf7Cs0raBaLceU8C7:-MxiSYgI-Nf6shO0Ei09:biq60ad) (no related file):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM modulo double checking the configurabiltiy of the new cluster settings.

---
___
*[pkg/server/drain.go, line 35 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGuAdN9BYxMLFGMvr_:-MxiS4dq78ilL1THi2li:b-9ra01p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/server/drain.go#L35)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

"all users' experience on this node" => "all tenants' experience on this node"
</blockquote></details>

I think I disagree. IMHO This should be settable by the tenant because the tenant's DBA should be able to choose how shutdowns affect connections.
Can you briefly check in with @jeffswenson to see if there's a reason in CC to lock this customization down?
___
*[pkg/cmd/roachtest/tests/drain.go, line 219 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGvtTn-af2txFlTTt8:-MxiRu4t9az6wvdtiuIh:buc6jz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/cmd/roachtest/tests/drain.go#L219)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Done. I also changed it back to `waitPhasesSettingStmt`, because the current lines lead to error: 
```
pq: prepared statement had 3 statements, expected 1
```
</blockquote></details>

you could use 3 different statements... but this is fine too.


<!-- Sent from Reviewable.io -->

2022-03-09 19:46 UTC, JeffSwenson reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cameronnunez, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/server/drain.go, line 35 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGuAdN9BYxMLFGMvr_:-Mxk9UIc7jV2hmK65_2_:b-b9f0hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/server/drain.go#L35)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think I disagree. IMHO This should be settable by the tenant because the tenant's DBA should be able to choose how shutdowns affect connections.
Can you briefly check in with @jeffswenson to see if there's a reason in CC to lock this customization down?
</blockquote></details>

I prefer keeping the settings as TenantReadOnly. The actual benefit of the settings to Serverless is lower because the sql proxy will migrate connections away from a sql server before shutting it down. Users may find the settings confusing because they do not control the sql proxy's draining behavior. When we drain a sql proxy, it impacts multiple tenants and there is no way for the sql proxy to respect per tenant settings.


<!-- Sent from Reviewable.io -->

2022-03-10 15:08 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72991)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cameronnunez, @knz, @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/server/drain.go, line 35 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/72991#-MxGuAdN9BYxMLFGMvr_:-MxoMRQo96eeYibWgPOM:b-k1n6av) ([raw file](https://github.com/cockroachdb/cockroach/blob/8107d9d0def2f2a8a4911aff1f09e07d94c64bf7/pkg/server/drain.go#L35)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

I prefer keeping the settings as TenantReadOnly. The actual benefit of the settings to Serverless is lower because the sql proxy will migrate connections away from a sql server before shutting it down. Users may find the settings confusing because they do not control the sql proxy's draining behavior. When we drain a sql proxy, it impacts multiple tenants and there is no way for the sql proxy to respect per tenant settings.
</blockquote></details>

@jeffswenson Thanks! 
For this PR I'll keep the original TenantWritable setting, and I'll open another PR to change them to `TenantReadOnly` after this PR is merged.


<!-- Sent from Reviewable.io -->

2022-03-10 19:34 UTC, merged