sql: include a memory size interface for descriptors for memory monit…
cockroachdb/cockroach pull request #73344
Opened 2021-12-01 18:54 UTC by jameswsj10

…oring

In order to allow for memory monitoring descriptors and leases (see #67049),
an interface method MemorySize is needed for catalog.Descriptor. This change
allows us to rely on existing protobuf Size() methods.

Release note (sql change): Exposed MemorySize method for a catalog.Descriptor
for memory monitoring purposes.

2021-12-01 18:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/73344)
<!-- Reviewable:end -->

2021-12-01 19:46 UTC, fqazi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-:-MprXF3lCrXXIly_FO83:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2021-12-01 22:09 UTC, ajwerner reviewed
Can you put at least a TODO in the concrete implementations to have it track the size of the descriptor in question. Can you write some tests that fetch some descriptors and validate their size in some way? It'd be bad if we had like a really big default expression and it didn't show up. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-:-Mps1iNt7gAm7nARtznK:b-2md8nc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jameswsj10)

___
*[pkg/sql/catalog/descriptor.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-Mps1_lm1cd9EQuaMTqq:-Mps1_lm1cd9EQuaMTqr:b5jipnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/26576c1c7119f288bbd4f55c887e779f02e132f4/pkg/sql/catalog/descriptor.go#L186)):*
> ```
> 	//MemorySize returns the memory held by the Descriptor.
> 	MemorySize() int
> ```
nit: can we call this `ByteSize`? 


<!-- Sent from Reviewable.io -->

2021-12-02 17:33 UTC, ajwerner commented on pkg/sql/catalog/lease/lease_internal_test.go
> +	actual = rankByDescSize(tableSizes)
For sorting, just use https://pkg.go.dev/sort#Slice

2021-12-02 17:34 UTC, ajwerner commented on pkg/sql/catalog/lease/lease_internal_test.go
> +	actual = rankByDescSize(tableSizes)
```
var descs []catalog.Descriptor
sort.Slice(len(descs), func(i, j int) bool { return descs[i].ByteSize() < descs[j].ByteSize() })
```

2021-12-02 19:14 UTC, jameswsj10 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73344)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1260 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-Mpw7Jpn5QiKl_o8F3AN-r2-1260:-MpwZTuV2dhNSrGU9zzv:bapf8ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0aca12ceef926b29c1342e2c63283eba222022/pkg/sql/catalog/lease/lease_internal_test.go#L1260)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

```
var descs []catalog.Descriptor
sort.Slice(len(descs), func(i, j int) bool { return descs[i].ByteSize() < descs[j].ByteSize() })
```
</blockquote></details>

Replaced the manual function with sort.Slice!


<!-- Sent from Reviewable.io -->

2021-12-02 19:32 UTC, ajwerner commented on pkg/sql/catalog/lease/lease_internal_test.go
> +func TestTableDescriptorByteSizeOrder(t *testing.T) {
refactor all of these tests into just one test so you can mix and match all the types of descriptors. For the names, you can [3]string or something and make the join in the namespace table accordingly or something.

2021-12-08 00:23 UTC, jameswsj10 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73344)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1211 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-Mpw7Jpn5QiKl_o8F3AN-r3-1211:-MqMQ9np-VeMI-zd6Fwt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/075b181f1cb3ad329a0833bdc2c8f38a6309f2fe/pkg/sql/catalog/lease/lease_internal_test.go#L1211)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

refactor all of these tests into just one test so you can mix and match all the types of descriptors. For the names, you can [3]string or something and make the join in the namespace table accordingly or something. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-21 18:45 UTC, ajwerner requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 9 files at r2, 1 of 2 files at r3, 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-:-MqQKfz88OUyKdaJrYWY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @fqazi, and @jameswsj10)

___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1331 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTIc3X4EzW5mHon9a1:-MrTIc3X4EzW5mHon9a2:bbiy8zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1331)):*
> ```Go
> 		},
> 	} {
> 		t.Run(fmt.Sprintf("test: %s", tc.name), func(t *testing.T) {
> ```

no reason for `test: `
___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1341 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTIY-fEzXSKqlOhW6J:-MrTIY-fEzXSKqlOhW6K:bp7ify) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1341)):*
> ```Go
> 				desc, err := manager.Acquire(ctx, s.Clock().Now(), tableID)
> 				require.NoError(t, err)
> 				log.Infof(ctx, "%s", expr)
> ```

nit: remove
___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1346 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTI_Rt90nIep1kC-RN:-MrTI_Rt90nIep1kC-RO:borx5nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1346)):*
> ```Go
> 			}
> 
> 			// Logging
> ```

if you must retain logging, consider `t.Log`



_Code quote:_
```Go
			// Logging
			log.Info(ctx, "All descriptors sizes before comparison")
			for _, desc := range descs {
				log.Infof(ctx, "Descriptor %s with size %d", desc.GetName(), desc.Underlying().ByteSize())
			}
```
___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1356 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTIeZj3RtCfZEPWLD8:-MrTIeZj3RtCfZEPWLD9:bp7ify) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1356)):*
> ```Go
> 				return descs[i].Underlying().ByteSize() < descs[j].Underlying().ByteSize()
> 			})
> 			log.Infof(ctx, "Sorted Descriptors: %v", descs)
> ```

nit: remove
___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1361 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTIfw65E82lWT8U_sh:-MrTIfw65E82lWT8U_si:bmloxe4) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1361)):*
> ```Go
> 				actual[i] = desc.GetName()
> 			}
> 			require.Equalf(t, tc.expOrder, actual, "Expected: %v, Got: %v", tc.expOrder, actual)
> ```

nit: lowercase these letter
___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1378 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTIv0L8CfsXVTtPt10:-MrTIv0L8CfsXVTtPt11:b-kvtfsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1378)):*
> ```Go
> 	manager := s.LeaseManager().(*Manager)
> 
> 	getApproxByteSize := func(descID descpb.ID) int64 {
> ```

you need to plumb the subtest `t *testing.T` here, otherwise you'll be using the outer test one which is a bug
___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1383 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTIj4H6b3CW49cUhCc:-MrTIj4H6b3CW49cUhCd:bodzqfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1383)):*
> ```Go
> 		if rows.Next() {
> 			if err := rows.Scan(&descBytes); err != nil {
> 				log.Eventf(ctx, "Error retrieving bytes from descriptor: %v", err)
> ```

I imagine this should be `t.NoError` or something like that? 


<!-- Sent from Reviewable.io -->

2021-12-21 21:11 UTC, jameswsj10 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73344)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1331 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTIc3X4EzW5mHon9a1:-MrToA0a16sUIh9Pfriy:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1331)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

no reason for `test: `
</blockquote></details>

Removed.
___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1346 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTI_Rt90nIep1kC-RN:-MrToFDU7F4BoAr_Vh8U:b-y5yhyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1346)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

if you must retain logging, consider `t.Log`
</blockquote></details>

Removed logging.
___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1378 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTIv0L8CfsXVTtPt10:-MrToUr0BSyr-Mb3Xlw9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1378)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you need to plumb the subtest `t *testing.T` here, otherwise you'll be using the outer test one which is a bug
</blockquote></details>

Done.
___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1383 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrTIj4H6b3CW49cUhCc:-MrTomMX8BEu0zzo9KLp:b-d5otuu) ([raw file](https://github.com/cockroachdb/cockroach/blob/083f2b616b25873ede59878bfa10d54ea8526ec3/pkg/sql/catalog/lease/lease_internal_test.go#L1383)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I imagine this should be `t.NoError` or something like that? 
</blockquote></details>

modified to t.NoError


<!-- Sent from Reviewable.io -->

2021-12-21 22:34 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-:-MrU7LN92P4YZjhcuEJX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @jameswsj10)

___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1331 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73344#-MrU72pGDKHoX_3f-WjO:-MrU72pGDKHoX_3f-WjP:bg9l9ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/97ac6f0129a66cb4dd2d979dc02976ed54ce6e1d/pkg/sql/catalog/lease/lease_internal_test.go#L1331)):*
> ```Go
> 	} {
> 		t.Run(fmt.Sprint(tc.name), func(t *testing.T) {
> 			// Create tables and retrieve TableDescriptors.
> ```

nit:

```go
			descs := make([]LeasedDescriptor, 0,  len(tc.sqlExprs))
			i := 0
			for size, expr := range tc.sqlExprs {
				tdb.Exec(t, expr)
				var tableID descpb.ID
				tdb.QueryRow(t, "SELECT id FROM system.namespace WHERE name = "+"'"+size+"'").Scan(&tableID)
				desc, err := manager.Acquire(ctx, s.Clock().Now(), tableID)
				require.NoError(t, err)
				descs = append(descs, desc)
			}
```



_Code quote:_
```Go
			// Create tables and retrieve TableDescriptors.
			descs := make([]LeasedDescriptor, len(tc.sqlExprs))
			i := 0
			for size, expr := range tc.sqlExprs {
				tdb.Exec(t, expr)
				var tableID descpb.ID
				tdb.QueryRow(t, "SELECT id FROM system.namespace WHERE name = "+"'"+size+"'").Scan(&tableID)
				desc, err := manager.Acquire(ctx, s.Clock().Now(), tableID)
				require.NoError(t, err)
				descs[i] = desc
				i++
			}
```


<!-- Sent from Reviewable.io -->

2021-12-22 18:52 UTC, jameswsj10 commented
bors r+

2021-12-22 20:36 UTC, merged