changefeedccl: limit in-memory rowfetcher cache
cockroachdb/cockroach pull request #73750
Opened 2021-12-13 18:34 UTC by HonoreDB

We generate a row.Fetcher for each new version of a watched
table, and cache it in-memory. This is technically an unbounded
memory usage and thus could cause an OOM, although in practice
you won't hit that unless you are Schema Changes Georg, the
hypothetical outlier who makes thousands of schema changes a second.
To support Schema Changes Georg, this PR bounds the size of the
cache and evicts the oldest record. There's smarter stuff we could
do (per an existing TODO) to eagerly evict records using resolved
timestamps, but that's an optimization only a small subset of
hypothetical Georgs would care about (those running single
changefeeds on many tables, all with many rapid schema changes)
so I doubt we'll want to bother.

Release note: None

2021-12-13 18:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/73750)
<!-- Reviewable:end -->

2021-12-13 18:45 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73750)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @HonoreDB)

___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-Mqp63D6Ds4YXRT5lMGk:-Mqp63D75Q4dKuDLdBLZ:b8tmhi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/76bb576cdb3e8295f4b0bc234f461ef353e50a39/pkg/ccl/changefeedccl/rowfetcher_cache.go#L42)):*
> ```Go
> 	leaseMgr      *lease.Manager
> 	fetchers      map[idVersion]*row.Fetcher
> 	fetcherBuffer ring.Buffer
> ```

Any reason not to leverage `util/cache.UnorderedCache`?


<!-- Sent from Reviewable.io -->

2021-12-13 18:52 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73750)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @HonoreDB)

___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-Mqp63D6Ds4YXRT5lMGk:-Mqp7uAGBOx5J2aQCi0O:b9ba0xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/76bb576cdb3e8295f4b0bc234f461ef353e50a39/pkg/ccl/changefeedccl/rowfetcher_cache.go#L42)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Any reason not to leverage `util/cache.UnorderedCache`?
</blockquote></details>

Will do, thanks!


<!-- Sent from Reviewable.io -->

2021-12-13 21:19 UTC, HonoreDB commented
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-Mqp63D6Ds4YXRT5lMGk:-MqpeYR12LSObx2DKN98:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/76bb576cdb3e8295f4b0bc234f461ef353e50a39/pkg/ccl/changefeedccl/rowfetcher_cache.go#L42)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Will do, thanks!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-13 21:26 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73750)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @HonoreDB)

___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-MqpdywSCYv-mCPyTEu8:-MqpdywSCYv-mCPyTEu9:bb3cvih) ([raw file](https://github.com/cockroachdb/cockroach/blob/738b4d73541709c395d84b604826042b9663dfb6/pkg/ccl/changefeedccl/rowfetcher_cache.go#L47)):*
> ```Go
> }
> 
> var rfCacheConfig = cache.Config{
> ```

I don't particularly like this global singleton. The cache datastructure is not safe for concurrent access:

https://github.com/cockroachdb/cockroach/blob/441809ed57e66fb0c55b5a3504480950be394352/pkg/util/cache/cache.go#L356

If you want to add a global cache, you could construct the object in the server and plumb it through. My sense is that that'd be a good bit of effort.


Instead, I suggest that we do something like configure the thing per changefeed with a size equal to the number of tables we're watching times some multiple (3-4?) and then change to LRU. 
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-MqpdfMV0yubqnUSIHU-:-MqpdfMV0yubqnUSIHU0:b-r3rbhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/738b4d73541709c395d84b604826042b9663dfb6/pkg/ccl/changefeedccl/rowfetcher_cache.go#L48)):*
> ```Go
> 
> var rfCacheConfig = cache.Config{
> 	Policy:      cache.CacheFIFO,
> ```

LRU seems better, no?


<!-- Sent from Reviewable.io -->

2021-12-13 21:54 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73750)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-MqpdywSCYv-mCPyTEu8:-MqpkO5BEapgcTY0CzdT:bk3xna0) ([raw file](https://github.com/cockroachdb/cockroach/blob/738b4d73541709c395d84b604826042b9663dfb6/pkg/ccl/changefeedccl/rowfetcher_cache.go#L47)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't particularly like this global singleton. The cache datastructure is not safe for concurrent access:

https://github.com/cockroachdb/cockroach/blob/441809ed57e66fb0c55b5a3504480950be394352/pkg/util/cache/cache.go#L356

If you want to add a global cache, you could construct the object in the server and plumb it through. My sense is that that'd be a good bit of effort.


Instead, I suggest that we do something like configure the thing per changefeed with a size equal to the number of tables we're watching times some multiple (3-4?) and then change to LRU. 
</blockquote></details>

Only the config is global, and it's not stateful; I saw this done in other files (e.g. `contention/registry`) so I know it's safe. Easy to change though if it feels like bad hygiene, definitely not planning on making this actually global.
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-MqpdfMV0yubqnUSIHU-:-MqpiklSAzTNJDwy0UDh:b-xri93b) ([raw file](https://github.com/cockroachdb/cockroach/blob/738b4d73541709c395d84b604826042b9663dfb6/pkg/ccl/changefeedccl/rowfetcher_cache.go#L48)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

LRU seems better, no?
</blockquote></details>

Yes from a reducing-misses perspective, but I feel like no overall just because the ratio of hits to misses is so enormous ( ratio of table writes to schema changes) that it's not worth doing any extra work on a hit, even the trivial step of tracking usage.


<!-- Sent from Reviewable.io -->

2021-12-13 22:19 UTC, ajwerner reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73750)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB)

___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-MqpdywSCYv-mCPyTEu8:-MqpraCF-9xTKfobPEln:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/738b4d73541709c395d84b604826042b9663dfb6/pkg/ccl/changefeedccl/rowfetcher_cache.go#L47)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Only the config is global, and it's not stateful; I saw this done in other files (e.g. `contention/registry`) so I know it's safe. Easy to change though if it feels like bad hygiene, definitely not planning on making this actually global.
</blockquote></details>

Ack
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-MqpdfMV0yubqnUSIHU-:-MqprbM8ECL6TK78gCNQ:b-xx61yf) ([raw file](https://github.com/cockroachdb/cockroach/blob/738b4d73541709c395d84b604826042b9663dfb6/pkg/ccl/changefeedccl/rowfetcher_cache.go#L48)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Yes from a reducing-misses perspective, but I feel like no overall just because the ratio of hits to misses is so enormous ( ratio of table writes to schema changes) that it's not worth doing any extra work on a hit, even the trivial step of tracking usage.
</blockquote></details>

Whoops
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-MqprjKy-Hi2h1u5ARKs:-MqprjKy-Hi2h1u5ARKt:bgylwmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f55ceef04f9674d74e4f3fa6dc2fb82c3c9c6a/pkg/ccl/changefeedccl/rowfetcher_cache.go#L178)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 
> 	// TODO(dan): Bound the size of the cache. Resolved notifications will let
> 	// us evict anything for timestamps entirely before the notification. Then
> 	// probably an LRU just in case?
> ```
</details>

Want to leave part of the TODO about evicting below the resolved timestamp or take a stab at it? Namely, when the frontier moves we can evict any descriptor which has another descriptor newer than it with the same ID. 


<!-- Sent from Reviewable.io -->

2021-12-15 16:20 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73750)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB)

___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-MqprjKy-Hi2h1u5ARKs:-MqytJzkEDCZ0M8VUjzF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f55ceef04f9674d74e4f3fa6dc2fb82c3c9c6a/pkg/ccl/changefeedccl/rowfetcher_cache.go#L178)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 	// TODO(dan): Bound the size of the cache. Resolved notifications will let
> 	// us evict anything for timestamps entirely before the notification. Then
> 	// probably an LRU just in case?
> ```
Want to leave part of the TODO about evicting below the resolved timestamp or take a stab at it? Namely, when the frontier moves we can evict any descriptor which has another descriptor newer than it with the same ID. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-15 17:23 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73750)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB)

___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-MqprjKy-Hi2h1u5ARKs:-Mqz6khm9PP75QUkqNz-:b-uli6j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f55ceef04f9674d74e4f3fa6dc2fb82c3c9c6a/pkg/ccl/changefeedccl/rowfetcher_cache.go#L178)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you forget to push?


<!-- Sent from Reviewable.io -->

2021-12-15 18:00 UTC, HonoreDB commented
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73750#-MqprjKy-Hi2h1u5ARKs:-MqzF1f6BCmR87AtyEAN:b9e27kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/64f55ceef04f9674d74e4f3fa6dc2fb82c3c9c6a/pkg/ccl/changefeedccl/rowfetcher_cache.go#L178)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Did you forget to push?
</blockquote></details>

Yup, sorry, actually done now (in that I added that part of the TODO as a comment in the cache config).


<!-- Sent from Reviewable.io -->

2021-12-18 13:27 UTC, miretskiy approved these changes

2021-12-20 18:58 UTC, HonoreDB commented
bors r=[miretskiy]

2021-12-20 21:54 UTC, merged