cluster-ui: remove divider and transparent button on timescale
cockroachdb/cockroach pull request #73752
Opened 2021-12-13 19:34 UTC by xinhaoz

Previously, the timescale dropdown component had transparent button
backgrounds and by default a divider to the left of the dropdown. This
commit removes the divider from the base component and make the button
backgrounds solid to make the component more reusable.

Release note: None

2021-12-13 19:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/73752)
<!-- Reviewable:end -->

2021-12-13 19:38 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73752#-MqpI9xK2xFqDX7qVj9R:-MqpI9xL3u--eXk2e_Vx:b-gkeq9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b29a56008d66ecf765f1273b932621f15e851e/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L238)):*
> ```XML
>   return (
>     <div className={cx("timescale")}>
>       <Divider type="vertical" />
> ```

if you're removing from the component, you will need add the divider on the places that require it, such as Transaction and Statement pages


<!-- Sent from Reviewable.io -->

2021-12-14 21:02 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73752#-MqpI9xK2xFqDX7qVj9R:-MquS-nX-ZuOABAFJ38F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69b29a56008d66ecf765f1273b932621f15e851e/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx#L238)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

if you're removing from the component, you will need add the divider on the places that require it, such as Transaction and Statement pages
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-15 14:30 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73752#-:-MqyUyhhAvKaL_zIST30:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2021-12-15 15:25 UTC, xinhaoz commented
bors r=maryliag

2021-12-15 16:21 UTC, merged