<ui>: added formatting to statements on the statement & transaction details pages.
cockroachdb/cockroach pull request #73853
Opened 2021-12-15 16:50 UTC by THardy98

Previously, statements displayed on the statement/transaction details
pages were not formatted.  Formatting was added to allow for better
readability of statements on these detail pages. Requested statements
are now formatted on the server using the existing pretty-printing
logic. Statements returned from the statement handler now include an
additional "formatted_statement" field.

Release note (ui change): added formatting to statemenets on the
statement & transaction details pages.

2021-12-15 16:50 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=73853) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=73853) before we can accept your contribution.<br/><hr/>**Thomas Hardy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=73853) it.</sub>

2021-12-15 16:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/73853)
<!-- Reviewable:end -->

2021-12-15 17:32 UTC, jocrl requested changes
What issue this solves and before/after screenshots would be helpful for context!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Mqz2o5ZDDfp8NhSvyer:bscsczt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz2CKjEMobTzYBQY4C:-Mqz2CKk4GIjDa7dJsj7:b-pvrjoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L151)):*
> ```
>     statement: "SELECT city, id FROM vehicles WHERE city = $1",
>     formattedStatement: "SELECT city, id FROM vehicles WHERE city = $1",
> ```
Could you modify this to demonstrate the difference between a normal statement and a formatted one?
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-Mqz6NULCjw0mCVtuKWp:bd96ac8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
> ```
>     const formattedStatements = results.map(s => s.formatted_statement);
>     const formattedStatement = formattedStatements.join();
> ```
I'm kinda confused what's going on here. Are you expecting multiple different formatted statements? I'm surprised you would format them nicely then just join everything with a comma. 


<!-- Sent from Reviewable.io -->

2021-12-15 18:26 UTC, Azhng requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[pkg/server/combined_statement_stats.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MqzKSLl4zmrNTP5W58y:-MqzKSLl4zmrNTP5W58z:b-qel9f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/server/combined_statement_stats.go#L183)):*
> ```Go
> 		alignMode := 2
> 		caseMode := 1
> 		metadata.Key.FormattedQuery, err = builtins.PrettyStatementCustomConfig(metadata.Key.Query, lineWidth, alignMode, caseMode)
> ```

When I mentioned that you can use the `builtin` within the RPC handler, I meant that you can embed the builtin directly within the SQL statements, instead of directly pulling the package in here.

So concretely, we currently fetch the statements as follow: 

``` sql
SELECT
  fingerprint_id,
  transaction_fingerprint_id,
  app_name,
  aggregated_ts,
  metadata,
  statistics,
  sampled_plan,
  aggregation_interval
FROM crdb_internal.statement_statistics
```

This will pull in `metadata`  (which includes the `query` field) as is, but we can modify its `query` field by changing our SQL query using the builtin you just created


``` sql
SELECT
  fingerprint_id,
  transaction_fingerprint_id,
  app_name,
  aggregated_ts,
  jsonb_set(
    metadata,
    array['query'],
    to_jsonb(
      prettify_statement(metadata ->> 'query')
    ))
  statistics,
  sampled_plan,
  aggregation_interval
FROM
  crdb_internal.statement_statistics;
```

Now rest of the RPC handler code can just remain unchanged and and the bulk of the work is left to the SQL engine. 


<!-- Sent from Reviewable.io -->

2021-12-15 18:27 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[pkg/sql/sem/builtins/builtins.go, line 8723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MqzLGao3S30OR0Fdyt-:-MqzLGao3S30OR0Fdyt0:b-blmvyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/sql/sem/builtins/builtins.go#L8723)):*
> ```Go
> }
> 
> func PrettyStatementCustomConfig(
> ```

By using the new SQL query above, we don't have to export this function from the builtin package and we can just delete this. 


<!-- Sent from Reviewable.io -->

2021-12-15 18:56 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jocrl)

___
*[pkg/server/combined_statement_stats.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MqzKSLl4zmrNTP5W58y:-MqzOCK43-ybuwxgOQeJ:b-4k1tom) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/server/combined_statement_stats.go#L183)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

When I mentioned that you can use the `builtin` within the RPC handler, I meant that you can embed the builtin directly within the SQL statements, instead of directly pulling the package in here.

So concretely, we currently fetch the statements as follow: 

``` sql
SELECT
  fingerprint_id,
  transaction_fingerprint_id,
  app_name,
  aggregated_ts,
  metadata,
  statistics,
  sampled_plan,
  aggregation_interval
FROM crdb_internal.statement_statistics
```

This will pull in `metadata`  (which includes the `query` field) as is, but we can modify its `query` field by changing our SQL query using the builtin you just created


``` sql
SELECT
  fingerprint_id,
  transaction_fingerprint_id,
  app_name,
  aggregated_ts,
  jsonb_set(
    metadata,
    array['query'],
    to_jsonb(
      prettify_statement(metadata ->> 'query')
    ))
  statistics,
  sampled_plan,
  aggregation_interval
FROM
  crdb_internal.statement_statistics;
```

Now rest of the RPC handler code can just remain unchanged and and the bulk of the work is left to the SQL engine. 
</blockquote></details>

ah, this makes more sense, my mistake I misunderstood.

in the case of an uncombined fetch, making a db query feels a bit counter-productive. Is importing the `builtins` logic in that scenario an acceptable solution, or would a db query okay?
___
*[pkg/sql/sem/builtins/builtins.go, line 8723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MqzLGao3S30OR0Fdyt-:-MqzPdyq4KdyebxIn2XG:b-ezvcc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/sql/sem/builtins/builtins.go#L8723)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

By using the new SQL query above, we don't have to export this function from the builtin package and we can just delete this. 
</blockquote></details>

It's still used as part of the `prettify_function` builtin function. `PrettyStatementCustomConfig` allows for users to pass in custom parameters when calling `prettify_function` in the CLI to customize their config.

I will definitely un-export it, unless with that context in mind, you still think it doesn't provide much value.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz2CKjEMobTzYBQY4C:-MqzLts93Brnr5jMm4hS:b-hfoz2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L151)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

> ```
>     statement: "SELECT city, id FROM vehicles WHERE city = $1",
>     formattedStatement: "SELECT city, id FROM vehicles WHERE city = $1",
> ```
Could you modify this to demonstrate the difference between a normal statement and a formatted one?
</blockquote></details>

In this case, there is no difference (the statement string isn't long or complex enough to for the pretty-printer to change its formatting).

But I think this does highlight a potential issue.

If we decide to change our formatting config `formattedStatement` may not be represented correctly in this fixture.
I think the issue lies with where we store the config settings. If they are stored on the backend, then the console has no scope of potential config changes, which in turn means no visibility to how statements are formatted.

Not sure how we handle these kinds of settings.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-MqzNEOABydoD3nGbGY_:b5ofkyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

> ```
>     const formattedStatements = results.map(s => s.formatted_statement);
>     const formattedStatement = formattedStatements.join();
> ```
I'm kinda confused what's going on here. Are you expecting multiple different formatted statements? I'm surprised you would format them nicely then just join everything with a comma. 
</blockquote></details>

I wasn't certain whether `results` would return multiple possible statements (although I think it only returns the one statement shown on the details page) so I thought a resolution would be to join the multiple formatted statements as a single formatted statement.

... it definitely shouldn't be comma-separated, but regardless, is it okay to assume that only 1 statement is returned here and we don't need to join anyway?


<!-- Sent from Reviewable.io -->

2021-12-15 21:02 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jocrl)

___
*[pkg/sql/sem/builtins/builtins.go, line 8723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MqzLGao3S30OR0Fdyt-:-MqzltEk2UKGJCO10tYy:by5zy4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/sql/sem/builtins/builtins.go#L8723)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

It's still used as part of the `prettify_function` builtin function. `PrettyStatementCustomConfig` allows for users to pass in custom parameters when calling `prettify_function` in the CLI to customize their config.

I will definitely un-export it, unless with that context in mind, you still think it doesn't provide much value.
</blockquote></details>

The custom config method is also currently being used when we fetch uncombined statements (formats on each statement iteration), restricting it from being un-exported.

That being said it could still at least be un-exported if we use the builtin function as you suggested for the combined logic, but I don't think the builtin function query for each statement iteration would be worth. Maybe a better solution would be to change the logic of how we add statements to the container, pre-populating the formatted statement field?

Another option could be to omit statement formatting for non-combined requests if the idea is to solely use combined requests going forward.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-MqzlpAaCJb3QVk-_mMJ:b-m20jxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

I wasn't certain whether `results` would return multiple possible statements (although I think it only returns the one statement shown on the details page) so I thought a resolution would be to join the multiple formatted statements as a single formatted statement.

... it definitely shouldn't be comma-separated, but regardless, is it okay to assume that only 1 statement is returned here and we don't need to join anyway?
</blockquote></details>

Removed the `map` and `join`, under the idea that a single statement is returned.


<!-- Sent from Reviewable.io -->

2021-12-15 22:14 UTC, jocrl requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz2CKjEMobTzYBQY4C:-MqzhasB0kloTlvG7YOA:b-30w0fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L151)):*
Chatted at standup about the config storage; it'll just be a backend constant.

You mention that
> If we decide to change our formatting config formattedStatement may not be represented correctly in this fixture.

The fixture is to use in storybook as an example of how the feature works. So similarly to how the onus is on you to add the field here, if the config changes the responsibility would be on the person who makes that change to also change the fixture example. You make a good point that there's no enforcement that ties this example together with what happens in the code. In this case I'm guessing you added the fixture field because typescript complained, but a change in the value of the string as you point out isn't a type change and won't be enforced.

I'd say that's an issue inherent with storybook - the point is to mock out what the back end provides the front, but that's only as realistic as the mock is accurate. So I'd file your concern under "well, there's a bigger general concern that we accept, so never mind 🙂".

That said, could you still instead change the string to something that's long or complex enough to demonstrate the difference? I see the point of storybook (and tests to an extent) as ways to demonstrate the scope of functionality including edge cases, different scenarios, and what the inputs and outputs look like. For storybook fixtures, the chosen statement should just be an arbitrary example so it should be fine to change the statement. If this specific select statement was demonstrating something I would expect a variable name or comment describing what it was demonstrating.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-Mr-7kHA8DGmHSGZRBOt:b-geim8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Removed the `map` and `join`, under the idea that a single statement is returned.
</blockquote></details>

Err..., so the treatment of `distSQL`, `node_id`, and other fields in the return seems to imply that the filter statement above returns potentially more than one element in the `results` array 🙂.

I suspect that it would return multiple elements where the value of `formattedStatement` are all the same, but I suggest checking what actually happens. I think multiple elements for the same statement will happen if you lower the aggregation interval, so that there are multiple aggregation intervals with the same statement.


<!-- Sent from Reviewable.io -->

2021-12-16 15:49 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mr2rZB25QZGlPoZwQje):*
Since we also introduced a SQL builtin, it's a user-visible change within the SQL Shell, this would qualify this PR to also have `sql change` in its release note. Though it's probably better to split this into 2 commits 
___
*[pkg/roachpb/app_stats.proto, line 190 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mr2rmLx0kqxctaubAhP:-Mr2rmLx0kqxctaubAhQ:bgv4dv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc67ae167a9017a94eec981bc2f86fa1b7a15d06/pkg/roachpb/app_stats.proto#L190)):*
> ```protobuf
>   optional uint64 plan_hash = 10 [(gogoproto.nullable) = false];
>   optional string query_summary = 12 [(gogoproto.nullable) = false];
>   optional string formatted_query = 13 [(gogoproto.nullable) = false];
> ```

Any particular reason that we need to introduce a new protobuf field here? We can simply just overwrite the `query` field here with the prettified statement text before sending the protobuf response to the frontend.

Introducing a new field here means we are incurring additional storage cost in memory as well as on disk. Also, if we *really* do need to introduce a new field here, we also need to update our encoder/decoder accordingly (in `pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil` package) otherwise we won't be able to properly encode/decode this field. 
___
*[pkg/server/combined_statement_stats.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MqzKSLl4zmrNTP5W58y:-Mr2skAwBfP688LTWZeR:b3ab7sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/server/combined_statement_stats.go#L183)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

ah, this makes more sense, my mistake I misunderstood.

in the case of an uncombined fetch, making a db query feels a bit counter-productive. Is importing the `builtins` logic in that scenario an acceptable solution, or would a db query okay?

</blockquote></details>

Hmmm good question :thinking: . My feeling here is that we can probably just leave the uncombined fetch alone (that is, do not prettify it). The reason behind that is that uncombined stats API really shouldn't be used by the frontend code at all. That was mostly left behind as an artifact of 21.1 and we are still in the process of cleaning it up. See #71829 for more details.
___
*[pkg/sql/conn_executor.go, line 518 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mr2tavACxrMxImrA2A2:-Mr2rX086VmQLbtkKHxN:b-w2eyq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc67ae167a9017a94eec981bc2f86fa1b7a15d06/pkg/sql/conn_executor.go#L518)):*
> ```Go
> 
> 	stmtStatsVisitor := func(_ context.Context, stat *roachpb.CollectedStatementStatistics) error {
> 		stat.Key.FormattedQuery, err = builtins.PrettyStatementCustomConfig(stat.Key.Query, lineWidth, alignMode, caseMode)
> ```

Since now the prettifying is handled by the API handler, do we still need to prettify the statement here?
___
*[pkg/sql/sem/builtins/builtins.go, line 8723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MqzLGao3S30OR0Fdyt-:-Mr2u-PJ0taFhDdhf1dw:bxiv3yx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/sql/sem/builtins/builtins.go#L8723)):*
> Maybe a better solution would be to change the logic of how we add statements to the container, pre-populating the formatted statement field?

I'm hesitant going down this route. There are a few reasons:
1. This incurs additional storage cost for an additional field. 
2. This incurs additional compute cost for the write-path. Currently, SQL Stats's write path is on the hot path of query execution. I don't feel the additional benefit of the prettified statement text outweighs the worsened query latency

> Another option could be to omit statement formatting for non-combined requests if the idea is to solely use combined requests going forward.

I like this idea a lot more. Then in this case perhaps we can just reuse the `query` field in the metadata protobuf messange. See my other comments for the reasoning.


<!-- Sent from Reviewable.io -->

2021-12-16 18:17 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[pkg/roachpb/app_stats.proto, line 190 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mr2rmLx0kqxctaubAhP:-Mr3Q_MWA_XtLyoDtW33:b-vs8p6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc67ae167a9017a94eec981bc2f86fa1b7a15d06/pkg/roachpb/app_stats.proto#L190)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Any particular reason that we need to introduce a new protobuf field here? We can simply just overwrite the `query` field here with the prettified statement text before sending the protobuf response to the frontend.

Introducing a new field here means we are incurring additional storage cost in memory as well as on disk. Also, if we *really* do need to introduce a new field here, we also need to update our encoder/decoder accordingly (in `pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil` package) otherwise we won't be able to properly encode/decode this field. 
</blockquote></details>

I wasn't sure if we were using the statement field for other reasons than displaying it on the details page, and didn't want to break anything by changing its contents (I think we retrieve it from the URL on the details page, not sure if we wanted the formatted statement in the URL).

If it is the case that it's okay to be replaced, I can make that change.
___
*[pkg/server/combined_statement_stats.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MqzKSLl4zmrNTP5W58y:-Mr3RVY68h7pUKOZ1HJB:bag84ib) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/server/combined_statement_stats.go#L183)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmmm good question :thinking: . My feeling here is that we can probably just leave the uncombined fetch alone (that is, do not prettify it). The reason behind that is that uncombined stats API really shouldn't be used by the frontend code at all. That was mostly left behind as an artifact of 21.1 and we are still in the process of cleaning it up. See #71829 for more details.
</blockquote></details>

Sweet. I'll remove it then.
___
*[pkg/sql/conn_executor.go, line 518 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mr2tavACxrMxImrA2A2:-Mr3RXuJ8XiAkojhbcjT:b-4wnbzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc67ae167a9017a94eec981bc2f86fa1b7a15d06/pkg/sql/conn_executor.go#L518)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Since now the prettifying is handled by the API handler, do we still need to prettify the statement here?
</blockquote></details>

Nope. Will remove.
___
*[pkg/sql/sem/builtins/builtins.go, line 8723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MqzLGao3S30OR0Fdyt-:-Mr3R_1W9E6cCHxENrxb:bg5hcyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/sql/sem/builtins/builtins.go#L8723)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

> Maybe a better solution would be to change the logic of how we add statements to the container, pre-populating the formatted statement field?

I'm hesitant going down this route. There are a few reasons:
1. This incurs additional storage cost for an additional field. 
2. This incurs additional compute cost for the write-path. Currently, SQL Stats's write path is on the hot path of query execution. I don't feel the additional benefit of the prettified statement text outweighs the worsened query latency

> Another option could be to omit statement formatting for non-combined requests if the idea is to solely use combined requests going forward.

I like this idea a lot more. Then in this case perhaps we can just reuse the `query` field in the metadata protobuf messange. See my other comments for the reasoning.
</blockquote></details>

Will remove. Left a comment regarding the `query` field in the protobuf message.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz2CKjEMobTzYBQY4C:-Mr3RhTN1ubS4rkKQB32:btfvutn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L151)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Chatted at standup about the config storage; it'll just be a backend constant.

You mention that
> If we decide to change our formatting config formattedStatement may not be represented correctly in this fixture.

The fixture is to use in storybook as an example of how the feature works. So similarly to how the onus is on you to add the field here, if the config changes the responsibility would be on the person who makes that change to also change the fixture example. You make a good point that there's no enforcement that ties this example together with what happens in the code. In this case I'm guessing you added the fixture field because typescript complained, but a change in the value of the string as you point out isn't a type change and won't be enforced.

I'd say that's an issue inherent with storybook - the point is to mock out what the back end provides the front, but that's only as realistic as the mock is accurate. So I'd file your concern under "well, there's a bigger general concern that we accept, so never mind 🙂".

That said, could you still instead change the string to something that's long or complex enough to demonstrate the difference? I see the point of storybook (and tests to an extent) as ways to demonstrate the scope of functionality including edge cases, different scenarios, and what the inputs and outputs look like. For storybook fixtures, the chosen statement should just be an arbitrary example so it should be fine to change the statement. If this specific select statement was demonstrating something I would expect a variable name or comment describing what it was demonstrating.
</blockquote></details>

You guess right :)

Thanks for the explanation, I'll definitely change the query string to something that warrants some formatting changes, good idea.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-Mr3S8GbE1BlGrEBKE_O:b-m647g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Err..., so the treatment of `distSQL`, `node_id`, and other fields in the return seems to imply that the filter statement above returns potentially more than one element in the `results` array 🙂.

I suspect that it would return multiple elements where the value of `formattedStatement` are all the same, but I suggest checking what actually happens. I think multiple elements for the same statement will happen if you lower the aggregation interval, so that there are multiple aggregation intervals with the same statement.
</blockquote></details>

I'll revert it back.

Simple solution would be to create a set of formatted statements, then join them with a newline character.


<!-- Sent from Reviewable.io -->

2021-12-17 21:52 UTC, jocrl requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-Mr9MQKwDwPjveYLYiQv:bspyziu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
> Simple solution would be to create a set of formatted statements, then join them with a newline character.

I think it's worth taking a look at what the actual input looks like (hence the suggestion to lower the aggregation to recreate the input) before deciding what to do... since as you mention, I expect there to be only one statement, and so only one formatted statement. Maybe the same formatted statement is repeated in the array, so if you just join them with a newline you might get the same thing repeated a bunch.


<!-- Sent from Reviewable.io -->

2021-12-17 22:06 UTC, jocrl requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz2CKjEMobTzYBQY4C:-Mr9Oyek46wxg_1wVTEV:b-4p4tch) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L151)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

You guess right :)

Thanks for the explanation, I'll definitely change the query string to something that warrants some formatting changes, good idea.
</blockquote></details>

Oo, I should also mention that you can run storybook for db console and cluster ui by running `yarn run storybook` in their respective directories.

Storybook as mentioned is useful for enumerating and testing various cases without having to recreate the in the back end. E.g., if you wanted to test how a component displaying an error message behaves if the error message is super long, but you don't want to have to bother recreating a real error with a super long message in the db.


<!-- Sent from Reviewable.io -->

2021-12-23 13:38 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-MrbUt45-Ymq1fspjGhr:b6mp6bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

> Simple solution would be to create a set of formatted statements, then join them with a newline character.

I think it's worth taking a look at what the actual input looks like (hence the suggestion to lower the aggregation to recreate the input) before deciding what to do... since as you mention, I expect there to be only one statement, and so only one formatted statement. Maybe the same formatted statement is repeated in the array, so if you just join them with a newline you might get the same thing repeated a bunch.
</blockquote></details>

Taken a look. From my testing on an aggregate interval of 10s, it only returns one statement even if the statement is executed multiple times within the same aggregate interval.

That being said, I think the aforementioned implementation using a set still stands (a set will only keep unique statements so duplicates should not be an issue) and would cover the case where multiple results are returned if changes in functionality in the future allow for it.

If covering this case is overkill, it can easily be removed.


<!-- Sent from Reviewable.io -->

2021-12-23 23:14 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jocrl)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mr2rZB25QZGlPoZwQje):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Since we also introduced a SQL builtin, it's a user-visible change within the SQL Shell, this would qualify this PR to also have `sql change` in its release note. Though it's probably better to split this into 2 commits 
</blockquote></details>

added `sql change` to the release note, but have kept it as a single commit
is splitting into multiple commits common for a PR?
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz2CKjEMobTzYBQY4C:-MrdZe-xErLXTd5pE5XG:b-khdg2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L151)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Oo, I should also mention that you can run storybook for db console and cluster ui by running `yarn run storybook` in their respective directories.

Storybook as mentioned is useful for enumerating and testing various cases without having to recreate the in the back end. E.g., if you wanted to test how a component displaying an error message behaves if the error message is super long, but you don't want to have to bother recreating a real error with a super long message in the db.
</blockquote></details>

Sweet :)

I've made changes to the statement details and statements page fixtures to show formatted statements, definitely better for transparency.


<!-- Sent from Reviewable.io -->

2022-01-04 17:31 UTC, jocrl requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-Ms_ndPY5gjj72LIEsAL:b-3pa03a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Taken a look. From my testing on an aggregate interval of 10s, it only returns one statement even if the statement is executed multiple times within the same aggregate interval.

That being said, I think the aforementioned implementation using a set still stands (a set will only keep unique statements so duplicates should not be an issue) and would cover the case where multiple results are returned if changes in functionality in the future allow for it.

If covering this case is overkill, it can easily be removed.
</blockquote></details>

Okay, yeah, I think that solution makes sense. Might be worth asking Kevin if he has an idea if/when there might be multiple statements on the page.

I saw your comment in db-console/.../statementDetails.tsx explaining that we don't know the >1 statement use case; thanks! Could you also add that here?
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Msa1a198CMpC2nD2fhu:-Msa1a198CMpC2nD2fhv:b-5lr194) ([raw file](https://github.com/cockroachdb/cockroach/blob/d184324db4d07079d912f804b01b0799f97327a9/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L151)):*
> ```XML
>   // If the aggregatedTs is unset, we will aggregate across the current date range.
>   const aggregatedTs = queryByName(location, aggregatedTsAttr);
>   const aggInterval = queryByName(location, aggregationIntervalAttr);
> ```

Sorry for being long-winded! If I'm understanding this correctly, I'm seeing some things here:

1) In the past, one used to be able to generate URLs to statement details pages without specifying an `aggregated_ts` query parameter, and have it aggregate across "the current date range", which I'm understanding through the implementation to mean everything returned by the response (which presumably queried for the "current date range"). This change removes this functionality of when aggregatedTs is unset in the URL.

2) This got removed, but aggregatedTs is still passed in generating `<StatementLink`, even though it is no longer respected and instead uses the aggregated ts value in built into the statementKey/aggregateKey. A full clean solution would remove the aggregatedTs from being used in `<StatementLink`.

3) That said... an upcoming thing I'm supposed to implement is to be able to have a statement details page that aggregates across a certain aggregatedTs, across multiple aggregation intervals
![image.png](https://files.reviewableusercontent.io/images/reviewable/91907326/hOGu03Oe1JvKFgFwIUtf6C33/image.png)

Would it be possible/sensible to pass `statement_fingerprint_id` in the URL query param, instead of `statementKey`? The prior implementation separated aggregated_ts and aggregation_interval when they are passed in the URL, then stuck them back together to create the statementKey. I think the current implementation should do the same, and in this file you would remove the `implicit_txn` and `database` stuff as you've done, but not the aggregatedTs and aggInterval stuff.



_Code quote:_
```XML
  // If the aggregatedTs is unset, we will aggregate across the current date range.
  const aggregatedTs = queryByName(location, aggregatedTsAttr);
  const aggInterval = queryByName(location, aggregationIntervalAttr);
```


<!-- Sent from Reviewable.io -->

2022-01-04 17:56 UTC, Azhng reviewed
> Reviewed 1 of 21 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mr2rZB25QZGlPoZwQje):*
> is splitting into multiple commits common for a PR?

Yeah it's fairly common. You can even split it into multiple PRs :smile: . In this case, I think it might be preferred if we can split the UI change (where we change how we link to Statement Detail Page) and the SQL change
___
*[pkg/server/combined_statement_stats.go, line 115 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaAvOGEeDF7OxYkvwV:-MsaAvOGEeDF7OxYkvwW:b-aq3yac) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/combined_statement_stats.go#L115)):*
> ```Go
> 	const lineWidth = 108
> 	const alignMode = 2
> 	const caseMode = 1
> ```

can we directly use `tree.UpperCase` and `tree.PrettyAlignAndDeindent` here ?  Hmm also just curious, how is `108` chosen here? 
___
*[pkg/server/combined_statement_stats.go, line 189 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaBQ-h7E2DguNsTnpd:-MsaBQ-h7E2DguNsTnpe:bupq4n9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/combined_statement_stats.go#L189)):*
> ```Go
> 			roachpb.TransactionFingerprintID(transactionFingerprintID)
> 
> 		if err != nil {
> ```

Hmm why additional error check here? 
___
*[pkg/server/index_usage_stats.go, line 233 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaBiFtEsRgIYeSGJVr:-MsaBiFtEsRgIYeSGJVs:b-6ghair) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/index_usage_stats.go#L233)):*
> ```Go
> 			total_reads,
> 			last_read,
> 			prettify_statement(indexdef)
> ```

Hmm why are we using the string overloaded `prettify_statement` builtin here? It seems like `tree.DefaultPrettyCfg()` is slightly different from the values you used in the other file? 
___
*[pkg/server/status_test.go, line 1928 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaAVnWAly77S5ieMA5:-MsaAVnWAly77S5ieMA6:b60hwpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/status_test.go#L1928)):*
> ```Go
> 		stmt                 string
> 		formattedStmt        string
> 		fingerprinted        string
> ```

nit: we can just call it `fingerprint` here.
___
*[pkg/server/status_test.go, line 1929 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaAa-_52BjN_KBFjFi:-MsaAa-_52BjN_KBFjFj:b6q05e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/status_test.go#L1929)):*
> ```Go
> 		formattedStmt        string
> 		fingerprinted        string
> 		formattedFingerPrint string
> ```

nit `s/formattedFingerPrint/formattedFingerprint/` 
___
*[pkg/server/status_test.go, line 1931 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaA2wt72nCcrOzebE1:-MsaA2wt72nCcrOzebE2:b4s9bec) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/status_test.go#L1931)):*
> ```Go
> 		formattedFingerPrint string
> 	}{
> 		{stmt: `CREATE DATABASE roachblog`,
> ```

nit: we can just expand the struct initialization here: 


``` golang
{
  stmt:          `CREATE DATABASE roachblog`,
  formattedStmt: `CREATE DATABASE roachblog\n`,
},
// ... 
```


<!-- Sent from Reviewable.io -->

2022-01-04 18:11 UTC, maryliag reviewed
> Reviewed 1 of 13 files at r1, 2 of 21 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx, line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaF7Cp78oVJG6AttZs:-MsaF7Cq4IJQwvdXpv-j:b-vvj3vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx#L53)):*
> ```XML
> import classNames from "classnames/bind";
> import { commonStyles } from "src/common";
> import Long from "long";
> ```

nit: where is this being used?
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-MsaFq_IDnTr3chcN2O1:bdlqcdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Okay, yeah, I think that solution makes sense. Might be worth asking Kevin if he has an idea if/when there might be multiple statements on the page.

I saw your comment in db-console/.../statementDetails.tsx explaining that we don't know the >1 statement use case; thanks! Could you also add that here?
</blockquote></details>

you should only have 1 result here. The key used to retrieve the statement should be specific per statement + aggregation time +app name etc. 
Because we have only one row per statement fingerprint on the same aggregation period you will only have one result. 
Even when we have the same fingerprint on different aggregation periods, the changes @jocrl is doing will make it that only one statement fingerprint is returned, with the combined value of all aggregation periods, so the Details page should align with what we're seeing on the Statements main page. (Similar case for transactions)
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 130 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaHD_c6k8xejnLTBdX:-MsaHD_c6k8xejnLTBdY:b423lik) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L130)):*
> ```XML
> // The aggregate key value will need to change if implementation of
> // 'statementKey' in appStats.ts changes.
> const aggregateKey = fingerprintID + aggregatedTs + aggregationInterval;
> ```

I think database is also part of key, isn't it?


<!-- Sent from Reviewable.io -->

2022-01-04 18:26 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 130 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaHD_c6k8xejnLTBdX:-MsaKw1UAnCCRWFD50k8:bigbh59) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L130)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I think database is also part of key, isn't it?
</blockquote></details>

I think the database is already [included](https://github.com/cockroachdb/cockroach/blob/3cf7120f20497050f4a73e3644936bbfe5eeec02/pkg/roachpb/app_stats.go#L43) in the `fingerprintID`


<!-- Sent from Reviewable.io -->

2022-01-04 20:21 UTC, jocrl requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-Msagnh6Ab_wsST5HJ-j:b-1ryata) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
Ah, okay, thanks!

> Even when we have the same fingerprint on different aggregation periods, the changes @jocrl is doing will make it that only one statement fingerprint is returned, with the combined value of all aggregation periods

I don't think this changes Thomas' implementation, but chatting with Xin Hao it sounds like it will be a cheaper implementation to aggregate on the front end. So there will still be the same fingerprint repeated for different aggregation periods. Just wanted to run this by you @maryliag, whether you anticipate problems with aggregating on the front? I'm going to prioritize de-risking this, and happy to chat off-thread.


<!-- Sent from Reviewable.io -->

2022-01-04 20:24 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-Msakc5N8yUP9x1XNAW_:b-kk686g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Ah, okay, thanks!

> Even when we have the same fingerprint on different aggregation periods, the changes @jocrl is doing will make it that only one statement fingerprint is returned, with the combined value of all aggregation periods

I don't think this changes Thomas' implementation, but chatting with Xin Hao it sounds like it will be a cheaper implementation to aggregate on the front end. So there will still be the same fingerprint repeated for different aggregation periods. Just wanted to run this by you @maryliag, whether you anticipate problems with aggregating on the front? I'm going to prioritize de-risking this, and happy to chat off-thread.
</blockquote></details>

Could be an issue with the pagination. If we aggregated on the frontend, it might miss data on that "page" that should be aggregated on the same fingerprint, but if the aggregation is done on the backend you don't risk having this issue, since you would group and then create the pages


<!-- Sent from Reviewable.io -->

2022-01-05 18:04 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/server/combined_statement_stats.go, line 115 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaAvOGEeDF7OxYkvwV:-Msaop1e0w8q4UQGgSzR:b-yf3k4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/combined_statement_stats.go#L115)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

can we directly use `tree.UpperCase` and `tree.PrettyAlignAndDeindent` here ?  Hmm also just curious, how is `108` chosen here? 
</blockquote></details>

Changed to use `tree.Uppercase` and `tree.PrettyAlignAndDeindent` is much more intuitive and removes the need for magic numbers.

108 was chosen via the discussion on the original issue: https://github.com/cockroachdb/cockroach/issues/71544

I've added a `LineWidthMode` to `pretty.go`, with a default and "console" mode to reflect these different values, also helping remove the remaining use of magic numbers here.
___
*[pkg/server/combined_statement_stats.go, line 189 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaBQ-h7E2DguNsTnpd:-MsalvacAueG-y7q9ZE_:bjpzuix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/combined_statement_stats.go#L189)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm why additional error check here? 
</blockquote></details>

Missed that, removed.
___
*[pkg/server/index_usage_stats.go, line 233 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaBiFtEsRgIYeSGJVr:-MsaqwJi7bPcxrj1UM7H:b-bzx5td) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/index_usage_stats.go#L233)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm why are we using the string overloaded `prettify_statement` builtin here? It seems like `tree.DefaultPrettyCfg()` is slightly different from the values you used in the other file? 
</blockquote></details>

I imagine indices should be formatted with the same specified parameters as the other file, made the respective change.
___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx, line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaF7Cp78oVJG6AttZs:-Msb52hB9DeEkEKpoRzI:bra1o7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx#L53)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: where is this being used?
</blockquote></details>

Missed that, most likely left over from previous changes but it wasn't marked as unused due to lines 83 & 84.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mqz6NULCjw0mCVtuKWo:-Msef86gEwTTcXcpU-Vr:b-dxgafn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff402ca282985ed54531d3fba75845be669c0e77/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L165)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Could be an issue with the pagination. If we aggregated on the frontend, it might miss data on that "page" that should be aggregated on the same fingerprint, but if the aggregation is done on the backend you don't risk having this issue, since you would group and then create the pages
</blockquote></details>

With this in mind, I'll remove the redundant logic concerning the case of multiple returned results.
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Msa1a198CMpC2nD2fhu:-MsfJZE01_DLIiBluR9N:bv3xjly) ([raw file](https://github.com/cockroachdb/cockroach/blob/d184324db4d07079d912f804b01b0799f97327a9/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L151)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Sorry for being long-winded! If I'm understanding this correctly, I'm seeing some things here:

1) In the past, one used to be able to generate URLs to statement details pages without specifying an `aggregated_ts` query parameter, and have it aggregate across "the current date range", which I'm understanding through the implementation to mean everything returned by the response (which presumably queried for the "current date range"). This change removes this functionality of when aggregatedTs is unset in the URL.

2) This got removed, but aggregatedTs is still passed in generating `<StatementLink`, even though it is no longer respected and instead uses the aggregated ts value in built into the statementKey/aggregateKey. A full clean solution would remove the aggregatedTs from being used in `<StatementLink`.

3) That said... an upcoming thing I'm supposed to implement is to be able to have a statement details page that aggregates across a certain aggregatedTs, across multiple aggregation intervals
![image.png](https://files.reviewableusercontent.io/images/reviewable/91907326/hOGu03Oe1JvKFgFwIUtf6C33/image.png)

Would it be possible/sensible to pass `statement_fingerprint_id` in the URL query param, instead of `statementKey`? The prior implementation separated aggregated_ts and aggregation_interval when they are passed in the URL, then stuck them back together to create the statementKey. I think the current implementation should do the same, and in this file you would remove the `implicit_txn` and `database` stuff as you've done, but not the aggregatedTs and aggInterval stuff.
</blockquote></details>

Nice catch, I hadn't notice the change in functionality by removing `aggregatedTs` and `aggInterval`. I've added them back in and reverted the filtering logic in `filterByKeys` to include the aggregation conditionals but without the `database` and `implicit_txn` conditionals.

I've kept the aggregatedTs and aggInterval in the URL and instead pass the statement fingerprint id as you suggested. Most significantly, to accommodate this change `AggregateStatistics` no longer stores the statement's "key" (i.e. fingerprint + aggregate timestamp + aggregate interval), but the fingerprint of the statement being aggregated. This change should not have any negative repercussions.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 130 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaHD_c6k8xejnLTBdX:-Msb5if8DK1pgw37qUaC:bb3zsoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L130)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I think the database is already [included](https://github.com/cockroachdb/cockroach/blob/3cf7120f20497050f4a73e3644936bbfe5eeec02/pkg/roachpb/app_stats.go#L43) in the `fingerprintID`
</blockquote></details>

Yea, I think it's already part of the `fingerprintID`, originating from `ConstructStatementFingerprintID` in `app_stats.go`.
___
*[pkg/server/status_test.go, line 1928 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaAVnWAly77S5ieMA5:-Msb5P-bCIOXe3vvzBtA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/status_test.go#L1928)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: we can just call it `fingerprint` here.
</blockquote></details>

Done.
___
*[pkg/server/status_test.go, line 1929 at r6] [...]

2022-01-05 18:41 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mr2rZB25QZGlPoZwQje):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

> is splitting into multiple commits common for a PR?

Yeah it's fairly common. You can even split it into multiple PRs :smile: . In this case, I think it might be preferred if we can split the UI change (where we change how we link to Statement Detail Page) and the SQL change
</blockquote></details>

Split into 2 commits, one reflecting the `sql change` and the other reflecting the `ui change`.


<!-- Sent from Reviewable.io -->

2022-01-06 14:40 UTC, maryliag reviewed
> Reviewed 2 of 16 files at r7, 1 of 1 files at r8, 1 of 15 files at r9, 15 of 15 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mr2rZB25QZGlPoZwQje):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Split into 2 commits, one reflecting the `sql change` and the other reflecting the `ui change`.
</blockquote></details>

your message for the sql commit got messed up, the title is including part of the description
___
*[-- commits, line 5 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsjmSXo4J1fBlrDHGqv):*
nit: ...formatted, making...
___
*[-- commits, line 30 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsjmaTV28thirhrw-VV):*
you can update this message to include only the ui change
___
*[pkg/server/index_usage_stats.go, line 233 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsjnGyb2zlbFbQpSy8S:-MsjnGyb2zlbFbQpSy8T:b9470p) ([raw file](https://github.com/cockroachdb/cockroach/blob/51cc371458e478989bb02b2db2ef9ba79ef113fb/pkg/server/index_usage_stats.go#L233)):*
> ```Go
> 			total_reads,
> 			last_read,
> 			indexdef
> ```

why the removal of `indexdef`?


<!-- Sent from Reviewable.io -->

2022-01-06 15:19 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mr2rZB25QZGlPoZwQje):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

your message for the sql commit got messed up, the title is including part of the description
</blockquote></details>

title was too long it was overflowing, shortened it.
___
*[-- commits, line 5 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsjmSXo4J1fBlrDHGqv):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: ...formatted, making...
</blockquote></details>

added comma.
___
*[-- commits, line 30 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsjmaTV28thirhrw-VV):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you can update this message to include only the ui change
</blockquote></details>

updated.
___
*[pkg/server/index_usage_stats.go, line 233 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsjnGyb2zlbFbQpSy8S:-MsjxCj_2gn0ra-1mDmD:b3guqnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/51cc371458e478989bb02b2db2ef9ba79ef113fb/pkg/server/index_usage_stats.go#L233)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why the removal of `indexdef`?
</blockquote></details>

Wasn't removed, just changed to `prettify_statement(indexdef, %d, %d %d)...` to return the prettified format of the index definition.


<!-- Sent from Reviewable.io -->

2022-01-06 15:29 UTC, maryliag reviewed
> Reviewed 1 of 16 files at r7, 15 of 15 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @THardy98)

___
*[pkg/server/index_usage_stats.go, line 233 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsjnGyb2zlbFbQpSy8S:-Msk-CSM3U3Y3cK-vH3l:b-6snwzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/51cc371458e478989bb02b2db2ef9ba79ef113fb/pkg/server/index_usage_stats.go#L233)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Wasn't removed, just changed to `prettify_statement(indexdef, %d, %d %d)...` to return the prettified format of the index definition.
</blockquote></details>

ahh nice!


<!-- Sent from Reviewable.io -->

2022-01-06 15:41 UTC, jocrl reviewed
Front end lgtm! Thanks :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Msk23pv6tICK9hZJGC8:b-lt1vfy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)



<!-- Sent from Reviewable.io -->

2022-01-06 15:41 UTC, jocrl approved these changes

2022-01-06 17:01 UTC, Azhng reviewed
Backend all looks good :fire:. Just some questions and nits for the frontend.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-MskKVl26is_wBtvl7eS:b-3j8d21)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/server/index_usage_stats.go, line 233 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaBiFtEsRgIYeSGJVr:-MskHcAc2bhSODoncAwk:b980dgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/index_usage_stats.go#L233)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

I imagine indices should be formatted with the same specified parameters as the other file, made the respective change.
</blockquote></details>

Nice! Though were you having issue to get `makeSQLQuery()` to work? In general we should avoid using `fmt.Sprintf()` to construct SQL queries since it leaves us in a vulnerable place for SQL injection. 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 152 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MskJUx7CcjRRHpGnLW5:-MskJUx87TRDeSN2fq0y:b-dl7c7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b75c6ab65cba92f399501b7a06bc975c135235/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L152)):*
> ```XML
>     const statementFingerprintID = getMatchParamByName(
>       props.match,
>       statementAttr,
> ```

One thing I just realized here is that: we are changing the semantics of the `statementAttr` query param in the URL. Previously, `statementAttr` means the statement fingerprint, but now the `statementAttr` means the statement fingerprint ID. 

I'm not entirely sure what's the implication of this for the rest of our frontend code base, or if this is going to be problematic. I guess one thing this can break is that if an user saves an URL from 21.2 cluster, and open the same URL on a 22.1 cluster, this can break. Though I'm not certain this is the level of backward compatiblity that we need to support. cc @maryliag thoughts ? 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 163 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MskIJP_0eOZ2o4on1Qi:-MskIJP_0eOZ2o4on1Qj:b-c42m3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b75c6ab65cba92f399501b7a06bc975c135235/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L163)):*
> ```XML
> 
>     // We expect a single result to be returned. The key used to retrieve results is specific per:
>     // - statement fingerprint
> ```

nit: `s/statement fingerprint/statement fingerprint id/`. Those two means kind of different things:
* the fingerprint is the anonymized query string
* the fingerprint id is the 8 byte hash (represented as either uint64 in backend or raw bytes column in SQL)
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 193 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MskJE9D2lfrQYXQOay4:-MskJE9ED1qmBpJKEQv-:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b75c6ab65cba92f399501b7a06bc975c135235/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L193)):*
> ```XML
> 
>     // We expect a single result to be returned. The key used to retrieve results is specific per:
>     // - statement fingerprint
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-01-06 18:58 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/server/index_usage_stats.go, line 233 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaBiFtEsRgIYeSGJVr:-Mskg2PC1lFfjtlR_iR6:bnn5z2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/index_usage_stats.go#L233)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Nice! Though were you having issue to get `makeSQLQuery()` to work? In general we should avoid using `fmt.Sprintf()` to construct SQL queries since it leaves us in a vulnerable place for SQL injection. 
</blockquote></details>

Not at all, I just replicated the pattern we used in `combined_statement_stats.go`, though using `append` in `makeSQLQuery` should've been intuitive...

changed to use `makeSQLQuery`.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 163 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MskIJP_0eOZ2o4on1Qi:-Mskg_5Y4fU5mFhauiO9:b-2jcr9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b75c6ab65cba92f399501b7a06bc975c135235/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L163)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `s/statement fingerprint/statement fingerprint id/`. Those two means kind of different things:
* the fingerprint is the anonymized query string
* the fingerprint id is the 8 byte hash (represented as either uint64 in backend or raw bytes column in SQL)
</blockquote></details>

Yup, forgot to update, nice catch :) 
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 193 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MskJE9D2lfrQYXQOay4:-Mskgype4keBrKEJJb0b:b-sfotxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b75c6ab65cba92f399501b7a06bc975c135235/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L193)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

updated :)


<!-- Sent from Reviewable.io -->

2022-01-06 19:02 UTC, Azhng reviewed
All lgtm! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Just waiting for marylia to see if it's fine for us to change the semantics of `statementAttr` query params.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Mskl1lX9M_t34XPVQ8c:b-3p2g3r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/server/index_usage_stats.go, line 233 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MsaBiFtEsRgIYeSGJVr:-Mskki8AETODJ1R3vGrU:b-te27mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfde513b88e11b97020375eca41a7e28c2fb292c/pkg/server/index_usage_stats.go#L233)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Not at all, I just replicated the pattern we used in `combined_statement_stats.go`, though using `append` in `makeSQLQuery` should've been intuitive...

changed to use `makeSQLQuery`.
</blockquote></details>

Awesome! Yeah we haven't been consistent with our SQL statement formatting throughout the code base (i'm partially responsible too :sweat_smile:) but it's nice that we start to pay attentions to things like this.


<!-- Sent from Reviewable.io -->

2022-01-06 19:32 UTC, maryliag reviewed
The change on query params are okay. The code looks good, but I want to do some testing and then I will give the approval (hopefully later today)

> Reviewed 1 of 18 files at r5, 4 of 21 files at r6, 1 of 16 files at r13, 15 of 15 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Msks0irC97wC_apRewB:b6n0euu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 152 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-MskJUx7CcjRRHpGnLW5:-MskrDez3EZmxMLTdb0u:b-tnkk52) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b75c6ab65cba92f399501b7a06bc975c135235/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L152)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

One thing I just realized here is that: we are changing the semantics of the `statementAttr` query param in the URL. Previously, `statementAttr` means the statement fingerprint, but now the `statementAttr` means the statement fingerprint ID. 

I'm not entirely sure what's the implication of this for the rest of our frontend code base, or if this is going to be problematic. I guess one thing this can break is that if an user saves an URL from 21.2 cluster, and open the same URL on a 22.1 cluster, this can break. Though I'm not certain this is the level of backward compatiblity that we need to support. cc @maryliag thoughts ? 
</blockquote></details>

That change was necessary because of cases where the fingerprint was huge and would end up breaking the size, with the id we don't have this type of issue anymore and is what we're also using the transaction page. We don't need to worry about the case you mentioned.


<!-- Sent from Reviewable.io -->

2022-01-06 19:37 UTC, jocrl reviewed
Ooo, good point about the backwards compatibility of URLs. @maryliag, does this mean that we generally don't have to worry about  backwards compatibility of URLs, as long as they are consistent (i.e. no broken links) within a version?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-MskszizA7CFh-Asw6ei:b18wtjt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)



<!-- Sent from Reviewable.io -->

2022-01-06 19:47 UTC, maryliag reviewed
In general we do worry about URL compatibility, this is why sometimes we create redirection of routes. 
For example, when I created the new SQL Activity page, I didn't remove the previous Statement and Transactions routes, instead I redirected them to the new SQL Activity route with the right tab selected.  

For this particular case I don't think we should worry because those urls are very ephemeral, in the sense those stats are cleanup with time and is not something people would tend to bookmark, so adding all the extra code to convert from one type to the other is a lot of checks for something small, but I'm open to different opinions if you all things we should be handling that case. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-MskuYpV5FLGuRF-wHHw:b-hni91y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)



<!-- Sent from Reviewable.io -->

2022-01-10 15:29 UTC, maryliag approved these changes
Great work on this! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Mt3ayIg-5eMpb_ZA00Y:b-xt04b1)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)



<!-- Sent from Reviewable.io -->

2022-01-10 17:55 UTC, Azhng approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :fire: :rocket: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Mt47M8f9H3WQG8ZtV6n:bpowf65)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)



<!-- Sent from Reviewable.io -->

2022-01-10 17:56 UTC, THardy98 commented
bors r+

2022-01-10 18:00 UTC, maryliag commented
bors r-

(sorry, just realized a few small changes you need to add)

2022-01-10 18:09 UTC, maryliag requested changes
since stmt.statement_fingerprint_id is a new field, you need to check for its existing on the frontend, for the cases where we have an older cluster with this ui. So I added some comments just about modifying to check the value before using

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Mt4AOY2EgSBQZJBUFSz:b-nj5pdn)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 55 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt48o12652xd0zL0GWq:-Mt48o12652xd0zL0GWr:b-gtxowt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L55)):*
> ```XML
>     if (!(key in statsKey)) {
>       statsKey[key] = {
>         statementFingerprintID: stmt.statement_fingerprint_id.toString(),
> ```

stmt.statement_fingerprint_id?.toString()
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 72 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4AFyp1RLdODwAeEuN:-Mt4AFyp1RLdODwAeEuO:b6lniu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L72)):*
> ```XML
>     const stmt = statsKey[key];
>     return {
>       aggregateFingerprintID: stmt.statementFingerprintID,
> ```

nit: aggregatedFingerprintID
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 117 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt48ykH3j1OSLebPL0X:-Mt48ykH3j1OSLebPL0Y:b-gtxowt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L117)):*
> ```XML
> 
>   const filterByKeys = (stmt: ExecutionStatistics) =>
>     stmt.statement_fingerprint_id.toString() === statementFingerprintID &&
> ```

stmt.statement_fingerprint_id?.toString()
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.selectors.ts, line 177 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt498t2Boo2ih1CplIl:-Mt498t2Boo2ih1CplIm:b-gtxowt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.selectors.ts#L177)):*
> ```XML
>       if (!(key in statsByStatementKey)) {
>         statsByStatementKey[key] = {
>           statementFingerprintID: stmt.statement_fingerprint_id.toString(),
> ```

stmt.statement_fingerprint_id?.toString()
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.selectors.ts, line 194 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4AHVd1u6jO71wflMd:-Mt4AHVd1u6jO71wflMe:b6lniu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.selectors.ts#L194)):*
> ```XML
>       const stmt = statsByStatementKey[key];
>       return {
>         aggregateFingerprintID: stmt.statementFingerprintID,
> ```

nit: aggregatedFingerprintID
___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx, line 206 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4AJ0V0T6aHlodmiuJ:-Mt4AJ0V0T6aHlodmiuK:b6lniu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx#L206)):*
> ```XML
> 
> export interface AggregateStatistics {
>   aggregateFingerprintID: string;
> ```

nit: aggregatedFingerprintID
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 103 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49HJHELwaa4aY8lOh:-Mt49HJHELwaa4aY8lOi:bmjcgfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L103)):*
> ```XML
>     if (!(key in statsKey)) {
>       statsKey[key] = {
>         aggregateFingerprintID: s.statement_fingerprint_id.toString(),
> ```

stmt.statement_fingerprint_id?.toString()

nit: aggregatedFingerprintID
___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts, line 262 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49Nja4J6hWIBGvj2v:-Mt49Nja4J6hWIBGvj2w:b-gtxowt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts#L262)):*
> ```XML
> export function statementKey(stmt: ExecutionStatistics): string {
>   return (
>     stmt.statement_fingerprint_id.toString() +
> ```

stmt.statement_fingerprint_id?.toString()
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 83 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49TAnA7UuGDZrZmg8:-Mt49TAnA7UuGDZrZmg9:b-gtxowt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L83)):*
> ```XML
>     if (!(key in statsKey)) {
>       statsKey[key] = {
>         statementFingerprintID: stmt.statement_fingerprint_id.toString(),
> ```

stmt.statement_fingerprint_id?.toString()
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 100 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4A3al2NcwA5SjGmQw:-Mt4A3al2NcwA5SjGmQx:b6lniu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L100)):*
> ```XML
>     const stmt = statsKey[key];
>     return {
>       aggregateFingerprintID: stmt.statementFingerprintID,
> ```

nit: aggregatedFingerprintID
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 145 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49V-H2WP6jFeq-viA:-Mt49V-H2WP6jFeq-viB:b-gtxowt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L145)):*
> ```XML
> 
>   const filterByKeys = (stmt: ExecutionStatistics) =>
>     stmt.statement_fingerprint_id.toString() === statementFingerprintID &&
> ```

stmt.statement_fingerprint_id?.toString()
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx, line 122 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49XcL3N5NmaSpZt3i:-Mt49XcL3N5NmaSpZt3j:b-gtxowt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L122)):*
> ```XML
>       if (!(key in statsByStatementKey)) {
>         statsByStatementKey[key] = {
>           statementFingerprintID: stmt.statement_fingerprint_id.toString(),
> ```

stmt.statement_fingerprint_id?.toString()
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx, line 139 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4A6VCEjTji13GQa17:-Mt4A6VCEjTji13GQa18:b6lniu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L139)):*
> ```XML
>       const stmt = statsByStatementKey[key];
>       return {
>         aggregateFingerprintID: stmt.statementFingerprintID,
> ```

nit: aggregatedFingerprintID
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 166 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4A9hT3N3Y0I [...]

2022-01-10 18:31 UTC, jocrl reviewed
@maryliag, if we have an older cluster with this UI, would it mean that the UI wouldn't work? (and is that fine?). Your changes make it so that it wouldn't give a hard error from trying to call `toString()` on `null`, but we still have a situation where `statementFingerprintID` is `null`, and it's supposed be used to identify statements in the details page, etc.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Mt4EtJj22LpNrxGKKMd:b-de7o5u)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)



<!-- Sent from Reviewable.io -->

2022-01-10 21:07 UTC, THardy98 reviewed
I hadn't considered this. I have the changes committed locally, but this raises a good point - we'll have an issue where multiple statements will match a `null` value if this field doesn't exist.

I thought that the statement fingerprint ID was provided by the backend but just not used. By that logic, we're using information that's already been provided to older clusters, which in turn should be able to support it. Or am I misunderstood and providing the statement fingerprint ID is a recent addition?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Mt4mvm2ErgsgbQVoCsE:b-qsg1t4)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)



<!-- Sent from Reviewable.io -->

2022-01-10 21:16 UTC, maryliag reviewed
@thardy98 you're correct. We were already providing the id value from the backend, I mistakenly read the code as you adding the new value also on the backend, not just on the frontend code. This means that new versions of the ui running on older cluster should work fine. 
I would still like you to add those checks just to be safe though. :) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Mt4pbPV2BPpFUA97RqS:b-po2yp8)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)



<!-- Sent from Reviewable.io -->

2022-01-10 21:21 UTC, THardy98 reviewed
@maryliag just pushed changes :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Mt4qzSB7ZSH-Dnv2qIK:bjn76li)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @Azhng, @maryliag, and @THardy98)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 55 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt48o12652xd0zL0GWq:-Mt4r4HrE4bxAxG0Dhrj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L55)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

stmt.statement_fingerprint_id?.toString()
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 117 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt48ykH3j1OSLebPL0X:-Mt4r7x8DlaUJ02cmADv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L117)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

stmt.statement_fingerprint_id?.toString()
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.selectors.ts, line 177 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt498t2Boo2ih1CplIl:-Mt4rA9SAWDFbTBRgDWh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.selectors.ts#L177)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

stmt.statement_fingerprint_id?.toString()
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.selectors.ts, line 194 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4AHVd1u6jO71wflMd:-Mt4rAsrC7JX-MXDuOTa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.selectors.ts#L194)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: aggregatedFingerprintID
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx, line 206 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4AJ0V0T6aHlodmiuJ:-Mt4rCD00a2QvN7ncVVS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx#L206)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: aggregatedFingerprintID
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 103 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49HJHELwaa4aY8lOh:-Mt4rDl2C72YmZymgudY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L103)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

stmt.statement_fingerprint_id?.toString()

nit: aggregatedFingerprintID
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts, line 262 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49Nja4J6hWIBGvj2v:-Mt4rF399urw4WFKgfpc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts#L262)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

stmt.statement_fingerprint_id?.toString()
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 83 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49TAnA7UuGDZrZmg8:-Mt4rFu38GT42Fzj6FtO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L83)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

stmt.statement_fingerprint_id?.toString()
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 100 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4A3al2NcwA5SjGmQw:-Mt4rHM90m0AZw8FpVlA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L100)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: aggregatedFingerprintID
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 145 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49V-H2WP6jFeq-viA:-Mt4rIRF96sNZs5bc87X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L145)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

stmt.statement_fingerprint_id?.toString()
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx, line 122 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49XcL3N5NmaSpZt3i:-Mt4rJbf0SvHlMpzpuJ7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L122)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

stmt.statement_fingerprint_id?.toString()
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx, line 139 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4A6VCEjTji13GQa17:-Mt4rK484VBHwo-STQsB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L139)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: aggregatedFingerprintID
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts, line 166 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt4A9hT3N3Y0I-Lfg39:-Mt4rLZw5NUNavlZl87Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts#L166)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: aggregatedFingerprintID
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts, line 289 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-Mt49dLO6Wf7Mz_dnjqF:-Mt4rMxe4MDN5uoJm-t3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8467a6965a9ee5418e6a0f99acf7f9a5d1168e/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts#L289)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: aggregatedFingerprintID
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-10 21:26 UTC, maryliag approved these changes
awesome! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :rocket: 

> Reviewed 10 of 10 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73853#-:-Mt4sVzo0yci-5HYib2f:bufnoql)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @THardy98)



<!-- Sent from Reviewable.io -->

2022-01-10 23:13 UTC, THardy98 commented
bors r+

2022-01-10 23:52 UTC, merged

2022-01-11 14:31 UTC, THardy98 commented
blathers backport 21.2