kvserver: lease transfer in JOINT configuration
cockroachdb/cockroach pull request #74077
Opened 2021-12-20 06:32 UTC by shralex

Previously:
1. Removing a leaseholder was not allowed.
2. A VOTER_INCOMING node wasn't able to accept the lease.

Because of (1), users needed to transfer the lease before removing
the leaseholder. Because of (2), when relocating a range from the
leaseholder A to a new node B, there was no possibility to transfer
the lease to B before it was fully added as VOTER. Adding it as a
voter, however, could degrade fault tolerance. For example, if A
and B are in region R1, C in region R2 and D in R3, and we had
(a, C, D), and now adding B to the cluster to replace A results in
the intermediate configuration (A, B, C, D) the failure of R1 would
make the cluster unavailable since no quorum can be established.
Since B can't be added before A is removed, the system would
transfer the lease out to C, remove A and add B, and then transfer
the lease again to B. This resulted a temporary migration of leases
out of their preferred region, imbalance of lease count and degraded
performance.

The PR fixes this, by (1) allowing removing the leaseholder, and
transferring the lease right before we exit the JOINT config. And (2),
allowing a VOTER_INCOMING to accept the lease.

Release note: None

Release note (<category, see below>): <what> <show> <why>

2021-12-20 06:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74077)
<!-- Reviewable:end -->

2021-12-20 20:44 UTC, nvanbenschoten reviewed
It's exciting to see this! When you get a chance, let's try out the repro steps from https://github.com/cockroachdb/cockroach/issues/67740#issuecomment-896480919 and see how things behave with this change.

@tbg should probably also give this a pass when it gets closer, as he was the author of a lot of this joint configuration code. I also left a comment for him in `replica_raft.go`.

> Reviewed 15 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-:-MrO_BL_0yjSbNwAOSmh:b-4p84sc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @shralex)

___
*[-- commits, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOQR6C8jfPmyrLupc4):*
nit: `s/a/A/`
___
*[-- commits, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOQc-B0u-kdrleS77y):*
Consider adding a release note to this commit. It's a valuable change that users will care about!
___
*[pkg/kv/db.go, line 629 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOQlMSCLw3mwEI6AAw:-MrOQlMSCLw3mwEI6AAx:b-599ny0) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/db.go#L629)):*
> ```Go
> 	err := db.Run(ctx, b)
> 	if err == nil {
> 		log.Infof(ctx, "Transferring lease to StoreID %s succeeded", target.String())
> ```

Was this just added for debugging purposes, or did you intend for us to keep it?
___
*[pkg/kv/kvserver/replica_command.go, line 985 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOQyCH5eaFO6hYqim7:-MrOQyCH5eaFO6hYqim8:b6j7c46) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L985)):*
> ```Go
> 	details string,
> 	chgs roachpb.ReplicationChanges,
> 	repl *Replica,
> ```

Isn't this already the method receiver?
___
*[pkg/kv/kvserver/replica_command.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOR2oI7D0mZO36MF5R:-MrOR2oJ49I22uqpCHQc:b-gbrvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1172)):*
> ```Go
> // NON_VOTER, and VOTER_FULL only.
> func maybeLeaveAtomicChangeReplicas(
> 	ctx context.Context, s *Store, desc *roachpb.RangeDescriptor, r *Replica,
> ```

Instead of adding this as a parameter, what do you think about making `maybeLeaveAtomicChangeReplicas` and `maybeLeaveAtomicChangeReplicasAndRemoveLearners` methods on `*Replica`? That way, we can actually get rid of all arguments except for the context.
___
*[pkg/kv/kvserver/replica_command.go, line 1177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrORHRTDlyTpOVpD6Q4:-MrORHRTDlyTpOVpD6Q5:bdhyqno) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1177)):*
> ```Go
> 	// with leaving a joint state when it's in one, so make sure we don't call
> 	// it if we're not.
> 	if !desc.Replicas().InAtomicReplicationChange(){
> ```

It looks like your gofmt is having issues. You should double-check that you have https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks#Enable-crlfmt-Watcher set up correctly.
___
*[pkg/kv/kvserver/replica_command.go, line 1184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrORZYX2GkMiRaNOrJr:-MrORZYX2GkMiRaNOrJs:b-2683cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1184)):*
> ```Go
> 
> 	voters := desc.Replicas().VoterDescriptors()
> 	if r != nil {
> ```

The fact that we can ignore this check seems like a source of bugs. The need for this is coming from the call to `maybeLeaveAtomicChangeReplicasAndRemoveLearners` on the RHS range in `mergeQueue.process`, right? Did you run into issues with the proposed idea to remove that call entirely and enter the `AdminRelocateRange` branch when the RHS is in a joint config instead?
___
*[pkg/kv/kvserver/replica_command.go, line 1185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOSGVuCDEC6Kj_vRZA:-MrOSGVuCDEC6Kj_vRZB:b-8odmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1185)):*
> ```Go
> 	voters := desc.Replicas().VoterDescriptors()
> 	if r != nil {
> 		// Current leaseholder is being removed
> ```

Let's add more to this comment. We can discuss why we're looking in the `voters` slice, what it means for the current replica (which we know to be the leaseholder) to be absent from it, and what we will do in that case (transfer the lease).
___
*[pkg/kv/kvserver/replica_command.go, line 1203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOTJA74oPUe6-Wv2IW:-MrOTJA74oPUe6-Wv2IX:b-kcyybm) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1203)):*
> ```Go
> 				transferLeaseOptions{
> 					goal:                               followTheWorkload,
> 					checkTransferLeaseSource:           true,
> ```

Consider adding a comment about why we set this to `true`. Something about having already filtered out the current leaseholder.
___
*[pkg/kv/kvserver/replica_command.go, line 1205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOUi1M7-6gn1-duC_W:-MrOUi1M7-6gn1-duC_X:b-alzrqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1205)):*
> ```Go
> 					checkTransferLeaseSource:           true,
> 					checkCandidateFullness:             false,
> 					disableLeaseCountConvergenceChecks: true,
> ```

Could you add a comment about why we set this? I don't understand the full flow in `Allocator.TransferLeaseTarget`, but it's interesting to me that we have to set this here, but not elsewhere. For instance, we don't disable the lease count convergence checks in `replicateQueue.maybeTransferLeaseAway`. Should we be doing so? @aayushshah15 do you know what this is about?
___
*[pkg/kv/kvserver/replica_command.go, line 1211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOSYuZDYVXAmDD0ZgN:-MrOSYuZDYVXAmDD0ZgO:b-sv8xqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1211)):*
> ```Go
> 			if target == (roachpb.ReplicaDescriptor{}) {
> 				log.Infof(ctx, "could not find a better lease transfer target for r%d",
> 					desc.RangeID)
> ```

Should we return an error in this case? If the lease can't be transferred away from the current leaseholder, then there's no use trying to perform the config change which we know is going to fail.

Also, regardless of whether we log (`log.Warningf`) or return an error, let's add more information about why we're trying to transfer the lease and what the fact that we can't find a target means. It's not a good situation, and we will want to be alerted of it if a customer cluster ever gets stuck in this state.
___
*[pkg/kv/kvserver/replica_command.go, line 1213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOVac_BJNbHk0z79R5:-MrOVac_BJNbHk0z79R6:b243agd) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1213)):*
> ```Go
> 					desc.RangeID)
> 			} else {
> 				log.Infof(ctx, "current leaseholder %v is being removed. Transferring lease to %v",
> ```

minor nit: `s/. T/, t/`

Also, `s/is being removed/is being removed through an atomic replication change/`
___
*[pkg/kv/kvserver/replica_command.go, line 2787 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOW4S-6YDMrP_vBSjw:-MrOW4S-6YDMrP_vBSjx:b2uud8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5 [...]

2021-12-21 02:42 UTC, nvanbenschoten commented
I remembered another comment I meant to leave here. We'll need to think about mixed version clusters when making this change. We shouldn't begin a joint configuration that would require the removal of the leaseholder until after all nodes in the cluster are running v22.1.

2021-12-21 10:33 UTC, tbg reviewed
Gave a shallow pass, generally looks good. Sad that all the messy lease stuff is now intertwining with the replication changes but I suppose that's what we signed up for. Still, if there's a way to clean that up I would be in favor of that. Maybe all of the lease handling doesn't have to be inline but can be pulled out into something compact that we can call in the right place.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-:-MrRY6GP3-pd-CsiCw_d:b51g447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @shralex)

___
*[pkg/kv/db.go, line 629 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOQlMSCLw3mwEI6AAw:-MrRT9cg7tdHom_FqWkQ:b-vbb51u) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/db.go#L629)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Was this just added for debugging purposes, or did you intend for us to keep it?
</blockquote></details>

These should go away, we shouldn't be logging in `*kv.DB`. If anything, these logs would be expected at the server that executes the actual transfer.

Also, general nits: 
- log messages start lowercase
- don't need to call `target.String`, just `target` should do fine (`%s` verb invokes `String()`)
- we usually refer to stores as `s%d` in logging
___
*[pkg/kv/kvserver/allocator.go, line 1381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrRTg5GDZ4EFXjymyEV:-MrRTg5GDZ4EFXjymyEW:b-uob3cr) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/allocator.go#L1381)):*
> ```Go
> 				fallthrough
> 			case decideWithoutStats:
> 				if !opts.disableLeaseCountConvergenceChecks &&
> ```

was this just missing & you noticed while writing this PR?
___
*[pkg/kv/kvserver/replica_command.go, line 1218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrRUglh5fXn4ANJ4ap0:-MrRUglh5fXn4ANJ4ap1:b-kdd2ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1218)):*
> ```Go
> 				if err != nil {
> 					return nil, err
> 				}
> ```

Are we sure the lease is now where it should be? There's obviously the case where for some reason the lease gets transferred somewhere else by a third party. Could there be races with lease preferences where the new leaseholder immediately sends the lease back, and we never manage to do the replication change below? Similarly, are there persistent error cases where the lease transfer (or one of the steps above) fail? I assume there are no new concerns here since we were never previously able to remove the leaseholder and so nothing has really changed. But I am vaguely worried that what we do now isn't 100% equivalent and that we need a fail-safe (which the migration forces us to have anyway).
___
*[pkg/kv/kvserver/replica_raft.go, line 302 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOWOsj0CHwSMY3P_lm:-MrRX3J21BxyFkBrxkDP:b-u2c98h) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_raft.go#L302)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider pulling this into a separate commit/PR, separate from the rest of the behavior changes. This shouldn't have any visible effect, but it would be nice to validate that. A separate commit also has the benefit of being "bisectable" in case there's any rare fallout that we need to track back to this change.

Ideally, we could even test this by manually issuing each step of the joint config process (enter joint, transfer lease, exit joint), but it doesn't look like we have any testing that invokes `execChangeReplicasTxn` directly. @tbg are you aware of any tests at this level?

EDIT: maybe we can do something around `TestLeaseHolderRemoveSelf` to test this?
</blockquote></details>

I don't think there's direct testing of this, unfortunately. Perhaps a reasonable way to get what we want is by inserting testing knobs between the steps that we can use to check on the replication change at various stages.
___
*[pkg/kv/kvserver/replica_raft.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrRWmDfANHJKCeuUXss:-MrRWmDfANHJKCeuUXst:b-7pmene) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_raft.go#L323)):*
> ```Go
> 		// and then transfer lease directly to v4, but this would change the number of replicas to 4,
> 		// and if region1 goes down, we loose a quorum. Instead, we move to a joint config where v1
> 		// (VOTER_DEMOTED_LEARNER) transfer the lease to v4 (VOTER_INCOMING) directly.
> ```

DEMOTING
___
*[pkg/kv/kvserver/replicate_queue.go, line 1288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOTdCyCtGbDOmpWAZh:-MrRXMbtCk3BloCO37XC:b-e524y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replicate_queue.go#L1288)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: missing punctuation.
</blockquote></details>

capitalization too and usually (though redundantly) the comment would say

// disableLeaseCountConvergenceChecks, when true, ...
___
*[pkg/kv/kvserver/client_raft_test.go, line 3826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrRXh3k6R82tb9i23Po:-MrRXh3k6R82tb9i23Pp:b3kqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/client_raft_test.go#L3826)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	// Check that lease moved to server 2
> ```

.


<!-- Sent from Reviewable.io -->

2021-12-21 17:13 UTC, aayushshah15 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @shralex)

___
*[pkg/kv/kvserver/replica_command.go, line 1205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOUi1M7-6gn1-duC_W:-MrSqXiV-78h1UMq9Xm-:b-o98rx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1205)):*
> For instance, we don't disable the lease count convergence checks in replicateQueue.maybeTransferLeaseAway

I dont fully follow why we need this new option. `disableLeaseCountConvergenceChecks` as its currently written makes it such that we're forced to use `followTheWorkload` or return an empty result.
___
*[pkg/kv/kvserver/replica_command.go, line 1211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOSYuZDYVXAmDD0ZgN:-MrSseT7AEevTx3qwpVi:b-3yxk52) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1211)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we return an error in this case? If the lease can't be transferred away from the current leaseholder, then there's no use trying to perform the config change which we know is going to fail.

Also, regardless of whether we log (`log.Warningf`) or return an error, let's add more information about why we're trying to transfer the lease and what the fact that we can't find a target means. It's not a good situation, and we will want to be alerted of it if a customer cluster ever gets stuck in this state.
</blockquote></details>

+1 I'm not sure we need to call into `TransferLeaseTarget` at all here. Zone configuration lease preferences must be compatible with the constraints placed on the range. So we should never be trying to replace the current leaseholder with another replica that is in violation of those lease preferences. Given all this, I think we should be able to directly transfer the lease to the `VOTER_INCOMING` that is replacing the current leaseholder. 

Another thing to note is that part of `AdminRelocateRange`'s contract is that it must transfer the lease to the first voting replica in the input slice. This is done here at the end: https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L2791-L2802 This further confuses this call into `TransferLeaseTarget` for me.
___
*[pkg/kv/kvserver/replica_command.go, line 2795 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrN8fiX6rcuiwFq-ngl:-MrN8fiX6rcuiwFq-ngm:bn5kb29) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L2795)):*
> ```Go
> 					// NB: we may need to transfer even if there are no ops, to make
> 					// sure the attempt is made to make the first target the final
> 					// leaseholder. If there are ops, lease transfer will happen during joint config exit,
> ```

nit: this addition is a bit out of place here, and wrapping.
___
*[pkg/kv/kvserver/replica_command.go, line 2796 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrSy-I7DLMUPyr_AIrb:-MrSy-I7DLMUPyr_AIrc:bpiad61) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L2796)):*
> ```Go
> 					// sure the attempt is made to make the first target the final
> 					// leaseholder. If there are ops, lease transfer will happen during joint config exit,
> 					// if leader is removed.
> ```

`s/leader/leaseholder`
___
*[pkg/kv/kvserver/replica_raft.go, line 302 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrSum_4ExXFAvGQVucD:-MrSum_4ExXFAvGQVucE:bglinbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_raft.go#L302)):*
> ```Go
> 		prefix = false
> 
> 		// The following deals with removing a leaseholder. A voter can be removed in two ways.
> ```

note that comments should be wrapped at 80 chars (see: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Line-Length) here and elsewhere.


<!-- Sent from Reviewable.io -->

2021-12-21 17:18 UTC, aayushshah15 commented
>We'll need to think about mixed version clusters when making this change. We shouldn't begin a joint configuration that would require the removal of the leaseholder until after all nodes in the cluster are running v22.1.

To add to this, we will also still need the removed allocator logic under mixed-version states.

2021-12-21 17:20 UTC, aayushshah15 commented
___
*[pkg/kv/kvserver/replicate_queue.go, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrT-P267QyAuST8z5cY:-MrT-P267QyAuST8z5cZ:b-54d89g) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replicate_queue.go#L543)):*
> ```Go
> 		// See about transferring the lease away if we're about to remove the
> 		// leaseholder.
> 		done, err := rq.maybeTransferLeaseAway(
> ```

This call should also probably go away. 


<!-- Sent from Reviewable.io -->

2022-01-05 01:24 UTC, shralex reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[-- commits, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOQc-B0u-kdrleS77y):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider adding a release note to this commit. It's a valuable change that users will care about!
</blockquote></details>

Sure, I'll add before this is merged, once we converge.
___
*[pkg/kv/kvserver/allocator.go, line 1381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrRTg5GDZ4EFXjymyEV:-MrY5rJ01PLzkRjAVGhj:byl2fq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/allocator.go#L1381)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

was this just missing & you noticed while writing this PR?
</blockquote></details>

I reverted this change, as the same can be achieved by setting checkTransferLeaseSource to false 
___
*[pkg/kv/kvserver/replica_command.go, line 1177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrORHRTDlyTpOVpD6Q4:-MrYAb1f6fX3xW6_E4V-:bpgoqho) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1177)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It looks like your gofmt is having issues. You should double-check that you have https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks#Enable-crlfmt-Watcher set up correctly.
</blockquote></details>

thanks! I set it up previously but it somehow disappeared...
___
*[pkg/kv/kvserver/replica_command.go, line 1203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOTJA74oPUe6-Wv2IW:-MrYOf198FiaPTj52030:be1tdke) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1203)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider adding a comment about why we set this to `true`. Something about having already filtered out the current leaseholder.
</blockquote></details>

actually I think it should be false because of the lease count checks in the TransferLeaseTarget method
___
*[pkg/kv/kvserver/replica_command.go, line 1205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOUi1M7-6gn1-duC_W:-MrYOr-v-NQbFq9vaKpt:b-afurhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1205)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

> For instance, we don't disable the lease count convergence checks in replicateQueue.maybeTransferLeaseAway

I dont fully follow why we need this new option. `disableLeaseCountConvergenceChecks` as its currently written makes it such that we're forced to use `followTheWorkload` or return an empty result.
</blockquote></details>

What I was observing is that when the lease counts are roughly similar, this method would return an empty result. I now removed this new option, since checkTransferLeaseSource=false would achieve what I needed here. 
___
*[pkg/kv/kvserver/replica_command.go, line 1211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOSYuZDYVXAmDD0ZgN:-MrYPgGtDm15koG169Cc:bbwx6vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1211)):*
Updated this to return an error.

>  I think we should be able to directly transfer the lease to the VOTER_INCOMING that is replacing the current leaseholder

It might be better to make this code a bit more general, such that it works even if there are multiple incoming nodes, or none. Also, there are cases where the joining node is not the best choice. Running the selection logic addresses both issues.
___
*[pkg/kv/kvserver/client_lease_test.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOZ1kB8eXSJ_ujs00z:-MrZQ9ul1SFRRpwD92yt:b-upia8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/client_lease_test.go#L654)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Without this, the liveness status of candidate nodes is unknown, and they are excluded from consideration when we're trying to decide where to transfer the lease.


<!-- Sent from Reviewable.io -->

2022-01-29 01:57 UTC, shralex reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/testutils/testcluster/testcluster.go, line 897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOYm0S8NyR62gmipK-:-MuYWRdU9O2RJU2qvqyu:bqgsj35) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/testutils/testcluster/testcluster.go#L897)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm surprised this works. Are we entering a joint config here?
</blockquote></details>

Yes. When removing a full voter, we’ll always demote it rather than removing, which will cause this to go through a joint config. When this is applied to the leaseholder, we now allow this demotion, and right before exiting the joint config move the lease somewhere else.


<!-- Sent from Reviewable.io -->

2022-01-29 08:04 UTC, shralex reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOR2oI7D0mZO36MF5R:-MuZo0SRB0p7KH0KJCyZ:by5b7tv) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1172)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of adding this as a parameter, what do you think about making `maybeLeaveAtomicChangeReplicas` and `maybeLeaveAtomicChangeReplicasAndRemoveLearners` methods on `*Replica`? That way, we can actually get rid of all arguments except for the context.
</blockquote></details>

Done. However, leaving the descriptor as a parameter for now because its not immediately clear that it's always derived from the replica.
___
*[pkg/kv/kvserver/replica_command.go, line 1184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrORZYX2GkMiRaNOrJr:-MuZnsWiDcEbGlbC6zw6:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1184)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The fact that we can ignore this check seems like a source of bugs. The need for this is coming from the call to `maybeLeaveAtomicChangeReplicasAndRemoveLearners` on the RHS range in `mergeQueue.process`, right? Did you run into issues with the proposed idea to remove that call entirely and enter the `AdminRelocateRange` branch when the RHS is in a joint config instead?
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/replica_raft.go, line 302 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrSum_4ExXFAvGQVucD:-MuYiYSV3RV2ruZbkLlw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_raft.go#L302)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

note that comments should be wrapped at 80 chars (see: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Line-Length) here and elsewhere.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replicate_queue.go, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrT-P267QyAuST8z5cY:-MuYhMf_6to1ah5z7jv9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replicate_queue.go#L543)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

This call should also probably go away. 
</blockquote></details>

Done.



_Code quote:_
```Go
rq.maybeTransferLeaseAway(
```


<!-- Sent from Reviewable.io -->

2022-01-31 15:21 UTC, nvanbenschoten reviewed
> To add to this, we will also still need the removed allocator logic under mixed-version states.

This is a good point. We'll need to do this in the first PR or it will immediately break nightly CI.

> Reviewed 1 of 10 files at r2, 10 of 15 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-:-MukiOl555-6a1cUiwCW:b6n07m6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/merge_queue.go, line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-Mukd_zR6Y1YdbYFhQ6D:-Mukd_zR6Y1YdbYFhQ6E:b6i3i2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ffb8b24fd8c0d60a92957105afc4d394d809fa1/pkg/kv/kvserver/merge_queue.go#L267)):*
> ```Go
> 		mergedQPS = lhsQPS + rhsQPS
> 	}
> ```

nit: stray diff
___
*[pkg/kv/kvserver/merge_queue.go, line 312 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MukdGjYCwFyKJz2wk8-:-MukdGjYCwFyKJz2wk80:bvcbci9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7620a3bf918c14fb3c7ea0704520981c89565f06/pkg/kv/kvserver/merge_queue.go#L312)):*
> ```Go
> 	// and types of the replicas (voting or non-voting) do not matter.
> 	if !replicasCollocated(leftRepls, rightRepls) ||
> 		rhsDesc.Replicas().InAtomicReplicationChange() {
> ```

Could we add to this comment to explain why we are performing this relocation?
___
*[pkg/kv/kvserver/merge_queue.go, line 341 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MukdMfvDLfa4XBoDnQo:-MukdMfvDLfa4XBoDnQp:b-cpx2k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7620a3bf918c14fb3c7ea0704520981c89565f06/pkg/kv/kvserver/merge_queue.go#L341)):*
> ```Go
> 		}
> 	}
> 	// Refresh RHS descriptor
> ```

Should this be inside the previous branch? Do we need to refresh the descriptor if we haven't relocated the range?

Also, nit, but punctuation.
___
*[pkg/kv/kvserver/replica_command.go, line 1218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrRUglh5fXn4ANJ4ap0:-MukfXT8-9UHGCsW_Rsg:b-p3inmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1218)):*
> Could there be races with lease preferences where the new leaseholder immediately sends the lease back, and we never manage to do the replication change below? 

I think the way this should work is that lease transfers to a voter in the process of being removed (`VOTER_DEMOTING` or `VOTER_OUTGOING`) should be disallowed, so once we move the lease away, nothing should be able to move it back.
___
*[pkg/kv/kvserver/replica_command.go, line 1041 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-Mukdmbf2K5Kfq_6DsB2:-Mukdmbf2K5Kfq_6DsB3:b44vtyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7620a3bf918c14fb3c7ea0704520981c89565f06/pkg/kv/kvserver/replica_command.go#L1041)):*
> ```Go
> 
> 	// Before we initialize learners, check that we're not removing the leaseholder.
> 	// Or if we are, ensure that leaseholder is collocated with the Raft leader.
> ```

Could we also explain why we have this limitation?
___
*[pkg/kv/kvserver/replica_command.go, line 1046 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-Mukdrch0Vr8GE1kS1Mg:-Mukdrch0Vr8GE1kS1Mh:byb43te) ([raw file](https://github.com/cockroachdb/cockroach/blob/7620a3bf918c14fb3c7ea0704520981c89565f06/pkg/kv/kvserver/replica_command.go#L1046)):*
> ```Go
> 			raftStatus := r.RaftStatus()
> 			if raftStatus == nil || len(raftStatus.Progress) == 0 {
> 				log.VEventf(ctx,5, "Removing leaseholder not allowed since it isn't the Raft leader.")
> ```

nit: a common pattern we have is to create an error, log it, then return it. That avoids the duplication. So something like:
```go
err := ...
log.VErrEventf(ctx, 2, "%s", err)
return nil, err
```

nit: we tend not to capitalize or punctuate logs messages or error messages

nit: did `gofmt` run on this?
___
*[pkg/kv/kvserver/replica_command.go, line 1198 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-Mukezeh99WWbIpqpvLo:-Mukezeh99WWbIpqpvLp:bmhpr5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7620a3bf918c14fb3c7ea0704520981c89565f06/pkg/kv/kvserver/replica_command.go#L1198)):*
> ```Go
> 
> 	// Determine whether the current leaseholder is being removed. voters includes
> 	// the set of full or incoming voters, and if we don't find the current leaseholder there
> ```

"full or incoming voters that will remain after the joint configuration is complete"
___
*[pkg/kv/kvserver/replica_command.go, line 1224 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MukfGHu1bJL3J7oM5iB:-MukfGHu1bJL3J7oM5iC:b-1mbd0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7620a3bf918c14fb3c7ea0704520981c89565f06/pkg/kv/kvserver/replica_command.go#L1224)):*
> ```Go
> 		)
> 		if target == (roachpb.ReplicaDescriptor{}) {
> 			log.VEventf(ctx, 5,"could not find a better lease transfer target for r%d", desc.RangeID)
> ```

nit: same comment about creating an error, logging it, then returning it.
___
*[pkg/kv/kvserver/replica_command.go, line 3008 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MukgEF_4lsdtp-I9pNt:-MukgEF_4lsdtp-I9pNu:b-8g5o5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ffb8b24fd8c0d60a92957105afc4d394d809fa1/pkg/kv/kvserver/replica_command.go#L3008)):*
> ```Go
> 				}
> 			}
> 			if !shouldRemove {
> ```

Is the removal of this logic dependent on any `AdminChangeReplicas` attempt which removes the leaseholder transferring the lease to _some_ other replica? That is now the case for joint configurations, but what about for simple config changes. For instance, will this work with a range that looks like `{1L, 2, 3, 4}` and wants to be changed to `{2L, 3, 4}`?
___
*[pkg/kv/kvserver/replicate_queue.go, line 17 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MukgfetAJtPBIMqlVAM:-MukgfetAJtPBIMqlVAN:b-un31ok) ([raw file](https://github.com/cockroachdb/cockroach/blob/7620a3bf918c14fb3c7ea0704520981c89565f06/pkg/kv/kvserver/replicate_queue.go#L17)):*
> ```Go
> 	"context"
> 	"fmt"
> 	"go.etcd.io/etcd/raft/v3"
> ```

nit: I don't think this meant to move.
___
*[pkg/testutils/testcluster/testcluster.go, line 897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOYm0S8NyR62gmipK-:-Mukh4Vh83EWMYiHGNAM:bsg7g3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/testutils/testcluster/testcluster.go#L897)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Yes. When removing a full voter, we’ll always demote it rather than removing, which will cause this to go through a joint config. When this is applied to the leaseholder, we now allow this demotion, and right before exiting the joint config move the lease somewhere else.
</blockquote></details>

Interesting, so VOTER->LEARNER demotions always go through a joint config? Maybe this answers my question about above simple (single-step, single change) config changes that remove the leaseholder. Do we not need to handle those because they don't exist?
___
*[pkg/kv/kvserver/client_lease_test.go, line 640 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOYxxf9m0GP7s5YoJO:-MukhLIs30sYVQnCN5Ww:btbg5g6) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/client_lease_test.go#L640)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: punctuation needed at the end of a lot of these comments.
</blockquote></details>

`s/,/./` :smiley: 
___
*[pkg/kv/kvserver/client_lease_test.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOZ1kB8eXSJ_ujs00z:-Mukhgkg8LuSlFrB9oX6:bgbi3h6) ([raw file](https://github.com/cockroachd [...]

2022-02-01 17:56 UTC, shralex reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 2796 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrSy-I7DLMUPyr_AIrb:-MuqORSd0DTbH5Cmjfn4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L2796)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

`s/leader/leaseholder`
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_command.go, line 3008 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MukgEF_4lsdtp-I9pNt:-MuqOaSZ6HHvCOfrsWLG:bucp2it) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ffb8b24fd8c0d60a92957105afc4d394d809fa1/pkg/kv/kvserver/replica_command.go#L3008)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the removal of this logic dependent on any `AdminChangeReplicas` attempt which removes the leaseholder transferring the lease to _some_ other replica? That is now the case for joint configurations, but what about for simple config changes. For instance, will this work with a range that looks like `{1L, 2, 3, 4}` and wants to be changed to `{2L, 3, 4}`?
</blockquote></details>

My understanding is that any voter demotion, including leader removal, will go through a joint configuration. See prepareChangeReplicasTrigger in replica_command.go
___
*[pkg/kv/kvserver/client_lease_test.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOZ1kB8eXSJ_ujs00z:-MuqQB759oL2qCkJmUM9:b-54hrlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/client_lease_test.go#L654)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm surprised that other tests don't run into this problem. Does the test reliably fail if you remove it, or does it just become flaky?
</blockquote></details>

This is done for other tests as well. See for example "// Gossip and heartbeat all the live stores, we do this manually otherwise the
		// allocator on server 0 may see everyone as temporarily dead due to the
		// clock move above."
___
*[pkg/kv/kvserver/client_lease_test.go, line 657 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOZBp68xiJvH5IWZMD:-MuqQW-OA6NepO6pRVnv:b-cbr7um) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/client_lease_test.go#L657)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did we consider making this change? I don't think we want to go through SQL here if we can avoid it. Better to issue an `AdminChangeReplicas` directly if possible.
</blockquote></details>

I changed it for the new tests I added in this file.


<!-- Sent from Reviewable.io -->

2022-02-02 16:32 UTC, nvanbenschoten reviewed
> Reviewed 3 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/merge_queue.go, line 288 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MuvEqVd0zk-N8Ql4rVB:-MuvEqVd0zk-N8Ql4rVC:b-rmokoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eebafa80a0579b166b006dcde55e6d6760ca5a0/pkg/kv/kvserver/merge_queue.go#L288)):*
> ```Go
> 		// For the sake of obviousness, just fix this all upfront. The merge is
> 		// performed by the LHS leaseholder, so it can easily do this for LHS.
> 		// We deal with the RHS further down.
> ```

"We deal with the RHS, whose leaseholder may be remote, further down."
___
*[pkg/kv/kvserver/replica_command.go, line 311 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MuvEyNfCD7uFvONhZ4n:-MuvEyNfCD7uFvONhZ4o:b-46mpd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eebafa80a0579b166b006dcde55e6d6760ca5a0/pkg/kv/kvserver/replica_command.go#L311)):*
> ```Go
> 	}
> 
> 	// As a result of exiting the joint config, we might no longer be the leaseholder
> ```

Did you mean to remove these commented-out blocks? I suspect that this had to do with the question of whether to bail on exiting the joint config on the outgoing leaseholder or not. Did we decide on what we want to do there?

We've talked a bit about "reactivity" to this lease transfer. If we don't continue with the joint config on the outgoing leaseholder then we'd like for the incoming leaseholder to quickly take over and carry the mantle forward without much delay. I took a look and think that this should be handled by this code:
https://github.com/cockroachdb/cockroach/blob/39ca6aca0806fa1dc1e846c7014799fb71621587/pkg/kv/kvserver/replica_raft.go#L875-L880

The lease transfer will be quickly followed by a transfer of raft leadership. This code ensures that when a replica assumes the role of raft leader, it immediately checks for whether it should perform any config changes. This should notice the joint config and complete it.

If we can confirm this then I think we'll be good with bailing on the outgoing leaseholder.


<!-- Sent from Reviewable.io -->

2022-02-14 17:46 UTC, aayushshah15 requested changes
Its getting closer!

We still seem to be missing mixed version logic at the `replicateQueue` level -- that is, under mixed version states we still need the `replicateQueue` to do the whole `maybeTransferLeaseAway` dance when it's trying to remove/rebalance the current leaseholder. 

> Reviewed 1 of 17 files at r1, 1 of 15 files at r3, 1 of 16 files at r8, 8 of 18 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-:-MvtJvEgAwA8KQMoCW7b:bgnfm0f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[-- commits, line 27 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqdgW40tqVKkAePLNP):*
This release note is a bit technical and won't be useful for end users. Let's instead say something about the user-facing aspect of this patch. Something along the lines of "Fixes a limitation which meant that, upon adding a new node to the cluster,  lease counts among existing nodes could diverge until the new node was fully upreplicated".
___
*[pkg/kv/kvserver/markers.go, line 83 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvpjYte4rhtCJcKagHK:-MvpjYte4rhtCJcKagHL:biivlzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/markers.go#L83)):*
> ```Go
> 
> var errLeaseholderNotRaftLeader = errors.New(
> 	"Removing leaseholder not allowed since it isn't the Raft leader")
> ```

error messages must all be lower case for consistency 
___
*[pkg/kv/kvserver/replica_command.go, line 1211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOSYuZDYVXAmDD0ZgN:-MvqSSGz07gdhsT97IZt:bhs7aak) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1211)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Updated this to return an error.

>  I think we should be able to directly transfer the lease to the VOTER_INCOMING that is replacing the current leaseholder

It might be better to make this code a bit more general, such that it works even if there are multiple incoming nodes, or none. Also, there are cases where the joining node is not the best choice. Running the selection logic addresses both issues.
</blockquote></details>

Do we understand the case(s) where `TransferLeaseTarget` would ever return an empty target when `checkTransferLeaseSource = false`? If it is somehow possible for `TransferLeaseTarget` to produce an empty target, then that seems like something we need to address because as Nathan was saying above, this means that the range would potentially never be able to get out of its joint state. We should have a `log.Fatal()` if this returns an empty target.

It looks like `TransferLeaseTarget` could return an empty target if all the other replicas of the range are on `suspect` or `draining` stores. The `suspect` state shouldn't be permanent (though it could last for a while), and the `draining` state is essentially permanent unless the node is restarted. We could perhaps fix this by having the caller ask `TransferLeaseTarget` to consider all candidate stores (i.e. use `storeFilterNone` instead of `storeFilterSuspect`). 

Also, what do you think about lifting this call to `TransferLeaseTarget` into an appropriately named helper that has comments outlining why we need to ensure that it produces a different lease target?
___
*[pkg/kv/kvserver/replica_command.go, line 2764 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqTx2w9z0aaMdKVi5F:-MvqTx2w9z0aaMdKVi5G:bd72c9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L2764)):*
> ```Go
> 	rangeDesc = *newDesc
> 
> 	rangeDesc, err = r.store.relocateReplicas(
> ```

It is odd that `relocateReplicas` (which is a helper for `AdminRelocateRange`) has a `Store` receiver whereas `AdminRelocateRange` has a `(*Replica)` receiver. If there's no good reason for it, let's have `relocateReplicas` also be implemented by `(*Replica)` as well.
___
*[pkg/kv/kvserver/replica_command.go, line 2833 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-Mvqi8Ko9pyxOjrOIKl6:-Mvqi8Ko9pyxOjrOIKl7:bhv19f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L2833)):*
> ```Go
> 
> 			if !s.cfg.Settings.Version.IsActive(ctx,
> 				clusterversion.EnableLeaseHolderRemoval) {
> ```

The way this is currently written,  it seems like `relocateReplicas` shouldn't need to worry about mixed version states.

`relocateOne` is not going to produce a lease transfer target unless we're already in a mixed version state, so `relocateReplicas` should still behave identically to before, right?
___
*[pkg/kv/kvserver/replica_command.go, line 2877 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqIzz89kvVJBKttU29:-MvqIzz89kvVJBKttU2A:b4q4euk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L2877)):*
> ```Go
> 			if success {
> 				if fn := s.cfg.TestingKnobs.OnRelocatedOne; fn != nil {
> 					if !s.cfg.Settings.Version.IsActive(ctx,
> ```

Since this is inside a testing knob, why do we need to check the cluster version here?
___
*[pkg/kv/kvserver/replica_command.go, line 3086 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqpABL7t6AKyTQNVal:-MvqpABL7t6AKyTQNVam:bdqfs6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L3086)):*
> ```Go
> 			StoreID: targetStore.StoreID,
> 		}
> 		// We can't remove the leaseholder, which really throws a wrench into
> ```

Let's update this comment. 
___
*[pkg/kv/kvserver/replica_command.go, line 3101 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqpNgM2m9WWdAlpfUI:-MvqpNgM2m9WWdAlpfUJ:bipp5bh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L3101)):*
> ```Go
> 		shouldRemove = (curLeaseholder.StoreID != removalTarget.StoreID) ||
> 			s.cfg.Settings.Version.IsActive(ctx,
> 				clusterversion.EnableLeaseHolderRemoval)
> ```

nit: the wrapping is a little odd. Code can go up to 100chars, only comments need to be 80chars.
___
*[pkg/kv/kvserver/replicate_queue.go, line 1378 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqzY6K4Yd1S_hPVbIN:-MvqzY6K4Yd1S_hPVbIO:b54mj1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replicate_queue.go#L1378)):*
> ```Go
> 	// queue is active.
> 	if _, err := repl.changeReplicasImpl(
> 		ctx, desc, priority, reason, details, chgs); err != nil {
> ```

nit: wrapping seems odd.
___
*[pkg/sql/logictest/logic.go, line 1449 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvtIWCr905OBoq5JzWB:-MvtIWCr905OBoq5JzWC:bx62c85) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/sql/logictest/logic.go#L1449)):*
> ```Go
> 					DisableConsistencyQueue: true,
> 					AllocatorKnobs: &kvserver.AllocatorTestingKnobs{
> 						AllowLeaseTransfersToReplicasNeedingSnapshots: true,
> ```

It's unfortunate that now even SQL level tests that call into `AdminRelocateRange` have to worry about setting this subtle KV-level testing knob. @nvanbenschoten do you see any way around this?

In any case, at the very least I think we should have a clear error that's returned by `AdminRelocateRange` (or one of its callees like `AdminChangeReplicas`) that provides a helpful hint to the test writer about setting this testing knob if its not set.  


<!-- Sent from Reviewable.io -->

2022-02-14 19:39 UTC, nvanbenschoten requested changes
> Reviewed 1 of 12 files at r7, 7 of 16 files at r8, 18 of 18 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1253 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvtdUUa0-CUBfN5HOeB:-MvtdUUa0-CUBfN5HOeC:b-mjzbja) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L1253)):*
> ```Go
> 			return desc, err
> 		}
> 		log.VEventf(ctx, 5, "Leaseholder transfer to %v complete.", target)
> ```

nit: same point as elsewhere about log statements being lower-case and generally not including punctuation if they are single-sentences.
___
*[pkg/kv/kvserver/replica_command.go, line 2764 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqTx2w9z0aaMdKVi5F:-MvtdpGEEBhEV6i-fLsc:b-4izy2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L2764)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

It is odd that `relocateReplicas` (which is a helper for `AdminRelocateRange`) has a `Store` receiver whereas `AdminRelocateRange` has a `(*Replica)` receiver. If there's no good reason for it, let's have `relocateReplicas` also be implemented by `(*Replica)` as well.
</blockquote></details>

+1, Aayush's suggestion seems reasonable, given the methods in the rest of this file. I think his reasoning also extends to `relocateOne`.
___
*[pkg/kv/kvserver/replica_command.go, line 2877 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqIzz89kvVJBKttU29:-MvteDJL1hBqCgSRU-rS:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L2877)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Since this is inside a testing knob, why do we need to check the cluster version here?
</blockquote></details>

+1
___
*[pkg/kv/kvserver/replica_command.go, line 3101 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvteViQ4yRfXGsa82_m:-MvteViQ4yRfXGsa82_n:bd7vgnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L3101)):*
> ```Go
> 		shouldRemove = (curLeaseholder.StoreID != removalTarget.StoreID) ||
> 			s.cfg.Settings.Version.IsActive(ctx,
> 				clusterversion.EnableLeaseHolderRemoval)
> ```

It's somewhat disconcerting to see so many calls to `IsActive(EnableLeaseHolderRemoval)`. The cluster version state is an atomic that can be changed at any time, so each of these calls needs to be the one that's prepared to see the active status switch from `false` to `true`. Furthermore, the cluster version is monotonic on a single node, but different nodes can see this active status switch at different times. Are we confident that we're handling things correctly in each case?

As a general design principle with version upgrades like this, it's helpful to try to find a single "gate" where the version can be checked. This eliminates the number of states that the system can be in midway through a version upgrade. With this change, we may need two:
1. a best-effort, graceful one in the `replicateQueue` to decide whether to attempt a leaseholder-removing replication change or whether to use the old logic
2. a strict one in `Replica.propose` to decide whether a leaseholder can enter a joint config that removes itself. This one is currently missing.

I guess we may also need one more somewhere in `relocateReplicas` to decide whether to attempt a leaseholder-removing replication change or whether to use the old logic.
___
*[pkg/sql/logictest/logic.go, line 1449 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvtIWCr905OBoq5JzWB:-Mvth-qm-JCIeYwoepC-:b-qmonj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/sql/logictest/logic.go#L1449)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

It's unfortunate that now even SQL level tests that call into `AdminRelocateRange` have to worry about setting this subtle KV-level testing knob. @nvanbenschoten do you see any way around this?

In any case, at the very least I think we should have a clear error that's returned by `AdminRelocateRange` (or one of its callees like `AdminChangeReplicas`) that provides a helpful hint to the test writer about setting this testing knob if its not set.  
</blockquote></details>

I agree that this is unfortunate. I think we should try to understand why these calls to `AdminRelocateRange` are hitting this issue. We shouldn't be trying to promote a learner to a `voter_incoming` until after it has received a [manual snapshot](https://github.com/cockroachdb/cockroach/blob/3be8121ad9e96416c49c27947facfa18831794b9/pkg/kv/kvserver/replica_command.go#L1687). So why are we seeing followers in need of a snapshot when we get to this state? It feels like we should be able to lock this down enough to avoid the testing knob.

As a strawman that we shouldn't actually implement (because it's a bad idea for extreme cases), we should be able to place a relatively strict assertion right after the call to `sendSnapshot` in `initializeRaftLearners` that `!replicaMayNeedSnapshot(r.RaftStatus(), rDesc.ReplicaID)`.

This relates to something we discussed last week. Is the etcd/raft leader being informed about this manual learner snapshot immediately after it succeeds? Are we forgetting to tell it and relying on async probing to later realize that the learner is caught up?


<!-- Sent from Reviewable.io -->

2022-02-14 19:52 UTC, shralex reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/markers.go, line 83 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvpjYte4rhtCJcKagHK:-MvtiRsU0oGABXjugkCD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/markers.go#L83)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

error messages must all be lower case for consistency 
</blockquote></details>

Done.



_Code quote:_
```Go
Removing leaseholder not allowed since it isn't the Raft leader
```
___
*[pkg/kv/kvserver/replica_command.go, line 311 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MuvEyNfCD7uFvONhZ4n:-MvtiZb1BHk4eV62NrhR:b4x5a8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eebafa80a0579b166b006dcde55e6d6760ca5a0/pkg/kv/kvserver/replica_command.go#L311)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to remove these commented-out blocks? I suspect that this had to do with the question of whether to bail on exiting the joint config on the outgoing leaseholder or not. Did we decide on what we want to do there?

We've talked a bit about "reactivity" to this lease transfer. If we don't continue with the joint config on the outgoing leaseholder then we'd like for the incoming leaseholder to quickly take over and carry the mantle forward without much delay. I took a look and think that this should be handled by this code:
https://github.com/cockroachdb/cockroach/blob/39ca6aca0806fa1dc1e846c7014799fb71621587/pkg/kv/kvserver/replica_raft.go#L875-L880

The lease transfer will be quickly followed by a transfer of raft leadership. This code ensures that when a replica assumes the role of raft leader, it immediately checks for whether it should perform any config changes. This should notice the joint config and complete it.

If we can confirm this then I think we'll be good with bailing on the outgoing leaseholder.
</blockquote></details>

Decided to continue with the outgoing leaseholder
___
*[pkg/kv/kvserver/replica_command.go, line 2764 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqTx2w9z0aaMdKVi5F:-MvtjXTQ-WgS5GYIGntd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L2764)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

It is odd that `relocateReplicas` (which is a helper for `AdminRelocateRange`) has a `Store` receiver whereas `AdminRelocateRange` has a `(*Replica)` receiver. If there's no good reason for it, let's have `relocateReplicas` also be implemented by `(*Replica)` as well.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_command.go, line 2877 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqIzz89kvVJBKttU29:-MvtjyE29PrfmCzunYPt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L2877)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.



_Code quote:_
```Go
if fn := s.cfg.TestingKnobs.OnRelocatedOne; fn 
```
___
*[pkg/kv/kvserver/replica_command.go, line 3086 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqpABL7t6AKyTQNVal:-MvtkbAsCrHlqcucx_ex:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L3086)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Let's update this comment. 
</blockquote></details>

Done.



_Code quote:_
```Go
 We can't remove the leaseholder, which really throws a wrench into
```
___
*[pkg/sql/logictest/logic.go, line 1449 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvtIWCr905OBoq5JzWB:-MvtlKFWC4mnpmCxmEIl:b41kiro) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/sql/logictest/logic.go#L1449)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I agree that this is unfortunate. I think we should try to understand why these calls to `AdminRelocateRange` are hitting this issue. We shouldn't be trying to promote a learner to a `voter_incoming` until after it has received a [manual snapshot](https://github.com/cockroachdb/cockroach/blob/3be8121ad9e96416c49c27947facfa18831794b9/pkg/kv/kvserver/replica_command.go#L1687). So why are we seeing followers in need of a snapshot when we get to this state? It feels like we should be able to lock this down enough to avoid the testing knob.

As a strawman that we shouldn't actually implement (because it's a bad idea for extreme cases), we should be able to place a relatively strict assertion right after the call to `sendSnapshot` in `initializeRaftLearners` that `!replicaMayNeedSnapshot(r.RaftStatus(), rDesc.ReplicaID)`.

This relates to something we discussed last week. Is the etcd/raft leader being informed about this manual learner snapshot immediately after it succeeds? Are we forgetting to tell it and relying on async probing to later realize that the learner is caught up?
</blockquote></details>

I agree we should investigate and improve this, but perhaps as a follow-up patch ? since this seems like a separate (or at least separable) issue.
___
*[pkg/testutils/testcluster/testcluster.go, line 897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOYm0S8NyR62gmipK-:-MvtlrhXBYutGKTp_ISM:bkqubzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/testutils/testcluster/testcluster.go#L897)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Interesting, so VOTER->LEARNER demotions always go through a joint config? Maybe this answers my question about above simple (single-step, single change) config changes that remove the leaseholder. Do we not need to handle those because they don't exist?
</blockquote></details>

That's my understanding... Search for "// NB: demotions require joint consensus because of limitations in etcd/raft."


<!-- Sent from Reviewable.io -->

2022-02-14 20:00 UTC, nvb reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/sql/logictest/logic.go, line 1449 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvtIWCr905OBoq5JzWB:-MvtnhF-AjMhuYgUzgAQ:bmlnzs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/sql/logictest/logic.go#L1449)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

I agree we should investigate and improve this, but perhaps as a follow-up patch ? since this seems like a separate (or at least separable) issue.
</blockquote></details>

I'm usually very pro-follow-up patch, but in this case, I think the flakiness is concerning enough to try to understand now. It may hint at a race that's going to make all of this unstable in practice. For instance, if we're not accounting for the learner snapshot when determining whether the voter_incoming can become the leaseholder, we may frequently roll back the entire config change. Learning a bit more about what's going on would help de-risk this change. If it is a testing-only flake then we can save the deflaking for a follow-up patch.


<!-- Sent from Reviewable.io -->

2022-02-14 20:01 UTC, shralex reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 2764 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvqTx2w9z0aaMdKVi5F:-MvtoRJJ95ApGVuzVPsn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L2764)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/logic.go, line 1449 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvtIWCr905OBoq5JzWB:-MvtouZR94xRFm4EM4Ni:b-hfghm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/sql/logictest/logic.go#L1449)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm usually very pro-follow-up patch, but in this case, I think the flakiness is concerning enough to try to understand now. It may hint at a race that's going to make all of this unstable in practice. For instance, if we're not accounting for the learner snapshot when determining whether the voter_incoming can become the leaseholder, we may frequently roll back the entire config change. Learning a bit more about what's going on would help de-risk this change. If it is a testing-only flake then we can save the deflaking for a follow-up patch.
</blockquote></details>

Sounds good


<!-- Sent from Reviewable.io -->

2022-02-17 17:50 UTC, shralex reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/sql/logictest/logic.go, line 1449 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvtIWCr905OBoq5JzWB:-Mw7mwRSDsjRG4oNi6r6:b-9za7oj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/sql/logictest/logic.go#L1449)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Sounds good
</blockquote></details>

Raft progress, which we use to determine whether the replica may need a snapshot, is managed by Raft, which expects one more log update after the snapshot before marking progress as "replicating". Discussed this with @tbg and we decided to go with a simpler solution - to consider any replica in the VOTER_INCOMING state as one that we shouldn't filter out based on "may need a snapshot", since we only move to that state after it got a snapshot. 


<!-- Sent from Reviewable.io -->

2022-02-17 18:09 UTC, nvanbenschoten reviewed
> Reviewed 2 of 3 files at r10, 12 of 12 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/allocator.go, line 1948 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-Mw7r5juDa02sQKKk4Yp:-Mw7r5juDa02sQKKk4Yq:bpb6o5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/562db05c33216c58cd7cb9d13e4ac588df616628/pkg/kv/kvserver/allocator.go#L1948)):*
> ```Go
> func replicaMayNeedSnapshot(raftStatus *raft.Status, replica roachpb.ReplicaDescriptor) bool {
> 	// When adding replicas, we only move them from LEARNER to VOTER_INCOMING after
> 	// they applied the snapshot
> ```

Do you mind pointing at the code that does this: `initializeRaftLearners`.

also, nit: punctuation.
___
*[pkg/kv/kvserver/replica_command.go, line 3101 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvteViQ4yRfXGsa82_m:-Mw7rriE3JxXzc6fqhN7:b-ncw7nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/kv/kvserver/replica_command.go#L3101)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's somewhat disconcerting to see so many calls to `IsActive(EnableLeaseHolderRemoval)`. The cluster version state is an atomic that can be changed at any time, so each of these calls needs to be the one that's prepared to see the active status switch from `false` to `true`. Furthermore, the cluster version is monotonic on a single node, but different nodes can see this active status switch at different times. Are we confident that we're handling things correctly in each case?

As a general design principle with version upgrades like this, it's helpful to try to find a single "gate" where the version can be checked. This eliminates the number of states that the system can be in midway through a version upgrade. With this change, we may need two:
1. a best-effort, graceful one in the `replicateQueue` to decide whether to attempt a leaseholder-removing replication change or whether to use the old logic
2. a strict one in `Replica.propose` to decide whether a leaseholder can enter a joint config that removes itself. This one is currently missing.

I guess we may also need one more somewhere in `relocateReplicas` to decide whether to attempt a leaseholder-removing replication change or whether to use the old logic.
</blockquote></details>

I think this is my last remaining comment!
___
*[pkg/sql/logictest/logic.go, line 1449 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MvtIWCr905OBoq5JzWB:-Mw7re8B-3CaEM-o4SKz:bcir6eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe38fae39a6f46dc70a5f34b82594760cf5d68bf/pkg/sql/logictest/logic.go#L1449)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Raft progress, which we use to determine whether the replica may need a snapshot, is managed by Raft, which expects one more log update after the snapshot before marking progress as "replicating". Discussed this with @tbg and we decided to go with a simpler solution - to consider any replica in the VOTER_INCOMING state as one that we shouldn't filter out based on "may need a snapshot", since we only move to that state after it got a snapshot. 
</blockquote></details>

That's a good idea. Glad we found a reasonable way to do this.


<!-- Sent from Reviewable.io -->

2022-02-17 20:15 UTC, nvanbenschoten approved these changes
The latest round of changes <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-:-Mw8Jp8a5fHuKt_FOUnI:bw81jut)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)



<!-- Sent from Reviewable.io -->

2022-02-18 02:31 UTC, shralex reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOSYuZDYVXAmDD0ZgN:-Mw9cqy5CYp8L_6JK4-x:bm96evn) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1211)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Do we understand the case(s) where `TransferLeaseTarget` would ever return an empty target when `checkTransferLeaseSource = false`? If it is somehow possible for `TransferLeaseTarget` to produce an empty target, then that seems like something we need to address because as Nathan was saying above, this means that the range would potentially never be able to get out of its joint state. We should have a `log.Fatal()` if this returns an empty target.

It looks like `TransferLeaseTarget` could return an empty target if all the other replicas of the range are on `suspect` or `draining` stores. The `suspect` state shouldn't be permanent (though it could last for a while), and the `draining` state is essentially permanent unless the node is restarted. We could perhaps fix this by having the caller ask `TransferLeaseTarget` to consider all candidate stores (i.e. use `storeFilterNone` instead of `storeFilterSuspect`). 

Also, what do you think about lifting this call to `TransferLeaseTarget` into an appropriately named helper that has comments outlining why we need to ensure that it produces a different lease target?
</blockquote></details>

This method is pretty complex and depends on many flags, so my confidence isn't very high. But with the current set of flags I'm providing (which I picked to do the least possible filtering of candidates), two cases where an empty set could still be returned seem to be suspect/unknown/draining nodes and nodes needing a snapshot. I added another test to make sure that if we have a preferred region but nodes aren't available there, this would not stop the lease from transferring somewhere. I also made sure that incoming nodes aren't filtered due to the snapshot heuristic. As for suspect/unknown/draining nodes, it seems to me that it is better to stay in the joint config until this is fixed for some node then transfer the lease to a node in this state, since this specific node isn't guaranteed to recover, and then we'd be waiting for re-election. 
___
*[pkg/kv/kvserver/replica_command.go, line 1218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrRUglh5fXn4ANJ4ap0:-Mw7psef7pr2a25_SyMf:bg0jfsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1218)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Could there be races with lease preferences where the new leaseholder immediately sends the lease back, and we never manage to do the replication change below? 

I think the way this should work is that lease transfers to a voter in the process of being removed (`VOTER_DEMOTING` or `VOTER_OUTGOING`) should be disallowed, so once we move the lease away, nothing should be able to move it back.
</blockquote></details>

Right, this check is done in CheckCanReceiveLease


<!-- Sent from Reviewable.io -->

2022-02-18 18:21 UTC, aayushshah15 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> except for that one comment. It's exciting to see this land!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-:-MwD2nhADlqAB6AhaFSV:b-eoai1j)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOSYuZDYVXAmDD0ZgN:-MwD0lLH2cl7gMfnFwB2:b-yexeex) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1211)):*
>As for suspect/unknown/draining nodes, it seems to me that it is better to stay in the joint config until this is fixed for some node then transfer the lease to a node in this state, since this specific node isn't guaranteed to recover, and then we'd be waiting for re-election.

A range not being able to exit the joint config will wedge splits, merges, and all rebalancing on the range (including load-based rebalancing). I'm particularly worried about wedging rebalancing on the range since that affects our ability to get the range off of suspect stores. 

Maybe its all fine but it adds an additional consideration that should at least be properly documented here. Did we consider pulling this call out into a helper that documents this discussion? 


<!-- Sent from Reviewable.io -->

2022-02-18 19:22 UTC, shralex reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOSYuZDYVXAmDD0ZgN:-MwDFqVVAhiryTjGXLxx:brl1x1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1211)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

>As for suspect/unknown/draining nodes, it seems to me that it is better to stay in the joint config until this is fixed for some node then transfer the lease to a node in this state, since this specific node isn't guaranteed to recover, and then we'd be waiting for re-election.

A range not being able to exit the joint config will wedge splits, merges, and all rebalancing on the range (including load-based rebalancing). I'm particularly worried about wedging rebalancing on the range since that affects our ability to get the range off of suspect stores. 

Maybe its all fine but it adds an additional consideration that should at least be properly documented here. Did we consider pulling this call out into a helper that documents this discussion? 
</blockquote></details>

This seems like an inherent risk with this whole approach.  I pulled this code into a separate method, please let me know if this is what you had in mind.  One thing we could perhaps do is call TransferLeaseTarget before entering the joint config to see if there are suitable candidates and not enter the config if there aren't. It does not guarantee that we'll be able to exit, but perhaps reduces the vulnerability. wdyt ? if you like this idea, any suggestion where to make this call ?


<!-- Sent from Reviewable.io -->

2022-02-18 21:16 UTC, aayushshah15 approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74077)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @aayushshah15, @nvanbenschoten, @shralex, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74077#-MrOSYuZDYVXAmDD0ZgN:-MwDd7mk6LCzpzjU8OwZ:b-h7djuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/527263a073748351f599d78fc1ceccc6bb671ee2/pkg/kv/kvserver/replica_command.go#L1211)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

This seems like an inherent risk with this whole approach.  I pulled this code into a separate method, please let me know if this is what you had in mind.  One thing we could perhaps do is call TransferLeaseTarget before entering the joint config to see if there are suitable candidates and not enter the config if there aren't. It does not guarantee that we'll be able to exit, but perhaps reduces the vulnerability. wdyt ? if you like this idea, any suggestion where to make this call ?
</blockquote></details>

Thanks, that is what I had in mind. We could do what you're suggesting (by faking the new incoming replica and passing that into `TransferLeaseTarget`), if so I'd suggest doing it where we're checking if we're removing the leaseholder before creating the learner replicas (and if so, if the version gate allows us to do so). We could also do that as a follow up patch. 


<!-- Sent from Reviewable.io -->

2022-02-18 23:34 UTC, shralex commented
bors r+

2022-02-19 00:32 UTC, merged