sql: introduce Transaction ID Cache
cockroachdb/cockroach pull request #74115
Opened 2021-12-21 00:41 UTC by Azhng

sql: introduce Transaction ID Cache

Previously, it was impossible to correlate an individual execution
of a transaction (identified via transaction ID) to this historical
execution statistics (identified via transaction fingerprint ID).

This commit introduces Transaction ID Cache (TxnIDCache), a FIFO
cache that stores the mapping from transaction ID to transaction
fingerprint ID. This buffer records the mapping at the
end of the transaction execution. The oldest entry in the buffer
will be evicted through FIFO policy. The default size of this
Transaction ID Cache is capped at 64 MB and it is configurable via
the sql.contention.txn_id_cache.max_size cluster setting.

Release note (sql change): Transaction ID to Transaction Fingerprint
ID mapping is now stored in the new Transaction ID Cache, a FIFO
unordered in-memory buffer. The size of the buffer is 64 MB by default
and configurable via sql.contention.txn_id_cache.max_size cluster
setting. Consequentially, two additioanl metrics are introduced:
* sql.contention.txn_id_cache.size: tracks the current memory usage
of transaction ID Cache
* sql.contention.txn_id_cache.discarded_count: number of resolved
transaction IDs that are dropped due to memory constraints.

2021-12-21 00:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74115)
<!-- Reviewable:end -->

2021-12-21 16:43 UTC, ajwerner commented on pkg/sql/contention/txnidcache/txn_id_cache.go
> +//   +----------------------------|---+
It feels to me like the connExecutor should just write straight to a shard. The shard is sharded and the channel is not. What would happen if you simplified it such that when a shard is full, you send the shard itself on the channel to flush and swap it out with a new shard? You can then sync.Pool the shards

2021-12-22 04:35 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-MrVN6ov7suLYfo0gnfc:b-29zc0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It feels to me like the connExecutor should just write straight to a shard. The shard is sharded and the channel is not. What would happen if you simplified it such that when a shard is full, you send the shard itself on the channel to flush and swap it out with a new shard? You can then sync.Pool the shards
</blockquote></details>

I agree that we want the connExecutor calling directly into a shard — until reading this comment, I thought that was the point of the `ConcurrentWriteBuffer`. But I don't understand your "shard is full" comment. We seem to be using a fixed number of shards and enforcing a separate memory limit + FIFO eviction policy within each shard. So unless I'm completely misreading this (very possible), the shards are static.
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVNpVn5KtcevdKsWlz:-MrVNpVn5KtcevdKsWm-:bt4my5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache.go#L80)):*
> 8 // the size of a hash

Where does this come from?
___
*[pkg/sql/contention/txnidcache/txn_id_cache_shard.go, line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVEcaIETKNMhKBRpUZ:-MrVEcaIETKNMhKBRpU_:b-z0sdn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache_shard.go#L51)):*
> ```Go
> 		txnIDCache:  t,
> 	}
> 	shard.mu.store = cache.NewUnorderedCache(cache.Config{
> ```

I've been following this work from afar since reading the original RFC. It seems like we're making great progress in terms of reducing the cost of this cache. The `ConcurrentWriteBuffer` should significantly reduce the lock contention we see when recording transaction IDs.

Another suggestion to make this cheaper is to avoid per-transaction accounting in each `cacheShard`. We are currently tracking the aggregate size of entries and enforcing a FIFO policy that keeps each cache shard as full as possible while staying below a memory limit. In exchange, we use `cache.UnorderedCache`, which is quite heavyweight (i.e. all entries are wrapped, a per-entry linked-list is maintained, etc.).

We really don't need precise memory accounting or FIFO enforcement, we just need something that approximates it. So you can imagine much cheaper methods for enforcing a hard memory limit with a loose temporal eviction preference. A strawman proposal is a ring buffer with each slot containing a size-limited bounded `map[uuid.UUID]roachpb.TransactionFingerprintID`. When inserting, you push into the head of the ring buffer, rotating if necessary when a map fills up. When performing a lookup, you would iterate over the maps (in reverse time order, to advantage recent entries) and perform lookups, short-circuiting if you found what you were looking for. You could play with the size of the ring buffer (i.e. the number of maps), which becomes a trade-off between read amplification and eviction granularity. My guess is that a value of 4 or 8 would be reasonable. Then the maximum capacity of each map would become `((MaxSize / shardCount) / ringBufferSize) / entrySize`, which is O(1000).
___
*[pkg/sql/contention/txnidcache/txn_id_cache_shard.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVOg1J0G01aThmCfuR:-MrVOg1J0G01aThmCfuS:b-uww5wr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache_shard.go#L79)):*
> ```Go
> 
> // Record implements the writer interface.
> func (s *cacheShard) Record(msg ResolvedTxnID) {
> ```

I don't mean to pick a fight with the interfaces here, as I imagine they have been useful during the design iteration, but let's make sure they don't force us into a suboptimal final state. For instance, does it make sense for the mutex locking around a `cacheShard` and its associated `ConcurrentWriteBuffer` to be separate? And does it make sense to record `ResolvedTxnID`s to a `cacheShard` one-by-one when the caller wants to do so in a large batch?
___
*[pkg/sql/contention/txnidcache/txn_id_cache_shard.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVL63XAu-bEUqj5UH6:-MrVL63XAu-bEUqj5UH7:b-6bf5ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache_shard.go#L80)):*
> ```Go
> // Record implements the writer interface.
> func (s *cacheShard) Record(msg ResolvedTxnID) {
> 	s.writeBuffer = append(s.writeBuffer, msg)
> ```

What is the benefit of this `writeBuffer`? Will is be replaced by `ConcurrentWriteBuffer` at some point?
___
*[pkg/sql/contention/txnidcache/txn_id_cache_shard.go, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVLv5P0YQTrh-CXVYA:-MrVLv5P0YQTrh-CXVYB:bdrxa9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache_shard.go#L94)):*
> ```Go
> 
> // Lookup implements the reader interface.
> func (s *cacheShard) Lookup(txnID uuid.UUID) (result roachpb.TransactionFingerprintID, found bool) {
> ```

Do we need to flush on lookup?


<!-- Sent from Reviewable.io -->

2021-12-23 18:21 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-MrcTLPG8HgJMk2rt8b1:b7dmqsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I agree that we want the connExecutor calling directly into a shard — until reading this comment, I thought that was the point of the `ConcurrentWriteBuffer`. But I don't understand your "shard is full" comment. We seem to be using a fixed number of shards and enforcing a separate memory limit + FIFO eviction policy within each shard. So unless I'm completely misreading this (very possible), the shards are static.
</blockquote></details>

Rewrote part of the diagram to reflect the new changes. 
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVNpVn5KtcevdKsWlz:-MrcTcVd5A8fDpTCgvsV:bexb22e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache.go#L80)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> 8 // the size of a hash

Where does this come from?
</blockquote></details>

It was used to account the "hash" inside of Go's hashmap. Removed. 
___
*[pkg/sql/contention/txnidcache/txn_id_cache_shard.go, line 51 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVEcaIETKNMhKBRpUZ:-MrcTryrDuwEh4at0EuS:bdyancv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache_shard.go#L51)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I've been following this work from afar since reading the original RFC. It seems like we're making great progress in terms of reducing the cost of this cache. The `ConcurrentWriteBuffer` should significantly reduce the lock contention we see when recording transaction IDs.

Another suggestion to make this cheaper is to avoid per-transaction accounting in each `cacheShard`. We are currently tracking the aggregate size of entries and enforcing a FIFO policy that keeps each cache shard as full as possible while staying below a memory limit. In exchange, we use `cache.UnorderedCache`, which is quite heavyweight (i.e. all entries are wrapped, a per-entry linked-list is maintained, etc.).

We really don't need precise memory accounting or FIFO enforcement, we just need something that approximates it. So you can imagine much cheaper methods for enforcing a hard memory limit with a loose temporal eviction preference. A strawman proposal is a ring buffer with each slot containing a size-limited bounded `map[uuid.UUID]roachpb.TransactionFingerprintID`. When inserting, you push into the head of the ring buffer, rotating if necessary when a map fills up. When performing a lookup, you would iterate over the maps (in reverse time order, to advantage recent entries) and perform lookups, short-circuiting if you found what you were looking for. You could play with the size of the ring buffer (i.e. the number of maps), which becomes a trade-off between read amplification and eviction granularity. My guess is that a value of 4 or 8 would be reasonable. Then the maximum capacity of each map would become `((MaxSize / shardCount) / ringBufferSize) / entrySize`, which is O(1000).
</blockquote></details>

This is a very neat idea. I rewrote the implementation behind each `shard` to use his ring buffer size approach.
___
*[pkg/sql/contention/txnidcache/txn_id_cache_shard.go, line 79 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVOg1J0G01aThmCfuR:-MrcWOWsAA4G8akJ9Iwg:b-sxlbvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache_shard.go#L79)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't mean to pick a fight with the interfaces here, as I imagine they have been useful during the design iteration, but let's make sure they don't force us into a suboptimal final state. For instance, does it make sense for the mutex locking around a `cacheShard` and its associated `ConcurrentWriteBuffer` to be separate? And does it make sense to record `ResolvedTxnID`s to a `cacheShard` one-by-one when the caller wants to do so in a large batch?
</blockquote></details>

Reworked the interface so that the write path happens through a batch-insertion `push()` call. 
___
*[pkg/sql/contention/txnidcache/txn_id_cache_shard.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVL63XAu-bEUqj5UH6:-MrcUz1o-BbsB7aZVrku:boiy07a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache_shard.go#L80)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What is the benefit of this `writeBuffer`? Will is be replaced by `ConcurrentWriteBuffer` at some point?
</blockquote></details>

It was kind left behind when I was playing around with different idea of reduce mutex contentions. Now removed since the entire shard implementation was rewritten. 
___
*[pkg/sql/contention/txnidcache/txn_id_cache_shard.go, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVLv5P0YQTrh-CXVYA:-MrcVqBDC4kTv4XfYFJr:bnupgrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache_shard.go#L94)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to flush on lookup?
</blockquote></details>

Hmm I'm leaning towards no. Since flush is a pretty expensive operation and it will block every single active writer (and consequently, every singe connExecutor). I think the caller should be responsible for retrying if the lookup fail.


<!-- Sent from Reviewable.io -->

2021-12-23 19:22 UTC, nvanbenschoten reviewed
> Reviewed 2 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/strip.go, line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrciQjgC_ec5CZsQ6zW:-MrciQjgC_ec5CZsQ6zX:b-9v2t7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2806625a4c0fefb5caa48a14c9976d392ac854f/pkg/sql/contention/txnidcache/strip.go#L30)):*
> ```Go
> func newStrip(capacity capacityLimiter) *strip {
> 	c := &strip{
> 		data:     make(map[uuid.UUID]roachpb.TransactionFingerprintID),
> ```

You could give the map an initial capacity of `capacity()`.
___
*[pkg/sql/contention/txnidcache/strip.go, line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrciE4_8hse8aNC_4K2:-MrciE4_8hse8aNC_4K3:buakjec) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2806625a4c0fefb5caa48a14c9976d392ac854f/pkg/sql/contention/txnidcache/strip.go#L61)):*
> ```Go
> 
> 	blockIdx := blockStartingOffset
> 	capn := c.capacity()
> ```

nit: Grab the capacity reading before entering the lock, since it might be an "expensive" atomic load.
___
*[pkg/sql/contention/txnidcache/strip.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrchnHU-qKAanR3H3EE:-MrchnHU-qKAanR3H3EF:bof82am) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2806625a4c0fefb5caa48a14c9976d392ac854f/pkg/sql/contention/txnidcache/strip.go#L64)):*
> ```Go
> 	for ; blockIdx < messageBlockSize && block[blockIdx].valid() && c.size < capn; blockIdx++ {
> 		c.data[block[blockIdx].TxnID] = block[blockIdx].TxnFingerprintID
> 		c.size++
> ```

Isn't `size` the same thing as `len(c.data)`?
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-MrciZxUEzmipminJR_U:b-e50v6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Rewrote part of the diagram to reflect the new changes. 
</blockquote></details>

Doesn't this diagram still show the connExecutor writing to the cache through a channel and goroutine?
___
*[pkg/sql/contention/txnidcache/txn_id_cache_shard.go, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVLv5P0YQTrh-CXVYA:-Mrcizp1-jDA0m5X_WlK:b-7lo16l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache_shard.go#L94)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm I'm leaning towards no. Since flush is a pretty expensive operation and it will block every single active writer (and consequently, every singe connExecutor). I think the caller should be responsible for retrying if the lookup fail.
</blockquote></details>

Retrying is an interesting idea. You can imagine a hybrid scheme where each caller performs an "optimistic" read and only flushes and retries if that misses.


<!-- Sent from Reviewable.io -->

2021-12-23 21:44 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/strip.go, line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrciQjgC_ec5CZsQ6zW:-Mrd8JznAyEOmK2wDuyu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2806625a4c0fefb5caa48a14c9976d392ac854f/pkg/sql/contention/txnidcache/strip.go#L30)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You could give the map an initial capacity of `capacity()`.
</blockquote></details>

Done.
___
*[pkg/sql/contention/txnidcache/strip.go, line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrciE4_8hse8aNC_4K2:-Mrd8Kw-BwMugoVnuJVb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2806625a4c0fefb5caa48a14c9976d392ac854f/pkg/sql/contention/txnidcache/strip.go#L61)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Grab the capacity reading before entering the lock, since it might be an "expensive" atomic load.
</blockquote></details>

Done.
___
*[pkg/sql/contention/txnidcache/strip.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrchnHU-qKAanR3H3EE:-Mrd8NMn1PrzAFYb208C:b-qf51hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2806625a4c0fefb5caa48a14c9976d392ac854f/pkg/sql/contention/txnidcache/strip.go#L64)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Isn't `size` the same thing as `len(c.data)`?
</blockquote></details>

Ah good point. Done.
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-Mrd8Px5BDlg852GIEVz:b-f81j5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Doesn't this diagram still show the connExecutor writing to the cache through a channel and goroutine?
</blockquote></details>

Hmm previously the set up was `ConcurrentWriteBuffer` -> `channel` --- polled via goroutine ---> `sharded store`.

It felt a bit redundant for sure, however after I updated the code to remove the `channel` in the middle to directly to the `sharded store`, 

However, after running the benchmark it looks like there's a jump in the overhead compared to the version where `channel` is used.

``` bash
$ benchstat ~/tmp/lightweightmap/bench ~/tmp/lightweightmap-no-chan/bench
name                                    old overhead(ns/op)  new overhead(ns/op)  delta
ConcurrentSelect1/concurrentConn=24-24           4.05k ±21%           5.44k ±18%  +34.41%  (p=0.000 n=10+9)
ConcurrentSelect1/concurrentConn=48-24           5.08k ±20%           5.83k ±98%     ~     (p=0.211 n=9+10)
ConcurrentSelect1/concurrentConn=64-24           5.58k ±22%           4.30k ±19%  -22.99%  (p=0.003 n=8+8)
```

I'm not sure how this will look on TPCC, I'll go ahead and run the benchmark and report back later. 
___
*[pkg/sql/contention/txnidcache/txn_id_cache_shard.go, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrVLv5P0YQTrh-CXVYA:-MrdEjco2Z6XYHllmy3b:ba4kizk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d09bcb268eee4d5eb509207adb99839f52f78d5/pkg/sql/contention/txnidcache/txn_id_cache_shard.go#L94)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Retrying is an interesting idea. You can imagine a hybrid scheme where each caller performs an "optimistic" read and only flushes and retries if that misses.
</blockquote></details>

Interesting :thinking:. That could definitely be a possibility. Though I will hold off on implementing that here and explore that when I work on the read-path of the Transaction ID Resolution protocol. 


<!-- Sent from Reviewable.io -->

2022-01-03 19:41 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-MsVggn94alFLb0YlG6o:b1byq1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm previously the set up was `ConcurrentWriteBuffer` -> `channel` --- polled via goroutine ---> `sharded store`.

It felt a bit redundant for sure, however after I updated the code to remove the `channel` in the middle to directly to the `sharded store`, 

However, after running the benchmark it looks like there's a jump in the overhead compared to the version where `channel` is used.

``` bash
$ benchstat ~/tmp/lightweightmap/bench ~/tmp/lightweightmap-no-chan/bench
name                                    old overhead(ns/op)  new overhead(ns/op)  delta
ConcurrentSelect1/concurrentConn=24-24           4.05k ±21%           5.44k ±18%  +34.41%  (p=0.000 n=10+9)
ConcurrentSelect1/concurrentConn=48-24           5.08k ±20%           5.83k ±98%     ~     (p=0.211 n=9+10)
ConcurrentSelect1/concurrentConn=64-24           5.58k ±22%           4.30k ±19%  -22.99%  (p=0.003 n=8+8)
```

I'm not sure how this will look on TPCC, I'll go ahead and run the benchmark and report back later. 
</blockquote></details>

Reporting back. I did a few TPCC runs. Compared to the baseline latency (`master` entries), the p75 (and above) latency is higher for the implementation without using the channel (if we disregard the last bad run). The implementation using the channel is a lot more comparable to the baseline latency. I also attached the benchmark result for the implementation where it directly writes to the channel without using `ConcurrentWriteBuffer` as a reference.


| Branch                               | tpmC    | %efficiency | Avg (ms) | p50 (ms) | p75 (ms) | p90 (ms) | p99 (ms) | pMax (ms) |
|--------------------------------------|---------|-------------|----------|----------|----------|----------|----------|-----------|
| master                               | 31386.0 | 97.6%       |  76.2    |  30.4    | 58.7     |  71.3    | 109.1    | 23622.3   |
| master                               | 31430.2 | 97.8%       |  50.4    |  29.4    | 58.7     |  71.3    | 113.2    | 11811.2   |
| no-chan                     | 31419.2 | 97.7%       |  64.1    |  29.4    | 75.5     |  92.3    | 151.0    | 12348.0   |
| no-chan                    | 31397.2 | 97.7%       |  73.9    |  31.5    | 83.9     |  104.9   | 176.2    | 16106.1   |
| no-chan*                    | 31324.9 | 97.4%       |  135.7   |  35.7    | 113.2    |  142.6   | 1476.4   | 38654.7   |
| chan                        | 31419.3 | 97.7%       |  54.7    |  28.3    | 56.6     |  67.1    | 109.1    | 16106.1   |
| chan                       | 31421.9 | 97.7%       |  56.6    |  28.3    | 58.7     |  75.5    | 121.6    | 17179.9   |
| channel without concurrent buffer                   | 31298.1 | 97.4%       |  153.3   |  58.7    | 218.1    |  469.8   | 2013.3   | 15032.4   |


<!-- Sent from Reviewable.io -->

2022-01-11 15:38 UTC, maryliag reviewed
> Reviewed 1 of 7 files at r1, 3 of 29 files at r5, 23 of 26 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor.go, line 286 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mt8h-pP4eSoVoBlNiHN:-Mt8h-pQ5Bgf-RblpqBO:bh6t7zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e68c054e17dd14fee0482505e3494e670f8db84/pkg/sql/conn_executor.go#L286)):*
> ```Go
> 
> 	// txnIDCache stores the mapping from transaction ID to transaction
> 	//fingerprint IDs for all recently executed.
> ```

nit: add space after // 
... all recently executed transactions.
___
*[pkg/sql/contention/txnidcache/shard.go, line 57 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mt8k0sGAVUYt5zqGJUU:-Mt8k0sGAVUYt5zqGJUV:br7696x) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e68c054e17dd14fee0482505e3494e670f8db84/pkg/sql/contention/txnidcache/shard.go#L57)):*
> ```Go
> 
> 	for i := s.head; ; i = s.prevIdx(i) {
> 		fingerprintID, found := s.ring[i].Lookup(txnID)
> ```

do we need both the ID and the `found`? Can't we just check the ID value, if is not 0 we know it was found, so we won't need the extra variable
___
*[pkg/sql/contention/txnidcache/cluster_settings.go, line 20 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mt8i99n5eHCycxjCkAP:-Mt8i99n5eHCycxjCkAQ:b-gefjs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e68c054e17dd14fee0482505e3494e670f8db84/pkg/sql/contention/txnidcache/cluster_settings.go#L20)):*
> ```Go
> 	`sql.contention.txn_id_cache.max_size`,
> 	"the maximum byte size TxnID cache will use",
> 	64*1024*1024, // 64 MB
> ```

where there any tests made to decide on this value?


<!-- Sent from Reviewable.io -->

2022-01-11 23:22 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor.go, line 286 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mt8h-pP4eSoVoBlNiHN:-MtAQYOK0bXr8k8l8a2b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e68c054e17dd14fee0482505e3494e670f8db84/pkg/sql/conn_executor.go#L286)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: add space after // 
... all recently executed transactions.
</blockquote></details>

Done.
___
*[pkg/sql/contention/txnidcache/shard.go, line 57 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mt8k0sGAVUYt5zqGJUU:-MtARGYK1uO6JmjRDNYx:b-ngdtwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e68c054e17dd14fee0482505e3494e670f8db84/pkg/sql/contention/txnidcache/shard.go#L57)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

do we need both the ID and the `found`? Can't we just check the ID value, if is not 0 we know it was found, so we won't need the extra variable
</blockquote></details>

We need to distinguish between the two cases where:
* transaction ID is present on this node, but transaction fingerprint ID is not yet available
* transaction ID is not present on this node.

The support for the first case is being introduced in #74687. 

This distinction is important later to handle [prolonged RPC failure](https://github.com/Azhng/cockroach/blob/rfc-ces/docs/RFCS/20211013_contentions.md#failure-modes) described in the original RFC. 
___
*[pkg/sql/contention/txnidcache/cluster_settings.go, line 20 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mt8i99n5eHCycxjCkAP:-MtAQwsw14Obk0s_eTKf:b-rwpvsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e68c054e17dd14fee0482505e3494e670f8db84/pkg/sql/contention/txnidcache/cluster_settings.go#L20)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

where there any tests made to decide on this value?
</blockquote></details>

This comes from Yahor's [latest comment](https://github.com/cockroachdb/cockroach/pull/71965#pullrequestreview-801950688) on the RFC. It's really there so that we keep long enough history to handle long-running transactions without explicitly tracking the expiration time.


<!-- Sent from Reviewable.io -->

2022-01-18 21:44 UTC, Azhng commented
@nvanbenschoten  @ajwerner  PTAL! 🙏

2022-01-21 16:14 UTC, maryliag reviewed
Changes <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> , but I would like to see the approval of others tagged here before a merge

> Reviewed 2 of 26 files at r6, 6 of 14 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-:-MtxPegr9I3DT38BgEve:b-gwg6d6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @maryliag, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-01-24 16:53 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-MuBzjyQ7ktU6h2LrB1s:b9a8h4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Reporting back. I did a few TPCC runs. Compared to the baseline latency (`master` entries), the p75 (and above) latency is higher for the implementation without using the channel (if we disregard the last bad run). The implementation using the channel is a lot more comparable to the baseline latency. I also attached the benchmark result for the implementation where it directly writes to the channel without using `ConcurrentWriteBuffer` as a reference.


| Branch                               | tpmC    | %efficiency | Avg (ms) | p50 (ms) | p75 (ms) | p90 (ms) | p99 (ms) | pMax (ms) |
|--------------------------------------|---------|-------------|----------|----------|----------|----------|----------|-----------|
| master                               | 31386.0 | 97.6%       |  76.2    |  30.4    | 58.7     |  71.3    | 109.1    | 23622.3   |
| master                               | 31430.2 | 97.8%       |  50.4    |  29.4    | 58.7     |  71.3    | 113.2    | 11811.2   |
| no-chan                     | 31419.2 | 97.7%       |  64.1    |  29.4    | 75.5     |  92.3    | 151.0    | 12348.0   |
| no-chan                    | 31397.2 | 97.7%       |  73.9    |  31.5    | 83.9     |  104.9   | 176.2    | 16106.1   |
| no-chan*                    | 31324.9 | 97.4%       |  135.7   |  35.7    | 113.2    |  142.6   | 1476.4   | 38654.7   |
| chan                        | 31419.3 | 97.7%       |  54.7    |  28.3    | 56.6     |  67.1    | 109.1    | 16106.1   |
| chan                       | 31421.9 | 97.7%       |  56.6    |  28.3    | 58.7     |  75.5    | 121.6    | 17179.9   |
| channel without concurrent buffer                   | 31298.1 | 97.4%       |  153.3   |  58.7    | 218.1    |  469.8   | 2013.3   | 15032.4   |



</blockquote></details>

What I don't really understand is the use of the sharded store underneath the channel. The sharding exists to deal with mutex contention due to writing. It feels like once we write to the channel, then we can leave the goroutine to consume from the channel and write to a much simpler cache. Have you tried replacing the cache with something very simple? 


<!-- Sent from Reviewable.io -->

2022-01-24 16:53 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-MuC-Sda82kz1HQ9PcZc:bwn6uuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What I don't really understand is the use of the sharded store underneath the channel. The sharding exists to deal with mutex contention due to writing. It feels like once we write to the channel, then we can leave the goroutine to consume from the channel and write to a much simpler cache. Have you tried replacing the cache with something very simple? 
</blockquote></details>

I think that if you find there's still issues, my guess is that the right thing to do is shard the writer as opposed to the cache 


<!-- Sent from Reviewable.io -->

2022-01-24 20:55 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-MuCreBN1kJFZ2RVDw4f:b-mbxfx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think that if you find there's still issues, my guess is that the right thing to do is shard the writer as opposed to the cache 
</blockquote></details>

Good point. Removed the hash sharded map and just use the ring buffer directly here instead. TPCC number still looks good. 


| Branch                               | tpmC    | %efficiency | Avg (ms) | p50 (ms) | p75 (ms) | p90 (ms) | p99 (ms) | pMax (ms) |
|--------------------------------------|---------|-------------|----------|----------|----------|----------|----------|-----------|
| master                               | 31430.2 | 97.8%       |  50.4    |  29.4    | 58.7     |  71.3    | 113.2    | 11811.2   |
| no-shard                             | 31428.8 | 97.8%       |  51.4    |  27.3    | 54.5     |  67.1    | 109.1    | 19327.4   |


<!-- Sent from Reviewable.io -->

2022-01-24 21:03 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-MuCt_kx-wokkNo0wRgC:b-tixp0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Good point. Removed the hash sharded map and just use the ring buffer directly here instead. TPCC number still looks good. 


| Branch                               | tpmC    | %efficiency | Avg (ms) | p50 (ms) | p75 (ms) | p90 (ms) | p99 (ms) | pMax (ms) |
|--------------------------------------|---------|-------------|----------|----------|----------|----------|----------|-----------|
| master                               | 31430.2 | 97.8%       |  50.4    |  29.4    | 58.7     |  71.3    | 113.2    | 11811.2   |
| no-shard                             | 31428.8 | 97.8%       |  51.4    |  27.3    | 54.5     |  67.1    | 109.1    | 19327.4   |

</blockquote></details>

Even the ring buffer now seems unncessary. Seems like you could just use a cache.Unordered with LRU and a Mutex 


<!-- Sent from Reviewable.io -->

2022-01-25 17:24 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-MuGtQhWBi_dquIPQVoJ:b-fx8gzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Even the ring buffer now seems unncessary. Seems like you could just use a cache.Unordered with LRU and a Mutex 
</blockquote></details>

Done. Though I don't think we need the LRU in this case, since once the contention event resolved, the cache will never be looked at again. So I just put FIFO as the eviction policy. 


<!-- Sent from Reviewable.io -->

2022-01-25 17:42 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor.go, line 1045 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHHz2i5hmjp6X7KJIW:-MuHHz2i5hmjp6X7KJIX:b-mbd6yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/conn_executor.go#L1045)):*
> ```Go
> 	}
> 
> 	// Since we are closing connExecutor, no need to fetch txnID.
> ```

This comment is not very easy for someone unfamiliar with the code to understand.
___
*[pkg/sql/conn_executor.go, line 1548 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHJAo07sh1yDyWOUKq:-MuHJAo07sh1yDyWOUKr:bffx7t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/conn_executor.go#L1548)):*
> ```Go
> // resetExtraTxnState resets the fields of ex.extraTxnState when a transaction
> // commits, rolls back or restarts.
> func (ex *connExecutor) resetExtraTxnState(
> ```

This deserves deep explanation about what that txnID is, what it means, and how it is being used. 
___
*[pkg/sql/conn_executor.go, line 2680 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHIRhMEAmhc5cyOG-L:-MuHIRhMEAmhc5cyOG-M:b-pz5djw) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/conn_executor.go#L2680)):*
> ```Go
> 		txnID = ex.state.mu.txn.ID()
> 	}
> 	ex.state.mu.RUnlock()
> ```

Is this definitely where you want to be reading this? Not below the state machine advance? This seems extremely subtle. It also seems subtle to be plumbing this into `resetExtraTxnState`.  At the very least we need commentary around why we're grabbing the ID here and what it means to plumb it where we are. 

I am not an expert on this code, but this sort of thing scares me. 



_Code quote:_
```Go
	ex.state.mu.RLock()
	var txnID uuid.UUID
	if ex.state.mu.txn != nil {
		txnID = ex.state.mu.txn.ID()
	}
	ex.state.mu.RUnlock()
```
___
*[pkg/sql/contention/txnidcache/provider.go, line 28 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHJmdc1lnVLbQIZJMq:-MuHJmdc1lnVLbQIZJMr:b-5n6h0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/contention/txnidcache/provider.go#L28)):*
> ```Go
> 	reader
> 	messageSink
> 	writerPool
> ```

I think this thing's design is less than optimal. I think what we want is something like a single `Writer` implementation that internally has some constant number of `ConcurrentWriterBuffer`s sharded by the txn ID. 
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MrPQwk2DwZ5zg2iI7pB-r2-52:-MuHGOAbCafqSdaCoTpw:bwzgazn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1849110aec3e26f7fbcdd3760b1a8a5eaf38b676/pkg/sql/contention/txnidcache/txn_id_cache.go#L52)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done. Though I don't think we need the LRU in this case, since once the contention event resolved, the cache will never be looked at again. So I just put FIFO as the eviction policy. 
</blockquote></details>

:thumbsup: glad we got here. 
___
*[pkg/sql/contention/txnidcache/concurrent_write_buffer.go, line 41 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHK7UO4g5dSorvOC-g:-MuHK7UP627O3crmPHkY:b74bl3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/contention/txnidcache/concurrent_write_buffer.go#L41)):*
> ```Go
> //    conditional variable (flushDone) while holding onto the read-lock. After
> //    the flush is completed, the writer is unblocked and allowed to retry.
> type ConcurrentWriteBuffer struct {
> ```

How come this is exported? 
___
*[pkg/sql/contention/txnidcache/concurrent_write_buffer.go, line 47 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHHQ2j7xAgMWoX8_M9:-MuHHQ2j7xAgMWoX8_MA:b-5pq4ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/contention/txnidcache/concurrent_write_buffer.go#L47)):*
> ```Go
> 	// msgBlock is the temporary buffer that ConcurrentWriteBuffer uses to batch
> 	// write requests before sending them into the channel.
> 	msgBlock messageBlock
> ```

I'd prefer if we used a pointer and a sync.Pool for this. These are intentionally very big. Using the values here and in the channel means a lot of copying we don't need to be doing. It'll also make the flush cheaper. 


<!-- Sent from Reviewable.io -->

2022-01-25 23:42 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor.go, line 1548 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHJAo07sh1yDyWOUKq:-MuIJmNrA3huPOStBg5g:b68onba) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/conn_executor.go#L1548)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This deserves deep explanation about what that txnID is, what it means, and how it is being used. 
</blockquote></details>

Added additional comments.
___
*[pkg/sql/conn_executor.go, line 2680 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHIRhMEAmhc5cyOG-L:-MuHmlks1A9AUiuLI8Gr:bfs36u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/conn_executor.go#L2680)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is this definitely where you want to be reading this? Not below the state machine advance? This seems extremely subtle. It also seems subtle to be plumbing this into `resetExtraTxnState`.  At the very least we need commentary around why we're grabbing the ID here and what it means to plumb it where we are. 

I am not an expert on this code, but this sort of thing scares me. 
</blockquote></details>

The txnID needs to be retrieved here since once the state machine advances by `COMMIT` or `ABORT`, the transaction state is reset and we lose the txnID information.

I added a comment here to explain that. Though who should I ping for review on this section?
___
*[pkg/sql/contention/txnidcache/provider.go, line 28 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHJmdc1lnVLbQIZJMq:-MuHnALcEvLaB-weIyVb:b1e6evv) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/contention/txnidcache/provider.go#L28)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this thing's design is less than optimal. I think what we want is something like a single `Writer` implementation that internally has some constant number of `ConcurrentWriterBuffer`s sharded by the txn ID. 
</blockquote></details>

Reworked to have a single writer with constant number of `concurrentWriteBuffer` 
___
*[pkg/sql/contention/txnidcache/concurrent_write_buffer.go, line 41 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHK7UO4g5dSorvOC-g:-MuHn31ZAfPvhkMGcIAF:b-u5ryhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/contention/txnidcache/concurrent_write_buffer.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How come this is exported? 
</blockquote></details>

unexported
___
*[pkg/sql/contention/txnidcache/concurrent_write_buffer.go, line 47 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHHQ2j7xAgMWoX8_M9:-MuHn5miBrwPAjxaXgor:b-e5jmna) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/contention/txnidcache/concurrent_write_buffer.go#L47)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'd prefer if we used a pointer and a sync.Pool for this. These are intentionally very big. Using the values here and in the channel means a lot of copying we don't need to be doing. It'll also make the flush cheaper. 
</blockquote></details>

Switched to pointer + sync.Pool


<!-- Sent from Reviewable.io -->

2022-01-25 23:53 UTC, ajwerner reviewed
This is looking good. Let me ponder the integration points and see if I can snipe @andreimatei into taking a stance. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-:-MuIe2nX4i5QWDbHSGmy:biq9ybt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/provider.go, line 22 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuIdbEgAcNNqnBgHFhq:-MuIdbEgAcNNqnBgHFhr:by2ow4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e78384750bddb759c2bb857fbe174c40cb40363/pkg/sql/contention/txnidcache/provider.go#L22)):*
> ```Go
> 
> // Provider is the main interface for txnidcache.
> type Provider interface {
> ```

Is there a lot of value in defining this interface here? Maybe define this interface in `sql`? Honestly, I'd just call this thing `Cache` if I could help it. 
___
*[pkg/sql/contention/txnidcache/provider.go, line 26 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuIcPK30wvgZFgkv2co:-MuIcPK30wvgZFgkv2cp:b-aru7xi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e78384750bddb759c2bb857fbe174c40cb40363/pkg/sql/contention/txnidcache/provider.go#L26)):*
> ```Go
> 	Start(ctx context.Context, stopper *stop.Stopper)
> 
> 	// GetWriter returns a Writer to the caller. After returned, the Writer
> ```

at this point, why not just embed writer here directly?



_Code quote:_
```Go
	// GetWriter returns a Writer to the caller. After returned, the Writer
	// is attached to the writerPool and a message sink, and can be disconnected
	// using the disconnector interface.
	GetWriter() Writer
```
___
*[pkg/sql/contention/txnidcache/concurrent_write_buffer.go, line 109 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuIcb-83Ff8-tVMJLQj:-MuIcb-83Ff8-tVMJLQk:bmewl31) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e78384750bddb759c2bb857fbe174c40cb40363/pkg/sql/contention/txnidcache/concurrent_write_buffer.go#L109)):*
> ```Go
> }
> 
> func (c *concurrentWriteBuffer) flushMsgBlockToChannelWLocked() {
> ```

nit: elsewhere in the code we generally just call this `Locked` as opposed to `RLocked`


<!-- Sent from Reviewable.io -->

2022-01-26 00:13 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/provider.go, line 22 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuIdbEgAcNNqnBgHFhq:-MuIiX-BAWCa2xa8ZwK6:b-qkqmsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e78384750bddb759c2bb857fbe174c40cb40363/pkg/sql/contention/txnidcache/provider.go#L22)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is there a lot of value in defining this interface here? Maybe define this interface in `sql`? Honestly, I'd just call this thing `Cache` if I could help it. 
</blockquote></details>

Just to confirm, are you suggesting move everything in `txnidcache` into the `sql` package? (including both the interface and the implementations?)


<!-- Sent from Reviewable.io -->

2022-01-26 04:36 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/provider.go, line 22 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuIdbEgAcNNqnBgHFhq:-MuJe2S67YjqEnPxYGKH:bd5d8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e78384750bddb759c2bb857fbe174c40cb40363/pkg/sql/contention/txnidcache/provider.go#L22)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Just to confirm, are you suggesting move everything in `txnidcache` into the `sql` package? (including both the interface and the implementations?)
</blockquote></details>

No, I was only suggesting moving the interface definition. Having the implementation in this package is 👌. I was thinking maybe we could name this interface sql.TxnIDCache and then we can lose the word Provider entirely. However now I’m thinking we can lose the word provider even without that. What if we just define two interfaces here, Reader and Writer and then use the concrete Cache object in the server package. That’ll simplify ~everything and give us better names, smaller interfaces and the same number of interfaces. What do you think?


<!-- Sent from Reviewable.io -->

2022-01-26 18:13 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/provider.go, line 22 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuIdbEgAcNNqnBgHFhq:-MuM_pMG5M4krLVTzZHb:bszqoir) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e78384750bddb759c2bb857fbe174c40cb40363/pkg/sql/contention/txnidcache/provider.go#L22)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

No, I was only suggesting moving the interface definition. Having the implementation in this package is 👌. I was thinking maybe we could name this interface sql.TxnIDCache and then we can lose the word Provider entirely. However now I’m thinking we can lose the word provider even without that. What if we just define two interfaces here, Reader and Writer and then use the concrete Cache object in the server package. That’ll simplify ~everything and give us better names, smaller interfaces and the same number of interfaces. What do you think?
</blockquote></details>

Done. Love this idea! 
___
*[pkg/sql/contention/txnidcache/provider.go, line 26 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuIcPK30wvgZFgkv2co:-MuM_iKK9_ed9hMQJy5a:b-wcextp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e78384750bddb759c2bb857fbe174c40cb40363/pkg/sql/contention/txnidcache/provider.go#L26)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

at this point, why not just embed writer here directly?
</blockquote></details>

Now the `txnidcache.Cache` directly exposes `Record()` method.
___
*[pkg/sql/contention/txnidcache/concurrent_write_buffer.go, line 109 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuIcb-83Ff8-tVMJLQj:-MuMZfcKESzgHXsAiDJU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e78384750bddb759c2bb857fbe174c40cb40363/pkg/sql/contention/txnidcache/concurrent_write_buffer.go#L109)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: elsewhere in the code we generally just call this `Locked` as opposed to `RLocked`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 18:26 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor.go, line 2680 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHIRhMEAmhc5cyOG-L:-MuMcVPH9ydXd3u2EtQK:b-x1co5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/conn_executor.go#L2680)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

The txnID needs to be retrieved here since once the state machine advances by `COMMIT` or `ABORT`, the transaction state is reset and we lose the txnID information.

I added a comment here to explain that. Though who should I ping for review on this section?
</blockquote></details>

I think the data flow would be much nicer if the id of the finished transaction was written by the `conn_fsm` into the events that it passes back to the `conn_executor`. Have you considered that?
I can help explain the conn_fsm code if you're not familiar with it.
___
*[pkg/sql/conn_executor.go, line 1559 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuMbtcI8hlwu7FV6xAn:-MuMbtcI8hlwu7FV6xAo:b-v55pi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb7abe71441745befb9dca8c81e72d3721e292b/pkg/sql/conn_executor.go#L1559)):*
> ```Go
> // in the transaction ID cache.
> func (ex *connExecutor) resetExtraTxnState(
> 	ctx context.Context, ev txnEvent, txnID uuid.UUID,
> ```

at the very least call the new arg `prevTxnID`. But have you considered putting it inside `ev`?


<!-- Sent from Reviewable.io -->

2022-01-26 19:13 UTC, ajwerner requested changes
On the data structure itself, this is very close. Let's get rid of the dropping of messages though. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-:-MuMnXN-763Jadx3Sua_:bdj8a4s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 31 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuMlub3CKXzC9IO3fLh:-MuMlub4C-wAr_08ZXpP:bk23lxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb7abe71441745befb9dca8c81e72d3721e292b/pkg/sql/contention/txnidcache/txn_id_cache.go#L31)):*
> ```Go
> 	// if the given txnID has no entry in the Cache, the returned "found" boolean
> 	// will be false.
> 	// TODO(azhng): we eventually want to implement a batch-lookup API.
> ```

I don't think this TODO is necessarily true. Re-acquiring the RLock seems fine. I'd just delete this TODO. 
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 179 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuMmCZj-8mUz2lGLC49:-MuMmCZj-8mUz2lGLC4A:b-q6w40r) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb7abe71441745befb9dca8c81e72d3721e292b/pkg/sql/contention/txnidcache/txn_id_cache.go#L179)):*
> ```Go
> 			select {
> 			case msgBlock := <-t.msgChan:
> 				func() {
> ```

nit: how do you feel about pulling these into some helper closures:

```go
addBlockToStore := func(b *messageBlock) {
	t.mu.Lock()
	defer t.mu.Unlock()
	for blockIdx := range msgBlock {
		if !msgBlock[blockIdx].valid() {
			break
		}
		t.mu.store.Add(msgBlock[blockIdx].TxnID, msgBlock[blockIdx].TxnFingerprintID)
	}
} 
consumeBlock := func(b *messageBlock) {
	addBlockToStore(b)
	*b = messageBlock{}
	t.messageBlockPool.Put(b)
}
_ = stopper.RunAsyncTask(ctx, "txn-id-cache-ingest", func(ctx context.Context) {
	for {
		select {
		case msgBlock := <-t.msgChan:
			consumeBlock(msgBlock)
		case <-stopper.ShouldQuiesce():
			return
		}
	}
})
```



_Code quote:_
```Go
				func() {
					t.mu.Lock()
					defer t.mu.Unlock()
					for blockIdx := range msgBlock {
						if !msgBlock[blockIdx].valid() {
							break
						}
						t.mu.store.Add(msgBlock[blockIdx].TxnID, msgBlock[blockIdx].TxnFingerprintID)
					}
				}()
```
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 222 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuMn62YEgNIsfJLZ9Bx:-MuMn62YEgNIsfJLZ9By:bolwg27) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb7abe71441745befb9dca8c81e72d3721e292b/pkg/sql/contention/txnidcache/txn_id_cache.go#L222)):*
> ```Go
> 	case t.msgChan <- msg:
> 		// noop.
> 	default:
> ```

I don't think I'd do this. I'd block. Everything that might possibly lead to blocking here implies CPU overload for seemingly fast tasks. I think discarding these is a little bit crazy and I feel like on shutdown, weird stuff is going to happen. Instead what I'd do is make a channel that you'll close when the `Start` loop exits and `select` on it. 



_Code quote:_
```Go
	default:
		t.metrics.DiscardedResolvedTxnIDCount.Inc(messageBlockSize)
```
___
*[pkg/sql/contention/txnidcache/writer.go, line 20 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuMkpjd3lrzBkhbkd4H:-MuMkpjd3lrzBkhbkd4I:b127cdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb7abe71441745befb9dca8c81e72d3721e292b/pkg/sql/contention/txnidcache/writer.go#L20)):*
> ```Go
> )
> 
> const shardCount = 128
> ```

My guess is that this is an order of magnitude more shards than you need. I don't have a strongly principled reason to say so beyond that Java's ConcurrentHashMap uses 16 shards and it does a good bit more under the mutex than you are here. How about 16 and a comment saying what I'm saying here and that empirically the number seems good enough. 


<!-- Sent from Reviewable.io -->

2022-01-26 19:48 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor.go, line 2680 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuHIRhMEAmhc5cyOG-L:-MuMvU9U-x8J9n-sEj9s:bf83us1) ([raw file](https://github.com/cockroachdb/cockroach/blob/558831d630a003cf98bf2afe4a8b30560b163771/pkg/sql/conn_executor.go#L2680)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think the data flow would be much nicer if the id of the finished transaction was written by the `conn_fsm` into the events that it passes back to the `conn_executor`. Have you considered that?
I can help explain the conn_fsm code if you're not familiar with it.
</blockquote></details>

Scheduled sessions offline to talk about `conn_fsm`.
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 31 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuMlub3CKXzC9IO3fLh:-MuMtzfs-Bm2lzt1b3AZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb7abe71441745befb9dca8c81e72d3721e292b/pkg/sql/contention/txnidcache/txn_id_cache.go#L31)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think this TODO is necessarily true. Re-acquiring the RLock seems fine. I'd just delete this TODO. 
</blockquote></details>

Done.
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 179 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuMmCZj-8mUz2lGLC49:-MuMu47o7W1m5X9T0f3x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb7abe71441745befb9dca8c81e72d3721e292b/pkg/sql/contention/txnidcache/txn_id_cache.go#L179)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: how do you feel about pulling these into some helper closures:

```go
addBlockToStore := func(b *messageBlock) {
	t.mu.Lock()
	defer t.mu.Unlock()
	for blockIdx := range msgBlock {
		if !msgBlock[blockIdx].valid() {
			break
		}
		t.mu.store.Add(msgBlock[blockIdx].TxnID, msgBlock[blockIdx].TxnFingerprintID)
	}
} 
consumeBlock := func(b *messageBlock) {
	addBlockToStore(b)
	*b = messageBlock{}
	t.messageBlockPool.Put(b)
}
_ = stopper.RunAsyncTask(ctx, "txn-id-cache-ingest", func(ctx context.Context) {
	for {
		select {
		case msgBlock := <-t.msgChan:
			consumeBlock(msgBlock)
		case <-stopper.ShouldQuiesce():
			return
		}
	}
})
```
</blockquote></details>

Done.
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 222 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuMn62YEgNIsfJLZ9Bx:-MuMu6xo4HJUJm1MWPkp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb7abe71441745befb9dca8c81e72d3721e292b/pkg/sql/contention/txnidcache/txn_id_cache.go#L222)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think I'd do this. I'd block. Everything that might possibly lead to blocking here implies CPU overload for seemingly fast tasks. I think discarding these is a little bit crazy and I feel like on shutdown, weird stuff is going to happen. Instead what I'd do is make a channel that you'll close when the `Start` loop exits and `select` on it. 
</blockquote></details>

Done.
___
*[pkg/sql/contention/txnidcache/writer.go, line 20 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuMkpjd3lrzBkhbkd4H:-MuMuAeNBywMVkUk0As8:b-a7et68) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb7abe71441745befb9dca8c81e72d3721e292b/pkg/sql/contention/txnidcache/writer.go#L20)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My guess is that this is an order of magnitude more shards than you need. I don't have a strongly principled reason to say so beyond that Java's ConcurrentHashMap uses 16 shards and it does a good bit more under the mutex than you are here. How about 16 and a comment saying what I'm saying here and that empirically the number seems good enough. 
</blockquote></details>

Done. Seems like 16 is indeed good enough from the microbenchmark :sweat_smile: 

```
name                                    old time/op          new time/op          delta
ConcurrentSelect1/concurrentConn=24-24           413µs ±14%           431µs ±14%    ~     (p=0.393 n=10+10)
ConcurrentSelect1/concurrentConn=48-24          1.07ms ±17%          1.10ms ±14%    ~     (p=0.529 n=10+10)
ConcurrentSelect1/concurrentConn=64-24          1.97ms ±26%          2.08ms ±30%    ~     (p=0.393 n=10+10)

name                                    old overhead(ns/op)  new overhead(ns/op)  delta
ConcurrentSelect1/concurrentConn=24-24           2.97k ±16%           2.96k ± 6%    ~     (p=0.838 n=10+10)
ConcurrentSelect1/concurrentConn=48-24           4.22k ±11%           4.29k ±11%    ~     (p=0.720 n=9+10)
ConcurrentSelect1/concurrentConn=64-24           5.03k ±25%           4.54k ± 7%  -9.59%  (p=0.036 n=9+8)

name                                    old alloc/op         new alloc/op         delta
ConcurrentSelect1/concurrentConn=24-24           368kB ± 2%           373kB ± 1%  +1.28%  (p=0.019 n=10+10)
ConcurrentSelect1/concurrentConn=48-24           764kB ± 2%           771kB ± 2%    ~     (p=0.143 n=10+10)
ConcurrentSelect1/concurrentConn=64-24          1.07MB ± 4%          1.09MB ± 6%    ~     (p=0.143 n=10+10)

name                                    old allocs/op        new allocs/op        delta
ConcurrentSelect1/concurrentConn=24-24           3.35k ± 1%           3.42k ± 1%  +1.96%  (p=0.000 n=10+10)
ConcurrentSelect1/concurrentConn=48-24           6.88k ± 2%           6.99k ± 1%  +1.61%  (p=0.001 n=10+10)
ConcurrentSelect1/concurrentConn=64-24           9.46k ± 3%           9.66k ± 4%  +2.06%  (p=0.011 n=10+10)
```


<!-- Sent from Reviewable.io -->

2022-01-27 15:20 UTC, ajwerner reviewed
> Reviewed 2 of 24 files at r9, 1 of 7 files at r12, 3 of 7 files at r13, 2 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 193 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuR6LmoCA3KXPg2Fli4:-MuR6LmoCA3KXPg2Fli5:b-clzmg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8d139cfbb24384018dd6c9fed87616253c368fa/pkg/sql/contention/txnidcache/txn_id_cache.go#L193)):*
> ```Go
> 	}
> 
> 	_ = stopper.RunAsyncTask(ctx, "txn-id-cache-ingest", func(ctx context.Context) {
> ```

I think you need to detect the error here and close `t.closeCh`. Otherwise it seems possible for there to be a race where a flush routine is blocked and nothing will ever read it. 
___
*[pkg/ts/catalog/chart_catalog.go, line 1887 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuR6edR-3Poed_zdWRz:-MuR6edR-3Poed_zdWS-:bdcwfca) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8d139cfbb24384018dd6c9fed87616253c368fa/pkg/ts/catalog/chart_catalog.go#L1887)):*
> ```Go
> 			{
> 				Title:   "Evicted Resolved Transaction IDs",
> 				Metrics: []string{"sql.contention.txn_id_cache.evicted_count"},
> ```

is this actually a useful metric for anybody? I feel like the useful metric would be the miss rate and maybe the total number of reads. I can't imagine anybody ever using this. 


<!-- Sent from Reviewable.io -->

2022-01-27 15:21 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/ts/catalog/chart_catalog.go, line 1887 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuR6edR-3Poed_zdWRz:-MuR72hw31w9osr34BW0:bwe9qe4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8d139cfbb24384018dd6c9fed87616253c368fa/pkg/ts/catalog/chart_catalog.go#L1887)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

is this actually a useful metric for anybody? I feel like the useful metric would be the miss rate and maybe the total number of reads. I can't imagine anybody ever using this. 
</blockquote></details>

By miss rate, I guess I mean, misses and reads as two counters. From that you can compute rate. 


<!-- Sent from Reviewable.io -->

2022-01-27 20:15 UTC, Azhng reviewed
@andreimatei updated the `conn_fsm` to return `txnID` in the `advanceInfo`. I have a few questions below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-:-MuS9PUj4ufEB6dotLAx:b1hvgml)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor.go, line 1559 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuMbtcI8hlwu7FV6xAn:-MuS97xc-7Usm07xwgeJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abb7abe71441745befb9dca8c81e72d3721e292b/pkg/sql/conn_executor.go#L1559)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

at the very least call the new arg `prevTxnID`. But have you considered putting it inside `ev`?
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 1033 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuS9ae07caAyM3Vgj8c:-MuS9ae07caAyM3Vgj8d:bxcg4mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/59293eb47d6494b1eb187cafc87337cbb672e132/pkg/sql/conn_executor.go#L1033)):*
> ```Go
> 			// that we can write it to transaction ID cache later.
> 			// TODO(azhng): wip: question: should we consume the advanceInfo here?
> 			finishedTxnID = ex.state.adv.txnID
> ```

in `txnStateTransitionsApplyWrapper` we always consume the `advanceInfo` (`consumeAdvanceInfo()`) before reading from it. Should we still do the same here? 
___
*[pkg/sql/conn_executor.go, line 2268 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuSA7eQDMZ95Gg2xbkC:-MuSA7eQDMZ95Gg2xbkD:bvf29p5) ([raw file](https://github.com/cockroachdb/cockroach/blob/59293eb47d6494b1eb187cafc87337cbb672e132/pkg/sql/conn_executor.go#L2268)):*
> ```Go
> 		txnOpt = copyTxnOpt{
> 			resetExtraTxnState: func(ctx context.Context, txnID uuid.UUID) error {
> 				return ex.resetExtraTxnState(ctx, noEvent, txnID)
> ```

@andreimatei it seems like the `copyMachine` doesn't quite go through the same `conn_fsm` transitions. Do you mind taking a look at the integration point here too as well to see if this is correct? 
___
*[pkg/sql/contention/txnidcache/txn_id_cache.go, line 193 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuR6LmoCA3KXPg2Fli4:-MuS9BeA2wBx_GELmbT9:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8d139cfbb24384018dd6c9fed87616253c368fa/pkg/sql/contention/txnidcache/txn_id_cache.go#L193)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think you need to detect the error here and close `t.closeCh`. Otherwise it seems possible for there to be a race where a flush routine is blocked and nothing will ever read it. 
</blockquote></details>

Done. 
___
*[pkg/ts/catalog/chart_catalog.go, line 1887 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuR6edR-3Poed_zdWRz:-MuS9DB-6T302QjdA1em:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8d139cfbb24384018dd6c9fed87616253c368fa/pkg/ts/catalog/chart_catalog.go#L1887)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

By miss rate, I guess I mean, misses and reads as two counters. From that you can compute rate. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-28 00:08 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/txn_state.go, line 280 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT-S_d9KaYYq24nx10:-MuT-S_d9KaYYq24nx11:b-vs7f5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/txn_state.go#L280)):*
> ```Go
> 	if ts.mu.txn != nil {
> 		finishedTxnID = ts.mu.txn.ID()
> 	}
> ```

Hmm I'm a bit surprised by this, without the `if nil` check, the call to `ts.mu.txn.ID()` will result in nil pointer exception on the CI. Anyone knows why this would be the case :thinking: ? 


<!-- Sent from Reviewable.io -->

2022-01-28 00:11 UTC, Azhng commented
E.g. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x116e2fc]

goroutine 823 [running]:
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).ID(0xc00264d2f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:226 +0x3c
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).finishExternalTxn(0xc001254690)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/txn_state.go:278 +0x10a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close(0xc001254600, {0x4eeb9b8, 0xc00264d2f0}, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1045 +0xc5
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:214 +0x11c
created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:204 +0x5f1
```

2022-01-28 00:47 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor.go, line 1033 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuS9ae07caAyM3Vgj8c:-MuT2GNTDsajozJHilL3:b-1rhyxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/59293eb47d6494b1eb187cafc87337cbb672e132/pkg/sql/conn_executor.go#L1033)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

in `txnStateTransitionsApplyWrapper` we always consume the `advanceInfo` (`consumeAdvanceInfo()`) before reading from it. Should we still do the same here? 
</blockquote></details>

Yes. The `adv` field is not meant to be read directly.
___
*[pkg/sql/conn_executor.go, line 2268 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuSA7eQDMZ95Gg2xbkC:-MuT8Fk56z-6n5GL-Fq6:b-x3i3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/59293eb47d6494b1eb187cafc87337cbb672e132/pkg/sql/conn_executor.go#L2268)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

@andreimatei it seems like the `copyMachine` doesn't quite go through the same `conn_fsm` transitions. Do you mind taking a look at the integration point here too as well to see if this is correct? 
</blockquote></details>

I don't really know... But are these changes necessary? Wouldn't it be suitable to pass `emptyTxnID` to `resetExtraTxnState` here, particularly since we're passing in `noEvent` ?
___
*[pkg/sql/conn_executor_exec.go, line 1932 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT4yhiAJxKx442xkNC:-MuT4yhiAJxKx442xkND:b-y80qdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/conn_executor_exec.go#L1932)):*
> ```Go
> }
> 
> func (ex *connExecutor) onTxnFinish(ctx context.Context, ev txnEvent, prevTxnID uuid.UUID) {
> ```

seeing how much plumbing it required to take this `prevTxnID` here, I think a better option would have been to turn `txnEvent` into a
```
type txnEvent struct {
  eventType <enum>
  txnID UUID
}
```

I would also consider making the `txnID` optional and not passing it in in the closing cases. Just don't collect the data for those transactions; if the connection drops in the middle of a transaction, I doubt anybody will be interested in those fingerprints. Like, undo the changes to `finishExternalTxn()` - remove the return value.
___
*[pkg/sql/conn_fsm.go, line 512 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT6abW25yt1Vn8t_3C:-MuT6abW25yt1Vn8t_3D:bob72f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/conn_fsm.go#L512)):*
> ```Go
> func (ts *txnState) finishTxn(ev txnEvent) error {
> 	returnedTxnID := uuid.UUID{}
> 	finishedTxnID := ts.finishSQLTxn()
> ```

move this line inside the `if` block below
___
*[pkg/sql/conn_fsm.go, line 514 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT7TQq7RZ9qkKok69s:-MuT7TQq7RZ9qkKok69t:b-4o56yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/conn_fsm.go#L514)):*
> ```Go
> 	finishedTxnID := ts.finishSQLTxn()
> 
> 	// Only set the txnID field in the advanceInfo if the txnEvent is either
> ```

would anything go wrong if you blindly filled in the `txnID`, even for `noEvent`? If you can get away with it, I'd consider doing it to get rid of the need for this comment.
___
*[pkg/sql/txn_state.go, line 151 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT2z8rA-4TrmWJIFYS:-MuT2z8rA-4TrmWJIFYT:b-6lsgrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/txn_state.go#L151)):*
> ```Go
> //   (unless otherwise specified).
> // tranCtx: A bag of extra execution context.
> // This function returns the ID of the new transaction.
> ```

s/This function//

And move this above the parameters.
___
*[pkg/sql/txn_state.go, line 209 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT38F--vC7HxFQBsv5:-MuT38F--vC7HxFQBsv6:b3f6grj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/txn_state.go#L209)):*
> ```Go
> 		ts.mu.txn = txn
> 	}
> 	txnID = ts.mu.txn.ID()
> ```

why do we need the `txnID` variable?
___
*[pkg/sql/txn_state.go, line 280 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT-S_d9KaYYq24nx10:-MuT3hC2Dy6PZniMH8Yx:bclnprl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/txn_state.go#L280)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm I'm a bit surprised by this, without the `if nil` check, the call to `ts.mu.txn.ID()` will result in nil pointer exception on the CI. Anyone knows why this would be the case :thinking: ? 
</blockquote></details>

I think because of [this transition](https://github.com/cockroachdb/cockroach/blob/b1381aa9a779051c0a89af1d01142a150cefc0b9/pkg/sql/conn_fsm.go#L491), no?
Looks like this `finishExternalTxn()` is called regardless of whether the txn had been previously finished.


<!-- Sent from Reviewable.io -->

2022-01-28 21:25 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor.go, line 2268 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuSA7eQDMZ95Gg2xbkC:-MuXXxzzDUTU4YXkJmmq:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/59293eb47d6494b1eb187cafc87337cbb672e132/pkg/sql/conn_executor.go#L2268)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't really know... But are these changes necessary? Wouldn't it be suitable to pass `emptyTxnID` to `resetExtraTxnState` here, particularly since we're passing in `noEvent` ?
</blockquote></details>

Good point. Done.
___
*[pkg/sql/conn_executor_exec.go, line 1932 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT4yhiAJxKx442xkNC:-MuXY28b-foDswTi9tNU:b-7vs34m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/conn_executor_exec.go#L1932)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

seeing how much plumbing it required to take this `prevTxnID` here, I think a better option would have been to turn `txnEvent` into a
```
type txnEvent struct {
  eventType <enum>
  txnID UUID
}
```

I would also consider making the `txnID` optional and not passing it in in the closing cases. Just don't collect the data for those transactions; if the connection drops in the middle of a transaction, I doubt anybody will be interested in those fingerprints. Like, undo the changes to `finishExternalTxn()` - remove the return value.
</blockquote></details>

Done. Also not passing `txnID` in the closing case.
___
*[pkg/sql/conn_fsm.go, line 514 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT7TQq7RZ9qkKok69s:-MuXYO5b5E3O-v2O1F8u:bgv2g0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/conn_fsm.go#L514)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

would anything go wrong if you blindly filled in the `txnID`, even for `noEvent`? If you can get away with it, I'd consider doing it to get rid of the need for this comment.
</blockquote></details>

Done. Filling in `txnID` unconditionally.
___
*[pkg/sql/txn_state.go, line 151 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT2z8rA-4TrmWJIFYS:-MuXYX7bAVYugB6Rpzqc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/txn_state.go#L151)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/This function//

And move this above the parameters.
</blockquote></details>

Done.
___
*[pkg/sql/txn_state.go, line 209 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT38F--vC7HxFQBsv5:-MuXY_0FEqgJ0yfxIz02:brurwt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/txn_state.go#L209)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why do we need the `txnID` variable?
</blockquote></details>

This is because here we are reading `ts.mu.txn.ID()` while we are holding the mutex. We need to have access to this variable to return after we release the mutex a few lines later. 
___
*[pkg/sql/txn_state.go, line 280 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT-S_d9KaYYq24nx10:-MuXYtNk0kba6262t3Fw:b-oots7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/txn_state.go#L280)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think because of [this transition](https://github.com/cockroachdb/cockroach/blob/b1381aa9a779051c0a89af1d01142a150cefc0b9/pkg/sql/conn_fsm.go#L491), no?
Looks like this `finishExternalTxn()` is called regardless of whether the txn had been previously finished.
</blockquote></details>

Ah makes sense. 


<!-- Sent from Reviewable.io -->

2022-01-31 17:13 UTC, andreimatei reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  for the changes around the conn_executor

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-:-Mul7-r55PACJdwtNHrN:b-13sh9k)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @Azhng, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor_exec.go, line 1982 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mul4Ls52MmiJnUgUxT2:-Mul4Ls52MmiJnUgUxT3:b76uok3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f44c694773c7f3d643108e91594f9484a669d058/pkg/sql/conn_executor_exec.go#L1982)):*
> ```Go
> }
> 
> func (ex *connExecutor) recordTransaction(
> ```

not your code, but pls take the opportunity to put a comment on this method. Also explain the `ev` parameter.
We have a `recordTransactionStart()`; should this one be called `recordTransactionFinish()`? If so, and these methods are related, consider also putting their code next to each other in a new commit.
___
*[pkg/sql/txn_state.go, line 209 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-MuT38F--vC7HxFQBsv5:-Mul6Ge23gL4YAiOcTk3:btdsfzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ca62738efec98cb5b20ab46e9b226fef17578dc/pkg/sql/txn_state.go#L209)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

This is because here we are reading `ts.mu.txn.ID()` while we are holding the mutex. We need to have access to this variable to return after we release the mutex a few lines later. 
</blockquote></details>

I see.
___
*[pkg/sql/txn_state.go, line 360 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mul6Q1r0Xd3WRW9qVNu:-Mul6Q1r0Xd3WRW9qVNv:bsdb6uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f44c694773c7f3d643108e91594f9484a669d058/pkg/sql/txn_state.go#L360)):*
> ```Go
> 	// with a SQL transaction (other than the state encapsulated in TxnState; e.g.
> 	// schema changes and portals).
> 	eventTyp txnEventType
> ```

a particular reason why this is not called `eventType` ?
___
*[pkg/sql/txn_state.go, line 362 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mul6aqw5fsokUU9kDa2:-Mul6aqw5fsokUU9kDa3:bn3qye2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f44c694773c7f3d643108e91594f9484a669d058/pkg/sql/txn_state.go#L362)):*
> ```Go
> 	eventTyp txnEventType
> 
> 	// txnID is filled when transaction starts, commits or aborts.
> ```

when _a_ transaction


<!-- Sent from Reviewable.io -->

2022-01-31 18:47 UTC, Azhng reviewed
@ajwerner do you mind to take another look? :pray: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-:-MulSU-d-djsc7bw6H_g:b-7n768k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @andreimatei, @maryliag, and @nvanbenschoten)

___
*[pkg/sql/conn_executor_exec.go, line 1982 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mul4Ls52MmiJnUgUxT2:-MulSGde37RKrweGi8Vf:b9lvhqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f44c694773c7f3d643108e91594f9484a669d058/pkg/sql/conn_executor_exec.go#L1982)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

not your code, but pls take the opportunity to put a comment on this method. Also explain the `ev` parameter.
We have a `recordTransactionStart()`; should this one be called `recordTransactionFinish()`? If so, and these methods are related, consider also putting their code next to each other in a new commit.
</blockquote></details>

Done. Moved the code in the new commit.
___
*[pkg/sql/txn_state.go, line 360 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mul6Q1r0Xd3WRW9qVNu:-MulSPuBBeEKEZSWDTCH:b66ad6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f44c694773c7f3d643108e91594f9484a669d058/pkg/sql/txn_state.go#L360)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

a particular reason why this is not called `eventType` ?
</blockquote></details>

Done. Changed to `eventType`. 
___
*[pkg/sql/txn_state.go, line 362 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-Mul6aqw5fsokUU9kDa2:-MulSSJi4irODsbq59_L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f44c694773c7f3d643108e91594f9484a669d058/pkg/sql/txn_state.go#L362)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

when _a_ transaction
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-01 19:36 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74115#-:-MuqmXVs2pzSvuidDKn-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @andreimatei, @maryliag, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-02-01 19:37 UTC, Azhng commented
Thank you everyone for the detailed reviews!

bors r+

2022-02-01 22:30 UTC, merged