sql: check quivalent constraint when creating hash index
cockroachdb/cockroach pull request #74179
Opened 2021-12-21 23:03 UTC by chengxiong-ruan

Fixes #68031

Previously we only try to create constraint for shard column if
it's newly created. We check duplicate constraint for shard
column when `Alter Primary Key` and `Create Index`, however the
check is simply a name check. This pr adds logic to check
equivalent constraint by checking if the formatted expression
string is the same.

Release not (sql change): Shard column constraint is not visible
any more. Creating a hash index would make sure the constraint is
created not matter there's a existing or user defined equivalent
column.

2021-12-21 23:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74179)
<!-- Reviewable:end -->

2021-12-22 04:42 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74179)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/create_table.go, line 1645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-MrVO6M33TO4gjp2ZYhI:-MrVO6M33TO4gjp2ZYhJ:b-lzja9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc13e138efc4b44c4b5b35b1096dc129a23018a2/pkg/sql/create_table.go#L1645)):*
> ```Go
> 				}
> 				if checkConstraintDesc.Expr == inputCheckConstraintDesc.Expr {
> 					inputCheckConstraint.Hidden = true
> ```

I kept questioning myself why we want to make a user defined constraint hidden.

I think my answer is that we may want to have a consistent `SHOW CREATE` experience for tables with hash sharded index, and it should be super rare that a super smart user defined a equivalent constraint for a shard column if we don't show the constraint at all >_> But if there would be a super smart user, showing the constraint would give them a chance to drop the constraint, do we want that? Dropping the constraint in this case could be fine since we trust the shard column so much that we skip validation during backfill already. The only thing is how optimizer gonna feel, I think it's also fine since it's user's choice.

However step back a bit I also questioned myself, why do we need all these equivalent constraint check at all. Why can't we just try to create the constraint anyway without checking? In this case, if a smart user defined an exactly same constraint, it would fail due to duplicated constraint. I think it's also an ok experience for user and this whole block of code would be gone.
___
*[pkg/sql/show_create_clauses.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-MrVMCcnAKlMNRjiG8rQ:-MrVMCco-v4xuWkCwU7a:bh6kiai) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc13e138efc4b44c4b5b35b1096dc129a23018a2/pkg/sql/show_create_clauses.go#L566)):*
> ```Go
> ) error {
> 	for _, e := range desc.AllActiveAndInactiveChecks() {
> 		if e.Hidden {
> ```

Let me know if you have a strong feeling that it should be in a separate PR.


<!-- Sent from Reviewable.io -->

2022-01-10 21:48 UTC, postamar reviewed
I took a look at this. Please bear in mind that my review is very superficial. I didn't find anything obviously wrong in this PR. You should probably have someone more knowledgeable take a look. Please bear in mind that it's OK to annoy people for reviews :+1: 

> Reviewed 1 of 8 files at r1, 1 of 4 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-:-Mt4xQHM8zZO419ZZpT-:bxg2iqu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt4t4qw0Cr-COrn5WLM):*
s/quivalent/equivalent/
___
*[-- commits, line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt4tall6TGFNtCBtY7g):*
Can you please reword this sentence?
___
*[pkg/sql/create_table.go, line 1645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-MrVO6M33TO4gjp2ZYhI:-Mt4vyNb3lLHa8KgmMDm:b-5w7mug) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc13e138efc4b44c4b5b35b1096dc129a23018a2/pkg/sql/create_table.go#L1645)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I kept questioning myself why we want to make a user defined constraint hidden.

I think my answer is that we may want to have a consistent `SHOW CREATE` experience for tables with hash sharded index, and it should be super rare that a super smart user defined a equivalent constraint for a shard column if we don't show the constraint at all >_> But if there would be a super smart user, showing the constraint would give them a chance to drop the constraint, do we want that? Dropping the constraint in this case could be fine since we trust the shard column so much that we skip validation during backfill already. The only thing is how optimizer gonna feel, I think it's also fine since it's user's choice.

However step back a bit I also questioned myself, why do we need all these equivalent constraint check at all. Why can't we just try to create the constraint anyway without checking? In this case, if a smart user defined an exactly same constraint, it would fail due to duplicated constraint. I think it's also an ok experience for user and this whole block of code would be gone.
</blockquote></details>

I may be wrong here, and I don't understand any of this too deeply, however I believe that anything that has `crdb_internal` in its name is assumed to not have been created by a user. This isn't enforced anywhere, but it is a convention.

I believe the goal here is that we want the output of a `SHOW CREATE TABLE` statement for a hash-sharded table to round-trip correctly. In other words, that executing the resulting `CREATE TABLE` statement would produce the same table.

I may be completely wrong here.
___
*[pkg/sql/create_table.go, line 1623 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt4v2Pk97RyVcJo-_kP:-Mt4v2Pk97RyVcJo-_kQ:b-5k5tor) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac4cb86a5714e3f11b31fbf668aa01945f4a6bb/pkg/sql/create_table.go#L1623)):*
> ```Go
> 		}
> 
> 		// if there is an equivalent check constraint from the CREATE TABLE (should be rare since we hide the constraint of shard column)
> ```

style: comments should wrap around at the 80th character column


<!-- Sent from Reviewable.io -->

2022-01-11 03:11 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74179)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[pkg/sql/create_index.go, line 237 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt64TMq00pI7u4pCHbH:-Mt64TMq00pI7u4pCHbI:b-v0zjxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac4cb86a5714e3f11b31fbf668aa01945f4a6bb/pkg/sql/create_index.go#L237)):*
> ```Go
> 		}
> 		columns = newColumns
> 		if err := params.p.maybeSetupConstraintForShard(params.ctx, tableDesc, shardCol, indexDesc.Sharded.ShardBuckets); err != nil {
> ```

nit: wrap this after `maybeSetupConstraintForShard(`

```go
if err := params.p.maybeSetupConstraintForShard(
	params.ctx, tableDesc, shardCol, indexDesc.Sharded.ShardBuckets,
); err != nil {
```
___
*[pkg/sql/create_index.go, line 476 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt65fCADR1uJ1sYBhpU:-Mt65fCADR1uJ1sYBhpV:bnniurx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac4cb86a5714e3f11b31fbf668aa01945f4a6bb/pkg/sql/create_index.go#L476)):*
> ```Go
> 
> // setupShardedIndex creates a shard column for the given index descriptor. It
> // returns the shard column and the new column list for the index If the shard
> ```

nit: missing period. Can you say "is new, it is added to the tableDesc as a mutation in DELETE_ONLY"?
___
*[pkg/sql/create_table.go, line 1645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-MrVO6M33TO4gjp2ZYhI:-Mt663FP4G5ev_ktVxs_:b-n5zl5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc13e138efc4b44c4b5b35b1096dc129a23018a2/pkg/sql/create_table.go#L1645)):*
> The only thing is how optimizer gonna feel, I think it's also fine since it's user's choice.

The optimizer is going to feel sad. It absolutely relies on the constraint. If a user drops it, I'm inclined to not care that much. Alternatively, one rather dire thing we could do is fail validation if we're missing the check constraint. If we do that, we should also add code to disallow the user from dropping it. 

> I believe the goal here is that we want the output of a SHOW CREATE TABLE statement for a hash-sharded table to round-trip correctly. In other words, that executing the resulting CREATE TABLE statement would produce the same table.

This is definitely a goal. 
___
*[pkg/sql/show_create_clauses.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-MrVMCcnAKlMNRjiG8rQ:-Mt66VBP1945m4k05NNy:b-8bwxv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc13e138efc4b44c4b5b35b1096dc129a23018a2/pkg/sql/show_create_clauses.go#L566)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Let me know if you have a strong feeling that it should be in a separate PR.
</blockquote></details>

I'm happy with this. 


<!-- Sent from Reviewable.io -->

2022-01-11 21:50 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74179)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt4t4qw0Cr-COrn5WLM):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

s/quivalent/equivalent/
</blockquote></details>

Done.
___
*[-- commits, line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt4tall6TGFNtCBtY7g):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Can you please reword this sentence?
</blockquote></details>

Reworded. Let me know if you're happy with it.
___
*[pkg/sql/create_index.go, line 476 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt65fCADR1uJ1sYBhpU:-MtA6NlX0B9ldHdY4B3r:b-283gmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac4cb86a5714e3f11b31fbf668aa01945f4a6bb/pkg/sql/create_index.go#L476)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: missing period. Can you say "is new, it is added to the tableDesc as a mutation in DELETE_ONLY"?
</blockquote></details>

Done. It actually has two different cases.
___
*[pkg/sql/create_table.go, line 1623 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt4v2Pk97RyVcJo-_kP:-MtA6X2tCjmIVCbbRAaq:b-zdu3nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac4cb86a5714e3f11b31fbf668aa01945f4a6bb/pkg/sql/create_table.go#L1623)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

style: comments should wrap around at the 80th character column
</blockquote></details>

Done, thanks for catching this~


<!-- Sent from Reviewable.io -->

2022-01-11 22:00 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74179)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 805 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-MtA8juV1W8wdX90p-IG:-MtA8juV1W8wdX90p-IH:bxb3ml8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bfea0fd2c21f1d136b78b16409ac6aa6c55d392/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L805)):*
> ```
>     CONSTRAINT t_pkey PRIMARY KEY (a ASC) USING HASH WITH BUCKET_COUNT = 8,
>     FAMILY "primary" (a)
> )
> ```

I feel like this test is setting out to demonstrate that the table created from show create also gets a good plan. That's nice and what you want, but I think it can be done more elegantly. Also, please comment the intention of the test.

Copy the statement to a variable
```sql
let $create_statement
SELECT create_statement FROM [SHOW CREATE TABLE t]
```

Use the statement
```
statement ok
$create_statement
```



_Code quote:_
```

SELECT @2 FROM [SHOW CREATE TABLE t]
----
CREATE TABLE public.t (
    crdb_internal_a_shard_8 INT4 NOT VISIBLE NOT NULL AS (mod(fnv32(crdb_internal.datums_to_bytes(a)), 8:::INT8)) VIRTUAL,
    a INT8 NOT NULL,
    CONSTRAINT t_pkey PRIMARY KEY (a ASC) USING HASH WITH BUCKET_COUNT = 8,
    FAMILY "primary" (a)
)
```


<!-- Sent from Reviewable.io -->

2022-01-11 23:42 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74179)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 805 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-MtA8juV1W8wdX90p-IG:-MtAPYUi8m3NMhyvh2do:b-hn192n) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bfea0fd2c21f1d136b78b16409ac6aa6c55d392/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L805)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like this test is setting out to demonstrate that the table created from show create also gets a good plan. That's nice and what you want, but I think it can be done more elegantly. Also, please comment the intention of the test.

Copy the statement to a variable
```sql
let $create_statement
SELECT create_statement FROM [SHOW CREATE TABLE t]
```

Use the statement
```
statement ok
$create_statement
```
</blockquote></details>

nice, thanks for suggesting that


<!-- Sent from Reviewable.io -->

2022-01-12 16:08 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 8 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-:-MtE1yLODXzfrCv-Rojk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[-- commits, line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt4tall6TGFNtCBtY7g):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Reworded. Let me know if you're happy with it.
</blockquote></details>

I still think the docs writers will struggle with this. Consider:

```
  Release note (sql change): Before this change, the check constraint on shard
  columns used by hash sharded index was printed in the corresponding
  `SHOW CREATE TABLE`. The constraint had been shown because cockroach
  lacked logic to ensure that such a constraint always exists for shard columns.
  The database now ensures that shard columns which are part of hash sharded
  indexes always have the corresponding check constraint which the optimizer relies
  on to achieve properly optimized query plans on hash sharded indexes. We no
  longer display this constraint in `SHOW CREATE TABLE` as it is now implied by
  the `USING HASH` clause on the relevant index.
```
___
*[-- commits, line 11 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-MtE0N8t3aUuvDiMRefJ):*
Grammar nits:

>   constraint no matter **if** a shard column is newly created or not. With



_Code quote:_
```
  string is the same. With this logic we can try to create the
  constraint no matter a shard column is newly created or not. With
```
___
*[-- commits, line 15 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-MtE0y-D7Nc97vp4wfUJ):*
created, or skipp**ed** if one already exists


<!-- Sent from Reviewable.io -->

2022-01-12 19:04 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74179)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)

___
*[-- commits, line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74179#-Mt4tall6TGFNtCBtY7g):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I still think the docs writers will struggle with this. Consider:

```
  Release note (sql change): Before this change, the check constraint on shard
  columns used by hash sharded index was printed in the corresponding
  `SHOW CREATE TABLE`. The constraint had been shown because cockroach
  lacked logic to ensure that such a constraint always exists for shard columns.
  The database now ensures that shard columns which are part of hash sharded
  indexes always have the corresponding check constraint which the optimizer relies
  on to achieve properly optimized query plans on hash sharded indexes. We no
  longer display this constraint in `SHOW CREATE TABLE` as it is now implied by
  the `USING HASH` clause on the relevant index.
```
</blockquote></details>

Thank you!


<!-- Sent from Reviewable.io -->

2022-01-12 20:30 UTC, chengxiong-ruan commented
bors r+

2022-01-12 20:31 UTC, chengxiong-ruan commented
TFTR!

2022-01-12 22:18 UTC, merged