opt: ignore shard columns when selecting arbiters
cockroachdb/cockroach pull request #74235
Opened 2021-12-23 05:28 UTC by chengxiong-ruan

Fixes #60829

Previously, we failed to select hash sharded unique indexes
as arbiters because there's an extra shard column ordinal
and input does not consider shard columns. This pr excludes
when matching for a unique index arbiter.

Release note: None

2021-12-23 05:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74235)
<!-- Reviewable:end -->

2022-01-04 14:59 UTC, mgartner requested changes
One thing I'm not sold on here is that we are making the optimizer aware specifically of hash-sharded indexes. This seems counter-productive to making hash-sharded indexes syntactic sugar for an index with a virtual computed column. As the implementation of hash-sharded indexes creeps deeper into the system internals, it becomes less like syntactic sugar.

That being said, the optimize must have some knowledge that the hash column is special and can be ignored when determining arbiter indexes. One alternative would be to generalize this by replacing `HasShardedColumn` with `ImplicitConflictKeyColumnCount` which returns the number of prefix key columns in the index that can be ignored for arbiter resolution: 0 for non-hash-sharded indexes and 1 for hash-sharded indexes. This would ensure that the optimizer remains blissfully unaware of hash-sharded indexes. I'm not sure if the generalization would ever be used by another form of index, but reusability might be another benefit too.

For this alternative, we would need some way in testcat to create an index with these implicit prefix columns. I think encoding the number of implicit conflict key columns in the index name would work, and we already have some precedent for this. See https://github.com/cockroachdb/cockroach/blob/8a9e560fd4ac8489485c87a266e99e4f1a852deb/pkg/sql/opt/testutils/testcat/testdata/table#L299 and https://github.com/cockroachdb/cockroach/blob/36d3f237180c1c385e82a56e6a313fe08b76e223/pkg/sql/opt/testutils/testcat/create_table.go#L1174-L1179. For example, something like `idx:implicit_conflict_cols:2` would indicate mean that the first two key columns can be ignored during arbiter ON CONFLICT resolution.

> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-Ms_Y45OC-GZrsUrtFdv:b-7544zn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[pkg/sql/opt_catalog.go, line 1335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Ms_UlrY4yl6DG42GWfG:-Ms_UlrY4yl6DG42GWfH:b-ymls6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e232eae947e04a8e12a374fbdf46571889c92dbf/pkg/sql/opt_catalog.go#L1335)):*
> ```Go
> 		oi.isSharded = true
> 		for ord := 0; ord < idx.NumKeyColumns(); ord++ {
> 			if idx.GetKeyColumnName(ord) == idx.GetShardColumnName() {
> ```

Relying on column names seems more fragile than IDs. Also, the shard column is always the first in key column in the index, correct? I think you could simplify this to something like:

```go
if idx.IsSharded() {
    oi.isSharded = true
    // The shard column is always the first key column of the index.
    oi.shardColOrdinal = oid.tab.lookupColumnOrdinal(idx.GetKeyColumnID(0 /* columnOrdinal */)
}
```
___
*[pkg/sql/opt/cat/index.go, line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Ms_VbWLAVJQRggD9p_d:-Ms_VbWMEZfoLnK_tjdM:b37qr9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e232eae947e04a8e12a374fbdf46571889c92dbf/pkg/sql/opt/cat/index.go#L198)):*
> ```Go
> 	// HasShardColumn returns a column ordinal corresponding to a hash shard
> 	// column and true if such a column exists. Otherwise, false is returned.
> 	HasShardColumn() (int, bool)
> ```

Can you follow the pattern for inverted indexes in this interface and split this to two functions `IsSharded() bool` and `ShardColumn() IndexColumn` where the latter panics if the index is not a sharded index.
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 718 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Ms_XVzrBwDaI1aICIxO:-Ms_XVzrBwDaI1aICIxP:b-g4r37x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e232eae947e04a8e12a374fbdf46571889c92dbf/pkg/sql/opt/testutils/testcat/create_table.go#L718)):*
> ```Go
> 
> 	// Add shard column if sharded.
> 	if def.Sharded != nil {
> ```

You can should add some hash sharded indexes to the testcat tests here: https://github.com/cockroachdb/cockroach/blob/36d3f237180c1c385e82a56e6a313fe08b76e223/pkg/sql/opt/testutils/testcat/testdata/index


<!-- Sent from Reviewable.io -->

2022-01-06 03:02 UTC, rytaft reviewed
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-insert, line 1580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MshJUgs-dEuS44iPzf2:-MshJUgs-dEuS44iPzf3:b57i2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e232eae947e04a8e12a374fbdf46571889c92dbf/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L1580)):*
> ```
>                           └── (i:42 != uniq_computed_pk.i:33) OR (c_i_expr:45 != uniq_computed_pk.c_i_expr:36)
> 
> exec-ddl
> ```

I don't think this file is the right place for this test, since the purpose of this file is to check that we are building uniqueness checks correctly for `UNIQUE WITHOUT INDEX` constraints. I think you'll want to put this in the `insert` or `upsert` test file.


<!-- Sent from Reviewable.io -->

2022-01-06 16:38 UTC, ajwerner reviewed
Another more advanced proposal which I'd like us to entertain is that if a column is an immutable computed expression of the other columns in a unique constraint, then the other columns also form a unique constraint. What do you think about building that rule? Like:

<img src="https://latex.codecogs.com/svg.image?\\U:&space;\textup{Set&space;of&space;columns&space;in&space;unique&space;constraint.}&space;\\\textup{ExprColumns}(c):&space;\textup{Set&space;of&space;columns&space;used&space;in&space;computed&space;expression&space;for&space;column&space;c}.&space;\\E_U:&space;\textup{Set&space;of&space;equivalent&space;unique&space;constraints&space;of&space;}&space;U.&space;\\E_U&space;=&space;\{&space;\\&space;\indent&space;&space;S&space;\in&space;\wp(U):&space;(\exists&space;C)[&space;\\&space;\indent&space;\indent&space;C&space;\in&space;\wp(U),&space;&space;\\&space;\indent&space;\indent&space;C&space;\cap&space;E_U&space;=&space;\emptyset,&space;\\&space;\indent&space;\indent&space;(\forall&space;c&space;\in&space;C)[&space;\\&space;\indent&space;\indent&space;\indent&space;c&space;\textup{&space;is&space;a&space;computed&space;column},&space;\\&space;\indent&space;\indent&space;\indent&space;(\exists&space;D&space;\in&space;\wp&space;(S))[\textup{ExprColumns}(c)&space;=&space;D]&space;\\&space;\indent&space;\indent]&space;\\&space;\indent&space;]&space;\\&space;\}&space;" title="\\U: \textup{Set of columns in unique constraint.} \\\textup{ExprColumns}(c): \textup{Set of columns used in computed expression for column c}. \\E_U: \textup{Set of equivalent unique constraints of } U. \\E_U = \{ \\ \indent S \in \wp(U): (\exists C)[ \\ \indent \indent C \in \wp(U), \\ \indent \indent C \cap E_U = \emptyset, \\ \indent \indent (\forall c \in C)[ \\ \indent \indent \indent c \textup{ is a computed column}, \\ \indent \indent \indent (\exists D \in \wp (S))[\textup{ExprColumns}(c) = D] \\ \indent \indent] \\ \indent ] \\ \} " />

I really hacked the latex
```latex
\\
U: \textup{Set of columns in unique constraint.} \\
\textup{ExprColumns}(c): \textup{Set of columns used in computed expression for column c}. \\
E_U: \textup{Set of equivalent unique constraints of } U. \\
E_U = \{ \\
 \indent  S \in \wp(U): (\exists C)[ \\
 \indent \indent C \in \wp(U),  \\
 \indent \indent C \cap E_U = \emptyset, \\
 \indent \indent (\forall c \in C)[ \\
 \indent \indent \indent c \textup{ is a computed column}, \\
 \indent \indent \indent (\exists D \in \wp (S))[\textup{ExprColumns}(c) = D] \\
 \indent \indent] \\
 \indent ] \\ 
\} 
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-Msk-Fl46Koa_L4A-m-n:b-d40aiq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @rytaft)



<!-- Sent from Reviewable.io -->

2022-01-06 18:43 UTC, rytaft commented
I think we already do what you're suggesting to determine unique constraints from functional dependencies here:
https://github.com/cockroachdb/cockroach/blob/5487f8b98f381ab37225bcf757e6cc4b94e975f3/pkg/sql/opt/memo/logical_props_builder.go#L1741

Perhaps the question is whether we should allow using unique constraints from functional dependencies as arbiters. I'm not sure whether or not that's a good idea, since I think that may have some unintended consequences.





<!-- Sent from Reviewable.io -->

2022-01-06 18:46 UTC, ajwerner commented
> I'm not sure whether or not that's a good idea, since I think that may have some unintended consequences.

What sort of unintended consequences do you have in mind? Is there a simplified version of the same idea you'd feel better about?

2022-01-06 18:59 UTC, rytaft commented
I'm struggling to think of a specific example, but I think we want our arbiters to be specific enforceable constraints defined on the schema. One possible solution is to treat unique hash indexes like we treat implicitly partitioned unique indexes, and add a fake "UNIQUE WITHOUT INDEX" constraint in the opt_catalog. Maybe that's where @mgartner was going with the `ImplicitConflictKeyColumnCount` method, which is similar to the `ImplicitPartitioningColumnCount` method used for implicitly partitioned indexes.





<!-- Sent from Reviewable.io -->

2022-01-06 20:51 UTC, ajwerner commented
Sorry, what you're saying makes total sense. We can't just go and create new arbiter via functional dependencies. Postgres doesn't support it. I like what y'all are thinking regarding implicit columns. Sorry for the noise.

2022-01-06 21:00 UTC, mgartner reviewed
You'll also want to add tests here to verify that the query plans are efficient. They should use the hash-sharded arbiter index to check for conflicts. I do not believe that is the case currently, and you'll probably need to make some changes in the follow code to make sure there is an equality condition for the shard column:

https://github.com/cockroachdb/cockroach/blob/6b1668e69e142a4795db94604c4a9f36297c91b4/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L232-L249

https://github.com/cockroachdb/cockroach/blob/6b1668e69e142a4795db94604c4a9f36297c91b4/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L320-L335

2022-01-06 21:49 UTC, mgartner commented
Forgot to mention in my last comment, that tests for the query plans can go here: https://github.com/cockroachdb/cockroach/blob/452515ef8bc5b82bea02d0a7690060c75673cb7e/pkg/sql/opt/exec/execbuilder/testdata/upsert

> One possible solution is to treat unique hash indexes like we treat implicitly partitioned unique indexes, and add a fake "UNIQUE WITHOUT INDEX" constraint in the opt_catalog. Maybe that's where @mgartner was going with the ImplicitConflictKeyColumnCount method, which is similar to the ImplicitPartitioningColumnCount method used for implicitly partitioned indexes.

This is basically what I was suggesting, but instead of adding new syntax I suggested hacking with column names in the test catalog. I don't think we need a new syntax for logic tests because we can create hash sharded indexes to exercise the new code paths.

> Sorry, what you're saying makes total sense. We can't just go and create new arbiter via functional dependencies. Postgres doesn't support it. I like what y'all are thinking regarding implicit columns. Sorry for the noise.

I think the idea has merit, though. I wouldn't consider it "creating new arbiters", but rather, "expanding the eligible arbiters for a set of conflict columns". And there is _some_ similar precedent in Postgres with unique partial indexes where arbiters can be selected without matching "specific enforceable constraints defined on the schema". Below, notice how the `ON CONFLICT .. WHERE` clause doesn't exactly match the partial index `WHERE` clause, but the former implies the latter.

```
marcus=# CREATE TABLE t (a INT, b INT);
CREATE TABLE

marcus=# CREATE UNIQUE INDEX ON t (a) WHERE b > 0;
CREATE INDEX

marcus=# EXPLAIN INSERT INTO t VALUES (1) ON CONFLICT (a) WHERE b > 1 DO NOTHING;
                   QUERY PLAN
------------------------------------------------
 Insert on t  (cost=0.00..0.01 rows=0 width=0)
   Conflict Resolution: NOTHING
   Conflict Arbiter Indexes: t_a_idx
   ->  Result  (cost=0.00..0.01 rows=1 width=8)
(4 rows)
```

2022-01-06 22:01 UTC, rytaft commented
I wasn't suggesting adding new syntax -- just suggesting that they do something like this:
https://github.com/cockroachdb/cockroach/blob/7e3a3e25dd70d9a12afdd441969ef303a207ca32/pkg/sql/opt_catalog.go#L833





<!-- Sent from Reviewable.io -->

2022-01-06 22:25 UTC, mgartner commented
Oh that's a good idea. Then optimizer changes might not be necessary at all. I am concerned that the query plan won't use the hash-sharded index to check for conflicts if and equality condition for the shard column is not added to the join conditions created in `buildAntiJoinForDoNothingArbiter` and `buildLeftJoinForUpsertArbiter`. Adding `execbuilder` tests like [I mentioned above](https://github.com/cockroachdb/cockroach/pull/74235#pullrequestreview-846063936) would be the best way to tell.

2022-01-12 18:32 UTC, chengxiong-ruan reviewed
Thanks for the suggestion! It turns out the simplest to just add the unique without index constraint magic :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-MtEYUly6fzmqqN-NiUF:b-sbolez)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt_catalog.go, line 1335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Ms_UlrY4yl6DG42GWfG:-MtEYs272rsSJR_Vyz68:b36aqcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e232eae947e04a8e12a374fbdf46571889c92dbf/pkg/sql/opt_catalog.go#L1335)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Relying on column names seems more fragile than IDs. Also, the shard column is always the first in key column in the index, correct? I think you could simplify this to something like:

```go
if idx.IsSharded() {
    oi.isSharded = true
    // The shard column is always the first key column of the index.
    oi.shardColOrdinal = oid.tab.lookupColumnOrdinal(idx.GetKeyColumnID(0 /* columnOrdinal */)
}
```
</blockquote></details>

Done since not relevant anymore :)
___
*[pkg/sql/opt/cat/index.go, line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Ms_VbWLAVJQRggD9p_d:-MtEYxr08riofROnrHoE:b36aqcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e232eae947e04a8e12a374fbdf46571889c92dbf/pkg/sql/opt/cat/index.go#L198)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you follow the pattern for inverted indexes in this interface and split this to two functions `IsSharded() bool` and `ShardColumn() IndexColumn` where the latter panics if the index is not a sharded index.
</blockquote></details>

Done since not relevant anymore :)
___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-insert, line 1580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MshJUgs-dEuS44iPzf2:-MtEYzNn-Wi4smD1fjnA:b-dygl7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e232eae947e04a8e12a374fbdf46571889c92dbf/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L1580)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think this file is the right place for this test, since the purpose of this file is to check that we are building uniqueness checks correctly for `UNIQUE WITHOUT INDEX` constraints. I think you'll want to put this in the `insert` or `upsert` test file.
</blockquote></details>

test moved :)
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 718 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Ms_XVzrBwDaI1aICIxO:-MtEZ2yT36-NZqSR9YIM:b36aqcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e232eae947e04a8e12a374fbdf46571889c92dbf/pkg/sql/opt/testutils/testcat/create_table.go#L718)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You can should add some hash sharded indexes to the testcat tests here: https://github.com/cockroachdb/cockroach/blob/36d3f237180c1c385e82a56e6a313fe08b76e223/pkg/sql/opt/testutils/testcat/testdata/index
</blockquote></details>

Done since not relevant anymore :)


<!-- Sent from Reviewable.io -->

2022-01-12 20:16 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 11 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-MtEviG7DXP93-ac4goc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @rytaft)

___
*[pkg/sql/opt_catalog.go, line 846 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtEv6US-E_VfT0ZRtUC:-MtEv6US-E_VfT0ZRtUD:bgtkhuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4b19d8f74cf9d496335b8176332f3651447d86/pkg/sql/opt_catalog.go#L846)):*
> ```Go
> 		}
> 
> 		// Add unique constraint for hash sharded indexes
> ```

nit: end comment with a period.


<!-- Sent from Reviewable.io -->

2022-01-12 20:38 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt_catalog.go, line 846 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtEv6US-E_VfT0ZRtUC:-MtF-g59CuvLceUBvSOI:bqguorn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4b19d8f74cf9d496335b8176332f3651447d86/pkg/sql/opt_catalog.go#L846)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: end comment with a period.
</blockquote></details>

thanks, period added


<!-- Sent from Reviewable.io -->

2022-01-12 20:44 UTC, rytaft requested changes
I see the new test file showing that we add uniqueness checks in some cases when inserting into hash index. That's not good, since we should be able to remove that uniqueness check. I wonder why the check isn't getting removed.

Please don't merge this yet.

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-MtF0t9P93cucdgjGnXQ:b-f01180)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @mgartner, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/alter_primary_key, line 393 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF0a3Z3uEnk35gyFJ5:-MtF0a3_5dxZKwEJ5CNY:b66xz1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/09191655a8b9918c3b00bf1ee04e8ba5a5fd381f/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L393)):*
> ```
> └── • constraint-check
>     │
>     └── • error if rows
> ```

Oh this isn't good -- we should make sure that we don't add these uniqueness checks for hash indexes. We should figure out why we're not automatically removing these checks.


<!-- Sent from Reviewable.io -->

2022-01-12 20:49 UTC, mgartner requested changes
> Reviewed 4 of 11 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @mgartner, and @rytaft)

___
*[-- commits, line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF-CZd606PbE_P9tml):*
nit: "to so" => "so"
___
*[pkg/sql/logictest/testdata/logic_test/alter_primary_key, line 393 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF0a3Z3uEnk35gyFJ5:-MtF1Y-z0RJa8DrAeJVm:bd593f3) ([raw file](https://github.com/cockroachdb/cockroach/blob/09191655a8b9918c3b00bf1ee04e8ba5a5fd381f/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L393)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Oh this isn't good -- we should make sure that we don't add these uniqueness checks for hash indexes. We should figure out why we're not automatically removing these checks.
</blockquote></details>

I think we'll need to recognize that the shard column is functionally dependent on the unique column(s) and avoid building uniqueness checks in that case in [`buildUniqueChecksForInsert`](https://github.com/cockroachdb/cockroach/blob/52c2df4fb00d943328dc59df9dc210a40a556ab2/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L37) and [`buildUniqueChecksForUpdate`](https://github.com/cockroachdb/cockroach/blob/52c2df4fb00d943328dc59df9dc210a40a556ab2/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L69). 

I expected something like this to happen, and I'm surprised that the test you added in `pkg/sql/opt/exec/execbuilder/testdata/upsert` doesn't also have a uniqueness check.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 811 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF-N4_4CQEEJudmqHq:-MtF-N4_4CQEEJudmqHr:b171zi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4b19d8f74cf9d496335b8176332f3651447d86/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L811)):*
> ```
> INSERT INTO child VALUES (1,1)
> 
> # make sure that uniqueness is guaranteed with hash index
> ```

nit: "make" => "Make" and end sentence with a period.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 812 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF-lm-9T1KFlY4s5zd:-MtF-lm-9T1KFlY4s5ze:b-mec7ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4b19d8f74cf9d496335b8176332f3651447d86/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L812)):*
> ```
> 
> # make sure that uniqueness is guaranteed with hash index
> subtest unique_hash_sharded_index
> ```

Some tests here that might be good to add:

* `INSERT` that causes a duplicate key violation
* `INSERT .. ON CONFLICT (y, z) DO NOTHING`
* `INSERT .. ON CONFLICT DO NOTHING`
___
*[pkg/sql/opt/exec/execbuilder/testdata/upsert, line 674 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF0-_q8T_5GTQEGs5U:-MtF-zaD5X3JPuC_Pd1L:b200mkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4b19d8f74cf9d496335b8176332f3651447d86/pkg/sql/opt/exec/execbuilder/testdata/upsert#L674)):*
> ```
>                           spans: /NULL-/!NULL /1-
> 
> # Test to make sure hash sharded index is used for uniqueness check
> ```

nit: end with period
___
*[pkg/sql/opt/exec/execbuilder/testdata/upsert, line 675 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF0J_a853qwTM8Y8iX:-MtF0J_a853qwTM8Y8iY:b-66hzb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4b19d8f74cf9d496335b8176332f3651447d86/pkg/sql/opt/exec/execbuilder/testdata/upsert#L675)):*
> ```
> 
> # Test to make sure hash sharded index is used for uniqueness check
> subtest hash_index_unique_constraint
> ```

Can you two more tests: `INSERT .. ON CONFLICT DO NOTHING` and `INSERT ON CONFLICT (a) DO NOTHING`?


<!-- Sent from Reviewable.io -->

2022-01-12 22:08 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @mgartner, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/alter_primary_key, line 393 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF0a3Z3uEnk35gyFJ5:-MtFK7o31PxGVadUV-U5:b-o51tce) ([raw file](https://github.com/cockroachdb/cockroach/blob/09191655a8b9918c3b00bf1ee04e8ba5a5fd381f/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L393)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think we'll need to recognize that the shard column is functionally dependent on the unique column(s) and avoid building uniqueness checks in that case in [`buildUniqueChecksForInsert`](https://github.com/cockroachdb/cockroach/blob/52c2df4fb00d943328dc59df9dc210a40a556ab2/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L37) and [`buildUniqueChecksForUpdate`](https://github.com/cockroachdb/cockroach/blob/52c2df4fb00d943328dc59df9dc210a40a556ab2/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L69). 

I expected something like this to happen, and I'm surprised that the test you added in `pkg/sql/opt/exec/execbuilder/testdata/upsert` doesn't also have a uniqueness check.
</blockquote></details>

Yea -- we'll need to look closer at where the FDs are built for computed columns here:
https://github.com/cockroachdb/cockroach/blob/5487f8b98f381ab37225bcf757e6cc4b94e975f3/pkg/sql/opt/memo/logical_props_builder.go#L1741


<!-- Sent from Reviewable.io -->

2022-01-12 22:42 UTC, chengxiong-ruan commented
___
*[pkg/sql/logictest/testdata/logic_test/alter_primary_key, line 393 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF0a3Z3uEnk35gyFJ5:-MtFQEZPAP8HTMihkRIk:b9i6t44) ([raw file](https://github.com/cockroachdb/cockroach/blob/09191655a8b9918c3b00bf1ee04e8ba5a5fd381f/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L393)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea -- we'll need to look closer at where the FDs are built for computed columns here:
https://github.com/cockroachdb/cockroach/blob/5487f8b98f381ab37225bcf757e6cc4b94e975f3/pkg/sql/opt/memo/logical_props_builder.go#L1741
</blockquote></details>

hmm...maybe I'm crazy, but if I drop the old primary key (a unique index here) `drop index t_x_key CASCADE;` then the constraint check  would be gone...
Wondering if multiple unique constraints on the same table caused some interesting behaviors.

Also Marcus pointed out that the other test I added doesn't cause a uniqueness check with table
```
CREATE TABLE t_hash_indexed (
  a INT8 PRIMARY KEY USING HASH WITH BUCKET_COUNT = 8,
  b INT8 NOT NULL
);
```
But uniqueness check appears if I make b as unique at the same time, like:
```
CREATE TABLE t_hash_indexed (
  a INT8 PRIMARY KEY USING HASH WITH BUCKET_COUNT = 8,
  b INT8 NOT NULL UNIQUE
);
```
So `SELECT * FROM [EXPLAIN INSERT INTO t_hash_indexed VALUES (4321, 8765)] OFFSET 2;` would cause a uniqueness check >_>:
```
  • root
  │
  ├── • insert
  │   │ into: t_hash_indexed(crdb_internal_a_shard_8, a, b)
  │   │
  │   └── • buffer
  │       │ label: buffer 1
  │       │
  │       └── • values
  │             size: 4 columns, 1 row
  │
  └── • constraint-check
      │
      └── • error if rows
          │
          └── • lookup join
              │ table: t_hash_indexed@t_hash_indexed_pkey
              │ equality: (lookup_join_const_col_@11, column1) = (crdb_internal_a_shard_8,a)
              │ equality cols are key
              │ pred: crdb_internal_a_shard_8_cast != crdb_internal_a_shard_8
              │
              └── • cross join
                  │ estimated row count: 8
                  │
                  ├── • values
                  │     size: 1 column, 8 rows
                  │
                  └── • scan buffer
                        label: buffer 1
```

Hope this make sense and would help finding the monster here.


<!-- Sent from Reviewable.io -->

2022-01-13 19:54 UTC, mgartner commented
There are two issues that seem to be preventing the omission of uniqueness checks for unique, secondary hash-sharded indexes:

1. Because the shard column is VIRTUAL, and scans over primary indexes don't produce VIRTUAL columns, the shard column isn't included in the functional dependencies (FDs) of the scan. This is preventing the uniqueness check logic from understanding the the shard column is a dependent of the unique column(s). During testing, changing the shard column to STORED fixed the issue (but this is not a solution because we want them to be VIRTUAL).
2. When the unique column(s) is nullable, the FDs aren't able to determine that the unique column is a lax key. We haven't run into this with multi-region tables because in those cases we aim to omit uniqueness checks for partitioned primary indexes where the columns are always `NOT NULL`. 

I'm going to take a crack at solving these, but I don't think they will be quick fixes. In particular, (2) may require a significant enhancement to our implementation of FDs.

In the meantime, we could consider the pragmatic, but perhaps unsavory solution of adding an `IgnoreUniquenessChecks() bool` method to `cat.UniqueConstraint` that returns true for only these unique constraints that are created from hash sharded unique indexes. This hack gets around the "loss of information" when creating a unique without index constraint for a hash-sharded unique index and deriving FDs from the table. It would essentially tell the uniqueness-check logic in the optimizer: "trust me, the column(s) in this unique constraint form a lax key and you do not need to perform a uniqueness check".

2022-01-13 21:09 UTC, mgartner commented on pkg/sql/opt/exec/execbuilder/testdata/upsert
> +# Test to make sure hash sharded index is used for uniqueness check
I've realized there are quite a few interesting cases that we'll want to test to make sure we avoid uniqueness checks. I think you should move this test to `pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index` and add tests for all types of mutations including `INSERT`, `UPDATE`, `UPSERT`, `INSERT .. ON CONFLICT DO NOTHING`, and `INSERT .. ON CONFLICT .. DO UPDATE`.

2022-01-14 15:46 UTC, mgartner commented
> 1. Because the shard column is VIRTUAL, and scans over primary indexes don't produce VIRTUAL columns, the shard column isn't included in the functional dependencies (FDs) of the scan. This is preventing the uniqueness check logic from understanding the the shard column is a dependent of the unique column(s). During testing, changing the shard column to STORED fixed the issue (but this is not a solution because we want them to be VIRTUAL).

Here's an example of what happens. Consider the table:

```sql
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT NOT NULL,
  shard INT4 NOT NULL AS (mod(fnv32(crdb_internal.datums_to_bytes(a)), 8)) VIRTUAL,
  CHECK (shard IN (0, 1, 2, 3, 4, 5, 6, 7)),
  UNIQUE INDEX (shard, a),
  UNIQUE WITHOUT INDEX (a)
)
```

In order to omit the uniqueness check, we need to prove that `a` is a lax key [here](https://github.com/cockroachdb/cockroach/blob/52c2df4fb00d943328dc59df9dc210a40a556ab2/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L300).

[`MakeTableFuncDep`](https://github.com/cockroachdb/cockroach/blob/5487f8b98f381ab37225bcf757e6cc4b94e975f3/pkg/sql/opt/memo/logical_props_builder.go#L1741) computes the following base FDs:

```
11: k
12: a
13: shard
14,15: system columns

key(11); (11)-->(12-15), (12,13)-->(11,14,15), (12)-->(13)
```

Because `shard:13` is not produced by the scan over the table (it is a virtual column), it is pruned from the FDs [here](https://github.com/cockroachdb/cockroach/blob/5487f8b98f381ab37225bcf757e6cc4b94e975f3/pkg/sql/opt/memo/logical_props_builder.go#L146). This results in the FDs below, which do not prove that `a:12` is a lax key.

```
11: k
12: a

key(11); (11)-->(12)
```

I believe that the base FDs should be simplified further. By transitivity, `(12,13)-->(11,14,15)` and `(12)-->(13)` imply `(12)-->(11,13-15)`. After pruning columns `13-15`, we'd be left with `key(11); (11)-->(12), (12)-->(11)`, which would prove that `a:12` is a lax key. So I think that better simplification of the base FDs would solve the problem.

---

I think this could be a deep rabbit hole, so I propose we move forward with the workaround I mentioned [above](https://github.com/cockroachdb/cockroach/pull/74235#issuecomment-1012459018). I can create an issue describing the enhancements to FDs that would make this workaround obsolete and we can leave a TODO pointing to the issue. @rytaft what do you think?

2022-01-14 16:12 UTC, rytaft commented
Seems reasonable, although I'd really love to avoid letting this hack hang around for too long. But if we want to go with the hack for now, the right place to call `IgnoreUniquenessChecks()` would be here: https://github.com/cockroachdb/cockroach/blob/5487f8b98f381ab37225bcf757e6cc4b94e975f3/pkg/sql/opt/memo/logical_props_builder.go#L1802-L1805

Basically, we'd need to move the current check for `if !md.TableMeta(tabID).IgnoreUniqueWithoutIndexKeys` inside the loop, and instead do:
```
if md.TableMeta(tabID).IgnoreUniqueWithoutIndexKeys && !unique.IgnoreUniquenessChecks() {
  continue
}
```

Also, maybe `SkipUniquenessChecks` is a better name than `IgnoreUniquenessChecks`?

2022-01-14 22:10 UTC, chengxiong-ruan reviewed
@mgartner @rytaft  Thanks for investigating this and sharing all these thoughts! I haven't dig too much but just curious if you have any quick thoughts about how this hack would work if we want to support partitioned hash-sharded index (#74626)?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-MtPcxYy0Y_g3Alvl1ge:be7jx16)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @mgartner, and @rytaft)



<!-- Sent from Reviewable.io -->

2022-01-18 15:55 UTC, mgartner commented
I created #75070 to track the FD improvements necessary to remove the hack.

> I haven't dig too much but just curious if you have any quick thoughts about how this hack would work if we want to support partitioned hash-sharded index.

I think we'll need to try out some test cases to be sure. We may not need this hack. Partitioned indexes already have `UNIQUE WITHOUT INDEX` constraints and uniqueness checks are required in order to ensure uniqueness, except for two cases: 1) the unique column is generated from `gen_random_uuid()` and the chance of a collision is almost zero, and 2) the partition column is a dependent on the unique columns in the index. For partitioned, hash-sharded unique indexes, we'll want to make sure that uniqueness checks are also omitted in these two cases, but for all other cases we'll want to make sure the uniqueness checks are performed.

I think we'll want to create a single `UNIQUE WITHOUT INDEX` constraint for a partitioned hash-sharded index, rather than two. For example, for an index on columns `(partition, shard, a)` we will create a `UNIQUE WITHOUT INDEX` constraint on `(a)`. I don't see any reason to create one on `(shard, a)` and another on `(a)`. At this point I can only guess how this will interact with FDs and uniqueness checks.

2022-01-19 18:27 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[-- commits, line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF-CZd606PbE_P9tml):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "to so" => "so"
</blockquote></details>

fixed
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 811 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF-N4_4CQEEJudmqHq:-Mtn_MrgAtSWnixSmInA:b-qssebl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4b19d8f74cf9d496335b8176332f3651447d86/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L811)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "make" => "Make" and end sentence with a period.
</blockquote></details>

fixed.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 812 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF-lm-9T1KFlY4s5zd:-Mtn_gYt5j1tQ_eIWWtq:bvv6nvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4b19d8f74cf9d496335b8176332f3651447d86/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L812)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Some tests here that might be good to add:

* `INSERT` that causes a duplicate key violation
* `INSERT .. ON CONFLICT (y, z) DO NOTHING`
* `INSERT .. ON CONFLICT DO NOTHING`
</blockquote></details>

test cases added~
___
*[pkg/sql/opt/exec/execbuilder/testdata/upsert, line 675 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtF0J_a853qwTM8Y8iX:-Mtn_mLS8m_q5Qp049Dw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f4b19d8f74cf9d496335b8176332f3651447d86/pkg/sql/opt/exec/execbuilder/testdata/upsert#L675)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you two more tests: `INSERT .. ON CONFLICT DO NOTHING` and `INSERT ON CONFLICT (a) DO NOTHING`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/upsert, line 674 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MtEW8jkZbUDAQ5JfUUR-r4-674:-Mtn_mdZ7V6qq-wJaLLR:b-nmj4x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/09191655a8b9918c3b00bf1ee04e8ba5a5fd381f/pkg/sql/opt/exec/execbuilder/testdata/upsert#L674)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I've realized there are quite a few interesting cases that we'll want to test to make sure we avoid uniqueness checks. I think you should move this test to `pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index` and add tests for all types of mutations including `INSERT`, `UPDATE`, `UPSERT`, `INSERT .. ON CONFLICT DO NOTHING`, and `INSERT .. ON CONFLICT .. DO UPDATE`.
</blockquote></details>

test cases added and moved to pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index


<!-- Sent from Reviewable.io -->

2022-01-19 18:32 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 188 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Mtnava-AmhafUPdPczL:-Mtnava-AmhafUPdPczM:b-y1gtxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a276bbeaffc7af228ef4b173c7f95a561596442/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L188)):*
> ```
> 
> query T
> EXPLAIN (VERBOSE) UPSERT INTO t_hash_indexed VALUES (4321, 8765);
> ```

I think `UPSERT` should be somehow similar to `INSERT ... ON CONFLICT (a) DO UPDATE`... but it looks quite different. is this a concern?
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 224 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Mtnalfu30-QKEEfXCJk:-Mtnalfu30-QKEEfXCJl:b-u9wvtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a276bbeaffc7af228ef4b173c7f95a561596442/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L224)):*
> ```
> │
> └── • project
>     │ columns: (crdb_internal_a_shard_8_cast, column1, column2, crdb_internal_a_shard_8, a, b, upsert_b, crdb_internal_a_shard_8, check1)
> ```

it was `rdb_internal_a_shard_8_comp` as the first column, but now it's `crdb_internal_a_shard_8_cast`. not sure what's the difference here.


<!-- Sent from Reviewable.io -->

2022-01-24 20:56 UTC, mgartner requested changes
Looking great! I left a few comments, mostly nits. I'd like to make sure @rytaft signs off on the final approach too.

> Reviewed 5 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-MuCrrC49MEP3uiaoZ3s:b-3bdzbf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @mgartner, and @rytaft)

___
*[pkg/sql/opt_catalog.go, line 1621 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCbBCfCqTt0sXj5ToX:-MuCbBCfCqTt0sXj5ToY:bl6b88j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/opt_catalog.go#L1621)):*
> ```Go
> 	validity     descpb.ConstraintValidity
> 
> 	ignoreUniquenessCheck bool
> ```

nit: name this something like `uniquenessGuaranteedByAnotherIndex` for consistency
___
*[pkg/sql/opt/cat/table.go, line 293 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCbM-1-x3f5l6PvuPh:-MuCbM-1-x3f5l6PvuPi:bxpahbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/opt/cat/table.go#L293)):*
> ```Go
> 	// UniquenessGuaranteedByAnotherIndex is a hack to make unique hash sharded
> 	// index work before issue #75070 is resolved. Optimizer will omit uniqueness
> 	// check if this method returns true.
> ```

nit: add a little bit more detail here. Something like:

```
UniquenessGuaranteedByAnotherIndex returns true when WithoutIndex() returns true and
the uniqueness of the constraint is guaranteed by another index. When true, the optimizer
will always consider the constraint to be satisfied when building functional dependencies for
the table. This enables additional optimizations, such as omission of uniqueness checks.
```
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 797 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCrD4vDT2fW0KG_nFA:-MuCrD4vDT2fW0KG_nFB:b-lzgh0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L797)):*
> ```
> statement ok
> CREATE TABLE t (
>     a INT PRIMARY KEY USING HASH WITH BUCKET_COUNT = 8
> ```

I think it would be wise to add some tests with the hash-sharded primary key that show that uniqueness cannot be violated. Unless those already exist somewhere else?
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 801 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuClbrS5M-Tcov52GJU:-MuClbrTBsMexqcbQolK:b6i3785) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L801)):*
> ```
> 
> query T
> explain (opt, catalog) select * from t
> ```

nit: upper-case keywords
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 840 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuClo5s3IWMnFqhuhtz:-MuClo5s3IWMnFqhuhu-:b6i3785) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L840)):*
> ```
> 
> query T
> explain (opt, catalog) select * from t
> ```

nit: upper-case keywords
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 885 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCmeo4-a2dc4JDTsoM:-MuCmeo4-a2dc4JDTsoN:b6i3785) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L885)):*
> ```
> 
> query T
> explain (opt, catalog) select * from t
> ```

nit: upper-case keywords
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 968 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCrOQrA7J1OP_LgyNN:-MuCrOQrA7J1OP_LgyNO:b-ongaw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L968)):*
> ```
> 
> statement ok
> INSERT INTO t (x, y, z) VALUES (3, 11, 111) ON CONFLICT DO NOTHING
> ```

nit: might not hurt to add some `DO UPDATE` tests. I think this one would be especially good to have:

```
statement error pq: duplicate key value violates ...
INSERT INTO t (x, y, z) VALUES (3, 11, 111) ON CONFLICT (y, z) DO UPDATE SET y = 22, z = 222
```
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 188 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Mtnava-AmhafUPdPczL:-MuCoTVM0S3Igz4X9lLp:b-hyi1t0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a276bbeaffc7af228ef4b173c7f95a561596442/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L188)):*
This is a special case of an UPSERT that we optimize, and it looks fine to me. From [the docs](https://www.cockroachlabs.com/docs/stable/upsert.html#considerations):

> When inserting/updating all columns of a table, and the table has no secondary indexes, UPSERT will be faster than the equivalent INSERT ON CONFLICT statement, as it will write without first reading.
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 224 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Mtnalfu30-QKEEfXCJk:-MuCov7B3ACgZdQiSHoy:bpz65sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a276bbeaffc7af228ef4b173c7f95a561596442/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L224)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

it was `rdb_internal_a_shard_8_comp` as the first column, but now it's `crdb_internal_a_shard_8_cast`. not sure what's the difference here.
</blockquote></details>

This is due to some recent work on assignment casts. It looks correct to me. The TLDR is that `mod` returns an `INT8` but the column type is `INT4` so the result of `mod` has to be cast to an `INT4` before being written. The result of this cast is given a new column name, which is why it changed.
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 127 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCmvhE0c11wbleTguT:-MuCmvhE0c11wbleTguU:b-wim0i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L127)):*
> ```
> 
> 
> # Test to make sure hash sharded index is used for uniqueness check.
> ```

nit: Test to make sure **unqiueness checks are omitted for unique without index constraints that are derived from hash-sharded indexes**.
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 131 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCnDv1EnJvowdOxJet:-MuCnDv1EnJvowdOxJeu:b-tw5p5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L131)):*
> ```
> 
> statement ok
> set experimental_enable_hash_sharded_indexes = on
> ```

nit: this is unnecessary - it's already enabled at the top of the file
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 134 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCnOnJ-xmXl8MtDVME:-MuCnOnJ-xmXl8MtDVMF:bzgxcvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L134)):*
> ```
> 
> statement ok
> DROP TABLE IF EXISTS t_hash_indexed
> ```

nit: unnecessary
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 160 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCnZDh2Pj6cp2_1ijA:-MuCnZDh2Pj6cp2_1ijB:b-1jif2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_inde [...]

2022-01-25 14:18 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once you address comments from @mgartner 

> Reviewed 5 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-MuGaUZ-2goh1wp-QtGw:bij5zhx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 801 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuG_OKc0jrvjHQWB7kh:-MuG_OKc0jrvjHQWB7ki:bkwjbha) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L801)):*
> ```
> 
> query T
> explain (opt, catalog) select * from t
> ```

we usually prefer to put all EXPLAIN tests in `sql/opt/execbuilder/testdata`, and leave logictest for tests that just output results.


<!-- Sent from Reviewable.io -->

2022-01-25 15:12 UTC, mgartner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 840 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuClo5s3IWMnFqhuhtz:-MuGmvGY8ITnp8y6OrQn:b-kognz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L840)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: upper-case keywords
</blockquote></details>

This should be in execbuilder tests too.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 953 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuGmpR36qVS8RG3I49-:-MuGmpR36qVS8RG3I490:b3ucnma) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L953)):*
> ```
> # as guard.
> query T
> SELECT * FROM [EXPLAIN INSERT INTO t (x, y, z) VALUES (3, 11, 111)] OFFSET 2
> ```

This needs to be in execbuilder tests too.


<!-- Sent from Reviewable.io -->

2022-01-27 15:11 UTC, mgartner requested changes
It's getting really close! Unfortunately there's a full table scan being done in one of the tests that we'll need to figure out before we can merge this. I'll spend some time trying to figure out what's going on and report back. Thanks for being patient!

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-MuR4_p151xnPH7P43yM:bdf4nhp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @mgartner, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 550 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuR3YuG9vGvylVExn20:-MuR3YuG9vGvylVExn21:bg2snw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/15ee3b08d27f2fe52ddd3b52da4983b6993e7d02/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L550)):*
> ```
> 
> query T
> EXPLAIN (VERBOSE) INSERT INTO t_hash_indexed VALUES (4321, 8765) ON CONFLICT (a) DO UPDATE SET b = 8765
> ```

Can you add another test exactly like this but with `ON CONFLICT (b)`?
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 676 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuR3d8aDipTImYQMm-4:-MuR3d8aDipTImYQMm-5:bpgep4) ([raw file](https://github.com/cockroachdb/cockroach/blob/15ee3b08d27f2fe52ddd3b52da4983b6993e7d02/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L676)):*
> ```
>                 │         estimated row count: 1,000 (missing stats)
>                 │         table: t_hash_indexed@t_hash_indexed_pkey
>                 │         spans: FULL SCAN
> ```

This full scan is bad. I'll need to spend some time with this test to figure out what is preventing it from being optimized further.


<!-- Sent from Reviewable.io -->

2022-01-27 22:33 UTC, chengxiong-ruan reviewed
Thanks for the help!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-MuSesaH0wjHc0R8gcMK:b50e5xk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 797 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCrD4vDT2fW0KG_nFA:-MuS_CMO2WP8W3F-rP7N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L797)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think it would be wise to add some tests with the hash-sharded primary key that show that uniqueness cannot be violated. Unless those already exist somewhere else?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 801 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuG_OKc0jrvjHQWB7kh:-MuS_Du4-D7BPlS3CFu3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L801)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

we usually prefer to put all EXPLAIN tests in `sql/opt/execbuilder/testdata`, and leave logictest for tests that just output results.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 953 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuGmpR36qVS8RG3I49-:-MuS_HYz6rA5l3Kc9poJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L953)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This needs to be in execbuilder tests too.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 160 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCnZDh2Pj6cp2_1ijA:-MuS_NWF-9QpV9SyMu83:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L160)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think updating `a` is the test case that is interesting. `b` is not a unique column so we would never expect uniqueness checks for this update.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 352 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuCqwic01JdfgP_gz9g:-MuS_UQB20fIf_OqdIkD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e485565fc3110fd21e282ba8364107672c288a9/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L352)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

These tests look great. Can you add the same set of tests, but with a unique, hash-sharded secondary index?
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 550 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuR3YuG9vGvylVExn20:-MuS_Wlc8aK1c-_10Hb8:bl5z1qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/15ee3b08d27f2fe52ddd3b52da4983b6993e7d02/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L550)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add another test exactly like this but with `ON CONFLICT (b)`?
</blockquote></details>

good point, added
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 676 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuR3d8aDipTImYQMm-4:-MuS__-A6JhYt8UCtFXN:b-osr5ds) ([raw file](https://github.com/cockroachdb/cockroach/blob/15ee3b08d27f2fe52ddd3b52da4983b6993e7d02/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L676)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This full scan is bad. I'll need to spend some time with this test to figure out what is preventing it from being optimized further.
</blockquote></details>

Thanks! I added a comment to warn you about this output but forgot to hit `Publish` on reviewable >_> oops..


<!-- Sent from Reviewable.io -->

2022-01-28 17:39 UTC, mgartner commented
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 676 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuR3d8aDipTImYQMm-4:-MuWk9OFDfuM3ZsQYqHy:b-i028o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/15ee3b08d27f2fe52ddd3b52da4983b6993e7d02/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L676)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Thanks! I added a comment to warn you about this output but forgot to hit `Publish` on reviewable >_> oops..
</blockquote></details>

I think the problem is that we don't generate lookup anti-joins when the right side of the anti-join has the pattern `(Project (Scan))`. See this TODO: https://github.com/cockroachdb/cockroach/blob/5fd739be5dbfcd8d08f83f7f0f24b302c85bb50d/pkg/sql/opt/xform/rules/join.opt#L215-L216

It may be as simple as extending the pattern from matching just InnerJoins to matching AntiJoins too (and probably SemiJoins). I'll work on that and should have a PR up soon if I don't run into any hurdles.


<!-- Sent from Reviewable.io -->

2022-01-28 21:23 UTC, mgartner commented
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 676 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-MuR3d8aDipTImYQMm-4:-MuXYr0Q2os8UT8QTzqq:bwduz5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/15ee3b08d27f2fe52ddd3b52da4983b6993e7d02/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L676)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think the problem is that we don't generate lookup anti-joins when the right side of the anti-join has the pattern `(Project (Scan))`. See this TODO: https://github.com/cockroachdb/cockroach/blob/5fd739be5dbfcd8d08f83f7f0f24b302c85bb50d/pkg/sql/opt/xform/rules/join.opt#L215-L216

It may be as simple as extending the pattern from matching just InnerJoins to matching AntiJoins too (and probably SemiJoins). I'll work on that and should have a PR up soon if I don't run into any hurdles.
</blockquote></details>

Unfortunately, it's not so simple. There's a number of things that prevent the rule from handling the semi- and anti-join cases. I've been playing around with one idea for a fix, but the complexity is growing out of hand. I'll continue with it and report back if I make any progress.


<!-- Sent from Reviewable.io -->

2022-02-02 15:23 UTC, mgartner reviewed
I think we should add TODOs for the bad plans and get this merged. I've added comments for the TODOs to add, and a couple of new tests.

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-Muv0nZtEXZG_lHTiRVl:b-rpdeht)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @mgartner, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 615 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Muv-YkSA2tGfG_M00h8:-Muv-YkSA2tGfG_M00h9:b63ecay) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dc0a9677423153cea628329aaa3bd051748b334/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L615)):*
> ```
> 
> query T
> EXPLAIN (VERBOSE) INSERT INTO t_hash_indexed VALUES (4321, 8765) ON CONFLICT (b) DO UPDATE SET b = 8765
> ```

Can you create a test just like this but insert 2 rows instead of one. `INSERT INTO t_hash_indexed VALUES (111, 222), (333, 444) ON CONFLICT (b) DO UPDATE ...`. I suspect this will result in a full index scan, so leave a `# TODO(mgartner): There is a full index scan because we do not currently generate left lookup joins on indexes with virtual columns.`
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 680 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Muv0YGlCJt2t65VMK4C:-Muv0YGmDzu_eddq1phs:b-rt5eka) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dc0a9677423153cea628329aaa3bd051748b334/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L680)):*
> ```
> 
> # TODO (issue #75498): we're using unique without index on (a) as an arbiter and
> # using the original hash sharded index as an arbiter is not necessary.
> ```

Add another todo here: `# TODO(mgartner): There is a full scan because we do not generate lookup anti-joins on indexes with virtual columns.`
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 751 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Muv0I2f26_Glny9zF2_:-Muv0I2f26_Glny9zF2a:bpmrzg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dc0a9677423153cea628329aaa3bd051748b334/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L751)):*
> ```
> 
> query T
> EXPLAIN (VERBOSE) INSERT INTO t_hash_indexed VALUES (4321, 8765) ON CONFLICT (b) DO NOTHING
> ```

Can you create a copy of this test that inserts two rows. If there is a full scan in the plan, leave a `# TODO(mgartner): There is a full scan because we do not generate lookup anti-joins on indexes with virtual columns.`


<!-- Sent from Reviewable.io -->

2022-02-02 19:48 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @mgartner, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 615 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Muv-YkSA2tGfG_M00h8:-MuvybJMA7H4lqN-BF3C:biqs4we) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dc0a9677423153cea628329aaa3bd051748b334/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L615)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you create a test just like this but insert 2 rows instead of one. `INSERT INTO t_hash_indexed VALUES (111, 222), (333, 444) ON CONFLICT (b) DO UPDATE ...`. I suspect this will result in a full index scan, so leave a `# TODO(mgartner): There is a full index scan because we do not currently generate left lookup joins on indexes with virtual columns.`
</blockquote></details>

added, but as we talked offline that it does not cause a full scan but still a nice to have.
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 680 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Muv0YGlCJt2t65VMK4C:-MuvylYlC58FwDK5bXtA:b-7tfmjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dc0a9677423153cea628329aaa3bd051748b334/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L680)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Add another todo here: `# TODO(mgartner): There is a full scan because we do not generate lookup anti-joins on indexes with virtual columns.`
</blockquote></details>

added
___
*[pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index, line 751 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-Muv0I2f26_Glny9zF2_:-MuvyodgAM44j300PPko:biqs4we) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dc0a9677423153cea628329aaa3bd051748b334/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L751)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you create a copy of this test that inserts two rows. If there is a full scan in the plan, leave a `# TODO(mgartner): There is a full scan because we do not generate lookup anti-joins on indexes with virtual columns.`
</blockquote></details>

added, but as we talked offline that it does not cause a full scan but still a nice to have.


<!-- Sent from Reviewable.io -->

2022-02-02 20:58 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Let's merge it!

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74235#-:-MuwDoBt5F_ODikyVE7m:b-l95zdm)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @mgartner, and @rytaft)



<!-- Sent from Reviewable.io -->

2022-02-02 23:57 UTC, chengxiong-ruan commented
thanks for the review and patience!
bors r+

2022-02-03 07:36 UTC, merged