opt: split a disjunction of equijoin predicates into a union of joins
cockroachdb/cockroach pull request #74303
Opened 2021-12-29 01:23 UTC by msirek

Previously, when the ON clause of an inner, semi or anti join contained
ORed equality predicates, the only available join method was cross join.

This was inadequate because cross join is often the worst performing
join method for joining large tables.

To address this, this patch adds a new cost-based transformation which
evaluates each disjunct in a separate join and unions or intersects the
results together.

Example query:

```
SELECT *
FROM   classRequest
       INNER JOIN classes
               ON classRequest.firstChoiceClassid = classes.classid
                  OR classRequest.secondChoiceClassid = classes.classid;
```
Transformation result written in pseudo-SQL:
```
SELECT DISTINCT ON (classes.<rowid_or_primary_key_columns>,
                    classRequest.<rowid_or_primary_key_columns>)
       dt.*
FROM   (
        SELECT     *
        FROM       classRequest
                   INNER JOIN classes
                   ON         classRequest.firstChoiceClassid =
		              classes.classid
                   UNION ALL
        SELECT     *
        FROM       classRequest
                   INNER JOIN classes
                   ON         classRequest.secondChoiceClassid =
		              classes.classid
       ) dt;
```

In addition, ORed ON clause selectivity estimation is enhanced to
estimate the selectivity of each '=' predicate separately and
combine the estimates in an iterative fashion like PostgreSQL does. This
enables the optimizer to cost the rewritten plan more accurately so it
will get picked.

Release note (performance improvement): Performance of inner, semi or
anti join between two tables with ORed equijoin predicates is improved
by enabling the optimizer to select a join plan in which each equijoin
predicate is evaluated by a separate join, with the results of the joins
unioned or intersected together.

2021-12-29 01:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74303)
<!-- Reviewable:end -->

2021-12-29 21:37 UTC, mgartner reviewed
Nice! It will take me some time to go through all this, but I've left a few comments for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-Ms72pf69wWLafqvr4BX:b42b63k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[pkg/sql/opt/xform/rules/join.opt, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms727UCCNb9fw23sULS:-Ms727UCCNb9fw23sULT:b-6sy09e) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/rules/join.opt#L136)):*
> ```
> # relations to the Join.
> #
> # The replace pattern adds primary key columns to the original Scan ColSet.
> ```

It seems like quite a bit of the complexity in the rule is there in order to supporting adding key columns when they are not already part of the input relations. Does it makes sense to not support that case initially and require that both input have key columns to simplify this? Then we can expand the rule or create a new one in a follow-up?
___
*[pkg/sql/opt/xform/rules/join.opt, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms6ysVi2op3zBRZp4hu:-Ms6ysVi2op3zBRZp4hv:b6nuliq) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/rules/join.opt#L192)):*
> ```
>                 $origLeftScanPrivate
>             )
>             $ok
> ```

I'm surprised that you can use a variable bound outside a `Let` as the `Let`'s return value. I didn't anticipate usage of `Let` like this. I'd probably consider it a bug. If we do have use cases where we want to bind function return values to arguments and those functions can never fail, maybe we should add new syntax, like a `Let` without the return value suffix: `(Let ($a $b):(GetAB $input))`, or maybe use a new keyword. `(Bind ($a $b):(GetAB $input))`. That's definitely outside the scope of this PR though.

However, I think the complexity of this optgen code is a possible hint that more of this logic should be written in Go, a la `GeneratedLookupJoins`, or `GenerateConstrainedScans`. Optgen's strength is matching expression patterns, and this rule doesn't have very complex pattern matching. It's mostly an InnerJoin pattern match with a bunch of Let bindings and function calls. So I don't think we're getting much value out of having so much logic written in optgen. It feels a bit unnatural. As a rough example of what it could look like if some of it was moved to Go (this is psuedo-optgen, and I'm not sure this is the optimal breakdown between optgetn/go, so you'll have to play around with it):

```
(InnerJoin
    $leftInput:*
    $rightInput:*
    $on:*
    $joinPrivate:* &
        (Let ($firstJoin $secondJoin $setPrivate $groupingCols $ok):(SplitJoinDisjunction $leftInput $rightInput $on $joinPrivate) $ok)
)
=>
(Project
    (DistinctOn
        (UnionAll
            $firstJoin
            $secondJoin
            $setPrivate
        )
        $groupingCols
        ...
    )
)
```
___
*[pkg/sql/opt/xform/testdata/rules/join, line 9896 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms74sZwDqcewJDwmB6Z:-Ms74sZwDqcewJDwmB6_:bnz9k1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/testdata/rules/join#L9896)):*
> ```
> 
> # --------------------------------------------------
> # SplitDisjunctionOfJoinTerms
> ```

I think there's some tests we should add like:

* The left and right sides of the join already produce key columns
* Join of tables with compound primary keys
* More than one disjunction in the filter, like `abc.a = xyz.x or abc.b = xyz.y or abc.c = xyz.z`
* Equality filters that do not reference a column on each side of the joins like `abc.a = abc.b OR abc.c = xyz.z`
* ON filters that are not a disjunction of equality filters, like `(abc.a = xyz.x AND abc.b = xyz.y) OR abc.c = xyz.z`
* Semi-join and anti-join tests with correlated and uncorrelated
___
*[pkg/sql/opt/xform/testdata/rules/join, line 9921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms73Iys1xP6IjyWmgpv:-Ms73Iys1xP6IjyWmgpw:bq6dvo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/testdata/rules/join#L9921)):*
> ```
> 
> # Inner join without constraints
> opt expect=SplitDisjunctionOfJoinTerms format=hide-all
> ```

nit: it'd be nice to see the output columns of expressions and grouping columns of the distinct-on in the expression trees, so I think you should remove `format=hide-all`.


<!-- Sent from Reviewable.io -->

2021-12-30 21:14 UTC, msirek commented
@mgartner Thanks for taking a look at this. I agree, it's a lot cleaner to keep the optgen logic to a minimum. I've pushed a commit. I haven't finished adding tests, but just thought I'd get this out there so you could see the direction it's headed. Regarding whether restricting the current fix to the HasStrictKey case would reduce complexity, it would mostly just remove the building of the aggCols and groupingCols in new method SplitJoinWithEquijoinDisjuncts. But maybe you are concerned about something else. Please take a look at the new code and let me know if you still think I should just handle the HasStrictKey case at this time.  By the way, I had previously tried using UNION instead of UNION ALL + DISTINCT for that case, and UNION ALL performed slightly better, so I thought to unify the rules. If PK column are already in the scan, the call to AddPrimaryKeyColsToScanPrivate has no effect. For compound PK testing, a case such as the following with PK columns (a,b) will not trigger the transformation:
```
SELECT c, a FROM abc INNER JOIN xyz on (abc.a = xyz.x and abc.b = xyz.y) or (abc.b = xyz.x and abc.a = xyz.y);
```
Currently it only handles simple equality predicates ORed together.

2022-01-07 17:49 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/rules/join.opt, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms727UCCNb9fw23sULS:-MspVuFm9lgHQw0YLU6_:b-tlwwvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/rules/join.opt#L136)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It seems like quite a bit of the complexity in the rule is there in order to supporting adding key columns when they are not already part of the input relations. Does it makes sense to not support that case initially and require that both input have key columns to simplify this? Then we can expand the rule or create a new one in a follow-up?
</blockquote></details>

The code is cleaned up now.  I was seeing better performance in UNION ALL + DISTINCT ON vs. UNION, so was hoping to have one rule to cover both cases, but if you think it makes more sense to have separate rules, we could do that.  The complexity perhaps is contained within the column remapping, such as this code in join_funcs.go:

		aggCols =
			c.e.funcs.remapColSet(
				c.e.funcs.UnionCols(
					c.e.funcs.NonKeyCols(newLeftScan),
					c.e.funcs.NonKeyCols(newRightScan)),
				firstJoinCols,
				amendedOrigCols,
			)

Maybe a line-by-line code walk-through is in order here, to see what's going on.
During expanded testing, as suggested, I did run across an issue in DISTINCT processing, which seems independent of my changes, which I documented here:
https://github.com/cockroachdb/cockroach/issues/74554

I am not sure if such a problem could happen on real customer clusters, but if it could, that issue should probably be fixed before this PR is merged.  If that issue does not affect UNION processing, that may be an argument for introducing a separate UNION rule, which could be merged sooner.
___
*[pkg/sql/opt/xform/rules/join.opt, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms6ysVi2op3zBRZp4hu:-MspYiIY0xvu84GdK8xr:b-i3jk0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/rules/join.opt#L192)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm surprised that you can use a variable bound outside a `Let` as the `Let`'s return value. I didn't anticipate usage of `Let` like this. I'd probably consider it a bug. If we do have use cases where we want to bind function return values to arguments and those functions can never fail, maybe we should add new syntax, like a `Let` without the return value suffix: `(Let ($a $b):(GetAB $input))`, or maybe use a new keyword. `(Bind ($a $b):(GetAB $input))`. That's definitely outside the scope of this PR though.

However, I think the complexity of this optgen code is a possible hint that more of this logic should be written in Go, a la `GeneratedLookupJoins`, or `GenerateConstrainedScans`. Optgen's strength is matching expression patterns, and this rule doesn't have very complex pattern matching. It's mostly an InnerJoin pattern match with a bunch of Let bindings and function calls. So I don't think we're getting much value out of having so much logic written in optgen. It feels a bit unnatural. As a rough example of what it could look like if some of it was moved to Go (this is psuedo-optgen, and I'm not sure this is the optimal breakdown between optgetn/go, so you'll have to play around with it):

```
(InnerJoin
    $leftInput:*
    $rightInput:*
    $on:*
    $joinPrivate:* &
        (Let ($firstJoin $secondJoin $setPrivate $groupingCols $ok):(SplitJoinDisjunction $leftInput $rightInput $on $joinPrivate) $ok)
)
=>
(Project
    (DistinctOn
        (UnionAll
            $firstJoin
            $secondJoin
            $setPrivate
        )
        $groupingCols
        ...
    )
)
```

</blockquote></details>

Yeah, I noticed optgen allows you to reference a variable on any line after it's defined. I wasn't sure how to write a Let rule which didn't require evaluation of a boolean expression return value, that's why I just reused the ok value. I've rewritten the rules as suggested.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 9896 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms74sZwDqcewJDwmB6Z:-Msp_YrK4JKn2rxpxRAv:b-5ngcrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/testdata/rules/join#L9896)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think there's some tests we should add like:

* The left and right sides of the join already produce key columns
* Join of tables with compound primary keys
* More than one disjunction in the filter, like `abc.a = xyz.x or abc.b = xyz.y or abc.c = xyz.z`
* Equality filters that do not reference a column on each side of the joins like `abc.a = abc.b OR abc.c = xyz.z`
* ON filters that are not a disjunction of equality filters, like `(abc.a = xyz.x AND abc.b = xyz.y) OR abc.c = xyz.z`
* Semi-join and anti-join tests with correlated and uncorrelated
</blockquote></details>

Thanks, I've added two new test files in the rules tests and logic tests named disjunction_in_join to cover these cases plus a few more.  Also, I've extended the code to not only support single-column equality, eg. a1 = b1 OR a2 = b2, but multicolumn equality as well: (a1 = b1 AND a2 = b2) OR (a3 = b3 AND a4 = b4).  This includes the join selectivity estimation code in statistics_builder.go.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 9921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms73Iys1xP6IjyWmgpv:-MspcyjU4fj09dj8UHnI:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/testdata/rules/join#L9921)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: it'd be nice to see the output columns of expressions and grouping columns of the distinct-on in the expression trees, so I think you should remove `format=hide-all`.
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2022-01-13 17:00 UTC, rytaft reviewed
Very impressive work here! I've gone through some of the PR and left some comments, but still have about half left. 

> Reviewed 3 of 11 files at r1, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-MtJN-tu0tCymwCehZuu:b-v00se5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 787 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ1LMLBMBK5RsC1bdZ:-MtJ1LMLBMBK5RsC1bd_:b-jhs8qw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L787)):*
> ```Go
> 	// ------------------------------------------------------------------------
> 	if pred != nil {
> 		predUnappliedConjucts, predConstrainedCols, predHistCols := sb.applyFilters(pred, scan, relProps, false)
> ```

nit: `false /* skipOrTermAccounting */`

here and below
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1157 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ0WuED6PX8xiVfaGb:-MtJ0WuED6PX8xiVfaGc:b-bnk3zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L1157)):*
> ```Go
> 			equivReps, h.leftProps.OutputCols, h.rightProps.OutputCols, &h.filtersFD, join, s,
> 		))
> 		var OredTermSelectivity props.Selectivity
> ```

OredTermSelectivity -> oredTermSelectivity

(this variable shouldn't be exported)
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1158 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ0y2LBBG9J7UDxfFO:-MtJ0y2M33Ws5cVWVL13:b-dw7b10) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L1158)):*
> ```Go
> 		))
> 		var OredTermSelectivity props.Selectivity
> 		OredTermSelectivity, numUnappliedConjuncts = sb.selectivityFromOredEquivalencies(h, join, s, numUnappliedConjuncts, true)
> ```

nit: `true /* semiJoin */`
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1177 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ17y1DTqIf-GL5sfj:-MtJ17y1DTqIf-GL5sfk:b-6pqkp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L1177)):*
> ```Go
> 		s.ApplySelectivity(sb.selectivityFromEquivalencies(equivReps, &h.filtersFD, join, s))
> 		var OredTermSelectivity props.Selectivity
> 		OredTermSelectivity, numUnappliedConjuncts = sb.selectivityFromOredEquivalencies(h, join, s, numUnappliedConjuncts, false)
> ```

nit: `false /* semiJoin */`
___
*[pkg/sql/opt/memo/statistics_builder.go, line 2942 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJD598ABT58r-uDrt0:-MtJD598ABT58r-uDrt1:b-mwels5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L2942)):*
> ```Go
> // counts and histograms will be used later to determine the selectivity of
> // the filter. If skipOrTermAccounting is true, OrExpr filters are not counted
> // towards numUnappliedConjuncts.
> ```

It seems like we might want to do this for regular selects in addition to joins -- any reason not to remove this parameter and always try to apply your new logic?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3924 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ21_E6zwfOuVSXWx-:-MtJ21_E6zwfOuVSXWx0:b-piidjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3924)):*
> ```Go
> 	selectivity = props.OneSelectivity
> 	var conjunctSelectivity props.Selectivity
> _FilterLoop:
> ```

We generally try to avoid these sorts of GOTO type features. Any way you can refactor to avoid this? Perhaps a helper function?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3936 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ2YF02cY4JrQ1uZMm:-MtJ2YF02cY4JrQ1uZMn:b-945rs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3936)):*
> ```Go
> 		var filter FiltersItem
> 		var filters FiltersExpr = nil
> 		var filtersFDs []props.FuncDepSet = nil
> ```

you don't need to assign nil, the default construction will be nil

here and below
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3941 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ3CloDn4FepgBaS8e:-MtJ3CloDn4FepgBaS8f:bsw59dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3941)):*
> ```Go
> 		for i := 0; i < len(disjuncts); i++ {
> 			var andFilters FiltersExpr = nil
> 			filtersFD := props.FuncDepSet{}
> ```

nit: `var filtersFD props.FuncDepSet`
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3958 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ3ok56HtiDtsNFI6i:-MtJ3ok56HtiDtsNFI6j:b-fozm8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3958)):*
> ```Go
> 			// If no column equivalencies are found, we know nothing about this term,
> 			// so should skip selectivity estimation on the entire conjunct.
> 			if filtersFD.Empty() {
> ```

even if it's not empty, it's possible that the FD does not contain an equivalency. You might want to check `equivReps` here instead of below.

But it's also possible that we can do better even if equivReps is empty -- e.g., if the column is constant, we can also calculate selectivity for that. See `buildDisjunctionConstraints`, which is doing something similar.

Along those lines, do you think there's a way we can extract a helper function that can be used here and elsewhere in the code for calculating selectivity that would take into account all the different types of selectivity? It's also possible that we are starting to run into the limits of the current design of this stats estimation code. Would be great to chat with you about ideas for how we can improve the state of the world here. 

I don't want to hold up this PR for that, though, so if you don't see a relatively simple approach to extracting a helper function (I don't see anything obvious right now), no worries.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3985 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ8fH_8dt8kQTAI_M3:-MtJ8fH_8dt8kQTAI_M4:bsv7m69) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3985)):*
> ```Go
> 			selectivities = append(selectivities, singleSelectivity)
> 		}
> 		// Iteratively apply the General Disjunction Rule.
> ```

Nice comment and explanation! I agree with this approach as a starting point -- we can consider a more complex solution if we find cases where this is insufficient.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4033 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ9SDZ-FHbCq8VFvjh:-MtJ9SDZ-FHbCq8VFvji:bohzghi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L4033)):*
> ```Go
> // with identical behavior to the Factory method of the same name, but for use
> // in cases where the Factory is not accessible.
> func ConstructFiltersItem(condition opt.ScalarExpr, m *Memo) FiltersItem {
> ```

This function shouldn't be exported (change to `constructFiltersItem`)
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4042 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJBAqzAJ1_zc1tHVT6:-MtJBAqzAJ1_zc1tHVT7:b-ynanqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc [...]

2022-01-13 23:04 UTC, rytaft reviewed
pushing a few more comments

> Reviewed 1 of 11 files at r1, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-MtKfbNI6unLJ9oKvKNR:brkxo2j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[pkg/sql/opt/xform/join_funcs.go, line 1614 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKYcF1EHOWcpxfI9rM:-MtKYcF1EHOWcpxfI9rN:b6u18wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1614)):*
> ```Go
> // For details on what makes an "interesting" disjunction, see
> // findInterestingDisjunctionPairForJoin.
> func (c *CustomFuncs) SplitDisjunctionForJoin(
> ```

does this need to be exported?
___
*[pkg/sql/opt/xform/join_funcs.go, line 1644 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKUtNv0rfJ6V38mjf4:-MtKUtNw2Iac3UR7DdcM:b-9q14qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1644)):*
> ```Go
> 					swapDuplicateScanPrivateOrder = true
> 				}
> 				return
> ```

nit: include return values
___
*[pkg/sql/opt/xform/join_funcs.go, line 1693 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKWxpL0jWb7Rj1Cn0N:-MtKWxpL0jWb7Rj1Cn0O:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1693)):*
> ```Go
> 	ok bool,
> ) {
> ```

nit: remove blank line
___
*[pkg/sql/opt/xform/join_funcs.go, line 1698 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKXFvUEaq_bon2mgLE:-MtKXFvUEaq_bon2mgLF:b-q0tzqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1698)):*
> ```Go
> 		return nil, nil, emptyColSet, emptyColSet, emptyColSet, false
> 	}
> 	type JoinType int64
> ```

why not just use `int`?
___
*[pkg/sql/opt/xform/join_funcs.go, line 1710 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKXcGb0TIvn5qNtGwO:-MtKXcGb0TIvn5qNtGwP:bezetr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1710)):*
> ```Go
> 	var rightInput memo.RelExpr
> 
> 	switch join := joinRel.(type) {
> ```

This is fine, but you could also consider using `joinRel.Child(0)`, `joinRel.Child(1)`, `joinRel.Private()`, and `joinRel.Op()` to avoid having multiple cases in the `switch` (and avoid the need for `joinType`)
___
*[pkg/sql/opt/xform/join_funcs.go, line 1791 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtK_L-z31gP0H-2vx8T:-MtK_L-z31gP0H-2vx8U:b-nfpgjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1791)):*
> ```Go
> 
> 	// Build a new first join with an identical join type to the original join.
> 	if joinType == Inner {
> ```

I'd use a switch here instead
___
*[pkg/sql/opt/xform/join_funcs.go, line 1819 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKaioOBLSQpHLJHkBz:-MtKaioOBLSQpHLJHkC-:b-h8c6bc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1819)):*
> ```Go
> 
> 	// Build a new second join with an identical join type to the original join.
> 	if joinType == Inner {
> ```

ditto here with the switch
___
*[pkg/sql/opt/xform/join_funcs.go, line 1839 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKb0w6Cq7p3RpUJO-M:-MtKb0w6Cq7p3RpUJO-N:bvwr3v0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1839)):*
> ```Go
> 	if joinType == Inner {
> 		aggCols =
> 			c.e.funcs.remapColSet(
> ```

Why do you need to map here? Can't you just get the key columns / non-key columns from the original scans?
___
*[pkg/sql/opt/xform/join_funcs.go, line 1889 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKc6XY5AQBYVgBTrXS:-MtKc6XY5AQBYVgBTrXT:b-27tkjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1889)):*
> ```Go
> 	interesting := true
> 	switch joinRel.(type) {
> 	case *memo.InnerJoinExpr, *memo.SemiJoinExpr, *memo.SemiJoinApplyExpr, *memo.LeftJoinExpr, *memo.RightJoinExpr,
> ```

why are you looking for these specific join types? A comment would help
___
*[pkg/sql/opt/xform/join_funcs.go, line 1896 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKf0qx5IxGpymbLCOY:-MtKf0qyAGW9WCDbbxlz:bv6ugcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1896)):*
> ```Go
> 	}
> 	var leftScan *memo.ScanExpr
> 	var rightScan *memo.ScanExpr
> ```

can you use your new function `getFilteredScan` here?
___
*[pkg/sql/opt/xform/join_funcs.go, line 1952 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKd_vgApbOyjfc5a8F:-MtKd_vgApbOyjfc5a8G:bwkg1gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1952)):*
> ```Go
> 		}
> 
> 		if interesting && leftHasNoJoinPreds {
> ```

why not just check `len(leftExprs)`?
___
*[pkg/sql/opt/xform/select_funcs.go, line 1717 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKemk5Azylbx0PsuAu:-MtKemk5Azylbx0PsuAv:b-qktuvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/select_funcs.go#L1717)):*
> ```Go
> 
> // ScanPrivateCols returns the ColSet of a ScanPrivate.
> func (c *CustomFuncs) ScanPrivateCols(sp *memo.ScanPrivate) opt.ColSet {
> ```

why did you put this function in this file?


<!-- Sent from Reviewable.io -->

2022-01-14 17:34 UTC, rytaft reviewed
Great stuff! I didn't examine every test closely, but seems like you have pretty good test coverage. It would be good to add some explicit stats tests, though.

> Reviewed 2 of 11 files at r1, 2 of 4 files at r2, 1 of 3 files at r4, 1 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-MtOdUW777QdbyqW2pLP:b-g4pvah)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[pkg/sql/opt/xform/rules/join.opt, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms727UCCNb9fw23sULS:-MtOV16K8Tz0zTb_sO1Q:b4x2elv) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/rules/join.opt#L136)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

The code is cleaned up now.  I was seeing better performance in UNION ALL + DISTINCT ON vs. UNION, so was hoping to have one rule to cover both cases, but if you think it makes more sense to have separate rules, we could do that.  The complexity perhaps is contained within the column remapping, such as this code in join_funcs.go:

		aggCols =
			c.e.funcs.remapColSet(
				c.e.funcs.UnionCols(
					c.e.funcs.NonKeyCols(newLeftScan),
					c.e.funcs.NonKeyCols(newRightScan)),
				firstJoinCols,
				amendedOrigCols,
			)

Maybe a line-by-line code walk-through is in order here, to see what's going on.
During expanded testing, as suggested, I did run across an issue in DISTINCT processing, which seems independent of my changes, which I documented here:
https://github.com/cockroachdb/cockroach/issues/74554

I am not sure if such a problem could happen on real customer clusters, but if it could, that issue should probably be fixed before this PR is merged.  If that issue does not affect UNION processing, that may be an argument for introducing a separate UNION rule, which could be merged sooner.
</blockquote></details>

We already have [this rule](https://github.com/cockroachdb/cockroach/blob/71cdf330605ea8b6ad8f1caacea52c70580dd5fc/pkg/sql/opt/norm/rules/set.opt#L139-L167) which will convert a UNION to a UNION ALL + DISTINCT, so maybe you can let that rule handle some of the complexity for you and just plan a UNION here?
___
*[pkg/sql/logictest/testdata/logic_test/disjunction_in_join, line 22 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtOWsZ3E4XkcBYKFBTp:-MtOWsZ41fzcxAmALkO2:bnnm4xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/logictest/testdata/logic_test/disjunction_in_join#L22)):*
> ```
>                INDEX d (d1) STORING (d2, d3, d4))
> 
> # shared column values
> ```

Nice test data!
___
*[pkg/sql/logictest/testdata/logic_test/inner-join, line 3 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtOZEIgCbbT7FbZ3f76:-MtOZEIgCbbT7FbZ3f77:b-it4u3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/logictest/testdata/logic_test/inner-join#L3)):*
> ```
> statement ok
> CREATE TABLE abc (a INT, b INT, c INT, PRIMARY KEY (a, b));
> ALTER TABLE abc INJECT STATISTICS '[
> ```

why did you need to add stats here? are there corresponding `execbuilder` tests that show the plans?
___
*[pkg/sql/logictest/testdata/logic_test/subquery, line 608 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtOYHjY-dRvMG_-TLXj:-MtOYHjY-dRvMG_-TLXk:baf0rhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/logictest/testdata/logic_test/subquery#L608)):*
> ```
> ### Split Disjunctions Tests
> query IIIIII rowsort
> SELECT * FROM abc INNER JOIN xyz on abc.a = xyz.x or abc.b = xyz.y
> ```

nit: we usually try to capitalize the keywords in SQL tests, e.g. ON and OR
___
*[pkg/sql/logictest/testdata/logic_test/subquery, line 615 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtOYzsy3rsp7cgQddAC:-MtOYzsy3rsp7cgQddAD:b-6rnjvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/logictest/testdata/logic_test/subquery#L615)):*
> ```
> 
> query IIIIII rowsort
> SELECT * FROM abc INNER JOIN xyz on abc.a = xyz.y or abc.b = xyz.x
> ```

do these tests make sense in the `subquery` test file? might be worth adding a comment at least to explain why if you want to include them
___
*[pkg/sql/opt/exec/execbuilder/testdata/join, line 2286 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtO_Ev62f-J3xoRtO8t:-MtO_Ev62f-J3xoRtO8u:b-2zfw5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/exec/execbuilder/testdata/join#L2286)):*
> ```
>       spans: FULL SCAN
> 
> # Test selectivity of ORed join predicates
> ```

for testing selectivity, it would be best to add some tests in `memo/testdata/stats`
___
*[pkg/sql/opt/xform/testdata/rules/disjunction_in_join, line 2061 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtOb85mBYY1NSoFvN0k:-MtOb85mBYY1NSoFvN0l:b-8sddxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/testdata/rules/disjunction_in_join#L2061)):*
> ```
>                 └── d4:11
> 
> memo expect=SplitDisjunctionOfJoinTerms
> ```

is there a reason you're only using `memo` here for predicates with multiple ORs?
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1554 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtOci814wlskFqUrNfz:-MtOci814wlskFqUrNg-:bh8x8h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/testdata/rules/join#L1554)):*
> ```
> # split into equality predicates by the SplitDisjunctionOfSemiJoinTerms rule.
> opt expect=CommuteSemiJoin
> SELECT * from abc WHERE EXISTS (SELECT * FROM def WHERE a=d OR c=e)
> ```

would be good to add another test that would continue to test `expect-not=CommuteSemiJoin` with a different predicate
___
*[pkg/sql/opt/xform/testdata/rules/join, line 10419 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtOdEuHDvaEDdvoYXpS:-MtOdEuHDvaEDdvoYXpT:b-79k2kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/testdata/rules/join#L10419)):*
> ```
> 
> # Outer join must use cross join
> opt expect-not=SplitDisjunctionOfJoinTerms
> ```

would be good to add a couple more expect-not type tests, for predicates that do not meet the criteria, etc.


<!-- Sent from Reviewable.io -->

2022-01-14 21:13 UTC, msirek reviewed
thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-MtNOnBH4uw4uRtLKWZx:b-k73z76)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 787 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ1LMLBMBK5RsC1bdZ:-MtNNC0f4HTPqwfdShie:bteari1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L787)):*
> /* skipOrTermAccounting */
Added comment
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1157 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ0WuED6PX8xiVfaGb:-MtNNxVh29rT3zHmdbLW:b-bgm30m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L1157)):*
> OredTermSelectivity
changed
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1158 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ0y2LBBG9J7UDxfFO:-MtNOUx34lTqeXiFGTjb:b-ebkdtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L1158)):*
> changed
Added comment
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1177 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ17y1DTqIf-GL5sfj:-MtNOiz84cuOgbabDy9M:b-z668pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L1177)):*
> Added comment
Added comment
___
*[pkg/sql/opt/memo/statistics_builder.go, line 2942 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJD598ABT58r-uDrt0:-MtNPIa4-x4qwp2rlhgE:b-kuvvh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L2942)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It seems like we might want to do this for regular selects in addition to joins -- any reason not to remove this parameter and always try to apply your new logic?
</blockquote></details>

No reason other than just to limit the size of the PR, since doing so would probably mean more coding and testing is needed.  I haven't really looked into single-table Or'ed term cases yet.  What do you think, should we open a new issue, or just extend the current PR?  The additional work would probably involve writing a new function to combine ORed filters with the same formula used in selectivityFromOredEquivalencies, but instead of calling selectivityFromEquivalencies on each term (as that one seems to be for join terms), it would call applyFiltersItem.  This would be the case for OR'ed terms on different columns (A=1 or B>3 or C=5) which can be considered independent.  I haven't looked at how Ored terms on the same column get simplified, but if they are rewritten into non-overlapping ranges, then we could just add up their selectivities.  I thought I had seen that IN list predicates are already handled in the code, but I didn't see what is currently done for generic OR'ed terms.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3924 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ21_E6zwfOuVSXWx-:-MtNbLJXD7taNdWswga1:bvz7wni) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3924)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

We generally try to avoid these sorts of GOTO type features. Any way you can refactor to avoid this? Perhaps a helper function?
</blockquote></details>

OK, I just added setting of ok to false in all flows where we can't calculate selectivity, then check the value and continue.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3936 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ2YF02cY4JrQ1uZMm:-MtNcKwUATnfPOpeG-LD:b-y02lq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3936)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

you don't need to assign nil, the default construction will be nil

here and below
</blockquote></details>

OK, removed it
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3941 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ3CloDn4FepgBaS8e:-MtNcVJ486Ljoo-CkyKL:b-kjy7jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3941)):*
> filtersFD props.FuncDepSet
removed assignment to nil
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3958 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ3ok56HtiDtsNFI6i:-MtO4VbrCgN8TOzHtEyI:b-ar1ogh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3958)):*
> buildDisjunctionConstraints
Thanks, I added checking if `equivReps` is empty too.  I also refactored the selectivity formula into its own function: `combineOredSelectivities`. 
I think dealing with single table preds (in ON clause) would need some additional study and work instead of being a quick change.  In the code for single-table filter preds, to use as a model for single-table preds in an ORed ON clause, it treats the sets of qualified rows as mutually exclusive by adding the selectivities together:

```
	} else if constraintUnion := sb.buildDisjunctionConstraints(filter); len(constraintUnion) > 0 {
		// The filters are one or more disjunctions and tight constraint sets
		// could be built for each.
		var tmpStats, unionStats props.Statistics
		unionStats.CopyFrom(s)

		// Get the stats for each constraint set, apply the selectivity to a
		// temporary stats struct, and union the selectivity and row counts.
		sb.constrainExpr(e, constraintUnion[0], relProps, &unionStats)
		for i := 1; i < len(constraintUnion); i++ {
			tmpStats.CopyFrom(s)
			sb.constrainExpr(e, constraintUnion[i], relProps, &tmpStats)
			unionStats.UnionWith(&tmpStats)  <<<---------------------------------
		}
```
this works if the predicates involve the same column and the ranges are not overlapping, e.g. A < 1 OR A > 6.  But for other combinations of predicates , e.g. A < 1 OR B < 1, we should not have the expectation that the A < 1 set doesn't overlap with the B < 1 set, so could maybe use the formula in `combineOredSelectivities` in that case.  So, we may want to look more closely into which cases should use `combineOredSelectivities` instead of just always using it for ORs.  Likewise with ON clause predicates with constants.  When I was working on this PR, I was considering whether it would be worthwhile to write a generic recursive function which could handle any nested depth of ORs and ANDs.  Each successive level would calculate its selectivity independently and then pass it up the call stack, combining selectivities with the appropriate method depending on whether we're handling an OR or an AND at that level.  I don't know if predicates get this fancy in real life, or if the estimates might end up being not so accurate anyway due to independence assumptions between all the predicates, but I decided to handle the simple use cases first.  Maybe it would be a good exercise to try to find some real-world use cases, both single-table and join cases, which we don't currently handle well.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3985 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ8fH_8dt8kQTAI_M3:-MtOBmeW8-FsaJqzK4Q8:b-k73z76) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3985)):*
<details><summary><i>Previously, rytaft (Rebe [...]

2022-01-16 16:46 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/join_funcs.go, line 1839 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKb0w6Cq7p3RpUJO-M:-MtYkAOV1jDdrTNCpRHP:bhatoz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1839)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

If not all primary key columns in origLeftScan or origRightScan are referenced in the query, then making a function call like NonKeyCols(origLeftScan) will hit an internal error:
```
ERROR: internal error: expected expression to have key
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/opt/norm/decorrelate_funcs.go:425: NonKeyCols()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:1833: SplitJoinWithEquijoinDisjuncts()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.og.go:523: exploreInnerJoin()
...
...
```
So, calling NonKeyCols and KeyCols on the new left and right scans which include the key columns is required.  To make it work without remapping we'd probably need to maintain a separate `FuncDepSet` in `props.Relational` which represents the Scan including all columns in the table, whether or not the actual Scan includes them.
</blockquote></details>

I suppose it would be possible to construct 2 temporary scans using leftSP and rightSP (which have all PK columns added in), just for the purposes of calling NonKeyCols and KeyCols.  It may be easier to read and understand, but possibly could involve a little more processing and memory overhead since we're building new Scans which are not used in the memo.  Do you have a preference, remapping columns vs. constructing temporary Scans?



_Code quote:_
```Go
amendedLeftOrigCols
```


<!-- Sent from Reviewable.io -->

2022-01-18 17:50 UTC, rytaft reviewed
> Reviewed 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2942 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJD598ABT58r-uDrt0:-Mti6wiwBbih0AO1P0Y2:b-o6dck) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L2942)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

No reason other than just to limit the size of the PR, since doing so would probably mean more coding and testing is needed.  I haven't really looked into single-table Or'ed term cases yet.  What do you think, should we open a new issue, or just extend the current PR?  The additional work would probably involve writing a new function to combine ORed filters with the same formula used in selectivityFromOredEquivalencies, but instead of calling selectivityFromEquivalencies on each term (as that one seems to be for join terms), it would call applyFiltersItem.  This would be the case for OR'ed terms on different columns (A=1 or B>3 or C=5) which can be considered independent.  I haven't looked at how Ored terms on the same column get simplified, but if they are rewritten into non-overlapping ranges, then we could just add up their selectivities.  I thought I had seen that IN list predicates are already handled in the code, but I didn't see what is currently done for generic OR'ed terms.
</blockquote></details>

Opening an issue would be great -- I agree we shouldn't further complicate this PR.

OR terms on single variables should already be handled by the constraints code, and we use constraints to calculate selectivity in this case.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3941 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ3CloDn4FepgBaS8e:-Mti7YW3EMwHUAInm0zW:b-lvodyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3941)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> filtersFD props.FuncDepSet
removed assignment to nil
</blockquote></details>

was suggesting that you use default construction instead of `filtersFD := props.FuncDepSet{}`
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3958 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ3ok56HtiDtsNFI6i:-MtiCXLP383pyiPCOCdq:b-qwev6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3958)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> buildDisjunctionConstraints
Thanks, I added checking if `equivReps` is empty too.  I also refactored the selectivity formula into its own function: `combineOredSelectivities`. 
I think dealing with single table preds (in ON clause) would need some additional study and work instead of being a quick change.  In the code for single-table filter preds, to use as a model for single-table preds in an ORed ON clause, it treats the sets of qualified rows as mutually exclusive by adding the selectivities together:

```
	} else if constraintUnion := sb.buildDisjunctionConstraints(filter); len(constraintUnion) > 0 {
		// The filters are one or more disjunctions and tight constraint sets
		// could be built for each.
		var tmpStats, unionStats props.Statistics
		unionStats.CopyFrom(s)

		// Get the stats for each constraint set, apply the selectivity to a
		// temporary stats struct, and union the selectivity and row counts.
		sb.constrainExpr(e, constraintUnion[0], relProps, &unionStats)
		for i := 1; i < len(constraintUnion); i++ {
			tmpStats.CopyFrom(s)
			sb.constrainExpr(e, constraintUnion[i], relProps, &tmpStats)
			unionStats.UnionWith(&tmpStats)  <<<---------------------------------
		}
```
this works if the predicates involve the same column and the ranges are not overlapping, e.g. A < 1 OR A > 6.  But for other combinations of predicates , e.g. A < 1 OR B < 1, we should not have the expectation that the A < 1 set doesn't overlap with the B < 1 set, so could maybe use the formula in `combineOredSelectivities` in that case.  So, we may want to look more closely into which cases should use `combineOredSelectivities` instead of just always using it for ORs.  Likewise with ON clause predicates with constants.  When I was working on this PR, I was considering whether it would be worthwhile to write a generic recursive function which could handle any nested depth of ORs and ANDs.  Each successive level would calculate its selectivity independently and then pass it up the call stack, combining selectivities with the appropriate method depending on whether we're handling an OR or an AND at that level.  I don't know if predicates get this fancy in real life, or if the estimates might end up being not so accurate anyway due to independence assumptions between all the predicates, but I decided to handle the simple use cases first.  Maybe it would be a good exercise to try to find some real-world use cases, both single-table and join cases, which we don't currently handle well.

</blockquote></details>

Sounds good to me. Let's leave this as-is for now.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4005 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtiCzr4-r-SdY8kk9fx:-MtiCzr5Cn5fi25PhHNT:b-p2jkvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4f778ba4c6aeb3e077fb6ca2670832a4c126688/pkg/sql/opt/memo/statistics_builder.go#L4005)):*
> ```Go
> // combineOredSelectivities iteratively applies the General Disjunction Rule
> // on a slice of 'selectivities' where each selectivity in the slice is the
> // selectivity on an individual ORed predicate.
> ```

nit: selectivity on -> selectivity of ?
___
*[pkg/sql/opt/xform/join_funcs.go, line 1839 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKb0w6Cq7p3RpUJO-M:-MtiE7tU6uE6AgFzLp8W:bhzlmez) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1839)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I suppose it would be possible to construct 2 temporary scans using leftSP and rightSP (which have all PK columns added in), just for the purposes of calling NonKeyCols and KeyCols.  It may be easier to read and understand, but possibly could involve a little more processing and memory overhead since we're building new Scans which are not used in the memo.  Do you have a preference, remapping columns vs. constructing temporary Scans?
</blockquote></details>

There are a couple of functions that give you the primary keys without needing a reference to any relational expression. Here: https://github.com/cockroachdb/cockroach/blob/5fd739be5dbfcd8d08f83f7f0f24b302c85bb50d/pkg/sql/opt/xform/join_funcs.go#L1089
and here:
https://github.com/cockroachdb/cockroach/blob/c38023e5350b191fae4ea7f36d561d3b309212d2/pkg/sql/opt/norm/general_funcs.go#L524

Would these be sufficient?
___
*[pkg/sql/opt/xform/join_funcs.go, line 1889 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKc6XY5AQBYVgBTrXS:-MtiFF7Y9N-cME1JIrkf:bu318xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1889)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I was just trying to make a generic test to check if we have a join in hand, so the code here wouldn't have to get updated if we start supporting more joins.  But since we can't test those other cases now anyway, it's probably better to just remove them, which is what I've done.
</blockquote></details [...]

2022-01-19 03:54 UTC, msirek reviewed
Thanks.  For explicit stats tests, I guess you mean in addition to what I put in `pkg/sql/opt/memo/testdata/stats/join`, maybe with faked stats?   OK, I've added some in that file.  The results aren't all that interesting.  I was going to try INSERT SELECTing some actual data to see if with histograms the selectivity would vary more for each predicate, but the test was injecting a couple extra keywords into my SQL, and it errored out: `unsupported statement: INSERT INTO classes SELECT g, 'dummy description' FROM ROWS FROM (generate_series(1, 5000)) AS g (g)`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-MtkDkeUCFy1yl7cHYCH:b-4l8odh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2942 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJD598ABT58r-uDrt0:-MtiPJfd4d1Ii2AkiXqF:bffr8ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L2942)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Opening an issue would be great -- I agree we shouldn't further complicate this PR.

OR terms on single variables should already be handled by the constraints code, and we use constraints to calculate selectivity in this case.
</blockquote></details>

OK, thanks.  The disjunction rule may still help in combining selectivities of predicates on different columns for Selects.  Opened https://github.com/cockroachdb/cockroach/issues/75090
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3941 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ3CloDn4FepgBaS8e:-MtiQ7NJ52jZXe1wNuqW:b-z485sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3941)):*
> var filtersFD props.FuncDepSet
OK, got it.  Fixed.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3958 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtJ3ok56HtiDtsNFI6i:-MtiQIvD91EXlO20i9LA:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/memo/statistics_builder.go#L3958)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Sounds good to me. Let's leave this as-is for now.
</blockquote></details>

OK
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4005 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtiCzr4-r-SdY8kk9fx:-MtiQYhJCUGO4E68wUoS:b-qdqpkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4f778ba4c6aeb3e077fb6ca2670832a4c126688/pkg/sql/opt/memo/statistics_builder.go#L4005)):*
> selectivity on
fixed
___
*[pkg/sql/opt/xform/join_funcs.go, line 1839 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKb0w6Cq7p3RpUJO-M:-MtiW1I_8YjtRlJnk3c3:b-py12cl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1839)):*
> PrimaryKeyCols(
Perfect.  I rewrote this code using PrimaryKeyCols and removed the definition of remapColSet.
___
*[pkg/sql/opt/xform/join_funcs.go, line 1889 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtKc6XY5AQBYVgBTrXS:-MtiWw_ZDi96Y7hbflM4:b-gp0pme) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/join_funcs.go#L1889)):*
> IsJoinOp
Thanks, changed the check to use `isJoinOp()`
___
*[pkg/sql/opt/xform/rules/join.opt, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms727UCCNb9fw23sULS:-Mtk-NLbCE1rCX6lAfUP:b-243kq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/rules/join.opt#L136)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

yea -- I think that type of exploration can be done as a separate rule. If it results in a simpler rule here, I think it's worth it to let the other rule convert to UNION ALL + DISTINCT. But if it doesn't simplify much, then no need.
</blockquote></details>

As discussed offline, will keep this unchanged for now.  The complexity reason is going away because column remapping is removed.  Using UNION would split this into 6 different rules (it's currently 2 rules), because semijoin only needs to check for PK inclusion on the left.  We could always push more matching logic into `splitDisjunctionForJoin` to keep the number of rules low, but we may still need 4 rules unless we also want to push generation of the replacement statements into that function.  Let's see what @mgartner thinks.
___
*[pkg/sql/logictest/testdata/logic_test/inner-join, line 3 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtOZEIgCbbT7FbZ3f76:-Mtk6-ye7YBkbizh9Y0n:bpcw9ur) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/logictest/testdata/logic_test/inner-join#L3)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

If you want to show that we're choosing the correct plan for some of these cases, then you could add a few more `execbuilder` tests, but you don't need to completely duplicate the tests.
</blockquote></details>

OK, created test file inner-join in execbuilder.
___
*[pkg/sql/logictest/testdata/logic_test/subquery, line 61 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtiFzmQC5LzvAP5SKDy:-Mtk6_dT9r-PmVNLziEz:bje28c1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4f778ba4c6aeb3e077fb6ca2670832a4c126688/pkg/sql/logictest/testdata/logic_test/subquery#L61)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you mean to make this change?
</blockquote></details>

No, I was finding and replacing SQL keywords.  Corrected it.



_Code quote:_
```
sub-expression being shared by two OR more plan nodes does not
```
___
*[pkg/sql/logictest/testdata/logic_test/subquery, line 432 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtiG0t70E5nF_idG0lf:-Mtk6i0Z0eFCKyu_vGG4:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4f778ba4c6aeb3e077fb6ca2670832a4c126688/pkg/sql/logictest/testdata/logic_test/subquery#L432)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed
___
*[pkg/sql/opt/xform/testdata/rules/disjunction_in_join, line 2061 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtOb85mBYY1NSoFvN0k:-Mtk758U42WQidfUtSt3:b-o1j4o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/testdata/rules/disjunction_in_join#L2061)):*
> Fixed
I did think there was a costing issue (though not related to this particular test case), and had talked to @jordanlewis about it.  He let me know about @rharding6373 's average column size costing PR, https://github.com/cockroachdb/cockroach/pull/74251, which seems to fix the issue.  I merged it with my code in a different branch and tested some large table cases.  For this specific case, it would have to do 4 scans in the split join plan, so it's not surprising the split is not picked.  We don't want to get too aggressive with scan costing because I don't think we're even modeling latency right now anyway.  But maybe I'm wrong, I haven't looked too closely.
___
*[pkg/sql/opt/xform/testdata/rules/disjunction_in_join, line 647 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtiGIGL3rZsflOC1nZs:-Mtk71FrCT19IsSJuASp:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4f778ba4c6aeb3e077fb6ca2670832a4c126688/pkg/sql/opt/xform/testdata/rules/disjunction_in_join#L647)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summ [...]

2022-01-19 14:57 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> but let's see if @mgartner has any additional feedback

> Thanks.  For explicit stats tests, I guess you mean in addition to what I put in pkg/sql/opt/memo/testdata/stats/join, maybe with faked stats?

That comment was from my previous review -- I thought the stats tests you added that uncovered the bug requiring `UnsafeAdd` were good. But I think the ones you just added are also useful, so no need to change anything.

> unsupported statement: INSERT INTO classes SELECT g, 'dummy description' FROM ROWS FROM (generate_series(1, 5000)) AS g (g)

That's odd -- I just tried running this in `cockroach demo` and it worked for me:
```
> create table classes (i int, s string);
CREATE TABLE

Time: 8ms total (execution 8ms / network 0ms)

> INSERT INTO classes SELECT g, 'dummy description' FROM ROWS FROM (generate_series(1, 5000)) AS g (g);
INSERT 5000

Time: 68ms total (execution 67ms / network 0ms)
```

> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-MtmofTs1p90X0Ya_yBr:bo2k2lv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/testdata/rules/disjunction_in_join, line 2061 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtOb85mBYY1NSoFvN0k:-MtmoGxzCP35zcgVtCPc:b1ubcge) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2dcd88c81ff4c0dd582aa6ffd6fa87ea78d4fc/pkg/sql/opt/xform/testdata/rules/disjunction_in_join#L2061)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> Fixed
I did think there was a costing issue (though not related to this particular test case), and had talked to @jordanlewis about it.  He let me know about @rharding6373 's average column size costing PR, https://github.com/cockroachdb/cockroach/pull/74251, which seems to fix the issue.  I merged it with my code in a different branch and tested some large table cases.  For this specific case, it would have to do 4 scans in the split join plan, so it's not surprising the split is not picked.  We don't want to get too aggressive with scan costing because I don't think we're even modeling latency right now anyway.  But maybe I'm wrong, I haven't looked too closely.
</blockquote></details>

Makes sense


<!-- Sent from Reviewable.io -->

2022-01-21 17:07 UTC, mgartner requested changes
This is looking great! I still have to look at the stats changes, stats tests, and logic tests, but I'll leave some comments (mostly nit-picks) for now.

> Reviewed 1 of 4 files at r2, 2 of 13 files at r7, 2 of 7 files at r8, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-Mtxa_S_1CIAxdgm8DXZ:b-yvtqfl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[pkg/sql/opt/props/selectivity.go, line 73 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxNtldEi2yHwGobvrZ:-MtxNtldEi2yHwGobvr_:b-bpetg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/props/selectivity.go#L73)):*
> ```Go
> // UnsafeAdd finds the sum of two selectivities and modifies
> // the selectivity specified in the receiver to equal the sum.
> // If does not do a range check to make sure the result is between 0 and 1.
> ```

nit `If` => `It`.
___
*[pkg/sql/opt/xform/general_funcs.go, line 115 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxSkkQ5f1ckBMCnkqm:-MtxSkkQ5f1ckBMCnkqn:b63jm3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/general_funcs.go#L115)):*
> ```Go
> // than a *ScanExpr, ok=false is returned. Scans or Selects with no filters may
> // return filters as nil.
> func (c *CustomFuncs) getfilteredScan(
> ```

nit: This seems specific enough to the new rule that you could move it to `join_funcs.go` I think.
___
*[pkg/sql/opt/xform/join_funcs.go, line 1630 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxO-k8EDP7ecgAjO9_:-MtxO-k8EDP7ecgAjO9a:b-o41138) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1630)):*
> The scan with lower column ids is expected on the left.

Is this a requirement that I'm unaware of, or is this purely an aesthetic improvement to the optimizer expression trees in tests? If it's aesthetic only, I'd say we should remove the code complexity that this introduces.
___
*[pkg/sql/opt/xform/join_funcs.go, line 1661 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxIZsC1XekSLVpmRkg:-MtxIZsC1XekSLVpmRkh:b-b0ngtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1661)):*
> ```Go
> 		c.e.f.ConstructSelect(
> 			newScan,
> 			c.e.funcs.MapFilterCols(filters, origCols, c.e.funcs.OutputCols(newScan)),
> ```

nit: `c.e.funcs.MapFilterCols(...)` can be simplified to `c.MapFilterCols(...)`. Same with `c.e.funcs.OutputCols` here and below.
___
*[pkg/sql/opt/xform/join_funcs.go, line 1663 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxJFYl9R1HJ-_C6fip:-MtxJFYl9R1HJ-_C6fiq:bn0d538) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1663)):*
> ```Go
> 			c.e.funcs.MapFilterCols(filters, origCols, c.e.funcs.OutputCols(newScan)),
> 		)
> 	newCols = c.e.funcs.OutputCols(newScan)
> ```

nit: you could move this up and use it in `c.MapFilterCols`
___
*[pkg/sql/opt/xform/join_funcs.go, line 1678 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxJQBnCdi7AJMk0HnA:-MtxJQBnCdi7AJMk0HnB:boqzzk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1678)):*
> ```Go
> // column ids from the original left Scan plus primary key columns from the left
> // relation.
> // aggCols contains the non-key columns of the left and right inputs.
> ```

super nit: we commonly separate paragraphs in comments with blank lines starting with `//`
___
*[pkg/sql/opt/xform/join_funcs.go, line 1710 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxPy_10Q6SzoeHhvrH:-MtxPy_10Q6SzoeHhvrI:b-axy9vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1710)):*
> ```Go
> 		// Do nothing
> 	default:
> 		return notOkSplitJoin()
> ```

In this case I think a `panic(errors.AssertionFailedf("expected joinRel to be inner, semi, or anti-join"))` is more appropriate here than returning `ok=false` because this code path should never occur.
___
*[pkg/sql/opt/xform/join_funcs.go, line 1713 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxQOJ31tcRGug2gJZr:-MtxQOJ31tcRGug2gJZs:b-7yptcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1713)):*
> ```Go
> 	}
> 
> 	origLeftScan, origLeftScanPrivate, leftFilters, ok := c.e.funcs.getfilteredScan(leftInput)
> ```

nit: `c.e.funcs.getFilteredScan` => `c.getFilteredScan` here and below
___
*[pkg/sql/opt/xform/join_funcs.go, line 1717 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxSAiL09Rb4Ea7rwvi:-MtxSAiL09Rb4Ea7rwvj:b-t02ego) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1717)):*
> ```Go
> 		return notOkSplitJoin()
> 	}
> 	origRightScan, origRightScanPrivate, rightFilters, ok := c.e.funcs.getfilteredScan(rightInput)
> ```

nit: It's a bit awkward to call `getFilteredScan` here to pass in the original scans to `splitDisjunctionForJoin`, which in turn leads to `getFilteredScan` being called again in `findInterestingDisjunctionPairForJoin`. Maybe there's a way to consolidate? 

Also, you might consider moving the canonical check to `getFilteredScan` and renaming it `getFilteredCanonicalScan`.
___
*[pkg/sql/opt/xform/join_funcs.go, line 1730 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxRcb84HvJm4RZkgrM:-MtxRcb84HvJm4RZkgrN:b-h59bty) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1730)):*
> ```Go
> 	// Add in the primary key columns so the caller can group by them to
> 	// deduplicate results.
> 	leftSP := c.e.funcs.AddPrimaryKeyColsToScanPrivate(origLeftScanPrivate)
> ```

`AddPrimaryKeyColsToScanPrivate()` always allocates a new scanPrivate and performs some computation to generate a new ColSet. I don't think we should call this function if we don't need to, i.e. if the PK cols are already included in the original scan private.
___
*[pkg/sql/opt/xform/join_funcs.go, line 1741 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxT8a62DRriJarY3K3:-MtxT8a62DRriJarY3K4:b6q9hdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1741)):*
> ```Go
> 	// new joins we're building.
> 	newLeftScanPrivate, newRightScanPrivate :=
> 		c.e.funcs.duplicateScanPrivatesForJoin(leftSP, rightSP, swapDuplicateScanPrivateOrder)
> ```

nit: `c.e.funcs.` => `c.` here and below
___
*[pkg/sql/opt/xform/join_funcs.go, line 1841 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxUngD2an3_qTQuGoF:-MtxUngD2an3_qTQuGoG:bukrgjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1841)):*
> ```Go
> // from both leftRelColSet and rightRelColSet, as indicated in the predicate's
> // referenced columns, predCols.
> func isJoinPred(predCols opt.ColSet, leftRelColSet opt.ColSet, rightRelColSet opt.ColSet) bool {
> ```

nit: this is probably specific enough that you could make it an anonymous function within `findInterestingDisjunctionPairForJoin`:

```go
isJoinPred := func(predCols, leftRelColSet, rightRelColSet opt.ColSet) bool {
    // ...
}
```
___
*[pkg/sql/opt/xform/join_funcs.go, line 1865 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxUCNsEavEY5Yl-ra5:-MtxUCNsEavEY5Yl-ra6:b-neoka7) ([raw file](https://github.com/c [...]

2022-02-16 21:21 UTC, msirek reviewed
Thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-Mw32F1oA9nDuHjw4aR_:b-zcjvte)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/props/selectivity.go, line 73 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxNtldEi2yHwGobvrZ:-Mw2_YZRDpD3bkm8ClNU:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/props/selectivity.go#L73)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit `If` => `It`.
</blockquote></details>

Fixed



_Code quote:_
```Go
// If does not do a range check to make sure the result is between 0 and 1.
```
___
*[pkg/sql/opt/xform/join_funcs.go, line 1630 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxO-k8EDP7ecgAjO9_:-Mw2bRdnDPaWngdYy-JD:bvwgf5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1630)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> The scan with lower column ids is expected on the left.

Is this a requirement that I'm unaware of, or is this purely an aesthetic improvement to the optimizer expression trees in tests? If it's aesthetic only, I'd say we should remove the code complexity that this introduces.
</blockquote></details>

This is required.  I've added the comment:
```
				// This is required because ColumnID mapping of the join filters is done
				// in a single pass from a source ColSet including both left and right
				// join relations to the combined target ColSets of the duplicated left
				// and right scans (see newJoinFilters in
				// SplitJoinWithEquijoinDisjuncts) So, getting the order wrong would
				// mean incorrect mapping of ColumnIDs in the left table to ColumnIDs in
				// the right table, or vice versa.
```
This is the code that needs it:
```
	// Assign the firstOnClause, which was built from splitting the disjunction,
	// to the first new join.
	newJoinFilters :=
		c.e.funcs.MapFilterCols(
			c.e.funcs.ReplaceFiltersItem(joinFilters, itemToReplace, firstOnClause),
			amendedOrigCols,
			c.e.funcs.UnionCols(newLeftCols, newRightCols),
		)
```
The alternative would be 2 separate calls to MapFilterCols (and possibly 2 calls to ReplaceFiltersItem?).



_Code quote:_
```Go
if filters[i].Condition.Op() == opt.OrOp {
```
___
*[pkg/sql/opt/xform/join_funcs.go, line 1661 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxIZsC1XekSLVpmRkg:-Mw2gIAj133_CzYJIn4X:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1661)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `c.e.funcs.MapFilterCols(...)` can be simplified to `c.MapFilterCols(...)`. Same with `c.e.funcs.OutputCols` here and below.
</blockquote></details>

Done
___
*[pkg/sql/opt/xform/join_funcs.go, line 1663 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxJFYl9R1HJ-_C6fip:-Mw2gWLrElh5jvBEROG4:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1663)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you could move this up and use it in `c.MapFilterCols`
</blockquote></details>

Done



_Code quote:_
```Go
func (c *CustomFuncs) makeFilteredSelectForJoin(
```
___
*[pkg/sql/opt/xform/join_funcs.go, line 1678 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxJQBnCdi7AJMk0HnA:-Mw2gcdi0A9wEUzBj0KX:birux39) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1678)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

super nit: we commonly separate paragraphs in comments with blank lines starting with `//`
</blockquote></details>

Done.  This does make it easier to read.



_Code quote:_
```Go
// SplitJoinWithEquijoinDisjuncts checks a join relation for a disjunction of
```
___
*[pkg/sql/opt/xform/join_funcs.go, line 1710 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxPy_10Q6SzoeHhvrH:-Mw2h4gg9ScJwEi7WMqJ:b-9dqe2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1710)):*
> panic(errors.AssertionFailedf("expected joinRel to be inner, semi, or anti-join"))

Added the panic
___
*[pkg/sql/opt/xform/join_funcs.go, line 1713 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxQOJ31tcRGug2gJZr:-Mw2h9IK2RN47AcPAXpG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1713)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `c.e.funcs.getFilteredScan` => `c.getFilteredScan` here and below
</blockquote></details>

Done
___
*[pkg/sql/opt/xform/join_funcs.go, line 1717 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxSAiL09Rb4Ea7rwvi:-Mw2tNwP1iLKdGjP5b8w:bjs1s1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1717)):*
> getFilteredScan

Added parameters `leftScan` and `rightScan` to `findInterestingDisjunctionPairForJoin` to eliminate the redundant calls and changed `getFilteredScan` to `getFilteredCanonicalScan`.
___
*[pkg/sql/opt/xform/join_funcs.go, line 1730 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxRcb84HvJm4RZkgrM:-Mw2wCec64UA7I5fI-vL:b-7uqqfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1730)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`AddPrimaryKeyColsToScanPrivate()` always allocates a new scanPrivate and performs some computation to generate a new ColSet. I don't think we should call this function if we don't need to, i.e. if the PK cols are already included in the original scan private.
</blockquote></details>

Changed as suggested.



_Code quote:_
```Go
Add in the primary key columns so the caller can group by them to
```
___
*[pkg/sql/opt/xform/join_funcs.go, line 1741 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxT8a62DRriJarY3K3:-Mw2wJSZ41yHs6nubw7b:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1741)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `c.e.funcs.` => `c.` here and below
</blockquote></details>

Done



_Code quote:_
```Go
duplicateScanPrivatesForJoin
```
___
*[pkg/sql/opt/xform/join_funcs.go, line 1841 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxUngD2an3_qTQuGoF:-Mw2wqgz32xgL5Yd7Wmh:b-t60f84) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1841)):*
> isJoinPred := func(predCols, leftRelColSet, rightRelColSet opt.ColSet) bool

Done
___
*[pkg/sql/opt/xform/join_funcs.go, line 1865 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxUCNsEavEY5Yl-ra5:-Mw2xEGf4B4kg_xup1S6:b-dgydi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1865)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: this should probably be a `panic(errors.AssertionFailedf(...))` too
</blockquote></details>

Added the panic
___
*[pkg/sql/opt/xform/join_funcs.go, line 1885 at r9](https://reviewable.io/rev [...]

2022-03-15 15:06 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> though it looks like there's some tests to iron out, and probably a few rebase conflicts to fix, e.g. to address the recent changes related to `MapFilterCols`.

I guess the question is whether or not we want to get this into 22.1. I'm hesitant because it was difficult to get the similar rule `SplitDisjunction` working well: https://github.com/cockroachdb/cockroach/pull/48025, https://github.com/cockroachdb/cockroach/pull/62187, https://github.com/cockroachdb/cockroach/pull/58434, https://github.com/cockroachdb/cockroach/pull/52499, https://github.com/cockroachdb/cockroach/issues/58744, https://github.com/cockroachdb/cockroach/issues/56690 (still an outstanding issue).

> Reviewed 2 of 13 files at r7, 2 of 7 files at r8, 8 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-MyD4Pev4aBTFTr3-iOZ:bng2uvd)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[pkg/sql/opt/xform/join_funcs.go, line 1630 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxO-k8EDP7ecgAjO9_:-MyCxEZ958c33-eWlUCq:b-n4is5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1630)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

This is required.  I've added the comment:
```
				// This is required because ColumnID mapping of the join filters is done
				// in a single pass from a source ColSet including both left and right
				// join relations to the combined target ColSets of the duplicated left
				// and right scans (see newJoinFilters in
				// SplitJoinWithEquijoinDisjuncts) So, getting the order wrong would
				// mean incorrect mapping of ColumnIDs in the left table to ColumnIDs in
				// the right table, or vice versa.
```
This is the code that needs it:
```
	// Assign the firstOnClause, which was built from splitting the disjunction,
	// to the first new join.
	newJoinFilters :=
		c.e.funcs.MapFilterCols(
			c.e.funcs.ReplaceFiltersItem(joinFilters, itemToReplace, firstOnClause),
			amendedOrigCols,
			c.e.funcs.UnionCols(newLeftCols, newRightCols),
		)
```
The alternative would be 2 separate calls to MapFilterCols (and possibly 2 calls to ReplaceFiltersItem?).
</blockquote></details>

If you use the new `RemapScanColsInFilter` (or `RemapCols` if the first option isn't appropriate), does this requirement go away?
___
*[pkg/sql/opt/xform/join_funcs.go, line 2029 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MyD2iFO-KmnyG_Gflp2:-MyD2iFO-KmnyG_Gflp3:b-oi4t4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/715d5126b28fe76030cd9c1a172388daeb342267/pkg/sql/opt/xform/join_funcs.go#L2029)):*
> ```Go
> // an "interesting" pair of join predicates.
> //
> // An "interesting" pair of predicates is one where one predicate is an
> ```

Is there value in performing the split if the columns in the left and right scalar expressions are not indexed? I guess there might be if it transforms a cross-join into a hash-join, is that correct? 

For SplitDisjunction, we ensure that the rule only fires if there is some chance that splitting up the disjunction will lead to constrained indexed scans on both sides of the disjunction, so that we don't needlessly increase the size of the memo:

https://github.com/cockroachdb/cockroach/blob/2fdd9aebb4315f73b4e78e804dd718194b37ffed/pkg/sql/opt/xform/select_funcs.go#L1671-L1678
___
*[pkg/sql/opt/xform/testdata/rules/disjunction_in_join, line 33 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MyCzgmu5KnHEskal_O5:-MyCzgmv0X9WUOmyBJrh:b-p2d9d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/715d5126b28fe76030cd9c1a172388daeb342267/pkg/sql/opt/xform/testdata/rules/disjunction_in_join#L33)):*
> ```
> 
> # The left AND right sides of the join already produce key columns
> memo expect=SplitDisjunctionOfJoinTerms
> ```

Why do some of these tests show the memo rather than just the final plan? If the purpose of these tests is to ensure that the rule creates valid transformations, it's very difficult to determine this by looking at the memo.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 9896 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-Ms74sZwDqcewJDwmB6Z:-MyD1jy6E0BYMjj1VqmB:bqyqot3) ([raw file](https://github.com/cockroachdb/cockroach/blob/42ce2b2d7196c784351bd1a06c9859fca298879b/pkg/sql/opt/xform/testdata/rules/join#L9896)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Thanks, I've added two new test files in the rules tests and logic tests named disjunction_in_join to cover these cases plus a few more.  Also, I've extended the code to not only support single-column equality, eg. a1 = b1 OR a2 = b2, but multicolumn equality as well: (a1 = b1 AND a2 = b2) OR (a3 = b3 AND a4 = b4).  This includes the join selectivity estimation code in statistics_builder.go.
</blockquote></details>

Thanks! Should these tests live in the new rules test file? Or is there a reason you've split them up?


<!-- Sent from Reviewable.io -->

2022-03-21 01:43 UTC, msirek reviewed
Right.  Maybe it should merge just to master.  If there is an urgent need to backport it, we could always reconsider.  It looks like the `release-22.1` branch already exists. I suppose this means anything merging to master will go in the next release and not end up in 22.1?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-Mydh2rY0wMljNCXCmww:b-pbfiqg)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/join_funcs.go, line 1630 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MtxO-k8EDP7ecgAjO9_:-Mydsho9BCXkc7NYghc0:b54k7n2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e92cf4943c426ed40cd5dc49b8485a22fca37bda/pkg/sql/opt/xform/join_funcs.go#L1630)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If you use the new `RemapScanColsInFilter` (or `RemapCols` if the first option isn't appropriate), does this requirement go away?
</blockquote></details>

I thought the requirement would go away, but when I tried removing this logic I found a problem case.  Not only the old remapping method relies on left and right scans maintaining the same relative order of column ids, so does construction of the UNION ALL.  Here's one problem cases that shows how the plan can go bad, with one branch of the UNION ALL seeing `x` as the first column, and another branch seeing `a` as the first column:
```
EXPLAIN(verbose)
SELECT * FROM abc WHERE EXISTS (SELECT * FROM xyz WHERE (abc.a = xyz.x OR abc.b = xyz.y) AND (abc.a = xyz.y OR abc.b = xyz.y));
                                                       info
-------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • distinct
  │ columns: (a, b, c)
  │ estimated row count: 0
  │ distinct on: x
  │
  └── • project
      │ columns: (x, y, a)
      │
      └── • distinct
          │ columns: (x, y, a, b, c)
          │ estimated row count: 1,002
          │ distinct on: x, b
          │
          └── • union all
              │ columns: (x, y, a, b, c)
              │ estimated row count: 1,002
              │
              ├── • distinct
              │   │ columns: (x, y, a, b, c)
              │   │ estimated row count: 1
              │   │ distinct on: x, b
              │   │
              │   └── • union all
              │       │ columns: (x, y, a, b, c)
              │       │ estimated row count: 1
              │       │
              │       ├── • lookup join (inner)
              │       │   │ columns: (x, y, a, b, c)
              │       │   │ estimated row count: 1
              │       │   │ table: abc@abc_pkey
              │       │   │ equality: (x) = (a)
              │       │   │ equality cols are key
              │       │   │
              │       │   └── • filter
              │       │       │ columns: (x, y)
              │       │       │ estimated row count: 1
              │       │       │ filter: x = y
              │       │       │
              │       │       └── • scan
              │       │             columns: (x, y)
              │       │             estimated row count: 1,000 (100% of the table; stats collected 1420 days ago)
              │       │             table: xyz@xyz_y
              │       │             spans: /!NULL-
              │       │
              │       └── • lookup join (inner)
              │           │ columns: (x, y, a, b, c)
              │           │ estimated row count: 0
              │           │ table: abc@abc_pkey
              │           │ equality: (a) = (a)
              │           │ equality cols are key
              │           │
              │           └── • lookup join (inner)
              │               │ columns: (x, y, a, b)
              │               │ estimated row count: 0
              │               │ table: abc@abc_b
              │               │ equality: (y, x) = (b,a)
              │               │ equality cols are key
              │               │
              │               └── • scan
              │                     columns: (x, y)
              │                     estimated row count: 1,000 (100% of the table; stats collected 1420 days ago)
              │                     table: xyz@xyz_y
              │                     spans: FULL SCAN
              │
              └── • hash join (inner)
                  │ columns: (a, b, c, x, y)
                  │ estimated row count: 1,000
                  │ equality: (b) = (y)
                  │
                  ├── • filter
                  │   │ columns: (a, b, c)
                  │   │ estimated row count: 3,333
                  │   │ filter: (a = b) OR ((b IS DISTINCT FROM CAST(NULL AS INT8)) OR CAST(NULL AS BOOL))
                  │   │
                  │   └── • scan
                  │         columns: (a, b, c)
                  │         estimated row count: 10,000 (100% of the table; stats collected 1420 days ago)
                  │         table: abc@abc_pkey
                  │         spans: FULL SCAN
                  │
                  └── • scan
                        columns: (x, y)
                        estimated row count: 1,000 (100% of the table; stats collected 1420 days ago)
                        table: xyz@xyz_y
                        spans: FULL SCAN
```
I got rid of a lot of the old logic, because it was a little messy, and added an updated comment:
```
	// The UNION ALL and join operations treat the output columns in the output
	// row as having the same order as the column id numbers. So, in order for the
	// resulting row definition to have the same columns in the same positions as
	// the join we're replacing, maintain this relative order. Follow a simple
	// rule that the new duplicated left and right tables maintain the same column
	// id order as the original scans. Scans allocate column ids in contiguous
	// chunks, so if the first column id in the left is less than the first column
	// id in the right, then all column ids in the left will be lower than all
	// right column ids.
	if leftFirstColID < rightFirstColID {
		newLeftScanPrivate = c.DuplicateScanPrivate(leftSP)
		newRightScanPrivate = c.DuplicateScanPrivate(rightSP)
		newLeftScanPrivate2 = c.DuplicateScanPrivate(leftSP)
		newRightScanPrivate2 = c.DuplicateScanPrivate(rightSP)
	} else {
		newRightScanPrivate = c.DuplicateScanPrivate(rightSP)
		newLeftScanPrivate = c.DuplicateScanPrivate(leftSP)
		newRightScanPrivate2 = c.DuplicateScanPrivate(rightSP)
		newLeftScanPrivate2 = c.DuplicateScanPrivate(leftSP)
	}
```
___
*[pkg/sql/opt/xform/join_funcs.go, line 2029 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-MyD2iFO-KmnyG_Gflp2:-MydU3s69cFvN0dYx80Y:b3saexs) ([raw file](https://github.com/cockroachdb/cockroach/blob/715d5126b28fe76030cd9c1a172388daeb342267/pkg/sql/opt/xform/join_funcs.go#L2029)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is there value in performing the split if the columns in the left and right scalar expressions are not indexed? I guess there might be if it transforms a cross-join into a hash-join, is that correct? 

For SplitDisjunction, we ensure that the rule only fires if there is some chance that splitting up the disjunction will lead to constrained indexed scans on both sides of the disjunction, so that we don't needlessly increase the size of the memo:

https://github.com/cockroachdb/cockroach/blob/2fdd9aebb4315f73b4e78e804dd718194b37ffed/pkg/sql/opt/xform/select_funcs.go#L1671-L1678
</blockquote></details>

Yes, even with no indexes, enabling the optimizer to pick hash join can make the join go faster.  The number of comparisons of left rows to right rows can be greatly reduced.  I'm not sure what a good check for joins would be, to avoid needlessly increasing the size of the memo.   [...]

2022-04-02 03:25 UTC, msirek reviewed
TFTRs!
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74303#-:-MzcIGs35g-faiFULKga:bg1822s)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)



<!-- Sent from Reviewable.io -->

2022-04-02 05:15 UTC, merged