opt: add Distribution physical property and Distribute enforcer
cockroachdb/cockroach pull request #74349
Opened 2021-12-30 22:36 UTC by rytaft

This commit adds a new physical property called `Distribution` to
expressions in the optimizer. Currently, `Distribution` is just the
list of regions that are touched by the expression.

This commit also adds a new enforcer called `Distribute`, which enforces
a particular `Distribution` on its input. This is similar to the way
`Sort` enforces a particular `Ordering`. Currently, `Distribute` is only
used to enforce that the results of a query end up in the same region
as the gateway node.

The `Distribution` property and `Distribute` enforcer will enable us to
perform better costing of query plans in future commits. This commit
adds a tiny cost for the `Distribute` enforcer, but otherwise does not
yet take advantage of distribution for costing. In the future, we can use
`Distribution` to better cost distributed joins and aggregations, and
accurately cost the `Distribute` enforcer so as to avoid scanning data
in remote regions if possible.

This commit represents a departure from the approach taken in the earlier
prototype in #43831. Instead of using a "neighborhood" abstraction to
represent arbitrary collections of nodes, this commit sticks to the
existing abstractions of region and locality. If we need a new abstration
in the future, we should be able to simply modify the representation of
`Distribution`.

Additionally, this commit does not make an attempt to represent exactly
how data is partitioned across regions; it only tracks *which* regions
contain data. This greatly simplifies the implementation, and I don't
think it will significantly reduce the accuracy of costing.

Informs #47226

Release note: None

2021-12-30 22:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74349)
<!-- Reviewable:end -->

2022-01-04 02:43 UTC, yuzefovich reviewed
It's great to see some work in this direction! I took a cursory look since I'm not super familiar with this code base, will defer to others for more careful review.

> Reviewed 21 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-:-MsXxzQS7U_GeQ6h2i2W:b-72nj1k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/constraint/constraint.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsXu-hz7k2_I9xs1p47:-MsXu-hz7k2_I9xs1p48:bceekt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e75bc6a092cc45878c25ca3e8bdbafab646a45/pkg/sql/opt/constraint/constraint.go#L327)):*
> ```Go
> 	keyCtx := MakeKeyContext(&c.Columns, evalCtx)
> 	// Binary search to find an overlapping span.
> 	for l, r := 0, c.Spans.Count()-1; l <= r; {
> ```

super nit: I think the canonical way for binary search is such that `l` is inclusive and `r` is exclusive.
___
*[pkg/sql/opt/memo/group.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsXuvKE-kGVBg2_HM_e:-MsXuvKE-kGVBg2_HM_f:bf56e6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e75bc6a092cc45878c25ca3e8bdbafab646a45/pkg/sql/opt/memo/group.go#L55)):*
> ```Go
> 
> 	// Provided properties, which must be compatible with the required properties.
> 	provided *physical.Provided
> ```

nit: should this change be in a separate commit? Any benchmarks to look at?
___
*[pkg/sql/opt/props/physical/distribution.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsXvsnuAMgS67nQQIi6:-MsXvsnuAMgS67nQQIi7:b1il885) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e75bc6a092cc45878c25ca3e8bdbafab646a45/pkg/sql/opt/props/physical/distribution.go#L116)):*
> ```Go
> 	}
> 
> 	regions := make(map[string]struct{})
> ```

nit: maybe make the allocation of this `map` lazy?


<!-- Sent from Reviewable.io -->

2022-01-04 22:12 UTC, rharding6373 requested changes
Looking pretty good! I have some nits and questions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-:-Msb8T2R4YWbMrXz25RR:b9a3o01)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/distribution/distribution.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsaJZQw6br0gG0kjDt_:-MsaJZQw6br0gG0kjDta:b3ryxt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/distribution/distribution.go#L1)):*
> ```Go
> // Copyright 2021 The Cockroach Authors.
> ```

nit: 2022, here and in all new files.
___
*[pkg/sql/opt/props/physical/distribution.go, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsayiuZBN2EKPbG51Go:-MsayiuZBN2EKPbG51Gp:b-wuppsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/props/physical/distribution.go#L166)):*
> ```Go
> // getRegionsFromZone returns the regions of the given zone config, if any. It
> // attempts to find the smallest set of regions likely to hold the leaseholder.
> func getRegionsFromZone(zone cat.Zone) map[string]struct{} {
> ```

I don't know enough about regional or voter replica constraints and lease preferences to properly review this function. Any documentation you can point me to? I found some reference to lease preferences at https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html, but I'm wondering if there is any other useful info around.
___
*[pkg/sql/opt/props/physical/provided.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-Msazpmo3LVFMHFEbK2X:-Msazpmo3LVFMHFEbK2Y:bm2z2xi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/props/physical/provided.go#L39)):*
> ```Go
> 	Ordering opt.Ordering
> 
> 	// Distribution is a distribution that needs to maintained on the rows
> ```

s/needs to maintained/needs to be maintained?
___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 1901 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-Msb18Wf2gIqj9WwN8m6:-Msb18Wg4EssR4ODw0ym:b-iadmxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/exec/execbuilder/testdata/explain#L1901)):*
> ```
>  │    │    ├── best: (explain G2="[presentation: a:1,b:2,k:6,v:7] [distribution: test]" [presentation: a:1,b:2,k:6,v:7] [distribution: test])
>  │    │    └── cost: 2269.93
>  │    └── []
> ```

Why is it exploring an option with no required properties when the top level has requirements? It doesn't look like this was showing up in the memo before this change, at least in G1 and G2.
___
*[pkg/sql/opt/xform/testdata/physprops/distribution, line 182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-Msb4_p40S_Lkfndw3Mm:-Msb4_p40S_Lkfndw3Mn:b-nog9i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/xform/testdata/physprops/distribution#L182)):*
> ```
>       ├── key: (3)
>       ├── fd: ()-->(1,2)
>       └── distribution: east
> ```

One thing I don't fully understand is why some scans, like this example, show a distribution, but the example below does not. Should the one below have project distribution: east and scan distribution: east?


<!-- Sent from Reviewable.io -->

2022-01-06 03:50 UTC, rytaft reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-:-MshUzKq78RCQzW-RjNG:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rharding6373, and @yuzefovich)

___
*[pkg/sql/opt/constraint/constraint.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsXu-hz7k2_I9xs1p47:-Msee7NcAA7v5VEfhgmh:b-lh8uuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e75bc6a092cc45878c25ca3e8bdbafab646a45/pkg/sql/opt/constraint/constraint.go#L327)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: I think the canonical way for binary search is such that `l` is inclusive and `r` is exclusive.
</blockquote></details>

I just copied this almost verbatim from the function above, `ContainsSpan`, so I think I'll leave this as-is for consistency
___
*[pkg/sql/opt/distribution/distribution.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsaJZQw6br0gG0kjDt_:-MsefIKV9xbbKgrw09eQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/distribution/distribution.go#L1)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: 2022, here and in all new files.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/group.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsXuvKE-kGVBg2_HM_e:-MshUrW6ChPqJfRN8jNf:bf6dy62) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e75bc6a092cc45878c25ca3e8bdbafab646a45/pkg/sql/opt/memo/group.go#L55)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should this change be in a separate commit? Any benchmarks to look at?
</blockquote></details>

I'll run some benchmarks and post results when I have them. Thanks for the suggestion!
___
*[pkg/sql/opt/props/physical/distribution.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsXvsnuAMgS67nQQIi6:-MshMnHK1_OU-0mOfGSh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e75bc6a092cc45878c25ca3e8bdbafab646a45/pkg/sql/opt/props/physical/distribution.go#L116)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe make the allocation of this `map` lazy?
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/physical/distribution.go, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsayiuZBN2EKPbG51Go:-MshNI_5C2EoGq4a-EXN:ba2meg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/props/physical/distribution.go#L166)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I don't know enough about regional or voter replica constraints and lease preferences to properly review this function. Any documentation you can point me to? I found some reference to lease preferences at https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html, but I'm wondering if there is any other useful info around.
</blockquote></details>

Hmm I don't think there's much, unfortunately. I based this function off of another function I wrote, `isZoneLocal`:
https://github.com/cockroachdb/cockroach/blob/1eebf3df494330d9aba06209f8134baf2110a4d4/pkg/sql/opt/xform/general_funcs.go#L347

That was based off of this function (which pre-dates `VoterConstraints`):
https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/xform/coster.go#L1475
and comments here:
https://github.com/cockroachdb/cockroach/blob/c3e8d8568467809c50a8eb8911fd120fe22661bb/pkg/config/zonepb/zone.proto#L88

The zone config eventually gets converted to a `roachpb.SpanConfig`, which is then used by the `kvserver/allocator.go` to actually place data. (Probably won't help much to look at that file, but just in case you were curious).
___
*[pkg/sql/opt/props/physical/provided.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-Msazpmo3LVFMHFEbK2X:-MshSThp3UwXZqKasdiW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/props/physical/provided.go#L39)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

s/needs to maintained/needs to be maintained?
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 1901 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-Msb18Wf2gIqj9WwN8m6:-MshTBeICgwp9LkmML9F:bme49ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/exec/execbuilder/testdata/explain#L1901)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why is it exploring an option with no required properties when the top level has requirements? It doesn't look like this was showing up in the memo before this change, at least in G1 and G2.
</blockquote></details>

This is how it works for ordering, too. For example: https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/memo/testdata/memo#L124
I'm not sure exactly why, but it probably has something to do with the fact that ordering and distribution are "enforceable" physical properties, so we explore all expressions both with and without the required properties.
___
*[pkg/sql/opt/xform/testdata/physprops/distribution, line 182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-Msb4_p40S_Lkfndw3Mm:-MshTuFW9YMuzIP_q5QE:b4hhgx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/xform/testdata/physprops/distribution#L182)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

One thing I don't fully understand is why some scans, like this example, show a distribution, but the example below does not. Should the one below have project distribution: east and scan distribution: east?
</blockquote></details>

To be consistent with ordering, we only show distribution when it's a required property. There's no required property below, since the Distribute enforcer takes care of it.

I'm open to also showing distribution based on the provided distribution property, though. Then it would show up for all operators that have any provided distribution. Do you think that would be better?


<!-- Sent from Reviewable.io -->

2022-01-06 20:39 UTC, mgartner approved these changes
Very cool! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Have you thought about how to make lookup joins distribution aware? It seems like we'd need other mechanisms than this to represent a lookup join operator placed in one region that performs lookups into other regions. Zig-zag joins might be a similar case too.

> Reviewed 33 of 39 files at r1, 6 of 7 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-:-Msl5s6V0G_d2f3vu7c_:b-2bc62z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373, @rytaft, and @yuzefovich)

___
*[-- commits, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskA9Dq-vNXJdlRRAaP):*
Maybe a stupid question, but what is the difference between "how data is partitioned across regions" and "which regions contain data"?
___
*[pkg/sql/opt/constraint/constraint.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsXu-hz7k2_I9xs1p47:-MskBGgj1g0Kn6V6VEz3:bckyekk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e75bc6a092cc45878c25ca3e8bdbafab646a45/pkg/sql/opt/constraint/constraint.go#L327)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I just copied this almost verbatim from the function above, `ContainsSpan`, so I think I'll leave this as-is for consistency
</blockquote></details>

nit: You could pull the binary search part out into a helper function `findIntersectingSpan( ... ) (_ *Span, ok bool)` and use it in `ContainsSpan` and `IntersectsSpan`.
___
*[pkg/sql/opt/distribution/distribution.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskezEw2OYK5LYi7jpi:-MskezEw2OYK5LYi7jpj:btyn1u2) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c51a39e49f9d3bc9de31b59a90f141ba34d132/pkg/sql/opt/distribution/distribution.go#L38)):*
> ```Go
> 		provided.FromLocality(evalCtx.Locality)
> 
> 	case *memo.ScanExpr:
> ```

I guess we don't need a case for `*memo.DistributeExpr` here that always returns true? Do you know why we don't need that?
___
*[pkg/sql/opt/distribution/distribution.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskdFOq5TNZ7j3JhefW:-MskdFOq5TNZ7j3JhefX:bcwiplo) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c51a39e49f9d3bc9de31b59a90f141ba34d132/pkg/sql/opt/distribution/distribution.go#L68)):*
> ```Go
> 
> 	case *memo.ScanExpr:
> 		return physical.Distribution{}
> ```

nit: ScanExprs don't have inputs, so is this case necessary?
___
*[pkg/sql/opt/props/physical/distribution.go, line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskhiYd6ji7jULX28rH:-MskhiYd6ji7jULX28rI:b-yz5qnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c51a39e49f9d3bc9de31b59a90f141ba34d132/pkg/sql/opt/props/physical/distribution.go#L127)):*
> ```Go
> 			for _, datums := range prefixes {
> 				if len(datums) == 0 {
> 					// This indicates a DEFAULT value, so we can't easily prune this partition.
> ```

This is not an obvious case to handle when dealing with partition prefixes. I wonder if we can make a more full-proof API for retrieving these prefix datums so that the next person to deal with them doesn't forget to handle this case. One idea (not very though out yet) would be to wrap the prefixes in a new type and provide functions like `func (p *Prefixes) Count() int`, `func (p *Prefixes) Get(i int) (_ tree.Datums, default bool)`. Maybe something to think about for a future PR?
___
*[pkg/sql/opt/xform/testdata/coster/zone, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskYbYyE4KVbX7I8muN:-MskYbYz9GzJwelCNCtE:b-2ywdzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c51a39e49f9d3bc9de31b59a90f141ba34d132/pkg/sql/opt/xform/testdata/coster/zone#L61)):*
> ```
>  ├── key: (1)
>  ├── fd: ()-->(2), (1)-->(3), (2,3)~~>(1)
>  ├── distribution: central
> ```

nit: might be easier to read if `input distribution` and `distribution` were adjacent
___
*[pkg/sql/opt/xform/testdata/physprops/distribution, line 182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-Msb4_p40S_Lkfndw3Mm:-Msk_jfR-93I7NZc5N26:b-umkyo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/xform/testdata/physprops/distribution#L182)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

To be consistent with ordering, we only show distribution when it's a required property. There's no required property below, since the Distribute enforcer takes care of it.

I'm open to also showing distribution based on the provided distribution property, though. Then it would show up for all operators that have any provided distribution. Do you think that would be better?
</blockquote></details>

This confused me too at first, but once I compared it to required orderings it makes sense. For now I'd vote to leave as-is for consistency with orderings and to avoid cluttering the test output.
___
*[pkg/sql/opt/constraint/constraint_test.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskbBcr6a5nGc3vYjBk:-MskbBcr6a5nGc3vYjBl:b-gfa08o) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c51a39e49f9d3bc9de31b59a90f141ba34d132/pkg/sql/opt/constraint/constraint_test.go#L372)):*
> ```Go
> 		{
> 			constraint:           "/1: [/1 - /3]",
> 			intersectingSpans:    "[/0 - /1] (/0 - /2] (/0 - /3) [/1 - /1] (/1 - /2) [/2 - /3] [/1 - /3] [/2 - /5]",
> ```

nit: `[/2 - /2]` might be an interesting case because its fully contained and doesn't include the endpoints in the constraint's span.
___
*[pkg/sql/opt/props/physical/distribution_test.go, line 122 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskcnmF8D_ZHHj7HOt6:-MskcnmF8D_ZHHj7HOt7:b-vewf0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c51a39e49f9d3bc9de31b59a90f141ba34d132/pkg/sql/opt/props/physical/distribution_test.go#L122)):*
> ```Go
> 		{constraints: "[-region=us,+dc=east]", expected: []string{}},
> 		{constraints: "[-region=eu]", expected: []string{}},
> 		{constraints: "[+region=us]", expected: []string{"us"}},
> ```

nit: should there be a test for something like `"[+region=us,-region=eu]"`?


<!-- Sent from Reviewable.io -->

2022-01-06 21:16 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-:-MslEvi7CAEgH4HP_AF-:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/props/physical/distribution.go, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsayiuZBN2EKPbG51Go:-MslE-HfBHxNH6ejs2Nb:bhyniy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc286a4e5ac5c1d1d07134e94a023e0e25b99d3b/pkg/sql/opt/props/physical/distribution.go#L166)):*
> cockroach/pkg/config/zonepb/zone.proto
Super helpful, thanks!


<!-- Sent from Reviewable.io -->

2022-01-12 20:28 UTC, rytaft reviewed
TFTRs!

> Have you thought about how to make lookup joins distribution aware? It seems like we'd need other mechanisms than this to represent a lookup join operator placed in one region that performs lookups into other regions. Zig-zag joins might be a similar case too.

Yea, we'll need to do some additional work to find the regions touched in the lookup index. In the worst case, this can just be all the regions of the index, but we may be able to apply a constraint similar to how we determine the regions of a scan. Zig-zag joins should be similar -- just apply the constant column(s) as the constraint. We'll need to update the cost model for these operators to account for the need to move data across regions (will be similar to the cost of the `Distribute` operator).

We'll need to update the cost model for other operators as well -- for example, all hash and merge joins will include a shuffle phase in which data is shuffled across all regions, and we'll need to add a cost for that.

But I think all of this can come in a future PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-:-MtE7nhgAtmgsWlKFMCL:bazgq9u)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @rharding6373, and @yuzefovich)

___
*[-- commits, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskA9Dq-vNXJdlRRAaP):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Maybe a stupid question, but what is the difference between "how data is partitioned across regions" and "which regions contain data"?
</blockquote></details>

Added some clarification -- let me know if it's still confusing.
___
*[pkg/sql/opt/constraint/constraint.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsXu-hz7k2_I9xs1p47:-MtE3qW2Bw6t6dApnE-9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e75bc6a092cc45878c25ca3e8bdbafab646a45/pkg/sql/opt/constraint/constraint.go#L327)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: You could pull the binary search part out into a helper function `findIntersectingSpan( ... ) (_ *Span, ok bool)` and use it in `ContainsSpan` and `IntersectsSpan`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/distribution/distribution.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskezEw2OYK5LYi7jpi:-MtE4P5XE9ZzTJq7mXgc:b-agox7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c51a39e49f9d3bc9de31b59a90f141ba34d132/pkg/sql/opt/distribution/distribution.go#L38)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I guess we don't need a case for `*memo.DistributeExpr` here that always returns true? Do you know why we don't need that?
</blockquote></details>

The only place `CanProvide` is called, we first check whether the operator is `opt.DistributeOp`. This mirrors how it's done with ordering and `Sort`. But I don't really see the harm of adding a check here for clarity. Done.
___
*[pkg/sql/opt/distribution/distribution.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskdFOq5TNZ7j3JhefW:-MtE5EBE1S8o0f1cJ6OD:bl1eak9) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c51a39e49f9d3bc9de31b59a90f141ba34d132/pkg/sql/opt/distribution/distribution.go#L68)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: ScanExprs don't have inputs, so is this case necessary?
</blockquote></details>

This mirrors `noChildReqOrdering` for ordering. I think you're right that we probably won't hit this case, but I like the symmetry / clarity of including the same operators in all the case statements. If we eventually move to the `funcMap` approach used for ordering, this will also make things easier.
___
*[pkg/sql/opt/memo/group.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MsXuvKE-kGVBg2_HM_e:-MtEy4X90hLkUyeWwuMY:b-m4zwvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0e75bc6a092cc45878c25ca3e8bdbafab646a45/pkg/sql/opt/memo/group.go#L55)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'll run some benchmarks and post results when I have them. Thanks for the suggestion!
</blockquote></details>

Here they are. As expected, allocations for some benchmarks increased slightly, but the impact on the time is negligible.
```
becca@gceworker-becca:~/go/src/github.com/cockroachdb/cockroach$ benchdiff --old=8c1528fff5c132b971428bc7f18bf0ea5eb16799 --new=4ba1a5f313f36a51b5a3fa413a395a1e4402745c --post-checkout='make buildshort' ./pkg/sql/opt/...
test binaries already exist for '8c1528f'; skipping build
test binaries already exist for '4ba1a5f'; skipping build

  pkg= 1/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt /
  pkg= 2/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/bench /
  pkg= 3/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/cat -
  pkg= 4/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/constraint -
  pkg= 5/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder \
  pkg= 6/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/exec/explain \
  pkg= 7/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/idxconstraint -
  pkg= 8/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/indexrec |
  pkg= 9/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/invertedexpr -
  pkg=10/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/invertedidx \
  pkg=11/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/memo |
  pkg=12/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/norm -
  pkg=13/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/opbench |
  pkg=14/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/optbuilder \
  pkg=15/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/optgen/cmd/optfmt \
  pkg=16/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/optgen/cmd/optgen \
  pkg=17/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/optgen/exprgen -
  pkg=18/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/optgen/lang -
  pkg=19/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/ordering \
  pkg=20/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/partialidx /
  pkg=21/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/props |
  pkg=22/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/props/physical -
  pkg=23/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/testutils -
  pkg=24/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/testutils/opttester /
  pkg=25/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/testutils/testcat \
  pkg=26/26 iter=10/10 cockroachdb/cockroach/pkg/sql/opt/xform /

name                                                                     old time/op    new time/op    delta
Phases/kv-read/Simple/ExecBuild-24                                         56.6µs ± 3%    55.4µs ± 4%   -2.05%  (p=0.009 n=10+10)
Implicator/two-var-comparison-24                                            408ns ± 1%     401ns ± 1%   -1.91%  (p=0.000 n=8+10)
Phases/kv-read/Simple/Explore-24                                           53.6µs ± 2%    52.6µs ± 3%   -1.88%  (p=0.011 n=10+10)
Phases/kv-read/Prepared/ExecBuild-24                                       1.67µs ± 3%    1.64µs ± 5%   -1.85%  (p=0.023 n=10+10)
Implicator/many-columns-inexact-match100-24                                 597µs ± 2%     586µs ± 2%   -1.85%  (p=0.000 n=10+10)
Phases/tpcc-new-order/Simple/ExecBuild-24                                   141µs ± 1%     138µs ± 2%   -1.81%  (p=0.000 n=10+10)
Implicator/many-columns-inexact-match10-24                                 9.59µs ± 2%    9.44µs ± 0%   -1.55%  (p=0.000 n=10+8)
Phases/tpcc-new-order/Simple/Explore-24                                     135µs ± 3%     133µs ± 3%   -1.50%  (p=0.035 n=10+10)
Implicator/multi-column-and-two-var-comparisons-24                          829ns ± 1%     818ns ± 1%   -1.30%  (p=0.000 n=10+10)
IndexConstraints/range-24                [...]

2022-01-12 21:08 UTC, mgartner approved these changes
> But I think all of this can come in a future PR.

Absolutely.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 41 of 41 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-:-MtF6aue8Cy_OhAqCNh1:bs6uoa)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373 and @yuzefovich)

___
*[pkg/sql/opt/distribution/distribution.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskdFOq5TNZ7j3JhefW:-MtF59B52pPukL0JbtAv:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c51a39e49f9d3bc9de31b59a90f141ba34d132/pkg/sql/opt/distribution/distribution.go#L68)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This mirrors `noChildReqOrdering` for ordering. I think you're right that we probably won't hit this case, but I like the symmetry / clarity of including the same operators in all the case statements. If we eventually move to the `funcMap` approach used for ordering, this will also make things easier.
</blockquote></details>

SGTM
___
*[pkg/sql/opt/props/physical/distribution.go, line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-MskhiYd6ji7jULX28rH:-MtF5QUu0yZ4aX8nGEDj:bpj1yze) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c51a39e49f9d3bc9de31b59a90f141ba34d132/pkg/sql/opt/props/physical/distribution.go#L127)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Sure, although I'm not convinced `Count` and `Get` will fix the problem. But definitely worth thinking about how we can improve this going forward.
</blockquote></details>

I don't think it would solve the issue 100%, but hopefully it'd require us to consider the `default` return value when adding calling `Prefixes.Get`. It could be ignored, but that'd it would have to be explicit (e.g., `datums, _ := prefixes.Get(0)`). But perhaps there's a more fool-proof API.


<!-- Sent from Reviewable.io -->

2022-01-12 22:05 UTC, rytaft reviewed
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74349#-:-MtFJfau6JNYxUHGl_p8:b-voiyyw)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373 and @yuzefovich)



<!-- Sent from Reviewable.io -->

2022-01-12 23:04 UTC, merged