storage: pool ScanStats objects
cockroachdb/cockroach pull request #74342
Opened 2021-12-30 22:07 UTC by nvanbenschoten

This commit introduces an object pool for `roachpb.ScanStats` objects. This
avoids a heap allocation when recording iterator stats to structured traces.

To make this change, the commit adjusts the contract of `tracing.Span.RecordStructured`
to allow mutation of the provided argument after the call has returned. This
change looks safe to me because nothing in `RecordStructured` holds on to a
reference to the item after it has returned, but reviewers should take a look,
as you know much more than I do about all of this.

```
name                      old time/op    new time/op    delta
KV/Scan/Native/rows=1-10    14.9µs ± 1%    15.0µs ± 4%    ~     (p=0.897 n=8+10)
KV/Scan/SQL/rows=1-10       93.2µs ± 4%    97.1µs ± 8%    ~     (p=0.143 n=10+10)

name                      old alloc/op   new alloc/op   delta
KV/Scan/Native/rows=1-10    6.87kB ± 0%    6.84kB ± 0%  -0.46%  (p=0.000 n=9+10)
KV/Scan/SQL/rows=1-10       20.0kB ± 0%    20.0kB ± 0%  -0.25%  (p=0.016 n=8+10)

name                      old allocs/op  new allocs/op  delta
KV/Scan/Native/rows=1-10      52.0 ± 0%      51.0 ± 0%  -1.92%  (p=0.000 n=10+10)
KV/Scan/SQL/rows=1-10          245 ± 0%       244 ± 0%  -0.53%  (p=0.000 n=8+10)
```

2021-12-30 22:07 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74342)
<!-- Reviewable:end -->

2022-01-05 16:07 UTC, andreimatei requested changes
> To make this change, the commit adjusts the contract of tracing.Span.RecordStructured
> to allow mutation of the provided argument after the call has returned. This
> change looks safe to me because nothing in RecordStructured holds on to a
> reference to the item after it has returned, but reviewers should take a look,
> as you know much more than I do about all of this.


Mmm I dunno about this. At the moment, indeed, `RecordStructured` does eager proto serialization via `types.MarshalAny()`. However, I don't know if that's a good idea. The `RecordStructured()` code was presumably written when the only spans interested in these events were the ones that will eventually serialize them in a recording of the whole trace. But, as I push on making the active spans registry more useful, I'll probably want the registry to have access to these structured events. I'm not sure yet of the exact details, but I think it's likely that I'll do away with the eager marshaling. I'd rather have the span take ownership of these events. We can make them `Span.Finish()` participate in a protocol where it releases different events back to different pools if it hasn't transferred ownership to someone else (i.e. to another span).
Btw, see the suggestion below for how these allocations will more easily disappear, at least for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74342#-:-MsewCBO29Gf--5vNGna:b-9ttvmk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @nvanbenschoten)

___
*[pkg/storage/mvcc.go, line 2320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74342#-MsewkDG8w0bkB--aY67:-MsewkDG8w0bkB--aY68:bxkjqcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a926566327465342ce70dd00569603304e27d89/pkg/storage/mvcc.go#L2320)):*
> ```Go
> func recordIteratorStats(traceSpan *tracing.Span, iteratorStats IteratorStats) {
> 	stats := iteratorStats.Stats
> 	if traceSpan != nil {
> ```

I think this is wrong / wasteful. Instead of nil, this function should check `sp.RecordingMode() != tracing.RecordingOff` (the nil check is handled internally). With that in place, as the code currently stands, you won't see these allocations any more (not even in tests, where a minimal tracing is always active).
Also have this take the `ctx` instead of the span and to `tracing.SpansFromContext(ctx)` inside the function.


<!-- Sent from Reviewable.io -->

2022-01-06 14:59 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74342)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

___
*[pkg/storage/mvcc.go, line 2320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74342#-MsewkDG8w0bkB--aY67:-Msjt6ruDiWkWqd6gMKg:b-1lhxwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a926566327465342ce70dd00569603304e27d89/pkg/storage/mvcc.go#L2320)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this is wrong / wasteful. Instead of nil, this function should check `sp.RecordingMode() != tracing.RecordingOff` (the nil check is handled internally). With that in place, as the code currently stands, you won't see these allocations any more (not even in tests, where a minimal tracing is always active).
Also have this take the `ctx` instead of the span and to `tracing.SpansFromContext(ctx)` inside the function.
</blockquote></details>

Are you saying that this should be `if traceSpan != nil && traceSpan.RecordingMode() != tracing.RecordingOff` and the rest can be unchanged? Is that because we are mostly in `RecordingOff` mode (trace sampling?) so the allocation cost is minor?


<!-- Sent from Reviewable.io -->

2022-07-08 19:29 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74342)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

___
*[`pkg/storage/mvcc.go` line 2320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74342#-MsewkDG8w0bkB--aY67:-N6UHBtV9oESGasJo9ar:bvqvbzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a926566327465342ce70dd00569603304e27d89/pkg/storage/mvcc.go#L2320)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are you saying that this should be `if traceSpan != nil && traceSpan.RecordingMode() != tracing.RecordingOff` and the rest can be unchanged? Is that because we are mostly in `RecordingOff` mode (trace sampling?) so the allocation cost is minor?
</blockquote></details>

Good idea. Done and confirmed that this preserves the reduction in heap allocations. PTAL.


<!-- Sent from Reviewable.io -->

2022-07-11 16:00 UTC, andreimatei approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74342#-:-N6hzS_23kpxBnwpsWDk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)



<!-- Sent from Reviewable.io -->

2022-07-11 17:58 UTC, nvanbenschoten commented
TFTR!

bors r+

2022-07-11 22:17 UTC, merged