schemachanger: declarative should delete comments for schema objects
cockroachdb/cockroach pull request #74430
Opened 2022-01-04 21:33 UTC by fqazi

Previously, the declarative schema changer did not clean up
comments for schema objects when dropping them. This was
inadequate because the system.comment table would never clean
up entries for deleted descriptors. To address this, this patch
will remove comment table entries for schema objects in the
declarative schema changer.

Release note: None

2022-01-04 21:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74430)
<!-- Reviewable:end -->

2022-01-05 14:40 UTC, ajwerner reviewed
Is it plausible to refactor out the code which deletes and updates comments from the sql package into an interface and then inject that interface into scdeps? Having the SQL for the various comment operations duplicated doesn't feel very good. The other point is that we'll eventually need to deal with all of the comment objects. That can be deferred, but it'll be good to think about the elements. An answer is to have a different element per comment type. That's not what you have here. It's weird that an empty comment on the descriptor would delete all of the comments for all of its sub-elements. 

> Reviewed 1 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-:-Msef1toDFUMUdoBDukX:b-cx3f3w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)



<!-- Sent from Reviewable.io -->

2022-01-06 15:21 UTC, fqazi reviewed
Refactored this and made the sql package adopt the new interfaces. Additionally, separated things out into multiple comment objects.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-:-MsjyOzR9KF9JHcu0jIS:boiv6j5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)



<!-- Sent from Reviewable.io -->

2022-01-06 20:47 UTC, ajwerner reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/pg_catalog.go, line 4374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Mskju5H9oZXdec6kjtL:-Mskju5H9oZXdec6kjtM:bhmlp86) ([raw file](https://github.com/cockroachdb/cockroach/blob/623b820fe02c395644bb9d397bb4280df40cdb40/pkg/sql/pg_catalog.go#L4374)):*
> ```Go
> }
> 
> //OidFromConstraint generates an OID given constraint information.
> ```

`oid` and descpb.ID are not at all the same thing. 



_Code quote:_
```Go
//OidFromConstraint generates an OID given constraint information.
func OidFromConstraint(
	desc catalog.TableDescriptor,
	schemaName string,
	constraintOrdinal int,
	constraintType scpb.ConstraintType,
) descpb.ID {
```
___
*[pkg/sql/commenter/comment_updater.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Mskk83nDhQREm0iDzf7:-Mskk83nDhQREm0iDzf8:b-wxolmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/623b820fe02c395644bb9d397bb4280df40cdb40/pkg/sql/commenter/comment_updater.go#L32)):*
> ```Go
> 	constraintOrdinal int,
> 	constraintType scpb.ConstraintType,
> ) descpb.ID
> ```

This should return a tree.DOid, no? The fact that we index the comments using some `descpb.ID` API shouldn't be shoved as far down as we can. 
___
*[pkg/sql/commenter/comment_updater.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msl7yi_8NnkPpYTjYpQ:-Msl7yi_8NnkPpYTjYpR:bko6zdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb0c094477ad2b7c59fee2f2f7ca124c63ccf54f/pkg/sql/commenter/comment_updater.go#L48)):*
> ```Go
> 	txn *kv.Txn,
> 	oidFromConstraint OidFromConstraintCallback,
> ) scexec.CommentUpdater {
> ```

how would you feel about a `CommentUpdaterFactory` type which returns a `CommentUpdater` with a `txn` and `sessionData`? Then we can stick that thing in the `ExecConfig` and pass it directly to `scdeps`



_Code quote:_
```Go
// NewCommentUpdater creates a new comment updater
func NewCommentUpdater(
	ctx context.Context,
	ieFactory sqlutil.SessionBoundInternalExecutorFactory,
	sessionData *sessiondata.SessionData,
	txn *kv.Txn,
	oidFromConstraint OidFromConstraintCallback,
) scexec.CommentUpdater {
```
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 242 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msl76Qc8h6W7XuLw_lt:-Msl76Qc8h6W7XuLw_lu:b25pboo) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb0c094477ad2b7c59fee2f2f7ca124c63ccf54f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L242)):*
> ```Go
> 			TableID: tbl.GetID(),
> 		}
> 		enqueue(b, targetStatus, &comment)
> ```

nit: do you prefer this assignment pattern to:
```go
enqueue(b, targetStatus, &scpb.TableComment{
    TableID: tbl.GetID()
})
```



_Code quote:_
```Go

			TableID: tbl.GetID(),
		}
		enqueue(b, targetStatus, &comment)
```
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 489 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msl7KfT-S--E139mvvI:-Msl7KfT-S--E139mvvJ:bz7omro) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb0c094477ad2b7c59fee2f2f7ca124c63ccf54f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L489)):*
> ```Go
> 			comment := scpb.ConstraintComment{
> 				ConstraintType:    scpb.ConstraintType_UniqueWithoutIndex,
> 				ConstraintOrdinal: uint32(idx),
> ```

what are your feelings on using names as opposed to ordinals? The ordinals, for me at least, are more of an in-memory concept as opposed to one which we make durable. It'll also allow for better execution time validation and more obvious debugging. Then, in the execution of the op, we can map the constraint to an ordinal. 
___
*[pkg/sql/schemachanger/scop/mutation.go, line 371 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MskknZnCgSUCy0MdXEN:-MskknZnCgSUCy0MdXEO:b-s98hht) ([raw file](https://github.com/cockroachdb/cockroach/blob/623b820fe02c395644bb9d397bb4280df40cdb40/pkg/sql/schemachanger/scop/mutation.go#L371)):*
> ```Go
> 	DescriptorID descpb.ID
> 	SubID        int
> 	CommentType  int
> ```

can we give this a stronger type with a String method?
___
*[pkg/sql/schemachanger/testdata/drop, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Mskkajx6Mb6n4fXUIkA:-Mskkajx6Mb6n4fXUIkB:b-71pm8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/623b820fe02c395644bb9d397bb4280df40cdb40/pkg/sql/schemachanger/testdata/drop#L281)):*
> ```
> delete comment for descriptor #70 of type 1
> delete comment for descriptor #71 of type 1
> delete comment for descriptor #74 of type 1
> ```

are we missing a stringer method on the type here? 



_Code quote:_
```
delete comment for descriptor #64 of type 1
delete comment for descriptor #67 of type 1
delete comment for descriptor #67 of type 2
delete comment for descriptor #67 of type 2
delete comment for descriptor #67 of type 2
delete comment for descriptor #67 of type 3
delete comment for descriptor #62 of type 4
delete comment for descriptor #65 of type 1
delete comment for descriptor #66 of type 1
delete comment for descriptor #66 of type 2
delete comment for descriptor #66 of type 2
delete comment for descriptor #66 of type 2
delete comment for descriptor #66 of type 3
delete comment for descriptor #68 of type 1
delete comment for descriptor #69 of type 1
delete comment for descriptor #70 of type 1
delete comment for descriptor #71 of type 1
delete comment for descriptor #74 of type 1
delete comment for descriptor #63 of type 4
delete comment for descriptor #61 of type 0
```


<!-- Sent from Reviewable.io -->

2022-01-06 21:01 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/commenter/comment_updater.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MslBat-1Q0ANTHYaMGC:-MslBat-1Q0ANTHYaMGD:b-dgs7wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb0c094477ad2b7c59fee2f2f7ca124c63ccf54f/pkg/sql/commenter/comment_updater.go#L41)):*
> ```Go
> }
> 
> // NewCommentUpdater creates a new comment updater
> ```

commentary in this file could use some cleanup 


<!-- Sent from Reviewable.io -->

2022-01-07 03:08 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/commenter/comment_updater.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Mskk83nDhQREm0iDzf7:-Msm-6NO-U1MxhZGX2Ts:bfzzo6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/623b820fe02c395644bb9d397bb4280df40cdb40/pkg/sql/commenter/comment_updater.go#L32)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This should return a tree.DOid, no? The fact that we index the comments using some `descpb.ID` API shouldn't be shoved as far down as we can. 
</blockquote></details>

Done.

Switched the API to generate tree.DOid
___
*[pkg/sql/commenter/comment_updater.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msl7yi_8NnkPpYTjYpQ:-Msm-CiF7JeoRs97xFQA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb0c094477ad2b7c59fee2f2f7ca124c63ccf54f/pkg/sql/commenter/comment_updater.go#L48)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

how would you feel about a `CommentUpdaterFactory` type which returns a `CommentUpdater` with a `txn` and `sessionData`? Then we can stick that thing in the `ExecConfig` and pass it directly to `scdeps`
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 489 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msl7KfT-S--E139mvvI:-MsmSDUN3ojuJf_1tEN-:b-a8c0b6) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb0c094477ad2b7c59fee2f2f7ca124c63ccf54f/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L489)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what are your feelings on using names as opposed to ordinals? The ordinals, for me at least, are more of an in-memory concept as opposed to one which we make durable. It'll also allow for better execution time validation and more obvious debugging. Then, in the execution of the op, we can map the constraint to an ordinal. 
</blockquote></details>

Done.
Switched this stuff over to names, will use a separate PR to switch existing stuff over, its a cleaner / safer solution.
___
*[pkg/sql/schemachanger/scop/mutation.go, line 371 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MskknZnCgSUCy0MdXEN:-MsmU5MY0eLf63-D7iB0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/623b820fe02c395644bb9d397bb4280df40cdb40/pkg/sql/schemachanger/scop/mutation.go#L371)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can we give this a stronger type with a String method?
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/testdata/drop, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Mskkajx6Mb6n4fXUIkA:-MsmU8Yy2UpjNwxU9MY1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/623b820fe02c395644bb9d397bb4280df40cdb40/pkg/sql/schemachanger/testdata/drop#L281)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

are we missing a stringer method on the type here? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-07 16:05 UTC, postamar requested changes
> Reviewed 13 of 41 files at r2, 5 of 31 files at r4, 24 of 37 files at r6, 1 of 16 files at r7, 4 of 18 files at r8, 1 of 16 files at r10, 15 of 15 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[-- commits, line 2 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp3-KB24E-SnctKii-):*
`declarative` what? delete them when?

Suggestion: `schemachanger: delete comments when dropping schemas`
___
*[-- commits, line 7 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp3PCyBzkk0ccne8CV):*
Reword this and feel free to not adhere so strictly to the commit message template to get your point across. Your first sentence is fine but the second is nonsensical, tables don't _do_ anything.
___
*[-- commits, line 16 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp46a7E4wxfxWWOlaP):*
Where was this ad-hoc code?
___
*[-- commits, line 17 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp42Iu0hOfjyN4PTTh):*
nit: superfluous comma
___
*[-- commits, line 20 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp4CTy0KQT8pR6hfhn):*
nit: prefer "legacy" to "existing", at this point they both exist.
___
*[-- commits, line 22 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp4KvC3nt0qaAeNMRB):*
This should be at the top of the commit message. Don't bury the lede.
___
*[pkg/server/server_sql.go, line 815 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MspCXgYDKkx2KCDv5eq:-MspCXgZBuMN6_t-EQIw:b-qwwrza) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/server/server_sql.go#L815)):*
> ```Go
> 		ieFactory,
> 		sql.OidFromConstraint,
> 		sql.NewFakeSessionData(&execCfg.Settings.SV))
> ```

Shouldn't we instead have `execCfg.Settings` as a field in the factory struct and pass the `sql.NewFaceSessionData` callback, like in the `indexValidator` assignment above? I'll admit I don't know what's right here, nor what makes it OK to use fake session data. On the latter point, I get why it doesn't matter for validating indexes, but I don't get why it's OK for comments, doesn't the session data have locale settings and stuff that could potentially impact the comments that get stored?
___
*[pkg/sql/pg_catalog.go, line 4381 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MspFukc6CENEN_FWdMz:-MspFukc6CENEN_FWdN-:bj62zbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/pg_catalog.go#L4381)):*
> ```Go
> 	constraintType scpb.ConstraintType,
> ) *tree.DOid {
> 	oidMaker := makeOidHasher()
> ```

Rather than defining `OidFromConstraint` and passing it as a callback, consider defining an interface in the `commenter` package:
```
type ConstraintOidBuilder interface {
    ForeignKeyConstraintOid(...) *tree.DOid
    UniqueConstraintOid
    ...
}
```
which will be implemented by `oidHasher`, which you can then pass to the factory constructor. This will allow you to move all this logic to `commenter`.
___
*[pkg/sql/commenter/comment_updater.go, line 47 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MspEaa6B11qcpvyyMfn:-MspEaa6B11qcpvyyMfo:b-7vyow1) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/commenter/comment_updater.go#L47)):*
> ```Go
> ) error {
> 	_, err := cu.ie.ExecEx(context.Background(),
> 		"upsert-schema-comment",
> ```

`fmt.Sprintf("upsert-%s-comment", commentType.String())`?
___
*[pkg/sql/commenter/comment_updater.go, line 64 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MspEo-96qf685GyIUcf:-MspEo-96qf685GyIUcg:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/commenter/comment_updater.go#L64)):*
> ```Go
> ) error {
> 	_, err := cu.ie.ExecEx(context.Background(),
> 		"delete-schema-comment",
> ```

Same as above.
___
*[pkg/sql/commenter/comment_updater.go, line 68 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MspEurKEQ3gZL4XJhJX:-MspEurKEQ3gZL4XJhJY:b227aq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/commenter/comment_updater.go#L68)):*
> ```Go
> 		sessiondata.InternalExecutorOverride{User: security.RootUserName()},
> 		"DELETE FROM system.comments WHERE object_id=$1 AND sub_id=$2 and "+
> 			"type = $3",
> ```

nit: run this through sqlfm.pt
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go, line 81 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp8m5x6QorZ0NnwGXl:-Msp8m5x6QorZ0NnwGXm:bp4e468) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go#L81)):*
> ```Go
> 	b.EnqueueDrop(&scpb.DatabaseComment{
> 		DatabaseID: db.GetID(),
> 		Comment:    "",
> ```

Hmm, I get that this works, but it doesn't feel right. Would it be hard to retrieve the actual comments and populate all the comment elements with their actual values? I have no idea.
___
*[pkg/sql/schemachanger/scexec/dependencies.go, line 262 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MspAse35xa6x3scg9Uh:-MspAse35xa6x3scg9Ui:b-puzuu) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scexec/dependencies.go#L262)):*
> ```Go
> 	NewCommentUpdater(
> 		ctx context.Context, txn *kv.Txn,
> 	) CommentUpdater
> ```

nit: remove superfluous newlines in method defn?
___
*[pkg/sql/schemachanger/scop/mutation.go, line 370 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp6_tAA7pto_vTERgg:-Msp6_tAA7pto_vTERgh:b-ntrxx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scop/mutation.go#L370)):*
> ```Go
> 	mutationOp
> 	DescriptorID descpb.ID
> 	SubID        int
> ```

`SubID` is pretty meaningless as a name. I get what it is, and that it comes from the comment system table schema, but this feels like an implementation detail that leaked too far.

Perhaps you'd be better off defining an op for each comment type instead. You already have `RemoveConstraintComment` anyway so might as well go all out. It's not like the number of comment types is likely to grow anyway.
___
*[pkg/sql/schemachanger/scpb/comment_type.go, line 17 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp6JkV26d3KKP66ffi:-Msp6JkV26d3KKP66ffj:b-bca380) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scpb/comment_type.go#L17)):*
> ```Go
> // CommentType the type of the schema object on which a comment has been
> // applied.
> type CommentType int
> ```

Would it be possible to define this type (and the stringer) in `keys` instead?
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 59 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp5JDN5bccTd8HDG6O:-Msp5JDN5bccTd8HDG6P:b-i02ubg) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scpb/scpb.proto#L59)):*
> ```protobuf
>   IndexComment indexComment = 37 [(gogoproto.moretags) = "parent:\"Index\""];
>   ColumnComment columnComment = 38 [(gogoproto.moretags) = "parent:\"Column\""];
>   ConstraintComment constraintComment = 39;
> ```

`ConstraintComment` doesn't have a parent? This is odd. If this is deliberate, can you please add a comment explaining why?
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 389 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp5S-J6dO9OPR9Byep:-Msp5S-J6dO9OPR9Byeq:b-3kv6p8) ([raw file](https://github.com/cockroachdb/cockro [...]

2022-01-07 19:50 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[-- commits, line 2 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp3-KB24E-SnctKii-):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

`declarative` what? delete them when?

Suggestion: `schemachanger: delete comments when dropping schemas`
</blockquote></details>

Done.
___
*[-- commits, line 7 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp3PCyBzkk0ccne8CV):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Reword this and feel free to not adhere so strictly to the commit message template to get your point across. Your first sentence is fine but the second is nonsensical, tables don't _do_ anything.
</blockquote></details>

Super terrible phrasing, should be clearer now:

    schemachanger: delete comments when dropping schemas

    Previously, the declarative schema changer did not clean
    comment for schema objects when dropping them. This was
    inadequate because the system.comment table would have
    rows for dropped schema objects left over when using
    the declarative schema changer versus the legacy schema
    changer. To address this, this patch will remove rows
    from the system.comment table for schema objects that
    are dropped.
___
*[-- commits, line 16 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp46a7E4wxfxWWOlaP):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Where was this ad-hoc code?
</blockquote></details>

Done.
___
*[-- commits, line 22 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp4KvC3nt0qaAeNMRB):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This should be at the top of the commit message. Don't bury the lede.
</blockquote></details>

Done.
___
*[pkg/server/server_sql.go, line 815 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MspCXgYDKkx2KCDv5eq:-MspuI0J-NJXUNmg_s1p:b-1ykydd) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/server/server_sql.go#L815)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Shouldn't we instead have `execCfg.Settings` as a field in the factory struct and pass the `sql.NewFaceSessionData` callback, like in the `indexValidator` assignment above? I'll admit I don't know what's right here, nor what makes it OK to use fake session data. On the latter point, I get why it doesn't matter for validating indexes, but I don't get why it's OK for comments, doesn't the session data have locale settings and stuff that could potentially impact the comments that get stored?
</blockquote></details>

Good point the right answer here is to push the sessiondata into execution.
___
*[pkg/sql/pg_catalog.go, line 4381 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MspFukc6CENEN_FWdMz:-MspuNdG8y4dFpsnHyev:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/pg_catalog.go#L4381)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Rather than defining `OidFromConstraint` and passing it as a callback, consider defining an interface in the `commenter` package:
```
type ConstraintOidBuilder interface {
    ForeignKeyConstraintOid(...) *tree.DOid
    UniqueConstraintOid
    ...
}
```
which will be implemented by `oidHasher`, which you can then pass to the factory constructor. This will allow you to move all this logic to `commenter`.
</blockquote></details>

Done.
___
*[pkg/sql/commenter/comment_updater.go, line 47 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MspEaa6B11qcpvyyMfn:-MspuOnACL4Ciz6H7PlT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/commenter/comment_updater.go#L47)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

`fmt.Sprintf("upsert-%s-comment", commentType.String())`?
</blockquote></details>

Done.
___
*[pkg/sql/commenter/comment_updater.go, line 64 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MspEo-96qf685GyIUcf:-MspuP7a21TweZGNgsY9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/commenter/comment_updater.go#L64)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go, line 81 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp8m5x6QorZ0NnwGXl:-MspurTX-ZAYyjNxYJNd:b1rhk4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go#L81)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Hmm, I get that this works, but it doesn't feel right. Would it be hard to retrieve the actual comments and populate all the comment elements with their actual values? I have no idea.
</blockquote></details>

I think this is easy for some cases, for other cases it will be an ugly mess since we need to map OID's to objects. The OID's are just hashes, so as we are decomposing constraints we would need to check if an entry exists via a query for each one. So, this would need a funny thing inside decomposition that will now run queries.
___
*[pkg/sql/schemachanger/scop/mutation.go, line 370 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp6_tAA7pto_vTERgg:-MspxLidAPNGjrkMm69Z:b61ur51) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scop/mutation.go#L370)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

`SubID` is pretty meaningless as a name. I get what it is, and that it comes from the comment system table schema, but this feels like an implementation detail that leaked too far.

Perhaps you'd be better off defining an op for each comment type instead. You already have `RemoveConstraintComment` anyway so might as well go all out. It's not like the number of comment types is likely to grow anyway.
</blockquote></details>

Done.

Moved this over having one an operation for each type of comment.
___
*[pkg/sql/schemachanger/scpb/comment_type.go, line 17 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp6JkV26d3KKP66ffi:-MspxQCc9pqbrUwzKT7s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scpb/comment_type.go#L17)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Would it be possible to define this type (and the stringer) in `keys` instead?
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 59 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp5JDN5bccTd8HDG6O:-Mspxzqu0xJhSKBvF3z4:bafblu) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scpb/scpb.proto#L59)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

`ConstraintComment` doesn't have a parent? This is odd. If this is deliberate, can you please add a comment explaining why?
</blockquote></details>

Added the mapping, though longer term we need to align things. Comments are mapped by names instead of ordinals.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 389 at r11](https://reviewable.io/reviews/cockroach [...]

2022-01-12 21:57 UTC, postamar approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> just nits

> Reviewed 6 of 48 files at r12, 2 of 18 files at r15, 1 of 20 files at r16, 8 of 25 files at r18, 1 of 2 files at r19, 27 of 50 files at r21, 1 of 4 files at r22, 1 of 2 files at r23, 1 of 1 files at r24, 24 of 24 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-:-MtFHrn31FMVPFH6ebrb:busdgnz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/scop/mutation.go, line 371 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MtFG8ko9xIzShNf4Wj8:-MtFG8ko9xIzShNf4Wj9:bse7kts) ([raw file](https://github.com/cockroachdb/cockroach/blob/016d0c9f948d5a548db6fcb75debdf5b4cd4b912/pkg/sql/schemachanger/scop/mutation.go#L371)):*
> ```Go
> type RemoveTableComment struct {
> 	mutationOp
> 	DescriptorID descpb.ID
> ```

nit: TableID?
___
*[pkg/sql/schemachanger/scop/mutation.go, line 377 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MtFGCP49v3nY2U5KmXP:-MtFGCP49v3nY2U5KmXQ:bf620mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/016d0c9f948d5a548db6fcb75debdf5b4cd4b912/pkg/sql/schemachanger/scop/mutation.go#L377)):*
> ```Go
> type RemoveDatabaseComment struct {
> 	mutationOp
> 	DescriptorID descpb.ID
> ```

nit: DatabaseID?
___
*[pkg/sql/schemachanger/scop/mutation.go, line 383 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MtFGEZw-pkTQOYpKwTU:-MtFGEZw-pkTQOYpKwTV:b-csws6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/016d0c9f948d5a548db6fcb75debdf5b4cd4b912/pkg/sql/schemachanger/scop/mutation.go#L383)):*
> ```Go
> type RemoveSchemaComment struct {
> 	mutationOp
> 	DescriptorID descpb.ID
> ```

nit: SchemaID?
___
*[pkg/sql/schemachanger/scpb/elements.proto, line 341 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MtFHQpQC96hrweSz6y1:-MtFHQpQC96hrweSz6y2:bxkjnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/016d0c9f948d5a548db6fcb75debdf5b4cd4b912/pkg/sql/schemachanger/scpb/elements.proto#L341)):*
> ```protobuf
>   UniqueWithoutIndex = 1;
>   Check = 2;
>   ForeignKeyConst = 3;
> ```

Oh, I didn't realize that you originally named this `FK` because of a name collision prevented you from naming it `ForeignKey`! In light of this, I'd be cool with `FK`. Your call.
___
*[pkg/sql/schemachanger/scplan/opgen/opgen_table_comment.go, line 31 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp7DLwD3ZrIn_4S3pK:-MtFGcP-38nTm76dKk1x:bluq7ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scplan/opgen/opgen_table_comment.go#L31)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm wondering which phase should these ops be in? Right now they'll effectively be in the statement phase. Is that what we want? I honestly don't know. How do we do it in the legacy schema changer? cc @ajwerner 
</blockquote></details>

After discussing this offline it appears that we can't assume that the legacy schema changer is doing the right thing. Let's worry about this some other time.


<!-- Sent from Reviewable.io -->

2022-01-13 00:30 UTC, ajwerner reviewed
> Reviewed 1 of 38 files at r6, 1 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/schemachanger/scpb/elements.proto, line 341 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MtFHQpQC96hrweSz6y1:-MtFpYCm5n9vOR_OMce9:b-6ks0c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/016d0c9f948d5a548db6fcb75debdf5b4cd4b912/pkg/sql/schemachanger/scpb/elements.proto#L341)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Oh, I didn't realize that you originally named this `FK` because of a name collision prevented you from naming it `ForeignKey`! In light of this, I'd be cool with `FK`. Your call.
</blockquote></details>

What about giving these all a suffix and relating this enum to comments? 

```go
enum CommentConstraintType {
```
```go
ForeignKeyComment
```


<!-- Sent from Reviewable.io -->

2022-01-13 00:33 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/schemachanger/scpb/elements.proto, line 341 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-MtFHQpQC96hrweSz6y1:-MtFqT8ZBn5DlMkIfbwA:bou3xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/016d0c9f948d5a548db6fcb75debdf5b4cd4b912/pkg/sql/schemachanger/scpb/elements.proto#L341)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What about giving these all a suffix and relating this enum to comments? 

```go
enum CommentConstraintType {
```
```go
ForeignKeyComment
```
</blockquote></details>

We use these for decomposition too, so we could just add Constraint at the end of each one


<!-- Sent from Reviewable.io -->

2022-01-13 01:21 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74430)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scplan/opgen/opgen_table_comment.go, line 31 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74430#-Msp7DLwD3ZrIn_4S3pK:-MtG0McX-GsEIilt6_07:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54195dd906f14e46d010ab8de345fda23628d252/pkg/sql/schemachanger/scplan/opgen/opgen_table_comment.go#L31)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

After discussing this offline it appears that we can't assume that the legacy schema changer is doing the right thing. Let's worry about this some other time.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-13 03:59 UTC, fqazi commented
bors r+

2022-01-13 04:24 UTC, fqazi commented
bors r-

2022-01-13 04:37 UTC, fqazi commented
bors r+

2022-01-13 05:18 UTC, merged