storage,roachpb: Add Key field to WriteTooOldError
cockroachdb/cockroach pull request #74572
Opened 2022-01-07 17:53 UTC by itsbilal

Currently, WriteTooOldErrors that happen as part of a
ranged put operation (eg. MVCCClearTimeRange) can be very
opaque, as we don't know what key we tried to "write too old"
on. This change addresses that by adding a Key field to WriteTooOldError.
The field is optional, as retaining that key for an MVCCScan would not
really be worth it.

Informs #72476.

Release note: None.

2022-01-07 17:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74572)
<!-- Reviewable:end -->

2022-01-07 20:30 UTC, bananabrick approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74572)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/roachpb/errors.go, line 897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-MsqCv9G4hrkcSV80MDa:-MsqCv9G4hrkcSV80MDb:b-ukucy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d496b1d5d2f8cc7af0de8ece6492bb1391eba0ed/pkg/roachpb/errors.go#L897)):*
> ```Go
> 		oldKey := key
> 		key := make([]byte, len(oldKey))
> 		copy(key, oldKey)
> ```

I'm curious why we need this copy. This won't modify `key` in the parent scope of the `if {...}`. Do we want `key = make([]byte, len(oldkey))`?


<!-- Sent from Reviewable.io -->

2022-01-07 22:47 UTC, itsbilal commented
___
*[pkg/roachpb/errors.go, line 897 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-MsqCv9G4hrkcSV80MDa:-MsqiF4uEjN37nJs_XTr:b-c0m64s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d496b1d5d2f8cc7af0de8ece6492bb1391eba0ed/pkg/roachpb/errors.go#L897)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I'm curious why we need this copy. This won't modify `key` in the parent scope of the `if {...}`. Do we want `key = make([]byte, len(oldkey))`?
</blockquote></details>

Yikes. Good catch; I should have not done the :=. Fixed, thanks for the review!


<!-- Sent from Reviewable.io -->

2022-01-10 15:44 UTC, itsbilal commented
bors r=bananabrick

2022-01-10 16:55 UTC, itsbilal commented
Made a quick update to also propagate the failing `Key` in the MVCC Scanner. PTAL?

2022-01-10 17:44 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74572)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @itsbilal)

___
*[pkg/roachpb/errors.proto, line 334 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-Mt44RXX0Ri57rc23Ahf:-Mt44RXY2o8gLv3c0Ooj:bsdx8nt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69763c5e57ab2fbf8d724deeb657772104db648/pkg/roachpb/errors.proto#L334)):*
> ```protobuf
> message WriteTooOldError {
>   optional util.hlc.Timestamp timestamp = 1 [(gogoproto.nullable) = false];
>   optional util.hlc.Timestamp actual_timestamp = 2 [(gogoproto.nullable) = false];
> ```

I think we need a comment that key is not necessarily the key at/around actual_timestamp -- it is just one of the newer keys that was found.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 378 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-Mt41r6oEIpeR54dALmI:-Mt41r6oEIpeR54dALmJ:bfw0aet) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69763c5e57ab2fbf8d724deeb657772104db648/pkg/storage/pebble_mvcc_scanner.go#L378)):*
> ```Go
> 				// that we can return the largest possible time.
> 				p.mostRecentTS.Forward(p.curUnsafeKey.Timestamp)
> 				p.mostRecentKey = append(p.mostRecentKey[:0], p.curUnsafeKey.Key...)
> ```

I'm somewhat concerned about the performance cost of this. 
There may be common cases where a large number of newer values are found and we efficiently discover all of them (someone from KV, like Nathan or Erik should be able to confirm), while here we will making a key copy.

Can we copy the key only if there isn't already a mostRecentKey.


<!-- Sent from Reviewable.io -->

2022-01-10 20:29 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74572)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @sumeerbhola)

___
*[pkg/roachpb/errors.proto, line 334 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-Mt44RXX0Ri57rc23Ahf:-Mt4fbpE3Sotdn3f1Bc9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69763c5e57ab2fbf8d724deeb657772104db648/pkg/roachpb/errors.proto#L334)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we need a comment that key is not necessarily the key at/around actual_timestamp -- it is just one of the newer keys that was found.
</blockquote></details>

Done.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 378 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-Mt41r6oEIpeR54dALmI:-Mt4fcNWAZKmVw6ZhG4D:bwory1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69763c5e57ab2fbf8d724deeb657772104db648/pkg/storage/pebble_mvcc_scanner.go#L378)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm somewhat concerned about the performance cost of this. 
There may be common cases where a large number of newer values are found and we efficiently discover all of them (someone from KV, like Nathan or Erik should be able to confirm), while here we will making a key copy.

Can we copy the key only if there isn't already a mostRecentKey.
</blockquote></details>

This is a good point. Made that optimization - thanks!


<!-- Sent from Reviewable.io -->

2022-01-11 15:51 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 8 of 11 files at r1, 1 of 1 files at r5, 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-:-Mt8pUXD1sJeiqvwE0Ap:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick, @itsbilal, and @sumeerbhola)

___
*[-- commits, line 9 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-Mt8ojos8wq7pV0jI0AY):*
Is this last sentence stale?
___
*[pkg/storage/pebble_mvcc_scanner.go, line 178 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-Mt8pBNh1ByU-dT3kOiH:-Mt8pBNh1ByU-dT3kOiI:bh9ddym) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7c7377564e3270d6c2f1594d0229fa32e5513d/pkg/storage/pebble_mvcc_scanner.go#L178)):*
> ```Go
> 	// set and no other error is hit, a WriteToOld error will be returned from
> 	// the scan. mostRecentKey is the key where mostRecentTS was most recently
> 	// encountered.
> ```

how about: mostRecentKey is one of the keys (not necessarily at mostRecentTS) that was more recent than the scan.


<!-- Sent from Reviewable.io -->

2022-01-11 15:55 UTC, itsbilal reviewed
TFTR! Since the only changes in the last update were comments, I'll:

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-:-Mt8q5VrB2ebk256vSen:b791wfb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick and @sumeerbhola)

___
*[-- commits, line 9 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-Mt8ojos8wq7pV0jI0AY):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this last sentence stale?
</blockquote></details>

Done.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 178 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74572#-Mt8pBNh1ByU-dT3kOiH:-Mt8qACk0CtdSZGW25Uj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a7c7377564e3270d6c2f1594d0229fa32e5513d/pkg/storage/pebble_mvcc_scanner.go#L178)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about: mostRecentKey is one of the keys (not necessarily at mostRecentTS) that was more recent than the scan.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-11 16:56 UTC, itsbilal commented
bors retry

2022-01-11 18:48 UTC, merged