release: week0 automation
cockroachdb/cockroach pull request #74570
Opened 2022-01-07 16:12 UTC by rail

Release note: None

2022-01-07 16:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74570)
<!-- Reviewable:end -->

2022-01-24 22:14 UTC, celiala reviewed
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74570)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[pkg/cmd/release/git.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-MuD7bGW1xgiIvDSZeDo:-MuD7bGW1xgiIvDSZeDp:b-3njkua) ([raw file](https://github.com/cockroachdb/cockroach/blob/d02c00579f6110927cc529954599cfa3acf8860f/pkg/cmd/release/git.go#L57)):*
> ```Go
> func nextRelease(version string) (string, error) {
> 	// TODO: use semantic version to bump
> 	fields := strings.Split(version, ".")
> ```

We can use `version.Parse` to parse/error check tag:
```
v, err := version.Parse(versionStr)
if err != nil {
  return "", err
}
return fmt.Sprintf("%s.%s.%d", v.Major(), v.Minor(), v.Patch()+1), nil
```



<!-- Sent from Reviewable.io -->

2022-01-27 16:40 UTC, rail commented
@jlinder would be great to hear some feedback. I can walk you through the PR if you prefer.

2022-02-04 22:08 UTC, jlinder requested changes
@rail here's the notes from our pair review and a few additional comments.

> Reviewed 1 of 11 files at r2, 4 of 7 files at r3, 1 of 6 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-:-Mv5lkk00LOflYBzttAB:b3ja926)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[pkg/cmd/release/git.go, line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv5iRDRAbopuPQbP0zu:-Mv5iNCE-dA8D_tjYkwp:b8mgg20) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/git.go#L24)):*
> ```Go
> }
> 
> // findNextRelease finds all required information for the next release.
> ```

I'm curious, why repeat the name of the function in the comment? I ask because I never do that since it's repetitive and it's easy to get out of sync with the function.
___
*[pkg/cmd/release/git.go, line 112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv02F_cBsNQ-ieDS887:-Mv02F_cBsNQ-ieDS888:b-culi4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/git.go#L112)):*
> ```Go
> // getMergeCommits lists all merge commits within a range of two refs.
> func getMergeCommits(fromRef, toRef string) ([]string, error) {
> 	cmd := exec.Command("git", "log", "--merges", "--format=format:%H %s", "--ancestry-path",
> ```

With `--ancestry-path` you'll need to make sure `fromRef` is an ancestor of`toRef`. The three dots, `...`, may fix this. Or [another way is to do it](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/label-merged-pr/main.go#L125-L132). 
___
*[pkg/cmd/release/jira.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv08UyK6uj5CoQs2bRy:-Mv08UyK6uj5CoQs2bRz:b-k79k24) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/jira.go#L150)):*
> ```Go
> // getClient returns jira.Client for username and password (API token).
> // To generate an API token, go to https://id.atlassian.com/manage-profile/security/api-tokens.
> func getClient(authUsername, authPassword string) (*jira.Client, error) {
> ```

Why separate out `getClient` and `newJiraClient`?
___
*[pkg/cmd/release/jira.go, line 162 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv08Ev87QCQeMe47fFd:-Mv08Ev87QCQeMe47fFe:b-p04h4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/jira.go#L162)):*
> ```Go
> }
> 
> type IssueDetails struct {
> ```

Maybe move this struct def to the topish of the file?
___
*[pkg/cmd/release/jira.go, line 230 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv07RHP2_dd_yEw2NtH:-Mv07RHP2_dd_yEw2NtI:b-whkcsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/jira.go#L230)):*
> ```Go
> }
> 
> func createTrackingIssue(
> ```

Note from convo with Rail: the `create*` names can create confusion about what is actually being created. Refactor a bit to include info about whether the function is doing something locally (creating an object) vs. going to the Jira server, etc.?
___
*[pkg/cmd/release/main.go, line 130 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv096D-9Dl1kD6mw05N:-Mv096D-9Dl1kD6mw05O:b-t5b2dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/main.go#L130)):*
> ```Go
> 	}
> 	smtpOpts := smtpOpts{
> 		from:     fmt.Sprintf("Justin Beaver <%s>", smtpUser),
> ```

Justin Beaver!!!!
___
*[pkg/cmd/release/metadata.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv04u9c8o0FfDsZFQm0:-Mv04u9c8o0FfDsZFQm1:b-5i02o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/metadata.go#L43)):*
> ```Go
> // publishBuildInfo copies release candidate metadata to a separate location.
> // This file will be used by the week 1 automation.
> func publishBuildInfo(ctx context.Context, next releaseInfo, bucket string, obj string) error {
> ```

Maybe rename this function since, by name, it looks like it publishes the file read by `getBuildInfo()`?
___
*[pkg/cmd/release/templates.go, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv5lAbe07NdicAnymvt:-Mv5lAbe07NdicAnymvu:b-7nkcss) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/templates.go#L25)):*
> ```Go
> }
> 
> // templateToText is helper function to execute a template using the html/template package
> ```

It turns out this comment is out of sync with the function name it's on. (Found this after writing my other comment asking about why the function names are used in the comment. :zany_face: )


<!-- Sent from Reviewable.io -->

2022-02-07 22:15 UTC, rail reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74570)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @jlinder, and @rail)

___
*[pkg/cmd/release/git.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-MuD7bGW1xgiIvDSZeDo:-MvLDelp0OeUoB5ZwkLn:bcxt2gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d02c00579f6110927cc529954599cfa3acf8860f/pkg/cmd/release/git.go#L57)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

We can use `version.Parse` to parse/error check tag:
```
v, err := version.Parse(versionStr)
if err != nil {
  return "", err
}
return fmt.Sprintf("%s.%s.%d", v.Major(), v.Minor(), v.Patch()+1), nil
```

</blockquote></details>

We will also need to address the alpha/beta/dotzero cases. TBD.
___
*[pkg/cmd/release/git.go, line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv5iRDRAbopuPQbP0zu:-MvLDPqmC0ec6VuxWJIq:b-y758qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/git.go#L24)):*
This is a godoc convention according to https://go.dev/blog/godoc
> Notice this comment is a complete sentence that begins with the name of the element it describes. This important convention allows ...
___
*[pkg/cmd/release/git.go, line 112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv02F_cBsNQ-ieDS887:-MvLDraeCk28Pbjuucpe:byi8hb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/git.go#L112)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

With `--ancestry-path` you'll need to make sure `fromRef` is an ancestor of`toRef`. The three dots, `...`, may fix this. Or [another way is to do it](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/label-merged-pr/main.go#L125-L132). 
</blockquote></details>

I am going to try using 3 dots instead of 2. This should address the edge case, when we have a non linear graph between versions.
___
*[pkg/cmd/release/jira.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv08UyK6uj5CoQs2bRy:-MvLE7FjCjTfbRmolHxO:bi4u9di) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/jira.go#L150)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Why separate out `getClient` and `newJiraClient`?
</blockquote></details>

We can probably simplify these. TBD.
___
*[pkg/cmd/release/jira.go, line 162 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv08Ev87QCQeMe47fFd:-MvLEH6uDjR9Z2K-H5VO:byp4bd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/jira.go#L162)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Maybe move this struct def to the topish of the file?
</blockquote></details>

SGTM. 
___
*[pkg/cmd/release/metadata.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv04u9c8o0FfDsZFQm0:-MvLEQWk7wDliL3IAx8Z:bqmbtxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/metadata.go#L43)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Maybe rename this function since, by name, it looks like it publishes the file read by `getBuildInfo()`?
</blockquote></details>

Something like `publishReleaseCandidateInfo()` probably should work. 
___
*[pkg/cmd/release/templates.go, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv5lAbe07NdicAnymvt:-MvLF92kBkDy4a0yx-GR:bx5ddgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/templates.go#L25)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

It turns out this comment is out of sync with the function name it's on. (Found this after writing my other comment asking about why the function names are used in the comment. :zany_face: )
</blockquote></details>

Hehe. The linter should catch this. ATM the PR doesn't pass  CI because I didn't update the vendor directory.


<!-- Sent from Reviewable.io -->

2022-02-08 18:56 UTC, rail reviewed
I addressed the comments and refactored it a bit. Also added --dry-run to simplify the dev workflow.

I think this is ready for the final review. If everything looks good, I need to do:

1.  mirror the new bazel archives
2. regenerate vendor
3. Update the commit message and the PR description

Optionally we can also switch from the RE Jira project to REL - this will simplify the issue template, but may need to tweak the issue details and test the submission.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-:-MvPfUFj6OhJfTAflN99:b-rkotal)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala, @jlinder, and @rail)

___
*[pkg/cmd/release/git.go, line 112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv02F_cBsNQ-ieDS887:-MvPew3q-nK2c43f61SP:b-28ytqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/git.go#L112)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

I am going to try using 3 dots instead of 2. This should address the edge case, when we have a non linear graph between versions.
</blockquote></details>

Ended up with using `git merge-base` - it just works.
___
*[pkg/cmd/release/jira.go, line 230 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv07RHP2_dd_yEw2NtH:-MvPBaw_AEIOSlHlvOpa:bewbw5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/jira.go#L230)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Note from convo with Rail: the `create*` names can create confusion about what is actually being created. Refactor a bit to include info about whether the function is doing something locally (creating an object) vs. going to the Jira server, etc.?
</blockquote></details>

I simplified most of jira.go, should be easier to read.


<!-- Sent from Reviewable.io -->

2022-02-11 17:37 UTC, rail commented
bors ping

2022-02-11 19:35 UTC, celiala approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - modulo updating the commit message & PR description

> Also added --dry-run to simplify the dev workflow.
Nice!

> Optionally we can also switch from the RE Jira project to REL - this will simplify the issue template, but may need to tweak the issue details and test the submission.

Let's hold on this (punt for a later commit) -- we're still working out permissions for the REL project (as in, only you and I have permissions currently. And we need edit permissions for the CS team, etc).

> Update the commit message and the PR description

That would be great -- thank you! (also, we can move out of `draft` status, as I think this is good to go!)
??

> Reviewed 1 of 7 files at r3, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-:-MveBV1-2YDkiatgmXbA:b-2p2tq9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder and @rail)

___
*[build/teamcity/internal/cockroach/release/process/pick_sha_impl.sh, line 29 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-MveCKmlDxjWsRw3-z18:-MveCKmlDxjWsRw3-z19:b-i8b4k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1abf5a21e25c8d3ac3fa0414593167a9ef3410a/build/teamcity/internal/cockroach/release/process/pick_sha_impl.sh#L29)):*
> ```Shell
> bazel build --config=crosslinux //pkg/cmd/release
> 
> $(bazel info --config=crosslinux bazel-bin)/pkg/cmd/release/release_/release \
> ```

(not related to this commit, more asking to understand the bazel wiring here)

how does the `/pkg/cmd/release/release_/release` here map the `BUILD.bazel` config; specifically I see:
```
go_binary(
    name = "release",
    embed = [":release_lib"],
    visibility = ["//visibility:public"],
)

```
but no mention of a `release_/release` ? :thinking: 
___
*[pkg/cmd/release/git.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-MuD7bGW1xgiIvDSZeDo:-MveEmFrDeKYYXpBtr6g:b-uwu4c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d02c00579f6110927cc529954599cfa3acf8860f/pkg/cmd/release/git.go#L57)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

We will also need to address the alpha/beta/dotzero cases. TBD.
</blockquote></details>

It looks like the `semver` package as some nice utility functions that `version` doesn't have - nice!
___
*[pkg/cmd/release/git.go, line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-MveD6cN619vxIZ8t6u-:-MveD6cN619vxIZ8t6u0:bosgvhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1abf5a21e25c8d3ac3fa0414593167a9ef3410a/pkg/cmd/release/git.go#L46)):*
> ```Go
> 		return releaseInfo{}, fmt.Errorf("cannot check if the candidate sha was released: %w", err)
> 	}
> 	if len(releasedVersions) > 0 {
> ```

Verifying that this SHA hasn't already been published is a nice check here!
___
*[pkg/cmd/release/jira.go, line 230 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv07RHP2_dd_yEw2NtH:-MveFBYtAqTFS2YtwBDi:b-5kg7gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/jira.go#L230)):*
> I simplified most of jira.go, should be easier to read.

Thanks for cleaning up `jira.go` - this helps clarify the the `create*` names 
___
*[pkg/cmd/release/metadata.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv04u9c8o0FfDsZFQm0:-MveGc0b1QNnVmC_mkQj:bmwydsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/metadata.go#L43)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Something like `publishReleaseCandidateInfo()` probably should work. 
</blockquote></details>

`publishReleaseCandidateInfo()` feels clear to me, thanks!


<!-- Sent from Reviewable.io -->

2022-02-14 16:33 UTC, jlinder approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-:-Mvt3vLi2vtd71Uz90XX:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @celiala and @rail)

___
*[pkg/cmd/release/git.go, line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv5iRDRAbopuPQbP0zu:-MvsrIpx8gyloka_y9cw:bpkkfpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/git.go#L24)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

This is a godoc convention according to https://go.dev/blog/godoc
> Notice this comment is a complete sentence that begins with the name of the element it describes. This important convention allows ...
</blockquote></details>

TIL. :thumbsup: 
___
*[pkg/cmd/release/git.go, line 112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv02F_cBsNQ-ieDS887:-MvswPrP-hDhwRLM-423:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/git.go#L112)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Ended up with using `git merge-base` - it just works.
</blockquote></details>

:thumbsup: 
___
*[pkg/cmd/release/jira.go, line 230 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv07RHP2_dd_yEw2NtH:-Mvt1s-B5W-nqUarVdlz:bdnu3o6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/jira.go#L230)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

> I simplified most of jira.go, should be easier to read.

Thanks for cleaning up `jira.go` - this helps clarify the the `create*` names 

</blockquote></details>

Thanks Rail. 
___
*[pkg/cmd/release/metadata.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74570#-Mv04u9c8o0FfDsZFQm0:-Mvt3RCi75V7-QRAJ9V0:b66nscb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ed44017900a613c766b0a9ced172fc6a46190d3/pkg/cmd/release/metadata.go#L43)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

`publishReleaseCandidateInfo()` feels clear to me, thanks!
</blockquote></details>

:heavy_plus_sign: 


<!-- Sent from Reviewable.io -->

2022-02-14 21:29 UTC, celiala commented
Thanks for updating the title & description 

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

🚢

2022-02-15 02:59 UTC, rail commented
bors r=celiala,jlinder

2022-02-15 04:02 UTC, merged