cdc: Allow webhook sink to provide client certificates to the remote webhook server
cockroachdb/cockroach pull request #74645
Opened 2022-01-10 20:02 UTC by sherman-grewal

Allow the webhook sink to provide client certificates to the remote webhook server.

Resolves #74230

Release note: None

2022-01-10 20:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74645)
<!-- Reviewable:end -->

2022-01-10 21:41 UTC, miretskiy requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74645)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @sherman-grewal)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74645#-Mt4vA9e5ufm_UDJXFOJ):*
I think you need to amend your change to include some  some additional information.
In particular, we should definitely have a release note here.
___
*[pkg/ccl/changefeedccl/sink_webhook.go, line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74645#-Mt4vnnW95VKPqY2cMhG:-Mt4vnnW95VKPqY2cMhH:bxcwdej) ([raw file](https://github.com/cockroachdb/cockroach/blob/f60862199f78362c03c32301df3e082a7f5644ab/pkg/ccl/changefeedccl/sink_webhook.go#L362)):*
> ```Go
> 	if err := u.decodeBase64(changefeedbase.SinkParamClientKey, &dialConfig.clientKey); err != nil {
> 		return nil, err
> 	}
> ```

Can we expand e.g. `webhookFeedFactory` (in testfeed_test.go) to also support these params?
For example, we could, perhaps add an option to `webhookTestWithOptions` function to also specify if we want "secure" connection, and have webhookFeedFactory start a secure http server for message ingestion?


<!-- Sent from Reviewable.io -->

2022-01-14 20:12 UTC, miretskiy approved these changes

2022-01-14 20:26 UTC, HonoreDB approved these changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74645)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @sherman-grewal)



<!-- Sent from Reviewable.io -->

2022-01-14 21:59 UTC, sherman-grewal commented
bors r+

2022-01-14 23:21 UTC, merged