rfcs: introduce rfc to support protected timestamps in multi-tenancy
cockroachdb/cockroach pull request #74685
Opened 2022-01-11 17:33 UTC by arulajmani

The protected timestamp subsystem (PTS) provides a mechanism for long
running operations such as backup and CDC to prevent any deleted data
they are operating on from getting garbage collected.

The PTS subsystem was designed before CRDB supported multi-tenancy,
and as such, only applies to host tenant ranges. This RFC proposes to
leverage the span configuration infrastructure as the transport
mechanism for protected timestamps. This allows secondary tenants
to lay protected timestamps as well, making the long running operations
mentioned above more robust.

The RFC only proposes changing the transport mechanism for the PTS
subsystem; the mechanism by which protection is guaranteed in KV
remains the same. However, the RFC does propose expressing protection
in terms of schema objects as opposed to static spans to unlock new
backup functionality for the future.

Release note: None

2022-01-11 17:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74685)
<!-- Reviewable:end -->

2022-01-13 16:04 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74685)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, @dt, @irfansharif, @nvanbenschoten, and @stevendanna)

___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtJ3zxx2-w3qDAwZFI3:-MtJ3zxx2-w3qDAwZFI4:bhp06c1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L73)):*
> ```Markdown
> lay protected timestamp on (say) databases and have them take effect on all tables inside the database 
> (including those created in the future!). This is quite powerful as it allows us to 
> [decouple scheduled backups with revision history from the GC TTL] (https://github.com/cockroachdb/cockroach/issues/67282) 
> ```

nit: extra space breaks the link
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtJ4V-A5fanWQ2rjXv6:-MtJ4V-B9xSJYMQPMCtb:b-lilz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L112)):*
> ```Markdown
> 
> The new PTS subsystem will operate on schema objects instead of a list of static spans. Schema 
> objects form the catalog hierarchy (“cluster”->database->schema->table->index->partition). Leaf 
> ```

`(“cluster”->database->schema->table->index->partition->subpartition->subpartition->...)` technically



_Code quote:_
```Markdown
“cluster”->database->schema->table->index->partition
```
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtJ4oA1237BeT7M2INC:-MtJ4oA1237BeT7M2IND:b-gk847w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L134)):*
> ```Markdown
> 
> The new invariant is slightly unsatisfying for users of the subsystem because there can be an 
> arbitrary amount of time between writing the PTS record and span configuration reconciliation. 
> ```

I think it's worth forwarding a link to a later section where we talk about the possibility of the client waiting for reconciliation. 
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 618 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtJ57Km1TqH1flqUasM:-MtJ57Km1TqH1flqUasN:b1bapcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L618)):*
> ```Markdown
> 
> 
> ## Future Work
> ```

I think here or in an Open Questions section we should discuss clients being able to observe reconciliation timestamps and what a client-observable invariant might look like.


<!-- Sent from Reviewable.io -->

2022-01-14 00:31 UTC, nvanbenschoten reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74685)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, @dt, @irfansharif, and @stevendanna)

___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKFLGtDknANwZ5kBgl:-MtKFLGtDknANwZ5kBgm:bbpkuk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L5)):*
> ```Markdown
> - Start Date: 2021-11-11
> - Authors: Arul Ajmani, Aditya Maru
> - RFC PR: (PR # after acceptance of initial draft)
> ```

#74685
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKFU6mCymNO11cAp87:-MtKFU6mCymNO11cAp88:b-dmhevd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L14)):*
> GC runs on the host tenant

I don't think this is quite how we'd describe things today. GC runs in KV, not on a particular tenant. However, KV only checks the host tenant's PTS table today.
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKGAYl4pK32-Is5ovU:-MtKGAYl4pK32-Is5ovV:bchm71l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L25)):*
> ```Markdown
> The rework of the PTS subsystem proposed here builds on top of the newly introduced 
> [span configuration infrastructure](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20210610_tenant_zone_configs.md) 
> as the transport layer. The RFC proposes how the existing span configuration infrastructure can be 
> ```

"transport layer" between what and what?
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKxpUB48sGJj4Smkd9:-MtKxpUB48sGJj4SmkdA:bq7vl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L184)):*
> ```Markdown
> 
> ```protobuf
> message SystemSpanConfig {
> ```

Did we explore the alternative of using the same `SpanConfig` type here? Why use a special type with fewer fields? SpanConfig inheritance is across all existing fields is well-defined.
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKuxlG-pskeI1bNI8y:-MtKuxlG-pskeI1bNI8z:byczvwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L287)):*
> ```Markdown
> Internally, we will continue to store the PTS records in the `system.protected_ts_records` table. 
> We will add a bytes `target` column alongside the existing `spans` column, to store the `ptpb.Target`
> protobuf which will describe what object the record is protecting.
> ```

Let's mention here that the `system.protected_ts_records` table is indexed on this UUID, so addressing a PTS record by its id is a point operation.
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 345 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKvzut2bXVzkrG4D8m:-MtKvzut2bXVzkrG4D8n:b-veallj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L345)):*
> ```Markdown
>   // GetProtectedTimestampsForCluster returns all the protected timestamps that
>   // apply to the entire cluster's keyspace.
>   GetProtectedTimestampsForCluster() []hlc.Timestamp
> ```

Should these return raw `hlc.Timestamp`s, or a message wrapping the timestamp and the `ProtectionMode`? I guess this question also applies to the new field in `SystemSpanConfig`. cc. @ajwerner 
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKwa5e8TIaCdPf_8jS:-MtKwa5e8TIaCdPf_8jT:b3925lw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L394)):*
> ```Markdown
> 
> Full reconciliation does not change much with the introduction of `SystemSpanConfigs` -- much of the
> heavy lifting will be continue to be done by the `FullTranslate` method of the `SQLTranslator`. In 
> ```

`s/will be continue/will continue/`
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKxTzYASm_WUJ0NXvG:-MtKxTzYASm_WUJ0NXvH:brzu9z9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L405)):*
> ```Markdown
> transaction in the `SQLTranslator` that was used to intialize the `SystemPTSRecordTableReader` we 
> will ensure that the protected timestamp state update to KV is represents a consistent view from the
> tenant's perspective.
> ```

Is this paragraph assuming a single reconciliation batch and no pagination across the KV connector?
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 652 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKzRFb-CpvK5sOlAdW:-MtKzRFb-CpvK5sOlAdX:b-ybya1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L652)):*
> ```Markdown
> unchanged which inturn simplifies the migration from the old subsystem to the new one.
> 
> ### Building a fully generalized hierrarchy for span configurations
> ```

`s/hierrarchy/hierarchy/`
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 684 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKzhWt1DOB4CiE65VW:-MtKzhWt1DOB4CiE65VX:bm74aek) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L684)):*
> ```Markdown
> of change to the newly introduced span configuration infrastructure which is yet to be hardened. 
> The fully generalized scheme is also more involved and would require a complex batching scheme when 
> reconciling the entire SQL state with KV. 
> ```

Do you mind adding one more sentence to this about what was complex about this batching scheme?


<!-- Sent from Reviewable.io -->

2022-01-14 02:07 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74685)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, @dt, @irfansharif, @nvanbenschoten, and @stevendanna)

___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 189 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtLKJhL519WNIsSr4VQ:-MtLKJhL519WNIsSr4VR:bwac3x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L189)):*
> ```Markdown
>   // ProtectedTimestamps is a list of timestamps which are protected from being
>   // GC-ed.
>   repeated util.hlc.Timestamp protected_timestamps = 1  [(gogoproto.nullable) = false];
> ```

Wrap this in a message type for future extensions? 
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 345 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKvzut2bXVzkrG4D8m:-MtLJbRSBS6AGl0VWl8M:b-hr48xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L345)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should these return raw `hlc.Timestamp`s, or a message wrapping the timestamp and the `ProtectionMode`? I guess this question also applies to the new field in `SystemSpanConfig`. cc. @ajwerner 
</blockquote></details>

Even if we don't add a `ProtectionMode` field at this point (the whole yagni thing and the winds seem to be blowing towards nobody really wanting `ProtectAt`). I feel fine about this for a go interface for now, we can always add more wrapping later. However, in protos, we should take care to wrap the timestamps in a message so we can add more info there. That's my 2c on this at this point. 


<!-- Sent from Reviewable.io -->

2022-01-14 03:24 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74685)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @dt, @irfansharif, @nvanbenschoten, and @stevendanna)

___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKxpUB48sGJj4Smkd9:-MtLPodl5Jhq2MrhUsPH:bd1l7ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L184)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did we explore the alternative of using the same `SpanConfig` type here? Why use a special type with fewer fields? SpanConfig inheritance is across all existing fields is well-defined.
</blockquote></details>

We considered using the same `SpanConfig` proto but decided to introduce this special type once the design moved away from generalized inheritance. As the hierarchy we're proposing is strictly above `RANGE DEFAULT`, `SpanConfigs` are guaranteed to be fully hydrated so we can never have inheritance of fields. We made this fully hydrated distinction explicit by choosing to make all fields on `SpanConfigs` non-nullable (unlike zone configs) and introducing this new message lets us keep things that way.

Now that I type this, maybe this fully hydrated argument may not apply in the future if we introduce new fields on `SpanConfigs` to be only set by the host tenant and apply to all tenant ranges. But a different type here shouldn't preclude us from doing so in the future. 
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtLZN6k6lhIIcuxbzGe:-MtLZN6k6lhIIcuxbzGf:baerg5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L194)):*
> ```Markdown
> // SystemSpanConfigEntry is a SystemSpan and its corresponding SystemSpanConfig.
> message SystemSpanConfigEntry {
>   Span systemSpan = 1 [(gogoproto.nullable) = false];
> ```

Wanted to call out that this might change as described in https://github.com/cockroachdb/cockroach/pull/74765#issuecomment-1011474576. 
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 345 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKvzut2bXVzkrG4D8m:-MtLYlTqEISriu1XV0Du:b-flbcal) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L345)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Even if we don't add a `ProtectionMode` field at this point (the whole yagni thing and the winds seem to be blowing towards nobody really wanting `ProtectAt`). I feel fine about this for a go interface for now, we can always add more wrapping later. However, in protos, we should take care to wrap the timestamps in a message so we can add more info there. That's my 2c on this at this point. 
</blockquote></details>

That's a fair point -- I didn't have it initially because we weren't making use of anything but the timestamp in KV, but I like the idea of future proofing by wrapping this in a message on the proto but keeping the interface as is for now.
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKxTzYASm_WUJ0NXvG:-MtLZaBDACLA9cZLL9Me:ba1w5jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L405)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this paragraph assuming a single reconciliation batch and no pagination across the KV connector?
</blockquote></details>

Yeah, or, at the least, it assumes that even if we paginate across the connector we will only write the updates in a single transaction. I'm not sure if doing so is reasonable. 

It's also worth capturing the discussion we had in the zone configs pod ( @ajwerner , @irfansharif , @nvanbenschoten , @adityamaru , and I) about how much we care about this. While it does make things easier to reason about and I think it's something we should try to do unless prohibitive, Andrew brought up a good point that it isn't really a guarantee consumers of the subsystem would really care about -- instead, consumers of the subsystem 
are interested in when their span config (with the protection on it) is reconciled and has made its way down to KV. 


<!-- Sent from Reviewable.io -->

2022-01-15 13:26 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74685)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @dt, @irfansharif, @nvanbenschoten, and @stevendanna)

___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtSn3AsEKFlLAoUWKRT:-MtSn3AtC0qoppI_iG0i:b40puk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L6)):*
> ```Markdown
> - Authors: Arul Ajmani, Aditya Maru
> - RFC PR: (PR # after acceptance of initial draft)
> - Cockroach Issue: #73727
> ```

nit: it's customary to write `[#NNNN](http://link/to/issue/NNNN)` so that we get the hyperlink when viewing the rendered doc.
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 684 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtSuFAL4GS4Fs8y_Kht:-MtSuFAL4GS4Fs8y_Khu:b6liy9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L684)):*
> ```Markdown
> of change to the newly introduced span configuration infrastructure which is yet to be hardened. 
> The fully generalized scheme is also more involved and would require a complex batching scheme when 
> reconciling the entire SQL state with KV. 
> ```

Maybe also worth a note about the complexity of detecting cycles to protect against low-level mistakes / bugs.


<!-- Sent from Reviewable.io -->

2022-01-18 19:24 UTC, irfansharif requested changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

This RFC for me feels 90% done; most of it feels sound. While there are some specific impl choices around API signatures and typing, they feel relatively minor to me and I'd be happy bottoming out on them wherever you prefer (here, or in actual PRs introducing them). A few of my comments below are marked with "NB:" and are worth agreeing upon (maybe in our pod today?), everything else is a nit or questions for my own understanding.

I see we've been tracking individual PRs/work-breakdown as part of https://github.com/cockroachdb/cockroach/issues/73727
(a few have already landed!). I encourage you to fill in more details there, and maybe mark exactly what's needed for 22.1. I think we know now with this RFC, but it's a good place to coordinate and communicate from.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-:-MtiUazz4ahN6Qei3Epr:bo2f7sf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @dt, @irfansharif, @nvanbenschoten, and @stevendanna)

___
*[-- commits, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MthmeAfE7pVmNkqWmjQ):*
[nit] Same as Nathan's comment below, more words to explain what we mean by "transport" (something something shipping of tenant scoped/keyspace protection records down into KV, where admittance is mediated by KV -- but worded better).
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtKFU6mCymNO11cAp87:-MtiRMO5AzFyHsSVq_D2:b2ngtib) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L14)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> GC runs on the host tenant

I don't think this is quite how we'd describe things today. GC runs in KV, not on a particular tenant. However, KV only checks the host tenant's PTS table today.
</blockquote></details>

+1.
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MthnLHn7Pp27znZMb4y:-MthnLHn7Pp27znZMb4z:bpivvtv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L24)):*
> ```Markdown
> 
> The rework of the PTS subsystem proposed here builds on top of the newly introduced 
> [span configuration infrastructure](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20210610_tenant_zone_configs.md) 
> ```

[nit] All throughout the doc: refer to the other RFCs/packages/files by SHA/permalink instead of `master`, path might break in the future.
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-Mtht4Yu1VII1UqT3YjX:-Mtht4Yu1VII1UqT3YjY:bb016t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L70)):*
> ```Markdown
> 
> In addition to building feature parity, the new protected timestamp subsystem aims to express PTS 
> records in terms of schema objects instead of static keyspans.This allows users of the subsystem to 
> ```

[nit] Missing space: "keyspans.This"
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-Mtho9lSCzNvmHRiYr_Y:-Mtho9lSCzNvmHRiYr_Z:b-819isu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L78)):*
> ```Markdown
> wide default GC TTL set to 25 hours.
> 
> The introduction of hierarchy in KV for span configurations is necessitated by the desire for the host 
> ```

[nit] Maybe caveat this by the "limited" or "static" form that this RFC is proposing below?
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MthoMN7Cw1dvKWGH-Kt:-MthoMN7Cw1dvKWGH-Ku:b-gvn5fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L81)):*
> ```Markdown
> tenant to lay protected timestamps on one or all secondary tenants’ keyspace. This is required when 
> the host tenant performs full tenant or full cluster backups, respectively. We also want to allow a 
> “fast path” for secondary tenants to set protected timestamps on their entire keyspace with no write
> ```

[nit] s/no write/minimal write
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtiRgY-3MUpnCdmQt7s:-MtiRgY06hNCcivEIfiY:byrv5nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L101)):*
> ```Markdown
> the `Connector`. KV then uses its view of the reconciled state to make various split, merge, and 
> rebalancing decisions. In line with this SQL/KV separation, the design below includes two orthogonal
> proposals, each with its own set of alternatives, to make protected timestamps work with multi-tenancy:
> ```

This way of structuring the RFC is pretty clarifying and easy to grok, thanks for doing it.
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-Mthtc3o-OATUCZZEB8Z:-Mthtc3o-OATUCZZEB8_:b-69z2a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L122)):*
> ```Markdown
> Any future leaves in the subtree will also be protected until the record is removed.
> 
> The original RFC provided an invariant in terms of the transaction that wrote the PTS record. The 
> ```

[nit] Link to the relevant section in the PTS RFC.
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-Mthtgd7EYrqSWr-nqVx:-Mthtgd7EYrqSWr-nqVy:b-fdwiws) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L133)):*
> ```Markdown
> ```
> 
> The new invariant is slightly unsatisfying for users of the subsystem because there can be an 
> ```

Is it any more/less "unsatisfying" than before? There was an arbitrary delay earlier with gossip propagation of the GC TTL before too, right? And the internal polling of protectedts.Cache? The only invariant change AFAIU is that we're talking about the txn writing to `system.span_configurations` vs. the txn writing to `system.zones`, which does not feel very controversial or that noticeably different to readers. The "invariant changes", if any, are related to us omitting protectedts verification because of non-destructive retry behavior -- something we've explained clearly below. If you agree, I'd maybe de-emphasize these few paragraphs.
___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MtiSSry54JXRfeJ2CQO:-MtiSSry54JXRfeJ2CQP:b-hcece8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L141)):*
> ```Markdown
> 
> Lastly, it's worth calling out that even though KVs view of protected timestamp state for a tenant 
> may be arbitrarily stale, it *will* be a consistent view that was valid at some timestamp  [...]

2022-01-18 19:34 UTC, irfansharif approved these changes
Woops, wrong button.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-:-Mtif_8gAOGy9maLWY4G:b-irvzj4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @dt, @irfansharif, @nvanbenschoten, and @stevendanna)



<!-- Sent from Reviewable.io -->

2022-01-25 17:18 UTC, irfansharif commented
+cc @nvanbenschoten, @ajwerner, friendly bump for reviews for this RFC and #74765 which is more updated for some proto definitions. There's already a fair bit of progress towards implementing this RFC (#73727), and it'd be better to get on the same page around interfaces/RPCs before we continue going further.

2022-01-25 17:56 UTC, ajwerner reviewed
I feel like there's a bunch of good outstanding comments to be addressed. Can we get one more pass iteration before stamping this and merging it in-progress?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-:-MuHN5vz-BXZZMASIZEu:bb562pn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @dt, @irfansharif, @nvanbenschoten, and @stevendanna)

___
*[docs/RFCS/20211111_multitenant_protected_timestamps.md, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-MuHNJ3T-S9W41WKSX3k:-MuHNJ3T-S9W41WKSX3l:b55kkgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a54ad70f95ea9854d706fbf116f84d52467cb30/docs/RFCS/20211111_multitenant_protected_timestamps.md#L2)):*
> ```Markdown
> - Feature Name: Multi-tenant Protected Timestamps Support
> - Status: draft
> ```

I'd update this to `in-progress`


<!-- Sent from Reviewable.io -->

2022-01-26 15:34 UTC, nvanbenschoten reviewed
> I feel like there's a bunch of good outstanding comments to be addressed. Can we get one more pass iteration before stamping this and merging it in-progress?

+1, I don't see any remaining discussion points that should block this from merging, so let's get one more iteration and then it should be good to merge.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74685#-:-MuM0OCkBE0zYAATVw3d:b-axnx64)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @dt, @irfansharif, @nvanbenschoten, and @stevendanna)



<!-- Sent from Reviewable.io -->

2022-08-07 20:13 UTC, irfansharif commented
I'm just going to go ahead and bors this, the text looks up-to-date enough. If anyone wants to make additional amendments, do so in different PRs.

bors r+

2022-08-07 21:50 UTC, irfansharif commented
bors r+

2022-08-07 23:00 UTC, merged