Ingestion
cockroachdb/cockroach pull request #74753
Opened 2022-01-12 18:54 UTC by gh-casper

2022-01-12 18:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74753)
<!-- Reviewable:end -->

2022-01-26 10:20 UTC, gh-casper reviewed
Will add more unit tests later that tests other aspects of the stream replication: how does the dest cluster react to the replication stream stop, pause and restart. and also do some assertions on the producer job's lifecycle.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-:-MuKt-6O9iMUXXqC7eOH:bhfb9dl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)



<!-- Sent from Reviewable.io -->

2022-01-26 15:13 UTC, miretskiy requested changes
> Reviewed 2 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @gh-casper)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLpxAq7TkZPVLKAnbV):*
Perhaps release note should note what this setting is for.
___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLq2nk-OLbsf4Iun_q:-MuLq2nk-OLbsf4Iun_r:b-rykyds) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/changefeedccl/changefeedbase/options.go#L85)):*
> ```Go
> 	// subscribes only to new messages.
> 	OptNoInitialScan = `no_initial_scan`
> 	// OptEmitAllResolvedTimestamps is a sentinel value to indicate that all
> ```

not sure this change belongs w/ this PR?
___
*[pkg/ccl/streamingccl/settings.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLq9G6AVfT6na3Ddee:-MuLq9G6AVfT6na3Ddef:b-wr75yo) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/settings.go#L36)):*
> ```Go
> 
> // UsePartitionedStreamClient controls whether to use partitioned stream client to
> // consume a replication stream.
> ```

Is there any time we would not want to use partition stream client?
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLqLjr0J_xdazehN0z:-MuLqLjr0J_xdazehN1-:b1d1zv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L23)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/security"
> 	"github.com/cockroachdb/cockroach/pkg/streaming"
> 	"github.com/cockroachdb/cockroach/pkg/testutils/sqlutils"
> ```

we definitely don't want to depend on testutils in production code.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLqR_V5zCNMypoiuwS:-MuLqR_V5zCNMypoiuwT:b-ks47rr) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L31)):*
> ```Go
> type partitionedStreamClient struct {
> 	db *gosql.DB // DB handle to the source cluster
> 	mu sync.Mutex
> ```

a more canonical way of protecting multiple fields under same mutex is to add
```
mu struct {
  syncutil.Mutex
  .. all fields protected by mutext
}
```
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLrMqc0woqTr1dcOms:-MuLrMqc0woqTr1dcOmt:b-vuikt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L35)):*
> ```Go
> 	closed bool
> 	pgURLCertCleanup []func()
> 	activeSubscriptions map[*partitionedStreamSubscription]bool
> ```

if you only store "true" in this map, it's cheaper to have a map of `map[*subscription]struct{}`
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLqgGB1-qXYwdt9tVE:-MuLqgGB1-qXYwdt9tVF:b-3lolay) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L45)):*
> ```Go
> 	return &partitionedStreamClient{
> 		db: db,
> 		pgURLCertCleanup: make([]func(), 0),
> ```

not sure what this is used for, but pre-making a slice w/ 0 storage is the same as not making it.
YOu can append to nil slice.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLr7YM5uMmPM2BZjSm:-MuLr7YM5uMmPM2BZjSn:b-59pged) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L136)):*
> ```Go
> 	topology := Topology{}
> 	for _, sp := range spec.Partitions {
> 		pgUrl, cleanupCertDir, err := sqlutils.PGUrlE(sp.SQLAddress.String(),
> ```

definitely need to use something else here. Please no testutils packages in prod code.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLrF537aac7BV34or9:-MuLrF537aac7BV34orA:b-tf8fe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L164)):*
> ```Go
> 	defer p.mu.Unlock()
> 	// Close all the active subscriptions and disallow more usage.
> 	p.closed = true
> ```

do we want to return if already closed? panic? return an error?
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLrYDx-rCF00Kca4Lf:-MuLrYDx-rCF00Kca4Lg:bn2k8ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L182)):*
> ```Go
> 	}
> 	sps.StartFrom = checkpoint
> 	sps.Config = streampb.StreamPartitionSpec_ExecutionConfig{MinCheckpointFrequency: 2 * time.Second}
> ```

why do we have this magic constant here?
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLrpC22jaHjiN93Hnq:-MuLrpC22jaHjiN93Hnr:b-yom52b) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L293)):*
> ```Go
> 		if event == nil {
> 			return nil
> 		}
> ```

I think it is strange to have methods (getNextEvent) `return nil, nil`.  I think you need to explain why
seeing nil event is okay.  Alternatively (and that would be my preference), do not return nil, nil events.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLs6zU2qvkLFC2-uZS:-MuLs6zU2qvkLFC2-uZT:b-s5j27) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L297)):*
> ```Go
> 		case p.eventsChan <- event:
> 		case <-p.closeChan:
> 			return nil
> ```

you could return io.EOF 
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLsElW4DuNRihf1CMp:-MuLsElXCJTnfEgpd2bM:b-x53d1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L143)):*
> ```Go
> }
> 
> func newHeartbeatSender(flowCtx *execinfra.FlowCtx, spec execinfrapb.StreamIngestionFrontierSpec) (*heartbeatSender, error) {
> ```

can we wrap this a bit?
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLsGv39Zvw0y6eGMXO:-MuLsGv39Zvw0y6eGMXP:b-6s6cks) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L145)):*
> ```Go
> func newHeartbeatSender(flowCtx *execinfra.FlowCtx, spec execinfrapb.StreamIngestionFrontierSpec) (*heartbeatSender, error) {
> 	partitionedStream := streamingccl.UsePartitionedStreamClient.Get(&flowCtx.EvalCtx.Settings.SV)
> 	streamClient, err := streamclient.NewStreamClient(streamingccl.StreamAddress(spec.StreamAddress), partit [...]

2022-01-27 01:29 UTC, gh-casper reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLpxAq7TkZPVLKAnbV):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Perhaps release note should note what this setting is for.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLq2nk-OLbsf4Iun_q:-MuMAE5u0pvBb4XRL6CZ:bea0vo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/changefeedccl/changefeedbase/options.go#L85)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

not sure this change belongs w/ this PR?
</blockquote></details>

I have a habit of correcting obvious typos and wrong comments when I see it. Here it shouldn't matter even it's out of scope of this PR, right?
___
*[pkg/ccl/streamingccl/settings.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLq9G6AVfT6na3Ddee:-MuMAiZzEFlRtoS5WxcQ:b-aajyag) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/settings.go#L36)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Is there any time we would not want to use partition stream client?
</blockquote></details>

When we want to use the original sinkless stream client. Do we want to deprecate that in this PR?
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLqLjr0J_xdazehN0z:-MuMrz_i48eq_t5lzeb7:bac4pnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L23)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we definitely don't want to depend on testutils in production code.
</blockquote></details>

See the comment below.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLqR_V5zCNMypoiuwS:-MuMDNoE54yKxaX_gtp_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L31)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

a more canonical way of protecting multiple fields under same mutex is to add
```
mu struct {
  syncutil.Mutex
  .. all fields protected by mutext
}
```
</blockquote></details>

Done.



_Code quote:_
```Go
partitionedStreamClient
```
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLrMqc0woqTr1dcOms:-MuMBFpq3_u5209fOuJy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L35)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

if you only store "true" in this map, it's cheaper to have a map of `map[*subscription]struct{}`
</blockquote></details>

Done.



_Code quote:_
```Go
activeSubscriptions map[*partitionedStreamSubscription]bool
```
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLqgGB1-qXYwdt9tVE:-MuMDbTz6f-97XD2u2uw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L45)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

not sure what this is used for, but pre-making a slice w/ 0 storage is the same as not making it.
YOu can append to nil slice.
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLr7YM5uMmPM2BZjSm:-MuMZ9HFCLpjeAz94bMQ:b-6qcr52) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L136)):*
> testutils
I couldn't find any other helper function in non-testutils packages that converts an sql address into pgurl with certs. 
What I can do is to define a helper that doesn't rely on any sqlutils code in this file, but it relies on securitytest code. sqlutils.PGUrlE definition relies on a lot of securitytest code .
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLrF537aac7BV34or9:-MuMc4BnDxx_lYy-9KGf:b-agczhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L164)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we want to return if already closed? panic? return an error?
</blockquote></details>

It makes more sense to make it a no-op if already closed.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLrYDx-rCF00Kca4Lf:-MuMd1nW32Ach_NBe6jc:bj91q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L182)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why do we have this magic constant here?
</blockquote></details>

Now I changed the `defaultMinCheckpointFrequency` to be 3 seconds. We can adjust it or make a cluster setting or make it dynamic once it got more productionized.



_Code quote:_
```Go
StreamPartitionSpec_ExecutionConfig
```
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLrpC22jaHjiN93Hnq:-MuMeZG_9SvuzzMPwwV0:b-rqobqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L293)):*
> getNextEvent
Removed. I accidentally added it for debugging purpose.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLs6zU2qvkLFC2-uZS:-MuMgxFB1Hh5tfbBy-87:b7eaob2) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L297)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

you could return io.EOF 
</blockquote></details>

I return nil here on purpose because we want to subscription to exit quietly here to not cause other subscriptions in the same ctxgroup.Group to exit. But I get your point since returing io.EOF is more unix style stream alike.



_Code quote:_
```Go
p.eventsChan <- event:
```
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLsElW4DuNRihf1CMp:-MuMhd0g84QJvR-GPDgk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L143)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Mir [...]

2022-01-27 01:43 UTC, dt commented on pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go
> +	tenantCAPath := filepath.Join(security.EmbeddedCertsDir, security.EmbeddedTenantCACert)
Do we ever connect to or as a tenant? isn't it always host-to-host connections, even if we're streaming a tenant?

2022-01-27 15:04 UTC, miretskiy requested changes
> Reviewed 2 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @gh-casper, and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLq2nk-OLbsf4Iun_q:-MuQxx140YZfIkc10-GN:bih6g9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/changefeedccl/changefeedbase/options.go#L85)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

I have a habit of correcting obvious typos and wrong comments when I see it. Here it shouldn't matter even it's out of scope of this PR, right?
</blockquote></details>

I wouldn't.  Send out cleanup PRs.  
___
*[pkg/ccl/streamingccl/settings.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLq9G6AVfT6na3Ddee:-MuQy18DBfNGIC0A-chx:bchslr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/settings.go#L36)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

When we want to use the original sinkless stream client. Do we want to deprecate that in this PR?
</blockquote></details>

I think so.  Why would we want to keep something we know doesn't work (well)?
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLr7YM5uMmPM2BZjSm:-MuR-2yfEcAe-5yGGpJj:b-q5w8gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L136)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

> testutils
I couldn't find any other helper function in non-testutils packages that converts an sql address into pgurl with certs. 
What I can do is to define a helper that doesn't rely on any sqlutils code in this file, but it relies on securitytest code. sqlutils.PGUrlE definition relies on a lot of securitytest code .




</blockquote></details>

See comments on that function; but using testutils is a big red flag.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuQylpx9YaypCtArvt3:-MuQylpx9YaypCtArvt4:b-pa729o) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L116)):*
> ```Go
> // postgresURL converts an SQL serving address into a postgres URL. In order to connect securely
> // using postgres, this method will create temporary on-disk copies of
> // certain embedded security certificates. The certificates will be created in a new temporary
> ```

This has me worried.  Perhaps we should involve someone from security (or server; perhaps @knz ).
To be clear, I'm not sure what we do here is what we should be doing in the first place.
But, if we absolutely must do what's described in this commend, the fact that we are storing anything
on temporary directory, which, btw, may not be available, or may not even be encrypted(!), just sounds wrong to me.
We could probably store this in memory; but storing it in temp dir.. just sounds wrong.



_Code quote:_
```Go
// using postgres, this method will create temporary on-disk copies of
// certain embedded security certificates. The certificates will be created in a new temporary
```
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuQzk2AEFoOnbFvovFp:-MuQzk2AEFoOnbFvovFq:b-9b632m) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L130)):*
> ```Go
> 
> 	// This CA is the one used by the SQL client driver to authenticate KV nodes on the host cluster.
> 	caPath := filepath.Join(security.EmbeddedCertsDir, security.EmbeddedCACert)
> ```

I'm thoroughly confused.  This code runs on a destination cluster; correct?  And from destination cluster we want to connect to source cluster.  Then... what good is it to use destination cluster certs when connecting to source cluster?
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuQyJmq9ame8N12_RKO:-MuQyJmq9ame8N12_RKP:bq2cwvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L131)):*
> ```Go
> 	// This CA is the one used by the SQL client driver to authenticate KV nodes on the host cluster.
> 	caPath := filepath.Join(security.EmbeddedCertsDir, security.EmbeddedCACert)
> 	tempCAPath, err := securitytest.RestrictedCopy(caPath, tempDir, "ca")
> ```

I understand that you were trying to do something where existing utilities are written for tests.
I think it's a red flag for me.  First, if you absolutely must have this, you would need to implement these
helpers outside test util packages.  Secondly, I would kinda ask: why don't we have these helpers already implemented?  Are we trying to do something from production code that we quite frankly shouldn't be doing?
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuR-Fec4-ixD9iPYTuN:-MuR-Fec4-ixD9iPYTuO:b-k3fai9) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L262)):*
> ```Go
> 		// Buffered channel allows caller to close an already closed subscription
> 		// without causing deadlock.
> 		closeChan: make(chan struct{}, 10),
> ```

Alright, something is off here.  Super magic constant of 10.  On a close chan is just suspicious.  Are we closing things 10 times? Why? What are we writing to that channel and why?  If you want to signal closure, then just close the channel.  Reading from the closed channel is okay.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 386 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuR-p6Y2mMmL9d_VEWc:-MuR-p6ZBwnP4aphQW7t:bizghyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L386)):*
> ```Go
> 	if !p.closed {
> 		p.closeChan <- struct{}{}
> 	}
> ```

Canonical way to do this is to just close(p.CloseChan); 
but you must ensure this is done only once.  
I would also say that calling close multiple times is probably a bug; so I'd figure out who/why closes multiple times.



_Code quote:_
```Go
	if !p.closed {
		p.closeChan <- struct{}{}
	}
```
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuR0CaCACHqq_0gXT99:-MuR0CaCACHqq_0gXT9A:b-18pvg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L151)):*
> ```Go
> 		return nil, err
> 	}
> 	const defaultHeartbeatFrequency = 2 * time.Second
> ```

this is probably too aggressive; you might want to have this as a setting perhaps.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuR0KsnA_JJw0G-pu-O:-MuR0KsnA_JJw0G-pu-P:b3pctl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L159)):*
> ```Go
> 		// Buffered channel allows call [...]

2022-02-02 06:21 UTC, gh-casper reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @miretskiy)

___
*[pkg/ccl/streamingccl/settings.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLq9G6AVfT6na3Ddee:-MuqTf8M-GePKZZfmjT9:b-oa6eix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/settings.go#L36)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think so.  Why would we want to keep something we know doesn't work (well)?
</blockquote></details>

Removed this cluster setting. I will have a standalone cleanup PR to clean up previous pg wire client.



_Code quote:_
```Go
UsePartitionedStreamClient
```
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLr7YM5uMmPM2BZjSm:-MuqZiE4CblGoZSGVyAO:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L136)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

See comments on that function; but using testutils is a big red flag.
</blockquote></details>

Removed.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuQylpx9YaypCtArvt3:-MuqUDI33HC0HAbEh5wn:bm7nz1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L116)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This has me worried.  Perhaps we should involve someone from security (or server; perhaps @knz ).
To be clear, I'm not sure what we do here is what we should be doing in the first place.
But, if we absolutely must do what's described in this commend, the fact that we are storing anything
on temporary directory, which, btw, may not be available, or may not even be encrypted(!), just sounds wrong to me.
We could probably store this in memory; but storing it in temp dir.. just sounds wrong.
</blockquote></details>

Thanks for leading the discussion on this. 

Now the operator who starts a stream replication on dest cluster needs to specify ssl authentication for PG URL in inline fashion. I added a validation for this in `stream_ingestion_planning.go`. This inlined URL will be stored as stream address for constructing the stream client. The stream client will use it as the template to create PG URL for every partition.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuQzk2AEFoOnbFvovFp:-MuqVU_a3hEESkiArivy:b-nf6kus) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L130)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm thoroughly confused.  This code runs on a destination cluster; correct?  And from destination cluster we want to connect to source cluster.  Then... what good is it to use destination cluster certs when connecting to source cluster?
</blockquote></details>

Removed. See comment above.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuQyJmq9ame8N12_RKO:-MuqVYDQ9ktaG4SW_82R:b-nf6kus) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L131)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I understand that you were trying to do something where existing utilities are written for tests.
I think it's a red flag for me.  First, if you absolutely must have this, you would need to implement these
helpers outside test util packages.  Secondly, I would kinda ask: why don't we have these helpers already implemented?  Are we trying to do something from production code that we quite frankly shouldn't be doing?
</blockquote></details>

Removed. See comment above.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MtEd6dTtAqZbYRaAcQp-r2-137:-MuqViVO3WMfoFlFK6R2:b714ar2) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L137)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Do we ever connect to or as a tenant? isn't it always host-to-host connections, even if we're streaming a tenant? 
</blockquote></details>

This code was copied from `sqlutils.PGUrlWithOptionalClientCertsE` which adds embedded certs for test cluster. It added the tenant cert for handy purpose. 

Now I've enforced all PG URL for c2c streaming to be sslinline. And the initial inline certificates for source cluster are passed in through operator issuing `RESTORE FROM TENANT STREAM ...`.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuR-Fec4-ixD9iPYTuN:-Mut45rQ4NEPZsbBSuWR:b-ats811) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L262)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Alright, something is off here.  Super magic constant of 10.  On a close chan is just suspicious.  Are we closing things 10 times? Why? What are we writing to that channel and why?  If you want to signal closure, then just close the channel.  Reading from the closed channel is okay.
</blockquote></details>

I think I've over-engineered this. `partitionedStreamSubscription.Close` shouldn't be called multiple times. Now I'm using `close(p.closeChan)` to make it panic when it's called multiple times.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 386 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuR-p6Y2mMmL9d_VEWc:-Mut4k5O9zbYAfGzvQaR:b-by9q0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L386)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Canonical way to do this is to just close(p.CloseChan); 
but you must ensure this is done only once.  
I would also say that calling close multiple times is probably a bug; so I'd figure out who/why closes multiple times.
</blockquote></details>

See other comment.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuR0CaCACHqq_0gXT99:-Muqdqp87ks4cmA69M9b:b-okwaik) ([raw file](https://github.com/cockroachdb/cockroach/blob/524e1e0215cbc32a3cf76691bb7560486aee2777/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L151)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

this is probably too aggressive; you might want to have this as a setting perhaps.
</blockquote></details>

Changed it to a cluster setting.



_Code quote:_
```Go
defaultHeartbeatFrequency
```
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuR0KsnA_JJw0G-pu-O:-Mut4tZwEkvOKkXCffE [...]

2022-02-02 16:51 UTC, miretskiy requested changes
This is getting to be much closer.

> Reviewed 1 of 11 files at r2, 11 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-:-MuvLJPRBitXq0DEtWVt:b-ue5q1e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @gh-casper, and @miretskiy)

___
*[-- commits, line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuuidTd3AQnA78R2fp9):*
Description and release note probably needs to be updated.
___
*[pkg/ccl/streamingccl/errors.go, line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuuiiLyDy1dB7K7nLZG:-MuuiiLyDy1dB7K7nLZH:bz8rq86) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/errors.go#L18)):*
> ```Go
> )
> 
> // StreamStatusErr is error that encapsulate a replication stream's bad status.
> ```

nit: s/bad status// -- the error might represent normal stuff -- like "cutover" or completion.
nit: s/is error/is an error/
___
*[pkg/ccl/streamingccl/errors.go, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuuivOX0vwicLvIYY4B:-MuuivOX0vwicLvIYY4C:b-utyve7) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/errors.go#L26)):*
> ```Go
> // Error implements the error interface.
> func (e StreamStatusErr) Error() string {
> 	return fmt.Sprintf("Replication stream %d is not running, status is %s", e.StreamID, e.StreamStatus.String())
> ```

Are error messages suppose to start w/ lower case? what does lint say on this?
nit: no need to call .String() on e.SteamStatus -- fmt.Sprintf calls that for you if the type implements Stringer interface.
___
*[pkg/ccl/streamingccl/settings.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuujAw5-ihLh4iQcc26:-MuujAw5-ihLh4iQcc27:bceafkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/settings.go#L42)):*
> ```Go
> 	"controls frequency the stream replication destination cluster sends heartbeat "+
> 		"to the source cluster to keep the stream alive",
> 	30*time.Second,
> ```

Do we allow 0? If not, perhaps add NonNegativeDuration check;
Also, pretty sure this does not need to be TenantWritable -- as a matter of fact none of the stream replication 
stuff can be done by tenants .
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuujP_xBqOAyh8SxnCb:-MuujP_xBqOAyh8SxnCc:bhria39) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L28)):*
> ```Go
> 
> type partitionedStreamClient struct {
> 	db             *gosql.DB // DB handle to the source cluster
> ```

nit: perhaps rename it `srcDB`?
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-Muv6LOn2tVyTzZucLr-:-Muv6LOn2tVyTzZucLr0:b-5pt6gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L106)):*
> ```Go
> 	// TODO(casper): add observability for stream protected timestamp
> 	if status.StreamStatus != streampb.StreamReplicationStatus_STREAM_ACTIVE {
> 		return streamingccl.StreamStatusErr{
> ```

I would add NewStreamStatusErr function.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 175 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvEOaGEK1yPcI_-qTl:-MuvEOaGEK1yPcI_-qTm:bj3uzdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L175)):*
> ```Go
> 		defer func() {
> 			close(h.stoppedChan)
> 			err = errors.CombineErrors(err, h.client.Close())
> ```

This is pretty confusing, and probably not necessary.
The first thing I would say is that if the client needs to be stopped, it should just be stopped/closed when 
h.stop() is called.

The second thing that's strange is the use of stopped channel.  I just don't think it's needed.
The stop method simply closes stopCh to signal this go routine that it needs to stop.
The go routine notices it, and exits.
After closing stopCh, all you need to do then is to way for `h.cg.Wait()`.  I don't think you need anything
else. 
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvD_aH4zvP6C14HxpV:-MuvD_aH4zvP6C14HxpW:b7bnyqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L181)):*
> ```Go
> 		// and it has been a while since last time we sent it, or when we need
> 		// to heartbeat to keep the stream alive even if the frontier has no update.
> 		timer := time.NewTimer(h.frequency)
> ```

I would drop h.frequency as a heartbeatSender member.
I would just do 
```
frequency := streamingccl.StreamReplicationStreamLivenessTrackFrequency.Get(&flowCtx.EvalCtx.Settings.SV)
```

See below why...
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 190 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvDjb79HyvmuUf5keL:-MuvDjb79HyvmuUf5keM:b-gmbz1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L190)):*
> ```Go
> 				return nil
> 			case <-timer.C:
> 				timer.Reset(h.frequency)
> ```

I good place to check if the cluster setting changed before resetting the timer:

```
if f := streamingccl.StreamReplicationStreamLivenessTrackFrequency.Get(&flowCtx.EvalCtx.Settings.SV); f != frequency {
   frequency = f
}
```
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvF1Bv8Mr8b8l3-VSp:-MuvF1Bv8Mr8b8l3-VSq:b-7239z0) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L192)):*
> ```Go
> 				timer.Reset(h.frequency)
> 			case frontier := <-h.frontierUpdates:
> 				h.frontier = frontier
> ```

we probably want to forward frontier?
h.frontier.Forward(frontier) -- I guess to be defensive in the case we send earlier timestamp later?
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 197 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvFEEm1LehS-HCPj7W:-MuvFEEm1LehS-HCPj7X:bsicrs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L197)):*
> ```Go
> 			var se streamingccl.StreamStatusErr
> 			if err != nil && errors.As(err, &se) &&
> 				se.StreamStatus == streampb.StreamReplicationStatus_UNKNOWN_STREAM_STATUS_RETRY {
> ```

Probably want to log.Warning here, and probably want to limit the rate of these log messages with something like
log.Every.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 274 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvGcNNELUNUkJBH0Za:-MuvGcNNELUNUkJBH0Zb:b-2zv47n) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L274)):*
> ```Go
> 			newResolvedTS := sf.frontier.Frontier()
> 			// Send the frontier update in the heartbeat to the source cluster.
> 			sf.heartbeatSender.frontierUpdates <- newResolvedTS
> ```

alright, I can  [...]

2022-02-08 09:17 UTC, gh-casper reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[-- commits, line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuuidTd3AQnA78R2fp9):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Description and release note probably needs to be updated.
</blockquote></details>

Done
___
*[pkg/ccl/streamingccl/errors.go, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuuivOX0vwicLvIYY4B:-MvNG2Jb9483V2f4N5sm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/errors.go#L26)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Are error messages suppose to start w/ lower case? what does lint say on this?
nit: no need to call .String() on e.SteamStatus -- fmt.Sprintf calls that for you if the type implements Stringer interface.
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/settings.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuujAw5-ihLh4iQcc26:-MvNGyAU3AY5DNm1DIZS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/settings.go#L42)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we allow 0? If not, perhaps add NonNegativeDuration check;
Also, pretty sure this does not need to be TenantWritable -- as a matter of fact none of the stream replication 
stuff can be done by tenants .
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-Muv6LOn2tVyTzZucLr-:-MvNI1oN42yRMUXiTcbO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go#L106)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would add NewStreamStatusErr function.
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 175 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvEOaGEK1yPcI_-qTl:-MvNa3cUEtNIIDUQdcXA:b-by9q0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L175)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This is pretty confusing, and probably not necessary.
The first thing I would say is that if the client needs to be stopped, it should just be stopped/closed when 
h.stop() is called.

The second thing that's strange is the use of stopped channel.  I just don't think it's needed.
The stop method simply closes stopCh to signal this go routine that it needs to stop.
The go routine notices it, and exits.
After closing stopCh, all you need to do then is to way for `h.cg.Wait()`.  I don't think you need anything
else. 
</blockquote></details>

See other comment.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvD_aH4zvP6C14HxpV:-MvNKhYBBX8Zyp0jsJIo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L181)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would drop h.frequency as a heartbeatSender member.
I would just do 
```
frequency := streamingccl.StreamReplicationStreamLivenessTrackFrequency.Get(&flowCtx.EvalCtx.Settings.SV)
```

See below why...
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 190 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvDjb79HyvmuUf5keL:-MvNKiT21AkhSrw05aEq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L190)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I good place to check if the cluster setting changed before resetting the timer:

```
if f := streamingccl.StreamReplicationStreamLivenessTrackFrequency.Get(&flowCtx.EvalCtx.Settings.SV); f != frequency {
   frequency = f
}
```
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvF1Bv8Mr8b8l3-VSp:-MvNO7df9zvd_kWWkWhQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L192)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we probably want to forward frontier?
h.frontier.Forward(frontier) -- I guess to be defensive in the case we send earlier timestamp later?
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 197 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvFEEm1LehS-HCPj7W:-MvNNvgoDBj52gIUxmJz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L197)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Probably want to log.Warning here, and probably want to limit the rate of these log messages with something like
log.Every.
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 274 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvGcNNELUNUkJBH0Za:-MvN_wEU5KTAo_u3b2Mf:blwpkvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L274)):*
> errCh
Interesting. This is one of the moments I really learn Go concurrency.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 295 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvA-SC03Dhi2fpRVEx:-MvNOTCCBjnsuRvUWtkP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L295)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Take a look at changefeed data processor (or backup one).  The pattern we have there is
ConsumerClosed calls "close()" helper, and in that helper we check for:
```
if InternalClose() {
    // try to stop heartbeat
}
```
Basically, this ensures that your close logic runs only once.
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLtFag080n3LnG7Pbl:-MvNWL1LDqJHmfHcXxnr:b1eukem) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L45)):*
> NewStreamClient
I think here it's easy to tell the error is not shadowed since client is only used in two lines below.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-Muv8qr68GzLv-RB3zEm:-MvNV4AfEHvsNA_IK6XP: [...]

2022-02-08 13:22 UTC, miretskiy requested changes
> Reviewed 3 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @gh-casper, and @miretskiy)

___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOSsVUCAKVgP8NmI0Y:-MvOSsVUCAKVgP8NmI0Z:by4j6fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L182)):*
> ```Go
> 		// and it has been a while since last time we sent it, or when we need
> 		// to heartbeat to keep the stream alive even if the frontier has no update.
> 		h.frequency = streamingccl.StreamReplicationStreamLivenessTrackFrequency.
> ```

does frequency need to be a member of heartbeatSender?
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 221 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOTBWS0L1uKMGZ1ywt:-MvOTBWS0L1uKMGZ1ywu:b-jyxfc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L221)):*
> ```Go
> 		return true, err
> 	default:
> 		return false, nil
> ```

not clear why we need this; but what happens if this is called multiple times?
you'll return false, nil the second time around, even if you were stopped before...
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOTb3b3MpMWpJiO7R2:-MvOTb3b3MpMWpJiO7R3:bd5vp6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L252)):*
> ```Go
> 		// stop the processor.
> 		if stopped, err := sf.heartbeatSender.isStopped(); stopped {
> 			sf.MoveToDraining(nil /* err */)
> ```

why are we moving to draining with nil error?
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOTwo71Xgky0OyQPWf:-MvOTwo71Xgky0OyQPWg:b2u630v) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L264)):*
> ```Go
> 		}
> 		if row == nil {
> 			sf.MoveToDraining(nil /* err */)
> ```

curious why nil errors here... 
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLtFag080n3LnG7Pbl:-MvOUANV5Pr67iA_YIe1:b-cfy2ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L45)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

> NewStreamClient
I think here it's easy to tell the error is not shadowed since client is only used in two lines below.
</blockquote></details>

I disagree.  This function will get more complex over time.  It might be easy to tell now.
Where as with my suggestion, it is always easy to tell.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go, line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOUSv50WzB4PuB1ULU:-MvOUSv50WzB4PuB1ULV:b-jnl0h5) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go#L104)):*
> ```Go
> 
> 		// Convert this URL into sslinline mode.
> 		*url, err = sqlutils.AddInlineSecurityCredentials(*url)
> ```

we cannot use testing library in production code.
___
*[pkg/testutils/sqlutils/pg_url.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvK_VD5aYY97t-86bp:-MvOUfd83qUzX2j2xcfU:b-j7qk9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/testutils/sqlutils/pg_url.go#L49)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Very nice.
___
*[pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go, line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvL6h93q1q7dXeDR11:-MvOUm-U5L0m0k1VluDx:b-haevfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go#L86)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

This is set very low on purpose to make the test to execute faster (we don't want to wait for flush interval)
</blockquote></details>

surely 10ms is fast enough.  Anyways, setting things that low sometimes bites you since this can cause busy loops.
But... okay.


<!-- Sent from Reviewable.io -->

2022-02-09 03:11 UTC, gh-casper reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOSsVUCAKVgP8NmI0Y:-MvPCGhP-zMqP9pnxOaj:b-4botle) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L182)):*
> heartbeatSender
Removed.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 221 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOTBWS0L1uKMGZ1ywt:-MvRRAqL8NiqaGTkZuV_:b-7t2c6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L221)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

not clear why we need this; but what happens if this is called multiple times?
you'll return false, nil the second time around, even if you were stopped before...
</blockquote></details>

I changed the code in following way:

introduced a channel `stoppedChan` work with `cg`. Closing it when the heartbeatThread stopped and error will be retrieved through `cg.Wait()`. Their benefit is we can read them multiple times. I could also use `errChan` to make it work but we need the help of `cg` since errChan can only be read its error for once. Introducing `stoppedChan` makes the code look cleaner.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOTb3b3MpMWpJiO7R2:-MvQZqohCMhs7HBjsWem:boz4m65) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L252)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why are we moving to draining with nil error?
</blockquote></details>

This was to be consistent with the code below: returning meta which contains error but `MoveToDraining` with nil error. However, now it seems more reasonable to `MoveToDraining` with err  and return a `DrainHelper()` which will add the error into the returned meta.


`
if meta.Err != nil {
	sf.MoveToDraining(nil /* err */)
}
return nil, meta
`



_Code quote:_
```Go
sf.MoveToDraining(nil /* err */)
```
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOTwo71Xgky0OyQPWf:-MvQVi69CfQADNPSTbl8:b26trqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L264)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

curious why nil errors here... 
</blockquote></details>

Because `meta` is nil now so there is no error happening here, the processor drains and exits normally.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuLtFag080n3LnG7Pbl:-MvQbG--86xgbJQIaOjJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f3986a4aa1a85e9330e2fd27957c32ce9cd7f4/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L45)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I disagree.  This function will get more complex over time.  It might be easy to tell now.
Where as with my suggestion, it is always easy to tell.
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go, line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOUSv50WzB4PuB1ULU:-MvRSYSECtod4t8oMdz8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go#L104)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we cannot use testing library in production code.
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go, line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvL6h93q1q7dXeDR11:-MvPF5vJERa9r3AD7JIu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go#L86)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

surely 10ms is fast enough.  Anyways, setting things that low sometimes bites you since this can cause busy loops.
But... okay.
</blockquote></details>

Done.
___
*[pkg/testutils/sqlutils/pg_url.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MuvK_VD5aYY97t-86bp:-MvQdocY4bNtq7QT8LB6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b4df74ed943b35db582890d0598748e024e7ae/pkg/testutils/sqlutils/pg_url.go#L49)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Very nice.
</blockquote></details>

Done.



_Code quote:_
```Go
AddInlineSecurityCredentials
```


<!-- Sent from Reviewable.io -->

2022-02-09 13:12 UTC, miretskiy requested changes
> Reviewed 1 of 11 files at r2, 1 of 17 files at r3, 1 of 10 files at r4, 3 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @gh-casper, and @miretskiy)

___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 221 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOTBWS0L1uKMGZ1ywt:-MvTY0eY9xj81y2Wq9XV:b-29hj80) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L221)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

I changed the code in following way:

introduced a channel `stoppedChan` work with `cg`. Closing it when the heartbeatThread stopped and error will be retrieved through `cg.Wait()`. Their benefit is we can read them multiple times. I could also use `errChan` to make it work but we need the help of `cg` since errChan can only be read its error for once. Introducing `stoppedChan` makes the code look cleaner.
</blockquote></details>

Okay.  I still think that this particular method -- it should definitely be called once.  When we shutdown or move to draining.  As such, you can probably just 
```
close(h.stopChan)
return h.cg.Wait()
```
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 245 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvTZHgr4Q5CF-kM-De6:-MvTZHgr4Q5CF-kM-De7:bqoah0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2464ccfb37fce8f2368e47391d4716bd85007a/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L245)):*
> ```Go
> 		select {
> 		case <-sf.heartbeatSender.stoppedChan:
> 			sf.MoveToDraining(sf.heartbeatSender.cg.Wait())
> ```

So, most of the time you will be blocked on sf.input.Next() below; Plus you're checking if heartbeat stopped below.
I think section can be removed.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 295 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvT_fGh0cNhr-pjoGm4:-MvT_fGi8vBB_SlkIvKU:b-4m1618) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2464ccfb37fce8f2368e47391d4716bd85007a/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L295)):*
> ```Go
> 				}
> 			case <-sf.heartbeatSender.stoppedChan:
> 				sf.MoveToDraining(sf.heartbeatSender.cg.Wait())
> ```

I think it would be nice to introduce an Err() method to heartBeatSender so that we don't access internal context groupl.
___
*[pkg/ccl/streamingccl/streamproducer/event_stream.go, line 391 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvTa2xn5YMrPRWtvqH_:-MvTa2xn5YMrPRWtvqHa:b-ohy4im) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2464ccfb37fce8f2368e47391d4716bd85007a/pkg/ccl/streamingccl/streamproducer/event_stream.go#L391)):*
> ```Go
> func setConfigDefaults(cfg *streampb.StreamPartitionSpec_ExecutionConfig) {
> 	const defaultInitialScanParallelism = 16
> 	const defaultMinCheckpointFrequency = 3 * time.Second
> ```

we almost certainly don't want to have default so low.
___
*[pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go, line 139 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvTbBmEBUudNDXNWTWL:-MvTbBmEBUudNDXNWTWM:bd0z8dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2464ccfb37fce8f2368e47391d4716bd85007a/pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go#L139)):*
> ```Go
> 	// Cut over the ingestion job and the job will stop eventually.
> 	destSysSQL.Exec(t, `SELECT crdb_internal.complete_stream_ingestion_job($1, $2)`, ingestionJobID, cutoverTime)
> 	jobutils.WaitForJob(t, destSysSQL, jobspb.JobID(ingestionJobID))
> ```

we probably want to check source cluster job was shutdown too?


<!-- Sent from Reviewable.io -->

2022-02-09 23:24 UTC, gh-casper reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 221 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvOTBWS0L1uKMGZ1ywt:-MvVj0Gk6cMsz7yonbWc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda353239515d74a77057bcda23fffd893502ecf/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L221)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Okay.  I still think that this particular method -- it should definitely be called once.  When we shutdown or move to draining.  As such, you can probably just 
```
close(h.stopChan)
return h.cg.Wait()
```
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 245 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvTZHgr4Q5CF-kM-De6:-MvVjE5S5e7wWnFdUMHT:b-y55j4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2464ccfb37fce8f2368e47391d4716bd85007a/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L245)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

So, most of the time you will be blocked on sf.input.Next() below; Plus you're checking if heartbeat stopped below.
I think section can be removed.
</blockquote></details>

In current code, we only check if heartbeat stopped when frontier is changed.  Now I removed this section and checked if heartbeat stopped in any case.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go, line 295 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvT_fGh0cNhr-pjoGm4:-MvUmpjC1AeKMxne8roL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2464ccfb37fce8f2368e47391d4716bd85007a/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L295)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think it would be nice to introduce an Err() method to heartBeatSender so that we don't access internal context groupl.
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamproducer/event_stream.go, line 391 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvTa2xn5YMrPRWtvqH_:-MvUt-Wa86oAeJVUKrlw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2464ccfb37fce8f2368e47391d4716bd85007a/pkg/ccl/streamingccl/streamproducer/event_stream.go#L391)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we almost certainly don't want to have default so low.
</blockquote></details>

Done.



_Code quote:_
```Go
defaultMinCheckpointFrequency
```
___
*[pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go, line 139 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74753#-MvTbBmEBUudNDXNWTWL:-MvVj2uQ3LAkJWw5xIVb:b-q24biz) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2464ccfb37fce8f2368e47391d4716bd85007a/pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go#L139)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we probably want to check source cluster job was shutdown too?
</blockquote></details>

Done. Will make producer job exit normally in curover scenario in a later PR.


<!-- Sent from Reviewable.io -->

2022-02-09 23:29 UTC, miretskiy approved these changes
> Reviewed 2 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)



<!-- Sent from Reviewable.io -->

2022-02-23 03:44 UTC, gh-casper commented
bors r+

2022-02-23 05:37 UTC, merged