sql: don't create a tracing span for every pgwire cmd
cockroachdb/cockroach pull request #74766
Opened 2022-01-12 21:51 UTC by andreimatei

Before this patch, processing each pgwire cmd was getting its own span
(when tracing is enabled). This span was not nice because it was
outliving its parent - something that's technically permitted, but not
generally encouraged.

Besides being funly, these spans are too costly for too little
benefit. Generally, executing a query takes a few commands:
bind,describe,exec,sync. If the query is executed as an implicit txn,
the "exec" command is generally twice (once superficially in the
"no-txn" state and once in the "open" state). For simple queries, these
spans end up being about half of the total spans created for the query.
I've never looked at a span for anything other than the "exec", and
there only at the one in the "open" state. So this patch gets rid of
creating spans mechanically for every pgwire command. Instead, we create
spans only for preparing statements, and for executing a query in the
"open" state.

Release note: None

2022-01-12 21:51 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74766)
<!-- Reviewable:end -->

2022-01-13 15:44 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @rafiss)

___
*[pkg/sql/conn_executor.go, line 1706 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74766#-MtJ60hq77JCMY0ViLIN:-MtJ60hq77JCMY0ViLIO:b-qg4nbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/49527abe6c6a2f342edb3a39e6e2e59ced15c810/pkg/sql/conn_executor.go#L1706)):*
> ```Go
> 	}
> 
> 	// Ensure that every statement has a tracing span set up.
> ```

i do think it might be useful to still make a span for `Bind` -- sometimes that needs to use a txn to resolve the arguments (e.g. binding a user-defined type https://github.com/cockroachdb/cockroach/commit/01ca1e53e2c84049abcf0f3d3acefa4bbbdb0db9)


<!-- Sent from Reviewable.io -->

2022-01-13 18:34 UTC, andreimatei reviewed
I've added a new span for auto-commits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74766#-:-MtJi2Z7EWy8RQg_3T66:b6ql3e8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/conn_executor.go, line 1706 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74766#-MtJ60hq77JCMY0ViLIN:-MtJZyiY8SG-JoRhz2bV:bpg7nrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/49527abe6c6a2f342edb3a39e6e2e59ced15c810/pkg/sql/conn_executor.go#L1706)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i do think it might be useful to still make a span for `Bind` -- sometimes that needs to use a txn to resolve the arguments (e.g. binding a user-defined type https://github.com/cockroachdb/cockroach/commit/01ca1e53e2c84049abcf0f3d3acefa4bbbdb0db9)
</blockquote></details>

well is the fact that "it uses a transaction" reason enough for it to get a span? That transaction will rarely do much, right? And when it does do things, those operations will get their own spans. Do you feel like it's important for the Bind to be explicitly represented as a span in the trace?
This PR came to be both because of upcoming performance cost once I make the spans actually be created (cause at the moment they generally aren't, btw, unless you explicitly turn on some tracing), and also because these spans are generally uninteresting and noisy.

But if you insist, I'll keep it.

Btw, as a rant, I think the need for a transaction in order to resolve catalog items is artificial and unfortunate. If things are as I remember them, I think the respective code should only need a timestamp, not a full transaction - like, the only thing conceptually needed for resolving things I think is the timestamp for which you're resolving it. But I know that a bunch of preparing code has grown to be tied to a txn.


<!-- Sent from Reviewable.io -->

2022-01-13 19:14 UTC, ajwerner commented
> the only thing conceptually needed for resolving things I think is the timestamp for which you're resolving it. But I know that a bunch of preparing code has grown to be tied to a txn.

This gets irritatingly complex tbh. There's two use cases for the transaction, one is about getting UDTs and the other is casts of OIDs. I think the right answer is indeed to just pick a timestamp and then to record the set of descriptor, version pairs that were used by the bind, then, during exec, go lease the relevant descriptors and make sure the versions match. This is precisely the protocol we use to validate that a previously prepared plan is still valid. It just takes some work. The language around transactions only comes up because our APIs are roundabout.

2022-01-22 21:06 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r1, 1 of 9 files at r5, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74766#-:-Mu2bG5l1WYJBgQUoyYc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @rafiss)

___
*[pkg/sql/conn_executor_exec.go, line 265 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74766#-Mu2azg8Ah8nJX9Zlavv:-Mu2azg8Ah8nJX9Zlavw:b-x0epsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3506e4ec71d8dc03cbde813a0767f0d0e1a2d249/pkg/sql/conn_executor_exec.go#L265)):*
> ```Go
> 	ctx, sp := tracing.EnsureChildSpan(ctx, ex.server.cfg.AmbientCtx.Tracer, "sql query")
> 	// TODO(andrei): Consider adding the placeholders as tags too.
> 	sp.SetTag("statement", attribute.StringValue(parserStmt.SQL))
> ```

[nit] should we maybe limit the length (for ridiculous queries)?


<!-- Sent from Reviewable.io -->

2022-01-26 23:30 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74766)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rafiss)

___
*[pkg/sql/conn_executor_exec.go, line 265 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/74766#-Mu2azg8Ah8nJX9Zlavv:-MuNi3x2DowdrZlxbmti:b1w4xz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3506e4ec71d8dc03cbde813a0767f0d0e1a2d249/pkg/sql/conn_executor_exec.go#L265)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] should we maybe limit the length (for ridiculous queries)?
</blockquote></details>

I think I'd rather have everybody who's presenting this info in charge of dealing gracefully with large tags... Perhaps Jaeger is not graceful, I don't know, but even if it isn't I'd rather truncate when we generate the JSON. Basically, I'd rather push the truncation elsewhere.


<!-- Sent from Reviewable.io -->

2022-01-28 15:10 UTC, andreimatei reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74766#-:-MuWE6dM7ILOx72ih9wa:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rafiss)



<!-- Sent from Reviewable.io -->

2022-01-29 13:38 UTC, andreimatei commented
bors r+

2022-01-29 17:43 UTC, andreimatei commented
bors r+

2022-01-29 18:56 UTC, merged