wip2
cockroachdb/cockroach pull request #74842
Opened 2022-01-14 10:20 UTC by knz

2022-01-14 10:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74842)
<!-- Reviewable:end -->

2022-01-14 10:38 UTC, knz commented
Comment from @JeffSwenson  [here](https://github.com/cockroachdb/cockroach/pull/74301#pullrequestreview-852337243):

> It is unfortunate that SCRAM uses more round trips than clear text authorization. For collocated clients this should only add a few ms, but it will be significant for clients that are far from the sql node.

Yes, we are cognizant of this cost, and we knew about when we started this discussion [all the way back](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20200720_modern_passwords.md). We're ok with this given that we're pushing our customers to co-locate their SQL clients in the same cloud / network.

2022-01-14 19:44 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74842)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @JeffSwenson, and @knz)

___
*[pkg/sql/pgwire/auth_methods.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74842#-MtP5ik13E5BOc6pUCes:-MtP5ik13E5BOc6pUCet:b-vfvwgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c978b0fe063b1050840b6ceb343e79ec4fcb351/pkg/sql/pgwire/auth_methods.go#L65)):*
> ```Go
> 	RegisterAuthMethod("scram-sha-256", authScram, hba.ConnAny,
> 		chainOptions(
> 			requireClusterVersion(clusterversion.SCRAMAuthentication),
> ```

i don't follow why we need the cluster version check here. could the cluster version gate be applied at the time of the `SET CLUSTER SETTING server.host_based_authentication.configuration` statement? having the gate apply at write-time seems safest, and i think if we do it there we already have access to the current clusterversion


<!-- Sent from Reviewable.io -->

2022-01-14 20:01 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74842)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @JeffSwenson, and @rafiss)

___
*[pkg/sql/pgwire/auth_methods.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74842#-MtP5ik13E5BOc6pUCes:-MtPA7ak5Lir122Ura9r:bcfiyah) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c978b0fe063b1050840b6ceb343e79ec4fcb351/pkg/sql/pgwire/auth_methods.go#L65)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't follow why we need the cluster version check here. could the cluster version gate be applied at the time of the `SET CLUSTER SETTING server.host_based_authentication.configuration` statement? having the gate apply at write-time seems safest, and i think if we do it there we already have access to the current clusterversion
</blockquote></details>

This is exactly what is happening! This "chainOptions" argument to `RegisterAuthMethods` places the function into the `hbaCheckHBAEntries` map, which is used to validate the value before it's written, in ` checkHBASyntaxBeforeUpdatingSetting()`. That function is the pre-write validation function passed in the setting constructor.


<!-- Sent from Reviewable.io -->

2022-01-19 13:09 UTC, knz commented
@rafiss wondering if you'd like anything else to happen here?

2022-01-19 17:23 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74842)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @JeffSwenson, and @knz)

___
*[pkg/sql/pgwire/auth_methods.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74842#-MtP5ik13E5BOc6pUCes:-MtnLx0bDm9Cbc9FBhZ-:b-ap3zou) ([raw file](https://github.com/cockroachdb/cockroach/blob/7474e9a0432605cff3c3e83816b3558ebc33632e/pkg/sql/pgwire/auth_methods.go#L65)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is exactly what is happening! This "chainOptions" argument to `RegisterAuthMethods` places the function into the `hbaCheckHBAEntries` map, which is used to validate the value before it's written, in ` checkHBASyntaxBeforeUpdatingSetting()`. That function is the pre-write validation function passed in the setting constructor.
</blockquote></details>

ah ok, thanks for explaining. in that case, a test that shows this would be nice

we can bring back a mixed version logic test configuration (which is straightforward; see https://github.com/cockroachdb/cockroach/commit/c3a154ba0273341a8575558d5e4e1d72c55b1d29) then add an `onlyif local-mixed-21.2-22.1` logic test somewhere


<!-- Sent from Reviewable.io -->

2022-01-20 12:18 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74842)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @JeffSwenson, and @rafiss)

___
*[pkg/sql/pgwire/auth_methods.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74842#-MtP5ik13E5BOc6pUCes:-MtrNAMM88B-veTKN9iV:b-9iet8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/7474e9a0432605cff3c3e83816b3558ebc33632e/pkg/sql/pgwire/auth_methods.go#L65)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah ok, thanks for explaining. in that case, a test that shows this would be nice

we can bring back a mixed version logic test configuration (which is straightforward; see https://github.com/cockroachdb/cockroach/commit/c3a154ba0273341a8575558d5e4e1d72c55b1d29) then add an `onlyif local-mixed-21.2-22.1` logic test somewhere
</blockquote></details>

Amazing. Thank you so much for teaching me this.
Done.


<!-- Sent from Reviewable.io -->

2022-01-20 16:17 UTC, knz commented
RFAL

2022-01-20 16:31 UTC, JeffSwenson approved these changes
sqlproxy changes LGTM

> Reviewed 4 of 11 files at r1, 4 of 9 files at r3, 2 of 7 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74842#-:-MtsK4vHC2NbfrPR2lNW:b-a88yic)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @rafiss)



<!-- Sent from Reviewable.io -->

2022-01-20 22:28 UTC, rafiss approved these changes
lgtm! 

> Reviewed 4 of 11 files at r1, 4 of 9 files at r3, 2 of 7 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74842#-:-Mttagst5fiOxz9Ubz9g:b-nzoors)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @rafiss)



<!-- Sent from Reviewable.io -->

2022-01-20 23:47 UTC, knz commented
NB: I'm holding off merging this PR until all the PRs in the sequence are ready (otherwise, the entire chain will be auto-closed by github).

2022-01-21 09:12 UTC, merged