wip10
cockroachdb/cockroach pull request #74850
Opened 2022-01-14 10:25 UTC by knz

2022-01-14 10:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/74850)
<!-- Reviewable:end -->

2022-01-14 19:22 UTC, knz commented
@ajwerner can you double check what I did to sql/users.go and see if that follows the idea you had

2022-01-14 19:52 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @knz, and @rafiss)

___
*[pkg/sql/user.go, line 681 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-MtP7maE50Afaro1T6Do:-MtP7maE50Afaro1T6Dp:b-29f3js) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6c4ce98fbf0ed6c8d4d9f7ea3dbd6aad2754956/pkg/sql/user.go#L681)):*
> ```Go
> 		return DescsTxn(
> 			ctx, execCfg,
> 			func(ctx context.Context, txn *kv.Txn, d *descs.Collection) error {
> ```

I quarrel only with this choice of wrapping, and that is a nit. Logically looks fine to me. 

The below wrapping will lose you one level of indentation 

```go
		return DescsTxn(ctx, execCfg, func(
			ctx context.Context, txn *kv.Txn, d *descs.Collection,
		) error {
```



_Code quote:_
```Go
		return DescsTxn(
			ctx, execCfg,
			func(ctx context.Context, txn *kv.Txn, d *descs.Collection) error {
```


<!-- Sent from Reviewable.io -->

2022-01-14 20:48 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @rafiss)

___
*[pkg/sql/user.go, line 681 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-MtP7maE50Afaro1T6Do:-MtPKIvG1-mMYSrDFM69:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6c4ce98fbf0ed6c8d4d9f7ea3dbd6aad2754956/pkg/sql/user.go#L681)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I quarrel only with this choice of wrapping, and that is a nit. Logically looks fine to me. 

The below wrapping will lose you one level of indentation 

```go
		return DescsTxn(ctx, execCfg, func(
			ctx context.Context, txn *kv.Txn, d *descs.Collection,
		) error {
```
</blockquote></details>

Thanks, done.


<!-- Sent from Reviewable.io -->

2022-01-17 17:06 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @knz)

___
*[-- commits, line 11 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-MtczqxB7EDjEUF5tyJu):*
what's the plan for migrating passwords for users that are used very infrequently? i.e., if a user goes years without logging in? it seems we can't do a long-running migration during the cluster upgrade, since we also want the auto-upgrade decision to respect the cluster setting
___
*[pkg/security/password.go, line 852 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-Mtcw_h5AMs1EwDCvfon:-Mtcw_hC-BKgZCmjvEpo:bi2o6cu) ([raw file](https://github.com/cockroachdb/cockroach/blob/14a69f44368710c7f373afa6b8a826bac2e79ebe/pkg/security/password.go#L852)):*
> ```Go
> 		// if the new cost is high and the operation takes a long time, so
> 		// the operator knows what's up.
> 		log.Infof(ctx, "hash conversion: computing a SCRAM hash with iteration count %d (from bcrypt cost %d)", scramIterCount, bcryptCost)
> ```

should this be in the USER_ADMIN logging channel since it's a  "Change to authentication credentials"?
___
*[pkg/security/password.go, line 864 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-MtcxbeT3dOXg908MBJK:-MtcxbeT3dOXg908MBJL:b-wldez6) ([raw file](https://github.com/cockroachdb/cockroach/blob/14a69f44368710c7f373afa6b8a826bac2e79ebe/pkg/security/password.go#L864)):*
> ```Go
> 	// - it checks that we're able to re-parse what we just generated,
> 	//   which is a safety mechanism to ensure the result is valid.
> 	// - it converts the raw bytes to the PasswordHash interface, which
> ```

it doesn't seem like `PasswordHash` is used in the return types
___
*[pkg/sql/user.go, line 678 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-Mtcz2OjCuZ9JaiGR0aT:-Mtcz2OjCuZ9JaiGR0aU:bj77auj) ([raw file](https://github.com/cockroachdb/cockroach/blob/14a69f44368710c7f373afa6b8a826bac2e79ebe/pkg/sql/user.go#L678)):*
> ```Go
> 	runFn := getUserInfoRunFn(execCfg, username, "set-hash-timeout")
> 
> 	return runFn(ctx, func(ctx context.Context) error {
> ```

does this mean that the updateuserPasswordHash step will happen with a separate timeout than the authentication flow? doesn't that mean that a login can now take twice as long as the configured timeout? should updating the hash be done in a background thread?


<!-- Sent from Reviewable.io -->

2022-01-17 17:11 UTC, knz commented
> what's the plan for migrating passwords for users that are used very infrequently? i.e., if a user goes years without logging in? it seems we can't do a long-running migration during the cluster upgrade

We can't do an automatic background migration because we need the cleartext password to upgrade. There's no way to do this automatically without a successful cleartext login.

Our recommendation in docs will be that operators who care about migrating everyone need to re-issue credentials to everyone.

2022-01-19 14:14 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, @knz, and @rafiss)

___
*[pkg/security/password.go, line 852 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-Mtcw_h5AMs1EwDCvfon:-MtmfFKx4wL9zfTIYtZ0:b-319nzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/14a69f44368710c7f373afa6b8a826bac2e79ebe/pkg/security/password.go#L852)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this be in the USER_ADMIN logging channel since it's a  "Change to authentication credentials"?
</blockquote></details>

I was thinking this was just a debugging message, for when things could be unusually slow. The final event is logged to USER_ADMIN by the function in the `sql` package, only after the UPDATE has completed successfully.
Added an explanatory comment. What do you think?
___
*[pkg/security/password.go, line 864 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-MtcxbeT3dOXg908MBJK:-MtmfhZQ6NbKizKF0H-H:b-40i2sn) ([raw file](https://github.com/cockroachdb/cockroach/blob/14a69f44368710c7f373afa6b8a826bac2e79ebe/pkg/security/password.go#L864)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it doesn't seem like `PasswordHash` is used in the return types
</blockquote></details>

Good call. This comment was stale. Fixed.


<!-- Sent from Reviewable.io -->

2022-01-19 18:31 UTC, rafiss requested changes
> Our recommendation in docs will be that operators who care about migrating everyone need to re-issue credentials to everyone.

sounds good

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-:-MtnauCs73GiEQFddFlF:bh6apub)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, @knz, and @rafiss)

___
*[pkg/security/password.go, line 852 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-Mtcw_h5AMs1EwDCvfon:-MtnaaOcE7T8DIelqe7y:b9pna21) ([raw file](https://github.com/cockroachdb/cockroach/blob/14a69f44368710c7f373afa6b8a826bac2e79ebe/pkg/security/password.go#L852)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I was thinking this was just a debugging message, for when things could be unusually slow. The final event is logged to USER_ADMIN by the function in the `sql` package, only after the UPDATE has completed successfully.
Added an explanatory comment. What do you think?
</blockquote></details>

got it, sounds great
___
*[pkg/sql/user.go, line 678 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-Mtcz2OjCuZ9JaiGR0aT:-Mtnao8L3npxuE8jWPSo:b-tyqhcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/14a69f44368710c7f373afa6b8a826bac2e79ebe/pkg/sql/user.go#L678)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this mean that the updateuserPasswordHash step will happen with a separate timeout than the authentication flow? doesn't that mean that a login can now take twice as long as the configured timeout? should updating the hash be done in a background thread?
</blockquote></details>

ping on this question


<!-- Sent from Reviewable.io -->

2022-01-19 18:39 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, @knz, and @rafiss)

___
*[pkg/sql/user.go, line 678 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-Mtcz2OjCuZ9JaiGR0aT:-MtnbqRU12FKi8s5l4yL:bd55utz) ([raw file](https://github.com/cockroachdb/cockroach/blob/14a69f44368710c7f373afa6b8a826bac2e79ebe/pkg/sql/user.go#L678)):*
oh I hadn't seen this.

Yes, the current implementation has this property, which is also highlighted in the release note:
>   This conversion will increase the latency of that initial login by a
>  factor of ~2x, but it will be reduced again after the conversion
>  completes.
>  When login latency is a concern, operators are invited to perform the
>  password conversion ahead of time, by computing new SCRAM hashes for
>  the clients via ALTER USER/ROLE WITH PASSWORD.


We could do this in a "background thread", although there are two separate concerns to solve:
- we should avoid storms of concurrent goroutines. If we start doing asynchronous stuff for this, we'll need a queue / semaphore.
- this then also asks complicated questions: what to do if the same username starts multiple sessions concurrently? With the current code, most will pick up the change (thx to table version bump) after the first one has logged in and the UPDATE statement won't even be run. If we spawn the work asynchronously, the detection will not be immediate and we might end up running many UPDATEs concurrently.
(NB: this last point is not a correctness issue, thanks to the WHERE clause. We're simply talking about load here.

How do you feel about this? Do you think that a one-off latency bump, with a workaround to issue ALTER ROLE WITH PASSWORD out-of-band to avoid it, is unacceptable?


<!-- Sent from Reviewable.io -->

2022-01-19 18:49 UTC, rafiss approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, @knz, and @rafiss)

___
*[pkg/sql/user.go, line 678 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74850#-Mtcz2OjCuZ9JaiGR0aT:-Mtnf1EJD9IVSq-io8aE:bctvt71) ([raw file](https://github.com/cockroachdb/cockroach/blob/14a69f44368710c7f373afa6b8a826bac2e79ebe/pkg/sql/user.go#L678)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

oh I hadn't seen this.

Yes, the current implementation has this property, which is also highlighted in the release note:
>   This conversion will increase the latency of that initial login by a
>  factor of ~2x, but it will be reduced again after the conversion
>  completes.
>  When login latency is a concern, operators are invited to perform the
>  password conversion ahead of time, by computing new SCRAM hashes for
>  the clients via ALTER USER/ROLE WITH PASSWORD.


We could do this in a "background thread", although there are two separate concerns to solve:
- we should avoid storms of concurrent goroutines. If we start doing asynchronous stuff for this, we'll need a queue / semaphore.
- this then also asks complicated questions: what to do if the same username starts multiple sessions concurrently? With the current code, most will pick up the change (thx to table version bump) after the first one has logged in and the UPDATE statement won't even be run. If we spawn the work asynchronously, the detection will not be immediate and we might end up running many UPDATEs concurrently.
(NB: this last point is not a correctness issue, thanks to the WHERE clause. We're simply talking about load here.

How do you feel about this? Do you think that a one-off latency bump, with a workaround to issue ALTER ROLE WITH PASSWORD out-of-band to avoid it, is unacceptable?

</blockquote></details>

good point on the one-off latency bump -- with that i think the 2x increase sounds fine


<!-- Sent from Reviewable.io -->

2022-01-20 16:17 UTC, knz commented
NB: I'm holding off merging this PR until all the PRs in the sequence are ready (otherwise, the entire chain will be auto-closed by github).

2022-01-21 09:12 UTC, merged