cli: improve `debug send-kv-batch`
cockroachdb/cockroach pull request #75519
Opened 2022-01-25 21:47 UTC by knz

This extends the `debug send-kv-batch` CLI utility to optionally
collect and print a trace of the remote processing.

The new command-line flags are as follows:
- `--verbose`: set the verbose flag on the span.
- `--print-recording`: show the pretty-printed recording at the end.
  Implies `--verbose=true`.
- `--keep-collected-spans`: whether to keep the collected spans on the
  response object. By default they are elided because
  `--print-recording` is more useful, but they can be preserved with
  this flag for troubleshooting.

Release note: None

2022-01-25 21:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/75519)
<!-- Reviewable:end -->

2022-01-26 08:46 UTC, erikgrinaker approved these changes
Nice, thank you! Out of curiosity, was there a particular need that motivated this?

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-:-MuKYvBa1u0JeiKRlELg:b-lf985i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/cli/debug.go, line 1704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuKW8pY9pClG30wUHUs:-MuKW8pY9pClG30wUHUt:b149wqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug.go#L1704)):*
> ```Go
> 	f.BoolVar(&debugSendKVBatchOpts.verboseTracing, "verbose", debugSendKVBatchOpts.verboseTracing, "whether to set the verbose flag in the trace span before the request")
> 	f.BoolVar(&debugSendKVBatchOpts.printRecording, "print-recording", debugSendKVBatchOpts.printRecording, "whether to print the trace recording at the end")
> 	f.BoolVar(&debugSendKVBatchOpts.keepCollectedSpans, "keep-collected-spans", debugSendKVBatchOpts.keepCollectedSpans, "whether to keep the CollectedSpans field on the response")
> ```

nit: consider breaking these lines up.
___
*[pkg/cli/debug_send_kv_batch.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuKWDsOCcmV_fsxhrG3:-MuKWDsOCcmV_fsxhrG4:b-fpw9zd) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L104)):*
> ```Go
> 	if debugSendKVBatchOpts.printRecording {
> 		// Not useful unless verbose is set.
> 		debugSendKVBatchOpts.verboseTracing = true
> ```

nit: is there a standard Cobra way to do argument pre-processing before the main work function?
___
*[pkg/cli/debug_send_kv_batch.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuKWtAIBVfi-iOLJx0w:-MuKWtAIBVfi-iOLJx0x:b-cy5jvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L140)):*
> ```Go
> 	admin := serverpb.NewAdminClient(conn)
> 
> 	br, rec, err := setupTraceThenSendKVBatchRequest(ctx, tracer, admin, jsonpb, &ba)
> ```

`jsonpb` doesn't appear to be used in `setupTraceThenSendKVBatchRequest`, so remove the parameter.
___
*[pkg/cli/debug_send_kv_batch.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuKXRvM-2Jxg43wfZHQ:-MuKXRvM-2Jxg43wfZHR:b-11s110) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L184)):*
> ```Go
> 
> 	// Run the request and collect the trace.
> 	br, err := doSendKVBatchRequestInternal(ctx, admin, jsonpb, ba)
> ```

nit: I think I'd prefer to inline `doSendKVBatchRequestInternal`, since that's also mostly fiddling with the trace.
___
*[pkg/server/node.go, line 956 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuKYU475jKedSFij3ng:-MuKYU475jKedSFij3nh:blns5s7) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/server/node.go#L956)):*
> ```Go
> }
> 
> func executeBatchRPCInternalFn(
> ```

nit: since this is now shared both by `Node` and `adminServer`, consider pulling it out into a different file.
___
*[pkg/server/node.go, line 966 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuKYgzj1UMJAOBxVB3e:-MuKYgzj1UMJAOBxVB3f:bg5lq50) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/server/node.go#L966)):*
> ```Go
> 	processorName redact.SafeString,
> 	senderName redact.SafeString,
> 	sender interface {
> ```

nit: we already have a named interface for this, `kv.Sender`.


<!-- Sent from Reviewable.io -->

2022-01-26 10:08 UTC, erikgrinaker approved these changes
PS: the commit title is a bit vague, consider e.g. "add tracing support for `debug send-kv-batch`"

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-:-MuKqtMgD0NU83adlgR-:byy8f5w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)



<!-- Sent from Reviewable.io -->

2022-01-26 16:39 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/debug.go, line 1702 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuM8Aj86Okzk83bQ_iG:-MuM8Aj86Okzk83bQ_iH:broqa5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug.go#L1702)):*
> ```Go
> 
> 	f = debugSendKVBatchCmd.Flags()
> 	f.BoolVar(&debugSendKVBatchOpts.verboseTracing, "verbose", debugSendKVBatchOpts.verboseTracing, "whether to set the verbose flag in the trace span before the request")
> ```

I don't think anybody will ever want a non-verbose trace. I'd replace `--verbose` and `--print-recording` with a single flag called `--trace`, that prints a verbose recording.

But another flag that I think would be useful would be a flag for a jaeger file name. You can use `Recording.ToJaegerJSON()` to produce it.
___
*[pkg/cli/debug.go, line 1704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuM8rc1-gxDcE_K3Dhy:-MuM8rc1-gxDcE_K3Dhz:b-ul6e1) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug.go#L1704)):*
> ```Go
> 	f.BoolVar(&debugSendKVBatchOpts.verboseTracing, "verbose", debugSendKVBatchOpts.verboseTracing, "whether to set the verbose flag in the trace span before the request")
> 	f.BoolVar(&debugSendKVBatchOpts.printRecording, "print-recording", debugSendKVBatchOpts.printRecording, "whether to print the trace recording at the end")
> 	f.BoolVar(&debugSendKVBatchOpts.keepCollectedSpans, "keep-collected-spans", debugSendKVBatchOpts.keepCollectedSpans, "whether to keep the CollectedSpans field on the response")
> ```

Nobody will understand what this flag does. Let's get rid of it and always wipe `br.CollectedSpans` if tracing was enabled.
___
*[pkg/cli/debug_send_kv_batch.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuM8SU10a5qOELcf-1p:-MuM8SU10a5qOELcf-1q:b-fii1fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L27)):*
> ```Go
> )
> 
> // TODO(knz): this struct belongs elsewhere.
> ```

I clicked on the linked and didn't immediately see what that issues has to do with the `TODO`. I doubt that this `TODO` adds anything. I'd say either address it or remove it.
___
*[pkg/cli/debug_send_kv_batch.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMD_AO9F7OEkUTW-Mw:-MuMD_AO9F7OEkUTW-Mx:buo40xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L168)):*
> ```Go
> }
> 
> func setupTraceThenSendKVBatchRequest(
> ```

just `sendRequest` :)
___
*[pkg/cli/debug_send_kv_batch.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuM9MA7BpJDT0_4TmUy:-MuM9MA7BpJDT0_4TmUz:b95g5gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L177)):*
> ```Go
> 	// Set up a tracing span and enable verbose tracing if requested by
> 	// configuration.
> 	ctx, rootSpan := tracing.EnsureChildSpan(ctx, tracer, "debug-send-kv-batch", tracing.WithForceRealSpan())
> ```

`WithForceRealSpan` is mostly historical. If you want a recording span, say so. I'm surprised that this works at all as written in the non-verbose case. I would have expected no recording to come back from the server. Can you show me what recording you get? As written, does `--print-recording` without `--verbose` make any sense?
If you want a recording, you're supposed to use `WithRecordingMode(RecordingStructured)`, or `WithRecordingMode(RecordingVerbose)`.

Like I was saying in the flags comment, I think we should always do `WithRecordingMode(RecordingVerbose)` if tracing is wanted.
___
*[pkg/cli/debug_send_kv_batch.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMEcU-BfaJZ_fo_Fo4:-MuMEcU-BfaJZ_fo_Fo5:b-hy6qoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L177)):*
> ```Go
> 	// Set up a tracing span and enable verbose tracing if requested by
> 	// configuration.
> 	ctx, rootSpan := tracing.EnsureChildSpan(ctx, tracer, "debug-send-kv-batch", tracing.WithForceRealSpan())
> ```

You don't need `tracing.EnsureChildSpan`. Use the simpler `tracer.StartSpanCtx()`.
As written, it reads like you're asking for a child span, but then are naming it `rootSpan`. 

also nit: `s/rootSpan/sp`. The vast majority of the code calls the span `sp`.
___
*[pkg/cli/debug_send_kv_batch.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMBqfH2hMTjgTj01Af:-MuMBqfH2hMTjgTj01Ag:b2ednxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L191)):*
> ```Go
> }
> 
> func doSendKVBatchRequestInternal(
> ```

`do` and `internal` seem like too many random words.
How about `sendRequestInternal`? But why does this function exist at all - particularly since it has tracing concerns that overlap with the caller and could be written more nicely in the other function (i.e. you don't need `tracing.SpanFromContext()`; you know the span cause you've just created it)? Fold it into the caller.
___
*[pkg/cli/start.go, line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMAo_m8rO-HG6Up55d:-MuMAo_m8rO-HG6Up55e:b-sx74n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/start.go#L1231)):*
> ```Go
> func getClientGRPCConn(
> 	ctx context.Context, cfg server.Config,
> ) (*grpc.ClientConn, *tracing.Tracer, func(), error) {
> ```

Did you actually need the tracer used by the stopper used by the `ClientConn` to be the same as the `Tracer` used by the rest of the program? Does that stopper end up interacting with the the the traced operation?
If you do need it, let's pass the Tracer in. But if you don't actually need them to be the same, I think it'd be better to leave this code alone, and have two different Tracers. This `rpcContext` would be better of not doing any tracing; since it insist on using a Tracer, let it use a different one if you can get away with it.


<!-- Sent from Reviewable.io -->

2022-02-01 23:25 UTC, knz reviewed
> was there a particular need that motivated this?

Education / onboarding.

> the commit title is a bit vague, consider e.g. "add tracing support"

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-:-MuragkD9cpyeHJ23LOS:b-icjbpa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @erikgrinaker)

___
*[pkg/cli/debug.go, line 1702 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuM8Aj86Okzk83bQ_iG:-MurRs4P99r_Cm8_yoUm:b-6ltluy) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug.go#L1702)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think anybody will ever want a non-verbose trace. I'd replace `--verbose` and `--print-recording` with a single flag called `--trace`, that prints a verbose recording.

But another flag that I think would be useful would be a flag for a jaeger file name. You can use `Recording.ToJaegerJSON()` to produce it.
</blockquote></details>

Great ideas. Done.
___
*[pkg/cli/debug.go, line 1704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuM8rc1-gxDcE_K3Dhy:-MurLr4486hQZK-Z1JXj:bnn5501) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug.go#L1704)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Nobody will understand what this flag does. Let's get rid of it and always wipe `br.CollectedSpans` if tracing was enabled.
</blockquote></details>

So as we've discussed today at team meeting, it's useful to have an option to keep the spans for education purposes (to explain how tracing works).
___
*[pkg/cli/debug.go, line 1704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuKW8pY9pClG30wUHUs:-MurSVOj4aKwpwIKLMqM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug.go#L1704)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: consider breaking these lines up.
</blockquote></details>

Done.
___
*[pkg/cli/debug_send_kv_batch.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuM8SU10a5qOELcf-1p:-MurLxGB93kyQEKlIOf_:b59wmug) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L27)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I clicked on the linked and didn't immediately see what that issues has to do with the `TODO`. I doubt that this `TODO` adds anything. I'd say either address it or remove it.
</blockquote></details>

It's part of a larger project to refactor the initialization code for _all_ `debug` sub-commands. That's out of scope here.
___
*[pkg/cli/debug_send_kv_batch.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuKWDsOCcmV_fsxhrG3:-MurMWbhAodNyjFMw_6d:bektl26) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L104)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: is there a standard Cobra way to do argument pre-processing before the main work function?
</blockquote></details>

We have a thorough architecture for command-line argument handling, it's just currently not available for all the `debug` stuff. There's a project to clean that up. Hence the TODO at the top.
___
*[pkg/cli/debug_send_kv_batch.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuKWtAIBVfi-iOLJx0w:-MurN-8qBClbQ7bUTQTV:boj1qgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L140)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

`jsonpb` doesn't appear to be used in `setupTraceThenSendKVBatchRequest`, so remove the parameter.
</blockquote></details>

Good catch. Done.
___
*[pkg/cli/debug_send_kv_batch.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMD_AO9F7OEkUTW-Mw:-MurN0IH6uzZkE3wE7Wz:biic7dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L168)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

just `sendRequest` :)
</blockquote></details>

This is a shared package with all the other CLI commands. This name is too generic.
___
*[pkg/cli/debug_send_kv_batch.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuM9MA7BpJDT0_4TmUy:-MurN5ukBw4Pb7eqUz_b:b-86jjwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L177)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`WithForceRealSpan` is mostly historical. If you want a recording span, say so. I'm surprised that this works at all as written in the non-verbose case. I would have expected no recording to come back from the server. Can you show me what recording you get? As written, does `--print-recording` without `--verbose` make any sense?
If you want a recording, you're supposed to use `WithRecordingMode(RecordingStructured)`, or `WithRecordingMode(RecordingVerbose)`.

Like I was saying in the flags comment, I think we should always do `WithRecordingMode(RecordingVerbose)` if tracing is wanted.
</blockquote></details>

TIL, thanks. Done.
___
*[pkg/cli/debug_send_kv_batch.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMEcU-BfaJZ_fo_Fo4:-MurNeqMCJTodFeqI_Um:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L177)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

You don't need `tracing.EnsureChildSpan`. Use the simpler `tracer.StartSpanCtx()`.
As written, it reads like you're asking for a child span, but then are naming it `rootSpan`. 

also nit: `s/rootSpan/sp`. The vast majority of the code calls the span `sp`.
</blockquote></details>

Done.
___
*[pkg/cli/debug_send_kv_batch.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuKXRvM-2Jxg43wfZHQ:-MurNfdk8q-bFnkY-4O0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L184)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: I think I'd prefer to inline `doSendKVBatchRequestInternal`, since that's also mostly fiddling with the trace.
</blockquote></details>

Done.
___
*[pkg/cli/debug_send_kv_batch.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMBqfH2hMTjgTj01Af:-MurO5z07njghLX6OtSI:b-il1tc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L191)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`do` and `internal` seem like too many random words.
How about `sendRequestInternal`? But why does this function exist at all - particularly since it has tracing concerns that overlap with the caller and could be written more nicely in the other function (i.e. you don't need `tracing.SpanFromContext()`; you know the span cause you've just created it)? Fold it into the caller.


</blockquote></details>

What Erik said. Done.
___
*[pkg/cli/start.go, line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMAo_m8rO-HG6Up55d:-MurOMUR9aPnUJPAfIPe:b-ynbf0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282d [...]

2022-02-01 23:44 UTC, knz commented
also added unit tests now. RFAL.

2022-02-02 13:32 UTC, erikgrinaker approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Will defer to @andreimatei on the tracing details.

> Reviewed 5 of 8 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-:-Muuca1WBEl6yaCZoKE5:bxl62l5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/server/exec_kv_batch.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuucKXd35xK-KI4RFQC:-MuucKXd35xK-KI4RFQD:b53iym1) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/server/exec_kv_batch.go#L41)):*
> ```Go
> // txn logic, or the store directly, when the batch is executed
> // "under" the txn logic.
> func executeBatchRPCInternalFn(
> ```

nit: the `Fn` suffix seems odd and unnecessary -- does it serve any purpose?


<!-- Sent from Reviewable.io -->

2022-02-02 18:06 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvWrR52INQtTsZSpez):*
looks like this commit message has diverged from the pr comment.
___
*[pkg/cli/debug_send_kv_batch.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuM8SU10a5qOELcf-1p:-MuvX8hO9qgFfhb2OMRY:b-nqpo21) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

It's part of a larger project to refactor the initialization code for _all_ `debug` sub-commands. That's out of scope here.
</blockquote></details>

be that as it may, this TODO is worse than nothing in my opinion :)
___
*[pkg/cli/debug_send_kv_batch.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMD_AO9F7OEkUTW-Mw:-MuvYag-3-TKd0sv-LPi:b-w2ukyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L168)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is a shared package with all the other CLI commands. This name is too generic.
</blockquote></details>

ok, but you do have to find something better :)
The name doesn't need to mention tracing.
___
*[pkg/cli/debug_send_kv_batch.go, line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvX_OyBD1AOixvJB3b:-MuvX_OyBD1AOixvJB3c:b-6gej2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/cli/debug_send_kv_batch.go#L35)):*
> ```Go
> 	traceFormat string
> 	// The output file to use.
> 	traceOutput string
> ```

`traceFile` ?
___
*[pkg/cli/debug_send_kv_batch.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvYFqz4N-1a4yqY3PC:-MuvYFqz4N-1a4yqY3PD:b-g4p7wd) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/cli/debug_send_kv_batch.go#L105)):*
> ```Go
> 
> func runSendKVBatch(cmd *cobra.Command, args []string) error {
> 	verboseTrace := false
> ```

by naming this `verboseTrace`, you're suggesting that there's also an option for some other type of trace (e.g. a structured recording). But there's isn't such an option, is there? Name this `trace`.
___
*[pkg/cli/debug_send_kv_batch.go, line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvZ8ZH0YUUcevtvlOs:-MuvZ8ZH0YUUcevtvlOt:bevw4nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/cli/debug_send_kv_batch.go#L243)):*
> ```Go
> 		// because otherwise the unit test TestSendKVBatch becomes non-deterministic
> 		// on the contents of the traceInfo JSON field in the request.
> 		ctx, sp = tracer.StartSpanCtx(ctx, "debug-send-kv-batch", tracing.WithRecording(tracing.RecordingVerbose))
> ```

nit: it'd be cleaner if you don't overwrite `ctx`; you're not getting any benefit from overwriting it, are you? Just do `sp := tracer.StartSpan(...)`.

But better yet, do you even need a span at all? I don't think anyone is interested in seeing this client span in the trace; it probably be better to represent only the server side trace (the client-side span in principle can tell you something about network latency, but I don't think it's interesting).
So consider populating `ba.TraceInfo` by hand. My guess is that populating `RecordingMode` should be sufficient. Maybe you also need to generate a `TraceID`. And then, on the response, you can just cast `br.CollectedSpans` to a `Recording`.
___
*[pkg/server/exec_kv_batch.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-Muvaxtw1h8jwgbxvjE2:-Muvaxtw1h8jwgbxvjE3:brse3l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/server/exec_kv_batch.go#L27)):*
> ```Go
> )
> 
> // executeBatchRPCInternalFn is a helper function which executes a KV
> ```

I don't think this refactoring is a good idea. Making this function generic over the `sender` will make the flow hard to trace. 
Why was this necessary again? If we make `adminServer.SendKVBatch`call `setupSpanForIncomingRPC`, does the reason go away?


<!-- Sent from Reviewable.io -->

2022-02-04 14:10 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @erikgrinaker)

___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvWrR52INQtTsZSpez):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

looks like this commit message has diverged from the pr comment.
</blockquote></details>

Done.
___
*[pkg/cli/debug_send_kv_batch.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuM8SU10a5qOELcf-1p:-Mv41QXaCMAja7LdesYo:b-nljlih) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L27)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

be that as it may, this TODO is worse than nothing in my opinion :)
</blockquote></details>

We have precedent elsewhere. The project to bring all debug commands under the fold wrt handling of command-line arguments is orthogonal to this PR.
___
*[pkg/cli/debug_send_kv_batch.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMD_AO9F7OEkUTW-Mw:-Mv427-1EdFSsltvumqd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/debug_send_kv_batch.go#L168)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ok, but you do have to find something better :)
The name doesn't need to mention tracing.
</blockquote></details>

Done.
___
*[pkg/cli/debug_send_kv_batch.go, line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvX_OyBD1AOixvJB3b:-Mv41YFVCvGznc-gnLB7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/cli/debug_send_kv_batch.go#L35)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`traceFile` ?
</blockquote></details>

Done.
___
*[pkg/cli/debug_send_kv_batch.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvYFqz4N-1a4yqY3PC:-Mv41bTL8QeY9su2Rl1q:b-nwaa3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/cli/debug_send_kv_batch.go#L105)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

by naming this `verboseTrace`, you're suggesting that there's also an option for some other type of trace (e.g. a structured recording). But there's isn't such an option, is there? Name this `trace`.
</blockquote></details>

cool, done.
___
*[pkg/cli/debug_send_kv_batch.go, line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvZ8ZH0YUUcevtvlOs:-Mv40yLf4t_HbDWb7Tu_:blaenqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/cli/debug_send_kv_batch.go#L243)):*
> it'd be cleaner if you don't overwrite ctx; you're not getting any benefit from overwriting it, are you?

Well yes absolutely I do, otherwise the verbose flag does not propagate. That's where grpc picks it up from.

> do you even need a span at all?

I've tried both with and without. With the span, the result trace is clearer, because it highlights the client-server network latency of the RPC call.
___
*[pkg/server/exec_kv_batch.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-Muvaxtw1h8jwgbxvjE2:-Mv43L2V30iEVxZ4pitM:b-hd50tx) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/server/exec_kv_batch.go#L27)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think this refactoring is a good idea. Making this function generic over the `sender` will make the flow hard to trace. 
Why was this necessary again? If we make `adminServer.SendKVBatch`call `setupSpanForIncomingRPC`, does the reason go away?
</blockquote></details>

Doing so essentially copy-pastes the body of the new function in two places. Given that it's not trivial to read (nor to maintain), I think that sharing the code is better.
___
*[pkg/server/exec_kv_batch.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuucKXd35xK-KI4RFQC:-Mv43aKH4FvuISXHH4I3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/server/exec_kv_batch.go#L41)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: the `Fn` suffix seems odd and unnecessary -- does it serve any purpose?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 16:36 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @knz)

___
*[pkg/cli/debug_send_kv_batch.go, line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvZ8ZH0YUUcevtvlOs:-Mv4Qq912uGdZXtBo8bn:b-gnm8rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/cli/debug_send_kv_batch.go#L243)):*
> Well yes absolutely I do, otherwise the verbose flag does not propagate. That's where grpc picks it up from.

I don't think that's true. We're not relying on gRPC to "pick up" anything, are we (since we're explicitly setting `ba.TraceInfo`)? I've just tried it `context.TODO()` in the `admin.SendKVBatch()` call below, and I get the trace fine. In fact, that's why I think it'd be better to not overwrite `ctx` - to not give the impression that that's needed.
___
*[pkg/cli/start.go, line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMAo_m8rO-HG6Up55d:-Mv4SelT9bxZmGDEfe2U:b-8q8yaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/start.go#L1231)):*
> Yes, I needed it. I was getting panics otherwise.

Can you show me please? I've stressed the new tests without this change and it all seems to work fine.

> I'm also not going to change the itnerface to getClientGRPCConn

If we do need to control the tracer, I don't think we'd need to change the interface. This function already takes in a tracer through `cfg`.
___
*[pkg/server/exec_kv_batch.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-Muvaxtw1h8jwgbxvjE2:-Mv4VLJfDABOVXUmsbVJ:b-n6m6r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/server/exec_kv_batch.go#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Doing so essentially copy-pastes the body of the new function in two places. Given that it's not trivial to read (nor to maintain), I think that sharing the code is better.
</blockquote></details>

I have to insist on this; I think it's important that the call to `Stores.Send()` be easily findable. The fact that both the server side senders and the client-side senders was, in my opinion, a mistake - they're forced to share an interface (which is inconvenient for the client-side ones which would rather not operate on `pErr`) and also their contracts are different despite sharing the interface. Let's not use this unfortunate history more than it's already used.

There's minimal copy-pasting needed to avoid this, and also minimal changes to the existing code (as opposed to your patch which changes a lot of code). A lot of what's in this `executeBatchRPCInternal` function is not particularly needed by the admin RPC; the code didn't deal with a couple of things here before, and in my opinion it was fine. I think the only thing that the admin RPC needs to do is below. I've tried it superficially.

```
	ctx, finishSpan := s.server.node.setupSpanForIncomingRPC(ctx, roachpb.SystemTenantID, ba)
	var br *roachpb.BatchResponse
	defer func() { finishSpan(ctx, br) }()
	br, pErr := s.server.db.NonTransactionalSender().Send(ctx, *ba)
	if pErr != nil {
		br = &roachpb.BatchResponse{}
		log.VErrEventf(ctx, 3, "error from stores.Send: %s", pErr)
	}
	br.Error = pErr
	return br, nil
```


<!-- Sent from Reviewable.io -->

2022-02-07 22:00 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @erikgrinaker)

___
*[pkg/cli/debug_send_kv_batch.go, line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvZ8ZH0YUUcevtvlOs:-MvJsZ_z6nAvPMv-ASWv:b-pgjhky) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/cli/debug_send_kv_batch.go#L243)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> Well yes absolutely I do, otherwise the verbose flag does not propagate. That's where grpc picks it up from.

I don't think that's true. We're not relying on gRPC to "pick up" anything, are we (since we're explicitly setting `ba.TraceInfo`)? I've just tried it `context.TODO()` in the `admin.SendKVBatch()` call below, and I get the trace fine. In fact, that's why I think it'd be better to not overwrite `ctx` - to not give the impression that that's needed.

</blockquote></details>

With the custom `ctx`, my trace starts like this:
```
     0.000ms      0.000ms    === operation:debug-send-kv-batch _unfinished:1 _verbose:1
     0.009ms      0.009ms        === operation:/cockroach.server.serverpb.Admin/SendKVBatch _verbose:1 span.kind:client
     0.261ms      0.253ms        === operation:/cockroach.server.serverpb.Admin/SendKVBatch _verbose:1 span.kind:server
     0.290ms      0.029ms        event:server/exec_kv_batch.go:62 adminServer received request: 1 Get, 1 Put
     0.299ms      0.009ms            === operation:dist sender send _verbose:1 node:1
```

Without the custom `ctx`, it starts like this:
```
     0.000ms      0.000ms    === operation:debug-send-kv-batch _unfinished:1 _verbose:1
     0.336ms      0.336ms        === operation:/cockroach.server.serverpb.Admin/SendKVBatch _verbose:1 span.kind:server
     0.364ms      0.028ms        event:server/exec_kv_batch.go:62 adminServer received request: 1 Get, 1 Put
     0.371ms      0.007ms            === operation:dist sender send _verbose:1 node:1
```

So you're right about the verbose flag, but there does seem to be a difference somehow. Can you explain that to me?
___
*[pkg/cli/start.go, line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMAo_m8rO-HG6Up55d:-MvL9qE421Iv2TXCCCWY:b-t1ov3) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/start.go#L1231)):*
> This function already takes in a tracer through cfg.

Oh you're right, I just changed that in this PR! :sweat_smile: 
Simplified accordingly.
___
*[pkg/server/exec_kv_batch.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-Muvaxtw1h8jwgbxvjE2:-MvLA97A6tVjsmPi7VbQ:b-cof5gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/server/exec_kv_batch.go#L27)):*
> I think it's important that the call to Stores.Send() be easily findable. 

I'm OK with that! Changed the interface accordingly.

> your patch which changes a lot of code

The first version of the patch had only minimal changes, because it was simply splitting a function in two. The diff was minimal. The diff is big now because Erik also asked me to move the thing to a different file.

If you think we need to optimize for diff size, I can move the function back to the place in the file where it makes the diff minimal again.

>  I think the only thing that the admin RPC needs to do is below.

That's the minimal thing, that's right, but it does not give us:
- a task that can be identified in the stopper while the batch is running.
- the trace event about which request was received.
- the assertion on br.Error at the end.

I really would prefer if the trace we get from the utility had the same structure as the trace we get from SQL (for education purposes). With your simplification, it does not any more.


<!-- Sent from Reviewable.io -->

2022-02-08 02:49 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @knz)

___
*[pkg/cli/debug_send_kv_batch.go, line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuvZ8ZH0YUUcevtvlOs:-MvLyULB0SL39d_vYx-R:bmnzwzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/cli/debug_send_kv_batch.go#L243)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

With the custom `ctx`, my trace starts like this:
```
     0.000ms      0.000ms    === operation:debug-send-kv-batch _unfinished:1 _verbose:1
     0.009ms      0.009ms        === operation:/cockroach.server.serverpb.Admin/SendKVBatch _verbose:1 span.kind:client
     0.261ms      0.253ms        === operation:/cockroach.server.serverpb.Admin/SendKVBatch _verbose:1 span.kind:server
     0.290ms      0.029ms        event:server/exec_kv_batch.go:62 adminServer received request: 1 Get, 1 Put
     0.299ms      0.009ms            === operation:dist sender send _verbose:1 node:1
```

Without the custom `ctx`, it starts like this:
```
     0.000ms      0.000ms    === operation:debug-send-kv-batch _unfinished:1 _verbose:1
     0.336ms      0.336ms        === operation:/cockroach.server.serverpb.Admin/SendKVBatch _verbose:1 span.kind:server
     0.364ms      0.028ms        event:server/exec_kv_batch.go:62 adminServer received request: 1 Get, 1 Put
     0.371ms      0.007ms            === operation:dist sender send _verbose:1 node:1
```

So you're right about the verbose flag, but there does seem to be a difference somehow. Can you explain that to me?
</blockquote></details>

The `span.kind=client` span is opened by the client grpc interceptor here: https://github.com/cockroachdb/cockroach/blob/9b46a597a02c37a6b809227f7269774517b4ecca/pkg/util/tracing/grpc_interceptor.go#L280

That span is kind of useless. The way this is supposed to be is that the server rpc span is a child of a client rpc span, but that's not how our trace is constructed. I might get rid of this client span.
___
*[pkg/cli/start.go, line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMAo_m8rO-HG6Up55d:-MvM7sZh3UOJ-SvkjklM:buvr269) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/start.go#L1231)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> This function already takes in a tracer through cfg.

Oh you're right, I just changed that in this PR! :sweat_smile: 
Simplified accordingly.

</blockquote></details>

But are you really sure even the current change is needed? The change to this function is fine but, unless we can't get away without it, I'd rather we didn't use `servercfg.Tracer` in the call to `sendKVBatchRequestWithTracingOption`. I don't think the client needs to use any `Tracer`, and if it does need to use one, I'd rather it not be important that it uses the same one as the `rpcContext` (because I think that ideally these client `RPCContexts` didn't use tracing at all). You've said above that you got panics without it, but I think I've tried it and didn't get any panic (which also matched my superficial impression that there shouldn't be any interaction between the stopper's tracer and the rpc caller's). Can you please check one more time that it is indeed needed to align these tracers?
___
*[pkg/server/exec_kv_batch.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-Muvaxtw1h8jwgbxvjE2:-MvMB5Bh4MZyN3UZymHe:b-egfmoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/server/exec_kv_batch.go#L27)):*
> I'm OK with that! Changed the interface accordingly.

I was afraid that this is what you might do. I still don't like it :); there's still unneeded indirection.

> a task that can be identified in the stopper while the batch is running.

Indeed. Screw that task. Or if you really want it, put it in by hand with another 3 lines. 

> the trace event about which request was received.

I think this is backwards; see below.

> the assertion on br.Error at the end.

Screw it.

> I really would prefer if the trace we get from the utility had the same structure as the trace we get from SQL (for education purposes). With your simplification, it does not any more.

I think it's the other way around. With this patch as written, this `received request` event that you want in the name of the traces "having the same structure" will appear twice - once in the  `adminServer` span and once in the `node` span (right?). That is confusing. As you probably realize, the requests sent through `AdminServer.SendKVBatch` eventually make their way to a `Node` (after going through all the `kvclient` stack), where `setupSpanForIncomingRPC` is called. So the `kvserver` side of the trace is the same as what SQL gets.
Let's not couple the `SendKVBatch` and `Batch` RPCs; they're very different. I don't know what Erik said, but I really think the code was fine the way it was.


<!-- Sent from Reviewable.io -->

2022-02-08 17:24 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @knz)

___
*[pkg/server/exec_kv_batch.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-Muvaxtw1h8jwgbxvjE2:-MvPKylJ25rvO84gP5rO:b-b7ar1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/server/exec_kv_batch.go#L27)):*
> > a task that can be identified in the stopper while the batch is running.

> Indeed. Screw that task. Or if you really want it, put it in by hand with another 3 lines.

Btw, we already have tasks for all RPCs here:
https://github.com/cockroachdb/cockroach/blob/844ac138ccac5e2c2ddb1ca20bce958a896e0882/pkg/rpc/context.go#L203
so the task in `batchInternal` is only useful for local batch RPC which bypass gRPC.

FWIW, I'm trying to unify the remote and local RPC paths by running the grpc interceptors for local requests too, to address https://github.com/cockroachdb/cockroach/issues/74732. I hope I'll be able to get rid for `setupSpanForIncomingRPC` in the process.


<!-- Sent from Reviewable.io -->

2022-02-08 18:45 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @erikgrinaker, and @knz)

___
*[pkg/server/exec_kv_batch.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-Muvaxtw1h8jwgbxvjE2:-MvPdLMX4dXA_OrbiS_s:bua72tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/server/exec_kv_batch.go#L27)):*
> I don't know what Erik said, but I really think the code was fine the way it was.

I agree that it's unfortunate to split this function out in this way, since it makes the code harder to follow. Your point about the request traversing this twice (in AdminServer and Node) makes sense. If we can avoid this then I'm all for it.


<!-- Sent from Reviewable.io -->

2022-02-08 21:14 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @erikgrinaker)

___
*[pkg/cli/start.go, line 1231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MuMAo_m8rO-HG6Up55d:-MvQ8cT5ABQiI3RR4S_z:b-oyh128) ([raw file](https://github.com/cockroachdb/cockroach/blob/678282dd861f1b7b7d61030eaadf12f846d1f930/pkg/cli/start.go#L1231)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

But are you really sure even the current change is needed? The change to this function is fine but, unless we can't get away without it, I'd rather we didn't use `servercfg.Tracer` in the call to `sendKVBatchRequestWithTracingOption`. I don't think the client needs to use any `Tracer`, and if it does need to use one, I'd rather it not be important that it uses the same one as the `rpcContext` (because I think that ideally these client `RPCContexts` didn't use tracing at all). You've said above that you got panics without it, but I think I've tried it and didn't get any panic (which also matched my superficial impression that there shouldn't be any interaction between the stopper's tracer and the rpc caller's). Can you please check one more time that it is indeed needed to align these tracers?
</blockquote></details>

yes, now it works. the panic was from an earlier generation of the code. I have simplified accordingly.
___
*[pkg/server/exec_kv_batch.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-Muvaxtw1h8jwgbxvjE2:-MvQAzBf5FNytwJKnjsR:b-oli48s) ([raw file](https://github.com/cockroachdb/cockroach/blob/253259176359097ff8471285f378f1cc23b07768/pkg/server/exec_kv_batch.go#L27)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

> I don't know what Erik said, but I really think the code was fine the way it was.

I agree that it's unfortunate to split this function out in this way, since it makes the code harder to follow. Your point about the request traversing this twice (in AdminServer and Node) makes sense. If we can avoid this then I'm all for it.
</blockquote></details>

ok I have simplified it as you suggest


<!-- Sent from Reviewable.io -->

2022-02-09 14:13 UTC, andreimatei approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-:-MvTp9NhE25RcO3TwYq3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @erikgrinaker, and @knz)

___
*[pkg/server/admin.go, line 2716 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MvTmc-o6HDaF6ArnGT5:-MvTmc-o6HDaF6ArnGT6:b-r6b6pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ceb6727d82b31034937c3e5e8ada3fc91188d2f/pkg/server/admin.go#L2716)):*
> ```Go
> 	if pErr != nil {
> 		br = &roachpb.BatchResponse{}
> 		log.VErrEventf(ctx, 3, "error from stores.Send: %s", pErr)
> ```

I think this message is wrong.
Also, is there a reason for this change? I don't think `br.Error` is used outside of KV. I think `return nil, pErr.GoError()` was the right thing.


<!-- Sent from Reviewable.io -->

2022-02-09 16:52 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75519)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @erikgrinaker)

___
*[pkg/server/admin.go, line 2716 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75519#-MvTmc-o6HDaF6ArnGT5:-MvUODaQEggJwEY6Bsti:b-l22kf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ceb6727d82b31034937c3e5e8ada3fc91188d2f/pkg/server/admin.go#L2716)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this message is wrong.
Also, is there a reason for this change? I don't think `br.Error` is used outside of KV. I think `return nil, pErr.GoError()` was the right thing.
</blockquote></details>

I copy-pasted your code from https://reviewable.io/reviews/cockroachdb/cockroach/75519#-Muvaxtw1h8jwgbxvjE2:-Mv4VLJfDABOVXUmsbVJ:b-n6m6r9 ...

anyway, fixed.


<!-- Sent from Reviewable.io -->

2022-02-09 18:16 UTC, merged