sql: add builtin function to validate unique constraints
cockroachdb/cockroach pull request #75548
Opened 2022-01-26 15:12 UTC by rytaft

Fixes #73560

Release note (sql change): Added a new builtin function called
`crdb_internal.validate_unique_constraints`, which can be used
to validate the unique constraints of all tables in the current
database. If any constraint fails validation, the function will
return an error with a hint about which data caused the constraint
violation. These violations can then be resolved manually by updating
or deleting the rows in violation. This will be useful to users who
think they may have been affected by #73024.

2022-01-26 15:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/75548)
<!-- Reviewable:end -->

2022-01-26 22:36 UTC, postamar requested changes
Nice! Just a few comments regarding implementation choices.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-:-MuNWrTRCWnkq-n8vr7p:b-wk1o9x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @otan, and @rytaft)

___
*[pkg/sql/check.go, line 409 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuNU0NH1ptm4748CJZ6:-MuNU0NH1ptm4748CJZ7:b-z6udpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/sql/check.go#L409)):*
> ```Go
> 		}
> 
> 		tableDescIntf, err := p.GetImmutableTableInterfaceByID(ctx, int(tableID))
> ```

Instead of this and the above `crdb_internal.tables` lookup, it would be better to call `p.Descriptors().GetAllTableDescriptorsInDatabase`. This requires a database ID, to get that from the name of the current database, you can do
```
p.Descriptors().GetImmutableDatabaseByName(ctx, p.Txn(), p.CurrentDatabase(), tree.DatabaseLookupFlags{Required: true})
```
to retrieve the current database descriptor.
___
*[pkg/sql/check.go, line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuNWdF2AsTgswE4R5tg:-MuNWdF2AsTgswE4R5th:bwhav2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/sql/check.go#L448)):*
> ```Go
> 				); err != nil {
> 					log.Errorf(ctx, "validation of unique constraints failed for table %s: %s", tableDesc.GetName(), err)
> 					return errors.Wrapf(err, "for table %s", tableDesc.GetName())
> ```

Here and in the index case above, would it be worth adding the violated constraint's name into the error message somehow?


<!-- Sent from Reviewable.io -->

2022-01-26 22:47 UTC, mgartner approved these changes
Cool! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-:-MuNZiYx-JvdnP6J8U3s:b-dp13x5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @postamar, and @rytaft)

___
*[pkg/sql/check.go, line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuNWdF2AsTgswE4R5tg:-MuNZVn77KEHQVz4l2uS:bcxwj13) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/sql/check.go#L448)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Here and in the index case above, would it be worth adding the violated constraint's name into the error message somehow?
</blockquote></details>

I think this is already included in the error returned from `validateUniqueConstraint` here: https://github.com/cockroachdb/cockroach/blob/fa193c3277de67408c6507bf0e2ef036ab6f070b/pkg/sql/check.go#L406


<!-- Sent from Reviewable.io -->

2022-01-26 23:16 UTC, ajwerner reviewed
How would you feel about making a function of regclass? My 2c is that it's easy to write the query for all tables but that this thing is going to be very slow to run and won't help if you just wanted to check on a single table. I'm cool also with a function like you've got to validate all of the constraints. It could just call into the logic to validate an individual table. Given the way the code is written, I don't think it's much of a refactor to take a name or table ID and then go and validate its constraints. I think it also might be useful to have an overload that's got the constraint name.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-:-MuNeHoI9nbi-cV4WGs7:bgihca8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @postamar, and @rytaft)



<!-- Sent from Reviewable.io -->

2022-01-26 23:18 UTC, ajwerner reviewed
Also, what do you think about using the term `revalidate` instead of `validate`. `VALIDATE CONSTRAINT` is existing sql syntax to make an unvalidated constraint validated. This might be confusing. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-:-MuNfYnV-ndqKihVc5kj:b-5p3sc5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @postamar, and @rytaft)



<!-- Sent from Reviewable.io -->

2022-01-27 03:55 UTC, otan commented
looking good, but i agree with both of @ajwerner's suggestions.
maybe have both revalidate_table and revalidate_all_tables?

meta question: i wonder if we want to incorporate more "data" based validations in future, e.g. each foreign key reference should exist. does that exist today (is that scrub)? should they all have a similar kind of interface to check?





<!-- Sent from Reviewable.io -->

2022-01-27 04:04 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar and @rytaft)

___
*[pkg/ccl/multiregionccl/unique_test.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuOdxFd2d2PkWsdp-eg:-MuOdxFd2d2PkWsdp-eh:bwktqnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/ccl/multiregionccl/unique_test.go#L31)):*
> ```Go
> // crdb_internal.validate_unique_constraints() can find unique constraint
> // violations.
> func TestValidateUniqueConstraints(t *testing.T) {
> ```

i think this test might read nicer as a datadriven test, but totally up to you- i can see it both ways!
___
*[pkg/ccl/multiregionccl/unique_test.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuOeE3yEXkcxPeo1wYp:-MuOeE3yEXkcxPeo1wYq:bk3vgjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/ccl/multiregionccl/unique_test.go#L112)):*
> ```Go
> 	t.Run("validate_unique_without_index", func(t *testing.T) {
> 		// Insert a couple of rows into table t.
> 		_, err := db.Exec(`INSERT INTO test.t VALUES (10, 10), (20, 20);`)
> ```

i think you can omit all the semicolons from the queries here


<!-- Sent from Reviewable.io -->

2022-01-28 04:00 UTC, rytaft reviewed
TFTRs!

> How would you feel about making a function of regclass? 

Done. (I think I did this correctly, but please let me know if not)

> I think it also might be useful to have an overload that's got the constraint name.

Done.

> what do you think about using the term revalidate instead of validate

Done.

> maybe have both revalidate_table and revalidate_all_tables?

I used the name revalidate_unique_constraint and revalidate_unique_constraints for all. But I can change to specify table / all_tables if you think it's confusing as-is, it just makes the names longer.

> meta question: i wonder if we want to incorporate more "data" based validations in future, e.g. each foreign key reference should exist. does that exist today (is that scrub)? should they all have a similar kind of interface to check?

Yea, SCRUB checks that, although it's not widely used. I have another issue open to add uniqueness checks to SCRUB. Agreed that we should incorporate more checks like this into our testing in general. I figured I'd get this PR merged with the new functions, and then we can go about sprinkling some calls throughout various tests (e.g., the multi-region SQLSmith test).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-:-MuTd36z2AltqaLUaz7V:bneaz2y)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @otan, and @postamar)

___
*[pkg/sql/check.go, line 409 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuNU0NH1ptm4748CJZ6:-MuTVIU01XGqwfqr3Jq3:b-uoez4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/sql/check.go#L409)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Instead of this and the above `crdb_internal.tables` lookup, it would be better to call `p.Descriptors().GetAllTableDescriptorsInDatabase`. This requires a database ID, to get that from the name of the current database, you can do
```
p.Descriptors().GetImmutableDatabaseByName(ctx, p.Txn(), p.CurrentDatabase(), tree.DatabaseLookupFlags{Required: true})
```
to retrieve the current database descriptor.
</blockquote></details>

Done. Thanks for the pointers!
___
*[pkg/sql/check.go, line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuNWdF2AsTgswE4R5tg:-MuTVNgp5IXVYKtteQNt:b-93fa55) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/sql/check.go#L448)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think this is already included in the error returned from `validateUniqueConstraint` here: https://github.com/cockroachdb/cockroach/blob/fa193c3277de67408c6507bf0e2ef036ab6f070b/pkg/sql/check.go#L406
</blockquote></details>

Yep, @mgartner is right
___
*[pkg/ccl/multiregionccl/unique_test.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuOdxFd2d2PkWsdp-eg:-MuTVRmICVEb-q4c2CjB:b-dcpad6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/ccl/multiregionccl/unique_test.go#L31)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think this test might read nicer as a datadriven test, but totally up to you- i can see it both ways!
</blockquote></details>

I did it this way because I needed to create some corrupted indexes by bypassing the SQL layer. Do you know of a way to do that as a datadtiven test?
___
*[pkg/ccl/multiregionccl/unique_test.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuOeE3yEXkcxPeo1wYp:-MuTVqii7wxF8Mvk7mjx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/ccl/multiregionccl/unique_test.go#L112)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think you can omit all the semicolons from the queries here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-28 08:28 UTC, otan reviewed
> Reviewed 4 of 8 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @otan, @postamar, and @rytaft)

___
*[pkg/sql/check.go, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuUmjaCEzyojz5RuLai:-MuUmjaCEzyojz5RuLaj:b-1g7xgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/102de17434e4d0dc1c7c377c5149eb3dcee6cbfd/pkg/sql/check.go#L430)):*
> ```Go
> 
> 	// Check implicitly partitioned UNIQUE indexes.
> 	for _, index := range tableDesc.ActiveIndexes() {
> ```

this is pretty close to ` revalidateUniqueConstraintsInTable`, but not exactly the same. was this deliberate?
___
*[pkg/sql/sem/builtins/builtins.go, line 6414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuUmM0Q0pVlKWLsdeAi:-MuUmM0Q0pVlKWLsdeAj:b-emigqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/102de17434e4d0dc1c7c377c5149eb3dcee6cbfd/pkg/sql/sem/builtins/builtins.go#L6414)):*
> ```Go
> 		tree.Overload{
> 			Types:      tree.ArgTypes{},
> 			ReturnType: tree.FixedReturnType(types.Bool),
> ```

probably worth using the void type `types.Void` to return for all of these
___
*[pkg/ccl/multiregionccl/unique_test.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuOdxFd2d2PkWsdp-eg:-MuUm6CcABQmvQd9cNhW:b-dzdsek) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/ccl/multiregionccl/unique_test.go#L31)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I did it this way because I needed to create some corrupted indexes by bypassing the SQL layer. Do you know of a way to do that as a datadtiven test?
</blockquote></details>

you'd need to introduce a new directive to do it. but yeah i'm not fussed, this is fine.


<!-- Sent from Reviewable.io -->

2022-01-28 15:33 UTC, rytaft reviewed
I ended up changing the function names to something similar to what @otan suggested. These functions won't be used often so I think it's better to be explicit about what they do even if it makes the names longer.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-:-MuWFe-wDYv6ODh5v36S:bgwjkd9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @otan, and @postamar)

___
*[pkg/sql/check.go, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuUmjaCEzyojz5RuLai:-MuWG-l_84xo8mtRJs_d:b-3llpi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/102de17434e4d0dc1c7c377c5149eb3dcee6cbfd/pkg/sql/check.go#L430)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this is pretty close to ` revalidateUniqueConstraintsInTable`, but not exactly the same. was this deliberate?
</blockquote></details>

Yea, it has to be a bit different since we're looking for a specific constraint as opposed to checking all constraints. I don't think it's possible to combine them easily.
___
*[pkg/sql/sem/builtins/builtins.go, line 6414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuUmM0Q0pVlKWLsdeAi:-MuWGiL1B-RCvDXVFgQ2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/102de17434e4d0dc1c7c377c5149eb3dcee6cbfd/pkg/sql/sem/builtins/builtins.go#L6414)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

probably worth using the void type `types.Void` to return for all of these
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/unique_test.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-MuOdxFd2d2PkWsdp-eg:-MuWGjfH5xofZt0_HQJK:b-mc7ln0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82c8fef9985f91670236d87d196a96f201a57da/pkg/ccl/multiregionccl/unique_test.go#L31)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

you'd need to introduce a new directive to do it. but yeah i'm not fussed, this is fine.
</blockquote></details>

Sounds good -- I think we can add the directive later if we think it will be used in more tests, but for now I'll just leave it like this.


<!-- Sent from Reviewable.io -->

2022-01-30 20:47 UTC, otan approved these changes
> Reviewed 1 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @postamar)



<!-- Sent from Reviewable.io -->

2022-01-31 15:27 UTC, rytaft reviewed
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-:-Mukjs8ODpcZ99zwIdEy:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @postamar)



<!-- Sent from Reviewable.io -->

2022-01-31 16:03 UTC, ajwerner commented
Looks like merge skew.

2022-01-31 16:29 UTC, rytaft reviewed
Rebased, will try again.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-:-Muky4rO-6_kX4yd8lAX:b-izfoo7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @otan, and @postamar)



<!-- Sent from Reviewable.io -->

2022-01-31 22:32 UTC, irfansharif commented
bors r- 

(Failing linters I think, sorry!)

2022-02-01 22:58 UTC, rytaft reviewed
Thanks. It was merge skew due to the package refactor.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75548#-:-MurUrWg5FRTcU9P8rb_:b-pqaysh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @otan, and @postamar)



<!-- Sent from Reviewable.io -->

2022-02-02 03:24 UTC, merged