sql: introduce contention event resolver
cockroachdb/cockroach pull request #75763
Opened 2022-01-31 23:49 UTC by Azhng

Note: only the last commit is relevant.

---

This commit introduces contention event resolver. The new resolver
implements a queue-like interface, where unresolved contention events
will be queued into the resolver. The resolution is performed by
invoking the `resolve()` method on the resolver queue, and the result of
the resolution can be retrieved by calling `dequeue()` method.

Release note: None

2022-01-31 23:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/75763)
<!-- Reviewable:end -->

2022-02-09 22:10 UTC, matthewtodd requested changes
Neat! I read through and left some initial thoughts / comments.

> Reviewed 13 of 17 files at r1, 4 of 4 files at r2, 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-:-MvVXDft-l39gD7zLocU:b-81hiyt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[pkg/sql/contention/resolver.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-MvVPJn2BlTfFWYKyu3I:-MvVPJn2BlTfFWYKyu3J:btixcza) ([raw file](https://github.com/cockroachdb/cockroach/blob/b87346f21ac0df27195843d7f3c45781a379b76f/pkg/sql/contention/resolver.go#L25)):*
> ```Go
> )
> 
> type resolverQueue interface {
> ```

I'm finding I want a comment on this type to tell me what it means to "resolve" an `ExtendedContentionEvent`.
___
*[pkg/sql/contention/resolver.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-MvVQBx8-JJv_gABSL_W:-MvVQBx99MQQNoVwmGYx:b5ix1e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b87346f21ac0df27195843d7f3c45781a379b76f/pkg/sql/contention/resolver.go#L47)):*
> ```Go
> 	// 2. the txnID is in the concurrentWriteBuffer of the remote node and
> 	//    the worker goroutine hasn't had the chance to processed it yet.
> 	retryBudgetForMissingResult = uint32(1)
> ```

Might be worth saying why 1 retry is enough. (Something about retry frequency vs. worker processing rate on the remote node?)
___
*[pkg/sql/contention/resolver.go, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-MvVQrh21A4hL6wR310h:-MvVQrh21A4hL6wR310i:b-wzp9mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b87346f21ac0df27195843d7f3c45781a379b76f/pkg/sql/contention/resolver.go#L94)):*
> ```Go
> 
> func (s *resolverQueueImpl) resolve(ctx context.Context) error {
> 	s.mu.Lock()
> ```

It looks like `resolve` blocks `enqueue`. Are we okay with that?


<!-- Sent from Reviewable.io -->

2022-02-11 19:54 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75763)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/sql/contention/resolver.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-MvVPJn2BlTfFWYKyu3I:-MveKMVx9dVfsZN_zo_l:bs3mhdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b87346f21ac0df27195843d7f3c45781a379b76f/pkg/sql/contention/resolver.go#L25)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I'm finding I want a comment on this type to tell me what it means to "resolve" an `ExtendedContentionEvent`.
</blockquote></details>

Comment added.
___
*[pkg/sql/contention/resolver.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-MvVQBx8-JJv_gABSL_W:-MveKOTt4W9JH1TjG0r7:bsnufkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b87346f21ac0df27195843d7f3c45781a379b76f/pkg/sql/contention/resolver.go#L47)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Might be worth saying why 1 retry is enough. (Something about retry frequency vs. worker processing rate on the remote node?)
</blockquote></details>

Rewrote the comment here and explained it in more details.
___
*[pkg/sql/contention/resolver.go, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-MvVQrh21A4hL6wR310h:-MveKSN69u7ivfRijs1v:b-r0k28f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b87346f21ac0df27195843d7f3c45781a379b76f/pkg/sql/contention/resolver.go#L94)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

It looks like `resolve` blocks `enqueue`. Are we okay with that?
</blockquote></details>

Yes, since we will have another layer of queuing outside of the `resolverQueue`. (Coming up in another PR, where the contention event will be collected using a `concurrentWriteBuffer` + golang's channel similar to txnID cache). Resolver queue will only be used by the background goroutine to so it's not on the query execution hot path. 

I think the locking here can potentially be optimized? E.g. the resolver work with a method-local copy of the queue and in the end (through a `defer`) that method-local copy of the queue can be appended to the actual queue. 

Though I think I want to get all the components merged first in order to run some benchmark before making micro-optimizations like that in the case where the performance is not ideal.


<!-- Sent from Reviewable.io -->

2022-02-14 18:45 UTC, Azhng commented
Rebased to pick up a lot of changes that can cause potential merge conflict. Still, only the last commit is relevant.

2022-02-16 16:35 UTC, matthewtodd requested changes
Nice! Bunch of comments here from our in-person conversation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-:-Mw2NmOU4xxA2kIBvy1B:b-203frq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[pkg/sql/contention/resolver.go, line 26 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2EFWDEVTS1hVhB74D:-Mw2EFWEE7LA5RjB_-uu:b-x5lboy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L26)):*
> ```Go
> )
> 
> // resolverQueue's main responsibility is to resolve the transaction IDs
> ```

nit: s/resolve/map, maybe?
___
*[pkg/sql/contention/resolver.go, line 28 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2EeyxE7wnmI1l_niA:-Mw2EeyxE7wnmI1l_niB:b-iwt7rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L28)):*
> ```Go
> // resolverQueue's main responsibility is to resolve the transaction IDs
> // present in the contention events into transaction fingerprint IDs (a.k.a
> // Txn ID resolution). When a contention event is collected, it is likely that
> ```

nit: Something like "When we are waiting because of contention, we will not yet know the blocking transaction's fingerprint id," worked into the rest of the prose.
___
*[pkg/sql/contention/resolver.go, line 29 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2Dve7CHEv3uZA1WUu:-Mw2Dve7CHEv3uZA1WUv:b-r3i70a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L29)):*
> ```Go
> // present in the contention events into transaction fingerprint IDs (a.k.a
> // Txn ID resolution). When a contention event is collected, it is likely that
> // the two conflicting transactions originated from different nodes. This
> ```

nit: say something like "so we won't have both of their txn fingerprint ids here on the current node."
___
*[pkg/sql/contention/resolver.go, line 47 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2Ffdt3dqDS5WiZ3Xc:-Mw2Ffdt3dqDS5WiZ3Xd:b-o3x19s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L47)):*
> ```Go
> 	// dequeue returns all the resolved contention events and remove them from the
> 	// resolverQueue.
> 	dequeue() []contentionpb.ExtendedContentionEvent
> ```

nit: since `resolve` is synchronous, would it make sense to combine it with `dequeue`? (All clients (all one of them?) will always call one followed by the other.)
___
*[pkg/sql/contention/resolver.go, line 55 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2G-hX2iHvGvvs8Bk4:-Mw2G-hX2iHvGvvs8Bk5:b-an9u2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L55)):*
> ```Go
> 	// scenarios:
> 	// 1. the txnID is in the concurrentWriteBuffer of the remote node and
> 	//    the worker goroutine hasn't had the chance to processed it yet.
> ```

nit: s/processed/process/
___
*[pkg/sql/contention/resolver.go, line 65 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2G7SM5njJCRBslOhJ:-Mw2G7SM5njJCRBslOhK:bkt389c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L65)):*
> ```Go
> 	//    is very low and it didn't generate enough transaction to fill the write
> 	//    buffer of the txnID cache). Since when the TxnIDResolution handler
> 	//    encounters a missing txnID entry, it will forces a txnID cache flush.
> ```

nit: maybe make this idea -- that the forced flush on query means our next retry will either succeed or always fail -- the most prominent? 
___
*[pkg/sql/contention/resolver.go, line 115 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2HIGU9iFzvdzzV53v:-Mw2HIGU9iFzvdzzV53w:b-2zfvz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L115)):*
> ```Go
> }
> 
> func (s *resolverQueueImpl) enqueue(block []contentionpb.ExtendedContentionEvent) {
> ```

nit: is `s` a funny name for this now?
___
*[pkg/sql/contention/resolver.go, line 142 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2H5K6E-USSWKJixVd:-Mw2H5K6E-USSWKJixVe:b-cy6hb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L142)):*
> ```Go
> 		if len(currentBatch) == 0 {
> 			break
> 		}
> ```

nit: put this in the for block
___
*[pkg/sql/contention/resolver.go, line 159 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2ID1_9fo2f_wzdzRz:-Mw2ID1_9fo2f_wzdzS-:bqnl2ga) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L159)):*
> ```Go
> 			continue
> 		}
> 		resolvedTxnIDs := resolvedTxnIDsToMap(resp.ResolvedTxnIDs)
> ```

nit: What if this function returned both the map and a slice of "in-progress" txns (maybe also as a map)? Except that'll mean rethinking the for loop below, so maybe not worth it?
___
*[pkg/sql/contention/resolver.go, line 204 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2J2ja1EKyhDYSHqvz:-Mw2J2ja1EKyhDYSHqw-:b6aruhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L204)):*
> ```Go
> 
> func (s *resolverQueueImpl) maybeRequeueBatchLocked(
> 	batch []contentionpb.ExtendedContentionEvent, defaultBudget uint32,
> ```

nit: s/defaultBudget/initialBudget, maybe?
___
*[pkg/sql/contention/resolver.go, line 218 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2JQaE3fNyjTyKY82f:-Mw2JQaE3fNyjTyKY82g:bidtvy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L218)):*
> ```Go
> 	// re-queue the event for retry and decrement its retry budget for the
> 	// event.
> 	remainingRetryBudget, ok := s.mu.retryRecord[event.Event.TxnMeta.ID]
> ```

nit: s/retryRecord/remainingRetries, maybe? Or something else?
___
*[pkg/sql/contention/resolver.go, line 231 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2JqSW6tcJ2chQxdHS:-Mw2JqSW6tcJ2chQxdHT:b-byeesj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L231)):*
> ```Go
> 
> 	s.mu.retryRecord[event.Event.TxnMeta.ID]--
> 	s.mu.unresolvedEvents = append(s.mu.unresolvedEvents, event)
> ```

nit: Can we reorder this to avoid duplicating the append call?
___
*[pkg/sql/contentionpb/contention.proto, line 169 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2LDDr09AbevcbwZY8:-Mw2LDDr09AbevcbwZY9:b-51ebf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contentionpb/contention.proto#L169)):*
> ```protobuf
>      (gogoproto.nullable) = false,
>      (gogoproto.stdtime) = true
>    ];
> ```

nit: @azhng says he should delete this field at this commit.
___
*[pkg/sql/contention/resolver_test.go, line 38 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2L_n67aiOJuXAmDVU:-Mw2L_n67aiOJuXAmDVV:b-2jqb9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver_test.go#L38)):*
> ```Go
> 
> 	t.Run("normal_resolution", func(t *testing.T) {
> 		tcs := []testCase{
> ```

nit: rename? (I expected each of these was going to result in a different test run.)
___
*[pkg/sql/contention/resolver_test.go, line 158 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2MHM0-YfBLWAQs_sI:-Mw2MHM0-YfBLWAQs_sJ:bixtn5l) ([raw file](https: [...]

2022-02-16 21:01 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75763)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/sql/contention/resolver.go, line 47 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2Ffdt3dqDS5WiZ3Xc:-Mw3BdvYB7nWJUVJLPHs:bcjqaql) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L47)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: since `resolve` is synchronous, would it make sense to combine it with `dequeue`? (All clients (all one of them?) will always call one followed by the other.)
</blockquote></details>

Done. Removed `resolve` from interface definition. 
___
*[pkg/sql/contention/resolver.go, line 65 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2G7SM5njJCRBslOhJ:-Mw3E7N7DsDyF2kKc7mn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L65)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: maybe make this idea -- that the forced flush on query means our next retry will either succeed or always fail -- the most prominent? 
</blockquote></details>

Done.
___
*[pkg/sql/contention/resolver.go, line 159 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2ID1_9fo2f_wzdzRz:-Mw36OI17zoyqQgxRHzE:btmgej8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L159)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: What if this function returned both the map and a slice of "in-progress" txns (maybe also as a map)? Except that'll mean rethinking the for loop below, so maybe not worth it?
</blockquote></details>

Done. Returning 2 maps (one for resolved txns and the other one for inprogress txns) and rewrote the loop logic below.
___
*[pkg/sql/contention/resolver.go, line 231 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2JqSW6tcJ2chQxdHS:-Mw37DOi3X-MAz9zlcwe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver.go#L231)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Can we reorder this to avoid duplicating the append call?
</blockquote></details>

Done.
___
*[pkg/sql/contention/resolver_test.go, line 38 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2L_n67aiOJuXAmDVU:-Mw3CG_wBy0kxi1b_6mz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver_test.go#L38)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: rename? (I expected each of these was going to result in a different test run.)
</blockquote></details>

Done.
___
*[pkg/sql/contention/resolver_test.go, line 158 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-Mw2MHM0-YfBLWAQs_sI:-Mw3IiL96rHAkmyMrVP-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b12aeb5dd6deef29d8364053313816341abca974/pkg/sql/contention/resolver_test.go#L158)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: for this and below, make a new expected rather than overwriting the old one.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-23 18:17 UTC, THardy98 reviewed
@azhng and I discussed the retry budget a bit during our synchronous review. The retry budget is currently set once and decremented upon each retry.

Might be worth considering how to handle updates to the retry budget in the future.

One scenario to consider might be:
- an initial retry budget is set when we encounter a missing result from the resolver
- retry budget falls to 1
- on last retry, the RPC fails

Should the retry budget be reset to the RPC failure retry budget (in cases where we have more than 1 remaining retry on our budget, would this overwrite or add to the existing # of retries)? Resetting/adding to the retry budget opens the possibility for a retry budget never reaching 0, would this be okay (or perhaps an alternative approach could be taken to allow the reset budget to be reset but also insure its eventual termination)?

Not a big issue. With the current implementation and the scenario mentioned above, the retry budget would reach 0 and the contention event would not be fetched, which isn't the end of the world.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-:-Mwbkx8U68NtAL65QL3T:b-t5pji1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)



<!-- Sent from Reviewable.io -->

2022-02-24 00:30 UTC, Azhng commented
Interesting idea. Indeed, if the failure mode transition from `MissingResult` to `RPCFailure`, the retry budget will not be reset. And in this case, the contention event only has 1 retry opportunity before it's being discarded. 

However, I think there is also the possibility of undesirable infinite retries when the remote node constantly transition from `MissingResult` -> `RPCFailure` -> `MissingResult` (due to txnID cache eviction?) -> `RPCFailure` (e.g. perhaps when the network link becomes flaky?). 

I have #75110 filed to track the work of stability testing during the stability period. I think this is something I will pay attention to when I start working on it.

2022-02-24 15:26 UTC, THardy98 reviewed
Potentially could introduce a secondary budget for failure mode transitions, called a `reset budget`. Each failure mode transition would reset the original retry budget to the initial budget of the new failure mode. Each budget reset would decrement from the reset budget. If the failure mode transitions and the reset budget has reached 0, decrement from the retry budget. The retry budget remains the budget that determines when no more retries occur.

In this case, I imagine the reset budget doesn't need to be too high, maybe something like 3.
Just an idea :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-:-MwgJT267AJzJ0aSMiSO:bc4jp2l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)



<!-- Sent from Reviewable.io -->

2022-02-24 18:48 UTC, matthewtodd approved these changes
Just took another quick look. I think we're ready to go with this one! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 24 files at r10, 6 of 6 files at r13, 19 of 19 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-:-Mwh2iE92xY0V9fKHSqf:bkr4xkr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)



<!-- Sent from Reviewable.io -->

2022-02-24 21:53 UTC, maryliag approved these changes
Nice! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 6 files at r13, 19 of 19 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75763#-:-MwhiQcb-lBcIvJmqmiA:bfd61qr)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)



<!-- Sent from Reviewable.io -->

2022-02-26 02:41 UTC, merged