sql: make UI user active statements and open transactions consistent
cockroachdb/cockroach pull request #75815
Opened 2022-02-01 20:32 UTC by THardy98

Previously, the number of Active SQL Statements could be greater than
the number of Open SQL Transactions on the UI. This inconsistency was
due to filtering out internal Open SQL Transactions but keeping
internal Active SQL Statements. This change fixes this inconsistency by
filtering out both internal Active SQL Statements and internal Open SQL
Transactions.

Resolves: #70228
Release note: None

2022-02-02 15:31 UTC, jocrl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl and @THardy98)

___
*[pkg/sql/exec_util.go, line 786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv0UqzAc-QMznBTuTu:-Muv0UqzAc-QMznBTuTv:b-jxwdjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/exec_util.go#L786)):*
> ```Go
> 		Measurement: "Active Statements",
> 		Unit:        metric.Unit_COUNT,
> 	}
> ```

I'm just curious that your change also seems to be adding accounting for the number of active statements. Whereas the commit/PR message seems to imply that this was already being counted; just that you are changing the behavior?



_Code quote:_
```Go
	MetaSQLActiveQueries = metric.Metadata{
		Name:        "sql.statements.active",
		Help:        "Number of SQL statements currently active",
		Measurement: "Active Statements",
		Unit:        metric.Unit_COUNT,
	}
```
___
*[pkg/sql/conn_executor_test.go, line 1406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv13e_C_Gnr7DWnlwi:-Muv13e_C_Gnr7DWnlwj:bza2sao) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1406)):*
> ```Go
> }
> 
> func TestTrackOnlyExternalOpenTransactions(t *testing.T) {
> ```

Just curious; I don't know - is "external" the vocabulary for the opposite of "internal"? My cursory understanding was that the opposite of "internal" was "general user app stuff that IDK how to name".



_Code quote:_
```Go
TestTrackOnlyExternalOpenTransactions
```
___
*[pkg/sql/conn_executor_test.go, line 1511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv2Wnc0zLJ7yQIMklv:-Muv2Wnc0zLJ7yQIMklw:b-ljcys1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1511)):*
> ```Go
> }
> 
> func TestTrackOnlyExternalActiveStatements(t *testing.T) {
> ```

I'm wondering if you also want a test to make sure that the behavior of the two are consistent in that they both filter out internal? To guard against changes to one but not the other. WDYT?


<!-- Sent from Reviewable.io -->

2022-02-02 15:51 UTC, maryliag requested changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jocrl, @maryliag, and @THardy98)

___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv62sOAG5RvV2Iqa1i):*
this should have a release note, since you're changing the behaviour that users can notice
___
*[pkg/sql/exec_util.go, line 786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv0UqzAc-QMznBTuTu:-Muv7_c16DXjDOdsiPwE:b2ngthx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/exec_util.go#L786)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

I'm just curious that your change also seems to be adding accounting for the number of active statements. Whereas the commit/PR message seems to imply that this was already being counted; just that you are changing the behavior?
</blockquote></details>

+1 


<!-- Sent from Reviewable.io -->

2022-02-02 17:26 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/sql/conn_executor_test.go, line 1430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuvR6lr5NrL_9LXCvPm:-MuvR6lr5NrL_9LXCvPn:bci5hx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1430)):*
> ```Go
> 			waitingQuery,
> 		)
> 		if err != nil {
> ```

The err should not be nil here. We can just remove the nil check. 
___
*[pkg/sql/conn_executor_test.go, line 1444 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuvRIQm4aNc7AXY-fSf:-MuvRIQm4aNc7AXY-fSg:b-ejlaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1444)):*
> ```Go
> 		)
> 		if err != nil {
> 			require.NoError(t, err, "executing %s  ", selectQuery)
> ```

Having `require.NoError` can be problematic in `testutils.SucceedsWithin` block. This is because if the `require` check fails the the function won't be retried, the test runner will just fail the test immediately. Simply returns the error in this case, or you can annotate it with additional information. The `SuceedsWithin` will handle the test failure 
___
*[pkg/sql/conn_executor_test.go, line 1493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuvSgam-7A-FC_qSdhP:-MuvSgam-7A-FC_qSdhQ:b-xz2irn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1493)):*
> ```Go
> 	if _, err := sqlDB.Exec("BEGIN"); err != nil {
> 		require.NoError(t, err, "executing %s  ", "BEGIN")
> 	}
> ```

nit: simply do:


``` golang
_, err := sqlDB.Exec("BEGIN')
require.NoError(t, err)
```


Conditional err check is not necessary with `require` library
___
*[pkg/sql/conn_executor_test.go, line 1511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv2Wnc0zLJ7yQIMklv:-MuvSwZFB1wLIUoTfi01:b-2x688y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1511)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

I'm wondering if you also want a test to make sure that the behavior of the two are consistent in that they both filter out internal? To guard against changes to one but not the other. WDYT?
</blockquote></details>

Correct me if I'm wrong, I feel the verification logic can live in the same unit test instead of two? (Otherwise we are spinning up two test servers instead of one) 


<!-- Sent from Reviewable.io -->

2022-02-02 18:40 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/sql/exec_util.go, line 786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv0UqzAc-QMznBTuTu:-MuvUtBt710E7vhkzObH:bjjh5lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/exec_util.go#L786)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

+1 
</blockquote></details>

Active statements was already being accounted for but included both internal & external active statements (`sql.distsql.queries.active`). The counting was being done at the SQL engine, which didn't provide enough context to determine whether the statement was internal/external. The introduced `sql.statements.active` counts active statements at a higher layer where internal/external context is available, and used to only counts external active statements. 
___
*[pkg/sql/conn_executor_test.go, line 1406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv13e_C_Gnr7DWnlwi:-MuvWiHI6bFMqtPfqcwE:bl2l116) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1406)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Just curious; I don't know - is "external" the vocabulary for the opposite of "internal"? My cursory understanding was that the opposite of "internal" was "general user app stuff that IDK how to name".
</blockquote></details>

From my discussions with @azhng, an "internal" transaction is any transaction executed by the `InternalExecutor`. Complementary, an external transaction is any transaction executed by any external executor (i.e. `sql.DB.beginTxn(...)`).

What's also worth knowing is that there are also "implicit" and "explicit" transactions. "Explicit" transactions occur when a user (explicitly) begins and ends a transaction with `BEGIN` and `COMMIT`. An "implicit" transaction is any single statement executed outside of an explicit transaction context (i.e. `SELECT city from rides;` is executed as a single statement, but becomes an "implicit" transaction under the hood, thereby carrying the same serializable guarantees a transaction provides).

@azhng just want to make sure this is correct
___
*[pkg/sql/conn_executor_test.go, line 1430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuvR6lr5NrL_9LXCvPm:-MuvZxtv5kffBRUzRoVT:b-ylhvb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1430)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

The err should not be nil here. We can just remove the nil check. 
</blockquote></details>

Yup, nice catch. Done.
___
*[pkg/sql/conn_executor_test.go, line 1444 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuvRIQm4aNc7AXY-fSf:-Muv_FkC51wX2vt7hpnA:bkmfa2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1444)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Having `require.NoError` can be problematic in `testutils.SucceedsWithin` block. This is because if the `require` check fails the the function won't be retried, the test runner will just fail the test immediately. Simply returns the error in this case, or you can annotate it with additional information. The `SuceedsWithin` will handle the test failure 
</blockquote></details>

Oh didn't know that, nice. Removed the `require.NoError` checks inside of `SucceedsWithin` blocks.
___
*[pkg/sql/conn_executor_test.go, line 1493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuvSgam-7A-FC_qSdhP:-MuvaUf43uTgci94-yJv:b2wtomz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1493)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: simply do:


``` golang
_, err := sqlDB.Exec("BEGIN')
require.NoError(t, err)
```


Conditional err check is not necessary with `require` library
</blockquote></details>

Removed, along with similar redundant error checks.
___
*[pkg/sql/conn_executor_test.go, line 1511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv2Wnc0zLJ7yQIMklv:-MuvZC5IBlajjohQZfPZ:b5lxn94) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1511)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Correct me if I'm wrong, I feel the verification logic can live in the same unit test instead of two? (Otherwise we are spinning up two test servers instead of one) 
</blockquote></details>

@azhng Yes. I've combined these into the same unit test (especially since the test to check internal transactions and internal statements are effectively identical). Effectively just added the external statement case into the original open transaction test. 
@jocrl I think simply having assertions to both transaction and statement counts after each statement execution should suffice. I considered adding the case where we execute an internal statement within an external transaction, but I think it would effectively be the same test as when we execute an internal statement outside of an external transaction. I don't think we can execute an external statement within an internal transaction, but could be wrong. Probably worth double checking my thoughts here @azhng


<!-- Sent from Reviewable.io -->

2022-02-02 19:34 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv62sOAG5RvV2Iqa1i):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this should have a release note, since you're changing the behaviour that users can notice
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-02 21:52 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/ts/catalog/chart_catalog.go, line 2115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muw7BlACNwetQ7O8Xz2:-Muw7BlBElIW2XC5wNa2:b-2cmh2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/ts/catalog/chart_catalog.go#L2115)):*
> ```Go
> 					"sql.statements.active.internal",
> 				},
> 				AxisLabel: "Transactions",
> ```

The `AxisLabel` looks off
___
*[pkg/sql/conn_executor_test.go, line 1406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv13e_C_Gnr7DWnlwi:-MuwJaOy369BVMMF9fV1:b7usx1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1406)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

From my discussions with @azhng, an "internal" transaction is any transaction executed by the `InternalExecutor`. Complementary, an external transaction is any transaction executed by any external executor (i.e. `sql.DB.beginTxn(...)`).

What's also worth knowing is that there are also "implicit" and "explicit" transactions. "Explicit" transactions occur when a user (explicitly) begins and ends a transaction with `BEGIN` and `COMMIT`. An "implicit" transaction is any single statement executed outside of an explicit transaction context (i.e. `SELECT city from rides;` is executed as a single statement, but becomes an "implicit" transaction under the hood, thereby carrying the same serializable guarantees a transaction provides).

@azhng just want to make sure this is correct
</blockquote></details>

Yep, your understanding is correct. Basically we can summarize it into a 2x2 table.

|   | External Txn (or just regular Txns issued by the user) | Internal Txn   |
|---|-------------------|--------------------|
|Implicit Txn| Using regular `connExecutor` without `BEGIN`/`COMMIT`       | Using `InternalExecutor`, where `txn` param is `nil`|
|Explicit Txn | Using regular `connExecutor` with `BEGIN`/`COMMIT`      | Using `InternalExecutor`, where `txn` param is not `nil` |
___
*[pkg/sql/conn_executor_test.go, line 1511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv2Wnc0zLJ7yQIMklv:-MuwPCXI6oFD_genY0HT:b-yw70z4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1511)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

@azhng Yes. I've combined these into the same unit test (especially since the test to check internal transactions and internal statements are effectively identical). Effectively just added the external statement case into the original open transaction test. 
@jocrl I think simply having assertions to both transaction and statement counts after each statement execution should suffice. I considered adding the case where we execute an internal statement within an external transaction, but I think it would effectively be the same test as when we execute an internal statement outside of an external transaction. I don't think we can execute an external statement within an internal transaction, but could be wrong. Probably worth double checking my thoughts here @azhng
</blockquote></details>

Yes. A transaction is bound to an executor. So if a transaction is an external transaction, I don't think we have any codepath that would execute an internal query in the context of the external transaction. And the mere thoughts of executing user-supplied query in an internal executor is scaring me, since we often override the security settings when we use internal executor. 
___
*[pkg/sql/conn_executor_test.go, line 1417 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwMrps-BMS2w3wbO8c:-MuwMrps-BMS2w3wbO8d:b-l1gzwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1417)):*
> ```Go
> 	sqlServer := s.SQLServer().(*sql.Server)
> 	waitingQuery := `SELECT pg_sleep(60)`
> 	selectQueryInternal := `SELECT query_id FROM crdb_internal.cluster_queries WHERE query = '` + waitingQuery + `'`
> ```

minor nit: `selectQueryIDInternal` 
___
*[pkg/sql/conn_executor_test.go, line 1418 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwMBSjCIS2P-Yws8tG:-MuwMBSjCIS2P-Yws8tH:b-qkgo1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1418)):*
> ```Go
> 	waitingQuery := `SELECT pg_sleep(60)`
> 	selectQueryInternal := `SELECT query_id FROM crdb_internal.cluster_queries WHERE query = '` + waitingQuery + `'`
> 	selectQueryExternal := `SELECT query_id FROM [SHOW CLUSTER STATEMENTS] WHERE query = '` + waitingQuery + `'`
> ```

minor nit, up to you if you wanna do this: there are couple ways you can do this `SHOW .. STATEMENTS` query,

for querying the external statements, you can do `[SHOW STATEMENTS]` and for both internal and external statements you can do `SHOW ALL STATEMENTS`. 
___
*[pkg/sql/conn_executor_test.go, line 1458 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwNATK-NqCWAzjQdaf:-MuwNATK-NqCWAzjQdag:b-64smty) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1458)):*
> ```Go
> 	require.Equal(t, int64(0), sqlServer.Metrics.EngineMetrics.SQLActiveStatements.Value())
> 
> 	_, err := sqlServer.GetExecutorConfig().InternalExecutor.ExecEx(
> ```

Hmm I wonder if the cancellation query can be issued using a regular SQL Connection. It might makes the code here a bit less verbose?
___
*[pkg/sql/conn_executor_test.go, line 1465 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwNLby26i49Go-gwwb:-MuwNLbz3YBm5txY2eOi:bjdvzu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1465)):*
> ```Go
> 		cancelQueryInternal,
> 	)
> 	require.NoError(t, err, "executing %s  ", cancelQueryInternal)
> ```

The third param in `require.NoError` is the error message the test runner prints out if the validation condition fails. It usually goes in the form of `expect .... to happen, but <something else unexpected happened>` . So here, it would be something like "expect the waiting query to be successfully cancelled, but it was not"
___
*[pkg/sql/conn_executor_test.go, line 1473 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwOSjs3JHCdo8m3Z-j:-MuwOSjs3JHCdo8m3Z-k:bk7pdny) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1473)):*
> ```Go
> 			nil,
> 			sessiondata.InternalExecutorOverride{User: security.RootUserName()},
> 			selectQueryInternal,
> ```

Hmm seems like this is to test whether the previous `pg_sleep()` has been properly cancelled yet. I feel this doesn't need to be wrapped in a `SucceedsWithin` since we know for sure at this point the query *must* be cancelled. Also I feel there's probably no need to use the internal executor here.
___
*[pkg/sql/conn_executor_test.go, line 1536 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwPrYt2zE4furLgyN7:-MuwPrYt2zE4furLgyN8:b-tdmxqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1536)):*
> ```Go
> 	require.NoError(t, err, "executing %s  ", cancelQueryExternal)
> 
> 	testutils.SucceedsWithin(t, func() error {
> ```

same here, I feel the retry loop is probably not necessary.
___
*[pkg/sql/conn_executor_test.go, line 1545 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwPwJG5uBIjd5Gipxu:-MuwPwJG5uBIjd5Gipxv:bpazwe5) ([ [...]

2022-02-03 22:27 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/ts/catalog/chart_catalog.go, line 2115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muw7BlACNwetQ7O8Xz2:-Mv0eGOGEQV9Cs-zXumY:b-39v3cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/ts/catalog/chart_catalog.go#L2115)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

The `AxisLabel` looks off
</blockquote></details>

Whoops, fixed.
___
*[pkg/sql/conn_executor_test.go, line 1417 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwMrps-BMS2w3wbO8c:-Mv0eMWL43j_03IEmZUV:bm8x6iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1417)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

minor nit: `selectQueryIDInternal` 
</blockquote></details>

The query now uses `count(*)` to see if the query is active (i.e. exists in `crdb_internal.cluster_queries` or `SHOW STATEMENTS`).

Renamed to `selectInternalQueryActive`/`selectExternalQueryActive`.
___
*[pkg/sql/conn_executor_test.go, line 1418 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwMBSjCIS2P-Yws8tG:-Mv0f9207n2hfezssv27:beuh98m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1418)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

minor nit, up to you if you wanna do this: there are couple ways you can do this `SHOW .. STATEMENTS` query,

for querying the external statements, you can do `[SHOW STATEMENTS]` and for both internal and external statements you can do `SHOW ALL STATEMENTS`. 
</blockquote></details>

Changed to use `[SHOW STATEMENTS]` instead of `[SHOW CLUSTER STATEMENTS]`.
___
*[pkg/sql/conn_executor_test.go, line 1458 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwNATK-NqCWAzjQdaf:-Mv0fY4nBhXvqGAUjeOY:b9w64pe) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1458)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm I wonder if the cancellation query can be issued using a regular SQL Connection. It might makes the code here a bit less verbose?
</blockquote></details>

No longer need cancellation queries now that we're using contention to hang queries instead of `pg_sleep()`.
___
*[pkg/sql/conn_executor_test.go, line 1465 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwNLby26i49Go-gwwb:-Mv0fwT--C6ubXbx0hGi:blquwvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1465)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

The third param in `require.NoError` is the error message the test runner prints out if the validation condition fails. It usually goes in the form of `expect .... to happen, but <something else unexpected happened>` . So here, it would be something like "expect the waiting query to be successfully cancelled, but it was not"
</blockquote></details>

Changed to use the `expect... but` format for `require.NoError`.
___
*[pkg/sql/conn_executor_test.go, line 1473 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwOSjs3JHCdo8m3Z-j:-Mv0g5pbCPNLHha7R1Od:b4qbars) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1473)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm seems like this is to test whether the previous `pg_sleep()` has been properly cancelled yet. I feel this doesn't need to be wrapped in a `SucceedsWithin` since we know for sure at this point the query *must* be cancelled. Also I feel there's probably no need to use the internal executor here.
</blockquote></details>

Now use contention to make a query hang instead of `pg_sleep()`, no longer cancel queries.
___
*[pkg/sql/conn_executor_test.go, line 1536 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwPrYt2zE4furLgyN7:-Mv0gNbfBhRhvmbmbSB7:bjxz7ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1536)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

same here, I feel the retry loop is probably not necessary.
</blockquote></details>

With the contention logic, we now check that the queries are no longer hanging once we `COMMIT` the transaction and the contention is resolved.
___
*[pkg/sql/conn_executor_test.go, line 1545 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-MuwPwJG5uBIjd5Gipxu:-Mv0gXXl3gWUBr1DOer6:b-c1mhah) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba04d7f200001a33d3f0ad54e415d06fe307efbb/pkg/sql/conn_executor_test.go#L1545)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Btw have you tried to use `sqlutil.MakeSQLRunner()`? They have a couple really neat interfaces (e.g. `QueryStr()`) that can make a lot of these `row.Scan()` go away. 
</blockquote></details>

Definitely useful, changes use `SQLRunner`, ty :smile: 


<!-- Sent from Reviewable.io -->

2022-02-04 17:31 UTC, maryliag reviewed
> Reviewed 2 of 7 files at r1, 2 of 5 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/sql/exec_util.go, line 786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv0UqzAc-QMznBTuTu:-Mv4m8ri3X5lWMtjwcMk:bknea9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/exec_util.go#L786)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Active statements was already being accounted for but included both internal & external active statements (`sql.distsql.queries.active`). The counting was being done at the SQL engine, which didn't provide enough context to determine whether the statement was internal/external. The introduced `sql.statements.active` counts active statements at a higher layer where internal/external context is available, and used to only counts external active statements. 
</blockquote></details>

Can you on the help of both metrics (active stmt and open queries) that they're filtering out internal?


<!-- Sent from Reviewable.io -->

2022-02-04 17:32 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, and @THardy98)

___
*[pkg/sql/exec_util.go, line 786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv0UqzAc-QMznBTuTu:-Mv4mnRB4_zegYn2CPNI:b4m7s1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/exec_util.go#L786)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Can you on the help of both metrics (active stmt and open queries) that they're filtering out internal?
</blockquote></details>

*can you add on...


<!-- Sent from Reviewable.io -->

2022-02-04 17:46 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @maryliag)

___
*[pkg/sql/exec_util.go, line 786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv0UqzAc-QMznBTuTu:-Mv4q3x16MW0sMHcpQ1Y:br31s0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/exec_util.go#L786)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

*can you add on...
</blockquote></details>

In their tooltips?


<!-- Sent from Reviewable.io -->

2022-02-04 17:49 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @jocrl, @kevin-v-ngo, and @maryliag)

___
*[pkg/sql/exec_util.go, line 786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv0UqzAc-QMznBTuTu:-Mv4qI5VD21bcHFN5DO3:b-l698gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/exec_util.go#L786)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

In their tooltips?
</blockquote></details>

yes, so something like
`Help:        "Number of non-internal SQL statements currently active",`

not sure if we decided on usage of non-internal vs external. Any opinios @kevin-v-ngo  or @annebirzin ?


<!-- Sent from Reviewable.io -->

2022-02-04 17:53 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @jocrl, @kevin-v-ngo, and @maryliag)

___
*[pkg/sql/exec_util.go, line 786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv0UqzAc-QMznBTuTu:-Mv4rTV3BdlaLCIrlS3w:boenfp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/exec_util.go#L786)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

yes, so something like
`Help:        "Number of non-internal SQL statements currently active",`

not sure if we decided on usage of non-internal vs external. Any opinios @kevin-v-ngo  or @annebirzin ?
</blockquote></details>

Clarified that we are keeping track of `non-internal` active statements/open transactions in the metrics metadata `Help`.


<!-- Sent from Reviewable.io -->

2022-02-04 18:02 UTC, kevin-v-ngo commented
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @jocrl, @kevin-v-ngo, and @maryliag)
> 
> _[pkg/sql/exec_util.go, line 786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv0UqzAc-QMznBTuTu:-Mv4qI5VD21bcHFN5DO3:b-l698gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/exec_util.go#L786)):_
> 
> Previously, THardy98 (Thomas Hardy) wrote…
> yes, so something like `Help: "Number of non-internal SQL statements currently active",`
> 
> not sure if we decided on usage of non-internal vs external. Any opinios @kevin-v-ngo or @Annebirzin ?

We can say, "The total number of running SQL statements across all nodes excluding internal statements." Adding @stbof for any other suggestions 

External seems odd ('user' would be better here) and i don't see us using the term anywhere: https://www.cockroachlabs.com/docs/stable/ui-statements-page.html#filter

2022-02-07 15:07 UTC, jocrl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @jocrl, @kevin-v-ngo, @maryliag, @stbof, and @THardy98)

___
*[pkg/sql/conn_executor_test.go, line 1511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv2Wnc0zLJ7yQIMklv:-MvJhgBn5xaqDVtJzyJq:b45o6v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/conn_executor_test.go#L1511)):*
> I think simply having assertions to both transaction and statement counts after each statement execution should suffice.
Ah makes sense, thanks!


<!-- Sent from Reviewable.io -->

2022-02-09 15:49 UTC, maryliag approved these changes
Great! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 
btw, can you update the title on the PR from `external` to `user` to align with our decision of naming convention? 

> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-:-MvUA4-RBRsQkunAucjP:b5t577x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @stbof, and @THardy98)



<!-- Sent from Reviewable.io -->

2022-02-09 15:52 UTC, THardy98 reviewed
Updated the PR title from `external` to `user`. Will do so for the commit message as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-:-MvUAg6l1oQJiy6LIdxW:b-u20al1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @stbof, and @THardy98)

___
*[pkg/sql/exec_util.go, line 786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-Muv0UqzAc-QMznBTuTu:-MvUAmpW20oGK7bmoPmr:bjqrmg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d5c7266d77ac5b2fa59e315915750168c8093d2/pkg/sql/exec_util.go#L786)):*
<details><summary><i>Previously, kevin-v-ngo wrote…</i></summary><blockquote>

We can say, "The total number of running SQL statements across all nodes." Adding @stbof for any other suggestions 

External seems odd ('user' would be better here) and i don't see us using the term anywhere: https://www.cockroachlabs.com/docs/stable/ui-statements-page.html#filter

FYI - no other charts quality internal vs user so i'd keep it consistent for now. 

</blockquote></details>

Changed to "user" instead of "external" and "non-internal"


<!-- Sent from Reviewable.io -->

2022-02-09 21:30 UTC, Azhng approved these changes
Nice! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75815#-:-MvVO9F_5jWohL9d9icF:bwuv9up)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @stbof, and @THardy98)



<!-- Sent from Reviewable.io -->

2022-02-09 21:30 UTC, THardy98 commented
TFTR!

bors r+

2022-02-10 00:03 UTC, merged