sql: implement basic row-level TTL job
cockroachdb/cockroach pull request #75840
Opened 2022-02-02 02:53 UTC by otan

Only last two commits matter.

2022-02-02 02:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/75840)
<!-- Reviewable:end -->

2022-02-02 17:47 UTC, postamar reviewed
I gave this an admittedly superficial look, because I'm not a scheduled jobs expert. For what it's worth, it looks good to me.

> Reviewed 4 of 4 files at r1, 11 of 11 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-:-MuvVBH2CWeZsVue7nol:bv4wf36)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @otan, and @rafiss)

___
*[pkg/sql/row_level_ttl.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvRiOl6t1ujMFuriUt:-MuvRiOl6t1ujMFuriUu:b1satih) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L58)):*
> ```Go
> 	// TODO(#75428): feature flag check, ttl pause check.
> 	// TODO(#75428): detect if the table has a schema change, in particular,
> 	// a PK change, a DROP TTL or a DROP TABLE should early exit the job.
> ```

Please bear in mind that some of these (PK change, DROP TABLE) may be done by the new schema changer in this release.
___
*[pkg/sql/catalog/tabledesc/ttl.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvMY6J6MMUk3N5XcOn:-MuvMY6J6MMUk3N5XcOo:b8wi9b8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d22e938f1480a58abb908055c32e56d240e2ade4/pkg/sql/catalog/tabledesc/ttl.go#L20)):*
> ```Go
> // TTLDefaultExpirationColumnName is the column name representing the expiration
> // column for TTL.
> const TTLDefaultExpirationColumnName = "crdb_internal_expiration"
> ```

Can you put this in the `colinfo` package, near its other friends like `const MVCCTimestampColumnName = "crdb_internal_mvcc_timestamp"`?
___
*[pkg/sql/ttlpb/ttlpb.proto, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvQDrN7QteSQDylC7M:-MuvQDrN7QteSQDylC7N:b-rw2tkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/28056ce94feee8f18d1adb687d685bff1ae7bc80/pkg/sql/ttlpb/ttlpb.proto#L23)):*
> ```protobuf
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb.ID"
>   ];
> }
> ```

This proto could conceivably be defined in `catpb` instead. @ajwerner thoughts?
___
*[pkg/sql/logictest/testdata/logic_test/row_level_ttl, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvMzCT17PVlmh-TvQJ:-MuvMzCT17PVlmh-TvQK:b73ylii) ([raw file](https://github.com/cockroachdb/cockroach/blob/d22e938f1480a58abb908055c32e56d240e2ade4/pkg/sql/logictest/testdata/logic_test/row_level_ttl#L22)):*
> ```
>                                                    crdb_internal_expiration TIMESTAMPTZ NOT VISIBLE NOT NULL DEFAULT current_timestamp():::TIMESTAMPTZ + '00:10:00':::INTERVAL ON UPDATE current_timestamp():::TIMESTAMPTZ + '00:10:00':::INTERVAL,
>                                                    CONSTRAINT tbl_pkey PRIMARY KEY (id ASC),
>                                                    FAMILY fam_0_id_text_crdb_internal_expiration (id, text, crdb_internal_expiration)
> ```

Are we cool with this column name making it into the family's name?


<!-- Sent from Reviewable.io -->

2022-02-02 18:27 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @otan, @postamar, and @rafiss)

___
*[pkg/sql/row_level_ttl.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Muvg3l_8NZ7DoCfOsLa:-Muvg3l_8NZ7DoCfOsLb:bv2wsjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L45)):*
> ```Go
> 
> // Resume implements the jobs.Resumer interface.
> func (t rowLevelTTLResumer) Resume(ctx context.Context, execCtx interface{}) error {
> ```

relatively strong preference for this job definition and its business logic to exist in packages outside of sql. Maybe `sql/ttljob`?
___
*[pkg/sql/ttlpb/ttlpb.proto, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvQDrN7QteSQDylC7M:-MuvfmfpE9hOX1fFTf7x:b-x87jim) ([raw file](https://github.com/cockroachdb/cockroach/blob/28056ce94feee8f18d1adb687d685bff1ae7bc80/pkg/sql/ttlpb/ttlpb.proto#L23)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This proto could conceivably be defined in `catpb` instead. @ajwerner thoughts?
</blockquote></details>

Yes, preference for `catpb`


<!-- Sent from Reviewable.io -->

2022-02-02 18:43 UTC, ajwerner commented
Ideally we'd be able to validate the scheduled job existing, but we lack the infrastructure for that right now. I think we should:

1) File an issue to track validating scheduled jobs as part of descriptor validatioN
2) Write some builtins which scan the descriptors and do this validation
3) Write some builtins which can create the scheduled jobs you might expect if they don't exist.

As I reflect on this whole project, that link-between the descriptor and the scheduled job, is the thing I worry most about.

2022-02-02 19:29 UTC, postamar commented
Agreed. Right now the only jobs validation we have is via `cockroach debug doctor` or via `crdb_internal.invalid_objects`.

2022-02-02 19:52 UTC, miretskiy reviewed
> Reviewed 2 of 4 files at r1, 7 of 11 files at r2, 4 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @otan, @postamar, and @rafiss)

___
*[-- commits, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Muv_kG3BEftrYEVrAa-):*
Do none of these commits need release notes?
___
*[pkg/sql/row_level_ttl.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Muvg3l_8NZ7DoCfOsLa:-MuvnVGg4WMi0xSyPh89:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L45)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

relatively strong preference for this job definition and its business logic to exist in packages outside of sql. Maybe `sql/ttljob`?
</blockquote></details>

+1
___
*[pkg/sql/row_level_ttl.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvzGWrD9GXDA6-VJAY:-MuvzGWs1spWf3fpY4iK:btarer8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L57)):*
> ```Go
> 
> 	// TODO(#75428): feature flag check, ttl pause check.
> 	// TODO(#75428): detect if the table has a schema change, in particular,
> ```

Pretty sure we'd need another todo here -- make this a dist sql flow job -- there is just no way it will scale to reasonably sized tables.
___
*[pkg/sql/row_level_ttl.go, line 82 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvqequEuJwgDNi3G_q:-MuvqequEuJwgDNi3G_r:b-djp0pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L82)):*
> ```Go
> 	const (
> 		selectBatchSize = 500
> 		deleteBatchSize = 100
> ```

Rule of magic constants applies?  Do you think these should be cluster settings?



_Code quote:_
```Go
		selectBatchSize = 500
		deleteBatchSize = 100
```
___
*[pkg/sql/row_level_ttl.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvyEFM3VvjPf07lgx5:-MuvyEFM3VvjPf07lgx6:b-n9uua7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L85)):*
> ```Go
> 	)
> 
> 	// TODO(#75428): break this apart by ranges to avoid multi-range operations.
> ```

I wonder if just using the "scan" portion of rangefeed library might address the above todo, add
support for parallelism (and memory monitoring), and be a bit more efficient vs running selects?
Of course you'd have to filter rows yourself; but at the same time you could also control pacing,
priority, etc...

Of course the rangefeed library assumes that after rangefeed you'd want to run the actual feed portion; 
but that can be easily remediated.
@ajwerner thoughts?
___
*[pkg/sql/row_level_ttl.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvpiAR1jZkXyWm9Noh:-MuvpiAR1jZkXyWm9Noi:b-5fds2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L253)):*
> ```Go
> 	})
> 	// TODO(#75189): allow user to configure schedule.
> 	if err := sj.SetSchedule("@hourly"); err != nil {
> ```

getting a bit worried that we now have multiple scheduled jobs w/ default set to hourly.
___
*[pkg/sql/row_level_ttl.go, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvqUohAFusLYDC9cOS:-MuvqUohAFusLYDC9cOT:bu5ej8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L277)):*
> ```Go
> 
> type rowLevelTTLMetrics struct {
> 	*jobs.ExecutorMetrics
> ```

Probably want to add more metrics (e.g. number of deleted rows, etc)?
Or a TODO?
___
*[pkg/sql/row_level_ttl.go, line 298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvqF0NDfZ42sDpjQyz:-MuvqF0NDfZ42sDpjQz-:bzbno00) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L298)):*
> ```Go
> 			"cannot drop row level TTL schedule",
> 		),
> 		`use ALTER TABLE ... RESET (expire_after) instead`,
> ```

Do we drop this schedule when this happens?


<!-- Sent from Reviewable.io -->

2022-02-02 19:56 UTC, miretskiy commented
> As I reflect on this whole project, that link-between the descriptor and the scheduled job, is the thing I worry most about.

I agree that this might be undesirable.  Auto stats compaction job has a code that verifies the job exists (runs every 6 hours I believe).  Here, we'd want to have a job for each table w/ ttl set.  I guess a dumb go routine to query descriptors, see if descriptor has ttl, and just create schedule if not exist....

2022-02-02 21:07 UTC, otan reviewed
I will track the validation in the existing meta (mega) issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-:-Muw7u165W_jzR3Rjrqy:bjcqfif)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, @postamar, and @rafiss)

___
*[-- commits, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Muv_kG3BEftrYEVrAa-):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do none of these commits need release notes?
</blockquote></details>

was planning to give a commit with a giant release note at the end, because otherwise it'd be noise on every TTL component i add
___
*[pkg/sql/row_level_ttl.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Muvg3l_8NZ7DoCfOsLa:-MuwFgvP3GkRDP_On_jk:b1apvdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L45)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

+1
</blockquote></details>

i put the job def out, the scheduled job needs to stay because of dependencies on planner and some other circular deps on the sql package if i move it out.
___
*[pkg/sql/row_level_ttl.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvzGWrD9GXDA6-VJAY:-Muw0OsVBCAJrd9bNifw:b-1w5svh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L57)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Pretty sure we'd need another todo here -- make this a dist sql flow job -- there is just no way it will scale to reasonably sized tables.
</blockquote></details>

not sure what this is, but haven't heard of this. there are some optimisations upcoming, but that's a lot of extra overhead to add for now.
___
*[pkg/sql/row_level_ttl.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvRiOl6t1ujMFuriUt:-Muw0Nyx6GclgfUOQluN:b-gr4f05) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L58)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Please bear in mind that some of these (PK change, DROP TABLE) may be done by the new schema changer in this release.
</blockquote></details>

noted. there will be PRs for this so i guess you'll see them :')
___
*[pkg/sql/row_level_ttl.go, line 82 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvqequEuJwgDNi3G_q:-Muw0oR-CIC4fSY294LT:bkvhteo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L82)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Rule of magic constants applies?  Do you think these should be cluster settings?
</blockquote></details>

these will be set on the storage parameter syntax (`CREATE TABLE ... WITH ( ... ) `), it requires a bit of plumbing and slated for a TODO.
___
*[pkg/sql/row_level_ttl.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvyEFM3VvjPf07lgx5:-Muw0w8r4Q452SaqyEkd:b-kak68k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L85)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I wonder if just using the "scan" portion of rangefeed library might address the above todo, add
support for parallelism (and memory monitoring), and be a bit more efficient vs running selects?
Of course you'd have to filter rows yourself; but at the same time you could also control pacing,
priority, etc...

Of course the rangefeed library assumes that after rangefeed you'd want to run the actual feed portion; 
but that can be easily remediated.
@ajwerner thoughts?
</blockquote></details>

does this handle secondary indexes? if not it is currently a non-starter.
___
*[pkg/sql/row_level_ttl.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvpiAR1jZkXyWm9Noh:-Muw3_ea48AM2VuvAc2i:bju5u4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L253)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

getting a bit worried that we now have multiple scheduled jobs w/ default set to hourly.
</blockquote></details>

is the worry here because it is unchartered? i'm not sure i can alleviate this unfortunately.
___
*[pkg/sql/row_level_ttl.go, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvqUohAFusLYDC9cOS:-Muw3nwE7OQkSTqr9bcZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L277)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Probably want to add more metrics (e.g. number of deleted rows, etc)?
Or a TODO?
</blockquote></details>

Done.
___
*[pkg/sql/row_level_ttl.go, line 298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvqF0NDfZ42sDpjQyz:-Muw12_f-gTgHAdszB5F:bkafvs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L298)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we drop this schedule when this happens?
</blockquote></details>

we will, but not yet.
___
*[pkg/sql/ttlpb/ttlpb.proto, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvQDrN7QteSQDylC7M:-Muw2YuY6L6y55771rW9:b-qyczwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/28056ce94feee8f18d1adb687d685bff1ae7bc80/pkg/sql/ttlpb/ttlpb.proto#L23)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yes, preference for `catpb`
</blockquote></details>

Import cycle for the casttype:

```
package github.com/cockroachdb/cockroach/pkg/cmd/cockroach-short
	imports github.com/cockroachdb/cockroach/pkg/ccl
	imports github.com/cockroachdb/cockroach/pkg/ccl/backupccl
	imports github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backupresolver
	imports github.com/cockroachdb/cockroach/pkg/sql
	imports github.com/cockroachdb/cockroach/pkg/cloud
	imports github.com/cockroachdb/cockroach/pkg/blobs
	imports github.com/cockroachdb/cockroach/pkg/rpc
	imports github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkeys
	imports github.com/cockroachdb/cockroach/pkg/sql/catalog
	imports github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb
	imports github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb
	imports github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb: import cycle not allowed
pkg/sql/row_level_ttl.go:25:2: cannot find package "." in:
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catpb
gmake: *** [Makefile:1006: cockroachshort] Error 1
gmake: *** Waiting for unfinished jobs....
bin/prereqs: failed to import ./pkg/cmd/docgen: [-: import cycle not allowed: import stack: [github.com/cockroachdb/cockroach/pkg/cmd/docgen github.com/cockroachdb/cockroach/pkg/sql/sem/builtins github.com/cockroachdb/cockroach/pkg/config/zonepb github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb]]
gmake: *** [Makefile:1812: bin/docgen] Error 1
```

how strong is this preference? it's the casttype so i *could* still.
___
*[pkg/sql/logictest/testdata/logic_test/row_level_ttl, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvMzCT17PVlmh-TvQJ:-Muw1DBT2WGtAWycNAzt:b-1jihxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d22e938f1480a58abb908055c32e56d240e2 [...]

2022-02-02 21:21 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @otan, @postamar, and @rafiss)

___
*[pkg/sql/row_level_ttl.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Muvg3l_8NZ7DoCfOsLa:-MuwHj6_CHwE1KRi2o_m:b-qmyo4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L45)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i put the job def out, the scheduled job needs to stay because of dependencies on planner and some other circular deps on the sql package if i move it out.
</blockquote></details>

Where is the planner dependency? I don't see it. If it's the testing knobs, here's my actual preference:

```
sql/ttl -- define interfaces and knobs as you need them, sql and the subpackages can depend on this
sql/ttl/ttljob -- define the job execution itself
sql/ttl/ttlexecutor -- define the scheduled job
```
___
*[pkg/sql/row_level_ttl.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvyEFM3VvjPf07lgx5:-MuwHWJM5SnN1cssK6Ic:bqtsejq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L85)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

does this handle secondary indexes? if not it is currently a non-starter.
</blockquote></details>

I think we definitely like letting the execution engine handle this. 
___
*[pkg/sql/ttlpb/ttlpb.proto, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvQDrN7QteSQDylC7M:-MuwITUV3b9wAzHGsTLN:b-vnbelk) ([raw file](https://github.com/cockroachdb/cockroach/blob/28056ce94feee8f18d1adb687d685bff1ae7bc80/pkg/sql/ttlpb/ttlpb.proto#L23)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Import cycle for the casttype:

```
package github.com/cockroachdb/cockroach/pkg/cmd/cockroach-short
	imports github.com/cockroachdb/cockroach/pkg/ccl
	imports github.com/cockroachdb/cockroach/pkg/ccl/backupccl
	imports github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backupresolver
	imports github.com/cockroachdb/cockroach/pkg/sql
	imports github.com/cockroachdb/cockroach/pkg/cloud
	imports github.com/cockroachdb/cockroach/pkg/blobs
	imports github.com/cockroachdb/cockroach/pkg/rpc
	imports github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkeys
	imports github.com/cockroachdb/cockroach/pkg/sql/catalog
	imports github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb
	imports github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb
	imports github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb: import cycle not allowed
pkg/sql/row_level_ttl.go:25:2: cannot find package "." in:
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catpb
gmake: *** [Makefile:1006: cockroachshort] Error 1
gmake: *** Waiting for unfinished jobs....
bin/prereqs: failed to import ./pkg/cmd/docgen: [-: import cycle not allowed: import stack: [github.com/cockroachdb/cockroach/pkg/cmd/docgen github.com/cockroachdb/cockroach/pkg/sql/sem/builtins github.com/cockroachdb/cockroach/pkg/config/zonepb github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb]]
gmake: *** [Makefile:1812: bin/docgen] Error 1
```

how strong is this preference? it's the casttype so i *could* still.
</blockquote></details>

Yeah, because you've got to change the ID to `catid.DescID`, `type descpb.ID = catid.DescID`


<!-- Sent from Reviewable.io -->

2022-02-02 21:49 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @miretskiy, @postamar, and @rafiss)

___
*[pkg/sql/row_level_ttl.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Muvg3l_8NZ7DoCfOsLa:-MuwNTWM8LA5TDj-XOK-:bsxpvam) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L45)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Where is the planner dependency? I don't see it. If it's the testing knobs, here's my actual preference:

```
sql/ttl -- define interfaces and knobs as you need them, sql and the subpackages can depend on this
sql/ttl/ttljob -- define the job execution itself
sql/ttl/ttlexecutor -- define the scheduled job
```
</blockquote></details>

the bit that was `p.(*planner).ExecCfg().JobRegistry`

adding `ExecCfg` as an interface method still relied on `*sql.ExecutorConfig`, which would be a circular dep as the sql package would need to call this package...

but i've made a new method on the planner called `JobRegistry` which just returns the JobRegistry component which resolved that.

dir structure fixed up
___
*[pkg/sql/ttlpb/ttlpb.proto, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvQDrN7QteSQDylC7M:-MuwNQaNEEv8x3iKs-HV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28056ce94feee8f18d1adb687d685bff1ae7bc80/pkg/sql/ttlpb/ttlpb.proto#L23)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yeah, because you've got to change the ID to `catid.DescID`, `type descpb.ID = catid.DescID`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-02 22:14 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @otan, @postamar, and @rafiss)

___
*[pkg/sql/row_level_ttl.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Muvg3l_8NZ7DoCfOsLa:-MuwRlbs3hgBKXM3ZHX4:bazknxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L45)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

the bit that was `p.(*planner).ExecCfg().JobRegistry`

adding `ExecCfg` as an interface method still relied on `*sql.ExecutorConfig`, which would be a circular dep as the sql package would need to call this package...

but i've made a new method on the planner called `JobRegistry` which just returns the JobRegistry component which resolved that.

dir structure fixed up
</blockquote></details>

I think the way you did it is maybe roundabout from how I'd do it. It's too much fighting the pattern and it smells. The only reason you're importing the `ttlschedule` package in sql is for `NewRowLevelTTLScheduledJob` but there's nothing in there which needs to have anything to do with the implementation of the executor. Separate the executor from that one function and you can safely import `sql`. Then you can have your whole `PlanHookState` and what not. 
___
*[pkg/sql/row_level_ttl.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvzGWrD9GXDA6-VJAY:-MuwUzZu--TJUwpO89dW:b-u0jqoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L57)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

not sure what this is, but haven't heard of this. there are some optimisations upcoming, but that's a lot of extra overhead to add for now.
</blockquote></details>

I suspect yevgeniy is right that on a 100 node cluster you're deleter is not going to be able to keep up without utilizing more nodes and parallelizing its scanning. 


<!-- Sent from Reviewable.io -->

2022-02-02 22:37 UTC, miretskiy commented
> not sure what this is, but haven't heard of this. there are some optimisations upcoming, but that's a lot of extra overhead to add for now.

Well, you're running this on a single node, issuing repeated selects and repeated deletes.  That assumes that this node can keep up with the rate of updates to the table; which it may not if the table is very large. I'm okay delaying this, but as I said, I just don't see it scaling to a large table sizes.  

> is the worry here because it is unchartered? i'm not sure i can alleviate this unfortunatel

I'm worried because @hourly doesn't add any jitter automatically.  I think we should.  Up to this point we let operators do this manually (and arguably for backups when you say @hourly you want your backups to start on top of the hour).  But for these kinds of jobs, perhaps an "jitter" option maybe added to create schedule so that @hourly doesn't mean on top of the hour.  Maybe a jobs system issue?

> re rangefeeds: does this handle secondary indexes? if not it is currently a non-starter.

Yes, I believe it does.  It just gets the span to run against -- so, just give it a secondary index.

2022-02-03 01:54 UTC, otan commented
> Well, you're running this on a single node, issuing repeated selects and repeated deletes. That assumes that this node can keep up with the rate of updates to the table; which it may not if the table is very large. I'm okay delaying this, but as I said, I just don't see it scaling to a large table sizes.

is there a way of sharding out jobs as you describe?

> I'm worried because `@hourly` doesn't add any jitter automatically.

hmmmm, i mean it will be configurable by the user but you have a fair point. didn't realise `@hourly` meant on the hour, thought it'd be an hour since invocation :P. it would be cool if schedules could take jitter.

2022-02-03 10:10 UTC, otan commented
i wonder if we can get away with sharding the job...

2022-02-03 13:00 UTC, miretskiy commented
> is there a way of sharding out jobs as you describe? grepping "dist sql job" didn't really get me anywhere
> i can tell you it doesn't do a great job atm with large tables from my initial prototyping (there is a possibility that it won't catch up)
> i wonder if we can get away with sharding the job... (i.e. option to spin up N jobs for every desc)

I'm pretty sure it won't catchup.  Effectively, you need to do a table scan every hour -- that alone might not complete w/current implementation. I had in mind something similar to e.g. changefeed_dist.go, where you split your span into subspans, based on locality of those spans (this can be done by schedulled job).  The job then starts coordinator on any node, and workers on each node hosting part(s) of the table; you then use Scan (or rangefeed library, as I suggested), to scan each row in parallel -- parse data, and build your delete batches.

2022-02-03 13:12 UTC, dt commented
This seems like it is rehashing a lot of the design phase discussions for how we'd incrementally improve the performance of this over time:
a) make a distsql processor that runs deletes and then let partition spans farm out the the deletes to run in parallel and be closer to the rows
b) introduce strict filtering in table reader then allow inconsistent indexes, and start doing deletes _per index_ instead of per table, to make them 1PC
c) add ttl predicate pushdown to deleterange

I thought we'd said we were _starting_ with a simple single `DELETE WHERE` and getting everything else working, the UX hammered out, etc and then, when we see indications that it can't keep up even when dialed up, that's when we'd work on iterative improvements in the implementation's performance under the hood?

2022-02-03 13:21 UTC, miretskiy commented
> This seems like it is rehashing a lot of the design phase discussions for how we'd incrementally improve the performance of this over time: a) make a distsql processor that runs deletes and then let partition spans farm out the the deletes to run in parallel and be closer to the rows b) introduce strict filtering in table reader then allow inconsistent indexes, and start doing deletes _per index_ instead of per table, to make them 1PC c) add ttl predicate pushdown to deleterange
> 
> I thought we'd said we were _starting_ with a simple single `DELETE` worker and getting everything else working, the UX hammered out, etc and then, when we see indications that it can't keep up even when dialed up, that's when we'd work on iterative improvements in the implementation's performance under the hood?

This makes sense -- a TODO is fine. But, imo, I think this is rather large todo.  Do we really need to see indications that it can't keep up? I think we can confidently say it won't keep up.  I just think  this work for anything but a super tiny tables.   So tiny, in fact, that ... you know.. you could just run delete yourself.  But that's not what this feature is for, is it?  Consider the fact that in this implementation the worker does ~2x work vs the process that inserted those rows in the first place (select + delete vs insert).  Not only is this not distributed, but also ~2x slower than whatever generated the row in the first place.  That just doesn't sound good -- unless i"m misunderstanding.

2022-02-03 13:25 UTC, dt commented
Maybe we don't wait for indications it can't keep up, but I still think it is completely reasonable to get the overall shape of the feature in place, the UX worked out, the schema <-> job schedule setup/validation/etc worked out, etc then come back and swap out the implementation for a higher throughput one in a targeted change.

2022-02-03 14:36 UTC, miretskiy commented
Ack.

On Thu, Feb 3, 2022, 8:26 AM David Taylor ***@***.***> wrote:

> Maybe we don't wait for indications it can't keep up, but I still think it
> is completely reasonable to get the overall shape of the feature in place,
> the UX worked out, the schema <-> job schedule setup/validation/etc worked
> out, etc then come back and swap out the implementation for a higher
> throughput one in a targeted change.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/75840#issuecomment-1028989051>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANA4FVEJG5JIDVZVSL4Y55DUZJ66VANCNFSM5NK4GJNQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-09 16:16 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @otan, and @postamar)

___
*[pkg/sql/catalog/catpb/catalog.proto, line 132 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvU8PKb-werfOWzBRuS:-MvU8PKb-werfOWzBRuT:bhzqht2) ([raw file](https://github.com/cockroachdb/cockroach/blob/190fc36040bf03e9598e1f40a44752b31558edb7/pkg/sql/catalog/catpb/catalog.proto#L132)):*
> ```protobuf
>   optional uint32 table_id = 1 [
>     (gogoproto.customname) = "TableID",
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sem/catid.DescID",
> ```

do you know why sometimes we use catid.DescID vs descpb.ID?
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvU9hvw5_U0PuAwsp7e:-MvU9hvw5_U0PuAwsp7f:b-behxmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L37)):*
> ```Go
> // Resume implements the jobs.Resumer interface.
> func (t rowLevelTTLResumer) Resume(ctx context.Context, execCtx interface{}) error {
> 	p := execCtx.(sql.JobExecContext)
> ```

why is this named `p`? (just asking since that makes me think of `planner`, which is not the case here)
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 89 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUAQJ62mG7DwR17-jv:-MvUAQJ62mG7DwR17-jw:bovc7al) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L89)):*
> ```Go
> 			// Generate (pk_col_1, pk_col_2, ...) > ($2, $3, ...), reserving
> 			// $1 for the now clause.
> 			filterClause = fmt.Sprintf("AND (%s) > (", selectClause)
> ```

took me a sec to understand since i thought `selectClause` would include "SELECT" in it. i think `colNames` or something like that might be clearer
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 99 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUBS0E-cIo6UveQlLy:-MvUBS0E-cIo6UveQlLz:b-sc8qhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L99)):*
> ```Go
> 		}
> 
> 		aostClause := "AS OF SYSTEM TIME '-30s'"
> ```

rather than using -30s for each query in the loop, could this generate one timestamp up front that is used throughout the loop? that way it's less likely some rows would get skipped.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 123 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUEDdj6FKeBuVhK8e5:-MvUEDdj6FKeBuVhK8e6:b-ke3meg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L123)):*
> ```Go
> 			)
> 			var err error
> 			expiredRowsPKs, err = ie.QueryBuffered(
> ```

why buffer everything instead of using the `Rows` interfaces?
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 125 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUBpPSCCb0rm3tIjwN:-MvUBpPSCCb0rm3tIjwO:bukh9vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L125)):*
> ```Go
> 			expiredRowsPKs, err = ie.QueryBuffered(
> 				ctx,
> 				"ttl",
> ```

maybe a more detailed description here would help (since this is ultimately shown in the DB Console). like "ttl_scanner"?
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 127 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUE2KqCXSTcKSwADzm:-MvUE2KqCXSTcKSwADzn:b-thflq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L127)):*
> ```Go
> 				"ttl",
> 				txn,
> 				q,
> ```

maybe rename "q" to "selectQuery"
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 145 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUEY6BBGl1LSTa_K8C:-MvUEY6BBGl1LSTa_K8D:bsgv38q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L145)):*
> ```Go
> 			deleteBatch := expiredRowsPKs[startRowIdx:until]
> 
> 			// Flatten the datums in deleteBatch and generate the placeholder string.
> ```

how big (in terms of number characters) is this query going to get? do we need a safeguard against some kind of "query string is too big" error?
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 171 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUE9AZEyhPANYBO9tR:-MvUE9AZEyhPANYBO9tS:b-a68rmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L171)):*
> ```Go
> 				// TODO(#75428): configure admission priority
> 
> 				q := fmt.Sprintf(
> ```

maybe rename to "deleteQuery"
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 216 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUEkcj4KnVk6T5tvJ_:-MvUEkcj4KnVk6T5tvJa:b-4i83lx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L216)):*
> ```Go
> //   {"a", "b"} => a, b
> //   {"escape-me", "b"} => "escape-me", b
> func makeSelectClauseFromColumns(pkColumns []string) string {
> ```

similar to above comment, i'd find it more clear if it wasn't named "selectClause" but that might just be a confusion specific to me
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 33 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUFedi2GLRmdyz4q_r:-MvUFedi2GLRmdyz4q_s:bati7fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b751ee91f341e9ed8750646df3d841a2659ac92/pkg/sql/ttl/ttljob/ttljob.go#L33)):*
> ```Go
> 	defaultSelectBatchSize = settings.RegisterIntSetting(
> 		settings.TenantWritable,
> 		"sql.defaults.ttl_select_batch_size",
> ```

hm, i think we should try to keep `sql.defaults.*` names for cluster settings that control session variable defaults. maybe name this `sql.ttl.default_select_batch_size`. or something?

i think it also matters because the MODIFYCLUSTERSETTING role option only applies to `sql.defaults` cluster settings
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 37 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUG1Zk5Sf-nGHMZZVK:-MvUG1Zk5Sf-nGHMZZVL:bmpqdbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b751ee91f341e9ed8750646df3d841a2659ac92/pkg/sql/ttl/ttljob/ttljob.go#L37)):*
> ```Go
> 		500,
> 		settings.PositiveInt,
> 	)
> ```

should it have a `.WithPublic()`? same for below
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 40 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUFz4FBKHNZtLpimiS:-MvUFz4FBKHNZtLpimiT:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b751ee91f341e9ed8750646df3d841a2659ac92/pkg/sql/ttl/ttljob/ttljob.go#L40)):*
> ```Go
> 	defaultDeleteBatchSize = settings.RegisterIntSetting(
> 		settings.TenantWritable,
> 		"sql.defaults.ttl_delete_batch_size",
> ```

ditto
___
*[pkg/sql/logictest/testdata/logic_test/row_level_ttl, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvU8rbU2gwVoQtpNPZO:-MvU8rbU2gwVoQtpNPZP:bhh6kyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/190fc36040bf03e9598e1f40a44752b31558edb7/pkg/sql/logictest/testdata/logic_test/row_level_ttl#L100)):*
> ```
> SELECT create_statement FROM [SHOW CREATE SCHEDULE $schedule_id]
> ----
> ALTER TABLE [62 as T] WITH (expire_after = ...)
> ```

i haven't seen this `[62 as T]` syntax before! what is it?
___
*[pkg/sql/ttl/ttljob/ttljob_integration_test.go, line 197 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUFGPf4MkWMv-z2ZgH:-MvUFGPf4MkWMv-z2ZgI:bx7hgf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob_integration_test.go#L197)):*
> ```Go
> 			t.Logf("test case: %#v", tc)
> 
> 			th, cleanupFunc := newRowLevelTTLTestJobTestHelper(t)
> ```

 [...]

2022-02-09 21:38 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @postamar, and @rafiss)

___
*[pkg/sql/catalog/catpb/catalog.proto, line 132 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvU8PKb-werfOWzBRuS:-MvV8nNy8KFD6R8VLeZm:b-uejcxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/190fc36040bf03e9598e1f40a44752b31558edb7/pkg/sql/catalog/catpb/catalog.proto#L132)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do you know why sometimes we use catid.DescID vs descpb.ID?
</blockquote></details>

yeah, descpb depends on catpb, so this prevents a circular dependency.
type alias: https://github.com/cockroachdb/cockroach/blob/4df7f50b9bd54fe943f048eb762f8e602ae8bf34/pkg/sql/catalog/descpb/structured.go#L41
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvU9hvw5_U0PuAwsp7e:-MvVI18F3U8z8FyZN1L-:b-d7khf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L37)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why is this named `p`? (just asking since that makes me think of `planner`, which is not the case here)
</blockquote></details>

form following other jobs, i've renamed it.
it's a sub-interface of the planner.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 89 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUAQJ62mG7DwR17-jv:-MvVGikw7-UdryfqlGtM:bz6plht) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L89)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

took me a sec to understand since i thought `selectClause` would include "SELECT" in it. i think `colNames` or something like that might be clearer
</blockquote></details>

Done. Named it columns_name_sql
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 99 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUBS0E-cIo6UveQlLy:-MvVGtB1EeohB5K9wmpI:b-sdbtvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L99)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

rather than using -30s for each query in the loop, could this generate one timestamp up front that is used throughout the loop? that way it's less likely some rows would get skipped.
</blockquote></details>

does this make a difference?

we already compare `crdb_internal_expiration` against a fixed timestamp already - if we made it compare against `now()` the job could take an unbounded amount of time.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 123 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUEDdj6FKeBuVhK8e5:-MvVQ2Fb82oZoISaLu7i:b-pmyjfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L123)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why buffer everything instead of using the `Rows` interfaces?
</blockquote></details>

done, tacked on as a commit at the end as it was a non-trivial change.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 125 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUBpPSCCb0rm3tIjwN:-MvVHWRn4VNQqrPq0e3u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L125)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe a more detailed description here would help (since this is ultimately shown in the DB Console). like "ttl_scanner"?
</blockquote></details>

Done.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 127 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUE2KqCXSTcKSwADzm:-MvVHf8q6MdqFl2flUfp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L127)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe rename "q" to "selectQuery"
</blockquote></details>

Done.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 145 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUEY6BBGl1LSTa_K8C:-MvVHgTH-_Kvjk7z0J2B:b-qupnsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L145)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

how big (in terms of number characters) is this query going to get? do we need a safeguard against some kind of "query string is too big" error?
</blockquote></details>

it's a function of the primary key.
i guess the knobs you have here is lessening the delete_batch_size.
but it's a prepared statement; i guess it runs into the same limitation as running it manually.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 171 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUE9AZEyhPANYBO9tR:-MvVHfuM2FdWDg7JA08t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L171)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe rename to "deleteQuery"
</blockquote></details>

Done.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 216 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUEkcj4KnVk6T5tvJ_:-MvVHudc8GWpfP550iSA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L216)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similar to above comment, i'd find it more clear if it wasn't named "selectClause" but that might just be a confusion specific to me
</blockquote></details>

Done.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 33 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUFedi2GLRmdyz4q_r:-MvV9eKV3Ezrrv7TMweW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b751ee91f341e9ed8750646df3d841a2659ac92/pkg/sql/ttl/ttljob/ttljob.go#L33)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, i think we should try to keep `sql.defaults.*` names for cluster settings that control session variable defaults. maybe name this `sql.ttl.default_select_batch_size`. or something?

i think it also matters because the MODIFYCLUSTERSETTING role option only applies to `sql.defaults` cluster settings
</blockquote></details>

Done.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 37 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUG1Zk5Sf-nGHMZZVK:-MvV9efb6lBZvyRCTE4T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b751ee91f341e9ed8750646df3d841a2659ac92/pkg/sql/ttl/ttljob/ttljob.go#L37)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should it have a `.WithPublic()`? same for below
</blockquote></details>

Done.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 40 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUFz4FBKHNZtLpimiS:-MvV9fBg-wOmaBzl-cU8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b751ee91f341e9ed8750646df3d841a2659ac92/pkg/sql/ttl/ttljob/ttljob.go#L40)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/row_level_ttl, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvU8rbU2gwVoQtpNPZO:-MvV96CB8gmMwOsLHkJM:b48krr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/190fc360 [...]

2022-02-09 22:04 UTC, otan commented
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 99 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUBS0E-cIo6UveQlLy:-MvVW4C-A9jL3Al4u7LE:b-27aycx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L99)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

does this make a difference?

we already compare `crdb_internal_expiration` against a fixed timestamp already - if we made it compare against `now()` the job could take an unbounded amount of time.
</blockquote></details>

i retract that statement, fixed


<!-- Sent from Reviewable.io -->

2022-02-10 04:08 UTC, otan commented
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 123 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MvUEDdj6FKeBuVhK8e5:-MvWo-oL8LIAcPLNtut0:bd0i4xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dd78e150a98cc8edc2ea12538a775d0394fcac8/pkg/sql/ttl/ttljob/ttljob.go#L123)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

done, tacked on as a commit at the end as it was a non-trivial change.
</blockquote></details>

i had to revert this. trying to use the iterator whilst only processing one delete batch didn't seem to make the code happy and prone to some sort of race:

```
=== RUN   TestRowLevelTTLJobRandomEntries/random_4
    ttljob_integration_test.go:210: test case: ttljob_test.testCase{desc:"random 4", createTable:"CREATE TABLE tbl (\n\tid UUID DEFAULT gen_random_uuid(),\n\trand_col_1 BOX2D,\n\trand_col_2 TIME,\n\ttext TEXT,\n\tPRIMARY KEY (id, rand_col_1, rand_col_2)\n) WITH (ttl_expire_after = '30 days', ttl_select_batch_size = 23, ttl_delete_batch_size = 45)", numExpiredRows:16, numNonExpiredRows:67}
    ttljob_integration_test.go:107: condition failed to evaluate within 3m45s: expected status succeeded, got failed (error: TransactionStatusError: client already committed or rolled back the transaction. Trying to execute: 1 Scan (REASON_TXN_COMMITTED))
        goroutine 10555 [running]:
        runtime/debug.Stack()
        	/usr/local/go/src/runtime/debug/stack.go:24 +0x72
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithin({0x8b9ccd8, 0xc002912340}, 0xe3, 0xc0005f01e0)
        	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:60 +0x7d
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon({0x8b9ccd8, 0xc002912340}, 0xc002297c38)
        	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:41 +0x5b
        github.com/cockroachdb/cockroach/pkg/sql/ttl/ttljob_test.(*rowLevelTTLTestJobTestHelper).waitForSuccessfulScheduledJob(0xc002494450, 0xc002912340)
        	/go/src/github.com/cockroachdb/cockroach/pkg/sql/ttl/ttljob/ttljob_integration_test.go:107 +0x195
        github.com/cockroachdb/cockroach/pkg/sql/ttl/ttljob_test.TestRowLevelTTLJobRandomEntries.func1(0xc002912340)
        	/go/src/github.com/cockroachdb/cockroach/pkg/sql/ttl/ttljob/ttljob_integration_test.go:269 +0x4ad
        testing.tRunner(0xc002912340, 0xc000775e48)
        	/usr/local/go/src/testing/testing.go:1259 +0x230
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:1306 +0x727
    --- FAIL: TestRowLevelTTLJobRandomEntries/random_4 (229.79s)
```

if you feel strongly about it i can dig in further, but seems like a marginal difference either way (and the code was a *lot* more complicated)


<!-- Sent from Reviewable.io -->

2022-02-10 21:36 UTC, rafiss requested changes
just have minor nits. i'm deferring to others for the details on how the job needs to be implemented.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-:-Mv_YxjC4iX0nGagPTCp:b-uzn3cx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @otan, @postamar, and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob.go, line 125 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Mv_YHDJBWQg2IEGC8Rx:-Mv_YHDJBWQg2IEGC8Ry:bqgwuml) ([raw file](https://github.com/cockroachdb/cockroach/blob/0356ef9d171c7700048d93f1eadf98fc97ea557d/pkg/sql/ttl/ttljob/ttljob.go#L125)):*
> ```Go
> 			// Generate (pk_col_1, pk_col_2, ...) > ($2, $3, ...), reserving
> 			// $1 for the now clause.
> 			filterClause = fmt.Sprintf("AND (%s) > (", selectClause)
> ```

i still see this named as `selectClause` but i thought you were renaming to `columnNames`?
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 156 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Mv_YjVd2Mab1C6SzjrE:-Mv_YjVe5M_ysc6Fi3La:b2saqn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0356ef9d171c7700048d93f1eadf98fc97ea557d/pkg/sql/ttl/ttljob/ttljob.go#L156)):*
> ```Go
> 			expiredRowsPKs, err = ie.QueryBuffered(
> 				ctx,
> 				"ttl",
> ```

nit: rename to "ttl_scanner"
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 158 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Mv_Ygxw1BBAsDUpgnqg:-Mv_Ygxw1BBAsDUpgnqh:b-x9ieyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0356ef9d171c7700048d93f1eadf98fc97ea557d/pkg/sql/ttl/ttljob/ttljob.go#L158)):*
> ```Go
> 				"ttl",
> 				txn,
> 				q,
> ```

nit: maybe rename to "selectQuery"
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 201 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Mv_YdjbBryONsM1RabX:-Mv_YdjbBryONsM1RabY:b-8jz55a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0356ef9d171c7700048d93f1eadf98fc97ea557d/pkg/sql/ttl/ttljob/ttljob.go#L201)):*
> ```Go
> 				// TODO(#75428): configure admission priority
> 
> 				q := fmt.Sprintf(
> ```

nit: maybe rename to "deleteQuery"
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 260 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Mv_YoOt86MCmEmcj9pY:-Mv_YoOt86MCmEmcj9pZ:bkbskj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0356ef9d171c7700048d93f1eadf98fc97ea557d/pkg/sql/ttl/ttljob/ttljob.go#L260)):*
> ```Go
> //   {"a", "b"} => a, b
> //   {"escape-me", "b"} => "escape-me", b
> func makeSelectClauseFromColumns(pkColumns []string) string {
> ```

nit: maybe rename so it's not "select clause"


<!-- Sent from Reviewable.io -->

2022-02-10 22:35 UTC, otan reviewed
some of my changes got rekt in the revert, my bad.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-:-Mv_l8MQCjLLcE-qOdR0:b-c8aqqs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, @postamar, and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob.go, line 125 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-Mv_YHDJBWQg2IEGC8Rx:-Mv_lYAz7bR4WvUCT2Rv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0356ef9d171c7700048d93f1eadf98fc97ea557d/pkg/sql/ttl/ttljob/ttljob.go#L125)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i still see this named as `selectClause` but i thought you were renaming to `columnNames`?
</blockquote></details>

Done.
___
*[pkg/sql/row_level_ttl.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75840#-MuvpiAR1jZkXyWm9Noh:-MvX-QB2AwcZDKxRqLac:b-71z0ow) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea56751f9a9c0ba520e5afa220eada7ba76ac2a3/pkg/sql/row_level_ttl.go#L253)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i can maybe add it into scheduled jobs later, added it to my TODO.
</blockquote></details>

https://cockroachlabs.slack.com/archives/C02DSDS9TM1/p1644461478718559 or maybe not


<!-- Sent from Reviewable.io -->

2022-02-11 03:40 UTC, otan commented
@ajwerner  / @dt / @miretskiy youse seem most familiar with the jobs code. does that portion of the code (first two commits) look good to you? if so i'll consider that approval...

2022-02-11 14:28 UTC, miretskiy commented
@miretskiy i'm okay w/ jobs/schedules jobs changes.

2022-02-11 14:29 UTC, miretskiy approved these changes
Good to go on scheduled jobs...

2022-02-13 21:51 UTC, otan commented
bors r-

merge conflict

2022-02-13 22:09 UTC, otan commented
bors r+

2022-02-13 23:21 UTC, merged