bazel: avoid stamping --config=dev builds
cockroachdb/cockroach pull request #75976
Opened 2022-02-03 21:10 UTC by irfansharif

When used with a remote build cache, these stamps (despite being marked
as volatile), induce an unnecessary golink step when switching back and
forth between branches. See
https://github.com/bazelbuild/bazel/issues/10075. Opting out here shaves
a few precious seconds if the previously built binary is already
available.

Release note: None

2022-02-03 21:10 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/75976)
<!-- Reviewable:end -->

2022-02-03 23:29 UTC, rickystewart requested changes

2022-02-03 23:29 UTC, rickystewart commented on .bazelrc
> -build:dev --stamp --workspace_status_command=./build/bazelutil/stamp.sh
Two problems with this:

1. In my testing, `cockroach` binaries can't start properly if they don't have the various stamped variables. You should be able to trivially reproduce this, but let me know if you can't. You can make this PR mergeable by removing those checks from `cockroach` (maybe only for `dev` builds if you need to?)
2. `dev doctor` will fail if you delete this line without making any other changes.

2022-02-17 16:32 UTC, irfansharif commented
Not having time to follow up, I'll try again some other day.

2022-04-04 18:35 UTC, irfansharif commented
Subsumed by #79360.

2022-04-04 18:35 UTC, closed without merging