storage: add experimental MVCC range tombstone primitives
cockroachdb/cockroach pull request #76131
Opened 2022-02-06 22:41 UTC by erikgrinaker

This is an alternative to #76090. Rather than hiding Pebble range keys inside the MVCC API, this exposes them as a first-class primitive for internal use. This allows callers to take advantage of Pebble range key functionality such as combined point/range key iteration and range key masking, which is useful e.g. for `IncrementalMVCCIterator` and `SSTIterator` (used by backups and rangefeed catchup scans).

For consistency with point keys, this also stores range tombstones as a range key with a `nil` value instead of a mostly-useless Protobuf that only adds overhead.

---

This patch adds initial experimental primitives for MVCC range
tombstones and the range keys they build on, based on experimental
Pebble range keys,

* Data structures:
  * `storage.MVCCRangeKey`
  * `nil` value for range tombstones (as for point tombstones).

* Engine methods for writing, removing, and reading range keys:
  * `Engine.ExperimentalClearMVCCRangeKey()`
  * `Engine.ExperimentalPutMVCCRangeKey()`
  * `SimpleMVCCIterator.HasPointAndRange()`
  * `SimpleMVCCIterator.RangeBounds()`
  * `SimpleMVCCIterator.RangeKeys()`

* MVCC functions and iterator for writing and reading range tombstones:
  * `storage.ExperimentalMVCCDeleteRangeUsingTombstone()`
  * `storage.ScanMVCCTombstones()`
  * `storage.MVCCRangeTombstoneIterator`

Range tombstones do not have a distinct identity, and should instead be
considered a tombstone continuum: they will merge with abutting
tombstones, can be partially cleared, can split or merge along with
ranges, and so on. Bounded scans will truncate them to the scan bounds.

Raw fragmented range keys can be accessed via the `Engine` and
`SimpleMVCCIterator` interfaces, but this is primarily for internal MVCC
usage. In the externally facing MVCC API, range tombstones will be
exposed primarily in defragmented form.

Range tombstones are not yet handled in the rest of the MVCC API, nor
are they exposed via KV APIs. They are not persisted to disk either, due
to Pebble range key limitations. Subsequent pull requests will extend
their functionality and integrate them with other components.

Release note: None

2022-02-06 22:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76131)
<!-- Reviewable:end -->

2022-02-08 16:47 UTC, sumeerbhola requested changes
> Reviewed 4 of 20 files at r1, 6 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @jbowens)

___
*[pkg/kv/kvserver/spanset/batch.go, line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP6rBy9ZpPAgdq24xx:-MvP6rBy9ZpPAgdq24xy:b-g88uxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/kv/kvserver/spanset/batch.go#L181)):*
> ```Go
> // HasPointAndRange implements SimpleMVCCIterator.
> func (i *MVCCIterator) HasPointAndRange() (bool, bool) {
> 	panic("not implemented")
> ```

why is this not passing through to the underlying `storage.MVCCIterator`?
___
*[pkg/storage/engine.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP4dCi8crey62ZYRdX:-MvP4dCj5_GuLu8TERil:b-1zhuie) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L78)):*
> ```Go
> 	// key and/or a range key. Range keys are only emitted when requested via
> 	// IterOptions.KeyTypes.
> 	HasPointAndRange() (bool, bool)
> ```

So the `Valid` bool would imply at least one of these 2 bools is true?
It may be time to do part of the cleanup mentioned below (not the part about renaming NextEngineKey). The cleanup would include returning (bool, error) from the Seek methods and eliminate Valid. I am hopeful that it is a mechanical step and could happen in a PR preceding this one.
```
	// TODO(sumeer): change MVCCIterator.Next() to match the
	// return values, change all its callers.
```
___
*[pkg/storage/engine.go, line 628 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP7ymCDbaWcxhYN5R5:-MvP7ymCDbaWcxhYN5R6:b-r0il1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L628)):*
> ```Go
> 
> 	// ExperimentalPutMVCCRangeKey writes a value to an MVCC range key. It is
> 	// currently only used for range tombstones, which have a value of nil.
> ```

I have a mild preference to specializing this for MVCC-range-tombstones (or whatever we are calling them so as to not confuse with the various other similar terms). Then one wouldn't be passing a nil value.
Btw, does this also mean that we are not writing the original key range as a value, or that's just an implementation detail not exposed here.
___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvP9Zh88RJ1PE1iJ3ua:b-ly2big) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
> ```Go
> // RangeBounds implements the MVCCIterator interface.
> func (p *pebbleIterator) RangeBounds() (roachpb.Key, roachpb.Key) {
> 	return p.iter.RangeBounds()
> ```

I think there is a problem here.
The []bytes returned by `pebble.Iterator` are not necessarily roachpb.Keys. They are an encoded key, that when parsed will give a `roachpb.Key`. One could parse both the start and end, but it is also legal for Pebble to return something like [a@20, a@10)@50, which if we parse and use only the `roachpb.Key` will give us [a, a) which is empty.

I think the solution here is to borrow an idea from an earlier version of the Pebble range keys RFC, but instead apply it at the CockroachDB level: make this appear as a point key a@50 to the client of pebbleIterator. There will need to be some de-duping in this interface since if the next range key is [a@10,a@5)@50 we don't want to emit a@50 again.

The next range key must be of the form [a@10,<something>)@50 since we don't allow unsetting of arbitrary key spans (they must be prefixes). Say it is [a@10,b@20)@50. We could produce [a,b)@50. There are a couple of problems with this. If the point key is b@25, it looks as if the range does not actually overlap with the point. We know the actual end of this range key will be at a key > b. We could expose an inclusive [a,b]@50 perhaps?

I think something reasonable can be worked out here that preserves a model to the caller that the range keys are of the form [roachpb.Key,roachpb.Key)@ts.


<!-- Sent from Reviewable.io -->

2022-02-08 16:51 UTC, aliher1911 commented on pkg/storage/mvcc_key.go
> +// MVCCRangeKey is an MVCC key span at a timestamp.
nit: it sounds ambiguous mvcc implies a timestamp aready, maybe just a keyspan at a timestamp?

2022-02-08 16:51 UTC, aliher1911 commented on pkg/storage/mvcc_key_test.go
> +		"start at end":     {MVCCRangeKey{StartKey: a, EndKey: b, Timestamp: ts1}, ""},
Should it be
```
"start at end":     {MVCCRangeKey{StartKey: a, EndKey: a, Timestamp: ts1}, ""},
```

2022-02-08 16:51 UTC, aliher1911 commented on pkg/storage/mvcc_range_tombstone_iterator.go
> +	// straddle the it will have their start key truncated to the lower bound.
straddle "it" or "the iterator"?

2022-02-08 16:51 UTC, aliher1911 commented on pkg/storage/engine.go
> +	HasPointAndRange() (bool, bool)
I find this naming confusing because of "And". Maybe
```
HasValue() (point bool, range bool)
```
would be better?

2022-02-08 16:51 UTC, aliher1911 commented on pkg/storage/engine.go
> +	RangeBounds() (roachpb.Key, roachpb.Key)
I was trying to get my head around this change and I think changes to how range keys are iterated deserves additional comments. While it is very straightforward how we iterate values, it is not so with range keys in terms of key bounds. Is RangeBounds a union of all RangeKeys() overlapping at current timestamp?

2022-02-08 18:37 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @jbowens, @sumeerbhola, and @ts)

___
*[pkg/kv/kvserver/spanset/batch.go, line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP6rBy9ZpPAgdq24xx:-MvPWbZi0WZ3egWdwItf:b2fhy4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/kv/kvserver/spanset/batch.go#L181)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is this not passing through to the underlying `storage.MVCCIterator`?
</blockquote></details>

It will. I was doing the minimum necessary to get feedback on this draft, I'll fix it up either when I complete this PR or in a follow-up PR where I do the batcheval latching bits (which is where this comes in).
___
*[pkg/storage/engine.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP4dCi8crey62ZYRdX:-MvPWtInBg1eGPm_OHbT:b-vq181n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L78)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So the `Valid` bool would imply at least one of these 2 bools is true?
It may be time to do part of the cleanup mentioned below (not the part about renaming NextEngineKey). The cleanup would include returning (bool, error) from the Seek methods and eliminate Valid. I am hopeful that it is a mechanical step and could happen in a PR preceding this one.
```
	// TODO(sumeer): change MVCCIterator.Next() to match the
	// return values, change all its callers.
```

</blockquote></details>

I suppose yes. But we have less than 3 weeks to get all of the MVCC range tombstone functionality in and migrate all callers, so I won't be spending time on any related cleanups now. We can do that for 22.2.
___
*[pkg/storage/engine.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvGBgfr-XB08vWIYNTa-r3-78:-MvPXa318dYg21Z_UsPP:b-60uk4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L78)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I find this naming confusing because of "And". Maybe
```
HasValue() (point bool, range bool)
```
would be better?
</blockquote></details>

This just mirrors the Pebble API, I figured that'd cause less confusion.
___
*[pkg/storage/engine.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvGBgfr-XB08vWIYNTa-r3-80:-MvPXjTB41Z2XXDqMtg7:bl41ocn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L80)):*
Yep, I'll be adding ample documentation on this once we have consensus that we'll be doing this PR rather than the alternative (#76090). I may defer that until after stability though, since that's backportable and we have very little time left to complete all of the MVCC bulk ops work.

>Is RangeBounds a union of all RangeKeys() overlapping at current timestamp?

The tl;dr is: Range keys and point keys exist independently, but can be iterated over in parallel. Range keys are also fragmented, such that all overlapping range keys have identical start/end bounds. So let's say we're at point c@5 where there is also a stack of range key fragments [a-f) at timestamps 1,2,3. RangeBounds() returns [a-f), Key() return c@5, RangeKeys() return 1:foo,2:bar,3:baz (or for range tombstones, simply `nil`).
___
*[pkg/storage/engine.go, line 628 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP7ymCDbaWcxhYN5R5:-MvPYEUx2vHr5aZhejkw:bnkykmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L628)):*
> I have a mild preference to specializing this for MVCC-range-tombstones (or whatever we are calling them so as to not confuse with the various other similar terms). Then one wouldn't be passing a nil value.

Yeah, I've been going back and forth on this. But we may have another use-case coming up for 22.2 (ranged intents for IMPORT INTO), so I figured we might as well generalize this. Not a strongly held opinion though, but the functional delta between tombstones or general keys is tiny (value or not).

>Btw, does this also mean that we are not writing the original key range as a value, or that's just an implementation detail not exposed here.

Yes, I realized that it didn't make sense, e.g. due to CRDB range splits/merges. For example, if we write [a-d), then split across three ranges [a-b), [b-c), [c-d), the middle bit can get GCed before the others. Similarly, two range tombstones that abut will merge into one. We'd have to rewrite all of the fragment values in these cases, but it just seems much better/simpler to not give them an identity at all. It should be considered a "tombstone continuum" that can be sliced and diced at will.

This also has the nice property of mirroring the point key API, where `nil` is tombstone and values are arbitrary byte slices.
___
*[pkg/storage/mvcc_key.go, line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvGBgfr-XB08vWIYNTg-r3-296:-MvPZfTb5ZjzL9R9COSO:bhms472) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/mvcc_key.go#L296)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

nit: it sounds ambiguous mvcc implies a timestamp aready, maybe just a keyspan at a timestamp?
</blockquote></details>

Yeah, this wording is a bit clumsy, will clean it up.
___
*[pkg/storage/mvcc_range_tombstone_iterator.go, line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvGBgfr-XB08vWIYNTo-r3-24:-MvPZl9072kChBXD_5is:b-o1geqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/mvcc_range_tombstone_iterator.go#L24)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

straddle "it" or "the iterator"?
</blockquote></details>

Ah -- should be "it", i.e. the bound. I'll write it out.
___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvP_7NK90cfRegP1IB5:b-wc006h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think there is a problem here.
The []bytes returned by `pebble.Iterator` are not necessarily roachpb.Keys. They are an encoded key, that when parsed will give a `roachpb.Key`. One could parse both the start and end, but it is also legal for Pebble to return something like [a@20, a@10)@50, which if we parse and use only the `roachpb.Key` will give us [a, a) which is empty.

I think the solution here is to borrow an idea from an earlier version of the Pebble range keys RFC, but instead apply it at the CockroachDB level: make this appear as a point key a@50 to the client of pebbleIterator. There will need to be some de-duping in this interface since if the next range key is [a@10,a@5)@50 we don't want to emit a@50 again.

The next range key must be of the form [a@10,<something>)@50 since we don't allow unsetting of arbitrary key spans (they must be prefixes). Say it is [a@10,b@20)@50. We could produce [a,b)@50. There are a couple of problems with this. If the point key is b@25, it looks as if the range does not actually overlap with the point. We know the actual end of this range key will be at a key > b. We could expose an inclusive [a,b]@50 perhaps?

I think something reasonable can be worked out here that preserves a model to the caller that the range keys are of the form [roachpb.Key,roachpb.Key)@ts.
</blockquote></deta [...]

2022-02-08 19:13 UTC, jbowens reviewed
> Reviewed 3 of 20 files at r1, 3 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/engine.go, line 619 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvJhHjN7yHEoraQASw9:-MvJhHjN7yHEoraQASwA:b-hzzmm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ed15373e0289afc22287163a686cc36b99d1994/pkg/storage/engine.go#L619)):*
> ```Go
> 	// boundaries will be cleared. Clears are idempotent.
> 	//
> 	// This method is primarily intented for MVCC garbage collection and similar
> ```

nit: s/intented/intended/
___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvPfxdhA_w9ceOJ4bYQ:blyvi6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Is that still the case now that we make sure Pebble doesn't split user keys across SSTs? I though that was done so that we were guaranteed to get all suffixes for the range key in a single call?

@jbowens Can you confirm?
</blockquote></details>

That change referred to 'user keys' from the perspective of Pebble, which are full versioned MVCC keys from the perspective of Cockroach (There can be multiple only if a Pebble snapshot prevented Pebble from dropping earlier keys).

Pebble still allows `a@2` and `a@1` to be written to separate sstables, which allows versions to be surfaced within range key fragment bounds.

It's a little unfortunate these internal bounds are surfaced, because `RangeKeySet`, `RangeKeyUnset` and `RangeKeyDelete` all require their bounds to be unsuffixed. If the user can only set, unset and delete range keys at prefixes, then a physical range key bound `[a@2, b@3)` does imply that the logical range key state must be unchanged in the range `[a, b]` (note the _inclusive_ `b` end boundary).


<!-- Sent from Reviewable.io -->

2022-02-08 19:26 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvPkvpg8k8P5DEpCVG2:b1mprp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

That change referred to 'user keys' from the perspective of Pebble, which are full versioned MVCC keys from the perspective of Cockroach (There can be multiple only if a Pebble snapshot prevented Pebble from dropping earlier keys).

Pebble still allows `a@2` and `a@1` to be written to separate sstables, which allows versions to be surfaced within range key fragment bounds.

It's a little unfortunate these internal bounds are surfaced, because `RangeKeySet`, `RangeKeyUnset` and `RangeKeyDelete` all require their bounds to be unsuffixed. If the user can only set, unset and delete range keys at prefixes, then a physical range key bound `[a@2, b@3)` does imply that the logical range key state must be unchanged in the range `[a, b]` (note the _inclusive_ `b` end boundary).


</blockquote></details>

@sumeerbhola's earlier iterations of the range keys API required the user provide an `ImmediateSucessor(k)` function that returns a key `k2` such that there are no valid keys greater than `k` and less than `k2`. I'm forgetting all the details that earlier proposal, but `ImmediateSuccessor` allows for representing an inclusive end boundary like the above `[a,b]` as `[a, IS(b))`.

Could we allow `(*storage.pebbleIterator)` to broaden the range key bounds returned by Pebble using its own implementation of an `ImmediateSuccessor` function for `roachpb.Key`s?  It makes me uncomfortable to broaden the bounds like that, but it sure would be convenient.


<!-- Sent from Reviewable.io -->

2022-02-08 19:51 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/engine.go, line 628 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP7ymCDbaWcxhYN5R5:-MvPoDSD4-70ckKQlBNK:b-5nfgwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L628)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

> I have a mild preference to specializing this for MVCC-range-tombstones (or whatever we are calling them so as to not confuse with the various other similar terms). Then one wouldn't be passing a nil value.

Yeah, I've been going back and forth on this. But we may have another use-case coming up for 22.2 (ranged intents for IMPORT INTO), so I figured we might as well generalize this. Not a strongly held opinion though, but the functional delta between tombstones or general keys is tiny (value or not).

>Btw, does this also mean that we are not writing the original key range as a value, or that's just an implementation detail not exposed here.

Yes, I realized that it didn't make sense, e.g. due to CRDB range splits/merges. For example, if we write [a-d), then split across three ranges [a-b), [b-c), [c-d), the middle bit can get GCed before the others. Similarly, two range tombstones that abut will merge into one. We'd have to rewrite all of the fragment values in these cases, but it just seems much better/simpler to not give them an identity at all. It should be considered a "tombstone continuum" that can be sliced and diced at will.

This also has the nice property of mirroring the point key API, where `nil` is tombstone and values are arbitrary byte slices.
</blockquote></details>

Agreed that using nil makes sense.
___
*[pkg/storage/mvcc_range_tombstone_iterator.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvPsB0Y3UxEgSIb7KQC:-MvPsB0Y3UxEgSIb7KQD:b-37f56u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/mvcc_range_tombstone_iterator.go#L60)):*
> ```Go
> // tombstones as soon as possible. Otherwise, a single tombstone across the the
> // entire key span would require all other tombstones at other timestamps to be
> // buffered in memory before they could be emitted. However, see the Fragmented
> ```

Perhaps add that this optimization means only the tombstones that are currently incomplete need to be buffered, while if we ordered by start key we would additionally need to buffer all complete tombstones that started after currently incomplete ones.
___
*[pkg/storage/mvcc_range_tombstone_iterator.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvPr02rDFz5qXhumCsz:-MvPr02rDFz5qXhumCt-:b-akxg5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/mvcc_range_tombstone_iterator.go#L61)):*
> ```Go
> // entire key span would require all other tombstones at other timestamps to be
> // buffered in memory before they could be emitted. However, see the Fragmented
> // option which emits non-deterministic fragments in StartKey,Timestamp order.
> ```

(I haven't read the implementation)
- What does "defragmentation" mean here. Does it mean that all abutting fragments (from a roachpb.Key perspective) and having the same timestamp will be combined.
- In this non-deterministic case, I assume we have the same issue we are discussing in the other thread?
___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvPpWlA-aUmgwBJb48L:b-z5csrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

@sumeerbhola's earlier iterations of the range keys API required the user provide an `ImmediateSucessor(k)` function that returns a key `k2` such that there are no valid keys greater than `k` and less than `k2`. I'm forgetting all the details that earlier proposal, but `ImmediateSuccessor` allows for representing an inclusive end boundary like the above `[a,b]` as `[a, IS(b))`.

Could we allow `(*storage.pebbleIterator)` to broaden the range key bounds returned by Pebble using its own implementation of an `ImmediateSuccessor` function for `roachpb.Key`s?  It makes me uncomfortable to broaden the bounds like that, but it sure would be convenient.
</blockquote></details>

I think we can broaden because we already have an ImmediateSuccessor function for `roachpb.Key`, `roachpb.Key.Next()`

It amuses me that we simply shifted the problem without realizing it. Though it was probably the correct shift to make given that we only have to handle this when iterating.


<!-- Sent from Reviewable.io -->

2022-02-08 20:23 UTC, erikgrinaker reviewed
From the feedback and prototyping I've done elsewhere, this approach seems preferable to #76090. I'm going to start wrapping this up while we discuss further.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-MvPzwxz1xujkv0czkbv:b-ssbscj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/mvcc_range_tombstone_iterator.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvPsB0Y3UxEgSIb7KQC:-MvPwoXg3FqH-mDG02v3:bsdn7sv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/mvcc_range_tombstone_iterator.go#L60)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Perhaps add that this optimization means only the tombstones that are currently incomplete need to be buffered, while if we ordered by start key we would additionally need to buffer all complete tombstones that started after currently incomplete ones.
</blockquote></details>

I agree, will clarify that.
___
*[pkg/storage/mvcc_range_tombstone_iterator.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvPr02rDFz5qXhumCsz:-MvPw1dbBbgKFhaaVL9T:bmueno0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/mvcc_range_tombstone_iterator.go#L61)):*
> What does "defragmentation" mean here. Does it mean that all abutting fragments (from a roachpb.Key perspective) and having the same timestamp will be combined.

Yes. I'm likely going to generalize this into a range key defragmenter rather than a tombstone defragmenter, which will also check the value (so two abutting range keys at the same suffix with different values are considered different defragmented range keys).

>In this non-deterministic case, I assume we have the same issue we are discussing in the other thread?

Yes. In that case, this iterator essentially reduces to the normal `SimpleMVCCIterator` range key functionality. This option was carried over from the other draft PR where we this iterator was the only place we surfaced range keys, it should likely be removed before completing this PR.
___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvPyUEI6Q9Qj-_aIWtD:bd05zcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
> Could we allow (*storage.pebbleIterator) to broaden the range key bounds returned by Pebble using its own implementation of an ImmediateSuccessor function for roachpb.Keys?  It makes me uncomfortable to broaden the bounds like that, but it sure would be convenient.

So `storage.pebbleIterator` will essentially check whether the range keys at the current position have a suffix, and if so defragment until we complete the start/end prefixes? Or is there some simpler option that I'm missing?


<!-- Sent from Reviewable.io -->

2022-02-08 20:31 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvQ0jsgAXwqXpI6Zvrc:b-fh9epo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

> Could we allow (*storage.pebbleIterator) to broaden the range key bounds returned by Pebble using its own implementation of an ImmediateSuccessor function for roachpb.Keys?  It makes me uncomfortable to broaden the bounds like that, but it sure would be convenient.

So `storage.pebbleIterator` will essentially check whether the range keys at the current position have a suffix, and if so defragment until we complete the start/end prefixes? Or is there some simpler option that I'm missing?
</blockquote></details>

To clarify: can this suffix "leakage" occur only at the iterator bounds, or anywhere within the iteration span? My understanding was that it could occur anywhere within the span, but from what you're saying it sounds like it's only at the iterator bounds so setting UpperBound:key.Next() essentially solves it?


<!-- Sent from Reviewable.io -->

2022-02-08 21:28 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvQBOZ0CmTaw64PRg7h:bcsio5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
> Or is there some simpler option that I'm missing?

I'm suggesting something like:
```
start, end := p.iter.RangeBounds()
if hasTimestamp(start) {
    start = stripTimestamp(start)
}
if hasTimestamp(end) {
    end = stripTimestamp(end).Next()
}
```

The suffixes can appear anywhere with the iteration span. Pebble may fragment the range keys into these suffixed keys because of sstable fragmentation. But because we never allow committing range keys with suffixed keys, a range key with suffixed bounds necessarily must be a physical fragment of a logical range key that covers whole user keys. We don't know the full defragmented bounds, but we do know that the entirety of the bounds' prefixes must fall within the defragmented bounds.

One consequence of the above is that you can have overlapping RangeBounds returned by `pebbleIterator`. eg, `[b@3, c@2)`, `[c@2, d)` is translated by `pebbleIterator` into `[b, c\0)` and `[c, d)`


<!-- Sent from Reviewable.io -->

2022-02-08 22:08 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvQMtgCAkBr1zvB5POf:b-d9xwjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> Or is there some simpler option that I'm missing?

I'm suggesting something like:
```
start, end := p.iter.RangeBounds()
if hasTimestamp(start) {
    start = stripTimestamp(start)
}
if hasTimestamp(end) {
    end = stripTimestamp(end).Next()
}
```

The suffixes can appear anywhere with the iteration span. Pebble may fragment the range keys into these suffixed keys because of sstable fragmentation. But because we never allow committing range keys with suffixed keys, a range key with suffixed bounds necessarily must be a physical fragment of a logical range key that covers whole user keys. We don't know the full defragmented bounds, but we do know that the entirety of the bounds' prefixes must fall within the defragmented bounds.

One consequence of the above is that you can have overlapping RangeBounds returned by `pebbleIterator`. eg, `[b@3, c@2)`, `[c@2, d)` is translated by `pebbleIterator` into `[b, c\0)` and `[c, d)`
</blockquote></details>

But in order to get the full set of suffixes and values for the current prefix I’ll have to keep iterating, so seems like we’ll have to do defragmentation here too then. A bit unfortunate, but it’s workable.


<!-- Sent from Reviewable.io -->

2022-02-09 00:37 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvQu8r-9QkGXoV_6r22:bwkksbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

But in order to get the full set of suffixes and values for the current prefix I’ll have to keep iterating, so seems like we’ll have to do defragmentation here too then. A bit unfortunate, but it’s workable.
</blockquote></details>

I don’t follow why we need to defragment? The full set of range keys for the prefix should be visible, even though the RangeBounds are narrow


<!-- Sent from Reviewable.io -->

2022-02-09 10:59 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvT5HGN-i_fLEo2msSc:b-4qp89l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I don’t follow why we need to defragment? The full set of range keys for the prefix should be visible, even though the RangeBounds are narrow
</blockquote></details>

Ah, of course. It's a bit unintuitive to map the 2D MVCC span to the 1D Pebble keyspan.

What would be a simple and deterministic way to construct this state for tests?


<!-- Sent from Reviewable.io -->

2022-02-09 11:38 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/engine.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvGBgfr-XB08vWIYNTa-r3-80:-MvTEKCe7BMYXcwpWA2S:b-92u8b8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L80)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yep, I'll be adding ample documentation on this once we have consensus that we'll be doing this PR rather than the alternative (#76090). I may defer that until after stability though, since that's backportable and we have very little time left to complete all of the MVCC bulk ops work.

>Is RangeBounds a union of all RangeKeys() overlapping at current timestamp?

The tl;dr is: Range keys and point keys exist independently, but can be iterated over in parallel. Range keys are also fragmented, such that all overlapping range keys have identical start/end bounds. So let's say we're at point c@5 where there is also a stack of range key fragments [a-f) at timestamps 1,2,3. RangeBounds() returns [a-f), Key() return c@5, RangeKeys() return 1:foo,2:bar,3:baz (or for range tombstones, simply `nil`).
</blockquote></details>

I think that's why it feels a bit off. For point keys we iterate mvcc values and next moves to next timestamp or nextkey moves to next key with highest timestamp, but rangekeys iterates over key "aggregates" exposed via RangeKeys?


<!-- Sent from Reviewable.io -->

2022-02-09 12:18 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/engine.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvGBgfr-XB08vWIYNTa-r3-80:-MvTIZ1u0D51tmMjh92V:b3bja7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L80)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I think that's why it feels a bit off. For point keys we iterate mvcc values and next moves to next timestamp or nextkey moves to next key with highest timestamp, but rangekeys iterates over key "aggregates" exposed via RangeKeys?
</blockquote></details>

Yes, they iterate over stacks of key fragments. The fragmentation is desirable at the storage layer, for example to be able to store range keys across multiple SSTs and across multiple CRDB ranges without incurring cross-SST/range read costs when accessing them. The stacking is desirable because it allows us to easily see all range keys that overlap with a given point, and also has to do with mapping the 2D MVCC keyspace onto the flat 1D Pebble keyspace and using range keys across these 1D points.

This fragmentation is one of the learnings from back when we implemented range tombstones in Pebble, you can read more about this in https://github.com/cockroachdb/pebble/blob/master/docs/rocksdb.md#range-deletions.

To iterate over defragmented range keys, which is more intuitive, use `MVCCRangeTombstoneIterator` (soon to be renamed `MVCCRangeKeyIterator`). Fragmented iteration is primarily useful for two cases: when iterating over point keys but wanting to see range keys that overlap the point, and when needing to emit partial results that can be resumed via a `ResumeSpan` (e.g. for `Export` requests). We will likely also add a point synthesizing iterator that will convert range keys that overlap points into point keys, which can then be iterated over as normal.

I'll write a few more comments about this. I'm going to flesh them out and write a tech note when I have time, but for now I need to hustle to get everything in before stability.


<!-- Sent from Reviewable.io -->

2022-02-09 14:21 UTC, sumeerbhola commented
> One consequence of the above is that you can have overlapping RangeBounds returned by pebbleIterator. eg, [b@3, c@2), [c@2, d) is translated by pebbleIterator into [b, c\0) and [c, d)

+1 to that. And I was imagining that pebbleIterator would remember that it had output up to `c\0`, so when it is on point key `cc` and has stripped the range span to `[c,d)`, it will then truncate it to `[c\0,d)`. Though perhaps no one upstream is relying on this behavior of the range spans being non-overlapping.

2022-02-09 14:26 UTC, erikgrinaker reviewed
Ok, I've cleaned up the PR, the only remaining bit is to handle these odd range bounds -- I'll add that once I get a test case set up.

>I was imagining that pebbleIterator would remember that it had output up to c\0, so when it is on point key cc and has stripped the range span to [c,d), it will then truncate it to [c\0,d). Though perhaps no one upstream is relying on this behavior of the range spans being non-overlapping.

Yeah, that makes sense. I think that's a nice and intuitive guarantee to provide in an iterator.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-MvTrhbM6An9eDplx6oP:b9mi7fu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-09 15:48 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvU90OGCxenIN14XBG0:b-do74k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
> What would be a simple and deterministic way to construct this state for tests?

I don't think we have a way right now, since this type of fragmentation is only possible with persistence.

Pebble doesn't yet enforce that the keys provided to RangeKeySet, RangeKeyUnset and RangeKeyDelete are prefixes, so I suppose you could just set fragments with those narrower bounds for now. Once we add sstable persistence, I think we can update the test to fiddle with pebble Options to force sstable splits where we want them.


<!-- Sent from Reviewable.io -->

2022-02-09 15:54 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvUBEk9-U3N_cLlcWv_:b-8e1wn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> What would be a simple and deterministic way to construct this state for tests?

I don't think we have a way right now, since this type of fragmentation is only possible with persistence.

Pebble doesn't yet enforce that the keys provided to RangeKeySet, RangeKeyUnset and RangeKeyDelete are prefixes, so I suppose you could just set fragments with those narrower bounds for now. Once we add sstable persistence, I think we can update the test to fiddle with pebble Options to force sstable splits where we want them.
</blockquote></details>

Got it, thanks. This is stuff we can fix during stability, so I'll try to write up a small test but otherwise just stick in a TODO and work on some other stuff in the meanwhile.


<!-- Sent from Reviewable.io -->

2022-02-10 14:47 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvYtz5_3B-CxtgiiPSx:b-996gqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
> +1 to that. And I was imagining that pebbleIterator would remember that it had output up to c\0, so when it is on point key cc and has stripped the range span to [c,d), it will then truncate it to [c\0,d). Though perhaps no one upstream is relying on this behavior of the range spans being non-overlapping.

This is pretty annoying. Consider an SST boundary at`c@5`, so a range key `[b-e)` will look like `[b-c@5)`, `[c@5-e)`. Now consider there are also point keys at `c@6` and `c@5`. When iterating forwards, we would then claim:

`c@6`: RangeBounds `[b-c@5)` -> `[b-c\0)`
`c@5`: RangeBounds `[c@5-e)` -> `[c\0-e)`

The result `c@5` is incorrect, because the claimed range bounds `[c\0-e)` do not overlap the point at `c@5`. Sure, we can store the previous and current bounds somewhere and compare as we iterate to decide which bound to use, but what if we seek to `c@5`? We would then have to backtrack to find the proper bounds, which could get expensive.

At this point, I'm inclined to return overlapping bounds and slap a TODO on this. This also seems safer: the logic for non-overlapping bounds could get non-trivial for all corner cases, and it seems less scary to accidentally overlap two range keys than to accidentally leave a gap between them. I think the only component outside of MVCC that needs to iterate over fragmented range keys is `Export`. We can revisit if it turns out to be a problem, although I definitely think it's unfortunate.

One other idea I had was that if we knew whether there were point keys for the boundary key (i.e. at `c`) then we could differentiate the behavior depending on the iteration mode: with `PointsAndRanges` we can split the span into `[b-c)`, `[c-c\0)`, `[c\0-e)` and then look at the current point key to know which bounds to use. With `RangesOnly`, we would split it into `[b-c\0)`, `[c\0-e)`. But is that an assumption we can make? The risk here is that if there are no point keys in `[c-c\0)` then we'll leave a gap -- I'd imagine things like timebound iterators could cause trouble here, unless perhaps if we lift this down into Pebble which would always have access to this info?


<!-- Sent from Reviewable.io -->

2022-02-10 15:27 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvZEaWt2RIDQU2daTJI:be48g4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
> At this point, I'm inclined to return overlapping bounds and slap a TODO on this.

I've updated the PR with this now. However, this can cause us to later ingest these overlapping bounds into Pebble, because the overlapping bounds will be exported into backup SSTs. Is this a problem?


<!-- Sent from Reviewable.io -->

2022-02-10 16:03 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvZAVxJ0JP-3Cs3M9ow:b-71k2g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
> We would then have to backtrack to find the proper bounds, which could get expensive.

I've been wrestling with a similar problem while integrating range keys into the Pebble metamorphic tests. I've been truncating the range key bounds to the seek key, but there's a lot of complexity, especially if you switch directions.

> However, this can cause us to later ingest these overlapping bounds into Pebble, because the overlapping bounds will be exported into backup SSTs. Is this a problem?

Do you mean overlapping bounds will be written to a single SST backup writer? Or that a backup may generate two adjacnet SSTs that contain overlapping bounds?

I think both are currently a problem, but the former could be solved by some small changes to the SST writer/range key coalescer. I think the latter is a problem, because the sstables would overlap and can't be ingested atomically if they overlap.

----

@sumeerbhola What do you think about defragmenting the range keys during iteration within Pebble, _before_ interleaving. Since we now have a separate iterator stack (separate level iter, merging iter, etc), we can defragment without the complexity of point keys.

If we implement this [TODO](https://github.com/cockroachdb/pebble/blob/b2295acd0a1514efd11b08bc9a43be073144245f/internal/rangekey/iter.go#L13-L16) we only need to pay the cost if there is indeed a range key. In practice, we expect very few overlapping range keys (at least for MVCCDeleteRange), so the cost should be dominated by how broad the range key(s) we do have are, which impacts how many sstables' range-key blocks we need to read.


<!-- Sent from Reviewable.io -->

2022-02-10 16:11 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)

___
*[pkg/storage/pebble_iterator.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP9Zh88RJ1PE1iJ3u_:-MvZOLPs4fsXAw7TkMLA:byj03oy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/pebble_iterator.go#L587)):*
> However, this can cause us to later ingest these overlapping bounds into Pebble, because the overlapping bounds will be exported into backup SSTs. Is this a problem?
> 
> Do you mean overlapping bounds will be written to a single SST backup writer? Or that a backup may generate two adjacnet SSTs that contain overlapping bounds?
> I think both are currently a problem, but the former could be solved by some small changes to the SST writer/range key coalescer. I think the latter is a problem, because the sstables would overlap and can't be ingested atomically if they overlap.

Yep, both can happen. And as you point out, the first is solvable (we can defragment before writing them) while the other is harder to handle. So maybe we should just bite the bullet and handle this inside MVCC/Pebble, rather than leaking this complexity everywhere.


<!-- Sent from Reviewable.io -->

2022-02-10 21:07 UTC, sumeerbhola commented
> @sumeerbhola What do you think about defragmenting the range keys during iteration within Pebble, before interleaving.

So the main cost would be pulling in all the `Reader`s into the `TableCache` if there was a wide range key?
It seems acceptable. If we find any performance regressions, we can bump up the TableCache size.

How does this defragmentation compose with the current interface where we expose one [start,end) in `Iterator.RangeBounds`. If we've defragmented `[a,f)@20` and `[b,h)@10` and we are at key `c` we have two overlapping range keys with different bounds. I guess what we could do is fragment them relative to each other, giving us `[b,f)` at key `c`. That would be deterministic because it is purely a function of the data and not how we split it across sstables. There would be a concern about potentially having to hold a lot of range keys in-memory.

2022-02-10 21:40 UTC, sumeerbhola commented
- I'm sympathetic to solving this in Pebble, given that Pebble semantics are already strong enough (the original range keys are defined over prefixes).
- I'm somewhat wary of fully defragmenting range keys, but could be convinced that it is the right thing to do. I realize there are testing benefits. @jbowens I'd like to understand the difficulties you are facing with metamorphic testing. This may be easier to discuss in a synchronous chat.
- We don't have ImmediateSuccessor defined in Pebble, but we have in CockroachDB. For iteration cleanliness, we could require that the Pebble user provide an (efficient) ImmediateSuccessor on the key prefix. Then Pebble could fragment range keys that overlap a point at `c` into `[c, IS(c))`, `[IS(c), ...)`. So the behavior of pebble.Iterator when there is a point at the current position would be to always expose a single-key range (if there are any range keys). This also trivially makes the bounds at the point key deterministic. Between 2 adjacent point keys, the range key bounds that get exposed would continue to be non-deterministic (the metamorphic test could iterate until the next point and buffer the range keys and defragment them to make them deterministic), but the points provide a deterministic output anchor.

2022-02-10 22:03 UTC, jbowens reviewed
> There would be a concern about potentially having to hold a lot of range keys in-memory.

Defragmenting would still use a constant multiple of the non-defragmenting implementation, right? The merging iterator already needs to hold in-memory every range-key block overlapping the current position. The defragmenting iterator only needs to hold at most one additional block per-level?

> I'd like to understand the difficulties you are facing with metamorphic testing. This may be easier to discuss in a synchronous chat.

Sure, let's chat.

I'm pretty inclined to defragment, for testing benefits as well as interface simplicity. I'd like to explore it a little more to see exactly what the tradeoff would be.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-Mv_ZjMK3HYSODpix6Bg:b15gn7e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-10 22:05 UTC, jbowens reviewed
We also have the option of keeping Pebble defragmentation optional, configured through an iterator option.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-Mv_eoIe8mWWI72A9wvy:b-589ddp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-11 11:27 UTC, erikgrinaker reviewed
> I'm somewhat wary of fully defragmenting range keys, but could be convinced that it is the right thing to do. I realize there are testing benefits.

In CRDB, we'll be using both.

For tests and functionality that exposes range keys as a distinct entity we'll primarily use defragmented range keys (but of course, these will get fragmented by CRDB range bounds, so it's fragments all the way up). Whether we do this in CRDB or Pebble is largely immaterial.

However, with export/backup we'll need some form of fragmentation, because as we're scanning across the key span the export can end at any moment (once we hit e.g. a byte limit) so we need to emit range keys and point keys in unison until we hit the limit, return the response, and then resume from the next key. Thus it would be great to defragment across SST bounds, but we still need these overlapping range key fragment stacks to be able to see all the range keys at a given point without iterating further ahead. The same is true when only iterating over range keys.

Here's an added twist: exports allow resumption in the middle of a key (i.e. between two timestamps). The next export will then resume from the next timestamp. This essentially gives the same problem that we had with SST boundaries: if we export up until `c@5`, returning a resume span from `c@5`, then the first export will include range keys that overlap `[a-c@5)`, and the second `[c@5-e)`. However, since we can only write range keys with prefixes, this means that the SSTs we output (and later ingest) will overlap as `[a-c\0)` and `[c-e)`.

A couple of alternative options:

* We could flatten the range key API by defining it between `MVCCKey` bounds, such that range key bounds can fall between two timestamps, like in Pebble. This would eliminate the impedance mismatch, and it would only affect callers who care about fragmented range keys (MVCC internals and exports).

* We could export range keys separately from point keys during backups. This would export defragmented keys, which yields space savings (we avoid all of the intermediate keys, and for future non-`nil` values, the value duplication), avoid the fragmentation issues including the suffixed boundary leaks, and significantly simplifies the logic. However, it does mean that any given key span will require two distinct exports/imports to be complete.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-MvcQZPW3Lp03FoFs9xY:b-pnqy7b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-11 11:28 UTC, erikgrinaker reviewed
> This may be easier to discuss in a synchronous chat.

I think I'd like to join a sync chat around these issues too. Set something up for Monday?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-MvcXT6pAEjcsviCaF3H:b-6lyr52)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-11 20:03 UTC, nicktrav reviewed
> Reviewed 20 of 20 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, 12 of 12 files at r4, 10 of 10 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @sumeerbhola, and @ts)

___
*[pkg/storage/mvcc.go, line 3967 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mvdx5_c5KejPXsG3QCZ:-Mvdx5_c5KejPXsG3QC_:bf5hjtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/68539f9db07c2f16898c35d19befe3913b0ce0a5/pkg/storage/mvcc.go#L3967)):*
> ```Go
> 
> // MVCCScanRangeTombstones returns a list of range tombstones across the given
> // span at the given timestamp, in end,timestamp order rather that
> ```

typo: s/that/than/
___
*[pkg/storage/mvcc_key_test.go, line 289 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MveMfxR6JilmcAKyEbw:-MveMfxS-OI0x9a2SWl_:bn2h82n) ([raw file](https://github.com/cockroachdb/cockroach/blob/68539f9db07c2f16898c35d19befe3913b0ce0a5/pkg/storage/mvcc_key_test.go#L289)):*
> ```Go
> 		"empty time lt set":     {bc0, bc1, -1}, // empty MVCC timestamps sort before non-empty
> 		"set time gt empty":     {bc1, bc0, 1},  // empty MVCC timestamps sort before non-empty
> 		"start time precedence": {ac2, bc3, -1},
> ```

Isn't this test case testing that a < b, and not exercising the timestamp part. Would a more indicative test case have the same start key?
___
*[pkg/storage/mvcc_range_key_iterator.go, line 45 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvdytgB0FaVVuTY7sCg:-MvdytgB0FaVVuTY7sCh:bfzweai) ([raw file](https://github.com/cockroachdb/cockroach/blob/68539f9db07c2f16898c35d19befe3913b0ce0a5/pkg/storage/mvcc_range_key_iterator.go#L45)):*
> ```Go
> 
> // MVCCRangeKeyIterator is an iterator over range keys in an engine. Unlike
> // SimpleMVCCIterator, range key are defragmented into contiguous deterministic
> ```

typo: s/range key/range keys/


<!-- Sent from Reviewable.io -->

2022-02-11 20:19 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @nicktrav, @sumeerbhola, and @ts)

___
*[pkg/storage/mvcc_key_test.go, line 289 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MveMfxR6JilmcAKyEbw:-MveQPAP9SHlxzfP0yW6:brchv6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/68539f9db07c2f16898c35d19befe3913b0ce0a5/pkg/storage/mvcc_key_test.go#L289)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Isn't this test case testing that a < b, and not exercising the timestamp part. Would a more indicative test case have the same start key?
</blockquote></details>

It's testing that the start key takes precedence over the timestamp. Here, the start key of `ac2` is ordered before `bc3`, but the timestamp of `bc3` is ordered before `ac2` (MVCC orders timestamps in reverse), and we want the start key to take precedence. I added a couple of comments to clarify this.


<!-- Sent from Reviewable.io -->

2022-02-11 20:34 UTC, nicktrav reviewed
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @sumeerbhola, and @ts)

___
*[pkg/storage/mvcc_key_test.go, line 289 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MveMfxR6JilmcAKyEbw:-MveTuT1-6APkW5IvtWm:b3xnzzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/68539f9db07c2f16898c35d19befe3913b0ce0a5/pkg/storage/mvcc_key_test.go#L289)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

It's testing that the start key takes precedence over the timestamp. Here, the start key of `ac2` is ordered before `bc3`, but the timestamp of `bc3` is ordered before `ac2` (MVCC orders timestamps in reverse), and we want the start key to take precedence. I added a couple of comments to clarify this.
</blockquote></details>

I misinterpreted the test case description. :thumbsup: on the comments.


<!-- Sent from Reviewable.io -->

2022-02-11 21:32 UTC, sumeerbhola commented
> Defragmenting would still use a constant multiple of the non-defragmenting implementation, right? The merging iterator already needs to hold in-memory every range-key block overlapping the current position. The defragmenting iterator only needs to hold at most one additional block per-level?

I may be missing the meaning of "defragmentation" -- if there is a wide MVCC tombstone that covers the whole CockroachDB range and many small tombstones, won't all the small ones need to be held in-memory?

> Here's an added twist: exports allow resumption in the middle of a key (i.e. between two timestamps). The next export will then resume from the next timestamp. ... We could export range keys separately from point keys during backups.

Hmm, that is indeed a twist. I'm ok with these two separate scans. But isn't there an issue even with that in that we want non-overlapping sstables for export?

> I think I'd like to join a sync chat around these issues too. Set something up for Monday?

Yes please!

2022-02-12 01:08 UTC, jbowens reviewed
> I may be missing the meaning of "defragmentation" -- if there is a wide MVCC tombstone that covers the whole CockroachDB range and many small tombstones, won't all the small ones need to be held in-memory?

Ah, sorry, I was being unclear and have been so focused on the fragmentation introduced by sstable-splits that I forgot we also use the term for splitting overlapping spans.

I'm thinking of specifically defragmenting the physical fragmentation introduced by sstable splits. At iteration time Pebble would defragment up to the next change in range key state (so up to the next small tombstone in the above example). This would produce deterministic bounds surfaced during iteration. The only keys that may be surfaced by `RangeBounds()` are keys that are currently bounds for some active, set range key.

Here's what I had in mind: cockroachdb/pebble#1509.

I prefer this to defragmenting above `*pebble.Iterator` because it avoids all the complexity of:
* point keys
* `WithLimit` variants
* range key bounds that may be exactly overlapping (when there are point keys)

> > I think I'd like to join a sync chat around these issues too. Set something up for Monday?
>
> Yes please!

Scheduled!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-Mv_h8UjCRAHjqI4aQYi:b-c5sutg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @nicktrav, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-12 15:01 UTC, erikgrinaker reviewed
>I'm thinking of specifically defragmenting the physical fragmentation introduced by sstable splits. At iteration time Pebble would defragment up to the next change in range key state

I think this would be great, as long as we can come up with a solution for exports/backups. I can't think of anything else that would need mid-key range bounds.

The seek/reversal truncation semantics on that PR deserve a bit more consideration. I don't _think_ they should be a problem, and they're probably worth the performance/complexity win -- and I suppose if anything did come up we could likely handle it during `MVCCRangeKeyIterator` defragmentation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-MviPfgz6b88OSUjycNN:b-tvwyrs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @nicktrav, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-16 16:56 UTC, erikgrinaker commented
@jbowens @sumeerbhola I'd like to get this merged to unblock some work on other teams, mind giving this a review?

For backups, it turns out that overlapping SST range keys is fine (on restore we build new SSTs for ingestion), so I'm going to try the simple thing of mixing range keys and point keys during exports. That shouldn't really affect anything on the Pebble side either way.

2022-02-16 18:40 UTC, jbowens reviewed
> Reviewed 2 of 20 files at r1, 1 of 8 files at r2, 2 of 12 files at r4, 3 of 10 files at r5, 1 of 1 files at r10, 3 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @nicktrav, @sumeerbhola, and @ts)

___
*[pkg/storage/engine.go, line 116 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2YFnB0MYvMwqETqaV:-Mw2YFnB0MYvMwqETqaW:b-4wu3x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/engine.go#L116)):*
> ```Go
> 	// internal SST structure (which changes with compactions) and the store's
> 	// write history. They will also split and merge along with CRDB ranges, can
> 	// be partially removed by GC, and may be truncated by iterator bounds.
> ```

nit: leave a TODO to update this comment and the `RangeBounds()` comment once determinism is merged, and we're guaranteed to have deterministic non-overlapping bounds?
___
*[pkg/storage/engine.go, line 615 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2ZqL94afb-dfmIaSD:-Mw2ZqL94afb-dfmIaSE:b-nkwvoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/engine.go#L615)):*
> ```Go
> 	//
> 	// It is safe to modify the contents of the arguments after it returns.
> 	ClearRawRange(start, end roachpb.Key) error
> ```

Where will `RangeKeyDelete(a, b)` come into play? Is it in `ClearRawRange`? AFAIK, we only need `RangeKeyDelete` for replica removal, at which point we want to lay down both a Pebble `RANGEDEL` and a `RANGEKEYDELETE`.
___
*[pkg/storage/engine.go, line 634 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2ZSAi2PoUzD2D_82z:-Mw2ZSAi2PoUzD2D_83-:b-vrnlg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/engine.go#L634)):*
> ```Go
> 	//
> 	// Note that when used on batches, subsequent reads may not reflect the result
> 	// of the ClearMVCCRange.
> ```

I think this came up somewhere else recently, but I believe this comment is outdated. Pebble range tombstones written to an indexed batch _will_ hide covered points.
___
*[pkg/storage/engine.go, line 637 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2Z25O-Zach-J6WN07:-Mw2Z25O-Zach-J6WN08:b-d2fu8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/engine.go#L637)):*
> ```Go
> 	//
> 	// It is safe to modify the contents of the arguments after it returns.
> 	ClearMVCCRange(start, end MVCCKey) error
> ```

Should `ClearMVCCRange`'s comment be clarified that it exclusively removes point keys, and does not remove MVCC range keys?
___
*[pkg/storage/mvcc.go, line 2235 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2_dF11EvYoACwxZLb:-Mw2_dF11EvYoACwxZLc:bupdifv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/mvcc.go#L2235)):*
> ```Go
> 	}
> 	return rw.ExperimentalPutMVCCRangeKey(MVCCRangeKey{
> 		StartKey: startKey, EndKey: endKey, Timestamp: timestamp}, nil)
> ```

I'm mildly bothered by the fact that these `MVCCDeleteRange` range keys have nothing recording the fact that they are a `MVCCDeleteRange` and not some future kind of range key. Here, and within range-key masking in Pebble, we're assuming that we'll never have another use case for writing a new kind of range key to the user key space with a suffix.

I suppose if we ever had another use case for range keys within the user key space, we could require it have a non-empty value and adjust Pebble to only mask value-less range keys.
___
*[pkg/storage/mvcc_key.go, line 354 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2brc2DZF8HtvM0wIp:-Mw2brc2DZF8HtvM0wIq:b-h1eo5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/mvcc_key.go#L354)):*
> ```Go
> 		return errors.Errorf("no timestamp")
> 	}
> 	if k.StartKey.Compare(k.EndKey) > 0 {
> ```

Shouldn't this be `>= 0` since the `EndKey` is exclusive?
___
*[pkg/storage/pebble_iterator.go, line 339 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2ow-s03z0VRmbUI3S:-Mw2ow-s03z0VRmbUI3T:b3gylgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/pebble_iterator.go#L339)):*
> ```Go
> 	if ok := p.iter.Valid(); ok {
> 		// TODO(erikgrinaker): Pebble does not seem to respect bounds for range
> 		// keys, so for now we invalidate the iterator here instead.
> ```

This sounds like a Pebble bug. Is this definitely still the case? I can look into it.
___
*[pkg/storage/mvcc_range_key_iterator.go, line 29 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2eaSv5au3IWdyndAF:-Mw2eaSv5au3IWdyndAG:b7t1n68) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/mvcc_range_key_iterator.go#L29)):*
> ```Go
> 	// this would be pointless: giving e.g. a@4 would skip a range key starting at
> 	// a@5, but the range key would logically exist at the adjacent a.Next()@5 so
> 	// it would be emitted almost immediately anyway.
> ```

Should Pebble require iterator bounds be prefixes if `IterKeyType` is `IterKeyTypeRangesOnly` or `IterKeyTypePointsAndRanges`? Otherwise, the truncation to bounds could surface MVCC keys in `RangeBounds()`.


<!-- Sent from Reviewable.io -->

2022-02-16 20:32 UTC, erikgrinaker reviewed
> Dismissed @aliher1911 and @sumeerbhola from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @nicktrav, @sumeerbhola, and @ts)

___
*[pkg/storage/engine.go, line 116 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2YFnB0MYvMwqETqaV:-Mw3EBR6AW80-ZlnJZI3:b9ba0xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/engine.go#L116)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: leave a TODO to update this comment and the `RangeBounds()` comment once determinism is merged, and we're guaranteed to have deterministic non-overlapping bounds?
</blockquote></details>

Will do, thanks.
___
*[pkg/storage/engine.go, line 615 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2ZqL94afb-dfmIaSD:-Mw36z_v6yutiiM_Wqrm:b-p3x8o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/engine.go#L615)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Where will `RangeKeyDelete(a, b)` come into play? Is it in `ClearRawRange`? AFAIK, we only need `RangeKeyDelete` for replica removal, at which point we want to lay down both a Pebble `RANGEDEL` and a `RANGEKEYDELETE`.
</blockquote></details>

Thanks for bringing this up. Replica removal sounds right. I haven't thought that far yet, but we'll possibly add a separate method for it. I don't know if we can use `ClearRawRange` since that can also be used on timestamped keys. But I'm going to look into range splits/merges and such shortly, and will keep this in mind.
___
*[pkg/storage/engine.go, line 634 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2ZSAi2PoUzD2D_82z:-Mw39949BgnffQ7D3Qny:b-uyyw7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/engine.go#L634)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think this came up somewhere else recently, but I believe this comment is outdated. Pebble range tombstones written to an indexed batch _will_ hide covered points.
</blockquote></details>

Yeah, came out of a recent postmortem. I'll submit a PR to clean it up, thanks.
___
*[pkg/storage/engine.go, line 637 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2Z25O-Zach-J6WN07:-Mw39FA-CcVztDPwVwo4:b-a9ux4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/engine.go#L637)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Should `ClearMVCCRange`'s comment be clarified that it exclusively removes point keys, and does not remove MVCC range keys?
</blockquote></details>

Probably, once we clarify the semantics. The biggest part of implementing MVCC range keys will be to review all of the existing MVCC/storage/KV APIs and make them handle range keys in a reasonable way. For now, none of the APIs handle them, so it's kind of meaningless to point it out (we'd have to point it out on everything). This will likely happen during the stability period, and possibly into the 22.1 release.
___
*[pkg/storage/mvcc.go, line 2235 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2_dF11EvYoACwxZLb:-Mw39vd4A7I9RtCZtlAt:b-5l6olh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/mvcc.go#L2235)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'm mildly bothered by the fact that these `MVCCDeleteRange` range keys have nothing recording the fact that they are a `MVCCDeleteRange` and not some future kind of range key. Here, and within range-key masking in Pebble, we're assuming that we'll never have another use case for writing a new kind of range key to the user key space with a suffix.

I suppose if we ever had another use case for range keys within the user key space, we could require it have a non-empty value and adjust Pebble to only mask value-less range keys.
</blockquote></details>

Yeah. But we'd likely want the caller to control that anyway, e.g. by registering a masking callback or value filter or something, I think?
___
*[pkg/storage/mvcc_key.go, line 354 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2brc2DZF8HtvM0wIp:-Mw3AHvE-H32wNCNM26s:brfovcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/mvcc_key.go#L354)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Shouldn't this be `>= 0` since the `EndKey` is exclusive?
</blockquote></details>

We allow zero-length ranges elsewhere in our APIs, e.g. it's valid to request a scan over the range [a-a) which will be empty. So I've allowed this for range keys too, for consistency. Of course, it'll essentially be a noop.
___
*[pkg/storage/pebble_iterator.go, line 339 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2ow-s03z0VRmbUI3S:-Mw3DghTE6VhCmJiOJiE:bptzn9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/pebble_iterator.go#L339)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This sounds like a Pebble bug. Is this definitely still the case? I can look into it.
</blockquote></details>

Yes, I believe so. Try commenting it out and run `TestMVCCRangeKeyIterator`, and you'll see lots of test cases go into infinite loops. When I looked into it a while ago, it seemed like calling `.Next()` when positioned at the last range key fragment of a bounded iterator would place the iterator back at the last fragment again, leading to an infinite loop. But I didn't look at it too closely.
___
*[pkg/storage/mvcc_range_key_iterator.go, line 29 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2eaSv5au3IWdyndAF:-Mw3AsNwAfBuFc8L_d1U:bc1hca9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/mvcc_range_key_iterator.go#L29)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Should Pebble require iterator bounds be prefixes if `IterKeyType` is `IterKeyTypeRangesOnly` or `IterKeyTypePointsAndRanges`? Otherwise, the truncation to bounds could surface MVCC keys in `RangeBounds()`.
</blockquote></details>

I'm a bit worried about backwards compatibility -- we'll enable `IterKeyTypePointsAndRanges` by default on lots of existing iterators on the read path, and I don't want to have to audit them all to make sure they don't use versioned bounds. Maybe we never do, but I'll have to look into it. Can we punt this decision for later? I'll keep it in mind and add some guards/handling for this in the MVCC iterator.


<!-- Sent from Reviewable.io -->

2022-02-16 20:44 UTC, sumeerbhola reviewed
> For backups, it turns out that overlapping SST range keys is fine (on restore we build new SSTs for ingestion)

Can you point me to the relevant CockroachDB code. I am curious how we are merging these ssts now (I vaguely remember seeing an sst merging iterator, but I can't find it -- I might have imagined it).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-Mw3G6i67KN2TNBRp4x_:b-n8twz0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @nicktrav, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-16 20:56 UTC, sumeerbhola reviewed
never mind, I found `multiIterator`. I think we'll need to change that code since we don't want to repeat the fragmenting logic in the CockroachDB code. I think we should expose a Pebble provided "merging iterator" that can be used to merge the various ssts. And then wrap the MVCC code on top of it. We should probably standardize on `InternalIterator` as the one unifying raw read interface, over which such merging operates, instead of things like `sstable.Iterator`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-Mw3HQkd3ycZWJU_Nnsk:b-pa3oll)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @nicktrav, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-16 21:01 UTC, erikgrinaker reviewed
Yeah, that makes sense -- would be great to avoid duplicating that in CRDB. But for restore, we'd want it to be tolerant of key collisions, which in the range key case would mean merging the range keys (as long as they have identical values). We'd also ideally want to do range key masking here, because restore only cares about the latest visible point key, which I think we might get for free by using `InternalIterator`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-Mw3JbAuEx_Y-SDr6To5:b-tf94jp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @nicktrav, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-16 21:03 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @nicktrav, @sumeerbhola, and @ts)

___
*[pkg/storage/engine.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP4dCi8crey62ZYRdX:-Mw3Kpaa8oFjFYIpW9Rx:b-h2s9be) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L78)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I suppose yes. But we have less than 3 weeks to get all of the MVCC range tombstone functionality in and migrate all callers, so I won't be spending time on any related cleanups now. We can do that for 22.2.
</blockquote></details>

Can you add a TODO to fix this later. I worry about technical debt in interfaces (not that you are responsible for what we have already accrued).


<!-- Sent from Reviewable.io -->

2022-02-16 21:04 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @nicktrav, @sumeerbhola, and @ts)

___
*[pkg/storage/engine.go, line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-MvP4dCi8crey62ZYRdX:-Mw3LOgq4fehIIxh15gM:b-louncl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83ced0d527f86872787b272a937adfab5cccb06/pkg/storage/engine.go#L78)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a TODO to fix this later. I worry about technical debt in interfaces (not that you are responsible for what we have already accrued).
</blockquote></details>

Yes, will do.


<!-- Sent from Reviewable.io -->

2022-02-17 00:10 UTC, jbowens approved these changes
>  I think we should expose a Pebble provided "merging iterator" that can be used to merge the various ssts.

This one 'merging iterator' would avoid the need for exposing an iter off the `sstable.Reader` that wraps using the interleaving iterator, right? [https://github.com/cockroachdb/pebble/pull/1513#pullrequestreview-883304335](https://github.com/cockroachdb/pebble/pull/1513#pullrequestreview-883304335)

Do we want to do this right now? I'm unclear on how much of a lift it'll be to adapt the Pebble point `mergingIter` for this use.

Should this interface take `vfs.File`s (so that we can construct point and range key iterators as necessary), or we could explicitly take separate sets of point iterators and range key iterators (and I'm assuming _no_ rangedel iterators.).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-Mw3y4fH2fKs4b0M5xPB:bqse3ej)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @nicktrav, @sumeerbhola, and @ts)

___
*[pkg/storage/engine.go, line 637 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2Z25O-Zach-J6WN07:-Mw4-I5l2p_kX9Dwcwuc:b-hfghm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/engine.go#L637)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Probably, once we clarify the semantics. The biggest part of implementing MVCC range keys will be to review all of the existing MVCC/storage/KV APIs and make them handle range keys in a reasonable way. For now, none of the APIs handle them, so it's kind of meaningless to point it out (we'd have to point it out on everything). This will likely happen during the stability period, and possibly into the 22.1 release.
</blockquote></details>

Sounds good
___
*[pkg/storage/mvcc.go, line 2235 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2_dF11EvYoACwxZLb:-Mw4-Nw43i6RiUKvyM5r:bpsuj28) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/mvcc.go#L2235)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yeah. But we'd likely want the caller to control that anyway, e.g. by registering a masking callback or value filter or something, I think?
</blockquote></details>

Yeah, for sure. I guess empty-value mapping to delete makes sense and mirrors point deletes. Seems fine.
___
*[pkg/storage/mvcc_key.go, line 354 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2brc2DZF8HtvM0wIp:-Mw4-dMGDJG4k6IgELAp:b9pn419) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/mvcc_key.go#L354)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

We allow zero-length ranges elsewhere in our APIs, e.g. it's valid to request a scan over the range [a-a) which will be empty. So I've allowed this for range keys too, for consistency. Of course, it'll essentially be a noop.
</blockquote></details>

Ok, I'll need to double check Pebble's behavior here. We might not tolerate them well at the moment.
___
*[pkg/storage/pebble_iterator.go, line 339 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2ow-s03z0VRmbUI3S:-Mw4-wiSDUTHxJqAobZz:bsilr3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/pebble_iterator.go#L339)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yes, I believe so. Try commenting it out and run `TestMVCCRangeKeyIterator`, and you'll see lots of test cases go into infinite loops. When I looked into it a while ago, it seemed like calling `.Next()` when positioned at the last range key fragment of a bounded iterator would place the iterator back at the last fragment again, leading to an infinite loop. But I didn't look at it too closely.
</blockquote></details>

Got it, I'll look into it.
___
*[pkg/storage/mvcc_range_key_iterator.go, line 29 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2eaSv5au3IWdyndAF:-Mw4-uaj0hFQf7WYS0Jn:b-djz89u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/mvcc_range_key_iterator.go#L29)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I'm a bit worried about backwards compatibility -- we'll enable `IterKeyTypePointsAndRanges` by default on lots of existing iterators on the read path, and I don't want to have to audit them all to make sure they don't use versioned bounds. Maybe we never do, but I'll have to look into it. Can we punt this decision for later? I'll keep it in mind and add some guards/handling for this in the MVCC iterator.
</blockquote></details>

Yeah, let's punt.


<!-- Sent from Reviewable.io -->

2022-02-17 08:07 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @nicktrav, @sumeerbhola, and @ts)

___
*[pkg/storage/mvcc_key.go, line 354 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-Mw2brc2DZF8HtvM0wIp:-Mw5hfkL3RMGhWWaQxjv:b-7crsmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d961ad669dcc1f1950b53e2c472a7a23c5d8453/pkg/storage/mvcc_key.go#L354)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Ok, I'll need to double check Pebble's behavior here. We might not tolerate them well at the moment.
</blockquote></details>

I'd be fine with checking this in MVCC too and dropping the Pebble call.


<!-- Sent from Reviewable.io -->

2022-02-18 09:04 UTC, erikgrinaker reviewed
I take it you were asking Sumeer here, but I'll throw in my 2c.

>This one 'merging iterator' would avoid the need for exposing an iter off the sstable.Reader that wraps using the interleaving iterator, right? cockroachdb/pebble#1513 (review)

Yes. If this merging iterator allows us to use an arbitrary number of SSTs (including 1) with mixed point and range keys and interleaved iteration then that covers our needs. Masking would be a nice-to-have that we can punt for now.

>Do we want to do this right now? I'm unclear on how much of a lift it'll be to adapt the Pebble point mergingIter for this use.

We're going to want interleaved point/range key iteration in SSTs for backup/restore, and we'd like to get the restore code updated and merged before stability if possible (i.e. during next week).

We can either do the SST merging in CRDB or in Pebble, but we're going to need it somewhere. If we do the merging in CRDB then we'll have to reimplement the interleaving logic on top of the merging logic, so it seems advantageous to do it in Pebble where we can hopefully reuse some of the existing logic.

>Should this interface take vfs.Files (so that we can construct point and range key iterators as necessary), or we could explicitly take separate sets of point iterators and range key iterators (and I'm assuming no rangedel iterators.).

I don't really have a strong or informed opinion here, but I think we're usually holding binary SST data so `vfs.File` seems reasonable. Would there be an advantage to taking iterators?

> Dismissed @aliher1911 and @sumeerbhola from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76131#-:-MwB0fTd24EgywTqeVyI:bfyt0zs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @50, @aliher1911, @erikgrinaker, @jbowens, @nicktrav, @sumeerbhola, and @ts)



<!-- Sent from Reviewable.io -->

2022-02-21 18:16 UTC, erikgrinaker commented
bors r=jbowens,sumeerbhola,nicktrav

TFTRs!

2022-02-21 19:18 UTC, merged