[WIP] Stats collection details added to Database pages
cockroachdb/cockroach pull request #76168
Opened 2022-02-07 16:38 UTC by ericharmeling

Closes: #67510

Release justification: low-risk, high benefit changes to
existing functionality

Release note (ui change):
- Added status of automatic statistics collection to the Database
and Database table pages on the DB Console.
- Added timestamp of last statistics collection to the Database
details and Database table pages on the DB Console.

2022-02-07 16:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76168)
<!-- Reviewable:end -->

2022-02-08 19:55 UTC, ericharmeling commented
I am having trouble getting the ui tests to pass for the pages I updated... And the [error messages](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_CheckGeneratedCode/4329966?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=4329966_1597_247.655.4319&logFilter=debug) aren't super helpful to me.

```
[18:50:25] :		 [Test web UI] ✖ 4 tests failed
[18:50:25] :		 [Test web UI] 
[18:50:25] :		 [Test web UI] FAILED TESTS:
[18:50:25] :		 [Test web UI]   Database Details Page
[18:50:25] :		 [Test web UI]     ✖ makes a row for each table
[18:50:25] :		 [Test web UI]       Chrome Headless 97.0.4692.71 (Linux x86_64)
[18:50:25] :		 [Test web UI]     AssertionError: { loading: false,
[18:50:25] :		 [Test web UI]       loaded: true,
[18:50:25] :		 [Test web UI]       name: 'things',
[18:50:25] :		 [Test web UI]       showNodeRegionsColumn: false,
[18:50:25] :		 [Test web UI]       viewMode: 'Tables',
[18:50:25] :		 [Test web UI]       sortSettingTables: { deepEqual { loading: false,
[18:50:25] :		 [Test web UI]       loaded: true,
[18:50:25] :		 [Test web UI]       name: 'things',
[18:50:25] :		 [Test web UI]       showNodeRegionsColumn: false,
[18:50:25] :		 [Test web UI]       viewMode: 'Tables',
[18:50:25] :		 [Test web UI]       sortSettingTables: {
[18:50:25] :		 [Test web UI]         at TestDriver.assertProperties (webpack-internal:///./src/views/databases/databaseDetailsPage/redux.spec.ts:114:53)
[18:50:25] :		 [Test web UI]         at _callee4$ (webpack-internal:///./src/views/databases/databaseDetailsPage/redux.spec.ts:241:22)
[18:50:25] :		 [Test web UI]         at tryCatch (webpack-internal:///../../node_modules/regenerator-runtime/runtime.js:63:40)
[18:50:25] :		 [Test web UI]         at Generator.invoke [as _invoke] (webpack-internal:///../../node_modules/regenerator-runtime/runtime.js:293:22)
[18:50:25] :		 [Test web UI]         at Generator.eval [as next] (webpack-internal:///../../node_modules/regenerator-runtime/runtime.js:118:21)
[18:50:25] :		 [Test web UI]         at fulfilled (webpack-internal:///./src/views/databases/databaseDetailsPage/redux.spec.ts:46:24)
[18:50:25] :		 [Test web UI] 
[18:50:25] :		 [Test web UI]   Database Table Page
[18:50:25] :		 [Test web UI]     ✖ starts in a pre-loading state
[18:50:25] :		 [Test web UI]       Chrome Headless 97.0.4692.71 (Linux x86_64)
[18:50:25] :		 [Test web UI]     AssertionError: { databaseName: 'DATABASE',
[18:50:25] :		 [Test web UI]       name: 'TABLE',
[18:50:25] :		 [Test web UI]       details: 
[18:50:25] :		 [Test web UI]        { loading: false,
[18:50:25] :		 [Test web UI]          loaded: false,
[18:50:25] :		 [Test web UI]          createStatement: '',
[18:50:25] :		 [Test web UI]          deepStrictEqual { automaticStatsCollectionEnabled: false,
[18:50:25] :		 [Test web UI]       databaseName: 'DATABASE',
[18:50:25] :		 [Test web UI]       name: 'TABLE',
[18:50:25] :		 [Test web UI]       showNodeRegionsSection: false,
[18:50:25] :		 [Test web UI]       detail
[18:50:25] :		 [Test web UI]         at TestDriver.assertProperties (webpack-internal:///./src/views/databases/databaseTablePage/redux.spec.ts:123:53)
[18:50:25] :		 [Test web UI]         at Context.eval (webpack-internal:///./src/views/databases/databaseTablePage/redux.spec.ts:221:12)
[18:50:25] :		 [Test web UI] 
[18:50:25] :		 [Test web UI]   Databases Page
[18:50:25] :		 [Test web UI]     ✖ starts in a pre-loading state
[18:50:25] :		 [Test web UI]       Chrome Headless 97.0.4692.71 (Linux x86_64)
[18:50:25] :		 [Test web UI]     AssertionError: { loading: false,
[18:50:25] :		 [Test web UI]       loaded: false,
[18:50:25] :		 [Test web UI]       databases: [],
[18:50:25] :		 [Test web UI]       sortSetting: { ascending: true, columnTitle: 'name' },
[18:50:25] :		 [Test web UI]       showNodeRegionsCo deepEqual { loading: false,
[18:50:25] :		 [Test web UI]       loaded: false,
[18:50:25] :		 [Test web UI]       databases: [],
[18:50:25] :		 [Test web UI]       sortSetting: { ascending: true, columnTitle: 'name' },
[18:50:25] :		 [Test web UI]       showNodeRegionsCo
[18:50:25] :		 [Test web UI]         at TestDriver.assertProperties (webpack-internal:///./src/views/databases/databasesPage/redux.spec.ts:155:53)
[18:50:25] :		 [Test web UI]         at _callee5$ (webpack-internal:///./src/views/databases/databasesPage/redux.spec.ts:200:22)
[18:50:25] :		 [Test web UI]         at tryCatch (webpack-internal:///../../node_modules/regenerator-runtime/runtime.js:63:40)
[18:50:25] :		 [Test web UI]         at Generator.invoke [as _invoke] (webpack-internal:///../../node_modules/regenerator-runtime/runtime.js:293:22)
[18:50:25] :		 [Test web UI]         at Generator.eval [as next] (webpack-internal:///../../node_modules/regenerator-runtime/runtime.js:118:21)
[18:50:25] :		 [Test web UI]         at eval (webpack-internal:///./src/views/databases/databasesPage/redux.spec.ts:56:67)
[18:50:25] :		 [Test web UI]         at new Promise (<anonymous>)
[18:50:25] :		 [Test web UI]         at __awaiter (webpack-internal:///./src/views/databases/databasesPage/redux.spec.ts:35:10)
[18:50:25] :		 [Test web UI]         at Context.eval (webpack-internal:///./src/views/databases/databasesPage/redux.spec.ts:195:12)
[18:50:25] :		 [Test web UI] 
[18:50:25] :		 [Test web UI]     ✖ makes a row for each database
[18:50:25] :		 [Test web UI]       Chrome Headless 97.0.4692.71 (Linux x86_64)
[18:50:25] :		 [Test web UI]     Error: No fallback response defined for GET to _admin/v1/settings?unredacted_values=true
[18:50:25] :		 [Test web UI]         at FetchMock.fetchMock (webpack-internal:///../../node_modules/fetch-mock/es5/fetch-mock.js:104:10)
[18:50:25] :		 [Test web UI]         at timeoutFetch (webpack-internal:///./src/util/api.ts:168:22)
[18:50:25] :		 [Test web UI]         at CachedDataReducer.getSettings [as apiEndpoint] (webpack-internal:///./src/util/api.ts:310:10)
[18:50:25] :		 [Test web UI]         at eval (webpack-internal:///./src/redux/cachedDataReducer.ts:206:22)
[18:50:25] :		 [Test web UI]         at Object.eval [as dispatch] (webpack-internal:///../../node_modules/redux-thunk/es/index.js:9:18)
[18:50:25] :		 [Test web UI]         at Object.eval [as refreshSettings] (webpack-internal:///../../node_modules/redux/es/redux.js:554:12)
[18:50:25] :		 [Test web UI]         at TestDriver._callee4$ (webpack-internal:///./src/views/databases/databasesPage/redux.spec.ts:142:64)
[18:50:25] :		 [Test web UI]         at tryCatch (webpack-internal:///../../node_modules/regenerator-runtime/runtime.js:63:40)
[18:50:25] :		 [Test web UI]         at Generator.invoke [as _invoke] (webpack-internal:///../../node_modules/regenerator-runtime/runtime.js:293:22)
[18:50:25] :		 [Test web UI]         at Generator.eval [as next] (webpack-internal:///../../node_modules/regenerator-runtime/runtime.js:118:21)
```

2022-02-08 22:45 UTC, maryliag requested changes
Looking really good! I added a few comments, still need to understand what's wrong on your tests.
Also, on PRs that have UI changes we like to add images or videos of the changes

> Reviewed 16 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-:-MvQT2zN7mvg2B7G5eEm:buh22we)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvPulAI75-CdLlmqxQm):*
nit: release justification is only for backport, you don't need on a regular PR
___
*[pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQQ_vP1RRFhDGZRpng:-MvQQ_vR268bedavNXMc:bujvhpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L299)):*
> ```XML
>         <a
>           className={booleanSettingCx("crl-hover-text__link-text")}
>           href="https://www.cockroachlabs.com/docs/stable/cost-based-optimizer#control-automatic-statistics"
> ```

we don't hard coded the full path in the url in case it changes, we use Anchor for those cases, for example:
https://github.com/cockroachdb/cockroach/blob/85913ddabbdfd7475d5314401270382834147cb4/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L457-L459
___
*[pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQQv5E1Kug8CDhHvjg:-MvQQv5E1Kug8CDhHvjh:bst72p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx#L399)):*
> ```XML
>                               "crl-hover-text__link-text",
>                             )}
>                             href="https://www.cockroachlabs.com/docs/stable/cost-based-optimizer#control-automatic-statistics"
> ```

similar comment as above
___
*[pkg/ui/workspaces/cluster-ui/src/settings/booleanSetting.tsx, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQVYg9EEWOGWCn_A6V:-MvQVYg9EEWOGWCn_A6W:bw2wxwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/settings/booleanSetting.tsx#L27)):*
> ```XML
> export function BooleanSetting(props: BooleanSettingProps) {
>   const { text, enabled, tooltipText } = props;
>   if (enabled) {
> ```

the two possible returned values are very similar, so create a variable for the label and another for the class and use that instead on just one return (I added a similar comment below and noticed this one after :) )
___
*[pkg/ui/workspaces/cluster-ui/src/summaryCard/index.tsx, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQRHEa5tz2AZHXY9MW:-MvQRHEa5tz2AZHXY9MX:bcsla5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/summaryCard/index.tsx#L59)):*
> ```XML
>   className,
> }) =>
>   value ? (
> ```

the options are very similar with just the difference on enable/disable, so you can create a variable for the class and label and use it here instead
e.g.

```
...}) => {
const label = value ? "Enabled" : "Disabled"
const class = value ? "bool-setting-icon__enabled" : "bool-setting-icon__disabled"

return (
     <div .....
      > 
      {label}
       </Tooltip>...
)
}
``` 
___
*[pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQSIvl4bF8sz4pIsYx:-MvQSIvl4bF8sz4pIsYy:b-z7f2ci) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts#L35)):*
> ```XML
> } from "src/redux/nodes";
> import { getNodesByRegionString } from "../utils";
> import { selectAutomaticStatsCollectionEnabled } from "oss/src/redux/clusterSettings";
> ```

nit: don't add `oss` to imports (it does that by default, so you need to always keep an eye)
`... from "src/redux..."
___
*[pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.ts, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQSYF1BO6lFNotLNVh:-MvQSYF1BO6lFNotLNVi:b266bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.ts#L35)):*
> ```XML
> import { getNodesByRegionString } from "../utils";
> import { resetIndexUsageStatsAction } from "src/redux/indexUsageStats";
> import { selectAutomaticStatsCollectionEnabled } from "oss/src/redux/clusterSettings";
> ```

similar as above, remove the `oss`
___
*[pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.spec.ts, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQSo5F8CgygjeP9LIK:-MvQSo5F8CgygjeP9LIL:b51l13j) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.spec.ts#L31)):*
> ```XML
> import { mapStateToProps, mapDispatchToProps } from "./redux";
> import moment from "moment";
> import { makeTimestamp } from "oss/src/views/databases/utils";
> ```

nit: same as above


<!-- Sent from Reviewable.io -->

2022-02-09 19:17 UTC, matthewtodd requested changes
Nice work! I left a few more comments. Happy to help pair on the tests if they get gnarly.

> Reviewed 2 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-:-MvUuh4z1qREvbj68Mnr:bxcws35)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @maryliag, and @matthewtodd)

___
*[pkg/server/admin.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUoywJ2E1Cv7uXfPGq:-MvUoywJ2E1Cv7uXfPGr:b16s095) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/server/admin.go#L881)):*
> ```Go
> 		sessiondata.InternalExecutorOverride{User: userName},
> 		fmt.Sprintf("SELECT max(created) AS created FROM [SHOW STATISTICS FOR TABLE %s]", escQualTable),
> 	)
> ```

I think this can be
```
row, cols, err = s.server.sqlServer.internalExecutor.QueryRowExWithCols(
	ctx, "admin-show-statistics", nil, /* txn */
	sessiondata.InternalExecutorOverride{User: userName},
	"SELECT max(created) AS created FROM [SHOW STATISTICS FOR TABLE $1]",
	escQualTable,
)
```
___
*[pkg/server/admin.go, line 894 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUsfnq8E7W9OLCd2t7:-MvUsfnq8E7W9OLCd2t8:b4eos5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/server/admin.go#L894)):*
> ```Go
> 		if !noTableStats {
> 			var createdTs time.Time
> 			if err := scanner.Scan(row, createdCol, &createdTs); err != nil {
> ```

[Looks like](https://github.com/cockroachdb/cockroach/blob/90629aecf20cf9423911005b9c81c65ee0173761/pkg/server/admin.go#L2895-L2906) you can pass a pointer to a pointer to `createdTs` here to avoid the `scanner.IsNull` check.
___
*[pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUtWDlBDRcILNlVlBF:-MvUtWDlBDRcILNlVlBG:bjfrmjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L367)):*
> ```XML
>         ),
>         cell: table =>
>           table.details.statsLastUpdated.isSame(moment.utc("0001-01-01"))
> ```

Can `statsLastUpdated` be undefined?
___
*[pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx, line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUtma7DmzZ2JdakhEO:-MvUtma7DmzZ2JdakhEP:b-1tww4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx#L376)):*
> ```XML
>                       value={this.props.stats.rangeCount}
>                     />
>                     {!this.props.details.statsLastUpdated.isSame(
> ```

ditto, can `statsLastUpdated` be undefined?
___
*[pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.ts, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUu7a96pE_m9z1YkMw:-MvUu7a96pE_m9z1YkMx:bz7fu6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.ts#L153)):*
> ```XML
>             statsLastUpdated: util.TimestampToMoment(
>               details?.data?.stats_last_created_at,
>               moment.utc("0001-01-01"),
> ```

I wonder if we want to use undefined here instead of this "magic" value. Or maybe make a constant for it?
___
*[pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.ts, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUuOEv-FI1ElUWf8Kh:-MvUuOEv-FI1ElUWf8Ki:b-41cds0) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.ts#L112)):*
> ```XML
>         statsLastUpdated: util.TimestampToMoment(
>           details?.data?.stats_last_created_at,
>           moment.utc("0001-01-01"),
> ```

ditto, consider using either undefined or a constant?


<!-- Sent from Reviewable.io -->

2022-02-11 00:52 UTC, ericharmeling reviewed
TFTRs! 

I've updated the PR in response to your feedback. PTAL at the latest commit.

@matthewtodd Would be nice to go over those tests! Thanks for offering to help. I'll follow-up offline.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-:-MvaFrP3Cpug32K2JVbF:bbx96z2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvPulAI75-CdLlmqxQm):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: release justification is only for backport, you don't need on a regular PR
</blockquote></details>

Done.
___
*[pkg/server/admin.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUoywJ2E1Cv7uXfPGq:-MvVHrj761N2t71FM1pq:b-vc0muz) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/server/admin.go#L881)):*
>"SELECT max(created) AS created FROM [SHOW STATISTICS FOR TABLE $1]",
	escQualTable,

Specifying the statement like this returns a SQL syntax error. I tried this instead:

>\`SELECT max(created) AS created FROM [SHOW STATISTICS FOR TABLE $1]\`,
	escQualTable,

And still get a SQL syntax error. FWIW, the surrounding statements (e.g., `admin-show-create`) use `fmt.Sprintf` (e.g., `fmt.Sprintf("SHOW CREATE %s", escQualTable),`). 

Is there an advantage to *not* using `fmt.Sprintf`?
___
*[pkg/server/admin.go, line 894 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUsfnq8E7W9OLCd2t7:-MvWclU12xI7244cGghP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/server/admin.go#L894)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

[Looks like](https://github.com/cockroachdb/cockroach/blob/90629aecf20cf9423911005b9c81c65ee0173761/pkg/server/admin.go#L2895-L2906) you can pass a pointer to a pointer to `createdTs` here to avoid the `scanner.IsNull` check.
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUtWDlBDRcILNlVlBF:-MvZAoUQ4dqJySTi0A4A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L367)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Can `statsLastUpdated` be undefined?
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQQ_vP1RRFhDGZRpng:-MvZ9HBVCzTeaDMdm2kW:b-goo7a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L299)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

we don't hard coded the full path in the url in case it changes, we use Anchor for those cases, for example:
https://github.com/cockroachdb/cockroach/blob/85913ddabbdfd7475d5314401270382834147cb4/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L457-L459
</blockquote></details>

Done.

On a related note, there is some inconsistency over which Tooltip component is being used on the Database pages and the SQL Activity pages, which is reflected in the font styling of the tooltip text between those pages.

- https://github.com/cockroachdb/cockroach/blob/85913ddabbdfd7475d5314401270382834147cb4/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L15
- https://github.com/cockroachdb/cockroach/blob/85913ddabbdfd7475d5314401270382834147cb4/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L13

I started updating the Databases pages in this PR to use ` import { Tooltip } from "@cockroachlabs/ui-components"; `, but the styling got a little too complicated. Might be best for another PR. Should I open an issue or just leave it as it is?
___
*[pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx, line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUtma7DmzZ2JdakhEO:-MvZB1ka6rjBxXnqwrCx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx#L376)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

ditto, can `statsLastUpdated` be undefined?
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQQv5E1Kug8CDhHvjg:-MvZ9bPgB3W7iL7DcL2s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx#L399)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

similar comment as above
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/settings/booleanSetting.tsx, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQVYg9EEWOGWCn_A6V:-MvZpK899YSu4pJ9JTA_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/settings/booleanSetting.tsx#L27)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the two possible returned values are very similar, so create a variable for the label and another for the class and use that instead on just one return (I added a similar comment below and noticed this one after :) )
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/summaryCard/index.tsx, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQRHEa5tz2AZHXY9MW:-MvZ4nUAB5Fv7GG7BOLL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/summaryCard/index.tsx#L59)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the options are very similar with just the difference on enable/disable, so you can create a variable for the class and label and use it here instead
e.g.

```
...}) => {
const label = value ? "Enabled" : "Disabled"
const class = value ? "bool-setting-icon__enabled" : "bool-setting-icon__disabled"

return (
     <div .....
      > 
      {label}
       </Tooltip>...
)
}
``` 
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.ts, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUu7a96pE_m9z1YkMw:-MvZpkrBAIslYt9cWb3R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.ts#L153)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I wonder if we want to use undefined here instead of this "magic" value. Or maybe make a constant for it?
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQSIvl4bF8sz4pIsYx:-MvZ4g2dBdGxXeALDmt8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts#L35)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: don't add `os [...]

2022-02-11 00:54 UTC, ericharmeling commented
@maryliag 

> Also, on PRs that have UI changes we like to add images or videos of the changes

Okay! I've added a video to the PR overview.

2022-02-11 14:13 UTC, maryliag reviewed
Thanks for the video! I just have one small nit regarding the commits, otherwise looking good! :D  
Something seems off with your test failures, because it seems some of the tests itself failed to run, not that they returned an error (e.g. `not a single test was parsed` message). I can see Matthew will help you, you might also get help from dev-inf for some of the tests too.

Another thing: we do have the same Database page in the managed repo (PR just landed this week https://github.com/cockroachlabs/managed-service/pull/7708), so you will need to create a PR very similar (if not equal) to this one, for the managed repo, so CC Console can have those changes too.

> Reviewed 3 of 4 files at r2, 11 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-:-Mvd620mCjocvUiCELrG:b-q0bzy5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @maryliag, and @matthewtodd)

___
*[-- commits, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-Mvd3WJn0EAJQVG0Fh_7):*
nit: we want to keep just one commit, so you can squash those two into a single one
___
*[pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQQ_vP1RRFhDGZRpng:-Mvd4-FMCl3Wr3j0XDca:b-brv4s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L299)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Done.

On a related note, there is some inconsistency over which Tooltip component is being used on the Database pages and the SQL Activity pages, which is reflected in the font styling of the tooltip text between those pages.

- https://github.com/cockroachdb/cockroach/blob/85913ddabbdfd7475d5314401270382834147cb4/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L15
- https://github.com/cockroachdb/cockroach/blob/85913ddabbdfd7475d5314401270382834147cb4/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L13

I started updating the Databases pages in this PR to use ` import { Tooltip } from "@cockroachlabs/ui-components"; `, but the styling got a little too complicated. Might be best for another PR. Should I open an issue or just leave it as it is?
</blockquote></details>

Best for another PR, feel free to open an issue so we keep track of it.


<!-- Sent from Reviewable.io -->

2022-02-11 21:22 UTC, ericharmeling reviewed
> Another thing: we do have the same Database page in the managed repo (PR just landed this week cockroachlabs/managed-service#7708), so you will need to create a PR very similar (if not equal) to this one, for the managed repo, so CC Console can have those changes too.

Got it. I'll start working on implementing these changes in `managed-service` once this PR is merged. 

Question: Should I have this PR *not* resolve https://github.com/cockroachdb/cockroach/issues/67510 and instead have a PR into `managed-service` resolve that issue, or should I just make the `managed-service` PR fast-follow work? It doesn't look like https://github.com/cockroachlabs/managed-service/pull/7708 directly resolves any open GH issues.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-:-MvedLQxDEG6P4HOBV1X:b-97k6jv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @matthewtodd)

___
*[-- commits, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-Mvd3WJn0EAJQVG0Fh_7):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: we want to keep just one commit, so you can squash those two into a single one
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx, line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvQQ_vP1RRFhDGZRpng:-MvedD_H4kNgWSwaQ9j8:b-hnfvjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L299)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Best for another PR, feel free to open an issue so we keep track of it.
</blockquote></details>

Looks like someone beat me to it :)

https://cockroachlabs.atlassian.net/browse/CC-5339


<!-- Sent from Reviewable.io -->

2022-02-11 22:02 UTC, maryliag reviewed
Since issue #67510 specifies DB Console, you can make this PR resolve that issue and create a follow issue and PR for the managed changes.
Issues that are specific for CC Console can be created just on jira. For example: the PR you mentioned have a `[CRDB-8616]` in the title, and that's the issue is solves (https://cockroachlabs.atlassian.net/browse/CRDB-8616). For that repo you add the issue on the title but it should also have the link of the issue on the description, to help. 

> Reviewed 1 of 13 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-:-MvemBq32Sqwxc-xfbLU:b15i1ce)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)



<!-- Sent from Reviewable.io -->

2022-02-14 14:37 UTC, maryliag approved these changes
Looks great! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-:-MvsedTj58Kn16VdzMUs:blerph5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)



<!-- Sent from Reviewable.io -->

2022-02-14 16:17 UTC, ericharmeling commented
Thanks for the approval, @maryliag!

I think I got to all of your feedback, @matthewtodd. I also pushed all of the updates we worked on on 2/11/22. If you're good with the changes, I'll go ahead and merge. :)

2022-02-14 16:35 UTC, matthewtodd approved these changes
Looks great, @ericharmeling! Thank you! :tada: 

> Reviewed 6 of 23 files at r1, 3 of 4 files at r2, 9 of 13 files at r3, 8 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-:-Mvt4TqC0sXnKmBt4Qjg:bae7te9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[pkg/server/admin.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUoywJ2E1Cv7uXfPGq:-Mvt3IpkAStfD3yClChO:b8tg6p5) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/server/admin.go#L881)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

>"SELECT max(created) AS created FROM [SHOW STATISTICS FOR TABLE $1]",
	escQualTable,

Specifying the statement like this returns a SQL syntax error. I tried this instead:

>\`SELECT max(created) AS created FROM [SHOW STATISTICS FOR TABLE $1]\`,
	escQualTable,

And still get a SQL syntax error. FWIW, the surrounding statements (e.g., `admin-show-create`) use `fmt.Sprintf` (e.g., `fmt.Sprintf("SHOW CREATE %s", escQualTable),`). 

Is there an advantage to *not* using `fmt.Sprintf`?
</blockquote></details>

Ugh, sorry for sending you into this. I was generally looking to avoid manually building SQL strings like this in a "defend against SQL injection" spirit, but given the escaping of the table name (as well as the pattern in the surrounding code), I think you're right that we're fine here.


<!-- Sent from Reviewable.io -->

2022-02-14 16:39 UTC, ericharmeling commented
bors r+

2022-02-14 17:04 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76168)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[pkg/server/admin.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76168#-MvUoywJ2E1Cv7uXfPGq:-Mvt4ybf6zcdLBVKvhMU:b-rju70j) ([raw file](https://github.com/cockroachdb/cockroach/blob/364fd1fd7165881e41dcd8058c65bba51346ac6b/pkg/server/admin.go#L881)):*
All good! 

> I was generally looking to avoid manually building SQL strings like this in a "defend against SQL injection" spirit, but given the escaping of the table name (as well as the pattern in the surrounding code), I think you're right that we're fine here.

Ah - that makes a lot of sense! :thumbsup: 


<!-- Sent from Reviewable.io -->

2022-02-14 21:24 UTC, ajwerner commented
bors r-

Sadly this needs a `./dev generate bazel`.

```
  +  "//pkg/ui/workspaces/cluster-ui:dist/types/settings/booleanSetting.d.ts",
  +  "//pkg/ui/workspaces/cluster-ui:dist/types/settings/index.d.ts",
```

I'm working on removing the tracking of these files in https://github.com/cockroachdb/cockroach/issues/76521.

Sorry

2022-02-14 21:32 UTC, ericharmeling commented
> Sadly this needs a ./dev generate bazel.

No worries! Just rebased on master, reran `./dev generate bazel`, and pushed the change to `pkg/gen/excluded.bzl`.

2022-02-14 22:53 UTC, ericharmeling commented
@ajwerner This passed GH CI after my [last update](https://github.com/cockroachdb/cockroach/pull/76168/files#diff-22f7e63851a18c9953decf019f51812b29a21cca7623430f37deadb4daf1ee2a) - good to retry the merge?

2022-02-15 13:38 UTC, ericharmeling commented
bors r+

2022-02-15 14:25 UTC, merged