opt: index accelerate && (overlaps) expressions for array inverted indexes
cockroachdb/cockroach pull request #76212
Opened 2022-02-08 00:08 UTC by RajivTS

Previously, we did not support index acceleration for queries involving
array overlaps (&&).

This change adds support for using the inverted index with && expressions on
Array columns. When there is an inverted index available, a scan will be done on
the Array column using the spans found from the constant value.

Fixes: #75477

Release note (performance improvement): Expressions using the overlaps (&&)
operator now support index-acceleration for faster execution.

2022-02-08 00:08 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=76212) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=76212) before we can accept your contribution.<br/><hr/>**Rajiv Sharma** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=76212) it.</sub>

2022-02-08 00:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76212)
<!-- Reviewable:end -->

2022-02-09 15:55 UTC, rytaft reviewed
Thanks for the contribution, @RajivTS! This is looking great. A few comments below.

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-:-MvU8xo_5IoLfduURST9:b-j1d87e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RajivTS)

___
*[-- commits, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTi0jo2UUTSMfGKaVb):*
nit: Mention that this is specifically array expressions
___
*[pkg/sql/opt/invertedidx/json_array.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTitkcC7AIvkQc7xeN:-MvTitkcC7AIvkQc7xeO:b9j6yzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/opt/invertedidx/json_array.go#L366)):*
> ```Go
> 		}
> 	case *memo.OverlapsExpr:
> 		invertedExpr = getInvertedExprForArrayIndexForOverlaps(evalCtx, memo.ExtractConstDatum(t.Right))
> ```

I'm surprised you don't need an extract function similar to the above. Are we doing extra work if `t.Left` is not actually an index column? Is it possible that `ExtractConstDatum` will panic if it cannot extract a constant from `t.Right`? It would be good to make sure we have test cases that exercise this.
___
*[pkg/sql/rowenc/index_encoding.go, line 866 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTqaAW3P_8eSMUPEl5:-MvTqaAW3P_8eSMUPEl6:b-nneo6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L866)):*
> ```Go
> // inKey is prefixed to all returned keys.
> //
> // Returns unique=true if the spans are guaranteed not to produce
> ```

I see that you copied this from above, but it looks like this comment has gotten stale so maybe you can fix it in both places?

We no longer return a value for `unique`, instead we set `Unique` appropriately on the returned `inverted.SpanExpression`. Feel free to just remove this comment, and/or maybe add a comment where we set `Unique=true` below. (A previous version of this code had a separate return value for `unique`)
___
*[pkg/sql/rowenc/index_encoding.go, line 872 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU3SNKBkXElczaDlha:-MvU3SNL3zy0SwSJ5Ezs:b-qeji7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L872)):*
> ```Go
> ) (invertedExpr inverted.Expression, err error) {
> 	emptyArrSpanExpr := inverted.ExprForSpan(
> 		inverted.MakeSingleValSpan(encoding.EncodeEmptyArray(inKey)), false, /* tight */
> ```

do we need this for overlaps? `ARRAY[]::int[] && ARRAY[]::int[];` is false
___
*[pkg/sql/rowenc/index_encoding.go, line 890 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTre4u9kMnWfdsVyP9:-MvTre4u9kMnWfdsVyPA:b-e35nva) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L890)):*
> ```Go
> 	for _, key := range keys {
> 		spanExpr := inverted.ExprForSpan(
> 			inverted.MakeSingleValSpan(key), false, /* tight */
> ```

The comment above on line 713 said that the span expression will be tight, but it looks like that may not be the case? Do you think this should be true?
___
*[pkg/sql/sem/tree/eval.go, line 434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU-YJD8BkrIVWzU2nK:-MvU-YJE6A060V7V2F15:b-5r817j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/sem/tree/eval.go#L434)):*
> ```Go
> }
> 
> // ArrayOverlaps return true if there is even one element common between the left and right arrays.
> ```

nit: comments should be <= 80 columns wide
___
*[pkg/sql/sem/tree/eval.go, line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU-hy89xEI-8qOZ6BW:-MvU-hy89xEI-8qOZ6BX:b-4itupb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/sem/tree/eval.go#L435)):*
> ```Go
> 
> // ArrayOverlaps return true if there is even one element common between the left and right arrays.
> func ArrayOverlaps(ctx *EvalContext, left, right *DArray) (*DBool, error) {
> ```

You should make sure that this is the same function we are actually using to evaluate `&&`. I think you'll want to extract the code from here for this helper function, and call it from both places: https://github.com/cockroachdb/cockroach/blob/63988a409584865a75ba80c0f0c3a1ceab67d076/pkg/sql/sem/tree/eval.go#L2598-L2616
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1572 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU08je7zBLGE7wMfpW:-MvU08je7zBLGE7wMfpX:b2xqfqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/logictest/testdata/logic_test/inverted_index#L1572)):*
> ```
> ----
> {rat}
> {rat,NULL,""}
> ```

nit: remove extra space (I think if you rewrite this file as follows it should remove the space):
`make test PKG=./pkg/sql/logictest/... TESTS='TestLogic//inverted_index' TESTFLAGS='-rewrite=true'`
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 1446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU6LrCAKDRlzxv-GV9:-MvU6LrCAKDRlzxv-GVA:b-rlmnqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L1446)):*
> ```
>             │ columns: (a, b_inverted_key)
>             │ inverted column: b_inverted_key
>             │ num spans: 2
> ```

the formatting looks weird -- you might try to run this to fix it:
`make test PKG=./pkg/sql/opt/exec/execbuilder... TESTS='TestExecBuild//inverted_index' TESTFLAGS='-rewrite=true'`
___
*[pkg/sql/opt/xform/testdata/rules/select, line 9398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU052EDM3ik-h1Mo8U:-MvU052EDM3ik-h1Mo8V:b-vqgtr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/opt/xform/testdata/rules/select#L9398)):*
> ```
>            └── const-agg [as=b:5, outer=(5)]
>                 └── b:5
>                 
> ```

nit: remove this
___
*[pkg/sql/rowenc/index_encoding_test.go, line 749 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU7CNv3HF2vf_6yP39:-MvU7CNv3HF2vf_6yP3A:be85i7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L749)):*
> ```Go
> 		// to determine if the spans produced from the second Array value will
> 		// correctly overlap or be distinct from the first value, indicated by
> 		// overlapsKeys. Then, if indexedValue && value, expected is true.
> ```

I don't see `overlapsKeys`
___
*[pkg/sql/rowenc/index_encoding_test.go, line 754 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU8CFz3R9kFSgG_vQq:-MvU8CFz3R9kFSgG_vQr:b10ca2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L754)):*
> ```Go
> 		// unless the value produces a single empty array span.
> 
> 		// First we test that the spans will include expected value.
> ```

Nice tests!
___
*[pkg/sql/rowenc/index_encoding_test.go, line 808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU7wAnCvHkERvvnboF:-MvU7wAo7VaURus4IAwL:b-7fpd9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L808)):*
> ```Go
> 		}
> 
> 		// Array spans for && are never tight.
> ```

why not? (as I wrote elsewhere, I think you might be able to make the spans tight)
___
*[pkg/sql/rowenc/index_encoding_test.go, line 813 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU86tX3aLx5gxhMqj-:-MvU86tX3aLx5gxhMqj0:b-ytxc6n) ([raw file](htt [...]

2022-02-09 16:36 UTC, mgartner requested changes
Great start! I left a few comments as well.

> Reviewed 4 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-:-MvUKllFEfdA4-kGY_Vk:b-bd3hya)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RajivTS and @rytaft)

___
*[pkg/sql/rowenc/index_encoding.go, line 872 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU3SNKBkXElczaDlha:-MvUIQiPDU31knINN-mS:b-mhjre7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L872)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do we need this for overlaps? `ARRAY[]::int[] && ARRAY[]::int[];` is false
</blockquote></details>

Hmmm, this is an interesting case. So what should we do when `val` is an empty array, generate no spans? I don't know if there's precedent for scans over an empty range... maybe this can't be index accelerated?

Maybe we can add a normalization rule in a follow-up PR for this case. We have to be careful though. We can't simply normalize `a && ARRAY[]::INT[]` to `false`, because if `a` is `NULL`, it evaluates to `NULL`. But I think we could normalize a filter with `a && ARRAY[]::INT[]` to `false`.
___
*[pkg/sql/rowenc/index_encoding.go, line 887 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU7pcdDKzoaRs8g3Uq:-MvU7pcdDKzoaRs8g3Ur:bru68lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L887)):*
> ```Go
> 		return nil, err
> 	}
> 	invertedExpr = emptyArrSpanExpr
> ```

Why do we include the empty array span in this case? It seems like it shouldn't be needed given that an empty array doesn't overlap with any other array.
___
*[pkg/sql/rowenc/index_encoding.go, line 890 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTre4u9kMnWfdsVyP9:-MvUBoQ54f2slNpTLJjc:b-6xjseu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L890)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The comment above on line 713 said that the span expression will be tight, but it looks like that may not be the case? Do you think this should be true?
</blockquote></details>

@rajivts FYI there's some explanation of tightness here: https://github.com/cockroachdb/cockroach/blob/a8fc111d61d409d1f81608aa60f9e755f0ce8aa5/pkg/sql/inverted/expression.go#L280-L282

You can see examples of tight and non-tight expressions here: https://github.com/cockroachdb/cockroach/blob/b2c04bed1d3f8a4f1cbd225fe6c22c4621a638fd/pkg/sql/opt/invertedidx/json_array_test.go#L237

This is a good example of a non-tight expression: https://github.com/cockroachdb/cockroach/blob/b2c04bed1d3f8a4f1cbd225fe6c22c4621a638fd/pkg/sql/opt/invertedidx/json_array_test.go#L266-L273

We can scan the inverted span for `'{"a": 1}'`, to get rows that _may_ match, but we need to re-evaluate the expression to ensure that the JSON columns don't contain other values that aren't contained by `'{"a": 1}'`.

I _think_ these overlaps expressions should be tight.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1491 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU9dBp47y-OAXyAaLw:-MvU9dBp47y-OAXyAaLx:bwriv63) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/logictest/testdata/logic_test/inverted_index#L1491)):*
> ```
> statement ok
> INSERT INTO cb VALUES
>   (0, ARRAY[], ARRAY[]),
> ```

Can you add a row where `numbers` and `words` are `NULL`?
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1504 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU8Wgj2g1b0qk9NG3j:-MvU8Wgj2g1b0qk9NG3k:b3to1y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/logictest/testdata/logic_test/inverted_index#L1504)):*
> ```
> SELECT numbers FROM cb@n WHERE numbers && ARRAY[]::INT[]
> ----
> ```

nit: remove extra lines after the empty test responses here and below
___
*[pkg/sql/opt/invertedidx/json_array_test.go, line 743 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUEzpnEfiWfiTV6dIV:-MvUEzpnEfiWfiTV6dIW:bcltboy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/opt/invertedidx/json_array_test.go#L743)):*
> ```Go
> 		},
> 		{
> 			filters:          "a && '{1}' OR str && '{hello}'",
> ```

It'd be interesting to add expressions that combine `&&` expressions with `@>` and `<@` with `AND`s and `OR`s.
___
*[pkg/sql/rowenc/index_encoding_test.go, line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUHoZY3MqJC8DGfmo1:-MvUHoZY3MqJC8DGfmo2:b-lwb0f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L752)):*
> ```Go
> 
> 		// The expression is a union of spans, so unique should never be true
> 		// unless the value produces a single empty array span.
> ```

Is this true for overlaps? I think the spans for a single array overlap would be unique, like `a &&
___
*[pkg/sql/rowenc/index_encoding_test.go, line 784 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUH_WwCZ3MbdHZa4pC:-MvUH_WwCZ3MbdHZa4pD:b-snege9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L784)):*
> ```Go
> 		{`{NULL}`, `{1, NULL}`, false, false},
> 		{`{1,NULL}`, `{NULL}`, false, true},
> 		{`{2, NULL}`, `{1, NULL}`, false, false},
> ```

Can you add test with `NULL` arrays?


<!-- Sent from Reviewable.io -->

2022-02-09 16:37 UTC, mgartner commented
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1491 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU9dBp47y-OAXyAaLw:-MvUKwiJAo3KOQNIbWLj:b-5s9tg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/logictest/testdata/logic_test/inverted_index#L1491)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add a row where `numbers` and `words` are `NULL`?
</blockquote></details>

I think arrays of tuples would be interesting test cases too, like `ARRAY[(1, 2)]`.


<!-- Sent from Reviewable.io -->

2022-02-09 17:29 UTC, rytaft commented
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1491 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU9dBp47y-OAXyAaLw:-MvUWtKJ2zl3gv3XyrbT:b-flbt38) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/logictest/testdata/logic_test/inverted_index#L1491)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think arrays of tuples would be interesting test cases too, like `ARRAY[(1, 2)]`.
</blockquote></details>

I don't think we support columns with arrays of tuples


<!-- Sent from Reviewable.io -->

2022-02-10 00:18 UTC, RajivTS reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RajivTS, and @rytaft)

___
*[pkg/sql/opt/invertedidx/json_array.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTitkcC7AIvkQc7xeN:-MvVPSdAAc9KwZIPIPOT:b-5l2p1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/opt/invertedidx/json_array.go#L366)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm surprised you don't need an extract function similar to the above. Are we doing extra work if `t.Left` is not actually an index column? Is it possible that `ExtractConstDatum` will panic if it cannot extract a constant from `t.Right`? It would be good to make sure we have test cases that exercise this.
</blockquote></details>

Good catch. On adding new tests, I can confirm that having non-constant array column on the right leads to panic. Observing the implementation of `EqExpr` (which is also commutative), I believe that in case of both `t.Left` and `t.Right` being indexed columns we should simply return a `NonInvertedColExpression` indicating that index acceleration is not possible in this case. What do you think? 
___
*[pkg/sql/rowenc/index_encoding.go, line 866 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTqaAW3P_8eSMUPEl5:-MvVTrBQCDYXtvWXTF5R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L866)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I see that you copied this from above, but it looks like this comment has gotten stale so maybe you can fix it in both places?

We no longer return a value for `unique`, instead we set `Unique` appropriately on the returned `inverted.SpanExpression`. Feel free to just remove this comment, and/or maybe add a comment where we set `Unique=true` below. (A previous version of this code had a separate return value for `unique`)
</blockquote></details>

Done.
___
*[pkg/sql/rowenc/index_encoding.go, line 872 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU3SNKBkXElczaDlha:-MvVTzz_DipOfKGh79It:bpl0345) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L872)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmmm, this is an interesting case. So what should we do when `val` is an empty array, generate no spans? I don't know if there's precedent for scans over an empty range... maybe this can't be index accelerated?

Maybe we can add a normalization rule in a follow-up PR for this case. We have to be careful though. We can't simply normalize `a && ARRAY[]::INT[]` to `false`, because if `a` is `NULL`, it evaluates to `NULL`. But I think we could normalize a filter with `a && ARRAY[]::INT[]` to `false`.
</blockquote></details>

I have kept this as is (except making tight=true for overlap) since I don't see a consensus on the expected behavior here. Please let me know if changes are needed.
___
*[pkg/sql/rowenc/index_encoding.go, line 887 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU7pcdDKzoaRs8g3Uq:-MvVa96w-IB9wvglxE7p:b-u6z9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L887)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why do we include the empty array span in this case? It seems like it shouldn't be needed given that an empty array doesn't overlap with any other array.
</blockquote></details>

Yes strictly speaking its not needed and hence I have updated the code here. It did help in the scenario when the input array is non-empty but contains only `NULL` values which then get filtered out leaving us again with an empty array (and 0 keys). `invertedExpr = emptyArrSpanExpr` makes sure an empty span expression gets returned in this case. It also helps prevent an explicit `nil` check within the loop. 
___
*[pkg/sql/rowenc/index_encoding.go, line 890 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTre4u9kMnWfdsVyP9:-MvVtz7OEuuCC01yj7i2:b-jm0zr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L890)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

@rajivts FYI there's some explanation of tightness here: https://github.com/cockroachdb/cockroach/blob/a8fc111d61d409d1f81608aa60f9e755f0ce8aa5/pkg/sql/inverted/expression.go#L280-L282

You can see examples of tight and non-tight expressions here: https://github.com/cockroachdb/cockroach/blob/b2c04bed1d3f8a4f1cbd225fe6c22c4621a638fd/pkg/sql/opt/invertedidx/json_array_test.go#L237

This is a good example of a non-tight expression: https://github.com/cockroachdb/cockroach/blob/b2c04bed1d3f8a4f1cbd225fe6c22c4621a638fd/pkg/sql/opt/invertedidx/json_array_test.go#L266-L273

We can scan the inverted span for `'{"a": 1}'`, to get rows that _may_ match, but we need to re-evaluate the expression to ensure that the JSON columns don't contain other values that aren't contained by `'{"a": 1}'`.

I _think_ these overlaps expressions should be tight.


</blockquote></details>

That's the understanding with which I began this implementation. However, if the generated inverted expression is marked `tight` then the execution plan created in `inverted_index` test shows a direct scan of all the rows for evaluating overlaps instead of filtering using the inverted index. I do not know the reason behind this but to ensure that the inverted index is used for array overlaps, I kept tight as false for now.
___
*[pkg/sql/sem/tree/eval.go, line 434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU-YJD8BkrIVWzU2nK:-MvVmJckBu61xv7Tfv3Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/sem/tree/eval.go#L434)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: comments should be <= 80 columns wide
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/eval.go, line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU-hy89xEI-8qOZ6BW:-MvVmFPEAkq0wLE62UZq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/sem/tree/eval.go#L435)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You should make sure that this is the same function we are actually using to evaluate `&&`. I think you'll want to extract the code from here for this helper function, and call it from both places: https://github.com/cockroachdb/cockroach/blob/63988a409584865a75ba80c0f0c3a1ceab67d076/pkg/sql/sem/tree/eval.go#L2598-L2616
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1491 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU9dBp47y-OAXyAaLw:-MvVmNomAWRTFC-6X25A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/logictest/testdata/logic_test/inverted_index#L1491)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think we support columns with arrays of tuples
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1504 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU8Wgj2g1b0qk9NG3j:-MvVmPun212jRf6jOCbH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/logictest/testdata/logic_test/inverted_index#L1504 [...]

2022-02-10 16:34 UTC, rytaft reviewed
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RajivTS, and @rytaft)

___
*[pkg/sql/opt/invertedidx/json_array.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTitkcC7AIvkQc7xeN:-MvZMfbK1H_LaTsyL6g5:b1fwiz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/opt/invertedidx/json_array.go#L366)):*
<details><summary><i>Previously, RajivTS (Rajiv Sharma) wrote…</i></summary><blockquote>

Good catch. On adding new tests, I can confirm that having non-constant array column on the right leads to panic. Observing the implementation of `EqExpr` (which is also commutative), I believe that in case of both `t.Left` and `t.Right` being indexed columns we should simply return a `NonInvertedColExpression` indicating that index acceleration is not possible in this case. What do you think? 
</blockquote></details>

Yep, looks good to me. Thanks!
___
*[pkg/sql/rowenc/index_encoding.go, line 872 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU3SNKBkXElczaDlha:-MvZNmZw5sisATg3gTbm:bc1zmyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L872)):*
<details><summary><i>Previously, RajivTS (Rajiv Sharma) wrote…</i></summary><blockquote>

I have kept this as is (except making tight=true for overlap) since I don't see a consensus on the expected behavior here. Please let me know if changes are needed.
</blockquote></details>

I think it's important that we don't scan spans that we don't need to. I think it's ok to just return `&inverted.SpanEpression{Tight: true}`. If that causes problems, try `&inverted.SpanEpression{Tight: true, SpansToRead: []Span{}, FactoredUnionSpans: []Span{}}}`. And if that still causes problems, you could just add a check in `extractArrayOverlapsCondition` that the const datum is not an empty array (and if it is, return `inverted.NonInvertedColExpression{}`).

We'll also want to add the normalization rule that @mgartner suggested, but I agree that can be done in a separate PR.
___
*[pkg/sql/rowenc/index_encoding.go, line 890 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTre4u9kMnWfdsVyP9:-MvZPqd84WixI91nIydY:b5yuss2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L890)):*
<details><summary><i>Previously, RajivTS (Rajiv Sharma) wrote…</i></summary><blockquote>

That's the understanding with which I began this implementation. However, if the generated inverted expression is marked `tight` then the execution plan created in `inverted_index` test shows a direct scan of all the rows for evaluating overlaps instead of filtering using the inverted index. I do not know the reason behind this but to ensure that the inverted index is used for array overlaps, I kept tight as false for now.
</blockquote></details>

Can you try forcing the use of the inverted index using the `table@idx` syntax in the `inverted_index` test? It's possible that we need to improve our statistics estimation to choose the correct plan for this case (that could be done in a follow up PR).

I do think we'll want to change `tight` to true here (we can validate that this is correct with the randomized test that you've included, although you'll need to modify the test to not apply the additional filter on top).
___
*[pkg/sql/sem/tree/eval.go, line 438 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvZSRBU2VrYTdYo2Kut:-MvZSRBU2VrYTdYo2Kuu:b2a41n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b434ce44f6baaca33fdc107fdb9119e414993c/pkg/sql/sem/tree/eval.go#L438)):*
> ```Go
> func ArrayOverlaps(ctx *EvalContext, left, right *DArray) (*DBool, error) {
> 	array := MustBeDArray(left)
> 	other := MustBeDArray(right)
> ```

you don't need these two lines -- the parameters are already type `DArray`


<!-- Sent from Reviewable.io -->

2022-02-13 22:59 UTC, RajivTS reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[-- commits, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTi0jo2UUTSMfGKaVb):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: Mention that this is specifically array expressions
</blockquote></details>

Done
___
*[pkg/sql/opt/invertedidx/json_array.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTitkcC7AIvkQc7xeN:-MvpD3Qr79vL2dYZoZsv:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/opt/invertedidx/json_array.go#L366)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yep, looks good to me. Thanks!
</blockquote></details>

:+1: 
___
*[pkg/sql/rowenc/index_encoding.go, line 872 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvU3SNKBkXElczaDlha:-MvpDAQ00JnGZa9qMmwv:b-l2lkvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L872)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think it's important that we don't scan spans that we don't need to. I think it's ok to just return `&inverted.SpanEpression{Tight: true}`. If that causes problems, try `&inverted.SpanEpression{Tight: true, SpansToRead: []Span{}, FactoredUnionSpans: []Span{}}}`. And if that still causes problems, you could just add a check in `extractArrayOverlapsCondition` that the const datum is not an empty array (and if it is, return `inverted.NonInvertedColExpression{}`).

We'll also want to add the normalization rule that @mgartner suggested, but I agree that can be done in a separate PR.
</blockquote></details>

Done. Returned `inverted.NonInvertedColExpression{}` in case of empty arrays or arrays with only `NULL`, in all other cases it produces a tight inverted expression. However this is being done in `encodeOverlapsArrayInvertedIndexSpans` instead of `extractArrayOverlapsCondition` since the null check for array elements can only be done once the value datums type has been confired as an Array.
The tests have been modified accordingly.
___
*[pkg/sql/rowenc/index_encoding.go, line 890 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvTre4u9kMnWfdsVyP9:-MvpFW7Y97l5Qe6Bpn7H:b-ddzg1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding.go#L890)):*
>Can you try forcing the use of the inverted index using the table@idx syntax in the inverted_index test? It's possible that we need to improve our statistics estimation to choose the correct plan for this case (that could be done in a follow up PR).

Yes this did the trick :)
`tight` is now true and the tests are working as expected.
___
*[pkg/sql/sem/tree/eval.go, line 438 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvZSRBU2VrYTdYo2Kut:-MvpG71f1nmg5p81akrS:b-sd92sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b434ce44f6baaca33fdc107fdb9119e414993c/pkg/sql/sem/tree/eval.go#L438)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

you don't need these two lines -- the parameters are already type `DArray`
</blockquote></details>

My bad. Done.
___
*[pkg/sql/rowenc/index_encoding_test.go, line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUHoZY3MqJC8DGfmo1:-MvpGFbT3Hd-1hOBBFlC:bd7vcle) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L752)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is this true for overlaps? I think the spans for a single array overlap would be unique, like `a &&
</blockquote></details>

I am not so sure. Since the same element can be present in multiple rows for the same array, can `unique` be true? i.e. Will the spans produce no duplicate primary keys?


<!-- Sent from Reviewable.io -->

2022-02-14 13:53 UTC, rytaft reviewed
Getting close! Thanks for the updates.

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-:-MvsVXkhAtiJNsU0IPS1:b-fyqbg5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RajivTS)

___
*[pkg/sql/rowenc/index_encoding.go, line 861 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsNlCi-GIOZqoPYY2i:-MvsNlCi-GIOZqoPYY2j:by5o7a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/rowenc/index_encoding.go#L861)):*
> ```Go
> // the given array, one slice of spans per entry in the array. The input
> // inKey is prefixed to all returned keys.
> //
> ```

nit: remove blank line (here and above where you removed the last bit of the function comment)
___
*[pkg/sql/rowenc/index_encoding.go, line 867 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsMJPd7G4QfKCCeUi2:-MvsMJPd7G4QfKCCeUi3:bfcmn4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/rowenc/index_encoding.go#L867)):*
> ```Go
> 	// If the given array is directly empty (i.e. Len == 0),
> 	// or contains only NULLs and thus has effective length 0,
> 	// we cannot generate an inverted expression.
> ```

We support the notion of a "contradiction" in regular constraints -- I think we might want to do the same for inverted constraints. A contradiction for inverted constraints would effectively be an empty SpanExpression (`&inverted.SpanEpression{Tight: true, SpansToRead: []Span{}, FactoredUnionSpans: []Span{}}}`). Does returning that expression cause an error? If so, we may need to update the `inverted.SpanEpression` code to explicitly support contradictions (can be a separate PR).

In the mean time, if that causes an error, returning `inverted.NonInvertedColExpression{}` is fine. Could you just add a TODO here that this should be a contradiction?
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 1398 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsOKraCAliSZGJ69Bs:-MvsOKrbBiocF2YCCnv_:bxks86h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L1398)):*
> ```
>                   spans: /"f"-/"f"/PrefixEnd /[]-/{} /Arr/"f"-/Arr/"f"/PrefixEnd /Arr/{}-/Arr/{}/PrefixEnd /Arr/"a"/"b"-/Arr/"a"/"b"/PrefixEnd /Arr/"c"/{}-/Arr/"c"/{}/PrefixEnd /Arr/"c"/"d"/[]-/Arr/"c"/"d"/{} /Arr/"c"/"d"/Arr/"e"-/Arr/"c"/"d"/Arr/"e"/PrefixEnd
> 
> # Test that queries with overlaps && operator use the inverted index
> ```

This comment is no longer valid for this test case, so please add a TODO for this case that we should have a normalization rule that turns this into a no-op, since the predicate is a contradiction.
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 1444 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsOfP89ZJAzct05dq6:-MvsOfP89ZJAzct05dq7:bho9g4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L1444)):*
> ```
> 
> query T
> EXPLAIN (VERBOSE) SELECT * FROM e WHERE b && ARRAY[NULL]::INT[]
> ```

ditto here -- add a TODO
___
*[pkg/sql/opt/xform/testdata/rules/select, line 3365 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsP0L4EwlMOJWioF-c:-MvsP0L4EwlMOJWioF-d:b-6pscds) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b434ce44f6baaca33fdc107fdb9119e414993c/pkg/sql/opt/xform/testdata/rules/select#L3365)):*
> ```
> 
> opt expect=GenerateInvertedIndexScans
> SELECT * FROM c WHERE a && ARRAY[]::INT[]
> ```

I think these test cases are good, so it would be better to leave them in but use `expect-not=GenerateInvertedIndexScans` and explain in a TODO that they should be addressed with a normalization rule rather than `GenerateInvertedIndexScans`
___
*[pkg/sql/opt/xform/testdata/rules/select, line 3338 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsOqaQ9uQy0Mky4StW:-MvsOqaQ9uQy0Mky4StX:b-swb46l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/opt/xform/testdata/rules/select#L3338)):*
> ```
> 
> opt expect=GenerateInvertedIndexScans
> SELECT * FROM c WHERE a && ARRAY[1]
> ```

you can use `c@a_inv_idx` here to show the plan with the inverted index
___
*[pkg/sql/opt/xform/testdata/rules/select, line 3353 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsPEWS9oyCefabimUA:-MvsPEWS9oyCefabimUB:b-e5t6tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/opt/xform/testdata/rules/select#L3353)):*
> ```
> 
> opt expect=GenerateInvertedIndexScans
> SELECT * FROM c WHERE a && ARRAY[1] OR a && ARRAY[2]
> ```

use c@a_inv_idx
___
*[pkg/sql/opt/invertedidx/json_array_test.go, line 744 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsT2bp1Yhf4RNl6DN-:-MvsT2bp1Yhf4RNl6DN0:b-xcn5s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b434ce44f6baaca33fdc107fdb9119e414993c/pkg/sql/opt/invertedidx/json_array_test.go#L744)):*
> ```Go
> 		{
> 			// When operations affecting two different variables are OR-ed, we cannot
> 			// constrain either index.
> ```

why did you remove this comment? I think it's useful
___
*[pkg/sql/opt/invertedidx/json_array_test.go, line 718 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsPwtz0ULVlMlpB-4V:-MvsPwtz0ULVlMlpB-4W:bbgmvek) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/opt/invertedidx/json_array_test.go#L718)):*
> ```Go
> 		},
> 		{
> 			// Overlaps with an empty array produces a non-inverted expression
> ```

nit: end comments with a period (here and below)
___
*[pkg/sql/opt/invertedidx/json_array_test.go, line 724 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsSUKDEGnBOcgvMI6_:-MvsSUKDEGnBOcgvMI6a:b2waw4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/opt/invertedidx/json_array_test.go#L724)):*
> ```Go
> 		},
> 		{
> 			// Overlaps with conjunction of both tight expression with
> ```

nit: conjunction of both tight expression -> conjunction of two tight expressions (here and below)
___
*[pkg/sql/rowenc/index_encoding_test.go, line 742 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsTeDA03ctLtGFgIoK:-MvsTeDA03ctLtGFgIoL:b-6a5yd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/rowenc/index_encoding_test.go#L742)):*
> ```Go
> 		indexedValue string
> 		value        string
> 		inverted     bool
> ```

I'd call this `ok` instead
___
*[pkg/sql/rowenc/index_encoding_test.go, line 751 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsQFUF8wAVpbG1ZQdy:-MvsQFUF8wAVpbG1ZQdz:byd75jg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/rowenc/index_encoding_test.go#L751)):*
> ```Go
> 		// correctly overlap or be distinct from the first value.
> 
> 		// The expression is a union of spans, so unique should never be true
> ```

In this case, I don't think we need to include it as a parameter of the test case. It would be better to just unconditionally add a test below that the resulting `SpanExpression` has `Unique=false`
___
*[pkg/sql/rowenc/index_encoding_test.go, line 817 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsTlrN72TWiHyE1RXS:-MvsTlrN72TWiHyE1RXT:b9o4srv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/rowenc/index_encoding_test.go#L817)):*
> ```Go
> 
> 		// Array spans for && are never unique unless the result
> 		// is a singular empty array span.
> ```

I think you can change this  [...]

2022-02-14 15:14 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RajivTS)

___
*[pkg/sql/rowenc/index_encoding.go, line 867 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsMJPd7G4QfKCCeUi2:-MvsmXeq07ZpwgW-VW0Z:b-h7slnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/rowenc/index_encoding.go#L867)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

We support the notion of a "contradiction" in regular constraints -- I think we might want to do the same for inverted constraints. A contradiction for inverted constraints would effectively be an empty SpanExpression (`&inverted.SpanEpression{Tight: true, SpansToRead: []Span{}, FactoredUnionSpans: []Span{}}}`). Does returning that expression cause an error? If so, we may need to update the `inverted.SpanEpression` code to explicitly support contradictions (can be a separate PR).

In the mean time, if that causes an error, returning `inverted.NonInvertedColExpression{}` is fine. Could you just add a TODO here that this should be a contradiction?
</blockquote></details>

Another reason I'd really like to just return an empty span (i.e. contradiction) here instead of `inverted.NonInvertedColExpression` is that if we want to use this function to support inverted joins with `&&` in the future, returning `inverted.NonInvertedColExpression` won't work (and any normalization rule we add won't help).

Anyway, as I said, this is fine for now if returning an empty span doesn't work, but we'll need to change it in the future.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1512 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-Mvsm25BAejHRH_Sp9HL:-Mvsm25C9nQFsaunCUtr:brpfh0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/logictest/testdata/logic_test/inverted_index#L1512)):*
> ```
> ----
> 
> query T
> ```

For all of these tests that return multiple rows, you'll either need to add an `ORDER BY` clause or use the `rowsort` directive (e.g., `query T rowsort`). That will prevent the CI build failures we're seeing.


<!-- Sent from Reviewable.io -->

2022-02-21 21:08 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Great work! Thanks again for the contribution.

Do you want to take another look, @mgartner? Otherwise I'll go ahead and merge this.

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-:-MwT5uHZ7ligkYpqphYy:b-qlx1no)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)



<!-- Sent from Reviewable.io -->

2022-02-21 21:39 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nicely done!

I left some minor optional suggestions, and one question for @rytaft.

> Reviewed 1 of 8 files at r3, 1 of 7 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-:-MwTD8Qc9Cj-vdyuQTvZ:b2wthka)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner, @RajivTS, and @rytaft)

___
*[pkg/sql/opt/invertedidx/json_array.go, line 398 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MwT7iBhDdHGDmTP3KVj:-MwT7iBhDdHGDmTP3KVk:brz3nbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8e33a3e43be3fdb518de93146c76317b2e0d44f/pkg/sql/opt/invertedidx/json_array.go#L398)):*
> ```Go
> 		// inverted expression with the constant value picked from right.
> 		constantVal = right
> 	} else if isIndexColumn(j.tabID, j.index, right, j.computedColumns) && memo.CanExtractConstDatum(left) {
> ```

This is fine for now because it's following a pattern already established in this file, but in the long term I think it'd be better to make a normalization rule to commute `&&` expressions so that variables are always on the left and constants are always on the right. I'm not sure why we didn't do that for contains `@>` and contained by `<@`. Maybe those aren't commutative?
___
*[pkg/sql/rowenc/index_encoding_test.go, line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUHoZY3MqJC8DGfmo1:-MwTC3QJ59lCQBFvM7pV:bfma60a) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L752)):*
<details><summary><i>Previously, RajivTS (Rajiv Sharma) wrote…</i></summary><blockquote>

I am not so sure. Since the same element can be present in multiple rows for the same array, can `unique` be true? i.e. Will the spans produce no duplicate primary keys?
</blockquote></details>

It would be impossible to have duplicate entries in the inverted index for the same primary key - they index keys would be identical. Here's a kvtrace test that proves it:

```
statement ok
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT[],
  INVERTED INDEX (a),
  FAMILY (k, a)
)

query T kvtrace
INSERT INTO t VALUES (1, ARRAY[1, 2])
----
CPut /Table/106/1/1/0 -> /TUPLE/
InitPut /Table/106/2/1/1/0 -> /BYTES/
InitPut /Table/106/2/2/1/0 -> /BYTES/

query T kvtrace
INSERT INTO t VALUES (2, ARRAY[1, 2, 1])
----
CPut /Table/106/1/2/0 -> /TUPLE/
InitPut /Table/106/2/1/2/0 -> /BYTES/
InitPut /Table/106/2/2/2/0 -> /BYTES/
```

Regardless, I think setting `unique=true` for an expression like `a && ARRAY[1]` would be a minor performance improvement. Leaving it as `unique=false` wouldn't cause incorrect results, is that correct @rytaft?
___
*[pkg/sql/rowenc/index_encoding_test.go, line 784 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUH_WwCZ3MbdHZa4pC:-MwTBWXSCJCttLUwjDyk:b-cosyqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L784)):*
<details><summary><i>Previously, RajivTS (Rajiv Sharma) wrote…</i></summary><blockquote>

Tried with `NULL::INT[]` and `NULL` but they could not be parsed while running the test. Got the below error:
`Failed to parse array NULL::INT[]: could not parse "NULL::INT[]" as type int[]: array must be enclosed in { and }`
</blockquote></details>

You could add a check for `"NULL"` in parseArray like:

```go
if s == "NULL" {
    return tree.DNull
}
```


<!-- Sent from Reviewable.io -->

2022-02-21 22:00 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @RajivTS)

___
*[pkg/sql/rowenc/index_encoding.go, line 882 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MwTH4tg2nS5AQ4uq3MO:-MwTH4tg2nS5AQ4uq3MP:b-mgk2vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8e33a3e43be3fdb518de93146c76317b2e0d44f/pkg/sql/rowenc/index_encoding.go#L882)):*
> ```Go
> 			inverted.MakeSingleValSpan(key), true, /* tight */
> 		)
> 		if invertedExpr == nil {
> ```

I think you should add `spanExpr.Unique = true` above this line.
___
*[pkg/sql/rowenc/index_encoding_test.go, line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUHoZY3MqJC8DGfmo1:-MwTHCYj-DBJiYhZ0s8I:bi5zopc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L752)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It would be impossible to have duplicate entries in the inverted index for the same primary key - they index keys would be identical. Here's a kvtrace test that proves it:

```
statement ok
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT[],
  INVERTED INDEX (a),
  FAMILY (k, a)
)

query T kvtrace
INSERT INTO t VALUES (1, ARRAY[1, 2])
----
CPut /Table/106/1/1/0 -> /TUPLE/
InitPut /Table/106/2/1/1/0 -> /BYTES/
InitPut /Table/106/2/2/1/0 -> /BYTES/

query T kvtrace
INSERT INTO t VALUES (2, ARRAY[1, 2, 1])
----
CPut /Table/106/1/2/0 -> /TUPLE/
InitPut /Table/106/2/1/2/0 -> /BYTES/
InitPut /Table/106/2/2/2/0 -> /BYTES/
```

Regardless, I think setting `unique=true` for an expression like `a && ARRAY[1]` would be a minor performance improvement. Leaving it as `unique=false` wouldn't cause incorrect results, is that correct @rytaft?

</blockquote></details>

Yea -- I think you're totally right, @mgartner. I added a comment in the code where I think `unique` should be set to true. So unfortunately you'll need to undo the change where you removed `unique` from the test case, @rajivts.


<!-- Sent from Reviewable.io -->

2022-02-27 13:42 UTC, RajivTS reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner, @RajivTS, and @rytaft)

___
*[pkg/sql/rowenc/index_encoding.go, line 867 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsMJPd7G4QfKCCeUi2:-MwOA1YED5o76KFVRmmT:biisvji) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/rowenc/index_encoding.go#L867)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Another reason I'd really like to just return an empty span (i.e. contradiction) here instead of `inverted.NonInvertedColExpression` is that if we want to use this function to support inverted joins with `&&` in the future, returning `inverted.NonInvertedColExpression` won't work (and any normalization rule we add won't help).

Anyway, as I said, this is fine for now if returning an empty span doesn't work, but we'll need to change it in the future.
</blockquote></details>

Currently it does cause an error and the tests fail which is why I reverted to `inverted.NonInvertedColExpression`. Will add the TODO for now.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1512 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-Mvsm25BAejHRH_Sp9HL:-MwO6S3h2xFf1-ew0ixR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/logictest/testdata/logic_test/inverted_index#L1512)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

For all of these tests that return multiple rows, you'll either need to add an `ORDER BY` clause or use the `rowsort` directive (e.g., `query T rowsort`). That will prevent the CI build failures we're seeing.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 1398 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsOKraCAliSZGJ69Bs:-MwO77N34t2Vqanpr3Kp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L1398)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This comment is no longer valid for this test case, so please add a TODO for this case that we should have a normalization rule that turns this into a no-op, since the predicate is a contradiction.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 1444 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsOfP89ZJAzct05dq6:-MwO7GTqDgYnkWrfBkd6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L1444)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto here -- add a TODO
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 3365 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsP0L4EwlMOJWioF-c:-MwO8PEDDCM7uAgeqOA_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b434ce44f6baaca33fdc107fdb9119e414993c/pkg/sql/opt/xform/testdata/rules/select#L3365)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think these test cases are good, so it would be better to leave them in but use `expect-not=GenerateInvertedIndexScans` and explain in a TODO that they should be addressed with a normalization rule rather than `GenerateInvertedIndexScans`
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 3338 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsOqaQ9uQy0Mky4StW:-MwO7ea67oDrNU6QccAU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/opt/xform/testdata/rules/select#L3338)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

you can use `c@a_inv_idx` here to show the plan with the inverted index
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 3353 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsPEWS9oyCefabimUA:-MwO8Scd-b2VxVOvG9BE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1683881e5aff4a468b527a72d419900462704d7d/pkg/sql/opt/xform/testdata/rules/select#L3353)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

use c@a_inv_idx
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/json_array_test.go, line 744 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvsT2bp1Yhf4RNl6DN-:-MwO8YVFCP6OOMtnUAgX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b434ce44f6baaca33fdc107fdb9119e414993c/pkg/sql/opt/invertedidx/json_array_test.go#L744)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why did you remove this comment? I think it's useful
</blockquote></details>

Done.
___
*[pkg/sql/rowenc/index_encoding_test.go, line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUHoZY3MqJC8DGfmo1:-MwvFerZBOiW2qOTtebS:b-4445ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L752)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea -- I think you're totally right, @mgartner. I added a comment in the code where I think `unique` should be set to true. So unfortunately you'll need to undo the change where you removed `unique` from the test case, @rajivts.
</blockquote></details>

Unfortunately, I don't know how to read a KV trace so am unable to figure out how the above trace confirms that there cannot be a duplicate. If there are any resources that you can share to better understand the above terms, it would really help.

Let me describe how I think how this whole scenario is working out. Please rectify wherever I am incorrect.
A table `T` contains an indexed `INT` array column, let's call it `A`. Few of the entries in `A` are: `[1], [1, 2], [2, 3], [3, 5, 6, 7], [6, 8], [9,0]` with auto-incrementing primary key starting at 1. The inverted index on `A` would be a table roughly like below:
| Array Value (ID) | Primary Key in T (VAL) |
|-------------|------------------|
| 1           | 1, 2             |
| 2           | 2, 3             |
| 3           | 3, 4             |
| 5           | 4                |
| 6           | 4, 5             |
| 7           | 4                |
| 8           | 5                |
| 9           | 6                |
| 0           | 6                |

Assume that we are running a query as follows:
`SELECT * FROM T WHERE A && [0,1,2,8]`

After generating the inverted span expression for the constant value on the right hand-side, we get a modified query like:
`SELECT * FROM T WHERE T_Idx IN (SELECT VAL FROM InvertedIdx_A WHERE ID == 0 OR ID == 1 OR ID == 2 OR ID == 8)`

Assuming everything up until this point has been (roughly) correct, we can make the following claims about uniqueness:
1. The above inverted span expression is not `unique` due to the `OR`ing of the keys pulled from the array, i.e. `A && [1]` would be `unique` but not `A && [0,1,2,8]`. Thus, overlaps between an indexed array and a single element array would always be `unique`.
2. `OR`ing of two different overlaps will not be `unique` even if the individual overlaps themselves are `unique`, i.e. `A && [1] OR A && [2]` won't be `unique`.
3. `AND`ing of two different overlaps will be `unique` provided the individual overlaps themselves are `unique`, i.e.  `A && [1] AND A && [2]` will be `unique` but `A && [1, 2, 3] AND A && [5, 6]` will not be `unique`.
___
*[pkg/sql/rowenc/index_encoding_test.go, line 7 [...]

2022-02-27 13:44 UTC, RajivTS reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner, @RajivTS, and @rytaft)

___
*[pkg/sql/rowenc/index_encoding_test.go, line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUHoZY3MqJC8DGfmo1:-MwvPyvrAv3P5UdujVTL:bvxu77o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L752)):*
<details><summary><i>Previously, RajivTS (Rajiv Sharma) wrote…</i></summary><blockquote>

Unfortunately, I don't know how to read a KV trace so am unable to figure out how the above trace confirms that there cannot be a duplicate. If there are any resources that you can share to better understand the above terms, it would really help.

Let me describe how I think how this whole scenario is working out. Please rectify wherever I am incorrect.
A table `T` contains an indexed `INT` array column, let's call it `A`. Few of the entries in `A` are: `[1], [1, 2], [2, 3], [3, 5, 6, 7], [6, 8], [9,0]` with auto-incrementing primary key starting at 1. The inverted index on `A` would be a table roughly like below:
| Array Value (ID) | Primary Key in T (VAL) |
|-------------|------------------|
| 1           | 1, 2             |
| 2           | 2, 3             |
| 3           | 3, 4             |
| 5           | 4                |
| 6           | 4, 5             |
| 7           | 4                |
| 8           | 5                |
| 9           | 6                |
| 0           | 6                |

Assume that we are running a query as follows:
`SELECT * FROM T WHERE A && [0,1,2,8]`

After generating the inverted span expression for the constant value on the right hand-side, we get a modified query like:
`SELECT * FROM T WHERE T_Idx IN (SELECT VAL FROM InvertedIdx_A WHERE ID == 0 OR ID == 1 OR ID == 2 OR ID == 8)`

Assuming everything up until this point has been (roughly) correct, we can make the following claims about uniqueness:
1. The above inverted span expression is not `unique` due to the `OR`ing of the keys pulled from the array, i.e. `A && [1]` would be `unique` but not `A && [0,1,2,8]`. Thus, overlaps between an indexed array and a single element array would always be `unique`.
2. `OR`ing of two different overlaps will not be `unique` even if the individual overlaps themselves are `unique`, i.e. `A && [1] OR A && [2]` won't be `unique`.
3. `AND`ing of two different overlaps will be `unique` provided the individual overlaps themselves are `unique`, i.e.  `A && [1] AND A && [2]` will be `unique` but `A && [1, 2, 3] AND A && [5, 6]` will not be `unique`.
</blockquote></details>

Once the above logic gets confirmed, I will make changes to the `unique` part and associated tests.


<!-- Sent from Reviewable.io -->

2022-02-27 17:35 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @RajivTS)

___
*[pkg/sql/rowenc/index_encoding_test.go, line 752 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUHoZY3MqJC8DGfmo1:-MwwCj5dCkEBEqPaY9BO:b-t0nzg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L752)):*
<details><summary><i>Previously, RajivTS (Rajiv Sharma) wrote…</i></summary><blockquote>

Once the above logic gets confirmed, I will make changes to the `unique` part and associated tests.
</blockquote></details>

@rajivts your understanding is correct, as described in this comment: https://github.com/cockroachdb/cockroach/blob/a8fc111d61d409d1f81608aa60f9e755f0ce8aa5/pkg/sql/inverted/expression.go#L300-L305

I think your examples above would make great test cases.

The logic for `AND` and `OR` is already taken care of in `expression.go`, so you don't need to worry about implementing it. 

The logic for `AND` is implemented here: https://github.com/cockroachdb/cockroach/blob/a8fc111d61d409d1f81608aa60f9e755f0ce8aa5/pkg/sql/inverted/expression.go#L655

And the logic for `OR` is implemented here: https://github.com/cockroachdb/cockroach/blob/a8fc111d61d409d1f81608aa60f9e755f0ce8aa5/pkg/sql/inverted/expression.go#L680-L687
(notice that the resulting `SpanExpression` has the default value for `Unique`, which is `false` for booleans in go.)

I think you should be able to just set `spanExpr.Unique = true` where I indicated in `index_encoding.go` and it should all "just work".


<!-- Sent from Reviewable.io -->

2022-02-27 21:48 UTC, RajivTS reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/invertedidx/json_array.go, line 398 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MwT7iBhDdHGDmTP3KVj:-Mwx8KHQ2gs9R_n-iK-k:b61k4gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8e33a3e43be3fdb518de93146c76317b2e0d44f/pkg/sql/opt/invertedidx/json_array.go#L398)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is fine for now because it's following a pattern already established in this file, but in the long term I think it'd be better to make a normalization rule to commute `&&` expressions so that variables are always on the left and constants are always on the right. I'm not sure why we didn't do that for contains `@>` and contained by `<@`. Maybe those aren't commutative?
</blockquote></details>

Will work on that PR next. IMHO, `contains` and `contained by` don't appear to be commutative (i.e. `A @> B` isn't always the same as `B @> A`)
___
*[pkg/sql/rowenc/index_encoding.go, line 882 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MwTH4tg2nS5AQ4uq3MO:-Mwx8rP8An0EdZ6Lf2C9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8e33a3e43be3fdb518de93146c76317b2e0d44f/pkg/sql/rowenc/index_encoding.go#L882)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you should add `spanExpr.Unique = true` above this line.
</blockquote></details>

Done.
___
*[pkg/sql/rowenc/index_encoding_test.go, line 784 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvUH_WwCZ3MbdHZa4pC:-Mwx8Ev6DkPHC4vWQg4I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f21d1a568420dfe0778951a38b9c97d1f564cdaa/pkg/sql/rowenc/index_encoding_test.go#L784)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You could add a check for `"NULL"` in parseArray like:

```go
if s == "NULL" {
    return tree.DNull
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-27 23:29 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks again for the contribution, @rajivts!

bors r+

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-:-MwxVmCM0awQ3q7e3hO4:b48xplv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)



<!-- Sent from Reviewable.io -->

2022-02-28 14:12 UTC, ajwerner commented on pkg/sql/rowenc/index_encoding.go
> +	keys, err := encodeArrayInvertedIndexTableKeys(val, inKey, descpb.LatestNonPrimaryIndexDescriptorVersion, true /* excludeNulls */)
This needs a rebase. 

bors r-

2022-02-28 14:13 UTC, ajwerner commented
bors r-

2022-02-28 15:13 UTC, rytaft reviewed
Thanks, @ajwerner 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-:-Mx-tAan-eu7Piv6dFEI:bqv6g6a)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RajivTS)

___
*[pkg/sql/rowenc/index_encoding.go, line 874 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76212#-MvLeHS4kZpyYcIlmh0F-r6-874:-Mx-sgWP0alRYjxmxiOL:b-hoe9mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c368e32733bb370dfe70c09e444c4700b2f324b6/pkg/sql/rowenc/index_encoding.go#L874)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This needs a rebase. 

bors r-
</blockquote></details>

@rajivts I don't have permission to push to your branch, so can you please rebase from `cockroach/master` and change
`descpb.LatestNonPrimaryIndexDescriptorVersion` here to `descpb.PrimaryIndexWithStoredColumnsVersion`. Thanks!


<!-- Sent from Reviewable.io -->

2022-03-01 08:57 UTC, otan commented
unfortunately, i think the rebase here was done incorrectly. there are 2436 files changed.

2022-03-01 08:59 UTC, RajivTS commented
> unfortunately, i think the rebase here was done incorrectly. there are 2436 files changed.

Yes, I will try to do this fresh with a new branch, avoiding this entire hassle. Will close this PR and create a new one (with link to the original) once I am done with my changes.

2022-03-01 08:59 UTC, closed without merging