server, ui: aggregate statements on period selected
cockroachdb/cockroach pull request #76301
Opened 2022-02-09 16:00 UTC by maryliag

Previously, the aggregation timestamp was used as part
of the key of a statement. The new query to collect
statement now ignores aggregation timestamp as keys.
This commit also removes the aggregated timestamp value on the UI,
 since it no longer applies.

Fixes #74513

Release note (ui change): We don't show information about
aggregations timestamp in Statements overview and Details pages, since
now all the statement fingerprints are grouped inside the same
time selection.

2022-02-10 16:14 UTC, matthewtodd requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZNxOZ2gP43_8WI8vH):*
nits: "commits" -> "commit", "aggreagted" -> "aggregated"
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZNi3V3BUox0CppYYw):*
nit: Maybe spell out "timestamps" here (for docs writers / future readers) instead of abbreviating "ts"?
___
*[pkg/server/combined_statement_stats.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZOyhzCj7dJEIMCOMh:-MvZOyhzCj7dJEIMCOMi:bj28euk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L134)):*
> ```Go
> 				transaction_fingerprint_id,
> 				app_name,
> 				max(aggregated_ts) as aggregated_ts,
> ```

I'm wondering if we want `max` or `min` here -- do we want to show the latest or the earliest timestamp?
___
*[pkg/server/combined_statement_stats.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZOEDp5eYZ9F1GEWvk:-MvZOEDp5eYZ9F1GEWvl:b-s084tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L248)):*
> ```Go
> 				max(aggregated_ts) as aggregated_ts,
> 				fingerprint_id,
> 				max(metadata) as metadata,
> ```

I see we were already using `max` in `collectCombinedStatements`, but this has me wondering what the type of `metadata` is. From its name, I'm surprised that `max` is meaningful here, though maybe we just needed some way to say "take any one of them"?


<!-- Sent from Reviewable.io -->

2022-02-10 16:37 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @yuzefovich)

___
*[pkg/server/combined_statement_stats.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZOEDp5eYZ9F1GEWvk:-MvZQXnb6IXS96-ujYLK:b18js80) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L248)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I see we were already using `max` in `collectCombinedStatements`, but this has me wondering what the type of `metadata` is. From its name, I'm surprised that `max` is meaningful here, though maybe we just needed some way to say "take any one of them"?
</blockquote></details>

Hmm I think in SQL Engine we have an [`any_not_null` aggregation operator](https://github.com/cockroachdb/cockroach/blob/c38023e5350b191fae4ea7f36d561d3b309212d2/pkg/sql/colexec/colexecagg/any_not_null_agg_tmpl.go#L65). However, it's used only internally and I don't think that's expose anywhere in the SQL CLI. 

Second thoughts here, `metadata` column is a big JSON blob. Running `max` aggregation essentially performs ordering comparison between those JSON blob. However, since we know that for each distinct `fingerprint_id`, its `metadata` column should be identical. So the JSON ordering comparison is mostly not useful computation. 

cc: @yuzefovich  any thoughts we can better express this `any_not_null` semantics better here in this query? 
___
*[pkg/server/combined_statement_stats.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZRjRO92l7wzhKRCZr:-MvZRjRO92l7wzhKRCZs:b-ftiob2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L249)):*
> ```Go
> 				fingerprint_id,
> 				max(metadata) as metadata,
> 				crdb_internal.merge_transaction_stats(array_agg(statistics)) AS statistics,
> ```

`array_agg` buffers all the rows in the same `GROUP BY` clause in-memory first before feeding them into `merge_transaction_stats`. So `array_agg` here effectively means that we are performing buffered aggregation. This might have some memory usage concerns here. 

Previously, we used `array_agg` to perform aggregation across the statement/transaction stats from multiple nodes. 
This was mostly fine since the amount of data is quite small. (e.g. we have maximum like 100 nodes or so, so this array is maximally size of 100-ish).

Now we are aggregating across a wider span of rows. We can do some quick math to get an idea how much data we are dealing with here, E.g. if user request statement statistics for the last month, assuming we are doing 1 hour agg interval, 30 days * 24 hours / days * 100 node * 1 row / hour = 72,000 rows (or size of the `tree.Datums` array when `array_agg` is executed). That's how much data we need to buffer per distinct statement stats. Optimistically, assuming each row takes 1 KiB, that means we buffering 72 MiB per distinct fingerprint. I'm afraid that at some point, the amount of data is just too large and SQL Engine would either decide to spill to disk (a better scenario) or just kill the query to protect itself from blowing up the memory.

Hmm so perhaps a better strategy here would be ditch the `GROUP BY` clause and use `ORDER BY` to get the the input to be in the correct order. Then we can perform streaming aggregation here without worrying about blowing up the memory. 

cc: @yuzefovich  also I want to poke your brain here a bit to see if my concern here is valid, and if there's a better strategy.


<!-- Sent from Reviewable.io -->

2022-02-10 22:15 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/server/combined_statement_stats.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZOEDp5eYZ9F1GEWvk:-Mv_XY5q03qaCumvfJh2:b3vow02) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L248)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm I think in SQL Engine we have an [`any_not_null` aggregation operator](https://github.com/cockroachdb/cockroach/blob/c38023e5350b191fae4ea7f36d561d3b309212d2/pkg/sql/colexec/colexecagg/any_not_null_agg_tmpl.go#L65). However, it's used only internally and I don't think that's expose anywhere in the SQL CLI. 

Second thoughts here, `metadata` column is a big JSON blob. Running `max` aggregation essentially performs ordering comparison between those JSON blob. However, since we know that for each distinct `fingerprint_id`, its `metadata` column should be identical. So the JSON ordering comparison is mostly not useful computation. 

cc: @yuzefovich  any thoughts we can better express this `any_not_null` semantics better here in this query? 
</blockquote></details>

`any_not_null` is an internal-only aggregate function that is used for columns from GROUP BY clause that need to be projected out (e.g. `app_name` in this query). Archer is right that using `max` will make us perform comparison of `metadata` objects within each aggregation bucket, and if all `metadata` values are the same, then it would be a redundant computation. We could include `metadata` in the GROUP BY clause and not use `max`, but then we'd have the same problem of redundant comparisons, just at a different stage (during grouping rather than during aggregation).

Unfortunately, I don't see a way to not perform these comparisons without allowing to use `any_not_null` aggregate explicitly in the query - that, however, might be a somewhat large change (the execution support is there, but the amount of changes in the optimizer is unknown to me).

I think using `max` or `min` is ok for now. I'd be curious to see the benchmarks of the performance overhead of having these redundant comparisons (i.e. try the query with and without `metadata` column) on a large dataset.
___
*[pkg/server/combined_statement_stats.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZRjRO92l7wzhKRCZr:-Mv_f4xu8nfEmG1xSpDK:b-i01qyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L249)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

`array_agg` buffers all the rows in the same `GROUP BY` clause in-memory first before feeding them into `merge_transaction_stats`. So `array_agg` here effectively means that we are performing buffered aggregation. This might have some memory usage concerns here. 

Previously, we used `array_agg` to perform aggregation across the statement/transaction stats from multiple nodes. 
This was mostly fine since the amount of data is quite small. (e.g. we have maximum like 100 nodes or so, so this array is maximally size of 100-ish).

Now we are aggregating across a wider span of rows. We can do some quick math to get an idea how much data we are dealing with here, E.g. if user request statement statistics for the last month, assuming we are doing 1 hour agg interval, 30 days * 24 hours / days * 100 node * 1 row / hour = 72,000 rows (or size of the `tree.Datums` array when `array_agg` is executed). That's how much data we need to buffer per distinct statement stats. Optimistically, assuming each row takes 1 KiB, that means we buffering 72 MiB per distinct fingerprint. I'm afraid that at some point, the amount of data is just too large and SQL Engine would either decide to spill to disk (a better scenario) or just kill the query to protect itself from blowing up the memory.

Hmm so perhaps a better strategy here would be ditch the `GROUP BY` clause and use `ORDER BY` to get the the input to be in the correct order. Then we can perform streaming aggregation here without worrying about blowing up the memory. 

cc: @yuzefovich  also I want to poke your brain here a bit to see if my concern here is valid, and if there's a better strategy.
</blockquote></details>

Your description seemed reasonable to me, so I decided to take a look the EXPLAIN of the query:
```
EXPLAIN (TYPES)
  SELECT
    app_name,
    max(aggregated_ts) AS aggregated_ts,
    fingerprint_id,
    max(metadata) AS metadata,
    crdb_internal.merge_transaction_stats(array_agg(statistics)) AS statistics,
    aggregation_interval
  FROM
    crdb_internal.transaction_statistics
  GROUP BY
    app_name, fingerprint_id, aggregation_interval
  ORDER BY
    1, 2, 3
  LIMIT
    1;
                                                                                         info
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • render
  │ columns: (app_name string, aggregated_ts timestamptz, fingerprint_id bytes, metadata jsonb, statistics jsonb, aggregation_interval interval)
  │ estimated row count: 1 (missing stats)
  │ render statistics: (crdb_internal.merge_transaction_stats((array_agg)[jsonb[]]))[jsonb]
  │ render fingerprint_id: (fingerprint_id)[bytes]
  │ render app_name: (app_name)[string]
  │ render aggregation_interval: (aggregation_interval)[interval]
  │ render max: (max)[timestamptz]
  │ render max: (max)[jsonb]
  │
  └── • top-k
      │ columns: (fingerprint_id bytes, app_name string, aggregation_interval interval, max timestamptz, max jsonb, array_agg jsonb[])
      │ ordering: +app_name,+max,+fingerprint_id
      │ estimated row count: 1 (missing stats)
      │ order: +app_name,+max,+fingerprint_id
      │ k: 1
      │
      └── • group (hash)
          │ columns: (fingerprint_id bytes, app_name string, aggregation_interval interval, max timestamptz, max jsonb, array_agg jsonb[])
          │ estimated row count: 2,000 (missing stats)
          │ aggregate 0: max(aggregated_ts)
          │ aggregate 1: max(max)
          │ aggregate 2: array_agg(crdb_internal.merge_transaction_stats)
          │ group by: fingerprint_id, app_name, aggregation_interval
          │
          └── • render
              │ columns: ("crdb_internal.merge_transaction_stats" jsonb, aggregated_ts timestamptz, fingerprint_id bytes, app_name string, aggregation_interval interval, max jsonb)
              │ estimated row count: 2,000 (missing stats)
              │ render crdb_internal.merge_transaction_stats: (crdb_internal.merge_transaction_stats((array_agg)[jsonb[]]))[jsonb]
              │ render aggregated_ts: (aggregated_ts)[timestamptz]
              │ render fingerprint_id: (fingerprint_id)[bytes]
              │ render app_name: (app_name)[string]
              │ render aggregation_interval: (aggregation_interval)[interval]
              │ render max: (max)[jsonb]
              │
              └── • group (hash)
                  │ columns: (aggregated_ts timestamptz, fingerprint_id bytes, app_name string, aggregation_interval interval, max jsonb, array_agg jsonb[])
                  │ estimated row count: 2,000 (missing stats)
                  │ aggregate 0: max(metadata)
                  │ aggregate 1: array_agg(statistics)
                  │ group by: aggregated_ts, fingerprint_id, app_name, aggregation_interval
                  │
                  └── • union all
                      │ columns: (aggregated_ts timestamptz, fingerprint_id bytes, app_name string, metadata jsonb, statistics jsonb, aggregation_interval interval)
              [...]

2022-02-10 23:23 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag, @matthewtodd, and @yuzefovich)

___
*[pkg/server/combined_statement_stats.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZOEDp5eYZ9F1GEWvk:-Mv_vtniCSD2Cg1Ctvia:b-97fxnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L248)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`any_not_null` is an internal-only aggregate function that is used for columns from GROUP BY clause that need to be projected out (e.g. `app_name` in this query). Archer is right that using `max` will make us perform comparison of `metadata` objects within each aggregation bucket, and if all `metadata` values are the same, then it would be a redundant computation. We could include `metadata` in the GROUP BY clause and not use `max`, but then we'd have the same problem of redundant comparisons, just at a different stage (during grouping rather than during aggregation).

Unfortunately, I don't see a way to not perform these comparisons without allowing to use `any_not_null` aggregate explicitly in the query - that, however, might be a somewhat large change (the execution support is there, but the amount of changes in the optimizer is unknown to me).

I think using `max` or `min` is ok for now. I'd be curious to see the benchmarks of the performance overhead of having these redundant comparisons (i.e. try the query with and without `metadata` column) on a large dataset.
</blockquote></details>

Hmm interesting. :thinking: 

It seems like somehow slightly improved the memory usage (from 166 MB -> 138 MB) in the second aggregator. Though the execution time remained mostly the same. 

[Query Plan using `max`](https://cockroachdb.github.io/distsqlplan/decode.html#eJykVdtu2zgUfN-vOOCTDbCxqIvj6IlukBbBxnHhuMUGC0NgpFNFqESqJNUmCPJZ-wP7ZQtKTmrLcTZJ38Q5HHI4c0jdEfO9JDG5ODk7OV7C10LmqGtdSJsUGQWrhTQitYWSSb8m6jqRokIKlbgZVGhFJqwYwvQCHgYUUp1dJYW0qKUoDyrUOSbGCosVStt-mYHQWtwmIs8HblwYW6Rm2K7za9xtYkRVl5gldSlkN2EDgA-L-ay34fZW3VKON_8AF5cXy5MZLE9nJ_BVlaX6iTrRKLLEFhUaK6p6MISPi_nnT_D-8k3OwNnp7HQJvud5HqFEqgzPRYWGxH8TRlaU1FqlaIzSDrprJ5xmNyT2KClk3VgHryhJlUYS3xFb2BJJTJbiqsQFigz1yC2coRVF2S771IF5rYtK6FtCybEqm0qaGESea8yFxSyxhr7qdM7r5FqY640WIJS4JTvjf4iSbrTAZoiOSyi5qIUT8Y5QMm9sDJxR7lMeUB5SHlF-SPmE8iPKx4SSP7-ASyQG3z-ITAekSlqUTt665v37z7qk1U8DLscY2GRMfRZ1-NWtxYdCEIYwK94TSmZfjo_BWKwhVY20MMAbOyqkHcYQHEZ0HHojNpnQw-jocTLitycm-_4o8H1CSSVuoMJK6VsQZalS53EMLFhveCVseo0GVGNrd3R2xAglrehHaC17dU9Jh637wFiRI4nZPX15rzgFJfwotG1ECdZ1Dngjtt01eINps-EmCzs7-2K9vlRvr0h_r8hf2gzqQpTQSKUz1JhtiVrdP3Gac_VO1SP_efW-x56W_wavvdd4PV1fKqVHwbbEfoO7bpqeXybn82Vy_vnsbMDZcAfyd6FgFwp3oWgXOnLQbPrXgI_b4mIxvUymHz8O-OFjZeK-Figz1PGLHm4-GVLgPgUeUOARBX5IoT3bTkONDyZm7-WYsPXlcGXzvQSLVQ1ZYb5BY0SOMUTR3uvjvzbS4I2Rhr1I13n-Tmyt7VEvELYd1UMgnG14Hb7sz8ojF5B7RM-KqrCPf6J-PEcHbH86bDz-v3hCtieecbSTDg398d5swtdks0BTK2mw92zsu8grSjDLsXuCjGp0ip-0StttuuG85bVAhsZ2Vb8bnMq21L69m2T2O2T_WXKwRfb65OBZcvg8OXyWHPXIq_s__gsAAP__-K5HdA==)

[Query Plan putting the `metadata` in the `GROUP BY`](https://cockroachdb.github.io/distsqlplan/decode.html#eJysVdtu2zgQfd-vGPDJBthYN8e2nugGaWGsL4XtFhssDIGRpopQiVRJqnUQ5LP2B_bLFpTcxJbjNGn3TTzDQ56ZMxzdEf01JyFZXU4vL9bwORMpqlJlwkRZQsEoLjSPTSZF1I7xsowEL5BCgYYn3HAKsUquo0wYVILnZwWqFCNtuMECham_dIcrxW8jnqYdu860yWLd7cJ4BY9rCgXfdjQvyhyTqMy5aDbsAfBuuZi1Ljy8qjnK8hbvYHW1Wl_OYD2ZXcJnmefyO6pIIU8ikxWoDS_KThfeLxcfP8Dbq98sBEwns8kaPMdxHEKJkAnOeYGahH8Tl2woKZWMUWupLHRXb5gkWxI6lGSirIyFN5TEUiEJ74jJTI4kJGt-neMSeYKqZw9O0PAsr499KnVWqqzg6pZQciHzqhA6BJ6mClNuMImMpq_K01Y9uuH6Zi9lQok9srHgG8_3m2HfTssllKxKbkW8IZQsKhMCcynzKPMpCyjrUzagbEjZiLJzQsmfn8B6E4LnnfV1A8RSGBRW3i7m_PvPLqTkdw3W0RDc4Tn1PL_Br28N_gj4QQCz7C2hZPbp4gK0wRJiWQkDHdyaXiZMNwR_0KeDkd9zRw71vMHDZsQvT2wOgp4fBISSgm-hwEKqW-B5LmNb4xBcf3fhNTfxDWqQlSlt6u7IJZTUoh-gnezNPSUNtusDbXiKJHTv6ct7xSrI4VumTMVzMLZzwOm5h12DW4yrvWq6g6acbbFOW6pzUqR3UuSjNo0q4zlUQqoEFSYHojb3T2Qzl29k2fN-on7kPS3_F2rtvKbW492jkqrnH0psN_iIUDKeX0XzxTqaf5xOO8ztHkHeMeQfQ8Ex1D-GRhaajf_qsPM6uFyOr6Lx-_cdNniIDO3XEkWCKnzRCGfDLgXmUWA-BdanwAYU6tyOLDk_G-qTj2Po7h6HDeuvORgsSkgy_QUqzVMMod8_-Xy811rq_6KlQcvSRz__b-cezXEPbfthDnP36h687H_L-tYsO1CnWZGZh79S26rRmXfaKdcf_syqwD1llXc0Plwa-N5Jo4LXGLVEXUqhsTVDTr3qDSWYpNjMIy0rFeMHJeP6mma5qHk1kKA2TdRrFhNRh-pBvE92f4fsPUv2D8hOm-w_Sw6eJwfPkvst8ub-j_8CAAD___ZxSQ8=)
___
*[pkg/server/combined_statement_stats.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZRjRO92l7wzhKRCZr:-Mv_ta5R1tlRE7-jVLqC:bh9glhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L249)):*
> IIUC the concern is that the removal aggregated_ts from GROUP BY in this query made many more buckets

I think the number of buckets here is less of a concern, I'm more concerned that the size of each bucket now is a lot bigger. 

Testing the query in the CLI, the second aggregator stage's
* execution time went from 2 seconds -> 9 seconds 
* allocated memory went from 76 MiB -> 166 MiB

This is with about ~180k rows in the table. Thoughts on if this growth would be reasonable?

The URL output of the `EXPLAIN ANALYZE (distsql)` is attached below

[Original Query](https://cockroachdb.github.io/distsqlplan/decode.html#eJy0lV9u2zgQxt_3FAM-2cA01j_Ljp7kBmkRbBwXjltssDAERpo6QiVSJak2QZBj7QX2ZAtKruPIdpp0d9_Ebzjkx_kNqXumvxYsYpen56cnC_icixWpSuXCJHmGYBQXmqcmlyLpxnhVJYKXhMBXK0UrbihLjEYo-W2vJMMzbngfJpfwY4CQquw6yYUhJXhxVJJaUaINN1SSMM2X7nGl-F3CV6ueHefa5KnuN-s8jttNNC-rgrKkKrhoJ2wJj7as-WbPb7yAd_PZtGPjqYF2A7va7B1cXl0uTqewOJuewmdZFPI7qUQRzxKTl6QNL6teH97PZx8_wNur_6Z8e22fn03PFuA5juMwZEJmdMFL0iz6k7lsiaxSMiWtpbLSfTPhLLtlkYMsF1VtrLxElkpFLLpnJjcFsYgt-HVBc-IZqYFdOCPD86JZdl9V4krlJVd3DNmJLOpS6Kjr_jUlsJiSG65vtqrBkNklNyfHre7Z5m9zGbLLilsTbxiyWW0iiF2MPYx9jAOMhxiPMB5jfIxxyJD9_gkstgg87yjQrZBKYUhYe-uY8_df65CS3zVY2BG44xA9N2j16ztDPwJ-EMA0f8uQTT-dnIA2VEEqa2GgR7dmkAvTj8AfDXE4PB644zEG3mgzmejLnsmeN_A9jyEr-S2UVEp1B7woZGprHIHrrze85ia9IQ2yNpU9unvsMmSN6Y20tr18QNZq6z7Qhq-IRe4DvrxXrIMCvuXK1LwAYzsHnIH7tGvoltJ6q5pu2Jaza9bpWnUOmvQOmnz0pknlvIBaSJWRouyJqeXDntNcyDeyGng_cT86YP8Xau28ptaT9aWSauA_tdht8GOGbHJxlVzMFsnFx_PzXuz2dyRvV_J3pWBXGu5Kx1aaTv7oxWETnM8nV8nk_ftePNpExvZrTiIjFb3ozY_HfbR3F2IPIfYR4iFCHCLEI4TmjLuNdRTqg5dk7K4viQ3rrwUYKivIcv0Fas1XFMFwePAaea9F6_8i2qCDdptr-L9CDDeoRh2I7n6IGy7BmlP4sp95PLJgxxYoQ3ael7nZ_MW6SL2j8WGio_CnRMMDRL2du-o5aC0c4hm8huecdCWFps6Tc-gRWCKjbEXt86VlrVL6oGTabNMOZ01eI2SkTRv12sGZaELNu72d7P6bZO_ZZP9JstNN9p9NDp5PDp5NHnaSlw-__RMAAP__UCRyNg==)

[New Query](https://cockroachdb.github.io/distsqlplan/decode.html#eJykVdtu2zgUfN-vOOCTDbCxqIvj6IlukBbBxnHhuMUGC0NgpFNFqESqJNUmCPJZ-wP7ZQtKTmrLcTZJ38Q5HHI4c0jdEfO9JDG5ODk7OV7C10LmqGtdSJsUGQWrhTQitYWSSb8m6jqRokIKlbgZVGhFJqwYwvQCHgYUUp1dJYW0qKUoDyrUOSbGCosVStt-mYHQWtwmIs8HblwYW6Rm2K7za9xtYkRVl5gldSlkN2EDgA-L-ay34fZW3VKON_8AF5cXy5MZLE9nJ_BVlaX6iTrRKLLEFhUaK6p6MISPi_nnT_D-8k3OwNnp7HQJvud5HqFEqgzPRYWGxH8TRlaU1FqlaIzSDrprJ5xmNyT2KClk3VgHryhJlUYS3xFb2BJJTJbiqsQFigz1yC2coRVF2S771IF5rYtK6FtCybEqm0qaGESea8yFxSyxhr7qdM7r5FqY640WIJS4JTvjf4iSbrTAZoiOSyi5qIUT8Y5QMm9sDJxR7lMeUB5SHlF-SPmE8iPKx4SSP7-ASyQG3z-ITAekSlqUTt665v37z7qk1U8DLscY2GRMfRZ1-NWtxYdCEIYwK94TSmZfjo_BWKwhVY20MMAbOyqkHcYQHEZ0HHojNpnQw-jocTLitycm-_4o8H1CSSVuoMJK6VsQZalS53EMLFhveCVseo0GVGNrd3R2xAglrehHaC17dU9Jh637wFiRI4nZPX15rzgFJfwotG1ECdZ1Dngjtt01eINps-EmCzs7-2K9vlRvr0h_r8hf2gzqQpTQSKUz1JhtiVrdP3Gac_VO1SP_efW-x56W_wavvdd4PV1fKqVHwbbEfoO7bpqeXybn82Vy_vnsbMDZcAfyd6FgFwp3oWgXOnLQbPrXgI_b4mIxvUymHz8O-OFjZeK-Figz1PGLHm4-GVLgPgUeUOARBX5IoT3bTkONDyZm7-WYsPXlcGXzvQSLVQ1ZYb5BY0SOMUTR3uvjvzbS4I2Rhr1I13n-Tmyt7VEvELYd1UMgnG14Hb7sz8ojF5B7RM-KqrCPf6J-PEcHbH86bDz-v3hCtieecbSTDg398d5swtdks0BTK2mw92zsu8grSjDLsXuCjGp0ip-0StttuuG85bVAhsZ2Vb8bnMq21L69m2T2O2T_WXKwRfb65OBZcvg8OXyWHPXIq_s__gsAAP__-K5HdA==)


<!-- Sent from Reviewable.io -->

2022-02-11 01:22 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/server/combined_statement_stats.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZRjRO92l7wzhKRCZr:-MvaMlQg60B3BEe8Tqu1:b-vufmbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L249)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

> IIUC the concern is that the removal aggregated_ts from GROUP BY in this query made many more buckets

I think the number of buckets here is less of a concern, I'm more concerned that the size of each bucket now is a lot bigger. 

Testing the query in the CLI, the second aggregator stage's
* execution time went from 2 seconds -> 9 seconds 
* allocated memory went from 76 MiB -> 166 MiB

This is with about ~180k rows in the table. Thoughts on if this growth would be reasonable?

The URL output of the `EXPLAIN ANALYZE (distsql)` is attached below

[Original Query](https://cockroachdb.github.io/distsqlplan/decode.html#eJy0lV9u2zgQxt_3FAM-2cA01j_Ljp7kBmkRbBwXjltssDAERpo6QiVSJak2QZBj7QX2ZAtKruPIdpp0d9_Ebzjkx_kNqXumvxYsYpen56cnC_icixWpSuXCJHmGYBQXmqcmlyLpxnhVJYKXhMBXK0UrbihLjEYo-W2vJMMzbngfJpfwY4CQquw6yYUhJXhxVJJaUaINN1SSMM2X7nGl-F3CV6ueHefa5KnuN-s8jttNNC-rgrKkKrhoJ2wJj7as-WbPb7yAd_PZtGPjqYF2A7va7B1cXl0uTqewOJuewmdZFPI7qUQRzxKTl6QNL6teH97PZx8_wNur_6Z8e22fn03PFuA5juMwZEJmdMFL0iz6k7lsiaxSMiWtpbLSfTPhLLtlkYMsF1VtrLxElkpFLLpnJjcFsYgt-HVBc-IZqYFdOCPD86JZdl9V4krlJVd3DNmJLOpS6Kjr_jUlsJiSG65vtqrBkNklNyfHre7Z5m9zGbLLilsTbxiyWW0iiF2MPYx9jAOMhxiPMB5jfIxxyJD9_gkstgg87yjQrZBKYUhYe-uY8_df65CS3zVY2BG44xA9N2j16ztDPwJ-EMA0f8uQTT-dnIA2VEEqa2GgR7dmkAvTj8AfDXE4PB644zEG3mgzmejLnsmeN_A9jyEr-S2UVEp1B7woZGprHIHrrze85ia9IQ2yNpU9unvsMmSN6Y20tr18QNZq6z7Qhq-IRe4DvrxXrIMCvuXK1LwAYzsHnIH7tGvoltJ6q5pu2Jaza9bpWnUOmvQOmnz0pknlvIBaSJWRouyJqeXDntNcyDeyGng_cT86YP8Xau28ptaT9aWSauA_tdht8GOGbHJxlVzMFsnFx_PzXuz2dyRvV_J3pWBXGu5Kx1aaTv7oxWETnM8nV8nk_ftePNpExvZrTiIjFb3ozY_HfbR3F2IPIfYR4iFCHCLEI4TmjLuNdRTqg5dk7K4viQ3rrwUYKivIcv0Fas1XFMFwePAaea9F6_8i2qCDdptr-L9CDDeoRh2I7n6IGy7BmlP4sp95PLJgxxYoQ3ael7nZ_MW6SL2j8WGio_CnRMMDRL2du-o5aC0c4hm8huecdCWFps6Tc-gRWCKjbEXt86VlrVL6oGTabNMOZ01eI2SkTRv12sGZaELNu72d7P6bZO_ZZP9JstNN9p9NDp5PDp5NHnaSlw-__RMAAP__UCRyNg==)

[New Query](https://cockroachdb.github.io/distsqlplan/decode.html#eJykVdtu2zgUfN-vOOCTDbCxqIvj6IlukBbBxnHhuMUGC0NgpFNFqESqJNUmCPJZ-wP7ZQtKTmrLcTZJ38Q5HHI4c0jdEfO9JDG5ODk7OV7C10LmqGtdSJsUGQWrhTQitYWSSb8m6jqRokIKlbgZVGhFJqwYwvQCHgYUUp1dJYW0qKUoDyrUOSbGCosVStt-mYHQWtwmIs8HblwYW6Rm2K7za9xtYkRVl5gldSlkN2EDgA-L-ay34fZW3VKON_8AF5cXy5MZLE9nJ_BVlaX6iTrRKLLEFhUaK6p6MISPi_nnT_D-8k3OwNnp7HQJvud5HqFEqgzPRYWGxH8TRlaU1FqlaIzSDrprJ5xmNyT2KClk3VgHryhJlUYS3xFb2BJJTJbiqsQFigz1yC2coRVF2S771IF5rYtK6FtCybEqm0qaGESea8yFxSyxhr7qdM7r5FqY640WIJS4JTvjf4iSbrTAZoiOSyi5qIUT8Y5QMm9sDJxR7lMeUB5SHlF-SPmE8iPKx4SSP7-ASyQG3z-ITAekSlqUTt665v37z7qk1U8DLscY2GRMfRZ1-NWtxYdCEIYwK94TSmZfjo_BWKwhVY20MMAbOyqkHcYQHEZ0HHojNpnQw-jocTLitycm-_4o8H1CSSVuoMJK6VsQZalS53EMLFhveCVseo0GVGNrd3R2xAglrehHaC17dU9Jh637wFiRI4nZPX15rzgFJfwotG1ECdZ1Dngjtt01eINps-EmCzs7-2K9vlRvr0h_r8hf2gzqQpTQSKUz1JhtiVrdP3Gac_VO1SP_efW-x56W_wavvdd4PV1fKqVHwbbEfoO7bpqeXybn82Vy_vnsbMDZcAfyd6FgFwp3oWgXOnLQbPrXgI_b4mIxvUymHz8O-OFjZeK-Figz1PGLHm4-GVLgPgUeUOARBX5IoT3bTkONDyZm7-WYsPXlcGXzvQSLVQ1ZYb5BY0SOMUTR3uvjvzbS4I2Rhr1I13n-Tmyt7VEvELYd1UMgnG14Hb7sz8ojF5B7RM-KqrCPf6J-PEcHbH86bDz-v3hCtieecbSTDg398d5swtdks0BTK2mw92zsu8grSjDLsXuCjGp0ip-0StttuuG85bVAhsZ2Vb8bnMq21L69m2T2O2T_WXKwRfb65OBZcvg8OXyWHPXIq_s__gsAAP__-K5HdA==)
</blockquote></details>

Thanks for checking this out. I wanna play around a bit with the data set, do you mind sharing it somehow?


<!-- Sent from Reviewable.io -->

2022-02-11 02:02 UTC, Azhng reviewed
_deleted_

2022-02-11 02:27 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/server/combined_statement_stats.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZOEDp5eYZ9F1GEWvk:-MvaahCW7SEUqC0xqhC0:bzdc9sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L248)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm interesting. :thinking: 

It seems like somehow slightly improved the memory usage (from 166 MB -> 138 MB) in the second aggregator. Though the execution time remained mostly the same. 

[Query Plan using `max`](https://cockroachdb.github.io/distsqlplan/decode.html#eJykVdtu2zgUfN-vOOCTDbCxqIvj6IlukBbBxnHhuMUGC0NgpFNFqESqJNUmCPJZ-wP7ZQtKTmrLcTZJ38Q5HHI4c0jdEfO9JDG5ODk7OV7C10LmqGtdSJsUGQWrhTQitYWSSb8m6jqRokIKlbgZVGhFJqwYwvQCHgYUUp1dJYW0qKUoDyrUOSbGCosVStt-mYHQWtwmIs8HblwYW6Rm2K7za9xtYkRVl5gldSlkN2EDgA-L-ay34fZW3VKON_8AF5cXy5MZLE9nJ_BVlaX6iTrRKLLEFhUaK6p6MISPi_nnT_D-8k3OwNnp7HQJvud5HqFEqgzPRYWGxH8TRlaU1FqlaIzSDrprJ5xmNyT2KClk3VgHryhJlUYS3xFb2BJJTJbiqsQFigz1yC2coRVF2S771IF5rYtK6FtCybEqm0qaGESea8yFxSyxhr7qdM7r5FqY640WIJS4JTvjf4iSbrTAZoiOSyi5qIUT8Y5QMm9sDJxR7lMeUB5SHlF-SPmE8iPKx4SSP7-ASyQG3z-ITAekSlqUTt665v37z7qk1U8DLscY2GRMfRZ1-NWtxYdCEIYwK94TSmZfjo_BWKwhVY20MMAbOyqkHcYQHEZ0HHojNpnQw-jocTLitycm-_4o8H1CSSVuoMJK6VsQZalS53EMLFhveCVseo0GVGNrd3R2xAglrehHaC17dU9Jh637wFiRI4nZPX15rzgFJfwotG1ECdZ1Dngjtt01eINps-EmCzs7-2K9vlRvr0h_r8hf2gzqQpTQSKUz1JhtiVrdP3Gac_VO1SP_efW-x56W_wavvdd4PV1fKqVHwbbEfoO7bpqeXybn82Vy_vnsbMDZcAfyd6FgFwp3oWgXOnLQbPrXgI_b4mIxvUymHz8O-OFjZeK-Figz1PGLHm4-GVLgPgUeUOARBX5IoT3bTkONDyZm7-WYsPXlcGXzvQSLVQ1ZYb5BY0SOMUTR3uvjvzbS4I2Rhr1I13n-Tmyt7VEvELYd1UMgnG14Hb7sz8ojF5B7RM-KqrCPf6J-PEcHbH86bDz-v3hCtieecbSTDg398d5swtdks0BTK2mw92zsu8grSjDLsXuCjGp0ip-0StttuuG85bVAhsZ2Vb8bnMq21L69m2T2O2T_WXKwRfb65OBZcvg8OXyWHPXIq_s__gsAAP__-K5HdA==)

[Query Plan putting the `metadata` in the `GROUP BY`](https://cockroachdb.github.io/distsqlplan/decode.html#eJysVdtu2zgQfd-vGPDJBthYN8e2nugGaWGsL4XtFhssDIGRpopQiVRJqnUQ5LP2B_bLFpTcxJbjNGn3TTzDQ56ZMxzdEf01JyFZXU4vL9bwORMpqlJlwkRZQsEoLjSPTSZF1I7xsowEL5BCgYYn3HAKsUquo0wYVILnZwWqFCNtuMECham_dIcrxW8jnqYdu860yWLd7cJ4BY9rCgXfdjQvyhyTqMy5aDbsAfBuuZi1Ljy8qjnK8hbvYHW1Wl_OYD2ZXcJnmefyO6pIIU8ikxWoDS_KThfeLxcfP8Dbq98sBEwns8kaPMdxHEKJkAnOeYGahH8Tl2woKZWMUWupLHRXb5gkWxI6lGSirIyFN5TEUiEJ74jJTI4kJGt-neMSeYKqZw9O0PAsr499KnVWqqzg6pZQciHzqhA6BJ6mClNuMImMpq_K01Y9uuH6Zi9lQok9srHgG8_3m2HfTssllKxKbkW8IZQsKhMCcynzKPMpCyjrUzagbEjZiLJzQsmfn8B6E4LnnfV1A8RSGBRW3i7m_PvPLqTkdw3W0RDc4Tn1PL_Br28N_gj4QQCz7C2hZPbp4gK0wRJiWQkDHdyaXiZMNwR_0KeDkd9zRw71vMHDZsQvT2wOgp4fBISSgm-hwEKqW-B5LmNb4xBcf3fhNTfxDWqQlSlt6u7IJZTUoh-gnezNPSUNtusDbXiKJHTv6ct7xSrI4VumTMVzMLZzwOm5h12DW4yrvWq6g6acbbFOW6pzUqR3UuSjNo0q4zlUQqoEFSYHojb3T2Qzl29k2fN-on7kPS3_F2rtvKbW492jkqrnH0psN_iIUDKeX0XzxTqaf5xOO8ztHkHeMeQfQ8Ex1D-GRhaajf_qsPM6uFyOr6Lx-_cdNniIDO3XEkWCKnzRCGfDLgXmUWA-BdanwAYU6tyOLDk_G-qTj2Po7h6HDeuvORgsSkgy_QUqzVMMod8_-Xy811rq_6KlQcvSRz__b-cezXEPbfthDnP36h687H_L-tYsO1CnWZGZh79S26rRmXfaKdcf_syqwD1llXc0Plwa-N5Jo4LXGLVEXUqhsTVDTr3qDSWYpNjMIy0rFeMHJeP6mma5qHk1kKA2TdRrFhNRh-pBvE92f4fsPUv2D8hOm-w_Sw6eJwfPkvst8ub-j_8CAAD___ZxSQ8=)
</blockquote></details>

I wouldn't look too much into the decrease in memory usage - in both cases we have to spill to disk, so the memory usage shouldn't be really a concern (and probably it vary somewhat).
___
*[pkg/server/combined_statement_stats.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZRjRO92l7wzhKRCZr:-MvaarulDy71qH3oWe6e:b-eju19w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L249)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

here's the zipped [`cockroach-data` directories](https://drive.google.com/file/d/1HorwArsiWx4aO-olaYo_iyVV5eRUtM7Y/view?usp=sharing)
</blockquote></details>

Thanks! I'll take a closer look.


<!-- Sent from Reviewable.io -->

2022-02-11 02:33 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/server/combined_statement_stats.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZRjRO92l7wzhKRCZr:-MvacCTl9ZZrMp4eCxfi:b-3vrpm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L249)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Thanks! I'll take a closer look.
</blockquote></details>

BTW does this data directory contain any confidential information? Is the link working only for folks in CRL?


<!-- Sent from Reviewable.io -->

2022-02-11 02:36 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag, @matthewtodd, and @yuzefovich)

___
*[pkg/server/combined_statement_stats.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZRjRO92l7wzhKRCZr:-MvacjfD8e7zx88SpTvI:ba9gc4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L249)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

BTW does this data directory contain any confidential information? Is the link working only for folks in CRL?
</blockquote></details>

No confidential information here. It's just a local database I used myself. Also the link is for CRL only. 


<!-- Sent from Reviewable.io -->

2022-02-11 05:40 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/server/combined_statement_stats.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZOEDp5eYZ9F1GEWvk:-Mvagfa1D1LF2B6G3DMj:bjwqaet) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L248)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I wouldn't look too much into the decrease in memory usage - in both cases we have to spill to disk, so the memory usage shouldn't be really a concern (and probably it vary somewhat).
</blockquote></details>

I made the change to allow the usage of `any_not_null` aggregate function explicitly, but it gives only a minor improvement (10% of the time of the second aggregation which is like 2% of the query latency overall):
[max](https://cockroachdb.github.io/distsqlplan/decode.html#eJykVdtu2zgUfN-vOOCTDbC1KMk3PdEN0iDYOC4ct9hgYQiMdKoIlUiVpNoEQT5rf2C_bEHJSWM59ibpmziHQw5nDqk7Yr4XJCIXx2fHRyv4mssMdaVzaeM8pWC1kEYkNlcy7tZEVcVSlEihFDe9Eq1IhRV9ColOr-JcWtRSFO9L1BnGxgqLJUrbfJme0FrcxiLLem6cG5snpt-H2QX8GrcLG1FWBaZxVQjZTngCwMflYt7ZcHurdinHW3yEi8uL1fEcVqfzY_iqikL9RB1rFGls8xKNFWXV68PJcvH5E3y4fJMbcHY6P12B73meRyiRKsVzUaIh0d-EkTUllVYJGqO0g-6aCafpDYk8SnJZ1dbBa0oSpZFEd8TmtkASkZW4KnCJIkU9cAunaEVeNMs-d2Be6bwU-pZQcqSKupQmApFlGjNhMY2toa86nfM6vhbm-knshBK3ZGv8D1FQeOgBuhWi4xJKLirhRLwjlCxqGwFnlPuUB5SHlA8pH1M-oXxK-YhQ8ucXcIlEwML3U9MCiZIWpZO3qXn__rMpafXTgMsxAjYZ0tD3Wvzq1uJDIQh9mOcfCCXzL0dHYCxWkKhaWujhjR3k0vbdpAmdjoMBm4zoOPQfJyN-253MAm_A_AmhpBQ3UGKp9C2IolCJ89jVNxteCZtcowFV28odnU0ZoaQR_QhtZK_vKWmxTR8YKzIkEbunL-8Vp6CAH7m2tSjAus4Bb8C2uwZvMKmfuBmw1s6uWK8rdb9If6_IX9oM6lwUUEulU9SYbola3z9zmnP1TlUD_7B65o-fl_8Gr73XeD3bXCqlB8G2xG6DTwkls_PL-Hyxis8_n531OOvvQP4uFOxC4S403IWmDprP_urxUVNcLmeX8ezkpMfHj5WJ-1qiTFFHL3q4-aRPgfsUeECBDynwMYXmbDuRBO-HZu_lmLDN5XBl870Ai2UFaW6-QW1EhhEMh3uvj__aSIM3Rhp2It3k-TuxNbYPO4Gw7ageAuHsidfhy_6sfOgCco_oWV7m9vFP1I1nvD8bNh39Xzgh2xPOaLSTDQ1Go73JhK9JZommUtJg59HYd43XlGCaYfsAGVXrBD9plTTbtMNFw2uAFI1tq347OJVNqXl5n5LZ75D9g-Rgi-x1ycFBcniYHB4kDzvk9f0f_wUAAP__fU9C_A==)
[metadata in GROUP BY](https://cockroachdb.github.io/distsqlplan/decode.html#eJysVd1u2zgTvf-eYsArG2Bj_flHuqIbpEHwxXHhuMUGC0NgpKkiVCJVkmodBHmsfYF9sgUlN7Hl2Ju0eyeemUOemTOkHoj-VpCIXJ9dnp0u4UsuMlSVyoWJ85SCUVxonphcirgb41UVC14ihRINT7nhFBKV3sa5MKgEL05KVBnG2nCDJQrTfOkeV4rfxzzLenada5Mnut-H6TU8rymUfN3TvKwKTOOq4KJN2ALgw2I-6xy4e1S7leXNP8D1zfXybAbLi9kZfJFFIX-gihXyNDZ5idrwsur14Xwx__QR3t_8ZiPg8mJ2sQTPcRyHUCJkile8RE2iP4lLVpRUSiaotVQWemgSLtI1iRxKclHVxsIrShKpkEQPxOSmQBKRJb8tcIE8RTWwG6doeF40275UOqtUXnJ1Tyg5lUVdCh0BzzKFGTeYxkbTN9Vpux7fcX23VTKhxG7ZWvCdF9vDsG2n5RJKrituRbwjlMxrEwFzKfMo8ykLKBtSNqZsQllI2YhQ8v_PYL2JwA1OhroFEikMCitvE3P-_msTUvKHButoBO5kSAPPafHbe4M_A37gwSx_TyiZfT49BW2wgkTWwkAP12aQC9O3SRMaBuOBOxnRYBQ-JSN-3U92fW_gejap5GsosZTqHnhRyMT22MY3B95yk9yhBlmbypbuhi6hpBH9BG1krx4pabHNHGjDMySR-0hfPytWQQHfc2VqXoCxkwPOwN2dGlxjUm910w_bdnbFOl2ph0V6B0U-a9Oocl5ALaRKUWG6I2r1-EI1V_KdrAbecfWh87L6X2i185ZWTzd3SqqBv6uwO992TqZXN_HVfBlffbq87DG3vwd5-5C_DwX70HAfCi00m_7RY6MmuFhMb-Lp-XmPjZ8iE_u1QJGiil71grNJnwLzKDCfAhtSYGMKTW1dR1zvJNQH78bE3dwNG9bfCjBYVpDm-ivUmmcYwXB48PZ4b7XU_0VLg46lz37-1849m-Pu2vbTHOZu9T143e-WDa1Z9j29zMvcPP2UulaND_vkhuN_MypwDxg1Gu35RP1ReNCl4C0uLVBXUmjsvB-HrvSKEkwzbN8iLWuV4Eclk-aYdjlveA2QojZt1GsXF6IJNY_wNtn9HbJ3lOzvkJ0u2T9KDo6Tg6PkYYe8evzfPwEAAP__k1FIYw==)
[any_not_null](https://cockroachdb.github.io/distsqlplan/decode.html#eJysVdtu2zgQfd-vGPDJBqaxKMk3PckN0iDYOC4ct9hgYQiMNHWESqRKUm2CIJ-1P7BftqDkXGzH2SS7b-I5POThnCF1y8yPgkXs_Oj06HAB33K5Il3pXNokzxCsFtKI1OZKJtucqKpEipIQhLxJpLKJrIuiU5IVmbCii5Dq7DLJpSUtRXFQkl5RYqywVJK0zZfpCK3FTSJWq44b58bmqel2YXIOj2OEUlx3jCirgrKkKoRsJzwB4NN8Nt3acHOrdimnm32C84vzxdEUFifTI_imikL9Ip1oElli85KMFWXV6cLxfPblM3y8eFdZ4PRkerIA3_M8jyGTKqMzUZJh0Z-MsyWySquUjFHaQbfNhJPsmkUeslxWtXXwElmqNLHoltncFsQithCXBc1JZKR7buGMrMiLZtnnDhxXOi-FvmHIDlVRl9JEIFYrTSthKUuswTedztU6uRLm6kn-DJlbsi38T1Eg3PcAboTotAzZeSWciQ8M2ay2EcQcYx_jAOMQ4z7GQ4xHGI8xHjBkv38Fl0gEPDwYmhZIlbQknb015_3915rS6pcBl2MEfNTH0Pda_PLG0j0RhD5M848M2fTr4SEYSxWkqpYWOnRte7m0XTdphONx0OOjAfaH3sNkou-7k3ng9bg_YshKcQ0llUrfgCgKlboaO3694aWw6RUZULWt3NH5mDNkjekHaG17eYesxdZ9YKxYEYv4Hb6-V5yDAn7m2taiAOs6B7we3-wauqa0flJNf9iWc9ust211v0l_r8lHb4Z0LgqopdIZaco2TC3vnjnNmfqgqp7_snvOx8_bf0etvbfUerK-VEr3gk2L2w0-ZsgmZxfJ2WyRnH05Pe3EvLsD-btQsAuFu1B_Fxo7aDr5oxMPGnI-n1wkk-PjTjx8YEbua04yIx296uGOR12E2EeIA4S4jxAPEZqz7UQSHHCz93KM-PpyONr8KMBSWUGWm-9QG7GiCPr9vdfHf2ukwTsjDbciXef5f8f2mAzfzOw-mZg_KXr4ul9s3HdJudf0NC9z-_BL2s5pcBDuj4mPB_-WU8j35DQY7MSEwWCwN6TwLSHNyVRKGtp6P_bd6CUyylbUvkVG1Tqlz1qlzTbtcNboGiAjY1vWbwcnsqGaR_ipmP8Xsf-iONgQe9vi4EVx-LI4fFHc3xIv7377JwAA__9dhUoW)

Given these observations, I think it's not worth making `any_not_null` non-internal. I'd probably choose the option of putting `metadata` in GROUP BY clause since overall it seems cleaner.
___
*[pkg/server/combined_statement_stats.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZRjRO92l7wzhKRCZr:-MvanFVL4yMvRQJjCWTV:baolfgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L249)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

No confidential information here. It's just a local database I used myself. Also the link is for CRL only. 
</blockquote></details>

Here the increase in memory usage is actually due to a bug - we are incorrectly limiting the size of the output batches in the hash aggregation, and I have a WIP fix in #76421. With that fix applied I get [this](https://cockroachdb.github.io/distsqlplan/decode.html#eJykVdtu2zgQfd-vGPDJAdhY1MWO9UQ36AbB-lI4abHBwhAYaVYRKlEqSXUdBPms_YH9sgUlJ7XlyE3aN_EMD3lmzgz1QPTXnITk6sPsw_k1_J3JFFWlMmmiLKFglJBaxCYrZdSNiaqKpCiQQiE2gwKNSIQRJzC9gqcFhVglt1EmDSop8tMCVYqRNsJggdI0X3oglBL3kUjTgV1n2mSxPmnO-b5uL9GiqHJMoioXst2wA8Dvq-W8c-H-Ve1RcLFafvoI729-KluYXc4vr8F1HMchlMgywYUoUJPwL8LImpJKlTFqXSoLPTQbLpMNCR1KMlnVxsJrSuJSIQkfiMlMjiQk1-I2xxWKBNXQHpygEVneHPtSErxSWSHUPaHkvMzrQuoQRJoqTIXBJDKavik7W7_oTui7HVsJJfbItpjfRE53bN01xnIJJVeVsCLeEUqWtQmBM8pdyj3KfcoDyseUn1E-oXxEKPnjM5iswBBYcDrWLRCX0qC08rYx579_tyFV_qNBoUhCYGcBDUZ-i9_eG3wKeL4H8-w9oWT--fwctMEK4rKWBga4McNMmpMQvLFH2Wg0ZGcjOvLGz5sRvxxudj1n6HrWjEJsoMCiVPcg8ryMbY1DYO72wlth4jvUUNamsqmzCSOUNKKfoa3s9SMlLbbtA21EiiRkj_T1vWIV5PAtU6YWORjbOeAM2X7X4AbjeqeabsDaenbVul2tXq9Kt1fld3EaVSZyqGWpElSY7KlaP76QzqJ8V1ZD97h85vbIZxPv5WKPe9Nw3lLs6XaqSjX09iV2O3xCKJkubqLF8jpafJrNBpydHEDuIeQdQv4hFBxCEwvNp38O-KgJrlbTm2h6cTHg4-fImf1aoUxQha96jfnZCQXuUuAeBR5Q4GMKTW6Hlpwy3Tsd48l2OmxYf83BYFFBkukvUGuRYghB0Ds_Bz35o_nxftJSv2Pp1s9fsa0pe9AxhO1b9WQIZzu19l_3u-SBNci-orOsyMzzr6hrz-jU73dn4v_IHZ_1ueMfmEO9sdtrjf8Wa1aoq1Jq7LwafXO8pgSTFNsXSJe1ivGjKuPmmna5bHgNkKA2bdRtF5eyCTVv7y6Z_QrZPUr29shOl-wdJfvHyf5RctAhrx9_-z8AAP__tUg4wg==).

I'm assuming this PR will not be backported? If not, then I think we should be good with the change to this query - the vectorized engine will spill to disk if necessary and (mostly) correctly accounts for the in-memory state, so we should not blow up.


<!-- Sent from Reviewable.io -->

2022-02-11 14:25 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZNxOZ2gP43_8WI8vH):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nits: "commits" -> "commit", "aggreagted" -> "aggregated"
</blockquote></details>

Done
___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZNi3V3BUox0CppYYw):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: Maybe spell out "timestamps" here (for docs writers / future readers) instead of abbreviating "ts"?
</blockquote></details>

Done
___
*[pkg/server/combined_statement_stats.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZOyhzCj7dJEIMCOMh:-MvZim8_0r1IlTrNAl-C:b-trofze) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L134)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I'm wondering if we want `max` or `min` here -- do we want to show the latest or the earliest timestamp?
</blockquote></details>

this one really doesn't matter, we won't use it anymore, but I wanted to still return something just in case, so I went with the latest since seeing the latest are priority.
___
*[pkg/server/combined_statement_stats.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZOEDp5eYZ9F1GEWvk:-Mvd9jp76GFELMtP1k3P:b30aizn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L248)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I made the change to allow the usage of `any_not_null` aggregate function explicitly, but it gives only a minor improvement (10% of the time of the second aggregation which is like 2% of the query latency overall):
[max](https://cockroachdb.github.io/distsqlplan/decode.html#eJykVdtu2zgUfN-vOOCTDbC1KMk3PdEN0iDYOC4ct9hgYQiMdKoIlUiVpNoEQT5rf2C_bEHJSWM59ibpmziHQw5nDqk7Yr4XJCIXx2fHRyv4mssMdaVzaeM8pWC1kEYkNlcy7tZEVcVSlEihFDe9Eq1IhRV9ColOr-JcWtRSFO9L1BnGxgqLJUrbfJme0FrcxiLLem6cG5snpt-H2QX8GrcLG1FWBaZxVQjZTngCwMflYt7ZcHurdinHW3yEi8uL1fEcVqfzY_iqikL9RB1rFGls8xKNFWXV68PJcvH5E3y4fJMbcHY6P12B73meRyiRKsVzUaIh0d-EkTUllVYJGqO0g-6aCafpDYk8SnJZ1dbBa0oSpZFEd8TmtkASkZW4KnCJIkU9cAunaEVeNMs-d2Be6bwU-pZQcqSKupQmApFlGjNhMY2toa86nfM6vhbm-knshBK3ZGv8D1FQeOgBuhWi4xJKLirhRLwjlCxqGwFnlPuUB5SHlA8pH1M-oXxK-YhQ8ucXcIlEwML3U9MCiZIWpZO3qXn__rMpafXTgMsxAjYZ0tD3Wvzq1uJDIQh9mOcfCCXzL0dHYCxWkKhaWujhjR3k0vbdpAmdjoMBm4zoOPQfJyN-253MAm_A_AmhpBQ3UGKp9C2IolCJ89jVNxteCZtcowFV28odnU0ZoaQR_QhtZK_vKWmxTR8YKzIkEbunL-8Vp6CAH7m2tSjAus4Bb8C2uwZvMKmfuBmw1s6uWK8rdb9If6_IX9oM6lwUUEulU9SYbola3z9zmnP1TlUD_7B65o-fl_8Gr73XeD3bXCqlB8G2xG6DTwkls_PL-Hyxis8_n531OOvvQP4uFOxC4S403IWmDprP_urxUVNcLmeX8ezkpMfHj5WJ-1qiTFFHL3q4-aRPgfsUeECBDynwMYXmbDuRBO-HZu_lmLDN5XBl870Ai2UFaW6-QW1EhhEMh3uvj__aSIM3Rhp2It3k-TuxNbYPO4Gw7ageAuHsidfhy_6sfOgCco_oWV7m9vFP1I1nvD8bNh39Xzgh2xPOaLSTDQ1Go73JhK9JZommUtJg59HYd43XlGCaYfsAGVXrBD9plTTbtMNFw2uAFI1tq347OJVNqXl5n5LZ75D9g-Rgi-x1ycFBcniYHB4kDzvk9f0f_wUAAP__fU9C_A==)
[metadata in GROUP BY](https://cockroachdb.github.io/distsqlplan/decode.html#eJysVd1u2zgTvf-eYsArG2Bj_flHuqIbpEHwxXHhuMUGC0NgpKkiVCJVkmodBHmsfYF9sgUlN7Hl2Ju0eyeemUOemTOkHoj-VpCIXJ9dnp0u4UsuMlSVyoWJ85SCUVxonphcirgb41UVC14ihRINT7nhFBKV3sa5MKgEL05KVBnG2nCDJQrTfOkeV4rfxzzLenada5Mnut-H6TU8rymUfN3TvKwKTOOq4KJN2ALgw2I-6xy4e1S7leXNP8D1zfXybAbLi9kZfJFFIX-gihXyNDZ5idrwsur14Xwx__QR3t_8ZiPg8mJ2sQTPcRyHUCJkile8RE2iP4lLVpRUSiaotVQWemgSLtI1iRxKclHVxsIrShKpkEQPxOSmQBKRJb8tcIE8RTWwG6doeF40275UOqtUXnJ1Tyg5lUVdCh0BzzKFGTeYxkbTN9Vpux7fcX23VTKhxG7ZWvCdF9vDsG2n5RJKrituRbwjlMxrEwFzKfMo8ykLKBtSNqZsQllI2YhQ8v_PYL2JwA1OhroFEikMCitvE3P-_msTUvKHButoBO5kSAPPafHbe4M_A37gwSx_TyiZfT49BW2wgkTWwkAP12aQC9O3SRMaBuOBOxnRYBQ-JSN-3U92fW_gejap5GsosZTqHnhRyMT22MY3B95yk9yhBlmbypbuhi6hpBH9BG1krx4pabHNHGjDMySR-0hfPytWQQHfc2VqXoCxkwPOwN2dGlxjUm910w_bdnbFOl2ph0V6B0U-a9Oocl5ALaRKUWG6I2r1-EI1V_KdrAbecfWh87L6X2i185ZWTzd3SqqBv6uwO992TqZXN_HVfBlffbq87DG3vwd5-5C_DwX70HAfCi00m_7RY6MmuFhMb-Lp-XmPjZ8iE_u1QJGiil71grNJnwLzKDCfAhtSYGMKTW1dR1zvJNQH78bE3dwNG9bfCjBYVpDm-ivUmmcYwXB48PZ4b7XU_0VLg46lz37-1849m-Pu2vbTHOZu9T143e-WDa1Z9j29zMvcPP2UulaND_vkhuN_MypwDxg1Gu35RP1ReNCl4C0uLVBXUmjsvB-HrvSKEkwzbN8iLWuV4Eclk-aYdjlveA2QojZt1GsXF6IJNY_wNtn9HbJ3lOzvkJ0u2T9KDo6Tg6PkYYe8evzfPwEAAP__k1FIYw==)
[any_not_null](https://cockroachdb.github.io/distsqlplan/decode.html#eJysVdtu2zgQfd-vGPDJBqaxKMk3PckN0iDYOC4ct9hgYQiMNHWESqRKUm2CIJ-1P7BftqDkXGzH2SS7b-I5POThnCF1y8yPgkXs_Oj06HAB33K5Il3pXNokzxCsFtKI1OZKJtucqKpEipIQhLxJpLKJrIuiU5IVmbCii5Dq7DLJpSUtRXFQkl5RYqywVJK0zZfpCK3FTSJWq44b58bmqel2YXIOj2OEUlx3jCirgrKkKoRsJzwB4NN8Nt3acHOrdimnm32C84vzxdEUFifTI_imikL9Ip1oElli85KMFWXV6cLxfPblM3y8eFdZ4PRkerIA3_M8jyGTKqMzUZJh0Z-MsyWySquUjFHaQbfNhJPsmkUeslxWtXXwElmqNLHoltncFsQithCXBc1JZKR7buGMrMiLZtnnDhxXOi-FvmHIDlVRl9JEIFYrTSthKUuswTedztU6uRLm6kn-DJlbsi38T1Eg3PcAboTotAzZeSWciQ8M2ay2EcQcYx_jAOMQ4z7GQ4xHGI8xHjBkv38Fl0gEPDwYmhZIlbQknb015_3915rS6pcBl2MEfNTH0Pda_PLG0j0RhD5M848M2fTr4SEYSxWkqpYWOnRte7m0XTdphONx0OOjAfaH3sNkou-7k3ng9bg_YshKcQ0llUrfgCgKlboaO3694aWw6RUZULWt3NH5mDNkjekHaG17eYesxdZ9YKxYEYv4Hb6-V5yDAn7m2taiAOs6B7we3-wauqa0flJNf9iWc9ust211v0l_r8lHb4Z0LgqopdIZaco2TC3vnjnNmfqgqp7_snvOx8_bf0etvbfUerK-VEr3gk2L2w0-ZsgmZxfJ2WyRnH05Pe3EvLsD-btQsAuFu1B_Fxo7aDr5oxMPGnI-n1wkk-PjTjx8YEbua04yIx296uGOR12E2EeIA4S4jxAPEZqz7UQSHHCz93KM-PpyONr8KMBSWUGWm-9QG7GiCPr9vdfHf2ukwTsjDbciXef5f8f2mAzfzOw-mZg_KXr4ul9s3HdJudf0NC9z-_BL2s5pcBDuj4mPB_-WU8j35DQY7MSEwWCwN6TwLSHNyVRKGtp6P_bd6CUyylbUvkVG1Tqlz1qlzTbtcNboGiAjY1vWbwcnsqGaR_ipmP8Xsf-iONgQe9vi4EVx-LI4fFHc3xIv7377JwAA__9dhUoW)

Given these observations, I think it's not worth making `any_not_null` non-internal. I'd probably choose the option of putting `metadata` in GROUP BY clause since overall it seems cleaner.
</blockquote></details>

Thank you for the input @yuzefovich and @azhng . I made the change to move the `metadata` to the `GROUP BY` clause.
___
*[pkg/server/combined_statement_stats.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZRjRO92l7wzhKRCZr:-Mvd9TZO7GEW3QY1IbfB:b-5vlv6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L249)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Here the increase in memory usage is actually due to a bug - we are incorrectly limiting the size of the output batches in the hash aggregation, and I have a WIP fix in #76421. With that fix applied I get [this](https://cockroachdb.github.io/distsqlplan/decode.html#eJykVdtu2zgQfd-vGPDJAdhY1MWO9UQ36AbB-lI4abHBwhAYaVYRKlEqSXUdBPms_YH9sgUlJ7XlyE3aN_EMD3lmzgz1QPTXnITk6sPsw_k1_J3JFFWlMmmiLKFglJBaxCYrZdSNiaqKpCiQQiE2gwKNSIQRJzC9gqcFhVglt1EmDSop8tMCVYqRNsJggdI0X3oglBL3kUjTgV1n2mSxPmnO-b5uL9GiqHJMoioXst2wA8Dvq-W8c-H-Ve1RcLFafvoI729-KluYXc4vr8F1HMchlMgywYUoUJPwL8LImpJKlTFqXSoLPTQbLpMNCR1KMlnVxsJrSuJSIQkfiMlMjiQk1-I2xxWKBNXQHpygEVneHPtSErxSWSHUPaHkvMzrQuoQRJoqTIXBJDKavik7W7_oTui7HVsJJfbItpjfRE53bN01xnIJJVeVsCLeEUqWtQmBM8pdyj3KfcoDyseUn1E-oXxEKPnjM5iswBBYcDrWLRCX0qC08rYx579_tyFV_qNBoUhCYGcBDUZ-i9_eG3wKeL4H8-w9oWT--fwctMEK4rKWBga4McNMmpMQvLFH2Wg0ZGcjOvLGz5sRvxxudj1n6HrWjEJsoMCiVPcg8ryMbY1DYO72wlth4jvUUNamsqmzCSOUNKKfoa3s9SMlLbbtA21EiiRkj_T1vWIV5PAtU6YWORjbOeAM2X7X4AbjeqeabsDaenbVul2tXq9Kt1fld3EaVSZyqGWpElSY7KlaP76QzqJ8V1ZD97h85vbIZxPv5WKPe9Nw3lLs6XaqSjX09iV2O3xCKJkubqLF8jpafJrNBpydHEDuIeQdQv4hFBxCEwvNp38O-KgJrlbTm2h6cTHg4-fImf1aoUxQha96jfnZCQXuUuAeBR5Q4GMKTW6Hlpwy3Tsd48l2OmxYf83BYFFBkukvUGuRYghB0Ds_Bz35o_nxftJSv2Pp1s9fsa0pe9AxhO1b9WQIZzu19l_3u-SBNci-orOsyMzzr6hrz-jU73dn4v_IHZ_1ueMfmEO9sdtrjf8Wa1aoq1Jq7LwafXO8pgSTFNsXSJe1ivGjKuPmmna5bHgNkKA2bdRtF5eyCTVv7 [...]

2022-02-12 03:16 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[pkg/server/combined_statement_stats.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-MvZRjRO92l7wzhKRCZr:-Mvfv3Dz1-y8UpwoY_qJ:brsema0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42a90bd77c4f94686b5a5a11b01235888a18c37/pkg/server/combined_statement_stats.go#L249)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

 Indeed this won't be backported. I can keep an eye when you land your PR if indeed we had improvements here. Thank you for taking a look into it!
</blockquote></details>

That bug is quite tricky to fix, so I filed #76464 to track it (I'll put my WIP to fix it aside for now). However, even with the bug present I think it's safe to proceed with this change. The behavior of the bug is such that we might create vectorized batches of sizes larger than we want; however, crucially we're still correctly accounting for that large size, so we should not OOM.


<!-- Sent from Reviewable.io -->

2022-02-14 16:25 UTC, Azhng approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-:-Mvt2GGm5bgRbbyWVh_U:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/server/combined_statement_stats.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-Mvt13JO8cR-v9_o93vF:-Mvt13JO8cR-v9_o93vG:bryen1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/71ef6b8fcb0513ed462c1233ed2be3cbea2190cf/pkg/server/combined_statement_stats.go#L254)):*
> ```Go
> 			FROM crdb_internal.transaction_statistics %s
> 			GROUP BY
> 				app_name,
> ```

Oh boy did we forget to aggregate by app_name this whole time :man_facepalming: 


<!-- Sent from Reviewable.io -->

2022-02-14 16:48 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76301)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/server/combined_statement_stats.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76301#-Mvt13JO8cR-v9_o93vF:-Mvt7MuZ2hFtUyu7JHqn:b-p9g4y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/71ef6b8fcb0513ed462c1233ed2be3cbea2190cf/pkg/server/combined_statement_stats.go#L254)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Oh boy did we forget to aggregate by app_name this whole time :man_facepalming: 
</blockquote></details>

no, the interline view aggregates by app_name, I'm just continuing the `group by` here. This function didn't use the `group by`, that's probably why you got that impression here :)


<!-- Sent from Reviewable.io -->

2022-02-14 18:00 UTC, merged