pkg/storage: support suffix replacement on MVCC interval collector
cockroachdb/cockroach pull request #76327
Opened 2022-02-09 19:50 UTC by nicktrav

The `SuffixReplaceableBlockCollector` interface was added to to Pebble
in cockroachdb/pebble#X, which allows a block property collector to
indicate that it supports being updated during suffix replacement.

The existing `pebbleDataBlockMVCCTimeIntervalCollector` block property
collector does not currently support suffix replacement. However, given
a new suffix, the interval for a block can be trivially calculated.

Implement the `SuffixReplaceableBlockCollector` interface.

Release note: None

2022-02-09 19:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76327)
<!-- Reviewable:end -->

2022-02-10 20:44 UTC, sumeerbhola requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76327)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jbowens, and @nicktrav)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76327#-Mv_KY9d1p4MVZRyI0T1):*
... added to Pebble ...
___
*[pkg/storage/pebble.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76327#-Mv_MBozBscS52ME721E:-Mv_MBozBscS52ME721F:bv09ifs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8003e66a2f63d54a41c901accdb0d173b3564eda/pkg/storage/pebble.go#L386)):*
> ```Go
> // add collects the given slice in the collector. The slice may be an entire
> // encoded MVCC key, or the suffix of an encoded key. In the case of the latter,
> // the slice must include the sentinel byte.
> ```

The definition of the suffix does not include the sentinel byte as described in https://github.com/cockroachdb/cockroach/blob/45d1c9e64e2524ee8e10fed7d593b43375df1ec5/pkg/storage/engine_key.go#L61-L65
Which is why we needed the code in https://github.com/cockroachdb/cockroach/blob/45d1c9e64e2524ee8e10fed7d593b43375df1ec5/pkg/storage/pebble.go#L102-L104


<!-- Sent from Reviewable.io -->

2022-02-10 23:53 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76327)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jbowens, and @sumeerbhola)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76327#-Mv_KY9d1p4MVZRyI0T1):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... added to Pebble ...
</blockquote></details>

Done.
___
*[pkg/storage/pebble.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76327#-Mv_MBozBscS52ME721E:-Mv_ivYr9TVg_2yyqJZC:bi9ej75) ([raw file](https://github.com/cockroachdb/cockroach/blob/8003e66a2f63d54a41c901accdb0d173b3564eda/pkg/storage/pebble.go#L386)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The definition of the suffix does not include the sentinel byte as described in https://github.com/cockroachdb/cockroach/blob/45d1c9e64e2524ee8e10fed7d593b43375df1ec5/pkg/storage/engine_key.go#L61-L65
Which is why we needed the code in https://github.com/cockroachdb/cockroach/blob/45d1c9e64e2524ee8e10fed7d593b43375df1ec5/pkg/storage/pebble.go#L102-L104
</blockquote></details>

Ah, missed that. I was using "suffix" in a more general "trailing bytes" sense. I didn't realize "suffix" has a precise definition in this context (MVCC timestamp + length byte; no sentinel).

If I'm understanding correctly now, this method should only receive _either_:
- a full `EngineKey` (which will include the sentinel) when called from `Add`; or
- a bare suffix (no sentinel), when called from `UpdateKeySuffixes`

I added some error handling and some additional test cases.


<!-- Sent from Reviewable.io -->

2022-02-11 21:51 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76327#-:-MvelIeD6vyEYheeTCfb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @jbowens, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-02-11 22:07 UTC, nicktrav commented
TFTR!

bors r=sumeerbhola

2022-02-12 03:38 UTC, merged