docs: Up-replicating learners with snapshots
cockroachdb/cockroach pull request #76408
Opened 2022-02-10 23:49 UTC by amygao9

This tech-note describes the process of up-replicating new learners, from the change replicas method to sending the raft snapshot. It's meant to give a more brief overview of the process instead of diving deep into one topic. 

Release note: None

2022-02-10 23:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76408)
<!-- Reviewable:end -->

2022-02-11 00:59 UTC, aayushshah15 reviewed
Looks mostly good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-:-MvaHVtL0PLs7FuaCs3I:b-f5ojy3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @amygao9)

___
*[docs/tech-notes/change-replicas.md, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaAtdh2PxrVv9-1eh6:-MvaAtdh2PxrVv9-1eh7:bbgsv9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L4)):*
> ```Markdown
> 
> This tech note briefly explains the end-to-end process of up-replicating a range, starting from the replicateQueue to
> sending Raft snapshots. This is meant to serve as a high level overview of the code paths taken, and more detailed
> ```

In the code, we usually refer to the snapshots sent by the raft snapshot queue as `Raft snapshots` and the snapshots sent to learners by the `replicateQueue` as `Learner snapshots`. 
___
*[docs/tech-notes/change-replicas.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaB9NDDHbCfDK-U-l8:-MvaB9NDDHbCfDK-U-l9:bw6tbk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L10)):*
> ```Markdown
> 
> Raft snapshots are necessary when a follower replica is unable to catch up using the existing Raft logs of the leader.
> Such a scenario occurs when a configuration change or rebalancing operation requires a new follower to be added. For
> ```

I think we're conflating the two cases we need snapshots here. The first sentence is correct but the second one isn't. I'd rephrase this as something like 
```
Such a scenario occurs when we add a new replica (due to a rebalancing operation) or when an existing replica falls too far behind the rest of the Raft group such that we've truncated the Raft log above it. 
```
___
*[docs/tech-notes/change-replicas.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaBnte52KQhVsvW3V9:-MvaBnte52KQhVsvW3VA:b-c2sg3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L14)):*
> ```Markdown
> clean slate. To up-replicate this replica, we need to send it an initial snapshot of the full range data.
> 
> In this note, we will focus on the scenario where a preemptive snapshot is needed for the up-replication and rebalancing
> ```

Heh, `preemptive snapshots` used to exist before learner replicas were a thing, so I'd refrain from using that term here to avoid confusion. I think I'd make it clear that this tech note focusses on learner snapshots but that there's nothing different about `Raft snapshots` in how they're generated.
___
*[docs/tech-notes/change-replicas.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaCEFo7f6qjYrOw-v-:-MvaCEFo7f6qjYrOw-v0:b-lcpodr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L20)):*
> ```Markdown
> 
> As a brief overview, the replicateQueue manages a queue of replicas and is responsible for processing replicas for
> rebalancing. For each replica, it decides whether any placement changes are needed and subsequently invokes the
> ```

The allocator decides whether any changes are needed, and the `replicateQueue` executes them.
___
*[docs/tech-notes/change-replicas.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaCeGJ-hC4dy3qQ4yl:-MvaCeGJ-hC4dy3qQ4ym:b-7fobye) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L27)):*
> ```Markdown
> ## ChangeReplicas
> 
> The ChangeReplicas method is mainly responsible for atomically changing replicas of a range. These changes include
> ```

nit: I'd make it clear that we're talking about the `AdminChangeReplicas` API that is exposed by KV. 
___
*[docs/tech-notes/change-replicas.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaCm1E0s2D7j6r9lgv:-MvaCm1E0s2D7j6r9lgw:b-x32mo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L28)):*
> ```Markdown
> 
> The ChangeReplicas method is mainly responsible for atomically changing replicas of a range. These changes include
> replica promotions, voter/non-voter swaps, additions and removals. The change is performed in a distributed transaction
> ```

non-voter promotions*
___
*[docs/tech-notes/change-replicas.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaCsNc0SzF0IoCEh7c:-MvaCsNc0SzF0IoCEh7d:b-qr2d0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L32)):*
> ```Markdown
> purposes of this note, we will focus on up-replication and the process of sending Raft learner snapshots.
> 
> During up-replication, ChangeReplicas runs a transaction that adds all new replicas as learner replicas to the range.
> ```

Note that we add and then promote these learners one by one. Meaning that if there are multiple replication changes to be made, the `ChangeReplicas` API is called one by one for each change by the `replicateQueue`. 
___
*[docs/tech-notes/change-replicas.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaDEgeAsgs9t5HHRmQ:-MvaDEgeAsgs9t5HHRmR:bi2uezx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L36)):*
> ```Markdown
> remain highly available during the replication process.
> 
> Once these learners are initialized in the range, they are synchronously sent a Raft snapshot from the leader to
> ```

`Learner` snapshot here and elsewhere. 
___
*[docs/tech-notes/change-replicas.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaDM_PBMabdK3GaHd3:-MvaDM_PBMabdK3GaHd4:b-37dbtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L39)):*
> ```Markdown
> up-replicate. There is some nuance here as Raft snapshots are typically automatically sent by the existing Raft snapshot
> queue. However, we are synchronously sending a snapshot here in the replicateQueue to quickly catch up learners. To
> prevent a race with the raftSnapshotQueue, we lock learner snapshots on the current node while processing the change.
> ```

The raft snapshot queue and the replicate queue can be sending two snapshots concurrently at the same time. What we do do is we place a best effort lock on log truncation to make it such that we won't truncate the raft log while the snapshot is in progress. It is best effort because its a local in-memory lock, so in case the leaseholder changes, the new leaseholder could still decide to truncate.
___
*[docs/tech-notes/change-replicas.md, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaFARZ1Yqh8UMNu2O8:-MvaFARZ1Yqh8UMNu2O9:b-nypn3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L50)):*
> ```Markdown
> A snapshot is a bulk transfer of all replicated data in a range and everything the replica needs to be a member of a
> Raft group. It consists of a consistent view of the state of some replica of a range as of an applied index. The
> GetSnapshot method gets a storage engine snapshot of the replica data at a moment in time and creates an iterator from
> ```

Let's talk about why, and why that's not important for correctness today (because we never actually construct more than one iterator from it). 
___
*[docs/tech-notes/change-replicas.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaGM7O9rYX5ICZHvyY:-MvaGM7O9rYX5ICZHvyZ: [...]

2022-02-11 22:13 UTC, amygao9 reviewed
Thanks for the review! Changed some parts as per your comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-:-Mvepted1EWefRVF37Hf:b8sjan5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[docs/tech-notes/change-replicas.md, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaAtdh2PxrVv9-1eh6:-MvdmnKu4ueHhhzV7KNd:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L4)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

In the code, we usually refer to the snapshots sent by the raft snapshot queue as `Raft snapshots` and the snapshots sent to learners by the `replicateQueue` as `Learner snapshots`. 
</blockquote></details>

Done. 
___
*[docs/tech-notes/change-replicas.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaB9NDDHbCfDK-U-l8:-MvdolpM-91KdTR6cmGU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L10)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I think we're conflating the two cases we need snapshots here. The first sentence is correct but the second one isn't. I'd rephrase this as something like 
```
Such a scenario occurs when we add a new replica (due to a rebalancing operation) or when an existing replica falls too far behind the rest of the Raft group such that we've truncated the Raft log above it. 
```
</blockquote></details>

Done.
___
*[docs/tech-notes/change-replicas.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaBnte52KQhVsvW3V9:-MveCE_x0yUzIEotFXih:b-b2w2aj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L14)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Heh, `preemptive snapshots` used to exist before learner replicas were a thing, so I'd refrain from using that term here to avoid confusion. I think I'd make it clear that this tech note focusses on learner snapshots but that there's nothing different about `Raft snapshots` in how they're generated.
</blockquote></details>

Done. Added some clarification on the differences between the two snapshots.
___
*[docs/tech-notes/change-replicas.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaCEFo7f6qjYrOw-v-:-MveEDYj7qDzUdGerU_c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L20)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

The allocator decides whether any changes are needed, and the `replicateQueue` executes them.
</blockquote></details>

Done.
___
*[docs/tech-notes/change-replicas.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaCm1E0s2D7j6r9lgv:-MveEKUu5Q4LkMrDds7j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L28)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

non-voter promotions*
</blockquote></details>

Done.
___
*[docs/tech-notes/change-replicas.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaCsNc0SzF0IoCEh7c:-MveGpBdDRfpD74C8kkR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L32)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Note that we add and then promote these learners one by one. Meaning that if there are multiple replication changes to be made, the `ChangeReplicas` API is called one by one for each change by the `replicateQueue`. 
</blockquote></details>

Done.
___
*[docs/tech-notes/change-replicas.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaDEgeAsgs9t5HHRmQ:-MveGtN573KiC4HElZMm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L36)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

`Learner` snapshot here and elsewhere. 
</blockquote></details>

Done.
___
*[docs/tech-notes/change-replicas.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaDM_PBMabdK3GaHd3:-MveSgby7TjpW9-ggQwC:b5cfpyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L39)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

The raft snapshot queue and the replicate queue can be sending two snapshots concurrently at the same time. What we do do is we place a best effort lock on log truncation to make it such that we won't truncate the raft log while the snapshot is in progress. It is best effort because its a local in-memory lock, so in case the leaseholder changes, the new leaseholder could still decide to truncate.
</blockquote></details>

Done. Added that both snapshots and log truncations are locked after our discussion.
___
*[docs/tech-notes/change-replicas.md, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaFARZ1Yqh8UMNu2O8:-MveTCmr1-noZJG5H5Ww:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L50)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Let's talk about why, and why that's not important for correctness today (because we never actually construct more than one iterator from it). 
</blockquote></details>

Done.
___
*[docs/tech-notes/change-replicas.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaGM7O9rYX5ICZHvyY:-MvegUDb9kVoMtt6ObEn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L57)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Can we briefly mention the condition(s) based on which the receiver actually accepts or rejects the sender's snapshot request?
</blockquote></details>

Done.
___
*[docs/tech-notes/change-replicas.md, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaFzFEBfye7DKdjhhR:-MvenzB_D0RRLpBUFGvC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L58)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Let's emphasize the fact that we're always only reading chunks of size `kv.snapshot_sender.batch_size` into memory. This is so that we're never actually holding any significant amount of data in memory. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-11 22:16 UTC, amygao9 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76408)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[docs/tech-notes/change-replicas.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaGM7O9rYX5ICZHvyY:-MveqjYd4Gr9VuMJtrvA:b608rxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L57)):*
<details><summary><i>Previously, amygao9 (Amy Gao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Added the conditions based on my understanding of the code,  please let me know if anything is off here.


<!-- Sent from Reviewable.io -->

2022-02-16 19:53 UTC, shralex commented
Nice writeup, thanks Amy! It was already useful as I was investigating a potential issue.

2022-02-17 17:11 UTC, aayushshah15 requested changes
It mostly LGTM except for the part talking about when snapshots might get rejected by the receiver. +1 to what Alex said, it's a really nice write-up!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-:-Mw7eMn7DyVqRItal6RN:b-bpvkgo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @amygao9, @nvanbenschoten, and @tbg)

___
*[docs/tech-notes/change-replicas.md, line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvjG6yo60Z0G2T34Lk4:-MvjG6yo60Z0G2T34Lk5:bbjh9xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a13a3659a9f979305aad99fd6ab252cf23ca75/docs/tech-notes/change-replicas.md#L14)):*
> ```Markdown
> distinction that `Learner snapshots` are sent during rebalancing operations by the `replicateQueue` and `Raft snapshots`
> are sent by the `raftSnapshotQueue` when a replica falls behind. However, there is no difference in the way the snapshots are sent,
> generated or applied. For example, in the case where the replication factor is increased, the Raft Group would need to
> ```

nit: `s/Group/group`
___
*[docs/tech-notes/change-replicas.md, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-Mw7_-R5EkTYI_Vd4013:-Mw7_-R5EkTYI_Vd4014:b-h32pzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a13a3659a9f979305aad99fd6ab252cf23ca75/docs/tech-notes/change-replicas.md#L67)):*
> ```Markdown
> The snapshot transfer is sent through a bi-directional stream of snapshot requests and snapshot responses. However,
> before the actual range data is sent, the streaming rpc first sends a header message to the recipient store and blocks
> until the store responds to accept or reject the snapshot data. The snapshot can be rejected if the range to add the
> ```

So, the following conditions determine whether the receiver accepts incoming snapshot: 

1. We only allow one concurrent snapshot application at a time. If there is a snapshot application already in-flight on the receiver, incoming snapshots are throttled or rejected if they wait too long. https://github.com/cockroachdb/cockroach/blob/2331ac1195b5d91ee1d30c4a70f1a5c6e5fe9446/pkg/kv/kvserver/store_snapshot.go#L426-L438
2. The receiver checks whether it already has a replica for the range that the snapshot is for, and if so, if its replica is "compatible" with the snapshot. Note that we expect a replica to be present on the receiver because we always add a new replica as a `LEARNER` before sending the first snapshot to it. That replica may or may not be "initialized" (like for example the `LEARNER`s added during rebalancing are uninitialized until they apply their first snapshot). This happens in https://github.com/cockroachdb/cockroach/blob/2331ac1195b5d91ee1d30c4a70f1a5c6e5fe9446/pkg/kv/kvserver/store_snapshot.go#L473
3. The `ReplicaPlaceholder` that you mentioned is essentially the in-memory bookkeeping that helps us avoid hazards like the one pointed out in this comment: https://github.com/cockroachdb/cockroach/blob/6b9168de33628257f3f1fdb17af1f8205ee21d32/pkg/kv/kvserver/replica_placeholder.go#L38-L53


<!-- Sent from Reviewable.io -->

2022-02-22 20:51 UTC, amygao9 reviewed
Thanks for the detailed reviews! I've fixed everything up, it's ready for a final look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-:-MwYAtrf4-D5Ytb_Yrdl:bi8kzjc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @tbg)

___
*[docs/tech-notes/change-replicas.md, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-Mw7_-R5EkTYI_Vd4013:-MwYAXsk1JAy8RlP7V_8:b-3squb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a13a3659a9f979305aad99fd6ab252cf23ca75/docs/tech-notes/change-replicas.md#L67)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

So, the following conditions determine whether the receiver accepts incoming snapshot: 

1. We only allow one concurrent snapshot application at a time. If there is a snapshot application already in-flight on the receiver, incoming snapshots are throttled or rejected if they wait too long. https://github.com/cockroachdb/cockroach/blob/2331ac1195b5d91ee1d30c4a70f1a5c6e5fe9446/pkg/kv/kvserver/store_snapshot.go#L426-L438
2. The receiver checks whether it already has a replica for the range that the snapshot is for, and if so, if its replica is "compatible" with the snapshot. Note that we expect a replica to be present on the receiver because we always add a new replica as a `LEARNER` before sending the first snapshot to it. That replica may or may not be "initialized" (like for example the `LEARNER`s added during rebalancing are uninitialized until they apply their first snapshot). This happens in https://github.com/cockroachdb/cockroach/blob/2331ac1195b5d91ee1d30c4a70f1a5c6e5fe9446/pkg/kv/kvserver/store_snapshot.go#L473
3. The `ReplicaPlaceholder` that you mentioned is essentially the in-memory bookkeeping that helps us avoid hazards like the one pointed out in this comment: https://github.com/cockroachdb/cockroach/blob/6b9168de33628257f3f1fdb17af1f8205ee21d32/pkg/kv/kvserver/replica_placeholder.go#L38-L53
</blockquote></details>

Done. Thanks for the detailed explanation! I've summarized these in the fix.


<!-- Sent from Reviewable.io -->

2022-02-24 10:54 UTC, tbg approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76408)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @amygao9, and @nvanbenschoten)

___
*[docs/tech-notes/change-replicas.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaB9NDDHbCfDK-U-l8:-MwfKasY0NZmM3y0Kpjo:b-a1q4ts) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L10)):*
<details><summary><i>Previously, amygao9 (Amy Gao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This still sounds a bit muddled, since now we say that "Raft snapshots occur when we add a new replica" but this is not true, we will only see a learner snapshot then. The small distinction follows, but it would be better to read if this were disentangled in the first place.
___
*[docs/tech-notes/change-replicas.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaDEgeAsgs9t5HHRmQ:-MwfLWot3LTZY4AOdAGM:buk6wdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L36)):*
<details><summary><i>Previously, amygao9 (Amy Gao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would avoid the word "initialized" here, since that is a concept that describes a replica that has received a snapshot. Just say "Once the learners have been added to the range, .."

The Learner snapshot is send from the leaseholder, which is typically, but not necessarily, the raft leader.
___
*[docs/tech-notes/change-replicas.md, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MwfL0wh3dBjHxtKsXHr:-MwfL0wh3dBjHxtKsXHs:bdbmzhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8d5108209aa10b440bb86a60de67430e59a3f9/docs/tech-notes/change-replicas.md#L27)):*
> ```Markdown
> and the `replicateQueue` executes these changes. Then the `replicateQueue` calls `changeReplicas` to act on these change
> requests and repeats until all changes are complete. Note that the `replicateQueue` only acts on ranges for which the
> local store is the current leaseholder.
> ```

Same pattern here, rather than saying something that is incorrect and later qualifying it, I would prefer streamlining this, for example by saying "For each replica which holds the lease, ..." earlier in the paragraph.
___
*[docs/tech-notes/change-replicas.md, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MwfLGjS8LsSZ2r4YJpk:-MwfLGjS8LsSZ2r4YJpl:bazdovs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8d5108209aa10b440bb86a60de67430e59a3f9/docs/tech-notes/change-replicas.md#L34)):*
> ```Markdown
> changes include non-voter promotions, voter/non-voter swaps, additions and removals. The change is performed in a
> distributed transaction and takes effect when the transaction is committed. There are many details involved in these
> changes, but for the purposes of this note, we will focus on up-replication and the process of sending Raft learner
> ```

Learner snapshot
___
*[docs/tech-notes/change-replicas.md, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MwfLKQCEb7oy5GBEsLs:-MwfLKQCEb7oy5GBEsLt:b-ckucdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8d5108209aa10b440bb86a60de67430e59a3f9/docs/tech-notes/change-replicas.md#L37)):*
> ```Markdown
> snapshots.
> 
> During up-replication, `ChangeReplicas` runs transactions that each add a new learner replica to the range. Learner
> ```

This sounds like you need multiple transactions to add a new learner, but it's only one.
___
*[docs/tech-notes/change-replicas.md, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MwfM-Tg0__LLaMNyAe9:-MwfM-Tg0__LLaMNyAeA:b-ev23h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8d5108209aa10b440bb86a60de67430e59a3f9/docs/tech-notes/change-replicas.md#L58)):*
> ```Markdown
> A snapshot is a bulk transfer of all replicated data in a range and everything the replica needs to be a member of a
> Raft group. It consists of a consistent view of the state of some replica of a range as of an applied index. The
> `GetSnapshot` method gets a storage engine snapshot of the replica data at a moment in time and creates an iterator from
> ```

Rather than talking about "in time", I would focus on what really matters, which is that it reflects the replicated state as of the applied index the snapshot is generated at, and that this does not change while the snapshot is being streamed out.


<!-- Sent from Reviewable.io -->

2022-02-25 23:17 UTC, aayushshah15 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once you address Tobi's feedback.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-:-Mwn6xpEEHAHBwyZitd6:b-bwlf7w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @amygao9, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-02-28 22:46 UTC, amygao9 reviewed
Thanks for the review Tobi! I addressed all the changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-:-Mx1VcTO3WdTUwJ3n6DH:bkfi5bi)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @nvanbenschoten, and @tbg)

___
*[docs/tech-notes/change-replicas.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaB9NDDHbCfDK-U-l8:-Mx16Ke_CodXpdLpbUJq:b710nhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L10)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This still sounds a bit muddled, since now we say that "Raft snapshots occur when we add a new replica" but this is not true, we will only see a learner snapshot then. The small distinction follows, but it would be better to read if this were disentangled in the first place.
</blockquote></details>

Done, I separated that part into 2 sentences to disambiguate. 
___
*[docs/tech-notes/change-replicas.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MvaDEgeAsgs9t5HHRmQ:-Mx1NhO96GZyJ9Xxl1KH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15f7444a91fa332620dc23912e8fcb7e14495e9/docs/tech-notes/change-replicas.md#L36)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I would avoid the word "initialized" here, since that is a concept that describes a replica that has received a snapshot. Just say "Once the learners have been added to the range, .."

The Learner snapshot is send from the leaseholder, which is typically, but not necessarily, the raft leader.
</blockquote></details>

Done.
___
*[docs/tech-notes/change-replicas.md, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MwfL0wh3dBjHxtKsXHr:-Mx16rO0E-YWFpk7ZtwA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8d5108209aa10b440bb86a60de67430e59a3f9/docs/tech-notes/change-replicas.md#L27)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Same pattern here, rather than saying something that is incorrect and later qualifying it, I would prefer streamlining this, for example by saying "For each replica which holds the lease, ..." earlier in the paragraph.
</blockquote></details>

Done.
___
*[docs/tech-notes/change-replicas.md, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MwfLKQCEb7oy5GBEsLs:-Mx1MsH5EwBfkc6BQGP_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8d5108209aa10b440bb86a60de67430e59a3f9/docs/tech-notes/change-replicas.md#L37)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This sounds like you need multiple transactions to add a new learner, but it's only one.
</blockquote></details>

Done.
___
*[docs/tech-notes/change-replicas.md, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-MwfM-Tg0__LLaMNyAe9:-Mx1UBp33aGzwU2osNrI:brrnpqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8d5108209aa10b440bb86a60de67430e59a3f9/docs/tech-notes/change-replicas.md#L58)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Rather than talking about "in time", I would focus on what really matters, which is that it reflects the replicated state as of the applied index the snapshot is generated at, and that this does not change while the snapshot is being streamed out.
</blockquote></details>

Done, added this part. 


<!-- Sent from Reviewable.io -->

2022-03-01 17:49 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> nice job on this! 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-:-Mx5aFfI1JnXrOiN0CFQ:b-69cna1)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @amygao9)

___
*[-- commits, line 6 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-Mx5ZecW8LRqWMJsAepd):*
Reminder to squash this commit before merging.
___
*[docs/tech-notes/change-replicas.md, line 89 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-Mx5_yJtE7o0aa4PETe0:-Mx5_yJtE7o0aa4PETe1:b-wbj7za) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f86a3ee33599d99dcfd1fcf4d7214aced998b1b/docs/tech-notes/change-replicas.md#L89)):*
> The key-value pairs are used to construct multiple SSTs for direct ingestion.

This occurs while the snapshot is being transmitted, which is how we avoid holding the entire snapshot in memory on the receiver. Consider rewording these two sections to make that more clear.


<!-- Sent from Reviewable.io -->

2022-03-07 19:27 UTC, amygao9 reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-:-Mx_q0v-6f5qfaLGox-V:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @nvanbenschoten)

___
*[docs/tech-notes/change-replicas.md, line 89 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76408#-Mx5_yJtE7o0aa4PETe0:-Mx_pkIT0bI8cIhqN0dt:bxsov6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f86a3ee33599d99dcfd1fcf4d7214aced998b1b/docs/tech-notes/change-replicas.md#L89)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> The key-value pairs are used to construct multiple SSTs for direct ingestion.

This occurs while the snapshot is being transmitted, which is how we avoid holding the entire snapshot in memory on the receiver. Consider rewording these two sections to make that more clear.
</blockquote></details>

Added this to the transmitting section instead.


<!-- Sent from Reviewable.io -->

2022-03-07 21:04 UTC, amygao9 commented
bors r+

2022-03-07 23:06 UTC, merged