colexec: deeply reset datum-backed vectors in ResetInternalBatch
cockroachdb/cockroach pull request #76463
Opened 2022-02-12 03:08 UTC by yuzefovich

Previously, we would keep references to the old datums set in the
datum-backed vectors until the datums are overwritten, thus, extending
the time period when the no-longer-used datums are live unnecessarily.
We don't have to do that for any other types because for others we can
actually reuse the old space for new elements, so we want to keep them
around (e.g. decimals can reuse the non-inlined coefficient). This
commit makes it so that we deeply unset the datums in
`ResetInternalBatch`.

Care had to be taken to keep the memory accounting up-to-date. In
particular, after deeply resetting the datum-backed vector, we want to
release the memory allocation that was taken up by the actual datums
while keeping the overhead of `tree.Datum` interface in (since
`[]tree.Datum` slice is still fully live).

Release note: None

2022-02-12 03:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76463)
<!-- Reviewable:end -->

2022-02-14 18:19 UTC, rharding6373 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76463)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/col/coldata/batch.go, line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76463#-MvtOa3k9YqDYnFzPLU-:-MvtOa3k9YqDYnFzPLU0:b-1ym80i) ([raw file](https://github.com/cockroachdb/cockroach/blob/338670d53c4f5d1b8bf9b4207ed57c5905981adf/pkg/col/coldata/batch.go#L345)):*
> ```Go
> 	}
> 	for i, ok := m.bytesVecIdxs.Next(0); ok; i, ok = m.bytesVecIdxs.Next(i + 1) {
> 		Reset(m.b[i])
> ```

We don't need to track released bytes in any other case, even bytes vec?


<!-- Sent from Reviewable.io -->

2022-02-14 18:25 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76463)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[pkg/col/coldata/batch.go, line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76463#-MvtOa3k9YqDYnFzPLU-:-MvtTPwvCl5_Begecu6C:b-ja9jb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/338670d53c4f5d1b8bf9b4207ed57c5905981adf/pkg/col/coldata/batch.go#L345)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

We don't need to track released bytes in any other case, even bytes vec?
</blockquote></details>

In all other cases we don't release any memory (i.e. we keep references to all old values in order to reuse them). In case of `Bytes` vectors, we do keep the full `Bytes.data` slice around, and we simply reset `maxSetLength` to 0 (with the current Bytes vector implementation).


<!-- Sent from Reviewable.io -->

2022-02-28 21:43 UTC, yuzefovich commented
Friendly ping @rharding6373 @michae2

2022-02-28 22:31 UTC, rharding6373 approved these changes
Apologies for the delay. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76463#-:-Mx1SQSzDSDzuR_Iefj6:biwi4tz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)



<!-- Sent from Reviewable.io -->

2022-02-28 23:32 UTC, yuzefovich commented
TFTR!

bors r+

2022-02-28 23:48 UTC, michae2 approved these changes
A little late, but <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :slightly_smiling_face:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76463#-:-Mx1j0OaCRy0lOtrO2BL:b-s9d613)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rharding6373)



<!-- Sent from Reviewable.io -->

2022-03-01 07:38 UTC, merged