ui: Use liveness info to populate decommissioned node lists
cockroachdb/cockroach pull request #76538
Opened 2022-02-14 21:32 UTC by zachlite

Previously, the decommissioned node lists considered node status entries
to determine decommissioning and decommissioned status. This changed in #56529,
resulting in empty lists. Now, the node's liveness entry is considered
and these lists are correctly populated.

Release note (bug fix): The list of recently decommissioned nodes
and the historical list of decommissioned nodes correctly display
decommissioned nodes.

2022-02-14 21:32 UTC, zachlite commented
Addresses https://github.com/cockroachdb/cockroach/issues/61812

2022-02-14 21:38 UTC, zachlite commented
With these changes, here's what decommissioning via `cockroach node` looks like:

1. Done moving replicas
![Screen Shot 2022-02-14 at 3 31 32 PM](https://user-images.githubusercontent.com/5423191/153950342-92106c63-25be-46d7-8909-91ace72579e2.png)


2. Immediately
![Screen Shot 2022-02-14 at 4 04 09 PM](https://user-images.githubusercontent.com/5423191/153950344-a0f21662-1d1e-487d-a992-a9fe8a79750e.png)

3. After 5 minutes
![Screen Shot 2022-02-14 at 4 08 00 PM](https://user-images.githubusercontent.com/5423191/153950345-79d17b61-e489-4c60-a0e9-758a687a6d70.png)


4. Full History
![Screen Shot 2022-02-14 at 3 56 46 PM](https://user-images.githubusercontent.com/5423191/153950343-c03a3838-2d6a-402c-88d2-fe0f5648ae3a.png)

2022-02-15 07:58 UTC, koorosh requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76538)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @Santamaura, @tbg, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/index.tsx, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76538#-MvwKfyN0cXyVtBYMcHu:-MvwKfyN0cXyVtBYMcHv:bg1elom) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b9c8fe4e7816fb047a36513b27e6c268f032c04/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/index.tsx#L56)):*
> ```XML
>   StatusTooltip,
> } from "./tooltips";
> import { cockroach } from "oss/src/js/protos";
> ```

nit. change import path to avoid `oss` part (it is added with auto-imports). 
Should be: `from "src/js/protos"`
___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/index.tsx, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76538#-MvwNPVR-zUrI3AkkSX4:-MvwNPVR-zUrI3AkkSX5:b-dk9dqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b9c8fe4e7816fb047a36513b27e6c268f032c04/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/index.tsx#L174)):*
> ```XML
> const NodeNameColumn: React.FC<{
>   record: NodeStatusRow | DecommissionedNodeStatusRow;
>   shouldLink: boolean;
> ```

Can it be defined with default value (`shouldLink = true`), so it shouldn't be defined explicitly in other places?
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodeHistory/decommissionedNodeHistory.tsx, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76538#-MvwMYCf6Ky74grUFqDN:-MvwMYCgD8L7_Bot0WCn:b-6c8vkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b9c8fe4e7816fb047a36513b27e6c268f032c04/pkg/ui/workspaces/db-console/src/views/reports/containers/nodeHistory/decommissionedNodeHistory.tsx#L21)):*
> ```XML
> import { nodesSummarySelector } from "src/redux/nodes";
> import { refreshLiveness, refreshNodes } from "src/redux/apiReducers";
> import { cockroach } from "oss/src/js/protos";
> ```

nit. the same as above, remove `oss` part from import.


<!-- Sent from Reviewable.io -->

2022-02-15 10:16 UTC, tbg approved these changes
Haven't reviewed any of the code (since it's all in the UI), but I did go through the PR message and the new behavior looks good. For my education, where does the behaviour to display the node as "unavailable" in the decommissioned section come from? I think if we're being idealistic about the UX then once a node is decommissioned, it shouldn't matter whether it has been offline for five minutes or not.

Thanks!

2022-02-15 10:26 UTC, erikgrinaker approved these changes
What Tobi said, LGTM!

Also, in general I'd encourage always joining `kv_node_status` data against `kv_node_liveness` before use. The liveness data is the source of truth for node existence. Using a status entry when a liveness entry does not exist, or ignoring a liveness entry when the status entry does not exist, both yield incorrect and surprising results -- we've had several cases where failing to do this has caused pretty severe downstream problems.

2022-02-15 15:54 UTC, zachlite commented
Thanks for the review, all.
@tbg, the unavailable status comes from the enum `cockroach.kv.kvserver.liveness.livenesspb.NodeLivenessStatus`
@erikgrinaker, ack.  I'm treating liveness data as the source of truth.

2022-02-15 16:36 UTC, koorosh approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76538)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Santamaura and @zachlite)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/76538#-MvyEPyH4Ll4yePlm0t1:-MvyEPyH4Ll4yePlm0t2:bg7igkv) (no related file):*
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

---


<!-- Sent from Reviewable.io -->

2022-02-15 18:11 UTC, zachlite commented
bors r+

2022-02-15 19:42 UTC, merged