ci,dev: allow injecting cockroach binary into `compose` tests
cockroachdb/cockroach pull request #76540
Opened 2022-02-14 22:11 UTC by rickystewart

Same sort of thing we do in `acceptance`: build the `cockroach` and
`compare_test` binaries ahead of time and pass the locations to the
binaries as flags.

Release note: None

2022-02-14 22:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76540)
<!-- Reviewable:end -->

2022-02-15 14:58 UTC, rail requested changes
Looks like you need to update the dev datadriven tests to reflect the changes, they are failing now.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76540#-:-Mvxsdnu8SkAzVlZeIJU:b-vweynw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2022-02-15 17:13 UTC, rickystewart commented
I just had to delete the test file, since the implementation of this command got a lot more complicated.

2022-02-17 18:30 UTC, rail approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76540#-:-Mw7wlvB-YLl3huk7IEr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2022-02-17 19:00 UTC, rickystewart commented
bors r=rail

2022-02-18 01:28 UTC, merged