changefeedccl: periodic pts record updates
cockroachdb/cockroach pull request #76605
Opened 2022-02-15 19:27 UTC by samiskin

Previously changefeeds only laid down protected timestamp records to
protect against either an ongoing backfill or the changefeed lagging
behind.  This is insufficient in cases such as if the gcttl is very
short, recurring errors retry the changefeed for too long, or in
upcoming work to enable serverless to shut down idle changefeeds.

This PR removes the manual PTS protection on backfills and begins an
async routine on the changeFrontier that updates the protected timestamp
record to the current highwater mark.

Release note: None

2022-02-15 19:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76605)
<!-- Reviewable:end -->

2022-02-16 15:58 UTC, miretskiy requested changes
This is very nice. 

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76605#-:-Mw2FIzMArtKMZKqfpma:b2l2u80)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @samiskin)

___
*[-- commits, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76605#-Mw2E3UA8JXWJ3hdGAtS):*
This definitely needs a release note.  It's an internal change, and probably nobody cares about this
internal implementation detail; but it's a release note worty.
At the very least mentioning that changefeeds can run reliably on tables w/ low ttl.
Definitely need to mention the setting to control the frequency of such updates because this frequency effectively 
overrides gcttl set on a table.
___
*[pkg/ccl/changefeedccl/changefeed.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76605#-Mw2ESi_CfCrtM3pJwoy:-Mw2ESi_CfCrtM3pJwoz:b-nagn2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/519906fc4d533b16b6e7407dde7e355266cd91bd/pkg/ccl/changefeedccl/changefeed.go#L46)):*
> ```Go
> }
> 
> func shouldProtectTimestamps(codec keys.SQLCodec) bool {
> ```

pls add a todo to remove this restriction once tenant based pts is in... 
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76605#-Mw2EhVsBNuz5HugxzaG:-Mw2EhVsBNuz5HugxzaH:b-fugtri) ([raw file](https://github.com/cockroachdb/cockroach/blob/519906fc4d533b16b6e7407dde7e355266cd91bd/pkg/ccl/changefeedccl/changefeed_processors.go#L1172)):*
> ```Go
> 	}
> 
> 	if err := cf.flowCtx.Stopper().RunAsyncTask(ctx, "changefeed-pts-manager", func(ctx context.Context) {
> ```

not sure if we need this.  Why not do this while trying to checkpoint job progress?


<!-- Sent from Reviewable.io -->

2022-02-17 15:31 UTC, samiskin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76605)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[-- commits, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76605#-Mw2E3UA8JXWJ3hdGAtS):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This definitely needs a release note.  It's an internal change, and probably nobody cares about this
internal implementation detail; but it's a release note worty.
At the very least mentioning that changefeeds can run reliably on tables w/ low ttl.
Definitely need to mention the setting to control the frequency of such updates because this frequency effectively 
overrides gcttl set on a table.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76605#-Mw2ESi_CfCrtM3pJwoy:-Mw784U99ltUllqgYV3d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/519906fc4d533b16b6e7407dde7e355266cd91bd/pkg/ccl/changefeedccl/changefeed.go#L46)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

pls add a todo to remove this restriction once tenant based pts is in... 
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76605#-Mw2EhVsBNuz5HugxzaG:-Mw786TJ44RwwyZqqVfp:b-yzprec) ([raw file](https://github.com/cockroachdb/cockroach/blob/519906fc4d533b16b6e7407dde7e355266cd91bd/pkg/ccl/changefeedccl/changefeed_processors.go#L1172)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

not sure if we need this.  Why not do this while trying to checkpoint job progress?
</blockquote></details>

I just had it this way since you mentioned it being a separate loop on a timer initially.  I wasn't sure whether it'd be considered more or less complex to either have a piece of functionality be more distinct from other functionality versus the timing of events being more deterministic where recurring events happen in lockstep with resolved events.

I do like that keeping it with checkpoints keeps table changes in one place and having it there lets it share the "min checkpoint frequency" option.  I made the changes to move it to resolved 👍.


<!-- Sent from Reviewable.io -->

2022-02-17 16:34 UTC, miretskiy approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76605)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @samiskin)

___
*[-- commits, line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76605#-Mw7WiFi2jrgjlp3H-0-):*
i don't think it's a bug fix -- it's an enterprise change.


<!-- Sent from Reviewable.io -->

2022-02-17 20:19 UTC, samiskin commented
bors r+

2022-02-18 01:28 UTC, merged

2022-03-08 22:02 UTC, shermanCRL commented on pkg/ccl/changefeedccl/changefeed.go
> +	// TODO(smiskin): Remove this restriction once tenant based pts are enabled
Can we TODO this @samiskin @adityamaru, given https://github.com/cockroachdb/cockroach/issues/73727#issuecomment-1061892910 ?