roachpb: add lock table metadata structures
cockroachdb/cockroach pull request #76611
Opened 2022-02-15 21:00 UTC by AlexTalks

This change adds the protobuf structures, as well as the method, needed
to capture the state of a replica's lock table.  This is part of the
work coming out of #75541, and is needed to be able to implement the
`QueryLocks` RPC.

Release note: None

2022-02-15 21:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76611)
<!-- Reviewable:end -->

2022-03-02 15:56 UTC, nvanbenschoten approved these changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76611)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[pkg/kv/kvserver/concurrency/lock/lock_waiter.proto, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76611#-MxAItgA7EkwQHdyfAKV:-MxAItgA7EkwQHdyfAKW:b-bwzrhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85db7b81d31f06a3bf671e6b29b17756982463a/pkg/kv/kvserver/concurrency/lock/lock_waiter.proto#L22)):*
> ```protobuf
> // KeyAccessType represents the type of operation that a transaction holding or
> // waiting on a lock intends to carry out, once necessary locks are acquired.
> enum KeyAccessType {
> ```

I think this can be replaced by the `Strength` enum. Currently, we only support two strengths, `None` (which maps to read-only here) and `Exclusive` (which maps to read-write here).
___
*[pkg/kv/kvserver/concurrency/lock/lock_waiter.proto, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76611#-MxAJG9HANQuHpfOVjgz:-MxAJG9HANQuHpfOVjh-:bvoob61) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85db7b81d31f06a3bf671e6b29b17756982463a/pkg/kv/kvserver/concurrency/lock/lock_waiter.proto#L31)):*
> ```protobuf
> // LockWaiter represents a transaction (or non-transactional operation) that is
> // waiting in the wait queue of readers or writers on an individual lock.
> message LockWaiter {
> ```

nit: this package is called `lock`, so we can call this `message Waiter {`. There's a part of the style guide we use that talks about package name "stuttering", though I'm having trouble finding it.
___
*[pkg/kv/kvserver/concurrency/lock/locking.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76611#-MxAKAQkE8VduRxWGGX1:-MxAKAQkE8VduRxWGGX2:b-wbvo2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85db7b81d31f06a3bf671e6b29b17756982463a/pkg/kv/kvserver/concurrency/lock/locking.go#L29)):*
> ```Go
> 
> // SafeValue implements redact.SafeValue.
> func (Durability) SafeValue() {}
> ```

Want to do the same for `Strength` sine you're here?
___
*[pkg/roachpb/data.proto, line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76611#-MxAKP2J1SjlHGY08GEU:-MxAKP2J1SjlHGY08GEV:b87clqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85db7b81d31f06a3bf671e6b29b17756982463a/pkg/roachpb/data.proto#L558)):*
> ```protobuf
>   bytes key = 2 [(gogoproto.casttype) = "Key"];
>   // The metadata on the current lock holder, or nil if the lock is not held.
>   LockAcquisition lock_holder = 3;
> ```

I think we decided that we should inline the txn and durability fields, since we don't need the LockAcquisition's Span and that message is used in a slightly different context. Or am I misremembering?
___
*[pkg/roachpb/data.proto, line 562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76611#-MxAKbpd3hAe4_b0GIkp:-MxAKbpe1OBXdtWwTkb7:b-3ut33l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85db7b81d31f06a3bf671e6b29b17756982463a/pkg/roachpb/data.proto#L562)):*
> ```protobuf
>   google.protobuf.Duration hold_duration = 4 [(gogoproto.nullable) = false,
>     (gogoproto.stdduration) = true];
>   // The queue of readers and writers currently waiting on the lock.
> ```

Let's note the order of this list, or mention that the order is arbitrary.
___
*[pkg/roachpb/method.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76611#-MxALDsKCWmCAXKFxejJ:-MxALDsKCWmCAXKFxejK:b-n6iwax) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85db7b81d31f06a3bf671e6b29b17756982463a/pkg/roachpb/method.go#L100)):*
> ```Go
> 	// aborting it.
> 	RecoverTxn
> 	// QueryLocks requests the current state of concurrency control's lock table.
> ```

I don't think we meant to include this in this PR.


<!-- Sent from Reviewable.io -->

2022-03-02 15:57 UTC, nvanbenschoten requested changes
Sorry, didn't mean to mark this as approved quite yet 😃

2022-03-02 23:02 UTC, AlexTalks reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76611)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/method.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76611#-MxALDsKCWmCAXKFxejJ:-MxBeNVqBr9ZrdEJjb7u:b-h8ten4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85db7b81d31f06a3bf671e6b29b17756982463a/pkg/roachpb/method.go#L100)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think we meant to include this in this PR.
</blockquote></details>

I did, though it was an artifact of an earlier version of the PR in which I included all API/proto updates in the same change (and running a `generate` build is very slow)


<!-- Sent from Reviewable.io -->

2022-03-03 02:24 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76611#-:-MxC_uaWByiCuBtbuPGq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks)



<!-- Sent from Reviewable.io -->

2022-03-07 18:22 UTC, AlexTalks commented
bors r+

2022-03-07 22:21 UTC, ajwerner commented
bors r-

this doesn't pass CI, needs more generation

2022-03-08 21:19 UTC, AlexTalks commented
bors r+

2022-03-08 21:24 UTC, AlexTalks commented
bors r+

2022-03-09 00:52 UTC, merged