server: remove query constants in sessions response for VIEWACTIVITYR…
cockroachdb/cockroach pull request #76675
Opened 2022-02-16 14:39 UTC by xinhaoz

…EDACTED

Previously, we return the full query in ListSessions for admin users,
users requesting their own sessions and users requesting all sessions
with VIEWACTIVITY or VIEWACTIVITYREDACTED roles. This commit removes
the query with constants from the response for users that only have the
VIEWACTIVITYREDACTED role if requesting all sessions in the cluster. The
query without constants remains in the response.

Release note (api change): users without admin or VIEWACTIVITY
roles will not have access to the full queries with constants in
the the ListSessions response.

2022-02-16 14:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76675)
<!-- Reviewable:end -->

2022-02-16 16:35 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76675)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[pkg/server/status.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76675#-Mw2N4Fs18p9gyocrEjI:-Mw2N4Fs18p9gyocrEjJ:b-am14el) ([raw file](https://github.com/cockroachdb/cockroach/blob/346fb07c8375c5ff039ba25807c606247ba13c31/pkg/server/status.go#L188)):*
> ```Go
> 	}
> 
> 	hasViewActivity, err := b.privilegeChecker.hasRoleOption(ctx, sessionUser, roleoption.VIEWACTIVITY)
> ```

a user can have VIEWACTIVITY and VIEWACTIVITYREDACTED, with the redacted taking precedent. The way it is right now, if they have both they will be able to see the data, but what you want is for them to have VIEWACTIVITY but not have VIEWACTIVITYREDACTED. You can use the function `requireViewActivityAndNoViewActivityRedactedPermission` 
___
*[pkg/server/status_test.go, line 2928 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76675#-Mw2NgEk025yrUXY8Lsm:-Mw2NgEk025yrUXY8Lsn:b9u32oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/346fb07c8375c5ff039ba25807c606247ba13c31/pkg/server/status_test.go#L2928)):*
> ```Go
> 	require.Equal(t, "SELECT _", session.LastActiveQueryNoConstants)
> 
> 	// Remove VIEWACTIVITYREDCATED and grant VIEWACTIVITY.
> ```

add a test which a user with both roles VIEWACTIVITY and VIEWACTIVITYREDACTED and they shouldn't see the info


<!-- Sent from Reviewable.io -->

2022-02-17 14:11 UTC, maryliag approved these changes
just some nits on your commit message (make sure to update the PR description with the changes you make there), otherwise
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76675#-:-Mw70Ow787iJA9pvxJiO:b-etwwxf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76675#-Mw7-qis2kzsQWWb6Jup):*
nit: remove the `only`, it doesn't matter if is only that or a combination with others
___
*[-- commits, line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76675#-Mw70-gT2GJHvczjn_WC):*
nit: you need to explain what was the change from this commit, so:
users with VIEWACTIVITYREDACTED will no longer have access to the full queries with...


<!-- Sent from Reviewable.io -->

2022-02-17 14:21 UTC, maryliag reviewed
and making sure the new test is passing :) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76675#-:-Mw72l4M51v_wjjxb-t6:b7ie607)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)



<!-- Sent from Reviewable.io -->

2022-02-25 20:07 UTC, jocrl commented
🎉 bors r+ !

2022-02-25 20:58 UTC, maryliag commented
bors r+

2022-02-25 23:54 UTC, merged