ui: create ui pages for active queries and transactions
cockroachdb/cockroach pull request #76753
Opened 2022-02-17 20:21 UTC by xinhaoz

This commit creates the pages for active transactins and
queries in db-console. Each page calls the /sessions API
at an interval of 10 seconds to refresh the data.

Release note (ui change): Users can now see actively running
queries and transactions in the SQL Activity tab. The transactions
and statements tabs in SQL activity now have a menu to show either
active or historial transactions and statements data.

2022-02-17 20:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76753)
<!-- Reviewable:end -->

2022-02-17 23:30 UTC, xinhaoz commented
TODO: add loom, and tests for utility functions + hooks

2022-02-18 15:35 UTC, Azhng reviewed
> Reviewed 55 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCFzFB-vOFFqef5N2f:-MwCFzFB-vOFFqef5N2g:b-2bsugr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx#L49)):*
> ```XML
>   onClearFilters: () => void;
>   onColumnsSelect: (columns: string[]) => void;
> };
> ```

FYI(note) props splitting only needs to happen when connecting a component to redux 
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCI-hz0h2OxAEgE0Qg:-MwCI-hz0h2OxAEgE0Qh:b-diqnv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx#L64)):*
> ```XML
> 
>   const tableColumns: SelectOption[] = getColumnOptions(selectedColumns);
>   const data = statements || [];
> ```

@xinhaoz `data` should be removed, `statement` should be used
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCGSFTBcfqyVkuNxTP:-MwCGSFU8w1sOZZFs0iJ:b-3st6bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx#L68)):*
> ```XML
>     ascending: true,
>     columnTitle: "startTime",
>   });
> ```

Nice, custom react hook! @xinhaoz pointed out that having 2 sources of truth (URL + localStorage) has led to many problems before. The idea/behaviors need to be more flushed out.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCJs_t-m9jvtNXDXwr:-MwCJs_t-m9jvtNXDXws:b-3iqmbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L20)):*
> ```XML
> export const ACTIVE_STATEMENT_SEARCH_PARAM = "q";
> 
> export function filterActiveStatements(
> ```

@xinhaoz oops, the filter was created but it was not used. So, use it :stuck_out_tongue: 
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCKFzD4-UJK5be7KPl:-MwCKFzD4-UJK5be7KPm:buaaxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L42)):*
> ```XML
> ): ActiveStatement[] {
>   const activeQueries: ActiveStatement[] = [];
>   if (sessionsResponse.sessions != null) {
> ```

nit: invert the conditions here to return early
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCKamy3zPssXLqizlW:-MwCKamy3zPssXLqizlX:b6gkjzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L48)):*
> ```XML
>           executionID: query.id,
>           transactionID: byteArrayToUuid(query.txn_id),
>           sessionID: byteArrayToUuid(session.id),
> ```

note: `sessionID` is a `uint128` instead of UUID. However, it's 16 bytes, which is same as UUID type.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCKmL3CoY_Uh5lFf2D:-MwCKmL3CoY_Uh5lFf2E:b-a3navc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L49)):*
> ```XML
>           transactionID: byteArrayToUuid(query.txn_id),
>           sessionID: byteArrayToUuid(session.id),
>           query: query.sql?.length > 0 ? query.sql : query.sql_no_constants,
> ```

nit: comment that this is for `VIEWACTIVTYREDACTED`
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCL2ypCmssZMLNurI1:-MwCL2ypCmssZMLNurI2:bjfanym) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L102)):*
> ```XML
>     const executionID = byteArrayToUuid(activeTxn.id);
>     // Find most recent statement.
>     const mostRecentStmt = activeStmts.find(
> ```

nit: build a map?
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsTable/activeStatementsTable.tsx, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCIp-HCDRK34T9_reQ:-MwCIp-HCDRK34T9_reR:bupt6rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsTable/activeStatementsTable.tsx#L116)):*
> ```XML
> 
>   return (
>     <SortedTable columns={columns} className="statements-table" {...rest} />
> ```

nit: maybe do that `cx()` thingy? 
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsTable/activeTransactionsTable.tsx, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCLisW0_dh2GZwMnPX:-MwCLisW0_dh2GZwMnPY:bwelh8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsTable/activeTransactionsTable.tsx#L121)):*
> ```XML
>     isSelected: isColumnSelected(selectedColumns, col),
>   }));
> }
> ```

nit: might make sense to refactor this a bit to work on both stmt and txn page.
___
*[pkg/ui/workspaces/cluster-ui/src/columnsSelector/utils.ts, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCN_Dx6ELMaY6YnGQZ:-MwCN_Dy0BYVoAtdyUc6:b-8tp3a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/columnsSelector/utils.ts#L20)):*
> ```XML
>     (selectedColumns == null && c.showByDefault !== false) || // show column if list of visible was never defined and can be show by default.
>     (selectedColumns !== null && selectedColumns.includes(c.name)) || // show column if user changed its visibility.
>     c.alwaysShow === true // show column if alwaysShow option is set explicitly.
> ```

note to self: check if we need to do this explicit comparision for boolean in typescript 
___
*[pkg/ui/workspaces/cluster-ui/src/columnsSelector/utils.ts, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCN-sa7my-OJInXect:-MwCN-sa7my-OJInXecu:bmdrisi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/columnsSelector/utils.ts#L22)):*
> ```XML
>     c.alwaysShow === true // show column if alwaysShow option is set explicitly.
>   );
> };
> ```

nice extraction. super small nit move the comment to the top cuz the long lines 
___
*[pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCPGzQBsGZiXwJdfUl:-MwCPGzQBsGZiXwJdfUm:b-7pkdeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx#L308)):*
> ```XML
>         ...this.state.filters,
>         [field]:
> [...]

2022-02-28 15:00 UTC, jocrl requested changes
Woooo!! Great stuff 😄. This is big!

I got as far as reviewing `pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx` (plus a random comment in `search.tsx` cos I happened to see it). But I thought I would publish the present comments so that you can take a look if you like; my brain is starting to go 😛. 

The spacing for the added UI seems little weird; not sure if that's part of that TODO? Even if you don't have the video ready I'd suggest commenting with a few screenshots to get approval from Anne.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-:-Mwba16q5Ta27FXCDnie:b-ilzc24)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCGSFTBcfqyVkuNxTP:-MwbYfQA77t8tq19YYU6:b-qu7r3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx#L68)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Nice, custom react hook! @xinhaoz pointed out that having 2 sources of truth (URL + localStorage) has led to many problems before. The idea/behaviors need to be more flushed out.
</blockquote></details>

Yay hooks! 🎉

**td;lr**
Hrrmm... @matthewtodd you might be interested in this as well. In summary, this is the same pattern that I flagged as concerning in the databases page PR, which is that it works by coincidence without using React state. That said, the databases page PR also sets the precedence that @xinhaoz you don't have to address this now, since with the exception of the corner case behavior (see the second section below), it works! It seems like @maryliag had good intuition when she suggested to show and tell on this 😄. I'm hoping to slowly lay some foundation and intuition for this across the next few show and tells. Having seen this twice, I will one day eventually write an RFC.

But if you're interested in this particular issue for now, here is my explanation.

**Explanation**
In a React app, React state should be used as the source of truth. This provides centralization and consistency that everything else can flow from: you update state, and React will take care of updating everything downstream that you've said is connected to it. Failure to put things in React state can cause corner case bugs where downstream things fail to update because you are working outside of the React system.

@azhng mentioned above that there are 2 things: "URL + localStorage". To be precise, it's more like "URL + Redux (which happens to be backed by local storage)". I would strongly say that the source of truth should be Redux (i.e. a type of React state, the other one being local component state), and that the URL should not be used as a "source of truth".

It helps to distinguish three things here. There's the:
(1) "initial/default sort selection", aka the "value to initialize state with"
(2) the "current sort selection", aka "current sort state", and 
(3) the "derivative of the current sort selection", aka "derivative of state"

Crucially, only (2) is actually state itself. (1) and (3) are not state. (1) is the value to initialize state with, and (3) reads from state. But they are not state.

I see the URL as
(1) the _initial_ sort selection
(3) a _derivative_ of the current sort selection

The Redux value under the `localStorage` key is
(2) the state

To illustrate things more, we can further distinguish that the Redux value under the `localStorage` key is not itself the browser local storage (https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). The Redux key is backed by local storage, which is to say that the existing implementation of the `LocalSetting` class encapsulates and automatically keeps the two in sync for you. With this in mind, the browser local storage _also should not be used as state_. The Redux value is the source of truth, so you would read from Redux value under the `localStorage` key. In contrast, one shouldn't read the sort value via `localStorage.getItem('whatever the key is');`.

I.e., the browser local storage is also
(1) the initial filter selection
(3) a _derivative_ of the current filter selection

but it is not (2) state.

**Corner case behavior**
I wrote that failure to put things in React state can cause corner case bugs due to working outside of the React system. This might not exactly be a bug, but it's probably undesired behavior and demonstrates what happens when you don't use React state.

The behavior in the fingerprint tables is probably what we want. To demonstrate:
- go to the statements fingerprints table, and click on one of the columns is set the sort, e.g. "Max Memory"
- go to the transaction fingerprints table, and click on "Contention" to sort
- go back to the statement fingerprints table. "Max Memory" should still be the sort
- and if you go back to the transaction fingerprints table, "Contention" should still be the short

If you do the same thing with the active statements/transactions tables, the sort will always be reset to the default sort. Note that this behavior, switching within the same page, is due to stay being put in React/Redux, and _not_ due to the persistence of local storage. The local storage should provide that the short will persist across browser tabs.

**How, concretely, to address this**
For addressing this issue, I'd suggest looking at how sort is handled in the existing statements page in `cluster-ui/src/statementsPage/statementsPage.tsx`. The sort state (2) is stored in Redux, and the component gets passed the [state](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L269) and the [setState](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L299) as props in the connection.

The state is initialized (1) [in the constructor](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L187) from the query params. An alternative to the `getStateFromHistory` would be to use the `useTableSortFromURL` introduced here 🙂.

And the query params are derived (3) from changing state in `componentDidUpdate`, [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L312).

Should the filter be shared with the fingerprints pages? If so, I would make sure to both read from and write to the same Redux state. If they should be independent, use different bits of redux state (I'm not great with redux vocabulary 😅).

**Side note**
It might seem like the appropriate solution here is unnecessary to do. Why add these layers of indirection, if it works? The same can be said for why use Redux instead of just vanilla React, since Redux further adds additional layers of indirection. It's an assessment of whether these layers of indirection are worth the benefits that these systems bring. And for us, we've decided that both are worth it. And so using React means actually using state 😉.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwbZmhMCCbIdPLgrAep:-MwbZmhMCCbIdPLgrAeq:b-wdm25p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f76867ca721389758f650245358d9dfe68cf7a0f/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L29)):*
> ```XML
>   );
> 
>   if (search && search !== "") {
> ```

nit: `""` is falsy (https://developer.mozilla.org/en-US/docs/Glossary/Falsy), so this can be simplified to `if (search)`
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 38 at r2](https://review [...]

2022-02-28 17:16 UTC, xinhaoz commented
___
*[pkg/ui/workspaces/cluster-ui/src/search/search.tsx, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCQde_8t6WLXbgo1rp:-Mx0HUuzA7kODSAwMBNC:boyiybp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/search/search.tsx#L100)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

So... this `onSubmit` isn't actually being used 🙂. It genuinely isn't being used anywhere in the render function!

The onSubmit that comes from props is actually being used in Line 46 😉.

`this.props.onSubmit` is the value from props
`this.onSubmit` is the `onSubmit` function _on the class itself_, defined in Line 43.

So to say, I haven't gotten deep enough into this PR to understand why you're omiting `onSubmit`. But given so, it's in Line 46 where you'll want to test for it and handle the case where it isn't passed.
</blockquote></details>

Pulling `onSubmit` out here was to fix a prior issue where the `onSubmit` passed to the search component , which is typed as a func of `(string) => void`, was being passed to the `Input` component from antd via the spread of `inputProps` below this. 

`Input` expects onSubmit func to be the one in `HTMLInputProps`, which has a different func signature than the one we define in search props. This caused whatever onSubmit function we pass into Search to cause a TS error as it didn't adhere to the onSubmit expected by Input. The `onSubmit` passed to search is only used in the class function that's used for the form, so it shouldn't be passed to `Input` in the first place, which is also the case for `onClear`, which was being pulled out before forwarding props to Input as well.

In the txns and stmts pages, the onSubmit functions passed to the search component are typed as `any` to avoid the TS errors, but cause introduced 'dont type this as any!!!' warnings. I didn't want to introduce another incorrectly typed 'any' warning in the new components when using `Search`, so I just decided to fix this. I'll remove the any typing in txns and stmts as well.


<!-- Sent from Reviewable.io -->

2022-02-28 22:57 UTC, jocrl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/search/search.tsx, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCQde_8t6WLXbgo1rp:-Mx1ToaY9SdKB8hrq6g-:b-puzirh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/search/search.tsx#L100)):*
Ooo, okay. I'm starting to understand this and Archer's request for a comment now.

Rather than a comment, what do you think of either of these two alternatives, to be more explicit via the code that the intention here is to omit keys?
Alternative 1: spread props (for immutable cloning), then use plain javascript delete https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete
Alternative 2: use lodash clone, then omit https://docs-lodash.com/v4/omit/

> The onSubmit passed to search is only used in the class function that's used for the form... In the txns and stmts pages, the onSubmit functions passed to the search component are typed as any to avoid the TS errors

Okay, interesting. Thanks for cleaning up the typing!
___
*[pkg/ui/workspaces/cluster-ui/src/search/search.tsx, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCQnDOApZd0h3t8ILh:-Mx1Y0u6CggGDXLSWJFl:b-alz8sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/search/search.tsx#L109)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Oooo. Archer, if you look closely, this line is not `this.props.onChange`.

See comment for the addition above.
</blockquote></details>

In light of better understanding the above thread, I now don't understand Archer what you mean 😛. There's still currently no `onChange` variable?


<!-- Sent from Reviewable.io -->

2022-03-02 15:11 UTC, jocrl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/sqlActivityContentRoot/sqlActivityContentRoot.tsx, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCCGm63Uu3HU-Kixem:-MxA9Ohw3TiVdYACPjO8:beggdl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/sqlActivityContentRoot/sqlActivityContentRoot.tsx#L24)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `SQLActivityContentBase` and a comment indicating that this is meant to be inherited by the `Statement` and `Transaction` Page ? 
</blockquote></details>

A few comments about this component:

**Use state, not query params** 🙂
Currently, this component has pseudo-state in which the query params is used as the source of truth, and there is no React state. This is the same comment that I previously wrote a long comment for, and that we chatted about. This component should instead be made stateful (I would think local component state, since no other components are concerned with this). Initializing through query params can be done by initializing useState, and updating history when state changes can be done with a useEffect. If you like, you could pull these things out into a custom hook, something like `useStateWithSyncedQueryParam`.

**Composition over inheritance**
Per Archer's comment, React [prefers composition over inheritance](https://reactjs.org/docs/composition-vs-inheritance.html). So instead of thinking of this component as a base, I would think of it as a wrapper. Concretely, it wraps the stmt and transaction page content with radio button controls, so maybe `SQLActivityRootControls` or `StatementsTransactionsRootControls`, since it's only for those two pages.

**useMemo note**
It's not always cost effective to use `useMemo`, even though it feels tempting and free to do performance optimizations. See [this article](https://blog.logrocket.com/rethinking-hooks-memoization/) and [this article](https://kentcdodds.com/blog/usememo-and-usecallback) for more. A common, genuine use case for useMemo is if the function is genuinely expensive.

If the intention here was to save the cost of searching array... I'd point out that this is an array on the order of 2 😄

If the intention here was pre-emptively for referential equality, I refer to this all caps from the second article by Dan the React Dan. It's loud, but makes the point 😅. One generally shouldn't think about re-renders. And if there genuinely are problems due to referential equality, I would justify that in a comment (since the function isn't obviously expensive).

![image.png](https://files.reviewableusercontent.io/images/reviewable/91907326/Rb8VoBkbssRheiyVzFDrM76t/image.png)

I think the mentality is definitely different from the back end side, where you're really trying to squeeze performance.


<!-- Sent from Reviewable.io -->

2022-03-02 17:18 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/search/search.tsx, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCQnDOApZd0h3t8ILh:-MxAcKoy6ndu6V2Tt2Vd:b8a2f5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/search/search.tsx#L109)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

In light of better understanding the above thread, I now don't understand Archer what you mean 😛. There's still currently no `onChange` variable?
</blockquote></details>

Oh right, I think I might have missed that this is not from the props :sweat_smile: 


<!-- Sent from Reviewable.io -->

2022-03-07 15:08 UTC, xinhaoz commented
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwmriP9651XThaqc9ro:-MxZrHje5xZuHRmu2aur:b-c5c6ci) ([raw file](https://github.com/cockroachdb/cockroach/blob/f76867ca721389758f650245358d9dfe68cf7a0f/pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx#L24)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: The string union type here is good, and I think an enum type would be even better! Please make this change for all string union types and usages introduced in this PR.

Docs are [here](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums). An enum would an able that when the value is used, it's easy to tell what type it is and what the other possible values are. So like, in places where you would use the string `"Executing"`, you would use `ExecutionStatus.Executing`. And one can type `ExecutionStatus.` and have your IDE complete the other possible values.

I made a similar comment for Matthew's databases page PR, and you can see that in the difference between r1 and r3. https://reviewable.io/reviews/cockroachlabs/managed-service/7708#-. I think in later revisions he made some changes needed for typing. Happy to chat or hop on a tuple to help with anything! And yeah, I think @matthewtodd would also helpful, since he made very similar revisions for his own PR.

I should probably also write in RFC for this... one day it will happen 😄
</blockquote></details>

AFAIK most editors will be able to autocomplete string union types / will complain about incorrectly typed string unions as well and missing values. Is there another specific reason to use string enums over string unions? 


<!-- Sent from Reviewable.io -->

2022-03-07 15:35 UTC, jocrl commented
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwmriP9651XThaqc9ro:-Mx_-wIA2uzK1UhVrVwg:b-4lda05) ([raw file](https://github.com/cockroachdb/cockroach/blob/f76867ca721389758f650245358d9dfe68cf7a0f/pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx#L24)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

AFAIK most editors will be able to autocomplete string union types / will complain about incorrectly typed string unions as well and missing values. Is there another specific reason to use string enums over string unions? 
</blockquote></details>

My preference is that it makes PRs easier to read, when you don't have your editor 😛. But I'm down to shelve this till we write an RFC.


<!-- Sent from Reviewable.io -->

2022-03-07 18:35 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCI-hz0h2OxAEgE0Qg:-MxZpSJnBuahpHKCMbfP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx#L64)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

@xinhaoz `data` should be removed, `statement` should be used
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCGSFTBcfqyVkuNxTP:-MxZpjy48f0gvYWojUGM:bakcq9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsSection.tsx#L68)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Yay hooks! 🎉

**td;lr**
Hrrmm... @matthewtodd you might be interested in this as well. In summary, this is the same pattern that I flagged as concerning in the databases page PR, which is that it works by coincidence without using React state. That said, the databases page PR also sets the precedence that @xinhaoz you don't have to address this now, since with the exception of the corner case behavior (see the second section below), it works! It seems like @maryliag had good intuition when she suggested to show and tell on this 😄. I'm hoping to slowly lay some foundation and intuition for this across the next few show and tells. Having seen this twice, I will one day eventually write an RFC.

But if you're interested in this particular issue for now, here is my explanation.

**Explanation**
In a React app, React state should be used as the source of truth. This provides centralization and consistency that everything else can flow from: you update state, and React will take care of updating everything downstream that you've said is connected to it. Failure to put things in React state can cause corner case bugs where downstream things fail to update because you are working outside of the React system.

@azhng mentioned above that there are 2 things: "URL + localStorage". To be precise, it's more like "URL + Redux (which happens to be backed by local storage)". I would strongly say that the source of truth should be Redux (i.e. a type of React state, the other one being local component state), and that the URL should not be used as a "source of truth".

It helps to distinguish three things here. There's the:
(1) "initial/default sort selection", aka the "value to initialize state with"
(2) the "current sort selection", aka "current sort state", and 
(3) the "derivative of the current sort selection", aka "derivative of state"

Crucially, only (2) is actually state itself. (1) and (3) are not state. (1) is the value to initialize state with, and (3) reads from state. But they are not state.

I see the URL as
(1) the _initial_ sort selection
(3) a _derivative_ of the current sort selection

The Redux value under the `localStorage` key is
(2) the state

To illustrate things more, we can further distinguish that the Redux value under the `localStorage` key is not itself the browser local storage (https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). The Redux key is backed by local storage, which is to say that the existing implementation of the `LocalSetting` class encapsulates and automatically keeps the two in sync for you. With this in mind, the browser local storage _also should not be used as state_. The Redux value is the source of truth, so you would read from Redux value under the `localStorage` key. In contrast, one shouldn't read the sort value via `localStorage.getItem('whatever the key is');`.

I.e., the browser local storage is also
(1) the initial filter selection
(3) a _derivative_ of the current filter selection

but it is not (2) state.

**Corner case behavior**
I wrote that failure to put things in React state can cause corner case bugs due to working outside of the React system. This might not exactly be a bug, but it's probably undesired behavior and demonstrates what happens when you don't use React state.

The behavior in the fingerprint tables is probably what we want. To demonstrate:
- go to the statements fingerprints table, and click on one of the columns is set the sort, e.g. "Max Memory"
- go to the transaction fingerprints table, and click on "Contention" to sort
- go back to the statement fingerprints table. "Max Memory" should still be the sort
- and if you go back to the transaction fingerprints table, "Contention" should still be the short

If you do the same thing with the active statements/transactions tables, the sort will always be reset to the default sort. Note that this behavior, switching within the same page, is due to stay being put in React/Redux, and _not_ due to the persistence of local storage. The local storage should provide that the short will persist across browser tabs.

**How, concretely, to address this**
For addressing this issue, I'd suggest looking at how sort is handled in the existing statements page in `cluster-ui/src/statementsPage/statementsPage.tsx`. The sort state (2) is stored in Redux, and the component gets passed the [state](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L269) and the [setState](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L299) as props in the connection.

The state is initialized (1) [in the constructor](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L187) from the query params. An alternative to the `getStateFromHistory` would be to use the `useTableSortFromURL` introduced here 🙂.

And the query params are derived (3) from changing state in `componentDidUpdate`, [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L312).

Should the filter be shared with the fingerprints pages? If so, I would make sure to both read from and write to the same Redux state. If they should be independent, use different bits of redux state (I'm not great with redux vocabulary 😅).

**Side note**
It might seem like the appropriate solution here is unnecessary to do. Why add these layers of indirection, if it works? The same can be said for why use Redux instead of just vanilla React, since Redux further adds additional layers of indirection. It's an assessment of whether these layers of indirection are worth the benefits that these systems bring. And for us, we've decided that both are worth it. And so using React means actually using state 😉.
</blockquote></details>

Changed filters and sort setting to read from redux, which are in turn synced with the URL.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCJs_t-m9jvtNXDXwr:-MxZpqRr7RvjuRmc4QHa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L20)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

@xinhaoz oops, the filter was created but it was not used. So, use it :stuck_out_tongue: 
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 42 at r1](https://reviewable.io/reviews/c [...]

2022-03-08 16:51 UTC, jocrl requested changes
Thank you for this PR, and the changes! 😍

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-:-MxeR3qN3TzIBfj0lZqp:b-s5obqj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx, line 584 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Mxe6BacEHkO7wnMb4Ia:-Mxe6BacEHkO7wnMb4Ib:b2fz2d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx#L584)):*
> ```XML
>                   {timeLabel
>                     ? timeLabel
>                     : "Statement fingerprint runs longer than"}
> ```

nit: I think this can be simplified to `{timeLabel || "Statement fingerprint runs longer than"}`



_Code quote:_
```XML
                  {timeLabel
                    ? timeLabel
                    : "Statement fingerprint runs longer than"}
```
___
*[pkg/ui/workspaces/cluster-ui/src/queryFilter/utils.ts, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Mxe70SoEroCUwrkfU7A:-Mxe70SoEroCUwrkfU7B:b-15vasl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/queryFilter/utils.ts#L26)):*
> ```XML
>     }
> 
>     filters[key] = typeof param === "boolean" ? param === "true" : param;
> ```

nit: does this line work? `URLSearchParams.get` returns `string | null`



_Code quote:_
```XML
typeof param === "boolean" ? param === "true" : param;
```
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/activeStatementDetails.tsx, line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeDkn8DVdvQ46pHSI1:-MxeDkn8DVdvQ46pHSI2:b-fftunj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/statementDetails/activeStatementDetails.tsx#L57)):*
> ```XML
>       refreshSessions();
>     }
>   }, [refreshSessions, statement]);
> ```

Nice edge case handling!
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/activeStatementDetails.tsx, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeBSfM8p7wq_01DAU8:-MxeBSfN7gzbQMmlpxwa:b-4bw7s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/statementDetails/activeStatementDetails.tsx#L88)):*
> ```XML
>           </Col>
>         </Row>
>         {statement != null && (
> ```

nit: `{statement && ...component stuff}` is pretty common/I think more common syntax for conditional rendering



_Code quote:_
```XML
statement != null &&
```
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsView.tsx, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCDq3f79-Tffb3ePRf:-MxeEBlL6eaP62Qy__WK:b-f9axmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsView.tsx#L74)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

TIL: it's common practice in React to `useEffect` with the callback it uses 
</blockquote></details>

@xinhaoz, I like your `useEffect`s across the PR, and this polling! 🎉 Thank you also for making this stateful 😄

note to Archer: `useEffect` is what replaces the old `componentDidUpdate` 🙂. Xin Hao's clean up by returning is great, and it replaces the old `componentWillUnmount` :)
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsView.tsx, line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeOMB58o3K8lTm8tht:-MxeOMB58o3K8lTm8thu:b-l7hwg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsView.tsx#L185)):*
> ```XML
>         loading={statements == null}
>         page="active statements"
>         error={fetchError}
> ```

nit: could you please de-verbify this object 😅
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx, line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeI0MF74stBVgiUIb4:-MxeI0MF74stBVgiUIb5:b14s07n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx#L18)):*
> ```XML
> export type StatementsPageRootProps = {
>   activeQueriesView: React.ComponentType;
>   fingerprintsView: React.ComponentType;
> ```

Hmm, I find it curious that these two components are specified in their props instead of being hardcoded into this component. Was this from trying to reuse the existing connected components across DB and CC Consoles?

I feel like it's a strange way to do things given that `activeQueriesView` and `fingerprintsView` are not generic/arbitrary children to render, but pretty much hardcoded to one specific component, just differently connected. I feel like a cleaner solution would be to  connect this component, and hardcode the unconnected `ActiveStatementsView` and `StatementsPage` components in this one, passing along their props 🤔. That seems like a more similar solution to whats done with other pages and their sub-parts. WDYT?



_Code quote:_
```XML
  activeQueriesView: React.ComponentType;
  fingerprintsView: React.ComponentType;
```
___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeKVCr26CxvnS0uLjj:-MxeKVCr26CxvnS0uLjk:b9hsdqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx#L54)):*
> ```XML
>   useEffect(() => {
>     if (transaction == null) {
>       // Refresh sessions if the statement was not found initially.
> ```

nit: transaction



_Code quote:_
```XML
statement
```
___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeKncdEFFLpQV4n7yv:-MxeKncdEFFLpQV4n7yw:b-m80rsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx#L60)):*
> ```XML
> 
>   const returnToActiveTransactions = () => {
>     history.push("/sql-activity?tab=Transactions&view=active");
> ```

The equivalent code in the fingerprint details pages likely also needs to be modified to specify the tab. Currently, clicking the back for that leads to active transactions/statements.
There's a chance that after modifying `SQLActivityRootControls` to be stateful this will be solved if the user previously came from the table page. But modifying the push location will still be needed for if the user starts off loading their tab from the details page.
___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx, line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeLn6F5cDIAZFM58D0:-MxeLn6F5cDIAZFM58D1:bh82p3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx#L93)):*
> ```XML
>           </Col>
>         </Row>
>         {transaction != null && (
> ```

nit: `transaction && ...`



_Code quote:_
```XML
transaction != null &&
```
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/activeTransactionsView.tsx, line 99 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeMMZM2tnk1Cst0hI8:-MxeMMZM2tnk1Cst0hI9:b-dc0y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/ [...]

2022-03-08 18:39 UTC, Azhng reviewed
> Reviewed 2 of 11 files at r2, 12 of 35 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/queryFilter/utils.ts, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Mxe70SoEroCUwrkfU7A:-Mxemt6oDxZM2oD5F76z:bjtwzbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/queryFilter/utils.ts#L26)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: does this line work? `URLSearchParams.get` returns `string | null`
</blockquote></details>

Hmm, would it be a big deal if we just return an empty `Filters` instead of `null` in the case where URL doesn't contain any filters?
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsView.tsx, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCDq3f79-Tffb3ePRf:-Mxeo6GrD-ahRa36EK0B:bnjzbbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsView.tsx#L74)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

@xinhaoz, I like your `useEffect`s across the PR, and this polling! 🎉 Thank you also for making this stateful 😄

note to Archer: `useEffect` is what replaces the old `componentDidUpdate` 🙂. Xin Hao's clean up by returning is great, and it replaces the old `componentWillUnmount` :)
</blockquote></details>

:tada:


<!-- Sent from Reviewable.io -->

2022-03-08 19:59 UTC, maryliag reviewed
> Reviewed 12 of 55 files at r1, 2 of 11 files at r2, 12 of 35 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Mxf2E8QD0_xS1jYMXLz:-Mxf2E8R0OP7HJxKThfj:b2whzpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx#L110)):*
> ```XML
>       placement="bottom"
>       style="tableTitle"
>       content={<p>{/* TODO (xzhang)*/}</p>}
> ```

just adding a comment here so we can easily check if that was done before merging :)  (same for the ones below)
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsTable/activeStatementsTable.tsx, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Mxf2frf2jVupQnmmUZb:-Mxf2frf2jVupQnmmUZc:b4xoujv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsTable/activeStatementsTable.tsx#L52)):*
> ```XML
>       ),
>       sort: (item: ActiveStatement) => item.query,
>       alwaysShow: true,
> ```

the alwaysShow is used when we don't want the column to ever be hidden, so if you set this to true you won't see it on the column selectors. We usually set this just for the first column and the action column (when that one exists), so you can remove the values for all those column (the default is false, so you can remove the line completely). Make sure all columns (except first) are being shown on the column selector and also that the right selection are being done correctly.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsTable/activeTransactionsTable.tsx, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Mxf3gOVBmpmcuWIbaTB:-Mxf3gOVBmpmcuWIbaTC:bqecayk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsTable/activeTransactionsTable.tsx#L52)):*
> ```XML
>       ),
>       sort: (item: ActiveTransaction) => item.executionID,
>       alwaysShow: true,
> ```

same thing as above, only this column should have alwaysShow and remove from all others
___
*[pkg/ui/workspaces/cluster-ui/src/columnsSelector/utils.ts, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCN_Dx6ELMaY6YnGQZ:-Mxf4SHRBsg9gprGI3BH:bo8icu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/columnsSelector/utils.ts#L20)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Note this function was just lifted out of existing code and left unchanged. Going to avoid making further changes (aside from moving comments) to it in this PR so as to not potentially introduce any bugs, if that's okay.
</blockquote></details>

the alwaysShow value can be `true`, `false` or `undefined`, I think when it was undefined it was causing issues so I had to add the explicit check for `== true`. I can't remember exactly what was the issue.


<!-- Sent from Reviewable.io -->

2022-03-09 18:35 UTC, matthewtodd reviewed
Nice! This is a lot of work. I took a quick read through to catch up and just noticed a couple of places where you could use `map` on an array. Not really to the main point, I know! 😅

> Reviewed 21 of 55 files at r1, 4 of 11 files at r2, 29 of 35 files at r3, 7 of 7 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-:-MxjwspUByYyCa_zPD76:b-76p311)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 49 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxjtT1lDXwGPoLe4iRs:-MxjtT1lDXwGPoLe4iRt:b-965e60) ([raw file](https://github.com/cockroachdb/cockroach/blob/35478d4a7970ca553cb1936cfdff7256ab584eb7/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L49)):*
> ```XML
>   }
> 
>   sessionsResponse.sessions.forEach(session => {
> ```

nit: you can use [`flatMap`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) for things like this, if you like.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 133 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxjuAjq4A1L1M00gan5:-MxjuAjq4A1L1M00gan6:b8deh8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/35478d4a7970ca553cb1936cfdff7256ab584eb7/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L133)):*
> ```XML
>   });
> 
>   sessionsResponse.sessions.forEach(session => {
> ```

nit: maybe a `map` here?


<!-- Sent from Reviewable.io -->

2022-03-15 20:56 UTC, jocrl commented
___
*[pkg/ui/workspaces/cluster-ui/src/sqlActivityContentRoot/sqlActivityContentRoot.tsx, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MwCCGm63Uu3HU-Kixem:-MyEJzfc7roNodUJIPKQ:b5rsg45) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d62432e23f33e5c5f1406d90e3bbd1ab0cf007/pkg/ui/workspaces/cluster-ui/src/sqlActivityContentRoot/sqlActivityContentRoot.tsx#L24)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Hmm, regarding the query params comment, this component still doesn't have state. Is that in progress, or is the decision to shelve that for now?
</blockquote></details>

cc @matthewtodd as well

Offline, Xin Hao brought up that the `useLocation` hook here is plugged into React, and that the [documentation suggests](https://v5.reactrouter.com/web/api/Hooks/uselocation) that it can be thought of like useState. I think I have some lingering awkwardness with this pattern, but she pointed out that this seems to be a common pattern, and I yeah I change my opinion to agree with that.

There's a question of whether the selection should persist between route changes, and if so Xin Hao pointed out that it would need to be stored in redux.

But yeah, if the persistence behavior isn't needed, I see how this makes sense. TIL!


<!-- Sent from Reviewable.io -->

2022-03-16 19:20 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 49 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxjtT1lDXwGPoLe4iRs:-MxkBb4mBCuR9Ba1Bn40:b-82hzpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/35478d4a7970ca553cb1936cfdff7256ab584eb7/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L49)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: you can use [`flatMap`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) for things like this, if you like.
</blockquote></details>

Ah I tried putting a `flatMap` here but was notified it's an es2019 feature.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 133 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxjuAjq4A1L1M00gan5:-MxkBUbiDtNQ2l2mUjUH:b-su64ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/35478d4a7970ca553cb1936cfdff7256ab584eb7/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L133)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: maybe a `map` here?
</blockquote></details>

Good catch, added a filter to for null values.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsTable/activeStatementsTable.tsx, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Mxf2frf2jVupQnmmUZb:-MxkBpDp0SDtogzL4uFO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementsTable/activeStatementsTable.tsx#L52)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the alwaysShow is used when we don't want the column to ever be hidden, so if you set this to true you won't see it on the column selectors. We usually set this just for the first column and the action column (when that one exists), so you can remove the values for all those column (the default is false, so you can remove the line completely). Make sure all columns (except first) are being shown on the column selector and also that the right selection are being done correctly.
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsTable/activeTransactionsTable.tsx, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Mxf3gOVBmpmcuWIbaTB:-MxkBt9S2JviCk0VA595:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsTable/activeTransactionsTable.tsx#L52)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

same thing as above, only this column should have alwaysShow and remove from all others
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx, line 584 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Mxe6BacEHkO7wnMb4Ia:-MyDtOVrEkqrszNQszAG:b-wt2gd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx#L584)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: I think this can be simplified to `{timeLabel || "Statement fingerprint runs longer than"}`
</blockquote></details>

(Discussed offline) Not incorporating this change here as this code was included in the diff to due an indentation change.
___
*[pkg/ui/workspaces/cluster-ui/src/queryFilter/utils.ts, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Mxe70SoEroCUwrkfU7A:-MyDwXem7myJP0mUISf0:bqgjmqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/queryFilter/utils.ts#L26)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, would it be a big deal if we just return an empty `Filters` instead of `null` in the case where URL doesn't contain any filters?
</blockquote></details>

@jocrl Oof, nice catch. The typeof here should be from defaultFilters. Fixed.
@azhng I wanted a clear way to convey that there were no filters found (this function is used on page loads to see if the user specified filters at all, to propogaoe to redux). We can return an empty filters object as long as we maintain that we only set keys on the returned filter object if they are found in the URL (and not set to null for example). LMK which approach you prefer, and I can add a comment.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsView.tsx, line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeOMB58o3K8lTm8tht:-MyE4f560nmEZO5Pdbzz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsView.tsx#L185)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: could you please de-verbify this object 😅
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx, line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeI0MF74stBVgiUIb4:-MyDqGwy1ntCjf8o_Z_A:bguhabi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx#L18)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Hmm, I find it curious that these two components are specified in their props instead of being hardcoded into this component. Was this from trying to reuse the existing connected components across DB and CC Consoles?

I feel like it's a strange way to do things given that `activeQueriesView` and `fingerprintsView` are not generic/arbitrary children to render, but pretty much hardcoded to one specific component, just differently connected. I feel like a cleaner solution would be to  connect this component, and hardcode the unconnected `ActiveStatementsView` and `StatementsPage` components in this one, passing along their props 🤔. That seems like a more similar solution to whats done with other pages and their sub-parts. WDYT?
</blockquote></details>

(Fleshed out more offline). Done!
___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeKVCr26CxvnS0uLjj:-MyDqXfn08ZfuyV2tpFc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx#L54)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: transaction
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx, line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeKncdEFFLpQV4n7yv:-MyE4jqd6TmqAwHdzIEc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/cluster-ui/src/transactionDetails/activeTransactionDetails.tsx#L60)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

The equivalent code in the fingerprint details pages likely also needs to be modified to specify the tab. Currently, clicking the back for that leads to active transactions/statements.
Ther [...]

2022-03-16 20:48 UTC, matthewtodd reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts, line 49 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxjtT1lDXwGPoLe4iRs:-MyJU7ln8tpP0zChV4Fn:b-4fpuoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/35478d4a7970ca553cb1936cfdff7256ab584eb7/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts#L49)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Ah I tried putting a `flatMap` here but was notified it's an es2019 feature.
</blockquote></details>

Oh, bummer. Thanks for letting me know!


<!-- Sent from Reviewable.io -->

2022-03-23 14:37 UTC, maryliag requested changes
Awesome work on this one. A few questions:
- We mentioned there was a lot of space between the bullets selection and the filters. Did you decreased that space? Would be nice to see an image/video with the latest version of the page
- We also talked about maybe changing the order to be historical first and active second, did we ever got a final decision on that? cc @kevin-v-ngo 
- I would also recommend you do a rebase, I notice a few changes on some styles here that might be affected by some other recent PRs :) 

> Reviewed 1 of 11 files at r2, 2 of 35 files at r3, 1 of 7 files at r5, 4 of 11 files at r7, 1 of 10 files at r8, 1 of 1 files at r9, 2 of 6 files at r10, 16 of 28 files at r12, 2 of 3 files at r13, 21 of 22 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-:-MyrByNfApxw6GalsJkR:b-i3k3q8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsSection.tsx, line 85 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Myr6PGT6eP9qRut-hFQ:-Myr6PGT6eP9qRut-hFR:bs0t0h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsSection.tsx#L85)):*
> ```XML
>         renderNoResult={
>           <EmptyTransactionsPlaceholder
>             isEmptySearchResults={search?.length > 0 && transactions.length > 0}
> ```

why do we need the check if there is a search? what is the difference on the message between no results because there is no active transactions vs no results because nothing matches the search?
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx, line 45 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrB-kHBGaG9cRM9WgW:-MyrB-kHBGaG9cRM9WgX:b-dswgkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx#L45)):*
> ```XML
>           executed SQL transactions and their latencies.{" "}
>           <Link to={statementsSql}>Learn more</Link>
>           {/* TODO add 'Learn More' link to documentation page*/}
> ```

nit: don't forget this todo
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx, line 59 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrB2hg0QeYUTNOZ22A:-MyrB2hg0QeYUTNOZ22B:b-dswgkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx#L59)):*
> ```XML
>           application or elapsed time, to understand and tune workload
>           performance.
>           {/* TODO add 'Learn More' link to documentation page*/}
> ```

nit: don't forget this todo


<!-- Sent from Reviewable.io -->

2022-03-23 15:32 UTC, xinhaoz commented
@kevin-v-ngo @maryliag 
All the changes requested have been made already, I'm in the process of updating the Loom to show this. For the TODO on adding the link, I'm not sure that it exists yet cc @kevin-v-ngo to confirm. If it doesn't exist yet, I can file a ticket and it to the TODO.

2022-03-23 22:05 UTC, jocrl reviewed
Looks great; thank you! For our synchronous discussions as well 😄

Three minor nits on the new changes, and otherwise everything looks good to me!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-:-MysnUAY5HfOo3tV8fHp:b-td68xy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @jocrl, @kevin-v-ngo, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx, line 100 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrErziA3pkxZqBb7Ul:-MyrErziA3pkxZqBb7Um:b-icyvak) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx#L100)):*
> ```XML
>           &ldquo;Preparing&rdquo;, the {execType} is being parsed and planned.
>           If &ldquo;Executing&rdquo;, the {execType} is currently being
>           executed.
> ```

nit: instead of using `&apos;`, it might be clearer to read what the symbols are if they were escaped with other string markers?

as in, sub with
```
          {`The status of the ${execType}'s execution. If
          “Preparing”, the ${execType} is being parsed and planned.
          If “Executing”;, the ${execType} is currently being
          executed.`}
```



_Code quote:_
```XML
          The status of the {execType}&apos;s execution. If
          &ldquo;Preparing&rdquo;, the {execType} is being parsed and planned.
          If &ldquo;Executing&rdquo;, the {execType} is currently being
          executed.
```
___
*[pkg/ui/workspaces/cluster-ui/src/selectWithDescription/selectWithDescription.tsx, line 25 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrCh4-3nqaSm-iT-_w:-MyrCh4-3nqaSm-iT-_x:b-9t6jdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/selectWithDescription/selectWithDescription.tsx#L25)):*
> ```XML
>   value: string;
>   label: string;
>   description: React.ReactNode;
> ```

nit: would this work with `ReactChild` instead of `ReactNode`? Per these guidelines https://github.com/cockroachlabs/managed-service/blob/master/docs/frontend-codereview-guide.md#prop-typing
___
*[pkg/ui/workspaces/db-console/src/views/transactions/activeTransactionsSelectors.tsx, line 30 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrG7yHBgirZNADP8Ui:-MyrG7yHBgirZNADP8Uj:bxz6c4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/db-console/src/views/transactions/activeTransactionsSelectors.tsx#L30)):*
> ```XML
>     state?: CachedDataReducerState<SessionsResponseMessage>,
>   ): ActiveTransaction[] => {
>     if (state?.data == null) return [];
> ```

nit: if you're doing `?.` chaining, not having `state` will return `undefined`. Do you also want to include that `undefined` case in this block (i.e., a broader falsy check and not just for `== null`)?


<!-- Sent from Reviewable.io -->

2022-03-23 22:16 UTC, kevin-v-ngo commented
> 

Thanks! CC @Annebirzin as well.

2022-03-23 22:35 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @jocrl, @kevin-v-ngo, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsSection.tsx, line 85 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-Myr6PGT6eP9qRut-hFQ:-Mystu3S1gFLe4l-xE1c:b-7m8jcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsSection.tsx#L85)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why do we need the check if there is a search? what is the difference on the message between no results because there is no active transactions vs no results because nothing matches the search?
</blockquote></details>

There is a different message for if it is empty due to a search filter. It was part of the component design prior to this change.
___
*[pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx, line 100 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrErziA3pkxZqBb7Ul:-Mysu7FuAKtFLZU80KnR:bz5py0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx#L100)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: instead of using `&apos;`, it might be clearer to read what the symbols are if they were escaped with other string markers?

as in, sub with
```
          {`The status of the ${execType}'s execution. If
          “Preparing”, the ${execType} is being parsed and planned.
          If “Executing”;, the ${execType} is currently being
          executed.`}
```
</blockquote></details>

Good idea! Done.
___
*[pkg/ui/workspaces/cluster-ui/src/selectWithDescription/selectWithDescription.tsx, line 25 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrCh4-3nqaSm-iT-_w:-Mysu9uU2aprWb78Q3qZ:b-fuvevh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/selectWithDescription/selectWithDescription.tsx#L25)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: would this work with `ReactChild` instead of `ReactNode`? Per these guidelines https://github.com/cockroachlabs/managed-service/blob/master/docs/frontend-codereview-guide.md#prop-typing
</blockquote></details>

Just checked and `ReactChild` works here. Done!
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx, line 45 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrB-kHBGaG9cRM9WgW:-MysuK9e9hIjQqUy4JWP:b-8fh777) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx#L45)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: don't forget this todo
</blockquote></details>

Filed a new followup issue.
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx, line 59 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrB2hg0QeYUTNOZ22A:-MysuOrc0XHr9dJTcifu:bf16mfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx#L59)):*
<details><summary><i>Previously, kevin-v-ngo wrote…</i></summary><blockquote>

Yeah we [decided to swap the order](https://docs.google.com/document/d/1gwjmM__cGpvaH7aKnEsx9s-thBXG7efB3W5xKkALt6o/edit?usp=sharing). Was that not done? 
</blockquote></details>

Filed a followup issue for the link.
___
*[pkg/ui/workspaces/db-console/src/views/transactions/activeTransactionsSelectors.tsx, line 30 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrG7yHBgirZNADP8Ui:-MysuTqxD1S-DZHM7ARK:b-n4lmrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/db-console/src/views/transactions/activeTransactionsSelectors.tsx#L30)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: if you're doing `?.` chaining, not having `state` will return `undefined`. Do you also want to include that `undefined` case in this block (i.e., a broader falsy check and not just for `== null`)?
</blockquote></details>

AFAIK `== null` checks for nullish, i.e. null and undefined, so that case should work here.


<!-- Sent from Reviewable.io -->

2022-03-23 22:44 UTC, Annebirzin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-:-Myswz7F2IdY3ILzFcx_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @jocrl, @kevin-v-ngo, @maryliag, @matthewtodd, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2022-03-24 13:50 UTC, maryliag reviewed
New UI looks great! Just a small nit from me. Also, would you mind adding a pic of how it looks when you expand the Description part of the bullets?

> Reviewed 1 of 22 files at r14, 1 of 4 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-:-MywB7RYEyzHdwJ2ll6F:b-dkaw2i)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @jocrl, @kevin-v-ngo, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx, line 45 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MywAMWE7tNni90_ISbu:-MywAMWE7tNni90_ISbv:b-sndvk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd1f1e650efaed0130a260e3d5f2a3031a757c9/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx#L45)):*
> ```XML
>           with underscores (_).\nThis can help you quickly identify
>           frequently executed SQL statements and their latencies.`}
>           <Link to={statementsSql}>Learn more</Link>
> ```

For `Learn More` we have been using Anchor (that already has the class with the right blue and target _blank), so you can use that one here
`<Anchor href={statementsSql}>Learn More</Anchor>`
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx, line 45 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrB-kHBGaG9cRM9WgW:-MywAtYpCV0jvwzhbliG:bmahjv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx#L45)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Filed a new followup issue.
</blockquote></details>

Same comment as above, replace by `<Anchor href={statementsSql}>Learn More</Anchor>`


<!-- Sent from Reviewable.io -->

2022-03-24 14:28 UTC, jocrl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @jocrl, @kevin-v-ngo, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/selectWithDescription/selectWithDescription.tsx, line 25 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrCh4-3nqaSm-iT-_w:-MywJZKsAMCkzBeY7NzQ:b-ag48fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/selectWithDescription/selectWithDescription.tsx#L25)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Just checked and `ReactChild` works here. Done!
</blockquote></details>

Great! Could you also modify the one on line 49, then?
```
const getDescription = (): React.ReactNode => {
```
___
*[pkg/ui/workspaces/db-console/src/views/transactions/activeTransactionsSelectors.tsx, line 30 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrG7yHBgirZNADP8Ui:-MywJtyg92Ll4Uz2k4OV:b-6bi5iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/db-console/src/views/transactions/activeTransactionsSelectors.tsx#L30)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

AFAIK `== null` checks for nullish, i.e. null and undefined, so that case should work here.
</blockquote></details>

TIL. Thanks!

![image.png](https://files.reviewableusercontent.io/images/reviewable/91907326/d4mtZEMb48MSBEV3lSCCClIv/image.png)


<!-- Sent from Reviewable.io -->

2022-03-24 15:33 UTC, kevin-v-ngo approved these changes
Looks good! For now, let's remove "Learn more" until we have the docs ready for this page. I'll create a separate issue to track it.

2022-03-24 19:13 UTC, jocrl commented
___
*[pkg/ui/workspaces/db-console/src/views/statements/activeStatementDetails.tsx, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeP_6X7jPJTwLj0YGL:-MyxLA23DitcBEJKBhyJ:bzg3b3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/db-console/src/views/statements/activeStatementDetails.tsx#L1)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ah - is this just me with reviewable, or does this not look done?


<!-- Sent from Reviewable.io -->

2022-03-24 20:22 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @jocrl, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/selectWithDescription/selectWithDescription.tsx, line 25 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrCh4-3nqaSm-iT-_w:-Myx_qT1Bsf6XJ8_NmBS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/selectWithDescription/selectWithDescription.tsx#L25)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Great! Could you also modify the one on line 49, then?
```
const getDescription = (): React.ReactNode => {
```
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx, line 45 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MywAMWE7tNni90_ISbu:-Myx_sCs6o2EoLoDFJKZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd1f1e650efaed0130a260e3d5f2a3031a757c9/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageRoot.tsx#L45)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

For `Learn More` we have been using Anchor (that already has the class with the right blue and target _blank), so you can use that one here
`<Anchor href={statementsSql}>Learn More</Anchor>`
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx, line 45 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MyrB-kHBGaG9cRM9WgW:-Myx_uHd9H4BZmr67F2g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f296650ed3ec3f12b113cd125f6f81be4e8bc387/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageRoot.tsx#L45)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Same comment as above, replace by `<Anchor href={statementsSql}>Learn More</Anchor>`
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/statements/activeStatementDetails.tsx, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-MxeP_6X7jPJTwLj0YGL:-Myx_w2NC5uO91kZlsdS:btrdczn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f30eebf72f398972f8b2367d1b20b2ef53e4b8/pkg/ui/workspaces/db-console/src/views/statements/activeStatementDetails.tsx#L1)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Ah - is this just me with reviewable, or does this not look done?
</blockquote></details>

Oops my bad, I did this for the other PR but not here. Done.


<!-- Sent from Reviewable.io -->

2022-03-24 21:03 UTC, jocrl approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 🎉🎉

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-:-Myxj7f59fS-K-giseRC:btn5cjx)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @jocrl, @maryliag, @matthewtodd, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2022-03-24 22:11 UTC, maryliag approved these changes
Awesome job on this one! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 6 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76753#-:-Myxysr_DSb5joLQYxXl:bb2trw5)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @jocrl, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2022-03-28 14:18 UTC, xinhaoz commented
Thanks for the review, all!
bors r+

2022-03-28 15:24 UTC, merged