storage: add `MVCCStats` for range keys
cockroachdb/cockroach pull request #76860
Opened 2022-02-21 17:43 UTC by erikgrinaker

Only the last 2 commits should be reviewed here, the others are from #76131 and #76783.

---

**storage: split out MVCCRangeKeyDefragmenter** 

This patch split out `MVCCRangeKeyDefragmenter` from
`MVCCRangeKeyIterator`. Keeping defragmentation separate from the
iterator allows for ad hoc range key defragmentation in other contexts,
e.g. during combined point/range key iteration.

Release note: None

**storage: add MVCCStats for range keys**

This patch adds `MVCCStats` tracking for range keys. It only considers
range tombstones for now, since the semantics of other range keys are
still unclear (e.g. how should overlapping range keys be interpreted?),
and will error if encountering non-tombstone range keys.

Two new fields are added to `MVCCStats`:

* `RangeKeyCount`: the number of individual defragmented logical range
  keys, regardless of any overlap with other range keys. Multiple versions
  count as separate range keys, even if they overlap exactly.

* `RangeKeyBytes`: the logical encoded byte size of all range keys,
  excluding value. This ignores fragmentation, and counts the key bounds
  separately for each version even if multiple range keys overlap exactly.
  Unlike point keys, which for historical reasons use a fixed-size
  timestamp contribution, this uses the actual variable-length timestamp
  encoding contribution.

`ComputeStatsForRange()` has been extended to calculate the above
quantities, and additionally account for range tombstones themselves in
`GCBytesAge` along with their effect on point keys.  However, these
statistics are not yet updated during range key mutations and GC, nor on
CRDB range splits and merges -- this will be addressed separately. All
relevant call sites have been updated to surface range keys for the MVCC
iterators passed to `ComputeStatsForRange()`.

Touches #70412.

Release note: None

2022-02-21 17:43 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76860)
<!-- Reviewable:end -->

2022-02-22 20:09 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76860)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @jbowens)

___
*[pkg/storage/enginepb/mvcc.proto, line 209 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76860#-MwY26lv4UWq3uk4y2Ek:-MwY26lv4UWq3uk4y2El:b-574ar9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d58c6b4ab4523e967abb1c46f9ac33c47e979190/pkg/storage/enginepb/mvcc.proto#L209)):*
> ```protobuf
>   // range key (assuming they have the same value). However, a range key that
>   // straddles a range split boundary will become two separate logical range
>   // keys (one in each range), and merge back to one when the ranges merge.
> ```

(drive by comment)
We currently sum the stats on a merge, as you are well aware.
I didn't spot the change in cmd_end_transaction.go to recompute these.
What did I miss?


<!-- Sent from Reviewable.io -->

2022-02-22 20:13 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76860)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @jbowens, and @sumeerbhola)

___
*[pkg/storage/enginepb/mvcc.proto, line 209 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/76860#-MwY26lv4UWq3uk4y2Ek:-MwY2sCFEgqnmggDcR94:b-92veaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d58c6b4ab4523e967abb1c46f9ac33c47e979190/pkg/storage/enginepb/mvcc.proto#L209)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(drive by comment)
We currently sum the stats on a merge, as you are well aware.
I didn't spot the change in cmd_end_transaction.go to recompute these.
What did I miss?
</blockquote></details>

Correct. These stats are not updated anywhere, including on range splits/merges or range key mutations -- this PR only implements the new stats quantities and accounts for them in `ComputeStatsForRange()` as a first step. Updates elsewhere will be addressed separately. For range splits/merges, that will require scanning range keys that straddle the split point and split/merge them accordingly.


<!-- Sent from Reviewable.io -->

2022-03-18 15:57 UTC, erikgrinaker commented
Closed in favor of #78085.

2022-03-18 15:57 UTC, closed without merging