opt: split filtered SELECT..ORDER BY..LIMIT into unioned SELECTs
cockroachdb/cockroach pull request #76893
Opened 2022-02-22 16:57 UTC by msirek

This commit adds a cost-based optimizer rewrite of queries of the form
```
SELECT * FROM t1 WHERE filter_expression ORDER BY secondIndexColumn LIMIT n;
```
where `filter_expression` is any boolean predicate on t1.
secondIndexColumn is the 2nd column defined in an index on t1, and `n`
is a positive integer. Equality or range predicates must exist on the
first index column, either explicitly in `filter_expression`, or
implicitly in a NOT NULL CHECK constraint, e.g. `index_col1 IN (1,2,3)`.
Given this example CHECK constraint, the rewritten query is of the form:
```
SELECT * FROM (
    SELECT * FROM t1 WHERE index_col1 = 1 AND filter_expression LIMIT n
    UNION ALL
    SELECT * FROM t1 WHERE index_col1 = 2 AND filter_expression LIMIT n
    UNION ALL
    SELECT * FROM t1 WHERE index_col1 = 3 AND filter_expression LIMIT n
) LIMIT n;
```
The ORDER BY is not needed because the required ordering is saved in the
outer LIMIT expression tree node which instructs the execution engine to
stitch together the UNION ALL branch results in order.

This commit builds statistics from NOT NULL CHECK constraints on virtual
columns which are of the form `column IN (const_1, const_2, ...)`. This
is needed because statistics cannot currently be created on virtual
columns, and the above query rewrite may not occur without these stats.

This commit also changes the structure of the UNION ALL tree built by
this and similar rewrites from left-deep to balanced, providing order of
magnitude speedup for cases which have high numbers of scans, for
example, hash-sharded primary key tables with a large number of buckets.

Fixes #75288

Release note (Performance Improvement): Queries of the form
`SELECT * FROM t1 WHERE filter_expression ORDER BY secondIndexColumn LIMIT n;`
where there is a NOT NULL CHECK constraint of the form:
`CHECK (firstIndexColumn IN (const_1, const_2, const_3...)`
may now be rewritten as a UNION ALL `skip scan` to avoid the
previously-required sort operation.

2022-02-22 16:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76893)
<!-- Reviewable:end -->

2022-02-23 00:26 UTC, michae2 requested changes
Very cool! I left some comments about the statistics building part, it looks great. My understanding of the optimizer is weak so I'll let someone else review the actual exploration rule! :slightly_smiling_face:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-MwYxfdmAOGSW8Cy-N2i:b-oueyh7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 4266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYnUe20BcjI9o8GImJ:-MwYn7GhEYTJW-wDwUUo:b32mjot) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4266)):*
> ```Go
> 			}
> 			datum := ExtractConstDatum(tuples.Elems[j])
> 			values[j] = datum
> ```

Is it possible for `NULL` to be one of these values? Or do we enforce that the column is non-nullable somewhere?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYqO2234Kw6iPOP9mK:-MwYkMpY-Iup_e4r63lG:b-qeb8wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4284)):*
> ```Go
> 			// Each value from the IN list is a sample value.
> 			// Give each sample value its own bucket with even distribution.
> 			h, err := stats.EquiDepthHistogram(sb.evalCtx,
> ```

nit: If `EquiDepthHistogram` didn't call `histogram.toHistogramData` at the end, then you wouldn't need the call to `DecodeHistogramBuckets` down below (assuming `NullCount` is always zero). It might be worth refactoring `EquiDepthHistogram` for this.

I don't think this refactor would be too hard (there's only one other caller of `EquiDepthHistogram`) but it would probably require exporting the `stats.histogram` type (maybe it would be better to move that type to `pkg/sql/opt/cat/table.go` and change the methods in `pkg/sql/stats/histogram.go` to functions?) so I understand if you don't want to.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4318 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYt1pQ3csDnQ0_iP11:-MwYpHls68MJwDh_uhJ9:bay0os2) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4318)):*
> ```Go
> 						RowCount:      rowCount,
> 						DistinctCount: uint64(numValues),
> 						NullCount:     0, // This is a non-null check constraint
> ```

Do we enforce this somewhere? If `NullCount` is always 0 then it seems like `DecodeHistogramBuckets` could be a function on a `HistogramData` that returns `[]cat.HistogramBucket` saving us from having to create the fake `TableStatistic`. (But it would also be nice to get rid of the call to `DecodeHistogramBuckets` altogether, see other comment.)


<!-- Sent from Reviewable.io -->

2022-02-23 00:39 UTC, mgartner reviewed
I haven't had a chance to go through the whole thing, but thought I'd leave some comments for now so you're not blocked.

> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-MwZ03D0-6WVqKDyWeJd:bvnxl9j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 4221 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYd9AWDh86x9yWez-8:-MwYd9AWDh86x9yWez-9:b-y7ao6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4221)):*
> ```Go
> // exist, the optimizer_use_histograms session setting is on, and the IN list
> // column is not invertable, then an EquiDepthHistogram is built for the IN list
> // values with an even data distribution.
> ```

What is the value of synthesizing histograms with even distributions? Wouldn't the non-histogram calculation based on `distinct_count` and `row_count` yield a similar estimate?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYdlBm-7QkU1rgy5mN:-MwYdlBm-7QkU1rgy5mO:b-cnbtw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4252)):*
> ```Go
> 		colID := column.Col
> 		var cols opt.ColSet
> 		cols.Add(colID)
> ```

nit: You could use `cols := opt.MakeColSet(colID)` here.
___
*[pkg/sql/opt/xform/general_funcs.go, line 391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYgOZrEJZ9jlAaUwhK:-MwYgOZrEJZ9jlAaUwhL:b-ipn8ib) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L391)):*
> ```Go
> 	// for example, introduce new operation types like "SkipScanExpr",
> 	// "SkipSelectExpr", "LooseScanExpr", "LooseSelectExpr" (see
> 	// https://wiki.postgresql.org/wiki/Loose_indexscan and
> ```

nit: Everything from "Is there a more efficient ..." onward reads like a TODO, so maybe convert it into a `TODO(msirek): ...`.

A loose index scan would be a great tool for these types of queries. :+1: 
___
*[pkg/sql/opt/xform/general_funcs.go, line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYgyK6-E7_tDDJaoMa:-MwYgyK6-E7_tDDJaoMb:b-sx8fik) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L397)):*
> ```Go
> 	// need for large UNION ALL expressions.
> 	//
> 	// We may want to lift this max entirely at some point.
> ```

nit: You could make this a separate TODO.
___
*[pkg/sql/opt/xform/general_funcs.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYh3MREi_NOWwSf6su:-MwYh3MREi_NOWwSf6sv:b-prxt79) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L398)):*
> ```Go
> 	//
> 	// We may want to lift this max entirely at some point.
> 	maxScanCount := 256
> ```

We might want to consider adding a cluster and sesssion setting for changing this maximum. This would give use flexibility and a backup plan in case it doesn't work for a particular user.

My hunch is that 16 -> 256 is a pretty large increase, too. If we add a setting I think we could be more conservative. It's unfortunate that we don't have telemetry data for bucket counts in the wild. I've asked around to see how many bucket counts are used by a particular high volume customer. I'll report back if I hear what bucket count they use.
___
*[pkg/sql/opt/xform/general_funcs.go, line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYehKs6scTt_2RS0CQ:-MwYehKs6scTt_2RS0CR:b-47ml1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L464)):*
> ```Go
> 	newHardLimit := memo.MakeScanLimit(int64(limit), reverse)
> 	// With a filter we might have to scan all rows before reaching the LIMIT.
> 	if filters != nil {
> ```

nit: You can use `!filters.IsTrue()` which does a slightly more robust check of `len(filters) == 0`, which is true for both `nil` and empty filters.
___
*[pkg/sql/opt/xform/general_funcs.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYlcZn5IN7B2Ai4_C-:-MwYlcZn5IN7B2Ai4_C0:b9sslvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L515)):*
> ```Go
> 
> 	// Make the UNION ALLs as a balanced binary tree. This performs better for
> 	// large numbers of spans than a left-deep tree.
> ```

I was thinking this might be simpler to implement as a normalization rule that would fire when `ConstructUnionAll` is called above. I thought something like this would work:

```
(UnionAll
    (UnionAll
        (UnionAll $a:* $b:*)
        $c:*
    $d:*
)
=>
(UnionAll
    (UnionAll $b $c)
    (UnionAll $d $a)
)
```

But I think you'd need multiple rules, and some way to know the depth of the tree.

This balancing is pretty tricky to get correct. It might be nice to contain this logic in a struct called something like `balancedUnionAllBuilder` which provide a simple API and encapsulate the complexity. Unit testing it might be nice too. If you'd prefer to do this in a separate commit/PR, you can leaving the balancing out of this commit for now.
    


<!-- Sent from Reviewable.io -->

2022-02-23 15:40 UTC, mgartner commented
___
*[pkg/sql/opt/xform/general_funcs.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYh3MREi_NOWwSf6su:-MwbDtWQ6NkF7L_K0y64:bg6kfxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L398)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We might want to consider adding a cluster and sesssion setting for changing this maximum. This would give use flexibility and a backup plan in case it doesn't work for a particular user.

My hunch is that 16 -> 256 is a pretty large increase, too. If we add a setting I think we could be more conservative. It's unfortunate that we don't have telemetry data for bucket counts in the wild. I've asked around to see how many bucket counts are used by a particular high volume customer. I'll report back if I hear what bucket count they use.
</blockquote></details>

Just heard back - the customer uses hash-sharded indexes with 64 buckets, which supports raising the maximum to at least that.


<!-- Sent from Reviewable.io -->

2022-02-23 16:59 UTC, msirek reviewed
Thank you both.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-Mw_6rIC3sUv_19X-ii4:b-srtiwf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @msirek, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 4221 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYd9AWDh86x9yWez-8:-Mw_6ygX4K45yn23Yxum:bb6gqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4221)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What is the value of synthesizing histograms with even distributions? Wouldn't the non-histogram calculation based on `distinct_count` and `row_count` yield a similar estimate?
</blockquote></details>

With a histogram we have exact values, so if we have a histogram built from `CHECK (a IN (1,2,3,4))` combined with `WHERE a > 3` we will be able to find the exact overlap between the predicate range and the histogram values to get a more accurate selectivity estimate.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYnUe20BcjI9o8GImJ:-Mw_7ZapEyvgVa_q-AFA:b-837w8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4266)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is it possible for `NULL` to be one of these values? Or do we enforce that the column is non-nullable somewhere?
</blockquote></details>

Conveniently the `Constraints` stored in TabMeta are only those check constraints which cannot ever evaluate to null.  In case of an `IN` check constraint on a nullable column, nothing will be stored here.
https://github.com/cockroachdb/cockroach/blob/2fdd9aebb4315f73b4e78e804dd718194b37ffed/pkg/sql/opt/table_meta.go#L143-L152

Likewise if you include a null value in the `IN` list, that check constraint would not appear here, e.g.:
`create table t3 (a int not null check (a in (1,2,3,null)));`
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYqO2234Kw6iPOP9mK:-Mwb9zPw53rPnGzynNmK:b2gfdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4284)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: If `EquiDepthHistogram` didn't call `histogram.toHistogramData` at the end, then you wouldn't need the call to `DecodeHistogramBuckets` down below (assuming `NullCount` is always zero). It might be worth refactoring `EquiDepthHistogram` for this.

I don't think this refactor would be too hard (there's only one other caller of `EquiDepthHistogram`) but it would probably require exporting the `stats.histogram` type (maybe it would be better to move that type to `pkg/sql/opt/cat/table.go` and change the methods in `pkg/sql/stats/histogram.go` to functions?) so I understand if you don't want to.
</blockquote></details>

Great point!, the unencoded buckets are available inside `EquiDepthHistogram`.  Since the encoding done inside `EquiDepthHistogram` is needed to calculate average row size here:
https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4297-L4301
We don't actually want to skip encoding.  I'v added the unencoded buckets as an additional return value from `EquiDepthHistogram`, so decoding can be skipped.  How does that look?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4318 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYt1pQ3csDnQ0_iP11:-MwbCRdUBFepHIn5Sa09:b-c3s0pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4318)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Do we enforce this somewhere? If `NullCount` is always 0 then it seems like `DecodeHistogramBuckets` could be a function on a `HistogramData` that returns `[]cat.HistogramBucket` saving us from having to create the fake `TableStatistic`. (But it would also be nice to get rid of the call to `DecodeHistogramBuckets` altogether, see other comment.)
</blockquote></details>

Yes, per my previous response we know all histogram values are non-null. I've removed the fake `TableStatistic` and the call to `DecodeHistogramBuckets`.
___
*[pkg/sql/opt/xform/general_funcs.go, line 391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYgOZrEJZ9jlAaUwhK:-MwbDSjEDGtxfgHVOCpl:bakan9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L391)):*
> TODO(msirek):
Thanks, converted it to a TODO.
___
*[pkg/sql/opt/xform/general_funcs.go, line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYgyK6-E7_tDDJaoMa:-MwbD_Ha-TtbgEZs8VA6:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L397)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: You could make this a separate TODO.
</blockquote></details>

Done
___
*[pkg/sql/opt/xform/general_funcs.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYh3MREi_NOWwSf6su:-MwbDoGDAEMW6ILwRuk5:b-21rlax) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L398)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Just heard back - the customer uses hash-sharded indexes with 64 buckets, which supports raising the maximum to at least that.
</blockquote></details>

I think the initial limit of 16 was related to poor performance seen with left-depth UNION ALL expressions that were too deep. Using a balanced tree structure brings the performance on-par with TopK when sorting/reading the entire table.  For tables with an IN list check constraint, we do bump up the maxScanCount to at least the size of the IN list:
https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L403-L410

So, if we want to be more conservative, one option is to keep the default value low, and then it would only then get bumped up for hash-sharded tables or regional partitioned tables.  Or, I could add cluster/session settings.  What do you think?
___
*[pkg/sql/opt/xform/general_funcs.go, line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYehKs6scTt_2RS0CQ:-MwbHBDG5mShOGJ-Ujmx:b3efq2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L464)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: You can use `!filters.IsTrue()` which does a slightly more robust check of `len(filters) == 0`, which is true for both `nil` and empty filters.
</blockquote></details>

Thanks!  Changed all occurrences.



_Code quote:_
```Go
With a filter we might have to scan all rows before reaching the LIMIT
```
___
*[pkg/sql/opt/xform/general_funcs.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYlcZn5IN7B2Ai4_C-:-MwbHxrC-ge0-gioz71N:b-7rfqd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L515)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I was thinking this might be simpler to implement as a normalization rule that would fire when `ConstructUnionAll` is calle [...]

2022-02-23 17:48 UTC, michae2 reviewed
> Reviewed 1 of 9 files at r1, 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 4266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYnUe20BcjI9o8GImJ:-MwbfK6D7DjhpDJOcxBo:b-83v4r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4266)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Conveniently the `Constraints` stored in TabMeta are only those check constraints which cannot ever evaluate to null.  In case of an `IN` check constraint on a nullable column, nothing will be stored here.
https://github.com/cockroachdb/cockroach/blob/2fdd9aebb4315f73b4e78e804dd718194b37ffed/pkg/sql/opt/table_meta.go#L143-L152

Likewise if you include a null value in the `IN` list, that check constraint would not appear here, e.g.:
`create table t3 (a int not null check (a in (1,2,3,null)));`
</blockquote></details>

Neat!
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYqO2234Kw6iPOP9mK:-MwbbN5R6baYAMa5XSNu:bn206ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4284)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Great point!, the unencoded buckets are available inside `EquiDepthHistogram`.  Since the encoding done inside `EquiDepthHistogram` is needed to calculate average row size here:
https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4297-L4301
We don't actually want to skip encoding.  I'v added the unencoded buckets as an additional return value from `EquiDepthHistogram`, so decoding can be skipped.  How does that look?
</blockquote></details>

Looks good! Thank you!
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4318 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYt1pQ3csDnQ0_iP11:-MwbbRUxC4-ZxlvyhE6p:btojbfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4318)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Yes, per my previous response we know all histogram values are non-null. I've removed the fake `TableStatistic` and the call to `DecodeHistogramBuckets`.
</blockquote></details>

Great!


<!-- Sent from Reviewable.io -->

2022-02-23 17:49 UTC, michae2 reviewed
The statistics parts LGTM. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-Mwbgxki9JC__f_fsw0h:b8763qh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)



<!-- Sent from Reviewable.io -->

2022-02-23 18:02 UTC, msirek reviewed
@michae2  Thank you.  Avoiding every bit of unnecessary work is helpful.  I'm glad you found out we don't need to decode the histogram.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-MwbjGi4CMMEC6M9ry7M:b-2w2kvm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)



<!-- Sent from Reviewable.io -->

2022-02-25 16:55 UTC, mgartner reviewed
> Reviewed 6 of 9 files at r1, 10 of 12 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 4221 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYd9AWDh86x9yWez-8:-MwlPpIwBbHR1eWJiVg4:bg8j4ma) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4221)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

With a histogram we have exact values, so if we have a histogram built from `CHECK (a IN (1,2,3,4))` combined with `WHERE a > 3` we will be able to find the exact overlap between the predicate range and the histogram values to get a more accurate selectivity estimate.
</blockquote></details>

Thanks. I see now that it's helpful with inequality expressions. :+1: 
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4309 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwlQs2p3_OOEbR3MLKi:-MwlQs2p3_OOEbR3MLKj:b16w66x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea90f8eb94b616d53f536985dc0fdc45a17b4dc5/pkg/sql/opt/memo/statistics_builder.go#L4309)):*
> ```Go
> 				histogram = unencodedBuckets
> 				distinctCount = max(float64(numValues), 1)
> 				nullCount = float64(0)
> ```

CHECK constraints allow NULL values:

```
defaultdb> CREATE TABLE t (a INT, CHECK (a IN (1, 2, 3)));
CREATE TABLE

defaultdb> INSERT INTO t VALUES (NULL);
INSERT 1

defaultdb> SELECT * FROM t;
   a
--------
  NULL
(1 row)
```

I'm not sure what else we could do here when there isn't a `NOT NULL` constraint on the column. Do you think that assuming a null count of zero will cause bad plans if a large percentage of values are actually NULL?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4329 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwlRtf91bCU9uaLIRk_:-MwlRtf91bCU9uaLIRka:b-iyu85e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea90f8eb94b616d53f536985dc0fdc45a17b4dc5/pkg/sql/opt/memo/statistics_builder.go#L4329)):*
> ```Go
> 		// Make the actual stats entry in statistics.ColStats that can be looked up
> 		// via a ColSet.
> 		if colStat, ok := statistics.ColStats.Add(cols); ok {
> ```

nit: this code might be simpler with some helper functions for the average size and using an inverse of`skipHistogram`, like: 

```go
distinctCount := max(float64(numValues, 1))
nullCount := float64(0)
if useHistogram {
    encodedHistogram, unencodedBuckets, err := stats.EquiDepthHistogram(
        sb.evalCtx,
        dataType,
        values, /* samples */
        numRows,
        int64(numValues), /* distinctCount */
        numValues,        /* maxBuckets */
    )
    // This shouldn't error out ...
    if err == nil {
        // ...
        avgSize = avgSizeFromEncodedHistogram(...)
    }
)
if avgSize == 0 {
    avgSize = avgSizeFromDatums(...)
}
// ...
````
   
___
*[pkg/sql/opt/xform/general_funcs.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYh3MREi_NOWwSf6su:-MwlUlxo3vAWzhFGggVC:b-lk3ng4) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L398)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I think the initial limit of 16 was related to poor performance seen with left-depth UNION ALL expressions that were too deep. Using a balanced tree structure brings the performance on-par with TopK when sorting/reading the entire table.  For tables with an IN list check constraint, we do bump up the maxScanCount to at least the size of the IN list:
https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L403-L410

So, if we want to be more conservative, one option is to keep the default value low, and then it would only then get bumped up for hash-sharded tables or regional partitioned tables.  Or, I could add cluster/session settings.  What do you think?
</blockquote></details>

I see, thanks for the context. So `256` is probably fine then. I do wonder if we want a hard maximum that is enforced incase a CHECK constraint has a very large number of values. A session setting for this hard maximum would be good unless you have high confidence that very large scan counts won't cause issues.
___
*[pkg/sql/opt/xform/general_funcs.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYlcZn5IN7B2Ai4_C-:-MwlZvEK2ByTMvv3KfNr:b-g12dsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L515)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

A normalization rule sounds like a good general-purpose method of rewriting a possibly-inefficient tree, when it's unknown what the input tree looks like. In this case we have access to all of the scans up-front, so we can just build as many UnionAllOps as possible that contain only Scans before proceeding to the next level up in the tree.  So, if we start with Scans: `s1`, `s2`, `s3`, `s4`, `s5`, `s6`     We feed them into the queue, and they get picked up in order and we build:
```
  UA1     UA2     UA3  
  / \     / \     / \  
 s1 s2   s3 s4   s5 s6 
```
As those are built, we put them into the queue, in order: `UA1`, `UA2`, `UA3`     .. and continue building UNION ALLs from those:
```
  UA4     UA5   
  / \     / \   
UA1 UA2 UA3 UA4 
```
`UA4` was pushed to the queue as soon as it was built, so when building `UA5` it pops `UA3` and `UA4` off the front of the queue.  Then at the end, after `UA4` has been popped off the front of the queue, and we push `UA5` to the back of the queue, it's the only item left in this pass of the `for` loop, so we know we're done:
```
         UA5         
        /   \        
      UA3    UA4     
     / \     / \     
    s5 s6  UA1  UA2  
          / \   / \  
         s1 s2 s3 s4 
```

We don't need to build a binary search tree here, so the requirements aren't so stringent.  For a general-purpose normalization rule, we'd have to answer the question of whether we actually want to apply the balancing rule in all cases.  Maybe in some cases we really do want a given left branch to remain a left branch, for some reason, etc.  Also, building up a balanced UNION ALL tree one step at a time might be more costly than waiting for the end of normalization and doing a one-pass conversion.  Anyway, I feel like there are many more questions that need answering in the general case vs. this specific optimization case, so it's probably worth opening a separate issue.  I can spend some time to refactor out this code into something like a `balancedUnionAllBuilder`, which takes a slice or queue of scans, etc., in a new commit with unit tests.  But this piece of code should probably ship before or at the same time as the other changes since we're bumping up maxScanCount.
</blockquote></details>

Sounds good. Can you add a comment here with a simplified explanation of how this balancing works?
___
*[pkg/sql/stats/histogram.go, line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwlb5bNCBiW12BMTe6Y:-Mwlb5bNCBiW12BMTe6Z:b-h5gukp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea90f8eb94b616d53f536985dc0fdc45a17b4dc5/pkg/sql/stats/histogram.go#L75)):*
> ```Go
> // returns the unencoded histogram buckets ([]cat.HistogramBucket) when
> // HistogramData.HistogramData_Bucket is non-nil, otherwise a nil
> // []cat.HistogramBucket to reduce any possible memory-pressure side-effects.
> ```

nit: I don't understand the comment about memory pressure. It seems like `nil` would be returned in this case regardless of memory concerns.
___ [...]

2022-02-25 20:22 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 4252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYdlBm-7QkU1rgy5mN:-MwlsRwW2yDFPaKxJaS_:bl8si9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/memo/statistics_builder.go#L4252)):*
> cols := opt.MakeColSet(colID)

Done
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4309 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwlQs2p3_OOEbR3MLKi:-Mwlse2s89386ibzVei1:b-2c53gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea90f8eb94b616d53f536985dc0fdc45a17b4dc5/pkg/sql/opt/memo/statistics_builder.go#L4309)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

CHECK constraints allow NULL values:

```
defaultdb> CREATE TABLE t (a INT, CHECK (a IN (1, 2, 3)));
CREATE TABLE

defaultdb> INSERT INTO t VALUES (NULL);
INSERT 1

defaultdb> SELECT * FROM t;
   a
--------
  NULL
(1 row)
```

I'm not sure what else we could do here when there isn't a `NOT NULL` constraint on the column. Do you think that assuming a null count of zero will cause bad plans if a large percentage of values are actually NULL?

</blockquote></details>

We won't create stats from check constraints in this case.  The null count of zero assumption is always true because `TabMeta.Constraints` only includes constraints on non-null columns, and if there is a null in the `IN` list, that constraint is also not included.  We could possibly extend building of stats from nullable constraints in the future, but this PR is not covering it.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4329 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwlRtf91bCU9uaLIRk_:-Mwlz0aJ2VfbhyYXnXck:b-80urv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea90f8eb94b616d53f536985dc0fdc45a17b4dc5/pkg/sql/opt/memo/statistics_builder.go#L4329)):*
> if avgSize == 0 {
>     avgSize = avgSizeFromDatums(...)
> }

Great suggestion!  Made the change.  This really cleaned up the code.
___
*[pkg/sql/opt/xform/general_funcs.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYh3MREi_NOWwSf6su:-MwmE6q6BROloYFrvw6i:b-l5kwld) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L398)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I see, thanks for the context. So `256` is probably fine then. I do wonder if we want a hard maximum that is enforced incase a CHECK constraint has a very large number of values. A session setting for this hard maximum would be good unless you have high confidence that very large scan counts won't cause issues.
</blockquote></details>

I'm fairly confident that large values won't cause a problem when the table is large.  If we ever get costing wrong for small tables and pick something that creates more scans than the number of rows in the table, that wouldn't be too good.  I've added session flag `opt_split_scan_limit` and set the default value to `2048`, the same as the hash-sharded table bucket limit.  In the future if we are more confident about costing we can remove the `256` limit entirely and just use`opt_split_scan_limit`.
___
*[pkg/sql/opt/xform/general_funcs.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwYlcZn5IN7B2Ai4_C-:-MwmUMMM85nu3PfvqrqY:b-gapgxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/caecbeb832db55c339fe7879639115e10b99db34/pkg/sql/opt/xform/general_funcs.go#L515)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Sounds good. Can you add a comment here with a simplified explanation of how this balancing works?
</blockquote></details>

Added:
```
	// Make the UNION ALLs as a balanced tree. This performs better for large
	// numbers of spans than a left-deep tree because neighboring branches can
	// be processed in parallel and the deeper the tree, the more comparisons the
	// rows from the deepest nodes in the tree need to undergo as rows are merged
	// for each UNION ALL operation.
	//
	// This balanced tree building  works by feeding RelExprs into a queue and
	// popping them from the front, combining each pair of nodes with a
	// UnionAllOp. Initially only Scan or Select operations are pushed to the
	// queue, so the first round of UnionAllOps, representing the deepest level of
	// the tree, contain only unions of scans. As UnionAllOps are built, they are
	// fed into the back of the queue, and when all scans have been popped from
	// the queue, the unions are processed. The unions themselves are then built
	// as children of new UnionAllOps. For every two UnionAllOps popped, we push
	// one new parent UnionAllOp onto the queue. Eventually we will end up with
	// only a single RelExpr in the queue, which is our root node.
```
___
*[pkg/sql/stats/histogram.go, line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwlb5bNCBiW12BMTe6Y:-MwmFUY69TJAo5snlpow:b-gqau1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea90f8eb94b616d53f536985dc0fdc45a17b4dc5/pkg/sql/stats/histogram.go#L75)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I don't understand the comment about memory pressure. It seems like `nil` would be returned in this case regardless of memory concerns.
</blockquote></details>

I've removed the comment about memory pressure since it may be confusing.  Basically I wanted to avoid what's done with `HistogramData`, where in the error case we construct an empty struct which won't be used:
`return HistogramData{}, nil, errors.Errorf("histogram requires at least two buckets")`

So I was just explaining why `nil` is returned instead of a dummy object.  Since Go is a garbage collected language, any allocated memory will need to get GC'd eventually, costing CPU cycles. But maybe the error cases don't occur very often anyway and wouldn't cost much memory overhead.



_Code quote:_
```Go
In addition to returning the encoded histogram (HistogramData), it also
```
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_json_array_dist, line 442 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwlZMZx80cHmk-xMQlG:-MwmGeB55OTxExxMoRoB:b-7c64ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea90f8eb94b616d53f536985dc0fdc45a17b4dc5/pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_json_array_dist#L442)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do you know why this query plan changed? Is it because stats are now synthesized for the `CHECK (c IN (10, 20))` constraint on `array_tab`? Seems odd that this would be affected when there are no filters on `c`.
</blockquote></details>

We now provide an average size estimate for column `c` which would affect average row size, so that may affect scan costs.  If two plans have very similar costs, it may tip the query planner's decision in one way vs. the other. With the OR terms, selectivity is likely pretty high already, so doing a full sequential scan may indeed be cheaper than index joining a large number of rows.
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 2282 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwlc_Zt8EH5IIxawlf0:-MwmJjqP84TNpENhjMme:b-qct9tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea90f8eb94b616d53f536985dc0fdc45a17b4dc5/pkg/sql/opt/memo/testdata/stats/scan#L2282)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I think it's more readable to put the columns and unique constraint on their own lines, but I realize we aren [...]

2022-02-25 20:45 UTC, michae2 approved these changes
Stats parts LGTM!

2022-02-25 22:34 UTC, rytaft reviewed
Great work!

> Reviewed 4 of 9 files at r1, 5 of 12 files at r2, 2 of 5 files at r3, 1 of 1 files at r4, 19 of 19 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-Mwn00hjBPLm4ZR3uLqV:b-9dwnzc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[-- commits, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmdWE28yeq4QP58OTq):*
I think you should still include an ORDER BY in the rewrite above (at least outside the subquery), because otherwise it's not actually a valid rewrite.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4220 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmewwL7OrIYaByYorF:-MwmewwL7OrIYaByYorG:b8puwj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4220)):*
> ```Go
> // column is not invertable, then an EquiDepthHistogram is built for the IN list
> // values with an even data distribution.
> func (sb *statisticsBuilder) BuildStatsFromCheckConstraints(
> ```

Does this function need to be exported?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4238 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmfO39-TXhlSGiInBZ:-MwmfO39-TXhlSGiInB_:bg6q1wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4238)):*
> ```Go
> 			continue
> 		}
> 		// It must be of the form "column IN (const_1, const_2, const_3, ...).
> ```

This works for hash tables where the check constraint is synthesized, but we could be more flexible to support user-defined check constraints like `column = const_1 OR column = const_2`. We already have the `constraintsBuilder` that can build arbitrary constraints from filters expressions, so maybe it's worth reusing that here? https://github.com/cockroachdb/cockroach/blob/d25385baa9d6dcb8d6fbbeca0396bc5a937bc044/pkg/sql/opt/memo/constraint_builder.go#L28
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4249 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwmh-hCAw-w9vpEnO1m:-Mwmh-hCAw-w9vpEnO1n:b-mxp1pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4249)):*
> ```Go
> 		colID := column.Col
> 		cols := opt.MakeColSet(colID)
> 		if _, ok := statistics.ColStats.Lookup(cols); ok {
> ```

you could check this first before doing any work above by just looking at the `OuterCols` of the filter expression
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4273 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmiD4hEb25-L_mRSR7:-MwmiD4hEb25-L_mRSR8:b-poxtd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4273)):*
> ```Go
> 		// histograms on inverted columns are interpreted differently, so don't
> 		// build one if the IN list column is inverted.
> 		// Also, histogram building errors out when the number samples is greater
> ```

nit: number samples -> number of samples
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4276 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmifpD0T2DCmlJ2TJA:-MwmifpD0T2DCmlJ2TJB:b-7ut9me) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4276)):*
> ```Go
> 		// than the number of rows, so just skip that case.
> 		useHistogram := sb.evalCtx.SessionData().OptimizerUseHistograms &&
> 			statistics.Available && len(invertedColOrds) == 0 && int64(numValues) <= numRows
> ```

I would say we don't need to check `statistics.Available`. This is exactly the kind of stat that would be great to have if stats are *not* available.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4293 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmiWMCACKwOD7pL7IX:-MwmiWMCACKwOD7pL7IY:bvul5gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4293)):*
> ```Go
> 			)
> 			// This shouldn't error out, but if it does, let's not punish the user.
> 			// Just build stats without the histogram in that case.
> ```

maybe we should at least log an error in this case?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4321 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwmjnw-BeAOIAepKcRm:-Mwmjnw-BeAOIAepKcRn:b-sv48s6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4321)):*
> ```Go
> }
> 
> func avgSizeFromEncodedHistogram(encodedHistogram stats.HistogramData) float64 {
> ```

Would be great to have @rharding6373 take a quick look at these two functions. They look fine to me, but just in case...
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4336 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwmk3sY8cIDbW5nc3hL:-Mwmk3sY8cIDbW5nc3hM:b-p3ho5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4336)):*
> ```Go
> 		encoded, err := keyside.Encode(nil, value, encoding.Ascending)
> 		if err != nil {
> 			dataSize = int(defaultColSize) * len(values)
> ```

nit: can use `numValues` here
___
*[pkg/sql/opt/xform/coster.go, line 1163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmkiYb0F4wCYGugeRR:-MwmkiYb0F4wCYGugeRS:b-jfhibs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/xform/coster.go#L1163)):*
> ```Go
> 
> // isStreamingSetOperator returns true if relation is a streaming set operator.
> func isStreamingSetOperator(relation memo.RelExpr) bool {
> ```

This function name is misleading. UnionAll and LocalityOptimizedSearch aren't necessarily streaming set operations, they are just exempt from the extra costing below. This would be more correct if it just checked the ordering.
___
*[pkg/sql/opt/xform/general_funcs.go, line 399 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmmWkaCkmE-VSM8Xov:-MwmmWkaCkmE-VSM8Xow:b9dhdbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/xform/general_funcs.go#L399)):*
> ```Go
> 	// TODO(msirek): We may want to lift this max entirely at some point.
> 	maxScanCount := 256
> 	hardMaxScanCount := int(c.e.evalCtx.SessionData().OptSplitScanLimit)
> ```

Can you add a comment to explain the difference between `maxScanCount` and `hardMaxScanCount`?
___
*[pkg/sql/opt/xform/general_funcs.go, line 447 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmlV0c5Wrs_k1H3zXe:-MwmlV0c5Wrs_k1H3zXf:b-zdt5xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/xform/general_funcs.go#L447)):*
> ```Go
> 	}
> 	rowCount := scan.Relational().Stats.RowCount
> 	nLogN := rowCount * math.Log2(rowCount)
> ```

nit: we don't need this variable unless limit > 0
___
*[pkg/sql/opt/xform/general_funcs.go, line 586 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmoNsV8D4R5q7HBxWc:-MwmoNsV8D4R5q7HBxWd:b-lnkf73) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/xform/general_funcs.go#L586)):*
> ```Go
> // given columnID by checking if there is a IN list CHECK constraint defined on
> // it and returning the IN list size. If not found, (0, false) is returned.
> func (c *CustomFuncs) numAllowedValues(
> ```

If you had a Constraint, we have a function that you might be able to use here: https://github.com/cockroachdb/cockroach/blob/2fdd9aebb4315f73b4e78e804dd718194b37ffed/pkg/sql/opt/constraint/constraint.go#L742
___
*[pkg/sql/opt/xform/ge [...]

2022-02-26 03:56 UTC, msirek reviewed
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-Mwn5pmc7m9fNYdvDd1N:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @msirek, and @rytaft)

___
*[-- commits, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmdWE28yeq4QP58OTq):*
Good point. It's not correctly representing what the code does.  The `Ordering` stored in our `LimitExpr` isn't shown in the SQL. Changed as follows:

```
SELECT * FROM (
    SELECT * FROM t1 WHERE index_col1 = 1 AND filter_expression LIMIT n
    UNION ALL
    SELECT * FROM t1 WHERE index_col1 = 2 AND filter_expression LIMIT n
    UNION ALL
    SELECT * FROM t1 WHERE index_col1 = 3 AND filter_expression LIMIT n
) ORDER BY secondIndexColumn LIMIT n;
```
>The ORDER BY in the rewritten query ends up getting removed by another
>optimization which takes advantage of the execution engine's ability to                   
>stitch together the UNION ALL branch results in order.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4220 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmewwL7OrIYaByYorF:-MwnA6VS1lB5Ljw_Ftp6:b-r5fg2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4220)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Does this function need to be exported?
</blockquote></details>

Unexported it



_Code quote:_
```Go
BuildStatsFromCheckConstraints
```
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4238 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmfO39-TXhlSGiInBZ:-MwnpcqtEnkC5E1tUgWw:b-5bai97) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4238)):*
> CalculateMaxResults

There is no need to build non-null user check constraints.  They are already built here:
https://github.com/cockroachdb/cockroach/blob/0ba84555cb36470686e9e9947608cf76a16a7fdc/pkg/sql/opt/optbuilder/select.go#L701-L715

I've changed the code to examine each span in the constraint and pull the Datums from the span keys.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4249 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwmh-hCAw-w9vpEnO1m:-MwnCGJH8phoCb_bT3-e:b-9i54ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4249)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

you could check this first before doing any work above by just looking at the `OuterCols` of the filter expression
</blockquote></details>

I'm not sure I follow.  The call to `Lookup` may do 4 lookups on the stats column.  Wouldn't it be better to disqualify check constraints which aren't `IN` expressions before doing these lookups?  In any case, the code is refactored and looks different now.  Maybe it's OK now?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4273 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmiD4hEb25-L_mRSR7:-MwnDZxB5-_DHh6upodG:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4273)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: number samples -> number of samples
</blockquote></details>

Fixed



_Code quote:_
```Go
Also, histogram building errors out when the number samples is greater
```
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4276 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmifpD0T2DCmlJ2TJA:-MwnDc9i8bZ2a2RrQVbE:blhm32f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4276)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I would say we don't need to check `statistics.Available`. This is exactly the kind of stat that would be great to have if stats are *not* available.
</blockquote></details>

Alright.  I was trying to be a little conservative here.  I noticed histograms getting built for internally generated SQL involving `system.statement_statistics` and didn't know if the little bit of extra overhead of histogram building would cause noticeable overhead.  I've gone ahead and removed the `statistics.Available` check.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4293 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmiWMCACKwOD7pL7IX:-MwnI7fa4GhZ44HZkKEg:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4293)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

maybe we should at least log an error in this case?
</blockquote></details>

Done



_Code quote:_
```Go
Just build stats without the histogram in that case.
```
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4336 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwmk3sY8cIDbW5nc3hL:-MwnIYPl8kkm99M2cAhp:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4336)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: can use `numValues` here
</blockquote></details>

Done



_Code quote:_
```Go
func avgSizeFromDatums(values tree.Datums) float64
```
___
*[pkg/sql/opt/xform/coster.go, line 1163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmkiYb0F4wCYGugeRR:-MwnJtNy36WS7hxQTZNn:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/xform/coster.go#L1163)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This function name is misleading. UnionAll and LocalityOptimizedSearch aren't necessarily streaming set operations, they are just exempt from the extra costing below. This would be more correct if it just checked the ordering.
</blockquote></details>

Fixed



_Code quote:_
```Go
func isStreamingSetOperator(relation memo.RelExpr) bool {
```
___
*[pkg/sql/opt/xform/general_funcs.go, line 399 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmmWkaCkmE-VSM8Xov:-MwnLIFr02TY7xHJdY7u:bvog13e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/xform/general_funcs.go#L399)):*
> hardMaxScanCount

Added:
```
	// maxScanCount is the maximum number of scans to produce if there is no
	// non-null check constraint defined on the first index column.
	maxScanCount := 256
	// hardMaxScanCount is the upper limit on what we'll attempt to increase
	// maxScanCount to using numAllowedValues() based on check constraint values.
	// This is configurable using a session setting opt_split_scan_limit.
	// If OptSplitScanLimit is below maxScanCount, we will decrease maxScanCount
	// to that value because a hard limit should never be lower than a soft limit.
	hardMaxScanCount := int(c.e.evalCtx.SessionData().OptSplitScanLimit)
	if hardMaxScanCount < maxScanCount {
		maxScanCount = hardMaxScanCount
	}

```
___
*[pkg/sql/opt/xform/general_funcs.go, line 447 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmlV0c5Wrs_k1H3zXe:-MwnLU_LB8W14_jpyCPW:b-g2edqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/xform/general_funcs.go#L447)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: we don't need this variable unless limit > 0
</blockquote></details>

Moved it into the `if` block.



_Code quote:_
```Go
nLogN := rowCount * math.Log2(rowCount)
 [...]

2022-02-27 23:14 UTC, rytaft reviewed
> Reviewed 6 of 8 files at r6, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[-- commits, line 25 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwwFfNS0Nns1euc1woA):*
nit: This still isn't technically correct -- we're not removing the ORDER BY, since we're explicitly telling the execution engine to maintain the ordering. If we didn't do that, there would be no guarantee that the ordering would be correct. But you could say that "there is no sort needed to enforce the ORDER BY, due to the execution engine's ability ..."
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4249 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwmh-hCAw-w9vpEnO1m:-MwwGzDU3Qo0UwL29CNK:bj9ckbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/memo/statistics_builder.go#L4249)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I'm not sure I follow.  The call to `Lookup` may do 4 lookups on the stats column.  Wouldn't it be better to disqualify check constraints which aren't `IN` expressions before doing these lookups?  In any case, the code is refactored and looks different now.  Maybe it's OK now?
</blockquote></details>

Ok, I assumed the lookup would be fast, but if it's not then this is fine
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4258 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwx8vSo3Ilk-uwpdg_z:-Mwx8vSp-X9c0-izwJuW:b1gchw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/memo/statistics_builder.go#L4258)):*
> ```Go
> 			}
> 			dataType := tabMeta.Table.Column(tabID.ColumnOrdinal(firstColID)).DatumType()
> 			numValues := filterConstraint.Spans.Count()
> ```

what if the values are combined into a single span? seems like it might be better to use `Constraint.CalculateMaxResults`
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4279 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwxABHK5gWglpq30FhQ:-MwxABHK5gWglpq30FhR:bvxrvbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/memo/statistics_builder.go#L4279)):*
> ```Go
> 				startKeyPrefix := startKey.Value(0)
> 				endKeyPrefix := endKey.Value(0)
> 				// Only handle point values for now, not ranges.
> ```

You can use `KeyContext.Next()` to get all the keys in the range. I'm a bit worried that you'll miss important cases if you don't handle ranges.

Might also be worth creating a new helper function on `Constraint` that does this for you so you can create a unit test for it.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4334 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwxEAs97WoVSJVlOJOt:-MwxEAs97WoVSJVlOJOu:bswybk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/memo/statistics_builder.go#L4334)):*
> ```Go
> 					useHistogram = false
> 					log.Infof(
> 						sb.evalCtx.Ctx(), "histogram could not be generated from check constraint",
> ```

would be good to include the error message from `err` too
___
*[pkg/sql/opt/xform/coster.go, line 1167 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwxEr2cDWm7lM8lHyEr:-MwxEr2cDWm7lM8lHyEs:bybzj19) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/xform/coster.go#L1167)):*
> ```Go
> 	switch relOp {
> 	case opt.UnionOp, opt.IntersectOp, opt.ExceptOp, opt.IntersectAllOp, opt.ExceptAllOp,
> 		opt.UnionAllOp, opt.LocalityOptimizedSearchOp:
> ```

We have a function `opt.IsSetOp` you can use instead of this switch.
___
*[pkg/sql/opt/xform/general_funcs.go, line 637 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmqI_U4gpWTSfDzEVS:-MwxNyvi8sO1DfPm_c8K:b1ubcge) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/xform/general_funcs.go#L637)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I believe the required ordering is enforced by the `LimitExpr` constructed in the `SplitLimitedSelectIntoUnionSelects` rule in `limit.opt`.  Notice in cases where `wrapScanInLimitedSelect` is not called and we construct just a Scan, that case also defines no required ordering for that relation. I believe it's this outer required ordering that instructs the UnionAllExprs to order results from its children, though maybe there is some nuance I don't know about.
</blockquote></details>

Makes sense
___
*[pkg/sql/opt/xform/general_funcs.go, line 635 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwxNQfc2pVrtF6lTlaZ:-MwxNQfd5nyVpINsJe0D:ba2s0ny) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/xform/general_funcs.go#L635)):*
> ```Go
> 				continue
> 			}
> 			if distinctVals, ok := constraint.CalculateMaxResults(c.e.evalCtx, cols, cols); ok {
> ```

This might be more of a bug with `CalculateMaxResults`, but I'm not sure this is doing what you want. That function currently doesn't seem to check that the constraint actually involves the given columns (although maybe it should...)

You could add a test case where a table has multiple check constraints defined on it to make sure we are looking at the right one here.
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_json_array_dist, line 442 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmzjxqAWZkZ3d5k__N:-MwxOkWE3fQpJ7ZyglEw:b-17jwhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_json_array_dist#L442)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Tweaked the preds to get the desired plan
</blockquote></details>

Now this is identical to the previous test case. I'd just remove it altogether.
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 2513 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwxP-td59ASFyDAG5-S:-MwxP-td59ASFyDAG5-T:b-xb207o) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/memo/testdata/stats/scan#L2513)):*
> ```
>       │    └── fd: (1)-->(2-7), (3,4)-->(1,2,5-7)
>       └── filters
>            └── s:3 > 'a' [type=bool, outer=(3), constraints=(/3: [/e'a\x00' - ]; tight)]
> ```

can you add another test with a check constraint that might turn into a single span? e.g., an integer column with check constraint `i IN (1, 2, 3, 4)`


<!-- Sent from Reviewable.io -->

2022-02-28 01:49 UTC, ajwerner reviewed
Signing off on the schema code. The constant on buckets <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-Mwy08nf3Sz1epcxYAxu:bvce8zu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @msirek)



<!-- Sent from Reviewable.io -->

2022-03-01 23:52 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @michae2, @msirek, and @rytaft)

___
*[-- commits, line 25 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwwFfNS0Nns1euc1woA):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: This still isn't technically correct -- we're not removing the ORDER BY, since we're explicitly telling the execution engine to maintain the ordering. If we didn't do that, there would be no guarantee that the ordering would be correct. But you could say that "there is no sort needed to enforce the ORDER BY, due to the execution engine's ability ..."
</blockquote></details>

Changed it to:
```
The ORDER BY in the rewritten query is handled efficiently by the
execution engine which has the ability to stitch together the UNION ALL 
branch results in order.
```
The stitching operation could be thought of as a type of sort with some pre-conditions.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4258 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mwx8vSo3Ilk-uwpdg_z:-Mx0VcmFAiY6CnBnMgO4:b-yfhxgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/memo/statistics_builder.go#L4258)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

what if the values are combined into a single span? seems like it might be better to use `Constraint.CalculateMaxResults`
</blockquote></details>

OK, will support ranges



_Code quote:_
```Go
dataType := tabMeta.Table.Column(tabID.ColumnOrdinal(firstColID)).DatumType()
```
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4279 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwxABHK5gWglpq30FhQ:-Mx4TXuj0Pkmud-oaW2Q:blglqga) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/memo/statistics_builder.go#L4279)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You can use `KeyContext.Next()` to get all the keys in the range. I'm a bit worried that you'll miss important cases if you don't handle ranges.

Might also be worth creating a new helper function on `Constraint` that does this for you so you can create a unit test for it.
</blockquote></details>

Thanks for the tip.  Added range support.  New function `CollectFirstColumnValues` collects the spans' first column values.  If the number of values surpasses 2048, `CollectFirstColumnBoundaryValues` collects the spans' first column start and end boundary values.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4334 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwxEAs97WoVSJVlOJOt:-Mx2qtb64sNqQjnLETRO:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/memo/statistics_builder.go#L4334)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would be good to include the error message from `err` too
</blockquote></details>

Done
___
*[pkg/sql/opt/xform/coster.go, line 1167 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwxEr2cDWm7lM8lHyEr:-Mx2rFfBAssGRh2TdYEZ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/xform/coster.go#L1167)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

We have a function `opt.IsSetOp` you can use instead of this switch.
</blockquote></details>

Done



_Code quote:_
```Go
ase opt.UnionOp, opt.IntersectOp, opt.ExceptOp, opt.IntersectAllOp, opt.ExceptAllOp,
```
___
*[pkg/sql/opt/xform/general_funcs.go, line 635 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwxNQfc2pVrtF6lTlaZ:-Mx2rUJeDasFo-25ErV_:biue2r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/xform/general_funcs.go#L635)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This might be more of a bug with `CalculateMaxResults`, but I'm not sure this is doing what you want. That function currently doesn't seem to check that the constraint actually involves the given columns (although maybe it should...)

You could add a test case where a table has multiple check constraints defined on it to make sure we are looking at the right one here.
</blockquote></details>

Thanks, I noticed that too and added a check for the proper ColumnID:
```
			firstConstraintColID := constraint.Columns.Get(0).ID()
			if columnID != firstConstraintColID {
				continue
			}
```
Changed table `a_check_int_IN_LIST` in the `stats\scan` test to have 2 check constraints.  I limited the number of stats buckets we can create from a check constraint to 256.
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_json_array_dist, line 442 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwmzjxqAWZkZ3d5k__N:-Mx2s5Vq978lGq2mlPpw:bm3yqt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6218db1b00bd9756579cf11370b894dea4413e6/pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_json_array_dist#L442)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Now this is identical to the previous test case. I'd just remove it altogether.
</blockquote></details>

OK, done.



_Code quote:_
```
SELECT a FROM array_tab WHERE b @> '{1}' OR a = 1 ORDER BY a
```
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 2513 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MwxP-td59ASFyDAG5-S:-Mx4TTON8y8OhlW43OOG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/005fa9fdfac79378112004df1f8f8db588d9a81d/pkg/sql/opt/memo/testdata/stats/scan#L2513)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you add another test with a check constraint that might turn into a single span? e.g., an integer column with check constraint `i IN (1, 2, 3, 4)`
</blockquote></details>

Done



_Code quote:_
```
├── columns: x:1(int!null) y:2(int) s:3(string!null) d:4(decimal!null) b:5(bool)
```


<!-- Sent from Reviewable.io -->

2022-03-02 02:29 UTC, msirek commented
The latest CI build/test took 1 hr 22 min, which seems a little high. Will try turning off check constraint stats generation for tables with no stats for comparison.

2022-03-02 04:17 UTC, rytaft reviewed
> Reviewed 5 of 7 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

___
*[pkg/sql/opt/constraint/constraint.go, line 793 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7f3S3D68uSJTVkYuu:-Mx7f3S47p4CWros-VFW:bemboqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L793)):*
> ```Go
> 
> 	var columns Columns
> 	columns.InitSingle(opt.MakeOrderingColumn(firstColID, false /* desc */))
> ```

Why not just use `c.Columns`?
___
*[pkg/sql/opt/constraint/constraint.go, line 807 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7ixqk5AlFg2-J3vtU:-Mx7ixqlD-HUr13917wf:b-6i4arf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L807)):*
> ```Go
> 			return nil, false, false
> 		}
> 		currKey := startKey.CutBack(startKey.Length() - 1)
> ```

Why do you need to do this? Can't you just do `startKey.Value(0)`?
___
*[pkg/sql/opt/constraint/constraint.go, line 843 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7jbOK-BaO-be5mjzN:-Mx7jbOK-BaO-be5mjzO:b-f9lb0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L843)):*
> ```Go
> 	firstColID := c.Columns.Get(0).ID()
> 	var columns Columns
> 	columns.InitSingle(opt.MakeOrderingColumn(firstColID, false /* desc */))
> ```

Same comment here
___
*[pkg/sql/opt/constraint/constraint.go, line 877 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7k4qz-gg1yuAyc_2c:-Mx7k4qz-gg1yuAyc_2d:b-dguglm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L877)):*
> ```Go
> 		// Collect both start and end values, or if boundaries are not included,
> 		// the next higher or lower values within the range.
> 		if startKey.Length() > 1 || span.startBoundary == IncludeBoundary {
> ```

I'd just do the same thing we do in other places, which is assume that PreferInclusive has been called. I think it would simplify this a lot.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4232 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7keGE3z1ACRIkBPNH:-Mx7keGE3z1ACRIkBPNI:b-inlus0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/memo/statistics_builder.go#L4232)):*
> ```Go
> 	tabID opt.TableID, statistics *props.Statistics, invertedIndexCols map[int][]int,
> ) {
> 	if !statistics.Available { // msirek-temp
> ```

Instead of this change, I was thinking that it might make sense to move the call to this function out of `makeTableStatistics`, and only build stats for columns that are requested in `colStatLeaf` (i.e., build these histograms lazily). Sorry I didn't think of this earlier, but I think that will help avoid a lot of overhead.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4272 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7lWDd2HcoJj0Va2bG:-Mx7lWDd2HcoJj0Va2bH:bqcbihk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/memo/statistics_builder.go#L4272)):*
> ```Go
> 			var distinctVals uint64
> 			if distinctVals, ok = filterConstraint.CalculateMaxResults(sb.evalCtx, cols, cols); ok {
> 				if len(invertedColOrds) == 0 {
> ```

nit: I'd flip this around and do:
```
if len(invertedColOrds) != 0 {
  // Add a comment here to explain why.
  continue
}
```
Then you don't need the `else`
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4293 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7m1ks5DF62KdpYBSM:-Mx7m1ks5DF62KdpYBSN:b-y5wj98) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/memo/statistics_builder.go#L4293)):*
> ```Go
> 			// greater than the number of rows, so just skip that case.
> 			useHistogram := sb.evalCtx.SessionData().OptimizerUseHistograms && numValues > 0 &&
> 				!hasNullValue && len(invertedColOrds) == 0 && int64(numValues) <= numRows
> ```

Can you add a comment to explain why you won't build a histogram if `hasNullValue` is true?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4314 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7nQ5l6CMGBDoAk17u:-Mx7nQ5l6CMGBDoAk17v:bbawe1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/memo/statistics_builder.go#L4314)):*
> ```Go
> 					numRows,
> 					int64(numValues), /* distinctCount */
> 					256,              /* maxBuckets */
> ```

You might as well use 200 to match this: https://github.com/cockroachdb/cockroach/blob/52c2df4fb00d943328dc59df9dc210a40a556ab2/pkg/sql/create_stats.go#L64

(you could also export that constant and move it to another package so you can use it here).
___
*[pkg/sql/opt/xform/testdata/rules/select, line 1445 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7prg94iqdWyY0CWGG:-Mx7oQst5cO70LyB6Tzj:bjwalit) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/xform/testdata/rules/select#L1445)):*
> ```
> 
> # TODO(ridwanmsharif): Confirm if this makes sense. I would've expected that the primary index
> #  would be used here. But it isn't the plan being picked. Curious.
> ```

looks like you can remove this TODO
___
*[pkg/sql/opt/constraint/constraint_test.go, line 1095 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7ovZ15vcmoAnQFlAp:-Mx7ovZ15vcmoAnQFlAq:b756xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint_test.go#L1095)):*
> ```Go
> 			expectedValues: "(1, 3)",
> 			hasNull:        false,
> 		},
> ```

would be good to test something like `"/1/2/3: [/1/1 - /1/1] [/1/3 - /1/3]"`
___
*[pkg/sql/opt/constraint/constraint_test.go, line 1158 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7pE11E9Kgb_FS4b0k:-Mx7pE11E9Kgb_FS4b0l:bsa10to) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint_test.go#L1158)):*
> ```Go
> 		},
> 		{ // 6
> 			spans:          "/1: [/NULL - /NULL]",
> ```

why do you collect NULL values with the other function but not this one?


<!-- Sent from Reviewable.io -->

2022-03-02 13:12 UTC, rytaft reviewed
I'm a little skeptical of using the CI build time to make any conclusions... a microbenchmark would probably be a better option if you're concerned. But also, I think building the histograms lazily as I suggested below should help.

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-Mx9jUAu9rWJvGbdv77k:bb0yjxe)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

___
*[pkg/sql/opt/constraint/constraint.go, line 843 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7jbOK-BaO-be5mjzN:-Mx9iRFwE3vkvPp1W9TL:bd7ek2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L843)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Same comment here
</blockquote></details>

(i.e. Why not just use c.Columns?)
___
*[pkg/sql/opt/constraint/constraint.go, line 832 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx9h-DqAmMuewvyNkME:-Mx9h-DqAmMuewvyNkMF:bcwxg3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e82c2849d413a1836ff157944370d475bf5f952a/pkg/sql/opt/constraint/constraint.go#L832)):*
> ```Go
> // excluded, we tighten the boundaries plus or minus 1 to collect values which
> // are included. The presence of a null value causes collection to fail.
> func (c *Constraint) CollectFirstColumnBoundaryValues(
> ```

Do you have any data driven tests (e.g., tests in `memo/testdata/stats`) where we build a histogram using this function? Something like `CHECK (x BETWEEN 0 and 500 OR x BETWEEN 1000 AND 1500)` or `CHECK (x BETWEEN 0 and 5000 OR x BETWEEN 10000 AND 15000)`. My hunch is that this approach might not give us a very accurate histogram. Another option is to just not build a histogram at all if there are too many values, or only build a 2-bucket histogram.

If you go with the 2-bucket histogram, you might want something lighter-weight than this function, and also lighter weight than `stats.EquiDepthHistogram`.

Better to do something simple that is easier to debug later...


<!-- Sent from Reviewable.io -->

2022-03-02 15:52 UTC, msirek reviewed
Thanks, this isn't the last say on performance, and I'm not trying to make conclusions based on it.  It is just making me curious since the build time increased by 30 minutes, so the first step is just to see if there is a measurable difference with and without the new code changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-MxAJqe1Doc23aUdiBJA:b56hg6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @msirek, and @rytaft)



<!-- Sent from Reviewable.io -->

2022-03-03 06:14 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @michae2, @msirek, and @rytaft)

___
*[pkg/sql/opt/constraint/constraint.go, line 793 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7f3S3D68uSJTVkYuu:-MxAPvBk6A3J_GRz5k_v:bxtoy1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L793)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why not just use `c.Columns`?
</blockquote></details>

In case `c.Columns` has more than one column, we only want to include the first column.  I couldn't find a check constraint that built multiple columns though.  Another option would be to use `c.Columns`, but return right away if it contained more than one column.



_Code quote:_
```Go
keyCtx := MakeKeyContext(&column
```
___
*[pkg/sql/opt/constraint/constraint.go, line 807 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7ixqk5AlFg2-J3vtU:-MxAQ_A91cryv7G8cdMB:b-efwozh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L807)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why do you need to do this? Can't you just do `startKey.Value(0)`?
</blockquote></details>

I was just modeling the code on similar code that uses `currKey.Next()`.  `startKey.Value(0)` is a `Datum`, not a `Key`, so I would not be able to use it as a receiver for calling `Next()`.



_Code quote:_
```Go
for l, ok := 0, true; l < int(keyCount); l++ {
```
___
*[pkg/sql/opt/constraint/constraint.go, line 843 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7jbOK-BaO-be5mjzN:-MxAT9S17ONZuTAvrY-n:b-4ctsav) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L843)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

(i.e. Why not just use c.Columns?)
</blockquote></details>

Removed this function.
___
*[pkg/sql/opt/constraint/constraint.go, line 877 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7k4qz-gg1yuAyc_2c:-MxATEQy-Gsw9C-YlCPX:b-4ctsav) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L877)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'd just do the same thing we do in other places, which is assume that PreferInclusive has been called. I think it would simplify this a lot.
</blockquote></details>

Removed this function.
___
*[pkg/sql/opt/constraint/constraint.go, line 832 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx9h-DqAmMuewvyNkME:-MxASx0c9hlBh43WcctV:b-n8mbjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e82c2849d413a1836ff157944370d475bf5f952a/pkg/sql/opt/constraint/constraint.go#L832)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you have any data driven tests (e.g., tests in `memo/testdata/stats`) where we build a histogram using this function? Something like `CHECK (x BETWEEN 0 and 500 OR x BETWEEN 1000 AND 1500)` or `CHECK (x BETWEEN 0 and 5000 OR x BETWEEN 10000 AND 15000)`. My hunch is that this approach might not give us a very accurate histogram. Another option is to just not build a histogram at all if there are too many values, or only build a 2-bucket histogram.

If you go with the 2-bucket histogram, you might want something lighter-weight than this function, and also lighter weight than `stats.EquiDepthHistogram`.

Better to do something simple that is easier to debug later...
</blockquote></details>

Alright, I've removed CollectFirstColumnBoundaryValues.  I had originally thought about writing a `Key.NextN(n int)` function to skip ahead by more than a single point value at a time for generating samples when `CalculateMaxResults` returns a high value, to keep the number of samples low.  But I felt that was an overly-complex fix to implement in this first pass, when it's not known how many actual use cases would benefit from that.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4232 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7keGE3z1ACRIkBPNH:-MxB0qUn7g7s_QG0wmgn:b-rnfvgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/memo/statistics_builder.go#L4232)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Instead of this change, I was thinking that it might make sense to move the call to this function out of `makeTableStatistics`, and only build stats for columns that are requested in `colStatLeaf` (i.e., build these histograms lazily). Sorry I didn't think of this earlier, but I think that will help avoid a lot of overhead.
</blockquote></details>

No worries. Yes, this looks like a natural place to do lazy evaluation.  I've reworked the logic and moved the `buildStatsFromCheckConstraints` call to `colStatLeaf`.  I also added a map to TabMeta to avoid rebuilding the stats every time we duplicate a Select/Scan. On a hash-sharded PK table with 256 buckets, this shaves the EXPLAIN time from 400 ms down to 300 ms. I had to make the value in the `map` an `Interface{}` to avoid cyclic imports. Building the filters for each new `Select` is still expensive. If we used a different representation than UNION ALL for the skip scan, that would eliminate all of that extra filter building.  But maybe there's another way to optimize filter building via direct copy of some items instead of rebuilding.

![Screenshot from 2022-03-02 18-26-34.png](https://files.reviewableusercontent.io/images/reviewable/3999975/ZbT_AnVmw_1VjHZj0G62P6s0/Screenshot%20from%202022-03-02%2018-26-34.png)

Maybe I'll take a look tomorrow and see what can be done about filter building costs. Though perhaps this should go in a separate PR.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4272 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7lWDd2HcoJj0Va2bG:-MxDMbARBIafjuZ3QY3S:bmxkhne) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/memo/statistics_builder.go#L4272)):*
> if len(invertedColOrds) != 0 {

This code is refactored
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4293 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7m1ks5DF62KdpYBSM:-MxCbc0W9hT6cII0LIaB:bc47boz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/memo/statistics_builder.go#L4293)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add a comment to explain why you won't build a histogram if `hasNullValue` is true?
</blockquote></details>

Added:
```
			// Non-null check constraints are not expected to have nulls, so we do
			// not expect to see null values. If we do see a null, something may have
			// gone wrong, so do not build a histogram in this case either.
```
I also added a log message in case we see an unexpected null.



_Code quote:_
```Go
// Histograms on inverted columns are interpreted differently
```
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4314 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7nQ5l6CMGBDoAk17u:-MxCdP6T9ZGVxOnH99Pe:bys5bb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/memo/statistics_builder.go#L4314)):*
> defaultHistogramBuckets

Done
___
*[pkg/sql/opt/xform/testdata/rules/select, line 1445 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7prg94iqdWyY0CWGG:-MxCd_Hh2YVWXiX93j [...]

2022-03-03 15:07 UTC, msirek commented
@rytaft   Regarding this comment:
> I would say we don't need to check statistics.Available. This is exactly the kind of stat that would be great to have if stats are not available.

Just double-checking, are you sure this is what we want to do?  This would invoke the code on all tables, including system tables, which don't have any stats collected.  It may be safer to allow it only on tables which have stats collected on other columns, just not virtual columns. Most users will have stats collected on all tables, so this would just be filling in the gap where we can't collect stats on virtual columns.

2022-03-03 16:35 UTC, rytaft commented
I'm not sure, so let's go with your instinct and add the check for `statistics.Available`, since it will reduce the footprint of queries that this change affects, which is definitely a good thing if we want to try to get this into 22.1.





<!-- Sent from Reviewable.io -->

2022-03-03 16:58 UTC, rytaft reviewed
> Reviewed 7 of 9 files at r14, 2 of 2 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

___
*[pkg/sql/BUILD.bazel, line 342 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxFcuwjAGZg53pRFQZY:-MxFcuwjAGZg53pRFQZZ:b-juic49) ([raw file](https://github.com/cockroachdb/cockroach/blob/24736c339995af6b773e15856457b88a396bafaa/pkg/sql/BUILD.bazel#L342)):*
> ```Starlark
>         "//pkg/sql/opt/memo",
>         "//pkg/sql/opt/optbuilder",
>         "//pkg/sql/opt/props",
> ```

Any way we can avoid adding a new dependency here? Maybe you could put the new constant in the `stats` package instead?
___
*[pkg/sql/opt/metadata.go, line 476 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxFdVvXEgs9NS-Zlw6r:-MxFdVvXEgs9NS-Zlw6s:blhxgop) ([raw file](https://github.com/cockroachdb/cockroach/blob/24736c339995af6b773e15856457b88a396bafaa/pkg/sql/opt/metadata.go#L476)):*
> ```Go
> 		for i := range tabMeta.checkConstraintsStats {
> 			if dstCol, ok := colMap.Get(int(i)); ok {
> 				checkConstraintsStats[ColumnID(dstCol)] = tabMeta.checkConstraintsStats[i]
> ```

don't you also need to remap the column IDs in the stats?

edit: looks like you're doing this elsewhere, but this is pretty subtle, so a comment would help.
___
*[pkg/sql/opt/constraint/constraint.go, line 793 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7f3S3D68uSJTVkYuu:-MxFe3OP-fYPQLYYb0bl:bdr26gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L793)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

In case `c.Columns` has more than one column, we only want to include the first column.  I couldn't find a check constraint that built multiple columns though.  Another option would be to use `c.Columns`, but return right away if it contained more than one column.
</blockquote></details>

But looking at the `KeyCount` code I think it will still work as long as you pass 1 for the `prefixLength` param
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4232 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7keGE3z1ACRIkBPNH:-MxFgYUIARzl-8CKrIre:b6jk6nr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/memo/statistics_builder.go#L4232)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

No worries. Yes, this looks like a natural place to do lazy evaluation.  I've reworked the logic and moved the `buildStatsFromCheckConstraints` call to `colStatLeaf`.  I also added a map to TabMeta to avoid rebuilding the stats every time we duplicate a Select/Scan. On a hash-sharded PK table with 256 buckets, this shaves the EXPLAIN time from 400 ms down to 300 ms. I had to make the value in the `map` an `Interface{}` to avoid cyclic imports. Building the filters for each new `Select` is still expensive. If we used a different representation than UNION ALL for the skip scan, that would eliminate all of that extra filter building.  But maybe there's another way to optimize filter building via direct copy of some items instead of rebuilding.

![Screenshot from 2022-03-02 18-26-34.png](https://files.reviewableusercontent.io/images/reviewable/3999975/ZbT_AnVmw_1VjHZj0G62P6s0/Screenshot%20from%202022-03-02%2018-26-34.png)

Maybe I'll take a look tomorrow and see what can be done about filter building costs. Though perhaps this should go in a separate PR.
</blockquote></details>

Yea, separate PR would be good.

Looks like from that flame chart that the statistics building is a relatively small part of the cost? If so, I would say this PR is probably good to go, but before the branch cut we should determine whether we can get these other costs down, and if not, we might want to reduce the number of hash buckets for which we're willing to apply this optimization.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4309 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxFg5By0dYee7s8YIy9:-MxFg5By0dYee7s8YIyA:bp2n6gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/24736c339995af6b773e15856457b88a396bafaa/pkg/sql/opt/memo/statistics_builder.go#L4309)):*
> ```Go
> 			var values tree.Datums
> 			var distinctVals uint64
> 			invertedIndexSourceColumn = sb.isInvertedSourceColumn(firstColID, tabID)
> ```

can you add a comment to explain this check?


<!-- Sent from Reviewable.io -->

2022-03-03 20:31 UTC, msirek reviewed
OK, `buildStatsFromCheckConstraints` returns false now if `statistics.Available` is false.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-MxG6s6k1cy7stZlIixP:bkmmvla)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @msirek, and @rytaft)

___
*[pkg/sql/opt/metadata.go, line 476 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxFdVvXEgs9NS-Zlw6r:-MxFlRB36gALdkH9eRdp:bear09m) ([raw file](https://github.com/cockroachdb/cockroach/blob/24736c339995af6b773e15856457b88a396bafaa/pkg/sql/opt/metadata.go#L476)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

don't you also need to remap the column IDs in the stats?

edit: looks like you're doing this elsewhere, but this is pretty subtle, so a comment would help.
</blockquote></details>

No, the `ColumnStatistic` exists in the original table's statistics, so we want to treat it as immutable in case it's subsequently used.  The new `ColumnStatistic` for the table copy will always be built directly with the proper column ID in `colStatLeaf`:
https://github.com/cockroachdb/cockroach/blob/24736c339995af6b773e15856457b88a396bafaa/pkg/sql/opt/memo/statistics_builder.go#L498

  `buildStatsFromCheckConstraints` may just reuse a previous result via a call to `ColumnStatistic.CopyFromOther` to copy all the useful information over into the new `ColumnStatistic`.  The new `Histogram` structure picks up the proper column ID here:
https://github.com/cockroachdb/cockroach/blob/24736c339995af6b773e15856457b88a396bafaa/pkg/sql/opt/props/statistics.go#L282

Added the comment:
```
				// We remap the column ID key, but not any column IDs in the
				// ColumnStatistic as this is still being used in the statistics of the
				// original table and should be treated as immutable. When the Histogram
				// is copied in ColumnStatistic.CopyFromOther, it is initialized with
				// the proper column ID.
```
___
*[pkg/sql/opt/constraint/constraint.go, line 793 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7f3S3D68uSJTVkYuu:-MxFs80t-BGtFL7PS3NU:bpslp1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/constraint/constraint.go#L793)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

But looking at the `KeyCount` code I think it will still work as long as you pass 1 for the `prefixLength` param
</blockquote></details>

I see. Changed it to use `c.Columns`.



_Code quote:_
```Go
columns.InitSingle(opt.MakeOrderingColumn(firstColID, false /* desc */))
```
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4232 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-Mx7keGE3z1ACRIkBPNH:-MxFsOcs4RK7spAhzcji:b-xzcvmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd59ba3281fe7deaa2574afb549db980d903dc8/pkg/sql/opt/memo/statistics_builder.go#L4232)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea, separate PR would be good.

Looks like from that flame chart that the statistics building is a relatively small part of the cost? If so, I would say this PR is probably good to go, but before the branch cut we should determine whether we can get these other costs down, and if not, we might want to reduce the number of hash buckets for which we're willing to apply this optimization.
</blockquote></details>

Yes, I could not find `buildStatsFromCheckConstraints` on the flame chart.  The `EXPLAIN` optimization time is actually double compared to running the query without `EXPLAIN` because it does an index recommendation pass.  But 150ms is still a lot of time.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4309 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxFg5By0dYee7s8YIy9:-MxG4llJADjUzraRVwkH:bg1qiub) ([raw file](https://github.com/cockroachdb/cockroach/blob/24736c339995af6b773e15856457b88a396bafaa/pkg/sql/opt/memo/statistics_builder.go#L4309)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you add a comment to explain this check?
</blockquote></details>

Removed this check.  It's still useful to collect the values for calculating average size on inverted columns.



_Code quote:_
```Go
isInvertedSourceColumn
```
___
*[pkg/sql/BUILD.bazel, line 342 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxFcuwjAGZg53pRFQZY:-MxGRanY4-1acVHKVYnY:b-34gp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/24736c339995af6b773e15856457b88a396bafaa/pkg/sql/BUILD.bazel#L342)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Any way we can avoid adding a new dependency here? Maybe you could put the new constant in the `stats` package instead?
</blockquote></details>

Yes, moving it to stats did the trick.


<!-- Sent from Reviewable.io -->

2022-03-04 06:58 UTC, rytaft approved these changes
Have you confirmed that the stats are getting built for the virtual column in the hash indexes? (and do your tests show that?)

Otherwise, <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once you address one last nit below. I think this is worth merging despite the stability period as part of making hash indexes production-ready

> Reviewed 6 of 8 files at r17, 16 of 16 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-MxFiA9X26iK4ddw4BKe:bjmj6hb)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

___
*[-- commits, line 46 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxIeUFHEhRj-0p6KBrn):*
Needs to be filled in
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4335 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxIfFca-4wv04eMtn9E:-MxIfFca-4wv04eMtn9F:b5uv8nt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb597f3625b8f9a6594b4a4e2bd35fb285fb4479/pkg/sql/opt/memo/statistics_builder.go#L4335)):*
> ```Go
> 			numValues := len(values)
> 			// Histograms are not typically built on inverted columns, and the data
> 			// types of such columns (JSON, ARRAY, TUPLE) aren't likely to occur in
> ```

we don't support TUPLE columns. The other relevant types here are geometry and geography (i.e., spatial types). If this decision is based on types, then it would be better to just use the column type directly, instead of finding `isInvertedSourceColumn` -- that just seems like a lot of unnecessary computation.


<!-- Sent from Reviewable.io -->

2022-03-04 07:00 UTC, rytaft commented
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4335 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxIfFca-4wv04eMtn9E:-MxIiPvb5iFGhpClqbCe:bkifs3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb597f3625b8f9a6594b4a4e2bd35fb285fb4479/pkg/sql/opt/memo/statistics_builder.go#L4335)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

we don't support TUPLE columns. The other relevant types here are geometry and geography (i.e., spatial types). If this decision is based on types, then it would be better to just use the column type directly, instead of finding `isInvertedSourceColumn` -- that just seems like a lot of unnecessary computation.
</blockquote></details>

You can use this to check: https://github.com/cockroachdb/cockroach/blob/9c1f347a1c00f6bc999e04402399d716826ef59f/pkg/sql/catalog/colinfo/col_type_info.go#L131


<!-- Sent from Reviewable.io -->

2022-03-04 13:18 UTC, msirek reviewed
OK, thanks.  I will merge it soon.  Yes, I have confirmed stats are built on the virtual column in the hash index. Here is one example hash index test (which uses a virtual column for the hash bucket), though it's not directly showing the stats that are collected:
https://github.com/msirek/cockroach/blob/splitSelectIntoUnionSelects/pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index#L48-L62

I couldn't create a stats test directly because the hash bucket column is not selectable in `testcat` tests, so I've added a new test to `stats/scan` to simulate the virtual hash index bucket column and show the stats which are built.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-MxJbtpB2iQ-GSswSwaH:bnjidxf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @msirek, and @rytaft)

___
*[-- commits, line 46 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxIeUFHEhRj-0p6KBrn):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Needs to be filled in
</blockquote></details>

Done
___
*[pkg/sql/opt/memo/statistics_builder.go, line 4335 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-MxIfFca-4wv04eMtn9E:-MxJW7WR68e6vWHOsRCk:b-686kel) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb597f3625b8f9a6594b4a4e2bd35fb285fb4479/pkg/sql/opt/memo/statistics_builder.go#L4335)):*
> spatial types

OK.  Actually I was making this decision based on histograms never previously existing on inverted index columns in the past, so thought it might possibly be an unexercised, possibly problematic code path.  The comment about types just means that the types allowed for inverted index columns are less likely to have check constraints defined on them, so we probably wouldn't be missing out on a customer use case by not supporting histograms from check constraints for inverted index columns.  But not building histograms for these types entirely is a good option too (the less supported variations, the lower the potential for problem cases). I've changed the check to call `ColumnTypeIsInvertedIndexable`.


<!-- Sent from Reviewable.io -->

2022-03-04 15:13 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-MxKUOOXAyPhODg3RW65:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)



<!-- Sent from Reviewable.io -->

2022-03-04 17:54 UTC, msirek reviewed
TFTR!
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76893#-:-MxL3B9C6aZOAR2OyrZ3:bihs03x)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)



<!-- Sent from Reviewable.io -->

2022-03-04 20:06 UTC, merged