sql: introduce crdb_internal.historical_contention_events virtual table
cockroachdb/cockroach pull request #76917
Opened 2022-02-23 03:35 UTC by Azhng

Reviewer note: only last commit is relevant

---

This commit introduces `crdb_internal.historical_contention_events`
virtual table. This virtual tables exposes historical contention events
annoated with transaction fingerprint IDs for transactions that finishes
execution. This allows this virtual table to be joined into the
statement statistics and transaction statistics table.
The new virtual table require at least VIEWACTIVITYREDACTED permission
to access. However, in order to view the contending keys, it would
require at least VIEWACTIVITY permission or above.

Resolves #75904

Release note (sql change): introducing
`crdb_internal.historical_contention_events` virtual table, that exposes
historical contention events. The events exposed in the new virtual
table also include transaction fingerprint IDs for both blocking and
waiting transactions. This allows the new virtual table to be joined
into statement statistics and transaction statistics tables.
The new virtual table require at least VIEWACTIVITYREDACTED permission
to access. However, in order to view the contending keys, it would
require at least VIEWACTIVITY permission or above.

Release note (api change): introducing
GET `/_status/historicalcontentionevents` endpoint, that returns
cluster-wide in-memory historical contention events.
The endpoint require at least VIEWACTIVITYREDACTED permission
to access. However, in order to expose the contending keys, it would
require at least VIEWACTIVITY permission or above.

2022-02-23 03:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/76917)
<!-- Reviewable:end -->

2022-02-24 21:23 UTC, matthewtodd requested changes
> Reviewed 6 of 6 files at r1, 28 of 28 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[-- commits, line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_m3MCPKFPdVKt36S):*
I'm a little troubled by the word "historical" here. It's unclear from the name how these relate to `crdb_internal.{cluster,node}_contention_events`.
___
*[-- commits, line 52 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_oDC5sH2qKi-0X1O):*
s/annoated/annotated
___
*[-- commits, line 52 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_poT6935LKmfD4-l):*
s/finishes execution/have finished executing
___
*[-- commits, line 54 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_rP40vr5deOSyPak):*
s/table/tables
___
*[-- commits, line 66 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhbO179k-lDWENNsiC):*
Maybe also say something about this data being stored in-memory rather than on disk, and the size being set by `sql.contention.event_store.capacity`?
___
*[pkg/server/status.go, line 3152 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_ecp5ftJafU-Rt5y:-Mwh_ecp5ftJafU-Rt5z:b-t613ep) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4b18fccb838900d1fdc20e230a0a52dd23b17a/pkg/server/status.go#L3152)):*
> ```Go
> 	}
> 
> 	localReq := &serverpb.HistoricalContentionEventsRequest{
> ```

nit: maybe inline this in the `rpcCallFn`, to make it clear that's the only use?
___
*[pkg/server/status.go, line 3165 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_gYUCx7IUBBC4cWa:-Mwh_gYUCx7IUBBC4cWb:blloqjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4b18fccb838900d1fdc20e230a0a52dd23b17a/pkg/server/status.go#L3165)):*
> ```Go
> 	}
> 
> 	if err := s.iterateNodes(ctx, fmt.Sprintf("historical contention events for node %s", req.NodeID),
> ```

If we get here, `len(req.NodeID)` is 0, no?
___
*[pkg/server/tenant_status.go, line 1125 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_jHW539XCWQlumro:-Mwh_jHW539XCWQlumrp:boymf8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4b18fccb838900d1fdc20e230a0a52dd23b17a/pkg/server/tenant_status.go#L1125)):*
> ```Go
> 	}
> 
> 	if err := t.iteratePods(ctx, fmt.Sprintf("historical contention events for instance %s", req.NodeID),
> ```

ditto, won't `len(req.NodeID)` be 0 here?


<!-- Sent from Reviewable.io -->

2022-02-24 21:27 UTC, matthewtodd reviewed
Looking good, main question is how we're positioning this view from a product perspective. I think we want to look at these in relationship to the existing `crdb_internal.{cluster,node}_contention_events` tables and either have some rationale for the existence of all 3 (considering the name for this new one) or find some way to put them together. WDYT, @kevin-v-ngo?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-:-MwhbeynAnM9COpOUipV:b-p8seu9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)



<!-- Sent from Reviewable.io -->

2022-02-24 21:35 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @matthewtodd)

___
*[-- commits, line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_m3MCPKFPdVKt36S):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I'm a little troubled by the word "historical" here. It's unclear from the name how these relate to `crdb_internal.{cluster,node}_contention_events`.
</blockquote></details>

I was going to call this new table `cluster_contention_events`, but realized we already have a virtual table with that name :face_exhaling: . `historical_contention_events` was the best idea I could come up with. :facepalm: :sweat_smile: . @kevin-v-ngo  any idea what we should call this new table? 
___
*[-- commits, line 52 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_oDC5sH2qKi-0X1O):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

s/annoated/annotated
</blockquote></details>

Done.
___
*[-- commits, line 52 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_poT6935LKmfD4-l):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

s/finishes execution/have finished executing
</blockquote></details>

Done.
___
*[-- commits, line 54 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_rP40vr5deOSyPak):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

s/table/tables
</blockquote></details>

Done.
___
*[-- commits, line 66 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhbO179k-lDWENNsiC):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Maybe also say something about this data being stored in-memory rather than on disk, and the size being set by `sql.contention.event_store.capacity`?
</blockquote></details>

Done.
___
*[pkg/server/status.go, line 3152 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_ecp5ftJafU-Rt5y:-MwhcfGO8N4UJP0mkai0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4b18fccb838900d1fdc20e230a0a52dd23b17a/pkg/server/status.go#L3152)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: maybe inline this in the `rpcCallFn`, to make it clear that's the only use?
</blockquote></details>

Done.
___
*[pkg/server/status.go, line 3165 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_gYUCx7IUBBC4cWa:-Mwhcg-3A8Hcyx_Y2gUz:b7ym0yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4b18fccb838900d1fdc20e230a0a52dd23b17a/pkg/server/status.go#L3165)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

If we get here, `len(req.NodeID)` is 0, no?
</blockquote></details>

Heh, good point! I just realized all of the SQL Obs endpoint has this bug :facepalm:.  I will send a follow up PR to cleanup other incorrect use.
___
*[pkg/server/tenant_status.go, line 1125 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_jHW539XCWQlumro:-Mwhd6lQ9CjH6QnrRlBV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4b18fccb838900d1fdc20e230a0a52dd23b17a/pkg/server/tenant_status.go#L1125)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

ditto, won't `len(req.NodeID)` be 0 here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-24 21:47 UTC, matthewtodd reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, and @matthewtodd)

___
*[-- commits, line 52 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwhg8Ss5NQGDVDk3tSS):*
nit: "annoatetd" is still misspelled here.
___
*[pkg/server/status.go, line 3152 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_ecp5ftJafU-Rt5y:-MwhgQ0b590kp6Ks-bLP:b-fosumj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4b18fccb838900d1fdc20e230a0a52dd23b17a/pkg/server/status.go#L3152)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops, what I meant was you could inline `localReq` into `rpcCallFn`. I guess it's also okay to inline `rpcCallFn` if you want, but it seems like other endpoints tend to pull it out.
___
*[pkg/server/status.go, line 3165 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_gYUCx7IUBBC4cWa:-MwhgZKa1_CbILB-pulr:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4b18fccb838900d1fdc20e230a0a52dd23b17a/pkg/server/status.go#L3165)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Heh, good point! I just realized all of the SQL Obs endpoint has this bug :facepalm:.  I will send a follow up PR to cleanup other incorrect use.
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2022-02-24 22:20 UTC, maryliag requested changes
Agree with Matthew, just by looking at those 3 names is not clear the relationship on the new one.

> Reviewed 1 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-:-Mwhk0mNA49OQUJqccw5:b-68v3qd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, @maryliag, and @matthewtodd)

___
*[-- commits, line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_m3MCPKFPdVKt36S):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I was going to call this new table `cluster_contention_events`, but realized we already have a virtual table with that name :face_exhaling: . `historical_contention_events` was the best idea I could come up with. :facepalm: :sweat_smile: . @kevin-v-ngo  any idea what we should call this new table? 
</blockquote></details>

one way of thinking about this is: what is the information that exist on this table and doesn't exist on cluster_contention_events. If this is related to cluster, does it make sense to change the existing table to add the new info? If it's a completely different goal, what makes it so?
___
*[-- commits, line 55 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwhkk2UDF4AXrJCkmsQ):*
the concept of "at least" a role sounds weird. Explain it requires VIEWACTIVITY or VIEWACTIVITYREDACTED, with the redacted removing the info about keys 
___
*[-- commits, line 76 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhkwwpEWVc0p3DDRE5):*
same comment as above
___
*[pkg/server/admin.go, line 3301 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhljJ17TIUNcXowog7:-MwhljJ17TIUNcXowog8:b5gqj1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/admin.go#L3301)):*
> ```Go
> 	userName, isAdmin, err := c.getUserAndRole(ctx)
> 	if err != nil {
> 		return false /* hasViewActivityPermission */, serverError(ctx, err)
> ```

personal preference: those extra comments are not necessary, this is a very simple function and the name of the return is right above, this just clog the view
___
*[pkg/server/tenant_status.go, line 1088 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhnhQF18aOfXNDpPRR:-MwhnhQF18aOfXNDpPRS:b-94awq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/tenant_status.go#L1088)):*
> ```Go
> 		return nil, err
> 	}
> 	shouldRedactContendingKeys := !hasViewActivity
> ```

if you redact keys when the role is VIEWACTIVITYREDACTED you should check for the existence of that role, bot for the non existence of the VIEWACTIVITY. A user can have both roles with REDACTED taking precedent. 
___
*[pkg/server/status_test.go, line 2935 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwhn5ie7gW5fImPgytr:-Mwhn5ie7gW5fImPgyts:b-injcv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/status_test.go#L2935)):*
> ```Go
> 
> 	txnID1 := sqlConn1.QueryStr(t, `
>   SELECT txn_id
> ```

nit: some weird spacing on these statement, from this one below is not aligned with the one above
___
*[pkg/server/status_test.go, line 2967 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhnDcsCcuMhBn10teF:-MwhnDcsCcuMhBn10teG:b-7021ew) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/status_test.go#L2967)):*
> ```Go
> 		COMMIT;
> 		SET TRACING=off;
> `,
> ```

nit: also not aligned


<!-- Sent from Reviewable.io -->

2022-02-25 00:37 UTC, matthewtodd requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, @maryliag, and @matthewtodd)

___
*[-- commits, line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_m3MCPKFPdVKt36S):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

one way of thinking about this is: what is the information that exist on this table and doesn't exist on cluster_contention_events. If this is related to cluster, does it make sense to change the existing table to add the new info? If it's a completely different goal, what makes it so?
</blockquote></details>

Yeah, thinking about this this evening, I was imagining it might make sense to add these values as columns to *both* `node_contention_events` and `cluster_contention_events`. Alternatively, maybe two separate tables, `node_contention_event_details` and `cluster_contention_event_details`? But I don't like those as much.


<!-- Sent from Reviewable.io -->

2022-02-28 07:35 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo, @maryliag, and @matthewtodd)

___
*[-- commits, line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_m3MCPKFPdVKt36S):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Yeah, thinking about this this evening, I was imagining it might make sense to add these values as columns to *both* `node_contention_events` and `cluster_contention_events`. Alternatively, maybe two separate tables, `node_contention_event_details` and `cluster_contention_event_details`? But I don't like those as much.
</blockquote></details>

Chatted with @kevin-v-ngo . Landed on the `transaction_contention_events` since the new table focused on correlating contention events with transactions. 

It doesn't quite make sense to add this new data to the old table. This is because as discussed in the original RFC, The old table focused on answering the question of "which table/index is experiencing the contention". The data is already presented in the way that has been aggregated based on table/index ID, contending keys and then transaction ID. It's difficult to build what we are trying to build right now on the old table. 
___
*[-- commits, line 52 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwhg8Ss5NQGDVDk3tSS):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

nit: "annoatetd" is still misspelled here.
</blockquote></details>

:facepalm: 
___
*[-- commits, line 55 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwhkk2UDF4AXrJCkmsQ):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the concept of "at least" a role sounds weird. Explain it requires VIEWACTIVITY or VIEWACTIVITYREDACTED, with the redacted removing the info about keys 
</blockquote></details>

Done.
___
*[-- commits, line 76 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhkwwpEWVc0p3DDRE5):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

same comment as above
</blockquote></details>

Done.
___
*[pkg/server/admin.go, line 3301 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhljJ17TIUNcXowog7:-MwzCR5e9uIBv20GAxMW:b-6iqd13) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/admin.go#L3301)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

personal preference: those extra comments are not necessary, this is a very simple function and the name of the return is right above, this just clog the view
</blockquote></details>

Hmm I do have some opinions here. Through my personal experience, these inline comments really help with me understanding the code. Especially when the Reviewable / GitHub generates diff in the way when portion of the function is collapsed. 
The function might be "simple" from our perspective, but excess simplicity creates cognitive burden for other people without domain-specific context when reading this code. 
___
*[pkg/server/status.go, line 3152 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_ecp5ftJafU-Rt5y:-MwzDJiP7LsoyLsCZ5gU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b4b18fccb838900d1fdc20e230a0a52dd23b17a/pkg/server/status.go#L3152)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Oops, what I meant was you could inline `localReq` into `rpcCallFn`. I guess it's also okay to inline `rpcCallFn` if you want, but it seems like other endpoints tend to pull it out.
</blockquote></details>

Done.
___
*[pkg/server/tenant_status.go, line 1088 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhnhQF18aOfXNDpPRR:-MwzDNzL3qbaxFVgAUXU:bi6dd6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/tenant_status.go#L1088)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

if you redact keys when the role is VIEWACTIVITYREDACTED you should check for the existence of that role, bot for the non existence of the VIEWACTIVITY. A user can have both roles with REDACTED taking precedent. 
</blockquote></details>

Explicitly checked for existence of VIEWACTIVITYREDACTED
___
*[pkg/server/status_test.go, line 2935 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwhn5ie7gW5fImPgytr:-MwzE_Xe4Bk5zRlap8T7:b-wr4aal) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/status_test.go#L2935)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: some weird spacing on these statement, from this one below is not aligned with the one above
</blockquote></details>

Hmm seems like I mixed tabs and space here :facepalm: 


<!-- Sent from Reviewable.io -->

2022-02-28 14:27 UTC, maryliag requested changes
> Reviewed 6 of 28 files at r7, 34 of 37 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, @maryliag, and @matthewtodd)

___
*[-- commits, line 55 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwhkk2UDF4AXrJCkmsQ):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You updated the one below, but not this (Also, don't forget to update the PR description)
___
*[-- commits, line 31 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mx-fKCmAcSkpa6vi6lN):*
if the user has VIEWACTIVITY but also have VIEWACTIVITYREDACTED they wouldn't see the key, so having VIEWACTIVITY is not enough. The sentence should be something like:
Contenting keys information will not be returned if the user has VIEWACTIVITYREDACTED.
___
*[pkg/server/status.go, line 3045 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mx-gGgw52YTlBXPbxVr:-Mx-gGgw52YTlBXPbxVs:bpwkkzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c363db31eef5e27c2ab0c35d7b08ee7b44698e71/pkg/server/status.go#L3045)):*
> ```Go
> 			break
> 		}
> 	}
> ```

you don't need all of that, you can use the `hasRoleOption` or `requireViewActivityAndNoViewActivityPermission` functions for example, without the extra need for UserSQLRoles call and loop on the results
___
*[pkg/server/tenant_status.go, line 1088 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhnhQF18aOfXNDpPRR:-Mx-hUaZ71Pwrhr_WFbs:bu32b2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/tenant_status.go#L1088)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Explicitly checked for existence of VIEWACTIVITYREDACTED
</blockquote></details>

same comment os above


<!-- Sent from Reviewable.io -->

2022-02-28 15:49 UTC, matthewtodd reviewed
> Reviewed 17 of 37 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, @maryliag, and @matthewtodd)

___
*[-- commits, line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_m3MCPKFPdVKt36S):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Chatted with @kevin-v-ngo . Landed on the `transaction_contention_events` since the new table focused on correlating contention events with transactions. 

It doesn't quite make sense to add this new data to the old table. This is because as discussed in the original RFC, The old table focused on answering the question of "which table/index is experiencing the contention". The data is already presented in the way that has been aggregated based on table/index ID, contending keys and then transaction ID. It's difficult to build what we are trying to build right now on the old table. 
</blockquote></details>

Awesome, that makes sense. Now I'm going to muse about what we do with this, but none of these thoughts are blocking for this PR in any way. :slightly_smiling_face:

Since the naming has been a little awkward to figure out, it does make me wonder if the introduction of this new table means something for those old ones -- will this new one be more powerful, and thus supersede the old ones? Would they go away entirely? Or, less dramatically, if they're less useful, would it make sense to give them longer names (maybe `{node,cluster}_contention_event_statistics`?) and take over the `cluster_contention_events` name here? (Since, IIUC, each row in the new table really is an event.)
___
*[pkg/server/admin.go, line 3301 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhljJ17TIUNcXowog7:-Mx-t90m7nWCxv8XbHO1:b5a9bus) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/admin.go#L3301)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm I do have some opinions here. Through my personal experience, these inline comments really help with me understanding the code. Especially when the Reviewable / GitHub generates diff in the way when portion of the function is collapsed. 
The function might be "simple" from our perspective, but excess simplicity creates cognitive burden for other people without domain-specific context when reading this code. 
</blockquote></details>

This is an interesting discussion! I went looking through our style guide and found a recommendation to [add these comments when the meaning is not obvious](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Avoid-Naked-Parameters). It was good for me to read that section. I hadn't previously appreciated the role these comments can play.

Is the meaning already obvious here? I think so: the boolean return parameter from `hasViewActivityPermission` most certainly is the answer to that question. But, @azhng, your point about the surrounding context being cut off during code review is useful. (And, indeed, since the IDE can already display parameter hints, perhaps these comments are primarily for code review anyway?)

On balance (acknowledging it's tricky), I wouldn't put these particular comments in right now, but I think it's okay if you do. Perhaps we'll all converge on a consensus the more we work together.


<!-- Sent from Reviewable.io -->

2022-02-28 18:28 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo, @maryliag, and @matthewtodd)

___
*[-- commits, line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_m3MCPKFPdVKt36S):*
> Since, IIUC, each row in the new table really is an event.)

Yes that is correct.

Hmm this is some interesting idea here, since the data presented in the old tables can be easily integrated into the new table, but not vice versa. It might make sense to deprecate the old tables here in this case. (iirc, I don't think we are exposing the old tables in the UI at all) 

Though, there might be some subtle implications of replacing the older tables with new ones, since the new one presents high fidelity information at the cost of short data retention. In contrast, the older table can store a lot more aggregated information for longer retention period. (since adding/deleting table is quite rare). Direct replacement might not be straightforward.

I think the older tables and newer tables can be used together in a lot of cases, since
* older table answer the question of:
  * which table/index/row experience contentions. (by providing a list of blocker txnIDs)
* new table answer a different question:
  * find the transactions that constantly contend with each other

When joining the new table into the old table, we can begin to answer even more questions that we previously were not able to, e.g.:
* which applications are causing high level of contentions
* which transaction fingerprint (and associated statement fingerprints) that frequently cause contentions on Table X / Index Y
* etc. 
___
*[-- commits, line 55 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwhkk2UDF4AXrJCkmsQ):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

You updated the one below, but not this (Also, don't forget to update the PR description)
</blockquote></details>

Done.
___
*[-- commits, line 31 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mx-fKCmAcSkpa6vi6lN):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

if the user has VIEWACTIVITY but also have VIEWACTIVITYREDACTED they wouldn't see the key, so having VIEWACTIVITY is not enough. The sentence should be something like:
Contenting keys information will not be returned if the user has VIEWACTIVITYREDACTED.
</blockquote></details>

Done.
___
*[pkg/server/status.go, line 3045 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mx-gGgw52YTlBXPbxVr:-Mx0XI5k-XxLTFjEp8DA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c363db31eef5e27c2ab0c35d7b08ee7b44698e71/pkg/server/status.go#L3045)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you don't need all of that, you can use the `hasRoleOption` or `requireViewActivityAndNoViewActivityPermission` functions for example, without the extra need for UserSQLRoles call and loop on the results
</blockquote></details>

Done.
___
*[pkg/server/tenant_status.go, line 1088 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhnhQF18aOfXNDpPRR:-Mx0XiaQ9NWomyEGicNw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/tenant_status.go#L1088)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

same comment os above
</blockquote></details>

Done.
___
*[pkg/server/admin.go, line 3301 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-MwhljJ17TIUNcXowog7:-Mx0_lKn8TDSvBaHqVox:bqdz09f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5b5fedc2f51aa8ea69fcca1cb750330b1665785/pkg/server/admin.go#L3301)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

This is an interesting discussion! I went looking through our style guide and found a recommendation to [add these comments when the meaning is not obvious](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Avoid-Naked-Parameters). It was good for me to read that section. I hadn't previously appreciated the role these comments can play.

Is the meaning already obvious here? I think so: the boolean return parameter from `hasViewActivityPermission` most certainly is the answer to that question. But, @azhng, your point about the surrounding context being cut off during code review is useful. (And, indeed, since the IDE can already display parameter hints, perhaps these comments are primarily for code review anyway?)

On balance (acknowledging it's tricky), I wouldn't put these particular comments in right now, but I think it's okay if you do. Perhaps we'll all converge on a consensus the more we work together.
</blockquote></details>

Done. Actually this function is not longer needed. Removed


<!-- Sent from Reviewable.io -->

2022-02-28 22:14 UTC, maryliag requested changes
> Reviewed 2 of 37 files at r10, 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @kevin-v-ngo)

___
*[-- commits, line 18 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mx1OPI3-0f0EYzwY0dg):*
s/historical/transaction
Can you add a little more information here about the table, to help the team writing the documentation? Columns names, etc
___
*[-- commits, line 30 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mx1OLM37AZFNnybSm4S):*
s/historical/transaction


<!-- Sent from Reviewable.io -->

2022-02-28 22:37 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @maryliag)

___
*[-- commits, line 18 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mx1OPI3-0f0EYzwY0dg):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

s/historical/transaction
Can you add a little more information here about the table, to help the team writing the documentation? Columns names, etc
</blockquote></details>

Done. Added table schema and explanation of each individual column
___
*[-- commits, line 30 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mx1OLM37AZFNnybSm4S):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

s/historical/transaction
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-28 23:16 UTC, maryliag approved these changes
From my comments <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 
Make sure to get an approval from Matthew's comments too

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-:-Mx1bglm80ccYCmj8-5u:bfsxigb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kevin-v-ngo)



<!-- Sent from Reviewable.io -->

2022-03-01 15:46 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-:-Mx59Ofj8BtAkv2In14I:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/76917#-Mwh_m3MCPKFPdVKt36S):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

> Since, IIUC, each row in the new table really is an event.)

Yes that is correct.

Hmm this is some interesting idea here, since the data presented in the old tables can be easily integrated into the new table, but not vice versa. It might make sense to deprecate the old tables here in this case. (iirc, I don't think we are exposing the old tables in the UI at all) 

Though, there might be some subtle implications of replacing the older tables with new ones, since the new one presents high fidelity information at the cost of short data retention. In contrast, the older table can store a lot more aggregated information for longer retention period. (since adding/deleting table is quite rare). Direct replacement might not be straightforward.

I think the older tables and newer tables can be used together in a lot of cases, since
* older table answer the question of:
  * which table/index/row experience contentions. (by providing a list of blocker txnIDs)
* new table answer a different question:
  * find the transactions that constantly contend with each other

When joining the new table into the old table, we can begin to answer even more questions that we previously were not able to, e.g.:
* which applications are causing high level of contentions
* which transaction fingerprint (and associated statement fingerprints) that frequently cause contentions on Table X / Index Y
* etc. 
</blockquote></details>

Cool, thanks for furthering the thinking here, @azhng! (And, to be clear, none of these thoughts are blocking for this PR.) cc @kevin-v-ngo 


<!-- Sent from Reviewable.io -->

2022-03-01 15:59 UTC, Azhng commented
TFTR!

bors r=maryliag,matthewtodd

2022-03-01 17:18 UTC, merged