sql: add SHOW STATISTICS WITH FORECAST
cockroachdb/cockroach pull request #77070
Opened 2022-02-26 01:37 UTC by michae2

**sql/stats: replace eval.Context with tree.CompareContext**

Most uses of eval.Context in the sql/stats package can actually be
tree.CompareContext instead, so make the replacement.

Release note: None

**sql/stats: bump histogram version to 2**

In 22.2 as of 963deb8 we support multiple histograms for trigram-
indexed strings. Let's bump the histogram version for this change, as we
may want to know whether multiple histograms are possible for a given
row in system.table_statistics.

(I suspect that during upgrades to 22.2 the 22.1 statistics builder will
choke on these statistics, so maybe we should also backport a version
check to 22.1.)

Also update avgRefreshTime to work correctly in multiple-histogram
cases.

Release note: None

**sql/stats: teach histogram.adjustCounts to remove empty buckets**

Sometimes when adjusting counts down we end up with empty buckets in the
histogram. They don't hurt anything, but they take up some memory (and
some brainpower when examining test results). So, teach adjustCounts to
remove them.

Release note: None

**sql/stats: always use non-nil buckets for empty-table histograms**

After 82b5926 I've been using the convention that nil histogram
buckets = no histogram, and non-nil-zero-length histogram buckets =
histogram on empty table. This is mostly useful for testing but is also
important for forecasting histograms.

Fix a spot that wasn't following this convention.

Also, add some empty-table testcases and some other testcases for
histogram.adjustCounts.

Release note: None

**sql/stats: make ordering of SHOW STATISTICS more deterministic**

Make two changes to produce more deterministic SHOW STATISTICS output:

1. Sort column IDs when creating statistics. We already use `FastIntSet`
   in both create_stats.go and statistics_builder.go to ignore ordering
   when gathering statistics by column set, but the column ordering from
   CREATE STATISTICS leaks into `system.table_statistics` and can affect
   SQL on that table, such as SHOW STATISTICS and various internal
   DELETE statements.

2. Order by column IDs and statistic IDs when reading from
   `system.table_statistics` in both SHOW STATISTICS and the stats
   cache. This will ensure SHOW STATISTICS always produces the same
   output, and shows us rows in the same order as the stats cache sees
   them (well, reverse order of the stats cache).

Release note (sql change): Make SHOW STATISTICS output more
deterministic.

**sql/stats: forecast table statistics**

Add function to forecast table statistics based on observed statistics.
These forecasts are based on linear regression models over time. For
each set of columns with statistics, we construct a linear regression
model over time for each statistic (row count, null count, distinct
count, average row size, and histogram). If all models are good fits
then we produce a statistics forecast for the set of columns.

Assists: #79872

Release note: None

**sql: add SHOW STATISTICS WITH FORECAST**

Add a new WITH FORECAST option to SHOW STATISTICS which calculates and
displays forecasted statistics along with the existing table statistics.

Also, forbid injecting forecasted stats.

Assists: #79872

Release note (sql change): Add a new WITH FORECAST option to SHOW
STATISTICS which calculates and displays forecasted statistics along
with the existing table statistics.

2022-02-26 01:37 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/77070)
<!-- Reviewable:end -->

2022-03-04 01:18 UTC, michae2 commented
Added some tests, fixed some bugs. A few tests still need to be written.

2022-03-08 06:58 UTC, michae2 commented
This is RFAL. I need to write two more tests, but that can happen concurrently with reviewing.

2022-03-08 18:25 UTC, michae2 commented
Make some linters happy. 🙂

2022-03-10 18:52 UTC, rharding6373 requested changes
I did a first pass review, but need to look at forecast and forecast_test in more detail. Looks good so far!

> Reviewed 4 of 13 files at r1, 3 of 9 files at r2, 6 of 8 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-:-Mxp9xe1DEuV7l_H77eQ:b-psu3ir)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[pkg/sql/show_stats.go, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxfYhmcBQp8BXa0CRSq:-MxfYhmcBQp8BXa0CRSr:b-2dih2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a1f4a4250b341877ce0a9ee796ec687b7d48f2/pkg/sql/show_stats.go#L154)):*
> ```Go
> 			}
> 
> 			if _, withForecast := opts[showTableStatsOptForecast]; withForecast {
> ```

I think this chunk should get moved below the `defer func()` for recovery. 
___
*[pkg/sql/sem/tree/datum.go, line 784 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxooHKy5S3oVNM_uDsM:-MxooHKz7jViWt7dYw7g:b-i0arc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/datum.go#L784)):*
> ```Go
> 	// DMaxInt is the maximum DInt.
> 	DMaxInt = NewDInt(math.MaxInt64)
> 	// DMinInt is the maximum DInt.
> ```

s/maximum/minimum
___
*[pkg/sql/sem/tree/datum.go, line 2466 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxorUTA0Z0GhYBaoTxC:-MxorUTA0Z0GhYBaoTxD:b-94ath3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/datum.go#L2466)):*
> ```Go
> 	}
> 	if t.After(MaxSupportedTime) {
> 		return &DTimestamp{Time: MaxSupportedTime.Round(precision)}
> ```

I was playing with this a bit, and if we round MaxSupportedTime to a precision of say a minute, it's going to round 294276-12-31 23:59:59.999999 up to 294277-01-01 00:00:00, which is outside of our timestamp bounds. Is this behavior acceptable? If not, I wonder if `time.Truncate` would be better here.
___
*[pkg/sql/sem/tree/datum.go, line 2763 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxov8QNAuWhj0VaNfJ9:-Mxov8QNAuWhj0VaNfJA:b-5zvdg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/datum.go#L2763)):*
> ```Go
> 	}
> 	if t.After(MaxSupportedTime) {
> 		return &DTimestampTZ{Time: MaxSupportedTime.Round(precision)}
> ```

Same issue here with rounding up over MaxSupportedTime.
___
*[pkg/sql/sem/tree/decimal.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxovRqq6JHgyleHRaJ7:-MxovRqq6JHgyleHRaJ8:b-uq8p9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/decimal.go#L96)):*
> ```Go
> 
> // MinDecimalForWidth returns the minimum decimal that fits within the given
> // precision and scale. If precision is zero it returns negative infinite.
> ```

minor nit: s/infinite/infinity
___
*[pkg/sql/sem/tree/decimal.go, line 116 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxovbV29tpavgByRnmp:-MxovbV29tpavgByRnmq:b-uq8p9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/decimal.go#L116)):*
> ```Go
> 
> // MaxDecimalForWidth returns the maximum decimal that fits within the given
> // precision and scale. If precision is zero it returns positive infinite.
> ```

minor nit: s/infinite/infinity
___
*[pkg/sql/stats/automatic_stats.go, line 533 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxozbXN7VKCAgKtW_Ra:-MxozbXN7VKCAgKtW_Rb:bncrbog) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/automatic_stats.go#L533)):*
> ```Go
> func avgRefreshTime(tableStats []*TableStatistic) time.Duration {
> 	var reference *TableStatistic
> 	var protos []*TableStatisticProto
> ```

It seems like we only need the `CreatedAt` field at this time, maybe we should just store and pass a slice of timestamps instead of the whole proto.
___
*[pkg/sql/stats/forecast.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp5unT6abfKoYmYAFw:-Mxp5unT6abfKoYmYAFx:byw1vqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L41)):*
> ```Go
> // We only use a predicted value in a forecast if the R² (goodness of fit)
> // measurement of the predictive model is high enough. Otherwise we use the
> // latest observed value. This means our forecasts are a mixture of predicted
> ```

For debugging purposes, how do we differentiate what type of prediction a forecast has?
___
*[pkg/sql/stats/forecast.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp687ZEcDASTpwAM6S:-Mxp687ZEcDASTpwAM6T:btkogkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L43)):*
> ```Go
> // latest observed value. This means our forecasts are a mixture of predicted
> // parts and observed parts.
> const minGoodnessOfFit = 0.95
> ```

How did you pick .95?
___
*[pkg/sql/stats/forecast.go, line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp7Nee5jEyWDuCAwSj:-Mxp7Nef-T3TZ-UbBYZ_:b-rf94r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L49)):*
> ```Go
> // valuable than others. We call the weighted number of predicted parts the
> // score of a forecast.
> const minForecastScore = 1
> ```

Does this mean that 100% of the parts need to be predicted via the forecast? I don't understand from the comment how this const will actually be used.
___
*[pkg/sql/logictest/testdata/logic_test/distsql_stats, line 635 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp0jSp4axKPGNWAcqh:-Mxp0jSp4axKPGNWAcqi:b2fnaxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/logictest/testdata/logic_test/distsql_stats#L635)):*
> ```
> __auto__         {e}
> __auto__         {e}
> __forecast__     {a}
> ```

Why is there no forecast for the other columns?
___
*[pkg/sql/stats/forecast_test.go, line 50 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp20ts8hD0pf5VlRpH:-Mxp20ts8hD0pf5VlRpI:bnono7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast_test.go#L50)):*
> ```Go
> 	testCases := []struct {
> 		x, y       []float64
> 		xn, yn, r2 float64
> ```

What does r2 mean?
___
*[pkg/sql/stats/forecast_test.go, line 672 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp3COM7OlQhHeiaBH7:-Mxp3COM7OlQhHeiaBH8:b-7be6y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast_test.go#L672)):*
> ```Go
> 			typ: types.Decimal,
> 			dat: makeDDecimal("42"),
> 			val: 42,
> ```

The answer to everything!
___
*[pkg/sql/stats/forecast_test.go, line 799 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp3YW98_il6ZOoU4nV:-Mxp3YW98_il6ZOoU4nW:bltmsrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast_test.go#L799)):*
> ```Go
> 			val: 0,
> 		},
> 		// Hmm... tree.DMinInterval and tree.DMaxInterval can't be encoded. Skip
> ```

Is this a TODO?


<!-- Sent from Reviewable.io -->

2022-03-10 22:26 UTC, mgartner reviewed
Very cool! I'll need some more time to get through all of this, but I've left some initial comments for now.

I'm curious to know your thoughts behind the utility of the `WITH FORECAST` option? Do you see a need for users or us to see stats both with and without forecasts? If not, I think we can remove the additional syntax. If so, I'm assuming the optimizer will use the forecasted stats by default, so it might be more clear to show the forecasted stats by default and add a `WITHOUT FORECAST` option to `SHOW STATS`. If we plan to turn on/off forecasting in the optimizer with a session setting, then maybe it makes the most sense to have `SHOW STATS` use the same session setting to determine whether or not to show forecasted stats.

> Reviewed 3 of 13 files at r1, 1 of 9 files at r2, 3 of 8 files at r3, 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-:-MxpbTJ3-kfx5Fp3k_Ja:b-16wib2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[pkg/sql/sem/tree/decimal.go, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpeNMi8uGbHNqGFQI7:-MxpeNMi8uGbHNqGFQI8:b-nm7nbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/decimal.go#L103)):*
> ```Go
> 	// Use +1 here because it is inverted later.
> 	if scale < math.MinInt32+1 || scale > math.MaxInt32 {
> 		return nil, errScaleOutOfRange
> ```

These bounds are checked by [`types.MakeDecimal`](https://github.com/cockroachdb/cockroach/blob/170d49cbedc6519ea1bfe092eba6c269b9f12954/pkg/sql/types/types.go#L874-L895). So rather than make these types take and arbitrary `precision` and `scale`, you could make these functions take a `*types.T` and pull the scale and precision out of the type. Then you wouldn't need to repeat these checks. You'd want to error/panic if the type was not a Decimal.
___
*[pkg/sql/stats/automatic_stats.go, line 563 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxph9g21UWjTFcjcQTS:-Mxph9g21UWjTFcjcQTT:b-fpym3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/automatic_stats.go#L563)):*
> ```Go
> }
> 
> func avgStatTime(stats []*TableStatisticProto) time.Duration {
> ```

nit: `avgStatTime` sounds more like the time it took to collect the stats. What about `avgStatPeriod` ("period" as in the reciprocal of frequency).
___
*[pkg/sql/stats/forecast.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpmLco9l6r9iyRgR70:-MxpmLco9l6r9iyRgR71:b943hy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L53)):*
> ```Go
> // forecastColumnStatistics, makeQuantile, and quantile.toHistogramData will
> // need to be changed if we introduce a new histogram version.
> const _ uint = 1 - uint(histVersion)
> ```

Neat trick!
___
*[pkg/sql/stats/forecast.go, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpkhlV2r6Wv69ROacl:-MxpkhlW0eWoADB_C7yp:b-o6tx1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L76)):*
> ```Go
> // finding exactly that v is p₂ - p₁. To put it in terms of our histograms:
> // NumRange = 0 becomes a vertical line, NumRange > 0 becomes a slanted line,
> // NumEq = 0 goes away, and NumEq > 0 becomes a horizontal line.
> ```

nit: some concrete examples in this description might be helpful. you can also cite external resources if you think any would be helpful for building an understanding of quantile functions.
___
*[pkg/sql/stats/forecast.go, line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxptAV83BkkAG_fZC_t:-MxptAV83BkkAG_fZC_u:b-ivx6g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L124)):*
> ```Go
> 	// Group observed statistics by columnset.
> 	var forecastCols []string
> 	observedByCols := make(map[string][]*TableStatisticProto)
> ```

An alternative to this columnset->string hack would be to use a slice of column sets where then index of each column set in the slice is a key into a `map[int][]*TableStatisticsProto`. Getting and setting values would have to scan the slice looking for an equal column set, but it's probably not a problem in this use case. You could encapsulate this in a struct and make the API nice and clean.
___
*[pkg/sql/stats/forecast.go, line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpqjM-0vJTwFWevREH:-MxpqjM-0vJTwFWevREI:b-ce7vmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L163)):*
> ```Go
> 	// statistics + the average time between collections, which should be roughly
> 	// when the next stats collection will occur.
> 	at := latest.Add(avgStatTime(observedCol0[:n]))
> ```

nit: It might be safer to forecast to `latest statistics + the maximum time between collections`. For example, if traffic ebbs and floods, collections will follow the pattern, like:

```
C1..........C2..............................C3..........C4
```

With average stat time we'd forecast like:

```
C1..........C2..............................C3..........C4................F
```

With maximum stat time we'd forecast like:

```
C1..........C2..............................C3..........C4..............................F
```
___
*[pkg/sql/stats/forecast.go, line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxpoyz--QbDmj-grlLh:-Mxpoyz--QbDmj-grlLi:bpegod8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L166)):*
> ```Go
> 
> 	// If any columnset has a valuable forecast, then we must also use forecasts
> 	// for the rest of the columnsets in the table (even if those forecasts are
> ```

Why must we use forecasts all column sets? Is there a reason to calculate the forecasts for all column sets together? Could we avoid the need for the `observedByCols` map and the columnset->string key hack by forecasting for each column set independently?
___
*[pkg/sql/stats/forecast.go, line 189 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxpte1_0d3CIrKoSFW1:-Mxpte1_0d3CIrKoSFW2:blhbcm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L189)):*
> ```Go
> 	cols := strconv.FormatUint(uint64(stat.ColumnIDs[0]), 10)
> 	for i := 1; i < len(stat.ColumnIDs); i++ {
> 		cols += " " + strconv.FormatUint(uint64(stat.ColumnIDs[i]), 10)
> ```

Do `stats.ColumnIDs` have a guaranteed ordering?
___
*[pkg/sql/stats/forecast.go, line 399 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpuhpIBwhRYz7NEQtE:-MxpuhpIBwhRYz7NEQtF:b-nyqfi9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L399)):*
> ```Go
> 		yHat := α + β*x[i]
> 		ε := y[i] - yHat
> 		Σεε += ε * ε
> ```

I don't have too strong of an opinion on the usage of these special characters in code, but it's not something I've seen us use elsewhere. For example, in `statistics_builder.go` we spell out `epsilon`. But I suppose it makes it easy to map these variables to the equations in comments, which is worth the extra work to type these characters when we update this code. Was that your main motivation?


<!-- Sent from Reviewable.io -->

2022-03-11 08:43 UTC, michae2 reviewed
Thank you for the first passes! :grin:

There was an issue with `forecastColumnStatistics` I had to fix (we were not calling `histogram.adjustCounts` when using the latest observed histogram instead of the predicted histogram). So I've made some changes, but have not yet addressed all your excellent comments. I will do that tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-:-Mxs0JPo8YgawCYCf0Aj:b-vjv2hz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rharding6373, and @rytaft)

___
*[pkg/sql/show_stats.go, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxfYhmcBQp8BXa0CRSq:-Mxs1bZXDdlpOl0mDm9x:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a1f4a4250b341877ce0a9ee796ec687b7d48f2/pkg/sql/show_stats.go#L154)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think this chunk should get moved below the `defer func()` for recovery. 
</blockquote></details>

Good point, done.
___
*[pkg/sql/sem/tree/datum.go, line 784 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxooHKy5S3oVNM_uDsM:-Mxs1iCk5zShgW-I5XXf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/datum.go#L784)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

s/maximum/minimum
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/datum.go, line 2466 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxorUTA0Z0GhYBaoTxC:-Mxs1jwY3nWwWAT5vqVu:b-acmhq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/datum.go#L2466)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I was playing with this a bit, and if we round MaxSupportedTime to a precision of say a minute, it's going to round 294276-12-31 23:59:59.999999 up to 294277-01-01 00:00:00, which is outside of our timestamp bounds. Is this behavior acceptable? If not, I wonder if `time.Truncate` would be better here.
</blockquote></details>

Ahhh good catch! Let me work on this.
___
*[pkg/sql/sem/tree/decimal.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxovRqq6JHgyleHRaJ7:-Mxs1pK17D_I7kFESBOX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/decimal.go#L96)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

minor nit: s/infinite/infinity
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/decimal.go, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpeNMi8uGbHNqGFQI7:-Mxs2QND8eWE2UGJc_bg:b-cip2ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/decimal.go#L103)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

These bounds are checked by [`types.MakeDecimal`](https://github.com/cockroachdb/cockroach/blob/170d49cbedc6519ea1bfe092eba6c269b9f12954/pkg/sql/types/types.go#L874-L895). So rather than make these types take and arbitrary `precision` and `scale`, you could make these functions take a `*types.T` and pull the scale and precision out of the type. Then you wouldn't need to repeat these checks. You'd want to error/panic if the type was not a Decimal.
</blockquote></details>

Oh, good point! I'll try this.
___
*[pkg/sql/sem/tree/decimal.go, line 116 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxovbV29tpavgByRnmp:-Mxs1sGJ7f3X1UiYr-qj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/decimal.go#L116)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

minor nit: s/infinite/infinity
</blockquote></details>

Done.
___
*[pkg/sql/stats/forecast.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp5unT6abfKoYmYAFw:-Mxs204n6_uK-S-4a_pH:b1cpf4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L41)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

For debugging purposes, how do we differentiate what type of prediction a forecast has?
</blockquote></details>

Currently the logging is the only way. Maybe we need something better?
___
*[pkg/sql/stats/forecast.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp687ZEcDASTpwAM6S:-Mxs27I6EjNY_tJImvaM:btig9k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L43)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

How did you pick .95?
</blockquote></details>

Just a random hunch, nothing scientific.
___
*[pkg/sql/stats/forecast.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpmLco9l6r9iyRgR70:-Mxs2HNj3Du-DhxV3SI4:bat1td5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L53)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Neat trick!
</blockquote></details>

:slightly_smiling_face:
___
*[pkg/sql/stats/forecast.go, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpkhlV2r6Wv69ROacl:-Mxs2ZMD-ebHE_13LOyD:bc7b0h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L76)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: some concrete examples in this description might be helpful. you can also cite external resources if you think any would be helpful for building an understanding of quantile functions.
</blockquote></details>

I've added an example and a link to Wikipedia, hopefully that helps a bit.
___
*[pkg/sql/stats/forecast.go, line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxptAV83BkkAG_fZC_t:-Mxs2kqC0rYa_Ahkg5ka:bdemfim) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L124)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

An alternative to this columnset->string hack would be to use a slice of column sets where then index of each column set in the slice is a key into a `map[int][]*TableStatisticsProto`. Getting and setting values would have to scan the slice looking for an equal column set, but it's probably not a problem in this use case. You could encapsulate this in a struct and make the API nice and clean.
</blockquote></details>

Oh, nice. Let me try this tomorrow.
___
*[pkg/sql/stats/forecast.go, line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpqjM-0vJTwFWevREH:-Mxs2p9_D0n0JiyhD1aQ:b-jxni2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L163)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: It might be safer to forecast to `latest statistics + the maximum time between collections`. For example, if traffic ebbs and floods, collections will follow the pattern, like:

```
C1..........C2..............................C3..........C4
```

With average stat time we'd forecast like:

```
C1..........C2..............................C3..........C4................F
```

With maximum stat time we'd forecast like:

```
C1..........C2..............................C3..........C4..............................F
```

</blockquote></deta [...]

2022-03-11 18:45 UTC, mgartner reviewed
I've left some more comments, but in general this looks great! 

> Reviewed 1 of 13 files at r1, 2 of 9 files at r2, 3 of 8 files at r3, 1 of 4 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-:-MxuHPDGDskLh8JYheUF:bhhemio)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rharding6373, and @rytaft)

___
*[pkg/sql/stats/forecast.go, line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp7Nee5jEyWDuCAwSj:-MxuI0ZGAqsIW2U7XLxz:bnoj3n9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L49)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Does this mean that 100% of the parts need to be predicted via the forecast? I don't understand from the comment how this const will actually be used.
</blockquote></details>

+1 The meaning of the score is not clear to me. I think it deserves some more explanation, here, and maybe other places where the score is computed.
___
*[pkg/sql/stats/forecast.go, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpkhlV2r6Wv69ROacl:-MxtW2OkEFZJ_t57zW7B:b-ayz2sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L76)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I've added an example and a link to Wikipedia, hopefully that helps a bit.
</blockquote></details>

Very helpful, thanks!
___
*[pkg/sql/stats/forecast.go, line 107 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxtp2toA28jdVY4B1Zz:-Mxtp2toA28jdVY4B1_-:bvwbii3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L107)):*
> ```Go
> //       0  .2  .4  .6  .8   1
> //
> type quantile []quantilePoint
> ```

It'd be nice to define the quantile type near its methods, which are currently at the bottom of the file. You could consider moving the quantile struct and methods into a separate file, and the tests to a corresponding test file - it'd be a nice encapsulated API that way.
___
*[pkg/sql/stats/forecast.go, line 125 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxtpRD_-rVLqnm5nje5:-MxtpRD_-rVLqnm5nje6:baqep24) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L125)):*
> ```Go
> // table, given the observed statistics. If a forecast cannot be produced (or is
> // not worth using) an error is returned. ForecastTableStatistics is
> // deterministic, given the same observations.
> ```

nit: Add some more explanation of the general approach to forecasting here. I don't think it needs to be too detailed, but since this is the entry-point to forecasting, a summary in its comment, with pointers to more specific comments would be helpful.
___
*[pkg/sql/stats/forecast.go, line 183 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxtY9N4BBeYK_T8Ti5j:-MxtY9N4BBeYK_T8Ti5k:b-n8cyvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L183)):*
> ```Go
> 			}
> 		}
> 	}
> ```

nit: might be nice to move this check into a helper function
___
*[pkg/sql/stats/forecast.go, line 201 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxtZfeX6JQkWO2ZjUF4:-MxtZfeX6JQkWO2ZjUF5:b-uv4tlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L201)):*
> //Forecasted RowCounts will be the same for all columnsets
> // assuming that all observations have the same RowCounts, by virtue of
> // passing the same minGoodnessOfFit each time.

Isn't this only true if the latest `n` collections for each columnset have the same row counts and creation times? The row counts and creation times should be consistent for all column sets if all the collections are automatic, but they might not be if there are manual collections for some subset of columns.

In any case, can we avoid the unnecessary work of calculating the linear regression for row counts, distinct counts, etc. multiple times if we expect the result to be the same for each column set?
___
*[pkg/sql/stats/forecast.go, line 206 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxtZ09T-O0X9H3PM-eA:-MxtZ09T-O0X9H3PM-eB:b-39zn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L206)):*
> ```Go
> 	for i := range forecastCols {
> 		observedCol := observedByCols[forecastCols[i]]
> 		forecast, score := forecastColumnStatistics(ctx, observedCol, at, n, minGoodnessOfFit)
> ```

nit: if you passed `observedCol[:n]` then you wouldn't need to pass `n` too
___
*[pkg/sql/stats/forecast.go, line 228 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxtdhtB-PLzuYrMJ8lP:-MxtdhtB-PLzuYrMJ8lQ:b-bo4bqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L228)):*
> ```Go
> // sorted by CreatedAt, descending (latest observation first). Parts of the
> // forecast with R² (goodness of fit) < minRequiredFit copy the equivalent part
> // from the latest observed statistics instead of the prediction. A score is
> ```

Can you explain the `score` a little more here. It looks like it's either `1` if a histogram was forecasted and `0` otherwise. Can we return a bool instead?
___
*[pkg/sql/stats/forecast.go, line 297 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxtWdzA1Pcc3psw9ut_:-MxtWdzA1Pcc3psw9uta:bfn4c1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L297)):*
> ```Go
> 	}
> 
> 	var histData *HistogramData = observed[0].HistogramData
> ```

nit: use `:=` instead of `var`
___
*[pkg/sql/stats/forecast.go, line 321 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxtbX7oA2vBXBh2W2h3:-MxtbX7p59Pw0Rmi9b4Z:b-7iljsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L321)):*
> ```Go
> 						tableID, columnIDs, observed[i].CreatedAt, err,
> 					)
> 					break
> ```

Should forecasting be aborted entirely if there is an error here, rather than continuing?
___
*[pkg/sql/stats/forecast.go, line 323 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxtcIhL9_bizTaDyNAj:-MxtcIhL9_bizTaDyNAk:b2ol66g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L323)):*
> ```Go
> 					break
> 				}
> 				quantiles = append(quantiles, q)
> ```

nit: you could reduce some code nesting by making a helper function that builds all the quantiles.
___
*[pkg/sql/stats/forecast.go, line 337 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxtblQOBw126mUOz1oj:-MxtblQOBw126mUOz1ok:b-cwmwkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L337)):*
> ```Go
> 							ctx, 2, "forecast for table %v columns %v quantile.toHistogram err %v",
> 							tableID, columnIDs, err,
> 						)
> ```

Same question as above, why continue if there is an error?
___
*[pkg/sql/stats/forecast.go, line 372 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxtdAKs-hLZASOCwA-z:-MxtdAKs-hLZASOCwA0-:b-ozejj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L372)):*
> ```Go
> 			nnDistinctCount--
> 		}
> 		hist.adjustCounts(nil, nnRowCount, nnDistinctCount)
> ```

It's not obvious to me why these counts exclude nulls? Is this a requirement of ` [...]

2022-03-15 19:12 UTC, rharding6373 submitted a review, later dismissed
Finished looking over the forecasts and only have a few additional comments. Appreciate all the code comments explaining the linear regressions etc.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-:-MyDzS0tDDE3qVnn3P3U:b-75yxgg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rharding6373, and @rytaft)

___
*[pkg/sql/stats/forecast.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp5unT6abfKoYmYAFw:-MyDw8Oj3wOeyy6FuKm8:b-ysyfzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L41)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Currently the logging is the only way. Maybe we need something better?
</blockquote></details>

I guess it's easy enough to see if the last observed stats were used in a forecast, so existing logging is fine.
___
*[pkg/sql/stats/forecast.go, line 384 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MyDmk220XGwiDh0fvW7:-MyDmk220XGwiDh0fvW8:b-2im5el) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L384)):*
> ```Go
> 			histData = &hd
> 			if predictedHist {
> 				score++
> ```

Is there ever a situation (e.g., if histograms are disabled) where forecasting stats might be valuable even if there is no histogram data?
___
*[pkg/sql/stats/forecast.go, line 849 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MyDtqDx2taJlRIs2_Hx:-MyDtqDx2taJlRIs2_Hy:b-idevm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L849)):*
> ```Go
> 			return nil, err
> 		}
> 		// Clamp instead of erring.
> ```

Looks like an error is returned anyway?
___
*[pkg/sql/stats/forecast.go, line 897 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MyDuVEq4hwSxb40h-j2:-MyDuVEq4hwSxb40h-j3:b565gpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L897)):*
> ```Go
> 		// Offset 0 means the TimeTZ will always have UTC as the timestamp.
> 		return tree.NewDTimeTZFromOffset(t.Round(roundTo), 0), nil
> 	case types.TimestampFamily:
> ```

If clamping for `TimestampFamily` and `TimestampTZFamily` are broken, why do we support converting them to/from quantiles and doing forecasts for these column types? It seems like it would make more sense to not support them for now and add them back when the issue is fixed.


<!-- Sent from Reviewable.io -->

2022-07-31 15:13 UTC, michae2 commented
Rebased on the previous patches, but haven't yet addressed feedback. Hold off on reviewing just yet.

2022-08-10 08:19 UTC, michae2 reviewed
At long last, this is RFAL. Thanks for your patience. I broke it into a handful of commits (the meat is in the last two).

Changes from the prototype:

* We're no longer trying to forecast all column sets for a table together. Instead, we're forecasting each column set independently. This makes `ForecastTableStatistics` much simpler, but could lead to inconsistent row counts for the same table. I don't think this will be a problem in practice, as statistics builder already has code to deal with this (e.g. from manual stats collected on individual columns).
* Got rid of the score thingy. The logic in `forecastColumnStatistics` is much simpler now: if all models have good fit we return a forecast, otherwise we return an error. The exception to this all-or-nothing logic is histograms: if everything else has a good fit, then we won't disqualify the forecast over a poor-fitting (or nonexistent) histogram model, instead we'll copy and adjust the latest observed histogram to match. This allows us to forecast columns whose type cannot be converted to quantile functions.
* Added a bunch of simple `forecastColumnStatistics` testcases. I'm planning to add more testing but this seems ready enough to review for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-:-N95n7zR82TgjhOh9i_a:b-pxd0yd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rharding6373, and @rytaft)

___
*[`pkg/sql/sem/tree/datum.go` line 2466 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxorUTA0Z0GhYBaoTxC:-N95lS-W5Ed8Vv2AOZir:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/datum.go#L2466)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Ahhh good catch! Let me work on this.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/datum.go` line 2763 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxov8QNAuWhj0VaNfJ9:-N95lWR44OedyfAZBTr2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/datum.go#L2763)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Same issue here with rounding up over MaxSupportedTime.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/decimal.go` line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpeNMi8uGbHNqGFQI7:-N95lYAr9Thg2pA-PSNH:b33b9ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/sem/tree/decimal.go#L103)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Oh, good point! I'll try this.
</blockquote></details>

Support for decimals was removed.
___
*[`pkg/sql/stats/automatic_stats.go` line 533 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxozbXN7VKCAgKtW_Ra:-N95leRf67BuUxa_JIG0:b-sjxohj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/automatic_stats.go#L533)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It seems like we only need the `CreatedAt` field at this time, maybe we should just store and pass a slice of timestamps instead of the whole proto.
</blockquote></details>

I reverted these changes.
___
*[`pkg/sql/stats/automatic_stats.go` line 563 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxph9g21UWjTFcjcQTS:-N95lhWnBB5s70t2lMfu:bok6a54) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/automatic_stats.go#L563)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `avgStatTime` sounds more like the time it took to collect the stats. What about `avgStatPeriod` ("period" as in the reciprocal of frequency).
</blockquote></details>

Reverted this.
___
*[`pkg/sql/stats/forecast.go` line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp7Nee5jEyWDuCAwSj:-N95jwix3IwBqdpASrPd:bhtk2we) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L49)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

+1 The meaning of the score is not clear to me. I think it deserves some more explanation, here, and maybe other places where the score is computed.
</blockquote></details>

Yes, this score business was really confusing, so it has been removed. Now we either predict everything if it all has good fit, or don't produce a forecast*

*with the exception of histograms. If everything else has a good fit, then we try to predict the histogram. If we cannot, we adjust the latest histogram. This is to allow forecasting over types whose histograms we cannot convert to quantile functions.
___
*[`pkg/sql/stats/forecast.go` line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxptAV83BkkAG_fZC_t:-N95k5FD4ZfOXrVCl5wE:b-brelnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L124)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Oh, nice. Let me try this tomorrow.
</blockquote></details>

I kept the columnset->string hack. If you hate it, I can change it.
___
*[`pkg/sql/stats/forecast.go` line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpqjM-0vJTwFWevREH:-N95mOgL0KU1MGvcqvqH:b1gnm3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L163)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Hmm, good point. Maybe when @rytaft is back we can discuss this. I don't have any intuition about which would be better.
</blockquote></details>

I left this as the average, but now bounded by 1 week past the latest collection. I'm nervous that if we go too far in the future (months? years? decades?) forecasts will become silly.
___
*[`pkg/sql/stats/forecast.go` line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxpoyz--QbDmj-grlLh:-N95kL9SA5TYQEfnbTD1:bs3oj6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L166)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

We need all of the RowCounts for a table to match. And then, related to that, if the forecast has a new row count, we need all of the histogram counts to add up to the new row count.
</blockquote></details>

Here's one big change from the prototype: now we're no longer forecasting all column sets. We're forecasting (or not forecasting) each column set independently. This means the row counts won't necessarily match, but statistics builder has code to deal with this already, so it seems fine.
___
*[`pkg/sql/stats/forecast.go` line 189 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxpte1_0d3CIrKoSFW1:-N95n-ZH8e-IWIhqVxFx:b-hkp7xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L189)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

:thinking:
</blockquote></details>

I shall investigate this.
___
*[`pkg/sql/stats/forecast.go` line 107 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxtp2toA28jdVY4B1Zz:-N95k0tYB_dCQ0_BNXVp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c903654bbbb2d351625e28a5864766b5a83f8af6/pkg/sql/stats/forecast.go#L107)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It'd be nice to de [...]

2022-08-10 08:31 UTC, michae2 reviewed
> I'm curious to know your thoughts behind the utility of the WITH FORECAST option? Do you see a need for users or us to see stats both with and without forecasts?

I do think we will need to see both with and without forecasts. (With for debugging, without for getting stats to inject.)

> If so, I'm assuming the optimizer will use the forecasted stats by default, so it might be more clear to show the forecasted stats by default and add a WITHOUT FORECAST option to SHOW STATS. If we plan to turn on/off forecasting in the optimizer with a session setting, then maybe it makes the most sense to have SHOW STATS use the same session setting to determine whether or not to show forecasted stats.

This is a good argument. `WITH` was handy because it's built into the parser already, but I could also hack `WITHOUT` in there.

How about I address this during the PR adding session / table settings?. I like the idea of showing the same thing the optimizer is seeing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-:-N95qeVWD_svQVMlM5zu:b-ptnhfr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rharding6373, @rytaft, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2022-08-11 00:01 UTC, yuzefovich reviewed
Great work! I didn't review this in great detail, so only surface-level nits and questions from me.

> Reviewed 17 of 18 files at r7, 5 of 5 files at r8, 2 of 2 files at r9, 3 of 3 files at r10, 6 of 7 files at r11, 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-:-N99C64z0qdAv_IgCYXj:bmyqn42)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rharding6373, @rytaft, and @yuzefovich)

___
*[`-- commits` line 17 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N98t9974OvA91KXgBTF):*
Seems concerning to me, but I'll defer to others.
___
*[`pkg/sql/show_stats.go` line 113 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N99AoRkErZ8B3dy5EcZ:-N99AoRlE-Ylo_2jWAGw:bv2jes1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4752cd4b8d9d8d37a3f998fc518e11cb757becbd/pkg/sql/show_stats.go#L113)):*
> ```Go
> 
> 			const (
> 				tableIDIdx = iota
> ```

nit: why this change? It doesn't seem that we're using the corresponding datum anywhere.
___
*[`pkg/sql/show_stats.go` line 184 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N99B93TDfELnbX1M0__:-N99B93TDfELnbX1M0_a:b-7hfqjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4752cd4b8d9d8d37a3f998fc518e11cb757becbd/pkg/sql/show_stats.go#L184)):*
> ```Go
> 				forecasts := stats.ForecastTableStatistics(ctx, p.EvalContext(), observed)
> 
> 				// Iterate in reverse order to match the ORDER BY "columnIDs".
> ```

I'm a bit confused - I think we only have `ORDER BY "createdAt"`.
___
*[`pkg/sql/stats/histogram.go` line 83 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N98rCUX0OqtkH2xMp6f:-N98rCUX0OqtkH2xMp6g:b-l55041) ([raw file](https://github.com/cockroachdb/cockroach/blob/479632bd435bbf7200b559d019a67c4b56aeebf2/pkg/sql/stats/histogram.go#L83)):*
> ```Go
> // []cat.HistogramBucket.
> func EquiDepthHistogram(
> 	evalCtx tree.CompareContext,
> ```

nit: should we do `s/evalCtx/compareCtx/` or something like that?
___
*[`pkg/sql/stats/histogram.go` line 320 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N98tZG94djKJE_CAL-7:-N98tZGA3hDiucwBUThk:bpp05jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df10863a14f928fc428fd17165cbf74c974e216/pkg/sql/stats/histogram.go#L320)):*
> ```Go
> }
> 
> // removeZeroBuckets reemoves any extra zero buckets if we don't need them
> ```

nit: `s/reemoves/removes/`.
___
*[`pkg/sql/stats/quantile.go` line 114 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N98soIU1faIyCThtfJF:-N98soIU1faIyCThtfJG:bfjceqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4d16e46cfa91e1df9915d247157cbf3f7555b30/pkg/sql/stats/quantile.go#L114)):*
> ```Go
> // TODO(michae2): Add support for DECIMAL, TIME, TIMETZ, and INTERVAL.
> func canMakeQuantile(version HistogramVersion, colType *types.T) bool {
> 	if version > 2 {
> ```

nit: is this an another safe guard in case someone bumps the histogram version but actually doesn't look at quantile functions? It seems like an overkill to me give the compile-time check above, but up to you.
___
*[`pkg/sql/stats/stats_cache.go` line 648 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N999gH6AZbD1yCCfQUc:-N999gH6AZbD1yCCfQUd:b-1c6hjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d92eb92d038666f13560bb7de025f48d8e40928/pkg/sql/stats/stats_cache.go#L648)):*
> ```Go
> 
> func (tabStat *TableStatistic) nonNullHistogram() histogram {
> 	if len(tabStat.Histogram) > 0 && tabStat.Histogram[0].UpperBound == tree.DNull {
> ```

Is it always guaranteed that the null bucket is the first one, regardless of a possible index direction?


<!-- Sent from Reviewable.io -->

2022-08-11 21:12 UTC, michae2 reviewed
TFYR!

Added a new commit to the middle of the stack that makes `SHOW STATISTICS` more deterministic.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-:-N9Djpve9h3hHpxL4Qfa:b1qllot)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rharding6373, @rytaft, and @yuzefovich)

___
*[`pkg/sql/show_stats.go` line 113 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N99AoRkErZ8B3dy5EcZ:-N9Df56V394IEUeqLtPe:bp2pv58) ([raw file](https://github.com/cockroachdb/cockroach/blob/4752cd4b8d9d8d37a3f998fc518e11cb757becbd/pkg/sql/show_stats.go#L113)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: why this change? It doesn't seem that we're using the corresponding datum anywhere.
</blockquote></details>

The tableID datum is used when we call `stats.NewTableStatisticProto(row)` down below.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 635 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp0jSp4axKPGNWAcqh:-N9DfU0HDNSlxbusn_GE:bl1t9ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/logictest/testdata/logic_test/distsql_stats#L635)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Because the most recent stats only contain `a` (they were created with `CREATE STATISTICS s8 ON a FROM [$t_id]`).

Hmm. The trouble is that we need to forecast stats for all current columns to get the row counts to match. But we base the "current columns" on the most recent stats. Hmm. Let me think about this.
</blockquote></details>

Now there are forecasts for the other columns as well.
___
*[`pkg/sql/stats/forecast.go` line 189 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxpte1_0d3CIrKoSFW1:-N9DfnBQB7itlwvGdswU:baodyo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L189)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I shall investigate this.
</blockquote></details>

Great question. As it turns out, column ID ordering was not guaranteed. So I've done two things:
1. Added another commit in the middle of the stack to make column ID ordering guaranteed going forward. This will help make `SHOW STATISTICS` output more deterministic, and will also fix some of our internal `DELETE` queries which are matching on column IDs.
2. Switched from my string-building function to the same string-key function used in `create_stats.go` which adds the column IDs to a FastIntMap first.
___
*[`pkg/sql/stats/histogram.go` line 320 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N98tZG94djKJE_CAL-7:-N9DiEFg8faQnfmhLbbn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7df10863a14f928fc428fd17165cbf74c974e216/pkg/sql/stats/histogram.go#L320)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/reemoves/removes/`.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/quantile.go` line 114 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N98soIU1faIyCThtfJF:-N9DiFx_-yngyQkghCBH:bjx6k0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4d16e46cfa91e1df9915d247157cbf3f7555b30/pkg/sql/stats/quantile.go#L114)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: is this an another safe guard in case someone bumps the histogram version but actually doesn't look at quantile functions? It seems like an overkill to me give the compile-time check above, but up to you.
</blockquote></details>

This is a guard for mixed-version clusters. In a mixed-version cluster an old-version node could read a row from `system.table_statistics` written by a new-version node, and might not understand what to do with it. (As I alluded to in that one commit message I think we need a similar guard in statistics builder, or at least in the stats cache.)
___
*[`pkg/sql/stats/stats_cache.go` line 648 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N999gH6AZbD1yCCfQUc:-N9Dj3UG4vEar_aZMd8d:bfdkmsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d92eb92d038666f13560bb7de025f48d8e40928/pkg/sql/stats/stats_cache.go#L648)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is it always guaranteed that the null bucket is the first one, regardless of a possible index direction?
</blockquote></details>

Great question. It looks like we're currently always putting the null bucket first, regardless of `NULLS LAST`? This could be a bug. Let me check.


<!-- Sent from Reviewable.io -->

2022-08-11 23:09 UTC, mgartner approved these changes
:tada: Great work! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 18 files at r7, 17 of 17 files at r13, 5 of 5 files at r14, 2 of 2 files at r15, 3 of 3 files at r16, 6 of 6 files at r17, 7 of 7 files at r18, 8 of 8 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-:-N9E7JQD2a4oxaDgnWyr:b-suikes)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rharding6373, @rytaft, and @yuzefovich)

___
*[`-- commits` line 17 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N98t9974OvA91KXgBTF):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Seems concerning to me, but I'll defer to others.
</blockquote></details>

Can you elaborate on your concerns with replacing eval.Context with tree.CompareContext?
___
*[`-- commits` line 19 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N9Dlvmu0tkDyaHEHpGL):*
You mention backporting to protect us in mixed version stated - a 22.1 node should try to read a forecasted stat? I would think it could read it fine because the histogram format doesn't change. But maybe we don't want to read a forecast histogram so that it operates like it would have before the mixed version state?

Edit: Actually I'm confused about your concern - forecasted stats are not persisted (right?) so they should cause no issues for older nodes. So do we need a new histogram version at all then?
___
*[`-- commits` line 40 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N9Dy3s21CcC54JgsrnB):*
Can you clarify in what places you'd potentially see a `nil` or zero-lenght histogram and document the meaning behind both? It looks like`EquiDepthHistogram` always returns a non-nil histogram, so I'm a bit confused.
___
*[`pkg/sql/stats/forecast.go` line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxptAV83BkkAG_fZC_t:-N9E8jMJ6JA5kWk4DJOP:b-kks4by) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L124)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I kept the columnset->string hack. If you hate it, I can change it.
</blockquote></details>

I think it's fine to leave for now. In general I'm concerned about a _set_ type that provides a way to retrieve values of the set in order - it might limit our ability to further optimize these sets. But that's irrelevant here.
___
*[`pkg/sql/stats/forecast.go` line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpqjM-0vJTwFWevREH:-N9E0MBD9WFDCH_fEeCA:b-4n8a9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L163)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I left this as the average, but now bounded by 1 week past the latest collection. I'm nervous that if we go too far in the future (months? years? decades?) forecasts will become silly.
</blockquote></details>

An upper bound sounds smart. I wonder if it makes sense for it to be in relation to the current time - if we collected stats 8 days ago, a 1 week upper bound won't help us. But then we could run into the same problem you are worried about... No need to change this now, but something to think about in the future.
___
*[`pkg/sql/stats/forecast.go` line 184 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N9E2wijDQKEphLVj8km:-N9E2wijDQKEphLVj8kn:bfi804j) ([raw file](https://github.com/cockroachdb/cockroach/blob/defc5affc1de71c316591d0e1a3e8033432e10cd/pkg/sql/stats/forecast.go#L184)):*
> ```Go
> 		if r2 < minRequiredFit {
> 			return yₙ, errors.Newf(
> 				"predicted %v R² %v below min required R² %v", name, r2, minRequiredFit,
> ```

These nice errors are created here, but they are never used in `ForecastTableStatistics`. I think this function could return an `ok bool` instead of an error - it doesn't really seem like a low goodness of fit is an error in the normal sense - just that an accurate forecast could not be generated.
___
*[`pkg/sql/stats/forecast_test.go` line 799 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-Mxp3YW98_il6ZOoU4nV:-N9E9VAq4y11UJpge5Fr:b-s1m28f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast_test.go#L799)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Interval was removed.
</blockquote></details>

:+1: Heh, I realized my comment from 5 months ago had an incorrect double negative, oops.
___
*[`pkg/sql/stats/stats_cache.go` line 648 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N999gH6AZbD1yCCfQUc:-N9E47ea1tR_Dl8YJawD:b-6s68i2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d92eb92d038666f13560bb7de025f48d8e40928/pkg/sql/stats/stats_cache.go#L648)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Great question. It looks like we're currently always putting the null bucket first, regardless of `NULLS LAST`? This could be a bug. Let me check.
</blockquote></details>

Oof. :crossed_fingers: this doesn't cause problems because the stats cache is shared by all sessions on a node, and null ordering can change query-to-query and [session-to-session](https://github.com/cockroachdb/cockroach/blob/4f52626b2d7774a7d016c83c0f054df95214118a/pkg/sql/vars.go#L1682).
___
*[`pkg/sql/stats/stats_cache.go` line 617 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N9E6aC619accsn2-k_p:-N9E6aC619accsn2-k_q:b-8yvk2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de1d50126b6850bbbfb72e75fe1f5c7a66f3754/pkg/sql/stats/stats_cache.go#L617)):*
> ```Go
> 			NumRange:      0,
> 			DistinctRange: 0,
> 			UpperBound:    tree.DNull,
> ```

nit: maybe we can combine this null-bucket adding logic with the function you added below?


<!-- Sent from Reviewable.io -->

2022-08-12 22:38 UTC, michae2 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77070)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @michae2, @rharding6373, @rytaft, and @yuzefovich)

___
*[`-- commits` line 17 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N98t9974OvA91KXgBTF):*
I think @yuzefovich's concern was with this note on the second commit:

> (I suspect that during upgrades to 22.2 the 22.1 statistics builder will choke on these statistics, so maybe we should also backport a version check to 22.1.)

My plan is to test this next week to see if this is actually a problem.
___
*[`-- commits` line 19 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N9Dlvmu0tkDyaHEHpGL):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You mention backporting to protect us in mixed version stated - a 22.1 node should try to read a forecasted stat? I would think it could read it fine because the histogram format doesn't change. But maybe we don't want to read a forecast histogram so that it operates like it would have before the mixed version state?

Edit: Actually I'm confused about your concern - forecasted stats are not persisted (right?) so they should cause no issues for older nodes. So do we need a new histogram version at all then?
</blockquote></details>

The backport concern isn't about forecasted stats. It's about the double-histograms for trigram indexes permitted by 963deb8. (Sorry, it snuck into this PR, I should have made it a separate PR.) Next week I'll test to see if this is actually a problem.
___
*[`-- commits` line 40 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N9Dy3s21CcC54JgsrnB):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you clarify in what places you'd potentially see a `nil` or zero-lenght histogram and document the meaning behind both? It looks like`EquiDepthHistogram` always returns a non-nil histogram, so I'm a bit confused.
</blockquote></details>

I added some comments to the fourth commit.
___
*[`pkg/sql/show_stats.go` line 184 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N99B93TDfELnbX1M0__:-N9JBy8wBcIhGSiCjiyT:b-2069n1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4752cd4b8d9d8d37a3f998fc518e11cb757becbd/pkg/sql/show_stats.go#L184)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm a bit confused - I think we only have `ORDER BY "createdAt"`.
</blockquote></details>

Ah, yeah, I was missing a commit. Now the fifth commit adds this `ORDER BY`.
___
*[`pkg/sql/stats/forecast.go` line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-MxpqjM-0vJTwFWevREH:-N9J6gd533p4dof7rOT1:b-ww64ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa07c6b290d902872a2c6f7875aae28d5c9e677/pkg/sql/stats/forecast.go#L163)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

An upper bound sounds smart. I wonder if it makes sense for it to be in relation to the current time - if we collected stats 8 days ago, a 1 week upper bound won't help us. But then we could run into the same problem you are worried about... No need to change this now, but something to think about in the future.
</blockquote></details>

Using the current time would be nice, but it would make forecasts non-deterministic, meaning we would sometimes get different forecasts when loading the stats cache during a cache miss or when using `SHOW STATISTICS ... WITH FORECAST`. To make the forecasts deterministic, they must only use information in the observed statistics.
___
*[`pkg/sql/stats/forecast.go` line 184 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N9E2wijDQKEphLVj8km:-N9J7NsmAF-gAELmVZnp:b-2lo0zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/defc5affc1de71c316591d0e1a3e8033432e10cd/pkg/sql/stats/forecast.go#L184)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

These nice errors are created here, but they are never used in `ForecastTableStatistics`. I think this function could return an `ok bool` instead of an error - it doesn't really seem like a low goodness of fit is an error in the normal sense - just that an accurate forecast could not be generated.
</blockquote></details>

It's a good point, and I thought about this too, but I'm a little reluctant to remove the error messages as they really helped during debugging and testing. I've added a vmodule log message that uses the error, so that we can find out why forecasts weren't generated if we need to.

Maybe if we ever added some kind of `FORECAST STATISTICS FOR COLUMN` command they could be shown to the user? Though that seems unlikely.
___
*[`pkg/sql/stats/histogram.go` line 83 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N98rCUX0OqtkH2xMp6f:-N9Dh06x4_K6QQX-8w4C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/479632bd435bbf7200b559d019a67c4b56aeebf2/pkg/sql/stats/histogram.go#L83)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we do `s/evalCtx/compareCtx/` or something like that?
</blockquote></details>

Done.
___
*[`pkg/sql/stats/stats_cache.go` line 648 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N999gH6AZbD1yCCfQUc:-N9J8n5xEn0dq0L35-lp:b-srfrqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d92eb92d038666f13560bb7de025f48d8e40928/pkg/sql/stats/stats_cache.go#L648)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Oof. :crossed_fingers: this doesn't cause problems because the stats cache is shared by all sessions on a node, and null ordering can change query-to-query and [session-to-session](https://github.com/cockroachdb/cockroach/blob/4f52626b2d7774a7d016c83c0f054df95214118a/pkg/sql/vars.go#L1682).
</blockquote></details>

Phew, looks like we're ok for now:

```
demo@127.0.0.1:26257/defaultdb> CREATE INDEX ON t (a NULLS LAST);
invalid syntax: statement ignored: at or near "last": syntax error: unimplemented: this syntax
SQLSTATE: 0A000
DETAIL: source SQL:
CREATE INDEX ON t (a NULLS LAST)
                           ^
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/6224/v22.2
```
___
*[`pkg/sql/stats/stats_cache.go` line 617 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/77070#-N9E6aC619accsn2-k_p:-N9J9VCw0YMNuscJYy1c:bwt94lu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de1d50126b6850bbbfb72e75fe1f5c7a66f3754/pkg/sql/stats/stats_cache.go#L617)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: maybe we can combine this null-bucket adding logic with the function you added below?
</blockquote></details>

We could make `DecodeHistogramBuckets` call `setHistogramBuckets` after it has converted the `HistogramData` to `[]cat.HistogramBucket` but that would incur an extra copy of the buckets which we're normally able to avoid except when forecasting... If it's alright with you, I'll leave it this way for now. (Maybe we'll come back to this when `NULLS LAST` can be used on indexes, see below.)


<!-- Sent from Reviewable.io -->

2022-08-12 23:57 UTC, michae2 commented
TFYRs!!

bors r+

2022-08-12 23:59 UTC, michae2 commented
bors r+

2022-08-13 04:23 UTC, merged