changefeedccl: enable changefeeds on multiple column families
cockroachdb/cockroach pull request #77084
Opened 2022-02-26 21:00 UTC by HonoreDB

Changes the behavior when starting a changefeed on a table
with multiple column families. Previously, this would error.
Now, we create a feed that will emit individual messages per
column family. Primary key columns will appear in the key
for all column families, but only in the value in the families
they are in. Avro schema names will include the family name.

For UX simplicity, adding a column family to a table that
previously had only one will cause the feed to error out
as before.

Release note (general change): changefeeds can now be created on tables with more than one column family.

2022-02-26 21:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/77084)
<!-- Reviewable:end -->

2022-02-27 18:37 UTC, sherman-grewal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss, @gh-casper, @HonoreDB, and @miretskiy)

___
*[pkg/ccl/changefeedccl/avro.go, line 789 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwRwEC9bp40-CQBlmg:-MwwRwEC9bp40-CQBlmh:b-pge3eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/avro.go#L789)):*
> ```Go
> 	}
> 
> 	include := make(map[descpb.ColumnID]struct{})
> ```

nit: I think you could define the length of `include` to be `len(family.ColumnIDs)`
___
*[pkg/ccl/changefeedccl/encoder.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwSLTEA09l7hMHvSDq:-MwwSLTEA09l7hMHvSDr:b25yltc) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/encoder.go#L204)):*
> ```Go
> 				// Not implemented yet
> 			default:
> 				// fall through to error
> ```

Did we want to return an error for the error/not implemented cases?
___
*[pkg/ccl/changefeedccl/encoder.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwSw7V0bHf4v1OJTi2:-MwwSw7V0bHf4v1OJTi3:b-pge3eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/encoder.go#L256)):*
> ```Go
> 			return nil, err
> 		}
> 		include := make(map[descpb.ColumnID]struct{})
> ```

nit: I think you could define the length of `include` to be `len(family.ColumnIDs)`
___
*[pkg/ccl/changefeedccl/encoder.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwTDRoAW1AGuXkJTcx:-MwwTDRoAW1AGuXkJTcy:b25yltc) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/encoder.go#L470)):*
> ```Go
> 				// Not implemented yet
> 			default:
> 				// fall through to error
> ```

Did we want to return an error for the error/not implemented cases?
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwQgEl9ArsR5PE16Zu:-MwwQgEl9ArsR5PE16Zv:bwdlvu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/rowfetcher_cache.go#L256)):*
> ```Go
> 	// Necessary because virtual columns are not populated.
> 	// TODO(radu): should we stop requesting those columns from the fetcher?
> 	rf.IgnoreUnexpectedNulls = true
> ```

I believe that we allow users to choose between [omitting virtual columns or emitting null](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/changefeedbase/options.go#L60). If a user were to choose to emit null for virtual columns, would setting `IgnoreUnexpectedNulls = true` become an issue?
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1711 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwOmn_0ewbpStPjUWY:-MwwOmn_0ewbpStPjUWZ:b9m9vpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeed_test.go#L1711)):*
> ```Go
> 		foo := feed(t, f, `CREATE CHANGEFEED FOR foo`)
> 		defer closeFeed(t, foo)
> 		assertPayloads(t, foo, []string{
> ```

It would be nice to extend this test to include deleting values from foo and ensuring that the changefeed emits the desired messages for the column families. 


<!-- Sent from Reviewable.io -->

2022-02-28 02:20 UTC, ajwerner commented
Drive-by feedback on message:

> Release note (general change): changefeeds can now be created on tables with more than one column family.

I feel like we generally mark changefeed changes as `(enterprise change)`. This release note could benefit from explaining the meat of *how* they are now supported and the semantics of their support. Consider moving most of the commit message into the release note.

2022-02-28 16:04 UTC, miretskiy requested changes
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss, @gh-casper, @HonoreDB, and @sherman-grewal)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-dgFqAmnC-b5eK4_3):*
Can you expand on why this is?
___
*[-- commits, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-dTbo38Snt6oRgXWB):*
I feel this description needs to be expanded significantly.
We should explain for example, why we are not emitting single message.
Perhaps give some examples of the messages; Also, I think this falls under "enterprise change".
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 783 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-gD3T-rA9AQtCXFTt:-Mx-gD3T-rA9AQtCXFTu:b-dmkqh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeed_processors.go#L783)):*
> ```Go
> 	} else {
> 		rf, err = c.rfCache.RowFetcherForTableDesc(desc)
> 	}
> ```

Do we need this split? Each key always has column family... Why not just always use column family and avoid having
this if/else?
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-gbsr4Gn24aK6dRSx:-Mx-gbsr4Gn24aK6dRSy:b-2spm1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeed_stmt.go#L544)):*
> ```Go
> 			if len(table.GetFamilies()) > 1 {
> 				typ = jobspb.ChangefeedTargetSpecification_EACH_FAMILY
> 			}
> ```

We should think about whether or not we need to have an opt in option here (`enable_multi_family` or some such).
I understand that we now support multiple families -- and so it stands to reason that we should
just enable this by default.  However, we are emitting multiple messages per row.  I understand why we are doing this,  but I'm not sure our customers would necessarily have the same intuitive understanding.  Running changefeeds on multi-family is not intuitive; has implications (multiple messages per row) -- even could have interesting downstream sink implications (such as 1 (or few) family updates being written to one file, and the rest to another file).
Because of this, I want to have an opt in.  Thoughts?
___
*[pkg/ccl/changefeedccl/encoder.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwSLTEA09l7hMHvSDq:-Mx-oNoI-tzayympNcG2:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/encoder.go#L204)):*
<details><summary><i>Previously, sherman-grewal (Sherman) wrote…</i></summary><blockquote>

Did we want to return an error for the error/not implemented cases?
</blockquote></details>

Ditto.
___
*[pkg/ccl/changefeedccl/encoder.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwTDRoAW1AGuXkJTcx:-Mx02pmd6koDTAY49eNS:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/encoder.go#L470)):*
<details><summary><i>Previously, sherman-grewal (Sherman) wrote…</i></summary><blockquote>

Did we want to return an error for the error/not implemented cases?
</blockquote></details>

+1
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-g-_U7q_7WcBhvFMa:-Mx-g-_U7q_7WcBhvFMb:bfnnmkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/rowfetcher_cache.go#L151)):*
> ```Go
> 	}
> 
> 	return tableDesc, &family, nil
> ```

why return a pointer? Just for the purpose of 0 value in case of an error?
Maybe just return 0 family?
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-f53z6IypeKboqzLq:-Mx-f53z6IypeKboqzLr:bwtdjjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/rowfetcher_cache.go#L234)):*
> ```Go
> 
> 	// TODO (zinger): fetchColumnIDs should be only the family and the primary key,
> 	// but this seems to cause an error.
> ```

nit: Can you rephrase as a to do?
___
*[pkg/ccl/changefeedccl/changefeedbase/validate.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-e8uqCTOrahCtptz8:-Mx-e8uqCTOrahCtptz9:b2gsuz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeedbase/validate.go#L54)):*
> ```Go
> 		return errors.Errorf(
> 			`going from single to multiple column families is not currently supported: %s now has %d`,
> 			tableDesc.GetName(), len(tableDesc.GetFamilies()))
> ```

nit: maybe rephrase?  "CHANGEFEED cannot target multiple column families"?
Not sure what the right phrasing might be.. but this one just sounds strange.
We can also include with hint? maybe?
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx03EWvAzKmka76axxW:-Mx03EWvAzKmka76axxX:bymmrsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeed_test.go#L1743)):*
> ```Go
> 		sqlDB := sqlutils.MakeSQLRunner(db)
> 
> 		sqlDB.Exec(t, `CREATE TABLE foo (a INT PRIMARY KEY, b STRING, c STRING, FAMILY most (a,b), FAMILY justc (c))`)
> ```

let's add virtual columns, and also test what happens during deletes.

Is it possible to schema change to move column from 1 column family to another? If so... we should test for that too.
Also would be nice to test what happens if you have a nullable column in a column family: say, "a, b" in 1 family, "c nullable" in another family.  Insert values for "a,b" -- nothing for "c". What happens?


<!-- Sent from Reviewable.io -->

2022-02-28 21:41 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss, @gh-casper, @HonoreDB, @miretskiy, and @sherman-grewal)

___
*[-- commits, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-dTbo38Snt6oRgXWB):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I feel this description needs to be expanded significantly.
We should explain for example, why we are not emitting single message.
Perhaps give some examples of the messages; Also, I think this falls under "enterprise change".
</blockquote></details>

Done. As discussed in slack I'm adding a mostly-identical release note as a "sql change" since core changefeeds are also benefiting.
___
*[pkg/ccl/changefeedccl/avro.go, line 789 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwRwEC9bp40-CQBlmg:-Mx1FGA75XdHt-ZeQW57:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/avro.go#L789)):*
<details><summary><i>Previously, sherman-grewal (Sherman) wrote…</i></summary><blockquote>

nit: I think you could define the length of `include` to be `len(family.ColumnIDs)`
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 783 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-gD3T-rA9AQtCXFTt:-Mx1FHXG4M_OcItB6Z7f:bhmhk5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeed_processors.go#L783)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we need this split? Each key always has column family... Why not just always use column family and avoid having
this if/else?
</blockquote></details>

Nice catch! Done.
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-gbsr4Gn24aK6dRSx:-Mx1FYDI3Wz9gvLLg0HP:byyrlla) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeed_stmt.go#L544)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

We should think about whether or not we need to have an opt in option here (`enable_multi_family` or some such).
I understand that we now support multiple families -- and so it stands to reason that we should
just enable this by default.  However, we are emitting multiple messages per row.  I understand why we are doing this,  but I'm not sure our customers would necessarily have the same intuitive understanding.  Running changefeeds on multi-family is not intuitive; has implications (multiple messages per row) -- even could have interesting downstream sink implications (such as 1 (or few) family updates being written to one file, and the rest to another file).
Because of this, I want to have an opt in.  Thoughts?


</blockquote></details>

Maybe just a pg warning would accomplish the same thing without the extra complexity of a setting?
___
*[pkg/ccl/changefeedccl/encoder.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwSLTEA09l7hMHvSDq:-Mx1FhUV558Gyp9un5e3:b-9z4wii) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/encoder.go#L204)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

I mean in theory but it's unreachable right now and the next time I touch this will be to implement all current types, so I got lazy.
___
*[pkg/ccl/changefeedccl/encoder.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwSw7V0bHf4v1OJTi2:-Mx1FuinDwZZSbj6FxB1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/encoder.go#L256)):*
<details><summary><i>Previously, sherman-grewal (Sherman) wrote…</i></summary><blockquote>

nit: I think you could define the length of `include` to be `len(family.ColumnIDs)`
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/encoder.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwTDRoAW1AGuXkJTcx:-Mx1FxN1Esa05QyWzB0F:b-vxui05) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/encoder.go#L470)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

+1
</blockquote></details>

See above re: my laziness, I'll see if there's a quick way of tidying this up though.
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-g-_U7q_7WcBhvFMa:-Mx0_jjG13MtN-MBlhn4:bc10ka3) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/rowfetcher_cache.go#L151)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why return a pointer? Just for the purpose of 0 value in case of an error?
Maybe just return 0 family?
</blockquote></details>

Just for the purpose of an error, yeah. The default column family has ID 0 so it didn't feel completely safe to use the zero family as a null value.
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-f53z6IypeKboqzLq:-Mx1G4YCBMnfcPwIH5Ro:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/rowfetcher_cache.go#L234)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: Can you rephrase as a to do?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwQgEl9ArsR5PE16Zu:-Mx0aG4B6Wk-KW3JaXYC:b3j3fcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/rowfetcher_cache.go#L256)):*
<details><summary><i>Previously, sherman-grewal (Sherman) wrote…</i></summary><blockquote>

I believe that we allow users to choose between [omitting virtual columns or emitting null](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/changefeedbase/options.go#L60). If a user were to choose to emit null for virtual columns, would setting `IgnoreUnexpectedNulls` become an issue?
</blockquote></details>

IgnoreUnexpectedNulls means don't error out when you get a null in a non-nullable column, so this is actually necessary for emitting nulls.
___
*[pkg/ccl/changefeedccl/changefeedbase/validate.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-e8uqCTOrahCtptz8:-Mx1G6Fk91sWTK25JKYY:bvudy74) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeedbase/validate.go#L54)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: maybe rephrase?  "CHANGEFEED cannot target multiple column families"?
Not sure what the right phrasing might be.. but this one just sounds strange.
We can also include with hint? maybe?
</blockquote></details>

Edited.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1711 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwOmn_0ewbpStPjUWY:-Mx1G7x73O2PzyHznaAf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeed_test.go#L1711)):*
<details><summary><i>Previously, sherman-grewal (Sherman) wrote…</i></summary><blockquote>

It would be nice to extend this test to include deleting  [...]

2022-02-28 22:35 UTC, miretskiy requested changes
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss, @gh-casper, @HonoreDB, @miretskiy, and @sherman-grewal)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 779 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx1SaijCiiq4ieNunFb:-Mx1SaijCiiq4ieNunFc:bit5uub) ([raw file](https://github.com/cockroachdb/cockroach/blob/4241e32fb1fc79d2ea1ce510cee6f28a09b5de6f/pkg/ccl/changefeedccl/changefeed_processors.go#L779)):*
> ```Go
> 	r.familyID = *family
> 	var rf *row.Fetcher
> 	rf, err = c.rfCache.RowFetcherForColumnFamily(desc, *family)
> ```

I guess that's why I asked before why we return family id by pointer.. Because now, I wonder if family could be nil.
And i'd rather not wonder :).
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-gbsr4Gn24aK6dRSx:-Mx1SobU5Bce6A8ERhnO:bfdkw1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeed_stmt.go#L544)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Maybe just a pg warning would accomplish the same thing without the extra complexity of a setting?
</blockquote></details>

I'm still of the opinion we should have an option; but I'm ready to be convinced otherwise.  Perhaps quick chat w/ @amruss ?
___
*[pkg/ccl/changefeedccl/encoder.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwSLTEA09l7hMHvSDq:-Mx1T0M84jSf7T8bUYoe:bbkfllh) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/encoder.go#L204)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I mean in theory but it's unreachable right now and the next time I touch this will be to implement all current types, so I got lazy.
</blockquote></details>

Hmm... Let's just slap assertion failedf.
___
*[pkg/ccl/changefeedccl/changefeedbase/validate.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-e8uqCTOrahCtptz8:-Mx1TB5N-zY2kwooISPp:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeedbase/validate.go#L54)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Edited.
</blockquote></details>

Nice.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx03EWvAzKmka76axxW:-Mx1TKLR6izfm4ErYMZV:bropzsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/changefeed_test.go#L1743)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Added all these tests and more. Except it doesn't look possible right now to move a column to another family, so we're spared that confusion for now. In the case where all columns in a family are null on an insert, we don't emit anything, which seems like the right behavior but is probably interesting enough to be in the docs.
</blockquote></details>

Ack.  I mostly wanted it for documentation purposes in this test.  


<!-- Sent from Reviewable.io -->

2022-03-03 02:57 UTC, HonoreDB commented
Ready for re-review after incorporating the results of an impromptu design meeting over family names and options.

2022-03-03 12:52 UTC, miretskiy approved these changes
This change <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  from me.  Just few minor nits, and question re option name.  This is exciting.

> Reviewed 1 of 6 files at r2, 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-:-MxEpev02zu_7dwQWELO:bsuyg4p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @amruss, @gh-casper, @HonoreDB, @miretskiy, and @sherman-grewal)

___
*[-- commits, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MxEnVFY3ALbM92rtn4S):*
Probably needs to be expanded w/ details on naming.
___
*[pkg/ccl/changefeedccl/avro.go, line 793 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MxEo59y1PaLzc1BUIPy:-MxEo59y1PaLzc1BUIPz:bw51d6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/99de83e462c449e6de5ad442a208186bd351dcc7/pkg/ccl/changefeedccl/avro.go#L793)):*
> ```Go
> 	for _, colID := range family.ColumnIDs {
> 		include[colID] = yes
> 	}
> ```

this is called many times (once for each row); would be nice not to recreate maps every time.
This could be a TODO since this might involve a bit of refactoring.  You'r call.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 779 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx1SaijCiiq4ieNunFb:-MxEoTkzA2QcMFx_HnGI:blttcnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4241e32fb1fc79d2ea1ce510cee6f28a09b5de6f/pkg/ccl/changefeedccl/changefeed_processors.go#L779)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I guess that's why I asked before why we return family id by pointer.. Because now, I wonder if family could be nil.
And i'd rather not wonder :).
</blockquote></details>

Still think returning family as a regular ID is better.
___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MxEon-8B6lnyhHKV4wz:-MxEon-8B6lnyhHKV4x-:b-jslxky) ([raw file](https://github.com/cockroachdb/cockroach/blob/99de83e462c449e6de5ad442a208186bd351dcc7/pkg/ccl/changefeedccl/changefeedbase/options.go#L52)):*
> ```Go
> 	OptSchemaChangeEvents       = `schema_change_events`
> 	OptSchemaChangePolicy       = `schema_change_policy`
> 	OptSplitColumnFamilies      = `split_column_families`
> ```

My preference would be `enable_multi_family`.  @amruss ?
___
*[pkg/ccl/changefeedccl/changefeedbase/validate.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MxEoxvL5nVWptpOj1b7:-MxEoxvL5nVWptpOj1b8:bhibdju) ([raw file](https://github.com/cockroachdb/cockroach/blob/99de83e462c449e6de5ad442a208186bd351dcc7/pkg/ccl/changefeedccl/changefeedbase/validate.go#L61)):*
> ```Go
> 	if !columnFamiliesOpt && len(tableDesc.GetFamilies()) != 1 {
> 		return errors.Errorf(
> 			`CHANGEFEED targeting a table (%s) with multiple column families requires WITH split_column_families and will emit multiple events per row.`,
> ```

Let's not hard code `split_column_familes` and use option name in fmt.


<!-- Sent from Reviewable.io -->

2022-03-03 19:18 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77084)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @amruss, @gh-casper, @miretskiy, and @sherman-grewal)

___
*[-- commits, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx-dgFqAmnC-b5eK4_3):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Can you expand on why this is?
</blockquote></details>

Done.
___
*[-- commits, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MxEnVFY3ALbM92rtn4S):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Probably needs to be expanded w/ details on naming.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/avro.go, line 793 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MxEo59y1PaLzc1BUIPy:-MxG9jpX2IA6E1vu6aMQ:bvr6yad) ([raw file](https://github.com/cockroachdb/cockroach/blob/99de83e462c449e6de5ad442a208186bd351dcc7/pkg/ccl/changefeedccl/avro.go#L793)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

this is called many times (once for each row); would be nice not to recreate maps every time.
This could be a TODO since this might involve a bit of refactoring.  You'r call.
</blockquote></details>

This particular instance of this pattern is actually cached and only called once per table version, but I think I'm doing the same thing elsewhere and will add TODOs there. Same for virtual column stuff.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 779 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-Mx1SaijCiiq4ieNunFb:-MxGCJMc12qKPaL9cyBJ:bhqivoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4241e32fb1fc79d2ea1ce510cee6f28a09b5de6f/pkg/ccl/changefeedccl/changefeed_processors.go#L779)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Still think returning family as a regular ID is better.
</blockquote></details>

I will argue about this later but making this change for now.
___
*[pkg/ccl/changefeedccl/encoder.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MwwTDRoAW1AGuXkJTcx:-MxGC_tFDbeFWk3O87HM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293b7968c8ec515b0789047166bac49388476393/pkg/ccl/changefeedccl/encoder.go#L470)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

See above re: my laziness, I'll see if there's a quick way of tidying this up though.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MxEon-8B6lnyhHKV4wz:-MxGCd0Y8eymyrKQVMJV:b-2am6e0) ([raw file](https://github.com/cockroachdb/cockroach/blob/99de83e462c449e6de5ad442a208186bd351dcc7/pkg/ccl/changefeedccl/changefeedbase/options.go#L52)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

My preference would be `enable_multi_family`.  @amruss ?
</blockquote></details>

My thought for this was to leave semantic room for other ways of handling multi family later (merging the whole row or emitting only the primary).
___
*[pkg/ccl/changefeedccl/changefeedbase/validate.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77084#-MxEoxvL5nVWptpOj1b7:-MxGCt5798YUXn1ndSM_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99de83e462c449e6de5ad442a208186bd351dcc7/pkg/ccl/changefeedccl/changefeedbase/validate.go#L61)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Let's not hard code `split_column_familes` and use option name in fmt.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-03 19:21 UTC, HonoreDB commented
bors r=[miretskiy]

2022-03-04 18:57 UTC, HonoreDB commented
bors r=[miretskiy]

2022-03-04 21:15 UTC, merged