kv/storage: introduce and track local timestamps for MVCC versions
cockroachdb/cockroach pull request #77342
Opened 2022-03-03 18:45 UTC by nvanbenschoten

Fixes #36431.
Fixes #49360.
Replaces #72121.

**NOTE**: this commit does not yet handle mixed-version compatibility and is not intended to merge for the v22.1 release.

This commit fixes the potential for a stale read as detailed in #36431 using the **_"remember when intents were written"_** approach described in https://github.com/cockroachdb/cockroach/issues/36431#issuecomment-586134702 and later expanded on in https://github.com/cockroachdb/cockroach/pull/72121#issuecomment-954433047.

This bug requires a combination of skewed clocks, multi-key transactions split across ranges whose leaseholders are stored on different nodes, a transaction read refresh, and the use of observed timestamps to avoid an uncertainty restart. With the combination of these four factors, it was possible to construct an ordering of events that violated real-time ordering and allowed a transaction to observe a stale read. Upon the discovery of the bug, we [introduced](https://github.com/cockroachdb/jepsen/pull/19) the `multi-register` test to the Jepsen test suite, and have since observed the test fail when combined with the `strobe-skews` nemesis due to this bug in #49360 (and a few issues linked to that one). This commit stabilizes that test.

### Explanation

The combination of all of the factors listed above can lead to the stale read because it breaks one of the invariants that the observed timestamp infrastructure[^1] relied upon for correctness. Specifically, observed timestamps relied on the guarantee that a leaseholder's clock must always be equal to or greater than the version timestamp of all writes that it has served. However, this guarantee did not always hold. It does hold for non-transactional writes. It also holds for transactions that perform all of their intent writes at the same timestamp and then commit at this timestamp. However, it does not hold for transactions which move their commit timestamp forward over their lifetime before committing, writing intents at different timestamps along the way and "pulling them up" to the commit timestamp after committing.

In violating the invariant, this third case reveals an ambiguity in what it means for a leaseholder to "serve a write at a timestamp". The meaning of this phrase is straightforward for non-transactional writes. However, for an intent write whose original timestamp is provisional and whose eventual commit timestamp is stored indirectly in its transaction record at its time of commit, the meaning is less clear. This reconciliation to move the intent write's timestamp up to its transaction's commit timestamp is asynchronous from the transaction commit (and after it has been externally acknowledged). So even if a leaseholder has only served writes with provisional timestamps up to timestamp 100 (placing a lower bound on its clock of 100), it can be in possession of intents that, when resolved, will carry a timestamp of 200. To uphold the real-time ordering property, this value must be observed by any transaction that begins after the value's transaction committed and was acknowledged. So for observed timestamps to be correct as currently written, we would need a guarantee that this value's leaseholder would never return an observed timestamp < 200 at any point after the transaction commits. But with the transaction commit possibly occurring on another node and with communication to resolve the intent occurring asynchronously, this seems like an impossible guarantee to make.

This would appear to undermine observed timestamps to the point where they cannot be used. However, we can claw back correctness without sacrificing performance by recognizing that only a small fraction[^2] of transactions commit at a different timestamps than the one they used while writing intents. We can also recognize that if we were to compare observed timestamps against the timestamp that a committed value was originally written (its provisional value if it was once an intent) instead of the timestamp that it had been moved to on commit, then the invariant would hold.

This commit exploits this second observation by adding a second timestamp to each MVCC key called the "local timestamp". The MVCC key's existing version timestamp dictates the key's visibility to readers and is tied to the writer's commit timestamp. The local clock timestamp records the value of the local HLC clock on the leaseholder when the key was originally written. It is used to make claims about the relative real time ordering of the key's writer and readers when comparing a reader's uncertainty interval (and observed timestamps) to the key. Ignoring edge cases, readers with an observed timestamp from the key's leaseholder that is greater than the local clock timestamp stored in the key cannot make claims about real time ordering and must consider it possible that the key's write occurred before the read began. However, readers with an observed timestamp from the key's leaseholder that is less than the clock timestamp can claim that the reader captured that observed timestamp before the key was written and therefore can consider the key's write to have been concurrent with the read. In doing so, the reader can avoid an uncertainty restart.

For more, see the updates made in this commit to `pkg/kv/kvserver/observedts/doc.go`.

To avoid the bulk of the performance hit from adding this new timestamp to the MVCC key encoding, the commit optimizes the clock timestamp away in the common case where it leads the version timestamp. Only in the rare cases where the local timestamp trails the version timestamp (e.g. future-time writes, async intent resolution with a new commit timestamp) does the local timestamp need to be explicitly represented in the key encoding. This is possible because it is safe for the local clock timestamp to be rounded down, as this will simply lead to additional uncertainty restarts. However, it is not safe for the local clock timestamp to be rounded up, as this could lead to stale reads.

### Future improvements

As noted in https://github.com/cockroachdb/cockroach/pull/72121#issuecomment-954433047, this commit paves a path towards the complete removal of synthetic timestamps, which were originally introduced in support of non-blocking transactions and GLOBAL tables.

The synthetic bit's first role of providing dynamic typing for `ClockTimestamps` is no longer necessary now that we never need to "push" transaction-domain timestamps into HLC clocks. Instead, the invariant that underpins observed timestamps is enforced by "pulling" local timestamps from the leaseholder's HLC clock.

The synthetic bit's second role of disabling observed timestamps is replaced by the generalization provided by "local timestamps". Local timestamps precisely track when an MVCC version was written in the leaseholder's clock timestamp domain. This establishes a total ordering across clock observations (local timestamp assignment for writers and observed timestamps for readers) and establish a partial ordering between writer and reader transactions. As a result, the use of observed timestamps during uncertainty checking becomes a comparison between two `ClockTimestamps`, the version's local timestamp and the reader's observed timestamp.

### Correctness testing

I was not able to stress `jepsen/multi-register/strobe-skews` hard enough to cause it to fail, even on master. We've only seen the test fail a handful of times over the past few years, so this isn't much of a surprise. Still, this prevents us from saying anything concrete about an reduced failure rate.

However, the commit does add a new test called `TestTxnReadWithinUncertaintyIntervalAfterIntentResolution` which controls manual clocks directly and was able to deterministically reproduce the stale read before this fix in a few different ways. After this fix, the test passes.

### Performance analysis

This correctness fix will lead to an increased rate of transaction retries under some workloads.

TODO( [...]

2022-03-03 18:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/77342)
<!-- Reviewable:end -->

2022-03-07 20:25 UTC, sumeerbhola requested changes
(read a bit of this -- flushing comments)

> Reviewed 4 of 7 files at r1, 5 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-:-Mxa2jEZ5XNTEat53SCh:blxw0g1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @stevendanna, and @sumeerbhola)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mx_zsNM0g0LOFnWdTfh:-Mx_zsNM0g0LOFnWdTfi:b-qze2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a12b2f1c97f34ab4922f06d0dd6f870efe3e3ca8/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L648)):*
> ```Go
> 	if linearizable && !readOnly {
> 		waitUntil = waitUntil.Add(tc.clock.MaxOffset().Nanoseconds(), 0)
> 	}
> ```

Would be nice to have a comment here on what kinds of transactions won't need to wait.
___
*[pkg/kv/kvserver/replica_send.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mxa-4xqEBUKN0oqEZ_M:-Mxa-4xqEBUKN0oqEZ_N:b-9dhwii) ([raw file](https://github.com/cockroachdb/cockroach/blob/a12b2f1c97f34ab4922f06d0dd6f870efe3e3ca8/pkg/kv/kvserver/replica_send.go#L268)):*
> ```Go
> 	// evaluation.
> 	if txn.WriteTimestamp.LessEq(r.Clock().Now()) {
> 		return nil // no wait fast-path
> ```

same comment here
___
*[pkg/kv/kvserver/replica_tscache.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mxa-ILw5FFuLxK5JJ8P:-Mxa-ILw5FFuLxK5JJ8Q:b1j4dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd15d3aef470a7838a0d770e408fa0d9f02d0671/pkg/kv/kvserver/replica_tscache.go#L62)):*
> ```Go
> 	// property this is asserting is no longer quite as important, so we can
> 	// disable the check. However, it would still be nice to track down how we
> 	// can hit this.
> ```

was this TODO stale and has been fixed?
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mxa0LPy6AJYGHxXkfd9:-Mxa0LPy6AJYGHxXkfdA:b-4c1f9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e245c923e4251887e6a724c957e1cf028eec3b9/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L573)):*
> ```Go
> 		// resolve the intent to timestamp 11 but leave its local timestamp at 8
> 		// then the reader would consider the value "uncertain" upon re-evaluation.
> 		// However, if the reader also updates the value's local timestamp to 16
> ```

In this example will this mean that we don't need to write the local timestamp since it is >= txn commit timestamp?
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 589 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mxa0cIG279JfzGhmOnr:-Mxa0cIG279JfzGhmOns:b-ylu676) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e245c923e4251887e6a724c957e1cf028eec3b9/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L589)):*
> ```Go
> 		// commits and acknowledges its client. This could not lead to the pusher
> 		// serving a stale read, but it could lead to other transactions serving
> 		// stale reads.
> ```

I see what this is saying, but a small example here would make it super clear for a reader.
___
*[pkg/roachpb/api.proto, line 1142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mxa1YG88CL31PzJ3GUo:-Mxa1YG88CL31PzJ3GUp:b-ui9fv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e245c923e4251887e6a724c957e1cf028eec3b9/pkg/roachpb/api.proto#L1142)):*
> ```protobuf
>   // from a different node than the node which evaluates the ResolveIntent
>   // request, it will be ignored and the intent's local timestamp will not be
>   // changed.
> ```

This could use a short example of the hazard in the absence of this ignore behavior.


<!-- Sent from Reviewable.io -->

2022-04-07 21:59 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 11 of 22 files at r10, 14 of 14 files at r11, 9 of 9 files at r12, 72 of 72 files at r13, 34 of 51 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-:-N-51UZiCVooM95Q7dH-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @stevendanna, and @sumeerbhola)

___
*[pkg/kv/kvserver/replica_proposal.go, line 656 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-N-4sZO72-9oi38ZOixB:-N-4sZO72-9oi38ZOixC:b-ngiisr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1e0a097d7057deada8079526fdb446b972ec78/pkg/kv/kvserver/replica_proposal.go#L656)):*
> ```Go
> 	idKey kvserverbase.CmdIDKey,
> 	ba *roachpb.BatchRequest,
> 	st *kvserverpb.LeaseStatus,
> ```

my familiarity with leasing is minimal, so assuming someone from KV will look carefully at those changes.
___
*[pkg/kv/kvserver/replica_send.go, line 251 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-N-4o_bHB6rcVlCybtXI:-N-4o_bHB6rcVlCybtXJ:bde53mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b01b0a560127fc45b732c6660a243a4d41a7bf/pkg/kv/kvserver/replica_send.go#L251)):*
> ```Go
> 	//   https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20200811_non_blocking_txns.md
> 	//
> 	// However, if a transaction has a commit trigger, the side-effects of the
> ```

just for my curiosity what is an example of a future time txn with a commit trigger. My understanding of the kinds of commit triggers is based on the list in `RunCommitTrigger` which seems mostly to do with splits and merges.
___
*[pkg/storage/mvcc.go, line 639 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-N-4tZI9ECno4UpAL5Ma:-N-4tZI9ECno4UpAL5Mb:b9lj87y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f4aa66ccd0933d2659f24065441c99ae7e1bfb0/pkg/storage/mvcc.go#L639)):*
> ```Go
> 	key roachpb.Key,
> 	timestamp hlc.Timestamp,
> 	localTimestamp hlc.ClockTimestamp,
> ```

callers in this commit are calling with `hlc.ClockTimestamp{}` or `cArgs.Now`. What does it mean to call it with the former? If it is legal, we should define the meaning with code comments in this file.
___
*[pkg/kv/kvserver/client_replica_test.go, line 495 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-N-51K1wEtkpQOd4yuCn:-N-51K1wEtkpQOd4yuCo:b-43bzjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6145166409a3877b837abce1248bfaa14090d40/pkg/kv/kvserver/client_replica_test.go#L495)):*
> ```Go
> }
> 
> // TestTxnReadWithinUncertaintyIntervalAfterIntentResolution tests cases where a
> ```

(haven't read this test yet)


<!-- Sent from Reviewable.io -->

2022-04-08 08:40 UTC, erikgrinaker commented
Drive-by: doesn't look like `MVCCStats` computation has been updated to account for the extra timestamp.

I can do a proper review pass if you'd like it, since I'm all over MVCC at the moment anyway, but it may take me a few weeks since I have some PTO coming up and I'm already underwater here. But feel free to just go with Sumeer's approval, of course (or any other).

But as I said over on https://github.com/cockroachdb/pebble/pull/1314, I think we should run some quick benchmarks to make including this in the key is actually worth it -- placing this sort of non-identifying metadata into an identifier seems unfortunate otherwise.

2022-04-08 12:55 UTC, sumeerbhola reviewed
> But as I said over on cockroachdb/pebble#1314, I think we should run some quick benchmarks to make sure including this in the key is actually worth it -- placing this sort of non-identifying metadata into an identifier seems unfortunate otherwise.

+1 to benchmarking.
Regarding non-identifying metadata in an identifier -- I agree in principle. This tension often arises when mapping a high-level data model into a less capable kv store (non-columnar). The first thing is of course that keys and values become opaque bytes and one loses local indexing capability of the columns in the key and value. I've seen (and myself implemented in the past) some recovery of this opacity by peering into the keys and locally indexing the columns. We are not doing anything like that (yet) in Pebble, and instead just relying on ordering behavior for locality (since CockroachDB users are conditioned, as OLTP users often are, to creating global secondary indexes for narrowing the scans).
But we are soon going to do value placement tricks based on version awareness -- the prototype has good results and we may eventually do something as extreme as WiscKey. Which makes reading the key much cheaper than the value. One thing I did in a past system was to allow extraction of additional attributes from the value and stash them in a cheaply accessible place. We could add a feature to Pebble to extract (small) attributes from the value, and store key => ({attributes}, value), so that when we separate keys and values the key would have key => (location of value, {attributes}). We have a little bit of this extraction capability with block property collectors, but there would need to be significant changes to the Pebble interface and some changes to the sstable implementation to allow for attribute access that is separate from key or value access.
I am (a) wary of waiting on significant Pebble changes for local timestamps to be implemented, and (b) that other approach is maybe more principled, but it is not clear that there is any significant stability or performance benefit (subject to the aforementioned benchmarking), hence my preference to not block this and stick it in the key.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-:-N-88OAa1R20pRqwOs3i:b52kog7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @stevendanna, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-04-08 13:24 UTC, erikgrinaker reviewed
Thanks for the additional color Sumeer. I definitely agree that this is workable if the performance gains are large, and you may well be right that they will be. I haven't looked closely enough at this yet to have a good sense of it. The gains would likely be marginal if we only had to read the clock timestamp in the rare cases where it would actually be relevant, but I'm not sure if it's possible to make that determination a priori based on the known timestamps.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-:-N-8HRSuCUv68RgX91eD:bgseq6h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @stevendanna, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-04-14 21:37 UTC, nvanbenschoten reviewed
> doesn't look like MVCCStats computation has been updated to account for the extra timestamp.

The MVCCStats computation deliberately avoids taking the variable-length timestamp component into account and assumes all engine key versions are 12 bytes large, which can be an overestimate or an underestimate. This has [always been](https://github.com/cockroachdb/cockroach/commit/eccc31031749dbd523baef331c864016c8671199#diff-587435f02d449719464f882ce618f67a3ecc0679972addbb00d271989d7ac24dR99) the case.

However, with this change, the degree to which we can underestimate gets 12 bytes worse. Still, I'm inclined to not change this for two reasons. First, it will be difficult to make this precise. Doing so will require lifting and leaking the decision about when to omit the local timestamp from the encoding routines up into most MVCC logic. Second, I think it might be wise to keep the door open to LSM compaction filters stripping this local timestamp once it is no longer needed. As a strawman, we could do this for key-values once they fall below their range's GC threshold.

> But as I said over on cockroachdb/pebble#1314, I think we should run some quick benchmarks to make sure including this in the key is actually worth it -- placing this sort of non-identifying metadata into an identifier seems unfortunate otherwise.

Agreed. I plan to run some benchmarks and will post the results here.

>> Regarding non-identifying metadata in an identifier -- I agree in principle.

I agree in principle as well. That's one of the reasons I've resisted this change in the past. However, in addition to everything Sumeer said, there is another practical reason why storing the local timestamp in the MVCC key simplifies things. Today with the way that KV, MVCC, and Storage are layered, the MVCC and storage layers operate on decoded engine/mvcc keys but encoded (opaque) values. That makes manipulation of keys more natural than manipulation of values in the layer that owns this "local timestamp" concept.

As a concrete example, MVCC intent resolution can change the version timestamp of an intent when resolving it. With this change, that translation also needs to interact with the local timestamp. If we were to store the local timestamp in the value then we would need to teach the MVCC layers to unpack and modify `roachpb.Value`s. We would also need to teach the MVCC scanner to decode values so that it could compute uncertainty. None of this is insurmountable, but it adds complexity.

I also think the lines between what is and what is not an identifier are blurred by a storage engine that allows for custom key equality and comparison functions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-:-N-_DVI50oz3DXw7NsmG:bgpaa9s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna and @sumeerbhola)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mx_zsNM0g0LOFnWdTfh:-N-d41UmE4al97D0yeqW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a12b2f1c97f34ab4922f06d0dd6f870efe3e3ca8/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L648)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Would be nice to have a comment here on what kinds of transactions won't need to wait.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_send.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mxa-4xqEBUKN0oqEZ_M:-N-d4hVYA6-r-KSVGasQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a12b2f1c97f34ab4922f06d0dd6f870efe3e3ca8/pkg/kv/kvserver/replica_send.go#L268)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same comment here
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_send.go, line 251 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-N-4o_bHB6rcVlCybtXI:-N-d4LyU9XBm52MdpcH0:bq3ga1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b01b0a560127fc45b732c6660a243a4d41a7bf/pkg/kv/kvserver/replica_send.go#L251)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

just for my curiosity what is an example of a future time txn with a commit trigger. My understanding of the kinds of commit triggers is based on the list in `RunCommitTrigger` which seems mostly to do with splits and merges.
</blockquote></details>

Splits and merges that interact with ranges in GLOBAL tables can both end up committing with a future time txn. This is demonstrated by `TestStoreRangeSplitAndMergeWithGlobalReads` and discussed further in https://github.com/cockroachdb/cockroach/commit/776076b2a59eea5ef97382fb9d56ad5e232edaf8.
___
*[pkg/kv/kvserver/replica_tscache.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mxa-ILw5FFuLxK5JJ8P:-N-d4rL_2EsTCAS8dZDg:b71acak) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd15d3aef470a7838a0d770e408fa0d9f02d0671/pkg/kv/kvserver/replica_tscache.go#L62)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

was this TODO stale and has been fixed?
</blockquote></details>

Yes, the TODO was stale and the property that the assertion was trying to check is no longer relevant. 
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mxa0LPy6AJYGHxXkfd9:-N-dD8Qp2xr2MV86Nzty:b-xhhs1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e245c923e4251887e6a724c957e1cf028eec3b9/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L573)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

In this example will this mean that we don't need to write the local timestamp since it is >= txn commit timestamp?
</blockquote></details>

Yes. I updated the comment to expand on this. There's a subtle interaction here that means that we do still need to continue pushing the mvcc timestamp of intent holders above the local uncertainty limit of pushees. I was hoping to be able to remove this, but because of the normalization rules in MVCC, we can't.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 589 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mxa0cIG279JfzGhmOnr:-N-dXtnW0dqghTLdzdol:bgowogn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e245c923e4251887e6a724c957e1cf028eec3b9/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L589)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I see what this is saying, but a small example here would make it super clear for a reader.
</blockquote></details>

I added two examples here.
___
*[pkg/roachpb/api.proto, line 1142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-Mxa1YG88CL31PzJ3GUo:-N-d_D5E57WVfeHjH68j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e245c923e4251887e6a724c957e1cf028eec3b9/pkg/roachpb/api.proto#L1142)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This could use a short example of the hazard in the absence of this ignore behavior.
</blockquote></details>

Done.
___
*[pkg/storage/mvcc.go, line 639 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-N-4tZI9ECno4UpAL5Ma:-N-dj_BeEI9nr8zp_yF9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f4aa66ccd0933d2659f24065441c99ae7e1bfb0/pkg/storage/mvcc.go#L639)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

callers in this commit are calling with `hlc.ClockTimestamp{}` or `cArgs.Now`. What does it mean to call it with the former? If it is legal, we should define the meaning with code comments in this file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-15 18:49 UTC, erikgrinaker reviewed
> doesn't look like MVCCStats computation has been updated to account for the extra timestamp.
> 
> The MVCCStats computation deliberately avoids taking the variable-length timestamp component into account and assumes all engine key versions are 12 bytes large, which can be an overestimate or an underestimate. This has always been the case.
> However, with this change, the degree to which we can underestimate gets 12 bytes worse. Still, I'm inclined to not change this for two reasons. First, it will be difficult to make this precise. Doing so will require lifting and leaking the decision about when to omit the local timestamp from the encoding routines up into most MVCC logic. Second, I think it might be wise to keep the door open to LSM compaction filters stripping this local timestamp once it is no longer needed. As a strawman, we could do this for key-values once they fall below their range's GC threshold.

I see. The reason I ask is that I've implemented MVCC stats for range keys in #78085 using the actual encoded size of timestamps, with the hope that we would eventually fix this for point keys too (we have TODOs for it). Since range tombstones would presumably also need local timestamps, these would contribute their actual encoded size to the statistics.

>Today with the way that KV, MVCC, and Storage are layered, the MVCC and storage layers operate on decoded engine/mvcc keys but encoded (opaque) values. That makes manipulation of keys more natural than manipulation of values in the layer that owns this "local timestamp" concept.

Sort of. `MVCCPut` takes a `roachpb.Value`, and `MVCCGet` and `MVCCScan` both return `roachpb.Value`, which would store the local timestamp -- but it's true that this encoding/decoding happens near the MVCC API boundaries, and in the case of scans returning encoded binary KV pairs it might get prohibitively expensive to decode these on the server-side during scanning. Similarly for intent rewrites. So it's quite likely that the performance gains here are worth it, despite the unpleasant aesthetics.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-:-N-iVZF17jemXeQ844Ir:b-fhjhh2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-04-18 13:20 UTC, HonoreDB reviewed
While I'm here to look at the cdc impact: have you considered storing this as an offset or xor from the hlc.Timestamp with a smaller or variable-length encoding?

> Reviewed 11 of 137 files at r21.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-:-N-wlQkwDgDN6joT25q7:b-w28imf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-04-18 15:37 UTC, sumeerbhola reviewed
> Reviewed 1 of 134 files at r15, 1 of 132 files at r20, 2 of 137 files at r21.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77342)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten, @stevendanna, and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 1285 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/77342#-N-xHal48gX1pkNyAE-u:-N-xHal48gX1pkNyAE-v:bw0mmp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb24b1a6e67a3e85a933af80de8d07ac2ff16b4f/pkg/storage/mvcc.go#L1285)):*
> ```Go
> // assigned an explicit local timestamp. The effect of this is that
> // readers treat the local timestamp as being equal to the version
> // timestamp.
> ```

When is it safe for the the putter to say "assume local timestamp == version timestamp"?
Is it always safe for non-blocking txns (including a txn rewriting its own intent) because this is a put and the use of a version timestamp implies that the local clock has been advanced? Or is it not true even in this case because "we never need to "push" transaction-domain timestamps into HLC clocks"?
I would like the comment to also define the safety requirement for using `hlc.ClockTimestamp{}`


<!-- Sent from Reviewable.io -->

2022-04-18 20:29 UTC, nvanbenschoten commented
> Since range tombstones would presumably also need local timestamps, ...

This is a good point. We'll want to make sure that whatever solution we come to here works well for range tombstones. My reading of #77762 and of https://github.com/cockroachdb/pebble/commit/5d99779ccb8da71056dcd753a263b9a59a3b89b2 is that the timestamp suffix that we typically append to the key for point KeyKinds is stored in the value of range keys (`InternalKeyKindRangeKeySet`, `InternalKeyKindRangeKeyUnset`, `InternalKeyKindRangeKeyDelete`). On the surface, that would seem to indicate that the choice of where to store the local timestamp for point keys does not impact range tombstones (suffix vs. value).

However, the semantics of `RangeKeyUnset` make this more nuanced. Currently, `RangeKeyUnset` says that "only range keys with suffixes that exactly match the unset suffix" will be removed. One way to read this is that anything that does not affect key equality cannot end up in the range key suffix and that range key equality is defined using byte equality of the suffix. Another way to read this is that range key equality should be using the `pebble.Comparer` functions for range keys to define ordering and equality of range keys like it does for point keys, but that it is not doing so yet.

I'd like to make sure that any choice we make here will be consistently applied to range keys and that I'm not landing a large hurdle in the path of range keys. @erikgrinaker do you mind if I set up a quick chat for when you're back to bottom out on a few of these questions?

> MVCCPut takes a roachpb.Value, and MVCCGet and MVCCScan both return roachpb.Value, which would store the local timestamp -- but it's true that this encoding/decoding happens near the MVCC API boundaries

In many cases, the encoding/decoding is actually far away from the MVCC API boundaries. It's often all the way up in the SQL layer on the client. In the common-path of a SQL INSERT, the `roachpb.Value` (which is little more than a wrapper around a [custom encoded byte slice](https://github.com/cockroachdb/cockroach/blob/ecb24ef19f49517ab9a0a5c3fdb8171af6f9b459/pkg/roachpb/data.proto#L79)) is encoded in SQL and treated as opaque below this level. That makes extending `roachpb.Value` with additional metadata unpleasant and also difficult to do without a meaningful performance impact (i.e. due to re-allocating and re-encoding the value in MVCC, then decoding and stripping the metadata during performance-sensitive scans).

An alternative that I've begun to explore is introducing a wrapper value in the MVCC layer that carries a `roachpb.Value` along with some optional metadata. Imagine a `storage.MVCCValue` struct which wraps a `roachpb.Value` in much the same way that a `storage.MVCCKey` wraps a `roachpb.Key`. There would be some challenges to a solution like this, including backwards compatibility and avoiding the encoding/decoding performance hit in the common case, but we may be able to rely on local_timestamps being rare and (ab)use the `roachpb.Value` tag to indicate that the value is wrapped or not, allowing for an extended encoding scheme only in the cases where it is.

> While I'm here to look at the cdc impact: have you considered storing this as an offset or xor from the hlc.Timestamp with a smaller or variable-length encoding?

This change should have little impact to CDC. Local timestamps will be stripped from the key below Raft before they end up in a rangefeed and will never make it up to a changefeed.

I considered storing the local timestamp as an offset from the hlc.Timestamp, but that doesn't get us anything without a variable-length encoding. A variable-length encoding itself is difficult because we rely on known key suffix sizes when decoding `MVCCKeys`. Given how rarely we'll need to include this field in practice (< 0.3% of writes in TPC-C), it didn't seem worth the complexity beyond making the encoding variable-length with respect to the presence or absence of a logical timestamp component.

2022-04-19 13:27 UTC, erikgrinaker commented
Sure @nvanbenschoten, let's have a chat when you're back.

2022-05-09 19:12 UTC, nvanbenschoten commented
Replaced by https://github.com/cockroachdb/cockroach/pull/80706.

2022-05-09 19:12 UTC, closed without merging