ui: add selected period as part of cached key
cockroachdb/cockroach pull request #77450
Opened 2022-03-07 19:56 UTC by maryliag

Notes to Reviewers: Only second commit to be reviewed on this PR. First being reviewed at https://github.com/cockroachdb/cockroach/pull/77215

Previously, the fingerprint id and the app names were used
as a key for a statement details cache. This commits adds
the start and end time (when existing) to the key, so
the details are correctly assigned to the selected period.

This commit also rounds the selected value period to the hour,
since that is what is used on the persisted statistics, with
the start value keeping the hour and the end value adding one
hour, for example:
start: 17:45:23  ->  17:00:00
end:   20:14:32  ->  21:00:00

Partially addresses https://github.com/cockroachdb/cockroach/issues/72129

Release note: None
Release Justification: Low risk, high benefit change

2022-03-07 19:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/77450)
<!-- Reviewable:end -->

2022-03-08 18:16 UTC, Azhng reviewed
Hmm seems like a couple unit tests are failing 

> Reviewed 5 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-:-MxejiLDD7cmft_hDT40:b-k374mx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[-- commits, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxeh1jgAoDzAQGqDrIQ):*
nit: dup release justification 
___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts, line 302 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxehbql1OLb0PpUKrz6:-Mxehbql1OLb0PpUKrz7:b-8pcou0) ([raw file](https://github.com/cockroachdb/cockroach/blob/609d3998a2dfc1471399f6d6e885661060cbe486/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts#L302)):*
> ```XML
>       if (apps[i].includes("$ internal")) {
>         apps[i] = "$ internal";
>       }
> ```

I just realized that, wouldn't we have multiple `$ internal` app names in the `app_names` field in this case :thinking:, Perhaps we can use a `Set` here? 
___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxej12uAujMXMd2goNK:-Mxej12vDsKv9zkF5p3b:bd03u2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/609d3998a2dfc1471399f6d6e885661060cbe486/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L15)):*
> ```XML
> import moment from "moment";
> import { util } from "@cockroachlabs/cluster-ui";
> const { generateStmtDetailsToID } = util;
> ```

Hmm, can we directly import `generateStmtDetailsToID` here? Since `appStats` package does have a top-level `index.ts` for package wide export


<!-- Sent from Reviewable.io -->

2022-03-09 18:58 UTC, matthewtodd approved these changes
Other than test failures, <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 9 files at r2, 30 of 30 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-:-Mxk1vvj0EMoypIsRm6G:b-u0w6r1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2022-03-09 19:21 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77450)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @matthewtodd)

___
*[-- commits, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxeh1jgAoDzAQGqDrIQ):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: dup release justification 
</blockquote></details>

Fixed
___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts, line 302 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxehbql1OLb0PpUKrz6:-Mxk78JkAyiZ0sNAFYT4:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/609d3998a2dfc1471399f6d6e885661060cbe486/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts#L302)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I just realized that, wouldn't we have multiple `$ internal` app names in the `app_names` field in this case :thinking:, Perhaps we can use a `Set` here? 
</blockquote></details>

Fixed
___
*[pkg/ui/workspaces/db-console/src/redux/apiReducers.ts, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxej12uAujMXMd2goNK:-Mxk3KMZ0_1q4zQAeQNe:brv385d) ([raw file](https://github.com/cockroachdb/cockroach/blob/609d3998a2dfc1471399f6d6e885661060cbe486/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L15)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, can we directly import `generateStmtDetailsToID` here? Since `appStats` package does have a top-level `index.ts` for package wide export
</blockquote></details>

The util is imported as its own name, and that one has its own imported files, so for the utils and api we need to import this way



_Code quote:_
```XML
const { generateStmtDetailsToID } = util;
```


<!-- Sent from Reviewable.io -->

2022-03-09 23:34 UTC, Azhng reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77450)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxl0yfv2_WNoH6wVr4U:-Mxl0yfv2_WNoH6wVr4V:b-dv3u7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a432d7fcde0ed6357c2e489dea124db3aa3dda01/pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts#L20)):*
> ```XML
>   OIDCAutoLogin: boolean;
>   OIDCLoginEnabled: boolean;
>   OIDCButtonText: string;
> ```

Hmm, what are these new fields for :thinking:, are they related to the CI test failures somehow ? 


<!-- Sent from Reviewable.io -->

2022-03-09 23:37 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77450)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxl0yfv2_WNoH6wVr4U:-Mxl1QdI2ft1LJKvaLyw:bmghje4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a432d7fcde0ed6357c2e489dea124db3aa3dda01/pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts#L20)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, what are these new fields for :thinking:, are they related to the CI test failures somehow ? 
</blockquote></details>

related to test failures


<!-- Sent from Reviewable.io -->

2022-03-09 23:57 UTC, Azhng approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-:-Mxl6O48BYDqmIQW34Lf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxl0yfv2_WNoH6wVr4U:-Mxl6FP05p5XBj6vehEa:b197xs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a432d7fcde0ed6357c2e489dea124db3aa3dda01/pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts#L20)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

related to test failures
</blockquote></details>

Out of curiosity, how did this fix the CI failure ? 


<!-- Sent from Reviewable.io -->

2022-03-10 00:24 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77450)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxl0yfv2_WNoH6wVr4U:-MxlBw-y9vflF9AwHswf:b-j3zz4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a432d7fcde0ed6357c2e489dea124db3aa3dda01/pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts#L20)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Out of curiosity, how did this fix the CI failure ? 
</blockquote></details>

This interface exists on both db console and cluster-ui, and the cluster-ui was missing those fields. Our guess is that it was always importing the one from db console first (for tests, etc), but I added a new dependency on package.json and that must have changed some order of import and was getting the one from here first, which was missing those fields and creating the failure. 
It's weird that never happened before but it was bound to happen any day and my Pr was the "lucky" one


<!-- Sent from Reviewable.io -->

2022-03-10 00:31 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77450)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-Mxl0yfv2_WNoH6wVr4U:-MxlEBRN2oCATuUu7PIk:b-u2e8oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a432d7fcde0ed6357c2e489dea124db3aa3dda01/pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts#L20)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

This interface exists on both db console and cluster-ui, and the cluster-ui was missing those fields. Our guess is that it was always importing the one from db console first (for tests, etc), but I added a new dependency on package.json and that must have changed some order of import and was getting the one from here first, which was missing those fields and creating the failure. 
It's weird that never happened before but it was bound to happen any day and my Pr was the "lucky" one
</blockquote></details>

 that's pretty interesting :D 


<!-- Sent from Reviewable.io -->

2022-03-10 16:47 UTC, jocrl requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77450)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @jocrl, @maryliag, and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.sagas.ts, line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-MxoVsMM7Er_QJTfJshH:-MxoVsMM7Er_QJTfJshI:b-qletl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a432d7fcde0ed6357c2e489dea124db3aa3dda01/pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.sagas.ts#L32)):*
> ```XML
>   action: PayloadAction<StatementDetailsRequest>,
> ): any {
>   const key = action?.payload
> ```

So I'm suspecting that in your https://github.com/cockroachdb/cockroach/pull/77215 PR which added this function, that this `action?.payload ... : ""` was added in order to mimic the `getStatements` vs `getCombinedStatements` forking in `sqlStats.sagas.ts`'s `requestSQLStatsSaga`.

Now that we know what that forking was about, should there actually be a forking here? Is there actually a use case where the key should be `""`? I'm thinking not since `action` in the function signature is required, and because I'm not sure what a `""` key would mean.



_Code quote:_
```XML
  const key = action?.payload
    ? generateStmtDetailsToID(
        action.payload.fingerprint_id,
        action.payload.app_names.toString(),
        action.payload.start,
        action.payload.end,
      )
    : "";
```
___
*[pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts, line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77450#-MxoiNxI62gRqAA9AWeV:-MxoiNxI62gRqAA9AWeW:b-gdybe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a432d7fcde0ed6357c2e489dea124db3aa3dda01/pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts#L90)):*
> ```XML
> };
> 
> export const toRoundedDateRange = (
> ```

Could you add a comment explaining the cluster setting in the back end that this is tied to?

Separately, I know we don't currently expose the setting to users. But does this front end assumption of the aggregation interval (I think it's aggregation interval?) limit our ability to develop and test front end functionality? E.g., if we want to generate data to test that aggregation intervals are correctly combined, one way would be to lower the aggregation interval so that you don't actually have to wait an hour. Or if you want to generate data to test that the time picker works correctly to retrieve different data.

If this rounding does affect dev-ability, one could in theory modify this function to change the number when developing. But that becomes one more thing to have to know to change, and runs the risk of accidentally being checked in + administrative back and forth if PRs accidentally check it in.


<!-- Sent from Reviewable.io -->

2022-03-10 17:30 UTC, maryliag commented
bors r+

2022-03-10 19:34 UTC, merged