opt: fix dangerous MapFilterCols function
cockroachdb/cockroach pull request #77463
Opened 2022-03-08 00:40 UTC by mgartner

The `MapFilterCols` custom function was dangerous because it relied on
the ordering of columns in two unordered sets to map columns referenced
in a filter. As one example, the implementation of the function made it
impossible to map column `1` to column `5` and column `2` to column `4`
in the same filter.

As far as I know this has not caused bugs. It was only used to remap
columns from a scan to columns in a duplicate scan. Column IDs of scans
are allocated in ascending order, and column sets are iterated over in
ascending order, so columns were always correctly mapped.

This commit replaces `MapFilterCols` with `RemapScanColsInFilter` which
does not rely on the ordering of columns in unordered sets. This will
prevent future bugs that would occur if either column ID allocation or
column set iteration change. The more specific name and arguments of
`RemapScanColsInFilter` should also prevent misuse.

Release justification: This is a minor change that does not affect
behavior and decreases the risk of future bugs in the optimizer.

Release note: None

2022-03-08 00:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/77463)
<!-- Reviewable:end -->

2022-03-08 02:50 UTC, msirek requested changes
Very nice update to make column remapping safe!

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-:-Mxb6n8z7W6iUJxIyknb:blbfcff)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[pkg/sql/opt/xform/general_funcs.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbQ5XJ9nPpT8Vpkspe:-MxbQ5XJ9nPpT8Vpkspf:b-avozzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/general_funcs.go#L72)):*
> ```Go
> 
> // RemapScanColsInFilter returns a new FiltersExpr where columns in src's table
> // are replaced with columns of the same ordinal in dst's table. src and dst
> ```

nit: parameters are named `from` and `to` but comment refers to old parameter names.
___
*[pkg/sql/opt/xform/general_funcs.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbIrch52dQ7v_uMQMZ:-MxbIrch52dQ7v_uMQM_:bavygyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/general_funcs.go#L82)):*
> ```Go
> 
> func (c *CustomFuncs) remapScanColsInScalarExpr(
> 	scalar opt.ScalarExpr, src, dst *memo.ScanPrivate,
> ```

nit: RemapScanColsInFilter had parameter names changed to `from` and `to`, but these are still `src` and `dst`.
___
*[pkg/sql/opt/xform/rules/select.opt, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbNPAT1yzYBvGrLt-5:-MxbNPAT1yzYBvGrLt-6:b4gqpi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/rules/select.opt#L229)):*
> ```
>             $leftScan:(Scan
>                 $leftScanPrivate:(AddPrimaryKeyColsToScanPrivate
>                     (DuplicateScanPrivate $scanPrivate)
> ```

`leftScanPrivate` should an exact duplicate of `scanPrivate` since remapping relies on both ScanPrivates having the same columns:
```
               (AddPrimaryKeyColsToScanPrivate
                    $leftScanPrivate:(DuplicateScanPrivate $scanPrivate)
```



_Code quote:_
```
                $leftScanPrivate:(AddPrimaryKeyColsToScanPrivate
                    (DuplicateScanPrivate $scanPrivate)
```
___
*[pkg/sql/opt/xform/rules/select.opt, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbO7ZJ3lQiQCNKd6OB:-MxbO7ZM4rK4H66unCs_:b9v3ltx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/rules/select.opt#L245)):*
> ```
>             $rightScan:(Scan
>                 $rightScanPrivate:(AddPrimaryKeyColsToScanPrivate
>                     (DuplicateScanPrivate $scanPrivate)
> ```

Same comment here as above.


<!-- Sent from Reviewable.io -->

2022-03-08 03:42 UTC, msirek requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77463)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[pkg/sql/opt/xform/general_funcs.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbbGaXANGhOkQpkOaM:-MxbbGaXANGhOkQpkOaN:b-wh48cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/general_funcs.go#L86)):*
> ```Go
> 	md := c.e.mem.Metadata()
> 	if md.Table(src.Table).ID() != md.Table(dst.Table).ID() {
> 		panic(errors.AssertionFailedf("src and dst must scan the same base table"))
> ```

It would be good to also maintain the old sanity check for number of columns:
```
if src.Cols.Len() != dst.Cols.Len() {
  panic(...)
}
```


<!-- Sent from Reviewable.io -->

2022-03-08 05:35 UTC, msirek approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77463)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[pkg/sql/opt/xform/rules/select.opt, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbNPAT1yzYBvGrLt-5:-Mxc-OlO2C1YEIeTAgPT:b-4xskgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/rules/select.opt#L229)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

`leftScanPrivate` should an exact duplicate of `scanPrivate` since remapping relies on both ScanPrivates having the same columns:
```
               (AddPrimaryKeyColsToScanPrivate
                    $leftScanPrivate:(DuplicateScanPrivate $scanPrivate)
```

</blockquote></details>

I take this back.  The mapping is now done based on column ordinals, so it should work fine.  


<!-- Sent from Reviewable.io -->

2022-03-08 15:49 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77463)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rharding6373)

___
*[pkg/sql/opt/xform/general_funcs.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbQ5XJ9nPpT8Vpkspe:-Mxe7wnL9I_Rngg30Xu-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/general_funcs.go#L72)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

nit: parameters are named `from` and `to` but comment refers to old parameter names.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/general_funcs.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbIrch52dQ7v_uMQMZ:-Mxe8-IW-5JZonRdNdxm:b-xvriwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/general_funcs.go#L82)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

nit: RemapScanColsInFilter had parameter names changed to `from` and `to`, but these are still `src` and `dst`.
</blockquote></details>

I changed RemapScanColsInFilter to have `src` and `dst`.
___
*[pkg/sql/opt/xform/general_funcs.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbbGaXANGhOkQpkOaM:-Mxe8PSH4-_W8MzSbFJM:bqfboda) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/general_funcs.go#L86)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

It would be good to also maintain the old sanity check for number of columns:
```
if src.Cols.Len() != dst.Cols.Len() {
  panic(...)
}
```
</blockquote></details>

Done. I had to adjust the `SplitDisjunctionAddKey` rule a bit so that the new left and right scan privates passed to this function do no contain the PK columns that are added, otherwise the number of columns would not be the same. This should be fine because the filters cannot contain references to these PK cols (otherwise they would be included in the original scan private's columns).
___
*[pkg/sql/opt/xform/rules/select.opt, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbNPAT1yzYBvGrLt-5:-MxeApXEBEwMdWnajsx-:b2t0qwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/rules/select.opt#L229)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I take this back.  The mapping is now done based on column ordinals, so it should work fine.  
</blockquote></details>

What you said originally makes sense, and it's required in order for the column count check in RemapScanColsInFilter to pass. So I've made the change.
___
*[pkg/sql/opt/xform/rules/select.opt, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbO7ZJ3lQiQCNKd6OB:-MxeB8FA9AiV9nO-FOH2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/rules/select.opt#L245)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Same comment here as above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-08 16:07 UTC, msirek approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77463)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rharding6373)

___
*[pkg/sql/opt/xform/rules/select.opt, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxbNPAT1yzYBvGrLt-5:-MxeGNvm9u86_i6lfhVh:b5vmzzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e89a7a81c09065e10a489023faf0a81f4bc9d5c/pkg/sql/opt/xform/rules/select.opt#L229)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What you said originally makes sense, and it's required in order for the column count check in RemapScanColsInFilter to pass. So I've made the change.
</blockquote></details>

Yeah, last night I was thinking the ordinals of all defined columns would exist in TabMeta, so retracted my comment. But now taking a closer look, it only calls Metadata.AddColumn for the columns included in the ScanPrivate, so the ordinals get compacted.  So I have to retract my retraction.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 


<!-- Sent from Reviewable.io -->

2022-03-08 17:25 UTC, rharding6373 approved these changes
Thanks for fixing this! Nice work. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-:-MxeYzvd5XYuGi-Crm-0:b-sj4dij)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/general_funcs.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxeW99S4NNsdXdFBrTU:-MxeW99S4NNsdXdFBrTV:bk9z9ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/a98763a30762bb605469391db40683795e27a7bc/pkg/sql/opt/xform/general_funcs.go#L89)):*
> ```Go
> 	}
> 	if src.Cols.Len() != dst.Cols.Len() {
> 		panic(errors.AssertionFailedf("src and dst must have the same number of columns"))
> ```

nit: will there be sufficient info in the panic message if info on src and dst are removed?


<!-- Sent from Reviewable.io -->

2022-03-08 21:08 UTC, mgartner reviewed
Thanks for all the great feedback!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-:-MxfM9Jh-oVA50QwOMBd:b5edqia)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rharding6373)

___
*[pkg/sql/opt/xform/general_funcs.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77463#-MxeW99S4NNsdXdFBrTU:-MxfLqKlCBY76cO1zJzX:b-os2pb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a98763a30762bb605469391db40683795e27a7bc/pkg/sql/opt/xform/general_funcs.go#L89)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: will there be sufficient info in the panic message if info on src and dst are removed?
</blockquote></details>

Good point, the variable names aren't necessary. Removed.


<!-- Sent from Reviewable.io -->

2022-03-09 20:04 UTC, mgartner commented
bors r+

2022-03-09 21:15 UTC, merged