sql: Add multitenant fairness tests
cockroachdb/cockroach pull request #77481
Opened 2022-03-08 13:44 UTC by cucaroach

Two tests intended to validate that kv and store admission control
queues distribute database resources fairly.

Release note: None

2022-03-08 13:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/77481)
<!-- Reviewable:end -->

2022-03-09 01:12 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @tbg)

___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MxgBdYh9w_vAgETSGOL:-MxgBdYi9e1lCgF2GBJs:b-8je9uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L63)):*
> ```Go
> }
> 
> // Test that the kvserver fairly distributes CPU token on a highly concurrent 4 MT workload.
> ```

4 MT?
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MxgCVaD5hC6SAWOXWSv:-MxgCVaD5hC6SAWOXWSw:b-hea7ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L146)):*
> ```Go
> 	fmt.Printf("Max latency delta: %d%% %v\n", int(maxDeltaPercentage*100), meanLatencies)
> 
> 	// TODO: Can we do anything to verify that admission control kicked in?  Check some stats?
> ```

What does the admin console look like when this is run, just as a rough sanity check?
Is there enough concurrency from each tenant to saturate some resource? I thought we would need --concurrency to be high (e.g. see roachtest/tests/kv.go).
Also, if each tenant has the same concurrency, I suspect they will get similar allocation even without admission control. We could manually turn off admission control and see if there is any change in the observed throughput for each tenant. An alternative would be to have tenants with different concurrency values, say tenant1 with C concurrency, tenant2 with 2*C, tenant3 with 4*C, tenant4 with 8*C, such that C is enough to use significantly more than 25% of the resource, and then see if everyone gets equal throughput.


<!-- Sent from Reviewable.io -->

2022-03-10 17:14 UTC, cucaroach reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MxgBdYh9w_vAgETSGOL:-MxomrE9BGMw_aYMo1DC:b-vvkvtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L63)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

4 MT?
</blockquote></details>

Sorry, what terminology should I use, 4 sql pod?
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MxgCVaD5hC6SAWOXWSv:-MxoXlmR9K0D6u0GzOId:b-bq05ky) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L146)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What does the admin console look like when this is run, just as a rough sanity check?
Is there enough concurrency from each tenant to saturate some resource? I thought we would need --concurrency to be high (e.g. see roachtest/tests/kv.go).
Also, if each tenant has the same concurrency, I suspect they will get similar allocation even without admission control. We could manually turn off admission control and see if there is any change in the observed throughput for each tenant. An alternative would be to have tenants with different concurrency values, say tenant1 with C concurrency, tenant2 with 2*C, tenant3 with 4*C, tenant4 with 8*C, such that C is enough to use significantly more than 25% of the resource, and then see if everyone gets equal throughput.
</blockquote></details>

What part of the console?   The kv server looks very un busy since the console bias is towards SQL activity.   It only shows %25 CPU usage but I know from top et al that the CPU is tapped out.   Each workload instance has default concurrency 8 so there's 32 concurrency.   I can see from custom metrics that there are 40 kv slot so I'll try to crank up concurrency to see if I can get any queuing to happen.   Then I'll play with varying concurrency per tenant.  Thanks for the suggestions!


<!-- Sent from Reviewable.io -->

2022-03-10 17:23 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @sumeerbhola, and @tbg)

___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MxgCVaD5hC6SAWOXWSv:-MxoqNkhC-oHfbTl74Jh:bynupbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L146)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

What part of the console?   The kv server looks very un busy since the console bias is towards SQL activity.   It only shows %25 CPU usage but I know from top et al that the CPU is tapped out.   Each workload instance has default concurrency 8 so there's 32 concurrency.   I can see from custom metrics that there are 40 kv slot so I'll try to crank up concurrency to see if I can get any queuing to happen.   Then I'll play with varying concurrency per tenant.  Thanks for the suggestions!
</blockquote></details>

the overload page should show queuing in admission control if we are overloading cpu (higher runnable goroutine count) or causing higher read amp in the store.


<!-- Sent from Reviewable.io -->

2022-03-10 17:49 UTC, cucaroach commented
Here's what 200 concurrency per sql pod looks like:

<img width="771" alt="Screen Shot 2022-03-10 at 12 48 39 PM" src="https://user-images.githubusercontent.com/80277990/157724381-ea48c340-b88a-48cb-b6ec-ba5495176d39.png">

2022-03-11 14:57 UTC, sumeerbhola reviewed
The mean delay is < 150us, and the 75th percentile is ~10ms. The slots don't look anywhere close to full. There must be some tiny spikes that are not caught by the low sampling frequency of the metric, which is why admission delay is not 0. What does the runnable goroutine count on the overload dashboard look like? I think we need significantly more load.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-:-MxtTO7yBa5hV70OfJz3:bfhvy69)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @sumeerbhola, and @tbg)



<!-- Sent from Reviewable.io -->

2022-03-11 15:11 UTC, cucaroach commented
I think the machine is so overloaded that we're adjusting the number of available slots down?   Isn't the dark line in the slots graph the number of slots we think we can handle?   The CPU is pegged at %100.  Maybe going from 32 to 400 was too big a jump in concurrency, I'll experiment some more...

2022-03-11 15:33 UTC, cucaroach commented
Here's what the machine's CPU looks like:

<img width="1142" alt="Screen Shot 2022-03-11 at 10 14 34 AM" src="https://user-images.githubusercontent.com/80277990/157894973-4d6b1bfa-ea71-476c-8cda-37c1daaf6e0c.png">

2022-03-11 21:00 UTC, sumeerbhola requested changes
> I think the machine is so overloaded that we're adjusting the number of available slots down? Isn't the dark line in the slots graph the number of slots we think we can handle?

I have no idea what the dark line is. What do the labels say when you hover over it? I doubt we would see such low admission control latency if the slots were truly scarce.

> The CPU is pegged at %100 (this is a 4 CPU machine running 4 workload processes, 4 SQL pods and 1 kvserver). Maybe going from 32 to 400 was too big a jump in concurrency, I'll experiment some more...

We shouldn't run the kv server (or storage server in the terminology doc) on a shared machine with the others. It's going to add noise due to cpu fluctuations caused by the cpu usage in the SQL pods and the workload processes. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-:-MxukcSp5I0NZdhyvVcd:blhpw4f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @tbg)

___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MxgBdYh9w_vAgETSGOL:-Mxulu1gD_ScvVUUskSv:b4msuzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L63)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Sorry, what terminology should I use, 4 sql pod?
</blockquote></details>

yes, that's fine https://docs.google.com/presentation/d/1IvqkP3EOiKLPPf7lPsMpJsoUk6hcaaDm4xg5VqJ97TI/edit#slide=id.g1125de19347_0_185


<!-- Sent from Reviewable.io -->

2022-03-17 14:49 UTC, tbg reviewed
Gave an initial review with some high-level suggestions. Sorry this took so long, I was out on PTO until earlier this week and had been catching up.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-:-MyNGL-58zhRka4yZX82:b-gkgsu7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MyNDMP1EP-2I-CpObp4:-MyNDMP1EP-2I-CpObp5:b-jugj5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L38)):*
> ```Go
> 		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
> 			runMultiTenantFairness(ctx, t, c, *t.BuildVersion(),
> 				10,  // init duration
> ```

I'd introduce a `multiTenantFairnessOptions` struct to hold these values. It also seems like you can just have a `BlockSize` parameter, since all uses currently specify min=max.
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MyNDcSr4BQgfgFFTMMz:-MyNDcSr4BQgfgFFTMN-:b1l0390) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L69)):*
> ```Go
> 	c cluster.Cluster,
> 	v version.Version,
> 	initDuration int,
> ```

Use `time.Duration` here or the caller can invoke this with `time.Second` expecting to get a second but it's really going to be 1E9 seconds. The workload flags are also `time.Duration` so you shouldn't need to perform any conversions.
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MyNEkT04l5HbLaW8uQI:-MyNEkT04l5HbLaW8uQJ:brf8vg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L100)):*
> ```Go
> 
> 	// Init kv on each tenant.
> 	var wg sync.WaitGroup
> ```

Throughout: Use a `c.NewMonitor`, not a WaitGroup. A WaitGroup is oblivious to the cluster becoming unavailable and will cause test hangs that the test harness has a hard time recovering from. Monitor does the right thing.
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MyNEanG0JjiNqQ0rbwB:-MyNEanG0JjiNqQ0rbwC:b-un0930) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L105)):*
> ```Go
> 		go func(pgurl string) {
> 			defer wg.Done()
> 			cmd := fmt.Sprintf("./cockroach workload run kv  --min-block-bytes %d --max-block-bytes %d --splits 10 --init --batch 100 --duration=%ds %s", minBlockSize, maxBlockSize, initDuration, pgurl)
> ```

nit: I think it's deprecated to use `run --init`. If you're just initializing, `./cockroach workload init kv` is the right thing to use.
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MyNF8hL6JTRoRNDieU6:-MyNF8hL6JTRoRNDieU7:bo3mwui) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L122)):*
> ```Go
> 	wg.Wait()
> 
> 	// Pull workload performance from crdb_internal.statement_statistics.
> ```

I think this is one of the tests that would really benefit from using prometheus instead of ad-hoc metrics stuff. For a recent example, see https://github.com/cockroachdb/cockroach/pull/76147/files#diff-28a39375143eb2ad1e76868f4086035dc8099dc89f98658c3f62f52987945b1eR139-R152. There are also the multi-region DRT tests, `drt.go`, which do something similar (but that's where I learned from, so my code is probably more easily digested for your use case).

The main reasons I am suggestion prometheus here is that a) you can test whatever metrics you like without any limits and b) if the test fails, you can easily go through the metrics and figure out exactly what was wrong since there'll be a prometheus snapshot in the artifacts.


<!-- Sent from Reviewable.io -->

2022-03-25 16:59 UTC, cucaroach commented
Here's the results from the latest full run, some mixed signals but overall admission control on looks like a win:

```
admission-control-on/store-fairness/size-skew/run_1/test.log
27:19:22:25 multitenant_fairness.go:236: Max throughput delta: 4% [8046 8117 8071 8570]
28:19:22:25 multitenant_fairness.go:247: Max latency delta: 31% [1.292192061218867 1.1910183562547731 1.1579871814502536 0.7477568048697794]

admission-control-off/store-fairness/size-skew/run_1/test.log
27:19:04:10 multitenant_fairness.go:236: Max throughput delta: 44% [3542 5170 8372 8518]
28:19:04:10 multitenant_fairness.go:247: Max latency delta: 33% [1.9760166527478815 1.9266345608191482 1.7435293913158136 1.1201716625158469]

admission-control-on/store-fairness/same/run_1/test.log
27:19:21:57 multitenant_fairness.go:236: Max throughput delta: 5% [8042 7832 8105 8608]
28:19:21:57 multitenant_fairness.go:247: Max latency delta: 35% [1.9362360887518 1.1774040776615182 1.7664052900354095 0.8348145489724682]

admission-control-off/store-fairness/same/run_1/test.log
27:19:04:17 multitenant_fairness.go:236: Max throughput delta: 42% [3724 6174 7504 8471]
28:19:04:17 multitenant_fairness.go:247: Max latency delta: 51% [1.953238985834854 1.5062504626903128 0.9549237519677499 0.7405189034660602]

admission-control-on/store-fairness/concurrency-skew/run_1/test.log
27:19:04:54 multitenant_fairness.go:236: Max throughput delta: 37% [4335 7058 7875 8621]
28:19:04:54 multitenant_fairness.go:247: Max latency delta: 62% [2.043226593744872 1.0792064205476055 1.1588510597380306 0.7411893042964846]

admission-control-off/store-fairness/concurrency-skew/run_1/test.log
27:19:04:07 multitenant_fairness.go:236: Max throughput delta: 44% [3497 4694 8398 8611]
28:19:04:07 multitenant_fairness.go:247: Max latency delta: 18% [0.9557216485936532 1.0696940393372412 1.1102637238685396 0.8027469069018707]

admission-control-on/kv-fairness/concurrency-skew/run_1/test.log
27:19:03:28 multitenant_fairness.go:236: Max throughput delta: 11% [2.261697e+06 2.502861e+06 2.847614e+06 2.607714e+06]
28:19:03:28 multitenant_fairness.go:247: Max latency delta: 7% [0.003673017991528602 0.004078486600023887 0.0035989890397046588 0.0037721962858242616]

admission-control-off/kv-fairness/concurrency-skew/run_1/test.log
27:19:03:23 multitenant_fairness.go:236: Max throughput delta: 21% [2.238545e+06 2.080805e+06 1.912632e+06 2.708984e+06]
28:19:03:23 multitenant_fairness.go:247: Max latency delta: 6% [0.003659826819451616 0.003537415493861285 0.003886044276673637 0.0035207262351404723]

admission-control-on/kv-fairness/same/run_1/test.log
27:19:03:29 multitenant_fairness.go:236: Max throughput delta: 2% [2.514439e+06 2.543065e+06 2.596264e+06 2.493127e+06]
28:19:03:29 multitenant_fairness.go:247: Max latency delta: 12% [0.004385765617854339 0.0036885013617139165 0.0034431416468633656 0.0040650634405109826]

admission-control-off/kv-fairness/same/run_1/test.log
27:19:03:28 multitenant_fairness.go:236: Max throughput delta: 24% [2.462123e+06 2.045751e+06 2.975329e+06 2.082289e+06]
28:19:03:28 multitenant_fairness.go:247: Max latency delta: 5% [0.00375622026082275 0.004142495671776924 0.0037409535538152072 0.004016245383471014]

admission-control-on/kv-fairness/size-skew/run_1/test.log
27:19:03:22 multitenant_fairness.go:236: Max throughput delta: 14% [2.249276e+06 2.351748e+06 2.490747e+06 1.923401e+06]
28:19:03:22 multitenant_fairness.go:247: Max latency delta: 10% [0.0034406955788691936 0.0038719533858636 0.003989169634826118 0.004103228254822516]

admission-control-off/kv-fairness/size-skew/run_1/test.log
27:19:03:24 multitenant_fairness.go:236: Max throughput delta: 11% [1.959306e+06 2.269946e+06 2.411642e+06 2.196523e+06]
28:19:03:24 multitenant_fairness.go:247: Max latency delta: 11% [0.004394470820938169 0.0034889320494695454 0.0038784322837821248 0.003976539002935638]
```

Going to look at some metrics for all these to make sure we're really hitting overload conditions.

2022-03-25 17:00 UTC, cucaroach commented
I'm at a loss on how to turn these tests into reliable pass/fail style tests and am leaning towards just having numbers published so we track over time how we're doing, any thoughts on this would be much appreciated.   I really don't want to add a flakey test that needs constant attention...

2022-03-28 09:03 UTC, tbg commented
> I'm at a loss on how to turn these tests into reliable pass/fail style tests and am leaning towards just having numbers published so we track over time how we're doing, any thoughts on this would be much appreciated. I really don't want to add a flakey test that needs constant attention...

That would be my suggestion as well. I would think of these as performance tests so that data accumulates over time and improvements/regressions can be identified. @stevendanna could you help Tommy figure out how to do that in case he needs help (which I assume he will). I also wonder if we wrote down the basics somewhere (I'd like to read that myself, because I'm shaky on what exactly we support and where changes need to be made), for example in our knowledge base: https://cockroachlabs.atlassian.net/wiki/spaces/TE/pages/2208629091/Knowledge+Base

2022-03-29 14:02 UTC, sumeerbhola requested changes
Numbers are quite nice!

I am wondering about the following size-skew.
> admission-control-on/kv-fairness/size-skew/run_1/test.log
> 27:19:03:22 multitenant_fairness.go:236: Max throughput delta: 14% [2.249276e+06 2.351748e+06 2.490747e+06 1.923401e+06]
> 28:19:03:22 multitenant_fairness.go:247: Max latency delta: 10% [0.0034406955788691936 0.0038719533858636 0.003989169634826118 0.004103228254822516]

is the one with the lowest throughput the one with the largest size? Could it be encountering more hits when reading keys (vs the key not being found)? Also, I am confused how the default hashGenerator for the kv workload behaves when the read percent is 100. Isn't it going to keep reading key 0 since it hasn't seen any writes?

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-:-MzKwF2k2Jzdlcno_08N:b-oxkzkq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @sumeerbhola, and @tbg)

___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MzKswGUA4yCyWgVASzV:-MzKswGUA4yCyWgVASzW:bybez52) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6c5548070ea0de4a594eed976cb69c4909d8f3/pkg/cmd/roachtest/tests/multitenant_fairness.go#L54)):*
> ```Go
> 				name:           "concurrency-skew",
> 				warmUpDuration: func(i int) time.Duration { return 5 * time.Minute },
> 				concurrency:    func(i int) int { return i * 8 },
> ```

looks like this will be called with i in [1,5]. Is that correct? So lowest concurrency is 8 and highest is 40.

And we are using a 4 cpu KV node?

Do you know if 4 tenants with a concurrency of 8 each are sufficient to saturate cpu for this no writes (kv-fairness) case, and sufficient to saturate the store in the only writes (store-fairness) case below?

Perhaps the delta number below is because a concurrency of 8 is too low to utilize 25% of the store capacity.
```
admission-control-on/store-fairness/concurrency-skew/run_1/test.log
27:19:04:54 multitenant_fairness.go:236: Max throughput delta: 37% [4335 7058 7875 8621]
```
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MzKuJzMEtDr_lKFdak1:-MzKuJzMEtDr_lKFdak2:bmv23h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6c5548070ea0de4a594eed976cb69c4909d8f3/pkg/cmd/roachtest/tests/multitenant_fairness.go#L90)):*
> ```Go
> 			{
> 				name:           "size-skew",
> 				warmUpDuration: func(i int) time.Duration { return time.Duration(i*2) * time.Minute },
> ```

Do you expect initial size skew to matter in this case that does only writes? I am assuming the writes after setup are not limited to overwriting the existing keys, yes?
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MzKrZcX-Z5Rq1viIMns:-MzKrZcX-Z5Rq1viIMnt:b3g7p0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6c5548070ea0de4a594eed976cb69c4909d8f3/pkg/cmd/roachtest/tests/multitenant_fairness.go#L250)):*
> ```Go
> 	}
> 
> 	// TODO: Can we do anything to verify that admission control kicked in?  Check some stats?
> ```

there are no tables with admission control stats. Only metrics. We may be able to do something with prometheus wrt doing an aggregation over time. I am fine with leaving a TODO if you've eyeballed these runs and seen admission control kick in.


<!-- Sent from Reviewable.io -->

2022-03-29 15:30 UTC, cucaroach reviewed
Yes, although there's no clear relationship.   I wonder if I should use --max-ops to get an exact size distribution instead of using time which is probably noisy.   I will dig into the how the reads behave I have wondered about that.   I also wonder if I should simplify this and do just one kv run invocation and just concurrently reset the stats after warmup period expires.  That should eliminate a lot of pitfalls.  Then maybe instead of doing a duration based size skew I can skew the size based on min/max block sizes..

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-:-MzLEKjJ0ryarjdx-aS3:b-8jyhk0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @sumeerbhola, and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-Myw7I0lCcIeRu6okboX:-Myw7I0lCcIeRu6okboY:bsl4hcx) (no related file):*
Thanks for the review feedback!   Here's version 2, I've moved the pods/workloads to their own nodes and expanded things a bit to see how AC handles heterogenous concurrency and database size.    Still a work in progress and need to analyze some runs and how well this is exercising things.  Any and all feedback welcome!

---
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MyNF8hL6JTRoRNDieU6:-MzLGxM13f2JQvURBgUN:b-yknivj) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fe46c448a85fc9f8933da3f5f580f46f56f69f/pkg/cmd/roachtest/tests/multitenant_fairness.go#L122)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think this is one of the tests that would really benefit from using prometheus instead of ad-hoc metrics stuff. For a recent example, see https://github.com/cockroachdb/cockroach/pull/76147/files#diff-28a39375143eb2ad1e76868f4086035dc8099dc89f98658c3f62f52987945b1eR139-R152. There are also the multi-region DRT tests, `drt.go`, which do something similar (but that's where I learned from, so my code is probably more easily digested for your use case).

The main reasons I am suggestion prometheus here is that a) you can test whatever metrics you like without any limits and b) if the test fails, you can easily go through the metrics and figure out exactly what was wrong since there'll be a prometheus snapshot in the artifacts.
</blockquote></details>

Sounds nice, what can I do with a prometheus snapshot, can that encompass any metrics from the db or is that just for metrics I produce from my test?
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MzKswGUA4yCyWgVASzV:-MzLFpTJ-jF93nxhA2iD:b5w6lbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6c5548070ea0de4a594eed976cb69c4909d8f3/pkg/cmd/roachtest/tests/multitenant_fairness.go#L54)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

looks like this will be called with i in [1,5]. Is that correct? So lowest concurrency is 8 and highest is 40.

And we are using a 4 cpu KV node?

Do you know if 4 tenants with a concurrency of 8 each are sufficient to saturate cpu for this no writes (kv-fairness) case, and sufficient to saturate the store in the only writes (store-fairness) case below?

Perhaps the delta number below is because a concurrency of 8 is too low to utilize 25% of the store capacity.
```
admission-control-on/store-fairness/concurrency-skew/run_1/test.log
27:19:04:54 multitenant_fairness.go:236: Max throughput delta: 37% [4335 7058 7875 8621]
```

</blockquote></details>

Here's what CPU % looks like for admission-control-on/kv-fairness/same:

![admission-control-on:kv-fairness:same.png](https://files.reviewableusercontent.io/images/reviewable/80277990/ECtY6vZHdeqiscmHvTvf-N8u/admission-control-on%3Akv-fairness%3Asame.png)

Maybe not fully saturated but close...
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MzKuJzMEtDr_lKFdak1:-MzLGWoj7VnGeci_uy4w:b-gi9kra) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6c5548070ea0de4a594eed976cb69c4909d8f3/pkg/cmd/roachtest/tests/multitenant_fairness.go#L90)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do you expect initial size skew to matter in this case that does only writes? I am assuming the writes after setup are not limited to overwriting the existing keys, yes?
</blockquote></details>

Hmm, since I'm not passing write-seq I guess its possible we're overwriting existing keys if the seed is stable.  One more reason to get rid of multi pass and just have one workload run.
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MzKrZcX-Z5Rq1viIMns:-MzLI1x-1J61qtb0tAqu:b7daa31) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6c5548070ea0de4a594eed976cb69c4909d8f3/pkg/cmd/roachtest/tests/multitenant_fairness.go#L250)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

there are no tables with admission control stats. Only metrics. We may be able to do something with prometheus wrt doing an aggregation over time. I am fine with leaving a TODO if you've eyeballed these runs and seen admission control kick in.
</blockquote></details>

Seems like its kicking in a little.  I'll try to crank it up a bit.

![admission-control-on:kv-fairness:same-ac-rate.png](https://files.reviewableusercontent.io/images/reviewable/80277990/iekjJliJGGcs8bKp7TzaWbuO/admission-control-on%3Akv-fairness%3Asame-ac-rate.png)


<!-- Sent from Reviewable.io -->

2022-03-29 16:18 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @sumeerbhola, and @tbg)

___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MzKswGUA4yCyWgVASzV:-MzLRgLa5DjEOiXDHxpH:bxfcpxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6c5548070ea0de4a594eed976cb69c4909d8f3/pkg/cmd/roachtest/tests/multitenant_fairness.go#L54)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Here's what CPU % looks like for admission-control-on/kv-fairness/same:

![admission-control-on:kv-fairness:same.png](https://files.reviewableusercontent.io/images/reviewable/80277990/ECtY6vZHdeqiscmHvTvf-N8u/admission-control-on%3Akv-fairness%3Asame.png)

Maybe not fully saturated but close...

</blockquote></details>

it is not close enough for admission control to kick in for cpu. The default for admission.kv_slot_adjuster.overload_threshold (for runnable goroutines) is 32.
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-MzKrZcX-Z5Rq1viIMns:-MzLSMvN8fycuS_cO9aS:b-nt6sex) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6c5548070ea0de4a594eed976cb69c4909d8f3/pkg/cmd/roachtest/tests/multitenant_fairness.go#L250)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Seems like its kicking in a little.  I'll try to crank it up a bit.

![admission-control-on:kv-fairness:same-ac-rate.png](https://files.reviewableusercontent.io/images/reviewable/80277990/iekjJliJGGcs8bKp7TzaWbuO/admission-control-on%3Akv-fairness%3Asame-ac-rate.png)

</blockquote></details>


We do want the admission delay rate to consistently stay positive.
And the delay rate/work rate should be a few ms at least (this is the mean admission latency). Even the spike in admission delay rate above of 120k, when divided by 20K work rate is 6 micros, which is too low.


<!-- Sent from Reviewable.io -->

2022-03-29 22:33 UTC, cucaroach commented
Here's the latest kv-fairness/same w/ admission control on/off.

<img width="1415" alt="Screen Shot 2022-03-29 at 6 32 29 PM" src="https://user-images.githubusercontent.com/80277990/160717767-336017af-7a2e-453b-beb5-f0babc2d3ca0.png">

2022-03-29 22:37 UTC, cucaroach commented
The are all running on http://34.148.129.97/. 

Here's the list of tests:
```
./admission-control-on/kv-fairness/size-skew/run_1/tsdump.gob
./admission-control-on/kv-fairness/concurrency-skew/run_1/tsdump.gob
./admission-control-on/kv-fairness/same/run_1/tsdump.gob
./admission-control-on/store-fairness/size-skew/run_1/tsdump.gob
./admission-control-on/store-fairness/concurrency-skew/run_1/tsdump.gob
./admission-control-on/store-fairness/same/run_1/tsdump.gob
./admission-control-off/kv-fairness/size-skew/run_1/tsdump.gob
./admission-control-off/kv-fairness/concurrency-skew/run_1/tsdump.gob
./admission-control-off/kv-fairness/same/run_1/tsdump.gob
./admission-control-off/store-fairness/size-skew/run_1/tsdump.gob
./admission-control-off/store-fairness/concurrency-skew/run_1/tsdump.gob
./admission-control-off/store-fairness/same/run_1/tsdump.gob
```

With the corresponding port assignments:

```

treilly  25976     1  2 22:24 pts/2    00:00:12 cockroach start-single-node --insecure --http-addr :8081 --listen-addr :26258 --store /tmp/tmp.gmtvLnHPIm
treilly  26040     1  1 22:24 pts/2    00:00:11 cockroach start-single-node --insecure --http-addr :8082 --listen-addr :26259 --store /tmp/tmp.XLOPl3eKYi
treilly  26104     1  2 22:24 pts/2    00:00:12 cockroach start-single-node --insecure --http-addr :8083 --listen-addr :26260 --store /tmp/tmp.zSRjvIa7C8
treilly  26182     1  2 22:24 pts/2    00:00:12 cockroach start-single-node --insecure --http-addr :8084 --listen-addr :26261 --store /tmp/tmp.tCzWw2BtKh
treilly  26246     1  2 22:24 pts/2    00:00:11 cockroach start-single-node --insecure --http-addr :8085 --listen-addr :26262 --store /tmp/tmp.qSOGYICyZM
treilly  26319     1  2 22:24 pts/2    00:00:12 cockroach start-single-node --insecure --http-addr :8086 --listen-addr :26263 --store /tmp/tmp.jak4cwQy45
treilly  26384     1  2 22:24 pts/2    00:00:12 cockroach start-single-node --insecure --http-addr :8087 --listen-addr :26264 --store /tmp/tmp.eZkYyj4MBI
treilly  26475     1  2 22:24 pts/2    00:00:12 cockroach start-single-node --insecure --http-addr :8088 --listen-addr :26265 --store /tmp/tmp.wZ8fqktn0u
treilly  26549     1  2 22:24 pts/2    00:00:12 cockroach start-single-node --insecure --http-addr :8089 --listen-addr :26266 --store /tmp/tmp.LnSeN1KJEm
treilly  26612     1  1 22:24 pts/2    00:00:11 cockroach start-single-node --insecure --http-addr :8090 --listen-addr :26267 --store /tmp/tmp.PiuCTyfVIE
treilly  26673     1  1 22:24 pts/2    00:00:11 cockroach start-single-node --insecure --http-addr :8091 --listen-addr :26268 --store /tmp/tmp.E0ZvRiibAB
treilly  26751     1  1 22:24 pts/2    00:00:11 cockroach start-single-node --insecure --http-addr :8092 --listen-addr :26269 --store /tmp/tmp.t6LDV6jgGV
```

So kv-fairness same on vs off is 8083 and 8089

2022-03-29 22:52 UTC, cucaroach commented
Here's the metrics for the runs above:

```
admission-control-on/kv-fairness/same/run_1/test.log
27:21:14:06 multitenant_fairness.go:226: Max throughput delta: 0% [374980 372841 371115 373571]
28:21:14:06 multitenant_fairness.go:237: Max latency delta: 0% [0.09838571427666201 0.0983222636944495 0.09845849673140669 0.09866594939322008]

admission-control-off/kv-fairness/same/run_1/test.log
27:21:14:20 multitenant_fairness.go:226: Max throughput delta: 1% [332511 334115 327458 328547]
28:21:14:20 multitenant_fairness.go:237: Max latency delta: 0% [0.11011505723921523 0.11015030326933709 0.11123614902932685 0.11175606750073881]

admission-control-on/kv-fairness/concurrency-skew/run_1/test.log
27:21:14:54 multitenant_fairness.go:226: Max throughput delta: 0% [373043 373400 372668 375798]
28:21:14:54 multitenant_fairness.go:237: Max latency delta: 0% [0.09839661788659015 0.0989487048111687 0.09904430286830378 0.09788012240106932]

admission-control-off/kv-fairness/concurrency-skew/run_1/test.log
27:21:14:17 multitenant_fairness.go:226: Max throughput delta: 1% [356143 353205 350085 355234]
28:21:14:17 multitenant_fairness.go:237: Max latency delta: 1% [0.10245501175890222 0.10325969819235263 0.10471150936353245 0.10360494607515]

admission-control-on/kv-fairness/size-skew/run_1/test.log
27:21:14:17 multitenant_fairness.go:226: Max throughput delta: 98% [4834 331257 328272 326965]
29:21:14:17 multitenant_fairness.go:237: Max latency delta: 5% [0.10354547360860568 0.11148500712492625 0.11198685482990056 0.11178204459124719]

admission-control-off/kv-fairness/size-skew/run_1/test.log
27:21:14:17 multitenant_fairness.go:226: Max throughput delta: 98% [5147 353123 349545 349786]
28:21:14:17 multitenant_fairness.go:237: Max latency delta: 9% [0.0904315736263841 0.10293622788041812 0.10374982631305775 0.10392101268366669]

admission-control-on/store-fairness/same/run_1/test.log
27:21:29:36 multitenant_fairness.go:226: Max throughput delta: 16% [39343 35719 33099 28697]
28:21:29:36 multitenant_fairness.go:237: Max latency delta: 17% [0.6890004264550749 0.7574437577303095 0.8198215218296948 0.9429895461594577]

admission-control-off/store-fairness/same/run_1/test.log
27:21:14:16 multitenant_fairness.go:226: Max throughput delta: 3% [23903 24937 24481 23223]
28:21:14:16 multitenant_fairness.go:237: Max latency delta: 4% [1.0878097552941446 1.0247036370398215 1.037290222089092 1.1177694609817843]

admission-control-on/store-fairness/size-skew/run_1/test.log
27:21:29:46 multitenant_fairness.go:226: Max throughput delta: 18% [36610 32489 27536 27301]
28:21:29:46 multitenant_fairness.go:237: Max latency delta: 16% [0.7354827762547138 0.8160667846137513 0.9820065250160528 0.9730210919445484]


admission-control-off/store-fairness/size-skew/run_1/test.log
27:21:14:16 multitenant_fairness.go:226: Max throughput delta: 5% [23736 24204 24676 22582]
28:21:14:16 multitenant_fairness.go:237: Max latency delta: 3% [1.1001490164555943 1.04747738008296 1.0474747277620406 1.1084257969557636]

admission-control-on/store-fairness/concurrency-skew/run_1/test.log
27:21:14:11 multitenant_fairness.go:226: Max throughput delta: 18% [40462 36644 36882 29285]
28:21:14:11 multitenant_fairness.go:237: Max latency delta: 19% [0.6629120118952132 0.7308463744794805 0.7376011781705947 0.9102437578656989]

admission-control-off/store-fairness/concurrency-skew/run_1/test.log
27:21:14:49 multitenant_fairness.go:226: Max throughput delta: 8% [23677 24434 21352 23431]
28:21:14:49 multitenant_fairness.go:237: Max latency delta: 10% [1.0706455065770573 1.046496808200623 1.2067807059272684 1.0608706575446623]
```

Something fishy with kv-fairness size-skew...

2022-03-29 22:53 UTC, cucaroach commented
The last 3 comments correspond with SHA 571bc061426f82e5b7584cea7954488da099c6e9

2022-03-29 23:06 UTC, cucaroach commented
With the objective being to demonstrate that admission control is no worse than w/o admission control I'm gonna declare mission accomplished.  For what its worth I really wish the timeseries data could be tagged and dumped into one database for easier analysis (ala oggy).

2022-03-31 13:36 UTC, tbg commented
Test setup looks good to me, I'll defer to Sumeer for the review of the actual test.

2022-03-31 14:16 UTC, sumeerbhola reviewed
These numbers look much better for admission-control-off than before, which is very puzzling. Specifically, we should expect significant difference with concurrency-skew.
The same case is using a concurrency of 48 for kv-fairness, while the concurrency-skew is using a set {10, 20, 30, 40, 50} (so a mean of 30). 48 is very slight overload in the same case -- runnable goroutines are hovering between 24 and 32 with admission control off. As I had mentioned earlier, the admission.kv_slot_adjuster.overload_threshold (for runnable goroutines) is 32. Can you rerun kv-fairness with the same concurrency of 80, and the concurrency-skew with {80, 160, 240, 320, 400}.

Also, let's get rid of size-skew completely. For kv-fairness, I don't see any difference in the spec between size-skew and same. For store-fairness, what you are doing now is changing the size of the write and read which means the admission control system will account for the different amounts of work and the throughput for different tenants will be different (this is already the case for the cpu bottleneck, since it is roughly equalizing slot-seconds, and will be true in the near future for store write tokens too).

We still need to investigate why `admission-control-on/store-fairness/concurrency-skew` is worse now than before. We want to tune the block sizes such that cpu utilization is significantly below 100% and only the store write tokens are constraining admission. That may already be true, but can you get the graphs from the overload dashboard to be sure.

I think we are close now, and the good thing is we only need to investigate and understand the two concurrency-skew experiments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-:-MzVEyYVAOFU2zZT65a-:b-ozbnjm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @sumeerbhola, and @tbg)



<!-- Sent from Reviewable.io -->

2022-04-05 01:52 UTC, cucaroach commented
I've done more experiments but can't get the kv IO token metric to budge.   What knobs can I tweak to stress I/O?   Do I need bigger transactions?   Do I need to make the kv workload cycle length small so I have lots of update collisions?   Maybe I need a bigger dataset?   Do we have other tests that cause disk stress?    Maybe I should turn on the secondary index...

2022-04-05 20:38 UTC, tbg commented
Not sure it completely applies here, but I had [good success](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1649068865739699?thread_ts=1649016671.689349&cid=C0KB9Q03D) triggering admission control on the write path with an incantation like

```
./cockroach workload run kv --read-percent 5 --concurrency 10 --min-block-bytes 10000 --max-block-bytes 10000 --sequential
```

and multiple instances of this. This is a write-heavy hotspot workload. The number of instances determines the number of hotspots.

2022-04-06 01:23 UTC, cucaroach commented
Here's the latest results, we now have solid IO token overload in store-fairness tests:

```
multitenant/admission-control-on/kv-fairness/same/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.527271, "max_latency_delta": 0.105453, "max_tput": 2276.263333, "min_tput": 731.660000, "max_latency": 0.123263, "min_latency": 0.099857}

multitenant/admission-control-off/kv-fairness/same/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.459949, "max_latency_delta": 0.204092, "max_tput": 1887.778889, "min_tput": 732.267778, "max_latency": 0.143129, "min_latency": 0.095761}

multitenant/admission-control-on/kv-fairness/concurrency-skew/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.533096, "max_latency_delta": 0.097088, "max_tput": 2283.990000, "min_tput": 720.470000, "max_latency": 0.123466, "min_latency": 0.101828}

multitenant/admission-control-off/kv-fairness/concurrency-skew/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.448792, "max_latency_delta": 0.220901, "max_tput": 2129.665556, "min_tput": 858.896667, "max_latency": 0.124979, "min_latency": 0.080862}

multitenant/admission-control-on/store-fairness/same/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.021955, "max_latency_delta": 0.579853, "max_tput": 25.364444, "min_tput": 24.377778, "max_latency": 1.324273, "min_latency": 0.367025}

multitenant/admission-control-off/store-fairness/same/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.311267, "max_latency_delta": 0.092532, "max_tput": 30.297778, "min_tput": 15.080000, "max_latency": 1.308540, "min_latency": 1.133717}

multitenant/admission-control-on/store-fairness/concurrency-skew/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.609175, "max_latency_delta": 0.580976, "max_tput": 50.122222, "min_tput": 24.217778, "max_latency": 1.292939, "min_latency": 0.366841}

multitenant/admission-control-off/store-fairness/concurrency-skew/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.644078, "max_latency_delta": 0.059790, "max_tput": 30.727778, "min_tput": 7.503333, "max_latency": 1.228227, "min_latency": 1.089796}
```

The numbers aren't amazing, but probably are more indicative of test noise than issues with admission control.   Honestly I think we should withhold judgment until we can see how the numbers look over the course of a number of runs.

2022-04-06 19:55 UTC, cucaroach commented
Here's another run:

```
multitenant/admission-control-on/kv-fairness/concurrency-skew/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.534833, "max_latency_delta": 0.095604, "max_tput": 2151.991111, "min_tput": 673.953333, "max_latency": 0.130758, "min_latency": 0.108473}

multitenant/admission-control-off/kv-fairness/concurrency-skew/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.443888, "max_latency_delta": 0.225029, "max_tput": 2003.197778, "min_tput": 806.834444, "max_latency": 0.133532, "min_latency": 0.086128}

multitenant/admission-control-on/kv-fairness/same/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.535304, "max_latency_delta": 0.094485, "max_tput": 2263.886667, "min_tput": 706.484444, "max_latency": 0.124033, "min_latency": 0.103133}

multitenant/admission-control-off/kv-fairness/same/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.444655, "max_latency_delta": 0.223417, "max_tput": 2088.057778, "min_tput": 841.360000, "max_latency": 0.127948, "min_latency": 0.082873}

multitenant/admission-control-on/store-fairness/same/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.023869, "max_latency_delta": 0.564604, "max_tput": 25.463333, "min_tput": 24.373333, "max_latency": 1.328105, "min_latency": 0.381142}

multitenant/admission-control-off/store-fairness/same/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.460315, "max_latency_delta": 0.044919, "max_tput": 43.894444, "min_tput": 14.885556, "max_latency": 1.232521, "min_latency": 1.128021}

multitenant/admission-control-on/store-fairness/concurrency-skew/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.035574, "max_latency_delta": 0.594139, "max_tput": 25.754444, "min_tput": 24.394444, "max_latency": 1.379416, "min_latency": 0.364090}

multitenant/admission-control-off/store-fairness/concurrency-skew/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.385942, "max_latency_delta": 0.179768, "max_tput": 50.658889, "min_tput": 13.947778, "max_latency": 1.331765, "min_latency": 0.992237}
```

The store-fairness admission control is remarkably good at throughput consistency although concurrency skew doesn't throw it much of a curve ball compared to same.   The kv-fairness seems to be more about latency fairness with maybe a little throughput bump due to reduced contention.  Is that in line with expectations?

2022-04-06 20:25 UTC, cucaroach commented
@sumeerbhola I can easily fire up the tsdump consoles for any of the last couple runs if you want to look at any metrics, just let me know.

2022-04-08 14:45 UTC, sumeerbhola requested changes
> The kv-fairness seems to be more about latency fairness with maybe a little throughput bump due to reduced contention.

I don't think we need to measure latency fairness. Admission control is trying to allocate resources fairly which should equalize throughput. By doing so, the latency for the higher concurrency tenants will be worse since they will have to wait longer. 

Also, do you know why the latter run for `admission-control-on/store-fairness/concurrency-skew` has low throughput delta while the previous one has high delta. Was anything changed?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-:-N-8bHpS6s48d_4zvePy:b-4cfsb2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @sumeerbhola, and @tbg)

___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 48 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-N-8_hu8-CdsdcaDijkb:-N-8_hu8-CdsdcaDijkc:bzhkx2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/607b410373b6db60bb07ff9f1897b555657b0b62/pkg/cmd/roachtest/tests/multitenant_fairness.go#L48)):*
> ```Go
> 				name:        "same",
> 				concurrency: func(int) int { return 80 },
> 				blockSizes:  func(int) (int, int) { return 4, 8 },
> ```

We need to understand the high throughput delta in this case. I would expect it to be low regardless of whether admission control was on or off. What do the metrics of goroutine count look like with admission off and on. And with on, what does the admission control queueing latency and kv slots look like?
Let me know if you want to do this interactively with a meeting -- it may be faster.

The kv workload prints the throughput every few seconds. I think we need to look at the logs for all the tenants to see whether the throughput fairness is changing over the course of the run.
___
*[pkg/cmd/roachtest/tests/multitenant_fairness.go, line 52 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-N-8aJy0C7SUXe6Ytoi1:-N-8aJy0C7SUXe6Ytoi2:b-wuh3c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/607b410373b6db60bb07ff9f1897b555657b0b62/pkg/cmd/roachtest/tests/multitenant_fairness.go#L52)):*
> ```Go
> 			{
> 				name:        "concurrency-skew",
> 				concurrency: func(i int) int { return i * 80 },
> ```

This case has a high throughput delta too with admission control on. Strange. But lets understand "same" first.


<!-- Sent from Reviewable.io -->

2022-04-08 19:08 UTC, cucaroach commented
I think I have some kind of reporting anomoly, the workload files for the "same" run show the concurrency levels for the concurrency-skew test.   Let me run it again and make sure all the ducks are lined up.

2022-04-11 16:06 UTC, cucaroach commented
Okay I figured out the problem with the tests (value vs reference lambda capture issue).  Here's a run of 3:

https://docs.google.com/spreadsheets/d/1YuZpgBpuhAjGMzN5Xj8awyTygtT8VqeBlDaAZv9TBZI/edit?usp=sharing

Hopefully this gives a clearer picture of whats going on.  Getting on a call to dig through results would be great!

2022-04-13 20:54 UTC, sumeerbhola commented
> the multitenant support in roachtest is incomplete and doesn’t use certs so the tenant id is never propagated from the sql pod to the kv server

Is there a work around for this that will allow us to test?

2022-04-13 21:40 UTC, cucaroach commented
> Is there a work around for this that will allow us to test?

I'm working on a quick fix, its not too hard since roachprod already supports secure mode and I have just to generate the tenant and client certs (I think).

2022-04-28 20:27 UTC, cucaroach commented
Here's the latest results that I think look pretty good.
```
multitenant/fairness/store/concurrency-skew/admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.238019, "max_latency_delta": 0.275468, "max_tput": 174.334444, "min_tput": 108.147778, "max_latency": 0.173205, "min_latency": 0.101687}

multitenant/fairness/store/concurrency-skew/no-admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.450391, "max_latency_delta": 0.059209, "max_tput": 169.963333, "min_tput": 64.195556, "max_latency": 0.174815, "min_latency": 0.155879}

multitenant/fairness/store/same/admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.024674, "max_latency_delta": 0.043759, "max_tput": 140.780000, "min_tput": 135.815556, "max_latency": 0.134441, "min_latency": 0.126053}

multitenant/fairness/store/same/no-admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.012418, "max_latency_delta": 0.022016, "max_tput": 128.071111, "min_tput": 124.966667, "max_latency": 0.138694, "min_latency": 0.133920}

multitenant/fairness/kv/concurrency-skew/admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.329216, "max_latency_delta": 0.418922, "max_tput": 1886.764167, "min_tput": 922.146667, "max_latency": 0.116354, "min_latency": 0.049378}

multitenant/fairness/kv/concurrency-skew/no-admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.447648, "max_latency_delta": 0.218034, "max_tput": 1578.764167, "min_tput": 635.807500, "max_latency": 0.106256, "min_latency": 0.068819}

multitenant/fairness/kv/same/admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.328848, "max_latency_delta": 0.039585, "max_tput": 1754.685000, "min_tput": 1167.888333, "max_latency": 0.117428, "min_latency": 0.109470}

multitenant/fairness/kv/same/no-admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.011448, "max_latency_delta": 0.021655, "max_tput": 1107.762500, "min_tput": 1086.889167, "max_latency": 0.127527, "min_latency": 0.122893}
```

```
multitenant/fairness/kv/concurrency-skew/admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.260764, "max_latency_delta": 0.487317, "max_tput": 1292.920000, "min_tput": 828.346667, "max_latency": 0.193207, "min_latency": 0.052886}

multitenant/fairness/kv/concurrency-skew/no-admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.488463, "max_latency_delta": 0.189269, "max_tput": 1308.253333, "min_tput": 470.410000, "max_latency": 0.121861, "min_latency": 0.087920}

multitenant/fairness/kv/same/admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.033435, "max_latency_delta": 0.154574, "max_tput": 1143.290000, "min_tput": 1082.263333, "max_latency": 0.136882, "min_latency": 0.103692}

multitenant/fairness/kv/same/no-admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.008568, "max_latency_delta": 0.204921, "max_tput": 985.156667, "min_tput": 971.610000, "max_latency": 0.155348, "min_latency": 0.104403}

multitenant/fairness/store/concurrency-skew/admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.221799, "max_latency_delta": 0.299106, "max_tput": 152.531111, "min_tput": 101.156667, "max_latency": 0.187678, "min_latency": 0.101447}

multitenant/fairness/store/concurrency-skew/no-admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.510869, "max_latency_delta": 0.077613, "max_tput": 166.635556, "min_tput": 53.558889, "max_latency": 0.176941, "min_latency": 0.153929}

multitenant/fairness/store/same/admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.057072, "max_latency_delta": 0.024260, "max_tput": 140.596667, "min_tput": 125.931111, "max_latency": 0.131501, "min_latency": 0.125317}

multitenant/fairness/store/same/no-admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.005693, "max_latency_delta": 0.049709, "max_tput": 120.416667, "min_tput": 119.298889, "max_latency": 0.140880, "min_latency": 0.131197}
```

2022-05-03 02:07 UTC, sumeerbhola commented
@cucaroach these are older than the ones you shared on slack on april 29th yes?
Also, I'll wait until there are updated numbers for the kv one, as we discussed.

2022-05-03 17:42 UTC, cucaroach commented
After bumping up kv/same concurrency to 250 we get more impressive throughput improvements but still tput_delta I think its just too consistently low for no-admission.  But we can hang our hats on the concurrency-skew tput_delta looking good.

```
multitenant/fairness/kv/same/admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.144249, "max_latency_delta": 0.036923, "max_tput": 304.520000, "min_tput": 245.673333, "max_latency": 0.781684, "min_latency": 0.728603}

multitenant/fairness/kv/same/no-admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.026597, "max_latency_delta": 0.087155, "max_tput": 163.460000, "min_tput": 156.700000, "max_latency": 1.525155, "min_latency": 1.324899}

multitenant/fairness/kv/concurrency-skew/admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.129229, "max_latency_delta": 0.630038, "max_tput": 286.176667, "min_tput": 232.210000, "max_latency": 2.107538, "min_latency": 0.472873}

multitenant/fairness/kv/concurrency-skew/no-admission/run_1/1.perf/stats.json
1:{ "max_tput_delta": 0.457215, "max_latency_delta": 0.378929, "max_tput": 225.376667, "min_tput": 96.706667, "max_latency": 2.449109, "min_latency": 1.436515}
```

2022-05-04 19:48 UTC, sumeerbhola commented
Looks good! "max_tput_delta": 0.129229 is certainly better than "max_tput_delta": 0.457215.

- Can you update the PR and commit description with the latest results for kv and store?
- I suggest removing max_latency_delta since it is confusing -- there should be a high latency delta in the skewed case if we fairly allocate to all tenants. If you want to keep it, please add a code comment explaining to the reader the reason for the observed latency delta.

2022-05-04 19:55 UTC, sumeerbhola requested changes
> Reviewed 3 of 7 files at r11, 1 of 6 files at r12, 1 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @sumeerbhola, and @tbg)

___
*[`pkg/cmd/roachtest/tests/multitenant_fairness.go` line 54 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-N1Fbnaa7OjRn0Y8W8yh:-N1Fbnaa7OjRn0Y8W8yi:brx7efs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1d989e48977c920aa479a5eb39041bc83b3ed1/pkg/cmd/roachtest/tests/multitenant_fairness.go#L54)):*
> ```Go
> 			{
> 				name:        "concurrency-skew",
> 				concurrency: func(i int) int { return i * 150 },
> ```

this should be i * 250.
We've verified that a concurrency of 250 is enough to consume 25% of the cpu when running "same" with no-admission, since it causes enough queueing in the goroutine scheduler. In the skewed case we want the smallest tenant to continue to be as demanding:  with perfect fairness it would get 25%.
___
*[`pkg/cmd/roachtest/tests/multitenant_fairness.go` line 83 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-N1FcaY8AZwQMz8FRKDn:-N1FcaY8AZwQMz8FRKDo:b64yqwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1d989e48977c920aa479a5eb39041bc83b3ed1/pkg/cmd/roachtest/tests/multitenant_fairness.go#L83)):*
> ```Go
> 			{
> 				name:        "concurrency-skew",
> 				concurrency: func(i int) int { return i * 20 },
> ```

same question. Why not i * 50.


<!-- Sent from Reviewable.io -->

2022-05-16 15:29 UTC, cucaroach commented
Here's the latest results with beta.5, I don't what happened but for store at least no-admission looks better.  Any thoughts for digging into that?  I think when we jacked up the operation size to get more lsm 0 files this happened, I'll revert those changes and see what happens.

```
multitenant/fairness/kv/concurrency-skew/admission/run_1/1.perf/stats.json { "max_tput_delta": 0.340925, "max_tput": 483.200000, "min_tput": 256.056667, "max_latency": 3.282347, "min_latency": 0.771148}
multitenant/fairness/kv/concurrency-skew/no-admission/run_1/1.perf/stats.json { "max_tput_delta": 0.330760, "max_tput": 205.740000, "min_tput": 108.903333, "max_latency": 7.151178, "min_latency": 1.618236}

multitenant/fairness/kv/same/admission/run_1/1.perf/stats.json { "max_tput_delta": 0.245294, "max_tput": 293.990000, "min_tput": 197.026667, "max_latency": 0.831686, "min_latency": 0.762475}
multitenant/fairness/kv/same/no-admission/run_1/1.perf/stats.json { "max_tput_delta": 0.031199, "max_tput": 132.443333, "min_tput": 124.676667, "max_latency": 1.915801, "min_latency": 1.776664}

multitenant/fairness/store/same/admission/run_1/1.perf/stats.json { "max_tput_delta": 0.018095, "max_tput": 139.950000, "min_tput": 136.336667, "max_latency": 0.346295, "min_latency": 0.341212}
multitenant/fairness/store/same/no-admission/run_1/1.perf/stats.json { "max_tput_delta": 0.001886, "max_tput": 149.296667, "min_tput": 148.878333, "max_latency": 0.306853, "min_latency": 0.303392}

multitenant/fairness/store/concurrency-skew/admission/run_1/1.perf/stats.json { "max_tput_delta": 0.024872, "max_tput": 143.875000, "min_tput": 138.346667, "max_latency": 1.094262, "min_latency": 0.346674}
multitenant/fairness/store/concurrency-skew/no-admission/run_1/1.perf/stats.json { "max_tput_delta": 0.005439, "max_tput": 148.848333, "min_tput": 147.500000, "max_latency": 1.007741, "min_latency": 0.313597}
```

2022-05-16 23:35 UTC, cucaroach commented
Actually reverting the value size changes didn't change much, I keep forgetting store admission control can and should lower throughput to prevent LSM from getting unhappy, although it makes me queasy to take performance off the table.  I wonder what happen if we ran this test for days, would the LSM implode at some point with too many L0 files?  What would that look like?

2022-05-18 17:07 UTC, sumeerbhola commented
> Any thoughts for digging into that?

I think we'd need to periodically log the slots and tokens allocated to each tenant to debug this.
If you want to leave a TODO to investigate, and merge this, I am ok with that.

>  I wonder what happen if we ran this test for days, would the LSM implode at some point with too many L0 files?

The node will probably fail heartbeats or other badness would happen. Tolerating a very poorly shaped LSM in order to get higher write throughput does not work out in a production setting.

2022-05-23 14:50 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77481#-:-N2lORvO7X7c89z_Ls6_:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @sumeerbhola, and @tbg)



<!-- Sent from Reviewable.io -->

2022-05-23 19:32 UTC, cucaroach commented
bors r+

2022-05-23 20:50 UTC, merged