changefeedccl: allow changefeeds specifying individual column families
cockroachdb/cockroach pull request #77640
Opened 2022-03-10 21:22 UTC by HonoreDB

Implements "CREATE CHANGEFEED FOR foo FAMILY bar". `foo FAMILY bar` is
a target, and can be part of a target list. The same table can now appear
multiple times in the same feed. (Fanning out to different topics will
be a separate PR, right now it's still by default a topic per table).

The rangefeed still covers the entire primary key span. I don't think
there's much room for efficiency gain by enabling it to filter by family,
but it's worth looking into. Instead we cache a check by family id in
the changefeed processor.

Release note (enterprise change): Changefeeds can now specify column families to target, using the syntax `[TABLE] foo FAMILY bar`. For example,`CREATE CHANGEFEED FOR TABLE foo FAMILY bar, TABLE foo FAMILY baz, TABLE users` will create a feed that watches the bar and baz column families of foo, as well as the whole table users. A family must exist with that name when the feed is created. If all columns in a watched family are dropped in an ALTER TABLE statement, the feed will fail with an error, similarly to dropping a table. Behavior is otherwise similar to feeds created using split_column_families.

Release note (sql change): Changefeeds can now specify column families to target, using the syntax `[TABLE] foo FAMILY bar`. For example,`EXPERIMENTAL CHANGEFEED FOR TABLE foo FAM
ILY bar, TABLE foo FAMILY baz, TABLE users` will create a feed that watches the bar and baz column families of foo, as well as the whole table users. A family must exist with that
name when the feed is created. If all columns in a watched family are dropped in an ALTER TABLE statement, the feed will fail with an error, similarly to dropping a table. Behavior
 is otherwise similar to feeds created using split_column_families.

Release justification: Additive change that mainly takes advantage of existing plumbing already merged.

2022-03-10 21:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/77640)
<!-- Reviewable:end -->

2022-03-11 14:59 UTC, miretskiy reviewed
Would be nice to see expanded test coverage.  (maybe it's done already).  I would love to see cases when:
* The table created after changefeed paused is added via alter statement.
* Removal of all targets?
* Wholesale replacement of all targets.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-:-MxtUF9N0uyu1F6XCnow:b-t2dx8x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2022-03-11 17:48 UTC, HonoreDB reviewed
I think this comment was meant for https://github.com/cockroachdb/cockroach/pull/77263. But this PR needs more test coverage too, including around alter changefeed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-:-Mxu4uAu8dC9Tqv1qmR3:b-89p6b6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2022-03-14 12:45 UTC, miretskiy requested changes
> Reviewed 3 of 12 files at r1, 15 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77640)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @HonoreDB, and @sherman-grewal)

___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7MnJw9yzgtEnY8kZR:-My7MnJw9yzgtEnY8kZS:b-lmv9j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/changefeed_dist.go#L139)):*
> ```Go
> 		// Note that all targets are currently guaranteed to have a Table ID
> 		// and lie within the primary index span. Deduplication is important
> 		// here as requesting the same span twice will deadlock.
> ```

curious: deadlock where?
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 723 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7MztwBg6zVoU112IJ:-My7MztwBg6zVoU112IK:b-ehz21o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/changefeed_processors.go#L723)):*
> ```Go
> 	if err != nil {
> 		// Column families are stored contiguously, so we'll get
> 		// events for each one even if we're not watching them all.
> ```

is that how it works? 1 event for each family even if you're not watching some?
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 559 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7R54FAN1_l8kiaI3r:-My7R54FAN1_l8kiaI3s:byye2c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/changefeed_stmt.go#L559)):*
> ```Go
> 	}
> 	for i, ct := range rawTargets {
> ```

nit: drop \n?
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 583 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7RB8Z7xHguCJfNkzZ:-My7RB8Z7xHguCJfNkz_:bx161ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/changefeed_stmt.go#L583)):*
> ```Go
> 
> // TODO (zinger): This is redoing work already done in backupresolver. Have backupresolver
> // return a map of descriptors to table patterns so this isn't necessary and is less fragile.
> ```

Can we do that instead of TODO? Is it too much for this PR?
___
*[pkg/ccl/changefeedccl/encoder.go, line 194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7RvCXAl0Z4x8493Y3:-My7RvCXAl0Z4x8493Y4:b7wm0ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/encoder.go#L194)):*
> ```Go
> 	descID := row.tableDesc.GetID()
> 	// use the target list since row.tableDesc.GetName() will not have fully qualified names
> 	for _, target := range e.targets {
> ```

do we need to memoize?
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 211 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7SKUlCouvoTtdCZaf:-My7SKUlCouvoTtdCZag:bf03mze) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/rowfetcher_cache.go#L211)):*
> ```Go
> 			f.skip = true
> 			return rf, ErrUnwatchedFamily
> 		}
> ```

we don't have separate rfCache tests, do we? Would be nice to add targeted tests for this.
___
*[pkg/sql/parser/sql.y, line 3908 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7NZ48BHQdphQPJsb1:-My7NZ48BHQdphQPJsb2:b4la3x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/sql/parser/sql.y#L3908)):*
> ```Yacc
>   }
> |
>   TABLE table_name FAMILY family_name
> ```

I see why we need TABLE when altering.
Can some sort of opt_table production rule to make TABLE optional be added?
___
*[pkg/sql/parser/testdata/alter_changefeed, line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7NIGq3exK9cUBDhGi:-My7NIGq3exK9cUBDhGj:b-opuo6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/sql/parser/testdata/alter_changefeed#L4)):*
> ```
> ALTER CHANGEFEED 123 ADD foo
> ----
> ALTER CHANGEFEED 123 ADD TABLE foo -- normalized!
> ```

do we now require TABLE keyword?
___
*[pkg/ccl/changefeedccl/alter_changefeed_test.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7PyTR95T1myvEa8ll:-My7PyTR95T1myvEa8lm:bz9w9sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/alter_changefeed_test.go#L146)):*
> ```Go
> 		sqlDB.Exec(t, `CREATE TABLE foo (a INT PRIMARY KEY, b STRING, FAMILY onlya (a), FAMILY onlyb (b))`)
> 
> 		testFeed := feed(t, f, `CREATE CHANGEFEED FOR foo FAMILY onlya, foo FAMILY onlyb`)
> ```

I'm still confused what happens when you create a feed on multi-family table, w/out specifying family?
Do we watch all familes? (I think so).  Anyway, would be nice to create such a feed where you don't specify
families, but then attempt to drop.


<!-- Sent from Reviewable.io -->

2022-03-14 14:52 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77640)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @sherman-grewal)

___
*[pkg/ccl/changefeedccl/alter_changefeed_stmt.go, line 145 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-Mxph_WYfM4j94sO32b--r3-145:-My7oO9qB-w5RMvk0IL9:bii46ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/alter_changefeed_stmt.go#L145)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: wrap? here and throughout?
</blockquote></details>

Done throughout, except I'm leaving one long string literal as-is.
___
*[pkg/ccl/changefeedccl/changefeed_dist.go, line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7MnJw9yzgtEnY8kZR:-My7oWwy0AjrKoBq_VvQ:beoy1n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/changefeed_dist.go#L139)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

curious: deadlock where?
</blockquote></details>

I am curious about this too! I think it's in kvfeed but I haven't nailed it down yet.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 723 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7MztwBg6zVoU112IJ:-My7ovWN1mTH69fyrJZr:bc3sdzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/changefeed_processors.go#L723)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

is that how it works? 1 event for each family even if you're not watching some?
</blockquote></details>

Yeah. There might be a way to move this filtering further up the stack but my tentative guess is that this is the most efficient place since it means we only have to parse the key once.
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 583 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7RB8Z7xHguCJfNkzZ:-My7ph3uCloQe5G8uDvS:b-k0cx1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/changefeed_stmt.go#L583)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Can we do that instead of TODO? Is it too much for this PR?
</blockquote></details>

It feels like one package too many for this PR that I'm trying to squeeze in at the last minute. It'll be a quick follow-up though if that's okay.
___
*[pkg/ccl/changefeedccl/encoder.go, line 194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7RvCXAl0Z4x8493Y3:-My7tVVa8pyPYtSkt2wi:bqfk0w9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/encoder.go#L194)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we need to memoize?
</blockquote></details>

We probably should, but we weren't before and there's some complexity there since we don't want an unbounded in-memory cache in the case where new families are continually added to a whole table feed. Added a TODO.
___
*[pkg/ccl/changefeedccl/rowfetcher_cache.go, line 211 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7SKUlCouvoTtdCZaf:-My7qy8F0gDMs5L1IvIn:b3q8o1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/rowfetcher_cache.go#L211)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we don't have separate rfCache tests, do we? Would be nice to add targeted tests for this.
</blockquote></details>

Maybe leave it for a stability PR to add an rfCache test file? We are exercising this filtering in tests.
___
*[pkg/sql/parser/sql.y, line 3908 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7NZ48BHQdphQPJsb1:-My7rEYZBmOVh_9Q6IWQ:bytmy0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/sql/parser/sql.y#L3908)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I see why we need TABLE when altering.
Can some sort of opt_table production rule to make TABLE optional be added?
</blockquote></details>

It's still optional here. The parsing change I've introduced here for both create and alter is that you can now also use it in the middle of the list. Before you could do `FOR TABLE foo, bar` or `FOR foo, bar`, but you couldn't do `FOR TABLE foo, TABLE bar`. Now it's optional at the start of every target clause, not just the first.
___
*[pkg/sql/parser/testdata/alter_changefeed, line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7NIGq3exK9cUBDhGi:-My7sRrG-ZaGK5yLXOnW:bnm1jdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/sql/parser/testdata/alter_changefeed#L4)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we now require TABLE keyword?
</blockquote></details>

No, it's still optional.
___
*[pkg/ccl/changefeedccl/alter_changefeed_test.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-My7PyTR95T1myvEa8ll:-My7sbID5nWJ7bCdLoj4:b-xwz6q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8de7b3cef741d68ced39365a74e6d652dd4c2d/pkg/ccl/changefeedccl/alter_changefeed_test.go#L146)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm still confused what happens when you create a feed on multi-family table, w/out specifying family?
Do we watch all familes? (I think so).  Anyway, would be nice to create such a feed where you don't specify
families, but then attempt to drop.
</blockquote></details>

We watch each family, but it's different from creating a target on each individual family--you wouldn't be able to do what you're describing as-is. Could be a bit of syntactic sugar to add in the future though.


<!-- Sent from Reviewable.io -->

2022-03-15 23:02 UTC, HonoreDB commented
Ready for re-review after merging in the alter changefeed updates.

2022-03-16 13:29 UTC, miretskiy approved these changes
> Reviewed 1 of 3 files at r4, 7 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77640)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @HonoreDB, @miretskiy, and @sherman-grewal)

___
*[-- commits, line 5 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-MyHsI_170UgM6MpKHUw):*
needs to be expanded? release justification, release note, etc?


<!-- Sent from Reviewable.io -->

2022-03-16 14:01 UTC, sherman-grewal approved these changes
> Reviewed 8 of 16 files at r3, 1 of 3 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77640)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @HonoreDB, and @miretskiy)



<!-- Sent from Reviewable.io -->

2022-03-16 16:12 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77640)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[-- commits, line 5 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77640#-MyHsI_170UgM6MpKHUw):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

needs to be expanded? release justification, release note, etc?
</blockquote></details>

Those are there at the end of the commit, reviewable's just hiding them. Unless you mean you think they need to be expanded.


<!-- Sent from Reviewable.io -->

2022-03-16 18:26 UTC, merged