ui: change sql box height for Statement Details
cockroachdb/cockroach pull request #77713
Opened 2022-03-12 02:06 UTC by maryliag

Change the height of SQL Box on Statement Details,
with the query box smaller (200px) and the Explain Plan
larger (400px);

Release justification: low risk change
Release note: None

<img width="1584" alt="Screen Shot 2022-03-11 at 9 05 08 PM" src="https://user-images.githubusercontent.com/1017486/157999646-b7824634-d030-4aee-b826-75dd03e1037d.png">

2022-03-12 02:07 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/77713)
<!-- Reviewable:end -->

2022-03-14 14:14 UTC, matthewtodd requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77713#-My7l9uECcvqAgVEM4Od:-My7l9uF80KGLbthIbX5:b1jd4n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f2ddc06ca2c56b35f42cac31327d645ed9b4fb2/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L544)):*
> ```XML
>           <Row gutter={24}>
>             <Col className="gutter-row" span={24}>
>               <SqlBox value={formatted_query} className={"small"} />
> ```

I'm a little worried about using these global names without passing through the `classnames.bind` mechanism. AFAICT, these 2 components don't even import the `sqlhighlight` styles directly, so they're counting on them being globally available?

Alternatively, would it be worth building something like `<SqlBox ... size={"small"} />`?


<!-- Sent from Reviewable.io -->

2022-03-14 15:44 UTC, Annebirzin approved these changes
LGTM, thank you!

2022-03-14 15:50 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77713#-My7l9uECcvqAgVEM4Od:-My87-NRAdJdUHvxMubI:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f2ddc06ca2c56b35f42cac31327d645ed9b4fb2/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L544)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I'm a little worried about using these global names without passing through the `classnames.bind` mechanism. AFAICT, these 2 components don't even import the `sqlhighlight` styles directly, so they're counting on them being globally available?

Alternatively, would it be worth building something like `<SqlBox ... size={"small"} />`?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-03-14 15:52 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77713#-:-My87PdKEhidhJ_f_P2k:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77713#-My7l9uECcvqAgVEM4Od:-My87N4j9_gx_hT8Ox_d:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f2ddc06ca2c56b35f42cac31327d645ed9b4fb2/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L544)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2022-03-14 18:03 UTC, maryliag commented
bors r+

2022-03-14 21:58 UTC, merged