concurrency: refactor the ContentionEventTracer to avoid deadlock
cockroachdb/cockroach pull request #77853
Opened 2022-03-15 19:02 UTC by andreimatei

The recently introduced ContentionEventTracer theoretically permits
deadlocks occur, as discovered by the deadlock detector. This was
because the ContentionEventTracer holds its lock while calling into
the tracing Span (which takes the Span's lock) for emitting trace
events. But, if one collects the Span's recording, the Span also calls
into the ContentionEventTracer.Render, as the ContentionEventTracer is
registered as a span (lazy) tag.

This patch fixes this potential deadlock by restructuring the
ContentionEventTracer. Instead of the ContentionEventTracer acting as a
tracing tag directly, a new tag struct is introduced. The new struct
doesn't call into the span.

Because the span is no longer linked to a ContentionEventTracer, this
patch also lifts up the creation of the ContentionEventTracer. Before,
the CET was created under the lockTableWaiter, which checked to see if
the Span has a CET and, if not, creates one. The lockTableWaiter could
be called into several times for a request, and it was basically using
the Span as "thread-local storage" to remember this anicilarrry state
across calls. In retrospect, that was not nice to begin with, and
maintaining it would make it even uglier now.
This patch lifts the creation of the CET to the replica's request
evaluation, which is the proper scope.

This patch also mucks with the datadriven concurrency manager tests.
These tests were using a particular testing hook to brutally override
a timing-dependent duration in contention events in order to make the
test output deterministic. This patch switches to getting determinism
from the lockTable's manual clock. This is one less knob to use;
additionally, the deterministic test output was sometimes non-sensical
(requests with the no-wait policy appearing to have waited for some
duration on a lock). The test was already using a manual clock for some
things, but not for the lock table. This change caused the diffs to the
datadriven tests; for some of the tests, I went to the trouble of
advancing the clock here and there in order to demonstrate that the
contention events have the right duration in them. In other tests, I've
more simply re-written them to expect a zero duration.
In the process, I've made timeutil.ManualTime a bit more ergonomic, and
added a deprecation notice to hlc.ManualClock - timeutil.ManualTime
should now be strictly better.

Release note: None

Fixes https://github.com/cockroachdb/cockroach/issues/77812
Fixes https://github.com/cockroachdb/cockroach/issues/77816
Fixes https://github.com/cockroachdb/cockroach/issues/77817
Fixes https://github.com/cockroachdb/cockroach/issues/77818
Fixes https://github.com/cockroachdb/cockroach/issues/77819
Fixes https://github.com/cockroachdb/cockroach/issues/77820
Fixes https://github.com/cockroachdb/cockroach/issues/77821
Fixes https://github.com/cockroachdb/cockroach/issues/77822
Fixed https://github.com/cockroachdb/cockroach/issues/77826
Fixed https://github.com/cockroachdb/cockroach/issues/77827

2022-03-15 19:02 UTC, andreimatei commented
@ajwerner I'm curious if you have any opinions on the first commit.

2022-03-15 20:55 UTC, ajwerner commented
Does something use the timesource to control time anywhere? I didn't see any uses of advance.

In general, I think that thing is pretty sound good. It can be somewhat painful to wait for all the timers you might expect. In the past that has lead to racy tests whereby you think the goroutines are fully synchronized with the clock by the time you advance it, but then find out they aren't under stress later.

2022-03-15 22:30 UTC, andreimatei reviewed
I mostly wanted to see if you objected to the store having both a `hlc.Clock` and a `timeutil.TimeSource`. As discussed offline, we'll leave both of them, at least for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-:-MyENlYVERbm5TN9237r:bjjki5c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-03-15 23:09 UTC, nvanbenschoten requested changes
> Reviewed 5 of 5 files at r1, 4 of 6 files at r3, 23 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/kv/kvserver/replica_send.go, line 453 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEl86QDHZ3YwjytdAs:-MyEl86QDHZ3YwjytdAt:b-paogcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/kv/kvserver/replica_send.go#L453)):*
> ```Go
> 			LatchSpans:      latchSpans, // nil if g != nil
> 			LockSpans:       lockSpans,  // nil if g != nil
> 		}, requestEvalKind, contentionTracer)
> ```

If this isn't changing across a Request, let's add it to the `concurrency.Request` struct. That also avoids the interface changes.
___
*[pkg/kv/kvserver/store.go, line 968 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEk0hwDFJXN8lfhy0F:-MyEk0hwDFJXN8lfhy0G:bir22wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/6750e5e4be981c4a5c7db43de8e41029e63cbfd6/pkg/kv/kvserver/store.go#L968)):*
> ```Go
> 	Settings             *cluster.Settings
> 	Clock                *hlc.Clock
> 	TimeSource           timeutil.TimeSource
> ```

Do you think it's odd to have a TimeSource passed around right next to an `hlc.Clock`? Why aren't we using the clock's physical time directly? We have plenty of ways to mock an HLC.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 869 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEm-v_7saiJJfUx-oL:-MyEm-v_7saiJJfUx-oM:b-mijrjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L869)):*
> ```Go
> const tagWaited = "lock_wait"
> 
> // ContentionEventTracer adds lock contention information to the trace, in the
> ```

Let's move this all into a separate file if it's now a stand-alone part of the package's API.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 923 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEn5GI-DdUo5ptv4og:-MyEn5GI-DdUo5ptv4oh:b-jy2ek7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L923)):*
> ```Go
> 	t := &ContentionEventTracer{}
> 	t.tag.clock = clock
> 	sp.SetLazyTag(tagContentionTracer, &t.tag)
> ```

Do you like that we now do this even when the request hits no contention?
___
*[pkg/util/hlc/hlc.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEnpnL5K7Y11PfXW8P:-MyEnpnM0J5KdAKmEdmB:b3mazcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/util/hlc/hlc.go#L96)):*
> ```Go
> // is manually controlled. ManualClock is thread safe.
> //
> // NOTE: ManualClock is deprecated. Use timeutil.ManualTime instead.
> ```

Let's keep this out of this change. If we want to deprecate ManualClock, we should do more than just say this is deprecated. That leads to confusion down the line when people who had nothing to do with this see that something is deprecated but then don't see any code respecting that deprecation nor any example of what to do instead.
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/uncertainty, line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEoicw8RCmCSL6-pnU:-MyEoicw8RCmCSL6-pnV:bbxg8jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/uncertainty#L44)):*
> ```
> [3] sequence req1: waiting in lock wait-queues
> [3] sequence req1: lock wait-queue event: wait for (distinguished) txn 00000001 holding lock @ key "k" (queuedWriters: 0, queuedReaders: 1)
> [3] sequence req1: pushing timestamp of txn 00000001 above 12.000000000,1
> ```

What happened here?
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter_test.go, line 598 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEp16W2TGjP7nrUKPP:-MyEp16X33YRMilqnYNO:blapyu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/kv/kvserver/concurrency/lock_table_waiter_test.go#L598)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	defer log.Scope(t).Close(t)
> 	tr := tracing.NewTracer()
> ```

Can we make things not break when a user doesn't provide a tracer and then remove this? It's a shame to see the same kind of boilerplate that makes tests in `pkg/kv/kvserver` such a pain to write start creeping into targeted packages.


<!-- Sent from Reviewable.io -->

2022-03-15 23:14 UTC, nvanbenschoten reviewed
> I mostly wanted to see if you objected to the store having both a hlc.Clock and a timeutil.TimeSource

I left a comment about this below — I think we should try to avoid this. It's confusing to see multiple clocks and not know how they relate. I'm on board with making `hlc.Clock` interop with `timeutil.TimeSource` better, but they shouldn't both be passed as dependencies to different components. The quickest way to walk back this fracture is probably to replace `timeutil.TimeSource` with `hlc.Clock` in `lockTable` (which only learned about time a few days ago).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-:-MyEq2wwCYNIbUNbpqQY:bp1pek4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)



<!-- Sent from Reviewable.io -->

2022-03-16 22:18 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 869 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEm-v_7saiJJfUx-oL:-MyJBFqRCAIyDwdjGL5N:bgy6oqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L869)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's move this all into a separate file if it's now a stand-alone part of the package's API.
</blockquote></details>

no longer part of the API
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 923 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEn5GI-DdUo5ptv4og:-MyIo9968kNNYgLlBI3O:bs9hsmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L923)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you like that we now do this even when the request hits no contention?
</blockquote></details>

reverted to only attaching this tag when contention is encountered.
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/uncertainty, line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEoicw8RCmCSL6-pnU:-MyJAAHB-2wyi5SsfKbH:bzbqtaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/uncertainty#L44)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What happened here?
</blockquote></details>

it had to do with the fact that the current timestamp of the clock had changed from a high one to 12. Reverted now.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter_test.go, line 598 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEp16W2TGjP7nrUKPP:-MyIgD1w9sqUZU9QZBo1:b2ni76j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/kv/kvserver/concurrency/lock_table_waiter_test.go#L598)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we make things not break when a user doesn't provide a tracer and then remove this? It's a shame to see the same kind of boilerplate that makes tests in `pkg/kv/kvserver` such a pain to write start creeping into targeted packages.
</blockquote></details>

n/a
___
*[pkg/kv/kvserver/replica_send.go, line 453 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEl86QDHZ3YwjytdAs:-MyJluvq4KePudo-pCpM:b-19q51e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/kv/kvserver/replica_send.go#L453)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If this isn't changing across a Request, let's add it to the `concurrency.Request` struct. That also avoids the interface changes.
</blockquote></details>

as discussed, reversed to creating the tracer inside the lock table
___
*[pkg/kv/kvserver/store.go, line 968 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEk0hwDFJXN8lfhy0F:-MyInovfCFeuUZ9SdCCt:b-q04hm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6750e5e4be981c4a5c7db43de8e41029e63cbfd6/pkg/kv/kvserver/store.go#L968)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think it's odd to have a TimeSource passed around right next to an `hlc.Clock`? Why aren't we using the clock's physical time directly? We have plenty of ways to mock an HLC.
</blockquote></details>

ok, switched to a single clock. As discussed offline, I've switched the LockTable to use an hlc.Clock in the process.
___
*[pkg/util/hlc/hlc.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyEnpnL5K7Y11PfXW8P:-MyJA6-A9F3hfsSZYHtf:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b68c4aec977be793a11064a310a779096ea0fcbc/pkg/util/hlc/hlc.go#L96)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's keep this out of this change. If we want to deprecate ManualClock, we should do more than just say this is deprecated. That leads to confusion down the line when people who had nothing to do with this see that something is deprecated but then don't see any code respecting that deprecation nor any example of what to do instead.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-03-17 00:56 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 15 of 15 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-:-MyKMwycDhxf5VF53A_l:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 262 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyKLVx63v0dTmnHPEJE:-MyKLVx63v0dTmnHPEJF:b-zgl70a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cbaaaecd743adada69166216c455168d4345f84/pkg/kv/kvserver/concurrency/lock_table.go#L262)):*
> ```Go
> 	finalizedTxnCache txnCache
> 
> 	// timeProvider is used to track the lock hold and lock wait start times.
> ```

Maybe just keep this one sentence so that it's clear why we need a clock in here.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 146 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyKLhn2EQeKQ7Ir-20_:-MyKLhn2EQeKQ7Ir-20a:b-891j4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5200644dea7878be0046646754e55da8e0287519/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L146)):*
> ```Go
> 	var lockDeadline time.Time
> 
> 	// Make sure we clean up the tracing when exiting the function.
> ```

nit: Say a bit more about what this is doing, now that it's more than just the defer.

Also, maybe just `s/contentionTracer/tracer/`
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter_test.go, line 769 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyKMim11ogAIeLoSmi_:-MyKMim11ogAIeLoSmia:byquu61) ([raw file](https://github.com/cockroachdb/cockroach/blob/5200644dea7878be0046646754e55da8e0287519/pkg/kv/kvserver/concurrency/lock_table_waiter_test.go#L769)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	defer log.Scope(t).Close(t)
> 	tr := tracing.NewTracer()
> ```

Do we need this?


<!-- Sent from Reviewable.io -->

2022-03-17 01:46 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77853)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 262 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyKLVx63v0dTmnHPEJE:-MyKWKrUBo3BldFSsMVC:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cbaaaecd743adada69166216c455168d4345f84/pkg/kv/kvserver/concurrency/lock_table.go#L262)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Maybe just keep this one sentence so that it's clear why we need a clock in here.
</blockquote></details>

done
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 146 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyKLhn2EQeKQ7Ir-20_:-MyKWjIZ5k9F5RBjMyns:b-gq6lss) ([raw file](https://github.com/cockroachdb/cockroach/blob/5200644dea7878be0046646754e55da8e0287519/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L146)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Say a bit more about what this is doing, now that it's more than just the defer.

Also, maybe just `s/contentionTracer/tracer/`
</blockquote></details>

done and done
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter_test.go, line 769 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-MyKMim11ogAIeLoSmi_:-MyKYKN59l0z3g0p0g8B:bogcyhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5200644dea7878be0046646754e55da8e0287519/pkg/kv/kvserver/concurrency/lock_table_waiter_test.go#L769)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

no, removed


<!-- Sent from Reviewable.io -->

2022-03-17 01:47 UTC, nvanbenschoten approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77853)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2022-03-17 01:54 UTC, andreimatei reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77853#-:-MyK_Kys4o46hGksN1sK:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2022-03-17 03:29 UTC, yuzefovich commented
This will be backported to 22.1, right? #77933 on 22.1 failed seemingly because of this issue:
```
=== RUN   TestBytesRead
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/39e1bb6cf6bde42cfeeb18f3d8b47a85/logTestBytesRead3305764215
    test_log_scope.go:80: use -show-logs to present logs inline
POTENTIAL DEADLOCK: Inconsistent locking. saw this ordering in one goroutine:
happened before
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_waiter.go:1020 concurrency.(*contentionEventTracer).notify ??? <<<<<
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_waiter.go:1019 concurrency.(*contentionEventTracer).notify ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock_table_waiter.go:164 concurrency.(*lockTableWaiterImpl).WaitOn ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/concurrency_manager.go:315 concurrency.(*managerImpl).sequenceReqWithGuard ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/concurrency_manager.go:215 concurrency.(*managerImpl).SequenceReq ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:440 kvserver.(*Replica).executeBatchWithConcurrencyRetries ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:169 kvserver.(*Replica).sendWithoutRangeID ???
...
```

2022-03-17 03:38 UTC, andreimatei commented
> This will be backported to 22.1, right? https://github.com/cockroachdb/cockroach/issues/77933 on 22.1 failed seemingly because of this issue:

Yeah, I've merged the backport already. I'll take care of closing all the open issues.

Burging in; the previous bors build "hang", and I want to make it in before the next round of nighlies.

bors r+ p=99

2022-03-17 03:43 UTC, andreimatei commented
bors r+ p=99

2022-03-17 04:35 UTC, merged