opt: copy check constraint filter props when duplicating table
cockroachdb/cockroach pull request #77870
Opened 2022-03-15 23:59 UTC by msirek

This commit copies check constraint filter properties when
DuplicateTable is called, remapping ColumnIDs in ScalarProps and
reusing Spans so they don't have to be rebuilt.

For the following test case, runtime drops from appr. 310ms to 180ms:
```
CREATE TABLE t (i INT PRIMARY KEY USING HASH WITH BUCKET_COUNT = 256, j int);
INSERT INTO t SELECT g,g FROM generate_series(1, 1000000) g(g);
ANALYZE t;
EXPLAIN SELECT * FROM t WHERE i%2 != 0 ORDER BY i LIMIT 1 OFFSET 49;
```

Release justification: Performance improvement for ORDER BY queries
involving hash-sharded tables.

Release note: none

2022-03-15 23:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/77870)
<!-- Reviewable:end -->

2022-03-17 18:58 UTC, rytaft reviewed
Nice speedup! Looks like you've got some CI failures. I think you also need some more unit tests.

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-:-MyODpwb5mbOliDmQapz:bows1mv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[pkg/sql/opt/ordering.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyNzX-SEF2ZIjMzOIHP:-MyNzX-SEF2ZIjMzOIHQ:bphqkk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/ordering.go#L59)):*
> ```Go
> 
> // RemapColumnWithColMap remaps an OrderingColumn c according to a colMap.
> func (c OrderingColumn) RemapColumnWithColMap(colMap ColMap) OrderingColumn {
> ```

Should this be "MaybeRemapColumnWithColMap"? Since it only remaps it if it's found in `colMap`?
___
*[pkg/sql/opt/ordering.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyNzGqQ52qi5qbGR0k4:-MyNzGqUDHG5ZuUh7NQa:b-9uxfn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/ordering.go#L62)):*
> ```Go
> 	var dstCol int
> 	var remappedCol ColumnID
> 	var ok bool
> ```

nit: you don't need to declare `dstCol` and `ok` above the if block. Can just do `if dstCol, ok := ...`
___
*[pkg/sql/opt/constraint/columns.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyNzmBh0AGpEEo1o4PY:-MyNzmBh0AGpEEo1o4PZ:brq5ltj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/constraint/columns.go#L146)):*
> ```Go
> }
> 
> // RemapColumnsWithColMap remaps ordering columns in c according to a colMap.
> ```

Same comment -- should this say "maybe"?
___
*[pkg/sql/opt/constraint/spans.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyO-8GI2AyiTnGAoRCX:-MyO-8GI2AyiTnGAoRCY:b2iaybc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/constraint/spans.go#L20)):*
> ```Go
> )
> 
> var dummySpans = Spans{Span{}, nil, 0, false}
> ```

nit: I'd call this `emptySpans`
___
*[pkg/sql/opt/constraint/spans.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyO-EvnBqIF6CIeCd--:-MyO-Evo5SJKfORs5rjW:bzam1jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/constraint/spans.go#L161)):*
> ```Go
> }
> 
> // Equals indicates if two Spans are equals, given keyCtx describing the full
> ```

nit: are equals -> are equal
___
*[pkg/sql/opt/norm/general_funcs.go, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyODB4L4vLvQPt3t3Wv:-MyODB4M7OzQYXjPcAan:b988go1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/norm/general_funcs.go#L367)):*
> ```Go
> // function. The passed-in "condition" is assigned as-is to the new FiltersItem
> // and must already refer to the proper ColumnIDs. Spans in the Constraints of
> // fromFilter are shared an reused in the new FiltersItem. If fromFilter's Spans
> ```

nit: an -> and
___
*[pkg/sql/opt/norm/general_funcs.go, line 388 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyO-wBW3GNIhT7llpMw:-MyO-wBW3GNIhT7llpMx:b-xnjvcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/norm/general_funcs.go#L388)):*
> ```Go
> // Scalar.Rule.WithUses is not copied as it is lazily populated, so will get
> // filled in later.
> func copyScalarProps(toProps *props.Scalar, fromProps *props.Scalar, colMap opt.ColMap) {
> ```

How will we make sure that scalar props that get added in the future are included here?
___
*[pkg/sql/opt/props/func_dep.go, line 576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyO0Kio8GlHG24bMww0:-MyO0Kio8GlHG24bMww1:bwscrp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/props/func_dep.go#L576)):*
> ```Go
> func (f *FuncDepSet) CopyAndRemap(colMap opt.ColMap) FuncDepSet {
> 	newFuncDepSet := FuncDepSet{}
> 	newFuncDepSet.deps = make([]funcDep, 0, len(f.deps))
> ```

I don't think you want 0 for the length -- is this getting tested anywhere? This function and the two below should probably have unit tests
___
*[pkg/sql/opt/filters_test.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyOBgqKDkrZQY8pPANL:-MyOBgqKDkrZQY8pPANM:b-5r817j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/filters_test.go#L26)):*
> ```Go
> )
> 
> // TestDuplicateTableWithCheckConstraint tests that we can accurately duplicate the optimizer's
> ```

nit: comments should be <= 80 columns wide


<!-- Sent from Reviewable.io -->

2022-03-22 14:47 UTC, mgartner reviewed
> Reviewed 8 of 17 files at r1, 1 of 3 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77870)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[pkg/sql/opt/constraint/columns.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mylq7RL0Weo9jV5-OnV:-Mylq7RL0Weo9jV5-OnW:b-os8oym) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/constraint/columns.go#L146)):*
> ```Go
> }
> 
> // RemapColumnsWithColMap remaps ordering columns in c according to a colMap.
> ```

nit: Can you make it clear in the description that the original columns are not mutated, rather new columns are returned.
___
*[pkg/sql/opt/constraint/span.go, line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MylsALR4bQpu90ocEgg:-MylsALR4bQpu90ocEgh:b13ok3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/constraint/span.go#L393)):*
> ```Go
> 	end := endKey.Value(prefixLength - 1)
> 
> 	if keyCtx.Columns.Count() >= prefixLength && keyCtx.Columns.Get(prefixLength-1).Descending() {
> ```

I don't understand this change. If `prefixLength` is greater than the number of columns in `keyCtx`, can we actually count the keys? Shouldn't we `return 0, false`?
___
*[pkg/sql/opt/constraint/spans.go, line 180 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mylqs6kEs87xkh2ZJ4L:-Mylqs6kEs87xkh2ZJ4M:b-icvkk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/constraint/spans.go#L180)):*
> ```Go
> 		if thisSpan.endBoundary != thatSpan.endBoundary {
> 			return false
> 		}
> ```

nit: The boundary checks seem much less complex than the `Compare` check, so we might get a slight speedup in some cases by moving them before the Compare.

edit: I see now that this is only used for testing., so it won't make a difference. But it might be nice to do now anyway in case someone uses this function outside of testing in the future.
___
*[pkg/sql/opt/norm/general_funcs.go, line 388 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyO-wBW3GNIhT7llpMw:-MylvmjZAlauABLrR3gP:b3p9k4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/norm/general_funcs.go#L388)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

How will we make sure that scalar props that get added in the future are included here?
</blockquote></details>

I had the same concern about some of the `Equals` methods. At the least, we can add a warning to the definition of `props.Scalar` that this function should be updated if any new fields are added. 

We could add a unit test for this function, and at the top of if use reflection to list all the fields and their types (maybe combine into one long string or something) and compare that with some constant. If the fields ever change, the unit test would break and a carefully worded comment would make it obvious that the `copyScalarProps` function needs to be updated and unit-tested. It'd be kinda like automatically versioning the definition of `props.Scalar`. Here's an example of using reflection to get the names of struct fields: https://go.dev/play/p/Iq3Nyyefg2k

Also, can we make this function a method of `*props.Scalar`?
___
*[pkg/sql/opt/norm/general_funcs.go, line 319 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mym2-q3EaBtN9lYXUnv:-Mym2-q3EaBtN9lYXUnw:b-9jtcyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/norm/general_funcs.go#L319)):*
> ```Go
> 			// call to replaceFiltersExpr which only calls RemapCols on
> 			// FiltersItem.Condition and not the entire FiltersItem.
> 			return copyAndMapFiltersItem(t, colMap)
> ```

If we want to be sure that the copying is only done for check constraints, should we split `RemapCols` into separate functions - one to handle the general case and one to handle the DuplicateTable case?
___
*[pkg/sql/opt/props/func_dep.go, line 574 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyluP5E7lkQgpjBrJSY:-MyluP5FEX0h7B6VESGC:b-obbtnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/props/func_dep.go#L574)):*
> ```Go
> // CopyAndRemap copies f, remapping column IDs according to the colMap. Panics
> // if any ColumnIDs cannot be remapped.
> func (f *FuncDepSet) CopyAndRemap(colMap opt.ColMap) FuncDepSet {
> ```

nit: You named other functions that copy and remap just "Remap...", like the ones for Colset and OrderingColumn. Should this name be consistent?
___
*[pkg/sql/opt/props/logical.go, line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyltjWI5euu6_hyrMkw:-MyltjWI5euu6_hyrMkx:b-26mpkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/props/logical.go#L346)):*
> ```Go
> // Equals returns true if the shared properties in s are identical to those in
> // "other". The Rule.WithUses map is not compared, as it is lazily populated.
> func (s *Shared) Equals(other *Shared) bool {
> ```

Can you add a warning where `Shared` is defined that if new fields are added then `Shared.Equals` must be updated.
___
*[pkg/sql/opt/props/logical.go, line 364 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mylty5N01jb9S0z0i8_:-Mylty5N01jb9S0z0i8a:b8f2hle) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/props/logical.go#L364)):*
> ```Go
> // Equals returns true if the scalar properties in s are identical to those in
> // "other", including Shared properties.
> func (s *Scalar) Equals(other *Scalar, evalCtx *tree.EvalContext) bool {
> ```

Same comment as above - add warning `Scalar` comment to update this function if new fields are added.
___
*[pkg/sql/opt/filters_test.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mym4Xqv835g9PVJjQs0:-Mym4Xqv835g9PVJjQs1:b-q0v8n1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/filters_test.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package opt_test
> ```

nit:  `pkg/sql/opt/norm/general_funcs_test.go` might be a better place for this test
___
*[pkg/sql/opt/filters_test.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mym4FTR-2KC_vXZKljX:-Mym4FTR-2KC_vXZKljY:bq7utts) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/filters_test.go#L48)):*
> ```Go
> 
> 	tabMeta := md.TableMeta(a)
> 	builder.AddCheckConstraintsForTable(tabMeta)
> ```

nit: rather than exporting `AddCheckConstraintsForTable` you could manually construct the constraints and add them to the table metadata: `md.TableMeta(tab).Constraints = memo.FiltersExpr{...}`.
___
*[pkg/sql/opt/filters_test.go, line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mym5Doa803tsA3T05ou:-Mym5Doa803tsA3T05ov:bqgrwp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/filters_test.go#L95)):*
> ```Go
> 
> 	_, err := cat.ExecuteDDL(
> 		`CREATE TABLE a (i INT 
> ```

nit: remove trailing space


<!-- Sent from Reviewable.io -->

2022-03-22 14:48 UTC, mgartner commented
Brilliant idea!





<!-- Sent from Reviewable.io -->

2022-04-27 22:42 UTC, msirek reviewed
Thanks.  I had marked this as a draft PR, but I guess that's not so visible.  I'll use [DNM] or the do-not-merge label next time.
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-:-N0d_11O5txa7nEKa_VH:bm1p7dk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/ordering.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyNzX-SEF2ZIjMzOIHP:-N0aDaT3Eg9aMULfF_DB:b-5g17jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/ordering.go#L59)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Should this be "MaybeRemapColumnWithColMap"? Since it only remaps it if it's found in `colMap`?
</blockquote></details>

OK.  New new: `CopyAndMaybeRemapColumnWithColMap`
___
*[`pkg/sql/opt/ordering.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyNzGqQ52qi5qbGR0k4:-N0aDmdgBvZEFbLNKtWY:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/ordering.go#L62)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: you don't need to declare `dstCol` and `ok` above the if block. Can just do `if dstCol, ok := ...`
</blockquote></details>

Done



_Code quote:_
```Go
var remappedCol ColumnID
```
___
*[`pkg/sql/opt/constraint/columns.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyNzmBh0AGpEEo1o4PY:-N0aDr-H0d_IsovJnwEn:bd88pwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/constraint/columns.go#L146)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Same comment -- should this say "maybe"?
</blockquote></details>

New name: `CopyAndMaybeRemapColumnsWithColMap`



_Code quote:_
```Go
RemapColumnsWithColMap
```
___
*[`pkg/sql/opt/constraint/columns.go` line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mylq7RL0Weo9jV5-OnV:-N0aES5R4GWgtADHgmrV:b-896fjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/constraint/columns.go#L146)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Can you make it clear in the description that the original columns are not mutated, rather new columns are returned.
</blockquote></details>

Done
___
*[`pkg/sql/opt/constraint/span.go` line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MylsALR4bQpu90ocEgg:-N0aPjU481ZPGoRVIaGi:bubpkmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/constraint/span.go#L393)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't understand this change. If `prefixLength` is greater than the number of columns in `keyCtx`, can we actually count the keys? Shouldn't we `return 0, false`?
</blockquote></details>

True.  I was just trying to avoid accessing nonexistent key columns by adding a bounds check.  But if the caller is passing a prefixLength greater than the number of columns, we should definitely return `0, false`.  I don't recall the call stack that hit this, but it might have been at:
https://github.com/cockroachdb/cockroach/blob/e3de17a2c6923b28638dda6fc2d8cd899d254784/pkg/sql/opt/memo/statistics_builder.go#L3420-L3428
@rytaft Do you think this logic needs an update when the prefix matches the key length?  Is `updateDistinctCountsFromConstraint` doing the correct thing?

I have added the following at the beginning of `KeyCount()`:
```
	if prefixLength > keyCtx.Columns.Count() {
		// Unable to examine a column not defined by keyCtx.
		return 0, false
	}
```



_Code quote:_
```Go
if keyCtx.Columns.Count() >= prefixLength && keyCtx.Columns.Get(prefixLength-1).Descending() {
```
___
*[`pkg/sql/opt/constraint/spans.go` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyO-8GI2AyiTnGAoRCX:-N0aWGBj5BFZkb8Drx7D:b34uopr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/constraint/spans.go#L20)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: I'd call this `emptySpans`
</blockquote></details>

This has been removed.
___
*[`pkg/sql/opt/constraint/spans.go` line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyO-EvnBqIF6CIeCd--:-N0aWOTwEpoXUCwL9jgS:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/constraint/spans.go#L161)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: are equals -> are equal
</blockquote></details>

Fixed



_Code quote:_
```Go
Equals indicates if two Spans are equals,
```
___
*[`pkg/sql/opt/constraint/spans.go` line 180 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mylqs6kEs87xkh2ZJ4L:-N0aWjBA1NRAsvsDg8lQ:b3fozem) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/constraint/spans.go#L180)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: The boundary checks seem much less complex than the `Compare` check, so we might get a slight speedup in some cases by moving them before the Compare.

edit: I see now that this is only used for testing., so it won't make a difference. But it might be nice to do now anyway in case someone uses this function outside of testing in the future.
</blockquote></details>

Good point.  Modified as suggested.



_Code quote:_
```Go
set of key columns. The caller must check that the number of columns and
```
___
*[`pkg/sql/opt/norm/general_funcs.go` line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyODB4L4vLvQPt3t3Wv:-N0afDgj9UQtq_rYnmHK:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/norm/general_funcs.go#L367)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: an -> and
</blockquote></details>

Fixed



_Code quote:_
```Go
fromFilter are shared an reused in the new FiltersItem. If fromFilter
```
___
*[`pkg/sql/opt/norm/general_funcs.go` line 388 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyO-wBW3GNIhT7llpMw:-N0bqYjw293Rtj6f-JDF:br02gkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/norm/general_funcs.go#L388)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I had the same concern about some of the `Equals` methods. At the least, we can add a warning to the definition of `props.Scalar` that this function should be updated if any new fields are added. 

We could add a unit test for this function, and at the top of if use reflection to list all the fields and their types (maybe combine into one long string or something) and compare that with some constant. If the fields ever change, the unit test would break and a carefully worded comment would make it obvious that the `copyScalarProps` function needs to be updated and unit-tested. It'd be kinda like automatically versioning the definition of `props.Scalar`. Here's an example of using reflection to get the names of struct fields: https://go.dev/play/p/Iq3Nyyefg2k

Also, can we make this function a method of `*props.Scalar`?
</blockquote></details>

Made this a function of `*props.Scalar` and added the test `TestScalarPropsChanged`.
___
*[`pkg/sql/opt/norm/general_funcs.go` line 319 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mym2-q3EaBtN9lYXUnv:-N0ae80jBgcGCJXanBDa:b8rrkz6) ([raw file](ht [...]

2022-04-29 18:02 UTC, mgartner requested changes
I've left some more comments. I'm excited about the performance gains here! But it's certainly a scary change - any mistake in copying the scalar properties will likely lead to an invalid query plan.

From what I can tell, all the `Equals` methods added are for tests only - they aren't actually required for the non-testing code. Can they be implemented in just the test code/packages as functions instead of methods to discourage their use in non-testing code? I'm paranoid (perhaps unnecessarily) about us forgetting to keep them up-to-date as we add fields to structs. Although I'm also paranoid about keeping the CopyAndMap methods up-to-date with changes to their structs, so maybe my suggestion is moot.

> Reviewed 16 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-:-N0qSJ3C2NsXnE2XrdB7:b-hj1ieh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[`pkg/sql/opt/ordering.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyNzX-SEF2ZIjMzOIHP:-N0qPVN--1oE0cdyclqR:birc3d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/ordering.go#L59)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK.  New new: `CopyAndMaybeRemapColumnWithColMap`
</blockquote></details>

`WithColMap` might be unnecessary given that its an argument to the function that's not optional - the other remap functions with a colmap argument don't have the same suffix.
___
*[`pkg/sql/opt/ordering.go` line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qD6B0AlGlkLOfCMMX:-N0qD6B0AlGlkLOfCMMY:b-giju98) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/ordering.go#L62)):*
> ```Go
> func (c OrderingColumn) CopyAndMaybeRemapColumnWithColMap(colMap ColMap) OrderingColumn {
> 	var remappedCol ColumnID
> 	if dstCol, ok := colMap.Get(int(c.ID())); !ok {
> ```

nit: I think it's clearer to handle the positive `ok` case before the `!ok` case
___
*[`pkg/sql/opt/constraint/columns.go` line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qDvDzEYQ0YWVSlfq3:-N0qDvDzEYQ0YWVSlfq4:bnr9ubf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/constraint/columns.go#L149)):*
> ```Go
> // conditionally remaps them according to a colMap if they can be found in the
> // colMap. If a column is mapped, the original OrderingColumn is not mutated, a
> // new mapped OrderingColumn is built.
> ```

nit: isn't a new OrderingColumn always built, regardless of whether it is mapped to a new column ID or not?
___
*[`pkg/sql/opt/constraint/constraint_set.go` line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qEQdrErg2fMMdMKFQ:-N0qEQdrErg2fMMdMKFR:biu6j68) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/constraint/constraint_set.go#L103)):*
> ```Go
> 	if s == nil {
> 		return true
> 	}
> ```

nit: The check for `s == nil` doesn't look necessary, and the other methods here don't do the same, so can we remove it?
___
*[`pkg/sql/opt/constraint/constraint_set.go` line 391 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qFCx565-QrEdBf_kR:-N0qFCx565-QrEdBf_kS:b-rqullk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/constraint/constraint_set.go#L391)):*
> ```Go
> // a pointer to it. The first constraint is stored inline, and subsequent
> // constraints are stored in the otherConstraints slice.
> func (s *Set) AllocConstraint(capacity int) *Constraint {
> ```

nit: I think you can undo this change, I don't see this function used anywhere outside the package.
___
*[`pkg/sql/opt/norm/general_funcs.go` line 319 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-Mym2-q3EaBtN9lYXUnv:-N0qMlLb-FqF10AWYGF-:b-nmjqlj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/norm/general_funcs.go#L319)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

If `copyAndMapFiltersItem` is in general quicker, and more importantly reduces GC pressure by cutting back on unnecessary copying of Spans, it may be good to use it for other cases too. Also, using it in all cases would allow the code to get more testing exposure, and it is relatively early in the release cycle so it wouldn't be used by customers for a while.  What do you think?

```
make bench PKG=./pkg/sql/opt BENCHES=BenchmarkCopyConstructConstraints TESTFLAGS="-count=5 -benchmem"

BenchmarkCopyConstructConstraints/ConstructFilterTest-32            116305       8805 ns/op      2084 B/op         1 allocs/op
BenchmarkCopyConstructConstraints/ConstructFilterTest-32                 1 1013801202 ns/op  242480024 B/op   170003 allocs/op
BenchmarkCopyConstructConstraints/ConstructFilterTest-32                 4  253115503 ns/op  60620030 B/op     42501 allocs/op
BenchmarkCopyConstructConstraints/ConstructFilterTest-32                 2  502570580 ns/op  121240000 B/op    85000 allocs/op
BenchmarkCopyConstructConstraints/ConstructFilterTest-32                 5  201043131 ns/op  48496044 B/op     34001 allocs/op
BenchmarkCopyConstructConstraints/CopyConstructFilterTest-32      1000000000           0.1927 ns/op          0 B/op         0 allocs/op
BenchmarkCopyConstructConstraints/CopyConstructFilterTest-32      1000000000           0.1421 ns/op          0 B/op         0 allocs/op
BenchmarkCopyConstructConstraints/CopyConstructFilterTest-32      1000000000           0.1449 ns/op          0 B/op         0 allocs/op
BenchmarkCopyConstructConstraints/CopyConstructFilterTest-32      1000000000           0.1609 ns/op          0 B/op         0 allocs/op
BenchmarkCopyConstructConstraints/CopyConstructFilterTest-32      1000000000           0.1646 ns/op          0 B/op         0 allocs/op
```
</blockquote></details>

That makes sense. Looks like there's a handful of places where we pass `FiltersItem.Condition` to Remap that can be changed to pass the whole `FtilersItem`.

But something is wrong with the logic here. `copyAndMapFiltersItem` explicitly states that it does not change `FiltersItem.Condition`, so the columns in the filters item won't be remapped.

If you want to think about this case later, you can also remove it for now and address it in a follow-up.
___
*[`pkg/sql/opt/norm/general_funcs.go` line 294 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qHd8hDKuSFhkuWrBy:-N0qHd8i1OimRhNu-MLo:bsiyzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/norm/general_funcs.go#L294)):*
> ```Go
> // encountered in the input ScalarExpr that are not keys in colMap, they are not
> // remapped.
> func (c *CustomFuncs) RemapCols(scalar opt.ScalarExpr, colMap opt.ColMap) opt.ScalarExpr {
> ```

I just moved this to `norm/factory.go` so you'll have to rebase and move your changes there. Sorry!
___
*[`pkg/sql/opt/norm/general_funcs.go` line 330 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qO2aq3k6E7U63nxse:-N0qO2ar8L2BNOrGOWt7:bxmfurj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/norm/general_funcs.go#L330)):*
> ```Go
> // copyAndMapFiltersItem copies all elements of filter, except for Condition,
> // into a new FiltersItem, with any ColumnIDs and ColSets remapped using colMap.
> func copyAndMapFiltersItem(filter *memo.FiltersItem, colMap opt.ColMap) *memo.FiltersItem {
> ```

nit: this name sounds like the function should be mapping columns in Condition. Is there a better name to make it's purpose more clear?
___
*[`pkg/sql/opt/norm/general_funcs.go` line 337 at r4](https://r [...]

2022-05-03 19:55 UTC, rytaft reviewed
> Reviewed 1 of 7 files at r3, 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77870)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/constraint/span.go` line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MylsALR4bQpu90ocEgg:-N15m7qwByElUzSM0brn:b-bj3gi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/constraint/span.go#L393)):*
> @rytaft Do you think this logic needs an update when the prefix matches the key length?  Is updateDistinctCountsFromConstraint doing the correct thing?

I agree it looks a bit weird, but I do think it's doing the right thing. If the prefix matches the key length, all of the columns will be accounted for here: https://github.com/cockroachdb/cockroach/blob/928f605c3e84efb30cab213b47b2f4a66b816701/pkg/sql/opt/memo/statistics_builder.go#L3471-L3473

The code you highlighted will just cause the function to return on the next (non-existent) column.

I think your change to `KeyCount` is fine, but unnecessary, as the key length should always be less than or equal to the number of columns in the constraint.
___
*[`pkg/sql/opt/props/func_dep.go` line 576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyO0Kio8GlHG24bMww0:-N15okk04CVDSra0m7i6:b-c4neeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/props/func_dep.go#L576)):*
> Do you mean when f.deps is zero length to not call make? 

No, I mean that since you were allocating a slice of zero length, you would get array out of bounds errors below. New code looks good.
___
*[`pkg/sql/opt/props/logical.go` line 397 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N15pJyKEgInDbVKJNg7:-N15pJyKEgInDbVKJNg8:b-shcy86) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/props/logical.go#L397)):*
> ```Go
> // Scalar.Rule.WithUses is not copied as it is lazily populated, so will get
> // filled in later.
> func (s *Scalar) CopyScalarProps(fromProps *Scalar, colMap opt.ColMap) {
> ```

nit: I think calling this `CopyFrom` would be a bit more idiomatic
___
*[`pkg/sql/opt/memo/statistics_builder_test.go` line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N1ASrHT35Dwsi90o_38:-N1ASrHT35Dwsi90o_39:b-oy8yvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/memo/statistics_builder_test.go#L134)):*
> ```Go
> 	}
> 
> 	testConstraintSetCopyRemap := func(t *testing.T, set *constraint.Set, evalCtx *tree.EvalContext) {
> ```

Can you explain a bit about why you're testing this here? Is it just because this test has a variety of interesting constraints?

If so, I'd rather just duplicate the part of the test that's needed for testing this function and put it elsewhere.


<!-- Sent from Reviewable.io -->

2022-06-20 03:24 UTC, msirek reviewed
Thanks.  It sounds like you were on the fence about moving `Equals` to testing packages since CopyAndMap methods need to be kept up-to-date anyway. Has your opinion changed or become more definite since you last looked at this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-:-N4yvkff6tRaIm0oCHfm:b-fz6wid)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/ordering.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyNzX-SEF2ZIjMzOIHP:-N4xkQwz-pTZDBdUG9an:b-3p2v14) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/ordering.go#L59)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`WithColMap` might be unnecessary given that its an argument to the function that's not optional - the other remap functions with a colmap argument don't have the same suffix.
</blockquote></details>

Changed it to `CopyAndMaybeRemapColumn`.
___
*[`pkg/sql/opt/ordering.go` line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qD6B0AlGlkLOfCMMX:-N4xkbJP7NPkM5e-0xoP:bol96zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/ordering.go#L62)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I think it's clearer to handle the positive `ok` case before the `!ok` case
</blockquote></details>

Modified as suggested
___
*[`pkg/sql/opt/constraint/columns.go` line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qDvDzEYQ0YWVSlfq3:-N4xlD-v8lw--DU9WNKb:b-s1n8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/constraint/columns.go#L149)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: isn't a new OrderingColumn always built, regardless of whether it is mapped to a new column ID or not?
</blockquote></details>

Changed the last sentence to: "The original OrderingColumns are not mutated."



_Code quote:_
```Go
CopyAndMaybeRemapColumnsWithColMap copies ordering columns in c and
```
___
*[`pkg/sql/opt/constraint/constraint_set.go` line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qEQdrErg2fMMdMKFQ:-N4xoqmr1Na9CwVwglOY:brlf3dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/constraint/constraint_set.go#L103)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: The check for `s == nil` doesn't look necessary, and the other methods here don't do the same, so can we remove it?
</blockquote></details>

Removed it



_Code quote:_
```Go
Immutable() bool {
```
___
*[`pkg/sql/opt/constraint/constraint_set.go` line 391 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qFCx565-QrEdBf_kR:-N4xp8k25-eBCi2z_exD:b-jmpnhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/constraint/constraint_set.go#L391)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I think you can undo this change, I don't see this function used anywhere outside the package.
</blockquote></details>

undone



_Code quote:_
```Go
AllocConstraint allocates space for a new constraint in the set and returns
```
___
*[`pkg/sql/opt/constraint/span.go` line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MylsALR4bQpu90ocEgg:-N4xplmjCBDsgtclHuGg:b-qqie4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/constraint/span.go#L393)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> @rytaft Do you think this logic needs an update when the prefix matches the key length?  Is updateDistinctCountsFromConstraint doing the correct thing?

I agree it looks a bit weird, but I do think it's doing the right thing. If the prefix matches the key length, all of the columns will be accounted for here: https://github.com/cockroachdb/cockroach/blob/928f605c3e84efb30cab213b47b2f4a66b816701/pkg/sql/opt/memo/statistics_builder.go#L3471-L3473

The code you highlighted will just cause the function to return on the next (non-existent) column.

I think your change to `KeyCount` is fine, but unnecessary, as the key length should always be less than or equal to the number of columns in the constraint.

</blockquote></details>

OK, I think I actually added this due to a bug I encountered, but I wasn't able to track down the problem case.  Do you have a preference? Leave it in, or remove it to try and catch the test case?
___
*[`pkg/sql/opt/props/func_dep.go` line 576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MyO0Kio8GlHG24bMww0:-N4ycQMxAEReZzLe_2OG:brujztc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bed3f8bb662fbc7c5274d1145cc9f0f6ec7f7e9/pkg/sql/opt/props/func_dep.go#L576)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> Do you mean when f.deps is zero length to not call make? 

No, I mean that since you were allocating a slice of zero length, you would get array out of bounds errors below. New code looks good.

</blockquote></details>

OK, thanks.



_Code quote:_
```Go
func (f *FuncDepSet) CopyAndRemap(colMap opt.ColMap) FuncDepSet {
```
___
*[`pkg/sql/opt/props/logical.go` line 397 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N15pJyKEgInDbVKJNg7:-N4ycdqu1_w5HV_GsQuR:ba3o3s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/props/logical.go#L397)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: I think calling this `CopyFrom` would be a bit more idiomatic
</blockquote></details>

Renamed



_Code quote:_
```Go
CopyScalarProps(
```
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 470 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N0qPJC62Qj_OVdhma20:-N4yq1fc7ZXmIiyChDbM:bz7sn2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/constraint/constraint_set_test.go#L470)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is this meant to test the Equals function for the CopyAndMaybeRemapConstraintSetWithColMap function. I think testing both would be nice. In general, these data driven tests are easiest to understand when the `cases` show input and expected output an operation clearly. This test uses `cases` input, but to understand the transformations applied to the input and what the expected output is, you have to continue on to the logic below.
</blockquote></details>

Sorry, I copied `testCase` and forgot to remove the `expected` field.  It's unused.  I've added the comment:
```
// TestEqualsNegative tests that a copy of constraints made with function
// CopyAndMaybeRemapConstraintSetWithColMap, with no columns remapped, is
// identical to the original constraint, and that unsetting the `immutable` flag
// in the copy makes it unequal.
```

There's a separate test of `CopyAndMaybeRemapConstraintSetWithColMap` here:
https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/constraint/constraint_set_test.go#L22-L35
___
*[`pkg/sql/opt/memo/statistics_builder_test.go` line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N1ASrHT35Dwsi90o_38:-N4yv6bm-oVDD5RhUAUn:b-hfm8co) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5da1e0c4dab15f831c83101f912c282a73b67f/pkg/sql/opt/memo/statistics_builder_test.go#L134)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><bloc [...]

2022-06-27 14:02 UTC, mgartner requested changes
> Thanks.  It sounds like you were on the fence about moving Equals to testing packages since CopyAndMap methods need to be kept up-to-date anyway. Has your opinion changed or become more definite since you last looked at this?

Maybe we should use the trick [here](https://github.com/mgartner/cockroach/blob/6ff463b3c61a9a6ef79fc7b18ba0c1f2492e7b39/pkg/sql/opt/memo/interner_test.go#L380-L382) to write simple unit tests for Equals and Copy* that will fail to compile if a field is added to these structs. 

> Reviewed 1 of 19 files at r4, 15 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-:-N5_T0taEZIOZF7jPeoh:b-pnceog)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[`pkg/sql/opt/constraint/span.go` line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MylsALR4bQpu90ocEgg:-N5_IGtr6tNj9-Kze688:bahrv8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/constraint/span.go#L393)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, I think I actually added this due to a bug I encountered, but I wasn't able to track down the problem case.  Do you have a preference? Leave it in, or remove it to try and catch the test case?
</blockquote></details>

I couldn't find any obvious places where this function would be called with a bad prefix length. So I don't think it's, necessary, but I also don't see much harm in leaving it. If you do choose to leave it, can you add a note about this additional requirement in the function comment.
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 23 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_SRCz2oEnlOoSxn_P:-N5_SRCz2oEnlOoSxn_Q:b-khlouu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L23)):*
> ```Go
> )
> 
> func testConstraintSetCopyRemap(t *testing.T, set *Set, evalCtx *eval.Context) {
> ```

nit: I'd just move this logic into `TestConstraintSetCopyRemap` so the test is easier to follow and you only have to build the maps once. 
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 284 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_Oxnw9PnTeaEgI3A2:-N5_Oxnw9PnTeaEgI3A3:bncb9h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L284)):*
> ```Go
> 			cs = cs.Intersect(evalCtx, SingleConstraint(&constraint))
> 		}
> 		testConstraintSetCopyRemap(t, cs, evalCtx)
> ```

What is the need for testing copyremap in all these other tests? It seems like TestConstraintsSetCopyRemap is sufficient.
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 525 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_Q-Vh-7s6PgqslKx_:-N5_Q-Vi9jTxb3h3TRzI:b-rc97aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L525)):*
> ```Go
> 			[]string{
> 				`/1: [/10 - /10]`,
> 				`/1: [/8 - /8]`,
> ```

Wouldn't these two constraints be combined into a single constraint with multiple spans when built?
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 530 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_QUU6CVl1kbvjTpT3:-N5_QF3ACZ0tCzJtQdmZ:b-gyj6pw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L530)):*
> ```Go
> 		{
> 			[]string{
> 				`/1/2: [/10 - /10]`,
> ```

nit: I think `/1/2:` should be `/1:` 
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 559 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_QwgMA8zUwjSB6MkN:-N5_QwgMA8zUwjSB6MkO:bw3mfoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L559)):*
> ```Go
> 		spansCopy := Spans{}
> 		spansCopy.InitSingleSpan(spans.Get(0))
> 		spansCopy.Alloc(int(spans.numSpans))
> ```

Why call Alloc here with `spans.numSpans` and again below with `csRemapped.Length()`?

Also, I don't think you need to call `InitSingleSpan`, you can just `Alloc` and then `Append`. `Append` handles the case when the first span has not been set.
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 574 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_RPde0NKv1RCJGA8U:-N5_RPde0NKv1RCJGA8V:b-d04tha) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L574)):*
> ```Go
> 		// Now they should match since Equals checks if Spans are immutable.
> 		if !csRemapped.Equals(cs, evalCtx) || !cs.Equals(csRemapped, evalCtx) {
> 			t.Errorf("Constraint Sets expected to be unequal. cs: %v: csRemapped: %v", cs, csRemapped)
> ```

nit: `unequal` => `equal`


<!-- Sent from Reviewable.io -->

2022-07-01 21:54 UTC, msirek reviewed
Thanks, added `TestTrivialConstraintSetEquals` and `newFieldCompileCheck`.  The latter was not added as a test because `props.funcDep` is unexported so must be constructed in the `props` package.

I had to update `ColSet.CopyAndRemap` to `ColSet.CopyAndMaybeRemap`, so it doesn't panic when failing to remap (I hit a test case with a panic). The same is done with `FuncDepSet`. This is because we sometimes don't want to map all columns, as in this location:
https://github.com/cockroachdb/cockroach/blob/23042cac6f14922b007e23ecda82d6370c56d8bc/pkg/sql/opt/xform/join_funcs.go#L681

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-:-N5vUuLO75my8Pf9shJX:b3wll0z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/constraint/span.go` line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-MylsALR4bQpu90ocEgg:-N5v5dp_-E87KtfpIPZF:brknw0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f279abbe017260c6fa159d2852234a347bc8daa3/pkg/sql/opt/constraint/span.go#L393)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I couldn't find any obvious places where this function would be called with a bad prefix length. So I don't think it's, necessary, but I also don't see much harm in leaving it. If you do choose to leave it, can you add a note about this additional requirement in the function comment.
</blockquote></details>

Added prerequisite #2:
```
// is not possible. Requirements:
//   1. The given prefix length must be at least 1.
//   2. The given prefix length must not be greater than the number of key 
//      columns in keyCtx.
```
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 23 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_SRCz2oEnlOoSxn_P:-N5v6h-X4o1hKBt042Hr:b-pu6qbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L23)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I'd just move this logic into `TestConstraintSetCopyRemap` so the test is easier to follow and you only have to build the maps once. 
</blockquote></details>

Removed `testConstraintSetCopyRemap`
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 284 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_Oxnw9PnTeaEgI3A2:-N5v8Z1DD4nNcXuvpA1P:b-wavpur) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L284)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What is the need for testing copyremap in all these other tests? It seems like TestConstraintsSetCopyRemap is sufficient.
</blockquote></details>

Removed the other tests
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 525 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_Q-Vh-7s6PgqslKx_:-N5vAvbHAEssZ6X9xRAI:bc553nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L525)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Wouldn't these two constraints be combined into a single constraint with multiple spans when built?
</blockquote></details>

Yes, they do get combined.



_Code quote:_
```Go
{[]string{`/1/2: [/10/2 - /10/2]`}},
```
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 530 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_QUU6CVl1kbvjTpT3:-N5vBU9F2VJU4mcyq58_:b-j1bkwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L530)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I think `/1/2:` should be `/1:` 
</blockquote></details>

Modified as suggested.
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 559 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_QwgMA8zUwjSB6MkN:-N5vF5ZZ8pv2nuj03UCS:bol96zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L559)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why call Alloc here with `spans.numSpans` and again below with `csRemapped.Length()`?

Also, I don't think you need to call `InitSingleSpan`, you can just `Alloc` and then `Append`. `Append` handles the case when the first span has not been set.
</blockquote></details>

Modified as suggested



_Code quote:_
```Go
spansCopy.Alloc(int(spans.numSpans))
```
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 574 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N5_RPde0NKv1RCJGA8U:-N5vFEgqAS3RbLssde17:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1bcc6ea9d6f963bd61cbbe724d13569e659ba7/pkg/sql/opt/constraint/constraint_set_test.go#L574)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `unequal` => `equal`
</blockquote></details>

Fixed



_Code quote:_
```Go
Constraint Sets expected to be unequal
```


<!-- Sent from Reviewable.io -->

2022-07-18 21:57 UTC, rytaft reviewed
Sorry for missing this -- feel free to send a "friendly ping" next time!

> Reviewed 11 of 18 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-:-N7I8i1iAcoVW6iTJimy:b-w8p177)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[`pkg/sql/opt/colset.go` line 142 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N7Gwva-A_pAzlt-iOYy:-N7Gwva-A_pAzlt-iOYz:bf9o8j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/46bf2da1e2fd1cb2254d8582f2bca5c6e59ea794/pkg/sql/opt/colset.go#L142)):*
> ```Go
> 
> // CopyAndMaybeRemap looks up each ColumnID from s in the colMap. If present,
> // the mapped ColumnID is added a new ColSet, otherwise the unmapped ColumnID is
> ```

nit: added -> added to
___
*[`pkg/sql/opt/constraint/columns.go` line 149 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N7GxdaZ3TK04EQawYIq:-N7GxdaZ3TK04EQawYIr:bhc1udi) ([raw file](https://github.com/cockroachdb/cockroach/blob/46bf2da1e2fd1cb2254d8582f2bca5c6e59ea794/pkg/sql/opt/constraint/columns.go#L149)):*
> ```Go
> // conditionally remaps them according to a colMap if they can be found in the
> // colMap. The original OrderingColumns are not mutated.
> func (c *Columns) CopyAndMaybeRemapColumnsWithColMap(colMap opt.ColMap) Columns {
> ```

nit: since you removed "WithColMap" from the other function, maybe you could do that here too (i.e., call it "CopyAndMaybeRemapColumns")
___
*[`pkg/sql/opt/norm/factory.go` line 530 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N7IAC3D0DKj0shu1ykH:-N7IAC3D0DKj0shu1ykI:b-7ntfcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/46bf2da1e2fd1cb2254d8582f2bca5c6e59ea794/pkg/sql/opt/norm/factory.go#L530)):*
> ```Go
> 			// directly on a FiltersExpr or FiltersItem.
> 			//
> 			//, the FiltersExpr is handled by a
> ```

looks like this comment got messed up
___
*[`pkg/sql/opt/norm/factory.go` line 571 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N7IBb9h4MI60gOWYD8k:-N7IBb9h4MI60gOWYD8l:b1nxhe6) ([raw file](https://github.com/cockroachdb/cockroach/blob/46bf2da1e2fd1cb2254d8582f2bca5c6e59ea794/pkg/sql/opt/norm/factory.go#L571)):*
> ```Go
> 	// to change, otherwise construct a new FiltersItem from scratch.
> 	constraints := fromFilter.ScalarProps().Constraints
> 	if constraints != nil && !constraints.Immutable() {
> ```

How do you know that constraints is the only property that matters here? What about `FuncDeps` or the properties in `Shared`?
___
*[`pkg/sql/opt/norm/factory.go` line 578 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N7IBD0cDWODWFjJZlQi:-N7IBD0d1pw6WyVWwP1Q:b8i56ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/46bf2da1e2fd1cb2254d8582f2bca5c6e59ea794/pkg/sql/opt/norm/factory.go#L578)):*
> ```Go
> 	// Remap Column IDs in the Constraints and ScalarProps.
> 	item := replace(fromFilter).(*memo.FiltersItem)
> 	return item
> ```

Do you think it's possible to build any of this directly into the code generated by optgen? It feels like this is probably what we'd want to do for all scalar list expressions. You'd need to update this code:
https://github.com/cockroachdb/cockroach/blob/5ffe3c531385bbf52e5a414addbc489279f3d535/pkg/sql/opt/optgen/cmd/optgen/factory_gen.go#L264-L319
___
*[`pkg/sql/opt/props/logical.go` line 394 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N7IH4Bk0R2swraXofmA:-N7IH4Bk0R2swraXofmB:bc4x5g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/46bf2da1e2fd1cb2254d8582f2bca5c6e59ea794/pkg/sql/opt/props/logical.go#L394)):*
> ```Go
> 
> // CopyFrom copies all properties from fromProps into s, remapping any
> // ColumnIDs or ColSets using colMap. Panics if a column cannot be remapped.
> ```

Is this part about the panic still true?
___
*[`pkg/sql/opt/filters_test.go` line 163 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N7IGGgv2hb8I21sHeWp:-N7IGGgv2hb8I21sHeWq:b-c9y9yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/46bf2da1e2fd1cb2254d8582f2bca5c6e59ea794/pkg/sql/opt/filters_test.go#L163)):*
> ```Go
> 		}
> 		b.StopTimer()
> 	}
> ```

Are these apples-to-apples? Seems like this might not be a totally fair comparison (relational expression v. scalar expression).
___
*[`pkg/sql/opt/constraint/constraint_set_test.go` line 528 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77870#-N7IDpswE6Z5VwG3Nlrs:-N7IDpsxAKYTO4gGHQ8W:b-lofux4) ([raw file](https://github.com/cockroachdb/cockroach/blob/46bf2da1e2fd1cb2254d8582f2bca5c6e59ea794/pkg/sql/opt/constraint/constraint_set_test.go#L528)):*
> ```Go
> 
> // TestEqualsNegative tests that a copy of constraints made with function
> // CopyAndMaybeRemapConstraintSetWithColMap, with no columns remapped, is
> ```

Is this still the name of the function? Were you going to remove "WithColMap"?


<!-- Sent from Reviewable.io -->

2022-09-08 06:54 UTC, msirek commented
Note: try out the test case in https://github.com/cockroachdb/cockroach/issues/87552

2023-12-22 08:05 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=77870) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=77870) before we can accept your contribution.<br/><hr/>**Mark Sirek** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=77870) it.</sub>

2023-12-22 15:17 UTC, closed without merging