[WIP] sql,cli: implement \password cli command
cockroachdb/cockroach pull request #77975
Opened 2022-03-16 20:46 UTC by ZhouXing19

This commit is to add support for the `\password` that securely changes the
password for a user.

fixes https://github.com/cockroachdb/cockroach/issues/48543

Release note (sql,cli): implement \password cli command.

2022-03-16 20:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/77975)
<!-- Reviewable:end -->

2022-03-31 16:21 UTC, rafiss requested changes
nice tests! just had a comment about hashing

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-:-MzVlxs8EIIcnC5GYUAz:bimlj3u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzVka041TgrToZYCNcB:-MzVka041TgrToZYCNcC:b-6f5coe) ([raw file](https://github.com/cockroachdb/cockroach/blob/248293cee5cbc9034974445005d233bc70ba6f72/pkg/cli/clisqlshell/sql.go#L1194)):*
> ```Go
> 				`ALTER USER %s WITH LOGIN PASSWORD '%s'`,
> 				userName,
> 				stripANSIFromString(string(password1)))
> ```

if i understand the motivation of https://github.com/cockroachdb/cockroach/issues/48543 correctly, we want to avoid sending the password in cleartext here. now that https://github.com/cockroachdb/cockroach/pull/72579 is completed, the CLI can pre-hash the password and then send it in the ALTER USER command.

you can see the `compareWithCleartextPassword` functions in pkg/security/password.go to see the code for how to hash passwords. (the hashing code will need to be extracted to a separate function so it can be used here)

I think we want this `\password` command to use SCRAM. I'm not sure if it should be configurable. perhaps @knz has a thought here.


<!-- Sent from Reviewable.io -->

2022-03-31 16:22 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzVm0ty1SW4Z4qxBdjC):*
this should be "Release note (cli change)"

also, add more details about what the command actually does. (i.e. just say "the command lets the current user alter their password")

also, if we do pre-hashing as per my other comment, that should be added here


<!-- Sent from Reviewable.io -->

2022-04-01 19:15 UTC, knz reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzaY6mX-rt8qAbBTQsT:-MzaY6mX-rt8qAbBTQsU:bln5092) ([raw file](https://github.com/cockroachdb/cockroach/blob/248293cee5cbc9034974445005d233bc70ba6f72/pkg/cli/clisqlshell/sql.go#L1167)):*
> ```Go
> 		fmt.Fprintf(c.iCtx.stdout, "Enter new password: \n")
> 
> 		password1, err := term.ReadPassword(int(c.ins.Stdin().Fd()))
> ```

Please use `security.PromptForPassword()` here instead of rolling out your own logic.
___
*[pkg/cli/clisqlshell/sql.go, line 1194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzVka041TgrToZYCNcB:-MzaYDgDCLHg0mCA1Doi:b-88mdkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/248293cee5cbc9034974445005d233bc70ba6f72/pkg/cli/clisqlshell/sql.go#L1194)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

if i understand the motivation of https://github.com/cockroachdb/cockroach/issues/48543 correctly, we want to avoid sending the password in cleartext here. now that https://github.com/cockroachdb/cockroach/pull/72579 is completed, the CLI can pre-hash the password and then send it in the ALTER USER command.

you can see the `compareWithCleartextPassword` functions in pkg/security/password.go to see the code for how to hash passwords. (the hashing code will need to be extracted to a separate function so it can be used here)

I think we want this `\password` command to use SCRAM. I'm not sure if it should be configurable. perhaps @knz has a thought here.
</blockquote></details>

Agreed with Rafi. As-is, this logic will not improve the situation too much, because customers will still complain the password is visible in SQL logs.

Pre-hashing will be the right way to avoid that.
___
*[pkg/cli/clisqlshell/sql.go, line 2132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzaYON_8DeLz0xf6263:-MzaYONa4J_i4M72ozHA:be8q2fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/248293cee5cbc9034974445005d233bc70ba6f72/pkg/cli/clisqlshell/sql.go#L2132)):*
> ```Go
> }
> 
> // stripANSIFromString returns str with all ANSI escape sequences removed.
> ```

Why is this logic important? I don't understand why you added this. What problem is this supposed to solve?


<!-- Sent from Reviewable.io -->

2022-04-05 20:13 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzaY6mX-rt8qAbBTQsT:-MzvJhwkBPMMOqlJ1PaI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/248293cee5cbc9034974445005d233bc70ba6f72/pkg/cli/clisqlshell/sql.go#L1167)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please use `security.PromptForPassword()` here instead of rolling out your own logic.
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzVka041TgrToZYCNcB:-MzvJjD35saSr18NI4tr:b-toqltt) ([raw file](https://github.com/cockroachdb/cockroach/blob/248293cee5cbc9034974445005d233bc70ba6f72/pkg/cli/clisqlshell/sql.go#L1194)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Agreed with Rafi. As-is, this logic will not improve the situation too much, because customers will still complain the password is visible in SQL logs.

Pre-hashing will be the right way to avoid that.
</blockquote></details>

Added pre-hashing. Here I hard-coded the `cost` for hashing the cleartext with SCRAM. This is not ideal but I can't think of other better ways.
___
*[pkg/cli/clisqlshell/sql.go, line 2132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzaYON_8DeLz0xf6263:-MzvKkVb8K9nIAvyZxOy:bvh5h1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/248293cee5cbc9034974445005d233bc70ba6f72/pkg/cli/clisqlshell/sql.go#L2132)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why is this logic important? I don't understand why you added this. What problem is this supposed to solve?
</blockquote></details>

This is because when I try **copying and pasting** a password to the cli, ANSIF prefix and suffix are automatically added. 
E.g. the password I wanted to pass was 
```
SCRAM-SHA-256$119680:Hw/dhibRaBVbObr6bATlqw==$BTFlXuZT2ZNxA3DxogkGgK0wVlOyNtxGoqDI62hyLUo=:3eZMZdAossPInncABj7/N/jkGtRZEUrz7uGkkNibxxx=
```
But `fmt.Fprintf(c.iCtx.stdout, "password1:%#v\n", password1)`, I got 
```
password1:“\x1b[200~SCRAM-SHA-256$119680:Hw/dhibRaBVbObr6bATlqw==$BTFlXuZT2ZNxA3DxogkGgK0wVlOyNtxGoqDI62hyLUo=:3eZMZdAossPInncABj7/N/jkGtRZEUrz7uGkkNibxxx=\x1b[201~”
```
You can see that `\x1b[200~` and `\x1b[201~` are automatically added. 
I think copy and paste a pre-hashed password can be a common usage, and this `stripANSIFromString` is to deal with this edge case.


<!-- Sent from Reviewable.io -->

2022-04-05 21:51 UTC, knz reviewed
> Reviewed 1 of 4 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 2132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzaYON_8DeLz0xf6263:-MzvgiGY6cqKIa8gDBAJ:b-ygxmh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/248293cee5cbc9034974445005d233bc70ba6f72/pkg/cli/clisqlshell/sql.go#L2132)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

This is because when I try **copying and pasting** a password to the cli, ANSIF prefix and suffix are automatically added. 
E.g. the password I wanted to pass was 
```
SCRAM-SHA-256$119680:Hw/dhibRaBVbObr6bATlqw==$BTFlXuZT2ZNxA3DxogkGgK0wVlOyNtxGoqDI62hyLUo=:3eZMZdAossPInncABj7/N/jkGtRZEUrz7uGkkNibxxx=
```
But `fmt.Fprintf(c.iCtx.stdout, "password1:%#v\n", password1)`, I got 
```
password1:“\x1b[200~SCRAM-SHA-256$119680:Hw/dhibRaBVbObr6bATlqw==$BTFlXuZT2ZNxA3DxogkGgK0wVlOyNtxGoqDI62hyLUo=:3eZMZdAossPInncABj7/N/jkGtRZEUrz7uGkkNibxxx=\x1b[201~”
```
You can see that `\x1b[200~` and `\x1b[201~` are automatically added. 
I think copy and paste a pre-hashed password can be a common usage, and this `stripANSIFromString` is to deal with this edge case.
</blockquote></details>

You're solving the wrong problem, see https://en.wikipedia.org/wiki/XY_problem

The real problem is that `PromptForPassword()` runs in a terminal mode with paste delimiters enabled. Which is strange; it should not do this. This is what needs to be fixed.
(We have other uses of `PromptForPassword()` in other places. They are all equally affected. But we don't process the password string in these other places, why is that so?) 
___
*[pkg/cli/clisqlshell/sql.go, line 1208 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-Mzvg_cFB0NiADfo22pW:-Mzvg_cFB0NiADfo22pX:by2m0yx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1208)):*
> ```Go
> 			isPreHashed, _, _, _, _, err := security.CheckPasswordHashValidity(context.Background(), []byte(password1))
> 			if err != nil {
> 				fmt.Fprintf(c.iCtx.stderr, "Error checking password hash validity\n:%v", err)
> ```

nit: you can remove the word `error`. The fact it's an error is implied.
___
*[pkg/cli/clisqlshell/sql.go, line 1214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhNYn4Uq-o_HZvDXi:-MzvhNYn4Uq-o_HZvDXj:b74gq6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1214)):*
> ```Go
> 
> 			if !isPreHashed {
> 				if c.checkPrehashScramEnabled() {
> ```

Why do you need this? Which problem is this aiming to solve?
___
*[pkg/cli/clisqlshell/sql.go, line 1217 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-Mzvgel-12waoE7zUCks:-Mzvgel-12waoE7zUCkt:b-dtiqtw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1217)):*
> ```Go
> 					hashedPassword, err = security.HashPasswordUsingSCRAM(context.Background(), scramIterCount, password1)
> 					if err != nil {
> 						fmt.Fprintf(c.iCtx.stderr, "error hash password using scram\n:%v", err)
> ```

ditto, replace `hash` by `hashing`
___
*[pkg/cli/clisqlshell/sql.go, line 2175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhA5aABe20LowFz5V:-MzvhA5aABe20LowFz5W:bhp1bio) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L2175)):*
> ```Go
> // `store_client_pre_hashed_passwords_enabled` is set true.
> func (c *cliState) checkPrehashScramEnabled() bool {
> 	passwrodEncrptMethod, err := c.getSessionVarValue("password_encryption")
> ```

passwrod -> password 
___
*[pkg/security/password.go, line 433 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhU_KAgK6P6SGZsfo:-MzvhU_KAgK6P6SGZsfp:b-6zlytw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/security/password.go#L433)):*
> ```Go
> 
> // HashPasswordUsingSCRAM hashes the cleartext password with given cost with SCRAM.
> func HashPasswordUsingSCRAM(ctx context.Context, cost int, cleartext string) ([]byte, error) {
> ```

Why introducing a new function instead of exporting the function that's already there?


<!-- Sent from Reviewable.io -->

2022-04-05 21:55 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhNYn4Uq-o_HZvDXi:-Mzvhs4O7LZxrN7SvypO:bo35hsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1214)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why do you need this? Which problem is this aiming to solve?
</blockquote></details>

i believe the `if !isPrehashed` check i believe is needed because the user themselves may type in a pre-hashed password at the CLI prompt

and the `c.checkPrehashScramEnabled()` check is needed because we should not convert the plaintext into a hash unless the server supports pre-hashed passwords (and SCRAM) in the ALTER USER command.


<!-- Sent from Reviewable.io -->

2022-04-05 22:01 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhNYn4Uq-o_HZvDXi:-Mzvj2My4_uK88ixCKIR:b9ljqjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1214)):*
> the if !isPrehashed check i believe is needed because the user themselves may type in a pre-hashed password at the CLI prompt

Ok, this is *not* a realistic use case. Interactive password entry via `\password` must never be interpreted as pre-hashed. If a client already has a prehashed password, they will use ALTER USER WITH PASSWORD.

>  the c.checkPrehashScramEnabled() check is needed because we should not convert the plaintext into a hash unless the server supports pre-hashed passwords (and SCRAM) in the ALTER USER command.

Ok that sounds mildly more reasonable, but:

1) that check can be done just once when the session is opened instead of every time `\password` is invoked. We already store a couple of other server-side parameters. 

2) we only need to check whether SCRAM is enabled though. The "recognize pre-hashed passwords" is *enabled by default* and I think the CLI `\password` option should always assume it is enabled. If an operator disables it, that is non-standard deployment, and I don't think we care much that `\password` will "not work" in that case.


<!-- Sent from Reviewable.io -->

2022-04-05 22:05 UTC, ZhouXing19 commented
*[pkg/cli/clisqlshell/sql.go, line 1214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhNYn4Uq-o_HZvDXi:-MzvkWlhEOJQfZwT8qm-:bwglui6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1214)):*
> Interactive password entry via \password must never be interpreted as pre-hashed. If a client already has a prehashed password, they will use ALTER USER WITH PASSWORD.

Could you explain more on this one?


<!-- Sent from Reviewable.io -->

2022-04-05 22:06 UTC, knz commented
> Could you explain more on this one?

`\password` is a convenience function for *humans who want to enter a password that they have in their head*.

Humans do not hold password hashes in their head. They store plaintext passwords in their head. That's the input we're guaranteed to get at the prompt.

2022-04-05 22:34 UTC, ZhouXing19 commented
*[pkg/cli/clisqlshell/sql.go, line 1214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhNYn4Uq-o_HZvDXi:-MzvnuU3E6GxFVQOdXMo:bhs8cle) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1214)):*
> That's the input we're guaranteed to get at the prompt.
Thanks for explaining. I agree that `\password` is expecting plaintext, but just out of curiosity, since we have considered an edge case, why do we want to exclude that in our code? Is it just not to make the logic too complicated, or it's because checking if it's prehashed is expensive? I.e. why does it hurt if we keep `!isPrehashed`?

Similar question to your comments for the `c.checkPrehashScramEnabled()` check -- why do you think it's better to "assume" instead of "ensuring" that it's enabled?


<!-- Sent from Reviewable.io -->

2022-04-06 17:10 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhNYn4Uq-o_HZvDXi:-Mzzp8209SWiW1omnmNV:b-t9y9un) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1214)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

> That's the input we're guaranteed to get at the prompt.
Thanks for explaining. I agree that `\password` is expecting plaintext, but just out of curiosity, since we have considered an edge case, why do we want to exclude that in our code? Is it just not to make the logic too complicated, or it's because checking if it's prehashed is expensive? I.e. why does it hurt if we keep `!isPrehashed`?

Similar question to your comments for the `c.checkPrehashScramEnabled()` check -- why do you think it's better to "assume" instead of "ensuring" that it's enabled?
</blockquote></details>

Generally, I would recommend we don't introduce more complexity in this feature than what postgres itself does in `psql`. Have you checked what postgres does here?

You can look this up in `exec_command_password`, `src/bin/psql/command.c`
and see how it uses `PQencryptPasswordConn` defined in `src/interfaces/libpq/fe-auth.c`.

This codes _only_ uses `show password_encryption` to decide which algorithm to use and does not attempt to be clever about what the user enters.

I think we should not invest into doing more than what pg does.


<!-- Sent from Reviewable.io -->

2022-04-06 21:35 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[-- commits, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzVm0ty1SW4Z4qxBdjC):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this should be "Release note (cli change)"

also, add more details about what the command actually does. (i.e. just say "the command lets the current user alter their password")

also, if we do pre-hashing as per my other comment, that should be added here
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 2132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzaYON_8DeLz0xf6263:-N--mloWB0iIHu2Ef2Fd:bmydom0) ([raw file](https://github.com/cockroachdb/cockroach/blob/248293cee5cbc9034974445005d233bc70ba6f72/pkg/cli/clisqlshell/sql.go#L2132)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You're solving the wrong problem, see https://en.wikipedia.org/wiki/XY_problem

The real problem is that `PromptForPassword()` runs in a terminal mode with paste delimiters enabled. Which is strange; it should not do this. This is what needs to be fixed.
(We have other uses of `PromptForPassword()` in other places. They are all equally affected. But we don't process the password string in these other places, why is that so?) 
</blockquote></details>

We didn't process the password string in these other places I'll it as a todo in this PR.
___
*[pkg/cli/clisqlshell/sql.go, line 1208 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-Mzvg_cFB0NiADfo22pW:-N--mGt68bqlMxvHEmrM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1208)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: you can remove the word `error`. The fact it's an error is implied.
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhNYn4Uq-o_HZvDXi:-N--mI3W7Yzb2Vtb1BUd:b-srlarg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1214)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Generally, I would recommend we don't introduce more complexity in this feature than what postgres itself does in `psql`. Have you checked what postgres does here?

You can look this up in `exec_command_password`, `src/bin/psql/command.c`
and see how it uses `PQencryptPasswordConn` defined in `src/interfaces/libpq/fe-auth.c`.

This codes _only_ uses `show password_encryption` to decide which algorithm to use and does not attempt to be clever about what the user enters.

I think we should not invest into doing more than what pg does.
</blockquote></details>

Makes sense, change it to only check if the session variable `password_encryption` is set with `scram-sha-256`.
___
*[pkg/cli/clisqlshell/sql.go, line 1217 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-Mzvgel-12waoE7zUCks:-N--mUkBB1Vy-2IwACRY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1217)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto, replace `hash` by `hashing`
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 2175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhA5aABe20LowFz5V:-N--n-l694dmUooXxigR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L2175)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

passwrod -> password 
</blockquote></details>

Done.
___
*[pkg/security/password.go, line 433 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhU_KAgK6P6SGZsfo:-N--nJltBwavLYHYZm2V:bkbdcks) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/security/password.go#L433)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why introducing a new function instead of exporting the function that's already there?
</blockquote></details>

Changed it to export the original `hashPasswordUsingSCRAM`.


<!-- Sent from Reviewable.io -->

2022-04-07 15:46 UTC, knz reviewed
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhNYn4Uq-o_HZvDXi:-N-3f3qJ2lJ69KaHbEIG:b-13picl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1214)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Makes sense, change it to only check if the session variable `password_encryption` is set with `scram-sha-256`.
</blockquote></details>

I've thought a bit more about this and I think it's sad that the CLI only supports that one hash method when we have a framework to support more hash methods.

What about we try to generalize the structure of the function `security.HashPassword()` and use that here. The advantage of doing this is that you wouldn't need to hardcode the cost in the CLI code any more.

How to generalize?

Currently `security.HashPassword()` uses a cluster setting in `GetConfiguredPasswordHashMethod()` to decide which hash method to use. In the CLI code, we want to decide the method by running `SHOW password_encryption` on the server instead.

So we need a new variant of `security.HashPassword` which takes a HashMethod as argument.
Then the CLI code would look up the HashMethod using the string returned by `password_encryption`. (We need a new lookup function from string to HashMethod. This can be added to the security package by inverting the `map` in the definition of `security.PasswordHashMethod`).

Then pass the HashMethod to the new variant of `security.HashPassword`. The remainder of the function can remain as-is: it obtains the default costs from the cluster settings. (Even though CLI code doesn't enable customizing cluster settings, it can still *use* them and this will observe the default values, which is what we want here).
___
*[pkg/cli/clisqlshell/sql.go, line 1217 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-Mzvgel-12waoE7zUCks:-N-3elqpBhurLyPfO3xE:b9ztuxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1217)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

lowercase `hashing`.


<!-- Sent from Reviewable.io -->

2022-04-07 19:50 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhNYn4Uq-o_HZvDXi:-N-4Zk188WmDmlN7r0T8:b-i7yyps) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1214)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

> it obtains the default costs from the cluster settings. 

I'm a bit concerned about this because only users with the admin role are allowed to show cluster setting. Can we also add 2 session vars that save the default SCRAM and bcrypt cost?
</blockquote></details>

This is CLI code. There is no access to cluster settings whatsoever. The code in the existing function will attempt to "read cluster setting", *find there is no value configured* (this is CLI code and thus the infrastructure does not allow customization) and switch to use the default values.

Since our use case (in the CLI) wants us to choose default values, that's exactly what we want.


<!-- Sent from Reviewable.io -->

2022-04-11 14:45 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/cli/clisqlshell/sql.go, line 1214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-MzvhNYn4Uq-o_HZvDXi:-N-O4L2Z8eO0ooCmpiCh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1214)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is CLI code. There is no access to cluster settings whatsoever. The code in the existing function will attempt to "read cluster setting", *find there is no value configured* (this is CLI code and thus the infrastructure does not allow customization) and switch to use the default values.

Since our use case (in the CLI) wants us to choose default values, that's exactly what we want.
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1217 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-Mzvgel-12waoE7zUCks:-N-O4QmU6snIZhg2FJq4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35927e012d6dc2e723e004fa721d8e8febc5486/pkg/cli/clisqlshell/sql.go#L1217)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

lowercase `hashing`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-11 16:40 UTC, knz reviewed
ok this looks much nicer! 

> Reviewed 1 of 2 files at r5, 2 of 5 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-:-N-OUng784EslGmMMd65:b-xfg5lc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[-- commits, line 23 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OTaA3-s322joHw58W):*
`i.e.` -> `e.g.`
___
*[pkg/cli/clisqlshell/sql.go, line 1166 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OUD735b3TmY0FaXN0:-N-OUD735b3TmY0FaXN1:bl5rlve) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L1166)):*
> ```Go
> 		}
> 
> 	case `\password`:
> ```

maybe add `if passwordHashMethod == invalid { print("feature not supported"); return errstate }`
___
*[pkg/cli/clisqlshell/sql.go, line 1169 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OTedSCaYlkBvkQVjN:-N-OTedSCaYlkBvkQVjO:blvckpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L1169)):*
> ```Go
> 		password1, err := pprompt.PromptForPassword()
> 		if err != nil {
> 			fmt.Fprintf(c.iCtx.stderr, "reading password:%v\n", err)
> ```

nit: missing space between `:` and `%`
___
*[pkg/cli/clisqlshell/sql.go, line 1177 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OTgxjAUcUH0DjIObI:-N-OTgxjAUcUH0DjIObJ:b-lpczqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L1177)):*
> ```Go
> 		password2, err := pprompt.PromptForPassword()
> 		if err != nil {
> 			fmt.Fprintf(c.iCtx.stderr, "Reading password\n:%v", err)
> ```

ditto: `password: %v\n`
___
*[pkg/cli/clisqlshell/sql.go, line 1204 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OToldBobKePakkBXb:-N-OToldBobKePakkBXc:b-zhd9li) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L1204)):*
> ```Go
> 
> 			if err != nil {
> 				fmt.Fprintf(c.iCtx.stderr, "hashing password:%v\n", err)
> ```

nit: missing space `password: %v\n`
___
*[pkg/cli/clisqlshell/sql.go, line 1781 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OTvs2CsBhwD3tuD4Z:-N-OTvs2CsBhwD3tuD4_:b-efmrm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L1781)):*
> ```Go
> }
> 
> var passwordHashMethod security.HashMethod
> ```

please avoid introducing new global variables. Use `cliState` or `cliState.iCtx` instead.
___
*[pkg/cli/clisqlshell/sql.go, line 2157 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OU8VE-UhE6m6Ul6ra:-N-OU8VE-UhE6m6Ul6rb:b-w2rykd) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L2157)):*
> ```Go
> // to get the password hash method.
> func (c *cliState) getPasswordHashMethod() security.HashMethod {
> 	passwordEncrptMethod, err := c.getSessionVarValue("password_encryption")
> ```

nit: missing vowel in variable name
___
*[pkg/cli/clisqlshell/sql.go, line 2168 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OUTZ19te6iK3FJ0RV:-N-OUTZ19te6iK3FJ0RW:b-j0msgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L2168)):*
> ```Go
> 	}
> 
> 	switch passwordEncrptMethod {
> ```

please don't implement this `switch` in the cli packge, and instead place it in `security/password.go` alongside the method definitions. This will ensure that any changes to the `security` package will automatically propagate here.
___
*[pkg/cli/clisqlshell/sql.go, line 2171 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OUMTU7U21Ej5HAI6E:-N-OUMTU7U21Ej5HAI6F:b-la0onp) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L2171)):*
> ```Go
> 	case "<invalid>":
> 		return security.HashInvalidMethod
> 	case "<missing password>":
> ```

what is this string?
___
*[pkg/sql/create_role.go, line 286 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OUkmjCr4VeIUBB9iN:-N-OUkmk0B0UdZ8ryhzm:b-5kxlsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/sql/create_role.go#L286)):*
> ```Go
> 	}
> 
> 	hashedPassword, err = security.HashPassword(ctx, &st.SV, security.GetConfiguredPasswordHashMethod(ctx, &st.SV), password)
> ```

nit: add an intermediate variable to clarify


<!-- Sent from Reviewable.io -->

2022-04-11 17:17 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[-- commits, line 23 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OTaA3-s322joHw58W):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`i.e.` -> `e.g.`
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1166 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OUD735b3TmY0FaXN0:-N-OcF9w6-KyEPLfpv3Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L1166)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe add `if passwordHashMethod == invalid { print("feature not supported"); return errstate }`
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1169 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OTedSCaYlkBvkQVjN:-N-OX-GP6qaoQp26a60B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L1169)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: missing space between `:` and `%`
</blockquote></details>

Done.



_Code quote:_
```Go
Reading password
```
___
*[pkg/cli/clisqlshell/sql.go, line 1177 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OTgxjAUcUH0DjIObI:-N-OX-so8dXAUsGbCdzr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L1177)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto: `password: %v\n`
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1204 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OToldBobKePakkBXb:-N-OX0gT1hvOhWiayAhJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L1204)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: missing space `password: %v\n`
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1781 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OTvs2CsBhwD3tuD4Z:-N-OWlCh3f3TVSAtZKQB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L1781)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please avoid introducing new global variables. Use `cliState` or `cliState.iCtx` instead.
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 2157 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OU8VE-UhE6m6Ul6ra:-N-OXAZL5Iq4_gRgm9NI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L2157)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: missing vowel in variable name
</blockquote></details>

Done.



_Code quote:_
```Go
passwordEncrptMethod
```
___
*[pkg/cli/clisqlshell/sql.go, line 2168 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OUTZ19te6iK3FJ0RV:-N-OakVn4ImHhwT2SnEF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L2168)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please don't implement this `switch` in the cli packge, and instead place it in `security/password.go` alongside the method definitions. This will ensure that any changes to the `security` package will automatically propagate here.
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 2171 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OUMTU7U21Ej5HAI6E:-N-Oamma3Yy0YPOb4LID:btmw8qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/cli/clisqlshell/sql.go#L2171)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

what is this string?
</blockquote></details>

It's from `HashMethod.String()`, where `security.HashMissingPassword -> "<missing password>"`
___
*[pkg/sql/create_role.go, line 286 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-OUkmjCr4VeIUBB9iN:-N-Ob_T4DmdCFJzfzFkX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25610586b5295aaf73f3b5da998c629c829db40d/pkg/sql/create_role.go#L286)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: add an intermediate variable to clarify
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-13 20:27 UTC, rafiss requested changes
lgtm, with some small nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-:-N-ZavYF1UkMS6Hg8SnJ:b3grk4y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1198 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-Za8B66xJ0osthFUI7:-N-Za8B66xJ0osthFUI8:b-px3qsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1198)):*
> ```Go
> 			return errState
> 		} else {
> 			var userName string
> ```

nit: this could be `var userName security.SQLUsername`, which is a bit safer (see below)
___
*[pkg/cli/clisqlshell/sql.go, line 1201 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZaUr7ENU9p-yf53jq:-N-ZaUr7ENU9p-yf53jr:b68ifgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1201)):*
> ```Go
> 
> 			if len(cmd) > 1 {
> 				userName = cmd[1]
> ```

would need to use `userName = security.MakeSQLUsernameFromUserInput(cmd[1], security.UsernameValidation)`
___
*[pkg/cli/clisqlshell/sql.go, line 1209 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZYIoI9jShbXvyvkUA:-N-ZYIoI9jShbXvyvkUB:b-mp1hmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1209)):*
> ```Go
> 			}
> 
> 			var hashedPassword = []byte(password1)
> ```

nit: i think this should just be initialized as `var hashedPassword []byte`
___
*[pkg/cli/clisqlshell/sql.go, line 1212 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZZZ686S1TJxf9askU:-N-ZZZ686S1TJxf9askV:bv4quvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1212)):*
> ```Go
> 
> 			sv := cluster.MakeClusterSettings().SV
> 			hashedPassword, err := security.HashPassword(context.Background(), &sv, c.passwordHashMethod, password1)
> ```

i may have missed this from the other comment thread, but why don't we need to make sure the server supports pre-hashed passwords? (i.e. expose the `server.user_login.store_client_pre_hashed_passwords.enabled` setting in some way)
___
*[pkg/cli/clisqlshell/sql.go, line 1223 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-Z_0522rEU_TBxyyiY:-N-Z_0534R4deaazzVyt:b-8wolg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1223)):*
> ```Go
> 				`ALTER USER %s WITH LOGIN PASSWORD '%s'`,
> 				userName,
> 				string(hashedPassword))
> ```

i think to be extra safe, this can be:
```
			c.concatLines = fmt.Sprintf(
				`ALTER USER %s WITH LOGIN PASSWORD %s`,
				userName.SQLIdentifier(),
				lexbase.EscapeSQLString(string(hashedPassword)),
			)
```
___
*[pkg/security/password.go, line 429 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZYeO40fVu4kJPZRcI:-N-ZYeO40fVu4kJPZRcJ:bgdpwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/security/password.go#L429)):*
> ```Go
> // using the currently configured method.
> func HashPassword(
> 	ctx context.Context, sv *settings.Values, method HashMethod, password string,
> ```

nit: this diff might be in the wrong commit


<!-- Sent from Reviewable.io -->

2022-04-14 09:26 UTC, knz reviewed
> Reviewed 1 of 4 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 210 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-bNnarDFyeqE6JsbOL:-N-bNnarDFyeqE6JsbOM:blz3w7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L210)):*
> ```Go
> 	// passwordHashMethod saves the hash method used for password encryption.
> 	// This is used by the `\password` cli command.
> 	passwordHashMethod security.HashMethod
> ```

I don't think `cliState` is the right place - that gets reset when the user uses `\i`  (recursive execution). The `c.iCtx` is the one that's shared.
___
*[pkg/cli/clisqlshell/sql.go, line 1172 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-bN1cC9x7tckauMcip:-N-bN1cC9x7tckauMciq:b-jmb404) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1172)):*
> ```Go
> 	case `\password`:
> 		if c.passwordHashMethod == security.HashInvalidMethod ||
> 			c.passwordHashMethod == security.HashMissingPassword {
> ```

I don't think it's possible to get HashMissingPassword here ever.
___
*[pkg/cli/clisqlshell/sql.go, line 1201 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZaUr7ENU9p-yf53jq:-N-bN8YC3Qgjo0JK6kv7:b-l0m6f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1201)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would need to use `userName = security.MakeSQLUsernameFromUserInput(cmd[1], security.UsernameValidation)`
</blockquote></details>

good catch :100: 
___
*[pkg/cli/clisqlshell/sql.go, line 1212 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZZZ686S1TJxf9askU:-N-bNB1e8jqpBNH2sw_a:b-wcipnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1212)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i may have missed this from the other comment thread, but why don't we need to make sure the server supports pre-hashed passwords? (i.e. expose the `server.user_login.store_client_pre_hashed_passwords.enabled` setting in some way)
</blockquote></details>

My argument for this is that it's not the responsibility of the CLI to support this setting. I don't think we care to support more functionality here than a user would get if they connected to crdb via `psql`.
___
*[pkg/cli/clisqlshell/sql.go, line 1223 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-Z_0522rEU_TBxyyiY:-N-bNKue619-N6FFOz4U:b-m2d819) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1223)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think to be extra safe, this can be:
```
			c.concatLines = fmt.Sprintf(
				`ALTER USER %s WITH LOGIN PASSWORD %s`,
				userName.SQLIdentifier(),
				lexbase.EscapeSQLString(string(hashedPassword)),
			)
```

</blockquote></details>

woah yes good catch :100: 


Also, separately, any reason why this code can't use a placeholder for the password instead?  i.e. `ALTER USER ... WITH LOGIN PASSWORD $1`?
___
*[pkg/security/password.go, line 157 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-bNgTP53oAMmWxgwzF:-N-bNgTP53oAMmWxgwzG:b996mle) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/security/password.go#L157)):*
> ```Go
> func GetHashMethodFromString(s string) (HashMethod, error) {
> 	switch s {
> 	case "<invalid>":
> ```

please remove the two first `case`s. They are not valid input.


<!-- Sent from Reviewable.io -->

2022-04-14 15:49 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/cli/clisqlshell/sql.go, line 210 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-bNnarDFyeqE6JsbOL:-N-chWgj5pyKfqT3KWcu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L210)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't think `cliState` is the right place - that gets reset when the user uses `\i`  (recursive execution). The `c.iCtx` is the one that's shared.
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1172 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-bN1cC9x7tckauMcip:-N-chY-4C5yULXT6AzgK:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1172)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't think it's possible to get HashMissingPassword here ever.
</blockquote></details>

Removed.
___
*[pkg/cli/clisqlshell/sql.go, line 1198 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-Za8B66xJ0osthFUI7:-N-chZw-1bpWEuoOgjXr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1198)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this could be `var userName security.SQLUsername`, which is a bit safer (see below)
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1201 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZaUr7ENU9p-yf53jq:-N-ch_bNCFVGTEashg8L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1201)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

good catch :100: 
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1209 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZYIoI9jShbXvyvkUA:-N-chdDy1gIBXBmlBEJp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1209)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think this should just be initialized as `var hashedPassword []byte`
</blockquote></details>

Done.
___
*[pkg/cli/clisqlshell/sql.go, line 1212 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZZZ686S1TJxf9askU:-N-cilnU6OKhASaM8tHc:b-lra4ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1212)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

My argument for this is that it's not the responsibility of the CLI to support this setting. I don't think we care to support more functionality here than a user would get if they connected to crdb via `psql`.
</blockquote></details>

Also, postgres always takes the input password as clear text and always encrypts it, see [here](https://github.com/postgres/postgres/blob/4cd8717af3f0345c758d46fea06fb390b4d593f2/src/bin/psql/command.c#L2115) and [here](https://github.com/postgres/postgres/blob/4cd8717af3f0345c758d46fea06fb390b4d593f2/src/interfaces/libpq/fe-auth.c#L1205-L1333).
___
*[pkg/cli/clisqlshell/sql.go, line 1223 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-Z_0522rEU_TBxyyiY:-N-cjGUW7tKNaG8Afmx4:b-2e1squ) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1223)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

woah yes good catch :100: 


Also, separately, any reason why this code can't use a placeholder for the password instead?  i.e. `ALTER USER ... WITH LOGIN PASSWORD $1`?
</blockquote></details>

Made the changes.
I didn't use a placeholder because only `c.concatLines`(a string) is passed to `clisqlclient.MakeQuery()` when the statement is being executed. 
```
	c.exitErr = c.runWithInterruptableCtx(func(ctx context.Context) error {
		return c.sqlExecCtx.RunQueryAndFormatResults(ctx,
			c.conn, c.iCtx.stdout, c.iCtx.stderr,
			clisqlclient.MakeQuery(c.concatLines))
	})
```
I'm not sure how to achieve this with a placeholder for the password.
___
*[pkg/security/password.go, line 157 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-bNgTP53oAMmWxgwzF:-N-ckD3f4WkPEy03vADK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/security/password.go#L157)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please remove the two first `case`s. They are not valid input.
</blockquote></details>

Done.
___
*[pkg/security/password.go, line 429 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZYeO40fVu4kJPZRcI:-N-cka7n9iEAl0KCpH80:b-gwkra9) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/security/password.go#L429)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this diff might be in the wrong commit
</blockquote></details>

Hm I see it's sitting in `security: let HashPassword take a HashMethod as an argument`, which is intended and seems correct to me?


<!-- Sent from Reviewable.io -->

2022-04-14 15:54 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1212 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZZZ686S1TJxf9askU:-N-cjoDx8i6HKTDvE953:b-pcqev6) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1212)):*
well the big difference is that PG doesn't have anything like the `server.user_login.store_client_pre_hashed_passwords.enabled` setting.

so the PG server unconditionally does the following logic:
> If the presented password string is already in MD5-encrypted or SCRAM-encrypted format, then it is stored as-is

and that is why the `psql` CLI can unconditionally pre-hash the password when using `\password`

However, if `server.user_login.store_client_pre_hashed_passwords.enabled` is false in CRDB, then the server will receive this pre-hashed password, and then hash it _again_ at this point: https://github.com/cockroachdb/cockroach/blob/4c35e3d751fdb8c6f6e36ec18a79cc4b369f6017/pkg/sql/create_role.go#L265-L286

and if that happens, the user who just changed the password will now have **no way** to know what the password was just changed to.


<!-- Sent from Reviewable.io -->

2022-04-14 16:08 UTC, knz reviewed
> Reviewed 1 of 4 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1212 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZZZ686S1TJxf9askU:-N-coHih97-kVwshwFOx:b-qx6tdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1212)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

well the big difference is that PG doesn't have anything like the `server.user_login.store_client_pre_hashed_passwords.enabled` setting.

so the PG server unconditionally does the following logic:
> If the presented password string is already in MD5-encrypted or SCRAM-encrypted format, then it is stored as-is

and that is why the `psql` CLI can unconditionally pre-hash the password when using `\password`

However, if `server.user_login.store_client_pre_hashed_passwords.enabled` is false in CRDB, then the server will receive this pre-hashed password, and then hash it _again_ at this point: https://github.com/cockroachdb/cockroach/blob/4c35e3d751fdb8c6f6e36ec18a79cc4b369f6017/pkg/sql/create_role.go#L265-L286

and if that happens, the user who just changed the password will now have **no way** to know what the password was just changed to.
</blockquote></details>

ok so my position is and remains that   there's  no use case for anyone to use `server.user_login.store_client_pre_hashed_passwords.enabled` ever. I think the deployments using this will be in the minority (if any exist at all -- we could add telemetry to confirm this)

We only added the cluster setting as a *troubleshooting* mechanism in case something goes wrong in the logic (i.e. a bug on our side). If we ever find a bug, we can tell the affected customer(s)  "you can use this cluster setting as a stop-gap until we fix the bug".

I am not keen adding extra logic in the CLI *in the common path* for a code path that's only used when troubleshooting a bug which we don't even know we have (and our testing suggests it's not even there).

If this remains a point of contention, I'd nearly tempted to suggest removing that cluster setting altogether -- if there's any bug, a customer could use `INSERT INTO system.users` manually. We could just make ALTER detect the hashes unconditionally.
___
*[pkg/cli/clisqlshell/sql.go, line 1223 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-Z_0522rEU_TBxyyiY:-N-coCxe4RLj6FLzQtvB:b4qngnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1223)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Made the changes.
I didn't use a placeholder because only `c.concatLines`(a string) is passed to `clisqlclient.MakeQuery()` when the statement is being executed. 
```
	c.exitErr = c.runWithInterruptableCtx(func(ctx context.Context) error {
		return c.sqlExecCtx.RunQueryAndFormatResults(ctx,
			c.conn, c.iCtx.stdout, c.iCtx.stderr,
			clisqlclient.MakeQuery(c.concatLines))
	})
```
I'm not sure how to achieve this with a placeholder for the password.
</blockquote></details>

yes, thanks for explaining.
___
*[pkg/cli/clisqlshell/sql.go, line 1188 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-cnYsRA6YrVl2dBQFb:-N-cnYsRA6YrVl2dBQFc:b86ao3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/be214a8ecddf5543a7438b51657c91de639570a2/pkg/cli/clisqlshell/sql.go#L1188)):*
> ```Go
> 		}
> 
> 		fmt.Fprintf(c.iCtx.stdout, "password1:%#v\npassword2:%#v\n", password1, password2)
> ```

don't forget to remove this before this merges
___
*[pkg/cli/clisqlshell/sql.go, line 1206 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-cnd2mCSitQ6AcRyhU:-N-cnd2nCgRvw_yifbdu:b-zb576s) ([raw file](https://github.com/cockroachdb/cockroach/blob/be214a8ecddf5543a7438b51657c91de639570a2/pkg/cli/clisqlshell/sql.go#L1206)):*
> ```Go
> 			}
> 			if err != nil {
> 				fmt.Fprintf(c.iCtx.stderr, "normalize username: %v\n", err)
> ```

i don't think this fprintf is necessary.  The error will _never_ happen unless the user is injecting some incompatible and erroneous network tool in-between the CLI and the server.
In fact, I would be in favor of adding a new line instead
```
err = errors.NewAssertionFailureWithWrappedErrf(err, "server-side username does not pass validation")
```


<!-- Sent from Reviewable.io -->

2022-04-14 16:12 UTC, rafiss approved these changes
lgtm after addressing rafael's nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-:-N-cqAO24_Xr-YnEvGvc:b8suseu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1212 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZZZ686S1TJxf9askU:-N-cp_qi2TsMkPhWq_Wt:bw53pm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1212)):*
>  there's no use case for anyone to use server.user_login.store_client_pre_hashed_passwords.enabled ever. I think the deployments using this will be in the minority (if any exist at all -- we could add telemetry to confirm this)

i wasn't aware of this, thanks for the info. OK, I'm fine to not check in the CLI then

However, i'd then argue that `server.user_login.store_client_pre_hashed_passwords.enabled` should not be a public setting. that can be discussed/addressed later
___
*[pkg/security/password.go, line 429 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZYeO40fVu4kJPZRcI:-N-cpv3z2CXL7f3Jfi4p:b-1yj6l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/security/password.go#L429)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Hm I see it's sitting in `security: let HashPassword take a HashMethod as an argument`, which is intended and seems correct to me?
</blockquote></details>

i must have seen the wrong thing, my bad


<!-- Sent from Reviewable.io -->

2022-04-14 16:22 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1212 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-ZZZ686S1TJxf9askU:-N-csU_51Os1wN_zY6tA:b-yqzax) ([raw file](https://github.com/cockroachdb/cockroach/blob/747fcd35fbb4a175dfe0dfb4d4014d5e86cecd8a/pkg/cli/clisqlshell/sql.go#L1212)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

>  there's no use case for anyone to use server.user_login.store_client_pre_hashed_passwords.enabled ever. I think the deployments using this will be in the minority (if any exist at all -- we could add telemetry to confirm this)

i wasn't aware of this, thanks for the info. OK, I'm fine to not check in the CLI then

However, i'd then argue that `server.user_login.store_client_pre_hashed_passwords.enabled` should not be a public setting. that can be discussed/addressed later
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/79954


<!-- Sent from Reviewable.io -->

2022-04-14 16:22 UTC, ZhouXing19 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @ZhouXing19)

___
*[pkg/cli/clisqlshell/sql.go, line 1188 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-cnYsRA6YrVl2dBQFb:-N-cs9BT60ESqiuX66AA:b-hw406u) ([raw file](https://github.com/cockroachdb/cockroach/blob/be214a8ecddf5543a7438b51657c91de639570a2/pkg/cli/clisqlshell/sql.go#L1188)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

don't forget to remove this before this merges
</blockquote></details>

Ah thanks! removed.
___
*[pkg/cli/clisqlshell/sql.go, line 1206 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-N-cnd2mCSitQ6AcRyhU:-N-csIku-2kf4vcRo4gx:b435755) ([raw file](https://github.com/cockroachdb/cockroach/blob/be214a8ecddf5543a7438b51657c91de639570a2/pkg/cli/clisqlshell/sql.go#L1206)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

i don't think this fprintf is necessary.  The error will _never_ happen unless the user is injecting some incompatible and erroneous network tool in-between the CLI and the server.
In fact, I would be in favor of adding a new line instead
```
err = errors.NewAssertionFailureWithWrappedErrf(err, "server-side username does not pass validation")
```


</blockquote></details>

Made the change.


<!-- Sent from Reviewable.io -->

2022-04-14 16:56 UTC, knz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77975#-:-N-d-EP0AoW5iRtH-g6B:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)



<!-- Sent from Reviewable.io -->

2022-04-14 18:48 UTC, ZhouXing19 commented
The coming commits are to fix for the CI tests.

2022-04-21 14:28 UTC, rafiss commented
Summarizing a convo I had with Jane:

The failing test is TestLint/TestForbiddenImportsSQLShell`. This change is making `cockroach-sql` pull in new dependencies: `pkg/roachpb`,`pkg/util/log`, `pkg/util/stop`, and `pkg/util/tracing`. These are not allowed since it makes the lightweight SQL shell binary too large.

It's caused by the import of the `security` and `settings/cluster` packages in `clisqlshell`. So it seems like the options are:
1. find another way to inject the `security` dependency at runtime
2. refactor the `security` package so that  there's a new `security/password` sub-package, which does not import `settings/cluster` or any other large database packages.

I feel like option 2 might be better.

2022-04-21 18:35 UTC, knz commented
nb: i was mistaken in my above assessment. Turns out rafi was right from the start (my apologies). I had a separate discussion with jane about this.

2022-04-21 20:43 UTC, ZhouXing19 commented
Per the suggestions above, we will be working on https://github.com/cockroachdb/cockroach/pull/80332 first to move the password logic to a separate package, `security/password`. Once #80332 is finished, we will rework this PR.

2022-04-28 22:45 UTC, knz commented
Jane and I did some pair programming on this to rebase it on top of https://github.com/cockroachdb/cockroach/pull/80332.

We were able to simplify as follows:
- the username does not need to be validated using package `security`, because we already take care of quoting it properly before passing it to ALTER 
- we can move the choice of default cost to the new password package

As a result, the `clisqlshell` package neither needs to depend on `security` nor on `clustersettings`. This was the missing simplification needed to satisfy the CI linter.

Now this PR can be merged (assuming CI does not find more problems).

2022-04-28 23:30 UTC, knz commented
also need to rebase on top of #80760

need to then adjust code in clisqlshell/sql.go as follows:

```go
       hashedPassword, err = password.HashPassword(
               context.Background(),
               passwordHashMethod.GetDefaultCost(),
               passwordHashMethod,
               password1,
               nil, /* hashSem - no need to throttle hashing in CLI */
       )
```

2022-04-29 20:25 UTC, ZhouXing19 commented
bors r+

2022-04-29 21:51 UTC, merged