server: VIEWACTIVITY role gates unredacted nodes info
cockroachdb/cockroach pull request #78045
Opened 2022-03-17 19:26 UTC by dhartunian

Previously, the `Nodes` and `NodesUI` endpoints were gated behind the
Admin role. For the former endpoint requests would fail if the user
didn't have the Admin role, and for the latter, we'd show partially
redacted information that omitted hostnames and IP addresses.

This was deemed problematic for customers who did not want to set the
Admin role just to grant a user the ability to view detailed node
information about the cluster.

This PR changes the role gate for the endpoints above to use the
`VIEWACTIVITY` role option. Users with the option will be able to access
the `Nodes` endpoint and see unredacted nodes information at the
`NodesUI` endpoint used by the DB Console.

As a result, the nodes overview page as well as the node reports page
will now show unredacted information to users with `VIEWACTIVITY`.
(Existing functionality for Admins us also retained as those users
implicitly have the `VIEWACTIVITY` role.)

Resolves #77665

Release note (ui change, security update, api change): The
`_status/v1/nodes` endpoint is avaible to all users with the
`VIEWACTIVITY` role option, not just Admins. In the DB Console, the
Nodes Overview and Node Reports pages will now display unredacted
information containing node hostnames and IP addresses for all users
with the `VIEWACTIVITY` role option. Previously this was also gated for
Admins only.

2022-03-17 19:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/78045)
<!-- Reviewable:end -->

2022-03-18 18:25 UTC, matthewtodd requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78045)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @rafiss)

___
*[pkg/server/admin_test.go, line 2561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78045#-MyTGAEG1z_wIvJDusyE:-MyTGAEH7wH6FPhl7yu9:bdzltxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0140c563fcabf2667f658005b36ee6965de24cf/pkg/server/admin_test.go#L2561)):*
> ```Go
> 			"requireViewActivityPermission",
> 			underTest.requireViewActivityPermission,
> 			map[string]bool{"withAdmin": true, "withva": false, "withvaredacted": true, "withvaandredacted": false, "withoutprivs": true},
> ```

I'm surprised to see this expecting an error for the admin. Are the usernames case-sensitive? If so, I think this would want to be `"withadmin": false` here & below, yes?


<!-- Sent from Reviewable.io -->

2022-03-19 00:48 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78045)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @matthewtodd, and @rafiss)

___
*[pkg/server/status.go, line 1408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78045#-MyUdJEaA-AceDvKmgCB:-MyUdJEaA-AceDvKmgCC:b-7fmoky) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0140c563fcabf2667f658005b36ee6965de24cf/pkg/server/status.go#L1408)):*
> ```Go
> 	ctx = s.AnnotateCtx(ctx)
> 
> 	err := s.privilegeChecker.requireViewActivityPermission(ctx)
> ```

nit: maybe the docs around where the VIEWACTIVITY role option is declared should be updated to say what it controls
___
*[pkg/server/admin_test.go, line 2561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78045#-MyTGAEG1z_wIvJDusyE:-MyUctDBAyd4Oy9amm34:bn3yo59) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0140c563fcabf2667f658005b36ee6965de24cf/pkg/server/admin_test.go#L2561)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I'm surprised to see this expecting an error for the admin. Are the usernames case-sensitive? If so, I think this would want to be `"withadmin": false` here & below, yes?
</blockquote></details>

all usernames are case-insensitive. internally in the database, it's all normalized to lower-case

i'd recommend using `security.SQLUsername` as the type of map key here


<!-- Sent from Reviewable.io -->

2022-03-21 17:25 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78045)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd and @rafiss)

___
*[pkg/server/status.go, line 1408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78045#-MyUdJEaA-AceDvKmgCB:-MyhSnFg7MYkLJcCWJMJ:bvbuiva) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0140c563fcabf2667f658005b36ee6965de24cf/pkg/server/status.go#L1408)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: maybe the docs around where the VIEWACTIVITY role option is declared should be updated to say what it controls
</blockquote></details>

I'm having trouble finding where these docs are. Role options don't have autogen docs, right? I assume the release note will result in the relevant docs getting updated.
___
*[pkg/server/admin_test.go, line 2561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78045#-MyTGAEG1z_wIvJDusyE:-MyhUkcoDoyNDjC8t2ZO:b-ovq8a7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0140c563fcabf2667f658005b36ee6965de24cf/pkg/server/admin_test.go#L2561)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

all usernames are case-insensitive. internally in the database, it's all normalized to lower-case

i'd recommend using `security.SQLUsername` as the type of map key here
</blockquote></details>

You're correct @matthewtodd, the test was wrong. This is fixed. Thanks for the helpful type @rafiss 


<!-- Sent from Reviewable.io -->

2022-03-21 17:26 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78045)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @matthewtodd, and @rafiss)

___
*[pkg/server/status.go, line 1408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78045#-MyUdJEaA-AceDvKmgCB:-MyhVu651Q7DgQxYeeEP:b-6bkgxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0140c563fcabf2667f658005b36ee6965de24cf/pkg/server/status.go#L1408)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I'm having trouble finding where these docs are. Role options don't have autogen docs, right? I assume the release note will result in the relevant docs getting updated.
</blockquote></details>

sorry, in this case i meant to refer to the internal comments in the code. i definitely was unclear!


<!-- Sent from Reviewable.io -->

2022-03-21 19:19 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78045#-:-MyhurOs5niFKPbaHuCD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)



<!-- Sent from Reviewable.io -->

2022-03-22 16:53 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78045)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @matthewtodd and @rafiss)

___
*[pkg/server/status.go, line 1408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78045#-MyUdJEaA-AceDvKmgCB:-MymXyFICF_NJBDSR79x:bmkq634) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0140c563fcabf2667f658005b36ee6965de24cf/pkg/server/status.go#L1408)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

sorry, in this case i meant to refer to the internal comments in the code. i definitely was unclear!
</blockquote></details>

Thx @rafiss. Added docs.


<!-- Sent from Reviewable.io -->

2022-03-22 21:30 UTC, dhartunian commented
TFTRs

bors r=matthewtodd

2022-03-23 14:32 UTC, dhartunian commented
bors r+

2022-03-23 20:16 UTC, merged