ui: sort items in the sql activity dropdown menu
cockroachdb/cockroach pull request #78095
Opened 2022-03-18 18:25 UTC by gtr

Fixes #78081.

Previously, app names in the dropdown menu for the stmts, txns, and
sessions pages were unsorted. This change sorts these app names.

Release note (ui change): app names in the dropdown menu are sorted.

2022-03-18 18:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/78095)
<!-- Reviewable:end -->

2022-03-18 18:53 UTC, maryliag requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78095)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78095#-MyTN-X24dz9oqVWgf4w):*
can you also check the order for databases? this both we have both things properly sorted


<!-- Sent from Reviewable.io -->

2022-03-18 18:54 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78095)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78095#-MyTN-X24dz9oqVWgf4w):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you also check the order for databases? this both we have both things properly sorted
</blockquote></details>

*this way


<!-- Sent from Reviewable.io -->

2022-03-21 15:43 UTC, gtr reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78095)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78095#-MyTN-X24dz9oqVWgf4w):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

*this way
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2022-03-21 19:42 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  once you have tests passing

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78095#-:-Myhzzcm6758eWvRBvdw:bwvoind)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2022-03-23 19:37 UTC, gtr commented
bors r+

2022-03-23 21:24 UTC, merged