ui: fix explain plan not rendering
cockroachdb/cockroach pull request #78105
Opened 2022-03-18 22:02 UTC by Azhng

Partially resolves #69237

Previously, in a multi-node cluster, query plans for single statement
fingerprints may only be sampled in the subset of the nodes in the
cluster.  Console previsouly assumed that when the query plan was
not sampled, it would be represented as "null". Unfortunately, this
is not the case, since the backend API always sends back a valid
JSON object with empty "Name" and "Children" fields for empty sampled
plan. This caused the Statement Detail page to incorrectly pick the
empty query plan to render.

This commit updates the frontend statement statistics aggregation logic to
properly discard the empty query plan.

Release note (bug fix): Previously Statement Detail Page fails to load query
plan even after when the plan has been sampled. This is now fixed.

2022-03-18 22:09 UTC, Azhng commented
This issue doesn't fully resolve #69237,  since when we have multiple query plan, we would still be flip flopping between them depending on the ordering of query plan in the API response sent back from backend. 

One way to address this could be artificially introduce some consistent ordering (e.g. call `.sort()` on `aggregated_ts + node_id` before combining the statement statistics in the API response). This feels a bit arbitrary though, but perhaps it's fine from UX perspective? 

Thoughts? @maryliag @kevin-v-ngo

2022-03-18 22:12 UTC, maryliag commented
I think is fine to force a consistence by using a order, in that case using the latest one we have.

2022-03-19 05:08 UTC, kevin-v-ngo commented
Hi Archer, few questions:

Which subset of nodes in the cluster samples the statement fingerprint (how do we determine which node does the sampling - is it by the gateway?)?

What is the experience given now we discard the empty plan? Are we guaranteed to have a non-empty plan?

> we would still be flip flopping between them depending on the ordering of query plan in the API response sent back from backend.

Is this because different nodes have different sampled plans? Why so?

Just trying to understand the problem a bit more here - but a consistent ordering sounds fine to me! This shouldn't be a problem in 22.1 as we've enhanced the experience, making it. more stable, using the plan gist (not relying on the sampled plan).

2022-03-21 18:51 UTC, Azhng reviewed
Updated the PR to always return the most recently sampled plan.

> Which subset of nodes in the cluster samples the statement fingerprint (how do we determine which node does the sampling - is it by the gateway?)?

The decision on whether if a query's plan is sampled is decided independently between the nodes in the cluster. There is no coordination there. The default heuristics used here is:
1. if this is the first time this query execute on a particular node, we perform sampling
2. if the last query sampling happened over 5 minutes ago, we perform sampling
3. if this is explicitly requested, e.g. (EXPLAIN ANALZE / Statement bundle), we perform sampling

> What is the experience given now we discard the empty plan? Are we guaranteed to have a non-empty plan?

We can guarantee a non-empty plan as long as there is at least 1 sampled plan.

> Is this because different nodes have different sampled plans? Why so?

It is possible that we would have a following scenario, suppose we have 3 nodes

1. Time = 0 mins
  a. Node 1 execute query A that reads primary index. The query plan is sampled and stored in Node 1.
  b. Node 2 execute query A that reads primary index. This query plan is sampled and stored in Node 2.
2. Time = 10 mins
  a. Schema change happened and a new secondary index is introduced for the underlying table accessed by query A.
3. Time = 15 mins
  a. Node 1 execute query A, and now the new secondary index cause A to read secondary index instead. This query plan is sampled and stored in Node 1.
4. Time = 20 mins
  a. Statement Detail Page loads, now we have two different plan from 


Note that, as this point, we will have two different plans stored on different nodes. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78105#-:-MyhlksY-yypBMOJC24o:bxihd2t)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-03-21 19:57 UTC, maryliag requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78105)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.spec.ts, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78105#-Myi2ZgSAof0uuE1CYdG:-Myi2ZgSAof0uuE1CYdH:bjlnt3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/60cfef181c85554b925bd1b272cad029f57cdb6a/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.spec.ts#L438)):*
> ```XML
>       const error2 = randomString();
>       const plan1 = randomPlanDescription();
>       const plan2 = randomPlanDescription();
> ```

add test where the plan is empty


<!-- Sent from Reviewable.io -->

2022-03-21 21:46 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78105)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.spec.ts, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78105#-Myi2ZgSAof0uuE1CYdG:-MyiRHL38SO0s23depr3:b-y1ieqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/60cfef181c85554b925bd1b272cad029f57cdb6a/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.spec.ts#L438)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

add test where the plan is empty
</blockquote></details>

The test cases for the empty plan case already exists here with `a` and the special `empty` variables. 

https://github.com/cockroachdb/cockroach/pull/78105/files#diff-2c3d4c532b652b88f3da7f05be3bad0156b61e15cd36f0dd02110c629144171fR449-R460


<!-- Sent from Reviewable.io -->

2022-03-21 21:53 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78105#-:-MyiTAGJ2b0gNtgkanAp:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2022-03-21 21:54 UTC, merged