stats: table-level setting to turn auto stats collection on/off
cockroachdb/cockroach pull request #78110
Opened 2022-03-18 23:20 UTC by msirek

Previously, there was no way to enable or disable automatic statistics
collection at the table level. It could only be turned on or off via the
`sql.stats.automatic_collection.enabled` cluster setting.

This was inadequate because statistics collection can be expensive for
large tables, and it would be desirable to defer collection until after
data is finished loading, or in off hours. Also, small tables which are
frequently updated may trigger statistics collection leading to
unnecessary overhead and/or unpredictable query plan changes.

To address this, this patch adds support for setting of the following
cluster settings at the table level:
```
sql.stats.automatic_collection.enabled
sql.stats.automatic_collection.fraction_stale_rows
sql.stats.automatic_collection.min_stale_rows
```
for example:
```
ALTER TABLE t1 SET ("sql.stats.automatic_collection.enabled" = true);
ALTER TABLE t1
      SET ("sql.stats.automatic_collection.fraction_stale_rows" = 0.1,
           "sql.stats.automatic_collection.min_stale_rows" = 2000);
```
The table-level setting takes precedence over the cluster setting.

Release justification: Low risk fix for missing fine-grained control
over automatic statistics collection.

Release note (sql change): Automatic statistics collection can now be
enabled or disabled for individual tables, for example:
```
ALTER TABLE t1 SET ("sql.stats.automatic_collection.enabled" = true);
ALTER TABLE t1 SET ("sql.stats.automatic_collection.enabled" = false);
ALTER TABLE t1 RESET ("sql.stats.automatic_collection.enabled");
```
RESET removes the setting value entirely, in which case the cluster
setting of the same name is in effect for the table.

Cluster settings `sql.stats.automatic_collection.fraction_stale_rows`
and `sql.stats.automatic_collection.min_stale_rows` can now also be
set at the table level, either at table creation time, or later:
```
ALTER TABLE t1
      SET ("sql.stats.automatic_collection.fraction_stale_rows" = 0.1,
           "sql.stats.automatic_collection.min_stale_rows" = 2000);
CREATE TABLE t1 (a INT, b INT)
       WITH ("sql.stats.automatic_collection.enabled" = true,
             "sql.stats.automatic_collection.min_stale_rows" = 1000000,
	     "sql.stats.automatic_collection.fraction_stale_rows" = 0.05
	    );
```
Tables that have auto stats collection explicitly enabled or disabled
may be discovered by querying system tables, for example,
find all tables with auto stats enabled:
```
SELECT
        tbl.database_name || '.' || tbl.schema_name || '.' || tbl.name
FROM
        crdb_internal.tables AS tbl
        INNER JOIN system.descriptor AS d ON d.id = tbl.table_id
WHERE
        tbl.database_name IS NOT NULL
        AND tbl.database_name <> '%s'
        AND tbl.drop_time IS NULL
        AND
         crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor',
                d.descriptor, false)->'table'->'tableLevelSetting'
		-> 'sqlStatsAutomaticCollectionEnabled' ? 'value';

      ?column?
--------------------
  defaultdb.mws.t1

```

2022-03-18 23:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/78110)
<!-- Reviewable:end -->

2022-03-21 15:00 UTC, postamar requested changes
I reviewed the parts of this change which directly apply to SQL Schema. 

Do you intend to backport this to 22.1? I ask because this commit changes the descriptor protobufs. cc @ajwerner 

> Reviewed 4 of 10 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-Mygy5uA2TknzLc99hCf:b-n9rd20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @rharding6373, @rytaft, and @vy-ton)

___
*[pkg/sql/catalog/catpb/catalog.proto, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MygvAEC8fo9oWRZ0bKH:-MygvAEC8fo9oWRZ0bKI:bht7soa) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/catpb/catalog.proto#L240)):*
> ```protobuf
> // TableLevelSettings represents cluster or session settings specified at the
> // table level. Each SettingValue is nullable so queries of the descriptor in
> // JSON form only list values which have been set.
> ```

Assuming that we can't get by with primitive values here, I'd much prefer that you define a nested message for each setting in this message, rather than define some generic `Int` or `String` box message at the top level
___
*[pkg/sql/catalog/catpb/catalog.proto, line 241 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MygvgPB4JHBsIT0VQEE:-MygvgPB4JHBsIT0VQEF:b-c6z04i) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/catpb/catalog.proto#L241)):*
> ```protobuf
> // table level. Each SettingValue is nullable so queries of the descriptor in
> // JSON form only list values which have been set.
> message TableLevelSettings {
> ```

Technically, `RowLevelTTL` are also table-level settings. Perhaps it would be preferable to rename this message type (and its corresponding field in the table descriptor) to TableAutomaticStatsCollectionSettings or something?
___
*[pkg/sql/catalog/descpb/structured.go, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygxvm_DMksN5dlrTgz:-Mygxvm_DMksN5dlrTh-:bcsiqe6) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L281)):*
> ```Go
> // true, auto stats are on for this table. If ok is false, there is no setting
> // for this table.
> func (desc *TableDescriptor) AutoStatsCollectionEnabled() (enabled bool, ok bool) {
> ```

Do we really need two boolean return values here?
___
*[pkg/sql/catalog/descpb/structured.go, line 317 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MygwGsY2uNPX1WOrd7p:-MygwGsY2uNPX1WOrd7q:b-3he3ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L317)):*
> ```Go
> 	}
> 	return desc.TableLevelSettings.SqlStatsAutomaticCollectionFractionStaleRows.Value, true
> }
> ```

Can you define these methods in the `catalog.TableDescriptor` interface please?
___
*[pkg/sql/catalog/tabledesc/structured.go, line 2573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygr_uUBn_ZrsQTdFpd:-Mygr_uUBn_ZrsQTdFpe:b-bdlhon) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/tabledesc/structured.go#L2573)):*
> ```Go
> 	}
> 	if desc.TableLevelSettings != nil {
> 		settings := desc.TableLevelSettings
> ```

nit: `if settings := desc.TableLevelSettings; settings != nil {` would be more idiomatic
___
*[pkg/sql/catalog/tabledesc/structured.go, line 2578 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygs0OI64cidpUSaCkf:-Mygs0OI64cidpUSaCkg:b-az3h5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/tabledesc/structured.go#L2578)):*
> ```Go
> 			value := settings.SqlStatsAutomaticCollectionEnabled.Value
> 			appendStorageParam(`"sql.stats.automatic_collection.enabled"`,
> 				boolAsString(value))
> ```

`fmt.Sprintf("%v", value)` aught to do the trick here
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1510 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygq7JH-LyStgoTLG8_:-Mygq7JH-LyStgoTLG8a:bc7rei3) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/tabledesc/validate.go#L1510)):*
> ```Go
> // validateTableLevelSettings validates that any new table-level settings hold
> // a valid value.
> func (desc *wrapper) validateTableLevelSettings() error {
> ```

This isn't obvious when you look a lot of this validation code, but the preferred pattern is to call `vea.Report` on errors as much as possible instead of returning on the first error, to report as many errors as possible.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygqfo-A364U0heHU04:-Mygqfo-A364U0heHU05:b6p99t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/tabledesc/validate.go#L1511)):*
> ```Go
> // a valid value.
> func (desc *wrapper) validateTableLevelSettings() error {
> 	if desc.TableLevelSettings != nil {
> ```

In situations like these consider returning early to avoid large blocks and lots of nesting. Alternatively, hoist this nil-check to the call site.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1535 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MygpplL2-06eWnJZgkc:-MygpplL2-06eWnJZgkd:bgvqkj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/tabledesc/validate.go#L1535)):*
> ```Go
> 		}
> 		if desc.TableLevelSettings.SqlStatsAutomaticCollectionFractionStaleRows != nil {
> 			setting := "sql.stats.automatic_collection.fraction_stale_rows"
> ```

nit: consider defining these strings as global `const`s in the `stats` package.
___
*[pkg/sql/catalog/tabledesc/validate_test.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygx-uyBKR01bMixhW3:-Mygx-uyBKR01bMixhW4:b2ewb9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/tabledesc/validate_test.go#L134)):*
> ```Go
> 			"NextConstraintID":              {status: iSolemnlySwearThisFieldIsValidated},
> 			"DeclarativeSchemaChangerState": {status: iSolemnlySwearThisFieldIsValidated},
> 			"TableLevelSettings":            {status: iSolemnlySwearThisFieldIsValidated},
> ```

Can you also throw in a couple of unit test cases that exercise at least some of this validation logic? Let that not distract from the fact that I'm grateful that you _did_ add validation logic, it's something that's easy to overlook.


<!-- Sent from Reviewable.io -->

2022-03-21 21:40 UTC, rharding6373 requested changes
Allowing stats to be enabled at the table-level is going to be useful. Thanks for this! Nice work so far.

> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-MyiPkHP5AaaUQ8IkYqE:bph86pv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @postamar, @rytaft, and @vy-ton)

___
*[pkg/sql/catalog/catpb/catalog.proto, line 218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Myi1lksEieN9GxDJWUC:-Myi1lksEieN9GxDJWUD:b-bygmzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/catpb/catalog.proto#L218)):*
> ```protobuf
> }
> 
> // Create separate messages for setting values so we may access the
> ```

Maybe I'm just not following this...why does this mean that we can't use primitive values to represent these settings? E.g., it looks like view_query (also accessed in the SQL in automatic_stats.go) is an optional string.
___
*[pkg/sql/catalog/descpb/structured.go, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygxvm_DMksN5dlrTgz:-MyhUtGZ0EXCXl_VMPI_:bukv7dn) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L281)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Do we really need two boolean return values here?
</blockquote></details>

+1, I think one boolean is fine with true for enabled and false for disabled/no setting.
___
*[pkg/sql/catalog/descpb/structured.go, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyiPPa2DjSPIHWaORgL:-MyiPPa2DjSPIHWaORgM:b-zah1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L288)):*
> ```Go
> 		return false, false
> 	}
> 	return desc.TableLevelSettings.SqlStatsAutomaticCollectionEnabled.Value, true
> ```

Should we also consider whether auto stats is enabled overall?
___
*[pkg/sql/catalog/descpb/structured.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyhVMDF-T9YH4S37uNz:-MyhVMDG8u9IxGkF_ALj:b16xnzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L296)):*
> ```Go
> // been set at the table level.
> func (desc *TableDescriptor) AutoStatsMinStaleRows() (minStaleRows int64, ok bool) {
> 	if desc.TableLevelSettings == nil {
> ```

Could dedupe some code with `AutoStatsCollectionEnabled`
___
*[pkg/sql/catalog/descpb/structured.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyhVqaJ4396Oz31T9W9:-MyhVqaJ4396Oz31T9WA:b-tdmhqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L310)):*
> ```Go
> // not been set at the table level.
> func (desc *TableDescriptor) AutoStatsFractionStaleRows() (fractionStaleRows float64, ok bool) {
> 	if desc.TableLevelSettings == nil {
> ```

Could dedupe here, too
___
*[pkg/sql/catalog/descpb/structured.proto, line 1201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyhWDC-6B28BofYNqX6:-MyhWDC-6B28BofYNqX7:b-yttqv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cdc505b79cde668e10d7a62109f4df313eda754/pkg/sql/catalog/descpb/structured.proto#L1201)):*
> ```protobuf
>     (gogoproto.customname) = "NextConstraintID", (gogoproto.casttype) = "ConstraintID"];
> 
>   // Next ID: 51
> ```

Keep comment and increment id.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 2588 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyhhMy8AnmmkjkaseIu:-MyhhMy8AnmmkjkaseIv:btfpkwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/tabledesc/structured.go#L2588)):*
> ```Go
> 			value := settings.SqlStatsAutomaticCollectionFractionStaleRows.Value
> 			appendStorageParam(`"sql.stats.automatic_collection.fraction_stale_rows"`,
> 				fmt.Sprintf("%g", value)) //strconv.FormatFloat(value, 10))
> ```

nit: comment seems unnecessary
___
*[pkg/sql/paramparse/paramobserver.go, line 709 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyhkdJO7z0SxVv20V7N:-MyhkdJO7z0SxVv20V7O:b-2rsy4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/paramparse/paramobserver.go#L709)):*
> ```Go
> 
> func settingValuePointer(settingName string, tableSettings *catpb.TableLevelSettings) interface{} {
> 	if idx, ok := tableSettingsDict[settingName]; ok {
> ```

After taking Marius's suggestion of adding the setting names as const strings, you could get rid of the `tableSettingsDict`, which will make this function easier to read.


<!-- Sent from Reviewable.io -->

2022-03-22 01:29 UTC, vy-ton reviewed
Removing myself as an assigned reviewer. If there are specific product questions, please @me.

2022-03-22 23:12 UTC, msirek reviewed
@postamar , @rharding6373  Thanks for the great comments!

@postamar It's possible we'd want to backport it to 22.1.1, but I don't know for sure.  Would that mean the protobuf changes would need to be merged to 21.1.0?  I believe @rytaft will be talking to the SQL Schema team about this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-Myj410K55WeCW6EUeCb:b-pffav1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/catpb/catalog.proto, line 218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Myi1lksEieN9GxDJWUC:-Myjq4v32gMG5aTNYr6I:b-2p04zb) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/catpb/catalog.proto#L218)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Maybe I'm just not following this...why does this mean that we can't use primitive values to represent these settings? E.g., it looks like view_query (also accessed in the SQL in automatic_stats.go) is an optional string.
</blockquote></details>

When I tested this previously, using the nullable primitive directly, for some reason the boolean conditional to check the value wasn't evaluating properly. I just tried it again, and it's working, so I'm not sure what is different this time.  I agree is preferable to use the primitive directly, so I've made this change.
___
*[pkg/sql/catalog/catpb/catalog.proto, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MygvAEC8fo9oWRZ0bKH:-MyjvvfJEPfX_xOG2idv:bgiq5tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/catpb/catalog.proto#L240)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Assuming that we can't get by with primitive values here, I'd much prefer that you define a nested message for each setting in this message, rather than define some generic `Int` or `String` box message at the top level
</blockquote></details>

Thanks. I was able to get this working with primitive values.
___
*[pkg/sql/catalog/catpb/catalog.proto, line 241 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MygvgPB4JHBsIT0VQEE:-Myjw9sg42pVMBF8cXv1:b-dw8f0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/catpb/catalog.proto#L241)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Technically, `RowLevelTTL` are also table-level settings. Perhaps it would be preferable to rename this message type (and its corresponding field in the table descriptor) to TableAutomaticStatsCollectionSettings or something?
</blockquote></details>

Good point.  What I'm trying to do here is group together all cluster settings that are also applicable as table-level settings, which we could add to in the future.  I've renamed this to `ClusterSettingsForTable`.
___
*[pkg/sql/catalog/descpb/structured.go, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygxvm_DMksN5dlrTgz:-Myk1xkMErsk8pCyDdqr:b-cyhrjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L281)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

+1, I think one boolean is fine with true for enabled and false for disabled/no setting.
</blockquote></details>

We have to distinguish between disabled and no setting because disabled overrides an enabled setting at the cluster level (for the given table), whereas no setting does not.  We pass the table-level setting out, then the caller can see if a value is set, and use that to override the cluster setting.



_Code quote:_
```Go
func (desc *TableDescriptor) AutoStatsCollectionEnabled() (enabled bool, ok bool) {
```
___
*[pkg/sql/catalog/descpb/structured.go, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyiPPa2DjSPIHWaORgL:-Myk2_3z4p9jsqapzq9q:b-hrwl5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L288)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should we also consider whether auto stats is enabled overall?
</blockquote></details>

The intent here is to just return the table-level setting then let the caller decide how to use that value (in this case, use the table-level setting, if available, and only if not set defer to the cluster-level setting).  The current design of auto stats tries to continue or break out of the main loop if the cluster setting value has changed since the mutations were recorded:
https://gist.github.com/msirek/c2cfae90384fa4a398e8ad727dda5e59
Combining the cluster setting and the table-level setting here would write the result into the `Refresher.autoStatsEnabled` map when the mutations are recorded and then if we didn't check the cluster setting again in this loop there would be some lag time in the cluster setting taking effect.
___
*[pkg/sql/catalog/descpb/structured.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyhVMDF-T9YH4S37uNz:-Myk8Z8K5hnR99FeZ3OE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L296)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could dedupe some code with `AutoStatsCollectionEnabled`
</blockquote></details>

Done.



_Code quote:_
```Go
AutoStatsMinStaleRows
```
___
*[pkg/sql/catalog/descpb/structured.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyhVqaJ4396Oz31T9W9:-Myk8nKL-JJr5PSdAxtI:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L310)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could dedupe here, too
</blockquote></details>

Done
___
*[pkg/sql/catalog/descpb/structured.go, line 317 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MygwGsY2uNPX1WOrd7p:-MykH33dCLEjq12NDnd5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L317)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Can you define these methods in the `catalog.TableDescriptor` interface please?
</blockquote></details>

Done.



_Code quote:_
```Go
AutoStatsFractionStaleRows()
```
___
*[pkg/sql/catalog/descpb/structured.proto, line 1201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyhWDC-6B28BofYNqX6:-MykHRy0EgWSNqjOMqcU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cdc505b79cde668e10d7a62109f4df313eda754/pkg/sql/catalog/descpb/structured.proto#L1201)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Keep comment and increment id.
</blockquote></details>

Done.



_Code quote:_
```protobuf
// Next ID: 51
```
___
*[pkg/sql/catalog/tabledesc/structured.go, line 2573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygr_uUBn_ZrsQTdFpd:-MykI0TgBfXwBD33xvql:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/tabledesc/structured.go#L2573)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: `if settings := desc.TableLevelSettings; settings != nil {` would be more idiomatic
</blockquote></details>

Done.



_Code quote:_
```Go
appendStorageParam(`exclude_data_from_backup`, `true`)
```
___
*[pkg/sql/catalog/table [...]

2022-03-23 02:04 UTC, rytaft reviewed
Awesome! It sounds like people are generally on board with merging this in 22.1.0. Seems best not to wait until 22.1.1 because of the descriptor changes etc. One option is to split the descriptor/protobuf changes out into a separate commit and backport only those changes for 22.1.0 and do the others later, but after reviewing the PR I think I'd rather just keep this all together. The remaining changes are pretty minimal.

> Reviewed 2 of 10 files at r1, 3 of 14 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-MyoUQ7Y7TsEK5K9BjwD:b-jsroa4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @postamar, and @rharding6373)

___
*[-- commits, line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoF7brCsaGQFGYWGI_):*
nit: some of these lines have tabs and some don't
___
*[-- commits, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoFAqv8A5IrOQ_L9xq):*
Looks like this line is copy pasta. Can you just remove it?
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1548 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoIN7zDIzt62SR4Xi1:-MyoIN8-1bJtbNwQNMEr:ba85lke) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/validate.go#L1548)):*
> ```Go
> 		desc.verifyProperTableForStatsSetting(errReportFn, settingName)
> 		if err :=
> 			validateFunc(*value); err != nil {
> ```

nit: this can all go on one line
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1562 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoIQk13IqY_LMKFSET:-MyoIQk13IqY_LMKFSEU:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/validate.go#L1562)):*
> ```Go
> 	if value != nil {
> 		desc.verifyProperTableForStatsSetting(errReportFn, settingName)
> 		if err :=
> ```

ditto
___
*[pkg/sql/stats/automatic_stats.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoLRQSB2UWPQiRXBaI:-MyoLRQT2eYtOaw5F67C:b-686oz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L213)):*
> ```Go
> 
> 	// autoStatsEnabled is true if auto stats collection is explicitly enabled for
> 	// the given table, which may override the cluster setting.
> ```

nit: mention it could also be explicitly disabled
___
*[pkg/sql/stats/automatic_stats.go, line 233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoPkyu9DXyypTnazNh:-MyoPkyu9DXyypTnazNi:bb6chta) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L233)):*
> ```Go
> 	autoStatsEnabled           *bool
> 	autoStatsFractionStaleRows *float64
> 	autoStatsMinStaleRows      *int64
> ```

What's the benefit of including these settings in this struct? I think it would be better to check them only when needed.
___
*[pkg/sql/stats/automatic_stats.go, line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoQes068bjHrN6F6g9:-MyoQes16QQWzxB2PVjT:b-142md7) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L258)):*
> ```Go
> 		autoStatsEnabled:           make(map[descpb.ID]bool),
> 		autoStatsFractionStaleRows: make(map[descpb.ID]float64),
> 		autoStatsMinStaleRows:      make(map[descpb.ID]int64),
> ```

I'm not really convinced we should be storing these values at all -- we should probably just be grabbing the value from the descriptor when it's needed
___
*[pkg/sql/stats/automatic_stats.go, line 391 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoN0JB5-hTJP6x2o0w:-MyoN0JB5-hTJP6x2o0x:b-1ca2qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L391)):*
> ```Go
> 		getTablesWithAutoStatsExplicitlyEnabledQuery := fmt.Sprintf(
> 			`
> SELECT
> ```

Do you have some tests that exercise this query?
___
*[pkg/sql/stats/automatic_stats.go, line 438 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoOndxD4xkUzCMOZuK:-MyoOndxD4xkUzCMOZuL:b-5darfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L438)):*
> ```Go
> 			// call to this method).
> 			log.Errorf(ctx, "failed to get tables for automatic stats: %v", err)
> 		}
> ```

nit: this feels like a lot of code duplication with what's below. Not sure if it's possible to remove, but maybe there's an opportunity to avoid it?
___
*[pkg/sql/stats/automatic_stats.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoQ1Fj1_FYVhG7esb9:-MyoQ1Fj1_FYVhG7esbA:b2449sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L529)):*
> ```Go
> 	if fractionStaleRows, ok := table.TableDesc().AutoStatsFractionStaleRows(); ok {
> 		fractionStaleRowsForTable = &fractionStaleRows
> 	}
> ```

NotifyMutation is a hot path. We don't need these settings here, so I'd rather not get them until later
___
*[pkg/sql/catalog/tabledesc/validate_test.go, line 2207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoTE9u-KwhZh4YIo4z:-MyoTE9u-KwhZh4YIo5-:b-50vk8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/validate_test.go#L2207)):*
> ```Go
> 		// Views.
> 		{ // 10
> 			err: ``,
> ```

you shouldn't need to set this -- empty string is the default in go
___
*[pkg/sql/catalog/tabledesc/validate_test.go, line 2300 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoTOtG2jcrsLQCl8MO:-MyoTOtG2jcrsLQCl8MP:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/validate_test.go#L2300)):*
> ```Go
> 		},
> 		{ // 13
> 			err:      ``,
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-03-23 16:33 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @postamar, @rharding6373, and @rytaft)

___
*[-- commits, line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoF7brCsaGQFGYWGI_):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: some of these lines have tabs and some don't
</blockquote></details>

Removed the tabs.
___
*[-- commits, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoFAqv8A5IrOQ_L9xq):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Looks like this line is copy pasta. Can you just remove it?
</blockquote></details>

Done.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1548 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoIN7zDIzt62SR4Xi1:-MypJ1oU7nFYZZdGxQlE:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/validate.go#L1548)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: this can all go on one line
</blockquote></details>

Fixed



_Code quote:_
```Go
desc.verifyProperTableForStatsSetting(errReportFn, settingName)
```
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1562 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoIQk13IqY_LMKFSET:-MypJ3MgEeK-cbXUl_k7:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/validate.go#L1562)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed
___
*[pkg/sql/stats/automatic_stats.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoLRQSB2UWPQiRXBaI:-MypJPHz932KWNEaWxIy:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L213)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: mention it could also be explicitly disabled
</blockquote></details>

Added.



_Code quote:_
```Go
autoStatsEnabled is true if auto stats collection is explicitly enabled
```
___
*[pkg/sql/stats/automatic_stats.go, line 233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoPkyu9DXyypTnazNh:-MyrKR492nKMCGITkJlr:bpgbky2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L233)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

What's the benefit of including these settings in this struct? I think it would be better to check them only when needed.
</blockquote></details>

The benefit is that if we don't save this information in `mutation`, `maybeRefreshStats` would have to look up the table descriptor to get the table-level settings.  This information is already available in `NotifyMutation`.
___
*[pkg/sql/stats/automatic_stats.go, line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoQes068bjHrN6F6g9:-MyrKwOn7zcvKluK7vAb:b-boje07) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L258)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm not really convinced we should be storing these values at all -- we should probably just be grabbing the value from the descriptor when it's needed
</blockquote></details>

What do you think the overhead would be of looking up the table descriptor when each mutation is processed in `maybeRefreshStats`?  That's the only thing I was worried about, extra overhead.  The trade-off here is that we're using more memory to create hash maps.  So far I'm having trouble locating a function that can look up a `TableDescriptor` using a TableID.  Please let me know if there is one.  If the TableDescriptor can't be looked up in `maybeRefreshStats`, the only way I know of to get this information is within `NotifyMutation`, and then save it away somewhere for later processing.


<!-- Sent from Reviewable.io -->

2022-03-23 17:19 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/stats/automatic_stats.go, line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoQes068bjHrN6F6g9:-Myrm6O330Ed2dJMjw8P:b4s47ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L258)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

What do you think the overhead would be of looking up the table descriptor when each mutation is processed in `maybeRefreshStats`?  That's the only thing I was worried about, extra overhead.  The trade-off here is that we're using more memory to create hash maps.  So far I'm having trouble locating a function that can look up a `TableDescriptor` using a TableID.  Please let me know if there is one.  If the TableDescriptor can't be looked up in `maybeRefreshStats`, the only way I know of to get this information is within `NotifyMutation`, and then save it away somewhere for later processing.
</blockquote></details>

Actually we wouldn't have to look up the TableDescriptor on every mutation, just when `maybeRefreshStats` gets called.  I'm still wondering if this could cause noticeable overhead. 


<!-- Sent from Reviewable.io -->

2022-03-23 17:25 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @postamar, @rharding6373, and @rytaft)

___
*[-- commits, line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoF7brCsaGQFGYWGI_):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Removed the tabs.
</blockquote></details>

Doesn't look like you pushed the latest update
___
*[pkg/sql/stats/automatic_stats.go, line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoQes068bjHrN6F6g9:-MyrmRu5Dr_CJ5jh_4Jg:b-duuxgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L258)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Actually we wouldn't have to look up the TableDescriptor on every mutation, just when `maybeRefreshStats` gets called.  I'm still wondering if this could cause noticeable overhead. 
</blockquote></details>

Right -- `NotifyMutation` is called much more frequently than `maybeRefreshStats`. I think `maybeRefreshStats` is called at most once per minute per table. But that's a good point that the table descriptor isn't readily available... maybe the schema team knows a good way to get it?


<!-- Sent from Reviewable.io -->

2022-03-23 18:36 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @postamar, @rharding6373, and @rytaft)

___
*[-- commits, line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoF7brCsaGQFGYWGI_):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Doesn't look like you pushed the latest update
</blockquote></details>

Yeah, I'm in the middle of changes, but wanted to get my comment posted about the table descriptor.
___
*[pkg/sql/stats/automatic_stats.go, line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoQes068bjHrN6F6g9:-Mys2uhn-jAA_TaX3GnB:b-p7c707) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L258)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Right -- `NotifyMutation` is called much more frequently than `maybeRefreshStats`. I think `maybeRefreshStats` is called at most once per minute per table. But that's a good point that the table descriptor isn't readily available... maybe the schema team knows a good way to get it?
</blockquote></details>

Thanks, the schema team told me how to get it. Adding the code now.


<!-- Sent from Reviewable.io -->

2022-03-23 18:57 UTC, mgartner requested changes
> Reviewed 2 of 10 files at r1, 3 of 14 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @postamar, @rharding6373, and @rytaft)

___
*[-- commits, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyrsfJA6W23BnwG-vSy):*
It's very useful to know how to view settings for a table, but I don't think a `crdb_internal` function belongs in a release note - they are generally not meant for users. A statement like `SHOW SETTING FOR TABLE t` would certainly be nice. Do you mind creating an issue to add a statement? cc @vy-ton for visibility.
___
*[pkg/settings/cluster/cluster_settings.go, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyrvOk5-d_iQwYrlFwZ:-MyrvOk5-d_iQwYrlFw_:bnda5nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/settings/cluster/cluster_settings.go#L84)):*
> ```Go
> 	// AutoStatsClusterSettingName is the name of the automatic stats collection
> 	// enabled cluster setting.
> 	AutoStatsClusterSettingName = "sql.stats.automatic_collection.enabled"
> ```

nit: `cluster.AutoStatsClusterSettingName` is redundant. Is `AutoStatsEnabledSettingName` a better name?
___
*[pkg/sql/catalog/catpb/catalog.proto, line 231 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Myrtb0a575bwjR03qaw:-Myrtb0a575bwjR03qax:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/catpb/catalog.proto#L231)):*
> ```protobuf
> }
> ```

nit: remove blank line
___
*[pkg/sql/catalog/descpb/structured.go, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygxvm_DMksN5dlrTgz:-MyrujGR37xUPJhVyUMs:b-dqfhve) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L281)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

We have to distinguish between disabled and no setting because disabled overrides an enabled setting at the cluster level (for the given table), whereas no setting does not.  We pass the table-level setting out, then the caller can see if a value is set, and use that to override the cluster setting.
</blockquote></details>

You could return an enum representing the three states. `tree.Nullability` is a good example: https://github.com/cockroachdb/cockroach/blob/9c2434a23d1830e6cf1d403a7e61d0303985de58/pkg/sql/sem/tree/create.go#L386-L395
___
*[pkg/sql/catalog/tabledesc/structured.go, line 2606 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mys3WQW9tOX8G69f1VE:-Mys3WQW9tOX8G69f1VF:b-5jz2ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/structured.go#L2606)):*
> ```Go
> 
> // NoClusterSettingsForTable implements the TableDescriptor interface.
> func (desc *wrapper) NoClusterSettingsForTable() bool {
> ```

nit: the name of this is confusing because a "cluster setting" and "table setting" are two different concepts. Maybe `NoClusterSettingOverrides` is better?
___
*[pkg/sql/paramparse/paramobserver.go, line 592 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mys69-4Aw-sC93zzqx6:-Mys69-4Aw-sC93zzqx7:bwwi3od) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/paramparse/paramobserver.go#L592)):*
> ```Go
> 	}
> 	*setting = boolVal
> 	return nil
> ```

This generalization adds a lot of complexity that's hard to follow. If the double pointers and such can't be simplified, I'd prefer declaring the `onSet` and `onReset` functions directly as anonymous functions, even if there is some repetition:

```go
cluster.AutoStatsClusterSettingName: {
  onSet: func (ctx context.Context, po *TableStorageParamObserver, semaCtx *tree.SemaCtx,
    evalCtx *tree.EvalCtx, key string, datum tree.Datum) error {
      boolVal, err := boolFromDatum(evalCtx, key, datum)
      if err != nil {
        return err
      }
      if po.tableDesc.ClusterSettingsForTable == nil {
        po.tableDesc.ClusterSettingsForTable = &catpb.ClusterSettingsForTable{}
      }
    po.tableDesc.ClustSettingsForTable.SqlStatsAutomaticCollectionEnabled = &boolVal
    return nil
  },
},
// ...
```
___
*[pkg/sql/stats/automatic_stats.go, line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyrwfEq89DQbdfb54Qc:-MyrwfEq89DQbdfb54Qd:b-jvrp8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L321)):*
> ```Go
> 								// remaining mutations in the autoStatsEnabledForTable map.
> 								if len(autoStatsEnabledForTable) == 0 {
> 									break
> ```

nit: reduce nested blocks by moving this check into its own block before the lookup in `autoStatsEnabledForTable`, like:

```go
if len(autoStatsEnabledForTable) == 0 && !AutomaticStatisticsClusterMode.Get(&r.st.SV) {
    break
}
if enabled, ok := autoStatsEnabledForTable[tableID]; ok {
    // ...
}
```
___
*[pkg/sql/stats/automatic_stats.go, line 437 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyrxxmTBGzAaHo07BH5:-MyrxxmTBGzAaHo07BH6:bo79jb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L437)):*
> ```Go
> 			// entry is idempotent (i.e. we didn't mess up anything for the next
> 			// call to this method).
> 			log.Errorf(ctx, "failed to get tables for automatic stats: %v", err)
> ```

nit: place the `if err != nil { }` before the successful code path, with an early `return`. That will eliminate the need for nesting the successful path in `if err == nil { }`.
___
*[pkg/sql/stats/automatic_stats.go, line 613 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyryYznD_la8mjZlPYr:-MyryYznD_la8mjZlPYs:bisqqha) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L613)):*
> ```Go
> 	}
> 	statsMinStaleRows := AutomaticStatisticsMinStaleRows.Get(&r.st.SV)
> 	if minStaleRowsForTable != nil {
> ```

There's quite a few places with a similar check, e.g., "use a table-level setting if set, use the cluster setting if not". It'd be nice to encapsulate this in an API that encapsulates this repetitive logic.
___
*[pkg/sql/catalog/tabledesc/validate_test.go, line 2403 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mys24ZtBSJqt37Ckc1g:-Mys24ZtBSJqt37Ckc1h:b-mt4qsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/validate_test.go#L2403)):*
> ```Go
> 			}
> 			// Validate other descriptors for specific test cases.
> 			if test.testName == "Stats setting in view" {
> ```

Why do you need this and `test.otherErr`? Can you instead follow the pattern in the other view test cases and make `desc` the view and put the `foo` table in `otherDescs`?
___
*[pkg/sql/stats/automatic_stats_test.go, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mys2hXg9snc8mioIlaP:-Mys2hXg9snc8mioIlaQ:be8xwmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats_test.go#L88)):*
> ```Go
> 		ctx, s.Stopper(), descA.GetID(), 0 /* rowsAffected */, time.Microsecond, /* asOf */
> 		false,                                    /* enabledForTable */
> 		nil /* fractionStaleRowsForTable */, nil, /* minStaleRowsForTable */
> ```

nit: put each argument on its own line here an in the same cases below


<!-- Sent from Reviewable.io -->

2022-03-23 19:33 UTC, vy-ton reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, @postamar, @rharding6373, and @rytaft)

___
*[-- commits, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyrsfJA6W23BnwG-vSy):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's very useful to know how to view settings for a table, but I don't think a `crdb_internal` function belongs in a release note - they are generally not meant for users. A statement like `SHOW SETTING FOR TABLE t` would certainly be nice. Do you mind creating an issue to add a statement? cc @vy-ton for visibility.
</blockquote></details>

+1 to filing a future issue. You can see configured storage parameters with `SHOW CREATE TABLE` and `pg_class`. 

I had a [related observation](https://cockroachlabs.slack.com/archives/C028YAH6Y3V/p1646949514660929) while testing row-level TTL


<!-- Sent from Reviewable.io -->

2022-03-23 20:00 UTC, mgartner commented
___
*[-- commits, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyrsfJA6W23BnwG-vSy):*
> but I don't think a crdb_internal function belongs in a release note - they are generally not meant for users

To be more clear: `crdb_internal` functions are not mean for users, release notes _are_ meant for users.


<!-- Sent from Reviewable.io -->

2022-03-24 06:28 UTC, msirek reviewed
Thanks!  Sounds good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-Mytbyw95YzOy42sdPUZ:b-85ng3c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @postamar, @rharding6373, @rytaft, and @vy-ton)

___
*[-- commits, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyrsfJA6W23BnwG-vSy):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> but I don't think a crdb_internal function belongs in a release note - they are generally not meant for users

To be more clear: `crdb_internal` functions are not mean for users, release notes _are_ meant for users.
</blockquote></details>

OK, I've created issue #78395 and removed the query from the release note.
___
*[pkg/settings/cluster/cluster_settings.go, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyrvOk5-d_iQwYrlFwZ:-Myswsmy5zPYzfpoHadb:b-7uqqfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/settings/cluster/cluster_settings.go#L84)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `cluster.AutoStatsClusterSettingName` is redundant. Is `AutoStatsEnabledSettingName` a better name?
</blockquote></details>

Changed as suggested.
___
*[pkg/sql/catalog/catpb/catalog.proto, line 231 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Myrtb0a575bwjR03qaw:-Mysx9QqBq-xLSmiml28:b-z674b1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/catpb/catalog.proto#L231)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: remove blank line
</blockquote></details>

Done, and also added `SessionSettingsForTable`, referenced in `message TableDescriptor` in case we want to set things like `optimizer_use_histograms` or `optimizer_use_multicol_stats` at the table level in the future.



_Code quote:_
```protobuf
ClusterSettingsForTable
```
___
*[pkg/sql/catalog/descpb/structured.go, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygxvm_DMksN5dlrTgz:-Mystz-w3LcSXXeghukX:b-4p5xkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/descpb/structured.go#L281)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You could return an enum representing the three states. `tree.Nullability` is a good example: https://github.com/cockroachdb/cockroach/blob/9c2434a23d1830e6cf1d403a7e61d0303985de58/pkg/sql/sem/tree/create.go#L386-L395
</blockquote></details>

Thanks.  Added `cluster.BoolSetting`
https://gist.github.com/msirek/bb9963e322d8037ae461b1a6cf0e4482



_Code quote:_
```Go
AutoStatsCollectionEnabled
```
___
*[pkg/sql/catalog/tabledesc/structured.go, line 2606 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mys3WQW9tOX8G69f1VE:-Mysw3gBDo2m4L-fgpBo:b-ftkfr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/structured.go#L2606)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: the name of this is confusing because a "cluster setting" and "table setting" are two different concepts. Maybe `NoClusterSettingOverrides` is better?
</blockquote></details>

Changed to `NoClusterSettingOverrides`
___
*[pkg/sql/paramparse/paramobserver.go, line 592 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mys69-4Aw-sC93zzqx6:-MytCQU07_DhDVt1w8X-:b-q9mzko) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/paramparse/paramobserver.go#L592)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This generalization adds a lot of complexity that's hard to follow. If the double pointers and such can't be simplified, I'd prefer declaring the `onSet` and `onReset` functions directly as anonymous functions, even if there is some repetition:

```go
cluster.AutoStatsClusterSettingName: {
  onSet: func (ctx context.Context, po *TableStorageParamObserver, semaCtx *tree.SemaCtx,
    evalCtx *tree.EvalCtx, key string, datum tree.Datum) error {
      boolVal, err := boolFromDatum(evalCtx, key, datum)
      if err != nil {
        return err
      }
      if po.tableDesc.ClusterSettingsForTable == nil {
        po.tableDesc.ClusterSettingsForTable = &catpb.ClusterSettingsForTable{}
      }
    po.tableDesc.ClustSettingsForTable.SqlStatsAutomaticCollectionEnabled = &boolVal
    return nil
  },
},
// ...
```

</blockquote></details>

I agree, the splitting of logic between the two functions was not ideal.  I cleaned it up by putting the set/reset logic directly in new functions `setBoolValue`, `setIntValue`, `setFloatValue` and `resetValue`. I think having generalized functions will make adding new settings easier and less error prone.
___
*[pkg/sql/stats/automatic_stats.go, line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyrwfEq89DQbdfb54Qc:-MytKPb1BpeSQEFkH1Oe:bjetrh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L321)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: reduce nested blocks by moving this check into its own block before the lookup in `autoStatsEnabledForTable`, like:

```go
if len(autoStatsEnabledForTable) == 0 && !AutomaticStatisticsClusterMode.Get(&r.st.SV) {
    break
}
if enabled, ok := autoStatsEnabledForTable[tableID]; ok {
    // ...
}
```
</blockquote></details>

This has been refactored to remove the `autoStatsEnabledForTable` map.
___
*[pkg/sql/stats/automatic_stats.go, line 391 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoN0JB5-hTJP6x2o0w:-MyuRjRA3IOrKzM1VX58:b-77xip2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L391)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you have some tests that exercise this query?
</blockquote></details>

I had some similar queries in logic tests, but not this exact query.  I've added function `TestEnsureAllTablesQueries` to test it.
___
*[pkg/sql/stats/automatic_stats.go, line 437 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyrxxmTBGzAaHo07BH5:-MytLCNf5TuMhEhwlkZd:b-3hlgz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L437)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: place the `if err != nil { }` before the successful code path, with an early `return`. That will eliminate the need for nesting the successful path in `if err == nil { }`.
</blockquote></details>

This pre-existing code has two places it's checking for errors: on creation of the query iterator and in the row reading loop.  The comment indicates it's letting the row reading loop proceed as far as it can error-free, so if we did an early return that would change the current behavior.
___
*[pkg/sql/stats/automatic_stats.go, line 438 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoOndxD4xkUzCMOZuK:-MytLU4a9Y34XZtaU7hQ:b-exz4jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/stats/automatic_stats.go#L438)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: this feels like a lot of code duplication with what's below. Not sure if it's possible to remove, but maybe there's an opportunity to avoid it?
</blockquote></details>

Defined the SQL as a template with a pluggable predicate.
___
*[pkg/s [...]

2022-03-24 14:14 UTC, msirek commented
@mgartner @vy-ton I posted a comment in Reviewable referencing the issue I opened, but the comment seems to have disappeared, along with your original request for the issue.  Here is the issue I opened: #78395

2022-03-24 16:33 UTC, msirek commented
Running into the error in https://github.com/cockroachdb/cockroach/pull/78431
Will rebase once it's merged.

2022-03-24 21:55 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice work! Want to add the backport-22.1 label?

> Reviewed 19 of 19 files at r15, 41 of 41 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-Myxumg978vn5O5WMVTj:b-23g7jq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @mgartner, @msirek, @postamar, and @rharding6373)

___
*[pkg/sql/stats/automatic_stats.go, line 279 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyxsB-1CGdXPsRMjbZZ:-MyxsB-1CGdXPsRMjbZ_:bwoujfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L279)):*
> ```Go
> }
> 
> func (r *Refresher) autoStatsEnabled(ctx context.Context, tableID descpb.ID) bool {
> ```

nit: it's a bit confusing that this function is just a shorter name of the previous one. If you can't combine them, maybe call one `autoStatsEnabled` and the other `autoStatsEnabledFromDescriptor` or something
___
*[pkg/sql/stats/automatic_stats.go, line 417 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Myxt3yh6LCVyNHXEMrf:-Myxt3yh6LCVyNHXEMrg:b-gker8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L417)):*
> ```Go
> 	)`
> 
> 	autoStatsEnableOrNotSpecifiedPredicate = `AND 
> ```

nit: autoStatsEnableOrNotSpecifiedPredicate -> autoStatsEnabledOrNotSpecifiedPredicate ("Enabled" instead of "Enable")
___
*[pkg/sql/stats/automatic_stats.go, line 573 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyxuvTJ56UJC5ONDdt-:-MyxuvTJ56UJC5ONDdt0:b-l01mh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L573)):*
> ```Go
> 
> 	statsFractionStaleRows := r.autoStatsFractionStaleRows(ctx, tableID)
> 	statsMinStaleRows := r.autoStatsMinStaleRows(ctx, tableID)
> ```

Is there any downside to calling `getTableDescriptor()` twice as a result of this? I don't know how expensive that call is.


<!-- Sent from Reviewable.io -->

2022-03-25 00:47 UTC, msirek reviewed
Thanks.  Should I wait to add the label until I know I have no more code changes?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-MyyTKnJ-MlKy-Rcvf3A:box22na)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/stats/automatic_stats.go, line 279 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyxsB-1CGdXPsRMjbZZ:-MyxxSSoDLIrrHo-X53S:b3gi2zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L279)):*
> autoStatsEnabledFromDescriptor

The function that takes a tableID has gone away (see below), so just using the name `autoStatsEnabled` now.
___
*[pkg/sql/stats/automatic_stats.go, line 417 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Myxt3yh6LCVyNHXEMrf:-Myxxdi9BIK8Jp3DxEqb:b-btxecn) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L417)):*
> autoStatsEnabledOrNotSpecifiedPredicate

Fixed.
___
*[pkg/sql/stats/automatic_stats.go, line 573 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyxuvTJ56UJC5ONDdt-:-MyyJhOX614j1V5KyHUB:b-sb3xdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L573)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is there any downside to calling `getTableDescriptor()` twice as a result of this? I don't know how expensive that call is.
</blockquote></details>

I don't know how expensive `maybeRefreshStats` is compared to all surrounding operations, but getting the table descriptor seems to take up most of the time within this function.  I wrote a benchmark for it, and combining these 2 lookups into one lookup basically cuts the time in half:
```
make bench PKG=./pkg/sql/stats BENCHES=BenchmarkMaybeRefreshStats TESTFLAGS="-count=5 -cpu=1,2,4,8,16"

name                                             old time/op  new time/op  delta
MaybeRefreshStats/BenchmarkMaybeRefreshStats     82.2ms ± 9%  40.7ms ± 1%  -50.49%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-2   68.6ms ± 3%  35.5ms ± 2%  -48.25%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-4   68.8ms ± 5%  34.4ms ± 3%  -50.02%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-8   71.3ms ± 2%  35.7ms ± 1%  -50.01%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-16  73.6ms ± 5%  37.0ms ± 4%  -49.78%  (p=0.008 n=5+5)

```
Not surprisingly, if `makeRefreshStats` is modified to pass in the `TableDescriptor` so that it doesn't have to be looked up at all, its performance improves even more:
```
name                                             old time/op  new time/op  delta
MaybeRefreshStats/BenchmarkMaybeRefreshStats     82.2ms ± 9%   1.5ms ± 1%  -98.22%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-2   68.6ms ± 3%   1.5ms ± 1%  -97.86%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-4   68.8ms ± 5%   1.5ms ± 1%  -97.87%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-8   71.3ms ± 2%   1.5ms ± 3%  -97.93%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-16  73.6ms ± 5%   1.5ms ± 2%  -97.97%  (p=0.008 n=5+5)
```

This is probably a significant enough speedup to warrant getting the table descriptor only once (instead of 3 times per `mutation`).  I've gone ahead and made this change.  I wish we didn't have to look up the table descriptor at all, but I guess it's required.


<!-- Sent from Reviewable.io -->

2022-03-25 19:35 UTC, postamar requested changes
> Reviewed 9 of 9 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @msirek, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/catpb/catalog.proto, line 238 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Ut6nA3Uv2VEhIU1F:-Mz1Ut6nA3Uv2VEhIU1G:b37g1yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/catalog/catpb/catalog.proto#L238)):*
> ```protobuf
> message SessionSettingsForTable {
>   option (gogoproto.equal) = true;
> }
> ```

suggestion: don't bother with this
___
*[pkg/sql/catalog/descpb/structured.go, line 279 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1WSm010733BY8fkAd:-Mz1WSm010733BY8fkAe:b-fg1qfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/catalog/descpb/structured.go#L279)):*
> ```Go
> // AutoStatsCollectionEnabled indicates if automatic statistics collection is
> // explicitly enabled or disabled for this table.
> func (desc *TableDescriptor) AutoStatsCollectionEnabled() cluster.BoolSetting {
> ```

We need to be careful about the `descpb` package's dependencies, and this requires we pull in a new one. Can you move these methods you added to the `tabledesc` package instead?

You don't actually need to define these methods on `descpb.TableDescriptor` because that struct does not implement the `catalog.TableDescriptor` interface on its own, instead it's embedded in the `wrapper` struct in `tabledesc`.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1510 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygq7JH-LyStgoTLG8_:-Mz1YTp5DRQftsWsy_Vj:bs3aqca) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/tabledesc/validate.go#L1510)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Thanks, modified it to pass `vea.Report` as a parameter and report on all errors.
</blockquote></details>

I meant to say: you can pass the `ValidationErrorAccumulator` interface. It's basically the same thing as as `func(error)` callback. Sorry for not being clearer.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1562 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1ZnKmACXghY-ymQMO:-Mz1ZnKmACXghY-ymQMP:bjgkm5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/catalog/tabledesc/validate.go#L1562)):*
> ```Go
> 		desc.verifyProperTableForStatsSetting(errReportFn, settingName)
> 		if err := validateFunc(*value); err != nil {
> 			errReportFn(errors.Wrapf(err, "invalid value for %s", settingName))
> ```

nit: `s/invalid value/invalid float value/` perhaps? 

comment applies elsewhere also
___
*[pkg/sql/stats/automatic_stats.go, line 573 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyxuvTJ56UJC5ONDdt-:-Mz1RUOD643dwHOJoHi6:b-md10ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L573)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I don't know how expensive `maybeRefreshStats` is compared to all surrounding operations, but getting the table descriptor seems to take up most of the time within this function.  I wrote a benchmark for it, and combining these 2 lookups into one lookup basically cuts the time in half:
```
make bench PKG=./pkg/sql/stats BENCHES=BenchmarkMaybeRefreshStats TESTFLAGS="-count=5 -cpu=1,2,4,8,16"

name                                             old time/op  new time/op  delta
MaybeRefreshStats/BenchmarkMaybeRefreshStats     82.2ms ± 9%  40.7ms ± 1%  -50.49%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-2   68.6ms ± 3%  35.5ms ± 2%  -48.25%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-4   68.8ms ± 5%  34.4ms ± 3%  -50.02%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-8   71.3ms ± 2%  35.7ms ± 1%  -50.01%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-16  73.6ms ± 5%  37.0ms ± 4%  -49.78%  (p=0.008 n=5+5)

```
Not surprisingly, if `makeRefreshStats` is modified to pass in the `TableDescriptor` so that it doesn't have to be looked up at all, its performance improves even more:
```
name                                             old time/op  new time/op  delta
MaybeRefreshStats/BenchmarkMaybeRefreshStats     82.2ms ± 9%   1.5ms ± 1%  -98.22%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-2   68.6ms ± 3%   1.5ms ± 1%  -97.86%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-4   68.8ms ± 5%   1.5ms ± 1%  -97.87%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-8   71.3ms ± 2%   1.5ms ± 3%  -97.93%  (p=0.008 n=5+5)
MaybeRefreshStats/BenchmarkMaybeRefreshStats-16  73.6ms ± 5%   1.5ms ± 2%  -97.97%  (p=0.008 n=5+5)
```

This is probably a significant enough speedup to warrant getting the table descriptor only once (instead of 3 times per `mutation`).  I've gone ahead and made this change.  I wish we didn't have to look up the table descriptor at all, but I guess it's required.
</blockquote></details>

You're absolutely on the right track here: table descriptor lookups are expensive. Well, to be precise, it's querying the `system.descriptor` table which is expensive, because it incurs a round-trip to the KV layer. This is in addition to the overhead incurred by opening a transaction. This is all a function of network latency between cluster nodes, so, tens or even hundreds of milliseconds.

Of course, as a consequence, we do a lot of in-memory caching, this is one of the main purposes of `descs.Collection`.

As an aside: schema changes involve a lot of these round-trips and we have benchmarks in `rttanalysis` and `rttanalysisccl` which measure performance solely in terms of number of round-trips.
___
*[pkg/sql/stats/automatic_stats.go, line 340 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1OJGFA4FjzYi4Mi5W:-Mz1OJGFA4FjzYi4Mi5X:b87s313) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/stats/automatic_stats.go#L340)):*
> ```Go
> 						}
> 
> 						for tableID, rowsAffected := range mutationCounts {
> ```

It seems that this map may comprise a lot of entries for which `rowsAffected == 0`, should these be skipped?
___
*[pkg/sql/stats/automatic_stats.go, line 345 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Jnrb7F8h7w_cGhk-:-Mz1Jnrb7F8h7w_cGhk0:b5yet6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/stats/automatic_stats.go#L345)):*
> ```Go
> 							var desc catalog.TableDescriptor
> 							var err error
> 							if desc, err = r.getTableDescriptor(ctx, tableID); err != nil {
> ```

This opens a transaction and does a descriptor point-lookup in each iteration. This is undesirable, each of these operations incur significant overhead.

I suggest you break down `mutationCounts` into batches with a constant max size (1000 is fairly typical in these kinds of situations) and loop over these instead. In the inner loop, open a transaction and do a batch descriptor lookup using the `GetImmutableDescriptorsByID` method on `*descs.Collection`. Outside of the transaction you may loop over the resulting slice and cast each descriptor to `catalog.TableDescriptor` using `catalog.AsTableDescriptor` and proceed to `maybeRefreshStats`.

I'm sorry I didn't notice this earlier. 


<!-- Sent from Reviewable.io -->

2022-03-25 19:54 UTC, rytaft reviewed
> Should I wait to add the label until I know I have no more code changes?

No, the label won't be used by blathers until this PR is merged

> Reviewed 9 of 9 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-Mz1cblwCkzfDCrG4s9U:b-j9yi2g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @msirek, @postamar, and @rharding6373)

___
*[pkg/sql/stats/automatic_stats.go, line 340 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1OJGFA4FjzYi4Mi5W:-Mz1a6IwAyMCRg_nQHDj:bfkukcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/stats/automatic_stats.go#L340)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

It seems that this map may comprise a lot of entries for which `rowsAffected == 0`, should these be skipped?
</blockquote></details>

No -- if it has been a while since the stats for a table are updated, we will still force a refresh. And this will only include rows with `rowsAffected == 0` at process startup.
___
*[pkg/sql/stats/automatic_stats.go, line 345 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Jnrb7F8h7w_cGhk-:-Mz1aIBCBpAgLETGyF-6:b-kgrgdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/stats/automatic_stats.go#L345)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This opens a transaction and does a descriptor point-lookup in each iteration. This is undesirable, each of these operations incur significant overhead.

I suggest you break down `mutationCounts` into batches with a constant max size (1000 is fairly typical in these kinds of situations) and loop over these instead. In the inner loop, open a transaction and do a batch descriptor lookup using the `GetImmutableDescriptorsByID` method on `*descs.Collection`. Outside of the transaction you may loop over the resulting slice and cast each descriptor to `catalog.TableDescriptor` using `catalog.AsTableDescriptor` and proceed to `maybeRefreshStats`.

I'm sorry I didn't notice this earlier. 
</blockquote></details>

The size of `mutationCounts` is bounded by the number of tables in the database, so maybe we can just call `GetImmutableDescriptorsByID` once outside the loop?

Otherwise, if this is going to be too complicated / expensive, maybe we should just go back to @msirek's previous approach of getting the settings in `NotifyMutation`. Didn't realize get a descriptor outside of that function would be so problematic -- sorry for causing this hassle.


<!-- Sent from Reviewable.io -->

2022-03-26 20:53 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/catpb/catalog.proto, line 238 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Ut6nA3Uv2VEhIU1F:-Mz1mFPQBl4ng6cEVMBm:b-aemea0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/catalog/catpb/catalog.proto#L238)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

suggestion: don't bother with this
</blockquote></details>

Would removing this be a problem if it's re-added in 22.1.1 and referenced in the `TableDescriptor`?  I thought that's the reason why we need to backport the protobuf changes to 22.1.0 in the first place, to prevent backwards incompatibility.  But maybe this is not the real reason?
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1510 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mygq7JH-LyStgoTLG8_:-Mz26VLZ1uPa6eZ5VKY9:b4qvl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/72a4d332217e69a9b6af91f91b4aee3f38902b62/pkg/sql/catalog/tabledesc/validate.go#L1510)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I meant to say: you can pass the `ValidationErrorAccumulator` interface. It's basically the same thing as as `func(error)` callback. Sorry for not being clearer.
</blockquote></details>

Made the change
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1562 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1ZnKmACXghY-ymQMO:-Mz2FczZ1fsuqa-kIheg:b-ww0ybu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/catalog/tabledesc/validate.go#L1562)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: `s/invalid value/invalid float value/` perhaps? 

comment applies elsewhere also
</blockquote></details>

Done.  Here and in `paramobserver.go`
___
*[pkg/sql/stats/automatic_stats.go, line 573 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyxuvTJ56UJC5ONDdt-:-Mz5lUUQ4zm0YywNWLSd:bh6vqdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L573)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

You're absolutely on the right track here: table descriptor lookups are expensive. Well, to be precise, it's querying the `system.descriptor` table which is expensive, because it incurs a round-trip to the KV layer. This is in addition to the overhead incurred by opening a transaction. This is all a function of network latency between cluster nodes, so, tens or even hundreds of milliseconds.

Of course, as a consequence, we do a lot of in-memory caching, this is one of the main purposes of `descs.Collection`.

As an aside: schema changes involve a lot of these round-trips and we have benchmarks in `rttanalysis` and `rttanalysisccl` which measure performance solely in terms of number of round-trips.
</blockquote></details>

Thanks, the code is updated to batch fetch table descriptors.  Currently the call to CollectionFactory.Txn I have creates a new `descs.Collection` each time descriptors are looked up, so I'm not sure how this helps caching.  I did play around with creating a local `Collection` and reusing it, which almost tripled performance in my benchmark.  But my understanding is that a `Collection` is supposed to be associated with a single transaction, so it is probably not correct to do this.  Adding a `ReleaseAll` after each batch lookup brought performance back down to match performance of using separate Collections.  I guess `descs.Collection` is like a local cache so we don't have to talk to the lease manager again for a given table id.  Such a cache wouldn't help auto stats though, because each TableID to look up is guaranteed to be unique (and then we wait a minute before the next set of lookups).  Please let me know if my understanding is not correct, or if you can see a way to safely re-use a local `descs.Collection`.  Thanks.
___
*[pkg/sql/stats/automatic_stats.go, line 340 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1OJGFA4FjzYi4Mi5W:-Mz5m3tVBfGUu1Wo-ZIo:bbg6wah) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/stats/automatic_stats.go#L340)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

No -- if it has been a while since the stats for a table are updated, we will still force a refresh. And this will only include rows with `rowsAffected == 0` at process startup.
</blockquote></details>

Left this logic as-is.
___
*[pkg/sql/stats/automatic_stats.go, line 345 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Jnrb7F8h7w_cGhk-:-Mz5mBj-AEpOPBw8tlS7:b-lw2fc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/stats/automatic_stats.go#L345)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The size of `mutationCounts` is bounded by the number of tables in the database, so maybe we can just call `GetImmutableDescriptorsByID` once outside the loop?

Otherwise, if this is going to be too complicated / expensive, maybe we should just go back to @msirek's previous approach of getting the settings in `NotifyMutation`. Didn't realize get a descriptor outside of that function would be so problematic -- sorry for causing this hassle.
</blockquote></details>

Changed it to look up 500 descriptors at a time.  If `GetImmutableDescriptorsByID` fails, we fall back to the one-by-one lookups, but this time within the same transaction.  An error looking up a descriptor for one table should not prevent auto stats collection on other tables.
___
*[pkg/sql/catalog/descpb/structured.go, line 279 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1WSm010733BY8fkAd:-Mz213ZYE0crDSuqWCbm:bgz01v7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/catalog/descpb/structured.go#L279)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

We need to be careful about the `descpb` package's dependencies, and this requires we pull in a new one. Can you move these methods you added to the `tabledesc` package instead?

You don't actually need to define these methods on `descpb.TableDescriptor` because that struct does not implement the `catalog.TableDescriptor` interface on its own, instead it's embedded in the `wrapper` struct in `tabledesc`.

</blockquote></details>

Thanks, removed these. and moved the logic into `tabledesc`.



_Code quote:_
```Go
func (desc *TableDescriptor) AutoStatsCollectionEnabled
```


<!-- Sent from Reviewable.io -->

2022-03-26 22:02 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 11 of 11 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-Mz7F43V80SCRlwHDVgN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @mgartner, @msirek, @postamar, and @rharding6373)

___
*[pkg/sql/stats/automatic_stats.go, line 407 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz7BBrB55T_dEdbdd0c:-Mz7BBrB55T_dEdbdd0d:b-ow9hl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7149f4a4632ac15a782bc4e690be8854bfd5a579/pkg/sql/stats/automatic_stats.go#L407)):*
> ```Go
> 						}
> 
> 						var tableIDs []descpb.ID
> ```

nit: you can allocate enough space for either `mutationChunkSize` or `len(mutationCounts)`, which ever is smaller
___
*[pkg/sql/stats/automatic_stats.go, line 425 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz7BSMr59Sf1qcrF35t:-Mz7BSMr59Sf1qcrF35u:beevfpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7149f4a4632ac15a782bc4e690be8854bfd5a579/pkg/sql/stats/automatic_stats.go#L425)):*
> ```Go
> 							}
> 							// Reset, so we'll process a new list of tables on the next pass.
> 							tableIDs = nil
> ```

nit: you can do `tableIDs = tableIDs[:0]` to avoid reallocating space
___
*[pkg/sql/stats/automatic_stats.go, line 454 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz7Cyg93LgWTueaHBEo:-Mz7BuEQC9I92YqoTJfk:bmw97e1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7149f4a4632ac15a782bc4e690be8854bfd5a579/pkg/sql/stats/automatic_stats.go#L454)):*
> ```Go
> }
> 
> func convertToTableDescriptor(
> ```

nit: I'd move this function closer to where it's used (or move all those other new helper functions down here)


<!-- Sent from Reviewable.io -->

2022-03-27 02:26 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/stats/automatic_stats.go, line 407 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz7BBrB55T_dEdbdd0c:-Mz8B2OYErSUdQcuABgW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7149f4a4632ac15a782bc4e690be8854bfd5a579/pkg/sql/stats/automatic_stats.go#L407)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: you can allocate enough space for either `mutationChunkSize` or `len(mutationCounts)`, which ever is smaller
</blockquote></details>

Done.
___
*[pkg/sql/stats/automatic_stats.go, line 425 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz7BSMr59Sf1qcrF35t:-Mz88U88E2EngfmJ8FxF:bavi7bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7149f4a4632ac15a782bc4e690be8854bfd5a579/pkg/sql/stats/automatic_stats.go#L425)):*
> tableIDs[:0]

Done, thanks.
___
*[pkg/sql/stats/automatic_stats.go, line 454 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz7Cyg93LgWTueaHBEo:-Mz88kGX5yU0elMS4XFj:bg704nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7149f4a4632ac15a782bc4e690be8854bfd5a579/pkg/sql/stats/automatic_stats.go#L454)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: I'd move this function closer to where it's used (or move all those other new helper functions down here)
</blockquote></details>

Moved this function up



_Code quote:_
```Go
convertToTableDescriptor
```


<!-- Sent from Reviewable.io -->

2022-03-27 13:43 UTC, rytaft reviewed
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @msirek, @postamar, and @rharding6373)

___
*[pkg/sql/stats/automatic_stats.go, line 252 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzA_rVtEfOAqWYLld7H:-MzA_rVtEfOAqWYLld7I:btoizes) ([raw file](https://github.com/cockroachdb/cockroach/blob/0421e59a9e458d0bdcb6c2b27c6289b1e8287fbc/pkg/sql/stats/automatic_stats.go#L252)):*
> ```Go
> }
> 
> func (r *Refresher) getDescriptors(ctx context.Context, tableIDs []descpb.ID) []catalog.Descriptor {
> ```

Honestly, I had no idea this would be so complicated to get the table descriptors outside of `NotifyMutation`. So I'd say it's up to you, @msirek -- I'm fine with merging this as-is (assuming @postamar signs off), but I'd also be fine with just going back to how you had it before, with grabbing the settings in `NotifyMutation`. The only change I would make to your previous approach is just grab a pointer to the `ClusterSettingsForTable` and store one map for all the settings, rather than each setting in its own map.

Looks like your work is saved by reviewable in r3 if you want it.


<!-- Sent from Reviewable.io -->

2022-03-27 13:50 UTC, rytaft commented
___
*[pkg/sql/stats/automatic_stats.go, line 252 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzA_rVtEfOAqWYLld7H:-MzAc0g_6ydNUbLPtJM6:b-4d0hvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0421e59a9e458d0bdcb6c2b27c6289b1e8287fbc/pkg/sql/stats/automatic_stats.go#L252)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Honestly, I had no idea this would be so complicated to get the table descriptors outside of `NotifyMutation`. So I'd say it's up to you, @msirek -- I'm fine with merging this as-is (assuming @postamar signs off), but I'd also be fine with just going back to how you had it before, with grabbing the settings in `NotifyMutation`. The only change I would make to your previous approach is just grab a pointer to the `ClusterSettingsForTable` and store one map for all the settings, rather than each setting in its own map.

Looks like your work is saved by reviewable in r3 if you want it.
</blockquote></details>

(I would personally have a slight preference for the latter -- i.e. going back to what you had with a single map for all settings. A single map would also make it easier to add new settings later.)


<!-- Sent from Reviewable.io -->

2022-03-27 14:36 UTC, rytaft commented
___
*[pkg/sql/stats/automatic_stats.go, line 252 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzA_rVtEfOAqWYLld7H:-MzAnFxL9Q_Q43Tyiczp:bddn3nx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0421e59a9e458d0bdcb6c2b27c6289b1e8287fbc/pkg/sql/stats/automatic_stats.go#L252)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

(I would personally have a slight preference for the latter -- i.e. going back to what you had with a single map for all settings. A single map would also make it easier to add new settings later.)
</blockquote></details>

Actually... I guess we need to leave it as-is since we want users to be able to disable auto-stats on a per-table basis and have it take effect right away. So ignore me. Sorry for the noise.


<!-- Sent from Reviewable.io -->

2022-03-27 14:54 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @postamar, and @rharding6373)

___
*[pkg/sql/stats/automatic_stats.go, line 252 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzA_rVtEfOAqWYLld7H:-MzAozC42iy04Tz1XUWi:bd7rnzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0421e59a9e458d0bdcb6c2b27c6289b1e8287fbc/pkg/sql/stats/automatic_stats.go#L252)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Actually... I guess we need to leave it as-is since we want users to be able to disable auto-stats on a per-table basis and have it take effect right away. So ignore me. Sorry for the noise.
</blockquote></details>

OK, but the current design doesn't take effect right away I think.  Getting TableDescriptors in a batch up front might encounter some large tables that take a long time to collect stats and if an ALTER TABLE is issued on a table in that set during that time, the TableDescriptor for that table will be stale and still reference old values of the cluster setting when its turn comes around.  Also, the LeaseManager we're getting the descriptors from is like a cache as well.  I'm not sure if the ALTER TABLE would immediately update the leased table descriptor.  I'm guessing there's a mechanism in place to invalidate it so it would be retrieved from disk.  I'm actually getting more slowness and test timeouts in the current revision than with looking up the table descriptors one-at-a-time (right before `maybeRefreshStats` is called).  I'm having trouble tracking down the source of the test timeouts, so I might just go back to the one-at-a-time lookups, which should also make disabling of auto-stats go back to taking immediate effect.


<!-- Sent from Reviewable.io -->

2022-03-27 15:10 UTC, rytaft commented
___
*[pkg/sql/stats/automatic_stats.go, line 252 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzA_rVtEfOAqWYLld7H:-MzAuOzL6YF67m8if8Hb:b-hzc07v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0421e59a9e458d0bdcb6c2b27c6289b1e8287fbc/pkg/sql/stats/automatic_stats.go#L252)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, but the current design doesn't take effect right away I think.  Getting TableDescriptors in a batch up front might encounter some large tables that take a long time to collect stats and if an ALTER TABLE is issued on a table in that set during that time, the TableDescriptor for that table will be stale and still reference old values of the cluster setting when its turn comes around.  Also, the LeaseManager we're getting the descriptors from is like a cache as well.  I'm not sure if the ALTER TABLE would immediately update the leased table descriptor.  I'm guessing there's a mechanism in place to invalidate it so it would be retrieved from disk.  I'm actually getting more slowness and test timeouts in the current revision than with looking up the table descriptors one-at-a-time (right before `maybeRefreshStats` is called).  I'm having trouble tracking down the source of the test timeouts, so I might just go back to the one-at-a-time lookups, which should also make disabling of auto-stats go back to taking immediate effect.
</blockquote></details>

Ah right... Well I think it's also not the end of the world if there is some delay in the setting taking effect, in which case going back to the old design of grabbing the settings in `NotifyMutation` is probably better than the current approach (we just need to make sure it's documented that it could take a few minutes to take effect, especially if there is already a large stats update in progress). But I think it's your call -- I'm fine with any of these options.


<!-- Sent from Reviewable.io -->

2022-03-27 22:51 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/stats/automatic_stats.go, line 573 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyxuvTJ56UJC5ONDdt-:-MzCYHA69lA0h3RUl_4F:bw7xn9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L573)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Thanks, the code is updated to batch fetch table descriptors.  Currently the call to CollectionFactory.Txn I have creates a new `descs.Collection` each time descriptors are looked up, so I'm not sure how this helps caching.  I did play around with creating a local `Collection` and reusing it, which almost tripled performance in my benchmark.  But my understanding is that a `Collection` is supposed to be associated with a single transaction, so it is probably not correct to do this.  Adding a `ReleaseAll` after each batch lookup brought performance back down to match performance of using separate Collections.  I guess `descs.Collection` is like a local cache so we don't have to talk to the lease manager again for a given table id.  Such a cache wouldn't help auto stats though, because each TableID to look up is guaranteed to be unique (and then we wait a minute before the next set of lookups).  Please let me know if my understanding is not correct, or if you can see a way to safely re-use a local `descs.Collection`.  Thanks.
</blockquote></details>

Well, I went back to a design which does not need to look up table descriptors.  Thank you though for your input on this topic though, it was very instructive.
___
*[pkg/sql/stats/automatic_stats.go, line 252 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzA_rVtEfOAqWYLld7H:-MzCWoh56jdbGZ3G3sLV:bdqe8ul) ([raw file](https://github.com/cockroachdb/cockroach/blob/0421e59a9e458d0bdcb6c2b27c6289b1e8287fbc/pkg/sql/stats/automatic_stats.go#L252)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ah right... Well I think it's also not the end of the world if there is some delay in the setting taking effect, in which case going back to the old design of grabbing the settings in `NotifyMutation` is probably better than the current approach (we just need to make sure it's documented that it could take a few minutes to take effect, especially if there is already a large stats update in progress). But I think it's your call -- I'm fine with any of these options.
</blockquote></details>

I was not confident about the stability and performance of the code which looks up table descriptors.  I went back to the old design, but also created a new channel for sending settings to keep the amount of memory allocated for `mutations` to a minimum.  The new channel is only used when setting overrides are present.  Crossing my fingers that the CI build will run fine now...


<!-- Sent from Reviewable.io -->

2022-03-28 02:06 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/stats/automatic_stats.go, line 252 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzA_rVtEfOAqWYLld7H:-MzDFQl85Z7nwIBY5kK6:b-jz5w89) ([raw file](https://github.com/cockroachdb/cockroach/blob/0421e59a9e458d0bdcb6c2b27c6289b1e8287fbc/pkg/sql/stats/automatic_stats.go#L252)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I was not confident about the stability and performance of the code which looks up table descriptors.  I went back to the old design, but also created a new channel for sending settings to keep the amount of memory allocated for `mutations` to a minimum.  The new channel is only used when setting overrides are present.  Crossing my fingers that the CI build will run fine now...
</blockquote></details>

Still getting timeouts, though the test time of non-hanging tests ran much quicker.  I profiled the execbuilder test, and the results are interesting:

![image.png](https://files.reviewableusercontent.io/images/reviewable/3999975/UXgr2KbArvdkrBxKshoKYn_D/image.png)

The Refresher main loop is taking up a lot of time.  I wonder if this causes CPU contention with other threads.  Perhaps we need to do a sleep in the loop, or maybe Go has a mechanism to wake up and do processing only when something is written to a channel.  Will research along these lines


<!-- Sent from Reviewable.io -->

2022-03-28 05:46 UTC, otan commented on pkg/sql/logictest/testdata/logic_test/create_table
> +CREATE TABLE t11 (a int) WITH ("sql.stats.automatic_collection.enabled" = true,
i would discourage using `.` as names for table storage parameters, using `_` as a separator instead.

2022-03-28 13:12 UTC, rytaft reviewed
It seems like there's a lot of new complexity to extract auto stats settings from the cluster settings for the table. I would suggest changing the struct to just refer to auto stats settings, and not try to cover all possible future cluster settings. That will also make it easier to address @otan's point about using a name without '.' characters.

I'm also wondering why you can't just pass around a pointer to these settings. Why do you need to copy by value when you're just reading from them? I would try to reduce complexity here as much as possible -- if we pass a pointer around, then we shouldn't need a separate channel, right?

> Reviewed 7 of 7 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-MzF_CtH6QvklDWL94fF:b-69o80p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @msirek, @postamar, and @rharding6373)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 2660 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFTkQ_8lakQFQAHGJA:-MzFTkQ_8lakQFQAHGJB:b-72s21o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/catalog/tabledesc/structured.go#L2660)):*
> ```Go
> 	if otherHasNoAutoStatsSettings {
> 		return false
> 	}
> ```

Feels like all this logic should go inside `AutoStatsSettingsEqual`
___
*[pkg/sql/stats/automatic_stats.go, line 252 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzA_rVtEfOAqWYLld7H:-MzFUW-m1-6s7PiJQ9vY:b971a5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0421e59a9e458d0bdcb6c2b27c6289b1e8287fbc/pkg/sql/stats/automatic_stats.go#L252)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Still getting timeouts, though the test time of non-hanging tests ran much quicker.  I profiled the execbuilder test, and the results are interesting:

![image.png](https://files.reviewableusercontent.io/images/reviewable/3999975/UXgr2KbArvdkrBxKshoKYn_D/image.png)

The Refresher main loop is taking up a lot of time.  I wonder if this causes CPU contention with other threads.  Perhaps we need to do a sleep in the loop, or maybe Go has a mechanism to wake up and do processing only when something is written to a channel.  Will research along these lines
</blockquote></details>

Ok, although this code has been mostly unchanged since 2019, so I'm not too concerned. Feel free to research more, but I don't think it should hold up this PR.
___
*[pkg/sql/stats/automatic_stats.go, line 340 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFVJfTDqcbVWkiUPhm:-MzFVJfU3hLIeWLYFd5I:b-vupds1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L340)):*
> ```Go
> 			refreshInterval = MinRefreshInterval
> 		}
> 		origRefreshInterval := refreshInterval
> ```

Why are you defining another variable here? Why not just use `refreshInterval`?

Since we're going to backport this PR, I'd rather not make a lot of changes here. If you think there's a bug, please file a separate GitHub issue and open a separate PR to fix.
___
*[pkg/sql/stats/automatic_stats.go, line 368 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFWnHbAgMiSduvg5iR:-MzFWnHbAgMiSduvg5iS:bnt724q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L368)):*
> ```Go
> 				mutationCounts := r.mutationCounts
> 				var settingOverrides map[descpb.ID]catpb.ClusterSettingsForTable
> 				settingOverrides = make(map[descpb.ID]catpb.ClusterSettingsForTable)
> ```

Why not just do the same as what we're doing for `mutationCounts`?
___
*[pkg/sql/stats/automatic_stats.go, line 416 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFd3no9pjTD35Mzy11:-MzFd3no9pjTD35Mzy12:b-uuj7tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L416)):*
> ```Go
> 				// This clears out any tables that may have been added to the
> 				// mutationCounts map by ensureAllTables. This is by design. We don't
> 				// want to constantly refresh tables that are read-only.
> ```

It's not just `ensureAllTables`, though, it's any mutation counts that have been added since the last call to `maybeRefreshStats`.
___
*[pkg/sql/stats/automatic_stats.go, line 433 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFYnvF2BnpeOYmXS9V:-MzFYnvF2BnpeOYmXS9W:b-356svc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L433)):*
> ```Go
> 					// If the old cluster setting overrides don't match the current ones, update
> 					// the hash map with the current settings.
> 					if !currentSettings.AutoStatsSettingsEqual(&oldSettings) {
> ```

Why not just reassign? Why do we need to check if they are equal?

This whole block seems more complicated than needed.
___
*[pkg/sql/stats/automatic_stats.go, line 551 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFZjO4Ab1XseH8HIkH:-MzFZjO4Ab1XseH8HIkI:bat5x3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L551)):*
> ```Go
> }
> 
> func copyAutoStatsSettings(
> ```

This seems like something that should be defined elsewhere, as a lower level copy function (if we still need it)


<!-- Sent from Reviewable.io -->

2022-03-28 14:47 UTC, postamar approved these changes
LGTM conditional on removing that undesirable import in `catpb`, which should be straightforward. No other concerns on my end, please don't wait on me to merge this PR once that's addressed.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-MzFz-yBAduLuICZ1YxQ:b-9e4nr0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @msirek, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/catpb/catalog.go, line 13 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFt6PK-ankrzoBIZ62:-MzFt6PK-ankrzoBIZ63:b-iziigz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/catalog/catpb/catalog.go#L13)):*
> ```Go
> package catpb
> 
> import "github.com/cockroachdb/cockroach/pkg/settings/cluster"
> ```

Sorry for being annoying again but we also don't want to pull in packages into `catpb` if we can avoid it...

Suggestion: replace the `cluster.BoolSetting` definition with a more specific `AutoStatsCollectionStatus` type defined in this file:
```
type AutoStatsCollectionStatus int
const (
  AutoStatsCollectionNotSet AutoStatsCollectionStatus = iota
  AutoStatsCollectionDisabled
  AutoStatsCollectionEnabled
)
```
___
*[pkg/sql/catalog/catpb/catalog.proto, line 238 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Ut6nA3Uv2VEhIU1F:-MzFogOO9CltavPh1_T0:b-6v5b3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/catalog/catpb/catalog.proto#L238)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Would removing this be a problem if it's re-added in 22.1.1 and referenced in the `TableDescriptor`?  I thought that's the reason why we need to backport the protobuf changes to 22.1.0 in the first place, to prevent backwards incompatibility.  But maybe this is not the real reason?
</blockquote></details>

Ah, I understand your motivation now. We don't ever add new fields or other things like that to protobufs in patch versions. We also typically just don't at this point in the release cycle either but sometimes we make exceptions (this is one).
___
*[pkg/sql/stats/automatic_stats.go, line 573 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyxuvTJ56UJC5ONDdt-:-MzFwd5ZBvepB5yP_pJ4:b-ow1za0) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L573)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Well, I went back to a design which does not need to look up table descriptors.  Thank you though for your input on this topic though, it was very instructive.
</blockquote></details>

Happy to help! The Collection's lifecycle is definitely tied to the transaction: it's absolutely not safe to use once the transaction commits. That being said, the collection is implemented using multiple layers of caching which have different lifecycles, some independent of transactions. For instance, one of these layers is the lease manager, which is a per-cluster-node singleton.
___
*[pkg/sql/stats/automatic_stats.go, line 345 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Jnrb7F8h7w_cGhk-:-MzFqDAaDgGAhkKHh0Bd:b-2xe2la) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/stats/automatic_stats.go#L345)):*
> The size of mutationCounts is bounded by the number of tables in the database, so maybe we can just call GetImmutableDescriptorsByID once outside the loop?

FYI, we should not assume that this number is small enough that it doesn't matter. Experience doing descriptor migrations during cluster upgrades has taught us otherwise.

 
___
*[pkg/sql/stats/automatic_stats.go, line 591 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFsN0X3J51Ts8_N1-Q:-MzFsN0X3J51Ts8_N1-R:bgp3qpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L591)):*
> ```Go
> 		clusterSettingsForTable := table.GetClusterSettingsForTable()
> 		autoStatsOverrides := catpb.ClusterSettingsForTable{}
> 		copyAutoStatsSettings(&autoStatsOverrides, clusterSettingsForTable)
> ```

nit: you can use `protoutil.Clone` to deep-copy any protobuf message like this:
```
var autoStatsOverrides catpb.ClusterSettingsForTable
if s := table.GetClusterSettingsForTable(); s != nil {
  autoStatsOverrides = *protoutil.Clone(s).(*catpb.ClusterSettingsForTable)
}
```
meaning you can probably get rid of `copyAutoStatsSettings`.


<!-- Sent from Reviewable.io -->

2022-03-28 14:53 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @msirek, @postamar, and @rharding6373)

___
*[pkg/sql/stats/automatic_stats.go, line 345 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Jnrb7F8h7w_cGhk-:-MzG-jwe-0ZkbWUdaHMe:b-ahle5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/stats/automatic_stats.go#L345)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

> The size of mutationCounts is bounded by the number of tables in the database, so maybe we can just call GetImmutableDescriptorsByID once outside the loop?

FYI, we should not assume that this number is small enough that it doesn't matter. Experience doing descriptor migrations during cluster upgrades has taught us otherwise.

 
</blockquote></details>

Good to know!


<!-- Sent from Reviewable.io -->

2022-03-28 16:03 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @msirek, @postamar, and @rharding6373)

___
*[pkg/sql/stats/automatic_stats.go, line 252 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzA_rVtEfOAqWYLld7H:-MzGFO_N7-eQXwrRk9v4:b-rqhxl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0421e59a9e458d0bdcb6c2b27c6289b1e8287fbc/pkg/sql/stats/automatic_stats.go#L252)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ok, although this code has been mostly unchanged since 2019, so I'm not too concerned. Feel free to research more, but I don't think it should hold up this PR.
</blockquote></details>

This turned out to be a bug in my code.  I also am suspecting some of the hangs may be due to `DefaultAsOfTime` and `DefaultRefreshInterval` being global variables that aren't properly reset, or are written/accessed in parallel during sharded tests.  I'm going to introduce overrides for these.


<!-- Sent from Reviewable.io -->

2022-03-28 16:12 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @msirek, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/stats/automatic_stats.go, line 340 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFVJfTDqcbVWkiUPhm:-MzGH3BE03vdmfEL0F3-:b-g08hi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L340)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why are you defining another variable here? Why not just use `refreshInterval`?

Since we're going to backport this PR, I'd rather not make a lot of changes here. If you think there's a bug, please file a separate GitHub issue and open a separate PR to fix.
</blockquote></details>

It's because of this code which avoids creating the asynchronous task:
```
				if len(r.mutationCounts) == 0 {
					timer.Reset(origRefreshInterval)
					continue
				}
```
Because it doesn't do this wait before resetting the timer:
```
						timerAsOf := time.NewTimer(r.asOfTime)
						defer timerAsOf.Stop()
						select {
						case <-timerAsOf.C:
							break
						case <-stopper.ShouldQuiesce():
							return
						}
```
It has to include `asOfTime` in the refresh interval, which had been subtracted out here:
```
		// We always sleep for r.asOfTime at the beginning of each refresh, so
		// subtract it from the refreshInterval.
		refreshInterval -= r.asOfTime
```

Do you think I should remove the code which avoids creating the asynchronous task when `r.mutationCounts` is empty?


<!-- Sent from Reviewable.io -->

2022-03-28 16:32 UTC, mgartner commented
___
*[pkg/sql/catalog/catpb/catalog.proto, line 224 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGMCbHDFc-0hjC5_Rr:-MzGMCbHDFc-0hjC5_Rs:b-6xnee3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/catalog/catpb/catalog.proto#L224)):*
> ```protobuf
> // level. Each setting is nullable so queries of the descriptor in JSON form
> // only list values which have been set.
> message ClusterSettingsForTable {
> ```

Based on @ajwerner's comment [here](https://github.com/cockroachdb/cockroach/issues/78395#issuecomment-1077019482), maybe we shouldn't call these things "cluster settings" to avoid confusion. The table settings you're introducing are a special subset of table settings that override cluster settings, correct? Maybe `ClusterSettingOverridesForTable` is clearer? 


<!-- Sent from Reviewable.io -->

2022-03-28 17:25 UTC, rytaft commented
___
*[pkg/sql/stats/automatic_stats.go, line 340 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFVJfTDqcbVWkiUPhm:-MzGTvtGELTrV0qN8i0T:biwn62a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L340)):*
> Do you think I should remove the code which avoids creating the asynchronous task when r.mutationCounts is empty?

Yea, I think we should keep this PR as minimal as possible.


<!-- Sent from Reviewable.io -->

2022-03-28 17:27 UTC, ajwerner requested changes
Putting a changes requested to deal with the cluster version stuff

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-MzGZBT8AVJUqDVAKVnI:b-4jqq7y)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/settings/cluster/cluster_settings.go, line 103 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGYjrk0Pa4J8EUOTsB:-MzGYjrk0Pa4J8EUOTsC:b-7aoshm) ([raw file](https://github.com/cockroachdb/cockroach/blob/acec614b3053041e8141ad9ed036b6ecd46271a6/pkg/settings/cluster/cluster_settings.go#L103)):*
> ```Go
> 	// collection fraction stale rows cluster setting.
> 	AutoStatsFractionStaleSettingName = "sql.stats.automatic_collection.fraction_stale_rows"
> )
> ```

This doesn't feel right here. This has nothing to do with the cluster setting package itself, which is a totally generic package. I'll go one further, we should not be conceptualizing the table settings as having anything to do with the cluster setting concept in terminology or code. 



_Code quote:_
```Go

	// AutoStatsEnabledSettingName is the name of the automatic stats collection
	// enabled cluster setting.
	AutoStatsEnabledSettingName = "sql.stats.automatic_collection.enabled"

	// AutoStatsMinStaleSettingName is the name of the automatic stats collection
	// min stale rows cluster setting.
	AutoStatsMinStaleSettingName = "sql.stats.automatic_collection.min_stale_rows"

	// AutoStatsFractionStaleSettingName is the name of the automatic stats
	// collection fraction stale rows cluster setting.
	AutoStatsFractionStaleSettingName = "sql.stats.automatic_collection.fraction_stale_rows"
)
```


<!-- Sent from Reviewable.io -->

2022-03-28 17:29 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/catpb/catalog.proto, line 238 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Ut6nA3Uv2VEhIU1F:-MzGZoR50iHs-_yNopA0:b3vas0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/catalog/catpb/catalog.proto#L238)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Ah, I understand your motivation now. We don't ever add new fields or other things like that to protobufs in patch versions. We also typically just don't at this point in the release cycle either but sometimes we make exceptions (this is one).
</blockquote></details>

I still don't get it. 
___
*[pkg/sql/catalog/catpb/catalog.proto, line 224 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGMCbHDFc-0hjC5_Rr:-MzGZd2KE0DKqM3xzyaC:b504574) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/catalog/catpb/catalog.proto#L224)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Based on @ajwerner's comment [here](https://github.com/cockroachdb/cockroach/issues/78395#issuecomment-1077019482), maybe we shouldn't call these things "cluster settings" to avoid confusion. The table settings you're introducing are a special subset of table settings that override cluster settings, correct? Maybe `ClusterSettingOverridesForTable` is clearer? 
</blockquote></details>

I feel like we shouldn't mention the word `ClusterSettings` whatsoever. The fact that there's a related cluster setting is a vestigial. 
___
*[pkg/sql/catalog/descpb/structured.proto, line 1205 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGZSIm6PKo5QsQkviI:-MzGZSIm6PKo5QsQkviJ:bchm0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/acec614b3053041e8141ad9ed036b6ecd46271a6/pkg/sql/catalog/descpb/structured.proto#L1205)):*
> ```protobuf
> 
>   // SessionSettingsForTable are session settings specified at the table level.
>   optional cockroach.sql.catalog.catpb.SessionSettingsForTable session_settings_for_table = 52 [(gogoproto.customname)="SessionSettingsForTable"];
> ```

I'm reading this PR and I don't think I get it. I feel like we're going about tightly coupling concepts that shouldn't be coupled at all. 



_Code quote:_
```protobuf
  // ClusterSettingsForTable are cluster settings specified at the table level.
  optional cockroach.sql.catalog.catpb.ClusterSettingsForTable cluster_settings_for_table = 51 [(gogoproto.customname)="ClusterSettingsForTable"];

  // SessionSettingsForTable are session settings specified at the table level.
  optional cockroach.sql.catalog.catpb.SessionSettingsForTable session_settings_for_table = 52 [(gogoproto.customname)="SessionSettingsForTable"];
```


<!-- Sent from Reviewable.io -->

2022-03-28 17:42 UTC, mgartner commented
___
*[pkg/sql/catalog/catpb/catalog.proto, line 224 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGMCbHDFc-0hjC5_Rr:-MzGb5dC3CL-k47w6NRp:b-owca1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/catalog/catpb/catalog.proto#L224)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like we shouldn't mention the word `ClusterSettings` whatsoever. The fact that there's a related cluster setting is a vestigial. 
</blockquote></details>

I'm fine with removing `ClusterSettings` altogether and conforming to the term "table settings". I think it would be most clear that way. :+1: 

I wouldn't call the related cluster setting "vestigial" though. It is useful even with the addition of auto-stats table settings, and I don't see us deprecating it. Also, Postgres has both server and table settings for auto-stats configurations: https://www.postgresql.org/docs/9.5/runtime-config-autovacuum.html#GUC-AUTOVACUUM-VACUUM-THRESHOLD


<!-- Sent from Reviewable.io -->

2022-03-28 18:29 UTC, postamar commented
> I still don't get it.

I was referring to the desire to keep a message stub around for a (perceived) need to maintain compatibility, nothing more.

2022-03-29 02:26 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/settings/cluster/cluster_settings.go, line 103 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGYjrk0Pa4J8EUOTsB:-MzHmFkdAkOCUGfkjOwt:b-b9xfzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/acec614b3053041e8141ad9ed036b6ecd46271a6/pkg/settings/cluster/cluster_settings.go#L103)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This doesn't feel right here. This has nothing to do with the cluster setting package itself, which is a totally generic package. I'll go one further, we should not be conceptualizing the table settings as having anything to do with the cluster setting concept in terminology or code. 
</blockquote></details>

These are here because I was getting import cycles if they were defined in the stats, sql or opt packages.  I had to remove a package dependency `catpb` had on `cluster`, so I've moved these, along with `BoolSetting` (renamed to `AutoStatsCollectionStatus`)  to `catpb/catalog.go`.  Maybe this could be where overridable setting names live. Is this OK, or do you have another suggestion?  Thanks.
___
*[pkg/sql/catalog/catpb/catalog.go, line 13 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFt6PK-ankrzoBIZ62:-MzIIJqm9w7OWFq1-5Xj:b-5c7vmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/catalog/catpb/catalog.go#L13)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Sorry for being annoying again but we also don't want to pull in packages into `catpb` if we can avoid it...

Suggestion: replace the `cluster.BoolSetting` definition with a more specific `AutoStatsCollectionStatus` type defined in this file:
```
type AutoStatsCollectionStatus int
const (
  AutoStatsCollectionNotSet AutoStatsCollectionStatus = iota
  AutoStatsCollectionDisabled
  AutoStatsCollectionEnabled
)
```


</blockquote></details>

No worries, and thanks. I moved this type definition into this file, which removes the dependency.  I've also renamed `BoolSetting` to `AutoStatsCollectionStatus` as suggested.
___
*[pkg/sql/catalog/catpb/catalog.proto, line 238 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Ut6nA3Uv2VEhIU1F:-MzIRDAUE4kcep9RD6n3:bmdqh3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/catalog/catpb/catalog.proto#L238)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I still don't get it. 
</blockquote></details>

This message type is going away.
___
*[pkg/sql/catalog/catpb/catalog.proto, line 224 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGMCbHDFc-0hjC5_Rr:-MzIO9rf2jygAkp_t5Tb:brbyao8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/catalog/catpb/catalog.proto#L224)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm fine with removing `ClusterSettings` altogether and conforming to the term "table settings". I think it would be most clear that way. :+1: 

I wouldn't call the related cluster setting "vestigial" though. It is useful even with the addition of auto-stats table settings, and I don't see us deprecating it. Also, Postgres has both server and table settings for auto-stats configurations: https://www.postgresql.org/docs/9.5/runtime-config-autovacuum.html#GUC-AUTOVACUUM-VACUUM-THRESHOLD
</blockquote></details>

Thanks.  It's good to be precise.  I could just call this `SettingOverrides`, however, it's possible we may want to place more items here than just overrides.  I added some generic functions for dealing with bool, int64 and float64 primitive types in `paramobserver.go`.  I was thinking maybe future table settings having these types might also live in this `catpb` struct, to avoid inlining them all in `descpb.TableDescriptor`, mixed in with other items that describe core attributes of the table.  With this approach, a name like `PrimitiveTableSettings` or `PrimitiveSettings`might be applicable.  Any preferences?  Maybe something not listed?
___
*[pkg/sql/catalog/descpb/structured.proto, line 1205 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGZSIm6PKo5QsQkviI:-MzIRRDQ4_Rskr7qNcZD:bpwwvru) ([raw file](https://github.com/cockroachdb/cockroach/blob/acec614b3053041e8141ad9ed036b6ecd46271a6/pkg/sql/catalog/descpb/structured.proto#L1205)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm reading this PR and I don't think I get it. I feel like we're going about tightly coupling concepts that shouldn't be coupled at all. 
</blockquote></details>

OK.  I left a note above.  It's just a way to group like items together.  `SettingOverrides` or `PrimitiveTableSettings` are other options.  Do you have a preference or other idea?  
___
*[pkg/sql/logictest/testdata/logic_test/create_table, line 926 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyUKFC5eExnCWfUW5qW-r20-926:-MzHlnw-1xtEzYowb4Z_:b3ld8kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/logictest/testdata/logic_test/create_table#L926)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i would discourage using `.` as names for table storage parameters, using `_` as a separator instead.
</blockquote></details>

What is the reason?  This was intentionally chosen to exactly match the setting name we're overriding for ease of use.


<!-- Sent from Reviewable.io -->

2022-03-29 15:16 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/catpb/catalog.proto, line 224 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGMCbHDFc-0hjC5_Rr:-MzLEPnjEvzmVjZ4HVqi:byxljkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/catalog/catpb/catalog.proto#L224)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Thanks.  It's good to be precise.  I could just call this `SettingOverrides`, however, it's possible we may want to place more items here than just overrides.  I added some generic functions for dealing with bool, int64 and float64 primitive types in `paramobserver.go`.  I was thinking maybe future table settings having these types might also live in this `catpb` struct, to avoid inlining them all in `descpb.TableDescriptor`, mixed in with other items that describe core attributes of the table.  With this approach, a name like `PrimitiveTableSettings` or `PrimitiveSettings`might be applicable.  Any preferences?  Maybe something not listed?
</blockquote></details>

I'll be opening a PR for the protobuf changes and versioning.  I will change `ClusterSettingsForTable` to `TableSettings` unless there is a preference for something else.



_Code quote:_
```protobuf
ClusterSettingsForTable
```


<!-- Sent from Reviewable.io -->

2022-03-29 19:13 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/catpb/catalog.proto, line 224 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGMCbHDFc-0hjC5_Rr:-MzM4qdlCTXAG3f_1Rr1:bveflx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/catalog/catpb/catalog.proto#L224)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I'll be opening a PR for the protobuf changes and versioning.  I will change `ClusterSettingsForTable` to `TableSettings` unless there is a preference for something else.
</blockquote></details>

After some more discussion, we decided to make the struct specific to auto stats and will be naming it `AutoStatsSettings` instead of `ClusterSettingsForTable` or `TableSettings`.
___
*[pkg/sql/stats/automatic_stats.go, line 345 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mz1Jnrb7F8h7w_cGhk-:-MzLlT-yE7esX4iGG5FZ:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dcd8a19829b27f069298d6859a4c42fe8ceac23/pkg/sql/stats/automatic_stats.go#L345)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Good to know!
</blockquote></details>

ack
___
*[pkg/sql/stats/automatic_stats.go, line 340 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFVJfTDqcbVWkiUPhm:-MzLkwbvCHPwZBqx9Xk5:bbeg432) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L340)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> Do you think I should remove the code which avoids creating the asynchronous task when r.mutationCounts is empty?

Yea, I think we should keep this PR as minimal as possible.
</blockquote></details>

OK, removed it.
___
*[pkg/sql/stats/automatic_stats.go, line 368 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFWnHbAgMiSduvg5iR:-MzLl8SG2nyYA-48p-bu:b-12ggz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L368)):*
> Why not just do the same as what we're doing for mutationCounts?

Modified as suggested.
___
*[pkg/sql/stats/automatic_stats.go, line 416 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFd3no9pjTD35Mzy11:-MzLlq2LDTKZiiWqSO5E:b1mdct3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L416)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It's not just `ensureAllTables`, though, it's any mutation counts that have been added since the last call to `maybeRefreshStats`.
</blockquote></details>

Modified the comment to include this case.
___
*[pkg/sql/stats/automatic_stats.go, line 433 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFYnvF2BnpeOYmXS9V:-MzLm8S45JmouoCSmQ5s:b4g7dmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L433)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why not just reassign? Why do we need to check if they are equal?

This whole block seems more complicated than needed.
</blockquote></details>

If we don't check for equality we'd be constructing a new


<!-- Sent from Reviewable.io -->

2022-03-29 23:17 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/settings/cluster/cluster_settings.go, line 103 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGYjrk0Pa4J8EUOTsB:-MzMxitn09zfVrqfIleB:b-b9vh41) ([raw file](https://github.com/cockroachdb/cockroach/blob/acec614b3053041e8141ad9ed036b6ecd46271a6/pkg/settings/cluster/cluster_settings.go#L103)):*
> so I've moved these, along with BoolSetting (renamed to AutoStatsCollectionStatus) to catpb/catalog.go

Is this now in `catpb`? That seems like a good place for these constants. 


<!-- Sent from Reviewable.io -->

2022-03-30 00:24 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/settings/cluster/cluster_settings.go, line 103 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzGYjrk0Pa4J8EUOTsB:-MzNCNrqAv7k57hsgE9R:bh0oq95) ([raw file](https://github.com/cockroachdb/cockroach/blob/acec614b3053041e8141ad9ed036b6ecd46271a6/pkg/settings/cluster/cluster_settings.go#L103)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> so I've moved these, along with BoolSetting (renamed to AutoStatsCollectionStatus) to catpb/catalog.go

Is this now in `catpb`? That seems like a good place for these constants. 
</blockquote></details>

Yes.  OK, thanks.


<!-- Sent from Reviewable.io -->

2022-03-30 17:21 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 2660 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFTkQ_8lakQFQAHGJA:-MzPk0YdBeC6tQH9asca:b-2uujo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/catalog/tabledesc/structured.go#L2660)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Feels like all this logic should go inside `AutoStatsSettingsEqual`
</blockquote></details>

The following functions are unused in the latest refactor and removed:
`AutoStatsClusterSettingOverridesEqual`
`AutoStatsSettingsEqual`
`NoClusterSettingOverrides`
___
*[pkg/sql/stats/automatic_stats.go, line 573 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyxuvTJ56UJC5ONDdt-:-MzPqHoV4It1pw4cllGg:b-bcniyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/284230fb063a110751a0883c6afbda054d8b2e38/pkg/sql/stats/automatic_stats.go#L573)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Happy to help! The Collection's lifecycle is definitely tied to the transaction: it's absolutely not safe to use once the transaction commits. That being said, the collection is implemented using multiple layers of caching which have different lifecycles, some independent of transactions. For instance, one of these layers is the lease manager, which is a per-cluster-node singleton.
</blockquote></details>

Thanks again for the help and advice.
___
*[pkg/sql/stats/automatic_stats.go, line 551 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFZjO4Ab1XseH8HIkH:-MzPq0F_0AL286AkeQk1:br5fy6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L551)):*
> copyAutoStatsSettings

Removed this function in favor of Marius' suggested `protoutil.Clone`.
___
*[pkg/sql/stats/automatic_stats.go, line 591 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzFsN0X3J51Ts8_N1-Q:-MzPprh5C7mYWvMaBVDE:b-gnxoa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/stats/automatic_stats.go#L591)):*
> *protoutil.Clone(s).(*catpb.ClusterSettingsForTable)

Excellent!  Thanks!
___
*[pkg/sql/logictest/testdata/logic_test/create_table, line 926 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyUKFC5eExnCWfUW5qW-r20-926:-MzPzL0j2cGfxLlXgDsa:b-co8eec) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f508f6b5e7938ce4d1c62234bffd519727ad21/pkg/sql/logictest/testdata/logic_test/create_table#L926)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

What is the reason?  This was intentionally chosen to exactly match the setting name we're overriding for ease of use.
</blockquote></details>

Changed the table setting names to:
`sql_stats_automatic_collection_enabled`
`sql_stats_automatic_collection_min_stale_rows`
`sql_stats_automatic_collection_fraction_stale_rows`


<!-- Sent from Reviewable.io -->

2022-03-30 21:20 UTC, rytaft reviewed
Getting very close!

> Reviewed 3 of 7 files at r21, 7 of 7 files at r23, 16 of 22 files at r24, 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-MzRgj4Z66TIYP2gExQo:btose9e)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/catpb/catalog.go, line 84 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzR_26T0U6nYfLAVqZY:-MzR_26U0uGMeouiK7Fm:b-s8sh20) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/catalog/catpb/catalog.go#L84)):*
> ```Go
> 
> // NoAutoStatsSettingsOverrides is true if no auto stats related cluster
> // settings are present in these TableSettings.
> ```

nit: update comment to remove reference to cluster settings and change TableSettings to AutoStatsSettings
___
*[pkg/sql/catalog/tabledesc/structured.go, line 2635 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzR_tiE9TPd_wqxs5Cl:-MzR_tiE9TPd_wqxs5Cm:b-93pprv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/catalog/tabledesc/structured.go#L2635)):*
> ```Go
> }
> 
> // AutoStatsSettings implements the TableDescriptor interface.
> ```

nit: AutoStatsSettings -> GetAutoStatsSettings
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1533 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzRde-m8CD4xWfzw6MF:-MzRde-nEauzChH93MeW:blx20em) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/catalog/tabledesc/validate.go#L1533)):*
> ```Go
> }
> 
> func (desc *wrapper) validateBoolSetting(
> ```

It's odd that this function name is generic when it's only used for the stats setting (ditto other functions below)
___
*[pkg/sql/paramparse/paramobserver.go, line 498 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzRaerv3N9shvBWxGda:-MzRaerv3N9shvBWxGdb:b-vvfjl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/paramparse/paramobserver.go#L498)):*
> ```Go
> 	},
> 	catpb.AutoStatsEnabledTableSettingName: {
> 		onSet:   boolTableSettingFunc,
> ```

All of these set/reset function have generic names, but in fact they are specific to auto stats. Maybe the names should be updated to make that clear?

Or just move the code inline like all the other settings above.
___
*[pkg/sql/stats/automatic_stats.go, line 399 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzRbOMX9tCfjdvC0jlJ:-MzRbOMX9tCfjdvC0jlK:b6wr0oj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/stats/automatic_stats.go#L399)):*
> ```Go
> 				// have been added since the last call to maybeRefreshStats.
> 				// This is by design. We don't want to constantly refresh tables that
> 				// are read-only. We update settingOverrides also to prevent data
> ```

Looks like this got cut off
___
*[pkg/sql/stats/automatic_stats_test.go, line 147 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzRgPNRDX6L7WBQqJin:-MzRgPNRDX6L7WBQqJio:b-9clkar) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/stats/automatic_stats_test.go#L147)):*
> ```Go
> }
> 
> func BenchmarkMaybeRefreshStats(b *testing.B) {
> ```

Is this benchmark still useful?


<!-- Sent from Reviewable.io -->

2022-03-30 22:01 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/catpb/catalog.go, line 84 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzR_26T0U6nYfLAVqZY:-MzRlnYiAU4tYC3ICuAa:undefined) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/catalog/catpb/catalog.go#L84)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: update comment to remove reference to cluster settings and change TableSettings to AutoStatsSettings
</blockquote></details>





_Suggestion:_
```Go
Done
```
___
*[pkg/sql/catalog/tabledesc/structured.go, line 2635 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzR_tiE9TPd_wqxs5Cl:-MzRlxHJ39LlvDAAcYhn:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/catalog/tabledesc/structured.go#L2635)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: AutoStatsSettings -> GetAutoStatsSettings
</blockquote></details>

Done



_Code quote:_
```Go
AutoStatsSettings implements the TableDescriptor interface.
```
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1533 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzRde-m8CD4xWfzw6MF:-MzRm2Rk3LNamtZdJcJ_:b-3x36it) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/catalog/tabledesc/validate.go#L1533)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It's odd that this function name is generic when it's only used for the stats setting (ditto other functions below)
</blockquote></details>

Changed function names to:
```
validateAutoStatsEnabled
validateMinStaleRows
validateFractionStaleRows
```
___
*[pkg/sql/paramparse/paramobserver.go, line 498 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzRaerv3N9shvBWxGda:-MzRndbO9vEk_8Gm9OxU:bfnq2dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/paramparse/paramobserver.go#L498)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

All of these set/reset function have generic names, but in fact they are specific to auto stats. Maybe the names should be updated to make that clear?

Or just move the code inline like all the other settings above.
</blockquote></details>

Changed the function names to:
```
autoStatsEnabledSettingFunc
autoStatsMinStaleRowsSettingFunc
autoStatsFractionStaleRowsSettingFunc
```



_Code quote:_
```Go
boolTableSettingFunc
```
___
*[pkg/sql/stats/automatic_stats.go, line 399 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzRbOMX9tCfjdvC0jlJ:-MzRoLYLEgNy-qHsBDv6:b5qksml) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/stats/automatic_stats.go#L399)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Looks like this got cut off
</blockquote></details>

Fixed:
```
				// This clears out any tables that may have been added to the
				// mutationCounts map by ensureAllTables and any mutation counts that
				// have been added since the last call to maybeRefreshStats.
				// This is by design. We don't want to constantly refresh tables that
				// are read-only. We update settingOverrides also to prevent data races
				// by multiple threads accessing the same map.
```
___
*[pkg/sql/stats/automatic_stats_test.go, line 147 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzRgPNRDX6L7WBQqJin:-MzRoWlO1OOoNCCiMuZ5:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/stats/automatic_stats_test.go#L147)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this benchmark still useful?
</blockquote></details>

Removed



_Code quote:_
```Go
BenchmarkMaybeRefreshStats(b *testing.B) {
```


<!-- Sent from Reviewable.io -->

2022-03-31 02:56 UTC, rytaft reviewed
> Reviewed 7 of 7 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/descriptor.go, line 681 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSfnd68Mrj8KRu1XcF:-MzSfnd68Mrj8KRu1XcG:b-986ppi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/catalog/descriptor.go#L681)):*
> ```Go
> 	// GetStorageParams returns a list of storage parameters for the table.
> 	GetStorageParams(spaceBetweenEqual bool) []string
> 	// NoAutoStatsSettingsOverrides is true if no auto stats related table
> ```

nit: just get rid of the word table -- it's already used two more times
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1533 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzRde-m8CD4xWfzw6MF:-MzSgD6I0RNA1td3VsRu:b8n5cvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/catalog/tabledesc/validate.go#L1533)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Changed function names to:
```
validateAutoStatsEnabled
validateMinStaleRows
validateFractionStaleRows
```
</blockquote></details>

nit: Now you don't need to pass the setting name in -- you can just pass it directly to `verifyProperTableForStatsSetting`
___
*[pkg/sql/paramparse/paramobserver.go, line 604 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSgwFO9VYq9_zjiBqG:-MzSgwFO9VYq9_zjiBqH:b-ok1veu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/paramparse/paramobserver.go#L604)):*
> ```Go
> }
> 
> func tableSettingResetFunc(
> ```

nit: change this to autoStatsTableSettingResetFunc
___
*[pkg/sql/paramparse/paramobserver.go, line 613 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSo4N-6vQumAf-BD7M:-MzSo4N098Nk7KFdJtXU:b-lktxku) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/paramparse/paramobserver.go#L613)):*
> ```Go
> }
> 
> func resetValue(settingName string, autoStatsSettings *catpb.AutoStatsSettings) error {
> ```

Does this need to be a separate function? Why not just put it in the previous one?
___
*[pkg/sql/paramparse/paramobserver.go, line 655 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSp2h564Con1-EGUJW:-MzSp2h638wBflmwhCuj:b-1bxwqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/paramparse/paramobserver.go#L655)):*
> ```Go
> }
> 
> func setBoolValue(
> ```

This function and the ones below also have generic names even though they are specific to stats.

It also feels like all of this logic is a lot more complicated than the set/reset functions for the ttl stuff and I don't fully appreciate why. Could you add a comment to explain the need for the complexity or else simplify?
___
*[pkg/sql/stats/automatic_stats.go, line 402 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSphkdElR6mQ7xv6qf:-MzSphkdElR6mQ7xv6qg:bvanmlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/stats/automatic_stats.go#L402)):*
> ```Go
> 				// by multiple threads accessing the same map.
> 				r.mutationCounts = make(map[descpb.ID]int64, len(r.mutationCounts))
> 				r.settingOverrides = make(map[descpb.ID]catpb.AutoStatsSettings)
> ```

I think I see now what you were trying to do before with copying this map based on the IDs. Feel free to put it back how it was, just make sure you add a detailed comment to explain.

(i.e., remove this line, and copy only the values of `r.settingOverrides` above that are contained in `r.mutationCounts`. Alternatively use a concurrent hash map as you were also considering previously)

Sorry I was slow to see what was going on.


<!-- Sent from Reviewable.io -->

2022-04-04 05:11 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/catalog/descriptor.go, line 681 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSfnd68Mrj8KRu1XcF:-MzmnjsLD9c-ksVzUsZm:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/catalog/descriptor.go#L681)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: just get rid of the word table -- it's already used two more times
</blockquote></details>

Done



_Code quote:_
```Go
// NoAutoStatsSettingsOverrides is true if no auto stats related table
```
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1533 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzRde-m8CD4xWfzw6MF:-Mzmoc6g7KZKs4JPoVXp:b-jx322i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f55f0df25635d95755657c9b5b4195e7a015328/pkg/sql/catalog/tabledesc/validate.go#L1533)):*
> validateAutoStatsEnabled

Fixed
___
*[pkg/sql/paramparse/paramobserver.go, line 604 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSgwFO9VYq9_zjiBqG:-MzmpCdi2tliv2MTDq7o:b-9k3evq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/paramparse/paramobserver.go#L604)):*
> autoStatsTableSettingResetFunc

Done
___
*[pkg/sql/paramparse/paramobserver.go, line 613 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSo4N-6vQumAf-BD7M:-MzmpsPlEY329HoR2Oxv:b-ndox5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/paramparse/paramobserver.go#L613)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Does this need to be a separate function? Why not just put it in the previous one?
</blockquote></details>

A remnant of when this was to be a more generalized function; combined this into `autoStatsTableSettingResetFunc`.



_Code quote:_
```Go
resetValue(
```
___
*[pkg/sql/paramparse/paramobserver.go, line 655 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSp2h564Con1-EGUJW:-MzmqE6T3IrJNOM1ozfh:b4w2491) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/paramparse/paramobserver.go#L655)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This function and the ones below also have generic names even though they are specific to stats.

It also feels like all of this logic is a lot more complicated than the set/reset functions for the ttl stuff and I don't fully appreciate why. Could you add a comment to explain the need for the complexity or else simplify?
</blockquote></details>

This was intended to handle any cluster settings that could be set at the table level, so I was trying to make this more generalized, to enable future code re-use (so we'd simply add a new case in the switch statement and a new validate function, and be good to go).  Since this approach was rejected, there's no need for the generalized functions now.  I've changed these to specialized functions.



_Code quote:_
```Go
setBoolValue(
```
___
*[pkg/sql/stats/automatic_stats.go, line 402 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSphkdElR6mQ7xv6qf:-Mzmub7Q5beb9K_z-wI_:b-kw6bsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/stats/automatic_stats.go#L402)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think I see now what you were trying to do before with copying this map based on the IDs. Feel free to put it back how it was, just make sure you add a detailed comment to explain.

(i.e., remove this line, and copy only the values of `r.settingOverrides` above that are contained in `r.mutationCounts`. Alternatively use a concurrent hash map as you were also considering previously)

Sorry I was slow to see what was going on.
</blockquote></details>

No worries.  I'm not sure what the best approach is.  The current state of the code is the simplest and ensures no data races.  Also, we only copy settings over that are actually set, so in the default case this map will be empty anyway.  I'm thinking I don't want to rush to merge this feature in because on average build and test times seem a little higher than without the feature.  Maybe I'll do some more test runs and/or profiling or we can discuss it further if you see any obvious inefficiencies.


<!-- Sent from Reviewable.io -->

2022-04-04 15:49 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> modulo comments from others

> Reviewed 7 of 19 files at r15, 3 of 11 files at r18, 2 of 7 files at r20, 4 of 22 files at r24, 4 of 7 files at r26, 9 of 9 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-MzpG4aiAiwJhei-uhly:b-cvewvs)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/alter_table.go, line 1963 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mzp0gh474gv6VWx2w1i:-Mzp0gh474gv6VWx2w1j:b-hhq00f) ([raw file](https://github.com/cockroachdb/cockroach/blob/629a6c271ef3664ac99369a07fc1e41cacc12ab7/pkg/sql/alter_table.go#L1963)):*
> ```Go
> 	params runParams, oldTableHasAutoStatsSettings, newTableHasAutoStatsSettings bool,
> ) error {
> 	if !oldTableHasAutoStatsSettings && !newTableHasAutoStatsSettings {
> ```

If the table already has auto-stats settings but the cluster upgrade has not been finalized, this logic will prevent changing table storage params that are unrelated to auto-stats. Maybe that's ok?
___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 2468 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzpCINL3BHrAG020iJi:-MzpCINL3BHrAG020iJj:b-esli7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/629a6c271ef3664ac99369a07fc1e41cacc12ab7/pkg/sql/logictest/testdata/logic_test/alter_table#L2468)):*
> ```
>     AND tbl.drop_time IS NULL
> ----
> {"fractionStaleRows": 0.15, "minStaleRows": "1234"}
> ```

Is `"1234"` suppose to be a string and not an integer?
___
*[pkg/sql/catalog/tabledesc/validate_test.go, line 2207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoTE9u-KwhZh4YIo4z:-MzpDPZV7Uql71VlyPGn:b-3qprb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/validate_test.go#L2207)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, but the test wasn't running properly without it.  The value of `i` was not properly getting set in the main test loop and some of the `TableDescriptor` fields that had initializations were not seeing those values.
</blockquote></details>

Hmm, I can't see how that's possible.


<!-- Sent from Reviewable.io -->

2022-04-04 16:05 UTC, rytaft reviewed
> Reviewed 9 of 9 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/stats/automatic_stats.go, line 402 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSphkdElR6mQ7xv6qf:-MzpHoc2Bi-8QqMgi34D:b-buwz3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/stats/automatic_stats.go#L402)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

No worries.  I'm not sure what the best approach is.  The current state of the code is the simplest and ensures no data races.  Also, we only copy settings over that are actually set, so in the default case this map will be empty anyway.  I'm thinking I don't want to rush to merge this feature in because on average build and test times seem a little higher than without the feature.  Maybe I'll do some more test runs and/or profiling or we can discuss it further if you see any obvious inefficiencies.
</blockquote></details>

Sounds good. The only issue with leaving it as-is is that refreshes that are retried (via messages on the `mutations` channel in `maybeRefreshStats`) might not have the setting overrides set if there have been no additional mutations before the refresh is retried.

So in this case I'm not really worried about inefficiencies -- just that we might miss some setting overrides.


<!-- Sent from Reviewable.io -->

2022-04-04 16:56 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/alter_table.go, line 1963 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mzp0gh474gv6VWx2w1i:-MzpL6gg7l_nqZgKog5C:b-fpakm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/629a6c271ef3664ac99369a07fc1e41cacc12ab7/pkg/sql/alter_table.go#L1963)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If the table already has auto-stats settings but the cluster upgrade has not been finalized, this logic will prevent changing table storage params that are unrelated to auto-stats. Maybe that's ok?
</blockquote></details>

This is desirable because allowing the ALTER TABLE to proceed would cause the auto-stats settings to be removed on the un-upgraded nodes if processing occurs there, when the user is not specifying to remove them.  We probably wouldn't get into this situation anyway because the user wouldn't be allowed to add the auto-stats settings in the first place until the upgrade completed, so it would have to be a backdown then re-upgrade scenario.



_Code quote:_
```Go
checkDisallowedAutoStatsSettingChange
```
___
*[pkg/sql/stats/automatic_stats.go, line 402 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSphkdElR6mQ7xv6qf:-MzpPSQ_6bJUIW9UEXhA:bh82c8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/stats/automatic_stats.go#L402)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Sounds good. The only issue with leaving it as-is is that refreshes that are retried (via messages on the `mutations` channel in `maybeRefreshStats`) might not have the setting overrides set if there have been no additional mutations before the refresh is retried.

So in this case I'm not really worried about inefficiencies -- just that we might miss some setting overrides.
</blockquote></details>

Ah, right.  This PR has gone through so many iterations, I forgot about this point.  It's still possible that looking up table descriptors will perform better.  Maybe it's the extra `case` in the `select` `for` loop that's adding some overhead.  The `for` loop with the `select` is in the main refresher thread, but looking up table descriptors would occur in the separate thread and not affect the performance of the refresher.  It turns out the concurrent hash map I was talking about the other day is only meant for append-only maps, so unless we pull in some third-party solution we'd probably have to write our own (though maybe we already have done so in some other package).
___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 2468 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzpCINL3BHrAG020iJi:-MzpQttG4fBWYF4hwKdp:b-2az542) ([raw file](https://github.com/cockroachdb/cockroach/blob/629a6c271ef3664ac99369a07fc1e41cacc12ab7/pkg/sql/logictest/testdata/logic_test/alter_table#L2468)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is `"1234"` suppose to be a string and not an integer?
</blockquote></details>

This is just the behavior of the `crdb_internal.pb_to_json` function.  I don't know why it decodes `int64` to a string, but not the `float64`, but this would be the same for other protobuf structures and was not changed by this PR.  The `SHOW CREATE TABLE` output at the end of the alter_table logic test prints these as a float and int.



_Code quote:_
```
crdb_internal.pb_to_json
```
___
*[pkg/sql/catalog/tabledesc/validate_test.go, line 2207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyoTE9u-KwhZh4YIo4z:-MzpLx4485kSYMwsQxdM:b-dr85al) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc99843deb09975a6ca8fb45bac4aa0b28d5383/pkg/sql/catalog/tabledesc/validate_test.go#L2207)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmm, I can't see how that's possible.
</blockquote></details>

Alright.  I did see this behavior though, and was mystified by it.  I don't think it's worth the time to pull up the old revision and re-test it.  These tests have since been moved out of this location.


<!-- Sent from Reviewable.io -->

2022-04-05 16:43 UTC, mgartner approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/alter_table.go, line 1963 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-Mzp0gh474gv6VWx2w1i:-MzuaTvF6sdgI1ScbmJQ:b-l0jfnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/629a6c271ef3664ac99369a07fc1e41cacc12ab7/pkg/sql/alter_table.go#L1963)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

This is desirable because allowing the ALTER TABLE to proceed would cause the auto-stats settings to be removed on the un-upgraded nodes if processing occurs there, when the user is not specifying to remove them.  We probably wouldn't get into this situation anyway because the user wouldn't be allowed to add the auto-stats settings in the first place until the upgrade completed, so it would have to be a backdown then re-upgrade scenario.
</blockquote></details>

Makes sense. Thanks for explaining.
___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 2468 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzpCINL3BHrAG020iJi:-MzuabqC9af2Taye2ruR:b-a7jug4) ([raw file](https://github.com/cockroachdb/cockroach/blob/629a6c271ef3664ac99369a07fc1e41cacc12ab7/pkg/sql/logictest/testdata/logic_test/alter_table#L2468)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

This is just the behavior of the `crdb_internal.pb_to_json` function.  I don't know why it decodes `int64` to a string, but not the `float64`, but this would be the same for other protobuf structures and was not changed by this PR.  The `SHOW CREATE TABLE` output at the end of the alter_table logic test prints these as a float and int.
</blockquote></details>

I see. Thanks for the explanation!


<!-- Sent from Reviewable.io -->

2022-04-05 16:47 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/alter_table, line 2468 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzpCINL3BHrAG020iJi:-MzubfEw5M9fRbquVVjJ:b9ul9d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/629a6c271ef3664ac99369a07fc1e41cacc12ab7/pkg/sql/logictest/testdata/logic_test/alter_table#L2468)):*
> I don't know why it decodes int64 to a string, but not the float64

Json numbers are float64s, so they can safely round-trip by using the number type in json. Int64 might not fit in a float64 in a lossless way, so it gets encoded as a string always.  


<!-- Sent from Reviewable.io -->

2022-04-26 00:29 UTC, otan approved these changes

2022-04-26 00:29 UTC, otan commented on pkg/sql/catalog/catpb/catalog.proto
>    optional bool enabled = 1;
nit: comments are usually `Enabled represents ...`

2022-04-26 03:31 UTC, msirek reviewed
TFTRs!  I thought there was a remaining performance issue, but it turns out the build is just running some additional maybe_stress and maybe_stressrace tests, which account for the extra time taken. I plan on merging this tomorrow (April 26). Please let me know if anyone has any more review comments coming.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-N0YsJOd1bXPyaseE5N4:b-vzu6rd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[`pkg/sql/catalog/catpb/catalog.proto` line 229 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MyUKFC5eExnCWfUW5qR-r28-229:-N0Ys5Aj6q7wpuxQF0bq:b-euf8rv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3784d803839916c4d43cca2a85fed2972fd7b9d8/pkg/sql/catalog/catpb/catalog.proto#L229)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: comments are usually `Enabled represents ...`
</blockquote></details>

Updated comments to start with the field name.



_Code quote:_
```protobuf
message AutoStatsSettings {
```
___
*[`pkg/sql/logictest/testdata/logic_test/alter_table` line 2468 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzpCINL3BHrAG020iJi:-N0YsCKJ5svieZjrHooA:b-wsvas3) ([raw file](https://github.com/cockroachdb/cockroach/blob/629a6c271ef3664ac99369a07fc1e41cacc12ab7/pkg/sql/logictest/testdata/logic_test/alter_table#L2468)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> I don't know why it decodes int64 to a string, but not the float64

Json numbers are float64s, so they can safely round-trip by using the number type in json. Int64 might not fit in a float64 in a lossless way, so it gets encoded as a string always.  

</blockquote></details>

Thanks for the explanation.


<!-- Sent from Reviewable.io -->

2022-04-26 15:32 UTC, rytaft reviewed
> Reviewed 9 of 9 files at r28, 3 of 3 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[`pkg/sql/stats/automatic_stats.go` line 402 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSphkdElR6mQ7xv6qf:-N0aUTJ87YRn70xKMRTs:b-gnnov1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/stats/automatic_stats.go#L402)):*
Still seems worthwhile to make this change to avoid missing the setting overrides during retries:

> remove this line, and copy only the values of r.settingOverrides above that are contained in r.mutationCounts

I'm also fine with doing that in a follow-on PR if you just want to get this merged.


<!-- Sent from Reviewable.io -->

2022-04-28 01:56 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[`pkg/sql/stats/automatic_stats.go` line 402 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSphkdElR6mQ7xv6qf:-N0hdWuDBRBOszDa1CcC:bwmawql) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/stats/automatic_stats.go#L402)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Still seems worthwhile to make this change to avoid missing the setting overrides during retries:

> remove this line, and copy only the values of r.settingOverrides above that are contained in r.mutationCounts

I'm also fine with doing that in a follow-on PR if you just want to get this merged.
</blockquote></details>

OK, I removed the line:
```
r.settingOverrides = make(map[descpb.ID]catpb.AutoStatsSettings)
```
... and re-added the code to build a local `settingOverrides` map. 
I realized that `settingOverrides` may get stale with long-running stats collection jobs, so have added table header lookups in the case where processing a given table mutation count starts more than 1 minute (`DefaultRefreshInterval`) after `mutationCounts` processing has started.


<!-- Sent from Reviewable.io -->

2022-05-02 17:57 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[`pkg/sql/stats/automatic_stats.go` line 402 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSphkdElR6mQ7xv6qf:-N14u-hzDX0p1OYwsuKS:b-1ty75n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/stats/automatic_stats.go#L402)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, I removed the line:
```
r.settingOverrides = make(map[descpb.ID]catpb.AutoStatsSettings)
```
... and re-added the code to build a local `settingOverrides` map. 
I realized that `settingOverrides` may get stale with long-running stats collection jobs, so have added table header lookups in the case where processing a given table mutation count starts more than 1 minute (`DefaultRefreshInterval`) after `mutationCounts` processing has started.

</blockquote></details>

@rytaft  When you get the chance, please let me know if you have any comments on the new code to look up table headers if the recorded settings are more than a minute old.  Thanks.


<!-- Sent from Reviewable.io -->

2022-05-02 19:30 UTC, rytaft reviewed
> Reviewed 11 of 11 files at r30, 2 of 2 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @msirek, @otan, @postamar, @rharding6373, and @rytaft)

___
*[`pkg/sql/stats/automatic_stats.go` line 402 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSphkdElR6mQ7xv6qf:-N158fDq7A9QYnD7fOKy:b2c5wy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/stats/automatic_stats.go#L402)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

@rytaft  When you get the chance, please let me know if you have any comments on the new code to look up table headers if the recorded settings are more than a minute old.  Thanks.
</blockquote></details>

Sorry for the delay!
___
*[`pkg/sql/stats/automatic_stats.go` line 377 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-N153NSB4xGe9UrV0kZy:-N153B3dB7qTn6C8WywT:b-vkmfu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/09127aaf9f1929cc2030387856128099a32af668/pkg/sql/stats/automatic_stats.go#L377)):*
> ```Go
> 				mutationCounts := r.mutationCounts
> 
> 				settingOverrides := make(map[descpb.ID]catpb.AutoStatsSettings)
> ```

nit: you could wait to allocate this map until it's needed below
___
*[`pkg/sql/stats/automatic_stats.go` line 429 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-N155j5i5LCztILbCbBg:-N155j5i5LCztILbCbBh:b-mtfdi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/09127aaf9f1929cc2030387856128099a32af668/pkg/sql/stats/automatic_stats.go#L429)):*
> ```Go
> 									useDescriptor = false
> 								}
> 							}
> ```

This logic seems convoluted. I'd suggest removing the `useDescriptor` boolean and doing something like this:

```
now := timeutil.Now()
elapsed := now.Sub(start)
// If a long-running stats collection caused a delay in
// processing the current table longer than the refresh
// interval, look up the table descriptor to ensure we don't
// have stale table settings.
if elapsed > DefaultRefreshInterval {
  desc = r.getTableDescriptor(ctx, tableID)
  if desc != nil {
    if !r.autoStatsEnabled(desc) {
      continue
    }
    settingOverrides[tableID] = desc.GetAutoStatsSettings()  
  }
}
```


<!-- Sent from Reviewable.io -->

2022-05-02 22:21 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[`pkg/sql/stats/automatic_stats.go` line 402 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-MzSphkdElR6mQ7xv6qf:-N15nPVC8DXo3cXftuyS:b-uzuz3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4369786dbb2e06dd3a660d607b53811d89d661e/pkg/sql/stats/automatic_stats.go#L402)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Sorry for the delay!
</blockquote></details>

No worries.  Thanks for all the great comments! 
___
*[`pkg/sql/stats/automatic_stats.go` line 377 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-N153NSB4xGe9UrV0kZy:-N15jlQ8-2sRkeoao3hD:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/09127aaf9f1929cc2030387856128099a32af668/pkg/sql/stats/automatic_stats.go#L377)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: you could wait to allocate this map until it's needed below
</blockquote></details>

Done



_Code quote:_
```Go
settingOverrides := make(map[descpb.ID]catpb.AutoStatsSettings)
```
___
*[`pkg/sql/stats/automatic_stats.go` line 429 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-N155j5i5LCztILbCbBg:-N15lNU_5S-qWsqUWEuY:bv6awap) ([raw file](https://github.com/cockroachdb/cockroach/blob/09127aaf9f1929cc2030387856128099a32af668/pkg/sql/stats/automatic_stats.go#L429)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This logic seems convoluted. I'd suggest removing the `useDescriptor` boolean and doing something like this:

```
now := timeutil.Now()
elapsed := now.Sub(start)
// If a long-running stats collection caused a delay in
// processing the current table longer than the refresh
// interval, look up the table descriptor to ensure we don't
// have stale table settings.
if elapsed > DefaultRefreshInterval {
  desc = r.getTableDescriptor(ctx, tableID)
  if desc != nil {
    if !r.autoStatsEnabled(desc) {
      continue
    }
    settingOverrides[tableID] = desc.GetAutoStatsSettings()  
  }
}
```


</blockquote></details>

OK, the point about `useDescriptor` was to avoid recalculating the elapsed time if we have already exceeded the time limit and to avoid calling `autoStatsEnabledForTableID` twice.  I have removed `useDescriptor` as suggested.  I've moved the declaration of `desc` to within the `for` loop so I could avoid a duplicate call to `autoStatsEnabledForTableID` without adding another variable.


<!-- Sent from Reviewable.io -->

2022-05-03 11:51 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> ship it!

> Reviewed 7 of 7 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-N18keCg54R0zbhW9nfN:b-quxs7z)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)

___
*[`pkg/sql/stats/automatic_stats.go` line 429 at r30](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-N155j5i5LCztILbCbBg:-N18hQ4XACqDqtCgZ-pA:b-fuht5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/09127aaf9f1929cc2030387856128099a32af668/pkg/sql/stats/automatic_stats.go#L429)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, the point about `useDescriptor` was to avoid recalculating the elapsed time if we have already exceeded the time limit and to avoid calling `autoStatsEnabledForTableID` twice.  I have removed `useDescriptor` as suggested.  I've moved the declaration of `desc` to within the `for` loop so I could avoid a duplicate call to `autoStatsEnabledForTableID` without adding another variable.
</blockquote></details>

Thanks, I think this is easier to understand now. 


<!-- Sent from Reviewable.io -->

2022-05-03 13:04 UTC, msirek reviewed
TFTR!
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78110#-:-N1907DF72UAcDWoaK6R:bihs03x)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @mgartner, @otan, @postamar, @rharding6373, and @rytaft)



<!-- Sent from Reviewable.io -->

2022-05-03 15:24 UTC, merged