distsql: clean up the determination of txn type in mixed version
cockroachdb/cockroach pull request #78195
Opened 2022-03-21 18:06 UTC by yuzefovich

This commit cleans up the way we determine what txn type to use for
a particular flow.

Release note: None

2022-03-21 18:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/78195)
<!-- Reviewable:end -->

2022-03-21 19:51 UTC, yuzefovich commented
I've been unable to reproduce the problem locally nor on the gceworker, and I don't have much confidence in this fix, so the issue is not closed at the moment. I also don't have any other ideas of what could be the root cause of the issue, so let's merge this change, and let the nightly job tell us whether the problem goes away.

2022-03-21 22:40 UTC, rharding6373 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/distsql/server.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78195#-MyicDoP1XqQb4llEO-Z:-MyicDoP1XqQb4llEO-_:bpimsz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/65e66152bb48e95616812a9311db52d7d0de6273/pkg/sql/distsql/server.go#L413)):*
> ```Go
> 	// we create, if necessary, a txn based on the request's LeafTxnInputState.
> 	var txn *kv.Txn
> 	if localState.IsLocal && !f.ConcurrentTxnUse() && leafTxn == nil {
> ```

This does seem cleaner, but is there a case where a `leafTxn` was already created but we actually want to use `localState.Txn`? I'm trying to understand the motivation behind what was previously here and avoid introducing other issues.
___
*[pkg/sql/distsql/server.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78195#-MyibDXu2Nfx_AP9TDgO:-MyibDXu2Nfx_AP9TDgP:b-6h2q7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3525c95b176f7520173e7a6d3e4a93dca86b198/pkg/sql/distsql/server.go#L417)):*
> ```Go
> 		for _, proc := range req.Flow.Processors {
> 			if jr := proc.Core.JoinReader; jr != nil {
> 				if jr.IsIndexJoin() {
> ```

Assuming that this is where the non-leaf txn is being created for the streamer, I think that your other fix in https://github.com/cockroachdb/cockroach/pull/78208 to disable streamer for lookup joins might resolve this issue. I can imagine that before that fix, `jr` could have been a lookup join, `useLeaf` was left as false so we used `localState.Txn` below, and the txn still used the streamer.


<!-- Sent from Reviewable.io -->

2022-03-22 00:24 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

___
*[pkg/sql/distsql/server.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78195#-MyicDoP1XqQb4llEO-Z:-Myj-SwzDlY89fKYzBJe:b-m2yen0) ([raw file](https://github.com/cockroachdb/cockroach/blob/65e66152bb48e95616812a9311db52d7d0de6273/pkg/sql/distsql/server.go#L413)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

This does seem cleaner, but is there a case where a `leafTxn` was already created but we actually want to use `localState.Txn`? I'm trying to understand the motivation behind what was previously here and avoid introducing other issues.
</blockquote></details>

Things are actually in the "opposite" direction. `localState.Txn` is the RootTxn (and the root txn is always created), and that field is only initialized on the gateway node for the plan. Before the introduction of the Streamer logic, we would use the root txn only for plans that consist of a single flow on the gateway (`localState.IsLocal` is true) and if that single flow that doesn't have any internal concurrency (`f.ConcurrentTxnUse()` is false). The streamer is the first component that can have internal concurrency, so we have to add an additional condition now when the root txn cannot be used. If a leaf txn was already created, then there must have been a reason for doing so, and here it doesn't really matter what it was - if we already have a leaf txn, then we must use it.
___
*[pkg/sql/distsql/server.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78195#-MyibDXu2Nfx_AP9TDgO:-MyizN-RC_bRSvwnYiNa:b4a78ad) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3525c95b176f7520173e7a6d3e4a93dca86b198/pkg/sql/distsql/server.go#L417)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Assuming that this is where the non-leaf txn is being created for the streamer, I think that your other fix in https://github.com/cockroachdb/cockroach/pull/78208 to disable streamer for lookup joins might resolve this issue. I can imagine that before that fix, `jr` could have been a lookup join, `useLeaf` was left as false so we used `localState.Txn` below, and the txn still used the streamer.
</blockquote></details>

That's a good point - :crossed_fingers: 


<!-- Sent from Reviewable.io -->

2022-03-22 00:32 UTC, rharding6373 approved these changes
Sounds like this is overall a good change and unlikely to break anything so <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78195#-:-Myj1DUUA3TW5OKL7wha:b-yrjtj7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)



<!-- Sent from Reviewable.io -->

2022-03-22 00:55 UTC, yuzefovich commented
TFTR!

bors r+

2022-03-22 06:47 UTC, merged

2022-06-13 15:54 UTC, yuzefovich commented
blathers backport 22.1