sql: use soft and hard limits in lookup and index joins
cockroachdb/cockroach pull request #78224
Opened 2022-03-22 04:35 UTC by yuzefovich

Previously, during the execution of lookup and index joins we completely
ignored the soft and hard limits and, instead, always fetched up to the
memory-based limit (which depends on the type of the join). This could
lead to having to read many more rows from the input and then looking up
many more rows from the KV layer than necessary.

This is now fixed by plumbing the soft and hard limits from the
optimizer and using them when sizing the batches of input rows to
perform lookup for. For index joins we know for sure that every input
row will get a looked up row; however, for lookup joins an input row
might result in a miss. To work around this we use a simple heuristic
for determining the limit-hint-based size of input batches: for the
first batch we use the limit hint as is, for the second batch we use 10x
of the original hint, and for the third and all consequent batches we
disable the limiting behavior altogether.

TODO: add tests.

Fixes: #77715.

Release note (bug fix): CockroachDB might now fetch less rows when
performing lookup and index joins on the queries with LIMIT clause.

2022-03-22 04:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/78224)
<!-- Reviewable:end -->

2022-03-23 22:04 UTC, rharding6373 requested changes
Hard to believe we didn't have this already! Nice.

> Reviewed 5 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-:-MysnY61-eJYbTIgLWyz:b-rq2b3d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/execinfra/readerbase.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-MysjJML0eazYAxKqaxX:-MysjJML0eazYAxKqaxY:baw0yi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4825bca217b276a4bd9ea25f0959082d7124a0c/pkg/sql/execinfra/readerbase.go#L129)):*
> ```Go
> 
> // LookupJoinLimitHelper is used for lookup and index joins in order to limit
> // batches of input rows in the presence of hard and soft limits.
> ```

Some of the nuance in `ReadSomeRows` deserves to be noted in the comment here or in field comments. E.g.:
* `currentLimitHint` of 0 means limits are disabled.
* We ignore the limit after`limitHintIdx` hits 2 or higher
* `limitHintIdx` is the number of times we've read the limit number of rows.
___
*[pkg/sql/execinfra/readerbase.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-MysfS2H-2tlSgZsLlVS:-MysfS2H-2tlSgZsLlVT:b-2nro50) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4825bca217b276a4bd9ea25f0959082d7124a0c/pkg/sql/execinfra/readerbase.go#L154)):*
> ```Go
> func (h *LookupJoinLimitHelper) ReadSomeRows(rowsRead int64) {
> 	if h.currentLimitHint != 0 {
> 		h.currentLimitHint -= rowsRead
> ```

It would be good to check that `rowsRead < h.currentLimitHint` or that `h.currentLimitHint <= 0` below. Assuming that `rowsRead` is always >= `currentLimitHint` relies on a close coupling between the user and this implementation, which is fragile. Better to have some defense in depth.
___
*[pkg/sql/execinfra/readerbase.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-MyskILk9MSaXdbL5LSC:-MyskILlEB-kKyEgd8i4:b-t1690h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4825bca217b276a4bd9ea25f0959082d7124a0c/pkg/sql/execinfra/readerbase.go#L165)):*
> ```Go
> 			// off or many input rows result in lookup misses.
> 			h.limitHintIdx++
> 			if h.limitHintIdx == 1 {
> ```

nit: consider moving 1 to a const as well.
___
*[pkg/sql/execinfra/readerbase.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-Mysf1fdAA6JulgzliTm:-Mysf1fdAA6JulgzliTn:b1u1v5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4825bca217b276a4bd9ea25f0959082d7124a0c/pkg/sql/execinfra/readerbase.go#L166)):*
> ```Go
> 			h.limitHintIdx++
> 			if h.limitHintIdx == 1 {
> 				h.currentLimitHint = 10 * h.origLimitHint
> ```

nit: move 10 into a const for easier tuning in the future.


<!-- Sent from Reviewable.io -->

2022-03-24 02:57 UTC, yuzefovich reviewed
I was too surprised that we haven't hit a customer problem because of this issue before - the code as is hasn't been changed in like three years now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-:-MytqPRqCGBwWBZg80ax:b-iiyuge)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @rharding6373)

___
*[pkg/sql/execinfra/readerbase.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-MysjJML0eazYAxKqaxX:-Mytprm4Bd-5w5jPcvCx:b1n17te) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4825bca217b276a4bd9ea25f0959082d7124a0c/pkg/sql/execinfra/readerbase.go#L129)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Some of the nuance in `ReadSomeRows` deserves to be noted in the comment here or in field comments. E.g.:
* `currentLimitHint` of 0 means limits are disabled.
* We ignore the limit after`limitHintIdx` hits 2 or higher
* `limitHintIdx` is the number of times we've read the limit number of rows.
</blockquote></details>

Refactored the code a bit and provided more commentary.
___
*[pkg/sql/execinfra/readerbase.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-MysfS2H-2tlSgZsLlVS:-Mytpl6DDiscv8BRitpX:b-ijpcn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4825bca217b276a4bd9ea25f0959082d7124a0c/pkg/sql/execinfra/readerbase.go#L154)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It would be good to check that `rowsRead < h.currentLimitHint` or that `h.currentLimitHint <= 0` below. Assuming that `rowsRead` is always >= `currentLimitHint` relies on a close coupling between the user and this implementation, which is fragile. Better to have some defense in depth.
</blockquote></details>

Good point. Added an assertion that `rowsRead <= h.currentLimitHint`.
___
*[pkg/sql/execinfra/readerbase.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-MyskILk9MSaXdbL5LSC:-Mytq0ry6GGKa8TBmfnP:byg433c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4825bca217b276a4bd9ea25f0959082d7124a0c/pkg/sql/execinfra/readerbase.go#L165)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: consider moving 1 to a const as well.
</blockquote></details>

Refactored.


<!-- Sent from Reviewable.io -->

2022-03-24 17:18 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-:-MywvLR-A45B9rBevKbD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/execinfra/readerbase.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-MysjJML0eazYAxKqaxX:-Mywv49-8KhnGVn8csQ0:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4825bca217b276a4bd9ea25f0959082d7124a0c/pkg/sql/execinfra/readerbase.go#L129)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Refactored the code a bit and provided more commentary.
</blockquote></details>

Thanks!
___
*[pkg/sql/execinfra/readerbase.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-MywjsNw1jAUnQJB3uM3:-MywjsNw1jAUnQJB3uM4:bzez84t) ([raw file](https://github.com/cockroachdb/cockroach/blob/be12022232d4d143765df213062248bfc3c28a84/pkg/sql/execinfra/readerbase.go#L131)):*
> ```Go
> // ljLimitHintIndex tracks how many times the caller has read LimitHint() number
> // of rows.
> type ljLimitHintIndex int
> ```

nit: something like ljLimitBatchCount would be a better name.
___
*[pkg/sql/execinfra/readerbase.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-MywkPyq60XBuAxF9-2g:-MywkPyq60XBuAxF9-2h:b-p4th2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/be12022232d4d143765df213062248bfc3c28a84/pkg/sql/execinfra/readerbase.go#L146)):*
> ```Go
> // LookupJoinLimitHelper is used for lookup and index joins in order to limit
> // batches of input rows in the presence of hard and soft limits.
> type LookupJoinLimitHelper struct {
> ```

Can we just call this LimitHelper or LimitHintHelper?


<!-- Sent from Reviewable.io -->

2022-03-24 17:25 UTC, yuzefovich reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-:-MywxWxN4SEopLaEPuI8:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)

___
*[pkg/sql/execinfra/readerbase.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-MywkPyq60XBuAxF9-2g:-Mywx4T918GKWehFT7wV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be12022232d4d143765df213062248bfc3c28a84/pkg/sql/execinfra/readerbase.go#L146)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Can we just call this LimitHelper or LimitHintHelper?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-24 20:45 UTC, cucaroach reviewed
Cool, TIL you can use explain analyze in an execbuilder test!   <img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 14 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78224#-:-MyxfEvrA1-Ul1LYLdzu:b2mjxz1)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)



<!-- Sent from Reviewable.io -->

2022-03-24 23:07 UTC, yuzefovich commented
bors r+

2022-03-25 02:04 UTC, yuzefovich commented
bors r+

2022-03-25 03:23 UTC, merged