ui: Hide table stats collection setting for non-admins
cockroachdb/cockroach pull request #78266
Opened 2022-03-22 16:30 UTC by ericharmeling

This PR hides the table statistics collection setting from non-admins in the DB Console.

https://user-images.githubusercontent.com/27286675/159527957-6eced87b-f5cb-481f-923f-1e5a694dcf09.mov

Part 1/2 of https://github.com/cockroachdb/cockroach/issues/77974.

(For background, see https://github.com/cockroachdb/cockroach/issues/77974#issuecomment-1072656497)

Release justification: low-risk change

Release note: None

2022-03-22 16:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/78266)
<!-- Reviewable:end -->

2022-03-22 18:26 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx, line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78266#-MymsI3W6WXQ7Alx_rN1:-MymsI3W6WXQ7Alx_rN2:b2nzkts) ([raw file](https://github.com/cockroachdb/cockroach/blob/d701ea29fca8652592a49f64bd26161107063f9e/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L298)):*
> ```XML
>         <div className={baseHeadingClasses.wrapper}>
>           <h3 className={baseHeadingClasses.tableName}>Databases</h3>
>           {this.props.automaticStatsCollectionEnabled && (
> ```

with this change if an admin user has this value set to false, it wouldn't show the value, but we still want to show it


<!-- Sent from Reviewable.io -->

2022-03-22 20:07 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx, line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78266#-MymsI3W6WXQ7Alx_rN1:-Myn19SQ5nUdgrizx8JA:b-idv9mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d701ea29fca8652592a49f64bd26161107063f9e/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L298)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

with this change if an admin user has this value set to false, it wouldn't show the value, but we still want to show it
</blockquote></details>

Fixed! (also updated the video to show the "disabled" case)


<!-- Sent from Reviewable.io -->

2022-03-22 21:05 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78266#-:-MynRjdy4SwdQoaf8LIv:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx, line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78266#-MymsI3W6WXQ7Alx_rN1:-MynRiB747XH-dgUnAbb:bccpe83) ([raw file](https://github.com/cockroachdb/cockroach/blob/d701ea29fca8652592a49f64bd26161107063f9e/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L298)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Fixed! (also updated the video to show the "disabled" case)
</blockquote></details>

Awesome!


<!-- Sent from Reviewable.io -->

2022-03-23 15:05 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks, @ericharmeling!

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78266#-:-MyrIwW91iXIQhVXogEJ:bger1cl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling)



<!-- Sent from Reviewable.io -->

2022-03-28 15:09 UTC, ericharmeling commented
bors r+

2022-03-28 18:58 UTC, merged