server, sql: expose closed sessions to ListSessions endpoint
cockroachdb/cockroach pull request #78650
Opened 2022-03-28 18:34 UTC by gtr

This is the second phase of #67888 which is to expose closed sessions to
the ListSessions endpoint.

Previously, the ListSessions endpoint only returned open sessions. This
change builds on top of the previous PR to add the `ClosedSessionsCache`
and now allows the ListSessions endpoint to also return closed sessions
in its response. Additionally, the `serverpb.Session` object was updated
to inlcude new `end` and `status` fields which specify the time the
session ended and the status (opened, closed) of the session,
respectively.

Release note (api change): `ListSessions` now returns closed sessions in
addition to open sessions; `serverpb.Session` now has `end` and `status`
fields.

2022-03-28 18:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/78650)
<!-- Reviewable:end -->

2022-03-29 14:43 UTC, maryliag requested changes
can you add tests to verify the new values being returned?

> Reviewed 13 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-:-MzL7PU208nEXPulo1DH:bplqety)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @gtr)

___
*[-- commits, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzL1Ovw9HazFvKRwINt):*
nit: include
___
*[pkg/sql/closed_session_cache.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzL6uL9ACOMJ2wpoU8o:-MzL6uL9ACOMJ2wpoU8p:bncpqdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfbed32835ede7523663d00e0b96636636e2327/pkg/sql/closed_session_cache.go#L31)):*
> ```Go
> 	"sql.closed_session_cache.capacity",
> 	"the maximum number of sessions in the cache",
> 	1000, // TODO(gtr): Totally arbitrary for now, adjust later.
> ```

have you done any testing to adjust this number?
___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzL77908GXoGWyXke9N:-MzL77908GXoGWyXke9O:by7vf8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfbed32835ede7523663d00e0b96636636e2327/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.fixture.ts#L50)):*
> ```XML
>     max_alloc_bytes: Long.fromNumber(10240),
>     active_queries: [],
>     status: Status.OPEN,
> ```

can you add some examples with status closed?


<!-- Sent from Reviewable.io -->

2022-03-29 15:43 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/server/status.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzLJS6GCxwejgR7JBdG:-MzLJS6H66L0Cr-5qf67:bm0z86u) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfbed32835ede7523663d00e0b96636636e2327/pkg/server/status.go#L202)):*
> ```Go
> 	registry := b.sessionRegistry
> 	sessions := registry.SerializeAll()
> 	closedSessions := b.closedSessionCache.GetSerializedSessions()
> ```

Just want to point out a subtle concurrency issue here. 

```golang
// the mutex on the registry is dropped after function returns,
// suppose we have a sessionA in `sessions` since sessionA is active.
sessions := registry.SerializeAll()

/*
 * sessionA finishes. Since mutex on the active session registry is dropped, sessionA moves from
 * the active registry into the closed session cache.
 */

// closedSessions now contains sessionA. The API response now will contain two entries of
// sessionA showing that sessionA is both "active" and "closed" at the same time.
closedSessions := b.closedSessionCache.GetSerializedSessions()
```

You might want to do some manual mutex management here to prevent that from happening. 
___
*[pkg/sql/conn_executor.go, line 1779 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzLKoOa-GkGhhgaLatf:-MzLKoOa-GkGhhgaLatg:b-9qyhlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfbed32835ede7523663d00e0b96636636e2327/pkg/sql/conn_executor.go#L1779)):*
> ```Go
> 	ex.planner.extendedEvalCtx.setSessionID(ex.sessionID)
> 	defer ex.server.cfg.SessionRegistry.deregister(ex.sessionID, ex.queryCancelKey)
> 	defer ex.server.cfg.ClosedSessionCache.add(ex.sessionID, ex.serialize())
> ```

optional style nit: i'd just put two function into a single defer block

```golang
defer func() {
  ex.server.cfg.SessionRegistry.deregistry()
  ex.server.cfg.ClosedSessionCache.add()
}()
```


<!-- Sent from Reviewable.io -->

2022-04-06 16:02 UTC, gtr reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/server/status.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzLJS6GCxwejgR7JBdG:-Mzzb3De52rMTpACHW_-:b-ckg5sv) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfbed32835ede7523663d00e0b96636636e2327/pkg/server/status.go#L202)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Just want to point out a subtle concurrency issue here. 

```golang
// the mutex on the registry is dropped after function returns,
// suppose we have a sessionA in `sessions` since sessionA is active.
sessions := registry.SerializeAll()

/*
 * sessionA finishes. Since mutex on the active session registry is dropped, sessionA moves from
 * the active registry into the closed session cache.
 */

// closedSessions now contains sessionA. The API response now will contain two entries of
// sessionA showing that sessionA is both "active" and "closed" at the same time.
closedSessions := b.closedSessionCache.GetSerializedSessions()
```

You might want to do some manual mutex management here to prevent that from happening. 
</blockquote></details>

Good catch! I locked the session registry while we get the serialized sessions from the closed session cache.
___
*[pkg/sql/conn_executor.go, line 1779 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzLKoOa-GkGhhgaLatf:-MzzazpL0t3i1Q6AKUoK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfbed32835ede7523663d00e0b96636636e2327/pkg/sql/conn_executor.go#L1779)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

optional style nit: i'd just put two function into a single defer block

```golang
defer func() {
  ex.server.cfg.SessionRegistry.deregistry()
  ex.server.cfg.ClosedSessionCache.add()
}()
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-06 16:46 UTC, knz reviewed
I dont see any memory accounting for the new structure. Where can I find it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-:-MzzlD1_6pj84xfajiN1:b-vhj7ec)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)



<!-- Sent from Reviewable.io -->

2022-04-11 15:12 UTC, gtr reviewed
Thanks for the heads up! I embedded a`*mon.BytesMonitor` object inside `ClosedSessionCache`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-:-N-O9SPM379eR-mjlpSf:b2z066x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzL77908GXoGWyXke9N:-N-O9yvxAuVPzFUdvnQJ:b-fuqo5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfbed32835ede7523663d00e0b96636636e2327/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.fixture.ts#L50)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you add some examples with status closed?
</blockquote></details>

I think the scope of the PR is getting a bit long; should these tests be added when i get to the UI part? These were added simply to get rid of compilation errors for the newly added `status` field in `serverpb.Session`. Also note the new `IDLE` status, which is defined in `pkg/sql/conn_executor.go`:

```go
status := serverpb.Session_IDLE
if len(activeQueries) > 0 {
    status = serverpb.Session_OPEN
}
```


<!-- Sent from Reviewable.io -->

2022-04-13 14:55 UTC, maryliag requested changes
> Reviewed 1 of 11 files at r2, 1 of 12 files at r3, 17 of 22 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/server/status.go, line 2757 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YNZI9-1QrwcqKRQhR:-N-YNZI9-1QrwcqKRQhS:b-v1if5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status.go#L2757)):*
> ```Go
> 		}
> 		sessions := nodeResp.([]serverpb.Session)
> 		sort.Slice(sessions, func(i, j int) bool {
> ```

nit: you don't need to do this sort since you are sorting again after appending the sessions
___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.fixture.ts, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzL77908GXoGWyXke9N:-N-YPDhL7G_C-f4DMgj1:b-24c703) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfbed32835ede7523663d00e0b96636636e2327/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.fixture.ts#L50)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

I think the scope of the PR is getting a bit long; should these tests be added when i get to the UI part? These were added simply to get rid of compilation errors for the newly added `status` field in `serverpb.Session`. Also note the new `IDLE` status, which is defined in `pkg/sql/conn_executor.go`:

```go
status := serverpb.Session_IDLE
if len(activeQueries) > 0 {
	status = serverpb.Session_OPEN
}
```
</blockquote></details>

Sure, they can be added during the UI PR. But I would like to see on the PR description some examples of the responses that include open, idle and closed sessions.
___
*[pkg/server/status_test.go, line 3377 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YPn9l-7IP1AN-39OB:-N-YPn9l-7IP1AN-39OC:b-gm4bdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3377)):*
> ```Go
> 		}
> 
> 		require.Equal(t, 5, open)
> ```

Avoid using the same value for 2 different things, because they might be returned switched values and you wouldn't know. Make one value for open and another for closed


<!-- Sent from Reviewable.io -->

2022-04-13 16:31 UTC, Azhng reviewed
> Reviewed 1 of 16 files at r1, 4 of 22 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/server/status.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzLJS6GCxwejgR7JBdG:-N-YkNqRB_cl87g1A74W:b-o11hcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfbed32835ede7523663d00e0b96636636e2327/pkg/server/status.go#L202)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Good catch! I locked the session registry while we get the serialized sessions from the closed session cache.
</blockquote></details>

Hmm, you might want to lock the `sessionRegistry` before calling `.SerializeAll()` (this will result in deadlock, but you can create a new function called `.SerializedAllLocked()`. 

The code currently still have unprotected critical section (between `.SerializeAll()` and the `.Lock()`) which can result in race condition. 
___
*[pkg/sql/closed_session_cache.go, line 176 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YfwJh9dEEoU3JEW0a:-N-YfwJh9dEEoU3JEW0b:bq6x3n9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/sql/closed_session_cache.go#L176)):*
> ```Go
> 	size += 16            // size of ClusterWideID
> 	size += n.data.Size() // size of serverpb.Session
> 	size += 8             // size of time.Time
> ```

You sure `time.Time` only takes 8 bytes? Seems like it has 2 * 64 bit integer + a pointer type. 

```golang
type Time struct {
	wall uint64
	ext  int64

	loc *Location
}

```

A trick here would be 

```golang
unsafe.Sizeof(time.Time{})
```
___
*[pkg/server/status_test.go, line 3265 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YbQBm-iAPoiHtwbdH:-N-YbQBn9M76fYSUAtJx:b-j5wqes) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3265)):*
> ```Go
> 		ReplicationMode: base.ReplicationManual,
> 		ServerArgs: base.TestServerArgs{
> 			Insecure: true,
> ```

Why are we spinning up an insecure cluster here? 
___
*[pkg/server/status_test.go, line 3274 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YbHNO0xHngQaUdLe0:-N-YbHNO0xHngQaUdLe1:bduoeef) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3274)):*
> ```Go
> 
> 	doSessionsRequest := func(client http.Client, username string) listSessionsResponse {
> 		req, err := http.NewRequest("GET", ts1.AdminURL()+"/_status/sessions", nil)
> ```

we have `serverutils.GetJSONProto` for all this boilerplates  
___
*[pkg/server/status_test.go, line 3302 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-Yb4Az43tl35WF9cNu:-N-Yb4Az43tl35WF9cNv:bwe3erz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3302)):*
> ```Go
> 			RawQuery: "sslmode=disable",
> 		}
> 		db, err := gosql.Open("postgres", pgURL.String())
> ```

have you tried `serverutils.OpenDBConnE` :P 
___
*[pkg/server/status_test.go, line 3311 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-Yat1J3jtRGITRt6Va:-N-Yat1K97rfEpSXdirz:b-q8h089) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3311)):*
> ```Go
> 	// Create three users.
> 	users := [3]string{"test_user_a", "test_user_b", "test_user_c"}
> 	conn, err := testCluster.ServerConn(0).Conn(ctx)
> ```

Can we just use `testCluster.ServerConn(0)` here? iirc `.Conn(ctx)` may or may not create a new connection. 
___
*[pkg/server/status_test.go, line 3324 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-Yaqk6EHxfdcqjVMvi:-N-Yaqk6EHxfdcqjVMvj:bgpi6il) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3324)):*
> ```Go
> 	if err != nil {
> 		t.Fatal(err)
> 	}
> ```

small nit: require.NoError
___
*[pkg/server/status_test.go, line 3349 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-Yajgh9pn7QCgQF0Nk:-N-Yajgh9pn7QCgQF0Nl:b-g0wdz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3349)):*
> ```Go
> 			targetDB := getUserConn(t, user, testCluster.Server(0))
> 			defer targetDB.Close()
> 			sqlutils.MakeSQLRunner(targetDB).Exec(t, `SELECT version()`)
> ```

Did you have to execute something for the session to be consider active? 
___
*[pkg/server/status_test.go, line 3353 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-Ya2YW0q9sJzimtreu:-N-Ya2YW0q9sJzimtrev:b-oil7pe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3353)):*
> ```Go
> 	}
> 
> 	time.Sleep(500 * time.Millisecond)
> ```

Hmm why the half a second sleep here? 


<!-- Sent from Reviewable.io -->

2022-04-13 22:47 UTC, gtr reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/server/status.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-MzLJS6GCxwejgR7JBdG:-N-ZEjDz5hJpeRKvzfYO:bfjhihq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfbed32835ede7523663d00e0b96636636e2327/pkg/server/status.go#L202)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, you might want to lock the `sessionRegistry` before calling `.SerializeAll()` (this will result in deadlock, but you can create a new function called `.SerializedAllLocked()`. 

The code currently still have unprotected critical section (between `.SerializeAll()` and the `.Lock()`) which can result in race condition. 
</blockquote></details>

Good catch! I added a method `SerializedAllLocked()` to the session registry and kept the session registry locked until we serialize all the sessions.



_Code quote:_
```Go
		// Before retrieving all the closed sessions, prevent any changes to the
		// session registry by locking the session registry. Without this, a session
```
___
*[pkg/server/status.go, line 2757 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YNZI9-1QrwcqKRQhR:-N-ZBwWB9YKUqN_ZEVpd:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status.go#L2757)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: you don't need to do this sort since you are sorting again after appending the sessions
</blockquote></details>

Done!



_Code quote:_
```Go
sort.Slice(sessions, func(i, j int) bool {
```
___
*[pkg/server/status_test.go, line 3265 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YbQBm-iAPoiHtwbdH:-N-Zq1TH54uCofav6-JB:b-9wqpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3265)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Why are we spinning up an insecure cluster here? 
</blockquote></details>

I based this test off `TestListSessionsV2` which uses an insecure connection but no reason other than that. I removed the insecure setting and added passwords for each user.
___
*[pkg/server/status_test.go, line 3274 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YbHNO0xHngQaUdLe0:-N-ZqIyQ0WN7FrXk2vq3:bck4gnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3274)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

we have `serverutils.GetJSONProto` for all this boilerplates  
</blockquote></details>

Thanks! Simplifies the code a lot :)
___
*[pkg/server/status_test.go, line 3302 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-Yb4Az43tl35WF9cNu:-N-Zt0wDCTuwuDp-YRaH:b-ilhu0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3302)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

have you tried `serverutils.OpenDBConnE` :P 
</blockquote></details>

I might be wrong on this but it looks like `serverutils.OpenDBConnE` opens a gosql DB connection using the root user:
```go
pgURL, cleanupGoDB, err := sqlutils.PGUrlE(
		sqlAddr, "StartServer" /* prefix */, url.User(security.RootUser))
```
but I want to open a connection using a specific username and password combination.



_Code quote:_
```Go
db, err := gosql.Open("postgres", pgURL.String())
```
___
*[pkg/server/status_test.go, line 3311 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-Yat1J3jtRGITRt6Va:-N-Zy-X81RB7s3cIcpeb:b-4c5f02) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3311)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Can we just use `testCluster.ServerConn(0)` here? iirc `.Conn(ctx)` may or may not create a new connection. 
</blockquote></details>

Good catch, done!
___
*[pkg/server/status_test.go, line 3324 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-Yaqk6EHxfdcqjVMvi:-N-Zy2N75kTvttGuUugM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3324)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

small nit: require.NoError
</blockquote></details>

Done.
___
*[pkg/server/status_test.go, line 3349 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-Yajgh9pn7QCgQF0Nk:-N-_51EWEIADMNbtehfD:b-54c8v9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3349)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Did you have to execute something for the session to be consider active? 
</blockquote></details>

If you mean "active" as in a session is started, yes. But this question made me think of the `IDLE` status. So I also decided to test if we get the correct response for `IDLE` vs `OPEN` sessions by running `SELECT pg_sleep(5)` to keep a session open. (see PR description). 
___
*[pkg/server/status_test.go, line 3353 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-Ya2YW0q9sJzimtreu:-N-_4zZp4tHdQk1g72ZN:buhprmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3353)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm why the half a second sleep here? 
</blockquote></details>

No reason, deleted!



_Code quote:_
```Go
time.Sleep(500 * time.Millisecond)
```
___
*[pkg/server/status_test.go, line 3377 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YPn9l-7IP1AN-39OB:-N-ZF8QY6QsQgV8OmyH-:b1rp7ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3377)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Avoid using the same value for 2 different things, because they might be returned switched values and you wouldn't know. Make one value for open and another for closed
</blockquote></details>

Got it! Done.


<!-- Sent from Reviewable.io -->

2022-04-20 19:48 UTC, Azhng reviewed
> Reviewed 2 of 3 files at r6, 4 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[build/teamcity-bazel-support.sh, line 1 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N07Q-mUEe-gCq2UU75l:-N07Q-mUEe-gCq2UU75m:b-jnkbce) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49a5d0a71728f42806e15236563684b8284fdd0/build/teamcity-bazel-support.sh#L1)):*
> ```Shell
> # FYI: You can run `./dev builder` to run this Docker image. :)
> ```

Is this file mode change intentional? 
___
*[pkg/sql/closed_session_cache.go, line 176 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YfwJh9dEEoU3JEW0a:-N07R8KJ9IYXBJ2HV_Fm:bpf84iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/sql/closed_session_cache.go#L176)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

You sure `time.Time` only takes 8 bytes? Seems like it has 2 * 64 bit integer + a pointer type. 

```golang
type Time struct {
	wall uint64
	ext  int64

	loc *Location
}

```

A trick here would be 

```golang
unsafe.Sizeof(time.Time{})
```
</blockquote></details>

friendly bump ^^ 
___
*[pkg/sql/exec_util.go, line 2041 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N07RILo7Tmn2iwN7z8T:-N07RILo7Tmn2iwN7z8U:b-i6cvq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49a5d0a71728f42806e15236563684b8284fdd0/pkg/sql/exec_util.go#L2041)):*
> ```Go
> 	}
> 
> 	return response
> ```

small nit: we can refactor this to just call `return r.SerializeAllLock()` 
___
*[pkg/sql/exec_util.go, line 2044 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N07RPMZ-jSu816WZsOA:-N07RPMZ-jSu816WZsOB:b-k344jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49a5d0a71728f42806e15236563684b8284fdd0/pkg/sql/exec_util.go#L2044)):*
> ```Go
> }
> 
> // SerializedAllLocked is like SerializeAll but assumes SessionRegistry's mutex is locked.
> ```

nit: `s/SerializedAllLocked/SerializeAllLocked/` 
___
*[pkg/server/status_test.go, line 3372 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N07Vm_rCefKJQnoHPKf:-N07Vm_rCefKJQnoHPKg:b-gk0xyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49a5d0a71728f42806e15236563684b8284fdd0/pkg/server/status_test.go#L3372)):*
> ```Go
> 		require.Equal(t, 5, active)
> 		require.Equal(t, 10, closed)
> 	}
> ```

Hmm, you might want to wrap this loop in a `testutils.SucceedSoon()`. Since the main test goroutine runs concurrently with the "active session" goroutine, there's non-zero probability that the main goroutine can execute this block of code before the "active session" goroutine to make the session active.


<!-- Sent from Reviewable.io -->

2022-04-20 21:43 UTC, gtr reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[build/teamcity-bazel-support.sh, line 1 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N07Q-mUEe-gCq2UU75l:-N07ugB1DprSRh-pUSo4:b-icd81j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49a5d0a71728f42806e15236563684b8284fdd0/build/teamcity-bazel-support.sh#L1)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Is this file mode change intentional? 
</blockquote></details>

Nope! Reverting back to master's file mode. Thanks!
___
*[pkg/sql/closed_session_cache.go, line 176 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YfwJh9dEEoU3JEW0a:-N07uleQ5lAx2nwstEgM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/sql/closed_session_cache.go#L176)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

friendly bump ^^ 
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 2041 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N07RILo7Tmn2iwN7z8T:-N07mY5920wtI-LPKQMC:b-gj8tya) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49a5d0a71728f42806e15236563684b8284fdd0/pkg/sql/exec_util.go#L2041)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

small nit: we can refactor this to just call `return r.SerializeAllLock()` 
</blockquote></details>

Great catch!
___
*[pkg/sql/exec_util.go, line 2044 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N07RPMZ-jSu816WZsOA:-N07m_M_B3zEFIZF282K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49a5d0a71728f42806e15236563684b8284fdd0/pkg/sql/exec_util.go#L2044)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `s/SerializedAllLocked/SerializeAllLocked/` 
</blockquote></details>

Done.
___
*[pkg/server/status_test.go, line 3372 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N07Vm_rCefKJQnoHPKf:-N07uq0v5cJnCTmEsf-y:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/d49a5d0a71728f42806e15236563684b8284fdd0/pkg/server/status_test.go#L3372)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, you might want to wrap this loop in a `testutils.SucceedSoon()`. Since the main test goroutine runs concurrently with the "active session" goroutine, there's non-zero probability that the main goroutine can execute this block of code before the "active session" goroutine to make the session active.
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2022-04-21 15:20 UTC, Azhng reviewed
Nice! Almost there! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-:-N0BhOEUD_KeqiteGXbn:bjg0osy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/closed_session_cache.go, line 54 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0BflxtDuWBKKh069AZ:-N0BflxtDuWBKKh069A_:b-oy0urp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3b4bdffe107ce19ed82361cb5c8d3656069b42/pkg/sql/closed_session_cache.go#L54)):*
> ```Go
> 	mu struct {
> 		syncutil.RWMutex
> 		mon  *mon.BytesMonitor
> ```

nit: you can move the bytes monitor out the `mu` struct since it has its own mutex to protect it.

For bound accounts, you can optionally assign it an [mutex](https://github.com/cockroachdb/cockroach/blob/7aa613b2c1b08aa9a96692d8a879f8407371bcf3/pkg/util/mon/bytes_usage.go#L505) to give the bound account threadsafety. 
___
*[pkg/sql/closed_session_cache.go, line 91 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0BejXE-M9dI_PlCj9K:-N0BejXE-M9dI_PlCj9L:b-bzakxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3b4bdffe107ce19ed82361cb5c8d3656069b42/pkg/sql/closed_session_cache.go#L91)):*
> ```Go
> 	node := &sessionNode{id: id, data: session, timestamp: c.timeSrc()}
> 
> 	acc := c.mu.mon.MakeBoundAccount()
> ```

Hmm I should've caught this earlier, we don't want to make a new bound account each time `.add()` is called. What we want is to initialize a bound account once when we initialize `ClosedSessionCache`, and close it once when we are destroying the this object. (however, in this case, `ClosedSessionCache` has the same object lifetime as the SQL Server, so it's really getting destroyed only when the SQL Server shuts down. 

The consequence of initializing bound account inside `.add()` is that, because of the `defer acc.Close(ctx)` call, the memory account becomes no-op, which defeat the purpose the memory accounting.
___
*[pkg/sql/closed_session_cache.go, line 174 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0Bdt1mCjPHzEOtXFBI:-N0Bdt1mCjPHzEOtXFBJ:bp4lin8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3b4bdffe107ce19ed82361cb5c8d3656069b42/pkg/sql/closed_session_cache.go#L174)):*
> ```Go
> 
> func (n *sessionNode) size() int {
> 	return int(unsafe.Sizeof(time.Time{}))
> ```

Ah my bad, what I meant was to replace the hardcoded `8` byte with this line. What I had in mind was

```golang
size := 0
size += int(unsafe.Sizeof(ClusterWideID{}))
size += n.data.Size()
size += int(unsafe.Sizeof(time.Time{}))
return size
```
___
*[pkg/server/status_test.go, line 3377 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YPn9l-7IP1AN-39OB:-N0BhByS8VPj652ooMXw:bc7xfoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3377)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Got it! Done.
</blockquote></details>

Hmm I don't see the `SucceedSoon` wraps? accidentally reverted ? 


<!-- Sent from Reviewable.io -->

2022-04-21 19:25 UTC, gtr reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/closed_session_cache.go, line 54 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0BflxtDuWBKKh069AZ:-N0C_CZo6ZF-28bWY7kh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3b4bdffe107ce19ed82361cb5c8d3656069b42/pkg/sql/closed_session_cache.go#L54)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: you can move the bytes monitor out the `mu` struct since it has its own mutex to protect it.

For bound accounts, you can optionally assign it an [mutex](https://github.com/cockroachdb/cockroach/blob/7aa613b2c1b08aa9a96692d8a879f8407371bcf3/pkg/util/mon/bytes_usage.go#L505) to give the bound account threadsafety. 
</blockquote></details>

Done.
___
*[pkg/sql/closed_session_cache.go, line 91 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0BejXE-M9dI_PlCj9K:-N0C_Dh1B-ZDCYTvuKi8:bmx1pzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3b4bdffe107ce19ed82361cb5c8d3656069b42/pkg/sql/closed_session_cache.go#L91)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm I should've caught this earlier, we don't want to make a new bound account each time `.add()` is called. What we want is to initialize a bound account once when we initialize `ClosedSessionCache`, and close it once when we are destroying the this object. (however, in this case, `ClosedSessionCache` has the same object lifetime as the SQL Server, so it's really getting destroyed only when the SQL Server shuts down. 

The consequence of initializing bound account inside `.add()` is that, because of the `defer acc.Close(ctx)` call, the memory account becomes no-op, which defeat the purpose the memory accounting.
</blockquote></details>

Good catch, I initialized the bound account when we initialize the `ClosedSessionCache` and call `c.mu.acc.Grow()` in the `.add()` method.
___
*[pkg/sql/closed_session_cache.go, line 174 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0Bdt1mCjPHzEOtXFBI:-N0C_QY59cTdF73Zziy2:b2ct66v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3b4bdffe107ce19ed82361cb5c8d3656069b42/pkg/sql/closed_session_cache.go#L174)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Ah my bad, what I meant was to replace the hardcoded `8` byte with this line. What I had in mind was

```golang
size := 0
size += int(unsafe.Sizeof(ClusterWideID{}))
size += n.data.Size()
size += int(unsafe.Sizeof(time.Time{}))
return size
```
</blockquote></details>

My bad, fixed!
___
*[pkg/server/status_test.go, line 3377 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N-YPn9l-7IP1AN-39OB:-N0C_WyI96Wz8xRVnxeu:b-l91dyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e5d453304fea2f73aaa366385eb1ecf33acce64/pkg/server/status_test.go#L3377)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm I don't see the `SucceedSoon` wraps? accidentally reverted ? 
</blockquote></details>

Yup, added it back.


<!-- Sent from Reviewable.io -->

2022-04-21 19:41 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/closed_session_cache.go, line 72 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0CcqTE4XX4ZmWa25Q5:-N0CcqTE4XX4ZmWa25Q6:b83nnze) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68c4f19bce9308eba5198c5bdcf7e40927794a3/pkg/sql/closed_session_cache.go#L72)):*
> ```Go
> 		ShouldEvict: func(size int, _, _ interface{}) bool {
> 			capacity := ClosedSessionCacheCapacity.Get(&st.SV)
> 			return int64(size) > capacity
> ```

Remember to shrink the bound account when you evicts the older data. Otherwise we would just be leaking memory here. There should be a callback here you can register.


<!-- Sent from Reviewable.io -->

2022-04-21 19:53 UTC, gtr reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/closed_session_cache.go, line 72 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0CcqTE4XX4ZmWa25Q5:-N0CfoH31wBowx8LcpgT:b-mvt8ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/e68c4f19bce9308eba5198c5bdcf7e40927794a3/pkg/sql/closed_session_cache.go#L72)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Remember to shrink the bound account when you evicts the older data. Otherwise we would just be leaking memory here. There should be a callback here you can register.
</blockquote></details>

Good catch, I used the `OnEvictedEntry` callback function.


<!-- Sent from Reviewable.io -->

2022-04-21 19:55 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/closed_session_cache.go, line 174 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0Bdt1mCjPHzEOtXFBI:-N0CgIO88IzLOESp19g5:bv7f6mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3b4bdffe107ce19ed82361cb5c8d3656069b42/pkg/sql/closed_session_cache.go#L174)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

My bad, fixed!
</blockquote></details>

Ugh, doesn't seem like it's fixed :sweat_smile: 


<!-- Sent from Reviewable.io -->

2022-04-21 20:25 UTC, gtr reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)

___
*[pkg/sql/closed_session_cache.go, line 174 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0Bdt1mCjPHzEOtXFBI:-N0Cn9zpAtsV18uVUdFZ:b-iw71hv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3b4bdffe107ce19ed82361cb5c8d3656069b42/pkg/sql/closed_session_cache.go#L174)):*
> size := 0
> size += int(unsafe.Sizeof(ClusterWideID{}))
> size += n.data.Size()
> size += int(unsafe.Sizeof(time.Time{}))
> return size

Ok got it this time haha


<!-- Sent from Reviewable.io -->

2022-04-21 20:32 UTC, Azhng approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-:-N0CovtF1862kq59DtyQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @gtr, and @maryliag)



<!-- Sent from Reviewable.io -->

2022-04-21 20:40 UTC, gtr commented
TFTR! let me just get Ci to green

2022-04-22 17:49 UTC, gtr reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78650)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @gtr, @maryliag, and @xinhaoz)

___
*[pkg/sql/crdb_internal.go, line 1898 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/78650#-N0H-yRI-XbvqppFmtKl:-N0HNgph3P0TtCSgPBrT:btm61ow) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c36b6e94e2c6ad28eaf638a95e31b08c1379a93/pkg/sql/crdb_internal.go#L1898)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Are these fields just for clearer distinction now that we're saving closed sessions? I noticed in both sessions table requests you're excluding closed sessions so these tables are still just open sessions.
</blockquote></details>

Yes, they are for clearer distinction. Right now the tables only list open sessions but I plan on also listing closed sessions; I'm saving that for a future PR.


<!-- Sent from Reviewable.io -->

2022-04-22 17:49 UTC, gtr commented
bors r+

2022-04-22 19:41 UTC, merged