sql: allow pg_type.oid lookup join on null value
cockroachdb/cockroach pull request #78960
Opened 2022-03-29 15:53 UTC by ecwall

fixes https://github.com/cockroachdb/cockroach/issues/76768

Release note (bug fix): Doing a lookup join on pg_type.oid no longer
results in an error.
Example:
SELECT pg_type.oid
FROM (SELECT null::OID AS b) AS a
INNER LOOKUP JOIN pg_type ON pg_type.oid=a.b

2022-03-29 15:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/78960)
<!-- Reviewable:end -->

2022-03-29 16:11 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[pkg/sql/pg_catalog.go, line 2997 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzLQteu0XdIbd2lY7wl:-MzLQteu0XdIbd2lY7wm:bofoyxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bc7a2985d4b6f45e0c91cadb4144e5fe9388e1/pkg/sql/pg_catalog.go#L2997)):*
> ```Go
> 				h := makeOidHasher()
> 				nspOid := h.NamespaceOid(db.GetID(), pgCatalogName)
> 				d := tree.UnwrapDatum(p.EvalContext(), constraint)
> ```

i realized that we'd want to try to fix this one level higher if we can -- the code that does the lookup join should probably check for a NULL value before calling into this virtual index.

otherwise we'd run into the same problem in every virtual index that we define. e.g., we could probably get a similar repro for a different virtual index. it looks like this other virtual index does have a check like this one you added though: https://github.com/cockroachdb/cockroach/blob/b9ea426e68bc8866641578d7e8ed88a5d99d7a85/pkg/sql/pg_catalog.go#L1068

(maybe there's a reason why we can't make the fix in the lookup join code, but could you try to find out?)


<!-- Sent from Reviewable.io -->

2022-03-29 17:46 UTC, ecwall reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/pg_catalog.go, line 2997 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzLQteu0XdIbd2lY7wl:-MzLm3Z31v-DV3qAQIJ_:b-iuxasi) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bc7a2985d4b6f45e0c91cadb4144e5fe9388e1/pkg/sql/pg_catalog.go#L2997)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i realized that we'd want to try to fix this one level higher if we can -- the code that does the lookup join should probably check for a NULL value before calling into this virtual index.

otherwise we'd run into the same problem in every virtual index that we define. e.g., we could probably get a similar repro for a different virtual index. it looks like this other virtual index does have a check like this one you added though: https://github.com/cockroachdb/cockroach/blob/b9ea426e68bc8866641578d7e8ed88a5d99d7a85/pkg/sql/pg_catalog.go#L1068

(maybe there's a reason why we can't make the fix in the lookup join code, but could you try to find out?)
</blockquote></details>

It looks like it can be moved there so I moved it and removed the individual `DNull` checks.  The code in the loop is a bit harder to follow now with the mix of `break`, `continue`, `return`.


<!-- Sent from Reviewable.io -->

2022-03-30 21:40 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[pkg/sql/virtual_schema.go, line 630 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzRlEFy3YjVGcJy53fX:-MzRlEFy3YjVGcJy53fY:bd1o8jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a661cb45f79d5f135d7b76468426fe1762b3097/pkg/sql/virtual_schema.go#L630)):*
> ```Go
> 			constraintDatum := span.StartKey().Value(0)
> 			virtualIndex := def.getIndex(index.GetID())
> 			if constraintDatum == tree.DNull {
> ```

do we need to call UnwrapDatum before checking DNull? it seems like that's what was happening in the `populate` function before. maybe the Queries team could help with this
___
*[pkg/sql/virtual_schema.go, line 634 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzRkmpe7HRmT5BQzAKe:-MzRkmpe7HRmT5BQzAKf:b-hw29nr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a661cb45f79d5f135d7b76468426fe1762b3097/pkg/sql/virtual_schema.go#L634)):*
> ```Go
> 					break
> 				}
> 				continue
> ```

i think both the `break` and `continue` could use comments. 


<!-- Sent from Reviewable.io -->

2022-03-31 20:47 UTC, yuzefovich reviewed
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[pkg/sql/virtual_schema.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzWfC6LDV-YCwoYwSPq:-MzWfC6M-mnjKBZU8yGV:bts87e4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a661cb45f79d5f135d7b76468426fe1762b3097/pkg/sql/virtual_schema.go#L81)):*
> ```Go
> 	// populate populates the table given the constraint. matched is true if any
> 	// rows were generated.
> 	populate func(ctx context.Context, constraint tree.Datum, p *planner, db catalog.DatabaseDescriptor,
> ```

nit: we should add a comment that `populate` will only be called with non-NULL datum that has been "unwrapped".
___
*[pkg/sql/virtual_schema.go, line 630 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzRlEFy3YjVGcJy53fX:-MzWgcVr7g-aMQJrHTVY:bvjsjfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a661cb45f79d5f135d7b76468426fe1762b3097/pkg/sql/virtual_schema.go#L630)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we need to call UnwrapDatum before checking DNull? it seems like that's what was happening in the `populate` function before. maybe the Queries team could help with this
</blockquote></details>

I think we should call it here too - it won't hurt, and it might be necessary. We can then remove `UnwrapDatum` calls in the implementations.
___
*[pkg/sql/virtual_schema.go, line 634 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzRkmpe7HRmT5BQzAKe:-MzWhxeUAgjmjAcGp-7Z:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a661cb45f79d5f135d7b76468426fe1762b3097/pkg/sql/virtual_schema.go#L634)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think both the `break` and `continue` could use comments. 
</blockquote></details>

+1
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 5623 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzWiI-p5agU0weDQ71n:-MzWiI-p5agU0weDQ71o:b2f9vce) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a661cb45f79d5f135d7b76468426fe1762b3097/pkg/sql/logictest/testdata/logic_test/pg_catalog#L5623)):*
> ```
> true
> 
> # Fix for https://github.com/cockroachdb/cockroach/issues/76768
> ```

nit: we usually describe in words what the problem was and then give the issue number. So something like
```
# Regression test for crashing when performing a lookup join of NULL into pg_type.oid
# virtual table (#76768).
```


<!-- Sent from Reviewable.io -->

2022-04-04 14:34 UTC, ecwall reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/virtual_schema.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzWfC6LDV-YCwoYwSPq:-MzobZf7D1OOY1Rf4I9X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a661cb45f79d5f135d7b76468426fe1762b3097/pkg/sql/virtual_schema.go#L81)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we should add a comment that `populate` will only be called with non-NULL datum that has been "unwrapped".
</blockquote></details>

Done.



_Code quote (from pkg/sql/crdb_internal.go):_
```Go
tree.UnwrapDatum(p.EvalContext(), constraint)
```
___
*[pkg/sql/virtual_schema.go, line 630 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzRlEFy3YjVGcJy53fX:-MzobdFf-7fjBMnFEWRE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a661cb45f79d5f135d7b76468426fe1762b3097/pkg/sql/virtual_schema.go#L630)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we should call it here too - it won't hurt, and it might be necessary. We can then remove `UnwrapDatum` calls in the implementations.
</blockquote></details>

Done.
___
*[pkg/sql/virtual_schema.go, line 634 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzRkmpe7HRmT5BQzAKe:-MzozlsJBS198r6780li:b-2nm4z0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a661cb45f79d5f135d7b76468426fe1762b3097/pkg/sql/virtual_schema.go#L634)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

+1
</blockquote></details>

I combined this with the other matching logic to remove the additional early loop exits.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 5623 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-MzWiI-p5agU0weDQ71n:-Mzolkon7SDW6dD_CyYn:b1nq7pj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a661cb45f79d5f135d7b76468426fe1762b3097/pkg/sql/logictest/testdata/logic_test/pg_catalog#L5623)):*
> # Regression test for crashing when performing a lookup join of NULL into pg_type.oid
> # virtual table (#76768).
Done.


<!-- Sent from Reviewable.io -->

2022-04-04 14:46 UTC, rafiss approved these changes
nice, the new logic is easier to follow

can you follow the instructions here to backport this change to 22.1, 21.2, and 21.2?
https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/900005932/Backporting+a+change+to+a+release+branch

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-:-Mzp15CL3aSW_E3x29zH:b-lxokte)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)



<!-- Sent from Reviewable.io -->

2022-04-04 15:16 UTC, yuzefovich approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-:-Mzp8RvV-s0blVMiosps:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[pkg/sql/virtual_schema.go, line 636 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-Mzp8Gn89tXR3I8dcKzD:-Mzp8Gn95YCYmKJLIaL5:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd88e5c5c46b69effa66e81e6526bed4c62527fb/pkg/sql/virtual_schema.go#L636)):*
> ```Go
> 			unwrappedConstraint := tree.UnwrapDatum(p.EvalContext(), constraintDatum)
> 			virtualIndex := def.getIndex(index.GetID())
> 			// NULL constraint will not match any row
> ```

nit: missing period.


<!-- Sent from Reviewable.io -->

2022-04-04 15:44 UTC, ecwall commented
bors r=rafiss,yuzefovich

2022-04-04 15:44 UTC, ecwall reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78960)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss and @yuzefovich)

___
*[pkg/sql/virtual_schema.go, line 636 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-Mzp8Gn89tXR3I8dcKzD:-MzpF-TwDGhMlZDqJD3P:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd88e5c5c46b69effa66e81e6526bed4c62527fb/pkg/sql/virtual_schema.go#L636)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: missing period.
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2022-04-04 17:20 UTC, merged

2022-04-04 18:49 UTC, ecwall commented
> nice, the new logic is easier to follow
> 
> can you follow the instructions here to backport this change to 22.1, 21.2, and 21.2? https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/900005932/Backporting+a+change+to+a+release+branch
> 
> > Reviewed 4 of 4 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78960#-:-Mzp15CL3aSW_E3x29zH:b-lxokte)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

Ah I see you did this already, thanks.