logictest: add support for statements that hang due to lock contention
cockroachdb/cockroach pull request #79010
Opened 2022-03-30 00:40 UTC by AlexTalks

While previously each statement in a logictest was expected to complete
(with success or error), this change adds support for a new type of
statement in a logictest that is expected to hang and be completed
later. This change enables the ability to test what happens during lock
contention, as in the case a statement is waiting on locks and does not
have a lock timeout set, the statement will hang until it can proceed
(by obtaining the locks).

This feature is supported by the syntax:
```
statement hangs namedStatement ok
<some statement that will hang as it cannot obtain locks>
...
<operations that would free the locks namedStatement is waiting on>
...
finishstatement namedStatement
<wait on namedStatement to complete and validate that results are ok>
```

Release note: None

Release Justification: Testing change only.

2022-03-30 00:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/79010)
<!-- Reviewable:end -->

2022-03-30 01:31 UTC, AlexTalks commented
FYI: The reason for the backport label is that this change is in service of additional test coverage for #77876 (intended for 22.1).

2022-03-30 18:09 UTC, yuzefovich reviewed
The implementation LGTM, but I'm a bit on the fence whether this feature makes sense in the context of the logic tests.

The image of logic tests in my head has always been that a single statement is executed fully and then you can optionally check whether the results match the provided expectation. In the past I think we've implemented tests that want to assert the locking via unit tests. However, I could see an argument that this change provides an infrastructure for writing those blocking tests easier. Curious what Andrei/Nathan think. I'm also curious what @cockroachdb/sql-queries think.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-:-MzQzwVv7IPu0WoGPwUk:b9um2th)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @andreimatei, and @nvanbenschoten)

___
*[pkg/sql/logictest/logic.go, line 992 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-MzQw-tp3E87K0rHczo8:-MzQw-tp3E87K0rHczo9:b-u97ess) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa72b3b09c7f493e86a188330b6f45eff0c885a2/pkg/sql/logictest/logic.go#L992)):*
> ```Go
> 	// expected rows affected count. -1 to avoid testing this.
> 	expectCount int64
> 	// if we expect this statement to hang, and become a pendingStatement
> ```

nit: missing periods here and below.
___
*[pkg/sql/logictest/logic.go, line 2478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-MzQwOs_DxtYSFXs5a0a:-MzQwOs_DxtYSFXs5a0b:b-b162vu) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa72b3b09c7f493e86a188330b6f45eff0c885a2/pkg/sql/logictest/logic.go#L2478)):*
> ```Go
> 			name := fields[1]
> 
> 			if pending, ok := t.pendingStatements[name]; ok {
> ```

nit: I think we tend to short-circuit on `!ok` case and then proceed with the main happy case. I.e. something like
```
pending, ok := t.pendingStatements[name]
if !ok {
  return errors.New("")
}
// happy case
```
___
*[pkg/sql/logictest/logic.go, line 3129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-MzQxbD77KnyZbRMoHxr:-MzQxbD77KnyZbRMoHxs:bi2qdzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa72b3b09c7f493e86a188330b6f45eff0c885a2/pkg/sql/logictest/logic.go#L3129)):*
> ```Go
> 	if stmt.expectHang {
> 		if _, ok := t.pendingStatements[stmt.statementName]; ok {
> 			return false, errors.Newf("pending statement with name \"%s\" already exists", stmt.statementName)
> ```

nit: you can use `%q` instead of `"%s"`.
___
*[pkg/sql/logictest/testdata/logic_test/cluster_locks, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-MzQyS06CKfy8a9gwCwN:-MzQyS06CKfy8a9gwCwO:by7mqbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa72b3b09c7f493e86a188330b6f45eff0c885a2/pkg/sql/logictest/testdata/logic_test/cluster_locks#L46)):*
> ```
> user testuser
> 
> finishstatement readReq
> ```

nit: I think the txn is still open for `testuser`.


<!-- Sent from Reviewable.io -->

2022-03-30 19:12 UTC, AlexTalks reviewed
Thanks for the feedback.  I'm curious to hear some other opinions too.  I had thought about trying to add generic `async/await` modifiers (inspired by JavaScript/C#/etc) but this seemed like a more straightforward method of getting something working quickly with the logictest infrastructure.

We have some logictests that incorporate locking, however I don't believe we have any that capture the concept of "waiting".  The tests I've seen that have transactions hold locks make sure that other operations that attempt to obtain those locks have timeouts, so that they fail after some short wait.  This means that we aren't able to test what happens when we have actively waiting operations in logictests unfortunately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-:-MzRDKsa7n5aSdwuE0dV:b-nhfz41)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @andreimatei, @nvanbenschoten, and @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 992 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-MzQw-tp3E87K0rHczo8:-MzREVAu4iiPQM0vvF3k:b1q1nww) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa72b3b09c7f493e86a188330b6f45eff0c885a2/pkg/sql/logictest/logic.go#L992)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: missing periods here and below.
</blockquote></details>

Working - thanks
___
*[pkg/sql/logictest/logic.go, line 2478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-MzQwOs_DxtYSFXs5a0a:-MzREXf92yT99-VOf3Hz:b-11h4we) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa72b3b09c7f493e86a188330b6f45eff0c885a2/pkg/sql/logictest/logic.go#L2478)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think we tend to short-circuit on `!ok` case and then proceed with the main happy case. I.e. something like
```
pending, ok := t.pendingStatements[name]
if !ok {
  return errors.New("")
}
// happy case
```
</blockquote></details>

Working - sounds good
___
*[pkg/sql/logictest/logic.go, line 3129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-MzQxbD77KnyZbRMoHxr:-MzREZ6sCom-S6Dx_bUd:b-9kj0sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa72b3b09c7f493e86a188330b6f45eff0c885a2/pkg/sql/logictest/logic.go#L3129)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: you can use `%q` instead of `"%s"`.
</blockquote></details>

Working - thanks for the tip
___
*[pkg/sql/logictest/testdata/logic_test/cluster_locks, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-MzQyS06CKfy8a9gwCwN:-MzREazoDixfSZ9-rWb7:bvb57fj) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa72b3b09c7f493e86a188330b6f45eff0c885a2/pkg/sql/logictest/testdata/logic_test/cluster_locks#L46)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think the txn is still open for `testuser`.
</blockquote></details>

This one is actually ok, though, correct?  Any open transactions are rolled back at the end of a logictest I think?


<!-- Sent from Reviewable.io -->

2022-03-31 22:22 UTC, nvanbenschoten commented
> The image of logic tests in my head has always been that a single statement is executed fully and then you can optionally check whether the results match the provided expectation. In the past I think we've implemented tests that want to assert the locking via unit tests. However, I could see an argument that this change provides an infrastructure for writing those blocking tests easier. Curious what Andrei/Nathan think.

Alex and I talked through this. I don't see what's here as much of a deviation from the existing logic test infrastructure. We already support switching between multiple sessions and we also have some non-determinism in certain cases, which is why we have the `retry` directive. Allowing statements to block using an async/await model seems fine to me. It's actually how I would have preferred that we implemented locking-related testing in the past.

2022-03-31 23:24 UTC, AlexTalks reviewed
Thanks @nvanbenschoten.  @yuzefovich, let me know if this seems ok to merge - I've modified the syntax a bit to use instead `statement async` and `awaitstatement`, and cleaned things up a bit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-:-MzXGY9YAE5BSYdFwXj2:bcr9kmy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2022-03-31 23:32 UTC, yuzefovich approved these changes
Sounds good <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Looks @michae2 was typing something, so it might be worth to wait a bit to give him a chance to share his feedback.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-:-MzXJJ55-TSdKXVXCmdi:bt6d282)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @andreimatei, and @nvanbenschoten)

___
*[pkg/sql/logictest/testdata/logic_test/cluster_locks, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-MzQyS06CKfy8a9gwCwN:-MzXIhRN2iG9JXxovTVu:bd3id1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa72b3b09c7f493e86a188330b6f45eff0c885a2/pkg/sql/logictest/testdata/logic_test/cluster_locks#L46)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

This one is actually ok, though, correct?  Any open transactions are rolled back at the end of a logictest I think?
</blockquote></details>

Hm, I don't know - tbh I don't think I've ever written a logic test that begins a txn :sweat_smile:

To me it seems cleaner to close things explicitly in case we'll be appending to this test file in the future, but I don't have strong feelings about it (that's why it's a "nit"), so feel free to ignore this comment :)


<!-- Sent from Reviewable.io -->

2022-03-31 23:32 UTC, yuzefovich commented
Don't forget to update the PR description based on the latest commit message.

2022-04-01 00:07 UTC, michae2 requested changes
Cool! I really like this!

Something is bothering me, though. Do we check that the async statement is still blocking while executing the following statements? If I understand the implementation correctly, the async statement could finish at any time, including before the next statement is executed. That doesn't seem like much of a test if we want to verify that locks are actually blocking a SELECT FOR UPDATE until after the UPDATE transaction commits or aborts.

Maybe we could add something like:

```
select {
execRes := <-pending.resultChan:
  // not blocking any more, failure
default:
  // still blocking, yay, proceed
}
```

to all of the statement executions after the async statement?

(Or maybe not all of the statement executions... maybe only statements with another option like `blocks namedStatement` which would then cause this check to happen before execution.)

Then we could write tests like:

```
statement count 7
BEGIN; UPDATE t SET v = concat(v, '_updated') WHERE k >= 'b' and k < 'z'

user testuser

statement ok
BEGIN

statement async readReq ok
select * from t for update

user root

sleep 2 blocks readReq

statement ok blocks readReq
ROLLBACK

user testuser

awaitstatement readReq

```

which would give a little more assurance that the SELECT FOR UPDATE was actually blocking until the ROLLBACK.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-:-MzXLLO6-vDKo_zgUq3u:b7026mi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @andreimatei, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-04-01 19:14 UTC, AlexTalks reviewed
@michae2 I actually talked with @nvanbenschoten about this a bit (with a code example just like the one you gave!), but the problem is even with such a check we can't reason deterministically about where the async goroutine actually is in its execution... therefore we thought it might be better to leave it as is with a more naive approach, and validate that the locks are held by polling the `crdb_internal.cluster_locks` table (introduced in #77876) until we see that we have both held locks and waiters as expected.  This will give us a more specific signal to test than just if the goroutine hasn't completed yet, as we can test for what we want to see - the waiting operation in the lock table.

This is also part of why I changed the terminology to `async` rather than `hangs` - the async statement may take some time, or it may complete quickly, the implementation doesn't care - but we can test for the other effects (like showing up in the lock table) that we are looking for anyway.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-:-MzaX31XDiRErEXOObHE:byf8l18)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @andreimatei, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-04-01 20:09 UTC, michae2 approved these changes
@alextalks that makes sense. Checking `cluster_locks` sounds even better. Thanks for the response!

Then I only have one small nit: could we use "block" as the terminology in comments, rather than "hang"? :slightly_smiling_face:

<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79010#-:-MzajCS4D8G5s9mQSVVQ:b8bswfc)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @AlexTalks, @andreimatei, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-04-06 21:54 UTC, AlexTalks commented
bors retry

2022-04-06 23:28 UTC, merged