server/status: add running non-idle jobs metric
cockroachdb/cockroach pull request #79022
Opened 2022-03-30 04:27 UTC by darinpp

Previously serverless was using the sql jobs running metric to determine
if a tenant process is idle and can be shut down. With the introduction
of continiously running jobs this isn't a good indicator anymore. A
recent addition is a per job metrics that show running or idle. The auto
scaler doesn't care about the individual jobs and only cares about the
total number of jobs that a running but haven't reported as being idle.
The pull rate is also very high so the retriving all the individual
running/idle metrics for each job type isn't optimal. So this PR adds a
single metric that just aggregates and tracks the total count of jobs
running and not idle.

Release justification: Bug fixes and low-risk updates to new functionality
Release note: None

Will be re-based once #79021 is merged

2022-03-30 04:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/79022)
<!-- Reviewable:end -->

2022-03-30 12:34 UTC, miretskiy requested changes
> Reviewed 5 of 9 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79022)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp and @miretskiy)

___
*[pkg/util/metric/prometheus_exporter.go, line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79022#-MzPo01kEtuUyx3sNaoh:-MzPo01kEtuUyx3sNaoi:bfqrh7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91a32b7941a148073bc430e60c1fd9b0c700b6/pkg/util/metric/prometheus_exporter.go#L129)):*
> ```Go
> ) error {
> 	pm.muScrapeAndPrint.Lock()
> 	defer pm.muScrapeAndPrint.Unlock()
> ```

should this be a read lock?
___
*[pkg/util/metric/registry.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79022#-MzPoDZwCoQR9ntwXvOJ:-MzPoDZwCoQR9ntwXvOK:b69lmw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91a32b7941a148073bc430e60c1fd9b0c700b6/pkg/util/metric/registry.go#L161)):*
> ```Go
> 
> // Select calls the given closure for the selected metric names.
> func (r *Registry) Select(metrics map[string]struct{}, f func(name string, val interface{})) {
> ```

I don't know if this method is really needed.  Couldn't `f` perform the same filtering and thus you could
just use `Each` w/out expanding the interface?


<!-- Sent from Reviewable.io -->

2022-03-30 15:38 UTC, darinpp reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79022)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/util/metric/prometheus_exporter.go, line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79022#-MzPo01kEtuUyx3sNaoh:-MzQRGxw581gCye-UF3m:b-dec1y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91a32b7941a148073bc430e60c1fd9b0c700b6/pkg/util/metric/prometheus_exporter.go#L129)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should this be a read lock?
</blockquote></details>

A read lock is shared so it wouldn't work here. The scrape call adds data to the exporter so it isn't read only. The print clears after the data is printed so also isn't read only.
___
*[pkg/util/metric/registry.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79022#-MzPoDZwCoQR9ntwXvOJ:-MzQT4I55WR7fJn5WasJ:b-i6mh1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd91a32b7941a148073bc430e60c1fd9b0c700b6/pkg/util/metric/registry.go#L161)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't know if this method is really needed.  Couldn't `f` perform the same filtering and thus you could
just use `Each` w/out expanding the interface?

</blockquote></details>

`f` can't perform the same filtering as it doesn't have access to the internals of the registry. It is possible to iterate over all the metrics and let `f` filter out the ones that aren't required but this isn't optimal from performance point of view and we want to do very frequent calls to this method.


<!-- Sent from Reviewable.io -->

2022-03-30 15:57 UTC, abarganier commented
Great to see more observability on the way! From the obs-inf review side, can you look into and consider defining some [AlertingRule(s)](https://github.com/cockroachdb/cockroach/blob/4cbaaaecd743adada69166216c455168d4345f84/pkg/util/metric/rule.go#L40-L58) and/or [AggregationRule(s)](https://github.com/cockroachdb/cockroach/blob/4cbaaaecd743adada69166216c455168d4345f84/pkg/util/metric/rule.go#L60-L70) for this? They can go a long way towards helping people understand expected value ranges/how to effectively use CRDB metrics.

Let us know if we can provide any more useful context on this.

2022-03-30 16:22 UTC, darinpp commented
> Great to see more observability on the way! From the obs-inf review side, can you look into and consider defining some [AlertingRule(s)](https://github.com/cockroachdb/cockroach/blob/4cbaaaecd743adada69166216c455168d4345f84/pkg/util/metric/rule.go#L40-L58) and/or [AggregationRule(s)](https://github.com/cockroachdb/cockroach/blob/4cbaaaecd743adada69166216c455168d4345f84/pkg/util/metric/rule.go#L60-L70) for this? They can go a long way towards helping people understand expected value ranges/how to effectively use CRDB metrics.
> 
> Let us know if we can provide any more useful context on this.

I don't see the need to define either type of rule for the added metric. It doesn't indicate a problem so not sure why would anyone have to define alert rule. Also it doesn't make sense aggregating it with anything else. It already is sort of an aggregation of the status of all jobs. While it can be used on the UI side, the main reason for adding this metric is to drive autoscaler for serverless.

2022-03-30 17:23 UTC, miretskiy approved these changes
Just giving 👍 from jobs perspective.

2022-04-01 17:01 UTC, abarganier reviewed
> I don't see the need to define either type of rule for the added metric. It doesn't indicate a problem so not sure why would anyone have to define alert rule. Also it doesn't make sense aggregating it with anything else. It already is sort of an aggregation of the status of all jobs. While it can be used on the UI side, the main reason for adding this metric is to drive autoscaler for serverless.

Observability Infra. always asks those implementing new metrics to consider aggregation rules or alerting rules, but it's not mandatory to add them. Thanks for looking into it & considering!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79022#-:-Mza1d0z6vkiFCoZiYu4:b5nv184)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)



<!-- Sent from Reviewable.io -->

2022-04-05 18:56 UTC, darinpp commented
bors r+

2022-04-05 21:09 UTC, merged