colrpc: fix tracing when an inbox receives an error
cockroachdb/cockroach pull request #79084
Opened 2022-03-30 20:22 UTC by yuzefovich

Currently, whenever an inbox encounters an error in `Next`, regardless
of the origin of error, we close the inbox which results in shutting
down the gRPC stream. However, such behavior is intended to occur only
in case of an ungraceful termination of the gRPC stream itself, and for
other error cases (like an error is sent from the outbox, internal error
in the inbox) we want to keep the stream alive in order to be able to
drain it later. As a consequence of the current incorrect behavior,
whenever a remote node encounters an error, we will not collect the
remote metadata, so we won't populate the trace (if the tracing is
enabled). This bug was introduced during a large refactor in
3771c58e9f286bf26b264c9afa076924889fffeb and is now fixed.

Release note (bug fix): Previously, whenever a distributed query
resulted in an error on the remote node, then the trace would be
incomplete. This is now fixed.

2022-03-30 20:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/79084)
<!-- Reviewable:end -->

2022-03-31 15:03 UTC, mgartner approved these changes
Thanks for fixing this! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but the other reviewers should take a look.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79084#-:-MzVVDVc7Vin12B7dpfZ:bscctj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @michae2)



<!-- Sent from Reviewable.io -->

2022-03-31 17:21 UTC, michae2 requested changes
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79084)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 389 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79084#-MzVxXVh3WHWcoQVHC0c:-MzVxXVi26NiLDnVHSzu:bodh98q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c36a4d4ead17a9f01ea5e6077c904283fbc147/pkg/sql/colflow/colrpc/inbox.go#L389)):*
> ```Go
> 								"first: %v\nsecond: %v", receivedErr, meta.Err,
> 						))
> 					}
> ```

Is throwing an assertion the right response here? I'm not sure it's strictly "wrong" for the outbox to send us multiple errors in the same metadata.

Could we use `errors.CombineErrors` to roll up all the errors from the metadata into one error, and throw that instead?



_Code quote:_
```Go
					if receivedErr != nil {
						colexecerror.InternalError(errors.AssertionFailedf(
							"multiple errors are received as metadata at once\n"+

								"first: %v\nsecond: %v", receivedErr, meta.Err,
						))
					}
```


<!-- Sent from Reviewable.io -->

2022-03-31 20:23 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79084)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @mgartner, and @michae2)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 389 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79084#-MzVxXVh3WHWcoQVHC0c:-MzWcecF4F_5-xybi0fu:b-ov86pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c36a4d4ead17a9f01ea5e6077c904283fbc147/pkg/sql/colflow/colrpc/inbox.go#L389)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Is throwing an assertion the right response here? I'm not sure it's strictly "wrong" for the outbox to send us multiple errors in the same metadata.

Could we use `errors.CombineErrors` to roll up all the errors from the metadata into one error, and throw that instead?
</blockquote></details>

Hm, I'm quite certain that we should not be sending multiple errors in a single message from the outbox, but you're right that it doesn't seem to be prohibited. However, I'm concerned of "corrupting" the errors with `errors.CombineErrors`, so, instead, I made the change so that the first error in the message is thrown as a panic while all others are buffered as metadata - this way the caller will see all errors the way they were decoded from the wire. This seems like the safest option overall. WDYT?


<!-- Sent from Reviewable.io -->

2022-04-01 00:22 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79084#-:-MzXUyNI9k_NQ-DnrrYz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 389 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79084#-MzVxXVh3WHWcoQVHC0c:-MzXSy-R2RNgz92V0hVd:boqx70i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c36a4d4ead17a9f01ea5e6077c904283fbc147/pkg/sql/colflow/colrpc/inbox.go#L389)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I'm quite certain that we should not be sending multiple errors in a single message from the outbox, but you're right that it doesn't seem to be prohibited. However, I'm concerned of "corrupting" the errors with `errors.CombineErrors`, so, instead, I made the change so that the first error in the message is thrown as a panic while all others are buffered as metadata - this way the caller will see all errors the way they were decoded from the wire. This seems like the safest option overall. WDYT?
</blockquote></details>

Good points. Throwing the first error while buffering the rest does seem the safest. Looks good!
___
*[pkg/sql/colflow/draining_test.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79084#-MzXUK4QCX-VKSRhXGkK:-MzXUK4QCX-VKSRhXGkL:bgcsr05) ([raw file](https://github.com/cockroachdb/cockroach/blob/773d9ca171edcaf2f5dd0795481c5f673aad30b5/pkg/sql/colflow/draining_test.go#L32)):*
> ```Go
> // an error occurs on a remote node. The verification is done by checking that
> // the trace from a distributed query contains spans of the remote processors.
> func TestDrainingAfterRemoteError(t *testing.T) {
> ```

Thank you for the comments. This test is a 4-star operatic masterpiece, showing in a theater near you, with popcorn.



_Code quote:_
```Go
TestDrainingAfterRemoteError
```


<!-- Sent from Reviewable.io -->

2022-04-01 00:31 UTC, yuzefovich reviewed
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79084#-:-MzXWyKg0kPPkUcqg1Jt:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @michae2)

___
*[pkg/sql/colflow/draining_test.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79084#-MzXUK4QCX-VKSRhXGkK:-MzXWvrm8lYFgCEoUW25:b-5y77ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/773d9ca171edcaf2f5dd0795481c5f673aad30b5/pkg/sql/colflow/draining_test.go#L32)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Thank you for the comments. This test is a 4-star operatic masterpiece, showing in a theater near you, with popcorn.
</blockquote></details>

Haha thanks :)


<!-- Sent from Reviewable.io -->

2022-04-01 02:08 UTC, merged