kv: alter error for SET TRANSACTION AS OF SYSTEM TIME
cockroachdb/cockroach pull request #79090
Opened 2022-03-30 20:53 UTC by e-mbrown

if reads or writes  are already performed

When a txn performed a read or write before setting up a historical timestamp a crash report was generated. This commit handles the error case.

Release note: None

2022-03-30 20:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/79090)
<!-- Reviewable:end -->

2022-03-31 16:05 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1085 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-MzVhmj88QmIRaYUUmyU:-MzVhmj88QmIRaYUUmyV:b-qji22p) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f1302608a4955592d48b59c75366bba12bb8b/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1085)):*
> ```Go
> 	// The transaction must not have already been used in this epoch.
> 	if !tc.interceptorAlloc.txnSpanRefresher.refreshFootprint.empty() {
> 		return errors.WithContextTags(errors.Newf(
> ```

hm after thinking about it more, i think maybe we want to keep the assertion error here, since there are other code paths to this logic that still should be treated as programming errors

i wonder if there's a way to make pkg/sql/set_transaction.go smart enough to detect when it's allowed to run. that is, can we return a friendly user-error _before_ calling `setTransactionModes`? @ajwerner do you know if that's feasible?

also, please add tests in pkg/sql/logictest/testdata/logic_test/as_of. (use the repro in https://github.com/cockroachdb/cockroach/issues/77265#issuecomment-1060911911 as inspiration)


<!-- Sent from Reviewable.io -->

2022-04-08 16:53 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1085 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-MzVhmj88QmIRaYUUmyU:-N-94o8t9V3XxHUcswta:b-nfcmp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f1302608a4955592d48b59c75366bba12bb8b/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1085)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm after thinking about it more, i think maybe we want to keep the assertion error here, since there are other code paths to this logic that still should be treated as programming errors

i wonder if there's a way to make pkg/sql/set_transaction.go smart enough to detect when it's allowed to run. that is, can we return a friendly user-error _before_ calling `setTransactionModes`? @ajwerner do you know if that's feasible?

also, please add tests in pkg/sql/logictest/testdata/logic_test/as_of. (use the repro in https://github.com/cockroachdb/cockroach/issues/77265#issuecomment-1060911911 as inspiration)
</blockquote></details>

we should be able to add a way to check for it. in txn_state.go we can add methods for `txnState` like `hasPerformedReads` and `hasPerformedWrites` and then have that delegate to the `TxnCoordSender`. the new functions in `TxnCoordSender` can do the same check that exists here.


<!-- Sent from Reviewable.io -->

2022-04-21 17:32 UTC, rafiss requested changes
looks like the right direction!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-:-N0CAaV0CeqW2vwK8Z1a:buzmb3h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N0C9AOL2kfWrvRhi3Cj:-N0C9AOL2kfWrvRhi3Ck:b-zbds1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/aae6e97faf6fcd2f8d6d10ed1bd1378b90170390/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L152)):*
> ```Go
> 
> 		// hasPerformedWrites is set true when a write has been performed.
> 		hasPerformedWrites bool
> ```

you shouldn't need either of these booleans - it looks like they are never used

however, you do need to add the **functions** (HasPerformedReads and HasPerformedWrites) to the `TxnSender` interface in pkg/kv/sender.go
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1414 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N0C9aa82wpMBM8U95Fu:-N0C9aa82wpMBM8U95Fv:b5exryg) ([raw file](https://github.com/cockroachdb/cockroach/blob/aae6e97faf6fcd2f8d6d10ed1bd1378b90170390/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1414)):*
> ```Go
> 
> // HasPerformedReads is part of the TxnSender interface.
> func (tc *TxnCoordSender) HasPerformedReads() bool {
> ```

at the beginning of the function, can you add
```
	tc.mu.Lock()
	defer tc.mu.Unlock()
```

(like how SetFixedTimestamp has). this acquires a lock, which is needed to prevent multiple goroutines from interacting with the TxnCoordSender at the same time
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1423 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N0C9tmHB7DptivBYlNW:-N0C9tmHB7DptivBYlNX:burjabs) ([raw file](https://github.com/cockroachdb/cockroach/blob/aae6e97faf6fcd2f8d6d10ed1bd1378b90170390/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1423)):*
> ```Go
> // HasPerformedWrites is part of the TxnSender interface.
> func (tc *TxnCoordSender) HasPerformedWrites() bool {
> 	if tc.mu.txn.Sequence != 0 {
> ```

```
	tc.mu.Lock()
	defer tc.mu.Unlock()
```

here as well
___
*[pkg/sql/txn_state.go, line 294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N0C9vmlEaZsTrGJKW9O:-N0C9vmlEaZsTrGJKW9P:b-rlddra) ([raw file](https://github.com/cockroachdb/cockroach/blob/aae6e97faf6fcd2f8d6d10ed1bd1378b90170390/pkg/sql/txn_state.go#L294)):*
> ```Go
> 	defer ts.mu.Unlock()
> 
> 	if sender, ok := ts.mu.txn.Sender().(*kvcoord.TxnCoordSender); ok {
> ```

you shouldn't need the `(*kvcoord.TxnCoordSender)` type assertion
___
*[pkg/sql/logictest/testdata/logic_test/as_of, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N0CAWdZ8yb1-WxzOg6k:-N0CAWdZ8yb1-WxzOg6l:b-s80hvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/aae6e97faf6fcd2f8d6d10ed1bd1378b90170390/pkg/sql/logictest/testdata/logic_test/as_of#L118)):*
> ```
> SELECT * from t
> 
> statement error cannot set fixed timestamp, .* already performed reads or writes
> ```

the error message should just be "already performed reads" now
___
*[pkg/sql/logictest/testdata/logic_test/as_of, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N0CAS8j8Sdtaevbbc7g:-N0CAS8k6vUNkxcszZBC:b-rxjhm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/aae6e97faf6fcd2f8d6d10ed1bd1378b90170390/pkg/sql/logictest/testdata/logic_test/as_of#L119)):*
> ```
> 
> statement error cannot set fixed timestamp, .* already performed reads or writes
> SET TRANSACTION AS OF system time '-1s'
> ```

right after this line, add:

```
statement ok
ROLLBACK
```
___
*[pkg/sql/logictest/testdata/logic_test/as_of, line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N0CAZbP0UwpNlrLUCjw:-N0CAZbP0UwpNlrLUCjx:b-gf84yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/aae6e97faf6fcd2f8d6d10ed1bd1378b90170390/pkg/sql/logictest/testdata/logic_test/as_of#L127)):*
> ```
> INSERT INTO t VALUES(1)
> 
> statement error cannot set fixed timestamp, .* already performed reads or writes
> ```

the error message should just be "already performed writes" now
___
*[pkg/sql/logictest/testdata/logic_test/as_of, line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N0CAW5B9WWWU7WWbnlU:-N0CAW5C3T-uLYuMekEr:b-rxjhm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/aae6e97faf6fcd2f8d6d10ed1bd1378b90170390/pkg/sql/logictest/testdata/logic_test/as_of#L128)):*
> ```
> 
> statement error cannot set fixed timestamp, .* already performed reads or writes
> SET TRANSACTION AS OF system time '-1s'
> ```

right after this line, add:

```
statement ok
ROLLBACK
```


<!-- Sent from Reviewable.io -->

2022-04-21 19:02 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[pkg/kv/sender.go, line 341 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N0CV1VhBA3rJjxMt5p6:-N0CV1VhBA3rJjxMt5p7:bimlr35) ([raw file](https://github.com/cockroachdb/cockroach/blob/97cec15829d85d0db35b9e43adbf9baf70723fec/pkg/kv/sender.go#L341)):*
> ```Go
> 
> 	// HasPerformedReads returns true if a read has been performed.
> 	HasPerformedReads() bool
> ```

nit: these two functions also need to be implemented in pkg/kv/mock_transactional_sender.go. i'm pretty sure you can just make the implementation panic, like how it does for some of the other funcitons: https://github.com/cockroachdb/cockroach/blob/1f61d74a6869969b4e54e506a81e4343eb2f90ed/pkg/kv/mock_transactional_sender.go#L147


<!-- Sent from Reviewable.io -->

2022-04-25 15:05 UTC, rafiss requested changes
There are two lint issues:
```
pkg/kv/kvclient/kvcoord/txn_coord_sender.go:1411:2: should use 'return !tc.interceptorAlloc.txnSpanRefresher.refreshFootprint.empty()' instead of 'if !tc.interceptorAlloc.txnSpanRefresher.refreshFootprint.empty() { return true }; return false' (S1008)
```

And make sure to run `crlfmt` so that import ordering is correct:
```
        diff -u old/sql/txn_state.go new/sql/txn_state.go
        --- old/sql/txn_state.go  2022-04-21 20:47:42.634886654 +0000
        +++ new/sql/txn_state.go  2022-04-21 20:47:42.634886654 +0000
        @@ -12,13 +12,13 @@
         import (
           "context"
        -  "github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgcode"
        -  "github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror"
           "time"
           "github.com/cockroachdb/cockroach/pkg/kv"
           "github.com/cockroachdb/cockroach/pkg/roachpb"
           "github.com/cockroachdb/cockroach/pkg/settings/cluster"
        +  "github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgcode"
        +  "github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror"
           "github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
           "github.com/cockroachdb/cockroach/pkg/sql/sessiondatapb"
           "github.com/cockroachdb/cockroach/pkg/storage/enginepb"
```

2022-05-17 21:02 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/sql/conn_executor.go` line 2595 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N2Io3kMDbHQmRvRcqM3:-N2Io3kMDbHQmRvRcqM4:b-dk0ats) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8fb26a70292fbe4311f27be3c2470a8074d465/pkg/sql/conn_executor.go#L2595)):*
> ```Go
> 				"cannot set fixed timestamp, txn %s already performed writes",
> 				ex.state.mu.txn)
> 		}
> ```

could you move all of this to a new function in txn_state.go instead?

it would be something like

```
// checkReadsAndWrites returns an error if the transaction has performed reads or writes.
func (ts *txnState) checkReadsAndWrites(ctx context.Context) error {
	ts.mu.Lock()
	defer ts.mu.Unlock()

	if ts.mu.txn.Sender().HasPerformedReads() {
		return pgerror.Newf(
			pgcode.InvalidTransactionState,
			"cannot set fixed timestamp, txn %s already performed reads",
			ex.state.mu.txn)
	}
	if ts.mu.txn.Sender().HasPerformedWrites() {
		return pgerror.Newf(
			pgcode.InvalidTransactionState,
			"cannot set fixed timestamp, txn %s already performed writes",
			ex.state.mu.txn)
	}
	return nil
}
```


<!-- Sent from Reviewable.io -->

2022-05-18 15:48 UTC, rafiss requested changes
looks close! just had a small nit. also, you will need to rebase to address the test flake

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-:-N2MqhTtEhUWsn-qQF0c:b1oc5oo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/sql/txn_state.go` line 474 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N2MqcSq8ibI2wjonCkw:-N2MqcSq8ibI2wjonCkx:bbn34tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/07bb03aca7aaea9ff100a9db61689171617db038/pkg/sql/txn_state.go#L474)):*
> ```Go
> // checkReadsAndWrites returns an error if the transaction has performed reads
> // or writes.
> func (ts *txnState) checkReadsAndWrites() error {
> ```

a the beginning of this function, can you add

```
ts.mu.Lock()
defer ts.mu.Unlock()
```


<!-- Sent from Reviewable.io -->

2022-05-20 20:52 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 1086 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N2YDwzl45aviPWdTtWD:-N2YDwzl45aviPWdTtWE:b-jkt5x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1e7e05195eb1e5fb7a5911f663df6cc0b40ad17/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1086)):*
> ```Go
> 	tc.mu.Lock()
> 	defer tc.mu.Unlock()
> 	// The transaction must not have already been used in this epoch.
> ```

i'm realizing another thing -- we will want to make sure the check here is always identical to the new function that you added. so we should avoid code duplication

to do that, we can make new functions like this:

```
func (tc *TxnCoordSender) hasPerformedReadsLocked() bool {
	return !tc.interceptorAlloc.txnSpanRefresher.refreshFootprint.empty()
}

func (tc *TxnCoordSender) hasPerformedWritesLocked() bool {
	return tc.mu.txn.Sequence != 0
}
```

The "locked" in the name is a convention that indicates that you can only call this if you have acquired the lock on `tc`.
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 1087 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N2YDx_q00Pe_pQNlT5n:-N2YDx_q00Pe_pQNlT5o:b5lrwjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1e7e05195eb1e5fb7a5911f663df6cc0b40ad17/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1087)):*
> ```Go
> 	defer tc.mu.Unlock()
> 	// The transaction must not have already been used in this epoch.
> 	if !tc.interceptorAlloc.txnSpanRefresher.refreshFootprint.empty() {
> ```

then replace this with `if tc.hasPerformedReadsLocked() {`
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 1091 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N2YE42k-Lle4acdNr5z:-N2YE42k-Lle4acdNr6-:b-lxxrbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1e7e05195eb1e5fb7a5911f663df6cc0b40ad17/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1091)):*
> ```Go
> 			"cannot set fixed timestamp, txn %s already performed reads", tc.mu.txn), ctx)
> 	}
> 	if tc.mu.txn.Sequence != 0 {
> ```

and replace this with `if tc.hasPerformedWritesLocked() {`
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 1414 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N2YEDKlDt1QaSpRZMrd:-N2YEDKlDt1QaSpRZMre:b-9wwrc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1e7e05195eb1e5fb7a5911f663df6cc0b40ad17/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1414)):*
> ```Go
> 	tc.mu.Lock()
> 	defer tc.mu.Unlock()
> 	return !tc.interceptorAlloc.txnSpanRefresher.refreshFootprint.empty()
> ```

and replace this with `return tc.hasPerformedReadsLocked() {`
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 1421 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N2YECSMExA6aZ5b_nWu:-N2YECSMExA6aZ5b_nWv:b-lxxrbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1e7e05195eb1e5fb7a5911f663df6cc0b40ad17/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1421)):*
> ```Go
> 	tc.mu.Lock()
> 	defer tc.mu.Unlock()
> 	return tc.mu.txn.Sequence != 0
> ```

and replace this with `if tc.hasPerformedWritesLocked() {`


<!-- Sent from Reviewable.io -->

2022-05-24 18:28 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 1425 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N2rHQXQDLKP7oH9d4ZK:-N2rHQXQDLKP7oH9d4ZL:bkk05qe) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0383347dde2ff1d8d11c001d0ff9057ac5f30b/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1425)):*
> ```Go
> 
> // HasPerformedReadsLocked is part of the TxnSender interface.
> func (tc *TxnCoordSender) HasPerformedReadsLocked() bool {
> ```

nit: make this lower case (so that the function is not visible outside of this package). also, remove the comment
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender.go` line 1430 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N2rHWKMCTaIL0wzjEpv:-N2rHWKMCTaIL0wzjEpw:bkk05qe) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0383347dde2ff1d8d11c001d0ff9057ac5f30b/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1430)):*
> ```Go
> 
> // HasPerformedWritesLocked is part of the TxnSender interface.
> func (tc *TxnCoordSender) HasPerformedWritesLocked() bool {
> ```

nit: make this lower case (so that the function is not visible outside of this package). also, remove the comment


<!-- Sent from Reviewable.io -->

2022-05-25 02:34 UTC, rafiss requested changes
> Reviewed 2 of 4 files at r4, 1 of 1 files at r5, 1 of 3 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-05-26 17:00 UTC, rafiss approved these changes
lgtm!

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-:-N30IrPq0ppv2kTPCZJ2:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-05-31 19:12 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-:-N3QX8uoBUGPoQQ0aK8X:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[`pkg/kv/sender.go` line 340 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/79090#-N3QX2jDDAWvKRAqoxVZ:-N3QX2jDDAWvKRAqoxV_:b-wi8dq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/40151deb29884a9990d253336436dd5d4b95783c/pkg/kv/sender.go#L340)):*
> ```Go
> 	ClearTxnRetryableErr(ctx context.Context)
> 
> 	// HasPerformedReads returns true if a read has been performed.
> ```

Let's add "in the transaction's current epoch" at the end of both of these comments.


<!-- Sent from Reviewable.io -->

2022-06-01 19:21 UTC, e-mbrown commented
TFTR!

bors r+

2022-06-01 21:32 UTC, merged