introduce show create secondary indexes from table_name
cockroachdb/cockroach pull request #79201
Opened 2022-04-01 06:48 UTC by arenatlx

Signed-off-by: arenatlx <tlxarena@gmail.com>

close issue https://github.com/cockroachdb/cockroach/issues/74748

2022-04-01 06:48 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=79201) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=79201) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=79201) it.</sub>

2022-04-01 06:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/79201)
<!-- Reviewable:end -->

2022-04-21 17:12 UTC, Xiang-Gu requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arenatlx and @mgartner)

___
*[pkg/sql/logictest/testdata/logic_test/show_create, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79201#-N0C3orF5Nx3cQ7Ilv4j:-N0C3orF5Nx3cQ7Ilv4k:b-tppq24) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bedac91a793b85aee584560038dec9b0e2cec81/pkg/sql/logictest/testdata/logic_test/show_create#L124)):*
> ```
> CREATE INDEX c_a_b_idx ON c (a ASC, b ASC)
> CREATE UNIQUE INDEX unique_a ON c (a ASC)
> CREATE INDEX test_idx ON c (b DESC, a ASC)
> ```

Hi, I'm new to the team and now learning to get myself into code reviews. I'm just browsing PRs to learn what other people are doing and ask some questions around. Please don't count solely on me to be the one to give final approval even if I might be the first one to leave a comment.


1. why don't we show the full resolved path for `c` in the response? e.g. CREATE INDEX test_idx ON public.c (b DESC, a ASC) because this is exactly the same command that created this index.

2. What will happen if the index is created implicitly? E.g. if I create a table with a unique column, a unique secondary index will be automatically created. Will we be able to also show this implicitly created secondary index?

3. What will happen for stored columns in the index? What should the response look like?

4. Did we make sure the response is consistent with "SHOW INDEX FROM table" in that they're identical except for the primary index? 


<!-- Sent from Reviewable.io -->

2022-04-21 18:36 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arenatlx, @mgartner, and @Xiang-Gu)

___
*[pkg/sql/delegate/show_table.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79201#-N0CNrfY6B22e0OBiU0L:-N0CNrfY6B22e0OBiU0M:b-hqjkk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bedac91a793b85aee584560038dec9b0e2cec81/pkg/sql/delegate/show_table.go#L94)):*
> ```Go
> 	index_basic`
> 
> 	return d.showTableDetails(n.Name, showCreateSecondaryIndexFromTable)
> ```

I think that my preference for the implementation of this would be to add a `create_statement` field to `crdb_internal.table_indexes` and then leverage https://github.com/cockroachdb/cockroach/blob/36d1b608bbabd7cf40bf18db513012653dabbfe9/pkg/sql/catalog/catformat/index.go#L53 internally. If there's concern that that'll make the virtual table more expensive, then I'd like us to refactor the logic of the virtual table out and add a new virtual table which has the added field, maybe `crdb_internal.table_indexes_with_create`. Then the delegate can access that directly. I'd also like us to leverage name resolution via `regclass` if we can so that we can get `O(1)` lookup for a single table.

Concretely, this means:

1) Add a `create_statement` column to `crdb_internal.table_indexes`
2) Change this delegate to:
```
SELECT create_statement FROM crdb_internal.table_indexes WHERE descriptor_id = $1::regclass::int AND index_type != 'primary'
```
___
*[pkg/sql/logictest/testdata/logic_test/show_create, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79201#-N0C3orF5Nx3cQ7Ilv4j:-N0CMVeu6k9zoZpRvnKV:b-6u0sg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bedac91a793b85aee584560038dec9b0e2cec81/pkg/sql/logictest/testdata/logic_test/show_create#L124)):*
These are all great questions! 

> Did we make sure the response is consistent with "SHOW INDEX FROM table" in that they're identical except for the primary index?

`SHOW INDEX` has a tabular format that doesn't print any syntax like this. 


<!-- Sent from Reviewable.io -->

2022-05-03 08:04 UTC, arenatlx commented
impressive instructions, thx a lot @ajwerner @Xiang-Gu

2022-05-14 06:59 UTC, arenatlx commented
PTAL again thx @ajwerner @Xiang-Gu

2022-05-20 19:22 UTC, Xiang-Gu reviewed
Hi @arenatlx Can you take some time to address our comments?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79201#-:-N2XuYa9348rjs5T2Ak7:b3fxt2s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arenatlx, @mgartner, and @Xiang-Gu)



<!-- Sent from Reviewable.io -->

2022-05-21 07:30 UTC, arenatlx commented
> Hi @arenatlx Can you take some time to address our comments?
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79201#-:-N2XuYa9348rjs5T2Ak7:b3fxt2s)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arenatlx, @mgartner, and @Xiang-Gu)

I think i did.
I followed what [ajwerner](https://github.com/ajwerner) said, and for your questions.
1: yes we did, `IndexForDisplay` can output like that.
2: yes we did, unique keyword is also a kind of unique constraint implemented by a unique index. 
3: for a stored column, since `IndexForDisplay` hasn't unfolded them to expression before, we output the delegate name.
4: `IndexForDisplay` has its tabular format quite different from what the index in show-create-table does.

2022-05-30 03:24 UTC, otan reviewed
can you fold all these commits into one? `git rebase -i HEAD~9` and doing a fixup on the following 8 commits and then `git push --force` should do the trick.

Please also make sure that one commit has the release note.

2022-05-30 03:29 UTC, otan commented on pkg/sql/delegate/show_table.go
> +	const showCreateSecondaryIndexFromTable = `SELECT create_statement FROM crdb_internal.table_indexes WHERE descriptor_id = %[2]s::regclass::int AND index_type != 'primary'`
i think this doesn't work when you use `SHOW CREATE SECONDARY INDEXES FROM <other_db>.table`. can you try it on a table on another database in the lgoic tests?

to fix this, you'll need to follow how `SHOW CREATE TABLE` references `<database_name>.crdb_internal.table_indexes` which will fetch the correct result

2022-05-30 03:30 UTC, otan commented on pkg/sql/logictest/testdata/logic_test/show_create
> +SHOW CREATE SECONDARY INDEXES FROM public.c
can you try this on a table which doesn't exist as well?

2022-06-15 20:22 UTC, Xiang-Gu reviewed
I'm sorry that I was aware of the request and I let it sit for so long. Your changes look good to me! Thank you for contributing to CRDB!

One last thing, I saw you added logic to build the PARTITION BY clause.  Can you add a test case to show a secondary index with PARTITION BY?

2022-06-15 20:24 UTC, Xiang-Gu approved these changes

2022-06-23 07:07 UTC, arenatlx commented
from the bazel ci log, it's hard to tell what's going on, I have no idea.  =.=  Somebody can help take a look at this?
(even GitHub ci has already been successful before)

2022-10-18 19:55 UTC, closed without merging