sql: version gating pkey virtual column validation.
cockroachdb/cockroach pull request #79345
Opened 2022-04-04 16:15 UTC by chengxiong-ruan

fixes: #79329

Release justification: version gating is needed to prevent descriptor
validation failures on 21.2.x nodes when a table is created with virtual
column in pkey on a 22.1.x node. This could happened is mixed version
clusters during upgrades.
Release note: None

2022-04-04 16:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/79345)
<!-- Reviewable:end -->

2022-04-04 16:19 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/catalog/tabledesc/validate.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79345#-MzpMblIEiMUXRH_Avut:-MzpMblIEiMUXRH_Avuu:blmjwre) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67c6af18ed38b8fdea772aa62b6ec1d6a38c533/pkg/sql/catalog/tabledesc/validate.go#L478)):*
> ```Go
> // If version is supplied, the descriptor is checked for version incompatibilities.
> func (desc *wrapper) ValidateSelf(
> 	vea catalog.ValidationErrorAccumulator, version clusterversion.ClusterVersion,
> ```

I feel like plumbing this version through could be quite useful for future descriptor improvements. Do we want to make this change for 22.2 as well?
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1061 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79345#-MzpMETG5uOu3yuv5fvr:-MzpMETG5uOu3yuv5fvs:b-cx8o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67c6af18ed38b8fdea772aa62b6ec1d6a38c533/pkg/sql/catalog/tabledesc/validate.go#L1061)):*
> ```Go
> 	}
> 
> 	if !version.IsActive(clusterversion.Start22_1) {
> ```

using the first version as gating could be aggressive, I can change it to the last version. But I think this is fine.


<!-- Sent from Reviewable.io -->

2022-04-04 16:21 UTC, chengxiong-ruan commented
note that this pr is created against 22.1 release branch. so I didn't add todo to remove version gates.





<!-- Sent from Reviewable.io -->

2022-04-04 16:32 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[pkg/sql/catalog/tabledesc/validate.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79345#-MzpMblIEiMUXRH_Avut:-MzpPl3N41eMy6bMCcMi:b-eij8rf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67c6af18ed38b8fdea772aa62b6ec1d6a38c533/pkg/sql/catalog/tabledesc/validate.go#L478)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I feel like plumbing this version through could be quite useful for future descriptor improvements. Do we want to make this change for 22.2 as well?
</blockquote></details>

ValidationErrorAccumulator already has the active version as a field, so you can simplify things. We added versioning because of constraint IDs



_Code quote:_
```Go
ValidationErrorAccumulator
```


<!-- Sent from Reviewable.io -->

2022-04-04 17:12 UTC, chengxiong-ruan commented
*[pkg/sql/catalog/tabledesc/validate.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79345#-MzpMblIEiMUXRH_Avut:-MzpZ6B5B9he0dnm34Aw:b-1o4p3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67c6af18ed38b8fdea772aa62b6ec1d6a38c533/pkg/sql/catalog/tabledesc/validate.go#L478)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

ValidationErrorAccumulator already has the active version as a field, so you can simplify things. We added versioning because of constraint IDs
</blockquote></details>

ah, good to know thanks, will update.


<!-- Sent from Reviewable.io -->

2022-04-04 17:25 UTC, chengxiong-ruan commented
*[pkg/sql/catalog/tabledesc/validate.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79345#-MzpMblIEiMUXRH_Avut:-Mzpb5Rb-EAgE2gmq4S6:b-u840fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67c6af18ed38b8fdea772aa62b6ec1d6a38c533/pkg/sql/catalog/tabledesc/validate.go#L478)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

ah, good to know thanks, will update.
</blockquote></details>

updated to use vea.


<!-- Sent from Reviewable.io -->

2022-04-04 17:28 UTC, chengxiong-ruan commented
oops...looks like this is linked with JIRA and I closed that JIRA ticket >_>

2022-04-04 21:32 UTC, ajwerner reviewed
I don't love that the only checking is in validation. Can we also gate it in the schema change itself and in that gate, put a proper pgcode? 

> Reviewed 3 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79345#-:-MzqUQhcApEC9wSATflV:bjp8ydu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @fqazi)



<!-- Sent from Reviewable.io -->

2022-04-04 21:50 UTC, chengxiong-ruan commented
ha yeah, I thought about that as well but decided to just add the validation back as we did before since that's the only defense we have before allowing virtual columns in pkey. But I can add more checks in the schema changer layer.





<!-- Sent from Reviewable.io -->

2022-04-04 22:25 UTC, ajwerner commented
Yeah fair. This is an edge case with to-be-deleted code. The thing is, the random schema change workload is still going to fail because it doesn't like unclassified errors. I think we'll at least need to give it a pgcode. We also may need to teach that thing to expect this pgcode.

2022-04-05 00:05 UTC, chengxiong-ruan commented
ah, make sense! I've added the check at schema changer level as well. Will look into the randomized test part, or maybe I'll bother Faizan tomorrow.





<!-- Sent from Reviewable.io -->

2022-04-05 14:46 UTC, chengxiong-ruan commented
@ajwerner I gave it a pgcode `InvalidSchemaDefinition` which I think is proper. But I feel like, instead of teaching it about the pgcode, it make more sense to teach the randomized test the error message in this special case. Because giving it a proper pgcode is nice, but it could also mean something else failed, and here I think we just want to keep looking for a proper schema operation when seeing the specific errors I added in this pr. By that I'm talking about checking error message here: https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/schemachange/operation_generator.go#L266-L266





<!-- Sent from Reviewable.io -->

2022-04-05 14:49 UTC, chengxiong-ruan commented
Or.. we may add a `mixedVersion` flag to the workload to indicate the context of the test (this can be future though...)





<!-- Sent from Reviewable.io -->

2022-04-05 14:49 UTC, ajwerner commented
You could also just give it `FeatureNotSupported`. 

> the error message in this special case. 
Nothing in the workload today looks at error messages. I *think* that's good? It's already so brittle.

2022-04-05 15:50 UTC, chengxiong-ruan commented
ah, `FeatureNotSupported` is a good one actually, in that case we don't need to check the mixed version context then.





<!-- Sent from Reviewable.io -->

2022-04-06 22:45 UTC, chengxiong-ruan commented
*[pkg/workload/schemachange/operation_generator.go, line 3045 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79345#-N-01O4UBmn9OOhhGdC9:-N-01O4UBmn9OOhhGdCA:b-p6t82s) ([raw file](https://github.com/cockroachdb/cockroach/blob/55485a6acd38f37bc84f734579434b98a0913755/pkg/workload/schemachange/operation_generator.go#L3045)):*
> ```Go
> // here is that if running in a mixed cluster the cluster version is always
> // the maximum cluster version from predecessor binary.
> func isInMixedVersion(ctx context.Context, tx pgx.Tx) (bool, error) {
> ```

@fqazi I verified that this should work. I hacked workload (both with and without this fix) to run with only `create table`. Also hacked the workload so that it generated mostly virtual columns. roachtest passed with this test but failed with the pkey virtual column error.


<!-- Sent from Reviewable.io -->

2022-04-07 14:24 UTC, fqazi requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @fqazi)

___
*[pkg/workload/schemachange/operation_generator.go, line 1129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79345#-N-3ON1L709Nhamcfspm:-N-3ON1L709Nhamcfspn:bkggjm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/55485a6acd38f37bc84f734579434b98a0913755/pkg/workload/schemachange/operation_generator.go#L1129)):*
> ```Go
> 		{code: pgcode.DuplicateRelation, condition: tableExists && !stmt.IfNotExists},
> 		{code: pgcode.UndefinedSchema, condition: !schemaExists},
> 		{code: pgcode.FeatureNotSupported, condition: mixedVersion},
> ```

We can get the caller to pass in the version (and turn the check into <=), maybe rename this isClusterVersionLessThan. Can you add a description of why we are detecting this, and a  TODO for more precise detection (you can put my name on it)? I'll deal with that separately, in a different PR



_Code quote:_
```Go
{code: pgcode.FeatureNotSupported, condition: mixedVersion},
```


<!-- Sent from Reviewable.io -->

2022-04-07 15:10 UTC, fqazi requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @fqazi)

___
*[pkg/workload/schemachange/operation_generator.go, line 1129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79345#-N-3ON1L709Nhamcfspm:-N-3ZTyt-nrBjE4cxGw5:b-rgzam7) ([raw file](https://github.com/cockroachdb/cockroach/blob/55485a6acd38f37bc84f734579434b98a0913755/pkg/workload/schemachange/operation_generator.go#L1129)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

We can get the caller to pass in the version (and turn the check into <=), maybe rename this isClusterVersionLessThan. Can you add a description of why we are detecting this, and a  TODO for more precise detection (you can put my name on it)? I'll deal with that separately, in a different PR
</blockquote></details>

Actually this won' work perfectly, we need to detect the specific case too. Its an expected error, so we need to detect this properly based on the column definitions. So, that second part can't be a TODO


<!-- Sent from Reviewable.io -->

2022-04-07 20:01 UTC, fqazi commented
I opened: https://github.com/cockroachdb/cockroach/pull/79609, this has a fix for the schemachanger workload inside it too. The rest of the code is the same.

2022-04-07 23:37 UTC, closed without merging