[wip] nightly: enable race for nightly pebble metamorphic test
cockroachdb/cockroach pull request #79468
Opened 2022-04-05 22:50 UTC by bananabrick

2022-04-05 22:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/79468)
<!-- Reviewable:end -->

2022-04-05 23:19 UTC, bananabrick commented
This isn't the full pr, just testing out a basic configuration.

2022-04-06 01:49 UTC, bananabrick commented
Looks like it worked. Adding the race flag for 20% of the runs.

2022-04-06 02:05 UTC, nicktrav commented
Any reason we can't spawn two jobs, the existing job, _in addition to_ a job that runs with race enabled?

One downside I see with this approach is that for 20% of runs we'll have reduced coverage in terms of "total metamorphic test run time" (for example, when we made the decision to do fewer runs that use disk, as the runs are slower). That said, we do gain the "total race test run time" in its place.

I'm not opposed to doing it this way, just wondering why we couldn't do a second job, which is strictly "better", as we'll have both.

cc: @jbowens for thoughts.

2022-04-06 02:08 UTC, bananabrick reviewed
Yea, we can do that. I'll update this.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79468#-:-Mzwc4xS3UnLYNkl7ZI0:bgw4uwb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nicktrav)



<!-- Sent from Reviewable.io -->

2022-04-06 03:28 UTC, bananabrick commented
Looks like it's going to pass. This should be good for another review.

2022-04-06 14:09 UTC, nicktrav approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - thanks for adding this. Perhaps wait on someone from dev-inf to take a look too.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79468#-:-MzzC8gyBEUYIBibaiaG:b-n22ljr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick)

___
*[-- commits, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79468#-MzzBh8pAVqbBAmIZ_Rk):*
Squash?


<!-- Sent from Reviewable.io -->

2022-04-06 15:46 UTC, rickystewart requested changes

2022-04-06 15:46 UTC, rickystewart commented on build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_race_impl.sh
> +BAZEL_BIN=$(bazel info bazel-bin --config race --config ci)
The `bazel info` invocation should match up to what you have in `bazel build`. In this case it's `--config ci`, not `--config race --config ci`.

2022-04-06 15:46 UTC, rickystewart commented on build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_race_impl.sh
> +$BAZEL_BIN/pkg/cmd/bazci/bazci_/bazci --config race --config=ci test \
Nit: `--config=race` to make it consistent

2022-04-06 17:08 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79468)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nicktrav and @rickystewart)

___
*[build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_race_impl.sh, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79468#-MzwmURhbDPymEGQeF0Y-r3-15:-MzzqBhP8zildpd0hnMf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18eab34bdf71e61831086fd5ea15d0d7c7361a22/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_race_impl.sh#L15)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

The `bazel info` invocation should match up to what you have in `bazel build`. In this case it's `--config ci`, not `--config race --config ci`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-06 17:11 UTC, rickystewart approved these changes

2022-04-06 17:20 UTC, bananabrick commented
tftrs!

bors r+

2022-04-06 17:22 UTC, bananabrick commented
bors r-

waiting for build to pass

2022-04-06 18:52 UTC, bananabrick commented
bors r+

2022-04-06 22:32 UTC, merged