roachtest: use SQL comparison in TLP
cockroachdb/cockroach pull request #79551
Opened 2022-04-06 22:39 UTC by michae2

Assists: #77279

TLP compares results of two queries, one unpartitioned and one
partitioned three ways by a predicate. We were comparing TLP results by
printing values to strings. Unfortunately there are some values which
are equal according to SQL comparison, but print differently. And TLP,
being the nefarious chaos monkey that it is, tends to find these. For
example:

  0::FLOAT
  -0::FLOAT;

  'hello' COLLATE "en-US-u-ks-level2"
  'HELLO' COLLATE "en-US-u-ks-level2";

  INTERVAL '1 day'
  INTERVAL '24 hours';

When equal-yet-different values like these are used in MAX or MIN
aggregations, or are the keys for GROUP BY bucketing, it is
nondeterministic which value will be chosen. (This is also true in
PostgreSQL.) And sometimes the two TLP queries choose differently. This
is not indicative of a bug, yet TLP fails.

So this patch teaches TLP to use SQL comparison instead of string
comparison. To do so, we wrap both queries in a bigger query:

  WITH unpart AS MATERIALIZED (
    <unpartitioned query>
  ), part AS MATERIALIZED (
    <partitioned query>
  ), undiff AS (
    TABLE unpart EXCEPT ALL TABLE part
  ), diff AS (
    TABLE part EXCEPT ALL TABLE unpart
  )
  SELECT (SELECT count(*) FROM undiff), (SELECT count(*) FROM diff);

Only if this query returns counts other than 0 (meaning the SQL
comparison detected a real mismatch) do we diff the printed results.

Release note: None

2022-04-06 22:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/79551)
<!-- Reviewable:end -->

2022-04-06 23:12 UTC, msirek approved these changes
Very clever solution!  
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79551#-:-N-07zxo-6dj0q1yaoTr:b6maqec)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)



<!-- Sent from Reviewable.io -->

2022-04-07 20:47 UTC, yuzefovich approved these changes
Nice! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79551#-:-N-4lpeLE5gHOpsyFBIL:be8rotp)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)



<!-- Sent from Reviewable.io -->

2022-04-08 16:33 UTC, mgartner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79551)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2)

___
*[pkg/cmd/roachtest/tests/tlp.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79551#-N-90NPC0U1gnKRR6Znh:-N-90NPC0U1gnKRR6Zni:b-5z43fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdacf77e976a0b8ba2eeae5061a62d01e8d8efb1/pkg/cmd/roachtest/tests/tlp.go#L256)):*
> ```Go
> 		}
> 
> 		if diff := unsortedMatricesDiff(unpartitionedRows, partitionedRows); diff != "" {
> ```

You can remove all the of `sqlutils.RowsToStrMatrix` and `unsortedMatricesDiff` stuff now, right?


<!-- Sent from Reviewable.io -->

2022-04-08 16:35 UTC, mgartner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79551)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2)

___
*[pkg/cmd/roachtest/tests/tlp.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79551#-N-90NPC0U1gnKRR6Znh:-N-90gff-U-LiDmXbXTP:b-quij2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdacf77e976a0b8ba2eeae5061a62d01e8d8efb1/pkg/cmd/roachtest/tests/tlp.go#L256)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You can remove all the of `sqlutils.RowsToStrMatrix` and `unsortedMatricesDiff` stuff now, right?
</blockquote></details>

I suppose you kept this so that the diff is still printed? I don't find it all that useful - the partitioned and unpartitioned queries are enough to begin diagnosing. But if you think it's useful, we can keep it.

But you will have to remove the error below to prevent these false positives.


<!-- Sent from Reviewable.io -->

2022-04-08 16:37 UTC, mgartner commented
*[pkg/cmd/roachtest/tests/tlp.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79551#-N-90NPC0U1gnKRR6Znh:-N-919yE1Zk92v2Ygkfo:b-auumnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdacf77e976a0b8ba2eeae5061a62d01e8d8efb1/pkg/cmd/roachtest/tests/tlp.go#L256)):*
> But you will have to remove the error below to prevent these false positives.

Oh, nevermind, I see the early returns.


<!-- Sent from Reviewable.io -->

2022-04-08 16:38 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79551)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/cmd/roachtest/tests/tlp.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79551#-N-90NPC0U1gnKRR6Znh:-N-91T0377jmfJET7AKx:boeojh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdacf77e976a0b8ba2eeae5061a62d01e8d8efb1/pkg/cmd/roachtest/tests/tlp.go#L256)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> But you will have to remove the error below to prevent these false positives.

Oh, nevermind, I see the early returns.
</blockquote></details>

I think I also don't find the diffs very useful either, so I'm +1 on removing the old stringified comparison altogether.


<!-- Sent from Reviewable.io -->

2022-04-08 17:06 UTC, michae2 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79551)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[pkg/cmd/roachtest/tests/tlp.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79551#-N-90NPC0U1gnKRR6Znh:-N-97e2a8NQLxWkeda55:b-jys1o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdacf77e976a0b8ba2eeae5061a62d01e8d8efb1/pkg/cmd/roachtest/tests/tlp.go#L256)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think I also don't find the diffs very useful either, so I'm +1 on removing the old stringified comparison altogether.
</blockquote></details>

Without the printed diff, won't it be more difficult to triage TLP issues? For example, when TLP was hitting #77279 it was easy to look at the diff in the issue and see "-0" and dupe it. But maybe I'm overthinking it?


<!-- Sent from Reviewable.io -->

2022-04-08 18:05 UTC, mgartner commented
> it was easy to look at the diff in the issue and see "-0" and dupe it.

Well, the diff fooled us into thinking it was a duplicate, but there was actually two separate cases - one was a false positive but the other was an actual correctness bug.

But I'm fine leaving it for now and seeing if it proves useful. Up to you.

2022-04-08 18:42 UTC, michae2 commented
> Well, the diff fooled us into thinking it was a duplicate, but there was actually two separate cases - one was a false positive but the other was an actual correctness bug.
> 
> But I'm fine leaving it for now and seeing if it proves useful. Up to you.

Good point! Hmm. After thinking about it, I left the diff but changed the logic slightly so that the test only depends on SQL comparison, and the diff is purely informative. This will make it easy to remove the diff if we so decide.

2022-04-11 20:39 UTC, michae2 commented
TFTRs!

Bazel CI failure looks unrelated, so I'll go ahead and merge.

bors r+

2022-04-11 23:24 UTC, merged

2022-05-04 22:54 UTC, michae2 commented
blathers backport 22.1