sql: add virtual indexes to crdb_internal.cluster_locks virtual table
cockroachdb/cockroach pull request #79623
Opened 2022-04-07 23:04 UTC by AlexTalks

This change adds virtual indexes on the `table_id`, `database_name`, and
`table_name` columns of the `crdb_internal.cluster_locks` virtual table,
so that when queried, the `kv.Batch`es with `QueryLocksRequest`s can be
constrained to query only specific tables or databases. This allows the
requests to be much more limited, rather than needing to request all of
the ranges that comprise the key spans of all tables accessible by the
user.

Release note (sql change): Improved query performance for
`crdb_internal.cluster_locks` when issued with constraints in the WHERE
clause on `table_id`, `database_name`, or `table_name` columns.

NOTE: depends on #77876

2022-04-07 23:04 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/79623)
<!-- Reviewable:end -->

2022-04-22 03:18 UTC, nvanbenschoten requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @rafiss)

___
*[pkg/sql/crdb_internal.go, line 5837 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79623#-N0EGftn1RzN8fYTHM9f:-N0EGftn1RzN8fYTHM9g:b-x67i2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab8db0df41e33c5fe097105526aeeb90cb36f32/pkg/sql/crdb_internal.go#L5837)):*
> ```Go
>     contended           BOOL,
>     duration            INTERVAL,
>     INDEX(table_id),
> ```

Do we have tests that exercise each of these indexes?
___
*[pkg/sql/crdb_internal.go, line 5844 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79623#-N0EFp541A-jr0gug7n-:-N0EFp541A-jr0gug7n0:b-e77xba) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab8db0df41e33c5fe097105526aeeb90cb36f32/pkg/sql/crdb_internal.go#L5844)):*
> ```Go
> 	indexes: []virtualIndex{
> 		{
> 			populate: func(
> ```

Could you give each of these objects that somehow indicate which INDEX they're implementing?
___
*[pkg/sql/crdb_internal.go, line 6023 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79623#-N0EG5uv9aH33cbJOKFS:-N0EG5uv9aH33cbJOKFT:b49ffwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab8db0df41e33c5fe097105526aeeb90cb36f32/pkg/sql/crdb_internal.go#L6023)):*
> ```Go
> 				IncludeUncontended: true,
> 			}
> 			if filters.contended != nil && *filters.contended {
> ```

If `!*filters.contended`, don't we want to include _only_ uncontended locks?


<!-- Sent from Reviewable.io -->

2022-04-25 21:30 UTC, AlexTalks reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 5837 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79623#-N0EGftn1RzN8fYTHM9f:-N0Xazrj5LoEMIkFWaoN:b-1fo756) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab8db0df41e33c5fe097105526aeeb90cb36f32/pkg/sql/crdb_internal.go#L5837)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we have tests that exercise each of these indexes?
</blockquote></details>

OK - Added these!  I'm not sure if I should also add a small test that double checks the query plan to make sure it's using the index?  If so let me know!
___
*[`pkg/sql/crdb_internal.go` line 5844 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79623#-N0EFp541A-jr0gug7n-:-N0Xb9l0Cb7eQfSMn0R0:b-a09kkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab8db0df41e33c5fe097105526aeeb90cb36f32/pkg/sql/crdb_internal.go#L5844)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you give each of these objects that somehow indicate which INDEX they're implementing?
</blockquote></details>

Not sure I understand - you mean comments?  Or you mean rename `unwrappedConstraint` to, say, `tableNameConstraint` for example?
___
*[`pkg/sql/crdb_internal.go` line 6023 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79623#-N0EG5uv9aH33cbJOKFS:-N0XbTeL3ptofeayAFeD:b-13fnzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab8db0df41e33c5fe097105526aeeb90cb36f32/pkg/sql/crdb_internal.go#L6023)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If `!*filters.contended`, don't we want to include _only_ uncontended locks?
</blockquote></details>

Yes - filtering this out, however, is already handled by the virtual schema table - only the rows that match the index constraint will be returned anyway, so we can instead focus here on limiting our request.


<!-- Sent from Reviewable.io -->

2022-04-26 00:22 UTC, otan commented on pkg/sql/logictest/testdata/logic_test/cluster_locks
> +SELECT database_name, schema_name, table_name, lock_key_pretty, lock_strength, durability, granted, contended FROM crdb_internal.cluster_locks WHERE database_name='test'
can you add a test for `table_id` and `table_name`?

to get the tableid, you can probably do `WHERE table_id = 'table_name'::regclass::oid::int`.

2022-04-26 02:04 UTC, AlexTalks reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @otan, and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/cluster_locks` line 149 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/79623#-N03fajHCD2Z8ZNl8xOW-r5-149:-N0Yb-IbD86xwWexOhcb:b-9kht3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46eafe34d0df8f8edf965bcd3a4c25f1be951ac/pkg/sql/logictest/testdata/logic_test/cluster_locks#L149)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can you add a test for `WHERE table_id = ...` and `WHERE table_name = ...`?

to get the tableid, you can probably do `WHERE table_id = 'table_name'::regclass::oid::int`. 
</blockquote></details>

OK - had a few with `table_name = ...` previously, but I just added one with `table_id`.


<!-- Sent from Reviewable.io -->

2022-04-26 02:04 UTC, AlexTalks reviewed
> Dismissed @otan from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @otan, and @rafiss)



<!-- Sent from Reviewable.io -->

2022-04-26 03:13 UTC, otan approved these changes

2022-04-26 18:01 UTC, AlexTalks reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 5844 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79623#-N0EFp541A-jr0gug7n-:-N0b0rdfARSkIVCk04Mk:b-p7a8fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab8db0df41e33c5fe097105526aeeb90cb36f32/pkg/sql/crdb_internal.go#L5844)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Not sure I understand - you mean comments?  Or you mean rename `unwrappedConstraint` to, say, `tableNameConstraint` for example?
</blockquote></details>

Done.  I refactored these a bit to use a generator, with the index-specific bits of logic passed in so it should now be pretty clear what these are.  


<!-- Sent from Reviewable.io -->

2022-05-13 23:46 UTC, AlexTalks commented
bors r+

2022-05-14 02:58 UTC, merged