[CRDB-13531] ui: enable dropdown filtering on node diagnostics page
cockroachdb/cockroach pull request #79900
Opened 2022-04-13 16:05 UTC by Santamaura

Previosuly, when a user navigated to the node diagnostics
page all node regardless of status were listed. This is
inconvenient when the user only wants to see active nodes.
Therefore, this patch add a dropdown filter to allow users
to view active nodes, decomissioned nodes, or all nodes.

resolves #77333

Release note (ui change): add dropdown filter on the node
diagnostics page to view by active, decomissioned or all nodes.

![Screen Shot 2022-04-13 at 12 04 59 PM](https://user-images.githubusercontent.com/17861665/163222971-afd32cc0-09d1-4af7-a48d-fb7f8a6fcefb.png)

2022-04-13 16:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/79900)
<!-- Reviewable:end -->

2022-04-14 08:54 UTC, koorosh requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79900)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N-bBmEA28BvYQAd1QQ8:-N-bBmEA28BvYQAd1QQ9:bgrlo7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/154676de863db1d47dc696f00684ac4a4db14005/pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx#L274)):*
> ```XML
> ];
> 
> type LocalNodeState = { selectFilter: string };
> ```

I have concerns about storing `selectFilter` as a string type. It forces you to perform multiple type castings from `number` to `string`. I suggest defining it as `number|null` type. NULL can be used for the "All nodes" case. 
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx, line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N-b9JEo7QNQTkeVqXWj:-N-b9JEo7QNQTkeVqXWk:b-mf290v) ([raw file](https://github.com/cockroachdb/cockroach/blob/154676de863db1d47dc696f00684ac4a4db14005/pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx#L283)):*
> ```XML
> 
>     this.state = {
>       selectFilter: _.isEmpty(this.props.location.search)
> ```

Can we parse specific search parameters to define the initial filter option? 
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx, line 421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N-bGc4I8gD-Q-d6WkCz:-N-bGc4I8gD-Q-d6WkD-:brm0hb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/154676de863db1d47dc696f00684ac4a4db14005/pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx#L421)):*
> ```XML
>         />
>         {!_.isEmpty(orderedNodeIDs) && <h2 className="base-heading">Nodes</h2>}
>         {_.isEmpty(filters) && (
> ```

Why do we need to check whether the `filters` array is empty? 


<!-- Sent from Reviewable.io -->

2022-04-14 09:01 UTC, koorosh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79900)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N-bI8M1AzuYcmHgTH8K:-N-bI8M26pXkMRCz8Q0R:b-6lt7g8) ([raw file](https://github.com/cockroachdb/cockroach/blob/154676de863db1d47dc696f00684ac4a4db14005/pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx#L387)):*
> ```XML
>     }
>     if (this.state.selectFilter !== "-1") {
>       nodeIDsContext = nodeIDsContext.filter(
> ```

Does this filtering implement the behavior described here: https://github.com/cockroachdb/cockroach/issues/77333#issuecomment-1075597236 


<!-- Sent from Reviewable.io -->

2022-04-19 15:24 UTC, Santamaura reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79900)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N-bBmEA28BvYQAd1QQ8:-N01Nr0y11GebXqAxjMI:bqlcdv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/154676de863db1d47dc696f00684ac4a4db14005/pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx#L274)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I have concerns about storing `selectFilter` as a string type. It forces you to perform multiple type castings from `number` to `string`. I suggest defining it as `number|null` type. NULL can be used for the "All nodes" case. 
</blockquote></details>

Sure, changed to `number | null`. One thing that should be noted is that `DropdownOption` values need to be string so we will need to convert at that point of interaction.
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx, line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N-b9JEo7QNQTkeVqXWj:-N01ODwC9z2deSvqVpv2:b-6z284t) ([raw file](https://github.com/cockroachdb/cockroach/blob/154676de863db1d47dc696f00684ac4a4db14005/pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx#L283)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Can we parse specific search parameters to define the initial filter option? 
</blockquote></details>

I changed it to use `getFilters()` which checks for specific filters. 
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N-bI8M1AzuYcmHgTH8K:-N01PEg0CdMMIYu4gT-6:br28p4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/154676de863db1d47dc696f00684ac4a4db14005/pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx#L387)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Does this filtering implement the behavior described here: https://github.com/cockroachdb/cockroach/issues/77333#issuecomment-1075597236 
</blockquote></details>

Ah good catch I didn't see that comment. I've changed it such that if the selection is `Active Nodes` then statuses for `DEAD`, `LIVE` or `UNAVAILABLE` (suspect) nodes are included.
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx, line 421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N-bGc4I8gD-Q-d6WkCz:-N01PkJr52VBZ7RFd9oO:b-35qdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/154676de863db1d47dc696f00684ac4a4db14005/pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx#L421)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Why do we need to check whether the `filters` array is empty? 
</blockquote></details>

those filters describe the nodes diagnostic view when we view by node ids or by locality where as this dropdown filter is supposed to be applied to the all nodes view. This check makes sure the dropdown filter only shows up when we are on the all nodes view (aka filters aren't applied)


<!-- Sent from Reviewable.io -->

2022-04-20 08:38 UTC, koorosh approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79900)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N056csx4YuaMnHpZINh:-N056csyCGwftRjQldWG:b82oqrl) (no related file):*
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Just a small request to add one comment for more clarity. Nice!

---
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N-bI8M1AzuYcmHgTH8K:-N055mhb8ldPXM1xXmUj:b-zd9l3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/154676de863db1d47dc696f00684ac4a4db14005/pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx#L387)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Ah good catch I didn't see that comment. I've changed it such that if the selection is `Active Nodes` then statuses for `DEAD`, `LIVE` or `UNAVAILABLE` (suspect) nodes are included.
</blockquote></details>

nit. I would also leave a comment to explain such a condition.
___
*[pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx, line 421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79900#-N-bGc4I8gD-Q-d6WkCz:-N056AdZ2CoftBawNeBL:bkclf7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/154676de863db1d47dc696f00684ac4a4db14005/pkg/ui/workspaces/db-console/src/views/reports/containers/nodes/index.tsx#L421)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

those filters describe the nodes diagnostic view when we view by node ids or by locality where as this dropdown filter is supposed to be applied to the all nodes view. This check makes sure the dropdown filter only shows up when we are on the all nodes view (aka filters aren't applied)
</blockquote></details>

Ah, got it!


<!-- Sent from Reviewable.io -->

2022-04-20 18:32 UTC, Santamaura commented
@thtruo did we want to backport this?

2022-04-20 19:12 UTC, thtruo commented
@Santamaura yeah let's get this into 21.2.x and 21.1.x if possible

2022-04-21 13:56 UTC, Santamaura commented
bors r+

2022-04-21 17:01 UTC, Santamaura commented
bors retry

2022-04-21 18:51 UTC, merged