colexec: add optimized implementation of LIKE '%foo%bar%' patterns
cockroachdb/cockroach pull request #80073
Opened 2022-04-16 20:06 UTC by yuzefovich

This commit introduces optimized implementation of LIKE patterns of the
form `%foo%bar%` with any number of "skeleton" words in between. There
are two TPCH queries that use this pattern, and this commit speeds Q13
by about 2x on a single node on my laptop.

The logic for evaluating such pattern is that for each "skeleton" words
we find its first occurrence in the unprocessed part of the input
string. If it is not found, then the pattern doesn't match, if it is
found, then we advance the input string right past that first
occurrence.

Here is the comparison of the microbenchmarks of the optimized version
and the default unoptimized version on the same pattern:
```
BenchmarkLikeOps/selSkeletonBytesBytesConstOp-16       	   37070	     32054 ns/op	2044.58 MB/s
BenchmarkLikeOps/selRegexpSkeleton-16                  	    1797	    668154 ns/op	  98.09 MB/s
```

Release note: None

2022-04-16 20:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/80073)
<!-- Reviewable:end -->

2022-04-18 17:28 UTC, rharding6373 requested changes
Cool!

> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-:-N-xhy_x9QwXvJV9jqG1:b-89q77x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/colexec/colexecsel/like_ops_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N-xhcaw0wcP0JiaP4PY:-N-xhcaw0wcP0JiaP4PZ:b57z8js) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12d0443cc14d7f786d2c0632376ead6ac0bd076/pkg/sql/colexec/colexecsel/like_ops_test.go#L95)):*
> ```Go
> 		},
> 		{
> 			pattern:  "%a%e%",
> ```

Could you add a test with 3+ strings to match?


<!-- Sent from Reviewable.io -->

2022-04-18 17:37 UTC, mgartner approved these changes
Very cool!

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-:-N-xk0Dm2LCXcLe3R5gT:b-jdo7t9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @rharding6373, and @yuzefovich)

___
*[pkg/sql/colexec/colexeccmp/like_ops.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N-xiaEN7Tsx-ATVhvI8:-N-xiaEN7Tsx-ATVhvI9:b-x86dz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12d0443cc14d7f786d2c0632376ead6ac0bd076/pkg/sql/colexec/colexeccmp/like_ops.go#L81)):*
> ```Go
> 	}
> 	hasEscape := strings.Contains(pattern, `\`)
> 	if len(pattern) > 1 && !strings.ContainsAny(pattern[1:len(pattern)-1], "_%") && !hasEscape {
> ```

not related to your PR, but short-circuiting on the `!hasEscape` before the `!strings.ContainsAny` might be a minor performance boost in the the slow case, right? Maybe it's negligible compared to the regex evaluation?
___
*[pkg/sql/colexec/colexecsel/like_ops_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N-xhcaw0wcP0JiaP4PY:-N-xjkjjAi-UeeYR83X5:b-j6q9gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12d0443cc14d7f786d2c0632376ead6ac0bd076/pkg/sql/colexec/colexecsel/like_ops_test.go#L95)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you add a test with 3+ strings to match?
</blockquote></details>

Maybe a test with fewer than 5 characters too, like `%%e%`?


<!-- Sent from Reviewable.io -->

2022-04-18 17:54 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rharding6373)

___
*[pkg/sql/colexec/colexeccmp/like_ops.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N-xiaEN7Tsx-ATVhvI8:-N-xkzIPAgN3Dbg8wD0G:bit66up) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12d0443cc14d7f786d2c0632376ead6ac0bd076/pkg/sql/colexec/colexeccmp/like_ops.go#L81)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

not related to your PR, but short-circuiting on the `!hasEscape` before the `!strings.ContainsAny` might be a minor performance boost in the the slow case, right? Maybe it's negligible compared to the regex evaluation?
</blockquote></details>

I made the change for consistency with the new code, but it shouldn't really matter much because this code block is only executed once for a single LIKE expression.
___
*[pkg/sql/colexec/colexecsel/like_ops_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N-xhcaw0wcP0JiaP4PY:-N-xn7DgB5BpJcHJaiaE:brthhrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12d0443cc14d7f786d2c0632376ead6ac0bd076/pkg/sql/colexec/colexecsel/like_ops_test.go#L95)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Maybe a test with fewer than 5 characters too, like `%%e%`?
</blockquote></details>

Added another test case.

`%%e%` pattern won't be evaluated via the new "skeleton" type - it'll default to the slow regex matcher. The pattern, however, is equivalent to `%e%`. I started typing the code for the transformation here (in `GetLikeOperatorType`), but we probably should make the transformation in the optimizer. Thoughts?


<!-- Sent from Reviewable.io -->

2022-04-19 15:31 UTC, cucaroach approved these changes
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rharding6373, and @yuzefovich)

___
*[pkg/sql/colexec/colexeccmp/like_ops.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N01PXwl0ofPwwWYXFy_:-N01PXwl0ofPwwWYXFya:b-wzqg7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db73eabdc455ea8d7e3cd7ef73fc8814deca687/pkg/sql/colexec/colexeccmp/like_ops.go#L54)):*
> ```Go
> 	// the form '%foo%bar%' with any number of "skeleton words"), and the result
> 	// is negated.
> 	LikeSkeletonNegate
> ```

nit: I feel like these should go at the end


<!-- Sent from Reviewable.io -->

2022-04-19 15:41 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-:-N01TbV69GGrJ-Hi1Wfz:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @yuzefovich)

___
*[pkg/sql/colexec/colexeccmp/like_ops.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N01PXwl0ofPwwWYXFy_:-N01Tk395tyv8oVKQx5q:b-negzlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db73eabdc455ea8d7e3cd7ef73fc8814deca687/pkg/sql/colexec/colexeccmp/like_ops.go#L54)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

nit: I feel like these should go at the end
</blockquote></details>

Or put them in alphabetical order
___
*[pkg/sql/colexec/colexecsel/like_ops_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N-xhcaw0wcP0JiaP4PY:-N01TCqbCDBNttT6oPCV:bj3mt16) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12d0443cc14d7f786d2c0632376ead6ac0bd076/pkg/sql/colexec/colexecsel/like_ops_test.go#L95)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Added another test case.

`%%e%` pattern won't be evaluated via the new "skeleton" type - it'll default to the slow regex matcher. The pattern, however, is equivalent to `%e%`. I started typing the code for the transformation here (in `GetLikeOperatorType`), but we probably should make the transformation in the optimizer. Thoughts?
</blockquote></details>

I think it's worth adding Marcus's test case, since it exercises the giant conditional that determines whether to go into the new skeleton type or not, even if it ultimately does not.


<!-- Sent from Reviewable.io -->

2022-04-19 16:59 UTC, yuzefovich reviewed
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-:-N01knqX9waln90ulAol:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)

___
*[pkg/sql/colexec/colexeccmp/like_ops.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N01PXwl0ofPwwWYXFy_:-N01kYS4-vnfUP3uxum4:b-p2y7xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db73eabdc455ea8d7e3cd7ef73fc8814deca687/pkg/sql/colexec/colexeccmp/like_ops.go#L54)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Or put them in alphabetical order
</blockquote></details>

Ok, reordered.
___
*[pkg/sql/colexec/colexecsel/like_ops_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N-xhcaw0wcP0JiaP4PY:-N01jnqp4YDiFqUZk0OX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12d0443cc14d7f786d2c0632376ead6ac0bd076/pkg/sql/colexec/colexecsel/like_ops_test.go#L95)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think it's worth adding Marcus's test case, since it exercises the giant conditional that determines whether to go into the new skeleton type or not, even if it ultimately does not.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-19 18:39 UTC, merged

2022-04-19 19:12 UTC, mgartner commented
*[pkg/sql/colexec/colexecsel/like_ops_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80073#-N-xhcaw0wcP0JiaP4PY:-N02Cwgt7b9q_3IyHHRb:b-mraw0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12d0443cc14d7f786d2c0632376ead6ac0bd076/pkg/sql/colexec/colexecsel/like_ops_test.go#L95)):*
Right, I wanted the test to cover the case in the conditional where the :skull: optimization would not apply.

> I started typing the code for the transformation here (in GetLikeOperatorType), but we probably should make the transformation in the optimizer. Thoughts?
 
Agreed that this would be a nice normalization rule. I created an issue: https://github.com/cockroachdb/cockroach/issues/80192


<!-- Sent from Reviewable.io -->