storageccl: Don't disable data key rotation after restart
cockroachdb/cockroach pull request #80114
Opened 2022-04-18 17:11 UTC by itsbilal

Currently, there's a bug in encryption-at-rest FS initialization
code that unintentionally disables automaticdata key rotation unless
the store key was updated since the last start of the node.
This change fixes that.

Fixes #79066

Release note (bug fix): Address issue where automatic encryption-at-rest
data key rotation would get disabled after a node restart without
a store key rotation.

2022-04-18 17:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/80114)
<!-- Reviewable:end -->

2022-04-18 17:19 UTC, itsbilal commented on pkg/ccl/storageccl/engineccl/pebble_key_manager.go
> +				"is really dangerous. data key rotation has been disabled.", storeKeyInfo.KeyId)
Maybe this isn't the right call, and we should be enabling data key rotation in this case too. Thoughts?

2022-04-18 17:43 UTC, itsbilal commented on pkg/ccl/storageccl/engineccl/pebble_key_manager.go
> +				"is really dangerous. data key rotation has been disabled.", storeKeyInfo.KeyId)
Nevermind, this case disables EAR.

2022-04-18 17:49 UTC, nicktrav reviewed
This seems like something we should have a test for.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-:-N-xlV2q9iO1oAIgQ4J9:b-jsqcgu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @shermanCRL, and @sumeerbhola)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-N-xkmCLEIYSGSTbfNB1):*
s/automaticdata/automatic data/


<!-- Sent from Reviewable.io -->

2022-04-18 18:37 UTC, itsbilal reviewed
Test added. TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-:-N-xxiKk204zrnk7L2VJ:b7j6360)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shermanCRL and @sumeerbhola)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-N-xkmCLEIYSGSTbfNB1):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

s/automaticdata/automatic data/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-18 19:10 UTC, nicktrav approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - I'm less familiar with this code, so worth getting another set of :eyes: on this.

Thanks for digging into it!

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-:-N-y3cgu8zNZnRTSVfzQ:b-gw9l4u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @shermanCRL, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/pebble_key_manager.go, line 307 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-N-y33Nd60Te4R6qS8QU:-N-y33Nd60Te4R6qS8QV:b-vhw0s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f21182e4a95aef84bb6d22309074f607d731f79/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L307)):*
> no need to do anything

nit: the bug here was that we weren't doing anything. Worth updating the comment to indicate that even though we're not rotating the key, it's important to keep rotation enabled?


<!-- Sent from Reviewable.io -->

2022-04-18 19:16 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-:-N-y5lqXEDhK9BqFtiSc:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nicktrav, @shermanCRL, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/pebble_key_manager.go, line 307 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-N-y33Nd60Te4R6qS8QU:-N-y5myu3vwp0HtdFkqY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f21182e4a95aef84bb6d22309074f607d731f79/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L307)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> no need to do anything

nit: the bug here was that we weren't doing anything. Worth updating the comment to indicate that even though we're not rotating the key, it's important to keep rotation enabled?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-18 19:19 UTC, nicktrav reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80114)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @shermanCRL and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-04-18 19:23 UTC, jbowens approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Nice job tracking that down

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-:-N-y7FtCD1oT3JTxBLsm:b-3t26s9)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @shermanCRL and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-04-18 20:02 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80114)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @shermanCRL)

___
*[pkg/ccl/storageccl/engineccl/pebble_key_manager.go, line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-N-yFRgbC45rlCNf5xEE:-N-yFRgbC45rlCNf5xEF:b-nfln4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/40188a16d845e8245ab882397f2e46de2ded79e5/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L302)):*
> ```Go
> 	}
> 	m.mu.Lock()
> 	defer m.mu.Unlock()
> ```

Can the rotationEnabled=true be hoisted to immediately after this defer?
I think this bug existed because of an oversight that this function could return early in a non-error case. And if we add more such paths in the future we may re-introduce this bug.


<!-- Sent from Reviewable.io -->

2022-04-18 20:43 UTC, itsbilal reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-:-N-yPbViCcPaSGR5zYHC:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @jbowens, @nicktrav, @shermanCRL, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/pebble_key_manager.go, line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-N-yFRgbC45rlCNf5xEE:-N-yP_tgBgAcTXqnZWc9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40188a16d845e8245ab882397f2e46de2ded79e5/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L302)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can the rotationEnabled=true be hoisted to immediately after this defer?
I think this bug existed because of an oversight that this function could return early in a non-error case. And if we add more such paths in the future we may re-introduce this bug.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-19 16:25 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80114#-:-N01d0uj68L-UrQOZDhP:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @shermanCRL and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-04-19 16:33 UTC, itsbilal commented
TFTRs!

bors r=sumeerbhola

2022-04-19 17:46 UTC, merged