schemachanger: Implemented partially-supported `DROP INDEX`
cockroachdb/cockroach pull request #80133
Opened 2022-04-18 22:27 UTC by Xiang-Gu

This PR implements `DROP INDEX` under the new schema changer
framework. Previously, `DROP INDEX` is supported with the old schema
changer code only.

One repeating theme of questions/difficulties that arose when
implementing this PR is that the old `DROP INDEX` code heavily utilizes
the `sql` package and `*planner` methods, neither of which can be
directly used in the new schema change, so, I spent a lot of effort into
refactoring and finding the right abstraction layer to expose methods
for the new schema changer.

Fixes: #79499

Release note (sql change): This PR implements `DROP INDEX` under the
new schema changer framework. Previously, `DROP INDEX` is supported only
under the old schema changer. This is necessary since the team
has decided to gradually move to the new schema changer and hence we
need to implement all DDL statement under the new schema changer. Such
a change should be transparent for end-user though.

2022-04-18 22:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/80133)
<!-- Reviewable:end -->

2022-04-20 13:28 UTC, ajwerner reviewed
Good start. I suspect we're going to want to tighten and better extract the resolution logic.

2022-04-20 13:28 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/dependencies.go
> +	CatalogReader
Why are you extending this interface as opposed to using the accessor to it below? I think we need to pick one.

2022-04-20 13:28 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/builder_state.go
> +	resolvedTablePrefix := b.cr.MayResolveObjectNamePrefix(ctx, tableName.ObjectNamePrefix)
This part seems suspicious. How can this be expected to work if the table name is empty?

2022-04-20 13:28 UTC, ajwerner commented on pkg/sql/schemachanger/scdeps/build_deps.go
> +	panic("There is not a single valid schema in search path.")
You need to panic errors in this layer. Non-errors will be turned into assertion failures.

2022-04-20 13:28 UTC, ajwerner commented on pkg/sql/schemachanger/scdeps/build_deps.go
> +func (d *buildDeps) currentSchema(ctx context.Context) string {
I don't think this concept really exists.

2022-04-20 13:28 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go
> +	ReadDescriptorByID(ctx context.Context, id descpb.ID) catalog.Descriptor
What is this used for?

2022-04-20 23:40 UTC, chengxiong-ruan commented
*[pkg/sql/schemachanger/scpb/elements.proto, line 199 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N08KgsBDFcn0aO61WXV:-N08KgsBDFcn0aO61WXW:b-w90vq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fe5cf27d41204517513894a0b3d7263742e220b/pkg/sql/schemachanger/scpb/elements.proto#L199)):*
> ```protobuf
>   bool is_inverted = 11;
>   cockroach.sql.catalog.catpb.ShardedDescriptor sharding = 12;
>   bool is_created_explicitly = 13;
> ```

mentioned in #80256, but also commenting it here that you need to set this field in `decomp.go` during `walkIndex`. but you may just rebase after #80256 is approved and merge.


<!-- Sent from Reviewable.io -->

2022-04-24 22:31 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 434 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N0ScRZr-R5MAh60Jjtg:-N0ScRZs6a3yP4Z5aCB-:b-atx2ad) ([raw file](https://github.com/cockroachdb/cockroach/blob/0258410f3141879fc16ce3916c24fa97639ce818/pkg/sql/schemachanger/scbuild/builder_state.go#L434)):*
> ```Go
> 		}
> 
> 		if tableDesc.IsVirtualTable() {
> ```

I don't think we want to put this [duplicate logic](https://github.com/cockroachdb/cockroach/blob/a3c0709b7c25c3e4cf4f33658a69091c3f32fdaf/pkg/sql/schemachanger/scbuild/builder_state.go#L559-L559) here. if a table name is provided from parser, we may just resolve table elements directly with what's currently supported already, this new path may just handle when only index name and object prefix is provided. Checking table name is empty or not should be something done at outer layer (of course we may add some helper so this logic can be reused).

I just realized we might be doing some repetitive work here so I sneaked in here :)  [here is my solution](https://github.com/cockroachdb/cockroach/pull/80459/files#diff-fd6e2f6a5cf3097b2810802a74ffba22203de90b2b133ec46c689c83d997a074R139) which I think should be more clean and simpler. (still a draft which is split out from another partially reviewed bigger pr and I still need to rebase after another pr is merged)
___
*[`pkg/sql/schemachanger/scdeps/build_deps.go` line 201 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N0Sg-qdE1rCpgbLIMJd:-N0Sg-qe9HdPEE6YSJ8f:b-qn8uyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0258410f3141879fc16ce3916c24fa97639ce818/pkg/sql/schemachanger/scdeps/build_deps.go#L201)):*
> ```Go
> 		prefix.SchemaName = tree.Name(d.currentSchema(ctx))
> 	} else {
> 		if !prefix.ExplicitCatalog {
> ```

I don't think this would work for cases like `db_name.index_name` where `db_name` is not current database. you might want to take a look at my solution as well, all I did is just call `resolver.ResolveObjectNamePrefix` which I think is the correct way to achieve both cases of `db_name.index_name` and `schema_name.index_name`. All that being said, I don't think we want to have this logic in new schema changer, but should keep it in resolver.


<!-- Sent from Reviewable.io -->

2022-04-25 20:05 UTC, Xiang-Gu reviewed
I've substantially updated this PR in two main ways:
    1. In the top-level `drop_index.go` file, we only play with elements. No descriptor is ever used in this level.

    2. As a consequence, I need to add a few fields to the various elements to facilitate some of the logic. Most notably, I added a repeated field in the `View` element that tracks all forward references to the index level (Previously, all we know about forward-references in a `View` is what are the descriptors IDs that this view depends on). With this, we can check whether a view depends on a particular index of a table.

    3. Get rid of a lot of business logic and try to reuse logic in resolver whenever possible. In the same direction of effort, I've consulted @chengxiong-ruan pr about `DROP COMMENT` and reused his helpers whenever possible since we both need to do highly similar things in both of our PRs.

    4. Existing tests: some tests are old but still we managed to modify them to accommodate both the old and new schema changer. There are a few ones that are not easy to fix so I skipped them (by turning off the new schema changer around the `drop index` statement) bc the difference is not important to us (e.g. `finish schema change` event is logged in the old schema changer but it's not present in the new schema changer).

Ready to take a look again!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N0XDW-96xk6N_AThmnJ:b-cgmwfb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 434 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N0ScRZr-R5MAh60Jjtg:-N0X2yZ0BfZVbNzUl_M3:bbikjtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0258410f3141879fc16ce3916c24fa97639ce818/pkg/sql/schemachanger/scbuild/builder_state.go#L434)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I don't think we want to put this [duplicate logic](https://github.com/cockroachdb/cockroach/blob/a3c0709b7c25c3e4cf4f33658a69091c3f32fdaf/pkg/sql/schemachanger/scbuild/builder_state.go#L559-L559) here. if a table name is provided from parser, we may just resolve table elements directly with what's currently supported already, this new path may just handle when only index name and object prefix is provided. Checking table name is empty or not should be something done at outer layer (of course we may add some helper so this logic can be reused).

I just realized we might be doing some repetitive work here so I sneaked in here :)  [here is my solution](https://github.com/cockroachdb/cockroach/pull/80459/files#diff-fd6e2f6a5cf3097b2810802a74ffba22203de90b2b133ec46c689c83d997a074R139) which I think should be more clean and simpler. (still a draft which is split out from another partially reviewed bigger pr and I still need to rebase after another pr is merged)
</blockquote></details>

Yeah, I recognized that we have very similar (almost identical) methods added in our PRs. I've changed mine to use your method signature. Also, you're right that I just need to handle the new case where table name is not specified, in which case I called your `ResolveIndex` method. 

The only thing I added to help with my `DROP INDEX` is that I added a `requireTable` input argument to the helper method `FindTableContainsIndex` such that I can call it with `requireTable=false` and in the caller check whether returned tableDesc is nil or not. If it's nil and `IF EXISTS` is set, I can just skip and don't need to panic.


<!-- Sent from Reviewable.io -->

2022-04-28 13:51 UTC, Xiang-Gu reviewed
I think it's easier to not turn `DROP INDEX` first on because it means we will need to fix a ton of tests. I will turn it off for now and let reviewers review the important changes first. Then, in a separate pr, turn on `DROP INDEX` which means fixes all the affected tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N0b7Hjk6JINBS1vsKZ-:bu6vzm1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprj-r1-405:-N0b5bu2AthfQtl8k7N2:b-11x42p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ce019445418ccdc8b1d3c6397ac8514d01951/pkg/sql/schemachanger/scbuild/builder_state.go#L405)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This part seems suspicious. How can this be expected to work if the table name is empty?
</blockquote></details>

ack. The new revision deletes this altogether.
___
*[`pkg/sql/schemachanger/scbuild/dependencies.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprk-r1-33:-N0b6Ckp0_TIKNx14Ucm:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ce019445418ccdc8b1d3c6397ac8514d01951/pkg/sql/schemachanger/scbuild/dependencies.go#L33)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Why are you extending this interface as opposed to using the accessor to it below? I think we need to pick one. 
</blockquote></details>

ack
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprm-r1-204:-N0gK0Cw1AbhmFBJfB5M:b-eatnox) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ce019445418ccdc8b1d3c6397ac8514d01951/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L204)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What is this used for?
</blockquote></details>

I'm not sure. I think @postamar added this?
___
*[`pkg/sql/schemachanger/scdeps/build_deps.go` line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprq-r1-385:-N0b6V829xblMqdYSSmV:b-28t3bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ce019445418ccdc8b1d3c6397ac8514d01951/pkg/sql/schemachanger/scdeps/build_deps.go#L385)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think this concept really exists. 
</blockquote></details>

the new revision deleted it.
___
*[`pkg/sql/schemachanger/scdeps/build_deps.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprq-r1-396:-N0b6Yp0B1k6IV-ACSJf:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ce019445418ccdc8b1d3c6397ac8514d01951/pkg/sql/schemachanger/scdeps/build_deps.go#L396)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

You need to panic errors in this layer. Non-errors will be turned into assertion failures. 
</blockquote></details>

ack
___
*[`pkg/sql/schemachanger/scdeps/build_deps.go` line 201 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N0Sg-qdE1rCpgbLIMJd:-N0b6TrODKaMOeXdTqQf:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0258410f3141879fc16ce3916c24fa97639ce818/pkg/sql/schemachanger/scdeps/build_deps.go#L201)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I don't think this would work for cases like `db_name.index_name` where `db_name` is not current database. you might want to take a look at my solution as well, all I did is just call `resolver.ResolveObjectNamePrefix` which I think is the correct way to achieve both cases of `db_name.index_name` and `schema_name.index_name`. All that being said, I don't think we want to have this logic in new schema changer, but should keep it in resolver.
</blockquote></details>

ack
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 199 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N08KgsBDFcn0aO61WXV:-N0b6ZtoB_flbTx7V4Em:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fe5cf27d41204517513894a0b3d7263742e220b/pkg/sql/schemachanger/scpb/elements.proto#L199)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

mentioned in #80256, but also commenting it here that you need to set this field in `decomp.go` during `walkIndex`. but you may just rebase after #80256 is approved and merge.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-05-03 12:51 UTC, ajwerner reviewed
I've not forgotten about this, I think it's waiting on work that @chengxiong-ruan is doing now to refactor out some relevant catalog pieces. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N18yLjAAIFxZVPFcP60:b-vmu71a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)



<!-- Sent from Reviewable.io -->

2022-05-16 18:44 UTC, Xiang-Gu reviewed
I've rebased Chengxiong's recent change and it's RFAL.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N2DAZZyCOY_zpOPKrpF:b1mu3k2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)



<!-- Sent from Reviewable.io -->

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go
> +	ResolveTableIndexBestEffort(tableIndexName *tree.TableIndexName, p ResolveParams) ElementResultSet
How about `MaybeResolveTableIndex`?

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go
> +	//ResolveIndexByName(index *tree.TableIndexName, p ResolveParams) ElementResultSet
leftover comment

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +			panic("cannot find secondary index after resolve. Check resolve logic!")
I think it's probably better to do:

```
panic(errors.AssertionFailedf("programming error: cannot find secondary index for ... after having resolved it", ...))
```
and then put in some more information about the table and index etc. Same for the below errors.

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +func mayDropDependentViews(
personally I find `maybe` to sound better than `may` when writing logic which is going to check some condition and then either fail or do a thing.
----
Aside: I do like this pattern, for what it's worth. When I first started programming, it smelled to me. I would think to myself, shouldn't the condition checking happen above calling the function which does a thing? Having conditional logic in multi-step functions however, can muddle the readability, especially when the condition checking is cumbersome.

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +				if dropBehavior != tree.DropCascade {
nit: I generally think it's better to invert the condition, especially when things are already getting quite nested. 
```go
if forwardRef.IndexID != sie.IndexID {
    continue
}
if dropBehavior != tree.DropCascade {
    // Get view name for error message
	_, _, ns := scpb.FindNamespace(b.QueryByID(ve.ViewID))
        // ...
}
dropCascadeDescriptor(b, ve.ViewID)
```

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +					// Get view name for panic message
I think it's cleaner to just say `for the error message`. The fact that the error is panicked internally in this layer is an implementation detail.

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +		panic("invalid toBeDroppedSecondaryIndexElms; does not contain a secondary index element.")
make this an error, and if it's not an assertion failure, then properly classify it.

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +		func(current scpb.Status, target scpb.TargetStatus, e *scpb.ForeignKeyConstraint) {
you can lose a layer of indentation if you wrap it:

```go 
	scpb.ForEachForeignKeyConstraint(b.BackReferences(sie.TableID), func(
		current scpb.Status, target scpb.TargetStatus, e *scpb.ForeignKeyConstraint,
	) {
```

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +				// a replacement candidate to serve this dependent FK is not found;
nit: sentence

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +	if !anyIndexUsesColOtherThan(b, sie.TableID, sce.ColumnID, sie.IndexID) {
invert this condition

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +			func(current scpb.Status, target scpb.TargetStatus, e *scpb.CheckConstraint) {
same wrapping trick

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +					if colID == sce.ColumnID {
invert this condition

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +					}
I don't think you need this return, do you?

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +							b.Drop(e)
you can lose a line if you invert this condition

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +			b.Drop(e)
you can lose a line if you invert this condition

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +) bool {
I'd name this return value

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
> +	used := false
consider: 

```go
hasColID := func(ids []descpb.ColumnID) bool {
    for _, id := range ids {
        if id == colID {
            return true
        }
    }
    return false
}
var used bool
scpb.ForEachPrimaryIndex(b.QueryByID(relationID), func(
    _ scpb.Status, _ scpb.TargetStatus, e *scpb.PrimaryIndex,
) {
    used = used || (e.IndexID != indexID && hasColID(e.KeyColumnIDs))
})
if used {
    return used
}
scpb.ForEachSecondaryIndex(b.QueryByID(relationID), func(
   _ scpb.Status, _ scpb.TargetStatus, e *scpb.SecondaryIndex,
) {
    used = used || (e.IndexID != indexID && 
        (hasColID(e.KeyColumnIDs) ||
             hasColID(e.KeySuffixColumnIDs) ||
             hasColID(e.StoringColumnIDs)))
}
```

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scdeps/helper.go
> +func FindTableContainsIndex(
nit: `Containing`

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scdeps/helper.go
> +func FindTableContainsIndex(
is this still needed?

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scpb/elements.proto
> +    (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sem/catid.ColumnID"];
nit: title these as though they were go comments, i.e. PascalCase with the field name as it will be.

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scpb/elements.proto
> +  uint32 fromID = 1 [
name this `view_id`?

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scpb/elements.proto
> +message Reference {
while this remains used only for views, can we just call it `ViewReference`?

2022-05-17 02:54 UTC, ajwerner commented on pkg/sql/schemachanger/scpb/elements.proto
> +  uint32 toID = 2 [
these should be `snake_case`

2022-05-17 18:26 UTC, Xiang-Gu reviewed
Thanks for your prompt review. Here are my responses.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N2IGK601LBWnQsrK3-E:beemlrq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 270 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprm-r7-270:-N2HfA2fCMdqG2r7NkUY:b-jaa7vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L270)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How about `MaybeResolveTableIndex`?
</blockquote></details>

This is from Chengxiong's merge. Actually, this method's behavior is no different from the rest in that it attempts to resolve something; If that something is not found, then we either panic or return nil depending on `p.IsExistenceOptional`.

So, I propose that we just name it `ResolveIndexByName`?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 272 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprm-r7-272:-N2HfVoE2zOac-GrI9Ys:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L272)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

leftover comment
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 64 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-64:-N2Hgejd4ax_d2axQoGr:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L64)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think it's probably better to do:

```
panic(errors.AssertionFailedf("programming error: cannot find secondary index for ... after having resolved it", ...))
```
and then put in some more information about the table and index etc. Same for the below errors. 
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 214 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-214:-N2HhDH83yLpl6lOHyUk:b-u1ul7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L214)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

personally I find `maybe` to sound better than `may` when writing logic which is going to check some condition and then either fail or do a thing.
----
Aside: I do like this pattern, for what it's worth. When I first started programming, it smelled to me. I would think to myself, shouldn't the condition checking happen above calling the function which does a thing? Having conditional logic in multi-step functions however, can muddle the readability, especially when the condition checking is cumbersome.
</blockquote></details>

agreed, I used it because it makes caller logic more readable. In this case, what I want is that when people read `func DropIndex`, it is clear that we are just doing
```
func DropIndex(...) {
do_A                   // for all index, we need to do A first
do_B                   // for all index, we need to do B second
maybe_do_C      // for some (but not all) index we need to do C
maybe_do_D     // for some (but not all) index we need to do D
done!
}
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 227 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-227:-N2I2jP0EMgqmN7xtn-g:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L227)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: I generally think it's better to invert the condition, especially when things are already getting quite nested. 
```go
if forwardRef.IndexID != sie.IndexID {
    continue
}
if dropBehavior != tree.DropCascade {
    // Get view name for error message
	_, _, ns := scpb.FindNamespace(b.QueryByID(ve.ViewID))
        // ...
}
dropCascadeDescriptor(b, ve.ViewID)
```
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 228 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-228:-N2I2qWE44XntWb8AcHJ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L228)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think it's cleaner to just say `for the error message`. The fact that the error is panicked internally in this layer is an implementation detail. 
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 255 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-255:-N2I3dR-AIZ3-pwVjnNm:b4k7j3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L255)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

make this an error, and if it's not an assertion failure, then properly classify it. 
</blockquote></details>

done. I've made it an assertion error



_Code quote:_
```Go
if sie == nil || sine == nil 
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 259 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-259:-N2I3w1TA3muGtp-tJki:b3bt5wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L259)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you can lose a layer of indentation if you wrap it:

```go 
	scpb.ForEachForeignKeyConstraint(b.BackReferences(sie.TableID), func(
		current scpb.Status, target scpb.TargetStatus, e *scpb.ForeignKeyConstraint,
	) {
```
</blockquote></details>

I didn't understand this one. Why do we prefer writing this way compared to my original version?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 262 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-262:-N2I4XZEDgYp9lhzVgP0:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L262)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: sentence
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 318 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-318:-N2I59kRB42HYbMnZLyo:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L318)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

invert this condition
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 322 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-322:-N2I5gor1NN-NTN246O9:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8 [...]

2022-05-17 18:58 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, @postamar, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 289 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprr-r7-289:-N2IN8whAcpEPFEkXpo8:bgq473a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scpb/elements.proto#L289)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

I want this message to model any directional reference between two relations and hence the name. It's true that it's now only used for reference from a view to a relation, but it could be used for other references in the future, so I'm inclined to keep those names (including the `from_id` field and `to_id` field)
</blockquote></details>

I'm inclined to disagree. It's tempting to want to generalize, but in my experience, it's a bad idea. Extra elements provide flexibility at the cost of some extra code. The good news is that if indeed there are two elements which are the same, then they can reuse library code in their implementations. I'd rather a little bit of copying than a little bit of an over-generalized data model. Can you think of specific places where you'd want to use it? 


<!-- Sent from Reviewable.io -->

2022-05-17 19:00 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, @postamar, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 289 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprr-r7-289:-N2IO5TTDlYc707GQojl:b-1n1arq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scpb/elements.proto#L289)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm inclined to disagree. It's tempting to want to generalize, but in my experience, it's a bad idea. Extra elements provide flexibility at the cost of some extra code. The good news is that if indeed there are two elements which are the same, then they can reuse library code in their implementations. I'd rather a little bit of copying than a little bit of an over-generalized data model. Can you think of specific places where you'd want to use it? 
</blockquote></details>

I could see making this an element on its own. There's arguments against that too. I'm slightly less wedded to that. 


<!-- Sent from Reviewable.io -->

2022-05-17 20:48 UTC, Xiang-Gu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 289 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprr-r7-289:-N2IlXO67jtgNuxEWtRR:bltv051) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scpb/elements.proto#L289)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I could see making this an element on its own. There's arguments against that too. I'm slightly less wedded to that. 
</blockquote></details>

If we make it `ViewReference`, then does it make sense to also define this message within the `View` message since we expect `View` to be the only user of this message?


<!-- Sent from Reviewable.io -->

2022-05-17 20:52 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, @postamar, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 289 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprr-r7-289:-N2ImevK1YCHUnqebz6X:bhdmffu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scpb/elements.proto#L289)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

If we make it `ViewReference`, then does it make sense to also define this message within the `View` message since we expect `View` to be the only user of this message?
</blockquote></details>

Yes, it makes sense to move the message definition into View 


<!-- Sent from Reviewable.io -->

2022-05-17 20:53 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, @postamar, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 289 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprr-r7-289:-N2Imo2T353bfzFIAV9m:b-2tz4lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scpb/elements.proto#L289)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yes, it makes sense to move the message definition into View 
</blockquote></details>

Also, at that point, remove the from_id altogether as it’s implicit give the containing View element. 


<!-- Sent from Reviewable.io -->

2022-05-18 18:33 UTC, Xiang-Gu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 289 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprr-r7-289:-N2NRaCBCSqAIjVDANvd:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scpb/elements.proto#L289)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Also, at that point, remove the from_id altogether as it’s implicit give the containing View element. 
</blockquote></details>

done!


<!-- Sent from Reviewable.io -->

2022-05-26 14:30 UTC, ajwerner reviewed
please add some new data driven tests to cover various drop index scenarios and to cover the new pieces of the decomposition you added. 

> Reviewed 1 of 10 files at r1, 2 of 17 files at r3, 2 of 17 files at r4, 2 of 10 files at r5, 3 of 24 files at r6, 10 of 29 files at r7, 5 of 18 files at r8, 4 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N3-l_kP2PrIE2OlMVXM:b-rzd1gd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 706 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-e1ky1BWLrxZ-vE_N:-N3-e1kzD6LlUmqT9kBD:b-oomuul) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scbuild/builder_state.go#L706)):*
> ```Go
> }
> 
> //func (b *builderState) ResolveIndexByName(
> ```

please remove this commented out logic
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 259 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-259:-N3-i5yc8PpRfQCeDutE:bjv11h0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L259)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

I didn't understand this one. Why do we prefer writing this way compared to my original version?
</blockquote></details>

I just like having one fewer tabs in the code
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 336 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-336:-N3-iJ1L-MISL_kVgnIs:b-runnfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L336)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

we know that once we found a check constraint that uses this to-be-dropped index, we marks its elements as dropped and we can return early without iterating over the remaining columns this check constraint uses. That's why I put a return here
</blockquote></details>

how about:

```go
if !descpb.ColumnIDs(e.ColumnIDs).Contains(sce.ColumnID) {
    return
}
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 396 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-396:-N3-jW98E9GSy-nyLxvV:b6alv8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L396)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

Done. Thanks a lot.
</blockquote></details>

I remembered now we have the `descpb.ColumnIDs.Contains` method.

you can do: 
```go
hasColID := func(ids []descpb.ColumnID) bool {
    return descpb.ColumnIDs(ids).Contains(colID)
}
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 39 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-hlQHEf1Fy0Z9PpZ1:-N3-hlQI2JTuJeniLDFa:b9clfzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L39)):*
> ```Go
> 
> 	for _, index := range n.IndexList {
> 		toBeDroppedIndexElms := b.ResolveIndexByName(index, ResolveParams{
> ```

nit: should we factor the body of this loop out?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 371 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-jJnC8cXcs1qQjWd5:-N3-jJnC8cXcs1qQjWd6:b-uxtjnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L371)):*
> ```Go
> 
> 	scpb.ForEachColumn(b.QueryByID(sie.TableID), func(current scpb.Status, target scpb.TargetStatus, ce *scpb.Column) {
> 		columnInIndexKeyCols := false
> ```

I think you can use https://github.com/cockroachdb/cockroach/blob/cc6aa337dc3c327b512b283ce9842afc942a244d/pkg/sql/catalog/descpb/structured.go#L177-L178 here
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 379 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-jOgY1Gid5Il0Eb8s:-N3-jOgY1Gid5Il0Eb8t:brh5mlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L379)):*
> ```Go
> 		}
> 
> 		if columnInIndexKeyCols && ce.IsInaccessible && ce.IsVirtual {
> ```

nit: invert this?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 64 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-jmID16PKs5hGBIsP:-N3-jmID16PKs5hGBIsQ:b-v3d5uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L64)):*
> ```Go
> 	reflect.TypeOf((*tree.CommentOnIndex)(nil)):      {CommentOnIndex, false},
> 	reflect.TypeOf((*tree.CommentOnConstraint)(nil)): {CommentOnConstraint, false},
> 	// TODO (Xiang): turn on `DROP INDEX` with version gating after 22.1 release.
> ```

should we try it? I want to see what tests break
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 208 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-l27qDlTr_EwZ0iEa:-N3-l27qDlTr_EwZ0iEb:b-mchm1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scpb/elements.proto#L208)):*
> ```protobuf
>   // can be used to uniquely identify a constraint.
>   uint32 constraint_id = 14 [(gogoproto.customname) = "ConstraintID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sem/catid.ConstraintID"];
>   bool is_partial = 15;
> ```

do we need this?
___
*[`pkg/sql/schemachanger/scplan/internal/scstage/stage.go` line 120 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-lL9b37jdaz_cIF-I:-N3-lL9c-jTfN_v9bSfr:b73100p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scplan/internal/scstage/stage.go#L120)):*
> ```Go
> 				stage.String(), currentPhase)
> 		}
> 		currentPhase = stage.Phase
> ```

:/ this seems like a legitimate bug, sad we had nothing to catch it. 


<!-- Sent from Reviewable.io -->

2022-06-02 18:41 UTC, Xiang-Gu reviewed
I re-organized the code structure a bit and added some data-driven tests (for `scbuild`, `scplan`, `scdecomp`, and `end_to_end`) for `DROP INDEX` that covers various drop-index scenarios (drop a "vanilla" index, drop an index with dependent view/FKs, drop a hash-shard index, and drop a partial, expression index).

RFAL again

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N3_hWKD6XKeabuO4_Mb:b-8rwka2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 706 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-e1ky1BWLrxZ-vE_N:-N3VT4Dm0982f1uvpGnX:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scbuild/builder_state.go#L706)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

please remove this commented out logic
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 259 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-259:-N3VUxwBDyMoC6Gpqn9E:b-yhi4az) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L259)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I just like having one fewer tabs in the code
</blockquote></details>

Got it. I also saw this pattern in many other places in the codebase.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 336 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-336:-N3VWQcRDYKbQ5F-_gyo:bfac5yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L336)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

how about:

```go
if !descpb.ColumnIDs(e.ColumnIDs).Contains(sce.ColumnID) {
    return
}
```
</blockquote></details>

Aww, this `Contains` is very handy. Thank you!
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 396 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprn-r7-396:-N3VbcvuCuypP8g9VA-_:b-nfv2ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d377173f8f944b7c28c9046597462d439825a8e/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L396)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I remembered now we have the `descpb.ColumnIDs.Contains` method.

you can do: 
```go
hasColID := func(ids []descpb.ColumnID) bool {
    return descpb.ColumnIDs(ids).Contains(colID)
}
```
</blockquote></details>

yup, done!
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 39 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-hlQHEf1Fy0Z9PpZ1:-N3VUtjgD_7JMnMquwQ4:b-bztpbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L39)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: should we factor the body of this loop out?
</blockquote></details>

yes, it will make the code a bit cleaner. Done



_Code quote:_
```Go
for _, index := range n.IndexList {
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 371 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-jJnC8cXcs1qQjWd5:-N3VZD-Z1qdtU-7_kjmm:b-wk6d6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L371)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think you can use https://github.com/cockroachdb/cockroach/blob/cc6aa337dc3c327b512b283ce9842afc942a244d/pkg/sql/catalog/descpb/structured.go#L177-L178 here
</blockquote></details>

yeah, similarily to above, we can exit early if this column (`ce.ColumnID`) is not contained in the to-be-dropped index's key columns. Done.



_Code quote:_
```Go
dropAdditionallyForExpressionInde
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go` line 379 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-jOgY1Gid5Il0Eb8s:-N3VadGxBnXUeJPHIqac:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go#L379)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: invert this?
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 64 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-jmID16PKs5hGBIsP:-N3Vbg6-CpQB8VoByRIN:bod4cwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L64)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should we try it? I want to see what tests break
</blockquote></details>

I've tried it actually; most of the failed tests are about minor/insignificant behavior differences between the legacy and declarative schema changer (e.g. log events, schema change job names).

My plan is to get approval on the general logic of `DROP INDEX` first, and then have another PR that enables it (which I expect to mostly about fixing broken tests)
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 208 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-l27qDlTr_EwZ0iEa:-N3VgAYw9Xve-jT3ZS4c:bcexe5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scpb/elements.proto#L208)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

do we need this?
</blockquote></details>

It's used in (only) one place:

```
func isValidReferencedUniqueConstraint(
	b BuildCtx, ie *scpb.Index, referencedColIDs []tree.ColumnID,
) bool {
	return ie.IsUnique && !ie.IsPartial &&
		explicitColumnIDsWithoutShardColumn(b, ie).PermutationOf(referencedColIDs)
}
```

which is a helper function to determine whether a particular index `ie` (in some particular table `t`) can serve as some foreign key constraint that references `referencedColIDs` (of table `t`). 

A few helper functions in this file (including this one) are copied from existing methods on `index` (or `indexDescriptor` or alike).
___
*[`pkg/sql/schemachanger/scplan/internal/scstage/stage.go` line 120 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-lL9b37jdaz_cIF-I:-N3ViWFXASnRBxmnClQq:b-4j366p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scplan/internal/scstage/stage.go#L120)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

:/ this seems like a legitimate bug, sad we had nothing to catch it. 
</blockquote></details>

agreed. 


<!-- Sent from Reviewable.io -->

2022-06-08 16:59 UTC, ajwerner approved these changes
Can you help me understand why the number of roundtrips in the rttanalysis benchmark went down? Also you'll need a regeneration. 

I think this <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>. We can iron out any fallout when we go to flip it on. 

> Reviewed 21 of 40 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N43EyGM2GIz2Q_wrSeE:bns4h8d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 208 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-l27qDlTr_EwZ0iEa:-N43EJC-3YuNmvzUiSsm:brm4unz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scpb/elements.proto#L208)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

It's used in (only) one place:

```
func isValidReferencedUniqueConstraint(
	b BuildCtx, ie *scpb.Index, referencedColIDs []tree.ColumnID,
) bool {
	return ie.IsUnique && !ie.IsPartial &&
		explicitColumnIDsWithoutShardColumn(b, ie).PermutationOf(referencedColIDs)
}
```

which is a helper function to determine whether a particular index `ie` (in some particular table `t`) can serve as some foreign key constraint that references `referencedColIDs` (of table `t`). 

A few helper functions in this file (including this one) are copied from existing methods on `index` (or `indexDescriptor` or alike).


</blockquote></details>

That makes sense. Any interest in adding some commentary?


<!-- Sent from Reviewable.io -->

2022-06-09 13:59 UTC, postamar requested changes
This is close. The major issue I have is the addition of `is_virtual` and `is_partial` in the element model which AFAIK are redundant.

> Reviewed 1 of 10 files at r1, 3 of 17 files at r3, 1 of 24 files at r6, 3 of 29 files at r7, 2 of 18 files at r8, 29 of 40 files at r10, 12 of 12 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N47k2dxBTu9K7nqL-p3:b-ux3j65)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @chengxiong-ruan, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N-ymTC7F-0y9KfWXprm-r1-204:-N47jS4-2Y7EDWioP0bs:b3ialvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f72ce019445418ccdc8b1d3c6397ac8514d01951/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L204)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

I'm not sure. I think @postamar added this?
</blockquote></details>

IIRC this encapsulates logic in which depends on descriptors.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 298 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47ik2k7m9-vjwuTAOF:-N47ik2k7m9-vjwuTAOG:bl834sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L298)):*
> ```Go
> 
> 	// ResolveConstraintByID retrieves a constraint by name and returns its elements.
> 	ResolveConstraintByID(relationID catid.DescID, constraintID descpb.ConstraintID, p ResolveParams) ElementResultSet
> ```

`Resolve*` methods map names to IDs and these two don't fall into that pattern. Also, and more importantly, they don't involve dependencies directly. We like to keep these interfaces quite tight. Can you refactor the methods as helper functions in `helpers.go` instead, please? 
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 64 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47icyv0Eo1HlDWStHy:-N47icyw7HnV1VTBQ7Er:b-1jhf0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L64)):*
> ```Go
> 	reflect.TypeOf((*tree.CommentOnConstraint)(nil)): {CommentOnConstraint, true},
> 	// TODO (Xiang): turn on `DROP INDEX` with version gating after 22.1 release.
> 	reflect.TypeOf((*tree.DropIndex)(nil)): {DropIndex, false},
> ```

You can act on this now, 22.1 is out.
___
*[`pkg/sql/schemachanger/scdecomp/decomp.go` line 220 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47hSFP0ysL6vhUhNZg:-N47hSFP0ysL6vhUhNZh:b-v39sfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scdecomp/decomp.go#L220)):*
> ```Go
> 								ToID:      toID,
> 								IndexID:   dep.IndexID,
> 								ColumnIDs: dep.ColumnIDs,
> ```

From experience, I can tell you it's best to not assume that the `dep.ColumnIDs` slice is well-formed (no zeroes, no duplicate elements) or safe to shallow-copy. I suggest you dump its non-zero contents into a `catalog.TableColSet` and assign `ColumnIDs` to the result of `.Ordered()`.
___
*[`pkg/sql/schemachanger/scdecomp/decomp.go` line 226 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47iBJY0eiCv2grocYm:-N47iBJY0eiCv2grocYn:b7qvkt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scdecomp/decomp.go#L226)):*
> ```Go
> 					}); err != nil {
> 						panic(err)
> 					}
> ```

nit: since your anonymous function never returns any errors you could simply have `_ = toDesc.Foreach...` instead of an if-panic.
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 144 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47e2FT5Ku4k8vmfmNK:-N47e2FT5Ku4k8vmfmNL:b-5k6f2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scpb/elements.proto#L144)):*
> ```protobuf
>   uint32 pg_attribute_num = 7 [(gogoproto.customname) = "PgAttributeNum", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sem/catid.PGAttributeNum"];
>   bool is_system_column = 8;
>   bool is_virtual = 9;
> ```

This information is already present in `ColumnType`.
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 209 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47e6ph89WI-zcZxS80:-N47e6ph89WI-zcZxS81:b-srackv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scpb/elements.proto#L209)):*
> ```protobuf
>   // can be used to uniquely identify a constraint.
>   uint32 constraint_id = 14 [(gogoproto.customname) = "ConstraintID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sem/catid.ConstraintID"];
>   bool is_partial = 15;
> ```

This information can be inferred from the existence or not of a `SecondaryIndexPartial` joining on `(table_id, index_id)`.
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 297 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47eYWVEEfnhJTwqO4u:-N47eYWVEEfnhJTwqO4v:b-nmsu95) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scpb/elements.proto#L297)):*
> ```protobuf
>   message Reference {
>     option (gogoproto.equal) = true;
>     uint32 to_id = 1 [
> ```

`s/to_id/relation_id/`?
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 308 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47ejT38OSQf-DJ2Wi_:-N47ejT38OSQf-DJ2Wia:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scpb/elements.proto#L308)):*
> ```protobuf
>   // all forward reference from this view -- it gives more details of those references than just
>   // referenced relation ids (which is stored in `uses_relation_ids`).
>   repeated Reference forward_references = 4 [(gogoproto.customname) = "ForwardReferences"];
> ```

Nice.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_name.go` line 42 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47fNln9Qf9tyZeXYOx:-N47fNloCdPBzMEX7OPI:b-s4oxlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_name.go#L42)):*
> ```Go
> 						TableID: this.TableID,
> 						IndexID: this.IndexID,
> 						Name:    this.Name,
> ```

Is there a reason for this? The original idea was to express the element removal by zero-ing the name field. An empty string would be invalid, in addition to being opaque, so we instead use a placeholder string instead.
___
*[`pkg/sql/schemachanger/scplan/internal/scstage/stage.go` line 120 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-lL9b37jdaz_cIF-I:-N47g5yU1ZlP6pA-R8T-:b-oxgb06) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scplan/internal/scstage/stage.go#L120)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

agreed. 
</blockquote></details>

Good find!
___
*[`pkg/sql/schemachanger/scrun/scrun.go` line 136 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47gBk-Bg6N2v_z21oW:-N47gBk-Bg6N2v_z21oX:by6fkfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scrun/scrun.go#L136)):*
> ```Go
> 		}
> 	}
> ```

nit: newline


<!-- Sent from Reviewable.io -->

2022-06-10 20:21 UTC, Xiang-Gu reviewed
@postamar Thanks for your feedback. I've removed `is_virtual` and `is_partial` in the latest revision. 

Another issue I discovered and fixed is that I also need to use your `isRelationBeingDropped` to avoid some very constraining dep rules. To do this, I replaced all `b.Drop(e)` with `dropElement(b, e)`. 

The rest of the change is just reorganizing texts.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N4EG3n_3l_2GXYBfMRR:bq8jqay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @chengxiong-ruan, @postamar, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 298 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47ik2k7m9-vjwuTAOF:-N49-dnH8vx1dCDCWd5b:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L298)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

`Resolve*` methods map names to IDs and these two don't fall into that pattern. Also, and more importantly, they don't involve dependencies directly. We like to keep these interfaces quite tight. Can you refactor the methods as helper functions in `helpers.go` instead, please? 
</blockquote></details>

Done!
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 64 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47icyv0Eo1HlDWStHy:-N49-v75Eq0m8hTzhCmI:b1d791m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L64)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

You can act on this now, 22.1 is out.
</blockquote></details>

I'll turn on `DROP INDEX` as fully supported in a follow-up PR. The main change should mostly be test difference (e.g. logging output or job description output)
___
*[`pkg/sql/schemachanger/scdecomp/decomp.go` line 220 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47hSFP0ysL6vhUhNZg:-N493qNR8RsGNRdRW6vg:b-35xmgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scdecomp/decomp.go#L220)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

From experience, I can tell you it's best to not assume that the `dep.ColumnIDs` slice is well-formed (no zeroes, no duplicate elements) or safe to shallow-copy. I suggest you dump its non-zero contents into a `catalog.TableColSet` and assign `ColumnIDs` to the result of `.Ordered()`.
</blockquote></details>

done. Thanks for sharing your experience.



_Code quote:_
```Go
				for _, toID := range tbl.GetDependsOn() {
					to := w.lookupFn(toID)
```
___
*[`pkg/sql/schemachanger/scdecomp/decomp.go` line 226 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47iBJY0eiCv2grocYm:-N4957TcDJfIHf741Kgk:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scdecomp/decomp.go#L226)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: since your anonymous function never returns any errors you could simply have `_ = toDesc.Foreach...` instead of an if-panic.
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 144 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47e2FT5Ku4k8vmfmNK:-N495M-l5Ygn5bYVb6qM:btoygiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scpb/elements.proto#L144)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This information is already present in `ColumnType`.
</blockquote></details>

done. I've removed this field (and the is_partial field from the Index element). Thanks for pointing this out!
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 209 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47e6ph89WI-zcZxS80:-N495iCq2N20d3354kGs:b-obtjqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scpb/elements.proto#L209)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This information can be inferred from the existence or not of a `SecondaryIndexPartial` joining on `(table_id, index_id)`.
</blockquote></details>

field removed, thanks!
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 297 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47eYWVEEfnhJTwqO4u:-N496Ijj3kKLrp4nWDkD:bm50xwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scpb/elements.proto#L297)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

`s/to_id/relation_id/`?
</blockquote></details>

I like `to_id` bc it makes it easier to immediately know this is the referenced relation id. Initially I modeled this `Reference` outside `View` as its own protobuf where I have a `from_id` field and a `to_id` field to represent a uni-directional reference. Andrew suggested that since we're only using this inside View now, we should move it into `View` message and omit the `from_id` field.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_name.go` line 42 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47fNln9Qf9tyZeXYOx:-N4EDXHe3zkq1uauMVNG:bv8szyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_name.go#L42)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Is there a reason for this? The original idea was to express the element removal by zero-ing the name field. An empty string would be invalid, in addition to being opaque, so we instead use a placeholder string instead.
</blockquote></details>

I cannot exactly recall. I think it's related to a failed test when I attempted to turn it on as 'fully supported'. I will revert it back for now and come back to it in the follow up PR that turns `DROP INDEX` on.
___
*[`pkg/sql/schemachanger/scrun/scrun.go` line 136 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47gBk-Bg6N2v_z21oW:-N48uQtT3vPgCFrnWu2p:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scrun/scrun.go#L136)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: newline
</blockquote></details>

done



_Code quote:_
```Go
// pausepointName construct a name for the job execution phase pausepoint.
func pausepointName(state scpb.CurrentState, i int) string {
```


<!-- Sent from Reviewable.io -->

2022-06-16 20:57 UTC, Xiang-Gu commented
While working on this PR, a dep rule error was discovered and described in #82907, which in turn is blocked by #83018.

2022-07-01 17:34 UTC, ajwerner reviewed
One thing I'm noticing looking at the output from this is that I think we're not doing the right thing when dropping constraints. When we drop a foreign key constraint, we need to move it to the dropping state and then remove it. Right now it just disappears. We should not remove the back-reference until later IIRC. I think this cascade is the first case of removing a fk constraint that we have. Can you return a not implemented error if there's a fk constraint and file an issue to track it? 

I'll have a PR up in a few for you to play with in terms of the job state management. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N5uoaXj3XJI4uAMYa-o:bu7cmp3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @chengxiong-ruan, @postamar, and @Xiang-Gu)



<!-- Sent from Reviewable.io -->

2022-07-01 19:50 UTC, Xiang-Gu reviewed
> we need to move it to the dropping state and then remove i

Looking at [fk op_gen](https://github.com/cockroachdb/cockroach/blob/cbfa501a444b67e553cd0d85f46f9288ca64dcd1/pkg/sql/schemachanger/scplan/internal/opgen/opgen_foreign_key_constraint.go#L28-L50), we directly transition from PUBLIC to ABSENT (of course, the fact that this transition is marked as 'non-revertible' but was ignored is a known issue of the planner).  so, it seems this op_gen is incomplete.

> When we drop a foreign key constraint, we need to move it to the dropping state and then remove it.

I'm not familiar of the necessary steps of dropping a FK constraint. I went back to the F1 paper, it says it needs to go through PUBLIC --> WRITE_AND_DELETE_ONLY --> ABSENT. 
I don't understand why you said we want to move it to the `DROPPED` state first -- I thought state `DROPPED` is reserved for db, schema, and tables (e.g. a secondary index won't reach the `DROPPED` state as we define its op_gen)

Finally, I filed https://github.com/cockroachdb/cockroach/issues/83726 to track this issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N5vDPBKEX6JnJ8avzzI:b-mftdj6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @chengxiong-ruan, @postamar, and @Xiang-Gu)



<!-- Sent from Reviewable.io -->

2022-07-01 20:06 UTC, ajwerner commented
>I'm not familiar of the necessary steps of dropping a FK constraint. I went back to the F1 paper, it says it needs to go through PUBLIC --> WRITE_AND_DELETE_ONLY --> ABSENT.
I don't understand why you said we want to move it to the DROPPED state first -- I thought state DROPPED is reserved for db, schema, and tables (e.g. a secondary index won't reach the DROPPED state as we define its op_gen)

Both that paper's terminology and our terminology are inconsistent, but yeah, that's the idea. In constraints, we have this enum: https://github.com/cockroachdb/cockroach/blob/c54f99d6a144e237f4226c93266caafb4fddb705/pkg/sql/catalog/descpb/structured.proto#L35-L36

I mean the dropping value of that thing. See this code here: https://github.com/cockroachdb/cockroach/blob/87e77619740aa6be30f434b2c852df9ea7d02133/pkg/sql/catalog/tabledesc/structured.go#L1441-L1442

We need to take some time to model dropping and adding foreign keys correctly. It definitely does not have to happen here.

2022-07-01 22:51 UTC, Xiang-Gu reviewed
Thank you. I'll remove those tests that involve dropping an index with dependent FK constraints and dependent views for now. I left clear steps required to enable this to be fully supported. I'm going to merge it once I got the CI passing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-:-N5vx3L_8Bo7evI9FSyn:b-862r15)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @chengxiong-ruan, and @postamar)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 208 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-l27qDlTr_EwZ0iEa:-N5vc6l7-ZX8_4uoBwFm:by90tvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scpb/elements.proto#L208)):*
> ref.Validity = descpb.ConstraintValidity_Dropping
this field, `index.is_partial`, is removed, as this information can be inferred from the existence of a `SecondaryIndexPartial` element.
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 308 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N47ejT38OSQf-DJ2Wi_:-N5vcI103e5eFGR_jnwJ:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94282b2e63de5f3831a4e13a3985769ab3c574/pkg/sql/schemachanger/scpb/elements.proto#L308)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Nice.
</blockquote></details>

:)
___
*[`pkg/sql/schemachanger/scplan/internal/scstage/stage.go` line 120 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/80133#-N3-lL9b37jdaz_cIF-I:-N5vcMjTC_O2X4wLURsA:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f23f621164c88af0947d9d3dbf8ba80be2e287ce/pkg/sql/schemachanger/scplan/internal/scstage/stage.go#L120)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Good find!
</blockquote></details>

:)


<!-- Sent from Reviewable.io -->

2022-07-04 14:10 UTC, merged