ui: display closed sessions, add username and session status filter
cockroachdb/cockroach pull request #80410
Opened 2022-04-22 21:12 UTC by gtr

Fixes #67888, #79914.

Previously, the sessions page UI did not support displaying closed
sessions and did not support the ability to filter by username or
session status. This commit adds the "Closed" session status to closed
sessions and adds the ability to filter by username and session status.

Release note (ui change): sessions overview and session details pages now
display closed sessions; sessions overview page now has username and session
status filters

2022-04-22 21:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/80410)
<!-- Reviewable:end -->

2022-04-22 21:35 UTC, gtr commented
One thing to note about this change is that since the `ListSessions` endpoint now returns closed sessions, the UI now has many closed sessions opened by internal app names:
![session-app-names](https://user-images.githubusercontent.com/35943354/164798733-767101ad-ddfc-4b19-a506-23b945d1499f.png)

Additionally, these hidden closed sessions cause the pagination label to quickly increases in number:
![session-pagination](https://user-images.githubusercontent.com/35943354/164798825-dc369a4d-730f-45ae-be2c-ca4c798675c5.png)

While technically correct, it can be a bit confusing because those closed sessions are hidden by default.
Is this a problem? CC: @kevin-v-ngo

2022-04-22 21:40 UTC, kevin-v-ngo commented
> One thing to note about this change is that since the `ListSessions` endpoint now returns closed sessions, the UI now has many closed sessions opened by internal app names: ![session-app-names](https://user-images.githubusercontent.com/35943354/164798733-767101ad-ddfc-4b19-a506-23b945d1499f.png)
> 
> Additionally, these hidden closed sessions cause the pagination label to quickly increases in number: ![session-pagination](https://user-images.githubusercontent.com/35943354/164798825-dc369a4d-730f-45ae-be2c-ca4c798675c5.png)
> 
> While technically correct, it can be a bit confusing because those closed sessions are hidden by default. Is this a problem? CC: @kevin-v-ngo

Thanks Gerardo, do we paginate results before or after the filter is applied? From what you're saying, it seems we paginate the entire result regardless of whether the user specifies filters to hid certain row correct?

CC @Annebirzin

2022-04-22 21:57 UTC, maryliag requested changes
> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80410#-N0IF5-REjROiXrZu0k6:-N0IF5-REjROiXrZu0k7:b-hionc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/57fc667c7bcf0455b0836705e40f1043b5cd4224/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx#L109)):*
> ```XML
>   const uniqueAppNames = new Set(
>     sessions.map(s =>
>       s.session.application_name ? s.session.application_name : "(unset)",
> ```

nit: I just notice this, but we want to use just `$ internal` for all internal app names, so add a check of: if starts with the internal prefix, use just internal prefix
___
*[pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx, line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80410#-N0IGirnB_K2YqyJUVli:-N0IGirnB_K2YqyJUVlj:b-e8ql5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/57fc667c7bcf0455b0836705e40f1043b5cd4224/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx#L437)):*
> ```XML
>           pageSize={pagination.pageSize}
>           current={pagination.current}
>           total={sessionsData.length}
> ```

the reason why you always see the total on the pagination is because here you're using `sessionsData.length` instead of the correct value `sessionsToDisplay.length`


<!-- Sent from Reviewable.io -->

2022-04-25 15:12 UTC, gtr reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80410#-N0IF5-REjROiXrZu0k6:-N0WCe5o6VQtjjJntNqT:b-vqalp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/57fc667c7bcf0455b0836705e40f1043b5cd4224/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx#L109)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: I just notice this, but we want to use just `$ internal` for all internal app names, so add a check of: if starts with the internal prefix, use just internal prefix
</blockquote></details>

Great catch! This also brings the number of filter options down.
___
*[`pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx` line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80410#-N0IGirnB_K2YqyJUVli:-N0WClVz73YQzJM7AEJI:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/57fc667c7bcf0455b0836705e40f1043b5cd4224/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx#L437)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the reason why you always see the total on the pagination is because here you're using `sessionsData.length` instead of the correct value `sessionsToDisplay.length`
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2022-04-25 15:19 UTC, gtr commented
> Thanks Gerardo, do we paginate results before or after the filter is applied? From what you're saying, it seems we paginate the entire result regardless of whether the user specifies filters to hid certain row correct?
> 
> CC @Annebirzin

As Marylia pointed out, the pagination total was always set to whatever the total number of sessions before we apply the filters. The correct value should be the total number of sessions *after* the filters are applied. 

So when first loading the sessions page, this is what it should look like:

<img width="1592" alt="sessions-page-empty" src="https://user-images.githubusercontent.com/35943354/165119758-2d63e9ca-6c64-4c80-bc75-c33030bde01e.png">

The filter now condenses all the `$ internal` app names and looks like this:

<img width="296" alt="sessions-page-filter" src="https://user-images.githubusercontent.com/35943354/165119891-0b6b0543-0927-4755-a50c-8ad9b416f1c2.png">

And finally, when we select `$ internal` app names, we get the correct pagination:

<img width="1744" alt="sessions-page-internal" src="https://user-images.githubusercontent.com/35943354/165120139-bdead619-7dd9-4d0e-8f60-4b4e5ee92c34.png">

2022-04-25 15:42 UTC, Annebirzin commented
@gtr 👍  Your latest update looks good to me (condense all internal app names, pagination applies after filters are applied)

2022-04-26 16:25 UTC, maryliag reviewed
> Reviewed 2 of 9 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx` line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80410#-N0ag1Cv9nKuHCJtEIhA:-N0ag1Cv9nKuHCJtEIhB:by2t0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d842f3ec667beceae94f27794914c0dba82a77fd/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx#L388)):*
> ```XML
> 
>     // const totalSessions = sessionsData.length;
>     const totalSessions = sessionsToDisplay.length;
> ```

nit: no need to create a variable just for the length, use this directly on the pagination component (also clean up the unnecessary comment)


<!-- Sent from Reviewable.io -->

2022-04-26 16:58 UTC, gtr reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx` line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80410#-N0ag1Cv9nKuHCJtEIhA:-N0anrSM2FeFhapfwczs:bucvtlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d842f3ec667beceae94f27794914c0dba82a77fd/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx#L388)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: no need to create a variable just for the length, use this directly on the pagination component (also clean up the unnecessary comment)
</blockquote></details>

Didn't mean to leave that in there, thanks!


<!-- Sent from Reviewable.io -->

2022-04-26 22:39 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80410#-:-N0c0nR8C4QJS8-m-pfY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gtr)



<!-- Sent from Reviewable.io -->

2022-04-26 22:51 UTC, gtr commented
bors r+

2022-04-27 00:20 UTC, merged