ui: Plot circuit breaker tripped events as a rate values
cockroachdb/cockroach pull request #81438
Opened 2022-05-18 13:03 UTC by koorosh

Resolves https://github.com/cockroachdb/cockroach/issues/78939

Before, Circuit Breaker Tripped events chart displayed the accumulated number
of events since the process started.

Now, it displays the number of events per aggregated interval of time.

Release note (ui change): Circuit Breaker Tripped events chart displays
rate of events per interval instead of the accumulated number of events.

<img width="988" alt="Screen Shot 2022-05-18 at 16 03 22" src="https://user-images.githubusercontent.com/3106437/169045058-b0424e72-08ef-4ceb-a1d1-f0f094048bd1.png">

2022-05-18 13:04 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/81438)
<!-- Reviewable:end -->

2022-05-18 20:00 UTC, tbg requested changes
Looks good mod the comment Help in metrics.go, thanks!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81438#-:-N2NkRzGBCZ86yKBPrh4:b-2pv0nf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/kv/kvserver/metrics.go` line 1407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81438#-N2Nk6c7CiB0pMZ0wSC6:-N2Nk6c7CiB0pMZ0wSC7:b1t6z57) ([raw file](https://github.com/cockroachdb/cockroach/blob/361bfd076ff41b5fbbdda4af97d1616adacb8b9a/pkg/kv/kvserver/metrics.go#L1407)):*
> ```Go
> 	metaReplicaCircuitBreakerCumTripped = metric.Metadata{
> 		Name:        "kv.replica_circuit_breaker.num_tripped_events",
> 		Help:        `The number of circuit breaker events occurred per second across all nodes since the process started.`,
> ```

This isn't "across all nodes", each metric counter is local to a store and thus will be reported at the store level. It just so happens that the chart we later expose in the DB console aggregates over all stores. So the comment in `graphTooltips.tsx` is correct. Also, this here is still a counter, not a rate. We only compute a rate in the console.


<!-- Sent from Reviewable.io -->

2022-05-19 06:55 UTC, koorosh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81438)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/kv/kvserver/metrics.go` line 1407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81438#-N2Nk6c7CiB0pMZ0wSC6:-N2Q51UR4_bwDmeF__Yc:b72big) ([raw file](https://github.com/cockroachdb/cockroach/blob/361bfd076ff41b5fbbdda4af97d1616adacb8b9a/pkg/kv/kvserver/metrics.go#L1407)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This isn't "across all nodes", each metric counter is local to a store and thus will be reported at the store level. It just so happens that the chart we later expose in the DB console aggregates over all stores. So the comment in `graphTooltips.tsx` is correct. Also, this here is still a counter, not a rate. We only compute a rate in the console.
</blockquote></details>

gotcha, then I tend to revert back this Help message because it also doesn't count "per second".


<!-- Sent from Reviewable.io -->

2022-05-19 08:40 UTC, tbg approved these changes

2022-05-19 14:03 UTC, koorosh commented
bors r+

2022-05-19 17:54 UTC, rickystewart commented
bors r-

2022-05-19 17:55 UTC, rickystewart commented
bors r=tbg

Sorry, needed to cancel this run to move `bors` along.

2022-05-19 21:01 UTC, merged