asim,kvserver: simulate rrq rebalancing
cockroachdb/cockroach pull request #82089
Opened 2022-05-30 21:37 UTC by kvoli

LastUpdatedTime tracks the last time a storepool has received an update
from another store via gossip. Stores are considered dead if the elapsed
duration between LastUpdatedTime and the current time is greater than
the gossip interval plus a buffer. In order to simulate gossip, this
patch exports the  LastUpdatedTime field so that it may be modified by
the allocation simulator in order to control the live and dead stores.

The simulator state did not have an interface to interact with
previously. This patch introduces a monolithic interface and separates
out simulator ojbects such as nodes, stores, ranges and replicas as
immutable. The purpose of this patch is to keep the simulator internal
state logic distinct from mutators which use the state as an input or
propose state changes.

This patch adds a state changer, which enqueues and delays the
application of changes based on the receiver and change itself. An
implementation of this logic is added for replica changes, simulating
the delay between deciding to move a replica and the decision taking
effect.

This patch adds logic to simulate the replicate queue. The replicate
queue considers replicas that it is given, enqueueing them if they meet
the criteria. The criteria is currently whether there is a non noop
allocator action for that replica. The replicate queue proceses one
replica at once and if a consider rebalance action is returned by the
allocator, it will create a replica change to be applied to state.

Release note: None

2022-05-30 21:37 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/82089)
<!-- Reviewable:end -->

2022-06-06 19:28 UTC, lidorcarmel requested changes
partial review for now - sorry about that, will continue today/tomorrow.
another huge progress, thank you Austen!
overall only minor comments.. some complaints about more dumb and simple unit tests.

> Reviewed 2 of 2 files at r1, 20 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-:-N3uU2MM-vsArEhct-2V:beklqee)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @lidorcarmel)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3XMwZgAhfSx1H1FSjn):*
is that true? is it related to the gossip time? or do we declare a store dead after 5 minutes?



_Code quote:_
```
  from another store via gossip. Stores are considered dead if the elapsed
  duration between LastUpdatedTime and the current time is greater than
  the gossip interval plus a buffer. In order to simulate gossip, this
```
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3XNDuo4H1G_ULkycw5):*
'control store liveness' maybe?



_Code quote:_
```
which store liveness
```
___
*[`pkg/kv/kvserver/asim/state/helpers.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uB2FH1pe1S6bMdOxF:-N3uB2FH1pe1S6bMdOxG:bu2rfog) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/helpers.go#L68)):*
> ```Go
> // ReverseOffsetTick converts an offset time from the start time, into the
> // number of ticks (seconds) since the start.
> func ReverseOffsetTick(start, tick time.Time) int64 {
> ```

above in `OffsetTick` you use `tick` as the int (tick number) and here as the time. maybe rename `tick` to something like `tickTime`?



_Code quote:_
```Go
tick
```
___
*[`pkg/kv/kvserver/asim/state/helpers.go` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uC7j1AC7ow0maZva1:-N3uC7j1AC7ow0maZva2:b-4alofb) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/helpers.go#L73)):*
> ```Go
> }
> 
> // NewTestState returns a State populated with the specification given.
> ```

what are those ranges that are returned here? we already have ranges in the state, right?



_Code quote:_
```Go
NewTestState returns a State
```
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uDIF802dwBmZjts2S:-N3uDIF9-DAx0jRmH1fE:b80o40e) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L106)):*
> ```Go
> }
> 
> // String returns string containing a compact representation of the state.
> ```

returns a string

also, is there a unit test for this one?



_Code quote:_
```Go
returns string
```
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uElnh-UwrGIxj448J:-N3uElni7NYS8GvnC9rg:budwod4) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L151)):*
> ```Go
> func (s *state) Stores() map[StoreID]Store {
> 	stores := make(map[StoreID]Store)
> 	for storeID, store := range s.stores {
> ```

is this just a deep copy?
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 321 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uHLHz84vd-UjCOrZS:-N3uHLHz84vd-UjCOrZT:bhwtt0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L321)):*
> ```Go
> // ValidTarget returns whether adding/removing a replica for the Range with ID
> // RangeID from/to the Store with ID StoreID is valid.
> func (s *state) ValidTarget(rangeID RangeID, storeID StoreID, add bool) bool {
> ```

would it be more readable to break this to adding and removing replicas? e.g.,`CanAddReplica` and `CanRemoveReplica`?
I think it would help but not critical so up to you.

also, unit test?
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uI8x8BEpVb5BAKwmX:-N3uI8x8BEpVb5BAKwmY:b-uy53vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L366)):*
> ```Go
> 
> 	if _, ok := rng.desc.RemoveReplica(roachpb.NodeID(nodeID), roachpb.StoreID(storeID)); !ok {
> 		return false
> ```

we probably want to start logging when we get these kind of errors?
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 432 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uJXxW2a2L7-x0FF0V:-N3uJXxW2a2L7-x0FF0W:b-o27hof) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L432)):*
> ```Go
> 	ranges.rangeTree.DescendLessOrEqual(r, func(i btree.Item) bool {
> 		// The case where the min key already exists cannot occur here, as a
> 		// panic will have fired in the above iteration.
> ```

we actually don't panic, right? just return early.



_Code quote:_
```Go
		// The case where the min key already exists cannot occur here, as a
		// panic will have fired in the above iteration.
```
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 444 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uK79nCmMhGb5bBeve:-N3uK79nCmMhGb5bBevf:b-9xe7ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L444)):*
> ```Go
> 
> 	// If there are existing replicas for the LHS of the split, then also
> 	// create replicas on the same stores for the RHS. We first check  whether
> ```

double space?

also, why would this ever fail? the location of the N replicas of the LHS is legal, and therefore it must be legal for the RHS, right?



_Code quote:_
```Go
We first check  whether
```
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uKVUl1Vw5ZUHLlR0t:-N3uKVUl1Vw5ZUHLlR0u:bv564bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L454)):*
> ```Go
> 	}
> 
> 	// Set the predecessor (LHS) end  key to the  start key of the split (RHS).
> ```

the double space strikes twice!



_Code quote:_
```Go
end  key to the  start
```
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 482 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uNXhIA9HdEyTDlkmO:-N3uNXhIA9HdEyTDlkmP:b-bdyay2) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L482)):*
> ```Go
> // no such Range; or if the Store doesn't hold a Replica for the Range; or
> // if the Replica for the Range on the Store is already the leaseholder.
> func (s *state) TransferLease(rangeID RangeID, storeID StoreID) bool {
> ```

unit test?
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uNbs45LexejvCqIi6:-N3uNbs45LexejvCqIi7:b-bdyay2) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L506)):*
> ```Go
> // ValidTransfer returns whether transferring the lease for the Range with ID
> // RangeID, to the Store with ID StoreID is valid.
> func (s *state) ValidTransfer(rangeID RangeID, storeID StoreID) bool {
> ```

unit test?
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uOPrf73Zoxw12XTMu:-N3uOPrf73Zoxw12XTMv:b-vcnjhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L552)):*
> ```Go
> 
> // TickClock modifies the state Clock time to Tick.
> // TODO(kvoli): tick refactor.
> ```

sorry, what is th [...]

2022-06-08 19:22 UTC, kvoli reviewed
Thanks for the review. Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-:-N43l4TY8iFi7fDs4kaU:bglezxx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @lidorcarmel)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3XMwZgAhfSx1H1FSjn):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

is that true? is it related to the gossip time? or do we declare a store dead after 5 minutes?
</blockquote></details>

https://github.com/cockroachdb/cockroach/blob/1ee37defce492a4f619b1110224ba139e263d6ad/pkg/kv/kvserver/allocator/storepool/store_pool.go#L94-L94 it's the gossip interval for stores (1 minute) + the buffer (15s default).
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3XNDuo4H1G_ULkycw5):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

'control store liveness' maybe?
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/asim/state/helpers.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uB2FH1pe1S6bMdOxF:-N42cw-xERx8tzDs3_H9:b-cypxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/helpers.go#L68)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

above in `OffsetTick` you use `tick` as the int (tick number) and here as the time. maybe rename `tick` to something like `tickTime`?
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/asim/state/helpers.go` line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uC7j1AC7ow0maZva1:-N42d3ya7ibBSnogjDkb:bb9ato9) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/helpers.go#L73)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

what are those ranges that are returned here? we already have ranges in the state, right?
</blockquote></details>

Unsure why this was left over. Removed.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uDIF802dwBmZjts2S:-N42eOGl4R8dZ-nKVjfK:bm6cgxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L106)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

returns a string

also, is there a unit test for this one?
</blockquote></details>

Updated. No unit test - this one seemed simple enough atm. I'll add a TODO and perhaps we look at it in the stats collection patch.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uElnh-UwrGIxj448J:-N42egUD4y332-61rFQE:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L151)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

is this just a deep copy?
</blockquote></details>

Yes.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 321 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uHLHz84vd-UjCOrZS:-N43hIIgC2TtYB7KNsTN:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L321)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

would it be more readable to break this to adding and removing replicas? e.g.,`CanAddReplica` and `CanRemoveReplica`?
I think it would help but not critical so up to you.

also, unit test?
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uI8x8BEpVb5BAKwmX:-N43JCAoA6CYVM9mhmDn:b-5et5vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L366)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

we probably want to start logging when we get these kind of errors?
</blockquote></details>

Im unsure if we need to, the caller can log on the return value.  In either case where it doesn't meet the first check or this one - the caller (our code) probably has a bug. So it would just dump the state and log there as it's better suited to handle it.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 432 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uJXxW2a2L7-x0FF0V:-N43JbsX-zk7vamWu7hz:b-yem8g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L432)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

we actually don't panic, right? just return early.
</blockquote></details>

That's right, we set the failed flag. Updated.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 444 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uK79nCmMhGb5bBeve:-N43K5-d0l7VM2BCWaxt:b-6u73vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L444)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

double space?

also, why would this ever fail? the location of the N replicas of the LHS is legal, and therefore it must be legal for the RHS, right?
</blockquote></details>

It can't fail at the moment. I can only see it failing if there were concurrency atm. Removing.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uKVUl1Vw5ZUHLlR0t:-N43KjEMBpIX2jUHxNF7:b-kh59k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L454)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

the double space strikes twice!
</blockquote></details>

My formatter needs some work :(
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 482 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uNXhIA9HdEyTDlkmO:-N43hGS81PO4fa7dOrsP:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L482)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

unit test?
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uNbs45LexejvCqIi6:-N43hFlgBLfk2LE14oF2:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L506)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

unit test?
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uOPrf73Zoxw12XTMu:-N43KycF4o_u7JhQV90F:b-chraxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L552)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

sorry, what is this about?
</blockquote></details>

Related to dropping time.Time in favor of a tick package which is just an int64. There's another comment so this I removed this more erroneous one.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 580 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uPNNM5bWa78To5N2n:-N [...]

2022-06-10 05:09 UTC, lidorcarmel requested changes
awesome. finished the first pass over everything (finally).

> Reviewed 5 of 5 files at r3, 5 of 5 files at r4, 7 of 24 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-:-N4B-jCs9Vt-dkDzsWLU:b-hac2b1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @lidorcarmel)

___
*[`-- commits` line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N40VCHXAWsSKWUqpLmw):*
nit - maybe add quotes around "consider rebalance"? for clarity.



_Code quote:_
```
consider rebalance
```
___
*[`pkg/kv/kvserver/asim/asim.go` line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N40WdGA-NJoRUgwmxh4:-N40WdGBEAhYqvN0eeMO:buebae6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/asim.go#L122)):*
> ```Go
> 		// Done with config and load updates, the state is ready for the
> 		// allocators.
> 		stateForAlloc := s.state
> ```

is this assignment still needed? if yes, explain here?
___
*[`pkg/kv/kvserver/asim/asim.go` line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N40Wrw874yZhzov0wHp:-N40Wrw874yZhzov0wHq:bcr713z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/asim.go#L163)):*
> ```Go
> 		for {
> 			r := s.pacers[storeID].Next(tick)
> 			// No replicas to consider at this tick.
> ```

nit: move the comment one line down.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4AwRvT9eXiabMknA3n:-N4AwRvT9eXiabMknA3o:bvltvs8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L56)):*
> ```Go
> 
> // Less is part of the container.Heap interface.
> func (pq priorityQueue) Less(i, j int) bool {
> ```

can you add basic unit tests to verify the methods of priorityQueue?
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4Ax0wLBqBjxSfWu3KG:-N4Ax0wLBqBjxSfWu3KH:bnupg15) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L74)):*
> ```Go
> }
> 
> // push is part of the container.Heap interface.
> ```

s/push/Push/ (lint will complain anyway..)



_Code quote:_
```Go
push
```
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4AvTUK2AAxtSX-ruEn:-N4AvTUK2AAxtSX-ruEo:b-x59lk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L95)):*
> ```Go
> }
> 
> type priorityQueue struct {
> ```

should this move up? to be before its methods?
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4AwEhk9cYAQP7cFIDG:-N4AwEhk9cYAQP7cFIDH:b5506on) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L97)):*
> ```Go
> type priorityQueue struct {
> 	seqGen int
> 	sl     []*replicaItem
> ```

what does `sl` stand for? 



_Code quote:_
```Go
sl
```
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4Ay6m197TUPJcATkex:-N4Ay6m197TUPJcATkey:boyn4wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L141)):*
> ```Go
> 
> 	action, priority := rq.allocator.ComputeAction(ctx, rng.SpanConfig(), rng.Descriptor())
> 	if action != allocatorimpl.AllocatorNoop {
> ```

nit: consider:

if noop
  return false
push
return true
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4Ayuaw4zkxJ_hQSS9Z:-N4Ayuaw4zkxJ_hQSS9_:bvz3ih0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L176)):*
> ```Go
> 	}
> 
> 	action, _ := rq.allocator.ComputeAction(ctx, rng.SpanConfig(), rng.Descriptor())
> ```

we call `ComputeAction` `in MaybeAdd` and here again, is it because the returned action can be different? does the prod code do the same?
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4Az6PuCBQvqKVQT5QY:-N4Az6PuCBQvqKVQT5QZ:b-1wunfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L185)):*
> ```Go
> 	default:
> 		log.Infof(ctx, "allocator action %s for range %s is unsupported by the simulator "+
> 			"replicate queue, ignoring.", action, rng)
> ```

this might be too noisy.. but up to you.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4-OkEHEU_GoXko6d19:-N4-OkEHEU_GoXko6d1A:bhrg7i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0690f05e0950f9698fac6536f68e5de444a541a0/pkg/kv/kvserver/asim/state/change.go#L21)):*
> ```Go
> // Change is a state change for a range, to a target store that has some delay.
> type Change interface {
> 	// Apply applies a change to given state.
> ```

to the given state?



_Code quote:_
```Go
to given
```
___
*[`pkg/kv/kvserver/asim/state/change.go` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N40TMBN9stHtcsJ68dm:-N40TMBN9stHtcsJ68dn:brfies7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0690f05e0950f9698fac6536f68e5de444a541a0/pkg/kv/kvserver/asim/state/change.go#L24)):*
> ```Go
> 	Apply(s State)
> 	// To returns the recipient of any added data for a change.
> 	To() StoreID
> ```

I am not a fan of the `To` and `For` names.. do you think `Store` and `Range` can work? if not, feel free to leave as is.



_Code quote:_
```Go
To()
```
___
*[`pkg/kv/kvserver/asim/state/change.go` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4-QSNj0QNEyz2hjF3O:-N4-QSNj0QNEyz2hjF3P:bk84wwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0690f05e0950f9698fac6536f68e5de444a541a0/pkg/kv/kvserver/asim/state/change.go#L43)):*
> ```Go
> }
> 
> // ReplicaChange contains information necessary to add, remove or move (both) a
> ```

do you want to say that ReplicaChange implements the Change interface?

btw, in the code we usually say that for all methods (X is part of Y interface), but you didn't and instead I think you called it out in the comment of the struct. I'm ok either way because it's not mentioned in the style guide, and also, with goland it's easy to get to the interface.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4-UfJW4bwgLE3VHhSt:-N4-UfJW4bwgLE3VHhSu:b-dohe5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0690f05e0950f9698fac6536f68e5de444a541a0/pkg/kv/kvserver/asim/state/change.go#L52)):*
> ```Go
> 
> // Apply applies a replica change for a range.
> func (rc *ReplicaChange) Apply(s State) {
> ```

do we have unit tests for this one?

it would be nice to go through all the supported scenarios:

add - always succeeds I think
remove - existing/non-existing
remove a leasholder
remove and add
remove a leaseholder and add
___
*[`pkg/kv/kvserver/asim/state/change.go` line 64 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4-UZ7w6ixlXw7Zvg12:-N4-UZ7w6ixlXw7Zvg13:b21gb9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/0690f05e0950f9698fac6536f68e5de444a541a0/pkg/kv/kvserver/asim/state/change.go#L64)):*
> ```Go
> 		if !s.ValidTransfer(rc.RangeID, rc.Add) {
> 			// Cannot transfer lease, bail out and revert.
> 			s.RemoveReplica(rc.RangeID, rc.Add)
> ```

do you want to return here?
___
*[ [...]

2022-06-10 18:26 UTC, kvoli reviewed
Ty for the review, updated with feedback - especially given how bloated this one became.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-:-N4DgLh26c1kmD1xerZF:b-mxngkt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lidorcarmel)

___
*[`-- commits` line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N40VCHXAWsSKWUqpLmw):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit - maybe add quotes around "consider rebalance"? for clarity.
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/asim/asim.go` line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N40WdGA-NJoRUgwmxh4:-N4D299T2yCG-NIb2ArM:b-s3hmk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/asim.go#L122)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

is this assignment still needed? if yes, explain here?
</blockquote></details>

Not needed.
___
*[`pkg/kv/kvserver/asim/asim.go` line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N40Wrw874yZhzov0wHp:-N4D2alkAqh5qVxg1NYN:b-yr8b9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/asim.go#L163)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit: move the comment one line down.
</blockquote></details>

jUpdated.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4AwRvT9eXiabMknA3n:-N4DgCyi074BDRwaE32C:bwyarr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L56)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

can you add basic unit tests to verify the methods of priorityQueue?
</blockquote></details>

These are tested in the actual base queue implementation. This is pretty much a rip from there.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4Ax0wLBqBjxSfWu3KG:-N4D3cAi4FboUuI82HnN:b-cypxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L74)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

s/push/Push/ (lint will complain anyway..)
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4AvTUK2AAxtSX-ruEn:-N4D3NJv1NIiuO1ZBdF_:b-cypxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L95)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

should this move up? to be before its methods?
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4AwEhk9cYAQP7cFIDG:-N4D3Ny89-eJbbooUIFn:bozkaxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L97)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

what does `sl` stand for? 
</blockquote></details>

updated to be items.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4Ay6m197TUPJcATkex:-N4D4yHy9s-lwxuv9vO2:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L141)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit: consider:

if noop
  return false
push
return true
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4Ayuaw4zkxJ_hQSS9Z:-N4D5-ILCdyiJQ31lDpQ:b-qbqk8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L176)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

we call `ComputeAction` `in MaybeAdd` and here again, is it because the returned action can be different? does the prod code do the same?
</blockquote></details>

The prod code does the same
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4Az6PuCBQvqKVQT5QY:-N4D53T3DMaH7kRLMRLR:biq5zaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L185)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

this might be too noisy.. but up to you.
</blockquote></details>

It signals that there's an issue at the moment so I'll leave it.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4-OkEHEU_GoXko6d19:-N4D5GM4-8FltxVmEZ4n:b-dlnszy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0690f05e0950f9698fac6536f68e5de444a541a0/pkg/kv/kvserver/asim/state/change.go#L21)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

to the given state?
</blockquote></details>

Updated.j
___
*[`pkg/kv/kvserver/asim/state/change.go` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N40TMBN9stHtcsJ68dm:-N4D5MZ_-ZgN4fK4k5_0:bkind27) ([raw file](https://github.com/cockroachdb/cockroach/blob/0690f05e0950f9698fac6536f68e5de444a541a0/pkg/kv/kvserver/asim/state/change.go#L24)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

I am not a fan of the `To` and `For` names.. do you think `Store` and `Range` can work? if not, feel free to leave as is.
</blockquote></details>

I wanted to keep it somewhat general, I suppose that To could only ever be a store and For could only ever be a range. Updated.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4-QSNj0QNEyz2hjF3O:-N4D5ufi40JC0kQMybqL:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0690f05e0950f9698fac6536f68e5de444a541a0/pkg/kv/kvserver/asim/state/change.go#L43)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

do you want to say that ReplicaChange implements the Change interface?

btw, in the code we usually say that for all methods (X is part of Y interface), but you didn't and instead I think you called it out in the comment of the struct. I'm ok either way because it's not mentioned in the style guide, and also, with goland it's easy to get to the interface.
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4-UfJW4bwgLE3VHhSt:-N4DcPGA43bmLrRzLw90:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0690f05e0950f9698fac6536f68e5de444a541a0/pkg/kv/kvserver/asim/state/change.go#L52)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

do we have unit tests for this one?

it would be nice to go through all the supported scenarios:

add - always succeeds I think
remove - existing/non-existing
remove a leasholder
remove and add
remove a leaseholder and add
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 64 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4-UZ7w6 [...]

2022-06-10 19:01 UTC, lidorcarmel approved these changes
thanks for all the updates!!! this looks awesome :)

> Reviewed 4 of 24 files at r5, 1 of 24 files at r9, 16 of 20 files at r10, 3 of 5 files at r11, 5 of 5 files at r12, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-:-N4DzYZ2A6cA2JH9qqSv:b-w6fqwo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4AwRvT9eXiabMknA3n:-N4DsnCq2AEGEXbQcDQc:bqa3gi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L56)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

These are tested in the actual base queue implementation. This is pretty much a rip from there.
</blockquote></details>

say we got `a.seq < b.seq` wrong, or some future comparison, and still the high level tests pass.
maybe rip the tests also? nothing too fancy, just make sure the FIFO and priority work as expected I think.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4Ayuaw4zkxJ_hQSS9Z:-N4Dv5NY7s2E3VIj_v8J:bd5l6n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L176)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

The prod code does the same
</blockquote></details>

thanks.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uDIF802dwBmZjts2S:-N4DwVreB9a6zPe8Xkb3:b-dwali7) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L106)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Updated. No unit test - this one seemed simple enough atm. I'll add a TODO and perhaps we look at it in the stats collection patch.
</blockquote></details>

everything starts simple.. and then... less simple.
thanks for the todo.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uKVUl1Vw5ZUHLlR0t:-N4Dy41qDzjAjOEUv20q:b-2wz6ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L454)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

My formatter needs some work :(
</blockquote></details>

forgot to update? :)
___
*[`pkg/kv/kvserver/asim/state/state.go` line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uRzg-7gue159RZgLm:-N4DyZdf3WLK7U7sUe3p:b-s0i0b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/state.go#L36)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

I don't see the update..
___
*[`pkg/kv/kvserver/asim/state/load.go` line 63 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4DyR2d6Y5ivXwifUSE:-N4DyR2d6Y5ivXwifUSF:bwf995o) ([raw file](https://github.com/cockroachdb/cockroach/blob/5915e29df4cdb5e0920ee8c673abcb3197a4c424/pkg/kv/kvserver/asim/state/load.go#L63)):*
> ```Go
> }
> 
> // Capacity returns the store capacity for the store with id storeid. it
> ```

nit: s/storeid/storeID/



_Code quote:_
```Go
storeid
```


<!-- Sent from Reviewable.io -->

2022-06-11 03:02 UTC, kvoli reviewed
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-:-N4FPebgAqWrp1dRUWlD:bzftgo7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lidorcarmel)

___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4AwRvT9eXiabMknA3n:-N4FP2fC0qfLaWbRGh_R:b-t948zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L56)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

say we got `a.seq < b.seq` wrong, or some future comparison, and still the high level tests pass.
maybe rip the tests also? nothing too fancy, just make sure the FIFO and priority work as expected I think.
</blockquote></details>

added.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4Ayuaw4zkxJ_hQSS9Z:-N4FPfm96Wge-lhmuB44:b2ni8v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd6d638d987a3010e7cab8c50f0ce904ab941d1/pkg/kv/kvserver/asim/replicate_queue.go#L176)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

thanks.
</blockquote></details>

nw.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uDIF802dwBmZjts2S:-N4FPd73BF9QVhbbGji-:bi6n0b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L106)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

everything starts simple.. and then... less simple.
thanks for the todo.
</blockquote></details>

agreed.
___
*[`pkg/kv/kvserver/asim/state/impl.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uKVUl1Vw5ZUHLlR0t:-N4FL0-P7QIVoKguvOb7:b-cypxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/impl.go#L454)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

forgot to update? :)
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/asim/state/state.go` line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N3uRzg-7gue159RZgLm:-N4FLK-Z7NKz08stTjn2:b-7tfmjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/97df7d44432924e3f579003cb09ca668888bec71/pkg/kv/kvserver/asim/state/state.go#L36)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

I don't see the update..
</blockquote></details>

added
___
*[`pkg/kv/kvserver/asim/state/load.go` line 63 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4DyR2d6Y5ivXwifUSE:-N4FLCq12H7STfWp2FKo:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/5915e29df4cdb5e0920ee8c673abcb3197a4c424/pkg/kv/kvserver/asim/state/load.go#L63)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit: s/storeid/storeID/
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2022-06-11 19:19 UTC, lidorcarmel approved these changes
> Reviewed 2 of 13 files at r15, 3 of 7 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82089)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lidorcarmel)



<!-- Sent from Reviewable.io -->

2022-06-11 21:08 UTC, kvoli commented
bors r+

2022-06-11 21:59 UTC, kvoli commented
bors r-

2022-06-11 23:22 UTC, kvoli commented
> bors r-

Branch was 500 commits behind. The `hlc.ManualClock` was refactored on master to not allow arbitrary time setting, instead being linked to system time. This is undesirable, added a simulator clock implementation to fix this.

2022-06-11 23:43 UTC, lidorcarmel approved these changes
lgtm.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-:-N4K7njLBFpoQb-14lrX:b-7nbn1n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @lidorcarmel)

___
*[`pkg/kv/kvserver/asim/workload/workload_test.go` line 113 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/82089#-N4K8aK9APvLcPXNNlDk:-N4K8aK9APvLcPXNNlDl:b-qi93oj) ([raw file](https://github.com/cockroachdb/cockroach/blob/def302e1b09042985abeb21e8fd503e70d11c8ca/pkg/kv/kvserver/asim/workload/workload_test.go#L113)):*
> ```Go
> 
> 	for _, tc := range testCases {
> 		start := time.Date(2022, 03, 21, 11, 0, 0, 0, time.UTC)
> ```

is this intentional? just making sure..


<!-- Sent from Reviewable.io -->

2022-06-12 00:46 UTC, kvoli commented
bors r+

2022-06-12 13:37 UTC, kvoli commented
bors r-

2022-06-12 15:08 UTC, kvoli commented
bors r+

2022-06-12 16:07 UTC, merged