build: remove double-quotes from aria-query .patch files
cockroachdb/cockroach pull request #82186
Opened 2022-05-31 23:41 UTC by sjbarag

The patches in pkg/ui/patches/ were previously generated with GNU diff
3.7 and applied with GNU patch 2.7.6 (both the latest versions in my
Ubuntu 20.04 remove dev machine). Those versions produce
and apply patch files that contain double-quoted filenames when
those names have spaces in them [1, 2]. Unfortunately, macOS 12.4
currently includes GNU diff 2.8.1 and GNU patch 2.5.8 -- neither of
which support double-quoted filenames. Regenerate the aria-query .patch
files that remove spaced filenames using GNU diff 2.8.1 to ensure the
patches correctly apply on macOS.

[1] https://github.com/gnu-mirror-unofficial/diffutils/blob/dd9deb765548679e821be565229bb2e142d93573/NEWS#L137-L140
[2] https://github.com/gnu-mirror-unofficial/patch/blob/24f81beb27b3ea92bc6bccfca960f93de7f9055d/NEWS#L51-L54

Release note: None

2022-05-31 23:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/82186)
<!-- Reviewable:end -->

2022-06-01 00:13 UTC, irfansharif approved these changes
🐶🔍 Just verified things worked on my M1.

2022-06-01 14:43 UTC, rickystewart requested changes
Looks like this breaks CI.

2022-06-09 20:36 UTC, sjbarag commented
There's a chance this is failing because the dates in the `.patch` file have my local timezone in them: `1969-12-31 16:00:00.000000000 -0800` though that's still 1970-01-01T00:00:00.000000 so I'm not entirely sure what that'd cause problems

2022-06-14 18:29 UTC, sjbarag commented
No longer needed thanks to #82854 !

2022-06-14 18:29 UTC, closed without merging