ppc64le - fix geogfn and geomfn test failures
cockroachdb/cockroach pull request #82250
Opened 2022-06-01 11:11 UTC by prashantkhoje

geogfn
    - TestAzimuth/north_east
    - TestSegmentize/LINESTRING(1.0_1.0,_2.0_2.0,_3.0_3.0),_maximum_segment_length:_100000.000000
    - TestSegmentize/POLYGON((0.0_0.0,_1.0_0.0,_1.0_1.0,_0.0_0.0)),_maximum_segment_length:_100000.000000
    - TestSegmentize/POLYGON((0.0_0.0,_1.0_0.0,_1.0_1.0,_0.0_0.0),_(0.1_0.1,_0.2_0.1,_0.2_0.2,_0.1_0.1)),_maximum_segment_length:_50000.000000
    - TestSegmentize/MULTILINESTRING((1.0_1.0,_2.0_2.0,_3.0_3.0),_(6.0_6.0,_7.0_6.0)),_maximum_segment_length:_100000.000000
    - TestSegmentize/MULTILINESTRING_(EMPTY,_(1.0_1.0,_2.0_2.0,_3.0_3.0),_(6.0_6.0,_7.0_6.0)),_maximum_segment_length:_100000.000000
    - TestSegmentize/MULTIPOLYGON(((3.0_3.0,_4.0_3.0,_4.0_4.0,_3.0_3.0)),_((0.0_0.0,_1.0_0.0,_1.0_1.0,_0.0_0.0),_(0.1_0.1,_0.2_0.1,_0.2_0.2,_0.1_0.1))),_maximum_segment_length:_100000.000000
    - TestSegmentize/GEOMETRYCOLLECTION_(POINT_(40_10),LINESTRING_(10_10,_20_20,_10_40),POLYGON_((40_40,_20_45,_45_30,_40_40))),_maximum_segment_length:_1000000.000000
    - TestSegmentize/LINESTRING(0_0_25,_0_1_0,_2_5_100),_maximum_segment_length:_150000.000000
    - TestSegmentizeCoords/Coordinate(85,_85)_to_Coordinate(0,_0),_0.29502092024628396
    - TestSegmentizeCoords/Coordinate(0,_16,_23,_10)_to_Coordinate(1,_0,_-5,_0),_0.07848050723825097
    - TestProject/SRID

geomfn - TestGenerateRandomPoints/Polygon_with_a_hole

Cherry picks #66621

Release note: None

Co-authored-by: Oliver Tan <otan@cockroachlabs.com>

2022-06-01 11:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/82250)
<!-- Reviewable:end -->

2022-06-01 18:43 UTC, prashantkhoje commented
@rafiss, please review.

2022-06-01 21:02 UTC, otan commented
looks like there are some build failures - namely you need to run `gofmt`/crlfmt on `pkg/geo/geotest/geotest.go` and run `./dev generate bazel`

2022-06-01 22:51 UTC, otan requested changes
(please fix the tests)

2022-06-02 23:29 UTC, otan approved these changes
bors r+

2022-06-03 00:48 UTC, merged