changefeedccl: handle old-style protobufs in rowfetcher_cache
cockroachdb/cockroach pull request #82312
Opened 2022-06-01 21:27 UTC by HonoreDB

Manual backport of https://github.com/cockroachdb/cockroach/pull/82311

Release note (bug fix): Fixed a bug where changefeeds created before upgrading to 22.1 would silently fail to emit any data other than resolved timestamps.

2022-06-01 21:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/82312)
<!-- Reviewable:end -->

2022-06-01 21:31 UTC, miretskiy approved these changes
Giving approval , but please add extra checks.

2022-06-01 21:46 UTC, HonoreDB commented on pkg/ccl/changefeedccl/rowfetcher_cache.go
> +	specs := AllTargets(details)
I like the idea of returning an error from rowfetcher_cache if no specs, but I'm having to change a lot of method signatures. Okay if I leave that out of the backport and just do it in master?

2022-06-01 22:44 UTC, miretskiy approved these changes

2022-06-01 22:44 UTC, miretskiy commented
Logcrash might be appropriate

2022-06-02 00:13 UTC, miretskiy requested changes

2022-06-02 00:13 UTC, miretskiy commented on pkg/ccl/changefeedccl/changefeed_processors.go
> +	}
Looking at release branch, I see exactly 2 call sites to newKVEventTORowConsumer;
Let's just return an error?

2022-06-02 01:38 UTC, miretskiy approved these changes
👍 .  Leave TODOs as appropriate, but good to check in.

2022-06-02 11:11 UTC, merged