sql: add metrics to track long-running SQL queries and transactions
cockroachdb/cockroach pull request #82393
Opened 2022-06-03 06:13 UTC by ajwerner

Stuck queries are a sure sign of an incident. These metrics should make it
relatively easy to tell if there are any long-running queries going on. One
note is that this might be noisy if users are running these queries by hand.
Having a long-running query doesn't mean there is something wrong, but it does
mean you should look at what is long running and make sure that the number of
long-running operations make sense.

Release note (general change): Added metrics sql.query.long_running.count,
sql.query.long_running.max_duration, sql.txn.long_running.count, and
sql.query.long_running.count which track the maximum duration for any
ongoing transactions or statements and the number of transactions or
statements which have been executing for more than 15 seconds. These
metrics can be helpful to quickly determine whether there are long-running
operations in the system and how-many such operations there are.

2022-06-03 06:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/82393)
<!-- Reviewable:end -->

2022-06-03 22:06 UTC, rafiss requested changes
this will be really useful! all my comments are minor

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82393#-:-N3faiTT4cR_mj6s6bhX:b1hqol0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rafiss)

___
*[`pkg/sql/session_metrics_tracker.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82393#-N3fZMxd5omG9LlS8DZP:-N3fZMxd5omG9LlS8DZQ:b-42f6a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b93bd08110cda5350eb75fe06908489fc6c4e6/pkg/sql/session_metrics_tracker.go#L41)):*
> ```Go
> type sessionMetricsTracker struct {
> 	registry *SessionRegistry
> 	// Below fields are only protected by the mutex to enable testing.
> ```

nit: should the comment be moved down further?
___
*[`pkg/sql/session_metrics_tracker.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82393#-N3fZ1WT3_M9ya7_Jcwh:-N3fZ1WT3_M9ya7_Jcwi:b-w3ubp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b93bd08110cda5350eb75fe06908489fc6c4e6/pkg/sql/session_metrics_tracker.go#L48)):*
> ```Go
> 
> 		lastUpdate     time.Time
> 		user, internal sessionMetricsData
> ```

nit: add brief comments mentioning that `user` vs `internal` is decided based on being user-initiated.
___
*[`pkg/sql/session_metrics_tracker.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82393#-N3faBjO1jvqInTlcmgs:-N3faBjO1jvqInTlcmgt:b-itzice) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b93bd08110cda5350eb75fe06908489fc6c4e6/pkg/sql/session_metrics_tracker.go#L62)):*
> ```Go
> 	} else {
> 		smt.minUpdateInterval = defaultMinUpdateInterval
> 		smt.longRunningThreshold = base.SlowRequestThreshold
> ```

one thing i wonder is if people will get confused by the fact that this is hard-coded, while other things like the slow query log threshold and stmt/txn timeouts are configurable. the concern could be addressed by naming -- like instead of using the term "long running" in the user-facing names, is there something else that could make sense? perhaps something to run by Product. (ultimately, i don't feel strongly about the names here, but it's worth considering)
___
*[`pkg/sql/session_metrics_tracker.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82393#-N3fXNvz4gb-QJa2uXyM:-N3fXNvz4gb-QJa2uXyN:brtw79y) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b93bd08110cda5350eb75fe06908489fc6c4e6/pkg/sql/session_metrics_tracker.go#L67)):*
> ```Go
> }
> 
> type longRunningMetrics struct {
> ```

nit: could you add a comment on this one? specifically, that it's aggregating across all the sessions on this node
___
*[`pkg/sql/session_metrics_tracker.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82393#-N3fYLhF8cKNQaLEt9kj:-N3fYLhF8cKNQaLEt9kk:b-lwbc4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b93bd08110cda5350eb75fe06908489fc6c4e6/pkg/sql/session_metrics_tracker.go#L112)):*
> ```Go
> 			updateLongRunning(&smd.txn, now.Sub(s.ActiveTxn.Start))
> 		}
> 		for i := range s.ActiveQueries {
> ```

i was confused for a bit, but then remembered the tech debt we have here. maybe a quick mention that in practice, ActiveQueries always has at most 1 element?
___
*[`pkg/testutils/sqlutils/sql_runner.go` line 250 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82393#-N3f_349Ds8wVIYI59IS:-N3f_349Ds8wVIYI59IT:b65ggc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b93bd08110cda5350eb75fe06908489fc6c4e6/pkg/testutils/sqlutils/sql_runner.go#L250)):*
> ```Go
> // using testutils.SucceedsSoon.
> func (sr *SQLRunner) CheckQueryResultsRetry(
> 	t testutils.TB, query string, expected [][]string, args ...interface{},
> ```

this doesn't feel that ergonomic to have the arguments tacked on after the expected results. do you think this is better than just using Sprintf formatting like how existing tests are doing?


<!-- Sent from Reviewable.io -->

2022-06-06 16:51 UTC, ajwerner commented
A discussion offline ocurred as to whether we should have separate metrics for sessions which contain only DML statements vs those which contain any non-DML statements. This is probably worth doing.

2022-06-15 16:11 UTC, abarganier reviewed
I agree - this metric is going to be very useful. Nice work. 

I just have one question re: the metric description.

Finally, are there any boilerplate alerting rules that you can think of for any of these new metrics? Consider [defining an alerting rule](https://github.com/cockroachdb/cockroach/blob/c030b8b6dcf61628f9e72f61848f8f9dd972fdde/pkg/util/metric/rule.go#L40-L58) to accompany some of these new metrics if so. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82393#-:-N4c6PpL5ghqLkgHyUAa:b-uk4i5f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @ajwerner, and @rafiss)

___
*[`pkg/sql/exec_util.go` line 1148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82393#-N4c3_DE2weHiH1N7tr9:-N4c3_DE2weHiH1N7trA:b-72oys2) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b93bd08110cda5350eb75fe06908489fc6c4e6/pkg/sql/exec_util.go#L1148)):*
> ```Go
> 	MetaLongRunningStatementCount = metric.Metadata{
> 		Name:        "sql.query.long_running.count",
> 		Help:        "Gauge of the number of statements which have been running for a long time",
> ```

nit: should we define what duration "a long time" is in the metric descriptions? Or do we plan on providing a way to configure these outside of just testing knobs?



_Code quote:_
```Go
running for a long time
```


<!-- Sent from Reviewable.io -->

2022-06-15 16:16 UTC, ajwerner commented
>nit: should we define what duration "a long time" is in the metric descriptions? Or do we plan on providing a way to configure these outside of just testing knobs?

Yeah, I've been thinking that a cluster setting would be good. 

I'm hesitant to put in alerting rules for the user queries. I also want to find a way to exclude things which are waiting for schema changes or other long-running jobs.

2022-06-15 16:29 UTC, awoods187 commented
@kevin-v-ngo ptal and factor into the broader user journey

2022-06-24 17:31 UTC, kevin-v-ngo commented
Thanks for this PR Andrew! Very useful. Let’s chat with Matthew when he’s back. From what I recall, he’s introducing a ‘latency_threshold’ setting for when a statement/transaction is considered ‘slow’ where we’d capture the execution of the statement for V1 of outerliers/insights. 

In V2, (‘quantile detection’) I think we’re introducing *another* setting for the ‘latency_threshold’. But i’d like to confirm with him if we can merge and reuse these settings for both V1 and V2 to avoid having 3 settings.

For this issue, the next step for the user after observing a spike in this metric is to find the actual queries that were ‘long-running’ so we’d need these queries captured including its execution context and stats. Hopefully tying into Matthew’s work? It seems like this metric should be consistent here with what is captured so perhaps this metric can be based on the latency_threshold as well?

Just seeing how we can reduce the number of cluster settings and also ensure we have all the necessary information on the long-running queries captured to help developers completely troubleshoot.

@maryliag fyi

2022-08-23 17:17 UTC, rafiss commented
Do we still want something like this?

2022-08-23 18:23 UTC, ajwerner commented
I do not know. I'll wait for @kevin-v-ngo or @maryliag to make a decision

2023-09-08 09:36 UTC, data-matt commented
@kevin-v-ngo / @rafiss , this is wanted.

2026-06-18 17:36 UTC, closed without merging