kvserver: add evaluate batch latency metrics
cockroachdb/cockroach pull request #82402
Opened 2022-06-03 13:18 UTC by koorosh

This patch introduces new metrics that measure read/write
batch evaluation latency. It should provide better visibility
what slows down batch processing (it is a small part of a bigger
project to measure e2e latency).

Release note: None

Resolves: #82341

Relates: #82200

2022-06-03 13:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/82402)
<!-- Reviewable:end -->

2022-06-07 08:29 UTC, tbg requested changes
Looks good! Just some minor code golf and then as far as I'm concerned this is good to go.

@cockroachdb/kv-prs (@nvanbenschoten)  - right now we are distinguishing between read-only and read-write request evaluation. However, "evaluation" is really always a read-only operation, so is it worth making this distinction? I could see that we would ideally want to have such a histogram per request type (i.e. one for Delete, one for Scan, etc). Should we do that instead? Histograms are expensive right now but I have a PR that lets us downsize them (see https://github.com/cockroachdb/cockroach/issues/64962#issuecomment-1144796259) so I would operate on the assumption that that will be in 22.2.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-:-N3xGOpy5d2jd_erSpXF:bvj408y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/kv/kvserver/metrics.go` line 1443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-N3xDoLV2-pT7aiy88hO:-N3xDoLV2-pT7aiy88hP:b-yww1wo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a335799084ae9a3378aafc3a9d08d84b498ed6c2/pkg/kv/kvserver/metrics.go#L1443)):*
> ```Go
> 		Unit:        metric.Unit_COUNT,
> 	}
> 	// Replica read batch evaluation
> ```

nit throughout: end comments with proper punctuation (but not inline comments `foo // no dot here`). Not going to duplicate this comment, just do a pass where you clean them all up, thanks!
___
*[`pkg/kv/kvserver/metrics.go` line 1446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-N3xFG_rEsb8EhBN5wFJ:-N3xFG_rEsb8EhBN5wFK:bs33wuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a335799084ae9a3378aafc3a9d08d84b498ed6c2/pkg/kv/kvserver/metrics.go#L1446)):*
> ```Go
> 	metaReplicaReadBatchEvaluationLatency = metric.Metadata{
> 		Name:        "kv.replica_read_batch_evaluate.latency",
> 		Help:        "Execution duration for read batch evaluation.",
> ```

Execution duration for evaluating a BatchRequest on the read-only path after latches have been acquired.

A measurement is recorded regardless of outcome (i.e. also in case of an error). If internal retries occur, each instance is recorded separately.

----

similar for writes (read-write path), with the addendum:

Note that the measurement does not include the duration for replicating the evaluated command.
___
*[`pkg/kv/kvserver/metrics.go` line 1453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-N3xDxp11nQGGqFDduEm:-N3xDxp11nQGGqFDduEn:b-krj1po) ([raw file](https://github.com/cockroachdb/cockroach/blob/a335799084ae9a3378aafc3a9d08d84b498ed6c2/pkg/kv/kvserver/metrics.go#L1453)):*
> ```Go
> 	metaReplicaWriteBatchEvaluationLatency = metric.Metadata{
> 		Name:        "kv.replica_write_batch_evaluate.latency",
> 		Help:        "Execution duration for read batch evaluation.",
> ```

write batch
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-N3xEQsz2l8wg9KCexJH:-N3xEQsz2l8wg9KCexJI:b-e2ymbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a335799084ae9a3378aafc3a9d08d84b498ed6c2/pkg/kv/kvserver/replica_evaluate.go#L172)):*
> ```Go
> 	}()
> 
> 	defer func(start time.Time) {
> ```

Looking at the callsites, I think we don't need to instrument the gossip and system config callers. Then we're left with one caller per metric, and we can lift the measurement out (i.e. do the time measurement in `executeReadOnlyBatchWithServersideRefreshes` and `evaluateWriteBatchWrapper`, respectively. We can then remove `evalBatchStats`.


<!-- Sent from Reviewable.io -->

2022-06-07 14:12 UTC, koorosh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura, @tbg, and @zachlite)

___
*[`pkg/kv/kvserver/metrics.go` line 1443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-N3xDoLV2-pT7aiy88hO:-N3yBXzI6BK8ZmQjMsX4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a335799084ae9a3378aafc3a9d08d84b498ed6c2/pkg/kv/kvserver/metrics.go#L1443)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit throughout: end comments with proper punctuation (but not inline comments `foo // no dot here`). Not going to duplicate this comment, just do a pass where you clean them all up, thanks!
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/metrics.go` line 1446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-N3xFG_rEsb8EhBN5wFJ:-N3yDCpX9Jke_DBk9fRN:bz8q8y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a335799084ae9a3378aafc3a9d08d84b498ed6c2/pkg/kv/kvserver/metrics.go#L1446)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Execution duration for evaluating a BatchRequest on the read-only path after latches have been acquired.

A measurement is recorded regardless of outcome (i.e. also in case of an error). If internal retries occur, each instance is recorded separately.

----

similar for writes (read-write path), with the addendum:

Note that the measurement does not include the duration for replicating the evaluated command.
</blockquote></details>

Done. Thanks for the extended description here!
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-N3xEQsz2l8wg9KCexJH:-N3yDi5lBO69daZJ2oYR:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a335799084ae9a3378aafc3a9d08d84b498ed6c2/pkg/kv/kvserver/replica_evaluate.go#L172)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Looking at the callsites, I think we don't need to instrument the gossip and system config callers. Then we're left with one caller per metric, and we can lift the measurement out (i.e. do the time measurement in `executeReadOnlyBatchWithServersideRefreshes` and `evaluateWriteBatchWrapper`, respectively. We can then remove `evalBatchStats`.
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2022-06-09 12:09 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> from my side, but hold off until @nvanbenschoten signs of as well on the above question.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-:-N47MRlq6Ov5ZBCtJH2g:boektsb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/kv/kvserver/metrics.go` line 1455 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-N47MAg_4b4Hfu84Bfxv:-N47MAg_4b4Hfu84Bfxw:b-ds25pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f529352457225cadedb143aba37580464971fbb/pkg/kv/kvserver/metrics.go#L1455)):*
> ```Go
> 	metaReplicaWriteBatchEvaluationLatency = metric.Metadata{
> 		Name: "kv.replica_write_batch_evaluate.latency",
> 		Help: `Execution duration for evaluating a BatchRequest on the write path after latches have been acquired.
> ```

nit: read-write path, not write path. For example, a `DeleteRange` is on the read-write path but if there's nothing to delete it will not actually do a write, so looks more like a read request.


<!-- Sent from Reviewable.io -->

2022-06-09 15:21 UTC, nvanbenschoten reviewed
I agree with the premise of your question. Evaluation is read-only so why have two different histograms? I also agree that if histograms were cheap enough, having a histogram per request type would be valuable.

In practice, I do still think this is better than having a single histogram, as there are some heavy-weight write operations like `AddSStable` and `EndTxn` which may skew any metric that they're grouped in with. As written, this at least gives us some way to compare two different classes of requests.

So my preference order would be:
1. a histogram per request type (if that's cheap enough to be feasible)
2. a read histogram and a write histogram (what we have here)
3. a single histogram

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-:-N481VKX8PpPSspeCUBs:b-85dkh2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)



<!-- Sent from Reviewable.io -->

2022-06-09 15:48 UTC, tbg commented
Thanks Nathan!
@koorosh let's merge this as-is but file an issue about possibly adding per-request evaluation histograms as well.

2022-06-09 20:00 UTC, koorosh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82402)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Santamaura, @tbg, and @zachlite)

___
*[`pkg/kv/kvserver/metrics.go` line 1455 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82402#-N47MAg_4b4Hfu84Bfxv:-N492Ujx-NbuhL6hp1__:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f529352457225cadedb143aba37580464971fbb/pkg/kv/kvserver/metrics.go#L1455)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: read-write path, not write path. For example, a `DeleteRange` is on the read-write path but if there's nothing to delete it will not actually do a write, so looks more like a read request.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-06-10 12:05 UTC, koorosh commented
bors r+

2022-06-10 13:00 UTC, merged