dev: provide a way to easily build and stage `libgeos` libraries
cockroachdb/cockroach pull request #82431
Opened 2022-06-03 21:45 UTC by rickystewart

Provide special logic to `dev build geos` which builds the libraries and
stages them in `lib/`. Also give the same power to
`dev build geos --cross`, and allow `roachtest` to find the libraries
in `artifacts/`.

Closes https://github.com/cockroachdb/cockroach/issues/80282.

Release note: None

2022-06-03 21:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/82431)
<!-- Reviewable:end -->

2022-06-03 21:45 UTC, rickystewart commented
The first commit is from #82418 here, only need to review the second.

2022-06-04 01:26 UTC, rail requested changes
`dev build --cros geos` worked like a charm!

`dev build --debug geos` gives me this:

```
./dev build --debug geos
DEBUG: getenv DEV_NO_REMOTE_CACHE
DEBUG: cat /Users/rail/Library/Caches/dev-bazel-remote/config.yml
DEBUG: cat /Users/rail/.bazelrc
$ bazel build //c-deps:libgeos
DEBUG: bazel build //c-deps:libgeos
INFO: Invocation ID: 4f8a4b60-59af-4e47-bc74-48977075642d
INFO: Analyzed target //c-deps:libgeos (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //c-deps:archived_cdep_libgeos_macos up-to-date (nothing to build)
INFO: Elapsed time: 14.907s, Critical Path: 14.47s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG: mkdir /Users/rail/go/src/github.com/cockroachdb/cockroach/bin
DEBUG: bazel info bazel-bin --color=no
DEBUG: EXEC OUT: /private/var/tmp/_bazel_rail/c160790ff936f0eb086918ae563f9ad0/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/bin
DEBUG: EXEC ERR: INFO: Invocation ID: 55a4d040-fe09-49b4-a4a9-ce330fbdee60
DEBUG: mkdir /Users/rail/go/src/github.com/cockroachdb/cockroach/lib
DEBUG: cat /private/var/tmp/_bazel_rail/c160790ff936f0eb086918ae563f9ad0/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/bin/build/bazelutil/test_force_build_cdeps.txt
ERROR: open /private/var/tmp/_bazel_rail/c160790ff936f0eb086918ae563f9ad0/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/bin/build/bazelutil/test_force_build_cdeps.txt: no such file or directory
```

After running `./dev build //build/bazelutil:test_force_build_cdeps` it worked as expected. Sounds like we need to add some deps.

2022-06-06 15:24 UTC, rickystewart commented
> After running `./dev build //build/bazelutil:test_force_build_cdeps` it worked as expected. Sounds like we need to add some deps.

Great catch, this is fixed now.

2022-06-07 14:11 UTC, rail approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82431#-:-N3yVSo7CRC2RmO6nFOF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)



<!-- Sent from Reviewable.io -->

2022-06-08 14:58 UTC, rickystewart commented
bors r=rail

2022-06-08 17:20 UTC, merged