[CRDB-14071] Remove parameter from `crdb_internal.schedule_sql_stats_compaction`
cockroachdb/cockroach pull request #82560
Opened 2022-06-07 22:48 UTC by surahman

The `crdb_internal.schedule_sql_stats_compaction` SQL function does not require the `byte` string parameter and has thus been removed. Closes #78332.

Jira issue: [CRDB-14071](https://cockroachlabs.atlassian.net/browse/CRDB-14071)

@Azhng

2022-06-07 22:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/82560)
<!-- Reviewable:end -->

2022-06-07 22:55 UTC, rafiss commented on pkg/sql/sem/builtins/builtins.go
> +			Types:      tree.ArgTypes{},
cc @cockroachdb/sql-observability is there any frontend page that calls this function? if so, we'd have  to make sure that this change  is OK to make.

2022-06-07 22:57 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82560)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @surahman)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82560#-N4-NPuB74qDhe6T5FgL):*
please update the commit message:

title should begin with `sql: removed parameter from ...`

the release note should begin with `Release note (sql change):`

the release note message is confusing right now, since it makes it seem like the function was removed.


<!-- Sent from Reviewable.io -->

2022-06-07 22:58 UTC, maryliag reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82560)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cockroachdb, @maryliag, @rafiss, and @surahman)

___
*[`pkg/sql/sem/builtins/builtins.go` line 6538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82560#-N4-LppEN6Fiyz4MLPbr-r1-6538:-N4-NYxh2a3NSeq-MjHL:b-eaa2uy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7ed58253c3b0f0de1ed0bc5f0bb63c00009ce5d/pkg/sql/sem/builtins/builtins.go#L6538)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

cc @cockroachdb/sql-observability is there any frontend page that calls this function? if so, we'd have  to make sure that this change  is OK to make.
</blockquote></details>

No, frontend pages don't make any calls to this function


<!-- Sent from Reviewable.io -->

2022-06-13 18:44 UTC, surahman commented
@rafiss all requested changes have been affected.

2022-06-15 15:50 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82560)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cockroachdb, @maryliag, @rafiss, and @surahman)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82560#-N4c2iCE6z2IGKTSkiDF):*
nit: this note would be more clear to readers if youo mentioned the function name specifically.

"The byte string parameter in the crdb_internal.schedule_sql_stats_compaction function has been removed."


<!-- Sent from Reviewable.io -->

2022-06-22 20:32 UTC, rafiss approved these changes
thanks for your contribution!

bors r+

2022-06-22 23:35 UTC, merged