fuzzystrmatch: fix crash and compatibility
cockroachdb/cockroach pull request #82761
Opened 2022-06-10 22:50 UTC by jordanlewis

Closes #82640

Release note (bug fix): fix behavior of soundex function when passed
certain unicode inputs. Previously, certain unicode inputs could result
in crashes, errors or incorrect outputs.

2022-06-10 22:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/82761)
<!-- Reviewable:end -->

2022-06-10 23:24 UTC, jordanlewis commented
cc @mgoddard

2022-06-13 19:50 UTC, rafiss requested changes

2022-06-13 19:50 UTC, rafiss commented on pkg/util/fuzzystrmatch/soundex_test.go
> +			Expected: "",
why did this one change? it looks like PG returns 000 for it (binary `d0303030`)

2022-06-13 19:50 UTC, rafiss commented on pkg/util/fuzzystrmatch/soundex_test.go
> +			Expected: "K000",
PG returns `K00` (binary `4bd03030`)

2022-06-13 19:57 UTC, jordanlewis commented
The differences you wrote don't materialize on the system I was testing on... what version are you testing on?

2022-06-15 00:40 UTC, jordanlewis commented
Here's what I get:

```

jordan=> select version();
                                                              version
-----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.3 (Ubuntu 14.3-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
(1 row)

jordan=> select soundex('🌞');
 soundex
---------

(1 row)

jordan=> select soundex('K😋');
 soundex
---------
 K000
(1 row)

jordan=>
```

It sounds like this functionality just doesn't work consistently for UTF8:

![image](https://user-images.githubusercontent.com/43821/173712362-b0c64b38-fda4-44b2-ab2f-7f4ee31e4870.png)

2022-06-15 00:41 UTC, jordanlewis commented
BTW, I get this same output even in Postgres 12 (I upgraded to Postgres 14 to see if it would repro on your version)

2022-06-21 16:22 UTC, rafiss approved these changes
ah i see thanks for looking. lgtm  then

2022-06-27 16:02 UTC, rafiss commented
bors r+

2022-06-27 17:39 UTC, merged