cli/sql: support for client-side `\o`
cockroachdb/cockroach pull request #83118
Opened 2022-06-21 10:48 UTC by knz

Release note (cli change): `cockroach sql` (and thus `cockroach demo`
too) now support the client-side commands `\o` and `\qecho` like
`psql`. The command `\o` can redirect the output of SQL queries to a
file. `\qecho` adds an arbitrary text to the current query output file.

2022-06-21 10:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/83118)
<!-- Reviewable:end -->

2022-06-21 16:17 UTC, rafiss requested changes
nice. just had  some testing comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83118#-:-N562K-z8xK0KvDGT2Vl:b-d1a87v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[`pkg/cli/interactive_tests/test_local_cmds.tcl` line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83118#-N5620oz479FTk8EKOez:-N5620oz479FTk8EKOf-:baouxkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cb297aab36ba9ba4fb1aaf3d9bb0d45b5fcf44/pkg/cli/interactive_tests/test_local_cmds.tcl#L272)):*
> ```Tcl
> send "\\o logs/query-output.txt\r"
> eexpect root@
> send "select 'hello world';\r"
> ```

does the output appear in the CLI as well (like `tee`)? if so, add a test for that

also, perhaps add a test to see how query syntax/execution errors are redirected to that file
___
*[`pkg/cli/interactive_tests/test_local_cmds.tcl` line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83118#-N561opT25uUUVmOJymJ:-N561opU6MvA-BvVVCkF:b1oqdfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cb297aab36ba9ba4fb1aaf3d9bb0d45b5fcf44/pkg/cli/interactive_tests/test_local_cmds.tcl#L283)):*
> ```Tcl
> eexpect "hello"
> eexpect root@
> end_test
> ```

nit: test `qecho` as well


<!-- Sent from Reviewable.io -->

2022-06-21 21:20 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83118)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[`pkg/cli/interactive_tests/test_local_cmds.tcl` line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83118#-N5620oz479FTk8EKOez:-N5778E372kXenh6wAog:bl6hu9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cb297aab36ba9ba4fb1aaf3d9bb0d45b5fcf44/pkg/cli/interactive_tests/test_local_cmds.tcl#L272)):*
> does the output appear in the CLI as well (like tee)?

nope

> also, perhaps add a test to see how query syntax/execution errors are redirected to that file

they're not (like in psql), but good point to test. Done.
___
*[`pkg/cli/interactive_tests/test_local_cmds.tcl` line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83118#-N561opT25uUUVmOJymJ:-N5775eX-749zb5oRC9L:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cb297aab36ba9ba4fb1aaf3d9bb0d45b5fcf44/pkg/cli/interactive_tests/test_local_cmds.tcl#L283)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: test `qecho` as well
</blockquote></details>

Good point. Done.


<!-- Sent from Reviewable.io -->

2022-06-22 11:26 UTC, knz commented
RFAL

2022-06-23 05:19 UTC, rafiss approved these changes
looks great!

> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83118#-:-N5E-5mB7tJBKFz3_5dZ:b6lqmcl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)



<!-- Sent from Reviewable.io -->

2022-06-23 10:19 UTC, knz commented
thanks!

bors r=rafiss

2022-06-23 11:32 UTC, knz commented
unrelated flake

bors r=rafiss

2022-06-23 12:49 UTC, merged