changefeedccl: reduce direct access to changefeeddetails
cockroachdb/cockroach pull request #83153
Opened 2022-06-21 20:54 UTC by HonoreDB

Directly referencing fields on the jobs proto makes
inter-version compatibility harder.
This PR takes a first step toward making most methods use
changefeedbase objects instead.

Fixes #82342.

Release note: None

2022-06-21 20:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/83153)
<!-- Reviewable:end -->

2022-06-22 14:13 UTC, miretskiy requested changes
Very nice; mostly nits.

2022-06-22 20:00 UTC, HonoreDB reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83153#-:-N5Bz-9wDOks--fgsuOO:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @livlobo and @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83153#-N571q1qEWcbrNbwFb_K-r1-27:-N5Bz1vuEhzzeYXyJF3F:b-781lva) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc01403c6050f277751c4bfa552d4b20048cfb4a/pkg/ccl/changefeedccl/changefeed.go#L27)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would mildly prefer not to call this `Changefeed`, but something more specific.
Maybe one one of `(CDC|Feed|Changefeed)(Config|Cfg)`?
</blockquote></details>

Changed to ChangefeedConfig.
___
*[`pkg/ccl/changefeedccl/changefeed.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83153#-N571q1qEWcbrNbwFb_K-r1-44:-N5Bz5ih4Xg7_qBvu2Sq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc01403c6050f277751c4bfa552d4b20048cfb4a/pkg/ccl/changefeedccl/changefeed.go#L44)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Function comment por favore.
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/sink.go` line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83153#-N571q1qEWcbrNbwFb_Z-r1-393:-N5Bz8KT5Jpl4Hq4k3D2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc01403c6050f277751c4bfa552d4b20048cfb4a/pkg/ccl/changefeedccl/sink.go#L393)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

a bit sad that we have to alloc new array every time...
Do you think we can/should special case when we have nil components?

</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/changefeedbase/target.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83153#-N5AWFzMww1sTlCqefPB-r1-24:-N5BzKiY70gW93SpqQbY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc01403c6050f277751c4bfa552d4b20048cfb4a/pkg/ccl/changefeedccl/changefeedbase/target.go#L24)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

lint would probably complain about lack of comments on exported symbols.
(even if it won't, we probably should have those).
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/changefeedbase/target.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83153#-N5AWFzMww1sTlCqefPB-r1-26:-N5BzLhgDFI27xo_3EPj:buq5pxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc01403c6050f277751c4bfa552d4b20048cfb4a/pkg/ccl/changefeedccl/changefeedbase/target.go#L26)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we imagine having methods on `Targets`? If not, perhaps we should use `[]Target` at the call sites?
</blockquote></details>

I am imagining having methods on Targets in a future PR, yeah, I think probably the thing to do is consolidate it and WatchedTables into one type that you can efficiently access in different ways (EachTarget, EachTable, FindStatementTimeNameByID).


<!-- Sent from Reviewable.io -->

2022-06-22 20:03 UTC, miretskiy approved these changes

2022-06-24 13:27 UTC, HonoreDB commented
bors retry

2022-06-24 15:13 UTC, merged