sql: allow foreign key to reference crdb_region column in REGIONAL BY ROW
cockroachdb/cockroach pull request #83375
Opened 2022-06-25 13:09 UTC by rytaft

This commit loosens the restrictions on foreign key references to allow
referencing `crdb_region` and other implicit partitioning columns used by
`PARTITION ALL BY` tables. There is no technical reason why such references
should be disallowed, so this commit simply removes the restriction.

Fixes #74244

Release note (sql change): Foreign keys can now reference the `crdb_region`
column in `REGIONAL BY ROW` tables even if `crdb_region` is not explicitly part
of a `UNIQUE` constraint. This is possible since `crdb_region` is implicitly
included in every index on `REGIONAL BY ROW` tables as the partitioning key.
(This applies to whichever column is used as the partitioning column, in
case a different name is used via `REGIONAL BY ROW AS`.)

2022-06-25 13:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/83375)
<!-- Reviewable:end -->

2022-06-25 13:12 UTC, rytaft reviewed
cc @andy-kimball 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N5PzZC-739EEiusjpV6:bbj0wwo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)



<!-- Sent from Reviewable.io -->

2022-06-26 06:42 UTC, andy-kimball reviewed
Great to see this! Will this be back-portable it to 22.1?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N5Tjm929oefbSXhyrbP:bvr3hq3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)



<!-- Sent from Reviewable.io -->

2022-06-28 01:23 UTC, rytaft commented
I think that should be possible 





<!-- Sent from Reviewable.io -->

2022-06-28 02:58 UTC, otan approved these changes

2022-06-28 10:50 UTC, postamar requested changes
Just one small request on my part, otherwise looks good to me.

2022-06-28 10:51 UTC, postamar commented on pkg/sql/catalog/descpb/index.go
> +			desc.keyColumnIDsWithoutShardColumn().PermutationOf(referencedColIDs))
There seems to be some redundancy here, in that the columns IDs returned by `keyColumnIDsWithoutShardColumn` always form a superset of `explicitColumnIDsWithoutShardColumn`. It seems that what we really want to check is that the referenced column IDs minus the shard and implicit columns equals the key column IDs. This makes referencing any implicit columns possible but not required. Of course right now there's only at most one implicit column but this change seems worth making if only to clarify our intentions in the code.

I'm not sure why the shard column is treated specially but perhaps I'm unaware of something. I don't see why it should be special but I don't have a strong opinion on this matter.

2022-06-29 13:46 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N5jhXty04riDCtdmq9R:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @postamar)

___
*[`pkg/sql/catalog/descpb/index.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-N5PympZ1TKJddCEkPEQ-r1-106:-N5jgzqt1azkFdkJaV3d:b-f3sa1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7602c77c64b54f416f4e5677584aee3b81944d2e/pkg/sql/catalog/descpb/index.go#L106)):*
> I'm not sure why the shard column is treated specially but perhaps I'm unaware of something. I don't see why it should be special but I don't have a strong opinion on this matter.

The shard column is computed, so I believe it's not allowed to be an FK because an update to the referenced table can't cascade to a computed column.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 2955 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-N5jgZPp6S4_Y3z7QRPz:-N5jgZPp6S4_Y3z7QRQ-:b-k5ibo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7602c77c64b54f416f4e5677584aee3b81944d2e/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L2955)):*
> ```
> RESET vectorize
> 
> subtest foreign_keys
> ```

Might be good to add query plan tests for FK checks and cascades to make sure they are efficient.


<!-- Sent from Reviewable.io -->

2022-06-29 16:18 UTC, postamar commented
> The shard column is computed, so I believe it's not allowed to be an FK because an update to the referenced table can't cascade to a computed column.

Makes sense. Thanks!

2022-07-02 21:00 UTC, rytaft reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N6-eHd--zYRPboV-0wC:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @nvanbenschoten, and @postamar)

___
*[`pkg/sql/catalog/descpb/index.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-N5PympZ1TKJddCEkPEQ-r1-106:-N6-cGB6ATwiBfwMcvjU:b-t7vkfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7602c77c64b54f416f4e5677584aee3b81944d2e/pkg/sql/catalog/descpb/index.go#L106)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> I'm not sure why the shard column is treated specially but perhaps I'm unaware of something. I don't see why it should be special but I don't have a strong opinion on this matter.

The shard column is computed, so I believe it's not allowed to be an FK because an update to the referenced table can't cascade to a computed column.
</blockquote></details>

I tried to remove some of the redundancy... let me know if you think this is better now.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 2955 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-N5jgZPp6S4_Y3z7QRPz:-N6-eFkx73ljVHFw_OjY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7602c77c64b54f416f4e5677584aee3b81944d2e/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L2955)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Might be good to add query plan tests for FK checks and cascades to make sure they are efficient.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-04 10:19 UTC, postamar approved these changes

2022-07-05 13:55 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N6DdKFX7KudUwXItIya:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @postamar)



<!-- Sent from Reviewable.io -->

2022-07-05 14:06 UTC, rytaft reviewed
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83375#-:-N6Df9GG94m2p-uj4sXj:b-voiyyw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @postamar)



<!-- Sent from Reviewable.io -->

2022-07-05 15:20 UTC, merged