release-21.2: opt: use expr and input fds to remap index join columns
cockroachdb/cockroach pull request #83550
Opened 2022-06-28 21:55 UTC by mgartner

Backport 1/1 commits from #81844.

/cc @cockroachdb/release

---

Before this change index joins would use their own FDs to remap input to
output columns if there was a required ordering. This could miss some
cases where the index joins' FDs were generated from another expression
in the memo group and did not include FDs from its own input, such as
equivalent columns only found the index joins' input. This change
modifies the FDs used for remapping columns to include both the index
join and input FDs.

Fixes: #81649

Release note (bug fix): Index joins now consider functional dependencies
from their input when determining equivalent columns instead of
returning an internal error.

---

Release justification: This fixes a minor bug in the optimizer.

2022-06-28 21:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/83550)
<!-- Reviewable:end -->

2022-06-28 22:45 UTC, msirek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83550#-:-N5gUOl64q8xAgv3abt1:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)



<!-- Sent from Reviewable.io -->

2022-06-29 21:18 UTC, rharding6373 requested changes, later dismissed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83550)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/xform/testdata/rules/join` line 10146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83550#-N5lJKx3-J8jcFBpZEdG:-N5lJKx435tsMAJ85O2X:b-q3gku3) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d3e8450f76c91e0a1eaa662f97aaa2f68e478c/pkg/sql/opt/xform/testdata/rules/join#L10146)):*
> ```
> 
> opt
> SELECT col2 FROM t81649@t81649_col3_col1_key ORDER BY col0 ASC, col3 ASC LIMIT 2;
> ```

I guess index naming conventions are different in 21.2. Should the syntax above be `UNIQUE INDEX t81649_col3_col1_key...`?


<!-- Sent from Reviewable.io -->

2022-07-01 14:25 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83550)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373)

___
*[`pkg/sql/opt/xform/testdata/rules/join` line 10146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83550#-N5lJKx3-J8jcFBpZEdG:-N5u8ZbZ9POPb0qblJms:bm2ril4) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d3e8450f76c91e0a1eaa662f97aaa2f68e478c/pkg/sql/opt/xform/testdata/rules/join#L10146)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I guess index naming conventions are different in 21.2. Should the syntax above be `UNIQUE INDEX t81649_col3_col1_key...`?
</blockquote></details>

Good catch. The test catalog previous named all secondary indexes "secondary" I think. I used your suggestion to use `UNIQUE INDEX` and gave the index a specific name.


<!-- Sent from Reviewable.io -->

2022-07-05 20:21 UTC, merged