sql: fix prepared statement query summary
cockroachdb/cockroach pull request #83673
Opened 2022-06-30 18:49 UTC by ericharmeling

This commit sets the StmtSummary metadata field for prepared
statements to the StatementSummary value in the prepared statement
metadata for prepared statements at execution.

Fixes #79152.

Release note (bug fix): Previously, the querySummary metadata field in
the crdb_internal.statement_statistics table was inconsistent with the
query metadata field for executed prepared statements. These fields
are now consistent for prepared statements.

2022-06-30 18:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/83673)
<!-- Reviewable:end -->

2022-06-30 19:55 UTC, maryliag requested changes
Can you add tests to confirm the correct behaviour?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83673#-:-N5qAVYT4BhQO5gf0lke:b-cw56yw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)



<!-- Sent from Reviewable.io -->

2022-07-01 16:30 UTC, ericharmeling reviewed
Done!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83673#-:-N5uaLhn0rN1c2eNiQs7:b-896fja)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2022-07-04 13:57 UTC, maryliag approved these changes
Awesome! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83673#-:-N68V7c83DVYOdxjUeFv:b-i581jd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)



<!-- Sent from Reviewable.io -->

2022-07-05 13:33 UTC, ericharmeling commented
bors r-

2022-07-05 19:31 UTC, ericharmeling commented
bors r+

2022-07-06 15:14 UTC, ericharmeling commented
bors retry

2022-07-06 22:31 UTC, ericharmeling commented
bors r+

2022-07-07 01:54 UTC, yuzefovich commented
Looks like this PR might be flaky - the merge failed twice on `TestPrepareStatisticsMetadata` and this PR seems related.

bors r-

2022-07-07 16:44 UTC, ericharmeling commented
> Looks like this PR might be flaky - the merge failed twice on `TestPrepareStatisticsMetadata` and this PR seems related.

😖 you're right. I actually just built master and could not repro the behavior shown in https://github.com/cockroachdb/cockroach/issues/79152 (the issue this PR fixes). It looks like something was merged in the last week that broke `querySummary` for prepared statements altogether. I just checked out the last commit from June 29 (https://github.com/cockroachdb/cockroach/commit/02dcb3816c4148ee15318a614901b266f1b8ae34) and was able to repro. I'm going to do some manual divide-and-conquer until I locate the culprit.

2022-07-07 18:42 UTC, ericharmeling commented
> It looks like something was merged in the last week that broke querySummary for prepared statements altogether.

Well this isn't entirely true. Just that the `querySummary` field isn't being populated for prepared statements in `crdb_internal.cluster_statement_statistics` (and therefore in `crdb_internal.statement_statistics.metadata`).

Looks like it's one of the commits in this merge: https://github.com/cockroachdb/cockroach/commit/ce1b42bd341cc5f87357ecf82027b3dd5a3e88c1#

2022-07-07 20:49 UTC, ericharmeling commented
The behavior that this PR seeks to fix has changed.

See https://github.com/cockroachdb/cockroach/issues/79152#issuecomment-1178209482.

2022-07-12 15:51 UTC, ericharmeling commented
Rebasing on master to include https://github.com/cockroachdb/cockroach/pull/84170. Note that https://github.com/cockroachdb/cockroach/pull/84170 has *not* been backported, so we probably shouldn't backport this PR either.

2022-07-12 19:56 UTC, ericharmeling commented
Looks like the test failure here (Example_demo_locality) is flaky

2022-07-12 19:56 UTC, ericharmeling commented
bors r+

2022-07-12 22:15 UTC, merged

2022-09-08 13:49 UTC, maryliag commented
@ericharmeling can you backport this to 22.1?