build/teamcity: add pebble crossversion metamorphic nightly
cockroachdb/cockroach pull request #83681
Opened 2022-06-30 21:18 UTC by jbowens

Add scripts for a new nightly that runs Pebble metamorphic tests across SHAs
from multiple release branches, passing data directories from one release to
the next. This nightly improves our test coverage of upgrade paths and
compatibility with databases constructed by previous versions.

The entrypoint script interprets each argument as a Pebble branch name. For
each provided branch, it retrieves the Pebble SHA and builds the metamorphic
package's test binary at that SHA.

The built metamorphic test binaries are passed through flags to the
crossversion test.

Close #82544.

Release note: none
Release justification: Non-production code changes

2022-06-30 21:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/83681)
<!-- Reviewable:end -->

2022-07-01 18:33 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83681)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5v0Wj25fksqO4kjKC_:-N5v0Wj25fksqO4kjKCa:bwf5ty8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7cc30a4480f14451ec3dc02201445f266ecc6d8/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh#L27)):*
> ```Shell
> # prefix each argument with `--test_arg `, so that we can instruct bazel
> # to set the arguments appropriately.
> test_args=($(printf "--test_arg=%s\n" "$@"))
> ```

This needs work. I'm not sure how to pass the arguments appropriately to bazel. I have no bash foo.
___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5v0m6C9xAYSjj3JP-V:-N5v0m6C9xAYSjj3JP-W:b-fwfa6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7cc30a4480f14451ec3dc02201445f266ecc6d8/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh#L38)):*
> ```Shell
>                                       $test_args \
>                                       --test_output streamed \
>     || exit_status=$?
> ```

Omitting the test args altogether, there's another issue when invoking the test. I'm not sure if that's coming from bazel, or the Go test itself (which does create temp dirs, but I would expect them to have a path that includes the test name):

```
[12:22:46]ERROR: /home/agent/.cache/bazel/_bazel_agent/40f5e2a2e18a7cdb4cd075f919d8072b/external/com_github_cockroachdb_pebble/internal/metamorphic/crossversion/BUILD.bazel:3:8: Testing @com_github_cockroachdb_pebble//internal/metamorphic/crossversion:crossversion_test failed: unexpected I/O exception: /artifacts/tmp/_tmp/6a10f69c366156a5cd835533979d6023 (No such file or directory)
```


<!-- Sent from Reviewable.io -->

2022-07-01 18:34 UTC, jbowens reviewed
This isn't working yet, but a review could be helpful to work past some of issues.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-:-N5v1fsnCT_H33WYwLrm:bi10m24)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-07-05 16:58 UTC, rickystewart requested changes

2022-07-05 16:58 UTC, rickystewart commented on build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh
> +mv $BAZEL_BIN/external/com_github_cockroachdb_pebble/internal/metamorphic/metamorphic_test_/metamorphic_test \
Instead, `cp` from the original location to the destination. Also you should `chmod a+w` the destination file.

2022-07-05 16:58 UTC, rickystewart commented on build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion.sh
> +    SHA=$($dir/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh "$branch" "bin")
The build will also output a lot of stuff to `stdout`. You can address this by piping to `tail` like:

    SHA=$("$dir/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh" "$branch" "bin" | tail -n1)

2022-07-05 16:58 UTC, rickystewart commented on build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion.sh
> +                               run_bazel
You need a `\` after every line or else `bash` will think the command is ended. Just indenting is not sufficient.

2022-07-05 16:58 UTC, rickystewart commented on build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh
> +test_args=($(printf "--test_arg=%s\n" "$@"))
You've got a couple options.

```
echo $@ | python3 -c "import sys; print(' '.join(['--test_arg=' + word.strip() for word in sys.stdin.read().split(' ')]))"
# OR
echo $@ | sed 's/[^ ]* */--test_arg=&/g'
```

2022-09-07 20:09 UTC, jbowens reviewed
thanks for the help @rickystewart.

Is there a trick to making these prebuilt binaries available to the final sandbox?

```
[Step 1/1] --- FAIL: TestMetaCrossVersion (0.00s)
[16:01:27][Step 1/1]     crossversion_test.go:72: Test directory: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/826/execroot/com_github_cockroachdb_cockroach/_tmp/366cdd6e86440d4e9e9c98d28c5c6592/TestMetaCrossVersion2375011969/001
[16:01:27][Step 1/1]     crossversion_test.go:73: Reproduction:
[16:01:27][Step 1/1]           go test -v -run 'TestMetaCrossVersion' --seed 1662580887395790294 --factor 10 --version crl-release-21.2,36e8e9214699,./bin/36e8e9214699.test --version crl-release-22.1,a78491c0086f,./bin/a78491c0086f.test --version master,ade651d00072,./bin/ade651d00072.test
[16:01:27][Step 1/1]         
[16:01:27][Step 1/1]     crossversion_test.go:83: stat ./bin/36e8e9214699.test: no such file or directory
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-:-NBOZBGZ-E01goVQ7SQR:bl610u4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5qTpzFMbSser6ve2se-r1-30:-NBOFae0Ay1u6pU3ftNx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7cc30a4480f14451ec3dc02201445f266ecc6d8/build/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh#L30)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

Instead, `cp` from the original location to the destination. Also you should `chmod a+w` the destination file.
</blockquote></details>

Done.
___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion.sh` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5qTpzFMbSser6ve2sf-r1-17:-NBOFftZ83IkBBlUarju:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7cc30a4480f14451ec3dc02201445f266ecc6d8/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion.sh#L17)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

This build looks unnecessary.
</blockquote></details>

Done.
___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion.sh` line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5qTpzFMbSser6ve2sf-r1-24:-NBOFp93EgOPVPASpwwV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7cc30a4480f14451ec3dc02201445f266ecc6d8/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion.sh#L24)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

The build will also output a lot of stuff to `stdout`. You can address this by piping to `tail` like:

    SHA=$("$dir/teamcity/cockroach/nightlies/pebble_nightly_build_test_binary.sh" "$branch" "bin" | tail -n1)
</blockquote></details>

Done.
___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion.sh` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5qTpzFMbSser6ve2sf-r1-33:-NBOGHurDRFiC7EtEvto:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7cc30a4480f14451ec3dc02201445f266ecc6d8/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion.sh#L33)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

You need a `\` after every line or else `bash` will think the command is ended. Just indenting is not sufficient.
</blockquote></details>

Done.
___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5qfdSTV7NmrxgLf1mn-r1-27:-NBOGCtA2nWAcRCT4Vr6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7cc30a4480f14451ec3dc02201445f266ecc6d8/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh#L27)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

You've got a couple options.

```
echo $@ | python3 -c "import sys; print(' '.join(['--test_arg=' + word.strip() for word in sys.stdin.read().split(' ')]))"
# OR
echo $@ | sed 's/[^ ]* */--test_arg=&/g'
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-08 22:21 UTC, rickystewart commented
> Is there a trick to making these prebuilt binaries available to the final sandbox?

I would use absolute paths rather than relative (like `/full/path/to/.../bin/file.test` rather than `./bin/file.test`). The test will run in a different working directory so if you use a relative path then it'll look in the current directory and get confused so it can't find it.

2022-09-12 17:20 UTC, jbowens reviewed
hrm, is there anything special that must done to make it available to the sandbox? or am I writing the binaries to a location that'll get blown away when running a new bazel sandbox?

```
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/36e8e9214699.test
  File: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/36e8e9214699.test
  Size: 11186821  	Blocks: 21856      IO Block: 4096   regular file
Device: 801h/2049d	Inode: 1563023     Links: 1
Access: (0777/-rwxrwxrwx)  Uid: ( 1024/   agent)   Gid: ( 1025/   agent)
Access: 2022-09-09 21:48:55.575816568 +0000
Modify: 2022-09-09 21:48:55.583817079 +0000
Change: 2022-09-09 21:48:55.583817079 +0000
 Birth: -

--- FAIL: TestMetaCrossVersion (0.00s)
    crossversion_test.go:72: Test directory: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/826/execroot/com_github_cockroachdb_cockroach/_tmp/366cdd6e86440d4e9e9c98d28c5c6592/TestMetaCrossVersion2024174597/001
    crossversion_test.go:73: Reproduction:
          go test -v -run 'TestMetaCrossVersion' --seed 1662760403342326388 --factor 10 --version crl-release-21.2,36e8e9214699,/home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/36e8e9214699.test --version crl-release-22.1,a78491c0086f,/home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/a78491c0086f.test --version master,20a40b515be9,/home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/20a40b515be9.test

    crossversion_test.go:83: stat /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/36e8e9214699.test: no such file or directory
FAIL
2022/09/09 21:53:23 Test @com_github_cockroachdb_pebble//internal/metamorphic/crossversion:crossversion_test exited with error code 1
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-:-NBZ93Su8BybzL-qSTK9:biolinw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2022-09-27 14:55 UTC, jbowens commented
@rickystewart any ideas on what could be going on?

2022-10-06 22:17 UTC, rickystewart commented
> @rickystewart any ideas on what could be going on?

Note the test itself is running in a Docker container and doesn't have direct access to the contents of the host filesystem. To make the binary available to the Docker container, you can mount `bin` (or `bin/$SHA.test`) into the Docker container and refer to it by the proper path from within the container.

2022-10-12 22:01 UTC, jbowens reviewed
Sorry for my bazel ignorance here. I've got the binary directory mounted into the Docker container, mounted under  the path `/test-bin` with 0777 perms, but the Go process receives a permission denied error when exec-ing it. Do I need to explicitly lift the binary into the bazel sandbox somehow?

```
[Step 1/1]     crossversion_test.go:162: Metamorphic test failed: fork/exec /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/826/execroot/com_github_cockroachdb_cockroach/_tmp/366cdd6e86440d4e9e9c98d28c5c6592/TestMetaCrossVersion3977711670/002/1665608991536476114/36e8e921_1665608991536476114_000/36e8e9214699.test: permission denied
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-:-NEDBaQK1FrOh-zJbDQ_:b6f6ah6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2022-10-14 16:09 UTC, jbowens reviewed
It was finding the correct binaries in `/test-bin/`, otherwise it wouldn't have errored with a permission denied. The test links the binary into the current working directory (eg, `/home/roach.cache/bazel/...`) before executing them. I believe this was the problem. Since the run_bazel command launches a new docker container, the relevant binary directory needed to be mounted. Since the binary directory was on a different volume, the test copied (instead of linking) the binaries into the test directory. The copied binaries, I believe, lacked the executable bit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-:-NEI3HSa-mLaPab5B-oG:b-s5yxv1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2022-10-17 17:19 UTC, rickystewart requested changes
@jbowens Are runs succeeding now or do you need further help?

2022-10-17 17:19 UTC, rickystewart commented on build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh
> +bazel build //pkg/cmd/bazci //pkg/cmd/github-post //pkg/cmd/testfilter --config=ci
You can remove `//pkg/cmd/github-post //pkg/cmd/testfilter`.

2022-10-17 17:19 UTC, rickystewart commented on build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh
> +$BAZEL_BIN/pkg/cmd/bazci/bazci_/bazci test \
`bazci`'s command-line has changed a bit,  but luckily it makes this invocation simpler.

Please rebase and make the following change here:

```
$BAZEL_BIN/pkg/cmd/bazci/bazci_/bazci --process_test_failures -- \
    test @com_github_cockroachdb_pebble//internal/metamorphic/crossversion:crossversion_test
    ...
```

2022-10-17 17:19 UTC, rickystewart commented on build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh
> +source "$dir/teamcity-bazel-support.sh"  # For process_test_json
I don't think you need this `source` any more.

2022-10-17 17:19 UTC, rickystewart commented on build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh
> +BAZEL_SUPPORT_EXTRA_GITHUB_POST_ARGS=--formatter=pebble-metamorphic process_test_json \
All of this (lines 42-45) can be removed now that `bazci` has been improved in #87938.

2022-10-20 20:54 UTC, rickystewart approved these changes
Need to rebase

2022-10-20 20:54 UTC, rickystewart approved these changes
Need to rebase

2022-10-21 20:32 UTC, jbowens reviewed
Thanks for your help, Ricky. I still have a remaining obstacle, where the test doesn't find the artifacts subprocesses create in the right place. That doesn't happen locally or on my gceworker when run with [this script](https://github.com/cockroachdb/pebble/blob/master/scripts/run-crossversion-meta.sh). Not sure what's going on, but @itsbilal and I are trying to figure it out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-:-NEwE-HQAf59lLVjqXDq:bhol7n3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh` line 4 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5qfdSTV7NmrxgLf1mn-r9-4:-NEh0GMQ9PFn2nvRZ55i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb19c53c55f10e4263109f9b07aa8c6cf39b6b0f/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh#L4)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

I don't think you need this `source` any more.
</blockquote></details>

Done.
___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh` line 17 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5qfdSTV7NmrxgLf1mn-r9-17:-NEh0LuUEJwfeb8ft2d7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb19c53c55f10e4263109f9b07aa8c6cf39b6b0f/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh#L17)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

You can remove `//pkg/cmd/github-post //pkg/cmd/testfilter`.
</blockquote></details>

Done.
___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh` line 32 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5qfdSTV7NmrxgLf1mn-r9-32:-NEh16rq7jNFAEN-nqfA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb19c53c55f10e4263109f9b07aa8c6cf39b6b0f/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh#L32)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

`bazci`'s command-line has changed a bit,  but luckily it makes this invocation simpler.

Please rebase and make the following change here:

```
$BAZEL_BIN/pkg/cmd/bazci/bazci_/bazci --process_test_failures -- \
    test @com_github_cockroachdb_pebble//internal/metamorphic/crossversion:crossversion_test
    ...
```
</blockquote></details>

Done.
___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh` line 42 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5qfdSTV7NmrxgLf1mn-r9-42:-NEh17ew34J33557IntJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb19c53c55f10e4263109f9b07aa8c6cf39b6b0f/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh#L42)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

All of this (lines 42-45) can be removed now that `bazci` has been improved in #87938.
</blockquote></details>

Done.
___
*[`build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh` line 30 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-N5qfdSTV7NmrxgLf1mn-r11-30:-NEwEJMU2VfQh8IfDztX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4def7b2818b788dc0fca281405cde4ff8994b6b0/build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_crossversion_impl.sh#L30)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

I don't think this `exit_status` stuff is necessary any more -- if the process fails, it'll just fail with the exit code, which is what you want.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-21 20:48 UTC, rickystewart commented
> Thanks for your help, Ricky. I still have a remaining obstacle, where the test doesn't find the artifacts subprocesses create in the right place. That doesn't happen locally or on my gceworker when run with [this script](https://github.com/cockroachdb/pebble/blob/master/scripts/run-crossversion-meta.sh?rgh-link-date=2022-10-21T20%3A32%3A13Z). Not sure what's going on, but @itsbilal and I are trying to figure it out.

OK, I can try to help out if you provide more info here.

2022-10-21 21:11 UTC, jbowens reviewed
Thanks. The test we're running is implemented [here](https://github.com/cockroachdb/pebble/blob/master/internal/metamorphic/crossversion/crossversion_test.go), which invokes [another test](https://github.com/cockroachdb/pebble/blob/master/internal/metamorphic/meta_test.go) on each of the prebuilt test binaries.

In [this section](https://github.com/cockroachdb/pebble/blob/f34af25a01873c9cf027e53147754e96ec8b2b53/internal/metamorphic/crossversion/crossversion_test.go#L178-L193), we run the sub-test using one of the prebuilt test binaries. When we run the binary, we set its pwd to `r.dir` which is basically `(*testing.T).TempDir()` suffixed with `<seed>/<an ID for the run>`. The expectation is that the subtest will create a nested subdirectory within its pwd prefixed like `_meta/<ID>/...`. In CI running against this script, we're failing to find the `_meta` directory after the exec'd subprocess ends (eg, [failed build](https://teamcity.cockroachdb.com/viewLog.html?buildId=7052948&buildTypeId=Cockroach_Nightlies_NightlyPebbleMetamorphicCrossversion&tab=buildLog&branch_Cockroach_Nightlies=refs%2Fpull%2F83681%2Fhead)).

We've been using this [scripts/run-crossversion-meta.sh](https://github.com/cockroachdb/pebble/blob/master/scripts/run-crossversion-meta.sh) script for iterating on this test, which finds the appropriate `_meta` directory.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-:-NEwKAcS3SIRk8Msh0lC:b-shd1yp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2022-10-25 15:00 UTC, jbowens reviewed
Looks like after rebasing, the test is failing to start:

```
[10:56:43][Step 1/1] + /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/cmd/bazci/bazci_/bazci --process_test_failures -- test @com_github_cockroachdb_pebble//internal/metamorphic/crossversion:crossversion_test --test_timeout=25200 '--test_filter=TestMetaCrossVersion$' --define gotags=bazel,invariants --test_env=GO_TEST_JSON_OUTPUT_FILE=/go/src/github.com/cockroachdb/cockroach/artifacts/test.json.txt --run_under '@com_github_cockroachdb_stress//:stress -bazel -shardable-artifacts '\''GO_TEST_JSON_OUTPUT_FILE=cat,XML_OUTPUT_FILE=/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/cmd/bazci/bazci_/bazci merge-test-xmls'\'' -maxtime 6h -maxfails 1 -stderr -p 1' --test_arg=-test.v --test_arg=-version --test_arg=crl-release-21.2,09f3473dd72a,/test-bin/09f3473dd72a.test --test_output streamed
[10:56:43][Step 1/1] running bazel w/ args:  test @com_github_cockroachdb_pebble//internal/metamorphic/crossversion:crossversion_test --test_timeout=25200 '--test_filter=TestMetaCrossVersion$' --define gotags=bazel,invariants --test_env=GO_TEST_JSON_OUTPUT_FILE=/go/src/github.com/cockroachdb/cockroach/artifacts/test.json.txt --run_under '@com_github_cockroachdb_stress//:stress -bazel -shardable-artifacts '"'"'GO_TEST_JSON_OUTPUT_FILE=cat,XML_OUTPUT_FILE=/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/cmd/bazci/bazci_/bazci merge-test-xmls'"'"' -maxtime 6h -maxfails 1 -stderr -p 1' --test_arg=-test.v --test_arg=-version --test_arg=crl-release-21.2,09f3473dd72a,/test-bin/09f3473dd72a.test --test_output streamed --bes_backend=grpc://127.0.0.1:8998
[10:56:43][Step 1/1] WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
[10:56:43][Step 1/1] Loading: 
[10:56:43][Step 1/1] Loading: 0 packages loaded
[10:56:44][Step 1/1] ERROR: Skipping '@com_github_cockroachdb_pebble//internal/metamorphic/crossversion:crossversion_test': no such package '@com_github_cockroachdb_pebble//internal/metamorphic/crossversion': BUILD file not found in directory 'internal/metamorphic/crossversion' of external repository @com_github_cockroachdb_pebble. Add a BUILD file to a directory to mark it as a package.
[10:56:44][Step 1/1] ERROR: no such package '@com_github_cockroachdb_pebble//internal/metamorphic/crossversion': BUILD file not found in directory 'internal/metamorphic/crossversion' of external repository @com_github_cockroachdb_pebble. Add a BUILD file to a directory to mark it as a package.
[10:56:44][Step 1/1] INFO: Elapsed time: 0.994s
[10:56:44][Step 1/1] INFO: 0 processes.
[10:56:44][Step 1/1] FAILED: Build did NOT complete successfully (0 packages loaded)
[10:56:44][Step 1/1] ERROR: Couldn't start the build. Unable to run tests
[10:56:44][Step 1/1] FAILED: Build did NOT complete successfully (0 packages loaded)
[10:56:44][Step 1/1] FAILED: Build did NOT complete successfully (0 packages loaded)
[10:56:44][Step 1/1] got error exit status 1 from bazel run
[10:56:44][Step 1/1] running find w/ args:  -name /artifacts EMERGENCY_BALLAST -delete
[10:56:44][Step 1/1] Failed with err exit status 1
[10:56:44][Step 1/1] StdErr: find: paths must precede expression: `EMERGENCY_BALLAST'
[10:56:44][Step 1/1] failed to process go test json output - open : no such file or directory
[10:56:44][Step 1/1] ERROR: exit status 1
[10:56:46][Step 1/1] Process exited with code 1
[10:56:46][Step 1/1] Process exited with code 1 (Step: Run teamcity-trigger (Command Line))
[10:56:46][Step 1/1] Step Run teamcity-trigger (Command Line) failed
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-:-NFEe0rV5KQ-8fZbD0KB:bm01eww)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2022-10-25 18:35 UTC, rickystewart approved these changes
For the `find` error message we have https://github.com/cockroachdb/cockroach/pull/90633 but it's not the root cause. I'm not really understanding the error you're getting because that binary definitely exists - you can run `bazel build @com_github_cockroachdb_pebble//internal/metamorphic/crossversion:crossversion_test` yourself to confirm.

I'd say rebase atop #90633 and address the little comments I have and let me know if you're still seeing this problem.

2022-10-25 22:44 UTC, jbowens commented
same deal post-rebase :/

2022-10-26 17:31 UTC, rickystewart commented
@jbowens OK, I looked at your logs. It looks like you're trying to run the test as of version `crl-release-21.2`, but that `internal/metamorphic/crossversion` directory doesn't exist as of that old version of the code.

2022-10-27 14:48 UTC, jbowens commented
Ah, thanks, I had removed the latter versions to try to reduce iteration time [is there a way to test this script outside the context of TeamCity?] without realizing that `pebble_nightly_build_test_binary.sh`'s `DEPS.bzl` changes would leak from that script invocation. The intention was that the crossversion test should only be invoked on the branch the nightly is running against.

Now I'm back at [this aforementioned obstacle](https://github.com/cockroachdb/cockroach/pull/83681#pullrequestreview-1151558529).

2022-10-27 18:39 UTC, jbowens reviewed
@rickystewart Do you understand why when the crossversion metamorphic test invokes one of the metamorphic test binaries, the working directory is not set to the working directory that the crossversion metamorphic test set when it exec'd the binary?

We appear to be getting the current working directory:
```
/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/1021/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/external/com_github_cockroachdb_pebble/internal/metamorphic/crossversion/crossversion_test_/crossversion_test.runfiles/com_github_cockroachdb_cockroach/external/com_github_cockroachdb_pebble/internal/metamorphic
```
We expected the subprocess to run within the working directory:
```
/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/1021/execroot/com_github_cockroachdb_cockroach/_tmp/366cdd6e86440d4e9e9c98d28c5c6592/TestMetaCrossVersion1870471968/001/1666895367139655616/1b644125_1666895367139655616_000
```

This discrepancy results in the crossversion metamorphic test being unable to discover the subprocess's artifacts.
https://teamcity.cockroachdb.com/viewLog.html?buildId=7176715&buildTypeId=Cockroach_Nightlies_NightlyPebbleMetamorphicCrossversion&tab=buildLog&_focus=5536

(NB: This non-bazel approach works fine: #90766)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83681#-:-NFPi2tA6gpbbqEKhbea:b-hjcxb6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2022-10-28 20:50 UTC, jbowens commented
TFTR!

Going to merge as cockroachdb/pebble#2072 worked around the working directory issue.

bors r=rickystewart

2022-10-28 21:39 UTC, nicktrav commented
Nice! Thanks all for the effort here with this peregrination.

2022-10-29 00:26 UTC, merged