pgwire: Parse, Describe, and Bind should fail in an aborted txn
cockroachdb/cockroach pull request #84177
Opened 2022-07-11 14:47 UTC by rafiss

fixes https://github.com/cockroachdb/cockroach/issues/84140

Release note (bug fix): The Parse, Bind, and Execute pgwire commands
now return an error if they are used during an aborted transaction.

2022-07-11 14:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/84177)
<!-- Reviewable:end -->

2022-07-11 15:04 UTC, ZhouXing19 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84177)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[`pkg/sql/pgwire/testdata/pgtest/aborted_txn` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84177#-N6hlP9e3AnVlg1-CxlE:-N6hlP9e3AnVlg1-CxlF:b-4qpht2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5831e8506a260952043045c4919037578c5236db/pkg/sql/pgwire/testdata/pgtest/aborted_txn#L90)):*
> ```
> 
> until
> ReadyForQuery
> ```

Not a blocker but curious if this part can actually confirm that no error has happened, i.e. if after `Flush` and `Sync`, there is an `ErrorReponse`, will this `until` part fail?  


<!-- Sent from Reviewable.io -->

2022-07-11 15:58 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84177)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`pkg/sql/pgwire/testdata/pgtest/aborted_txn` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84177#-N6hlP9e3AnVlg1-CxlE:-N6hyoMr9r4tSmOLp6uW:b-r1od9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5831e8506a260952043045c4919037578c5236db/pkg/sql/pgwire/testdata/pgtest/aborted_txn#L90)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Not a blocker but curious if this part can actually confirm that no error has happened, i.e. if after `Flush` and `Sync`, there is an `ErrorReponse`, will this `until` part fail?  
</blockquote></details>

nice question! yes, the way this test runner works is that if there is ever an ErrorResponse that is not expected by the `until` block, then the test fails


<!-- Sent from Reviewable.io -->

2022-07-11 20:17 UTC, ZhouXing19 commented
LGTM! Just seems that some other tests need to be updated too: `TestPGTest/implicit_txn` and `TestPGTest/portals`, as suggested in the CI

2022-07-11 20:18 UTC, ZhouXing19 approved these changes

2022-07-13 01:55 UTC, rafiss commented
tftr!

bors r=ZhouXing19

2022-07-13 04:25 UTC, merged