test: enforce skip.UnderStress[Race] locally
cockroachdb/cockroach pull request #84364
Opened 2022-07-13 16:59 UTC by HonoreDB

Fixes #84312

Previously, skip.UnderStress only checked NightlyStress(),
which is only set during nightly stress test runs, not
by ./dev test --stress or make stress. This lead to
developers checking in tests that flake or reliably fail
under stress or stressrace.

This PR modifies dev and make to set a COCKROACH_STRESS
environment variable, and modifies skip to honor both
that flag and the one set by nightly stress.

A follow-up might be to default to not skipping when
a filter matches only one test, as there the intent was
almost certainly to actually run it.

Release note: None

2022-07-13 16:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/84364)
<!-- Reviewable:end -->

2022-07-13 19:04 UTC, rickystewart requested changes
Can you address the lint/test failures?

```
pkg/testutils/skip/stress.go:15:5: don't use underscores in Go names; var nightly_stress should be nightlyStress
```

For the `dev` test failures, you can `dev test pkg/cmd/dev --rewrite -f 'TestDataDriven/test(logic)?'`

2022-07-13 22:41 UTC, HonoreDB commented
Thanks for the help! I think the remaining failures are unrelated now.

2022-07-15 12:41 UTC, HonoreDB commented
(merge conflicts fixed, all CI passing)

2022-07-19 19:11 UTC, rickystewart approved these changes

2022-07-19 19:43 UTC, HonoreDB commented
bors r=[rickystewart]

2022-07-19 21:10 UTC, merged