WIP: sql: support grant options on system privileges
cockroachdb/cockroach pull request #84391
Opened 2022-07-13 21:30 UTC by RichardJCai

2022-07-19 21:37 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84391)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84391#-N7NMNTdC6qgfYvGI-aE):*
not sure if we need a release note for this, since the whole syntax is new in v22.2. (but the commit message itself can still be kept, just with Release note: None)
___
*[`pkg/sql/syntheticprivilege/global_privilege.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84391#-N7NN0E71FgQZviR8Njj:-N7NN0E71FgQZviR8Njk:b-t21l5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbfe0d768f3e97eb2071250a3284e0f8a39d6adc/pkg/sql/syntheticprivilege/global_privilege.go#L129)):*
> ```Go
> 		)
> 		privsWithoutGrantOption := privilege.ListFromBitField(
> 			privs.ToBitField()-privsWithGrantOption.ToBitField(),
> ```

i think `-` means this is relying on `grant options` always being a subset of `privs`, but if that were to ever be untrue (due to some other part of the code messing up), this might become broken

can we change `-` to `&^` as a defensive programming measure?
___
*[`pkg/sql/syntheticprivilege/global_privilege.go` line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84391#-N7NNvGPDvwKgar9fxeL:-N7NNvGQ2OEG9Enxffp-:b-5mcqx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbfe0d768f3e97eb2071250a3284e0f8a39d6adc/pkg/sql/syntheticprivilege/global_privilege.go#L135)):*
> ```Go
> 			username.MakeSQLUsernameFromPreNormalizedString(string(user)),
> 			privsWithGrantOption,
> 			true,
> ```

nit: add an inline comment for `true`
___
*[`pkg/sql/syntheticprivilege/global_privilege.go` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84391#-N7NNxoU2wur_CQBQM0p:-N7NNxoU2wur_CQBQM0q:bvy8bh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbfe0d768f3e97eb2071250a3284e0f8a39d6adc/pkg/sql/syntheticprivilege/global_privilege.go#L140)):*
> ```Go
> 			username.MakeSQLUsernameFromPreNormalizedString(string(user)),
> 			privsWithoutGrantOption,
> 			false,
> ```

nit: add an inline comment for `false`
___
*[`pkg/sql/logictest/testdata/logic_test/system_privileges` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84391#-N7NO5uT3rOK-bl74PYj:-N7NO5uT3rOK-bl74PYk:b-lmlxcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbfe0d768f3e97eb2071250a3284e0f8a39d6adc/pkg/sql/logictest/testdata/logic_test/system_privileges#L73)):*
> ```
> 
> statement ok
> GRANT SYSTEM MODIFYCLUSTERSETTING TO testuser WITH GRANT OPTION
> ```

this file should have a test that makes sure that if `testuser` does not have the grant option, then they cannot grant that privilege.


<!-- Sent from Reviewable.io -->

2022-07-20 21:59 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84391)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84391#-N7NMNTdC6qgfYvGI-aE):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

not sure if we need a release note for this, since the whole syntax is new in v22.2. (but the commit message itself can still be kept, just with Release note: None)
</blockquote></details>

Done.
___
*[`pkg/sql/syntheticprivilege/global_privilege.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84391#-N7NN0E71FgQZviR8Njj:-N7SZVUgEct5D7g_bYdK:byx45sw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbfe0d768f3e97eb2071250a3284e0f8a39d6adc/pkg/sql/syntheticprivilege/global_privilege.go#L129)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think `-` means this is relying on `grant options` always being a subset of `privs`, but if that were to ever be untrue (due to some other part of the code messing up), this might become broken

can we change `-` to `&^` as a defensive programming measure?
</blockquote></details>

Yeah that sounds solid
___
*[`pkg/sql/logictest/testdata/logic_test/system_privileges` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84391#-N7NO5uT3rOK-bl74PYj:-N7Sbi3f4amerB5zfy9c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbfe0d768f3e97eb2071250a3284e0f8a39d6adc/pkg/sql/logictest/testdata/logic_test/system_privileges#L73)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this file should have a test that makes sure that if `testuser` does not have the grant option, then they cannot grant that privilege.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-22 20:34 UTC, rafiss approved these changes
looks great, nice!

> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84391#-:-N7bb_8bDCKoW4tXoE-m:b-7fterw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)



<!-- Sent from Reviewable.io -->

2022-07-22 21:09 UTC, RichardJCai commented
Thanks! 
bors r=rafiss

2022-07-25 20:02 UTC, RichardJCai commented
bors r=rafiss

2022-07-25 22:13 UTC, merged