ci: add CI support for Antithesis POC
cockroachdb/cockroach pull request #84662
Opened 2022-07-19 18:16 UTC by srosenberg

TODO: change summary

Release note: None

2022-07-19 18:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/84662)
<!-- Reviewable:end -->

2022-07-26 02:23 UTC, AlexTalks requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

I have some thoughts about switching to TPCC, and also about instrumenting the workload and using their `rng`, but I don't think that needs to hold this up at all.  Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84662#-:-N7sIvsa-_i4xQRg-WQr:b-u9drvn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart and @srosenberg)

___
*[`build/deploy/Dockerfile_antithesis_instrumented` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84662#-N7sJ2--9ukMC3sGBmD7:-N7sJ2--9ukMC3sGBmD8:b-kdw2sy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccc88e6a7f04cea0f74026418cae27624d75e6e/build/deploy/Dockerfile_antithesis_instrumented#L19)):*
> ```
> COPY go-*.sym.tsv /opt/antithesis/
> COPY libvoidstar.so /opt/antithesis/lib/
> COPY licenses/* /licenses/
> ```

Is this all we need to make sure it is a licensed version?


<!-- Sent from Reviewable.io -->

2022-07-26 02:23 UTC, AlexTalks approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
(fixing earlier comment to ensure it registers as an approve)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84662#-:-N7sJHe-4pCv-1kfP1fY:b-q7qlwc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart and @srosenberg)



<!-- Sent from Reviewable.io -->

2022-08-02 16:10 UTC, rickystewart approved these changes

2022-08-02 19:16 UTC, srosenberg reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84662#-:-N8Uyy4cBXOurLUN4RPN:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @AlexTalks)

___
*[`build/deploy/Dockerfile_antithesis_instrumented` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84662#-N7sJ2--9ukMC3sGBmD7:-N8Uz1w74E0YUT58qjqL:blqv96e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ccc88e6a7f04cea0f74026418cae27624d75e6e/build/deploy/Dockerfile_antithesis_instrumented#L19)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Is this all we need to make sure it is a licensed version?
</blockquote></details>

I believe so; that's what our mkrelease does as well.


<!-- Sent from Reviewable.io -->

2022-08-02 19:16 UTC, srosenberg commented
bors r+

2022-08-02 22:45 UTC, rickystewart commented
bors r-

2022-08-02 23:11 UTC, merged