changefeedccl/kvfeed: ignore unwatched column drops with stop policy
cockroachdb/cockroach pull request #84674
Opened 2022-07-19 21:09 UTC by jayshrivastava

See commit note.

2022-07-19 21:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/84674)
<!-- Reviewable:end -->

2022-07-21 19:51 UTC, HonoreDB requested changes
Great commit message and a very fast first PR, love to see it.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-:-N7XHu7YBGio_JzD63PY:b-dm0w43)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @samiskin)

___
*[`pkg/ccl/changefeedccl/changefeedbase/target.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7X4hee-ULICfzf0xsR:-N7X4hee-ULICfzf0xsS:b-vkw4ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/changefeedbase/target.go#L88)):*
> ```Go
> // HasNonDefaultColumnFamily returns true if the Targets include least
> // one watched column family which is not the default column family.
> func (ts *Targets) HasNonDefaultColumnFamily() (bool, error) {
> ```

This method needs to take a TableID. It's possible to create a changefeed like this: "CREATE CHANGEFEED FOR TABLE foo, TABLE bar FAMILY baz", so that we have one target with a specified column family and another without.

Also, a nit: "NonDefault" isn't quite how I'd describe what this is checking for. It's possible for a table to have only one column family but it's not the default family, it's one that was created explicitly. I'd maybe call this HasSpecifiedColumnFamilies().

Or you could just call EachHavingTableID in the filtering logic rather than add a method here.

If you keep this method implemented here, you could optimize it by implementing it more low-level, something like `ts.m[tableID].wholeTable == nil` should be equivalent if we know the tableID is in the map.
___
*[`pkg/ccl/changefeedccl/schemafeed/table_event_filter.go` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7X91O_9EZGr8gtzP2u:-N7X91O_9EZGr8gtzP2v:blsh9gk) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/schemafeed/table_event_filter.go#L203)):*
> ```Go
> 		}
> 
> 		for _, watchedColID := range watchedCols {
> ```

I'm a little worried about scalability here...people do silly things like create tables with thousands of columns, so even though this method won't get called very often it'd still be a shame to be anything worse than O(number of columns) in complexity. If you look at how the filter is determining that a column was dropped in the first place, dropVisibleColumnMutationExists, it's able to iterate over the changes and check if it cares about each individual column. What if that function were family-aware? Like for example if the signature were `dropVisibleColumnMutationExists(desc catalog.TableDescriptor, relevancyChecker func(catalog.Column) bool)`,
and it called relevancyChecker on each dropped column. Then if the whole table is being watched, you could pass in a function that just returns true, while if it's not, you could create a function with a closure over a set of column ids that checks whether the column is in that set. https://github.com/cockroachdb/cockroach/blob/e28e716814b760ba05cdf2be2ced6fa0039b101c/pkg/sql/opt/indexrec/index_recommendation_set.go#L94-L107 has an example of creating a set of columns that can be efficiently checked whether it contains a specific column. If you could find a way to just create that once by iterating over the watched families, I think you'd be in more efficient territory.
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 1001 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7XEK614FDXBg0JtZaO:-N7XEK614FDXBg0JtZaP:b-9fqeo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/changefeed_test.go#L1001)):*
> ```Go
> // If the schema_change_policy is 'stop' and we drop columns which are not
> // targeted by the changefeed, it should not stop.
> func TestNoStopAfterNonTargetColumnDrop(t *testing.T) {
> ```

Great test!
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 1005 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7XELpSBkcZKerWmuG0:-N7XELpSBkcZKerWmuG1:ba7dtbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/changefeed_test.go#L1005)):*
> ```Go
> 	testFn := func(t *testing.T, s TestServer, f cdctest.TestFeedFactory) {
> 		sqlDB := sqlutils.MakeSQLRunner(s.DB)
> 		disableDeclarativeSchemaChangesForTest(t, sqlDB)
> ```

Was this copied from another test or is it necessary? The declarative schema changer is on by default, so I'd rather not add any new tests that disable it--this feature will need to work when it's on. If it's an issue with the test framework, though, no need to fix it.
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 1034 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7XFsZc5opJnJaI2vSW:-N7XFsZc5opJnJaI2vSX:b-bugi1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/changefeed_test.go#L1034)):*
> ```Go
> }
> 
> // If we drop columns which are not targeted by the changefeed, it should not backfill.
> ```

I'd suggest adding tests with a single changefeed that has multiple targets. Three important cases are

1. `TABLE hasfams FAMILY b_and_c, TABLE nofams`(checking behavior for each)
2. `TABLE hasfams FAMILY b_and_c, TABLE alsohasfams FAMILY only id_a` (with the same family names on both tables).
3. `TABLE hasfams FAMILY id_a, TABLE hasfams FAMILY b_and_c`(I wouldn't worry about optimizing away the case where somebody has listed all the families in a table, but it's important that a table that's referenced multiple times with different families works correctly).
___
*[`pkg/ccl/changefeedccl/schemafeed/helpers_test.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7XHjIy30JVOZSKjBdb:-N7XHjIy30JVOZSKjBdc:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/schemafeed/helpers_test.go#L44)):*
> ```Go
> }
> 
> func CreateChangefeedTargets(tableID descpb.ID) changefeedbase.Targets {
> ```

Nice!


<!-- Sent from Reviewable.io -->

2022-07-22 21:16 UTC, jayshrivastava reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84674)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @samiskin)

___
*[`pkg/ccl/changefeedccl/changefeedbase/target.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7X4hee-ULICfzf0xsR:-N7bg1LYEXfom8t6jQH4:b-k337db) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/changefeedbase/target.go#L88)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

This method needs to take a TableID. It's possible to create a changefeed like this: "CREATE CHANGEFEED FOR TABLE foo, TABLE bar FAMILY baz", so that we have one target with a specified column family and another without.

Also, a nit: "NonDefault" isn't quite how I'd describe what this is checking for. It's possible for a table to have only one column family but it's not the default family, it's one that was created explicitly. I'd maybe call this HasSpecifiedColumnFamilies().

Or you could just call EachHavingTableID in the filtering logic rather than add a method here.

If you keep this method implemented here, you could optimize it by implementing it more low-level, something like `ts.m[tableID].wholeTable == nil` should be equivalent if we know the tableID is in the map.
</blockquote></details>

I agree with this. Adding the table ID makes it easier while filtering schema changes. I didn't realize I could do the `nil` check until I read how `Targets.add(...)` works. I added some commentary to the `Target` struct  in `pkg/ccl/changefeedccl/changefeedbase/target.go` to make it more clear. 
___
*[`pkg/ccl/changefeedccl/schemafeed/table_event_filter.go` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7X91O_9EZGr8gtzP2u:-N7bj_nu4-Yd8fTcVpAV:bdzs3to) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/schemafeed/table_event_filter.go#L203)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I'm a little worried about scalability here...people do silly things like create tables with thousands of columns, so even though this method won't get called very often it'd still be a shame to be anything worse than O(number of columns) in complexity. If you look at how the filter is determining that a column was dropped in the first place, dropVisibleColumnMutationExists, it's able to iterate over the changes and check if it cares about each individual column. What if that function were family-aware? Like for example if the signature were `dropVisibleColumnMutationExists(desc catalog.TableDescriptor, relevancyChecker func(catalog.Column) bool)`,
and it called relevancyChecker on each dropped column. Then if the whole table is being watched, you could pass in a function that just returns true, while if it's not, you could create a function with a closure over a set of column ids that checks whether the column is in that set. https://github.com/cockroachdb/cockroach/blob/e28e716814b760ba05cdf2be2ced6fa0039b101c/pkg/sql/opt/indexrec/index_recommendation_set.go#L94-L107 has an example of creating a set of columns that can be efficiently checked whether it contains a specific column. If you could find a way to just create that once by iterating over the watched families, I think you'd be in more efficient territory.
</blockquote></details>

Great comment :) 

I updated the function. It returns immediately if the whole table is being watched. At the moment, we don't store column IDs in `Targets`, so I have to look them up from the descriptor. There's also no way to get a family by name in the descriptor. I iterate over the families in the descriptor, skipping them if they are not watched and collecting the column ids in the `FastIntSet` for later. Then the function checks all the mutations (I would imagine that the number of mutations in a single schema feed event descriptor should be small) for a watched column that is being dropped, returning immediately if it finds one. 
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 1005 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7XELpSBkcZKerWmuG0:-N7bgNp74PbPVXOJqaV6:b-fj1de5) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/changefeed_test.go#L1005)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Was this copied from another test or is it necessary? The declarative schema changer is on by default, so I'd rather not add any new tests that disable it--this feature will need to work when it's on. If it's an issue with the test framework, though, no need to fix it.
</blockquote></details>

Initially, I copied another test to write mine. I agree that it's better to enable declarative schema changes since those are what we are working towards.

One issue I ran into with enabling them is that it causes errors to pop up when using sinkless/core changefeeds. When the primary index swap occurs as a part of the column drop schema change, the sinkless changefeed doesn't get restarted in the same way that other ones do. The next write after the schema change causes this error. Thus, I've omitted the sinkless changefeed from these tests. 
```
(error encountered after some results were delivered)
ERROR: schema change occurred at 1658520726642164000.0000000000
```

Some other tests (ex. `TestChangefeedEachColumnFamilySchemaChanges`) fail on sinkless for the same reason if `disableDeclarativeSchemaChangesForTest()` is removed.



_Code quote:_
```Go
feedTestOmitSinks("sinkless"))
```
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 1034 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7XFsZc5opJnJaI2vSW:-N7bl0k7EzeFUk433qK5:b-ehr54h) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/changefeed_test.go#L1034)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I'd suggest adding tests with a single changefeed that has multiple targets. Three important cases are

1. `TABLE hasfams FAMILY b_and_c, TABLE nofams`(checking behavior for each)
2. `TABLE hasfams FAMILY b_and_c, TABLE alsohasfams FAMILY only id_a` (with the same family names on both tables).
3. `TABLE hasfams FAMILY id_a, TABLE hasfams FAMILY b_and_c`(I wouldn't worry about optimizing away the case where somebody has listed all the families in a table, but it's important that a table that's referenced multiple times with different families works correctly).
</blockquote></details>

Ack! I added more tests for these cases.


<!-- Sent from Reviewable.io -->

2022-07-25 17:27 UTC, HonoreDB approved these changes
> Reviewed 2 of 7 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84674)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @jayshrivastava, and @samiskin)

___
*[`pkg/ccl/changefeedccl/changefeedbase/target.go` line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7qMnB4EgNURhAFL13e:-N7qMnB4EgNURhAFL13f:bj65zvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6f667ca06badd4cd01b88acb1ef569e449e8f26/pkg/ccl/changefeedccl/changefeedbase/target.go#L92)):*
> ```Go
> // GetSpecifiedColumnFamilies returns a set of watched families
> // belonging to the table.
> func (ts *Targets) GetSpecifiedColumnFamilies(tableID descpb.ID) map[string]*struct{} {
> ```

I usually see this done as `map[string]struct{}`, curious what making it a map to pointers does.
___
*[`pkg/ccl/changefeedccl/schemafeed/table_event_filter.go` line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7X91O_9EZGr8gtzP2u:-N7qOJlnCwIfWVIL9MqS:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/31266fe14f97890edebd78ca7a23b303eab935bd/pkg/ccl/changefeedccl/schemafeed/table_event_filter.go#L203)):*
<details><summary><i>Previously, jayshrivastava wrote…</i></summary><blockquote>

Great comment :) 

I updated the function. It returns immediately if the whole table is being watched. At the moment, we don't store column IDs in `Targets`, so I have to look them up from the descriptor. There's also no way to get a family by name in the descriptor. I iterate over the families in the descriptor, skipping them if they are not watched and collecting the column ids in the `FastIntSet` for later. Then the function checks all the mutations (I would imagine that the number of mutations in a single schema feed event descriptor should be small) for a watched column that is being dropped, returning immediately if it finds one. 
</blockquote></details>

Nice!


<!-- Sent from Reviewable.io -->

2022-07-25 18:30 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84674)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @jayshrivastava, and @samiskin)

___
*[`pkg/ccl/changefeedccl/changefeedbase/target.go` line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7qMnB4EgNURhAFL13e:-N7qbdamDDxTGTcnLcXC:b-vozrgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6f667ca06badd4cd01b88acb1ef569e449e8f26/pkg/ccl/changefeedccl/changefeedbase/target.go#L92)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I usually see this done as `map[string]struct{}`, curious what making it a map to pointers does.
</blockquote></details>

I'd go so far as to say that it's a mistake. I think for funny reasons, it ends up not really being less efficient, but it's unidiomatic. If I see `map[string]struct{}` I know it's a set of strings, if I see this, I feel unsure. 


<!-- Sent from Reviewable.io -->

2022-07-25 18:32 UTC, jayshrivastava reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84674)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @jayshrivastava, and @samiskin)

___
*[`pkg/ccl/changefeedccl/changefeedbase/target.go` line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7qMnB4EgNURhAFL13e:-N7qcAUi6kX51-LPj13k:b-bc0roq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6f667ca06badd4cd01b88acb1ef569e449e8f26/pkg/ccl/changefeedccl/changefeedbase/target.go#L92)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'd go so far as to say that it's a mistake. I think for funny reasons, it ends up not really being less efficient, but it's unidiomatic. If I see `map[string]struct{}` I know it's a set of strings, if I see this, I feel unsure. 
</blockquote></details>

Agreed. I'll change it before I merge.


<!-- Sent from Reviewable.io -->

2022-07-26 15:09 UTC, jayshrivastava commented
bors r+

2022-07-26 17:15 UTC, merged