kvserver: honor lease preferences in store balance
cockroachdb/cockroach pull request #84863
Opened 2022-07-21 18:09 UTC by kvoli

Previously, lease preferences were not considered when selecting a
voter to become the leaseholder after replica rebalancing. Instead, the
voter on the store with the least QPS was selected.

This patch introduces a check to try and satisfy the lease preference
from the rebalanced voting set of replicas, if possible. Among voters
satisfying the preference, the one on a store with the least QPS is
selected to be the leaseholder.

When not possible, where none of the voting replicas satisfy the lease
preference, the store rebalancer will pick the miminum QPS store, as
before.

Release note: None

2022-07-21 18:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/84863)
<!-- Reviewable:end -->

2022-07-21 18:38 UTC, kvoli commented
On the configuration from the issue, it hasn't violated the lease preference. The leases for the kv table remain within us-east1. Which is the first three stores.

![image](https://user-images.githubusercontent.com/39606633/180288862-29aa5ba4-4820-4baf-bc68-520c405ddf9e.png)


```bash
export gce_project=cockroach-ephemeral
export email=austen-lease-prefs

roachprod create $email -n 9 --clouds=gce --gce-zones=us-east1-b:1,us-east1-c:1,us-east1-d:1,us-east4-a:1,us-east4-b:1,us-east4-c:1,us-west1-a:1,us-west1-b:1,us-west1-c:1 --gce-machine-type=n1-standard-4 

roachprod put $email cockroach-remote cockroach
roachprod start $email

roachprod run $email:1 -- './cockroach workload init kv'

roachprod sql $email:1 -- -e 'ALTER DATABASE kv SET PRIMARY REGION "us-east1";'
roachprod sql $email:1 -- -e 'ALTER DATABASE kv ADD REGION "us-west1"';
roachprod sql $email:1 -- -e 'ALTER DATABASE kv ADD REGION "us-east4"';
roachprod sql $email:1 -- -e 'ALTER DATABASE kv SURVIVE REGION FAILURE;'


while true 
do
roachprod sql $email:1 -- -e "SELECT now(), range_id, node_id, node_id = lease_holder as is_leasholder, ARRAY[node_id] <@ voting_replicas as voter, locality, database_name, table_name, start_pretty, end_pretty FROM [ SELECT start_pretty, end_pretty, range_id, unnest(replicas) as node_id, unnest(replica_localities) as locality, lease_holder, voting_replicas, database_name, table_name FROM [ SELECT * FROM crdb_internal.ranges WHERE database_name = 'kv' ] GROUP BY range_id, node_id, lease_holder, start_pretty, end_pretty, locality, voting_replicas, database_name, table_name ] WHERE node_id = lease_holder and locality not like 'cloud=gce,region=us-east1%' ORDER BY range_id ASC, node_id = lease_holder DESC, ARRAY[node_id] <@ voting_replicas ASC;" 
sleep 5
done

roachprod run $email -- './cockroach workload run kv --max-rate=1000 --read-percent=95 --max-block-bytes=2'
```

2022-07-21 23:40 UTC, lidorcarmel requested changes
awesome testing :)

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-:-N7Y7S4dAVuTW-2Btxv5:byx5nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @kvoli)

___
*[`pkg/kv/kvserver/store_rebalancer.go` line 678 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7Y52L6Ccb3ietrxavP:-N7Y52L6Ccb3ietrxavQ:b-c2xpn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2445fbc2d108bfb37f9881565415022442934056/pkg/kv/kvserver/store_rebalancer.go#L678)):*
> ```Go
> 
> 		for i := 0; i < len(targetVoterRepls); i++ {
> 			if targetVoterRepls[i].StoreID == leaseCandidates[newLeaseIdx].StoreID {
> ```

say our voters were on stores 5,6,7, and the allocator said the only valid target is 7.
then, when we iterate over the candidate (only 7), we see that it is `ReplicaIsBehind`, so we don't update `newLeaseIdx`.
then, here we will decide to move to 7 because newLeaseIdx is 0.
is that right?
IOW, if all candidates (from the allocator) are raft-behind, then we will move the lease to a replica that is behind, instead of a replica that is not behind but doesn't respect the lease preference.
IOW(2), what's more important? lease preferences or raft-replica-behind state? probably better to stick with the old behavior if all candidates are behind?


<!-- Sent from Reviewable.io -->

2022-07-22 04:05 UTC, lidorcarmel requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84863)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @kvoli)

___
*[`pkg/kv/kvserver/store_rebalancer.go` line 678 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7Y52L6Ccb3ietrxavP:-N7Z3aAZ42TYB1EsBj4W:b-6zraep) ([raw file](https://github.com/cockroachdb/cockroach/blob/2445fbc2d108bfb37f9881565415022442934056/pkg/kv/kvserver/store_rebalancer.go#L678)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

say our voters were on stores 5,6,7, and the allocator said the only valid target is 7.
then, when we iterate over the candidate (only 7), we see that it is `ReplicaIsBehind`, so we don't update `newLeaseIdx`.
then, here we will decide to move to 7 because newLeaseIdx is 0.
is that right?
IOW, if all candidates (from the allocator) are raft-behind, then we will move the lease to a replica that is behind, instead of a replica that is not behind but doesn't respect the lease preference.
IOW(2), what's more important? lease preferences or raft-replica-behind state? probably better to stick with the old behavior if all candidates are behind?
</blockquote></details>

looking some more, in addition to the above `PreferredLeaseholders` is a bit misleading, returning a slice but that slice can only be nil or with one element, so the code here can be simplified if we change that function to return a ReplicaDescriptor instead of a slice.
Also, that function tries to return the first good candidate, which means that we should pass in a sorted slice by QPS.
Last, the allocator has a `FilterBehindReplicas` function which might make the code here cleaner? maybe.. I guess something like:
```
upToDateReplicas := FilterBehindReplicas(ctx, raftStatus, replicas)
```
(copied from somewhere)
right after calling `PreferredLeaseholders`.

WDYT?


<!-- Sent from Reviewable.io -->

2022-07-22 20:27 UTC, aayushshah15 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84863)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/store_rebalancer.go` line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7b_bRlBfZMWUI6r4JB:-N7b_bRlBfZMWUI6r4JC:b-2ujfj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2445fbc2d108bfb37f9881565415022442934056/pkg/kv/kvserver/store_rebalancer.go#L653)):*
> ```Go
> 		// it is more likely than not that this would only occur under
> 		// misconfiguration.
> 		leaseCandidates := sr.rq.allocator.PreferredLeaseholders(rebalanceCtx.conf, targetVoterRepls)
> ```

We should use the `ValidLeaseTargets()` method here, which has other checks in addition to lease preferences, such that whether the replica needs a snapshot or not, or whether the replica belongs to a suspect /draining node (which aren't allowed to receive leases). This perhaps answers part of Lidor's concerns from below as well.


<!-- Sent from Reviewable.io -->

2022-07-25 12:59 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84863)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @lidorcarmel)

___
*[`pkg/kv/kvserver/store_rebalancer.go` line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7b_bRlBfZMWUI6r4JB:-N7pQWcGC6dFykihitf8:b-9xtn5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2445fbc2d108bfb37f9881565415022442934056/pkg/kv/kvserver/store_rebalancer.go#L653)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

We should use the `ValidLeaseTargets()` method here, which has other checks in addition to lease preferences, such that whether the replica needs a snapshot or not, or whether the replica belongs to a suspect /draining node (which aren't allowed to receive leases). This perhaps answers part of Lidor's concerns from below as well.
</blockquote></details>

Originally I used that method. Unfortunately it won't work with replicas that aren't already initialized. It filters on behind raft snapshots, in which case it removes the incoming voters who don't yet exist.

I think it might be best to add in a flag, similar to the testing knobs, which ignores this.
___
*[`pkg/kv/kvserver/store_rebalancer.go` line 678 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7Y52L6Ccb3ietrxavP:-N7pQsKS9LhRtfcWMIwg:b-n61gzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2445fbc2d108bfb37f9881565415022442934056/pkg/kv/kvserver/store_rebalancer.go#L678)):*
>  then, when we iterate over the candidate (only 7), we see that it is ReplicaIsBehind, so we don't update newLeaseIdx.
That is a good point.

The filter behind replicas won't be able to be used here, as it filters incoming replicas which don't yet exist too.

I think altering the allocator to pass a flag that performs the check, if the candidate exists in the range descriptor otherwise we skip.


<!-- Sent from Reviewable.io -->

2022-07-25 16:42 UTC, lidorcarmel requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84863)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @kvoli)

___
*[`pkg/kv/kvserver/store_rebalancer.go` line 678 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7Y52L6Ccb3ietrxavP:-N7qEH2X76yo2eizeK6O:b-tf1lgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2445fbc2d108bfb37f9881565415022442934056/pkg/kv/kvserver/store_rebalancer.go#L678)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

>  then, when we iterate over the candidate (only 7), we see that it is ReplicaIsBehind, so we don't update newLeaseIdx.
That is a good point.

The filter behind replicas won't be able to be used here, as it filters incoming replicas which don't yet exist too.

I think altering the allocator to pass a flag that performs the check, if the candidate exists in the range descriptor otherwise we skip.
</blockquote></details>

I see, makes sense, thanks!


<!-- Sent from Reviewable.io -->

2022-07-26 21:34 UTC, lidorcarmel approved these changes
LGTM!

> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-:-N7w2xlR6gBym_A5XX5H:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @kvoli)

___
*[`pkg/kv/kvserver/store_rebalancer.go` line 669 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7vd4v36D7SZyK-ZYmG:-N7vd4v36D7SZyK-ZYmH:b-yrkma0) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/store_rebalancer.go#L669)):*
> ```Go
> 		// this range post-rebalance would have no suitable location.
> 		if len(validTargets) == 0 {
> 			continue
> ```

can you please add a level 3 VEventf log here? similar to some above. we're skipping a lease (rarely, very rarely) so a log would be great.
___
*[`pkg/kv/kvserver/store_rebalancer.go` line 676 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7vhQkN7ZqfkEh6-dDw:-N7vhQkN7ZqfkEh6-dDx:bnh1ky6) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/store_rebalancer.go#L676)):*
> ```Go
> 		newLeaseQPS := math.MaxFloat64
> 
> 		// Find the incoming voting replica, which is a valid lease target and
> ```

not necessarily incoming voting, right? might be existing?



_Code quote:_
```Go
Find the incoming voting replica
```
___
*[`pkg/kv/kvserver/allocator/base.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7vaG8VEVum7NuoHhp7:-N7vaG8VEVum7NuoHhp8:bmti373) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/allocator/base.go#L56)):*
> ```Go
> 	if len(constraints) == 0 {
> 		return true
> ```

perhaps an unintentional empty line?
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1477 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7vhfYv9F5LoJs8Q34r:-N7vhfYv9F5LoJs8Q34s:bw5wk7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1477)):*
> ```Go
> 		Desc() *roachpb.RangeDescriptor
> 	},
> 	// excludeLeaseRepl dictates whether the result set can include the source
> ```

drop this comment?



_Code quote:_
```Go
	// excludeLeaseRepl dictates whether the result set can include the source
	// replica.
```
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7viW8gBfqgJ_i1en_h:-N7viW8gBfqgJ_i1en_i:b-kr8ek0) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1523)):*
> ```Go
> 			// candidates which are not in the current range descriptors
> 			// replica set, however are in the candidate list. Uninitialized
> 			// replicas, will always need a snapshot.
> ```

remove the comma?



_Code quote:_
```Go
,
```
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1539 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7vaktc0lsXAS0HWtXL:-N7vaktc0lsXAS0HWtXM:b-oeazfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1539)):*
> ```Go
> 		if a.knobs != nil && a.knobs.RaftStatusFn != nil {
> 			status = a.knobs.RaftStatusFn(leaseRepl)
> ```

empty line?


<!-- Sent from Reviewable.io -->

2022-07-26 21:38 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84863)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @kvoli, and @lidorcarmel)

___
*[`pkg/kv/kvserver/store_rebalancer.go` line 669 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7vd4v36D7SZyK-ZYmG:-N7wRZHI8UKaWyftuQnz:b-8b11j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/store_rebalancer.go#L669)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

can you please add a level 3 VEventf log here? similar to some above. we're skipping a lease (rarely, very rarely) so a log would be great.
</blockquote></details>

Added
___
*[`pkg/kv/kvserver/store_rebalancer.go` line 676 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7vhQkN7ZqfkEh6-dDw:-N7wRZth5GfoONWc9ELW:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/store_rebalancer.go#L676)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

not necessarily incoming voting, right? might be existing?
</blockquote></details>

Updated
___
*[`pkg/kv/kvserver/allocator/base.go` line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7vaG8VEVum7NuoHhp7:-N7wRaSdB80F32M6ntG3:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/allocator/base.go#L56)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

perhaps an unintentional empty line?
</blockquote></details>

Updated
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1477 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7vhfYv9F5LoJs8Q34r:-N7wRaoq348Aqs3unPeN:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1477)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

drop this comment?
</blockquote></details>

Updated
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7viW8gBfqgJ_i1en_h:-N7wRbB13WSAD2xsVT9t:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1523)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

remove the comma?
</blockquote></details>

Updated
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1539 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7vaktc0lsXAS0HWtXL:-N7wRbWeEX2j5rld1uOV:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/95cdb1b5c2cb696eaa7e56bdaed122de7a204531/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1539)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

empty line?
</blockquote></details>

Updated


<!-- Sent from Reviewable.io -->

2022-07-26 22:05 UTC, lidorcarmel approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84863)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @kvoli, and @lidorcarmel)

___
*[`pkg/kv/kvserver/store_rebalancer.go` line 672 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-N7wX_MiDe2uByLcPrCG:-N7wX_MiDe2uByLcPrCH:b9yunah) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fcd897dbf0d3d9da60f66aa5f7fb5d735054b99/pkg/kv/kvserver/store_rebalancer.go#L672)):*
> ```Go
> 				ctx,
> 				3,
> 				"could not find rebalance opportunities for r%d, replica found to hold lease",
> ```

maybe "no" replica found?



_Code quote:_
```Go
replica found to hold lease
```


<!-- Sent from Reviewable.io -->

2022-07-27 20:22 UTC, aayushshah15 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> and ditto on the nice testing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84863#-:-N80JjTD6sXiFsEgmhzn:b-c8cful)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @kvoli, and @lidorcarmel)



<!-- Sent from Reviewable.io -->

2022-07-27 21:38 UTC, kvoli commented
bors r+

2022-07-28 00:08 UTC, kvoli commented
> Canceled.

Mentioned merge conflict, rebased on master.

2022-07-28 16:03 UTC, kvoli commented
bors r+

2022-07-28 19:20 UTC, merged

2022-10-14 20:54 UTC, irfansharif commented
blathers backport 22.1