kvserver: add metrics to track snapshot queueing and application
cockroachdb/cockroach pull request #84947
Opened 2022-07-22 23:52 UTC by AlexTalks

While we previously had one metric to track "in-progress" snapshots,
`replicas.reserved`, this metric is used by both senders and receivers,
and does not track the number of snapshots queued on its semaphore. This
change adds the following new metrics, separated by sender and receiver:
```
range.snapshots.send-queue
range.snapshots.recv-queue
range.snapshots.send-in-progress
range.snapshots.recv-in-progress
```

These metrics specifically track the number of queued non-empty
snapshots on a sender or receiver store, as well as the number of
snapshots currently being sent or received by a given store. These
metrics specifically only track non-empty snapshots, because empty
snapshots are not throttled at all, and thus do not compete for the
semaphore.

Release note (ops change): Added new metrics
`range.snapshots.(send|recv)-queue` and
`range.snapshots.(send|recv)-in-progress` to track the number of queued
and in-progress snapshots being sent or received on a store.

2022-07-22 23:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/84947)
<!-- Reviewable:end -->

2022-07-27 21:17 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @KnightAsterial)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84947#-N80V5_OBNE_I7J7P4SM:-N80V5_OBNE_I7J7P4SN:b-9n0nsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d995b1b8010f1682a5c178cbb489559eedb92f5/pkg/kv/kvserver/store_snapshot.go#L596)):*
> ```Go
> 		}
> 
> 		inProgressSnapshotMetric.Inc(1)
> ```

The way this is written, we won't be recording empty snapshots ingestion as "in progress". I don't have a strong opinion but curious what you think. 

I think it would be better to have this increment (and the following decrement in the returned closure) outside of this if-block, what do you think?  I think there might be instances where we might find it useful to observe the impact of a wave of empty snapshot ingestion.  


<!-- Sent from Reviewable.io -->

2022-07-28 03:02 UTC, AlexTalks reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @KnightAsterial)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84947#-N80V5_OBNE_I7J7P4SM:-N81k42H7JxW-r63oqJG:bblv6rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d995b1b8010f1682a5c178cbb489559eedb92f5/pkg/kv/kvserver/store_snapshot.go#L596)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

The way this is written, we won't be recording empty snapshots ingestion as "in progress". I don't have a strong opinion but curious what you think. 

I think it would be better to have this increment (and the following decrement in the returned closure) outside of this if-block, what do you think?  I think there might be instances where we might find it useful to observe the impact of a wave of empty snapshot ingestion.  
</blockquote></details>

This was intentional - since the empty snapshots don't wait for the semaphore (on either sender or receiver side), I thought it wouldn't be extremely useful to see how many are in progress at a given time, especially when in the same metric as non-empty snapshots.  Do you think we should add a separate metric for this?  Or incorporate the non-empty snapshots as well?


<!-- Sent from Reviewable.io -->

2022-07-28 03:04 UTC, AlexTalks reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @KnightAsterial)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84947#-N80V5_OBNE_I7J7P4SM:-N81kQwQDGm8yq5kKD0y:b-m7kkmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d995b1b8010f1682a5c178cbb489559eedb92f5/pkg/kv/kvserver/store_snapshot.go#L596)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

This was intentional - since the empty snapshots don't wait for the semaphore (on either sender or receiver side), I thought it wouldn't be extremely useful to see how many are in progress at a given time, especially when in the same metric as non-empty snapshots.  Do you think we should add a separate metric for this?  Or incorporate the non-empty snapshots as well?
</blockquote></details>

Incorporate the ~non-~ empty snapshots, I mean.


<!-- Sent from Reviewable.io -->

2022-07-28 10:22 UTC, kvoli commented
Related but not a comment on this patch.

Is it possible to instrument tracking the number of aggregate bytes queued (send/recv) and remaining bytes of processing snapshots?

2022-07-28 20:43 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @KnightAsterial)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84947#-N80V5_OBNE_I7J7P4SM:-N85Xc37DlqoQf-4SXZF:b-sncfya) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d995b1b8010f1682a5c178cbb489559eedb92f5/pkg/kv/kvserver/store_snapshot.go#L596)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Incorporate the ~non-~ empty snapshots, I mean.
</blockquote></details>

My suggestion would be to incorporate empty snapshots in this metric and add a separate metric that tracks just the set of non-empty snapshots. So we'd have one metric corresponding to all snapshots and one corresponding to just non-empty snapshots. 


<!-- Sent from Reviewable.io -->

2022-08-03 01:02 UTC, AlexTalks reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @KnightAsterial)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84947#-N80V5_OBNE_I7J7P4SM:-N8WDHlx67ApQFSoahfH:bbxdxmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d995b1b8010f1682a5c178cbb489559eedb92f5/pkg/kv/kvserver/store_snapshot.go#L596)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

My suggestion would be to incorporate empty snapshots in this metric and add a separate metric that tracks just the set of non-empty snapshots. So we'd have one metric corresponding to all snapshots and one corresponding to just non-empty snapshots. 
</blockquote></details>

Added `range.snapshots.(send|recv)-total-in-progress` metrics to track empty snapshots as well.


<!-- Sent from Reviewable.io -->

2022-08-03 01:04 UTC, AlexTalks reviewed
As for @kvoli's suggestion, I assume you mean per-snapshot, tracking on the sender side for remaining, and on the receiver side for the queued bytes?  I think this is definitely feasible but I'd put it in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84947#-:-N8WDXmA9L4zGaWB7X80:bbf9t57)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @KnightAsterial)



<!-- Sent from Reviewable.io -->

2022-08-03 14:05 UTC, kvoli commented
> As for @kvoli's suggestion, I assume you mean per-snapshot, tracking on the sender side for remaining, and on the receiver side for the queued bytes? I think this is definitely feasible but I'd put it in a separate PR.


A separate PR sounds good. I filed an issue for it: https://github.com/cockroachdb/cockroach/issues/85528.

2022-08-03 19:10 UTC, aayushshah15 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @AlexTalks, and @KnightAsterial)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 569 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84947#-N8_2paDAQx1Z0xXlj6s:-N8_2paDAQx1Z0xXlj6t:b2p8mv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/79e7df4ab7e3fde6bd93d0dcd4959e3f3dfa116f/pkg/kv/kvserver/store_snapshot.go#L569)):*
> ```Go
> ) (_cleanup func(), _err error) {
> 	tBegin := timeutil.Now()
> 	totalInProgressSnapshotMetric.Inc(1)
> ```

This increment should be after the logic that waits to acquire the snapshot reservation, right?

Currently, we have this asymmetry where the `total` metric includes the snapshots waiting on the semaphore whereas the non-empty in-progress metric doesn't. 


<!-- Sent from Reviewable.io -->

2022-08-03 20:39 UTC, AlexTalks reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @KnightAsterial)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 569 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84947#-N8_2paDAQx1Z0xXlj6s:-N8_QleR55J1O8DtzsIP:b-czz8o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/79e7df4ab7e3fde6bd93d0dcd4959e3f3dfa116f/pkg/kv/kvserver/store_snapshot.go#L569)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

This increment should be after the logic that waits to acquire the snapshot reservation, right?

Currently, we have this asymmetry where the `total` metric includes the snapshots waiting on the semaphore whereas the non-empty in-progress metric doesn't. 
</blockquote></details>

Thanks for catching - should be fixed now.


<!-- Sent from Reviewable.io -->

2022-08-03 21:05 UTC, aayushshah15 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84947#-:-N8_Wiq_ECBC3euJDD0B:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @KnightAsterial)



<!-- Sent from Reviewable.io -->

2022-08-03 21:49 UTC, AlexTalks commented
bors r+

2022-08-04 20:55 UTC, AlexTalks commented
bors r+

2022-08-05 03:06 UTC, merged