Revert "sql: Add database ID to sampled query log"
cockroachdb/cockroach pull request #85017
Opened 2022-07-25 18:14 UTC by THardy98

Reverts: #84195
This reverts commit 307817e96ee7ef4c5d6f908aa5fb01adbca5f62d.

Removes the DatabaseID field from the
`SampledQuery` telemetry log due to the potential of indefinite blocking
in the case of a lease acquisition failure. Protobuf field not reserved as 
no official build was released with these changes yet.

Release note (sql change): Removes the DatabaseID field from the
`SampledQuery` telemetry log due to the potential of indefinite blocking
in the case of a lease acquisition failure.

2022-07-25 18:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/85017)
<!-- Reviewable:end -->

2022-07-25 18:27 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85017#-:-N7qbGIG3nI8J8i0NFbJ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-07-26 13:17 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85017)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag and @THardy98)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85017#-N7udo2CBZuetxMMkPj6:-N7udo2D-zIy_726Zd1r:bdanrky) ([raw file](https://github.com/cockroachdb/cockroach/blob/61eaa5f1511001f8b644d07184850c13b6bc1d96/pkg/util/log/eventpb/telemetry.proto#L63)):*
> ```protobuf
> 
>   // Statement fingerprint ID of the query.
>   uint64 statement_fingerprint_id = 12 [(gogoproto.customname) = "StatementFingerprintID", (gogoproto.jsontag) = ',omitempty'];
> ```

change back fingerprint to 13 and add 12 as reserved


<!-- Sent from Reviewable.io -->

2022-07-27 15:05 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85017)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85017#-N7udo2CBZuetxMMkPj6:-N8-B0po6zTS54jwSfBE:bit542n) ([raw file](https://github.com/cockroachdb/cockroach/blob/61eaa5f1511001f8b644d07184850c13b6bc1d96/pkg/util/log/eventpb/telemetry.proto#L63)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

change back fingerprint to 13 and add 12 as reserved
</blockquote></details>

Reserved 12 and reverted back to 13.
Small `gen.go` change to accomodate `reserved` fields in the proto.


<!-- Sent from Reviewable.io -->

2022-07-27 17:45 UTC, maryliag approved these changes
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85017)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag and @THardy98)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85017#-N7udo2CBZuetxMMkPj6:-N8-kf0m060fjX6wGg5d:b-2a6prq) ([raw file](https://github.com/cockroachdb/cockroach/blob/61eaa5f1511001f8b644d07184850c13b6bc1d96/pkg/util/log/eventpb/telemetry.proto#L63)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Reserved 12 and reverted back to 13.
Small `gen.go` change to accomodate `reserved` fields in the proto.
</blockquote></details>

Move the reserved list to the end


<!-- Sent from Reviewable.io -->

2022-07-28 23:15 UTC, THardy98 commented
bors r+

2022-07-29 13:08 UTC, THardy98 commented
bors r-

2022-07-29 19:59 UTC, THardy98 commented
bors r+

2022-07-29 21:05 UTC, merged