Revert "Merge pull request #84354 from cockroachdb/blathers/backport-release-22.1-84195"
cockroachdb/cockroach pull request #85026
Opened 2022-07-25 19:21 UTC by THardy98

Reverts: #84195, PR that introduces the DatabaseID to the `SampledQuery`
telemetry log.

This reverts commit 0b9023d284e59e384a2ada31f1a7192cd260bf46, reversing
changes made to 8265e2a5f2e13738dea81039c53665b952fe6b81.

Removes the `DatabaseID` field from the `SampledQuery` telemetry log due to
the potential of indefinite blocking in the case of a lease acquisition
failure. Protobuf field not reserved as no official build was released
with these changes yet.

Release note (sql change): Removes the DatabaseID field from the
SampledQuery telemetry log due to the potential of indefinite blocking
in the case of a lease acquisition failure.

2022-07-25 19:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/85026)
<!-- Reviewable:end -->

2022-07-25 21:32 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85026#-:-N7rGZ-05LOFIbXMUzSL:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-07-26 11:07 UTC, rail commented
> Protobuf field not reserved as no official build was released
with these changes yet.

FYI, there is an extraordinary release (v22.1.5) in progress which uses [this commit](https://github.com/cockroachdb/cockroach/commit/a30a663cbd9323d34d50f343dd038af64671e25f).

2022-07-26 13:15 UTC, maryliag requested changes
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85026)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85026#-N7udQvLCmHLv2jwmayO:-N7udQvLCmHLv2jwmayP:b-dqvn80) ([raw file](https://github.com/cockroachdb/cockroach/blob/504b37f0cafdb786548e370b56cb4d87ef0cc07f/pkg/util/log/eventpb/telemetry.proto#L63)):*
> ```protobuf
> 
>   // Statement fingerprint ID of the query.
>   uint64 statement_fingerprint_id = 12 [(gogoproto.customname) = "StatementFingerprintID", (gogoproto.jsontag) = ',omitempty'];
> ```

from Rail's comment: keep the fingerprint as 13 and reserve 12


<!-- Sent from Reviewable.io -->

2022-07-27 15:05 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85026)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85026#-N7udQvLCmHLv2jwmayO:-N8-BEOJ34zKhqilboiq:bit542n) ([raw file](https://github.com/cockroachdb/cockroach/blob/504b37f0cafdb786548e370b56cb4d87ef0cc07f/pkg/util/log/eventpb/telemetry.proto#L63)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

from Rail's comment: keep the fingerprint as 13 and reserve 12
</blockquote></details>

Reserved 12 and reverted back to 13.
Small `gen.go` change to accomodate `reserved` fields in the proto.


<!-- Sent from Reviewable.io -->

2022-07-27 17:43 UTC, maryliag approved these changes
small nit
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85026#-:-N8-kRi08mzejG64C34Z:baex3hh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85026#-N7udQvLCmHLv2jwmayO:-N8-kGuQ7lfJpUcv4YGe:bi2i5lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/504b37f0cafdb786548e370b56cb4d87ef0cc07f/pkg/util/log/eventpb/telemetry.proto#L63)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Reserved 12 and reverted back to 13.
Small `gen.go` change to accomodate `reserved` fields in the proto.
</blockquote></details>

same comment as the other PR, put the list of reserved as the last thing


<!-- Sent from Reviewable.io -->

2022-07-27 19:12 UTC, merged