flowinfra: disable queueing mechanism of the flow scheduler by default
cockroachdb/cockroach pull request #85091
Opened 2022-07-26 21:10 UTC by yuzefovich

This commit disables the queueing mechanism of the flow scheduler as
part of the effort to remove that queueing altogether during 23.1
release cycle. To get there though we choose a conservative approach of
introducing a cluster setting that determines whether the queueing is
enabled or not, and if it is disabled, then we effectively a treating
`sql.distsql.max_running_flows` limit as infinite. By default, the
queueing is now disabled since recent experiments have shown that the
admission control does a good job of protecting the nodes from the
influx of remote flows.

Addresses: #34229.

Release note: None

2022-07-26 21:10 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/85091)
<!-- Reviewable:end -->

2022-07-28 13:18 UTC, miretskiy approved these changes
cdc is 👍

2022-08-01 14:05 UTC, cucaroach requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85091)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/flowinfra/cluster_test.go` line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85091#-N8OiLM38wqrsi0ZRncQ:-N8OiLM38wqrsi0ZRncR:b-hk27h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7b901d7d28ceb4900dd60c5c73b2180089a3e3a/pkg/sql/flowinfra/cluster_test.go#L389)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 	}
> ```

Why was this query removed?


<!-- Sent from Reviewable.io -->

2022-08-01 15:42 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85091)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

___
*[`pkg/sql/flowinfra/cluster_test.go` line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85091#-N8OiLM38wqrsi0ZRncQ:-N8P3FvTAgHGZH2E_u86:b-p62xbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7b901d7d28ceb4900dd60c5c73b2180089a3e3a/pkg/sql/flowinfra/cluster_test.go#L389)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Why was this query removed?
</blockquote></details>

I don't think it's needed here. Probably it was introduced to populate the range cache, but we are manually constructing the physical plan, so the range cache doesn't matter. This test if effectively a copy of `TestClusterFlow`, but in the tenant world, and in there we don't have such a query.


<!-- Sent from Reviewable.io -->

2022-08-01 16:11 UTC, cucaroach approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85091)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/flowinfra/cluster_test.go` line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85091#-N8OiLM38wqrsi0ZRncQ:-N8PAG8_2yIT_LGn9-3v:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7b901d7d28ceb4900dd60c5c73b2180089a3e3a/pkg/sql/flowinfra/cluster_test.go#L389)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I don't think it's needed here. Probably it was introduced to populate the range cache, but we are manually constructing the physical plan, so the range cache doesn't matter. This test if effectively a copy of `TestClusterFlow`, but in the tenant world, and in there we don't have such a query.
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2022-08-01 16:13 UTC, yuzefovich commented
TFTRs!

bors r+

2022-08-01 20:12 UTC, merged