sql: add columns to node_execution_insights
cockroachdb/cockroach pull request #85131
Opened 2022-07-27 14:30 UTC by j82w

This commit adds the following new columns
to crdb_internal.node_execution_insights table.

```
txn_id                     UUID NOT NULL,
txn_fingerprint_id         BYTES NOT NULL,
query                      STRING NOT NULL,
status                     STRING NOT NULL,
start_time                 TIMESTAMP NOT NULL,
end_time                   TIMESTAMP NOT NULL,
full_scan                  BOOL NOT NULL,
user_name                  STRING NOT NULL,
application_name           STRING NOT NULL,
database_name              STRING NOT NULL,
plan_gist                  STRING NOT NULL,
rows_read                  INT8 NOT NULL,
rows_written               INT8 NOT NULL,
priority                   FLOAT NOT NULL,
retries                    INT8 NOT NULL
```

Part of #81024

Release note (sql change): Adding new columns
to crdb_internal.node_execution_insights

2022-07-27 14:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/85131)
<!-- Reviewable:end -->

2022-07-27 16:27 UTC, matthewtodd requested changes
:tada: Woo! Thanks, Jake! Left a few comments inline.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-:-N8-TqAI8aTCv8tdjISg:b-9ulxkl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @matthewtodd)

___
*[`pkg/sql/executor_statement_metrics.go` line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-QaxYCFHQzRmFoWTB:-N8-QaxYCFHQzRmFoWTC:boqu7lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/executor_statement_metrics.go#L190)):*
> ```Go
> 		StatementError:       stmtErr,
> 		IndexRecommendations: planner.instrumentation.indexRecommendations,
> 		Query:                stmt.StmtNoConstants,
> ```

I think "no constants" is a good choice for now. In #81023 we'll want to have the option to show the constants to users with permission. (The constants, though sensitive, can be helpful when understanding why the execution may have been slow.) cc @kevin-v-ngo 
___
*[`pkg/sql/sqlstats/ssprovider.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-R6QjETH0tpSFlpME:-N8-R6QjETH0tpSFlpMF:bfxoxl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/ssprovider.go#L18)):*
> ```Go
> import (
> 	"context"
> 	"github.com/cockroachdb/cockroach/pkg/sql/sessiondata"
> ```

You can `dev build crlfmt` and [have Goland use it](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks#Enable-crlfmt-Watcher) to keep these imports organized. (I think the linter will complain if you don't?)
___
*[`pkg/sql/sqlstats/insights/insights.proto` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-RfT-9om7MZk_gDH-:-N8-RfT-9om7MZk_gDH0:by9dnir) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/insights/insights.proto#L42)):*
> ```protobuf
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/roachpb.StmtFingerprintID"];
>   double latency_in_seconds = 3;
>   string transaction_id = 4;
> ```

Remove this one.
___
*[`pkg/sql/sqlstats/insights/insights.proto` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-Rif64j4_wMOZ2Bf3:-N8-Rif64j4_wMOZ2Bf4:bl0wcmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/insights/insights.proto#L45)):*
> ```protobuf
>   string query = 5;
>   string status = 6;
>   google.protobuf.Timestamp start_time = 7[(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
> ```

nit: add a space between the `7` and the `[`.
___
*[`pkg/sql/sqlstats/insights/insights.proto` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-RtO46IxZDZnmrTzG:-N8-RtO5DTDVyMKJOP33:b-nqgmux) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/insights/insights.proto#L53)):*
> ```protobuf
>   string plan_gist = 13;
>   int64 rowsRead = 14;
>   int64 rowsWritten = 15;
> ```

nit: `rows_read` and `rows_written`. (Snake case for protobuf field names.)
___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-S51X1gNtKZoXnY33:-N8-S51X1gNtKZoXnY34:b28cty7) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go#L45)):*
> ```Go
> var _ sqlstats.Writer = &Container{}
> 
> func GetStatusString(statementError error) string {
> ```

nit: `getStatusString`. (To make it private.)
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-SKoCB6eoDmbvlNE6:-N8-SKoCB6eoDmbvlNE7:bghk65y) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/insights/integration/insights_test.go#L68)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	// Execute a fast statement that is under the latencyThreshold to verify it does not get logged
> ```

We have other, more focused tests that do this. See `detector_test.go`. This broader integration test is here mostly to show something working end-to-end; the branching out details are tested in faster unit tests lower in the stack.
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-SsVZ4zkSwq-JxhPK:-N8-SsVZ4zkSwq-JxhPL:b-isoua9) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/insights/integration/insights_test.go#L84)):*
> ```Go
> 	}, 1*time.Second)
> 
> 	// Verify time
> ```

nit: I think our [style guide](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines) requires that comments be full, punctuated sentences.
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-TK-D0875lGhhy3sw:-N8-TK-D0875lGhhy3sx:b-aoya1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/insights/integration/insights_test.go#L92)):*
> ```Go
> 			"end_time, "+
> 			"full_scan "+
> 			"FROM crdb_internal.node_execution_insights")
> ```

I feel ambivalent about testing the specifics of the data up here in this integration test, but I don't have any better ideas at the moment. :-)


<!-- Sent from Reviewable.io -->

2022-07-27 17:21 UTC, kevin-v-ngo commented
@j82w and @maryliag - do you think we can integrate the CREATE index recommendations in this table as well? https://github.com/cockroachdb/cockroach/issues/83782#issuecomment-1183634969

Having Create index recommendations for 'outliers' and slow executions would really complete the e2e experience with being actionable for suboptimal plans.

2022-07-27 17:38 UTC, maryliag reviewed
@kevin-v-ngo once that feature is added, it can be added to this table. Right now it would be empty.

> Reviewed 3 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-:-N8-fw6K66uLZcjrSEYt:bx9hwzx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @maryliag, and @matthewtodd)

___
*[`-- commits` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-gX7U68-DvD-wgeu7):*
nit: the release notes is used for the docs team, so try being more descriptive to help them out, listing the column name (you don't need to specify, just the names are enough)
___
*[`pkg/sql/crdb_internal.go` line 6235 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-glrcCoJf5jfvxmZb:-N8-glrcCoJf5jfvxmZc:b-r18qpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/505e458afd1dadbd0c89a7e9aa4a550b02436fd4/pkg/sql/crdb_internal.go#L6235)):*
> ```Go
> 	session_id                 STRING NOT NULL,
> 	txn_id                     UUID NOT NULL,
>   txn_fingerprint_id         BYTES NOT NULL,
> ```

this line seems to be misaligned (space vs tabs perhaps?)
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-iwRc1y1xbxLmlWTg:-N8-iwRc1y1xbxLmlWTh:b-a5k42r) ([raw file](https://github.com/cockroachdb/cockroach/blob/505e458afd1dadbd0c89a7e9aa4a550b02436fd4/pkg/sql/sqlstats/insights/integration/insights_test.go#L109)):*
> ```Go
> 	testutils.SucceedsWithin(t, func() error {
> 		rows, err := conn.QueryContext(ctx, "SELECT "+
> 			"crdb_internal.decode_plan_gist(plan_gist) "+
> ```

FYI, it is possible to have null values for plan_gist, so you would need to check if the value is not null, before calling this function.
But I don't think this test is necessary here, because it's testing the decode function, but we already have tests for that.


<!-- Sent from Reviewable.io -->

2022-07-27 17:45 UTC, kevin-v-ngo commented
> @kevin-v-ngo once that feature is added, it can be added to this table. Right now it would be empty.
> 
 
I guess my question is more on when will it be available? And if possible, can we have it as part of the V1 experience here.

2022-07-27 18:00 UTC, matthewtodd commented
@maryliag @j82w regarding release notes, I've been a little lax on these PRs (since a lot was in flux as we were figuring things out), instead aiming to lay out a first cohesive overview in the eventual PR that flips the cluster settings on by default.

2022-07-27 18:04 UTC, maryliag reviewed
> when will it be available? And if possible, can we have it as part of the V1 experience here
it will be available soon (by beginning of August), hopefully we can add to the V1

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-:-N8-oxVw5sDyCQn6eWgy:b-eo4cri)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @maryliag, and @matthewtodd)



<!-- Sent from Reviewable.io -->

2022-07-27 18:44 UTC, j82w reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @maryliag, and @matthewtodd)

___
*[`pkg/sql/crdb_internal.go` line 6235 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-glrcCoJf5jfvxmZb:-N8-qJ5E2Tn9qBCzmzSc:b-367xfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/505e458afd1dadbd0c89a7e9aa4a550b02436fd4/pkg/sql/crdb_internal.go#L6235)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this line seems to be misaligned (space vs tabs perhaps?)
</blockquote></details>

Fixed, it was using spaces instead of tabs.
___
*[`pkg/sql/sqlstats/ssprovider.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-R6QjETH0tpSFlpME:-N8-dPxW4ySi4MTEaCCO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/ssprovider.go#L18)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

You can `dev build crlfmt` and [have Goland use it](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks#Enable-crlfmt-Watcher) to keep these imports organized. (I think the linter will complain if you don't?)
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/insights/insights.proto` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-RfT-9om7MZk_gDH-:-N8-mjOx5uh76Jp5bFLq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/insights/insights.proto#L42)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Remove this one.
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-SKoCB6eoDmbvlNE6:-N8-mdXg4q1_mxXqn19U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/insights/integration/insights_test.go#L68)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

We have other, more focused tests that do this. See `detector_test.go`. This broader integration test is here mostly to show something working end-to-end; the branching out details are tested in faster unit tests lower in the stack.
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-TK-D0875lGhhy3sw:-N8-wWK3E5szGefcf42q:b-k3i9dh) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/insights/integration/insights_test.go#L92)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I feel ambivalent about testing the specifics of the data up here in this integration test, but I don't have any better ideas at the moment. :-)
</blockquote></details>

If you don't verify the data in the integration test how can you be sure that the data did not get corrupted and/or incorrectly converted at some point?


<!-- Sent from Reviewable.io -->

2022-07-27 19:03 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-:-N801h0KDlIvgaoVrJ7i:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w, @maryliag, and @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-TK-D0875lGhhy3sw:-N800Ve66eANc_r09mRv:b74jua5) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fad1ce4e06442e7f52ce896b0efa655f782523/pkg/sql/sqlstats/insights/integration/insights_test.go#L92)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

If you don't verify the data in the integration test how can you be sure that the data did not get corrupted and/or incorrectly converted at some point?
</blockquote></details>

I think I figured out why I was feeling that -- I had written this test first as a design tool, to help me see when I had gotten the right bits connected end-to-end, where showing something working (a row in the table!) gave me the confidence I needed at the time.

But I think you're probably on to something here: it may make sense for this test to now shift into more of a regression coverage tool, where we use it to make sure nothing gets broken going forward. And in that context, checking the data is certainly useful.


<!-- Sent from Reviewable.io -->

2022-07-28 13:00 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, 1 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-:-N83t6q0CYEZaMFqaulm:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w)



<!-- Sent from Reviewable.io -->

2022-07-28 16:20 UTC, j82w commented
bors r+

2022-07-28 16:26 UTC, kevin-v-ngo requested changes

2022-07-28 16:26 UTC, kevin-v-ngo commented on pkg/sql/crdb_internal.go
> +	end_time                   TIMESTAMP NOT NULL,
When are we going to derive elapsed time?

2022-07-28 16:26 UTC, kevin-v-ngo commented on pkg/sql/crdb_internal.go
> +	application_name           STRING NOT NULL,
app_name

2022-07-28 16:30 UTC, kevin-v-ngo commented on pkg/sql/crdb_internal.go
> +	statement_id               STRING NOT NULL,
Let's abbreviate statement -> stmt

statement_id -> stmt_id
stmt_fingerprint_id -> stmt_fingerprint_id

Seems like that's the pattern: https://www.cockroachlabs.com/docs/stable/crdb-internal.html#statement_statistics

2022-07-28 16:43 UTC, kevin-v-ngo commented on pkg/sql/crdb_internal.go
>  CREATE TABLE crdb_internal.node_execution_insights (
From the [brief](https://cockroachlabs.atlassian.net/wiki/spaces/SQLOBS/pages/2322268382/Troubleshooting+slow+and+failed+executions+90), seems like we're just missing the following:

retryable 
last_retry_reason
last_contended_row
index_recommendation

2022-07-28 16:53 UTC, j82w commented
bors r-

2022-07-28 17:46 UTC, j82w commented
bors r+

2022-07-28 17:47 UTC, j82w reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85131)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w and @kevin-v-ngo)

___
*[`pkg/sql/crdb_internal.go` line 6235 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-3DiMDyX8BvjKwrBN-r6-6235:-N84jOWZ9FciBs0gZHhz:b-rcfkw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc9f4213174cfd5ae0526f4981a119e9b49843c8/pkg/sql/crdb_internal.go#L6235)):*
<details><summary><i>Previously, kevin-v-ngo wrote…</i></summary><blockquote>

From the [brief](https://cockroachlabs.atlassian.net/wiki/spaces/SQLOBS/pages/2322268382/Troubleshooting+slow+and+failed+executions+90), seems like we're just missing the following:

retryable 
last_retry_reason
last_contended_row
index_recommendation
</blockquote></details>

This PR was marked as partial change for the issue. Those columns are more complicated to implement. To avoid making the PR to large I'm going to do a separate follow up PR. I will fix the column names specified in the other comments at that time too.
___
*[`pkg/sql/crdb_internal.go` line 6239 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-3DiMDyX8BvjKwrBN-r6-6239:-N84usHH4R3NxFMFLSSx:bud3zn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc9f4213174cfd5ae0526f4981a119e9b49843c8/pkg/sql/crdb_internal.go#L6239)):*
<details><summary><i>Previously, kevin-v-ngo wrote…</i></summary><blockquote>

Let's abbreviate statement -> stmt

statement_id -> stmt_id
stmt_fingerprint_id -> stmt_fingerprint_id

Seems like that's the pattern: https://www.cockroachlabs.com/docs/stable/crdb-internal.html#statement_statistics
</blockquote></details>

This will be fixed in a follow up PR. Merging this now to unblock other tasks.
___
*[`pkg/sql/crdb_internal.go` line 6244 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-3DiMDyX8BvjKwrBN-r6-6244:-N84kD_Q3p8S9rtKAZ3b:bxde8hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc9f4213174cfd5ae0526f4981a119e9b49843c8/pkg/sql/crdb_internal.go#L6244)):*
<details><summary><i>Previously, kevin-v-ngo wrote…</i></summary><blockquote>

When are we going to derive elapsed time?
</blockquote></details>

Elapsed time can easily be computed when needed.
___
*[`pkg/sql/crdb_internal.go` line 6247 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85131#-N8-3DiMDyX8BvjKwrBN-r6-6247:-N84ujAT4QlR_zPGFnnL:bud3zn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc9f4213174cfd5ae0526f4981a119e9b49843c8/pkg/sql/crdb_internal.go#L6247)):*
<details><summary><i>Previously, kevin-v-ngo wrote…</i></summary><blockquote>

app_name
</blockquote></details>

This will be fixed in a follow up PR. Merging this now to unblock other tasks.


<!-- Sent from Reviewable.io -->

2022-07-29 15:44 UTC, matthewtodd commented
Since we've got a green build and I'm eager to ship my branch that depends on these changes, I'm going to go ahead and kick off the bors process again:

bors r+

2022-07-29 18:55 UTC, merged