[WIP] sql: add DisableNotVisibleIndex to ScanFlags
cockroachdb/cockroach pull request #85239
Opened 2022-07-28 15:14 UTC by wenyihu6

This PR is still work in progress. This draft PR is created now to see the
effect of DisableNotVisibleIndex flag by checking the new output of some test
cases.

2022-07-28 15:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/85239)
<!-- Reviewable:end -->

2022-07-30 01:04 UTC, wenyihu6 commented
The first commit comes from https://github.com/cockroachdb/cockroach/pull/84912.

2022-08-02 21:49 UTC, michae2 requested changes
Nice!

> Reviewed 2 of 40 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-:-N8VX90d5TefRYXuud8Z:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rhu713, and @wenyihu6)

___
*[`pkg/sql/opt/memo/expr_format.go` line 465 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8VRq5F7P2loMqf3C6K:-N8VRq5GBkZlmSuXxh95:b-kcwwd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/memo/expr_format.go#L465)):*
> ```Go
> 			if private.Flags.DisableNotVisibleIndex {
> 				b.WriteString(" disabled not visible index feature")
> 			}
> ```

Let's only print this if an invisible index is used. I.e. `if md.Table(private.Table).Index(private.Index).IsNotVisible() && private.Flags.DisableNotVisibleIndex`. That's really the only time we will care if this flag is set. (And then this PR won't change so many files.)
___
*[`pkg/sql/opt/optbuilder/fk_cascade.go` line 304 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8VWOvU9lgKbmbDQpWp:-N8VWOvU9lgKbmbDQpWq:b-yef2yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/optbuilder/fk_cascade.go#L304)):*
> ```Go
> 			// Disable not visible index feature because this scan is for DELETE
> 			// CASCADE.
> 			true,
> ```

nit: Usually when passing literal values to a function call, we suffix them with a comment with the parameter name. In this case it would be something like: `true, /* disableNotVisibleIndex */`. I think that's all you really need to do; I don't think you need this longer comment.


<!-- Sent from Reviewable.io -->

2022-08-03 03:49 UTC, wenyihu6 commented
*[`pkg/sql/opt/memo/expr_format.go` line 465 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8VRq5F7P2loMqf3C6K:-N8WlyNQD-fF4dbD7aNK:b-zg6hfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/memo/expr_format.go#L465)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Let's only print this if an invisible index is used. I.e. `if md.Table(private.Table).Index(private.Index).IsNotVisible() && private.Flags.DisableNotVisibleIndex`. That's really the only time we will care if this flag is set. (And then this PR won't change so many files.)
</blockquote></details>

That makes sense. This brings up some thoughts about how I am organizing the testdata. 

I was planning to use these existing test cases to check if the flag has been passed correctly. If we make it print only when invisible indexes are used, we can't use our existing testdata to check the flag any more. We would need to add more test cases to check for flags. But the test cases that we want to add would be very similar to what we already have under `pkg/sql/opt/optbuilder/testdata`(fk-checks, unique-checks). I was also talking about this with @mgartner last week. 

I think we can print this flag only when invisible indexes are used. And we can add a small subset of test cases that involve fk-checks and unique-checks under `opt`. That would make things more clear as well---all the testdata changes for this feature will be all together.


<!-- Sent from Reviewable.io -->

2022-08-03 15:50 UTC, mgartner reviewed
Very nice!

> Reviewed 40 of 40 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-:-N8ZOPPY-5V6FShodcyN:b-j7qk9t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @rhu713, and @wenyihu6)

___
*[`pkg/sql/opt/memo/expr.go` line 374 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8ZGv5qDzYXsalRyr7W:-N8ZGv5qDzYXsalRyr7X:b-3zdaik) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/memo/expr.go#L374)):*
> ```Go
> 	// constraint check, we will temporarily disable the not visible index feature
> 	// and treat all indexes as they are visible. Default behaviour is to enable
> 	// the not visible feature.
> ```

nit: It can be helpful to future readers to explicitly spell out what happens when this is true and what happens when this is false.
___
*[`pkg/sql/opt/memo/expr_format.go` line 465 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8VRq5F7P2loMqf3C6K:-N8ZIRlM3xJHYx4tbjlz:b-woraua) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/memo/expr_format.go#L465)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

That makes sense. This brings up some thoughts about how I am organizing the testdata. 

I was planning to use these existing test cases to check if the flag has been passed correctly. If we make it print only when invisible indexes are used, we can't use our existing testdata to check the flag any more. We would need to add more test cases to check for flags. But the test cases that we want to add would be very similar to what we already have under `pkg/sql/opt/optbuilder/testdata`(fk-checks, unique-checks). I was also talking about this with @mgartner last week. 

I think we can print this flag only when invisible indexes are used. And we can add a small subset of test cases that involve fk-checks and unique-checks under `opt`. That would make things more clear as well---all the testdata changes for this feature will be all together.
</blockquote></details>

I think having this flag printed for all the optbuilder tests is useful because it proves that optbuilder is setting the flag for all the necessary scans. Existing optbuilder tests already cover all the interesting cases when this flag should be set, so this avoids having to rewrite a bunch of test cases for FK checks, cascades, UPSERT conflict detection, etc.

We could hide this flag for non-optbuilder tests by creating a new expr formatter flag that enables formatting of this flag here:

https://github.com/cockroachdb/cockroach/blob/4e455f02cc7bc580d58d3f924087810e4808a5a5/pkg/sql/opt/memo/expr_format.go#L42-L94

And setting the formatting flag for optbuilder tests here:

https://github.com/cockroachdb/cockroach/blob/367ccec1ce5b9e6ffc84a8e28e638f18269f0948/pkg/sql/opt/optbuilder/builder_test.go#L63-L71
___
*[`pkg/sql/opt/optbuilder/mutation_builder_arbiter.go` line 597 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8ZJmxs0WouWxigTXT9:-N8ZJmxs0WouWxigTXTA:b-wteaao) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L597)):*
> ```Go
> 			// Disable not visible index feature because this scan is for findArbiters
> 			// which is for UPSERT, INSERT ON CONFLICT DO NOTHING or DO UPDATE SET.
> 			true,
> ```

This is a weird case where we build a scan, but we never actually use the scan in the memo. We only use the scope it creates here:

https://github.com/cockroachdb/cockroach/blob/91ea6948f7ed6e6f66ed37400642db8a78a57ca0/pkg/sql/opt/optbuilder/partial_index.go#L129

and here:

https://github.com/cockroachdb/cockroach/blob/91ea6948f7ed6e6f66ed37400642db8a78a57ca0/pkg/sql/opt/optbuilder/partial_index.go#L133

and its relational properties here:

https://github.com/cockroachdb/cockroach/blob/91ea6948f7ed6e6f66ed37400642db8a78a57ca0/pkg/sql/opt/optbuilder/partial_index.go#L179

So, we don't need to pass `true` here. If you change this to `false`, the optbuilder test output should not change. 
___
*[`pkg/sql/opt/optbuilder/select.go` line 126 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8ZLK1jCQTQz37MV_Dk:-N8ZLK1kAii1IBLucTTz:bpnkyel) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/optbuilder/select.go#L126)):*
> ```Go
> 				// Enable not visible index feature because this scan is for buildJoin,
> 				// buildFromWithLateral, and buildFromTablesRightDeep (called by
> 				// buildInputForUpdate, buildSelectClause).
> ```

nit: technically this is for normal SELECTs too
___
*[`pkg/sql/opt/optbuilder/select.go` line 416 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8ZMOQIDaMZpSXyR44I:-N8ZMOQIDaMZpSXyR44J:b-7cntcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/optbuilder/select.go#L416)):*
> ```Go
> 
> 	// Enable not visible index feature because this scan is for a normal SELECT
> 	// query.
> ```

nit: technically this is for tables referenced by their OID - see the comment above.


<!-- Sent from Reviewable.io -->

2022-08-03 15:57 UTC, michae2 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85239)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rhu713, and @wenyihu6)

___
*[`pkg/sql/opt/memo/expr_format.go` line 465 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8VRq5F7P2loMqf3C6K:-N8ZP0lP1RufanzikR_S:b-1vlou4) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/memo/expr_format.go#L465)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think having this flag printed for all the optbuilder tests is useful because it proves that optbuilder is setting the flag for all the necessary scans. Existing optbuilder tests already cover all the interesting cases when this flag should be set, so this avoids having to rewrite a bunch of test cases for FK checks, cascades, UPSERT conflict detection, etc.

We could hide this flag for non-optbuilder tests by creating a new expr formatter flag that enables formatting of this flag here:

https://github.com/cockroachdb/cockroach/blob/4e455f02cc7bc580d58d3f924087810e4808a5a5/pkg/sql/opt/memo/expr_format.go#L42-L94

And setting the formatting flag for optbuilder tests here:

https://github.com/cockroachdb/cockroach/blob/367ccec1ce5b9e6ffc84a8e28e638f18269f0948/pkg/sql/opt/optbuilder/builder_test.go#L63-L71
</blockquote></details>

I said the same thing to Wenyi this morning in slack :slightly_smiling_face: I'm ok with always printing in opttests. It's only `EXPLAIN (OPT, VERBOSE)` that I care about not printing unless it's relevant.


<!-- Sent from Reviewable.io -->

2022-08-03 19:34 UTC, wenyihu6 commented
*[`pkg/sql/opt/optbuilder/mutation_builder_arbiter.go` line 597 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8ZJmxs0WouWxigTXT9:-N8_BqR81oOawzswiDEd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L597)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is a weird case where we build a scan, but we never actually use the scan in the memo. We only use the scope it creates here:

https://github.com/cockroachdb/cockroach/blob/91ea6948f7ed6e6f66ed37400642db8a78a57ca0/pkg/sql/opt/optbuilder/partial_index.go#L129

and here:

https://github.com/cockroachdb/cockroach/blob/91ea6948f7ed6e6f66ed37400642db8a78a57ca0/pkg/sql/opt/optbuilder/partial_index.go#L133

and its relational properties here:

https://github.com/cockroachdb/cockroach/blob/91ea6948f7ed6e6f66ed37400642db8a78a57ca0/pkg/sql/opt/optbuilder/partial_index.go#L179

So, we don't need to pass `true` here. If you change this to `false`, the optbuilder test output should not change. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-03 19:46 UTC, wenyihu6 commented
*[`pkg/sql/opt/memo/expr_format.go` line 465 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8VRq5F7P2loMqf3C6K:-N8_EXCj9MVP62JwUiRE:baxt0eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/memo/expr_format.go#L465)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I said the same thing to Wenyi this morning in slack :slightly_smiling_face: I'm ok with always printing in opttests. It's only `EXPLAIN (OPT, VERBOSE)` that I care about not printing unless it's relevant.
</blockquote></details>

I just pushed the changes. The logic is a bit more complicated now; initially we are printing out "flags:" whenever the Flags is nonempty. But now, there is another case where we don't want to print "flags"; when invisible index is the only flag on and we are not scanning an invisible index.


<!-- Sent from Reviewable.io -->

2022-08-03 21:54 UTC, wenyihu6 commented
*[`pkg/sql/opt/optbuilder/fk_cascade.go` line 304 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8VWOvU9lgKbmbDQpWp:-N8_gvNj8VymxjI_duN5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/optbuilder/fk_cascade.go#L304)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Usually when passing literal values to a function call, we suffix them with a comment with the parameter name. In this case it would be something like: `true, /* disableNotVisibleIndex */`. I think that's all you really need to do; I don't think you need this longer comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-03 22:42 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thank you! Nice work.

> Reviewed 22 of 40 files at r5, 1 of 3 files at r6, 9 of 32 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-:-N8_rpHI4PQe2_klP4Eg:b-hzhm6l)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @rhu713, and @wenyihu6)

___
*[`pkg/sql/opt/memo/expr.go` line 709 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8_pYJ63uRTKlUbT5OC:-N8_pYJ63uRTKlUbT5OD:bxmz0ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5094ae36794f7dfc088da40cd1535107bfa81f7/pkg/sql/opt/memo/expr.go#L709)):*
> ```Go
> // is true or if the scan index is actually invisible.
> func (s *ScanPrivate) showInvisibleIndexInfo(md *opt.Metadata, alwaysShowInvisibleIndexInfo bool) bool {
> 	if alwaysShowInvisibleIndexInfo || s.IsNotVisibleIndex(md) {
> ```

nit: This could `return alwaysShowInvisibleIndexInfo || s.IsNotVisibleIndex(md)` directly.
___
*[`pkg/sql/opt/memo/expr_format.go` line 465 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8VRq5F7P2loMqf3C6K:-N8_rlnA7vJFaCEG8D4q:b-9755fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/memo/expr_format.go#L465)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I just pushed the changes. The logic is a bit more complicated now; initially we are printing out "flags:" whenever the Flags is nonempty. But now, there is another case where we don't want to print "flags"; when invisible index is the only flag on and we are not scanning an invisible index.
</blockquote></details>

Thank you!
___
*[`pkg/sql/opt/memo/expr_format.go` line 472 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8_pFyr18tae2zk-UGf:-N8_pFyr18tae2zk-UGg:bndnf84) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5094ae36794f7dfc088da40cd1535107bfa81f7/pkg/sql/opt/memo/expr_format.go#L472)):*
> ```Go
> 
> 			if private.showInvisibleIndexInfo(md, f.HasFlags(ExprFmtAlwaysShowInvisibleIndexInfo)) {
> 				if private.Flags.DisableNotVisibleIndex {
> ```

nit: I would flip these conditions around (so that `if private.Flags.DisableNotVisibleIndex` is on the outside), or even better combine them into one if statement.



_Code quote:_
```Go
			if private.showInvisibleIndexInfo(md, f.HasFlags(ExprFmtAlwaysShowInvisibleIndexInfo)) {
				if private.Flags.DisableNotVisibleIndex {
```


<!-- Sent from Reviewable.io -->

2022-08-04 11:38 UTC, wenyihu6 commented
*[`pkg/sql/opt/memo/expr.go` line 709 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8_pYJ63uRTKlUbT5OC:-N8cdLBHCAkaHcZcT-bU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5094ae36794f7dfc088da40cd1535107bfa81f7/pkg/sql/opt/memo/expr.go#L709)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: This could `return alwaysShowInvisibleIndexInfo || s.IsNotVisibleIndex(md)` directly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-04 11:38 UTC, wenyihu6 commented
*[`pkg/sql/opt/memo/expr_format.go` line 472 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8_pFyr18tae2zk-UGf:-N8cdXXN6RT6BHjze87w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5094ae36794f7dfc088da40cd1535107bfa81f7/pkg/sql/opt/memo/expr_format.go#L472)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: I would flip these conditions around (so that `if private.Flags.DisableNotVisibleIndex` is on the outside), or even better combine them into one if statement.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-04 13:21 UTC, mgartner approved these changes
> Reviewed 8 of 32 files at r7, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85239)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rhu713, and @wenyihu6)

___
*[`pkg/sql/opt/memo/expr.go` line 700 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8d-rwl16IzwlX6qn3K:-N8d-rwl16IzwlX6qn3L:b21zwjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2904adc87f50499fabf856b00991e1892632236d/pkg/sql/opt/memo/expr.go#L700)):*
> ```Go
> // IsNotVisibleIndex returns true if the index being scanned is a not visible
> // index.
> func (s *ScanPrivate) IsNotVisibleIndex(md *opt.Metadata) bool {
> ```

nit: IsNotVisibleIndexScan
___
*[`pkg/sql/opt/memo/expr_format.go` line 465 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8VRq5F7P2loMqf3C6K:-N8d0-eC2UgkvEAaTpRQ:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/192418c35565c2699fb734470c78bd1965f9ee0d/pkg/sql/opt/memo/expr_format.go#L465)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Thank you!
</blockquote></details>

:+1: 
___
*[`pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade` line 1575 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8cxgmS920chWYYXUYF:-N8cxgmS920chWYYXUYG:btdyph3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a72e9dcaa75ce2fbdad8be53d6f3885fb60d7706/pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade#L1575)):*
> ```
>            │    │    ├── scan t.public.child_diff_type
>            │    │    │    ├── columns: t.public.child_diff_type.c:12(int!null) t.public.child_diff_type.p:13(int2)
>            │    │    │    ├── flags: disabled not visible index feature
> ```

Isn't this a case where we expect the flag to be set? 
___
*[`pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade` line 1626 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8cxnPO3PrUZarRNgZa:-N8cxnPO3PrUZarRNgZb:b2ua52g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a72e9dcaa75ce2fbdad8be53d6f3885fb60d7706/pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade#L1626)):*
> ```
>                           ├── scan t.public.parent_diff_type
>                           │    ├── columns: t.public.parent_diff_type.p:20(int!null)
>                           │    ├── flags: disabled not visible index feature
> ```

Shouldn't the flag be set here too?


<!-- Sent from Reviewable.io -->

2022-08-04 19:31 UTC, michae2 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85239)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rhu713, and @wenyihu6)

___
*[`pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade` line 1575 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8cxgmS920chWYYXUYF:-N8eKEqd20VYzz74oPmu:b-u9evy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a72e9dcaa75ce2fbdad8be53d6f3885fb60d7706/pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade#L1575)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Isn't this a case where we expect the flag to be set? 
</blockquote></details>

Wow, good catch!

After adding that same case to `pkg/sql/opt/optbuilder/testdata/fk-on-delete-cascade` it looks like the flag is also missing for the scan of the child in the cascaded delete:

```
+
+# Test cascade to a child with a reference column of a different type.
+exec-ddl
+CREATE TABLE parent_diff_type (p INT PRIMARY KEY)
+----
+
+exec-ddl
+CREATE TABLE child_diff_type (
+  c INT PRIMARY KEY,
+  p INT2 REFERENCES parent_diff_type(p) ON DELETE CASCADE
+)
+----
+
+build-cascades format=show-all
+DELETE FROM parent_diff_type WHERE p = 0
+----
+root
+ ├── delete t.public.parent_diff_type
+ │    ├── columns: <none>
+ │    ├── fetch columns: t.public.parent_diff_type.p:4(int)
+ │    ├── cascades
+ │    │    └── child_diff_type_p_fkey
+ │    ├── cardinality: [0 - 0]
+ │    ├── volatile, mutations
+ │    ├── stats: [rows=0]
+ │    └── select
+ │         ├── columns: t.public.parent_diff_type.p:4(int!null) t.public.parent_diff_type.crdb_internal_mvcc_timestamp:5(decimal) t.public.parent_diff_type.tableoid:6(oid)
+ │         ├── cardinality: [0 - 1]
+ │         ├── stats: [rows=1, distinct(4)=1, null(4)=0, avgsize(4)=4]
+ │         ├── key: ()
+ │         ├── fd: ()-->(4-6)
+ │         ├── prune: (5,6)
+ │         ├── scan t.public.parent_diff_type
+ │         │    ├── columns: t.public.parent_diff_type.p:4(int!null) t.public.parent_diff_type.crdb_internal_mvcc_timestamp:5(decimal) t.public.parent_diff_type.tableoid:6(oid)
+ │         │    ├── stats: [rows=1000, distinct(4)=1000, null(4)=0, avgsize(4)=4]
+ │         │    ├── key: (4)
+ │         │    ├── fd: (4)-->(5,6)
+ │         │    └── prune: (4-6)
+ │         └── filters
+ │              └── eq [type=bool, outer=(4), constraints=(/4: [/0 - /0]; tight), fd=()-->(4)]
+ │                   ├── variable: t.public.parent_diff_type.p:4 [type=int]
+ │                   └── const: 0 [type=int]
+ └── cascade
+      └── delete t.public.child_diff_type
+           ├── columns: <none>
+           ├── fetch columns: t.public.child_diff_type.c:11(int) t.public.child_diff_type.p:12(int2)
+           ├── cardinality: [0 - 0]
+           ├── volatile, mutations
+           ├── stats: [rows=0]
+           └── select
+                ├── columns: t.public.child_diff_type.c:11(int!null) t.public.child_diff_type.p:12(int2!null)
+                ├── stats: [rows=10, distinct(12)=1, null(12)=0, avgsize(12)=4]
+                ├── key: (11)
+                ├── fd: ()-->(12)
+                ├── prune: (11)
+                ├── scan t.public.child_diff_type
+                │    ├── columns: t.public.child_diff_type.c:11(int!null) t.public.child_diff_type.p:12(int2)
+                │    ├── stats: [rows=1000, distinct(11)=1000, null(11)=0, avgsize(11)=4, distinct(12)=100, null(12)=10, avgsize(12)=4]
+                │    ├── key: (11)
+                │    ├── fd: (11)-->(12)
+                │    └── prune: (11,12)
+                └── filters
+                     ├── eq [type=bool, outer=(12), constraints=(/12: [/0 - /0]; tight), fd=()-->(12)]
+                     │    ├── variable: t.public.child_diff_type.p:12 [type=int2]
+                     │    └── const: 0 [type=int]
+                     └── is-not [type=bool, outer=(12), constraints=(/12: (/NULL - ]; tight)]
+                          ├── variable: t.public.child_diff_type.p:12 [type=int2]
+                          └── null [type=int2]
```


<!-- Sent from Reviewable.io -->

2022-08-04 19:37 UTC, wenyihu6 commented
> 

Yeah. I think its because of how we are setting the flag for `ExprFmtFlags`. Because `ShowAll` has 0000 0000, it is actually hiding the flag for `ExprFmtAlwaysShowNotVisibleIndexInfo`. Note how all the other flags have Hide... and `ExprFmtAlwaysShowNotVisibleIndexInfo` is the only flag that is showing things. So I would need to change the value for `ShowAll` and `HideAll` to make things right. I want to make another PR so that the flags can take into account of flags that are showing things.

2022-08-04 22:33 UTC, wenyihu6 commented
*[`pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade` line 1575 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8cxgmS920chWYYXUYF:-N8ey0w_EZz4SadB6wyE:b-2wip6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a72e9dcaa75ce2fbdad8be53d6f3885fb60d7706/pkg/sql/opt/optbuilder/testdata/fk-on-update-cascade#L1575)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Yeah. I think its because of how we are setting the flag for `ExprFmtFlags`. Because `ShowAll` has 0000 0000, it is actually hiding the flag for `ExprFmtAlwaysShowNotVisibleIndexInfo`. Note how all the other flags have Hide... and `ExprFmtAlwaysShowNotVisibleIndexInfo` is the only flag that is showing things. So I would need to change the value for `ShowAll` and `HideAll` to make things right. I want to make another PR so that the flags can take into account of flags that are showing things. 
</blockquote></details>

Michael and I talked about this for a bit and decided that staying with our existing flags is probably better. Initially, I was thinking about introducing show flags and writing the const `ExprFmtShowAll` and `ExprFmtHideAll` separately by doing OR of every show flags and OR of every hide flags. But if we introduce show flags, we might need to change the logic at some places. For example, [here](https://github.com/cockroachdb/cockroach/blob/06bcc12937a19bfe55124e29e3544a587a5129eb/pkg/sql/opt/testutils/opttester/opt_tester.go#L90-L89), we can no longer just use this map for every flags. We have to introduce a new map for show flags as well.


<!-- Sent from Reviewable.io -->

2022-08-05 16:59 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Excellent. Good job digging into the exprfmt flags!

> Reviewed 17 of 18 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-:-N8iwEJ28_z8jKQSNb4h:b5pxq2p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @rhu713, and @wenyihu6)

___
*[`pkg/sql/opt/memo/expr.go` line 379 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8iu7Hi5_w5GhzT1pXe:-N8iu7Hj8d3-g4AFNbc9:bydoro0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4965eb63ffe89380dce6e7df921430d5fc47eb3/pkg/sql/opt/memo/expr.go#L379)):*
> ```Go
> 	// table to generate equivalent memo groups. If DisableNotVisibleIndex is
> 	// true, optimizer will also generate equivalent memo group using the
> 	// invisible index. Otherwise, optimizer will ignore the invisible indexes.
> ```

This is a great comment! :100:


<!-- Sent from Reviewable.io -->

2022-08-05 17:01 UTC, michae2 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85239)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @rhu713, and @wenyihu6)

___
*[`pkg/sql/opt/memo/expr_format.go` line 75 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85239#-N8iwqrr3x-Srld_P0Tm:-N8iwqrr3x-Srld_P0Tn:bh9ahfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4965eb63ffe89380dce6e7df921430d5fc47eb3/pkg/sql/opt/memo/expr_format.go#L75)):*
> ```Go
> // a flag that show things, ShowAll = 0000..000 would actually turn this flag
> // off. Thus, in order for ExprFmtShowAll and ExprFmtHideAll to be correct, we
> // can only add flags to hide things but not flags to show things.
> ```

Thank you for taking the time to document this, as well. Really thoughtful.


<!-- Sent from Reviewable.io -->

2022-08-05 22:17 UTC, wenyihu6 commented
TFTRs! 

bors r+

2022-08-06 00:27 UTC, merged