sql: implement new function resolution to work with UDF
cockroachdb/cockroach pull request #85391
Opened 2022-08-01 02:56 UTC by chengxiong-ruan

2022-08-01 02:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/85391)
<!-- Reviewable:end -->

2022-08-01 20:30 UTC, ajwerner reviewed
I only made it through the first commit but I still think it's worth flushing. 

I don't think your optimizations are safe in the general case. It feels to me like what we want to do is make an in-memory cache for the builtin overloads such that when we resolve a builtin and there are no UDFs with the same name that we don't allocate anything. We can optimize the usage of UDFs later. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-:-N8Q5Jdt9K6z9DyAjzoe:b-vl1jhb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @miretskiy)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q36Fq4NFDNFAKDFq5):*
nit: this commit modifies
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q3IyS7rFoS00gnGSG):*
Can you rework and expand the last sentence to explain where exactly the cache exists? 



_Code quote:_
```
  resolver. A cache of Overload is added to schema layer to
  hoepfully can save some effort on protobuf conversions.
```
___
*[`pkg/sql/catalog/schemadesc/schema_desc.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4lCfEEvHk4eEHEnC:-N8Q4lCfEEvHk4eEHEnD:bvs5tc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/catalog/schemadesc/schema_desc.go#L59)):*
> ```Go
> 	// list of overload signatures. This helps to avoid converting a function
> 	// signature protobuf to a ResolvedFunctionDefinition over and over again.
> 	prefixedFuncDefs map[string]*tree.ResolvedFunctionDefinition
> ```

I don't think this is kosher. You're going to have multiple different sessions accessing this cache at one. Also, you need to make sure the leasing remains coherent. This is why the hydrated cache goes to such lengths to achieve its goals. 

You could do this on the mutable, but I have to imagine it doesn't matter there. 
___
*[`pkg/sql/sem/tree/function_definition.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q3j084WKSditpCGlL:-N8Q3j084WKSditpCGlM:bxmrrsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L41)):*
> ```Go
> // overloads prefixed wit schema name.
> type ResolvedFunctionDefinition struct {
> 	Name string
> ```

Should `Name` here be of the `Name` type?
___
*[`pkg/sql/sem/tree/function_definition.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q3furD07yuXb2wKBg:-N8Q3furD07yuXb2wKBh:b-og0gxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L54)):*
> ```Go
> // It indicates that the overload is defined with the specified schema.
> type PrefixedOverload struct {
> 	Schema string
> ```

should `Schema` here be of the `Name` type?
___
*[`pkg/sql/sem/tree/function_definition.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4Id11UkQ4XBpHSi8:-N8Q4Id11UkQ4XBpHSi9:b-70jlmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L284)):*
> ```Go
> // error is returned if there is any overload with different Class.
> func (fd *ResolvedFunctionDefinition) GetClass() (FunctionClass, error) {
> 	return getFuncClass(fd.Name, toOverloads(fd.Overloads))
> ```

these scare me because they are going to allocate and I have to imagine `GetClass` gets called in the optimizer under the planning path. Should we change the prefixes to be a parallel slice to the overloads and then access them via methods? 



_Code quote:_
```Go
func (fd *ResolvedFunctionDefinition) GetClass() (FunctionClass, error) {
	return getFuncClass(fd.Name, toOverloads(fd.Overloads))
}

// GetReturnLabel returns function ReturnLabel by checking each overload and
// returns a ReturnLabel if all overloads have a ReturnLabel of the same length.
// Ambiguous error is returned if there is any overload has ReturnLabel of a
// different length. This is good enough since we don't create UDF with
// ReturnLabel.
func (fd *ResolvedFunctionDefinition) GetReturnLabel() ([]string, error) {
	return getFuncReturnLabels(fd.Name, toOverloads(fd.Overloads))
}
```
___
*[`pkg/sql/sem/tree/function_definition.go` line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q46c20MqEUYRCL_5i:-N8Q46c20MqEUYRCL_5j:b-z3nn0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L380)):*
> ```Go
> // searchPath are searched. A nil is returned if no function is found. It's
> // caller's choice to error out if function not found.
> func GetBuiltinFuncDefinition(
> ```

is there any reason these functions need to be in the `tree` package?



_Code quote:_
```Go
// PrefixBuiltinFunctionDefinition prefix all overloads in a function definition
// with a schema name. Note that this function can only be used for builtin
// function. Hence, HasUDF is set to false.
func PrefixBuiltinFunctionDefinition(
	def *FunctionDefinition, schema string,
) *ResolvedFunctionDefinition {
	ret := &ResolvedFunctionDefinition{
		Name:      def.Name,
		Overloads: make([]*PrefixedOverload, 0, len(def.Definition)),
	}
	for _, o := range def.Definition {
		ret.Overloads = append(
			ret.Overloads,
			&PrefixedOverload{Schema: schema, Overload: o},
		)
	}
	return ret
}

// GetBuiltinFuncDefinitionOrFail is similar to GetBuiltinFuncDefinition but
// fail if function is not found.
func GetBuiltinFuncDefinitionOrFail(
	fName *FunctionName, searchPath SearchPath,
) (*ResolvedFunctionDefinition, error) {
	def, err := GetBuiltinFuncDefinition(fName, searchPath)
	if err != nil {
		return nil, err
	}
	if def == nil {
		return nil, pgerror.Newf(pgcode.UndefinedFunction, "unknown function: %s", fName.String())
	}
	return def, nil
}

// GetBuiltinFuncDefinition search for a builtin function given a function name
// and a search path. If function name is prefixed, only the builtin functions
// in the specific schema are searched. Otherwise, all schemas on the given
// searchPath are searched. A nil is returned if no function is found. It's
// caller's choice to error out if function not found.
func GetBuiltinFuncDefinition(
```


<!-- Sent from Reviewable.io -->

2022-08-01 20:52 UTC, mgartner requested changes
I did a first pass over all the commits, but did not look at the schema-y stuff in too much detail.

> Reviewed 29 of 29 files at r1, 3 of 3 files at r2, 7 of 7 files at r3, 38 of 38 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-:-N8QAWzHBgp9XbVfwekk:b9szdzn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @miretskiy)

___
*[`pkg/sql/schema_resolver.go` line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PpvUYDV5TijGAZWWG:-N8PpvUYDV5TijGAZWWH:b-la4czb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/schema_resolver.go#L406)):*
> ```Go
> 
> 	if builtinDef == nil && udfDef == nil {
> 		// Try a little harder.
> ```

nit: expand this comment
___
*[`pkg/sql/catalog/schema.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PltDXAuhcAlBvJOzE:-N8PltDYAX_r0iZY-LrZ:biplcsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/catalog/schema.go#L38)):*
> ```Go
> 	// GetPrefixedFuncDefinition returns a ResolvedFunctionDefinition given a
> 	// function name.
> 	GetPrefixedFuncDefinition(name string) (*tree.ResolvedFunctionDefinition, bool)
> ```

nit: Would "qualified" be a better word than "prefixed" here and in other places where you've used prefix in this PR?
___
*[`pkg/sql/opt/cat/catalog.go` line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PmLBX7jsTkcuwV9F4:-N8PmLBX7jsTkcuwV9F5:b-2pmd37) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/opt/cat/catalog.go#L145)):*
> ```Go
> 	) (*tree.ResolvedFunctionDefinition, error)
> 
> 	// ResolveFunctionByOID resolves a function overload by OID
> ```

nit: add `.` the the end of the sentence.
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 286 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q9ISV9evcYKMa8Zbt:-N8Q9ISV9evcYKMa8Zbu:b-lhapti) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc192675b7608c20f0ab1dfbbd35c10caef4ae/pkg/sql/opt/exec/execbuilder/scalar.go#L286)):*
> ```Go
> 	}
> 	// TODO(mgartner): Consider modifying this to use a function resolver. Or is a
> 	// function definition needed here at all?
> ```

This occurs after the query has been optimized. It builds an optimizer expression of a function back into a tree.FuncExpr that can be evaluated during execution. I don't see why we would need to resolve anything at this point - the function overload has to be resolved already.
___
*[`pkg/sql/opt/testutils/testcat/function.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pmmt0DyHB4MVvOQXe:-N8Pmmt0DyHB4MVvOQXf:bnabq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/opt/testutils/testcat/function.go#L54)):*
> ```Go
> // ResolveFunctionByOID part of the tree.FunctionReferenceResolver interface.
> func (tc *Catalog) ResolveFunctionByOID(ctx context.Context, oid oid.Oid) (*tree.Overload, error) {
> 	return nil, nil
> ```

nit: return an assertion error stating the resolving a function by OID is not supported by the test catalog.
___
*[`pkg/sql/sem/transform/aggregates.go` line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pvs9L6xbMwgL5zdZ7:-N8Pvs9L6xbMwgL5zdZ8:b9rox1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc192675b7608c20f0ab1dfbbd35c10caef4ae/pkg/sql/sem/transform/aggregates.go#L41)):*
> ```Go
> 			return true, expr
> 		}
> 		fd, err := t.Func.Resolve(v.ctx, &v.searchPath, v.funcResolver)
> ```

I don't think we need a resolver here until we support user-defined aggregate functions. I'm inclined to leave this TODO here and not make any changes to this file until they can be tested. What do you think?
___
*[`pkg/sql/sem/transform/expr_transform.go` line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pw8_k5fq5t62QmAtH:-N8Pw8_k5fq5t62QmAtI:b-gh62nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc192675b7608c20f0ab1dfbbd35c10caef4ae/pkg/sql/sem/transform/expr_transform.go#L66)):*
> ```Go
> 		ctx:          ctx,
> 		searchPath:   searchPath,
> 		funcResolver: funcResolver,
> ```

This is legacy transformation logic. I'd like to rip it out at some point. Can we just leave as-is for now?
___
*[`pkg/sql/sem/tree/function_definition.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pnyp5-84-vN4hoeon:-N8Pnyp5-84-vN4hoeoo:bgvgfnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L39)):*
> ```Go
> 
> // ResolvedFunctionDefinition is similar to FunctionDefinition but with all the
> // overloads prefixed wit schema name.
> ```

nit: wit => with
___
*[`pkg/sql/sem/tree/function_definition.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pq_En0y9TGhLlDu7g:-N8Pq_En0y9TGhLlDu7h:b-xncokn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L48)):*
> ```Go
> 	ExplicitSchema bool
> 
> 	Overloads []*PrefixedOverload
> ```

nit: `[]PrefixedOverload` - I don't see any need to make this a slice of pointers
___
*[`pkg/sql/sem/tree/function_definition.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PpSPW6_eeM_WlSHvK:-N8PpSPW6_eeM_WlSHvL:b-dj9bu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L55)):*
> ```Go
> type PrefixedOverload struct {
> 	Schema string
> 	// TODO(Chengxiong): make this into a *Overload
> ```

nit: remove this TODO
___
*[`pkg/sql/sem/tree/function_definition.go` line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PrMOX82RHNS-bBlPn:-N8PrMOX82RHNS-bBlPo:biegrzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L259)):*
> ```Go
> // MergeWith is used specifically to merge two UDF definitions with
> // same name but from different schemas. Currently, the FunctionProperties field
> // is not set for UDFs.
> ```

Does it have to be from different schemas? Should it error if the schemas are the same and ExplicitSchema is true, or should it merge them successfully and set ExplicitSchema to true?
___
*[`pkg/sql/sem/tree/function_definition.go` line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Ps0Cl7ziGfjkEGGdB:-N8Ps0CmEtNZMh2n4eiP:b-7uw733) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L282)):*
> ```Go
> // GetClass returns function class by checking each overload's Class and returns
> // the homogeneous Class value if all overloads are the same Class. Ambiguous
> // error is returned if there is any overload with different Class.
> ```

PG have some logic to resolve overloads in this case instead of erroring:

```
marcus=# select count(10);
 count
-------
     1
(1 row)

marcus=# create function count(i int) returns int language sql as 'select i';
CREATE FUNCTION
marcus=# select count(10);
 count
-------
    10
(1 row)
```

Can you leave some TODOs here?
___
*[`pkg/sql/sem/tree/function_definition.go` line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PsSdfABpNCcJifUi4:-N8PsSdfABpNCcJifUi5:b7um6qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L341)):*
> ```Go
> }
> 
> // PrefixBuiltinFunctionDefinition prefix all overloads in a function definition
> ```

nit: prefix => prefixes (or use "qualifies" if you decide to follow my advice above re: using "qua [...]

2022-08-02 03:17 UTC, chengxiong-ruan reviewed
Thanks for the reviews! @ajwerner and @mgartner 
@ajwerner I remove the not-good udf cache from schema and add a in-memory cache of resolved functions for builtin functions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-:-N8QyCNX8AGYkH_S-NNZ:bpu73b1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, and @miretskiy)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q36Fq4NFDNFAKDFq5):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: this commit modifies
</blockquote></details>

fixed.
___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q3IyS7rFoS00gnGSG):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you rework and expand the last sentence to explain where exactly the cache exists? 
</blockquote></details>

fixed.
___
*[`pkg/sql/schema_resolver.go` line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PpvUYDV5TijGAZWWG:-N8Qwy_LDf1LgSM4ZddE:b-lkuq4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/schema_resolver.go#L406)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: expand this comment
</blockquote></details>

added more words
___
*[`pkg/sql/catalog/schema.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PltDXAuhcAlBvJOzE:-N8QxOR58hNU6dOFomsB:b-4txklp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/catalog/schema.go#L38)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Would "qualified" be a better word than "prefixed" here and in other places where you've used prefix in this PR?
</blockquote></details>

good point, I don't have strong preference, I'm leaving as it is.
___
*[`pkg/sql/catalog/schemadesc/schema_desc.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4lCfEEvHk4eEHEnC:-N8QxW4673PQC9nerIo7:bea6mrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/catalog/schemadesc/schema_desc.go#L59)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think this is kosher. You're going to have multiple different sessions accessing this cache at one. Also, you need to make sure the leasing remains coherent. This is why the hydrated cache goes to such lengths to achieve its goals. 

You could do this on the mutable, but I have to imagine it doesn't matter there. 
</blockquote></details>

this cache is deleted and an in-memory cache is added for builtin functions as suggested. Added a todo for myself to optimize UDF performance here.
___
*[`pkg/sql/opt/cat/catalog.go` line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PmLBX7jsTkcuwV9F4:-N8Qy_PaCQG5lEuYtKAn:b-32hugm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/opt/cat/catalog.go#L145)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add `.` the the end of the sentence.
</blockquote></details>

fixed. thanks
___
*[`pkg/sql/opt/testutils/testcat/function.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pmmt0DyHB4MVvOQXe:-N8QzCei8IIT3_KBbH32:b-cb6ztd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/opt/testutils/testcat/function.go#L54)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: return an assertion error stating the resolving a function by OID is not supported by the test catalog.
</blockquote></details>

ah, good call, fixed.
___
*[`pkg/sql/sem/transform/aggregates.go` line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pvs9L6xbMwgL5zdZ7:-N8R-oc_DkdPLOD69hbl:b9eb0cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc192675b7608c20f0ab1dfbbd35c10caef4ae/pkg/sql/sem/transform/aggregates.go#L41)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think we need a resolver here until we support user-defined aggregate functions. I'm inclined to leave this TODO here and not make any changes to this file until they can be tested. What do you think?
</blockquote></details>

Yeah, I agree. removed.
___
*[`pkg/sql/sem/transform/expr_transform.go` line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pw8_k5fq5t62QmAtH:-N8R0J57091T114_JmGQ:bg2ivet) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc192675b7608c20f0ab1dfbbd35c10caef4ae/pkg/sql/sem/transform/expr_transform.go#L66)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is legacy transformation logic. I'd like to rip it out at some point. Can we just leave as-is for now?
</blockquote></details>

ah, nice, removed changes here. thanks for pointing it out.
___
*[`pkg/sql/sem/tree/function_definition.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pnyp5-84-vN4hoeon:-N8R0hsU0ZLMRRlCYPsA:b-qssebl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L39)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: wit => with
</blockquote></details>

fixed.
___
*[`pkg/sql/sem/tree/function_definition.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q3j084WKSditpCGlL:-N8R0n0-7xtL0P4DOUHp:b-rrty4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Should `Name` here be of the `Name` type?
</blockquote></details>

good point, though I'm leaving it as string to avoid too many castings.
___
*[`pkg/sql/sem/tree/function_definition.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pq_En0y9TGhLlDu7g:-N8R1Yyn-coOovZCkPjh:bbof29m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L48)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `[]PrefixedOverload` - I don't see any need to make this a slice of pointers
</blockquote></details>

I think it's actually better to use pointers here since we need to merge functions through different schemas, using pointers would avoid allocating.
___
*[`pkg/sql/sem/tree/function_definition.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q3furD07yuXb2wKBg:-N8R3TrF5Xl9l46oIp4-:bqzg7ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L54)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should `Schema` here be of the `Name` type?
</blockquote></details>

good point as well, similarly, I'm leaving it as string to avoid too many castings.
___
*[`pkg/sql/sem/tree/function_definition.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PpSPW6_eeM_WlSHvK:-N8R6Chk3s3SNdbd5OV-:burxa7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L55)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: remove this TODO
</blockquote></details>

good catch...
___
*[`pkg/sql/sem/tree/function_definition.go` line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/ [...]

2022-08-02 17:00 UTC, ajwerner reviewed
This is getting there. A lot of my comments are nits. 

> Reviewed 12 of 29 files at r1, 12 of 49 files at r6, 12 of 12 files at r7, 1 of 8 files at r9, 1 of 40 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-:-N8UUwrB8pj6gipJWg5O:b-dltnxy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, @mgartner, and @miretskiy)

___
*[`-- commits` line 20 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UToHM3oa5Vb5oVltw):*
nit: implements
___
*[`-- commits` line 30 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UUcXV-T_ewy7OV8YL):*
nit: updates
___
*[`pkg/sql/schema_resolver.go` line 406 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UU8sn8sjf4bMcyLY0:-N8UU8sn8sjf4bMcyLY1:b-62e1zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/schema_resolver.go#L406)):*
> ```Go
> 
> 	if builtinDef == nil && udfDef == nil {
> 		// If nothing found, there is a chance that user type in quoted function
> ```

nit: `typed in a quoted` 
___
*[`pkg/sql/schema_resolver.go` line 442 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UQKRp-6JIxv8WCZIg:-N8UQKRp-6JIxv8WCZIh:b-5gz7kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/schema_resolver.go#L442)):*
> ```Go
> 		Name:            fn.Object(),
> 		Overloads:       append(builtinDef.Overloads, udfDef.Overloads...),
> 		OriginOverloads: append(builtinDef.OriginOverloads, udfDef.OriginOverloads...),
> ```

This is sadly dangerous in the general case. Maybe you made it such that the backing slice is perfectly sized, but I'd rather not have this code rely on that. Maybe make a helper?

```go
func combineOverloads(a, b []tree.Overload) []tree.Overload {
    return append(append(make([]tree.Overload, 0, len(a) + len(b)), a...), b...)
}
```



_Code quote:_
```Go
		Overloads:       append(builtinDef.Overloads, udfDef.Overloads...),
		OriginOverloads: append(builtinDef.OriginOverloads, udfDef.OriginOverloads...),
```
___
*[`pkg/sql/schema_resolver.go` line 349 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UVAf7CwsPlq73Ta2-:-N8UVAf7CwsPlq73Ta20:bxmztwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/993846422b9c69109a6c15766242a50eb02f54e6/pkg/sql/schema_resolver.go#L349)):*
> ```Go
> }
> 
> func (sr *schemaResolver) ResolveFunction(
> ```

For a later PR: to the extent possible, this logic belongs in the sql/catalog/resolver package and not the sql package. We'll need it for the declarative schema changer and we may want it in other places.
___
*[`pkg/sql/catalog/schema.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PltDXAuhcAlBvJOzE:-N8UQw7x02TFIFjUsdgQ:b-bbyg9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/catalog/schema.go#L38)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

good point, I don't have strong preference, I'm leaving as it is.
</blockquote></details>

I also don't like the term `Prefixed` given it is neither a well-defined concept nor is the name of the returned type. Can we just call this `GetResolvedFunctionDefinition`? Can you also put commentary explaining why this exists and what it does in terms of collecting overloads?
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 483 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8URwVKEkNkMj9NqwDk:-N8URwVKEkNkMj9NqwDl:bb1p2x9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/catalog/funcdesc/func_desc.go#L483)):*
> ```Go
> 		argTypes = append(
> 			argTypes,
> 			struct {
> ```

Can you just add a `tree.ArgType` struct? This dance seems pointless
___
*[`pkg/sql/catalog/schemadesc/schema_desc.go` line 463 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8URjwX5JQpOZeLff6I:-N8URjwX5JQpOZeLff6J:b-n44e46) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/catalog/schemadesc/schema_desc.go#L463)):*
> ```Go
> 				argTypes,
> 				struct {
> 					Name string
> ```

why is this not `tree.ArgType



_Code quote:_
```Go
					Name string
					Typ  *types.T
				}{Typ: argType},
```
___
*[`pkg/sql/sem/tree/function_definition.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q3j084WKSditpCGlL:-N8USf3tCH7N5pIobi_w:b3qbckj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L41)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

good point, though I'm leaving it as string to avoid too many castings.
</blockquote></details>

:thinking: I'm not convinced, but you have implementers choice. Know that these conversions cost nothing in terms of runtime. Give this commentary explaining that this is the name of the function and not the name of the schema and that it is not prefixed. 
___
*[`pkg/sql/sem/tree/function_definition.go` line 49 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UT7B1BC3WHdSp7Ygd:-N8UT7B1BC3WHdSp7Yge:b36vvpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/sem/tree/function_definition.go#L49)):*
> ```Go
> 	// TODO(chengxiong): remove this when we can make sure one overload is
> 	// resolved wherever function properties are checked.
> 	OriginOverloads []*Overload
> ```

Does this need to be exported? Can it just be private? 
___
*[`pkg/sql/sem/tree/function_definition.go` line 60 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UStgEEO-5BRRguk2J:-N8UStgEEO-5BRRguk2K:b-lnqt1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/sem/tree/function_definition.go#L60)):*
> ```Go
> 
> // MakePrefixedOverload creates a new PrefixedOverload.
> func MakePrefixedOverload(schema string, overload *Overload) *PrefixedOverload {
> ```

This should be called `NewPrefixedOverload` because it allocates a pointer
___
*[`pkg/sql/sem/tree/overload.go` line 113 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UTFb9DbseJiftzbsD:-N8UTFb9DbseJiftzbsE:b-eayfes) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/sem/tree/overload.go#L113)):*
> ```Go
> 	WindowFunc    WindowOverload
> 
> 	// Only one of the following 5 attributes and Body can be set.
> ```

This seems like a recipe for rotting. Just say "below"


<!-- Sent from Reviewable.io -->

2022-08-02 21:51 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, and @miretskiy)

___
*[`-- commits` line 20 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UToHM3oa5Vb5oVltw):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: implements
</blockquote></details>

fixed
___
*[`-- commits` line 30 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UUcXV-T_ewy7OV8YL):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: updates
</blockquote></details>

fixed
___
*[`pkg/sql/schema_resolver.go` line 406 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UU8sn8sjf4bMcyLY0:-N8V5tl-Ecaw7eGLYmX4:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/schema_resolver.go#L406)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: `typed in a quoted` 
</blockquote></details>

fixed
___
*[`pkg/sql/schema_resolver.go` line 442 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UQKRp-6JIxv8WCZIg:-N8VLPJE4eYyDb5o2stI:b-w5vi3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/schema_resolver.go#L442)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is sadly dangerous in the general case. Maybe you made it such that the backing slice is perfectly sized, but I'd rather not have this code rely on that. Maybe make a helper?

```go
func combineOverloads(a, b []tree.Overload) []tree.Overload {
    return append(append(make([]tree.Overload, 0, len(a) + len(b)), a...), b...)
}
```
</blockquote></details>

ah, good catch, much better to preallocate. also this can be done by calling `MergeWith` and use the helpers there.
___
*[`pkg/sql/schema_resolver.go` line 349 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UVAf7CwsPlq73Ta2-:-N8V5K4dD3vCgojO8wYX:b-ai2k0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/993846422b9c69109a6c15766242a50eb02f54e6/pkg/sql/schema_resolver.go#L349)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

For a later PR: to the extent possible, this logic belongs in the sql/catalog/resolver package and not the sql package. We'll need it for the declarative schema changer and we may want it in other places.
</blockquote></details>

yes, agree, I have a TODO at the top of the `schemaResolver` struct definition.
___
*[`pkg/sql/catalog/schema.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PltDXAuhcAlBvJOzE:-N8VLl2i5_HbqarV3KV7:bkeru1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/catalog/schema.go#L38)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I also don't like the term `Prefixed` given it is neither a well-defined concept nor is the name of the returned type. Can we just call this `GetResolvedFunctionDefinition`? Can you also put commentary explaining why this exists and what it does in terms of collecting overloads?
</blockquote></details>

heh, I guess I got the concept from ObjectPrefix... but agree that it's different here because only Schema matters here.
Changed it to `GetResolvedFunctionDefinition` and added more words.
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 483 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8URwVKEkNkMj9NqwDk:-N8VOLmM8LGVeje3VJM2:b-c24yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/catalog/funcdesc/func_desc.go#L483)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you just add a `tree.ArgType` struct? This dance seems pointless
</blockquote></details>

agree, created added a `tree.ArgType` for it.
___
*[`pkg/sql/catalog/schemadesc/schema_desc.go` line 463 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8URjwX5JQpOZeLff6I:-N8VOuL59DwCxEEElNbe:bjl91nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/catalog/schemadesc/schema_desc.go#L463)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why is this not `tree.ArgType
</blockquote></details>

same as the other comment, created a new struct `tree.ArgTyp` for it. lucky that I didn't have to fix the 700 use cases of `tree.ArgTypes`...
___
*[`pkg/sql/sem/tree/function_definition.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q3j084WKSditpCGlL:-N8VPA4s0dbHs4683Q0W:b-szho0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

:thinking: I'm not convinced, but you have implementers choice. Know that these conversions cost nothing in terms of runtime. Give this commentary explaining that this is the name of the function and not the name of the schema and that it is not prefixed. 
</blockquote></details>

added comment for it. Agree that the casting cost zero. The original `FunctionDefinition` thing use a string so there're quite some use cases to fix. Since I have a TODO to get rid of `FunctionDefinition` entirely, I'll do this together with it. Updated the TODO
___
*[`pkg/sql/sem/tree/function_definition.go` line 49 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UT7B1BC3WHdSp7Ygd:-N8VQ1aM7e9yh02zD3zY:b-7t2bsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/sem/tree/function_definition.go#L49)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Does this need to be exported? Can it just be private? 
</blockquote></details>

yes, need to access it from schema descriptor when doing the conversion there.
___
*[`pkg/sql/sem/tree/function_definition.go` line 60 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UStgEEO-5BRRguk2J:-N8VQCJR45Ep62VNU5OH:b-iu0d5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/sem/tree/function_definition.go#L60)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This should be called `NewPrefixedOverload` because it allocates a pointer
</blockquote></details>

oops.. you taught me about this before... fixed
___
*[`pkg/sql/sem/tree/overload.go` line 113 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8UTFb9DbseJiftzbsD:-N8VTIgh4Bm3bEjAPfT5:b-t64rm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/sem/tree/overload.go#L113)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This seems like a recipe for rotting. Just say "below"
</blockquote></details>

I listed out the attribute names explicitly..hope that's better.


<!-- Sent from Reviewable.io -->

2022-08-02 21:51 UTC, chengxiong-ruan reviewed
Thanks, I made the changes suggested.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-:-N8VXfPB5ILz9bfXwfXd:b-juq8k7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, and @miretskiy)



<!-- Sent from Reviewable.io -->

2022-08-02 22:03 UTC, mgartner reviewed
> Reviewed 5 of 49 files at r6, 11 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, @mgartner, and @miretskiy)

___
*[`pkg/sql/catalog/schema.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PltDXAuhcAlBvJOzE:-N8VZeI4-_S6iFKObNLs:bgj272q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/catalog/schema.go#L38)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

heh, I guess I got the concept from ObjectPrefix... but agree that it's different here because only Schema matters here.
Changed it to `GetResolvedFunctionDefinition` and added more words.
</blockquote></details>

I'll push back on the "prefix" wording used in other places in this PR. Isn't "qualified" or "fully qualified" the commonly used word for this in our code base? Or is this someone different than that? I understand that these names will only have two parts, schema and function name, but it's still "qualified", isn't it?
___
*[`pkg/sql/catalog/schemadesc/schema_desc.go` line 463 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8URjwX5JQpOZeLff6I:-N8VR2WD-nHmc-Jnqxrz:b-sabz92) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/catalog/schemadesc/schema_desc.go#L463)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why is this not `tree.ArgType
</blockquote></details>

I ran into this too. tree.ArgTypes is define as a slice of anonymous structs: https://github.com/cockroachdb/cockroach/blob/6da18dc4404e6be9c018f82414e54526d83e8a7e/pkg/sql/sem/tree/overload.go#L292-L295

We can add a `tree.ArgType` type instead of the anonymous struct.
___
*[`pkg/sql/sem/tree/function_definition.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pq_En0y9TGhLlDu7g:-N8VY2LC499oGMT4fzfU:b-kcjo2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L48)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I think it's actually better to use pointers here since we need to merge functions through different schemas, using pointers would avoid allocating.
</blockquote></details>

I don't see how this reduces allocations. PrefixedOverload is just a struct with a string and a pointer to an overload, both of which can be copied cheaply.
___
*[`pkg/sql/sem/tree/function_definition.go` line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Ps0Cl7ziGfjkEGGdB:-N8VWWXRE74pdzzObVOB:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L282)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

yes, added a TODO. let me know if that sg to you.
</blockquote></details>

SGTM
___
*[`pkg/sql/sem/tree/function_definition.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4Id11UkQ4XBpHSi8:-N8VYouw0w7xxxOTRbXS:bccw16m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L284)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

yeah, good point, Added a parallel `[]*Overload` to address.
</blockquote></details>

Why do we need the two slices? Can the `getFuncReturnLabels` operate on `[]PrefixedOverloads` instead of `[]*Overload`?
___
*[`pkg/sql/sem/tree/function_name.go` line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PuJ3N7-lvJvTP-fJP:-N8VZKvKESxyisVIWjYv:b3kdndn) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c23f6cdc0d9de62ceaf79492f7d717e0156992/pkg/sql/sem/tree/function_name.go#L72)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

currently, builtin function names are hard coded as one string used as a map key, which can be something like "crdb_internal.xxxx", it's one string but qualified. "information_schema.xxx" is another example.
</blockquote></details>

Why are they a string and not a `tree.ObjectName` (or something like that)?


<!-- Sent from Reviewable.io -->

2022-08-02 22:14 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I'm still not enamored with some of the naming, but I'm cool to defer it to later. We'll leave the rest for later. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-:-N8Vb0CmAQpI-QFJVbdK:b-igt7fo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, @mgartner, and @miretskiy)

___
*[`pkg/sql/catalog/schemadesc/schema_desc.go` line 463 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8URjwX5JQpOZeLff6I:-N8V_yGqAcwU38ew4N1Y:blgsoom) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/catalog/schemadesc/schema_desc.go#L463)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I ran into this too. tree.ArgTypes is define as a slice of anonymous structs: https://github.com/cockroachdb/cockroach/blob/6da18dc4404e6be9c018f82414e54526d83e8a7e/pkg/sql/sem/tree/overload.go#L292-L295

We can add a `tree.ArgType` type instead of the anonymous struct.
</blockquote></details>

https://github.com/golang/go/issues/16085 fortunately you can still cast between them (at least, I think you can). 


<!-- Sent from Reviewable.io -->

2022-08-02 22:26 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, @mgartner, and @miretskiy)

___
*[`pkg/sql/catalog/schema.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PltDXAuhcAlBvJOzE:-N8VcIys3mkYejqaXXc9:b-wu9bm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/catalog/schema.go#L38)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'll push back on the "prefix" wording used in other places in this PR. Isn't "qualified" or "fully qualified" the commonly used word for this in our code base? Or is this someone different than that? I understand that these names will only have two parts, schema and function name, but it's still "qualified", isn't it?
</blockquote></details>

Prefix is a thing when talking exclusively about the database and schema (https://github.com/cockroachdb/cockroach/blob/2623bae761d8b310cc7b16d40199c0dbf62afa4e/pkg/sql/catalog/catalog.go#L74-L85). "Prefixed" is not really a term. Fully-qualified means that it has both the database and schema. Schema-qualified is what I'd use to refer to the things in this PR which are called "prefixed".
___
*[`pkg/sql/sem/tree/function_definition.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4Id11UkQ4XBpHSi8:-N8VcjnJ-5G2HrmmNYJO:b-lnso3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L284)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why do we need the two slices? Can the `getFuncReturnLabels` operate on `[]PrefixedOverloads` instead of `[]*Overload`?
</blockquote></details>

I feel like my preference for all of this is to not have `PrefixedOverload` even be a thing and to have the `ResolvedFunctionDefinition` opaquely store a slice of `*Overload` and a slice of schema names and then have some mechanism to iterate them together if you need it or something like that. I'm still unclear on when we need this `PrefixedOverload`. It looks like the schema comes up when we're doing the resolution, but that would not be harmed by what I propose -- indeed you could just have it such that we iterate by schema as a method on `ResolvedFunctionDefinition`. 


<!-- Sent from Reviewable.io -->

2022-08-02 22:37 UTC, mgartner reviewed
> Reviewed 3 of 49 files at r6, 1 of 12 files at r7, 42 of 48 files at r11, 4 of 4 files at r12, 6 of 7 files at r13, 38 of 38 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, @mgartner, and @miretskiy)

___
*[`pkg/sql/sem/tree/function_definition.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4Id11UkQ4XBpHSi8:-N8VgMtpBIvHoxsD8cWc:bll51jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L284)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like my preference for all of this is to not have `PrefixedOverload` even be a thing and to have the `ResolvedFunctionDefinition` opaquely store a slice of `*Overload` and a slice of schema names and then have some mechanism to iterate them together if you need it or something like that. I'm still unclear on when we need this `PrefixedOverload`. It looks like the schema comes up when we're doing the resolution, but that would not be harmed by what I propose -- indeed you could just have it such that we iterate by schema as a method on `ResolvedFunctionDefinition`. 
</blockquote></details>

I like that idea. Getting a slice of overloads of the first matching member of a search path could be a method of `ResolvedFunctionDefinition`, so the schemas can be opaque. Seems like removing PrefixedOverload would simplify things a lot.
___
*[`pkg/sql/sem/tree/function_name.go` line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PuJ3N7-lvJvTP-fJP:-N8VbgsaD8Y5TWubdctU:b-kzpi5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c23f6cdc0d9de62ceaf79492f7d717e0156992/pkg/sql/sem/tree/function_name.go#L72)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why are they a string and not a `tree.ObjectName` (or something like that)?
</blockquote></details>

Nevermind, I misunderstood. I saw your other comment about this too.
___
*[`pkg/sql/sem/tree/type_check.go` line 1147 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8VdnKoB7MUgn55qTMu:-N8VdnKoB7MUgn55qTMv:b99bd9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4a91d5e4e2b43cd98ea84fc5e47a60fd3468d29/pkg/sql/sem/tree/type_check.go#L1147)):*
> ```Go
> 	}
> 
> 	// Sort overloads by the order of their schema in search path.
> ```

nit: update the comment now that we are no longer sorting.
___
*[`pkg/sql/sem/tree/type_check.go` line 1150 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8VdXPlEAH2aiMimsHU:-N8VdXPlEAH2aiMimsHV:bobjgly) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4a91d5e4e2b43cd98ea84fc5e47a60fd3468d29/pkg/sql/sem/tree/type_check.go#L1150)):*
> ```Go
> 	typeCheckedOverloads := make([]*PrefixedOverload, len(fns))
> 	for i := range fns {
> 		typeCheckedOverloads[i] = fns[i].(*PrefixedOverload)
> ```

Is it guaranteed that all elements of `fns` are `*PrefixedOverload`? If so, can we have `typeCheckOverloadedExprs` return `[]PrefixedOverload` instead of `[]overloadImpl` and avoid allocating this new slice?


<!-- Sent from Reviewable.io -->

2022-08-03 00:18 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, and @miretskiy)

___
*[`pkg/sql/catalog/schema.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8PltDXAuhcAlBvJOzE:-N8VkqEd-lthrqc-HRGz:b-fulh5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/catalog/schema.go#L38)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Prefix is a thing when talking exclusively about the database and schema (https://github.com/cockroachdb/cockroach/blob/2623bae761d8b310cc7b16d40199c0dbf62afa4e/pkg/sql/catalog/catalog.go#L74-L85). "Prefixed" is not really a term. Fully-qualified means that it has both the database and schema. Schema-qualified is what I'd use to refer to the things in this PR which are called "prefixed".
</blockquote></details>

Good point. I renamed structures, methods and comments to use "qualify".
___
*[`pkg/sql/catalog/schemadesc/schema_desc.go` line 463 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8URjwX5JQpOZeLff6I:-N8Vi5r-A_eUB6Icwdfz:bpcaahi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4fd74de05733598467f5081c4f0200e980a9943/pkg/sql/catalog/schemadesc/schema_desc.go#L463)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

https://github.com/golang/go/issues/16085 fortunately you can still cast between them (at least, I think you can). 
</blockquote></details>

hmm. looks like the 700 use cases in builtin functions constructed the struct with unkeyed values, and got 700 of such errors from CI if I make `tree.ArgTypes` as `[]tree.ArgType`:
`tree.ArgType composite literal uses unkeyed fields (composites)`. Is there a way to fix this kind of thing quickly? For now what I did is just define the new `tree.ArgType` but not touching `tree.ArgTypes` and looks like it can be casted automatically from `tree.ArgType` to the unnamed struct as Andrew pointed out.
___
*[`pkg/sql/sem/tree/function_definition.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Pq_En0y9TGhLlDu7g:-N8VyIzb7Rww5U02KQFE:bv1gxqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L48)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't see how this reduces allocations. PrefixedOverload is just a struct with a string and a pointer to an overload, both of which can be copied cheaply.
</blockquote></details>

yeah, sure, changed it to use the struct instead of pointer.
___
*[`pkg/sql/sem/tree/function_definition.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4Id11UkQ4XBpHSi8:-N8VyRohA4c5r6u0uz9D:beepv89) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L284)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I like that idea. Getting a slice of overloads of the first matching member of a search path could be a method of `ResolvedFunctionDefinition`, so the schemas can be opaque. Seems like removing PrefixedOverload would simplify things a lot.
</blockquote></details>

One down side is that, after the filtering of `typeCheckOverloadedExprs`, I don't see a good way to track schemas for each overload :( . 
I just realized that the get-properties methods of `FunctionDefinition` are not need anymore after we move all function resolution use cases to the new interface...(apologies didn't realize that), so this parallel is not need at all since I can just implement the get-properties methods for (now) `QualifiedOverload` and not need to allocate anything... How does that sound?
___
*[`pkg/sql/sem/tree/type_check.go` line 1147 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8VdnKoB7MUgn55qTMu:-N8VzHl7BupBnX2a3JGl:b-kl8g3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4a91d5e4e2b43cd98ea84fc5e47a60fd3468d29/pkg/sql/sem/tree/type_check.go#L1147)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: update the comment now that we are no longer sorting.
</blockquote></details>

good catch.
___
*[`pkg/sql/sem/tree/type_check.go` line 1150 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8VdXPlEAH2aiMimsHU:-N8VwlGWE8DIr0Klt8JY:b-qyv37p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4a91d5e4e2b43cd98ea84fc5e47a60fd3468d29/pkg/sql/sem/tree/type_check.go#L1150)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is it guaranteed that all elements of `fns` are `*PrefixedOverload`? If so, can we have `typeCheckOverloadedExprs` return `[]PrefixedOverload` instead of `[]overloadImpl` and avoid allocating this new slice?
</blockquote></details>

good question.
1. yes `fns` are always (now) `QualifiedOverload`s.
2. but no....`typeCheckOverloadedExprs` is also used by other type of expressions for example `BinaryExpr` :(


<!-- Sent from Reviewable.io -->

2022-08-03 02:26 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @mgartner, and @miretskiy)

___
*[`pkg/sql/sem/tree/function_definition.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4Id11UkQ4XBpHSi8:-N8WW4ttC05qE391dxt2:bkmajts) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L284)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

One down side is that, after the filtering of `typeCheckOverloadedExprs`, I don't see a good way to track schemas for each overload :( . 
I just realized that the get-properties methods of `FunctionDefinition` are not need anymore after we move all function resolution use cases to the new interface...(apologies didn't realize that), so this parallel is not need at all since I can just implement the get-properties methods for (now) `QualifiedOverload` and not need to allocate anything... How does that sound?
</blockquote></details>

I took a stab at it. It wasn't too bad. I believe I like it a lot better. There is a moment in type checking when we need to fish the schemas back out, but we can do that (see [here](https://github.com/ajwerner/cockroach/blob/123a74e187283045ab14a75ac3426504e0306aa9/pkg/sql/sem/tree/function_definition.go#L334-L366)). 

https://github.com/ajwerner/cockroach/commit/123a74e187283045ab14a75ac3426504e0306aa9


<!-- Sent from Reviewable.io -->

2022-08-03 13:59 UTC, chengxiong-ruan commented
*[`pkg/sql/sem/tree/function_definition.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4Id11UkQ4XBpHSi8:-N8YzRr0BlUyD6jNGg0v:b-dl3gin) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L284)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I took a stab at it. It wasn't too bad. I believe I like it a lot better. There is a moment in type checking when we need to fish the schemas back out, but we can do that (see [here](https://github.com/ajwerner/cockroach/blob/123a74e187283045ab14a75ac3426504e0306aa9/pkg/sql/sem/tree/function_definition.go#L334-L366)). 

https://github.com/ajwerner/cockroach/commit/123a74e187283045ab14a75ac3426504e0306aa9



</blockquote></details>

Chatted offline that I appreciate the shared solution here but I'm not enthusiastic about the extra complexity (though I love the iterator pattern) and like to avoid parallel slices if we could. In the mean while I'm open to a separate pr from Andrew to get his solution in.


<!-- Sent from Reviewable.io -->

2022-08-03 15:08 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks for working through all our comments!

> Reviewed 45 of 45 files at r15, 4 of 4 files at r16, 7 of 7 files at r17, 38 of 38 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-:-N8ZEfBjAOsDzOQMbwUO:b1gwt2p)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @chengxiong-ruan, @mgartner, and @miretskiy)

___
*[`pkg/sql/sem/tree/function_definition.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4Id11UkQ4XBpHSi8:-N8ZAWPe39cMJm5V3VpZ:b-5r2c8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L284)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Chatted offline that I appreciate the shared solution here but I'm not enthusiastic about the extra complexity (though I love the iterator pattern) and like to avoid parallel slices if we could. In the mean while I'm open to a separate pr from Andrew to get his solution in.
</blockquote></details>

SGTM. I think the parallel slices pattern is useful. The complexity can be hidden from callers by not exporting the slices and providing an API that prevents misusage.
___
*[`pkg/sql/sem/tree/type_check.go` line 1150 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8VdXPlEAH2aiMimsHU:-N8ZDtdP-OXOBVN7u-UQ:b-oed4b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4a91d5e4e2b43cd98ea84fc5e47a60fd3468d29/pkg/sql/sem/tree/type_check.go#L1150)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

good question.
1. yes `fns` are always (now) `QualifiedOverload`s.
2. but no....`typeCheckOverloadedExprs` is also used by other type of expressions for example `BinaryExpr` :(
</blockquote></details>

Thanks for the explanation. You could have `getMostSignificatnOverloads` take a `[]overloadImpl`. Then the allocation of `typeCheckedOverloads` can be removed, and the only allocation of `[]QualifiedOverload` would occur in `getMostSignificatnOverloads`.


<!-- Sent from Reviewable.io -->

2022-08-03 15:42 UTC, chengxiong-ruan commented
*[`pkg/sql/sem/tree/type_check.go` line 1150 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8VdXPlEAH2aiMimsHU:-N8ZMMdv8dAY_nF1mlor:bnh74yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4a91d5e4e2b43cd98ea84fc5e47a60fd3468d29/pkg/sql/sem/tree/type_check.go#L1150)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Thanks for the explanation. You could have `getMostSignificatnOverloads` take a `[]overloadImpl`. Then the allocation of `typeCheckedOverloads` can be removed, and the only allocation of `[]QualifiedOverload` would occur in `getMostSignificatnOverloads`.
</blockquote></details>

Ah, smart, changed as suggested. and just realized maybe we can just return one single overload from `getMostSignificatnOverloads` after I pushed... I'll do that and push again.


<!-- Sent from Reviewable.io -->

2022-08-03 17:30 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 43 of 43 files at r19, 4 of 4 files at r20, 7 of 7 files at r21, 38 of 38 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-:-N8ZkXZjA_p4ydKaPNK9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @chengxiong-ruan, @mgartner, and @miretskiy)

___
*[`pkg/sql/sem/tree/type_check.go` line 2978 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Zk3R37vXIe2y9_pCl:-N8Zk3R37vXIe2y9_pCm:bt4etvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/679f66b8cd049b3172bc1839fb434e32fad90425/pkg/sql/sem/tree/type_check.go#L2978)):*
> ```Go
> 	}
> 
> 	ret := make([]overloadImpl, 0, len(overloads))
> ```

nit: I think you can remove this allocation altogether now - you just need a variable for a single overload. If it's already been set, then you can return the ambiguity error.


<!-- Sent from Reviewable.io -->

2022-08-03 21:00 UTC, chengxiong-ruan commented
*[`pkg/sql/sem/tree/type_check.go` line 2978 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Zk3R37vXIe2y9_pCl:-N8_V-hdC4UVyyPwl5Xk:bfxry8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/679f66b8cd049b3172bc1839fb434e32fad90425/pkg/sql/sem/tree/type_check.go#L2978)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I think you can remove this allocation altogether now - you just need a variable for a single overload. If it's already been set, then you can return the ambiguity error.
</blockquote></details>

Good point, thanks for all the suggestion. I also added more edge cases checking and tests. There was one obvious edge case I didn't catch is that if a function is resolved with a qualified name (with explicit schema) but the schema is not in search path.


<!-- Sent from Reviewable.io -->

2022-08-03 21:00 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @mgartner, and @miretskiy)

___
*[`pkg/sql/sem/tree/function_definition.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4Id11UkQ4XBpHSi8:-N8_VgqO5ScfcIzHSCAm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L284)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

SGTM. I think the parallel slices pattern is useful. The complexity can be hidden from callers by not exporting the slices and providing an API that prevents misusage.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-03 21:01 UTC, chengxiong-ruan commented
*[`pkg/sql/sem/tree/function_definition.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85391#-N8Q4Id11UkQ4XBpHSi8:-N8_VifV4o18w5AGLhX8:b-2x31jp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5de65f8f3f4e2e10bc91ccd020288b486438ce3c/pkg/sql/sem/tree/function_definition.go#L284)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

oops... tried to resolve the discussion, not done...


<!-- Sent from Reviewable.io -->

2022-08-03 21:31 UTC, mgartner approved these changes
> Reviewed 3 of 3 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85391)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @mgartner, and @miretskiy)



<!-- Sent from Reviewable.io -->

2022-08-03 23:17 UTC, chengxiong-ruan commented
TFTR!
bors r+

2022-08-04 03:49 UTC, chengxiong-ruan commented
looks like there's one of the jobs test shards kept failing
bors r-

2022-08-04 14:24 UTC, chengxiong-ruan commented
It looks like one of the job tests (TestStartableJobMixedVersion) hang and timeout. Added some logging and I suspect that it's the `publicSchemaMigration` upgradge stuck while it's waiting the database descriptor lease to expire... looking into why :(

2022-08-04 20:56 UTC, chengxiong-ruan commented
TFTR! and the fix of leaked lease!
bors r+

2022-08-04 23:40 UTC, merged

2022-10-04 02:38 UTC, yuzefovich commented
I narrowed down a regression in micro-benchmark to this PR:
```
BENCHTIMEOUT=24h PKG=./pkg/bench BENCHES=BenchmarkSQL/MultinodeCockroach/Upsert/count=1000 ./scripts/bench ddabd1890635ce088ec60af5cbf39bda2fe60ace^ b0b54ff294eaed0645758dcf473e1e3ee34f1e9b
...
name                                         old time/op    new time/op    delta
SQL/MultinodeCockroach/Upsert/count=1000-24    26.1ms ±10%    30.3ms ± 6%  +15.81%  (p=0.000 n=10+10)

name                                         old alloc/op   new alloc/op   delta
SQL/MultinodeCockroach/Upsert/count=1000-24    10.9MB ±11%    11.2MB ±11%     ~     (p=0.258 n=9+9)

name                                         old allocs/op  new allocs/op  delta
SQL/MultinodeCockroach/Upsert/count=1000-24     79.9k ± 6%     92.1k ± 6%  +15.26%  (p=0.000 n=10+10)
```
Note that most likely ddabd1890635ce088ec60af5cbf39bda2fe60ace is to blame, but the build fails on that commit - another plug for making sure that builds succeed on each commit in the PR.

I took a quick look at that commit, and I didn't see an easy way to reduce the impact. Do we want to do something about that?

2022-10-04 03:52 UTC, chengxiong-ruan commented
> 

Thanks for raising this @yuzefovich. Yeah, looks like the upsert benchmark is calling `unique_rowid()` function, so I suspect it's the new function resolution adds more overhead for builtin function. Previously it was just a hashmap key check. I'll take a closer look tomorrow. Will probably need help on profiling things in go. Thanks again.

2022-10-04 03:54 UTC, chengxiong-ruan commented
And yes... my bad that didn't make each commit built when I broke up the pr into smaller commits. I went too far and found it hard to make each commit pass. But this is not a good excuse. This is a good lesson and I'll definitely keep this in mind.

2022-10-04 18:50 UTC, ajwerner commented
I attacked the resolution side of the allocations in https://github.com/cockroachdb/cockroach/pull/89317. There's more we can do on the type checking side. For what it's worth, that's going to be more of the bytes allocated.