ui: Add Transaction and Statement fingerprint id
cockroachdb/cockroach pull request #85464
Opened 2022-08-02 15:03 UTC by j82w

This adds the Transaction and Statement fingerprint id
to SQL Activity Statements overview page. The columns
are hidden by default.

closes #78509

<img width="1511" alt="Screen Shot 2022-08-02 at 9 47 26 AM" src="https://user-images.githubusercontent.com/8868107/182406700-20ea398b-fd26-4703-a66a-32f6a45b0e07.png">

Release note (ui change): Adds Transaction and
Statement fingerprint id to SQL Activity Statements
overview page. New columns are hidden by default.

2022-08-02 15:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/85464)
<!-- Reviewable:end -->

2022-08-02 15:16 UTC, maryliag requested changes
To clarify, the issues is to add the stmt/txn IDs to their respective overview pages, that is because the same row on the statement overview can have multiple transaction fingerprint IDs. So on this issue you should add only the Statement Fingerprint ID to the Statement overview table, and only the Transaction Fingerprint ID to the Transactions overview table.

Can you also add the ability to search on those fields?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-:-N8U6BSXEp29TAa1gb7-:bvtk8bf)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-08-04 12:12 UTC, j82w reviewed
Fixed in latest iteration

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-:-N8clKkHBWNT8KvyKrXC:b-ox115e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2022-08-04 13:34 UTC, maryliag requested changes
just a few nits 

> Reviewed 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-:-N8d37Zl7bezkCIWunEP:bmje1ww)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx` line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8d1uLqAal59zh7G716:-N8d1uLqAal59zh7G717:b-vdarc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d4a318400d6952c319310786cd1fe3d27931d5/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L61)):*
> ```XML
>   workloadPct: "% of All Runtime",
>   lastExecTimestamp: "Last Execution Time (UTC)",
>   statementFingerPrintId: "Statement Fingerprint ID",
> ```

nit: `statementFingerprintID` and `transactionFingerprintID` (and all usages like this in other locations)
___
*[`pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8d1pAf7s-Ge3kaQhj3:-N8d1pAf7s-Ge3kaQhj4:bapqzdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d4a318400d6952c319310786cd1fe3d27931d5/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L226)):*
> ```XML
>         style="tableTitle"
>         placement="bottom"
>         content={"The statement finger print id."}
> ```

nit: The statement fingerprint ID.
___
*[`pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx` line 237 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8d2hXX3r6UHcWJ1mXw:-N8d2hXX3r6UHcWJ1mXx:b-5gaqb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d4a318400d6952c319310786cd1fe3d27931d5/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L237)):*
> ```XML
>         style="tableTitle"
>         placement="bottom"
>         content={"The transaction finger print id."}
> ```

nit: The transaction fingerprint ID.


<!-- Sent from Reviewable.io -->

2022-08-04 18:52 UTC, j82w reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8d1pAf7s-Ge3kaQhj3:-N8eBu0o6cXf6zUvYM4e:b-vagzl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d4a318400d6952c319310786cd1fe3d27931d5/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L226)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: The statement fingerprint ID.
</blockquote></details>

Please take a look at the expanded text.


<!-- Sent from Reviewable.io -->

2022-08-04 20:03 UTC, maryliag reviewed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8eRsC4CQNU7pZDPVA4):*
To close the issue, this commit would also need the capability to search for the stmt/txn IDs on the search input of each page
from the comment here: https://github.com/cockroachdb/cockroach/issues/78509#issuecomment-1175551867
___
*[`pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8d1pAf7s-Ge3kaQhj3:-N8eSCoB1xbTEuBg_CaZ:b-vs1prh) ([raw file](https://github.com/cockroachdb/cockroach/blob/43d4a318400d6952c319310786cd1fe3d27931d5/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L226)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Please take a look at the expanded text.
</blockquote></details>

Looks good!


<!-- Sent from Reviewable.io -->

2022-08-05 00:47 UTC, j82w reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8eRsC4CQNU7pZDPVA4):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

To close the issue, this commit would also need the capability to search for the stmt/txn IDs on the search input of each page
from the comment here: https://github.com/cockroachdb/cockroach/issues/78509#issuecomment-1175551867
</blockquote></details>

I added search support for the column. Do you think it would be better to add another field to AggregateStatistics to avoid needing to convert it back to a long then to hex?


<!-- Sent from Reviewable.io -->

2022-08-08 14:39 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8eRsC4CQNU7pZDPVA4):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

I added search support for the column. Do you think it would be better to add another field to AggregateStatistics to avoid needing to convert it back to a long then to hex?
</blockquote></details>

I think is worth it, otherwise there is a lot of conversion going on.
___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 180 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8xpC1-3Bfa-mXBLizl:-N8xpC1-3Bfa-mXBLizm:bksb70s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5059e2ad286deb4d36f5fceb56019751cf7ea0e/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L180)):*
> ```XML
>     }
> 
>     return matchFingerPrintId.includes(search);
> ```

you can just do `return matchString.includes(search) || matchFingerPrintId.includes(search);` like you did below


<!-- Sent from Reviewable.io -->

2022-08-08 18:56 UTC, j82w reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8eRsC4CQNU7pZDPVA4):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I think is worth it, otherwise there is a lot of conversion going on.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 180 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8xpC1-3Bfa-mXBLizl:-N8yo22d0NN25ndHGXyj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d71984148f0b1588ce78acbf8be2d68eeb280624/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L180)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you can just do `return matchString.includes(search) || matchFingerPrintId.includes(search);` like you did below
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-08 19:45 UTC, maryliag requested changes
> Reviewed 6 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.selectors.ts` line 192 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-N8yz-t7DjGkTpI_aajC:-N8yz-t7DjGkTpI_aajD:b-ucsmqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fec1cc9c471f4e48386a7fba6019f2727f748349/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.selectors.ts#L192)):*
> ```XML
>       return {
>         aggregatedFingerprintID: stmt.statementFingerprintID,
>         aggregatedFingerprintHexID: stmt.statementFingerprintID,
> ```

you probably mean `aggregatedFingerprintHexID: stmt.statementFingerprintHexID,`


<!-- Sent from Reviewable.io -->

2022-08-08 21:44 UTC, maryliag approved these changes
Awesome! As long as tests are passing and you made sure the details page (both statement and transactions) are working properly <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85464#-:-N8zPTGn38r3AXvJUYaQ:b-8531u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)



<!-- Sent from Reviewable.io -->

2022-08-26 19:51 UTC, maryliag commented
bors r+

2022-08-26 23:59 UTC, merged

2022-08-29 21:40 UTC, j82w commented
blathers backport release-22.1

2022-08-30 11:07 UTC, j82w commented
blathers backport release-22.1