ui: new index recommendations table component
cockroachdb/cockroach pull request #85862
Opened 2022-08-09 22:56 UTC by maryliag

Creation of the base index recommendations table,
that can be used on both schema insights and statement
details page.

This commit only introduce the table, with the different
types, but still needs the proper cell formating for
each type.

Part of #83783

Release note: None

2022-08-09 22:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/85862)
<!-- Reviewable:end -->

2022-08-10 13:40 UTC, THardy98 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[`pkg/ui/workspaces/cluster-ui/src/indexRecommendationsTable/indexRecommendationsTable.tsx` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85862#-N96yYwN2HNEkmo5Cd0s:-N96yYwN2HNEkmo5Cd0t:bejltt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f02f3835397f6e80ee682204eb080093957bdc8/pkg/ui/workspaces/cluster-ui/src/indexRecommendationsTable/indexRecommendationsTable.tsx#L31)):*
> ```XML
> }
> 
> export class IdxInsightsSortedTable extends SortedTable<IdxRecommendation> {}
> ```

I see on the figma (https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4/22.2_SQL-obsrv_query-performance?node-id=301%3A3805) there could be schema insights unrelated to index recs like `Outdated Table Statistics`, despite that, are we we okay with keeping this table as "Index Insights" ?
___
*[`pkg/ui/workspaces/cluster-ui/src/indexRecommendationsTable/indexRecommendationsTable.tsx` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85862#-N96yrzG0vi70-dINsBj:-N96yrzG0vi70-dINsBk:b-5oj35) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f02f3835397f6e80ee682204eb080093957bdc8/pkg/ui/workspaces/cluster-ui/src/indexRecommendationsTable/indexRecommendationsTable.tsx#L73)):*
> ```XML
>       return "Create New Index";
>     case "DROP":
>       return "Drop Index";
> ```

I think should be `Drop Unused Index`, currently that's the only index recommendation we recommend for index drops.


<!-- Sent from Reviewable.io -->

2022-08-10 13:54 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/ui/workspaces/cluster-ui/src/indexRecommendationsTable/indexRecommendationsTable.tsx` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85862#-N96yYwN2HNEkmo5Cd0s:-N971C9UDWUULSRKobMQ:ba3o3s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f02f3835397f6e80ee682204eb080093957bdc8/pkg/ui/workspaces/cluster-ui/src/indexRecommendationsTable/indexRecommendationsTable.tsx#L31)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

I see on the figma (https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4/22.2_SQL-obsrv_query-performance?node-id=301%3A3805) there could be schema insights unrelated to index recs like `Outdated Table Statistics`, despite that, are we we okay with keeping this table as "Index Insights" ?
</blockquote></details>

Renamed
___
*[`pkg/ui/workspaces/cluster-ui/src/indexRecommendationsTable/indexRecommendationsTable.tsx` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85862#-N96yrzG0vi70-dINsBj:-N971DMt-JHi6at5z1Th:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f02f3835397f6e80ee682204eb080093957bdc8/pkg/ui/workspaces/cluster-ui/src/indexRecommendationsTable/indexRecommendationsTable.tsx#L73)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

I think should be `Drop Unused Index`, currently that's the only index recommendation we recommend for index drops.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-08-10 14:39 UTC, THardy98 approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2022-08-10 14:40 UTC, THardy98 approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2022-08-10 17:38 UTC, maryliag commented
bors r+

2022-08-10 20:24 UTC, merged