kvserver: allow certain read-only requests to drop latches before evaluation
cockroachdb/cockroach pull request #85993
Opened 2022-08-11 20:26 UTC by aayushshah15

This commit introduces a change to the way certain types of read-only requests
are evaluated. Traditionally, read-only requests have held their latches
throughout their execution. This commit allows certain qualifying reads to be
able to release their latches earlier.

At a high level, reads may attempt to resolve all conflicts upfront by
performing a sort of "validation" phase before they perform their MVCC scan.
This validation phase performs a scan of the lock table keyspace in order to
find any conflicting intents that may need to be resolved before the actual
evaluation of the request over the MVCC keyspace. If no conflicting intents are
found, then (since https://github.com/cockroachdb/cockroach/pull/76312), the
request is guaranteed to be fully isolated against all other concurrent
requests and can be allowed to release its latches at this point. This allows
the actual evaluation of the read (over the MVCC part of the keyspace) to
proceed without latches being held, which is the main motivation of this work.
This validation phase could be thought of as an extension to the validation
that the concurrency manager already performs when requests are sequenced
through it, by trying to detect any conflicting intents that have already been
pulled into the in-memory lock table.

Additionally, for certain types of requests that can drop their latches early,
and do not need to access the `IntentHistory` for any of their parent txn's
intents, this commit attempts to make their MVCC scan cheaper by eliminating
the need for an `intentInterleavingIterator`. This is enabled by the
observation that once the validation phase is complete, the only remaining
intents in the read's declared span must be intents belonging to the reader's
transaction. So if the reader doesn't need to read an intent that isn't the
latest intent on a key, then it doesn't need access to the key's
`IntentHistory` (which lives in the lock-table keyspace), and doesn't need to
use an `intentInterleavingIterator`.

Release note (performance improvement):
TODO

Resolves https://github.com/cockroachdb/cockroach/issues/66485

2022-08-11 20:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/85993)
<!-- Reviewable:end -->

2022-08-11 20:32 UTC, aayushshah15 commented
cc @nvanbenschoten and @arulajmani 

I'm working through the testing and the test failures, but this should still benefit from a high-level pass before that's done.

2022-08-12 18:00 UTC, nvanbenschoten reviewed
> Reviewed 6 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_evaluate.go` line 625 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I91Oa2Nm4_cIEm0eK:-N9I91Oa2Nm4_cIEm0eL:bqj1ai4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L625)):*
> ```Go
> 	// conflicting requests during their execution. Thus, they cannot release
> 	// their latches before evaluation.
> 	if ba.IsLocking() || !ba.IsReadOnly() {
> ```

nit: do we need to check `IsReadOnly`? We're only calling this from the read-only path.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 625 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I96BK1HLnqgnrf28F:-N9I96BK1HLnqgnrf28G:buvk95v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L625)):*
> ```Go
> 	// conflicting requests during their execution. Thus, they cannot release
> 	// their latches before evaluation.
> 	if ba.IsLocking() || !ba.IsReadOnly() {
> ```

nit: move `ba.IsLocking()` this down right above the WaitPolicy check.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I9Asb6pma-xtQoLLH:-N9I9Asb6pma-xtQoLLI:bl3tftt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L643)):*
> ```Go
> 		return false
> 	default:
> 		return false
> ```

nit: here and below, panic on unexpected enum values instead of failing silently.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 662 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I9GGu24kagBoJFxcj:-N9I9GGu24kagBoJFxck:b-ocqhhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L662)):*
> ```Go
> 		case *roachpb.ExportRequest:
> 		case *roachpb.GetRequest:
> 			if inner.(*roachpb.GetRequest).KeyLocking != lock.None {
> ```

We shouldn't need this now that we're checking `IsLocking()`.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I9HYj0m4-xC8d-dqF:-N9I9HYj0m4-xC8d-dqG:bn80l9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L666)):*
> ```Go
> 			}
> 		case *roachpb.ScanRequest:
> 			if inner.(*roachpb.ScanRequest).KeyLocking != lock.None {
> ```

Same comment, this shouldn't be needed now.
___
*[`pkg/kv/kvserver/replica_read.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IA6lL8KcvuVsSJDCX:-N9IA6lL8KcvuVsSJDCY:bf9nz6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L83)):*
> ```Go
> 		return nil, g, nil, roachpb.NewError(err)
> 	}
> 	// TODO(nvanbenschoten): once all replicated intents are pulled into the
> ```

We can delete this now :partying_face: 
___
*[`pkg/kv/kvserver/replica_read.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I9mSz-t6BtfycBAar:-N9I9mSz-t6BtfycBAas:b-4v1o02) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L167)):*
> ```Go
> 		pErr = r.handleReadOnlyLocalEvalResult(ctx, ba, result.Local)
> 	}
> 	if !canDropLatches {
> ```

Can this be `if g != nil`. That would mean that latches are still held.
___
*[`pkg/kv/kvserver/replica_read.go` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I9_Hp2nhUo1ym_QHG:-N9I9_Hp2nhUo1ym_QHH:b1j4fy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L231)):*
> ```Go
> ) {
> 	var ec endCmds
> 	ec, g = endCmds{repl: r, g: g, st: st}, nil
> ```

I don't think the assignment to `g` is doing the right thing anymore, now that this is in a helper function. You'll need to lift that back up into `executeReadOnlyBatch` after each call to this function.
___
*[`pkg/kv/kvserver/replica_read.go` line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IAfvQ8JhNUKtX3GZn:-N9IAfvQ8JhNUKtX3GZo:bp5uk2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L266)):*
> needIntentHistory

This is a confusing condition, especially because we're returning true when `canDropLatches` is false. What is the intent history in the context of a read-only request? Why do we need it for non-txn requests?

Consider changing the condition to either `needsIntentInterleaving` or `stillNeedsIntentInterleaving` (depending on whether you want to return true or false when `!canDropLatches`.
___
*[`pkg/kv/kvserver/replica_read.go` line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IB7T5AoObzXSR8-3I:-N9IB7T5AoObzXSR8-3J:b-hd2pfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L266)):*
> ```Go
> 	g *concurrency.Guard,
> 	st kvserverpb.LeaseStatus,
> ) (canDropLatches, needIntentHistory bool, pErr *roachpb.Error) {
> ```

nit: `s/canDropLatches/ok/`, because this is already the name of the method.
___
*[`pkg/kv/kvserver/replica_read.go` line 275 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IAk4d9FacQhDqTKRF:-N9IAk4d9FacQhDqTKRG:b-snkac9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L275)):*
> ```Go
> 		ctx, 3, "can drop latches early for batch (%v); scanning lock table first to detect conflicts", ba,
> 	)
> 	maximalLatchSpan := g.LatchSpans().BoundarySpan(spanset.SpanGlobal)
> ```

Discussed in person: this isn't quite right. We don't want to scan across the entire boundary span, just the spans of the individual requests.
___
*[`pkg/kv/kvserver/replica_read.go` line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IAqDvESwOTUdly4Y3:-N9IAqDvESwOTUdly4Y4:b-mnnmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L278)):*
> ```Go
> 	start, end := maximalLatchSpan.Key, maximalLatchSpan.EndKey
> 	maxIntents := storage.MaxIntentsPerWriteIntentError.Get(&r.store.cfg.Settings.SV)
> 	intents, needIntentHistory, err := storage.ScanConflictingIntents(
> ```

Discussed in person: for point reads, we want this to use a prefix iterator so that it can hit bloom filters.
___
*[`pkg/kv/kvserver/replica_read.go` line 431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IBrf93K5sA0tB2Npz:-N9IBrf93K5sA0tB2Nq-:brrag77) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L431)):*
> ```Go
> 		// pass in a latch guard here that indicates as much. In other words, what
> 		// we want is to ensure that requests that have acquired-and-then-dropped
> 		// latches at ts X cannot retry above ts X.
> ```

This relates to the comment about setting `g` to nil if we drop latches early.
___
*[`pkg/kv/kvserver/replica_tscache.go` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IC6Fd6WPpv9VTDsi-:-N9IC6Fd6WPpv9VTDsi0:bc1qxkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_tscache.go#L59)):*
> ```Go
> // expected to be called when a request is dropping its latches before it
> // is evaluated.
> func (r *Replica) updateTimestampCacheBeforeEval(
> ```

Why do we need this? Is [...]

2022-08-15 15:22 UTC, sumeerbhola requested changes
> Reviewed 6 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_evaluate.go` line 628 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X0JtoBq5gcF0LENsz:-N9X0JtoBq5gcF0LENt-:b-uuxuvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L628)):*
> ```Go
> 		return false
> 	}
> 	if ba.Header.ReadConsistency != roachpb.CONSISTENT {
> ```

It would be helpful to have a comment stating why !CONSISTENT is not eligible.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X0Ru1ChBF0tJBQtjl:-N9X0Ru1ChBF0tJBQtjm:b-mldsco) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L631)):*
> ```Go
> 		return false
> 	}
> 	if g == nil {
> ```

A code comment would help here, since its not clear what the `g==nil` case represents.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 656 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X1XNaDB7Wn52P5Lcm:-N9X1XNaDB7Wn52P5Lcn:b-nhn374) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L656)):*
> ```Go
> 	}
> 	// TODO(aayush): Consider whether there are other requests that can be let
> 	// through.
> ```

A high-level comment would help here. IIUC, everything below is about ensuring the request does not acquire locks.
Otherwise it is hard to see why `ExportRequest` is always ok.
___
*[`pkg/storage/engine.go` line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X3BoQ1xf0tqtv3DzY:-N9X3BoQ1xf0tqtv3DzZ:b-6tvdw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/storage/engine.go#L429)):*
> ```Go
> 	// scans the MVCC keyspace and does not interleave intents into the results.
> 	// This is only relevant for MVCCIterators.
> 	DontInterleaveIntents bool
> ```

nit:
why do we have this in `IterOptions` given that we have an explicit parameter in `NewMVCCIterator(iterKind MVCCIterKind, opts IterOptions) MVCCIterator`?
`IterOptions` shouldn't be used for `mvcc.go` plumbing since that is a higher layer than the code in engine.go. It should be used for what is needed for the interfaces defined in `engine.go`?
___
*[`pkg/storage/engine.go` line 1183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X4-ov6PwbJOfL1Iz4:-N9X4-ov6PwbJOfL1Iz5:b3i596y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/storage/engine.go#L1183)):*
> ```Go
> // be able to read the correct provisional value.
> //
> // Note that this method does not take interleaved intents into account at all.
> ```

I don't think we need this "Note that ..." comment since there are no interleaved intents.
Unfortunately, we still have some stale commentary and code in `intentInterleavingIter` that allows for it, but we shouldn't propagate that to new code.
We've also not always been clear in distinguishing physically interleaved intents from a storage perspective (which we no longer have) and logically interleaving intents (which we of course continue to have) -- I assume this comment was referring to the former.
___
*[`pkg/storage/engine.go` line 1191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X4vXh4JDBIXT10oAn:-N9X4vXh4JDBIXT10oAo:b-ilhpzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/storage/engine.go#L1191)):*
> ```Go
> 	start, end roachpb.Key,
> 	maxIntents, targetBytes int64,
> ) (intents []roachpb.Intent, needIntentHistory bool, err error) {
> ```

so if this scan comes back with no intents but says `needIntentHistory=true` we will need to scan the lock table twice (since we will need to interleave), yes? Worth benchmarking that case to see how much slower it is, especially for short scans or gets. I wonder whether we will need a heuristic to guess that `needIntentHistory` will be false.


<!-- Sent from Reviewable.io -->

2022-08-22 16:03 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_evaluate.go` line 625 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I91Oa2Nm4_cIEm0eK:-N9IOn_70iu-IhThNWhp:b1phe1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L625)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: do we need to check `IsReadOnly`? We're only calling this from the read-only path.
</blockquote></details>

Updated the method name to make that clear.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 625 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I96BK1HLnqgnrf28F:-N9IOxkP8ygZ2YNB_Bz0:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L625)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move `ba.IsLocking()` this down right above the WaitPolicy check.
</blockquote></details>

Done. 
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 628 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X0JtoBq5gcF0LENsz:-N9cA1Hd8zLbM4iyL3uY:b9tv4nl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L628)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It would be helpful to have a comment stating why !CONSISTENT is not eligible.
</blockquote></details>

PTAL. I'd like to have these requests still drop their latches early while also having them skip the initial lock table scan. Let me know if anything seems incorrect in that `TODO`.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X0Ru1ChBF0tJBQtjl:-N9cAFLnCZywS77SJTFD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L631)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

A code comment would help here, since its not clear what the `g==nil` case represents.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I9Asb6pma-xtQoLLH:-N9IPT5J2_v4nwyqxLNW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L643)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: here and below, panic on unexpected enum values instead of failing silently.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 656 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X1XNaDB7Wn52P5Lcm:-N9rP_Tu1H1sPAqhWY7n:bsrfy0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L656)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

A high-level comment would help here. IIUC, everything below is about ensuring the request does not acquire locks.
Otherwise it is hard to see why `ExportRequest` is always ok.
</blockquote></details>

How do you feel about the overall commentary here now?
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 662 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I9GGu24kagBoJFxcj:-N9IPZgH0ltwgokWLRk8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L662)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We shouldn't need this now that we're checking `IsLocking()`.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I9HYj0m4-xC8d-dqF:-N9IP_Mo6YuGslWDkhOE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L666)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same comment, this shouldn't be needed now.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_read.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IA6lL8KcvuVsSJDCX:-N9IQUjK70nQDDeaQ3MW:b-qj92pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L83)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can delete this now :partying_face: 
</blockquote></details>

Reworded.
___
*[`pkg/kv/kvserver/replica_read.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I9mSz-t6BtfycBAar:-N9IQan-13SpXK-S-DaT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L167)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can this be `if g != nil`. That would mean that latches are still held.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_read.go` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9I9_Hp2nhUo1ym_QHG:-N9IQc5P2Alj5ZBIfxSq:b-55hg01) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L231)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think the assignment to `g` is doing the right thing anymore, now that this is in a helper function. You'll need to lift that back up into `executeReadOnlyBatch` after each call to this function.
</blockquote></details>

Lifted.
___
*[`pkg/kv/kvserver/replica_read.go` line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IAfvQ8JhNUKtX3GZn:-N9cAvzR1mI6rKI2vlGS:bwfvbk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L266)):*
>What is the intent history in the context of a read-only request?

You're right, done. 
___
*[`pkg/kv/kvserver/replica_read.go` line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IB7T5AoObzXSR8-3I:-N9IQdkx6Hoh0-XH2GQh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L266)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `s/canDropLatches/ok/`, because this is already the name of the method.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_read.go` line 275 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IAk4d9FacQhDqTKRF:-N9xX0Hv-m9xI8BiCZlC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_read.go#L275)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Discussed in person: this isn't quite right. We don't want to scan across the entire boundary span, just the spans of the individual requests.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_read.go` line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9IAqDvESwOTUdly4Y3:-N9mXLfbAfcuqNteR8wn:b-896fix) ([raw file](https://github.com/cockroachdb/coc [...]

2022-08-23 17:39 UTC, sumeerbhola reviewed
btw, I'm just doing drive-by reviewing of selective pieces -- don't block on me for merging

> Reviewed 4 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-:-NAAmBOGDth25dmjZaMQ:b-qjfray)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_evaluate.go` line 656 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X1XNaDB7Wn52P5Lcm:-NAAl1Zj5zNEYNuwgiFG:b-47fafm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_evaluate.go#L656)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

How do you feel about the overall commentary here now?
</blockquote></details>

looks good
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 699 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAAl6sp-0ug72EwNlXt:-NAAl6sp-0ug72EwNlXu:b-nfnjim) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a6c2547f6ac9d2e600b76d11ddc37f42d8b365/pkg/kv/kvserver/replica_evaluate.go#L699)):*
> ```Go
> // using an intent interleaving iterator in order to be able to read the correct
> // provisional value.
> func scanConflictingIntents(
> ```

nit: we usually place such storage reading code in the storage package. It could go with the various helper functions defined at the bottom of engine.go (for example `ScanIntents`).
___
*[`pkg/storage/engine.go` line 1191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-N9X4vXh4JDBIXT10oAn:-NAAjVZe-0h1H2tfgeCW:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/storage/engine.go#L1191)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

> I wonder whether we will need a heuristic to guess that needIntentHistory will be false.

I don't fully follow this part, did you just mean to say that in some cases, we should be able to have a heuristic to say "this batch will definitely need access to the intent history, so don't bother scanning the lock table upfront"?

I'll post some benchmark results here shortly.
</blockquote></details>

Ack.


<!-- Sent from Reviewable.io -->

2022-08-23 18:32 UTC, aayushshah15 commented
Quick update on this PR:

I ran just the roachtest `ycsb/A/nodes=3/cpu=32` (for now) for 10 iterations each before and after this patch and here are the results:
```
benchstat before after

name  old ops/sec  new ops/sec  delta
.      27.6k ± 5%   28.9k ± 4%  +4.54%  (p=0.002 n=10+9)

name  old p50      new p50      delta
.       2.44 ± 2%    2.50 ± 0%  +2.46%  (p=0.034 n=10+7)

name  old p95      new p95      delta
.       8.80 ±10%    8.99 ±17%    ~     (p=0.764 n=10+10)

name  old p99      new p99      delta
.       74.4 ±13%    70.0 ±14%    ~     (p=0.192 n=10+10)
``` 

However, we're seeing a big regression in `TestCleanupIntentsDuringBackupPerformanceRegression` which is a test that prevents big regressions in the time it takes for backups to resolve a lot of intents, so I wouldn't fully trust those benchmark numbers yet. 

I'm digging into that right now, but it seems like I'm likely doing something silly in this initial lock table scan based on the CPU profiles from that test.
![image](https://user-images.githubusercontent.com/10788754/186236643-057602e3-38ef-481b-b743-56009a6ca5ff.png)

2022-08-24 03:05 UTC, aayushshah15 commented
I ran the `ycsb/[ABCDEF]/nodes=3/cpu=32` roachtests with and without this patch. The results seem promising! 

`new` is with this patch and `old` is without

#### YCSB-A 
```
name            old ops/sec  new ops/sec  delta
nodes=3/cpu=32   30.0k ± 7%   30.5k ± 8%    ~     (p=0.280 n=10+10)

name            old p50      new p50      delta
nodes=3/cpu=32    2.34 ±10%    2.26 ± 6%    ~     (p=0.242 n=10+10)

name            old p95      new p95      delta
nodes=3/cpu=32    8.51 ±10%    7.85 ± 3%  -7.76%  (p=0.001 n=10+8)

name            old p99      new p99      delta
nodes=3/cpu=32    62.9 ±13%    62.7 ±14%    ~     (p=0.990 n=9+9)

```

#### YCSB-B
```
name            old ops/sec  new ops/sec  delta
nodes=3/cpu=32   91.4k ± 4%   94.7k ± 3%   +3.59%  (p=0.007 n=10+10)

name            old p50      new p50      delta
nodes=3/cpu=32    1.40 ± 0%    1.40 ± 0%     ~     (all equal)

name            old p95      new p95      delta
nodes=3/cpu=32    5.83 ± 6%    5.62 ± 3%   -3.60%  (p=0.019 n=10+10)

name            old p99      new p99      delta
nodes=3/cpu=32    15.7 ±20%    12.8 ± 7%  -18.63%  (p=0.000 n=10+9)

```
#### YCSB-C
```
name            old ops/sec  new ops/sec  delta
nodes=3/cpu=32    123k ± 6%    131k ± 6%   +6.48%  (p=0.001 n=10+10)

name            old p50      new p50      delta
nodes=3/cpu=32    1.40 ± 0%    1.26 ± 5%  -10.00%  (p=0.000 n=9+10)

name            old p95      new p95      delta
nodes=3/cpu=32    3.42 ± 4%    3.26 ± 7%   -4.82%  (p=0.019 n=8+10)

name            old p99      new p99      delta
nodes=3/cpu=32    6.04 ±13%    5.52 ± 9%   -8.61%  (p=0.005 n=10+10)

```
#### YCSB-D
```
name            old ops/sec  new ops/sec  delta
nodes=3/cpu=32    101k ± 5%    106k ± 3%  +5.69%  (p=0.000 n=10+10)

name            old p50      new p50      delta
nodes=3/cpu=32    1.20 ± 0%    1.10 ± 0%  -8.33%  (p=0.000 n=10+8)

name            old p95      new p95      delta
nodes=3/cpu=32    3.51 ± 5%    3.36 ± 4%  -4.27%  (p=0.005 n=10+10)

name            old p99      new p99      delta
nodes=3/cpu=32    6.01 ± 5%    5.69 ± 5%  -5.32%  (p=0.013 n=10+10)

```

#### YCSB-E
```
name            old ops/sec  new ops/sec  delta
nodes=3/cpu=32   3.39k ± 3%   3.20k ±13%   ~     (p=0.089 n=10+10)

name            old p50      new p50      delta
nodes=3/cpu=32    36.5 ± 3%    39.0 ±13%   ~     (p=0.124 n=10+10)

name            old p95      new p95      delta
nodes=3/cpu=32     110 ± 3%     121 ±18%   ~     (p=0.067 n=10+10)

name            old p99      new p99      delta
nodes=3/cpu=32     151 ± 0%     162 ±19%   ~     (p=0.387 n=9+10)

```

#### YCSB-F
```
name            old ops/sec  new ops/sec  delta
nodes=3/cpu=32   15.4k ± 5%   15.9k ± 7%    ~     (p=0.095 n=9+10)

name            old p50      new p50      delta
nodes=3/cpu=32    5.59 ± 4%    5.53 ± 6%    ~     (p=0.720 n=10+10)

name            old p95      new p95      delta
nodes=3/cpu=32    17.4 ±10%    16.1 ± 6%  -7.00%  (p=0.008 n=10+9)

name            old p99      new p99      delta
nodes=3/cpu=32     158 ±22%     151 ±14%    ~     (p=0.577 n=10+10)

```

2022-08-24 04:05 UTC, nvanbenschoten reviewed
Those results look promising! Thanks for running them. It would also be worthwhile to run the kv0 and kv95 roachtests on 8 and 32 vCPU machines.

> Reviewed 4 of 14 files at r1, 8 of 11 files at r2, 2 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-:-NAD015G1KzHEPIJRrBj:bsxoxc1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_evaluate.go` line 699 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAAl6sp-0ug72EwNlXt:-NACsXUu5y_osBAHLPCr:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a6c2547f6ac9d2e600b76d11ddc37f42d8b365/pkg/kv/kvserver/replica_evaluate.go#L699)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: we usually place such storage reading code in the storage package. It could go with the various helper functions defined at the bottom of engine.go (for example `ScanIntents`).
</blockquote></details>

+1
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 646 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACrIMVBE31A8HfPT57:-NACrIMVBE31A8HfPT58:b87p8fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/replica_evaluate.go#L646)):*
> ```Go
> 	if len(g.Req.LockSpans.GetSpans(spanset.SpanReadOnly, spanset.SpanLocal)) != 0 {
> 		// If the request declared any local read spans, it must hold latches
> 		// throughout its execution.
> ```

Why is this?
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 708 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACvqrR8LhDApg7Xufq:-NACvqrR8LhDApg7Xufr:bhg9qbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/replica_evaluate.go#L708)):*
> ```Go
> 	maxIntents int64,
> ) (needIntentHistory bool, err error) {
> 	upperBoundUnset := bytes.Equal(end, roachpb.KeyMin) // NB: Get requests do not set the end key.
> ```

nit: this is usually expressed as `len(end) == 0`.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 714 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACvxeo2-ORx7JvFw0W:-NACvxeo2-ORx7JvFw0X:bbpggga) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/replica_evaluate.go#L714)):*
> ```Go
> 
> 	ltStart, _ := keys.LockTableSingleKey(start, nil)
> 	ltEnd, _ := keys.LockTableSingleKey(end, nil)
> ```

Can we avoid allocating this key if `upperBoundUnset`?
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 727 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACwE8G5F6EEC2AhlfX:-NACwE8G5F6EEC2AhlfY:b-mybkrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/replica_evaluate.go#L727)):*
> ```Go
> 	var ok bool
> 	for ok, err = iter.SeekEngineKeyGE(storage.EngineKey{Key: ltStart}); ok; ok, err = iter.NextEngineKey() {
> 		if err := ctx.Err(); err != nil {
> ```

Do we need to check the context on each key? This often incurs a mutex acquisition (depending on the ctx), so it could be expensive if there are a lot of keys in the lock table.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 733 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACxVmg3AH1bTp6dGiN:-NACxVmg3AH1bTp6dGiO:b-oukzsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/replica_evaluate.go#L733)):*
> ```Go
> 			break
> 		}
> 		key, err := iter.EngineKey()
> ```

This allocates and copies the key. In the next step, we decode the key. Should we save both until after we're sure it's a conflicting intent that we care about?
___
*[`pkg/kv/kvserver/replica_read.go` line 108 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACxyKrEzUELA4wep_h:-NACxyKrEzUELA4wep_i:b-ueodlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_read.go#L108)):*
> ```Go
> 			evalPath = readOnlyWithoutInterleavedIntents
> 		}
> 		g = r.updateTimestampCacheAndDropLatches(ctx, g, ba, nil /* br */, nil /* pErr */, st)
> ```

If `updateTimestampCacheAndDropLatches` always returns nil then it's probably not worth the confusion. Just have the next line be `g = nil`. We should do that down below with the other call to `updateTimestampCacheAndDropLatches` as well.
___
*[`pkg/kv/kvserver/replica_read.go` line 233 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAD06-d7_Mm5wzQb-DO:-NAD06-d7_Mm5wzQb-DP:b-apayz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_read.go#L233)):*
> ```Go
> 	ec := endCmds{repl: r, g: g, st: st}
> 	ec.done(ctx, ba, br, pErr)
> 	return nil
> ```

See my comment above.
___
*[`pkg/kv/kvserver/replica_read.go` line 236 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACyG7872UfPlDVb91D:-NACyG7872UfPlDVb91E:bqshmjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_read.go#L236)):*
> ```Go
> }
> 
> var allowDroppingLatchesBeforeEval = settings.RegisterBoolSetting(
> ```

Can we use this instead of the new testing knob in tests? But actually, is anyone using that testing knob?
___
*[`pkg/kv/kvserver/replica_read.go` line 288 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAD0BDeBKfnAbBf1xYz:-NAD0BDeBKfnAbBf1xZ-:bv56hs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_read.go#L288)):*
> ```Go
> 
> 	maxIntents := storage.MaxIntentsPerWriteIntentError.Get(&r.store.cfg.Settings.SV)
> 	var start, end roachpb.Key
> ```

nit: do these need such a large scope? Can we just do `start, end := ...` and `needsIntentInterleavingForThisRequest, err := 
 ...` in the loop?
___
*[`pkg/kv/kvserver/replica_send.go` line 795 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAD-2Am-V0UXbk4Lbio:-NAD-2Am-V0UXbk4Lbip:b-82k537) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_send.go#L795)):*
> ```Go
> 	// latchSpans, because we have already released our latches and plan to
> 	// re-acquire them if the retry is allowed.
> 	if !canDoServersideRetry(ctx, pErr, ba, nil /* br */, nil /* g */, hlc.Timestamp{} /* deadline */) {
> ```

nit: I don't think we want to lose this.
___
*[`pkg/kv/kvserver/replica_send.go` line 487 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAD-lU-09o19S0Y6cb6:-NAD-lU-09o19S0Y6cb7:bj6562n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_send.go#L487)):*
> ```Go
> 		dropLatchesAndLockWaitQueues := func() {
> 			if g != nil {
> 				latchSpans, lockSpans = g.TakeSpanSets()
> ```

We don't want to do this in the `ReadWithinUncertaintyIntervalError` case, so we may want this function to accept a `reuseLatchAndLockSpans` arg.
___
*[`pkg/kv/kvserver/store_test.go` line 1910 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACtqJtBxa0St9y7Ypf:-NACtqJtBxa0St9y7Ypg:b-s9okec) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/store_test.go#L1910)):*
> ```Go
> 	// This test expects different updates to the timestamp cache based on whether
> 	// a given request was evaluated under `PessimisticEval` or `OptimisticEval`.
> 	// If these requests hit any concurrency retry errors, they are typically
> ```

If we stay on the optimistic eval path after hitting a conflict, don't we risk seeing the same conflicting lock over and over again? Are there other ways that we could avoid the flakiness without introducing this knob? For i [...]

2022-08-24 19:50 UTC, aayushshah15 reviewed
>It would also be worthwhile to run the kv0 and kv95 roachtests on 8 and 32 vCPU machines.

#### kv95/enc=false/nodes=3/cpu=32 

```
name                      old ops/sec  new ops/sec  delta
enc=false/nodes=3/cpu=32    115k ± 9%    113k ± 7%   ~     (p=0.481 n=10+10)

name                      old p50      new p50      delta
enc=false/nodes=3/cpu=32    1.30 ± 0%    1.33 ± 5%   ~     (p=0.248 n=9+10)

name                      old p95      new p95      delta
enc=false/nodes=3/cpu=32    4.28 ±10%    4.34 ±15%   ~     (p=0.695 n=10+10)

name                      old p99      new p99      delta
enc=false/nodes=3/cpu=32    7.70 ± 3%    8.02 ±11%   ~     (p=0.135 n=9+10)

```

#### kv0/enc=false/nodes=3/cpu=32
```
name                      old ops/sec  new ops/sec  delta
enc=false/nodes=3/cpu=32   37.3k ± 7%   37.8k ± 8%   ~     (p=0.905 n=9+10)

name                      old p50      new p50      delta
enc=false/nodes=3/cpu=32    4.70 ± 0%    4.73 ± 6%   ~     (p=1.000 n=6+10)

name                      old p95      new p95      delta
enc=false/nodes=3/cpu=32    9.92 ±11%    9.70 ±13%   ~     (p=0.638 n=10+10)

name                      old p99      new p99      delta
enc=false/nodes=3/cpu=32    13.5 ±13%    13.5 ±21%   ~     (p=0.904 n=10+10)

```

I'll start the 8vCPU runs and post here if the results are any different from the above.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-:-NADSgia0Hww7GTp677F:bipv7it)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_evaluate.go` line 699 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAAl6sp-0ug72EwNlXt:-NADNeBE4hRXxy62ok7Z:b-wqwkbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/67a6c2547f6ac9d2e600b76d11ddc37f42d8b365/pkg/kv/kvserver/replica_evaluate.go#L699)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Moved back to `storage`.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 646 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACrIMVBE31A8HfPT57:-NAD5pxd8q8HOxpbitAy:b4ol062) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/replica_evaluate.go#L646)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why is this?
</blockquote></details>

Heh I'm not sure why I added this check. Maybe because of the last two subtests inside `TestReplicaLatchingTimestampNonInterference`. I think my initial thought was that we need to hold latches because local keys are non-mvcc, but given that we're evaluating over a pebble snapshot, don't now see why we'd need to hold latches during eval. I've removed this check now.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 708 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACvqrR8LhDApg7Xufq:-NADADMR9S7xA3sCcwa_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/replica_evaluate.go#L708)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: this is usually expressed as `len(end) == 0`.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 714 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACvxeo2-ORx7JvFw0W:-NADAK-f0JFHIGLGnRX4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/replica_evaluate.go#L714)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we avoid allocating this key if `upperBoundUnset`?
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 727 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACwE8G5F6EEC2AhlfX:-NADB3047C9GBSAOBVQO:b-gs6dbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/replica_evaluate.go#L727)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to check the context on each key? This often incurs a mutex acquisition (depending on the ctx), so it could be expensive if there are a lot of keys in the lock table.
</blockquote></details>

Did you want me to move it out of the loop entirely and just check it at the beginning and the end? I've made that change for now but let me know if that's not desirable.
___
*[`pkg/kv/kvserver/replica_evaluate.go` line 733 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACxVmg3AH1bTp6dGiN:-NAD3UY-Cd-I8DfHzoeh:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ba3c673b6c5831ed267098bc0c3e65bc31f323/pkg/kv/kvserver/replica_evaluate.go#L733)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This allocates and copies the key. In the next step, we decode the key. Should we save both until after we're sure it's a conflicting intent that we care about?
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/replica_read.go` line 108 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACxyKrEzUELA4wep_h:-NAD3kWqAnuiygoVAbCo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_read.go#L108)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If `updateTimestampCacheAndDropLatches` always returns nil then it's probably not worth the confusion. Just have the next line be `g = nil`. We should do that down below with the other call to `updateTimestampCacheAndDropLatches` as well.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_read.go` line 233 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAD06-d7_Mm5wzQb-DO:-NAD4uL_5yUOA8hmLLhh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_read.go#L233)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

See my comment above.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_read.go` line 236 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NACyG7872UfPlDVb91D:-NADF4yB-HqEcndttEfF:bm7x9sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_read.go#L236)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we use this instead of the new testing knob in tests? But actually, is anyone using that testing knob?
</blockquote></details>

Nope, I'd added it while playing around with some of these test failures. Removed now.
___
*[`pkg/kv/kvserver/replica_read.go` line 288 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAD0BDeBKfnAbBf1xYz:-NAD4sn4Eger3Sa5pm1p:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_read.go#L288)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: do these need such a large scope? Can we just do `start, end := ...` and `needsIntentInterleavingForThisRequest, err := 
 ...` in the loop?
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/replica_send.go` line 795 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAD-2Am-V0UXbk4Lbio:-NAD57FWBuZCNCvpPQ-g:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e46d282d48ed277a926145a9118aa867eb699a5d/pkg/kv/kvserver/replica_send.go#L795)):*
<details><summary><i>Previously, nvanbenschoten (Nathan [...]

2022-08-25 21:59 UTC, nvanbenschoten reviewed
> Reviewed 8 of 9 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_send.go` line 487 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAD-lU-09o19S0Y6cb6:-NALzjePCqnL2a2atf5z:b3zavvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_send.go#L487)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Do you dislike what we're doing for `ReadWithinUncertaintyIntervalError` in this revision? 
```
	dropLatchesAndLockWaitQueues()
	// If the batch is able to perform a server-side retry in order to avoid
	// the uncertainty error, it will have a new timestamp. Force a refresh of
	// the latch and lock spans.
	latchSpans, lockSpans = nil, nil
```
</blockquote></details>

That works, but it fails to Release the spansets back into their sync.Pool. You get that for free if you don't `TakeSpanSets()` before `FinishReq`.
___
*[`pkg/kv/kvserver/replica_send.go` line 525 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAM-2o_C0KyTS-23QnY:-NAM-2o_C0KyTS-23QnZ:b-wqpzq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8560f93c4fc9004ef6c5e2927fe6bf8c159980/pkg/kv/kvserver/replica_send.go#L525)):*
> ```Go
> 				return nil, nil, pErr
> 			}
> 		case *roachpb.ReadWithinUncertaintyIntervalError:
> ```

Is this the only case where latches might have already been dropped?
___
*[`pkg/kv/kvserver/batcheval/cmd_export.go` line 94 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAM-hBRBWrCq1t4k1Fm:-NAM-hBRBWrCq1t4k1Fn:b-iwd7y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8560f93c4fc9004ef6c5e2927fe6bf8c159980/pkg/kv/kvserver/batcheval/cmd_export.go#L94)):*
> ```Go
> 	DefaultDeclareIsolatedKeys(rs, header, req, latchSpans, lockSpans, maxOffset)
> 	latchSpans.AddNonMVCC(spanset.SpanReadOnly, roachpb.Span{Key: keys.RangeGCThresholdKey(header.RangeID)})
> 	// Export requests will usually not hold latches during their evaluation.
> ```

Why did we need this? Do the spanset assertion work when evaluating without latches?


<!-- Sent from Reviewable.io -->

2022-09-06 18:54 UTC, sumeerbhola reviewed
Isn't ycsb-c read-only? I am confused by the improvement there, since I was expecting to see an improvement only for workloads with read-write contention. What am I missing?

Do we think ycsb-b and ycsb-d, which have only 5% writes, are better because:
- the zipfian/latest distributions result in contention
- the read latch release reduces contention for waiting writes, which helps reads that arrive after the write (since we have fair FIFO latch behavior, that can cause read-read contention due to intervening writes).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-:-NBJ7GWf5BA4e7YRZrpU:bjhvbqf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-10-04 19:14 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_send.go` line 487 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAD-lU-09o19S0Y6cb6:-NDZ7iDk98p6F3lDCWbV:bqkpqr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6dce8f5665107c3d952d4c9622882f6951d116a4/pkg/kv/kvserver/replica_send.go#L487)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That works, but it fails to Release the spansets back into their sync.Pool. You get that for free if you don't `TakeSpanSets()` before `FinishReq`.
</blockquote></details>

oh, that makes sense. Done. 
___
*[`pkg/kv/kvserver/replica_send.go` line 525 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAM-2o_C0KyTS-23QnY:-NDZ7ST6-fyrIh9w3f2V:b-o6b98f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8560f93c4fc9004ef6c5e2927fe6bf8c159980/pkg/kv/kvserver/replica_send.go#L525)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this the only case where latches might have already been dropped?
</blockquote></details>

Yes I think so 
___
*[`pkg/kv/kvserver/batcheval/cmd_export.go` line 94 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/85993#-NAM-hBRBWrCq1t4k1Fm:-NDZP6moCnBES-CAshsG:b-crz5g6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e8560f93c4fc9004ef6c5e2927fe6bf8c159980/pkg/kv/kvserver/batcheval/cmd_export.go#L94)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why did we need this? Do the spanset assertion work when evaluating without latches?
</blockquote></details>

It's because we specifically assert on accesses to the GC threshold key here: https://github.com/cockroachdb/cockroach/blob/cd0fb93fd672cf84ea599fcdbd5c1623ecec9a42/pkg/kv/kvserver/replica_eval_context_span.go#L160-L162. 

Do you feel like we should address this differently? 


<!-- Sent from Reviewable.io -->

2022-10-10 04:13 UTC, aayushshah15 commented
I re-ran YCSB-E (for 50 iterations) and YCSB-C (for 20 iterations) to try and clarify the results from https://github.com/cockroachdb/cockroach/pull/85993#issuecomment-1225125983.

```
benchstat before after
name                   old ops/sec  new ops/sec  delta
ycsb/E/nodes=3/cpu=32   3.48k ± 5%   3.41k ± 4%  -2.19%  (p=0.000 n=45+50)

name                   old p50      new p50      delta
ycsb/E/nodes=3/cpu=32    35.7 ± 0%    36.3 ± 4%  +1.57%  (p=0.000 n=44+50)

name                   old p95      new p95      delta
ycsb/E/nodes=3/cpu=32     108 ± 5%     110 ± 5%  +1.78%  (p=0.000 n=45+50)

name                   old p99      new p99      delta
ycsb/E/nodes=3/cpu=32     149 ± 7%     151 ± 0%  +1.03%  (p=0.048 n=49+36)

```

```
benchstat before after
name                   old ops/sec  new ops/sec  delta
ycsb/C/nodes=3/cpu=32    132k ± 2%    134k ± 4%    ~     (p=0.141 n=17+20)

name                   old p50      new p50      delta
ycsb/C/nodes=3/cpu=32    1.30 ± 0%    1.20 ± 0%  -7.69%  (p=0.000 n=16+18)

name                   old p95      new p95      delta
ycsb/C/nodes=3/cpu=32    3.30 ± 0%    3.23 ± 5%    ~     (p=0.302 n=12+20)

name                   old p99      new p99      delta
ycsb/C/nodes=3/cpu=32    5.50 ± 0%    5.49 ± 9%    ~     (p=0.594 n=15+20)

```

Do these numbers make more sense @sumeerbhola? The reasons you've outlined for improvements in YCSB B and D match my understanding.

2022-10-20 19:10 UTC, sumeerbhola commented
No change in ycsb/C does make sense. Thanks for collecting the numbers.

2022-10-31 14:21 UTC, nvanbenschoten approved these changes
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-10-31 14:22 UTC, nvanbenschoten commented
But let's still wait until v22.2 is out the door (in a week or so) before merging onto master.

2022-11-07 18:47 UTC, nvanbenschoten commented
Test failures on master will no longer be considered release blockers, so we can go ahead and merge this. Nice job @aayushshah15!

2022-11-17 16:53 UTC, aayushshah15 commented
TFTRs 

bors r+

2022-11-17 17:31 UTC, sumeerbhola approved these changes

2022-11-17 17:35 UTC, aayushshah15 commented
bors r+

2022-11-17 18:29 UTC, aayushshah15 commented
bors r+

2022-11-17 19:55 UTC, merged