sql: Support DISCARD SEQUENCES
cockroachdb/cockroach pull request #86230
Opened 2022-08-16 15:59 UTC by e-mbrown

Release note (sql change): We now support DISCARD SEQUENCES, which discards
all sequence-related state such as currval/lastval information. DISCARD ALL
now also discards sequence-related state.

2022-08-18 19:12 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86230)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/sql/discard.go` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mIPv9BmYMuXxSiu6o:-N9mIPvAD9X6cnYxTBpE:b-s25jsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/discard.go#L45)):*
> ```Go
> 		p.preparedStatements.DeleteAll(ctx)
> 
> 		//DISCARD SEQUENCES
> ```

nit: add a space after `//`
___
*[`pkg/sql/discard.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mM6-m1cItaBEQlnYM:-N9mM6-m1cItaBEQlnYN:b-gm2wki) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/discard.go#L49)):*
> ```Go
> 
> 	case tree.DiscardModeSequences:
> 		p.SessionData().SequenceState = sessiondata.NewSequenceState()
> ```

these calls should both be:
```
		p.sessionDataMutatorIterator.applyOnEachMutator(func(m sessionDataMutator) {
			m.data.SequenceState = sessiondata.NewSequenceState()
			m.initSequenceCache() 
		})
```

`applyOnEachMutator` is needed because it iterates through the stack of sessionData -- when a new transaction is started, a new sessionData is added to the stack.
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mKl7q6RJpvHZhpj-8:-N9mKl7q6RJpvHZhpj-9:b-h7dfrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/logictest/testdata/logic_test/discard#L47)):*
> ```
> 
> statement ok
> DISCARD ALL
> ```

can you verify that DISCARD ALL also removes the sequence info too
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mKdkC41DgcVE-DbJq:-N9mKdkC41DgcVE-DbJr:b-293b0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/logictest/testdata/logic_test/discard#L62)):*
> ```
> 
> statement ok
> CREATE SEQUENCE lastval_test_2 START WITH 10
> ```

nit: maybe name it `discard_seq_test`
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mMgAl0AOscGcEd4BM:-N9mMgAl0AOscGcEd4BN:bvtv7mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/logictest/testdata/logic_test/discard#L67)):*
> ```
> SELECT nextval('lastval_test_2')
> ----
> 10
> ```

we also want to make sure we match this behavior from postgres:

```
rafiss@127:postgres> create sequence s2 cache 10;
CREATE SEQUENCE

rafiss@127:postgres> select nextval('s2');
+---------+
| nextval |
|---------|
| 1       |
+---------+

rafiss@127:postgres> discard sequences;
DISCARD SEQUENCES

rafiss@127:postgres> select nextval('s2');
+---------+
| nextval |
|---------|
| 11      |
+---------+
```
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mKRNt6XiZz9OFS-N0:-N9mKRNz4BfNL2BouJfT:b-bsmr6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/logictest/testdata/logic_test/discard#L72)):*
> ```
> SELECT lastval()
> ----
> 10
> ```

can you also check that `SELECT currval('lastval_test_2')` returns 10 here
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mKYjAAAsZtZD-xdIh:-N9mKYjAAAsZtZD-xdIi:b-qg9rpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/logictest/testdata/logic_test/discard#L78)):*
> ```
> 
> statement error pgcode 55000 pq: lastval\(\): lastval is not yet defined in this session
> SELECT lastval()
> ```

and check that `SELECT currval('lastval_test_2')` returns a "currval of sequence "s" is not yet defined in this session" error here
___
*[`pkg/sql/sem/tree/discard.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mIYzJ2p_qgknUU28-:-N9mIYzK5jJQ_K2gycwB:b7ijwf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/sem/tree/discard.go#L28)):*
> ```Go
> 
> 	// DiscardModeSequences represents a DISCARD SEQUENCES statement
> 	DiscardModeSequences DiscardMode = iota
> ```

the `iota` keyword is special. it's defined once in the block, and then it causes everything else to count up from there. so you want
```
const (
	// DiscardModeAll represents a DISCARD ALL statement.
	DiscardModeAll DiscardMode = iota

	// DiscardModeSequences represents a DISCARD SEQUENCES statement
	DiscardModeSequences
)
```

the type is also added implicitly. 


<!-- Sent from Reviewable.io -->

2022-08-22 17:11 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86230)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/discard.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mM6-m1cItaBEQlnYM:-NA5FalZ6X6vlKTS6s06:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/discard.go#L49)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

these calls should both be:
```
		p.sessionDataMutatorIterator.applyOnEachMutator(func(m sessionDataMutator) {
			m.data.SequenceState = sessiondata.NewSequenceState()
			m.initSequenceCache() 
		})
```

`applyOnEachMutator` is needed because it iterates through the stack of sessionData -- when a new transaction is started, a new sessionData is added to the stack.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mKl7q6RJpvHZhpj-8:-NA5SchVA83de2bqNxkT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/logictest/testdata/logic_test/discard#L47)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you verify that DISCARD ALL also removes the sequence info too
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mMgAl0AOscGcEd4BM:-NA5Uzlk1QxcRL3UPK-q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/logictest/testdata/logic_test/discard#L67)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we also want to make sure we match this behavior from postgres:

```
rafiss@127:postgres> create sequence s2 cache 10;
CREATE SEQUENCE

rafiss@127:postgres> select nextval('s2');
+---------+
| nextval |
|---------|
| 1       |
+---------+

rafiss@127:postgres> discard sequences;
DISCARD SEQUENCES

rafiss@127:postgres> select nextval('s2');
+---------+
| nextval |
|---------|
| 11      |
+---------+
```
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mKRNt6XiZz9OFS-N0:-NA5Vp33EDI817_hpt7C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/logictest/testdata/logic_test/discard#L72)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you also check that `SELECT currval('lastval_test_2')` returns 10 here
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mKYjAAAsZtZD-xdIh:-NA5XAF27OGV74F5Qa2M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/logictest/testdata/logic_test/discard#L78)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

and check that `SELECT currval('lastval_test_2')` returns a "currval of sequence "s" is not yet defined in this session" error here
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/discard.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-N9mIYzJ2p_qgknUU28-:-NA5XHDf3RxXYtBXu64F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edca7426cd37b7722762ccf64e9361fcb5e0982c/pkg/sql/sem/tree/discard.go#L28)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the `iota` keyword is special. it's defined once in the block, and then it causes everything else to count up from there. so you want
```
const (
	// DiscardModeAll represents a DISCARD ALL statement.
	DiscardModeAll DiscardMode = iota

	// DiscardModeSequences represents a DISCARD SEQUENCES statement
	DiscardModeSequences
)
```

the type is also added implicitly. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-22 21:19 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86230)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-NA6Q5eYCHQV1_CpjEkU:-NA6Q5eYCHQV1_CpjEkV:b-nhnfjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4502ea1af4488334910189387622be4e58d295cd/pkg/sql/logictest/testdata/logic_test/discard#L50)):*
> ```
> 
> statement error pgcode 55000 pq: lastval\(\): lastval is not yet defined in this session
> SELECT lastval()
> ```

this test isn't testing the right thing, since there was no sequence used before the call to DISCARD ALL. so we'd want to create and use a sequence before DISCARD ALL


<!-- Sent from Reviewable.io -->

2022-08-23 16:26 UTC, rafiss approved these changes
lgtm! but it does need to be rebased first

2022-08-24 15:01 UTC, rafiss approved these changes
this lgtm! i'm gonna try to bors it, since the failures seem too be flakes

bors r+

> Reviewed 2 of 7 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86230#-:-NAFMfapCcDJ4JXjp0wi:b-n9xt53)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)



<!-- Sent from Reviewable.io -->

2022-08-25 03:27 UTC, merged