sql: Implement Discard Temp
cockroachdb/cockroach pull request #86246
Opened 2022-08-16 19:25 UTC by e-mbrown

Release note (sql change): We now support DISCARD TEMP/TEMPORARY, which drops
all temporary tables created in the current session. The command does not drop
temporary schemas.

2022-08-16 19:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/86246)
<!-- Reviewable:end -->

2022-08-18 16:00 UTC, ajwerner commented
How is this a bug fix? Seems like a new feature to me.

2022-08-18 18:52 UTC, e-mbrown reviewed
Updated

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-:-N9mI5bw6cGH6nQMeMjp:b-bu91xm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)



<!-- Sent from Reviewable.io -->

2022-08-26 18:19 UTC, rafiss commented
the bug fix part of this is that `DISCARD ALL` was supposed to also run the `DISCARD TEMP` logic, but it wasn't

2022-08-26 20:53 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/sql/discard.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQrlki2A2BPtVXJZPd:-NAQrlki2A2BPtVXJZPe:b7yw6ak) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L55)):*
> ```Go
> 
> 		//	DISCARD TEMP
> 		err := prepareDeleteTempTables(ctx, p)
> ```

the `prepare` part of the function name seems unnecessary
___
*[`pkg/sql/discard.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQtJfICKRHGK90sdfe:-NAQtJfICKRHGK90sdff:bcqy267) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L94)):*
> ```Go
> }
> 
> func getTempSchema(
> ```

why is this named `getTempSchema`? it looks like it is returning sessionIDs
___
*[`pkg/sql/discard.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQto2QBkf9YupD8gL9:-NAQto2QBkf9YupD8gLA:b-izv704) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L106)):*
> ```Go
> 		}
> 
> 		for _, scEntry := range schemaEntries {
> ```

you shouldn't need to iterate here -- actually it would be wrong since this will mean that it will delete _all_ of the temporary tables including those from other sessions.

instead use `p.SessionData().DatabaseIDToTempSchemaID[dbDesc.ID]` to get the temp schema for each DB (if one exists)
___
*[`pkg/sql/discard.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQsjpV5wJw4SYVZLsO:-NAQsjpV5wJw4SYVZLsP:bpp8wxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L109)):*
> ```Go
> 			isTempSchema, sessionID, err := temporarySchemaSessionID(scEntry.Name)
> 			if err != nil {
> 				// This should not cause an error.
> ```

this should return the error instead of logging and ignoring it
___
*[`pkg/sql/discard.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQsibJ0MrUPzQKlMq7:-NAQsibJ0MrUPzQKlMq8:by68onj) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L119)):*
> ```Go
> 		}
> 	}
> 	log.Infof(ctx, "found %d temporary schemas", len(sessionIDs))
> ```

no need to log this
___
*[`pkg/sql/discard.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQv7Gh1OfS8CibPmJq:-NAQv7Gh1OfS8CibPmJr:blrwzol) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L137)):*
> ```Go
> 
> 	for _, dbDesc := range allDbDescs {
> 		err = removeTempTable(ctx, p, ie, descCol, dbDesc, sessionIDs)
> ```

can you instead call `cleanupSchemaObjects`, which already exists?


<!-- Sent from Reviewable.io -->

2022-08-26 20:54 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/sql/discard.go` line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQvjSq03O2doegXvTQ:-NAQvjSq03O2doegXvTR:b-2pvpe3) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L145)):*
> ```Go
> }
> 
> func removeTempTable(
> ```

with the above comment, there shouldn't be a need for this function


<!-- Sent from Reviewable.io -->

2022-08-30 18:24 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/discard.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQrlki2A2BPtVXJZPd:-NAj1Vt74XwQjoA2y65s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L55)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the `prepare` part of the function name seems unnecessary
</blockquote></details>

Done.
___
*[`pkg/sql/discard.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQtJfICKRHGK90sdfe:-NAj1lOq67FllPEvtj1N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L94)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why is this named `getTempSchema`? it looks like it is returning sessionIDs
</blockquote></details>

Done.
___
*[`pkg/sql/discard.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQto2QBkf9YupD8gL9:-NAjqc4s2xrqmtXowlmN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L106)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

you shouldn't need to iterate here -- actually it would be wrong since this will mean that it will delete _all_ of the temporary tables including those from other sessions.

instead use `p.SessionData().DatabaseIDToTempSchemaID[dbDesc.ID]` to get the temp schema for each DB (if one exists)
</blockquote></details>

Done.
___
*[`pkg/sql/discard.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQsjpV5wJw4SYVZLsO:-NAjqcRB3ahMPawErfni:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L109)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this should return the error instead of logging and ignoring it
</blockquote></details>

Done.
___
*[`pkg/sql/discard.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQsibJ0MrUPzQKlMq7:-NAjzs7z7UbvKS1JVY0T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L119)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

no need to log this
</blockquote></details>

Done.
___
*[`pkg/sql/discard.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQv7Gh1OfS8CibPmJq:-NAjzsT83Tvwkc75bsKR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L137)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you instead call `cleanupSchemaObjects`, which already exists?
</blockquote></details>

Done.
___
*[`pkg/sql/discard.go` line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAQvjSq03O2doegXvTQ:-NAjqddw3S7tX7EjFMl8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/caa21ad7332c69b8a73fe7fb93ea17ba694feded/pkg/sql/discard.go#L145)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

with the above comment, there shouldn't be a need for this function
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-30 20:45 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/sql/discard.go` line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAkUgAE1GL-6OLYQf16:-NAkUgAE1GL-6OLYQf17:b-nzc1po) ([raw file](https://github.com/cockroachdb/cockroach/blob/94bd6fcbbc4f06749540fd5fa4ad00690c4794f2/pkg/sql/discard.go#L69)):*
> ```Go
> 		})
> 	case tree.DiscardModeTemp:
> 		err := deleteTempTables(params.ctx, params.p)
> ```

this needs to be called as part of DISCARD ALL too
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 120 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAkUnVg4VtXOd-yH-eI:-NAkUnVg4VtXOd-yH-eJ:b-96fkh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/94bd6fcbbc4f06749540fd5fa4ad00690c4794f2/pkg/sql/logictest/testdata/logic_test/discard#L120)):*
> ```
> statement ok
> SET experimental_enable_temp_tables=on
> ```

can you test what happens if DISCARD TEMP is called before creating any temp tables? i would expect `SELECT count(*) FROM [SHOW SCHEMAS] WHERE schema_name LIKE 'pg_temp_%` to return 0 both before and after the DISCARD TEMP


<!-- Sent from Reviewable.io -->

2022-08-31 13:53 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/discard.go` line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAkUgAE1GL-6OLYQf16:-NAo6eIK4RDzq21ua5xP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/94bd6fcbbc4f06749540fd5fa4ad00690c4794f2/pkg/sql/discard.go#L69)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this needs to be called as part of DISCARD ALL too
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/discard` line 120 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAkUnVg4VtXOd-yH-eI:-NAoAF3z-UraTzQr6DEv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/94bd6fcbbc4f06749540fd5fa4ad00690c4794f2/pkg/sql/logictest/testdata/logic_test/discard#L120)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you test what happens if DISCARD TEMP is called before creating any temp tables? i would expect `SELECT count(*) FROM [SHOW SCHEMAS] WHERE schema_name LIKE 'pg_temp_%` to return 0 both before and after the DISCARD TEMP
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-31 15:43 UTC, rafiss approved these changes
very nice, lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-:-NAoZd9G7wJ6zKznI_PM:b2k9n6f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)



<!-- Sent from Reviewable.io -->

2022-08-31 15:44 UTC, rafiss approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86246)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86246#-NAoZjms71DswqlhMfnC):*
can you also add another note like `Release note (bug fix): DISCARD ALL now deletes temporary tables`


<!-- Sent from Reviewable.io -->

2022-08-31 18:23 UTC, rafiss approved these changes
bors r+

2022-08-31 19:17 UTC, merged