[DNM] eventpb: add storage event types
cockroachdb/cockroach pull request #86277
Opened 2022-08-17 02:15 UTC by nicktrav

The first commit is from #86242.

---

Add the `StoreStats` event type, a per-store metric emitted to the
`TELEMETRY` logging channel. This event type will be populated from the
Pebble metrics for each store.

This patch adds the API for the event type. The wiring and scheduling of
the event type will be added in a subsequent patch.

Touches #85589.

Release note: None.

Release justification: low risk, high benefit changes to existing
functionality.

2022-08-17 02:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/86277)
<!-- Reviewable:end -->

2022-08-17 02:17 UTC, nicktrav commented
cc: @jbowens - sneak peak at the new event type. I've cherry-picked a bunch of metrics from the Pebble metrics, erring on the side of "too many". We can probably prune this list a bit, but wanted to get a sense check on what we'd be capturing (second commit).

2022-08-22 14:11 UTC, sumeerbhola requested changes
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86277)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @nicktrav)

___
*[`pkg/kv/kvserver/store.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NA4rBLH0hr4rQveEQrK:-NA4rBLH0hr4rQveEQrL:b-ua27vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e5e401d6595407229f316b4f7b064efc863e6ce/pkg/kv/kvserver/store.go#L130)):*
> ```Go
> var logStoreTelemetryTicks = envutil.EnvOrDefaultInt(
> 	"COCKROACH_LOG_STORE_TELEMETRY_TICKS_INTERVAL",
> 	6*60, // Once per hour. (tick interval = 10s) * 6 * 60 = 3600s = 1h.
> ```

what's the justification for 1h intervals? Can we miss transient interesting events because of this coarse granularity? What are other layers using as their telemetry logging interval?
___
*[`pkg/util/log/eventpb/storage_events.proto` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NA4rt3Q9fAEANPLgZBG:-NA4rt3Q9fAEANPLgZBH:b-84o6f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e5e401d6595407229f316b4f7b064efc863e6ce/pkg/util/log/eventpb/storage_events.proto#L33)):*
> ```protobuf
>   repeated LevelStats levels = 4 [(gogoproto.nullable) = false, (gogoproto.jsontag) = ""];
> 
>   // Cache metrics.
> ```

Could you add in parentheses whether something is cumulative? I'm assuming everything here is cumulative since node restart. Do we expect to take deltas or rates of these cumulative values downstream (in the analytics pipeline)? If yes, would it be simpler to export the deltas? Otherwise I can imagine a more complex calculation where we also export the restart time and then do a delta calculation from 0 if the restart time changed. Metrics systems can sometimes do that under the covers for you (Monarch did), but it is a complicated sql query to write in the absence of built-in support.


<!-- Sent from Reviewable.io -->

2022-08-22 23:35 UTC, nicktrav reviewed
After talking with some folks internally, I'm going to open this back up for review.

Some points that I've discussed with folks:

**PCI compliance / sensitive data.** There is no PII emitted in these per-store stats. The data in each even is numerical, and pertains the state of a single LSM (i.e. store).

**Data volume.** We've landed on a starting rate of one event per store per hour. There were some concerns that logging too much could overload the fluentbit logging daemon. I expect the size of the events to be on the order of low single digit KB per event (uncompressed). The set of stats present in this PR can also be scoped down, if necessary, to bring this number down.

More context in this [thread](https://cockroachlabs.slack.com/archives/C0222501329/p1661201907662669) (internal).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-:-NA6q7igBq8N48SEo_bZ:bpg5xmb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @pransudash, and @sumeerbhola)

___
*[`pkg/kv/kvserver/store.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NA4rBLH0hr4rQveEQrK:-NA53j495SuhTLMrqw1K:b1u6w1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e5e401d6595407229f316b4f7b064efc863e6ce/pkg/kv/kvserver/store.go#L130)):*
> what's the justification for 1h intervals?

My intention was to strike a balance between frequent (basically degenerates into timeseries metrics the lower the interval, and is more expensive, puts more stress on the logging infra) and useful (when emitting infrequently, derived metrics like rates of change become harder to compute, etc.). I believe the lower bound is more important from an operational / cost perspective. I suspect on the upper bound, logging as infrequently as once every 24 hours could still be useful. I'd be hesitant to go higher than that.

> Can we miss transient interesting events because of this coarse granularity?

Certainly - however, the goal of this telemetry logging isn't to capture such events. These new telemetry events are intended to roll up to provide an aggregate view across all clusters (cloud, for now). We're more interested in the trends / broad themes. We have the ability to dig into the details if necessary, as we have the cluster, node and store information in the events.

> What are other layers using as their telemetry logging interval?

One recent example of telemetry logging is #84761. That emits schema information _once per week_.

I have a thread going [here](https://cockroachlabs.slack.com/archives/C0222501329/p1661201907662669) (internal) that discusses what is reasonable. tldr: it was indicated that an event per store per hour seems like a reasonable starting point, and should not be an issue.
___
*[`pkg/kv/kvserver/store.go` line 3357 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NA6ogWH8BKSMBx_Xlq2:-NA6ogWH8BKSMBx_Xlq3:be5iy5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/341e8c3c60726254a29fdfcd0c49d6655664045a/pkg/kv/kvserver/store.go#L3357)):*
> ```Go
> 	// if reporting is enabled. These events are intended to be emitted at low
> 	// frequency. Trigger on tick 1 for the same reasons as above.
> 	if logcrash.DiagnosticsReportingEnabled.Get(&s.ClusterSettings().SV) &&
> ```

While the `logcrash` package name doesn't seem all that relevant here, [the comment on `DiagnosticsReportingEnabled`](https://github.com/cockroachdb/cockroach/blob/76f5b3aa459f2f1cc6cf8400600ba7db60e0bb14/pkg/util/log/logcrash/crash_reporting.go#L40-L53) makes me believe it is suitable for use as a gate on whether we should emit the event or not:

```
	// "diagnostics.reporting.enabled" enables reporting of metrics related to a
	// node's storage (number, size and health of ranges) back to CockroachDB.
	// Collecting this data from production clusters helps us understand and improve
	// how our storage systems behave in real-world use cases.
```

If there's a better cluster setting / env var to use, please let me know. Alternatively, if it's fine to unconditionally log this to the telemetry channel, that could also be an option (less inclined to do this for non-CC clusters, as that data is effectively useless and will eat up disk space).
___
*[`pkg/util/log/eventpb/storage_events.proto` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NA4rt3Q9fAEANPLgZBG:-NA6pQiG9kSz3T0jSF1G:b-i06sa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e5e401d6595407229f316b4f7b064efc863e6ce/pkg/util/log/eventpb/storage_events.proto#L33)):*
> Could you add in parentheses whether something is cumulative? 

Done. Clarified whether a metric is a counter or gauge.

>  I'm assuming everything here is cumulative since node restart.

Correct. Added that clarification at the top.

> Do we expect to take deltas or rates of these cumulative values downstream (in the analytics pipeline)?

cc: @pransudash - do you know the answer to this? Will it be an issue if we emit counters that contain discontinuities? I assume that's only an issue to consider when we get to performing the analytics?


<!-- Sent from Reviewable.io -->

2022-08-23 16:05 UTC, jbowens approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

modulo the question about deltas.

> Reviewed 1 of 11 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-:-NAARmUHCO3c8ZH-1BzZ:bj46c0e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @nicktrav, @pransudash, and @sumeerbhola)

___
*[`pkg/kv/kvserver/store.go` line 3358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NAAPPIMABCc1CS_T72P:-NAAPPIN5JDWr09Abp4J:bma3me8) ([raw file](https://github.com/cockroachdb/cockroach/blob/341e8c3c60726254a29fdfcd0c49d6655664045a/pkg/kv/kvserver/store.go#L3358)):*
> ```Go
> 	// frequency. Trigger on tick 1 for the same reasons as above.
> 	if logcrash.DiagnosticsReportingEnabled.Get(&s.ClusterSettings().SV) &&
> 		tick%logStoreTelemetryTicks == 1 {
> ```

To avoid spamming the telemetry if we're crash looping, I think we could report on `tick%logStoreTelemetryTicks == logStoreTelemetryTicks-1`.
___
*[`pkg/storage/engine.go` line 1062 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NAAQLdK1Av2-EPzeUc6:-NAAQLdK1Av2-EPzeUc7:bupf29c) ([raw file](https://github.com/cockroachdb/cockroach/blob/341e8c3c60726254a29fdfcd0c49d6655664045a/pkg/storage/engine.go#L1062)):*
> ```Go
> 		TableZombieCount:           m.Table.ZombieCount,
> 		TableZombieSize:            m.Table.ZombieSize,
> 	}
> ```

maybe I'm greedy, but I'm not sure if there's anything I'd want to drop. If anything, maybe `WAL.ObsoleteFiles` and `WAL.ObsoletePhysicalSize`.

I think eventually we could replace `CompactionNumInProgress` with a value that shows the 'effective compaction concurrency' over time, rather than just a single moment. I think including the `CompactionNumInProgress` until we have that metric is fine.

Can we add the new `Keys.RangeKeySetsCount` metric too?


<!-- Sent from Reviewable.io -->

2022-08-23 21:36 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86277)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens, @knz, @pransudash, and @sumeerbhola)

___
*[`pkg/kv/kvserver/store.go` line 3358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NAAPPIMABCc1CS_T72P:-NABbeP19QZykzpKdJXY:bombmv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/341e8c3c60726254a29fdfcd0c49d6655664045a/pkg/kv/kvserver/store.go#L3358)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

To avoid spamming the telemetry if we're crash looping, I think we could report on `tick%logStoreTelemetryTicks == logStoreTelemetryTicks-1`.
</blockquote></details>

Good call. Done.
___
*[`pkg/storage/engine.go` line 1062 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NAAQLdK1Av2-EPzeUc6:-NABa1ccDIa_dqIzkSDe:b-h8t5es) ([raw file](https://github.com/cockroachdb/cockroach/blob/341e8c3c60726254a29fdfcd0c49d6655664045a/pkg/storage/engine.go#L1062)):*
> Can we add the new Keys.RangeKeySetsCount metric too?

Done!

>  not sure if there's anything I'd want to drop.

+1 - Given the limited concern around the amount of data being emitted and the relative infrequency (even at one event per hour per store), I'm inclined to keep this set of metrics as they are.


<!-- Sent from Reviewable.io -->

2022-08-23 23:17 UTC, pransudash reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86277)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @jbowens, @knz, and @sumeerbhola)

___
*[`pkg/util/log/eventpb/storage_events.proto` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NA4rt3Q9fAEANPLgZBG:-NAByKRB2td4np3DO3Qa:b-hu98gz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e5e401d6595407229f316b4f7b064efc863e6ce/pkg/util/log/eventpb/storage_events.proto#L33)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> Could you add in parentheses whether something is cumulative? 

Done. Clarified whether a metric is a counter or gauge.

>  I'm assuming everything here is cumulative since node restart.

Correct. Added that clarification at the top.

> Do we expect to take deltas or rates of these cumulative values downstream (in the analytics pipeline)?

cc: @pransudash - do you know the answer to this? Will it be an issue if we emit counters that contain discontinuities? I assume that's only an issue to consider when we get to performing the analytics?
</blockquote></details>

If needed, I can instruct downstream pipelines to reconstruct deltas from the cumulative values and this something we do frequently for other datasets. As long as your counters are always increasing, that shouldn't be an issue. If it ever decreases or goes back to 0 does that mean the node restarted? In any case, I think it's good to keep cumulative values and only include deltas if they can't be reliably calculated from the counters.


<!-- Sent from Reviewable.io -->

2022-08-24 14:08 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86277)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @jbowens, @knz, and @sumeerbhola)

___
*[`pkg/util/log/eventpb/storage_events.proto` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NA4rt3Q9fAEANPLgZBG:-NAFA6_KBc86OW64zaTu:b-rj9at5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e5e401d6595407229f316b4f7b064efc863e6ce/pkg/util/log/eventpb/storage_events.proto#L33)):*
>  If it ever decreases or goes back to 0 does that mean the node restarted?

Correct.

> I think it's good to keep cumulative values and only include deltas if they can't be reliably calculated from the counters.

Great. In that case I think we should be good here. We have either counters or gauges. No deltas.


<!-- Sent from Reviewable.io -->

2022-09-06 19:03 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86277)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @jbowens, @knz, @pransudash, and @sumeerbhola)

___
*[`pkg/util/log/eventpb/storage_events.proto` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-NA4rt3Q9fAEANPLgZBG:-NBJAJGK295WGOrRV6gj:b-mor69g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e5e401d6595407229f316b4f7b064efc863e6ce/pkg/util/log/eventpb/storage_events.proto#L33)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

>  If it ever decreases or goes back to 0 does that mean the node restarted?

Correct.

> I think it's good to keep cumulative values and only include deltas if they can't be reliably calculated from the counters.

Great. In that case I think we should be good here. We have either counters or gauges. No deltas.
</blockquote></details>

Ignore me since I'm being nitpicky, but I do want to stress that we can't really reliably calculate from resetting counters since we may observe monotonically non-decreasing values despite the counter having dropped to 0.


<!-- Sent from Reviewable.io -->

2022-09-21 18:51 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86277#-:-NCWO0vq3oGkiqygTJj-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @jbowens, @knz, @pransudash, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-09-21 18:54 UTC, pransudash commented
@nicktrav Sounds good! Let me know if there's any need for us to chat about reporting from these log events. I'm assuming the logs are still scheduled to send hourly?

2022-09-21 19:08 UTC, nicktrav commented
bors r=jbowens,sumeerbhola

2022-09-21 21:14 UTC, merged