cli: add `--managed` flag, log.SafeManaged redaction function & usage
cockroachdb/cockroach pull request #86475
Opened 2022-08-19 19:02 UTC by abarganier

Currently, log redaction policies have no way to discern their own
runtime environment. Logged objects that may be considered sensitive
and unsafe in on-prem deployments of CockroachDB might be otherwise
safe when we're running within a managed service such as Cockroach
Cloud. For example, CLI argument lists included as part of the
`cockroach start` command are already known to those operating the
managed service, so there's no reason we should be redacting this
information from logs in this case.

This patch adds the `--managed` flag to the start commands. This
flag is plumbed through to the global logging config object where
the log package has access to it.

We also introduce `log.SafeManaged(s interface{})`, which conditionally
marks an object with `redact.Safe()` depending on whether or not we
are running as a managed service. This is inspired by the original
`log.SafeOperational(s interface{})` function.

I believe that this new `--managed` flag should not be advertised in
our public documentation, as its intended use is for those running
Cockroach Cloud.

Release justification: low-risk, high benefit changes to existing
functionality. The new CLI flag has a minimal impact on DB
operations and provides high value reduction of log redaction,
which will be necessary for support staff with our latest compliance
requirements.

Release note (cli change): `cockroach start` commands now have an
additional `--managed` flag that can be used to indicate whether
or not the node is running as part of a managed service (e.g.
Cockroach Cloud). Perhaps this shouldn't be advertised in our
public facing docs, as its only intended for use by those running
Cockroach Cloud and not for on-prem deployments.

Release justification:

2022-08-19 19:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/86475)
<!-- Reviewable:end -->

2022-08-22 13:46 UTC, knz reviewed
> Reviewed 1 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @logston)

___
*[`pkg/base/config.go` line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4kvndB3D6IUrNTKyd:-NA4kvndB3D6IUrNTKye:b-m15oka) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/base/config.go#L163)):*
> ```Go
> 	// of a managed service (e.g. CockroachCloud). Impacts log
> 	// redaction policies.
> 	Managed bool
> ```

Not here. Add the field to `cliCtx` in pkg/cli/context.go.
___
*[`pkg/base/config.go` line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4kzeG5WsI--XqrzJO:-NA4kzeG5WsI--XqrzJP:b4ei2vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/base/config.go#L270)):*
> ```Go
> func (cfg *Config) InitDefaults() {
> 	cfg.Insecure = defaultInsecure
> 	cfg.Managed = defaultManaged
> ```

Do this in `setCliConextDefaults`, pkg/cli/context.go.
___
*[`pkg/cli/context.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4l6jhAKki6Wp6A88G:-NA4l6jhAKki6Wp6A88H:blfs4qx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/cli/context.go#L454)):*
> ```Go
> 	serverCertPrincipalMap []string
> 	serverListenAddr       string
> 	serverManaged          bool
> ```

no need for this.
___
*[`pkg/cli/flags.go` line 476 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4l8EX9N7VFCiPHx5i:-NA4l8EX9N7VFCiPHx5j:b-741737) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/cli/flags.go#L476)):*
> ```Go
> 		// NB: Insecure is deprecated. See #53404.
> 		cliflagcfg.BoolFlag(f, &startCtx.serverInsecure, cliflags.ServerInsecure)
> 		cliflagcfg.BoolFlag(f, &startCtx.serverManaged, cliflags.ServerManaged)
> ```

cliCtx.managed
___
*[`pkg/cli/flags.go` line 894 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4lDW78VcX88zsD8pJ:-NA4lDW78VcX88zsD8pK:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/cli/flags.go#L894)):*
> ```Go
> 		// NB: Insecure is deprecated. See #53404.
> 		cliflagcfg.BoolFlag(f, &startCtx.serverInsecure, cliflags.ServerInsecure)
> 		cliflagcfg.BoolFlag(f, &startCtx.serverManaged, cliflags.ServerManaged)
> ```

ditto
___
*[`pkg/cli/flags.go` line 994 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4lE83BOvqFmRnZyms:-NA4lE8457OQNp7eovbt:b-3w2u63) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/cli/flags.go#L994)):*
> ```Go
> 	serverCfg.User = username.NodeUserName()
> 	serverCfg.Insecure = startCtx.serverInsecure
> 	serverCfg.Managed = startCtx.serverManaged
> ```

no need for this
___
*[`pkg/util/log/redact.go` line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4lP1u7GFYl1rewecl:-NA4lP1u7GFYl1rewecm:by8hrtv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/util/log/redact.go#L223)):*
> ```Go
> // and does not need to be treated as sensitive. This function marks
> // the provided object as safe/unsafe accordingly.
> func SafeManaged(s interface{}) redact.RedactableString {
> ```

Nah, this is not the right way to go about this. Let's get away from global variables. Try this instead:

1. here:
```go
func SafeManaged(a interface{}) interface{} {
   return safeManaged{a}
}

type safeManaged struct {a  interface{}}
```

2. in `makeUnstructuredEntry`, taking inspiration from https://github.com/cockroachdb/cockroach/pull/82891, something like that:
```go
for i, a := range args {
			if e, ok := a.(safeManaged); ok && logger.managed {
				args[i] = e.a
			}
		}
```

(you might need to copy the args slice if there's a safeManaged in it, instead of overwriting it in-place, i'm not sure)

this will likely need to make `makeUnstructuredEntry` a method of *loggerT, but I think that's OK.

The flip side is that it opens the door to choosing the redaction per logger (i.e. per channel) too.


<!-- Sent from Reviewable.io -->

2022-08-22 13:48 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @logston)

___
*[`pkg/util/log/redact.go` line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4lP1u7GFYl1rewecl:-NA4nu7M7IZ1RDC5_EYI:boxuxit) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/util/log/redact.go#L223)):*
> safeManaged

btw that new `safeManaged` type will need a Format and/or SafeFormat method too.


<!-- Sent from Reviewable.io -->

2022-08-22 13:49 UTC, knz commented
I encourage you to study how the `redact` library does this, see the source in `internal/redact/wrappers.go`.

2022-08-27 00:14 UTC, abarganier reviewed
Thanks for the feedback - RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-:-NARGmbYAAjDPS3prmJV:b-d0douj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @logston)

___
*[`pkg/base/config.go` line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4kvndB3D6IUrNTKyd:-NARFmGd4A3ZaCXBAv_5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/base/config.go#L163)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Not here. Add the field to `cliCtx` in pkg/cli/context.go.
</blockquote></details>

Done.
___
*[`pkg/base/config.go` line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4kzeG5WsI--XqrzJO:-NARFn-LDNn_9vfKeOQo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/base/config.go#L270)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Do this in `setCliConextDefaults`, pkg/cli/context.go.
</blockquote></details>

Done.
___
*[`pkg/cli/context.go` line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4l6jhAKki6Wp6A88G:-NAPoLRjB8v_TnNm_AG0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/cli/context.go#L454)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

no need for this.
</blockquote></details>

Done.
___
*[`pkg/cli/flags.go` line 476 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4l8EX9N7VFCiPHx5i:-NAPoKQa5_owcLm71AZr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/cli/flags.go#L476)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

cliCtx.managed
</blockquote></details>

Done.
___
*[`pkg/cli/flags.go` line 894 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4lDW78VcX88zsD8pJ:-NAPoKBDAxbDhEdF-aaB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/cli/flags.go#L894)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/cli/flags.go` line 994 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4lE83BOvqFmRnZyms:-NAPoJl96e7tvXhMdD2Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/cli/flags.go#L994)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

no need for this
</blockquote></details>

Done.
___
*[`pkg/util/log/redact.go` line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4lP1u7GFYl1rewecl:-NAREMWmBvY7Bb4-YikR:bm7gu4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/util/log/redact.go#L223)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> safeManaged

btw that new `safeManaged` type will need a Format and/or SafeFormat method too.

</blockquote></details>

Thanks for this advice - the separate `safeManaged` type implementing `redact.SafeFormatter` is a much better approach. 

I gave modifying `makeUnstructuredEntry` a try and defining it on the `*loggerT` itself. Things were going great, until some testing at the end revealed that handling the conditional unwrapping depending on `logger.managed` within `makeUnstructuredEntry` doesn't cover cases [such as this one](https://github.com/cockroachdb/cockroach/blob/8e3b269ef209bf0c1eaf100a42b436752492704f/pkg/cli/start.go#L1046) where  `RedactableBytes()` is called on a `redact.StringBuilder`. 

Instead, we need to know the state of the `managed` flag at the time `SafeManaged` was called, or at the time `SafeFormat` is called. Otherwise, my interpretation is that we won't have full coverage. Let me know if I'm missing something.

As a result, I chose to store a copy of the state of the `managed` flag at call time for `SafeManaged` (but I don't feel strongly about it over checking `isManaged()` when executing `SafeFormat`). I've added a `managed bool` to the new type, which we can reference within `SafeFormat` to make the determination there on whether to mark safe or not. This covers cases such as `RedactableBytes` nicely.

I realize this still leaves us depending on the package-global `logging` variable :thinking:. As an alternative, I chose to at least define `setManaged` and `isManaged` on the `loggingT` itself. I didn't see a good way to include it as part of the `loggerT` itself, but I'm open to alternatives - let me know any thoughts you might have. 


<!-- Sent from Reviewable.io -->

2022-08-29 16:15 UTC, abarganier reviewed
I did some thinking about this over the weekend. To optimize for meeting our requirements before we cut for 22.2, I'd like to keep the implementation here simple where we choose to wrap in `safeManaged`/leave as-is at the time we call `SafeManaged`. 

Looking forward, I am feeling the need for a more holistic solution to these "conditional redaction" cases. I've created https://github.com/cockroachdb/cockroach/issues/87038 to track this work & come up with a broader solution that aligns with our future goals of multiple logging configurations per-process.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-:-NAeNAFz5QsJFolCXdW0:b-p4ty4w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @logston)

___
*[`pkg/util/log/redact.go` line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NA4lP1u7GFYl1rewecl:-NAeMupC3fd-gQwsox4o:bq7dq5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6b2a76bcf4c1269e1296006d1f6b4a343920fe2/pkg/util/log/redact.go#L223)):*
> As a result, I chose to store a copy of the state of the managed flag at call time for SafeManaged (but I don't feel strongly about it over checking isManaged() when executing SafeFormat). I've added a managed bool to the new type, which we can reference within SafeFormat to make the determination there on whether to mark safe or not. This covers cases such as RedactableBytes nicely.

After some sleep I realized that storing the state of `managed` within `safeManaged` is completely unnecessary. We'll just check it at the time `SafeManaged` is called & make the decision to wrap/leave as-is then. 


<!-- Sent from Reviewable.io -->

2022-08-31 16:50 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @knz, and @logston)

___
*[`pkg/cli/cliflags/flags.go` line 729 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAol79J3oRY9UnhFm--:-NAol79J3oRY9UnhFm-0:bx8hwnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/cli/cliflags/flags.go#L729)):*
> ```Go
> 	}
> 
> 	ServerManaged = FlagInfo{
> ```

instead of a flag, would it be better to make this part of the `logconfig.Config` ?
___
*[`pkg/cli/cliflags/flags.go` line 733 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAokGy25gCOQy88Y8I1:-NAokGy25gCOQy88Y8I2:bbk3l80) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/cli/cliflags/flags.go#L733)):*
> ```Go
> 		EnvVar: "COCKROACH_MANAGED",
> 		Description: `
> Indicate that the node being started is being run as part of a managed service.
> ```

s/being started/
___
*[`pkg/util/log/redact.go` line 226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAongxT2vvEALJHz1LN:-NAongxT2vvEALJHz1LO:b-ae8i5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/util/log/redact.go#L226)):*
> ```Go
> // NB: If the argument itself implements the redact.SafeFormatter interface,
> // then we delegate to its implementation in either case.
> func SafeManaged(a interface{}) interface{} {
> ```

consider leaving a link to https://github.com/cockroachdb/cockroach/issues/87038 in a comment
___
*[`pkg/util/log/redact.go` line 230 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAomXpV9NPPS-5ZSVie:-NAomXpV9NPPS-5ZSVif:b3wcutq) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/util/log/redact.go#L230)):*
> 	return safeManaged{a}

instead of this, could we do `return redact.Safe(a)` and get rid of `safeManaged` ? Wouldn't that be simpler?
I think the `safeManaged` struct would be useful if the decision to the argument or not was deferred to logging time, but given the current structure I don't understand what it's for.


<!-- Sent from Reviewable.io -->

2022-09-01 19:20 UTC, abarganier reviewed
TFTR, RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-:-NAuUkZf8fck9nHOiZIW:b-lhgni0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @logston)

___
*[`pkg/cli/cliflags/flags.go` line 729 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAol79J3oRY9UnhFm--:-NAuUS3TB_4Ly_NrfE4u:b4ypsp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/cli/cliflags/flags.go#L729)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

instead of a flag, would it be better to make this part of the `logconfig.Config` ?
</blockquote></details>

I gave this some thought and I'd like to keep it as a flag. I could see this flag being used in the future for purposes beyond just logging, where we want to alter behavior elsewhere if we're running in a managed service. 
___
*[`pkg/cli/cliflags/flags.go` line 733 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAokGy25gCOQy88Y8I1:-NAuUj716wLJg1-QqNeH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/cli/cliflags/flags.go#L733)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/being started/
</blockquote></details>

Done.
___
*[`pkg/util/log/redact.go` line 226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAongxT2vvEALJHz1LN:-NAuUIPIBxLy1xqxJual:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/util/log/redact.go#L226)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider leaving a link to https://github.com/cockroachdb/cockroach/issues/87038 in a comment
</blockquote></details>

Done.
___
*[`pkg/util/log/redact.go` line 230 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAomXpV9NPPS-5ZSVie:-NAuUIv2AlMY2wxWt6PN:b-2lbagt) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/util/log/redact.go#L230)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> 	return safeManaged{a}

instead of this, could we do `return redact.Safe(a)` and get rid of `safeManaged` ? Wouldn't that be simpler?
I think the `safeManaged` struct would be useful if the decision to the argument or not was deferred to logging time, but given the current structure I don't understand what it's for.
</blockquote></details>

You're right - we've essentially come full circle on this :sweat_smile: . Switched it to the simpler approach. 


<!-- Sent from Reviewable.io -->

2022-09-01 19:48 UTC, andreimatei approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-:-NAuYsGY9f32UYype8DR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @knz, and @logston)

___
*[`pkg/cli/cliflags/flags.go` line 729 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAol79J3oRY9UnhFm--:-NAuZ8RmDcsVWW8Jggni:bi8f3te) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/cli/cliflags/flags.go#L729)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

I gave this some thought and I'd like to keep it as a flag. I could see this flag being used in the future for purposes beyond just logging, where we want to alter behavior elsewhere if we're running in a managed service. 
</blockquote></details>

I don't very clearly see how "running as a managed service" is tied to the logging changes being made here. It seems to me that it's not the fact that it's a managed service that makes all the things you're unredacting safe, but that it's CRL who runs this managed service and we don't intend to give anyone else `debug.zip`'s produced by it. So perhaps consider `--crl-managed` as the flag name. I generally feel that we haven't dissected enough what it is that makes what we're doing here safe, so I'd still vote we relegate this setting to a more narrowly-scoped log config option. But whatever you think.
___
*[`pkg/cli/cliflags/flags.go` line 733 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAu_OVL0YdencUKGccj:-NAu_OVL0YdencUKGcck:bd1ju2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e3bcdb96c89574039cbf520478f1c13466eb23/pkg/cli/cliflags/flags.go#L733)):*
> ```Go
> 		EnvVar: "COCKROACH_MANAGED",
> 		Description: `
> Indicate that the node is being run as part of a managed service/ This primarily
> ```

there's a slash at the end of the first sentence


<!-- Sent from Reviewable.io -->

2022-09-01 19:58 UTC, abarganier reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @andreimatei, @knz, and @logston)

___
*[`pkg/cli/cliflags/flags.go` line 729 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAol79J3oRY9UnhFm--:-NAucQTW5CHBy52c_UYj:bqnt8lo) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/cli/cliflags/flags.go#L729)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't very clearly see how "running as a managed service" is tied to the logging changes being made here. It seems to me that it's not the fact that it's a managed service that makes all the things you're unredacting safe, but that it's CRL who runs this managed service and we don't intend to give anyone else `debug.zip`'s produced by it. So perhaps consider `--crl-managed` as the flag name. I generally feel that we haven't dissected enough what it is that makes what we're doing here safe, so I'd still vote we relegate this setting to a more narrowly-scoped log config option. But whatever you think.
</blockquote></details>

I think you make a good point - I'll prepare a patch to move this into the logging config


<!-- Sent from Reviewable.io -->

2022-09-06 14:26 UTC, abarganier reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @knz, and @logston)

___
*[`pkg/cli/cliflags/flags.go` line 729 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAol79J3oRY9UnhFm--:-NBIBKbZDVcLB0llth2v:b816anu) ([raw file](https://github.com/cockroachdb/cockroach/blob/838aa0af846de1c0bfe3907bf5035a44d34b59c5/pkg/cli/cliflags/flags.go#L729)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

I think you make a good point - I'll prepare a patch to move this into the logging config
</blockquote></details>

After further consideration, our time table to get this delivered as part of the larger PCI redaction project is too tight to rework the implementation at this point. I'm going to leave as-is. 
___
*[`pkg/cli/cliflags/flags.go` line 733 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NAu_OVL0YdencUKGccj:-NBIBKPAAbt_fwT94XAN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2e3bcdb96c89574039cbf520478f1c13466eb23/pkg/cli/cliflags/flags.go#L733)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

there's a slash at the end of the first sentence
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-06 14:43 UTC, knz reviewed
Overall OK, but I'm :-1: on adding a CLI flag at all. IMHO this should be exclusively an env var. See rationale below.

> Reviewed 8 of 15 files at r2, 12 of 14 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-:-NBIFEE-D7i87gcl4qql:b-7k6vpz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @andreimatei, @knz, and @logston)

___
*[`pkg/cli/cliflags/flags.go` line 730 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NBIEZO4Denzzp58JxNa:-NBIEZO4Denzzp58JxNb:b-ayx9v0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5a9f9dbbbc8bc20ed9fc9b6163b8993db8a1784/pkg/cli/cliflags/flags.go#L730)):*
> ```Go
> 
> 	ServerManaged = FlagInfo{
> 		Name:   "managed",
> ```

I think a flag with this word structure `--managed` is not sufficiently descriptive. 
Can we make it `--keep-operational-details-during-redaction`? or perhaps `--log-redact-policy=managed`

But really I am also wondering if this needs a documented command-line flag at all. I think the env var should be sufficient? Especially for CC deployments, adding a new flag means that the operator team needs to detect the version of crdb before they decide to add the flag.

With an env var, they can set it for every version without causing errors and the new version will pick it up automatically.


<!-- Sent from Reviewable.io -->

2022-09-06 15:12 UTC, abarganier reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @knz, and @logston)

___
*[`pkg/cli/cliflags/flags.go` line 730 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NBIEZO4Denzzp58JxNa:-NBILrENCHz_dHRNVz1q:bz8vfvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5a9f9dbbbc8bc20ed9fc9b6163b8993db8a1784/pkg/cli/cliflags/flags.go#L730)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think a flag with this word structure `--managed` is not sufficiently descriptive. 
Can we make it `--keep-operational-details-during-redaction`? or perhaps `--log-redact-policy=managed`

But really I am also wondering if this needs a documented command-line flag at all. I think the env var should be sufficient? Especially for CC deployments, adding a new flag means that the operator team needs to detect the version of crdb before they decide to add the flag.

With an env var, they can set it for every version without causing errors and the new version will pick it up automatically.
</blockquote></details>

That SGTM, especially since this is primarily meant to only be used by CRL. Thanks for the guidance here - I'll prepare a patch to remove the flag & solely rely on the env var instead.


<!-- Sent from Reviewable.io -->

2022-09-07 17:48 UTC, abarganier reviewed
I've removed the flag in favor of an environment variable, and adjusted the naming to be more descriptive.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-:-NBO2iEG5EbhydcmqKxZ:bdwr408)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @knz, and @logston)



<!-- Sent from Reviewable.io -->

2022-09-07 17:56 UTC, knz requested changes
I think this is missing unit tests.

> Reviewed 11 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-:-NBO56tJ-3HcJTvM_2Gh:b89tfjl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @andreimatei, @knz, and @logston)

___
*[`pkg/cli/flags.go` line 526 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NBO4rEZ5Siu24XJGIgX:-NBO4rEZ5Siu24XJGIgY:b-cv044x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ffb93b1341fc15d81cc59dd6a8597632f22b04/pkg/cli/flags.go#L526)):*
> ```Go
> 		}
> 
> 		cliCtx.redactionPolicyManaged = envutil.EnvOrDefaultBool(redactionPolicyManagedEnvVar, false)
> ```

Not quite. I'm expecting this will crash.
Also, it won't properly reset in-between unit tests.

I recommend you move this logic in `context.go` (same directory), in `setCliContextDefaults()`.


<!-- Sent from Reviewable.io -->

2022-09-07 18:53 UTC, abarganier reviewed
Added unit tests and reduced invasiveness on `pkg/cli`. We now contain the handling of the env var within `pkg/util/log`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-:-NBOElo40dsJDN3teApv:b-a9u704)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @knz, and @logston)

___
*[`pkg/cli/flags.go` line 526 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86475#-NBO4rEZ5Siu24XJGIgX:-NBOEz9999iqes0X-lYD:bbo7w6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ffb93b1341fc15d81cc59dd6a8597632f22b04/pkg/cli/flags.go#L526)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Not quite. I'm expecting this will crash.
Also, it won't properly reset in-between unit tests.

I recommend you move this logic in `context.go` (same directory), in `setCliContextDefaults()`.
</blockquote></details>

I didn't experience any crash during manual testing, but nonetheless, if we're not using a CLI flag anymore then it doesn't feel like we need to invade on this package.

I've instead opted to move all of this into `log.ApplyConfig`. We can read the env variable there, allowing tests that touch logging (e.g. use `TestingResetActive()` and `log.ApplyConfig()`) to reset in-between unit tests.


<!-- Sent from Reviewable.io -->

2022-09-07 19:07 UTC, knz approved these changes
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86475)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @knz, and @logston)



<!-- Sent from Reviewable.io -->

2022-09-08 15:37 UTC, abarganier commented
bors r=knz

2022-09-08 17:15 UTC, merged