ui/cluster-ui: create statements insights api
cockroachdb/cockroach pull request #86596
Opened 2022-08-22 18:43 UTC by xinhaoz

This commit adds a function to the `cluster-ui` pkg that queries
`crdb_internal.cluster_execution_insights` to surface slow running
queries. The information retrieved  is intended to be used in the
insights statement overview and details pages.

Release justification: non-production code change
Release note: None

2022-08-22 18:43 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/86596)
<!-- Reviewable:end -->

2022-08-22 20:10 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69CQ2A1TF99He6JMC:-NA69CQ2A1TF99He6JMD:b-rm300a) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L249)):*
> ```XML
>   session_id: string;
>   txn_id: string;
>   txn_fingerprint_id: string; // bytes
> ```

we are always using the ids as int64, so it's better to keep consistency, in case we want to use that value to link to the details page of that fingerprint id. To be able to do this there are 2 things you will need to change. I'll add a line on the 2 places
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69zjD-64ILGHCv3qk:-NA69zjD-64ILGHCv3ql:b-rerm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L282)):*
> ```XML
>     const end = moment.utc(row.end_time);
>     return {
>       transactionID: row.txn_id,
> ```

are you missing txn fingerprint ID? Looks like you can on the query, but don't use it
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69oEU8yzlOCV3IGlQ:-NA69oEU8yzlOCV3IGlR:b-hg5scf) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L291)):*
> ```XML
>       execType: InsightExecEnum.STATEMENT,
>       statementID: row.stmt_id,
>       statementFingerprintID: row.stmt_fingerprint_id,
> ```

use `HexStringToInt64String(row.stmt_fingerprint_id)`
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69XH64qCZSJenF_Hl:-NA69XH64qCZSJenF_Hm:b37vpzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L314)):*
> ```XML
>       session_id,
>       txn_id,
>       txn_fingerprint_id,
> ```

change to `encode(txn_fingerprint_id, 'hex') AS txn_fingerprint_id,`
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69Z3qDI7CSReLCxxm:-NA69Z3qDI7CSReLCxxn:br08fs8) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L316)):*
> ```XML
>       txn_fingerprint_id,
>       stmt_id,
>       stmt_fingerprint_id,
> ```

change to `encode(stmt_fingerprint_id, 'hex') AS stmt_fingerprint_id,`


<!-- Sent from Reviewable.io -->

2022-08-22 20:18 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69CQ2A1TF99He6JMC:-NA6C-3kEE6dpA62GcXz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L249)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

we are always using the ids as int64, so it's better to keep consistency, in case we want to use that value to link to the details page of that fingerprint id. To be able to do this there are 2 things you will need to change. I'll add a line on the 2 places
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69zjD-64ILGHCv3qk:-NA6BzELEbiV9bcE8pTQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L282)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

are you missing txn fingerprint ID? Looks like you can on the query, but don't use it
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69oEU8yzlOCV3IGlQ:-NA6C07q8jY30Nyhfv2G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L291)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

use `HexStringToInt64String(row.stmt_fingerprint_id)`
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69XH64qCZSJenF_Hl:-NA6C0u61vzPqTPdjDt-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L314)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

change to `encode(txn_fingerprint_id, 'hex') AS txn_fingerprint_id,`
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69Z3qDI7CSReLCxxm:-NA6C1r68oQxzjV2CutX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L316)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

change to `encode(stmt_fingerprint_id, 'hex') AS stmt_fingerprint_id,`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-22 20:47 UTC, maryliag reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA69CQ2A1TF99He6JMC:-NA6IYmN1jl06oSk_I5q:b-pmku6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/85150ebdb01adc42aa4d1b91d131a3d1969f0bcc/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L249)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

don't forget to remove the bytes comment, since it's no longer bytes


<!-- Sent from Reviewable.io -->

2022-08-22 22:41 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-:-NA6hqYQ-5bcsmNVzsuk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)



<!-- Sent from Reviewable.io -->

2022-08-22 22:48 UTC, ericharmeling approved these changes
Nice! LGTM

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-:-NA6jUTrB7u9t9DUoSVz:bcyhil1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)



<!-- Sent from Reviewable.io -->

2022-08-23 13:41 UTC, j82w reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86596)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 308 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NA9vNLw4pEvp5zLGVTq:-NA9vNLx7hlpi4L-blPM:b1m85wt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7fb31a5f2e9ead4c43e90dbc759341a2227c314/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L308)):*
> ```XML
> }
> 
> const statemenInsightsQuery: InsightQuery<
> ```

typo: statementInsightsQuery


<!-- Sent from Reviewable.io -->

2022-08-23 15:14 UTC, j82w requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86596)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 290 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-NAAFsbh9vWIxQtBGMj5:-NAAFsbh9vWIxQtBGMj6:bjyun69) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7fb31a5f2e9ead4c43e90dbc759341a2227c314/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L290)):*
> ```XML
>       endTime: end,
>       databaseName: row.database_name,
>       elapsedTimeMillis: start.diff(end, "milliseconds"),
> ```

This causes it to be negative. You need to reverse start and end. 


<!-- Sent from Reviewable.io -->

2022-08-23 17:26 UTC, j82w approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86596#-:-NAAjOdr55Y3bF1EjthO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2022-08-23 17:37 UTC, xinhaoz commented
TFTR!
bors r+

2022-08-23 23:04 UTC, xinhaoz commented
bors r+

2022-08-24 11:23 UTC, j82w commented
bors r+

2022-08-24 21:26 UTC, xinhaoz commented
bors r+

2022-08-25 02:15 UTC, merged