[wip,dnm] admission,kvserver: elastic cpu granter
cockroachdb/cockroach pull request #86638
Opened 2022-08-23 05:46 UTC by irfansharif

Release note: None
Release justification: Non-production code

2022-08-23 05:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/86638)
<!-- Reviewable:end -->

2022-08-24 07:57 UTC, irfansharif commented
@sumeerbhola @andrewbaptist this is ready for a look. There are some TODOs (marked with `XXX:`) in there I need to address (missing tests, a microbenchmark, and granting requests more frequently to ensure high utilization) that I'll do while you review.

2022-08-24 19:58 UTC, sumeerbhola requested changes
> Reviewed 1 of 1 files at r1, 27 of 27 files at r5, 23 of 29 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andrewbaptist, @irfansharif, and @sumeerbhola)

___
*[`pkg/kv/kvserver/store.go` line 3815 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAG9z2-1FixH1HFQ24k:-NAG9z2-1FixH1HFQ24l:b48y20w) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/kv/kvserver/store.go#L3815)):*
> ```Go
> 	}
> 
> 	bypassAdmission := ba.IsAdmin()
> ```

There is also rearrangement of logic here. It looks correct to me, but this is also a part that has no existing tests (my fault).
Can you add a TODO to write a unit test for this -- there are enough cases that make me nervous. Fine to do it after the branch cut.
___
*[`pkg/kv/kvserver/store.go` line 3856 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAG9DYi9sPvFvFqqRqn:-NAG9DYi9sPvFvFqqRqo:bbczsbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/kv/kvserver/store.go#L3856)):*
> ```Go
> 			if admissionEnabled {
> 				defer func() {
> 					if retErr != nil {
> ```

does a return from this function that uses a different variable automatically populate `retErr` before the defer is run?
___
*[`pkg/kv/kvserver/kvadmissionhandle/handle.go` line 54 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAG6zUqDgCXjEQDfSCN:-NAG6zUqDgCXjEQDfSCO:b-onau90) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/kv/kvserver/kvadmissionhandle/handle.go#L54)):*
> ```Go
> // ContextWithHandle returns a Context wrapping the supplied kvadmission handle.
> func ContextWithHandle(ctx context.Context, h Handle) context.Context {
> 	return context.WithValue(ctx, handleKey{}, h)
> ```

this is a memory allocation, yes?
Is this only being used plumb the ability to call `OverElasticCPULimit`? If yes, can we call this something like `ContextWithElasticCPUWorkHandle` and only do the allocation for those elastic cases. Those seem heavy weight enough for the allocation to not matter.
___
*[`pkg/storage/mvcc.go` line 5880 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGBCPTAaSwrT8bAC2p:-NAGBCPTAaSwrT8bAC2q:b-1etrb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/storage/mvcc.go#L5880)):*
> ```Go
> 		// prefer callers being able to use SSTs directly). Going over limit is
> 		// accounted for in admission control by penalizing the subsequent
> 		// request, so doing it slightly is find.
> ```

s/find/fine/
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 182 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGO64M3de7Uu9ccCSe:-NAGO64M3de7Uu9ccCSf:btq8o9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_granter.go#L182)):*
> ```Go
> 		tokens := e.requester.granted(noGrantChain)
> 		if tokens == 0 {
> 			return // requester didn't accept, nothing to do
> ```

don't we give back the 1 token that was consumed?
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 191 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGOl_s4XDHoTSybNwj:-NAGOl_s4XDHoTSybNwk:bv22i3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_granter.go#L191)):*
> ```Go
> // TODO(irfansharif): Provide separate enums for different elastic CPU token
> // sizes? (1ms, 10ms, 100ms). Write up something about picking the right value.
> // Can this value be auto-estimated?
> ```

(note to self) haven't looked at these metrics yet
___
*[`pkg/util/admission/elastic_cpu_utilization_adjuster.go` line 21 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGLyB8EDcjTPq6jbkp:-NAGLyB8EDcjTPq6jbkq:b-lznbwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_utilization_adjuster.go#L21)):*
> ```Go
> )
> 
> var _ elasticCPUUtilizationAdjuster = &elasticCPUGranter{}
> ```

Is this interface being abstracted for testing?
Even if this is, it seems unnecessary to put this simple functionality in a separate file from `elasticCPUGranter`.
"Adjuster" suggests that this is the one making the decision based on load info, like `kvSlotAdjuster`. This is just a listener.
___
*[`pkg/util/admission/elastic_cpu_utilization_adjuster.go` line 51 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGMuIO-KZYHikkmeSe:-NAGMuIO-KZYHikkmeSf:b-daf4jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_utilization_adjuster.go#L51)):*
> ```Go
> 		float64(int64(runtime.GOMAXPROCS(0))*time.Second.Nanoseconds())
> 	return e.getTargetUtilization() *
> 		float64(int64(totalElasticCPUTime)-availableElasticCPUTime.Nanoseconds()) / totalElasticCPUTime
> ```

I didn't understand what is going on in this function. We have some math that seems to be `usedCPUTimeTokens/totalCPUTimeTokens`. Are the numerator and denominator the tokens for 1s? Then the numerator is doing a subtraction: what invariant ensures that the results in not negative? Can the first value in `a-b` be small because we just recently reduced the target utilization, but `b` be large because we still have some burst tokens accumulated?
This could use code comments and a crisper statement of invariants.
___
*[`pkg/util/admission/elastic_cpu_work_queue.go` line 56 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGP5J6BnEuPUz8JhRv:-NAGP5J6BnEuPUz8JhRw:b-4is2cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_work_queue.go#L56)):*
> ```Go
> 	}
> 	e.metrics.AcquiredNanos.Inc(duration.Nanoseconds())
> 	e.metrics.Acquisitions.Inc(1)
> ```

there is a workQueue metric for admitted count already.
___
*[`pkg/util/admission/elastic_cpu_work_queue.go` line 136 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGPP-5EtxWD0ov6-ob:-NAGPP-5EtxWD0ov6-oc:bz04at8) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_work_queue.go#L136)):*
> ```Go
> 		return true, grunning.Subtract(runningTime, h.allotted)
> 	}
> 	return false, grunning.Subtract(h.allotted, runningTime)
> ```

changing the subtraction order for the 2 cases is confusing. There should be a single meaning to what this return value means.
___
*[`pkg/util/admission/grant_coordinator.go` line 979 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGJkld82o6xNUnQF5q:-NAGJkld82o6xNUnQF5r:b-fec24p) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/grant_coordinator.go#L979)):*
> ```Go
> // SQL-level admission. All this informs why its structured as a separate grant
> // coordinator.
> type ElasticCPUGrantCoordinator struct {
> ```

I didn't expect this to see a new GrantCoordinator implementation. Even `StoreGrantCoordinators` is able to use a `GrantCoordinator` for KV write work with tokens. Using the normal implementation allows us to reuse a bunch of mediating code. In that KV write case we needed a way to break out of the abstraction at done time, which is why we "leaked" a `granterWithStoreWriteDone` to the `StoreWorkQueue`. In this elastic cpu case, I think the situation is even simpler, in that we can simply call `granter.{returnGrant,tookWithoutPermission}` at done time.

I do see why this works in the sense that you can intercept all the work in the `granter` implementation itself, and the `granter` implementation knows that it is being used in this context [...]

2022-08-25 05:25 UTC, irfansharif reviewed
Flushing out some comments, review changes, and tests. There's still more tests I need to write.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-:-NAISQerAjpgQyHAOGsN:b-o8yfhv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @sumeerbhola)

___
*[`pkg/kv/kvserver/store.go` line 3815 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAG9z2-1FixH1HFQ24k:-NAI623IABt1eAWX63gZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/kv/kvserver/store.go#L3815)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

There is also rearrangement of logic here. It looks correct to me, but this is also a part that has no existing tests (my fault).
Can you add a TODO to write a unit test for this -- there are enough cases that make me nervous. Fine to do it after the branch cut.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/store.go` line 3856 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAG9DYi9sPvFvFqqRqn:-NAI64Ek8JMbj47K8XsA:b-2in94h) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/kv/kvserver/store.go#L3856)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

does a return from this function that uses a different variable automatically populate `retErr` before the defer is run?
</blockquote></details>

Yes, and it makes code structure slightly simpler.
___
*[`pkg/kv/kvserver/kvadmissionhandle/handle.go` line 54 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAG6zUqDgCXjEQDfSCN:-NAIKxlZE5qTX-QQowdS:b-jmce8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/kv/kvserver/kvadmissionhandle/handle.go#L54)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is a memory allocation, yes?
Is this only being used plumb the ability to call `OverElasticCPULimit`? If yes, can we call this something like `ContextWithElasticCPUWorkHandle` and only do the allocation for those elastic cases. Those seem heavy weight enough for the allocation to not matter.
</blockquote></details>

Good idea, done. The context helpers now felt better placed near where ElasticCPUWorkHandle is defined (pkg/util/admission), making this kvadmissionhandle package redundant (only needed it to take on a dependency from pkg/storage). TL;DR this package is now gone and the handle type moves back to kvserver.
___
*[`pkg/storage/mvcc.go` line 5880 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGBCPTAaSwrT8bAC2p:-NAI6H1i40wPfEys3TTG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/storage/mvcc.go#L5880)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/find/fine/
</blockquote></details>

Done.
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 182 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGO64M3de7Uu9ccCSe:-NAI6s412pd8jUvsCQia:b-mam7nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_granter.go#L182)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

don't we give back the 1 token that was consumed?
</blockquote></details>

Done. Was trying to avoid introducing a variant of `returnGrant` that didn't in turn call tryGrant, but that's a bad reason.
___
*[`pkg/util/admission/elastic_cpu_utilization_adjuster.go` line 21 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGLyB8EDcjTPq6jbkp:-NAI7NqjC-QKNygFVd0M:b8qpva3) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_utilization_adjuster.go#L21)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this interface being abstracted for testing?
Even if this is, it seems unnecessary to put this simple functionality in a separate file from `elasticCPUGranter`.
"Adjuster" suggests that this is the one making the decision based on load info, like `kvSlotAdjuster`. This is just a listener.
</blockquote></details>

Moved it to elastic_cpu_granter.go. And yes, for tests that I had yet to add.
___
*[`pkg/util/admission/elastic_cpu_utilization_adjuster.go` line 51 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGMuIO-KZYHikkmeSe:-NAIOsXC6g6oTzvGFgMO:b-sbeb3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_utilization_adjuster.go#L51)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand what is going on in this function. We have some math that seems to be `usedCPUTimeTokens/totalCPUTimeTokens`. Are the numerator and denominator the tokens for 1s? Then the numerator is doing a subtraction: what invariant ensures that the results in not negative? Can the first value in `a-b` be small because we just recently reduced the target utilization, but `b` be large because we still have some burst tokens accumulated?
This could use code comments and a crisper statement of invariants.
</blockquote></details>

Since this feeds into the following TODO, I'm just going to replace it instead in my next pass (tomorrow) on this PR:
```
	// TODO(irfansharif): This setting is flawed. It can make for a very slow
	// rise (the observed utilization value is not smoothed) or be altogether
	// unreactive when operating at low elastic CPU % limits. Consider if the
	// target utilization is at 1% in an 8vCPU machine. The burst capacity of
	// the token bucket = 1% * 8s = 80ms. If we're relying on observing 90% of
	// that value being in use, i.e. 72ms to have been acquired by elastic work,
	// this is simply not possible when the smallest unit of acquisition is
	// larger, say 100ms.
	//
	// We really only want this for one reason: only increase CPU allotment if
	// there are active users of this quota that possibly benefit from a larger
	// allotment. So we could instead make this conditional on there being >= 1
	// waiters X% of time over some recent time window.
	elasticCPUGranterUtilizationFractionForAdditionalCPU = settings.RegisterFloatSetting(
		settings.SystemOnly,
		"elastic_cpu_granter.utilization_fraction_for_additional_cpu",
		"sets the minimum utilization of the current limit needed before increasing elastic CPU %",
		0.9, // 90%
	)
```
___
*[`pkg/util/admission/elastic_cpu_work_queue.go` line 56 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGP5J6BnEuPUz8JhRv:-NAI7_peBTS9yIMLGBRv:bb4gqc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_work_queue.go#L56)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

there is a workQueue metric for admitted count already.
</blockquote></details>

Removed. This was detritus from before when I wasn't using a work queue but still wanted to see admitted metrics
___
*[`pkg/util/admission/elastic_cpu_work_queue.go` line 136 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGPP-5EtxWD0ov6-ob:-NAIOUudEeF2KNKTU1n2:b-dkr6nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_work_queue.go#L136)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

changing the subtraction order for the 2 cases is confusing. There should be a single meaning to what this return value means.
</blockquote></details>

Simplified.
___
*[`pkg/util/admission/grant_coordinator.go` line 979 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGJkld82o6xNUnQF5q:-NAIPM0ABCj7lYDUhwb1:bg47xt8) ([raw [...]

2022-08-25 12:24 UTC, sumeerbhola requested changes
> Reviewed 7 of 29 files at r10, 19 of 22 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @sumeerbhola)

___
*[`pkg/util/admission/elastic_cpu_granter.go` line 127 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAJmpr1Cq2-YdhMLmUo:-NAJmpr1Cq2-YdhMLmUp:b-8eieew) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d87ea14bd62399f122a07f14092ca2ad6e86139/pkg/util/admission/elastic_cpu_granter.go#L127)):*
> ```Go
> 		0, 0,
> 		quotapool.OnWaitStart(func(ctx context.Context, poolName string, r quotapool.Request) {
> 			metrics.Waiters.Inc(1)
> ```

Nothing should be doing a blocking wait on this `RateLimiter`. The `WorkQueue` does a `tryGet` which is non-blocking. There are existing WorkQueue metrics for wait_queue_length and wait durations (cumulative sum and histogram). Also the `WorkQueue` hides who is waiting and when they started waiting from the `granter`.
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 156 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAJoKBs2-rNVKPWvlLo:-NAJoKBt3vFpK4IczB1T:bjatjqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d87ea14bd62399f122a07f14092ca2ad6e86139/pkg/util/admission/elastic_cpu_granter.go#L156)):*
> ```Go
> // tryGet implements granter.
> func (e *elasticCPUGranter) tryGet(count int64) (granted bool) {
> 	return e.rl.AdmitN(count)
> ```

This granter is slightly differing from the other ones in admission in that if the number of tokens are > 0 they will grant and let the tokens become negative. So a request will get through unless the adjustment the tokens down to 0. Not that this difference matters.

I doubt we will allow for granularities larger than 100ms, and really admission control should not allow the calling code to request more than some threshold defined by admission control, since it is the job of admission control to ensure performance isolation.
How about defining a 100ms const in admission control and make `ElasticCPUWorkQueue.Admit` cap whatever is asked for by 100ms. We already have the enforcement mechanism to change/reduce what was asked for via the handle we give back, so there is no new functionality needed there.
___
*[`pkg/util/admission/elastic_cpu_utilization_adjuster.go` line 51 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGMuIO-KZYHikkmeSe:-NAJrNqO53NQeAjdq-YO:b-qx67ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_utilization_adjuster.go#L51)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Since this feeds into the following TODO, I'm just going to replace it instead in my next pass (tomorrow) on this PR:
```
	// TODO(irfansharif): This setting is flawed. It can make for a very slow
	// rise (the observed utilization value is not smoothed) or be altogether
	// unreactive when operating at low elastic CPU % limits. Consider if the
	// target utilization is at 1% in an 8vCPU machine. The burst capacity of
	// the token bucket = 1% * 8s = 80ms. If we're relying on observing 90% of
	// that value being in use, i.e. 72ms to have been acquired by elastic work,
	// this is simply not possible when the smallest unit of acquisition is
	// larger, say 100ms.
	//
	// We really only want this for one reason: only increase CPU allotment if
	// there are active users of this quota that possibly benefit from a larger
	// allotment. So we could instead make this conditional on there being >= 1
	// waiters X% of time over some recent time window.
	elasticCPUGranterUtilizationFractionForAdditionalCPU = settings.RegisterFloatSetting(
		settings.SystemOnly,
		"elastic_cpu_granter.utilization_fraction_for_additional_cpu",
		"sets the minimum utilization of the current limit needed before increasing elastic CPU %",
		0.9, // 90%
	)
```
</blockquote></details>

If you cap a single request at 100ms (see other comment) within admission control, then this special case can be recognized by admission control as remaining tokens < 100ms, which would imply full utilization.
___
*[`pkg/util/admission/elastic_cpu_work_queue.go` line 124 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAJrwUe43WPEe6xYvw2:-NAJrwUe43WPEe6xYvw3:b-7wj91d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d87ea14bd62399f122a07f14092ca2ad6e86139/pkg/util/admission/elastic_cpu_work_queue.go#L124)):*
> ```Go
> // OverLimit is used to check whether we're over the allotted elastic CPU
> // tokens. It also returns the time difference between how long we ran for and
> // what was allotted. Integrated callers are expected to invoke this in tight
> ```

how about:
... what was allotted (so difference will be negative if the running duration is less than what was allotted).
___
*[`pkg/util/admission/grant_coordinator.go` line 979 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGJkld82o6xNUnQF5q:-NAJsetG7BqYJXcgVzuL:b-3n5k8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/grant_coordinator.go#L979)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I first tried reusing the existing GrantCoordinator but the code got too confusing and littered with edge cases. Consider: - grant chains (don't apply here), or 
- the use of `tryGrant()` (we only want to "grant forwarding" for a given work class and work kind", and not all APIs on the GrantCoordinator consider both. 
Perhaps these are the creaking aspects you're talking about which made it feel easier to copy paste this mediation code. I'm also wondering whether we need to re-use this one concrete type as opposed to a grantCoordinator interface. But I also don't clearly see how to pull out such an interface. Added a TODO.
</blockquote></details>

Something like:
```
	coord := &GrantCoordinator{
		settings:       st,
		useGrantChains: false,
		numProcs:       1,
	}
        coord.queues[KVWork] = workQueue
        coord.granters[KVWork] = elasticCPUGranter
```
should just work for the current setup.
You will just have to make `elasticCPUGranter` implement `granterWithLockedCalls` which adds the *Locked() functions where the current logic will shift too.

As I said earlier, you don't have to make this change.
___
*[`pkg/util/goschedstats/latency.go` line 83 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGElsQERodOtScAi4J:-NAJweJt-4S4_sku1KkV:b-lnynyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/goschedstats/latency.go#L83)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

To make tests that register their own listeners (just added one) be able to clean up after themselves. Imagine two tests that independently need to add such listeners and are run concurrently. I actually cargo culted ~a lot~ all of this from the RunnableCountCallback variant in this package BTW, so possibly it's too much for this listener since I'm doing no smoothing, fixed-point arithmetic, or dynamic changing of sampling periods. But I'll keep this as is unless you feel differently.
</blockquote></details>

`schedulerLatencyCallbackWithID` has an id for each callback. I was asking about the id in here. Clearly it needs a code comment.
___
*[`pkg/util/grunning/grunning.go` line 30 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAJu1BE8uaIXKj4JU08:-NAJu1BE8uaIXKj4JU09:bwlk4gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d87ea14bd62399f122a07f14092ca2ad6e86139/pkg/util/grunning/grunning.go#L30)):*
> ```Go
> 	diff := a.Nanoseconds() - b.Nanoseconds()
> 	if diff < 0 {
> 		diff = -diff
> ```

this seems to have the same issue in that takes a [...]

2022-08-30 15:56 UTC, irfansharif reviewed
I addressed all comments; the post-review changes are in the last commit. Added a bunch of microbenchmarks, tests, etc. and went over it live with @andrewbaptist (the last commit message spells out all the changes). I wanted to merge this PR now given @sumeerbhola's last pass but I’ve been asked to wait until he's back from PTO next week (i.e. unless @andrewbaptist feels comfortable reviewing before then). I've already caught 2-3 merge skews with Erik's work and changes in the vendor directory so I'd prefer getting this in sooner than not.

+cc @bananabrick; this PR provides the building blocks for replacing our use of soft/moderate slots. It also integrates into export requests so you have a frame reference. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-:-NAjRjaS5ELIX0hzyZDJ:bh77s44)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @sumeerbhola)

___
*[`pkg/util/admission/elastic_cpu_granter.go` line 127 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAJmpr1Cq2-YdhMLmUo:-NAjLx043nHXJqhtG16u:bg6ekrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d87ea14bd62399f122a07f14092ca2ad6e86139/pkg/util/admission/elastic_cpu_granter.go#L127)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Nothing should be doing a blocking wait on this `RateLimiter`. The `WorkQueue` does a `tryGet` which is non-blocking. There are existing WorkQueue metrics for wait_queue_length and wait durations (cumulative sum and histogram). Also the `WorkQueue` hides who is waiting and when they started waiting from the `granter`.
</blockquote></details>

Removed these metrics in favor of the requester/WorkQueue side ones.
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 156 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAJoKBs2-rNVKPWvlLo:-NAjMpSMEFMF813TazhZ:buea87l) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d87ea14bd62399f122a07f14092ca2ad6e86139/pkg/util/admission/elastic_cpu_granter.go#L156)):*
> How about defining a 100ms const in admission control and make ElasticCPUWorkQueue.Admit cap whatever is asked for by 100ms. 

Done, this makes sense. I also cluster-settings-ified how many tokens are handed out to export requests at the admission gate (subject to bounds defined by admission control of course, and also added validation around the cluster setting itself).

Added a comment about the fact that the tokens are allowed to go into debt. There are also tests around the granter type that walk through this phenomenon. 
___
*[`pkg/util/admission/elastic_cpu_utilization_adjuster.go` line 51 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGMuIO-KZYHikkmeSe:-NAjM3Za4awnN3Sy3AIa:b-5nw0i4) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/elastic_cpu_utilization_adjuster.go#L51)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If you cap a single request at 100ms (see other comment) within admission control, then this special case can be recognized by admission control as remaining tokens < 100ms, which would imply full utilization.
</blockquote></details>

Added a comment. I'll rip out elasticCPUGranterUtilizationFractionForAdditionalCPU in a future PR since this is already large. Cleaned up and added comments for the CPU token math to get current utilization numbers; added some better invariants, safeguards and tests.
___
*[`pkg/util/admission/elastic_cpu_work_queue.go` line 124 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAJrwUe43WPEe6xYvw2:-NAjMPRZ1cq0dHHxDJO7:b-h21xxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d87ea14bd62399f122a07f14092ca2ad6e86139/pkg/util/admission/elastic_cpu_work_queue.go#L124)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about:
... what was allotted (so difference will be negative if the running duration is less than what was allotted).
</blockquote></details>

Removed the possibility of negative differences, it's now an absolute term.
___
*[`pkg/util/admission/grant_coordinator.go` line 979 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGJkld82o6xNUnQF5q:-NAjMVMj3qMR0Bp0ztQR:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/admission/grant_coordinator.go#L979)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Something like:
```
	coord := &GrantCoordinator{
		settings:       st,
		useGrantChains: false,
		numProcs:       1,
	}
        coord.queues[KVWork] = workQueue
        coord.granters[KVWork] = elasticCPUGranter
```
should just work for the current setup.
You will just have to make `elasticCPUGranter` implement `granterWithLockedCalls` which adds the *Locked() functions where the current logic will shift too.

As I said earlier, you don't have to make this change.



</blockquote></details>

Ack.
___
*[`pkg/util/goschedstats/latency.go` line 83 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAGElsQERodOtScAi4J:-NAjMYVHDKm2rJXGLb-c:bmloqo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/213ec015db428d22a87d2308a4a8fe6e6137c99e/pkg/util/goschedstats/latency.go#L83)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`schedulerLatencyCallbackWithID` has an id for each callback. I was asking about the id in here. Clearly it needs a code comment.
</blockquote></details>

Added commentary and tests.
___
*[`pkg/util/grunning/grunning.go` line 30 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAJu1BE8uaIXKj4JU08:-NAjMabV2cw-klW_zXfV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d87ea14bd62399f122a07f14092ca2ad6e86139/pkg/util/grunning/grunning.go#L30)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this seems to have the same issue in that takes an absolute value but doesn't tell us in the function comment that that is what it is doing
</blockquote></details>

Done.
___
*[`pkg/util/quotapool/int_rate.go` line 101 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NAJuuQ997y9UhsUq7yc:-NAjMkvn6OABGun1c7xL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d87ea14bd62399f122a07f14092ca2ad6e86139/pkg/util/quotapool/int_rate.go#L101)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

needs new unit tests
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-31 00:07 UTC, irfansharif commented
This [snapshot](https://snapshots.raintank.io/dashboard/snapshot/GKujzvEMIN9XZdK2ygr1zENFsd0ClEM4?orgId=2) shows this PR in action. I'm running stock TPC-C using the following:

```
set CLUSTER irfansharif-export
roachprod create -n 4 --gce-machine-type=n2-standard-8 $CLUSTER -l 24h
roachprod sync # fight annoying resolution issues
roachprod stop $CLUSTER:1-3
roachprod put $CLUSTER:1-4 ./cockroach ./cockroach 
roachprod start $CLUSTER:1-3
roachprod sql $CLUSTER:1 -- -e "SET CLUSTER SETTING cluster.organization = 'Cockroach Labs - Production Testing';"
roachprod sql $CLUSTER:1 -- -e "SET CLUSTER SETTING enterprise.license = 'nice-try';"
roachprod run $CLUSTER:1 -- ./cockroach workload fixtures import tpcc --warehouses=1000 --checks=false # takes ~6m
roachprod sql $CLUSTER:1 -- -e "CREATE SCHEDULE FOR BACKUP INTO 'gs://<public-bucket>/$CLUSTER-22?AUTH=implicit' RECURRING '*/12 * * * *' FULL BACKUP ALWAYS;"
```

```
roachprod run $CLUSTER:4 -- ./cockroach workload run tpcc --warehouses=1000 --max-rate=450 --conns 90 --tolerate-errors (roachprod pgurl $CLUSTER:1-3) 
```

The two red annotations are where we disable and enable this controller respectively (`set cluster setting admission.elastic_cpu.enabled = {false,true};`). We see that in the middle portion, when disabled:
- p99 latency is upwards of 100ms
- aggregate CPU utilization is pushed up to 93%
- full backups take 10m

When enabled enabled:
- p99 latency is closer to 22ms
- aggregate CPU utilization is kept at a steady 70%
- full backups take 30m

<img width="1686" alt="image" src="https://user-images.githubusercontent.com/10536690/187564082-c485493c-b2e1-43ff-8265-968b22ab0ad9.png">

2022-09-06 22:01 UTC, sumeerbhola requested changes
flushing some comments. There is a lot I haven't read yet.

> Reviewed 2 of 29 files at r14, 17 of 50 files at r15, 2 of 13 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-:-NBJoTem0LMXp3dMVr-0:bg5ke49)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @sumeerbhola)

___
*[`-- commits` line 98 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJTT5P-AxY6yLalecq):*
I don't quite understand either of these graphs. What are the X and Y axes?
___
*[`-- commits` line 152 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJUA-t9YgLVnE-dhrY):*
s/give//
___
*[`pkg/kv/kvserver/store.go` line 3894 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJUgar8j3_83XNYJgS:-NBJUgar8j3_83XNYJgT:b-faeogk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/kv/kvserver/store.go#L3894)):*
> ```Go
> 			// the same machine.
> 			elasticWorkHandle, err := n.elasticCPUWorkQueue.Admit(
> 				ctx, admission.ElasticCPUDurationPerExportRequest.Get(&n.settings.SV), admissionInfo,
> ```

It is odd that the caller is fetching this cluster setting that is defined inside the admission package.
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 88 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJZc-Y8mY7zR-42qAZ:-NBJZc-Y8mY7zR-42qA_:b6b4ebo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_granter.go#L88)):*
> ```Go
> 	elasticCPUGranterInjectedTargetUtilization = settings.RegisterFloatSetting(
> 		settings.SystemOnly,
> 		"admission.elastic_cpu.reset_target_utilization",
> ```

This cluster setting seems odd to me. It is being used to reset something that has been auto-adjusted, which will then again get auto-adjusted. How will that be useful to a system operator? It seems better to define upper and lower bounds on the target utilization.

Also, this granter is not the decision maker on what the current auto-adjusted utilization should be. That happens in `schedulerLatencyListener`. So it is odd that this setting is defined here and used here. I suggest moving the upper and lower bounds to the decision making component who would read it every time it is going to make an adjustment and not use `SetOnChange`.
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 196 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJbYAG55VnlDjTCynO:-NBJbYAH3nbDdIAXx5Ev:b-egw3u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_granter.go#L196)):*
> ```Go
> // tryGrant is used to attempt to grant to waiting requests.
> func (e *elasticCPUGranter) tryGrant() {
> 	if e.requester.hasWaitingRequests() && e.tryGet(1) {
> ```

Note how `GrantCoordinator.tryGrant` loops and grants until there are no more waiting requests or tokens/slots are exhausted. We need a loop here too. I wonder why this is not showing up as a problem in experiments. 
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 243 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJdTZO63GkQGXtfNvt:-NBJdTZO63GkQGXtfNvu:b-dju6is) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_granter.go#L243)):*
> ```Go
> 	// and burst tokens).
> 	totalCPUTimeNanos := int64(runtime.GOMAXPROCS(0)) * time.Second.Nanoseconds()
> 	_, availableElasticCPUTime, totalElasticCPUTime := e.rl.Parameters()
> ```

This needs another code comment stating that the burst and the rate limit are the same. Otherwise it is unclear why we are using the burst as `totalElasticCPUTime` per second.
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 269 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJf1Py16QSQE_Dd_IC:-NBJf1Py16QSQE_Dd_ID:b-436x80) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_granter.go#L269)):*
> ```Go
> 		}
> 	}
> 	return float64(inUseElasticCPUTimeNanos) / float64(totalCPUTimeNanos)
> ```

I don't quite understand this calculation. The denominator is clear -- it is the total cpu-nanos available to this Go process. The numerator is the (burst-available) tokens, which seems to be some measure of what is used, but it isn't clear that it really is. If the burst size is 100, and setUtilizationLimit has just been called, available will also be 100, yes? If 100ms have elapsed since the call to setUtilizationLimit and 10 tokens have been used, we will also have replenished those, so (burst-available) will still be 0. In general, if there is no real burst and tokens are being consumed at exactly the rate limit, (burst-available) will always be 0.
What am I missing?
___
*[`pkg/util/admission/elastic_cpu_work_queue.go` line 39 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJjyeZ2UWO5gJvAsJc:-NBJjye_7APkHrrCNan-:b6icku1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_work_queue.go#L39)):*
> ```Go
> 	ElasticCPUDurationPerExportRequest = settings.RegisterDurationSetting(
> 		settings.SystemOnly,
> 		"admission.elastic_cpu.duration_per_export_request",
> ```

Does this cluster setting need to be for ExportRequest only? I realize we've only experimented and integrated with ExportRequest, but it seems preferable to define this as `admission.elastic_cpu.duration_per_request`.
Oh, I see this is used by the callee, and has nothing to do with the max/min. I think this should move out of the admission package.
___
*[`pkg/util/admission/grant_coordinator.go` line 1012 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJm_bMAjzdQLszk8Es:-NBJm_bMAjzdQLszk8Et:b-fuso8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/grant_coordinator.go#L1012)):*
> ```Go
> 
> // tryGrant is used to attempt to grant to waiting requests.
> func (e *ElasticCPUGrantCoordinator) tryGrant() {
> ```

Is schedulerLatencyListener the only caller of this?
___
*[`pkg/util/grunning/disabled_test.go` line 28 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJnuM1BP9LXTKo6jqB:-NBJnuM1BP9LXTKo6jqC:b-y149zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/grunning/disabled_test.go#L28)):*
> ```Go
> 	require.False(t, grunning.Supported())
> 	require.Zero(t, grunning.Time())
> 	require.Zero(t, grunning.Difference(grunning.Time(), grunning.Time()))
> ```

is this the only caller of `Difference`?
___
*[`pkg/util/quotapool/int_rate.go` line 102 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJd3Ft7j3d2z_s4qV4:-NBJd3Ft7j3d2z_s4qV5:bxdj2e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/quotapool/int_rate.go#L102)):*
> ```Go
> 
> // Parameters returns the refill rate, number of available and burst tokens.
> func (rl *RateLimiter) Parameters() (rate Limit, available, burst Tokens) {
> ```

rate and burst are configured and available is what is currently available, yes?
If so, I'd suggest reordering as (rate, burst, available) and clarifying this in a code comment.
Also, presumably the invariant is available <= burst.


<!-- Sent from Reviewable.io -->

2022-09-07 11:33 UTC, sumeerbhola requested changes
Remaining stuff to to read: schedulerlatency package, and all the new unit tests.

> Reviewed 3 of 29 files at r14, 6 of 50 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-:-NBMiM_46ZdxHb0LUs1E:b-s3ti4i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @sumeerbhola)

___
*[`pkg/util/admission/elastic_cpu_work_handle.go` line 26 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJrUDF7weFUlNHUCDb:-NBJrUDG4p7j3wzVTugj:bzablnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_work_handle.go#L26)):*
> ```Go
> 	cpuStart, allotted               time.Duration
> 	itersSinceCheck, itersUntilCheck int
> 	lastCheck, lastDifference        time.Duration
> ```

All these variables could use code comments. In particular it isn't obvious what quantities are from the beginning of this goroutine, which are from the beginning of this request, and which are differences between what is allotted and what has been consumed. Since all of these quantities use `time.Duration` it can be a bit confusing for a future reader who is trying to quickly understand what is going on.
___
*[`pkg/util/admission/scheduler_latency_listener.go` line 33 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBMcviv-wDjY7TMnYiJ:-NBMcviv-wDjY7TMnYiK:b-5q1hcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/scheduler_latency_listener.go#L33)):*
> ```Go
> 	ctx                context.Context
> 	ewmaP99            float64
> 	elasticCPUAdjuster elasticCPUUtilizationAdjuster
> ```

"Adjuster" somehow suggests to me that it decides the cpu utilization, which it does not. How about s/Adjuster/Enforcer/ since it is enforcing what it is told to do,
___
*[`pkg/util/admission/scheduler_latency_listener.go` line 48 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBMdLlB7YwwNilgRTrm:-NBMdLlB7YwwNilgRTrn:bwe9851) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/scheduler_latency_listener.go#L48)):*
> ```Go
> ) *schedulerLatencyListener {
> 	ctx := ambientCtx.AnnotateCtx(context.Background())
> 	ctx = logtags.AddTag(ctx, "scheduler-latency-listener", "")
> ```

what is the purpose of this additional tag?
___
*[`pkg/util/admission/scheduler_latency_listener.go` line 75 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBMdsw_AxebSzFZSJnK:-NBMdsw_AxebSzFZSJnL:b-ehupc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/scheduler_latency_listener.go#L75)):*
> ```Go
> //
> // Where the input parameters are:
> // - scheduler_latency_sample_period: Inverse of how frequently the CPU
> ```

This "Inverse of how frequently ... " is needlessly convoluted, in terms of defining period in terms of frequency. We can just say "Period at which the CPU scheduler's ...".
___
*[`pkg/util/admission/scheduler_latency_listener.go` line 81 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBMeGIy7UjjVK5HA8TD:-NBMeGIy7UjjVK5HA8TE:b-9n89vv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/scheduler_latency_listener.go#L81)):*
> ```Go
> // - ewma_c: Recency bias for EWMA smoothing of scheduling_p99.
> // - target_p99: Target p99 scheduling latency.
> // - observed_cpu_utilization: Observed CPU % attributed to elastic work.
> ```

can you rename this to observed_elastic_cpu_utilization.
___
*[`pkg/util/admission/scheduler_latency_listener.go` line 86 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBMeYI43U-V7UfU16jT:-NBMeYI43U-V7UfU16jU:bkfyx2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/scheduler_latency_listener.go#L86)):*
> ```Go
> // - delta: Additive adjustment of CPU %.
> // - factor: Multiplicative factor for delta, used when decreasing utilization
> // - min_utilization_fraction: Minimum utilization of CPU limit before raising
> ```

min_elastic_utilization_fraction: Minimum utilization of elastic CPU limit ...
___
*[`pkg/util/admission/scheduler_latency_listener.go` line 103 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBMh52hAhBVSeTFMX5i:-NBMh52hAhBVSeTFMX5j:bgoqnh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/scheduler_latency_listener.go#L103)):*
> ```Go
> 
> 	// TODO(irfansharif): Does utilization need to be smoothed
> 	// out? Ripped out entirely?
> ```

I don't understand this TODO.
___
*[`pkg/util/admission/scheduler_latency_listener.go` line 186 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBMfM7dB4fDXtC4tLND:-NBMfM7dB4fDXtC4tLNE:b-k549b1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/scheduler_latency_listener.go#L186)):*
> ```Go
> }
> 
> var ( // cluster settings to control how elastic CPU granter is adjusted
> ```

These settings are fine to start with, but no one wants settings once this mechanism is mature. For instance, the 25% max is too conservative and if we can react quickly to arrival of regular work we would want to have the default be very high.
Meanwhile, should we be marking these with Reserved visibility to convey that users should not change these without consultation with us?
___
*[`pkg/util/admission/scheduler_latency_listener.go` line 229 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBMg_JS-0D-nk6yjIpA:-NBMg_JS-0D-nk6yjIpB:b-yhpova) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/scheduler_latency_listener.go#L229)):*
> ```Go
> 	// value being in use, i.e. 72ms to have been acquired by elastic work, this
> 	// is simply not possible when the smallest unit of acquisition is larger,
> 	// say 100ms. (We can check for this explicitly since we know what the
> ```

Do we now check for this explicitly? I see we don't. Please fix that.
Once fixed, I don't think this setting is necessarily flawed -- there is just one corner case to additionally check.

The "So we could instead make this conditional ..." is too complicated IMO.


<!-- Sent from Reviewable.io -->

2022-09-07 15:26 UTC, sumeerbhola requested changes
> Reviewed 2 of 50 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @sumeerbhola)

___
*[`pkg/util/schedulerlatency/sampler.go` line 30 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBNR3tM8I7D5yYXwMLL:-NBNR3tM8I7D5yYXwMLM:b75h8ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/schedulerlatency/sampler.go#L30)):*
> ```Go
> //
> // TODO(irfansharif): What's the right frequency? Does it need to be adjusted
> // during periods of high/low load? This needs to be relatively high to drive
> ```

Does the frequency need to be high or the period? Since the setting is a period, I would suggest phrasing the whole comment in terms of period and high and low values of that period.
Also, I don't understand the "to drive ... within the prescribed limit" and the "we only check requests ..." part.
Is the issue here there is no explicit ticking mechanism in the `RateLimiter` or `TokenBucket` and that it replenishes based on the time at which the request asks for a token, and since we channel all such requesting through the `WorkQueue` which does non-blocking waits via `tryGet` we do need an explicit ticking mechanism that will realize that tokens are no longer zero and will do a `requester.granted` call?
If so, I wonder whether this `RateLimiter` reuse is worth it -- it makes the code more opaque and we are not using most of the functionality. What if we just used `TokenBucket` directly and added some sort of explicit ticking. We have this need for fine-granularity explicit ticking for the IO tokens too, where the 250ms granularity is too coarse. Ideally a 1ms granularity would be good. We have had problems with that in unloaded systems, as you can see with the `samplePeriod{Short,Long}` logic goschedstats. Maybe we can generalize that period switching into a struct where the coarser period is used only when some func indicates that the relevant "resource" is underloaded -- for goschedstats this resource is the CPU, and for these token buckets it will be based on how many tokens are still available.
___
*[`pkg/util/schedulerlatency/sampler.go` line 125 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBNVIlUDAW9WjZIjMwE:-NBNVIlUDAW9WjZIjMwF:b-w7o1q0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/schedulerlatency/sampler.go#L125)):*
> ```Go
> 	s.mu.Lock()
> 	s.mu.ringBuffer.Discard()
> 	numSamples := int(duration / period)
> ```

this reads a bit odd. If duration == period, we only need to store one sample, and do a diff with the one we are about to throw away.
If duration=2*period, we should store 2 and still do the diff with the one we are about to throw away. But with this logic in the latter case we will store 2 and do the diff with the one stored period before. So the logic here seems to be off-by-one.
___
*[`pkg/util/schedulerlatency/sampler.go` line 145 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBNWEAt7XzE_D2u1DUK:-NBNWEAt7XzE_D2u1DUL:b-wrqaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/schedulerlatency/sampler.go#L145)):*
> ```Go
> 
> 	globallyRegisteredCallbacks.mu.Lock()
> 	cbs := globallyRegisteredCallbacks.mu.callbacks
> ```

How can we use cbs without a mutex? I see we only append to it and removal makes a new copy, but we will still be non-atomically reading the length below, which seems wrong.
___
*[`pkg/util/schedulerlatency/sampler.go` line 242 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBNXpy9BRtdpRy7Ax0v:-NBNXpy9BRtdpRy7Ax0w:bcqp3vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/schedulerlatency/sampler.go#L242)):*
> ```Go
> 		min, max = h.Buckets[i], h.Buckets[i+1]
> 		cumulative += h.Counts[i]
> 		if p == 1.0 {
> ```

So for this special case of p == 1.0, we are not doing linear interpolation and reporting (min+max)/2? Is there a principle behind this choice?
I think we need a code comment explaining the semantics of this percentile calculation.
Also, I don't think we should simply ignore the -inf and +inf buckets. We can say we will use max=min for the +inf bucket and min=max for the -inf bucket since it is more precise than ignoring them. And if there is a single [-inf,+inf) bucket ehn the result will be 0 since there is no information in this histogram.


<!-- Sent from Reviewable.io -->

2022-09-09 07:11 UTC, irfansharif reviewed
PTAL, appended a single commit with all the changes. I've moved away from using utilization data in the control loop itself and instead now use data about whether there are requests waiting as an indicator that there's benefit to raising the utilization limit (and ran validation experiments, etc.) I've also added a "decay" parameter to not settle at a high limit after elastic work dies down. Doing so can result in short bursts of over admission if the CPU demand of foreground workload on the given node has increased since the last backup. The decay parameter settles somewhere between min and max; if set to zero it settles at min. I'm ok with that being made the default, right now it's at 10% of the way between min and max and decays relatively slowly (I'm also ok speeding it up).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-:-NBW3QCi7TU338Ii4Cm_:bams3ps)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @sumeerbhola)

___
*[`-- commits` line 98 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJTT5P-AxY6yLalecq):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't quite understand either of these graphs. What are the X and Y axes?
</blockquote></details>

X-axis is time, Y-axis in the first graph is the latency value and in the second graph, the CPU %. In the second graph there are two plots -- one for the limit, one for the (simulated) utilization itself. This is a bit better explained in the test file itself and the corresponding datadriven test code.
___
*[`-- commits` line 152 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJUA-t9YgLVnE-dhrY):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/give//
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/store.go` line 3894 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJUgar8j3_83XNYJgS:-NBVJoIJEh84tAE2aIbU:bomktib) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/kv/kvserver/store.go#L3894)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It is odd that the caller is fetching this cluster setting that is defined inside the admission package.
</blockquote></details>

Moved it into kvserver.
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 88 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJZc-Y8mY7zR-42qAZ:-NBVKOup6fRZKjx8JkmF:bigd3yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_granter.go#L88)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This cluster setting seems odd to me. It is being used to reset something that has been auto-adjusted, which will then again get auto-adjusted. How will that be useful to a system operator? It seems better to define upper and lower bounds on the target utilization.

Also, this granter is not the decision maker on what the current auto-adjusted utilization should be. That happens in `schedulerLatencyListener`. So it is odd that this setting is defined here and used here. I suggest moving the upper and lower bounds to the decision making component who would read it every time it is going to make an adjustment and not use `SetOnChange`.
</blockquote></details>

Removed this setting. I was using it during experiments to "inject" a utilization point to see how the controller behaves, but that's not useful for operators. I figured it may come in handy in escalations but meh. There are upper/lower bounds defined elsewhere in this package -- admission.elastic_cpu.{min,max}_utilization.
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 196 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJbYAG55VnlDjTCynO:-NBVLd2JD3pqys7bgGl2:b-eqhubg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_granter.go#L196)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Note how `GrantCoordinator.tryGrant` loops and grants until there are no more waiting requests or tokens/slots are exhausted. We need a loop here too. I wonder why this is not showing up as a problem in experiments. 
</blockquote></details>

Heh, it did show up as a problem. I'd noticed that loop and copied it here as part of https://github.com/cockroachdb/cockroach/pull/87429, but I've now pulled that into this PR instead.
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 243 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJdTZO63GkQGXtfNvt:-NBVLrLABZvyclrqDMGt:bgl591a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_granter.go#L243)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This needs another code comment stating that the burst and the rate limit are the same. Otherwise it is unclear why we are using the burst as `totalElasticCPUTime` per second.
</blockquote></details>

All this code was removed. I simplified the controller to not need to consider actual utilization; just adjust based on whatever the limit is instead and whether there are requests waiting. The appended commit message spells out some problems with the old approach. 
___
*[`pkg/util/admission/elastic_cpu_granter.go` line 269 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJf1Py16QSQE_Dd_IC:-NBVMxmh7erK2Pnxj9Gj:b-ourhwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_granter.go#L269)):*
All this code was removed.

> If the burst size is 100, and setUtilizationLimit has just been called, available will also be 100, yes?

No. If the token bucket's burst size was reduced from 100 to 50, we'll deduct 50 from the available tokens, not just reset it back to 100. 

> If 100ms have elapsed since the call to setUtilizationLimit and 10 tokens have been used, we will also have replenished those, so (burst-available) will still be 0. 

Yes. In that case the measurement obtained through this burst-available calculation says that there's 0% utilization, which is "true" at that instant in time, though like you've correctly noticed, we're missing the fact that there was non-zero utilization between measurements. This was one of the problems of using this approach and why I ripped it out entirely. Before ripping it out I tried another version that considered the windowed utilization by measuring "running time in interval - returned time in interval / total cpu time in interval" that avoided these pitfalls.
___
*[`pkg/util/admission/elastic_cpu_work_handle.go` line 26 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJrUDF7weFUlNHUCDb:-NBVWBuWBzgE_Q692wYe:b-277h9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_work_handle.go#L26)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

All these variables could use code comments. In particular it isn't obvious what quantities are from the beginning of this goroutine, which are from the beginning of this request, and which are differences between what is allotted and what has been consumed. Since all of these quantities use `time.Duration` it can be a bit confusing for a future reader who is trying to quickly understand what is going on.
</blockquote></details>

Added comments.
___
*[`pkg/util/admission/elastic_cpu_work_queue.go` line 39 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBJjyeZ2UWO5gJvAsJc:-NBVP0uL-9GoFbmDo6pp:bw132kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d4ae5cfd1c1a35ab0df53bad40fdaa790f57573/pkg/util/admission/elastic_cpu_work_queue.go#L39) [...]

2022-09-09 21:17 UTC, sumeerbhola requested changes
This is getting close to the finish line. But I still have the tests to work through. 

> Reviewed 3 of 29 files at r19, 24 of 50 files at r20, 9 of 28 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-:-NBZ6BWi5iPvDd8Qyu8m:bej141d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @sumeerbhola)

___
*[`pkg/util/admission/scheduler_latency_listener.go` line 113 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBZ4lloEsW-Y3jV16sI:-NBZ4lloEsW-Y3jV16sJ:b-mo4qvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e14c6d0c152e9798542138e6bf83e633034f12a1/pkg/util/admission/scheduler_latency_listener.go#L113)):*
> ```Go
> 	e.metrics.P99SchedulerLatency.Update(p99.Nanoseconds())
> 
> 	hasWaitingRequests := e.elasticCPULimiter.hasWaitingRequests()
> ```

I'm not convinced about this change to use an instantaneous queue empty signal. We should be increasing the elastic cpu (if possible) even at 90% utilization. Also the utilization value is a useful number to export in a metric. And if we have the utilization we can also do a more judicious decrease e.g. decrease if utilization/limit is < 50%, by doing (limit+utilization)/2, instead of introducing more knobs on the step size of decrease.
Tracking the utilization is not hard in the limiter. It can have a counter for tokens allocated that is added to and subtracted from (when returned) and is forced to stay >= 0. Then it can introduce a GetDeltaTokensAllocatedAndReset() method that returns that int64, and the caller can use the previous time.Time and the current time to compute the utilization etc.
___
*[`pkg/util/quotapool/int_rate.go` line 101 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBZ3mpDA--oqT7ahrPI:-NBZ3mpDA--oqT7ahrPJ:btrmi8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e14c6d0c152e9798542138e6bf83e633034f12a1/pkg/util/quotapool/int_rate.go#L101)):*
> ```Go
> }
> 
> // Adjust returns tokens to the bucket (positive delta) or accounts for a debt
> ```

Can all the changes in this file be reverted since the code now directly uses TokenBucket?


<!-- Sent from Reviewable.io -->

2022-09-09 22:14 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @sumeerbhola)

___
*[`pkg/util/admission/scheduler_latency_listener.go` line 113 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBZ4lloEsW-Y3jV16sI:-NBZGUWSDFFzKO-W9pof:bep3dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e14c6d0c152e9798542138e6bf83e633034f12a1/pkg/util/admission/scheduler_latency_listener.go#L113)):*
The utilization value can still be computed in a metric, though not through CRDB directly (I can improve that in a follow up). In prometheus you can define an expression to do (acquired_nanos - returned_nanos) / max_available_nanos to get the utilization value -- this is what I've been using in experiments.

> introduce a GetDeltaTokensAllocatedAndReset() method that returns that int64, and the caller can use the previous time.Time and the current time to compute the utilization etc.

I tried this exact thing BTW, from another comment thread:

> Before ripping it out I tried another version that considered the windowed utilization by measuring "running time in interval - returned time in interval / total cpu time in interval"

That also worked, though I still find this instantaneous check simpler to reason about + it makes for a faster rise when operating near lower limits. The following snippet demonstrates this with some commentary:

![image.png](https://files.reviewableusercontent.io/images/reviewable/10536690/-IIUHLzsRs1G20TJqrk44qEJ/image.png)

This is something I also observed experimentally even with the 90% parameter which also in part motivated this change. Both these forms of controls work fine in experiments, and I'm happy to revert back to this `min-util-fraction` form, but I prefer to do it in a follow up PR since it entails rewriting some tests and re-running experiments for sanity checking (this would've been faster had I packaged things up as roachtests and/or kept the other SHA around). 
___
*[`pkg/util/quotapool/int_rate.go` line 101 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBZ3mpDA--oqT7ahrPI:-NBZGRRB1BufviArVWcm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e14c6d0c152e9798542138e6bf83e633034f12a1/pkg/util/quotapool/int_rate.go#L101)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can all the changes in this file be reverted since the code now directly uses TokenBucket?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-09 22:53 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @sumeerbhola)

___
*[`pkg/util/admission/scheduler_latency_listener.go` line 113 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBZ4lloEsW-Y3jV16sI:-NBZQrbuDpaQfYPneL9K:b-q6wr2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e14c6d0c152e9798542138e6bf83e633034f12a1/pkg/util/admission/scheduler_latency_listener.go#L113)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

The utilization value can still be computed in a metric, though not through CRDB directly (I can improve that in a follow up). In prometheus you can define an expression to do (acquired_nanos - returned_nanos) / max_available_nanos to get the utilization value -- this is what I've been using in experiments.

> introduce a GetDeltaTokensAllocatedAndReset() method that returns that int64, and the caller can use the previous time.Time and the current time to compute the utilization etc.

I tried this exact thing BTW, from another comment thread:

> Before ripping it out I tried another version that considered the windowed utilization by measuring "running time in interval - returned time in interval / total cpu time in interval"

That also worked, though I still find this instantaneous check simpler to reason about + it makes for a faster rise when operating near lower limits. The following snippet demonstrates this with some commentary:

![image.png](https://files.reviewableusercontent.io/images/reviewable/10536690/-IIUHLzsRs1G20TJqrk44qEJ/image.png)

This is something I also observed experimentally even with the 90% parameter which also in part motivated this change. Both these forms of controls work fine in experiments, and I'm happy to revert back to this `min-util-fraction` form, but I prefer to do it in a follow up PR since it entails rewriting some tests and re-running experiments for sanity checking (this would've been faster had I packaged things up as roachtests and/or kept the other SHA around). 
</blockquote></details>

One other thing: the code is a bit more involved with maintaining measured utilization. It's too instantaneous/jagged if the utilization measurement is just across sample points (100ms), you want a larger, rolling window of time over which you measure utilization over -- needing something similar to the ring buffer we maintain for latency histogram samples. If that window was too long (5+s) the controller was a bit laggy, too short and the measurements were not good. Making it a cluster setting also meant resizing the buffer when it or the controller tick period changed, alternatively recording timestamps with each sample which increased memory usage slightly. These are all minor quibbles and doable, but I found this `has-waiting-requests` form to be as effective experimentally and simpler code-wise.


<!-- Sent from Reviewable.io -->

2022-09-12 21:49 UTC, irfansharif commented
(Gentle bump.)

2022-09-12 23:16 UTC, sumeerbhola requested changes
> Reviewed 2 of 29 files at r19, 1 of 50 files at r20, 7 of 28 files at r21, 3 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @sumeerbhola)

___
*[`pkg/util/admission/elastic_cpu_work_queue_test.go` line 137 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBnbvBm1cxbo5VBsdq1:-NBnbvBm1cxbo5VBsdq2:bn7hvmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/elastic_cpu_work_queue_test.go#L137)):*
> ```Go
> }
> 
> func (t *testElasticCPUGranter) tryGet(count int64) (granted bool) {
> ```

how can this test code avoid implementing `tryGet`. The `WorkQueue` will call `tryGet` if the queue is empty and a new piece of work arrives.
Is this because the work queue implementation is also abstracted out using the `elasticCPUInternalWorkQueue` interface and the test implementation below is not doing much?
___
*[`pkg/util/admission/scheduler_latency_listener_test.go` line 48 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBnvcUb8KYVYGTmf9Gk:-NBnvcUb8KYVYGTmf9Gl:bqmq8sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/scheduler_latency_listener_test.go#L48)):*
> ```Go
> //     ....
> //     Invoke the listener with the specified p99 latency a specific number of
> //     times (default = 1). Optionally control the utilization fraction (of the
> ```

does the utilization fraction change by this quantity on every tick? Is there a way to specify a constant fraction?
And why is this utilization fraction relevant any more given that you are using queue empty as the signal?
___
*[`pkg/util/admission/scheduler_latency_listener_test.go` line 58 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBnxIQYElR2B_G_SfHW:-NBnxIQYElR2B_G_SfHX:bso2hdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/scheduler_latency_listener_test.go#L58)):*
> ```Go
> //     observed utilization).
> //
> //   - "auto" ticks=<int> set-point=<percentage> [m=<int>] [c=<int>]
> ```

If one chooses to do "auto" instead of "ticks" how does one set the util-fraction?
___
*[`pkg/util/admission/testdata/scheduler_latency_listener/delta` line 26 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBnyyzR1Tn0OGsYZEK5:-NBnyyzR1Tn0OGsYZEK6:b-4nnxhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/testdata/scheduler_latency_listener/delta#L26)):*
> ```
> p99=1ms ticks=1 util-fraction=0.0
> p99=1ms ticks=1 util-fraction=+0.01
> ----
> ```

so this ticks twice?

I am not seeing how this directive composes with auto below.
___
*[`pkg/util/admission/testdata/elastic_cpu_granter` line 2 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBn_9ZZAoWiMsFHSVEX:-NBn_9ZZAoWiMsFHSVEY:b-t99k63) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/testdata/elastic_cpu_granter#L2)):*
> ```
> # Walk through the basics of this test. We initialize a granter with a default
> # limit of 25% CPU limit on an 8-core machine.
> ```

s/25/5/


<!-- Sent from Reviewable.io -->

2022-09-12 23:52 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @sumeerbhola)

___
*[`pkg/util/admission/elastic_cpu_work_queue_test.go` line 137 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBnbvBm1cxbo5VBsdq1:-NBo4yFeCdHsylNZyrUX:buob2h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/elastic_cpu_work_queue_test.go#L137)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how can this test code avoid implementing `tryGet`. The `WorkQueue` will call `tryGet` if the queue is empty and a new piece of work arrives.
Is this because the work queue implementation is also abstracted out using the `elasticCPUInternalWorkQueue` interface and the test implementation below is not doing much?
</blockquote></details>

Yes, the ElasticCPUWorkQueue type does not embed the WorkQueue directly, it's doing it through the elasticCPUInternalWorkQueue interface which we're providing a testing implementation for here.
___
*[`pkg/util/admission/scheduler_latency_listener_test.go` line 48 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBnvcUb8KYVYGTmf9Gk:-NBo5RJK9b2I47Qn4e71:bdp8yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/scheduler_latency_listener_test.go#L48)):*
> does the utilization fraction change by this quantity on every tick?

It only changes if there's a preceding + or - sign. 

> Is there a way to specify a constant fraction?

Yes, by omitting the + or - sign.

> And why is this utilization fraction relevant any more given that you are using queue empty as the signal?

The "queue non-empty" evaluates to true in this test file if utilization > 1% (see `setHasWaitingRequests`). I found it useful to change it in experiments/earlier iterations to be some function of installed limit to see how it behaves.
___
*[`pkg/util/admission/scheduler_latency_listener_test.go` line 58 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBnxIQYElR2B_G_SfHW:-NBo64b98k4D6Z2OfGXt:b-o1e5z9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/scheduler_latency_listener_test.go#L58)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If one chooses to do "auto" instead of "ticks" how does one set the util-fraction?
</blockquote></details>

Most of the tests do just this. You set things up manually, and then you let "auto" take over. Below for ex we're setting up a utilization growth from 0% growing at 1% per tick:

```
tick
p99=1ms ticks=1 util-fraction=0.0
p99=1ms ticks=1 util-fraction=+0.01
----

auto set-point=40% ticks=500 m=10 c=20
----
```
___
*[`pkg/util/admission/testdata/scheduler_latency_listener/delta` line 26 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBnyyzR1Tn0OGsYZEK5:-NBo6Uz3AUWPYp524tbO:bnnu3ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/testdata/scheduler_latency_listener/delta#L26)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so this ticks twice?

I am not seeing how this directive composes with auto below.
</blockquote></details>

See comment above. The first tick "resets" it to 0%, the second sets up the delta term for subsequent ticks.
___
*[`pkg/util/admission/testdata/elastic_cpu_granter` line 2 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBn_9ZZAoWiMsFHSVEX:-NBo6TkG5NqozGueHD46:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/testdata/elastic_cpu_granter#L2)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/25/5/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-13 14:40 UTC, irfansharif commented
@sumeerbhola: are there any blocking comments? I’d like to merge + backport. I also have some observability PRs sequenced on top.

2022-09-15 19:43 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 10 of 28 files at r21.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-:-NBq_pmx-9s4dPIG0e99:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @sumeerbhola)

___
*[`pkg/util/admission/testdata/scheduler_latency_listener/min_max_factor` line 82 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBq_Jto7qzVZP3je3tg:-NBq_Jto7qzVZP3je3th:b-82g13a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/testdata/scheduler_latency_listener/min_max_factor#L82)):*
> ```
>   0.0 ┼╯
>                        elastic cpu utilization and limit (%)
> ----
> ```

love these visual tests!
___
*[`pkg/util/admission/scheduler_latency_listener_test.go` line 214 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBqVmGI6T8otF3Lh33h:-NBqVmGI6T8otF3Lh33i:b-aglnn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/scheduler_latency_listener_test.go#L214)):*
> ```Go
> 					}
> 
> 					for i := 0; i < ticks; i++ {
> ```

How does auto "take over" if we are also ticking here? Is it because the utilDelta, utilFrac etc. are also remembered and used in "auto"? This can use some commentary at the top of this test. And for the degenerate case that we are going to do many ticks with "auto" is there a reason we tick once in this tick command (in the testdata files), instead of specifying ticks=0?


<!-- Sent from Reviewable.io -->

2022-09-15 19:45 UTC, sumeerbhola commented
something went wrong with reviewable or my clicking, and my comments and approval from monday 7.30am did not go through :(

2022-09-15 22:11 UTC, irfansharif reviewed
TFTR -- that was a lot to have had to read through! Only force pushing to rebase off of a pebble vendor bump.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-:-NC2AUk_1iB9pyK9XY_f:b-4sz0t7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist and @sumeerbhola)

___
*[`pkg/util/admission/scheduler_latency_listener_test.go` line 214 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/86638#-NBqVmGI6T8otF3Lh33h:-NC2AeCy2m7mn5qYByYA:b-xzyw3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41f2650ba9c53d10b282d75e89a8203bfaa57d4/pkg/util/admission/scheduler_latency_listener_test.go#L214)):*
There's a bit of code duplication here that I didn't bother refactoring. This ticking happens under the "tick" directive where each tick is manually specified, the same loop exists in "auto" where only the tick count is specified. 

> Is it because the utilDelta, utilFrac etc. are also remembered and used in "auto"?

Indeed.

> This can use some commentary at the top of this test.

Added.

> And for the degenerate case that we are going to do many ticks with "auto" is there a reason we tick once in this tick command (in the testdata files), instead of specifying ticks=0?

No good reason, that too would work.


<!-- Sent from Reviewable.io -->

2022-09-15 22:43 UTC, irfansharif commented
bors r+

2022-09-15 23:50 UTC, merged