ui: add snapshots metrics dashboard
cockroachdb/cockroach pull request #86702
Opened 2022-08-23 20:13 UTC by Santamaura

This change adds a new snapshot dashboard to the metrics
page. Metrics visualized on this dashboard can be used
to help triage decommissioning issues. Metrics visualized
include:
- queue.replicate.addreplica.(success|error)
- queue.replicate.removereplica.(success|error)
- queue.replicate.replacedeadreplica.(success|error)
- queue.replicate.removedeadreplica.(success|error)
- queue.replicate.replacedecommissioningreplica.(success|error)
- queue.replicate.removedecommissioningreplica.(success|error)
- range.snapshots.send-queue
- range.snapshots.recv-queue
- range.snapshots.send-in-progress
- range.snapshots.recv-in-progress
- queue.replicate.purgatory
- range.snapshots.unknown.rcvd-bytes
- range.snapshots.unknown.sent-bytes
- range.snapshots.rebalancing.rcvd-bytes
- range.snapshots.rebalancing.sent-bytes
- range.snapshots.recovery.rcvd-bytes
- range.snapshots.recovery.sent-bytes

Release justification: low risk, high benefit changes to
existing functionality.

Resolves #86599

Release note (ui change): introduce snapshots dashboard on metrics
page to improve decommissioning observability

2022-08-23 20:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/86702)
<!-- Reviewable:end -->

2022-08-25 07:14 UTC, AlexTalks requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @Santamaura)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIpGes9JbrlzkDwzRa:-NAIpGes9JbrlzkDwzRb:bea9pyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx#L176)):*
> ```XML
>   <div>
>     The number of snapshots queued to be applied on a receiver which can only{" "}
>     send 1 at a time per store.
> ```

`s/send/accept`
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIpUFV2eRgRYJm93xj:-NAIpUFV2eRgRYJm93xk:bd99pgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx#L183)):*
> ```XML
>   <div>
>     The number of replicas that had an error and cannot be processed until
>     something changes.
> ```

until cluster configuration changes.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIpwm42TM9HbY-pA4U:-NAIpwm42TM9HbY-pA4V:b-nl1d5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L186)):*
> ```XML
>         {_.map(nodeIDs, nid => (
>           <>
>             <Metric
> ```

Do we need the total if we have the breakdown metrics?
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIqQo0EtwoitkWNlTb:-NAIqQo0EtwoitkWNlTc:bwi56z3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L389)):*
> ```XML
>     </LineGraph>,
>     <LineGraph
>       title="Replicas in Purgatory"
> ```

Should this this specifically reference the Replicate Queue or would that already be inferred by the fact that this is on the Replication dashboard?


<!-- Sent from Reviewable.io -->

2022-08-25 07:33 UTC, AlexTalks requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @Santamaura)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIsa4L0UjY3wFHxomz:-NAIsa4L0UjY3wFHxon-:bt0rzb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L295)):*
> ```XML
>               key={nid}
>               name="cr.store.queue.replicate.addreplica.success"
>               title={nodeDisplayName(nodesSummary, nid) + "-live-add"}
> ```

Do we need the `nodeDisplayName(..)` bit if we have an annotation of the node next to the metric already?

Also, as useful as I think it is to see the breakdown of the successes/failures by node, after taking a look the number of time series will indeed be extremely huge on a cluster with a large number of nodes/stores.  I think it might make sense to group each action across all nodes after all, similar to the Queues / Replication Queue chart.  More detailed breakdowns can always be obtained with the "Create Custom Chart" tool also.
![Screen Shot 2022-08-25 at 3.33.04 AM.png](https://files.reviewableusercontent.io/images/reviewable/3944700/-yf7L4UPRRc_ec-zIfjDuKTS/Screen%20Shot%202022-08-25%20at%203.33.04%20AM.png)
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIqQo0EtwoitkWNlTb:-NAIrusM6MXUMcGq02LJ:b-bkhjh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L389)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Should this this specifically reference the Replicate Queue or would that already be inferred by the fact that this is on the Replication dashboard?
</blockquote></details>

I feel bad that I didn't catch this earlier but on a closer look it seems we already have "Replicas in Purgatory" metric on the "Queues / Replication Queue" chart - in which case I'm not sure this chart will be as useful.


<!-- Sent from Reviewable.io -->

2022-08-25 15:08 UTC, Santamaura reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIpGes9JbrlzkDwzRa:-NAKXkDKCroHUh_ox1sB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx#L176)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

`s/send/accept`
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIpUFV2eRgRYJm93xj:-NAKXl3s64PMEEW7R4v3:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx#L183)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

until cluster configuration changes.
</blockquote></details>

Removed.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIpwm42TM9HbY-pA4U:-NAKXo324nyKzaZKSJjd:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L186)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Do we need the total if we have the breakdown metrics?
</blockquote></details>

Removed.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIsa4L0UjY3wFHxomz:-NAKXr4vABG-nOGUwzdA:b-s7oate) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L295)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Do we need the `nodeDisplayName(..)` bit if we have an annotation of the node next to the metric already?

Also, as useful as I think it is to see the breakdown of the successes/failures by node, after taking a look the number of time series will indeed be extremely huge on a cluster with a large number of nodes/stores.  I think it might make sense to group each action across all nodes after all, similar to the Queues / Replication Queue chart.  More detailed breakdowns can always be obtained with the "Create Custom Chart" tool also.
![Screen Shot 2022-08-25 at 3.33.04 AM.png](https://files.reviewableusercontent.io/images/reviewable/3944700/-yf7L4UPRRc_ec-zIfjDuKTS/Screen%20Shot%202022-08-25%20at%203.33.04%20AM.png)

</blockquote></details>

Done. Changed so that it is not per node metrics.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIqQo0EtwoitkWNlTb:-NAKXzt8CAlSGak4mjdG:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L389)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

I feel bad that I didn't catch this earlier but on a closer look it seems we already have "Replicas in Purgatory" metric on the "Queues / Replication Queue" chart - in which case I'm not sure this chart will be as useful.
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2022-08-25 21:32 UTC, AlexTalks requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @Santamaura)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIpGes9JbrlzkDwzRa:-NALtpYQ21eqINFUndQA:b-sezw5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx#L176)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I mean you should change "send/accept" to just "accept"
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 318 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NALuFTACKSGWOPw_caB:-NALuFTACKSGWOPw_caC:b-3y7d6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/57097ab3dcdffd8dd02c4acd7fb423e20cd8b64d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L318)):*
> ```XML
>         <Metric
>           name="cr.store.queue.replicate.addreplica.error"
>           title={"Replicas Added / Sec"}
> ```

For each of these, can we clarify that what we are seeing are errors in the series title?

![Screen Shot 2022-08-25 at 5.26.38 PM.png](https://files.reviewableusercontent.io/images/reviewable/3944700/ngYhKHTroxVHSMVS8khzBBh6/Screen%20Shot%202022-08-25%20at%205.26.38%20PM.png)


<!-- Sent from Reviewable.io -->

2022-08-26 13:35 UTC, Santamaura reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAIpGes9JbrlzkDwzRa:-NAPMBg_7bSH5T_tJlzX:btoedfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc893f746e81b08ee58bab3589bfafd33cb10b0d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx#L176)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

I mean you should change "send/accept" to just "accept"
</blockquote></details>

Ah ok, done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 318 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NALuFTACKSGWOPw_caB:-NAPMDMIEEhIqZOftbCw:b2aa8fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/57097ab3dcdffd8dd02c4acd7fb423e20cd8b64d/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L318)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

For each of these, can we clarify that what we are seeing are errors in the series title?

![Screen Shot 2022-08-25 at 5.26.38 PM.png](https://files.reviewableusercontent.io/images/reviewable/3944700/ngYhKHTroxVHSMVS8khzBBh6/Screen%20Shot%202022-08-25%20at%205.26.38%20PM.png)

</blockquote></details>

Done, added "Errors" to series titles.


<!-- Sent from Reviewable.io -->

2022-08-31 18:25 UTC, AlexTalks requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @Santamaura)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAp8MV22HdOL3eI44c6:-NAp8MV49kx7jUNuu6VK:b764cy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4055957d9db0f62c889b238f2248f1d5c8a70fe1/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L187)):*
> ```XML
>             <Metric
>               key={nid}
>               name="cr.store.range.snapshots.unknown.rcvd-bytes"
> ```

Let's remove this metric from the chart.  I've validated that we do not send snapshots with priority `UNKNOWN`.  We should get rid of this in the KV code entirely - I'll create a follow-up issue for that.


<!-- Sent from Reviewable.io -->

2022-09-01 14:17 UTC, Santamaura reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAp8MV22HdOL3eI44c6:-NAtPVdm918m3wgIP5FT:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4055957d9db0f62c889b238f2248f1d5c8a70fe1/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L187)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Let's remove this metric from the chart.  I've validated that we do not send snapshots with priority `UNKNOWN`.  We should get rid of this in the KV code entirely - I'll create a follow-up issue for that.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-09-01 17:20 UTC, AlexTalks requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @Santamaura)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAu1KLk6HlVBT83LWIk:-NAu1KLk6HlVBT83LWIl:btivnfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/39a257b1821cef80c13047ce839eb84b8b315090/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L182)):*
> ```XML
> 
>     <LineGraph title="Snapshot Data Received" sources={storeSources}>
>       <Axis label="bytes">
> ```

`units={AxisUnits.Bytes}`
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 330 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAu1MWa61sJ4_XPxWxq:-NAu1MWa61sJ4_XPxWxr:b-ebqcez) ([raw file](https://github.com/cockroachdb/cockroach/blob/39a257b1821cef80c13047ce839eb84b8b315090/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L330)):*
> ```XML
>         />
>         <Metric
>           name="cr.store.queue.replicate.replacedecommissioningreplica.error"
> ```

One thing suggested upon reviewing with team members yesterday: would it be possible to _also_ add another chart showing `queue.replicate.replacedecommissioningreplica.error` (or possibly a series showing the sum of `queue.replicate.replacedecommissioningreplica.error` and `queue.replicate.removedecommissioningreplica.error`, if that is possible) titled "Decommissioning Errors"?  With a single series, we could have these 

The reason for breaking out this chart would be to:  
A) show the errors coming from each node.  That makes it possible to immediately identify which logs to investigate to see what the actual errors are, without requiring the user to add a custom chart to find which node is reporting the errors, and
B) Since decommissioning is the only action which has an operator actively waiting until completion to do other actions (I.e. get rid of the node), and causes significant frustration when there are errors or things are stuck, it merits displaying this in a unique chart.


<!-- Sent from Reviewable.io -->

2022-09-01 22:34 UTC, Santamaura reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAu1KLk6HlVBT83LWIk:-NAv9Hsd2c_vGSSjFK6L:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/39a257b1821cef80c13047ce839eb84b8b315090/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L182)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

`units={AxisUnits.Bytes}`
</blockquote></details>

Done
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 330 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-NAu1MWa61sJ4_XPxWxq:-NAv9L9B4HQMZszRjNY2:b-gtu8dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/39a257b1821cef80c13047ce839eb84b8b315090/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L330)):*
> One thing suggested upon reviewing with team members yesterday: would it be possible to also add another chart showing queue.replicate.replacedecommissioningreplica.error

Done

> A) show the errors coming from each node. That makes it possible to immediately identify which logs to investigate to see what the actual errors are, without requiring the user to add a custom chart to find which node is reporting the errors,

Per this comment I'm assuming per node metrics on the new graph.

>(or possibly a series showing the sum of queue.replicate.replacedecommissioningreplica.error and queue.replicate.removedecommissioningreplica.error, if that is possible)

I don't think this is possible with the current infra.


<!-- Sent from Reviewable.io -->

2022-09-01 23:23 UTC, AlexTalks approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
Thanks for all the work on this!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-:-NAvMNu632otSfaj8UrY:bqufl8z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks)



<!-- Sent from Reviewable.io -->

2022-09-02 16:03 UTC, AlexTalks commented
bors r+

2022-09-02 18:27 UTC, AlexTalks commented
bors cancel

2022-09-02 18:27 UTC, AlexTalks commented
bors r+

2022-09-05 20:59 UTC, AlexTalks commented
bors cancel

2022-09-05 20:59 UTC, AlexTalks commented
bors r+

2022-09-06 14:03 UTC, Santamaura commented
bors r+

2022-09-06 16:29 UTC, nkodali approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86702#-:-NBIcYFW8Au0vEt6_CIC:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Santamaura)



<!-- Sent from Reviewable.io -->

2022-09-06 16:39 UTC, Santamaura commented
bors r+

2022-09-06 19:19 UTC, merged