release-22.1: changefeedccl: add non-batching retries to kafka sink
cockroachdb/cockroach pull request #87048
Opened 2022-08-29 17:45 UTC by samiskin

Backport 1/1 commits from https://github.com/cockroachdb/cockroach/pull/86138

/cc @cockroachdb/release 

---

A recurring painpoint of changefeeds is the "message too large" kafka
issue where a fixed size batch may sometimes end up being too many bytes
in size due to varying message sizes, but there was no mechanism to
reduce the batch size dynamically, so the changefeed would simply fail.

This PR adds an internal retry mechanism to the kafka sink, where upon
observing a messagetoolarge error the sink will pause all new incoming
messages, attempt to retry those messages with a progressively smaller
batch size, then once one is found resumes operation with the original
configuration.

Release note (bug fix): Changefeeds emitting to Kafka upon receiving a
"message too large" error will now halve the size of their batches until
it either succeeds or a batch size of 1 fails.

Release justification: high priority bug fix, new code is mostly only ran in
cases where an unrecoverable error would've occurred previously and can
be toggled with a cluster setting.

---

Release justification: high priority bug fix

2022-08-29 17:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/87048)
<!-- Reviewable:end -->

2022-10-14 16:13 UTC, samiskin commented
The only difference between this and master is that the option defaults to false + the tests are each ran in their own `kafkaTest(...)` call as for some reason it would fail when reusing the same sink even though this error didn't happen on master.  I was stuck for a while on seeing `TestChangefeedFlushesSinkToReleaseMemory` fail, but turns out thats a flake that happens even with no changes as shown by this no-op test branch CI failure https://github.com/cockroachdb/cockroach/pull/89943

2022-10-15 15:28 UTC, miretskiy approved these changes

2022-10-15 23:19 UTC, miretskiy requested changes
I don't know if this batch retrying works at all.

2022-10-16 00:45 UTC, miretskiy commented
Informs https://github.com/cockroachdb/cockroach/issues/90029

2023-04-21 14:38 UTC, shermanCRL commented
Is a backport to v22.1 plausible or advisable? There are large users who are on that version and are likely to be for a while.

2025-07-09 07:05 UTC, closed without merging