storage: assert invariants for `intentInterleavingIter`
cockroachdb/cockroach pull request #87134
Opened 2022-08-30 18:28 UTC by erikgrinaker

Would like to get your thoughts on this pattern before I add assertions for the other iterators.

---

This patch adds invariant assertions for `intentInterleavingIter` using
a similar pattern as `pointSynthesizingIter`: by calling
`assertInvariants()` under race during `Valid()`. This allows specifying
all internal invariants in a simple-to-understand form and asserting
them all after every state transition.

Existing race assertions have been migrated.

Touches #86651.

Release justification: non-production code changes

Release note: None

2022-08-30 18:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/87134)
<!-- Reviewable:end -->

2022-08-31 09:18 UTC, tbg requested changes, later dismissed
Did not review but +1 on the pattern
Req changes so that you can re-request when ready

2022-09-06 18:57 UTC, sumeerbhola reviewed
+1 on centralizing the assertions. If we ever do https://github.com/cockroachdb/cockroach/issues/66869#issuecomment-1177729588, this will help there too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87134#-:-NBJ9F6Q5CAXzNmCw7i0:b-m1zi5c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)



<!-- Sent from Reviewable.io -->

2022-09-13 20:22 UTC, erikgrinaker commented
This should be ready to review now. Found a couple of bugs, and a bonus performance optimization as well.

2022-09-14 14:54 UTC, jbowens approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 8 of 8 files at r9, 2 of 2 files at r10, 4 of 4 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87134#-:-NBwUawq2AEOScXQg5pe:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)



<!-- Sent from Reviewable.io -->

2022-09-14 15:41 UTC, erikgrinaker commented
TFTR!

bors r=jbowens

2022-09-14 15:42 UTC, erikgrinaker commented
bors r=jbowens

2022-09-14 16:43 UTC, erikgrinaker commented
bors retry

2022-09-14 17:36 UTC, merged