sql: index rec with NotVisible indexes
cockroachdb/cockroach pull request #87174
Opened 2022-08-31 12:50 UTC by wenyihu6

**sql: introduce index rec type**
This commit introduces a type indexRecType which acts as an enum to represent
the type of index recommendation. This commit does not change any existing
functionality, and the main purpose is to make future commits cleaner.

Release justification: This is a low risk change to the existing functionality.

Release note: None

---

**sql: finds better index to replace in index rec**
Background information on how index recommendation works now: It first finds
possible index candidates with the given query. These index candidates determine
which columns to store inside hypothetical indexes definition. In addition, the
hypothetical indexes store every other column from the table (as they are stored
in a STORING clause). Then, the index recommender calls the optimizer with the
updated table that stores both existing and hypothetical indexes. The index
recommender then scans over the optimal plan and sees if a hypothetical index is
used. If so, an index recommendation is constructed. However, we do not know the
entire set of useful columns yet. While processing the entire optimal plan, we
update the index recommendation instances to add useful columns.

Prior to this commit, index recommendation decides what existing index can be
potentially replaced when the index recommendation is constructed. It looks for
the first existing index with the same explicit column as the hypothetical index
definition. This is not ideal because the best existing index to replace might
not be the first one. This commit changes the logic so that the index
recommender decides what the best existing index to replace is after it fully
processes the optimal plan and decides the entire set of columns that are
useful. The best existing index to replace is the one that stores the same
explicit column as the hypothetical index and stores the most columns from 
what was actually scanned.

Consider the following example. 
```
CREATE INDEX idx_1 ON t(v) 
CREATE INDEX idx_2 ON t(v) STORING (i) 
```
Given `SELECT i, j FROM t5 WHERE v > 1`, the index recommendation
previously recommends replacing idx_1 with `idx(v) STORING (i, j)`. It now
recommends replacing `idx_2 with idx(v) STORING (i, j)` as idx_2 is more similar
to what we want to replace later on.

In addition, this commit also makes adding invisible indexes to index
recommender much easier.

Release justification: This is a low risk change to the existing functionality.

Release note: Instead of always recommending to replace the first existing index
with the same explicit columns, the index recommendation now considers all
existing indexes in the table to decide the best one to replace.

---

**sql: index rec with NotVisible indexes**

Now that we have introduced not visible index feature, we should update index
recommendations accordingly. Prior to this commit, the index recommendation
engine treats all indexes as they are visible. If an index already exists in the
table and is the same as we want to recommend, this index recommendation 
is not created. However, it is possible that this index is not visible now. This 
commits fixes this by adding not visible indexes to the logic.

The index recommender only recommends alter index visible if the index already
contains every explicit column in the hypothetical index and every useful column. 
It will never recommend dropping an invisible index.

Fixes: #85477

Release justification: This commit does not interfere with existing
functionality and fixes the index recommendation engine to take an index 
visibility into account.

Release note: Index recommendation now considers not visible indexes and can
also make index recommendations for alter index … visible.

2022-08-31 12:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/87174)
<!-- Reviewable:end -->

2022-08-31 13:00 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAnxdvvBlnBOaf4b0RH:-NAnxdvvBlnBOaf4b0RI:b-vhplp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4069c6d792b99cca40118c2811cfb82ae1d3972d/pkg/sql/opt/indexrec/rec.go#L127)):*
> ```Go
> 	var existingStoredOrds util.FastIntSet
> 	for i, n := existingIndex.ExplicitColumnCount(), existingIndex.ColumnCount(); i < n; i++ {
> 		existingStoredOrds.Add(existingIndex.Column(i).Ordinal())
> ```

I want to draw attention to this line:
Initially, we get stored columns of an existing index's the STORING clause by 
```
	for i, n := ir.existingIndex.KeyColumnCount(), ir.existingIndex.ColumnCount(); i < n; i++ {
		existingStoredOrds.Add(ir.existingIndex.Column(i).Ordinal())
	}

```

Now I am using `ExplicitColumnCount()` instead of `KeyColumnCount()`. I'm assuming `ExplicitColumnCount()` has the number of keys in the explicit index definition, and `KeyColumnCount()` has extra stored columns. But I'm not sure if I'm understanding correctly. Does ExplicitColumnCount also include inverted columns?


<!-- Sent from Reviewable.io -->

2022-08-31 13:04 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 234 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAnzwQd1vE3D3mwR6Gc:-NAnzwQd1vE3D3mwR6Gd:bt5pz72) ([raw file](https://github.com/cockroachdb/cockroach/blob/4069c6d792b99cca40118c2811cfb82ae1d3972d/pkg/sql/opt/indexrec/rec.go#L234)):*
> ```Go
> 				// means optimizer must be using some columns from the hypothetical
> 				// indexes that are not stored by the existing index.
> 				panic("Index recommendation should not be redundant.")
> ```

I'm also not sure if we want to panic if something odd happens here. Is it too disruptive?


<!-- Sent from Reviewable.io -->

2022-08-31 17:00 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAnxdvvBlnBOaf4b0RH:-NAolWYGBNxIO76cNBY7:bovdlr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4069c6d792b99cca40118c2811cfb82ae1d3972d/pkg/sql/opt/indexrec/rec.go#L127)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I want to draw attention to this line:
Initially, we get stored columns of an existing index's the STORING clause by 
```
	for i, n := ir.existingIndex.KeyColumnCount(), ir.existingIndex.ColumnCount(); i < n; i++ {
		existingStoredOrds.Add(ir.existingIndex.Column(i).Ordinal())
	}

```

Now I am using `ExplicitColumnCount()` instead of `KeyColumnCount()`. I'm assuming `ExplicitColumnCount()` has the number of keys in the explicit index definition, and `KeyColumnCount()` has extra stored columns. But I'm not sure if I'm understanding correctly. Does ExplicitColumnCount also include inverted columns?
</blockquote></details>

My bad. I see now. `KeyColumnCount()` includes columns that are implicitly stored such as row id or other columns, so KeyColumnCount() is more correct here. I reverted the changes. 


<!-- Sent from Reviewable.io -->

2022-08-31 17:03 UTC, mgartner requested changes
Left some feedback for the first two commits.

> Reviewed 9 of 9 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-:-NAoqpl6D-UQA2jNS2DX:b-qgci75)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @wenyihu6)

___
*[`-- commits` line 19 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoZfgrD5MvoX_DJThc):*
nit: the index rec call => the index recommender calls
___
*[`-- commits` line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAo_08J3y6x_JphRRNz):*
nit: set of columns are useful => set of columns **that** are useful
___
*[`pkg/sql/opt/indexrec/hypothetical_table_test.go` line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAohWUMBXQFU-0tj7jQ:-NAohWUMBXQFU-0tj7jR:blrtz0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/hypothetical_table_test.go#L52)):*
> ```Go
> }
> 
> func TestCheckSameExplicitCols(t *testing.T) {
> ```

nit: these unit tests are difficult to understand, because you have to go to the helper functions to look at the values returned. Are these covering code that is not covered by the data drive tests? If you think they are necessary, I recommend trying to convert them to table driven tests if possible. Example: https://github.com/cockroachdb/cockroach/blob/928f605c3e84efb30cab213b47b2f4a66b816701/pkg/sql/opt/distribution/distribution_test.go#L27
___
*[`pkg/sql/opt/indexrec/rec.go` line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAnxdvvBlnBOaf4b0RH:-NAoj-f5DBoih1WyRH7i:b-52r4qt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4069c6d792b99cca40118c2811cfb82ae1d3972d/pkg/sql/opt/indexrec/rec.go#L127)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

My bad. I see now. `KeyColumnCount()` includes columns that are implicitly stored such as row id or other columns, so KeyColumnCount() is more correct here. I reverted the changes. 
</blockquote></details>

Explicit columns are the columns explicit listed when the index is created, not including columns in `STORING`. Key columns are the columns the make up the key for each key-value pair in the index. Key columns is generally longer than explicit columns.

For example

```
CREATE TABLE t (
  id1 INT,
  id2 INT,
  a INT,
  b INT,
  c INT,
  PRIMARY KEY (id1, id2),
  INDEX idx (a, b) STORING (c)
)
```

The explicit columns of `idx` are `(a, b)`. The key columns of `idx` are `(a, b, id1, id2)`.
___
*[`pkg/sql/opt/indexrec/rec.go` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoX1wFBkr5Qe5Wyje4:-NAoX1wJ9ESCdEPvU7mC:bwvlzku) ([raw file](https://github.com/cockroachdb/cockroach/blob/6496f05609d675c2b3f80b4cb129b97d120c6db1/pkg/sql/opt/indexrec/rec.go#L24)):*
> ```Go
> )
> 
> type indexRecType uint8
> ```

It's a bit weird to export the constants of this type, but not the actual type, so maybe export this? You could name it just `Type` so that references to it outside the package at `indexrec.Type` instead of the repetitive `indexrec.IndexRecType`.
___
*[`pkg/sql/opt/indexrec/rec.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoXciuBesmsNkTisKJ:-NAoXciv1d8F6XsDP1ql:birnigf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6496f05609d675c2b3f80b4cb129b97d120c6db1/pkg/sql/opt/indexrec/rec.go#L29)):*
> ```Go
> 	TypeCreateIndex indexRecType = iota
> 	TypeReplaceIndex
> 	TypeUseless
> ```

nit: You can unexport this (i.e., rename to `typeUseless`) if it won't be used outside of this package.
___
*[`pkg/sql/opt/indexrec/rec.go` line 91 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAobBCeEIbO433aFR6i:-NAobBCeEIbO433aFR6j:b-eg2lpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L91)):*
> ```Go
> }
> 
> // checkSameExplicitCols is a helper function that checks whether the given
> ```

nit: the statement "is a helper function" isn't necessary.
___
*[`pkg/sql/opt/indexrec/rec.go` line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoioFM-Or9aDUsPNHn:-NAoioFM-Or9aDUsPNHo:b4kx3ln) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L94)):*
> ```Go
> // existing index has the same explicit columns as the given indexCols. If so,
> // it returns true.
> func checkSameExplicitCols(
> ```

I think this should be a method of `hypotheticalIndex` since it's always used in the context of a hypo-index. Consider renaming it to `hasExplicitCols`.
___
*[`pkg/sql/opt/indexrec/rec.go` line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoasE0B19DM8y6pwZ8:-NAoasE0B19DM8y6pwZ9:b-eloi25) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L100)):*
> ```Go
> 		return false
> 	}
> 	for j, m := 0, existingIndex.ExplicitColumnCount(); j < m; j++ {
> ```

With this current implementation, the order of columns matters. For example `INDEX (a, b)` would not match `INDEX (b, a)`. I think that's desired, but just wanted you to confirm. If order does matter, the comment on the function should make that clear.
___
*[`pkg/sql/opt/indexrec/rec.go` line 119 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAobRSz9TTNl5X0DcMB:-NAobRSz9TTNl5X0DcMC:b92hqhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L119)):*
> ```Go
> 
> // getStoredCols returns stored columns of the given existingIndex including in
> // the STORING clause.
> ```

nit: remove "including in the STORING clause" - it's redundant

nit: make it clear that the ordinals of the stored columns are returned
___
*[`pkg/sql/opt/indexrec/rec.go` line 129 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAobnOM7JzpPQ7rP_bv:-NAobnOM7JzpPQ7rP_bw:by1ta4) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L129)):*
> ```Go
> 
> // findBestExistingIndexToReplace finds the best existing index to replace given
> // the table with existing indexes, hypothetical index's explicit columns, and
> ```

nit "hypothetical index's explicit columns" => "**the** hypothetical index's explicit columns"
___
*[`pkg/sql/opt/indexrec/rec.go` line 133 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoc5FJ4NvtVSZriZHZ:-NAoc5FJ4NvtVSZriZH_:bpsufb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L133)):*
> ```Go
> //
> // We are looking for the best existing index candidate to replace. To be a
> // candidate, the existing index has to be 1. not a partial index (because we do
> ```

nit: => "has to 1. not be a partial index"
___
*[`pkg/sql/opt/indexrec/rec.go` line 134 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoc9W0AWqd2MXL3H3I:-NAoc9W0AWqd2MXL3H3J:b-1xbodm) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L134)):*
> ```Go
> // We are looking for the best existing index candidate to replace. To be a
> // candidate, the existing index has to be 1. not a partial index (because we do
> // not want to recommend dropping a partial index) 2. stores the same explicit
> ```

nit: We should only use the word "store(s)" when referring to columns in STORING. So instead of "stores the same explicit columns as the hypIndex", how about "has the same explicit columns as hypIndex".
___
*[`pkg/sql/opt/indexrec/rec.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAocxPMBqFnYW9bdkRF:-NAocxPMBqFnYW9bdkRG:bivc8t3) ([raw file](https://github.com/cockroachdb/cockroach/bl [...]

2022-08-31 20:20 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/hypothetical_table_test.go` line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAohWUMBXQFU-0tj7jQ:-NApY1cF7ctJY5c9I-01:blpzswc) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/hypothetical_table_test.go#L52)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: these unit tests are difficult to understand, because you have to go to the helper functions to look at the values returned. Are these covering code that is not covered by the data drive tests? If you think they are necessary, I recommend trying to convert them to table driven tests if possible. Example: https://github.com/cockroachdb/cockroach/blob/928f605c3e84efb30cab213b47b2f4a66b816701/pkg/sql/opt/distribution/distribution_test.go#L27
</blockquote></details>

I agree. They were confusing to me as well. Some were useful when I checked the helper function but no longer useful now. I have removed them.


<!-- Sent from Reviewable.io -->

2022-08-31 20:20 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoX1wFBkr5Qe5Wyje4:-NApYyM6CjzGxTq23O0u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6496f05609d675c2b3f80b4cb129b97d120c6db1/pkg/sql/opt/indexrec/rec.go#L24)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's a bit weird to export the constants of this type, but not the actual type, so maybe export this? You could name it just `Type` so that references to it outside the package at `indexrec.Type` instead of the repetitive `indexrec.IndexRecType`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-31 20:20 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoXciuBesmsNkTisKJ:-NApYzje7mzi6bWxxnAX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6496f05609d675c2b3f80b4cb129b97d120c6db1/pkg/sql/opt/indexrec/rec.go#L29)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: You can unexport this (i.e., rename to `typeUseless`) if it won't be used outside of this package.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-31 20:20 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAnxdvvBlnBOaf4b0RH:-NApZ16739r5sWQG7qlt:b5b8d6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/4069c6d792b99cca40118c2811cfb82ae1d3972d/pkg/sql/opt/indexrec/rec.go#L127)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Explicit columns are the columns explicit listed when the index is created, not including columns in `STORING`. Key columns are the columns the make up the key for each key-value pair in the index. Key columns is generally longer than explicit columns.

For example

```
CREATE TABLE t (
  id1 INT,
  id2 INT,
  a INT,
  b INT,
  c INT,
  PRIMARY KEY (id1, id2),
  INDEX idx (a, b) STORING (c)
)
```

The explicit columns of `idx` are `(a, b)`. The key columns of `idx` are `(a, b, id1, id2)`.
</blockquote></details>

That makes sense. Thanks for explaining to me!


<!-- Sent from Reviewable.io -->

2022-08-31 20:25 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoasE0B19DM8y6pwZ8:-NApZ5K-9oB1PxOcVegD:b-l3vqlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L100)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

With this current implementation, the order of columns matters. For example `INDEX (a, b)` would not match `INDEX (b, a)`. I think that's desired, but just wanted you to confirm. If order does matter, the comment on the function should make that clear.
</blockquote></details>

That's right; for an existing index to be a candidate to be dropped, it has to have identical explicit columns as the hypothetical index. (same length, same element, and same order). I think this is what the index recommendation has prior to this commit as well (although this is room for index rec to improve here -> for example, if we know a specific explicit column is actually not used in a workload, we can still recommend to replace it).


<!-- Sent from Reviewable.io -->

2022-08-31 20:25 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAoasE0B19DM8y6pwZ8:-NAp_3URDhH7XpQSxR7t:bv6hcoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L100)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

That's right; for an existing index to be a candidate to be dropped, it has to have identical explicit columns as the hypothetical index. (same length, same element, and same order). I think this is what the index recommendation has prior to this commit as well (although this is room for index rec to improve here -> for example, if we know a specific explicit column is actually not used in a workload, we can still recommend to replace it).
</blockquote></details>

I've updated the comment.


<!-- Sent from Reviewable.io -->

2022-08-31 20:28 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAocxPMBqFnYW9bdkRF:-NAp_PBDAEBJRkCnNQaZ:b-tfss25) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L143)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It'd be more idiomatic to return an `ok bool` as `false` if an existing index is not found. So the return type of the function would be `(idx cat.Index, storedCols util.FastIntSet, ok bool)`.
</blockquote></details>

Type is returned here to make introducing alter index visible easier. This logic returns TypeAlterIndex if an invisible index could be used in the 3rd commit. 


<!-- Sent from Reviewable.io -->

2022-08-31 20:31 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 196 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAodGlfEQOFQzXh6KmS:-NAp_qpaClA-s2Ak5m4N:buopgjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L196)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We can't panic from this code, because callers of `indexrec.FindRecs` are do not have panic catchers (`recover` blocks). It would likely crash an entire cockroach DB node. If this is a case that should error, we'll need to propagate the error up as a returned value. I think we should simply ignore this case - if the scanned columns are all stored by the index then just continue the search for an existing index. Maybe just do this

```go
if numOfStoredColsDiff.Empty() {
    continue
}
```
</blockquote></details>

I see. I've removed panic. I'm returning TypeUseless here instead of continue to match up with our behaviour prior to this commit. Before this commit, we call `prune()` to filter out index recommendations that are useless. I think this is also better as we don't know what would happen if we just leave it in an error state. (Can also be helpful for future debugging)


<!-- Sent from Reviewable.io -->

2022-08-31 20:36 UTC, wenyihu6 commented
*[`pkg/sql/opt/indexrec/rec.go` line 222 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAogsk5-ynySrclL793:-NApbURH21uKFl5IrITo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/623e8c30730143240ff99ae11ecf1534fa9af71b/pkg/sql/opt/indexrec/rec.go#L222)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think it'd be simpler to move the logic in `outputCreateIndexRec` and `outputReplaceIndex` directly into `constructIndexRec`, similar to how it was before. 

Also, we should continue to use `strings.Builder` here instead of `+` to reduce allocations. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-01 19:54 UTC, mgartner approved these changes
Very nicely done! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Let's get @maryliag to sign off on the new recommendation type before merging.

> Reviewed 10 of 10 files at r9, 8 of 8 files at r10, 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-:-NAubTD67G8IDRMbkO12:bjtwzk1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @wenyihu6)

___
*[`-- commits` line 76 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAuZGuP3346uOnjg3Wc):*
The release note should have a category like `Release note (sql change): ..`
___
*[`pkg/sql/explain_plan.go` line 152 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAuZhTf7EgCsxie5Hpq:-NAuZhTf7EgCsxie5Hpr:bz7xh29) ([raw file](https://github.com/cockroachdb/cockroach/blob/416a9ffb9482d69025c793dc192ad1081ae14b83/pkg/sql/explain_plan.go#L152)):*
> ```Go
> 				plural = "s"
> 			} else if recs[i].RecType == indexrec.TypeAlterIndex {
> 				recType = "index alteration"
> ```

nit: consider a switch statement here
___
*[`pkg/sql/idxrecommendations/idx_recommendations.go` line 54 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAuZjzz2ZUXJ-VwQ9sK:-NAuZjzz2ZUXJ-VwQ9sL:bz7xh29) ([raw file](https://github.com/cockroachdb/cockroach/blob/416a9ffb9482d69025c793dc192ad1081ae14b83/pkg/sql/idxrecommendations/idx_recommendations.go#L54)):*
> ```Go
> 		if recs[i].RecType == indexrec.TypeReplaceIndex {
> 			recType = "replacement"
> 		} else if recs[i].RecType == indexrec.TypeAlterIndex {
> ```

nit: consider a switch statement here
___
*[`pkg/sql/idxrecommendations/idx_recommendations.go` line 55 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAuZly0Ch_TPAp8vFYG:-NAuZly0Ch_TPAp8vFYH:bm5vlvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/416a9ffb9482d69025c793dc192ad1081ae14b83/pkg/sql/idxrecommendations/idx_recommendations.go#L55)):*
> ```Go
> 			recType = "replacement"
> 		} else if recs[i].RecType == indexrec.TypeAlterIndex {
> 			recType = "alteration"
> ```

cc @maryliag - is there anything else we need to do when introducing a new index recommendation type?
___
*[`pkg/sql/opt/indexrec/rec.go` line 119 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAuCs_11wZgDo1cIsQ9:-NAuCs_291kn3G2PH80u:baosp05) ([raw file](https://github.com/cockroachdb/cockroach/blob/3475e1df44c8d917ce45ef586c41c24535bdb7f0/pkg/sql/opt/indexrec/rec.go#L119)):*
> ```Go
> // this means that there does not exist an index that satisfy the requirement to
> // be a candidate. So no existing indexes can be replaced, and creating a new
> // index is necessary. It returns TypeCreateIndex, nil, and util.FastIntSet{}.
> ```

nit: mention when typeUseless is returned
___
*[`pkg/sql/opt/indexrec/rec.go` line 227 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAuD7lD-71oSO5VJlJW:-NAuD7lD-71oSO5VJlJX:b8ln6r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3475e1df44c8d917ce45ef586c41c24535bdb7f0/pkg/sql/opt/indexrec/rec.go#L227)):*
> ```Go
> 			Inverted: ir.index.IsInverted(),
> 		}
> 		sb.WriteString(createCmd.String() + ";")
> ```

nit: 

```go
sb.WriteString(createCmd.String())
sb.WriteByte(';')
```
___
*[`pkg/sql/opt/indexrec/rec.go` line 244 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAuDDgo9lQE9vvd597j:-NAuDDgo9lQE9vvd597k:b-lk6szy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3475e1df44c8d917ce45ef586c41c24535bdb7f0/pkg/sql/opt/indexrec/rec.go#L244)):*
> ```Go
> 			Inverted: ir.index.IsInverted(),
> 		}
> 		sb.WriteString(createCmd.String() + "; " + dropCmd.String() + ";")
> ```

nit: WriteString, WriteByte, WriteString, WriteByte like I mentioned above
___
*[`pkg/sql/opt/indexrec/rec.go` line 172 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAuahRW7yEwh8h7nLhY:-NAuahRW7yEwh8h7nLhZ:b-5fjzcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/416a9ffb9482d69025c793dc192ad1081ae14b83/pkg/sql/opt/indexrec/rec.go#L172)):*
> ```Go
> 			existingIndexAllCols := getAllCols(existingIndex)
> 			if actuallyScannedCols.Difference(existingIndexAllCols).Empty() {
> 				// There exists an invisible index storing every explicit column in
> ```

nit: It's not only "storing", it's all columns, right? Maybe it'd be less confusing to say "an invisible index containing ..."?
___
*[`pkg/sql/opt/indexrec/rec.go` line 284 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAub8st8zpgRIGa8co3:-NAub8st8zpgRIGa8co4:b-c6b4ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/416a9ffb9482d69025c793dc192ad1081ae14b83/pkg/sql/opt/indexrec/rec.go#L284)):*
> ```Go
> 		sb.WriteString(createCmd.String() + "; " + dropCmd.String() + ";")
> 		return Rec{sb.String(), TypeReplaceIndex}
> 	} else if recType == TypeAlterIndex {
> ```

nit: switch statement?


<!-- Sent from Reviewable.io -->

2022-09-01 22:39 UTC, mgartner approved these changes
> Reviewed 12 of 12 files at r12, 5 of 5 files at r13, 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87174)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag and @wenyihu6)

___
*[`pkg/sql/explain_plan.go` line 150 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAvBm8A4HWrUfhCmsIr:-NAvBm8A4HWrUfhCmsIs:bh4iy9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b03a975ca9d066356d0736f7bd37d94195163cbc/pkg/sql/explain_plan.go#L150)):*
> ```Go
> 			switch recs[i].RecType {
> 			case indexrec.TypeCreateIndex:
> 				plural = ""
> ```

nit `plural = ""` isn't needed
___
*[`pkg/sql/explain_plan.go` line 157 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAvCFt2CzeAnKmKl4L5:-NAvCFt2CzeAnKmKl4L6:b-6rx9mg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b03a975ca9d066356d0736f7bd37d94195163cbc/pkg/sql/explain_plan.go#L157)):*
> ```Go
> 			case indexrec.TypeAlterIndex:
> 				recType = "index alteration"
> 			default:
> ```

nit: I think you can remove the default.
___
*[`pkg/sql/idxrecommendations/idx_recommendations.go` line 59 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAvBrcJ8LER5vfn1Oo4:-NAvBrcJ8LER5vfn1Oo5:b-ypz9gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b03a975ca9d066356d0736f7bd37d94195163cbc/pkg/sql/idxrecommendations/idx_recommendations.go#L59)):*
> ```Go
> 		case indexrec.TypeAlterIndex:
> 			recType = "alteration"
> 		default:
> ```

I don't think the `default` is necessary, is it?
___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 2165 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-NAvBy0m6gvtbi3tbsT6:-NAvBy0m6gvtbi3tbsT7:b5ws111) ([raw file](https://github.com/cockroachdb/cockroach/blob/b03a975ca9d066356d0736f7bd37d94195163cbc/pkg/sql/opt/testutils/opttester/opt_tester.go#L2165)):*
> ```Go
> 		case indexrec.TypeAlterIndex:
> 			t = "alteration"
> 		default:
> ```

You could return an error if we got an unexpected type.


<!-- Sent from Reviewable.io -->

2022-09-06 13:56 UTC, wenyihu6 commented
@maryliag Friendly ping : ) hoping to merge before the branch cuts

2022-09-06 14:15 UTC, maryliag approved these changes
there are some changes on the UI that will be required with this change, but you probably wouldn't be able to make them by eod, so I'll create an issue and look into it.

> Reviewed 3 of 10 files at r11, 1 of 12 files at r12, 3 of 7 files at r14, 2 of 5 files at r15, 5 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87174#-:-NBI8gpB25fZFNi2o311:bjjbp66)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag, @mgartner, and @wenyihu6)



<!-- Sent from Reviewable.io -->

2022-09-06 14:17 UTC, wenyihu6 commented
> 

Sounds good. Thank you!

2022-09-07 17:12 UTC, michae2 commented
bors r=mgartner,maryliag

2022-09-07 17:14 UTC, wenyihu6 commented
> bors r=mgartner,maryliag

Thank you! : )

2022-09-07 17:15 UTC, michae2 commented
> > bors r=mgartner,maryliag
> 
> Thank you! : )

No, thank YOU! :)

2022-09-07 20:21 UTC, merged