generate-logictest: add test timeout to BUILD files template
cockroachdb/cockroach pull request #87299
Opened 2022-09-01 18:29 UTC by healthy-pod

In #86363, we added a test.timeout arg to all go_test targets.
When generate-logictest runs out of `bazel-generate.sh`,
logic tests build files are re-created based on the template
that was missing the `test.timeout` arg and since the timeout
script doesn't run, the timeouts get deleted. This patch updates
the template to include a test timeout.

Release justification: Non-production code changes
Release note: None

2022-09-01 18:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/87299)
<!-- Reviewable:end -->

2022-09-01 18:30 UTC, rickystewart requested changes

2022-09-01 18:30 UTC, rickystewart commented on pkg/cmd/generate-logictest/templates.go
> +	args = ["-test.timeout=3595s"],
Indentation looks wrong?

2022-09-01 18:34 UTC, rickystewart approved these changes

2022-09-02 04:51 UTC, healthy-pod commented
bors r=rickystewart

2022-09-02 06:09 UTC, merged