ui: update txn contention insights to use waiting txns as event
cockroachdb/cockroach pull request #87440
Opened 2022-09-06 18:15 UTC by ericharmeling

This commit updates the transaction workload insights pages to use the waiting
contended transaction as the primary contention event, rather than the blocking
transaction.

Fixes https://github.com/cockroachdb/cockroach/issues/87284.

Release justification: bug fixes and low-risk updates to new functionality
Release note: None

2022-09-06 18:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/87440)
<!-- Reviewable:end -->

2022-09-06 21:21 UTC, maryliag approved these changes
Reviewing just 2nd commit (consider you will rebase since the first got merged): <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87440#-:-NBJf9mUACnX3520ewBz:b-zbtv0w)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-09-06 23:36 UTC, ericharmeling commented
TFTR!

2022-09-07 14:03 UTC, ericharmeling commented
bors r+

2022-09-07 16:35 UTC, maryliag commented
bors r+

2022-09-07 17:48 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87440)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsView.tsx` line 238 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87440#-NBO31GeDdoWHjASAdE1:-NBO31GeDdoWHjASAdE2:b4m48aw) ([raw file](https://github.com/cockroachdb/cockroach/blob/be87b4afca25137f39674113b7e703a6c091cb80/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsView.tsx#L238)):*
> ```XML
>                   <EmptyInsightsTablePlaceholder
>                     isEmptySearchResults={
>                       search?.length > 0 && filteredTransactions?.length > 0
> ```

this should be `==` (saw this error also on statement insights if you want to fix that).
this is asking if there is an empty result because of a search term, so you're checking if there was a search term and if there were not results, meaning length == 0


<!-- Sent from Reviewable.io -->

2022-09-07 18:07 UTC, maryliag commented
bors r-

2022-09-07 18:19 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87440#-:-NBOAVYcAcjVfa9l4AEq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)



<!-- Sent from Reviewable.io -->

2022-09-07 19:36 UTC, ericharmeling commented
bors r+

2022-09-07 21:39 UTC, maryliag commented
bors r-

2022-09-08 15:26 UTC, ericharmeling commented
bors r+

2022-09-08 16:19 UTC, merged

2022-09-08 17:12 UTC, ericharmeling commented
I'm going to wait until https://github.com/cockroachdb/cockroach/pull/87608 is merged and then retry the backport, as this PR is rebased on that PR.

2022-09-08 17:46 UTC, ericharmeling commented
blathers backport

2022-09-08 17:46 UTC, ericharmeling commented
blathers backport 22.2