sql: Fix notice fail cause by URL
cockroachdb/cockroach pull request #87641
Opened 2022-09-08 19:33 UTC by e-mbrown

This commit added regex matching so changing versions dont cause notice test to fail.

Release justification: Bug fix
Release note: None

2022-09-08 19:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/87641)
<!-- Reviewable:end -->

2022-09-09 01:52 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87641)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 3416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87641#-NBUwQwl4UPFNv2qVbow:-NBUwQwl4UPFNv2qVbox:b-jtuz1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fee480734836356b1a192b42e6cacd6cdd61b46a/pkg/sql/logictest/logic.go#L3416)):*
> ```Go
> 		for i := range query.expectedResults {
> 			expected, actual := query.expectedResults[i], actualResults[i]
> 			resultMatches, _ := regexp.MatchString(expected, actual)
> ```

can you change it so the regexp is only used if `query.noticetrace` is true?

also, don't think we should ignore the error here. we should keep it, and add
```
				if err != nil {
					return errors.CombineErrors(makeError(), err)
				}
```
(similar to the lines below)


<!-- Sent from Reviewable.io -->

2022-09-09 19:04 UTC, rafiss approved these changes
nice work!

2022-09-09 19:05 UTC, e-mbrown commented
bors r=rafiss

2022-09-09 20:17 UTC, merged