sql/schemachanger/rel: optimize error checking
cockroachdb/cockroach pull request #87820
Opened 2022-09-12 13:37 UTC by ajwerner

This change ends up making a huge difference. Otherwise, each subquery
invocation would lead to allocations which showed up in the profiles.

Release note: None

2022-09-22 13:47 UTC, ajwerner commented
I've tried to add more commentary and to clean this up a bit. It's ready for a look.

2022-09-22 15:48 UTC, chengxiong-ruan approved these changes
LGTM. awesome changes!

2022-09-22 15:48 UTC, chengxiong-ruan commented on pkg/sql/schemachanger/rel/database.go
> +			Attrs:    []Attr{idx.Attrs[0], sliceSource, sliceIndex},
maybe a redundant commentary here that there'll be only one attribute if it's inverted index so it's safe to just do `idx.Attrs[0]`

2022-09-22 15:48 UTC, chengxiong-ruan commented on pkg/sql/schemachanger/rel/database.go
> +		if typ.isSliceMemberType && !idx.isInverted {
I'd appreciate some commentary on why we want to skip in such case even it's clear that slice member can only be inserted into inverted index. like the good one you have on line #377

2022-09-22 15:48 UTC, chengxiong-ruan commented on pkg/sql/schemachanger/rel/database_entity_set.go
> +				smv.Field(sliceMemberSourceFieldIndex).Set(value)
what about the other index we expanded with attributes `Attrs: []Attr{idx.Attrs[0], sliceSource, sliceIndex}` ?

2022-09-22 15:48 UTC, chengxiong-ruan commented on pkg/sql/schemachanger/rel/doc.go
> -//   - Arrays, Maps, Slices.
Do we support Maps and Arrays already?

2022-09-22 15:48 UTC, chengxiong-ruan commented on pkg/sql/schemachanger/rel/query_build.go
> +// to creating marking the variable which is the source of the slice
`creating marking` -> `creating` ?

2022-09-22 15:48 UTC, chengxiong-ruan commented on pkg/sql/schemachanger/rel/query_build.go
> +func (p *queryBuilder) maybeAddVar(v Var, isEntity bool) slotIdx {
thanks for this renaming

2022-09-22 16:08 UTC, postamar requested changes
This is a wonderful change. I have only minor requests. Admittedly, I've only given somewhat superficial treatment to the second commit.

2022-09-26 03:21 UTC, ajwerner reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-:-NCrnrIC0mi6W5yJpInw:bodgj64)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @postamar, and @Xiang-Gu)

___
*[`pkg/sql/schemachanger/rel/database.go` line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtK6poDafokP7NI-r2-170:-NCriBkfDdBmASl29gbe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83426156d0635c2070e3a50dd22ab1d8903cbadc/pkg/sql/schemachanger/rel/database.go#L170)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Thanks for this explanation!
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/database.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtK6poDafokP7NI-r2-174:-NCaEVCn8EBtTJ7QarFd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83426156d0635c2070e3a50dd22ab1d8903cbadc/pkg/sql/schemachanger/rel/database.go#L174)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: this seems superfluous
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/database.go` line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtK6poDafokP7NI-r4-185:-NCaJxoEEVakbpK2NE86:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb67bade2e85203ab48eed44266aed6f87822fb2/pkg/sql/schemachanger/rel/database.go#L185)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

maybe a redundant commentary here that there'll be only one attribute if it's inverted index so it's safe to just do `idx.Attrs[0]`
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/database.go` line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtK6poDafokP7NI-r4-267:-NCf7DKD8QIbD9t4FEPn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb67bade2e85203ab48eed44266aed6f87822fb2/pkg/sql/schemachanger/rel/database.go#L267)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I'd appreciate some commentary on why we want to skip in such case even it's clear that slice member can only be inserted into inverted index. like the good one you have on line #377
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/database_entity_set.go` line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtK6poDafokP7NM-r4-79:-NCf7GDJ53ejrdlQr_sx:b-l6b4px) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb67bade2e85203ab48eed44266aed6f87822fb2/pkg/sql/schemachanger/rel/database_entity_set.go#L79)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

what about the other index we expanded with attributes `Attrs: []Attr{idx.Attrs[0], sliceSource, sliceIndex}` ?
</blockquote></details>

That's handled transparently. The indexing is independent of the struct fields. There's essentially two layers of indirection. We go from a struct (entity) to a `rel.values` which is a effectively a `map[Attr]interface{}` with some optimizations and then we go from a `rel.values` to a `rel.valuesItem` which combines the `values` with the `indexSpec` to describe how to sort it relative to other index entries. 
___
*[`pkg/sql/schemachanger/rel/query_build.go` line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtLM3Tq_GetAMEy-r2-184:-NCfAkZB2cYlLiXgIjKq:bcev121) ([raw file](https://github.com/cockroachdb/cockroach/blob/83426156d0635c2070e3a50dd22ab1d8903cbadc/pkg/sql/schemachanger/rel/query_build.go#L184)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: this sentence is very hard to read
</blockquote></details>

I rewrote it.
___
*[`pkg/sql/schemachanger/rel/query_build.go` line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtLM3Tq_GetAMEy-r4-181:-NCriCO5Aeswa2BVqbYi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb67bade2e85203ab48eed44266aed6f87822fb2/pkg/sql/schemachanger/rel/query_build.go#L181)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

`creating marking` -> `creating` ?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/reltest/registry.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NBlumtLM3Tq_GetAMF1-r2-97:-NCfB2kM54JrmjJXm2R4:b8amr83) ([raw file](https://github.com/cockroachdb/cockroach/blob/83426156d0635c2070e3a50dd22ab1d8903cbadc/pkg/sql/schemachanger/rel/reltest/registry.go#L97)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Just curious but how did this come about?
</blockquote></details>

slices are unhashable.

This code exists to make it possible to display pointers to structs (entities) elegantly by giving them names and replaying their inline yaml with their name. It allows the graph structure to be more apparent. Slices themselves are never part of that. 
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_drop_column.go` line 91 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCX13M4vgw7EePZiL6p-r4-91:-NCrid9Z3wIGD3SSYNVn:bn54kz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb67bade2e85203ab48eed44266aed6f87822fb2/pkg/sql/schemachanger/scplan/internal/rules/dep_drop_column.go#L91)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Yes please. Could you wrap this clause in a function which takes a `nodeVars`? I think it's worth going the extra mile with type safety in these rule definitions for any clause used more than once or twice.
</blockquote></details>

Done. Added a method.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go` line 124 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCVcVyCSCpgpECY_u5J-r3-124:-NCrkgazE2QDg1O_h34g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/872d0be2837480a526deaefd721de3c0a758ccdd/pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go#L124)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Can you replace this with a named rule? Something like `joinReferencedTypeIDInSlice(from, to, "typeDescID")`? Same for referenced sequences below.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go` line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCVcVyCSCpgpECY_u5J-r3-126:-NCrkhEI-X9O4HD9eI9P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/872d0be2837480a526deaefd721de3c0a758ccdd/pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go#L126)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

We already have a `not` function defined in `helpers.go` which takes a predicate and constructs its complement,  so you should also define an `or` combinator which builds a disjunction. It's worth it, it makes rule definitions easier to read, it's hard enough as it is.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/screl/attr.go` line 81 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCVcVyCSCpgpECY_u5W-r3-81:-NCrl6sn7Ogqc8pycNP5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/872d0be2837480a526deaefd721de3c0a758ccdd/pkg/sql/schemachanger/screl/attr.go#L81)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

`s/ReferencedTypeDescIDs/ReferencedTypeIDs/`?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/screl/attr.go` line 82 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/87820#-NCVcVyCSCpgpECY_u5W-r3-82:-NCrl6Pu9a68C4EXx0yd:b-896fix) ([raw file](https://github.com/cockroachdb/cock [...]

2022-09-26 14:56 UTC, postamar approved these changes

2022-09-26 14:57 UTC, ajwerner commented
TFTR!

bors r+

2022-09-26 18:45 UTC, merged