clisqlshell: new infrastructure for describe commands
cockroachdb/cockroach pull request #88061
Opened 2022-09-16 18:10 UTC by knz

Release note: None

2022-09-16 19:23 UTC, nvanbenschoten reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @nvanbenschoten, and @rafiss)

___
*[`pkg/cli/clisqlshell/sql.go` line 1236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NC6kG8E8UiacOF7frvr:-NC6kG8E8UiacOF7frvs:b5m229t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1e65be8ee351f991517506ad51f9e987f0f811/pkg/cli/clisqlshell/sql.go#L1236)):*
> ```Go
> 
> 	cmd := strings.Fields(line)
> 	if strings.HasPrefix(cmd[0], `\d`) && cmd[0] != `\demo` {
> ```

There are a few additional informational patterns that don't start with `\d`. For instance, `\s` and `\z`. Do we want to support those as well?


<!-- Sent from Reviewable.io -->

2022-09-16 19:53 UTC, knz commented
> There are a few additional informational patterns that don't start with \d. For instance, \s and \z. Do we want to support those as well?

Done

2022-09-16 20:31 UTC, knz commented
added the unit tests too

2022-09-16 21:58 UTC, knz commented
now with datadriven tests too

2022-09-17 21:03 UTC, knz commented
Remaining to do: list indexes and constraints under table details.

2022-09-18 14:20 UTC, knz commented
Ok I have completed the functionality -- this is more or less ready for review, the followup issues listed at top notwithstanding.

2022-11-28 20:44 UTC, ZhouXing19 approved these changes
Thanks for this impressive work! <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> my comments are just for nits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-:-NHzyx24-3bms6NA4vtZ:bthv9i1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @nvanbenschoten, and @rafiss)

___
*[`pkg/cli/clisqlshell/describe.go` line 100 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHztvhQ1v_F9InzsPAs:-NHztvhQ1v_F9InzsPAt:b37pm1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L100)):*
> ```Go
> // PostgreSQL sources, file src/bin/psql/describe.c.
> // Please keep them in sync.
> func listAllDbs(hasPattern bool, verbose bool) string {
> ```

Seems that the results of all these functions are not added with multi-region info of objects (such as `primary_region` and `survival goal` for databases). Do we have a plan for adding them in the future?
___
*[`pkg/cli/clisqlshell/describe.go` line 110 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHvucv9BOOx4MDsQWYw:-NHvucv9BOOx4MDsQWYx:b-89yoyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L110)):*
> ```Go
>        d.datcollate AS "Collate",
>        d.datctype AS "Ctype",`)
> 		printACLColumn(&buf, "d.datacl")
> ```

nit: I noticed that in Postgres 15, a new column `daticulocale` is [added](https://github.com/postgres/postgres/blob/ec25ba624e9c0168d44c9f6e87872f1e3e6b308f/src/bin/psql/describe.c#L941-L946). I don't think we have this column in `pg_catalog.pg_database` yet, but maybe we can add a TODO here.
___
*[`pkg/cli/clisqlshell/describe.go` line 162 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHvydKpDiztRtWZAMNR:-NHvydKpDiztRtWZAMNS:b-6m12bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L162)):*
> ```Go
> 
> 	buf.WriteString(`
> ORDER BY 1`)
> ```

FYI: [pg15 and forward](https://github.com/postgres/postgres/blob/ec25ba624e9c0168d44c9f6e87872f1e3e6b308f/src/bin/psql/describe.c#L5002-L5045) prints out the names of related publications in footers. We don't support `pg_catalog.pg_publication` now and I don't know if we have a plan for it, so unsure if a todo is needed here.
___
*[`pkg/cli/clisqlshell/describe.go` line 169 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHw3-yU7i9hAaG75qpU:-NHw3-yU7i9hAaG75qpV:b-3bc3dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L169)):*
> ```Go
> // objectDescription is adapted from the function of the same name in the
> // PostgreSQL sources, file src/bin/psql/describe.c.
> // Please keep them in sync.
> ```

nit: We only have descriptions for table and domain constraint here, but in [PG15](https://github.com/postgres/postgres/blob/ec25ba624e9c0168d44c9f6e87872f1e3e6b308f/src/bin/psql/describe.c#L1333-L1412) they also have those for operator class, operator family, rule and trigger. Do you think we can have a comment to remind people to update this function when needed can be helpful?
___
*[`pkg/cli/clisqlshell/describe.go` line 216 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHwbAST9EqqbH9w9cCN:-NHwbAST9EqqbH9w9cCO:bdyu5yp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L216)):*
> ```Go
>        AND n.nspname <> 'crdb_internal'
>        AND n.nspname <> 'information_schema'
>        AND pg_catalog.pg_type_is_visible(t.oid)`)
> ```

nit: in functions below (such as `describeTypes()`) we have the `pg_catalog.pg_type_is_visible(t.oid)` condition added if there is no pattern provided, but here it also needs `!showSystem`. Do you think we should also extract this as in those examples? 
___
*[`pkg/cli/clisqlshell/describe.go` line 306 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHw8G-P0caZYev6UhEB:-NHw8G-P0caZYev6UhEC:bg3jbp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L306)):*
> ```Go
> 
> 	if showTables {
> 		buf.WriteString(`'r','P',`)
> ```

nit: should it be lowercase `p` here?
___
*[`pkg/cli/clisqlshell/describe.go` line 473 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHwaIjn-5pzhzEEiufc:-NHwaIjn-5pzhzEEiufd:br8z5ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L473)):*
> ```Go
> 	buf.WriteString(`
>       AND (`)
> 	if hasPattern {
> ```

I'm trying to understand if here we're consistent with [PG15's behavior](https://github.com/postgres/postgres/blob/b5d8fd4182f24ee489aa6bb72308f8712cd8810d/src/bin/psql/describe.c#L684-L685):
```c
	if (pattern == NULL || strstr(pattern, "[]") == NULL)
		appendPQExpBufferStr(&buf, "  AND NOT EXISTS(SELECT 1 FROM pg_catalog.pg_type el WHERE el.oid = t.typelem AND el.typarray = t.oid)\n");
```
IIUC, it means that  the `NOT EXISTS...` condition will be added only if there's not a pattern provided. But here it seems that this condition will be added anyways. Do we have the same logic here?
___
*[`pkg/cli/clisqlshell/describe.go` line 588 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHwh3Vo2uhk9sCJxPMm:-NHwh3Vo2uhk9sCJxPMn:bwe622i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L588)):*
> ```Go
>           c.relhasindex,
>           EXISTS(SELECT 1 FROM pg_catalog.pg_constraint WHERE conrelid = c.oid AND contype = 'f') AS relhasfkey,
>           EXISTS(SELECT 1 FROM pg_catalog.pg_constraint WHERE confrelid = c.oid AND contype = 'f') AS relhasifkey,
> ```

nit: can `contype = 'f'` get removed here?
___
*[`pkg/cli/clisqlshell/describe.go` line 629 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHwi0MZ6zCGtSH0RNZq:-NHwi0MZ6zCGtSH0RNZr:bwl9nod) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L629)):*
> ```Go
> LEFT JOIN pg_catalog.pg_am am    ON (c.relam = am.oid)
>     WHERE c.oid = %[1]s)`)
> ```

PG15 also has [this part](https://github.com/postgres/postgres/blob/ec25ba624e9c0168d44c9f6e87872f1e3e6b308f/src/bin/psql/describe.c#L1595-L1598) with `c.reloptions`:
```sql
(verbose ?
"pg_catalog.array_to_string(c.reloptions || "
"array(select 'toast.' || x from pg_catalog.unnest(tc.reloptions) x), ', ')\n"
: "''"),
```
Curious if it is intended that we didn't follow them here.
___
*[`pkg/cli/clisqlshell/describe.go` line 648 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHwl3pW0N16tUPWlZA5:-NHwl3pW0N16tUPWlZA6:bz50v9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L648)):*
> ```Go
> 			showColDetails := false
> 			switch relkind {
> 			case "r", "v", "m", "f", "c", "p":
> ```

nit for all references to relation kinds -- can we have these characters stored as const types?
___
*[`pkg/cli/clisqlshell/describe.go` line 743 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHymAEDA_tKLnz3Yho9:-NHymAEDA_tKLnz3YhoA:b5ewho3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L743)):*
> ```Go
>          CASE attidentity
>          WHEN 'a' THEN 'generated always as identity'
>          WHEN 'd' THEN 'generated by default as identity'
> ```

This revealed a bug for which I made https://github.com/cockroachdb/cockroach/pull/92545.
___
*[`pkg/cli/clisqlshell/describe.go` line 746 at r7](https://revie [...]

2022-12-09 03:50 UTC, rafiss requested changes

2023-01-09 22:42 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88061)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @rafiss, and @ZhouXing19)

___
*[`pkg/cli/clisqlshell/describe.go` line 100 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHztvhQ1v_F9InzsPAs:-NLMtHKA5cpuvWo6JKwJ:b-vigt3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L100)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Seems that the results of all these functions are not added with multi-region info of objects (such as `primary_region` and `survival goal` for databases). Do we have a plan for adding them in the future?
</blockquote></details>

I don't have a plan. Postgres does not show this info either. Maybe have the user run SHOW DATABASES manually?
___
*[`pkg/cli/clisqlshell/describe.go` line 110 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHvucv9BOOx4MDsQWYw:-NLMtq-o6EY9te1jLlWl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L110)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: I noticed that in Postgres 15, a new column `daticulocale` is [added](https://github.com/postgres/postgres/blob/ec25ba624e9c0168d44c9f6e87872f1e3e6b308f/src/bin/psql/describe.c#L941-L946). I don't think we have this column in `pg_catalog.pg_database` yet, but maybe we can add a TODO here.
</blockquote></details>

Done.
___
*[`pkg/cli/clisqlshell/describe.go` line 169 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHw3-yU7i9hAaG75qpU:-NLMzrZE8FRNjGrV2MFD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L169)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: We only have descriptions for table and domain constraint here, but in [PG15](https://github.com/postgres/postgres/blob/ec25ba624e9c0168d44c9f6e87872f1e3e6b308f/src/bin/psql/describe.c#L1333-L1412) they also have those for operator class, operator family, rule and trigger. Do you think we can have a comment to remind people to update this function when needed can be helpful?
</blockquote></details>

Done.
___
*[`pkg/cli/clisqlshell/describe.go` line 216 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHwbAST9EqqbH9w9cCN:-NLNF6Y18fVqyWMVKk0r:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L216)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: in functions below (such as `describeTypes()`) we have the `pg_catalog.pg_type_is_visible(t.oid)` condition added if there is no pattern provided, but here it also needs `!showSystem`. Do you think we should also extract this as in those examples? 
</blockquote></details>

Fixed.
___
*[`pkg/cli/clisqlshell/describe.go` line 306 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHw8G-P0caZYev6UhEB:-NLNF7xt2qnfjksKrono:brrym9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L306)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: should it be lowercase `p` here?
</blockquote></details>

Yes, good catch. Fixed.
___
*[`pkg/cli/clisqlshell/describe.go` line 473 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHwaIjn-5pzhzEEiufc:-NLNN4ou9_WxtE2PI_2G:bi7goej) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L473)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

I'm trying to understand if here we're consistent with [PG15's behavior](https://github.com/postgres/postgres/blob/b5d8fd4182f24ee489aa6bb72308f8712cd8810d/src/bin/psql/describe.c#L684-L685):
```c
	if (pattern == NULL || strstr(pattern, "[]") == NULL)
		appendPQExpBufferStr(&buf, "  AND NOT EXISTS(SELECT 1 FROM pg_catalog.pg_type el WHERE el.oid = t.typelem AND el.typarray = t.oid)\n");
```
IIUC, it means that  the `NOT EXISTS...` condition will be added only if there's not a pattern provided. But here it seems that this condition will be added anyways. Do we have the same logic here?
</blockquote></details>

Yes this is correct. Explained in comment with predicate logic.
___
*[`pkg/cli/clisqlshell/describe.go` line 588 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHwh3Vo2uhk9sCJxPMm:-NLNQ459AywMOBVeL7eT:btbb5vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L588)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: can `contype = 'f'` get removed here?
</blockquote></details>

Why? this is what denotes foreign key constraints.
___
*[`pkg/cli/clisqlshell/describe.go` line 629 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHwi0MZ6zCGtSH0RNZq:-NLNRXzr-ITSfjtIsuO5:b-2sj03g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L629)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

PG15 also has [this part](https://github.com/postgres/postgres/blob/ec25ba624e9c0168d44c9f6e87872f1e3e6b308f/src/bin/psql/describe.c#L1595-L1598) with `c.reloptions`:
```sql
(verbose ?
"pg_catalog.array_to_string(c.reloptions || "
"array(select 'toast.' || x from pg_catalog.unnest(tc.reloptions) x), ', ')\n"
: "''"),
```
Curious if it is intended that we didn't follow them here.
</blockquote></details>

This code was dead; removed.
___
*[`pkg/cli/clisqlshell/describe.go` line 743 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHymAEDA_tKLnz3Yho9:-NLNSIUA3WBQFtcckqVS:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L743)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

This revealed a bug for which I made https://github.com/cockroachdb/cockroach/pull/92545.
</blockquote></details>

Nice.
___
*[`pkg/cli/clisqlshell/describe.go` line 765 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHzbqnFDAk6GpZjkeKK:-NLNSgb35msxJjIMFOnG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L765)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: could you add more comments about this stage? IIUC this `firstStage` is about the "basic" info about the table. 
</blockquote></details>

Done.
___
*[`pkg/cli/clisqlshell/describe.go` line 799 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHywB1z4_vWYHmOFJlJ:-NLNSyu---N_gPLE-Jz_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L799)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

[PG15](https://github.com/postgres/postgres/blob/b5d8fd4182f24ee489aa6bb72308f8712cd8810d/src/bin/psql/describe.c#L2274-L2277) added a boolean column `indnullsnotdistinct` here. For version prior to pg15, they have false as the default value. Do we want to be consistent with them here?
FYI, filed issue for support for `indnullsnotdistinct` in `pg_catalog.pg_indexes`: https://github.com/cockroachdb/cockroach/issues/92583
</blockquote></details>

Done.
___
*[`pkg/cli/clisqlshell/describe.go` line 832 at  [...]

2023-01-19 09:18 UTC, knz commented
@rafiss do you want to update your review disposition on this?

2023-01-20 15:29 UTC, rafiss approved these changes
this lgtm! and i'm excited for the nice tests

2023-01-20 15:31 UTC, rafiss commented
though the CI failure is interesting. is that an optimizer bug?

```
        testdata/describe:33:
         \l
        output didn't match expected:
        @@ -6,11 +6,52 @@
                d.datcollate AS "Collate",
                d.datctype AS "Ctype",
                COALESCE(pg_catalog.array_to_string(d.datacl, e'\n'), '') AS "Access privileges"
           FROM pg_catalog.pg_database d
         ORDER BY 1
        -Name,Owner,Encoding,Collate,Ctype,Access privileges
        -defaultdb,root,UTF8,en_US.utf8,en_US.utf8,
        -mydb,root,UTF8,en_US.utf8,en_US.utf8,
        -postgres,root,UTF8,en_US.utf8,en_US.utf8,
        -system,unknown (OID=3233629770),UTF8,en_US.utf8,en_US.utf8,
        +ERROR: internal error: lookup for ComparisonExpr ((@18)[oid] = (('defaultdb')[string])[name])[bool]'s CmpOp failed
        +SQLSTATE: XX000
        +DETAIL: stack trace:
        +github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:491: MemoizeComparisonExprOp()
        +github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:400: NewTypedComparisonExpr()
        +github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:257: buildComparison()
        +github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:107: buildScalar()
        +github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:325: BuildScalar()
        +github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/format.go:54: fmtInterceptor()
```

2023-01-20 23:30 UTC, knz commented
wowzer, this is new. It wasn't there before today's rebase.

2023-01-20 23:43 UTC, knz commented
filed  #95633

2023-02-16 04:23 UTC, ZhouXing19 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-:-NONScc56_GM_tFN8fv0:b-yncq5u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @nvanbenschoten, and @rafiss)

___
*[`pkg/cli/clisqlshell/describe.go` line 588 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/88061#-NHwh3Vo2uhk9sCJxPMm:-NONS7zGEpQrT2ZSgj_q:bc5ktfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2334cf46dfa12010a1dc1e4e6b98f378306d443c/pkg/cli/clisqlshell/describe.go#L588)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Why? this is what denotes foreign key constraints.
</blockquote></details>

Ah I see, sorry for the noise!


<!-- Sent from Reviewable.io -->

2023-02-24 20:59 UTC, knz commented
TFYRs!

bors r=rafiss,ZhouXing19

2023-02-24 21:43 UTC, merged