cli/interactive_tests: avoid running interaction tests with TERM=xterm
cockroachdb/cockroach pull request #88274
Opened 2022-09-20 18:59 UTC by knz

Running the multiline / history tests with TERM=xterm causes the shell to emit xterm-specific escape syntax that in turn confuses expect/TCL.

Release note: None

2022-09-20 19:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/88274)
<!-- Reviewable:end -->

2022-09-21 14:32 UTC, rickystewart requested changes
Looks like `test_multiline_statements` is still failing?

2022-09-22 21:54 UTC, knz commented
yes sadly it still fails, but now at least the problem is super contained. I'm, still looking

2022-12-28 05:18 UTC, knz commented
We've fixed this with the new editor i believe.

2022-12-28 05:19 UTC, closed without merging