cdc: avoid deadlock on error in pubsub sink
cockroachdb/cockroach pull request #88289
Opened 2022-09-20 20:01 UTC by HonoreDB

https://github.com/cockroachdb/cockroach/pull/88130 introduced a deadlock when an attempt to create a
topic fails -- the goroutine tries to acquire a lock in order to record the error, but it already has it in order to write to the map. This PR releases the lock while creating the topic, which should also help with performance a bit on startup.

Fixes #85374

Release note (bug fix): Fixed a bug preventing pubsub changefeeds from retrying.

2022-09-20 20:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/88289)
<!-- Reviewable:end -->

2022-09-21 07:54 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88289)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @shermanCRL)

___
*[`pkg/ccl/changefeedccl/sink_pubsub.go` line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88289#-NCU1Nw50ErvhKm7qOQ6:-NCU1Nw63DYsL7igDOn_:b-egxu4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c46a9d0e7185ed342d919886b864de5346ef6220/pkg/ccl/changefeedccl/sink_pubsub.go#L362)):*
> ```Go
> 	}
> 	p.mu.Unlock() // openTopic may need the lock to record an error
> 	topic, err := p.openTopic(name)
> ```

openTopic seems to only be called from this function and record error is only called from openTopic; why not just rename openTopic to openTopicLocked (and possible recordError to recordErrorLocked)?


<!-- Sent from Reviewable.io -->

2022-09-21 20:55 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88289)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @shermanCRL)

___
*[`pkg/ccl/changefeedccl/sink_pubsub.go` line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88289#-NCU1Nw50ErvhKm7qOQ6:-NCWoNGOEjeLklQyViPg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c46a9d0e7185ed342d919886b864de5346ef6220/pkg/ccl/changefeedccl/sink_pubsub.go#L362)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

openTopic seems to only be called from this function and record error is only called from openTopic; why not just rename openTopic to openTopicLocked (and possible recordError to recordErrorLocked)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-21 22:16 UTC, miretskiy approved these changes

2022-09-27 19:18 UTC, HonoreDB commented
bors r+

2022-09-27 21:07 UTC, merged