sql: add grammar help text for udf statements
cockroachdb/cockroach pull request #88493
Opened 2022-09-22 18:42 UTC by chengxiong-ruan

Backport resolves #87425

Release note: None
Release justification: necessary but low risk user experience change

2022-09-22 18:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/88493)
<!-- Reviewable:end -->

2022-09-23 18:09 UTC, stbof requested changes

2022-09-23 18:09 UTC, stbof commented on pkg/sql/parser/sql.y
>  alter_func_stmt:
```suggestion
// %SeeAlso: WEBDOCS/alter-function.html
alter_func_stmt:
```

2022-09-23 18:09 UTC, stbof commented on pkg/sql/parser/sql.y
>  create_func_stmt:
```suggestion
// %SeeAlso: WEBDOCS/create-function.html
create_func_stmt:
```

2022-09-23 18:09 UTC, stbof commented on pkg/sql/parser/sql.y
>  drop_func_stmt:
```suggestion
// %SeeAlso: WEBDOCS/drop-function.html
drop_func_stmt:
```

2022-09-23 18:18 UTC, chengxiong-ruan commented on pkg/sql/parser/sql.y
>  alter_func_stmt:
fixed as suggested

2022-09-23 18:18 UTC, chengxiong-ruan commented on pkg/sql/parser/sql.y
>  create_func_stmt:
fixed as suggested

2022-09-23 18:18 UTC, chengxiong-ruan commented on pkg/sql/parser/sql.y
>  drop_func_stmt:
fixed as suggested

2022-09-23 19:25 UTC, stbof approved these changes

2022-09-23 21:56 UTC, chengxiong-ruan commented
TFTR!
bors r+

2022-09-23 23:33 UTC, merged