opt/props: shallow-copy props.Histogram when applying selectivity
cockroachdb/cockroach pull request #88526
Opened 2022-09-22 22:26 UTC by michae2

**opt/props: add benchmark for props.Histogram**

Add a benchmark that measures various common props.Histogram operations.

Release note: None

**opt/props: shallow-copy props.Histogram when applying selectivity**

`pkg/sql/opt/props.(*Histogram).copy` showed up as a heavy allocator in
a recent customer OOM. The only caller of this function is
`Histogram.ApplySelectivity` which deep-copies the histogram before
adjusting each bucket's `NumEq`, `NumRange`, and `DistinctRange` by the
given selectivity.

Instead of deep-copying the histogram, we can change `ApplySelectivity`
to shallow-copy the histogram and remember the current selectivity. We
can then wait to adjust counts in each bucket by the selectivity until
someone actually calls `ValuesCount` or `DistinctValuesCount`.

This doesn't eliminate all copying of histograms. We're still doing some
copying in `Filter` when applying a constraint to the histogram.

Release note: None

2022-09-22 22:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/88526)
<!-- Reviewable:end -->

2022-09-22 22:32 UTC, michae2 commented
The tradeoff is that ValuesCount and DistinctValuesCount are in some cases twice as slow, but the absolute times are in 10s of ns so it seems like a non-issue.

```
name                                                    old time/op    new time/op    delta
Histogram/int/buckets=0/ValuesCount-16                    0.46ns ± 5%    0.48ns ± 2%    +4.00%  (p=0.004 n=9+10)
Histogram/int/buckets=0/DistinctValuesCount-16            3.20ns ± 3%    3.05ns ± 3%    -4.72%  (p=0.000 n=9+10)
Histogram/int/buckets=0/Filter-16                         64.7ns ± 0%    63.2ns ± 1%    -2.28%  (p=0.000 n=8+10)
Histogram/int/buckets=0/ApplySelectivity-16               46.3ns ± 1%    42.7ns ± 1%    -7.65%  (p=0.000 n=9+10)
Histogram/int/buckets=2/ValuesCount-16                    1.58ns ± 2%    2.50ns ± 5%   +58.36%  (p=0.000 n=10+10)
Histogram/int/buckets=2/DistinctValuesCount-16            40.8ns ± 2%    47.4ns ± 1%   +16.33%  (p=0.000 n=10+9)
Histogram/int/buckets=2/Filter-16                         1.22µs ± 1%    1.21µs ± 2%    -0.34%  (p=0.046 n=10+9)
Histogram/int/buckets=2/ApplySelectivity-16                121ns ± 1%      43ns ± 3%   -64.61%  (p=0.000 n=10+10)
Histogram/int/buckets=20/ValuesCount-16                   5.63ns ± 1%   10.51ns ± 7%   +86.50%  (p=0.000 n=8+10)
Histogram/int/buckets=20/DistinctValuesCount-16            400ns ± 2%     468ns ± 1%   +16.96%  (p=0.000 n=9+10)
Histogram/int/buckets=20/Filter-16                        4.56µs ± 4%    4.45µs ± 0%    -2.36%  (p=0.000 n=10+8)
Histogram/int/buckets=20/ApplySelectivity-16               432ns ± 2%      43ns ± 1%   -90.13%  (p=0.000 n=10+9)
Histogram/int/buckets=200/ValuesCount-16                  50.2ns ± 2%    94.7ns ± 1%   +88.70%  (p=0.000 n=10+9)
Histogram/int/buckets=200/DistinctValuesCount-16          3.95µs ± 2%    4.54µs ± 1%   +14.97%  (p=0.000 n=9+10)
Histogram/int/buckets=200/Filter-16                       33.5µs ± 0%    33.3µs ± 1%    -0.50%  (p=0.026 n=8+9)
Histogram/int/buckets=200/ApplySelectivity-16             3.30µs ± 1%    0.04µs ± 1%   -98.71%  (p=0.000 n=10+10)
Histogram/int/buckets=2000/ValuesCount-16                  482ns ± 7%     911ns ± 2%   +88.91%  (p=0.000 n=10+10)
Histogram/int/buckets=2000/DistinctValuesCount-16         41.8µs ± 5%    45.3µs ± 0%    +8.40%  (p=0.000 n=10+10)
Histogram/int/buckets=2000/Filter-16                       319µs ± 7%     326µs ± 8%      ~     (p=0.143 n=10+10)
Histogram/int/buckets=2000/ApplySelectivity-16            29.8µs ± 1%     0.0µs ± 0%   -99.85%  (p=0.000 n=9+10)
Histogram/float/buckets=0/ValuesCount-16                  0.50ns ± 6%    0.46ns ± 1%    -8.13%  (p=0.000 n=10+10)
Histogram/float/buckets=0/DistinctValuesCount-16          3.39ns ± 9%    3.12ns ± 6%    -8.06%  (p=0.001 n=10+10)
Histogram/float/buckets=0/Filter-16                       64.9ns ± 1%    64.1ns ± 5%      ~     (p=0.085 n=10+10)
Histogram/float/buckets=0/ApplySelectivity-16             48.1ns ± 3%    42.6ns ± 2%   -11.42%  (p=0.000 n=8+10)
Histogram/float/buckets=2/ValuesCount-16                  1.61ns ±12%    2.52ns ± 8%   +56.37%  (p=0.000 n=10+10)
Histogram/float/buckets=2/DistinctValuesCount-16          45.5ns ± 5%    53.2ns ± 1%   +16.79%  (p=0.000 n=10+8)
Histogram/float/buckets=2/Filter-16                       1.27µs ± 4%    1.21µs ± 1%    -4.91%  (p=0.000 n=9+10)
Histogram/float/buckets=2/ApplySelectivity-16              122ns ± 1%      44ns ± 1%   -63.80%  (p=0.000 n=10+9)
Histogram/float/buckets=20/ValuesCount-16                 5.72ns ± 1%   10.79ns ± 7%   +88.50%  (p=0.000 n=9+10)
Histogram/float/buckets=20/DistinctValuesCount-16          423ns ± 1%     494ns ± 0%   +16.75%  (p=0.000 n=9+10)
Histogram/float/buckets=20/Filter-16                      4.53µs ± 1%    4.49µs ± 1%    -0.96%  (p=0.000 n=10+9)
Histogram/float/buckets=20/ApplySelectivity-16             433ns ± 1%      43ns ± 3%   -90.10%  (p=0.000 n=10+10)
Histogram/float/buckets=200/ValuesCount-16                50.2ns ± 1%    94.4ns ± 1%   +88.13%  (p=0.000 n=9+10)
Histogram/float/buckets=200/DistinctValuesCount-16        4.24µs ± 1%    4.80µs ± 1%   +13.26%  (p=0.000 n=9+10)
Histogram/float/buckets=200/Filter-16                     33.8µs ± 1%    34.1µs ± 5%      ~     (p=0.433 n=9+10)
Histogram/float/buckets=200/ApplySelectivity-16           3.29µs ± 1%    0.05µs ± 4%   -98.63%  (p=0.000 n=8+9)
Histogram/float/buckets=2000/ValuesCount-16                453ns ± 1%     987ns ± 8%  +117.75%  (p=0.000 n=9+10)
Histogram/float/buckets=2000/DistinctValuesCount-16       42.1µs ± 4%    48.7µs ± 4%   +15.64%  (p=0.000 n=9+10)
Histogram/float/buckets=2000/Filter-16                     317µs ± 1%     317µs ± 1%      ~     (p=0.971 n=10+10)
Histogram/float/buckets=2000/ApplySelectivity-16          30.1µs ± 5%     0.0µs ± 1%   -99.86%  (p=0.000 n=10+10)
Histogram/string/buckets=0/ValuesCount-16                 0.47ns ± 2%    0.46ns ± 2%    -1.69%  (p=0.003 n=10+10)
Histogram/string/buckets=0/DistinctValuesCount-16         3.27ns ± 2%    3.12ns ± 4%    -4.49%  (p=0.000 n=10+10)
Histogram/string/buckets=0/Filter-16                      64.8ns ± 0%    63.3ns ± 1%    -2.29%  (p=0.000 n=9+9)
Histogram/string/buckets=0/ApplySelectivity-16            46.3ns ± 1%    42.5ns ± 1%    -8.18%  (p=0.000 n=10+10)
Histogram/string/buckets=2/ValuesCount-16                 1.64ns ± 6%    2.48ns ± 2%   +51.28%  (p=0.000 n=10+9)
Histogram/string/buckets=2/DistinctValuesCount-16         95.6ns ± 1%   106.0ns ± 5%   +10.83%  (p=0.000 n=9+10)
Histogram/string/buckets=2/Filter-16                      1.61µs ± 1%    1.61µs ± 0%      ~     (p=0.643 n=10+9)
Histogram/string/buckets=2/ApplySelectivity-16             120ns ± 2%      43ns ± 1%   -64.64%  (p=0.000 n=10+9)
Histogram/string/buckets=20/ValuesCount-16                5.69ns ± 5%   11.11ns ±10%   +95.21%  (p=0.000 n=9+10)
Histogram/string/buckets=20/DistinctValuesCount-16         961ns ± 1%    1047ns ± 0%    +8.96%  (p=0.000 n=9+9)
Histogram/string/buckets=20/Filter-16                     2.75µs ± 1%    2.84µs ± 5%    +3.61%  (p=0.002 n=9+9)
Histogram/string/buckets=20/ApplySelectivity-16            431ns ± 2%      44ns ± 1%   -89.80%  (p=0.000 n=10+8)
Histogram/string/buckets=200/ValuesCount-16               50.3ns ± 1%    94.5ns ± 2%   +87.84%  (p=0.000 n=9+10)
Histogram/string/buckets=200/DistinctValuesCount-16       9.84µs ± 0%   10.93µs ±11%   +11.10%  (p=0.000 n=9+10)
Histogram/string/buckets=200/Filter-16                    5.55µs ± 0%    5.62µs ± 1%    +1.24%  (p=0.000 n=10+10)
Histogram/string/buckets=200/ApplySelectivity-16          3.31µs ± 0%    0.04µs ± 0%   -98.69%  (p=0.000 n=9+9)
Histogram/string/buckets=2000/ValuesCount-16               474ns ±10%     901ns ± 0%   +90.10%  (p=0.000 n=10+9)
Histogram/string/buckets=2000/DistinctValuesCount-16       111µs ± 7%     115µs ± 6%    +2.90%  (p=0.023 n=10+10)
Histogram/string/buckets=2000/Filter-16                   20.2µs ± 1%    20.4µs ± 6%      ~     (p=0.631 n=10+10)
Histogram/string/buckets=2000/ApplySelectivity-16         29.9µs ± 0%     0.0µs ± 0%   -99.86%  (p=0.000 n=9+9)
Histogram/int[]/buckets=0/ValuesCount-16                  0.49ns ± 3%    0.48ns ± 2%    -2.93%  (p=0.000 n=10+9)
Histogram/int[]/buckets=0/DistinctValuesCount-16          3.42ns ± 6%    3.10ns ± 4%    -9.30%  (p=0.000 n=10+9)
Histogram/int[]/buckets=0/Filter-16                       67.2ns ± 4%    63.4ns ± 1%    -5.59%  (p=0.000 n=10+9)
Histogram/int[]/buckets=0/ApplySelectivity-16             46.2ns ± 1%    42.6ns ± 1%    -7.86%  (p=0.000 n=10+9)
Histogram/int[]/buckets=2/ValuesCount-16                  1.58ns ± 3%    2.47ns ± 1%   +56.45%  (p=0.000 n=9+10)
Histogram/int[]/buckets=2/DistinctValuesCount-16           424ns ± 0%     433ns ± 1%    +2.06%  (p=0.000 n=10+9)
Histogram/int[]/buckets=2/Filter-16                       2.33µs ± 6%    2.24µs ± 1%    -4.15%  (p=0.000 n=10+8)
Histogram/int[]/buckets=2/ApplySelectivity-16              121ns ± 1%      43ns ± 1%   -64.76%  (p=0.000 n=9+10)
Histogram/int[]/buckets=20/ValuesCount-16       [...]

2022-09-22 22:40 UTC, michae2 commented
(This can wait until after stability.)

2022-09-23 01:16 UTC, DrewKimball approved these changes
Nice improvement! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

We've got an extra 4 bytes of padding after the ColumnID in the Histogram struct... I wonder if we could use that somehow?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-:-NCbq9Yo4B3vmJxvJERJ:b-ih6r8l)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @msirek)



<!-- Sent from Reviewable.io -->

2022-09-23 18:00 UTC, msirek requested changes
Very cool!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-:-NCfVC9R1rpTMd4Xb7LQ:b-jdo7t9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/opt/props/histogram.go` line 230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-NCfRTR-3lcNjEDSBZAC:-NCfRTR-3lcNjEDSBZAD:bnrf5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6db9189e95bc9652f4fd1c68ecc1ab56f5c6e643/pkg/sql/opt/props/histogram.go#L230)):*
> ```Go
> 		evalCtx:     h.evalCtx,
> 		col:         h.col,
> 		selectivity: OneSelectivity,
> ```

I believe more than just scans can be filtered, so it may be possible that `h` already has `selectivity` set.  So, we should copy selectivity from `h` into the new `filtered` histogram instead of using `OneSelectivity`.


<!-- Sent from Reviewable.io -->

2022-09-23 22:10 UTC, rytaft reviewed
Nice change! Looks like you have some test failures with different stats, though -- maybe @msirek's suggestion below will help

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-:-NCgOK0F4hpL_dCM-_zE:bt73ohi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)



<!-- Sent from Reviewable.io -->

2022-09-24 00:23 UTC, michae2 reviewed
> We've got an extra 4 bytes of padding after the ColumnID in the Histogram struct... I wonder if we could use that somehow?

I was tempted to make the selectivity a float32 but for now I just moved the ColumnID last in the struct. Maybe the go runtime can use those 4 bytes, depending on alignment of things.

> Looks like you have some test failures with different stats, though -- maybe @msirek's suggestion below will help

Yeah, hopefully it will! I also am expecting some small-magnitude histogram changes due to floating point errors. We'll see.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-:-NCgrVat3vtZqRCK3Emp:b-8tube)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @msirek, and @rytaft)

___
*[`pkg/sql/opt/props/histogram.go` line 230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-NCfRTR-3lcNjEDSBZAC:-NCgrMB57bqBnbaiXql1:b-6m43al) ([raw file](https://github.com/cockroachdb/cockroach/blob/6db9189e95bc9652f4fd1c68ecc1ab56f5c6e643/pkg/sql/opt/props/histogram.go#L230)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I believe more than just scans can be filtered, so it may be possible that `h` already has `selectivity` set.  So, we should copy selectivity from `h` into the new `filtered` histogram instead of using `OneSelectivity`.
</blockquote></details>

Good catch! Thank you! :cold_sweat:


<!-- Sent from Reviewable.io -->

2022-09-27 20:51 UTC, rytaft reviewed
Looks like there is still at least one case where the stats are significantly different than before...

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-:-ND-hoLn4Ax51cTCkUSV:b-gwwmeg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)



<!-- Sent from Reviewable.io -->

2022-10-13 19:11 UTC, mgartner approved these changes
Great idea! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-:-NEHkYiv-8vWhtsVp1LL:b-tpuhzu)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek)



<!-- Sent from Reviewable.io -->

2022-10-13 20:06 UTC, michae2 commented
I'm thinking of backporting this to 22.2.1 or 22.2.2 after letting it bake for a few weeks. Any objections?

2022-10-13 20:39 UTC, mgartner approved these changes
I think that should be fine. I'd almost prefer it to go into 22.2.0, because I think the biggest risk is that it changes query plans, and it's more acceptable to have query plans change in a .0 than in a .1 or .2. But I think it's too late to push in 22.2.0 at this point.

> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-:-NEI3QWj9HMF2jUTQbd7:b-rmborz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @msirek)



<!-- Sent from Reviewable.io -->

2022-10-13 21:02 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-:-NEI9-BMBJTtSTF2ie7B:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @msirek)



<!-- Sent from Reviewable.io -->

2022-10-13 21:29 UTC, michae2 commented
Thanks for the reviews, and the help!

bors r=DrewKimball,mgartner,rytaft

2022-10-13 21:30 UTC, michae2 commented
@msirek do you have any more comments? (Your requested changes are preventing bors'ing.)

2022-10-13 21:32 UTC, msirek approved these changes
No more comments.  <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88526#-:-NEIFgO2A0g01490znkL:bcmxlu3)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 3 stale) (waiting on @michae2)



<!-- Sent from Reviewable.io -->

2022-10-13 22:07 UTC, michae2 commented
TY!

bors r=DrewKimball,mgartner,rytaft,msirek

2022-10-14 01:23 UTC, merged