split: add observability for when load based splitting cannot find a key
cockroachdb/cockroach pull request #88720
Opened 2022-09-26 15:16 UTC by KaiSun314

Previously, there were no metrics or logging in the load-based splitter.

This was inadequate because there is minimal observability into why the load splitter could not find a split key.

To address this, this patch adds metrics and logging to the load splitter, including counter metrics indicating number of times could not find a split key and popular key (>62.5% occurrence) and logging indicating causes for no split key (insufficient counters, imbalance, too many contained).

Release note (ops change): Added observability for when load based splitting cannot find a key to indicate the reasons why the load splitter could not find a split key, enabling us to have more observability and insight to debug why a range is not splitting more easily.

2022-09-26 15:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/88720)
<!-- Reviewable:end -->

2022-09-28 17:55 UTC, kvoli requested changes
> Reviewed 5 of 16 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314 and @kvoli)

___
*[`pkg/kv/kvserver/split/decider.go` line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND3olcEABGTpXd-6xYz:-ND3olcF-Zw79K0njqsE:b7f34xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/decider.go#L175)):*
> ```Go
> 					majorityKeyFrequency := d.mu.splitFinder.MajorityKeyFrequency()
> 					loggedStr := fmt.Sprintf(
> 						"No split key found: insufficient counters = %v, imbalance = %v, too many contained = %v, imbalance and too many contained = %v",
> ```

Can we update to use `%d` instead of `%v`
___
*[`pkg/kv/kvserver/split/decider.go` line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND3osQU5xF7Gndv6Vy2:-ND3osQU5xF7Gndv6Vy3:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/decider.go#L179)):*
> ```Go
> 					if majorityKeyFrequency >= (1+splitKeyThreshold)/2 {
> 						d.loadSplitterMetrics.PopularKeyCount.Inc(1)
> 						loggedStr += fmt.Sprintf(", most popular key occurs in %v%% of samples", majorityKeyFrequency*100)
> ```

Same as above.
___
*[`pkg/kv/kvserver/split/decider.go` line 182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND48FRV8QWFRehoSHTU:-ND48FRV8QWFRehoSHTV:b-e7912l) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/decider.go#L182)):*
> ```Go
> 					}
> 					d.loadSplitterMetrics.NoSplitKeyCount.Inc(1)
> 					log.KvDistribution.Infof(ctx, "%s", loggedStr)
> ```

nit: `log.kvDistribution.Info(...)` rather than `Infof`
___
*[`pkg/kv/kvserver/split/decider_test.go` line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND4BkMx2nLxXI2v-kYX:-ND4BkMx2nLxXI2v-kYY:b-788qim) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/decider_test.go#L410)):*
> ```Go
> }
> 
> func TestMetrics(t *testing.T) {
> ```

Nice testing

nit: `TestDeciderMetrics`
___
*[`pkg/kv/kvserver/split/finder_test.go` line 276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND3pD3n5uieiXypT7YS:-ND3pD3n5uieiXypT7YT:b-g9t7oz) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/finder_test.go#L276)):*
> ```Go
> }
> 
> func TestFinder_NoSplitKeyCause(t *testing.T) {
> ```

nit: drop the _ between parts.
___
*[`pkg/kv/kvserver/split/finder_test.go` line 320 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND4DtxI9n6ZucUkZS37:-ND4DtxI9n6ZucUkZS38:b-k98mdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/finder_test.go#L320)):*
> ```Go
> 	}
> 
> 	testCases := []struct {
> ```

It isn't necessary to add a for loop for a single test case here. Nice test logic.
___
*[`pkg/kv/kvserver/split/finder_test.go` line 339 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND4C-WC-4bnQRq9-FWG:-ND4C-WC-4bnQRq9-FWH:b10602b) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/finder_test.go#L339)):*
> ```Go
> 		}
> 		if imbalance != test.expectedImbalance {
> 			t.Errorf(
> ```

Older tests tend to use `t.Errorf` but newer ones have migrated to use `require.Equal(t, expected, actual, msg, args)`. We should swap it out w/ the newer format.
___
*[`pkg/kv/kvserver/split/finder_test.go` line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND4DPkvEqRvXr2itLo0:-ND4DPkvEqRvXr2itLo1:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/finder_test.go#L356)):*
> ```Go
> }
> 
> func TestFinder_MajorityKeyFrequency(t *testing.T) {
> ```

Same as above.


<!-- Sent from Reviewable.io -->

2022-09-28 19:47 UTC, KaiSun314 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/split/decider.go` line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND3olcEABGTpXd-6xYz:-ND4cAw_9Fd_UMnH5gkk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/decider.go#L175)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Can we update to use `%d` instead of `%v`
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split/decider.go` line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND3osQU5xF7Gndv6Vy2:-ND4cHDQ2CYaK841JLG_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/decider.go#L179)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split/decider.go` line 182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND48FRV8QWFRehoSHTU:-ND4cKM04j4yidJzfaRU:bt9x8x1) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/decider.go#L182)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: `log.kvDistribution.Info(...)` rather than `Infof`
</blockquote></details>

Unfortunately doing log.KvDistribution.Info(ctx, loggedStr) gives the build error:

compilepkg: nogo: errors found by nogo during build-time code analysis:
pkg/kv/kvserver/split/decider.go:182:29: recordLocked(): message argument is not a constant expression\n++Tip: use YourFuncf("descriptive prefix %s", ...) or list new formatting wrappers in pkg/testutils/lint/passes/fmtsafe/functions.go. (fmtsafe)
Target //pkg/cmd/cockroach:cockroach failed to build
___
*[`pkg/kv/kvserver/split/decider_test.go` line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND4BkMx2nLxXI2v-kYX:-ND4c_Y231IDOYvl377l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/decider_test.go#L410)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Nice testing

nit: `TestDeciderMetrics`
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split/finder_test.go` line 320 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND4DtxI9n6ZucUkZS37:-ND4cdCP-x89l6OhDKkR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/finder_test.go#L320)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It isn't necessary to add a for loop for a single test case here. Nice test logic.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split/finder_test.go` line 339 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND4C-WC-4bnQRq9-FWG:-ND4ckH04a5DsoP3-oyn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/finder_test.go#L339)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Older tests tend to use `t.Errorf` but newer ones have migrated to use `require.Equal(t, expected, actual, msg, args)`. We should swap it out w/ the newer format.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split/finder_test.go` line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-ND4DPkvEqRvXr2itLo0:-ND4couu0yBl1VVFPbrv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e7ff8be33dbfff3d5a9a990fc11e51e9e592ca/pkg/kv/kvserver/split/finder_test.go#L356)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-05 13:45 UTC, kvoli approved these changes
Nice patch. <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

Great to have this obs in.

> Reviewed 2 of 16 files at r1, 2 of 7 files at r3, 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88720#-:-NDcNtFU6BvcAZV2tD6q:b-d5vhmx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)



<!-- Sent from Reviewable.io -->

2022-10-05 14:18 UTC, KaiSun314 commented
bors r=kvoli

2022-10-05 16:42 UTC, merged