server: fix panic when SendKVBatch is used with invalid req
cockroachdb/cockroach pull request #88828
Opened 2022-09-27 16:46 UTC by aliher1911

This commit fixes a panic in admin.SendKVBatch when `debug send-kv-request` command is called with invalid request.

Release note: None

Fixes #88826

2022-09-27 16:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/88828)
<!-- Reviewable:end -->

2022-09-27 16:58 UTC, knz requested changes
Can you change this to:
```go
if br == nil {
   br = &roachpb.BatchResponse{}
}
```
then keep the lines below.

That's because the client command expects the error to be inside the response `Error` field.

2022-09-27 17:15 UTC, knz approved these changes

2022-09-27 17:16 UTC, aliher1911 commented
Interesting. I run with initial change and the error was exposed as an error making cli return error.
I'll run that with the new version, but I guess it'll just return a json with failed response rather than return error code in cli.

2022-09-27 17:16 UTC, aliher1911 commented
Thanks for looking at it!

2022-09-28 07:37 UTC, aliher1911 commented
bors r=tbg

2022-09-28 08:31 UTC, merged