sql: add SHOW CREATE INDEXES and SHOW CREATE SECONDARY INDEXES
cockroachdb/cockroach pull request #88861
Opened 2022-09-27 21:02 UTC by andyyang890

This patch adds the SQL statements `SHOW CREATE INDEXES FROM ...` and `SHOW CREATE SECONDARY INDEXES FROM ...`, which users can use to generate easy-to-read `CREATE INDEX` statements for a table's (secondary) indexes.

Release note (sql change): Users can now use `SHOW CREATE INDEXES FROM ...` and `SHOW CREATE SECONDARY INDEXES FROM ...` to generate easy-to-read `CREATE INDEX` statements for a table's (secondary) indexes.

2022-09-27 21:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/88861)
<!-- Reviewable:end -->

2022-09-28 18:52 UTC, ZhouXing19 approved these changes
Excellent work, <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> ! I just added nit comments. 
Tiny nit: we can add a one-line test in `pkg/sql/parser/testdata/show`. You can generate the test output with `./dev test pkg/sql/parser -f TestParseDatadriven --rewrite`. 

@rafiss could you finalize the review?

> Reviewed 6 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-:-ND4QWHU1KAhCCW87HPT:bltm5d3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890 and @ZhouXing19)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4R87ABNHRzh042The):*
nit: `SHOW CREATE INDEXES FROM <table_name>` may be more concrete.
___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4RDgX8CqalgI0TVVe):*
ditto
___
*[`pkg/sql/crdb_internal.go` line 2914 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4ORt7DpV7-6Vh1MrC:-ND4ORt7DpV7-6Vh1MrD:bc16n9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d2bd2a06dbfdcbca4e949676edc880d5f7f42d/pkg/sql/crdb_internal.go#L2914)):*
> ```Go
> 		secondary := tree.NewDString("secondary")
> 		// Pre-allocate slice of size equal to number of cols in schema.
> 		row := make(tree.Datums, 12)
> ```

I wonder if we must declare the size here. Eventually, we will append all columns to `row`. Also, previously the number of columns was larger than 7, but it didn't break anything.

So can we just do `var row []tree.Datums` here? If later we'd like to add more columns to `crdb_internal.table_indexes`, we won't bother to change the size.
___
*[`pkg/sql/crdb_internal.go` line 2916 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND3uwRA2BiochHLcJys:-ND3uwRA2BiochHLcJyt:bidtllp) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d2bd2a06dbfdcbca4e949676edc880d5f7f42d/pkg/sql/crdb_internal.go#L2916)):*
> ```Go
> 		row := make(tree.Datums, 12)
> 		worker := func(ctx context.Context, pusher rowPusher) error {
> 			a := &tree.DatumAlloc{}
> ```

nit: maybe a more informative var name?
___
*[`pkg/sql/crdb_internal.go` line 2959 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4Pm271Pd1MnVNYNDL:-ND4Pm271Pd1MnVNYNDM:b-bgku2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d2bd2a06dbfdcbca4e949676edc880d5f7f42d/pkg/sql/crdb_internal.go#L2959)):*
> ```Go
> 							return err
> 						}
> 						createStmt, err := catformat.IndexForDisplay(
> ```

nit: rename `createStmt` to `createIndexStmt`


<!-- Sent from Reviewable.io -->

2022-09-28 20:15 UTC, andyyang890 reviewed
TFTR! Fixed all the things you mentioned.

> Dismissed @ZhouXing19 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-:-ND4itYR-Qq-hxssWDrA:b-u75hd9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4R87ABNHRzh042The):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: `SHOW CREATE INDEXES FROM <table_name>` may be more concrete.
</blockquote></details>

Done.
___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4RDgX8CqalgI0TVVe):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal.go` line 2914 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4ORt7DpV7-6Vh1MrC:-ND4ipHK0AK243ENWY2P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d2bd2a06dbfdcbca4e949676edc880d5f7f42d/pkg/sql/crdb_internal.go#L2914)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

I wonder if we must declare the size here. Eventually, we will append all columns to `row`. Also, previously the number of columns was larger than 7, but it didn't break anything.

So can we just do `var row []tree.Datums` here? If later we'd like to add more columns to `crdb_internal.table_indexes`, we won't bother to change the size.
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal.go` line 2916 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND3uwRA2BiochHLcJys:-ND4iqko3S272n51DNim:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d2bd2a06dbfdcbca4e949676edc880d5f7f42d/pkg/sql/crdb_internal.go#L2916)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: maybe a more informative var name?
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal.go` line 2959 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4Pm271Pd1MnVNYNDL:-ND4irs-4QuTmwlUFMY3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32d2bd2a06dbfdcbca4e949676edc880d5f7f42d/pkg/sql/crdb_internal.go#L2959)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: rename `createStmt` to `createIndexStmt`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-28 20:26 UTC, rafiss requested changes
just some small nits, nice job!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-:-ND4loOcBEYmjPtJulrr:b-m3euwt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @rafiss, and @ZhouXing19)

___
*[`pkg/sql/delegate/show_table.go` line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4j_PSA-L5pB9b4_gj:-ND4j_PSA-L5pB9b4_gk:b3dlmy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4ebe08508e2ce08da501cd16609138af1c859b/pkg/sql/delegate/show_table.go#L110)):*
> ```Go
> 	showCreateIndexesQuery := `
> SELECT
> 	create_statement
> ```

for `show create table <t>` we have two result columns -- table name, and statement.

i think we should have the name here too
___
*[`pkg/sql/delegate/show_table.go` line 115 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4jMf2Di3vE3adAOJY:-ND4jMf35GVQuawMa4sd:b-qn87hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4ebe08508e2ce08da501cd16609138af1c859b/pkg/sql/delegate/show_table.go#L115)):*
> ```Go
> 
> 	switch n.Mode {
> 	case tree.ShowCreateModeIndexes:
> ```

consider adding a comment here that says this case is intentionally empty
___
*[`pkg/sql/logictest/testdata/logic_test/show_create_indexes` line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4lh0XBWzSBAAnNmyI:-ND4lh0YAFUJcVqYb1J8:b-65i6j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4ebe08508e2ce08da501cd16609138af1c859b/pkg/sql/logictest/testdata/logic_test/show_create_indexes#L1)):*
> ```
> statement ok
> ```

feel free to drop these tests in the existing `show_create` file. it would avoid having to generate the new code


<!-- Sent from Reviewable.io -->

2022-09-28 22:02 UTC, andyyang890 reviewed
> Dismissed @ZhouXing19 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88861)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[`pkg/sql/delegate/show_table.go` line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4j_PSA-L5pB9b4_gj:-ND56W0F8XTKRA6_Z-o2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4ebe08508e2ce08da501cd16609138af1c859b/pkg/sql/delegate/show_table.go#L110)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

for `show create table <t>` we have two result columns -- table name, and statement.

i think we should have the name here too
</blockquote></details>

Done.
___
*[`pkg/sql/delegate/show_table.go` line 115 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4jMf2Di3vE3adAOJY:-ND56_c256seSW-FI6as:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4ebe08508e2ce08da501cd16609138af1c859b/pkg/sql/delegate/show_table.go#L115)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

consider adding a comment here that says this case is intentionally empty
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/show_create_indexes` line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4lh0XBWzSBAAnNmyI:-ND56b7r1O-_uRZ8ct7I:b3cfowz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4ebe08508e2ce08da501cd16609138af1c859b/pkg/sql/logictest/testdata/logic_test/show_create_indexes#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

feel free to drop these tests in the existing `show_create` file. it would avoid having to generate the new code
</blockquote></details>

Done. I think it's unavoidable for the ccl logictests because there isn't really a good file to drop it into there.


<!-- Sent from Reviewable.io -->

2022-09-29 15:47 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88861)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @rafiss, and @ZhouXing19)

___
*[`pkg/sql/logictest/testdata/logic_test/show_create_indexes` line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4lh0XBWzSBAAnNmyI:-ND8rrFk9N13ghmtzivA:b29u38j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4ebe08508e2ce08da501cd16609138af1c859b/pkg/sql/logictest/testdata/logic_test/show_create_indexes#L1)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Done. I think it's unavoidable for the ccl logictests because there isn't really a good file to drop it into there.
</blockquote></details>

you only need extra files in pkg/ccl to test CCL-specific functionality, like for example follower reads. so that file can just be removed


<!-- Sent from Reviewable.io -->

2022-09-29 15:55 UTC, andyyang890 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88861)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[`pkg/sql/logictest/testdata/logic_test/show_create_indexes` line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4lh0XBWzSBAAnNmyI:-ND8xBqE7ELAlQxs9-gG:b-8gwk1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4ebe08508e2ce08da501cd16609138af1c859b/pkg/sql/logictest/testdata/logic_test/show_create_indexes#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

you only need extra files in pkg/ccl to test CCL-specific functionality, like for example follower reads. so that file can just be removed
</blockquote></details>

I added that file because "PARTITION BY" requires an enterprise license. Is there a way to test it without putting the logic test in the ccl package?


<!-- Sent from Reviewable.io -->

2022-09-29 15:57 UTC, rafiss approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88861)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @rafiss, and @ZhouXing19)

___
*[`pkg/sql/logictest/testdata/logic_test/show_create_indexes` line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/88861#-ND4lh0XBWzSBAAnNmyI:-ND8xhA99ctKM-bzfhR-:bgn5jsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4ebe08508e2ce08da501cd16609138af1c859b/pkg/sql/logictest/testdata/logic_test/show_create_indexes#L1)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

I added that file because "PARTITION BY" requires an enterprise license. Is there a way to test it without putting the logic test in the ccl package?
</blockquote></details>

ah ok, i missed the PARTITION clause. then you're all good!


<!-- Sent from Reviewable.io -->

2022-09-29 17:04 UTC, andyyang890 commented
TFTR!

bors r=ZhouXing19,rafiss

2022-09-29 19:05 UTC, merged