allocatorimpl: Prioritize non-voters in voter additions
cockroachdb/cockroach pull request #89650
Opened 2022-10-10 13:23 UTC by KaiSun314

Previously, when adding a voter via the allocator, we would not prioritize stores with non-voters when selecting candidate stores.

This was inadequate because selecting a store without a non-voter would require sending a snapshot over the WAN in order to add a voter onto that store. On the other hand, selecting a store with a non-voter would only require promoting that non-voter to a voter, no snapshot needs to be sent over the WAN.

To address this, this patch determines if candidate stores have a non-voter replica and prioritize this status when sorting candidate stores (priority lower than balance score, but higher than range count). By prioritizing selecting a store with a non-voter, we can reduce the number of snapshots that need to be sent over the WAN.

Release note (ops change): We prioritized non-voters in voter additions, meaning that when selecting a store to add a voter on (in the allocator), we would prioritize candidate stores that contain a non-voter replica higher. This allows us to reduce the number of snapshots that need to be sent over the WAN.

2022-10-10 13:23 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/89650)
<!-- Reviewable:end -->

2022-10-11 13:46 UTC, kvoli reviewed
Great work on this so far. A few things to add in:

(1) Update the `score` fn to be consistent in ordering values it returns
(2) Add some testing to exercise the example we want this to work in, then a few where there's too great imbalance or other reasons where a non-voter exists for promotion but we don't want to promote it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-:-NE6HUd7DPGMnNJXcxis:b5cx88f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 693 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-NE6FW9uDLROZZgxZRe5:-NE6FW9v8m6Rkv5HERL8:b-eejvhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e862d2581469c3550d82f130c88017b1f51136/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L693)):*
> ```Go
> 		return -(1 + (float64(o.balanceScore-c.balanceScore))/10.0)
> 	}
> 	if c.hasNonVoter != o.hasNonVoter {
> ```

The above scores are strictly ordered. The 10 is out of order with the other scores returned:

```
...
converges (+-)[2,3]
balance (+-)[1,2]
nonVoter +-10
```

This is fine for calling `Less` which is used to sort them and for allocation.

However it does matter for rebalancing, which won't be in this patch here but we should keep consistent to avoid confusion in the future.

https://github.com/cockroachdb/cockroach/blob/20e55fcca7651472a6b112900c413e67b270979f/pkg/roachpb/data.pb.go#L285-L288

We can adjust the other values up and slot this one in below. or just return a value in the range (+-)[0,1).


<!-- Sent from Reviewable.io -->

2022-10-11 21:59 UTC, KaiSun314 reviewed
(1) Done - added a bunch of unit 0s
(2) Done - added 3 unit tests:
1. One store with non-voter and range count 516 + one store with voter and range count 480 - make sure allocator selects store with the non-voter despite higher range count
2. Stores with non-voter and range count > 475 + one store with voter and range count < 475 (resulting in different balance scores) - make sure allocator selects store with the voter due to higher balance score
3. One store with non-voter and range count 516 but does not satisfy voter constraint + one store with voter and range count 480 that satisfies voter constraint - make sure allocator selects store with voter that satisfies voter constraint

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-:-NE80QQiBdOTPYJAN2LT:bnhz7yn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 693 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-NE6FW9uDLROZZgxZRe5:-NE80Nm6B-GQr8lqY3no:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9e862d2581469c3550d82f130c88017b1f51136/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L693)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

The above scores are strictly ordered. The 10 is out of order with the other scores returned:

```
...
converges (+-)[2,3]
balance (+-)[1,2]
nonVoter +-10
```

This is fine for calling `Less` which is used to sort them and for allocation.

However it does matter for rebalancing, which won't be in this patch here but we should keep consistent to avoid confusion in the future.

https://github.com/cockroachdb/cockroach/blob/20e55fcca7651472a6b112900c413e67b270979f/pkg/roachpb/data.pb.go#L285-L288

We can adjust the other values up and slot this one in below. or just return a value in the range (+-)[0,1).

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-17 23:25 UTC, kvoli requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go` line 8186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-NEcEumM3PDG4fLFidhj:-NEcEumM3PDG4fLFidhk:brvmh1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/08176bfd21d445b422dc3a9a3dab01e95b98005a/pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go#L8186)):*
> ```Go
> }
> 
> func TestNonVoterPrioritizationInVoterAdditions(t *testing.T) {
> ```

Could you add the test scenario descriptions that you mentioned, above each test case to make this easier to parse for future readers.

```go
// NB: ... is overfull despite having a nonvoter, we select store X.
```
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go` line 8280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-NEcFLvu09yU__aJAfkx:-NEcFLvu09yU__aJAfky:bz8qxfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/08176bfd21d445b422dc3a9a3dab01e95b98005a/pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go#L8280)):*
> ```Go
> 			},
> 			expectedTargetAllocate: roachpb.ReplicationTarget{NodeID: 4, StoreID: 4},
> 		},
> ```

Could you add in the test case from the issue.

Perhaps in a TestMultiiRegion... , just so we can cover our cases.

```
region 1: voter (leaseholder), voter, voter
region 2: non-voter
region 3: non-voter
```


<!-- Sent from Reviewable.io -->

2022-10-25 15:53 UTC, KaiSun314 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go` line 8186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-NEcEumM3PDG4fLFidhj:-NFEq9pY7bATiqeqlSh4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/08176bfd21d445b422dc3a9a3dab01e95b98005a/pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go#L8186)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you add the test scenario descriptions that you mentioned, above each test case to make this easier to parse for future readers.

```go
// NB: ... is overfull despite having a nonvoter, we select store X.
```
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go` line 8280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-NEcFLvu09yU__aJAfkx:-NFEqDL5ACk2M3pM1vqv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/08176bfd21d445b422dc3a9a3dab01e95b98005a/pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go#L8280)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you add in the test case from the issue.

Perhaps in a TestMultiiRegion... , just so we can cover our cases.

```
region 1: voter (leaseholder), voter, voter
region 2: non-voter
region 3: non-voter
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-25 15:54 UTC, KaiSun314 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go` line 8280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-NEcFLvu09yU__aJAfkx:-NFEqNM_2nYTz_BC_gzz:bicnn56) ([raw file](https://github.com/cockroachdb/cockroach/blob/08176bfd21d445b422dc3a9a3dab01e95b98005a/pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go#L8280)):*
<details><summary><i>Previously, KaiSun314 (Kai Sun) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In replicate_queue_test.go


<!-- Sent from Reviewable.io -->

2022-10-25 18:38 UTC, kvoli approved these changes
small nits otherwise great stuff

<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 3 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-:-NFFQxye1j7ax9SfwPeP:bnkboor)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/replicate_queue_test.go` line 2015 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-NFFKxBe6qrGOp87Eb2z:-NFFKxBe6qrGOp87Eb3-:blgyad7) ([raw file](https://github.com/cockroachdb/cockroach/blob/178631c9484661d4ff53377d735221b936ff25ea/pkg/kv/kvserver/replicate_queue_test.go#L2015)):*
> ```Go
> 			Knobs: base.TestingKnobs{
> 				SpanConfig: &spanconfig.TestingKnobs{
> 					ConfigureScratchRange: true,
> ```

nit: I don't think you need this field anymore.
___
*[`pkg/kv/kvserver/replicate_queue_test.go` line 2033 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-NFFIGZD2bTcqA-RAobp:-NFFIGZD2bTcqA-RAobq:bc9kuuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/178631c9484661d4ff53377d735221b936ff25ea/pkg/kv/kvserver/replicate_queue_test.go#L2033)):*
> ```Go
> 	// predictable behaviour when the allocator ranks stores using balance score.
> 	_, err := db.Exec(
> 		"ALTER DATABASE system CONFIGURE ZONE USING num_replicas = 7, num_voters = 7",
> ```

nit: Add a local function

```go
initConstraintFn := func(count int, range string) { ... }
initConstraintFn(7, "system")
...
initConstraintFn(7, "default")
```


<!-- Sent from Reviewable.io -->

2022-10-27 15:32 UTC, KaiSun314 reviewed
Thank you for the review Austen!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89650#-:-NFP3RRsDRlf2BYFGGLm:b-s4bt6r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)



<!-- Sent from Reviewable.io -->

2022-10-27 18:05 UTC, KaiSun314 commented
bors r=kvoli

2022-10-28 01:55 UTC, KaiSun314 commented
bors r=kvoli

2022-10-28 04:18 UTC, KaiSun314 commented
bors r=kvoli

2022-10-28 05:14 UTC, merged