kv,rangefeed: integrate catchup scans with elastic cpu
cockroachdb/cockroach pull request #89709
Opened 2022-10-11 00:46 UTC by irfansharif

Part of #65957. First commit is from #89656.

Changefeed backfills, given their scan-heavy nature, can be fairly
CPU-intensive. In #89656 we introduced a roachtest demonstrating the
latency impact backfills can have on a moderately CPU-saturated cluster.
Similar to what we saw for backups, this CPU heavy nature can elevate Go
scheduling latencies which in turn translates to foreground latency
impact. This commit integrates rangefeed catchup scan with the elastic
CPU limiter we introduced in #86638; this is one of two optional halves
of changefeed backfills. The second half is the initial scan -- scan
requests issued over some keyspan as of some timestamp. For that we
simply rely on the existing slots mechanism but now setting a lower
priority bit (BulkNormalPri). Experimentally we observed that during
initial scans the encoding routines in changefeedccl are the most
impactful CPU-wise, something #89589 can help with. We leave admission
integration of parallel worker goroutines to future work.

Unlike export requests rangefeed catchup scans are non-premptible. The
rangefeed RPC is a streaming one, and the catchup scan is done during
stream setup. So we don't have resumption tokens to propagate up to the
caller like we did for backups. We still want CPU-bound work going
through admission control to only use 100ms of CPU time, to exercise
better control over scheduling latencies. To that end, we introduce the
following component used within the rangefeed catchup iterator.

    // Pacer is used in tight loops (CPU-bound) for non-premptible
    // elastic work. Callers are expected to invoke Pace() every loop
    // iteration and Close() once done. Internally this type integrates
    // with elastic CPU work queue, acquiring tokens for the CPU work
    // being done, and blocking if tokens are unavailable. This allows
    // for a form of cooperative scheduling with elastic CPU granters.
    type Pacer struct
    func (p *Pacer) Pace(ctx context.Context) error { ... }
    func (p *Pacer) Close() { ... }

Release note: None

2022-10-11 00:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/89709)
<!-- Reviewable:end -->

2022-10-11 03:12 UTC, irfansharif commented
Before (lack of throughput isolation, very poor latency isolation):

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/10536690/194988491-6412bbf1-8aeb-47f8-872c-b577c023aa64.png">


After (throughput isolation, ok latency isolation):

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/10536690/194988332-53625c40-db04-4210-8c43-a924fc8dd381.png">

2022-10-11 07:46 UTC, erikgrinaker reviewed
Very promising!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-:-NE5-Y1gA0QDeWi9mXoy:bmsclta)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @jayshrivastava, and @miretskiy)

___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 334 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE4whyf6G2q0c0lPjKD:-NE4whyf6G2q0c0lPjKE:b8vr5b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/kv/kvserver/rangefeed/catchup_scan.go#L334)):*
> ```Go
> 		}
> 
> 		if err := i.pacer.Pace(ctx); err != nil {
> ```

This should be lifted to the start of the loop, to account for the `continue` statements. In particular, the `!withDiff` fast path.


<!-- Sent from Reviewable.io -->

2022-10-11 15:52 UTC, sumeerbhola requested changes
(flushing some comments -- haven't finished reading)

just curious: Is the total number of catchup scans the same in the before and after runs? The time duration for the changefeeds look similar despite the lower cpu being given to the them in the after case. 

> Reviewed 16 of 16 files at r2, 2 of 2 files at r3, 6 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-:-NE6eOyO0Ggjut_kyCH7:brvtn0p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @jayshrivastava, and @miretskiy)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6fLKXDLwsuujuyyGv):*
how will this affect someone who starts using this in v22.2 and then upgrade to v23.1?
___
*[`-- commits` line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6fx-Z9pEiKIlRfKyC):*
Add a reference to https://github.com/cockroachdb/cockroach/issues/88733.
Also, this is something we should consider backporting to v22.2 so worth pulling out into a separate PR/commit.
___
*[`pkg/ccl/changefeedccl/kvfeed/scanner.go` line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6glwoDETp7MQcrVU7:-NE6glwoDETp7MQcrVU8:b-lwucw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/ccl/changefeedccl/kvfeed/scanner.go#L128)):*
> ```Go
> 	knobs TestingKnobs,
> ) error {
> 	txn := p.db.NewTxn(ctx, "changefeed backfill")
> ```

See https://github.com/cockroachdb/cockroach/issues/88733. That was suggesting overriding the priority at txn creation time. What this code is doing is overriding for each batch. The latter may be nicer to others in that the CreateTime is advanced, which means later batches will not out-compete others because their txn started earlier.
This can use a code comment.
___
*[`pkg/ccl/changefeedccl/kvfeed/scanner.go` line 137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6jC7XERttzNE2ZoLv:-NE6jC7XERttzNE2ZoLw:bfo6bw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/ccl/changefeedccl/kvfeed/scanner.go#L137)):*
> ```Go
> 	stopwatchStart := timeutil.Now()
> 	var scanDuration, bufferDuration time.Duration
> 	targetBytesPerScan := changefeedbase.ScanRequestSize.Get(&p.settings.SV)
> ```

changefeed.backfill.scan_request_size of 16MB is too large. Can you add a TODO for cdc folks to reduce the default?
___
*[`pkg/clusterversion/cockroach_versions.go` line 314 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6iawE4HqkZv6-Hajk:-NE6iawE4HqkZv6-Hajl:b-t5jffh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/clusterversion/cockroach_versions.go#L314)):*
> ```Go
> 	// something that was not true in older versions.
> 	//
> 	// TODO(irfansharif): Depends on v22.2 being minted first.
> ```

why do we need a cluster version for this change? This doesn't seem to need cluster-wide coordination.


<!-- Sent from Reviewable.io -->

2022-10-11 17:01 UTC, irfansharif commented
Experiment data: [rangefeed-catchup-scan.zip](https://github.com/cockroachdb/cockroach/files/9758249/rangefeed-catchup-scan.zip). Follow instructions here to visualize things locally: https://github.com/cockroachdb/cockroach/pull/89656#issuecomment-1273408225. +cc @jayshrivastava.

2022-10-11 17:19 UTC, sumeerbhola reviewed
> Reviewed 10 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @jayshrivastava, and @miretskiy)

___
*[`pkg/kv/kvserver/store.go` line 3106 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6liB7ALvSJAfOwGRY:-NE6liB7ALvSJAfOwGRZ:b7swolm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/kv/kvserver/store.go#L3106)):*
> ```Go
> 	tenID, _ := repl.TenantID()
> 	if pacer := s.cfg.KVAdmissionController.AdmitRangefeedRequest(tenID, args); pacer != nil {
> 		ctx = kvadmission.ContextWithPacer(ctx, pacer)
> ```

nit: what is the motivation for this context dance instead of passing the pacer directly as a parameter? Unlike the normal BatchRequest execution path there is only 1 caller along this code path.


<!-- Sent from Reviewable.io -->

2022-10-17 20:12 UTC, irfansharif commented
I'm going to pull out the version-gate related things and backport it to 22.2 since it's not out yet, to give ourselves the flexibility to use this integration in 22.2 clusters under supervision. Similar to what we're planning to do for backups. I'm still not planning to backport the actual integration itself, not until it's had a few more weeks to bake, but including the right AdmissionHeaders in older versions seems fine.

2022-10-24 19:16 UTC, irfansharif reviewed
PTAL; system-internal rangefeed scans now use a higher-than-BulkNormalPri for catch-up scan work. Sorry for taking long, I got distracted.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-:-NFAPcp68g1TgzDoIYuI:b-yf3zaz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @miretskiy, and @sumeerbhola)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6fLKXDLwsuujuyyGv):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how will this affect someone who starts using this in v22.2 and then upgrade to v23.1?
</blockquote></details>

I'm going to backport this cluster setting name change commit to 22.2.0+. I'm going to backport the whole commit carving out the kvadmission package to make subsequent backports easier.
___
*[`-- commits` line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6fx-Z9pEiKIlRfKyC):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Add a reference to https://github.com/cockroachdb/cockroach/issues/88733.
Also, this is something we should consider backporting to v22.2 so worth pulling out into a separate PR/commit.
</blockquote></details>

Added the reference. Pulled it into its own commit/PR in #90093 and backported to 22.2 in #90102 + #90103.
___
*[`pkg/ccl/changefeedccl/changefeedbase/settings.go` line 111 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE3VUMMmBaVlL4afVAP-r4-111:-NF9itVwEjoBfFXDkqOB:bo85mqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/ccl/changefeedccl/changefeedbase/settings.go#L111)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

minor nit:maybe  exclude this file from this pr
(but if you feel strongly, keep it)
</blockquote></details>

Meh, our perilous CI+bors cycles have taught me to be less particular about small offences to commit/PR hygiene.
___
*[`pkg/ccl/changefeedccl/kvfeed/scanner.go` line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6glwoDETp7MQcrVU7:-NF9jFx924UC5W_hx-kp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/ccl/changefeedccl/kvfeed/scanner.go#L128)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

See https://github.com/cockroachdb/cockroach/issues/88733. That was suggesting overriding the priority at txn creation time. What this code is doing is overriding for each batch. The latter may be nicer to others in that the CreateTime is advanced, which means later batches will not out-compete others because their txn started earlier.
This can use a code comment.
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/kvfeed/scanner.go` line 137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6jC7XERttzNE2ZoLv:-NF9mV-NBM0CSksc0Y2z:bhnyw14) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/ccl/changefeedccl/kvfeed/scanner.go#L137)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

changefeed.backfill.scan_request_size of 16MB is too large. Can you add a TODO for cdc folks to reduce the default?
</blockquote></details>

Added: 

```
// TODO(cdc,yevgeniy,irfansharif): 16 MiB is too large for "elastic" work such
// as this; reduce the default. Evaluate this as part of #90089.
```
___
*[`pkg/ccl/changefeedccl/kvfeed/scanner.go` line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE3VUMMmBaVlL4afVAR-r4-145:-NF9nKht5TCX5-jgmzaM:bunycm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/ccl/changefeedccl/kvfeed/scanner.go#L145)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

How would you feel about adding an option to kvfeed library to control this priority? Do we ever envision if e.g. some system table  scanners may want to run at an elevated priority?
</blockquote></details>

This is a good suggestion. I did something slightly different -- instead of treating all rangefeed catchup scans homogeneously, now system-internal rangefeeds (we use this all over the place in span configs, settings watchers, etc.) use into a higher priority; PTAL at uses + plumbing for `rangefeed.WithSystemTablePriority`. As for using a configurable pri at this level -- we might want to if we introduce notions of "higher priority" changefeeds, perhaps over more important data or for more important apps. I'll leave that as a TODO.
___
*[`pkg/clusterversion/cockroach_versions.go` line 314 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6iawE4HqkZv6-Hajk:-NFABxbB77NG1s4zQyVZ:b988vme) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/clusterversion/cockroach_versions.go#L314)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why do we need a cluster version for this change? This doesn't seem to need cluster-wide coordination.
</blockquote></details>

Was mistaken, we were just populating new headers/fields that would get ignored on older versions. Removed. Also the populating of headers was merged in #90093.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go` line 513 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE3VUMMmBaVlL4afVAU-r4-513:-NFAE1VIA497AZO-WyLT:bu4gc2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L513)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Same comment as on rangefeed library -- consider making it an option
to support system rangefeeds running with higher priority if needed.
</blockquote></details>

Done, great suggestion.
___
*[`pkg/kv/kvserver/store.go` line 3106 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE6liB7ALvSJAfOwGRY:-NFAF4MID7Z17hyXKghs:b-8gsi1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/kv/kvserver/store.go#L3106)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: what is the motivation for this context dance instead of passing the pacer directly as a parameter? Unlike the normal BatchRequest execution path there is only 1 caller along this code path.
</blockquote></details>

No good reason, done. I thought maybe this Pacer fellow could end up being used in other places but that's too speculative.
___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 334 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE4whyf6G2q0c0lPjKD:-NFAECbg0S0CsAW7Eknf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/kv/kvserver/rangefeed/catchup_scan.go#L334)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This should be lifted to the start of the loop, to account for the `continue` statements. In particular, the `!withDiff` fast path.
</blockquote></details>

Done.



_Code quote:_
```Go
	if err := i.pacer.Pace(ctx); err != nil {
```
___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 335 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE3VUMMmBaVlL4afVAX-r4-335:-NFAEtQv5fMM7M5SmdjZ:bdsj90d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/kv/kvserver/rangefeed/catchup_scan.go#L335)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

How is this error handled and propagated through rangefeed stack?
Is this error ever bubbled up to the client (dist_sender_rangefeed)? If so, it needs to be handled - presum [...]

2022-10-25 10:03 UTC, miretskiy reviewed
> Reviewed 7 of 33 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89709)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-10-28 12:43 UTC, sumeerbhola requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 29 of 33 files at r5, 5 of 7 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-:-NFTbPC9BnjR5VUTGfn3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif, @jayshrivastava, and @miretskiy)

___
*[`pkg/ccl/changefeedccl/kvfeed/scanner.go` line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE3VUMMmBaVlL4afVAR-r4-145:-NFTUfaI66K2aZfA9Y2e:b-aln1gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/ccl/changefeedccl/kvfeed/scanner.go#L145)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This is a good suggestion. I did something slightly different -- instead of treating all rangefeed catchup scans homogeneously, now system-internal rangefeeds (we use this all over the place in span configs, settings watchers, etc.) use into a higher priority; PTAL at uses + plumbing for `rangefeed.WithSystemTablePriority`. As for using a configurable pri at this level -- we might want to if we introduce notions of "higher priority" changefeeds, perhaps over more important data or for more important apps. I'll leave that as a TODO.
</blockquote></details>

Slightly confused here. The catchup scan for the system-internal rangefeeds is using a higher priority, but not the initial scan for the corresponding changefeeds. Is there something about these system-internal ones that makes the latter not very important?
___
*[`pkg/clusterversion/cockroach_versions.go` line 304 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NFTUB6B14IS94MBPITr:-NFTUB6B14IS94MBPITs:b-jo7ba0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8fc390ac97bfe5ce2735151180d4bd85652e2da/pkg/clusterversion/cockroach_versions.go#L304)):*
> ```Go
> 	// supported in cloud storage and KMS.
> 	SupportAssumeRoleAuth
> ```

nit: stray diff here due to the empty line being removed
___
*[`pkg/ts/catalog/chart_catalog.go` line 3551 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NFTXSYlDbOHMzeszTSr:-NFTXSYlDbOHMzeszTSs:bumpt7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f113452148e59c7f393d8aa5fdce830cbac88b4/pkg/ts/catalog/chart_catalog.go#L3551)):*
> ```Go
> 					"admission.admitted.sql-sql-response.locking",
> 					"admission.admitted.sql-sql-response.normal",
> 					"admission.errored.elastic-cpu.normal",
> ```

I must have missed something here. Why is normal priority getting classified as elastic traffic?


<!-- Sent from Reviewable.io -->

2022-10-28 14:24 UTC, irfansharif reviewed
@sumeerbhola, you might've hit the wrong reviewable button. bors will no longer let me merge unless the green stamp goes through -- it doesn't recognize the LGTM sticker.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-:-NFTxub6A0YQU-jKyrzL:bc7p6lz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jayshrivastava, @miretskiy, and @sumeerbhola)

___
*[`pkg/ccl/changefeedccl/kvfeed/scanner.go` line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE3VUMMmBaVlL4afVAR-r4-145:-NFTwK5T8CsXwImmXsYy:bs1g6ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/ccl/changefeedccl/kvfeed/scanner.go#L145)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Slightly confused here. The catchup scan for the system-internal rangefeeds is using a higher priority, but not the initial scan for the corresponding changefeeds. Is there something about these system-internal ones that makes the latter not very important?
</blockquote></details>

We don't use changefeeds for system tables within CRDB, we use rangefeeds directly. Which is why only the catch up scan priority was bumped. Some of these system tables also use initial scans, using the following:

https://github.com/cockroachdb/cockroach/blob/c1e4c935dd64437f543fac7d9e353f6091849268/pkg/kv/kvclient/rangefeed/scanner.go#L24-L30

But they're just scan requests that don't use BulkNormalPri. The code for the scans above bottom out here, where it doesn't look like we specify an AC header. I've been assuming that means it gets treated as NormalPri/doesn't bypass AC -- is that true? 

https://github.com/cockroachdb/cockroach/blob/9f113452148e59c7f393d8aa5fdce830cbac88b4/pkg/kv/kvclient/rangefeed/db_adapter.go#L181-L192
___
*[`pkg/clusterversion/cockroach_versions.go` line 304 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NFTUB6B14IS94MBPITr:-NFTxRGgEd96Ube-gS33:b-2tnt2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8fc390ac97bfe5ce2735151180d4bd85652e2da/pkg/clusterversion/cockroach_versions.go#L304)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: stray diff here due to the empty line being removed
</blockquote></details>

Was on purpose, none of the named versions above have line breaks between them.
___
*[`pkg/ts/catalog/chart_catalog.go` line 3551 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NFTXSYlDbOHMzeszTSr:-NFTxa317sCXTMsN1nvD:b-6u7odu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f113452148e59c7f393d8aa5fdce830cbac88b4/pkg/ts/catalog/chart_catalog.go#L3551)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I must have missed something here. Why is normal priority getting classified as elastic traffic?
</blockquote></details>

That's not what's happening, what's happening is that we can now have normal pri requests wait in the elastic-cpu wait queue. So there are two priority classes now, bulk-normal and normal. The normal pri elastic-cpu work is what originates from system table rangefeed catchup scans.


<!-- Sent from Reviewable.io -->

2022-10-28 16:38 UTC, sumeerbhola requested changes
> Reviewed 1 of 16 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89709)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif, @jayshrivastava, and @miretskiy)

___
*[`pkg/ccl/changefeedccl/kvfeed/scanner.go` line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE3VUMMmBaVlL4afVAR-r4-145:-NFUPdEvEvRUBzmubaxW:bkxggu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/ccl/changefeedccl/kvfeed/scanner.go#L145)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

We don't use changefeeds for system tables within CRDB, we use rangefeeds directly. Which is why only the catch up scan priority was bumped. Some of these system tables also use initial scans, using the following:

https://github.com/cockroachdb/cockroach/blob/c1e4c935dd64437f543fac7d9e353f6091849268/pkg/kv/kvclient/rangefeed/scanner.go#L24-L30

But they're just scan requests that don't use BulkNormalPri. The code for the scans above bottom out here, where it doesn't look like we specify an AC header. I've been assuming that means it gets treated as NormalPri/doesn't bypass AC -- is that true? 

https://github.com/cockroachdb/cockroach/blob/9f113452148e59c7f393d8aa5fdce830cbac88b4/pkg/kv/kvclient/rangefeed/db_adapter.go#L181-L192
</blockquote></details>

That `dbc.db.Txn()` method is doing
```
	return db.TxnWithAdmissionControl(
		ctx, roachpb.AdmissionHeader_OTHER, admissionpb.NormalPri, retryable)
```
so it will bypass admission control because of OTHER.
___
*[`pkg/ts/catalog/chart_catalog.go` line 3551 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NFTXSYlDbOHMzeszTSr:-NFUPu09D0WKVArxnhg0:b-liishc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f113452148e59c7f393d8aa5fdce830cbac88b4/pkg/ts/catalog/chart_catalog.go#L3551)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

That's not what's happening, what's happening is that we can now have normal pri requests wait in the elastic-cpu wait queue. So there are two priority classes now, bulk-normal and normal. The normal pri elastic-cpu work is what originates from system table rangefeed catchup scans.
</blockquote></details>

Oh yes, it is because we are explicitly integrating with the elastic-cpu in AdmitRangefeedRequest by using elasticCPUWorkQueue.
This may be ok-ish to merge, but I should have picked up on this oddity earlier (or maybe I didn't because until the latest revision all rangefeeds were using bulk priority? I have forgotten part of the PR history). One could argue that normal-pri rangefeed requests should not be using this elastic work queue and instead they should be using a "pacer" that looks the same from the outside but tells them to stop after they have consumed 100ms, and then returns the cpu slot (since normal and higher priorities use the slot mechanism) and queues again for a cpu slot. That is, the part of the pacing we still want to use is to submit to admission again after doing 100ms of work.
Thoughts?


<!-- Sent from Reviewable.io -->

2022-11-02 18:16 UTC, irfansharif reviewed
PTAL. Want to merge this soon-ish after recent discussions with @jayshrivastava who wants to make use of this Pacer library up in changefeed code where we decode rows 1-by-1 one.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-:-NFtY3285zrG8YPEDyMF:b-78vg3f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jayshrivastava, @miretskiy, and @sumeerbhola)

___
*[`pkg/ccl/changefeedccl/kvfeed/scanner.go` line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NE3VUMMmBaVlL4afVAR-r4-145:-NFtTd3Z3aoYssuGpDlc:b-cd2rb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de437be6ee8358a5fad30cb5a69d35e751951e6/pkg/ccl/changefeedccl/kvfeed/scanner.go#L145)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

That `dbc.db.Txn()` method is doing
```
	return db.TxnWithAdmissionControl(
		ctx, roachpb.AdmissionHeader_OTHER, admissionpb.NormalPri, retryable)
```
so it will bypass admission control because of OTHER.
</blockquote></details>

Brilliant, shoudn't have just assumed (frequent occurrence like you've seen). Made these rangefeed catch up scans opt into AC, I think they should, and for the ones declared over system tables specify NormalPri (for everything else use BulkNormalPri). Amended the last commit -- PTAL.
___
*[`pkg/ts/catalog/chart_catalog.go` line 3551 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NFTXSYlDbOHMzeszTSr:-NFtXQd63wWxdhkOCLVu:bei3mib) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f113452148e59c7f393d8aa5fdce830cbac88b4/pkg/ts/catalog/chart_catalog.go#L3551)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Oh yes, it is because we are explicitly integrating with the elastic-cpu in AdmitRangefeedRequest by using elasticCPUWorkQueue.
This may be ok-ish to merge, but I should have picked up on this oddity earlier (or maybe I didn't because until the latest revision all rangefeeds were using bulk priority? I have forgotten part of the PR history). One could argue that normal-pri rangefeed requests should not be using this elastic work queue and instead they should be using a "pacer" that looks the same from the outside but tells them to stop after they have consumed 100ms, and then returns the cpu slot (since normal and higher priorities use the slot mechanism) and queues again for a cpu slot. That is, the part of the pacing we still want to use is to submit to admission again after doing 100ms of work.
Thoughts?
</blockquote></details>

This current form I think is fine for now, especially considering in light of thread above that these catch up scans (both for user-defined rangefeeds and system-defined ones) were previously bypassing AC altogether which I think was a gap. I like the idea of introduce a Pacer that instead makes use of the slot mechanism for the reasons you mention, but this case here specifically is not compelling I think. I could be wrong. I want to re-visit if this becomes a problem. My reasoning is mostly to do with experimental intuition that we might not be decreasing slot count well enough given it's built atop the runnable-g's-per-p measure, which can be insensitive relative to more direct forms of measured scheduling latency.


<!-- Sent from Reviewable.io -->

2022-11-03 16:30 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 16 files at r9, 13 of 17 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-:-NFyK-Rn0tBOE9ocy468:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif, @jayshrivastava, and @miretskiy)

___
*[`pkg/kv/db.go` line 895 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NFyCkI35WNG7GFnYdz8:-NFyCkI35WNG7GFnYdz9:bxrkq8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f960408b2223ca563e9dcdd5431a84b3358fced4/pkg/kv/db.go#L895)):*
> ```Go
> // the other variant (TxnWithAdmissionControl) the default, or maybe rename this
> // to be more explicit (TxnWithoutAdmissionControl) so new callers have to be
> // conscious about what they want.
> ```

+1 to TxnWithoutAdmissionControl
___
*[`pkg/ts/catalog/chart_catalog.go` line 3551 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/89709#-NFTXSYlDbOHMzeszTSr:-NFyE4af3MRkZXEQNR0a:b-4q55d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f113452148e59c7f393d8aa5fdce830cbac88b4/pkg/ts/catalog/chart_catalog.go#L3551)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This current form I think is fine for now, especially considering in light of thread above that these catch up scans (both for user-defined rangefeeds and system-defined ones) were previously bypassing AC altogether which I think was a gap. I like the idea of introduce a Pacer that instead makes use of the slot mechanism for the reasons you mention, but this case here specifically is not compelling I think. I could be wrong. I want to re-visit if this becomes a problem. My reasoning is mostly to do with experimental intuition that we might not be decreasing slot count well enough given it's built atop the runnable-g's-per-p measure, which can be insensitive relative to more direct forms of measured scheduling latency.
</blockquote></details>


I agree that it is likely that the total slots will stay too large, and then this control will become ineffective.


<!-- Sent from Reviewable.io -->

2022-11-04 00:31 UTC, irfansharif commented
bors r+

2022-11-04 03:11 UTC, merged

2022-11-04 21:04 UTC, irfansharif commented
I'm just going to backport it, but not to the .0 point. In 22.2 this machinery is all switched off by default anyway. If the next few weeks of baking time surface anything specific to this catchup scan integration, we can quickly fix and backport those too.

blathers backport 22.2