kvserver: ensure follower reads correctly synchronize with splits
cockroachdb/cockroach pull request #89886
Opened 2022-10-13 02:07 UTC by arulajmani

This patch fixes a bug in how follower reads are synchronized with the application of concurrent split operations. Reads on the leaseholder are serialized with concurrent split operations by latching. However, splits are simply applied on the follower, and as such, don't go through latching like they do on the leaseholder. Previously, this could lead to invalid reads in cases where the range split and the RHS was removed after the range descriptor's bounds were checked but before a storage snapshot was acquired.

This patch fixes this hazard by checking the range bounds after acquiring the storage snapshot (in addition to before, like we used to prior to this change). It also adds a couple of tests -- one exercising the exact scenario described in the associated issue and another that runs concurrent split/read operations without tightly controlling the synchronization between them.

Fixes #67016

Release note (bug fix): fixes a rare bug where concurrent follower read/split operations could lead to invalid read results.

2022-10-13 02:07 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/89886)
<!-- Reviewable:end -->

2022-10-13 02:15 UTC, arulajmani commented
I haven't removed the `readOnlyCmdMu` in this PR -- I'm planning on doing it in a quick followup given @nvanbenschoten's comment https://github.com/cockroachdb/cockroach/issues/67016#issuecomment-1162382866.

2022-10-15 19:57 UTC, aayushshah15 commented
*[`pkg/kv/kvserver/replica.go` line 1483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NESD2RhDaoz6BAPuUjp:-NESD2RhDaoz6BAPuUjq:b-4zezk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica.go#L1483)):*
> ```Go
> 		return err
> 	}
> 	if err := r.checkSpanInRangeRLocked(ctx, rSpan); err != nil {
> ```

For my understanding, do we still need to have the same bounds check before we acquire the storage snapshot after this change? Why?


<!-- Sent from Reviewable.io -->

2022-10-15 21:22 UTC, aayushshah15 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89886)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_test.go` line 13932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NESW7D109evQhS0ITQL:-NESW7D109evQhS0ITQM:b-8ep29k) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica_test.go#L13932)):*
> ```Go
> // We include subtests for both follower reads and reads served from the
> // leaseholder.
> func TestRangeSplitRacesWithRead(t *testing.T) {
> ```

I wasn't able to get this test to fail with the following diff (ran into this when I was playing around with something else):

```
diff --git a/pkg/kv/kvserver/replica.go b/pkg/kv/kvserver/replica.go
index ebc115cf46..99b707b3c8 100644
--- a/pkg/kv/kvserver/replica.go
+++ b/pkg/kv/kvserver/replica.go
@@ -1456,6 +1456,8 @@ func (r *Replica) checkExecutionCanProceedBeforeStorageSnapshot(
 		// defer.
 		postRUnlock = func() { r.maybeExtendLeaseAsync(ctx, st) }
 	}
+
+	time.Sleep(100 * time.Millisecond)
 	return st, nil
 }
 
@@ -1476,13 +1478,13 @@ func (r *Replica) checkExecutionCanProceedAfterStorageSnapshot(
 	// meaningful in the context of follower reads. This is because latches on
 	// followers don't provide the synchronization with concurrent splits like
 	// they do on leaseholders.
-	rSpan, err := keys.Range(ba.Requests)
-	if err != nil {
-		return err
-	}
-	if err := r.checkSpanInRangeRLocked(ctx, rSpan); err != nil {
-		return err
-	}
+	// rSpan, err := keys.Range(ba.Requests)
+	// if err != nil {
+	// 	return err
+	// }
+	// if err := r.checkSpanInRangeRLocked(ctx, rSpan); err != nil {
+	// 	return err
+	// }
 
 	// NB: For read-only requests, the GC threshold check is performed after the
 	// state of the storage engine has been pinned by the iterator. This is

```

The diff comments the fix out and adds a sleep right after the range-bounds have been checked before the storage snapshot is pinned. Could we understand why that is? Perhaps something is wrong w/ the diff above or with the test, but I can't tell what.
___
*[`pkg/kv/kvserver/replica_test.go` line 14154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NESEYc-DvSgn1X8MNhd:-NESEYc-DvSgn1X8MNhe:blkpk7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica_test.go#L14154)):*
> ```Go
> 
> 	split := func() {
> 		<-startSplit
> ```

nit: Let's cap the time the test will spend waiting here with something like the following:
```
select {
  case <-startSplit:
  case <-time.After(5 * time.Second):
    panic('timed out waiting for read to block')
}
```


<!-- Sent from Reviewable.io -->

2022-10-20 11:16 UTC, nvanbenschoten reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89886)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @arulajmani)

___
*[`pkg/kv/kvserver/replica.go` line 1479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NEp3MNX43U7NQdUJcQ0:-NEp3MNY7vWkyq045pI6:bnquvf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica.go#L1479)):*
> ```Go
> 	// followers don't provide the synchronization with concurrent splits like
> 	// they do on leaseholders.
> 	rSpan, err := keys.Range(ba.Requests)
> ```

Let's lift this above the `r.mu.RLock()`, like we do in `checkExecutionCanProceedBeforeStorageSnapshot`.
___
*[`pkg/kv/kvserver/replica.go` line 1483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NESD2RhDaoz6BAPuUjp:-NEp3Vqn7FmGjNOMBFXE:b-q2h744) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica.go#L1483)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

For my understanding, do we still need to have the same bounds check before we acquire the storage snapshot after this change? Why?
</blockquote></details>

I think we still probably want it so that we check for `RangeKeyMismatchError`s before checking for the leaseholder. I wonder if any tests would notice the change.
___
*[`pkg/kv/kvserver/replica_test.go` line 13932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NESW7D109evQhS0ITQL:-NEp4_tC6a-5MNiDoqgr:b-imvsmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica_test.go#L13932)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I wasn't able to get this test to fail with the following diff (ran into this when I was playing around with something else):

```
diff --git a/pkg/kv/kvserver/replica.go b/pkg/kv/kvserver/replica.go
index ebc115cf46..99b707b3c8 100644
--- a/pkg/kv/kvserver/replica.go
+++ b/pkg/kv/kvserver/replica.go
@@ -1456,6 +1456,8 @@ func (r *Replica) checkExecutionCanProceedBeforeStorageSnapshot(
 		// defer.
 		postRUnlock = func() { r.maybeExtendLeaseAsync(ctx, st) }
 	}
+
+	time.Sleep(100 * time.Millisecond)
 	return st, nil
 }
 
@@ -1476,13 +1478,13 @@ func (r *Replica) checkExecutionCanProceedAfterStorageSnapshot(
 	// meaningful in the context of follower reads. This is because latches on
 	// followers don't provide the synchronization with concurrent splits like
 	// they do on leaseholders.
-	rSpan, err := keys.Range(ba.Requests)
-	if err != nil {
-		return err
-	}
-	if err := r.checkSpanInRangeRLocked(ctx, rSpan); err != nil {
-		return err
-	}
+	// rSpan, err := keys.Range(ba.Requests)
+	// if err != nil {
+	// 	return err
+	// }
+	// if err := r.checkSpanInRangeRLocked(ctx, rSpan); err != nil {
+	// 	return err
+	// }
 
 	// NB: For read-only requests, the GC threshold check is performed after the
 	// state of the storage engine has been pinned by the iterator. This is

```

The diff comments the fix out and adds a sleep right after the range-bounds have been checked before the storage snapshot is pinned. Could we understand why that is? Perhaps something is wrong w/ the diff above or with the test, but I can't tell what.
</blockquote></details>

@aayushshah15's verification is valuable to pin down. We should know what it would take to break this test so that we know that we're testing something real and we know exactly what code is providing the fix.
___
*[`pkg/kv/kvserver/replica_test.go` line 13978 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NEp4unADiCplI163Nx9:-NEp4unADiCplI163NxA:b1bx69x) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica_test.go#L13978)):*
> ```Go
> 
> 		// If the test wants to read from a follower, drop the closed timestamp
> 		// duration and then wait until the follower can serve requests at ts1.
> ```

nit: Bounded-staleness reads on the follower might allow us to get away with not performing this wait.
___
*[`pkg/kv/kvserver/replica_test.go` line 14060 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NEp5gWL4QgmuS7FTqrv:-NEp5gWL4QgmuS7FTqrw:bxwcsg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica_test.go#L14060)):*
> ```Go
> // - Follower read resumes. The expectation is for the follower read to fail
> // with a RangeKeyMismatchError.
> func TestRangeSplitAndRHSRemovalRacesWithFollowerRead(t *testing.T) {
> ```

Similar to @aayushshah15's point above, this test fails if you comment out the new call to `checkSpanInRangeRLocked`, right?


<!-- Sent from Reviewable.io -->

2022-10-20 20:42 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89886)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[`pkg/kv/kvserver/replica.go` line 1483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NESD2RhDaoz6BAPuUjp:-NEr1Mih0xGhbx8Ohi07:busdy5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica.go#L1483)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we still probably want it so that we check for `RangeKeyMismatchError`s before checking for the leaseholder. I wonder if any tests would notice the change.
</blockquote></details>

I only had it around so we'd return early, but the `RangeKeyMismatchError` before leaseholder check makes sense. Nothing in `kvserver` or `kvcoord` broke when I removed it though. 
___
*[`pkg/kv/kvserver/replica_test.go` line 13932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NESW7D109evQhS0ITQL:-NEqz0I56pTPyLfxKTLD:b-ytcsxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica_test.go#L13932)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@aayushshah15's verification is valuable to pin down. We should know what it would take to break this test so that we know that we're testing something real and we know exactly what code is providing the fix.
</blockquote></details>

In your diff we're sleeping without releasing the replica mu. To see the bug in action, we need both the split and change replicas to apply on the RHS (after the checks have completed but before the snapshot is pinned). [The application of change replicas also acquires the replica mu](https://github.com/cockroachdb/cockroach/blob/89058d53769dad1d7f01c63afbc8e4722b2c3a35/pkg/kv/kvserver/replica_application_state_machine.go#L872-L879), so I don't think the diff does what we're intending here. Instead, if we modify things slightly as below, the test reliably fails:  


```
--- a/pkg/kv/kvserver/replica.go
+++ b/pkg/kv/kvserver/replica.go
@@ -1401,6 +1401,11 @@ func (r *Replica) checkExecutionCanProceedBeforeStorageSnapshot(
                r.mu.RUnlock()
                postRUnlock()
        }()
+       defer func() {
+               if r.store.NodeID() == 2 {
+                       time.Sleep(100 * time.Millisecond)
+               }
+       }()

        // Has the replica been initialized?
        // NB: this should have already been checked in Store.Send, so we don't need
@@ -1481,13 +1486,11 @@ func (r *Replica) checkExecutionCanProceedAfterStorageSnapshot(
        // meaningful in the context of follower reads. This is because latches on
        // followers don't provide the synchronization with concurrent splits like
        // they do on leaseholders.
-       rSpan, err := keys.Range(ba.Requests)
-       if err != nil {
-               return err
-       }
-       if err := r.checkSpanInRangeRLocked(ctx, rSpan); err != nil {
-               return err
-       }
+       //if err := r.checkSpanInRangeRLocked(ctx, rSpan); err != nil {
+       //      return err
+       //}
+
+       _ = rSpan

        // NB: For read-only requests, the GC threshold check is performed after the
        // state of the storage engine has been pinned by the iterator. This is
```

That being said, I wasn't able to get this test to fail without introducing a sleep, which is what prompted the test below which tightly synchronizes things. IMO it's still worth keeping this around. 
___
*[`pkg/kv/kvserver/replica_test.go` line 14060 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-NEp5gWL4QgmuS7FTqrv:-NEq9NbDDIILAv_582Qd:b7jcanz) ([raw file](https://github.com/cockroachdb/cockroach/blob/18dc83703efdfbc584ff8ec299b7139f7e9542fa/pkg/kv/kvserver/replica_test.go#L14060)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Similar to @aayushshah15's point above, this test fails if you comment out the new call to `checkSpanInRangeRLocked`, right?
</blockquote></details>

Yeah, this fails if I comment out my changes to `checkExecutionCanProceedAfterStorageSnapshot`.


<!-- Sent from Reviewable.io -->

2022-10-24 15:20 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89886#-:-NF9_9_O8g4salbADO58:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)



<!-- Sent from Reviewable.io -->

2022-10-24 15:33 UTC, arulajmani commented
TFTRs! Adding a backport label for 22.2 as well. 

bors r=nvanbenschoten

2022-10-24 15:53 UTC, aayushshah15 approved these changes

2022-10-24 15:53 UTC, arulajmani commented
bors r+

2022-10-24 17:01 UTC, merged