roachprod: add InitTarget to Start and Init
cockroachdb/cockroach pull request #90051
Opened 2022-10-17 13:20 UTC by stevendanna

This is a small change that makes it easier to use a single roachprod created cluster to initialise multiple CRDB clusters. The intended use is for cluster to cluster performance roachtests.

In a roachtest, you might use this as follows:

    srcCluster := c.Range(1, 3)
    dstCluster := c.Range(4, 6)

    srcStartOps := option.DefaultStartOpts()
    srcStartOps.RoachprodOpts.InitTarget = 1
    srcClusterSetting := install.MakeClusterSettings(install.SecureOption(true))
    c.Start(ctx, t.L(), srcStartOps, srcClusterSetting, srcCluster)

    dstStartOps := option.DefaultStartOpts()
    dstStartOps.RoachprodOpts.InitTarget = 4
    dstClusterSetting := install.MakeClusterSettings(install.SecureOption(true))
    c.Start(ctx, t.L(), dstStartOps, dstClusterSetting, dstCluster)

You can also use this feature using the roachprod command line with the `--init-target` option.

Release note: None

2022-10-17 13:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/90051)
<!-- Reviewable:end -->

2022-10-17 22:14 UTC, renatolabs approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Ideally we'd provide a higher level API for this, but this is good to me as it improves the current experience. Better multi-cluster management is tracked in #79305.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90051#-:-NEc-4dG6iLVp6xlECJ9:bhgyjr8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @stevendanna)

___
*[`pkg/roachprod/install/cockroach.go` line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90051#-NEbzeGYAOZpMQdoWMPM:-NEbzeGYAOZpMQdoWMPN:b-1afqls) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bbbcbb642811441048668fb5d00845681e4c619/pkg/roachprod/install/cockroach.go#L136)):*
> ```Go
> }
> 
> func (so StartOpts) GetInitTarget() Node {
> ```

Given `StartOpts` created via the command line already set the default and the same applies to roachtests that use `DefaultStartOpts`, do we really need this function?

(Also, the linter is complaining about missing documentation)


<!-- Sent from Reviewable.io -->

2022-10-18 09:40 UTC, herkolategan reviewed
The change looks good to me, but we probably need to keep the linter happy (and add docs for `GetInitTarget`) as @renatolabs mentioned, before proceeding.

> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90051#-:-NEeSKnyAlG1rulajHRM:b-n4giny)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260 and @stevendanna)



<!-- Sent from Reviewable.io -->

2022-10-18 09:42 UTC, herkolategan requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90051)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260 and @stevendanna)



<!-- Sent from Reviewable.io -->

2022-10-26 13:23 UTC, herkolategan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90051#-:-NFJSa9N8mD2nE4AfhA1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @smg260 and @stevendanna)



<!-- Sent from Reviewable.io -->

2022-10-26 13:24 UTC, herkolategan approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90051)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @smg260 and @stevendanna)



<!-- Sent from Reviewable.io -->

2022-10-27 12:00 UTC, stevendanna commented
TFTR!

bors r=herkolategan

2022-10-27 12:54 UTC, merged