sql: disallow star expressions in UDF bodies
cockroachdb/cockroach pull request #90085
Opened 2022-10-17 19:52 UTC by mgartner

Fixes #86070

Release note (sql change): Star expressions, e.g., `SELECT * FROM ...` are no longer allowed in statements in user-defined functions. They were allowed in early betas of v22.2 from v22.2.0-beta.1 to v22.2.0-beta.4, but have been disallowed because they do not behave correctly. Issue #90080 tracks re-enabling star expressions in UDFs.

2022-10-17 19:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/90085)
<!-- Reviewable:end -->

2022-10-17 20:00 UTC, rytaft requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90085#-:-NEbX2ch8FnXrpDsj8l3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/views` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90085#-NEbX8LiDjlCDIxd6WQj:-NEbX8LiDjlCDIxd6WQk:b6f9vzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6213eaa9a95e91d3cabd478fa6624cbcb1ae0e50/pkg/sql/logictest/testdata/logic_test/views#L50)):*
> ```
> 
> statement error pgcode 42703 column \"j\" does not exist
> CREATE VIEW err AS SELECT a FROM t WHERE a = j
> ```

Are these tests related to this change? (They are fine, just wondering...)


<!-- Sent from Reviewable.io -->

2022-10-17 20:01 UTC, rytaft approved these changes

2022-10-17 20:14 UTC, mgartner commented
*[`pkg/sql/logictest/testdata/logic_test/views` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90085#-NEbX8LiDjlCDIxd6WQj:-NEb_D02Do_NUNqxMo9S:b9rah90) ([raw file](https://github.com/cockroachdb/cockroach/blob/6213eaa9a95e91d3cabd478fa6624cbcb1ae0e50/pkg/sql/logictest/testdata/logic_test/views#L50)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Are these tests related to this change? (They are fine, just wondering...)
</blockquote></details>

Oops, forgot to mention this in the commit message - fixed. I ran into a confusing error message with views that is now fixed too.


<!-- Sent from Reviewable.io -->

2022-10-17 20:42 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90085#-:-NEbfcOIA4TSSGCr4zP-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)



<!-- Sent from Reviewable.io -->

2022-10-18 15:08 UTC, chengxiong-ruan approved these changes
LGTM! Thanks for working on this.

2022-10-18 16:48 UTC, mgartner commented
TFTRs!

bors r+

2022-10-18 18:06 UTC, merged