sql: add implicit_txn column to insights execution
cockroachdb/cockroach pull request #90100
Opened 2022-10-17 22:00 UTC by maryliag

This commit adds a new column `implicit_txn` (boolean) to:
- `crdb_internal.cluster_execution_insights`
- `crdb_internal.node_execution_insights`

Part Of #87750

Release note (sql change): Adds a new column `implicit_txn` (boolean) to `crdb_internal.cluster_execution_insights` and `crdb_internal.node_execution_insights`

2022-10-17 22:01 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/90100)
<!-- Reviewable:end -->

2022-10-18 12:23 UTC, j82w approved these changes
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90100#-NEf1Cug8MI_oj550Tm_:-NEf1Cug8MI_oj550Tma:bd6rxvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6def792eab71c3fbcb34b0147b7c8657fe7d0681/pkg/sql/sqlstats/insights/integration/insights_test.go#L109)):*
> ```Go
> 		var fullScan bool
> 		var implicitTxn bool
> 		err = row.Scan(&query, &status, &startInsights, &endInsights, &fullScan, &implicitTxn)
> ```

Verify that the implicitTxn value is correct.  The priority validation below has both implicit and explicit transaction which would allow both scenarios to be validated.


<!-- Sent from Reviewable.io -->

2022-10-18 13:51 UTC, matthewtodd requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`pkg/sql/sqlstats/insights/insights.proto` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90100#-NEfMA7oDzpbIC7adoG4:-NEfMA7oDzpbIC7adoG5:bu8ux3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6def792eab71c3fbcb34b0147b7c8657fe7d0681/pkg/sql/sqlstats/insights/insights.proto#L102)):*
> ```protobuf
>   google.protobuf.Duration contention = 18 [(gogoproto.stdduration) = true];
>   repeated string index_recommendations = 19;
>   bool implicit_txn = 20;
> ```

Thanks, @maryliag! Modeling-wise, I think this information belongs on the `Transaction`, not the `Statement`, yeah?


<!-- Sent from Reviewable.io -->

2022-10-18 14:00 UTC, matthewtodd requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`pkg/sql/sqlstats/insights/insights.proto` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90100#-NEfMA7oDzpbIC7adoG4:-NEfO2fX113nVOkO2O4M:bjx6yr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6def792eab71c3fbcb34b0147b7c8657fe7d0681/pkg/sql/sqlstats/insights/insights.proto#L102)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Thanks, @maryliag! Modeling-wise, I think this information belongs on the `Transaction`, not the `Statement`, yeah?
</blockquote></details>

Looks like you have `ImplicitTxn` available on `RecordedTxnStats` ready to use in [the call to ObserveTransaction](https://github.com/cockroachdb/cockroach/blob/9edf2c84e2c75858aa50e90c6bc87453e1a80451/pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go#L315-L318).


<!-- Sent from Reviewable.io -->

2022-10-18 14:03 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/insights.proto` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90100#-NEfMA7oDzpbIC7adoG4:-NEfO-3M4clErU2ker3g:beiexa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6def792eab71c3fbcb34b0147b7c8657fe7d0681/pkg/sql/sqlstats/insights/insights.proto#L102)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Looks like you have `ImplicitTxn` available on `RecordedTxnStats` ready to use in [the call to ObserveTransaction](https://github.com/cockroachdb/cockroach/blob/9edf2c84e2c75858aa50e90c6bc87453e1a80451/pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go#L315-L318).
</blockquote></details>

This is the information to say if the statement was part of an implicit or explicit transaction, so it's part of the `Statement`.  I need this value on the statement level so I can generate the link to the details page, that consists of `implicitValue/statementFingerprintID`. 
What are you suggesting when looking at the table, to get the value to use on the UI?
___
*[`pkg/sql/sqlstats/insights/integration/insights_test.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90100#-NEf1Cug8MI_oj550Tm_:-NEfOrqS63z4Xbu4jQHA:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/6def792eab71c3fbcb34b0147b7c8657fe7d0681/pkg/sql/sqlstats/insights/integration/insights_test.go#L109)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Verify that the implicitTxn value is correct.  The priority validation below has both implicit and explicit transaction which would allow both scenarios to be validated.
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2022-10-18 14:34 UTC, matthewtodd reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`pkg/sql/sqlstats/insights/insights.proto` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90100#-NEfMA7oDzpbIC7adoG4:-NEfVp1V36UccB-U40vL:b-8re1y9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6def792eab71c3fbcb34b0147b7c8657fe7d0681/pkg/sql/sqlstats/insights/insights.proto#L102)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

This is the information to say if the statement was part of an implicit or explicit transaction, so it's part of the `Statement`.  I need this value on the statement level so I can generate the link to the details page, that consists of `implicitValue/statementFingerprintID`. 
What are you suggesting when looking at the table, to get the value to use on the UI?
</blockquote></details>

Talked in person, the table is good! Will move the `implicit` property from the `Statement` message to the `Transaction` message.


<!-- Sent from Reviewable.io -->

2022-10-18 14:41 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/insights.proto` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90100#-NEfMA7oDzpbIC7adoG4:-NEfXjxG6UbnJ3FjVZ0o:bce1i65) ([raw file](https://github.com/cockroachdb/cockroach/blob/6def792eab71c3fbcb34b0147b7c8657fe7d0681/pkg/sql/sqlstats/insights/insights.proto#L102)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Talked in person, the table is good! Will move the `implicit` property from the `Statement` message to the `Transaction` message.
</blockquote></details>

Changes done!


<!-- Sent from Reviewable.io -->

2022-10-18 15:24 UTC, matthewtodd approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/sqlstats/insights/insights.proto` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90100#-NEfMA7oDzpbIC7adoG4:-NEfgThu7NnUHWJsww6O:b-9755fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6def792eab71c3fbcb34b0147b7c8657fe7d0681/pkg/sql/sqlstats/insights/insights.proto#L102)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Changes done!
</blockquote></details>

Thank you!


<!-- Sent from Reviewable.io -->

2022-10-18 15:55 UTC, maryliag commented
TFTR!
bors r+

2022-10-18 17:18 UTC, merged