sql,*: rework plan hooks to type check separately from execution
cockroachdb/cockroach pull request #90254
Opened 2022-10-19 17:07 UTC by ajwerner

Prior to this change, plan hooks would be invokved twice, once during prepare and again during execution. At prepare time, the placeholder values are not known, but, critically, the placeholders were being type-checked. This type checking informs the sql layer how to interpret the placeholder values when we are trying to bind them. Importantly, the sql layer does not ever use the `planNode` produced via the `PlanHookRowFn` returned from the planning invocation.

The above dance meant that these plan hooks had quite a bit of complexity to eagerly type check but lazily evaluate expressions passed in via the statement. This complexity became a problem more recently: one cannot and should not access many planner data structures from the row func because such functions can, theoretically, run concurrently and these data structures are not thread safe.

Note that the above problem is not commonly a real problem. Most plan hook statements don't permit concurrency and those than do, via, say, `UNION ALL` don't commonly get executed in such a setting. In some ways, the real reason for this change is to unwind some unneeded complexity and clarify the bounds of what one can do in a plan hook.

The big change which unearthed the problem is that we now support privileges on external URLs. These URLs may be provided via placeholders or expressions. If we couldn't access the expressions until we were in the row fn, then we'd be at risk of performing privilege checking concurrently, which is not safe.

One thing that this commit does is introduce a new package `evalexpr` with helpers for type checking. It is so named because I'd like to also remove the methods from the `PlanHookState` which we now use for expr evaluation and place them in this new package. I don't love the name.

Fixes #88385

Release note: None

2022-10-19 17:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/90254)
<!-- Reviewable:end -->

2022-10-19 21:20 UTC, ajwerner commented
I will rename `evalexpr` to `exprutil`

2022-10-19 22:51 UTC, dt approved these changes
Looked though the backup changes and looks great; none of our hook plan statements are expected to be prepare-once-execute-repeatedly, so just doing all our work in exec makes sense to me, with a super-minimal type-check-only prep phase. Doing permission/auth checks at exec makes sense for hook plans since some of the permissions we check are based on the _values_ of bound parameters (e.g. the URI to which one is backing up) to overall this looks sane to me.

2022-10-20 04:57 UTC, ajwerner reviewed
Alright, I cleaned this up. Should be RFAL.

2022-10-20 04:57 UTC, ajwerner commented on pkg/ccl/backupccl/backup_test.go
> +	findJobQuery := `SELECT job_id FROM [SHOW JOBS] WHERE description LIKE '%RESTORE DATABASE%' AND job_type = 'RESTORE' ORDER BY created DESC`
Fixed

2022-10-20 08:57 UTC, stevendanna approved these changes
I like this. seems like it'll also lower some of the psychological overhead of supporting placeholders for more parts of the planHook driven statements.

2022-10-20 11:53 UTC, miretskiy approved these changes

2022-10-20 12:56 UTC, ajwerner commented
@rafiss and @mgartner can I get some some SQL eyes on this?

2022-10-20 15:16 UTC, rafiss requested changes
this looks nice! i think the new package  looks better to use

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-:-NEpvb0lBbSzX0CcESrI:b-u3en7r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @rhu713)

___
*[`pkg/sql/alter_role.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEpqFpa6lR8ZELhh3xT:-NEpqFpa6lR8ZELhh3xU:bgerg9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/alter_role.go#L74)):*
> ```Go
> }
> 
> func asStringOrNull(
> ```

the nested `return func` structure here makes it bit hard to follow. could you add comments, or even making the function return values be named parameters could be sufficient

also, since it seems to be only used for role options, would this make sense to put in the `sql/roleoption` package?
___
*[`pkg/sql/alter_role.go` line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEpuK4lEvi93Bt1cDBO:-NEpuK4lEvi93Bt1cDBP:b-f95psy) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/alter_role.go#L90)):*
> ```Go
> 				return true, "", nil
> 			}
> 			return false, string(*got.(*tree.DString)), nil
> ```

want to use `string(tree.MustBeDString(d))`?
___
*[`pkg/sql/exprutil/evaluator.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEpsZsB-D-UsjiE2vw_:-NEpsZsB-D-UsjiE2vwa:b-8xzlng) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/exprutil/evaluator.go#L35)):*
> ```Go
> 
> // StringArray evaluates expr to a string slice.
> func (e Evaluator) StringArray(ctx context.Context, exprs tree.Exprs) ([]string, error) {
> ```

want to use pointer receivers? i'm just thinking about  avoiding copying the `op` string unnecessarily, which to be fair probably doesn't matter at all
___
*[`pkg/sql/exprutil/evaluator.go` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEptXKh0KJpqPzkLdn9:-NEptXKh0KJpqPzkLdnA:b-f95psy) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/exprutil/evaluator.go#L53)):*
> ```Go
> 		return "", err
> 	}
> 	return string(*d.(*tree.DString)), nil
> ```

want to use `string(tree.MustBeDString(d))`?
___
*[`pkg/sql/exprutil/evaluator.go` line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEptaGn7BkvG1F4fc8U:-NEptaGn7BkvG1F4fc8V:bvjtita) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/exprutil/evaluator.go#L62)):*
> ```Go
> 		return false, err
> 	}
> 	return bool(*d.(*tree.DBool)), nil
> ```

want to use `bool(tree.MustBeDBool(d))`?
___
*[`pkg/sql/exprutil/evaluator.go` line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEpuyqyAYfFKYJnh7qJ:-NEpuyqyAYfFKYJnh7qK:b3xlv0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/exprutil/evaluator.go#L72)):*
> ```Go
> 	for _, opt := range opts {
> 		k := string(opt.Key)
> 		validate, ok := optValidate[k]
> ```

instead of the validation logic below, should this call `optValidate.validate(opt)`


<!-- Sent from Reviewable.io -->

2022-10-20 17:22 UTC, ajwerner reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-:-NEqPO544cP1W_cU_Lzc:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @rafiss, and @rhu713)

___
*[`pkg/sql/alter_role.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEpqFpa6lR8ZELhh3xT:-NEqKQ3M3Je1Z3hLw9Ox:bk6484) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/alter_role.go#L74)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the nested `return func` structure here makes it bit hard to follow. could you add comments, or even making the function return values be named parameters could be sufficient

also, since it seems to be only used for role options, would this make sense to put in the `sql/roleoption` package?
</blockquote></details>

I unwound this mess, moved some of the logic to `exprutil` and also reversed the `roleoption`/`tree` import direction. See what you think. 
___
*[`pkg/sql/alter_role.go` line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEpuK4lEvi93Bt1cDBO:-NEqKY3X4i3yK0eInddl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/alter_role.go#L90)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

want to use `string(tree.MustBeDString(d))`?
</blockquote></details>

Done.
___
*[`pkg/sql/exprutil/evaluator.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEpsZsB-D-UsjiE2vw_:-NEqKYl-EiUUWoWKdSZc:bn0t7m2) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/exprutil/evaluator.go#L35)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

want to use pointer receivers? i'm just thinking about  avoiding copying the `op` string unnecessarily, which to be fair probably doesn't matter at all
</blockquote></details>

Meh it means you can't use it inline. I don't feel like optimizing that right now. 
___
*[`pkg/sql/exprutil/evaluator.go` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEptXKh0KJpqPzkLdn9:-NEqKZigCU1tGzcpBFf2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/exprutil/evaluator.go#L53)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

want to use `string(tree.MustBeDString(d))`?
</blockquote></details>

Done.
___
*[`pkg/sql/exprutil/evaluator.go` line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEptaGn7BkvG1F4fc8U:-NEqK_c-1Gc6wh3zD5cs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/exprutil/evaluator.go#L62)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

want to use `bool(tree.MustBeDBool(d))`?
</blockquote></details>

Done.
___
*[`pkg/sql/exprutil/evaluator.go` line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-NEpuyqyAYfFKYJnh7qJ:-NEqKsjTD124Zf-wKQJA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50e3122b66d67c7fee101102a02580d0259aaa62/pkg/sql/exprutil/evaluator.go#L72)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of the validation logic below, should this call `optValidate.validate(opt)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-20 17:34 UTC, rafiss approved these changes
lgtm! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90254#-:-NEqSQWW44xz3aUKk1cA:b-nzoors)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rhu713)



<!-- Sent from Reviewable.io -->

2022-10-20 18:41 UTC, ajwerner commented
TFTR!

bors r+

2022-10-20 19:40 UTC, merged