ci: add arm64 scripts for tests
cockroachdb/cockroach pull request #90396
Opened 2022-10-20 20:09 UTC by healthy-pod

Note that some non-impl scripts do contain some pre-processing steps so I kept all existing scripts unchanged and pointed arm64 scripts to them. This ensures we don't repeat ourselves.

Release note: None
Epic: CRDB-1463

2022-10-20 20:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/90396)
<!-- Reviewable:end -->

2022-10-21 02:40 UTC, jlinder requested changes
A slight tweak please.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90396#-:-NEsPAFo5UrZRq9I2cXI:bo21yel)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod)

___
*[`build/teamcity/cockroach/ci/tests-aws-linux-arm64/acceptance.sh` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90396#-NEsO6qqE7JMAYJUB5H3:-NEsO6qqE7JMAYJUB5H4:bjnfm4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d0990d5e67b186206611c71e3a667f1f5e49133/build/teamcity/cockroach/ci/tests-aws-linux-arm64/acceptance.sh#L5)):*
> ```Shell
> set -euo pipefail
> 
> build/teamcity/cockroach/ci/tests/acceptance.sh
> ```

Instead of executing the script, let's `source` it. This way, the script is "run" in the same shell as this script is in and so it inherits all the env vars and everything else about the current shell.

```bash
source build/teamcity/cockroach/ci/tests/acceptance.sh
```

This applies to all the other files in this PR too.



_Code quote (from build/teamcity/cockroach/ci/tests-gcp-linux-x86_64-bigvm/unused_test.sh):_
```Shell
build/teamcity/cockroach/ci/tests/unused_test.sh
```


<!-- Sent from Reviewable.io -->

2022-10-21 13:35 UTC, jlinder approved these changes
Great! One last change and then it's good to go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90396#-:-NEuk33O9RB7DnM-PRRb:b-98xzyq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod)

___
*[`build/teamcity/cockroach/ci/tests-gcp-linux-x86_64-bigvm/unused_test.sh` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90396#-NEujdmc7bRB95nJQHyw:-NEujdmc7bRB95nJQHyx:b-83g94w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3a7c54548115f8f127e5f7746d8627742150e3a/build/teamcity/cockroach/ci/tests-gcp-linux-x86_64-bigvm/unused_test.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Can you change the name of this file to `unused_lint.sh` to match the name of the build config in TC?


<!-- Sent from Reviewable.io -->

2022-10-21 18:59 UTC, healthy-pod commented
TFTR!

bors r=jlinder

2022-10-21 19:34 UTC, merged