backupccl: use the backup codec when inspecting spans in the backupManifest
cockroachdb/cockroach pull request #90477
Opened 2022-10-21 19:55 UTC by msbutler

Informs #90475, #90474

Release note (bug fix): previously, during restore planning, the restoring cluster's codec was accidentally used to reason about spans in the backup manifest. When a backup was restored by a different tenant, two bugs described in #90475, #90474 could manifest. This patch fixes these bugs.

2022-10-21 19:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/90477)
<!-- Reviewable:end -->

2022-10-21 20:29 UTC, msbutler commented on pkg/ccl/backupccl/restore_job.go
> -	if len(sqlDescs) != 0 {
i've removed this extra condition around checking if len(sqlDescs) !=0. I'm not really sure what it adds. I think it's to curb against decoding the tenant prefix for a system tenant backup, but I believe `latestBackupManifest.HasTenants()` would prevent decoding a span from a system tenant backup as well.

2022-10-22 00:26 UTC, stevendanna requested changes
Thanks for the quick turn-around on this. Did we find this via the random tenant tests? If not, is there a test we can add here?

2022-10-22 13:58 UTC, msbutler commented
https://github.com/cockroachdb/cockroach/issues/90475 caused the in-progress-imports data driven test to start failing when server taking the backup ran as a tenant and the server running the restore was a system tenant (Or vice versa)

I have not looked into the testing for https://github.com/cockroachdb/cockroach/issues/90474 yet, though i could.

2022-10-23 17:02 UTC, stevendanna approved these changes

2022-10-23 21:50 UTC, msbutler commented
bors r=stevendanna

2022-10-23 22:30 UTC, merged