server: clean up startAttemptUpgrade
cockroachdb/cockroach pull request #91049
Opened 2022-11-01 10:19 UTC by knz

This avoids a log error when `preserve_downgrade_option` is set, and overall simplifies the control flow.

@dt can you help me read the control flow in this patch? I've added a TODO for the one thing I don't understand. Does this need to change?

Fixes #90382. (A regression introduced by #90165)

2022-11-01 10:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/91049)
<!-- Reviewable:end -->

2022-11-01 21:36 UTC, rafiss approved these changes
lgtm, but i left an optional nit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-:-NFp6qdd3hebOilaHyUh:b5cjpp2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[`pkg/server/auto_upgrade.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-NFp6C5v6wiKGf55qNGy:-NFp6C5v6wiKGf55qNGz:b329idk) ([raw file](https://github.com/cockroachdb/cockroach/blob/353c9c23c5626aed201744d731c30b14f27e8760/pkg/server/auto_upgrade.go#L57)):*
> ```Go
> 			// Check if we should upgrade cluster version, keep checking upgrade
> 			// status, or stop attempting upgrade.
> 			if upgradeAlreadyCompleted, autoUpgradeDisabled, err := s.upgradeStatus(ctx); err != nil || autoUpgradeDisabled {
> ```

nit: this might accidentally result in a "nil" log being written in the future, if someone returns autoUpgradeDisabled==true and err==nil.

what if we change this line to:
```
if upgradeAlreadyCompleted, autoUpgradeDisabled, err := s.upgradeStatus(ctx); err != nil {
```

and only do the `autoUpgradeDisabled` check inside the if-body
___
*[`pkg/server/auto_upgrade.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-NFp6UbTEr1Uc9VLcU2n:-NFp6UbTEr1Uc9VLcU2o:b-x4mpia) ([raw file](https://github.com/cockroachdb/cockroach/blob/353c9c23c5626aed201744d731c30b14f27e8760/pkg/server/auto_upgrade.go#L63)):*
> ```Go
> 					log.Errorf(ctx, "failed attempt to upgrade cluster version, error: %v", err)
> 				}
> 				// TODO(knz): do we want to 'continue' here when autoUpgradeDisabled==false?
> ```

i think it's `continue` so that the upgrade keeps getting attempted, and then when `preserve_downgrade_option` is unset, the upgrade will finally go through


<!-- Sent from Reviewable.io -->

2022-11-02 09:40 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91049)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[`pkg/server/auto_upgrade.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-NFp6C5v6wiKGf55qNGy:-NFrhZfq0X5Uvd-v__Y2:b-kc02yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/353c9c23c5626aed201744d731c30b14f27e8760/pkg/server/auto_upgrade.go#L57)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this might accidentally result in a "nil" log being written in the future, if someone returns autoUpgradeDisabled==true and err==nil.

what if we change this line to:
```
if upgradeAlreadyCompleted, autoUpgradeDisabled, err := s.upgradeStatus(ctx); err != nil {
```

and only do the `autoUpgradeDisabled` check inside the if-body
</blockquote></details>

I've done something a bit different. Do you like it?
___
*[`pkg/server/auto_upgrade.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-NFp6UbTEr1Uc9VLcU2n:-NFrfBAI7suGROezY9zL:bvelvqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/353c9c23c5626aed201744d731c30b14f27e8760/pkg/server/auto_upgrade.go#L63)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think it's `continue` so that the upgrade keeps getting attempted, and then when `preserve_downgrade_option` is unset, the upgrade will finally go through
</blockquote></details>

Thanks. Added a comment to clarify.


<!-- Sent from Reviewable.io -->

2022-11-02 15:32 UTC, rafiss requested changes
the new control flow is good! now i just had nits about wording+severity, though i might be wrong

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-:-NFsy8nN6eq4YULAN2zw:bz7uvm1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[`pkg/server/auto_upgrade.go` line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-NFsxnwh30PqsvJFL3dZ:-NFsxnwh30PqsvJFL3d_:bpvi8b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ed7f4cb9ae123730e5e2df46da7a7477c08dd7d/pkg/server/auto_upgrade.go#L69)):*
> ```Go
> 				continue
> 			case upgradeDisabledByConfiguration:
> 				log.Infof(ctx, "auto upgrade is disabled for current version: %s", redact.Safe(clusterVersion))
> ```

something i just thought of: could this log reference the `preserve_downgrade_option` as the reason for why the upgrade is disabled? and it would be more clear to a reader what they're supposed to do to enable the upgrade. if that makes the message too verbose, i'm fine to skip that
___
*[`pkg/server/auto_upgrade.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-NFsxHnF70pbu4VNFzM7:-NFsxHnF70pbu4VNFzM8:b-bo5mkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ed7f4cb9ae123730e5e2df46da7a7477c08dd7d/pkg/server/auto_upgrade.go#L148)):*
> ```Go
> 			newVersion = version
> 		} else if version != newVersion {
> 			return upgradeBlockedDueToError, errors.Newf(
> ```

just noticed - is this one really an error? don't we expect nodes to be on different versions during a normal rolling upgrade?


<!-- Sent from Reviewable.io -->

2022-12-28 11:33 UTC, knz reviewed
Oops, I'm sorry I forgot to update this. It's ready for another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-:-NKNTPf9A7zfhFEX1P6o:bggvxjh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[`pkg/server/auto_upgrade.go` line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-NFsxnwh30PqsvJFL3dZ:-NKNTDqF4_psn4lIJXfb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ed7f4cb9ae123730e5e2df46da7a7477c08dd7d/pkg/server/auto_upgrade.go#L69)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

something i just thought of: could this log reference the `preserve_downgrade_option` as the reason for why the upgrade is disabled? and it would be more clear to a reader what they're supposed to do to enable the upgrade. if that makes the message too verbose, i'm fine to skip that
</blockquote></details>

Done.
___
*[`pkg/server/auto_upgrade.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-NFsxHnF70pbu4VNFzM7:-NKNTC2_4BmZAFVQ3if4:boj1qgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ed7f4cb9ae123730e5e2df46da7a7477c08dd7d/pkg/server/auto_upgrade.go#L148)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just noticed - is this one really an error? don't we expect nodes to be on different versions during a normal rolling upgrade?
</blockquote></details>

Good catch. Done.


<!-- Sent from Reviewable.io -->

2022-12-29 06:15 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91049)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[`pkg/server/auto_upgrade.go` line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-NKRW0i63pohh9KUiM6h:-NKRW0i63pohh9KUiM6i:bzz409) ([raw file](https://github.com/cockroachdb/cockroach/blob/2beadec3154555b6ed6e5da0d47847217113be34/pkg/server/auto_upgrade.go#L118)):*
> ```Go
> 	upgradeDisabledByConfiguration
> 	upgradeBlockedDueToError
> 	upgradeBlockedDueToMixedVersions
> ```

`upgradeBlockedDueToMixedVersions` doesn't seem to be returned anywhere. was it meant to be used on line 162?


<!-- Sent from Reviewable.io -->

2022-12-29 10:00 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91049)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[`pkg/server/auto_upgrade.go` line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91049#-NKRW0i63pohh9KUiM6h:-NKSJoaQ0qqvlInfaHEc:b6az6td) ([raw file](https://github.com/cockroachdb/cockroach/blob/2beadec3154555b6ed6e5da0d47847217113be34/pkg/server/auto_upgrade.go#L118)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

`upgradeBlockedDueToMixedVersions` doesn't seem to be returned anywhere. was it meant to be used on line 162?
</blockquote></details>

:facepalm: 

yes, yes, it was meant so.
Done.


<!-- Sent from Reviewable.io -->

2022-12-29 10:00 UTC, knz commented
(Yay to code reviews.)

2022-12-29 15:16 UTC, rafiss approved these changes
thanks for this improvement!

2022-12-29 15:55 UTC, knz commented
thank you!

bors r=rafiss

2022-12-29 16:47 UTC, merged

2022-12-29 16:58 UTC, knz commented
Backports:
- https://github.com/cockroachdb/cockroach/pull/94422
- https://github.com/cockroachdb/cockroach/pull/90234