server,cachewarm: add a mechanism to fetch sql leases upon startup
cockroachdb/cockroach pull request #91399
Opened 2022-11-07 14:42 UTC by ajwerner

Pre-fetching the leases is important to reduce the overall startup latency. The code, as it stands, is hacky in that it does not have a concurrency limit or a limit on the total number of descriptors it'll fetch. It's off by default, so that's okay.

Release note: None

2022-11-07 14:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/91399)
<!-- Reviewable:end -->

2022-11-07 21:30 UTC, postamar requested changes

2022-11-07 21:30 UTC, postamar commented on pkg/sql/catalog/cachewarm/leases.go
> +	log.Infof(ctx, "pre-fetching descriptor leases")
nit: consider logging the number of descriptor leases we're going to pre-fetch

2022-11-07 21:30 UTC, postamar commented on pkg/sql/catalog/cachewarm/leases.go
> +	})
I know the point of goroutines is that they're cheap etc etc but I'm uneasy about this being unbounded. Can you set a constant cap in this PR? The ranking you mention in your TODO seems simple enough to implement: sort the namespace entries by:
1. parentID == 1 or not
2. parentID == 0 && parentSchemaID == 0 or not
3. by decreasing ID or whatever, I don't know;

and then fire up goroutines only for the first 1000 or so and ignore the rest.

2022-11-07 21:30 UTC, postamar commented on pkg/sql/catalog/internal/catkv/catalog_reader.go
> +	log.Eventf(ctx, "fetching all descriptors and namespace entries")
s/fetching all descriptors and namespace entries/fetching all namespace entries/

2022-11-07 21:30 UTC, postamar commented on pkg/sql/catalog/cachewarm/leases.go
> +package cachewarm
Perhaps `cachewarm` should be a child package of `lease`? No strong feelings.

2022-12-02 14:35 UTC, ajwerner commented
This is no longer needed.

2022-12-02 14:35 UTC, closed without merging