schemachanger: improve panic- and error handling
cockroachdb/cockroach pull request #91411
Opened 2022-11-07 16:28 UTC by postamar

Previously, the declarative schema changer would only recover from runtime errors in certain subsystems like building the targets or planning the execution of operations. Consequently an implementation bug leading to a runtime error in the execution layer would trigger a panic which would not be recovered and which would cause the whole process to crash.

This commit fixes this by introducing a common error handler in the form of scerrors.HandleErrorOrPanic, which recovers from panics, wraps errors, and prints informative log messages in a uniform way, to be used at the top of (or near the top of) the declarative schema changer call stack.

Fixes #91400.

Release note (bug fix): fixed a bug in which panics triggered by certain DDL statements were not properly recovered, leading to the cluster node crashing.

2022-11-07 16:31 UTC, postamar commented
I'm keen for some suggestions on how to improve this. Here's what the log looks like now after crashing the node by doing `ALTER PRIMARY KEY USING COLUMNS (k, k)`:
```
I221107 16:23:10.066992 1888 sql/schemachanger/scerrors/errors.go:41 ⋮ [n1,client=127.0.0.1:50816,user=root] 83  building declarative schema change targets for 
‹ALTER TABLE›
I221107 16:23:10.124597 1888 sql/schemachanger/scerrors/errors.go:62 ⋮ [n1,client=127.0.0.1:50816,user=root] 84  done building declarative schema change targets for ‹ALTER TABLE›
I221107 16:23:10.124972 1888 sql/schemachanger/scerrors/errors.go:41 ⋮ [n1,client=127.0.0.1:50816,user=root] 85  building declarative schema changer plan
I221107 16:23:10.146719 1888 sql/schemachanger/scerrors/errors.go:62 ⋮ [n1,client=127.0.0.1:50816,user=root] 86  done building declarative schema changer plan
I221107 16:23:10.146827 1888 sql/schemachanger/scerrors/errors.go:41 ⋮ [n1,client=127.0.0.1:50816,user=root] 87  executing declarative schema change ‹StatementPhase stage 1 of 1 with 14 MutationType ops› (rollback=false)
I221107 16:23:10.197301 1888 sql/schemachanger/scerrors/errors.go:62 ⋮ [n1,client=127.0.0.1:50816,user=root] 88  done executing declarative schema change ‹StatementPhase stage 1 of 1 with 14 MutationType ops› (rollback=false) with error: executing declarative schema change ‹StatementPhase stage 1 of 1 with 14 MutationType ops› (rollback=false): error executing ‹StatementPhase stage 1 of 1 with 14 MutationType ops›: relation ‹"kv"› (104): index ‹"crdb_internal_index_2_name_placeholder"› contains key column ‹""› with unknown ID 0
```

2022-11-07 16:35 UTC, ajwerner reviewed
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91411)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scerrors/errors.go` line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91411#-NGHwDZe2ozcYNRixxLw:-NGHwDZf-2sK8cGpf5sG:b-10fwai) ([raw file](https://github.com/cockroachdb/cockroach/blob/130c189bae8df8b7ea046796b2576f16a7d3e7a8/pkg/sql/schemachanger/scerrors/errors.go#L34)):*
> ```Go
> // logging and wrapping errors, for convenience.
> func HandleErrorOrPanic(
> 	ctx context.Context, err *error, wrapMsgFmt string, wrapMsgArgs ...interface{},
> ```

I feel like we have an obnoxious linter that's not going to like this. Maybe just add a wrap function that's like `func(error) error` to which you can pass the message in closure scope? Then just log the error as opposed to this? 


<!-- Sent from Reviewable.io -->

2022-11-07 16:37 UTC, postamar commented
I told the linter not to annoy us with `HandleErrorOrPanic`. I feel that it's appropriate to do so, for what it's worth.

2022-11-07 19:25 UTC, ajwerner reviewed
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91411)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scerrors/errors.go` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/91411#-NGIYMW02Gq5J6dRhxuR:-NGIYMW02Gq5J6dRhxuS:bobpfe7) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2bf18245cfd3848cd9a96d54203d8da3264bb4/pkg/sql/schemachanger/scerrors/errors.go#L28)):*
> ```Go
> )
> 
> // HandleErrorOrPanic generates a closure, intended to be deferred, to handle
> ```

I don't really get why this function unconditionally logs twice. I feel like it's doing too much. Can we have it either only log on the error path?


<!-- Sent from Reviewable.io -->

2022-11-07 19:29 UTC, postamar commented
> I don't really get why this function unconditionally logs twice. I feel like it's doing too much. Can we have it either only log on the error path?

Fair enough, we don't need to log twice in most cases. I'll remove the "done" logs unless there's an error or expensive logging is enabled.

2022-11-07 20:12 UTC, postamar commented
Thanks for the feedback. Things are now in a state where I'm happy with them.

2022-11-07 20:45 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91411)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scerrors/errors.go` line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91411#-NGHwDZe2ozcYNRixxLw:-NGIkSh83pSveW-OL4h2:befk66u) ([raw file](https://github.com/cockroachdb/cockroach/blob/130c189bae8df8b7ea046796b2576f16a7d3e7a8/pkg/sql/schemachanger/scerrors/errors.go#L34)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like we have an obnoxious linter that's not going to like this. Maybe just add a wrap function that's like `func(error) error` to which you can pass the message in closure scope? Then just log the error as opposed to this? 
</blockquote></details>

I don't know, it seems pretty crazy to have a thing called `HandleErrorOnPanic` unconditionally log a message when called that has nothing to do with any possible error. I was absolutely fine with the message being logged in the case of an error, but I'm pretty opposed to the choice you've made without really making it clear in the function. 

If you renamed the method to something clearer and then made the message a part of the description of the function, I'd be more amenable. 
___
*[`pkg/sql/schemachanger/scerrors/errors.go` line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91411#-NGIl-eF2n3_Uv7WPVZV:-NGIl-eF2n3_Uv7WPVZW:b-w9e22y) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd21fee2cedc114db42f18c2c499ba96790cb179/pkg/sql/schemachanger/scerrors/errors.go#L60)):*
> ```Go
> 			msgFmt = "failed " + msgFmt + " with error: %v"
> 			args = append(args[:len(args):len(args)], unwrappedErr)
> 			log.InfofDepth(ctx, logDepth, msgFmt, args...)
> ```

should this be `Warning`?  Also, should we also check and see if the context is canceled? 


<!-- Sent from Reviewable.io -->

2022-11-07 21:00 UTC, postamar commented
Agreed, `HandleErrorOnPanic` is a bad name. I'll fix that.

> I'd be more amenable.

I'm keen to avoid further back and forth here, please don't hesitate to be more explicit about what I should do.

> should this be Warning? Also, should we also check and see if the context is canceled?

I don't know the answer to either of these questions. Please tell me.

2022-11-07 21:43 UTC, ajwerner reviewed
Okay, let's do `Warning` if there was an error and the context was not canceled.

As for nameing, this is a little convoluted, but I think it reads nicely:

```go

type EventLogger struct {
    format string
    args []interface
}

func StartEvent(format string, args ...interface) EventLogger { /* ... */ }

func (el EventLogger) HandlePanicAndLogError(err *error) { /*...*/ }

```

Then this thing would be called like:

```go
defer scerrors.LogStart(
   "building declarative schema changer plan in %s (rollback=%v) for %s",
   redact.Safe(params.ExecutionPhase),
   redact.Safe(params.InRollback),
   redact.Safe(initial.StatementTags()),
).RecoverPanicAndLogError(&err)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91411#-:-NGJ1AHeABiPiKTR5jyp:bak3xce)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)



<!-- Sent from Reviewable.io -->

2022-11-08 11:48 UTC, postamar commented
Thanks! Much appreciated. I like this a lot. Will do :+1:

2022-11-08 19:44 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91411#-:-NGNlQ43BhgISxZ9bY43:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)



<!-- Sent from Reviewable.io -->

2022-11-08 20:19 UTC, postamar commented
Thanks for the review!

bors r+

2022-11-08 21:14 UTC, merged