kvserver: add load dimensions
cockroachdb/cockroach pull request #91593
Opened 2022-11-09 13:20 UTC by kvoli

Previously, disparate types were used when comparing `StoreCapcity`, `XThreshold` and `RangeUsageInfo`. This patch introduces a uniform intermediate type `Load`, which is used to perform arithmetic and comparison between types representing load.

The purpose of this change is to decouple changes to the underlying inputs in these components to enable modifying existing load dimensions and adding new ones with less code modification.

Additionally, `RangeUsageInfo` is uniformly passed around in place of any specific calls to the underlying accounting `ReplicaStats`, to a tight dependency.

Release note: None

2022-11-09 13:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/91593)
<!-- Reviewable:end -->

2022-12-28 18:18 UTC, andrewbaptist requested changes
This mostly looks great. Most of the comments are pretty minor, but I'm a little confused about some of the "multi-dimension" code that exists.

> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-:-NKOx0dBC8Wp0io5r3pV:bwt2elb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOYEGh2ElFdeEZ_3s1:-NKOYEGh2ElFdeEZ_3s2:bj0tgex) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replica_rankings.go#L103)):*
> ```Go
> //
> // TODO(kvoli): When adding another load dimension to be balanced upon, it will
> // be necessary to clairfy the semantics of this API. This is especially true
> ```

nit: clairfy -> clarify
___
*[`pkg/kv/kvserver/replica_rankings.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOYmKz9cjpN4I9adiM:-NKOYmKz9cjpN4I9adiN:b-e2akf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replica_rankings.go#L105)):*
> ```Go
> // be necessary to clairfy the semantics of this API. This is especially true
> // since the UI is coupled to this function.
> func (rr *ReplicaRankings) NewAccumulator(dimension load.Dimension) *RRAccumulator {
> ```

I'm confused why this is a method on ReplicaRankings instead of just a function. You don't use the rr in here at all. It looks like it was this way before, but makes it a little more confusing to read. 
___
*[`pkg/kv/kvserver/replica_rankings.go` line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOaarD6wJfg1iTiJZr:-NKOaarD6wJfg1iTiJZs:b-8c6cn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replica_rankings.go#L223)):*
> ```Go
> 
> // TopQPS returns the highest QPS CandidateReplicas that are tracked.
> func (rr *ReplicaRankingMap) TopQPS(tenantID roachpb.TenantID) []CandidateReplica {
> ```

Rename to `TopLoad`?
___
*[`pkg/kv/kvserver/replica_rankings.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOb6iU5IUusdlqJMyA:-NKOb6iU5IUusdlqJMyB:b-j9x8cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replica_rankings.go#L244)):*
> ```Go
> func (a RRAccumulatorByTenant) AddReplica(repl CandidateReplica) {
> 	// Do not consider ranges as hot when they are accessed once or less times.
> 	if repl.RangeUsageInfo().QueriesPerSecond <= 1 {
> ```

I probably just need a walk through with you on this. But I assumed that the function here would be "generic" over the replica. Here it is still assuming QPS. 
___
*[`pkg/kv/kvserver/replicate_queue.go` line 2167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOcBGVDzMzlwowAKif:-NKOcBGVDzMzlwowAKig:b-9xutv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replicate_queue.go#L2167)):*
> ```Go
> // NB: This is currently just the replicas usage, it assumes that the range's
> // usage information matches. Which is dubious in some cases but often
> // reasoanble when we only consider the leaseholder.
> ```

nit: reasoanble -> reasonable
___
*[`pkg/kv/kvserver/store.go` line 3411 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOeCOi6LStiBET3fTR:-NKOeCOi6LStiBET3fTS:b-m5z40m) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/store.go#L3411)):*
> ```Go
> // out of date.
> func (s *Store) HottestReplicas() []HotReplicaInfo {
> 	topQPS := s.replRankings.TopLoad()
> ```

nit: rename variable.
___
*[`pkg/kv/kvserver/store_rebalancer.go` line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOjeJSDANelbzVa6hS:-NKOjeJSDANelbzVa6hT:bmgjo5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/store_rebalancer.go#L714)):*
> ```Go
> 
> 		desc, conf := candidateReplica.DescAndSpanConfig()
> 		log.KvDistribution.VEventf(ctx, 3, "considering lease transfer for r%d with %s load",
> ```

Consider printing the dimension being used here so that the "units" make sense. Otherwise, this might be hard to debug if the configuration isn't known. (add on other events as well).
___
*[`pkg/kv/kvserver/store_rebalancer.go` line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOk9pb3foW3gY1V_l6:-NKOk9pb3foW3gY1V_l7:bo9b6rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/store_rebalancer.go#L824)):*
> ```Go
> 
> 		if candidateReplica == nil {
> 			panic("programming error: nil candidate replica found")
> ```

This is unnecessary to have this check at all anymore. It will panic anyway on the line below.
___
*[`pkg/kv/kvserver/allocator/base.go` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOl-Se71rR6dA3HY7p:-NKOl-Se71rR6dA3HY7q:b-i5hmnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/allocator/base.go#L176)):*
> ```Go
> 	// LoadDimensions declares the load dimensions to use when the Goal is
> 	// LoadConvergence.
> 	LoadDimensions []load.Dimension
> ```

I'm a little confused why this is an array (rather than just a single Dimension). I'm not clear that this is needed here at all since it can be pulled from configuration when needed (should discuss at walkthrough).
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1923 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOs-MODxCO-PEIHaRr:-NKOs-MODxCO-PEIHaRs:bcfk040) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1923)):*
> ```Go
> 				LoadThreshold:                LoadThresholds(&a.st.SV, opts.LoadDimensions...),
> 				MinLoadThreshold:             LoadMinThresholds(opts.LoadDimensions...),
> 				MinRequiredRebalanceLoadDiff: LoadRebalanceRequiredMinDiff(&a.st.SV, opts.LoadDimensions...),
> ```

It seems like this would be much better if it was a ratio rather than an absolute difference. 
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOsYIW7L4weJQSANl7:-NKOsYIW7L4weJQSANl8:b-4v391t) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L417)):*
> ```Go
> 	// MinRequiredRebalanceLoadDiff declares the minimum load difference
> 	// between stores required before recommending an action to rebalance.
> 	MinRequiredRebalanceLoadDiff load.Load
> ```

As noted elsewhere, can this be changed to be a ratio rather than an absolute difference?
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOsJS0CcfIGwRIxMTj:-NKOsJS0CcfIGwRIxMTk:bndb1tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L438)):*
> ```Go
> 	// rebalance or transfer. These shoulld more generally use two different
> 	// methods when estimating an impact.
> 	RebalanceImpact load.Load
> ```

This seems very difficult to calculate correctly. Also, I'm a little confused if you are computing the "cost" of follower replicas. If not, then it may skew the results badly. Let's discuss during the walkthrough.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOsvi5-gD7qDms_WmL: [...]

2022-12-29 03:24 UTC, kvoli reviewed
Thanks for taking a look! Lets discuss the multiple dimension part - it is done with an intent to use more than one dimension of load at a time in the near future.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-:-NKQjl5M4B9BE010NdOX:b-j7ysxi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOYEGh2ElFdeEZ_3s1:-NKQLh4U2u4CxhFGllD2:b-cypxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replica_rankings.go#L103)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: clairfy -> clarify
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOYmKz9cjpN4I9adiM:-NKQLhyQ1v90MPeUssYu:bh5ct4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replica_rankings.go#L105)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I'm confused why this is a method on ReplicaRankings instead of just a function. You don't use the rr in here at all. It looks like it was this way before, but makes it a little more confusing to read. 
</blockquote></details>

I agree, it has been that way since inception (a11ff0f3e6d1ffd95be3eb0bd22460bb101ac2c1). Updated to be separate. My only thought was that possibly it was used for namespacing in lieu of  a separate package.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOaarD6wJfg1iTiJZr:-NKQLkpE2U2WqBy5iT14:b-sylq2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replica_rankings.go#L223)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Rename to `TopLoad`?
</blockquote></details>

The tenant tracking is different in that it is only used in the UI (and was recently added). I opted not to touch it here since it only has purpose in supporting UI unified architecture changes. I've added a TODO above the `ReplicaRankingsMap` to come back and update after clarifying what "should" happen between UI and what is used in rebalancing - initially I thought it was obvious to force every ranking to be on the current rebalancing load dimension, however it's not necessarily in the tenants control (system setting) etc.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOb6iU5IUusdlqJMyA:-NKQLld936_RKLIT1h7m:btjcmrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replica_rankings.go#L244)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I probably just need a walk through with you on this. But I assumed that the function here would be "generic" over the replica. Here it is still assuming QPS. 
</blockquote></details>

See above comment - can discuss.
___
*[`pkg/kv/kvserver/replicate_queue.go` line 2167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOcBGVDzMzlwowAKif:-NKQLnIB0HoRsfsbfaVs:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replicate_queue.go#L2167)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: reasoanble -> reasonable
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/store.go` line 3411 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOeCOi6LStiBET3fTR:-NKQLnuRA7cwMh2DOiMQ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/store.go#L3411)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: rename variable.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/store_rebalancer.go` line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOjeJSDANelbzVa6hS:-NKQjNo47IoSBbTYGsoK:bk9zkga) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/store_rebalancer.go#L714)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Consider printing the dimension being used here so that the "units" make sense. Otherwise, this might be hard to debug if the configuration isn't known. (add on other events as well).
</blockquote></details>

It does make me reconsider including every dimension by default or not filtering earlier, so that what is displayed when calling string is just the filtered dimensions. I considered it but decided against it to avoid the added fields.

Lets discuss this. Printing the dimension seems good if keeping this approach.
___
*[`pkg/kv/kvserver/store_rebalancer.go` line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOk9pb3foW3gY1V_l6:-NKQLrsF-y0y01JSBlfi:b32wk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/store_rebalancer.go#L824)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

This is unnecessary to have this check at all anymore. It will panic anyway on the line below.
</blockquote></details>

do
___
*[`pkg/kv/kvserver/allocator/base.go` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOl-Se71rR6dA3HY7p:-NKQLxeS8hxHjHJWSs0l:bb0s69j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/allocator/base.go#L176)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I'm a little confused why this is an array (rather than just a single Dimension). I'm not clear that this is needed here at all since it can be pulled from configuration when needed (should discuss at walkthrough).
</blockquote></details>

I opted (perhaps prematurely) to setup for multiple dimension in the load vector to be used. Lets discuss.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1923 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOs-MODxCO-PEIHaRr:-NKQM0Be86hpxMmVubOR:bbrxl25) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1923)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

It seems like this would be much better if it was a ratio rather than an absolute difference. 
</blockquote></details>

There have to be some absolute numbers somewhere in the system at this stage.  This just wraps what already existed with QPS, which is 2x the min threshold difference https://github.com/kvoli/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/allocator/base.go#L38-L38. The reason that it exists as 2x the min threshold difference is essentially to stop thrashing. The reason the min threshold difference exists is explained here

https://github.com/kvoli/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/allocator/base.go#L36-L37

It would be nice to rid ourselves of magic numbers but it makes sense at least when considering QPS for there to be a minimum to create friction. A better alternative is to estimate the cost vs benefit and use that ratio to ensure adequate smoothing/rebalance friction in the system.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 417 at r1](https://reviewable.io/reviews/cockroachdb [...]

2022-12-30 18:05 UTC, andrewbaptist approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - there were a couple minor comments that you hadn't fully addressed, but after that I'm happy with the changes.

> Reviewed 6 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-:-NKZC4Eo8kRbauChehhL:bj6h79f)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-12-30 18:10 UTC, nvanbenschoten reviewed
> Reviewed 10 of 37 files at r1, 6 of 20 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91593)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/allocator/load/dimension.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOtePAANM0t-HNOPm1:-NKZ9CBN9-fGWBLkc5D7:b-gmwofd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/allocator/load/dimension.go#L22)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Good idea, updated.
</blockquote></details>

I think it's even more idiomatic to rely on the auto-incrementing `iota`, so that there's no chance of the value being missed when new dimensions are added. This will inherit the `Dimension` type though. If that's an issue, you could:
```
Queries Dimension = iota

nDimensionsTyped
nDimensions = int(nDimensionsTyped)
```
___
*[`pkg/kv/kvserver/allocator/load/dimension.go` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZ9xw_75tzKHNhtcIu:-NKZ9xw_75tzKHNhtcIv:b-yidkpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/dimension.go#L31)):*
> ```Go
> 	String() string
> 	// Format returns a formatted string for a value.
> 	Format(float64)
> ```

It doesn't currently return anything. So `Format(float64) string` and then maybe also a type assertion that `Dimension` implements `DimensionMeta`. Is this interface used though? Will it be?
___
*[`pkg/kv/kvserver/allocator/load/load.go` line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZAg8u5SyniMYqUzIl:-NKZAg8u5SyniMYqUzIm:b-zg3o5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/load.go#L20)):*
> ```Go
> 	Dim(dim Dimension) float64
> 	// Greater returns true if for every dim given the calling load is greater
> 	// than the other element-wise, false otherwise.
> ```

Consider being explicit about unspecified dimensions being ignored.
___
*[`pkg/kv/kvserver/allocator/load/load.go` line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZBBAhDVpOgJAENP30:-NKZBBAhDVpOgJAENP31:bwgmhwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/load.go#L36)):*
> ```Go
> 	Min(other Load) Load
> 	// ElementWiseProduct multiplies the calling Load with other and returns
> 	// the result. The multiplication is done entry-wise:
> ```

nit: you use "element-wise" instead of "entry-wise" everywhere else, so might as well use that here.
___
*[`pkg/kv/kvserver/allocator/load/vector.go` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZBVVF0cMYy-_H0ffi:-NKZBVVF0cMYy-_H0ffj:b1kum5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/vector.go#L25)):*
> ```Go
> func (s Vector) Dim(dim Dimension) float64 {
> 	if int(dim) > len(s) || dim < 0 {
> 		panic("Unkown load dimension tried to be accessed")
> ```

nit: this includes less information (no index) than if you just let `s[dim]` panic.
___
*[`pkg/kv/kvserver/allocator/load/vector.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZBjNnD_4ueGNlIx4I:-NKZBjNnD_4ueGNlIx4J:b84v04l) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/vector.go#L34)):*
> ```Go
> func (s Vector) Greater(other Load, dims ...Dimension) bool {
> 	for _, dim := range dims {
> 		if s.Dim(dim) <= other.Dim(dim) {
> ```

It's interesting that `Greater` and `Less` could be defined above the interface as free functions that apply to any `Load` implementations, instead of being pushed into it. To some extent, that's true of most of these methods. The `Load` interface could be as simple as:

```go
type Load interface {
	// Dim returns the value of the Dimension given.
	Dim(dim Dimension) float64
	// String returns a string representation of Load.
	String() string
}
```

It raises the question of what the interface is providing. Do we plan to add other implementations of it? Perhaps on a data structure that sits in gossip? If not, do we need the interface? At a minimum, it forces the `Vector` array onto the heap, which is mildly unfortunate.
___
*[`pkg/kv/kvserver/allocator/load/vector.go` line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZCxwg-KYJi5tKTgI-:-NKZCxwg-KYJi5tKTgI0:bsn1eqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/vector.go#L91)):*
> ```Go
> // String returns a string representation of Load.
> func (s Vector) String() string {
> 	var buf bytes.Buffer
> ```

nit: `strings.Builder` avoids a heap alloc.
___
*[`pkg/kv/kvserver/allocator/load/vector.go` line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZD8IdDzqoq6TjWZ_m:-NKZD8IdDzqoq6TjWZ_n:b-qhnm6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/vector.go#L97)):*
> ```Go
> 		dim := Dimension(i)
> 		fmt.Fprintf(&buf, "%s=%s", dim.String(), dim.Format(val))
> 		if i < n-1 {
> ```

nit: you can avoid `n` by placing this first in the loop under the condition `if i > 0 {`.
___
*[`pkg/kv/kvserver/asim/config/settings.go` line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZDRLD8yWn4ir3fL81:-NKZDRLD8yWn4ir3fL82:b-atizxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/asim/config/settings.go#L33)):*
> ```Go
> 	defaultLBRebalanceQPSThreshold = 0.1
> 	defaultLBMinRequiredQPSDiff    = 200
> 	defaultLBRebalancingDimension  = 0 // QPS
> ```

Can we use the type directly? Or does that create an import cycle?


<!-- Sent from Reviewable.io -->

2022-12-30 18:20 UTC, nvanbenschoten reviewed
> Reviewed 9 of 37 files at r1, 10 of 20 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91593)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 233 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZFA9Z-fhUvMr4SnLv:-NKZFA9Z-fhUvMr4SnLw:bkeoxn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/replica_rankings.go#L233)):*
> NB:

Did you mean to add more here?
___
*[`pkg/kv/kvserver/asim/config/settings.go` line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZDRLD8yWn4ir3fL81:-NKZFn4uBVgtRpoBXaux:b-cdovkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/asim/config/settings.go#L33)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we use the type directly? Or does that create an import cycle?
</blockquote></details>

EDIT: never mind. The type you'd want to import is `kvserver.LBRebalancingDimension`, not `load.Dimension`, so it would create a cycle.


<!-- Sent from Reviewable.io -->

2023-01-03 17:01 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91593)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 233 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZFA9Z-fhUvMr4SnLv:-NKsA5bo-dhhtsAm6NPQ:b-lztjg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/replica_rankings.go#L233)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> NB:

Did you mean to add more here?
</blockquote></details>

I did not - removed.
___
*[`pkg/kv/kvserver/store_rebalancer.go` line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOk9pb3foW3gY1V_l6:-NKsA7bIBnKZF5s2bfXQ:b-7rl0jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/store_rebalancer.go#L824)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

do
</blockquote></details>

done*
___
*[`pkg/kv/kvserver/allocator/load/dimension.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOtePAANM0t-HNOPm1:-NKsAH_K5yGvTDWhR69O:b40y0ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/allocator/load/dimension.go#L22)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think it's even more idiomatic to rely on the auto-incrementing `iota`, so that there's no chance of the value being missed when new dimensions are added. This will inherit the `Dimension` type though. If that's an issue, you could:
```
Queries Dimension = iota

nDimensionsTyped
nDimensions = int(nDimensionsTyped)
```
</blockquote></details>

Nice - updated.
___
*[`pkg/kv/kvserver/allocator/load/dimension.go` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZ9xw_75tzKHNhtcIu:-NKs_8QpEx9ktkfBKmcq:b-w3hy68) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/dimension.go#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It doesn't currently return anything. So `Format(float64) string` and then maybe also a type assertion that `Dimension` implements `DimensionMeta`. Is this interface used though? Will it be?
</blockquote></details>

Removed the iface - it was redundant here.
___
*[`pkg/kv/kvserver/allocator/load/load.go` line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZAg8u5SyniMYqUzIl:-NKsXEmzASw7uXYjI5uv:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/load.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider being explicit about unspecified dimensions being ignored.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/allocator/load/load.go` line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZBBAhDVpOgJAENP30:-NKsX55c7l8Bz7jt3i-N:b-cypxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/load.go#L36)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: you use "element-wise" instead of "entry-wise" everywhere else, so might as well use that here.
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/allocator/load/vector.go` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZBVVF0cMYy-_H0ffi:-NKsX3Cx-BIUQuXwsgSD:b-qx2nsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/vector.go#L25)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: this includes less information (no index) than if you just let `s[dim]` panic.
</blockquote></details>

Added index along with description.
___
*[`pkg/kv/kvserver/allocator/load/vector.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZBjNnD_4ueGNlIx4I:-NKsKwIG232sS9HkVL66:b-zfm8yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/vector.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's interesting that `Greater` and `Less` could be defined above the interface as free functions that apply to any `Load` implementations, instead of being pushed into it. To some extent, that's true of most of these methods. The `Load` interface could be as simple as:

```go
type Load interface {
	// Dim returns the value of the Dimension given.
	Dim(dim Dimension) float64
	// String returns a string representation of Load.
	String() string
}
```

It raises the question of what the interface is providing. Do we plan to add other implementations of it? Perhaps on a data structure that sits in gossip? If not, do we need the interface? At a minimum, it forces the `Vector` array onto the heap, which is mildly unfortunate.
</blockquote></details>

A fair point. I was leaning towards ranges/replicas having an implementation as well as a container over the top of StoreDescriptor in the store pool. However since this patch doesn't add this you're right it is needless complexity.

Updated to your suggestion.
___
*[`pkg/kv/kvserver/allocator/load/vector.go` line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZCxwg-KYJi5tKTgI-:-NKsKuci7hkW1VPuHYOY:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/vector.go#L91)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `strings.Builder` avoids a heap alloc.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/allocator/load/vector.go` line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKZD8IdDzqoq6TjWZ_m:-NKsKvam3BM_Sm4EZ0rx:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/88964ca7ebe14dd26d106c3aadbdeb3f66dbba59/pkg/kv/kvserver/allocator/load/vector.go#L97)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: you can avoid `n` by placing this first in the loop under the condition `if i > 0 {`.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/replica_rankings_test.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-NKOvbfQ5S4Pet1Vf4uY:-NKsECZe2e7xl2L9Q7uu:b-7rl0jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4edb0f76dc368fb1d25c74c5ed35aba5575f75/pkg/kv/kvserver/replica_rankings_test.go#L83)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

do
</blockquote></details>

done*


<!-- Sent from Reviewable.io -->

2023-01-03 17:11 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91593#-:-NKsbMu31K-RQs1aX70y:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist)



<!-- Sent from Reviewable.io -->

2023-01-03 18:09 UTC, kvoli commented
bors r=nvanbenschoten,andrewbaptist

2023-01-03 19:17 UTC, merged