split: Add a testing framework to benchmark load splitter approaches
cockroachdb/cockroach pull request #91636
Opened 2022-11-09 22:29 UTC by KaiSun314

Informs: https://github.com/cockroachdb/cockroach/issues/90574

Here, we create a testing framework to benchmark load-based splitters, to enable experimenting and comparison of different designs and settings.

This testing framework inputs:
1. Generator settings to generate the requests for the load splitter to record
- Start key generator type (zipfian or uniform) and iMax
- Span length generator type (zipfian or uniform) and iMax
- Weight generator type (zipfian or uniform) and iMax
2. Range request percent (percent of range requests [startKey, endKey) as opposed to point requests with just a start key)
3. Load-based splitter constructor
4. Random seed

This testing framework performs the following work:
1. Generates the requests for the load splitter to record
2. Calculates the optimal split key and its left / right weights
3. Constructs the load splitter and invokes the load splitter's Record function on all the generated requests
4. Invokes the load splitter's Key function to get the split key and calculates its left / right weights
5. Maintains the times it took to execute the load splitter's Record and Key functions

This testing framework also supports repeating the test multiple times with different random numbers and calculating the average / max percentage differences of left / right weights and execution times. This testing framework also supports running tests with different settings and printing the test results for each setting.

Example of testing framework output:
<img width="1452" alt="Load-Based Splitter Testing Framework Sample Output" src="https://user-images.githubusercontent.com/28762332/201250317-7bf71fd7-0ef2-44d9-807a-45c66aab79ea.png">

Release note: None

2022-11-10 20:55 UTC, kvoli requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYHXJo8AbKgcl1ILgI:-NGYHXJo8AbKgcl1ILgJ:b-5nr77u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L42)):*
> ```Go
> }
> 
> type Config struct {
> ```

Do these structs/methods need to be exported?
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYJ_zlB7E0PQtCOSsS:-NGYJ_zm4TU7S9x-gJWr:b-nbsdwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L66)):*
> ```Go
> }
> 
> func runTest(
> ```

It feels as though there are a lot of separate components coming together here, could we split out generating the sequence of keys, evaluating an oracle and evaluating the real code?
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYIdmM6jLooX2o3pi_:-NGYIdmM6jLooX2o3pia:b-aez2ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L112)):*
> ```Go
> 		return weightedKeys[i].key < weightedKeys[j].key
> 	})
> 	var optimalKeyPtr *uint32
> ```

Could we split this out into an "oracle" function.
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYI_Rh1OiyHYprS1V6:-NGYI_Ri6PsgqxqVkDCx:bihfgj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L115)):*
> ```Go
> 	var prefixTotalWeight float32
> 	for _, weightedKey := range weightedKeys {
> 		if optimalKeyPtr == nil || math.Abs(float64(totalWeight-2*prefixTotalWeight)) < math.Abs(float64(totalWeight-2*optimalLeftWeight)) {
> ```

This probably needs a comment or explanation.
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYJVtr9QL6Asc0_v3t:-NGYJVtr9QL6Asc0_v3u:b-1o2ab7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L162)):*
> ```Go
> 	var err error
> 	if generatorType == zipfGenerator {
> 		generator, err = ycsb.NewZipfGenerator(randSource, 1, iMax, 0.99, false)
> ```

Is the 0.99 the same as ycsb here?
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYICXC1uQ5wAyKgphA:-NGYICXC1uQ5wAyKgphB:bi4xtnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L215)):*
> ```Go
> 
> func runTestMultipleSettings(t *testing.T, settingsArr []Settings) {
> 	fmt.Printf(
> ```

Could we change this to a similar structure to here: https://github.com/kvoli/cockroach/blob/a92f9564748d3ac23ce596542649a8427ce1e3b8/pkg/kv/kvserver/asim/metrics_tracker.go#L36-L45

For clarity.
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYInnX-0B_edROGux2:-NGYInnY3dPcDWuG4euA:byzdm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L255)):*
> ```Go
> 				return NewTestFinder(randSource)
> 			},
> 			seed: 2022,
> ```

If we could parameterize some randomness - i.e. get a seed generated randomly and then also run a n iterations where we randomly select the generator and lengths (without some bounds), it may be useful to enable some degree of assertions on the existing split finder - perhaps just that you find a key would be a good start (assuming that parameter boundaries allow for it).


<!-- Sent from Reviewable.io -->

2022-11-11 02:46 UTC, KaiSun314 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYHXJo8AbKgcl1ILgI:-NGZY-JA-zopqlCY9h2L:b6fo6bj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L42)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Do these structs/methods need to be exported?
</blockquote></details>

No, made them all lowercase
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYJ_zlB7E0PQtCOSsS:-NGZY62N59Q47BLVFHyh:b-7bjx13) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L66)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It feels as though there are a lot of separate components coming together here, could we split out generating the sequence of keys, evaluating an oracle and evaluating the real code?
</blockquote></details>

Split out into generateRequests, getOptimalKey, and getKey
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYIdmM6jLooX2o3pi_:-NGZYEir7aL8DUC2iRrC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L112)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could we split this out into an "oracle" function.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYI_Rh1OiyHYprS1V6:-NGZYG2F57aLrGZv7feL:b9gjgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L115)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This probably needs a comment or explanation.
</blockquote></details>

Added comment and made the code clearer
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYJVtr9QL6Asc0_v3t:-NGZZfv73LdtOtD0ZNeH:b-pnsaqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L162)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Is the 0.99 the same as ycsb here?
</blockquote></details>

Yep defaultTheta in ycsb's zipf generator is 0.99
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYICXC1uQ5wAyKgphA:-NGZZnDb7LaU1TkLYHnN:b-kkvz5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L215)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could we change this to a similar structure to here: https://github.com/kvoli/cockroach/blob/a92f9564748d3ac23ce596542649a8427ce1e3b8/pkg/kv/kvserver/asim/metrics_tracker.go#L36-L45

For clarity.
</blockquote></details>

Used the tabular printer tabwriter
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91636#-NGYInnX-0B_edROGux2:-NGZ_5Ih82iNpAvHFrtN:b1v7vpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aca9775265bb97595de790725973bdb86f6689f/pkg/kv/kvserver/split/load_based_splitter_test.go#L255)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

If we could parameterize some randomness - i.e. get a seed generated randomly and then also run a n iterations where we randomly select the generator and lengths (without some bounds), it may be useful to enable some degree of assertions on the existing split finder - perhaps just that you find a key would be a good start (assuming that parameter boundaries allow for it).
</blockquote></details>

Added documentation explaining this load-based splitter testing framework and the intent / usage / where it's going


<!-- Sent from Reviewable.io -->

2022-11-11 11:17 UTC, kvoli approved these changes

2022-11-14 20:33 UTC, KaiSun314 commented
bors r=kvoli

2022-11-14 22:03 UTC, merged