sql/opt: Support regtype and oid type in foldStringToRegclassCast
cockroachdb/cockroach pull request #91681
Opened 2022-11-10 16:19 UTC by e-mbrown

This commit adds allows queries like
`select * from pg_class where oid ='my_table'::regclass::oid` and `select * from pg_type where oid ='my type'::regtype` to use index on `pg_class(oid)` and `pg_type(oid)`

Release note: None

2022-11-10 16:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/91681)
<!-- Reviewable:end -->

2022-11-10 16:33 UTC, rafiss requested changes
this is good progress!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-:-NGXNppO53LYc3Ryw1Bc:blm6f3e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGXN3xH0ebZkubGfFPN:-NGXN3xH0ebZkubGfFPO:b13o50n) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad5f0461020daa4c9fef525720eb210cb51c12e/pkg/sql/opt/norm/fold_constants_funcs.go#L324)):*
> ```Go
> // optimizer to do intelligent things like push down filters that look like:
> // ... WHERE oid = 'my_table'::REGCLASS
> func (c *CustomFuncs) foldStringToRegclassCast(
> ```

since we're making this function more general now, let's rename it to something like `foldOIDFamilyCast`
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGXMg3WDA_juHDNGS4l:-NGXMg3WDA_juHDNGS4m:b-pdxzie) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad5f0461020daa4c9fef525720eb210cb51c12e/pkg/sql/opt/norm/fold_constants_funcs.go#L339)):*
> ```Go
> 	switch typ {
> 	case types.RegType:
> 		typRef, err := parser.GetTypeFromValidSQLSyntax(string(s))
> ```

regtypes need a bit more handling. this works for the builtin types, but not for user-defined types. for those, we'd need to `resolve` them, which might mean introducing a new function similar to the `ResolveDataSource` one below. (or maybe something exists already, we can look into it)

that will be a bit more involved, so could you take the regtype handling out from this PR, and keep it just focused on the OID change?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/scalar` line 1023 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGXNR-I6In7rfhRt63S:-NGXNR-I6In7rfhRt63T:bdpr002) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad5f0461020daa4c9fef525720eb210cb51c12e/pkg/sql/opt/exec/execbuilder/testdata/scalar#L1023)):*
> ```
> 
> query T
> EXPLAIN (VERBOSE) select * from pg_class where oid = 't'::regclass::oid
> ```

could you also add a test for `select * from pg_class where oid = 101::oid`

that will test that int->oid casts are also handled


<!-- Sent from Reviewable.io -->

2022-11-10 16:57 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91681)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGXN3xH0ebZkubGfFPN:-NGXSTFf0SCkZnVeUZFB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad5f0461020daa4c9fef525720eb210cb51c12e/pkg/sql/opt/norm/fold_constants_funcs.go#L324)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since we're making this function more general now, let's rename it to something like `foldOIDFamilyCast`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGXMg3WDA_juHDNGS4l:-NGXTHJ05bcpxN_uEeWr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad5f0461020daa4c9fef525720eb210cb51c12e/pkg/sql/opt/norm/fold_constants_funcs.go#L339)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

regtypes need a bit more handling. this works for the builtin types, but not for user-defined types. for those, we'd need to `resolve` them, which might mean introducing a new function similar to the `ResolveDataSource` one below. (or maybe something exists already, we can look into it)

that will be a bit more involved, so could you take the regtype handling out from this PR, and keep it just focused on the OID change?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/scalar` line 1023 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGXNR-I6In7rfhRt63S:-NGXTLWz7ggkgRt1a2on:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad5f0461020daa4c9fef525720eb210cb51c12e/pkg/sql/opt/exec/execbuilder/testdata/scalar#L1023)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you also add a test for `select * from pg_class where oid = 101::oid`

that will test that int->oid casts are also handled
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-10 22:01 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91681)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 330 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGYSgNk5Bvhp7NN1_LK:-NGYSgNn3Mljh27Xhw9A:b-6bryfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89d84fbc0d16d4ef86d86793d06fb8cc02f20a3/pkg/sql/opt/norm/fold_constants_funcs.go#L330)):*
> ```Go
> 	datum := memo.ExtractConstDatum(input)
> 
> 	if typ == types.Oid {
> ```

we need a bit more logic here now. a brief pseudocode outline:
```
switch typ.Oid() {
case types.Oid.Oid():
  switch input.Family() {
  case types.StringFamily:
    // use `tree.ParseDOidAsInt`
  case types.IntFamily:
    // use `tree.IntToOid`
  case types.OidFamily:
    // use `tree.MustBeDOid`
  default:
    // return an error
  }
case types.Regclass.Oid():
  switch input.Family() {
  case types.StringFamily:
    // use the existing logic from before
  default:
    // return an error
  }
}
```
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 357 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGY4ktv5B8Z--vgYPZ4:-NGY4ktv5B8Z--vgYPZ5:bbq5xll) ([raw file](https://github.com/cockroachdb/cockroach/blob/f89d84fbc0d16d4ef86d86793d06fb8cc02f20a3/pkg/sql/opt/norm/fold_constants_funcs.go#L357)):*
> ```Go
> func (c *CustomFuncs) FoldCast(input opt.ScalarExpr, typ *types.T) (_ opt.ScalarExpr, ok bool) {
> 	if typ.Family() == types.OidFamily {
> 		if input.DataType().Family() == types.StringFamily || typ == types.Oid {
> ```

let's move the check for `input.DataType.Family` and `typ` to go inside of the `foldOIDFamily` function


<!-- Sent from Reviewable.io -->

2022-11-15 21:26 UTC, rafiss requested changes
looks close!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-:-NGxAxhd-ydIshqrSL9W:b4mg42i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 320 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGx99Mn8A1rh8PdYwhV:-NGx99Mn8A1rh8PdYwhW:btd0xb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc62a0dd34c6dc9032caa74266ec735cd3019214/pkg/sql/opt/norm/fold_constants_funcs.go#L320)):*
> ```Go
> }
> 
> // foldStringToRegclassCast resolves a string that is a table name into an OID
> ```

nit: adjust the comment (both for naming, and to describe the more general functionality it has now)
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 330 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGx9Fyi59CeBRxLv0Od:-NGx9Fyi59CeBRxLv0Oe:b-tde725) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc62a0dd34c6dc9032caa74266ec735cd3019214/pkg/sql/opt/norm/fold_constants_funcs.go#L330)):*
> ```Go
> 	bool, /*castValid*/
> 	error,
> ) {
> ```

nit: define the return values like this:
```
func (c *CustomFuncs) foldOIDFamilyCast(
  ...
) (
  _ opt.ScalarExpr,
  isValid bool,
  retErr error
) {
```
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 335 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGxABe-4HNRYLbMpEa1:-NGxABe-4HNRYLbMpEa2:b-clp3xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc62a0dd34c6dc9032caa74266ec735cd3019214/pkg/sql/opt/norm/fold_constants_funcs.go#L335)):*
> ```Go
> 
> 	inputFamily := input.DataType().Family()
> 	var typOid *tree.DOid
> ```

nit: name it `dOid`
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 338 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGx9dik44rWOV1_QDC8:-NGx9dik44rWOV1_QDC9:bjkbxlr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc62a0dd34c6dc9032caa74266ec735cd3019214/pkg/sql/opt/norm/fold_constants_funcs.go#L338)):*
> ```Go
> 	var err error
> 
> 	switch typ {
> ```

nit: make it `switch typ.Oid()`

the reason is that `typ` is a `*types.T`, so technically the pointer could be different from what you are comparing to
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 339 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGx9piy6_sLF0wZ9kvI:-NGx9piy6_sLF0wZ9kvJ:b-ju5hl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc62a0dd34c6dc9032caa74266ec735cd3019214/pkg/sql/opt/norm/fold_constants_funcs.go#L339)):*
> ```Go
> 
> 	switch typ {
> 	case types.Oid:
> ```

and this should be `case oid.T_oid`
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 354 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGxAJ6BBD6jTDn1tE4u:-NGxAJ6BBD6jTDn1tE4v:b-22miyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc62a0dd34c6dc9032caa74266ec735cd3019214/pkg/sql/opt/norm/fold_constants_funcs.go#L354)):*
> ```Go
> 
> 		if err != nil {
> 			return nil, true, err
> ```

nit: putting the err check here is risky since it would be easy to miss if something gets refactored. can you put it to be right after the errs are created
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 356 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGxA0rY-rqrTToS7JzR:-NGxA0rZ2aHzK8MaDCL3:b-q2kwp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc62a0dd34c6dc9032caa74266ec735cd3019214/pkg/sql/opt/norm/fold_constants_funcs.go#L356)):*
> ```Go
> 			return nil, true, err
> 		}
> 	case types.RegClass:
> ```

and this should be `case oid.T_regclass`
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 362 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGxAOEc51I85XENxOxz:-NGxAOEc51I85XENxOy-:bb948bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc62a0dd34c6dc9032caa74266ec735cd3019214/pkg/sql/opt/norm/fold_constants_funcs.go#L362)):*
> ```Go
> 			tn, err := parser.ParseQualifiedTableName(string(s))
> 			if err != nil {
> 				return nil, true, err
> ```

`return nil, false, err`
___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 367 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91681#-NGxAPjA1Aru-VMCn4FX:-NGxAPjA1Aru-VMCn4FY:bb948bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc62a0dd34c6dc9032caa74266ec735cd3019214/pkg/sql/opt/norm/fold_constants_funcs.go#L367)):*
> ```Go
> 			ds, resName, err := c.f.catalog.ResolveDataSource(c.f.ctx, flags, tn)
> 			if err != nil {
> 				return nil, true, err
> ```

`return nil, false, err`


<!-- Sent from Reviewable.io -->

2022-11-16 17:12 UTC, rafiss requested changes

2022-11-16 17:12 UTC, rafiss commented on pkg/sql/opt/norm/fold_constants_funcs.go
> +				return nil, false, err
i guess i was mistaken before, technically the cast is valid, but there was an error, so it should be `return nil, true, err`

2022-11-17 18:12 UTC, rafiss approved these changes

2022-11-17 19:10 UTC, e-mbrown commented
TFTR

bors r=rafiss

2022-11-17 20:41 UTC, merged