builtins: deflake TestSerialNormalizationWithUniqueUnorderedID
cockroachdb/cockroach pull request #91868
Opened 2022-11-14 20:19 UTC by ajwerner

The use of range stats and splits was not very stable and not needed.

Fixes #91858

Release note: None

2022-11-14 20:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/91868)
<!-- Reviewable:end -->

2022-11-15 15:32 UTC, rafiss approved these changes

2022-11-15 15:33 UTC, rafiss commented on pkg/sql/sem/builtins/builtins_test.go
>  	// Enforce 3 bits worth of range splits in the high order to collect range
does the comment about enforcing range splits still technically apply?

2022-11-15 15:34 UTC, rafiss requested changes
thanks for fixing! i think it needs a rebase and unskip for https://github.com/cockroachdb/cockroach/pull/91857

2022-11-21 17:18 UTC, ajwerner reviewed
>  i think it needs a rebase and unskip for #91857

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91868#-:-NHQBk0q6nRwQ1iuEQ9x:brjcs1m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/builtins_test.go` line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91868#-NGrmy29OkdCgOYCME0q-r1-121:-NHQBc8l3GXMuu-pj_Yo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7541c84bf63394dab0ee0caede339b2319e047/pkg/sql/sem/builtins/builtins_test.go#L121)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does the comment about enforcing range splits still technically apply?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins_test.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91868#-NGrmy29OkdCgOYCME0q-r1-132:-NHQBcqaBaif66qttXv4:b-2bcsdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7541c84bf63394dab0ee0caede339b2319e047/pkg/sql/sem/builtins/builtins_test.go#L132)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

at a high level i get that this is computing a histogram, but want to add some comments about what's up with the bit-shifting and why the numbers `60`, `62`, and `7` were chosen? perhaps explain the `SELECT p AS low, lead(p) OVER () AS high FROM boundaries` window clause a bit too
</blockquote></details>

Done. I generalized the query a bit to take a bits parameter and tried to explain it better.


<!-- Sent from Reviewable.io -->

2022-11-22 15:26 UTC, rafiss approved these changes
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91868#-:-NHUwi9mC49S_6oA9K0Y:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-11-22 15:44 UTC, ajwerner commented
bors r+

2022-11-22 17:07 UTC, merged