Faizaan/merge histograms
cockroachdb/cockroach pull request #91933
Opened 2022-11-15 18:56 UTC by faizaanmadhani

This commit adds support to the table stats
cache to merge partial statistics with full table
statistics and forecast new table statistics.
It currently does not work, as support for merging
has not been implemented

Release note: None

Epic: [CRDB-19449](https://cockroachlabs.atlassian.net/browse/CRDB-19449)

2022-11-15 18:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/91933)
<!-- Reviewable:end -->

2022-12-02 17:29 UTC, michae2 requested changes
Very nice! I'm still reading, just a couple nits so far.

> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NIIsWKx25EJvdrMePxb:b-eoyka0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIrQn8DESzy-SCNKiE):*
nit: I think it would be helpful to also mention how this merging relates to forecasting. Could be as simple as "before forecasting" somewhere in this sentence.
___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIqyca8zafxXl0VzTu):*
I believe everything after "Release note" will get picked up by [the release note script](https://github.com/cockroachdb/ed-tools/blob/main/docs/release-notes/release-notes.py), so this "Epic" reference needs to be above the release note.
___
*[`pkg/sql/stats/merge.go` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIFCJBqDKTxlcJTCCBR:-NIFCJBr6FkT6GwIqw8G:b-vcqzyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L170)):*
> ```Go
> 		}
> 	}
> 	forecastCols, fullStatsMap, colKeyToColIDs := groupObservedStatistics(fullStatsList)
> ```

nit: Does this need the full "grouping" behavior now that it's not forecasting and just using the latest full stats? Maybe `fullStatsMap` should just be `map[string]*TableStatistic` now instead of `map[string][]*TableStatistic`.
___
*[`pkg/sql/stats/new_stat.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIEiObK1ZRj2HpdRKyA:-NIEiObK1ZRj2HpdRKyB:b-rtfttm) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/new_stat.go#L106)):*
> ```Go
> 					"nullCount",
> 					"avgSize",
> 					histogram
> ```

nit: Is this the same fix sneaking in again? :slightly_smiling_face:
___
*[`pkg/sql/stats/stats_cache.go` line 792 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIEhlodBnZyqXcctdUR:-NIEhlodBnZyqXcctdUS:b-q3qvf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/stats_cache.go#L792)):*
> ```Go
> 	}
> 
> 	var forecasts []*TableStatistic
> ```

nit: I think this slice can go back to being local to the `if forecast` branch.
___
*[`pkg/sql/stats/stats_cache.go` line 793 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIEi-3j1hCDJ09tEHev:-NIEi-3j1hCDJ09tEHew:b-72jh2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/stats_cache.go#L793)):*
> ```Go
> 
> 	var forecasts []*TableStatistic
> 	if len(partialStatsList) > 0 {
> ```

todo: In a future PR we should add a variable to disable merging, just in case we need to turn it off for some reason.


<!-- Sent from Reviewable.io -->

2022-12-02 18:31 UTC, rytaft reviewed
This is looking good!

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NIJ57rtD3qynbXSBk9X:bjwdyz2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @michae2)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIJ3bHOAXTOhTVvMpS7):*
Since you're noting that the optimizer now uses these stats, it would be good to include a couple of tests where you show that the optimizer uses the merged stats.  A good place for this would probably be in a new file `pkg/sql/opt/exec/execbuilder/testdata/partial_stats` (similar to the `forecast` file in the same directory). No need to actually generate partial stats -- you can just inject them with `INJECT STATISTICS`. Alternatively, you could add a file `pkg/sql/opt/memo/testdata/stats/partial_stats` and add the tests there.
___
*[`pkg/sql/stats/merge.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIrCkA2iou_gQ4XIdR:-NIIrCkA2iou_gQ4XIdS:b-erwjo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L24)):*
> ```Go
> )
> 
> // mergeExtremesStatistics merges a full table statistic with a partial table statistic
> ```

nit: mergeExtremesStatistics -> mergeExtremesStatistic
___
*[`pkg/sql/stats/merge.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIrSeG2JOEYI75tBvQ:-NIIrSeG2JOEYI75tBvR:b2zxuik) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L37)):*
> ```Go
> 
> 	// Merge the histograms
> 	// Currently, since we don't merge non-multi-column statistics, each
> ```

nit: non-multi-column -> multi-column ?
___
*[`pkg/sql/stats/merge.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIrfva9_8DpsSbfgAw:-NIIrfva9_8DpsSbfgAx:b-vjq3qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L51)):*
> ```Go
> 	var partialNullCount uint64
> 	if partialHistogram[0].UpperBound == tree.DNull {
> 		partialNullCount += uint64(partialHistogram[0].NumEq)
> ```

nit: just assign, no need to add:
```
partialNullCount = uint64(partialHistogram[0].NumEq)
```

You could also add this null bucket to the merged histogram here to avoid needing to copy everything over below
___
*[`pkg/sql/stats/merge.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIskLnBvlOizbGjLec:-NIIskLnBvlOizbGjLed:b-io537h) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L76)):*
> ```Go
> 			} else {
> 				// Partial is now larger, we break
> 				break
> ```

instead of breaking here, I think you could just do:
```
mergedHistogram = append(mergedHistogram, fullHistogram[j])
numOriginalRows += uint64(fullHistogram[j].NumRange + fullHistogram[j].NumEq)
j++
```
Then update the comment to say "Merge" instead of "Prepend". 

Then the next block would just be:
```
for j < len(fullHistogram) {
	mergedHistogram = append(mergedHistogram, fullHistogram[j])
	numOriginalRows += uint64(fullHistogram[j].NumRange + fullHistogram[j].NumEq)
	j++
}
```
___
*[`pkg/sql/stats/merge.go` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIuKbG6JxCfcsw48k-:-NIIuKbG6JxCfcsw48k0:bwngvkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L140)):*
> ```Go
> 
> 	hist := histogram{
> 		buckets: append([]cat.HistogramBucket{}, mergedHistogram...),
> ```

why are you prepending an empty bucket?
___
*[`pkg/sql/stats/merge.go` line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIv1bZCbPEiLzHqjsh:-NIIv1bZCbPEiLzHqjsi:bfa9pqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L147)):*
> ```Go
> 	}
> 	mergedTableStatistic.HistogramData = &histData
> 	mergedTableStatistic.setHistogramBuckets(hist)
> ```

instead of doing this here, you could add the null bucket first like I suggested above.

Also, do we need to set `HistogramData`?

hmm, I see that a lot of this was copied from forecast.go. Maybe @michae2 has some answers to my questions here
___
*[`pkg/sql/stats/merge.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIx7_yBrN653s68YN8:-NIIx7_yBrN653s68YN9:bs9eoj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L155)):*
> ```Go
> // are the merged combinations of the latest full statistic and the latest partial
> // statistic for a specific column set. If merging a partial stat with the full
> // stat is not possible, we return the latest full stat as part of the result.
> ```

as part of the result? Or the whole thing?
___
*[`pkg/sql/stats/merge.go` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIwcp53dx6dOuzyGTU:-NIIwcp53dx6dOuzyGTV:bwn5gaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L156)):*
> ```Go
> // statistic for a specific column set. If merging a partial stat with the full
> // stat is not possible, we return the latest full stat as part of the result.
> func CreateMergedStatistics(
> ```

does this need to be exported?

Edit: I think you might need to call it from show_stats.go, which would require exporting
___
*[`pkg/sql/stats/merge.go` line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIxT1Z2XLjf6NYx9mD:-NIIxT1Z2XLjf6NYx9mE:btse5wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L166)):*
> ```Go
> 	for _, stat := range partialStatsList {
> 		colKey := MakeSortedColStatKey(stat.ColumnIDs)
> 		if _, ok := partialStatsMap[MakeSortedColStatKey(stat.ColumnIDs)]; !ok {
> ```

nit: `MakeSortedColStatKey(stat.ColumnIDs)` -> `colKey`
___
*[`pkg/sql/stats/merge.go` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIFCJBqDKTxlcJTCCBR:-NIIyIll1s7GOymUMPSW:b-2gqr3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L170)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Does this need the full "grouping" behavior now that it's not forecasting and just using the latest full stats? Maybe `fullStatsMap` should just be `map[string]*TableStatistic` now instead of `map[string][]*TableStatistic`.
</blockquote></details>

It's also confusing that you're calling the columns "forecastCols", since there's nothing here related to forecasts.
___
*[`pkg/sql/stats/merge.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIyVO71O60Lo6ga8jp:-NIIyVO71O60Lo6ga8jq:bffxel1) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L171)):*
> ```Go
> 	}
> 	forecastCols, fullStatsMap, colKeyToColIDs := groupObservedStatistics(fullStatsList)
> 	// Store the forecasts as a map where the colKey maps to the forecasted table statistic
> ```

forecasts -> merged stats? also you're not storing a map anymore
___
*[`pkg/sql/stats/stats_cache.go` line 799 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIJ3GRW2crN9D8o1w91:-NIJ3GRW2crN9D8o1w92:b-lhuxam) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/stats_cache.go#L799)):*
> ```Go
> 
> 	if forecast {
> 		forecasts = ForecastTableStatistics(ctx, fullStatsList)
> ```

I think you're going to need to update show_stats.go as well with the logic to merge partial stats before calling `ForecastTableStatistics`
__ [...]

2022-12-05 17:00 UTC, faizaanmadhani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIqyca8zafxXl0VzTu):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I believe everything after "Release note" will get picked up by [the release note script](https://github.com/cockroachdb/ed-tools/blob/main/docs/release-notes/release-notes.py), so this "Epic" reference needs to be above the release note.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIskLnBvlOizbGjLec:-NIXdLgJ9khZqDno2sJD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L76)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

instead of breaking here, I think you could just do:
```
mergedHistogram = append(mergedHistogram, fullHistogram[j])
numOriginalRows += uint64(fullHistogram[j].NumRange + fullHistogram[j].NumEq)
j++
```
Then update the comment to say "Merge" instead of "Prepend". 

Then the next block would just be:
```
for j < len(fullHistogram) {
	mergedHistogram = append(mergedHistogram, fullHistogram[j])
	numOriginalRows += uint64(fullHistogram[j].NumRange + fullHistogram[j].NumEq)
	j++
}
```

</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIuKbG6JxCfcsw48k-:-NIXdPEJ15GeuisrRX_R:b-dx17z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L140)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why are you prepending an empty bucket?
</blockquote></details>

I followed process of appending histogram buckets the same way it's done in `forecast.go`. I don't think we need to prepend an empty bucket but I was just following the process there. 
___
*[`pkg/sql/stats/merge.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIx7_yBrN653s68YN8:-NIXeGF8D5RsykxU9kbW:bcsgljx) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L155)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

as part of the result? Or the whole thing?
</blockquote></details>

Done. When I refactored my code to decouple it from forecasting this comment became inaccurate. 
___
*[`pkg/sql/stats/merge.go` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIwcp53dx6dOuzyGTU:-NIXeY-q6kFxwKU0cO4K:brxp9sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L156)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

does this need to be exported?

Edit: I think you might need to call it from show_stats.go, which would require exporting
</blockquote></details>

Sounds good!
___
*[`pkg/sql/stats/merge.go` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIFCJBqDKTxlcJTCCBR:-NIXvpXy5j3a7ze49403:b-yi85sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L170)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It's also confusing that you're calling the columns "forecastCols", since there's nothing here related to forecasts.
</blockquote></details>

I changed the naming back -- it was a leftover from when this code was more coupled with forecasting. I also removed the grouping function because now that the two functionalities are separate and neither forecasting or merging uses or requires all of the return values / functionality of grouping, I've separated them into their respective functions which I think helps avoid confusion as well. 
___
*[`pkg/sql/stats/merge.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIyVO71O60Lo6ga8jp:-NIYCnjpESroVMaGDHDI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L171)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

forecasts -> merged stats? also you're not storing a map anymore
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge_test.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIJ1ZL61QJlKaxGloVQ:-NIXf73W8ICMJNJm63eR:bdm55rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge_test.go#L113)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: overlap with overlap? (also I don't see any overlap in the test case)
</blockquote></details>

Fixed the comment. Since we're just prepending and appending there shouldn't be overlap. This is a leftover from an earlier test case and I had missed changing the comment
___
*[`pkg/sql/stats/merge_test.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIzIWlAvzCzCBrp9pk:-NIXgAaP7jKIcbfC_eat:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge_test.go#L196)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

leftover debug code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-05 17:19 UTC, faizaanmadhani commented
*[`pkg/sql/stats/merge.go` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIuKbG6JxCfcsw48k-:-NIYHzmZ0Ygi-FPBgzOj:b-wrnbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L140)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

I followed process of appending histogram buckets the same way it's done in `forecast.go`. I don't think we need to prepend an empty bucket but I was just following the process there. 
</blockquote></details>

Actually, that was incorrect. I have removed the prepending functionality. 


<!-- Sent from Reviewable.io -->

2022-12-05 19:19 UTC, rytaft reviewed
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @michae2)

___
*[`pkg/sql/stats/forecast.go` line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIYhmKQ70RkFZe9l-31:-NIYhmKQ70RkFZe9l-32:b-223z9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/forecast.go#L88)):*
> ```Go
> 		// forecast statistics for normal BYTES columns.
> 		// TODO(michae2): Improve this when issue #50655 is fixed.
> 		if stat.HistogramData != nil && stat.HistogramData.ColumnType != nil &&
> ```

this isn't your change, right? If you rebase from master this diff be removed
___
*[`pkg/sql/stats/merge.go` line 158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIYewOFC284hOFtPT5I:-NIYewOFC284hOFtPT5J:bsbpdka) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/merge.go#L158)):*
> ```Go
> 	}
> 	// Map the ColumnIDs to the latest full table statistic,
> 	// and map the keys to the amount of columns in the set.
> ```

nit: amount -> number
___
*[`pkg/sql/stats/merge.go` line 172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIYfjln7xtorR92mtms:-NIYfjln7xtorR92mtmt:b-pv1jz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/merge.go#L172)):*
> ```Go
> 		}
> 		colKeyToNumCols[colKey] = len(stat.ColumnIDs)
> 	}
> ```

I think you can simplify this and the below logic a lot:
1. You don't need to create the slice `colKeys`, since you can just iterate through the map using
```
for col, stats := range fullStatsMap {
```
  You can also use `len(fullStatsMap)` to determine the capacity of `mergedStats`

2. You don't need to keep the map `colKeyToNumCols`, since you're only using it below to check whether the stats have a single column. I think you can just avoid putting any stats in the `fullStatsMap` that have more than one column

3. If you only store stats with one column, you don't need to call `MakeSortedColStatKey`, and you can just use the one column as a key of type `int`.
___
*[`pkg/sql/stats/merge_test.go` line 272 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIYha8n3RXX8TigPlWE:-NIYha8n3RXX8TigPlWF:b-5r817j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/merge_test.go#L272)):*
> ```Go
> 		},
> 		{
> 			// Multiple partial stats for a full statistic. Ensure it picks the latest for each respective set of column keys.
> ```

nit: comments should be <= 80 columns wide


<!-- Sent from Reviewable.io -->

2022-12-06 01:16 UTC, michae2 reviewed
> Reviewed 2 of 9 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/distsql_plan_stats.go` line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIZGvys38IN-i52-qve:-NIYQhXGD2otggYX2uuY:b-5o3en5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/distsql_plan_stats.go#L227)):*
> ```Go
> 	// cache.
> 	for _, t := range tableStats {
> 		if len(t.ColumnIDs) == 1 && column.GetID() == t.ColumnIDs[0] && t.PartialPredicate == "" && t.Name != jobspb.ForecastStatsName && t.Name != jobspb.MergedStatsName {
> ```

(You might already be doing this.) As mentioned [here](https://github.com/cockroachdb/cockroach/pull/91228#pullrequestreview-1192405950) we also need to avoid looking at table statistics with inverted histograms for `ARRAY` and `STRING` types.
___
*[`pkg/sql/stats/merge.go` line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIv1bZCbPEiLzHqjsh:-NIZXcGb423z4FVsrZWV:b2c52nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L147)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

instead of doing this here, you could add the null bucket first like I suggested above.

Also, do we need to set `HistogramData`?

hmm, I see that a lot of this was copied from forecast.go. Maybe @michae2 has some answers to my questions here
</blockquote></details>

`HistogramData` is needed by the `SHOW STATISTICS USING JSON` code, which is the reason forecasting did this awkward stuff. `HistogramData` is not supposed to contain a null bucket, so first we convert the `histogram` without null bucket to `HistogramData` to make `SHOW STATISTICS` work, then we add the null bucket to the `histogram` to make the `TableStatistic` look right to the optimizer.

If it would be easier to add a null bucket before converting to `HistogramData`, we could change `toHistogramData` to skip over that bucket. It wasn't helpful in the case of forecasts (which only manipulate the non-null part of the histogram) but there's no reason we couldn't do it.
___
*[`pkg/sql/stats/merge.go` line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIZcG_27rdEMDxW0WAI:-NIZ_LCCDPdxdSg_pdXP:bnjhajk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/merge.go#L97)):*
> ```Go
> 		i++
> 	}
> ```

This merge algorithm is the right idea, but is not really robust to overlaps. And overlaps can be a problem. For example, here's a case where the histogram from the partial statistics appears to have no "hole" at all:

```
CREATE TABLE b (b PRIMARY KEY) WITH (sql_stats_automatic_collection_enabled = false) AS SELECT 5;
CREATE STATISTICS b_full ON b FROM b;
INSERT INTO b SELECT generate_series(0, 4) UNION ALL SELECT generate_series(6, 1990);
CREATE STATISTICS b_partial ON b FROM b USING EXTREMES;
SHOW STATISTICS FOR TABLE b;
```

Here's `SHOW HISTOGRAM` for the full stats:

```
demo@127.0.0.1:26257/defaultdb> SHOW HISTOGRAM 819914366775525377;

  upper_bound | range_rows | distinct_range_rows | equal_rows
--------------+------------+---------------------+-------------
  5           |          0 |                   0 |          1
(1 row)
```

If we `SHOW HISTOGRAM` for the partial stats, the histogram has a bucket from 1-10, totally covering the old value of 5:

```
demo@127.0.0.1:26257/defaultdb> SHOW HISTOGRAM 819914435845455873;

  upper_bound | range_rows | distinct_range_rows | equal_rows
--------------+------------+---------------------+-------------
  0           |          0 |                   0 |          1
  10          |          9 |   8.994350282485833 |          1
  20          |          9 |   8.994978028876291 |          1
  30          |          9 |   8.994978028876291 |          1
  40          |          9 |   8.994978028876291 |          1
...
```

If we follow this algorithm, I believe the merged histogram will look something like:

```
{0, 0, 0, 1}
{5, 0, 0, 1}
{10, 9, 8.99, 1}
...
```

This isn't right (it says there are zero rows from (0-5) and 9 rows from (5-10) when there are in fact four and four).

I think to make merging robust to overlaps, we would need to know where the "hole" is. One way to do this would be to parse the predicate, like you were trying. But another way, perhaps easier, would be to encode the "hole" in the histogram itself using buckets with negative counts. This means we would need to teach `EquiDepthHistogram` about the holes. I don't think that would be too tough.


<!-- Sent from Reviewable.io -->

2022-12-06 15:31 UTC, mgartner commented
*[`pkg/sql/stats/merge.go` line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIZcG_27rdEMDxW0WAI:-NIc2EIh-bxSFYeGi0zZ:buw00ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/merge.go#L97)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

This merge algorithm is the right idea, but is not really robust to overlaps. And overlaps can be a problem. For example, here's a case where the histogram from the partial statistics appears to have no "hole" at all:

```
CREATE TABLE b (b PRIMARY KEY) WITH (sql_stats_automatic_collection_enabled = false) AS SELECT 5;
CREATE STATISTICS b_full ON b FROM b;
INSERT INTO b SELECT generate_series(0, 4) UNION ALL SELECT generate_series(6, 1990);
CREATE STATISTICS b_partial ON b FROM b USING EXTREMES;
SHOW STATISTICS FOR TABLE b;
```

Here's `SHOW HISTOGRAM` for the full stats:

```
demo@127.0.0.1:26257/defaultdb> SHOW HISTOGRAM 819914366775525377;

  upper_bound | range_rows | distinct_range_rows | equal_rows
--------------+------------+---------------------+-------------
  5           |          0 |                   0 |          1
(1 row)
```

If we `SHOW HISTOGRAM` for the partial stats, the histogram has a bucket from 1-10, totally covering the old value of 5:

```
demo@127.0.0.1:26257/defaultdb> SHOW HISTOGRAM 819914435845455873;

  upper_bound | range_rows | distinct_range_rows | equal_rows
--------------+------------+---------------------+-------------
  0           |          0 |                   0 |          1
  10          |          9 |   8.994350282485833 |          1
  20          |          9 |   8.994978028876291 |          1
  30          |          9 |   8.994978028876291 |          1
  40          |          9 |   8.994978028876291 |          1
...
```

If we follow this algorithm, I believe the merged histogram will look something like:

```
{0, 0, 0, 1}
{5, 0, 0, 1}
{10, 9, 8.99, 1}
...
```

This isn't right (it says there are zero rows from (0-5) and 9 rows from (5-10) when there are in fact four and four).

I think to make merging robust to overlaps, we would need to know where the "hole" is. One way to do this would be to parse the predicate, like you were trying. But another way, perhaps easier, would be to encode the "hole" in the histogram itself using buckets with negative counts. This means we would need to teach `EquiDepthHistogram` about the holes. I don't think that would be too tough.
</blockquote></details>

By "hole" do you mean the range of values already in the histrogram? We should know that - the lower bound should be indicated by a bucket with `num_range=0`. So in this example, we know the hole is `[5, 5]`.


<!-- Sent from Reviewable.io -->

2022-12-06 15:34 UTC, mgartner commented
*[`pkg/sql/stats/merge.go` line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIZcG_27rdEMDxW0WAI:-NIc3YfT7RGzNORUPN7R:b-kibvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/merge.go#L97)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

By "hole" do you mean the range of values already in the histrogram? We should know that - the lower bound should be indicated by a bucket with `num_range=0`. So in this example, we know the hole is `[5, 5]`.
</blockquote></details>

And we shouldn't have any overlaps because we scanned down from the lower bound and up from the upper bound.


<!-- Sent from Reviewable.io -->

2022-12-06 15:42 UTC, mgartner requested changes
> Reviewed 3 of 9 files at r1, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @michae2, and @rytaft)

___
*[`pkg/sql/distsql_plan_stats.go` line 232 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc-xow5aKXCHAiZmJj:-NIc-xox3vQmd-YaQtX7:bfa00im) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/distsql_plan_stats.go#L232)):*
> ```Go
> 			t.PartialPredicate == "" &&
> 			t.Name != jobspb.ForecastStatsName &&
> 			t.Name != jobspb.MergedStatsName &&
> ```

Ideally we wouldn't rely on the name here - someone could create a full table stat with one of these special names, though that's unlikely. I think we can simply add an enum to `stats.TableStatistics` to indicate the type of stat. Can you leave a TODO for this?
___
*[`pkg/sql/stats/merge.go` line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc3DhPBdBq3pZOcodc:-NIc3DhPBdBq3pZOcodd:b15addz) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L26)):*
> ```Go
> 
> // mergeExtremesStatistic merges a full table statistic with a partial table statistic
> // and returns a new full table statistic.
> ```

Can you describe how the merge algorithm works in this comment? Running through an example(s) may be helpful too.
___
*[`pkg/sql/stats/merge.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc16NW4sisf6yW_HYM:-NIc16NW4sisf6yW_HYN:b-4mvapm) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L34)):*
> ```Go
> 	if fullStatColKey != partialStatColKey {
> 		log.VEventf(ctx, 2, "Column sets for full table statistics and partial table statistics column sets do not match")
> 		return fullStat, nil
> ```

Shouldn't an error be returned in this case?
___
*[`pkg/sql/stats/merge.go` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc1IVm6qq3MCOaSii7:-NIc1IVm6qq3MCOaSii8:b-5bimzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L39)):*
> ```Go
> 	// Merge the histograms
> 	// Currently, since we don't merge multi-column statistics, each
> 	// statistic passed through should have a histogram.
> ```

nit: might be safest to check for histograms here.
___
*[`pkg/sql/stats/merge.go` line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc3oD8-zIN6FQvOTTD:-NIc3oD9EMLBfgPNUr2B:b-spbht4) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L70)):*
> ```Go
> 
> 				i++
> 			} else if val == 0 {
> ```

I don't understand this case. When would we have a bucket in the partial stats that has the same upper bound as a bucket in the full stats?
___
*[`pkg/sql/stats/merge.go` line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc45lgDA1HTEIDA19E:-NIc45lgDA1HTEIDA19F:b-8x16f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L150)):*
> ```Go
> 	// mapping the columnID set to the latest partial table stat.
> 	// It relies on the fact that the first partial stat for that
> 	// column is the latest due to the query that calls this.
> ```

What do you mean by "due to the query the calls this"?
___
*[`pkg/sql/stats/merge_test.go` line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc4scJ7VLvSe7dhNvt:-NIc4scJ7VLvSe7dhNvu:b-5vvd6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge_test.go#L95)):*
> ```Go
> 					{1, 0, 0, 3},
> 					{1, 0, 0, 4},
> 					{1, 0, 0, 5},
> ```

Is this case possible? Aren't we scanning only values less than 5? If it is possible, do we expect the original `{3, 3, 2, 5}` to be ignored in the result like it is below?


<!-- Sent from Reviewable.io -->

2022-12-06 17:08 UTC, michae2 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/stats/merge.go` line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIZcG_27rdEMDxW0WAI:-NIcMXMg3BbQe8uD0g07:ba096qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/merge.go#L97)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

And we shouldn't have any overlaps because we scanned down from the lower bound and up from the upper bound.
</blockquote></details>

Sorry, I didn't explain myself clearly. By "hole" I meant the part of the index not scanned. By "overlaps" I meant overlaps between the bucket bounds of the old histogram and the bucket bounds of the new histogram (not overlaps between the two parts of the the index scanned).

Yeah, we could also use the old histogram bounds to "punch a hole" in the new histogram. That will involve splitting histogram buckets, which is fine, also doable. Probably just a small change from the existing code.


<!-- Sent from Reviewable.io -->

2022-12-06 17:35 UTC, michae2 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/stats/merge.go` line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc3oD8-zIN6FQvOTTD:-NIcR_Ai0j2Jx8hKrbuh:bn2suy3) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L70)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't understand this case. When would we have a bucket in the partial stats that has the same upper bound as a bucket in the full stats?
</blockquote></details>

On the happy path I don't think this is possible, but there are some unhappy paths where we could be merging with full stats that weren't the ones we used to pick the USING EXTREMES bounds. For example, we saw one such unhappy path in https://github.com/cockroachdb/cockroach/issues/92559 when the stats cache hadn't yet loaded the latest full stats. Another unhappy path is when some full stats are deleted from `system.table_statistics` and we're now trying to merge with older full stats.

Another case worth thinking about is a full stats histogram representing {12, 13, 14} like:

```
{upperBound: 12, numRange: 0, numEq: 1}
{upperBound: 14, numRange: 1, numEq: 1}
```

being merged with a partial stats histogram representing {10, 11, 15, 16} like:

```
{upperBound: 10, numRange: 0, numEq: 1}
{upperBound: 12, numRange: 1, numEq: 0}
{upperBound: 16, numRange: 1, numEq: 1}
```

In this case the upper bounds are equal even though the scanned values are disjoint.

Currently I don't think we'll generate histograms like this, but there's nothing in `EquiDepthHistogram`'s contract that says it can't. Forecasted histograms can look like this.


<!-- Sent from Reviewable.io -->

2022-12-09 23:40 UTC, faizaanmadhani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIJ3bHOAXTOhTVvMpS7):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Since you're noting that the optimizer now uses these stats, it would be good to include a couple of tests where you show that the optimizer uses the merged stats.  A good place for this would probably be in a new file `pkg/sql/opt/exec/execbuilder/testdata/partial_stats` (similar to the `forecast` file in the same directory). No need to actually generate partial stats -- you can just inject them with `INJECT STATISTICS`. Alternatively, you could add a file `pkg/sql/opt/memo/testdata/stats/partial_stats` and add the tests there.
</blockquote></details>

Done. I added tests in `partial_stats`!
___
*[`pkg/sql/distsql_plan_stats.go` line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIZGvys38IN-i52-qve:-NIt3Sd_Et6E3z-ucRBt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/distsql_plan_stats.go#L227)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

(You might already be doing this.) As mentioned [here](https://github.com/cockroachdb/cockroach/pull/91228#pullrequestreview-1192405950) we also need to avoid looking at table statistics with inverted histograms for `ARRAY` and `STRING` types.
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_plan_stats.go` line 232 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc-xow5aKXCHAiZmJj:-NIgvF1QEY2IGoK84bEX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/distsql_plan_stats.go#L232)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ideally we wouldn't rely on the name here - someone could create a full table stat with one of these special names, though that's unlikely. I think we can simply add an enum to `stats.TableStatistics` to indicate the type of stat. Can you leave a TODO for this?
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIv1bZCbPEiLzHqjsh:-NIt5XbTDyVxUynx2S98:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L147)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

`HistogramData` is needed by the `SHOW STATISTICS USING JSON` code, which is the reason forecasting did this awkward stuff. `HistogramData` is not supposed to contain a null bucket, so first we convert the `histogram` without null bucket to `HistogramData` to make `SHOW STATISTICS` work, then we add the null bucket to the `histogram` to make the `TableStatistic` look right to the optimizer.

If it would be easier to add a null bucket before converting to `HistogramData`, we could change `toHistogramData` to skip over that bucket. It wasn't helpful in the case of forecasts (which only manipulate the non-null part of the histogram) but there's no reason we couldn't do it.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIIwcp53dx6dOuzyGTU:-NIt5_FK1CqFYEb_DhAJ:bk7s7zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/31edf0ab175ffdabc6d26fb7ea02ecdd78cb6fd2/pkg/sql/stats/merge.go#L156)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Sounds good!
</blockquote></details>

Added support to `show_stats.go`! Also CreateMergedStatistics was moved to the top of the file since it's exported.
___
*[`pkg/sql/stats/merge.go` line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIZcG_27rdEMDxW0WAI:-NIc3Lk--DFiQ_nntKcm:b-6o81nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/merge.go#L97)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Sorry, I didn't explain myself clearly. By "hole" I meant the part of the index not scanned. By "overlaps" I meant overlaps between the bucket bounds of the old histogram and the bucket bounds of the new histogram (not overlaps between the two parts of the the index scanned).

Yeah, we could also use the old histogram bounds to "punch a hole" in the new histogram. That will involve splitting histogram buckets, which is fine, also doable. Probably just a small change from the existing code.
</blockquote></details>

Resolved offline. I've added the associated changes we discussed in `ConstructExtremesHistogram`.
___
*[`pkg/sql/stats/merge.go` line 158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIYewOFC284hOFtPT5I:-NItFZp0-w7GOMBEjiAZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/merge.go#L158)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: amount -> number
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIYfjln7xtorR92mtms:-NIgvoyH5S2EGVwIWiNy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7417f1fbc8107e0b7acc060d1fdff7f2ca5f781/pkg/sql/stats/merge.go#L172)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you can simplify this and the below logic a lot:
1. You don't need to create the slice `colKeys`, since you can just iterate through the map using
```
for col, stats := range fullStatsMap {
```
  You can also use `len(fullStatsMap)` to determine the capacity of `mergedStats`

2. You don't need to keep the map `colKeyToNumCols`, since you're only using it below to check whether the stats have a single column. I think you can just avoid putting any stats in the `fullStatsMap` that have more than one column

3. If you only store stats with one column, you don't need to call `MakeSortedColStatKey`, and you can just use the one column as a key of type `int`.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc3DhPBdBq3pZOcodc:-NIt44NVBt6WyiK9h6Zb:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L26)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you describe how the merge algorithm works in this comment? Running through an example(s) may be helpful too.
</blockquote></details>

Done!
___
*[`pkg/sql/stats/merge.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc16NW4sisf6yW_HYM:-NIgvI3M8M_I-hj1GTju:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L34)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Shouldn't an error be returned in this case?
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc1IVm6qq3MCOaSii7:-NIt4CEz41yA8XCLkxcT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L39)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: might be safest to check for histograms here.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 70 at r4](https://reviewable.io/reviews/cockroach [...]

2022-12-12 20:20 UTC, michae2 requested changes
> Reviewed 1 of 11 files at r5, 1 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/distsql_plan_stats.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NItOEWS7IYmQM_jVRSs:-NItOEWS7IYmQM_jVRSt:bfh803p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ce5f0297453d527b67272bd7d92b5c1737140a0/pkg/sql/distsql_plan_stats.go#L238)):*
> ```Go
> 			t.Name != jobspb.ForecastStatsName &&
> 			t.Name != jobspb.MergedStatsName &&
> 			(!colinfo.ColumnTypeIsInvertedIndexable(column.GetType()) || t.HistogramData.ColumnType.Family() != types.BytesFamily) {
> ```

Thanks for adding this check! I just realized I left out one part, sorry: before checking `t.HistogramData.ColumnType.Family() != types.BytesFamily` we need to guard against HistogramData being nil or ColumnType being nil (this was the cause of #92489). If either of these are nil we can proceed (we'll immediately hit the empty histogram error case below, which is what we want). So this needs to be something like:

```
(!colinfo.ColumnTypeIsInvertedIndexable(column.GetType()) || t.HistogramData == nil || t.HistogramData.ColumnType == nil || t.HistogramData.ColumnType.Family() != types.BytesFamily)
```

(Wow, that's ugly... :slightly_smiling_face: Might be better as a helper function.)
___
*[`pkg/sql/distsql_plan_stats.go` line 283 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6m6Kv-bfojcGoWRVW:-NJ6m6Kv-bfojcGoWRVX:b-x54eiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/distsql_plan_stats.go#L283)):*
> ```Go
> 		Columns:             make([]uint32, len(reqStat.columns)),
> 		StatName:            reqStat.name,
> 		PartialPredicate:    extremesPredicate,
> ```

Should we be setting `LowerBound` here?
___
*[`pkg/sql/execinfrapb/processors_table_stats.proto` line 59 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6mEe18_rjmBIgI5p0:-NJ6mEe18_rjmBIgI5p1:b-exeldo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/execinfrapb/processors_table_stats.proto#L59)):*
> ```protobuf
>   optional string partial_predicate = 7 [(gogoproto.nullable) = false];
> 
>   optional string lower_bound = 8 [(gogoproto.nullable) = false];
> ```

nit: This needs a comment. (The field will be called `LowerBound` in the generated go code.)
___
*[`pkg/sql/stats/histogram.go` line 99 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6ud2x8J7R7WgZp0MZ:-NJ6ud2x8J7R7WgZp0M_:b-2xoh0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L99)):*
> ```Go
> 	_, h, err := equiDepthHistogramWithoutAdjustment(compareCtx, colType, samples, numRows, distinctCount, maxBuckets)
> 	if err != nil {
> 		return HistogramData{}, []cat.HistogramBucket{}, err
> ```

Instead of `[]cat.HistogramBucket{}` we should return `nil` for the error cases.
___
*[`pkg/sql/stats/histogram.go` line 122 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6tHQy-euaBsHn155c:-NJ6tHQy-euaBsHn155d:b5w19ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L122)):*
> ```Go
> 			ColumnType: colType, Buckets: make([]HistogramData_Bucket, 0), Version: histVersion,
> 		}, histogram{}, nil
> 	}
> ```

This `numSamples == 0` check needs to be lifted up to `EquiDepthHistogram` / `ConstructExtremesHistogram` because it's not an error case, just an early exit. And then we won't need `equiDepthHistogramWithoutAdjustment` to return a `HistogramData` at all.
___
*[`pkg/sql/stats/histogram.go` line 131 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6tbn-76Y-JTd2RZea:-NJ6tbn-76Y-JTd2RZeb:b4rvpxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L131)):*
> ```Go
> 	if distinctCount == 0 {
> 		return HistogramData{}, histogram{}, errors.Errorf("histogram requires distinctCount > 0")
> 	}
> ```

Let's also lift this `distinctCount` check up to `EquiDepthHistogram` / `ConstructExtremesHistogram`, because then we won't need to pass `distinctCount` into this function at all.
___
*[`pkg/sql/stats/histogram.go` line 192 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6rOCp6qXTWsBcfNYc:-NJ6rOCp6qXTWsBcfNYd:b-vyz2u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L192)):*
> ```Go
> 	}
> 
> 	histogramData, err := h.toHistogramData(colType)
> ```

We should only be doing this conversion at the end of `EquiDepthHistogram` / `ConstructExtremesHistogram`. I don't think we need `equiDepthHistogramWithoutAdjustment` to return a `HistogramData` at all.
___
*[`pkg/sql/stats/histogram.go` line 196 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6ofPpErsIprcoZzdF:-NJ6ofPpErsIprcoZzdG:b-afbu8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L196)):*
> ```Go
> }
> 
> // ConstructExtremesHistogram returns a histogram that are is equi-depth
> ```

nit: Should this read "... a histogram that is two equi-depth ..."?
___
*[`pkg/sql/stats/histogram.go` line 213 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6z-1V7t56mqFwaqeR:-NJ6z-1V7t56mqFwaqeS:b-44i50t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L213)):*
> ```Go
> 	if maxBuckets < 2 {
> 		return HistogramData{}, []cat.HistogramBucket{}, errors.Errorf("partial histogram requires at least four buckets")
> 	}
> ```

This should be `if maxBuckets < 4`.
___
*[`pkg/sql/stats/histogram.go` line 218 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6qeFE1RZZPoP6W1PI:-NJ6qeFE1RZZPoP6W1PJ:b-uk1hr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L218)):*
> ```Go
> 	var upperSamples tree.Datums
> 	for _, val := range values {
> 		if c := val.Compare(compareCtx, lowerBound); c == -1 {
> ```

nit: In new code, instead of `Compare` we usually use `CompareError`.
___
*[`pkg/sql/stats/histogram.go` line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6xGF4-Q6UugyNQkK7:-NJ6xGF4-Q6UugyNQkK8:bp2bbwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L236)):*
> ```Go
> 	estNumRowsLower := (int64(lowerSamples.Len()) * numRows) / numTotalSamples
> 	estNumRowsUpper := (int64(upperSamples.Len()) * numRows) / numTotalSamples
> 	_, lowerHist, err := equiDepthHistogramWithoutAdjustment(compareCtx, colType, lowerSamples, estNumRowsLower, distinctCount, maxBuckets/2)
> ```

Instead of `maxBuckets/2` we should give each histogram a proportion of buckets matching the proportion of samples.

And also, if one slice of samples was empty we can skip calling `equiDepthHistogramWithoutAdjustment` for that part entirely.


<!-- Sent from Reviewable.io -->

2022-12-12 21:26 UTC, rytaft reviewed
> Reviewed 1 of 5 files at r4, 1 of 11 files at r5, 5 of 11 files at r6, 3 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @michae2)

___
*[`pkg/sql/execinfrapb/processors_table_stats.proto` line 59 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6mEe18_rjmBIgI5p0:-NJ7CDUYDt72Jeiy5ueN:bo158zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/execinfrapb/processors_table_stats.proto#L59)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: This needs a comment. (The field will be called `LowerBound` in the generated go code.)
</blockquote></details>

Also -- maybe a better name is `prev_lower_bound`? Or something like that...
___
*[`pkg/sql/stats/merge.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc16NW4sisf6yW_HYM:-NJ77moYDwXiLtz1Sgm-:bv7jiuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L34)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Shouldn't this be an assertion failure? (errrors.AssertionFailed)
___
*[`pkg/sql/stats/merge.go` line 51 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ74qh37QUlPI1JDZ-X:-NJ74qh45YbFT39OyjhM:bdfai7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/merge.go#L51)):*
> ```Go
> 	fullStatsMap := make(map[descpb.ColumnID]*TableStatistic)
> 	for _, stat := range fullStatsList {
> 		col := stat.ColumnIDs[0]
> ```

nit: move this inside the `if` block
___
*[`pkg/sql/stats/merge.go` line 64 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ758xA6COTyWLbkplU:-NJ758xBAaOXIUw9Im2H:b-j011pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/merge.go#L64)):*
> ```Go
> 		var merged *TableStatistic
> 		var err error
> 		if val, ok := partialStatsMap[col]; ok && val.CreatedAt.After(fullStatsMap[col].CreatedAt) {
> ```

nit: `fullStatsMap[col]`-> `fullStat` 
___
*[`pkg/sql/stats/merge.go` line 88 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ76GRQCVoAFiYaVAyN:-NJ76GRQCVoAFiYaVAyO:b-5gvc2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/merge.go#L88)):*
> ```Go
> //
> // For example, consider this case:
> // Full Statistic: {row: 14, dist: 9, null: 4, size: 1}
> ```

nit: where do you get row: 14 from? or dist: 9? Based on the full stat histogram, I would assume this should be row: 5 and dist: 5 (or maybe dist: 6 since you're including null values... probably a good idea to create a table with some rows and actually look at what the stats look like)

Let's try to make this example as realistic as possible while still being simple and useful.
___
*[`pkg/sql/stats/merge.go` line 91 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ76Pbr969n_Md3MXX9:-NJ76Pbr969n_Md3MXXA:b274t2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/merge.go#L91)):*
> ```Go
> // CreatedAt: 2022-01-02
> // Histogram (format is: {NumEq, NumRange, DistinctRange, UpperBound}):
> // [{1, 0, 0, 2}, {1, 1, 0, 4}, {1, 1, 0, 6}]
> ```

nit: If NumRange is non-zero, DistinctRange should also be non-zero
___
*[`pkg/sql/stats/merge.go` line 144 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ78CFwDQnj2VsBqPbV:-NJ78CFwDQnj2VsBqPbW:bbdxzr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/merge.go#L144)):*
> ```Go
> 	if len(partialHistogram) == 0 {
> 		fullStat.Name = jobspb.MergedStatsName
> 		fullStat.CreatedAt = partialStat.CreatedAt
> ```

shouldn't we at least perform a shallow copy here to avoid modifying `fullStat`? (we don't need to deep copy the histogram since it's not changing).
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 1 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ797r-3e6639INCTMC:-NJ797r-3e6639INCTMD:buycm8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L1)):*
> ```
> # LogicTest: local
> ```

Can you add some tests with histograms that have some buckets with a non-zero NumRange and DistinctRange?
___
*[`pkg/sql/stats/histogram_test.go` line 275 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ7AH_h8vRHFg46gzCG:-NJ7AH_i5aWuVYi7SVCD:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram_test.go#L275)):*
> ```Go
> 
> func TestConstructExtremesHistogram(t *testing.T) {
> ```

nit: remove blank line


<!-- Sent from Reviewable.io -->

2022-12-12 23:25 UTC, faizaanmadhani reviewed
Thanks for the review! I've addressed most of the comments but there's still one or two left and I need to add some additional tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJ7dw4Y0ch_FgsQTAiO:bnpgisd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/distsql_plan_stats.go` line 283 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6m6Kv-bfojcGoWRVW:-NJ7YHhb0lirMs89zgt9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/distsql_plan_stats.go#L283)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should we be setting `LowerBound` here?
</blockquote></details>

Done.
___
*[`pkg/sql/stats/histogram.go` line 99 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6ud2x8J7R7WgZp0MZ:-NJ7dgi3ApZT0QJUv_4y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L99)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Instead of `[]cat.HistogramBucket{}` we should return `nil` for the error cases.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/histogram.go` line 122 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6tHQy-euaBsHn155c:-NJ7dhu3DaYLTSuQ7pSp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L122)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

This `numSamples == 0` check needs to be lifted up to `EquiDepthHistogram` / `ConstructExtremesHistogram` because it's not an error case, just an early exit. And then we won't need `equiDepthHistogramWithoutAdjustment` to return a `HistogramData` at all.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/histogram.go` line 131 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6tbn-76Y-JTd2RZea:-NJ7diA-9PkX9rx2Wi1I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L131)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Let's also lift this `distinctCount` check up to `EquiDepthHistogram` / `ConstructExtremesHistogram`, because then we won't need to pass `distinctCount` into this function at all.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/histogram.go` line 192 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6rOCp6qXTWsBcfNYc:-NJ7djVV9jCHqD9UD3i5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L192)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

We should only be doing this conversion at the end of `EquiDepthHistogram` / `ConstructExtremesHistogram`. I don't think we need `equiDepthHistogramWithoutAdjustment` to return a `HistogramData` at all.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/histogram.go` line 213 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6z-1V7t56mqFwaqeR:-NJ7dlXv9NAeQkqSoUgU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L213)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

This should be `if maxBuckets < 4`.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/histogram.go` line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6xGF4-Q6UugyNQkK7:-NJ7doE91DbqoQlgB7_a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L236)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Instead of `maxBuckets/2` we should give each histogram a proportion of buckets matching the proportion of samples.

And also, if one slice of samples was empty we can skip calling `equiDepthHistogramWithoutAdjustment` for that part entirely.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 144 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ78CFwDQnj2VsBqPbV:-NJ7dseZ8XUD7g6MY6A0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/merge.go#L144)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

shouldn't we at least perform a shallow copy here to avoid modifying `fullStat`? (we don't need to deep copy the histogram since it's not changing).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-12 23:49 UTC, mgartner commented
*[`pkg/sql/stats/histogram.go` line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6xGF4-Q6UugyNQkK7:-NJ7jI_N9wPZEHN4WUL7:bwg9zer) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L236)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is this really necessary? 100 buckets for both min and max extremes should be plenty - that's up to half of the size of the full histogram. I doubt we'd need granularity beyond that. It might be safest to cap it at a reasonable fixed value like 20 to avoid bloating the histogram.


<!-- Sent from Reviewable.io -->

2022-12-12 23:51 UTC, faizaanmadhani commented
*[`pkg/sql/stats/histogram.go` line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6xGF4-Q6UugyNQkK7:-NJ7juKK8xreLSBSp34A:b-65y8cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L236)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is this really necessary? 100 buckets for both min and max extremes should be plenty - that's up to half of the size of the full histogram. I doubt we'd need granularity beyond that. It might be safest to cap it at a reasonable fixed value like 20 to avoid bloating the histogram.
</blockquote></details>

Also, oops, sorry about the "Done". I did not mean to resolve this comment :) 


<!-- Sent from Reviewable.io -->

2022-12-13 16:30 UTC, mgartner reviewed
> Reviewed 3 of 11 files at r5, 3 of 11 files at r6, 1 of 4 files at r7, 2 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @michae2, and @rytaft)

___
*[`pkg/sql/show_stats.go` line 69 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJB97jE5u7FhJ8cF-Gm:-NJB97jE5u7FhJ8cF-Gn:b-mmmqm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/show_stats.go#L69)):*
> ```Go
> }
> 
> func ignoreDroppedColumn(colIDs tree.Datums, desc catalog.TableDescriptor) (bool, error) {
> ```

nit: `ignoreDroppedColumn` => `containsDroppedColumn`
___
*[`pkg/sql/show_stats.go` line 177 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJB9JsJ54VXkFEkudnF:-NJB9JsJ54VXkFEkudnG:b-55jemo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a36338f8d21432abf0bb6126d4f0d255ea1da28/pkg/sql/show_stats.go#L177)):*
> ```Go
> 				observed := make([]*stats.TableStatistic, 0, len(rows))
> 				for _, row := range rows {
> 					// Skip stats on dropped columns.
> ```

nit: keep this comment.
___
*[`pkg/sql/show_stats.go` line 221 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBCh1g-kGpi6U2nQP5:-NJBCh1g-kGpi6U2nQP6:bg8kinx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/show_stats.go#L221)):*
> ```Go
> 				}
> 				// Reverse the partial and full stats lists to
> 				// sort by createdAt time.
> ```

Aren't they already ordered by createdAt? Do you mean to order them by createdAt descending?
___
*[`pkg/sql/show_stats.go` line 263 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBEcqy4xOAIshLrwO4:-NJBEcqy4xOAIshLrwO5:bpiif41) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/show_stats.go#L263)):*
> ```Go
> 					obs := &stats.TableStatistic{TableStatisticProto: *stat}
> 					if obs.HistogramData != nil && !obs.HistogramData.ColumnType.UserDefined() {
> 						if err := stats.DecodeHistogramBuckets(obs); err != nil {
> ```

Haven't we already decoded the histogram buckets (besides the merged one). Can we avoid duplicating work by using `obsFullStats` instead of `rows`?
___
*[`pkg/sql/execinfrapb/processors_table_stats.proto` line 63 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBEv_99O6VFCmPMpX8:-NJBEv_99O6VFCmPMpX9:baqpn8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/execinfrapb/processors_table_stats.proto#L63)):*
> ```protobuf
>   // It is used as the boundary between the lower extreme histogram and
>   // the upper extreme histogram when partial statistics USING EXTREMES
>   // are collected and the histogram is constructed.
> ```

nit: mention that it is the empty string if the sketchspec is for a full stat collection
___
*[`pkg/sql/rowexec/sample_aggregator.go` line 444 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBFBvP93MulatzoMM0:-NJBFBvP93MulatzoMM1:b-6hgf9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/rowexec/sample_aggregator.go#L444)):*
> ```Go
> 				typ := s.inTypes[colIdx]
> 
> 				lowerBound := tree.DNull
> ```

I think we should use `nil` here instead of `tree.DNull` to differentiate between "no lower bound" and "lower bound is the NULL SQL value"
___
*[`pkg/sql/rowexec/sample_aggregator.go` line 646 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBFS5YDjivG-3DEqw9:-NJBFS5YDjivG-3DEqwA:bxb0xba) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/rowexec/sample_aggregator.go#L646)):*
> ```Go
> 	}
> 
> 	if lowerBound != tree.DNull {
> ```

`tree.DNull` => `nil`
___
*[`pkg/sql/stats/histogram.go` line 197 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBG7nODydr_7xYuTXr:-NJBG7nODydr_7xYuTXs:b-58g5tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/stats/histogram.go#L197)):*
> ```Go
> // equiDepthHistogramWithoutAdjustment. The first histogram covers the range of
> // samples up to the value specified by lowerBound and the second histogram
> // covers the values up from lowerBound to the maximum. This function assumes
> ```

nit: Can you make it clear if the two histograms are inclusive or exclusive of the lowerBound.
___
*[`pkg/sql/stats/histogram.go` line 199 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBGm_10aiuIsskFznb:-NJBGm_10aiuIsskFznc:b6qfpna) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/stats/histogram.go#L199)):*
> ```Go
> // covers the values up from lowerBound to the maximum. This function assumes
> // that the sample only includes values from the extremes of the column.
> func ConstructExtremesHistogram(
> ```

nit: organizationally it might be nice to put this function right under `EquiDepthHistogram` and rename this to be similar so it's obvious that they are doing similar things. Maybe `EquiDepthExtremesHistogram` or something?
___
*[`pkg/sql/stats/histogram.go` line 230 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBG_hDEoxcc1rhwgwh:-NJBG_hDEoxcc1rhwgwi:b-jy5xck) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/stats/histogram.go#L230)):*
> ```Go
> 	numTotalSamples := int64(values.Len())
> 	if numTotalSamples == 0 {
> 		return HistogramData{
> ```

nit: move this early return up above the for loop


<!-- Sent from Reviewable.io -->

2022-12-13 16:40 UTC, rytaft reviewed
getting very close!

> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJBM-Yb2ukG_mFZb7Xh:b8ylwsy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @michae2)



<!-- Sent from Reviewable.io -->

2022-12-13 20:51 UTC, faizaanmadhani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/distsql_plan_stats.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NItOEWS7IYmQM_jVRSs:-NJB1YDP054cNoFjP4Mi:bdjurw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ce5f0297453d527b67272bd7d92b5c1737140a0/pkg/sql/distsql_plan_stats.go#L238)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Thanks for adding this check! I just realized I left out one part, sorry: before checking `t.HistogramData.ColumnType.Family() != types.BytesFamily` we need to guard against HistogramData being nil or ColumnType being nil (this was the cause of #92489). If either of these are nil we can proceed (we'll immediately hit the empty histogram error case below, which is what we want). So this needs to be something like:

```
(!colinfo.ColumnTypeIsInvertedIndexable(column.GetType()) || t.HistogramData == nil || t.HistogramData.ColumnType == nil || t.HistogramData.ColumnType.Family() != types.BytesFamily)
```

(Wow, that's ugly... :slightly_smiling_face: Might be better as a helper function.)
</blockquote></details>

Done. Added this predicate and moved the check to a helper function.
___
*[`pkg/sql/show_stats.go` line 69 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJB97jE5u7FhJ8cF-Gm:-NJCDC-W9GRRMYXnbQ4I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/show_stats.go#L69)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `ignoreDroppedColumn` => `containsDroppedColumn`
</blockquote></details>

Done.
___
*[`pkg/sql/show_stats.go` line 177 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJB9JsJ54VXkFEkudnF:-NJCDH8G9otG5keNOyBo:ba1p472) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a36338f8d21432abf0bb6126d4f0d255ea1da28/pkg/sql/show_stats.go#L177)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: keep this comment.
</blockquote></details>

Done. Added "Skip stats on dropped columns." back
___
*[`pkg/sql/show_stats.go` line 221 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBCh1g-kGpi6U2nQP5:-NJCDOpn98Mlo4nPc7TC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/show_stats.go#L221)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Aren't they already ordered by createdAt? Do you mean to order them by createdAt descending?
</blockquote></details>

Done.
___
*[`pkg/sql/show_stats.go` line 263 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBEcqy4xOAIshLrwO4:-NJCDSjA-CtA09CWoPvO:b-d7enwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/show_stats.go#L263)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Haven't we already decoded the histogram buckets (besides the merged one). Can we avoid duplicating work by using `obsFullStats` instead of `rows`?
</blockquote></details>

Done. Consolidated all of this logic above.
___
*[`pkg/sql/rowexec/sample_aggregator.go` line 444 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBFBvP93MulatzoMM0:-NJCDppe0RE0ENPn0wb7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/rowexec/sample_aggregator.go#L444)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think we should use `nil` here instead of `tree.DNull` to differentiate between "no lower bound" and "lower bound is the NULL SQL value"
</blockquote></details>

Done.
___
*[`pkg/sql/rowexec/sample_aggregator.go` line 646 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBFS5YDjivG-3DEqw9:-NJCDqb22iCxo7bjaQux:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/rowexec/sample_aggregator.go#L646)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`tree.DNull` => `nil`
</blockquote></details>

Done.
___
*[`pkg/sql/stats/histogram.go` line 199 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBGm_10aiuIsskFznb:-NJCDyXD3Wl5_psMAfXe:bof231b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/stats/histogram.go#L199)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: organizationally it might be nice to put this function right under `EquiDepthHistogram` and rename this to be similar so it's obvious that they are doing similar things. Maybe `EquiDepthExtremesHistogram` or something?
</blockquote></details>

I moved the function above, but my only argument against naming it `EquiDepthExtremesHistogram` is that the returned histogram is not guaranteed to be equi-depth.
___
*[`pkg/sql/stats/merge.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc16NW4sisf6yW_HYM:-NJB1nIq9dAypTZg4I4b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L34)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Shouldn't this be an assertion failure? (errrors.AssertionFailed)
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 88 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ76GRQCVoAFiYaVAyN:-NJCETa48E20lr6159hs:b-6cck8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/merge.go#L88)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: where do you get row: 14 from? or dist: 9? Based on the full stat histogram, I would assume this should be row: 5 and dist: 5 (or maybe dist: 6 since you're including null values... probably a good idea to create a table with some rows and actually look at what the stats look like)

Let's try to make this example as realistic as possible while still being simple and useful.
</blockquote></details>

I went back through the example and fixed it. For the sake of simplicity as well, I set the first example to have just zero valued NumRange and DistinctRange values as well.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 1 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ797r-3e6639INCTMC:-NJC2mDU595viTMFMeJo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L1)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add some tests with histograms that have some buckets with a non-zero NumRange and DistinctRange?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-13 22:36 UTC, rytaft reviewed
> Reviewed 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @michae2)

___
*[`pkg/sql/distsql_plan_stats.go` line 166 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJCaWYQ5G4rGGaWT-Gr:-NJCaWYQ5G4rGGaWT-Gs:b-uticfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0201faf604ffcdfe6ec43e0fd110c3f973d48e45/pkg/sql/distsql_plan_stats.go#L166)):*
> ```Go
> // table statistic can be used as the base full statistic for a new partial
> // statistic collection, for the specified column.
> func isTableStatValid(column catalog.Column, t *stats.TableStatistic) bool {
> ```

This name is misleading -- it's not checking that the stat is valid, rather that it's valid *for the particular purpose described the comment*. Try to rename to give some hint about that.


<!-- Sent from Reviewable.io -->

2022-12-14 00:47 UTC, michae2 requested changes
> Reviewed 1 of 5 files at r4, 2 of 5 files at r9, 2 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/stats/histogram.go` line 236 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJ6xGF4-Q6UugyNQkK7:-NJBnEII390wz9xInJfA:bcxqaux) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a2fc6aaca10b378b98ca8a72b01f9c9219f8bcc/pkg/sql/stats/histogram.go#L236)):*
> Is this really necessary? 100 buckets for both min and max extremes should be plenty - that's up to half of the size of the full histogram. I doubt we'd need granularity beyond that. It might be safest to cap it at a reasonable fixed value like 20 to avoid bloating the histogram.

True, `maxBuckets/2` would still work. Maybe I'm overthinking it. (I was bothered that the histogram wouldn't be "equi-depth" any more if the rows weren't evenly distributed between upper and lower segments, but I suppose even if we made the number of buckets for each segment proportional to the number of rows for each segment, the merged histogram still wouldn't be equi-depth anyway. So maybe this doesn't matter.)
___
*[`pkg/sql/stats/histogram.go` line 145 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJCoJanD6fz9yR1M-Yt:-NJCoJanD6fz9yR1M-Yu:bq77n5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0201faf604ffcdfe6ec43e0fd110c3f973d48e45/pkg/sql/stats/histogram.go#L145)):*
> ```Go
> 		}, nil, nil
> 	}
> ```

We also need a copy of the `if distinctCount == 0` check here now that it's no longer in `equiDepthHistogramWithoutAdjustment`.
___
*[`pkg/sql/stats/merge.go` line 74 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJC3u0GB5j4E-jUdAvX:-NJC3u0GB5j4E-jUdAvY:b-kkqggf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/stats/merge.go#L74)):*
> ```Go
> 		}
> 	}
> 	return mergedStats
> ```

Appending to `mergedStats` while iterating over `fullStatsMap` won't necessarily produce a `mergedStats` sorted in descending `CreatedAt` order.

(Even though `mergedStats` contains at most one `TableStatistic` per column, we still want it to be sorted in descending `CreatedAt` order because the optimizer uses the first `TableStatistic` for the overall row count of the table, and we want that to be the freshest stat.)

One option is to sort the slice of `mergedStats` at the end. Another option is to do the appending to `mergedStats` while iterating over `partialStatsList` which should be in the correct order.

The latter option would be something like:
1. build `fullStatsMap`
2. iterate over `partialStatsMap` in order
   a. if we have already seen this column, skip
   b. if we haven't seen this column, perform the merge using `fullStatsMap`, append to `mergedStats`, and remember that we've seen this column

(Side note, this is the same algorithm as our hash join! :grin:)


<!-- Sent from Reviewable.io -->

2022-12-14 04:50 UTC, faizaanmadhani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/distsql_plan_stats.go` line 166 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJCaWYQ5G4rGGaWT-Gr:-NJDQKes5qwHWXQUqx0x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0201faf604ffcdfe6ec43e0fd110c3f973d48e45/pkg/sql/distsql_plan_stats.go#L166)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This name is misleading -- it's not checking that the stat is valid, rather that it's valid *for the particular purpose described the comment*. Try to rename to give some hint about that.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/histogram.go` line 145 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJCoJanD6fz9yR1M-Yt:-NJDwzH42mZranP41Ew9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0201faf604ffcdfe6ec43e0fd110c3f973d48e45/pkg/sql/stats/histogram.go#L145)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

We also need a copy of the `if distinctCount == 0` check here now that it's no longer in `equiDepthHistogramWithoutAdjustment`.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 74 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJC3u0GB5j4E-jUdAvX:-NJDx0ib41tvYRofsI-X:b-ix3r21) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/stats/merge.go#L74)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Appending to `mergedStats` while iterating over `fullStatsMap` won't necessarily produce a `mergedStats` sorted in descending `CreatedAt` order.

(Even though `mergedStats` contains at most one `TableStatistic` per column, we still want it to be sorted in descending `CreatedAt` order because the optimizer uses the first `TableStatistic` for the overall row count of the table, and we want that to be the freshest stat.)

One option is to sort the slice of `mergedStats` at the end. Another option is to do the appending to `mergedStats` while iterating over `partialStatsList` which should be in the correct order.

The latter option would be something like:
1. build `fullStatsMap`
2. iterate over `partialStatsMap` in order
   a. if we have already seen this column, skip
   b. if we haven't seen this column, perform the merge using `fullStatsMap`, append to `mergedStats`, and remember that we've seen this column

(Side note, this is the same algorithm as our hash join! :grin:)
</blockquote></details>

Done! I went with the second option.


<!-- Sent from Reviewable.io -->

2022-12-14 13:58 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (but wait for @mgartner and @michae2 to sign off) Nice work!

> Reviewed 3 of 4 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJFvEM9ENVnSwZepGNB:bstyzr7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)



<!-- Sent from Reviewable.io -->

2022-12-14 20:13 UTC, michae2 requested changes
Very close! I'm just reading the last bits.

> Reviewed 2 of 11 files at r5, 1 of 11 files at r6, 1 of 7 files at r10, 2 of 4 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJHGGHR6OogicSt2aoq:br3ubsi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @faizaanmadhani and @mgartner)

___
*[`pkg/sql/stats/merge.go` line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc3oD8-zIN6FQvOTTD:-NJH7n9BCOj-7039Q1MO:biq55u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L70)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Removed the case from the conditional. Stitching the Equi-Depth histograms together should guarantee no overlap.
</blockquote></details>

If we don't think we'll ever have buckets in partial and full with the same upper bounds, can we keep the = case but use it to return an error instead of handling it?
___
*[`pkg/sql/stats/merge.go` line 131 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJH15nr4m-uosIypfLf:-NJH15nr4m-uosIypfLg:b-yc044i) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d5236f803e3cc7a546add55c98fa14d1f2e8e2/pkg/sql/stats/merge.go#L131)):*
> ```Go
> 	if len(fullHistogram) == 0 {
> 		return fullStat, errors.New("the full statistic histogram does not exist")
> 	}
> ```

I think we should add one more check before we merge the histograms: a check that a call to `constructUsingExtremesPredicate` on the first and last non-NULL bounds of `fullHistogram` creates a predicate exactly matching `partialStat.PartialPredicate`. This will avoid most cases of merging a USING EXTREMES partial stat with a different full stat than the one it was based on.
___
*[`pkg/sql/stats/merge.go` line 155 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJGyVTY64-M816FaPpy:-NJGyVTY64-M816FaPpz:b-3wf3k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d5236f803e3cc7a546add55c98fa14d1f2e8e2/pkg/sql/stats/merge.go#L155)):*
> ```Go
> 	}
> 
> 	var cmpCtx *eval.Context
> ```

I'm a little nervous that this won't work for `TIME`, `TIMETZ`, `TIMESTAMP`, or `TIMESTAMPTZ` types which actually use this compare context in `CompareError`. But let me do some research, it might be ok. I remember it was ok for forecasting (which does work on `TIMESTAMP` and `TIMESTAMPTZ`).
___
*[`pkg/sql/stats/merge.go` line 166 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJH9wnCB7wTaJ8xXehd:-NJH9wnCB7wTaJ8xXehe:b-q3m3oj) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d5236f803e3cc7a546add55c98fa14d1f2e8e2/pkg/sql/stats/merge.go#L166)):*
> ```Go
> 			if val == -1 {
> 				mergedHistogram = append(mergedHistogram, partialHistogram[i])
> 				numOriginalRows += uint64(partialHistogram[i].NumRange + partialHistogram[i].NumEq)
> ```

I'm confused about `numOriginalRows`. We're adding row counts from both the partial histogram and the full histogram, but then down below we calculate `mergedRowCount` from the merged histogram, which I think will be the same thing?


<!-- Sent from Reviewable.io -->

2022-12-15 16:31 UTC, mgartner commented
*[`pkg/sql/stats/merge.go` line 131 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJH15nr4m-uosIypfLf:-NJLb3LK-800SEf50B6y:bfnha5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d5236f803e3cc7a546add55c98fa14d1f2e8e2/pkg/sql/stats/merge.go#L131)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I think we should add one more check before we merge the histograms: a check that a call to `constructUsingExtremesPredicate` on the first and last non-NULL bounds of `fullHistogram` creates a predicate exactly matching `partialStat.PartialPredicate`. This will avoid most cases of merging a USING EXTREMES partial stat with a different full stat than the one it was based on.
</blockquote></details>

If we do need to guarantee that the partial histogram was built with the extreme bounds of the full histogram, I don't think checking predicates or relying on `createdAt` is sufficient. The meaning of a predicate can change with schema changes (either a column referenced by name or by the whacky ordinal syntax `@1`). And the `createdAt` is not guaranteed to be correctly ordered given that stats are collected asynchoronously. For example, isn't this ordering possible:

```
t1: collect full_stat_1 with createdAt = t1
t2: queue partial_stat
t3: queue full_stat_2
t4: collect full_stat_2 with createAt = t4
t5: collect partial_stat with createdAt = t5
```

I think the only surefire way to guarantee the relationship is to store a reference to a full stat ID in the partial stat, and ensure those IDs match before merging.


<!-- Sent from Reviewable.io -->

2022-12-15 17:37 UTC, michae2 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/stats/merge.go` line 131 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJH15nr4m-uosIypfLf:-NJLq7dB3z4qhtoQI9lp:blc79dg) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d5236f803e3cc7a546add55c98fa14d1f2e8e2/pkg/sql/stats/merge.go#L131)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If we do need to guarantee that the partial histogram was built with the extreme bounds of the full histogram, I don't think checking predicates or relying on `createdAt` is sufficient. The meaning of a predicate can change with schema changes (either a column referenced by name or by the whacky ordinal syntax `@1`). And the `createdAt` is not guaranteed to be correctly ordered given that stats are collected asynchoronously. For example, isn't this ordering possible:

```
t1: collect full_stat_1 with createdAt = t1
t2: queue partial_stat
t3: queue full_stat_2
t4: collect full_stat_2 with createAt = t4
t5: collect partial_stat with createdAt = t5
```

I think the only surefire way to guarantee the relationship is to store a reference to a full stat ID in the partial stat, and ensure those IDs match before merging.
</blockquote></details>

Good points. I was hoping that checking the predicate would be simple, but as you pointed out in slack this `@` syntax turned out to have weird semantics. I like the idea of referencing a full stat ID, that seems very robust.


<!-- Sent from Reviewable.io -->

2022-12-16 16:10 UTC, faizaanmadhani reviewed
Hey @michae2 @mgartner! I've addressed the comments, and most notably added a check for StatisticID which validates that the partial stat we are merging was derived from the full statistic we are merging with. To do this, I updated the older migration have that in a different PR which I rebased this branch off of, so its changes are here and https://github.com/cockroachdb/cockroach/pull/93751 will need to be merged before we merge this, but that's why there are a lot of additional changes to this PR that were also in #93751 

I also made some changes to my unit tests. There was an issue with the way I recalculating the avgSize for the merged statistic that has now been fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJQg26S2QBuvUzT7fRt:bni3ge1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/stats/merge.go` line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIc3oD8-zIN6FQvOTTD:-NJI8j5SDZYtPtgNd0W9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19b9f49ff08f28679dfbd614ee190bcffaf450f7/pkg/sql/stats/merge.go#L70)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If we don't think we'll ever have buckets in partial and full with the same upper bounds, can we keep the = case but use it to return an error instead of handling it?
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 131 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJH15nr4m-uosIypfLf:-NJQfcVE1zHaa2M3ERmD:b-3ai2j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d5236f803e3cc7a546add55c98fa14d1f2e8e2/pkg/sql/stats/merge.go#L131)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Good points. I was hoping that checking the predicate would be simple, but as you pointed out in slack this `@` syntax turned out to have weird semantics. I like the idea of referencing a full stat ID, that seems very robust.
</blockquote></details>

So I added a fullStatisticsID column in this PR: https://github.com/cockroachdb/cockroach/pull/93751 and rebased off of it for this PR so the changes are shared between the two PRs and #93751 will need to be merged first.

I've also added this check here and updated the tests accordingly. 
___
*[`pkg/sql/stats/merge.go` line 155 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJGyVTY64-M816FaPpy:-NJHQn0s23iPmIZXRjYB:b-4ra55h) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d5236f803e3cc7a546add55c98fa14d1f2e8e2/pkg/sql/stats/merge.go#L155)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I'm a little nervous that this won't work for `TIME`, `TIMETZ`, `TIMESTAMP`, or `TIMESTAMPTZ` types which actually use this compare context in `CompareError`. But let me do some research, it might be ok. I remember it was ok for forecasting (which does work on `TIMESTAMP` and `TIMESTAMPTZ`).
</blockquote></details>

Sounds good. I've left this here for now if it's ok, but let me know if it should be changed. If the context needs to be set to something, what would we need to do?
___
*[`pkg/sql/stats/merge.go` line 166 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJH9wnCB7wTaJ8xXehd:-NJI8Zjp35gEZa68q8-t:bytgnww) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d5236f803e3cc7a546add55c98fa14d1f2e8e2/pkg/sql/stats/merge.go#L166)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I'm confused about `numOriginalRows`. We're adding row counts from both the partial histogram and the full histogram, but then down below we calculate `mergedRowCount` from the merged histogram, which I think will be the same thing?
</blockquote></details>

This was a leftover from the older merge code and was unnecessary. In fact, changing it helped me catch a few issues in my tests, which I've gone back and fixed because the average calculation wasn't happening correctly.


<!-- Sent from Reviewable.io -->

2022-12-19 20:07 UTC, mgartner requested changes
> Reviewed 1 of 2 files at r12, 4 of 27 files at r14, 26 of 28 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @faizaanmadhani and @michae2)

___
*[`pkg/sql/distsql_plan_stats.go` line 170 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfkEdeDFZD5uzyRfSQ:-NJfkEdf9hHbgvCWYKs5:bmv5m5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/distsql_plan_stats.go#L170)):*
> ```Go
> 		t.Name != jobspb.ForecastStatsName &&
> 		t.Name != jobspb.MergedStatsName &&
> 		(!colinfo.ColumnTypeIsInvertedIndexable(column.GetType()) || t.HistogramData == nil || t.HistogramData.ColumnType == nil || t.HistogramData.ColumnType.Family() != types.BytesFamily)
> ```

I don't understand the `... || t.HistogramData == nil || t.Histogram.ColumnType == nil || ...`. Doesn't the full stat need to have a histogram in order to create a partial stat from it?
___
*[`pkg/sql/stats/histogram.go` line 199 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJBGm_10aiuIsskFznb:-NJflUMHBN7rcpoW4jmm:bqokfla) ([raw file](https://github.com/cockroachdb/cockroach/blob/7532020aa78fd423b149c905488f329f1aeab1f6/pkg/sql/stats/histogram.go#L199)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

I moved the function above, but my only argument against naming it `EquiDepthExtremesHistogram` is that the returned histogram is not guaranteed to be equi-depth.
</blockquote></details>

Oh right. I agree, that would be a confusing name.
___
*[`pkg/sql/stats/merge.go` line 216 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NIt59xu94hDbFmgh9ls:-NJfnM3u3ekcnedMyjRM:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5077934e54ff16a2886474c4f2536a9a3b3313cb/pkg/sql/stats/merge.go#L216)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Just noting here that we don't have support for SHOW HISTOGRAM for forecasts yet either. This is because SHOW HISTOGRAM uses the on-disk representation of Histogram Data that it fetches from the system table. Since we don't store merged or forecasted histograms in the system table, we can't support it. 
</blockquote></details>

:+1: 
___
*[`pkg/sql/stats/merge.go` line 166 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfmp4q8MCw8kLUpZj4:-NJfmp4q8MCw8kLUpZj5:b-jaednn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/stats/merge.go#L166)):*
> ```Go
> 	j := 0
> 	// Merge partial stats to prior full statistics.
> 	for i < len(partialHistogram) && j < len(fullHistogram) {
> ```

I don't understand why we need to iterate over the full histogram here. Can we simplify this to just appending from the partial until we reach the lower bucket of the full histogram, and then keep the logic below this loop as-is (adding the full histogram buckets, then the rest of the partial histogram buckets)?
___
*[`pkg/sql/stats/merge.go` line 196 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfndcN-r5BKs0-Yqoi:-NJfndcN-r5BKs0-Yqoj:b68w2ga) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/stats/merge.go#L196)):*
> ```Go
> 	var mergedRowCount uint64
> 	var mergedDistinctCount uint64
> 	mergedNullCount := partialNullCount
> ```

We don't include the full stat's null count because the partial stats collection always scans over all nulls, is that correct? A comment here explaining that would be helpful.
___
*[`pkg/sql/stats/stats_cache.go` line 804 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfnydt4B6VDoP6PUwu:-NJfnydt4B6VDoP6PUwv:bd4bp9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/stats/stats_cache.go#L804)):*
> ```Go
> 	}
> 
> 	// TODO (faizaanmadhani): Wrap merging behind a boolean so
> ```

nit: the common format is no space after "TODO"
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 291 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfsfnlD-5bRj_1xah0:-NJfsfnlD-5bRj_1xah1:b-ncefuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L291)):*
> ```
> 
> query T
> EXPLAIN (OPT, VERBOSE) SELECT * FROM g WHERE b >= 10
> ```

nit: I think one variant of these explains is enough to prove that the merged stats are working as intended (probably the `OPT, VERBOSE` one since it shows the histogram), unless there's something specific you're trying to show with each that I'm missing.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 352 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJft3qE34ut7aaVNbPg:-NJft3qE34ut7aaVNbPh:b-u7sntn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L352)):*
> ```
>         {
>             "distinct_range": 0,
>             "num_eq": 0,
> ```

It's weird that forecasting turned this `num_eq` from 1 to 0... Any ideas why?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 415 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJftDtJ7CL3QwG9nBf-:-NJftDtJ7CL3QwG9nBf0:b-lguyga) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L415)):*
> ```
>     "name": "__forecast__",
>     "null_count": 0,
>     "row_count": 14
> ```

I only count `13` rows based on the histograms. Shouldn't this number match, or is that not guaranteed for forecasted stats? The distinct count above is also 14. cc @michae2 
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 745 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfu5V4232GNF_0gKf0:-NJfu5V4232GNF_0gKf1:b-ca524l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L745)):*
> ```
> 
> query T
> EXPLAIN (OPT, VERBOSE) SELECT * FROM i WHERE i = 6 OR i <= -1
> ```

ditto: I think one explain is enough.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 777 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfuwwi533nt85sff9e:-NJfuwwjE_iI2KpTF_tc:b5ootjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L777)):*
> ```
>        ],
>        "created_at":"2022-12-12 15:22:21.988179",
>        "distinct_count":25,
> ```

nit: This should be 26 to include NULL rows.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 814 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfuXIq65tYdZ4P_g63:-NJfuXIq65tYdZ4P_g64:b-4ny4xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L814)):*
> ```
>        "name":"full_b",
>        "null_count":3,
>        "row_count":25
> ```

nit: I think this should be 28 to include the NULL rows.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 822 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfv5k4A2WbFJANRLsB:-NJfv5k4A2WbFJANRLsC:b-vvew83) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L822)):*
> ```
>        ],
>        "created_at":"2022-12-13 15:22:21.988179",
>        "distinct_count":31,
> ```

nit: 32 to include NULL
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line  [...]

2022-12-19 20:24 UTC, mgartner commented
*[`pkg/sql/distsql_plan_stats.go` line 170 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfkEdeDFZD5uzyRfSQ:-NJg2QqP8qo6HozxGNhY:bp7ahj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/distsql_plan_stats.go#L170)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't understand the `... || t.HistogramData == nil || t.Histogram.ColumnType == nil || ...`. Doesn't the full stat need to have a histogram in order to create a partial stat from it?
</blockquote></details>

I see - we are guarding against NPEs. It's a bit confusing that this function returns `true` if the histogram is nil -we clearly need that to do partial stats collection. Is this more clear? cc @michae2 

```go
    return len(t.ColumnIDs) == 1 &&
        column.GetID() == t.ColumnIDs[0] &&
        t.PartialPredicate == "" &&
        t.Name != jobspb.ForecastStatsName &&
        t.Name != jobspb.MergedStatsName &&
        (!colinfo.ColumnTypeIsInvertedIndexable(column.GetType()) ||
            (t.HistogramData != nil && t.HistogramData.ColumnType != nil && t.HistogramData.ColumnType.Family() != types.BytesFamily))

```


<!-- Sent from Reviewable.io -->

2022-12-19 21:47 UTC, faizaanmadhani reviewed
I addressed all the comments and implemented all the changes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJgL_zm3zIUl4rWQwn9:b-8jf714)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/distsql_plan_stats.go` line 170 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfkEdeDFZD5uzyRfSQ:-NJgJyB62WX1BW2uqZm_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/distsql_plan_stats.go#L170)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I see - we are guarding against NPEs. It's a bit confusing that this function returns `true` if the histogram is nil -we clearly need that to do partial stats collection. Is this more clear? cc @michae2 

```go
    return len(t.ColumnIDs) == 1 &&
        column.GetID() == t.ColumnIDs[0] &&
        t.PartialPredicate == "" &&
        t.Name != jobspb.ForecastStatsName &&
        t.Name != jobspb.MergedStatsName &&
        (!colinfo.ColumnTypeIsInvertedIndexable(column.GetType()) ||
            (t.HistogramData != nil && t.HistogramData.ColumnType != nil && t.HistogramData.ColumnType.Family() != types.BytesFamily))

```
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 166 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfmp4q8MCw8kLUpZj4:-NJgK5uWDXQg_UwR1Iom:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/stats/merge.go#L166)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't understand why we need to iterate over the full histogram here. Can we simplify this to just appending from the partial until we reach the lower bucket of the full histogram, and then keep the logic below this loop as-is (adding the full histogram buckets, then the rest of the partial histogram buckets)?
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge.go` line 196 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfndcN-r5BKs0-Yqoi:-NJgK9977CHk91cfA_X4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/stats/merge.go#L196)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We don't include the full stat's null count because the partial stats collection always scans over all nulls, is that correct? A comment here explaining that would be helpful.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 352 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJft3qE34ut7aaVNbPg:-NJgKiiP2F7hnt4j3Mwl:b-vfuda2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L352)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's weird that forecasting turned this `num_eq` from 1 to 0... Any ideas why?
</blockquote></details>

I'm not sure... :thinking: 
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 415 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJftDtJ7CL3QwG9nBf-:-NJgKowR-wmLkYdMAjEl:b-3m95c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L415)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I only count `13` rows based on the histograms. Shouldn't this number match, or is that not guaranteed for forecasted stats? The distinct count above is also 14. cc @michae2 
</blockquote></details>

I would assume it wouldn't be guaranteed because it's forecasted, and the forecast might believe the table is growing in size, but I'm not too sure. 
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 745 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfu5V4232GNF_0gKf0:-NJgL-367-xq5BGZE6NM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L745)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

ditto: I think one explain is enough.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/merge_test.go` line 32 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJgLBsx8T7KVtqV4ndm:-NJgLBsx8T7KVtqV4ndn:b-p5rr6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b91997711bc23668d124a83afadbe1dae9e4abe3/pkg/sql/stats/merge_test.go#L32)):*
> ```Go
> 	}{
> 		{
> 			// Single partial at the extremes of full.
> ```

Adding a comment to this file to clarify these changes. Your (@marcus's) corrections above made me realize that I wasn't incrementing the discount count by 1 if the column has NULL values, so I fixed that and reworked these tests to account for that.
___
*[`pkg/sql/stats/bounds/extremes.go` line 52 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfoD-gDYgS5PahWEhO:-NJgKD4RBS6_VwRHFKLt:bp4rsxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/stats/bounds/extremes.go#L52)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why do you need `tree.FmtSymbolicSubqueries` here?
</blockquote></details>

That was a leftover from when we tried doing ordinals. I've changed it back to normal serializing.
___
*[`pkg/sql/stats/bounds/extremes.go` line 72 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfpV6y0VtUp27AANiL:-NJgKTX37-95d5pzXukT:bwwd8t5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/stats/bounds/extremes.go#L72)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

AFAIK There is no requirement that `constraint.Spans` are in any particular order. Did you run into problems adding DESC spans in the same order as ASC spans?
</blockquote></details>

Yes, I did. Added a comment clarify why we need to generate the constraints differently.


<!-- Sent from Reviewable.io -->

2022-12-19 22:52 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 6 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJg_WR_9D0t16tjboN9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @faizaanmadhani and @michae2)

___
*[`pkg/sql/stats/merge.go` line 166 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJgXGgV-ba4Nx9x-3eT:-NJgXGgV-ba4Nx9x-3eU:b-1tal7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6619697d54eda84a624bf191e3e8e6a653e6079b/pkg/sql/stats/merge.go#L166)):*
> ```Go
> 	// Merge partial stats to prior full statistics.
> 	for i < len(partialHistogram) {
> 		if val, err := partialHistogram[i].UpperBound.CompareError(cmpCtx, fullHistogram[0].UpperBound); err == nil {
> ```

nit: `val, err := ....` then `if err != nil { .. } ` to handle the err case first.
___
*[`pkg/sql/stats/merge.go` line 181 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJgXUnXACVnne-tOm3z:-NJgXUnXACVnne-tOm4-:b-kq4c1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/6619697d54eda84a624bf191e3e8e6a653e6079b/pkg/sql/stats/merge.go#L181)):*
> ```Go
> 
> 	// Iterate through the rest of the full histogram and append it.
> 	for j := 0; j < len(fullHistogram); j++ {
> ```

nit: `for j := range fullHistogram { .. }` 
___
*[`pkg/sql/stats/merge.go` line 195 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJgYIkX1Ul30ah86d9n:-NJgYIkX1Ul30ah86d9o:b-os3ano) ([raw file](https://github.com/cockroachdb/cockroach/blob/6619697d54eda84a624bf191e3e8e6a653e6079b/pkg/sql/stats/merge.go#L195)):*
> ```Go
> 	// Since partial statistics at the extremes will always scan over
> 	// the NULL rows at the lowerbound, we don't include the NULL count
> 	// of the full statistic.
> ```

No need to do anything now, but I'm worried about partial stats scanning all rows where a column is NULL. It's not hard to imagine cases where 50+% of rows have NULL for a column (e.g. a `deleted_at TIMESTAMPTZ` column on a table where most things are not deleted). That would be a _really_ expensive partial stats collection, relative to most other cases. I think we should consider scanning `(\NULL - \lowerbound)` instead of `[\NULL - \lowerbound)` if `null_count` is already non-zero.


<!-- Sent from Reviewable.io -->

2022-12-19 23:50 UTC, faizaanmadhani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/stats/merge.go` line 195 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJgYIkX1Ul30ah86d9n:-NJgmgWBE_yKDNTp14Oj:b-p4aer7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6619697d54eda84a624bf191e3e8e6a653e6079b/pkg/sql/stats/merge.go#L195)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

No need to do anything now, but I'm worried about partial stats scanning all rows where a column is NULL. It's not hard to imagine cases where 50+% of rows have NULL for a column (e.g. a `deleted_at TIMESTAMPTZ` column on a table where most things are not deleted). That would be a _really_ expensive partial stats collection, relative to most other cases. I think we should consider scanning `(\NULL - \lowerbound)` instead of `[\NULL - \lowerbound)` if `null_count` is already non-zero.
</blockquote></details>

Sounds good. I will open an issue for this and link it here when I merge this PR.


<!-- Sent from Reviewable.io -->

2022-12-20 00:59 UTC, michae2 approved these changes
I'm going to read through testcases after dinner, but this <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

Nice work, @faizaanmadhani!! You put a ton of effort into this!!

> Reviewed 2 of 27 files at r14, 18 of 28 files at r15, 1 of 2 files at r16, 3 of 6 files at r17, 1 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJh1Tdl2dj2fZty6fC0:b-tqqtgt)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/distsql_plan_stats.go` line 170 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfkEdeDFZD5uzyRfSQ:-NJgbGPf63aBB8zFChwv:b-ia9car) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/distsql_plan_stats.go#L170)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Comment for @mgartner: This logic isn't quite the same. Now in some cases where before we would have returned a "prior histogram has no buckets" error from `createPartialStatsPlan` we are instead creating partial stats based on a stale full statistic. Here's one such case:

```sql
SET CLUSTER SETTING sql.stats.automatic_collection.fraction_stale_rows = 0.001;
SET CLUSTER SETTING sql.stats.automatic_collection.min_stale_rows = 5;

CREATE TABLE r (s STRING PRIMARY KEY);

INSERT INTO r VALUES ('a'), ('b'), ('c'), ('d'), ('e');

-- wait a while for full auto stats

SET CLUSTER SETTING sql.stats.histogram_collection.enabled = false;

DELETE FROM r WHERE true;
INSERT INTO r VALUES ('v'), ('w'), ('x'), ('y'), ('z');

-- wait a while for full auto stats

SELECT jsonb_pretty(statistics) FROM [SHOW STATISTICS USING JSON FOR TABLE r];
```

This produces statistics like the following:

```
  [
      {
          "avg_size": 0,
          "columns": [
              "s"
          ],
          "created_at": "2022-12-19 23:28:55.124743",
          "distinct_count": 0,
          "histo_col_type": "STRING",
          "histo_version": 2,
          "name": "__auto__",
          "null_count": 0,
          "row_count": 0
      },
      {
          "avg_size": 4,
          "columns": [
              "s"
          ],
          "created_at": "2022-12-19 23:29:55.156286",
          "distinct_count": 5,
          "histo_buckets": [
              {
                  "distinct_range": 0,
                  "num_eq": 1,
                  "num_range": 0,
                  "upper_bound": "a"
              },
              {
                  "distinct_range": 0,
                  "num_eq": 1,
                  "num_range": 0,
                  "upper_bound": "b"
              },
              {
                  "distinct_range": 0,
                  "num_eq": 1,
                  "num_range": 0,
                  "upper_bound": "c"
              },
              {
                  "distinct_range": 0,
                  "num_eq": 1,
                  "num_range": 0,
                  "upper_bound": "d"
              },
              {
                  "distinct_range": 0,
                  "num_eq": 1,
                  "num_range": 0,
                  "upper_bound": "e"
              }
          ],
          "histo_col_type": "STRING",
          "histo_version": 2,
          "name": "__auto__",
          "null_count": 0,
          "row_count": 5
      },
      {
          "avg_size": 4,
          "columns": [
              "s"
          ],
          "created_at": "2022-12-19 23:32:55.222092",
          "distinct_count": 5,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 5
      }
  ]
```

Before, `isFullStatValidToCreatePartial` would have returned true for the latest 23:32 stat (which has `t.HistogramData == nil`) and then `createPartialStatsPlan` would have returned an error because the histogram is empty. Now, `createPartialStatsPlan` is building a partial stat based on the stale 23:29 stat. I'm not sure this is better.

In other words, stats with nil HistogramData (and all other conditions true) are "valid" meaning we should not continue searching past them, but then we should return an error because histograms were turned off and have length 0. Does that make sense? WDYT?
___
*[`pkg/sql/stats/merge.go` line 131 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJH15nr4m-uosIypfLf:-NJgr0l91nOZKl2wxfKG:b-j764li) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d5236f803e3cc7a546add55c98fa14d1f2e8e2/pkg/sql/stats/merge.go#L131)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

So I added a fullStatisticsID column in this PR: https://github.com/cockroachdb/cockroach/pull/93751 and rebased off of it for this PR so the changes are shared between the two PRs and #9371 will need to be merged first.

I've also added this check here and updated the tests accordingly. 
</blockquote></details>

Thank you for doing this!!
___
*[`pkg/sql/stats/merge.go` line 155 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJGyVTY64-M816FaPpy:-NJgt9L23LsRGficK7Zt:bshjvhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/94d5236f803e3cc7a546add55c98fa14d1f2e8e2/pkg/sql/stats/merge.go#L155)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Sounds good. I've left this here for now if it's ok, but let me know if it should be changed. If the context needs to be set to something, what would we need to do?
</blockquote></details>

It looks like all time comparisons will be done using UTC, which should be fine for merging, so this is good.
___
*[`pkg/sql/stats/merge.go` line 81 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJgwo-54pUxaHF-n4_w:-NJgwo-54pUxaHF-n4_x:b-ovs7mh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6619697d54eda84a624bf191e3e8e6a653e6079b/pkg/sql/stats/merge.go#L81)):*
> ```Go
> //
> // For example, consider this case:
> // Full Statistic: {row: 3, dist: 4, null: 4, size: 1}
> ```

micro-nit: I think this example should have `row: 7` (including nulls) and the merge should have `row: 15`
___
*[`pkg/sql/stats/merge.go` line 182 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJgtpEP5NXLabHaVry7:-NJgtpEQ9uaAEQu76D6P:b-j61i5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/6619697d54eda84a624bf191e3e8e6a653e6079b/pkg/sql/stats/merge.go#L182)):*
> ```Go
> 	// Iterate through the rest of the full histogram and append it.
> 	for j := 0; j < len(fullHistogram); j++ {
> 		mergedHistogram = append(mergedHistogram, fullHistogram[j])
> ```

It would be nice to have a defensive `break` in this loop if `i < len(partialHistogram) && partialHistogram[i].UpperBound.CompareError(cmpCtx, fullHistogram[j].UpperBound)` is ever <= 0 before we reach the end of the full histogram. (Or maybe instead of a break, return an error?)


<!-- Sent from Reviewable.io -->

2022-12-20 04:04 UTC, faizaanmadhani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/distsql_plan_stats.go` line 170 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfkEdeDFZD5uzyRfSQ:-NJhgiQSCRVeUNTfYrs8:b-ze1sa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/distsql_plan_stats.go#L170)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Comment for @mgartner: This logic isn't quite the same. Now in some cases where before we would have returned a "prior histogram has no buckets" error from `createPartialStatsPlan` we are instead creating partial stats based on a stale full statistic. Here's one such case:

```sql
SET CLUSTER SETTING sql.stats.automatic_collection.fraction_stale_rows = 0.001;
SET CLUSTER SETTING sql.stats.automatic_collection.min_stale_rows = 5;

CREATE TABLE r (s STRING PRIMARY KEY);

INSERT INTO r VALUES ('a'), ('b'), ('c'), ('d'), ('e');

-- wait a while for full auto stats

SET CLUSTER SETTING sql.stats.histogram_collection.enabled = false;

DELETE FROM r WHERE true;
INSERT INTO r VALUES ('v'), ('w'), ('x'), ('y'), ('z');

-- wait a while for full auto stats

SELECT jsonb_pretty(statistics) FROM [SHOW STATISTICS USING JSON FOR TABLE r];
```

This produces statistics like the following:

```
  [
      {
          "avg_size": 0,
          "columns": [
              "s"
          ],
          "created_at": "2022-12-19 23:28:55.124743",
          "distinct_count": 0,
          "histo_col_type": "STRING",
          "histo_version": 2,
          "name": "__auto__",
          "null_count": 0,
          "row_count": 0
      },
      {
          "avg_size": 4,
          "columns": [
              "s"
          ],
          "created_at": "2022-12-19 23:29:55.156286",
          "distinct_count": 5,
          "histo_buckets": [
              {
                  "distinct_range": 0,
                  "num_eq": 1,
                  "num_range": 0,
                  "upper_bound": "a"
              },
              {
                  "distinct_range": 0,
                  "num_eq": 1,
                  "num_range": 0,
                  "upper_bound": "b"
              },
              {
                  "distinct_range": 0,
                  "num_eq": 1,
                  "num_range": 0,
                  "upper_bound": "c"
              },
              {
                  "distinct_range": 0,
                  "num_eq": 1,
                  "num_range": 0,
                  "upper_bound": "d"
              },
              {
                  "distinct_range": 0,
                  "num_eq": 1,
                  "num_range": 0,
                  "upper_bound": "e"
              }
          ],
          "histo_col_type": "STRING",
          "histo_version": 2,
          "name": "__auto__",
          "null_count": 0,
          "row_count": 5
      },
      {
          "avg_size": 4,
          "columns": [
              "s"
          ],
          "created_at": "2022-12-19 23:32:55.222092",
          "distinct_count": 5,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 5
      }
  ]
```

Before, `isFullStatValidToCreatePartial` would have returned true for the latest 23:32 stat (which has `t.HistogramData == nil`) and then `createPartialStatsPlan` would have returned an error because the histogram is empty. Now, `createPartialStatsPlan` is building a partial stat based on the stale 23:29 stat. I'm not sure this is better.

In other words, stats with nil HistogramData (and all other conditions true) are "valid" meaning we should not continue searching past them, but then we should return an error because histograms were turned off and have length 0. Does that make sense? WDYT?
</blockquote></details>

Considering this example, I'm leaning on changing this logic back to what it was previously, but I'm going to hold off on changing this and merging after getting @mgartner's input. 


<!-- Sent from Reviewable.io -->

2022-12-20 06:35 UTC, michae2 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @faizaanmadhani, @mgartner, and @rytaft)

___
*[`pkg/sql/stats/merge.go` line 219 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJi6P5S5VT1dbS7gBGF:-NJi6P5S5VT1dbS7gBGG:bpozo9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/stats/merge.go#L219)):*
> ```Go
> 	}
> 
> 	mergedAvgSize := (partialStat.AvgSize*partialStat.RowCount + fullStat.AvgSize*fullStat.RowCount) / mergedRowCount
> ```

Could `mergedRowCount` be zero?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 352 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJft3qE34ut7aaVNbPg:-NJi-GfDBWEPKeQ9RlSM:b-pxalfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L352)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

I'm not sure... :thinking: 
</blockquote></details>

Probably because of the missing 9 in the merged stat + the forecast distance being half a day instead of a full day (or two).
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 415 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJftDtJ7CL3QwG9nBf-:-NJi0bL80DO5tvC3K9Iv:bgbe8ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L415)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

I would assume it wouldn't be guaranteed because it's forecasted, and the forecast might believe the table is growing in size, but I'm not too sure. 
</blockquote></details>

It's probably because the partial stat has the wrong number for row_count and distinct_count (6 instead of 3).
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 13 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJi269S8dmVoR6-YrfW:-NJi269S8dmVoR6-YrfX:broxw0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L13)):*
> ```
> 
> statement ok
> CREATE TABLE g (b INT PRIMARY KEY) WITH (sql_stats_automatic_collection_enabled = false);
> ```

micro-nit: Statements in our logic tests don't need the terminating semicolon.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 126 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJhyXop04_UOiLpMMGp:-NJhyXop04_UOiLpMMGq:bs49enc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L126)):*
> ```
>       ],
>       "created_at": "1988-08-08 00:00:00.000000",
>       "distinct_count": 6,
> ```

This should be 3.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 132 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJi-8wW5K51IhW9iLIL:-NJi-8wW5K51IhW9iLIM:b1lbt4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L132)):*
> ```
>           "num_eq": 1,
>           "num_range": 0,
>           "upper_bound": "10"
> ```

We'll get less confusing forecasts if this partial stat is {9, 10, 11} rather than {10, 11, 12}.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 152 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJhyaNC-WxE_ywWLHMB:-NJhyaNC-WxE_ywWLHMC:b-jrdaru) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L152)):*
> ```
>       "null_count": 0,
>       "partial_predicate": "(b < 0:::INT8) OR ((b > 8:::INT8) OR (b IS NULL))",
>       "row_count": 6
> ```

3 here too
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 163 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJhv2Xj8yVU5QwMmuuO:-NJhv2Xj8yVU5QwMmuuP:b-7qq13b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L163)):*
> ```
> # statistic id is generated when a statistic is added to
> # system.table_statistics, and since we don't store it in the JSON statistic
> # object, we need to set it manually here.
> ```

Oh, hmm. I think we need to file an issue about this. I did not consider that `ALTER TABLE INJECT STATISTICS` would not work for this new `fullStatisticID` column. This could be a problem. :thinking: (No need to change this PR.)
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 304 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJi-UcS1QwxcnB6OACH:-NJi-UcS1QwxcnB6OACI:bg7fsjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L304)):*
> ```
> partial       {b}  1988-08-08 00:00:00 +0000 +0000  6   6   0  2
> __merged__    {b}  1988-08-08 00:00:00 +0000 +0000  12  12  0  1
> __forecast__  {b}  1988-08-08 12:00:00 +0000 +0000  14  14  0  1
> ```

Beautiful to see it all working together! :smiling_face_with_tear:

We're forecasting 12 hours into the future because none of these are named `__auto__`. That's going to give a confusing result because we're growing 3 rows per day, so 12 hours = 1.5 rows. The forecast will still work correctly, but won't be as easy to obviously prove correct at a glance.

If we rename full_0 and full_1 to `__auto__` then we should get a forecast 48 hours into the future, which should give a less confusing forecast.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 606 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJiBA1HBcrvuxP_jT9r:-NJiBA1HBcrvuxP_jT9s:b-bn54jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L606)):*
> ```
>         "num_eq": 1,
>         "num_range": 0,
>         "upper_bound": "4"
> ```

Might be less confusing with {3, 4, 5} instead of {4, 5, 6}?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 761 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJiCHSkB5fjE8Vnbe9u:-NJiCHSkB5fjE8Vnbe9v:brarrw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L761)):*
> ```
>              "distinct_range":4,
>              "num_eq":1,
>              "num_range":4,
> ```

First bucket always needs to have num_range and distinct_range of zero.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 824 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJiCrPYCq9FdD1EOGG_:-NJiCrPYCq9FdD1EOGGa:b-rwrbz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L824)):*
> ```
>              "distinct_range":4,
>              "num_eq":1,
>              "num_range":4,
> ```

Won't `ConstructExtremesHistogram` always make upperHist with a first bucket with num_range and distinct_range of zero?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 864 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJiDjfy3VdkGBGvhhDJ:-NJiDjfzEeH2hmogFzC2:b-wyd6hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L864)):*
> ```
>              "distinct_range":4,
>              "num_eq":1,
>              "num_range":4,
> ```

same comment here about num_range and distinct_ra [...]

2022-12-20 14:05 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @faizaanmadhani, @michae2, and @rytaft)

___
*[`pkg/sql/distsql_plan_stats.go` line 170 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfkEdeDFZD5uzyRfSQ:-NJjml2F1KrhXiC_aH1-:b-xag12s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/distsql_plan_stats.go#L170)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Considering this example, I'm leaning on changing this logic back to what it was previously, but I'm going to hold off on changing this and merging after getting @mgartner's input. 
</blockquote></details>

Thanks for the example, Michael. I would expect partial stats to not occur at all if `sql.stats.histogram_collection.enabled = false` (@faizaanmadhani let's make an issue to track that). But I believe a slight modification to your example of setting `SET CLUSTER SETTING sql.stats.histogram_collection.enabled = true` after the non-histogram full collection would lead to the same problem.

I suggest we make this logic more closely match how you've described things should work. It sounds like the logic is:

1. Is this the most recent full stat for this column? If not, continue.
2. Does the full stat have a histogram? If not, return an error.
3. Is the histogram's type invertable or a byes type? If so, return an error.

Making these steps distinct may make the code more clear. Or, if you feel strongly that it should remain as-is, then I'd suggest at least renaming `isFullStatValidToCreatePartial` because it's suprising that a full stat without a histogram can be "valid" to create a partial.

I'm also curious when we'd return an error from (3) without being able to error before the loop by checking the column's type. Is that specifically for trigram indexes?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 163 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJhv2Xj8yVU5QwMmuuO:-NJjqNlQ89yW5DxbWTtM:boettei) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L163)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Oh, hmm. I think we need to file an issue about this. I did not consider that `ALTER TABLE INJECT STATISTICS` would not work for this new `fullStatisticID` column. This could be a problem. :thinking: (No need to change this PR.)
</blockquote></details>

Why do you think this could be a problem? I think this is fine - these are just test fixtures that we need to setup to mimic a real collection of them.


<!-- Sent from Reviewable.io -->

2022-12-20 14:52 UTC, faizaanmadhani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/stats/merge.go` line 219 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJi6P5S5VT1dbS7gBGF:-NJjwFXE45qYxDOIM3Z1:b52t5e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/stats/merge.go#L219)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Could `mergedRowCount` be zero?
</blockquote></details>

No, it shouldn't be. The only time that could happen would be if there is no partial and no full statistic histograms, in which case we already have an error above.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 352 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJft3qE34ut7aaVNbPg:-NJjx2n_5dqgSznS4UuG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L352)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Probably because of the missing 9 in the merged stat + the forecast distance being half a day instead of a full day (or two).
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 415 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJftDtJ7CL3QwG9nBf-:-NJjx5Qj2stJtMK1UzK4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L415)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

It's probably because the partial stat has the wrong number for row_count and distinct_count (6 instead of 3).
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 304 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJi-UcS1QwxcnB6OACH:-NJk-zVc7SEiqmNdzj9X:b-bqsfiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L304)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Beautiful to see it all working together! :smiling_face_with_tear:

We're forecasting 12 hours into the future because none of these are named `__auto__`. That's going to give a confusing result because we're growing 3 rows per day, so 12 hours = 1.5 rows. The forecast will still work correctly, but won't be as easy to obviously prove correct at a glance.

If we rename full_0 and full_1 to `__auto__` then we should get a forecast 48 hours into the future, which should give a less confusing forecast.
</blockquote></details>

Ok, renamed to __auto__
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 824 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJiCrPYCq9FdD1EOGG_:-NJjxaNY8LW11ezTFQNF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L824)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Won't `ConstructExtremesHistogram` always make upperHist with a first bucket with num_range and distinct_range of zero?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/partial_stats` line 864 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJiDjfy3VdkGBGvhhDJ:-NJjyHV2DR5pmyuYY5pH:b-dn35q7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e427d0773d6955d59d2d4e29650d1c6f159156d/pkg/sql/opt/exec/execbuilder/testdata/partial_stats#L864)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

same comment here about num_range and distinct_range
</blockquote></details>

Done -- this histogram was constructed by hand from a larger histogram as histograms this small wouldn't have num_range, distinct_range > 0. I've added those buckets back in.


<!-- Sent from Reviewable.io -->

2022-12-20 16:30 UTC, faizaanmadhani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/distsql_plan_stats.go` line 170 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfkEdeDFZD5uzyRfSQ:-NJkM8Ft44z0mP2PE14C:b-b59dbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/distsql_plan_stats.go#L170)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Thanks for the example, Michael. I would expect partial stats to not occur at all if `sql.stats.histogram_collection.enabled = false` (@faizaanmadhani let's make an issue to track that). But I believe a slight modification to your example of setting `SET CLUSTER SETTING sql.stats.histogram_collection.enabled = true` after the non-histogram full collection would lead to the same problem.

I suggest we make this logic more closely match how you've described things should work. It sounds like the logic is:

1. Is this the most recent full stat for this column? If not, continue.
2. Does the full stat have a histogram? If not, return an error.
3. Is the histogram's type invertable or a byes type? If so, return an error.

Making these steps distinct may make the code more clear. Or, if you feel strongly that it should remain as-is, then I'd suggest at least renaming `isFullStatValidToCreatePartial` because it's suprising that a full stat without a histogram can be "valid" to create a partial.

I'm also curious when we'd return an error from (3) without being able to error before the loop by checking the column's type. Is that specifically for trigram indexes?
</blockquote></details>

Ok, I removed the function and moved this logic below. I also modified it so it's easier to read and a bit clearer.


<!-- Sent from Reviewable.io -->

2022-12-20 20:01 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Can you make an issue to make sure that statement bundles include the latest full stats and partial stats?

> Reviewed 1 of 2 files at r18, 1 of 1 files at r20, 1 of 1 files at r21, 1 of 2 files at r22, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJkolnG29uIqK-IXiBZ:b4swq5n)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @faizaanmadhani and @michae2)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 2205 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJl6hisCKTTur2e34zh:-NJl6hisCKTTur2e34zi:bf1rd5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f74a315dd4d3bb979f5b5c1953a89955e5fce53/pkg/sql/logictest/testdata/logic_test/distsql_stats#L2205)):*
> ```
> 
> # Verify that a non-inverted index string column with a string histogram
> # can have partial statistics
> ```

Do you want to add a test for inverted indexes as well, similar to the error cases above?


<!-- Sent from Reviewable.io -->

2022-12-20 20:21 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice work, Faizaan!

> Reviewed 1 of 1 files at r24.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJlBc3Y9f6qBDjsRj4m:b-xoxbxk)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @faizaanmadhani and @mgartner)

___
*[`pkg/sql/distsql_plan_stats.go` line 170 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-NJfkEdeDFZD5uzyRfSQ:-NJlAo1o7pV-4hSonJ7n:bkucxzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1272956724332bc8c6bb251a788ffeb02fda4b41/pkg/sql/distsql_plan_stats.go#L170)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

Ok, I removed the function and moved this logic below. I also modified it so it's easier to read and a bit clearer.
</blockquote></details>

Really clear. Perfect. Thank you!


<!-- Sent from Reviewable.io -->

2022-12-20 22:24 UTC, faizaanmadhani commented
TFTR! 🎉 
bors r=michae2

2022-12-20 22:30 UTC, faizaanmadhani commented
bors r-

2022-12-21 16:47 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r25, 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91933#-:-NJp_G-dA5-OdatHeBxN:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @faizaanmadhani and @michae2)



<!-- Sent from Reviewable.io -->

2022-12-21 16:57 UTC, faizaanmadhani commented
TFTRs! :fire: 

bors r=michae2, rytaft, mgartner

2022-12-21 19:05 UTC, erikgrinaker commented
Cancelling since it doesn't pass bors, it needs a `dev gen bazel` 

bors r-

```diff
diff --git a/pkg/sql/stats/BUILD.bazel b/pkg/sql/stats/BUILD.bazel
index b945a28d23..548af1a8a6 100644
--- a/pkg/sql/stats/BUILD.bazel
+++ b/pkg/sql/stats/BUILD.bazel
@@ -47,6 +47,7 @@ go_library(
         "//pkg/sql/sqlerrors",
         "//pkg/sql/sqlutil",
         "//pkg/sql/types",
+        "//pkg/util",
         "//pkg/util/cache",
         "//pkg/util/encoding",
         "//pkg/util/hlc",
```

2022-12-21 20:44 UTC, faizaanmadhani commented
bors r=michae2,mgartner,rytaft

2022-12-21 21:56 UTC, merged