opt: add rule to replace outer cols with equivalent non-outer cols
cockroachdb/cockroach pull request #92378
Opened 2022-11-23 08:28 UTC by DrewKimball

This commit adds three decorrelation rules, `TryRemapJoinOuterColsRight`, `TryRemapJoinOuterColsLeft`, and `TryRemapSelectOuterCols`. These rules match joins and selects that have a correlated input and an equality filter between an outer and a non-outer column from the input. Upon matching, the rules traverse the input as far as it would be valid to push the equality filter through normal push-down rules, and replace any encountered references to the equivalent outer column. This approach avoids interactions with rules like `TryDecorrelateSelect`, which attempt to pull filters *up* the operator tree when correlation is present.

Fixes #88885

Release note: None

2022-11-23 08:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/92378)
<!-- Reviewable:end -->

2022-11-23 18:21 UTC, DrewKimball commented
Hold off on reviewing - I've got some test changes to investigate.

2022-11-30 21:13 UTC, DrewKimball commented
This is RFAL. The plan for TPCH Q2 changed and is slower; this seems to be because decorrelation rules no longer pull the groupby above the apply-join. Stats end up being further off in some additional cases, and the optimizer chooses a (buffering) sort + limit instead of a top-k operator because it believes the sort only receives one row as input. I think this is likely because the groupby makes stats estimation more difficult for the operators above it.

2022-12-02 19:12 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @msirek)

___
*[`pkg/bench/rttanalysis/orm_queries_bench_test.go` line 319 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIJFAxs5eXAkXWXddbg:-NIJFAxs5eXAkXWXddbh:b-i52q2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/257f862e1674aa0135f9aec4acc73c14a9f2906b/pkg/bench/rttanalysis/orm_queries_bench_test.go#L319)):*
> ```Go
> 
> 		{
> 			Name: "hasura column descriptions 8 tables",
> ```

in https://github.com/cockroachdb/cockroach/pull/92929 the preceding test case was also skipped, so could you unskip it when this PR is good to go?


<!-- Sent from Reviewable.io -->

2022-12-02 23:36 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rafiss)

___
*[`pkg/bench/rttanalysis/orm_queries_bench_test.go` line 319 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIJFAxs5eXAkXWXddbg:-NIKBb8467ooRzwlzX8z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/257f862e1674aa0135f9aec4acc73c14a9f2906b/pkg/bench/rttanalysis/orm_queries_bench_test.go#L319)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in https://github.com/cockroachdb/cockroach/pull/92929 the preceding test case was also skipped, so could you unskip it when this PR is good to go?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-05 16:26 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @msirek, and @rafiss)

___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1072 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY45OT5AVJh8rKuPnk:-NIY45OT5AVJh8rKuPnl:bpa1am1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1072)):*
> ```Go
> // valid to push down a filter on those non-outer columns. If a reference to the
> // outer column is discovered during this traversal, it is valid to replace it
> // with one of the non-outer columns in the set.
> ```

Is there a reason that we can't do a single traversal and replace any of the outer columns we find?
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1096 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY5Iuf02DLED4z18IP:-NIY5Iug1DniGUwsQDZ2:b-rxlt8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1096)):*
> ```Go
> 					// This outer-column reference can be remapped.
> 					succeeded = true
> 					return c.f.ConstructVariable(replaceCol)
> ```

Do we need any logic to prevent making a substitution that actually drops a filter? For example, how do we prevent replacing the expression `non_outer_col = outer_col` with `non_outer_col = non_outer_col`?


<!-- Sent from Reviewable.io -->

2022-12-05 23:24 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rafiss)

___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1072 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY45OT5AVJh8rKuPnk:-NIZaZeOBv80HsHOuN9L:b-5dbii8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1072)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is there a reason that we can't do a single traversal and replace any of the outer columns we find?
</blockquote></details>

Hm, that might be possible with an `EquivSet`. I'll check it out.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1096 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY5Iuf02DLED4z18IP:-NIZa1wo6A-w0jey3ieA:bq9gmcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1096)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do we need any logic to prevent making a substitution that actually drops a filter? For example, how do we prevent replacing the expression `non_outer_col = outer_col` with `non_outer_col = non_outer_col`?
</blockquote></details>

Do you mean a case where there are two `non_outer_col = outer_col` filters to start with, one above the other in the tree?


<!-- Sent from Reviewable.io -->

2022-12-06 01:13 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rafiss)

___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1072 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY45OT5AVJh8rKuPnk:-NIZydQDCri36MA9I6LG:beco1uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1072)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Hm, that might be possible with an `EquivSet`. I'll check it out.
</blockquote></details>

Update: it should be possible, but would introduce some complexity, since we can no longer restrict the set of columns we're considering to just non-outer columns - we would also need to keep track of which outer columns are equal to which non-outer columns, but only those outer columns that were "outer" in the original matched expression. Additionally, it would require more allocations since `ColSet` copies would become slice copies. 
So my feeling is that if the query is complex enough to make the number of traversals significant, doing a single traversal would cause the number of allocations to be significant. Do you have any strong opinions about this?


<!-- Sent from Reviewable.io -->

2022-12-15 02:29 UTC, msirek approved these changes
This is great! I tried to find problem cases involving composite sensitive columns of different data types, but these seem to not be comparable with each other in an IN or NOT IN subquery clause, so that seems to prevent the introduction of column comparisons of data types which didn't exist in the un-rewritten query, for example, `float` with `int`, which didn't exist before. For example:
```
create table t5 (a float, b dec);
create table t6 (a float, b float);
select * from t6 where (b) in (select a from t5 where t5.b = t6.b);
```
This derives a t5.a = t5.b term, but since t6.b and t5.a are equivalent, and of the same data type (in the IN clause), we're not introducing a new term comparing different data types.

Honestly, it's a little difficult to tell if any problem cases are possible just from examining the code. I wonder if it would make sense to put in a sanity check that the type family of the column we're mapping to matches that of the "from" column.

For the TPCH Q2 regression, maybe it would be good to open an issue for that.  These new decorrelation rules should have a very positive impact on other queries so a regression here or there seems acceptable and may highlight other issues which need addressing (like stats accuracy of groupby, as you mentioned).  One alternative solution could be to derive new terms instead of just mapping them, and link them. When one term in the pair is applied, mark the other as not requiring evaluation. This could help prevent some beneficial rewrite rules from no longer being able to fire after these rewrites. But maybe such an approach is too complex and could lead to more stats inaccuracies due to redundant terms. Just throwing it out there to ponder.

You may wish to get at least one more approval due to the complexity of this PR, but it looks good to me.

> Reviewed 3 of 3 files at r1, 7 of 7 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-:-NJISlQE4_yqthtJEElC:b-nkc2x4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rafiss)

___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1096 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY5Iuf02DLED4z18IP:-NJHVVjXBKKEppiOy4IW:b-kgiub1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1096)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Do you mean a case where there are two `non_outer_col = outer_col` filters to start with, one above the other in the tree?
</blockquote></details>

Maybe the question being asked here is, could we ever drop a filter which is still needed?  It seems that if the `non_outer_col` is already in the same equivalence set with `outer_col` due to IN or NOT IN subquery connecting conditions, it is OK to generate a `non_outer_col = non_outer_col` filter because the filtering would be done by the IN or NOT IN.  This mapped term gets normalized into something like `non_outer_col IS DISTINCT FROM CAST(NULL AS INT8)`.
e.g.
```
explain select * from t1 where a in (select a from t3 where t3.a = t1.a);
                                          info
----------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • hash join (semi)
  │ estimated row count: 1
  │ equality: (a) = (a)
  │
  ├── • filter
  │   │ estimated row count: 1
  │   │ filter: a IS DISTINCT FROM CAST(NULL AS INT8)
  │   │
  │   └── • scan
  │         estimated row count: 1 (100% of the table; stats collected 51 minutes ago)
  │         table: t1@t1_pkey
  │         spans: FULL SCAN
  │
  └── • filter
      │ estimated row count: 1
      │ filter: a IS DISTINCT FROM CAST(NULL AS INT8)
      │
      └── • scan
            estimated row count: 1 (100% of the table; stats collected 34 minutes ago)
            table: t3@t3_pkey
            spans: FULL SCAN
```


<!-- Sent from Reviewable.io -->

2023-01-10 19:24 UTC, rafiss reviewed
just wondering if this PR is still planned for 23.1?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-:-NLS7ps060VW3tziw08G:b-5qjppr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)



<!-- Sent from Reviewable.io -->

2023-01-25 03:27 UTC, DrewKimball commented
>just wondering if this PR is still planned for 23.1?

Still planned, I just got distracted by other things for a bit.

2023-01-25 03:47 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rafiss)

___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1072 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY45OT5AVJh8rKuPnk:-NMaz85j8FBIxTimNTtn:b-h498gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1072)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Update: it should be possible, but would introduce some complexity, since we can no longer restrict the set of columns we're considering to just non-outer columns - we would also need to keep track of which outer columns are equal to which non-outer columns, but only those outer columns that were "outer" in the original matched expression. Additionally, it would require more allocations since `ColSet` copies would become slice copies. 
So my feeling is that if the query is complex enough to make the number of traversals significant, doing a single traversal would cause the number of allocations to be significant. Do you have any strong opinions about this?
</blockquote></details>

@mgartner friendly ping on this point - TL;DR is that we could do it in one pass with more allocations.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1096 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY5Iuf02DLED4z18IP:-NMay9437yLFul0n_M98:bn57xiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1096)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Maybe the question being asked here is, could we ever drop a filter which is still needed?  It seems that if the `non_outer_col` is already in the same equivalence set with `outer_col` due to IN or NOT IN subquery connecting conditions, it is OK to generate a `non_outer_col = non_outer_col` filter because the filtering would be done by the IN or NOT IN.  This mapped term gets normalized into something like `non_outer_col IS DISTINCT FROM CAST(NULL AS INT8)`.
e.g.
```
explain select * from t1 where a in (select a from t3 where t3.a = t1.a);
                                          info
----------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • hash join (semi)
  │ estimated row count: 1
  │ equality: (a) = (a)
  │
  ├── • filter
  │   │ estimated row count: 1
  │   │ filter: a IS DISTINCT FROM CAST(NULL AS INT8)
  │   │
  │   └── • scan
  │         estimated row count: 1 (100% of the table; stats collected 51 minutes ago)
  │         table: t1@t1_pkey
  │         spans: FULL SCAN
  │
  └── • filter
      │ estimated row count: 1
      │ filter: a IS DISTINCT FROM CAST(NULL AS INT8)
      │
      └── • scan
            estimated row count: 1 (100% of the table; stats collected 34 minutes ago)
            table: t3@t3_pkey
            spans: FULL SCAN
```
</blockquote></details>

As Mark says, we only make the replacement in cases where it doesn't affect the result at the level of the matched filter. I'll add a test case that leads to a column being set equal to itself.


<!-- Sent from Reviewable.io -->

2023-01-25 16:42 UTC, mgartner requested changes
This is very cool. Nice work!

> Reviewed 1 of 3 files at r1, 4 of 7 files at r2, 1 of 1 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-:-NMdnTewBMxGrMJLDYhA:b-1qbf0n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rafiss)

___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1072 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY45OT5AVJh8rKuPnk:-NMdhbDD2bpSCLB6vdDF:brqa13) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1072)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

@mgartner friendly ping on this point - TL;DR is that we could do it in one pass with more allocations.
</blockquote></details>

Thanks for the explanation. No need to change this.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1096 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY5Iuf02DLED4z18IP:-NMdhfB43_EzghSvRNRl:b-1qur4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1096)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

As Mark says, we only make the replacement in cases where it doesn't affect the result at the level of the matched filter. I'll add a test case that leads to a column being set equal to itself.
</blockquote></details>

I see. I think my original concern is void - this would only happen if we had something like an inner filter of `inner_col = outer_col` and an outer filter of `outer_col = inner_col` - I don't even know if that's possible with other normalization rules that should eliminate one of those filters, but even if it were, we'd never eliminate the outer filter.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1091 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMde9oy24YLfjReOkfv:-NMde9oy24YLfjReOkfw:b-co6axc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1091)):*
> ```Go
> 		// candidateCols is the set of input columns for which it may be possible to
> 		// push a filter constraining the column to be equal to an outer column.
> 		candidateCols := input.Relational().FuncDeps.ComputeEquivGroup(col)
> ```

super nit: Can you think of a better name for `candidateCols` (and associated functions with "candidate" in the name)? It's mildly confusing because it's unclear if they represent columns that are candidates to be replaced or candidates to replace with. Maybe `substituteCols`?
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1095 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdgMZE9TJTTuHnHBCJ:-NMdgMZE9TJTTuHnHBCK:bwq9k66) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1095)):*
> ```Go
> 			candidateCols = filters[i].ScalarProps().FuncDeps.ComputeEquivClosureNoCopy(candidateCols)
> 		}
> 		candidateCols.DifferenceWith(input.Relational().OuterCols)
> ```

nit: `candidateCols.DifferenceWith(outerCols)`
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdbpLK5zIdjpOYrswI:-NMdbpLK5zIdjpOYrswJ:bb5uvum) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1104)):*
> ```Go
> 			}
> 			if v, ok := e.(*memo.VariableExpr); ok && v.Col == col {
> 				if replaceCol, ok := candidateCols.Next(0); ok {
> ```

nit: You could use `candidateCols.SingleColumn()` here instead and avoid the `if`.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1111 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdde8I-gzOnXT0Wjo5:-NMdde8I-gzOnXT0Wjo6:b-s1eo06) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1111)):*
> ```Go
> 			}
> 			switch t := e.(type) {
> 			case memo.RelExpr:
> ```

nit: I think you can mix structs and interfaces in a type switch, for example:

```go
switch t := e.(type) {
case *memo.VariableExpr:
  // ...
case memo.RelExpr:
  // ...
case opt.ScalarExpr:
  // ...
}
```
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1125 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdd34a0_F365hs3PJc:-NMdd34a0_F365hs3PJd:bon42pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1125)):*
> ```Go
> 			// If we made it here, candidateCols has been modified so that calling the
> 			// replace function on the current expression is valid.
> 			return c.f.Replace(e, replaceFn)
> ```

Don't we need to reset candidate cols to what it was before we called `getCandidateColsRelExpr`? For example, if we recurse into the left side of a join and mutate the candidate columns, don't we want to revert the candidate columns when we pop back up and recurse into the right side of a join?
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1216 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdgfIz2PBLw9LKL46k:-NMdgfIz2PBLw9LKL46l:b-p8u88e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1216)):*
> ```Go
> 	// both inputs. We filter out non-output columns from candidateCols on
> 	// each recursive call to TryRemapOuterCols, so we don't need to remove any
> 	// columns here.
> ```

I don't fully understand this last sentence. Don't we need to filter out the `SetPrivate.OutCols` for the recursion with the `replaceFn` so that we don't replace an outer column with another outer column (from the perspective of the set's left or right child)? I think a test with replacement in two sides of a setop might reveal this.
___
*[`pkg/sql/opt/norm/rules/decorrelate.opt` line 86 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdipBi-vaiTJR0hxrQ:-NMdipBi-vaiTJR0hxrR:b-z1ndd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/rules/decorrelate.opt#L86)):*
> ```
> # decorrelation rules because it does not perform any transformations beyond the
> # variable replacement. This prevents situations where decorrelation rules make
> # the plan worse in their attempts to decorrelate the query.
> ```

nit: elaborating on this last sentence or adding an example might be helpful. Or is it obvious how the plans can become worse, and I'm not seeing it?
___
*[`pkg/sql/opt/norm/rules/decorrelate.opt` line 101 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdm-Op51Ip25bLenk7:-NMdm-Op51Ip25bLenk8:b-2pc22o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/rules/decorrelate.opt#L101)):*
> ```
> 
> # TryRemapJoinOuterColsLeft is similar to TryRemapJoinOuterColsRight, but it
> # applies to the right input of a join.
> ```

nit "right input" => "left input"
___
*[`pkg/sql/opt/norm/testdata/rules/decorrelate` line 6154 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdlHMFDbqRTbNPFhoQ:-NMdlHMFDbqRTbNPFhoR:b-ciabzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/testdata/rules/decorrelate#L6154)):*
> ```
> # Case with a LeftJoin. The filter can be mapped to the right input.
> norm expect=TryRemapJoinOuterColsRight format=hide-all
> SELECT * FROM xy INNER JOIN LATERAL (SELECT * FROM ab LEFT JOIN (SELECT u, v + x FROM uv) ON a = u) ON a = x
> ```

Can you add a case like this were the remap cannot happen because the join filter doesn't have an equality fil [...]

2023-01-26 01:48 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1096 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NIY5Iuf02DLED4z18IP:-NMeKMQW-MxZBUFcRZQa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e37a13e9f28c911e43989ad409375ac7924492f/pkg/sql/opt/norm/decorrelate_funcs.go#L1096)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I see. I think my original concern is void - this would only happen if we had something like an inner filter of `inner_col = outer_col` and an outer filter of `outer_col = inner_col` - I don't even know if that's possible with other normalization rules that should eliminate one of those filters, but even if it were, we'd never eliminate the outer filter.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1091 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMde9oy24YLfjReOkfv:-NMeJQRt6ZiWQd-YsNiQ:bopbm7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1091)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

super nit: Can you think of a better name for `candidateCols` (and associated functions with "candidate" in the name)? It's mildly confusing because it's unclear if they represent columns that are candidates to be replaced or candidates to replace with. Maybe `substituteCols`?
</blockquote></details>

`substituteCols` sounds good to me. Done.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1095 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdgMZE9TJTTuHnHBCJ:-NMeJYX88KELgsViEsDy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1095)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `candidateCols.DifferenceWith(outerCols)`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdbpLK5zIdjpOYrswI:-NMeJpuCB7eHpcOExrEo:b-jsfrd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1104)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: You could use `candidateCols.SingleColumn()` here instead and avoid the `if`.
</blockquote></details>

`SingleColumn` panics if there isn't exactly one column, and there could be multiple possible substitute columns.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1111 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdde8I-gzOnXT0Wjo5:-NMeKJuN6RBUTohaaLh1:b-4pj5my) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1111)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I think you can mix structs and interfaces in a type switch, for example:

```go
switch t := e.(type) {
case *memo.VariableExpr:
  // ...
case memo.RelExpr:
  // ...
case opt.ScalarExpr:
  // ...
}
```
</blockquote></details>

Nice, done.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1125 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdd34a0_F365hs3PJc:-NMeKym50TgYZ6vhvfQ-:b3jqjck) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1125)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Don't we need to reset candidate cols to what it was before we called `getCandidateColsRelExpr`? For example, if we recurse into the left side of a join and mutate the candidate columns, don't we want to revert the candidate columns when we pop back up and recurse into the right side of a join?
</blockquote></details>

Really good catch. In practice this meant we'd end up firing the rule more often than needed (e.g. once per correlated input of a join/set op). I've refactored the traversal logic so that the new `substituteCols` gets captured by the `replaceFunc` definition without also setting the old one.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1216 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdgfIz2PBLw9LKL46k:-NMeMqRu3XcrLO4Q5KsR:b2bnsgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1216)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't fully understand this last sentence. Don't we need to filter out the `SetPrivate.OutCols` for the recursion with the `replaceFn` so that we don't replace an outer column with another outer column (from the perspective of the set's left or right child)? I think a test with replacement in two sides of a setop might reveal this.
</blockquote></details>

I think this comment was outdated - when `getSubstituteColsRelExpr` is called for the left input, `substituteColumns` will be restricted to just the left columns and vice versa for the right input. Additionally, it is possible for `OutCols` and `LeftCols` to be the same - say for an Intersect. That being said, I think the clearest thing will be to just construct the new substituteCols from scratch. Let me know what you think.
___
*[`pkg/sql/opt/norm/rules/decorrelate.opt` line 86 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdipBi-vaiTJR0hxrQ:-NMePqlCDyG5-_50IyXd:b-o7ptkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/rules/decorrelate.opt#L86)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: elaborating on this last sentence or adding an example might be helpful. Or is it obvious how the plans can become worse, and I'm not seeing it?
</blockquote></details>

Added some elaboration, let me know what you think.
___
*[`pkg/sql/opt/norm/rules/decorrelate.opt` line 101 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdm-Op51Ip25bLenk7:-NMePx8049Fk4j3wBIjn:b-4c5ezp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/rules/decorrelate.opt#L101)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit "right input" => "left input"
</blockquote></details>

Good catch, done.
___
*[`pkg/sql/opt/norm/testdata/rules/decorrelate` line 6154 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdlHMFDbqRTbNPFhoQ:-NMeREeS42JpfGZv927p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/testdata/rules/decorrelate#L6154)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add a case like this were the remap cannot happen because the join filter doesn't have an equality filter with a column on the right?

Can you also add a case where both the left and right side of the join should have columns remapped? I think that might expose the need to reset `candidateCols` (see my previous comment).
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/testdata/rules/decorrelate` line 6293 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdlkNrCywGdwLyzJPt:-NMeS7WY4saI2rIQ6hjN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/testdata/rules/decorrelate#L6293)):*
<details><summary><i>P [...]

2023-01-26 16:22 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-:-NMismI7-98DqT4ikYe7:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rafiss)

___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdbpLK5zIdjpOYrswI:-NMimYNpBdwwEZgdEFTm:b1clgq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1104)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`SingleColumn` panics if there isn't exactly one column, and there could be multiple possible substitute columns.
</blockquote></details>

Oh right, sorry for the noise.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1125 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdd34a0_F365hs3PJc:-NMisiGx8Hx4Vm9wpzcO:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1125)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Really good catch. In practice this meant we'd end up firing the rule more often than needed (e.g. once per correlated input of a join/set op). I've refactored the traversal logic so that the new `substituteCols` gets captured by the `replaceFunc` definition without also setting the old one.
</blockquote></details>

:100: 
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1216 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdgfIz2PBLw9LKL46k:-NMiqWDE2oBKEhxukYZb:b-85i63v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/decorrelate_funcs.go#L1216)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think this comment was outdated - when `getSubstituteColsRelExpr` is called for the left input, `substituteColumns` will be restricted to just the left columns and vice versa for the right input. Additionally, it is possible for `OutCols` and `LeftCols` to be the same - say for an Intersect. That being said, I think the clearest thing will be to just construct the new substituteCols from scratch. Let me know what you think.
</blockquote></details>

LGTM.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1133 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMipWcX2wLt27nlmYog:-NMipWcX2wLt27nlmYoh:b-9y9esy) ([raw file](https://github.com/cockroachdb/cockroach/blob/736a8e3aa02619e83458a9ec7e5a5b405f35b393/pkg/sql/opt/norm/decorrelate_funcs.go#L1133)):*
> ```Go
> 		// outer-column remapping within (the children of) a RelExpr. Note that
> 		// getSubstituteColsRelExpr copies substituteCols before modifying it, so
> 		// different branches of the traversal don't interact.
> ```

nit: "dont' interact **on the same column set**."
___
*[`pkg/sql/opt/norm/rules/decorrelate.opt` line 86 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMdipBi-vaiTJR0hxrQ:-NMio6d27aZLPlDuE6pF:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6eae2848975b89d78d2a3a57b5ec65edd22363a/pkg/sql/opt/norm/rules/decorrelate.opt#L86)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Added some elaboration, let me know what you think.
</blockquote></details>

:+1: 
___
*[`pkg/sql/opt/norm/testdata/rules/decorrelate` line 6343 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMion3Z61MmLBDUsLrX:-NMion3Z61MmLBDUsLrY:b-vqks6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/736a8e3aa02619e83458a9ec7e5a5b405f35b393/pkg/sql/opt/norm/testdata/rules/decorrelate#L6343)):*
> ```
>  │         ├── scan uv
>  │         └── projections
>  │              └── v + u
> ```

It's tricky to see why it's valid to replace `v+x` with `v+u`. I think it might be more obvious if you alias the result of the union and qualify it in the join condition, e.g.:

```
SELECT * FROM xy INNER JOIN LATERAL (SELECT * FROM (SELECT a, b+x FROM ab) UNION (SELECT u, v+x FROM uv)) AS rhs ON rhs.a = x
```

You might want to do the same with the other set test cases.


<!-- Sent from Reviewable.io -->

2023-01-26 23:54 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92378)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rafiss)

___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 1133 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMipWcX2wLt27nlmYog:-NMkR2Es3mBh7k2hLmRk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb64392346a2fd9c3bb2605b0022730297b125c/pkg/sql/opt/norm/decorrelate_funcs.go#L1133)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "dont' interact **on the same column set**."
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/testdata/rules/decorrelate` line 6343 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92378#-NMion3Z61MmLBDUsLrX:-NMkV18XAmYa-AOJwIzT:b9xudln) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb64392346a2fd9c3bb2605b0022730297b125c/pkg/sql/opt/norm/testdata/rules/decorrelate#L6343)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's tricky to see why it's valid to replace `v+x` with `v+u`. I think it might be more obvious if you alias the result of the union and qualify it in the join condition, e.g.:

```
SELECT * FROM xy INNER JOIN LATERAL (SELECT * FROM (SELECT a, b+x FROM ab) UNION (SELECT u, v+x FROM uv)) AS rhs ON rhs.a = x
```

You might want to do the same with the other set test cases.
</blockquote></details>

I added an alias to each of the Set ops `foo(a, b)` and had the filter reference it. Hopefully that clears things up.


<!-- Sent from Reviewable.io -->

2023-01-27 01:15 UTC, DrewKimball commented
Thanks for the thorough reviews!

Github CI failure is a known flake.
bors r+

2023-01-27 07:15 UTC, merged