pgwire: lift readVersion + TLS handshake into the pre-serve handler
cockroachdb/cockroach pull request #92576
Opened 2022-11-28 15:25 UTC by knz

2022-11-28 15:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/92576)
<!-- Reviewable:end -->

2022-11-28 15:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/92576)
<!-- Reviewable:end -->

2022-11-29 18:25 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/sql/pgwire/server.go` line 987 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92576#-NI3b5NG9RyfxC5ZZOt9:-NI3b5NG9RyfxC5ZZOtA:b-qgwo2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/10cf4c8bb3b2c9cff29597249a42ea6488904930/pkg/sql/pgwire/server.go#L987)):*
> ```Go
> 	// Replace RemoteAddr if specified by client and we trust the client.
> 	if cp.clientProvidedRemoteAddr != "" {
> 		if !trustClientProvidedRemoteAddr {
> ```

since this `trustClientProvidedRemoteAddr` comes from an env var, i don't see why the client-provided address logic is tenant-specfic
___
*[`pkg/sql/pgwire/server.go` line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92576#-NI3c8Kj2lrrcYXZtToh:-NI3c8Kj2lrrcYXZtToi:bui2qk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/521774a83ddf6ddc43298591d96f78f0812e6c79/pkg/sql/pgwire/server.go#L258)):*
> ```Go
> 	// tenantConnMonitor is the pool where the memory usage for the
> 	// initial connection overhead is accounted for.
> 	tenantConnMonitor *mon.BytesMonitor
> ```

should this be called `tenantSpecificConnMonitor`? it seems like that `tenantSpecificXYZ` convention was used elsewhere


<!-- Sent from Reviewable.io -->

2022-12-06 12:59 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/sql/pgwire/server.go` line 987 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92576#-NI3b5NG9RyfxC5ZZOt9:-NIbWA3n0y6mtNkTjGLx:bp7ay4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/69040924931b05ff46933b4c55c49e632492938b/pkg/sql/pgwire/server.go#L987)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since this `trustClientProvidedRemoteAddr` comes from an env var, i don't see why the client-provided address logic is tenant-specfic
</blockquote></details>

You are very right. I'm moving it there in #92579.
___
*[`pkg/sql/pgwire/server.go` line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92576#-NI3c8Kj2lrrcYXZtToh:-NIbW9Ox6H0Q6_Jo6n0w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/040237785177d2485918a87319829b35fd4f18b1/pkg/sql/pgwire/server.go#L258)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this be called `tenantSpecificConnMonitor`? it seems like that `tenantSpecificXYZ` convention was used elsewhere
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-07 15:19 UTC, rafiss approved these changes
> Reviewed 1 of 5 files at r5, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92576)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)



<!-- Sent from Reviewable.io -->

2023-01-09 01:50 UTC, merged