sql: Fix create partial stats test cases
cockroachdb/cockroach pull request #92617
Opened 2022-11-28 20:51 UTC by faizaanmadhani

This commit modifies the create partial statistics test cases to ensure that the full table statistics that are to be used to create a partial statistic exist in the cache. Previously, this was not the case so certain tests had non-deterministic outputs causes failures in stress tests.

Resolves: #92495

Epic: CRDB-19449

Release note: None

2022-11-28 20:51 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/92617)
<!-- Reviewable:end -->

2022-11-28 21:26 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92617)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @michae2)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 2080 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-NI-7-R30F3_VNTdmfuL:-NI-7-R30F3_VNTdmfuM:b5hzv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce2a3def12ef1bfd614aa576ae2014046ac41da/pkg/sql/logictest/testdata/logic_test/distsql_stats#L2080)):*
> ```
> # Test null values.
> statement ok
> SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;
> ```

nit: this should not be needed since we always disable auto stats in logic tests (see `newCluster` in `logic.go`) and in this file we don't enable them. What is the reason you included this? I'd guess that the bug you're fixing is due to table stats cache not being populated and not that some extra stats are being collected.


<!-- Sent from Reviewable.io -->

2022-11-28 21:34 UTC, faizaanmadhani commented
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 2080 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-NI-7-R30F3_VNTdmfuL:-NI-7ocl33XJpERAy9hM:b-vcphqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce2a3def12ef1bfd614aa576ae2014046ac41da/pkg/sql/logictest/testdata/logic_test/distsql_stats#L2080)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this should not be needed since we always disable auto stats in logic tests (see `newCluster` in `logic.go`) and in this file we don't enable them. What is the reason you included this? I'd guess that the bug you're fixing is due to table stats cache not being populated and not that some extra stats are being collected.
</blockquote></details>

I didn't realize we already disabled this, but this shouldn't be here anyways. Since this is disabled by default I've also removed it from when it's disabled above as well. 


<!-- Sent from Reviewable.io -->

2022-11-28 21:50 UTC, michae2 requested changes
Nice, glad it worked!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-:-NI-CzPN3Es3JaNDm50Y:b-igvjqa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @yuzefovich)

___
*[`pkg/sql/alter_table.go` line 1379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-NI-9evY1MCTgpdeoNTy:-NI-9evY1MCTgpdeoNTz:b-w0d0do) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce2a3def12ef1bfd614aa576ae2014046ac41da/pkg/sql/alter_table.go#L1379)):*
> ```Go
> 	}
> 
> 	if !settings.Version.IsActive(ctx, clusterversion.V23_1AddPartialStatisticsPredicateCol) {
> ```

If the `JSONStatistics` has a partial predicate, it would be wrong to insert it into table_statistics without the partial predicate, even if we haven't yet crossed the version gate. We need to throw an error if `s.PartialPredicate != ""`.
___
*[`pkg/sql/stats/new_stat.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-NI-93aLDSs2iyHOXN3K:-NI-93aLDSs2iyHOXN3L:bljp8wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce2a3def12ef1bfd614aa576ae2014046ac41da/pkg/sql/stats/new_stat.go#L106)):*
> ```Go
> 					"nullCount",
> 					"avgSize",
> 					histogram
> ```

nit: was this already fixed in another PR?
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 2096 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-NI-8Shs1OpPBp6yqb11:-NI-8Shs1OpPBp6yqb12:b-7y26c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce2a3def12ef1bfd614aa576ae2014046ac41da/pkg/sql/logictest/testdata/logic_test/distsql_stats#L2096)):*
> ```
> 
> statement ok
> ALTER TABLE a_null INJECT STATISTICS '$a_null_stats'
> ```

nit: Please leave comments at all of these `ALTER TABLE INJECT STATISTICS` here and below explaining that the purpose is to invalidate the stats cache.


<!-- Sent from Reviewable.io -->

2022-11-28 21:55 UTC, faizaanmadhani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92617)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @yuzefovich)

___
*[`pkg/sql/stats/new_stat.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-NI-93aLDSs2iyHOXN3K:-NI-DLkkA5lcuvrymf2R:b-th5gfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce2a3def12ef1bfd614aa576ae2014046ac41da/pkg/sql/stats/new_stat.go#L106)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: was this already fixed in another PR?
</blockquote></details>

It was supposed to be fixed in #92419, but that PR hasn't been merged in yet because there's a test there that keeps timing out. In order the keep the changes separate I can remove this change from this PR and we can merge in the other one first.


<!-- Sent from Reviewable.io -->

2022-11-28 22:13 UTC, faizaanmadhani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92617)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @yuzefovich)

___
*[`pkg/sql/alter_table.go` line 1379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-NI-9evY1MCTgpdeoNTy:-NI-ILtYAAulxyL7O_zk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce2a3def12ef1bfd614aa576ae2014046ac41da/pkg/sql/alter_table.go#L1379)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If the `JSONStatistics` has a partial predicate, it would be wrong to insert it into table_statistics without the partial predicate, even if we haven't yet crossed the version gate. We need to throw an error if `s.PartialPredicate != ""`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-28 22:18 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thank you!

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-:-NI-JX4x-4pqRucap6x1:b-ae66e1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @faizaanmadhani, @mgartner, and @yuzefovich)

___
*[`pkg/sql/alter_table.go` line 1382 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-NI-IvWn1mfZxrXa1sqt:-NI-IvWn1mfZxrXa1squ:b-qkv1lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be6fa8956f084d17d230f4e2eb81fc92975f2ea/pkg/sql/alter_table.go#L1382)):*
> ```Go
> 
> 		if s.PartialPredicate != "" {
> 			return pgerror.Newf(pgcode.ObjectNotInPrerequisiteState, "statistic to insert is partial but cluster version is below 23.1")
> ```

nit: The injected statistics often contain dozens of objects, and can be several megabytes in size. Can we add something to this error message that helps identify which one was partial? Maybe the column name and the collection time?
___
*[`pkg/sql/stats/new_stat.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92617#-NI-93aLDSs2iyHOXN3K:-NI-JPFUBnhs9fpMFmWj:brxp9sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fce2a3def12ef1bfd614aa576ae2014046ac41da/pkg/sql/stats/new_stat.go#L106)):*
<details><summary><i>Previously, faizaanmadhani (Faizaan Madhani) wrote…</i></summary><blockquote>

It was supposed to be fixed in #92419, but that PR hasn't been merged in yet because there's a test there that keeps timing out. In order the keep the changes separate I can remove this change from this PR and we can merge in the other one first.
</blockquote></details>

Sounds good!


<!-- Sent from Reviewable.io -->

2022-11-29 16:10 UTC, faizaanmadhani commented
TFTRs! 🎉 

bors r=michae2

2022-11-29 23:26 UTC, merged