kv: default kv.raft_log.disable_synchronization_unsafe to env var
cockroachdb/cockroach pull request #92642
Opened 2022-11-29 03:23 UTC by nvanbenschoten

This commit introduces a new environment variable called `COCKROACH_DISABLE_RAFT_LOG_SYNCHRONIZATION_UNSAFE` which controls the default value of the `kv.raft_log.disable_synchronization_unsafe` cluster setting.

This is useful for operators that want to disable Raft log syncs ahead of cluster bootstrapping. In particular, this is useful to speed up tsdump ingestion on macOS. I plan to add `COCKROACH_DISABLE_RAFT_LOG_SYNCHRONIZATION_UNSAFE=true` to the instructions in https://cockroachlabs.atlassian.net/wiki/spaces/CKB/pages/2284880796/Exporting+Importing+Timeseries+from+a+Cluster.

Release note: None.
Epic: None.

2022-11-29 08:48 UTC, tbg commented
The tsdump import already disables fsync,

https://github.com/cockroachdb/cockroach/blob/2b595c5214aead3e7d4f47f9a1dedce57dba6e7f/pkg/server/import_ts.go#L71-L74

I'm still fine with adding the env var, but it should not be necessary for tsdump, and so if we still want it we should update the PR/commit message before merge.

It doesn't seem necessary to update the runbooks either.

2022-11-29 08:48 UTC, tbg requested changes
.

2022-11-30 15:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/92642)
<!-- Reviewable:end -->

2022-12-20 18:02 UTC, nvanbenschoten commented
> The tsdump import already disables fsync

Huh, TIL. I could have sworn that wasn't always the case. It looks like this is new-ish as of https://github.com/cockroachdb/cockroach/commit/4442cc4854adde7210575fe14ddf12e75ed58215.

Regardless, I updates the commit message and PR description to remove mention of tsdumps.

2022-12-21 07:47 UTC, tbg approved these changes

2022-12-21 07:47 UTC, tbg commented
bors r+

2022-12-21 08:40 UTC, merged