server, ui: Multi-tenant login/logout and tenant dropdown
cockroachdb/cockroach pull request #92694
Opened 2022-11-29 21:51 UTC by Santamaura

This PR adds a few changes:

- a new format for the session cookie if the cluster is multi-tenant, the new format is `<encoded_session>,<tenant_name>&<encoded_session2>,<tenant_name2>` etc.
- introduces a way to fanout and perform login for all tenants
- introduces a way to fanout and perform logout for all tenants
- changes to both `getSession` functions in order to correctly parse the new session cookie format
- a top level tenant dropdown which lists all tenants logged in to; selecting a different tenant will set the `tenant` cookie (so that traffic can be correctly routed) and reload the page

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-14546

2022-11-30 15:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/92694)
<!-- Reviewable:end -->

2022-12-01 09:20 UTC, knz reviewed
Overall architecture LGTM.  What's the followup issue/epic to discuss the semantics when one of the session expires?

This PR will also benefit from more unit tests.

> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-:-NIBz20E8MgqWOayA2vt:b-i2zrd1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/server/api_v2_auth.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxyVW0kY3uwfKOnQX:-NIBxyVW0kY3uwfKOnQY:bg5742w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L331)):*
> ```Go
> 		var session string
> 		// This case is if the session cookie has a multi-tenant pattern.
> 		if strings.Contains(possibleSessions[i], ",") {
> ```

Please move this logic to its own function in authentication.go.
Then also please implement unit tests for that function.
___
*[`pkg/server/api_v2_auth.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBy6My8J5H7OrqJFZX:-NIBy6My8J5H7OrqJFZY:b2n48qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L331)):*
> ```Go
> 		var session string
> 		// This case is if the session cookie has a multi-tenant pattern.
> 		if strings.Contains(possibleSessions[i], ",") {
> ```

Also, this condition is brittle and makes the format non-extensible.
I recommend a prefix with a special name, and match that instead.
___
*[`pkg/server/api_v2_auth.go` line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIByIMh0UDtGBY1lVbD:-NIByIMh0UDtGBY1lVbE:b-dzvx4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L336)):*
> ```Go
> 				return "", nil, http.StatusBadRequest, errors.New("unable to find tenant cookie")
> 			}
> 			sessionSlice := strings.FieldsFunc(possibleSessions[i], func(r rune) bool {
> ```

I don't understand this condition. What are you trying to achieve?
___
*[`pkg/server/authentication.go` line 636 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBy1YO4J9Hwn4HRZm1:-NIBy1YO4J9Hwn4HRZm2:bysx0j5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/authentication.go#L636)):*
> ```Go
> 		// This case is if the session cookie has a multi-tenant pattern.
> 
> 		if strings.Contains(c.Value, ",") {
> ```

Reuse the common function (see previous comment)
___
*[`pkg/server/server_controller.go` line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBx3f543NB_vUA3DGw:-NIBx3f543NB_vUA3DGx:b-wu8roh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L209)):*
> ```Go
> 	// if the client didnt specify tenant name call these for login/logout.
> 	if !nameProvided {
> 		if r.URL.Path == loginPath {
> ```

nit: use `switch`
___
*[`pkg/server/server_controller.go` line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBx7Pz3V3O_Dh5ar7V:-NIBx7Pz3V3O_Dh5ar7W:b-i5tisl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L245)):*
> ```Go
> }
> 
> type sessionWriter struct {
> ```

I recommend you move this helper to a separate file.
___
*[`pkg/server/server_controller.go` line 287 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIByqga1H4dsgDgj1cI:-NIByqga1H4dsgDgj1cJ:b-og290k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L287)):*
> ```Go
> }
> 
> // login for all tenant, find better nane
> ```

yes, please do. Also enhance the comment that explains what this function does.
___
*[`pkg/server/server_controller.go` line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIByuER75KNLp7J-JYy:-NIByuER75KNLp7J-JYz:b60wzty) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L289)):*
> ```Go
> // login for all tenant, find better nane
> func (c *serverController) loginFanout() http.Handler {
> 	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
> ```

It would also be good to sprinkle the body of the function with explanatory comments that explain what each part does. Ditto for logoutFanout.
___
*[`pkg/server/server_controller.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxV05ElqFinc_bob6:-NIBxV05ElqFinc_bob7:b-dza89c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L308)):*
> ```Go
> 			if err != nil {
> 				log.Warningf(ctx, "unable to find tserver for tenant %q: %v", name, err)
> 				w.WriteHeader(http.StatusInternalServerError)
> ```

missing return?
___
*[`pkg/server/server_controller.go` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIByhpgA6BKv4NKcEKO:-NIByhpgA6BKv4NKcEKP:b-h3xqnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L317)):*
> ```Go
> 			} else {
> 				sessionCookieSlice := strings.Split(strings.ReplaceAll(setCookieHeader, "session=", ""), ";")
> 				sessionsStr += sessionCookieSlice[0] + "," + name + "&"
> ```

This composition needs to go into its own function alongside the other new one in authentication.go, so that someone working in that area can see them side-by-side.
___
*[`pkg/server/server_controller.go` line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxNaoEBtr490e1hoZ:-NIBxNaoEBtr490e1ho_:b91csg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L333)):*
> ```Go
> 			cookie = http.Cookie{
> 				Name:     TenantSelectCookieName,
> 				Value:    catconstants.SystemTenantName,
> ```

add a reference to https://github.com/cockroachdb/cockroach/issues/91741 in a comment around here.
___
*[`pkg/server/server_controller.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxbNW0aPT-8jIHG-5:-NIBxbNW0aPT-8jIHG-6:bdaoub3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L368)):*
> ```Go
> 			if err != nil {
> 				log.Warningf(ctx, "%q", err)
> 				w.WriteHeader(http.StatusInternalServerError)
> ```

missing return
___
*[`pkg/server/server_controller.go` line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxcLm12L3s3CQzqjh:-NIBxcLm12L3s3CQzqji:bdaoub3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L374)):*
> ```Go
> 			if err != nil {
> 				log.Warningf(ctx, "unable to find tserver for tenant %q: %v", name, err)
> 				w.WriteHeader(http.StatusInternalServerError)
> ```

missing return
___
*[`pkg/server/server_controller.go` line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxd9sDhQ76SJ4RJI0:-NIBxd9sDhQ76SJ4RJI1:bdaoub3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L379)):*
> ```Go
> 			if sw.header.Get("Set-Cookie") == "" {
> 				log.Warningf(ctx, "logout for tenant %q failed", name)
> 				w.WriteHeader(http.StatusInternalServerError)
> ```

missing return
___
*[`pkg/server/tenant.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxpGq4i5Cnot6OkOX:-NIBxpGq4i5Cnot6OkOY:b20u0d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/tenant.go#L112)):*
> ```Go [...]

2022-12-01 14:09 UTC, koorosh reviewed
> Reviewed 5 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @Santamaura, and @zachlite)

___
*[`pkg/ui/workspaces/db-console/src/components/dropdown/dropdown.tsx` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NICp8RD7ityrkkHXmrf:-NICp8RD7ityrkkHXmrg:bsf0zew) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/ui/workspaces/db-console/src/components/dropdown/dropdown.tsx#L33)):*
> ```XML
>   className?: string;
>   menuPlacement?: "right" | "left";
>   icon?: JSX.Element;
> ```

`cluster-ui` package contains another version of `Dropdown` component that allows to customize icon. See example: `pkg/ui/workspaces/cluster-ui/src/dropdown/dropdown.stories.tsx:34`
___
*[`pkg/ui/workspaces/db-console/src/redux/tenantOptions.ts` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NICqlkU-0_oiueV7r_B:-NICqlkU-0_oiueV7r_C:b-fdi75k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/ui/workspaces/db-console/src/redux/tenantOptions.ts#L13)):*
> ```XML
>   const sessionCookieStr = document.cookie
>     .split(";")
>     .filter(row => row.trim().startsWith("session="))[0];
> ```

it is not safe to access `[0]`s element without assertion that array isn't empty.
___
*[`pkg/ui/workspaces/db-console/src/redux/tenantOptions.ts` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NID-4NdB5zWtyYJdDDo:-NID-4NdB5zWtyYJdDDp:b-p4ld4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/ui/workspaces/db-console/src/redux/tenantOptions.ts#L17)):*
> ```XML
>     ? sessionCookieStr
>         .replace(/["]/g, "")
>         .replace("session=", "")
> ```

Why `session=` is replaced?
___
*[`pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NID-fNx2MBtAG54GPEW:-NID-fNx2MBtAG54GPEX:bg4zzhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx#L36)):*
> ```XML
>   const setTenantCookie = (tenant: string) => {
>     if (tenant !== currentTenant) {
>       document.cookie = `${tenantIDKey}=${tenant};path=/`;
> ```

I suggest to define sagas to perform side effects like writing or reading cookies from `document` object.


<!-- Sent from Reviewable.io -->

2022-12-01 16:13 UTC, dhartunian submitted a review, later dismissed
Can you sync the PR description and commit messages? They shouldn't be different.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-:-NIDOmmy6UFMllDTpTGz:b-t0pjed)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura and @zachlite)

___
*[`pkg/server/server_controller.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIDPJmk310Nik2p2A8W:-NIDPJmk310Nik2p2A8X:b-9dt0x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L221)):*
> ```Go
> }
> 
> func getTenantNameFromHTTPRequest(r *http.Request) (string, bool) {
> ```

is the `bool` necessary here or can we just check if the name returned is not the system tenant?
___
*[`pkg/ui/workspaces/db-console/src/redux/alerts.ts` line 657 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBwbFh3aRAiM8uRkfr:-NIDPblYEqQj5eI3IkLO:bz2f9u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/ui/workspaces/db-console/src/redux/alerts.ts#L657)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Why did this need to change?
</blockquote></details>

This was an unrelated bug that were trying to squash while working. @santamaura can you lift the login-fail bug code out of here? It should be in a separate PR.
___
*[`pkg/ui/workspaces/db-console/src/redux/tenantOptions.ts` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIDSKJz4AGs9j7hD07x:-NIDSKJz4AGs9j7hD07y:bewas36) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/ui/workspaces/db-console/src/redux/tenantOptions.ts#L21)):*
> ```XML
>         .filter((_, idx) => idx % 2 == 1)
>     : [];
> };
> ```

any chance we can abstract all the cookie manipulation into a "library" in a single file? there's a lot of spread out code that deals with the cookies and it's tough to know if it's internally consistent and it's not well-tested.


<!-- Sent from Reviewable.io -->

2022-12-05 22:54 UTC, Santamaura reviewed
Yep, copied it over to the PR desc.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-:-NIZOin6-9WJ2Jv9HwMx:bbwzwz7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @koorosh, and @zachlite)

___
*[`pkg/server/api_v2_auth.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxyVW0kY3uwfKOnQX:-NIZOpDCArjEOZJpi2bp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L331)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Please move this logic to its own function in authentication.go.
Then also please implement unit tests for that function.
</blockquote></details>

Done.
___
*[`pkg/server/api_v2_auth.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBy6My8J5H7OrqJFZX:-NIZOsQ20gPAn4yHhirn:blnwhhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L331)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Also, this condition is brittle and makes the format non-extensible.
I recommend a prefix with a special name, and match that instead.
</blockquote></details>

IIUC you want to add something to the session cookie value before the actual values, so the format will become e.g. `session=<some_prefix>:<session>,<tenant_name>&<session2>,<tenant_name2>` etc? If so, any idea for the prefix, maybe `multi_tenant:`?
___
*[`pkg/server/api_v2_auth.go` line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIByIMh0UDtGBY1lVbD:-NIZPtpV5v31PiJdFAMe:bk38u23) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L336)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I don't understand this condition. What are you trying to achieve?
</blockquote></details>

My reasoning was if for some reason the tenant value is an empty string, then there is something not right and we should return an error. If you think it's unnecessary I can remove it.
___
*[`pkg/server/authentication.go` line 636 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBy1YO4J9Hwn4HRZm1:-NIZRCid7FNeO3e9VhF7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/authentication.go#L636)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Reuse the common function (see previous comment)
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBx3f543NB_vUA3DGw:-NIZRET59xbKA1YBaBR2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L209)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: use `switch`
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIDPJmk310Nik2p2A8W:-NIZRFeSE8LMjBU-8pjI:b-3jexh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L221)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is the `bool` necessary here or can we just check if the name returned is not the system tenant?
</blockquote></details>

I think we do actually need the `bool` because it distinguishes between whether the client actually provided a value or not. If the client provides no `tenant` cookie then we should do multi-tenant login/logout.
___
*[`pkg/server/server_controller.go` line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBx7Pz3V3O_Dh5ar7V:-NIZRf727wO9FMpUQ-2A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L245)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I recommend you move this helper to a separate file.
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 287 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIByqga1H4dsgDgj1cI:-NIZRgpL7W5Ia6B0_prF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L287)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

yes, please do. Also enhance the comment that explains what this function does.
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIByuER75KNLp7J-JYy:-NIZRi-51yH4A5n1EFDq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L289)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

It would also be good to sprinkle the body of the function with explanatory comments that explain what each part does. Ditto for logoutFanout.
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxV05ElqFinc_bob6:-NIZRjQV1hPCM66LKeCA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L308)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

missing return?
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIByhpgA6BKv4NKcEKO:-NIZRrPS2_77CPPNB9pV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L317)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This composition needs to go into its own function alongside the other new one in authentication.go, so that someone working in that area can see them side-by-side.
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxNaoEBtr490e1hoZ:-NIZSBi41NTaQ5Zdy0qY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L333)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

add a reference to https://github.com/cockroachdb/cockroach/issues/91741 in a comment around here.
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxbNW0aPT-8jIHG-5:-NIZSH6eBIWUl5U9J3PG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L368)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

missing return
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxcLm12L3s3CQzqjh:-NIZSHfK-4OiykNJhxHr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/server_controller.go#L374)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

missing return
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 379 at r1](https://revie [...]

2022-12-06 16:55 UTC, knz reviewed
> Reviewed 6 of 16 files at r2, 3 of 5 files at r3, 1 of 1 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/server/api_v2_auth.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxyVW0kY3uwfKOnQX:-NIcKvPo913fK5IvmMqQ:b-df94w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L331)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not really, no. That `strings.Contains` above does not belong here. It's part of the details of the encoding, so should be "inside" the API.
___
*[`pkg/server/api_v2_auth.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBy6My8J5H7OrqJFZX:-NIcL2joDJIsQjdyTAtd:b-hhsm7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L331)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

IIUC you want to add something to the session cookie value before the actual values, so the format will become e.g. `session=<some_prefix>:<session>,<tenant_name>&<session2>,<tenant_name2>` etc? If so, any idea for the prefix, maybe `multi_tenant:`?
</blockquote></details>

Let's bring this conversation over to the new function.
___
*[`pkg/server/api_v2_auth.go` line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIByIMh0UDtGBY1lVbD:-NIcL6d26ppkeNdaZQcu:b-7bmjjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L336)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

My reasoning was if for some reason the tenant value is an empty string, then there is something not right and we should return an error. If you think it's unnecessary I can remove it.
</blockquote></details>

What I'm asking is why not simply `strings.Split`.
___
*[`pkg/server/authentication.go` line 634 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIcLE5G-AELudZa5a-r:-NIcLE5G-AELudZa5a-s:b-z7i5f3) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a8dd6f6d4b14d8fe0feab96000ebb95f21449a/pkg/server/authentication.go#L634)):*
> ```Go
> 		sessionCookie := c
> 		// This case is if the session cookie has a multi-tenant pattern.
> 		if strings.Contains(c.Value, ",") {
> ```

ditto on strings.Contains
___
*[`pkg/server/authentication.go` line 720 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIcM-lN2b-XV4CgTa3B:-NIcM-lN2b-XV4CgTa3C:bdl8415) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a8dd6f6d4b14d8fe0feab96000ebb95f21449a/pkg/server/authentication.go#L720)):*
> ```Go
> }
> 
> // createAggregatedSessionCookieValue is used for multi-tenant login.
> ```

I think we should revisit the idea of overloading the `session` cookie here.
By changing the format of `session`, we're going to get a complex situation during a rolling upgrade from a previous version: the new format will be recognized by some nodes and not others.

What about reusing a completely separate cookie name? With its own format?
___
*[`pkg/server/authentication.go` line 728 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIcMJcl-pDVBBmgCF42:-NIcMJcl-pDVBBmgCF43:bf8rfgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a8dd6f6d4b14d8fe0feab96000ebb95f21449a/pkg/server/authentication.go#L728)):*
> ```Go
> 	for _, val := range sessionCookieValue {
> 		sessionCookieSlice := strings.Split(strings.ReplaceAll(val.setCookie, "session=", ""), ";")
> 		sessionsStr += sessionCookieSlice[0] + "," + val.name + "&"
> ```

I don't understand why you mix `,` and `&` here.
___
*[`pkg/util/httputil/http.go` line 116 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIcLdfzDA010P9sqpvW:-NIcLdfzDA010P9sqpvX:bbndihz) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a8dd6f6d4b14d8fe0feab96000ebb95f21449a/pkg/util/httputil/http.go#L116)):*
> ```Go
> 	httpClient http.Client, req *http.Request, response protoutil.Message,
> ) (*http.Response, error) {
> 	req.Header.Set("X-Cockroach-Tenant", "system")
> ```

What's this? What is it for?


<!-- Sent from Reviewable.io -->

2022-12-06 22:06 UTC, Santamaura reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @koorosh, and @zachlite)

___
*[`pkg/server/api_v2_auth.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBxyVW0kY3uwfKOnQX:-NIdRR9aDNovQRLHtTCx:b2xnuhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L331)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Not really, no. That `strings.Contains` above does not belong here. It's part of the details of the encoding, so should be "inside" the API.
</blockquote></details>

Fair enough, moved that logic (though it is not slightly different) into the api.
___
*[`pkg/server/api_v2_auth.go` line 331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIBy6My8J5H7OrqJFZX:-NIdRZme4ggMTMmHk6Sf:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L331)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Let's bring this conversation over to the new function.
</blockquote></details>

:thumbsup: 
___
*[`pkg/server/api_v2_auth.go` line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIByIMh0UDtGBY1lVbD:-NIdRvsHBIdnRqgYE8Hf:b-3cdxa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/server/api_v2_auth.go#L336)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

What I'm asking is why not simply `strings.Split`.
</blockquote></details>

Previously would have had to do `strings.Split` twice since there's 2 delimiters. Irrelevant now since I changed the format to be only comas.
___
*[`pkg/server/authentication.go` line 634 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIcLE5G-AELudZa5a-r:-NIdS6QbD2MHrsmTuxlS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a8dd6f6d4b14d8fe0feab96000ebb95f21449a/pkg/server/authentication.go#L634)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

ditto on strings.Contains
</blockquote></details>

Done.
___
*[`pkg/server/authentication.go` line 720 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIcM-lN2b-XV4CgTa3B:-NIdS7Db4mipCKWIT2Ik:b-w00q50) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a8dd6f6d4b14d8fe0feab96000ebb95f21449a/pkg/server/authentication.go#L720)):*
> we're going to get a complex situation during a rolling upgrade from a previous version: the new format will be recognized by some nodes and not others.

Yeah that's a good point. I've now made a `multitenant-session` cookie with the format like before except we only have commas to separate tenant names and encoded sessions.
___
*[`pkg/server/authentication.go` line 728 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIcMJcl-pDVBBmgCF42:-NIdSash1ArtzF2wk-e3:b1suoc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a8dd6f6d4b14d8fe0feab96000ebb95f21449a/pkg/server/authentication.go#L728)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I don't understand why you mix `,` and `&` here.
</blockquote></details>

It was for readability, I've swapped it to only commas.
___
*[`pkg/util/httputil/http.go` line 116 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIcLdfzDA010P9sqpvW:-NIdSlTb5zFYyF4npJdq:b5xleoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a8dd6f6d4b14d8fe0feab96000ebb95f21449a/pkg/util/httputil/http.go#L116)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

What's this? What is it for?
</blockquote></details>

`TestAuthenticationAPIUserLogin` and `TestLogout` were failing since not specifying the header (or cookie) would route to the multitenant login changes and the response header does not returning a content type. Adding this will make it route the original way.


<!-- Sent from Reviewable.io -->

2022-12-06 22:19 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/util/httputil/http.go` line 116 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIcLdfzDA010P9sqpvW:-NIdWAkNCVrNPgtC5tIZ:b-l2mz7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a8dd6f6d4b14d8fe0feab96000ebb95f21449a/pkg/util/httputil/http.go#L116)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

`TestAuthenticationAPIUserLogin` and `TestLogout` were failing since not specifying the header (or cookie) would route to the multitenant login changes and the response header does not returning a content type. Adding this will make it route the original way.
</blockquote></details>

I believe these tests should set the header (because they care). not here where it's going to "leak" to every other test


<!-- Sent from Reviewable.io -->

2022-12-07 13:27 UTC, koorosh requested changes, later dismissed
> Reviewed 2 of 16 files at r2, 1 of 5 files at r3, 1 of 1 files at r4, 1 of 3 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @Santamaura, and @zachlite)

___
*[`pkg/ui/workspaces/db-console/src/redux/cookies.ts` line 10 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgfgWO0q0qRiM1hkpY:-NIgfgWO0q0qRiM1hkpZ:b-mjjylb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/redux/cookies.ts#L10)):*
> ```XML
> // by the Apache License, Version 2.0, included in the file
> // licenses/APL.txt.
> ```

Would be nice to have generic function `getAllCookies()` that returns map of available cookies (that is already properly parsed from cookie string).
That would help simply call it from functions below, ie
```typescript
const cookiesMap: Map<string, string> = getAllCookies()
const mtCookieVal = cookiesMap.get("multitenant-session")
```
My primary concern here is having multiple functions that access `document` object.
___
*[`pkg/ui/workspaces/db-console/src/redux/cookies.ts` line 59 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgeXrr1riKjzTU3efn:-NIgeXrr1riKjzTU3efo:bxsv02s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/redux/cookies.ts#L59)):*
I suggest to use `document.location.pathname` as default `path` value.
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#write_a_new_cookie):
> ;path=path (e.g., '/', '/mydir') If not specified, defaults to the current path of the current document location.
___
*[`pkg/ui/workspaces/db-console/src/redux/cookies.ts` line 61 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgayYt7W5BGLv9lDJW:-NIgayYt7W5BGLv9lDJX:b66f0wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/redux/cookies.ts#L61)):*
> ```XML
>     cookieStr += "/";
>   }
>   document.cookie = cookieStr;
> ```

Is it intended to overwrite existing cookies with provided value? I'd suggest to append value?
___
*[`pkg/ui/workspaces/db-console/src/redux/login.ts` line 245 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgj8qj8Ruuz1Bq8_Rg:-NIgj8qj8Ruuz1Bq8_Rh:bswupfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/redux/login.ts#L245)):*
> ```XML
>     // we can do a multi-tenant logout.
>     if (tenants.length > 1) {
>       setCookie("tenant", "");
> ```

Is it also necessary to clear `multitenant-session` value?
___
*[`pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NID-fNx2MBtAG54GPEW:-NIgkilh71kpP6bPLVfd:b3s3rui) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d71611b8292e172048bb92d1dde4f77a47af439/pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx#L36)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Talked with CRUX about this because I was unsure, the consensus was we don't think it's necessary to have it in sagas because we don't have the cookies using any data from the redux store. If you feel strongly about it we discuss more though.
</blockquote></details>

Makes sense then! Thanks for clarifying this with others! 
___
*[`pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx` line 34 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgjY5a2i0aR4M-yjqw:-NIgjY5a2i0aR4M-yjqx:b-vo6rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx#L34)):*
> ```XML
>   };
> 
>   const setTenantCookie = (tenant: string) => {
> ```

nit. Let's rename this function to something like `onTenantChange` because it's a part of `TenantDropdown` UI component that now shouldn't know directly know about cookies.
___
*[`pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.spec.tsx` line 13 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgkSMc5kMFQNQ0vnbL:-NIgkSMc5kMFQNQ0vnbM:ba306ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.spec.tsx#L13)):*
> ```XML
>   selectTenantsFromMultitenantSessionCookie,
>   selectCurrentTenantFromCookie,
> } from "oss/src/redux/cookies";
> ```

nit. remove `oss/` prefix.


<!-- Sent from Reviewable.io -->

2022-12-07 18:49 UTC, Santamaura reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @koorosh, and @zachlite)

___
*[`pkg/ui/workspaces/db-console/src/redux/cookies.ts` line 10 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgfgWO0q0qRiM1hkpY:-NIhtRUh9-Ox6U5FhLyM:b7h5ebv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/redux/cookies.ts#L10)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Would be nice to have generic function `getAllCookies()` that returns map of available cookies (that is already properly parsed from cookie string).
That would help simply call it from functions below, ie
```typescript
const cookiesMap: Map<string, string> = getAllCookies()
const mtCookieVal = cookiesMap.get("multitenant-session")
```
My primary concern here is having multiple functions that access `document` object.
</blockquote></details>

I agree, created the function.
___
*[`pkg/ui/workspaces/db-console/src/redux/cookies.ts` line 59 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgeXrr1riKjzTU3efn:-NIhta441QD3T0tXB2SG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/redux/cookies.ts#L59)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I suggest to use `document.location.pathname` as default `path` value.
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#write_a_new_cookie):
> ;path=path (e.g., '/', '/mydir') If not specified, defaults to the current path of the current document location.

</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/redux/cookies.ts` line 61 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgayYt7W5BGLv9lDJW:-NIhtpPy4KpRQpJZRkt3:bkzxk7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/redux/cookies.ts#L61)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Is it intended to overwrite existing cookies with provided value? I'd suggest to append value?
</blockquote></details>

It's supposed to update a single cookie. Per the MDN doc you linked: `Note that you can only set/update a single cookie at a time using this method`. So it will only update the cookie of the provided name.
___
*[`pkg/ui/workspaces/db-console/src/redux/login.ts` line 245 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgj8qj8Ruuz1Bq8_Rg:-NIhu9XH-wF7cr-CpLfn:bv4smjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/redux/login.ts#L245)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Is it also necessary to clear `multitenant-session` value?
</blockquote></details>

No, it's needed server side to logout of all the sessions. It also gets cleared server side if logout is successful.
___
*[`pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx` line 34 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgjY5a2i0aR4M-yjqw:-NIhuXwW4kLwAUO00wMD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx#L34)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

nit. Let's rename this function to something like `onTenantChange` because it's a part of `TenantDropdown` UI component that now shouldn't know directly know about cookies.
</blockquote></details>

Done.
___
*[`pkg/util/httputil/http.go` line 116 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIcLdfzDA010P9sqpvW:-NIhulPN5RNHePSmbevy:b-9wj0yl) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a8dd6f6d4b14d8fe0feab96000ebb95f21449a/pkg/util/httputil/http.go#L116)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I believe these tests should set the header (because they care). not here where it's going to "leak" to every other test
</blockquote></details>

Agreed, changed so that only those tests set the tenant.


<!-- Sent from Reviewable.io -->

2022-12-07 19:00 UTC, knz reviewed
Ok I can see this is getting somewhere now. Just a few nits and this is good to go.

> Reviewed 2 of 8 files at r7, 6 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-:-NIhxKLc8RWFAlB2PIgC:b-xcg2f0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/server/api_v2_auth.go` line 313 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIhwrB57vEeo9NWqykx:-NIhwrB57vEeo9NWqyky:bfv3pvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/864a0046d79cb42a56d4d638f47688c0efc8a3db/pkg/server/api_v2_auth.go#L313)):*
> ```Go
> 	possibleSessions := []string{}
> 	if rawSession == apiV2UseCookieBasedAuth {
> 		cookies := req.Cookies()
> ```

Are you sure about the structure of this loop and the code below? Don't you want to first consider the multi-tenant session cookie, and only if that fails look at the  base session cookie?

The real question underlying mine is what do you propose the behavior should be if there's both a `session` and a `multi-tenant-session` cookie side-by-side in the request. Is that even supported? If not, we need an error; if yes, we need to choose a priority order and stick to it.
___
*[`pkg/server/authentication_test.go` line 505 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIhwN8x0HvzShIDtNRe:-NIhwN8x0HvzShIDtNRf:btykmvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/864a0046d79cb42a56d4d638f47688c0efc8a3db/pkg/server/authentication_test.go#L505)):*
> ```Go
> 		var resp serverpb.UserLoginResponse
> 		return httputil.PostJSONWithRequest(
> 			httpClient, ts.AdminURL()+loginPath+queryParams, &req, &resp,
> ```

Why did you need to change this one? Shouldn't the test pass even with your changes?
___
*[`pkg/server/authentication_test.go` line 578 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIhwQFK3e1N9Yad1wiz:-NIhwQFK3e1N9Yad1wj-:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/864a0046d79cb42a56d4d638f47688c0efc8a3db/pkg/server/authentication_test.go#L578)):*
> ```Go
> 	// Log out.
> 	var resp serverpb.UserLogoutResponse
> 	if err := httputil.GetJSON(authHTTPClient, ts.AdminURL()+logoutPath+queryParams, &resp); err != nil {
> ```

Ditto.


<!-- Sent from Reviewable.io -->

2022-12-07 21:01 UTC, dhartunian reviewed
> Reviewed 5 of 16 files at r2, 1 of 5 files at r3, 1 of 3 files at r6, 1 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @koorosh, @Santamaura, and @zachlite)

___
*[`-- commits` line 7 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIh_RuhBKGeKqVBdNQo):*
format needs fixing here. missing `>` I think. wrap in ``
___
*[`pkg/server/authentication.go` line 721 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIZT8qfCt87L8YPsdfv:-NIZT8qfCt87L8YPsdfw:btzqfp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d95554ffc380c634d2f49074c525b2c188cb96/pkg/server/authentication.go#L721)):*
> ```Go
> 
> // createAggregatedSessionCookieValue is used for multi-tenant login.
> // It takes a tenant name to set cookie map and converts it to a single
> ```

I think this is inaccurate. I don't see a "map" anywhere in here.
___
*[`pkg/server/authentication.go` line 723 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIZSgZYDINiGH0bSm5n:-NIZSgZZ3ZE8sViMl1tE:b-cbckof) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d95554ffc380c634d2f49074c525b2c188cb96/pkg/server/authentication.go#L723)):*
> ```Go
> // It takes a tenant name to set cookie map and converts it to a single
> // string which is the aggregated session. Currently the format of the
> // aggregated session is: session,tenant_name&session2,tenant_name2 etc.
> ```

nit: fix the comment to match cookie format and use `` to wrap the format.
___
*[`pkg/server/authentication.go` line 740 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIZSbC78ElA6FjaQxID:-NIZSbC78ElA6FjaQxIE:be9gld6) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d95554ffc380c634d2f49074c525b2c188cb96/pkg/server/authentication.go#L740)):*
> ```Go
> // method cannot find a match between the tenant name and session
> // or cannot find the tenant cookie value, it will return an empty
> // string to indicate this.
> ```

docstring should have some examples of valid cookies and what gets extracted.
___
*[`pkg/server/authentication.go` line 744 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIZSORP4kAfjPNLZrU_:-NIZSORP4kAfjPNLZrUa:b-qn7q29) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d95554ffc380c634d2f49074c525b2c188cb96/pkg/server/authentication.go#L744)):*
> ```Go
> 	tenantName := findTenantCookieValue(cookies)
> 	if tenantName == "" {
> 		return "", errors.New("unable to find tenant cookie")
> ```

I thought this would default to system tenant.
___
*[`pkg/server/session_writer.go` line 25 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIha3D0DVOzy4HRmXtP:-NIha3D0DVOzy4HRmXtQ:by06y18) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/server/session_writer.go#L25)):*
> ```Go
> 	buf    bytes.Buffer
> 	code   int
> }
> ```

add `var _ http.ResponseWriter = &sessionWriter{}` to ensure compile-time checking of interface impl.


<!-- Sent from Reviewable.io -->

2022-12-07 22:05 UTC, Santamaura reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @koorosh, and @zachlite)

___
*[`-- commits` line 7 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIh_RuhBKGeKqVBdNQo):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

format needs fixing here. missing `>` I think. wrap in ``
</blockquote></details>

Thanks for the catch, added.
___
*[`pkg/server/api_v2_auth.go` line 313 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIhwrB57vEeo9NWqykx:-NIia1ZkB-nsAnTa1G58:b-t1m47f) ([raw file](https://github.com/cockroachdb/cockroach/blob/864a0046d79cb42a56d4d638f47688c0efc8a3db/pkg/server/api_v2_auth.go#L313)):*
> Are you sure about the structure of this loop and the code below? Don't you want to first consider the multi-tenant session cookie, and only if that fails look at the base session cookie?

Actually yes we should prioritize `multitenant-session` cookie, changed the loop so this is the case.

> The real question underlying mine is what do you propose the behavior should be if there's both a session and a multi-tenant-session cookie side-by-side in the request. Is that even supported? If not, we need an error; if yes, we need to choose a priority order and stick to it.

I don't imagine this should happen but if for whatever reason it does the newest change now has `multitenant-session` cookie prioritized.
What's interesting is this (resolved) issue indicates it's possible to have multiple `session` cookies: https://github.com/cockroachdb/cockroach/issues/70376. I wonder if we could have a scenario where there is multiple of both cookies.
___
*[`pkg/server/authentication.go` line 721 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIZT8qfCt87L8YPsdfv:-NIibCr17ehM-lnCqGYT:b70hlfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d95554ffc380c634d2f49074c525b2c188cb96/pkg/server/authentication.go#L721)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I think this is inaccurate. I don't see a "map" anywhere in here.
</blockquote></details>

Ah right forgot to update this comment, thanks for catching.
___
*[`pkg/server/authentication.go` line 723 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIZSgZYDINiGH0bSm5n:-NIibI9o4IHNB7qgMQQY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d95554ffc380c634d2f49074c525b2c188cb96/pkg/server/authentication.go#L723)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: fix the comment to match cookie format and use `` to wrap the format.
</blockquote></details>

Done.
___
*[`pkg/server/authentication.go` line 740 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIZSbC78ElA6FjaQxID:-NIibJfK8i-q1YEdwKtn:bv4nmlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d95554ffc380c634d2f49074c525b2c188cb96/pkg/server/authentication.go#L740)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

docstring should have some examples of valid cookies and what gets extracted.
</blockquote></details>

I added an example which should be the main case (other cases should just be an extension of that case).
___
*[`pkg/server/authentication.go` line 744 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIZSORP4kAfjPNLZrU_:-NIibY4NA-44QGEuVDyt:b-9yy7en) ([raw file](https://github.com/cockroachdb/cockroach/blob/66d95554ffc380c634d2f49074c525b2c188cb96/pkg/server/authentication.go#L744)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I thought this would default to system tenant.
</blockquote></details>

Right, done.
___
*[`pkg/server/session_writer.go` line 25 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIha3D0DVOzy4HRmXtP:-NIib_MFC34nohPmuOgO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/server/session_writer.go#L25)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

add `var _ http.ResponseWriter = &sessionWriter{}` to ensure compile-time checking of interface impl.
</blockquote></details>

Done.
___
*[`pkg/server/authentication_test.go` line 505 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIhwN8x0HvzShIDtNRe:-NIibfTmD_MegHrDwu6p:b-50grhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/864a0046d79cb42a56d4d638f47688c0efc8a3db/pkg/server/authentication_test.go#L505)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Why did you need to change this one? Shouldn't the test pass even with your changes?
</blockquote></details>

It needed to change because the test wouldn’t pass since the multi-tenant login doesn’t set `Content-Type` on the response (the response is empty so it shouldn’t matter) but there is a check for the `Content Type` being “application/json” in that http.go helper and will return an error if it isn’t. Same for logout.
___
*[`pkg/server/authentication_test.go` line 578 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIhwQFK3e1N9Yad1wiz:-NIibq1M58RAcMfBJZni:bdak37m) ([raw file](https://github.com/cockroachdb/cockroach/blob/864a0046d79cb42a56d4d638f47688c0efc8a3db/pkg/server/authentication_test.go#L578)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

See above comment for explanation.
___
*[`pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.spec.tsx` line 13 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIgkSMc5kMFQNQ0vnbL:-NIi_Ng60YDIvT4FwQJJ:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0ef4940c3ad04e4890dcb577953752ba7bc6b1/pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.spec.tsx#L13)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

nit. remove `oss/` prefix.
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2022-12-07 22:13 UTC, knz reviewed
> Reviewed 1 of 8 files at r7, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/server/api_v2_auth.go` line 311 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIidINZ-e5KeJ-NHkRo:-NIidINZ-e5KeJ-NHkRp:b-bh8axk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a583b74b377e3b339a31437ef376567901834258/pkg/server/api_v2_auth.go#L311)):*
> ```Go
> 	}
> 
> 	possibleSessions := []string{}
> ```

This loop and the one below are now implemented in two places (here and in authentication.go). Please extract them into a separate function called in both places.
___
*[`pkg/server/authentication.go` line 756 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIidTOQ8LQxdx-wkA-S:-NIidTOQ8LQxdx-wkA-T:b-49vdgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a583b74b377e3b339a31437ef376567901834258/pkg/server/authentication.go#L756)):*
> ```Go
> 		tenantName := findTenantCookieValue(cookies)
> 		if tenantName == "" {
> 			tenantName = catconstants.SystemTenantName
> ```

Please add a reference to the issue where we will make this configurable in a comment around here.
___
*[`pkg/server/authentication_test.go` line 505 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIhwN8x0HvzShIDtNRe:-NIicxuC-apxbjT95AZc:b93w127) ([raw file](https://github.com/cockroachdb/cockroach/blob/864a0046d79cb42a56d4d638f47688c0efc8a3db/pkg/server/authentication_test.go#L505)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

It needed to change because the test wouldn’t pass since the multi-tenant login doesn’t set `Content-Type` on the response (the response is empty so it shouldn’t matter) but there is a check for the `Content Type` being “application/json” in that http.go helper and will return an error if it isn’t. Same for logout.
</blockquote></details>

Could you perhaps make your new endpoint set the content type? That seems the more correct way forward.


<!-- Sent from Reviewable.io -->

2022-12-08 18:08 UTC, Santamaura reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @koorosh, and @zachlite)

___
*[`pkg/server/api_v2_auth.go` line 311 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIidINZ-e5KeJ-NHkRo:-NImuwHlCd8utOG8dA5s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a583b74b377e3b339a31437ef376567901834258/pkg/server/api_v2_auth.go#L311)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This loop and the one below are now implemented in two places (here and in authentication.go). Please extract them into a separate function called in both places.
</blockquote></details>

Done.
___
*[`pkg/server/authentication.go` line 756 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIidTOQ8LQxdx-wkA-S:-NImv86xDA57jPryiKJG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a583b74b377e3b339a31437ef376567901834258/pkg/server/authentication.go#L756)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Please add a reference to the issue where we will make this configurable in a comment around here.
</blockquote></details>

Done.
___
*[`pkg/server/authentication_test.go` line 505 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NIhwN8x0HvzShIDtNRe:-NImvD20CUONbaekwUTz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/864a0046d79cb42a56d4d638f47688c0efc8a3db/pkg/server/authentication_test.go#L505)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Could you perhaps make your new endpoint set the content type? That seems the more correct way forward.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-08 18:13 UTC, knz reviewed
No more comment from me. I do believe we'll need to iterate on the precise handling of cookies (in light of the other issue you've filed) but this does not need to happen now.

> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-:-NImwFnMCxPRnUMlKMHs:b2dznwy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/server/server_controller.go` line 341 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NImw02E94eNlq3K4FgR:-NImw02E94eNlq3K4FgS:b-u9h3ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa331e7683c1ce809ada43b6a6924f1695a2caa/pkg/server/server_controller.go#L341)):*
> ```Go
> 			}
> 			http.SetCookie(w, &cookie)
> 			if r.Header.Get(AcceptHeader) == JSONContentType {
> ```

nit: you could do this just once at the start of the function.


<!-- Sent from Reviewable.io -->

2022-12-08 19:25 UTC, Santamaura reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, @koorosh, and @zachlite)

___
*[`pkg/server/server_controller.go` line 341 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/92694#-NImw02E94eNlq3K4FgR:-NInBO_Q4tT8m1V3P6cu:b74vkgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa331e7683c1ce809ada43b6a6924f1695a2caa/pkg/server/server_controller.go#L341)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: you could do this just once at the start of the function.
</blockquote></details>

Hm, seems like `w.Write([]byte("{}")` removes the response status which will mean the tests where we expect an unauthorized status will fail. So i'll leave it here for now.


<!-- Sent from Reviewable.io -->

2022-12-12 15:34 UTC, Santamaura commented
If there's any further comments let me know, otherwise it would be nice to get a thumbs up as I'd like to merge this before I go OOO next week.

2022-12-12 16:54 UTC, zachlite approved these changes
> Reviewed 2 of 14 files at r1, 1 of 1 files at r4, 1 of 8 files at r7, 4 of 7 files at r8, 1 of 1 files at r9, 1 of 4 files at r10, 1 of 2 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, and @koorosh)



<!-- Sent from Reviewable.io -->

2022-12-12 19:32 UTC, Santamaura commented
bors r+

2022-12-12 19:33 UTC, Santamaura commented
bors r+

2022-12-13 14:56 UTC, Santamaura commented
bors retry

2022-12-13 22:20 UTC, merged