tree: improve type-checking for placeholders with ambiguous type
cockroachdb/cockroach pull request #92834
Opened 2022-12-01 16:36 UTC by rafiss

fixes https://github.com/cockroachdb/cockroach/issues/90364

The key fix is to change the typeCheckSplitExprs function so that it marks _all_
placeholder indexes. This then causes the existing type-checking logic
in typeCheckOverloadedExprs to check all placeholder expressions, rather
than just ones that don't have type hints.

Release note (bug fix): Prepared statements that use type hints can now succeed type-checking in more cases when the placeholder type is ambiguous.

2022-12-01 16:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/92834)
<!-- Reviewable:end -->

2022-12-02 18:01 UTC, jordanlewis requested changes
I'm surprised there are no changed test cases. Can you look to see if there are some new test cases to add in `type_check_internal_test.go` or `type_check_test.go`? I think it would be nice to have some more targeted tests than just the big end-to-end one you added.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-:-NIIzZ3sDpQErs15Gzoz:b-wkli9m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/sem/tree/type_check.go` line 1699 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIyREK0oK3gwtJvfHN:-NIIyREK0oK3gwtJvfHO:be2y11b) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L1699)):*
> ```Go
> 	} else if ok {
> 		typ = typ.WithoutTypeModifiers()
> 		if !desired.Equivalent(typ) || (typ.IsAmbiguous() && !desired.IsAmbiguous()) {
> ```

I think the comment is now inaccurate, can you add an explanation of the second case? And/or an example?
___
*[`pkg/sql/sem/tree/type_check.go` line 2559 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIz6Ix9_c3yRq1naEa:-NIIz6Ix9_c3yRq1naEb:b-gtsrwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L2559)):*
> ```Go
> ) (constIdxs util.FastIntSet, placeholderIdxs util.FastIntSet, resolvableIdxs util.FastIntSet) {
> 	for i, expr := range exprs {
> 		if isConstant(expr) {
> ```

why do we need to StripParens below but not for the isConstant case?
___
*[`pkg/sql/sem/tree/type_check.go` line 2565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIzDgd3tRKO4cLvhO8:-NIIzDgd3tRKO4cLvhO9:b-ebq177) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L2565)):*
> ```Go
> 				placeholderIdxs.Add(i)
> 			}
> 			if !semaCtx.isUnresolvedPlaceholder(expr) {
> ```

It seems like now we can have an index in more than one group. That seems suspect - it means (I think) that the type checker can run over an index more than once. Was this an intentional change? Does the behavior now depend on the order in which we do the resolution over each index group?


<!-- Sent from Reviewable.io -->

2022-12-02 18:57 UTC, rafiss reviewed
i've added a smaller test

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-:-NIJBvVP3bQFcClo8aQd:bed2n4b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @jordanlewis)

___
*[`pkg/sql/sem/tree/type_check.go` line 1699 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIyREK0oK3gwtJvfHN:-NIJ07OR1VaLOztqAOpI:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L1699)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think the comment is now inaccurate, can you add an explanation of the second case? And/or an example?
</blockquote></details>

done
___
*[`pkg/sql/sem/tree/type_check.go` line 2559 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIz6Ix9_c3yRq1naEa:-NIJ-sfG7JzC1AdnfyIw:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L2559)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

why do we need to StripParens below but not for the isConstant case?
</blockquote></details>

done
___
*[`pkg/sql/sem/tree/type_check.go` line 2565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIzDgd3tRKO4cLvhO8:-NIJ-tsC16d0YVeYAcyF:b-9wvyp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L2565)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It seems like now we can have an index in more than one group. That seems suspect - it means (I think) that the type checker can run over an index more than once. Was this an intentional change? Does the behavior now depend on the order in which we do the resolution over each index group?
</blockquote></details>

this was intentional - the comment on this function was modified to describe the new behavior, and i've updated the commit message to explain why this was the key part of the fix. also, this typeCheckSplitExprs function only has two usages


<!-- Sent from Reviewable.io -->

2022-12-02 19:23 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @jordanlewis)

___
*[`pkg/sql/sem/tree/type_check.go` line 2559 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIz6Ix9_c3yRq1naEa:-NIJHq4n8LiM2E5kCvWM:bpaj7j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L2559)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

done
</blockquote></details>

added a comment to explain why


<!-- Sent from Reviewable.io -->

2022-12-02 20:04 UTC, jordanlewis reviewed
Tests LGTM, in general LGTM except for the open thread about the duplicate type check calls.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-:-NIJRE4wD__qfCtwgL-v:b-2j3vd4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/sem/tree/type_check.go` line 2565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIzDgd3tRKO4cLvhO8:-NIJQmIPDkVA7RsBbJEj:b-56wj0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L2565)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this was intentional - the comment on this function was modified to describe the new behavior, and i've updated the commit message to explain why this was the key part of the fix. also, this typeCheckSplitExprs function only has two usages
</blockquote></details>

My comment still holds though - look at the usage in `typeCheckSameTypedExprs` for example. This means we'll type check the given index twice. That can't be a good thing right?

Is there a way to avoid adding an index to both places? I guess I'm sort of arguing on principle, but it does feel messy and wrong to force these things to be type checked twice, unless we really have a good reason for it (and if we do that should definitely be explained in the comment).


<!-- Sent from Reviewable.io -->

2022-12-02 20:33 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @jordanlewis)

___
*[`pkg/sql/sem/tree/type_check.go` line 2565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIzDgd3tRKO4cLvhO8:-NIJWSp40h85oWyL9Fuz:b-glq4mj) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L2565)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

My comment still holds though - look at the usage in `typeCheckSameTypedExprs` for example. This means we'll type check the given index twice. That can't be a good thing right?

Is there a way to avoid adding an index to both places? I guess I'm sort of arguing on principle, but it does feel messy and wrong to force these things to be type checked twice, unless we really have a good reason for it (and if we do that should definitely be explained in the comment).
</blockquote></details>

i feel the opposite - it seems wrong to _avoid_ type-checking a placeholder (since we avoid calling `checkReturnPlaceholdersAtIdx` for that placeholder) just because a type-hint was provided by the user.

why is it wrong for something to be type-checked twice? the type-checker has logic for type-checking placeholders as well as resolvable expressions. if something is _both_ a placeholder and a resolvable expression, then it feels more correct to say that this expression must pass both type-checking heuristics.

are you saying that the reason in the commit message is not good enough?


<!-- Sent from Reviewable.io -->

2022-12-02 20:58 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/sem/tree/type_check.go` line 2565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIzDgd3tRKO4cLvhO8:-NIJ_JyZAxj2MemQB7X7:b-wzl8dj) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L2565)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i feel the opposite - it seems wrong to _avoid_ type-checking a placeholder (since we avoid calling `checkReturnPlaceholdersAtIdx` for that placeholder) just because a type-hint was provided by the user.

why is it wrong for something to be type-checked twice? the type-checker has logic for type-checking placeholders as well as resolvable expressions. if something is _both_ a placeholder and a resolvable expression, then it feels more correct to say that this expression must pass both type-checking heuristics.

are you saying that the reason in the commit message is not good enough?
</blockquote></details>

I hadn't read the reason in the commit message, and it does make sense to me as much as I'm able to understand it. We did always include every index in one of the returned sets, right?

I guess I'm just nervous that we're introducing a bit more fragility into this already fragile code by potentially calling TypeCheck more than once (which might mutate expressions as well as just check them).

I don't really have a strong reason to say no to this change though... it's just a feeling that calling TypeCheck more than once is inefficient or inelegant. That will happen if we found a placeholder that already has a type. In what situation does a placeholder already have a resolved type? That's the case I'm wondering about.

Another complaint I have (sorry) is that it's not possible to *not* add an index to any set, since the second function always returns false if an expression is not a placeholder, but that's not obvious from the control flow... and I do think it's important that this function always categorize an index into one of the sets.

Looking at the implementation of `isUnresolvedPlaceholder`, I notice that it does the same thing that we do above - strip parens and check for *Placeholder. My concrete suggestion then is to base the second arm of the if on `p.Type` rather than re-calling `isUnresolvedPlaceholder`. 


<!-- Sent from Reviewable.io -->

2022-12-02 20:58 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/sem/tree/type_check.go` line 2565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIzDgd3tRKO4cLvhO8:-NIJcXBTEWeRLOhsTY-V:b-ewvobl) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L2565)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I hadn't read the reason in the commit message, and it does make sense to me as much as I'm able to understand it. We did always include every index in one of the returned sets, right?

I guess I'm just nervous that we're introducing a bit more fragility into this already fragile code by potentially calling TypeCheck more than once (which might mutate expressions as well as just check them).

I don't really have a strong reason to say no to this change though... it's just a feeling that calling TypeCheck more than once is inefficient or inelegant. That will happen if we found a placeholder that already has a type. In what situation does a placeholder already have a resolved type? That's the case I'm wondering about.

Another complaint I have (sorry) is that it's not possible to *not* add an index to any set, since the second function always returns false if an expression is not a placeholder, but that's not obvious from the control flow... and I do think it's important that this function always categorize an index into one of the sets.

Looking at the implementation of `isUnresolvedPlaceholder`, I notice that it does the same thing that we do above - strip parens and check for *Placeholder. My concrete suggestion then is to base the second arm of the if on `p.Type` rather than re-calling `isUnresolvedPlaceholder`. 
</blockquote></details>

It might be easier for us to chat about this offline, happy to do that :)


<!-- Sent from Reviewable.io -->

2022-12-02 21:37 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @jordanlewis)

___
*[`pkg/sql/sem/tree/type_check.go` line 2565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIIzDgd3tRKO4cLvhO8:-NIJlSUN8vAElDqsGtJI:b-d19fxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/25cbd8e7a85259e65705481810a8a05c2cb1e903/pkg/sql/sem/tree/type_check.go#L2565)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It might be easier for us to chat about this offline, happy to do that :)
</blockquote></details>

sure, let's chat offline


<!-- Sent from Reviewable.io -->

2022-12-07 16:36 UTC, jordanlewis approved these changes
Woohoo! Thanks for pushing on this, it looks a lot cleaner now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-:-NIhRP5J8QNYdnMR9NN-:bcm6z8v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/sem/tree/overload.go` line 1208 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIhR3aY1sRiInS-06nm:-NIhR3aY1sRiInS-06nn:bs35gk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ead8e62a39b3fa68c4a64c0eb504cf78b4df53/pkg/sql/sem/tree/overload.go#L1208)):*
> ```Go
> 		if errorOnPlaceholders {
> 			if _, err := s.exprs[i].TypeCheck(ctx, semaCtx, types.Any); err != nil {
> 				return err
> ```

The old behavior seems fairly broken here... wut


<!-- Sent from Reviewable.io -->

2022-12-07 16:36 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @jordanlewis)

___
*[`pkg/sql/sem/tree/overload.go` line 1208 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-NIhR3aY1sRiInS-06nm:-NIhR_KaCn08OmySiXTz:b-r35j0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ead8e62a39b3fa68c4a64c0eb504cf78b4df53/pkg/sql/sem/tree/overload.go#L1208)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

The old behavior seems fairly broken here... wut
</blockquote></details>

yeah no idea how this didn't cause issues previously


<!-- Sent from Reviewable.io -->

2022-12-07 16:37 UTC, rafiss reviewed
bors r=jordanlewis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92834#-:-NIhRfz4CsVU_gK-3NIf:bkhbmek)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @jordanlewis)



<!-- Sent from Reviewable.io -->

2022-12-07 18:53 UTC, merged