kvserver: add average cpu nanos per replica
cockroachdb/cockroach pull request #92858
Opened 2022-12-01 21:28 UTC by kvoli

This patch adds partial accounting for the time spent on processing requests, for a specific replica. The time spent is recorded in `ReplicaStats` and allows for observing the aggregate cpu time spent on replicas via an exported metric `rebalancing.cpunanospersecond`.

Release note: None

2022-12-01 21:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/92858)
<!-- Reviewable:end -->

2022-12-02 09:27 UTC, kvoli commented
Will link the issue. The extended ci appears like a flake.

2022-12-02 15:30 UTC, andrewbaptist requested changes, later dismissed
Is there a reason you didn't add timing to `store_raft.processRequestQueue`? It seems like some work happens there as well. 

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-:-NIILqNsEiYbFzE9DxbP:b-tcvv3l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @kvoli, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/metrics.go` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIIHJsR-_f0mtgnL1nj:-NIIHJsR-_f0mtgnL1nk:bnanfak) ([raw file](https://github.com/cockroachdb/cockroach/blob/7588441a58a5bc7cadbbd952701f50aee6d1de0b/pkg/kv/kvserver/metrics.go#L357)):*
> ```Go
> 		Unit:        metric.Unit_BYTES,
> 	}
> 	metaAverageNanosPerSecond = metric.Metadata{
> ```

Nit: I don't really like this variable name (nanos/second is always 1 billion). Maybe something like metaNanosProcessingPerSecond or metaNanosRunningPerSecond or metaCPUNanosPerSecond.
___
*[`pkg/kv/kvserver/replica_load.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIII--IEw88CWNpSEAz:-NIII--IEw88CWNpSEB-:bsd3z5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7588441a58a5bc7cadbbd952701f50aee6d1de0b/pkg/kv/kvserver/replica_load.go#L27)):*
> ```Go
> 	writeBytes    *replicastats.ReplicaStats
> 	readBytes     *replicastats.ReplicaStats
> 	nanos         *replicastats.ReplicaStats
> ```

Nit: Don't necessarily change in this PR, but the fact that the same operations need to be repeated in 4 different places (construction, split counts, merge counts, and reset) for 6 different stats feels a little like a code smell. Maybe structure these into an array so they can just be looped over once?
___
*[`pkg/kv/kvserver/replica_metrics.go` line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIIIgAGDWHMA-gjeXgH:-NIIIgAGDWHMA-gjeXgI:b-ly5jkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7588441a58a5bc7cadbbd952701f50aee6d1de0b/pkg/kv/kvserver/replica_metrics.go#L339)):*
> ```Go
> func (r *Replica) RequestLocality() *replicastats.RatedSummary {
> 	return r.loadStats.batchRequests.SnapshotRatedSummary()
> }
> ```

What is this method for - it doesn't seem to be called or used anywhere. Should this be in a different PR?
___
*[`pkg/kv/kvserver/store.go` line 3215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIIJgUW-LC6ipvdLAgB:-NIIJgUW-LC6ipvdLAgC:b-1mlxw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7588441a58a5bc7cadbbd952701f50aee6d1de0b/pkg/kv/kvserver/store.go#L3215)):*
> ```Go
> 		averageReadBytesPerSecond     float64
> 		averageWriteBytesPerSecond    float64
> 		averageNanosPerSecond         float64
> ```

Nit: Similar naming issue as above.


<!-- Sent from Reviewable.io -->

2022-12-05 08:40 UTC, kvoli reviewed
TYFTR - replied to comments. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-:-NIWROY_E29-zzI79BB2:b-1bziqd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/metrics.go` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIIHJsR-_f0mtgnL1nj:-NIWPrsZ1BHuFr517SCC:b-m8p4jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7588441a58a5bc7cadbbd952701f50aee6d1de0b/pkg/kv/kvserver/metrics.go#L357)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Nit: I don't really like this variable name (nanos/second is always 1 billion). Maybe something like metaNanosProcessingPerSecond or metaNanosRunningPerSecond or metaCPUNanosPerSecond.
</blockquote></details>

Updated to be consistently `...CPUNanosPerSecond` across the patch.
___
*[`pkg/kv/kvserver/replica_load.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIII--IEw88CWNpSEAz:-NIWQ83GB3fPwVtBvDM3:b-1mb2rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7588441a58a5bc7cadbbd952701f50aee6d1de0b/pkg/kv/kvserver/replica_load.go#L27)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Nit: Don't necessarily change in this PR, but the fact that the same operations need to be repeated in 4 different places (construction, split counts, merge counts, and reset) for 6 different stats feels a little like a code smell. Maybe structure these into an array so they can just be looped over once?
</blockquote></details>

I agree that this structure isn't ideal. Overall this area needs a bit of a refactor.  A similar vector structure to #91593 is the likely outcome eventually.  

This is tracked in #87187.
___
*[`pkg/kv/kvserver/replica_metrics.go` line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIIIgAGDWHMA-gjeXgH:-NIWQeJU3CmRv1409kZi:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7588441a58a5bc7cadbbd952701f50aee6d1de0b/pkg/kv/kvserver/replica_metrics.go#L339)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

What is this method for - it doesn't seem to be called or used anywhere. Should this be in a different PR?
</blockquote></details>

Removed.
___
*[`pkg/kv/kvserver/store.go` line 3215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIIJgUW-LC6ipvdLAgB:-NIWQn_W49K3SseiXyD1:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/7588441a58a5bc7cadbbd952701f50aee6d1de0b/pkg/kv/kvserver/store.go#L3215)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Nit: Similar naming issue as above.
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2022-12-05 09:20 UTC, kvoli reviewed
> Is there a reason you didn't add timing to store_raft.processRequestQueue? It seems like some work happens there as well.

Initially it wasn't included simply because we didn't include it in the cputime prototype. I've added it, good suggestion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-:-NIW_WXBAC9u3D0SFz3h:bmysfrm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2022-12-06 16:06 UTC, nvanbenschoten requested changes
It's cool to see this.

What is the plan for tracking and balancing on load in cases where `grunning` is disabled?

Also, do we intend to split the CPU attribution across work that a replica performs in the leaseholder role vs. work that it performs in the follower replica role? Now that we can attribute work with precision, it seems valuable to measure exactly the amount of work a lease transfer can shed, and then also exactly the amount of work a replica rebalance can shed.

> Reviewed 4 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-:-NIc9PdrDGtjTng7s2GW:bw7i94i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @kvoli)

___
*[`pkg/kv/kvserver/store_raft.go` line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc7TI18orVR2y4Z-Dp:-NIc7TI18orVR2y4Z-Dq:bvtgjdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/kv/kvserver/store_raft.go#L353)):*
> ```Go
> 	// Record the CPU time processing the request for this replica. This is
> 	// recorded regardless of errors that are encountered.
> 	grunningStart := grunning.Time()
> ```

We have this same logic in a number of places. Consider pushing more of it into a library so that it's easier to use (harder to misuse) and less redundant.

For instance, we use the following pattern elsewhere. As long as it doesn't heap allocate (please check if you go with it), it feels like an improvement:
```go
func (r *Replica) MeasureNanosRunning() func() {
	start := grunning.Time()
	return func() {
		end :=  grunning.Time()
		dur := grunning.Difference(start, end).Nanoseconds()
		r.loadStats.cpuNanos.RecordCount(float64(dur), 0 /* nodeID */)
	}
}

...

// to use
defer r.MeasureNanosRunning()()
```
___
*[`pkg/kv/kvserver/store_raft.go` line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc8qqN-HCFmq4dLiKs:-NIc8qqN-HCFmq4dLiKt:b732smv) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/kv/kvserver/store_raft.go#L643)):*
> ```Go
> 	stats, err := r.handleRaftReady(ctx, noSnap)
> 	maybeFatalOnRaftReadyErr(ctx, err)
> 	grunningStart := grunning.Time()
> ```

This is starting the timer after the `handleRaftReady` call, so we're missing most of the CPU time inside of Raft. Fixing this should improve the accuracy of the CPU attribution.
___
*[`pkg/kv/kvserver/store_send.go` line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc9AJe5u8czSVPjNmb:-NIc9AJe5u8czSVPjNmc:bqfombb) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/kv/kvserver/store_send.go#L173)):*
> ```Go
> 	startGrunning := grunning.Time()
> 	defer func() {
> 		repl, err := s.GetReplica(ba.RangeID)
> ```

Can we find a way to record this without passing back through the `replicasByRangeID` sync map? We have the `Replica` down below and it's probably safe to assume that all of the work was done by the last Replica touched in that loop.
___
*[`pkg/ts/catalog/chart_catalog.go` line 689 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc7dJi29s8FXTpl_jk:-NIc7dJi29s8FXTpl_jl:b6i8m5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/ts/catalog/chart_catalog.go#L689)):*
> ```Go
> 			},
> 			{
> ```

nit: stray line


<!-- Sent from Reviewable.io -->

2022-12-08 03:34 UTC, kvoli reviewed
> What is the plan for tracking and balancing on load in cases where grunning is disabled?

tracking: It will record 0.
balancing on load: call to https://github.com/kvoli/cockroach/blob/bbc219e2b6863aa82b27751deba67b6aea0d27b8/pkg/util/grunning/grunning.go#L43-L43 and set the cluster setting to QPS rebalancing or "legacy" in that case, if `Supported` returns false.

> do we intend to split the CPU attribution across work that a replica performs in the leaseholder role vs. work that it performs in the follower replica role? 

That is the intention. I was concerned on the memory usage of adding two different replica stats objects at once. They need to be refactored but I was intending on doing that after merging https://github.com/cockroachdb/cockroach/pull/91593. I don't see why that should block this so I've added both.

I have opted not to include two, separate metrics yet. Keeping the same metric as before.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-:-NIjXOfQ3biJ1RcQkuYy:b-tjhghu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/store_raft.go` line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc7TI18orVR2y4Z-Dp:-NIjRO9f6utr2QZihcS3:b-78f3tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/kv/kvserver/store_raft.go#L353)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We have this same logic in a number of places. Consider pushing more of it into a library so that it's easier to use (harder to misuse) and less redundant.

For instance, we use the following pattern elsewhere. As long as it doesn't heap allocate (please check if you go with it), it feels like an improvement:
```go
func (r *Replica) MeasureNanosRunning() func() {
	start := grunning.Time()
	return func() {
		end :=  grunning.Time()
		dur := grunning.Difference(start, end).Nanoseconds()
		r.loadStats.cpuNanos.RecordCount(float64(dur), 0 /* nodeID */)
	}
}

...

// to use
defer r.MeasureNanosRunning()()
```
</blockquote></details>

Adopted this method instead.
___
*[`pkg/kv/kvserver/store_raft.go` line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc8qqN-HCFmq4dLiKs:-NIjRLWV47Eb5u0pEKKS:b-eu89v) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/kv/kvserver/store_raft.go#L643)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is starting the timer after the `handleRaftReady` call, so we're missing most of the CPU time inside of Raft. Fixing this should improve the accuracy of the CPU attribution.
</blockquote></details>

That's an error. Updated to be above.
___
*[`pkg/ts/catalog/chart_catalog.go` line 689 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc7dJi29s8FXTpl_jk:-NIj_U8y-p7UVPn4Z652:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/ts/catalog/chart_catalog.go#L689)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: stray line
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/store_send.go` line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc9AJe5u8czSVPjNmb:-NIjQpQH56Ys1bA9XD9X:bdtyw3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/kv/kvserver/store_send.go#L173)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we find a way to record this without passing back through the `replicasByRangeID` sync map? We have the `Replica` down below and it's probably safe to assume that all of the work was done by the last Replica touched in that loop.
</blockquote></details>

Moved to `repl.SendWithWriteBytes()` for now. 


<!-- Sent from Reviewable.io -->

2022-12-08 07:07 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92858)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/store_raft.go` line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc7TI18orVR2y4Z-Dp:-NIkYddp9tFAjFgQ_8SY:b-na7iyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/kv/kvserver/store_raft.go#L353)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Adopted this method instead.
</blockquote></details>

It looks like it does heap alloc w/ that approach. 

![image.png](https://files.reviewableusercontent.io/images/reviewable/39606633/fFPRrY5xqez6FWOqgQxAxOCD/image.png)


Albeit a relatively tiny amount (kv max-rate=1k running).


<!-- Sent from Reviewable.io -->

2022-12-08 23:43 UTC, nvanbenschoten reviewed
> Reviewed 7 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92858)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @kvoli)

___
*[`pkg/kv/kvserver/store_raft.go` line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc7TI18orVR2y4Z-Dp:-NIo6-RtDnYGMnRN98hf:b8esf4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/kv/kvserver/store_raft.go#L353)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It looks like it does heap alloc w/ that approach. 

![image.png](https://files.reviewableusercontent.io/images/reviewable/39606633/fFPRrY5xqez6FWOqgQxAxOCD/image.png)


Albeit a relatively tiny amount (kv max-rate=1k running).
</blockquote></details>

I took a look at this and was also unable to find a way to avoid the heap allocation. It's unfortunate, but the heap allocation is probably not worth paying for. A slightly worse version ergonomically that avoids the closure allocation is:
```go
// MeasureReqCPUNanos measures the cpu time spent on this replica processing
// requests.
func (r *Replica) MeasureReqCPUNanos(start time.Duration) {
	r.measureNanosRunning(start, func(dur float64) {
		r.loadStats.reqCPUNanos.RecordCount(dur, 0 /* nodeID */)
	})
}

// measureNanosRunning measures the difference in cpu time from when this
// method is called, to when the returned function is called. This difference
// is recorded against the replica's cpu time attribution.
func (r *Replica) measureNanosRunning(start time.Duration, f func(float64)) {
	end := grunning.Time()
	dur := grunning.Difference(start, end).Nanoseconds()
	f(float64(dur))
}

...

func (r *Replica) SendWithWriteBytes(
	ctx context.Context, ba *roachpb.BatchRequest,
) (*roachpb.BatchResponse, *kvadmission.StoreWriteBytes, *roachpb.Error) {
   
    ...

    defer r.MeasureReqCPUNanos(grunning.Time())

    ...

}
```
Consider switching to an approach along these lines.
___
*[`pkg/kv/kvserver/store_send.go` line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc9AJe5u8czSVPjNmb:-NIo6cH77aNLTDbw7Jq2:b-zgyu97) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/kv/kvserver/store_send.go#L173)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Moved to `repl.SendWithWriteBytes()` for now. 
</blockquote></details>

That seems like a better place for it. Thanks.


<!-- Sent from Reviewable.io -->

2022-12-09 05:37 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92858)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @irfansharif, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/store_raft.go` line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-NIc7TI18orVR2y4Z-Dp:-NIpNhD35Xy735zFxsRn:bl4afc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/20632972ff4b55216f1f2e185337945d1794e9fc/pkg/kv/kvserver/store_raft.go#L353)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I took a look at this and was also unable to find a way to avoid the heap allocation. It's unfortunate, but the heap allocation is probably not worth paying for. A slightly worse version ergonomically that avoids the closure allocation is:
```go
// MeasureReqCPUNanos measures the cpu time spent on this replica processing
// requests.
func (r *Replica) MeasureReqCPUNanos(start time.Duration) {
	r.measureNanosRunning(start, func(dur float64) {
		r.loadStats.reqCPUNanos.RecordCount(dur, 0 /* nodeID */)
	})
}

// measureNanosRunning measures the difference in cpu time from when this
// method is called, to when the returned function is called. This difference
// is recorded against the replica's cpu time attribution.
func (r *Replica) measureNanosRunning(start time.Duration, f func(float64)) {
	end := grunning.Time()
	dur := grunning.Difference(start, end).Nanoseconds()
	f(float64(dur))
}

...

func (r *Replica) SendWithWriteBytes(
	ctx context.Context, ba *roachpb.BatchRequest,
) (*roachpb.BatchResponse, *kvadmission.StoreWriteBytes, *roachpb.Error) {
   
    ...

    defer r.MeasureReqCPUNanos(grunning.Time())

    ...

}
```
Consider switching to an approach along these lines.
</blockquote></details>

looks good, adopted.


<!-- Sent from Reviewable.io -->

2022-12-10 22:38 UTC, nvb approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92858#-:-NIyB6lT6Tx4aJBwr449:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @irfansharif)



<!-- Sent from Reviewable.io -->

2022-12-13 14:35 UTC, kvoli commented
bors r=nvanbenschoten

2022-12-14 00:00 UTC, merged