Add support for collecting partial statistics automatically
cockroachdb/cockroach pull request #93067
Opened 2022-12-05 19:38 UTC by faizaanmadhani

This is a draft PR, and currently is incomplete

2022-12-05 19:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/93067)
<!-- Reviewable:end -->

2024-08-16 00:23 UTC, michae2 requested changes
Thanks for dusting this off, @Uzair5162! (And retroactive thanks, @faizaanmadhani! Your work is not forgotten! :slightly_smiling_face:) It's looking pretty good. I'm still reading, but have some initial comments.

> Reviewed 10 of 31 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-:-O4NZ3ZU6rh_-j4Pl9VC:be441vr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, and @faizaanmadhani)

___
*[`pkg/sql/create_stats.go` line 222 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NSBZA1gcB_kyh71ME:-O4NSBZA1gcB_kyh71MF:b-mn2roq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/create_stats.go#L222)):*
> ```Go
> 	}
> 
> 	if n.Options.UsingExtremes && !n.p.SessionData().EnableCreateStatsUsingExtremes && n.Name.String() != jobspb.AutoPartialStatsName {
> ```

I think the check for `n.Options.UsingExtremes` here should be enough. We shouldn't need to check the name.
___
*[`pkg/sql/create_stats.go` line 741 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NSywv1oNnzxI-fMfp:-O4NSywv1oNnzxI-fMfq:btmxlhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/create_stats.go#L741)):*
> ```Go
> 					len(details.ColumnStats), i,
> 				); err != nil {
> 					retErr = errors.CombineErrors(retErr, err)
> ```

Is the idea that we should make a best-effort attempt to collect the rest of the partial stats even if one fails?

I think this might not interact correctly with cancellation of the CREATE STATISTICS: if the error is ContextCanceled, we should fail right away. (That reminds me: it would probably be a good idea to check `ctx.Err()` at the top of this loop.)

I'm also not sure this is going to interact correctly with the single transaction within which all of these distsql invocations are running. The transaction could be dead, for example, in which case all subsequent distsql invocations will fail, and we'll retry the entire thing anyway.
___
*[`pkg/sql/catalog/catpb/catalog.go` line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NCPB76Rl4lyjTG7qu:-O4NCPB76Rl4lyjTG7qv:b-2bq175) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/catalog/catpb/catalog.go#L73)):*
> ```Go
> 	// AutoPartialStatsEnabledTableSettingName is the name of the automatic
> 	// partial stats collection enabled table setting.
> 	AutoPartialStatsEnabledTableSettingName = "sql_partial_stats_automatic_collection_enabled"
> ```

To be consistent with the other per-table settings, I think we should make these names the same as the matching cluster setting names but with periods replaced with underscores.
___
*[`pkg/sql/stats/automatic_stats.go` line 144 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NYrux8aMM45YvLys5:-O4NYjVWDUQIMoMg8Xf-:b-bu7q3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L144)):*
> ```Go
> 	catpb.AutoPartialStatsMinStaleSettingName,
> 	"target minimum number of stale rows per table that will trigger a partial statistics refresh",
> 	500,
> ```

It might be worth making this smaller than 500? 100?
___
*[`pkg/sql/stats/automatic_stats.go` line 392 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NGd491PXKEesP3PDE:-O4NGd491PXKEesP3PDF:b7kmfa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L392)):*
> ```Go
> 	if desc == nil {
> 		// If the descriptor could not be accessed, defer to the cluster setting.
> 		return AutomaticPartialStatisticsClusterMode.Get(&r.st.SV)
> ```

I think we should require both `sql.stats.automatic_partial_collection.enabled` and `sql.stats.automatic_collection.enabled` to be true in order to automatically collect partial stats, because (a) partial stats don't work without full stats anyway, and (b) that will preserve the behavior of `SET CLUSTER SETTING sql.stats.automatic_collection.enabled = off;` disabling all automatic stats collection, which is relied upon by many tests (and customers).

And same with table settings. So the precedence hierarchy would be:
1. per-table auto full
2. per-table auto partial
3. cluster auto full
4. cluster auto partial

In other words, I think `sql.stats.automatic_partial_collection.enabled` should only describe what happens when automatic stats are already enabled.
___
*[`pkg/sql/stats/automatic_stats.go` line 986 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NQsSG0HLY9Z9x8Pkn:-O4NQsSG0HLY9Z9x8Pko:bscciu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L986)):*
> ```Go
> 	if isPartial {
> 		stmt = fmt.Sprintf(
> 			"CREATE STATISTICS %s FROM [%d] WITH OPTIONS THROTTLING %g AS OF SYSTEM TIME '-%s' USING EXTREMES",
> ```

nit: Instead of duplicating the call to `Sprintf` it might be nice to add %s to the end of the original format string which takes `" USING EXTREMES"` if `isPartial` else `""`.


<!-- Sent from Reviewable.io -->

2024-08-16 23:06 UTC, Uzair5162 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93067)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, and @michae2)

___
*[`pkg/sql/create_stats.go` line 222 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NSBZA1gcB_kyh71ME:-O4RjE5u3Lpk6gfBTYGt:bmyq724) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/create_stats.go#L222)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I think the check for `n.Options.UsingExtremes` here should be enough. We shouldn't need to check the name.
</blockquote></details>

Done. Does this work because we use session settings' default values in job runs?
___
*[`pkg/sql/create_stats.go` line 741 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NSywv1oNnzxI-fMfp:-O4RmfIe5oF7lvj3Phmb:b3jayi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/create_stats.go#L741)):*
> Is the idea that we should make a best-effort attempt to collect the rest of the partial stats even if one fails?

That was my thinking, yeah. Partial stats will fail if prior full stats don't exist on the column and I didn't want that to prevent stat collections on other columns that have existing stats. Now that I think about it though, this is unlikely to happen for auto partial stats since the default column set for these collections is a subset of the default auto full stats column set, so this is probably unnecessary.
___
*[`pkg/sql/catalog/catpb/catalog.go` line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NCPB76Rl4lyjTG7qu:-O4SBvBU6Jr8PWxwYjyF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/catalog/catpb/catalog.go#L73)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

To be consistent with the other per-table settings, I think we should make these names the same as the matching cluster setting names but with periods replaced with underscores.
</blockquote></details>

Done.
___
*[`pkg/sql/stats/automatic_stats.go` line 144 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NYrux8aMM45YvLys5:-O4SC8hwCucZtXHFDvPp:b-pkexrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L144)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

It might be worth making this smaller than 500? 100?
</blockquote></details>

Done, I agree!
___
*[`pkg/sql/stats/automatic_stats.go` line 392 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NGd491PXKEesP3PDE:-O4SDHCq3Nv9R2yjQkPd:b-bm5q9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L392)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I think we should require both `sql.stats.automatic_partial_collection.enabled` and `sql.stats.automatic_collection.enabled` to be true in order to automatically collect partial stats, because (a) partial stats don't work without full stats anyway, and (b) that will preserve the behavior of `SET CLUSTER SETTING sql.stats.automatic_collection.enabled = off;` disabling all automatic stats collection, which is relied upon by many tests (and customers).

And same with table settings. So the precedence hierarchy would be:
1. per-table auto full
2. per-table auto partial
3. cluster auto full
4. cluster auto partial

In other words, I think `sql.stats.automatic_partial_collection.enabled` should only describe what happens when automatic stats are already enabled.
</blockquote></details>

This was my thinking as well and I think this is the current behavior. We check if auto full stats are enabled in [automatic_stats.go#L793](https://github.com/faizaanmadhani/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L793) after mutations, and early return if they're not (either (`sql_stats_automatic_partial_collection_enabled` table setting is unset and the `sql.stats.automatic_partial_collection.enabled` cluster setting is false) or (`sql_stats_automatic_partial_collection_enabled` table setting is false)).

We also check if auto full stats are enabled again before calling `maybeRefreshStats()` (which has the auto partial stat logic) in [automatic_stats.go#L592](https://github.com/faizaanmadhani/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L592) in case settings change between the mutation notification and the refresher picking it up.

The logic test in [distsql_automatic_partial_stats#L5-L26](https://github.com/faizaanmadhani/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats#L5-L26) should confirm this where auto partial stats are enable for the table but auto full stats are disabled for the cluster, so auto partial stats are not collected.

Do you think it would be a good idea to add another check for auto full stats being enabled in [autoPartialStatsEnabled()](https://github.com/faizaanmadhani/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L389) to make this more clear?
___
*[`pkg/sql/stats/automatic_stats.go` line 986 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NQsSG0HLY9Z9x8Pkn:-O4SQK4u5F5dN1lFPhk2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L986)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Instead of duplicating the call to `Sprintf` it might be nice to add %s to the end of the original format string which takes `" USING EXTREMES"` if `isPartial` else `""`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-20 00:24 UTC, michae2 requested changes
Awesome work! This is very close. Main thing I'm worried about is the error handling in that loop in `makeJobRecord`.

> Reviewed 15 of 31 files at r3, 1 of 5 files at r5, 5 of 6 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-:-O4h9bCD4KGy26Qk8Cl7:b-a45zv4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, @faizaanmadhani, and @Uzair5162)

___
*[`-- commits` line 9 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gMBs-9XkJM9OFg0mT):*
nit: looks like the per-table setting names need to be updated here

(Also, you might consider moving the details about the settings to the release note.)
___
*[`-- commits` line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4h6ZYR982m5JFCT22j):*
@rytaft do you have any objection to multiple automatic partial stats collections at once? It seems like a good way to start trying out multiple concurrent stats jobs?

I remember we discussed this before in:
- https://github.com/cockroachdb/cockroach/pull/118983
- some slack conversations I can't seem to find now
___
*[`pkg/sql/create_stats.go` line 222 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NSBZA1gcB_kyh71ME:-O4gY1atEvfDYbBbvKHo:b3ga6k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/create_stats.go#L222)):*
<details><summary><i>Previously, Uzair5162 (Uzair Ahmad) wrote…</i></summary><blockquote>

Done. Does this work because we use session settings' default values in job runs?
</blockquote></details>

For auto stats, these session variables come from the internal executor when [the stats.Refresher runs CREATE STATISTICS](https://github.com/cockroachdb/cockroach/blob/f5e3b37dced49ed37db1957e2e6abfb8412f8699/pkg/sql/stats/automatic_stats.go#L866-L871). We have a way to [set session variables for the internal executor](https://github.com/cockroachdb/cockroach/pull/122855), too, so I think it would be nice if CREATE STATISTICS respected the `enable_create_stats_using_extremes` session variable regardless of whether it was run manually or automatically.

In other words, I think `SET CLUSTER SETTING sql.internal_executor.session_overrides = 'enable_create_stats_using_extremes=off';` should prevent automatic collection of partial stats (even if `sql.stats.automatic_partial_collection.enabled` is on).
___
*[`pkg/sql/create_stats.go` line 741 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NSywv1oNnzxI-fMfp:-O4gg9Rn40lJTBo0akT6:b-p5dr3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/create_stats.go#L741)):*
> Partial stats will fail if prior full stats don't exist on the column and I didn't want that to prevent stat collections on other columns that have existing stats.

Could we protect against that case by changing distsql_plan_stats.go to skip over columns that don't have a prior full stat if this is an automatic collection?

I think simpler behavior here (failing the entire partial stats collection) will lead to fewer surprises, both here and in the optimizer when using these partial stats.
___
*[`pkg/sql/catalog/catpb/catalog.go` line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NCPB76Rl4lyjTG7qu:-O4gUn6fB9MkgeicDZE9:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/catalog/catpb/catalog.go#L73)):*
<details><summary><i>Previously, Uzair5162 (Uzair Ahmad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`pkg/sql/stats/automatic_stats.go` line 392 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NGd491PXKEesP3PDE:-O4guZDI-497zACWoDbb:bu875fj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L392)):*
Thank you for explaining! 

> Do you think it would be a good idea to add another check for auto full stats being enabled in [autoPartialStatsEnabled()](https://github.com/faizaanmadhani/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/stats/automatic_stats.go#L389) to make this more clear?

No, it's fine the way you have it. I just didn't read all of the code.
___
*[`pkg/sql/stats/automatic_stats.go` line 866 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gvVxi8UnZds8Ejua4:-O4gvVxi8UnZds8Ejua5:b-cnmuh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/stats/automatic_stats.go#L866)):*
> ```Go
> 	var rowCount float64
> 	mustRefresh := false
> 	mustRefreshPartial := false
> ```

bikeshedding: The purpose of this is a little different than `mustRefresh`, maybe `isPartial` would be better?
___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 686 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gn-h02c6WWgJb1Ode:-O4gn-h02c6WWgJb1Odf:bx76sjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L686)):*
> ```Go
> 		return nil
> 	}
> 	return errors.Newf("unable to set table setting %s", key)
> ```

nit: This could probably be `errors.AssertionFailedf`.
___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 712 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gn6p77phXqtRUPG9R:-O4gn6p77phXqtRUPG9S:b5ejy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L712)):*
> ```Go
> 			return nil
> 		}
> 		return errors.Newf("unable to set table setting %s", key)
> ```

nit: could also be `errors.AssertionFailedf`
___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 740 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gnAfo0BBCt_DuVwQx:-O4gnAfo0BBCt_DuVwQy:b5ejy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L740)):*
> ```Go
> 			return nil
> 		}
> 		return errors.Newf("unable to set table setting %s", key)
> ```

nit: could also be `errors.AssertionFailedf`
___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 771 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gnboy-BUd1YkWxlvb:-O4gnboy-BUd1YkWxlvc:b-6cn6s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L771)):*
> ```Go
> 		return nil
> 	}
> 	return errors.Newf("unable to reset table setting %s", key)
> ```

nit: this could also become `errors.AssertionFailedf`
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats` line 38 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gxjNX4qQw3b8EEvcY:-O4gxjNX4qQw3b8EEvcZ:b-lj3x4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats#L38)):*
> ```
> # not triggered.
> statement ok
> SET CLUSTER SETTING sql.stats.automatic_collection.min_stale_rows = 2147483647
> ```

nit: might be safer to do this before turning on `sql.stats.automatic_collection.enabled`
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats` line 90 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gyGhYDhTMvXzFumIA:-O4gyGhYDhTMvXzFumIB:b-mb5a72) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats#L90)):*
> ```
> ALTER TABLE data SET (sql_stats_automatic_partial_collection_enabled = true)
 [...]

2024-08-20 15:25 UTC, Uzair5162 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93067)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, @faizaanmadhani, and @michae2)

___
*[`-- commits` line 9 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gMBs-9XkJM9OFg0mT):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: looks like the per-table setting names need to be updated here

(Also, you might consider moving the details about the settings to the release note.)
</blockquote></details>

Done.
___
*[`pkg/sql/create_stats.go` line 222 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NSBZA1gcB_kyh71ME:-O4kJSFXEZwO9ttVomuv:bdq0svh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/create_stats.go#L222)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

For auto stats, these session variables come from the internal executor when [the stats.Refresher runs CREATE STATISTICS](https://github.com/cockroachdb/cockroach/blob/f5e3b37dced49ed37db1957e2e6abfb8412f8699/pkg/sql/stats/automatic_stats.go#L866-L871). We have a way to [set session variables for the internal executor](https://github.com/cockroachdb/cockroach/pull/122855), too, so I think it would be nice if CREATE STATISTICS respected the `enable_create_stats_using_extremes` session variable regardless of whether it was run manually or automatically.

In other words, I think `SET CLUSTER SETTING sql.internal_executor.session_overrides = 'enable_create_stats_using_extremes=off';` should prevent automatic collection of partial stats (even if `sql.stats.automatic_partial_collection.enabled` is on).
</blockquote></details>

Interesting! I've added a test for this [here](https://github.com/faizaanmadhani/cockroach/blob/2fc418280ce8f83b17e1adc9c10c1dcc970dbf78/pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats#L86-L114).
___
*[`pkg/sql/create_stats.go` line 741 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4NSywv1oNnzxI-fMfp:-O4kK4ZpC1IxOoDuHV2e:b-t4lrrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b06f5d08a0bce851f8f9ef379a7ba07ea4669b/pkg/sql/create_stats.go#L741)):*
> I think simpler behavior here (failing the entire partial stats collection) will lead to fewer surprises, both here and in the optimizer when using these partial stats.

I agree, let's keep it as is.
___
*[`pkg/sql/stats/automatic_stats.go` line 866 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gvVxi8UnZds8Ejua4:-O4kLPwq3izE-Yc3zJWi:bu2cqb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/stats/automatic_stats.go#L866)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

bikeshedding: The purpose of this is a little different than `mustRefresh`, maybe `isPartial` would be better?
</blockquote></details>

Agree, renamed to `isPartial`.
___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 686 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gn-h02c6WWgJb1Ode:-O4kM5H80x50d0fiNHZy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L686)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: This could probably be `errors.AssertionFailedf`.
</blockquote></details>

Done.
___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 712 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gn6p77phXqtRUPG9R:-O4kMDv48EcHtnkUbnH0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L712)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: could also be `errors.AssertionFailedf`
</blockquote></details>

Done.
___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 740 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gnAfo0BBCt_DuVwQx:-O4kMEGT1i2Szh7ls9sB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L740)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: could also be `errors.AssertionFailedf`
</blockquote></details>

Done.
___
*[`pkg/sql/storageparam/tablestorageparam/table_storage_param.go` line 771 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gnboy-BUd1YkWxlvb:-O4kMEtbCeK1iKQQUG2D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/storageparam/tablestorageparam/table_storage_param.go#L771)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: this could also become `errors.AssertionFailedf`
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats` line 38 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gxjNX4qQw3b8EEvcY:-O4kMHrV4lIpZQpZ_0sY:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats#L38)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: might be safer to do this before turning on `sql.stats.automatic_collection.enabled`
</blockquote></details>

Good point, done.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats` line 90 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4gyGhYDhTMvXzFumIA:-O4kMW0XA1A289K1KZmH:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9f44628c7878d2ce034fbdca109c2f684a01b/pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats#L90)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

typo: s/an/a/g
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2024-08-20 17:25 UTC, michae2 approved these changes
After addressing @rytaft's concerns, this <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Nice work bringing this back to life!!

> Reviewed 1 of 5 files at r5, 1 of 6 files at r6, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-:-O4koY3Y4aV_CZmuyZh4:b-gd8f1q)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, and @faizaanmadhani)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats` line 89 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4kf-la3KqX71v7r4MV:-O4kf-la3KqX71v7r4MW:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fc418280ce8f83b17e1adc9c10c1dcc970dbf78/pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats#L89)):*
> ```
> # setting instead
> statement ok
> SET CLUSTER SETTING sql.internal_executor.session_overrides = 'EnableCreateStatsUsingExtremes=false';
> ```

Nice!
___
*[`pkg/sql/stats/create_stats_job_test.go` line 404 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4klGCC7DPmPTB4auTr:-O4klGCC7DPmPTB4auTs:b-awz7gc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fc418280ce8f83b17e1adc9c10c1dcc970dbf78/pkg/sql/stats/create_stats_job_test.go#L404)):*
> ```Go
> 	allowRequest = make(chan struct{})
> 	initialFullStatErrCh := make(chan error)
> 	go func() {
> ```

speculation: You might not need the goroutine here if you `close(allowRequest)` first? I'm not 100% sure, though.
___
*[`pkg/sql/stats/create_stats_job_test.go` line 451 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4kmXlXEXQlPB0voAsS:-O4kmXlXEXQlPB0voAsT:bdmivzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fc418280ce8f83b17e1adc9c10c1dcc970dbf78/pkg/sql/stats/create_stats_job_test.go#L451)):*
> ```Go
> 	}
> 
> 	<-runningAutoPartialStatErrCh
> ```

Should we also check that this is nil?
___
*[`pkg/sql/stats/create_stats_job_test.go` line 489 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4koSynCpi-DZMqs4bI:-O4koSynCpi-DZMqs4bJ:b-gsac8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fc418280ce8f83b17e1adc9c10c1dcc970dbf78/pkg/sql/stats/create_stats_job_test.go#L489)):*
> ```Go
> 	}
> 
> 	<-runningAutoPartialStatErrCh
> ```

Same question here


<!-- Sent from Reviewable.io -->

2024-08-21 17:16 UTC, Uzair5162 reviewed
Thanks for the review @michae2 :)

I've changed it now so that auto partial stats jobs can't run concurrently on the same table, but they can still run at the same time as any other stats job.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-:-O4puiYB6Valla1UGFX-:b-ubm28f)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @dt, @faizaanmadhani, and @michae2)

___
*[`pkg/sql/stats/create_stats_job_test.go` line 404 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4klGCC7DPmPTB4auTr:-O4puBmX6uOqIYjODuZy:bsj4o0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fc418280ce8f83b17e1adc9c10c1dcc970dbf78/pkg/sql/stats/create_stats_job_test.go#L404)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

speculation: You might not need the goroutine here if you `close(allowRequest)` first? I'm not 100% sure, though.
</blockquote></details>

Correct :)
___
*[`pkg/sql/stats/create_stats_job_test.go` line 451 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4kmXlXEXQlPB0voAsS:-O4puRRpBRryVKahkkSA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fc418280ce8f83b17e1adc9c10c1dcc970dbf78/pkg/sql/stats/create_stats_job_test.go#L451)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should we also check that this is nil?
</blockquote></details>

Done.
___
*[`pkg/sql/stats/create_stats_job_test.go` line 489 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4koSynCpi-DZMqs4bI:-O4puTrJ1JcA8E3iuN20:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fc418280ce8f83b17e1adc9c10c1dcc970dbf78/pkg/sql/stats/create_stats_job_test.go#L489)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Same question here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-21 18:28 UTC, rytaft approved these changes
I just looked at the last revision, and that <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, thanks!

> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-:-O4qBN0l3HrACntbSyYN:b-vkm8xd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @dt, @faizaanmadhani, and @michae2)

___
*[`-- commits` line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4h6ZYR982m5JFCT22j):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

@rytaft do you have any objection to multiple automatic partial stats collections at once? It seems like a good way to start trying out multiple concurrent stats jobs?

I remember we discussed this before in:
- https://github.com/cockroachdb/cockroach/pull/118983
- some slack conversations I can't seem to find now
</blockquote></details>

Yea I think this should be fine now.
___
*[`pkg/jobs/utils.go` line 113 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4q9YlS9q-ctmljKrlB:-O4q9YlTEflDA5xw_dDF:bt45d9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a0852cafabf0b1db2d7f44a91f781c6b03e206/pkg/jobs/utils.go#L113)):*
> ```Go
> 		s.WriteByte(')')
> 		typeStrs = s.String()
> 	}
> ```

Can you pull this code to get typeStrs into a helper function? Looks identical to what's in the function above.


<!-- Sent from Reviewable.io -->

2024-08-21 19:50 UTC, Uzair5162 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93067)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @dt, @faizaanmadhani, @michae2, and @rytaft)

___
*[`pkg/jobs/utils.go` line 113 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4q9YlS9q-ctmljKrlB:-O4qUQ4s9lirPBtQjggS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78a0852cafabf0b1db2d7f44a91f781c6b03e206/pkg/jobs/utils.go#L113)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you pull this code to get typeStrs into a helper function? Looks identical to what's in the function above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-21 20:00 UTC, rytaft approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93067)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @dt, @faizaanmadhani, and @michae2)



<!-- Sent from Reviewable.io -->

2024-08-22 14:41 UTC, mgartner approved these changes
Nice work! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

I'm a bit concerned about the extra pressure this will place on the jobs system because this will fairly significantly increase the number of jobs. If we see problems when enabling this we might have to prioritize addressing #108435. 

> Reviewed 12 of 31 files at r3, 1 of 5 files at r5, 3 of 6 files at r6, 2 of 3 files at r8, 2 of 3 files at r9, 1 of 1 files at r11, 5 of 5 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-:-O4uWZdf0cZBlbBUoZL3:bjvr5k2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @dt, @faizaanmadhani, and @michae2)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats` line 73 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/93067#-O4uVMff6dE2sSN6IbIv:-O4uVMff6dE2sSN6IbIw:b1f6nub) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac3f39d904cde9a63967d442a9aea73ea8e2810/pkg/sql/logictest/testdata/logic_test/distsql_automatic_partial_stats#L73)):*
> ```
> query TTIIIT colnames
> SELECT DISTINCT ON (statistics_name, column_names) statistics_name, column_names, row_count, distinct_count, null_count, partial_predicate
> FROM [SHOW STATISTICS FOR TABLE data] ORDER BY statistics_name, column_names, created DESC
> ```

This test and the one below might erroneously pass because the queries complete before the partial stats could be collected. I don't see an easy way of making the tests more robust though... I suppose if there is a bug here the test will flake periodically in nightly tests and we'll find it.


<!-- Sent from Reviewable.io -->

2024-08-22 19:00 UTC, merged