pkg/ui: Add span details component to tracez_v2.
cockroachdb/cockroach pull request #93207
Opened 2022-12-07 18:52 UTC by benbardin

Modifies the route structure a little to encapsulate better.

Release note: None

<img width="1583" alt="Screen Shot 2022-12-07 at 1 52 26 PM" src="https://user-images.githubusercontent.com/261508/206270214-9708e298-cc8e-4a69-9554-8bfb8555277c.png">

<img width="1583" alt="Screen Shot 2022-12-07 at 1 51 59 PM" src="https://user-images.githubusercontent.com/261508/206270152-8d0a36f0-c64d-40bd-a47e-1573039e33ac.png">

<img width="1664" alt="Screen Shot 2022-12-05 at 12 12 41 PM" src="https://user-images.githubusercontent.com/261508/206269949-a62130c7-53cf-4655-84ae-8f6c42d4e66e.png">

2022-12-07 18:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/93207)
<!-- Reviewable:end -->

2022-12-13 16:36 UTC, dhartunian requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93207)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @benbardin)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93207#-NJBKw5Q9l1mH-KupNOT):*
Can you write more here to describe the purpose of your changes.
It's hard for me to review the PR when I don't understand your intent with it.

I don't work on this feature regularly so screenshots don't communicate what's changed.


<!-- Sent from Reviewable.io -->

2022-12-13 16:55 UTC, benbardin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93207)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @dhartunian)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93207#-NJBKw5Q9l1mH-KupNOT):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you write more here to describe the purpose of your changes.
It's hard for me to review the PR when I don't understand your intent with it.

I don't work on this feature regularly so screenshots don't communicate what's changed.
</blockquote></details>

Sure! I updated the PR description, that help any?


<!-- Sent from Reviewable.io -->

2022-12-19 18:30 UTC, dhartunian approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> let's get this merged once commit message is sync'ed. I'd like to delete the old code, clean up the routes, and start refining this experience.

> Reviewed 8 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93207#-:-NJfdLi9ETlIi-jKEgav:btic8r4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @benbardin)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93207#-NJBKw5Q9l1mH-KupNOT):*
<details><summary><i>Previously, benbardin (Ben Bardin) wrote…</i></summary><blockquote>

Sure! I updated the PR description, that help any?
</blockquote></details>

Yep, thanks. Please copy it over to the git commit message. The commit msg should be the "primary source" for the PR description.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93207#-NJfUUS67JaEnsQIhiOr:-NJfUUS67JaEnsQIhiOs:b9s4xb) ([raw file](https://github.com/cockroachdb/cockroach/blob/29eb3d2e46ce6dbdc118b062a3373091cb6ea0d9/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L81)):*
> ```XML
> }
> 
> // Ditto.
> ```

Copy paste the above please. They could get separated, etc.


<!-- Sent from Reviewable.io -->

2023-01-03 19:45 UTC, benbardin reviewed
sounds good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93207#-:-NKt9duU5QvW_Xs4X8RI:bp7vbfx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @andreimatei, and @dhartunian)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93207#-NJBKw5Q9l1mH-KupNOT):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Yep, thanks. Please copy it over to the git commit message. The commit msg should be the "primary source" for the PR description.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93207#-NJfUUS67JaEnsQIhiOr:-NKt8hFqCdzEaAj1bMAG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/29eb3d2e46ce6dbdc118b062a3373091cb6ea0d9/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L81)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Copy paste the above please. They could get separated, etc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-03 20:40 UTC, benbardin commented
bors r+

2023-01-03 23:09 UTC, merged