sql, server: implement and write to new recent statements cache
cockroachdb/cockroach pull request #93270
Opened 2022-12-08 18:48 UTC by amyyq2

This change implements and tests a new RecentStatementsCache that is used to store the recent statements that were executed. The cache has two new cluster settings that tune the capacity and time that a statement lives in the cache.

This change also implements writing ActiveQueries to the cache. The RecentStatementsCache is added to the ExecutorConfig, and the Server writes to this cache whenever a non-internal statement finishes. This change also removes queryMeta.phase, and replaces it with ActiveQuery.Phase. The phases Canceled, Timed Out, Completed, and Failed are also as possible values to ActiveQuery.Phase.

This change also defines a new ListRecentStatements API, that will be used to read from the cache. This will be implemented in a future PR.

Part Of #86955
Fixes #91556

Release note: None

2022-12-08 18:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/93270)
<!-- Reviewable:end -->

2022-12-08 21:23 UTC, xinhaoz commented
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NInbWqo763CuikScE4j):*
I noticed in your PR it says in the next PR, but this says the next commit.
IMO if this isn't implemented or used in this PR, there's no need to include it right now.


<!-- Sent from Reviewable.io -->

2022-12-14 21:39 UTC, matthewtodd requested changes
Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-:-NJHZrduCkjXNL9NOpz_:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amyyq2 and @xinhaoz)

___
*[`pkg/sql/conn_executor.go` line 597 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJHXVNnCRBMJSHO5F64:-NJHXVNo8-ege2-9N7Tk:bmvf7q1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1ece8d3dcd91cac0f30e8dda9c223ffa6f9f4e4/pkg/sql/conn_executor.go#L597)):*
> ```Go
> 	}
> 	activeQuery := qm.toActiveQuery(queryID, sessionID, appName, username, clientAddr, parsed, timeNow)
> 	err = s.cfg.RecentStatementsCache.Add(ctx, activeQuery)
> ```

I see below that this error's about not being about to allocate memory. Maybe add a comment here to that effect, so that it's clear why we're throwing it away? Or maybe even just assign to `_` and get rid of the `if` block altogether?
___
*[`pkg/sql/recent/statements_cache.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJHZ8WT5Q2a8t8Iwn3A:-NJHZ8WU6AwSZfE4XO9a:bokgxau) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1ece8d3dcd91cac0f30e8dda9c223ffa6f9f4e4/pkg/sql/recent/statements_cache.go#L138)):*
> ```Go
> 	toEvict := ""
> 	rc.mu.data.Do(func(entry *cache.Entry) {
> 		if toEvict != "" {
> ```

Is there a way to move this ttl eviction logic up into the `ShouldEvict` function above?


<!-- Sent from Reviewable.io -->

2022-12-14 22:12 UTC, amyyq2 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd and @xinhaoz)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NInbWqo763CuikScE4j):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I noticed in your PR it says in the next PR, but this says the next commit.
IMO if this isn't implemented or used in this PR, there's no need to include it right now.
</blockquote></details>

Ok, I've removed it from this PR, and will add it in the next PR
___
*[`pkg/sql/conn_executor.go` line 597 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJHXVNnCRBMJSHO5F64:-NJHgKtM9x94RbYUFfyY:b-l16t4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1ece8d3dcd91cac0f30e8dda9c223ffa6f9f4e4/pkg/sql/conn_executor.go#L597)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I see below that this error's about not being about to allocate memory. Maybe add a comment here to that effect, so that it's clear why we're throwing it away? Or maybe even just assign to `_` and get rid of the `if` block altogether?
</blockquote></details>

Ah yes, I'll add a comment and assign it to `_`. Thanks!
___
*[`pkg/sql/recent/statements_cache.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJHZ8WT5Q2a8t8Iwn3A:-NJHesQ66P5Lg__dTt9C:bojzsco) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1ece8d3dcd91cac0f30e8dda9c223ffa6f9f4e4/pkg/sql/recent/statements_cache.go#L138)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Is there a way to move this ttl eviction logic up into the `ShouldEvict` function above?
</blockquote></details>

Yes there is, but adding it to `ShouldEvict` only evicts on adds to the cache. I put it here so that we evict the entries past ttl on every access to the cache. Do you think it's preferred to put it in `ShouldEvict`?


<!-- Sent from Reviewable.io -->

2022-12-19 20:29 UTC, matthewtodd requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amyyq2 and @xinhaoz)

___
*[`pkg/sql/recent/statements_cache.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJHZ8WT5Q2a8t8Iwn3A:-NJg1mTt1-3sRJJcvpY2:b5tear) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1ece8d3dcd91cac0f30e8dda9c223ffa6f9f4e4/pkg/sql/recent/statements_cache.go#L138)):*
<details><summary><i>Previously, amyyq2 wrote…</i></summary><blockquote>

Yes there is, but adding it to `ShouldEvict` only evicts on adds to the cache. I put it here so that we evict the entries past ttl on every access to the cache. Do you think it's preferred to put it in `ShouldEvict`?
</blockquote></details>

Yeah, you're right that, if we moved all the logic to `ShouldEvict`, there would be a small "incorrectness window" where we could show old entries that should have been evicted.

I would suggest that we could be okay with that, because
1. there's already a ton of write traffic through the cache, so we'll have plenty of opportunity to check for evictions
2. in the overwhelmingly common case, we'll be hitting the size limit before the ttl limit anyway
3. having the eviction logic all in the same place will (I suspect) make this code easier to understand later

Does that work for you?


<!-- Sent from Reviewable.io -->

2022-12-19 22:37 UTC, amyyq2 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd and @xinhaoz)

___
*[`pkg/sql/recent/statements_cache.go` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJHZ8WT5Q2a8t8Iwn3A:-NJgX1tCCTO99sBHpIlZ:b-fknmxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1ece8d3dcd91cac0f30e8dda9c223ffa6f9f4e4/pkg/sql/recent/statements_cache.go#L138)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Yeah, you're right that, if we moved all the logic to `ShouldEvict`, there would be a small "incorrectness window" where we could show old entries that should have been evicted.

I would suggest that we could be okay with that, because
1. there's already a ton of write traffic through the cache, so we'll have plenty of opportunity to check for evictions
2. in the overwhelmingly common case, we'll be hitting the size limit before the ttl limit anyway
3. having the eviction logic all in the same place will (I suspect) make this code easier to understand later

Does that work for you?
</blockquote></details>

Yup that sounds good, I changed it to evict on both capacity and TTL in `ShouldEvict`


<!-- Sent from Reviewable.io -->

2022-12-21 16:30 UTC, matthewtodd approved these changes
Nice work, @amyyq2! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-:-NJpWD3G8FtXlM8-r4tL:b8kuad)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)



<!-- Sent from Reviewable.io -->

2022-12-21 16:44 UTC, maryliag approved these changes
Awesome work! Just a few nits, otherwise <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 13 of 18 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-:-NJpZR9FBP5enl-3wuPH:bshdwep)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @amyyq2, @matthewtodd, and @xinhaoz)

___
*[`pkg/sql/exec_util.go` line 1995 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpZNFgAoCMPXpRiNoC:-NJpZNFgAoCMPXpRiNoD:b-11xfsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/exec_util.go#L1995)):*
> ```Go
> 
> // toActiveQuery translates the queryMeta to a serverpb.ActiveQuery.
> func (q *queryMeta) toActiveQuery(
> ```

can you add tests for this function?
___
*[`pkg/sql/recent/statements_cache.go` line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpZ24q2_ONacon0zg-:-NJpZ24q2_ONacon0zg0:bs1atum) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/recent/statements_cache.go#L136)):*
> ```Go
> 	ctx context.Context, visitor func(context.Context, *serverpb.ActiveQuery),
> ) {
> 	rc.mu.Lock()
> ```

are you doing any changes to the values that you're iterating? if this is just about reading you can use RLock / RUnlock
___
*[`pkg/sql/recent/statements_cache_test.go` line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpZEjo-nZLCogWMGtb:-NJpZEjo-nZLCogWMGtc:bebo1p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/recent/statements_cache_test.go#L39)):*
> ```Go
> 	StatementsCacheTimeToLive.Override(ctx, &st.SV, timeToLive)
> 
> 	// Add 6 statements with IDs ranging from 0 to 5, inclusive.
> ```

nit: from 0 to 6


<!-- Sent from Reviewable.io -->

2022-12-21 17:29 UTC, rafiss requested changes
this is cool! just left some suggestions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-:-NJpirsNE0jJRlzdZJ7d:b89qfs9)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @amyyq2, @maryliag, @matthewtodd, and @xinhaoz)

___
*[`pkg/sql/conn_executor.go` line 591 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpfqqTDgCfGIDRwsfk:-NJpfqqTDgCfGIDRwsfl:b-vq4aio) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/conn_executor.go#L591)):*
> ```Go
> 	timeNow time.Time,
> ) {
> 	parsed, err := parser.ParseOne(qm.stmt.SQL)
> ```

can you add a comment saying why we need to re-parse, instead of just using `qm.stmt.AST`?
___
*[`pkg/sql/conn_executor.go` line 3245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpgIQHAjVmU53-TGDP:-NJpgIQHAjVmU53-TGDQ:b-6l82qb) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/conn_executor.go#L3245)):*
> ```Go
> 	}
> 
> 	sd := ex.sessionDataStack.Base()
> ```

nit: use `ex.sessionData()`
___
*[`pkg/sql/conn_executor.go` line 3247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpg7HYB4dOpF37ZwdU:-NJpg7HYB4dOpF37ZwdV:bodxt6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/conn_executor.go#L3247)):*
> ```Go
> 	sd := ex.sessionDataStack.Base()
> 
> 	remoteStr := "<admin>"
> ```

what does this `<admin>` mean?
___
*[`pkg/sql/conn_executor.go` line 3289 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpgUA87KwjkNmMdt9P:-NJpgUA87KwjkNmMdt9Q:b3gzq1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/conn_executor.go#L3289)):*
> ```Go
> 
> 	// We always use base here as the fields from the SessionData should always
> 	// be that of the root session.
> ```

this comment should be moved up to where you copied the code
```
	sd := ex.sessionDataStack.Base()

	remoteStr := "<admin>"
	if sd.RemoteAddr != nil {
		remoteStr = sd.RemoteAddr.String()
	}
```
___
*[`pkg/sql/exec_util.go` line 2006 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpglGD5ahB6yuQ_Vt_:-NJpglGD5ahB6yuQ_Vta:b22tvyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/exec_util.go#L2006)):*
> ```Go
> 	truncateSQL := func(sql string) string {
> 		if len(sql) > MaxSQLBytes {
> 			sql = sql[:MaxSQLBytes-utf8.RuneLen('…')]
> ```

hm, i didn't follow where this `sql[:MaxSQLBytes-utf8.RuneLen('…')]` bit came from. what is this doing?
___
*[`pkg/sql/recent/statements_cache.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJphO5k3c8CdUZrRUcR:-NJphO5lDtRaKOvzXBuo:bf0axdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/recent/statements_cache.go#L53)):*
> ```Go
> type StatementsCache struct {
> 	st      *cluster.Settings
> 	timeSrc timeSource
> ```

i might be missing something - i don't see `timeSrc` ever being set anywhere. can we just remove it?

if we keep it, this could deserve a comment


<!-- Sent from Reviewable.io -->

2022-12-21 17:30 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @amyyq2, @maryliag, @matthewtodd, and @xinhaoz)

___
*[`pkg/sql/conn_executor.go` line 3245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpgIQHAjVmU53-TGDP:-NJpixYQ1KF1d6a3JNto:b6g266s) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/conn_executor.go#L3245)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: use `ex.sessionData()`
</blockquote></details>

ah, nvm, i see the comment below, which should be moved here
```
	// We always use base here as the fields from the SessionData should always
	// be that of the root session.
```
___
*[`pkg/sql/conn_executor.go` line 3247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpg7HYB4dOpF37ZwdU:-NJpj2U0D79DoAUUyTT3:b-2jxwo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/conn_executor.go#L3247)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what does this `<admin>` mean?
</blockquote></details>

nevermind, i see it was from the existing code


<!-- Sent from Reviewable.io -->

2022-12-21 19:36 UTC, amyyq2 reviewed
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-:-NJq9rLa6LmtQQ_SFqJJ:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @maryliag, @matthewtodd, @rafiss, and @xinhaoz)

___
*[`pkg/sql/conn_executor.go` line 591 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpfqqTDgCfGIDRwsfk:-NJq13BZ19xXgqho7Udi:b-vytofz) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/conn_executor.go#L591)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you add a comment saying why we need to re-parse, instead of just using `qm.stmt.AST`?
</blockquote></details>

Yup, also moved the parsing logic into `toActiveQuery`, since I was duplicating that in both calls to the function
___
*[`pkg/sql/conn_executor.go` line 3245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpgIQHAjVmU53-TGDP:-NJq19pV7XiNbruCtoKa:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/conn_executor.go#L3245)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah, nvm, i see the comment below, which should be moved here
```
	// We always use base here as the fields from the SessionData should always
	// be that of the root session.
```
</blockquote></details>

Done
___
*[`pkg/sql/conn_executor.go` line 3247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpg7HYB4dOpF37ZwdU:-NJq1BIhDmpOkTcU2MPZ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/conn_executor.go#L3247)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nevermind, i see it was from the existing code
</blockquote></details>

Done
___
*[`pkg/sql/conn_executor.go` line 3289 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpgUA87KwjkNmMdt9P:-NJq1BpQ8z6OCXmgNaju:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/conn_executor.go#L3289)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this comment should be moved up to where you copied the code
```
	sd := ex.sessionDataStack.Base()

	remoteStr := "<admin>"
	if sd.RemoteAddr != nil {
		remoteStr = sd.RemoteAddr.String()
	}
```
</blockquote></details>

Done
___
*[`pkg/sql/exec_util.go` line 1995 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpZNFgAoCMPXpRiNoC:-NJq9uou2qtLaPXDZECL:bie9rby) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/exec_util.go#L1995)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you add tests for this function?
</blockquote></details>

I tested by changing `MaxSQLBytes` to 4. On the UI, the sql is truncated to only the first character and `...`, showing that it is truncated correctly.
___
*[`pkg/sql/exec_util.go` line 2006 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpglGD5ahB6yuQ_Vt_:-NJq2CiPBZXvV7Oi86So:b-l6ke2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/exec_util.go#L2006)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, i didn't follow where this `sql[:MaxSQLBytes-utf8.RuneLen('…')]` bit came from. what is this doing?
</blockquote></details>

I copied this over from the existing `serialize` function in `conn_executor`, but it looks like it's just keeping the part of the sql string that is within the MaxSQLBytes, and replacing the rest with `...`
___
*[`pkg/sql/recent/statements_cache.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJphO5k3c8CdUZrRUcR:-NJq1fl06mn6t_iYsUcl:bdd1f7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/recent/statements_cache.go#L53)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i might be missing something - i don't see `timeSrc` ever being set anywhere. can we just remove it?

if we keep it, this could deserve a comment
</blockquote></details>

Hm, I believe I'm setting it in `NewStatementsCache` on line 88. Then I read from it in the `ShouldEvict` function to determine when a stmt is past TTL. I can add a comment explaining that
___
*[`pkg/sql/recent/statements_cache.go` line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpZ24q2_ONacon0zg-:-NJq1FBu4fMAIpFcvAB1:b-vn0gx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/recent/statements_cache.go#L136)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

are you doing any changes to the values that you're iterating? if this is just about reading you can use RLock / RUnlock
</blockquote></details>

I'm only reading the values, so changed to RLock/RUnlock
___
*[`pkg/sql/recent/statements_cache_test.go` line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJpZEjo-nZLCogWMGtb:-NJq1KP5CjFa3s-efO-W:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6cbed9bac09a32b1f218611999d4469c473d13/pkg/sql/recent/statements_cache_test.go#L39)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: from 0 to 6
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-12-21 22:17 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @amyyq2, @maryliag, @matthewtodd, and @xinhaoz)

___
*[`pkg/sql/conn_executor.go` line 596 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJqkjFH9iEOrXsZ-LkH:-NJqkjFH9iEOrXsZ-LkI:b-nnuo60) ([raw file](https://github.com/cockroachdb/cockroach/blob/01bf321741242910ba28104f443e09f3b3b4656f/pkg/sql/conn_executor.go#L596)):*
> ```Go
> 	}
> 	err = s.cfg.RecentStatementsCache.Add(ctx, activeQuery)
> 	if err != nil {
> ```

nit: log a warning here so if something is going wrong, it's possible to learn about it. otherwise, this could fail silently forever
___
*[`pkg/sql/exec_util.go` line 2028 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJqkFPo6iBPAgqx-xkg:-NJqkFPo6iBPAgqx-xkh:b-rr0flz) ([raw file](https://github.com/cockroachdb/cockroach/blob/01bf321741242910ba28104f443e09f3b3b4656f/pkg/sql/exec_util.go#L2028)):*
> ```Go
> 	if err != nil {
> 		// We can't just log the SQL as it could contain sensitive information.
> 		log.Warningf(ctx, "failed to re-parse sql")
> ```

nit: instead of logging and returning the error, it should be one or the other. so here, just return the error

at lines 593 and 3259 of conn_executor.go, at the places where the error gets swallowed, instead of doing nothing, the warning should be logged there.


<!-- Sent from Reviewable.io -->

2022-12-21 22:18 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @amyyq2, @maryliag, @matthewtodd, and @xinhaoz)

___
*[`pkg/sql/conn_executor.go` line 592 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJqkulXCbDmBjJCML92:-NJqkulXCbDmBjJCML93:b-mu6eca) ([raw file](https://github.com/cockroachdb/cockroach/blob/01bf321741242910ba28104f443e09f3b3b4656f/pkg/sql/conn_executor.go#L592)):*
> ```Go
> 	activeQuery, err := qm.toActiveQuery(ctx, queryID, sessionID, appName, username, clientAddr, timeNow)
> 	if err != nil {
> 		// Failed to re-parse SQL
> ```

nit: log a warning here rather than swallowing the error silently


<!-- Sent from Reviewable.io -->

2022-12-21 22:50 UTC, amyyq2 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @maryliag, @matthewtodd, @rafiss, and @xinhaoz)

___
*[`pkg/sql/conn_executor.go` line 592 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJqkulXCbDmBjJCML92:-NJqsMtu-j2MgYsYVZqv:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/01bf321741242910ba28104f443e09f3b3b4656f/pkg/sql/conn_executor.go#L592)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: log a warning here rather than swallowing the error silently
</blockquote></details>

Done
___
*[`pkg/sql/conn_executor.go` line 596 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJqkjFH9iEOrXsZ-LkH:-NJqsMEr0E_bdxebwOIo:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/01bf321741242910ba28104f443e09f3b3b4656f/pkg/sql/conn_executor.go#L596)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: log a warning here so if something is going wrong, it's possible to learn about it. otherwise, this could fail silently forever
</blockquote></details>

Done
___
*[`pkg/sql/exec_util.go` line 2028 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJqkFPo6iBPAgqx-xkg:-NJqs6SNDnKUk-KlJybA:byiq1as) ([raw file](https://github.com/cockroachdb/cockroach/blob/01bf321741242910ba28104f443e09f3b3b4656f/pkg/sql/exec_util.go#L2028)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: instead of logging and returning the error, it should be one or the other. so here, just return the error

at lines 593 and 3259 of conn_executor.go, at the places where the error gets swallowed, instead of doing nothing, the warning should be logged there.
</blockquote></details>

Ah that makes a lot of sense, fixed!


<!-- Sent from Reviewable.io -->

2022-12-22 16:57 UTC, rafiss approved these changes
one small nit, then lgtm! feel free to merge after you address that

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-:-NJul0j55x58GmtCZfBA:b-3x1o52)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @amyyq2, @maryliag, @matthewtodd, and @xinhaoz)

___
*[`pkg/sql/conn_executor.go` line 597 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJukrHkBzU1vD9O92jk:-NJukrHkBzU1vD9O92jl:bdicd0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/76ccb819b854a04655192f9cb96a29a029304e6d/pkg/sql/conn_executor.go#L597)):*
> ```Go
> 	}
> 	err = s.cfg.RecentStatementsCache.Add(ctx, activeQuery)
> 	if err != nil {
> ```

nit: log a warning here, like "could not add to cache"


<!-- Sent from Reviewable.io -->

2022-12-22 17:04 UTC, amyyq2 reviewed
Sounds good, TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-:-NJumhN18GfcZzYIOARg:b-hdn79z)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @maryliag, @matthewtodd, @rafiss, and @xinhaoz)

___
*[`pkg/sql/conn_executor.go` line 597 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93270#-NJukrHkBzU1vD9O92jk:-NJumfhL-cRZOmLtcfWU:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/76ccb819b854a04655192f9cb96a29a029304e6d/pkg/sql/conn_executor.go#L597)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: log a warning here, like "could not add to cache"
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-12-22 18:39 UTC, amyyq2 commented
bors r+

2022-12-22 19:56 UTC, merged