[DNM]: sql: add new crdb_internal.get_index_tuples for reading raw key/values from indexes
cockroachdb/cockroach pull request #93536
Opened 2022-12-13 19:26 UTC by fqazi

This PR will do the following:

1.  Add a new crdb_internal.get_index_tuples generator for reading raw key/values for indexes from KV.
2. Add a new optimizer transformation that converts calls of crdb_internal.get_index_tuples into a new IndexReader processor, which will support distributed execution.
3. Adopt this new crdb_internal for validating inverted indexes.

Epic: None

2022-12-13 19:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/93536)
<!-- Reviewable:end -->

2022-12-14 15:03 UTC, ajwerner reviewed
This is great! I'd be cool to see the speed-up on inverted index construction quantified. When this is ready to go, consider making a roachprod cluster and creating an inverted index over some relatively large corpus and seeing if you can get it to make a big difference.

One observation is that this is very similar to `crdb_internal.scan`added in https://github.com/cockroachdb/cockroach/pull/83934. Is there a way we can accelerate that and have this use that? The biggest challenge I see is that that thing is admin only, but I don't know that that's a problem for our use case. WDYT?

Separetely, can you add some testing which uses explain (distsql) to show that we get the proper nodes in the physical plan?

We're definitely going to need to have some queries folks looking at this. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-:-NJG7grY3F-Jqplq26Sd:brcp7f1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/repair.go` line 805 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJG8Dbz0UG4WELKEEJH:-NJG8Dbz0UG4WELKEEJI:b9netjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c99801ce5ba0e01d127aa6f182b4494841fbcca/pkg/sql/repair.go#L805)):*
> ```Go
> }
> 
> // IndexTupleGenerator goes over all tuples inside
> ```

repair.go seems like an odd place for this to go. 
___
*[`pkg/sql/logictest/testdata/logic_test/get_index_tuple` line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJG8lr97OfjVeiONO-7:-NJG8lr97OfjVeiONO-8:bfckvtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/796b778cd319ce4cc3194b730a7332ac5a3535a2/pkg/sql/logictest/testdata/logic_test/get_index_tuple#L3)):*
> ```
> # LogicTest: fakedist
> subtest query-indexes
> ```

it'd be nice to have some testing which reveals column family encodings, if only to show that it works. 


<!-- Sent from Reviewable.io -->

2022-12-14 15:14 UTC, fqazi reviewed
@ajwerner Based on how the crdb_internal.scan we can definitely do that and kill off the crdb_internal that was added here. The main change is that we have to reach a bit deeper and extract values from crdb_internal.index_span call. Let me take a stab and sort out the other comments as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-:-NJGB-Q9-Gb6FV0bFE2s:bfor22y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2022-12-16 17:32 UTC, rytaft requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[`-- commits` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJQz3p673L6oD1o48BU):*
Can you help me understand why we can't use our existing infrastructure of optimizer ScanExprs and DistSQL TableReaders for this?


<!-- Sent from Reviewable.io -->

2022-12-16 18:24 UTC, stevendanna reviewed
Nice! This will be so useful. Thanks for working on it

2022-12-16 18:42 UTC, fqazi commented
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93536)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)
> 
> _[`-- commits` line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJQz3p673L6oD1o48BU):_ Can you help me understand why we can't use our existing infrastructure of optimizer ScanExprs and DistSQL TableReaders for this?

Part of the reason is that we need to be able to get raw values from within a set of spans for an inverted index without combining column families / decoding things. The intent for this type of scan is to be able to see the raw number of entries within the inverted index for validation, which may not map nicely to normal SQL constructs. So, this makes it a simple leaf DistSQL processor that just returns raw KV data. 

While I think we could teach normal TableReaders to do the same thing, it probably would be an overkill special case (i.e. some really weird special case code path that skips most of their intent of decoding and turning things into actual rows). That said maybe this should be a more general kvScan operation, which is only focused on raw data for this general use case (versus the current index focus).

2022-12-19 16:30 UTC, rytaft requested changes
Thanks for the explanation! I'm working my way through this. Still have some more files to review, but pushing what I have for now. I'd also like someone with DistSQL expertise to take a look, maybe either @drewkimball or @rharding6373 since @yuzefovich is out for the rest of the week.

> maybe this should be a more general kvScan operation

I think that would be an improvement. IndexScan is too close to our regular Scan operator, which already implies a scan of a specific index.

> Reviewed 6 of 26 files at r2, 8 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-:-NJf5m1P15BIgfEOKV7O:b2fy9j8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[`pkg/sql/distsql_physical_planner.go` line 4541 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJf8J6t193SJPSLqUX4:-NJf8J6t193SJPSLqUX5:b-jr6f8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/distsql_physical_planner.go#L4541)):*
> ```Go
> 		p.ResultRouters[i] = pIdx
> 	}
> 	p.PlanToStreamColMap = []int{0, 1, 2}
> ```

I don't think this should be hardcoded. Also, don't you need to set the merge ordering somewhere?
___
*[`pkg/sql/index_scan.go` line 23 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJfABqzDwiZPU7DCbSA:-NJfABqzDwiZPU7DCbSB:b-krkz2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/index_scan.go#L23)):*
> ```Go
> )
> 
> type indexScanNode struct {
> ```

This needs a comment explaining what it is
___
*[`pkg/sql/index_scan.go` line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJf9JjE6fhow604HUES:-NJf9JjE6fhow604HUET:boqavuu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/index_scan.go#L37)):*
> ```Go
> 		return nil, err
> 	}
> 	return &indexScanNode{
> ```

The `distSQLSpecExecFactory` should not be returning plan nodes. Take a look at distsql_spec_exec_factory.go. I'd suggest just returning an unimplemented error for now like most other operators. Also, this function should go in that file.
___
*[`pkg/sql/index_scan.go` line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJf9tdk7WFXn9soWPXA:-NJf9tdk7WFXn9soWPXB:b-7epewn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/index_scan.go#L44)):*
> ```Go
> 
> // ConstructIndexScan is part of the exec.Factory interface.
> func (ef *execFactory) ConstructIndexScan(table cat.Table, index cat.Index) (exec.Node, error) {
> ```

this function should go in opt_exec_factory.go
___
*[`pkg/sql/index_scan.go` line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJf9qR30ogsz3KemXF7:-NJf9qR30ogsz3KemXF8:b-wyo2p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/index_scan.go#L45)):*
> ```Go
> // ConstructIndexScan is part of the exec.Factory interface.
> func (ef *execFactory) ConstructIndexScan(table cat.Table, index cat.Index) (exec.Node, error) {
> 	tableDesc, err := ef.planner.Descriptors().GetImmutableTableByID(context.Background(), ef.planner.Txn(), descpb.ID(table.ID()), tree.ObjectLookupFlagsWithRequired())
> ```

I think you can just do:
```
tabDesc := table.(*optTable).desc
```
Take a look at `execFactory.ConstructScan`

also a nit: code lines should be <= 100 characters
___
*[`pkg/sql/catalog/colinfo/result_columns.go` line 297 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJfAMHF4-xN_efW5ceh:-NJfAMHF4-xN_efW5cei:b-4cval) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/catalog/colinfo/result_columns.go#L297)):*
> ```Go
> }
> 
> // IndexScanColumns are the results for index scan selects
> ```

nit: end comment with period.
___
*[`pkg/sql/opt/exec/factory.opt` line 781 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJfAdiR-gDzouyyv6ie:-NJfAdiR-gDzouyyv6if:b2v7e9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/exec/factory.opt#L781)):*
> ```
> }
> 
> define IndexScan {
> ```

This needs a comment
___
*[`pkg/sql/opt/exec/execbuilder/statement.go` line 415 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJfCV-PEaT_cW-CKJC-:-NJfCV-PEaT_cW-CKJC0:b43opod) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/exec/execbuilder/statement.go#L415)):*
> ```Go
> func (b *Builder) buildIndexScan(indexScan *memo.IndexScanExpr) (execPlan, error) {
> 	// Resolve the table and index based on IDs.
> 	ds, _, err := b.catalog.ResolveDataSourceByID(b.ctx, cat.Flags{AvoidDescriptorCaches: true}, cat.StableID(indexScan.Table))
> ```

I don't think you need to do this. The data source should already have been resolved.

You should be able to do something like:
```
tab := md.Table(indexScan.Table)
```

Take a look at `Builder.buildScan`
___
*[`pkg/sql/opt/exec/execbuilder/statement.go` line 421 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJfCpUd2DJhYWxPNexl:-NJfCpUd2DJhYWxPNexm:behihfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/exec/execbuilder/statement.go#L421)):*
> ```Go
> 	table := ds.(cat.Table)
> 	var index cat.Index
> 	for idx := 0; idx < table.IndexCount(); idx++ {
> ```

this for loop shouldn't be needed either. Take a look at how it's done in `buildScan`


<!-- Sent from Reviewable.io -->

2022-12-19 17:44 UTC, yuzefovich commented
My eyes are recovering faster than anticipated, so I should be able to take a look within a day or two. Still it wouldn't hurt if Drew or Rachael took a look too.

2022-12-19 21:32 UTC, rytaft requested changes
> Reviewed 7 of 26 files at r2, 12 of 20 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[`-- commits` line 28 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJgGcfkD6-jj9_hX37P):*
Seems like this deserves a release note for improved performance
___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2811 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJg7aiZ-r_DRlsbSXlJ:-NJg7aiZ-r_DRlsbSXlK:b-47v9x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/memo/logical_props_builder.go#L2811)):*
> ```Go
> 
> func (b *logicalPropsBuilder) buildIndexScanProps(indexScan *IndexScanExpr, rel *props.Relational) {
> 	b.buildBasicProps(indexScan, indexScan.Cols, rel)
> ```

We should be able to do better than this. Take a look at `buildScan` for an example.
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 486 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJg7JeR3AurM0U9worn:-NJg7JeR3AurM0U9woro:b9s61w2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/memo/statistics_builder.go#L486)):*
> ```Go
> 		opt.OpaqueRelOp, opt.OpaqueMutationOp, opt.OpaqueDDLOp, opt.RecursiveCTEOp,
> 		opt.IndexScanOp:
> 		return sb.colStatUnknown(colSet, e.Relational())
> ```

I think we can do a lot better than this. We know how many rows are in the table, so we should be able to get correct stats. Take a look at `colStatScan` and `buildScan` for examples.
___
*[`pkg/sql/opt/norm/general_funcs.go` line 1110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJgBizoBUvMeGiu95w1:-NJgBizoBUvMeGiu95w2:b-ova86l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/norm/general_funcs.go#L1110)):*
> ```Go
> 		panic(errors.AssertionFailedf("index scans can only be generated from constants"))
> 	}
> 	indexScan := c.mem.MemoizeIndexScan(&memo.IndexScanPrivate{
> ```

You should call ConstructIndexScan here, not MemoizeIndexScan
___
*[`pkg/sql/opt/norm/general_funcs.go` line 1141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJgAtv7CGMx0D-LtgGn:-NJgAtv7CGMx0D-LtgGo:b9jisfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/norm/general_funcs.go#L1141)):*
> ```Go
> 			return false
> 		}
> 		if indexSpanExpr.Name != "crdb_internal.index_span" || len(indexSpanExpr.Args) != 2 {
> ```

This isn't actually checking if the args are constant. What if the args are variables? (I think the function above, MakeIndexScanFromZip, will panic in this case). Please add a test to confirm.
___
*[`pkg/sql/opt/norm/rules/project.opt` line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJg84zv7hnrvsjbKUtE:-NJg84zv7hnrvsjbKUtF:besuesx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/norm/rules/project.opt#L302)):*
> ```
> # containing an invocation to crdb_internal.index_get_tuples directly
> # into an index scan expression that supports distributed execution.
> [ConvertProjectionSetGetIndexTuplesToIndexScan, Normalize]
> ```

nit: I'd call this `ConvertProjectSetGetIndexTuplesToIndexScan` (or `ConvertProjectSetGetIndexTuplesToKVScan` or something like that if you change the name from IndexScan)
___
*[`pkg/sql/opt/norm/rules/project.opt` line 303 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJg7sPt0xsweQ5GASsE:-NJg7sPt0xsweQ5GASsF:b-cd4xku) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/norm/rules/project.opt#L303)):*
> ```
> # into an index scan expression that supports distributed execution.
> [ConvertProjectionSetGetIndexTuplesToIndexScan, Normalize]
> (ProjectSet $input:* $zip:* & (IsIndexScanBuiltin $zip))
> ```

this should go in `project_set.opt`

Also, please add some optimizer tests for this rule in `pkg/sql/opt/norm/testdata/rules/project_set`
___
*[`pkg/sql/opt/ops/relational.opt` line 1410 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJgA5UB27hJjhOM4qjb:-NJgA5UB27hJjhOM4qjc:b-hb91f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/ops/relational.opt#L1410)):*
> ```
>     Table TableID
>     Index IndexOrdinal
>     Cols ColList
> ```

Any reason not to use a ColSet like ScanPrivate does?

Also, please add comments (you can just copy the comments used in ScanPrivate)
___
*[`pkg/sql/sem/builtins/builtins.go` line 5539 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJgD8r58bNjPT8R9a2x:-NJgD8r63kJ8_0Ky6l3k:b-tpy674) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/sem/builtins/builtins.go#L5539)):*
> ```Go
> 			Info: "This function returns the span that contains the keys for the given index.",
> 			// Note: This is intentionally volatile, so that transformations can be
> 			// used to optimize constant cases into DistSQL, when used with crdb_internal.scan.
> ```

I don't think you need to make the function volatile to do this. You could just make sure that your rule fires before the constant folding rules by making it HighPriority.
___
*[`pkg/sql/logictest/testdata/logic_test/get_index_tuple` line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJG8lr97OfjVeiONO-7:-NJgEG5r3p58GlHQmjKW:b3bojke) ([raw file](https://github.com/cockroachdb/cockroach/blob/796b778cd319ce4cc3194b730a7332ac5a3535a2/pkg/sql/logictest/testdata/logic_test/get_index_tuple#L3)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

it'd be nice to have some testing which reveals column family encodings, if only to show that it works. 
</blockquote></details>

Can you also add some tests with:
- an inverted index
- variable arguments instead of constants
- call `crdb_internal.scan` with arguments other than `crdb_internal.index_span`
- call the function from the select list instead of FROM clause
- call the function multiple times in the select list
- include some other relational operators such as join / aggregation

(alternatively, or in addition, you could add some of these additional tests as optimizer tests in `pkg/sql/opt/norm/testdata/rules/project_set`)
___
*[`pkg/sql/logictest/testdata/logic_test/index_scan_opt` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJgDqAmCPNuZbyHmCIM:-NJgDqAmCPNuZbyHmCIN:b-y8bzfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/logictest/testdata/logic_test/index_scan_opt#L34)):*
> ```
> 
> query T
> EXPLAIN SELECT count(*)  FROM crdb_internal.scan(crdb_internal.index_span($q_id,2));
> ```

all tests that print the explain plan should go in `execbuilder`

In execbuilder, can you also show a variety of other plans, including the DistSQL plans (maybe add some more data and split ranges so the plan touches multiple nodes)


<!-- Sent from Reviewable.io -->

2022-12-20 02:44 UTC, yuzefovich reviewed
Nice work! I agree that this deserves a separate DistSQL processor, and I'll leave it up to you to decide whether we want to generalize it into a "KV scan" rather than specifically an "index scan".

> Reviewed 8 of 26 files at r2, 10 of 20 files at r4, 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-:-NJhOQ50-3fXA8bh0jzE:bu6gje5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @rytaft)

___
*[`-- commits` line 28 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJgGcfkD6-jj9_hX37P):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Seems like this deserves a release note for improved performance
</blockquote></details>

Will this `crdb_internal.scan` primitive be used for user-facing operations? The comment suggests that it'll be used for index validation, and if there are no other use cases, then I'd imagine users shouldn't see any impact meaning the release note is not necessary, unless the speed of index validation will change or something like that.
___
*[`pkg/sql/backfill.go` line 1603 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhO6xX9eL18YyoVKur:-NJhO6xX9eL18YyoVKus:bgf2wl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f0d07a7bc13c802f6d945514d24d1f77f8c2d61/pkg/sql/backfill.go#L1603)):*
> ```Go
> 		grp.GoCtx(func(ctx context.Context) error {
> 			// KV scan can be used to get the index length.
> 			// TODO (lucy): Switch to using DistSQL to get the count, so that we get
> ```

nit: can we remove this TODO now?
___
*[`pkg/sql/backfill.go` line 1609 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhOAQE5vFEkUJiz8Yw:-NJhOAQE5vFEkUJiz8Yx:b4wyg22) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f0d07a7bc13c802f6d945514d24d1f77f8c2d61/pkg/sql/backfill.go#L1609)):*
> ```Go
> 				tableDesc,
> 				idx,
> 				true,
> ```

nit: ditto for an inline comment.
___
*[`pkg/sql/distsql_physical_planner.go` line 4507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhH9Db23GPZ_gKEc3O:-NJhH9Db23GPZ_gKEc3P:bn4dcej) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/distsql_physical_planner.go#L4507)):*
> ```Go
> 
> // createPlanForIndexScan creates a physical plan for the index scan expression,
> // which will be distributed based on the spans of the indexes. Each partition
> ```

nit: can it scan multiple indexes? My intuition says no, so `s/indexes/index/`.
___
*[`pkg/sql/distsql_physical_planner.go` line 4524 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhHTho15GauZQ2K4eH:-NJhHTho15GauZQ2K4eI:b-fkycx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/distsql_physical_planner.go#L4524)):*
> ```Go
> 
> 	p.ResultRouters = make([]physicalplan.ProcessorIdx, len(spanPartitions))
> 	for i, sp := range spanPartitions {
> ```

Let's replace this loop with `p.AddNoInputStage` function call.
___
*[`pkg/sql/distsql_physical_planner.go` line 4542 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhHttY3uQHcWLwpVkv:-NJhHttY3uQHcWLwpVkw:b-wqinpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/distsql_physical_planner.go#L4542)):*
> ```Go
> 	}
> 	p.PlanToStreamColMap = []int{0, 1, 2}
> 	p.ResultColumns = planColumns(n)
> ```

nit: this line doesn't seem necessary currently (i.e. only needed in the new experimental `distSQLSpecExecFactory`).
___
*[`pkg/sql/index_scan.go` line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJf9JjE6fhow604HUES:-NJhI8AD9qTl0fmrLu5_:bbhitvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/index_scan.go#L37)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The `distSQLSpecExecFactory` should not be returning plan nodes. Take a look at distsql_spec_exec_factory.go. I'd suggest just returning an unimplemented error for now like most other operators. Also, this function should go in that file.
</blockquote></details>

+1 on just returning an error in the new factory.
___
*[`pkg/sql/execinfrapb/flow_diagram.go` line 539 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhIPFZA2AcRgUWVBLJ:-NJhIPFZA2AcRgUWVBLK:bh6p6pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/execinfrapb/flow_diagram.go#L539)):*
> ```Go
> // summary implements the diagramCellType interface.
> func (s *IndexReaderSpec) summary() (string, []string) {
> 	return "IndexReaderSpec", []string{}
> ```

nit: I feel like it'd be good to include the keys (or at least a few) that a particular DistSQL processor is responsible for into this `summary`. Then we'd check the physical planning in some `EXPLAIN (DISTSQL)` tests in `execbuilder` testdata.
___
*[`pkg/sql/execinfrapb/processors_sql.proto` line 1088 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhIYc28bmBDnVy3jFb:-NJhIYc28bmBDnVy3jFc:b227b8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/execinfrapb/processors_sql.proto#L1088)):*
> ```protobuf
>  message IndexReaderSpec {
>   // Table is the table that this index belongs to.
>    optional sqlbase.TableDescriptor table = 1 [(gogoproto.nullable) = false];
> ```

Do we need to have access to the fully-fledged table descriptor? We did a lot of work to not pass the table descriptors in the proto, but this was for SQL processing, maybe it's ok. Also @ajwerner didn't say anything. Still, it might be good to leave a quick comment here as a justification.

Update: do we actually ever use this descriptor? I don't think I saw any usages.
___
*[`pkg/sql/opt/exec/explain/emit.go` line 333 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhJ25M90SORlPjcZvT:-NJhJ25M90SORlPjcZvU:bam11nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/exec/explain/emit.go#L333)):*
> ```Go
> 	windowOp:               "window",
> 	zigzagJoinOp:           "zigzag join",
> 	indexScanOp:            "index scan",
> ```

nit: this list seems almost sorted, let's try not to make it less sorted :smile: 
___
*[`pkg/sql/opt/exec/explain/emit.go` line 943 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhJ9HQ7mKen5uYaUSV:-NJhJ9HQ7mKen5uYaUSW:bdf8mrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/exec/explain/emit.go#L943)):*
> ```Go
> 			ob.Expr("from", a.fromStoreID, nil /* columns */)
> 		}
> 	case indexScanOp:
> ```

nit: add an empty line before this `case` to be in sync with other `case`s.
___
*[`pkg/sql/rowexec/index_scan.go` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhJRlEDI6G2Nv8CGUV:-NJhJRlEDI6G2Nv8CGUW:b-8ulbbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/rowexec/index_scan.go#L24)):*
> ```Go
> )
> 
> type indexScan struct {
> ```

nit: a quick comment would be great.
___
*[`pkg/sql/rowexec/index_scan.go` line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhKXVo0vqF7kyD_ISj:-NJhKXVo0vqF7kyD_ISk:b-8tgdti) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/rowexec/index_scan.go#L26)):*
> ```Go
> type indexScan struct {
> 	execinfra.ProcessorBase
> 	spec         execinfrapb.IndexReaderSpec
> ```

nit: consider storing just `spans` here rather than the whole spec.
___
*[`pkg/sql/rowexec/index_scan.go` line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhJaLn9Ue1RSrvu7Eb:-NJhJaLn9Ue1RSrvu7Ec:b1libpg) ([raw file](https://github.com/cockroach [...]

2023-04-13 20:36 UTC, fqazi reviewed
I'm gonna open a fresh PR since reviewable isn't making it easy to see the changes, but think I got them all sorted out this breather week. Thanks for for the comment @rytaft @yuzefovich 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-:-NSwJUrfC182SrUqXyW9:b7r19ax)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rytaft, and @yuzefovich)

___
*[`-- commits` line 28 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJgGcfkD6-jj9_hX37P):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Will this `crdb_internal.scan` primitive be used for user-facing operations? The comment suggests that it'll be used for index validation, and if there are no other use cases, then I'd imagine users shouldn't see any impact meaning the release note is not necessary, unless the speed of index validation will change or something like that.
</blockquote></details>

It's internal, so I'm gonna leave it out of here for now. The improvement will be visible when validating inverted indexes.
___
*[`pkg/sql/distsql_physical_planner.go` line 4524 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhHTho15GauZQ2K4eH:-NSwCloT0ASASiizXJ5k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/distsql_physical_planner.go#L4524)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Let's replace this loop with `p.AddNoInputStage` function call.
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_physical_planner.go` line 4541 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJf8J6t193SJPSLqUX4:-NSwCnAo7AEvem3Ehoaj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/distsql_physical_planner.go#L4541)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think this should be hardcoded. Also, don't you need to set the merge ordering somewhere?
</blockquote></details>

Done.
___
*[`pkg/sql/execinfrapb/processors_sql.proto` line 1088 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhIYc28bmBDnVy3jFb:-NSwD0nt2jffUevm199c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/execinfrapb/processors_sql.proto#L1088)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Do we need to have access to the fully-fledged table descriptor? We did a lot of work to not pass the table descriptors in the proto, but this was for SQL processing, maybe it's ok. Also @ajwerner didn't say anything. Still, it might be good to leave a quick comment here as a justification.

Update: do we actually ever use this descriptor? I don't think I saw any usages.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/factory.opt` line 781 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJfAdiR-gDzouyyv6ie:-NSwDIQ7CZaIbBhyh2gA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/exec/factory.opt#L781)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This needs a comment
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/statement.go` line 415 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJfCV-PEaT_cW-CKJC-:-NSwDSyU2NO_zTAtmAFI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/exec/execbuilder/statement.go#L415)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think you need to do this. The data source should already have been resolved.

You should be able to do something like:
```
tab := md.Table(indexScan.Table)
```

Take a look at `Builder.buildScan`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/statement.go` line 421 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJfCpUd2DJhYWxPNexl:-NSwDY79ErfUZ-2uVZBA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/exec/execbuilder/statement.go#L421)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this for loop shouldn't be needed either. Take a look at how it's done in `buildScan`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/explain/emit.go` line 333 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhJ25M90SORlPjcZvT:-NSwElaZ-KvMb-UpZ4Hr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/exec/explain/emit.go#L333)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this list seems almost sorted, let's try not to make it less sorted :smile: 
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/explain/emit.go` line 943 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJhJ9HQ7mKen5uYaUSV:-NSwEos08WFe46rP6pOL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/exec/explain/emit.go#L943)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: add an empty line before this `case` to be in sync with other `case`s.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2811 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJg7aiZ-r_DRlsbSXlJ:-NSwErA0C6tThoDsy5Vj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/memo/logical_props_builder.go#L2811)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

We should be able to do better than this. Take a look at `buildScan` for an example.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/memo/statistics_builder.go` line 486 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJg7JeR3AurM0U9worn:-NSwEth08dfpp7qhttAE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/memo/statistics_builder.go#L486)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think we can do a lot better than this. We know how many rows are in the table, so we should be able to get correct stats. Take a look at `colStatScan` and `buildScan` for examples.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/general_funcs.go` line 1110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJgBizoBUvMeGiu95w1:-NSwEw_ABzkXaEnzRX7z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/norm/general_funcs.go#L1110)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You should call ConstructIndexScan here, not MemoizeIndexScan
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/general_funcs.go` line 1141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93536#-NJgAtv7CGMx0D-LtgGn:-NSwF3bpDGvYKhCWxBE2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d0e89c221586953818342f29fd8a72faabb2e5d/pkg/sql/opt/norm/general_funcs.go#L1141)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This isn't actually checking if the args are constant. What if the args are variables? (I think the function above, MakeIndexScanFromZip, will panic in this case). Please add a test to confirm.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/ops/relational.opt` line 1410 at r4](https://reviewable.io/reviews/cockroachdb/cock [...]

2023-04-13 20:36 UTC, closed without merging