split: Redesign the load-based splitter to be consistent with new rebalancing signals.
cockroachdb/cockroach pull request #93838
Opened 2022-12-17 00:29 UTC by KaiSun314

Fixes: #90574

In the current load splitter, we find the split key that best balances the QPS of the left and right sides. As a result, each request is unweighted, since one request contributes one to the QPS. In particular, the load splitter does not differentiate between what kinds of requests they are, how heavy the request is, and what resources these requests consume, which can result in scenarios where QPS is balanced but one side has a lot more work due to a few heavy requests. Moreover, the current load splitter treats requests that contain a split key as “contained”. Optimizing for QPS, contained requests are bad since splitting at a point in a contained request will not help lower the QPS of either side. However, optimizing for other signals like CPU, splitting at a point in a contained request is great as each side will get part of the work of processing that request. This motivates a redesign of the load splitter, one that enables recording weighted requests and considers contained requests in the weight balancing for splitting.

In this PR, we redesign the load-based splitter with the following interface:
1. Record a point key “start” or span “[start, end)” with a weight “w” at a specific time “ts”, where “w” is some measure of load recorded for a span e.g. Record(ts, start, w) or Record(ts, [start, end), w)
2. Find a split key such that the load (i.e. total weight) on the resulting split ranges would be as equal as possible according to the recorded loads above e.g. Key()

To make the current load-based splitter (Finder) weighted, we make the following modifications:
1. Instead of using reservoir sampling, we use weighted reservoir sampling (a simplified version of A-Chao)
2. Remove the contained counter
3. Increment the left and right counters by the weight of the request rather than just 1
4. Treat a weighted range request ([start, end), w) into two weighted point requests (start, w/2) and (end, w/2)

For more details, see
https://docs.google.com/document/d/1bdSxucz-xFzwnxL3fFXNZsRc9Vsht0oO0XuZrz5Iw84/edit#bookmark=id.xjc41tm3jx3x.

Release note (ops change): The load-based splitter has been redesigned to be more consistent with CPU-based rebalancing rather than QPS-based rebalancing to improve range splits.

2022-12-17 00:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/93838)
<!-- Reviewable:end -->

2022-12-19 15:24 UTC, kvoli requested changes
Great stuff.

I left a few comments, these are mostly w.r.t readability.

The algorithm itself looks good.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-:-NJexJDDExHs5CV3-oSj:b-khyflv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/split/decider.go` line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJeqTvUBSLSm3wOjUUl:-NJeqTvUBSLSm3wOjUUm:b-a62jx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/decider.go#L104)):*
> ```Go
> 	loadSplitterMetrics *LoadSplitterMetrics,
> ) {
> 	if randSource == nil {
> ```

What calls this with `nil`? Could you add a comment here explaining or update the callers to always pass a source.
___
*[`pkg/kv/kvserver/split/decider.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJersLx0BVxT-pCkZ7J:-NJersLx0BVxT-pCkZ7K:bozou9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/decider.go#L155)):*
> ```Go
> 		if d.mu.lastQPS >= d.qpsThreshold() {
> 			if d.mu.splitFinder == nil {
> 				d.mu.splitFinder = NewWeightedFinder(now, d.randSource)
> ```

The old `finder` code is still in this commit. What plans do you have for it? This instantiates the weighted finder so does that mean the old code is now unused?

We could either:
1. Completely remove the old code and tests.
2. Mark the old code as deprecated e.g. `DecprecatedFinder` and `deprecated_finder.go`, then add a cluster setting `EnableDeprecatedLBSplitFinder` that defaults to false.
___
*[`pkg/kv/kvserver/split/finder.go` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJer-wG-SVQvVeBo15m:-NJer-wG-SVQvVeBo15n:b-dvs197) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/finder.go#L183)):*
> ```Go
> }
> 
> // NoSplitKeyCauseLogMsg returns a log message containing all of this
> ```

nit: consider rewording this comment, specifically `all` and `this`.
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJeyJjw9oSQvtJMkpOh:-NJeyJjw9oSQvtJMkpOi:b3u3dne) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/weighted_finder.go#L21)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/roachpb"
> )
> ```

nit: Consider adding a block comment above that links the A-Chao paper or Wikipedia. 
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJesiK3BOXqzMTDvlqe:-NJesiK46uFUlVwqqZ-K:b6ecv7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/weighted_finder.go#L29)):*
> ```Go
> }
> 
> type RandSource interface {
> ```

nit: Add comments to these exported structs.
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJet6340nEDI90svG45:-NJet6340nEDI90svG46:b-5ob7xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/weighted_finder.go#L42)):*
> ```Go
> }
> 
> func NewWeightedFinder(startTime time.Time, randSource RandSource) *WeightedFinder {
> ```

Add a comment for this fn.
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJetJj7BmKU475H9vNR:-NJetJj7BmKU475H9vNS:b9qhxcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/weighted_finder.go#L56)):*
> ```Go
> 
> func (f *WeightedFinder) record(key roachpb.Key, weight float64) {
> 	if f == nil {
> ```

When can this condition hit?
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJetZRm2-Dk_8-8XT3T:-NJetZRm2-Dk_8-8XT3U:bl96mcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/weighted_finder.go#L68)):*
> ```Go
> 	} else if f.randSource.Float64() > splitKeySampleSize*weight/f.totalWeight {
> 		for i := range f.samples {
> 			if comp := key.Compare(f.samples[i].key); comp < 0 {
> ```

nit: This is an important piece of code. The comment is good, could you also add a small diagram similar to the RFC for the cases to illustrate `<` and `>=`. 
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJeyBkxDM0KUfmgXQ2y:-NJeyBkxDM0KUfmgXQ2z:b359v1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/weighted_finder.go#L110)):*
> ```Go
> 			continue
> 		}
> 		balanceScore := math.Abs(s.left-s.right) / (s.left + s.right)
> ```

nit: Likewise to above, this is one of  the most important parts of the code. Could you comment an example.
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJewpsJDWwkE1HDIaZq:-NJewpsJDWwkE1HDIaZr:b-7xy27a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/load_based_splitter_test.go#L335)):*
> ```Go
> }
> 
> func TestCompareFinders(t *testing.T) {
> ```

You could change this test to be an example, rather than a unit test - given that there is no assertion atm.

 `Example_Finder()`

see: https://go.dev/blog/examples
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJevcne1HZ6Wi5zp7oU:-NJevcne1HZ6Wi5zp7oV:bia2hiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/load_based_splitter_test.go#L342)):*
> ```Go
> 	runTestMultipleSettings(t, []settings{
> 		{
> 			desc:                    "Weighted Finder",
> ```

Add a more descriptive desc e.g. `weighted/start=uniform/length=uniform`
___
*[`pkg/kv/kvserver/split/weighted_finder_test.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJexWPZ-K8pmbfT0jXj:-NJexWPZ-K8pmbfT0jXk:b20beo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/weighted_finder_test.go#L51)):*
> ```Go
> // TestSplitWeightedFinderKey verifies the Key() method correctly
> // finds an appropriate split point for the range.
> func TestSplitWeightedFinderKey(t *testing.T) {
> ```

Are the tests in this file very similar to the unweighted split tests?

I think adding some weights here is necessary for testing - or add granular assertions to the TestCompareFinders.


<!-- Sent from Reviewable.io -->

2022-12-22 18:44 UTC, KaiSun314 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/split/decider.go` line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJeqTvUBSLSm3wOjUUl:-NJv74xP0JH3jczrfNMl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/decider.go#L104)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

What calls this with `nil`? Could you add a comment here explaining or update the callers to always pass a source.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split/decider.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJersLx0BVxT-pCkZ7J:-NJv76uF1OYRnC--y-O3:b-amq9q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/decider.go#L155)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

The old `finder` code is still in this commit. What plans do you have for it? This instantiates the weighted finder so does that mean the old code is now unused?

We could either:
1. Completely remove the old code and tests.
2. Mark the old code as deprecated e.g. `DecprecatedFinder` and `deprecated_finder.go`, then add a cluster setting `EnableDeprecatedLBSplitFinder` that defaults to false.


</blockquote></details>

Done. Marked the old code as deprecated and added a cluster setting that defaults to true (discussed offline)
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJet6340nEDI90svG45:-NJv7J7M8TjHqebKeJll:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/weighted_finder.go#L42)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Add a comment for this fn.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJetJj7BmKU475H9vNR:-NJv7K8b7lB1iUDJjp4c:b-9gsuf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/weighted_finder.go#L56)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

When can this condition hit?
</blockquote></details>

This condition is probably not hit (we check if the finder is nil in decider.go), but it is there as a safety check I think? This check is in the original finder code, so I also kept the check for the weighted finder
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJewpsJDWwkE1HDIaZq:-NJv7koLADE4TgnKjzTd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/load_based_splitter_test.go#L335)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

You could change this test to be an example, rather than a unit test - given that there is no assertion atm.

 `Example_Finder()`

see: https://go.dev/blog/examples
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split/load_based_splitter_test.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJevcne1HZ6Wi5zp7oU:-NJv7lrC4GJtixQsDdGv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/load_based_splitter_test.go#L342)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Add a more descriptive desc e.g. `weighted/start=uniform/length=uniform`
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split/weighted_finder_test.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NJexWPZ-K8pmbfT0jXj:-NJv7n2iA8hMYpi-jHDU:b-d21i5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e57c3ceb6ce966dd904fd05b8226fb2457979379/pkg/kv/kvserver/split/weighted_finder_test.go#L51)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Are the tests in this file very similar to the unweighted split tests?

I think adding some weights here is necessary for testing - or add granular assertions to the TestCompareFinders.
</blockquote></details>

The tests are similar to the unweighted split tests, but there are some differences that test the differences between the finder and weighted finder

E.g. in TestSplitWeightedFinderKey, we only check the balance score (left and right counter difference).
In TestSplitWeightedFinderRecorder, we record a ranged span with weight 1, which should be split up into a point request with weight 0.5 for the start key and a point request with weight 0.5 for the end key. I think this should test the weights?


<!-- Sent from Reviewable.io -->

2023-01-03 14:40 UTC, kvoli reviewed
Looks great! Updated some naming in the patch.

> Reviewed 1 of 12 files at r2, 2 of 3 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-:-NKs1g7kEk3AFbgePCtj:bhppg90)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/split/decider.go` line 67 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NKrytTv3CLiYEPAX3CJ:-NKrytTv3CLiYEPAX3CK:b-a44srr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c1cfd7ed87e09d554f98267f72fa226df03b2e0/pkg/kv/kvserver/split/decider.go#L67)):*
> ```Go
> }
> 
> var enableDeprecatedLBSplitFinder = settings.RegisterBoolSetting(
> ```

Going back on what I said earlier - changing the name here to be something more specific than deprecated is better. I'll update.
___
*[`pkg/kv/kvserver/split/decider.go` line 68 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NKrzglU67odsGrmuH6-:-NKrzglU67odsGrmuH60:b78xtg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c1cfd7ed87e09d554f98267f72fa226df03b2e0/pkg/kv/kvserver/split/decider.go#L68)):*
> ```Go
> 
> var enableDeprecatedLBSplitFinder = settings.RegisterBoolSetting(
> 	settings.TenantWritable,
> ```

This should be system writable only here, rather than tenant.
___
*[`pkg/kv/kvserver/split/weighted_finder.go` line 100 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93838#-NKrwZt33EsqNgV0WGeJ:-NKrwZt33EsqNgV0WGeK:brgvfv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c1cfd7ed87e09d554f98267f72fa226df03b2e0/pkg/kv/kvserver/split/weighted_finder.go#L100)):*
> ```Go
> 			// f.samples[i].Key).
> 			//
> 			// Suppose we record the following weighted keys:
> ```

This is really great!


<!-- Sent from Reviewable.io -->

2023-01-03 18:06 UTC, kvoli approved these changes
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)



<!-- Sent from Reviewable.io -->

2023-01-03 18:06 UTC, kvoli commented
bors r+

2023-01-03 18:14 UTC, KaiSun314 commented
Thank you so much for the review and for updating the finder name, Austen!

2023-01-03 19:17 UTC, merged