Optexpr
cockroachdb/cockroach pull request #93979
Opened 2022-12-20 15:23 UTC by miretskiy

2022-12-20 15:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/93979)
<!-- Reviewable:end -->

2022-12-20 22:34 UTC, HonoreDB reviewed
> Reviewed 14 of 14 files at r1, 10 of 10 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @miretskiy)

___
*[`pkg/ccl/changefeedccl/event_processing.go` line 322 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJldLcQAlsvOY3BDOHo:-NJldLcR5yPbRQbE891Z:b-drgz9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7bf36e7dce9950d438c33e7565e0afa21dc825/pkg/ccl/changefeedccl/event_processing.go#L322)):*
> ```Go
> 	// Get prev value, if necessary.
> 	prevRow, err := func() (cdcevent.Row, error) {
> 		if keyOnly || !c.details.Opts.GetFilters().WithDiff {
> ```

What about keyOnly feeds with references to cdc_prev in the WHERE clause?
___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 560 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJle6gN2YrGuhrV-mGD:-NJle6gN2YrGuhrV-mGE:b-k68rf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7bf36e7dce9950d438c33e7565e0afa21dc825/pkg/ccl/changefeedccl/cdcevent/event.go#L560)):*
> ```Go
> // to make the order of system columns clear and explicit.
> // In particular, when decoding previous row, we strip table OID column
> // since it makes little sense to include it in the previous row value.
> ```

Can you say more about why this is worth doing? I get that it'll always be the same in prev and current, but what's the harm?
___
*[`pkg/sql/distsql_plan_changefeed.go` line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJlVwaY4jSyb5FVBqhE:-NJlVwaZ8nnCxQP8yhO4:b-6icr0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e2aba5c0ab4cdb81fa9b58cd0454c0fe377a9/pkg/sql/distsql_plan_changefeed.go#L389)):*
> ```Go
> // CDC currently supports primary index only.
> // TODO(yevgeniy): We should be able to use secondary indexes provided
> // the CDC expression access only the columns available in that secondary index.
> ```

nonblocking: Occurs to me just now that we'll need to be opt-in about this to avoid customers shooting themselves in the foot by altering/dropping a secondary index they didn't realize a changefeed was running on, which would probably need to trigger a replan and partial backfill.
___
*[`pkg/sql/parser/sql.y` line 12054 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJlZwp83TRkUCQTRu6r:-NJlZwp83TRkUCQTRu6s:b83w7ss) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e2aba5c0ab4cdb81fa9b58cd0454c0fe377a9/pkg/sql/parser/sql.y#L12054)):*
> ```Yacc
>      $$.val = &tree.IndexFlags{ZigzagIndexIDs: []tree.IndexID{tree.IndexID($4.int64())}}
>   }
> | FAMILY '=' '[' iconst64 ']'
> ```

Would it cause ambiguities if we made this `FAMILY <familyname>` to be consistent with other places we specify a family (column definitions and regular changefeeds)? This could be a mildly useful bit of syntax to actually surface and support (at point) for people who want to ensure certain statements are only touching one family.


<!-- Sent from Reviewable.io -->

2022-12-20 23:37 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @mgartner)

___
*[`pkg/ccl/changefeedccl/event_processing.go` line 322 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJldLcQAlsvOY3BDOHo:-NJlsiHZ3sUocTGn-mzv:bdcv6kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7bf36e7dce9950d438c33e7565e0afa21dc825/pkg/ccl/changefeedccl/event_processing.go#L322)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

What about keyOnly feeds with references to cdc_prev in the WHERE clause?
</blockquote></details>

Good point!
___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 560 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJle6gN2YrGuhrV-mGD:-NJlsntk7mCifN-ipjOv:bexbb8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7bf36e7dce9950d438c33e7565e0afa21dc825/pkg/ccl/changefeedccl/cdcevent/event.go#L560)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Can you say more about why this is worth doing? I get that it'll always be the same in prev and current, but what's the harm?
</blockquote></details>

It just looked so weird.  There is really no other reason except that it makes little sense to me.
I of course, used to put it unconditionally, but felt it was annoying enough that I wanted it gone.
In reality, I wanted to have the same rules applied to cdc_prev as to the regular star expansion.  Alas, that's not that simple, and so I settled on this to remove at least part of the thing that's annoying to me.
If you feel strongly, I can bring back old behavior.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJlVwaY4jSyb5FVBqhE:-NJltD7n78OSQcpvyPbb:bcvj0i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e2aba5c0ab4cdb81fa9b58cd0454c0fe377a9/pkg/sql/distsql_plan_changefeed.go#L389)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

nonblocking: Occurs to me just now that we'll need to be opt-in about this to avoid customers shooting themselves in the foot by altering/dropping a secondary index they didn't realize a changefeed was running on, which would probably need to trigger a replan and partial backfill.
</blockquote></details>

I don't think drop of a secondary index would need to trigger backfill.  Once plan is made (and we only use primary index for this), sec index does not matter..
___
*[`pkg/sql/parser/sql.y` line 12054 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJlZwp83TRkUCQTRu6r:-NJltLn940QzGSTIfBry:bm4wexl) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e2aba5c0ab4cdb81fa9b58cd0454c0fe377a9/pkg/sql/parser/sql.y#L12054)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Would it cause ambiguities if we made this `FAMILY <familyname>` to be consistent with other places we specify a family (column definitions and regular changefeeds)? This could be a mildly useful bit of syntax to actually surface and support (at point) for people who want to ensure certain statements are only touching one family.
</blockquote></details>

I don't think it would; I was thinking of keeping the name, but realized that it's not necessary since I never serialize this representation anyway -- family index flag added dynamically once we know which family we have the event for.


<!-- Sent from Reviewable.io -->

2022-12-28 12:57 UTC, miretskiy commented
@HonoreDB can I have another pass on this? @mgartner let me know if you have any q's re this pr.

2022-12-28 21:56 UTC, mgartner commented
Apologies for the delay. Please wait until I have a chance to take a look before merging.

2022-12-28 21:57 UTC, miretskiy commented
Ack. No worries

2023-01-03 20:43 UTC, mgartner requested changes
This approach seems to work well, but I do have a concern about VIRTUAL computed columns.

How does CDC currently work with VIRTUAL computed columns? Those don't belong to any families, so with this approach we'd never be able to access them.

> Reviewed 5 of 14 files at r1, 1 of 10 files at r3, 2 of 13 files at r6, 13 of 13 files at r8, 10 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-:-NKtDDLk8y52fzV84pax:b-ysbopi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @miretskiy)

___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 234 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtMNJK-2DN_ZFbfV4T:-NKtMNJK-2DN_ZFbfV4U:btg0dwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/650cbbcdc9d3db1542ed8abf1d0771df0aaf785f/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L234)):*
> ```Go
> ) ([]*types.T, catalog.TableColMap, error) {
> 	numCols := len(ed.ResultColumns()) + len(colinfo.AllSystemColumnDescs)
> 	inputTypes := make([]*types.T, numCols)
> ```

You need the length to be `len(ed.ResultColumns())` and the capacity to be `numCols`, right?
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 242 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtMUGQDaNtBR3MDi5P:-NKtMUGQDaNtBR3MDi5Q:b5lfzk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/650cbbcdc9d3db1542ed8abf1d0771df0aaf785f/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L242)):*
> ```Go
> 		}
> 		inputCols.Set(col.GetID(), i)
> 		inputTypes[i] = c.Typ
> ```

nit: consider using append here so that you can make the length 0 above and the capacity `numCols` - feels simpler and less error-prone.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 52 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtAWYZ--6jpeYlG9sI:-NKtAWYZ--6jpeYlG9sJ:b-lrrn9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/854f0a9f86f0a7c69daa0b73e051b7d1bb254fc9/pkg/ccl/changefeedccl/cdceval/validation.go#L52)):*
> ```Go
> 	// Configure index flags to restrict access to specific column family.
> 	sc := *n.SelectClause
> 	sc.From.Tables = append(tree.TableExprs(nil), n.SelectClause.From.Tables...)
> ```

nit: Why use `append` here rather than `sc.From.Tables = tree.TableExprs{&tree.AliasedTableExpr{ ... }}`?
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 55 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKt9MHk6dl-rkAIKvO-:-NKt9MHk6dl-rkAIKvO0:bwhsy6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/854f0a9f86f0a7c69daa0b73e051b7d1bb254fc9/pkg/ccl/changefeedccl/cdceval/validation.go#L55)):*
> ```Go
> 	sc.From.Tables[0] = &tree.AliasedTableExpr{
> 		Expr:       n.SelectClause.From.Tables[0],
> 		IndexFlags: &tree.IndexFlags{FamilyID: &n.desc.FamilyID},
> ```

These should really be renamed to something like `Hints` instead of `IndexFlags`. No need to change that in this PR though. I created #94647 to track this.
___
*[`pkg/sql/opt/cat/catalog.go` line 79 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtD4JQ17e8pt_ROh7j:-NKtD4JQ17e8pt_ROh7k:b-o4uwuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/854f0a9f86f0a7c69daa0b73e051b7d1bb254fc9/pkg/sql/opt/cat/catalog.go#L79)):*
> ```Go
> 
> 	// IndexFlag contain index flags specified when accessing table (if any).
> 	IndexFlags *tree.IndexFlags
> ```

The only "index flag" that is needed is a family, so it seems like overkill to bring in all of these flags.
___
*[`pkg/sql/opt/optbuilder/util.go` line 638 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtCzUz9GboqLeM-Wla:-NKtCzUz9GboqLeM-Wlb:by63j56) ([raw file](https://github.com/cockroachdb/cockroach/blob/854f0a9f86f0a7c69daa0b73e051b7d1bb254fc9/pkg/sql/opt/optbuilder/util.go#L638)):*
> ```Go
> // the fully qualified name.
> func (b *Builder) resolveDataSource(
> 	tn *tree.TableName, flags cat.Flags,
> ```

Do we need all of `cat.Flags` here? Can we just pass the privilege and family, if there is one?


<!-- Sent from Reviewable.io -->

2023-01-03 22:39 UTC, miretskiy reviewed
Your concerns about VIRTUAL computed columns is valid.  As it stands right now, virtual columns
are not supported by CDC, and we have issues/todo's to address that.
So, as far as this PR is concerned, status quo is maintained.

We would have to do something along the lines of walking virtual computed column expressions
and determining if it's valid in the context of the target family.  Or perhaps, we just let optimizer
error out and figure out what to do in this case (figure out from the UX perspective).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-:-NKtfxwD6ZreLLoIKSqq:b8uvhsh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @mgartner)

___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 234 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtMNJK-2DN_ZFbfV4T:-NKth70y2rio8070VDid:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/650cbbcdc9d3db1542ed8abf1d0771df0aaf785f/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L234)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You need the length to be `len(ed.ResultColumns())` and the capacity to be `numCols`, right?
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/cdceval/expr_eval.go` line 242 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtMUGQDaNtBR3MDi5P:-NKthHeH7_9uMb0hFU2y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/650cbbcdc9d3db1542ed8abf1d0771df0aaf785f/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L242)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: consider using append here so that you can make the length 0 above and the capacity `numCols` - feels simpler and less error-prone.
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/cdceval/validation.go` line 52 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtAWYZ--6jpeYlG9sI:-NKthW6R0aKjaSkYkz9i:b-frs67v) ([raw file](https://github.com/cockroachdb/cockroach/blob/854f0a9f86f0a7c69daa0b73e051b7d1bb254fc9/pkg/ccl/changefeedccl/cdceval/validation.go#L52)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Why use `append` here rather than `sc.From.Tables = tree.TableExprs{&tree.AliasedTableExpr{ ... }}`?
</blockquote></details>

Thanks for calling this out.  Arguably, this should have been done in the other PR (https://github.com/cockroachdb/cockroach/pull/94459) I have for review; but I think it makes sense to do it here.  Basically, I don't want to mutate underlying selectClause in any way.
I left a comment to explain why.
___
*[`pkg/sql/opt/cat/catalog.go` line 79 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtD4JQ17e8pt_ROh7j:-NKtjht553zQb_hInqgF:b-upd13o) ([raw file](https://github.com/cockroachdb/cockroach/blob/854f0a9f86f0a7c69daa0b73e051b7d1bb254fc9/pkg/sql/opt/cat/catalog.go#L79)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The only "index flag" that is needed is a family, so it seems like overkill to bring in all of these flags.
</blockquote></details>

Perhaps; but I think I do need to be able to tell if this option was set ; I would need to specify *FamilyID as a index flag -- which is fine, but also seems like a bit more work to set; i.e.
instead of:
```
ds, depName := b.resolveDataSourceRef(source,
			cat.Flags{RequiredPrivilege: privilege.SELECT, IndexFlags: indexFlags})
```
It would have to be something like:

```
familyIDFromIndexFlags := func() *FamilyID {
   if indexFlags != nil {
      return indexFlags.FamilyID
  }
  return nil
}
ds, depName := b.resolveDataSourceRef(source,
			cat.Flags{RequiredPrivilege: privilege.SELECT, FamilyID: familyIDFromIndexFlags()})
```

So..... I guess, how strongly do you feel about this.
___
*[`pkg/sql/opt/optbuilder/util.go` line 638 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtCzUz9GboqLeM-Wla:-NKtlUMqCswNSjbV4YSc:bxdk3bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/854f0a9f86f0a7c69daa0b73e051b7d1bb254fc9/pkg/sql/opt/optbuilder/util.go#L638)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do we need all of `cat.Flags` here? Can we just pass the privilege and family, if there is one?
</blockquote></details>

Your question/request is a perfectly valid one -- normally, that'd be my preference too.
There are two reasons why I chose to pass cat.Flags:
1. This method makes a call to `ds, resName, err := b.catalog.ResolveDataSource(b.ctx, flags, tn)` which takes flags anyway (`catalog.Catalog` interface)
2. I felt that passing in *FamilyID would be pretty strange considering that (at least right now) CDC is the only user.

(I lied: it's more of a 3 reasons, but 3rd one is more of a pet peeve  --  I don't like adding `nil /* familyID */` nil arguments with comment at call sites -- I think cat.Flags{} is explicit, clearer, and doesn't require silly trailing comments).

If I haven't convinced you and you feel strongly about this, please let me know.


<!-- Sent from Reviewable.io -->

2023-01-04 16:20 UTC, mgartner reviewed
> Reviewed 12 of 12 files at r10, 11 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @miretskiy)

___
*[`pkg/sql/opt/optbuilder/util.go` line 638 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NKtCzUz9GboqLeM-Wla:-NKxVpoq8SlG_mF04-Cq:b-ox361t) ([raw file](https://github.com/cockroachdb/cockroach/blob/854f0a9f86f0a7c69daa0b73e051b7d1bb254fc9/pkg/sql/opt/optbuilder/util.go#L638)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Your question/request is a perfectly valid one -- normally, that'd be my preference too.
There are two reasons why I chose to pass cat.Flags:
1. This method makes a call to `ds, resName, err := b.catalog.ResolveDataSource(b.ctx, flags, tn)` which takes flags anyway (`catalog.Catalog` interface)
2. I felt that passing in *FamilyID would be pretty strange considering that (at least right now) CDC is the only user.

(I lied: it's more of a 3 reasons, but 3rd one is more of a pet peeve  --  I don't like adding `nil /* familyID */` nil arguments with comment at call sites -- I think cat.Flags{} is explicit, clearer, and doesn't require silly trailing comments).

If I haven't convinced you and you feel strongly about this, please let me know.
</blockquote></details>

These are valid points.

But, thinking about this a bit more, I don't agree that we should intertwine this family hinting with data source resolution. They are very separate ideas, and mashing them together feels wrong.

Can we instead set the family hint as field of `cdcOptCatalog` here: https://github.com/cockroachdb/cockroach/blob/b5cb99073a0dee584d7a4ca126f8a060cc5f4dd1/pkg/sql/distsql_plan_changefeed.go#L74-L77

Then we'd avoid the changes to the resolver interface function signatures and the new hint syntax (which is good because it doesn't work outside of CDC at all).


<!-- Sent from Reviewable.io -->

2023-01-04 17:07 UTC, HonoreDB approved these changes
> Reviewed 1 of 13 files at r8, 1 of 12 files at r10, 8 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @miretskiy)

___
*[`pkg/ccl/changefeedccl/cdcevent/event.go` line 560 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJle6gN2YrGuhrV-mGD:-NKxiVED6ZSY3TmrZg13:b-gpchxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7bf36e7dce9950d438c33e7565e0afa21dc825/pkg/ccl/changefeedccl/cdcevent/event.go#L560)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

It just looked so weird.  There is really no other reason except that it makes little sense to me.
I of course, used to put it unconditionally, but felt it was annoying enough that I wanted it gone.
In reality, I wanted to have the same rules applied to cdc_prev as to the regular star expansion.  Alas, that's not that simple, and so I settled on this to remove at least part of the thing that's annoying to me.
If you feel strongly, I can bring back old behavior.
</blockquote></details>

If I understand correctly, this column also wouldn't be there in a regular row tuple if you made it from a * expansion? That seems fine then, my only concern was making functions that work on a regular row tuple break surprisingly on cdc_prev.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJlVwaY4jSyb5FVBqhE:-NKxjQ3c2yBXb_vuu6bI:b-ad2xdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e2aba5c0ab4cdb81fa9b58cd0454c0fe377a9/pkg/sql/distsql_plan_changefeed.go#L389)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't think drop of a secondary index would need to trigger backfill.  Once plan is made (and we only use primary index for this), sec index does not matter..
</blockquote></details>

This was in response to your code comment that we should be able to use secondary indexes--if we're actually using a secondary index, messing with it would mess with the changefeed.


<!-- Sent from Reviewable.io -->

2023-01-04 17:11 UTC, miretskiy commented
> Can we instead set the family hint as field of `cdcOptCatalog` here:

All I can say is: "doh"... Yes, we can.  There is a bit of logic that needs to happen (namely, looking at select statement to see of tables[0] has index flag set), but it is localized.  Very nice.  I reverted changes to opt related stuff.
Thanks for pushing on this.

2023-01-04 17:15 UTC, miretskiy commented
> If I understand correctly, this column also wouldn't be there in a regular row tuple if you made it from a * expansion? That seems fine then, my only concern was making functions that work on a regular row tuple break surprisingly on cdc_prev.

Yes, I believe that's the case; * expansion does not expand hidden columns.  Say more re "functions that work on regular row tuple that break on cdc_prev"?  I want to make sure I fully understand your concern.

2023-01-05 17:25 UTC, HonoreDB reviewed
>Say more re "functions that work on regular row tuple that break on cdc_prev"?
I think it's probably desirable that any expression or custom function that can take `*` as an input can also take `(cdc_prev).*` as an input, so that it's easy to write projections that you call on both the before and after values. So I don't think any metadata that's available in * should be removed from cdc_prev, even if it's guaranteed to be the same in both.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-:-NL1xJZr831JlLc6cnuq:b-jfd90v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @miretskiy)



<!-- Sent from Reviewable.io -->

2023-01-05 19:03 UTC, miretskiy commented
> I think it's probably desirable that any expression or custom function that can take `*` as an input can also take `(cdc_prev).*` as an input, so that it's easy to write projections that you call on both the before and after values. So I don't think any metadata that's available in * should be removed from cdc_prev, even if it's guaranteed to be the same in both.

I'm not sure anything prevents you from passing `(cdc_prev).*`; It is true that this * expansion in cdc_prev is a bit different; but it was different from the get go -- namely, there is no way to have a hidden tuple column like you can have in a table...  I would have loved cdc_prev to behave identically -- and maybe some day it will. I just think it's fine to exclude some columns; of course, I could just re-add it back if you feel strongly. Let me know.

2023-01-06 02:48 UTC, miretskiy commented
@mgartner let me know if you have more q's/comments.

2023-01-06 14:53 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Just a few minor nits.

> Reviewed 6 of 6 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-:-NL6Zdld9k7c2sMGuPfi:b-f7du1v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB and @miretskiy)

___
*[`-- commits` line 26 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NL6YpsW9_6TGC9raNIf):*
I think this explanation is now out-of-date, the optimizer isn't as involved anymore. Can you update it?
___
*[`pkg/ccl/changefeedccl/cdcevent/rowfetcher_cache.go` line 241 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NL6XbMfDTKcmWpjcVuE:-NL6XbMfDTKcmWpjcVuF:b8tdhiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/93ea83a992f710f8f60c6b816b8f008b892a0bbe/pkg/ccl/changefeedccl/cdcevent/rowfetcher_cache.go#L241)):*
> ```Go
> 	}
> 
> 	//Add system columns.
> ```

nit: add space after `//`
___
*[`pkg/sql/parser/sql.y` line 12176 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NL6Z7Of3N6Yrjqxf-pw:-NL6Z7Of3N6Yrjqxf-px:b3lyj0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/93ea83a992f710f8f60c6b816b8f008b892a0bbe/pkg/sql/parser/sql.y#L12176)):*
> ```Yacc
>      $$.val = &tree.IndexFlags{ZigzagIndexIDs: []tree.IndexID{tree.IndexID($4.int64())}}
>   }
> | FAMILY '=' '[' iconst64 ']'
> ```

This syntax has no effect on regular queries, so they should probably error with a message like "the FAMILY hint is only allowed in changefeed expressions". Can you create an issue to track that?

Long term, we might want to support this FAMILY hint in all statements, which would move the logic into the optimizer and remove the catalog faking you're doing in this PR. But for now, I think it's better to not open up this hint to general queries.


<!-- Sent from Reviewable.io -->

2023-01-06 17:25 UTC, HonoreDB commented
> I just think it's fine to exclude some columns; of course, I could just re-add it back if you feel strongly. Let me know.
I do not feel strongly.

2023-01-08 22:42 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93979)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB and @mgartner)

___
*[`-- commits` line 26 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NL6YpsW9_6TGC9raNIf):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think this explanation is now out-of-date, the optimizer isn't as involved anymore. Can you update it?
</blockquote></details>

Hmm... I kinda of think of the stuff under sql as optimizer.  Point is: it's not strictly CDC.
But I'll update.
___
*[`pkg/sql/distsql_plan_changefeed.go` line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NJlVwaY4jSyb5FVBqhE:-NLIWILyEifJaIbOc0VU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/543e2aba5c0ab4cdb81fa9b58cd0454c0fe377a9/pkg/sql/distsql_plan_changefeed.go#L389)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

This was in response to your code comment that we should be able to use secondary indexes--if we're actually using a secondary index, messing with it would mess with the changefeed.
</blockquote></details>

Done.
___
*[`pkg/sql/parser/sql.y` line 12176 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/93979#-NL6Z7Of3N6Yrjqxf-pw:-NLIXN74DOuWxKy-MHDY:b-trz22t) ([raw file](https://github.com/cockroachdb/cockroach/blob/93ea83a992f710f8f60c6b816b8f008b892a0bbe/pkg/sql/parser/sql.y#L12176)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This syntax has no effect on regular queries, so they should probably error with a message like "the FAMILY hint is only allowed in changefeed expressions". Can you create an issue to track that?

Long term, we might want to support this FAMILY hint in all statements, which would move the logic into the optimizer and remove the catalog faking you're doing in this PR. But for now, I think it's better to not open up this hint to general queries.
</blockquote></details>

I added a check in the indexFlags.Check method to always return an error -- this flag is currently set
internally by CDC, and so it is safe to return an error if somebody specifies this hint in the query.

Issue filed: https://github.com/cockroachdb/cockroach/issues/94900


<!-- Sent from Reviewable.io -->

2023-01-09 16:24 UTC, miretskiy commented
bors r+

2023-01-09 19:04 UTC, miretskiy commented
bors r+

2023-01-09 23:22 UTC, miretskiy commented
Bors r+

2023-01-10 11:17 UTC, miretskiy commented
Bors r+

2023-01-10 12:44 UTC, miretskiy commented
Bors r+

2023-01-10 14:23 UTC, merged