build: use llvm-nm in place of nm
cockroachdb/cockroach pull request #94196
Opened 2022-12-23 00:59 UTC by nicktrav

Currently, the build containers contain the standard GNU version of `nm`. This version of the tool is sufficient for the current build, which does not need to directly interact with binaries cross compiled for platforms other than Linux.

When pulling in the latest version of `jemalloc` (`5.3.0`), builds for cross compiled for macOS requiring using `nm` to perform name mangling. As the GNU version of `nm` in the Linux build container does not know how to read Macho-O binaries, the name mangling does not occur, and the Cockroach binary will fail to link.

Use the version of `nm` that ships with LLVM (`llvm-nm`) in place of GNU `nm`. This version of `nm` can understand Macho-O binaries and perform the name mangling as intended, resolving the linking issue.

Touches #83289.

Informs #93045.

Release note: None.

2022-12-23 01:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/94196)
<!-- Reviewable:end -->

2023-01-03 21:13 UTC, rickystewart commented
LGTM, currently I'm building and pushing the new images.

2023-01-04 01:04 UTC, rickystewart requested changes
Can you apply the following changes to pull in the new version of these images?

```
diff --git a/build/.bazelbuilderversion b/build/.bazelbuilderversion
index 99b4de6f456..5a75e14d136 100644
--- a/build/.bazelbuilderversion
+++ b/build/.bazelbuilderversion
@@ -1 +1 @@
-cockroachdb/bazel:20221215-030250
\ No newline at end of file
+cockroachdb/bazel:20230103-211452
\ No newline at end of file
diff --git a/build/builder.sh b/build/builder.sh
index f81788f969d..970a2e5fbce 100755
--- a/build/builder.sh
+++ b/build/builder.sh
@@ -3,7 +3,7 @@
 set -euo pipefail
 
 image=cockroachdb/builder
-version=20221219-170552
+version=20230103-212639
 
 function init() {
   docker build --tag="${image}" "$(dirname "${0}")/builder"

```

2023-01-04 16:17 UTC, rickystewart approved these changes

2023-01-04 17:23 UTC, nicktrav commented
TFTR!

bors r=rickystewart

2023-01-04 17:57 UTC, nicktrav commented
bors retry

2023-01-04 18:57 UTC, nicktrav commented
bors r=rickystewart

2023-01-04 21:37 UTC, merged