changefeedccl: Bring changefeed transformations out of preview
cockroachdb/cockroach pull request #94806
Opened 2023-01-05 23:13 UTC by miretskiy

Add a mechanism to migrate changefeed expressions
created in 22.2 clusters to be compatible with
recently introduced changes.

Old changefeed expressions are transparently rewritten,
and the changefeed job record automatically updated
once cluster upgrade has been finalized.

A warning message may be logged if the rewritten expression
is inefficient.

The automatic update might still fail.  The end users
are encourraged to closely monitor the health of the
changefeeds during the upgrade, and recreate any failed
changefeeds as needed.

Epic: [CRDB-17161](https://cockroachlabs.atlassian.net/browse/CRDB-17161)

Release note (enterprise change): Changefeed transformations
introduced in 22.2 release in preview mode are no longer
experimental.  This feature can now be considered
to be fully production ready.

2023-01-05 23:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/94806)
<!-- Reviewable:end -->

2023-01-05 23:15 UTC, miretskiy commented
@HonoreDB Only top 2 commits.

2023-01-06 17:24 UTC, HonoreDB requested changes
> Reviewed 10 of 10 files at r1, 11 of 11 files at r2, 17 of 17 files at r3, 16 of 16 files at r4, 11 of 11 files at r5, 2 of 2 files at r6, 11 of 11 files at r7, 7 of 7 files at r8, 3 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94806)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @samiskin)

___
*[`pkg/ccl/changefeedccl/metrics.go` line 387 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/94806#-NL70x_ZAAqrOKl0o9QK:-NL70x_ZAAqrOKl0o9QL:b-xi2gee) ([raw file](https://github.com/cockroachdb/cockroach/blob/f601780864e79d6061372f847b56df223b40e128/pkg/ccl/changefeedccl/metrics.go#L387)):*
> ```Go
> 	metaChangefeedFilteredMessages := metric.Metadata{
> 		Name:        "changefeed.filtered_messages",
> 		Help:        "Messages filtered out by all feeds",
> ```

Maybe specify "filtered out in memory" in the description and I think also in the name. I assume this doesn't include "messages" that got filtered out by the range constraints before they even became messages which is going to be confusing to the user (if you do N writes, EmittedMessages+FilteredMessages can be less than N).
___
*[`pkg/ccl/changefeedccl/cdceval/compat.go` line 29 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/94806#-NL74BFZ9UI1E4lH7gi6:-NL74BFZ9UI1E4lH7gi7:b1zfquq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fcf7410da33d6223f1428f8d2728e7568d648ce/pkg/ccl/changefeedccl/cdceval/compat.go#L29)):*
> ```Go
> 			// Replace this call with a call to row_to_json((cdc_prev).*)
> 			if n, ok := t.Func.FunctionReference.(*tree.UnresolvedName); ok && n.Parts[0] == "cdc_prev" {
> 				rowToJSON := &tree.FuncExpr{
> ```

could this be a singleton?
___
*[`pkg/jobs/jobspb/jobs.proto` line 936 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/94806#-NL74puP30Ioop4Amh8t:-NL74puP30Ioop4Amh8u:b-5guhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f601780864e79d6061372f847b56df223b40e128/pkg/jobs/jobspb/jobs.proto#L936)):*
> ```protobuf
> 
>   string select = 10;
>   sessiondatapb.SessionData session_data = 11 [(gogoproto.nullable) = false];
> ```

I'm not sure this change is backwards-compatible, is it meant to be? Non-nullable fields are serialized differently I think.


<!-- Sent from Reviewable.io -->

2023-01-09 14:09 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94806)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @samiskin)

___
*[`pkg/ccl/changefeedccl/metrics.go` line 387 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/94806#-NL70x_ZAAqrOKl0o9QK:-NLLpq_41GS8a2Y8RCiw:bqm6edk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f601780864e79d6061372f847b56df223b40e128/pkg/ccl/changefeedccl/metrics.go#L387)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Maybe specify "filtered out in memory" in the description and I think also in the name. I assume this doesn't include "messages" that got filtered out by the range constraints before they even became messages which is going to be confusing to the user (if you do N writes, EmittedMessages+FilteredMessages can be less than N).
</blockquote></details>

i'd rather not add memory bit; but you do bring up a good point; alas, w/out explain statement, there
is no way to tell how many were filtered.  I've expanded help message a bit to at least mention this.
___
*[`pkg/ccl/changefeedccl/cdceval/compat.go` line 29 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/94806#-NL74BFZ9UI1E4lH7gi6:-NLLr6N08oT-WNuA9TTS:b-7b7cv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fcf7410da33d6223f1428f8d2728e7568d648ce/pkg/ccl/changefeedccl/cdceval/compat.go#L29)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

could this be a singleton?
</blockquote></details>

I'm not sure tbh... But I'm honestly not worried about this.
___
*[`pkg/jobs/jobspb/jobs.proto` line 936 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/94806#-NL74puP30Ioop4Amh8t:-NLLrIYg4jy1oLik4y14:b-qc120g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f601780864e79d6061372f847b56df223b40e128/pkg/jobs/jobspb/jobs.proto#L936)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I'm not sure this change is backwards-compatible, is it meant to be? Non-nullable fields are serialized differently I think.
</blockquote></details>

Sure; but I think it's fine -- session data was added in prior PRs -- and arguably, I should have
added version gate, but I didn't.  Anyway, that code was never released, so I think it's fine to make this change now.


<!-- Sent from Reviewable.io -->

2023-01-11 15:20 UTC, abarganier commented
New metric & the new addition to the chart catalog LGTM

2023-01-11 23:45 UTC, miretskiy commented
@HonoreDB -- want to make sure you saw recent updates...

2023-01-12 16:03 UTC, HonoreDB approved these changes
> Reviewed 46 of 46 files at r10, 7 of 43 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94806)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @samiskin)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1400 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/94806#-NLahThJ4Kx38ZKUP1jZ:-NLahThJ4Kx38ZKUP1j_:b1aca7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f20423138ab46fcdd8d19f16f84e9f7de1ed70/pkg/ccl/changefeedccl/changefeed_stmt.go#L1400)):*
> ```Go
> 
> 	// Job record upgraded.  Return transient error to reload job record and retry.
> 	if newExpression == oldExpression {
> ```

I think safer to compare tree.AsString before and after than directly compare pointers?
___
*[`pkg/ccl/changefeedccl/metrics.go` line 387 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/94806#-NL70x_ZAAqrOKl0o9QK:-NLaez0n-BfM8Iz2Koax:bfs8rxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f601780864e79d6061372f847b56df223b40e128/pkg/ccl/changefeedccl/metrics.go#L387)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

i'd rather not add memory bit; but you do bring up a good point; alas, w/out explain statement, there
is no way to tell how many were filtered.  I've expanded help message a bit to at least mention this.
</blockquote></details>

I agree there's no way to efficiently tell right now. I'm not sure "the range constraints" communicates this to a non-roacher, would "due to primary key constraints in WHERE clauses" be reasonably accurate?


<!-- Sent from Reviewable.io -->

2023-01-12 22:02 UTC, miretskiy commented
> to primary key constraints in WHERE clauses

done.

2023-01-12 22:02 UTC, miretskiy commented
> I think safer to compare tree.AsString before and after than directly compare pointers?

I think it's fine; walk methods compare pointers when they need to determine if something changed.

2023-01-12 22:03 UTC, merged

2023-01-12 22:03 UTC, miretskiy commented
Argh; accidentally merged w/out updates to doc string.