storage: Add support for TargetBytes for resolve intent + range cmd
cockroachdb/cockroach pull request #94814
Opened 2023-01-06 05:38 UTC by KaiSun314

Informs: https://github.com/cockroachdb/cockroach/issues/77228

Intent resolution batches are sequenced on raft and each batch can
consist of 100-200 intents. If an intent key or even value in some cases
are large, it is possible that resolving all intents in the batch would
result in a raft command size exceeding the max raft command size
kv.raft.command.max_size.

To address this, we add support for TargetBytes in resolve intent and
resolve intent range commands, allowing us to stop resolving intents in
the batch as soon as we exceed the TargetBytes max bytes limit.

Adding support for byte size pagination for intent resolver and
RequestBatcher is added in PR https://github.com/cockroachdb/cockroach/pull/92268.

We also add support for pagination in synchronous intent resolution
(EndTxn).

Release note (ops change): Added support for a byte limit on resolve
intent and resolve intent range raft commands to prevent such commands
from exceeding the max raft command size.

2023-01-06 05:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/94814)
<!-- Reviewable:end -->

2023-01-06 05:43 UTC, KaiSun314 commented
The second commit `storage: Add support for TargetBytes for resolve intent + range cmd` is rebased on top of the first commit `storage: Refactor resolve write intent options`. Please only review the second commit. Thank you so much in advance!

2023-01-09 22:21 UTC, sumeerbhola requested changes, later dismissed
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @KaiSun314, and @nvanbenschoten)

___
*[`pkg/storage/mvcc.go` line 3994 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLN_fbQ3og5JbtjiyWW:-NLN_fbQ3og5JbtjiyWX:b-75s8fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a95bb299c244288c889114ac013ab0200c415bc3/pkg/storage/mvcc.go#L3994)):*
> ```Go
> // parameter. ResolveWriteIntent will skip write intents of other txns.
> //
> // An opts.TargetBytes of -1 means resolve nothing and returns the intent as
> ```

nit: of < 0 means ...
___
*[`pkg/storage/mvcc.go` line 4039 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLNaBKP7ySTmg599gle:-NLNaBKP7ySTmg599glf:b-rt5fy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a95bb299c244288c889114ac013ab0200c415bc3/pkg/storage/mvcc.go#L4039)):*
> ```Go
> 	}))
> 	iterAndBuf.iter.SeekIntentGE(intent.Key, intent.Txn.ID)
> 	beforeBytes := rw.BufferedSize()
> ```

Consider adding a code comment that production code will be using a buffered writer, which makes the `numBytes` calculation accurate. Also worth stating that an inaccurate `numBytes` (like 0, in case of an unbuffered writer) does not affect any safety properties of the database.
___
*[`pkg/storage/mvcc.go` line 4806 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLNb1Tp5jg1HY_KE9BW:-NLNb1Tp5jg1HY_KE9BX:b-fvylbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a95bb299c244288c889114ac013ab0200c415bc3/pkg/storage/mvcc.go#L4806)):*
> ```Go
> // ResolveWriteIntentRange will skip write intents of other txns.
> //
> // An opts.MaxKeys of zero means unbounded. An opts.MaxKeys of -1 means resolve
> ```

nit: of < 0 means
___
*[`pkg/storage/mvcc.go` line 4808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLNb7Tm2MFQILo_nNxB:-NLNb7Tm2MFQILo_nNxC:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/a95bb299c244288c889114ac013ab0200c415bc3/pkg/storage/mvcc.go#L4808)):*
> ```Go
> // An opts.MaxKeys of zero means unbounded. An opts.MaxKeys of -1 means resolve
> // nothing and returns the entire intent span as the resume span. An
> // opts.TargetBytes of 0 means no byte limit. An opts.TargetBytes of -1 means
> ```

ditto
___
*[`pkg/storage/mvcc.go` line 4812 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLNbUEF8R7p7Ig2lELc:-NLNbUEF8R7p7Ig2lELd:bsj5hjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a95bb299c244288c889114ac013ab0200c415bc3/pkg/storage/mvcc.go#L4812)):*
> ```Go
> // opts.TargetBytes > 0, then resolve intents in the range until the number of
> // bytes added to the write batch by intent resolution exceeds
> // opts.TargetBytes.
> ```

Can we have a situation where resolving one intent costs `kv.raft.command.max_size/2+1`, so we resolve one intent, are below the target size and so resolve the second and now `bytesExceeded` becomes true, but now it's too late?


<!-- Sent from Reviewable.io -->

2023-01-10 15:08 UTC, KaiSun314 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 4039 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLNaBKP7ySTmg599gle:-NLRDAyx68i5JrZaLVsC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a95bb299c244288c889114ac013ab0200c415bc3/pkg/storage/mvcc.go#L4039)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Consider adding a code comment that production code will be using a buffered writer, which makes the `numBytes` calculation accurate. Also worth stating that an inaccurate `numBytes` (like 0, in case of an unbuffered writer) does not affect any safety properties of the database.
</blockquote></details>

Done.
___
*[`pkg/storage/mvcc.go` line 4808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLNb7Tm2MFQILo_nNxB:-NLRDHna8pITbRZFbXvK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a95bb299c244288c889114ac013ab0200c415bc3/pkg/storage/mvcc.go#L4808)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/storage/mvcc.go` line 4812 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLNbUEF8R7p7Ig2lELc:-NLRDJ9cA3PUMQKOUFmP:bj5pi84) ([raw file](https://github.com/cockroachdb/cockroach/blob/a95bb299c244288c889114ac013ab0200c415bc3/pkg/storage/mvcc.go#L4812)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can we have a situation where resolving one intent costs `kv.raft.command.max_size/2+1`, so we resolve one intent, are below the target size and so resolve the second and now `bytesExceeded` becomes true, but now it's too late?
</blockquote></details>

Yes, this situation could happen. However, `kv.raft.command.max_size` is `64MB` and is normally not changed, whereas the target byte limit will be set to `4MB`, which would make the case of exceeding the max raft command size very rare with byte pagination enabled. It's still possible if we have an intent of size `3MB` and then another intent of size `62MB`, but this feels like an extreme edge case.


<!-- Sent from Reviewable.io -->

2023-01-10 16:59 UTC, sumeerbhola reviewed
Storage changes are fine. @nvanbenschoten or someone in KV with the full context should give a review and approval.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-:-NLRbb9x48OP2PXqhyuD:b-cf9i2e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2023-01-10 17:14 UTC, nvanbenschoten reviewed
:wave: Thanks @kaisun314! Just a few small comments, and then this looks good to go.

> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-:-NLRf5CJ62xMAebr8YqS:b-vdsokt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314 and @sumeerbhola)

___
*[`-- commits` line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLRd7yS9Un9MvCOU6-o):*
I'm not sure that this change needs a release note. If we want to add one, it should be considered a `bug fix` and we should reframe this from the perspective of a user of CRDB. What effect does this change have to a user of CRDB.
___
*[`pkg/roachpb/api.proto` line 2529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLRdjOr07B7T3tanV29:-NLRdjOr07B7T3tanV2A:bmwd8ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/68fc6b4fabe74c6b3d06adffdeeb93fd52aad243/pkg/roachpb/api.proto#L2529)):*
> ```protobuf
>   // target_bytes_allow_empty is set. A suitable resume span will be returned.
>   //
>   // The semantics around overlapping requests, unordered requests, and
> ```

nit: should this be moved below the following paragraph?
___
*[`pkg/storage/mvcc_history_test.go` line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLRevin16oBveUsmDuI:-NLRevin16oBveUsmDuJ:bauu4jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/68fc6b4fabe74c6b3d06adffdeeb93fd52aad243/pkg/storage/mvcc_history_test.go#L84)):*
> ```Go
> //
> // resolve_intent t=<name> k=<key> [status=<txnstatus>] [clockWhilePending=<int>[,<int>]] [targetBytes=<int>]
> // resolve_intent_range t=<name> k=<key> end=<key> [status=<txnstatus>] [maxKeys=<int>,targetBytes=<int>]
> ```

nit: should this be `[maxKeys=<int>] [targetBytes=<int>]`? The two arguments are independent, right?


<!-- Sent from Reviewable.io -->

2023-01-11 01:07 UTC, KaiSun314 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[`-- commits` line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-NLRd7yS9Un9MvCOU6-o):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm not sure that this change needs a release note. If we want to add one, it should be considered a `bug fix` and we should reframe this from the perspective of a user of CRDB. What effect does this change have to a user of CRDB.
</blockquote></details>

Removed the release note.

I agree, this adds byte pagination for asynchronous intent resolution, which is in the background, so the improvements are less noticeable from the perspective of a user. Not sure yet, but maybe in the PR adding byte pagination for synchronous intent resolution could have a release note?


<!-- Sent from Reviewable.io -->

2023-01-12 17:18 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r5, 14 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94814#-:-NLazRJW7JAC9NHXB48Z:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-01-12 17:20 UTC, merged

2023-01-12 18:06 UTC, KaiSun314 commented
Thank you so much for the review Nathan and Sumeer!

2023-01-12 20:06 UTC, abarganier commented
@KaiSun314 I believe this led to some merge skew - I'm seeing CI failures in my PR related to these changes:
```
pkg/kv/kvserver/batcheval/cmd_resolve_intent_test.go:341:17: assignment mismatch: 3 variables but storage.MVCCGet returns 2 values
pkg/kv/kvserver/batcheval/cmd_resolve_intent_test.go:368:22: assignment mismatch: 3 variables but storage.MVCCGet returns 2 values
pkg/kv/kvserver/batcheval/cmd_resolve_intent_test.go:407:17: assignment mismatch: 3 variables but storage.MVCCGet returns 2 values
pkg/kv/kvserver/batcheval/cmd_resolve_intent_test.go:437:22: assignment mismatch: 3 variables but storage.MVCCGet returns 2 values
pkg/kv/kvserver/batcheval/cmd_resolve_intent_test.go:441:17: assignment mismatch: 3 variables but storage.MVCCGet returns 2 values
pkg/kv/kvserver/batcheval/cmd_resolve_intent_test.go:471:22: assignment mismatch: 3 variables but storage.MVCCGet returns 2 values
```