upgrades_test: speed up TestRoleMembersIDMigration1500Users test
cockroachdb/cockroach pull request #95382
Opened 2023-01-17 19:44 UTC by andyyang890

This patch speeds up the TestRoleMembersIDMigration1500Users test by
moving the creation of testusers into a single transaction.

Fixes #95268

Release note: None

2023-01-17 19:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/95382)
<!-- Reviewable:end -->

2023-01-17 19:57 UTC, rafiss requested changes
nice, that's the right idea, but i left a comment about a different interface to use

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95382#-:-NM0IdT-7fUwbsoMAzgc:b-duur68)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/upgrade/upgrades/role_members_ids_migration_test.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95382#-NM0Ha_v93em61BQzsHF:-NM0Ha_v93em61BQzsHG:buvpnxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d8f1af05998b26c1eb1fb3a45acef16cdf4aa9/pkg/upgrade/upgrades/role_members_ids_migration_test.go#L97)):*
> ```Go
> 	// Create test users.
> 	expectedNumRoleMembersRows := 1
> 	tdb.Exec(t, "BEGIN")
> ```

using `BEGIN` directly like this doesn't work ideally, since `tdb` may actually be a connection pool.

so i think we want something like this:

```
tx, err := db.BeginTx(ctx, nil /* txOptions */)
require.NoError(t, err)
txRunner := sqlutils.MakeSQLRunner(tx)

// use txRunner for all the things that should be in the transaction

err = tx.Commit()
require.NoError(t, err)
```


<!-- Sent from Reviewable.io -->

2023-01-18 20:18 UTC, andyyang890 reviewed
FYI I tried splitting the CREATE USER and GRANT statements into two separate loops and that actually made it slower

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95382#-:-NM5ClToBBMVb-dleGkr:b-g5v3ni)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/upgrade/upgrades/role_members_ids_migration_test.go` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95382#-NM0Ha_v93em61BQzsHF:-NM5WfB21rhTzIJ1JVg6:bvpnwma) ([raw file](https://github.com/cockroachdb/cockroach/blob/78d8f1af05998b26c1eb1fb3a45acef16cdf4aa9/pkg/upgrade/upgrades/role_members_ids_migration_test.go#L97)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

using `BEGIN` directly like this doesn't work ideally, since `tdb` may actually be a connection pool.

so i think we want something like this:

```
tx, err := db.BeginTx(ctx, nil /* txOptions */)
require.NoError(t, err)
txRunner := sqlutils.MakeSQLRunner(tx)

// use txRunner for all the things that should be in the transaction

err = tx.Commit()
require.NoError(t, err)
```
</blockquote></details>

Done. I split it into smaller transactions like we discussed offline since putting all the users into a single transaction led to the transaction being aborted when the test runs on CI.


<!-- Sent from Reviewable.io -->

2023-01-19 16:59 UTC, rafiss approved these changes
lgtm! were you able to see a difference in latency? could be useful to include that in the commit message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95382#-:-NM9y1-7EaE4Yq1FYYCk:b-16quou)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-01-19 18:20 UTC, andyyang890 reviewed
yeah it went from around ~55s to ~15s locally! updated the commit message too

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95382#-:-NMAFff87g1WERKuCP-c:b-41til8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)



<!-- Sent from Reviewable.io -->

2023-01-19 19:24 UTC, merged