opt: do not hoist correlated, non-leakproof subqueries in COALESCE
cockroachdb/cockroach pull request #95599
Opened 2023-01-20 18:31 UTC by mgartner

Previously, correlated, non-leakproof subqueries within a `COALESCE`
expression would be hoisted into an apply-join. This caused those
arguments to be evaluated when they shouldn't have been, i.e., when
previous arguments always evaluated to non-NULL values. This could cause
errors to propagate from arguments that should have never been
evaluated, and it was inconsistent with Postgres:

> Like a CASE expression, COALESCE only evaluates the arguments that are
needed to determine the result; that is, arguments to the right of the
first non-null argument are not evaluated[^1].

Now, non-leakproof subqueries are only hoisted from within a `COALESCE`
expression if they are not in the first argument. It is safe to hoist a
non-leakproof subquery in the first argument because it is always
evaluated.

Fixes #95560

Release note (bug fix): A bug has been fixed that could arguments of a
`COALESCE` to be evaluated when previous arguments always evaluated to
non-NULL values. This bug could cause query errors to originate from
arguments of a `COALESCE` that should have never been evaluated.

[^1]: https://www.postgresql.org/docs/15/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL

2023-01-20 18:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/95599)
<!-- Reviewable:end -->

2023-01-20 19:47 UTC, michae2 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95599)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-NMFfBkx3UQRLkS2Ny2C):*
nit: Should this be "if they are the first argument" instead of "if they are _not in_ the first argument"?
___
*[`-- commits` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-NMFfNLh6u7aAFYzUtPC):*
nit: I think "could" should be "could cause"?
___
*[`-- commits` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-NMFfV8OATCTRq231WqO):*
nit: I think the release notes script is going to incorrectly pick up this footnote as part of the release note.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-NMFhV7556K7j6P_YBu6:-NMFhV7556K7j6P_YBu7:b-94ddfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39085f5b31f7d0ba3eda52bf93f11e7c694f899/pkg/sql/opt/norm/decorrelate_funcs.go#L100)):*
> ```Go
> 				// The first argument does not need to be leakproof because it
> 				// is always evaluated.
> 				for j := 1; j < len(t.Args); j++ {
> ```

I'm confused by this loop. Aren't we already in a loop over the children of the coalesce expression? Should this be `if i > 0 {`?


<!-- Sent from Reviewable.io -->

2023-01-22 15:09 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95599)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-NMFfBkx3UQRLkS2Ny2C):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Should this be "if they are the first argument" instead of "if they are _not in_ the first argument"?
</blockquote></details>

Removed the "not". But I'm keeping the `in` because the first argument could be a scalar expression with a subquery nested below it - it doesn't have to be a subquery itself.
___
*[`-- commits` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-NMFfNLh6u7aAFYzUtPC):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: I think "could" should be "could cause"?
</blockquote></details>

Done.
___
*[`-- commits` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-NMFfV8OATCTRq231WqO):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: I think the release notes script is going to incorrectly pick up this footnote as part of the release note.
</blockquote></details>

Moved the footnote above the release note.
___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-NMFhV7556K7j6P_YBu6:-NMLncs6B0-bHB6xJ9i8:b384awr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39085f5b31f7d0ba3eda52bf93f11e7c694f899/pkg/sql/opt/norm/decorrelate_funcs.go#L100)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I'm confused by this loop. Aren't we already in a loop over the children of the coalesce expression? Should this be `if i > 0 {`?
</blockquote></details>

It confused me too. A CoalesceExpr has only a single child, which is a ScalarListExpr, and it's the ScalarListExpr that has a child for each argument of the CoalesceExpr. So in this `case` branch, `i` is always `0`. We also can't simply recurse like in the other cases because we'd loose the context of being in a `Coalesce` and/or the argument position. I considered passing this information along in the recursive call, but the approach here seemed cleaner.


<!-- Sent from Reviewable.io -->

2023-01-22 20:46 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-:-NMQDl9p0QKZmWy4uS_v:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)



<!-- Sent from Reviewable.io -->

2023-01-23 19:53 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-:-NMVBD9E6z-5Ar51j4Av:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/norm/decorrelate_funcs.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95599#-NMFhV7556K7j6P_YBu6:-NMVAxtkEKJcwLjMB5UI:b-9755fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39085f5b31f7d0ba3eda52bf93f11e7c694f899/pkg/sql/opt/norm/decorrelate_funcs.go#L100)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It confused me too. A CoalesceExpr has only a single child, which is a ScalarListExpr, and it's the ScalarListExpr that has a child for each argument of the CoalesceExpr. So in this `case` branch, `i` is always `0`. We also can't simply recurse like in the other cases because we'd loose the context of being in a `Coalesce` and/or the argument position. I considered passing this information along in the recursive call, but the approach here seemed cleaner.
</blockquote></details>

Thank you!


<!-- Sent from Reviewable.io -->

2023-01-24 16:38 UTC, mgartner commented
TFTRs!

bors r+

2023-01-24 18:36 UTC, merged