sql: support `*` in udf bodies
cockroachdb/cockroach pull request #95710
Opened 2023-01-24 00:52 UTC by rharding6373

This change allows `*` usage in UDF bodies. In order to facilitate schema changes after a UDF is created but should not affect the UDF output, we rewrite UDF ASTs in place to reference tables and columns by ID instead of by name.

Informs: #90080

Epic: CRDB-19496
Release note (sql change): Allow `*` expressions in UDFs.

2023-01-24 00:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/95710)
<!-- Reviewable:end -->

2023-01-24 04:43 UTC, rharding6373 commented
There are a handful of UDF tests I need to clean up, but I think it's ready for a first round of review.

2023-01-24 06:51 UTC, DrewKimball reviewed
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/builder.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWmo4a4XAcC9Jm3FNr:-NMWmo4b2iV592mF8IuT:bwf1pzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/opt/optbuilder/builder.go#L148)):*
> ```Go
> 	// If set, the data source names in the AST are rewritten to the table ID and
> 	// all the visible column IDs.
> 	useIDsInAST bool
> ```

[nit] Could this be replaced by `insideFuncDef`?
___
*[`pkg/sql/opt/optbuilder/select.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWmutP2FMd2n1gCDbH:-NMWmutP2FMd2n1gCDbI:b-6r4y4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/opt/optbuilder/select.go#L112)):*
> ```Go
> 
> 		ds, depName, resName := b.resolveDataSource(tn, privilege.SELECT)
> 		if b.useIDsInAST {
> ```

Why replace the data source instead of the `*`?
___
*[`pkg/sql/opt/optbuilder/util.go` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWfJDfEhsdc5j0Pay8:-NMWfJDgA0SwT_NFdrpc:b-l7lkbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/opt/optbuilder/util.go#L65)):*
> ```Go
> ) (aliases []string, exprs []tree.TypedExpr) {
> 	if b.insideViewDef {
> 		panic(unimplemented.NewWithIssue(10028, "views do not currently support * expressions"))
> ```

Can we also support `*` in views the same way?
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWfjTd7C_FdgIRpv5i:-NMWfjTd7C_FdgIRpv5j:b-wjbcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/logictest/testdata/logic_test/udf#L127)):*
> ```
>   LANGUAGE SQL
>   AS $$
>   SELECT a FROM [113(1, 2, 3) AS t];
> ```

For outputs like this one, are we sure we want to show the rewritten version instead of the original?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWhJJR7OiEwc9P3A0b:-NMWhJJR7OiEwc9P3A0c:b8e5a41) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/logictest/testdata/logic_test/udf_star#L95)):*
> ```
> 
> statement ok
> ALTER TABLE t_twocol ADD COLUMN c INT DEFAULT 5;
> ```

What happens if you change the column type (both to something compatible and something not compatible)? Or the column name?


<!-- Sent from Reviewable.io -->

2023-01-24 07:18 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWhJJR7OiEwc9P3A0b:-NMXcYSgCL7LE80xIFxb:b-uq20us) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/logictest/testdata/logic_test/udf_star#L95)):*
>Or the column name?

Oops, didn't notice you had this case already.

Also, could you add one where `f_allcolsel` is called after the table is altered? Postgres actually seems ok with that case:
```
postgres=# create table t (a int);
CREATE TABLE
postgres=# create function f() returns t language sql as 'select * from t';
CREATE FUNCTION
postgres=# alter table t add column b int;
ALTER TABLE
postgres=# select f();
 f
---

(1 row)

postgres=# insert into t values(1);
INSERT 0 1
postgres=# select f();
  f
------
 (1,)
(1 row)
```


<!-- Sent from Reviewable.io -->

2023-01-24 07:39 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWhJJR7OiEwc9P3A0b:-NMXhtGEANvJBHAEPaeY:b-9bctgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/logictest/testdata/logic_test/udf_star#L95)):*
>Postgres actually seems ok with that case

Nevermind, I didn't realize we wanted to default to early binding.


<!-- Sent from Reviewable.io -->

2023-01-24 23:32 UTC, rharding6373 reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-:-NMa6taSCawSUJ1kxycr:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/optbuilder/builder.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWmo4a4XAcC9Jm3FNr:-NM_HiNc2XiDmHQLa3sr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/opt/optbuilder/builder.go#L148)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Could this be replaced by `insideFuncDef`?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/select.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWmutP2FMd2n1gCDbH:-NM_HnWh0zAaYpdNgWDu:br805fj) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/opt/optbuilder/select.go#L112)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Why replace the data source instead of the `*`?
</blockquote></details>

Using table and column IDs should make handling schema changes like column and table renaming easier, since the underlying IDs don't change. Otherwise when we rename something we'll need to rewrite the UDF body, I think.
___
*[`pkg/sql/opt/optbuilder/util.go` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWfJDfEhsdc5j0Pay8:-NM_IumOA__wS6zCScMr:brfuzda) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/opt/optbuilder/util.go#L65)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Can we also support `*` in views the same way?
</blockquote></details>

Maybe, thanks for pointing that out. Let me look into that after this PR goes out. It looks like there's a long history about views and schema changes.
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWfjTd7C_FdgIRpv5i:-NM_j4EPC5ohRBpAl_cC:bthsir2) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/logictest/testdata/logic_test/udf#L127)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

For outputs like this one, are we sure we want to show the rewritten version instead of the original?
</blockquote></details>

I discussed this with @mgartner offline, and we decided that ultimately we want to support both pretty printing with the table names and printing the rewritten query (like postgres does with \df+ and pg_catalog.pg_proc's prosqlbody, respectively). But now that I'm looking at this again, we are using pg_catalog.pg_proc here, though we seem to be using prosrc and prosqlbody differently than postgres given our different binding treatment for the same syntax... I will solicit opinions in the #udf channel about where we expect pretty versions of the udf vs not.

@mgartner is probably right that we need to reconstruct a pretty version of the body as opposed to the original source. This is what postgres appears to do for early binding UDFs, since altering the schema results in changes to what is output by \df+. 
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWhJJR7OiEwc9P3A0b:-NM_LERy0r19gNRPiHSI:bk8m5xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/logictest/testdata/logic_test/udf_star#L95)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

>Postgres actually seems ok with that case

Nevermind, I didn't realize we wanted to default to early binding.
</blockquote></details>

My understanding is that we only support early binding right now. I added a comment to clarify that this behavior is only expected for early binding. Added more `ALTER` examples in the test, which work as expected.


<!-- Sent from Reviewable.io -->

2023-01-25 00:05 UTC, rharding6373 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWfjTd7C_FdgIRpv5i:-NMaDmWt8JHzxGQPwpEJ:b-roxkx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/logictest/testdata/logic_test/udf#L127)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I discussed this with @mgartner offline, and we decided that ultimately we want to support both pretty printing with the table names and printing the rewritten query (like postgres does with \df+ and pg_catalog.pg_proc's prosqlbody, respectively). But now that I'm looking at this again, we are using pg_catalog.pg_proc here, though we seem to be using prosrc and prosqlbody differently than postgres given our different binding treatment for the same syntax... I will solicit opinions in the #udf channel about where we expect pretty versions of the udf vs not.

@mgartner is probably right that we need to reconstruct a pretty version of the body as opposed to the original source. This is what postgres appears to do for early binding UDFs, since altering the schema results in changes to what is output by \df+. 
</blockquote></details>

Actually, using the rewritten version here may break backups. Might need to reinterpret the udf body here.


<!-- Sent from Reviewable.io -->

2023-01-25 01:35 UTC, DrewKimball reviewed
I think this <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> sans the possible backport issue.

> Reviewed 1 of 1 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-:-NMaYwUH78a2uoHa_Dml:b4subcu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @mgartner, and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/select.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWmutP2FMd2n1gCDbH:-NMaW8w092zLqDwSTEH9:b-kicul9) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/opt/optbuilder/select.go#L112)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Using table and column IDs should make handling schema changes like column and table renaming easier, since the underlying IDs don't change. Otherwise when we rename something we'll need to rewrite the UDF body, I think.
</blockquote></details>

Makes sense, it looks like it would be very invasive to make that change on second glance.
___
*[`pkg/sql/opt/optbuilder/select.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMaWjWR2ew0ZQap3Lkf:-NMaWjWR2ew0ZQap3Lkg:bq0tm6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebbbe8fe99e7a3e7a2f642ef5b7adfafc008ce7b/pkg/sql/opt/optbuilder/select.go#L46)):*
> ```Go
> // See Builder.buildStmt for a description of the remaining input and
> // return values.
> func (b *Builder) buildDataSource(
> ```

[nit] I think we should either expand the comment here to mention that it can mutate `texpr`, or maybe change its contract to return the replacement. Do you know if we do this sort of thing anywhere else in the optbuilder?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMaY2Vn9l4nxE7BUOZs:-NMaXmmNBJMxmEIklqX_:b-2cl1x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebbbe8fe99e7a3e7a2f642ef5b7adfafc008ce7b/pkg/sql/logictest/testdata/logic_test/udf_star#L105)):*
> ```
> # ok for late binding.
> query T
> SELECT f_unqualified_twocol()
> ```

I wonder if we should consider this a valid departure from postgres like defaulting to early binding - it seems reasonable to also early-bind the return type. Do you know what happens if a UDT is used as the return type and later altered?


<!-- Sent from Reviewable.io -->

2023-01-25 16:53 UTC, chengxiong-ruan requested changes
Nice work on this! I learned a lot  here. But as we chatted through slack that we'd prefer expanding `*` into column names instead of rewriting the data source. Not sure how much more work that would be to do the expansion, but it would save a lot of work on deserialization for things like `SHOW CREATE FUNCTION`.

2023-01-26 20:27 UTC, rharding6373 reviewed
I reimplemented to modify the AST in place to do `*` expansion instead of datasource replacement. RFAL, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-:-NMjki2c74jBmMusu4N5:b-2448r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @dt, and @mgartner)

___
*[`pkg/sql/opt/optbuilder/select.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWmutP2FMd2n1gCDbH:-NMjhjj59Meu_eCXx-sM:b781dub) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/opt/optbuilder/select.go#L112)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Makes sense, it looks like it would be very invasive to make that change on second glance.
</blockquote></details>

Reimplemented to expand the `*`, PTAL
___
*[`pkg/sql/opt/optbuilder/select.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMaWjWR2ew0ZQap3Lkf:-NMjiKzz-2XoVutUgZE0:bjvjzy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebbbe8fe99e7a3e7a2f642ef5b7adfafc008ce7b/pkg/sql/opt/optbuilder/select.go#L46)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] I think we should either expand the comment here to mention that it can mutate `texpr`, or maybe change its contract to return the replacement. Do you know if we do this sort of thing anywhere else in the optbuilder?
</blockquote></details>

We do some minor tweaks to the AST, such as fully qualifying table names, but afaict we don't replace expressions often. I've added a comment to `analyzeSelectList`, which is where the expansion happens in the reimplementation.
___
*[`pkg/sql/opt/optbuilder/util.go` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWfJDfEhsdc5j0Pay8:-NMjhI5E-WKuHpB8iauh:b-71wxrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/opt/optbuilder/util.go#L65)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Maybe, thanks for pointing that out. Let me look into that after this PR goes out. It looks like there's a long history about views and schema changes.
</blockquote></details>

With the reimplementation it's not really relevant anymore, but the work slated to https://github.com/cockroachdb/cockroach/issues/83233 is more closely aligned with that goal, it seems.
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWfjTd7C_FdgIRpv5i:-NMjc9x0DEW1v2s1qlO5:bogl8dl) ([raw file](https://github.com/cockroachdb/cockroach/blob/acb0b1fbd80fca84bee392f717b370d2136feaff/pkg/sql/logictest/testdata/logic_test/udf#L127)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Actually, using the rewritten version here may break backups. Might need to reinterpret the udf body here.
</blockquote></details>

No longer relevant with the rewrite
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMaY2Vn9l4nxE7BUOZs:-NMjgO_r7BodeZn7rb5L:bp3ymx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebbbe8fe99e7a3e7a2f642ef5b7adfafc008ce7b/pkg/sql/logictest/testdata/logic_test/udf_star#L105)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I wonder if we should consider this a valid departure from postgres like defaulting to early binding - it seems reasonable to also early-bind the return type. Do you know what happens if a UDT is used as the return type and later altered?
</blockquote></details>

Renaming the return type is fine, but adding attributes results in a return type mismatch error in postgres:
```
rharding=# create type typ as (a int);
CREATE TYPE
rharding=# create function f() returns typ language sql begin atomic; select 1; end;
CREATE FUNCTION
rharding=# select f();
  f  
-----
 (1)
(1 row)
rharding=# alter type typ rename to rtyp;
ALTER TYPE
rharding=# select f();
  f  
-----
 (1)
(1 row)
rharding=# alter type rtyp add attribute b int;
ALTER TYPE
rharding=# select f();
ERROR:  return type mismatch in function declared to return rtyp
DETAIL:  Final statement returns too few columns.
CONTEXT:  SQL function "f" during inlining

```


<!-- Sent from Reviewable.io -->

2023-01-26 20:49 UTC, chengxiong-ruan reviewed
Nice work!

2023-01-26 20:49 UTC, chengxiong-ruan commented on pkg/sql/logictest/testdata/logic_test/udf_star
> +statement error pq: cannot drop column "b" because function "f_unqualified_twocol" depends on it
Could you also add test cases with `DROP CASCADE` ? like the ones in test `TestDropCascadeRemoveFunction`. Just want to make sure the dependencies are handled well (I'm sure it does).

2023-01-26 20:49 UTC, chengxiong-ruan commented on pkg/sql/opt/optbuilder/testdata/create_function
> + │   	AS $$SELECT w FROM [55(1) AS workdays];$$
these test changes need to be reverted?

2023-01-26 21:14 UTC, mgartner requested changes
> Reviewed 2 of 15 files at r1, 23 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @dt, and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/project.go` line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjrGUM9v2qsl29wsea:-NMjrGUM9v2qsl29wseb:bg5jbcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/opt/optbuilder/project.go#L153)):*
> ```Go
> 						expanded = true
> 						for _, expr := range exprs {
> 							col := expr.(*scopeColumn)
> ```

I don't think the exprs are guaranteed to be `*scopeColumn`s: https://github.com/cockroachdb/cockroach/blob/d0a5b853a31d4739a62c09f059577185a618ead4/pkg/sql/opt/optbuilder/util.go#L119

Is there a way to exercise that case in a UDF?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjtlYU8uL-6yu4mWkc:-NMjtlYU8uL-6yu4mWkd:b-1lyc9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/logictest/testdata/logic_test/udf_star#L18)):*
> ```
> CREATE FUNCTION f_subquery() RETURNS INT AS
> $$
>   SELECT * FROM (SELECT a FROM (SELECT * FROM t_onecol) AS foo) AS bar;
> ```

Can you add a test like this without the subquery aliases `foo` and `bar`? If we can't support it because we the column names can't be fully qualified, then we can return a user error if there are unaliased subqueries in a UDF.
___
*[`pkg/sql/opt/optbuilder/testdata/udf` line 1181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjumqb1a3aSFzfWpk4:-NMjumqcEvKbvev1BKEa:b-gi126t) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/opt/optbuilder/testdata/udf#L1181)):*
> ```
> 
> exec-ddl
> CREATE FUNCTION fn_star() RETURNS INT LANGUAGE SQL AS 'SELECT * FROM tstar'
> ```

Might be nice to have another, more complicated test case here, like with a subquery where the column qualification is important. It'll make sure that `testcat` respects the rewriting correctly, too.
___
*[`pkg/ccl/backupccl/backup_test.go` line 10630 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjv8G4EjfwxlmxgLhk:-NMjv8G4EjfwxlmxgLhl:b-85ikog) ([raw file](https://github.com/cockroachdb/cockroach/blob/705d6a1b650b68be5863ee5bc0729254f91dd2f6/pkg/ccl/backupccl/backup_test.go#L10630)):*
> ```Go
> $$;
> `)
> ```

nit: revert this change


<!-- Sent from Reviewable.io -->

2023-01-26 21:14 UTC, mgartner commented
This looks great! Nice work! I just left a couple minor comments.





<!-- Sent from Reviewable.io -->

2023-01-26 22:09 UTC, mgartner commented
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMk75G2CkYH3AcAu_Rs:-NMk75G2CkYH3AcAu_Rt:b-gv5lyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/logictest/testdata/logic_test/udf_star#L61)):*
> ```
> query TTT
> SELECT oid, proname, prosrc
> FROM pg_catalog.pg_proc WHERE proname LIKE 'f\_%' ORDER BY oid;
> ```

It might be good to add some tests with `SHOW CREATE FUNCTION` here too.


<!-- Sent from Reviewable.io -->

2023-01-26 22:59 UTC, DrewKimball reviewed
> Reviewed 23 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @mgartner, and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/project.go` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjqRtq4n-PFjcQyoFo:-NMjqRtrCgEp_8ucsPnc:b-ud9w1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/opt/optbuilder/project.go#L129)):*
> ```Go
> ) {
> 	var expansions tree.SelectExprs
> 	expanded := false
> ```

[nit] Since we're filling out `expansions` unconditionally when `b.insideFuncDef`, checking `expanded` doesn't seem useful.
___
*[`pkg/sql/opt/optbuilder/select.go` line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjrrG_37QxNbTvnrFY:-NMjrrG_37QxNbTvnrFZ:b-d3jdqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/opt/optbuilder/select.go#L47)):*
> ```Go
> // return values.
> func (b *Builder) buildDataSource(
> 	texpr *tree.TableExpr, indexFlags *tree.IndexFlags, locking lockingSpec, inScope *scope,
> ```

[nit] Is the change here still necessary?


<!-- Sent from Reviewable.io -->

2023-01-31 00:22 UTC, rharding6373 reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-:-NN4Bwt40_t122v6ZRAO:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan, @DrewKimball, @dt, and @mgartner)

___
*[`pkg/sql/opt/optbuilder/project.go` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjqRtq4n-PFjcQyoFo:-NMkK38-CjxKWqcUJJZV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/opt/optbuilder/project.go#L129)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Since we're filling out `expansions` unconditionally when `b.insideFuncDef`, checking `expanded` doesn't seem useful.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/project.go` line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjrGUM9v2qsl29wsea:-NN4AJSgDiLRuwwxpBbQ:bp891bz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/opt/optbuilder/project.go#L153)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think the exprs are guaranteed to be `*scopeColumn`s: https://github.com/cockroachdb/cockroach/blob/d0a5b853a31d4739a62c09f059577185a618ead4/pkg/sql/opt/optbuilder/util.go#L119

Is there a way to exercise that case in a UDF?
</blockquote></details>

Good catch. Fixed this and added a test case.
___
*[`pkg/sql/opt/optbuilder/select.go` line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjrrG_37QxNbTvnrFY:-NMkJvUCC3uVeJHAv0fI:b-dz155i) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/opt/optbuilder/select.go#L47)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Is the change here still necessary?
</blockquote></details>

Done. Thanks for the catch!
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjtlYU8uL-6yu4mWkc:-NMkUJ5u7EBE-19V9kpL:br2t3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/logictest/testdata/logic_test/udf_star#L18)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add a test like this without the subquery aliases `foo` and `bar`? If we can't support it because we the column names can't be fully qualified, then we can return a user error if there are unaliased subqueries in a UDF.
</blockquote></details>

Doesn't seem like we do this correctly outside of UDFs, but maybe this is intentional. Thoughts?

In postgres:

```
rharding=# create table t (a int);
CREATE TABLE
rharding=# select * from (select a from (select * from t));
ERROR:  subquery in FROM must have an alias
LINE 1: select * from (select a from (select * from t));
                                     ^
HINT:  For example, FROM (SELECT ...) [AS] foo.
```

In CRDB we don't error:
```
root@127.0.0.1:26257/defaultdb> create table t (a int);                                               
CREATE TABLE

root@127.0.0.1:26257/defaultdb> select * from (select a from (select * from t));                      
  a
-----
(0 rows)
root@127.0.0.1:26257/defaultdb> explain (opt, verbose) select * from (select a from (select * from t));                                                                  
             info
-------------------------------
  scan t
   ├── columns: a:1
   ├── stats: [rows=1]
   ├── cost: 25.68
   ├── distribution: us-east1
   └── prune: (1)
(6 rows)

```
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMk75G2CkYH3AcAu_Rs:-NMkhrKh41JZ-tqVK2s3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/logictest/testdata/logic_test/udf_star#L61)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It might be good to add some tests with `SHOW CREATE FUNCTION` here too.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWFk-_j_6h7mrZgDmE-r4-140:-NN3eX2k7EXPcwSB1oX2:b-wy9vv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/logictest/testdata/logic_test/udf_star#L140)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Could you also add test cases with `DROP CASCADE` ? like the ones in test `TestDropCascadeRemoveFunction`. Just want to make sure the dependencies are handled well (I'm sure it does).
</blockquote></details>

Done. Let me know if you think we need to test more cases than dropping columns and tables, in which case it might make more sense to expand the unit test to include a function with select *.
___
*[`pkg/sql/opt/optbuilder/testdata/create_function` line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMWf9Yi9mZDJJZtAquM-r4-45:-NMjxY8x1V5bK_u3BuH-:b60r4zt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/opt/optbuilder/testdata/create_function#L45)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

these test changes need to be reverted?
</blockquote></details>

Yes, done!
___
*[`pkg/sql/opt/optbuilder/testdata/udf` line 1181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjumqb1a3aSFzfWpk4:-NN3g0xl7-HUWlg9xO7g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/opt/optbuilder/testdata/udf#L1181)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Might be nice to have another, more complicated test case here, like with a subquery where the column qualification is important. It'll make sure that `testcat` respects the rewriting correctly, too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-31 15:31 UTC, chengxiong-ruan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-:-NN7Rd2kD_NzuG5-7Gnv:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @dt, and @mgartner)



<!-- Sent from Reviewable.io -->

2023-01-31 23:35 UTC, mgartner reviewed
> Reviewed 5 of 10 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @chengxiong-ruan, @DrewKimball, @dt, and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/project.go` line 158 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NN987Zu3qlH4UT0hsez:-NN987Zu3qlH4UT0hsf-:btar8jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9010a133d9ddde76ca5bd608751d7d0511b69809/pkg/sql/opt/optbuilder/project.go#L158)):*
> ```Go
> 							case *tree.ColumnAccessExpr:
> 								expansions = append(expansions, tree.SelectExpr{Expr: col})
> 							}
> ```

I think we should add a `default` case that panics with an assertion failed error rather than continuing on successfully.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjtlYU8uL-6yu4mWkc:-NN98g9n2BvV4BW6njCq:b-5xrqdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/logictest/testdata/logic_test/udf_star#L18)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Doesn't seem like we do this correctly outside of UDFs, but maybe this is intentional. Thoughts?

In postgres:

```
rharding=# create table t (a int);
CREATE TABLE
rharding=# select * from (select a from (select * from t));
ERROR:  subquery in FROM must have an alias
LINE 1: select * from (select a from (select * from t));
                                     ^
HINT:  For example, FROM (SELECT ...) [AS] foo.
```

In CRDB we don't error:
```
root@127.0.0.1:26257/defaultdb> create table t (a int);                                               
CREATE TABLE

root@127.0.0.1:26257/defaultdb> select * from (select a from (select * from t));                      
  a
-----
(0 rows)
root@127.0.0.1:26257/defaultdb> explain (opt, verbose) select * from (select a from (select * from t));                                                                  
             info
-------------------------------
  scan t
   ├── columns: a:1
   ├── stats: [rows=1]
   ├── cost: 25.68
   ├── distribution: us-east1
   └── prune: (1)
(6 rows)

```
</blockquote></details>

Right, CRDB has allowed unaliased subqueries for some time. It's probably a relic from some early implementation rather than a specific decision we made to allow it. Since we allow it, we need to figure out what to do when they are present in UDFs with star expansions. If you add a test with a UDF body of: `SELECT * FROM (SELECT a FROM (SELECT * FROM t_onecol));`, what do the stars get expanded to?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 79 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NN99uMH9tnS---XW8qF:-NN99uMH9tnS---XW8qG:b-mb2v6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9010a133d9ddde76ca5bd608751d7d0511b69809/pkg/sql/logictest/testdata/logic_test/udf_star#L79)):*
> ```
> 100115  f_unqualified_doublestar  SELECT t_onecol.a, t_onecol.a FROM test.public.t_onecol;
>                                   SELECT a FROM test.public.t_onecol;
> 100116  f_exprstar                SELECT word FROM (SELECT (pg_get_keywords()).word, (pg_get_keywords()).catcode, (pg_get_keywords()).catdesc ORDER BY word LIMIT 1);
> ```

This rewrite is a bit unfortunate - now we're evaluating the `pg_get_keywords()` function multiple times. I wonder if there is a more efficient rewrite we can do.


<!-- Sent from Reviewable.io -->

2023-02-01 00:26 UTC, rharding6373 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @chengxiong-ruan, @DrewKimball, @dt, and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjtlYU8uL-6yu4mWkc:-NN9FUuB9REHu7TLMBEk:bjxsq63) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/logictest/testdata/logic_test/udf_star#L18)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Right, CRDB has allowed unaliased subqueries for some time. It's probably a relic from some early implementation rather than a specific decision we made to allow it. Since we allow it, we need to figure out what to do when they are present in UDFs with star expansions. If you add a test with a UDF body of: `SELECT * FROM (SELECT a FROM (SELECT * FROM t_onecol));`, what do the stars get expanded to?
</blockquote></details>

The expansion (in the current implementation) is `SELECT a FROM (SELECT a FROM (SELECT t_onecol.a FROM test.public.t_onecol))`

If we allow it outside of UDFs, wouldn't it make sense to allow it inside UDFs even if it means they both differ in comparison to postgres? Why do we prefer different behavior in UDFs than outside of UDFs?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 79 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NN99uMH9tnS---XW8qF:-NN9MHw63DZckRDcd2-Z:b3to87b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9010a133d9ddde76ca5bd608751d7d0511b69809/pkg/sql/logictest/testdata/logic_test/udf_star#L79)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This rewrite is a bit unfortunate - now we're evaluating the `pg_get_keywords()` function multiple times. I wonder if there is a more efficient rewrite we can do.
</blockquote></details>

Not very efficient, but happens to be what postgres does in its rewrite so I decided to leave it for now.


<!-- Sent from Reviewable.io -->

2023-02-01 15:02 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @chengxiong-ruan, @DrewKimball, @dt, and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjtlYU8uL-6yu4mWkc:-NNCPRxh-ZRwZtRA6Jxk:bxmz8hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/logictest/testdata/logic_test/udf_star#L18)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

The expansion (in the current implementation) is `SELECT a FROM (SELECT a FROM (SELECT t_onecol.a FROM test.public.t_onecol))`

If we allow it outside of UDFs, wouldn't it make sense to allow it inside UDFs even if it means they both differ in comparison to postgres? Why do we prefer different behavior in UDFs than outside of UDFs?
</blockquote></details>

I think we should allow it, if possible, but I'm worried that without an alias for the subquery, this rewrite will produce a query that's either ambiguous or not equivalent to the original. I can see my last example wasn't interesting, so let me try again. Consider the query:

```sql
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT);

SELECT * FROM (SELECT a FROM t1) JOIN (SELECT a FROM t2) ON true;
```

This should produce two columns, one from each side of the join. Without an alias for the subqueries, I'm assuming we'd rewrite this as:

```sql
SELECT a, a FROM (SELECT a FROM t1) JOIN (SELECT a FROM t2) ON true;
```

Both `a`s are ambiguous, and if we try to run this we get the error: `column reference "a" is ambiguous`.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 79 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NN99uMH9tnS---XW8qF:-NNCUZJHA-rC-SzY67HV:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9010a133d9ddde76ca5bd608751d7d0511b69809/pkg/sql/logictest/testdata/logic_test/udf_star#L79)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Not very efficient, but happens to be what postgres does in its rewrite so I decided to leave it for now.
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2023-02-02 00:57 UTC, rharding6373 reviewed
Thanks for all the careful reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-:-NNEc-tr2KBwWVQ2J7e4:bwhy7gx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @chengxiong-ruan, @DrewKimball, @dt, and @mgartner)

___
*[`pkg/sql/opt/optbuilder/project.go` line 158 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NN987Zu3qlH4UT0hsez:-NNDjNb6BktTjmHO486_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9010a133d9ddde76ca5bd608751d7d0511b69809/pkg/sql/opt/optbuilder/project.go#L158)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think we should add a `default` case that panics with an assertion failed error rather than continuing on successfully.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjtlYU8uL-6yu4mWkc:-NNDduzZChtQgvDv4xTe:b-w84wes) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/logictest/testdata/logic_test/udf_star#L18)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think we should allow it, if possible, but I'm worried that without an alias for the subquery, this rewrite will produce a query that's either ambiguous or not equivalent to the original. I can see my last example wasn't interesting, so let me try again. Consider the query:

```sql
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT);

SELECT * FROM (SELECT a FROM t1) JOIN (SELECT a FROM t2) ON true;
```

This should produce two columns, one from each side of the join. Without an alias for the subqueries, I'm assuming we'd rewrite this as:

```sql
SELECT a, a FROM (SELECT a FROM t1) JOIN (SELECT a FROM t2) ON true;
```

Both `a`s are ambiguous, and if we try to run this we get the error: `column reference "a" is ambiguous`.


</blockquote></details>

I opened an issue to address ambiguous columns in subqueries here: https://github.com/cockroachdb/cockroach/issues/96375

We now throw an unimplemented error for unaliased subqueries, could you take a look at optbuilder/select.go? TY!


<!-- Sent from Reviewable.io -->

2023-02-02 22:02 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice work!

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-:-NNJ8dVg0mifTrghegFQ:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @chengxiong-ruan, @DrewKimball, and @dt)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_star` line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95710#-NMjtlYU8uL-6yu4mWkc:-NNCV2tx2hwUtvr82UWk:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee5bf066bf0ac5670c6a3aafa92e45624e9d4f5/pkg/sql/logictest/testdata/logic_test/udf_star#L18)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I opened an issue to address ambiguous columns in subqueries here: https://github.com/cockroachdb/cockroach/issues/96375

We now throw an unimplemented error for unaliased subqueries, could you take a look at optbuilder/select.go? TY!
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2023-02-02 22:16 UTC, rharding6373 commented
TFTRs everyone!

bors r+

2023-02-03 02:03 UTC, merged