sql: ensure TLV is consistent with SLV
cockroachdb/cockroach pull request #95904
Opened 2023-01-26 01:57 UTC by healthy-pod

In #94774, we didn't intend to change the TLV and it is still supposed to be equal to the SLV. Changing the way we set it however has caused TLV and SLV to be different if a test uses two binaries, and only one of them was built with `crdb_test` due to how we add `1e6` to versions in test binaries.

Closes #95648

Epic: none
Release note: None

2023-01-26 01:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/95904)
<!-- Reviewable:end -->

2023-01-27 17:01 UTC, ajstorm requested changes
I left some comments, but I think we're going to need @postamar's eyes on this too.  I know the spirit of what his PR meant to accomplish, but the details are important and subtle.  

@postamar could you please take a look?

2023-01-27 17:01 UTC, ajstorm commented on pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go
> +// Returns two versions v0, v1, v2 which correspond to adjacent releases. v0 will
Is this change future-proof?  If, for example, we let MinSupportedVerion trail a few releases, would this comment still be correct?  I'd _imagine_ that the test would still do what we'd want it to do, though maybe not if we wanted to test all of the upgrade stages in between v0 and v2.

2023-01-27 21:00 UTC, healthy-pod commented
I agree maybe this is not the right change, maybe we should make the changes to how we test instead? I am looking for suggestions but I will leave 2 points on why I made this change to further explain how this is just a testing issue and not an actual correctness issue:
1) passing a version override using testing knobs or by setting version when creating testing cluster settings is no longer effective because the changes in `createTenantInternal` run after that (ofcourse) and do not check for any overrides. Ideally, `minVersion` and `curVersion` in `createTenantInternal` should have the testing overrides values if an override was passed.
2) checking for version equality between two servers where a server is started with a `crdb_test`-built binary and the other isn't will return different versions even if they are technically the same. I am thinking of adding another version equality function that works around this by incrementing/decrementing one of the versions by `1e6` and returning true if they become equal.

2023-01-30 04:30 UTC, healthy-pod commented
When multiple previous releases are supported, my previous code change becomes incorrect. I removed my changes to `tenant_creation` and just made the test ignore the difference between normal versions and versions from test binaries by normalizing them.

Ready for another pass.

2023-01-30 15:12 UTC, renatolabs commented
Drive-by comment about upgrade testing here: If we decide to merge this PR as it currently is, I'd suggest adding a note/TODO/issue to revert it at some point. I think we can agree that asserting on specific cluster versions makes for a stronger test (and having or not having the version offset is part of that); more importantly, we want to eventually live in a world where most upgrade roachtests don't have to deal with version offsetting (#92608).

I'd also make a small correction here that version offsetting does not depend on the `crdb_test` build flag; offsetting happens if the binary is not considered a release binary:

https://github.com/cockroachdb/cockroach/blob/3e65660091c0870988978032999acda5a675e5e7/pkg/clusterversion/cockroach_versions.go#L712-L717

2023-01-30 23:49 UTC, healthy-pod commented
@renatolabs 
> I'd suggest adding a note/TODO/issue to revert it at some point

What should the trigger of this revert be? Is there something expected after which we won't need to normalize versions?

> I'd also make a small correction here that version offsetting does not depend on the crdb_test build flag; offsetting happens if the binary is not considered a release binary

👍

2023-01-31 14:35 UTC, renatolabs commented
> What should the trigger of this revert be?

Once #92608 is closed.

2023-02-01 12:59 UTC, ajstorm approved these changes
I like this change much better than the initial one, but it's not clear to me that it's what we want long-term.  I'd think that the long-term fix here is to ensure that the create tenant code respects the version overrides contained in the testing knobs.  That way we won't need the offset ignoring code.  I'm OK to merge this now if we plan to add the testing knobs fix in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95904#-:-NNC2Azj5CPkOyjhE432:bpsevqe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @knz, @postamar, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/multitenant_upgrade.go` line 315 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95904#-NN1xZU15B90gPGr3tY9:-NN1xZU15B90gPGr3tYA:b-yvsrxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/452c5eec2bdf63ef503f9f97a0fc9566b436cc5f/pkg/cmd/roachtest/tests/multitenant_upgrade.go#L315)):*
> ```Go
> ) {
> 	normalizeVersion := func(v roachpb.Version) roachpb.Version {
> 		if (v.Major - clusterversion.DevOffset) >= 0 {
> ```

Nit: it might beeasier to understand this code if it was written as:

`if v.Major > clusterversion.DevOffset {`


<!-- Sent from Reviewable.io -->

2023-02-01 18:03 UTC, healthy-pod reviewed
We added the tenant logical version overrides in #94973, this is not related to that. Previously (ie before #94774) we used to set the tenant logical version to be exactly the storage logical version. As in, we read the SLV and set the TLV to that. Now this is not true, it's either the SBV if it's equal to the SLV or otherwise the min version the storage binary can use to create a tenant. What happens here is:

current binary = non-release binary with version offset
predecessor binary = release binary without version offset

- storage starts with `predecessor binary` and its logical version is `predecessor binary` so SLV doesn't have offset
- storage upgrades to `current binary` but doesn't finalize so SLV is still without offset
- storage binary now though is `current binary` which is non-release and when it "calculates" the tenant creation version (instead of what used to happen previously which was just copying SLV) it will be the min supported version of `current binary` which happens to be `predecessor binary` but with offset because current binary is not a release binary even if storage didn't finalize yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95904#-:-NNCk7d1EL-9HFRjqV44:b-cet5ge)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @postamar, @smg260, and @srosenberg)



<!-- Sent from Reviewable.io -->

2023-02-02 03:29 UTC, healthy-pod commented
bors r=ajstorm

2023-02-02 05:22 UTC, merged