ui: add search, filter and time picker on index details
cockroachdb/cockroach pull request #96112
Opened 2023-01-27 18:38 UTC by maryliag

Fixes #93087

This commit adds search, filters and time picker for the list of fingerprints most used per index, on the Index Details page.

It also limits to 20 fingerprints until we can make improvements to use pagination on our calls with
sql-over-http.

With no filters
<img width="1669" alt="Screen Shot 2023-01-27 at 1 37 35 PM" src="https://user-images.githubusercontent.com/1017486/215167830-bd119e13-a875-49bd-9c8d-305230dd4b01.png">

With filters
<img width="1508" alt="Screen Shot 2023-01-27 at 1 37 49 PM" src="https://user-images.githubusercontent.com/1017486/215167846-c668d79a-7a59-420e-b96c-2eff6a50aca6.png">

https://www.loom.com/share/d4129452593a40198902a5f2539d8568

Release note (ui change): Add search, filter and time picker for the list of most used statement fingerprints on the Index Details page.

2023-01-27 18:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/96112)
<!-- Reviewable:end -->

2023-01-27 21:27 UTC, dongniwang commented
nice! LGTM!

2023-01-31 16:07 UTC, ericharmeling reviewed
Looks good! I have a nit (see below) and a question: 

Do we need to add a `put(indexStats.invalidated())` to the `sqlStats.sagas.ts`?

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-:-NN7ZKFeC4spgzoZjmFF:bs6zkwk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dongniwang and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7Twp4E_APszwoRr0s:-NN7Twp4E_APszwoRr0t:b9uui0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L240)):*
> ```XML
>     )
>     .filter(statement =>
>       search ? filterBySearchQuery(statement, search) : true,
> ```

nit:

Because this function is being exported for use in the `indexDetailsPage.tsx`, should we move it into a new file in the `sqlActivity` directory (or something "shared")?



_Code quote:_
```XML
export function filteredStatementsData(
  filters: Filters,
  search: string,
  statements: AggregateStatistics[],
  nodeRegions: { [key: string]: string },
  isTenant: boolean,
): AggregateStatistics[] {
  const timeValue = getTimeValueInSeconds(filters);
  const sqlTypes =
    filters.sqlType.length > 0
      ? filters.sqlType.split(",").map(function (sqlType: string) {
          // Adding "Type" to match the value on the Statement
          // Possible values: TypeDDL, TypeDML, TypeDCL and TypeTCL
          return "Type" + sqlType;
        })
      : [];
  const databases =
    filters.database.length > 0 ? filters.database.split(",") : [];
  if (databases.includes(unset)) {
    databases.push("");
  }
  const regions = filters.regions.length > 0 ? filters.regions.split(",") : [];
  const nodes = filters.nodes.length > 0 ? filters.nodes.split(",") : [];

  // Return statements filtered by the values selected on the filter and
  // the search text. A statement must match all selected filters to be
  // displayed on the table.
  // Current filters: search text, database, fullScan, service latency,
  // SQL Type, nodes and regions.
  return statements
    .filter(
      statement =>
        databases.length == 0 || databases.includes(statement.database),
    )
    .filter(statement => (filters.fullScan ? statement.fullScan : true))
    .filter(
      statement =>
        statement.stats.service_lat.mean >= timeValue || timeValue === "empty",
    )
    .filter(
      statement =>
        sqlTypes.length == 0 || sqlTypes.includes(statement.stats.sql_type),
    )
    .filter(
      // The statement must contain at least one value from the selected regions
      // list if the list is not empty.
      statement =>
        regions.length == 0 ||
        (statement.stats.nodes &&
          containAny(
            statement.stats.nodes.map(
              node => nodeRegions[node.toString()],
              regions,
            ),
            regions,
          )),
    )
    .filter(
      // The statement must contain at least one value from the selected nodes
      // list if the list is not empty.
      // If the cluster is a tenant cluster we don't care
      // about nodes.
      statement =>
        isTenant ||
        nodes.length == 0 ||
        (statement.stats.nodes &&
          containAny(
            statement.stats.nodes.map(node => "n" + node),
            nodes,
          )),
    )
    .filter(statement =>
      search ? filterBySearchQuery(statement, search) : true,
    );
}
```


<!-- Sent from Reviewable.io -->

2023-01-31 16:24 UTC, maryliag reviewed
> Do we need to add a put(indexStats.invalidated()) to the sqlStats.sagas.ts?

the new information that I added is not on our cache, so there is no need to invalidate. Since this page works a little different than SQL Activity (in the sense people won't just open and stare at it for minutes), I just get the new data for the list of fingerprints each time. So there is no need to invalidate anything right now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-:-NN7bgyB1-gOadoFESJj:b-6ain1h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dongniwang and @ericharmeling)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7Twp4E_APszwoRr0s:-NN7dCjWD-673a30KSQf:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L240)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit:

Because this function is being exported for use in the `indexDetailsPage.tsx`, should we move it into a new file in the `sqlActivity` directory (or something "shared")?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-31 16:27 UTC, xinhaoz requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dongniwang, @ericharmeling, and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7_cyc69uAAyTYbpo9:-NN7_cyc69uAAyTYbpoA:bkfpk4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts#L132)):*
> ```XML
> 
>   const statements: AggregateStatistics[] = [];
>   result.execution.txn_results[0].rows.forEach(s => {
> ```

nit: this can be a map, setting the variable above directly.
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetails.selectors.ts` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7cYpP2zu3bY26JDap:-NN7cYpP2zu3bY26JDaq:b-rha3x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetails.selectors.ts#L95)):*
> ```XML
>       ),
>       isTenant: isTenant,
>       timeScale: timeScale,
> ```

I know this wasn't created in this PR, but this selector creation looks off. It looks like this `selectIndexDetails` function is actually a mapStateToProps for the index details component. So now what we're doing is every time one of these parameters changes, we run the body which regenerates the breadcrumbs and index details, event hough something like nodeRegions has no effect on either fields. We might want to split these up into their respective fields (doesn't have to be in this PR). cc @THardy98   in case there was a reason to batch these all together
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx` line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7cw9Q5mOhRFzaMNvG:-NN7cw9R3ys6JyQZxRO0:b-gght69) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx#L184)):*
> ```XML
>     this.refresh();
> 
>     setInterval(() => {
> ```

This interval needs to be cleared on dismount.
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx` line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7dEUN3VkmeMSeLjY8:-NN7dEUN3VkmeMSeLjY9:b-cmgcnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx#L262)):*
> ```XML
> 
>   private refreshStatementsList(): void {
>     const noData = this.state.lastStatementsUpdated === null;
> ```

nit: prefer unstrict equality check here to catch also undefined (unless you specifically wanted to not catch that, then ignore this comment)
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx` line 605 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7dxBjEW4WuLGubEtV:-NN7dxBjEW4WuLGubEtW:bxwjmev) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx#L605)):*
> ```XML
>                     </PageConfig>
>                     <Loading
>                       loading={statements === null}
> ```

same thing here


<!-- Sent from Reviewable.io -->

2023-01-31 16:48 UTC, ericharmeling approved these changes
> the new information that I added is not on our cache, so there is no need to invalidate.

Ah, I see that. Okay! LGTM

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-:-NN7iaE00bNAFsEzYYMG:bsoel70)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dongniwang and @maryliag)



<!-- Sent from Reviewable.io -->

2023-01-31 17:09 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dongniwang, @THardy98, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7_cyc69uAAyTYbpo9:-NN7jt8JDFYlGWdMOyNA:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts#L132)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: this can be a map, setting the variable above directly.
</blockquote></details>

Done
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetails.selectors.ts` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7cYpP2zu3bY26JDap:-NN7lEAn2b7tc-qSHnWD:b-1lyhhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetails.selectors.ts#L95)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I know this wasn't created in this PR, but this selector creation looks off. It looks like this `selectIndexDetails` function is actually a mapStateToProps for the index details component. So now what we're doing is every time one of these parameters changes, we run the body which regenerates the breadcrumbs and index details, event hough something like nodeRegions has no effect on either fields. We might want to split these up into their respective fields (doesn't have to be in this PR). cc @THardy98   in case there was a reason to batch these all together
</blockquote></details>

Created issue https://github.com/cockroachdb/cockroach/issues/96277
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx` line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7cw9Q5mOhRFzaMNvG:-NN7m_KV4Vc0emvw--r7:b-gjka0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx#L184)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

This interval needs to be cleared on dismount.
</blockquote></details>

ohh nice catch! forgot to do that! thanks!
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx` line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7dEUN3VkmeMSeLjY8:-NN7n5-8-i06BVCI628j:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx#L262)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: prefer unstrict equality check here to catch also undefined (unless you specifically wanted to not catch that, then ignore this comment)
</blockquote></details>

Done
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx` line 605 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-NN7dxBjEW4WuLGubEtV:-NN7nII4ARr2JgxW8ho5:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea62f2eb1727d3ef00174d86aa398fac2b12b6ee/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx#L605)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

same thing here
</blockquote></details>

Done



_Code quote:_
```XML
oading={statements === null
```


<!-- Sent from Reviewable.io -->

2023-01-31 19:43 UTC, xinhaoz approved these changes
Nice! 
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> :

> Reviewed 3 of 10 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96112#-:-NN8LcbD2YSUh7Z7rR4s:b-gqww2l)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dongniwang and @THardy98)



<!-- Sent from Reviewable.io -->

2023-01-31 19:47 UTC, maryliag commented
TFTR!
bors r+

2023-01-31 22:59 UTC, merged