sql: add a SHOW CLUSTER SETTING sql.defaults deprecation notice
cockroachdb/cockroach pull request #96155
Opened 2023-01-29 14:33 UTC by mastersobg

Release note (sql change): The `ALTER ROLE` syntax` allows users to set default values for session variables making `SET CLUSTER SETTINGS sql.defaults...` redundant. This PR adds a notice to `SHOW CLUSTER SETTING sql.defaults...` that directs the user to use the `ALTER ROLE` syntax instead.

Fixes: #88520

2023-01-29 14:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/96155)
<!-- Reviewable:end -->

2023-02-02 22:46 UTC, rafiss requested changes
thanks for your contribution! i have left a few comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96155#-:-NNJIaHZ1RPzENmkAy_I:b-aeca7u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dikshant and @mastersobg)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96155#-NNJIdv3-pDSnzzG4x3V):*
you can use `Release note: None` for this, since no behavior is changed. it's just modifying the message shown to the user

(this info is still useful for the commit message, but just doesn't need to be in a release note)
___
*[`pkg/sql/show_cluster_setting.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96155#-NNJHtFiDtccDOZ9bioC:-NNJHtFiDtccDOZ9bioD:b-ctgun0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1fb1edb3d555d26aa33514d5778c94c4a616cdf/pkg/sql/show_cluster_setting.go#L131)):*
> ```Go
> 	}
> 
> 	p.noticeSqlDefaultsAccess(ctx, n)
> ```

this is only used in one place, so i think it would be simpler to inline that code here
___
*[`pkg/sql/logictest/testdata/logic_test/show_setting_defaults_notice` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96155#-NNJI1A8Af8n9czKxDW8:-NNJI1A8Af8n9czKxDW9:bg7qn2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1fb1edb3d555d26aa33514d5778c94c4a616cdf/pkg/sql/logictest/testdata/logic_test/show_setting_defaults_notice#L1)):*
> ```
> query T noticetrace
> ```

this is a good test! but instead of making a new file, can you put this in pkg/sql/logictest/testdata/logic_test/cluster_settings


<!-- Sent from Reviewable.io -->

2023-02-03 06:35 UTC, mastersobg reviewed
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96155#-:-NNKv_GUAgEDR-zJoDKO:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dikshant and @rafiss)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96155#-NNJIdv3-pDSnzzG4x3V):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

you can use `Release note: None` for this, since no behavior is changed. it's just modifying the message shown to the user

(this info is still useful for the commit message, but just doesn't need to be in a release note)
</blockquote></details>

Thanks, fixed!
___
*[`pkg/sql/show_cluster_setting.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96155#-NNJHtFiDtccDOZ9bioC:-NNKusP1D9hgrl5gsKa9:undefined) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1fb1edb3d555d26aa33514d5778c94c4a616cdf/pkg/sql/show_cluster_setting.go#L131)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is only used in one place, so i think it would be simpler to inline that code here
</blockquote></details>





_Suggestion:_
```Go
Thanks, fixed.
```
___
*[`pkg/sql/logictest/testdata/logic_test/show_setting_defaults_notice` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96155#-NNJI1A8Af8n9czKxDW8:-NNKvPAc4ggkTx5GOg3M:b-8gcx32) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1fb1edb3d555d26aa33514d5778c94c4a616cdf/pkg/sql/logictest/testdata/logic_test/show_setting_defaults_notice#L1)):*
> sql/logictest/testdata/logic_test/cluster_settings
Fixed


<!-- Sent from Reviewable.io -->

2023-02-07 22:32 UTC, rafiss approved these changes
thanks for your contribution! we can merge this now

bors r+

2023-02-07 23:50 UTC, merged