kvcoord:  Fix multiple MuxRangeFeed client bugs
cockroachdb/cockroach pull request #96230
Opened 2023-01-30 20:40 UTC by miretskiy

This PR addresses multiple issues with MuxRangeFeed client
implementation, identified by running various CDC stress tests.

The first issue was incorrect context used when establishing
MuxRangeFeed with a node.  When calling `startMuxRangeFeed`, the caller
provided context was used to establish the RPC with a node.
However, this context was meant to be used only for a single range
rangefeed -- and not for a node level MuxRangeFeed RPC.  As a result,
as soon as the first rangefeed completed (perhaps due to an error, such
as range split), the entire node level MuxRangeFeed, along with all of
the ranges running on that node, would be canceled.

The second issue is a race between consumer termination (consumer is a
single range rangefeed), and the "demux" loop.  There were really two
races here.  First, when we return an error to the caller (e.g. range
split), the caller simply executes cleanup and returns.  The cleanup
removes the information about the stream from the mux rangefeed, which
produces an error.  Secondly, it is possible for the demux loop to
observe additional events even after receving event error.
This is because the rangefeed processor (server side) termination is asynchronous.
It is possible that when the server shuts down (i.e. cancels) output
loop due to an error (range split), the internal buffer may still have
some events (such as checkpoint).  It's a race whether or not such
event will be sent on the RPC stream.  If such event arrives,
demux loop will block forever because the caller already terminated.

The fixes in thisThis were verified by verifying clean, non-flaky
execution over 25000 runs of multiple CDC tests
(TestChangefeedInitialScanOnly, and others).

Informs #95781

Release note: None

2023-01-30 20:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/96230)
<!-- Reviewable:end -->

2023-01-30 21:38 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @erikgrinaker, and @jayshrivastava)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NN3PNWvk9kf7Uzzq199-r1-37:-NN3XLhG4cU5M7iDOZs-:b-gn0tdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a7658b87327c8b96c52482954369d47dbfc92e/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L37)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

cute, but why?
</blockquote></details>

Ahh... I just felt it communicated better that this is mux related state.
This code underwent quite a few changes, including one where I had no locks involved (atomic ref counting).. But, kinda that's what transpired now.  I can revert if you prefer mu.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NN3PNWvk9kf7Uzzq199-r1-54:-NN3XZ9_-ssTkBfvtci6:bdd4vz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a7658b87327c8b96c52482954369d47dbfc92e/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L54)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

seems like a good fit for `syncutil.IntMap`
</blockquote></details>

Good idea. done.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NN3PNWvk9kf7Uzzq199-r1-110:-NN3YKDC97sdD1o5JZAO:bv7lgr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a7658b87327c8b96c52482954369d47dbfc92e/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L110)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

wait, this does hold a mutex while there's an RPC, doesn't it? I don't know about this. 
</blockquote></details>

I think the setup did involve RPC (MuxRangeFeed), this version also issues Send to start single range feed on mux rangefeed.  But, it's an easy enough change to not hold the lock during the send.


<!-- Sent from Reviewable.io -->

2023-01-30 22:15 UTC, ajwerner reviewed
Can you remind me of the threading model? If I remember correctly, we have:

Client side:
1 in `RangeFeedSpans` blocked on Wait
1 in `demuxLoop`
1 per node in `recieveFromNode`
1 per range in `singleRangeFeed`

Server side:
1 per node in MuxRangeFeed
1 per range blocked in RangeFeed
1 per range in the processor
1 per range in the registration output loop?

The difference in goroutines, then, comes down to what? I count one fewer on the server and ... no fewer anywhere else. What am I missing?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-:-NN3gNCRAqz8pKRZKAYA:b-77shpk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @jayshrivastava, and @miretskiy)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NN3PNWvk9kf7Uzzq199-r1-37:-NN3feuL6a7_wCFI42QI:btcjgip) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a7658b87327c8b96c52482954369d47dbfc92e/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L37)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Ahh... I just felt it communicated better that this is mux related state.
This code underwent quite a few changes, including one where I had no locks involved (atomic ref counting).. But, kinda that's what transpired now.  I can revert if you prefer mu.
</blockquote></details>

please do rename it back to `mu`. The struct is already called `rangefeedMuxer`. The reason we have an embedded structure is to indicate the locking. 
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NN3PNWvk9kf7Uzzq199-r1-110:-NN3fxGs8JAXldpWlUxK:b-nu2gbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a7658b87327c8b96c52482954369d47dbfc92e/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L110)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think the setup did involve RPC (MuxRangeFeed), this version also issues Send to start single range feed on mux rangefeed.  But, it's an easy enough change to not hold the lock during the send.
</blockquote></details>

Yes, please change the code to not hold onto the mutex for the RPC.


<!-- Sent from Reviewable.io -->

2023-01-30 22:32 UTC, miretskiy reviewed
I think you have it right; The way the MuxRangeFeed was implemented was not to change the existing dist_sender_rangefeed. 
 As a result, there aren't that many changes threading model wise (to be clear -- I think it is possible to get rid of singleRangeFeed go routine, but that required significant changes in dist_Sender_rangefeed, and that was not done)

We did however see significant impact when muxrf was tried in prod.  So, what gives? My best guess: underlying grpc  and/or http2 probably/likely creates go routines to process stream responses;  It's a guess though .

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-:-NN3lS164eG1lYlt7lbs:b9xi436)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @erikgrinaker, and @jayshrivastava)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NN3PNWvk9kf7Uzzq199-r1-37:-NN3ksDS6j2nCdjf0K70:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a7658b87327c8b96c52482954369d47dbfc92e/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L37)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

please do rename it back to `mu`. The struct is already called `rangefeedMuxer`. The reason we have an embedded structure is to indicate the locking. 
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NN3PNWvk9kf7Uzzq199-r1-110:-NN3kuQe73xAOh8BK7gK:b-swd7q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a7658b87327c8b96c52482954369d47dbfc92e/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L110)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yes, please change the code to not hold onto the mutex for the RPC.
</blockquote></details>

To clarify: you don't want any locks held during establishment of the rpc (we have MuxRangeFeed + Send to start actual range)?

Old code also held this lock for the MuxRangeFeed portion, but not for the Send -- just like this version.

I think it might actually be something that we would want to do; otherwise, you'll wind up with multiple callers racing to establish connection.  Given that we may have 100s-1000s of ranges on a node, the chance of this race is pretty high.  


<!-- Sent from Reviewable.io -->

2023-01-30 22:37 UTC, ajwerner reviewed
Yeah, that's why I'm asking. It doesn't make sense to me. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-:-NN3oybo446lTstw3lu6:bhrx8d5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @jayshrivastava, and @miretskiy)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NN3PNWvk9kf7Uzzq199-r1-110:-NN3okJa2WOa4oAm6pON:b-hjoefa) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a7658b87327c8b96c52482954369d47dbfc92e/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L110)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

To clarify: you don't want any locks held during establishment of the rpc (we have MuxRangeFeed + Send to start actual range)?

Old code also held this lock for the MuxRangeFeed portion, but not for the Send -- just like this version.

I think it might actually be something that we would want to do; otherwise, you'll wind up with multiple callers racing to establish connection.  Given that we may have 100s-1000s of ranges on a node, the chance of this race is pretty high.  
</blockquote></details>

I don't understand. This is a rather common pattern. Grab the lock, kick off the goroutine, install state in the map so concurrent attempts will see it, release the lock. 


<!-- Sent from Reviewable.io -->

2023-01-30 22:39 UTC, miretskiy commented
> I don't understand. This is a rather common pattern. Grab the lock, kick off the goroutine, install state in the map so concurrent attempts will see it, release the lock.

Sure, I was just pointing out that this version is *no* different from what was there before, and wanted to confirm
that that's what you want -- namely, also fix this locking -- even though it's not changed by this PR.

2023-01-30 22:44 UTC, miretskiy commented
> I don't understand. This is a rather common pattern. Grab the lock, kick off the goroutine, install state in the map so concurrent attempts will see it, release the lock.

Actually, I don't understand why you think it's important.  singleRangeFeed calls this method, perhaps concurrently; all
of those block until MuxRangeFeed establishes connection; then they proceed to issue Send for their single range request.
Why complicate anything else?

2023-01-30 22:45 UTC, ajwerner commented
Fair enough. Also, I think there is another goroutine in the grpc code.

2023-01-30 22:45 UTC, ajwerner commented
It means that context cancellation won't work if you're blocked on the network.

2023-01-30 23:04 UTC, miretskiy commented
> It means that context cancellation won't work if you're blocked on the network.

I think the question is whether or not grpc respects cancellation during connection setup.  If it does, then I think the code can remain the same -- we just quickly terminate if ctx is cancelled -- no need for complexity.

If we assume that it doesn't, then things are no worse, I think.  I mean, sure, I can add the code to make all of this async, but then, when context is cancelled, instead of blocking singleRangeFeed during attempt to establish mux, I'll block waiting for all of those go routines to exit (which will happen after they establish connection, if we assume that grpc doesn't respect cancellation during the setup).

2023-01-31 00:01 UTC, ajwerner commented
I had forgotten that all possible callers who would block are sharing a context in effect.

2023-01-31 16:15 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @erikgrinaker, and @jayshrivastava)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NN3PNWvk9kf7Uzzq199-r1-110:-NN7bE2O0fHwOO552gZ8:bt5t5y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/79a7658b87327c8b96c52482954369d47dbfc92e/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L110)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't understand. This is a rather common pattern. Grab the lock, kick off the goroutine, install state in the map so concurrent attempts will see it, release the lock. 
</blockquote></details>

Done.  Discussed; 


<!-- Sent from Reviewable.io -->

2023-01-31 17:48 UTC, jayshrivastava approved these changes
Looks good from the changefeed side of things. I'll let someone else approve rangefeed changes.

2023-02-01 15:32 UTC, tbg requested changes
Looks pretty good - I think something about `startNodeMuxRangeFeed` and `connectDone` and holding the mutex across things is off, see the comments. Either we're holding the mutex across network I/O which is bad, or we're not but calling it "connecting" but don't actually "connect" in any meaningful way. One of the two has to give, I think. I'd try to get that critical section down to something that's "obviously" safe.

I'm pushing a commit with a few comment fixes and small improvements. Take the ones you agree with and let's discuss the rest if there's any.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-:-NNCaP4aAdWdXi04gAl4:b-ronohu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @erikgrinaker, and @miretskiy)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 34 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCW5Oc0XBZHrsIFSHw:-NNCW5Oc0XBZHrsIFSHx:bgf7s1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L34)):*
> ```Go
> 	eventCh chan *roachpb.MuxRangeFeedEvent
> 
> 	// Context group controlling execution of MuxRangeFeed calls.
> ```

This isn't new but could you add more info on how this is used? I don't think we ever `Wait` on this, but if any of the goroutines returns an error everyone's context will be canceled. Is this what we want? Are errors every expected to be returned during normal operation?

I answered this for myself reading the code - basically the goroutines running in these are `receiveEvents` and it normally returns `nil`, except when it sees its context canceled - this happens only when the mux has become inactive and is torn down, which is after the async goroutine has already exited. So I think the only role this `cancel()` really has is shutting down `(*muxClientState).client`.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 104 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNC_xri8C49oLGRhc0f:-NNC_xrj7ji_-lrDIdZg:b-mjj4bz) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ef5d9d7a646831799faa0f0611834fe032b93b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L104)):*
> ```Go
> 	ctx context.Context, client rpc.RestrictedInternalClient, req *roachpb.RangeFeedRequest,
> ) (_ roachpb.RangeFeedEventProducer, cleanup func(), _ error) {
> 	producer, rpcClient, streamID, cleanup, err := m.connect(ctx, client, req.Replica.NodeID)
> ```

Was this the buggy `ctx`? It looks like this was the ctx from `RangeFeedSpans` before and after this PR, so probably not. Could you point me at 
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 170 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCQIDN4Nstax09jIqn:-NNCQIDN4Nstax09jIqo:b-id663e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L170)):*
> ```Go
> 			return 0, nil, err
> 		}
> 		m.mu.clients[nodeID] = ms
> ```

I know this is a single critical section, but it makes sense to me to insert into the map before the call to startNodeMuxRangeFeed above.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 211 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCRcyD3keuGaShnO9q:-NNCRcyD3keuGaShnO9r:bmb4uqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L211)):*
> ```Go
> 		defer ms.cancel()
> 
> 		ms.client, err = client.MuxRangeFeed(ctx)
> ```

I'd have to double check but I don't think this "connects" anything? It just makes the client.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 219 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCQkXhAXkVLhG2wHu8:-NNCQkXhAXkVLhG2wHu9:be7kkuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L219)):*
> ```Go
> 	})
> 
> 	return ms, <-m.mu.connectDone
> ```

This is weird - this effectively holds the mutex open for the duration of the connect attempt. I don't think this is what you want? We should never hold this mutex across any I/O.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 279 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCUBta5a90J4BwWUZF:-NNCUBta5a90J4BwWUZG:b8crjrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L279)):*
> ```Go
> 		if streamErr != nil {
> 			s.recvErr = streamErr
> 			close(s.done)
> ```

How is this related to cancellation of `ctx`? I see that `muxClientState` has a cancellation function. Shouldn't we call `cancel` here, and then nobody would have to listen to `s.done` and we could remove it?

I *think* the answer for why things are the way they are is that you'd have to synchronize access to `s.recvErr`, because it's now unclear whether `ctx.Done()` would be closed as a result of higher-level ctx cancellation or because we set `recvErr` here.

Still, I think having two ways to cancel a thing is asking for trouble, so at least document more clearly how everything is set up if you think we can't simplify it. Personally, I'd try to do away with `s.done` (instead holding on to the `Done()` channel of the context for `s.cancel`), and make `recvErr` an `atomic.Value`. Access to it would go through code like this:

```go
func (s *muxClientState) Err() error {
  if err, _ := s.recvErr.Load().(error); err != nil { return err }
  return s.ctxErr()
}
```

adn the code at this comment would be

```go
s.recvErr.Store(streamErr)
s.cancel()
```

I'm also not clear why we `return nil` here whereas we return `ctx.Err()` (non-nil) in the case of ctx cancellation. When is that ctx cancelled?


<!-- Sent from Reviewable.io -->

2023-02-01 19:17 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @erikgrinaker, and @tbg)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 34 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCW5Oc0XBZHrsIFSHw:-NND2Lmv6FevUY0FFTrJ:bpy62vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L34)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This isn't new but could you add more info on how this is used? I don't think we ever `Wait` on this, but if any of the goroutines returns an error everyone's context will be canceled. Is this what we want? Are errors every expected to be returned during normal operation?

I answered this for myself reading the code - basically the goroutines running in these are `receiveEvents` and it normally returns `nil`, except when it sees its context canceled - this happens only when the mux has become inactive and is torn down, which is after the async goroutine has already exited. So I think the only role this `cancel()` really has is shutting down `(*muxClientState).client`.

</blockquote></details>

Exactly right; thanks for the improved comment.



_Code quote:_
```Go
	// Context group controlling execution of MuxRangeFeed calls. When this group
	// cancels, the entire muxer shuts down. The goroutines started in `g` will
	// always return `nil` errors except when they detect that the mux is shutting
	// down.
```
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 104 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNC_xri8C49oLGRhc0f:-NND2SJaBXM3vdD83Wy5:beuzg10) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ef5d9d7a646831799faa0f0611834fe032b93b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L104)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Was this the buggy `ctx`? It looks like this was the ctx from `RangeFeedSpans` before and after this PR, so probably not. Could you point me at 
</blockquote></details>

It's the context that came from singleRangeFeed method in dist_sender_rangefeed; and this context
is cancelled as soon as that single range feed returns.  Prior, we used that context to established node level connection -- so, when that single range feed returned, it would cancel all other rangefeeds.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 211 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCRcyD3keuGaShnO9q:-NND2ows0Dc3NqiF4h7o:bjxl4kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L211)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'd have to double check but I don't think this "connects" anything? It just makes the client.
</blockquote></details>

I believe you are correct; it doesn't start anything until we are sending.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 219 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCQkXhAXkVLhG2wHu8:-NND2sxO387j4I7s1x-R:b1l1ihn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L219)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This is weird - this effectively holds the mutex open for the duration of the connect attempt. I don't think this is what you want? We should never hold this mutex across any I/O.
</blockquote></details>

Well, that's the thing: I don't think it's a problematic area.
As you say, MuxRangefeed doesn't actually connect to anything -- it's a local client.
But, even if it did, I still think it's okay.  I'm almost sure we'd want to make sure we don't have multiple
ranges attempt to connect to the same node at the same time;
Now, of course, more complexity can be added (more state) -- but I honestly don't see why.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 279 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCUBta5a90J4BwWUZF:-NND4kT85i1Ns-18Z-Qn:b-jtd9c5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L279)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

How is this related to cancellation of `ctx`? I see that `muxClientState` has a cancellation function. Shouldn't we call `cancel` here, and then nobody would have to listen to `s.done` and we could remove it?

I *think* the answer for why things are the way they are is that you'd have to synchronize access to `s.recvErr`, because it's now unclear whether `ctx.Done()` would be closed as a result of higher-level ctx cancellation or because we set `recvErr` here.

Still, I think having two ways to cancel a thing is asking for trouble, so at least document more clearly how everything is set up if you think we can't simplify it. Personally, I'd try to do away with `s.done` (instead holding on to the `Done()` channel of the context for `s.cancel`), and make `recvErr` an `atomic.Value`. Access to it would go through code like this:

```go
func (s *muxClientState) Err() error {
  if err, _ := s.recvErr.Load().(error); err != nil { return err }
  return s.ctxErr()
}
```

adn the code at this comment would be

```go
s.recvErr.Store(streamErr)
s.cancel()
```

I'm also not clear why we `return nil` here whereas we return `ctx.Err()` (non-nil) in the case of ctx cancellation. When is that ctx cancelled?
</blockquote></details>

I don't think we have two ways to cancel; and I don't see (at least yet) a way to get rid of done.
Large part of the complexity here is because Recv rpc method doesn't take context.
At any rate, I'll start with the last parts of your question first; namely questions about receveEvents termination.  I agree with you that it is confusing that we had "return nil", and "return ctx.Err()".  I've fixed this using more explicit muxDone channel.  Basically, this go routine, as you noted in your earlier comment, should never return an error; if the stream is broken, the error propagates to the callers (waiting on Recv), and if the main rangefeed is done, then, we just exit. I've replace the confusing context with a channel that's closed when demuxLoop exit;  when that happens, there is no more reader for eventCh, and we should exit all of the "receveEvents" go routines.

The other part regarding done method -- I don't see how to remove it.  I have renamed context fields in channelRangeFeedEventProducer, and added documentation on the interaction of those two context.
Basically, one context is from the caller -- the singleRangeFeed contexts.  That context may be cancelled, and we need to respect that.  On the other hand, the MuxRangeFeed go routine may also encounter an error -- and the caller blocked in Recv() must respect both of these signals.

Let me know if the comment I've added is sufficient.


<!-- Sent from Reviewable.io -->

2023-02-02 10:28 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks for sticking with me. I pushed another fixup commit but no functional changes, so take what you like and leave the rest.

Something I had forgotten - we probably want to backport this; maybe some of my renames are a bad idea in light of that, though if they backport cleanly and you like them I would suggest we keep them.

There are still 1-2 places where I'm unsure if we really want to tear down the entire thing, I left comments inline on those, but even if we don't fix them now - after this PR things are going to work a whole lot better and since you have tested this PR extensively we should merge it without further changes that could cause unexpected side effects.

> Dismissed @ajwerner and @miretskiy from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-:-NNGeFgv4xDiPV6UzxFN:b-89jxeq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @erikgrinaker, and @miretskiy)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 104 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNC_xri8C49oLGRhc0f:-NNG_Q_L3Ll7eBpGxFVu:b-astka5) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ef5d9d7a646831799faa0f0611834fe032b93b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L104)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

It's the context that came from singleRangeFeed method in dist_sender_rangefeed; and this context
is cancelled as soon as that single range feed returns.  Prior, we used that context to established node level connection -- so, when that single range feed returned, it would cancel all other rangefeeds.
</blockquote></details>

:thumbsup: I understand this now. Added a comment for the next poor soul, I missed where this was called at first since it was hidden behind the streamProducerFactory.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 219 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCQkXhAXkVLhG2wHu8:-NNGPyn-2esgYuFHS7xN:b-o280cv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L219)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Well, that's the thing: I don't think it's a problematic area.
As you say, MuxRangefeed doesn't actually connect to anything -- it's a local client.
But, even if it did, I still think it's okay.  I'm almost sure we'd want to make sure we don't have multiple
ranges attempt to connect to the same node at the same time;
Now, of course, more complexity can be added (more state) -- but I honestly don't see why.

</blockquote></details>

By holding the mutex over network I/O to node 1, you block connection attempts to any other nodes. So it does in theory matter. I touched this up a little bit more - but left it functionally unchanged.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 279 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCUBta5a90J4BwWUZF:-NNGdhpnBaVRjNFtwLmW:bo2vs3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L279)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't think we have two ways to cancel; and I don't see (at least yet) a way to get rid of done.
Large part of the complexity here is because Recv rpc method doesn't take context.
At any rate, I'll start with the last parts of your question first; namely questions about receveEvents termination.  I agree with you that it is confusing that we had "return nil", and "return ctx.Err()".  I've fixed this using more explicit muxDone channel.  Basically, this go routine, as you noted in your earlier comment, should never return an error; if the stream is broken, the error propagates to the callers (waiting on Recv), and if the main rangefeed is done, then, we just exit. I've replace the confusing context with a channel that's closed when demuxLoop exit;  when that happens, there is no more reader for eventCh, and we should exit all of the "receveEvents" go routines.

The other part regarding done method -- I don't see how to remove it.  I have renamed context fields in channelRangeFeedEventProducer, and added documentation on the interaction of those two context.
Basically, one context is from the caller -- the singleRangeFeed contexts.  That context may be cancelled, and we need to respect that.  On the other hand, the MuxRangeFeed go routine may also encounter an error -- and the caller blocked in Recv() must respect both of these signals.

Let me know if the comment I've added is sufficient.


</blockquote></details>

Good changes, thank you! I added a bit more docs and made some renames - I don't want to force them upon you, they just helped me clarify "who's who" a bit more. For example, `streamCtx` was the caller, but we also maintain a node-level stream, so there was opportunity for confusion.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 37 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNGWAsY-lM8Ns0gXyhA:-NNGWAsY-lM8Ns0gXyhB:b305lz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/04401070acff881c953b39eca850ad4e01364d27/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L37)):*
> ```Go
> 	// cancels, the entire muxer shuts down. The goroutines started in `g` will
> 	// always return `nil` errors except when they detect that the mux is shutting
> 	// down.
> ```

This one doesn't: https://github.com/cockroachdb/cockroach/blob/217fcf1f4b415dc142e2e01fc3529cb1e471be6f/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L206-L209

Looking at the code below this call (`singleRangeFeed` and `partialRangeFeed`) it seems like they default to passing errors up if they can't handle them internally. Isn't this a problem?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 241 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNGXdtd55twMZe3839r:-NNGXdtd55twMZe3839s:b-66x4x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/04401070acff881c953b39eca850ad4e01364d27/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L241)):*
> ```Go
> // consumer.
> func (m *rangefeedMuxer) demuxLoop(ctx context.Context) (retErr error) {
> 	defer close(m.muxDone)
> ```

`m.demuxLoopDone` could make it even clearer - any bit of clarity helps with all the moving parts in action here :-)


<!-- Sent from Reviewable.io -->

2023-02-02 13:38 UTC, miretskiy reviewed
Thanks for thorough review, and lots of good questions and suggestions.  Yes, we want to backport this, but I'm not concerned about this -- it's almost a whole file replacement.  I'll try to address your comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-:-NNH06F6DavV4Trp0DFW:bk6d9xa)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @erikgrinaker, and @tbg)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 279 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNCUBta5a90J4BwWUZF:-NNH3AMPArhCWvgZN4c1:baog407) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba283726d2cd14df6467c0ac88d20c42b4c068b/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L279)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Good changes, thank you! I added a bit more docs and made some renames - I don't want to force them upon you, they just helped me clarify "who's who" a bit more. For example, `streamCtx` was the caller, but we also maintain a node-level stream, so there was opportunity for confusion.
</blockquote></details>

Ack -- took all of your suggestions.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 37 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNGWAsY-lM8Ns0gXyhA:-NNH0KZ719Qu44BTXk0C:b-6cqz4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/04401070acff881c953b39eca850ad4e01364d27/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L37)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This one doesn't: https://github.com/cockroachdb/cockroach/blob/217fcf1f4b415dc142e2e01fc3529cb1e471be6f/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L206-L209

Looking at the code below this call (`singleRangeFeed` and `partialRangeFeed`) it seems like they default to passing errors up if they can't handle them internally. Isn't this a problem?
</blockquote></details>

No, that's correct; that's how it always worked -- and it is important to cancel entire mux rangefeed if one of those returns an error.  Updated comment here, and updated comment you left during connection -- it's a good point -- we need to propagate this error to the caller, but we shouldn't kill mux group if error happens; let the caller (single range feed) decide if the error retryable.


<!-- Sent from Reviewable.io -->

2023-02-02 15:35 UTC, tbg approved these changes
Nits only! Good to merge as far as I'm concerned (I didn't look at the non-rangefeed changes but saw some stuff show up in the diffs as I paged through, so maybe double check that nothing unintentional crept in).

> Reviewed 1 of 3 files at r1, 1 of 9 files at r12, 5 of 5 files at r16, 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-:-NNHkt6v-Q3tI16FJlFX:bdenlyp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @erikgrinaker, and @miretskiy)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 37 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNGWAsY-lM8Ns0gXyhA:-NNHg6-a9CSkDv2cJLkm:buijhcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/04401070acff881c953b39eca850ad4e01364d27/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L37)):*
> and it is important to cancel entire mux rangefeed if one of those returns an error. 

I wasn't sure why, so I took a look - I think when we get an error back from `partialRangeFeed` then the 'caller' already had a look at this error and has decided they can't retry the rangefeed. So now we do want to tear down the entire mux; because what's the alternative? You can keep the mux going but then this one rangefeed in it has failed and the caller decided to give up on it.

I guess my response to that would be, why does the caller give up on unspecified errors, killing the mux? Wouldn't it be better to indiscriminately retry the failing portion of the rangefeed? But looking at the retry loop in `partialRangeFeed`, it really is retrying pretty much indiscriminately already, since it retries through `SendError`s. So the things it would return are really unexpected errors, for example if there were any correctness checks in this code, it might return that up the stack.

So this is all fine.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 45 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNHg9Fy7d_Fv9bJxkXW:-NNHg9Fy7d_Fv9bJxkXX:bvqbx95) ([raw file](https://github.com/cockroachdb/cockroach/blob/af808320067af7b99c9c7f74bccaf091957ea183/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L45)):*
> ```Go
> 
> 	mu struct {
> 		// lock used to coordinate establishment and tear down of client connections.
> ```

nit: no need to change anything, but this kind of comment doesn't strike me as particularly useful. It's clear that the lock guards everything in the struct, i.e. the map.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 70 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNHgNpQDRFAjgFS7Mnu:-NNHgNpQDRFAjgFS7Mnv:b77h723) ([raw file](https://github.com/cockroachdb/cockroach/blob/af808320067af7b99c9c7f74bccaf091957ea183/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L70)):*
> ```Go
> 	cancel context.CancelFunc
> 
> 	initCtx terminationContext // Signaled when initialization completes.
> ```

nit: I keep editing this in my fixups, but I need to say it once since they keep coming back: inline comments don't capitalize and punctuate (Go style guide). So this should be `// signaled when initialization completes` and similar in all other inline comments.

Besides, the old comment told me more - what is "initialization"? It's exactly when the `client` field is ready to use. I found that valuable information. The world "initialization" doesn't mean anything here IMO.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 191 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNHhTTp6la26OxDZyj4:-NNHhTTp6la26OxDZyj5:bulehxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/af808320067af7b99c9c7f74bccaf091957ea183/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L191)):*
> ```Go
> 		})
> 	}
> 	m.mu.clients[nodeID] = ms
> ```

nit: move this line into the `if !found`.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 188 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNHk4Xr1AhwK27dJXN6:-NNHk4Xr1AhwK27dJXN7:b-kg058k) ([raw file](https://github.com/cockroachdb/cockroach/blob/35c27e23825f948e039264f966c3156f20c78e5e/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L188)):*
> ```Go
> 		// context available in the main context group used for this muxer.
> 		m.g.GoCtx(func(ctx context.Context) error {
> 			return m.startNodeMuxRangeFeedLocked(ctx, ms, client, nodeID)
> ```

rename back to remove the `Locked` suffix, which is no longer accurate.


<!-- Sent from Reviewable.io -->

2023-02-02 17:11 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96230)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @erikgrinaker, and @tbg)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 45 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNHg9Fy7d_Fv9bJxkXW:-NNI4rWj8RC-pCScR5B_:bdq5eku) ([raw file](https://github.com/cockroachdb/cockroach/blob/af808320067af7b99c9c7f74bccaf091957ea183/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L45)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: no need to change anything, but this kind of comment doesn't strike me as particularly useful. It's clear that the lock guards everything in the struct, i.e. the map.
</blockquote></details>

Ack; I think it was more useful when mu had more fields.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go` line 70 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/96230#-NNHgNpQDRFAjgFS7Mnu:-NNI5j9l5ipJtMAPC1dj:bw22657) ([raw file](https://github.com/cockroachdb/cockroach/blob/af808320067af7b99c9c7f74bccaf091957ea183/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L70)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: I keep editing this in my fixups, but I need to say it once since they keep coming back: inline comments don't capitalize and punctuate (Go style guide). So this should be `// signaled when initialization completes` and similar in all other inline comments.

Besides, the old comment told me more - what is "initialization"? It's exactly when the `client` field is ready to use. I found that valuable information. The world "initialization" doesn't mean anything here IMO.
</blockquote></details>

I long ago stopped fighting these style wars.  Changed.
I personally find that the desire to write complete sentences as a comment contradicts with lower case, but, I just don't care.


<!-- Sent from Reviewable.io -->

2023-02-02 20:48 UTC, tbg approved these changes
Squash and go 🥳

2023-02-02 20:49 UTC, tbg commented
```
    alter_changefeed_test.go:1238: condition failed to evaluate within 45s: waiting for checkpoint
    --- FAIL: TestAlterChangefeedAddTargetsDuringSchemaChangeError/kafka (48.80s)
```

This isn't new, https://github.com/cockroachdb/cockroach/issues/95687, but maybe you know more and this could be caused by this PR

2023-02-02 20:53 UTC, miretskiy commented
> ```
>     alter_changefeed_test.go:1238: condition failed to evaluate within 45s: waiting for checkpoint
>     --- FAIL: TestAlterChangefeedAddTargetsDuringSchemaChangeError/kafka (48.80s)
> ```
> 
> This isn't new, #95687, but maybe you know more and this could be caused by this PR

I'm still working on this; my 25k runs started flaking on me.. so trying to determine what's up with it.

2023-02-03 13:25 UTC, miretskiy commented
bors r+

2023-02-03 14:48 UTC, merged