230201.follower snapshot stats
cockroachdb/cockroach pull request #96350
Opened 2023-02-01 15:53 UTC by andrewbaptist

kv: Add stats for delegated snapshots

    Adds four new stats for delegated snapshots. These are not currently
    exposed through the admin UI, but will be useful for determining the
    effectiveness of using delegated snapshots in a multi-region setup.

    The stats are:
    range.snapshot.delegate.send-bytes - Number of bytes sent by a delegate.
    range.snapshot.delegate.successes - Successful delegation requests.
    range.snapshot.delegate.successes - Failed delegation requests.

    range.snapshot.send.latency - Histogram of timing to send a snapshot.

    The last one is useful regardless of snapshot delegation, but is useful
    in this context because it can be used to compare the latency with and
    without delegation.

    Release note (ops change): Adding additional stats described above.
    Epic: none

2023-02-01 15:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/96350)
<!-- Reviewable:end -->

2023-02-10 14:30 UTC, andrewbaptist commented
Some graphs of an actual run:
![latency](https://user-images.githubusercontent.com/46975918/218116854-15b586e7-607b-40e2-92e0-ffa727f653c6.png)
![success](https://user-images.githubusercontent.com/46975918/218116961-57ceadcf-b539-4bd2-9e6e-4f3b24b5ec64.png)
![bytes](https://user-images.githubusercontent.com/46975918/218116964-889bb2ce-96fc-445c-9b60-546969d7c4b4.png)

2023-02-16 00:34 UTC, AlexTalks requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96350)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvserver/metrics.go` line 780 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96350#-NOM8TDPCL0nuIpu3PxE:-NOM8TDPCL0nuIpu3PxF:b-af9pe1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c64752496162b25652becbce47baddb5957bf968/pkg/kv/kvserver/metrics.go#L780)):*
> ```Go
> 	}
> 
> 	metaRangeSnapshotSendLatency = metric.Metadata{
> ```

Discussed directly: this metric may not be very useful due to the disparate size of snapshots. It would be better to expose this via logs to the `KVDistribution` channel from the coordinator.


<!-- Sent from Reviewable.io -->

2023-02-21 19:33 UTC, andrewbaptist commented
I removed the stat as we discussed. I'm going to create a separate PR for adding logging, and a different one for changing the names of the settings (as we discussed).

2023-02-22 19:37 UTC, knz commented
Andrew don't forget to fix your github PR title and description.

2023-02-22 21:16 UTC, AlexTalks approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96350#-:-NOuyy6l2lyuatJJ_rI0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)



<!-- Sent from Reviewable.io -->

2023-02-22 21:21 UTC, andrewbaptist commented
bors r=AlexTalks

2023-02-23 15:25 UTC, andrewbaptist commented
bors r=AlexTalks

2023-02-23 15:54 UTC, merged