ui: databases shows partial results for size limit error
cockroachdb/cockroach pull request #96431
Opened 2023-02-02 15:19 UTC by j82w

The databases page displays partial results instead of just showing an error message.

The database details are now loaded on demand. Previously a network call was done for all databases which could result in 2k network calls. It now only loads the page of details the user is looking at. If the user does try to sort by column other than database name it will load database details for all the databases since it is necessary.

part of: #94333

Release note: none

2023-02-02 15:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/96431)
<!-- Reviewable:end -->

2023-02-02 22:33 UTC, matthewtodd requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/databasesApi.ts` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNJFNu_7NpetVOgHny3:-NNJFNu_7NpetVOgHny4:b23pb6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5158693b0a551e7b90cf8e6698beca1a9901a567/pkg/ui/workspaces/cluster-ui/src/api/databasesApi.ts#L60)):*
> ```XML
>     if (
>       result.error &&
>       !result.error.message.endsWith("max result size exceeded")
> ```

What would you think about switching these checks around so we don't have to depend on the text of the error message? Perhaps getting back both result rows and an error means that we've been size-limited?


<!-- Sent from Reviewable.io -->

2023-02-06 21:19 UTC, THardy98 reviewed
Could you update the `buildSQLApiDatabasesResponse` function used in `fakeApi.ts` for tests in `api.spec.ts`. Now that we're only getting the database name from `SHOW DATABASES` we don't need to mock the other columns (they aren't tested, but worth changing for accuracy).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-:-NNc_nKq23iaZKCMlmUD:b-wivfvg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @matthewtodd)



<!-- Sent from Reviewable.io -->

2023-02-07 15:50 UTC, THardy98 reviewed
Also, should we consider removing the ability to sort by other columns (at least temporarily) if we know they can break the page for large table sets?

Imo, the only columns worth sorting on would be size/range count and it's not a big loss if users aren't using them much anyways. Worth having some discussion on this imo. It'd be nice to really get some idea on whether these sorting options are used much, @kevin-v-ngo do we have any data on this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-:-NNgYJ2y6ojFM4WbfDfe:b-1otcq8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @matthewtodd)



<!-- Sent from Reviewable.io -->

2023-02-07 17:02 UTC, j82w commented
I'm fine with removing the sort capability if @kevin-v-ngo agrees. 





<!-- Sent from Reviewable.io -->

2023-02-07 21:34 UTC, j82w commented
*[`pkg/ui/workspaces/cluster-ui/src/api/databasesApi.ts` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNJFNu_7NpetVOgHny3:-NNhnOlT7qOukVz3ZF7d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5158693b0a551e7b90cf8e6698beca1a9901a567/pkg/ui/workspaces/cluster-ui/src/api/databasesApi.ts#L60)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

What would you think about switching these checks around so we don't have to depend on the text of the error message? Perhaps getting back both result rows and an error means that we've been size-limited?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-09 19:01 UTC, kevin-v-ngo commented
> Also, should we consider removing the ability to sort by other columns (at least temporarily) if we know they can break the page for large table sets?
> 
> Imo, the only columns worth sorting on would be size/range count and it's not a big loss if users aren't using them much anyways. Worth having some discussion on this imo. It'd be nice to really get some idea on whether these sorting options are used much, @kevin-v-ngo do we have any data on this?
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-:-NNgYJ2y6ojFM4WbfDfe:b-1otcq8)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @matthewtodd)

Can you clarify what you mean by _other_ columns? Are we removing sorting for all? 

If this page breaks, let's remove the capability. We should file a follow-up issue to track adding the behavior back in. Especially sorting by size.

2023-02-09 19:02 UTC, kevin-v-ngo commented
I'm assuming we already sort by default on size correct? FYI @dongniwang

2023-02-09 19:53 UTC, j82w commented
The default sort is by name. Sorting by name works because all the names are loaded in memory. It can handle about 2000 names depending on how big the names are before hitting the size limit. The table sorting will break for any column except the database name if there are more than like 50 dbs because it will get throttled. If you ask to sort by size then it requires doing 2k network calls to get the details of all dbs rather than just the details for the first page. It can probably handle more depending on the configuration. 





<!-- Sent from Reviewable.io -->

2023-02-09 21:32 UTC, matthewtodd reviewed
Code <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I wonder (in follow-on work) if it would be interesting / valuable to re-enable sorting below a certain number of databases, when we could do it efficiently enough. But I don't deeply understand if / how people use sorting today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-:-NNs4PJ77-V9o4pXfhUn:bfd2equ)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-02-09 21:34 UTC, matthewtodd approved these changes
Oops, published without approving! Also I think @THardy98 already said what I was thinking. :smile: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-:-NNs5B1zAoY7wDF2Aqn-:b-53wnh)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-02-09 21:39 UTC, dongniwang commented
I think the default is sort by name...but I'd imagine sort by size would be used by users on this page. Do we not have pagination for this page? What was the initial reasoning?

2023-02-10 16:49 UTC, THardy98 requested changes
Just left some small nits. Really like this change. Some follow up work to batch these requests would be great.

> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-:-NNwDh0r27ZrxyzfjQTX:b-ht19o7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w and @matthewtodd)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/databasesApi.ts` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNw8rFJ3XeVY1-fC1cr:-NNw8rFJ3XeVY1-fC1cs:b-py69o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/api/databasesApi.ts#L52)):*
> ```XML
>     timeout,
>   ).then(result => {
>     // If request succeeded but query failed, throw error (caught by saga/cacheDataReducer).
> ```

This isn't entirely accurate anymore, we only throw an error when the request succeeds with empty results and throws an error.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNw99Cp0j0EkUYbZYxq:-NNw99Cp0j0EkUYbZYxr:b-6ftk3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L303)):*
> ```XML
>     let filteredDbs = this.props.databases;
> 
>     console.log("refresh: " + JSON.stringify(this.props.sortSetting));
> ```

Do we want to log on refresh? We can probably remove this.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 307 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNw9QbICmxJry2forOm:-NNw9QbICmxJry2forOn:b-bsap1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L307)):*
> ```XML
>     // 40 dbs. If there is more than 40 dbs sort will be disabled.
>     if (this.props.databases.length > disableTableSortSize) {
>       let startIndex = 0;
> ```

We are reassigning this immediately below, we can initialize instead as:
```
let startIndex = this.state.pagination.pageSize * (this.state.pagination.current - 1);
```
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNw9nlmDX7Vec9yTsBU:-NNw9nlmDX7Vec9yTsBV:biiv5u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L315)):*
> ```XML
>       }
> 
>       if (!filteredDbs || filteredDbs.length === 0) {
> ```

Do we need the `!filteredDbs` check if we assign it to all databases by default?
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 335 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNwC4kM994SdbgZa2UN:-NNwC4kN2jVsdvTmCLXp:b2oypco) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L335)):*
> ```XML
>     }
> 
>     filteredDbs.forEach((database, i, arr) => {
> ```

We don't seem to be using the `i` or `arr` params, can just be `(database)`.
___
*[`pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx` line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNwCTpDBd0VZRua19lE:-NNwCTpE046eJBBD1_44:ba7ly1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx#L106)):*
> ```XML
>   loading?: boolean;
>   loadingLabel?: string;
>   disableSortForLargeData: number;
> ```

Maybe could use a better name, `disableSortForLargeData` sounds like a boolean value. `disableSortSizeLimit` or something similar might be more intuitive.
___
*[`pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx` line 231 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNwClDP8lpCxp3Uff4d:-NNwClDP8lpCxp3Uff4e:b-sn18db) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx#L231)):*
> ```XML
> 
>       if (
>         this.props.disableSortForLargeData &&
> ```

`disableSortForLargeData` isn't an optional parameter, are we checking for a non-zero value?
We're comparing `data.length` to it anyways in the conditional below so not sure if this check is necessary.
___
*[`pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx` line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNwD9HW9QaYXYVqEari:-NNwD9HW9QaYXYVqEarj:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx#L266)):*
> ```XML
>     ) => {
>       const sort =
>         !this.props.disableSortForLargeData ||
> ```

Ditto.


<!-- Sent from Reviewable.io -->

2023-02-10 18:21 UTC, j82w reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96431)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @matthewtodd and @THardy98)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/databasesApi.ts` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNw8rFJ3XeVY1-fC1cr:-NNwIpX26NWAELeGUzWR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/api/databasesApi.ts#L52)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

This isn't entirely accurate anymore, we only throw an error when the request succeeds with empty results and throws an error.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNw99Cp0j0EkUYbZYxq:-NNwIzoT-HKV1mOVQHSK:bdrkaqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L303)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Do we want to log on refresh? We can probably remove this.
</blockquote></details>

Good catch, I thought I removed all the console logs.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 307 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNw9QbICmxJry2forOm:-NNwJKbh4cJZKv0bG2sI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L307)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

We are reassigning this immediately below, we can initialize instead as:
```
let startIndex = this.state.pagination.pageSize * (this.state.pagination.current - 1);
```
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNw9nlmDX7Vec9yTsBU:-NNwJ_P6BSJ6Hn2-7X63:b-puhcnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L315)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Do we need the `!filteredDbs` check if we assign it to all databases by default?
</blockquote></details>

The issue is if a user searches for a name that does not exist it can return no results. Which can cause the sort and foreach to fail.
___
*[`pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx` line 335 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNwC4kM994SdbgZa2UN:-NNwKFKb2CqW1E6_abHX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx#L335)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

We don't seem to be using the `i` or `arr` params, can just be `(database)`.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx` line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNwCTpDBd0VZRua19lE:-NNwKWSN86QM2W9_XAdI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx#L106)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Maybe could use a better name, `disableSortForLargeData` sounds like a boolean value. `disableSortSizeLimit` or something similar might be more intuitive.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx` line 231 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNwClDP8lpCxp3Uff4d:-NNwOveC8ON-syIyg5pi:bp2ltr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx#L231)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

`disableSortForLargeData` isn't an optional parameter, are we checking for a non-zero value?
We're comparing `data.length` to it anyways in the conditional below so not sure if this check is necessary.
</blockquote></details>

I made the parameter optional. Even though it's not optional currently it doesn't fail to build for any of the other tables and the value is undefined for other tables.
___
*[`pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx` line 266 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNwD9HW9QaYXYVqEari:-NNwY5GY6WQzGAGZfO0l:boil6kq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5addb739703d6fd73741d6b225a254f141bf926c/pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.tsx#L266)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

It can be undefined so it needs the check. 


<!-- Sent from Reviewable.io -->

2023-02-10 18:23 UTC, THardy98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
Awesome improvements with this PR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-:-NNwZKTN5O8GAVOQMiDi:b-3c6dfa)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @matthewtodd)



<!-- Sent from Reviewable.io -->

2023-02-10 19:29 UTC, xinhaoz commented
*[`pkg/ui/workspaces/cluster-ui/src/sqlActivity/errorComponent.tsx` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNwnOObBl7qoFBzQVJw:-NNwnOObBl7qoFBzQVJx:buqd0bv) ([raw file](https://github.com/cockroachdb/cockroach/blob/35dcf8519a99ba68d4467cb6c862ddd305175fad/pkg/ui/workspaces/cluster-ui/src/sqlActivity/errorComponent.tsx#L24)):*
> ```XML
> 
> const LoadingError: React.FC<SQLActivityErrorProps> = props => {
>   if (props.error && props.error.name === "GetDatabaseInfoError") {
> ```

Why do we need to check specifically if it's `GetDatabaseInfoError`? Can we just print it if we get the prop?


<!-- Sent from Reviewable.io -->

2023-02-10 19:39 UTC, j82w commented
*[`pkg/ui/workspaces/cluster-ui/src/sqlActivity/errorComponent.tsx` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96431#-NNwnOObBl7qoFBzQVJw:-NNwoyCnDTg4HMv5ovi4:b-i2hl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/35dcf8519a99ba68d4467cb6c862ddd305175fad/pkg/ui/workspaces/cluster-ui/src/sqlActivity/errorComponent.tsx#L24)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Why do we need to check specifically if it's `GetDatabaseInfoError`? Can we just print it if we get the prop?
</blockquote></details>

GetDatabaseInfoError has the full error message already formatted for the user, and it shouldn't show a refresh option.  Other errors should show the existing error message and refresh button. 


<!-- Sent from Reviewable.io -->

2023-02-10 20:59 UTC, j82w commented
bors r+

2023-02-10 22:30 UTC, merged