ui: add execution insights to statement and transaction fingerprint details
cockroachdb/cockroach pull request #96440
Opened 2023-02-02 16:34 UTC by ericharmeling

This commit adds execution insights to the Statement Fingerprint and Transaction Fingerprint Details pages.

Part of #83780.

Loom: https://www.loom.com/share/98d2023b672e43fa8016829aa641a829

Release note (ui change): Added execution insights to the Statement Fingerprint Details and Transaction Fingerprint Details Pages.

2023-02-02 16:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/96440)
<!-- Reviewable:end -->

2023-02-02 21:51 UTC, gtr requested changes, later dismissed
Looking good :) Just some nits and a couple suggestions from me.

> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-:-NNJ62Iw4GgfIoXTPz9W:bz7x23v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/stmtInsightsApi.ts` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNIfgkp5NEj5PtszYtz:-NNIfgkq61Qu5Tk0jKbT:bi90fj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/api/stmtInsightsApi.ts#L129)):*
> ```XML
> 
>   return `
> SELECT ${stmtColumns} FROM 
> ```

nit: trailing space
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts` line 464 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNIjq2c4i4_nPmZFVhR:-NNIjq2c4i4_nPmZFVhS:bi90fj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts#L464)):*
> ```XML
>       *
>     FROM
>       ${TXN_INSIGHTS_TABLE_NAME} 
> ```

nit: trailing space
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts` line 517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNIzHz_-Kca6KG-t0XN:-NNIzHz_-Kca6KG-t0XO:bwqxcbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts#L517)):*
> ```XML
>   };
>   filters.execID = req?.txnExecutionID ? req.txnExecutionID : null;
>   filters.fingerprintID = req?.txnFingerprintID ? req.txnFingerprintID : null;
> ```

Nit suggestion but can we move these expressions inside the above block like so?
```
  const filters: TxnQueryFilters = {
    start: req?.start,
    end: req?.end,
    execID: req?.txnExecutionID ? req.txnExecutionID : null,
    fingerprintID: req?.txnFingerprintID ? req.txnFingerprintID : null,
  };

```



_Code quote:_
```XML
  filters.execID = req?.txnExecutionID ? req.txnExecutionID : null;
  filters.fingerprintID = req?.txnFingerprintID ? req.txnFingerprintID : null;
```
___
*[`pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNIoV3BCyC1aN6AmZFw:-NNIoV3BCyC1aN6AmZFx:bb8p98o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx#L83)):*
> ```XML
>         placement="bottom"
>         content={
>           "The latest execution of the statement fingerprint with an insight within the selected time period."
> ```

The Loom video shows an ID in this column - should this tooltip say `The latest execution ID...`? 

Also, I'm not entirely sure if the `...within the selected time period.` bit is necessary since I haven't seen any other tooltips specify this but perhaps others can chime in here.
___
*[`pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/index.ts` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNJ0JQw4AjyaviVJ04r:-NNJ0JQw4AjyaviVJ04s:bxqvv2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/index.ts#L1)):*
> ```XML
> // Copyright 2022 The Cockroach Authors.
> ```

nit: 2023
___
*[`pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.reducer.ts` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNJ0OA427xRPzlCvG9G:-NNJ0OA427xRPzlCvG9H:bxqvv2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.reducer.ts#L1)):*
> ```XML
> // Copyright 2022 The Cockroach Authors.
> ```

nit: 2023
___
*[`pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.sagas.ts` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNJ1Di3Dv2jQQS5Up1p:-NNJ1Di3Dv2jQQS5Up1q:bxqvv2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.sagas.ts#L1)):*
> ```XML
> // Copyright 2022 The Cockroach Authors.
> ```

nit: 2023
___
*[`pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.selectors.ts` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNJ1H0t4-2GMiFvc4Xb:-NNJ1H0t4-2GMiFvc4Xc:bxqvv2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.selectors.ts#L1)):*
> ```XML
> // Copyright 2022 The Cockroach Authors.
> ```

nit: 2023


<!-- Sent from Reviewable.io -->

2023-02-07 16:15 UTC, ericharmeling reviewed
TFTR! I think I got to all of your comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-:-NNgU1HVA5uLF5oUY5qf:b-hcfbe2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/stmtInsightsApi.ts` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNIfgkp5NEj5PtszYtz:-NNgPwg244KoaNv1FlDf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/api/stmtInsightsApi.ts#L129)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

nit: trailing space
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts` line 464 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNIjq2c4i4_nPmZFVhR:-NNgQ5IEBtfOAz5Pz-DF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts#L464)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

nit: trailing space
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts` line 517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNIzHz_-Kca6KG-t0XN:-NNgQK3mAb98kEg3ta1m:b-ac09at) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts#L517)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Nit suggestion but can we move these expressions inside the above block like so?
```
  const filters: TxnQueryFilters = {
    start: req?.start,
    end: req?.end,
    execID: req?.txnExecutionID ? req.txnExecutionID : null,
    fingerprintID: req?.txnFingerprintID ? req.txnFingerprintID : null,
  };

```
</blockquote></details>

Definitely! Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNIoV3BCyC1aN6AmZFw:-NNgTwys2OA6mWSAYKjC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx#L83)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

The Loom video shows an ID in this column - should this tooltip say `The latest execution ID...`? 

Also, I'm not entirely sure if the `...within the selected time period.` bit is necessary since I haven't seen any other tooltips specify this but perhaps others can chime in here.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/index.ts` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNJ0JQw4AjyaviVJ04r:-NNgTyYZ9N8KRx090eXt:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/index.ts#L1)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

nit: 2023
</blockquote></details>

Done
___
*[`pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.reducer.ts` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNJ0OA427xRPzlCvG9G:-NNgTzNN4tUROG47uDUo:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.reducer.ts#L1)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

nit: 2023
</blockquote></details>

Done
___
*[`pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.sagas.ts` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNJ1Di3Dv2jQQS5Up1p:-NNgU-5n5WHaL30Pnh36:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.sagas.ts#L1)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

nit: 2023
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.selectors.ts` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNJ1H0t4-2GMiFvc4Xb:-NNgU-uoAzgH0aSdx-hZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2cdbd6b2944c1a6c76f7db5daafd9e68a93db86/pkg/ui/workspaces/cluster-ui/src/store/insights/statementFingerprintInsights/statementFingerprintInsights.selectors.ts#L1)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

nit: 2023
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-07 16:55 UTC, maryliag requested changes
can you should the network tab? I want to confirm the cache is working and it's not spamming refresh calls

> Reviewed 24 of 37 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-:-NNgnO1Z6LhVBPmJZ2jX:b-1fr8r7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @gtr)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNgnEw2DxstZgZ7yKKA:-NNgnEw2DxstZgZ7yKKB:b47u12) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a4eae38f45b920a129f56f739b4d6336a7672eb/pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts#L83)):*
> ```XML
> export const LONG_TIMEOUT = "300s";
> export const LARGE_RESULT_SIZE = 50000; // 50 kib
> export const VERY_LARGE_RESULT_SIZE = 500000; // 500 kib
> ```

I don't see this used
___
*[`pkg/ui/workspaces/cluster-ui/src/selectors/insightsCommon.selectors.ts` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNgm2SF8o0_Gatl8YJS:-NNgm2SF8o0_Gatl8YJT:b-6was4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a4eae38f45b920a129f56f739b4d6336a7672eb/pkg/ui/workspaces/cluster-ui/src/selectors/insightsCommon.selectors.ts#L34)):*
> ```XML
> };
> 
> export const selectStatementInsightDetailsCombinerByFingerprint = (
> ```

did you mean `CombineD`?
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 666 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNgmNY-AuC0eDOSCsFo:-NNgmNY-AuC0eDOSCsFp:brhpbaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a4eae38f45b920a129f56f739b4d6336a7672eb/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L666)):*
> ```XML
>     const isCockroachCloud = useContext(CockroachCloudContext);
>     const insightsColumns = useMemo(
>       () => makeInsightsColumns(isCockroachCloud, false, false),
> ```

the second false should not be hard coded,  you should use `hasAdminRole` that already exists on this file
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx` line 453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNgmxpv7_m-Kmy9suY-:-NNgmxpwCyL-WQLgT90Y:btwff5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a4eae38f45b920a129f56f739b4d6336a7672eb/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L453)):*
> ```XML
>             );
> 
>             const insightsColumns = makeInsightsColumns(true, false, false);
> ```

don't hard code the values here. Get the real value for cockroach cloud and hasAdminRole


<!-- Sent from Reviewable.io -->

2023-02-07 20:10 UTC, ericharmeling reviewed
> can you should the network tab? I want to confirm the cache is working and it's not spamming refresh calls

Sure thing!

https://www.loom.com/share/89bab56b76a446fc9b2ca81775317e52

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-:-NNhToxZ7_i_pkGKchzx:b5ms7no)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/selectors/insightsCommon.selectors.ts` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNgm2SF8o0_Gatl8YJS:-NNh3TmxAK7TZ_cV56hy:bkmk2uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a4eae38f45b920a129f56f739b4d6336a7672eb/pkg/ui/workspaces/cluster-ui/src/selectors/insightsCommon.selectors.ts#L34)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

did you mean `CombineD`?
</blockquote></details>

I'm using the naming from the selector above this and below this (`selectStatementInsightDetailsCombiner` and `selectTxnInsightDetailsCombiner`).
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 666 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNgmNY-AuC0eDOSCsFo:-NNh4DsW43GVtKcR3mVA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a4eae38f45b920a129f56f739b4d6336a7672eb/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L666)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the second false should not be hard coded,  you should use `hasAdminRole` that already exists on this file
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx` line 453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNgmxpv7_m-Kmy9suY-:-NNh4_aS-EVHvx1_V6c5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a4eae38f45b920a129f56f739b4d6336a7672eb/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L453)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

don't hard code the values here. Get the real value for cockroach cloud and hasAdminRole
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNgnEw2DxstZgZ7yKKA:-NNh59V62TCiGyW50pdG:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a4eae38f45b920a129f56f739b4d6336a7672eb/pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts#L83)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I don't see this used
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2023-02-07 20:18 UTC, ericharmeling reviewed
FWIW, the changes in this PR do not work on CRDB versions without https://github.com/cockroachdb/cockroach/pull/96279/commits/06838a1492c4ee74013432fb97f89a7b09b45ab3

The SQL API call returns the following error:

`code: "42703", message: "executing stmt 1: run-query-via-api: column \"cpu_sql_nanos\" does not exist", severity: "ERROR", … `

But the page won't crash. There just won't be any insights on any fingerprint's details page.

There are also some cryptic jest failures that I need to investigate.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-:-NNhVAcl6BbPJaJfegmX:b-ylprm4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @maryliag)



<!-- Sent from Reviewable.io -->

2023-02-07 22:30 UTC, maryliag approved these changes
Nice!

Once you get tests passing (you might need a rebase): <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 37 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-:-NNhzObM50he91T7zS70:bw0uas9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gtr)



<!-- Sent from Reviewable.io -->

2023-02-07 22:50 UTC, xinhaoz commented on pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts
> +    fingerprintID: req?.txnFingerprintID ? req.txnFingerprintID : null,
nit: This can be simplified to `req?.txFingerprintID`. You don't need the ternary operator here, the `?` will make the value null

2023-02-07 22:50 UTC, xinhaoz commented on pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetails.tsx
> +      stmts != null && stmts?.length === txnDetails?.stmtExecutionIDs?.length;
nit: You don't need to add the `?` to the second part of the && here. If stmts is nullish the `stmts != null &&` will ensure the part after && doesn't get read.

2023-02-07 22:50 UTC, xinhaoz commented on pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/queriesCell.tsx
> +    (transactionQueries?.length === 1 &&
Ditto for the addition of `?` here. `!transactionQueries?.length` will ensure that the part after `||` means that transactionQueries has a non-zero length.

2023-02-07 22:50 UTC, xinhaoz commented on pkg/ui/workspaces/cluster-ui/src/selectors/insightsCommon.selectors.ts
> +  if (!statementInsights || statementInsights?.length < 1 || !fingerprintID) {
nit: can be condensed to (!statementInsights?.length || !fingerprintID)

2023-02-07 22:50 UTC, xinhaoz commented on pkg/ui/workspaces/cluster-ui/src/selectors/insightsCommon.selectors.ts
> +  statementInsights.forEach(insight => {
nit: Try replacing this with an aray.filter, and you can set the var above directly.

2023-02-07 22:50 UTC, xinhaoz commented on pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
> +                  {tableData != null && tableData?.length > 0 && (
nit: tableData?.length &&

2023-02-07 23:02 UTC, xinhaoz commented on pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
> +              const tableDataTypes: InsightType[] = [];
nit: if you're using this to track the insight types seen already, a `set` is prob preferred (although the array size will be small so it's probably not a big deal 🤷 )

2023-02-08 18:14 UTC, ericharmeling reviewed
TFTR @xinhaoz ! I think I got to all of your comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-:-NNmE2kQ8Jdr-C9lCUZe:biekcfp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gtr, @maryliag, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts` line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNHynopLukbrENgmijR-r3-516:-NNlShYT3gpINHlKJdcy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b75cd9fdaa69a8f73375bb6f6df50bc01d19b73/pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts#L516)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: This can be simplified to `req?.txFingerprintID`. You don't need the ternary operator here, the `?` will make the evaluated value null
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetails.tsx` line 78 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNHynopLukbrENgmijY-r3-78:-NNm8EHwAZpV8Bz3R6iI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b75cd9fdaa69a8f73375bb6f6df50bc01d19b73/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetails.tsx#L78)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: You don't need to add the `?` to the second part of the && here. If stmts is nullish the `stmts != null &&` will ensure the part after && doesn't get read.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/queriesCell.tsx` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNHynopLukbrENgmija-r3-25:-NNm8bKmC6HcM9SAmgWc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b75cd9fdaa69a8f73375bb6f6df50bc01d19b73/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/queriesCell.tsx#L25)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Ditto for the addition of `?` here. `!transactionQueries?.length` will ensure that the part after `||` means that transactionQueries has a non-zero length.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/selectors/insightsCommon.selectors.ts` line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNHynopLukbrENgmijf-r3-38:-NNm92SO39UYdsmYZxjg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b75cd9fdaa69a8f73375bb6f6df50bc01d19b73/pkg/ui/workspaces/cluster-ui/src/selectors/insightsCommon.selectors.ts#L38)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: can be condensed to (!statementInsights?.length || !fingerprintID)
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/selectors/insightsCommon.selectors.ts` line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNHynopLukbrENgmijf-r3-42:-NNm9Oe_7yfhFzXT-2L3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b75cd9fdaa69a8f73375bb6f6df50bc01d19b73/pkg/ui/workspaces/cluster-ui/src/selectors/insightsCommon.selectors.ts#L42)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: Try replacing this with an aray.filter, and you can set the var above directly.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx` line 467 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNHynopLukbrENgmijt-r3-467:-NNm9kiQ0c8dN84wqDZn:b-h7ekxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b75cd9fdaa69a8f73375bb6f6df50bc01d19b73/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L467)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: if you're using this to track the insight types seen already, a `set` is prob preferred (although the array size will be small so it's probably not a big deal 🤷 )
</blockquote></details>

Done (here and in `statementDetails`).
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx` line 561 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNHynopLukbrENgmijt-r3-561:-NNm9df_2BdCY7am2bMV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b75cd9fdaa69a8f73375bb6f6df50bc01d19b73/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L561)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: tableData?.length &&
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-09 15:41 UTC, ericharmeling reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96440)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gtr, @maryliag, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx` line 303 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNHynopLukbrENgmijd-r4-303:-NNqlx8T1Lam9qzBx4nH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7716ab4a9218f12f93e3be5607a9d420a0bb9258/pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx#L303)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: This might be a little clearer with a switch case statement
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 272 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNHynopLukbrENgmijj-r4-272:-NNqkLtR59-UEAaMtwdr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7716ab4a9218f12f93e3be5607a9d420a0bb9258/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L272)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: if this param is just from the props, why not just put it directly in the function instead as a param?
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 669 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96440#-NNHynopLukbrENgmijj-r4-669:-NNqmT8I-7htGYb1kwy2:boqp0oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7716ab4a9218f12f93e3be5607a9d420a0bb9258/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L669)):*
> I don't think it's recommended to use hooks inside non-functional components.

That makes sense. I just removed the hook for now. IDK how much we save memoizing the cockroachcloud context.

> also I don't think conditional calls to hooks are allowed (not sure what hte error behaviour will be though, did you get any console warnings?). I believe what you're doing here means these hooks will attach to the parent component (in this case StatementDetails), and since we render something different when we don't have data we'll be conditionally calling these hooks

I didn't get any console warnings  (from what I'm reading, it's just bad practice), but that's good to know for future reference :smile: !


<!-- Sent from Reviewable.io -->

2023-02-09 18:41 UTC, ericharmeling commented
Tests are passed and I've gotten to everyone's feedback. I'm going to go ahead and bors :grin:.

2023-02-09 18:42 UTC, ericharmeling commented
bors r+

2023-02-09 19:59 UTC, merged