kvflowhandle: implement kvflowcontrol.Handle
cockroachdb/cockroach pull request #96642
Opened 2023-02-06 14:18 UTC by irfansharif

Part of #95563.

Release note: None

2023-02-06 14:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/96642)
<!-- Reviewable:end -->

2023-02-14 02:37 UTC, sumeerbhola requested changes
still reading

> Reviewed 7 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-:-NOCm1_e14T6MY5VnPZa:bantulr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[`pkg/kv/kvserver/kvflowcontrol/doc.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOCdIIG81mzzO_tR5Jg:-NOCdIIH8db-kUqwktLS:b-xghga2) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/doc.go#L368)):*
> ```Go
> //       - Since we don't want to wait below raft, one way bound the lag between
> //         appended entries and applied ones is to only release flow tokens for
> //         an entry at position P once the applied state position >= P - delta.
> ```

I don't think we can link the return of tokens to state machine application without being very careful. If state machine application on one range is not happening because quorum has been lost due to some other node failure, we don't want that to exhaust tokens such that it causes interference on other unrelated ranges.

I think the simpler thing would be to not let state machine application get significantly behind due to local scheduling reasons. IIRC, we will be asynchronously doing the the raft log writes, since those require fsync, and not necessarily decoupling the async raft log writes and state machine application (which almost never fsyncs, so could be done by the same goroutine that is doing the async raft log writes). So we may be able to structurally avoid a "scheduling issue" that causes state machine application to lag behind raft log writes.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOCfqxw3cMjGPb2w-aI:-NOCfqxw3cMjGPb2w-aJ:b-v30tkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go#L61)):*
> ```Go
> 	// with the given priority, create-time, and over the given stream. This
> 	// blocks until there are flow tokens available or the stream disconnects,
> 	// subject to context cancellation.
> ```

If the stream disconnects, will Admit be successful?
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller.go` line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOCiZH00vWJzZPNtqMV:-NOCiZH00vWJzZPNtqMW:bqbss2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller.go#L390)):*
> ```Go
> // (signaled return true if ctx is canceled), and admit can increment the right
> // errored metric underneath. We'll have to plumb this to the (test) caller too
> // to prevent it from deducting tokens for canceled requests.
> ```

hmm, I overlooked this in the previous PR. This is similar to Admit and we don't exercise Admit in tests and instead exercise this. This seems wrong in that we are not quite testing the production code.
Can we share most of the code between the sync and async implementation?
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOCgktuCoeb507vaQdI:-NOCgktuCoeb507vaQdJ:bhitnrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go#L90)):*
> ```Go
> 	requestsBypassed = metric.Metadata{
> 		Name:        "kvadmission.flow_controller.%s_requests_bypassed",
> 		Help:        "Number of %s requests that bypassed the flow controller (due to disconnecting streams)",
> ```

disconnecting or disconnected? Things that were waiting and while waiting a stream was disconnected?
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOCkjBV2pnJcgwbzbXi:-NOCkjBV2pnJcgwbzbXj:bche8lw) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L122)):*
> ```Go
> 
> 		lowerBound := h.mu.perStreamLowerBound[c.Stream()]
> 		if !(lowerBound.Less(pos)) {
> ```

Why not let thing race and not do any deduction if the lower bound has already passed the pos?
It is often hard to maintain synchronization invariants across different components.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOClExA9sA058ctgCi5:-NOClExA9sA058ctgCi6:bx8a7qd) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L125)):*
> ```Go
> 			log.Fatalf(ctx, "observed regression in lower bound (%s <= %s)", pos, lowerBound)
> 		}
> 		h.mu.perStreamLowerBound[c.Stream()] = pos
> ```

I misunderstood the lower-bound. I thought it was maintained based on `ReturnTokensUpto`. But it is because `[]tracked` needs to be ordered by pos and we don't want to have to do work to keep it sorted.


<!-- Sent from Reviewable.io -->

2023-02-14 15:24 UTC, sumeerbhola requested changes
Haven't read the tests yet. Generally looks good.

> Reviewed 10 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-:-NOFWjfW9qlzsucknoBN:b-d0l9h6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[`pkg/kv/kvserver/kvflowcontrol/doc.go` line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOF-TOW910P2V5C1_sQ:-NOF-TOW910P2V5C1_sR:b-tli7gm) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/doc.go#L318)):*
> ```Go
> //      application, create lots of overlapping files/sublevels in L0.
> // - We want to pace the initial rate of log appends while factoring in the
> //   effect of the subsequent state machine application on L0 (modulo [^9]). We
> ```

I think we can do the same thing here as I mentioned in the other comment (not let state machine application get significantly behind the raft log writes). It simpler than having to factor in the effect of subsequent state machine application.
___
*[`pkg/kv/kvserver/kvflowcontrol/doc.go` line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOF0fl20XuBrK4Ywlzp:-NOF0fl20XuBrK4Ywlzq:b-kdhd0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/doc.go#L323)):*
> ```Go
> //   for it to be sufficiently caught before deducting/blocking for flow tokens.
> //   Until that point we can use flow tokens on sender nodes that wish to send
> //   MsgApps to the newly-restarted node. Similar to the steady state, flow
> ```

It seems like we have the following modes with flow tokens:
- Connected: Waiting on flow tokens at Admit time and deducting after proposal evaluation. This is the common case.
- Disconnected: Not waiting on flow tokens and not deducting after proposal evaluation.
- Catchup: Not waiting on flow tokens before proposal eval and not deducting after proposal eval. These proposals get queued below raft, and need waiting on and deducting tokens before sending to the store.

State transitions are connected => disconnected => catchup => connected/disconnected
Is that consistent with your mental model?

The state transitions in this roughly sketched approach are per range/Handle. This makes sense since we want the transition to disconnected to happen when pausing (among other things), which may be only for a subset of ranges sending to that store. And different ranges will finish catchup at different times. So we can have one range doing catchup competing with another range in connected state for the same tokens. This is ok-ish since we have isolation at the work class level. But there is a concern that if two ranges are seeing regular WorkClass and range R1 is connected and R2 transitions from disconnected => catchup that it can consume all the tokens causing a slowdown for user-facing work in R1. We can fix this by separating out a token category for regular work catchup: something like 16MB for regular, 8MB for elastic, 8MB for regular-catchup.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOFOD6K92yOaRvXncn6:-NOFOD6K92yOaRvXncn7:b7ohess) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L39)):*
> ```Go
> 		// (identified by their log positions) have been admitted below-raft,
> 		// streams disconnect, or the handle closed entirely.
> 		perStreamTokenTracker map[kvflowcontrol.Stream]*kvflowtokentracker.Tracker
> ```

Can you consolidate these two maps into a single one.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOFPOOY2I_kkEIMMryA:-NOFPOOY2I_kkEIMMryB:b3vco38) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L42)):*
> ```Go
> 		// perStreamLowerBound tracks on a per-stream basis the log position
> 		// below which we're not allowed to deduct tokens. It's used only for
> 		// assertions
> ```

We should document in the interface the requirement that `DeductTokensFor` requires that the `RaftLogPositions` be monotonically increasing.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOFQ_bN4PVTSSscwRPN:-NOFQ_bN4PVTSSscwRPO:btiloh) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L72)):*
> ```Go
> 		// introducing cluster settings that disable flow control entirely or
> 		// for regular traffic. We risk returning tokens that we never deducted
> 		// otherwise.
> ```

It seems ok to return tokens for accounting purposes, since ReturnTokensUpto would return only what has been actually deducted.
Could the disable case be handled at a higher level by not calling Admit?
We also need to handle the transitions from enabled => disabled and vice versa, which may be simpler by always having a `Handle` and sometimes not using it.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOFST9A9oQVyD9_Cyln:-NOFST9A9oQVyD9_Cylo:bq61sqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L123)):*
> ```Go
> 		lowerBound := h.mu.perStreamLowerBound[c.Stream()]
> 		if !(lowerBound.Less(pos)) {
> 			log.Fatalf(ctx, "observed regression in lower bound (%s <= %s)", pos, lowerBound)
> ```

How about checking the lower bound before calling Track? This would allow for some defensive code where we log an error if this invariant is violated and if not violated we would call Track. I slightly worry that with various failure modes and state transitions involving disconnected/catchup/disconnected that we may end up with a small race and it is better not to crash the node.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOFTQuU0HARp7s3QB1k:-NOFTQuU0HARp7s3QB1l:b-hf0dos) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L154)):*
> ```Go
> 		// acquired (whichever comes after). This is used to assert against
> 		// regressions in token deductions (i.e. deducting tokens for indexes
> 		// lower than the current term/lease).
> ```

We may want to weaken this assertion to a error log too.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOFTkne8QKQb2PVGmk4:-NOFTkne8QKQb2PVGmk5:bnpucsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L165)):*
> ```Go
> 
> 	h.mu.perStreamTokenTracker[stream].Untrack(ctx, pri, pos,
> 		func(tokens kvflowcontrol.Tokens, _ kvflowcontrolpb.RaftLogPosition) {
> ```

why bother with this `RaftLogPosition` param?
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOFTu41DGu_vmnttcQj:-NOFTu41DGu_vmnttcQk:buwlqw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L170)):*
> ```Go
> 	)
> 
> 	lowerBound := h.mu.perStreamLowerBound[stream]
> ```

Should this `lowerBound` be moved into the `Tracker` since that's the one trying to maintain a sorted slice.
__ [...]

2023-02-16 11:15 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96642)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/doc.go` line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOF-TOW910P2V5C1_sQ:-NOOsRHD-KPJXMO6xZuU:b-x9yfqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/doc.go#L318)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we can do the same thing here as I mentioned in the other comment (not let state machine application get significantly behind the raft log writes). It simpler than having to factor in the effect of subsequent state machine application.
</blockquote></details>

Ack. But BTW, this problem (= large deferred state machine application) might still exist even if at the individual replica level we made it so that state machine application never got significantly behind the raft log writes. Consider the pathological case described in the text below:

```
//       - For what it's worth, this "deferred application with high read-amp"
//         was also a problem before async raft storage writes. Consider many
//         replicas on an LSM, all of which appended a few large raft log entries
//         without applying, and at apply time across all those replicas, we end
//         up inverting the LSM.
```
___
*[`pkg/kv/kvserver/kvflowcontrol/doc.go` line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOF0fl20XuBrK4Ywlzp:-NOOlXMUEWyG5UDG_YGB:b-adzbk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/doc.go#L323)):*
> State transitions are connected => disconnected => catchup => connected/disconnected. Is that consistent with your mental model?

Yes.

> We can fix this by separating out a token category for regular work catchup: something like 16MB for regular, 8MB for elastic, 8MB for regular-catchup.

Yes, I was thinking we'd do this this -- a separate category of tokens for performance isolation. BTW, I wasn't thinking we'd use the Handle for this catchup work, but perhaps something very similar that's also layered above the kvflowcontrol.Controller dealing with these "catchup tokens". But now that you mention it, maybe using the Handle here makes sense -- for any range we would never be using catchup tokens and also {regular,elastic} tokens. Maybe that means we could also just use elastic tokens for catchup work.
___
*[`pkg/kv/kvserver/kvflowcontrol/doc.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOCdIIG81mzzO_tR5Jg:-NOOofOB0TN0WM4cv5Hu:bdrqdfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/doc.go#L368)):*
> If state machine application on one range is not happening because quorum has been lost due to some other node failure, we don't want that to exhaust tokens such that it causes interference on other unrelated ranges.

Good point. Added.

>  IIRC, we will be asynchronously doing the the raft log writes, since those require fsync, and not necessarily decoupling the async raft log writes and state machine application (which almost never fsyncs, so could be done by the same goroutine that is doing the async raft log writes). 

I was anticipating https://github.com/cockroachdb/cockroach/issues/94854 and https://github.com/cockroachdb/cockroach/issues/94853, which I've now linked to in the text. This comment thread is also now visible on those issues. I agree this would be simpler. Perhaps we can revisit I11 and [^9] once we try to decouple log appends and state machine applications.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOCfqxw3cMjGPb2w-aI:-NONhb4s-OC0cM-ESXZp:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go#L61)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If the stream disconnects, will Admit be successful?
</blockquote></details>

Yes.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller.go` line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOCiZH00vWJzZPNtqMV:-NONsAUT4O368l3x70yv:bhd4eer) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller.go#L390)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

hmm, I overlooked this in the previous PR. This is similar to Admit and we don't exercise Admit in tests and instead exercise this. This seems wrong in that we are not quite testing the production code.
Can we share most of the code between the sync and async implementation?
</blockquote></details>

I tried sharing code between the sync and async implementations but it got awkward. So what I did instead was add tests for the production `Handle.Admit()` implementation in `TestHandleAdmit`. It ends up testing the production implementation of `Controller.Admit()` as well.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOCgktuCoeb507vaQdI:-NONhzG-0KOXLpp4MT7y:b-y3zzwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go#L90)):*
Disconnecting. These requests were waiting and while waiting a stream was disconnected. If you look at `(h *Handle) DisconnectStream` we get rid of the connection from `Handle.mu.connections` to subsequent calls to Handle.Admit() don't try to `Controller.Admit` using the now-disconnected stream. Reworded the help text to be clearer:

> Number of {regular,elastic} waiting requests that bypassed the flow controller due to disconnecting streams.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOFOD6K92yOaRvXncn6:-NOODAysAEFd99FTO2_5:b38mjxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L39)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you consolidate these two maps into a single one.
</blockquote></details>

Done (by moving the per-stream lower-bound tracking into the tracker itself).
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOFPOOY2I_kkEIMMryA:-NONjdK96AG1Ey9iP1zR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L42)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We should document in the interface the requirement that `DeductTokensFor` requires that the `RaftLogPositions` be monotonically increasing.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOFQ_bN4PVTSSscwRPN:-NOOhRE53R5fOQcbZ2wS:bw59zpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle.go#L72)):*
> since ReturnTokensUpto would return only what has been actually deducted.

Ah, good point.

> Could the disable case be handled at a higher level by not calling Admit? We also need to handle the transitions from enabled => disabled and vice versa, which may be simpler by [...]

2023-02-17 18:02 UTC, sumeerbhola requested changes
Looks good. I just need to read through some of the handle_ files

> Reviewed 1 of 26 files at r1, 13 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-:-NOVXX-d-hccZUm-QFfL:b-y6cw97)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[`-- commits` line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOV7Os4ETu7_nq8XGnI):*
nice simulations!
___
*[`pkg/kv/kvserver/kvflowcontrol/doc.go` line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOF0fl20XuBrK4Ywlzp:-NOV7z2cEbZnWRHMKrTj:b-q3j2vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/doc.go#L323)):*
Yes, I think we should use the Handle for this too.

> Maybe that means we could also just use elastic tokens for catchup work.

That's a good point. Catchup is elastic. And if there is enough regular work that there are no tokens for elastic, then catchup should be deprioritized. The only concern I can think of is that if R2 is doing catchup and has regular work, and R3 is doing an index backfill, then R2 is more important.
___
*[`pkg/kv/kvserver/kvflowcontrol/doc.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOCdIIG81mzzO_tR5Jg:-NOVTG5Z2yUPiCtGCC2E:b-rt1i8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/93aa05884902eedb42d99210ae1648c5987baa03/pkg/kv/kvserver/kvflowcontrol/doc.go#L368)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

> If state machine application on one range is not happening because quorum has been lost due to some other node failure, we don't want that to exhaust tokens such that it causes interference on other unrelated ranges.

Good point. Added.

>  IIRC, we will be asynchronously doing the the raft log writes, since those require fsync, and not necessarily decoupling the async raft log writes and state machine application (which almost never fsyncs, so could be done by the same goroutine that is doing the async raft log writes). 

I was anticipating https://github.com/cockroachdb/cockroach/issues/94854 and https://github.com/cockroachdb/cockroach/issues/94853, which I've now linked to in the text. This comment thread is also now visible on those issues. I agree this would be simpler. Perhaps we can revisit I11 and [^9] once we try to decouple log appends and state machine applications.
</blockquote></details>

Ack. I added a comment to one of those issues.


<!-- Sent from Reviewable.io -->

2023-02-17 21:40 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 26 files at r1, 2 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-:-NOWJTLJEYeCbLw1uI6g:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_overview` line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOWE2BT0NSdFNoFZji9:-NOWE2BT0NSdFNoFZjiA:bdr4exa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1876d8bc8c6acf4a9794aac7a8cf76429a23394d/pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_overview#L134)):*
> ```
> 
> 
>  4.0 ┤              ╭╮       ╭───────╮
> ```

nit: how much smoothing is happening in this rate calculation? It does look at bit odd that we don't show 4MB/s throughout that interval. Worth a comment at least.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_shared_stream` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOWFy8Q0HoJDGloNrDH:-NOWFy8Q0HoJDGloNrDI:b17owlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1876d8bc8c6acf4a9794aac7a8cf76429a23394d/pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_shared_stream#L1)):*
> ```
> # Demonstrate the behavior when a single stream is share across two handles h1
> ```

nit: shared
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_single_slow_stream` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOWHD8VCzKfxYUX36x7:-NOWHD8VCzKfxYUX36x8:bpv68wk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1876d8bc8c6acf4a9794aac7a8cf76429a23394d/pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_single_slow_stream#L37)):*
> ```
> #   blocked/unblocked as tokens are deducted/returned. The demand for tokens
> #   (1MiB/s) is higher than the replenishment rate (0.5MiB/s).
> # - The overall admission rate is reduced from 30 reqs/s to 25 reqs/s,
> ```

why 30 req/s and not 10 req/s. Is this just because the metric is counting the same request 3 times because of the 3 stores?
And why is the reduction then to 25 req/s instead of 15 req/s. The plot below also shows 25.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_stream_disconnection` line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOWIbRT8EyiQc7KKH4k:-NOWIbRT8EyiQc7KKH4l:b-2kqe4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1876d8bc8c6acf4a9794aac7a8cf76429a23394d/pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_stream_disconnection#L30)):*
> ```
> # (s3, at 0.5MiB/s). We see the blocked stream count bouncing between 0 and 1
> # as tokens get depleted and replenished (demand here is higher than the
> # replenishment rate).
> ```

It would be good to see the admission rate until s3 gets exhausted, which then causes the rate to drop to s3's replenishment rate, and then after s3 disconnects see the admission rate climb back.


<!-- Sent from Reviewable.io -->

2023-02-17 23:32 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96642)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_overview` line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOWE2BT0NSdFNoFZji9:-NOWNR7OB33iAZtsfKLv:b-7vn8g8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1876d8bc8c6acf4a9794aac7a8cf76429a23394d/pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_overview#L134)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: how much smoothing is happening in this rate calculation? It does look at bit odd that we don't show 4MB/s throughout that interval. Worth a comment at least.
</blockquote></details>

Done (added a comment + extended timescales to show 4MiB/s for a while longer).
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_single_slow_stream` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOWHD8VCzKfxYUX36x7:-NOWNkXz3xlHKCK_uGg6:b-k6fo90) ([raw file](https://github.com/cockroachdb/cockroach/blob/1876d8bc8c6acf4a9794aac7a8cf76429a23394d/pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_single_slow_stream#L37)):*
>  Is this just because the metric is counting the same request 3 times because of the 3 stores?

Yes.

> And why is the reduction then to 25 req/s instead of 15 req/s. The plot below also shows 25.

It's because that graph was plotting metrics from the controller's POV. When a handle wants to admit work along 3 streams s1-s3, where s3 is the bottleneck, when iterating through s1-s3, if it's able to admit on s1 and s2 before being blocked on s3, those metrics are incremented. But this is a bit onerous to explain and easy to misread since work is not actually getting admitted "at the handle level", so I added a few metrics to add visibility into admission rates and wait durations from the handle's perspective, across all connected streams. Now it looks like:

```
# Set up a triply connected handle (to s1, s2, s3) and start issuing writes at
# 1MiB/s. For two of the streams, return tokens at exactly the rate its being
# deducted (1MiB/s). For the third stream (s3), we return flow tokens at only
# 0.5MiB/s.
timeline
t=0s         handle=h op=connect    stream=t1/s1   log-position=1/0
t=0s         handle=h op=connect    stream=t1/s2   log-position=1/0
t=0s         handle=h op=connect    stream=t1/s3   log-position=1/0
t=[0s,50s)   handle=h class=regular adjust=-1MiB/s   rate=10/s
t=[0.2s,50s) handle=h class=regular adjust=+1MiB/s   rate=10/s stream=t1/s1
t=[0.2s,50s) handle=h class=regular adjust=+1MiB/s   rate=10/s stream=t1/s2
t=[0.2s,50s) handle=h class=regular adjust=+0.5MiB/s rate=10/s stream=t1/s3
----

# The overall admission rate through the handle is reduced from 10 reqs/s
# (corresponding to 1MiB/s) to 5 reqs/s (corresponding to 0.5MiB/s), the
# difference now found in the +5 reqs/s accumulating in the wait queue.
plot
kvadmission.flow_handle.regular_requests_{admitted,waiting}    unit=reqs/s rate=true
----
 10.0 ┤╭───────────────────────╮
  9.3 ┤│                       │
  8.7 ┤│                       │
  8.0 ┤│                       ╰╮
  7.3 ┤│                        │
  6.7 ┤│                        │
  6.0 ┤│                        │
  5.3 ┤│                        ╭─────────────
  4.7 ┤│                        │
  4.0 ┤│                        │
  3.3 ┤│                        │
  2.7 ┤│                        │
  2.0 ┤│                       ╭╯
  1.3 ┤│                       │
  0.7 ┤│                       │
  0.0 ┼────────────────────────╯
       rate(flow_handle.regular_requests_{admitted,waiting}) (reqs/s)
````
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_stream_disconnection` line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-NOWIbRT8EyiQc7KKH4k:-NOWd50I3kxSiXg_g8Xb:b-fgzuhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1876d8bc8c6acf4a9794aac7a8cf76429a23394d/pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_stream_disconnection#L30)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It would be good to see the admission rate until s3 gets exhausted, which then causes the rate to drop to s3's replenishment rate, and then after s3 disconnects see the admission rate climb back.
</blockquote></details>

Done. It looks like the following, with 4 phases:
- slowest stream tokens available, high admission rate
- slowest stream tokens depleted, admission rate shaped to slow stream
- slowest stream disconnects, earlier requests waiting for admission are admitted in a burst
- high admission rate (again) now that the slow stream is not considered

```

  25.0 ┤                     ╭─╮
  22.3 ┤                    ╭╯ │
  19.7 ┤                    │  │
  17.0 ┤                   ╭╯  │
  14.3 ┤                   │   │
  11.7 ┼───────╮           │   ╰───────────────
   9.0 ┤       ╰─╮         │
   6.3 ┤         ╰╭────────╮
   3.7 ┤        ╭─╯        │
   1.0 ┼────────╯          │   ╭───────────────
  -1.7 ┤                   │   │
  -4.3 ┤                   │   │
  -7.0 ┤                   ╰╮  │
  -9.7 ┤                    │  │
 -12.3 ┤                    ╰─╮│
 -15.0 ┤                      ╰╯
        rate(flow_handle.regular_requests_{admitted,waiting}) (reqs/s)
```


<!-- Sent from Reviewable.io -->

2023-02-17 23:34 UTC, irfansharif reviewed
TFTR! 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96642#-:-NOWiLFI30EyxABvjqm6:b-4iczgp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-02-18 00:50 UTC, merged