bulk,backupccl: log ExportRequest trace on failure
cockroachdb/cockroach pull request #96905
Opened 2023-02-09 21:25 UTC by adityamaru

This change adds logic to fetch the trace for each ExportRequest once it has returned a response or failed with an error. If the request failed with an error, we unconditionally log the trace, otherwise we log it when the appropriate vmodule is set.

This change also fixes a bug where the child context created by the tracing aggregator would not inherit its parent's RecordingMode. Today there is no mechanism to toggle a job's RecordingMode from Structured to Verbose, but when we do add the ability to do so we expect all operations in the job to collect information in accordance with that mode.

Fixes: #86047

Release note: None

2023-02-09 21:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/96905)
<!-- Reviewable:end -->

2023-02-10 14:53 UTC, msbutler reviewed
thanks for doing this! backport to 22.2/.1? Also, did you get a chance to test it out?

2023-02-10 14:54 UTC, msbutler approved these changes

2023-02-10 14:55 UTC, msbutler requested changes

2023-02-10 14:55 UTC, msbutler commented on pkg/ccl/backupccl/backup_processor.go
> +					exportReqTrace := fetchExportRequestTrace(ctx)
oh wait, don't we only want to fetch the trace on failure, or with a higher vmodule? this would fetch every time, by default.

2023-03-17 18:14 UTC, shermanCRL commented
Do we have next steps on this?

2023-03-28 21:29 UTC, adityamaru commented
We have a better solution in https://github.com/cockroachdb/cockroach/pull/97895 that supersedes this.

2023-03-28 21:29 UTC, closed without merging