kv, util: add mvcc stats to telemetry logging channel
cockroachdb/cockroach pull request #97413
Opened 2023-02-21 21:00 UTC by Santamaura

This change add a replicas field to the store stats payload for the telemetry logging channel. The replica stats that are logged are: contains_estimates, last_updated_nanos, intent_age, gc_bytes_age, live_bytes, live_count, key_bytes, key_count, value_bytes, value_count, intent_count, separated_intent_count, range_key_count, range_key_bytes, range_val_count, range_val_bytes, sys_bytes, sys_count, abort_span_bytes.

Fixes: #85411

Release note: None

2023-02-21 21:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/97413)
<!-- Reviewable:end -->

2023-02-28 21:25 UTC, knz requested changes
wowzer, how does this behave when there are, say, 20000 replicas in a store? Do they fit within our maximum event size limit?

2023-03-01 14:41 UTC, Santamaura reviewed
Unsure but I agree with the sentiment that it's too much to log at once. Perhaps we could log the first n replicas that meet some criteria related to the stats? I'm open to suggestions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97413#-:-NPSb_PO76y33TkQwriY:b-a71jka)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @zachlite)



<!-- Sent from Reviewable.io -->

2023-03-01 17:40 UTC, knz commented
Can you get in touch with members of the kv team to brainstorm solutions?

2023-03-01 18:04 UTC, andreimatei commented
Do we need per-range info, or can we sum up everything in the store?

Btw, did you consider whether collecting the same info from every replica of a range versus only from one distinguished replica (e.g. the leaseholder, or the first replica if there's no lease) is a good idea?

2023-03-01 21:32 UTC, Santamaura commented
Having a discussion with product to better understand what is being requested

2023-03-08 15:03 UTC, closed without merging