allocator: [wip] check store health on lease transfer
cockroachdb/cockroach pull request #97587
Opened 2023-02-23 19:41 UTC by kvoli

Previously, the allocator would transfer leases without considering candidate's IO overload. When leases would transfer to the IO overloaded stores, service latencies tended to degrade.

This commit adds health checks prior to lease transfers. The health checks are similar to the IO overload checks for allocating replicas in #97142.

The checks work by comparing a candidate store against `kv.allocator.io_overload_threshold` and the mean of other candidates. If the candidate store exceeds both these values, it is considered IO overloaded.

The current leaseholder has to meet a higher bar to be considered IO overloaded. It must have an IO overload score greater than `kv.allocator.io_overload_threshold` +
`kv.allocator.io_overload_threshold_enforcement_leases`.

The level of enforcement for IO overload is controlled by `kv.allocator.io_overload_threshold_enforcement_leases` controls the action taken when a candidate store for a lease transfer is IO overloaded.

- `block_none`: don't exclude stores.
- `block_none_log`: don't exclude stores, log an event.
- `block`: exclude stores from being considered as leaseholder targets for a range if they exceed The current leaseholder store will NOT be excluded as a candidate for its current range leases.
- `shed`: same behavior as block, however the current leaseholder store WILL BE excluded as a candidate for its current range leases i.e. The lease will always transfer to a healthy and valid store if one exists.

The default is `block` and a buffer value of `0.2`.

Release note: None

2023-02-23 19:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/97587)
<!-- Reviewable:end -->

2023-02-24 16:10 UTC, irfansharif submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97587)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP31rUhCneU5Peqnd7R):*
[mega nit] Avoid the "health" verbiage as best you can. Lets make this more precise, "store health" is both vague and ambiguous; we're just checking the store's IO overload score. 
___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP322uI2Vo_4090y6DZ):*
"IO overload" -> "IO overload score"
___
*[`-- commits` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP33Lyc6I0JX4idbssL):*
Could you explain why the lease transfer threshold has a higher bar? Shouldn't it have a lower bar given lease transfers are cheaper, and we ought to try and stop those first before considering the more heavy weight replica transfers?
___
*[`-- commits` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP32nNx8CgfjNWd4yZX):*
This combination of two cluster settings seems complex -- every time we debug this we'd always have to go look at two things and sum them up. It also raises questions like "Can the delta be -ve?", and knowing the value of just one of the settings is not helpful. Why not just have one specifically for leases? 
___
*[`-- commits` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP33Ne65E_oAbGLIJqL):*
This help text feels like it's assuming familiarity with allocator internals with its reference to "candidates" or things we're "excluding". I find it hard to use. Lets instead say something like the following (note the change in cluster setting name and enums):

```
We can control the lease transfer behaviour in the presence of IO overloaded stores using kv.allocator.io_overload_threshold_lease_enforcement:
- ignore: ignore IO overload scores entirely during lease transfers (effectively disabling this mechanism);
- future_lease_transfers: for future lease transfers only consider stores that aren't IO overloaded (existing leases on IO overloaded stores are left as is);
- shed_current_leases: actively shed leases from IO overloaded stores to less IO overloaded stores (this is a super-set of future_lease_transfers).
```
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2035 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP36t83E7wYjmF8-kJ7:-NP36t83E7wYjmF8-kJ8:b-9ojqw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2035)):*
> ```Go
> }
> 
> // healthyLeaseTargets returns a list of healthy replica targets and whether
> ```

[same mega nit] Please avoid this "health" moniker. We've overused this term in the allocator code, consider this code comment for example:

```
	// StoreFilterSuspect requests that the returned store list additionally
	// exclude stores that have been suspected as unhealthy. We dont want unhealthy
	// stores to be considered for rebalancing or for lease transfers. i.e. we dont
	// actively shift leases or replicas away from them, but we dont allow them to
	// get any new ones until they get better.
```

But this has nothing to do with IO overload scores -- it's got to do with liveness heartbeat blips due to intermittent connectivity or write stalls.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP3158N0GPKedDOpLMj:-NP3158N0GPKedDOpLMk:bek4ic3) ([raw file](https://github.com/cockroachdb/cockroach/blob/13550056ce334ae40ed20a7b805514e7677f5c6e/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L77)):*
> ```Go
> 	// IO overload score greater than what's set. This is typically used in
> 	// conjunction with IOOverloadMeanThreshold below.
> 	DefaultIOOverloadThreshold = 0.5
> ```

This feels like a random change, what were the motivating experiments? If you're seeing IO overload score thrashing between (0.4,1.x) and we're not reactive enough at 0.8, consider exponential smoothing instead of just lowering the threshold hoping for more sensitivity to a fluctuating signal.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP3-ZnS26eyWbRGimfr:-NP3-ZnS26eyWbRGimfs:b-auq8ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L183)):*
> ```Go
> 	// considered as leaseholder targets for a range, regardless of the store IO
> 	// overload.
> 	LeaseIOOverloadThresholdNoAction LeaseIOOverloadEnforcementLevel = iota
> ```

Lets re-use the same types as above; these are symmetric module the "BlockAll" vs. "Shed" naming but that seems superfluous. We can keep the separate cluster setting to control lease enforcement. 

Also [nit] the log only action (here and above) feels pointless -- who's actually looking at these logs? Unless you increment a metric counter which we can scan for in a CC-like environment, this is effectively dead code. Lets get rid of it, keep a metric and log under non-zero verbosity for the "NoAction" variants. These cluster settings feels overly hedgy otherwise. 
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 2317 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP38P660Zxbr9ZJloZZ:-NP38P660Zxbr9ZJloZ_:b-1bzgd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L2317)):*
> ```Go
> }
> 
> func (o StoreHealthOptions) transferToStoreIsHealthy(
> ```

[same mega nit] Avoid the "healthy" verbiage. Also, this method and leaseStoreIsHealthy are identical and could be made into one by passing in a `leaseholder bool` parameter, right? Which we can at the callsite?
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 2342 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP3AJGS4wJB5orqGFKV:-NP3AJGS4wJB5orqGFKW:b-tjajrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L2342)):*
> ```Go
> 
> 	// The store is only considered unhealthy when the enforcement level is
> 	// LeaseIOOverloadThresholdNoAction.
> ```

The comment does not match the code.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 2346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP38XuL3UNzCkodYEpb:-NP38XuL3UNzCkodYEpc:b-2yyzcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L2346)):*
> ```Go
> }
> 
> func (o StoreHealthOptions) leaseStoreIsHealthy(
> ```

[same mega nit] Avoid the "healthy" verbiage.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go` line 1979 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP38Yr49yk2igyn2Xo7:-NP38Yr49yk2igyn2Xo8:b-2yyzcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go#L1979)):*
> ```Go
> }
> 
> func TestAllocatorTransferLeaseTargetHealthCheck(t *testing.T) {
> ```

[same mega nit] Avoid the "healthy" verbiage.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go` line 2033 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP39g9W0HG9NHniP9VK:-NP39g9W0HG9NHniP9VL:bibjlz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go#L2033)):*
>  [...]

2023-02-24 21:17 UTC, andrewbaptist requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97587)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @kvoli)

___
*[`-- commits` line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP45Lca0diGu3k33j2Y):*
We should add a release note as it changes the behavior when leases are transferred. There are a lot of comments on the PR text already, so I'll review again once you update.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2044 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP469JC6EuY5Djp1MGV:-NP469JC6EuY5Djp1MGW:b-dnlo5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2044)):*
> ```Go
> 	leaseStoreID roachpb.StoreID,
> 	storeHealthOpts StoreHealthOptions,
> ) (healthyTargets []roachpb.ReplicaDescriptor, excludeLeaseRepl bool) {
> ```

I think this is a little wrong. If the current store is unhealthy, then we shouldn't exclude any other stores due to health reasons unless they are worse than us. Otherwise if for instance, all the stores in the system are at 0.6, no lease transfers will happen even if the current leaseholder gets severely overloaded. 
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP48BQvCmXZYqbFt9MC:-NP48BQvCmXZYqbFt9MD:br80h17) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2198)):*
> ```Go
> 
> 	var excludeLeaseReplForHealth bool
> 	existing = a.ValidLeaseTargets(ctx, storePool, conf, existing, leaseRepl, opts)
> ```

Use a different variable name for existing after each check and in the log message below, print out more details about why we ended up with no valid lease targets. Tracking this down is hard even if you have the code, and even harder if you are just looking at the log. It would be nice to see that some stores were rejected because of their overload. Also I'm concerned that if all stores in the system are overloaded, then no lease transfers will happen. I'm not sure what should happen in this case, but it seems we should still correctly handle lease preference movement.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP3-ZnS26eyWbRGimfr:-NP47bXjDfXQ6Q1u0Lvd:bk9vbp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L183)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Lets re-use the same types as above; these are symmetric module the "BlockAll" vs. "Shed" naming but that seems superfluous. We can keep the separate cluster setting to control lease enforcement. 

Also [nit] the log only action (here and above) feels pointless -- who's actually looking at these logs? Unless you increment a metric counter which we can scan for in a CC-like environment, this is effectively dead code. Lets get rid of it, keep a metric and log under non-zero verbosity for the "NoAction" variants. These cluster settings feels overly hedgy otherwise. 
</blockquote></details>

I agree with the log setting seeing unnecessary. It would only be useful during development/tuning, but at that point, you could change the vmodule setting to get what you want.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 2251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP4Fmog4p9PO6i_CQex:-NP4Fmog4p9PO6i_CQey:b-nzz5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L2251)):*
> ```Go
> 	LeaseEnforcementLevel              LeaseIOOverloadEnforcementLevel
> 	IOOverloadThreshold                float64
> 	LeaseIOOverloadThresholdShedBuffer float64
> ```

I'm a little concerned about consistency here. We likely could add a ReplicaIOOverloadThresholdShedBuffer also in the future, but there is only one IOOverloadThreshold that is used for both. Short term it might be easier to completely separate out Lease vs Replica values as I could see the need to tune these separately. So in total there would be four values:
ReplicaIOOverloadThreshold (0.8) - value to block replica transfers
LeaseIOOverloadTheshold (0.5) - value to block lease transfers
ReplicaIOOverloadThresholdShedThreshold (2.0) - (future) value to begin shedding replicas - this should be considerably greater than 1.0 since we only want to shed when we are severely overloaded as this is expensive and it is not that bad to have replicas if we are not the leaseholder. 
LeaseIOOverloadThresholdShedThreshold (0.9) - value to begin shedding leases - this should be a little less than 1.0 since we want to shed before we begin engaging AC to prevent system slowdowns. 

I am not sure if I like the "buffer" vs "threshold" for shed, and I can see the argument for both. I slightly prefer threshold though as it can be bad if someone wants to adjust the threshold for overload a little and that unintentionally pushes the sum above 1.0.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 2321 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP4FGCtA_LnpfUnCmDk:-NP4FGCtA_LnpfUnCmDl:b-x98r75) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L2321)):*
> ```Go
> ) bool {
> 	ioOverloadScore, _ := store.Capacity.IOThreshold.Score()
> 	if o.LeaseEnforcementLevel == LeaseIOOverloadThresholdNoAction ||
> ```

If you are keeping `LogOnly` don't you need to check it here? As Irfan mentioned, I would rather just ditch that option.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 2351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP4FPUc5pTKUmlsms4a:-NP4FPUc5pTKUmlsms4b:b-60xi1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L2351)):*
> ```Go
> 	threshold := o.IOOverloadThreshold + o.LeaseIOOverloadThresholdShedBuffer
> 	ioOverloadScore, _ := store.Capacity.IOThreshold.Score()
> 	if o.LeaseEnforcementLevel == LeaseIOOverloadThresholdNoAction ||
> ```

If you are keeping `LogOnly` don't you need to check it here?


<!-- Sent from Reviewable.io -->

2023-02-24 21:47 UTC, andrewbaptist reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97587)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP4Nu_J7t718zcon8qV:-NP4Nu_J7t718zcon8qW:bpo9yaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L198)):*
> ```Go
> 	// range leases i.e. The lease will always transfer to a healthy and valid
> 	// store if one exists.
> 	LeaseIOOverloadThresholdShed
> ```

nit: The order of these matter since there is a `<` check when determining whether they are enabled. That is somewhat unexpected and we could easily introduce a bug if that wasn't apparent. I would either add a big warning to note that this order is important or preferably change the code below to not only do equality comparisons on this.


<!-- Sent from Reviewable.io -->

2023-02-27 21:57 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97587)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @irfansharif)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP31rUhCneU5Peqnd7R):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[mega nit] Avoid the "health" verbiage as best you can. Lets make this more precise, "store health" is both vague and ambiguous; we're just checking the store's IO overload score. 
</blockquote></details>

Fair enough. I've removed most references to it I could find. My initial reasoning for using "health" was that I envisaged the enforcement level being general and adding more signals that could classify a store as unhealthy from the storeHealthOptions perspective.

This hasn't really come to fruition as we spent time on other stuff and we moved (some of this stuff) into the balancing signal instead, since it is less prone to thrashing.
___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP322uI2Vo_4090y6DZ):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

"IO overload" -> "IO overload score"
</blockquote></details>

Updated.
___
*[`-- commits` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP33Lyc6I0JX4idbssL):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Could you explain why the lease transfer threshold has a higher bar? Shouldn't it have a lower bar given lease transfers are cheaper, and we ought to try and stop those first before considering the more heavy weight replica transfers?
</blockquote></details>

None of this code causes replica transfers, only filtering out stores as candidates.

The lease transfer threshold causes a lease transfer.
___
*[`-- commits` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP32nNx8CgfjNWd4yZX):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This combination of two cluster settings seems complex -- every time we debug this we'd always have to go look at two things and sum them up. It also raises questions like "Can the delta be -ve?", and knowing the value of just one of the settings is not helpful. Why not just have one specifically for leases? 
</blockquote></details>

I made it a buffer rather than a hard setting for the reason you mentioned above - I don't want it to be easy to set the shed threshold lower than the "blocking" threshold. The negative value concern seems relevant to any cluster setting which doesn't have validation. 

I'm happy to change it if you feel strongly.
___
*[`-- commits` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP33Ne65E_oAbGLIJqL):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This help text feels like it's assuming familiarity with allocator internals with its reference to "candidates" or things we're "excluding". I find it hard to use. Lets instead say something like the following (note the change in cluster setting name and enums):

```
We can control the lease transfer behaviour in the presence of IO overloaded stores using kv.allocator.io_overload_threshold_lease_enforcement:
- ignore: ignore IO overload scores entirely during lease transfers (effectively disabling this mechanism);
- future_lease_transfers: for future lease transfers only consider stores that aren't IO overloaded (existing leases on IO overloaded stores are left as is);
- shed_current_leases: actively shed leases from IO overloaded stores to less IO overloaded stores (this is a super-set of future_lease_transfers).
```
</blockquote></details>

I agree the references could be improved. I've updated these. I don't think I agree on using `future_lease_transfers` or `shed_current_leases`.  The setting itself has lease in the name, it seems unnecessary to repeat that when you enter a value for the cluster setting. 

I've updated the commit message to be clearer and changed the setting names to be consistent along the lines of 

`ignore`
`block_transfer_to`
`shed`
___
*[`-- commits` line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP45Lca0diGu3k33j2Y):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

We should add a release note as it changes the behavior when leases are transferred. There are a lot of comments on the PR text already, so I'll review again once you update.
</blockquote></details>

Added
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2035 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP36t83E7wYjmF8-kJ7:-NPJrpUqA6qmiN6CNaOd:b-7wjm6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2035)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[same mega nit] Please avoid this "health" moniker. We've overused this term in the allocator code, consider this code comment for example:

```
	// StoreFilterSuspect requests that the returned store list additionally
	// exclude stores that have been suspected as unhealthy. We dont want unhealthy
	// stores to be considered for rebalancing or for lease transfers. i.e. we dont
	// actively shift leases or replicas away from them, but we dont allow them to
	// get any new ones until they get better.
```

But this has nothing to do with IO overload scores -- it's got to do with liveness heartbeat blips due to intermittent connectivity or write stalls.
</blockquote></details>

Removed all healthy refs
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2044 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP469JC6EuY5Djp1MGV:-NP4_6U3-AZZd4A2duyz:b-jl98es) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2044)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I think this is a little wrong. If the current store is unhealthy, then we shouldn't exclude any other stores due to health reasons unless they are worse than us. Otherwise if for instance, all the stores in the system are at 0.6, no lease transfers will happen even if the current leaseholder gets severely overloaded. 
</blockquote></details>

We discussed over slack on this. For other reviewers - the mean check is baked into any call to healthyTargets/leaseIsHealthy. So this shouldn't occur.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP48BQvCmXZYqbFt9MC:-NP4_R47BFqqlO3jSZiV:bs44ai9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2198)):*
> Also I'm concerned that if all stores in the system are overloaded, then no lease transfers will happen. I'm not sure what should happen in this case, but it seems we should still correctly handle lease preference movement.

Lease preferences get filtered out before calling this fn. So we calc the avg based only on equally preferable and valid replicas. Since a store needs to be >1.1 * mean, if there's just one preferable replica it would never fail the io overload check.


> Use a different variable name for existing after each check and in the log message below, print out more details about why we ended up with no valid lease targets. Tracking this down is hard even if you have the code, and even harder if you are just looking at the log.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go` line 77 at r1](https://reviewable.io/review [...]

2023-03-06 20:07 UTC, andrewbaptist approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> I'd love to see some of the results of running this on the index backfill test with shed enabled. Once I get back to fixing the TPC-E stuff please rerun and post the results on the story. It might help make a decision for the correct default. Any other tests that cause LSM inversion would be good to run also.

> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-:-NPsWvqF4gGhhRZ_kKlX:ble4o2p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2044 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP469JC6EuY5Djp1MGV:-NPsWKlBDD4iSjcYnXV8:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2044)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

We discussed over slack on this. For other reviewers - the mean check is baked into any call to healthyTargets/leaseIsHealthy. So this shouldn't occur.
</blockquote></details>

Ack
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 2198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97587#-NP48BQvCmXZYqbFt9MC:-NPsWP9jBf_ZzGzp7HvD:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d964813c7ff9180c56dc10eb7d2210aabb97c6da/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2198)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> Also I'm concerned that if all stores in the system are overloaded, then no lease transfers will happen. I'm not sure what should happen in this case, but it seems we should still correctly handle lease preference movement.

Lease preferences get filtered out before calling this fn. So we calc the avg based only on equally preferable and valid replicas. Since a store needs to be >1.1 * mean, if there's just one preferable replica it would never fail the io overload check.


> Use a different variable name for existing after each check and in the log message below, print out more details about why we ended up with no valid lease targets. Tracking this down is hard even if you have the code, and even harder if you are just looking at the log.
</blockquote></details>

Ack


<!-- Sent from Reviewable.io -->

2023-03-06 21:39 UTC, kvoli commented
@irfansharif did you have any other comments?

2023-03-07 15:30 UTC, kvoli commented
bors r=andrewbaptist

2023-03-07 15:32 UTC, kvoli commented
bors r=andrewbaptist

2023-03-07 17:32 UTC, merged