sql: create new slice when removing backreference items
cockroachdb/cockroach pull request #97631
Opened 2023-02-24 16:43 UTC by chengxiong-ruan

Fixes: #97546

Previously we reused the underlying slots of the `DependedOnBy` slice when removing items from it. This is problematic because we normally have to iterate the same slice to figure out what to drop. Iterating on a slice which is rewritten can be problematic unless we always know how to smartly move the cursor backward. This commit changes it to just create a new slice to avoid the hazzard.

Release note: None.

2023-02-24 16:43 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/97631)
<!-- Reviewable:end -->

2023-02-24 17:16 UTC, fqazi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/alter_table.go` line 1615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97631#-NP3QAIUBg4kM-52HgPz:-NP3QAIUBg4kM-52HgQ-:bytyqjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe645a54cf3749fc0896db955d3e8777792208fc/pkg/sql/alter_table.go#L1615)):*
> ```Go
> 			return nil, err
> 		}
> 		if depDesc.Dropped() {
> ```

Is there another bug we are fixing here, we should maybe have a commit message and release not if it was public.
___
*[`pkg/sql/drop_table.go` line 650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97631#-NP3Q1tP9zoIpbwhfNx9:-NP3Q1tP9zoIpbwhfNxA:b-zdda5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe645a54cf3749fc0896db955d3e8777792208fc/pkg/sql/drop_table.go#L650)):*
> ```Go
> 	refs []descpb.TableDescriptor_Reference, id descpb.ID,
> ) []descpb.TableDescriptor_Reference {
> 	var updatedRefs []descpb.TableDescriptor_Reference
> ```

Pre-allocate based on the size of the old refs, incase nothing gets removed. That way we don't keep on growing.


<!-- Sent from Reviewable.io -->

2023-02-24 17:25 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @fqazi)

___
*[`pkg/sql/drop_table.go` line 650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97631#-NP3Q1tP9zoIpbwhfNx9:-NP3RI-g1lrGAltDK16u:b-ewglla) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe645a54cf3749fc0896db955d3e8777792208fc/pkg/sql/drop_table.go#L650)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Pre-allocate based on the size of the old refs, incase nothing gets removed. That way we don't keep on growing.
</blockquote></details>

This can be N^2 now in the worst case, right? Some other options are to collect the ids to remove or to clone the slice before iterating. This is yet another reason why the legacy schema changer is bad. I imagine the recursion makes this all tricky. What is the loop we were messing up? 


<!-- Sent from Reviewable.io -->

2023-02-24 17:37 UTC, chengxiong-ruan commented
*[`pkg/sql/drop_table.go` line 650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97631#-NP3Q1tP9zoIpbwhfNx9:-NP3UNhZDxh8aqdXhEDg:b-ipx0ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe645a54cf3749fc0896db955d3e8777792208fc/pkg/sql/drop_table.go#L650)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This can be N^2 now in the worst case, right? Some other options are to collect the ids to remove or to clone the slice before iterating. This is yet another reason why the legacy schema changer is bad. I imagine the recursion makes this all tricky. What is the loop we were messing up? 
</blockquote></details>

Yeah, N^2 can be bad if the dep graph is large.
The loops under concern here is [DROP INDEX CASCADE](https://github.com/cockroachdb/cockroach/blob/4eb5451dcfbac79906eb48340f76597ca4d8ead2/pkg/sql/drop_index.go#L427-L427) and [DROP COLUMN CASCADE](https://github.com/cockroachdb/cockroach/blob/4eb5451dcfbac79906eb48340f76597ca4d8ead2/pkg/sql/alter_table.go#L1592-L1592)
But yeah, I think collecting ids to drop is a good idea here.


<!-- Sent from Reviewable.io -->

2023-02-24 19:01 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[`pkg/sql/alter_table.go` line 1615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97631#-NP3QAIUBg4kM-52HgPz:-NP3n-wI7xee4HQfWGqL:bk8cqv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe645a54cf3749fc0896db955d3e8777792208fc/pkg/sql/alter_table.go#L1615)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Is there another bug we are fixing here, we should maybe have a commit message and release not if it was public.
</blockquote></details>

Yeah, another bug was accidentally fixed here...I added both bugs to commit message and added release note.
___
*[`pkg/sql/drop_table.go` line 650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97631#-NP3Q1tP9zoIpbwhfNx9:-NP3nBDEEzsRCqMrbacb:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe645a54cf3749fc0896db955d3e8777792208fc/pkg/sql/drop_table.go#L650)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Yeah, N^2 can be bad if the dep graph is large.
The loops under concern here is [DROP INDEX CASCADE](https://github.com/cockroachdb/cockroach/blob/4eb5451dcfbac79906eb48340f76597ca4d8ead2/pkg/sql/drop_index.go#L427-L427) and [DROP COLUMN CASCADE](https://github.com/cockroachdb/cockroach/blob/4eb5451dcfbac79906eb48340f76597ca4d8ead2/pkg/sql/alter_table.go#L1592-L1592)
But yeah, I think collecting ids to drop is a good idea here.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-02-24 19:37 UTC, ajwerner reviewed
I like this much more

2023-02-27 23:23 UTC, fqazi approved these changes
This looks much nicer <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97631#-:-NPKAuY71xjXwRyIHR-Y:b9qxgcf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan)



<!-- Sent from Reviewable.io -->

2023-02-28 04:18 UTC, ajwerner approved these changes
The version gate feels like it should have been a separate PR. 

> Reviewed 1 of 3 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97631#-:-NPLEQt87GMjGABW2F1s:b-8dllen)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chengxiong-ruan and @fqazi)

___
*[`pkg/sql/schemachanger/scdecomp/decomp.go` line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97631#-NPLDkiG883dYuclXmDA:-NPLDkiG883dYuclXmDB:bqe1icv) ([raw file](https://github.com/cockroachdb/cockroach/blob/181008fd06c0e423b75c51f4148fda47f3222536/pkg/sql/schemachanger/scdecomp/decomp.go#L123)):*
> ```Go
> 			panic(
> 				scerrors.NotImplementedErrorf(
> 					nil,
> ```

nit: can you name the `nil` with a comment?


<!-- Sent from Reviewable.io -->

2023-02-28 04:37 UTC, chengxiong-ruan commented
TFTRs!
bors r+

2023-02-28 04:38 UTC, chengxiong-ruan commented
bors r-

2023-02-28 04:41 UTC, chengxiong-ruan commented
> The version gate feels like it should have been a separate PR.
Actually it's needed in this PR... the `mixed-22.2-23.1` logictest nicely failed the tests I added because it can't do drop column which cascade drop the function.





<!-- Sent from Reviewable.io -->

2023-02-28 04:42 UTC, chengxiong-ruan commented
> The version gate feels like it should have been a separate PR.

Sorry.. terrible formatting....
Actually it's needed in this PR... the mixed-22.2-23.1 logictest nicely failed the tests I added because it can't do drop column which cascade drop the function.





<!-- Sent from Reviewable.io -->

2023-02-28 04:45 UTC, chengxiong-ruan commented
*[`pkg/sql/schemachanger/scdecomp/decomp.go` line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97631#-NPLDkiG883dYuclXmDA:-NPLKazT10yLcsqEuI-k:b-rnrapz) ([raw file](https://github.com/cockroachdb/cockroach/blob/181008fd06c0e423b75c51f4148fda47f3222536/pkg/sql/schemachanger/scdecomp/decomp.go#L123)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: can you name the `nil` with a comment?
</blockquote></details>

done. 


<!-- Sent from Reviewable.io -->

2023-02-28 14:30 UTC, chengxiong-ruan commented
TFTRs!
bors r+

2023-02-28 14:55 UTC, merged