sql: add owner_id column to system.external_connections table
cockroachdb/cockroach pull request #97877
Opened 2023-03-01 21:39 UTC by andyyang890

This patch adds a new `owner_id` column to the `system.external_connections`
table, which corresponds to the existing `owner` column. Migrations are
also added to alter and backfill the table in older clusters.

Part of #87079

Release note: None

2023-03-01 21:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/97877)
<!-- Reviewable:end -->

2023-03-06 07:35 UTC, stevendanna reviewed
Thanks! It might be good to put why we are adding this field in the PR/commit message somewhere.

We also need to handle external_connections tables in backups that don't the owner_id column.  Check out 1bc6c6d0bf54 for an example.

2023-03-06 15:07 UTC, andyyang890 commented
> It might be good to put why we are adding this field in the PR/commit message somewhere.

Done.

> We also need to handle external_connections tables in backups that don't the owner_id column. 

Yep, I'm planning on doing that in a followup PR where I set the column to be NOT NULL.

2023-03-06 17:26 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97877)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andyyang890, @dt, and @stevendanna)

___
*[`pkg/cloud/externalconn/record.go` line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-NPrx0MEExzEF9QHS43N:-NPrx0MEExzEF9QHS43O:bwqz2da) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1639fffe358696575fa0c382156ed01e971b605/pkg/cloud/externalconn/record.go#L355)):*
> ```Go
> 		case `owner`:
> 			arg = tree.NewDString(e.rec.Owner.Normalized())
> 		case `owner_id`:
> ```

it looks like this change will cause the owner_id column to always be stored. but we need to gate it on the clusterversion you just added. 

and it would be good to have a test that shows it working fine in a mixed version cluster. let's add another mixed-version logic test using the new framework (which is skipped right now, but you should be able to run locally)
___
*[`pkg/sql/create_external_connection.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-NPrvL1O7ZAp1EqCvYSs:-NPrvL1O7ZAp1EqCvYSt:b-or4gpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1639fffe358696575fa0c382156ed01e971b605/pkg/sql/create_external_connection.go#L141)):*
> ```Go
> 	row, err := txn.QueryRowEx(params.ctx, `get-user-id`, txn.KV(),
> 		sessiondata.NodeUserSessionDataOverride,
> 		`SELECT user_id FROM system.users WHERE username = $1`,
> ```

in the future, we should add another function similar to `p.User()` that returns the user ID instead. that way we can cache the user ID in one place, and avoid having to do this lookup query in many places. could you file a github issue for that, and make a comment here that references it?


<!-- Sent from Reviewable.io -->

2023-03-07 20:27 UTC, andyyang890 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97877)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, @rafiss, and @stevendanna)

___
*[`pkg/sql/create_external_connection.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-NPrvL1O7ZAp1EqCvYSs:-NPxkJQS1Yc4efAy9DFY:b-mrp7e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1639fffe358696575fa0c382156ed01e971b605/pkg/sql/create_external_connection.go#L141)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in the future, we should add another function similar to `p.User()` that returns the user ID instead. that way we can cache the user ID in one place, and avoid having to do this lookup query in many places. could you file a github issue for that, and make a comment here that references it?
</blockquote></details>

Done. See https://github.com/cockroachdb/cockroach/issues/98170


<!-- Sent from Reviewable.io -->

2023-03-07 22:47 UTC, andyyang890 reviewed
FYI I rebased this onto https://github.com/cockroachdb/cockroach/pull/98163 so the first commit is from that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-:-NPyEgAO-uUilWoHOCZi:b-ll2sg4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, @rafiss, and @stevendanna)

___
*[`pkg/cloud/externalconn/record.go` line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-NPrx0MEExzEF9QHS43N:-NPyDvQJ43oxvAk1OcIU:b5evh39) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1639fffe358696575fa0c382156ed01e971b605/pkg/cloud/externalconn/record.go#L355)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it looks like this change will cause the owner_id column to always be stored. but we need to gate it on the clusterversion you just added. 

and it would be good to have a test that shows it working fine in a mixed version cluster. let's add another mixed-version logic test using the new framework (which is skipped right now, but you should be able to run locally)
</blockquote></details>

I added some gating by threading through a map of excluded columns from the relevant planner function since I don't think this function has access to the version handle, but I'm not sure if this is the best approach. Let me know if you have any other ideas!
___
*[`pkg/upgrade/upgrades/external_connections_table_user_id_migration_test.go` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-NPyF2MnEsN0sM9mospT:-NPyF2MnEsN0sM9mospU:b-ju2vms) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0a04d572381842de9906964cc6b67cfd8359703/pkg/upgrade/upgrades/external_connections_table_user_id_migration_test.go#L20)):*
> ```Go
> 
> 	"github.com/cockroachdb/cockroach/pkg/base"
> 	_ "github.com/cockroachdb/cockroach/pkg/cloud/userfile"
> ```

I had to add this import in order to trigger the `init()` function to make the `CREATE EXTERNAL CONNECTION` statement below work.


<!-- Sent from Reviewable.io -->

2023-03-09 19:56 UTC, rafiss approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97877)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andyyang890, @dt, and @stevendanna)

___
*[`pkg/cloud/externalconn/record.go` line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-NPrx0MEExzEF9QHS43N:-NQ6wHVdEm7re0o90pxF:b-8hdhch) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1639fffe358696575fa0c382156ed01e971b605/pkg/cloud/externalconn/record.go#L355)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

I added some gating by threading through a map of excluded columns from the relevant planner function since I don't think this function has access to the version handle, but I'm not sure if this is the best approach. Let me know if you have any other ideas!
</blockquote></details>

this looks like it works, but i'd be curious if @stevendanna or @adityamaru have opinions on how to version gate this, since they own this area of the code.
___
*[`pkg/sql/logictest/testdata/logic_test/testserver_22.2_23.1_external_connections_user_id_upgrade` line 3 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-NQ6w4te7vDDv0zO8GUh:-NQ6w4te7vDDv0zO8GUi:b-v8i2tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a82cdae55a172eeb0e5ce11b7ec5ccf5cd363f/pkg/sql/logictest/testdata/logic_test/testserver_22.2_23.1_external_connections_user_id_upgrade#L3)):*
> ```
> # LogicTest: cockroach-go-testserver-22.2-master
> 
> # Verify that all nodes are running 22.2 binaries.
> ```

nit: i think we can remove these checks for 22.2 binaries. they were there in the first mixed version test more as a sanity check / proof-of-concept
___
*[`pkg/sql/logictest/testdata/logic_test/testserver_22.2_23.1_external_connections_user_id_upgrade` line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-NQ6wEAy9RewfqQUY3KR:-NQ6wEAy9RewfqQUY3KS:b-z3p5ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a82cdae55a172eeb0e5ce11b7ec5ccf5cd363f/pkg/sql/logictest/testdata/logic_test/testserver_22.2_23.1_external_connections_user_id_upgrade#L52)):*
> ```
> upgrade 2
> 
> # Verify that all nodes are now running 23.1 binaries.
> ```

ditto above


<!-- Sent from Reviewable.io -->

2023-03-09 21:12 UTC, adityamaru approved these changes
Thanks for doing this!

2023-03-10 05:55 UTC, andyyang890 commented on pkg/sql/logictest/testdata/logic_test/testserver_22.2_23.1_external_connections_user_id_upgrade
> +sleep 10s
I guess not, I've removed it!

2023-03-10 05:56 UTC, andyyang890 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97877)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, @rafiss, and @stevendanna)

___
*[`pkg/sql/logictest/testdata/logic_test/testserver_22.2_23.1_external_connections_user_id_upgrade` line 3 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-NQ6w4te7vDDv0zO8GUh:-NQ94kSP6mRpAFpJljUX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a82cdae55a172eeb0e5ce11b7ec5ccf5cd363f/pkg/sql/logictest/testdata/logic_test/testserver_22.2_23.1_external_connections_user_id_upgrade#L3)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think we can remove these checks for 22.2 binaries. they were there in the first mixed version test more as a sanity check / proof-of-concept
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/testserver_22.2_23.1_external_connections_user_id_upgrade` line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97877#-NQ6wEAy9RewfqQUY3KR:-NQ94jWBDN2omJnfrZIw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a82cdae55a172eeb0e5ce11b7ec5ccf5cd363f/pkg/sql/logictest/testdata/logic_test/testserver_22.2_23.1_external_connections_user_id_upgrade#L52)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ditto above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-10 14:23 UTC, andyyang890 commented
TFTRs!

bors r=rafiss,adityamaru

2023-03-10 16:29 UTC, andyyang890 commented
bors r=rafiss,adityamaru

2023-03-10 17:52 UTC, merged

2023-03-10 19:51 UTC, andyyang890 commented on pkg/sql/logictest/testdata/logic_test/testserver_22.2_23.1_external_connections_user_id_upgrade
> +sleep 10s
Actually, it looks like the test is flaky on CI without the additional sleep so I'm adding it back in https://github.com/cockroachdb/cockroach/pull/98401.