sql: fix record-returning udfs when used as data source
cockroachdb/cockroach pull request #98162
Opened 2023-03-07 19:00 UTC by rharding6373

When record-returning UDFs (both implicit and `RECORD` return types) are used as a data source in a query, the result should be treated as a row with separate columns instead of a tuple, which is how UDF output is normally treated. This PR closes this gap between CRDB and Postgres.

For example:

```
CREATE FUNCTION f() RETURNS RECORD AS
$$
  SELECT 1, 2, 3;
$$ LANGUAGE SQL

SELECT f()
    f
--------
 (1,2,3)

SELECT * FROM f() as foo(a int, b int, c int);
 a | b | c
---+---+---
 1 | 2 | 3
```

The behavior is the same for implicit record return types.

Epic: CRDB-19496
Fixes: #97059

Release note (sql change): UDFs with record-returning types now return a row instead of a tuple.

2023-03-07 19:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/98162)
<!-- Reviewable:end -->

2023-03-07 20:17 UTC, rharding6373 commented
Please hold off on reviewing. I introduced some test failures when finalizing this PR.

2023-03-09 00:04 UTC, rharding6373 commented
Ok, I think this is RFAL now. Thanks!

2023-03-09 22:50 UTC, DrewKimball reviewed
I like this solution. I think we should refactor some of the srf logic to also use the `insideDataSource` check, since it seems less error-prone than the current method (see #98352).

> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NQ7X9riEwpcC58jRtwP:bdul6q8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/routine.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7DrHG7F6ifJonWqIP:-NQ7DrHG7F6ifJonWqIQ:b-lx1dfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/routine.go#L116)):*
> ```Go
> 	rt := g.expr.ResolvedType()
> 	var retTypes []*types.T
> 	if g.expr.MultiColOutput {
> ```

Do you think it would be worth asserting that the type is a tuple as expected?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 730 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7JXn2E9P5cLCWhUWy:-NQ7JXn2E9P5cLCWhUWz:b-i8h8rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/scalar.go#L730)):*
> ```Go
> 				}
> 			}
> 			if b.insideDataSource && (types.IsRecordType(rtyp) || rtyp.UserDefined()) {
> ```

Won't this set `MultiColOutput` for any UDT? What happens for a user-defined enum? Could we just check if its a `TupleFamily` type instead?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7LQQP3FLoFBV6zkpx:-NQ7LQQP3FLoFBV6zkpy:b-1zns1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/scalar.go#L815)):*
> ```Go
> 	// For strict, set-returning UDFs, the evaluation logic achieves this
> 	// behavior.
> 	if !isSetReturning && !o.CalledOnNullInput && len(args) > 0 {
> ```

What happens for a strict UDF that's used as a table source?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 847 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7Y0RX2v0Sb2EkZLoU:-NQ7Y0RX2v0Sb2EkZLoV:bliud8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/scalar.go#L847)):*
> ```Go
> 	if outCol == nil && isMultiColOutput {
> 		f.ResolvedOverload().ReturnsRecordType = types.IsRecordType(rtyp)
> 		return b.finishBuildGeneratorFunction(f, f.ResolvedOverload(), out, inScope, outScope, outCol)
> ```

What is `finishBuildGeneratorFunction` doing that we haven't already done above - didn't we already synthesize all the needed columns?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7YQtsEaydO62Tv85u:-NQ7YQtsEaydO62Tv85v:b-ph8xe6) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/scalar.go#L851)):*
> ```Go
> 	// Should return a single tuple.
> 	// Synthesize an output column for set-returning UDFs.
> 	if outCol == nil && isSetReturning {
> ```

I know you didn't change this, but why are we also checking `isSetReturning` here? It seems like we'd want to synthesize a column if we don't have one already, since `finishBuildScalar` expects a non-nil `outCol`. Maybe `outCol == nil` implies `isSetReturning`, but in that case we can remove the latter check anyway.
___
*[`pkg/sql/opt/optbuilder/srfs.go` line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7PpoqDFHAONi38l6m:-NQ7PpoqDFHAONi38l6n:b-2dx62o) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/srfs.go#L114)):*
> ```Go
> 		startCols := len(outScope.cols)
> 
> 		isRecordReturningUDF := def != nil && funcExpr.ResolvedOverload().IsUDF && (texpr.ResolvedType().UserDefined() || types.IsRecordType(texpr.ResolvedType())) && b.insideDataSource
> ```

Similar to above - doesn't this condition capture UDFs that return non-tuple UDTs?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7RJ08EZrlKP4sgvSt:-NQ7RJ08EZrlKP4sgvSu:b-vo0se0) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/logictest/testdata/logic_test/udf_record#L185)):*
> ```
> ----
> a b
> 1 10
> ```

Other tests to consider:
* UDF that returns user-defined enum used as a table source
* UDF that returns SETOF RECORD used as a data source
* Strict UDF that returns RECORD used as a data source


<!-- Sent from Reviewable.io -->

2023-03-10 06:16 UTC, rharding6373 reviewed
TFTR! Good idea. When refactoring we'll have to be careful not to break the UDFs that currently use `finishBuildGeneratorFunction`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NQ97gUH0Td3RIIZNkaS:b7dff8d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/routine.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7DrHG7F6ifJonWqIP:-NQ8zgWuCnIlgf44Rs5c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/routine.go#L116)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Do you think it would be worth asserting that the type is a tuple as expected?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 730 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7JXn2E9P5cLCWhUWy:-NQ8zhz1EozGvillpUc0:b-e5lnz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/scalar.go#L730)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Won't this set `MultiColOutput` for any UDT? What happens for a user-defined enum? Could we just check if its a `TupleFamily` type instead?
</blockquote></details>

You're right, that's a bug. Fixed.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7LQQP3FLoFBV6zkpx:-NQ8zmRR2KUu0nDdmUAY:b-r428td) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/scalar.go#L815)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

What happens for a strict UDF that's used as a table source?
</blockquote></details>

Added a test, looks like we handle this correctly compared to postgres.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 847 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7Y0RX2v0Sb2EkZLoU:-NQ814si4fY0SsruOCX1:bqt309o) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/scalar.go#L847)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

What is `finishBuildGeneratorFunction` doing that we haven't already done above - didn't we already synthesize all the needed columns?
</blockquote></details>

It synthesizes the outScope columns (`finsihBuildScalar` does this, but only for one column). The columns we synthesized in the code added above are an intermediate step when we need to add a column access to expand a tuple into columns.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7YQtsEaydO62Tv85u:-NQ8gNQF05qH0ymGIY4K:b7uz5sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/scalar.go#L851)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I know you didn't change this, but why are we also checking `isSetReturning` here? It seems like we'd want to synthesize a column if we don't have one already, since `finishBuildScalar` expects a non-nil `outCol`. Maybe `outCol == nil` implies `isSetReturning`, but in that case we can remove the latter check anyway.
</blockquote></details>

Rewrote this slightly. There are cases when outScope is nil, in which case outCol is likely also nil, which can go to `finishBuildScalar`, so I modified this to check that instead.
___
*[`pkg/sql/opt/optbuilder/srfs.go` line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7PpoqDFHAONi38l6m:-NQ94D0rAi6b8kckZzye:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/srfs.go#L114)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Similar to above - doesn't this condition capture UDFs that return non-tuple UDTs?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7RJ08EZrlKP4sgvSt:-NQ8h3yJ5kzCNoFbH_bp:b-iq66em) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/logictest/testdata/logic_test/udf_record#L185)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Other tests to consider:
* UDF that returns user-defined enum used as a table source
* UDF that returns SETOF RECORD used as a data source
* Strict UDF that returns RECORD used as a data source
</blockquote></details>

Great suggestions, done. We have some `SETOF RECORD` tests in `udf_setof`, too.


<!-- Sent from Reviewable.io -->

2023-03-10 07:01 UTC, DrewKimball reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/scalar.go` line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7LQQP3FLoFBV6zkpx:-NQ9Ik4b899Qc-nDM4tq:b-83gtvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/scalar.go#L815)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Added a test, looks like we handle this correctly compared to postgres.
</blockquote></details>

Could we have an optimizer test for this case as well? I'm confused how a `CaseExpr` is returning multiple columns. Or is it returning a tuple that gets expanded after?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ9JOhi0m4esR9MHUfA:-NQ9JOhi0m4esR9MHUfB:b-1mexmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/logictest/testdata/logic_test/udf_record#L233)):*
> ```
> 
> statement ok
> CREATE FUNCTION f_strict() RETURNS RECORD STRICT AS
> ```

For the tests with strict UDFs, could we add a parameter to the functions? And also make sure they're called with both NULL and non-null inputs.


<!-- Sent from Reviewable.io -->

2023-03-13 19:53 UTC, mgartner requested changes
Nice work!

The typing of these expressions confuses me - it's counterintuitive why we need to convert back and forth between tuple and non-tuples. Some more explanation of why that's necessary would be helpful.

> Reviewed 2 of 11 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NQRWlBgEkpIzndB1O-D:bjl9i26)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`-- commits` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRSvFz0z3Xu_XXWVZ0):*
nit: I don't think `RECORD` return types are possible in v22.2, so I think we can get rid of the release note.
___
*[`pkg/sql/routine.go` line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRTau30-O6mYRuBlqq:-NQRTau30-O6mYRuBlqr:bch2n9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/routine.go#L125)):*
> ```Go
> 		for i, c := range rt.TupleContents() {
> 			retTypes[i] = c
> 		}
> ```

It might be simpler to determine the return type of the routine in execbuilder, before calling `tree.NewTypedRoutineExpr`, e.g. here: https://github.com/cockroachdb/cockroach/blob/74c8e59800377d93b1e565c4dbb62a5c7c2681bd/pkg/sql/opt/exec/execbuilder/scalar.go#L887-L894

Which makes me wonder - why isn't the memo.UDFExpr correctly typed in optbuilder? If there are multiple columns returned by the last statement, it's type should be a tuple, no?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 718 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRUx9-6tykzTwgDaeX:-NQRUx9-6tykzTwgDaeY:b-7ect) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/opt/optbuilder/scalar.go#L718)):*
> ```Go
> 				if isSingleTupleResult {
> 					rtyp.InternalType.TupleContents = stmtScope.cols[0].typ.TupleContents()
> 					rtyp.InternalType.TupleLabels = stmtScope.cols[0].typ.TupleLabels()
> ```

I'm not 100% that it's safe to muck around with a type's `InternalType`. Other expressions may hold pointers to the same type, which would cause issues. I think it's safest to create a new type.

Can you add some comments describing these cases. I'm not understanding this first case - why do we need to change `rtyp`?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 734 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRVvCDBjXyissGbBKS:-NQRVvCDBjXyissGbBKT:b-spqzx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/opt/optbuilder/scalar.go#L734)):*
> ```Go
> 				if isSingleTupleResult {
> 					// When used as a data source, we need to expand the tuple into
> 					// individual columns.
> ```

It seems odd that we need to expand the tuple into individual columns here, only to put them back into a Tuple during execution. Is there a fundamental problem with out handling of tuples vs rows - they should be more-or-less the same thing, I think.


<!-- Sent from Reviewable.io -->

2023-03-16 22:51 UTC, rharding6373 reviewed
TFTRs! I added some comments and rearranged the code to hopefully make it less confusing, let me know if that needs more work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NQgbWoE3AvkzduOkxYl:b-prfcx4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRSvFz0z3Xu_XXWVZ0):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I don't think `RECORD` return types are possible in v22.2, so I think we can get rid of the release note.
</blockquote></details>

Done.
___
*[`pkg/sql/routine.go` line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRTau30-O6mYRuBlqq:-NQYZmST0vPncsL8b7kh:bko2cvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/routine.go#L125)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It might be simpler to determine the return type of the routine in execbuilder, before calling `tree.NewTypedRoutineExpr`, e.g. here: https://github.com/cockroachdb/cockroach/blob/74c8e59800377d93b1e565c4dbb62a5c7c2681bd/pkg/sql/opt/exec/execbuilder/scalar.go#L887-L894

Which makes me wonder - why isn't the memo.UDFExpr correctly typed in optbuilder? If there are multiple columns returned by the last statement, it's type should be a tuple, no?
</blockquote></details>

When there are multiple output columns, the function return type is a tuple (as seen here, the tuple contents are the column types). The issue that motivated this change is that when the routine returns multiple columns, if we don't have a 1:1 mapping with `retTypes` the exec engine panics.

I think that adding multiple types at `NewTypedRoutineExpr` would break the `RoutineExpr`'s `TypedExpr` interface. 
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ7LQQP3FLoFBV6zkpx:-NQgb-253mFTt12sKJng:b-9mlcbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deff9e9bed291a0a5cf291f504df4e31777dda/pkg/sql/opt/optbuilder/scalar.go#L815)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Could we have an optimizer test for this case as well? I'm confused how a `CaseExpr` is returning multiple columns. Or is it returning a tuple that gets expanded after?
</blockquote></details>

Added. I added more comments to scalar.go around expanding tuples to columns to try to clarify. Let me know if they need more detail.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 718 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRUx9-6tykzTwgDaeX:-NQRmmA8-Cp_x4QLX-Ke:b-mfmirn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/opt/optbuilder/scalar.go#L718)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm not 100% that it's safe to muck around with a type's `InternalType`. Other expressions may hold pointers to the same type, which would cause issues. I think it's safest to create a new type.

Can you add some comments describing these cases. I'm not understanding this first case - why do we need to change `rtyp`?
</blockquote></details>

Good suggestion, this seems much less hacky. I updated some comments, please let me know if it's more or less clear.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 734 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRVvCDBjXyissGbBKS:-NQW-msa8I7aLsRIJzQg:bypi8ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/opt/optbuilder/scalar.go#L734)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It seems odd that we need to expand the tuple into individual columns here, only to put them back into a Tuple during execution. Is there a fundamental problem with out handling of tuples vs rows - they should be more-or-less the same thing, I think.
</blockquote></details>

Could you point me to where we are putting them back into a tuple? I could potentially see some optimization that could be done here to prevent this output tuple from being created in the first place, but after we expand it here I don't think we turn it into a tuple again. Might have missed something though.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ9JOhi0m4esR9MHUfA:-NQRj1enBhRCvhd2-FuA:bns1woo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/logictest/testdata/logic_test/udf_record#L233)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

For the tests with strict UDFs, could we add a parameter to the functions? And also make sure they're called with both NULL and non-null inputs.
</blockquote></details>

Good call, it turns out we don't do this properly, but fixing it will take a bit more work because A) the bug is elsewhere (`BuildUDF` isn't actually called if one of the function args is NULL), and B) reworking the CASE statement wrapper to return multiple NULLs or expanding columns after the CASE statement instead of before memoizing the UDF will take some refactoring.

I was going to disable all strict multi-col UDFs used as a datasource, but since the bug is elsewhere I'm learning towards allowing them for now. Thoughts?


<!-- Sent from Reviewable.io -->

2023-03-21 21:33 UTC, mgartner reviewed
> Reviewed 4 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/routine.go` line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRTau30-O6mYRuBlqq:-NR53tnq12XbpEtVLO3U:b-4ddjde) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/routine.go#L125)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

When there are multiple output columns, the function return type is a tuple (as seen here, the tuple contents are the column types). The issue that motivated this change is that when the routine returns multiple columns, if we don't have a 1:1 mapping with `retTypes` the exec engine panics.

I think that adding multiple types at `NewTypedRoutineExpr` would break the `RoutineExpr`'s `TypedExpr` interface. 
</blockquote></details>

Ahh thanks for the explanation.
___
*[`pkg/sql/routine.go` line 120 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NR53zaj52p9bxdkl63I:-NR53zaj52p9bxdkl63J:b-aikhl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/be790d02f5a2309972419297eb0c3050ac68f44e/pkg/sql/routine.go#L120)):*
> ```Go
> 		// A routine with multiple output column should have its types in a tuple.
> 		if rt.Family() != types.TupleFamily {
> 			panic(errors.AssertionFailedf("routine expected to return multiple columns"))
> ```

I don't think it's safe to panic here, but we can return an error instead.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 718 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRUx9-6tykzTwgDaeX:-NR53FC28KxPbxr7NN4f:bqjeix2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/opt/optbuilder/scalar.go#L718)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Good suggestion, this seems much less hacky. I updated some comments, please let me know if it's more or less clear.
</blockquote></details>

If `stmtScope.cols[0].typ` already has contents and labels, isn't it already a labelled tuple? Why do we have to build a new labeled tuple type?


<!-- Sent from Reviewable.io -->

2023-03-21 23:51 UTC, DrewKimball approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> sans the question about strict functions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NR5_FLC8quNBbIHpJwk:b-aeojp2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/scalar.go` line 743 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NR5WPJi1e0apBghISZ9:-NR5WPJi1e0apBghISZA:b-bgstab) ([raw file](https://github.com/cockroachdb/cockroach/blob/be790d02f5a2309972419297eb0c3050ac68f44e/pkg/sql/opt/optbuilder/scalar.go#L743)):*
> ```Go
> 			// data source. Data sources may output multiple columns, and if the
> 			// statement body produces a tuple it needs to be expanded into columns.
> 			// When not used as a data source, statements producing multiple columns, combine them into a tuple. If the last statement is already returning a tuple
> ```

[nit] Is this line too long?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ9JOhi0m4esR9MHUfA:-NR5ZL-M279HyjQAw7wZ:b7ji8nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/logictest/testdata/logic_test/udf_record#L233)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Good call, it turns out we don't do this properly, but fixing it will take a bit more work because A) the bug is elsewhere (`BuildUDF` isn't actually called if one of the function args is NULL), and B) reworking the CASE statement wrapper to return multiple NULLs or expanding columns after the CASE statement instead of before memoizing the UDF will take some refactoring.

I was going to disable all strict multi-col UDFs used as a datasource, but since the bug is elsewhere I'm learning towards allowing them for now. Thoughts?
</blockquote></details>

The bug only applies when the NULL argument is a constant, right? What happens if its a column with a NULL value?

WRT B, is it correct to just return a tuple with all NULL elements instead of NULL? Or do you see some more complication involved with that approach?


<!-- Sent from Reviewable.io -->

2023-04-07 17:38 UTC, rharding6373 reviewed
Strict UDFs now work as data sources! The main changes are not building a CASE statement for this case and adding a new routine generator to generate nulls instead. This is RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NSRlsxOAQy4h3HHvLYx:b-kkr4ku)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/routine.go` line 120 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NR53zaj52p9bxdkl63I:-NRj016b6TgJ6yx0mzUC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be790d02f5a2309972419297eb0c3050ac68f44e/pkg/sql/routine.go#L120)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think it's safe to panic here, but we can return an error instead.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 718 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQRUx9-6tykzTwgDaeX:-NRix6SR1-7lKog1iZBw:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/opt/optbuilder/scalar.go#L718)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If `stmtScope.cols[0].typ` already has contents and labels, isn't it already a labelled tuple? Why do we have to build a new labeled tuple type?
</blockquote></details>

Good point. Done.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 743 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NR5WPJi1e0apBghISZ9:-NRixHE49fpKIdiMAWzm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be790d02f5a2309972419297eb0c3050ac68f44e/pkg/sql/opt/optbuilder/scalar.go#L743)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Is this line too long?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/enums` line 1771 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSRiW8w5_ZbixTtut29:-NSRiW8w5_ZbixTtut2A:b-p19ucv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5656f70855caa6e04bb66ad17b6444cf34df9659/pkg/sql/logictest/testdata/logic_test/enums#L1771)):*
> ```
> SELECT "🙏"('😊'), "🙏"(NULL:::"Emoji 😉")
> ----
> NULL  mixed
> ```

Tested in postgres, and the new output is correct.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ9JOhi0m4esR9MHUfA:-NQhzN7P5jftX5PLV4xB:bt24s22) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/logictest/testdata/logic_test/udf_record#L233)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

The bug only applies when the NULL argument is a constant, right? What happens if its a column with a NULL value?

WRT B, is it correct to just return a tuple with all NULL elements instead of NULL? Or do you see some more complication involved with that approach?
</blockquote></details>

I think the most recent revision fixes the strict case. The solution Marcus and I came up with is in strict functions where we return records and the function is being used as a data source, we do not add the case wrapper and instead let the routine return the multiple NULLs if necessary. We could return a tuple with all NULL elements, but the challenge has been expanding the tuple into columns as expected for data sources.

Please let me know if there are any other interesting test cases that are missing.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSRkycr-AdvHp0bJSZT:-NSRkycr-AdvHp0bJSZU:b-qh9mnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5656f70855caa6e04bb66ad17b6444cf34df9659/pkg/sql/logictest/testdata/logic_test/udf_record#L321)):*
> ```
> 
> # Test ambiguous function signatures with records
> subtest ambiguity
> ```

I came up with these examples when I was modifying type checking / function resolution. None work as expected, but I think that it's out of scope for this already big PR so I filed https://github.com/cockroachdb/cockroach/issues/100928 to fix this.


<!-- Sent from Reviewable.io -->

2023-04-12 19:30 UTC, DrewKimball approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Great work!

> Reviewed 1 of 6 files at r3, 10 of 14 files at r4, 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NSqwa2IAqav_zh2WflW:bolbkdq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`-- commits` line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSqn8Cl0cSrpqNVZmFB):*
Why remove this? Also, worth mentioning that this is for UDFs used as a table source.
___
*[`pkg/sql/opt/ops/scalar.opt` line 1290 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSqnR7v-HVEEGVrZRv5:-NSqnR7v-HVEEGVrZRv6:bj4cixy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0fcd7b6999ee0fa26b95a53e2e478a6b271dc6/pkg/sql/opt/ops/scalar.opt#L1290)):*
> ```
> 
>     # Generator is true if the function may output a set of rows.
>     Generator bool
> ```

Isn't this already covered by `SetReturning`?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 740 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSqosiA2wwi3KyKvdf9:-NSqosiA2wwi3KyKvdfA:bcwirnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0fcd7b6999ee0fa26b95a53e2e478a6b271dc6/pkg/sql/opt/optbuilder/scalar.go#L740)):*
> ```Go
> 				}
> 				f.SetTypeAnnotation(rtyp)
> 				rtyp = f.ResolvedType()
> ```

[nit] I don't think this line does anything, it should always just return the same type.


<!-- Sent from Reviewable.io -->

2023-04-12 21:10 UTC, rharding6373 reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NSrIVmc-fFi-dbM7-PX:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSqn8Cl0cSrpqNVZmFB):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Why remove this? Also, worth mentioning that this is for UDFs used as a table source.
</blockquote></details>

This fixes a bug with record-returning UDFs, which were only introduced in 23.1 which has not been released yet, so no need for a release note after all.
___
*[`pkg/sql/opt/ops/scalar.opt` line 1290 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSqnR7v-HVEEGVrZRv5:-NSr8euTAk3zXhVEp-OZ:b9y03jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0fcd7b6999ee0fa26b95a53e2e478a6b271dc6/pkg/sql/opt/ops/scalar.opt#L1290)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Isn't this already covered by `SetReturning`?
</blockquote></details>

Yes, you're right. We only need a new field in routines.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 740 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSqosiA2wwi3KyKvdf9:-NSr5LbdEQnbPo3yyv1n:bg1ktfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0fcd7b6999ee0fa26b95a53e2e478a6b271dc6/pkg/sql/opt/optbuilder/scalar.go#L740)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] I don't think this line does anything, it should always just return the same type.
</blockquote></details>

You're right. Fixed.


<!-- Sent from Reviewable.io -->

2023-04-13 15:46 UTC, mgartner reviewed
Great work! It's quite a challenge to understand all this UDF behavior!

> Reviewed 2 of 11 files at r1, 1 of 4 files at r2, 1 of 6 files at r3, 7 of 14 files at r4, 3 of 4 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NSvHm3N6sueqjfcYa1j:b-2hmrll)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rharding6373)

___
*[`-- commits` line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSqn8Cl0cSrpqNVZmFB):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

This fixes a bug with record-returning UDFs, which were only introduced in 23.1 which has not been released yet, so no need for a release note after all.
</blockquote></details>

When I originally told you to remove this, I was unaware that we expect release notes for changes in pre-release (alphas and betas) behavior. So might be good to add a quick note here. Sorry to make extra work for you.
___
*[`pkg/sql/routine.go` line 120 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSv7ldCBiuVWSacEhxm:-NSv7ldCBiuVWSacEhxn:bhlk1gz) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/routine.go#L120)):*
> ```Go
> 		// A routine with multiple output column should have its types in a tuple.
> 		if rt.Family() != types.TupleFamily {
> 			return errors.New("routine expected to return multiple columns")
> ```

This should be an `errors.AssertionFailedf` because it should be an internal error at this point, I think. If the return type of the function was incorrect we should have errored earlier during type-checking.
___
*[`pkg/sql/routine.go` line 122 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSv8JJ54z0uqEUFkuEP:-NSv8JJ54z0uqEUFkuEQ:b-mxxfi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/routine.go#L122)):*
> ```Go
> 			return errors.New("routine expected to return multiple columns")
> 		}
> 		retTypes = make([]*types.T, len(rt.TupleContents()))
> ```

Can we simplify this to `retTypes = rt.TupleContents()`? As long as we don't mutate the types in `retTypes` this should be safe, AFAIK.
___
*[`pkg/sql/opt/ops/scalar.opt` line 1290 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSqnR7v-HVEEGVrZRv5:-NSv8bPzBvO8NKwejTAh:bvydt9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0fcd7b6999ee0fa26b95a53e2e478a6b271dc6/pkg/sql/opt/ops/scalar.opt#L1290)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Yes, you're right. We only need a new field in routines.
</blockquote></details>

Did you mean to remove this?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 739 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSvAVwQ-pW2eCifm6G6:-NSvAVwQ-pW2eCifm6G7:beeirl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/opt/optbuilder/scalar.go#L739)):*
> ```Go
> 					rtyp = types.MakeLabeledTuple(tc, tl)
> 				}
> 				f.SetTypeAnnotation(rtyp)
> ```

Can you explain why we need to update the type of the `tree.FuncExpr`?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 746 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSvAqUj9zqLHbUecMP_:-NSvAqUj9zqLHbUecMPa:b-rhyeon) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/opt/optbuilder/scalar.go#L746)):*
> When not used as a data source, statements producing multiple columns, combine them into a tuple.

nit: seems like there's a typo in this sentence
___
*[`pkg/sql/rowexec/project_set.go` line 194 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSvFJ1fA3xLkdulyeiy:-NSvFJ1fA3xLkdulyeiz:bo6u4pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/rowexec/project_set.go#L194)):*
> ```Go
> 					gen = builtins.NullGenerator(t.ResolvedType())
> 				} else {
> 					gen = builtins.EmptyGenerator()
> ```

This logic seems wrong for a non-set-returning function that returns multiple columns as a data source. It should produce values, but I don't think it will with the empty generator. I see you have a test like the one below, but I'm not understanding how the empty generator is working for that.

```
marcus=# CREATE FUNCTION f() RETURNS RECORD LANGUAGE SQL AS 'select 1, 2, 3';
CREATE FUNCTION

marcus=# SELECT * FROM f() AS (a INT, b INT, c INT);
 a | b | c
---+---+---
 1 | 2 | 3
(1 row)
```
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1262 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSvEFNlDFVIjUlBmxnt:-NSvEFNlDFVIjUlBmxnu:b-gqt2nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/sem/builtins/generator_builtins.go#L1262)):*
> ```Go
> func NullGenerator(typ *types.T) eval.ValueGenerator {
> 	if typ.Family() != types.TupleFamily {
> 		return nil
> ```

Should this be an error instead?
___
*[`pkg/sql/sem/tree/type_check.go` line 1143 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSvFrCO1yp6-c10acIU:-NSvFrCO1yp6-c10acIV:b9wyhi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/sem/tree/type_check.go#L1143)):*
> ```Go
> 	// NULL is given as an argument.
> 	if len(s.overloadIdxs) > 0 && calledOnNullInputFns.Len() == 0 && funcCls != GeneratorClass &&
> 		funcCls != AggregateClass && !hasUDFOverload {
> ```

Why was this type-checking change needed?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ9JOhi0m4esR9MHUfA:-NSvHNjL5VURFKacWyRp:b2t9rff) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/logictest/testdata/logic_test/udf_record#L233)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think the most recent revision fixes the strict case. The solution Marcus and I came up with is in strict functions where we return records and the function is being used as a data source, we do not add the case wrapper and instead let the routine return the multiple NULLs if necessary. We could return a tuple with all NULL elements, but the challenge has been expanding the tuple into columns as expected for data sources.

Please let me know if there are any other interesting test cases that are missing.
</blockquote></details>

Wouldn't hurt to label some of these UDFs as STABLE to make sure we're inlining correctly.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 132 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSv9wdF8At0mDAZG6z9:-NSv9wdF8At0mDAZG6zA:bha4h1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/logictest/testdata/logic_test/udf_record#L132)):*
> ```
> (1,5)
> 
> # subtest datasource
> ```

nit: un-comment the `subtest` directive


<!-- Sent from Reviewable.io -->

2023-04-13 21:19 UTC, rharding6373 reviewed
TFTR! PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NSw7ZjI0uEry_ODgUqb:bousnez)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSqn8Cl0cSrpqNVZmFB):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

When I originally told you to remove this, I was unaware that we expect release notes for changes in pre-release (alphas and betas) behavior. So might be good to add a quick note here. Sorry to make extra work for you.
</blockquote></details>

Good to know.
___
*[`pkg/sql/routine.go` line 120 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSv7ldCBiuVWSacEhxm:-NSvxcto5445k4DW-N4_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/routine.go#L120)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This should be an `errors.AssertionFailedf` because it should be an internal error at this point, I think. If the return type of the function was incorrect we should have errored earlier during type-checking.
</blockquote></details>

Done.
___
*[`pkg/sql/routine.go` line 122 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSv8JJ54z0uqEUFkuEP:-NSvxpQS-DQqzRZ-VBqT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/routine.go#L122)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can we simplify this to `retTypes = rt.TupleContents()`? As long as we don't mutate the types in `retTypes` this should be safe, AFAIK.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/ops/scalar.opt` line 1290 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSqnR7v-HVEEGVrZRv5:-NSvy2nr7uaen-dMzhog:bk0c7gz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0fcd7b6999ee0fa26b95a53e2e478a6b271dc6/pkg/sql/opt/ops/scalar.opt#L1290)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Did you mean to remove this?
</blockquote></details>

I must not have pushed all the changes that followed Drew's last review. Fixed.
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 739 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSvAVwQ-pW2eCifm6G6:-NSvyf_F8EvKvZebd-JN:b-e7yu1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/opt/optbuilder/scalar.go#L739)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you explain why we need to update the type of the `tree.FuncExpr`?
</blockquote></details>

I reworded the comment at the top of this block to try to explain this with more clarity. Could you PTAL and let me know if it needs more detail?
___
*[`pkg/sql/rowexec/project_set.go` line 194 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSvFJ1fA3xLkdulyeiy:-NSw0BZV22Mb0CCwPyp0:b-cgjde4) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/rowexec/project_set.go#L194)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This logic seems wrong for a non-set-returning function that returns multiple columns as a data source. It should produce values, but I don't think it will with the empty generator. I see you have a test like the one below, but I'm not understanding how the empty generator is working for that.

```
marcus=# CREATE FUNCTION f() RETURNS RECORD LANGUAGE SQL AS 'select 1, 2, 3';
CREATE FUNCTION

marcus=# SELECT * FROM f() AS (a INT, b INT, c INT);
 a | b | c
---+---+---
 1 | 2 | 3
(1 row)
```
</blockquote></details>

This is because of the contract with `GetRoutineGenerator`. `GetRoutineGenerator` will return a nil `gen` if the function's `CalledOnNullInput` is false and one of the args is null as a signal to use the `EmptyGenerator`. It can't return the `EmptyGenerator` (or the `NullGenerator`) due to build dependency issues.

The example you show has no null as input params, so `GetRoutineGenerator` would have returned a valid, non-nil `gen`.

I added a comment which doesn't quite go into this detail, but hopefully adds some clarity as to why we use the `NullGenerator` here and why that's ok. Also did some refactoring now that `NullGenerator` returns an error.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1262 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSvEFNlDFVIjUlBmxnt:-NSw3s_j9KPiyhZy5JXP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/sem/builtins/generator_builtins.go#L1262)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should this be an error instead?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/type_check.go` line 1143 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSvFrCO1yp6-c10acIU:-NSw45lS9zgq-RpBg5cM:b-r6sjml) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/sem/tree/type_check.go#L1143)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why was this type-checking change needed?
</blockquote></details>

This block of the code checks args for nulls, and if there are any null args and there are no overloads that can be called on null input the type checker returns null. It's essentially a fast path for functions that are not called on null input.

This is not the expected behavior for strict record-returning UDFs, which should not be called on null input but should return nulls for every output column. Unfortunately, we don't know how many nulls to return until we have an overload, which is what this function (or call chain of functions) is supposed to provide :-(. I've opted to let UDFs handle their own called on null input behavior instead of having the type checker do it.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ9JOhi0m4esR9MHUfA:-NSw7RUHAmr7gMODYmYu:bgmkmgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/logictest/testdata/logic_test/udf_record#L233)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Wouldn't hurt to label some of these UDFs as STABLE to make sure we're inlining correctly.
</blockquote></details>

Scattered some STABLEs throughout the test. This did find a bug, and when I tried to fix inlining to make it work with record-returning UDFs, I eventually remembered that subqueries can only return 1 column, so inlining when they're used as a datasource doesn't work :-(


<!-- Sent from Reviewable.io -->

2023-04-18 20:28 UTC, rharding6373 commented
Gentle ping @mgartner

2023-04-20 14:25 UTC, mgartner reviewed
Sorry for the delay. This is looking great! Just a few more nits and some suggestions on tests to add.

> Reviewed 1 of 14 files at r4, 5 of 7 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NTU2J652M4UCy6mMvKm:b30yhgk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/opt/ops/scalar.opt` line 1287 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NTTyiRaC31vRVPVwzvM:-NTTyiRaC31vRVPVwzvN:b-mtk1kr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4391b91689cb7aef783fcefb29b5b7e9f6a097b7/pkg/sql/opt/ops/scalar.opt#L1287)):*
> ```
> 
>     # MultiColOutput is true if the function may return multiple columns.
>     MultiColOutput bool
> ```

This is only true if the UDF is used as a datasource, correct? Can you add that to the comment here? Does it make more sense to name this `MultiColDataSource`?
___
*[`pkg/sql/opt/optbuilder/scalar.go` line 739 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSvAVwQ-pW2eCifm6G6:-NTTzYA20xYM6BYRb_sv:br06oxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/90ff224acc833088129266672b736bfaa1b9ac93/pkg/sql/opt/optbuilder/scalar.go#L739)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I reworded the comment at the top of this block to try to explain this with more clarity. Could you PTAL and let me know if it needs more detail?
</blockquote></details>

Looks good, thanks!
___
*[`pkg/sql/rowexec/project_set.go` line 190 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NTTxyHk4dINrKZeaMgg:-NTTxyHlCbqgpTZKIiXf:bl3et3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4391b91689cb7aef783fcefb29b5b7e9f6a097b7/pkg/sql/rowexec/project_set.go#L190)):*
> ```Go
> 					// (i.e., Generators), have different behavior and are handled
> 					// separately.
> 					gen, err = builtins.NullGenerator(t.ResolvedType())
> ```

It'd be nice to put this logic into `eval.GetRoutineGenerator`, but I suspect that'll cause in import cycle betwen `eval` and `builtins`. For now, can you update the comment here to reflect that the empty or null generator can be used: https://github.com/cockroachdb/cockroach/blob/1b45ced1a1b96fee6e1c8fe58fa207d2905b114c/pkg/sql/sem/eval/generators.go#L54-L56
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ9JOhi0m4esR9MHUfA:-NTU0d9O4RKiRQfLe9Y3:b-e5qayb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/logictest/testdata/logic_test/udf_record#L233)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Scattered some STABLEs throughout the test. This did find a bug, and when I tried to fix inlining to make it work with record-returning UDFs, I eventually remembered that subqueries can only return 1 column, so inlining when they're used as a datasource doesn't work :-(
</blockquote></details>

Good find. I think that's an ok sacrifice for now. We can revisit lifting that restriction in the future.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NSRkycr-AdvHp0bJSZT:-NTU17NK8uvYupBL7vxn:b-73m6vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5656f70855caa6e04bb66ad17b6444cf34df9659/pkg/sql/logictest/testdata/logic_test/udf_record#L321)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I came up with these examples when I was modifying type checking / function resolution. None work as expected, but I think that it's out of scope for this already big PR so I filed https://github.com/cockroachdb/cockroach/issues/100928 to fix this.
</blockquote></details>

Nice catch!
___
*[`pkg/sql/opt/optbuilder/testdata/udf` line 1175 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NTU1e7C0zxpvvuUiBBh:-NTU1e7C0zxpvvuUiBBi:b1037oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4391b91689cb7aef783fcefb29b5b7e9f6a097b7/pkg/sql/opt/optbuilder/testdata/udf#L1175)):*
> ```
> 
> build format=show-scalars
> SELECT * FROM strict_fn_record(1, 'foo', false) as bar(i INT, t TEXT, b BOOl)
> ```

Some tests here with nested datasources would be good. I'm most concerned about `insideDataSource` working correctly with something like this:

```
SELECT * FROM (SELECT strict_fn_record(1, 'foo', false) FROM (VALUES (1), (2)))
```

Some logic tests like this might be good to have too.


<!-- Sent from Reviewable.io -->

2023-04-21 16:55 UTC, rharding6373 reviewed
TFTR! Turns out there wasn't much that could be simplified here after the strict/inlining changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NTZjAsp6u-MqygtEqsn:b-tsp7s0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/ops/scalar.opt` line 1287 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NTTyiRaC31vRVPVwzvM:-NTW0514DOnPd0ty0Y5o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4391b91689cb7aef783fcefb29b5b7e9f6a097b7/pkg/sql/opt/ops/scalar.opt#L1287)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is only true if the UDF is used as a datasource, correct? Can you add that to the comment here? Does it make more sense to name this `MultiColDataSource`?
</blockquote></details>

Done.
___
*[`pkg/sql/rowexec/project_set.go` line 190 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NTTxyHk4dINrKZeaMgg:-NTVzQq5-sWCKhb3mlUD:b-ah6mxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4391b91689cb7aef783fcefb29b5b7e9f6a097b7/pkg/sql/rowexec/project_set.go#L190)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It'd be nice to put this logic into `eval.GetRoutineGenerator`, but I suspect that'll cause in import cycle betwen `eval` and `builtins`. For now, can you update the comment here to reflect that the empty or null generator can be used: https://github.com/cockroachdb/cockroach/blob/1b45ced1a1b96fee6e1c8fe58fa207d2905b114c/pkg/sql/sem/eval/generators.go#L54-L56
</blockquote></details>

Yes, I tried that before and there's an import cycle :-(

Updated the comment.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_record` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NQ9JOhi0m4esR9MHUfA:-NTVznZp8m7-nOVDHsPl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb39a5bbca12e4707d2ef38c2b63b8e591bd937/pkg/sql/logictest/testdata/logic_test/udf_record#L233)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good find. I think that's an ok sacrifice for now. We can revisit lifting that restriction in the future.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/testdata/udf` line 1175 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-NTU1e7C0zxpvvuUiBBh:-NTZiszm1Q9vCYZjQ76U:b-kg62qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4391b91689cb7aef783fcefb29b5b7e9f6a097b7/pkg/sql/opt/optbuilder/testdata/udf#L1175)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Some tests here with nested datasources would be good. I'm most concerned about `insideDataSource` working correctly with something like this:

```
SELECT * FROM (SELECT strict_fn_record(1, 'foo', false) FROM (VALUES (1), (2)))
```

Some logic tests like this might be good to have too.
</blockquote></details>

That was a good test. Found an error and fixed it.


<!-- Sent from Reviewable.io -->

2023-04-24 15:42 UTC, mgartner approved these changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice job working through all these tricky edge cases!

> Reviewed 13 of 13 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NTnvORm8GaMwY17mpJR:b-4iige4)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)



<!-- Sent from Reviewable.io -->

2023-04-24 15:54 UTC, rharding6373 reviewed
TFTRs everyone!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98162#-:-NTnwcJLEF4e226dGH7j:bb46uk3)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)



<!-- Sent from Reviewable.io -->

2023-04-24 16:46 UTC, rharding6373 commented
Bors failed with a known flake: https://github.com/cockroachdb/cockroach/issues/101336

bors r+

2023-04-24 17:17 UTC, merged