sql: disallow using cluster_logical_timestamp as column default when backfilling
cockroachdb/cockroach pull request #98696
Opened 2023-03-15 18:09 UTC by Xiang-Gu

Previously, `ADD COLUMN ... DEFAULT cluster_logical_timestamp()` would crash the node and leave the table in a corrupt state. The root cause is a nil pointer dereference. This commit fixed it by returning an unimplemented error and hence disallow using this builtin function as default value when backfilling.

Fixes: #98269
Release note (bug fix): fixed a bug as detailed in #98269.

2023-03-15 18:10 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/98696)
<!-- Reviewable:end -->

2023-03-15 23:53 UTC, rharding6373 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/backfill/backfill.go` line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98696#-NQbeHXw71QLYFk3yiGV:-NQbeHXw71QLYFk3yiGW:b-c9dn5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7aa6ea798f370593d847e4b60eb74a250d508a/pkg/sql/backfill/backfill.go#L380)):*
> ```Go
> 				if errors.Is(err, colexecerror.ErrNilTxnAccessedInColBackfill) {
> 					// Issue #98269; Cannot use `cluster_logical_timestamp()` as column default value.
> 					return roachpb.Key{}, pgerror.WithCandidateCode(err, pgcode.FeatureNotSupported)
> ```

Consider using `unimplemented.NewWithIssue` instead.
___
*[`pkg/sql/sem/eval/context.go` line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98696#-NQbaDvx-DzWcEvKVAeM:-NQbaDvx-DzWcEvKVAeN:b-9nwy7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7aa6ea798f370593d847e4b60eb74a250d508a/pkg/sql/sem/eval/context.go#L501)):*
> ```Go
> func (ec *Context) GetClusterTimestamp() (*tree.DDecimal, error) {
> 	if ec.Txn == nil {
> 		return nil, colexecerror.ErrNilTxnAccessedInColBackfill
> ```

`GetClusterTimestamp()` can be called outside of col backfill, right? It seems like this error is misnamed. Maybe something like `ErrNilTxnInClusterContext` instead.


<!-- Sent from Reviewable.io -->

2023-03-17 15:33 UTC, Xiang-Gu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/backfill/backfill.go` line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98696#-NQbeHXw71QLYFk3yiGV:-NQkC-CpCrhGNJAxcHZc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7aa6ea798f370593d847e4b60eb74a250d508a/pkg/sql/backfill/backfill.go#L380)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Consider using `unimplemented.NewWithIssue` instead.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/eval/context.go` line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98696#-NQbaDvx-DzWcEvKVAeM:-NQkC-lh4AdDZjn9Tk-w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7aa6ea798f370593d847e4b60eb74a250d508a/pkg/sql/sem/eval/context.go#L501)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

`GetClusterTimestamp()` can be called outside of col backfill, right? It seems like this error is misnamed. Maybe something like `ErrNilTxnInClusterContext` instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-17 16:09 UTC, Xiang-Gu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/backfill/backfill.go` line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98696#-NQbeHXw71QLYFk3yiGV:-NQkJuud5kQBfGRXiRPC:b2cezx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7aa6ea798f370593d847e4b60eb74a250d508a/pkg/sql/backfill/backfill.go#L380)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It turns out I cannot. The base error is defined and I can only decorate it with a FeatureNotSupported pgcode. Plus, I don't think creating a issue for this is necessary; my original comments refers to the issue that required this fix. I've updated the comments.


<!-- Sent from Reviewable.io -->

2023-03-17 16:22 UTC, fqazi approved these changes
> Reviewed 1 of 8 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)



<!-- Sent from Reviewable.io -->

2023-03-17 17:06 UTC, Xiang-Gu commented
TFTR!

bors r+

2023-03-17 19:46 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98696#-:-NQl5yLdEPwDOeX93f2o:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Xiang-Gu)



<!-- Sent from Reviewable.io -->

2023-03-20 15:38 UTC, Xiang-Gu commented
bors r+

2023-03-20 16:41 UTC, merged