Jsonb forward indexes composite testing
cockroachdb/cockroach pull request #99275
Opened 2023-03-22 20:01 UTC by Shivs11

2023-03-22 20:01 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/99275)
<!-- Reviewable:end -->

2023-03-30 14:38 UTC, Shivs11 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/sql/ttl/ttljob/ttljob_test.go` line 583 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NRmwh_C7GG-X5lp9bKi:-NRmwh_C7GG-X5lp9bKj:bm4uqpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e14460d1a55881451774d2b5b8db940ca6ecc2bc/pkg/sql/ttl/ttljob/ttljob_test.go#L583)):*
> ```Go
> 			indexableTyps = append(indexableTyps, typ)
> 		}
> 	}
> ```

An issue has been raised here: https://github.com/cockroachdb/cockroach/issues/99432


<!-- Sent from Reviewable.io -->

2023-04-03 19:50 UTC, yuzefovich commented
@Shivs11 there are no explicit reviewers on this PR. Once any PR is ready for a look, you should explicitly assign a couple of people for review (usually two is the right number: one person who you believe is the expert in this part of the codebase, and another person who would benefit from learning a bit more about this part of the codebase). In this example, perhaps myself and @mgartner are the right people to review since we spent most time when reviewing your JSON key encoding change.

2023-04-04 12:29 UTC, Shivs11 reviewed
Oh I see. I wasn't sure if that was great practice since I was under the assumption if I tagged someone more than once it would be repetitive. I shall keep this in mind from next time, and thank you for tagging Marcus into this too!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-:-NSBEFwM00Kf2mDQySoj:bxecp5r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)



<!-- Sent from Reviewable.io -->

2023-04-04 14:06 UTC, mgartner requested changes
> Reviewed 23 of 36 files at r1, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Shivs11 and @yuzefovich)

___
*[`.gitignore` line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBK5P07k00iQBuZxEt:-NSBK5P07k00iQBuZxEu:bvwgxzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/.gitignore#L60)):*
> ```ignore
> 
> pkg/sql/logictest/testdata/logic_test/__test
> .idea/
> ```

Add these to `.git/info/exclude` which isn't tracked in the repository, instead of editing the shared `.gitignore` file.
___
*[`pkg/sql/catalog/systemschema/system.go` line 2677 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBKVy95NKs5T6yAkad:-NSBKVy95NKs5T6yAkae:b-486fkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/catalog/systemschema/system.go#L2677)):*
> ```Go
> 				Type:                descpb.IndexDescriptor_INVERTED,
> 				InvertedColumnKinds: []catpb.InvertedIndexColumnKind{catpb.InvertedIndexColumnKind_DEFAULT},
> 				CompositeColumnIDs:  []descpb.ColumnID{13},
> ```

This is an inverted index. Since an inverted index key encodes only a single "path" of the value, the column value cannot be derived from a single key. So "composite"-ness doesn't really apply here. Is this change necessary?
___
*[`pkg/sql/colencoding/key_encoding.go` line 194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBLr66DkWI1mOs8MDq:-NSBLr66DkWI1mOs8MDr:bccfb8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/colencoding/key_encoding.go#L194)):*
> ```Go
> 
> 		// Decode the JSON, and then store the bytes in the
> 		// vector in the value-encoded format.
> ```

"and then store the bytes in the vector in the value-encoded format" - I don't understand this part. I don't see any value-encoding happening below. Can you clarify this?
___
*[`pkg/sql/sem/tree/datum.go` line 3621 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBQPkJ7cZZMdgIeEV2:-NSBQPkJ7cZZMdgIeEV3:bogqlsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3621)):*
> ```Go
> 		dec, isDone := d.JSON.AsDecimal()
> 		if !isDone {
> 			panic("could not convert into JSON Decimal")
> ```

nit: this should be `panic(errors.AssertionFailedf("..."))`
___
*[`pkg/sql/sem/tree/datum.go` line 3628 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBQUuQ99n8AlFdcr0I:-NSBQUuQ99n8AlFdcr0J:bogqlsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3628)):*
> ```Go
> 		jsonArray, isDone := d.AsArray()
> 		if !isDone {
> 			panic("could not extract the JSON Array")
> ```

nit: this should be `panic(errors.AssertionFailedf("..."))`
___
*[`pkg/sql/sem/tree/datum.go` line 3637 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBQtAn3iBYnnsxYkRl:-NSBQrR192vyp5a7lKzw:b3fhqgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3637)):*
> ```Go
> 		}
> 	case json.ObjectJSONType:
> 		if it, err := d.ObjectIter(); it != nil && err == nil {
> ```

This is ignoring a non-nil `err`. We should probably panick instead of ignoring the error.
___
*[`pkg/sql/logictest/testdata/logic_test/expression_index` line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBRfO_ARhlvd3bloFv:-NSBRfO_ARhlvd3bloFw:b-6uht9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/expression_index#L118)):*
> ```
> 
> statement ok
> DROP TABLE err
> ```

You should replace these error tests with tests that make sure these indexes work as intended. Checkout the "Querying expression indexes" and "backfilling expression indexes" section, where you can add these tests.

https://github.com/cockroachdb/cockroach/blob/4fe110098e25f23baa47f685a4a8ba1d5f35fc51/pkg/sql/logictest/testdata/logic_test/expression_index#L586`
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 81 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSB_PAD6MEifUrZcy-R:-NSB_PAD6MEifUrZcy-S:b-7j8wra) ([raw file](https://github.com/cockroachdb/cockroach/blob/2414bbadfb48015de9bc7444bc4379881d7c3f90/pkg/sql/logictest/testdata/logic_test/inverted_index#L81)):*
> ```
>   foo JSONB,
>   bar JSONB,
>   INVERTED INDEX (foo, bar)
> ```

This is an interesting index type that we should add some tests for - it's a multi-column inverted index where the first indexed column is indexed in the forward-indexing manner, and the second is indexed as an inverted value.
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index_multi_column` line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSB_dgSEgKD8FT1Od6W:-NSB_dgSEgKD8FT1Od6X:buzlhj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2414bbadfb48015de9bc7444bc4379881d7c3f90/pkg/sql/logictest/testdata/logic_test/inverted_index_multi_column#L13)):*
> ```
> # Err if a non-last column is not a non-invertable type.
> statement error column j of type jsonb is only allowed as the last column in an inverted index\nHINT: see the documentation for more information about inverted indexes: https://www.cockroachlabs.com/docs/.*/inverted-indexes.html
> CREATE TABLE m_err (k INT PRIMARY KEY, a INT, j JSON, geom GEOMETRY, INVERTED INDEX (a, j, geom))
> ```

We should test this type of index too.
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 948 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBVGDIDfEZLP7UVAVh:-NSBVGDIDfEZLP7UVAVi:bymhsrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/json#L948)):*
> ```
> 
> 
> # Add JSON columns as primary index.
> ```

nit: can you move these tests to a new file, like `json_index`. This file is mostly for basic JSON tests, not involving indexes.
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 962 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBWCsr7ke_G_D6v6Hq:-NSBWCsr7ke_G_D6v6Hr:b-etldoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/json#L962)):*
> ```
>   ('100'::JSONB),
>   ('1'::JSONB),
>   ('{"a": "b"}')
> ```

Can you add some composite values like `1.00`, `1.0`, `["a", 1.20]`, etc. here and test them below?
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 965 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBVRomBHTp46S3AQ92:-NSBVRomBHTp46S3AQ93:b-h2xs4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/json#L965)):*
> ```
> 
> # Ensuring the ordering is intact due
> # to the creation of an index
> ```

The index is not ensuring ordering here - the `ORDER BY` in the query is. What are you trying to test?
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 1063 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBX31c0gt1zFFOcHQU:-NSBX31d5kxZccP2GzSw:b6n9day) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/json#L1063)):*
> ```
> statement ok
> INSERT INTO t VALUES
>   ('true'::JSONB),
> ```

nit: You can omit the `::JSONB` casts - the string literals will be automatically casted to string literals.
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 1113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBXFDM-3_vStvZ6p1q:-NSBXFDM-3_vStvZ6p1r:br2wb8u) ([raw file](https://github.com/cockroachdb/co [...]

2023-04-04 22:26 UTC, yuzefovich reviewed
> Reviewed 8 of 36 files at r1, 6 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @Shivs11)

___
*[`pkg/sql/colencoding/key_encoding.go` line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDH2c56ozbPGBH1Gj4:-NSDH2c56ozbPGBH1Gj5:bhyuc9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/colencoding/key_encoding.go#L192)):*
> ```Go
> 		vecs.IntervalCols[colIdx][rowIdx] = d
> 	case types.JsonFamily:
> ```

nit: stray empty line (we don't have such a line in previous `case`s).
___
*[`pkg/sql/colencoding/key_encoding.go` line 194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBLr66DkWI1mOs8MDq:-NSDJrlfDnPFpTOHWPuD:b-i1ry2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/colencoding/key_encoding.go#L194)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

"and then store the bytes in the vector in the value-encoded format" - I don't understand this part. I don't see any value-encoding happening below. Can you clarify this?
</blockquote></details>

What happens here is that we first key-decode the json in `keyside.Decode` and then in `coldata.JSONs.Set` we pass in `json.JSON` object that is value-encoded internally and is stored in the underlying `coldata.Bytes` vector as `[]byte`.

This seems reasonable; however, I wonder whether in the future we will want to extend `coldata.JSONs` to store the key-encoded JSONs? I.e. currently we assume that `JSONs.Bytes` stores value-encoded JSONs, but we could mark the vector as storing key-encoded JSONs and then we'd avoid this "key-decode and then value-encode" step here (we'd be key-decoding on demand in `coldata.JSONs.Get`). Consider leaving a TODO here to explore this idea.
___
*[`pkg/sql/colencoding/key_encoding.go` line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDJZTC7FJXSE7yqarq:-NSDIHOR0dshhDEsMDyd:b951nb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/colencoding/key_encoding.go#L202)):*
> ```Go
> 		}
> 		d, rkey, err = keyside.Decode(da, valType, key, encDir)
> 		json, _ = tree.AsJSON(d, sessiondatapb.DataConversionConfig{}, time.UTC)
> ```

nit: you should just do `json, ok := d.(*tree.DJSON)` and return an error `if !ok`.
___
*[`pkg/sql/sem/tree/datum.go` line 3615 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDLT8Z9FC3Mbs0Mp8g:-NSDLT8Z9FC3Mbs0Mp8h:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3615)):*
> ```Go
> }
> 
> // DJSON implements the CompositeDatum interface
> ```

nit: missing period.
___
*[`pkg/sql/sem/tree/datum.go` line 3619 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDLOmFEu8QVoAhzbga:-NSDLOmFEu8QVoAhzbgb:b-j29h0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3619)):*
> ```Go
> 	switch d.JSON.Type() {
> 	case json.NumberJSONType:
> 		dec, isDone := d.JSON.AsDecimal()
> ```

nit: `isDone` is an unusual name for this variable, I think the comment pattern is to use `ok`.
___
*[`pkg/sql/sem/tree/datum.go` line 3638 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDLeY49QyBN3cqHFQ4:-NSDLeY49QyBN3cqHFQ5:b-10psh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3638)):*
> ```Go
> 	case json.ObjectJSONType:
> 		if it, err := d.ObjectIter(); it != nil && err == nil {
> 			// Assumption: no collated strings are
> ```

nit: these comment lines are too short (sorry, I probably mentioned previously that some other comment lines were too long :smile: ) - we should strive for lines with up to 80 characters in the comments.
___
*[`pkg/sql/sem/tree/datum.go` line 3648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDLxv23i5oS1ft0uIe:-NSDLxv23i5oS1ft0uIf:b94iihn) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3648)):*
> ```Go
> 				}
> 			}
> 			return false
> ```

nit: this `return` is redundant with the global `return false` below.
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 81 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSB_PAD6MEifUrZcy-R:-NSDMrbx0HwJSHSsxcXh:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/2414bbadfb48015de9bc7444bc4379881d7c3f90/pkg/sql/logictest/testdata/logic_test/inverted_index#L81)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is an interesting index type that we should add some tests for - it's a multi-column inverted index where the first indexed column is indexed in the forward-indexing manner, and the second is indexed as an inverted value.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-04-06 16:48 UTC, Shivs11 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/colencoding/key_encoding.go` line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDH2c56ozbPGBH1Gj4:-NSG_EVY3cLgHfrdIALo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/colencoding/key_encoding.go#L192)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: stray empty line (we don't have such a line in previous `case`s).
</blockquote></details>

Done.
___
*[`pkg/sql/colencoding/key_encoding.go` line 194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBLr66DkWI1mOs8MDq:-NSG_Rg06KuPonipfAG2:b-ddhqku) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/colencoding/key_encoding.go#L194)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

What happens here is that we first key-decode the json in `keyside.Decode` and then in `coldata.JSONs.Set` we pass in `json.JSON` object that is value-encoded internally and is stored in the underlying `coldata.Bytes` vector as `[]byte`.

This seems reasonable; however, I wonder whether in the future we will want to extend `coldata.JSONs` to store the key-encoded JSONs? I.e. currently we assume that `JSONs.Bytes` stores value-encoded JSONs, but we could mark the vector as storing key-encoded JSONs and then we'd avoid this "key-decode and then value-encode" step here (we'd be key-decoding on demand in `coldata.JSONs.Get`). Consider leaving a TODO here to explore this idea.
</blockquote></details>

By the "value-encoded format", I meant that the call of the function `.Set` results in calling the function `EncodeJSON`. This function is responsible for encoding JSON in a structure which is different than the key-encoding scheme that I had defined for JSON previously. This scheme involves the creation of `JEntry` objects which are used when value encoding JSON.

@yuzefovich That's a good idea and would be much simpler to work with in the future. Shall leave a TO-DO and get back to it. 
___
*[`pkg/sql/colencoding/key_encoding.go` line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDJZTC7FJXSE7yqarq:-NSGcaLB3XH4J3jkuG6w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/colencoding/key_encoding.go#L202)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: you should just do `json, ok := d.(*tree.DJSON)` and return an error `if !ok`.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/datum.go` line 3615 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDLT8Z9FC3Mbs0Mp8g:-NSGcfvi4EMKe2nxnUCp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3615)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: missing period.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/datum.go` line 3619 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDLOmFEu8QVoAhzbga:-NSGcnkJ8s6f4yke44z7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3619)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `isDone` is an unusual name for this variable, I think the comment pattern is to use `ok`.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/datum.go` line 3621 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBQPkJ7cZZMdgIeEV2:-NSGczY1CnBc2A5XsmR1:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3621)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: this should be `panic(errors.AssertionFailedf("..."))`
</blockquote></details>

Done!
___
*[`pkg/sql/sem/tree/datum.go` line 3628 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBQUuQ99n8AlFdcr0I:-NSGd-Ki3MpSsc9YOeIX:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3628)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: this should be `panic(errors.AssertionFailedf("..."))`
</blockquote></details>

Done!
___
*[`pkg/sql/sem/tree/datum.go` line 3637 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBQtAn3iBYnnsxYkRl:-NSGdm7ACjvwCt6L2aVK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3637)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is ignoring a non-nil `err`. We should probably panick instead of ignoring the error.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/datum.go` line 3638 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDLeY49QyBN3cqHFQ4:-NSGdtun66FPX7-FHulh:bs7wuaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3638)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: these comment lines are too short (sorry, I probably mentioned previously that some other comment lines were too long :smile: ) - we should strive for lines with up to 80 characters in the comments.
</blockquote></details>

Done !
___
*[`pkg/sql/sem/tree/datum.go` line 3648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSDLxv23i5oS1ft0uIe:-NSGe7po35yOuNLSwgcU:b-xvohb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/sem/tree/datum.go#L3648)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this `return` is redundant with the global `return false` below.
</blockquote></details>

You're right. Done.
___
*[`pkg/sql/logictest/testdata/logic_test/expression_index` line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBRfO_ARhlvd3bloFv:-NSHKX4l0znhu1h_Yt81:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/expression_index#L118)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You should replace these error tests with tests that make sure these indexes work as intended. Checkout the "Querying expression indexes" and "backfilling expression indexes" section, where you can add these tests.

https://github.com/cockroachdb/cockroach/blob/4fe110098e25f23baa47f685a4a8ba1d5f35fc51/pkg/sql/logictest/testdata/logic_test/expression_index#L586`
</blockquote></details>

Done!
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 81 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSB_PAD6MEifUrZcy-R:-NSHtJ2g-bSsfD2E0WWu:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/2414bbadfb48015de9bc7444bc4379881d7c3f90/pkg/sql/logictest/testdata/logic_test/inverted_index#L81)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done!
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index_multi_column` line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSB_dgSEgKD8FT1Od6W:-NSI1eYW2LcCoV8XSF3Y:b-jtupa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2414bbadfb48015de9bc7444bc4379881d7c3f9 [...]

2023-04-06 19:00 UTC, yuzefovich reviewed
nit: add "Fixes: <issue number>" to the PR description.

> Reviewed 8 of 36 files at r1, 1 of 4 files at r2, 3 of 12 files at r3, 13 of 26 files at r5, 13 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-:-NSMo57cD9wlRW6acu30:b6x6fxo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @mgartner, and @Shivs11)

___
*[`pkg/sql/colencoding/key_encoding.go` line 202 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMoX578G6UWP3SFd75:-NSMoX578G6UWP3SFd76:b-lfv6wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/colencoding/key_encoding.go#L202)):*
> ```Go
> 		json, ok := d.(*tree.DJSON)
> 		if !ok {
> 			return nil, false, scratch, errors.New("Could not type assert into DJSON")
> ```

nit: this probably should be `errors.AssertionFailedf`.
___
*[`pkg/sql/sem/tree/datum.go` line 3615 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMsDFgAfi36iUWRu7r:-NSMsDFgAfi36iUWRu7s:b-calw64) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/sem/tree/datum.go#L3615)):*
> ```Go
> }
> 
> // DJSON implements the CompositeDatum interface.
> ```

nit: do `IsComposite implements the CompositeDatum interface.`.
___
*[`pkg/sql/logictest/testdata/logic_test/expression_index` line 644 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMw0kY3D1mRLCxGUhD:-NSMw0kY3D1mRLCxGUhE:bymgr83) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/logictest/testdata/logic_test/expression_index#L644)):*
> ```
> statement ok
> CREATE TABLE d (a INT, j JSON);
> CREATE INDEX json_expr_index on d ((j->'a'))
> ```

nit: it'd be good to add some EXPLAIN tests for the queries in this file to `execbuilder/testdata`.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 229 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMtvJe1LjOQ-SP57NO:-NSMtvJe1LjOQ-SP57NP:bvyb2cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/opt/exec/execbuilder/testdata/json#L229)):*
> ```
> 
> query T kvtrace
> INSERT INTO composite VALUES ('1.00'::JSONB), ('2'::JSONB), ('3.0'::JSONB), ('"a"'::JSONB)
> ```

nit: maybe include `'1'::JSONB` to highlight the difference from `'1.00'::JSONB`? This will require introducing a non-unique secondary index on the json column.
___
*[`pkg/sql/rowenc/index_encoding_test.go` line 176 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMuOkKBexsI24KsDrv:-NSMuOkKBexsI24KsDrw:bwmkxp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/rowenc/index_encoding_test.go#L176)):*
> ```Go
> 			secondaryValues: []tree.Datum{tree.NewDInt(20)},
> 		},
> 		// Testing JSON in primary indexes.
> ```

nit: shouldn't this comment be a few lines above?
___
*[`pkg/sql/rowenc/index_encoding_test.go` line 270 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMugISDj_SK9kJ-SEj:-NSMugISDj_SK9kJ-SEk:bgxwv2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/rowenc/index_encoding_test.go#L270)):*
> ```Go
> 		evalCtx := eval.NewTestingEvalContext(cluster.MakeTestingClusterSettings())
> 		defer evalCtx.Stop(context.Background())
> 		tableDesc, colMap := makeTableDescForTest(test, true)
> ```

nit: add inlined comment like `/* isSecondaryIndexForward */` here and below.
___
*[`pkg/sql/rowenc/keyside/keyside_test.go` line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMvBw37NT4oow0__-k:-NSMvBw37NT4oow0__-l:b-kt22up) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/rowenc/keyside/keyside_test.go#L75)):*
> ```Go
> 
> 	// Run the property on JSON values specifically.
> 	properties.Property("roundtrip-json", prop.ForAll(
> ```

How is this different from `roundtrip` test case above? I'd expect that we'd have a different "datum generation function", but we're using the same `getDatumWithType`. For arrays case above we're including NULLs, so that's different.
___
*[`pkg/sql/rowenc/keyside/keyside_test.go` line 161 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMvi5A-5G_oMCsvLFt:-NSMvi5A-5G_oMCsvLFu:bf5tpe7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/rowenc/keyside/keyside_test.go#L161)):*
> ```Go
> 	))
> 
> 	properties.Property("order-preserving-json", prop.ForAll(
> ```

ditto: how is this different from `order-preserving` case?


<!-- Sent from Reviewable.io -->

2023-04-06 19:02 UTC, Shivs11 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index_multi_column` line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSB_dgSEgKD8FT1Od6W:-NSMwZmcErfT3wUo1Q1g:b-7i5xxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/2414bbadfb48015de9bc7444bc4379881d7c3f90/pkg/sql/logictest/testdata/logic_test/inverted_index_multi_column#L13)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

Currently waiting.
</blockquote></details>

Please ignore the comment above. Changes have been made.


<!-- Sent from Reviewable.io -->

2023-04-06 19:59 UTC, Shivs11 reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-:-NSMxnxECWhtAGngpPfl:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @mgartner, and @yuzefovich)

___
*[`pkg/sql/colencoding/key_encoding.go` line 202 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMoX578G6UWP3SFd75:-NSMy-Pv7aNsAz0TCbtM:bdlfnin) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/colencoding/key_encoding.go#L202)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this probably should be `errors.AssertionFailedf`.
</blockquote></details>

Hmm, yeah I agree. Changes have been made.
___
*[`pkg/sql/sem/tree/datum.go` line 3615 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMsDFgAfi36iUWRu7r:-NSMyBXJ7NQEEdp3PJiC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/sem/tree/datum.go#L3615)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: do `IsComposite implements the CompositeDatum interface.`.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/expression_index` line 644 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMw0kY3D1mRLCxGUhD:-NSMyEpw6xQMV8GDBaR3:b-80tlqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/logictest/testdata/logic_test/expression_index#L644)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it'd be good to add some EXPLAIN tests for the queries in this file to `execbuilder/testdata`.
</blockquote></details>

Sure!
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 948 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBVGDIDfEZLP7UVAVh:-NSN2kxTCiYExDB3BmDY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/json#L948)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: can you move these tests to a new file, like `json_index`. This file is mostly for basic JSON tests, not involving indexes.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 229 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMtvJe1LjOQ-SP57NO:-NSMyuXD8lE9BypXQsSh:bn42ayx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/opt/exec/execbuilder/testdata/json#L229)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe include `'1'::JSONB` to highlight the difference from `'1.00'::JSONB`? This will require introducing a non-unique secondary index on the json column.
</blockquote></details>

For sure. Done.
___
*[`pkg/sql/rowenc/index_encoding_test.go` line 176 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMuOkKBexsI24KsDrv:-NSMzrfV8U0QRxvxMmI_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/rowenc/index_encoding_test.go#L176)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: shouldn't this comment be a few lines above?
</blockquote></details>

Done.
___
*[`pkg/sql/rowenc/index_encoding_test.go` line 270 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMugISDj_SK9kJ-SEj:-NSN1HqKDe9spaXllLk1:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/rowenc/index_encoding_test.go#L270)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: add inlined comment like `/* isSecondaryIndexForward */` here and below.
</blockquote></details>

Done!
___
*[`pkg/sql/rowenc/keyside/keyside_test.go` line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMvBw37NT4oow0__-k:-NSN1cBVEDLTZ2PQILWD:b-cc2ksx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/rowenc/keyside/keyside_test.go#L75)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

How is this different from `roundtrip` test case above? I'd expect that we'd have a different "datum generation function", but we're using the same `getDatumWithType`. For arrays case above we're including NULLs, so that's different.
</blockquote></details>

Your question is valid. However, in the first case ("roundtrip"), we are calling `getDatumwithType` to generate random `Datums` for column types that are *also* generated randomly. While the JSON column type can be chosen in this case, I wanted to have an additional test case where the type of the column was in fact guaranteed. Thus, in the added test case, the datums are being generated randomly but all of them will be of the type `JSON`.
___
*[`pkg/sql/rowenc/keyside/keyside_test.go` line 161 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMvi5A-5G_oMCsvLFt:-NSN2T5BACFs3lpOnKBy:b-vdzsni) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/rowenc/keyside/keyside_test.go#L161)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

ditto: how is this different from `order-preserving` case?
</blockquote></details>

 The motivation was the same as described above.


<!-- Sent from Reviewable.io -->

2023-04-06 21:01 UTC, yuzefovich reviewed
> Reviewed 1 of 1 files at r7, 3 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @mgartner, and @Shivs11)

___
*[`pkg/sql/rowenc/keyside/keyside_test.go` line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMvBw37NT4oow0__-k:-NSNLVdP-LmRjuUzJa8k:bhduaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/rowenc/keyside/keyside_test.go#L75)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

Your question is valid. However, in the first case ("roundtrip"), we are calling `getDatumwithType` to generate random `Datums` for column types that are *also* generated randomly. While the JSON column type can be chosen in this case, I wanted to have an additional test case where the type of the column was in fact guaranteed. Thus, in the added test case, the datums are being generated randomly but all of them will be of the type `JSON`.
</blockquote></details>

But why is JSON special? You're right that in "roundtrip" case we first choose a random type that has key encoding, and then for that type we generate random datums, meaning that not every key-encodable type is exercised on each test run. However, when this test is run many times (and it does run many times as part of the CI), then eventually all key-encodable types, including now JSON, will be tested. That's the beauty of the randomized tests - you don't have to define separate cases for different combinations as long as your randomization explores enough of the testing space.

I'm not saying that we should definitely not add a separate case for JSONs. E.g. for arrays we did, but we also used a special datum generation function, different from the "roundtrip" case. But if we use the same `genDatumWithType` datum generation for JSON, then this test case is redundant.

In other words, we should either:
- use a different datum generation function for JSON, or
- remove this test case.


<!-- Sent from Reviewable.io -->

2023-04-06 22:26 UTC, Shivs11 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @mgartner, and @yuzefovich)

___
*[`pkg/sql/rowenc/keyside/keyside_test.go` line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSMvBw37NT4oow0__-k:-NSNeL6h6KTe5O2tUf1P:b-9a9kft) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c52400a04ecb4723cf2e59ce58fcd5474d564c/pkg/sql/rowenc/keyside/keyside_test.go#L75)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

But why is JSON special? You're right that in "roundtrip" case we first choose a random type that has key encoding, and then for that type we generate random datums, meaning that not every key-encodable type is exercised on each test run. However, when this test is run many times (and it does run many times as part of the CI), then eventually all key-encodable types, including now JSON, will be tested. That's the beauty of the randomized tests - you don't have to define separate cases for different combinations as long as your randomization explores enough of the testing space.

I'm not saying that we should definitely not add a separate case for JSONs. E.g. for arrays we did, but we also used a special datum generation function, different from the "roundtrip" case. But if we use the same `genDatumWithType` datum generation for JSON, then this test case is redundant.

In other words, we should either:
- use a different datum generation function for JSON, or
- remove this test case.
</blockquote></details>

Hmm I see. I think the point you made here: `That's the beauty of the randomized tests - you don't have to define separate cases for different combinations as long as your randomization explores enough of the testing space.` pretty much gives confidence that JSON as a column type will be selected and datums will be generated. My only worry and reasoning behind the addition of this test case was the fact that a randomized test *could* maybe not select the JSON column type. But I think your explanation is valid and I can go ahead and remove this case. 


<!-- Sent from Reviewable.io -->

2023-04-10 14:13 UTC, mgartner approved these changes
Very nice! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 26 files at r5, 12 of 14 files at r6, 1 of 1 files at r7, 3 of 5 files at r8, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-:-NSfVwRLD5akeVOQ9J2o:bup7q37)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi, @Shivs11, and @yuzefovich)

___
*[`pkg/sql/catalog/tabledesc/structured.go` line 718 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfNqnUCsr-JHan9_y5:-NSfNqnUCsr-JHan9_y6:bopiw48) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/catalog/tabledesc/structured.go#L718)):*
> ```Go
> 
> 		// Inverted indexes don't store composite values in the individual
> 		// paths present. The composite values will be differentiated in
> ```

nit: replace "differentiated" with "encoded"
___
*[`pkg/sql/opt/indexrec/hypothetical_table.go` line 48 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfOZRh-98VIvyqe4cN:-NSfOZRh-98VIvyqe4cO:bf5yurp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/indexrec/hypothetical_table.go#L48)):*
> ```Go
> 			// to be part of inverted indexes since they are also forward indexable.
> 			inverted := !(colinfo.ColumnTypeIsIndexable(lastKeyCol.DatumType()) &&
> 				lastKeyCol.DatumType().Family() != types.JsonFamily)
> ```

nit: easier to understand this as `!colinfo.ColumnTypeIsIndexable(...) || lastKeyCol.DatumType().Family() == types.JSON`
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 962 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBWCsr7ke_G_D6v6Hq:-NSfUv0a9N7Y7gjalpfj:b-25uz73) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/json#L962)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

I have added the test for composite types, as a subtest, below. Was there another reason why you wanted them to be added here?
</blockquote></details>

LGTM. I must have missed them the first time around. 
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 1251 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBXQhaDLG5BqvUL9oT:-NSfQcOF5pQ9hE9hfsth:beqiydh) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/json#L1251)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

Resolved by moving to a new file.
</blockquote></details>

I was suggesting they stay in this file, but either is fine.
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 1415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBZ89rE6weLy4r7bjo:-NSfQz6i4VUGP4L3k3lL:bglmwp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/json#L1415)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

The intention of these joins was to test them on indexed columns consisting `JSON`.  Won't this be relevant?
</blockquote></details>

Oh, because they use the key encoding of the JSON value to perform the join?
___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog` line 3383 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBZJtM7QdwEw9YKo9N:-NSfS-529Gt6TgKBFCxQ:b-gehd7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/pg_catalog#L3383)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

There seems to be more changes here than a re-ordering. I verified this by checking the file out from the master and comparing the results, which led to this conclusion.
</blockquote></details>

I see. This changed because there are now comparison operators for JSON. Sorry for the noise.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 272 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfSpcQAIjLsiKavYI3:-NSfSpcQAIjLsiKavYI4:bbqgbtv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/exec/execbuilder/testdata/json#L272)):*
> ```
> 
> query T
> EXPLAIN SELECT j from d where j->'a' = '"b"' ORDER BY a
> ```

nit: None of the tests you added in this section need an `ORDER BY` clause because the results aren't part of the output - only the query plan is. If you remove it then the`sort` operator will be removed and you'll eliminate a few lines of tests.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 325 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfSOdJCXSec2f5X-y6:-NSfSOdJCXSec2f5X-y7:bs9x1ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/exec/execbuilder/testdata/json#L325)):*
> ```
> 
> query T
> EXPLAIN SELECT j from d where j->'a' = '"a"' ORDER BY a
> ```

nit: This looks like a duplicate of the first test: `EXPLAIN SELECT j from d where j->'a' = '"b"' ORDER BY a`.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 342 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfSVBd2Bn8PulFFbln:-NSfSVBd2Bn8PulFFblo:b-ynsbd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/exec/execbuilder/testdata/json#L342)):*
> ```
> 
> query T
> EXPLAIN SELECT j from d where j->'a' = '"hello"' ORDER BY a
> ```

nit: This also looks like a duplicate of the first test - changing the constant value in the query filter isn't all that interesting for this type of test.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 387 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfSn827Bgh9EO_6mIQ:-NSfSn827Bgh9EO_6mIR:barat5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/exec/execbuilder/testdata/json#L387)):*
> ```
> 
> query T
> EXPLAIN SELECT j from d where j->'a' = '"c"' AND j->'json' = '"d"' ORDER BY a
> ```

nit: also looks like a duplicate


<!-- Sent from Reviewable.io -->

2023-04-10 19:59 UTC, yuzefovich approved these changes
Nice work! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 26 files at r5, 1 of 5 files at r8, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-:-NSgk8vT0Wr23YUHjUZI:b-8ewgme)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @fqazi and @Shivs11)

___
*[`pkg/sql/sem/tree/datum.go` line 3658 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSgfDyH3qEQFkA2z9Sy:-NSgfDyH3qEQFkA2z9Sz:bw52tcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/sem/tree/datum.go#L3658)):*
> ```Go
> 			}
> 		} else if err != nil {
> 			panic(errors.AssertionFailedf("could not receive an ObjectKeyIterator"))
> ```

nit: let's not lose the original `err` here - use `errors.NewAssertionErrorWithWrappedErrf`.
___
*[`pkg/sql/logictest/testdata/logic_test/json_index` line 3 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSggYD327GEwy0tAHkt:-NSggYD327GEwy0tAHku:b6ezqp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/logictest/testdata/logic_test/json_index#L3)):*
> ```
> # Add JSON columns as primary index.
> statement ok
> DROP TABLE IF EXISTS t;
> ```

nit: at the top of the logic test we don't have any tables, so this DROP is not needed.
___
*[`pkg/sql/logictest/testdata/logic_test/json_index` line 311 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSghS7n2V88rjpTFeHk:-NSghS7n2V88rjpTFeHl:b-vdvc9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/logictest/testdata/logic_test/json_index#L311)):*
> ```
> {"e": {"f": {"g": 1}}, "f": [1, 2, 3]}
> 
> # Ensure that we can order by JSONS without any indexes.
> ```

nit: `s/JSONS/JSONs/g` and below.
___
*[`pkg/sql/logictest/testdata/logic_test/json_index` line 478 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSgiRzH4dNB7ykKWu5v:-NSgiRzH4dNB7ykKWu5w:b71fuxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/logictest/testdata/logic_test/json_index#L478)):*
> ```
> 
> query T rowsort
> SELECT t1.x FROM t1 INNER HASH JOIN t2 ON t1.x = t2.x
> ```

nit: similar to Marcus' comment above, I'm also confused by this - can you provide more context how JSON being forward-indexable changes the hash join execution? I agree that testing merge joins (they do require ordering from the index) and lookup joins (they do need to lookup into JSON forward index) makes sense, but I don't see why hash join would be mentioned here. Same goes for GROUP BY below.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 185 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSgjC2a-g68zZxgRXdk:-NSgjC2a-g68zZxgRXdl:b-5kvgf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/exec/execbuilder/testdata/json#L185)):*
> ```
>       table: t@t_pkey
>       spans: FULL SCAN
> ```

nit: maybe add a couple of tests cases with `WHERE x IN (...)` with multiple values to show that multiple spans can be generated.


<!-- Sent from Reviewable.io -->

2023-04-10 23:15 UTC, Shivs11 reviewed
Thank you for your reviews! Have made the final changes too and shall be requesting `bors` for a merge!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-:-NShRxmu8d36UmC88NBb:biqezij)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @fqazi, @mgartner, and @yuzefovich)

___
*[`pkg/sql/catalog/tabledesc/structured.go` line 718 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfNqnUCsr-JHan9_y5:-NShKVT28X5P_gGpnfFY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/catalog/tabledesc/structured.go#L718)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: replace "differentiated" with "encoded"
</blockquote></details>

Done.
___
*[`pkg/sql/opt/indexrec/hypothetical_table.go` line 48 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfOZRh-98VIvyqe4cN:-NShKjqFEhLeiyOv40VG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/indexrec/hypothetical_table.go#L48)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: easier to understand this as `!colinfo.ColumnTypeIsIndexable(...) || lastKeyCol.DatumType().Family() == types.JSON`
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/datum.go` line 3658 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSgfDyH3qEQFkA2z9Sy:-NShKye5-nee7eFBcjpk:b3wvk4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/sem/tree/datum.go#L3658)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: let's not lose the original `err` here - use `errors.NewAssertionErrorWithWrappedErrf`.
</blockquote></details>

I agree. Changes have been made.
___
*[`pkg/sql/logictest/testdata/logic_test/json` line 1415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSBZ89rE6weLy4r7bjo:-NShNO1_0_5CMMlop9fl:b90g3qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/890ba2f057edd6c70f977f8349460faaf5277a6e/pkg/sql/logictest/testdata/logic_test/json#L1415)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Oh, because they use the key encoding of the JSON value to perform the join?
</blockquote></details>

Responded below.
___
*[`pkg/sql/logictest/testdata/logic_test/json_index` line 3 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSggYD327GEwy0tAHkt:-NShP30a0_f4Ii3gJ4Od:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/logictest/testdata/logic_test/json_index#L3)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: at the top of the logic test we don't have any tables, so this DROP is not needed.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/json_index` line 311 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSghS7n2V88rjpTFeHk:-NShRWm2-_phCNQwZSjE:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/logictest/testdata/logic_test/json_index#L311)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/JSONS/JSONs/g` and below.
</blockquote></details>

Done!
___
*[`pkg/sql/logictest/testdata/logic_test/json_index` line 478 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSgiRzH4dNB7ykKWu5v:-NShLs8h59UOb2v9Vi0W:bceztt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/logictest/testdata/logic_test/json_index#L478)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: similar to Marcus' comment above, I'm also confused by this - can you provide more context how JSON being forward-indexable changes the hash join execution? I agree that testing merge joins (they do require ordering from the index) and lookup joins (they do need to lookup into JSON forward index) makes sense, but I don't see why hash join would be mentioned here. Same goes for GROUP BY below.
</blockquote></details>

Yes, the reasoning provided by you @yuzefovich (about lookup joins and merge joins requiring the look up and ordering respectively) was the main reason behind these tests. However, I was also under the assumption that hash joins and GROUP BY clauses would require JSON to be key encoded. This was verified by me by just running the join and the clause on my local binary. Sorry for their inclusion! Changes have been made.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 185 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSgjC2a-g68zZxgRXdk:-NShPn7LDvBSJ9RdfCCE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/exec/execbuilder/testdata/json#L185)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe add a couple of tests cases with `WHERE x IN (...)` with multiple values to show that multiple spans can be generated.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 272 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfSpcQAIjLsiKavYI3:-NShQYJo7IVGOBITaD8f:b-cl4os4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/exec/execbuilder/testdata/json#L272)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: None of the tests you added in this section need an `ORDER BY` clause because the results aren't part of the output - only the query plan is. If you remove it then the`sort` operator will be removed and you'll eliminate a few lines of tests.
</blockquote></details>

Hmm, I see your point. The `ORDER BY` clause in them has been removed.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 325 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfSOdJCXSec2f5X-y6:-NShQpiG35bzBHlkYb-l:b7ttvvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/exec/execbuilder/testdata/json#L325)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: This looks like a duplicate of the first test: `EXPLAIN SELECT j from d where j->'a' = '"b"' ORDER BY a`.
</blockquote></details>

Changed to a JSON number instead.



_Code quote:_
```
EXPLAIN SELECT j from d where j->'a' = '"a"' ORDER BY a
```
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 342 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfSVBd2Bn8PulFFbln:-NShQx7DEgfsjyH2ZiQP:b-5ennm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/exec/execbuilder/testdata/json#L342)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: This also looks like a duplicate of the first test - changing the constant value in the query filter isn't all that interesting for this type of test.
</blockquote></details>

Altered.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/json` line 387 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/99275#-NSfSn827Bgh9EO_6mIQ:-NShR9XA3qN0VBdqFlAp:b-nwu5ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc619a724fbfd2eceba0730e1d05620dd39be533/pkg/sql/opt/exec/execbuilder/testdata/json#L387)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: also looks like a duplicate
</blockquote></details>

Altered to demonstrate different types of JSON values (JSON arrays and [...]

2023-04-11 15:02 UTC, Shivs11 commented
bors r+

2023-04-11 15:50 UTC, Shivs11 commented
bors retry

2023-04-11 16:23 UTC, rickystewart commented
bors ping

2023-04-11 16:45 UTC, rickystewart commented
bors ping

2023-04-11 16:45 UTC, rickystewart commented
bors r+

2023-04-11 18:37 UTC, merged