ui: drop index with space
cockroachdb/cockroach pull request #99690
Opened 2023-03-27 17:07 UTC by maryliag

Previously, if the index had a space on its name,
it would fail to drop.
This commit adds quotes so it can be executed.

Fixes #97988

Schema Insights
https://www.loom.com/share/04363b7f83484b5da19c760eb8d0de21

Table Details page
https://www.loom.com/share/1519b897a14440ddb066fb2ab03feb2d

Release note (bug fix): Index recommendation to DROP an index that have a space on its name can now be properly executed.

2023-03-28 13:49 UTC, THardy98 requested changes
We can use the `safesql` package here, take a look at `Identifier`, `Join` and `QualifiedIdentifier`. Might need a bit of tinkering because of the `@` in the string.

2023-03-29 13:18 UTC, maryliag reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99690#-:-NRhWLsG1qcqlbbnn3BP:bb6un1j)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-03-29 13:27 UTC, THardy98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99690#-:-NRhYN2J2HXBoFG7MwBO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2023-03-30 01:00 UTC, maryliag commented
bors r+

2023-03-30 05:35 UTC, merged