ui: introduce foundations to support configurable timezone display
cockroachdb/cockroach pull request #99848
Opened 2023-03-28 19:25 UTC by zachlite

This commit adds the foundational dependencies and components needed to display timestamps in DB console in a user's preferred timezone.

Introduced:
- A dependency on `moment-timezone` in DB console and Cluster UI.
- A cluster setting: `ui.display_timezone`.
- A timezone context with a default value of "UTC". This enables backwards-compatability for cluster-ui components. No changes in cloud are needed, and cluster-ui components will continue to display timestamps in UTC.
- A context provider at the top of DB console's component tree.

Part of: https://github.com/cockroachdb/cockroach/issues/40419
Epic: https://cockroachlabs.atlassian.net/browse/CRDB-24406
Release note: None

2023-03-28 19:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/99848)
<!-- Reviewable:end -->

2023-03-29 06:45 UTC, koorosh reviewed
> Reviewed 150 of 150 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99848)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRg4-95D21Pl6VJnlMw:-NRg4-962NVRy4W9IwuP:b-fntxms) (no related file):*
LGTM in general! I like the idea of using context to propagate selected timezone! 

___
___
*[`pkg/ui/workspaces/cluster-ui/src/contexts/timezoneContext.tsx` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRg5pg6BHLr2ImV-d7i:-NRg5pg6BHLr2ImV-d7j:b-tjivx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb9fcd4dec4ec7954ca664b06a249381b7cabb9/pkg/ui/workspaces/cluster-ui/src/contexts/timezoneContext.tsx#L14)):*
> ```XML
> import { createContext, useContext } from "react";
> 
> export const TimezoneContext = createContext<string>("UTC");
> ```

Do we need to set default timezone for `moment` as described here: https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/
```
moment.tz.setDefault("UTC");
```
___
*[`pkg/ui/workspaces/db-console/src/contexts/timezoneProvider.tsx` line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRePYXC-uiU3CmkLnzZ:-NRePYXD1n9s02bUCcEB:bifa40p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb9fcd4dec4ec7954ca664b06a249381b7cabb9/pkg/ui/workspaces/db-console/src/contexts/timezoneProvider.tsx#L24)):*
> ```XML
>   const dispatch = useDispatch();
>   const settings = useSelector(selectClusterSettings);
>   useEffect(() => {
> ```

It is safe to dispatch `refreshSettings()` action on initial component load without validation for `null`.
`refreshSettings()` will be ignored if it is called within some interval and cached value returned instead. And calling without validation would guarantee that requested value is not invalidated.


<!-- Sent from Reviewable.io -->

2023-03-29 12:06 UTC, j82w commented
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRhFPj30LpCf6Hua0M-):*
Can you add a loom video showing the new functionality? Also please add a release note since this a new feature for users.


<!-- Sent from Reviewable.io -->

2023-03-29 12:11 UTC, j82w commented
*[`pkg/ui/workspaces/db-console/package.json` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRhGpUv03PTn44rjx-j:-NRhGpUv03PTn44rjx-k:bnvp22c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb9fcd4dec4ec7954ca664b06a249381b7cabb9/pkg/ui/workspaces/db-console/package.json#L38)):*
> ```JSON
>     "mini-create-react-context": "^0.3.2",
>     "moment": "^2.19.3",
>     "moment-timezone": "^0.5.42",
> ```

Do new packages need to go through any approval process to verify the license?


<!-- Sent from Reviewable.io -->

2023-03-29 18:08 UTC, zachlite reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99848)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @koorosh)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRg4-95D21Pl6VJnlMw:-NRiY2ol2QEiEfSjrgwn:b4c9lyr) (no related file):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

LGTM in general! I like the idea of using context to propagate selected timezone! 
</blockquote></details>

:thumbsup: 

___
___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRhFPj30LpCf6Hua0M-):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Can you add a loom video showing the new functionality? Also please add a release note since this a new feature for users.
</blockquote></details>

There's no new functionality here. This is only laying the groundwork for user-facing changes.
___
*[`pkg/ui/workspaces/cluster-ui/src/contexts/timezoneContext.tsx` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRg5pg6BHLr2ImV-d7i:-NRiPn9Z-4X0jFAwOh9W:bbwvnxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb9fcd4dec4ec7954ca664b06a249381b7cabb9/pkg/ui/workspaces/cluster-ui/src/contexts/timezoneContext.tsx#L14)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Do we need to set default timezone for `moment` as described here: https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/
```
moment.tz.setDefault("UTC");
```

</blockquote></details>

I wish it could be this easy! But there's so many places where we call `moment.utc` that I think it would be easier to leave `moment.tz.setDefault` out of the equation. Otherwise, we'd have half the codebase magically controlled by `setDefault`, and half not controlled. I think that would be confusing.
___
*[`pkg/ui/workspaces/db-console/package.json` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRhGpUv03PTn44rjx-j:-NRiJGn8AOqK2vpuxlFB:b-5jam2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb9fcd4dec4ec7954ca664b06a249381b7cabb9/pkg/ui/workspaces/db-console/package.json#L38)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Do new packages need to go through any approval process to verify the license?
</blockquote></details>

`moment-timezone` is MIT licensed, and the license is distributed with the downloaded package, so I think we're good!
___
*[`pkg/ui/workspaces/db-console/src/contexts/timezoneProvider.tsx` line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRePYXC-uiU3CmkLnzZ:-NRiJN7r3hlO5Rqr5za1:b-fimbuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb9fcd4dec4ec7954ca664b06a249381b7cabb9/pkg/ui/workspaces/db-console/src/contexts/timezoneProvider.tsx#L24)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

It is safe to dispatch `refreshSettings()` action on initial component load without validation for `null`.
`refreshSettings()` will be ignored if it is called within some interval and cached value returned instead. And calling without validation would guarantee that requested value is not invalidated.
</blockquote></details>

Cool! Updated.


<!-- Sent from Reviewable.io -->

2023-03-29 21:07 UTC, xinhaoz commented on pkg/ui/workspaces/cluster-ui/src/contexts/timezoneContext.tsx
> +export function WithTimezone(Component: any) {
nit:Isn't there a react component type? I personally prefer to avoid `any` wherever possible.

2023-04-02 18:02 UTC, koorosh reviewed
> Reviewed 1 of 1 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99848)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @xinhaoz, and @zachlite)

___
*[`pkg/ui/ui.go` line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NS25DYUArvI6bTSQKoM:-NS25DYUArvI6bTSQKoN:b-oi6b4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c3ab5a6a5969850d47da13ac677fa8dc2b48c4/pkg/ui/ui.go#L41)):*
> ```Go
> )
> 
> var _ = settings.RegisterEnumSetting(
> ```

How this setting can be changed to use non-default value?
___
*[`pkg/ui/workspaces/cluster-ui/src/contexts/timezoneContext.tsx` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRg5pg6BHLr2ImV-d7i:-NS22BnDAzE4BNPsRQfw:b-dxcbu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bb9fcd4dec4ec7954ca664b06a249381b7cabb9/pkg/ui/workspaces/cluster-ui/src/contexts/timezoneContext.tsx#L14)):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

I wish it could be this easy! But there's so many places where we call `moment.utc` that I think it would be easier to leave `moment.tz.setDefault` out of the equation. Otherwise, we'd have half the codebase magically controlled by `setDefault`, and half not controlled. I think that would be confusing.
</blockquote></details>

Makes sense!


<!-- Sent from Reviewable.io -->

2023-04-03 21:44 UTC, maryliag reviewed
> Reviewed 138 of 150 files at r1, 1 of 1 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99848)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @koorosh, @xinhaoz, and @zachlite)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NRg4-95D21Pl6VJnlMw:-NS83x191run5HLnzSqf:be3pdl6) (no related file):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Nice foundation! Left a few nits

___
___
*[`pkg/ui/ui.go` line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NS81d1S6ILUk67Pp6Ls:-NS81d1S6ILUk67Pp6Lt:b-36kat6) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c3ab5a6a5969850d47da13ac677fa8dc2b48c4/pkg/ui/ui.go#L38)):*
> ```Go
> const (
> 	utc int64 = iota
> 	americaNewYork
> ```

Is there a requirement to use NY? Asking because several other places use this timezone and is common to called EST time, so maybe you should go with that.
___
*[`pkg/ui/workspaces/cluster-ui/src/util/format.ts` line 195 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NS82gz-4dvVwFEfIgZC:-NS82gz-4dvVwFEfIgZD:b-gglw9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c3ab5a6a5969850d47da13ac677fa8dc2b48c4/pkg/ui/workspaces/cluster-ui/src/util/format.ts#L195)):*
> ```XML
> export const DATE_FORMAT_24_UTC = "MMM DD, YYYY [at] H:mm UTC";
> export const DATE_WITH_SECONDS_FORMAT_24_UTC = "MMM DD, YYYY [at] H:mm:ss UTC";
> export const DATE_WITH_SECONDS_FORMAT_24_TZ = "MMM DD, YYYY [at] H:mm:ss z";
> ```

should you also be creating one for DATE_FORMAT_24_TZ (without the seconds)?
and then your function below can select with or without seconds
___
*[`pkg/ui/workspaces/db-console/src/contexts/timezoneProvider.tsx` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NS832dq1vsC6tlPOuQm:-NS832dr8hoogNhq_FGq:b-b5goa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c3ab5a6a5969850d47da13ac677fa8dc2b48c4/pkg/ui/workspaces/db-console/src/contexts/timezoneProvider.tsx#L21)):*
> ```XML
> 
> export const TimezoneProvider = (props: any) => {
>   // Refresh cluster settings if needed
> ```

very nit: period at end of comments
___
*[`pkg/ui/workspaces/db-console/src/redux/clusterSettings/clusterSettings.selectors.ts` line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NS83JWk6QQyaI5XH4ol:-NS83JWk6QQyaI5XH4om:b-8ae2iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c3ab5a6a5969850d47da13ac677fa8dc2b48c4/pkg/ui/workspaces/db-console/src/redux/clusterSettings/clusterSettings.selectors.ts#L30)):*
> ```XML
>     }
>     const setting = settings["ui.display_timezone"];
>     return setting ? setting.value : "UTC";
> ```

you can combine these two lines as `return settings["ui.display_timezone"]?.value || "UTC"`


<!-- Sent from Reviewable.io -->

2023-04-03 23:27 UTC, zachlite reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99848)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @koorosh, @maryliag, and @xinhaoz)

___
*[`pkg/ui/ui.go` line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NS81d1S6ILUk67Pp6Ls:-NS8NgAW99zO6YN_s3ey:bmbsg6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c3ab5a6a5969850d47da13ac677fa8dc2b48c4/pkg/ui/ui.go#L38)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Is there a requirement to use NY? Asking because several other places use this timezone and is common to called EST time, so maybe you should go with that.
</blockquote></details>

`America/New_York` gives the actual local time regardless of whether daylight savings time is being observed.

Right now, NYC is observing `EDT` (eastern daylight time)

And I figured when we want to support more timezones, we can add them to the list and ensure that the timezone library includes the proper data.
___
*[`pkg/ui/ui.go` line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NS25DYUArvI6bTSQKoM:-NS8P0S471KrbgVMplfH:b-r49imr) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c3ab5a6a5969850d47da13ac677fa8dc2b48c4/pkg/ui/ui.go#L41)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

How this setting can be changed to use non-default value?
</blockquote></details>

UTC: `SET CLUSTER SETTING ui.display_timezone = 0`; 
America/New_York: `SET CLUSTER SETTING ui.display_timezone = 1`;
___
*[`pkg/ui/workspaces/cluster-ui/src/util/format.ts` line 195 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NS82gz-4dvVwFEfIgZC:-NS8PN5O9_1ZjdZ889VH:b-osq4d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c3ab5a6a5969850d47da13ac677fa8dc2b48c4/pkg/ui/workspaces/cluster-ui/src/util/format.ts#L195)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

should you also be creating one for DATE_FORMAT_24_TZ (without the seconds)?
and then your function below can select with or without seconds
</blockquote></details>

Yes. I clean all of these up in my forthcoming PR where I add the user-facing changes.
I wanted to keep the diff as small as possible here.
___
*[`pkg/ui/workspaces/db-console/src/contexts/timezoneProvider.tsx` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NS832dq1vsC6tlPOuQm:-NS8PV9SDRyfo9D0Hm0Z:b-bqivcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c3ab5a6a5969850d47da13ac677fa8dc2b48c4/pkg/ui/workspaces/db-console/src/contexts/timezoneProvider.tsx#L21)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

very nit: period at end of comments
</blockquote></details>

Will fix.
___
*[`pkg/ui/workspaces/db-console/src/redux/clusterSettings/clusterSettings.selectors.ts` line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-NS83JWk6QQyaI5XH4ol:-NS8PXvNACv_P-Ct6gFU:b-bqivcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c3ab5a6a5969850d47da13ac677fa8dc2b48c4/pkg/ui/workspaces/db-console/src/redux/clusterSettings/clusterSettings.selectors.ts#L30)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you can combine these two lines as `return settings["ui.display_timezone"]?.value || "UTC"`
</blockquote></details>

Will fix.


<!-- Sent from Reviewable.io -->

2023-04-04 13:41 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-:-NSBV4-D0Ra1Z3hgNag3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w, @koorosh, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2023-04-04 13:42 UTC, maryliag approved these changes
Looking great!
As long as tests are passing <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99848#-:-NSBV8sH2lDlVQsD6-Co:b517d06)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w, @koorosh, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2023-04-04 18:12 UTC, sjbarag requested changes
Watch out! Adding `moment-timezone` adds ~950KB to the total bundle size of cluster-ui alone: https://bundlephobia.com/package/moment-timezone@0.5.43 (and confirmed with both webpack's stdout warning and `du -k dist/js/main.js` before and after this change).

We'll likely want to pull in `moment-timezone-data-webpack-plugin` to limit the number of years of timezone data we include in the bundle: https://momentjs.com/timezone/docs/#/use-it/webpack/  I can't tell how many years are included by default, but it's quite likely more than 60 years considering that the 1970-2030 time range is called out explicitly as "not the full data file".

2023-04-05 15:59 UTC, sjbarag reviewed
Your webpack changes look good! Thanks for vendoring the new dependencies too :) Just one question about the number of years included!

2023-04-05 15:59 UTC, sjbarag commented on pkg/ui/ui.go
> +)
Just for my knowledge — does this imply that only `Etc/UTC` and `America/New_York` are supported, and other timezones aren't possible? I think I'd expect a much longer list than just UTC + EST, but perhaps this is just the starting point 🤔

2023-04-05 15:59 UTC, sjbarag commented on pkg/ui/workspaces/cluster-ui/webpack.config.js
> +        startYear: 2021,
I can't find an answer reading through the source yet — how many years does this include if we only specify `startYear`?

2023-04-05 16:29 UTC, sjbarag commented on pkg/ui/workspaces/cluster-ui/webpack.config.js
> +        startYear: 2021,
`currentYear + 10` is probably safe and not super heavy! It gives us quite a bit of buffer beyond the 3-version support window.

2023-04-05 17:44 UTC, sjbarag approved these changes

2023-04-05 17:45 UTC, sjbarag commented
Thanks for the quick fixes, @zachlite!

2023-04-10 19:24 UTC, merged